### ISSUE TITLE
Deal History bug

### ISSUE THREAD

**Issue by shaunfitz** [LoneGazebo/Community-Patch-DLL#10003]
The deal history screen under diplomacy is bugged. the contents of the deals between you and other civs are always empty. This is a bug with the community patch only. The vanilla version works fine. Go have a look yourself you will see when you make deals with other civs the details are not recorded in this screen. This is a problem with the community core patch itself I haven't tested with the full patch Vox.Populi.3.7.8.

Thanks
Shaun

**Comment by n-core** [comment]
It's hard to debug without additional contexts such as screenshots, log files, etc.
Not many people within the dev team play on CP only, so there are many bugs in it.

**Comment by shaunfitz** [comment]
Ja its easy just load up a game and trade with a civ. then go look at the deal history screen. Its a pretty significant bug as that is the core patch for all other mods, I am sure this bug is with the full patch Vox.Populi.3.7.8 as well haven't tested though. I think CP is way better than the full patch as it keeps with the core experience of what the game was meant to be. its way better.

**Comment by Tesla101a** [comment]
I have seen this bug as well in CP only, I've been meaning to gather the logs and screenshots, will do that today if I can.

**Comment by n-core** [comment]
> Its a pretty significant bug as that is the core patch for all other mods, I am sure this bug is with the full patch Vox.Populi.3.7.8 as well haven't tested though. I think CP is way better than the full patch as it keeps with the core experience of what the game was meant to be. its way better.

Under the hood, VP has its own parts of code and functions. CP =/= VP or vice versa. VP has extended functionalities that don't exist in bare CP.
If this bug occurs in VP, I'm sure there are many people already reported it.

Also, CP doesn't keep some of the core experience because it's simply written in borked code or not AI-friendly.

**Comment by shaunfitz** [comment]
Ok good, thanks

**Comment by axatin** [comment]
Will be fixed in the next version.

**Comment by shaunfitz** [comment]
ok great thanks

**Comment by shaunfitz** [comment]
ok great thanks
