### ISSUE TITLE
workers building improvements outside city range (no resources)

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10014]
v 3.7.7

not a big deal i guess but this seems to be new? is it intended?

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/0944cd31-ffbd-4054-917b-266336e2d326)

**Comment by APLion-nsk** [comment]
Has Arabia taken tradition? If so, the 4-distance ring is inside city range

**Comment by ilteroi** [comment]
oh, didn't consider that
