### ISSUE TITLE
AI won't take acceptable deal

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10015]
v 3.7.7

i accidentally declined a deal the arabians offered to me (2 iron for 4 gold iirc). so i wanted to offer the same deal myself, but they won't even take my iron for free!

what's more, the deal value is supposedly acceptable:

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/fb3fe552-8686-4e87-aa73-1f5605663e80)

(i offered 4 here but it's independent of the number)

**Comment by axatin** [comment]
If you click on "Propose", they should still take it. They only don't add something to the list when you ask them for something in exchange. The text should be changed.

If they offer gold for 2 iron, they should also offer some for 4 iron? Do you have a savegame?

**Comment by axatin** [comment]
Fixed the AI rejecting acceptable deals. If you encounter it again that the AI gives less if you offer more resources, make a new issue please.
