### ISSUE TITLE
Impassable Feature Promotion Override Bug

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1001]
Apologies if this has already been brought up, as I faintly recall something to do with the impassable terrain system being raised, however, I wanted to make a note anyway. It appears that the UnitPromotions_Features/PassableTech column no longer allows a promotion to grant units the ability to move across otherwise impassable terrain/features. Specifically, in ExCE, my Jungle Immunity promotion no longer allows units to cross Jungle prior to discovering Optics, when it is otherwise impassable.

**Comment by LoneGazebo** [comment]
Sounds like a flaw in the plot rewrite. Ilteroi should be able to fix.

**Comment by Iamblichos** [comment]
I only notice this happening from loading a save

**Comment by ilteroi** [comment]
this is the relevant piece of code

	if(enterPlot.getFeatureType() != NO_FEATURE)  
	{
		// assume that all units can use roads and rails
		if(isFeatureImpassable(enterPlot.getFeatureType()) && enterPlot.getRouteType() == NO_ROUTE)
		{
			// Check all Promotions to see if this Unit has one which allows Impassable movement with a certain Tech
			if(m_Promotions.GetAllowFeaturePassable(enterPlot.getFeatureType()))
				return true;
		}
	}

so i can't really explain that. maybe it's time to install ExCE :)

**Comment by JFDaly** [comment]
A [screenshot](http://i.imgur.com/8wn38Mu.jpg) of the issue. Even though the Archer has the Jungle Immunity promotion, Jungle is still blocked. And the UnitPromotions_Features is definitely still set up correctly, as it shows using SQLite Manager.

**Comment by ilteroi** [comment]
hmm. i cannot reproduce in the latest version. might have been fixed along with the ocean issues. can you confirm with the latest hotfix version from the forum?

btw: nothing in the description of the jungle immunity promotions says it's supposed to grant passability to jungles. neither does uncharted territory say so. but both work.

**Comment by JFDaly** [comment]
I still inexplicably cannot cross Jungle with the promotion.

**Comment by ilteroi** [comment]
ok this is where it gets interesting. last time i used cpp full + exce. everything was good. just retried with cp base + exce, now it reproduces

**Comment by ilteroi** [comment]
ok got it - should be included in the next release

**Comment by JFDaly** [comment]
Thank you. Appreciate the investigation ilteroi.
