### ISSUE TITLE
Game hangs or freezes during barbarian turn 12/18

### ISSUE THREAD

**Issue by aht820** [LoneGazebo/Community-Patch-DLL#1002]
I'm using the 12/18 version with the hot fix. My game either freezes or hangs during the barb turn. I've left it for about 10 min before force quitting the game. I then reloaded and it happened at the same point. I'm using the full version and E&D and a few of Whowards mods.

**Comment by ilteroi** [comment]
please try to narrow it down a bit - does it happen with CPP only as well? E&D is known to be buggy.

**Comment by aht820** [comment]
I might be related to E&D. I've played a game without it and it hasnt hung up yet.
