### ISSUE TITLE
Some trouble with Unit:SetConversionStrength() and Unit:SetSpreadsLeft()

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1003]
I'm guessing this is a case of misunderstanding how they're supposed to work, however, I'm having some trouble. Whenever I invoke these in Firetuner, the value set will correctly apply to a specified unit. However, when trying to do so in a Lua function (from unit created, specifically), it doesn't - all the correct variables register (the unit, the value, etc.), they just don't do anything when passed in SetConversionStrength()/SetSpreadsLeft().

So, is there something that could explain why it would work in Firetuner but not in a Lua function?

Thanks for any ideas.

**Comment by JFDaly** [comment]
By accident, I discovered that these functions will work on units spawned via InitUnit(). So I'm guessing Units purchased with Faith are somewhy spawned differently. So, I think I have a workaround until this can be properly addressed (if at all).

**Comment by LoneGazebo** [comment]
Well, the values are set on spawn, and I'm not exactly sure how they function discretely in the DLL. I'll take a look.

G

**Comment by LoneGazebo** [comment]
I've looked at this and I can't see any reason why it isn't working. Any updates on this on your end?

**Comment by JFDaly** [comment]
Still didn't work on purchase last I tried. I resolved to use SerialEventUnitCreated(), which works well enough, albeit a little less cleanly. So if you can't figure it, then it's no problem.

**Comment by LoneGazebo** [comment]
I think what happens is that the construction model for units has to occur 'naturally' or it may mess up (as the religion construction is destroyed if default/empty).

G
