### ISSUE TITLE
CTD on turn start (3.7.11)

### ISSUE THREAD

**Issue by yamlime** [LoneGazebo/Community-Patch-DLL#10034]
_1. Mod Version (X.Y.Z). Current Version: 3.7.11_

-Version 3.7.11

_2. DirectX Version_

-DX 10 & 11

_3. List of Other Mods_

-No other mods, just VP without EUI

_4. Describe the Issue_

-Game Crashes at the beginning of turn, it is a multiplayer game. I believe the issue is that the world council starts on the turn that the game crashes, but am not possitive

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[SaveGame.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12229754/SaveGame.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12229857/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12229870/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

-Game Crashes on turn 471

_9. Screenshots of the Issue (Optional)_

**Comment by seroperson** [comment]
@yamlime can you attach used modpack please? Sorry for such a late response.
