### ISSUE TITLE
CTD during end of turn

### ISSUE THREAD

**Issue by vetox20** [LoneGazebo/Community-Patch-DLL#10032]
3.7.11

![Mods](https://github.com/LoneGazebo/Community-Patch-DLL/assets/82966157/84b98a52-1136-4136-9439-b4f04316200d)

Describe the Issue_
Selecting next turn on turn , once it passes to Netherlands, CTD.

_8. Steps to reproduce the Issue (Optional)_
Once at turn 240, click next turn.
[Save_Logs_DMP.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12217896/Save_Logs_DMP.zip)

Edit: This is new as of 3.7.11, no CTD in 3.7.10 during many games.

**Comment by axatin** [comment]
Same as #10023, already fixed
