### ISSUE TITLE
City growth while building settlers

### ISSUE THREAD

**Issue by ChristosLabrou** [LoneGazebo/Community-Patch-DLL#10030]
_1. Mod Version (X.Y.Z). Current Version: 3.7.11_
VP EUI 3.7.11

_3. List of Other Mods_
InGameEditor for VP (to speed up process of reproducing)
(*Note*: Discovered it while playing with more mods but replicated it in vanilla VP)

_4. Describe the Issue_
While building a settler it is possible for a city to grow if it had maximum food already

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12212939/saves.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_\

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12212902/Logs.zip)

_8. Steps to reproduce the Issue (Optional)_
- Step 1: Have a city eligible to build a settler.
- Step 2: Toggle on 'Avoid Growth' and have the city hit the food limit.
- Step 3: Start building a settler and toggle off 'Avoid Growth'

The result is that it gains a pop while still building a settler

_9. Screenshots of the Issue (Optional)_
Before (turn 3)
![20230731110845_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/34106033/79ce3ddf-be98-4ebc-a085-6b94f1149f5c)
After (turn 4)
![20230731110856_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/34106033/7c1c3a6d-ca24-4d5e-a166-2a600d49882b)

**Comment by LessRekkless** [comment]
at first glance, I don't see a problem with this.
