### ISSUE TITLE
Automated worker road building

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1004]
OP by Funak: "Automated workers tend to stack up and try to improve the same tile(even though they can't) especially when building roads. I had 5 workers on the same tile trying to build one road for 4 turns then all 5 moved to the next tile and starting building one road. "

I've noticed that the AI tends to clump their workers when building roads as well.

**Comment by ilteroi** [comment]
hmm. just took a look, is it the case that it only happens outside of your owned territory?

**Comment by ilteroi** [comment]
no matter. should be fixed
