### ISSUE TITLE
Vassal state achievable thru trade bug

### ISSUE THREAD

**Issue by dananichev** [LoneGazebo/Community-Patch-DLL#1005]
Maybe it's somehow related to difficulty, but i doubt it. Anyways, difficulty King/Prince.
Plus, i'm using multiplayer version of this mod. 

This issue is similar to the issue with gold in Civ 3 (you were able to ask crazy amout of gold in Civ 3 from any computer-controlled CIV).

Steps to 'vassal-scam' offer:
1. Computer controlled CIV must have at least couple of luxury resources (depends on current era i suppose)
2. Open trade-dialog with CIV
3. From this dialog choose:

```
- Vassal State
- All theirs resources and money (ask for maximum avaiable resource count)
- For one of this resources choose a number high enough to confuse this CIV (i mean, something like 9999 will be enough)
```
,,,
4. Press "Trade"... Congrats! Enjoy your new vassal.

**Comment by Edaka** [comment]
Related: #991
