### ISSUE TITLE
GameEvent.BuildFinished and GameEvents.UnitPrekill are triggered twice

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#10050]
Double triggering can complicate the code, so I have to use a dirty workaround to prevent that. For now two GameEvenets located:
- GameEvent.BuildFinished
- GameEvents.UnitPrekill

**Comment by azum4roll** [comment]
I don't see how BuildFinished can be fired twice. Progress is wiped once it's triggered in `CvPlot::changeBuildProgress()` as the build is complete, so even if you call the Lua Plot:ChangeBuildProgress twice it won't happen.

UnitPrekill can be called multiple times if CvUnit::kill(true) is somehow called multiple times in the same turn for the same unit.

Need someone else more familiar with the code to comment on this.

**Comment by adaneslavo** [comment]
I did the testing long time ago, so I cannot remember, but if I posted this, then I was quite sure about double triggering at that time I suppose.

Have you tested if it is true now? I don't think anything changed in last half a year, but...

**Comment by axatin** [comment]
can't be reproduced, closed
