### ISSUE TITLE
improvement maintenance

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1007]
there seems to be a bug in CvTreasury.

    /// What are our gold maintenance costs because of Improvements?
    int CvTreasury::GetImprovementGoldMaintenance() const
    {
	int iMaintenance = m_iBaseImprovementGoldMaintenance;

	// Player modifier
	iMaintenance *= (100 + m_pPlayer->GetRouteGoldMaintenanceMod());
	iMaintenance /= 100;

	// Handicap
	iMaintenance *= m_pPlayer->getHandicapInfo().getRouteCostPercent();
	iMaintenance /= 100;

	return iMaintenance;
    }

the route maintenance modifier is applied to the total improvement maintenance. now i'm not sure if there are any other improvements at the moment which cost maintenance, but this should probably be resolved one way or the other.

**Comment by LoneGazebo** [comment]
There aren't any maintenance improvements at present, thus the tooltips re: 'routes' (policies etc.) is a byproduce of this. We can either change the code, or change the tooltip (in the event that we ever add improvements that have maintenance).

**Comment by ilteroi** [comment]
ok, how about you change the tooltip and i change the function names?

**Comment by LoneGazebo** [comment]
Okay, sounds good.

**Comment by ilteroi** [comment]
done. but note: existing naming conventions are extremely inconsistent.

in the handicapinfos, there's a value RouteCostPercent, which is not actually a cost but a rate. it's now mapped to CvHandicapInfo::getImprovementMaintenancePercent()

**Comment by LoneGazebo** [comment]
Inconsistency? In this DLL? Well I never...

:)
