### ISSUE TITLE
Declaration of war warning when moving a worker into an allied city

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#10070]
_1. Mod Version (X.Y.Z). Current Version: 3.7.12_

_4. Describe the Issue_
Moving a worker into an allied CS triggers a declaration of war warning. Is that intended?

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[worker war.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12329373/worker.war.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12329375/Logs.zip)

_8. Steps to reproduce the Issue (Optional)_
Move the worker near Kathmandu into the city.

_9. Screenshots of the Issue (Optional)_
<img width="960" alt="worker_near_CS_ally" src="https://github.com/LoneGazebo/Community-Patch-DLL/assets/620131/43f884a4-81d6-4a91-ab35-31395337d8b8">

**Comment by azum4roll** [comment]
Civilians can pass through, but not stay in friendly cities.

**Comment by bsesar** [comment]
Understood. Since this behavior is intended, I'll close the issue.
