### ISSUE TITLE
city valuation / score calculation

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1008]
something strange happened here. brazil has already won the game.

then they give half their cities to the maya in exchange for athens which the maya had conquered. quite a deal. maybe we should limit the number of cities per deal?

357, The Maya, Brazil, Exchange Cities Offer
357, Brazil, The Maya, , , ***** City Trade: ID Uxmal *****, (value 9534 - raw)
357, The Maya, Brazil, , , ***** City Trade: ID Athens *****, (value 85892 - raw)
357, Brazil, The Maya, , , ***** City Trade: ID Halicarnassus *****, (value 4603 - raw)
357, Brazil, The Maya, , , ***** City Trade: ID Recife *****, (value 8747 - raw)
357, Brazil, The Maya, , , ***** City Trade: ID Calakmul *****, (value 9047 - raw)
357, Brazil, The Maya, , , ***** City Trade: ID Curitiba *****, (value 9718 - raw)
357, Brazil, The Maya, , , ***** City Trade: ID Cadiz *****, (value 9162 - raw)
357, Brazil, The Maya, , , ***** City Trade: ID Manaus *****, (value 12672 - raw)
357, Brazil, The Maya, , , ***** City Trade: ID Brasilia *****, (value 17094 - raw)
357, Brazil, The Maya, , , ***** City Trade: ID Sao Paulo *****, (value 20149 - raw)
357, The Maya, Brazil, , , ***** Resource Trade: ID 2 *****, (value 282 - raw)
357, The Maya, Brazil, , , ***** Gold Trade: 1032 *****, (value 1032 - raw)
357, Brazil, The Maya, ***** You have a Luxury I would like *****
357, The Maya, Brazil, , , ***** Resource Trade: ID 32 *****, (value 426 - raw)
357, Brazil, The Maya, , , ***** Resource Trade: ID 37 *****, (value 471 - raw) 

![image](https://cloud.githubusercontent.com/assets/1358966/12012714/a281dbbe-ad02-11e5-9ab3-75548fa58b7d.png)

anyway their score is unaffected.

![image](https://cloud.githubusercontent.com/assets/1358966/12012729/130e1cbc-ad03-11e5-9ba7-9bbb1a45ca88.png)

not sure if this can be right, all yields etc are about half of what they were before.

**Comment by LoneGazebo** [comment]
The AI gets weird after the game ends, as the grand strategy logic returns false. Breaks opinion, valuation, etc.
