### ISSUE TITLE
Lua method pPlot:SetOwner (iPlayer, iCity, true, true) doesn't work properly

### ISSUE THREAD

**Issue by gwennog** [LoneGazebo/Community-Patch-DLL#10096]
_1.Current Version: 3.7.12_

_3. List of Other Mods_
G&H's Kingdom of Scotland for Vox Populi

_4. Describe the Issue_
When I build the UI of this civ, the tile is claimed and therefore the resource on it (all the resources are well entered in Improvement_ResourceTypes with ResourceMakesValid at 1). It works very well for all the resources I tested except resources for Building Requirement (Stone for stone works, cattle/sheep for stable).
Tested by @azum4roll with citadel and same problem.

**Comment by azum4roll** [comment]
The resources are "connected" for strategic/luxury resource count purposes, but not for building requirement purposes.

**Comment by axatin** [comment]
Has been fixed in 4.6.2
