### ISSUE TITLE
Something wrong with a luxury resource

### ISSUE THREAD

**Issue by GeneralAmadeus** [LoneGazebo/Community-Patch-DLL#10109]
1. Mod Version
3.7.12

3. List of Other Mods
More Unique Components for VP (v 86)
JFD-US-DMS-THP-GH's Ireland - Brian Boru for VP (v.6)
Improved City View (v 20)
Squads for VP (v 2)
VP Sweden (v 1)

4. Describe the Issue
A city-state has the only coffee on the map. It was my ally and was taken by rome. After taking it back it for some reason did not give me coffee anymore. So I made a save and used a general to take the tile from the city-state. This was the result:
![civ coffee](https://github.com/LoneGazebo/Community-Patch-DLL/assets/126560657/b104f0d2-0fca-420a-a02b-960655120eb6)

5. Save Game From 1 Turn Before
[William_0442 AD-1852.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12403976/William_0442.AD-1852.zip)

**Comment by axatin** [comment]
The bug happened earlier, when the CS didn't have coffee anymore after being liberated. I assume you don't have a save game from before the liberation anymore? Reopen if you have.
