### ISSUE TITLE
Oil tooltip not working

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1011]
I don`t know if this comes from CP or EUI, but I report anyway.
The tooltip for oil does not appear. It will show the one of an adjacted resource instead if I move the cursor on oil.

**Comment by LoneGazebo** [comment]
getting errors in the lua.log?

G

**Comment by ricanuck** [comment]
Confirmed that the Oil tooltip is acting wonky, and also makes the rest of the tooltips in the Top Panel act wonky. Counts and icon are correct though.

**Comment by Der-Zorn-Gottes** [comment]
Sorry for not answering for so long, but I started a couple of games during the last days, and non of them went until oil.

**Comment by Der-Zorn-Gottes** [comment]
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/83642/Lua.zip)
Here is the log. Sorry it took so long.

**Comment by LoneGazebo** [comment]
No worries,

**Comment by LoneGazebo** [comment]
Fixed. It's an old EUI bug he refuses to fix (forgot to put my workaround in it for the latest version).
G

**Comment by ricanuck** [comment]
Beautiful. Thanks! (is it in the new beta already, or the next release? What are the chances of the next release to be save-compat? I am holding on now because I don't want to start one of those great new games only for it to be rendered void by the new release...
