### ISSUE TITLE
Remove UCS references from "Flags" component and fix the columns

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#10113]
2 things regarding Flag components integrated into VP.
First is I have to change some stuff in my UCS, so all references to it in VP should be deleted as soon as possible.
Second is I have no access to the _FlagPromoOrder_, _RankList_ and _RankNumber_ from the UCS, because I get an SQL error:
`[1260.098] no such column: FlagPromoOrder`

If you could fix this for the next patch so I could apply the changes with my new UCS version I would be very grateful. Now I have all changes commented out waiting for the fix.

**Comment by azum4roll** [comment]
Gotta wait for [complete-merge](https://github.com/azum4roll/Community-Patch-DLL/tree/complete-merge) to finish

**Comment by adaneslavo** [comment]
Will it be soon or rather in undefined future?
There's an annoying thing when Clermont promotions are merged together in the unit panel when they should't be.

**Comment by adaneslavo** [comment]
May I use them now? Should we close the issue?
