### ISSUE TITLE
Some building modifiers are not shown in Civilopedia

### ISSUE THREAD

**Issue by GeneralAmadeus** [LoneGazebo/Community-Patch-DLL#10120]
A picture is worth a thousand words.

![Civ5Screen0031](https://github.com/LoneGazebo/Community-Patch-DLL/assets/126560657/949d4285-fd61-4711-be23-669d8dce7759)
![Civ5Screen0032](https://github.com/LoneGazebo/Community-Patch-DLL/assets/126560657/23082c97-879a-4229-a6b9-4216034b7c9f)
![Civ5Screen0033](https://github.com/LoneGazebo/Community-Patch-DLL/assets/126560657/89da292c-9c79-48f3-97f6-ec54c74edc39)

**Comment by azum4roll** [comment]
Most of it is text issue, but IFC actually has +5% food that's not shown on Civilopedia.
