### ISSUE TITLE
CTD during AI turn

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1012]
I have get a CTD during Brazils turn when I conquer a city of them.
If I don`t, the game conzinues as normal.
I could conquer their cities before without problems. The CTD appears after United Nations was passed, so it might have to do with this (or any) project.
Using latest Beta with Iterois hotfix.
[Crash report + save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/73095/Crash.report.save.zip)

**Comment by ilteroi** [comment]
can't use your save unfortunately because of missing DLC, but i might have hit it independently (it's a divide by zero). i'll upload a new version at the usual place, please retry

**Comment by LoneGazebo** [comment]
If it's the two most recent map pack dlcs  that you need, ilteroi, theyre on deep discount on steam right now.

**Comment by Der-Zorn-Gottes** [comment]
Yes that did it!
