### ISSUE TITLE
Workers ignore existing roads when building railroad

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#10137]
_1. Mod Version (X.Y.Z). Current Version: 3.9.1_

This issues has been around for a couple of months and apparently hasn't been fixed.

A worker sitting in Si Satchanalai is ordered to build railroad to Nimrud (to the south-west, seen on the second screenshot) via "Route to Mode" button.

![20230830135105_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/16341598/bf98638d-a8a4-4099-b69c-8367a700a5b4)

Instead of using existing road, the worker steps into a roadless forest tile to construct railroad

![20230830135125_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/16341598/142747d8-86eb-440c-af3b-870cbcabff9e)

**Comment by azum4roll** [comment]
It's likely working as intended, since there's a Town on the Flood Plains that will benefit from a Railroad.

**Comment by saamohod** [comment]
> It's likely working as intended, since there's a Town on the Flood Plains that will benefit from a Railroad.

It's actually not about the town. Why did the worker sidestepped into a forest tile to build a railroad parallel to an existing road. There is a road right to the right of him, but he ignored it and decided to build a new path parallel to an existing one.

**Comment by azum4roll** [comment]
Need that to make the Town part of the city connection (shortest path between any two cities)

**Comment by saamohod** [comment]
> Need that to make the Town part of the city connection (shortest path between any two cities)

It isn't shortest. It takes the same amount of tiles.

**Comment by azum4roll** [comment]
Being a railroad makes that the shortest. But just adding a railroad to the town definitely wouldn't.

**Comment by saamohod** [comment]
Looks like we're talking about different things.

Railroad already exists on the silk tile at 5 o'clock of Si-Satchanalai. The worker sitting in that city is ordered to build railroad to the Nimrud city by using "Route to Mode". Instead of starting from the existing railroad tile (the silk tile), the worker steps into the roadless forest tile (seen on the second screenshot) and begins to dig railroad from there. 

It doesn't make the route shorter, feel free to count the tiles. Same amount of tiles.

Also worth noting that this is a relatively fresh problem, I first noticed it a month or two ago. It never happened in years I played VP. A worker who was ordered to build a railroad could properly build a railroad over a pre-existing road between points A and B. Now it looks like AI is oblivious to an existing road and therefore often builds railroad parallel to the existing road.

I hope I make it clearer this time.

**Comment by saamohod** [comment]
> Being a railroad makes that the shortest. But just adding a railroad to the town definitely wouldn't.

That town may indeed be the cause. However I'm quite sure I saw instances of irrational AI railroad building behavior in other situations. I'll post it when I spot it.

**Comment by saamohod** [comment]
Another screenshot to illustrate the case of flawed worker AI.

The worker that is now sitting next to Ha Noi at 9 o'clock (hilly mine tile) was ordered to build a railroad from Quy (west) to Ha Noi (east). He did a good job and followed a previously built road (just because there were nowhere to diverge to), but screwed up on the last tile and instead of following the existing road into the cow tile, he strayed into the hill tile and began building railroad there. 
There was absolutely no reason to build a railroad on the hilly tile right next to a now redundant road tile.

![20230901151449_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/16341598/6f6a22e4-9136-4834-be65-1f60cd7072f0)

**Comment by n-core** [comment]
Because AI workers for route building have been reworked recently by @KungCheops. You might wanna report it to him.

**Comment by KungCheops** [comment]
The reason it prioritizes the hill tile over the cattle tile is because a village/town can be built on the hill.

**Comment by KungCheops** [comment]
And in the first case, it is indeed rerouting your road network to include the town.

**Comment by ilteroi** [comment]
you might want to make a different between AI workers and automated human workers

**Comment by KungCheops** [comment]
It's starting to look like there's no way around it. Haven't had much energy to work on this in a while unfortunately.

**Comment by ryanmusante** [comment]
Is the road logic for AI workers indeed different than automated workers? I had just assumed it was

**Comment by KungCheops** [comment]
The AI uses the same road pathfinding logic as the human workers do when asked to build a route from point to point.

It should really only prioritize routing for villages when one of the two points is a capital city though. And maybe never for human players. Might be worth to have a look at, should be a fairly easy fix.

Have been thinking about doing something about the fact that the AI builds villages on road tiles even when they are not city connections as well, but maybe that's intended behavior.

**Comment by azum4roll** [comment]
They really shouldn't. I've seen Town on a strategic road, which is just terrible.
