### ISSUE TITLE
Ship oddities

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1014]
Minor stuff just:
If I rightclick with a ranged ship on a enemy, it will not just attack, but move on that tile afterwards (if the unit there was killed). It doesn´t happen if you use the button ranged attack.
Also, submarines cannot attack cities any more.
Ships can move on ice tiles (might be inteded), but subs cannot attack them there.

**Comment by ilteroi** [comment]
will check.

which kinds of ships can move under ice? can't reproduce with anything except subs, and that's by design

**Comment by Der-Zorn-Gottes** [comment]
It was a cruiser.

**Comment by ilteroi** [comment]
strange @ cruiser.

as for the ranged ship attack / movement, that's only with embarked units as target, because they count as civilians by accident. will revert that.

subs also fixed. new version up at the usual place.

**Comment by LoneGazebo** [comment]
I'm finally home, ilteroi. When you have a chance, can you send me a list of fixes that have been made since the 18th so I can have a proper update bugfix list? I'll try to work on a new version tomorrow.

**Comment by ilteroi** [comment]
it's all uploaded to github, you can check the commit messages. or simply use the summary i posted in the hotfix thread in the forum

**Comment by LoneGazebo** [comment]
Sounds good. I'll take a look at it all tomorrow. My inbox is bursting with reports and messages right now - somewhat terrified to see what all we have left to do. :)

**Comment by Der-Zorn-Gottes** [comment]
Unfortunately, it`s not quite fixed. Now embarked units cannot be attacked by ranged units at all, if you use rightclick. 
Bombard button works, though.

**Comment by ilteroi** [comment]
that's strange. for me it works. anybody else tested this recently?
