### ISSUE TITLE
3.9.1 CTD during computer turn

### ISSUE THREAD

**Issue by Mlac99** [LoneGazebo/Community-Patch-DLL#10166]
_1. Mod Version (X.Y.Z). Current Version: 3.9.1_

3.9.1

_2. DirectX Version_

DirectX 10/11

_3. List of Other Mods_

Without other mods

_4. Describe the Issue_

CTD during computer turn

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Every time I load Civ and that savegame, ctd happens after "next turn". I haven't problems with 3.7.12

_9. Screenshots of the Issue (Optional)_

**Comment by Mlac99** [comment]
savegame
[Bismarck_0224 AD-1908.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12589056/Bismarck_0224.AD-1908.zip)
minidump
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12589057/CvMiniDump.zip)

**Comment by axatin** [comment]
The same error as #10161, has been fixed for the next version.
