### ISSUE TITLE
Reckless civilians

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1016]
I'm seeing many situations when the AI will move its civilian units (mainly diplomats and great people, doesn't seem to happen with workers) carelessly close to enemy troops. 
![civilians](https://cloud.githubusercontent.com/assets/12978597/12026627/6edbc366-adc4-11e5-8c47-da37df32c01f.jpg)
This great general moved into that tile from the East, all by himself. I believe he was making his way from Beijing to Weifang, as there is a unit stationed there.
![civilians1](https://cloud.githubusercontent.com/assets/12978597/12026628/707f9fc6-adc4-11e5-9d51-bfa73d9b40c0.jpg)
This diplomat moved into that tile from the city down South. Was probably going for that city state, which borders can be seen here.

In all cases the enemy AI had clear sight of my units.

**Comment by ilteroi** [comment]
i've also noticed that, it's on my list :)

**Comment by ilteroi** [comment]
i have increased the penalty for civilians walking into danger. they should now make detours of up to 10 tiles to avoid it.

**Comment by LoneGazebo** [comment]
Sounds good.
