### ISSUE TITLE
Game Crash at city-state's turn

### ISSUE THREAD

**Issue by Nobody679** [LoneGazebo/Community-Patch-DLL#10170]
_1. Mod Version (X.Y.Z). Current Version: 3.9.1_

3.9.1

_2. DirectX Version_

DX 10 & 11

_3. List of Other Mods_

no extra mods are activated

_4. Describe the Issue_

The game crashes at city-state's turn making me unable to get to turn 98. Tried to do various other things in my turn to see if I can prevent the crash but that didn't do anything.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[1 turn before crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12594806/1.turn.before.crash.zip)
[2 turns before crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12594807/2.turns.before.crash.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12594776/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12594788/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

click next turn

_9. Screenshots of the Issue (Optional)_

**Comment by seroperson** [comment]
Not checked, but from description feels like the same as #10161

**Comment by axatin** [comment]
I just had a quick look, it's something different. A crash in `CvBaseInfo.GetDescriptionKey()`, but I can't see which object it's trying to retrieve the base info for...

**Comment by seroperson** [comment]
@axatin Yea, if so, it's already fixed. Here is stacktrace which we had for issue I mentioned: ![image.png](https://github.com/LoneGazebo/Community-Patch-DLL/assets/3791221/5e4b94f9-fdd7-47c4-aae1-398f472f58b4)

**Comment by axatin** [comment]
You're right! I only read something about different quest lengths in the discussion, didn't notice that you mentioned that it returned NO_BUILDING because of that. Then it's indeed already fixed.
