### ISSUE TITLE
Harappan Reservoir AND Aqueduct in captured cities

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1017]
When capturing an Indian city that retains its Harappan Reservoir, I am able to build an Aqueduct in addition. 12/18 version

**Comment by LoneGazebo** [comment]
Just India? Also, what civ are you?

**Comment by joosegoose** [comment]
Just India...it was my understand they are the only civ to get the Harappan Reservoir, no? I'm playing as Rome and have had this happen to every Indian city I've captured.

**Comment by LoneGazebo** [comment]
Interesting. Rome can capture unique buildings in new cities, but being able to build other buildings of the same class is odd. If you capture buildings of another player, let me know if a similar behavior happens.

G

**Comment by joosegoose** [comment]
Yep, captured an Austrian city (still as Rome) and was able to build a windmill despite retaining the Coffee House.
