### ISSUE TITLE
Multiple Negative Influence Notifications Cannot Be Toggled (logs included this time)

### ISSUE THREAD

**Issue by ZetaLambdaNinja** [LoneGazebo/Community-Patch-DLL#10175]
_1. Mod Version (X.Y.Z). Current Version: 3.9.1_

3.9.1

_2. DirectX Version_

DX 10 & 11

_3. List of Other Mods_

pineappledan's More Unique Components for VP (v 87)

_4. Describe the Issue_

NOTE:  This is a resubmission of a bug I had previously observed.  I have made sure to include logs with the savegame file this time.
When two or more negative influence shift notifications occur on the same turn, the player can only see the last one in the list.  Normally, with stacked notifications, left-clicking the icon will toggle through them.  However, left-clicking a negative influence icon instead opens the culture overview screen.

See the attached savegame for an example.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[BUG - MultipleNegInfluenceShifts.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12604786/BUG.-.MultipleNegInfluenceShifts.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12604788/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Have two negative influence shift notifications occur in the same turn.  See the attached savegame.

_9. Screenshots of the Issue (Optional)_

**Comment by azum4roll** [comment]
fixed by #10627
