### ISSUE TITLE
[CSD] City-State revolting despite gaining 200+ influence from defeating rebels

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1018]
Crossposting from Civfanatics. Apologies if this is lazy, but I don't have anything else to add other than what was in this post:

http://forums.civfanatics.com/showpost.php?p=14106055&postcount=2296

**Comment by Edaka** [comment]
I hink the answer might be in your third screenshot - there was a barbarian in a one tile radius from the CS borders, which might count sufficient for the quest failure to trigger. At least there was a 'Barbarians envading our territory' icon beneath the CS banner, which is an indicator that barbarians are close.

**Comment by LoneGazebo** [comment]
Ah, I thought he was saying that it failed the same turn it opened. Yep, this is WAD.
G
