### ISSUE TITLE
Community patch is broken - 3.10.2 (September 15, 2023)

### ISSUE THREAD

**Issue by shaunfitz** [LoneGazebo/Community-Patch-DLL#10188]
[Morocco1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12623675/Morocco1.zip)

Same thing different place, to the desktop we go. Attached  is the save game. Go next turn and off we go. CTD
Community patch only.

_1. Mod Version (X.Y.Z). Current Version: 3.10.2_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
Fixed. You can use the file here https://forums.civfanatics.com/threads/new-version-3-10-2-september-15-2023.685541/post-16508310 to continue playing.
