### ISSUE TITLE
Some game config options are not saved

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#10187]
2 very annoying things from the vanilla are still left. When you start the game you would like your setting to be remembered so you could quickly start new game. This gets much more improtant when you do frequent playtesting. But two things are not remembered:
- **Victory: Time** is always set to ON:
![2023-09-15_19h13_13](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/9a121e8a-fd3a-46b1-9ea0-ce75ece8e6a9)
- **Number of Major Players** is always reset to the default. When I delete few (let's say there are 3 left), start the game, go to main menu, enter the config menu, then there is always default number of Major Civs instead of 3:
![2023-09-15_19h13_20](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/ee93b725-7e15-42f6-9faf-07873640132b)

**Comment by axatin** [comment]
Unfortunately we don't have access to the part of the code that controls these things, so as far as I see an easy fix is not possible. However, you can use the "Really Advanced Setup" mod, in which the advanced selection screen is completely rewritten and the options you mentioned are being saved.

**Comment by adaneslavo** [comment]
@axatin Is there a special version dedicated to VP and compatible with latest version?

**Comment by axatin** [comment]
I can't tell for sure because I rarely use the mod myself, but it seems a lot of people are using the normal version of the mod with VP, so I guess it works fine: [https://forums.civfanatics.com/threads/really-advanced-setup.486324/](https://forums.civfanatics.com/threads/really-advanced-setup.486324/)
