### ISSUE TITLE
3.10.2 CTD

### ISSUE THREAD

**Issue by LBier** [LoneGazebo/Community-Patch-DLL#10193]
_1. Mod Version (X.Y.Z). Current Version: 3.10.2_

3.10.2 with EUI

_2. DirectX Version_

DX 11

_3. List of Other Mods_

InfoAddict

_4. Describe the Issue_

CTD when pressing next turn

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[3.10.2 - Germany CTD.Civ5Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12640041/3.10.2.-.Germany.CTD.Civ5Save.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12640046/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12640049/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
Fixed. You can use the file here https://forums.civfanatics.com/threads/new-version-3-10-2-september-15-2023.685541/post-16508310 to continue playing.
