### ISSUE TITLE
CTD 3.10.1 & 3.10.2 

### ISSUE THREAD

**Issue by brsoft1981** [LoneGazebo/Community-Patch-DLL#10194]
_1. Mod Version (X.Y.Z). Current Version: 3.10.2

_2. DirectX Version_
DX 11

_3. List of Other Mods_
None

_4. Describe the Issue_
CTD on AI turn

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[AutoSave_0313 BC-0370&0360.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12640108/AutoSave_0313.BC-0370.0360.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12640110/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12640112/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
Fixed. You can use the file here https://forums.civfanatics.com/threads/new-version-3-10-2-september-15-2023.685541/post-16508310 to continue playing.
