### ISSUE TITLE
Broken CP 3.10.1 & 3.10.2

### ISSUE THREAD

**Issue by brsoft1981** [LoneGazebo/Community-Patch-DLL#10190]
_1. Mod Version (X.Y.Z). Current Version: 3.10.2_

_2. DirectX Version_
DX11

_3. List of Other Mods_
None

_4. Describe the Issue_
CTD
[AutoSave_0313 BC-0370&0360.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12623903/AutoSave_0313.BC-0370.0360.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12623905/Logs.zip)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by Tesla101a** [comment]
For future reference CvMiniDump.dmp can be found in C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Civiliation V\ and they might be necessary for CTD issues.  I posted mine in another issue though.

**Comment by brsoft1981** [comment]
Ok, I'm closing this issue and i'm adding new with CvMiniDump.dmp
