### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#10203]
CvMinorCivAI::GetUnitSpawnCounter(PlayerTypes ePlayer)

I'd like this to be exposed to the Lua of Player, so I can add a timer in the UI for how long a city-state might be ready to send its unit. It should also work in the case of Rome's UA as well. 

Thanks to anyone who can do it!

**Comment by axatin** [comment]
I don't think it should be shown in the UI. The number of turns is random, precisely to prevent the players counting down turns and planning ahead when they'll get the next unit.

**Comment by axatin** [comment]
Still it seems to me that the information was intentionally hidden, so it should be discussed in congress if it should be added to the UI.
