### ISSUE TITLE
Separate Great People Counters Question

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1021]
Sorry to bring up so many issues lately, however, I wanted to ask how exactly the GLOBAL_SEPARATE_GP_COUNTERS define works. 

Is it fixed to only separate the vanilla Great People, as seems to be the case? I'm having some trouble with my added Great People - Great Magistrate, Great Dignitary, Great Doctor, and Great Prophet (not mine, but generated via Specialist in Piety and thus having the same issue) and wanted to know if there was any way I could get them separated, too, so that when one spawns it doesn't increase the others' GP counter (atm, when one spawns it'll increase the GP counter of one another, or of the Great Engineer). How does the Great Diplomat in CSD work around this? Thanks for any insight.

**Comment by LoneGazebo** [comment]
Those values are hard-coded into the DLL (the rates). The Great Diplomat has it's own entry in the DLL. There's currently no means by which to add 'unique' rates without modifying the DLL.

G

**Comment by JFDaly** [comment]
Anything to be done to make it more modular? Or is this one of those spagehetti code?

**Comment by LoneGazebo** [comment]
I'll take a look, but I don't see a way to do so (As the values are hardcoded everywhere. I could create a 'spoof' table that pretends to be a GP counter, but it wouldn't interact as clearly with everything else.

**Comment by JFDaly** [comment]
Thank you. If it's too much, then by all means don't worry about it.

**Comment by LoneGazebo** [comment]
It's on my list. I'd love to de-hard-code the World Congress and GPs a bit, but man is it ever a noodly mess.

In the meantime, you could co-opt the Great Diplomat's slot, perhaps.

G

**Comment by LoneGazebo** [comment]
Yeah, looking over it, I just don't see an easy way to fix it without having to completely rewrite all GP logic in the DLL (which would break most GP lua). Is a shame.
