### ISSUE TITLE
Very low valuation of strategic resources by AI

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1022]
Adding more strategic resources to a deal doesn't seem to affect how much the AI is willing to pay. Adding 4 iron didn't even add 1 gpt from the AI side. Generally 1-2 gpt is the most you can get for 1-4 of early strategic resources (e.g., iron, horses). Don't know if it's a bug, but it seems like one given how the AI used to value SRs previously.

**Comment by LoneGazebo** [comment]
Intentional. Humans tend to abuse this in the early game.
G

**Comment by Edaka** [comment]
I see. That cuts the value of SRs a little too much for my liking, trading them isn't really worthwhile at the moment. Maybe it's just me, though.

**Comment by LoneGazebo** [comment]
They come up pretty quickly by the mid-game. If they aren't, I can check the tuning value.

G

**Comment by Edaka** [comment]
So you're saying that early SRs (horses,iron) come up in value? Playing in the industrial era, I didn't notice a change. We'll need more substantial evidence, though.

**Comment by LoneGazebo** [comment]
They should, marginally, based on GPT.

G

**Comment by Edaka** [comment]
Ah, right. By the way, whose gpt matters more when we're talking about how much the AI is willing to pay - your, their, both?

**Comment by LoneGazebo** [comment]
The buyer's GPT.

G

**Comment by ilteroi** [comment]
how about basing it on GDP?

**Comment by LoneGazebo** [comment]
We could – I probably need to switch most GPT elements to GDP (as GPT inflation is way lower in CBP than BNW).

G

**Comment by Edaka** [comment]
Napoleon with +155 gpt would only pay this much for iron. That's dirt cheap.
![valuation](https://cloud.githubusercontent.com/assets/12978597/12079793/fc1e6286-b24e-11e5-83c7-1b8e85754411.jpg)
This concerns luxury resource valuation, too. The same Napoleon with the same +155 gpt was willing to pay only 5 gpt for pearls - as much as Oda who only had +11 gpt (although I admit that Oda seemed a little frendlier).
![valuation2](https://cloud.githubusercontent.com/assets/12978597/12079806/6ecaf2f4-b24f-11e5-90a0-7f9781c8542a.jpg)
