### ISSUE TITLE
Game crashes to desktop somewhen near turn 120-130

### ISSUE THREAD

**Issue by radziu93** [LoneGazebo/Community-Patch-DLL#10220]
_1. Mod Version (X.Y.Z). Current Version: 3.10.6_

3.10.5

_2. DirectX Version_

DX11

_3. List of Other Mods_

Pontoon Bridges for VP (v2)
Resource - Granary includes Bison
Resource - Mint Includes Copper
Less Warmonger for VP (v3)

_4. Describe the Issue_

So I recently (5 days ago) updated Vox Populi to lastes version. The problem I have now is, game (seemingly) randomly crashes to desktop near turn 120-130. I have no idea what could case this, there is no error message, it just shuts down. All of those four aforementioned mods worked just fine with previous version of VP I had. Tho I don't really remember the number, it was something from year 2022. I'm attaching 2 different saves, first is one turn before crash in previous game, second is about 3 turn before crash in my newest game.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[single.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12654315/single.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12654310/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12654320/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

Start playing, see if you can go past 150 turns.
I did reproduce issue, both by loading saves and trying to get to next turn, and also starting completelly new game. It also crashed to the desktop, but about 10 turns later than the first game.

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
These save files are not from one of the 3.10 versions. The 3.10 versions use "Community Patch (v. 121)".
![Screenshot (444)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/95587882/ef2ab7e0-145d-48c7-a131-a3d6653ffbbd)

**Comment by radziu93** [comment]
That's also why I created a whole new game, The second save didn't use Bridges and Canals at all. Well, I'll test wit 3.10.7, but still it's weird that this wasn't 3.10.5. I downloaded latest installer a week ago from community patch project and made a full install from it.

**Comment by axatin** [comment]
I see. I checked the other save you uploaded, it was also created using an older version (must be one of the 3.8.x). The crash you had is fixed in the 3.10 versions.
