### ISSUE TITLE
Multiplayer Turn 1 CTD

### ISSUE THREAD

**Issue by 1slayerpikmin1** [LoneGazebo/Community-Patch-DLL#10227]
_1. Mod Version (X.Y.Z). Current Version: 3.10.9_

3.10.9

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

Using the 3.10.9 VP + EUI modpack from:
https://forums.civfanatics.com/threads/voxpopuli-modpacks-last-update-3-10-9.685164/
(which is this one):
https://drive.google.com/file/d/1mZ21ElRiD1MHMrHtMY5tmcNh-ZJeCwaL/view?usp=drive_link
We kept trying several games so I don't even remember exactly, but it was completely broken. I hit next turn on turn 0, the host crash, some German wizardry happened on the non-hosts turn after I crashed, with a settler appearing in their capital and a pathfinder appearing outside their borders, then it crashed for them too. Every time we tried it kept breaking in new and interesting ways, such as cities disappearing, teleportation, never could make it even one turn.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

This zip has the logs and minidump and autosaves:
[two.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12666320/two.zip)

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by Cyclopia31** [comment]
I tested 5 turns at two players and it works well.

I think you have an installation problem: both players should have the exact same DLC folder (with the same modpack inside).

If you have some lekmaps on the MAPS folder try to delete them: even without using them it can cause issues with base Civ5 and VP (personal experience...).

If you have the map option "override AssignStartingPlots" when you create the game on the map option desactivate it can help to prevent Turn0 desync.

Maybe it is something else that need to be fixed I am not the expert here ;)

**Comment by 1slayerpikmin1** [comment]
We definitely should both have the same DLC folder, and I definitely don't have any lekmaps, I don't really even know what that is. We played on communitu_79a so we did have override AssignStartingPlots on, but it did work fine for when we played 3.9, and also we went back today to 3.9.1 to try that and it also broke so I don't really know what's going it's always been kind of all over the place when we try to play multiplayer

**Comment by Cyclopia31** [comment]
Thank you for your reports, it really helps the Devs to debug things :) I hope someone will figure out what is your problem.

**Comment by seroperson** [comment]
Yea, sounds weird and really more like some installation issue or modpack issue. I will check anyway a little bit later, thank you for the report!

**Comment by 1slayerpikmin1** [comment]
What do you mean by installation issue? You mean the whole civ installation is borked and needs to be reinstalled?

**Comment by 1slayerpikmin1** [comment]
I believe it may indeed be an installation issue, but I won't be able to attempt multiplayer for who knows how long because they need to have time so we'll see

**Comment by seroperson** [comment]
I did a brief test with 2 players + 1 AI and my few sessions were running ok (I have skipped around 10 turns in each). From the description it sounds like pretty reproduciable issue, but both of me and @Cyclopia31 did our tests successfully. Maybe I will sound corny, but try to verify game files (or even reinstall civ5 from scratch), clean Documents/ game folder, reinstall modpack again and be sure that you both did all the steps correctly. Feel free to reopen if it still fails with clean install.
