### ISSUE TITLE
Civs happy when their own resolutions are repealed

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1023]
![2015-12-29_00001](https://cloud.githubusercontent.com/assets/11132095/12047389/33853352-ae90-11e5-9d3e-66b81f7ed274.jpg)

As you can see, an open door with Mogadishu was overwhelmingly passed. However, on the very next turn...

![2015-12-29_00002](https://cloud.githubusercontent.com/assets/11132095/12047390/3394432e-ae90-11e5-8830-52bea427c58d.jpg)

**Comment by LoneGazebo** [comment]
It happens sometimes. Also, the 'grateful' element there is based on your shadow AI's assumptions, not necessarily reality.
