### ISSUE TITLE
Strange pathing for Caravan trade route

### ISSUE THREAD

**Issue by dape6509** [LoneGazebo/Community-Patch-DLL#10236]
_1. Mod Version (X.Y.Z). Current Version: 3.10.11_

3.10.10

_2. DirectX Version_

_3. List of Other Mods_

Great Prophet Historical Names
Info Addict
R.E.D. Modpack
Strange Religions
Subs Ignore Borders
Wonder Race

_4. Describe the Issue_

Caravan from Paris to Riga takes an interesting detour through additional rough terrain when it should probably take a straight path between the two cities, as the route to Cattaro does, or at least take a more direct path. All other routes look normal.

EDIT: Looks like it could just be attempting to follow the river, but it still seems a bit too far out of its way to go for that.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0051 BC-1960.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12683075/AutoSave_0051.BC-1960.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12683084/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

![20230921034128_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/19981950/0daffb4a-9307-4cc5-b967-0a7af5e7e664)

![20230921034132_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/19981950/2835ef71-3f73-45e4-8c14-094ffb39a889)

**Comment by ilteroi** [comment]
rough terrain is ignored if there is a river.

**Comment by axatin** [comment]
Yes, caravans move more quickly along rivers, that's why the route shown is indeed the fastest.
