### ISSUE TITLE
"Feature Request" for Ostrog and Great Wall

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#10241]
Lua line to detect when a City has BorderObstacle or BorderObstacleCity

City:HasBorderObstacle(bLocal).. or something like that. We already have one for City:IsMined(), but nothing  for covering Great Wall and Ostrogs really.

**Comment by azum4roll** [comment]
Great Wall is already covered with Team:IsBorderObstacle() (yes it affects the whole team)
City:IsMined() is only for deep water damage, not the border effect.
I suppose I can make City:IsBorderObstacleLand() and City:IsBorderObstacleWater().
