### ISSUE TITLE
garrisons

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1024]
the limited influence of a garrison and the fact that a healthy garrisoned unit is simply killed when a city is captured have been bothering me for a while.

so here are some ideas:

1. increase the defense bonus a city gets from a garrison. it's rather marginal right now
2. add the garrison's hitpoints to the city hitpoints. if the city is attacked, garrison and city split the damage. open point is the heal rate, if both can heal, it would make cities harder to capture.
3. if the city is captured, the garrison flees (a la heavy charge). if there's no place to go, it is killed. 

point 1 is rather independent. point 2 makes re-capturing a city harder (desirable?) and almost makes 3 redundant (an almost dead unit is no big help). point 3 on its own might intensify the capturing and recapturing of cities (desirable?).

opinions?

**Comment by LoneGazebo** [comment]
I like #1 and #2, though I don't want #1 to add too much, as it swings crime unhappiness a bit. Might even be worthwhile to add a promotion element that reduces unit damage received while garrisoning a city.

**Comment by ilteroi** [comment]
surprise fix? i was just about to get cracking :)

**Comment by LoneGazebo** [comment]
oh oops. not sure why that appeared.

**Comment by LoneGazebo** [comment]
FYI, I need to upload my merge - will do this evening. Not too different from your current version, though.

**Comment by ilteroi** [comment]
ok. initial version done. maybe needs some tweaking regarding the damage distribution, otherwise the garrison will die long before the city is captured. but then maybe that's realistic?

**Comment by Kolaris8472** [comment]
I was more worried that with Medic, Hospital, God of War etc the garrison might never die.

**Comment by ilteroi** [comment]
pushed. unit share of the damage depends on the hitpoints the city has. ie no walls etc -> unit takes more damage.
