### ISSUE TITLE
Lua hook for "extra" resources

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#10258]
Currently I have no possible way to get the information how many luxuries are available from certain sources. These things are (all I know about):
- East India Company - doubles resource
- Great Admiral's voyage - adds flat +2 of the resource not on the map
- free resources from buildings.

With the function that can get the amount of extra luxuries, I could add additional info to the Trade Opportunities' tooltip.
Now I have this:
![2023-09-26_00h02_09](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/0e270652-2dd5-496a-b841-ecb6a873bb41)
There are 5 Ambers on the map, and I get 2 extra. 1 is not improved.
With this info I could write this:
```
1'' (4 of 5, 2 extra)
```
Also there's another problem I could resolve. I got 2 Peppers from Great Admiral, but without the knowledge how many resources are available, I can see nothing:
![2023-09-25_23h59_07](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/7bf32bdf-7835-46cc-b576-705d1909170a)

This is the code I use so far. I could add an additional parameter called let's say "extra":
```
local iMinors  = pPlayer:GetResourceFromMinors(eResource) -- doubling the number of resources after allying? Commented out...
local iImports = pPlayer:GetResourceImport(eResource)
local iExports = pPlayer:GetResourceExport(eResource)
local iLocal   = pPlayer:GetNumResourceTotal(eResource, false) + iExports
local iUsed    = pPlayer:GetNumResourceUsed(eResource)
		
local iSurplus = iLocal - iExports - iUsed
iTotal = iLocal + --[[iMinors +--]] iImports - iExports - iUsed
```
These resources do not count for monopolies. This means the tooltip is misleading.

**Comment by adaneslavo** [comment]
Another thing that could be fixed, this time on the VP side would be this window:
![2023-09-25_23h40_49](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/953b2cd3-efc4-4d31-bc0e-778953c7451d)
It shows 120%, but in real only 80% is counted towards Monopoly.

**Comment by axatin** [comment]
You can get resources from Admirals with  `GetResourcesFromGP` (but they're also included in `GetNumResourceTotal`).

Resources from buildings or the East India Company do count towards monopolies, there's no difference between them and resources from tiles. So the VP tooltip is correct, a total of (4+2) resources count towards a monopoly. This number is compared against the number of resources on the map (excluding extra sources), which is 5.

**Comment by adaneslavo** [comment]
Ok, thanks for explanation. I will try to mess up with the GP resources after I finish the Great Merge thing.
Do GP resources count towards monopoly?
And still, I think I could make a use of the additional hook returning me the exact number of these building + EIC resources. Is it doable?

**Comment by axatin** [comment]
Resources from GAs don't count towards monopolies because they're not present on the map.

Well, currently the same function `changeNumResourceTotal` is used both for normal and for extra resources. Changing that wouldn't be a problem, but then all the modmodders will also have to be taught to use two different functions in the future.

**Comment by adaneslavo** [comment]
Wil you be able to do that or it's not your "department"?

**Comment by adaneslavo** [comment]
I cannot uderstand why you want to change this `ChangeNumResourcetotal` function? Can you only add new stuff like `GetNumExtraResources`.

**Comment by adaneslavo** [comment]
> You can get resources from Admirals with `GetResourcesFromGP` (but they're also included in `GetNumResourceTotal`).
> 
> Resources from buildings or the East India Company do count towards monopolies, there's no difference between them and resources from tiles. So the VP tooltip is correct, a total of (4+2) resources count towards a monopoly. This number is compared against the number of resources on the map (excluding extra sources), which is 5.
If building resources are counting into monopolies, then Tern Egg added by one of the World wonders does not cound, because it's not present on the map. It's probably true also for regular resources given by the buildings when they are not drawn from the pool and placed on the map.

**Comment by adaneslavo** [comment]
> This number is compared against the number of resources on the map (excluding extra sources), which is 5.

Does it mean multiple players can have a Global Monopoly? Let's say 2 players have 2 copies of particular resource in the capital and both have EIC constructed there. Normally both would have 50%, so no one would have Global Monopoly. But with EIC they both have 100% (4/4, 2 from tiles, and 2 from EIC), so both should have a Global Monopoly. Right?

**Comment by adaneslavo** [comment]
I managed to use function you provided me: `GetResourcesFromGP`
This is the result:
![2023-10-01_22h22_42](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/1c0aa2cb-66fb-468b-a827-56d3e5bdf591)

**Comment by axatin** [comment]
> Does it mean multiple players can have a Global Monopoly of the same resource? Let's say 2 players have 2 copies of particular resource in the capital and both have EIC constructed there. Normally both would have 50%, so no one would have Global Monopoly. But with EIC they both have 100% (4/4, 2 from tiles, and 2 from EIC), so both should have a Global Monopoly. Right?
>

That's correct

**Comment by axatin** [comment]
> I cannot uderstand why do you want to change this `ChangeNumResourcetotal` function. Can you explain that? Can you only add new stuff like `GetNumExtraResources`? Only function getting the number and doing nothing more.

Internally, when GetNumResourceTotal is called, the number of resources isn't calculated based on what tiles/buildings the player has. Instead, a stored value NumResourceTotal is returned. That value is 0 at the start of the game and it's changed whenever the player gets or loses a resource. So, NumResourceTotal tells us how many resources a player has, but it doesn't give us any information where they originally came from.

To change this, we need two separate variables NumResourceFromTiles and NumResourceFromBuildings that would replace NumResourceTotal, and that would also require splitting up changeNumResourceTotal.

**Comment by adaneslavo** [comment]
Why to split NumResourceTotal? We can leave it as it is and add up new values that will be returned.

**Comment by axatin** [comment]
That would be possible. We can add changeNumResourceExtra and getNumResourceExtra, and if a modmodder doesn‘t use it properly the only consequence is that it‘s shown incorrectly in the UI.

If your congress proposal passes, this has to be done anyway, because extra resources would increase the monopoly threshold while normal ones wouldn‘t.

**Comment by adaneslavo** [comment]
Yeah. Let's wait for the results.
Either way, I would use it in my modmods.

**Comment by adaneslavo** [comment]
Are any of these available through code (except first 3 we talked about)?
![2023-10-02_14h39_21](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/c08cfe9d-ce65-42d2-acdd-fdfa12e90ef5)
I added some new exceptions to TO, so now Great Admiral resources and Dutch are supported:
![2023-10-02_14h34_02](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/275fb20a-12cf-430c-a0b7-02e325f413d7)
![2023-10-02_14h36_15](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/499ddc22-5ea5-41c1-95da-b3c7f6ade96d)

**Comment by axatin** [comment]
> Yeah. Let's wait for the results.
> Either way, I would use it in my modmods.

Okay, let's do it that way.

Other resource types:
Russia UA: nothing yet, is currently included in iNumResourceTotal, but I can write it

The others exist all together in `GetResourcesMisc`

`GetResourcesMisc` is calculated as the sum of `GetResourcesFromCorporation`, `GetResourceFromCSAlliances` (Foreign Service), `GetResourcesFromGP`, `GetResourcesFromFranchises`, and to that value modifiers for religion and policies are applied. So you can get the effect of the modifiers by taking the difference between `GetResourceMisc` and the sum of the four functions mentioned.

**Comment by adaneslavo** [comment]
I understand `GetResourcesMisc` is currently included in `iNumResourceTotal`?
Ok. I need to think of it a bit. So when I use `GetResourcesMisc` and subtract from it Franchises, Corporations, GPs and "Foreign Service, I will get a summary which will be the total of:
- Zealotry (+1% to strategics per converted city)
- Third Alternative (+100% to strategics)
If you would add up Russian UA function I think I could add some useful information.
I guess EIC and free buidlings are not counted into `GetResourcesMisc`?

**Comment by adaneslavo** [comment]
> If your congress proposal passes, this has to be done anyway, because extra resources would increase the monopoly threshold while normal ones wouldn‘t.

I feel it will fail. Too much resistance from major personas. It's almost like me vs whole VP developing team ;)

**Comment by adaneslavo** [comment]
I found these two:
`Method(GetStrategicResourceMod)`
`Method(GetResourceModFromReligion)`

**Comment by axatin** [comment]
Yes, if you take this value
`local iLocal   = pPlayer:GetNumResourceTotal(eResource, false) + iExports`
and subtract GetResourcesMisc from it, you get the Resources from Tiles (including Russia's UA) and Buildings. I will later write GetNumResourceExtra, and then you can use that to separate these two.

`GetResourcesFromFranchises`: See the "Office Bonus" of Hexxon Refinery
`GetResourcesFromCorporation`: Refers to the database table "Corporations_NumFreeResources", currently not used in base VP

All of these are counted towards monopolies. The only exception is that monopolies are not calculated at all if there are no resources on the map.

> Method(GetStrategicResourceMod) --> Third Alternative?
> Method(GetResourceModFromReligion) --> Zealotry?

Yes. But they don't return the number of resources you get, but the modifiers (200 and 1*(Number of following cities), respectively).

**Comment by adaneslavo** [comment]
> Yes. But they don't return the number of resources you get, but the modifiers (200 and 1*(Number of following cities), respectively).

Indeed, but I wonder why 200?

**Comment by adaneslavo** [comment]
![2023-10-03_17h32_10](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/243783df-a525-4d89-ae1c-db30923d2858)
![2023-10-03_17h57_08](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/e3ae9e6a-5a83-4e10-a85a-c5f443579760)

**Comment by axatin** [comment]
nice!

**Comment by adaneslavo** [comment]
If you have something more for me, then I will gladly try to use it :)

**Comment by axatin** [comment]
Implemented for next version. Use `GetNumResourceFromBuildings`

**Comment by adaneslavo** [comment]
Hell yeah! One step forward.
Does it count only EIC or all buildings (_Building_ResourceQuantity_)?

**Comment by adaneslavo** [comment]
@RecursiveStar It is not finished yet.

**Comment by axatin** [comment]
`pPlayer:GetResourceQuantityModifierFromTraits(iResource)` returns 100 for Russia and 0 for all others. you know the number of resources a player has after the modifier has been applied. use that to calculate backwards:

(Unmodified Number of Resources) = (ResourcesAfterModifier) / (100 + iMod) * 100
(Extra Russia Resources) = (ResourcesAfterModifier) / (100 + iMod) * iMod

**Comment by adaneslavo** [comment]
Thanks. I will try to test them out soon.
