### ISSUE TITLE
Unit visual beam select missing after disembark with movement left

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#10265]
_1. Mod Version (X.Y.Z). Current Version: 3.10.13

_4. Describe the Issue_
If a unit has movement left after disembark it no longer has the visual beam selector (white circle around unit), if you select another unit and than select it again work correctly.

_9. Screenshots of the Issue (Optional)_
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/49090452/8d7a0657-e830-4869-b44b-49b9c5c8d64d)

**Comment by axatin** [comment]
unfortunately this seems to be controlled by a part of the code we don't have access to
