### ISSUE TITLE
Multiplayer Desync 

### ISSUE THREAD

**Issue by Domonu** [LoneGazebo/Community-Patch-DLL#1026]
After multiple desync issues in multiplayer, I believe I have narrowed down the cause. When the AI turns are processing any attempt to move the map (by click and drag or sidescrolling) will cause a desync and the game reloads. This is 99% repeatable at least for the people I've been playing with. We both are using the same version of the patch in DLC form.

**Comment by ilteroi** [comment]
hmm. that's interesting. nominally display and game state should be decoupled. however, there may be a race condition somewhere which is exposed under high load? hard to debug in any case.

**Comment by LoneGazebo** [comment]
Using EUI? Could be the danger plot calculator in the plot tooltip, ilteroi.

**Comment by Domonu** [comment]
Yes, using EUI. It does seem to have something to do with the tooltip since that fails to load right before the game reload happens.

**Comment by LoneGazebo** [comment]
I'll remove the danger rollover from release candidates in the future, see if it helps.

**Comment by Adonis-VII** [comment]
Just wanted to weigh in that this problems exists with the non-EUI version as well. Using 12-16 release that Lynnes made. we had >100 desync turns until this I read this post. We've had 0 desyncs since I've stopped scrolling/moving the map at all.

**Comment by ilteroi** [comment]
@LoneGazebo : good idea with the tooltips. don't think the danger calculation is special though (it is side-effect free and furthermore only applies to visible plots). in general tooltips seem to be processed only when the lua interpreter is holding the game core lock (that's why it may take a while for them to show up when the AI is processing).

@Adonis-VII : is it about the scrolling or about tooltips? can you do some experiments?

**Comment by Adonis-VII** [comment]
It's the scrolling. 

Given the following steps for a normal turn:
1) AI Civs have turns
2) Crom has turns
3) Human Player turns
4) Last human player hits end turn, 2-3s pause where no icons are blinking before it returns to step 1

If any play moves the map during step 4, after they have hit end turn, the game will desync 100% of the time.  Scrolling as fast as you want during any other step is okay.

**Comment by LoneGazebo** [comment]
@Adonis-VII 
You've made sure that your video drivers are up to date? A long shot, but graphical redraw errors could be related to that. If not graphical, then it sounds like there's a phantom client-side calculation going on when tiles are revealed to the player. Possible fix could be to limit danger and plot calculations (perhaps even if in MP only) to only the active player?
