### ISSUE TITLE
Barrack culture displaying Bug

### ISSUE THREAD

**Issue by myclan123** [LoneGazebo/Community-Patch-DLL#10261]
_1. Mod Version (X.Y.Z). Current Version: 3.10.12_
3.10.12, with EUI

_3. List of Other Mods_

no other mods

_4. Describe the Issue_
The barrack should produce 2 culture with policy Militarism, but it displays as 4.

_9. Screenshots of the Issue (Optional)_
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/143814249/aaa78dcd-25d6-4c5d-b9d4-099b1f4bc202)

**Comment by azum4roll** [comment]
Is this still a problem?

**Comment by myclan123** [comment]
> Is this still a problem?

yes in 4.2.7, for Creative Expression will dipslay +6 culture for thost building
