### ISSUE TITLE
Infinite loop of impossible diplo suggestions by Aztecs

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#10267]
3.10.13
Win 11
Save: https://www.dropbox.com/scl/fo/rpehrf2ldmnkadygq34ar/h?rlkey=mje61hi4f72687rvtvshz7283&dl=0

The problem is Aztecs suggested impossible for the deal, and even if this was their suggestion they didn't want to accept it. Changing it was pointless, because when I changed and clicked to suggest something new, then it returned to initial values. As you can see points on the left and right are inconsistent. I ended up lowering GPT by 1 and clicking Accept without knowing what was the deal value.

![2023-09-27_18h36_58](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/6fdef0bd-2526-45bd-9afb-4dfd721ec338)

**Comment by PointMeAtTheDawn** [comment]
You should still be able to Propose a matching deal (instead of hitting 'what will'). The calculation is clearly broken, but that'll let you progress.

**Comment by adaneslavo** [comment]
Crap, I probably didn't attack a save. When I'm back at home in few hours I will. Sorry.

**Comment by adaneslavo** [comment]
Ok, it's there for the testing. Sorry for the delay.

**Comment by adaneslavo** [comment]
Another similar offer, this time from Austria:
![2023-09-28_20h45_00](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/e19537e8-0238-4667-8a07-c91a1c79073f)
[auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12752936/auto.zip)

**Comment by adaneslavo** [comment]
And another one
![2023-09-28_21h56_41](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/bd63bf3b-69f7-4e0d-89e3-cdcce490efb6)
[auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12753486/auto.zip)

**Comment by axatin** [comment]
The bug with the peace deals is fixed. Austria's deal is not a bug, renew deals are also offered if they aren't good enough anymore because the player should have the possibility to change the deal. She also says that it's a renew deal which needs to be improved.

**Comment by axatin** [comment]
Hmm, don't know, never paid attention to that. Maybe the button is shown only when the renew deal has a negative initial value?
