### ISSUE TITLE
3.10.10 - Frequent CTDs

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#10260]
_1. Mod Version (X.Y.Z). Current Version: 3.10.12_

3.10.10

_2. DirectX Version_

_3. List of Other Mods_

[ModList.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12721676/ModList.zip)

_4. Describe the Issue_

Pretty frequent CTDs over the last several turns. Sometimes reloading and pressing end turn will get me through it, often it just crashes out.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0332 AD-1912.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12721686/AutoSave_0332.AD-1912.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
I tried several times, but I don't get any CTDs here. Seems these are memory/graphics-related crashes.

**Comment by seroperson** [comment]
Can we maybe create new label, like "Memory issues"? I will check them as part of #10151.
