### ISSUE TITLE
Broken Research Agreement

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#10268]
3.10.14
Unfortunately no save.
![2023-09-27_19h58_52](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/6845aef4-b858-4d5f-a11b-a3bf08696963)

**Comment by axatin** [comment]
This is a bug, but without a save game it can't be fixed. Please reopen with save game if it happens again

**Comment by adaneslavo** [comment]
Ok, I will.
