### ISSUE TITLE
Synagouges Give Sceince even when not in WLTLKD

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#1027]
![2015-12-31_00006](https://cloud.githubusercontent.com/assets/11430209/12069486/bf61fd08-b000-11e5-9c5e-38e1ac0bd1c3.jpg)
![2015-12-31_00005](https://cloud.githubusercontent.com/assets/11430209/12069487/bf63f3d8-b000-11e5-82ad-0838478c69e4.jpg)

**Comment by Kolaris8472** [comment]
Adding the numbers it doesn't seem to be in effect. Looks like a UI bug.

**Comment by LoneGazebo** [comment]
Is just a lua bug, yep.
