### ISSUE TITLE
Anyway to easily calculate a city's total yields?

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1029]
Is there a quick method of calculating the sum of a city's yields, without going through and individually adding the value of each? I need the total value for Crimes, but something is causing a bit of a stutter when this is done, so I'm looking for possible ways to streamline the process.

**Comment by LoneGazebo** [comment]
Not really, as they're all calculated independently.

**Comment by JFDaly** [comment]
No matter. The addition of Crime as a yield should make up for it. Thanks.
