### ISSUE TITLE
Religion Event Bug

### ISSUE THREAD

**Issue by JSPiero** [LoneGazebo/Community-Patch-DLL#10299]
_Mod Version 3.10.14_
EUI included

_List of Other Mods_
4UC (v.87), Unique City-States (v.15.4), Even More Resources(v.11), Historical Religions Complete (v.45), Civic and Reform (v.21)

_Describe the Issue_
Player and AI are given the Way of Noble Truths/Way of the Pilgrim Event before Founding a Religion. Checked for similarities between Civic and Reform decisions to find obvious trigger, but could not find one (Triggered with and without any changes to early C&R options). Happened in two games, 2nd with Cleared Cache. First time was around Turn 45, the second game it happened around Turn 80.

______________________________________________________________________________________

_Save Game From 1 Turn Before_
AutoSave from Beginning of Game and Manual Save attached

_Screenshots of the Issue_
Screens from my own Event, and one showcasing AI receiving Event as well
![20231001213320_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/146751791/fbf9b3f8-6671-4f67-a4dd-df0ef9988c1f)
![20231001220542_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/146751791/c3560b68-b690-4a3f-86e9-12b09f6bbf44)

**Comment by axatin** [comment]
This is not an event from base VP, but from a modmod (community events?). Report the issue to the creators of the modmod.
