### ISSUE TITLE
Unit graphics fail in new naval mod

### ISSUE THREAD

**Issue by Tarzan737** [LoneGazebo/Community-Patch-DLL#10303]
_1. Mod Version (X.Y.Z). Current Version: 4.1.2_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

The icon fails 90 degree (just seen dreadnough and destroyer so far didnt continue the game)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![Skärmbild (13)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/20152388/28e22a91-83e0-4390-abe4-8d886ee7167f)

**Comment by azum4roll** [comment]
Looks like they're sinking 🤣
