### ISSUE TITLE
Hexxon Franchises multiplicate resources

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#10305]
3.10.14

**Hexxon Office** says: +1 Oil and +1 Coal for every 3 Hexxon Franchises.

But when you have 3 Hexxon Franchises, it looks like it is tied to a Franchise building, so every Hexxon Franchise gives +1 Oil and +1 Coal for every 3 Franchises. Bonus is multiplied by 3 Franchises, so the result is +3 Oil and +3 Coal instead of +1 Oil and +1 Coal.

I checked this function and it returns 3: `local iExtraFromFranchise = pPlayer:GetResourcesFromFranchises(eResource)`

![2023-10-03_18h13_37](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/8c66709d-9e17-4e1b-b6f4-f8b9a11b9037)

**Comment by axatin** [comment]
The franchise bonus is given for every _office_ you have. In your example you should have 3 offices in your cities which each provide 1 coal and oil.

**Comment by axatin** [comment]
You can have an office in every city, they are normal buildings you can build

**Comment by adaneslavo** [comment]
Ok.
