### ISSUE TITLE
Great Diplomat mission description missing text

### ISSUE THREAD

**Issue by Vordikk** [LoneGazebo/Community-Patch-DLL#10307]
_1. Mod Version_
4.1.2_

_2. DirectX Version_
Not related

_3. List of Other Mods_
Nothing, only VP mods downloaded with 4.1.2 release

_4. Describe the Issue_
Quite simple: missing text
"Conduct Diplomatic Mission" via Great Diplomat grants:
+X Influence
+30 TXT_KEY_VP_RESTING_INFLUENCE
+1 Paper

So the "issue" is simply missing text about increasing resting influence with city state

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
Not needed

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
Not needed

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
Not a crash

_8. Steps to reproduce the Issue (Optional)_
1) Create Great Diplomat and send it to city state territory
2) Move the mouse cursor to the ability description

_9. Screenshots of the Issue (Optional)_
![MO Tests](https://github.com/LoneGazebo/Community-Patch-DLL/assets/146865968/9710cb62-36ad-43f6-959e-21f6ce1a316d)

**Comment by Vordikk** [comment]
Thank you! :)

**Comment by hyuckkim** [comment]
Thank you!
