### ISSUE TITLE
Adding Crime as a yield

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1031]
In my quest to improve the performance of Crimes, I'd like to ask that YIELD_JFD_CRIME be added to the DLL just as with Heath and Disease - i.e. it doesn't need to be hooked up to anything specifically, just that its there and registers when returning NUM_YIELD_TYPES. This is beneficial as functions like City:GetYieldRate() seem to return the correct value (all yield calculating functions appear to work save plot-based ones, but that's irrelevant for Crimes), so long as the yield is properly added in the DLL (or whatever) - these functions work for Health and Disease, otherwise they just return seemingly random numbers. I think this would help performance immensely (calculation of Health and Disease is exceptionally smooth), and so would be much appreciated. Thanks!

**Comment by LoneGazebo** [comment]
Done!

**Comment by JFDaly** [comment]
Thanks. This'll be really useful.
