### ISSUE TITLE
Crash when selecting research in mid-game

### ISSUE THREAD

**Issue by woolymuffler** [LoneGazebo/Community-Patch-DLL#10316]
_1. Mod Version (X.Y.Z). Current Version: 4.1.2_

4.1.2

_2. DirectX Version_

_3. List of Other Mods_

Really Advanced Setup is only additional mod

_4. Describe the Issue_

Immediate crash going to research selection screen after completing corporations tech
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Arabia.Civ5Save.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/12805781/Arabia.Civ5Save.txt)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.dmp.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/12805786/CvMiniDump.dmp.txt)

_8. Steps to reproduce the Issue (Optional)_

Click on Research button in notifications

_9. Screenshots of the Issue (Optional)_

**Comment by woolymuffler** [comment]
Huh, interesting. I have 32GB of RAM (with 12GB GPU RAM) so that didn't occur to me as a possibility. I'll close everything out and try again. Thanks for checking.

**Comment by ryanmusante** [comment]
I wish Firaxis would revisit and release a remastered 64 bit engine.

**Comment by woolymuffler** [comment]
You know, I never had this issue on my older system, but I think I had set the large memory flag on the Civ 5 exe (years ago) with CFFExplorer and forgot to do that with my new system. I'll go ahead and close this issue out since it's not fixable and I can get past it
