### ISSUE TITLE
Feature Request: Unit:IsNearGreatAdmiral()

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1033]
Similar to Unit:IsNearGreatGeneral(), but for Great Admirals.

Or if it's convenient and is a little more general to help other modders.
>Unit:IsNearUnitType(UnitType unit)

**Comment by ilteroi** [comment]
in fact, IsNearGreatGeneral() should also trigger for admirals if you call it for a naval unit

**Comment by LoneGazebo** [comment]
So this isn't necessary?

**Comment by ilteroi** [comment]
don't think so, no.

**Comment by LoneGazebo** [comment]
Cool. Closing.
