### ISSUE TITLE
Statecraft opener giving nothing?

### ISSUE THREAD

**Issue by myclan123** [LoneGazebo/Community-Patch-DLL#10346]
_1. Mod Version (X.Y.Z). Current Version: 4.2.1_

4.2.0

_3. List of Other Mods_

None

_4. Describe the Issue_

The Statecraft opener policy should +1 every yield to capital for every 20 citizens in the empire, but in fact it gives nothing at all

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0140 AD-0600.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12846986/AutoSave_0140.AD-0600.zip)

_8. Steps to reproduce the Issue (Optional)_

Just count the yield of the capital. Use IGE to try to adopt the policy in another save, nothing has changed

**Comment by azum4roll** [comment]
Seems it's using division instead of multiplication. Currently you should get +1 yield when you have 500 citizens.

**Comment by myclan123** [comment]
> Seems it's using division instead of multiplication. Currently you should get +1 yield when you have 500 citizens.

sorry but why it is 500

**Comment by azum4roll** [comment]
Game correctly calculates it gives 0.05 yield (1/20) per pop (stored as 5).
Then it _divides_ (instead of _multiplies_) total population by this number, then divides it by 100.
Which gives 1 per 500 population.
