### ISSUE TITLE
Monopolies/Corporations Undismissable UI Bug

### ISSUE THREAD

**Issue by bdc0der** [LoneGazebo/Community-Patch-DLL#10348]
_1. Mod Version (X.Y.Z). Current Version: 4.2.1_
https://github.com/LoneGazebo/Community-Patch-DLL/releases/tag/Release-4.2.1 

_2. DirectX Version_

_3. List of Other Mods_

1 - Community Patch (v124)
2. Vox Populi (v17)
3. - VP EUI Compatability FIxes (v1)
4. - UI - Promotion tree for VP (v23)

_4. Describe the Issue_

**_Whenever I start the game, the monopolies/corporations UI pops up, and I can't dismiss it, effectively making the game impossible to play. Is this because I'm playing on a Mac? I manually installed the mods and followed the steps taken to install Vox Populi With EUI down to the letter._**

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

**_[Washington_0000 BC-4000.Civ5Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12847416/Washington_0000.BC-4000.Civ5Save.zip)_**

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

**_[Archive.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12847422/Archive.zip)_**

**_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
**

_8. Steps to reproduce the Issue (Optional)_

**_It's pretty simple, loading any game with the mods I have enabled on macOS (I got all of them from the link I provided) gives me this screenshot_**

_9. Screenshots of the Issue (Optional)_

<img width="1440" alt="Screenshot 2023-10-09 at 7 47 16 AM" src="https://github.com/LoneGazebo/Community-Patch-DLL/assets/119639394/409d294c-d557-414b-ba74-b4429f1c8c70">

**Comment by Cyclopia31** [comment]
Hello, it looks the same as when "Multiplayer Mods Workaround (v 1)" mod is activated, are you sure you do not have it activated ?

**Comment by seroperson** [comment]
VP is Windows-only mod, just like any other "DLL mod" because only Windows sources were open-sourced by Firaxis.

**Comment by bdc0der** [comment]
right, I forgot that .dlls won't run on Macos (no wonder the faster turn processing is a bust) but thanks for the clarification. oh well.
