### ISSUE TITLE
AI not accepting own peace deals

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1034]
![2016-01-01_00001](https://cloud.githubusercontent.com/assets/11132095/12073140/cda27aa6-b0d1-11e5-8a9d-dc46a77571f1.jpg)
![2016-01-01_00002](https://cloud.githubusercontent.com/assets/11132095/12073138/cda08cc8-b0d1-11e5-8b22-598fab875cf1.jpg)
![2016-01-01_00003](https://cloud.githubusercontent.com/assets/11132095/12073139/cda216ce-b0d1-11e5-907f-269e8604d915.jpg)

These screens tell a story, though I'm not exactly sure what. Gustavus is proposing a deal, yet the "max value" is supposedly 0. Gustavus won't accept the terms he is proposing, and the warscore tooltip implies that he would go for a small settlement.

Edit: This is the 12-29 beta

**Comment by joosegoose** [comment]
Another example:

![2016-01-02_00003](https://cloud.githubusercontent.com/assets/11132095/12076902/53bca09e-b186-11e5-8ce5-a661341350e8.jpg)

**Comment by LoneGazebo** [comment]
Odd!

**Comment by Edaka** [comment]
This happens with me when I'm proposing a peace deal. The odd thing is that the trade value counter appears, but it apparently shouldn't.

**Comment by LoneGazebo** [comment]
Will take a look. Replication savegames are nice.

**Comment by joosegoose** [comment]
Here's a savegame. It's a particularly good one, as Alex offers me peace on his turn and it appears to work. We are only confined to white peace when we meet on my turns.

[Alex won't accept own proposal.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/76508/Alex.won.t.accept.own.proposal.zip)

**Comment by LoneGazebo** [comment]
Thanks, fixed. False pDeal used doesn't have proper surrender value set.
