### ISSUE TITLE
Cannot build Citadel despite meeting requirements

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1035]
![2016-01-02_00001](https://cloud.githubusercontent.com/assets/11132095/12073430/ace20006-b0e6-11e5-8577-82c66ccd4705.jpg)

Adjacent to own territory, no adjacent forts/citadels, required technology to clear terrain, yet cannot build this Citadel. If this is WAD, an update to the changelog/tooltip saying "citadels cannot be built in enemy territory" is highly suggested :)

**Comment by LoneGazebo** [comment]
Can't build them outside owned territory anymore.

**Comment by joosegoose** [comment]
As I figured. Consider this a friendly suggestion for a
tooltip/pedia/changelog update :)

**Comment by LoneGazebo** [comment]
I don't think any element of the civilopedia states that you can use them in foreign land. If you find a spot that says this, I'll change it.

**Comment by joosegoose** [comment]
![2016-01-02_00002](https://cloud.githubusercontent.com/assets/11132095/12076885/d342ab16-b185-11e5-9d09-21ff68922eff.jpg)

"You can construct a citadel anywhere within your territory, or directly adjacent to your territory."

In BNW it did not matter if the tile was previously owned by another civ, you could build a citadel there if the requirements were met. There's nothing indicating otherwise for someone coming over to CPP...even a user that RTFM won't know, the changelog only mentions that forts and citadels can no longer be adjacent to one another.

**Comment by LoneGazebo** [comment]
I'll change that line. It was a an AI fix IIRC.

G
