### ISSUE TITLE
Build Actions Broken Tooltips

### ISSUE THREAD

**Issue by elonthelad** [LoneGazebo/Community-Patch-DLL#10368]
Mod version 4.2.2 (No EUI) 
Game version Steam 1.0.3.279

DX 10/11

Mods-
(1) Community Patch
(2) Vox Populi
(4a) UI - Promotion Tree for VP

Build action and great person action buttons have default Names & Descriptions, but they also inherit the Name & Descriptions of the last seen button tooltip. Issue needs no setup, just click on a worker and try to read their actions

[Catherine_0104 BC-0275.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12918542/Catherine_0104.BC-0275.zip)

[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12918521/Lua.log)

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/55890023/64350cef-1a84-40e1-8b53-98f30fdbb6bc)
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/55890023/976a78c7-1cdd-41a3-a228-d3ba58445259)
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/55890023/c21b1873-90d5-4879-ad2d-30022392dce6)

**Comment by axatin** [comment]
Fixed in 4.2.3
