### ISSUE TITLE
Icons for Polder and Ordo yield increases show up on the tech tree for non-Netherlands/Mongolia civs

### ISSUE THREAD

**Issue by reikken** [LoneGazebo/Community-Patch-DLL#10364]
Version 4.2.1 with EUI
no other mods

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/17669897/ffa14e95-8d05-4601-a020-679604afe4ec)

This is an anomaly that doesn't happen for other unique improvements. Moai yield increases only show the icons when playing Polynesia, for instance.

edit: looks like there's also another issue with polder yield increases
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/17669897/45deb24e-5295-4f32-b203-5a50e0e49e65)

**Comment by LessRekkless** [comment]
Your own screenshot shows that's not the case:
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/34615525/3f202f12-efb4-45d3-a9e8-69b9d422a5d2)

The second issue with Polder is an artifact of it actually being two improvements, one for land, one for water.

**Comment by LessRekkless** [comment]
The second issue is an artifact that the Polder is actually two improvements, one works on land, the other works on water.

**Comment by azum4roll** [comment]
Both are because the improvements aren't internally unique to a civ.

Polder (Water) should be relatively easy to fix, but technically a Khan (somehow) obtained by another civ can still build an Ordo (unlike Nau/Feitoria which is hardcoded to be Portugal only).
