### ISSUE TITLE
Cavalry upgrades into lancers

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1037]
That's according to merill from the forum.

**Comment by joosegoose** [comment]
Can confirm.

![2016-01-02_00004](https://cloud.githubusercontent.com/assets/11132095/12077741/4f5f444c-b1b9-11e5-9c0b-b1effc82d3ff.jpg)

**Comment by LoneGazebo** [comment]
Fixed
