### ISSUE TITLE
UnitPromotions_YieldModifiers is not working

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#10379]
I have this in my code:
```
INSERT INTO UnitPromotions_YieldModifiers 
            (PromotionType,         YieldType,             Yield)
SELECT         'PROMOTION_AMBRACIA',     'YIELD_PRODUCTION', 5;
```
According to what @azum4roll found it should work like this:
`City gains %Yield modifier from a Unit in this city (unit can be combat or civilian)`

But the problem is production in my city do not change when I'm garrisoning. No modifiers show up in the tootlips.

With unit:
![2023-10-21_12h47_43](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/d3cedf82-67e8-4f77-b47d-88802a230243)
![2023-10-21_12h46_35](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/dfb00a19-1007-4720-b967-9d433c197f75)
![2023-10-21_12h46_42](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/66494395-caac-49f3-96b8-21ccc120a736)

Without unit:
![2023-10-21_12h47_17](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/ea9c4ed6-49e2-4315-b1f9-f29ce32de8e6)
![2023-10-21_12h47_33](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/488b4bdc-b013-42f2-86c2-1c16ddd115a2)

**Comment by azum4roll** [comment]
Enable YIELD_MODIFIER_FROM_UNITS in CustomModOptions

**Comment by adaneslavo** [comment]
Confirmed. Thanks.
