### ISSUE TITLE
Unassigned spies are not shown in the espionage icon in diplo corner

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#10395]
3.10.14:
I captured a city-state where I had a spy. This spy is now free to use somewhere else. Unfortunately I have no info (number) on the icon, so I checked that only because other window in from Trade Opportunities said so... Otherwise I wouldn't know that.
![2023-10-25_21h08_25](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/c7dba896-268e-41a8-b637-670fdbc1fbab)
![2023-10-25_21h08_35](https://github.com/LoneGazebo/Community-Patch-DLL/assets/33016300/3a4af07e-53c5-4184-95c5-88c828bd76f6)

**Comment by axatin** [comment]
That's why you get a notification telling you that. The number is updated at the beginning of the next turn
