### ISSUE TITLE
Refinery description (minor)

### ISSUE THREAD

**Issue by Vordikk** [LoneGazebo/Community-Patch-DLL#10396]
_1. Mod Version 4.2.4_

_4. Describe the Issue_
Refinery which gives 1 coal, 1 oil and 1 iron has limitation. One part of tooltip says "not more than 5 per player" and other says "can have maximum 2 of them"

**Comment by azum4roll** [comment]
Need screenshot

**Comment by Vordikk** [comment]
Unlike Hall of Honor, here's other problem, i just understood that.
Text shows "Only X allowed per player" when it actually mean "Can construct X more"
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/146865968/82cba4ab-54c4-402d-8b00-b35729325671)

**Comment by bsesar** [comment]
The "Only 2 allowed per player" should probably be changed to "You can only build 2 more".

**Comment by azum4roll** [comment]
I don't think this line is needed. The building/unit help text already shows the limit(s).
