### ISSUE TITLE
God of War bonus yields aren't awarded upon city bombardment kills

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#10408]
Authority ones are, and there's nothing in the pantheon wording that makes me think it should work differently: in the screenshot, Barcelona attack killed a barbarian, while a military unit near Madrid killed another.

![civgowbug](https://github.com/LoneGazebo/Community-Patch-DLL/assets/53142313/f3d5aedf-cb57-4c8d-961f-1a7d32390042)

**Comment by azum4roll** [comment]
It's how vanilla God of War and Honor worked. I can change that (even for CP only, as it seems like a bug).
