### ISSUE TITLE
Religious pressure is subtracted

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1040]
Sorry I didn't take a better screenshot, but here it goes. The CS seen here is walled off by a single mountain from the main landmass. As a result, it can't be accessed by land only. Moreover, the land inbetween the CS and my nearest city is desert hills - a pretty rough terrain type.

As a consequence (I think) the CS had zero religious pressure, even though I have plenty of religious cities around. When I sent a trade route that was supposed to add +60 pressure, it actually added +58.
![pressure](https://cloud.githubusercontent.com/assets/12978597/12079741/fbf13baa-b24c-11e5-9811-ccd2b2693565.jpg)

**Comment by ilteroi** [comment]
well, if there's no trade path (potential trade route) to the city, it doesn't receive pressure. land paths are blocked here, but i assume a water route would have been possible - correct? so there should have been some pressure. 

why 58 instead of 60, i don't know. do you have the savegame?

**Comment by Edaka** [comment]
Sorry, I've been busy lately so forgot to answer. I'll definitely try to reproduce with just the CPP package to get that save, because this game was played with a load of mods and trying to use the save would be a pain in the neck. I'll report back when I get the chance.
