### ISSUE TITLE
Game freezes randomly (4.2.5)

### ISSUE THREAD

**Issue by scarredminer** [LoneGazebo/Community-Patch-DLL#10400]
_1. Mod Version (X.Y.Z). Current Version: 4.2.5_

Mod Version 4.2.5
EUI, 43 Civ version.

_2. DirectX Version_

DX11

_3. List of Other Mods_

None

_4. Describe the Issue_

My game freezes randomly and must be manually exited and reopened to continue playing, and I have struggled to recreate the freeze afterward. It always seems to occur during the city-state's turn, and happened 3 times, once every 6 turns to start my latest game, however this regularity could be chance. Looking in the logs, it may be 'ECONOMICAISTRATEGY_CITIES_NEED_NAVAL_TILE_IMPORVEMENT' which is the last line before the log ends.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0011 BC-3560.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13192169/AutoSave_0011.BC-3560.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[CityStrategyAILog_Antwerp_Antwerp.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13192172/CityStrategyAILog_Antwerp_Antwerp.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

No file was generated as game did not crash, just froze.

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by Vordikk** [comment]
Also it crashes in lategame sometimes even with turned off resourses and display production on every tile. Even tho it was just 4 players (1 hum + 3 AI) game on small map. Even tho i have quite much RAM and good CPU and GPU.
I'll send crash report when play and catch it again; prolly not soon, unfortunately.

**Comment by axatin** [comment]
I loaded your save and could play for 30 turns without any problems twice. No one else has reported any issues either. It's strange. You can try reinstalling the game and the VP mod, maybe that helps. If not, no idea what could have caused the issue or how to address it.
