### ISSUE TITLE
A bit close for comfort

### ISSUE THREAD

**Issue by michaelgo361** [LoneGazebo/Community-Patch-DLL#10417]
_1. Mod Version (X.Y.Z). Current Version: 4.2.7_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by michaelgo361** [comment]
1. 4.2.5
2. 11
3. 3rd/4th uc
4. Starting location too close to each other
9.
![Civ 4 5 2 Start](https://github.com/LoneGazebo/Community-Patch-DLL/assets/106539361/874560e7-37a1-4da5-b51e-342f22d02b6a)

**Comment by axatin** [comment]
save game needed. and logs.

which map settings do you use?

**Comment by n-core** [comment]
The map is too small. Try using IGE or Reseed (or debug menu) to reveal the map.
