### ISSUE TITLE
weird automated roads

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10411]
v4.2.5

automated workers are building strange redundant roads. intended?

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/1edd640f-4625-44cb-8e1b-9a722054e465)

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/d0ad17da-87ca-456f-a7a6-6f05354b34cb)

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/de245732-695d-483c-93d7-55c43dd4c9c1)

**Comment by KungCheops** [comment]
Maybe strategic roads should be disabled for human players

**Comment by ilteroi** [comment]
looks more random than strategic to me

**Comment by KungCheops** [comment]
Currently, every tile with a defensive modifier > 15% and is sufficiently close to a potential enemy is considered a strategic tile.

**Comment by KungCheops** [comment]
Currently, every tile with a defensive modifier >= 15% and is sufficiently close to a potential enemy is considered a strategic tile.

**Comment by azum4roll** [comment]
Wait, does that mean Inca builds roads on every mountain? What about Iroquois?

**Comment by cidk2000** [comment]
have seen this occur when i turn on automation with worker
![Roads](https://github.com/LoneGazebo/Community-Patch-DLL/assets/106168061/c9a0b83b-262d-429f-9352-720315dcfc0d)

sorry for the overly bright pic printscrn on windows 11 over does the brightness

**Comment by KungCheops** [comment]
> Wait, does that mean Inca builds roads on every mountain? What about Iroquois?

Iroquois "builds roads" essentially everywhere before railroads.
I think mountain tiles are ignored when looking for strategic tiles, may be an oversight (think it's connected to other parts of the AI but not sure).
