### ISSUE TITLE
City states don't build walls

### ISSUE THREAD

**Issue by NewFell0w** [LoneGazebo/Community-Patch-DLL#10412]
_1. Mod Version (X.Y.Z). Current Version: 4.2.7_

version 4.2.5

_2. DirectX Version_

_3. List of Other Mods_

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/149498749/fe544b50-58d9-4da3-b98c-1c17b9f43811)

_4. Describe the Issue_

I see no walls built by city states! Only Bucharest has mere walls (no castle) all other city states seem to be lacking this.

I use 4.2.5

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[PANAMA CONQUERED NEXT TURN.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13216671/PANAMA.CONQUERED.NEXT.TURN.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/149498749/d122afb5-0472-4fed-b87a-71b922a59203)

**Comment by NewFell0w** [comment]
This bug has some nasty side effects of course, in my last game,  two city-states were conquered in the early game by mere barbarians. I don't think I've ever seen that one before.

**Comment by ilteroi** [comment]
barbarians conquer cities only when the horde quest expires, so that is unrelated

**Comment by NewFell0w** [comment]
I don't recall such an even going on, but perhaps I missed it and just saw what I wanted to see. :)

**Comment by ilteroi** [comment]
anyway, the logs say you are right ...
```
231, Kuala Lumpur, Kuala Lumpur, PRE: Building 35, Walls, 1160, 4
231, Kuala Lumpur, Kuala Lumpur, SKIPPED: Building 35, Walls, tooexpensive, 4
```

i added an exception for defensive buildings to the maintenance cost check but the real question is, why are the city states so broke all of a sudden?

**Comment by cidk2000** [comment]
have seen this ai hit a cs with just 1 treb and a unique melee polynesian unit they didnt build city walls and was a walkover

**Comment by tomekpa** [comment]
Conquered two city states almost near Modern Era. Both 38 defence.
They were near each other and other AI would catch them in few turns..
Both had only market place and custom house..
I understand i could be unlucky, but considering 15% chance for building to destroyed and, that i have two 
instances, which should behave more or less the same it seems they are generally underdeveloped..

**Comment by ilteroi** [comment]
turns out minor players just never updated their gold income stats. so the going broke check was broken ...

**Comment by tomekpa** [comment]
Just curious, any estimations, when next release might be? Can this issue be fixed using some hotfix? Current state of city states is kinda bad, and i cant wait for this particular fix :)

**Comment by ilteroi** [comment]
check https://github.com/LoneGazebo/Community-Patch-DLL/issues/10473

**Comment by tomekpa** [comment]
I'm not sure i understood correctly, is this new build fix this issue? I mean, just by quick glance doesn't look like, but what do i know :) Or maybe i should expect those fixes to be added to this experimental build shortly?

**Comment by azum4roll** [comment]
I don't see anyone complaining in the new version, so I guess this is fixed?
