### ISSUE TITLE
CvCity::IsBlockaded vs CvCity::IsBlockadedTest

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1042]
getting to the finer points now ... i don't quite get the distinction between those two functions.

IsBlockaded() is used for unhappiness, concerns only cities with a harbor. if all water plots adjacent to the city are blockaded, the city is considered blockaded. a water plot is blockaded if an enemy ship is within two tiles of it. road connections to the city are not considered.

IsBlockadedTest() is used to give an attack bonus against the city. it counts friendly and enemy units on water tiles adjacent to the city. free tiles are ignored. this bonus seems a little arbitrary to me - it does not consider land units, but applies to land units also. it's also part of the reason why naval attacks are so easy (see forum discussion). if it did include land units in the count, it would almost always apply, and the effect could be achieved by tweaking unit strength vs city strength.

neither has direct influence on third-party trade routes (as far as i can see).

coming to the point, i propose 

- split IsBlockaded() into water and land parts. third party trade units should be recalled if their domain is blockaded.
- remove IsBlockadedTest() completely. the increased unhappiness already reduces defender combat strength

**Comment by LoneGazebo** [comment]
I'm fine with removing the bonus - it was added when the AI was still pretty bad at blockades, but they do better now than before. There's a lua function tied to BlockadedTest as well which we can leave.

Ideally, IsBlockaded() would check for war and, if war, check to see if there are friendly routes out of the city. If it can do that, it'd work (this would include route connections as well as trade connections).

**Comment by ilteroi** [comment]
ok, refactored the whole thing. let's see how it works out.
