### ISSUE TITLE
worker as pow on recap from barbs on 4.2.7

### ISSUE THREAD

**Issue by ChordaCiv** [LoneGazebo/Community-Patch-DLL#10424]
_1. Mod Version (X.Y.Z). Current Version: 4.2.7
_4. Describe the Issue_
after returning workers from barbarians they have POW debuff. dunno if that matters, chill barbs options is enabled.

**Comment by azum4roll** [comment]
The captured unit gains all the free promotions from traits, buildings, etc. before being returned. Not sure what can be done about it.

**Comment by axatin** [comment]
can't reproduce this in 4.5.1, seems to have been fixed
