### ISSUE TITLE
Destroyed Corporation does not show again in Buildings queue

### ISSUE THREAD

**Issue by tomekpa** [LoneGazebo/Community-Patch-DLL#10433]
_1. Mod Version (X.Y.Z). Current Version: 4.2.7_

_2. DirectX Version_

_3. List of Other Mods_

'(1) Community Patch'
'(2) Vox Populi'
'(3a) VP - EUI Compatibility Files'
'(4a) UI - Promotion Tree for VP'

'(9d) Reforestation for VP v.5'
'(over) More Unique Components for VP (v 87)'
'(overhaul) Even More Resources for Vox Populi (v 11)'
'(overhaul) More Wonders for VP (v21)'
'(overhaul) Unique City States for VP (v15.10)'
'(ui) Trade Opportunities for VP (v21)'
'Better Lakes for Vox Populi (v 2.5)'
'Civic And Reform (v 21)'
'Convert Caravans and Cargo Ships (v 4)'
'Global - Civilians Move After Purchase (v 2)'
'Global - Pro-rata Buildings Purchase (v 2)'
'Improved City View (v 20)'
'Maps - Rotate Start Position (v 13)'
'Monopoly Buildings for Vox Populi (v 3.5)'
'Provincial Palace (v 3)'
'TreeSuccession (v 37.12)'
'UI - Enhanced Demographics (v 6)'
'UI - No Auto-Embark Workers (v 7)'
'UI - Overlay Barbarians (v 8)'
'UI - Overlay City Limits (v 8)'
'UI - Overlay Luxuries (v 3)'
'UI - Overlay Resources (v 11)'
'UI - Overlay Road And Rail (v 9)'
'UI - Overlay Unimproved Tiles (v 1)'
'Units - Cheap Workboats (v 2)'
'Units - No Mechs (v 6)'
'Vox Populi'\''s Bare Necessities (v 12)'
'Worker Mountaineering (v 2)'

_4. Describe the Issue_

Destroyed Corporation does not show again in Buildings queue

China built Giorgio Armeier (I have global monopoly on Silk) 
Indonesia build Centaurus Extractors (Later i had monopoly on horses)
Brazil had TwoKay Foods

China was conquered by Mongols, Shanghai with corpo was their last city.
I Conquered Jakarta, but it wasnt their last city.
Then i conquered Indonesia entirely.

All those corporations disappeared from the view of Global Corporations.
All are showed under view "Your Corporation" not grayed.
Other built, not destroyed are greyed with Civ Icon
However only Hexxon Refinery is available to build.

This happend to me also long time ago like 2.X.. thou, didn't do anything with that, just build other Corporation back then.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

https://filetransfer.io/data-package/xgqN0wrV#link

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![CivCorpoReport](https://github.com/LoneGazebo/Community-Patch-DLL/assets/21251138/fb84ea55-ffd2-4927-947b-7bc287cda35b)

**Comment by azum4roll** [comment]
The headquarters are World Wonders, which cannot be built again even after being destroyed.

**Comment by tomekpa** [comment]
Wiki says:
"A destroyed Corporation immediately becomes available to be founded again by any civilization in the world. There is no restriction in the number of times a Corporation may be established in a game. "

So this is a bug?

**Comment by azum4roll** [comment]
Wait, there's actually code (CvPlayerCorporations::DestroyCorporation) to decrement global building count when a corporation is destroyed.

Did you get a notification that a corporation is destroyed?

**Comment by tomekpa** [comment]
I actually don't remember, sorry :) 
Usually about turn 400 modern/atomic, there is tons of notifications, and i usually briefly look at them, so i could miss it any way.
I know, that one turn, corporation were present in global corporation panel, and next didn't.

**Comment by tomekpa** [comment]
Just test in 4.5.1, still after destroying Headquaters, nobody can build them
