### ISSUE TITLE
Request: make illiteracy/poverty unhappiness visible in trade route preview for cities that don't have harbors/caravansaries

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1043]
At the moment the unhappiness only seems to be shown for cities with a harbor (caravansary too, I presume, but haven't tested). Ontong Java on the screenshot had a handful of both illiteracy and poverty unhappiness, but it wasn't displayed. That was true for any city without a harbor.
![tr preview1](https://cloud.githubusercontent.com/assets/12978597/12079841/8c14abe2-b250-11e5-9291-74bac2bc3f2d.jpg)
![tr preview 2](https://cloud.githubusercontent.com/assets/12978597/12079842/8de658ee-b250-11e5-8e6e-f2905b6af920.jpg)

**Comment by LoneGazebo** [comment]
Can't replicate the issue, sorry. Seems to work on my end.
G

**Comment by LoneGazebo** [comment]
Fixed the bug, which fixed your error. Yay.

**Comment by Edaka** [comment]
Awesome!
