### ISSUE TITLE
Polynesian dromons get the 'cannot enter deep ocean' promotion when upgraded to galleasses

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1044]
I think this one has been addressed at least a couple of times by now, but it's still there in the 12/29 version. Basically, newtrained galleases don't get this promotion and therefore can enter ocean tiles. However, galleases that are created by means of upgrading dromons get the promotion and therefore can't cross oceans.

**Comment by LoneGazebo** [comment]
This fell off my radar, sorry. I'll look at fixing it for the next version.

**Comment by Edaka** [comment]
Sorry? Never!

Another thing to look out for with galleasses: judging from this post, it seems that newly trained galleasses for civs other than Polynesia don't receive the promotion right away, but only after a reload. I say newly trained because upgraded galleasses definitely get the promotion, as I described initially. I could've misunderstood, though.
http://forums.civfanatics.com/showpost.php?p=14111671&postcount=4191

**Comment by LoneGazebo** [comment]
I've fixed it for Polynesia.
