### ISSUE TITLE
4.2.7 - (AI) Top science civ not building SS parts.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#10446]
_1. Mod Version (X.Y.Z). Current Version: 4.2.7_

4.2.7

_2. DirectX Version_

_3. List of Other Mods_

[ModList.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13291499/ModList.zip)

_4. Describe the Issue_

As you can see in this screenshot (using IGE), Siam isn't building any SS parts, just science process, even though they are only 1 tech from the completed set and have only built one part so far.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Pacal_0429 AD-2009.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13291501/Pacal_0429.AD-2009.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs - Copy2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13291517/Logs.-.Copy2.zip)
[Logs - Copy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13291519/Logs.-.Copy.zip)

copy2 is actually a z01 file (split archive)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/20593976/15038a4b-724c-49af-abee-be0b5110c42f)

**Comment by bsesar** [comment]
Can you check if there are any spies in their cities that can build SS parts?
