### ISSUE TITLE
4.2.7 - (AI) AI ignores gorgeous tundra land

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#10445]
_1. Mod Version (X.Y.Z). Current Version: 4.2.7_

4.2.7

_4. Describe the Issue_

This has been a long outstanding problem. The AI just ignores the large tundras of communitas, even though they are often filled with resources (see screenshot). There are some gorgeous cities to be made in that tundra, but the AI ignores it.

_9. Screenshots of the Issue (Optional)_
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/20593976/944055a6-ac4b-4105-9315-8200ff9134c2)

**Comment by azum4roll** [comment]
How are they supposed to connect the cities?

**Comment by ilteroi** [comment]
duplicate #10422
