### ISSUE TITLE
The mod either crashes for me or just breaks things

### ISSUE THREAD

**Issue by TheBlackRay** [LoneGazebo/Community-Patch-DLL#10448]
1. Mod Version: 4.2.7
I'm currently using the full install of Vox Populi with EUI no extra civs. 
I have also **tried** using the no EUI version.

2. DirectX Version: 
**10/11** 

4. List of Other Mods
I am not using **any** other modifications. 
The game is on the correct version with all DLC enabled on Windows 11 home edition.

5. Describe the Issue:
As soon as finish setting up a game and I start it I'll receive a ton of popups saying: **Failed to load** all sorts of stuff; it wont show visuals but I can still hear the game playing in the background. **It seems to partially be EUI** because I installed the version without EUI and it worked to some extent, unfortunately it would **crash** after a while of playing only this time without a popup.

______________________________________________________________________________________
6. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)
Unfortunately I did not know about the warning for saving every turn so it might be pointless to attach my savegame from playing with **no EUI.** Not that I have it anymore anyways, **I attempted a clean install** to see if that would fix the crashing but it did not so apologies.

7. Logs (ALWAYS ATTACH THESE IF POSSIBLE)
_No log either sorry._  **:(**

8. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)
**Crap!** _I would have had one but I did a clean install before coming to here for help!_

9. Screenshots of the Issue (Optional)
![Screenshot 2023-11-09 113321](https://github.com/LoneGazebo/Community-Patch-DLL/assets/65493653/50484fa2-7509-43fb-9bae-0e353b630b0b)
![20231109113358_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/65493653/8aac8e5f-40e3-4c09-8e52-046e701e78e2)

**Comment by axatin** [comment]
Please check if you specified the correct folder for the UI files during installation.
![install](https://github.com/LoneGazebo/Community-Patch-DLL/assets/95587882/f7d1e208-131b-438f-906c-3c8ab5f316b5)
The correct folder is the one that contains the following files:
![folder](https://github.com/LoneGazebo/Community-Patch-DLL/assets/95587882/98d258c3-e933-4cb5-9f7a-ee48e73517b4)

If VP is installed correctly, you will find a folder "VPUI" in Assets > DLC.

**Comment by TheBlackRay** [comment]
Aha! It seems that the default path: C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Civilization V was incorrect for my system, my path was C:\SteamLibrary\steamapps\common\Sid Meier's Civilization V and the VPUI folder is now present. 
![Screenshot 2023-11-10 143744](https://github.com/LoneGazebo/Community-Patch-DLL/assets/65493653/c48133ce-fc03-428a-91ab-88580ae21ee6)

Thank you very much for assisting me.  :)
