### ISSUE TITLE
Strange bug w/Great Person generation & less important fixed spawning on custom map.

### ISSUE THREAD

**Issue by TheBlackRay** [LoneGazebo/Community-Patch-DLL#10457]
_1. Mod Version: 4.2.7_
(1) Community patch
(2) Vox Populi
(3a) VP - EUI compatibility files
(4a) UI - VP promotion tree

_3. List of Other Mods_
+Fast Animations+ (v 501)
=Aquatic Resources= (v 4)
=Furious Turns= (v 1)
Barbarians - Unlimited Exp (v 2)
Fate Zero -- Arturia's Britain Civilization [BNW] (v 8)
Femboy's (v 4)(religion mod I am making, [not public yet/occurs with and without]
Fire Emblem - Mila's Zofia (v 1)
Haruhi Suzumiya Series - SOS Brigade (v 2)
R.E.D. Modpack (v 27)

_4. Describe the Issue_
Basically there's a weird issue going on where my spawn is fixed and I crash after a while.
I am using the VP mod on a custom map named Enochs Ascent 2 which is my favourite custom. Anyways I was playing the map with your guy's mod and a whole bunch of others no problems, but for some reason as of today my spawn is always fixed no matter if start bias is enabled or disabled. At first I honestly kind of just said screw it and kept playing but no matter what it will crash eventually, it might be after 100 turns or it might be as soon as a few turns in. I haven't the slightest idea why this has occurred, I've disabled VP and tested the map after and the fixed spawning goes away, although I haven't bothered playing a full game to see if it crashes after that. What's even more strange is it doesn't happen on vanilla maps, but I don't play those very often. There's also this weird thing as Japan after you get a great general it will basically put you in an infinite loop of spawning great people every turn. 

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[AutoSave_0032 BC-2080.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13330650/AutoSave_0032.BC-2080.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13330696/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
[CvMiniDump.dmp](https://github.com/LoneGazebo/Community-Patch-DLL/files/13330655/CvMiniDump.dmp)

_8. Steps to reproduce the Issue (Optional)_
Honestly I just played like normal.

_9. Screenshots of the Issue (Optional)_
Here's the location where my spawns fixed, although I don't know if this matters at all.
![Screenshot 2023-11-12 124428](https://github.com/LoneGazebo/Community-Patch-DLL/assets/65493653/cb74636d-4de3-47b2-898b-f8ffbb90aecd)

**Comment by axatin** [comment]
I can't load the save game without the Femboy's mod, can you attach it here as a zip-file?
