### ISSUE TITLE
Crush to desktop, repeatable

### ISSUE THREAD

**Issue by tomekpa** [LoneGazebo/Community-Patch-DLL#10455]
_1. Mod Version (X.Y.Z). Current Version: 4.2.7_

_2. DirectX Version_

_3. List of Other Mods_

'(1) Community Patch'
'(2) Vox Populi'
'(3a) VP - EUI Compatibility Files'
'(4a) UI - Promotion Tree for VP'

'(9d) Reforestation for VP v.5'
'(over) More Unique Components for VP (v 87)'
'(overhaul) Even More Resources for Vox Populi (v 11)'
'(overhaul) More Wonders for VP (v21)'
'(overhaul) Unique City States for VP (v15.10)'
'(ui) Trade Opportunities for VP (v21)'
'Better Lakes for Vox Populi (v 2.5)'
'Convert Caravans and Cargo Ships (v 4)'
'Global - Civilians Move After Purchase (v 2)'
'Global - Pro-rata Buildings Purchase (v 2)'
'Improved City View (v 20)'
'Maps - Rotate Start Position (v 13)'
'Monopoly Buildings for Vox Populi (v 3.5)'
'Provincial Palace (v 3)'
'TreeSuccession (v 37.12)'
'UI - Enhanced Demographics (v 6)'
'UI - No Auto-Embark Workers (v 7)'
'UI - Overlay Barbarians (v 8)'
'UI - Overlay City Limits (v 8)'
'UI - Overlay Luxuries (v 3)'
'UI - Overlay Resources (v 11)'
'UI - Overlay Road And Rail (v 9)'
'UI - Overlay Unimproved Tiles (v 1)'
'Units - Cheap Workboats (v 2)'
'Units - No Mechs (v 6)'
'Worker Mountaineering (v 2)'

_4. Describe the Issue_

When i press next turn, Celts have their turn, and the game crushes. Did load and do next turn like 6 times.
Also i did 1 turn back, make dummy turn in hope something will change, but crush again. 
Usually, early game, it helped sometimes, but not this time.
I had similar scenario in one of my previous games, but gave up with intent of longer break :)
In previous game also had Celts, and also it was late game, more or less Atomic/Modern.

EDIT:
I played 2 more games starting from Modern era, second game crushed on turn 35.
Third game crushed about turn 65. 
In both cases, load, and next turn caused "reliable" crush, so there is some issues there.
I'm not sure about 2nd game, but first and third were crushing just after notification, that nuke was launched.
The nukes were already flying few times by different civz, so maybe its some correlation, but rather not the main cause.
In third game i turned off  mod "Units - No Mechs (v 6)", since i kinda felt this might be the reason, but crush still
happened.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Genghis Khan_0484 AD-1894.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13327667/Genghis.Khan_0484.AD-1894.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13327670/Logs1.zip)
[Logs2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13327672/Logs2.zip)
[Logs3.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13327673/Logs3.zip)

Logs1 are those that i zipped after turning on logging. Logs2 and Logs3 is same thing. Just load game, removed logs directory,
pressed next turn, and zip, so that they should be clean.

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.dmp](https://github.com/LoneGazebo/Community-Patch-DLL/files/13331013/CvMiniDump.dmp)

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
you use a lot of mods, and I can't reload the save game anymore because some of them are outdated by now. In general, the more modmods are used, the higher the chance of crashes. In the versions after 4.2.7., a lot of crashes have been fixed, maybe this one is also solved by now.
