### ISSUE TITLE
Espionage Overview sorting by "Spy Owner" or "Target Player" clears the Active Spy Effect list (minor)

### ISSUE THREAD

**Issue by tomekpa** [LoneGazebo/Community-Patch-DLL#10462]
_1. Mod Version (X.Y.Z). Current Version: 4.2.7_

_2. DirectX Version_

_3. List of Other Mods_

'(1) Community Patch'
'(2) Vox Populi'
'(3a) VP - EUI Compatibility Files'
'(4a) UI - Promotion Tree for VP'

'(9d) Reforestation for VP v.5'
'(over) More Unique Components for VP (v 87)'
'(overhaul) Even More Resources for Vox Populi (v 11)'
'(overhaul) More Wonders for VP (v21)'
'(overhaul) Unique City States for VP (v16)'
'(ui) Trade Opportunities for VP (v21)'
'Better Lakes for Vox Populi (v 2.5)'
'Convert Caravans and Cargo Ships (v 4)'
'Global - Civilians Move After Purchase (v 2)'
'Global - Pro-rata Buildings Purchase (v 2)'
'Improved City View (v 20)'
'Maps - Rotate Start Position (v 13)'
'Monopoly Buildings for Vox Populi (v 3.5)'
'TreeSuccession (v 37.12)'
'UI - Enhanced Demographics (v 6)'
'UI - No Auto-Embark Workers (v 7)'
'Units - Cheap Workboats (v 2)'
'Worker Mountaineering (v 2)'

_4. Describe the Issue_

As in tile. Espionage Overview sorting by "Spy Owner" or "Target Player" clears the list 
Sorting by Turns start/end and effect works correctly, the list is properly sorted.
But when sorting mentioned column makes the whole list disappear. However, the list appears again correctly 
sorted, when you use working columns. 
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![obraz](https://github.com/LoneGazebo/Community-Patch-DLL/assets/21251138/3987dba8-ebaf-4d97-8091-2bf275becefe)

**Comment by axatin** [comment]
Not going to fix, the whole espionage system will be reworked in the next version.

**Comment by Vordikk** [comment]
Wow. Is there an approximate time till release?

**Comment by axatin** [comment]
Maybe in two or three weeks.

**Comment by Vordikk** [comment]
Thank you.
