### ISSUE TITLE
great wall unimpressed by my gunpowder

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10469]
v 4.2.5

description says great wall becomes obsolete at gunpowder but that is a bit tricky - whose gunpowder? attacker or defender? depends on the effect i guess ... for the border obstacle i feel it should be the attacker, but that is tricky to code. so maybe no obsolescence at all? it's the only wonder with that feature anyhow.

**Comment by Vordikk** [comment]
I'd propose to change the effect entirely, so it won't be obsolete, and thus no questions.
Something like:
a) "Passing through border costs 1 additional turn for infantry and all turns for other units" (somewhat similar to Mine Field, but with an exception for movement without penalty like on scouts), and requires Walls on city territory to provide an effect
Additionally it may work when passing in both sides. Prolly OP.
b) Passing through border on any side deals minor damage to enemy units (5-10)
c) "Great Wall" simply buffs walls in cities (like in some others mods)

**Comment by Tekamthi** [comment]
yeah my understanding is that any obsolesence is done via the building owner's tech.  imo its imperfect but reasonable abstraction.

I think there's not a lot of obsolesence overall in VP.  Thematically it makes a lot of sense to have the great wall obsolete, whether its necessary gameplay-wise however is another matter

**Comment by axatin** [comment]
agree that thematically the movement effect should obsolete for the attacker, but that would be completely new code and not easy to implement. The wonder gives also other bonuses like increased military supply cap that have nothing to do with any attackers. However, this balance discussion should be continued on the forum.

**Comment by Vordikk** [comment]
I didn't mean to open balance discussions, this was more about avoiding technical difficulties in units behaviour, which is seemingly more important in this case than balance.
Also, i don't use that forum and won't ever use, so here i go. hf :)
