### ISSUE TITLE
Caravels can't enter ocean

### ISSUE THREAD

**Issue by mikes61293** [LoneGazebo/Community-Patch-DLL#1046]
On the 1/3/16 version I'm running into an issue where caravels can not enter ocean tiles until astronomy is researched as opposed to at compass.

**Comment by LoneGazebo** [comment]
thread link: http://forums.civfanatics.com/showpost.php?p=14111871&postcount=4194

**Comment by LoneGazebo** [comment]
Ilteroi, I think we need to add an exception for naval units that do not have the 'no ocean passable until astronomy' promotion. If they don't have this promotion, they should be able to cross with or without astronomy.

**Comment by ilteroi** [comment]
can confirm. caraval doesn't have the deepwater promotion. can i ask you to add it? i don't know how. maybe add it to the great admiral also.

**Comment by LoneGazebo** [comment]
There isn't a promotion that allows deepwater, only one that prevents it. We need to treat naval units as capable of going anywhere unless they have promotion penalties.

**Comment by ilteroi** [comment]
but what about MOD_PROMOTIONS_CROSS_OCEANS then?

**Comment by LoneGazebo** [comment]
Silly me, yes, there's that, but the problem with it is that it is a modded element, thus standard CP-only units (or uniques from modded civs) would not be supported by that function. It'd be far more mod-friendly to have it be 'can ocean travel unless x' instead of 'cannot ocean travel unless x' (as it is now).

**Comment by ilteroi** [comment]
yeah, i concluded the same in the meantime. reworked CanEnterTerrain() again. this seems to be the trickiest part in the whole DLL

**Comment by LoneGazebo** [comment]
Heh, yeah. Considering that the vast majority of the game's 'interaction' is moving x unit to y hex, it is not surprising that this element is problematic.

**Comment by LoneGazebo** [comment]
Also, http://forums.civfanatics.com/showpost.php?p=14113042&postcount=4201

**Comment by ilteroi** [comment]
hmm. the fact that he says optics makes me suspicious. we only have fishing and sailing, now do we?

**Comment by LoneGazebo** [comment]
Right. If you can build a workboat, you should be able to build a fishing boat improvement. Unless he's talking about the vanilla tech tree, in which you get workboats before you get embarkation (which could be the problem).

G

**Comment by Iamblichos** [comment]
This isn't how you want to go about it I guess, but in the CustomModOptions Table, there is PROMOTIONS_CROSS_OCEANS, and then you can just give pre-Astronomy units the PROMOTION_CAN_CROSS_OCEANS promotion that need it.
