### ISSUE TITLE
Random city name changes/deletion

### ISSUE THREAD

**Issue by tomekpa** [LoneGazebo/Community-Patch-DLL#10463]
_1. Mod Version (X.Y.Z). Current Version: 4.2.7_

_2. DirectX Version_

_3. List of Other Mods_

'(1) Community Patch'
'(2) Vox Populi'
'(3a) VP - EUI Compatibility Files'
'(4a) UI - Promotion Tree for VP'

'(9d) Reforestation for VP v.5'
'(over) More Unique Components for VP (v 87)'
'(overhaul) Even More Resources for Vox Populi (v 11)'
'(overhaul) More Wonders for VP (v21)'
'(overhaul) Unique City States for VP (v16)'
'(ui) Trade Opportunities for VP (v21)'
'Better Lakes for Vox Populi (v 2.5)'
'Convert Caravans and Cargo Ships (v 4)'
'Global - Civilians Move After Purchase (v 2)'
'Global - Pro-rata Buildings Purchase (v 2)'
'Improved City View (v 20)'
'Maps - Rotate Start Position (v 13)'
'Monopoly Buildings for Vox Populi (v 3.5)'
'TreeSuccession (v 37.12)'
'UI - Enhanced Demographics (v 6)'
'UI - No Auto-Embark Workers (v 7)'
'Units - Cheap Workboats (v 2)'
'Worker Mountaineering (v 2)'

_4. Describe the Issue_

I was playing England on Archipelago. When i settled like 7th city it showed with empty name, this was kinda strange, so 
i just name it by myself and just play along.
But later, i noticed, my Polish ambassador is in city named "2", that was strange, but i figure, maybe i was sleepy and in fact only looked at the star indicating capitol :)
But then, it changed name of my "York" to empty name. This city had same name last 300 turns, so i realised something in fact is 
happening without my permission :)

On the second screen can be seen that two of Sweden cities were renamed: Turku and Uppsala in game are empty/Single character (Milan is ok, just view was too short to make good screenshot). 

It seemed like isolated event, like some event trigger one time thing, thou, i played like few games and noticed this few first time. Since my last game finished with crash, i restricted amount of mods.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[NAMES_Elizabeth_0324 AD-1520.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13400738/NAMES_Elizabeth_0324.AD-1520.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13400741/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![obraz](https://github.com/LoneGazebo/Community-Patch-DLL/assets/21251138/5dba2c67-e42c-4799-a821-31e660d961bd)
![obraz](https://github.com/LoneGazebo/Community-Patch-DLL/assets/21251138/cd7de27e-acad-41bc-a817-3e9f10fae5a4)

**Comment by axatin** [comment]
Hard to say what causes this, I assume it's an issue with one of the mods you use. Don't see a way to figure out the exact reason using just the logs and the autosave. 

By checking the logs, it's at least possible to see when the name changes happened. For example, the last entry in "CityStrategyAILog_England_York.csv" is from turn 309, so the name changed in turn 309 or 310. I'll close this ticket for now, but if the issue still exists in the current VP version, you can change the game options to make an autosave every turn, and then check the logs and open a new issue with a save game from directly before one of the name changes.
