### ISSUE TITLE
Great Admiral from Mayan Long Year can't enter oceans.

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#1047]
Copied from [Civfanatics:](http://forums.civfanatics.com/showpost.php?p=14112341&postcount=4197)
Using the latest 3/1/2016 version and I started a game as Maya. During the "Long count GP" selector screen the text describes the Great Admiral as being able to cross oceans without the necessary techs. This doesn't appear to be working in this version or the text for that screen hasn't been updated to reflect a change, not sure if it is a change or not.

**Comment by ilteroi** [comment]
see #1046
