### ISSUE TITLE
Experimental Build - Ancient Ruins won't activate

### ISSUE THREAD

**Issue by iJuanHello** [LoneGazebo/Community-Patch-DLL#10474]
_1. Mod Version (X.Y.Z). Current Version: 4.2.7_

4.2.7 Ex

_2. DirectX Version_

11

_3. List of Other Mods_

VP Community Events
Dolen2 Ethnic Diversity
Global Warming
Global Warming Congress
Great Proph Historical Names
Music Changer
Quick Turns
Civ VI Style City Names

_4. Describe the Issue_

Standing on a set of ancient ruins that won't activate. Going to start new game with ruins so I can report on tact AI as requested, but figured I'd report this bug since I've got it
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0001 BC-3960.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13451443/AutoSave_0001.BC-3960.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13451451/logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13451466/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by usadefcon1** [comment]
Ancient Ruins can only be activated by recon now, were you using a recon unit?

**Comment by iJuanHello** [comment]
Nope, it was a warrior.

**Comment by usadefcon1** [comment]
That's intended behavior now. Only recon can activate ruins.

**Comment by iJuanHello** [comment]
Oh whoops, I read your comment wrong at first. Thanks!
