### ISSUE TITLE
Repeatable CTD (Experimental version)

### ISSUE THREAD

**Issue by iJuanHello** [LoneGazebo/Community-Patch-DLL#10485]
_1. Mod Version (X.Y.Z). Current Version: 4.2.7_

Experimental build

_2. DirectX Version_

dx11

_3. List of Other Mods_

Community Events
8a Enhanced Air Warfare 4VP
Dolen2's Ethnic Diversity
Global Warming
Global Warming Congress
Great Prophet Historical Names
Music Changer
Quick Turns
Civ 6 Style City Names

_4. Describe the Issue_

Game ctds while Korea's (AI) turn is processing
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0396 AD-1772.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13496341/AutoSave_0396.AD-1772.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13496349/logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13496353/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

I've included 2 auto saves; the turn before and the turn of. On the turn of the world congress, just skip to next turn and the game will CTD while Korea's turn is processing at the bottom of the screen

_9. Screenshots of the Issue (Optional)_

**Comment by ilteroi** [comment]
updated https://github.com/LoneGazebo/Community-Patch-DLL/issues/10473 - this should fix it

**Comment by iJuanHello** [comment]
Works perfectly, thank you! In the modern era of my second game with this build. I'm taking notes along the way and I'll add the feedback to your #10473 thread once this game is wrapped up.
