### ISSUE TITLE
city razing, war score, deal value

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10484]
4.2.7

washington declared war on me around T130, but i was prepared so i quickly captured city from him. so far so good. situation:

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/a1935647-1cb9-4f89-b338-b8a23edd07f4)

but i started razing the city and this catapulted my warscore to crazy values. in the end up to 74. 

T143: they make a crazy peace offer, even offering me another city because of the crazy 23k plus deal value! although from a military perspective they were under no pressure. (didn't accept to see how this develops)

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/bb95fab6-b5d6-4e5b-99d7-3ce4b4d98d77)

T150: warscore 56, deal value 465

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/dff7da59-bc05-4056-813d-baf72554e87a)

T153: warscore 42, deal value 212

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/8e7f4989-4658-47fb-ab8f-69db24510e2b)

T156: now they don't want to make peace at all ... still warscore 42!

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/6b2267d4-b18b-4b16-bdcd-fb90d057e4d2)

all the while the military situation did not really change, i never even got close to laying siege to boston.

so all of this is weird, but two things stick out:

1. why does razing change the war score, the city is lost already! seems like double dipping
2. deal value should never be so high if the military situation is stable (no city under siege)

**Comment by tomekpa** [comment]
Had same situation, Persia offered me 20k or maybe even more deal and on of his city, but the city was in bad spot to defence and resource wise and  i wanted his other city more, so i took other city, and deal value drop to like 400-100 dont rly remember.. 
I was thinking, maybe he knew the treat, so he was prepared to give me good deal, but after i took his city, "the deal was off"..
I was suspecting, that kind of logic could be too refined for AI, but then again, guys program how AI behaves, so it was rude to assume its impossible :) .. so i kinda, just notice it and play along and didn't thought about it too much..
Thou i dont rly remeber how warscore numbers changed.

**Comment by axatin** [comment]
> 1. why does razing change the war score, the city is lost already! seems like double dipping

you can make a congress proposal to suggest this balance change

> 2\. deal value should never be so high if the military situation is stable (no city under siege)

to explain the internal logic a bit: the AI uses the warscore to decide what to give away. For example, if the warscore is > 60 and some other conditions are fulfilled, they are willing to give away a city. A similar logic is used to decide if they give away resources or gold (and what amount). _After_ that's done, the deal value is calculated and shown in the UI, and the human can change the offered items as long as the deal value threshold is not exceeded.

So, the deal value is a bit misleading, it is **not** calculated to determine what to give away, but the other way around.

**Comment by azum4roll** [comment]
Have you changed the item valuation so that they're valued at the winner's (perceived) value, not the loser's?

**Comment by axatin** [comment]
> Have you changed the item valuation so that they're valued at the winner's (perceived) value, not the loser's?

Yes

**Comment by ilteroi** [comment]
> > 1. why does razing change the war score, the city is lost already! seems like double dipping
> 
> you can make a congress proposal to suggest this balance change
> 
> > 2. deal value should never be so high if the military situation is stable (no city under siege)
> 
> to explain the internal logic a bit: the AI uses the warscore to decide what to give away. For example, if the warscore is > 60 and some other conditions are fulfilled, they are willing to give away a city. A similar logic is used to decide if they give away resources or gold (and what amount). _After_ that's done, the deal value is calculated and shown in the UI, and the human can change the offered items as long as the deal value threshold is not exceeded.
> 
> So, the deal value is _not_ calculated to determine what to give away, but the other way around.

yes, i'm aware how deal AI works. so that was bad phrasing. what i meant was: AI should not offer to give up cities if they aren't under siege, no matter the war score.

**Comment by azum4roll** [comment]
> > Have you changed the item valuation so that they're valued at the winner's (perceived) value, not the loser's?
> 
> Yes

The next step then is to make the max peace deal value change more gradually based on warscore.

Regardless of warscore, absolute max peace deal value (APV) is the sum of everything that the other player is willing to get (gold, gpt, resources, cities, votes, techs (if enabled), and map that aren't valued IMPOSSIBLE).

The (current) max peace deal value (CPV) is a percentage of APV based on warscore. It doesn't have to be linear, but should be continuous (no sudden jumps from 58 to 60 warscore). `getCPV(APV, 100)` should always be equal to APV.

Capitulation is always valued at the CPV at the warscore that we're willing to capitulate. For example, if we capitulate at 85 warscore or above, `CPV = getCPV(APV, 85)`.

There should be no hidden warscore threshold to offer cities. If we don't have enough to give at the current warscore, we have to give out cities.

**Comment by ilteroi** [comment]
so i guess i'm saying APV should be high when cities are threatened and low when not.

**Comment by azum4roll** [comment]
Or warscore should increase when cities are damaged.

**Comment by ilteroi** [comment]
well warscore is very slow to change so i'd prefer the other way

**Comment by azum4roll** [comment]
APV is every city that the winner wants though. Already the max value of a possible deal.

**Comment by axatin** [comment]
discussion on how to change this should be continued on the forum
