### ISSUE TITLE
anyone know what this is?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1049]
![image](https://cloud.githubusercontent.com/assets/1358966/12102297/35293b3c-b33a-11e5-8ba2-3198b77fb808.png)

tooltip doesn't show anything special.

**Comment by LoneGazebo** [comment]
Happens sometimes on maps - it's just a random graphical glitch.

**Comment by LoneGazebo** [comment]
Also, some pathfinder woes still seem to be around: http://forums.civfanatics.com/showpost.php?p=14113620&postcount=43

**Comment by ilteroi** [comment]
i think i know whats up

**Comment by LoneGazebo** [comment]
Cool. Take your time, no rush.

**Comment by Edaka** [comment]
Don't know if you've fixed it already, Ilteroi. Take a look at these:
![passthru1](https://cloud.githubusercontent.com/assets/12978597/12133148/1ffe7b0e-b42b-11e5-9a34-00cec818af1a.jpg)
![passthru2](https://cloud.githubusercontent.com/assets/12978597/12133149/21ce733a-b42b-11e5-9cea-9d57867e0d10.jpg)
Normally my scout should be able to pass through the city tile, but he seems to avoid it, which even causes going all the way around a sea.

**Comment by ilteroi** [comment]
should it? as far as i know, only civilians can pass through enemy cities.

**Comment by ilteroi** [comment]
regarding the other issues linked above, couldn't reproduce but made some changes nevertheless. should be fixed.

**Comment by Edaka** [comment]
I'm fairly sure any unit used to be able to pass through non-enemy cities (they aren't hostile on the screenshots). As long as it didn't mean ending a turn on the city tile.

**Comment by joosegoose** [comment]
I've had the same experiences as Edaka regarding not being able to pass through cities with military. It definitely was supposed to be possible, I would do it all the time with my initial scout passing through city-states.

**Comment by ilteroi** [comment]
ok. i can probably make it so, but i really don't think that it's needed. i mean, why should i let an enemy army into my city?

if it was different initially, i'd presume that was a bug that people simply got used to. so how much do you want it?

**Comment by joosegoose** [comment]
If by initially you mean present with base BNW, then yes units initially had the ability to pass through neutral/friendly cities. It would have been bugged so far as BNW was bugged. Enemies have never been able to pass through a city, though.

It's not a huge deal the way it is now, but it's definitely a change from vanilla behavior and if I had to guess most would see it as an unnecessary change.

**Comment by Edaka** [comment]
Yeah, the deal here is that the cities weren't enemy - they were either neutral or even friendly. I visioned passing through cities the same as passing through friendly/neutral units with your military units - you could always do that as long as you didn't end your movement on top of a city/unit. 

With enemies it's different, yes, and I don't think you're supposed to pass through them.

**Comment by Iamblichos** [comment]
The observations are correct, in vanilla Civ you could pass through Minor or friendly City plots.
