### ISSUE TITLE
deal history is wrong

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10498]
v 4.2.7

(minor issue)

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/f560acb1-e60b-44aa-8d00-a55a4d2a0b37)

theodora was killed in turn 287 ... the deal end dates are in the future, should all be 287.

interestingly, in DoCancelDealsBetweenPlayers() it says

```
				it->m_iFinalTurn = GC.getGame().getGameTurn();
```

but this doesn't seem to work

**Comment by axatin** [comment]
`m_iDuration` also had to be changed
