### ISSUE TITLE
CTD CP 1-3

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1050]
Got a CTD with the CP latest version (1-3) while moving a unit from one tile to another. Late Industrial era.

https://www.dropbox.com/s/8kzwxcdisl2ji48/CvMiniDump.zip?dl=0

**Comment by LoneGazebo** [comment]
breaks to disassembly. savegame?

**Comment by LoneGazebo** [comment]
also, modlist?

**Comment by Iamblichos** [comment]
heh, too many to list....all custom. Unless you're interested in playing around with my mod package ;)

**Comment by LoneGazebo** [comment]
That usually means a LUA crash. (99.9% of the time)
G
