### ISSUE TITLE
AI refuses to make peace

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10500]
v 4.2.7

this is the situation

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/f5956553-f3b3-4eb4-8c7e-2aef927f7a29)

i've conquered the indian captital and destroyed their army. i have a warscore of 100. two of their cities are blockaded.

however, i don't actually want to capture more cities because of warmonger penalties ... but gandhi refuses to make peace. what gives?

**Comment by msw1age** [comment]
I've noticed AIs won't accept peace deals for a couple of turns after you took one of their cities, I guess because they think there is a chance they can take it back. Doesn't look like it from the screenshot, but could that be the issue?

**Comment by Vordikk** [comment]
I suppose this is intentional masochism. Sometimes civs doesn wants them to be destroyed but not make peace or become vassals. Probably if relations were too bad. Just a guess.

**Comment by axatin** [comment]
save game needed

**Comment by axatin** [comment]
can't fix without save game
