### ISSUE TITLE
Production is lost when building units that become obsolete halfway through

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1051]
You've definitely seen this, but I'm just clarifying: is this a bug or something intentional?

OP by kaspergm: "I was producing a Swordsman and then researched the technology for Longswordsman. The production was not converted into the new unit, but all hammers was lost instead, and I had to start the Longswordsman from scratch. "

**Comment by LoneGazebo** [comment]
This code hasn't been touched by me. I'll keep an eye on it, though.
G

**Comment by ProtocolHD** [comment]
Hey Gazebo,

I can confirm that this happened in a MP game just a moment ago. It happened when Physics was researched with a catapult currently being built.

**Comment by LoneGazebo** [comment]
Let me know.
G
