### ISSUE TITLE
Texture load error for Zulus' unique promotions

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1052]
This is what I get when selecting a unit that was produced in a city with ikanda:
![texture1](https://cloud.githubusercontent.com/assets/12978597/12133056/4f62f72c-b42a-11e5-8f21-5a12d740a05b.jpg)
![texture2](https://cloud.githubusercontent.com/assets/12978597/12133057/50f71190-b42a-11e5-8c41-5d83ac8b04e3.jpg)
I can't click on the red square, as everytime I hover over it the error appears. I tried disabling the FlagPromotions mod, but it was no use. I've also verified game cache - similar results.

**Comment by LoneGazebo** [comment]
Not sure, that file isn't altered by me.

**Comment by Edaka** [comment]
I'll try to reproduce it some more with/without EUI.

**Comment by GrantSP** [comment]
Just had this happen to me also. It only applies to melee units and is in line with the Zulu UB's description of adding unique promotions to to them. All the previous units produced in this city were archers and no error is produced, as soon I switch to melee it happens.

To clarify I have also added in the FlagPromotions mod so I'll check with that mod also to see if it is missing this texture.

**Comment by GrantSP** [comment]
Yeah it looks like an error in the FlagPromotions mod. The error lists an IcanAtlas that matches the naming schema of that mod, and is not included in it. I'll try and track it down but I can safely say it is not an error with CBP.

**Comment by Edaka** [comment]
Eh, I must've done a terrible job at disabling FlagPromotions when, then. Silly me.

**Comment by LoneGazebo** [comment]
If it stays in your mods folder some lua will load whether or not it is enabled, just FYI.
