### ISSUE TITLE
Civil Society (freedom) conflicting with Majesty (Tradition) policy

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1053]
Dunno if it's intended, but if one already took the Majesty policy from Tradition then Civil Society does absolutely nothing for specialist food consumption in the capital. [Screens are from before and after taking Civil Society, in capital and in other city]

![2016-01-06_00001](https://cloud.githubusercontent.com/assets/11132095/12138076/97903186-b41b-11e5-9fb9-13ead5c9391d.jpg)
![2016-01-06_00004](https://cloud.githubusercontent.com/assets/11132095/12138075/97817ac4-b41b-11e5-8106-d04e2bca32c8.jpg)
![2016-01-06_00002](https://cloud.githubusercontent.com/assets/11132095/12138077/97923364-b41b-11e5-887e-1ffa4c604584.jpg)
![2016-01-06_00003](https://cloud.githubusercontent.com/assets/11132095/12138078/9794b15c-b41b-11e5-8cec-f4f84cfb4243.jpg)

**Comment by Kolaris8472** [comment]
Wait, fixed? I assumed this was intentional. Will they consume 25% Food now?

**Comment by LoneGazebo** [comment]
If you get both, yes.
