### ISSUE TITLE
Can't open city state screen

### ISSUE THREAD

**Issue by TitaniumSteel** [LoneGazebo/Community-Patch-DLL#10531]
When I click the names of city states, the city state screen doesn't show up. It does show up when I first meet them, but I can not get it to open again, even through the diplomacy screen.

**Things I tried:**
1. Reinstalling Vox Populi without EUI
2. Trying both DirectX versions
3. Reloading save
4. Trying with just Vox Populi enabled
5. Reinstalling the game
6. Clearing cache and databases
7. Fully deleting the Sid Meier's Civilization V folder in Documents/My Games and reinstalling Vox Populi
All of the solutions above did not work.

When I start a new vanilla game, the city state screen works perfectly.

**Playing with:**
1. Vox Populi without EUI version 4.4,
2. Ingame Editor+ (already tried without)

**Reproducing steps:**
1. Start a game with just Vox Populi without EUI
2. Find a city state
3. Try to open their diplomacy screen after the first time

Here are the logs and the zip:
[Logs+save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13779760/Logs%2Bsave.zip)

**Comment by axatin** [comment]
logs are no longer needed, the bug is fixed for the next version
