### ISSUE TITLE
City states don't spawn correctly

### ISSUE THREAD

**Issue by gamezoid123** [LoneGazebo/Community-Patch-DLL#10538]
_1. Mod Version:_ Current Version: 4.4.1 (With or without EUI)

_2. DirectX Version_ DX 10 & 11

_3. List of Other Mods_

(1) Community Patch (v.126) 
(2) Vox Populi (v. 17) (Issue does not occur when this is disabled)
InGame Editor+ (v. 46) (Only used this to glance at map. Issue occurs without this mod)

_4. Describe the Issue_

Game does not create City states when set to any less than 22

Note: This is running the game in Linux through Proton, However, this issue didn't come up prior to updating to new version.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before_

[Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13790507/Saves.zip)

_6. Logs_ 

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13790501/Logs.zip)

_8. Steps to reproduce the Issue_

Start game with the above mods.

_9. Screenshots of the Issue (Optional)_

![Dec-28-23-19:08](https://github.com/LoneGazebo/Community-Patch-DLL/assets/66498171/174edbb8-bb4f-4ecc-8ad8-fcb77d58d26f)
![Dec-28-23-19:14](https://github.com/LoneGazebo/Community-Patch-DLL/assets/66498171/9a21f30d-0515-4bad-bd91-e6f32375d574)

**Comment by azum4roll** [comment]
Need Lua.log and mapscript used

**Comment by gamezoid123** [comment]
Map script is communita_79a v2.7.0, though this occured with the vanilla continents script as well.

[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/13795758/Lua.log)

**Comment by azum4roll** [comment]
You can't use the old version of the map if you're on 4.3+.

Also, the log is useless since you started the game again afterwards.

**Comment by gamezoid123** [comment]
Tried it again with a new game, clean logs, and the newest version of the script.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13797287/Logs.zip)

[Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13797291/Saves.zip)

**Comment by azum4roll** [comment]
Still nothing? There's no log about generating a new map.

**Comment by gamezoid123** [comment]
Okay, double checked the lua logs, the mapscript info is in there.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13799317/Logs.zip)

[Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13799319/Saves.zip)

**Comment by azum4roll** [comment]
Did you install the 43-civ version?

**Comment by gamezoid123** [comment]
The above mods are all I had running for these logs and saves. No EUI, no 43 civs, though, if it's worth anything, I experienced this issue with both.

**Comment by Hugo-Pratas** [comment]
got the same issue here:
![imagem](https://github.com/LoneGazebo/Community-Patch-DLL/assets/90699949/c169ede5-b570-4865-ac74-cba35bcb9805)

ring for vp, version 4.2

**Comment by azum4roll** [comment]
> got the same issue here: ![imagem](https://private-user-images.githubusercontent.com/90699949/293584294-c169ede5-b570-4865-ac74-cba35bcb9805.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNTgzMjksIm5iZiI6MTcwNDE1ODAyOSwicGF0aCI6Ii85MDY5OTk0OS8yOTM1ODQyOTQtYzE2OWVkZTUtYjU3MC00ODY1LWFjNzQtY2JhMzViY2I5ODA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDAxMTM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0N2E1NjIwNGFjODc3NTYyNjU4ZmY0ZGM5MzY0NDIzZjI4YWVkMjgzNWNmYTRkYmQzZjE0MzlkMzk2N2E2ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BSvYtoIJ8K6MT0TC3N0A3V4TagLgkJgJG6bsOR_FGn4)
> 
> ring for vp, version 4.4.2

Looks normal for this map.

**Comment by azum4roll** [comment]
> The above mods are all I had running for these logs and saves. No EUI, no 43 civs, though, if it's worth anything, I experienced this issue with both.

How many players and CS? From the logs it looks like the number of CS is 0.

**Comment by azum4roll** [comment]
Can you uncomment all "print" lines in AssignStartingPlots:AssignCityStatesToRegionsOrToUninhabited(), start a new game and upload the logs?

**Comment by gamezoid123** [comment]
> > The above mods are all I had running for these logs and saves. No EUI, no 43 civs, though, if it's worth anything, I experienced this issue with both.
> 
> How many players and CS? From the logs it looks like the number of CS is 0.

It should have been assigned to 8 and and 16.



> Can you uncomment all `print` lines in `AssignStartingPlots:AssignCityStatesToRegionsOrToUninhabited()` in `(2) Vox Populi\Core Files\Overrides\AssignStartingPlots.lua`, start a new game and upload the logs?
> 
> Edit: Also line 1618.

done, 

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13806960/Logs.zip)

![Jan-01-24-20:25](https://github.com/LoneGazebo/Community-Patch-DLL/assets/66498171/9b626eaa-bc19-4f7b-93d0-3e46468a0fa2)

**Comment by azum4roll** [comment]
I can confirm the number of CS set by game options is indeed 0.

Maybe it's some lingering options from RAS? Can you clear both cache and ModUserInfo (or whatever it's named) and try again?

If it still persists, maybe try unsubscribing to RAS.

**Comment by gamezoid123** [comment]
Yeah, it still seems to be persisting, even after unsubscribing. I'll try a reinstall and get back to you.

**Comment by gamezoid123** [comment]
Yep, reinstall fixed it. Is it safe to assume the issue was RAS?

**Comment by azum4roll** [comment]
Steam mod subscription is jank in civ5. Things in subscribed mods sometimes load without you activating them.
