### ISSUE TITLE
No resources on start

### ISSUE THREAD

**Issue by tolonaro** [LoneGazebo/Community-Patch-DLL#10546]
4.4.1  no additional mods.  chieftain,  community map,, no resources.  check the settings.  wonder about "starting resources both"

CTD on first while retarting, but no every time. Rather obviously unplayable.

_1. Mod Version (X.Y.Z). Current Version: 4.4.1_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

[CvMiniDump.dmp](https://github.com/LoneGazebo/Community-Patch-DLL/files/13798446/CvMiniDump.dmp)

_9. Screenshots of the Issue (Optional)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13798429/Logs.zip)

[Poland Art.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13798422/Poland.Art.zip)

**Comment by Azhral** [comment]
Can confirm same problem. Issue appears to be on Natural Wonder placement.

`[1809702.656] no such column: Type
[1809702.656] In Query - select * from Natural_Wonder_Placement where Type = ? LIMIT 1`

I can't find that select query anyplace either.

**Comment by azum4roll** [comment]
> [1809702.656] no such column: Type
[1809702.656] In Query - select * from Natural_Wonder_Placement where Type = ? LIMIT 1

Not a problem. That's been there for ages.

Logs are useless since you've started the game again before zipping.

**Comment by tolonaro** [comment]
Ok, understand.  Do over?
