### ISSUE TITLE
AI still building pointless navies

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1055]
![image](https://cloud.githubusercontent.com/assets/1358966/12140011/bed5e1c0-b464-11e5-9dff-276e3ebd0241.png)

this is on the great plains map. no enemies around for the venetian ships.

**Comment by LoneGazebo** [comment]
It'll  build up to around that amount in terms of 'x ships per water plot.' One advantage of that, though, is that a land conqueror will have to deal with a navy retaking coastal cities.

G

**Comment by ilteroi** [comment]
yeah. but if the resources were invested in land units, they wouldn't lose the city in the first place :)

there's supposed to be a check where i looks whether there are enemy units or cities on a body of water. if there are none, it shouldn't bother building ships.

**Comment by LoneGazebo** [comment]
Makes sense to me.

**Comment by LoneGazebo** [comment]
![2016-01-06_00001](https://cloud.githubusercontent.com/assets/7849458/12156815/367595b4-b49b-11e5-839f-a1b3e0e147c2.jpg)

Boat parties around barbarian camps still happening from time to time. I like them, but they may not be effective.

**Comment by GrantSP** [comment]
Isn't this something more to do with the poor AI choices make in general, not just navies?
I'm starting to see a few CSs with Explorers as their garrisoned units. Not exactly sure of the process the AI goes through based on the era and the levels of tech of the civs around them but is it possible that on a purely figures based equation those units have the greatest "bang for buck"?

**Comment by Iamblichos** [comment]
In my opinion they should still build a few ships in this coastal cities, otherwise they'll be liable to a naval sneak attack and building ships will be too late.

**Comment by LoneGazebo** [comment]
Working on this in the unitsanity function, should be better now.
