### ISSUE TITLE
morrocco building a kasbah next to MY city

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10556]
v 4.4.1

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/7b18e4fc-e48b-4eb1-9f42-43f9d51524bc)

they stole the plot but it's outside of their cities' working range

**Comment by azum4roll** [comment]
Intentional. It doesn't specify whose city it must be adjacent to.

**Comment by bsesar** [comment]
The description of Moroccan UI could also be incomplete/imprecise.

Can the Chinese UI (forgot the name) also be built next to a non-Chinese city or is the Kasbah the only UI that can be built next to a city owned by someone else?

**Comment by ilteroi** [comment]
well that is one aspect but the other is, why build an improvement outside of working range

**Comment by azum4roll** [comment]
> The description of Moroccan UI could also be incomplete/imprecise.
> 
> Can the Chinese UI (forgot the name) also be built next to a non-Chinese city or is the Kasbah the only UI that can be built next to a city owned by someone else?

They share the same code.
