### ISSUE TITLE
3.10.14 CTD on player leave/rejoin

### ISSUE THREAD

**Issue by nsporillo** [LoneGazebo/Community-Patch-DLL#10559]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

[3.10.14_VP-SSEM_EUI](https://drive.google.com/file/d/1BQ_B5x-fDyvmGvdfLHRKp_4MX-YW_eA7/view?usp=drive_link)

_2. DirectX Version_

DX 11

_3. List of Other Mods_

- More unique components
- Supersettler
- Even More resources

_4. Describe the Issue_

Anytime anyone disconnects the multiplayer lobby for any reason, we must all exit and re-host for the game to be playable.

The attached save below works fine if we all go back to desktop, boot back up, and load that save. 
The attached save is unfortunately not the 1 turn before but rather the turn we crashed on.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0039 BC-2440.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13815239/AutoSave_0039.BC-2440.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13815230/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.dmp](https://github.com/LoneGazebo/Community-Patch-DLL/files/13815217/CvMiniDump.dmp)

_8. Steps to reproduce the Issue (Optional)_

Multiplayer game consisting of 8 players total, 3 humans.
1 Player disconnects **either by choice or by crashing to desktop**.
That player rejoins the lobby, and upon Next Turn - the other two humans crash to desktop. 

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
This seems to be the same issue as the one that makes it necessary that all players clear their cache before loading a MP game. It seems to have something to do with modpacks, but the error happens in a part of the code we don't have access to. I don't see a way how we could fix this, so unfortunately all players exiting and re-joining seems to be the only option.
