### ISSUE TITLE
Game Crash 

### ISSUE THREAD

**Issue by zautos** [LoneGazebo/Community-Patch-DLL#10553]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_
3.10.14_VP-SSEM_EUI

_2. DirectX Version_
 DX 10 & 11. 

_3. List of Other Mods_
No other mods

_4. Describe the Issue_
The none host player game craches. 

[Uploading Desktop.zip…]()

**Comment by bsesar** [comment]
@zautos, your upload of Desktop.zip failed. Would you please upload the zipfile again?

**Comment by zautos** [comment]
[Uploading Desktop.zip…]()

**Comment by axatin** [comment]
Cannot reproduce this, I could continue to the next turn and also a few turns beyond when I loaded the game.
