### ISSUE TITLE
Game crash on player turn

### ISSUE THREAD

**Issue by Vordikk** [LoneGazebo/Community-Patch-DLL#10569]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_
4.4.2. with EUI from installer, no 43 civs

_3. List of Other Mods_

No other mods

_4. Describe the Issue_

At first game has crashed right after making an autosave when my turn has come. Attached savegame is this one. After that i have reloaded, ordered a couple of construction projects, and it has crashed again. Attached logs are from this point.
[Save, logs, dump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13850203/Save.logs.dump.zip)

_8. Steps to reproduce the Issue (Optional)_
I don't know exactly, i've been toggling between cities and ordering buildings, and game at first begin not changing info when getting into next city and crashes 2-3 seconds afterwards

_9. Screenshots of the Issue (Optional)_

**Comment by Vordikk** [comment]
What do you mean by Memory Issue? Something like unlimited loops, plenty of excessive or uncleaned variables, etc or local hardware problem?

**Comment by azum4roll** [comment]
Turn 396 is really late game. A 32-bit game like civ5 can only handle having a limited amount of stuff showing up on screen at the same time.

Zooming in or switching to strategic view may solve this problem for a while.

**Comment by Vordikk** [comment]
Uhum
I have turned off most of info (tile production, tile edges, trade routes, everything aside of specific resourses)
Zooming doesnt change anything
But for me it seems that certain info is not getting cleaned from being displayed even when not needed anymore, which is prolly original game bug, and so mod has nothing to do about it. Im thinking about this because sometimes when you toggling somewhere in other view, game may show previous info and then renew it.

Generally ok, i understood, game "optimization" is awful :) Reminds me Civilization 3, which was "flying" even on old PC. but in 5 they did something extremely wrong...

I will try strategic view and logging, thanks.

**Comment by Vordikk** [comment]
It makes no sence at all. I have continued that game, and it did not lag or crash anymore.
