### ISSUE TITLE
War Weariness

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#10568]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

_3. List of Other Mods_ [https://files.fm/u/ux6f88quyh](url)

_4. Describe the Issue_
war weariness not seem to work. Still 0 after many war turns

______________________________________________________________________________________
_5. Save Game 
[PADREXIX.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13850031/PADREXIX.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13850034/Logs.zip)

**Comment by Hokath** [comment]
Could someone in the know clarify how this is meant to work?
The notes sort of implied that you would only see weariness if you had negative war score? Did I read that right?

**Comment by Amecareth002** [comment]
Yeah, that new war weariness system certainly needs some tuning/fixes. I've been at many wars for I don't know how many in-game years with my war weariness being still at zero as well

**Comment by ilteroi** [comment]
i don't really understand how this new war weariness is supposed to work but i think i fixed it
