### ISSUE TITLE
Ancient Ruins not picked up

### ISSUE THREAD

**Issue by Mandritti** [LoneGazebo/Community-Patch-DLL#10573]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

version 4.4.2, full mod no eui

_2. DirectX Version_

-

_3. List of Other Mods_

-

_4. Describe the Issue_

The unit moved onto an Ancient Ruins tile ignores the ruin.  As in the screenshot, the ruin exists underneath my unit.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[before_bug_Maria I_0001 BC-3960.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13851408/before_bug_Maria.I_0001.BC-3960.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13851407/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

-

_8. Steps to reproduce the Issue (Optional)_

End the turn in the save.  Then, move the Warrior 1NE to the forest ancient ruins tile.

_9. Screenshots of the Issue (Optional)_
![20240104135356_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/11051545/e3b1119e-af67-424c-acbb-a7a35b420303)

**Comment by Cyclopia31** [comment]
Only recon units and cities border can take antic ruins ;)

**Comment by Vordikk** [comment]
Feature.
