### ISSUE TITLE
more weird roadbuilding

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10572]
v 4.4.2 + visibility fix (3ba6fb915ac4cbb5676938aeba7c3c7cbfe8838f)

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/8579c8c9-d128-4836-83e3-0aa7613e29d3)

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/a0fdf0f3-7369-4df7-b6f0-773f6ec81c98)

seems quite chaotic, is there a method to the madness? also note the weird mix of road and rail ...

@KungCheops

**Comment by KungCheops** [comment]
I think it's mostly because the workers are not removing obsolete roads. Fix for that is included in #10567.

**Comment by ilteroi** [comment]
more road madness. the coastal road i built manually. then i automated a worker and first thing it does is to build a parallel road. 

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/54428cdf-af2d-4f1f-95e2-e7f28456cc2e)

**Comment by KungCheops** [comment]
> more road madness. the coastal road i built manually. then i automated a worker and first thing it does is to build a parallel road. 
> 
> ![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/54428cdf-af2d-4f1f-95e2-e7f28456cc2e)
> 

It doesn't take existing roads into account when planning the road network (well, not very much at least). So it seems that the AI has a different idea for how the road network should be laid out.

**Comment by KungCheops** [comment]
In this case though I'm not sure why it did it like this, don't see a reason for why it would reroute that (unless maybe there's a hidden resource in one of the tiles, I think there was a bug with that, will be fixed with next PR).

**Comment by rambo919** [comment]
Possibly related, I noticed that the game treats worker built roads differently to legionary built roads.... the one replaces the other.

**Comment by rambo919** [comment]
> > more road madness. the coastal road i built manually. then i automated a worker and first thing it does is to build a parallel road.
> > ![image](https://private-user-images.githubusercontent.com/1358966/300172991-54428cdf-af2d-4f1f-95e2-e7f28456cc2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MzM4ODQsIm5iZiI6MTcwNjQzMzU4NCwicGF0aCI6Ii8xMzU4OTY2LzMwMDE3Mjk5MS01NDQyOGNkZi1hZjJkLTRmMWYtOTVlMi1lN2YyODQ1NmNjMmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjhUMDkxOTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDgwYTVlNjdjYWFmYjhhMTU1ZTMyN2UzNGQ0ZmVkZTg1ZDcxZDU3YjA2MTA3Y2I1NTNjNDY5MzFmNzhkNDdhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pM5PIaswu3MeImI9IXHDVoFNSlls6PkTv5UX16WsnLo)
> 
> It doesn't take existing roads into account when planning the road network (well, not very much at least). So it seems that the AI has a different idea for how the road network should be laid out.

Odd difference, the one road is paved and the other is dirt.

**Comment by axatin** [comment]
road building has been reworked in 4.5
