### ISSUE TITLE
Early CTD after settling with Spain

### ISSUE THREAD

**Issue by subversiveasset** [LoneGazebo/Community-Patch-DLL#10574]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

Current Version: 4.4.2_

_2. DirectX Version_

DX 11

_3. List of Other Mods_

(1) Community Patch
(2) Vox Populi
(3a) VP - EUI Compatibility Files
(4a) UI - Promotion Tree for VP
(over) More Unique Components for VP (v 87)
JFD's Cultural Diversity - (1) (Core) Utilities (v 21)
JFD's Cultural Diversity - (2) (Sound) Unit Dialogue (v 1)
JFD's Cultural Diversity - (2) (Art) Splash Screens (v 1)
JFD's Cultural Diversity - (2) (Core) Mod Support (v 1)
JFD's Cultural Diversity - (2) (Gameplay) Starting Bonuses (v 1)
JFD's Cultural Diversity - (2) (Art) Art Styles (v 1)
JFD's Cultural Diversity (Soundtrack)

_4. Describe the Issue_

Sometime after settling the second city as Spain and going into the city screen, the game crashes to desktop. It might be from selecting something to build. but I'm not sure.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[IsabellaSETTLE_CTD_0034 BC-2640.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13852299/IsabellaSETTLE_CTD_0034.BC-2640.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13852310/logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13852313/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

Settle at the place located, browse over build screen options

_9. Screenshots of the Issue (Optional)_

**Comment by ryanmusante** [comment]
Are those JFD mods compatible with VP?

**Comment by subversiveasset** [comment]
They haven't had any problems in the past. I know that's probably not a super rigorous answer.

As an update, I tried a new game keeping the JFD mods but *not* using "(over) More Unique Components for VP (v 87)", and I have not experienced any CTDs with the revised setup. So my revised thought is that this bug is probably an incompatibility with the latest version of (over) More Unique Components for VP (v 87)

**Comment by axatin** [comment]
the same memory issue as reported in #10848 and #10534
