### ISSUE TITLE
MultiplayerTest_VP4.4.2 + Turn 0 players location issue (everyone spawn on the same side of the map)

### ISSUE THREAD

**Issue by Cyclopia31** [LoneGazebo/Community-Patch-DLL#10571]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_
VP 4.4.2
Modpack: https://drive.google.com/file/d/1hNbNQZCcZdaPzXRi0E-4kg9-Npl9xTB_/view?usp=drive_link

_2. DirectX Version_
DirectX11

_3. List of Other Mods_
.(over) More Unique Components for VP (v 87)
.(qua) Supersettler (v 2)

_4. Describe the Issue_
Hello, I played a game using the patch 4.4.2 with a friend and we faced desyncs, especially the non-host player had a lot of them. The game ended with a CTD for the non-host player.
I hope this report can help the multiplayer stability !

Bonus: In this game we can see the problem with every players (AI and humans here) start really close to each other. (Was this map: https://forums.civfanatics.com/attachments/terraoval_13a-zip.624366/)
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/80354202/61f5d9b6-93e8-4ad4-9cab-737b3ed15eae)

______________________________________________________________________________________
_5. Data
Here a link with the data: https://drive.google.com/file/d/1BS71vqDvdas4LWVCtssjMRq5gm66QeZl/view?usp=sharing

**Comment by azum4roll** [comment]
I think the map issue is due to the stupid Area != Landmass thing. Terra uses GetBiggestArea to determine the biggest landmass since there isn't a GetBiggestLandmass function. And in this case, the biggest area is the right side of the landmass.

What even is area used for when it's so arbitrary?

**Comment by Cyclopia31** [comment]
@azum4roll Do you know if anything has changed since the last patches on this point? I'm pretty sure I never saw this problem in 3.x.x. while I got it 3 times in a row on the most recent patch.

**Comment by azum4roll** [comment]
I cleaned up the AssignStartingPlots.lua file, but no logic was changed regarding region division (checked again).

On the DLL side, CvMap and CvArea are also not changed, so I'm not sure what's going on here.

Ideally we get a new lua function to identify the biggest landmass.

**Comment by azum4roll** [comment]
> Same issue appeared in our game, distance between civs is very short on continents type of map

Not strictly an issue unless there's also a lot of empty space on the same continent.

**Comment by azum4roll** [comment]
Cause is known, so I'm closing duplicates.
