### ISSUE TITLE
Replayable CTD with no foreseeable in game fix.

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#1057]
In my current game I've come across a save game that just will not progress.
I've been resorting to saving before each "End turn" to combat late game CTDs and usually when it happens I can progress further but this time it just refuses to do so.

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/80656/CvMiniDump.zip)

I unfortunately haven't yet setup my system with the SDK or ModBuddy so I can't examine it myself yet.

Only CBP+EUI, with all parts active and only InfoAddict as the other mod.

**Comment by LoneGazebo** [comment]
infoaddict is known to cause CTDs for a lot of users. This dump breaks to disassembly, meaning the crash is not in the dll.
G

**Comment by GrantSP** [comment]
"Breaks to disassembly", never heard that term before, I'll need to read up on that.
So can mods be safely removed midgame or are they "baked into" the save? It's been so long since I played.
