### ISSUE TITLE
VP 4.4.2. No ancient ruins spawn (Single and Multiplayer)

### ISSUE THREAD

**Issue by vaderkos** [LoneGazebo/Community-Patch-DLL#10583]
_1. Mod Version (4.4.2). Current Version: 4.4.2_
https://drive.google.com/drive/folders/1Qq5mWnGGv2uuEPA62azseUhw-pE4--3O

Using modpack version 4.4.2_VP-SSEM_EUI

_2. DirectX Version_
11

_3. List of Other Mods_
Ingame editor to check map (same result without ingame editor)

_4. Describe the Issue_
No ancient ruins spawn regardless _no ancient ruins option_ or game type (single/multi)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13885727/save.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13885744/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
No CTD

_8. Steps to reproduce the Issue (Optional)_
Create game on continent regardless multiplayer or single player. Look for runes. No runes generated.

_9. Screenshots of the Issue (Optional)_

**Comment by azum4roll** [comment]
[AssignStartingPlots.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13896214/AssignStartingPlots.zip)
Try replacing AssignStartingPlots.lua with this.
