### ISSUE TITLE
Income shift per turn displayed wildly incorrectly

### ISSUE THREAD

**Issue by rambo919** [LoneGazebo/Community-Patch-DLL#10580]
Mod Version 
 4.4.1

DirectX Version
wine / DX11

List of Other Mods
none

Describe the Issue
This has been an issue in past years and I thought it would have been fixed by now. Income change shows negative 100+ but gives positive 1000+ per turn.

[saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13871116/saves.zip)

**Comment by azum4roll** [comment]
No idea what that means

**Comment by rambo919** [comment]
I see.... did not know about this. Can the display not be updated then?

**Comment by azum4roll** [comment]
How would the game even know how much instant yields you will get this turn? Plus it'll become meaningless when it fluctuates every turn.

**Comment by rambo919** [comment]
But it fluctuates every turn anyway?

**Comment by azum4roll** [comment]
Hover over the star to see your total instant yields last turn and past 10 (IIRC) turns.

**Comment by rambo919** [comment]
Yes I know that, both that and regular income fluctuates every turn.... sometimes wildly. I don't see how the game cannot make at least an estimation of the coming instant yields but maybe that's just my ignorance. Late game due to spiraling expenses it always becomes a gamble because you have no idea whether or not your money is going to run out or not forcing you to keep a large reserve just in case.
