### ISSUE TITLE
Inspired Works Reformation not granting +2 Science and Faith to Landmarks

### ISSUE THREAD

**Issue by bryan317** [LoneGazebo/Community-Patch-DLL#10588]
1. 4.4.2

4. Inspired Works Reformation not granting +2 Science and Faith to Landmarks.  Other Great Person Improvements work as intended.

______________________
![Screenshot 2024-01-10 224435](https://github.com/LoneGazebo/Community-Patch-DLL/assets/25620720/bb8f0370-0293-4d92-9a04-0820f54b3bf2)
________________________________________________________________

[Harun al-Rashid_0753 AD-1716.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13909458/Harun.al-Rashid_0753.AD-1716.zip)

To recreate: Either end the turn or select an Archaeologist near Mecca or Kufah and complete their dig.  Choose a Landmark.

Forgive me if i didnt do this correctly.  If i can do anything else please let me know.

**Comment by azum4roll** [comment]
You claimed to be playing in the "latest stable" which isn't 4.4.2 on the forums. It's already fixed.

**Comment by bryan317** [comment]
So sorry.  I won't make that mistake again.  The BETA thread was throwing me off.
