### ISSUE TITLE
Cotton Monopoly

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1058]
(this is with the 1/3 still)

The notification popup thing, civilopedia, and monopoly screen all list Cotton's monopoly at still only +3 happiness. Its not my monopoly, so I'm not sure if it actually provides the +5 the others do now.

**Comment by LoneGazebo** [comment]
should be 5. i'll check

**Comment by pandasnail** [comment]
Sorry sorry! Misread it somehow...

**Comment by LoneGazebo** [comment]
No worries.
