### ISSUE TITLE
CTD When Hovering Over Granary in Build Queue While Playing India using Commuitu_79a v3.0.1 Map Script

### ISSUE THREAD

**Issue by NavidC** [LoneGazebo/Community-Patch-DLL#10597]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

- (1) Community Patch (v. 126)
- (2) Vox Populi (v. 17)
- (3a) VP - EUI Compatibility Files (v.1)
- (4a) UI - Promotion Tree for VP (v.23)

_2. DirectX Version_

DX 10 & 11

_3. List of Other Mods_

No other MODs enabled

_4. Describe the Issue_

Whenever you play as India using a map created by Commuitu_79a v3.0.1 Map Script, it will crash once you hover over Granary in the building queue.  Hovering over Granary does in the Tech Tree does not cause a crash - only when you've finished researching it and it becomes an available building for your city to create.  

This is re-producible with a 100% crash rate.   Playing Greece or Poland while using the Commuitu_79a v3.0.1 Map Script does NOT cause a crash.  Playing India on Pangea does NOT cause a crash.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[autosaves-granary_india_commuitu_79a_bug_report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13926175/autosaves-granary_india_commuitu_79a_bug_report.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[logs-granary_india_commuitu_79a_bug_report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13926179/logs-granary_india_commuitu_79a_bug_report.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.dmp](https://github.com/LoneGazebo/Community-Patch-DLL/files/13926193/CvMiniDump.dmp)

_8. Steps to reproduce the Issue (Optional)_

- Start a game as India using the Commuitu_79a v3.0.1 Map Script
- Research the tech to unlock Granary
- Once Granary is complete, hover over it and the game will crash

_9. Screenshots of the Issue (Optional)_

**Comment by azum4roll** [comment]
Which farm resources did you have in each of the scenarios you mentioned?

**Comment by NavidC** [comment]
@azum4roll I don't have the old save files for most of the scenarios mentioned, but after some further experimentation, I think you are on to something; it appears its the presence of farm resources within city borders that causes the crash, not the specific combination of my original title.  Below are the save files for 3 scenarios:

- American on Pangea with Wheat within City Borders - CTD [granary_america_pangea_crash-wheat.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13928073/granary_america_pangea_crash-wheat.zip)

- India on Pangea with Maize within City Borders - CTD [granary_india_pangea_crash-maize.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13928074/granary_india_pangea_crash-maize.zip)

- Poland on Pangea with no farmable resources within City Borders - NO CRASH [granary_poland_pangea_nocrash-no_farm_res.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/13928075/granary_poland_pangea_nocrash-no_farm_res.zip)

**Comment by azum4roll** [comment]
Can't replicate with the save provided even if it's loaded in a new game session.

**Comment by NavidC** [comment]
After hearing that you were not able to replicate, I did a fresh re-install of Civ 5 & Vox Populi - the save files I uploaded no longer crash the game, so I believe the issue is resolved.  Thanks for looking into it.
