### ISSUE TITLE
CP-ONLY Friends give gifts now

### ISSUE THREAD

**Issue by Tesla101a** [LoneGazebo/Community-Patch-DLL#10591]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

4.4.2 COMMUNITY PATCH ONLY

_2. DirectX Version_

DX11

_3. List of Other Mods_

In Game Editor

_4. Describe the Issue_

I think some part of the Full Vox Populi is leaking into the Community Patch, as now in 4.4.2 when you declare a friendship the AI will randomly gift you stuff, like a lux you didn't have, or gold, out of the blue.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

Let me know if I need this and I can provide it.

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

Let me know if I need this and I can provide it.

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Just declare a friendship in a game, it happens all the time.

_9. Screenshots of the Issue (Optional)_

**Comment by Tesla101a** [comment]
Thank you!  I've never seen it occur before, sounds like it not happening before was the bug and now it's behaving correctly.  AI feels less selfish now!

**Comment by axatin** [comment]
Yes, that's intentional, part of additional diplomacy features. It was bugged all the time and only an empty leader screen appeared instead of the offer: https://github.com/LoneGazebo/Community-Patch-DLL/issues/10069

**Comment by Nu-Illasera** [comment]
> Yes, that's intentional, part of additional diplomacy features. It was bugged all the time and only an empty leader screen appeared instead of the offer: #10069

AHHHHHHH! so that's why i would sometimes have an empty leader screen, i was gonna report it as a bug for 3 months now but i guess i always got too caught up in the game to do it, i would press "Escape" as in "Cancel trade" as i didn't know what it was, THANK YOU!

**Comment by axatin** [comment]
> Quick question : Does it have any implications for diplomacy modifiers? does it give you a positive "Trade partner" value to your modifier like when you give gifts to your allies?

Afaik you get a positive modifier for active trade deals, but not specifically for gifts, so it's better to just trade normally and send gifts only if they ask.

**Comment by Nu-Illasera** [comment]
> > Quick question : Does it have any implications for diplomacy modifiers? does it give you a positive "Trade partner" value to your modifier like when you give gifts to your allies?
> 
> Afaik you get a positive modifier for active trade deals, but not specifically for gifts, so it's better to just trade normally and send gifts only if they ask.

Noted, Thank you.
