### ISSUE TITLE
Cannot work tile despite no enemy present

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1059]
This might have been a change made by CPP, and apologies if so.

![2016-01-07_00001](https://cloud.githubusercontent.com/assets/11132095/12169890/d64b9f1e-b501-11e5-9d59-0a7e902c0b54.jpg)
![2016-01-07_00002](https://cloud.githubusercontent.com/assets/11132095/12169891/d7db1b52-b501-11e5-9b59-09db5835e656.jpg)

There were enemies on my tiles, and I was correctly unable to work them. There's another tile with no enemy though, and I don't even have an icon allowing me to work it or telling me that it's occupied by an enemy. This is with today's beta, first time I've noticed this behavior.

**Comment by ilteroi** [comment]
can't reproduce ...

**Comment by joosegoose** [comment]
[AutoSave_0130 AD-0375.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/81890/AutoSave_0130.AD-0375.zip)

Here's my save. I'm running the 1/6 beta, full CPP w/ EUI

**Comment by joosegoose** [comment]
A slightly different example...


[AutoSave_0135 AD-0500.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/81906/AutoSave_0135.AD-0500.zip)

I know it's the same turn, I went back and replayed the previous 5 turns slightly differently. Of note: if you move my spearman on top of one of the workable tiles, it becomes workable.

**Comment by joosegoose** [comment]
I don't mean to be needy, but if this is fixed any chance I could get the appropriate file (updated .dll I'm assuming)? I don't finish enough CBP games as is and I was hoping to play this one out without the bug. Ignore if a hotfix is incoming :)

**Comment by LoneGazebo** [comment]
Good news is that the change is reverted (technically it wasn't a bug so much as it was a design decision that we're reversing). Bad news is that it won't be savegame compatible. :(

**Comment by joosegoose** [comment]
:( I'll probably just wait for the next release then.

Glad to hear it's been reverted though!
