### ISSUE TITLE
[Bug] Satrap-court yields are wrong

### ISSUE THREAD

**Issue by wileyhk2001** [LoneGazebo/Community-Patch-DLL#106]
Problem: 
The Satrap-court currently only provides 1 happiness, 1 merchant and 3 gold. No gold/pop or bonus to traderoutes that are on the Bank.

Possible Cause:
TBD

http://forums.civfanatics.com/showthread.php?t=528142&page=59 - Funak

**Comment by LoneGazebo** [comment]
I'll look, but it sounds more like a tooltip error than a SQL error, as the SQL shows it having these things.
