### ISSUE TITLE
MoreLuxuries.sql in the Compatibility Files (v1/6 beta) 

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#1060]
1.
MoreLuxuries.sql in the **EUI** Compatibility Files lacks three values, compared with **No-EUI** Compatibility Files.

e.g.
WHERE ResourceType = 'RESOURCE_COFFEE';
WHERE ResourceType = 'RESOURCE_TOBACCO';
WHERE ResourceType = 'RESOURCE_PERFUME';

Please check EUI and No-EUI Compatibility Files.

2.
This is a personal request.
Would you please use the same file names in the EUI and No-EUI Compatibility folders?
That will make it easier to use Diff tools.

cf.
Folder name
(1) More Luxuries (EUI Compatibility)
(2) MoreLuxuries (No-EUI Compatibility)

File name
(1) C4DF Compatibility.sql  (EUI Compatibility)
(2) C4DFCompatibility.sql  (No-EUI Compatibility)

There is (or not) a Spce.
Sorry for my English.

**Comment by LoneGazebo** [comment]
Not sure I understand your second request.

**Comment by 8h42** [comment]
Like this.
http://www.dropbox.com/s/wlyq3hmc1bvm7gp/%286a%29%20Community%20Balance%20Patch%20-%20Compatibility%20Files%20%28EUI%29.zip?dl=0
I deleted a space between **More** and  **Luxuries**, **C4DF** and **Compatibility.sql** in the EUI Compatibility Files.
