### ISSUE TITLE
Incorrect worker action tooltip

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#10617]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_unofficial

_4. Describe the Issue_

Tooltip for a worker constructing farm on a marsh tells that it would add 3 food which is incorrect, because removing the marsh would remove the hammers and gold from the tile as well.

![20240125020234_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/16341598/cdabb8f5-6dc4-49fe-ba0c-c55c5cd659a6)

**Comment by axatin** [comment]
Fixed by #10625
