### ISSUE TITLE
Discipline's culture for garrisons

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1061]
OP by Gokudo01: "Discipline(Authority) doesn't provide any culture yield if the city isn't the capital. Although it works with the happiness part, it doesn't provide any culture on your other cities."

Also, this: http://forums.civfanatics.com/showpost.php?p=14116284&postcount=4224

**Comment by LoneGazebo** [comment]
Ilteroi, related to your garrison changes?

**Comment by ilteroi** [comment]
hmm. shouldn't be the case. but then you never know

**Comment by ilteroi** [comment]
can not see a difference between capital and non-capital in the code. also cannot reproduce. however there's an issue with the update of the numbers in the status bar: culture updates instantly, happiness only after a mouseover.

the conquistor problem is real though, and the provided hypothesis correct. the code is a bit stupid, it doesn't check for the presence of a garrison each turn but instead does some bookkeeping every time a unit is moved ... the easiest fix would be to deny the garrison bonus to conquistadores. opinion?

**Comment by LoneGazebo** [comment]
That'd be hard to explain in-game, though. Also the AI wouldn't get it (and other mods that add expendable military units might create problems).

Seems like the city garrison value should simply be a toggle (either it has or it does not have a garrison) which provides the bonus or does not. I can't really figure out why it is subtracting the value when it is technically a boolean check.
