### ISSUE TITLE
Spanish Hacienda cannot be built on snow tiles

### ISSUE THREAD

**Issue by SuperNoobCamper** [LoneGazebo/Community-Patch-DLL#10623]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

4.4.2

_2. DirectX Version_

Dx11

_3. List of Other Mods_

Base VP with EUI
More Unique components
Squads for VP

_4. Describe the Issue_

Spanish Hacienda cannot be built on snow tiles although the it should be buildable as per line 169 of spain SQL file
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/20557080/cb3eec59-5c7a-4942-a772-214d00b553b3)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by azum4roll** [comment]
Screenshot needed with cursor hovering on the build button.

**Comment by SuperNoobCamper** [comment]
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/20557080/e69de5d3-0f54-4df5-8758-f3169511b43d)


> Screenshot needed with cursor hovering on the build button.

**Comment by bsesar** [comment]
Just out of curiosity, @SuperNoobCamper, the snow tile you want to build the Hacienda on is the one outside of your borders (between iron and stone at the bottom of the map) or...?

**Comment by SuperNoobCamper** [comment]
It is outside my territory but snow tiles inside my territory aswell does not allow building haciendas.
The tooltip shows info and expected yields of tiles even if they are outside your territory

**Comment by azum4roll** [comment]
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/14953746/94b1e186-ec1a-48a5-aa3c-5517e331b489)
Can't replicate. All 3 workers here can build Hacienda.

**Comment by SuperNoobCamper** [comment]
> ![image](https://private-user-images.githubusercontent.com/14953746/301558887-94b1e186-ec1a-48a5-aa3c-5517e331b489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MDMyMTksIm5iZiI6MTcwNjgwMjkxOSwicGF0aCI6Ii8xNDk1Mzc0Ni8zMDE1NTg4ODctOTRiMWUxODYtZWMxYS00OGE1LWFhM2MtNTUxN2UzMzFiNDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDE1NTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NGI2MDBlYjgwYzQyOGQ3MmVjMGM4M2NhNWI1MmEwMDZmM2I1OTdmN2E5OGYyZWEyYzExNWVkYWIzNzQ4MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TBWO_li2SqM0DdjAXlVx2TWK1unufsUNsxL256BotOU) Can't replicate. All 3 workers here can build Hacienda.

I shall attach a save file when i get home.

**Comment by azum4roll** [comment]
Oh it's the Inuit mod. @pineappledan made all UI except the Inuksuk unbuildable on snow.
