### ISSUE TITLE
Would like to have notification option

### ISSUE THREAD

**Issue by myclan123** [LoneGazebo/Community-Patch-DLL#10624]
Some notifications become less and less important in later era, like +5 faith for killing a unit. While combat log can be important for early war. Can VP be compatible with Notification custom mod?
Like:
https://forums.civfanatics.com/resources/custom-notifications.16671/history
&
https://www.picknmixmods.com/mods/CivV/UI/Notification%20Options.html

**Comment by axatin** [comment]
Not the same mod, but this one also allows turning off the instant yield notifications: https://forums.civfanatics.com/threads/qol-notification-settings.688500/

**Comment by axatin** [comment]
The mod in the link solves the issue for instant yields. If other notifications are also too common, it's better to remove them in base VP, you can discuss it in https://forums.civfanatics.com/threads/notifications-discussion.688671/.
