### ISSUE TITLE
4.4.2 CTD during AI turn (modern era, no other mods)

### ISSUE THREAD

**Issue by sofrondr** [LoneGazebo/Community-Patch-DLL#10626]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_
4.4.2 no-EUI, modpack for multiplayer made without any issues by me

_2. DirectX Version_
DX 10 & 11

_3. List of Other Mods_
No other mods

_4. Describe the Issue_
In this multiplayer game (I am host), clicking next turn results in a CTD for both me and the other one non-host. It happens during AI turns (Rome to Indonesia transition?)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14088174/save.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14088185/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14088202/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

For both players, F-key all units, choose any research nad production and click next turn. The CTD is guaranteed if the host is the last player to click next turn (In some cases where non-host pressed the button later than host, it resulted in CTD only for the non-host, but this was not reliable.)

**Comment by sofrondr** [comment]
Not sure this is a duplicate of the mentioned issue, @axatin has the same opinion. But what is it? Can someone look please? The same crash happened for us in another game today, around the same era. Is it some atomic era tech? Currently, we are always unable to finish games on this patch :(

**Comment by sofrondr** [comment]
Another report, probably the same issue #10644

**Comment by ilteroi** [comment]
duplicate
