### ISSUE TITLE
Cannot upgrade Janissary to Gatling Gun (Only -1 allowed per player)

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#10621]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

_4. Describe the Issue_
I am unable to upgrade a Janissary (that I just built in Athens) to a Gatling Gun even though I have enough gold to do so (the upgrade button is grayed out). Interestingly enough, the message at the bottom of the Upgrade Unit panel says "Only -1 allowed per player". In previous turns, I was able to upgrade Janissaries to Gatling Guns without any problems.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
The save is from the turn when the unit was built: [cannot_upgrade.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14074547/cannot_upgrade.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14074548/Logs.zip)

_8. Steps to reproduce the Issue (Optional)_
Load the save and try to upgrade the Janissary in Athens.

_9. Screenshots of the Issue (Optional)_
<img width="960" alt="cannot_upgrade_Janissary" src="https://github.com/LoneGazebo/Community-Patch-DLL/assets/620131/e6cb2dfb-a1a9-486f-90b0-3460757a9c17">

**Comment by bsesar** [comment]
SOLVED: I already had a unit (Commando) garrisoned in the city when the Janissary was built and there was no nearby tile available for Janissary to move to because I had units around the city. Once I moved the Commando out of the city, I was able to upgrade the Janissary.

**Comment by Nu-Illasera** [comment]
Mark this "issue" closed if that is the way its suppose to work, please and thank you.

**Comment by bsesar** [comment]
@Nu-Illasera, it's not a showstopper, but the error message is misleading and that may be a bug. I'll ask on Discord if others think it's a bug or not.
