### ISSUE TITLE
Great Altar adds non-military units production. Public works dont't add city security level.

### ISSUE THREAD

**Issue by myclan123** [LoneGazebo/Community-Patch-DLL#10639]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

4.4.2

_3. List of Other Mods_

None

_4. Describe the Issue_

Great Altar should only +15% military unit production, but instead it also +15% envoy/worker/settler production.
Public works don't add city security level.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Gajah Mada.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14175528/Gajah.Mada.zip)

_9. Screenshots of the Issue (Optional)_
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/143814249/d20e73b2-b265-41a8-b0c0-e8f21c21f3e3)
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/143814249/3989d7e7-5bcc-4b09-aa72-d16f9d890b7a)

**Comment by axatin** [comment]
Public works are already fixed for the next version.

**Comment by azum4roll** [comment]
I don't know why Great Altar and Hexxon are using domain modifiers instead of the MilitaryProductionModifier column.
