### ISSUE TITLE
Monopolies & Corporations tab

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1063]
![monopolies corp](https://cloud.githubusercontent.com/assets/12978597/12173095/8b3b248e-b55d-11e5-8c69-4701a2f155e6.jpg)
There are two "t" tabs in there. This is in 1/3, so sorry if you've already fixed that.

**Comment by LoneGazebo** [comment]
Lua log?

**Comment by LoneGazebo** [comment]
that 't' symbol is actually indicative of a lua break.

**Comment by GrantSP** [comment]
I saw that too and just thought it was the UI poorly showing an empty label as in my games the header shows after clicking it and it didn't have any information below. Or is the lack of information below also an issue?

**Comment by LoneGazebo** [comment]
lua.log?

**Comment by GrantSP** [comment]
Yeah I saw it a couple of games ago. As soon as I see it again I'll post one.

**Comment by LoneGazebo** [comment]
I could use a lua.log for this...

**Comment by GrantSP** [comment]
I have started a few games but can't seem to replicate it at will, hence no logs.

**Comment by LoneGazebo** [comment]
Nice! I'd rather it not come back up than be a bug! :)
