### ISSUE TITLE
Indonesia monopoly bonus doesn't count cloves

### ISSUE THREAD

**Issue by myclan123** [LoneGazebo/Community-Patch-DLL#10637]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

4.4.2

_3. List of Other Mods_

None

_4. Describe the Issue_

The Monopoly of cloves should give 6+2 happiness instead of 6 for Indonesia UA, but until I gain monopoly of Jewelry the extra +2 doesn't come into being.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[temp.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14160404/temp.zip)

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/143814249/4cc126f3-98f3-4227-b7fa-6412b948a463)
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/143814249/a87a3da6-a518-4b6c-9d91-ea3a56f72254)

**Comment by azum4roll** [comment]
Can't replicate using IGE+. Will need someone loading the save to check I guess.

**Comment by axatin** [comment]
Everything is correct here. You have 19 resources (amber is both owned and imported) giving 2 Happiness each, and then 8 happiness from the monopoly.
