### ISSUE TITLE
Community Mod 4.4.2 CTD towards Turn 311

### ISSUE THREAD

**Issue by Daedalus86** [LoneGazebo/Community-Patch-DLL#10645]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_
Community Patch only version 4.4.2

_2. DirectX Version_
DX11

_3. List of Other Mods_
None

_4. Describe the Issue_
When going to turn 311 the game crashes to desktop... already loaded an game from a few turns before that to see if that fixes anything. But it always CTD.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
This is an savegame in turn 310, so if you click on Next turn. It wil CTD.
[Gustavus Adolphus_0310 AD-1880.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14230002/Gustavus.Adolphus_0310.AD-1880.zip)

Older Save Games:
[Older_Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14230224/Older_Saves.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14230003/logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14230004/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_
From Save Game, just click on Next Turn. It crashes on the Byzantium turn.

**Comment by axatin** [comment]
@Daedalus86 
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14230513/CvGameCore_Expansion2.zip)
you can use this file to continue playing
