### ISSUE TITLE
Preventing any hostile espionage action is impossible

### ISSUE THREAD

**Issue by radziu93** [LoneGazebo/Community-Patch-DLL#10647]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

4.4.2

_2. DirectX Version_

DX 10

_3. List of Other Mods_

More Wonders for VP
More Unique Components for VP
Less Warmonger for VP
Pontoon Bridges for VP

_4. Describe the Issue_

As title says. Now any hostile spy operation is guaranteed success. Spy can still be identified and imprisoned/killed, but this doesn't change a fact, that no matter how badly he does, operation is a success. While this issue inclues all spy actions, especially constant stealing of my Great Works is incredibly annoying.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Elizabeth1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14230798/Elizabeth1.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

My logs are too big to attach here

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by ilteroi** [comment]
may be related to the "security level" being zero in all cities?

**Comment by axatin** [comment]
Both are intentional, see the proposal: https://forums.civfanatics.com/threads/6-cp-espionage-system-overhaul.685902/

**Comment by radziu93** [comment]
Okay, this is awful. Can I change anything in game files to just restore success chance, or the only way for now is to disable whole espionage system?

**Comment by axatin** [comment]
No, it can't be changed in the game files, success chances for espionage missions have been completely removed. You can start a forum discussion or make a proposal if you want it to be changed in the future
