### ISSUE TITLE
This project's github Issues disappearing?

### ISSUE THREAD

**Issue by Nu-Illasera** [LoneGazebo/Community-Patch-DLL#10640]
The issue tracker shows currently 172 issues while yesterday we were at 206

Only 3 of them were marked as closed since yesterday, where did the other issues went?

I AM ASKING NOT TO DELETE ISSUES, whatever the reason might be, close them with a full description as to why they were closed,
Even if they are old, even if its a mod conflict, even if you are not going to fix them.

We need to have a fully disclosed log on all the issues being reported.

**Comment by axatin** [comment]
They **are** being closed with an explanation, check the closed issues tab and sort by "recently updated".

**Comment by Nu-Illasera** [comment]
> EDIT : @axatin Helped me, i had to resort it, didn't even know about this option while working with github for years, my bad, I apologize.

Thank you, I have made a mistake.
