### ISSUE TITLE
Automated explore not possible even though there are reachable unexplored tiles

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#10642]
Mod version: Built from commit 2b874ffa

Issue: Automated explore can't be selected because it says there are no reachable areas to explore, but my scout is standing right next to some unexplored tiles.
![Screenshot (539)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/95587882/be8fa3e2-5329-4f22-b1ee-53b45613b4ff)

The problem is the check  `pPlayer->getCapitalCity()->HasAccessToArea(pPlot->getArea())` in `CvEconomicAI::TestExplorationPlots`, which returns false for the plots in question even though they are reachable from the capital.

@azum4roll Are you familiar with that code? It seems `HasAccessToArea` returns true only for areas that contain one of the plots directly adjacent to the city...

Additional Mods:
[MODS.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14181310/MODS.zip)

Save game:
[Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14181733/Save.zip)

**Comment by ilteroi** [comment]
use HasAccessToLandmass() instead?

**Comment by azum4roll** [comment]
I think HasAccessToArea makes sense only in vanilla. It's only checked when you don't have the embark tech, and in vanilla you need to go back to your territory to gain the embark promotion, so you can't risk to get stuck out there. The check can be removed in VP.

On the other hand, ScoreExplorePlot seems to add a huge value to ancient ruins that only recon units can get. Is there any way to do it only for recon unit automation when EconomicAI is unit-agnostic?

**Comment by axatin** [comment]
> I think HasAccessToArea makes sense only in vanilla. It's only checked when you don't have the embark tech, and in vanilla you need to go back to your territory to gain the embark promotion, so you can't risk to get stuck out there. The check can be removed in VP.

Good point, I didn't consider that  in vanilla embarkation is only given upon entering owned territory again. Removing the check in VP and keeping it in CP should be fine then.

> On the other hand, ScoreExplorePlot seems to add a huge value to ancient ruins that only recon units can get. Is there any way to do it only for recon unit automation when EconomicAI is unit-agnostic?

Plots with goody huts are excluded for non-recon units in `CvHomelandAI::IsValidExplorerEndTurnPlot`, which is called when assigning exploration targets to units.
