### ISSUE TITLE
Venice - cities

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#10641]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

The description says "gain happiness like normal cities", but in reality Venetian cities gain happiness like puppet cities.

**Comment by Vordikk** [comment]
Exactly they "gains" (produces) happines as normal cities and consumes happiness as puppets. Puppets of other civilizations do not produce any happiness and only consume it in amount of population/4.

**Comment by Padre19** [comment]
That seems to make sense. Thank you.
