### ISSUE TITLE
archeologist not shown in build options

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10651]
v 4.4.2

observe, archeologist is not in the list, not even in greyed out form:

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/ff4c8d1d-4b9a-4dca-8b2b-d0adbc9e34df)

this seems to be happening when an existing archeologist has finished their dig and is waiting for orders what to do (ie the 'choose archeology popup'). no idea what the connection is though.

**Comment by bentakacs** [comment]
Pretty dumb question, but does the city have a Museum?

**Comment by Nu-Illasera** [comment]
> Pretty dumb question, but does the city have a Museum?

I don't see how it affects the production of an archeologist.

**Comment by calloatti** [comment]
I think when you reach the limit of 3 archeologists, sometimes the option is disabled, or its not shown at all.

**Comment by bentakacs** [comment]
> > Pretty dumb question, but does the city have a Museum?
> 
> I don't see how it affects the production of an archeologist.

Since version 3.8.3, a Museum is needed in the city to train an archeologist there.

**Comment by Nu-Illasera** [comment]
Probably VP stuff, sorry, didn't know, i only use community patch AI changes.

**Comment by azum4roll** [comment]
Does it reappear once you pick the outcome? Even though it makes no sense.

**Comment by ilteroi** [comment]
yes it does iirc. and there is a museum

**Comment by axatin** [comment]
Tried to reproduce it, there seems to be no issue with archeologists waiting for orders, so it was probably the unit number restriction. Fixed archeologists not being shown in greyed-out form when the unit limit is reached.
