### ISSUE TITLE
When you capture an Indonesian city with pillaged Kampong improvements, automated workers stand over them and never repair them

### ISSUE THREAD

**Issue by calloatti** [LoneGazebo/Community-Patch-DLL#10654]
_1. Mod Version (X.Y.Z). Current Version: 4.4.2_

3.7.12

_2. DirectX Version_

12

_3. List of Other Mods_

_4. Describe the Issue_

When you capture an Indonesian city with pillaged Kampong improvements, automated workers stand over them and never repair them. You have to manually click repair on them

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/12817862/0aec36c7-edfe-434c-83bf-5c6584f62c78)

**Comment by azum4roll** [comment]
Should be fixed by the builder AI rework.
