### ISSUE TITLE
Highlands (for CP)

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#10659]
_1. Mod Version  4.4.2_

On the Highlands for CP mapscrips, all palyers spawn on the eastern side of the map, leaving the western part copletely empty.
(happend twice, using huge mapsize and 12 players).

**Comment by azum4roll** [comment]
There's no Highlands for CP.

**Comment by Der-Zorn-Gottes** [comment]
Yeah, it's called Hoghlands for VP.
