### ISSUE TITLE
Korea UA does not scale with era

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1066]
I could not spot the yields in the early ages, but I am getting 375 science for wonders/science buildings in capitol in industrial and modern age. This seems way too low.
I cannot tell whether this has scaled with gamespeed or not (playing Marathon), anyway it should.

**Comment by LoneGazebo** [comment]
Technically it bases its yield on '50% of the value of the median value of a tech we can research,' which is an odd way of doing it, to say the least. I'm just going to have it scale with era and gamespeed on top of that.
