### ISSUE TITLE
4.5 resource not being added to the tradeable ones, monopoly not updating

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#10666]
![civmono](https://github.com/LoneGazebo/Community-Patch-DLL/assets/53142313/fec5a3ce-4d83-4700-b968-eec2938d8086)

Latest beta, no other mods. A bit hard to explain but see the screenshot, I definitely own 3 coral tiles, all improved, yet one of those isn't considered when it comes to the monopoly. I reloaded some turns and the issue started when I sent the first boat to coral, doesn't matter in what town, such resource wasn't being correctly added to my disponibility.

**Comment by randomnublet** [comment]
I tracked it down, the bug happens when you conquer and then raze a city. Egypt had a city when Santiago is placed, and Ramses built that workboat. Upon city raze, and not having connected the other corals yet, I was in this situation:
![civmono2](https://github.com/LoneGazebo/Community-Patch-DLL/assets/53142313/336598d8-8e95-4600-8345-cdbeec8685e0)

**Comment by randomnublet** [comment]
> No idea at a glance. Either CvCity::PreKill() calls CvPlot::setOwner() twice, or CvPlot::setOwner() deducts resources twice.

If it helps, when I conquered that city I had no fishing researched yet. While razing it to the ground, I was (correctly) at 0% monopoly and couldn't trade the resource.

When the razing was completed (and fishing had yet to be researched), I experienced the lost resource issue, sitting at -1 resource under direct control.

**Comment by azum4roll** [comment]
CvPlot::setOwner uses IsResourceRevealed to remove resources from the old owner...
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/14953746/b0f55516-efd9-45b6-8694-da91484dced0)

but IsResourceImproveable to add resources to the new owner.
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/14953746/54cd3012-489e-41a3-91f4-d9c6a4bb7e8e)

**Comment by azum4roll** [comment]
Changing IsResourceRevealed to IsResourceImproveable should work.
