### ISSUE TITLE
Not able to build anything on 1st turn

### ISSUE THREAD

**Issue by vgh12** [LoneGazebo/Community-Patch-DLL#10665]
_1. Mod Version (X.Y.Z). Current Version: 4.5.0_
4.5

_2. DirectX Version_
DX 10 / 11

_3. List of Other Mods:
See screen shot below

_4. Describe the Issue_
Not able to build anything on turn 1

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_
Launch game, select mods, set up game and when starts not able to build anything 

_9. Screenshots of the Issue (Optional)_

![civ mods](https://github.com/LoneGazebo/Community-Patch-DLL/assets/160661863/ec83f919-2f52-43d8-b696-b763a214dc4d)

![civ screen shot](https://github.com/LoneGazebo/Community-Patch-DLL/assets/160661863/401ce15c-38a6-4f31-a12d-1c908e4d2f49)

**Comment by vgh12** [comment]
I will do that.  Thanks

**Comment by azum4roll** [comment]
Looks like a very old version of ICV.
