### ISSUE TITLE
4.5 free food from invisible city states

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#10667]
Latest beta, no other mods.

![freefood](https://github.com/LoneGazebo/Community-Patch-DLL/assets/53142313/54600427-fa5f-4a6e-9620-f67202e9a303)

This is the situation after I settled some cities... I didn't meet any single maritime city state yet, my capital (bottom right) food plays fair, same for the first expansion. When I settled my 3rd city though, I noticed some more food (3) coming out of nowhere, then the successive cities have 5 more food ''from city states'' each.

**Comment by randomnublet** [comment]
![freefood2](https://github.com/LoneGazebo/Community-Patch-DLL/assets/53142313/d0fbfc8f-9668-4d31-9672-9ddc2e188b72)

Freshly founded city in the same turn gets +12, it's growing out of control :D

**Comment by azum4roll** [comment]
Are you actually getting the food?

**Comment by ilteroi** [comment]
need to check

**Comment by randomnublet** [comment]
> Are you actually getting the food?

Yes, the latest fresh city who was getting +12 food out of nowhere for a total of +15 excess food grew from 1 to 2 pop in 1 turn.

**Comment by randomnublet** [comment]
Upon further testing this might be related to cs alliances, the number of free food (+0 in capital and 2nd city, +3 in 3rd city, +5 in 4th and 5th, and now +12 upon settling the 6th city) ramped up with the number of allies/friends, even if those are not maritime, and this number is not applying retroactive changes to cities food. 
For reference, I have 2 mercantile, 1 cultural and 1 militaristic allies when I found the 6th city and it gets +12 food right off the bat.

**Comment by ilteroi** [comment]
not sure if this is a real issue? anyway there are some changes (not mentioned in the patch notes)

* bonus food from maritime city states is now booked correctly as food from city states and not just added to the city plot
* freshly founded cities also get the bonuses (they did not before)
* siam trait is actually working (before was considered for the tooltip only)

so do your bonuses match your friendships/alliances?
