### ISSUE TITLE
Aztec Eagle minor description mismatch

### ISSUE THREAD

**Issue by tomekpa** [LoneGazebo/Community-Patch-DLL#10668]
_1. Mod Version (X.Y.Z). Current Version: 4.5.0_

NA

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

It says it has Cover I but it doesnt, its probably after old rework of discipline promotion.
I check other units from Iron working and Steel and they are already have descriptions updated correctly in this regard,
so this is probably the last one.
It is probable that it just lacks Cover I, but i honestly doubt this unit needs a buff :)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![obraz](https://github.com/LoneGazebo/Community-Patch-DLL/assets/21251138/3b92e270-906a-4b17-b03d-47d0b27d3047)

**Comment by azum4roll** [comment]
Go question @pineappledan. This isn't base VP.
