### ISSUE TITLE
4.5 tech tree not showing required amount of science for tech you can research

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#10675]
Science points not displayed for tech you can reasearch : 

![20240222162921_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/64471766/69245933-4a86-40df-aac7-abf205235365)
![20240222162925_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/64471766/c76917dd-9b83-4bd1-9c7f-c0dcb6a5cab2)

**Comment by jayeye2011** [comment]
I too saw this problem. Once a tech becomes available you no longer see the tech costs.
Good Tech Tree on turn 1
![GoodTechCosts_turn1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/ee587860-2730-407b-a561-00993cf67b73)

Bad Tech Tree on turn 10 after first tech researched.
![BadNoTechCosts_turn10](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/c03b35f1-86ac-4253-8a34-ecf6146cd387)

turn 19 
![BadNoTechCosts_turn19](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/8a61677e-b1a2-48ac-89fb-b0981694005c)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14387549/Logs.zip)
Here are my logs and saves (only VP4.5 w/EUI) mods


[ModdedSaves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14387551/ModdedSaves.zip)

**Comment by jayeye2011** [comment]
I tried the copied the revised TechTree.lua file into  4.5.0 and it removed all the tech cost data from the tech tree tool tips from the start. Not sure if this was because there are other files (like cpp or h) needed for the fix or not.  If this was intended that should have been a VP Congress Proposal as the ability to see the current tech costs is used to determine how what techs the AI civs have already researched in order to estimate the likelihood of being able to build a world wonder.
turn 2 tech tree tool tip shows no costs for any of the first ancient era techs include the one being researched as shown.
![NoTechTreeCosts_turn2](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/ffa095de-a429-4535-8c2e-80b9e9ea2f51)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14402481/Logs.zip)
[ModdedSaves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14402484/ModdedSaves.zip)

**Comment by jayeye2011** [comment]
This is how the tech tree cost tool tips should look, taken from VP 3.7.11.
turn 0 before initial tech selection
![VP3 7 11techtree_turn0beforeselect](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/b3e45ff0-50cc-4038-86ef-c44f20f3c751)
turn 0 after first tech selection
![VP3 7 11techtree_turn0afterselect](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/a30d21ed-1a63-4fcb-9771-90e6595515e6)
turn 10 finished first tech research
![vp3 7 11techtree_turn10a](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/ef5735a7-c07a-457d-829b-46ca552410e7)
![vp3 7 11techtree_turn10b](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/b6885b16-2c3f-4b44-8e93-cd62ac651579)
![vp3 7 11techtree_turn10c](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/0d8685bf-d5f1-45d7-ac7e-b595cb357372)
turn 12
![vp3 7 11techtree_turn12a](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/a591b7c7-db41-4761-9d84-84fb4cd40c61)
![vp3 7 11techtree_turn12b](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/d8414d8e-ff82-4c64-ab5f-b202007283d4)
![vp3 7 11techtree_turn12c](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/4b9dcee0-3bda-47e3-aa66-b3fd43ba8f7a)
![vp3 7 11techtree_turn12d](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/9f7f8b28-e6a2-4bb5-8747-f6e1d61db836)

**Comment by azum4roll** [comment]
Try again.

**Comment by jayeye2011** [comment]
Okay, the last techtree.lua patch worked correctly.
turn 0 before settle
![vp4 5 0techtreepatch_turn0_beforesettle](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/076119a7-7e24-4ec7-8a41-4f39bbacdddb)
turn 0 after settle before tech select
![vp4 5 0techtreepatch_turn0_aftersettle](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/482994fc-c917-498e-9d36-2f57f8f1f28d)
turn 0 after settle with tech selected
![vp4 5 0techtreepatch_turn0_techselected](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/9d8c3093-4d0f-409a-be03-f05a3ff52e8e)
turn 10 after first tech researched
![vp4 5 0techtreepatch_turn10_1sttech](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/b5cf66aa-2e9c-42a0-8089-177005d8b451)
turn 15 after 2nd tech researched
![vp4 5 0techtreepatch_turn15_2ndtech_a](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/e179ab6e-b809-4
![vp4 5 0techtreepatch_turn15_2ndtech_b](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/7eaa6ce8-465b-4584-8d1a-c82f1fd9899b)
8c7-b0b3-784977a02432)
