### ISSUE TITLE
4.5 City attack combat preview not shown

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#10676]
Damage preview is not displayed for city attack : 

![20240222173436_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/64471766/ab595c08-c833-479b-829e-6fc26e4165e6)

**Comment by bsesar** [comment]
Already reported and fixed

https://github.com/LoneGazebo/Community-Patch-DLL/issues/10671
