### ISSUE TITLE
4.5.0 Cancel button not working in espionage view 

### ISSUE THREAD

**Issue by Hugo-Pratas** [LoneGazebo/Community-Patch-DLL#10670]
_2. DX 11

_3. List of Other Mods_
InfoAddict, fast animations, furious turns, historical religions, squads for vp

_4. Describe the Issue_
Espionage view - click 'move' on the spy and you get this screen
![imagem](https://github.com/LoneGazebo/Community-Patch-DLL/assets/90699949/3ab584ab-5772-4208-ab82-3beb38f2d4c1)
if you then click 'Cancel' nothing happens.

**Comment by bsesar** [comment]
In case you need logging, here is a save file and the logs.
[cannot_cancel_spy_move.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14472381/cannot_cancel_spy_move.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14472382/Logs.zip)

To reproduce, go to Spy panel, try to move Recruit Fatiga --> cancel button does not work, but Esc key does. The only other mod that I have is Improved City View (v20).
