### ISSUE TITLE
Combat overview is not displayed when using city attack

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#10671]
_1. Mod Version (X.Y.Z). Current Version: 4.5.0_

_3. List of Other Mods_
Improved City View+ (v20)
IGE+

_4. Describe the Issue_
The Combat Overview panel is not displayed when using city attack.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[city_attack_panel.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14364310/city_attack_panel.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14364319/Logs.zip)

_8. Steps to reproduce the Issue (Optional)_
Use IGE to create a Barbarian unit next to your city and try to attack it with the city.

_9. Screenshots of the Issue (Optional)_
<img width="960" alt="city_attack_combat_overview" src="https://github.com/LoneGazebo/Community-Patch-DLL/assets/620131/4888040f-888c-46a8-981d-915e9c1d20dd">

**Comment by bsesar** [comment]
@azum4roll, it seems there is something wrong at line 947 in CoreLua\EnemyUnitPanel.lua:

Runtime Error: C:\Users\XXX\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files\CoreLua\EnemyUnitPanel.lua:947: Instance no longer exists.

**Comment by azum4roll** [comment]
Thanks, easy fix.
