### ISSUE TITLE
Combat Information shows "Minor Defeat" when naval melee attacking embarked units

### ISSUE THREAD

**Issue by usadefcon1** [LoneGazebo/Community-Patch-DLL#10672]
Mod Version:  Current Version: 4.5.0

Describe the Issue: 
Combat Information shows "Minor Defeat" when naval melee attacking embarked units.
Approximate damage inflicted is 23 - 0. This should not be a minor defeat.

Screenshots of the Issue:
![Defeat](https://github.com/LoneGazebo/Community-Patch-DLL/assets/57153924/3b98be9b-3ec8-4504-a7f4-8e643f864939)

**Comment by azum4roll** [comment]
That's always been how it's shown. I guess I could change it to DECISIVE VICTORY.
