### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1068]
How is City Strength calculated on Mountains? Is it the same as CITY_STRENGTH_HILL_CHANGE ?

**Comment by LoneGazebo** [comment]
No need for caps. 

if(plot()->isMountain())
	{
		m_iStrengthValue += (/*3*/ GC.getCITY_STRENGTH_HILL_CHANGE() * 2);
	}

**Comment by Iamblichos** [comment]
Well I wasn't meaning to do caps, I copied and pasted the column from the defines table.

**Comment by LoneGazebo** [comment]
No worries. :)
G
