### ISSUE TITLE
order of effects in combat preview

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10687]
V 4.5

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/e5b2b38c-d953-4801-afb1-aa3db403b003)

note that it says +73% for misc bonuses, whereas everything listed explicitly is <=20%.

would it be possible to sort the bonuses by absolute value so that the most important components are guaranteed to be listed first?

**Comment by azum4roll** [comment]
Just noticed it's missing the terrain defense, will fix.

The ones that are not easy to deduce (unit health, anti-warmonger fervor, auras, multiattack, near capital bonus, etc.) are shown first, then the ones that may be unclear to newer players (flanking, trait bonuses, etc.), then the rest.

The +73% here are from promotion (+20% shock, +33% in forest, +10% morale, +10% honor). Missing +25% from terrain defense.

**Comment by axatin** [comment]
> but different approach: is it possible to enlarge the area of the textbox?

done
