### ISSUE TITLE
AI's buy units at full XP

### ISSUE THREAD

**Issue by psparky** [LoneGazebo/Community-Patch-DLL#10686]
Found by code inspection, but affects all versions for at least the last 6 years!

Calls of CVCity::CreateUnit from CvCity::CheckForOperationUnits, CvEconomicAI::DoHurry and CvMilitaryAI::BuyEmergencyUnit don't set the bIsPurchased parameter. This means the units get full XP.

Some of these calls don't seem to result in a cooldown being set either.

Please take into consideration that balance issues may arise if fixing this.

Sorry, but I don't have any saves or logs from any recent release showing the problem.

**Comment by KungCheops** [comment]
To add onto this, the function CvCity::Purchase, which is called when a Human player buys a unit/building/etc. does a lot more than what is done in CvCity::CreateUnit.

E.g. setting the purchase cooldown as mentioned above, but also seems to be a few more things.

**Comment by calloatti** [comment]
This probably explains how the AI materializes two new units while you are siegeing a city and they attack you on the same turn.

**Comment by ilteroi** [comment]
wow this is really some of the worst code i've seen in a while

**Comment by jayeye2011** [comment]
This should be fixed, especially if it applies to lower difficulty. It might be okay for king to deity but not for settler to prince difficulty.
