### ISSUE TITLE
4.5 Weird CS behavior

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#10689]
In the below screenshots, Vilnius suddenly became allied with Indonesia when I attacked the archer (bottom right) : 
![20240227225639_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/64471766/be192a95-2fc4-4aed-ace1-de3ebf33754e)
![20240227225656_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/64471766/b44aea24-04d3-40ce-9958-d641d3a420f2)

Also saw a CS turn hostile when I conducted a great diplomat mission with them. Sadly no screenshots or logs.

**Comment by azum4roll** [comment]
Mod list?

**Comment by Zuizgond** [comment]
Only 3/4 UC (v87) and RAS (v15).

**Comment by randomnublet** [comment]
Did Indonesia spawn a geat general due to the xp received on the archer, and maybe that was a quest trigger for the AI?

**Comment by Zuizgond** [comment]
Technically it would be possible they had a GG quest, but as I also had a CS turn hostile after expending a GD on them I tend to think there might be something wrong with CS influence.
I know the lack of logs doesn't help. I'll check how to enable it.

**Comment by azum4roll** [comment]
Logs won't help. Need a savegame and someone willing to load it to check.

**Comment by axatin** [comment]
Without save games it can't be investigated further. Let's assume it did happen as discussed and there was no bug. If you encounter some other strange influence behavior, create a new issue with a save game from one turn before.
