### ISSUE TITLE
Flood Plain cities have normal desert movement penalty.

### ISSUE THREAD

**Issue by Llednar-Twem** [LoneGazebo/Community-Patch-DLL#107]
Founding a city on a flood plain seems to remove the actual "flood plain" terrain type.  As a result, moving onto the tile uses the increased movement cost of regular desert.  The inherent road / railroad cities eventually get mostly mitigates the issue, but it can still be problematic at times.  Overall a very minor bug, but still occasionally irritating.

**Comment by LoneGazebo** [comment]
I'll fix this.
