### ISSUE TITLE
Sri Pada is one tile island

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1070]
Today's beta, never seen this before in Civ 5.

![2016-01-08_00001](https://cloud.githubusercontent.com/assets/11132095/12214208/81ebc67e-b650-11e5-8fcf-54f18cfe89fa.jpg)

It's the continents mapscript and I can't imagine this would have been touched by CBP, but I've never seen it to my recollection and it struck me as odd so I'm passing it along.

**Comment by LoneGazebo** [comment]
It can happen sometimes, oddly enough. I've seen it two or three times.

**Comment by joosegoose** [comment]
Had a feeling, just figured I'd check. I think I'm just more paranoid of things with a fresh new beta ;)
