### ISSUE TITLE
Late Game CTD 4.5.1

### ISSUE THREAD

**Issue by iJuanHello** [LoneGazebo/Community-Patch-DLL#10707]
_1. Mod Version (X.Y.Z). Current Version: 4.5.0_

4.5.1

_2. DirectX Version_

dx11

_3. List of Other Mods_

VP
Community Events
EAW 4VP (Standard for VP 4.4)
Dolen2's Ethnic Diversity trinity
Great Prophet Historical Names
Music Changer
Quick Turns
Civ VI Style City Names

_4. Describe the Issue_

CTD When I send an aircraft to attack the barbarian in my territory (Assur). Repeatable upon reload. If using the turn before save, use the aircraft to attack the barbarians and it'll happen. Will take a few attacks. If using the turn of save, should be the first attack.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[turn before.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14505270/turn.before.zip)
[turn of.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14505273/turn.of.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14505474/logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14505373/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

If using the turn before save, end turn. Barbs will spawn due to Iroquois, I believe. Use the aircraft from the carrier between Assur and Enlil(sp) to attack the barbarians and it'll happen. Will take a few attacks, but is reproducible.

_9. Screenshots of the Issue (Optional)_

**Comment by iJuanHello** [comment]
Finishing off the barbs with my tanks didn't trigger the CTD, so I believe it's isolated to aircraft attacking them.

**Comment by ilteroi** [comment]
minidump points to a location outside the gamecore ...

**Comment by iJuanHello** [comment]
Had another instance of this under the same conditions later this game. Enemy spy spawned barbs in my territory, bombing them with planes triggers CTD. I've been going plane-heavy for the past ~70 turns but the only CTDs all game have been the two I reported here. 

[logs (2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14516622/logs.2.zip)
[turn of (2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14516628/turn.of.2.zip)
[turn before (2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14516633/turn.before.2.zip)
[CvMiniDump (2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14516646/CvMiniDump.2.zip)

**Comment by ilteroi** [comment]
same

**Comment by axatin** [comment]
Yes, this is a memory issue, not a VP bug. You can try turning off combat animations or deactivating the Ethnic Diversity Mod, which is quite memory-heavy.

**Comment by azum4roll** [comment]
I guess it's Ethnic Diversity loading the plane model causing it then.
