### ISSUE TITLE
Spies for England do not operate level higher

### ISSUE THREAD

**Issue by tomekpa** [LoneGazebo/Community-Patch-DLL#10706]
_1. Mod Version (X.Y.Z). Current Version: 4.5.1

_2. DirectX Version_

_3. List of Other Mods_

![obraz](https://github.com/LoneGazebo/Community-Patch-DLL/assets/21251138/cc47d797-94c4-416e-8086-ce6e1932489c)

_4. Describe the Issue_

As shown in the screenshots, Spy Level 2 gets 20 extra network points, and Spy Level 3 gets 30.
If i recall corectly Level 1 gets 10 points, and i think those values were the same when i played non england.

 I would expect, that if max level is 3, then level 2 spy should get 30 points.

I could be wrong if in fact level 1 spy should get zero extra point, which then it would be correct behaviour, but then again,
level 3 spy, would operate as in fact level 4, and to my knowledge, max level should be 3. 
Ofc, assuming the purpose of this ability is to need less training for spys for them to reach max level.
If this is correct behaviour, then maybe it would be good to change wording in England description, indicating, that their spy could operate as level 4.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![obraz](https://github.com/LoneGazebo/Community-Patch-DLL/assets/21251138/d018efe0-c3f6-4750-a1dd-066e205f9bc2)

**Comment by azum4roll** [comment]
It's correct. Non-English Recruits get 20 base NP only.
