### ISSUE TITLE
barbarians capturing city states

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10702]
v 4.5

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/77af791e-8a43-466f-8aa1-b97c8309c502)

this is an island which has not been discovered by any major player yet. all the minors have been taken over by barbarians after the horde quest expired. intended?

**Comment by azum4roll** [comment]
You mean there shouldn't be hordes before any major civ meets them?

**Comment by ilteroi** [comment]
well there are 4 options ...

1. do nothing
2. change the quest
3. improve the defense capabilities
3. don't create the quest

**Comment by axatin** [comment]
there is already code that should prevent the quest from being given to island CS

 CvMinorCivAI::SpawnHorde
![hordeisland](https://github.com/LoneGazebo/Community-Patch-DLL/assets/95587882/0b0e7425-84ed-469a-95c1-6acdaf4c5344)

**Comment by azum4roll** [comment]
Then it was just normal barbs taking over the cities? Is it possible?

**Comment by ilteroi** [comment]
barbarians cannot capture cities the normal way afaik

**Comment by azum4roll** [comment]
They can, but I'm not sure about City States.

**Comment by ilteroi** [comment]
yeah i was just about to say this:

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/afc0641c-2b73-4362-981c-01af6153dec4)

but they are not very efficient ... i'm kind of itching to change this. but then we also need to improve the AI offshore colonization logic

**Comment by ilteroi** [comment]
ok ran the autoplay again ... this is turn 87 ... that was quick :)

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/f1775fd0-6a27-48b0-ae49-db0cb107ccf1)

now, maybe a  quick hack is to make barbarians ignore minor-owned cities?

**Comment by axatin** [comment]
or we could give minor civs a combat bonus against barbarians

**Comment by ilteroi** [comment]
that might also work ... but i was thinking since minors don't attack camps, it would be a nice symmetry for barbarians to ignore city states. could even go further and say barbarians and minors are *not* at war except during the horde quest or if the minor is allied with a major.

**Comment by axatin** [comment]
I've seen your forum post, agree that the discussion should be continued there.
