### ISSUE TITLE
Multiplayer CTD when offering to trade city at war

### ISSUE THREAD

**Issue by vaderkos** [LoneGazebo/Community-Patch-DLL#10710]
It's an edge case. I don't think this has high priority as this might have some implications to fix and is rather rare. I also think this might also happen in newer versions

_1. Mod Version (3.10.14). Current Version: 4.5.0_
Modpack [3.10.14_VP-SSEM_EU](https://drive.google.com/file/d/1BQ_B5x-fDyvmGvdfLHRKp_4MX-YW_eA7/view?usp=drive_link)

_3. List of Other Mods_
Only everything from 3.10.14_VP-SSEM_EU

_4. Describe the Issue_
CTD on next turn if captured city is traded to other human player.

_8. Steps to reproduce the Issue (Optional)_
1. Start war between 2 human players (A and B for simplicity, player A makes turns first).
2. _Player A_ offers owned city in trade deal to _player B_ and ends turn.
3. _Player B_ captures offered city and **only then** approves deal.
4. CTD on next turn

**Comment by ilteroi** [comment]
do you have a minidump?

**Comment by vaderkos** [comment]
@ilteroi nope, unfortunately not, we already moved to playing older version so nothing is available. I can only guess. Might be the deal had null pointer to city as city was already owned by another player.

**Comment by axatin** [comment]
After player B accepted the deal, did a notification "The deal is no longer valid" show up?

Can you attach DiplomacyAI_TradeAgreements_Log ?

**Comment by vaderkos** [comment]
@ilteroi @axatin I have found some minidumps, but not sure if any of them is related exactly to described CTD.
@axatin unfortunately, I can't find logs related to that game with CTD. I'll attach all logs. (It was trade between Arabia and Korea)
[minidumps.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14546357/minidumps.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14546362/Logs.zip)

**Comment by axatin** [comment]
I recreated the scenario, but when I tried to accept the deal after taking the city, I got a message that the deal is no longer valid, which is the intended behavior. I assume you don't have a savegame anymore? Reopen if you have one, or if you run into the issue again.
