### ISSUE TITLE
Currency on Tech Tree does not show extra trade route

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1071]
![2016-01-09_00001](https://cloud.githubusercontent.com/assets/11132095/12214904/c1575e0c-b66b-11e5-9517-192a9a564b21.jpg)

The pedia does show that Currency grants an additional trade route, but the tech tree doesn't.

**Comment by TechpriestEnginseer** [comment]
You're just going to have to accept this and move on. This is a common issue where you would have more than 5 "items" requiring a certain technology. Most likely the trade route was overlapped.

**Comment by joosegoose** [comment]
Sorry, I didn't know about any of that. I don't really care personally honestly, just trying to be helpful!
