### ISSUE TITLE
ExecuteWorkerMoves()

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10719]
i see the following in ExecuteWorkerMoves()

```
		if (pBestCity && pUnit->GeneratePath(pBestCity->plot(), CvUnit::MOVEFLAG_NO_ENEMY_TERRITORY|CvUnit::MOVEFLAG_PRETEND_ALL_REVEALED, 23))
		{
			ExecuteMoveToTarget(pUnit, pBestCity->plot(), CvUnit::MOVEFLAG_NO_ENEMY_TERRITORY|CvUnit::MOVEFLAG_PRETEND_ALL_REVEALED);
```

why the (unnecessary?) cheating with MOVEFLAG_PRETEND_ALL_REVEALED?

i would however recommend using MOVEFLAG_AI_ABORT_IN_DANGER and/or MOVEFLAG_ABORT_IF_NEW_ENEMY_REVEALED

**Comment by ilteroi** [comment]
@KungCheops

**Comment by KungCheops** [comment]
This isn't my doing, was introduced in this commit: 31fc2362da5faf9ae857eeb57b43926bfd3dd457

**Comment by ilteroi** [comment]
hmm so it seems i did that? well then it must be good :)

seriously, cannot remember why ... need to think about it
