### ISSUE TITLE
something wrong with unhappiness

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1072]
![image](https://cloud.githubusercontent.com/assets/1358966/12215610/19209726-b6c5-11e5-9eb8-24750ef9ede8.png)

i guess the best solution would be to simply outlaw crime :)

**Comment by ilteroi** [comment]
also, it seems all children are below average in this game ...

![image](https://cloud.githubusercontent.com/assets/1358966/12215621/8ab2659a-b6c5-11e5-8868-1607f4da654c.png)

**Comment by Der-Zorn-Gottes** [comment]
Yes, I think it is a bit too rough. In my last game, I spent almost half the time in unhappines, and two games before I had to scratch because I couldn`t climb out of the unhappiness hole.

**Comment by ilteroi** [comment]
ok. seems that BALANCE_HAPPINESS_BASE_CITY_COUNT_MULTIPLIER is set to 150, where 5 would be more appropriate ...

**Comment by LoneGazebo** [comment]
Weird, haven't seen it go that high. To be clear, though, the '150' value was done to make it more granular (the modifier should actually be lower now. Was 2, is now 1.5.

G

**Comment by ilteroi** [comment]
did you do any changes there lately? maybe it's a simple version mismatch between the code from github and your 1/8 release?

anyway, i don't see a 100 denominator in CvCity::getThresholdAdditions()

**Comment by LoneGazebo** [comment]
Yeah, I need to update DLL.
G

**Comment by LoneGazebo** [comment]
Done. Update pushed.

**Comment by joosegoose** [comment]
Update pushed? I don't see anything new in the betas folder, so I assume this just means github code?

**Comment by ilteroi** [comment]
this only affected you after re-compiling the dll. closing the issue

**Comment by joosegoose** [comment]
Oh. Well I guess it's unrelated then, but there seem to be a few of us experiencing rougher than normal crime with the beta release as well.
