### ISSUE TITLE
4.5.1 - Workers are suiciding themselves into enemy units

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#10735]
_1. Mod Version (X.Y.Z). Current Version: 4.5.0_

4.5.1

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

A continuous behavior I am seeing in many games now. When workers are on auto-work, they love to work unprotected tiles right next to enemy armies, leading to dozens of losses over the course of the game. 
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Bug_AI Worker Suicide.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14628141/Bug_AI.Worker.Suicide.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs - Copy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14628157/Logs.-.Copy.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/20593976/008d1d88-4796-43ba-af1e-fafe21365a6d)

**Comment by bsesar** [comment]
Should be fixed in the next version

https://github.com/LoneGazebo/Community-Patch-DLL/pull/10699
