### ISSUE TITLE
Inconsistent tile purchase costs with America's Manifest Destiny feature

### ISSUE THREAD

**Issue by ZetaLambdaNinja** [LoneGazebo/Community-Patch-DLL#10736]
_1. Mod Version (X.Y.Z). Current Version: 4.5.0_

Vox Populi Version 4.5.1

_2. DirectX Version_

_3. List of Other Mods_

pineappledan's More Unique Components for VP (4.2+ compatible version)

_4. Describe the Issue_

I'm playing as America, which means I can purchase opponent tiles with Manifest Destiny.  In the attached save, you'll notice that for the city of Chicago, all of the tiles that Lhasa owns can be purchased for a minimal amount, except one that outstandingly costs 445 gold.  I'm not actually sure whether the expensive tile is messed up, or all the cheap ones are.  (Seems reasonable I should have to pay extra for stealing land.)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[BUG-ChicagoPlotCosts445Gold.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14628875/BUG-ChicagoPlotCosts445Gold.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[ManifestDestinyBugLogs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14628877/ManifestDestinyBugLogs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

In the attached save, click on Chicago's banner to enter the city screen, and note the costs of buying tiles owned by Lhasa, the city-state to the south.  One is uber-expensive, while the rest have costs comparable to unowned tiles.

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
A consequence of the bug that also causes #10688
