### ISSUE TITLE
Fighter promotions

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1073]
No big thing, but I noticed that there are two promotions for fighters that are identical. 
Both "Sortie" and "Air Interception I" add one interception chance per turn. Assuming that there are "Air Interception II" and more, "Sortie" can probably be scrapped.

**Comment by GrantSP** [comment]
"Air Interception 1" makes the combat strength of interception 33% greater whereas "Sortie" adds another interception run to the unit. At least according to the database and the code it does.

**Comment by LoneGazebo** [comment]
That's correct, @GrantSP 
G
