### ISSUE TITLE
 Great Lighthouse and Navigator II promotion

### ISSUE THREAD

**Issue by myclan123** [LoneGazebo/Community-Patch-DLL#10745]
It seems that Great Lighthouse works as giving every naval unit the free promotion of Navigator II. But if my units already have  Navigator II promotion, the Great Lighthouse will give nothing. Will it be better to make a unique promotion for Great Lighthouse like  Navigator III?

**Comment by azum4roll** [comment]
There was a separate promotion for Great Lighthouse in vanilla, but it was made Navigator II instead. Maybe if you dig deep into the forums you could find why.

**Comment by Vordikk** [comment]
Supposedly before reworking naval it was extremely OP.

**Comment by Tekamthi** [comment]
the problem was stacking all the various unique naval movement promos -- england w/ great lighthouse and treasure fleet etc., would get like 10 moves per turn if they could collect all the bonuses in one game, vs everyone else having like 5.  It was too much for the community's tastes
