### ISSUE TITLE
Feature/adjustment request: UnitFreePromotion in Improvements table & turn timers

### ISSUE THREAD

**Issue by Tekamthi** [LoneGazebo/Community-Patch-DLL#10743]
The Improvements table contains a field, 'UnitFreePromotion' that sits unused in VP.

When populated, it adds the designated promotion to any eligible unit that enters the plot.  When combined with the 'IsLostOnMove' field in the Promotions table, the resulting improvement/promo pairing can be entirely location based, dropping off the unit as it moves out of the plot.

Or it can stay active on the unit after it moves away.  In my current usecase, the promo is not intended to drop off immediately, but has a  'PromotionDuration' so it falls off eventually.  Units can re-add this promo by re-entering the relevant improvement plot.  However, if the PromotionDuration timer has not yet expired, the unit experiences no change at all ie the promo stays up with the partially expired timer as-is.  

Request:  It would be preferable to have the timer reset to the full PromotionDuration value in this situation.  One quick-and-dirty way to do this is just to remove the promo then immediately re-add it, but doing so in lua is inefficient; since this check is already happening at the dll level, would be nice just to have it reset the timer all at once each time this process triggers

**Comment by Padre19** [comment]
Also now this promotion is given even if improvement is pillaged.

**Comment by ilteroi** [comment]
both fixed

**Comment by Tekamthi** [comment]
I think there is a problem here -- I am testing this right now, and it seems to work as follows:

1st move into improvement plot: unit gets promo
2nd move into improvement plot, with promo already active: unit's promo gets set to 0 turns remaining, then expires next turn
3rd move into improvement plot: unit gets promo, just like 1st

obviously the reset timer to 0 is undesirable here, should reset timer to max duration

I am also having trouble getting it to trigger off unique improvements -- the shared/common improvements all work, but unique improvements aren't so far in a few tests.
