### ISSUE TITLE
CTD When Removing Building from Queue

### ISSUE THREAD

**Issue by EmptyMonad** [LoneGazebo/Community-Patch-DLL#10742]
Current Version: 4.5.1
Vox Populi + EUI
No Other Mods

Seems the game crashes after trying to cancel the monument and swapping to a worker. Please confirm.
Also, I noted that Russia still gives tiles from ruins, without culture rebate or whatever was meant to be disabled.

Cheers,
V

Save Game:
[AutoSave_0010 BC-3600.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14681824/AutoSave_0010.BC-3600.zip)

Logs:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14681829/Logs.zip)

_7. CvMiniDump.dmp File:
[CvMiniDump.dmp](https://github.com/LoneGazebo/Community-Patch-DLL/files/14681840/CvMiniDump.dmp)

_8. Steps to reproduce the Issue:
Allow Shrine to finish. Remove queued Monument. (May require one extra turn to pass.)

**Comment by ilteroi** [comment]
the minidump points outside the gamecore, so not much hope ...

can't load the save, even with a clean 4.5.1 rebuild. weird. maybe somebody else can try

**Comment by axatin** [comment]
I can load the save and I can also switch buildings in the queue without any problems. Memory issue.

**Comment by EmptyMonad** [comment]
I will try a full reinstall and come back around on it in a day or so.On Mar 21, 2024, at 1:50 AM, ilteroi ***@***.***> wrote:﻿
the minidump points outside the gamecore, so not much hope ...
can't load the save, even with a clean 4.5.1 rebuild. weird. maybe somebody else can try

**Comment by axatin** [comment]
You can try reinstalling with non-EUI, that should help
