### ISSUE TITLE
Broken tooltips

### ISSUE THREAD

**Issue by pixlepix** [LoneGazebo/Community-Patch-DLL#1074]
Playing with full version + EUI, windows 10 from installer. 

http://puu.sh/mpeRA.png

**Comment by LoneGazebo** [comment]
Seems like your copy of EUI ended up in the wrong place. Make sure it is in the DLC folder of your main civ install.
G

**Comment by pixlepix** [comment]
I have a UI_bc1 folder in ASSETS/DLC. Is this not correct?

I originally had EUI installed before installing the community patch. However, I uninstalled (via steam "Delete local game content"), reinstalled, and ran the installer.

**Comment by Edaka** [comment]
Recheck if the Assets/DLC folder that UI_bc1 got into is on the correct drive that you have Steam installed on. Especially if you don't have it on your C drive, which is the default location and which is where UI_bc1 might have ended up.
