### ISSUE TITLE
Ceremony +1 happiness

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#10755]
4.5.1

I don't find the POLICY_LEGALISM entries in the Policy_BuildingClassHappiness table like they should be.
I asked Jarcast for his debug database, and he didn't have them either. 
Please could someone more confident on this than me check, and if it is indeed missing then lines 88--102 in Tradition.sql
```
-- +1 happiness to National Wonders with building requirement
INSERT INTO Policy_BuildingClassHappiness
	(PolicyType, BuildingClassType, Happiness)
SELECT
	'POLICY_LEGALISM', Type, 1
FROM BuildingClasses
WHERE MaxPlayerInstances = 1 AND (
	EXISTS (
		SELECT 1 FROM Building_ClassesNeededInCity
		WHERE BuildingType = DefaultBuilding
	) OR EXISTS (
		SELECT 1 FROM Building_ClassNeededAnywhere
		WHERE BuildingType = DefaultBuilding
	)
);
```
are presumably not working?

**Comment by Hokath** [comment]
It looks like the issue was
Line 1188 reads PreBuildingChanges.sql, deletes table Building_ClassesNeededInCity
Line 1214 reads Tradition.sql, references Building_ClassesNeededInCity to make Legalism effects.
Line 1228 reads BuildingChanges.sql, where it readds Building_ClassesNeededInCity

I moved Tradition.sql in the load order underneath BuildingChanges.sql and now they show up

**Comment by azum4roll** [comment]
Thanks for figuring that out. This will be a much needed Tradition "buff".
