### ISSUE TITLE
Question about MAX_MINOR_CIVS

### ISSUE THREAD

**Issue by Maksym-Nosatskyi** [LoneGazebo/Community-Patch-DLL#10753]
Hello, not sure if it's acceptable to post questions here, but no one replied to my post on the forums, so I figured I'd try. Sorry if I wasted dev time.
I wanted to start a game on a modified huge map with the vanilla balance of X civs to 2X CS, but made the map a bit too big for 20/40. I tried modding the dll to change the max number of civs and CS to 21 and 42 respectively, but while `MAX_MAJOR_CIVS` worked, `MAX_MINOR_CIVS` didn't seem to do anything, whether I set it higher or lower (nor does it automatically recalculate, as `MAX_CIV_PLAYERS - MAX_MAJOR_CIVS` would imply). What should I do to change the max number of CS to 42?

**Comment by axatin** [comment]
You have to change the value of MOD_GLOBAL_MAX_MAJOR_CIVS in CvGameCoreDLLUtil/include/CustomModsGlobal.h, then the other values should update automatically. You also have to use the 43 civ version to be able to select more city-states in the setup menu.

**Comment by Maksym-Nosatskyi** [comment]
> You also have to use the 43 civ version to be able to select more city-states in the setup menu.

Oooh, thank you. That must be what AdvancedSetup.lua does.
Can there be any unexpected differences (with regards to modmod compatibilty and the like) between the base version and the 43-civ version with changed civ and CS numbers?
