### ISSUE TITLE
VP 4.5.1 - Starts Maybe Too Close (7 tile Separation)?

### ISSUE THREAD

**Issue by jayeye2011** [LoneGazebo/Community-Patch-DLL#10751]
_1. Mod Version (X.Y.Z). Current Version: 4.5.0_
VP 4.5.1 (EUI option)

_2. DirectX Version_

DX11

_3. List of Other Mods_

None

_4. Describe the Issue_

With VP 4.5.1 (and earlier 4.4.2) versions, it seems like either my player starting location is to close to an AI civ or AI Civs are to close together. The second is good for me because it usually means I have more room around my starting location to expand. By too close, I mean 7 tiles separation. This means if one of the civs goes tradition then your city max boundaries either touch or will overlap (if both go tradition).
In this example, the player civ is Songhai and is in an okay situation as no AI civs are close, just close city states (annoying). But 4 of the AI civs (standard map, pangea, low sea level, 5 billion years, abundant resources) are too close to each other as shown.

Player - Askia of Songhai (good start except for a bunch of close city states which limit expansion options)
![PlayerStart-Good](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/02538cd6-54a8-4da3-93d7-1e0de9b57314)

AI Denmark - AI Sweden too close together
![Denmark-SwedenAIs-TooCloseStart](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/19820b38-c5ca-447f-8f8d-723fe4bffeab)

AI Assyria - AI Spain too close together
![Assyria-Spain-AI-Start-TooClose](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/01f415d7-296d-4e61-aac8-d9d1ec770b50)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[ModdedSaves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14732872/ModdedSaves.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14732875/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by jayeye2011** [comment]
Maybe the  map height and width size for each map size needs to be made  bigger to allow more land tiles to be available allowing better separation of starting locations. That is why I was using low sea level and 5 billion years to reduce the number of mountain tiles and to increase the number of land tiles as opposed to sea tiles.

**Comment by jayeye2011** [comment]
Well in the specific test case, it's the AI who are going to be fighting over turf, not the human player (Askia of Songhai) unless I want to spend my time taking out the city states that surround me, which is a pretty much a waste of time.  Even when it happens that the human player has a start that is 7 tiles away from a AI civ start, then you end up having to take out the AI civ in the ancient and/or classical era which in most cases is a waste of effort due to lack of development of its cities and before you have the tech for courthouse or are able to vassalize. I do not find it interesting to capture early era's underdeveloped cities only to have to raze them and resettle a more optimal city with my own settler.

I find that earlier VP versions seem not to have this issue or at least not occur as frequently. Here is an example of the first start roll for VP 2.4.4 using the same Askia of Songhai for human player on Pangea, standard size, low sea level, 5 billion years, abundant resources settings.

Askia-Aztecs
![vp2 4 4-askia-aztecs](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/5b2dc500-af24-4ba9-9722-ce67266b9d5e)

Askia India
![vp2 4 4-askia-india](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/3d0c65b1-8911-4144-a32d-10041339fe9c)

Aztecs - Denmark
![vp2 4 4-aztecs-denmark](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/08b3fefc-9606-477c-98aa-fc5865515c70)

[ModdedSaves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14735188/ModdedSaves.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14735189/Logs.zip)

**Comment by jayeye2011** [comment]
Maybe related to start bias, by disabling start bias using 4.5.1 pangea, standard size, 5 billion years, low sea level, abundant resource s as Askia had a decent separation to closest AI civ start location. Also all the other AI civs start locations were not near each other either (although some were very close 5 to 6 tiles to city states).


![vp4 5 1-askia start bias disabled](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/fbda3a8c-8d7e-4f9b-86ed-08f6b22bdc5b)

**Comment by azum4roll** [comment]
If you're on debug mode to reveal the map anyway, you should use Ctrl+Z to also show the resources. Nothing can be interpreted from the screenshots there.

**Comment by jayeye2011** [comment]
Easy enough to do since the autosaves were included in the download modded saves folder. Here are the screenshots of init0 turn before settler and using Ctrl-Z (which I did not know about before, don't usually use the debug mode as I normally use IGE).

Askia init 0
![askia_init0](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/b1db9948-0507-4dbd-a885-a6e627e80cf4)

Denmark-Sweden init0
![Denmark_Sweden_init0](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/19c01c96-1c2c-4e65-b183-e364425153c4)

Assyria-Spain  init 0
![Assyria_Spain_init0](https://github.com/LoneGazebo/Community-Patch-DLL/assets/69315126/6b147a29-6522-454d-a8d3-31a406a7dfb8)

It looks like for whatever reason, one of the AI's in each pair decided to move one tile closer to the other before settling, although going from 8 tile separation to 7 tile separation is not much of a difference.   I moved Askia of Songhai one tile to be next to the oasis for better food start without prior knowledge of the horses on that tile which actually put me one tile farther (from 6 to 7 tiles) from the city state to the north. So maybe the reason why disabling start bias allows for better separation of starting locations is that it prevents the AI civs from moving from their initial starting locations? Is there really any reason to allow the AI to change their initial settle point if this screws up the initial setup by bringing them to close together? 
Does using abundant resources somehow mess this up by making less options for starting placement?
The reason I prefer to use abundant resources is because I find that standard resources tends to be too sparse for my prefered Authority-Domination war game play style, often putting me in a position of having only 2 horse or 2 sword units or 0 horse/sword units in a 5 city settle area forcing a map restart. Also, I don't find that the strategic  balance setting actually works anymore either.

**Comment by jayeye2011** [comment]
So I guess if this closeness of starting positions is just an artifact of using abundant resources and the AI and player unintentionally moving closer, then there is not much that can be done here after all.

**Comment by azum4roll** [comment]
> disabling start bias allows for better separation of starting locations

Not a factor. Start locations are decided before placing civs onto them.

> Does using abundant resources somehow mess this up by making less options for starting placement?

Same with this. Start locations are before resources.

Either way, two civs starting 9 tiles from each other (aka 8 tiles in between) is perfectly normal.
