### ISSUE TITLE
starvation tooltip is wrong

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#10763]
v 4.5 dirty

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/71d9c83f-68c9-406f-a690-4bf23e69c517)

it says the city would starve faster (11 turns) with more food?

**Comment by azum4roll** [comment]
The city will still have 17.4 food left in 11 turns, and will have 6.32 food below the threshold in the next turn.

**Comment by ilteroi** [comment]
ah, then i misinterpreted it ...
