### ISSUE TITLE
4.5.1 Tourism Actual (or Visual) Bug

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#10764]
_1. Mod Version (X.Y.Z). Current Version: 4.5.0_

4.5.1

_2. DirectX Version_

_3. List of Other Mods_

[modlist.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14783746/modlist.zip)

_4. Describe the Issue_

I'm not sure what the exact bug is here, and whether its truly actual or just visual. But I'll note the weirdnesses I am seeing.

1) Both Poland, Indonesia, and I are getting +4 tourism from wonders. Only I have the sacred sites belief that should grant that. Poland has Artistry + Freedom, Indonesia has Fealty + Order.

2) On the city screen (using a spy), both mine and Indonesia's show +2 tourism when you hover over each work. Based on our buildings, we should both have +7. Meanwhile, Poland says +6, but they should have +9 (with creative freedom).

3) If you hover over the Poland's capital tourism, it will break down the values, including tourism for great work. When you do the math, its saying 7 tourism per work (and again it should be 9). On Byzantium's capital, the math is saying 4 tourism per work instead of 7. Indonesia's capital actually shows 2.46 tourism per work, which should not be possible.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Tourism Bugs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14783748/Tourism.Bugs.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs - Copy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14783749/Logs.-.Copy.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

I have spies in a lot of cities for Poland and Indonesia, so feel free to use them, or IGE for a good look.

_9. Screenshots of the Issue (Optional)_

**Comment by azum4roll** [comment]
Since it could actually matter, @Stalker012345 is using Improved City View.

**Comment by axatin** [comment]
Fixed now. Most of them were visual bugs, but there was also an error in the calculation: Bonuses to great works from creative expression were counted twice.

Note that fractional numbers for tourism per great work can arise because of the modifiers from hotels and stadiums.
