### ISSUE TITLE
Final Yield Request: Loyalty

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1076]
I have one last yield request (and don't worry, it is, as my development of the Cities in Development mod, where these new yields are needed to pacify the otherwise crazy City View, is coming to a close, and this was a pre-existing yield that I just used roundabout methods to calculate): YIELD_JFD_LOYALTY. Same as with CRIME, DISEASE, and HEALTH. 

Much obliged to your help :)

**Comment by LoneGazebo** [comment]
Will do.

**Comment by LoneGazebo** [comment]
And done. In next beta.

**Comment by JFDaly** [comment]
Thank you!

**Comment by LoneGazebo** [comment]
It's in the 1-10b beta FYI

**Comment by JFDaly** [comment]
Yup, got that, and it works perfectly.
