### ISSUE TITLE
City States ask for too high XP Units

### ISSUE THREAD

**Issue by der1weihnachtsmann** [LoneGazebo/Community-Patch-DLL#10779]
_1. Mod Version (X.Y.Z). Current Version: 4.5.0_

4.5.1.

_2. DirectX Version_

DX 11

_3. List of Other Mods_

4 UC
UCS
Extraction Outpost
Notifications Settings
Quick Turns
Squads
Upgrade All Units Button
Global Relations

_4. Describe the Issue_

City States asks for higher XP Units than I can produce or have.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

Its on the same turn but issue persists

[xp.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14816028/xp.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14816030/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![WhatsApp Image 2024-03-31 at 15 29 26_4c05f560](https://github.com/LoneGazebo/Community-Patch-DLL/assets/130388865/0432afe0-a1d6-4d27-ac91-83f47d95c9ce)

**Comment by Stalker012345** [comment]
I have seen this a few times, and what has likely happened is that the player has a Teocalli somewhere in there empire. I have found once you get even one teocalli, the quest XP rates will increase to expect that extra XP.

So probably not a bug, though we could argue whether that's "good" behavior or not.

**Comment by Vordikk** [comment]
City States do not accept poor weak units. In other words, you should actually spend part of your actual army to complete quests :)

**Comment by axatin** [comment]
You can produce units with 90 XP in Seoul.
