### ISSUE TITLE
Civilopedia entry for colosseum

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1077]
Straight from the forum: http://forums.civfanatics.com/showpost.php?p=14118942&postcount=32
I don't know what granary typos in GamerKG is talking about, though. Perhaps somebody with enough will and time could check that.

**Comment by GrantSP** [comment]
The tooltip for the Tech screen and the CityView should be the same as I believe they are generated by Lua.
The Pedia though does lack any mention of tourism. Rome's unique variant also lacks any mention of tourism, does it have it?

**Comment by LoneGazebo** [comment]
I'll check both.
