### ISSUE TITLE
Espionage - Cannot resolve event popup as new counterspy is blocked from selecting focus (Multiplayer)

### ISSUE THREAD

**Issue by sofrondr** [LoneGazebo/Community-Patch-DLL#10783]
_1. Mod Version (X.Y.Z). Current Version: 4.6_

4.5.1 Non-EUI modpack

_3. List of Other Mods_

None

_4. Describe the Issue_

One turn before, human player 2 (non-host, Russia) has assigned a new spy Tatiana (from new era reward) as a counterspy in capital Moscow. This turn, there is no option to select his focus (due to changing it recently, the spy claims). As that is an event popup that cannot be resolved, there is no way to continue the game.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Ramkhamhaeng_0378 AD-1958.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14817699/Ramkhamhaeng_0378.AD-1958.zip)
[Last 10 saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14817700/Last.10.saves.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14817701/Logs.zip)

_8. Steps to reproduce the Issue (Optional)_

Start MP game with two players, player 2 cannot complete his turn.

_9. Screenshots of the Issue (Optional)_

**Comment by EliskaSvobodova** [comment]
This happens ![Screenshot 2024-03-31 234932](https://github.com/LoneGazebo/Community-Patch-DLL/assets/41467806/c8cc096f-c0df-4242-8322-4d15799789de)

**Comment by sofrondr** [comment]
Turned out to be a badly copied modpack, sorry for irrelevant issue.
