### ISSUE TITLE
Multiplayer CTD - next turn + UI-Issue + many Desynced-Saves for Desync-Investigation

### ISSUE THREAD

**Issue by Tpk2210x** [LoneGazebo/Community-Patch-DLL#10784]
_1. Mod Version (X.Y.Z). Current Version: 4.6_

Version 4.4.2_VP_EUI -  located in Folder VP + EUI Only of this Link:
https://drive.google.com/drive/folders/1Sv2p7jq2TaZNqtuuVFf3bJc_bCPgIEW_?usp=sharing

_2. DirectX Version_
DX 10 & 11

_3. List of Other Mods_
Nothing

_4. Describe the Issue_
Main issue:
CTD for Player 2 (America) when processing next turn. Player 1 (Boudicca) is not crashing.
Saves 224-225 adresses this issue.

Second Issue:
When Genghis Khan started the war against Player 1 (Boudicca) in turn 216, it is not possible to view how much damage each of my units deal to Genghis units. The windows indicating terrain-bonus, flank-bonus, dmg inflicted, etc. is missing. This  UI-Bug proceeds for the whole session. The save file is 'Boudicca_0216_Github_WarDeclare' in the folder 'additional desyncs', the war is declared after advancing from turn 215 to 216.

Additional:
There are many additional savegames added in the folder 'additional Desyncs' in 'CIV_MP_DesyncsANDCTD'. In those saves, desyncs between Player 1 (Celts) and Player 2 (America) happened (same Playtrough as the CTD-save). This data can be used to further investigate desyncs but it's not guaranteed that every desync is 100% reproducable.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[CIV_MP_DesyncsANDCTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14817838/CIV_MP_DesyncsANDCTD.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[logs_Player2_America.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14817803/logs_Player2_America.zip)
[Logs_Player1_Boudicca.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14817807/Logs_Player1_Boudicca.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
[CvMiniDump_Player1_Boudicca.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14817810/CvMiniDump_Player1_Boudicca.zip)
[CvMiniDump_Player2_America.dmp](https://github.com/LoneGazebo/Community-Patch-DLL/files/14817813/CvMiniDump_Player2_America.dmp)

_8. Steps to reproduce the Issue (Optional)_
Player 1 plays as Boudicca, Player 2 plays as America. As soon as the button next turn is clicked, America crashes. This behavior is shown in Savefile 224 and 225.

If further Information is needed just comment please.
Thank you all for making CIV VP Multiplayer possible !

**Comment by axatin** [comment]
The UI bug is fixed. Unfortunately I can't load MP games with three or more players myself, so for further investigation I need the log files. Also, for the upcoming version 4.8 some other desyncs and crashes have been fixed, so I'll close this ticket. When you play the next MP game, make sure all players have logging enabled. When the first desync happens, please create a ticket and upload the log folders of all three players.
