### ISSUE TITLE
Ranged Unit skips turn when on the same tile as worker.

### ISSUE THREAD

**Issue by der1weihnachtsmann** [LoneGazebo/Community-Patch-DLL#10781]
_1. Mod Version (X.Y.Z). Current Version: 4.5.0_

4.5.1.

_2. DirectX Version_

_3. List of Other Mods_

4 UC
UCS
Extraction Outpost
Notifications Settings
Quick Turns
Squads
Upgrade All Units Button
Global Relations

_4. Describe the Issue_

Bazooka in picture skips turn while being on the same tile as a worker. Had the problem before with other ranged units.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0376 AD-1956.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14816045/AutoSave_0376.AD-1956.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14816043/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![WhatsApp Image 2024-03-31 at 15 40 06_2b2a84e6](https://github.com/LoneGazebo/Community-Patch-DLL/assets/130388865/878a78bb-f471-4731-8c98-8870b8f7bd40)

**Comment by azum4roll** [comment]
You started a new issue #10831, so I'll close this.
