### ISSUE TITLE
Combat calculator graphical representation of damage is wrong

### ISSUE THREAD

**Issue by SuperNoobCamper** [LoneGazebo/Community-Patch-DLL#10793]
_1. Mod Version (X.Y.Z). Current Version: 4.6_

4.6

_2. DirectX Version_

_3. List of Other Mods_

*(over) More Unique Components for VP (v 84)
*Better Lakes for Vox Populi (v 2.3)
*InGame Editor+ (v 46)
*Really Advanced Setup (v 15)

_4. Describe the Issue_

The combat calculator graphic visualisation is not showing appropriate graphical representation of the damage (the numbers are correct)
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Isabella_0212 AD-0580.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14860300/Isabella_0212.AD-0580.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![Screenshot (73)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/20557080/e2347d8d-8195-4d86-8db5-73e4b9970a1f)

**Comment by Hokath** [comment]
same
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/11889219/e2b3e24c-178e-4cd3-a8e9-ac9fe9a39809)

**Comment by axatin** [comment]
@Hokath see here: https://forums.civfanatics.com/threads/new-version-4-6-march-31-2024.688848/post-16588111

**Comment by azum4roll** [comment]
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/14953746/1600ea9c-9d59-47e8-9995-80af71d666fb)
It's not working for me btw

**Comment by axatin** [comment]
I tried again, cleared the cache myself and reinstalled VP using the installer, still can't reproduce it.

Please attach log files, maybe something can be found there.

**Comment by azum4roll** [comment]
Any specific video option you're using? I mean, yours is probably the only one working.

**Comment by psparky** [comment]
Looks like EnenyUnitPanel.xml and EnemyUnitPanel_small.xml are not synchronised, The latter is used for resolutions up to and including 1920x1080 or if Use Small Interface (or similar words) is ticked in the Options.

**Comment by azum4roll** [comment]
Small screen issue :(
