### ISSUE TITLE
Worker 2 turns remain tooltip error

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#10795]
4.6 
I've noticed that when a worker is "woken" by nearby enemies the number of turns to complete their improvement is off by 1.
The most obvious is when there is only 1 turns remaining: it says there are 2. If I click the button to re-order them to build, it completes immediately. Seems to be for roads and normal improvements both.

**Comment by Zuizgond** [comment]
For info I already reported it in last version https://github.com/LoneGazebo/Community-Patch-DLL/issues/10727
Number of turns to continue building a partially built improvement is off by 1 turn. Apparently it is more complicated to solve than it seems.

**Comment by axatin** [comment]
duplicate
