### ISSUE TITLE
Game crashes 1 round after entering Renaissance Era

### ISSUE THREAD

**Issue by ptoepfer12** [LoneGazebo/Community-Patch-DLL#10790]
_1. Mod Version (X.Y.Z). Current Version: 4.6_

_2. DirectX Version_

_3. List of Other Mods_
Amphibious Assault Mod Gods and Kings v3
Arecibo Observatory v2
Atlantean Civ v1 (This is the civ I am playing)
cistern and Marina v2
Combat Engineer v3
Combat Medic v3
Fortress Borders v2
Improved Air Recon v1
Improvement Upgrades v1
National Wonder Collection v3
Neolithic wonders v1
Pirate Civ v2 
Pontoon bridge for VP v2
Promotions Expansion Pack v9
Reforestation v9
remove ice v1
Resource Mint Include copper v2
RetroA Building Pack and tweaks v4
Special forces mod v4
Strategic Buildings pack v2
Units Scout to Explorer v10
VP's Bare Necessities v12

_4. Describe the Issue_
Game crashes 1 round after entering Renaissance Era

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[riz5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14852538/riz5.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_
[CvMiniDump.dmp](https://github.com/LoneGazebo/Community-Patch-DLL/files/14852560/CvMiniDump.dmp)

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
Too many mods here, not going to fix. The more mods are being used, the higher the chance of mod conflicts leading to crashes. Also you may want to check out this page with mods designed for use with VP, as many of the base game mods are incompatible with VP: https://forums.civfanatics.com/forums/mods-repository.549/
