### ISSUE TITLE
No diplomat in the vassal capital

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#10798]
_1. Mod Version (X.Y.Z). Current Version: 4.6_

_4. Describe the Issue_
Despite the in-game description, there is no diplomat in the capital of my vassals.

**Comment by bsesar** [comment]
Can you buy votes? Perhaps the "diplomat" in the vassal capital is not the same as a diplomat that can be assigned elsewhere.

**Comment by saamohod** [comment]
> Can you buy votes? Perhaps the "diplomat" in the vassal capital is not the same as a diplomat that can be assigned elsewhere.

yeah I can. I guess this is the reason

**Comment by saamohod** [comment]
![20240404170041_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/16341598/8b32bef9-f6cd-4d66-a3c1-f94125e2a7b0)

**Comment by bsesar** [comment]
Perhaps the "Diplomat" in "We have a Diplomat in their capital" message should be changed to something else to avoid the confusion (e.g., Trade Representative, Lobbyist)?

**Comment by saamohod** [comment]
> Perhaps the "Diplomat" in "We have a Diplomat in their capital" message should be changed to something else to avoid the confusion (e.g., Trade Representative, Lobbyist)?

I believe in one of the previous versions there was a visual indication of that diplomat in the capital.

**Comment by azum4roll** [comment]
Diplomats also allow intrigues and peeking into policy/tech trees, etc.

I guess this will require an espionage UI change too.

**Comment by axatin** [comment]
the "diplomat" has never been a real spy, just the bonuses of a diplomat were given. not easy to change because it's not just a UI issue: if we create an extra spy, we need to make sure it's automatically moved if the vassal's capital changes and it's deleted if the vassal is liberated or killed. new spies would also change accumulated spy points. and of course it must be impossible to move the spy manually somewhere else

**Comment by Vordikk** [comment]
Maybe it's possible to make spies not being able to become diplomats in that capital then
Now i'm curious if i'd get double diplomat bonus

**Comment by azum4roll** [comment]
Is it better to just change the wordings about vassals and make another icon to show it's vote trading and vote preferences only?
