### ISSUE TITLE
Indonesian UA and city connections

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1080]
Ilteroi, any reason the 'no unhappiness from isolation' code would cause Indonesian cities not to allow city connections?

**Comment by ilteroi** [comment]
not that i know of. i have indonesia in my current testgame though. will check

**Comment by ilteroi** [comment]
seems to work fine

![image](https://cloud.githubusercontent.com/assets/1358966/12223074/9963951a-b7cd-11e5-9a30-da26f988982d.png)

**Comment by LoneGazebo** [comment]
Cool. Closing.
