### ISSUE TITLE
Mid game CTD in any VP version after 4.2.7 

### ISSUE THREAD

**Issue by Punklife** [LoneGazebo/Community-Patch-DLL#10813]
_1. Mod Version (X.Y.Z). Current Version: 4.6_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

Good afternoon! For some reason in any VP version later than 4.2.7 my game crashes just passing the turn at some point in the mid game. When I disable spying the crash stops permanently in any version.  Any explanation? Thanks for your attention.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Hiawatha_0037 BC-1780.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14920555/Hiawatha_0037.BC-1780.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14920639/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.dmp](https://github.com/LoneGazebo/Community-Patch-DLL/files/14920641/CvMiniDump.dmp)

_8. Steps to reproduce the Issue (Optional)_

Just press enter.

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
This has nothing to do with spies.

@ilteroi commit 08c1f0c5: In `TacticalAI::dropSuperfluousUnit`, `iMaxUnitsToKeep` can become negative.

**Comment by axatin** [comment]
But there is another cause of crashes that is related to espionage: https://github.com/LoneGazebo/Community-Patch-DLL/issues/10836.

**Comment by Punklife** [comment]
> This has nothing to do with spies.
> 
> @ilteroi commit [08c1f0c](https://github.com/LoneGazebo/Community-Patch-DLL/commit/08c1f0c52b9e3cae0938687a7effb0551fca39c8): In `TacticalAI::dropSuperfluousUnit`, `iMaxUnitsToKeep` can become negative.

Excuse my ignorance but what does this do?

**Comment by axatin** [comment]
It's a part of the tactical AI, it makes sure the AI doesn't try to find the best tactical moves for too many units at the same time as calculations would take too long otherwise. An internal error there causes the game to crash. My comment was addressed to ilteroi, he will know best how to fix it.

**Comment by ilteroi** [comment]
it's fixed already
