### ISSUE TITLE
United Nations host elections keep happening every turn

### ISSUE THREAD

**Issue by Iexhu** [LoneGazebo/Community-Patch-DLL#10812]
_1. Mod Version (X.Y.Z). Current Version: 4.6_

running 4.6

_2. DirectX Version_

_3. List of Other Mods_

ZNW-Symbolic Ideology Tenets (v 1)
InfoAddict (v 22)
Quick Turns (v 10)
Ethnic Units (v 31)

_4. Describe the Issue_
 Each turn the election for UN host turns up, delaying all other voting issues with it. The game also crashed at end turn. The game has crashed before but i am playing a very large map and its late game. So i don't know if that is related but added the file.

[CvMiniDump.dmp](https://github.com/LoneGazebo/Community-Patch-DLL/files/14915927/CvMiniDump.dmp)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0390 AD-1970.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14915810/AutoSave_0390.AD-1970.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/14915832/Database.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/14915833/Lua.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/14915834/xml.log)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.dmp](https://github.com/LoneGazebo/Community-Patch-DLL/files/14915947/CvMiniDump.dmp)

_8. Steps to reproduce the Issue (Optional)_

Just end turn, election popup is active on start turn

_9. Screenshots of the Issue (Optional)_

**Comment by Punklife** [comment]
I experienced the same issue at the end of the game right after winning the United Nations race. Because of the CTD reported in #10813, spying is disabled. I didn't have CTD problems even using a map with 20 Civs and 8 CE on a small map. You can try playing without spying to see if at least the CTD stops.

**Comment by Iexhu** [comment]
Thanks for your response. Actually i have spy system disabled as well as events. Only thing i can note on CTD's is that it happens after long play sessions. Very often when i check info addict after saving and when i'm about to leave the game it crashes on clicking  on the info addict button, again this is after long play sessions.

**Comment by axatin** [comment]
The UN bug is fixed in 4.6.1
