### ISSUE TITLE
Can't recapture missionary from barbarians

### ISSUE THREAD

**Issue by reikken** [LoneGazebo/Community-Patch-DLL#10817]
VP 4.6
other mods: Music Changer

The missionary just dies instead of being returned.

[saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14948250/saves.zip)

**Comment by axatin** [comment]
Something got mixed up in the internal logic. The barbarians shouldn't be able to capture missionaries from others, not the other way around.

**Comment by azum4roll** [comment]
Barbarians are supposed to capture missionaries though.

**Comment by axatin** [comment]
> Barbarians are supposed to capture missionaries though.

The database says otherwise
![ovr](https://github.com/LoneGazebo/Community-Patch-DLL/assets/95587882/19a9402d-add5-434f-992e-b9727701f0aa)

**Comment by azum4roll** [comment]
That means they can't spawn missionaries.

**Comment by axatin** [comment]
It‘s also used for capturing.

**Comment by azum4roll** [comment]
In that case, the fix is removing UNITCLASS_MISSIONARY from that table. It wasn't there before 4.0.

**Comment by axatin** [comment]
> In that case, the fix is removing UNITCLASS_MISSIONARY from that table. It wasn't there before 4.0.

ok, removed it
