### ISSUE TITLE
Civilizations are still starting all next to each other while leaving half of the world completelly empty

### ISSUE THREAD

**Issue by radziu93** [LoneGazebo/Community-Patch-DLL#10819]
_1. Mod Version (X.Y.Z). Current Version: 4.6_

4.6

_2. DirectX Version_

DX 11

_3. List of Other Mods_

More Unique Components  for VP
More Wonders for VP
Less Warmongering for VP
Pontoon Bridges for VP

_4. Describe the Issue_

Civilizations are starting all next to each other while leaving half of the world completelly empty. I basically have 3 other capital within 10-15 tiles from my capital, and the nex ones are near theirs, etc. I saw this reported in earlier version, but it was also tagged as resolved for next release, and 4.6 was next release. As you can see from the minimap screenshot, only half of the continent has visible cities, and it's about 10 civs there I already found, while bigger part to the left is completelly uninhibited, excluding some city states further away.

It is also worth mentioning, that all those closest 3 neighbours, from all possible directions to settle, placed their second cities within that small space between our capitals, like it was predetermined they MUST settle near player.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[example.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14966931/example.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

(too big to insert here)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Start a game. I started with Arborea for VP Pangea, low level of water, 4ml years old, random start and abundant resources

_9. Screenshots of the Issue (Optional)_
![2024-04-13_11h35_47](https://github.com/LoneGazebo/Community-Patch-DLL/assets/50568007/d4bdc731-e12b-41d1-9ec9-8bc18495b4a9)

**Comment by radziu93** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14982089/Logs.zip)
Here are my logs

**Comment by azum4roll** [comment]
No map generation is found in the log file (presumably because you started the game again, which clears the log).

If you encounter this issue again, feel free to open another issue with logs before you start Civ5 again.
