### ISSUE TITLE
Great Artists begin giving only minimum Golden Age points at some point

### ISSUE THREAD

**Issue by Vordikk** [LoneGazebo/Community-Patch-DLL#10816]
_1. Mod Version (X.Y.Z). Current Version: 4.6_
Vox populy with EUI

_4. Describe the Issue_

Free Great Artists at some point not gains any bonus golden age points (granting only basic 200)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Oda Nobunaga_0309 AD-1878.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14945022/Oda.Nobunaga_0309.AD-1878.zip)

_8. Steps to reproduce the Issue (Optional)_
Spawn Great Artist (in example. do so via buying General since there's Japan)

_9. Screenshots of the Issue (Optional)_
![Civ 5 Tests](https://github.com/LoneGazebo/Community-Patch-DLL/assets/146865968/e92b14bd-320d-4d0c-945d-d74ee10ef7f8)

**Comment by Vordikk** [comment]
Would be nice if you catch CTD meanwhile, but i'm not reporting them anymore... seemingly will happen always in lategame, no matter what
However, CTD didn't happen after Germany have started a war.

**Comment by azum4roll** [comment]
But do you have sources of Golden Age Points at all?

**Comment by Vordikk** [comment]
That's the most unexpected question :D
Of course i had plenty. It's 300+ turn after all.

Previous correctly working GA gave smth like 6314 GAP, and following begin giving 200.

**Comment by azum4roll** [comment]
Some integer overflow happened?

aka you had too much tourism/GAP in the past 10 turns, that it looped into negative.

**Comment by Vordikk** [comment]
Yeah, i thought about that. Didn't happen in previous VP versions, however — once i got above 96000 GAP without problems from GA in superlate game.
Yesterday i've tried to check calculations in mod code, but haven't found, which file is related to this.

**Comment by azum4roll** [comment]
It's at CvUnit::getGAPBlast()

**Comment by Vordikk** [comment]
i still can't find it even tho seeked through all files so w/e

**Comment by axatin** [comment]
it's not an overflow issue. there are values stored in your save game which are completely implausible, and which must be caused by an error on creating/loading the save file, as there's no way they could have been produced regularly. (note to self: m_aiYieldPerReligion for city at 32,4)

did you save the game around turn 300? if so, do you still have a save game from earlier?

the memory overflows are likely caused by EUI.

**Comment by Vordikk** [comment]
Ah, so save-load related.

Yes, there are some: 264, 265, 295, 309
[Japan saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15137087/Japan.saves.zip)

**Comment by axatin** [comment]
Yes, as I thought, the save file from turn 295 is fine, the one from turn 309 is corrupt. I played from turn 295 to turn 309, and the issue didn't occur.

You have reported that your game crashes frequently. So I assume what happened here is that you had a crash and then reloaded from an auto save that was corrupt for some reason. Unfortunate, but it seems to be a one-off incident, nothing we can do there.

**Comment by Vordikk** [comment]
Uhum, probably that's the case, who knows.

Actually crashes become much less frequent with latest patches. Thank you for a nice job ;)
In example, last game i did was on smaller map with 4 players only. There it went way smoother and completed in 1 session without any issues. But in lategame on bigger map game may ran out of free memory and therefore crash. This is not related to my RAM, though. And turning off additionally displayed stuff (tiles info, trade routes, etc) naturally helps against crashing in lategame.
