### ISSUE TITLE
Crime function garrison or defense scaling issue?

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1082]
Ilteroi, could your change to garrisons cause a spike in the global average for defense need in cities? Only explanation I have for why crime is specifically inflating so much.

**Comment by ilteroi** [comment]
well if it affects everyone it shouldn't matter. beauty of the system.

there might have been situations where city strength was not updated correctly (but that should have lead to weaker cities). anyway, fixed now

**Comment by LoneGazebo** [comment]
Fixed with your latest merge? I've merged and pushed as 1-10b beta.

**Comment by ilteroi** [comment]
in my latest commit i rewrote part of the happiness code because i don't trust in const-casting. also the whole thing relied on the different contributions being computed in a defined order, which seemed brittle.

**Comment by LoneGazebo** [comment]
Cool.
