### ISSUE TITLE
Cannot switch the city tile back

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#10822]
_1. Mod Version (X.Y.Z). Current Version: 4.6.0_

_3. List of Other Mods_
Improved City View (v20)

_4. Describe the Issue_
The city tile of Medina is visible from Mecca and its ownership can be switched from there. Unfortunately, the tile cannot be switched back and as a result, the city tile resources are not counted in Medina. Actually, switching the ownership of *city* tiles should not even be permitted.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[cannot_revert_tile_ownership.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14971473/cannot_revert_tile_ownership.zip)

_8. Steps to reproduce the Issue (Optional)_
Go to Mecca city screen, switch the Medina city tile to Mecca's ownership, go to Medina's city screen and try to switch it back.
<img width="960" alt="tile_ownership" src="https://github.com/LoneGazebo/Community-Patch-DLL/assets/620131/0bf05950-1234-4482-b78d-8f00569e0ffc">

**Comment by azum4roll** [comment]
Huh, wasn't this fixed?

**Comment by axatin** [comment]
Apparently not. Fixed it now.
