### ISSUE TITLE
Automated workers and archeologists are weird

### ISSUE THREAD

**Issue by Vordikk** [LoneGazebo/Community-Patch-DLL#10827]
_1. Mod Version (X.Y.Z). Current Version: 4.6.1_

_4. Describe the Issue_

Sometimes automated workers not finishing upgrades and going chill in cities. In example, i had partially built Mine, then discovered Aluminum on that tile, and then worker has just went away without completing his project.

3 automated Archeologists went on same dig spot, and after one ofthem completed dig, others stayed there and chilled until i given them orders manually. Even re-ordering autodig didn't give them any sanity.

**Comment by Vordikk** [comment]
![Civ 5 Tests 2](https://github.com/LoneGazebo/Community-Patch-DLL/assets/146865968/464da25e-5b08-48f1-8442-1dea62b0e0bb)
Another example. 2 workers went chill in cty while there are some unrepaired tiles, including Luxury.

**Comment by Vordikk** [comment]
Later in the same game automated Archeologist went afk in city even tho he could've reach dig location in less than 1 turn. And counting what i wrote above, he was clearly not scared of on-going war but just blind.

**Comment by KungCheops** [comment]
Can you provide a save file?

**Comment by Vordikk** [comment]
Yes, but latest manual save of this game was done at turn 211. I'm not sure, how far it is from accessing to archeologists (unless it can be cheated to get them sooner)
[Wu Zetian_0211 AD-1505.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15097167/Wu.Zetian_0211.AD-1505.zip)

**Comment by cidk2000** [comment]
Workers are chilling a lot in a recent game Workers are leaving unimproved Uranium and in general not replacing tiles that have an improvement on them with a quarry some workers as from a previous issues dont finish thier improvement i had to delete the worker and assign another one manually to the task to get it done.

**Comment by nobubblegums** [comment]
I also noticed workers going bonkers when building routes after railroads. This happens when not automated too, the "route to" mission doesn't work properly when upgrading existing routes to railroads, the worker just gets stuck on the initial tile

**Comment by KungCheops** [comment]
The "workers leaving some tiles unimproved" issue should now be fixed.

**Comment by Vordikk** [comment]
Aight let's see

**Comment by KungCheops** [comment]
I think this should be closed

**Comment by Vordikk** [comment]
Yeah, i think so. Thank you guys for a work.
