### ISSUE TITLE
CTD on end turn 

### ISSUE THREAD

**Issue by DhuBleidd** [LoneGazebo/Community-Patch-DLL#10828]
_1. Mod Version 4.6.1 but was the same on 4.6.0

_2. DirectX Version 9

_3. List of Other Mods_
R.E.D Modpack
Calypsos Colored Religious Icons
Great Prophet Historical Names
Really Advanced Setup
Reforestation
Units wake up when upgradeable
Wonder race
UI - Improved City View (Vox Populi EUI)
4UC
Music Changer

_4. Describe the Issue_
CTD after I end turn 304 to go into turn 305. Happens when barbarians are doing their actions.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[AutoSave_0302 AD-1410.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14994175/AutoSave_0302.AD-1410.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14994186/logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/14994188/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_
End turn 304

**Comment by DhuBleidd** [comment]
I realised that I had a CTD on 4.5.1 that happened at the same exact turn 304 (also Epic speed - https://github.com/LoneGazebo/Community-Patch-DLL/issues/10704). Not sure if relevant or not - I tried clearing cache/restarting/verifying file integrity etc.

**Comment by axatin** [comment]
Can't reproduce the ctd. Do you also have a save from turn 304 directly before the crash?

**Comment by DhuBleidd** [comment]
Hi Axatin, thanks for having a look. I should have updated the post but 4.5.2 actually fixed the issue. I suspect it was the same as #10829

**Comment by axatin** [comment]
ok good
