### ISSUE TITLE
Feature Request: Ranged Units Use Their Fire Arrow Animation When Attacking Naval

### ISSUE THREAD

**Issue by usadefcon1** [LoneGazebo/Community-Patch-DLL#10824]
Feature Request: 
Ranged Units Use Their Fire Arrow Animation When Attacking Naval

Rational:
Purely for aesthetic purposes I think the animation that is used against cities would be cool to see against naval too.

**Comment by azum4roll** [comment]
Is that even possible?

**Comment by LessRekkless** [comment]
I don't think there's graphics code to differentiate between attacking naval units vs land units.  Only code for attacking cities vs units.

Almost guaranteed not possible for us.

**Comment by n-core** [comment]
It is impossible since there is no special unit action only to attack naval units. City attack has its own unique action.
This is something that the DLL is unable to modify. Please close this issue.

**Comment by usadefcon1** [comment]
😕
