### ISSUE TITLE
Consistent turn ~250 CTD across multiple games

### ISSUE THREAD

**Issue by Hesston4** [LoneGazebo/Community-Patch-DLL#10829]
_1. Mod Version (X.Y.Z). Current Version: 4.6.1_
4.6.1 CBP VP, 43-civ EUI 

_3. List of Other Mods_
Better Helicopters
Communitas Map
Contextual Unit Names
InfoAddict
Ingame Editor
Quick Turns
Resource - Mint Include Copper
Submarines Ignore Borders
Terrain - Pontoon Bridge
Units - No Futuristic Units
The single line of code making Special Forces go obsolete at Lasers was also manually removed from UnitChanges in the VP database change files as I've removed the XCOM squad from the game.

_4. Describe the Issue_
On turn 240 of my latest Korea game (and around the ~250 mark of my last three), the game CTD on the AI turn (currently on India's turn in this save). I've ran this exact mod/game setup before and I don't believe memory is the issue (I've made sure yield icons were disabled and also tried passing the turn in strategic view). If I had my saves from the prior games I would've included them too, but I do remember last game it seemed to occur when a capital was captured (not what's happening here I'm pretty sure).

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[pls dont crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15017517/pls.dont.crash.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15017499/Logs.zip)
I enabled these after my first run-in with the CTD and crashed again with them on after reloading the save, so I don't know if they'll be useful, but just in case.

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15017514/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_
Hit next turn and it should happen on India's turn.

**Comment by axatin** [comment]
An issue with the complete kills option, Samarkand had just been conquered. Fixed for the next version. 

>  but I do remember last game it seemed to occur when a capital was captured
that was probably the same bug
