### ISSUE TITLE
AI city has gold focus but isn't working any specialists

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1083]
![image](https://cloud.githubusercontent.com/assets/1358966/12223873/4d9becd4-b7e3-11e5-9968-dc754605a403.png)

gold focus, extreme unhappiness, no specialists ... something is wrong

**Comment by LoneGazebo** [comment]
That's odd, should be. Is a puppet? Also, is it possible that the graphic isn't updating in observer view?
G

**Comment by ilteroi** [comment]
not a puppet. also, the stats update each turn. i watched it for a bit, sometimes some specialist slots are worked, but it's not very consistent.

**Comment by LoneGazebo** [comment]
Interesting. We probably should put some logging info in the cvcitycitizens files to get more insight into the AI's valuation of specialists and tiles.

**Comment by phantommaxwell** [comment]
I have this game from long ago with such a problem.  Forget till now.

![2015-12-13_00002](https://cloud.githubusercontent.com/assets/11430209/12226016/8a535bd0-b7e3-11e5-9c0f-bd05bd65c50a.jpg)
![Uploading 2015-12-13_00003.jpg…]()

**Comment by phantommaxwell** [comment]
![2015-12-13_00003](https://cloud.githubusercontent.com/assets/11430209/12226020/94b95cfa-b7e3-11e5-9ca5-a129fac25e32.jpg)

**Comment by Kolaris8472** [comment]
By the way, shouldn't there be a gold icon under the city name if you're in Gold Focus? There's a hammer for Production Focus.

**Comment by LoneGazebo** [comment]
Worked on this a bit, so we'll see.
G
