### ISSUE TITLE
Game crashes when playing in the map scenario

### ISSUE THREAD

**Issue by dldev32** [LoneGazebo/Community-Patch-DLL#10839]
_1. Mod Version 4.6.2._

_2. DirectX Version 11_

_3. List of Other Mods_
Realistic Earth (v 2) (TSL)

_4. Describe the Issue_
The game crashes when starting a scenario in the map

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
No

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
[CvMiniDump.dmp](https://github.com/LoneGazebo/Community-Patch-DLL/files/15064066/CvMiniDump.dmp)

_8. Steps to reproduce the Issue (Optional)_
1) Install Community Patch
2) Install Realistic Earth (v2) (TSL)
3) Launch the game and enable these mods
4) Run the scenario on the map of the installed map mod

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
There are a lot of errors in that mod. Not a Community Patch bug.
![errors](https://github.com/LoneGazebo/Community-Patch-DLL/assets/95587882/49045c30-f372-4bf2-8bbd-c6fcf1ebc8f0)
