### ISSUE TITLE
Memory issues and CTD link and display problems possibily due to memory 

### ISSUE THREAD

**Issue by cidk2000** [LoneGazebo/Community-Patch-DLL#10848]
_1. Mod Version (X.Y.Z). Current Version: 4.7.1_

Vox Populi 4.7.1

_2. DirectX Version_

DX11 

_3. List of Other Mods_

None

_4. Describe the Issue_

extra CTDS including the usual science screen now a lot from city screen and not enough memory always late game 

small 6 players 12 city states communitas map (mostly set to random on settings)
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0367 AD-1947.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15138221/AutoSave_0367.AD-1947.zip)

selecting a city to add International space station show Out of Memory on other Buildings 

_6. Logs (ALWAYS ATTACH THESE IF PO

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15138225/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15138227/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

CTD can occur from science screen/city or attempting to load a menu screen to either save 

_9. Screenshots of the Issue (Optional)_
![error](https://github.com/LoneGazebo/Community-Patch-DLL/assets/106168061/4c05be87-1f97-4283-8230-bd604ea23e95) - from older game without logging
![new city](https://github.com/LoneGazebo/Community-Patch-DLL/assets/106168061/2d67a44b-b292-4a33-b03d-c827bea6d922) from older game but without extra items in the build queue
![wierd issue](https://github.com/LoneGazebo/Community-Patch-DLL/assets/106168061/5572ee56-1a90-4c11-9eb1-10817e609ed5) this is from the uploaded latest game before a ctd the recycling centre has been invested and tried to add the international space station to the queue but nothing displays - display error

**Comment by cidk2000** [comment]
additionally highlighting too many tooltips either too quickly or by reading too many can cause the Out of Memory Message on the city screen i didn't hang around on the city screen selecting and now Ive moved turn this has now happened at exactly the same place on both games prev game was on 4.6

**Comment by cidk2000** [comment]
Debugging the Minidump using Microsoft tools 
Below is an excerpt:
STACK_TEXT:  
00000000 00000000 heap_corruption!CivilizationV_DX11.exe+0x0


STACK_COMMAND:  ** Pseudo Context ** ManagedPseudo ** Value: ffffffff ** ; kb

SYMBOL_NAME:  heap_corruption!CivilizationV_DX11.exe

MODULE_NAME: heap_corruption

IMAGE_NAME:  heap_corruption

FAILURE_BUCKET_ID:  HEAP_CORRUPTION_c0000005_heap_corruption!CivilizationV_DX11.exe

OSPLATFORM_TYPE:  x86

OSNAME:  Windows 8

FAILURE_ID_HASH:  {cad8b1e0-94b6-1097-9c81-df67d77d66a5}

Followup:     MachineOwner

**Comment by axatin** [comment]
See here: https://forums.civfanatics.com/threads/new-version-4-7-1-april-25-2024.689478/post-16598238

**Comment by cidk2000** [comment]
i dont get early game crashes at all its always late game ive played about 5-6 games of the 4.6-4.7 and its always late game

**Comment by azum4roll** [comment]
I think there's a memory leak for the highlight function or something?

**Comment by cidk2000** [comment]
this may be extra information that may or may not be relevant but im playing the game past the win and the 2050 mark (i won by conquest) but im not getting any ctd related to that particular issue its when im playing at that particular time (perhaps when the game is most demanding) late game  with multiple ai,

still going into city screen to invest and build all buildings still no ctd i have noticed one or two wobbles in the buiilding queue often items are missing but pulling out the city screen quickly and waiting a moment or two (moving around the map/issue order) and returning to the city screen the building queue looks normal 

theres 49 cities on the screen and lots of automation im expecting a ctd but its very solid so far (small map communitas)

**Comment by cidk2000** [comment]
this occurs during play and I can reproduce it. I don't have this issue during vanilla its exactly when it comes to building Powerplants at alternative energy during a game, screenshots above

 @Nu-Illasera  - HW isnt an issue and the game is limited to 32-bit addressing as i have the latest AM5 Hardware and 6000 series graphics 

@RecursiveVision thats disappointing considering this affects VP specifically not the EXE in my opinion

**Comment by axatin** [comment]
@cidk2000 please test if the issues also exists in the non-EUI version

**Comment by cidk2000** [comment]
@axatin - will use non eui from the installer (ive just seen a new release so ill remove civ 5 from steam and reinstall and report back) 

@Nu-Illasera thanks but as i said Hardware isnt an issue here i far exceed the requirements and the base civ 5 game does not crash at all

But just for reference AMD 7900X 12 core, 64GB RAM, 6700xt 12GB Vram NVME 1TB samsung 980evo board is: Asrock 670E PG
Win 11 Pro 

Pagefile is set automatically currently allocated 4GB

**Comment by cidk2000** [comment]
@axatin issue is not present non-EUI version game played with no ctd i was in and out of the science screen city screens constantly

in fact i had no niggles at all with the game ZERO crashes.  The EUI version is really buggy in comparison

**Comment by azum4roll** [comment]
It's something called by CityView.lua, or CityView.lua itself being too memory inefficient.

**Comment by azum4roll** [comment]
`CvCity::GetPlotsBoostedByBuilding()` creates four new sets on every call, but never deletes them.

Neither is the `std::vector<int> aiPlotList` created in `CvLuaCity::lGetPlotsBoostedByBuilding()`.

**Comment by cidk2000** [comment]
just seen an issue on non eui dont know if its linked at all 
![w1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/106168061/c3b540ba-c573-48b6-9953-8ecc7cf0d66b)

im meant to be building a wind power plant at murmansk but its showing SS Engine 1,180.9 production a turn 7 turns 
the city yakutks is building it 
![buildw2](https://github.com/LoneGazebo/Community-Patch-DLL/assets/106168061/08e8948f-41b8-4e66-b718-2c9b3f961372)
[Catherine_0406 AD-1986.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15181459/Catherine_0406.AD-1986.zip)

uploaded another save 
log folder is too large to send breaking it up 
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15181480/Lua.zip) - contains all but below 
[BuilderTaskingYieldLog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15181482/BuilderTaskingYieldLog.zip)
