### ISSUE TITLE
GP List

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1085]
I noticed that you didn't have a GP List replacement for the Info Panel, in order to account for your Great Diplomat. It's not much, but for completion's sake [here](https://www.dropbox.com/s/o3h7ez49jmy3ov7/GPList.rar?dl=0) is the replacement you need if you'd like it, with all things related to the GD marked as --Gazebo CSD (I have my own Great People in there, but there are no adverse effects of having this when my mods are inactive). 

![Img](http://i.imgur.com/nXbmMVo.jpg)

You'll just need to add [this](http://pastebin.com/A6ENPH5G) in xml:

(not really an issue, but didn't know where else to get your attention).

**Comment by LoneGazebo** [comment]
Thanks!

**Comment by LoneGazebo** [comment]
Good news! I've got a solution to your GP problem. Since the DLL is hardcoded, I leaned into it and created 5 'dummy' GP slots that are free to use. All you need to do is assign your GP one of the following promotions as a free promotion;

ALTER TABLE UnitPromotions ADD 'GPExtra1' BOOLEAN DEFAULT 0;
ALTER TABLE UnitPromotions ADD 'GPExtra2' BOOLEAN DEFAULT 0;
ALTER TABLE UnitPromotions ADD 'GPExtra3' BOOLEAN DEFAULT 0;
ALTER TABLE UnitPromotions ADD 'GPExtra4' BOOLEAN DEFAULT 0;
ALTER TABLE UnitPromotions ADD 'GPExtra5' BOOLEAN DEFAULT 0;

These each have their own independent meters for faith and natural GP birth, and should work like other GPs. You'll still need the LUA in the cityview etc. to have them show up, but this should do the trick!

**Comment by JFDaly** [comment]
That's truly excellent news! This will make some people very happy.

**Comment by LoneGazebo** [comment]
Glad to hear it. Beta test inbound. Give it a go and report back if there are any oddities.
[(1) Community Patch (JFD Beta).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/88442/1.Community.Patch.JFD.Beta.zip)

**Comment by LoneGazebo** [comment]
If you want to assign the GPs a policy branch unlock, you can use the method already in the GP for this. Such as this:

INSERT INTO Policy_FaithPurchaseUnitClasses (PolicyType, UnitClassType)
SELECT 'POLICY_LIBERTY_FINISHER' , 'UNITCLASS_WRITER'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

**Comment by JFDaly** [comment]
Yea, I had my GP assigned to policies already. Their cost just never went up when purchased.

The only issue I've encountered is that when a GP with this promotion is spawned, it doesn't increase the threshold of the next one (e.g. Great Dignitary spawns at 100, the next threshold is still 100, not 200 like it should be). But it definitely works otherwise - and even for faith purchases it increased the cost of the next purchase for only that GP.

**Comment by LoneGazebo** [comment]
I'll take a look at the natural rate tomorrow, not sure why it is messing up. May switch it over to a unitinfo assignment (instead of a promotion) because of how the DLL handles classes, but we'll see.

G

**Comment by LoneGazebo** [comment]
Okay, yeah, switching to a simpler unitinfo model.

-- GP tabling - use this to define up to 5 GP types with indpendent meters (will not affect rates of other GPs)
-- GPs that you assign the same number to will affect each other, so make sure no other mods are using these!
ALTER TABLE Units ADD 'GPExtra' INTEGER DEFAULT 0;
-- Example: <GPExtra>1</GPExtra> in a unit's XML table will put all of its GPP into a unique meter and a faith buy track.


New version below. Should work, hopefully!

**Comment by LoneGazebo** [comment]
[(1) Community Patch (JFD Beta v2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/89161/1.Community.Patch.JFD.Beta.v2.zip)

**Comment by JFDaly** [comment]
Unfortunately not - when spawned, a Great Magistrate/Great Dignitary's next threshold remains at 100. The transfer to Units doesn't seem to have adversely affected it though - the 'not-affecting-Great-Engineers' still works.

**Comment by LoneGazebo** [comment]
That's really odd, the code is a mirror-image of what exists. Are you spawning them 'naturally?'
G

**Comment by JFDaly** [comment]
Yup, spawning from specialists. You can see what I mean below:
![image1(http://i.imgur.com/obuVR3o.jpg)
![image2](http://i.imgur.com/3WnUjsl.jpg)

**Comment by LoneGazebo** [comment]
Mind sending me your mod so I can test with the debugger?

**Comment by JFDaly** [comment]
[Sure thing](https://www.dropbox.com/s/ehn0q7hif0iuckj/JFD%27s%20Cities%20in%20Development%20%28v%2014%29.civ5mod?dl=0). Justs needs CP.

**Comment by LoneGazebo** [comment]
Got it fixed. Simple else statement overwriting my change. Should be working as intended in next version. Prost!

**Comment by JFDaly** [comment]
Great to hear
