### ISSUE TITLE
Units quircks

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#1086]
There is no info that guided missile is maintenance free (I recall it is free in fact).
There is no info about carrier interception value (50? 100?).
Planes' new range doesn't match their interception ranges (interc. range are greater).

**Comment by LoneGazebo** [comment]
It's not maintenance free (guided missile).

**Comment by LoneGazebo** [comment]
Plane ranges and interception seem to be the same - which ones?

**Comment by Finarvi** [comment]
All fighters have old interception range in tech tree (at least in my 12-18 version but I don't recall it being changed).

**Comment by LoneGazebo** [comment]
Where? In the help text?

**Comment by Finarvi** [comment]
When I click on promotion in civpedia.

**Comment by LoneGazebo** [comment]
Are you talking about 'air sweep' or whatever? Because that isn't their interception range, that's their view range.

G

**Comment by Finarvi** [comment]
Sorry, something was displaying incorrectly or I've mistaken air sweep with sight range. It's OK then, sorry once again.

**Comment by LoneGazebo** [comment]
No worries
