### ISSUE TITLE
City-State "Build Wonder" Quest Expiry Notification Error

### ISSUE THREAD

**Issue by ZetaLambdaNinja** [LoneGazebo/Community-Patch-DLL#10877]
_1. Mod Version (X.Y.Z). Current Version: 4.7.3_

Version 4.7.3

_2. DirectX Version_

_3. List of Other Mods_

pineappledan's 34uc (NOTE:  you may need to overwrite the MODINFO file with the one attached here.  This fixes a mod dependency issue that has not yet been resolved with the introduction of Squads.)

[(over) More Unique Components for VP (v 87).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15213584/over.More.Unique.Components.for.VP.v.87.zip)

_4. Describe the Issue_

When a city-state "Build a Wonder" quest expires due to time, rather than someone else building the wonder, the notification reads as though the quest vanished because another player built the wonder.
Suggestion:  perhaps the time limit should be removed from wonder-building quests?  They'll get built eventually, anyway, right?

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[BUG - QuestExpiryTempleofArtemis.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15213589/BUG.-.QuestExpiryTempleofArtemis.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[AI_Personality_Log_Arabia.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15213595/AI_Personality_Log_Arabia.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Open attached save, then advance the turn.  You will see the quest expiry notification appear.

_9. Screenshots of the Issue (Optional)_

**Comment by Vordikk** [comment]
Time limit was added on wonders exactly to avoid cases when nobody could build them (i.e. outdated) but quests was hanging forever.
