### ISSUE TITLE
Discipline Policy gives double culture

### ISSUE THREAD

**Issue by Tascani** [LoneGazebo/Community-Patch-DLL#1087]
Beta 1/10b:

Discipline gives +6 culture (happiness is correct) when there is a unit stationed in the city.
This does not happen in all of my cities (4) but two of them where one is the capital and one is not.
I founded the city with a settler (playing Spain).

I can move out the unit (lose the +6 culture) and when the unit is put back to the city I regain +6 culture.

**Comment by ilteroi** [comment]
now that's ironic. first no culture at all and now this

**Comment by Tascani** [comment]
Okay. All cities are affected but in different way.
The amount created by Discipline is always 6.

Sometimes you have -3 / +3 and sometimes 0 and +6.

**Comment by LoneGazebo** [comment]
@ilteroi check the cvplayer for culture from policies. There's a spot in it that might've been missed.
