### ISSUE TITLE
Question about UnitPromotions_CivilianUnitType

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#10881]
I'd like adopting a policy to give great merchants a promotion.
I saw PROMOTION_FAST(ER)_GENERAL seems to accomplish this for great generals (and admirals) by combining 
Policy_FreePromotions with UnitPromotions_CivilianUnitType
But I cannot get this to work for the merchant. Am I missing something or does the merchant not like one of these tables?

Currently I am giving it the promotion with lua (the promotion works fine), I also tested that a straight up Unit_FreePromotion would give it, and it also works fine.

Does anyone know what I should do or is this a feature request?

**Comment by azum4roll** [comment]
There's no additional check. It should just work.

**Comment by Hokath** [comment]
Hmm ok. I checked everything had updated in the database and didn't have any logging errors. Tried a good few times, but will try again this evening.

**Comment by Hokath** [comment]
Seems to be working now.
Not sure what changed since I just uncommented-out some lines :S
Thanks for looking.
