### ISSUE TITLE
Feature Request/Change: Building_ResourcePlotsToPlace

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#10897]
It is found generally that the Building_ResourcePlotsToPlace very often fails to place resources at all. This is likely because the conditions on the table are overly strict.

Here is an example of a lua function Jarcast has written for his mod that has behaviour more in line with what is anticipated.

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/11889219/005d667a-18c7-4171-b575-bf633e712a67)

Please could we have this functionality for the DLL table so we can avoid lua usage?
(this may also be relevant to 4UC integration)
I don't believe table is used in the base VP.

**Comment by azum4roll** [comment]
That'll make the table(s) very complex.

Table: Resource_PlacementRequirements

Columns: ResourceType, PlotType, TerrainType, FeatureType, MustHaveFreshWater, MustNotHaveFreshWater, MustBeCoastal, MustNotBeCoastal, MustBeTropical

This will be a headache...

**Comment by Hokath** [comment]
Presumably the current method is even more complicated though? Do you know where it is?

**Comment by azum4roll** [comment]
CvPlot::canHaveResource()

It's way too simple.

**Comment by Hokath** [comment]
And the FeatureTerrainBoolean, this is what terrains it will allow the feature in FeatureBoolean to be on?

**Comment by azum4roll** [comment]
Yes

**Comment by Hokath** [comment]
@azum4roll 
So I understood this discussion to mean that if, for example, RESOURCE_COPPER has TERRAIN_HILL in Resource_TerrainBooleans, then Building_ResourcePlotsToPlace would put it there.

Yet, here is the result of giving myself copper using that table a dozen times
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/11889219/b8bba05d-f076-47f4-90c6-9d53a890e1ff)
It avoids the hill tiles (there are no hidden resources there)

Any ideas?

**Comment by Hokath** [comment]
Ooooh this is fun.
So now I changed the dummy to give me Amber instead -- it already spawns on hills.
Now I get Amber ONLY spawn on hills, none of the flatland.

Can it be that it is checking for either Hill OR Grassland OR Plains etc. etc. and it goes with the first one? I.e. it doesn't consider plains/desert/tundra/grassland/snow Hills, but just *hills* as a type. 
In one table hills is above the others in the load order and this is why?

**Comment by azum4roll** [comment]
Hills is not a terrain. Use the Hills and Flatlands columns.

**Comment by Hokath** [comment]
Aha I get it. So in the Resource table itself. Amber is hills and no flatland.
So the Resource_TerrainBooleans for TERRAIN_HILLS is just to populate the civopedia, it has no actual effect.

I should have worked that out, sorry. Combat promotions kinda work this way too don't they.

**Comment by Hokath** [comment]
@azum4roll 

Just to confirm,
UPDATE Resources SET Hills = 1 WHERE Type = 'RESOURCE_COPPER';
will have no affect on map gen?

**Comment by Hokath** [comment]
Dear diary, today I tried to use this table again and it continues to be ineffable.
I managed to get totally unreproducible placements in a handful of Cities (most didn't work at all) when trying to get things to spawn on hills and flatland.

**Comment by Hokath** [comment]
Hello friends.
We learnt today from c69manifold's hard work that the reason some custom resources dont spawn is because you must set MaxLatitude for the resource. If you let it default to 0, it will fail the placement check every time.
Hurray! Case closed.
