### ISSUE TITLE
Towns/Villages and roads/trade routes

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1089]
From Funak:

http://forums.civfanatics.com/showpost.php?p=14121656&postcount=4269

Trade Routes should give the same gold bonus as a road (and vice-versa), but it seems that only roads are getting the bonus right now.

**Comment by ilteroi** [comment]
just checked the code, it's a bit redundant, not to say inefficient. also it seems there is some confusion between a plot being a route (road or railroad) and a plot being a traderoute (caravan passes here). but no obvious problems. needs further analysis

				CvGameTrade* pTrade = GC.getGame().GetGameTrade();
				bool bTrade = false;
				for (uint uiConnection = 0; uiConnection < pTrade->GetNumTradeConnections(); uiConnection++)
				{
					const TradeConnection* pConnection = &(pTrade->GetTradeConnection(uiConnection));
					if (pTrade->IsTradeRouteIndexEmpty(uiConnection))
					{
						continue;
					}
					for (uint ui = 0; ui < pConnection->m_aPlotList.size(); ui++)
					{
						if (pConnection->m_aPlotList[ui].m_iX == getX() && pConnection->m_aPlotList[ui].m_iY == getY())
						{
							bTrade = true;
							break;
						}
					}
				}
				if(IsTradeRoute(ePlayer))
				{
					if(IsRouteRailroad())
					{
						iYield += GC.getImprovementInfo(eImprovement)->GetRouteYieldChanges(ROUTE_RAILROAD, eYield);
					}
					else if(IsRouteRoad())
					{
						iYield += GC.getImprovementInfo(eImprovement)->GetRouteYieldChanges(ROUTE_ROAD, eYield);
					}
				}
				if(bTrade)
				{
					if(IsRouteRailroad())
					{
						iYield += GC.getImprovementInfo(eImprovement)->GetRouteYieldChanges(ROUTE_RAILROAD, eYield);
					}
					else if(IsRouteRoad())
					{
						iYield += GC.getImprovementInfo(eImprovement)->GetRouteYieldChanges(ROUTE_ROAD, eYield);
					}
				}

**Comment by LoneGazebo** [comment]
We could probably store plot values for 'trade route passing here' and then use that. Set it when trade routes are created/destroyed?

**Comment by LoneGazebo** [comment]
I'm going to do this. (the plot element)
G

**Comment by ilteroi** [comment]
ah, this caching is already implemented in the form of IsTradeRoute(ePlayer)! 

hope you didn't duplicate it

**Comment by LoneGazebo** [comment]
Is TradeRoute is for city connections, though, right?
G
