### ISSUE TITLE
What, if anything, does SpecialistProductionModifier do?

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#10895]
This policy field was thought to give 1% production per worked specialist. Testing, it doesn't seem to do anything at all.
I browsed the DLL but couldn't really find where it actually gets used. Is it dead?

**Comment by azum4roll** [comment]
It modifies the production when producing a specialist (??????). Probably left over from older games?

**Comment by Hokath** [comment]
Funky.
I guess can be removed then.
