### ISSUE TITLE
AI can't/won't expand

### ISSUE THREAD

**Issue by ircy** [LoneGazebo/Community-Patch-DLL#109]
Currently in a game with sweden as my neighbor. On epic speed, turn 107, they are beelining the military techs, bottom side, but have not gotten pottery, therefore, they can't expand. is this intentional? All the other 6 civs have gotten pottery and are expanding correctly. I apologize if this is too long.

**Comment by LoneGazebo** [comment]
It happens sometimes – I need to rewrite some of the tech flavors for the mod, as the shifts in unit/building locations haven't been followed up by a flavor update.

G

**Comment by wileyhk2001** [comment]
I have the same problem, particularly on epic speed.
