### ISSUE TITLE
On Diffcult Target 

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#1090]
![2016-01-12_00006](https://cloud.githubusercontent.com/assets/11430209/12277872/e5632906-b94b-11e5-8dcd-3715acc77f93.jpg)

![2016-01-12_00007](https://cloud.githubusercontent.com/assets/11430209/12277873/e57ef58c-b94b-11e5-8d48-3dcdae90680c.jpg)

**Comment by phantommaxwell** [comment]
The Promotion says 50% and was never updated.

**Comment by GrantSP** [comment]
Is it still there when the target is not in range?
