### ISSUE TITLE
LUA religion error with GetReligionCreatedByPlayer()

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#10907]
If you look at this code
`
if(not pPlayer:IsMinorCiv() and pPlayer:IsEverAlive() and pPlayer:HasCreatedReligion()) then
	local iPlayer = pPlayer:GetID();
	local eReligion = pPlayer:GetReligionCreatedByPlayer();
	print("eReligion and Religion")
	print(pPlayer:GetNameKey())
	print(eReligion)
`
It seems like if you get past the if statement of pPlayer:HasCreatedReligion(), then you would populate eReligion?
Not so. I took the Holy City of Sweden as Ottomans. The lua log prints my name, but the eReligion is -1.

This causes mod incompatibilities.

**Comment by Hokath** [comment]
#3302 Seems the Samsara still has us. Will use Gazebo's function :)

**Comment by Hokath** [comment]
Dear diary,
My next step was this
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/11889219/2da429b1-cb54-4ffe-b01a-87d38f3ddf46)
assuming the player has moved the religion to their capital for now.
pOGPlayer correctly returns sweden
however eReligion is still -1...

**Comment by Hokath** [comment]
So in conclusion if you take someone else's holy city without having founded a religion:
pPlayer:HasCreatedReligion() will work for you (correctly)
pPlayer:GetReligionCreatedByPlayer() will not work for you (bad)
pPlayer:GetReligionCreatedByPlayer() will also not work for the person you took the religion off (correctly)
pPlayer:GetOriginalReligionCreatedByPlayer() will work for the person you took the religion off (correctly)

Please could someone with the DLL skills look into what is going on here? Ty

**Comment by axatin** [comment]
I'd say HasCreatedReligion should not return true if a holy city was only conquered. You can use `GetOwnedReligion` to check if a player controls a holy city (returns -1 if not).

The inconsistency needs to be fixed of course.
