### ISSUE TITLE
CP ONLY Building Settlers causes city to starve

### ISSUE THREAD

**Issue by Tesla101a** [LoneGazebo/Community-Patch-DLL#10906]
_1. Mod Version (X.Y.Z). Current Version: 4.7.3_

4.7.3

_2. DirectX Version_

_3. List of Other Mods_

None

_4. Describe the Issue_

I found in patch notes for 4.6 that a bug was fixed in vox populi so that your city would properly starve while building settlers if enough food wasn't produced.  Seems it leaked into the Community Patch.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/15335913/logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Build a settler and just work hills

_9. Screenshots of the Issue (Optional)_
![Untitled](https://github.com/LoneGazebo/Community-Patch-DLL/assets/15092772/b30034ee-98cc-4bff-850f-4fee3172920f)

**Comment by axatin** [comment]
That‘s intentional, it was a bug also in vanilla that cities couldn‘t starve when building a settler. It was only intended that they couldn‘t grow.
