### ISSUE TITLE
Monuments don't get cheaper with Tech

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#1091]
![2016-01-12_00002](https://cloud.githubusercontent.com/assets/11430209/12277957/4ceb72d6-b94c-11e5-9e10-aa16764aa6c6.jpg)
![2016-01-12_00001](https://cloud.githubusercontent.com/assets/11430209/12277958/4ceef5d2-b94c-11e5-9847-80feaae3ca42.jpg)

**Comment by phantommaxwell** [comment]
It's only 2 Hammers now.

**Comment by LoneGazebo** [comment]
Monuments don't have an era assigned IIRC, therefore they don't cheapen.
