### ISSUE TITLE
National Wonders question

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1093]
I was doing the NWs for the Wikia, and only about half of the tooltips say they increase in cost per city. I thought this was true of all NWs. I admit, I'm not the best at remembering hammer cost from one game to the next tho, so maybe not. If they do all, I can make a list of the ones that don't include that sentence if you want. Last time I posted one of these somebody did something called a 'commit,' ..I'm not really sure what that is, but if its something I can do myself I could try to figure it out.

Oh, if it is all, does that include the Founder Belief wonders as well or all they exempt somehow.

Finally, is the their a number of cities owned where the cost stops rising?

**Comment by LoneGazebo** [comment]
Yeah, all should. Let me know which don't and I'll fix. No the cost always rises.

G

**Comment by pandasnail** [comment]
Okay. The ones that don't:

Heroic Epic
Scrivener's Office
School of Philosophy
Circus Maximus
East India
Grand Temple
Ironworks
Oxford University
Hermitage
National Intelligence Agency
National Visitor Center

MoMA and Grand Cothon don't say it either, those could be exceptions I guess.

All nine religious wonders don't have it. I don't know an easy way to look at the tooltips for those, so this is just from the civpedia Game Info, but it seems like they both come from the same source.

Finally, related: The Diplomacy and Ideology National Wonders are in the Building section of the civpedia instead of the National Wonder section ie:

Scrivener's Office
Printing Press
Foreign Bureau
Hall of Honor
Palace of Culture and Science
International Finance Center

Sorry to put so much all at once!

**Comment by LoneGazebo** [comment]
Latter is because they have specialists. Are you using EUI or no-EUI version?
G

**Comment by pandasnail** [comment]
EUI version
