### ISSUE TITLE
Can't buy nearby tiles

### ISSUE THREAD

**Issue by Nigel--C** [LoneGazebo/Community-Patch-DLL#1094]
Using beta 1/10b with EUI. Only non-CPP mod active is my own which modifies "TECH_COST_TOTAL_KNOWN_TEAM_MODIFIER".
Playing as Carthage on a standard size Communitas map, quick speed, Prince difficulty.
In some of my cities, I cannot purchase nearby tiles even though they are within working range and adjacent to already-owned tiles. See attachment for an example.
![civ5bug](https://cloud.githubusercontent.com/assets/8080565/12284752/8b088346-ba06-11e5-9c7c-37ddf91a871d.PNG)

**Comment by LoneGazebo** [comment]
If you quit, clear cache, and then reload, does it work? Also, EUI/No-EUI?

G

**Comment by Nigel--C** [comment]
Clearing the cache and reloading didn't resolve it.
I removed EUI (and changed compatibility files accordingly), cleared cache and ModUserData but the problem is still there. 

Savegame and logs attached.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/88448/Logs.zip)

[Dido_0187 AD-1810.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/88447/Dido_0187.AD-1810.zip)

**Comment by ilteroi** [comment]
closing this as duplicate
