### ISSUE TITLE
Pathfinding issues

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1095]
I know this has been around and reported in the past, just want to clarify that it's still present to some degree in the current build.

![2016-01-12_00001](https://cloud.githubusercontent.com/assets/11132095/12285204/483256ca-b97d-11e5-9a2f-667c5528f252.jpg)

You can see that my gatling gun should be able to move to the selected spot, but unless I manually move each tile it's going to take a suboptimal path and use 2 turns.

**Comment by ilteroi** [comment]
any chance this was on the dateline? (i.e. the place where the map wraps around). just fixed a bug there.

otherwise, savegame please

**Comment by LoneGazebo** [comment]
Is it possible that the issue is still tied to being able to pass through cities? The 'faster route (moving SW, W, NW, NW) takes you through a garrisoned city.

**Comment by LoneGazebo** [comment]
Or perhaps the fact that you can't 'stop' on the rifleman or artillery tiles?

**Comment by ilteroi** [comment]
it's his own city. friendly units only count if you need to end the turn on their plot. 

the blue line shows the movement range correctly ... need to check in detail

**Comment by LoneGazebo** [comment]
Ideally, yes (friendly units/cities not counting), but that's where I thought the bug might be. :)

G

**Comment by joosegoose** [comment]
You're correct, my dateline was (thankfully) nothing but ocean.

I don't have a savegame for that exact instance, but I'll upload one the next time it happens. It's happened a few times, shouldn't take too long once I start playing.

**Comment by joosegoose** [comment]
Naval pathfinding this time, and a savegame to accompany. Running full CPP.

![2016-01-13_00004](https://cloud.githubusercontent.com/assets/11132095/12315116/4622cb74-ba3d-11e5-9f21-7f7cf414b48c.jpg)

[Test Cruiser Pathfinding.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/89826/Test.Cruiser.Pathfinding.zip)

Actually, as I'm posting this I'm realizing it might be related to the dateline issue. But here it is anyways.

**Comment by ilteroi** [comment]
yup, that's the dateline - already fixed
