### ISSUE TITLE
Midpoint of map hijinks

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1096]
![2016-01-13_00002](https://cloud.githubusercontent.com/assets/11132095/12288805/0e81bffe-b99d-11e5-9f8c-16549a5af8cb.jpg)

My bombard range is mysteriously cut off here. My guess is it has something to do with the center of the map--when first exploring I noticed the fog of war tended to form a straight line down the middle here until I busted it all up.

Sorry that this probably isn't very helpful, let me know if I can give any more details.

**Comment by Nigel--C** [comment]
I think my issue (#1094) is related to this - the tiles I cannot purchase are on the other side of the map's midpoint.

**Comment by ilteroi** [comment]
yeah it seems my new plotDistance() suffers from a different but similar problem as the old one. guess that makes me a moron too ;)

**Comment by ilteroi** [comment]
pushed. closing this
