### ISSUE TITLE
Blank leader screen

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1097]
![2016-01-13_00001](https://cloud.githubusercontent.com/assets/11132095/12288901/b0bcf50e-b99d-11e5-8461-0994783ff08f.jpg)

This is really about all I have. At some point while playing this screen came up and I took a screenshot as I always do with CPP bugs :D

Unfortunately I don't have any more info, I wasn't able to guess the context or what may have triggered it. I can try to go back and find an autosave with it if that would be useful.

**Comment by LoneGazebo** [comment]
If you have logging enabled, post your DiplomacyAI_Messages.log. What turn was this?

G

**Comment by joosegoose** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/89453/Logs.zip)

Here's my logs folder, I don't see any file with that name though. Would it be in a different location?

**Comment by LoneGazebo** [comment]
You don't have AI logging enabled, so it won't make that file. Oh well. You might enable that (in configini) for future.
G

**Comment by joosegoose** [comment]
I had ValidateGameDatabase = 1, LoggingEnabled = 1, and AILog=1

Is there something else I'm supposed to be changing?

**Comment by LoneGazebo** [comment]
; Enable message logging
MessageLog = 1
