### ISSUE TITLE
EUI not installing in Installer

### ISSUE THREAD

**Issue by PyraDrake** [LoneGazebo/Community-Patch-DLL#10986]
Mod Version 4.8.1

When I'm using the installer, it's not installing the EUI version that should be installed with VP. I've tried using both regular and 43-civ install options and haven't gotten the (3) mod for EUI, jus 1, 2, 3a, 3b, and 4a.

**Comment by KungCheops** [comment]
Isn't 3a the EUI compatibility files?

**Comment by PyraDrake** [comment]
Yes, but I'm not getting the actual EUI mod.

**Comment by Hokath** [comment]
There is no (3) mod afaik. EUI files go in the Steam/.../DLC type location instead of the MODS/ one.

**Comment by PyraDrake** [comment]
Fair enough, it is there. Thanks.
