### ISSUE TITLE
Third Alternative resource bonus. Just a question.

### ISSUE THREAD

**Issue by Punklife** [LoneGazebo/Community-Patch-DLL#10989]
_1. Mod Version (X.Y.Z). Current Version: 4.8.1_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_
 Is there a way to reduce Autocracy Third Alternative policy resource bonus by 50% inserting something in this script?

"-- Third Alternative
DELETE FROM Policy_CapitalYieldChanges
WHERE PolicyType = 'POLICY_THIRD_ALTERNATIVE';

UPDATE Policies
SET UnitGoldMaintenanceMod = -25
WHERE Type = 'POLICY_THIRD_ALTERNATIVE';"

Thanks!
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by azum4roll** [comment]
Update the StrategicResourceMod column to 150 instead of 200.

**Comment by Punklife** [comment]
> Update the StrategicResourceMod column to 150 instead of 200.

In CoreTableEntries.sql?

**Comment by Hokath** [comment]
Just giving it a quick read but should it actually be set the 100 to 50?
(in CoreTableEntries.sql, yes. Bit weird but at some point the table must have changed in the DLL so here it is)

**Comment by Punklife** [comment]
> Just giving it a quick read but should it actually be set the 100 to 50? (in CoreTableEntries.sql, yes. Bit weird but at some point the table must have changed in the DLL so here it is)

It does not work. I had already tried changing it in CoreTableEntries.sql and Autocracy.sql, but it just didn't work. Maybe I did something wrong.

**Comment by axatin** [comment]
> Just giving it a quick read but should it actually be set the 100 to 50? (in CoreTableEntries.sql, yes. Bit weird but at some point the table must have changed in the DLL so here it is)

Yes, it must be changed from 100 to 50.
We redefined it in the DLL to make it consistent with the other modifiers, and to make it possible to have multiple bonuses that stack.

@Punklife Did you start a new game when you tested it? The change doesn‘t apply to existing save games

**Comment by Punklife** [comment]
> > Just giving it a quick read but should it actually be set the 100 to 50? (in CoreTableEntries.sql, yes. Bit weird but at some point the table must have changed in the DLL so here it is)
> 
> Yes, it must be changed from 100 to 50. We redefined it in the DLL to make it consistent with the other modifiers, and to make it possible to have multiple bonuses that stack.
> 
> @Punklife Did you start a new game when you tested it? The change doesn‘t apply to existing save games

No. Since the other changes I made work even in saved games, I didn't start a new game. I will try this. Thanks!

**Comment by Punklife** [comment]
@axatin Excuse my ignorance, but how do I know that the change has taken effect in a new game?

**Comment by Hokath** [comment]
If you have IGE enabled you could give yourself the tenet temporarily

**Comment by Punklife** [comment]
> If you have IGE enabled you could give yourself the tenet temporarily

Thank you for the tip! It worked.
"UPDATE Policies SET StrategicResourceMod = 50 WHERE StrategicResourceMod == 200;"

**Comment by Punklife** [comment]
@axatin @Hokath Obs: It works on saved games but it does not change de policy text, just the top panel tooltip text.

**Comment by Punklife** [comment]
> Correct. To change the text you would have to go to MODS(2) Vox Populi\Database Changes\Text\en_US\Policies\PolicyTextChanges.sql and find it there

Thank you again! It worked.

"UPDATE Language_en_US
SET Text = '[COLOR_POSITIVE_TEXT]Third Alternative[ENDCOLOR]: Quantity of Strategic Resources produced is increased by 50%. Reduces Unit [ICON_GOLD] Gold Maintenance costs by 25%.'
WHERE Tag = 'TXT_KEY_POLICY_THIRD_ALTERNATIVE_HELP';"
