### ISSUE TITLE
CS building too many work boats

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1099]
I see (at least) two CS who have a small flotilla of 3-6 work boats idling around. 
It only happend in later ages, modern upwards.
It might have to do with them both having oil in their sea, but not jet the tech to improve it. But what do I know. 
If required, I can provide srceenshots later.

**Comment by LoneGazebo** [comment]
This can happen sometimes with the RNG model of the unit production. Rare, but unfortunate.
