### ISSUE TITLE
Bonus from belief - "Mastery" - is hidden

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#110]
When you get "Mastery" belief (+1 yield from specialists) you get bonus gold/prod/science but it isn't shown when you assign citizen to specialist slot.

**Comment by LoneGazebo** [comment]
Can you elaborate? I see the change in the cityview screen, so I'm not sure where the problem occurs.

**Comment by Finarvi** [comment]
Sorry, it seems that it has been once-off bug. After reloading everything
is displaying correctly. If there will be more issues with that I will
check it and report.
Regards.

2015-02-02 17:24 GMT+01:00 LoneGazebo <notifications@github.com>:
