### ISSUE TITLE
Multiplayer_VP4.9 with EUI

### ISSUE THREAD

**Issue by Cyclopia31** [LoneGazebo/Community-Patch-DLL#11003]
_1. Mod Version (X.Y.Z). Current Version: 4.9.0_
VP 4.9.0 with EUI in a modpack: https://drive.google.com/file/d/1gZAzOwFv1TuMZh7DwlSPtmfODZ6w89Xx/view?usp=sharing

_2. DirectX Version_
11

_3. List of Other Mods_
None

_4. Describe the Issue_
This is the same game than the one I reported there: https://github.com/LoneGazebo/Community-Patch-DLL/issues/10997, I have continued it by loading the last save.

The game behavior was fine until I attend the Indistrial era. Then I got a lot of desync messages in the chat, expecially for the non-host player. The game ended up by crashing for non-host player during/just after the AI turn between turn 256 & 257. 

I have loaded again the turn 256 without clearing the cache but the game can be continued normally. 
I can repeat a desync between turn 256 & 257. For that you have to skip turn on all unit, take random promotion, refuse the diamond renewal proposed by Portugal for host player. For non-host player you can do the same with units, build a frigate with the capital, accept the firendship with Byzantine AI, send the cargoship to a host city (Mongol)
The desync is : 
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/80354202/d6348a52-301e-4271-b335-6fcb46c02721)

I hope it can help !

_5. Data_
Saves/logs/cache: https://drive.google.com/file/d/1tYop8Z2yzmrrfTXmI12Pqpi_CLh0gNrh/view?usp=sharing

**Comment by axatin** [comment]
A result of the desyncs from before. Good to know, I thought loading a saved game would re-sync all players with the host, so previous desyncs would not be carried over, but apparently that's not the case.

**Comment by Cyclopia31** [comment]
Hum good to know, and that is sad, it makes multiplayer debugging harder and the multiplayer itself less stable...
