### ISSUE TITLE
4.9 Great Cothon grants free harbors to inland cities

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#11004]
Most harbor abilities are wasted but not the +2 army supply, and with the Cothon that's 3 free production still.

![civbugharbor](https://github.com/LoneGazebo/Community-Patch-DLL/assets/53142313/4b51e95b-664f-4eff-bcf4-e4ca0b1c1ee2)

**Comment by Piotr-Wieczorek** [comment]
This city also doesn't have a river which makes it even weirder. I've never tested this-> Do cities become coastal after connecting via a canal to the shore? -> Maybe this could make this behaviour reasonable.

**Comment by Vordikk** [comment]
Cities not becomes coastal in original VP, but there was some mod which was making cities coastal if they're only 1 tile away from shore and it's connected with via smth.
