### ISSUE TITLE
Fort + Citadel + Fort Does not create 3 tile channel

### ISSUE THREAD

**Issue by MathiasBotoft** [LoneGazebo/Community-Patch-DLL#11028]
_1. Mod Version 4.9.1_
EUR, 43 Civ version

_3. List of Other Mods_
4 UC

_4. Describe the Issue_
I being able to create 2 or 3 tile channels across land through forts and citadels in version 3.7.11
I am playing a game on the current version as America and Inland citadels does not allow for naval units passage.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
File from when the citadels are placed, have been using fishing boats to test from all angles.
(NavalChannelIssue.zip](https://github.com/user-attachments/files/15938355/NavalChannelIssue.zip)

**Comment by Hokath** [comment]
I believe this is intended. Can't tell you when it happened but a fort/citadel that doesn't touch coast cannot function as a canal.

**Comment by MathiasBotoft** [comment]
Damn. I quite like build the massive channels
It is like figuring out where the Suez of each game can be.

**Comment by azum4roll** [comment]
You've never been able to do that.
