### ISSUE TITLE
Tactical AI issues

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1103]
AI subroutines to decide whether an attack or a move is more valid (major)
Tactical map awareness re: air units (major)
Clean-up of redundancies in operational code (minor)
Explorer plot evaluation rework (minor)
AI offensive/defensive operation optimization (minor)

**Comment by LoneGazebo** [comment]
Also, adding to this, sometimes it seems that the Center of Mass for tactical operations causes the operation to move in the opposite direction of the final target (i.e. the CoM seems to be 'pulling' the operation backwards, instead of dragging it forwards).

**Comment by ilteroi** [comment]
other issues:
- respect UNITAI_CLASS in tactical AI also (right now considers only ranged vs melee)
- rewrite formation moves (invert logic, find best plot for unit and not best unit for plot)

**Comment by Kolaris8472** [comment]
AI used 3 Guided Missiles to take down an embarked Machine Gun. Not a good use of resources.

**Comment by LoneGazebo** [comment]
I added some parthian logic to the tactical AI, ilteroi, but I don't think it is helping. Mind taking a look at some point? It's 'ParthianMoves' in the tacticalAI.

**Comment by ilteroi** [comment]
i did see some hit and run tactics from barbarian horsemen. so in fact i thought it is working. but yeah, i can take a look. in the near future :)

**Comment by LoneGazebo** [comment]
Cool, thanks.

**Comment by ilteroi** [comment]
i think it's because in most cases, the unit's turn was already forcefully ended before ParthianMoves is called.

i'll try and put a MoveToSafestPlot() into ExecuteAttack

**Comment by ilteroi** [comment]
boy, how i hate this "queued attack" concept

**Comment by LoneGazebo** [comment]
Hmm...but isn't there a check for whether or not a unit has moves/attacks left after it moves/attacks? Why are they being processed/ended early? That's a curiosity.

**Comment by LoneGazebo** [comment]
The queuing system is pretty damn weird.

**Comment by ilteroi** [comment]
poof. it's gone. now i feel better

**Comment by LoneGazebo** [comment]
how's that gonna affect things?

**Comment by ilteroi** [comment]
to the better, i assume :)

**Comment by LoneGazebo** [comment]
haha – will it affect the order of things re: attacks/moves?

Also, I've been thinking about tactical moves and the rigid priority model that currently exists, and I wonder – what do you think about introducing personality and flavor-based modifications to the values? I.e. higher boldness civs are going to attempt more 'close on target' moves, whereas high disloyalty will try more hit and run. Thoughts? Could be a fun way of imparting some humanity and variety into the tactical AI.

**Comment by ilteroi** [comment]
sounds interesting. it's also partially implemented already. the tactical move priorities are reset every turn, but always to the same values. it should be possible to hook them up to boldness etc.

a few caveats though:
- tactical moves need flavors, don't think they have at the moment
- "more" of a move is difficult. what can be changed is the order of moves. but it might result in a particular move being skipped completely. or it might change nothing at all. depending on the situation.
- in many cases a there is an optimal order. so changing it would lead to worse play. there was a ticket once where i listed the priorities, and there's also code to dump them again. let's look at them first

**Comment by LoneGazebo** [comment]
Sounds good. I guess the issue is that the static order feels, well, static, and may not always be the best order. I wonder if we could introduce a simple scoring model, dump the priorities into it and then sort them by weight on the other end. This could be done for all except for 'key' priorities like withdraw, heal, etc.

**Comment by ilteroi** [comment]
ok, it's done. testing now. fairly big change this late in the release cycle though. maybe pass on it for the time being.

**Comment by LoneGazebo** [comment]
Which part is done? Feel free to push if it's not crashing. I'm going to push the latest beta fairly soon (doing some more testing on my end), so we can open up beta testing to the wider audience. :)

**Comment by ilteroi** [comment]
the surgical removal of queued attacks and the wider application of parthian moves.

pushed.

**Comment by LoneGazebo** [comment]
Fun!

**Comment by ilteroi** [comment]
sorry. don't use it for now. made a mistake when committing.

**Comment by ilteroi** [comment]
it will crash

**Comment by ilteroi** [comment]
ok. the crash was in PlotParthianMoves() btw. i took the liberty to remove it whole. shouldn't be required anymore. pushed again.

**Comment by LoneGazebo** [comment]
Cool. Glad my code wasn't working, then! :)

G

**Comment by LoneGazebo** [comment]
Out of curiosity, will the removal of queued attacks affect any of the other mod elements or lua hooks that look at combat? Thinking about the RED stuff.

**Comment by ilteroi** [comment]
nah. shouldn't do that.

i was referenced in ResolveCombat(), that's true, but as far as i can tell, it didn't do anything there.

btw, another update, i really was to rash before. proper thread safety for pathfinder, i've seen some crashes because of lua and dll both accessing it.

**Comment by LoneGazebo** [comment]
Cool. Will update and push the beta fairly soon.

**Comment by LoneGazebo** [comment]
I don't know what you did, exactly, but the AI is suddenly incredibly competent with their city attack organization. Nice work.

**Comment by Iamblichos** [comment]
Man, nice, just looked at it. The good Doctor is a machine.

**Comment by ilteroi** [comment]
good to hear! i didn't do anything specific for city attacks, but maybe it's because the "overkill" factor is no longer needed. AI will not waste attacks on a dead target anymore.

**Comment by LoneGazebo** [comment]
http://forums.civfanatics.com/showpost.php?p=14169389&postcount=62

**Comment by LoneGazebo** [comment]
Seems like a basic case of melee units not 'sealing the deal.'

**Comment by ilteroi** [comment]
hmm. savegame would have been nice. will keep an eye on it

anyway, pushed an update with some fixes.

**Comment by LoneGazebo** [comment]
Thanks!
