### ISSUE TITLE
AI is not making roads

### ISSUE THREAD

**Issue by Ninakoru** [LoneGazebo/Community-Patch-DLL#1104]
Seems the worker AI is not working properly with roads. AI doesn't build them to connect cities even on ancient games turn 150+. I've seen idle workers (all territory tiles improved) and roads not being built to connect cities.

**Comment by LoneGazebo** [comment]
Really? I see roads all over the place.

**Comment by LoneGazebo** [comment]
Well, I take it (partially) back, it's sporadic. I'd say 50% of civs aren't building them correctly. Ilteroi made some changes here recently, and I've messaged him about it.

**Comment by ilteroi** [comment]
hmm. i made some changes to the valuation of roads. so indeed they might stall a few turns if the connection gold is much lower than the maintenance cost. however, in my tests they did build the road as soon as it became worthwhile. will check

**Comment by ilteroi** [comment]
fixed. nasty side effect changed state of pathfinder before the plots were to be marked
