### ISSUE TITLE
Highlights CTD on founding city ONLY with a MODPACK

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1105]
The new Highlights.xml crashes the game on city found when you use a MODPACK, does not crash when you play as regular mod. Deleted Highlights.xml out of the Lua folder and then the MODPACK works as normal. FYI...for the multiplayer mod.

**Comment by LoneGazebo** [comment]
Gotcha. I'll delete the file then. Seems it does not like hot swapping at all.

**Comment by Iamblichos** [comment]
I wonder if it'll work if I just completely overwrite the original file...

**Comment by Iamblichos** [comment]
Here's an idea, and I just tried this and it work. The rows you have in this Highlight.xml correspond to the one's in UI_bc1\Core (though he has more rows in his file). You could just copy and paste over the rows in the UI_bc1\Core\Highlights.xml file if you want.

**Comment by LoneGazebo** [comment]
Hmm, interesting...

**Comment by LoneGazebo** [comment]
Just going to delete that file and not mess with it in the modpack for now.
