### ISSUE TITLE
empty deal offers are back

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#11062]
v4.9

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/073abc0c-1e31-49ca-ad92-9bc4c0786df1)

[AutoSave_Post_0275 AD-1810.zip](https://github.com/user-attachments/files/16044031/AutoSave_Post_0275.AD-1810.zip)

**Comment by ilteroi** [comment]
one more. this time they try to prolong a gpt vs tech trade
[AutoSave_Post_0321 AD-1901.zip](https://github.com/user-attachments/files/16045184/AutoSave_Post_0321.AD-1901.zip)

**Comment by axatin** [comment]
Yes, should be fixed now.
