### ISSUE TITLE
Hospitals

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1107]
I noted that units don`t get the healing bonus from hospitals any more.
I have hospitals in every city from the freedom tenet, but units heal 20 HP if they do nothing, and not at all if they acted.
the game was with the 1/3 version.

**Comment by LoneGazebo** [comment]
Land units, I assume?

G

**Comment by LoneGazebo** [comment]
Works for me.
G
