### ISSUE TITLE
Right-clicking Printing Press Tech pulls up Printing Press NW Civilopedia Page

### ISSUE THREAD

**Issue by ZetaLambdaNinja** [LoneGazebo/Community-Patch-DLL#11075]
_1. Mod Version (X.Y.Z). Current Version: 4.11.0_

4.11

_2. DirectX Version_

DX 10 & 11

_3. List of Other Mods_

pdan's 34UC (v 88.9), azum4roll's Unit Supply for VP, UI - Promotion Tree for VP

_4. Describe the Issue_

When Printing Press is the technology displayed in the technology view in the upper left-hand corner, right clicking on it should display the civilopedia page for the Printing Press technology.  Instead, it displays the civilopedia page for the Printing Press national wonder.

I presume there's just a broken reference somewhere, and while I doubt logs are needed, I've been wrong about that before.  I'll include them here just in case.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[BUG-PrintingPressTechRightClick.zip](https://github.com/user-attachments/files/16095384/BUG-PrintingPressTechRightClick.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/user-attachments/files/16095401/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Open the attached save.  Open the technology view from the upper left drop-down menu, then right-click on the Printing Press technology icon.

_9. Screenshots of the Issue (Optional)_

**Comment by Hokath** [comment]
It seems that right clicking performs some kind of text-based search that selects the first hit (the building)
I think this because: In a modmod I have renamed the national wonder and this behavior goes away, i.e. right clicking the tech leads to the correct page.

**Comment by axatin** [comment]
exactly, it's a text-based search, so we can't change which result we get. feel free to propose to rename either the tech or the wonder next congress.
