### ISSUE TITLE
No AI code to handle Complete Kills settlers

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#11080]
@ilteroi If an AI has a Settler and no cities with the Complete Kills game option enabled, they currently:
- Wander randomly in search of a valid plot to settle, unless they happen to be on one already, due to CvHomelandAI::ExecuteFirstTurnSettlerMoves();
- Won't get any military units they might also have alive to escort the Settler to safety;
- Have no code that checks "just found a city in the closest legal position possible that we're able to pathfind to, don't be picky about found value".

I don't know how to create a settle operation, and existing preconditions seem to require an escort as well (an exception would need to be made if the player has zero cities and no military units, only the Settler).

Would you be able to add code for this? It's a necessary prerequisite to implement this proposal: https://forums.civfanatics.com/threads/7-61-complete-the-complete-kills-functionality.689067/

**Comment by OneFuriousDon** [comment]
@RecursiveVision Sorry to budge in but if possible preferably in set min safe distance from oppressor and one extra move from "run for your lives promo".

**Comment by ilteroi** [comment]
not sure i get this - where would this settler spawn? what if there is no reachable spot for settling?

anyway i think it's not too hard. do the change mentioned above. and replace the city number check in IsTestStrategy_FoundCity() with a isFoundedFirstCity() check. should work.

**Comment by azum4roll** [comment]
Units already automatically spawn embarked (if needed) when using IGE+, given the player has the tech for it.
