### ISSUE TITLE
Atomic Era CTD on AI turn

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1108]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/91508/Logs.zip)

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/91509/CvMiniDump.zip)
[Crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/91510/Crash.zip)

No idea what could be causing this one, no crashes all game but getting an unavoidable crash on turn 311. Egypt offers a trade and then crashes on his turn. Running full CPP (1/10b), logs, dump, save attached

**Comment by LoneGazebo** [comment]
Breaks to disassembly, Looks like (in your database log) that you are missing Gods and Kings or something.

G

**Comment by joosegoose** [comment]
Bizarre, I'm a longtime player of CPP and definitely not missing DLC. I did
neglect to mention that I was playing in MPMPM form though... I suppose
I'll have to try later from the mod menu. Don't know why I would have a
random crash now when it's been  fine all game though.

**Comment by LoneGazebo** [comment]
Not sure, definitely breaks to disassembly, though, which means it isn't breaking in the DLL.
G

**Comment by joosegoose** [comment]
Might want to take another look at this. I had an idea--I had just bought atomic bombs the turn when I crashed. I went back and replayed the turn without building any bombs, and no crash.

Perhaps it's related to leaders being 'afraid' or some other sort of diplo action?

**Comment by joosegoose** [comment]
Yep, I just loaded up the exact save I uploaded, did nothing but delete the bomb using IGE, and was able to complete the turn. It has to be related to that.

**Comment by LoneGazebo** [comment]
Interesting. I'll take another look.

G

**Comment by joosegoose** [comment]
FYI, I was having trouble getting it to load going through the mods menu without the DLC pack installed. Modpack attached in case you try loading it up at any point.

https://drive.google.com/file/d/0BxQ5ePZeOZ_Uck8xVWVPZU9lSVE/view?usp=sharing

**Comment by Iamblichos** [comment]
The database will be slightly different with a mod pack vs going through the the Modmenu. The mod pack will basically replace everything while the Modmenu is updating the database. The save game will not be compatible across the two, even if it seems the content is the same.

**Comment by LoneGazebo** [comment]
Unfortunately it still crashes to disassembly. Can't reproduce the results of the crash, sorry.
