### ISSUE TITLE
Duplicate Notifications for Ended Trade Deal

### ISSUE THREAD

**Issue by ZetaLambdaNinja** [LoneGazebo/Community-Patch-DLL#11091]
_1. Mod Version (X.Y.Z). Current Version: 4.11.0_

4.11

_2. DirectX Version_

DX 10 & 11

_3. List of Other Mods_

pdan's 34UC (v88.9), azum4roll's Unit Supply for VP, UI - Promotion Tree for VP

_4. Describe the Issue_

Sometimes, when a trade deal with another player ends, I get multiple notifications saying the exact same thing.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[BUG-RepeatedDealEndNotifications.zip](https://github.com/user-attachments/files/16118271/BUG-RepeatedDealEndNotifications.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/user-attachments/files/16118284/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Open the attached save, and look at the golden globe icon with the red X.  You will see that a trade deal with Siam ended involving open borders and GPT.  Notifications 1, 2, and 3 on the list are identical to 4, 5, and 6.

_9. Screenshots of the Issue (Optional)_

**Comment by OneFuriousDon** [comment]
Can confirm it's like that in 4.9 (modpack) as well.
