### ISSUE TITLE
Teletransportation of ranged units v1.1.14

### ISSUE THREAD

**Issue by ricanuck** [LoneGazebo/Community-Patch-DLL#1109]
I just got a nasty teletransportation bug. An archer that could not fire on a city because of a forest, was instead teletransported to a tile near my capital (some 12 tiles away from original position). I did not check the range for the archer, so I right clicked the city, and the teletransport happened. Should be easy to reproduce, just need a similar situation.

**Comment by LoneGazebo** [comment]
You just discovered teleportation early. No bugs! :)

**Comment by Iamblichos** [comment]
Funny thing...Japan asked for some iron and I gave.  all of a sudden 3 samurai teleported to my nearest and then DoW'd me next turn. I thought it was quite hilarious!!

**Comment by LoneGazebo** [comment]
neat

**Comment by LoneGazebo** [comment]
I'm sure ilteroi is going to love this one. Make sure to link some saves here, as well as extra mods if using any other than the standard set.

**Comment by GrantSP** [comment]
Not exactly sure if this is the save that it happened on, only saw this issue after I noticed the exact thing happen to me.
All of a sudden three Samurai swoop in to the interior of the continent that I'm the sole occupant of. Nearly spat my coffee on the monitor.
[AutoSave_0240 AD-1650.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/92790/AutoSave_0240.AD-1650.zip)

**Comment by Christoph-Wagner** [comment]
They don't always teleport, I've had two volley guns completely vanish.

**Comment by ilteroi** [comment]
funny, can't load the savegame ... will try to reproduce on my own

@LoneGazebo: any last minute changes to savegame compatibilty which aren't on github?

**Comment by Der-Zorn-Gottes** [comment]
I just wanted to report the same. It happend when I wanted to bombard a civilian with a ranged ship using right-click.

**Comment by LoneGazebo** [comment]
No the GitHub version is identical to 1/14 version.

**Comment by ilteroi** [comment]
hmm. anyone else has a savefile? couldn't reproduce (on autoplay, maybe that makes a difference)

**Comment by LoneGazebo** [comment]
You need to do it manually ilteroi. Requires unit right click movement to do.

**Comment by ilteroi** [comment]
ok, funny story, as always. pathfinding fails but from lua side a move mission is pushed nevertheless, using stale pathfinder data.

the return value from the pathfinder is ignored at a crucial point, instead pathfinder internals are accessed directly. previously, those were reset if the pathfinding failed but in the last version i changed that for performance. perfectly harmless change, right.

**Comment by LoneGazebo** [comment]
Good to hear.
