### ISSUE TITLE
City unable to purchase a valid tile within its normal purchasing radius

### ISSUE THREAD

**Issue by ZetaLambdaNinja** [LoneGazebo/Community-Patch-DLL#11092]
_1. Mod Version (X.Y.Z). Current Version: 4.11.0_

4.11

_2. DirectX Version_

DX 10 & 11

_3. List of Other Mods_

pdan's 34UC (v88.9), azum4roll's Unit Supply for VP, UI - Promotion Tree for VP

_4. Describe the Issue_

I have three cities that should all be able to claim a tile that is 3 spaces away from city center, but for some reason one of the three is not given the option to purchase that tile (though it can purchase other tiles in its radius.)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[BUG-TheHagueCantBuyTile.zip](https://github.com/user-attachments/files/16118381/BUG-TheHagueCantBuyTile.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/user-attachments/files/16118382/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

In the attached save, open the city screen for The Hague.  Observe the coal tile to the southeast; though it is within 3 tiles of the city center, it cannot purchase the tile.  Other tiles are purchasable by The Hague as normal, and the other two cities in range (i.e. Amsterdam and Rotterdam) have the option to purchase the tile as expected.

_9. Screenshots of the Issue (Optional)_

**Comment by Hokath** [comment]
I suspect the reason is that none of the tiles next to the coal belong to The Hague, is it?

**Comment by SuperNoobCamper** [comment]
Check for tile ownership on the tiles next to it, at least one of the tiles immediately adjacent to it should be owned by that particular city you want to purchase the tile for

**Comment by ZetaLambdaNinja** [comment]
I see the issue may have already been fixed, but just to respond to the above comments:  The Hague did own and was working one of the adjacent tiles.
