### ISSUE TITLE
CTD During AI turn

### ISSUE THREAD

**Issue by boombar123** [LoneGazebo/Community-Patch-DLL#11109]
_1. Mod Version (X.Y.Z). Current Version: 4.12.1_

4.12.1

_2. DirectX Version_
11

_3. List of Other Mods_
[Mods.zip](https://github.com/user-attachments/files/16165470/Mods.zip)

_4. Describe the Issue_
CTD during morocco turn 

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[QuickSave.zip](https://github.com/user-attachments/files/16165490/QuickSave.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/user-attachments/files/16165495/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.dmp](https://github.com/user-attachments/files/16165500/CvMiniDump.dmp)

_8. Steps to reproduce the Issue (Optional)_
Load quick save and just click next turn

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
Thanks for the attached mods folder, that made debugging a lot easier. Bug is fixed for the next version.
