### ISSUE TITLE
1/14 Longhouse isn't allowing production trade routes

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#1110]

**Comment by LoneGazebo** [comment]
It isn't a workshop anymore. Does it still say that in tip? Oops.

**Comment by Mitchsp** [comment]
Yep, so only a problem tip then.

**Comment by LoneGazebo** [comment]
I'll fix.

**Comment by LoneGazebo** [comment]
There's no reference to the longhouse and production on internal routes in the current version. I believe you have a bug on your end here.

**Comment by Mitchsp** [comment]
Strange, I tried before posting here to download again last version of 1/14 and clear cache. Will do another time and start a new game to double check.

<img width="680" alt="sin titulo" src="https://cloud.githubusercontent.com/assets/13163824/12370122/1d5920ce-bc06-11e5-8655-c8b9ad1656cf.png">

**Comment by Mitchsp** [comment]
Tried with only CP + CBP bundle and a new reinstall and still appears as the image above after starting a new game, will take another look tomorrow, thanks.
