### ISSUE TITLE
Players' icons no longer sort by score

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#11106]
_1. Mod Version (X.Y.Z). Current Version: 4.12.1_

_3. List of Other Mods_

![20240710162918_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/16341598/ca087235-46ce-4f9b-ab3d-59831b1b1f60)

_4. Describe the Issue_
Since the previous versions, it seems the game no longer properly sorts players' icons in ascending order. 

![20240710162624_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/16341598/0ee84434-9aa9-4ae7-920a-c72d98b4974a)

**Comment by axatin** [comment]
This is also caused by the teams settings then. Zulu and Aztecs are in one team, and I assume the list is sorted by team score.
