### ISSUE TITLE
4.12.1. Court Chapels in all of my cities

### ISSUE THREAD

**Issue by brsoft1981** [LoneGazebo/Community-Patch-DLL#11108]
_1. Mod Version (X.Y.Z). Current Version: 4.12.1_

_3. List of Other Mods_ None

_4. Describe the Issue_ I've got a free Court Chapel in all of my cities (not only in the capital) 

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[AutoSave_0212 BC-1380.zip](https://github.com/user-attachments/files/16173290/AutoSave_0212.BC-1380.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of
![court2](https://github.com/LoneGazebo/Community-Patch-DLL/assets/96129291/44007207-7272-42b4-bc96-3a62511737ca)
 the Issue (Optional)_

**Comment by azum4roll** [comment]
This and #11107 should be related to the new `CvCity::SetNumFreeBuilding()` function.

But I can't find anything wrong there. Can someone debug?

**Comment by brsoft1981** [comment]
I added my save game
