### ISSUE TITLE
Wonders are not granting any free buildings

### ISSUE THREAD

**Issue by KungCheops** [LoneGazebo/Community-Patch-DLL#11107]
_1. Mod Version (X.Y.Z). Current Version: 4.12.1_

4.12.1

_2. DirectX Version_

_3. List of Other Mods_

(over) More Unique Components for VP (v 88)
(text) Alternative Component Names for VP
azum4roll's Unit Supply for VP
Historical Religions Complete (BNW or GK) (v 45)
InGame Editor+ (v 46)
Quick Turns (v 10)
Randomize City Names (v 2)
Really Advanced Setup (v 15)
Route Planner for VP (v 1)
UI - Small Resource Icons (v 4)

_4. Describe the Issue_

Seems like no wonders are granting their free buildings (Stonehenge, Great Library, etc.).

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by KungCheops** [comment]
Seems like the AI gets the free buildings though.

**Comment by KungCheops** [comment]
AI China not getting a free stone works from Mausoleum
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/6018217/bef12d16-7172-4b93-ab0d-62d4d3701f89)

**Comment by brsoft1981** [comment]
In my game (4.12.1), I've received a free buildings from the Great Wonders
![FreeBuildings](https://github.com/LoneGazebo/Community-Patch-DLL/assets/96129291/dc6b6f6d-603c-4481-b816-d2a4d2dd8122)
