### ISSUE TITLE
Incorrect calculation of happiness and unhappiness

### ISSUE THREAD

**Issue by SuperNoobCamper** [LoneGazebo/Community-Patch-DLL#11105]
_1. Mod Version (X.Y.Z). Current Version: 4.12.1_

4.12
_2. DirectX Version_

DX11

_3. List of Other Mods_

VP with EUI
MUC V88
Better lakesV2
Misc Tweaks v10
Really advanced setup V15

_4. Describe the Issue_

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Oda Nobunaga_0354 AD-1670.zip](https://github.com/user-attachments/files/16159831/Oda.Nobunaga_0354.AD-1670.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

The sum of unhappiness from all sources is far less than the number of calculated unhappiness 

_9. Screenshots of the Issue (Optional)_
![Screenshot (118)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/20557080/7d3452ee-d9ad-4176-a902-1178f65a4bcb)

**Comment by SuperNoobCamper** [comment]
The Screenshot shows:
5 From war weariness
58 from Puppets
2 from poverty
1 from illiteracy
5 Boredom
2 from religious unrest


The sum should be 71 however i have 164 unhappiness

**Comment by boombar123** [comment]
Ive noticed something is messed up with happiness 
![Screenshot 2024-07-10 192412](https://github.com/LoneGazebo/Community-Patch-DLL/assets/174969347/3fd9c2b9-e1c6-4273-a34f-e46fc209274c)
where is this -22 coming from?

**Comment by bsesar** [comment]
@boombar123, do you have Holy Council national wonder (from the Council of Elders founder belief)?

https://github.com/LoneGazebo/Community-Patch-DLL/issues/11113

**Comment by axatin** [comment]
@boombar123  @bsesar  Also other buildings could cause the bug with the negative local unhappiness (which is now fixed).

**Comment by tomekpa** [comment]
Did you check dissidents in tourism tab?

**Comment by axatin** [comment]
save game can't be loaded. the file says it requires CP (133) which is not 4.12 but 4.11, but using 4.11 I can't load it either. Seems to be something wrong with the VP installation.
