### ISSUE TITLE
1/14 Internal trade route not eliminating isolation unhappiness

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#1111]

**Comment by Mitchsp** [comment]
Food trade route from capital with Granary and Longhouse

**Comment by LoneGazebo** [comment]
Interesting, I'll take a look. Is it ocean or land travel?

**Comment by Mitchsp** [comment]
<img width="680" alt="sin titulo" src="https://cloud.githubusercontent.com/assets/13163824/12369982/9bce23f0-bc01-11e5-905b-46aab6c264ea.png">

**Comment by LoneGazebo** [comment]
Your caravan icon looks different...using any other mods that could be causing this?

G

**Comment by Mitchsp** [comment]
R.E.D. Modpack and my usual pack, nothing different in this particular game to the ones I use always without problems.

<img width="680" alt="sin titulo" src="https://cloud.githubusercontent.com/assets/13163824/12370013/c55758ee-bc02-11e5-8b86-62b9e7e70185.png">

**Comment by LoneGazebo** [comment]
Ok.
