### ISSUE TITLE
Bugged peace treaty

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#11119]
_1. Mod Version (X.Y.Z). Current Version: 4.12.1_

_3. List of Other Mods_

![20240710162918_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/16341598/04293a0c-586e-46d9-ba95-22be8dd734a6)

_4. Describe the Issue_
I'm at war with two independent civs - Zulus and Aztecs. During AI turn Zulu asks for peace, I refuse. Next the Aztecs ask for peace, I agree. For some reason I end up having peace with both Aztecs AND Zulu.

_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[1.zip](https://github.com/user-attachments/files/16173704/1.zip)

**Comment by axatin** [comment]
can you attach a zip-file with Local Generals and the UI mods you're using (except ICV)?

**Comment by saamohod** [comment]
> can you attach a zip-file with Local Generals and the UI mods you're using (except ICV)?

[Local Generals to Nearest City (v 2).zip](https://github.com/user-attachments/files/16180350/Local.Generals.to.Nearest.City.v.2.zip)
[UI.zip](https://github.com/user-attachments/files/16180449/UI.zip)

**Comment by axatin** [comment]
they are in the same team

**Comment by saamohod** [comment]
> they are in the same team

Weird. Maybe I accidentally marked them as the same team in game setup. 
Any way to check it in game? The mouse-over tooltip gives no info about it.

**Comment by axatin** [comment]
Having players in the same team is probably also the reason for the incorrect player icons in the notifications you mentioned in the forum thread.
