### ISSUE TITLE
new observer mode has some quirks

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#11125]
v 4.11

* nonsensical numbers in top panel:

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/26236394-d099-4d0d-99f5-ab67d22def44)

* hard to describe but it feels slower. especially the first turns is extremely slow because of of all the settler animations. this was not a problem before, there were no animations in observer mode. what changed?

**Comment by axatin** [comment]
The top panel numbers are not a bug in observer mode, but [this issue](https://github.com/LoneGazebo/Community-Patch-DLL/issues/11113).

Fixed the issue with the animations.
