### ISSUE TITLE
Supply drops in global observer mode (azums supply mod enabled)

### ISSUE THREAD

**Issue by Pipiskus** [LoneGazebo/Community-Patch-DLL#11121]
_1. Mod Version (X.Y.Z). Current Version: 4.12.1_
Current Version: 4.12.1 EUI Community patch

_2. DirectX Version_
9

_3. List of Other Mods_
4uc, Meaningful colors (ui mod that changes CS colors) , My adjusted version of Azums supply mod (read 8)

_4. Describe the Issue_

Global Observer mod seem to change Supply difficulty value to 8 when i toggle it on my first turn. I am using Azums supply mod and i the values he set for difficulty match with the ones he stated, but the moment i toggle Global observer mod it all drops to 8 (i was playing king with 10 supply by default)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

Initial save with accurate supply
[SAVE SUPPLY BUG.zip](https://github.com/user-attachments/files/16175649/SAVE.SUPPLY.BUG.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Database.log](https://github.com/user-attachments/files/16175619/Database.log)

[stopwatch.log](https://github.com/user-attachments/files/16175614/stopwatch.log)

[Lua.log](https://github.com/user-attachments/files/16175600/Lua.log) 

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

Nope

_8. Steps to reproduce the Issue (Optional)_

Use my version of Azum's mod (though i think it would work the same with original version) if you want to load my save, all i did was changing cities hp and increasing supply from difficulty by two for each level, nothing extreme, i changed md5 and mod id, everything worked fine until i used the Observer mode.
 
[pipi's supply.zip](https://github.com/user-attachments/files/16175827/pipi.s.supply.zip)

Make sure that you chose difficulty with supply higher than 8 using Azums mod (i was playing king, so it should have been 10 (or 12 if you play with my version)), you will see that the supply from difficulty level drops the moment you toggle Global observer mode, after this it will not come back if you decided to choose any civ, it will always be 8 to the rest of the game ( the supply from difficulty).

_9. Screenshots of the Issue (Optional)_

--------

**Comment by Pipiskus** [comment]
To be honest i changed the existing azum's mod, i didnt create a new mod for this play, so the pipi's supply mod differ in names with the one used in the save - the adjusted azums mod. Idk if it can cause issues, i can link you the exact version of this mod iam using right now with old name if thats the problem

**Comment by axatin** [comment]
Intentional, AI players always play on AI difficulty.
