### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1112]
what does CvTraitEntry::IsTradeRouteOnly() do? which trait is that? it'd be really nice to have some comments in the code, it's often entirely non-obvious what they are supposed to mean ...

**Comment by LoneGazebo** [comment]
That's for terrain yield bonuses. Only gain them from tiles on TRs or city connections.

**Comment by LoneGazebo** [comment]
Should be comments in CP where column info is defined.

**Comment by ilteroi** [comment]
so it's a negative trait? maybe let's call it IsYieldBonusFromTradeRouteOnly() then.

anyway, did some cleanup work on IsTradeRoute() but the way IsTradeRouteOnly() is used is not quite logical to me. can you give it a look? pushing right now

**Comment by LoneGazebo** [comment]
I'll look tomorrow or the next day. Thanks!
