### ISSUE TITLE
Huge unhappiness bug?

### ISSUE THREAD

**Issue by Amecareth002** [LoneGazebo/Community-Patch-DLL#11122]
_1. Mod Version (X.Y.Z). Current Version: 4.12.1_

_2. DirectX Version_

_3. List of Other Mods_

More unique components v.88
Unique city-states v.16.3
New Beliefs mod v.20
PinnappleDanTweaks

All of them are VP versions

_4. Describe the Issue_

Since downloading 4.12.1, I have some ridiculous happiness penalties. Notably, in the provided save file, my capital directly goes from -18 happiness from buildings to -31 after completing The Colossus of Rhodes. I unfortunately didn't notice exactly when the previous unhappiness occurred. I don't remember that kind of bug happening in 4.11.

Bonus bug, I didn't get a free herbalist after completing the Temple of Artemis. I don't have the save file, but you can see that the herbalist in my city isn't a free one
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0116 BC-1100.zip](https://github.com/user-attachments/files/16177575/AutoSave_0116.BC-1100.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs(part_1).zip](https://github.com/user-attachments/files/16177626/Logs.part_1.zip)

[Logs(part_2).zip](https://github.com/user-attachments/files/16177679/Logs.part_2.zip)

[Logs(part_3).zip](https://github.com/user-attachments/files/16177709/Logs.part_3.zip)

[Logs(part_4).zip](https://github.com/user-attachments/files/16177720/Logs.part_4.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

![bug_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/20826050/202a874a-724b-47ee-910c-a9c219ab3b79)

![Bug_2](https://github.com/LoneGazebo/Community-Patch-DLL/assets/20826050/f384b539-b00c-4eb2-8626-c0a73ede7661)

One pictures shows unhappiness before and the other shows the same after the Colossus is completed

**Comment by axatin** [comment]
Already fixed.

**Comment by Amecareth002** [comment]
Is it going to be fixed in an upcoming version? It's happening in the brand new 4.12.1

**Comment by axatin** [comment]
Yes, that's what I meant, already fixed for the next upcoming version.
