### ISSUE TITLE
Intended feature or bug with farm repairing 

### ISSUE THREAD

**Issue by Amecareth002** [LoneGazebo/Community-Patch-DLL#11137]
_1. Mod Version (X.Y.Z). Current Version: 4.13_

_2. DirectX Version_

_3. List of Other Mods_

More unique components v.88
Unique city-states v.16.2
New beliefs v.20

All of those are VP versions

_4. Describe the Issue_

Whenever I repair farms, not only they do not immediately regain their yields, their food is set to 1. After about 15 turns, their food yields is set to normal (as shown in both save files). The auto-building ai seems to notice that repairing farms won't work as intended and just let them pillaged unless I manually tell them to go there. I am not aware of this behavior happening to other improvements since, in my testing, repaired mines do instantly regain their yields.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0146 BC-0410.zip](https://github.com/user-attachments/files/16201820/AutoSave_0146.BC-0410.zip)
[AutoSave_0161 BC-0185.zip](https://github.com/user-attachments/files/16201821/AutoSave_0161.BC-0185.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Log.zip](https://github.com/user-attachments/files/16201828/Log.zip)

*Log files from the day before the bug was reported*

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

In the 146th turn save, repair the farm (the one shown in the screenshot), you will see that the food yield goes down to 1. Then either play along or load the other provided save, which is the last turn before the farm gets back its normal yields.

_9. Screenshots of the Issue (Optional)_

![bug_1](https://github.com/user-attachments/assets/0a4b46d2-5ebb-4241-b42a-e9503630dc26)

**Comment by Amecareth002** [comment]
EDIT 1: The same farm got pillaged again and the bug didn't appear, it could be happening only on the first repair?

**Comment by axatin** [comment]
Are you playing with events on? Some events temporarily reduce food given by farms.

**Comment by Amecareth002** [comment]
Yeah......It might just be a question of timing here, my bad..
