### ISSUE TITLE
Empty gifts

### ISSUE THREAD

**Issue by TemonOak** [LoneGazebo/Community-Patch-DLL#1113]
Sometimes at the start of a game I am friendly with an Ai. So good friends that they want to give me a gift. Sadly, it seems that they have not selected anything to give me, so I cant accept it and have to decline. This give me a bad relations untill the penelty go away.

As far as I know I have no other mods active. used the multiplayer folder since it makes it easier to start the game without extra clicking

**Comment by ZaresI** [comment]
Happened to me as well. And not only this, AI wanted to give me something as a gift, but when I accept it, it refuses!

If we are in trade problems, I sold Lapus Lazuli for 4 GPT, but on top bar it showed as 1 gold from other Civilizations.

So yes, something is wrong with trading :(

**Comment by LoneGazebo** [comment]
Using modpack both of you? Reports of the error seem to only come from modpack users.

**Comment by LoneGazebo** [comment]
This is a modpack issue, closing.
