### ISSUE TITLE
Question/suggestion - Passable rivers

### ISSUE THREAD

**Issue by Punklife** [LoneGazebo/Community-Patch-DLL#11141]
_1. Mod Version (X.Y.Z). Current Version: 4.13.1_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_
 Is there any way to make rivers passable for naval units? Also, is there a way to make coastal cities on lakes and rivers at least able to build ports (without lighthouses and prevented from building seaports)? Thanks!

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by Punklife** [comment]
> Nope, i mean, its possible but if its not in vanilla, it shouldn't be here.
> 
> also, its not a feature request forum, its github, its for technicalities, coding and bug reports.

"Nope, i mean, its possible but" does not appear to be an example of a technical answer.

**Comment by azum4roll** [comment]
No, it's not possible. Rivers are between tiles and units are within tiles.

**Comment by Punklife** [comment]
@azum4roll So what you're saying is that it's not possible to make the game generate rivers that only pass through one tile, as they will always be generated between two tiles?
Let me explain the reason for the doubt: since update 4.11 I noticed that the game has been generating large masses of water on standard or larger maps without the possibility of creating an exit to the sea (forts and citadels). The problem is that these bodies of water are too large to be considered lakes and too small to be considered oceans. The game considers them oceans (I lost the saved games and logs so I didn't open a discussion). The AI ​​starts to create units within these masses but they are held back, which doesn't make much sense. My proposal would be to make them large lakes (probably a size modifier problem) opening the possibility of finding a path to the sea. The possibility of creating ports and creating naval units in rivers and lakes, making them passable, would make this solution viable. I do not know if i was clear.

**Comment by axatin** [comment]
> Nope, i mean, its possible but if its not in vanilla, it shouldn't be here.
> 
> also, its not a feature request forum, its github, its for technicalities, coding and bug reports.

Feature requests are totally acceptable here as long as the feature is turned off by default and used only in a modmod or by manually editing files. @nu-illasera2 You are not a developer here, it's not up to you to decide what this repo is used for.

@Punklife As azum said, rivers are between tiles so units can't move on them. As to the other changes: I'm not sure if you're asking for them to be implemented in base VP or if you want to modify the game for yourself. In the former case github is indeed not the right place, but you can make a proposal in the next congress session on the VP forum. In the latter case: It's not possible to have a building that can be built on coasts or on rivers/lakes, but not everywhere else. You can change the number of tiles a body of water must have for it to be considered an ocean. In (2) Vox Populi/Database Changes/DefineChanges.sql, use an update-statement like the ones in the file to change the value of "MIN_WATER_SIZE_FOR_OCEAN" (current value 10).

**Comment by Punklife** [comment]
@axatin I'm asking to modify the game myself, but it might be a solution to the problem I reported (the big closed ocean problem). Personally, I like the idea of ​​large lakes concentrating plots in a few areas. Thanks for the tip anyway.
