### ISSUE TITLE
stack corruption

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1115]
barbarians captured a capital, this resulted in a stack corruption exception in CvPlayer::SetHasLostCapital() - "stack corruption around aTeamCityCount"

![image](https://cloud.githubusercontent.com/assets/1358966/12372866/2c98d858-bc66-11e5-9576-326c20501823.png)

didn't watch the game closely, but barbarians capturing two cities from a major shouldn't really happen i guess. maybe indicates another problem

**Comment by ilteroi** [comment]
seems it's not a barbarian problem, happened also when the zulu captured the songhai capital. could continue the game though

**Comment by ilteroi** [comment]
haven't experienced this again ... closing it

**Comment by LoneGazebo** [comment]
Sounds good.
