### ISSUE TITLE
Negative gold on city connection with 1 pop city

### ISSUE THREAD

**Issue by artemigkh** [LoneGazebo/Community-Patch-DLL#11158]
Mod Version: 4.13.1
Mod List: (1) Community Path + (2) Vox Populi
Description: Easily reproducible with IGE, a city connection with the capital that only has 1 pop has a negative amount:
![image](https://github.com/user-attachments/assets/8378e989-8191-4a8a-97f9-465fe7179d0d)

Attached Save:
[Turn_Pre_City_Connection.zip](https://github.com/user-attachments/files/16277396/Turn_Pre_City_Connection.zip)

There's already a negative cost with city connections in the form of road maintenance, so this seems unintentional to me

**Comment by Hokath** [comment]
It is intentional in that the formula has a -1 gold in it as a base.

**Comment by azum4roll** [comment]
It's intentional, but you can propose a lower limit of 0 or even change the formula next congress.

**Comment by artemigkh** [comment]
gotcha, thanks

**Comment by Hokath** [comment]
I didn't have a good feel for it, so I quickly calculated city yields
for a total 100 citizens you get a map like this:
![image](https://github.com/user-attachments/assets/e7c7702e-991d-44ba-97d8-e408c4d48081)

**Comment by Hokath** [comment]
zoom on the realistic part
![image](https://github.com/user-attachments/assets/c2ebf3bc-2eff-4c56-9d42-5dadc331837c)
