### ISSUE TITLE
God of War not Triggering on Barbarian Kill

### ISSUE THREAD

**Issue by coinich** [LoneGazebo/Community-Patch-DLL#11169]
_1. Mod Version (X.Y.Z). Current Version: 4.14.1_

_2. DirectX Version_

_3. List of Other Mods_

More Unique Components for VP v88
azum4roll's Unit Supply for VP
Squads DISABLED

_4. Describe the Issue_

Killing barbarians does not trigger God of War pantheon.  Did not notice any change for conquering cities or killing AI Civ units either.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Alexander_0178 BC-1720.zip](https://github.com/user-attachments/files/16326222/Alexander_0178.BC-1720.zip)
Only one save, but there's a barbarian near Persepolis with a Scout nearby in range to kill it

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/user-attachments/files/16326225/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Kill a barbarian unit.  Possibly kill any unit/city?

_9. Screenshots of the Issue (Optional)_
![20240721180713_1](https://github.com/user-attachments/assets/1857e841-78a9-4ad6-88b1-9fe5b9ef7656)
![20240721180729_1](https://github.com/user-attachments/assets/c0764af5-e0f8-4630-a978-8a91375171eb)
![20240721180732_1](https://github.com/user-attachments/assets/4124c816-67eb-4fad-bd62-7ccdf9295b9b)
![20240721180743_1](https://github.com/user-attachments/assets/8c9be1b5-ce66-427a-b857-fb28516d3878)
![20240721180831_1](https://github.com/user-attachments/assets/1e649b57-3aeb-4a0e-b974-7e856e4f5423)
![20240721180846_1](https://github.com/user-attachments/assets/26b0633e-089c-4caa-9171-1b83f5afd619)

**Comment by Hokath** [comment]
Tested God of War with latest version and works for me. Will look at save

**Comment by coinich** [comment]
Weird.  Attaching zips of my mods.  Ofc the 4UC mod is 28MB not 25MB so I can't attach directly.

https://drive.proton.me/urls/DSN8AS0KMC#jpDRTchk2OqR

**Comment by Hokath** [comment]
Opened save -- no yield
Spawned new barbarian near Hoplites to the North East -- no yield
IGE -- Founded Religion
Spawned new barbarian near Hoplites to the North East -- yield again

**Comment by Hokath** [comment]
so something wonky going on with the Belief backend

**Comment by azum4roll** [comment]
What's your primary religion?

**Comment by coinich** [comment]
Err, mine?  I mean, I hadn't founded one yet.

**Comment by Hokath** [comment]
Is that a thing? If you don't have your pantheon in the majority of cities you lose God of War?

**Comment by coinich** [comment]
I kinda hope not - nobody takes God of War to go hippie peace mode.  Capturing even one capital at that point threatens to turn off your pantheon unless/until you get more cities running.

**Comment by azum4roll** [comment]
It's a "global" belief, so it only works if and only if the belief belongs to your primary religion.

But shouldn't a captured city automatically gain the pantheon before you found?

**Comment by Hokath** [comment]
Yeah I would have thought so but in this save file at least the conquered cities have no followers

**Comment by coinich** [comment]
Hmm, I can try checking my past autosaves to see the exact order of
things.  I believe I conquered Persia before I founded my pantheon - not
sure if they had founded one yet.  India already had theirs of course.

**Comment by coinich** [comment]
Unless conquered cities are supposed to take my pantheon... cant remember
now.

**Comment by azum4roll** [comment]
There's actually no reason for Faith on kill to not be local. Maybe we should just change it to local?

**Comment by coinich** [comment]
Is that a change thats savegame compatible?  Do I just need to go back 30-50 turns of autosave and reevaluate how I do things?

**Comment by axatin** [comment]
> Maybe we should just change it to local?

What exactly does that mean?

**Comment by azum4roll** [comment]
> > Maybe we should just change it to local?
> 
> What exactly does that mean?

Not requiring the belief to be part of the primary religion, instead only the majority religion of the origin city of the unit.

**Comment by axatin** [comment]
> > > Maybe we should just change it to local?
> > 
> > 
> > What exactly does that mean?
> 
> Not requiring the belief to be part of the primary religion, instead only the majority religion of the origin city of the unit.

Could be done, but that's something to be discussed in congress. I'd say it's intentional that the bonuses are not given completely unconditionally.
