### ISSUE TITLE
Puppets aren't working tiles (4.13.1)

### ISSUE THREAD

**Issue by Primarch-Alpharius** [LoneGazebo/Community-Patch-DLL#11168]
_1. Mod Version: 4.13.1

_2. DirectX Version_

_3. List of Other Mods_
![MODS](https://github.com/user-attachments/assets/450844f8-d015-4805-b47e-7fc01f002577)

_4. Describe the Issue_ My puppets aren't working all the tiles available. In the case of Berlin, it's even to the point of starvation (it has instead 10 laborers)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[Harald Bluetooth_0183 AD-1230.zip](https://github.com/user-attachments/files/16322723/Harald.Bluetooth_0183.AD-1230.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![1](https://github.com/user-attachments/assets/d8cc4bf5-91f5-4bba-85b5-41f4917b9b1c)
![2](https://github.com/user-attachments/assets/15dd42e8-5932-4dee-b86f-f6a0efc6afcf)
![3](https://github.com/user-attachments/assets/43e10794-3561-42f6-aa5d-781eca6da8e6)
![4](https://github.com/user-attachments/assets/be8e6ddf-aec8-4f24-ab21-7eed567d9d7b)
![5](https://github.com/user-attachments/assets/b8a7b75f-c860-42de-9536-80226c7cbf7e)

**Comment by axatin** [comment]
I can't load the save. Don't know what's wrong, I'm using the exact same mods as in the screenshot, but it crashes whenever I try to load it. Nothing I can do here...

**Comment by Mwallx** [comment]
@RecursiveVision @axatin hey this is happening to me again in 4.15.2 may I send you my save?

**Comment by Mwallx** [comment]
@RecursiveVision
![image](https://github.com/user-attachments/assets/e3579f31-aa92-40b4-b5d4-af1fb216d8b5)
just 4uc(guess everyone has it)

![image](https://github.com/user-attachments/assets/e9c67fba-0b50-4b43-945e-586c0ad30110)
[saves.zip](https://github.com/user-attachments/files/16922472/saves.zip)

**Comment by Mwallx** [comment]
Anyway, seems starving a pop would reset the work tiles and backs to normal.

**Comment by Mwallx** [comment]
It's still happening in every of my 4.16 run with 4 uc
