### ISSUE TITLE
CTD End of turn

### ISSUE THREAD

**Issue by vetox20** [LoneGazebo/Community-Patch-DLL#11172]
_1. Mod Version (X.Y.Z). Current Version: 4.14.1_

_3. List of Other Mods_

![image](https://github.com/user-attachments/assets/8e9e5aeb-0a73-492d-9ab5-e6db43992ac4)

_4. Describe the Issue_
CTD during end of turn process

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[LogsSaveDump.zip](https://github.com/user-attachments/files/16379317/LogsSaveDump.zip)

_8. Steps to reproduce the Issue (Optional)_
proceed until end of turn

**Comment by axatin** [comment]
Memory issue
