### ISSUE TITLE
Modpack version 1/14 crashes upon founding first city

### ISSUE THREAD

**Issue by Domonu** [LoneGazebo/Community-Patch-DLL#1117]
Added Lynnes's modpack version 1/14 this morning (cleared cache, logs, old MP out) and went to start up a new game in single player. As soon as I clicked 'found city' the game crashed. I tested this multiple times with multiple civs and it crashed 100% of the time with each of them. 

EDIT: Reverted to 1/10b Beta modpack and found city works just fine.

**Comment by Iamblichos** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/1105

**Comment by LoneGazebo** [comment]
Delete the highlights.xml file. I should've told Lynnes, oops.

**Comment by Domonu** [comment]
Thanks for all your hard work!
