### ISSUE TITLE
guided missile damage

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1118]
something is wrong here.

![image](https://cloud.githubusercontent.com/assets/1358966/12374679/76d33ca0-bca3-11e5-9724-5d06083895b2.png)

this is the second guided missile i dropped on the swedish rifles. first one said 57 damage, second one 50 damage. but the rifleman still has 70hp left.

**Comment by ilteroi** [comment]
it's even stranger. after attacking with a tank, the rifleman heals spontaneously?

![image](https://cloud.githubusercontent.com/assets/1358966/12374897/ad0f4608-bcab-11e5-821a-a19296493306.png)

**Comment by LoneGazebo** [comment]
Latter is because of Swedish UA. Value difference is odd.

**Comment by ilteroi** [comment]
ok, strange coincidence with the GG ...

anyway it seems the problem is in the text formatting for the missile: the value shown is the damage to the missile before it self-destructs. it should be the damage to the defender instead.

**Comment by ilteroi** [comment]
another small problem though:

![image](https://cloud.githubusercontent.com/assets/1358966/12377280/4bfbe9a8-bd18-11e5-8f4e-aa38b96053ad.png)

note the interception warning. but there is no interceptor. in EnemyUnitPanel.lua it says

				if (pMyUnit:GetDomainType() == DomainTypes.DOMAIN_AIR) then
					iTheirDamageInflicted = pTheirUnit:GetAirStrikeDefenseDamage(pMyUnit, false);				
					iNumVisibleAAUnits = pMyUnit:GetInterceptorCount(pToPlot, pTheirUnit, true, true);		
					bInterceptPossible = true;
				end

so it doesn't check if iNumVisibleAAUnits is zero. also, the additional parameters for the GetInterceptorCount() are true, so only land-based interceptors are counted.

proposal would be to change the text TXT_KEY_EUPANEL_AIR_INTERCEPT_WARNING2 to something like "interception may boost damage to attacker" or change the lua.

**Comment by LoneGazebo** [comment]
Probably best to change text not Lua in this case.
