### ISSUE TITLE
Rival scouts pushing away my units

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#11180]
1. Mod Version (X.Y.Z). Current Version: 4.14.1_

3. List of Other Mods_
![20240729152112_1](https://github.com/user-attachments/assets/eae56e14-76d9-4ef9-b003-f2bcf6b9271d)

_4. Describe the Issue_
This may not be a bug but a mechanic intended to counter cheesy human tactic, but I'll report it in case it isn't.
Rival units of the scout line are able to push my units sitting atop an ancient ruin, and "steal" the ruin from my "guardian".
![20240729152037_1](https://github.com/user-attachments/assets/c3c47aad-4f7e-4036-ab8f-85abec7b4658)

![20240729152404_1](https://github.com/user-attachments/assets/d6f728d5-73e2-4f3e-bf22-94b6cef5d9a1)

_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[1.zip](https://github.com/user-attachments/files/16412891/1.zip)

**Comment by SuperNoobCamper** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/10529
already reported

**Comment by axatin** [comment]
closed, duplicate
