### ISSUE TITLE
Logistics

### ISSUE THREAD

**Issue by mikes61293** [LoneGazebo/Community-Patch-DLL#1119]
I cannot upgrade sea units with logistics (double attack) after coastal raider 3.  I have the authority policy that grants the promotion with the same name.  The only way I can find the logistics promotion in the civilpedia is by going to the ship of the line.

**Comment by TechpriestEnginseer** [comment]
Don't you need like the +1 Range promotion before the double attack promotion?

**Comment by Kolaris8472** [comment]
Logistics is for ranged units only. Melee units get Blitz, but I don't know if it's available on ships.
