### ISSUE TITLE
City tile expands into a useless out-of-range bonus resource tile instead of expanding into a bonus resource within range.

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#11198]
_1. Mod Version (X.Y.Z). Current Version: 4.15_

_4. Describe the Issue_
Could the automatic tile expansion logic be improved? This case looks bugged/suboptimal.
Here on the screenshot it shows that the next expansion will happen onto Bison tile that won't be useful anyway due to distance, while ignoring the Wheat tile that is in range.

![20240804023556_1](https://github.com/user-attachments/assets/ad7e1ce0-e750-40fc-b083-e225ecd4fe3b)
![20240804023857_1](https://github.com/user-attachments/assets/115cb6a3-24df-4990-9792-48da92e2b30b)

**Comment by azum4roll** [comment]
I'm guessing it wants the stone?

**Comment by azum4roll** [comment]
It's not something that can be looked into without mod list and save file.

**Comment by saamohod** [comment]
> It's not something that can be looked into without mod list and save file.

It appears I don't have a savegame from that turn. Maybe next time :(

**Comment by azum4roll** [comment]
Closing this for now then.
