### ISSUE TITLE
puppet cities not building anything

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1120]
this zulu game is really a goldmine of oddities

![image](https://cloud.githubusercontent.com/assets/1358966/12377444/ca202f0a-bd1e-11e5-83ae-08f14a42ef47.png)

some puppets do build things, but not those three. it seems they ran out of buildings and are not eligible for processes? is this intended?

**Comment by LoneGazebo** [comment]
Yep, they can't do processes. Perhaps we should allow that if there is nothing else to do?

**Comment by ilteroi** [comment]
yes. in this particular case, wealth would help a lot against unhappiness

**Comment by LoneGazebo** [comment]
Fixed.
