### ISSUE TITLE
unit swapping

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1121]
another strange problem.

![image](https://cloud.githubusercontent.com/assets/1358966/12377634/80c5dc0a-bd24-11e5-9579-e71df79e4423.png)

the infantry cannot regularly enter the plot to its east (both canMoveInto() and canSwapHere() correctly return false) but the move mission is nevertheless executed. call comes straight from lua.

![image](https://cloud.githubusercontent.com/assets/1358966/12377646/fb74b30e-bd24-11e5-8d31-503ba2f61e17.png)

any changes on lua side lately? anyone know how to debug this?

**Comment by LoneGazebo** [comment]
No changes to Lua, no. You can use the firetuner to call a specific Lua function on a plot. It might give you the true/false element you need.

**Comment by ilteroi** [comment]
same root cause as #1109
