### ISSUE TITLE
Pioneer Bug Report

### ISSUE THREAD

**Issue by Flamingcheesepie** [LoneGazebo/Community-Patch-DLL#11219]
4.14.1

When settling a pioneer, the value of PIONEER_POPULATION_CHANGE is being counted twice. Currently the define is 3, so settling should create a 4 pop city, (3 + 1 base), but is creating a 7 pop city. Confirm that when changing PIONEER_POPULATION_CHANGE to 2 it settles a 5 pop city. 

Likely this bug came when pioneers and colonists were fixed to start spawning with (1 + PIONEER_POPULATION_CHANGE) pop instead of PIONEER_POPULATION_CHANGE pop. It may also be linked to Colonist - Colonist spawns a city with (1 + PIONEER_POPULATION_CHANGE  + COLONIST_POPULATION_CHANGE) pop, which is calculated correctly as (1 + 3 + 5).

**Comment by axatin** [comment]
Can't reproduce. When I found with a pioneer I get a city with 4 pop, and 6 when using a colonist. (tested on 4.15 but I don't think anything related to it was changed in between). Any additional mods you're using?
