### ISSUE TITLE
crash upon opening the tech tree or pressing the next turn button playing denmark

### ISSUE THREAD

**Issue by Mwallx** [LoneGazebo/Community-Patch-DLL#11224]
_1. Mod Version (X.Y.Z). Current Version: 4.14.1

_2. DirectX Version_
10&11 but not graphical

_3. List of Other Mods_
![image](https://github.com/user-attachments/assets/ebf3d791-6c6e-4cc1-8bef-ae45b597ff01)

_4. Describe the Issue_
Crash when I open the tech tree or sometimes the next moment I click next turn. It's not stably reproducible but happens randomly since about turn 195. Don't know civ 5 modding yet so I've no idea what's the common point between these 2 actions but it should be the same cause I guess.

_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
Sorry but I only switched the interval from 2 turn a save to 1 turn after some point of the run. Hope no essential info is lost. Oh it's 1 turn before not from turn 1, well, uploaded all saves already.
https://drive.google.com/file/d/1cs3PTloX6iCJiK1wu3xfKZL7WwtPc5YP/view?usp=drive_link

_6. Logs
[logs.zip](https://github.com/user-attachments/files/16602544/logs.zip)

_7. CvMiniDump.dmp File 
[CvMiniDump.dmp](https://github.com/user-attachments/files/16602561/CvMiniDump.dmp)

_8. Steps to reproduce the Issue (Optional)_
not ruproducible by a fixed procedure, happens randomly but utter frequently (like 1~2 times a turn since turn 195)

_9. Screenshots of the Issue (Optional)_

**Comment by bsesar** [comment]
Maybe a memory issue? Have you tried turning off yield icons or going into strategic view before opening the tech tree?

**Comment by azum4roll** [comment]
Just don't zoom out.

**Comment by Mwallx** [comment]
> Maybe a memory issue? Have you tried turning off yield icons or going into strategic view before opening the tech tree?

but my pc has 32 gb of it, how could that be, I used to play the same map size with a 8 year older laptop with ony 8 gb than the current one and it never crashes because of memory

**Comment by Mwallx** [comment]
I can load the save in like 5 seconds, I'd really doubt it's a memory issue.

**Comment by Mwallx** [comment]
here's another data point 

[quick save and logs.zip](https://github.com/user-attachments/files/16613606/quick.save.and.logs.zip)
[CvMiniDump.dmp](https://github.com/user-attachments/files/16613608/CvMiniDump.dmp)

**Comment by Mwallx** [comment]
that's just strange I just saved before clicking the tech tree and crashing, then after loading and openning the tech tree it wont crash

**Comment by Mwallx** [comment]
Trying this and that I found out that if I open the tech tree the next second after I save the game, it seems not to crash. Also it could crash if I stay too long pondering at what tech I should choose AT the tech tree screen the moment when I click the next tech to research.

**Comment by Mwallx** [comment]
maybe this has been fixed in 4.15.2 or I learned not to toggle yield icon since industrial era, havent encountered this in the next 2 runs, maybe this could be closed
