### ISSUE TITLE
City governor favors food instead of gold while producing a settler

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#11228]
_1. Mod Version (X.Y.Z). Current Version: 4.15.2_

_2. List of Other Mods_

![20240806225028_1](https://github.com/user-attachments/assets/ccfe02f4-24cf-4e52-91df-619f7e8adc3b)

_3. Describe the Issue_
City governors gives preference to a 4-food 1-gold tile over a 2-food 2-gold tile when producing a settler. Since food is not consumed when producing a settler, nor is it used for the production of the settler, obviously the governor should give preference to the 2-gold tile.

_4. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[1.zip](https://github.com/user-attachments/files/16634293/1.zip)

_5. Screenshots of the Issue (Optional)_
![20240816102322_1](https://github.com/user-attachments/assets/3cf5dc71-2d13-44b4-bd0d-3935cbd359fc)

**Comment by azum4roll** [comment]
2 excess food = 1 production.

**Comment by axatin** [comment]
Yes, excess food is converted to production when a settler is being built, so it makes sense the governor chose the tile with more food.
