### ISSUE TITLE
Some Methods from DLL to Lua

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1122]
A simple request, I think. Could I please get the following functions pushed out to Lua (assuming I read correctly that they are in r/CvGameCoreDLL/CvTeam.h:
**Team:GetNumTurnsAtWar(teamID)**
**Team:GetNumNaturalWondersDiscovered()**

These are fairly low priority for me, so feel free to look into it at your leisure. Thanks.

**Comment by LoneGazebo** [comment]
Done.
