### ISSUE TITLE
Tech UI Issue

### ISSUE THREAD

**Issue by TheIllestVillain100** [LoneGazebo/Community-Patch-DLL#11238]
1. Mod Version (4.15.2) (8/21 as of writing)
2. DirectX 10
3. List of Other Mods: N/A

The tech tree messes up and starts to clip into itself a bit. You also can't scroll down the tree, and the farthest the game will let you research is up until the classical era before it blanks out and gives you no more techs as if the other eras don't even exist.

I'm not very good with computers, so figuring out how to diagnose the cause of this in the first place has taken me roughly a week. I barely learned how to log and came across something in my LUA logs suggesting that something with TechHelpInclude.lua and TechTree.lua is messing up in some way. I'll add the logs and attachments as well to help see if there's something that someone else could see that I'm missing. Like I said, I'm not experienced with this sort of thing, so if it looks like I'm doing something stupid, let me know because I probably am. 

[Lua.zip](https://github.com/user-attachments/files/16703267/Lua.zip)

[TechHelpInclude.zip](https://github.com/user-attachments/files/16703268/TechHelpInclude.zip)

![tech tree screenshot](https://github.com/user-attachments/assets/1a246e69-fc83-4be3-81e8-39706397f4d8)

**Comment by axatin** [comment]
Looks like there's something wrong with your installation. Are you using the latest version of Civ 5 (ends on .279)? Do you have all DLC installed?

**Comment by TheIllestVillain100** [comment]
> Looks like there's something wrong with your installation. Are you using the latest version of Civ 5 (ends on .279)? Do you have all DLC installed?

My version ends in .279, yeah. I have all DLC for the game except the Kamehameha Leader Pack, other than that I have every other leader pack and DLC items.

**Comment by axatin** [comment]
You need all the DLCs, also the Kamehameha one.

**Comment by TheIllestVillain100** [comment]
> You need all the DLCs, also the Kamehameha one.

Yeah, that worked wow. I hope I never come into a situation where I have to learn in depth how computers work cause that's really dumb that that fixed it. Nevertheless, thank you so much for helping. I'm pleasantly surprised people still take the time to help people with a game that's over a decade old.
