### ISSUE TITLE
Gold gifting to city states not working properly

### ISSUE THREAD

**Issue by JimPix1** [LoneGazebo/Community-Patch-DLL#11243]
_1. Mod Version (X.Y.Z). Current Version: 4.15.2_

4.15.2 EUI compatible 

_2. DirectX Version_

DX 11

_3. List of Other Mods_

I am only using Vox Populi, No other mods.

_4. Describe the Issue_

When using Vox Populi and going into the menu of any city state and then going to the Diplomatic missions, gold gifts cost you 0 gold but give you 5 influence with them, for all gold gift options. Clicking it does actually give you the 5 influence with the city state and can be spammed to get an alliance.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0000 BC-4000.Civ5Save.zip](https://github.com/user-attachments/files/16741540/AutoSave_0000.BC-4000.Civ5Save.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/user-attachments/files/16741543/Logs.zip)

_8. Steps to reproduce the Issue (Optional)_

Click a city state and go into diplomatic missions.

_9. Screenshots of the Issue (Optional)_
![image](https://github.com/user-attachments/assets/ebdad512-dd51-4c2d-8c5e-f0b3c17d34e2)
![image](https://github.com/user-attachments/assets/3ecac67e-7111-4bf3-ad3d-ccad19564c57)

**Comment by bsesar** [comment]
@JimPix1, I just checked my game and I do not see any "0 Gold" entries in the CS diplomacy screen. Have you tried to delete the MODS and cache folders, and install the mod from scratch?

**Comment by JimPix1** [comment]
Reinstalled Vox Populi again and it seems to be working now. Sorry.
