### ISSUE TITLE
Work Boat Purchase Price Increased by 10

### ISSUE THREAD

**Issue by Mwallx** [LoneGazebo/Community-Patch-DLL#11244]
_1. Mod Version (X.Y.Z). Current Version: 4.15.2_

_2. DirectX Version_
11

_3. List of Other Mods_
only 4uc

_4. Describe the Issue_
Literally the title, it was 60 production or 130 gold at the beginning of the game, then the gold cost increased by 10 some time during the run. 

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[saves.zip](https://github.com/user-attachments/files/16743459/saves.zip)
you can see the cost difference loading these 2 saves, they are arbitrarily picked, I can provide others or locate exactly which turn it changed if necessary.

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[logs.zip](https://github.com/user-attachments/files/16743473/logs.zip)

_8. Steps to reproduce the Issue (Optional)_
not sure

_9. Screenshots of the Issue (Optional)_
![~BS$U$4()R)X``{4613(YP6_tmb](https://github.com/user-attachments/assets/e28051c2-013e-47cc-9e81-67c4d8f1a677)
![BYZ) XIML%WPDMAO`X1L0UO_tmb](https://github.com/user-attachments/assets/d6f38d69-7181-43bf-bb4d-56dd41131701)

**Comment by Mwallx** [comment]
If this is a feature, please add related text in the compedium since I dont find it in corresponding entries.

**Comment by axatin** [comment]
Intentional, all purchase costs increase with the number of researched techs. Added it in the Civilopedia.
