### ISSUE TITLE
CPU Freeze During England's Turn

### ISSUE THREAD

**Issue by iJuanHello** [LoneGazebo/Community-Patch-DLL#11241]
_1. Mod Version (X.Y.Z). Current Version: 4.15.2_

4.15.2

_2. DirectX Version_

11

_3. List of Other Mods_

VP Community Events (v8)
8a Enhanced Air Warfare 4vp
More unique components v88
Great Prophet Historical Names
Music Changer
Quick Turns
Sukitracts Civ 6 Style City Names
Sumer (CBP v24)

_4. Describe the Issue_

I can play my turn normally, but after ending it, the game begins processing England's turn before eventually freezing. Task Manager is unable to close the game when this happens, and you are forced to restart the pc.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Ahmad al-Mansur_0320 AD-1500.zip](https://github.com/user-attachments/files/16734946/Ahmad.al-Mansur_0320.AD-1500.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[BuilderEventLog_Kuala Lumpur.zip](https://github.com/user-attachments/files/16734949/BuilderEventLog_Kuala.Lumpur.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/user-attachments/files/16734959/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

End turn and wait for England.

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
Probably the same as #11220
