### ISSUE TITLE
Suggestion: Unit SelectionSound

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#1124]
I've assigned **SelectionSound** and **FirstSelectionSound** for new units.
https://www.dropbox.com/s/plaxqdyxqibqc4a/%282%29%20Community%20Balance%20Patch%20%28ver.1.1.14%29.zip?dl=0
Could you check whether it works or not?

-----Details-----
Cruiser: Battleship sound
Volley Gun: Cannon sound
Mercenaries: Infantry sound
War Elephant: Naresuan's Elephant sound
Explorer: Scout sound
Pioneer: Settler sound
Colonist: Settler sound

**Comment by LoneGazebo** [comment]
Yeah, I'll give it a go!
