### ISSUE TITLE
CTD when loading ~860+ turn save

### ISSUE THREAD

**Issue by chu-ko-nu** [LoneGazebo/Community-Patch-DLL#11251]
**1. Mod Version**
4.15.2 and 43 CIV with EUI

**2. DirectX Version**
DX 10 & DX 11

**3. List of Other Mods**
- Wonder Race https://steamcommunity.com/sharedfiles/filedetails/?id=656292791
- Calypso's Colored Religious Icons (Basic) https://steamcommunity.com/sharedfiles/filedetails/?id=117064727
- Calypso's Colored Religious Icons (Extended) https://steamcommunity.com/sharedfiles/filedetails/?id=135423316
- Calypso's Colored Religious Icons (BNW Extended) https://steamcommunity.com/sharedfiles/filedetails/?id=162076842

**4. Describe the Issue**
Whenever I load a save of my lategame Denmark run, the game CTD's before the save is finished loading. Older saves of about 10-20 turns back do work. I have already overwritten some of the newer autosaves by loading an older save and then taking some different decisions, but when I load a new save it still CTD's.

**5. Save Game**
I have included two autosaves, the old one seems to sometimes load, the latest one CTD's.
[AutoSave_0855 AD-1836.zip](https://github.com/user-attachments/files/16816474/AutoSave_0855.AD-1836.zip)

**6. Logs**
[Logs2.zip](https://github.com/user-attachments/files/16816496/Logs2.zip)

**7. CvMiniDump.dmp File**
[CvMiniDump.dmp](https://github.com/user-attachments/files/16816396/CvMiniDump.dmp)

**8. Steps to reproduce the Issue**
Load the latest autosave.

**Comment by chu-ko-nu** [comment]
It is hard to tell if the CTD is random or not, I could load one of the autosaves earlier and continued playing until late in the evening. Then I saved, but this morning that save crashed on me thrice, but I could load the autosave from the turn before.
Here are both saves
[Harald Bluetooth_0875 AD-1856.zip](https://github.com/user-attachments/files/16824439/Harald.Bluetooth_0875.AD-1856.zip)

**Comment by axatin** [comment]
This is a memory issue, nothing we can fix. The combination of 43 Civs, EUI and marathon speed might be too much for the game

**Comment by chu-ko-nu** [comment]
> This is a memory issue, nothing we can fix. The combination of 43 Civs, EUI and marathon speed might be too much for the game

Thanks! Too bad nothing can be done.
