### ISSUE TITLE
CTD every game (later eras)

### ISSUE THREAD

**Issue by Tarzan737** [LoneGazebo/Community-Patch-DLL#11259]
_1. Mod Version (X.Y.Z). Current Version: 4.15.2_

4.15.2

_2. DirectX Version_

_3. List of Other Mods_

Advanced air units mod v13
Giant Death robot eraser v1
Global 2 units per fort
Hex conquer VP v4
Improvement airbases V12
Quick turns V10
Really advanced setup V15
Remove Xcom squad V1
Self propelled Artillery V1
Edit unit names V1
subs ignore borders V3
world congress reformation v12

_4. Describe the Issue_

CTD after some turn in savegame. I upload all my mods except advanced air units because of size (i know the original air units mod have som error lines like assult instead of assault but it is fixed in my version)
i also upload the save and logs

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
[files to github.zip](https://github.com/user-attachments/files/16834850/files.to.github.zip)

**Comment by skodkim** [comment]
Seems connected with this https://github.com/LoneGazebo/Community-Patch-DLL/issues/11282

As I wrote on that post my game also starts crtaching upon entering the Medieval era.

**Comment by skodkim** [comment]
Just did a test where I first continued the game as normal from a save at the end of the turn before I get a CTD. This resulted in a CTD. 

Then I reloaded and used IGE to remove all Classical Era techs from the Civ that was causing me issues (in my last two games where I CTD's on both this was the last player in the array) and then I had no CTD. 

I'll se if I can do some more testing if it helps.
