### ISSUE TITLE
Broken unit movement

### ISSUE THREAD

**Issue by Nunuyz** [LoneGazebo/Community-Patch-DLL#1125]
**Copy-pasted from thread on the forums:**

Edit 4: Forgot about the Bug Reports thread, sorry!

http://imgur.com/a/MVyZk

Turn 245: Tried attacking weakened Spearman with Crossbowman. Moved northwest onto my other Crossbowman.

Turn 246: I think I tried moving back to the square to the southeast (might have tried to attack the adjacent Spearman) and ended up with... that.

Also, something similar happened a few times earlier - every time during this war, I believe. Crossbowman would run from that same zone northwest of Mecca to around southeast of Medina, iirc.

Note: has only happened (I'm pretty sure) with Crossbowmen (as in, ranged units).

Mods: 1.1.14 plus http://i.imgur.com/pcOrx93.jpg

Edit: Happened again; on 246, attacked adjacent Spearman. The other Crossbowman moved to the southeastern tile. Tried to attack with that one from its new/old tile. Teleported.

Edit 2: I think it's a particularly stupid Crossbowman. Happened in a different way this time when trying to attack the Spearman on the Marsh on 245. Ended up on the Town southwest of Mecca.

Edit 3: Nope. Not just the one unit.

**Comment by LoneGazebo** [comment]
This was reported and is resolved, will be addressed in an upcoming beta. Thanks!
