### ISSUE TITLE
[1.1.14] No barbarians in scenario

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#1126]
It seems there's a problem with scenarios in the 1.1.14 version.

I just did some testing comparing a scenario I usually use with CPP and one that the CivFanatics user "SgtCiv" uploaded (which he reported has barbarians using the 1.1.14 version):

* SgtCivs scenario loads with barbarians
* My scenario loads without barbarians
* If I create a new scenario using all my regular mods the scenario starts without barbarians
* If I create a new scenario using only the mods below (CPP mods without More luxuries, version 1.1.14) the scenario starts without barbarians

Mod list:
Sid Meier's Civilization 5\Mods\(1) Community Patch\
Sid Meier's Civilization 5\Mods\(2) Community Balance Patch\
Sid Meier's Civilization 5\Mods\(3) CSD for CBP\
Sid Meier's Civilization 5\Mods\(4) Civ IV Diplomatic Features\
Sid Meier's Civilization 5\Mods\(6a) Community Balance Patch - Compatibility Files (EUI)\

It *seems* to me that the culprit here is somewhere in the CPP. I had opened my regular scenario with version 1.1.14 loaded, made some changes and saved the file - maybe that's why my scenario doen't work while SgtCiv's does?

Newly created scenario with only the mods listed above active attached to post.

This has been posted on CivFanatics as well.

Hoping for a solution!

\Skodkim

[AAA_2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/94915/AAA_2.zip)

**Comment by skodkim** [comment]
Just checked and I don't see a player called 'Crom' in the Firetuner when I load the scenario. All I see is myself, ther major civs and city states (and of course n/a).

\Skodkim

**Comment by skodkim** [comment]
Wait a minute. When I look in the Players panel of the firetuner I see no Crom, however the Players list of the Map panel of the Fire Tuner I'm able to place 'Crom units', e.g. barbarian units.

\Skodkim

**Comment by skodkim** [comment]
FYI I just tried loading a scenario with 1.1.20 beta and the result is the same; No barbarians.

This scenario has never been saved with the new CPP versions active so I guess that ruins the theory of CPP somehow corrupting the scenario when saving.

\Skodkim

**Comment by LoneGazebo** [comment]
I haven't had a chance to look at it yet, sorry. Hope to do so soon.
G

**Comment by skodkim** [comment]
Fine - just wanted to keep you updated on my findings to help you (and thereby speed up the process :smiley: )

\Skodkim

**Comment by skodkim** [comment]
Just wanted to make a plea with you not to forget about this bug. Been following the thread lately and unfortunately it seems it hasn't been fixed yet.

\Skodkim

**Comment by LoneGazebo** [comment]
Patience, grasshopper.

**Comment by LoneGazebo** [comment]
Test the CP in this folder for me and report back. Seems to be working on my end now: https://mega.nz/#F!2c8UUDQK!44DLtvHQRZcwyPFqcMBe8g

**Comment by skodkim** [comment]
Just did an install og CPP 1.1.23 using the full installer and replaced CP with the one you provided above. I played 5- turns on my scenario map to test and unfortunately it doesn't work on my end. Checked that the cache libeary had actually been deleted before starting Civ and it had.

I noticed a couple of errors in lua.log so I've uploaded the logs along with my scenarion and a screen shot of a barb free map

Thank you so much for looking into it and my apologies for being such an impatient litte grasshopper :smiling_imp: Let me know if theres anything I can do to help - I plan to do some serious Civ'ing when possible so just say the word!

\Skodkim

![civ5screen0003](https://cloud.githubusercontent.com/assets/6018459/12584218/c40180f4-c446-11e5-9d62-6fff0b4593e7.jpg)

[Barb_bug_20160126.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/105096/Barb_bug_20160126.zip)

**Comment by LoneGazebo** [comment]
That scenario map looks completely different from the one you linked me.

G

**Comment by skodkim** [comment]
Yes, this is (one of the scenarios that I usually use, while the last one was one created just for the test .

Is this important (shouldn't it generally work..?).

Should I test with the other one?

\Skodkim

**Comment by LoneGazebo** [comment]
The problem, as far as I can tell, is that the 'observer' is being assigned a position in the game, thus the fact that the observer can see all tiles makes barbs not spawn. In the DLL above, I set it to ignore the observer, but it seems that it is still doing that for you. Not sure why. Are you using IGE to look at stuff, or the firetuner?

**Comment by skodkim** [comment]
I'm using the fire tuner (for the tests, have been using ige at other times)

\Skodkim

On 26. jan. 2016 18.21.15 CET, LoneGazebo <notifications@github.com> wrote:
>The problem, as far as I can tell, is that the 'observer' is being
>assigned a position in the game, thus the fact that the observer can
>see all tiles makes barbs not spawn. In the DLL above, I set it to
>ignore the observer, but it seems that it is still doing that for you.
>Not sure why. Are you using IGE to look at stuff, or the firetuner?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LoneGazebo/Community-Patch-DLL/issues/1126#issuecomment-175126673

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by skodkim** [comment]
Just a thought but could it be somehow related to which team numbers are used in the scenario? Afaik barbarians are always number 22 so I'm always careful to not use that for a player.

\Skodkim

On 26. jan. 2016 18.21.15 CET, LoneGazebo <notifications@github.com> wrote:
>The problem, as far as I can tell, is that the 'observer' is being
>assigned a position in the game, thus the fact that the observer can
>see all tiles makes barbs not spawn. In the DLL above, I set it to
>ignore the observer, but it seems that it is still doing that for you.
>Not sure why. Are you using IGE to look at stuff, or the firetuner?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LoneGazebo/Community-Patch-DLL/issues/1126#issuecomment-175126673

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by LoneGazebo** [comment]
Well, the first scenario you linked me works (and worked) for producing barbs with my fix. So link your actual scenario when you have a chance and I'll see why it differs.

**Comment by skodkim** [comment]
I linked that in the post from about an hour ago (the one with the image).

\Skodkim

On 26. jan. 2016 18.48.42 CET, LoneGazebo <notifications@github.com> wrote:
>Well, the first scenario you linked me works (and worked) for producing
>barbs with my fix. So link your actual scenario when you have a chance
>and I'll see why it differs.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LoneGazebo/Community-Patch-DLL/issues/1126#issuecomment-175139370

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by LoneGazebo** [comment]
Thanks.

**Comment by skodkim** [comment]
Just wanted to say that I've been experimenting with creating a new scenario todag and so far it works when I use that on.

I have no idea, why it doesn't work when I use the other one, but I'll see if I get a chance to test it again.

\Skodkim

**Comment by skodkim** [comment]
This is really weird. I've been creating a new scenario with CPP 1-25b loaded and it worked fine (barbarians on map). 

Today I switched to version 1-29b (used autoinstaller), started a new game and they were gone!

I checked several times but there was no barbarians with 1-29b. Afterwards I tried switching back to 1-25b and they appear on the map again, tried 1-29b once more and they're gone again, ...

I'm including the scenario here. I have no idea what's going one but I hope you get this squashed!

[A_JHW_Map_v11_05.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/110996/A_JHW_Map_v11_05.zip)

\Skodkim

**Comment by skodkim** [comment]
Just noticed that CBP says version 1-23 while CP is version 1-25b (probably the version you uploaded for me to test five days ago). Thats for the mod combp that seems to work right now.

\Skodkim

**Comment by LoneGazebo** [comment]
I stated that I had removed the 'fix' for that until I had a better one.

**Comment by LoneGazebo** [comment]
(stated this in patchnotes)

**Comment by skodkim** [comment]
Are you sure you implemented the fix again for the 2-1 Beta? Just tried it with my newly created scenario and I have no barbarians on the map (see below) :disappointed: 

Map was attached a couple of posts up.

I'll see if I can do some more testing today, e.g. try with the CPP version you uploaded here earlier.

![civ5screen0023](https://cloud.githubusercontent.com/assets/6018459/12740240/a79dbc40-c971-11e5-83d5-345cdabcfe02.jpg)

\Skodkim

**Comment by LoneGazebo** [comment]
Yep, definitely implemented fix, and definitely tested it to see if it worked (and it did).

**Comment by skodkim** [comment]
Just did some more testing and it definately does not work for me with v2-1b - no other mods involved.

What I did:
1. Did a clean install of 2-1b
2. Loaded scenario (tried two different ones) and played five turns
3. Used the fire tuner to "Refresh/Reveal Map" ->**no** barbarians 

I then tested with 1-25b:
1. Did a clean install og 1-23b and overwrote CP with the 1-25b version you posted earlier in this thread
2. Loaded scenario (tried two different ones) and played five turns
3. Used the fire tuner to "Refresh/Reveal Map" ->barbarians

I'm including the two scenarios in this post (you've seen at least one of them before). Let me know if there's anything I can do to help!

\Skodkim

[Maps.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/113541/Maps.zip)

**Comment by skodkim** [comment]
It seems to work now. I have barbarians in my scenario! :smile: 

Thank you very much G - I don't know why it didn't work with 2-2b while it does with 5-2b but it does.

\Skodkim

**Comment by LoneGazebo** [comment]
Not sure - the fix was in in the 2-2b version, but hey, whatever works.

**Comment by skodkim** [comment]
Yeah. Just a thought (not a programmer but I've worked along them for some years testing code) - could it be some kind of variable that's not being cleared properly? It seems to me that it depends on "the other code".

But hey, it works and I'm happy. Just hope it doesn't return any time soon.

\Skodkim

On 5. feb. 2016 19.43.11 CET, LoneGazebo <notifications@github.com> wrote:
>Not sure - the fix was in in the 2-2b version, but hey, whatever works.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LoneGazebo/Community-Patch-DLL/issues/1126#issuecomment-180493842

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by LoneGazebo** [comment]
It was the observer causing the problem, but I fixed it in 2-2B. Anyways, all's well that ends well.
