### ISSUE TITLE
Hand Axes upgrade to Knights

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1127]
(Playing as The Huns)

Is this intentional? I feel like this might be intentional for reasons that have to do with barb-spawning which after all is the actual point of the Hand Axe. I mean, the civpedia says they are a Chariot Archer replacement, so in that sense it makes sense they go through the horse class. But it feels odd, so I thought I'd put a quick thing on it, and if its intentional or too hard to change, obvi just ignore.

Also, Brutes are WAY more expensive to make Spearmen than Warriors. Basically dead units at that point, no matter the promotions gained.

**Comment by TechpriestEnginseer** [comment]
Let's just say if you want an army of uncivilized ruthless barbarians to become disciplined spearmen. It's going to cost more presumably..

**Comment by LoneGazebo** [comment]
I'll make them upgrade to comp bowmen.

And yeah, brutes are expensive by design.
G
