### ISSUE TITLE
Player:GetNationalPopulation()

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1128]
Basically count up all of your cities' population and return them as an integer, so basically like the national wonder's requirement of having a national population threshold. I'm doing a function on where units are unlocked after the player reach a certain national population.

If it does exist, redirect me to where it is there.

**Comment by LoneGazebo** [comment]
Use 'GetCurrentTotalPop()'

**Comment by TechpriestEnginseer** [comment]
I was actually looking for 'GetTotalPopulation() as that function doesn't detect puppeted population.
