### ISSUE TITLE
Denounce dialog option

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#1129]
When you discuss with another leader the discuss button is empty (has no text). Works properly however.

**Comment by LoneGazebo** [comment]
Version and mods?

**Comment by AnastaseAlex** [comment]
Clean install of civ V and community patch with the auto installer, nothing else.

**Comment by LoneGazebo** [comment]
Latest version?

**Comment by AnastaseAlex** [comment]
yep

**Comment by TechpriestEnginseer** [comment]
I can confirm this. I've ignored it because it seems to work properly, just missing the text.

**Comment by LoneGazebo** [comment]
Ah fixed.
