### ISSUE TITLE
[Bug] passable fort (whoward's minimod) is not recognize by trade routes

### ISSUE THREAD

**Issue by wileyhk2001** [LoneGazebo/Community-Patch-DLL#113]
Problem:
Trade routes doesn't recognize the water channel opened up by passable fort (whoward's minimod).

How it happened:
In my game I have this huge peninsula blocking my trade route so I build a citadel so that the ships can sell through. But the cargo ships don't seem to recognize it.

**Comment by LoneGazebo** [comment]
Unfortunately the path generator would have to be re-written to allow for this, as the method employed in this minimod does not affect the path finder. Sorry.
G
