### ISSUE TITLE
Citry State diplomacy bug

### ISSUE THREAD

**Issue by Vantucci27** [LoneGazebo/Community-Patch-DLL#11302]
_1. Mod Version (X.Y.Z). 
Current Version: 4.16.0_ (but ingame says v. 138) not sure what that means
VP EUI without compatibility mods enabled (they break my game).

_2. DirectX Version_
10/11

_3. List of Other Mods_
Smart AI (v .3)
disable world congress (v .2)
(2) Vox Populi (v. 17)
(4d) Squards for VP (v. 1)

_4. Describe the Issue_
From the start of my first game with the newest version, City State diplomacy gifts are bugged.  All three options are 0g for 5 influence.  They continually work as well as you can see from be being an ally already.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
I attached last save
[Ramesses II_0018 BC-3280.zip](https://github.com/user-attachments/files/17170618/Ramesses.II_0018.BC-3280.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[CivLogs.zip](https://github.com/user-attachments/files/17170605/CivLogs.zip)

_8. Steps to reproduce the Issue (Optional)_
choose a city state, all give 5 influence for 0g.

_9. Screenshots of the Issue (Optional)_
![CityState](https://github.com/user-attachments/assets/956c03a5-3b07-48f9-a9c0-ad21f4b99a4e)

**Comment by bsesar** [comment]
Maybe a mod conflict? Disable world congress seems sus. Have you tried without it? Same with Smart AI.

**Comment by axatin** [comment]
Yes, both mods are incompatible with VP.

**Comment by Vantucci27** [comment]
> Yes, both mods are incompatible with VP.

Ah ok.  Thanks.
