### ISSUE TITLE
CTD during AI turn

### ISSUE THREAD

**Issue by Noire-Black-Heart** [LoneGazebo/Community-Patch-DLL#11313]
Mod version 4.16, EUI non-43 CIV VP

Other mods used: 
(7a) VP Events Overhaul (Expansion Pack system) (v 2.1)
(9d) Reforestation for VP v.5
(game) Capture+++ (v 5)
(overhaul) More Unique Components for VP (v 88)
(overhaul) More Wonders for VP
(text) Promotion Overhaul for VP
(overhaul) Unique City States for VP
(ui) City-States Leaders for VP
(ui) Commander Influence Borders (v 3)
(ui) List Enhancements for VP
(ui) Small Resource Icons for MW (v 5)
(ui) Trade Opportunities for VP
(ui) Wonder Planner For VP
Better Lakes for Vox Populi (v 2.5)
InGame Editor+ (v 46)
Jarcast's Cities of Marble for VP (v 2)
Jarcast's Volcanoes for VP (v 6)
New Beliefs Mods
Quick Turns (v 10)
Really Advanced Setup (v 15)
UI - Promotion Tree for VP
Wonder Race (v 7)

The game CTD during AI Polynesia turn at turn 136, after he prompt for an open border treaty. 

______________________________________________________________________________________

TO reproduce the issue, simply pass turn 136 with any action. 
[Logs (2).zip](https://github.com/user-attachments/files/17242194/Logs.2.zip)

**Comment by Noire-Black-Heart** [comment]
After reading other CTD issues, I decided to put a test on my issue. With IGE I noticed Polynesia is 1 tech from medieval era on turn 136, so I used IGE and give him all classical era techs on turn 134. On his turn the game crashed right away.

**Comment by Noire-Black-Heart** [comment]
Here is the mods I'm using, all packaged just in case it could ease the debugging process. 

https://pixeldrain.com/u/ntkjwGiH

**Comment by axatin** [comment]
seems to be the same as https://github.com/LoneGazebo/Community-Patch-DLL/issues/11292#issuecomment-2381457896, should be fixed now
