### ISSUE TITLE
CTD at the beginning of player's turn

### ISSUE THREAD

**Issue by Noire-Black-Heart** [LoneGazebo/Community-Patch-DLL#11318]
Mod version 4.16.2, EUI non-43 CIV VP

This game is started in 4.16 and updated to 4.16.1 then 4.16.2 midgame. 

Other mods used:
(7a) VP Events Overhaul (Expansion Pack system) (v 2.1)
(9d) Reforestation for VP v.5
(game) Capture+++ (v 5)
(overhaul) More Unique Components for VP (v 88)
(overhaul) More Wonders for VP
(text) Promotion Overhaul for VP
(overhaul) Unique City States for VP
(ui) City-States Leaders for VP
(ui) Commander Influence Borders (v 3)
(ui) List Enhancements for VP
(ui) Small Resource Icons for MW (v 5)
(ui) Trade Opportunities for VP
(ui) Wonder Planner For VP
Better Lakes for Vox Populi (v 2.5)
InGame Editor+ (v 46)
Jarcast's Cities of Marble for VP (v 2)
Jarcast's Volcanoes for VP (v 6)
New Beliefs Mods
Quick Turns (v 10)
Really Advanced Setup (v 15)
UI - Promotion Tree for VP
Wonder Race (v 7)

The game CTD at the beginning of player's turn at turn 170, loading autosave on that turn (turn 169 autosave)causes immediate crash

To reproduce the issue, simply pass turn 169 with any action, or loading autosave on turn 169.
[log_dump_save.zip](https://github.com/user-attachments/files/17278557/log_dump_save.zip)

dump says null_class_ptr_read_c0000005 at civ5_dx11.exe

**Comment by Noire-Black-Heart** [comment]
https://pixeldrain.com/u/ntkjwGiH

Again, here are all the modmods I've been using.

**Comment by Noire-Black-Heart** [comment]
Update: I had another plain new game on 4.16.2, and I deleted many possibly outdated mods. The new game crashed on 140 turn as player turn starts, and loading autosave 139 will crash immediately right as the loading image begin to fade. Same behavior as above. 

Other mods used:
(7a) VP Events Overhaul (Expansion Pack system) (v 2.1)
(overhaul) More Unique Components for VP (v 88)
(overhaul) More Wonders for VP
(text) Promotion Overhaul for VP
(overhaul) Unique City States for VP
InGame Editor+ (v 46)
Jarcast's Cities of Marble for VP (v 2)
Jarcast's Volcanoes for VP (v 6)
New Beliefs Mods
Really Advanced Setup (v 15)
UI - Promotion Tree for VP
Wonder Race (v 7)

[log save dump.zip](https://github.com/user-attachments/files/17303003/log.save.dump.zip)

This time the dump file says the crash happened at CvGameCore_Expansion2.dll, the same NULL_CLASS_PTR_READ_c0000005_CvGameCore_Expansion2.dll crash.

**Comment by azum4roll** [comment]
Autosave 139 should be turn 140 player's turn, so they should be the same cause.

**Comment by Noire-Black-Heart** [comment]
After a few more games of testing, I can pinpoint the CTD issue is from the mod (7a) VP Events Overhaul (Expansion Pack system) (v 2.1). Playing without this mod gives no CTD at least until Atomic era.
