### ISSUE TITLE
For some reason the game keeps CTD during AI turn, citing a driver error

### ISSUE THREAD

**Issue by enbyenergyyy** [LoneGazebo/Community-Patch-DLL#11315]
4.14.1, Full version (EUI, 43 CIV, Vox Populi)
DX 10 & 11
No additional mods
Randomly crashes during AI turn when playing as Korea, cites driver/rendering issues. Issue never occurred before current game with Korea.
Sorry, I keep autosaves on, but I can't find them in the saves for some reason.
Sorry, no logs available.
[CvMiniDump.dmp](https://github.com/user-attachments/files/17268480/CvMiniDump.dmp)
Sorry, don't have any idea how to reproduce this, just the fact that I was playing as Korea.
![Screenshot 2024-09-07 162433](https://github.com/user-attachments/assets/0572554c-4460-48f2-b9d4-7936aae60c33)

**Comment by axatin** [comment]
This is a common issue which has nothing to do with VP, see for example https://forums.civfanatics.com/threads/lets-fix-renderer-error-once-and-for-all.532842/. We can't fix it.

You can try the steps mentioned in the forum post. Also, the usual steps to fix graphics-related issues might help, which are:
- turn off yield icons
- don't zoom out as far as possible
- don't use EUI
