### ISSUE TITLE
Trait_LitYieldChanges and Great General Points

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#11312]
In a modded civ I've used the Trait_LitYieldChanges table to add a Great General Point.
The UI registers this, displaying it in all the relevant places.
However, at the end of each turn, the Great General Point pool (as displayed in military overview) does not update.

So it seems somewhere there is a broken connection or a loop that doesn't go over all the yields possible.
Maybe this bug also exists in other places?

**Comment by azum4roll** [comment]
As with most yield loops, yields after YIELD_GOLDEN_AGE_POINTS are skipped unless BALANCE_CORE_JFD is on.

**Comment by Hokath** [comment]
Alright I will enable the BALANCE_CORE_JFD option

For my own edification -- how do you go about finding this exact loop that is giving the problem? I.e. how would you personally find it starting from this web page. I seem to have pretty hit-or-miss luck finding things in the DLL :(

**Comment by axatin** [comment]
> Alright I will enable the BALANCE_CORE_JFD option
> 
> For my own edification -- how do you go about finding this exact loop that is giving the problem? I.e. how would you personally find it starting from this web page. I seem to have pretty hit-or-miss luck finding things in the DLL :(

Basically the approach is to search for the column/table name in the dll and see what it's used for. You can find Trait_LitYieldChanges in
`kUtility.SetYields(m_piLitYieldChanges, "Trait_LitYieldChanges", "TraitType", szTraitType);`
which means that the database entries are saved in a variable `m_piLitYieldChanges`. If you search for that, you'll find a function GetLitYieldChanges, and that it called in CvCity::GetYieldFromGreatWorks. From there we go to GetBaseYieldRateFromGreatWorks and then to getBaseYieldRate. It's a nice rabbit hole. At the end we arrive at CvCity::getYieldRate and CvCity::getYieldRateTimes100, which are called in various places depending on the yield type.

For example player-wide faith is updated in CvReligionClasses, Gold is updated in CvTreasury and so on. For great generals we can find
`iGreatGeneralPoints += pLoopCity->getYieldRate(YIELD_GREAT_GENERAL_POINTS, false);` in CvPlayer line 23969.
So great general points from cities being added to the pool is implemented and it should work, and we need to do debugging to understand why it does not.

**Comment by Hokath** [comment]
Great, thanks.
So my method was correct, it just seems like some .cpp files are too big to be indexed by the github search -- need to search the files on the computer itself, not the internet.

The reason we have these stops on the loops with MOD_BALANCE_CORE_JFD is presumably just to save the time of not checking those extra 3 or 4 indices, I presume?

**Comment by axatin** [comment]
yes, git search is unreliable, you need to search within files locally. and you're right, the yields are skipped for performance reasons.

**Comment by azum4roll** [comment]
I use VSCode's workspace search (with Match Whole Word option on). If it's a way too common name like `GetYieldChanges`, I use Find All References from context menu instead (need a configured C++ compiler in this case).

**Comment by Hokath** [comment]
https://forums.civfanatics.com/threads/afghanistan-for-vp.689898/post-16686922

Jarcast did more digging, please see above post
