### ISSUE TITLE
4.16.2 Governor tile selection

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#11319]
Version 4.16.2

Governor has weird default focus tile selection (city is not a puppet) : 

![20241007183942_1](https://github.com/user-attachments/assets/cdd9d722-12ff-46a3-aa98-a13c0d7c00c7)

Mods : 4UC / RAS
Save : 
[Pachacuti_0129 BC-0775.zip](https://github.com/user-attachments/files/17281994/Pachacuti_0129.BC-0775.zip)

**Comment by axatin** [comment]
There are faith and gold yields on the pasture, so you have God of the Open Sky as Pantheon. Working the two grassland tiles gives 1 Faith, 1 Culture, which the governor sees as more valuable than 1 Food, 1 Prod (and I would agree with that).

**Comment by Zuizgond** [comment]
You're right, I forgot about the pantheon. Sorry for wasting your time. Issue can be closed. Thanks!

**Comment by Mwallx** [comment]
> There are faith and gold yields on the pasture, so you have God of the Open Sky as Pantheon. Working the two grassland tiles gives 1 Faith, 1 Culture, which the governor sees as more valuable than 1 Food, 1 Prod (and I would agree with that).

My current run had some turns puppets put all the citizens on pillaged tiles with yield like around 3 food, ignoring tiles with 8 or 9 food. I can provide saves if necessary.

**Comment by axatin** [comment]
yes I‘d need a savegame to investigate it

**Comment by Mwallx** [comment]
> yes I‘d need a savegame to investigate it

![image](https://github.com/user-attachments/assets/6deb3ca7-40c0-42da-bcc7-c1a349851b8c)

[saves.zip](https://github.com/user-attachments/files/17647554/saves.zip)
