### ISSUE TITLE
governor fail

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#11329]
started a game with v 4.15 but my enjoyment was cut short when the governor started sabotaging my city growth. this used to work better.

![image](https://github.com/user-attachments/assets/661997c9-f9c7-4997-bf33-5a8cb1ed8e20)

**Comment by bsesar** [comment]
I think some issues with the governor have been fixed in 4.16. Have you tried v4.16.2?

**Comment by azum4roll** [comment]
Hmm, was the code that forces cities to have a certain amount of growth removed?
