### ISSUE TITLE
Worker actions and manufactory problem

### ISSUE THREAD

**Issue by Punklife** [LoneGazebo/Community-Patch-DLL#11322]
_1. Mod Version (X.Y.Z). Current Version: 4.16.2_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_
 Worker offering all special improvements for construction. Manufactory does not connect resources. 

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[Montezuma_0065 BC-0400.zip](https://github.com/user-attachments/files/17316934/Montezuma_0065.BC-0400.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/user-attachments/files/17316935/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![main_full](https://github.com/user-attachments/assets/6fccd3d7-302e-4e39-a0fd-a348e6216a0f)

**Comment by Punklife** [comment]
[Montezuma_0065 BC-0400.zip](https://github.com/user-attachments/files/17316961/Montezuma_0065.BC-0400.zip)

**Comment by azum4roll** [comment]
Try reinstalling VP.

**Comment by Punklife** [comment]
@azum4roll It solved the issue with the worker but the manufactory still doesn't connect the resources.

**Comment by Punklife** [comment]
> @azum4roll It solved the issue with the worker but the manufactory still doesn't connect the resources.

Yeah, there was a conflict in the changes I made in VP. I'm careful to check which files you changed in the update but this time it went through and I can't find the error. I changed everything again by hand but I couldn't find the conflict. However, it worked. Thanks anyway.
