### ISSUE TITLE
4.16.2 Puppet cities don't reset tiles

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#11334]
Puppet cities tile selection seems to be stuck and do not reset.

The only way to reset tiles is to annex the city.

![image](https://github.com/user-attachments/assets/abb26c6c-c351-4754-8abf-1791b3a48da6)

Mods : 4UC, RAS

[Pocatello_0353 AD-1665.zip](https://github.com/user-attachments/files/17451481/Pocatello_0353.AD-1665.zip)

**Comment by axatin** [comment]
That's intentional, it shouldn't not possible to make any kind of changes to tile selection in puppet cities
