### ISSUE TITLE
LUA error when generating map

### ISSUE THREAD

**Issue by calloatti** [LoneGazebo/Community-Patch-DLL#11332]
_1. Mod Version (X.Y.Z). Current Version: 4.16.2_

4.16.2

_2. DirectX Version_

_3. List of Other Mods_

Really Advanced Setup (v 15)

_4. Describe the Issue_

Game crashes when generating map "Ring for VP" (Huge) when adding more than 12 players with "Really Advanced Setup"
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

![image](https://github.com/user-attachments/assets/d638ca50-16cc-4ee5-8ff8-f84fd8dd9f61)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Select map "Ring for VP" (Huge), add 16 players, no city states with "Really Advanced Setup", game crashes, probably due to LUA error, see lua.log screenshot above.

If only using up to 12 players, it works and game loads map.

_9. Screenshots of the Issue (Optional)_

**Comment by azum4roll** [comment]
Yes, the map only works up to 12 players. It's by Firaxis design and I'm not putting effort to add more player support.

**Comment by calloatti** [comment]
It was right there in the ring.lua file comments, sorry for not checking first.

![image](https://github.com/user-attachments/assets/ec07f95b-8fca-4cb6-8700-06f43d625edf)
