### ISSUE TITLE
No notification for destroyed garrison

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1133]
I've noticed this since the change to garrisons but only just remembered to open an issue on it. I use EUI so I have no idea if it's specific to that, but I'm not getting notifications.

On a side note, this probably isn't the place to ask but what is the intended use of garrisons now that they are destroyed during a siege? Are garrisons no longer supposed to be used...should units be kept outside of the city instead?

**Comment by LoneGazebo** [comment]
They boost city defense and absorb hits that would otherwise go the city itself.

**Comment by LoneGazebo** [comment]
Ilteroi, did you add a notification to the unit destruction event for garrisons?

**Comment by ilteroi** [comment]
not that i know of. but the regular notification should work as before.

**Comment by ilteroi** [comment]
i have to correct myself: turns out no post-combat processing was done at all if a garrison is killed. e.g. no yield from kills either. needed a bit of work.

note: garrisons can not be captured.

**Comment by LoneGazebo** [comment]
Cool, let me know if I can help.

**Comment by ilteroi** [comment]
no biggie. fix is pushed
