### ISSUE TITLE
God of the Expanse pantheon does not give 25% border growth 

### ISSUE THREAD

**Issue by mt-empty** [LoneGazebo/Community-Patch-DLL#11348]
_1. Mod Version (X.Y.Z). Current Version: 4.16.2_

4.16.2

_4. Describe the Issue_

No 25% border growth after adopting the pantheon

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

1. Take note of border growth before adopting the pantheon
2. Adopt the God of the Expanse pantheon
3. Compare with step one 

_9. Screenshots of the Issue (Optional)_
Same city Before and after adopting the pantheon
![image](https://github.com/user-attachments/assets/ab2426dc-0f68-4b4f-9ef2-265197b1f0a9)

![image](https://github.com/user-attachments/assets/b7ccb7ef-0ddc-47ce-b31d-df71f2efd57e)

**Comment by azum4roll** [comment]
1 + 25% is 1.25, rounded down to 1.

**Comment by mt-empty** [comment]
@azum4roll , It's not a rendering float limitation.

If my understanding is correct, God of Expanse is meant to increase tile acquisition by 25%, for example: from 20 turns to 15 turns when starting a fresh game:

Detailed steps to reproduce the Issue
1. start a new standard speed game as **India**, because of their ability to start with Pantheon
2. settle a city and take note of border growth before adopting the pantheon(it should say that you will get a tile by turn 20)
3. Adopt the God of the Expanse pantheon, you might expect to acquire a new tile by turn 15, however you won't actually acquire one until turn 20

**Comment by azum4roll** [comment]
Nah, your understanding is just not correct.
