### ISSUE TITLE
strategic resources locked but tradeable and useable

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#1134]
Hi
happen on 1.14 (i think)
I Built "Fuels Corp".
After that, i had 3 fuel & 3 uranium that i could trade and use to build plane even if i didn't have biology nor atomic theory.
Also, they don't show up in the main ui bar. (with EUI)

**Comment by LoneGazebo** [comment]
That's because you have to have the tech for them to actually have them 'show up' elsewhere. This is normal.
