### ISSUE TITLE
Boarding Party promotion uses faulty description when attacking

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#11359]
_1. Mod Version (X.Y.Z). Current Version: 4.16.2_

4.16.2

_2. DirectX Version_

_3. List of Other Mods_

A lot but I checked for the text and promotion text tags and only this mod seems to alter them

_4. Describe the Issue_

When a naval unit having the Boarding Party promotion attacks another unit the notification says "Your {1_Unit} is spreading plague!". Txt key is TXT_KEY_UNIT_PLAGUE_TRANSFER_S from CoreText_en_US.xml

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by azum4roll** [comment]
Caused by having JFD features enabled in one of your mods.
