### ISSUE TITLE
Incorrect Gold/Faith displayed when gold/faith insufficient to buy units/buildings/tiles in City View.

### ISSUE THREAD

**Issue by Klokinator** [LoneGazebo/Community-Patch-DLL#11374]
_1. Mod Version (X.Y.Z). Current Version: 4.16.2_

My version is 4.16.2 and I'm using the full mod with EUI and all subcomponents. I disabled the optional troop system, but the issue happens with or without it.

_2. DirectX Version_
I'm using DX 10 & 11.

_3. List of Other Mods_
I'm only using two other mods, and the issue is present with or without these mods. It exists in base VP with no other mods enabled.

The mods I'm using:
Larger Cities by dninemfive
Wonder Race by hambil and Cynther

_4. Describe the Issue_
Simple explanation: When purchasing tiles with gold, or units with faith/gold in the city screen, the display is entirely wrong if my gold is insufficient. If I have enough gold or faith to purchase something, it displays properly, but when I don't, the numbers appear to become totally random.

Quick screenshots:
![image](https://github.com/user-attachments/assets/367e4c39-8b88-4b17-9f06-bfacfb19fccf)

In this second image, I purchased a couple of tiles. Observe how the gold cost for units and buildings changed, and the incorrect price displayed for tiles I cannot afford.
![image](https://github.com/user-attachments/assets/5fa3e4f3-ce4a-4ee6-92c8-b569063469a7)

This issue is less pressing for tiles, since hovering over a tile shows me what it would cost, but the problem is that units and buildings do not, so I never know what the proper price is to buy units I cannot currently afford.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
I am including a save right before I make the purchase, and a save the turn before too.
[Saves.zip](https://github.com/user-attachments/files/17878908/Saves.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/user-attachments/files/17878923/Logs.zip)
Hopefully these logs help. I enabled them, then loaded into the game and purchased tiles until my money ran out.

**Comment by azum4roll** [comment]
Red = the amount of gold you lack for the purchase.

**Comment by Klokinator** [comment]
Ahhhh, I see, now. Does the base game do that? In any case, thank you for answering my issue.

**Comment by azum4roll** [comment]
It's an EUI thing.

76% is the ratio of production cost relative to the invest/purchase cost. The higher it is, the more efficient it is to invest instead of produce.

**Comment by Klokinator** [comment]
Thanks! That wasn't clear to me at all based on ingame context... but I also can't think of a single way to make that more obvious without cluttering the UI. So, it is what it is.
