### ISSUE TITLE
[0402] No "pledge to Protect" information in city state screen

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#114]
With version 0402 you get no pop up stating the benefits of pledging to protect a city state when you move the mouse over the "Pledge to Protect" button in the city state screen anymore.

![civ5screen0010](https://cloud.githubusercontent.com/assets/6018459/6078369/1fed2ec4-adf8-11e4-93ff-3e33eded9e00.jpg)

BTW I really like the new benefits! :thumbsup:

\Skodkim

**Comment by LoneGazebo** [comment]
This should work - using EUI or anything? I've checked this issue in 2-06, and it wasn't present.
G

**Comment by skodkim** [comment]
Yes, I am using EUI. Installed 1.25c and used your compatibility files. It may be a mod conflict. If so I'd appreciate if you could point me to the files used for the tool tip.

\Skodkim

**Comment by skodkim** [comment]
It seems it was in incompatibility issue with Whowards "Global - City States Gifts (v 4)" mod.

Sorry!!

\Skodkim
