### ISSUE TITLE
Forbidden palace giving 4 extra votes in WC

### ISSUE THREAD

**Issue by Stickerbrush** [LoneGazebo/Community-Patch-DLL#1140]
Out of all this project i am only using the community patch.

the mods i have installed (besides the CP) are:

-JFD'S mercenaries mod
-JFD'S republic of france
-JFD'S cultural diversity
-sukitrackt events and decisions
-Ethnic units 
-Global passable forts (i got the impression that the CP doesn't have this mod included but the CBP does?)

Anyway, this only started happening after i installed the CP so i can only assume it is the problem

**Comment by TechpriestEnginseer** [comment]
Depending on the number of current alive city-states, any building that give out city-state votes is multiplied. I've addressed this problem to Gazebo before. But, he made 
```ALTER TABLE Buildings ADD COLUMN 'SingleLeagueVotes' INTEGER DEFAULT 0;```
the <SingleLeagueVotes> tag which was what the old <ExtraLeagueVotes> did.

The solution to this would be to switch their functionality. Vanilla <ExtraLeagueVotes> would just give out 1 irregardless of city-states, whereas <SingleLeagueVotes>(it may be renamed) would give out multiplied votes.

**Comment by Stickerbrush** [comment]
so is gazebo gonna do something about this ? :S

**Comment by LoneGazebo** [comment]
Lack of scaling on the building was widely considered a bugfix when implemented a year ago. Not undoing that, sorry. The building's value was atrocious at mapsizes above standard, and this bugfix addressed that.
