### ISSUE TITLE
Problem with some of JFD's mods

### ISSUE THREAD

**Issue by Stickerbrush** [LoneGazebo/Community-Patch-DLL#1141]
i have been using this mod http://steamcommunity.com/sharedfiles/filedetails/?id=363003983&searchtext=the+republic+of+france from jfd and i noticed that the CP pretty much breaks the UA.

when i use the CP and this mod i can only bulb great generals for 0 culture (pretty sure it's not supposed to work like that). I would be really grateful if someone could fix it.

Also, something semi related is that i was just playing with jfd's mercenaries mod not too long ago and i noticed that the option to acquire a new mercenary contract was greyed out always even tho i had the money and mercenaries weren't banned on the WC. Not entirely sure if this is related to the CP but this has only happened when i have it installed. It's not something that always happens, but since i have had this happen at least twice i might as well post it here and see what happens

**Comment by TechpriestEnginseer** [comment]
I think it's related to Great People Change.
```Writers and Scientists now have their 'pop' values set at birth, instead of scaling while they exist (i.e., you can't effectively hoard them anymore) (CP)```

**Comment by LoneGazebo** [comment]
Contact JFD, not me, for mod conflicts, so that he can then ask me what he needs me to do to make it compatible as-is.

G
