### ISSUE TITLE
4.17.4 - 4.17.6 CTD upon eliminating another civ

### ISSUE THREAD

**Issue by subversiveasset** [LoneGazebo/Community-Patch-DLL#11416]
_1. Mod Version (X.Y.Z). Current Version: 4.17.4_

**4.17.4**

_2. DirectX Version_

**DX 11**

_3. List of Other Mods_

(1) Community Patch
(2) Vox Populi
(3a) VP - EUI Compatibility Files
(4a) Squads for VP
(7) VP Community Events (v 8)
(over) More Unique Components for VP (v 88)
JFD's Cultural Diversity - (1)(Core) Utilities (v 21)
JFD's Cultural Diversity - (2) (Art) Art Styles (v 1)
JFD's Cultural Diversity - (2)(Art) Splash Screens (v 1)
JFD's Cultural Diversity - (2)(Core) Mod Support (v 1)
JFD's Cultural Diversity - (2)(Gameplay) Starting Bonuses (v 1)
JFD's Cultural Diversity - (2)(Sound) Unit Dialogue (v 1)
JFD's Cultural Diversity  (Soundtrack)

_4. Describe the Issue_

Game crashes to desktop upon conquering final city of another player (in this case, Sweden, by taking final city with scout)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[QuickSave.zip](https://github.com/user-attachments/files/18088931/QuickSave.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/user-attachments/files/18088922/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump_20241210_205342_4.17.4_Release.zip](https://github.com/user-attachments/files/18089076/CvMiniDump_20241210_205342_4.17.4_Release.zip)

_8. Steps to reproduce the Issue (Optional)_

Take scout and conquer final Swedish city.

_9. Screenshots of the Issue (Optional)_

**Comment by altanom0** [comment]
I think it's still an issue

**Comment by subversiveasset** [comment]
> 4.17.6 has been released, please check to see if the issue persists as I don't have time to debug every save individually at the moment. @subversiveasset

Unfortunately, the game save still won't even open with this update so I cannot test if the issue is resolved.

should i try just a new game and trying to conquer a civ in that?

**Comment by subversiveasset** [comment]
OK, I was able to start a new game, and conquering an entire civ did not crash to desktop, so, I think this can be closed. (For the other players who were experiencing this, I guess it would probably make sense for you to have your own issue/thread?)
