### ISSUE TITLE
[1/23 -CBP] Religion can not be founded.

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#1143]
Turn 215 and there is still one religion to be founded when I get a Great prophet in my capital.
Press the button to found a religion and I pick my founder and follower beliefs but the Found Religion is inactive.
Since the End Turn button is now also inactive, it only allows me to found a religion, I am now stuck with no way to proceed.
[Elizabeth_0215 AD-1525.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/102265/Elizabeth_0215.AD-1525.zip)

**Comment by Kolaris8472** [comment]
Is there anything on the World Religions tab? I've noticed that despite 5 Religions being founded in my game it says "There are no World Religions" and it's blank.

**Comment by LoneGazebo** [comment]
I'll look, but that sounds like a mod incompatibility issue. What's your modlist?

**Comment by GrantSP** [comment]
Solved. For some reason there was no Pantheon belief selected. I could've sworn I chose one but I'm not going to be dogmatic about it. Anyway, it is simply a user error in not seeing it when I was founding the religion.
