### ISSUE TITLE
[4.17.6] No production from Chopping

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#11434]
_1. Mod Version (X.Y.Z). Current Version: 4.17.6_

4.17.6

_2. DirectX Version_

_3. List of Other Mods_

Tested without

_4. Describe the Issue_

Did choping forests change in 4.17? I don't seem to get the production boost I used to when one of my workers finish it. This also applies when funding cities on forest tiles.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by azum4roll** [comment]
Do you have Bronze Working?

**Comment by skodkim** [comment]
No, but forests should be with mining (right?) and I have that.

**Comment by brsoft1981** [comment]
You must have Bronze Working for production from chopping
![bw](https://github.com/user-attachments/assets/ee1a5b95-a030-4679-81ec-d6b5afb5329a)

**Comment by skodkim** [comment]
Sorry, it was on my end as I didn't know that the Production boost was tied to Bronze Working while the build was tied to Mining.

@brsoft1981 ; Which mod are you running to get those Tech tree info? I don't see them even though I use the EUI version of the mod.

**Comment by brsoft1981** [comment]
@skodkim I don't use any mods. Just Vox Populi with EUI.

**Comment by skodkim** [comment]
Aaah, I think I have another mod overriding that pop-up. Thx for the answer :-)
