### ISSUE TITLE
Hun UA/Dominance policy

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1144]
If the kill generated from clearing a barb camp finishes a tech, it somehow overrides the process and I wasn't getting the unit. This wasn't really a problem, I could change techs if necessary. But if its the same process for the AI, I would feel sad for AI Atilla and his missed early game units. Might not be the same process of course tho. EUI version if it matters. And, also, AI Atilla usually takes Progress for me (by the old flavors at least). I mean, main reason I picked Authority is to know where the barb camps are after all, and I think the AI already gets at least some bonus to that. So this might not matter at all.

**Comment by pandasnail** [comment]
forgot to mention this is with the 1/14 version

**Comment by LoneGazebo** [comment]
Wait, explain again?

**Comment by pandasnail** [comment]
Sorry, I can get kinda rambly at times, especially on the internet.

So the Dominance policy in the Authority branch gives science per kill. On account of the Huns UA, I was of course hunting barbarians in camps. If the science gained from the Dominance policy finished a technology, I wouldn't get the unit from the camp. The tech popup with the fancy quote would show up, then the regular barb popup would show up, congrats you've cleared the camp blah blah blah. Instead of the special Hun glorious Atilla side popup. And, again, no unit gained. 

The rest of my ranting was saying that this is an easy thing for a human to work around-just briefly switch techs. So the question is whether its the same for the AI Huns. I mean, there are obvi no popups when the AI finishes a tech. So maybe the order of things is different in such a way that this clash doesn't happen for the AI. (or it could just be me and my computer)

And the final bit was this unnecessary thing about I've basically never seen AI Atilla take Authority, he always takes Progress. So even if it does happen to AI Atilla, it might not matter all that much. But I play with certain settings and such, for other settings things could be different. Just ignore that part.

**Comment by LoneGazebo** [comment]
The two functions operate independently, so there's nothing that should directly cause this behavior. I'll look, but since they operate independently, I can't imagine a connection (unless the notification engine is hijacking the base DLL, which might explain a lot about MP desyncs)...

**Comment by pandasnail** [comment]
Well, its for sure happening to me this game, I tested it out, if its a weird local me only thing ok fine.

FWIW, my modlist: your six, eui, flag promotions, celtic city names, iroquian city names, more great works, randomize city names, and 'noaltitudetraining' which removes the mt kilman promotion

**Comment by LoneGazebo** [comment]
Fixed.
