### ISSUE TITLE
God of the Expanse 

### ISSUE THREAD

**Issue by boombar123** [LoneGazebo/Community-Patch-DLL#11442]
_1. Mod Version (X.Y.Z). Current Version: 4.17.7_

_4. Describe the Issue_
+25% border growth results in 0 less turns until border growth. i have 20 turns until border growth. I take pantheon and still have 20 turns until border growth. I rember playing russia some time ago and always taking this pantheon. city ui would calculate new border growth immediately. 
 

_8. Steps to reproduce the Issue (Optional)_
no mods. just start the game and take the pantheon

**Comment by axatin** [comment]
Intentional, the pantheon was changed recently. Previously it reduced the number of BGP that were needed for tile acquisitions. Now it increases the generated BGP per turn, and 1 + 25% is still 1 after rounding down.
