### ISSUE TITLE
Contradiction on Rocket Artillery Resource Requirements

### ISSUE THREAD

**Issue by theunholypotato** [LoneGazebo/Community-Patch-DLL#1145]
Conflict between comment and Resource type: is Rocket Arty meant to cost Iron or Oil?

-- Make Rocket Artillery cost oil, not aluminum:
	UPDATE Unit_ResourceQuantityRequirements
	SET ResourceType = 'RESOURCE_IRON'
	WHERE UnitType = 'UNIT_ROCKET_ARTILLERY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

**Comment by TechpriestEnginseer** [comment]
Think it's most likely iron due to the fact that iron in the later eras is abundant.

**Comment by phantommaxwell** [comment]
And all other Siege Units use Iron

**Comment by LoneGazebo** [comment]
It's just a typo in the -- text.
