### ISSUE TITLE
weird world congress proposal scoring

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#11452]
v 4.15.2

greece has the order ideology.

portugal and babylon have freedom.

portugal is proposing freedom as world ideology, and the game thinks greece stands to benefit from that?

![image](https://github.com/user-attachments/assets/2bebc19a-d978-46d5-8f7a-92fe65485a02)

savegame [proposalscore_0392 AD-1972.zip](https://github.com/user-attachments/files/18218424/proposalscore_0392.AD-1972.zip) (needs RemoveBanLuxury)

**Comment by axatin** [comment]
They are going for DV and need a world ideology for that, even if it's not the one they're following.

**Comment by ilteroi** [comment]
i don't understand ... also maybe i should have mentioned, greece is a human player. and the proposal came from portugal

**Comment by axatin** [comment]
ah, you are greece. the logic is still valid: the AI evaluates based on the number of delegates that the players is close to a diplo victory. to win DV a world ideology needs to active. it doesn't need to be your own, it can be any ideology. so for a player close to DV it's also positive if one of the other ideologies is declared world ideology.

**Comment by ilteroi** [comment]
Ah well then. Advanced!
