### ISSUE TITLE
AI passivity

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1146]
representative image:

![image](https://cloud.githubusercontent.com/assets/1358966/12539695/d0075530-c2f8-11e5-954e-b7db5ad042ab.png)

this is in 1700 AD. no single city has been captured. wide areas are unsettled. seems like expansion went out out style.

**Comment by TechpriestEnginseer** [comment]
I don't know when I only have cultural and domination as my victory condition (Because these two can make the game basically last forever), war is everywhere.

**Comment by LoneGazebo** [comment]
Hmm...

Only one of those civs (the aztec) is a war-focused civ - they never went to war?

**Comment by Iamblichos** [comment]
Really I'm seeing more units and more aggression in my games. Ever since Gazebo changed the grand strategy and AI focus stuff I've been running into much stiffer competition.

**Comment by ilteroi** [comment]
next game - this is 1860AD

![image](https://cloud.githubusercontent.com/assets/1358966/12545454/ad2829e6-c342-11e5-9b1d-fcd779644265.png)

obviously the perfect spot for a city. never settled. and again, no conquest (can't say whether war was ever declared)

**Comment by Kolaris8472** [comment]
I'm seeing the AI settle in waves. A couple AIs will be content with 3-4 cities for several eras even if there's prime real estate next door. Then they suddenly go on a rapid colonization spree up to ~8 cities. 

As for war and aggression, I have to weigh in on the side of worlds being very, very peaceful. I'm playing with Random Personalities though, not sure how that might affect the new AI.

**Comment by ilteroi** [comment]
added some logging for economic strategies. here are the relevant ones. note that the spot will be finally settled in turn 311, the log is from 113 - the screenshot is from in between.

113, Persia, ECONOMICAISTRATEGY_EARLY_EXPANSION is inactive, checking for start
--> 3 cities settled, no longer applicable
113, Persia, ECONOMICAISTRATEGY_ENOUGH_EXPANSION is inactive, checking for start
--> ok
113, Persia, ECONOMICAISTRATEGY_FOUND_CITY is inactive, checking for start
--> no settler to work with
113, Persia, ECONOMICAISTRATEGY_ISLAND_START is inactive, checking for start
--> only applies to the first 50 turns
113, Persia, ECONOMICAISTRATEGY_EXPAND_TO_OTHER_CONTINENTS is active, checking for nothing
--> ok
113, Persia, ECONOMICAISTRATEGY_REALLY_EXPAND_TO_OTHER_CONTINENTS is inactive, checking for start
--> needs ocean crossing. not yet applicable
113, Persia, ECONOMICAISTRATEGY_EXPAND_LIKE_CRAZY is inactive, checking for start
--> this has a rather high weight threshold of 10. maybe reduce it? strategy is inhibited if the empire is unhappy, so it's not like they would overexpand

so regarding settling, it seems to me they simply don't prioritize building settlers after the initial EARLY_EXPANSION phase. only in the lategame when cities are running out of things to build they get a chance.

**Comment by LoneGazebo** [comment]
We can directly modify this in the new unitproductionAI sanity check.

**Comment by LoneGazebo** [comment]
Speaking of which, I think it'd be prudent to have flavors passed into production choices be 'normalized' a bit  (i.e. if one thing has a flavor of 200, and another a flavor of 200,000, let's bring the 200,000 down by a magnitude or two). Any ideas?

**Comment by ilteroi** [comment]
well, i did something similar with the flavors for city sites, to make sure the resulting score is in a predefined range. i used a simple L1 normalization there (i.e. make sure the sum of absolute flavor values is always the same).

however, it seems your problem is that the flavors are in different orders of magnitude. so first question: why not simply change them to something sane? alternatively, simply use the log10 of the values. or cap them at 100.

**Comment by LoneGazebo** [comment]
Well, the flavors are pre-processed by the flavor AI - it might be prudent, honestly, to just have all flavors output from the flavor AI be normalized for the entire DLL.

G

**Comment by ilteroi** [comment]
well i think you'd need to re-normalize time and again after flavors are added together etc. but it's a nice idea, i theory you could rewrite it in a clean vector notation. because that's what it is. just inner products between flavor vectors.

**Comment by LoneGazebo** [comment]
Blegh.

**Comment by LoneGazebo** [comment]
Fixed issue with passivity, i think. AI target evaluation was breaking.
