### ISSUE TITLE
Feature/adjustment request: AOE damage abilities display their enabling promotion name

### ISSUE THREAD

**Issue by Tekamthi** [LoneGazebo/Community-Patch-DLL#11469]
There's a number of AOE damage abilities in the promo table... Several of these always display a message when activated "pilum", "rend", etc.  One of them doesn't have any message, just the damage value.

When using these abilities via another promotion, it is undesirable for them to display "rend" or "pilum" etc.  The ideal would be to just dynamically display the name of the promotion that enables these abilities, and for it to work consistently this way across all similar abilities.  If this is too complicated/costly, displaying just the damage value would be preferable to the misleading names in status quo

**Comment by azum4roll** [comment]
It's not possible to get the promotion that has already applied the effect to the unit (what if there are two of them?)

> One of them doesn't have any message, just the damage value.

All of them have a name (Pilum, Rend, Viking, Splash Damage, Area Damage). We can change them to "Fortify Area Damage", but that's too long...

**Comment by Tekamthi** [comment]
okay thanks for considering, i'll close this one -- since posting i've discovered they're just text tags like any other and can be overwritten anyway -- i used "fortify" and "move" to indicate the cause -- but if theres only one source for each in the mod by default then the labels make sense

**Comment by azum4roll** [comment]
NearbyEnemyDamage is an end-of-turn effect, not a type of AOE damage.

**Comment by Tekamthi** [comment]
yes thats right, however from general player perspective it appears to work as somewhat of a variant of the other aoe effects -- for example the fortify aoe is almost like its start-of-turn counterpart
