### ISSUE TITLE
CTD while loading 2 player LAN or at 1st turn

### ISSUE THREAD

**Issue by Rouzax** [LoneGazebo/Community-Patch-DLL#11466]
_1. Mod Version (X.Y.Z). Current Version: 4.17.8_

VP Only modpack with EUI: 4.16.1_VP-EUI.zip ([Link](https://drive.google.com/drive/folders/1k6rheDL2Q38oBF9je2ADw_dgVkqaG7Ey))

_2. DirectX Version_

DX11

_3. List of Other Mods_

None

_4. Describe the Issue_

CTD while loading 2 player LAN game, or after pressing End Turn first time.
Same two systems have been able to play a few weeks ago, but seem to keep crashing now.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/user-attachments/files/18261615/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.dmp](https://github.com/user-attachments/files/18261621/CvMiniDump.dmp)

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by Cyclopia31** [comment]
You can try to empty Civ5 cache on both PC (in Documents/mygames/civilizationV folder)

**Comment by Rouzax** [comment]
> You can try to empty Civ5 cache on both PC (in Documents/mygames/civilizationV folder)

Feel stupid 😝 
I did clear the cache and ModUserData on the machine that was crashing, but not the other one.
It seems to have fixed the issue for now

**Comment by Cyclopia31** [comment]
I don't know why but most of the time it's the host cache that make the non host pc crash...

**Comment by Rouzax** [comment]
In my case it was the other way around, the none host cache was crashing the host pc.
I think at least
