### ISSUE TITLE
Any of these GameEvents possible?

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1147]
Would it be possible to create these (or similiar) GameEvents?
**GameEvent.CityBeginsWLTKD.Add(playerID, plotX, plotX, turns)** -- detects when a WLTKD begins in a city.
**GameEvent.CityRazed.Add(playerID, plotX, plotX)** -- detects when a city is razed.

You can substitute plotX, plotY for cityID, but I see the former more often so figure it might easier.

Thanks for any that can be done, and let me know if either or neither are not possible/easy.

**Comment by TechpriestEnginseer** [comment]
```
function CityBeganWLTKD(iPlayer)
   local pPlayer = Players[iPlayer]
	for pCity in pplayer:Cities() do
		if pCity:GetWeLoveTheKingDayCounter() > 0 then 
			print(pCity:GetName() ... pCity:GetX() ... pCity:GetY() ... pCity:GetWeLoveTheKingDayCounter())
		end
	end
end
function CityRazed(iPlayer)
   local pPlayer = Players[iPlayer]
	for pCity in pplayer:Cities() do
		if pCity:IsRazing() then 
			print(pCity:GetName() ... pCity:GetX() ... pCity:GetY())
		end
	end
end
GameEvents.PlayerDoTurn.Add(CityBeganWLTKD)
GameEvents.PlayerDoTurn.Add(CityRazed)
```

**Comment by JFDaly** [comment]
Neither of those detect when a WLTKD begins/Razing ends, and would merely trigger each turn that a WLTKD is active/that a city is being razed. In fact, CityRazed would probably not even trigger when a city has been fully razed, as the city object would no longer exist at that point.

**Comment by TechpriestEnginseer** [comment]
Well, you can add in a dummy building to prevent it from being triggered multiple times. However, CityRazed might be of course something difficult to do.

**Comment by JFDaly** [comment]
Perhaps, but that not only makes any function using these imprecise, but also encumbered by messy and potentially buggy workarounds. This notwithstanding, I would need to create LuaEvents in order to make these of general purpose, which is the intent behind adding them as GameEvents, in which case they may as well be added as GameEvents, if at all possible (a predication aimed at Gazebo).

**Comment by LoneGazebo** [comment]
Done.
