### ISSUE TITLE
DLL CvUnit::setMoves

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1148]
I have  a mod for a certain improvement that calls out a GameEvents.UnitSetXY to change moves when a unit moves over this improvement. It's called out correctly, but breaks out often on this function:

    void CvUnit::setMoves(int iNewValue)
    {
	    VALIDATE_OBJECT
	    if(getMoves() != iNewValue)
	    {
		    CvPlot* pPlot = plot();

		    m_iMoves = iNewValue;

		    auto_ptr<ICvUnit1> pDllUnit(new CvDllUnit(this));
		    gDLL->GameplayUnitShouldDimFlag(pDllUnit.get(), /*bDim*/ getMoves() <= 0);

		    if(IsSelected())
		    {
			    DLLUI->setDirty(UnitInfo_DIRTY_BIT, true);
		    }

		    auto_ptr<ICvPlot1> pDllSelectionPlot(DLLUI->getSelectionPlot());
		    int iSelectionPlotIndex = (pDllSelectionPlot.get() != NULL)? pDllSelectionPlot->GetPlotIndex() : -1;

		    if(pPlot->GetPlotIndex() == iSelectionPlotIndex)
		    {
			    DLLUI->setDirty(PlotListButtons_DIRTY_BIT, true);
		    }
	    }
    }

Breaks on: if(pPlot->GetPlotIndex() == iSelectionPlotIndex). Shouldn't there be a check there for pPlot? If I change that to:
    if(pPlot && pPlot->GetPlotIndex() == iSelectionPlotIndex), then it passes.

**Comment by LoneGazebo** [comment]
The extra pPlot is insurance, yep, but the function (being in CvUnit) should always have a plot. If it doesn't, something else is wrong (or your function is calling a unit function when there is actually no unit).

G

**Comment by Iamblichos** [comment]
I have checks in the lua to ensure unit and plot is not nil. Doesn't seem to matter.

**Comment by LoneGazebo** [comment]
Interesting. The insurance isn't a bad idea (I try to add that where I can), so I'll add it.

**Comment by Iamblichos** [comment]
Let me back up. At first I didn't have the checks in the lua, so I thought adding the checks in the lua would solve the problem. No dice. Thought it needed the check in the DLL and it passed. I kept the same save state each time to test  where the crash was, to ensure the AI was going to make the same moves each time for consistency.

**Comment by LoneGazebo** [comment]
So what's the final conclusion, then?

**Comment by Iamblichos** [comment]
doesn't pass unless I put the check in the DLL. doesn't matter what I did in LUA. just wanted to go through my debugging steps to make that clear.

**Comment by LoneGazebo** [comment]
ah ok

**Comment by Iamblichos** [comment]
Oh and btw--why do some mod authors make a CC license "against the spirit" of modiquette when they have no essential changes to the game and their mod is merely formal? I found that odd if not somewhat pretentious.
