### ISSUE TITLE
Coffe and coral

### ISSUE THREAD

**Issue by TemonOak** [LoneGazebo/Community-Patch-DLL#1150]
I have had trouble building improvments on coffe and Coral. dont have any mods apart from the full Community installer

**Comment by LoneGazebo** [comment]
Make sure your copy of civ is updated to latest version.

**Comment by TemonOak** [comment]
I am currently running version 1.0.3.279. Are there any later version?

**Comment by LoneGazebo** [comment]
No. Not sure. Enable logging, post database.log once you've launched a game.

**Comment by TemonOak** [comment]
it seems I forgot to delete an old modpack I had. will see if deleting everything reinstalling civ 5 and so on will fix it.

**Comment by LoneGazebo** [comment]
Sounds good.
