### ISSUE TITLE
Wrong description

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1151]
A minor bug. Description says "Sort by unhappiness" while it sorts by City Strength (top left corner).
![2016-01-25_00002](https://cloud.githubusercontent.com/assets/16341598/12564723/794ba96e-c3b9-11e5-87de-b122a798443b.jpg)

**Comment by LoneGazebo** [comment]
I should probably make that 'defense' calc there unhappiness anyways.
