### ISSUE TITLE
AI doesn't respect unit limit

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1152]
just saw this after autoplay ended

![image](https://cloud.githubusercontent.com/assets/1358966/12564691/ebd1d4da-c3b0-11e5-8a1e-a34e64aacc8f.png)

apparently AI keeps building units even after hitting the limit.

this whole unit supply thing seems to be very poorly documented by the way. I wonder if it's needed at all, isn't unit maintenance cost enough on its own?

**Comment by LoneGazebo** [comment]
Weird, there's a specific catch to prevent that in the new unitproduction sanity check. I'll double-check it.

Also, fairly certain my new 'sanity' code is as streamlined as possible, but I might've missed a chance to cache data. Not sure. Any thoughts on the code?
G

**Comment by LoneGazebo** [comment]
I see problem, wasn't checking for zero value in pushback. Fixed.
