### ISSUE TITLE
Harald units

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#1153]
Some of them (probably those not build or bought but rather given by policies do not have the pillage for free and loot money when attacking cities. Version 1.23, playing only CBP+EUI

**Comment by LoneGazebo** [comment]
Well, which is it? Just policies?

**Comment by AnastaseAlex** [comment]
yes those given by policies (I did not get any gifts from city states I think)

**Comment by LoneGazebo** [comment]
Such as conscription, you mean? There are no policies that give standard units.

**Comment by LoneGazebo** [comment]
Cannot reproduce in-game with conscription.
