### ISSUE TITLE
Leader Screens blank

### ISSUE THREAD

**Issue by conor97** [LoneGazebo/Community-Patch-DLL#1154]
Whenever I enter diplomacy, the animation for the leader plays, but there are no buttons available:
![2016-01-26_00001](https://cloud.githubusercontent.com/assets/1420255/12591063/eebcb522-c45d-11e5-9180-fc05dbe691e1.jpg)

I have these mods installed: https://gyazo.com/24b9e9857721377728a275d3c0f7e822
And I'm using the EUI installed from the auto installer. I've reinstalled and cleared caches and cleared every other mod I had. I just haven't a clue what to do now, I apologise in advance if I'm being dumb, but this is my last resort. As a side note, I'm not playing as JFD's Great Britain and that mod is not active when I'm trying to play.

**Comment by LoneGazebo** [comment]
Remove inactive mods from mods folder. I think the 3rd and 4th UC mods conflict. Remove all non-CBP mods, clear cache, and report back.

**Comment by conor97** [comment]
Okay, the problem was JFD's Cities in Development. What's confusing me though, is that mod requires the community patch to function. I presume that it's due to the versions of EUI?

**Comment by conor97** [comment]
Wow, turns out I'm just stupid. I moved some files to the wrong place when installing that mod. Sorry for wasting your time! It's all working now, all the mods work together. Thanks anyway!

**Comment by LoneGazebo** [comment]
No worries!
