### ISSUE TITLE
Warmonger penalty being added twice?

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1158]
Some seemingly odd behavior with warmonger penalty. Portugal tried to sneak attack DoW me when I had been at peace all game. After fighting back for a long time, I was in position to take a city. I had not been at war or taken any cities all game, so my (lack of) warmonger score is apparent:

![2016-01-27_00001](https://cloud.githubusercontent.com/assets/11132095/12608769/a7cb4a98-c4a3-11e5-9fbc-ad9582a9c06a.jpg)
![2016-01-27_00002](https://cloud.githubusercontent.com/assets/11132095/12608772/a7cdb422-c4a3-11e5-9ba9-4ec76f33749e.jpg)

I went and took the city, and my warmonger score with both Maria and others was updated to reflect that:

![2016-01-27_00003](https://cloud.githubusercontent.com/assets/11132095/12608770/a7cda1e4-c4a3-11e5-9a46-f54a693c28f5.jpg)
![2016-01-27_00004](https://cloud.githubusercontent.com/assets/11132095/12608774/a7d60334-c4a3-11e5-8e3f-1d921ad9b623.jpg)

This is where it gets weird. All I did was hit 'next turn', and my penalty seemed to progress again:

![2016-01-27_00005](https://cloud.githubusercontent.com/assets/11132095/12608773/a7cfc94c-c4a3-11e5-985b-4ee09f5d80db.jpg)
![2016-01-27_00006](https://cloud.githubusercontent.com/assets/11132095/12608771/a7cd9a3c-c4a3-11e5-8900-69b06841a387.jpg)

All I did was take one city, and after hitting next turn my warmonger penalty progressed to a high amount. Save and logs attached.

Semi-related: how long is the "building new cities too aggressively" penalty supposed to stick around? Pretty sure I hadn't built a new city in at least a millennium at that point.

[Warmonger penalty.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/106316/Warmonger.penalty.zip)

**Comment by LoneGazebo** [comment]
Warmonger penalties can change in-between turns during the AI evaluation period, but I'll look.
Aggressive city settlement has no cutoff, so I'll add one.
