### ISSUE TITLE
[CBP 23-01] Specialist do not consume half (tradition and freedom)

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#1159]
A specialist consume 2 food, +1 food for each era (starting with Rennaissance)
There is two policies which says "specialist consume half" (tradition is only for the capital, and freedom is for all cities), but what they really do is "specialist consume 1 food less".
A specialist consume 6 food during atomic era, so -1 and half is not at all the same thing.

So either it is a bug, either the text of the social policie is false 
(or at least missleading : with both policies, a specialist still consume more than a normal personne in the capital, which is not at all what you would expect)

**Comment by LoneGazebo** [comment]
Fixed, thanks.
