### ISSUE TITLE
Suicidal Great Generals

### ISSUE THREAD

**Issue by ricanuck** [LoneGazebo/Community-Patch-DLL#1160]
Suicidal generals are back in version 1.20beta: I have seen many of them in the same game, in one occasion the AI even doubled the GGs one on top of the other and marched unescorted towards my lines... did not take advantage of it as it was just too lame, but wanted to report it here. I have no idea if it has been fixed for the latest version.

**Comment by ilteroi** [comment]
savegame would be good

**Comment by ricanuck** [comment]
Sorry, that game has been long gone. If I see the same in the latest beta, I will make sure I have a savegame before the event and post it.

**Comment by ilteroi** [comment]
doesn't matter, i've seen it. they trying to build a citadel. let me see what i can do

**Comment by ricanuck** [comment]
Ha! The one troubling though was the double GG, one on top of the other, that I saw in front of my troops, completely undefended... and I remember them clearly, if they were trying to build a citadel, they did not even succeed at that (there was not citadel built in the area for the next few turns), making it a complete double suicide.

**Comment by ilteroi** [comment]
should be better now
