### ISSUE TITLE
Decolonization WAD?

### ISSUE THREAD

**Issue by ricanuck** [LoneGazebo/Community-Patch-DLL#1161]
I am not sure if this is a bug or WAD, but sure does not look like the latter. Both me and Poland were heavily competing for the same CS's the entire game. At some point, both me and Poland got "Decolonized" via the WC. All my CS's influences fell to 50 as expected, but the very next turn I see one of my former CS allies getting Ally status with Poland for a crazy 803 influence points.

I cannot find an explanation as to how Poland got from 50 influence (post-decolonization) to 803 influence in one turn, but for a possible bug.

This was 1.20beta.

**Comment by LoneGazebo** [comment]
Well, were you competing over it? Because decolonization does not affect the influence of non-allied civs in the CS.

G

**Comment by ricanuck** [comment]
Oh, yes, you are right! Poland was not allied to this particular CS, I was, so I went to 50 and they became allied with their remaining 803...

Duh moment.

Was well played by the AI, by the way, basically defeated my game when I was going for a SV. No way I could recover from that blow, and I was also already sanctioned. Very well played.

**Comment by ricanuck** [comment]
Had to retire from that game.

**Comment by ricanuck** [comment]
Now that it has been established that it is indeed WAD, I wonder if it is too powerful? I don't know if I am just enraged by my loss in the hands of the AI, but going down to 50 in the late game is potentially game breaking... no way to recover from such a loss. What do you think?

(thinking loud, something like going down 50% of influence may work...)

**Comment by LoneGazebo** [comment]
It's pretty brutal, yes, but it's also a snowball-reversal proposal. The AI will generally only propose it if you have lots of CS allies, so the chance of it succeeding is lower.
