### ISSUE TITLE
Treasure fleet; noone but me bothered at all

### ISSUE THREAD

**Issue by a1nosweat** [LoneGazebo/Community-Patch-DLL#1162]
Just completed about 200 years of treasure fleet.  Playing Islands map with dutch, arabia, Maria, Napoleon...(Brazil destroyed as they nearly got runaway CV) I own Paris - as byzantium,

Noone bothered at all.  Yet Portugal and france declared Naval war on me halfway through.

Is this because they are going for diplo victory?

**Comment by LoneGazebo** [comment]
There's a bug or two in the process logic that i've since fixed.
