### ISSUE TITLE
[CBP] Civilopedia : some missing or outdated things

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#1163]
I've tried to find all missing or outdated things in the Civilopedia [CBP 23-01]

Unfortunately, I was not suffisantly motivated to continue after the first part : the "Game Concept" part.
Event if not a lot of peoples really read this part of the Civilopedia, correcting it is still a good thing.

+Cities
-Combat Units : now, unit in garnison can take damages (and reduce cities damages)
-Benefits of Specialists : Uncomplete list of specialists.
-Attaking a City : now, unit in garnison can take damages (and reduce cities damages)

+Combat Rules
-Melee Combat Result : Add that when a unit attack from a city, it does not move even if the defender is destroyed.
-Garnison Units in Cities : It is said that unit in garnison takes no damages. It's false. 
-Cities Firing at Attackers : It is sait that the city range is 2. It's false most of the time.
-Great Generals : "Warrior Code" no longer exists.
-Acquiring XPs Through Combat : Barbarian limit is now 45XP

+Terrain and Features : Completely outdated. Moreover, this sub-part is redundant with the "Terrain and Feature" part (which is up to date).

+Resources : OK

+Constructing Improvements
-Clearing Land : Now, remove forest is bronze working, remove jungle is iron working, and remove marshes is machinery.
-Time to Clear Land : TO CHECK.
-Farm Improvements : Outdated, and redundant with the "Farm" of the "Improvement" part.
-Mine Improvements : Outdated, and redundant with the "Mine" of the "Improvement" part.

+Food and City Growth
-City Unhappiness : Unhappiness no longer reduce by 75% the growth (instead, it reduce all yields by up to 30%)
-City Growth : Maybe recall here that specialist food consumption increase with era

+Technology
-Trage : It should add that research agreement need to be enabled (avanced options) and that tech trading is by default allowed.
-Wonder : The National College effect is outdated
-Which Technologies Are Available : The example is outdated (for example, Potery does not unlock Writing)

+Culture : OK

+Diplomacy
-Research Agreements : Have to be enabled (avanced options)
-Negotiating Peace : Maybe add an explanation of the "War score" and other things like that.

+Happiness
-Happiness : Add that happiness modify all global yields (-30% -> +10%)
-Levels of Unhappiness : Unhappiness no longer reduce by 75% the growth (instead, it reduce all yields by up to 30%)
-Unhappy : Unhappiness no longer reduce by 75% the growth (instead, it reduce all yields by up to 30%)

+Fog of War : OK

+Social Policies : Completely outdated. Moreover, this sub-part is redundant with the "Social Policies" part (which is up to date).

+Gold and the Economy, Advisors, Great People and Specialists, City-States, Unit Movement : OK

+Air Combat Rules : I've not use a lot of air units with CBP, so I don't know what is outdated and what is not.

+Ruins and Barbarian : Uncomplete list of Ancient Ruins benefits 
-Map : outdated
-Experience Points Limitations : now 45XP

+Units
-National Units : B-17 are no longer American's unique unit, Companion Cavalery are non longer Greek's unique unit.

+Victory, Espionage, Religion, Trade, World Congress, Vassalage, Corporation and Monopolies : OK

I've quickly look at other parts, and found no errors, which is a good thing (usefull informations are already up-to-date !!!)
But, I've remark that if techs shows "Prerequisite Techs" and "Leads to Techs", Buildings only shows "Prerequisites Buildings" and not "Lead to Buildings"

I hope it would help you to improve this (already great) mod.

**Comment by LoneGazebo** [comment]
Thanks!

**Comment by LoneGazebo** [comment]
Fixed! Also added that 'leads to building' element for you. :)
