### ISSUE TITLE
Mercenaries and Commerce Branch

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1164]
Civilopedia mentions a unit called Mercenary that can only be hired if Commerce Branch is unlocked. The problem is that there is no Commerce Branch in CBP. And therefore no Mercenaries are available for build after reaching Penicillin Technology.

**Comment by LoneGazebo** [comment]
Ah, that's a double-typo (Mercenary comes from Imperialism).
