### ISSUE TITLE
Player:GetNumPolicies() and Dummy Policies

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1165]
Would it be at all possible to modify GetNumPolicies() in order to skip dummy Policies (or, make a new function like GetNumRealPolicies(), whichever would be most possible)? A lot of people (not just myself) tend to use dummy policies to achieve particular effects, but the flaw in this has become most apparent to me with Sovereignty, where the innumerous Reforms are technically Policies and thus counted in GetNumPolicies. The distinction between dummy and real Policies is simply whether the policy has a PolicyBranchType in its database entry. Not sure how feasible any of this is, however. 

Thanks for any help here.

**Comment by LoneGazebo** [comment]
What markers would you need to see if something was a 'dummy' policy?

**Comment by JFDaly** [comment]
I'm not sure how it'd read in the DLL, but in Lua it would be something like (if GameInfo.Policies[policyID].PolicyBranchType == nil then, we're a dummy policy). Basically, a dummy policy would be marked by having a nil/null entry as its PolicyBranchType. Would that be possible?

**Comment by LoneGazebo** [comment]
Yep, but I'll also add an IsDummy element you can use (just to be sure).

G

**Comment by JFDaly** [comment]
Awesome, thanks

**Comment by LoneGazebo** [comment]
Done, auto-calc'd in lua check for 'getnumpolicy' and in the DLL.

G

**Comment by JFDaly** [comment]
Wow, that was quick. Thanks again!

**Comment by LoneGazebo** [comment]
Yeah, was a simple iterator (and I'm working on a beta right now, so might as well!)
