### ISSUE TITLE
Golden age tooltip doesn't display properly (when playing as Morocco)

### ISSUE THREAD

**Issue by Bombad** [LoneGazebo/Community-Patch-DLL#1167]
See screenshot : https://www.dropbox.com/s/yntznq2dnlqjy2g/Capture%20d%27%C3%A9cran%202016-01-25%2021.19.30.png?dl=0

Happened when playing as Morocco.

Mods used : 
- Complete CP/CBP suite (1/23, no EUI)
- Quick turns (from steam workshop)
- UI - small resource icons (from whoward)
- UI - Map Pins (from whoward)

**Comment by 8h42** [comment]
There is a typo in the **No-EUI TopPanel.lua** file.

cf.
CPP 1/28 beta v2
(6b) Community Balance Patch - Compatibility Files (No-EUI)\LUA\TopPanel.lua
Line: 1083

TXT_KEY_TP_GOLDEN_AGE_ADDITION_TRAITTXT_KEY_TP_GOLDEN_AGE_ADDITION_CITIES
should be
TXT_KEY_TP_GOLDEN_AGE_ADDITION_CITIES

**Comment by LoneGazebo** [comment]
Ah, that explains the error..

**Comment by LoneGazebo** [comment]
Thanks!
