### ISSUE TITLE
Collapsing title diplayed improperly for diplomats (in the top-left GP menu)

### ISSUE THREAD

**Issue by Bombad** [LoneGazebo/Community-Patch-DLL#1168]
See screenshot : https://www.dropbox.com/s/6ywiqccii4ofhua/Capture%20d%27%C3%A9cran%202016-01-26%2011.46.25.png?dl=0

Mods used :

- Complete CP/CBP suite (1/23, no EUI)
- Quick turns (from steam workshop)
- UI - small resource icons (from whoward)
- UI - Map Pins (from whoward)

**Comment by LoneGazebo** [comment]
Fixed.
