### ISSUE TITLE
GP line displayed on every building after getting a Civilized Jeweler's franchise.

### ISSUE THREAD

**Issue by Bombad** [LoneGazebo/Community-Patch-DLL#1169]
See screenshots : 

https://www.dropbox.com/s/l1c178nmfo6opmq/Capture%20d%27%C3%A9cran%202016-01-26%2011.02.24.png?dl=0

https://www.dropbox.com/s/khd2kind2znuehs/Capture%20d%27%C3%A9cran%202016-01-26%2011.02.26.png?dl=0

https://www.dropbox.com/s/oy9t179uvdiri6n/Capture%20d%27%C3%A9cran%202016-01-26%2011.02.30.png?dl=0

That line appears on every building (available for construction and already constructed) in the cities which have an office as soon as a franchise is built.

Mods used :

- Complete CP/CBP suite (1/23, no EUI)
- Quick turns (from steam workshop)
- UI - small resource icons (from whoward)
- UI - Map Pins (from whoward)

**Comment by LoneGazebo** [comment]
Please post your log file. If you don't have logging enabled, enable it, load the game, then post your logs (triggering each instance of the problem you see here).

G

**Comment by Bombad** [comment]
What do you mean by "triggering each instance of the problem" ? Hover on buildings to display the tooltips where the line appears ?

Here's the log folder (I enabled logging, loaded a game, then displayed the various tooltips that were problematic), tell me if you need anything else.

https://dl.dropboxusercontent.com/u/68988878/Logs.zip

**Comment by LoneGazebo** [comment]
Yep, thanks!
G

**Comment by LoneGazebo** [comment]
Fixed.
