### ISSUE TITLE
Combat predictions for cities with garrisons

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1170]
The combat prediction does not take into account the damage that gets redirected to the garrison. 
So while it is technically not wrong, it does not display the actual outcome. It is especially striking when it shows that you would conquer the city with the attack, but you don't.

**Comment by ilteroi** [comment]
true, but needs a major rewrite to fix this ... let me check

**Comment by ilteroi** [comment]
needs lua changes, cannot do it properly on DLL side

**Comment by LoneGazebo** [comment]
What does it need?

**Comment by ilteroi** [comment]
the combat preview does not use the CvCombatInfo structure but calls CvUnit::getCombatDamage() directly. 

so either we need to change that or duplicate the garrison logic on lua side.

**Comment by LoneGazebo** [comment]
Can we not just edit the function in cvluaunit.cpp? 

G

**Comment by ilteroi** [comment]
well, that would be a hack. no likey. but for want of alternatives maybe the way to go

**Comment by LoneGazebo** [comment]
How so? We can just edit the value to reflect the fact that it is a garrison (or the city is garrisoned) in that function, right? All that's passing through is the int value.

G

**Comment by LoneGazebo** [comment]
The 'defenderiscity'  bool already exists in the lua function, so we just used that as a chance to check for a garrison. If there is one, we just drop the value by the appropriate amount.
G

**Comment by ilteroi** [comment]
problem is, in lGetCombatDamage() we don't know which plot is being attacked, so we don't know if the city is garrisoned.

**Comment by LoneGazebo** [comment]
I'm editing the lua now, adding a pCity as the 8th variable on the function. Should give us the info we need.

**Comment by LoneGazebo** [comment]
In getcombatdamage, does this look right?

```
	// Modify damage for when unit is attacking a city
	if(bDefenderIsCity)
	{
		iDamage *= /*100*/ GC.getATTACKING_CITY_MELEE_DAMAGE_MOD();
		iDamage /= 100;
#if defined(MOD_BALANCE_CORE)
		if(pCity)
		{
			CvUnit* pGarrison = pCity->GetGarrisonedUnit();
			if(pGarrison)
			{
				//make sure there are no rounding errors
				int iGarrisonShare = (iDamage*2*pGarrison->GetMaxHitPoints()) / (pCity->GetMaxHitPoints()+2*pGarrison->GetMaxHitPoints());
				iDamage -= iGarrisonShare;
			}
		}
#endif
	}
```

**Comment by LoneGazebo** [comment]
Fixed, needs testing.
