### ISSUE TITLE
[BUG] Pupppeted cities produce Artists Guilds and World Wonders (CP 01-23)

### ISSUE THREAD

**Issue by kaspergm** [LoneGazebo/Community-Patch-DLL#1171]
This bug was experienced in version 1-23 of CP:

Puppeted city builds World Wonder (thus preventing me from building it in different city):
http://i105.photobucket.com/albums/m217/kaspergm/BugWonder.jpg

Puppeted city builds Musicians Guild:
http://i105.photobucket.com/albums/m217/kaspergm/BugGuilds.jpg

**Comment by LoneGazebo** [comment]
Fixed in 1-28.
