### ISSUE TITLE
[BUG] AI doesn't participate in WC project (CP 01-23)

### ISSUE THREAD

**Issue by kaspergm** [LoneGazebo/Community-Patch-DLL#1172]
This bug was experienced in CP version 01-23:

AI was happy for my proposal for World Games and also voted for it, but afterwords universally allocated 0 production to the project.
http://i105.photobucket.com/albums/m217/kaspergm/BugCompetition.jpg

**Comment by LoneGazebo** [comment]
Fixed in 1-28.
