### ISSUE TITLE
Military-Tradition (Imperialism) Military-Academies

### ISSUE THREAD

**Issue by Kolaris8472** [LoneGazebo/Community-Patch-DLL#1175]
They've got the +2 Science, but they're missing the +1 Culture that Barracks and Armories have.

**Comment by LoneGazebo** [comment]
Code has it, so can't reproduce, sorry.
G

**Comment by Kolaris8472** [comment]
http://i.imgur.com/dgv2ots.jpg

No idea why it doesn't show up in the buildable menu. It does show up once it's built, or in the tech tree.

**Comment by LoneGazebo** [comment]
Not in the build-able list? In a city? Weird. But it shows up in the tech tree?

**Comment by Kolaris8472** [comment]
Yeah, the +1 Culture is there if I mouse over it under the Military Theory tech, or if I mouse over an already built Military Academy. 

Just not the build list, like in that screenshot.

**Comment by LoneGazebo** [comment]
That's odd. Investigating.

**Comment by LoneGazebo** [comment]
Code looks normal, so must just be an EUI thing.
