### ISSUE TITLE
Autarky Tenant

### ISSUE THREAD

**Issue by Kolaris8472** [LoneGazebo/Community-Patch-DLL#1176]
I'm not sure if the +10 Gold for internal trade routes is working. The trade route panel shows only the Food/Production, the city panels don't list anything, and hovering over my gold income (EUI) offers no leads. 

I have Piety finished and the routes start from my Holy City, if that matters.

**Comment by LoneGazebo** [comment]
it is - it appears in the toppanel under city connection gold, not in the trade panel.
G

**Comment by Kolaris8472** [comment]
Ok, not where I would have looked. Is it affected by Machu Picchu or Arenas?

**Comment by LoneGazebo** [comment]
No, it's just added there (there's not an elegant way to add gold to internal TR tooltips/trade route screens, thus this).

**Comment by LoneGazebo** [comment]
Alright, I'll move it to a separate tooltip for clarity. Thanks!
