### ISSUE TITLE
Peace Deal discord

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1178]
The same issue arises again in the latest hotfix.
When me or an AI initiate a peace talk (either my enemy offers peace agreement or me by pressing "What deal will end this conflict") the AI offers his conditions but won't agree to them.
Here is the savegame. Try to make peace with Brazil.

[No Peace Deal.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/110396/No.Peace.Deal.zip)

**Comment by Der-Zorn-Gottes** [comment]
I have often the same issue. When it happens, it gives an absurly high deal value (10digits).

**Comment by saamohod** [comment]
"When it happens, it gives an absurly high deal value (10digits)."
That's exactly my case.

**Comment by ilteroi** [comment]
are city states included in the deal? in that case i fixed it yesterday.
