### ISSUE TITLE
Harbour cost/profit

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1179]
Civilopedia explanation for the Harbour seems to be lacking sense. It says:
Gold: +1 Coin
Maintenance: -2 Coin
Seems redundant to me, if I understand it correctly.

**Comment by TechpriestEnginseer** [comment]
Gold can be manipulated by gold multipliers. Maintenance will always remain -2.

**Comment by LoneGazebo** [comment]
Enginseer is correct.
