### ISSUE TITLE
Hunnic Behaviour

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1181]
have seen the huns build lots of battering rams in my current game
however, as they can only attack cities, this is pretty useless

**Comment by LoneGazebo** [comment]
I hate the battering ram and siege tower nonsense.

**Comment by Ninakoru** [comment]
Yeah, also happens with roman Ballista and in modern+ with naval army composition AI will easily train subs over destroyers all the time.

**Comment by LoneGazebo** [comment]
I've addressed discrepancy of unit types a bit in recent releases, but it is a constant project.

**Comment by LoneGazebo** [comment]
New stuff in 2-2.
