### ISSUE TITLE
AI deal offers

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1184]
AI seems to value third party peace a bit too high, i get 9 gpt for making peace with a major or a free luxury for making peace with a city state (didn't even know we were at war!)

**Comment by ilteroi** [comment]
and another thing. AI now offers capitulation, which is good. but there's a bug where it's impossible to accept their offer.

![image](https://cloud.githubusercontent.com/assets/1358966/12699120/76ef9d92-c7b0-11e5-8a12-a79cf5c0d9bf.png)

they offer peace with minors where in fact peace is blocked. i've fixed it, but there are two things:

- peace is only blocked because the minor is my ally and we are at war. since we're about to sign the peace treaty, peace with the minor shouldn't be blocked. chicken and egg problem.
- it's not possible to remove city states from the deal by clicking on them. intended?

**Comment by joosegoose** [comment]
Was about to open an issue on this...civs appear willing to make peace, but will only do so when they offer on their turn, not the human's. I'm pretty much stuck at war until a civ decides to offer on their turn...I get the same screens with the ridiculously large max value as well. Here are logs just in case.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/111248/Logs.zip)

**Comment by ilteroi** [comment]
yeah this large number is a magic number, should probably be replaced by "invalid" on lua side.

anyway, @LoneGazebo : got another situation here where napoleon's musketeers are kicking my ass. nevertheless my warscore is +1, and he's offering me a white peace although he's one turn way from taking the egyptian capital from me (which i conquered previously). will see what i can do about the war projection, but maybe some adjustment to the warscore would be useful too.

**Comment by joosegoose** [comment]
In the aforementioned game, I had a warscore of +4 the second I declared war on Songhai. Hadn't even left the leader screen yet, nothing had been killed or pillaged. Warscore is definitely funky right now.

**Comment by ilteroi** [comment]
@LoneGazebo : just found during debugging:

GetWarScore(eLoopPlayer,true) is 80
GetWarScore(eLoopPlayer,false) is -3

something is broken

**Comment by LoneGazebo** [comment]
That's correct, ilteroi. true/false is essentially peace/war. You can't use warscore to determine prewar 'how will this war go?' values.

Re: peace invalidity, it's on my todo list. 
Re: napoleon situation, that's more of an issue of the AI's war state (should realize what it can do and refuse peace).

**Comment by LoneGazebo** [comment]
Joosegoose, warscore decay can allow for +/- at start of war if the war is fairly recent compared to your last one.

**Comment by ilteroi** [comment]
ok, let me summarize the issues here, it's a bit confused

1. AI paying quite much for third party peace
2. AI offering impossible peace. fixed, but at the cost of excluding minors
3. UI for removing minors not working
4. INT_MAX displayed in UI. replace by invalid?
5. GetWarScore values differing between peacetime and wartime. i'll rename the parameter to make it clear what's going on
6. AI making peace when winning. fixed
7. warscore in favor of the losing player. the big one. how can that be?

**Comment by LoneGazebo** [comment]
1. I'm working on that.
2. Don't need to exclude them, as I've fixed that now.
3. That's by design (minors are at a value of zero in a deal, but required to be added.
4. Working on that.
5. That's by design, as the war/peace bool allows the AI to 'predict' a war using projection outside of war.
6. Cool.
7. No idea, unless the log is reading wrong.

**Comment by ilteroi** [comment]
2. they are only excluded if PeaceBlocked() returns true. but i won't interfere in deal AI.
7. maybe the power graph was misleading and they simply built more units than i destroyed. i'll keep an eye on it.

**Comment by LoneGazebo** [comment]
What are your numbers referring to? I don't know that those answers make sense for 1 and 2. :)

**Comment by ilteroi** [comment]
d'oh. it seems markup is so smart, i autoformatted my list :)

that was for 2) and 7)
