### ISSUE TITLE
Water mill description

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1185]
It says in the tooltip that a Water Mill requires Well ("Required Buildings: Well"). Which is wrong, because there is another description in Civipedia saying a Water Mill cannot be built if a city contains Well.
English is not my first language but I'm pretty sure these two statements aren't the same and the first one is wrong.

**Comment by LoneGazebo** [comment]
The fact that the words 'required buildings' are red indicates that they are inverses. It's an EUI thing, don't ask me.
