### ISSUE TITLE
AI capital lost to barbarians

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1187]
Playing latest hotfix. 
Turn 210. Germany loses its capital Berlin to barbarians. Not sure if some bug or disbalance, but in my hundreds of hours of playing Civ5, including ~100 hours with this mod, it never happened before. Germany is left with 4 cities, all the same continent with the capital.

**Comment by LoneGazebo** [comment]
Lots of things can happen in the CP! :)

**Comment by Kolaris8472** [comment]
So you actually made it possible for Barbs to take cities? Does it require the "Barbarians Steal Gold" option?

Since I was just testing this and the vanilla behavior seemed unchanged. If a Barb melee unit attacks a city with 0 hp, they raid some gold and then vanish.

**Comment by LoneGazebo** [comment]
No, I imagine this is another mod he has running.

G

**Comment by ilteroi** [comment]
it's strange though, i've seen in the code "barbarians can't capture cities" but it does happen. from minors and from majors too.
