### ISSUE TITLE
AI has super spy

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1188]
#![2016-01-31_00002](https://cloud.githubusercontent.com/assets/11132095/12701955/a4b63c6c-c7de-11e5-978b-0b9d8cce5223.jpg)
![2016-01-31_00001](https://cloud.githubusercontent.com/assets/11132095/12701954/a4b61dc2-c7de-11e5-948a-1383ddcb07f9.jpg)

Spies had just been unlocked, and I assigned my spy the turn it was available. Here we are, one (maybe two?) turn(s) later and Songhai has managed to steal a tech. It should still be the "establishing surveillance" phase, so not sure how this happened. Logs attached, this is the latest hotfix (w/ EUI).

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/111251/Logs.zip)

**Comment by saamohod** [comment]
The Songhai may have taken the Statecraft Policy Tree, in which case they took a spy early with a policy.

**Comment by LoneGazebo** [comment]
Yep, saamohod is correct.
G

**Comment by joosegoose** [comment]
Opened the save back up, Songhai did not have the relevant policy, having gone Piety instead.

![2016-02-01_00001](https://cloud.githubusercontent.com/assets/11132095/12710254/4dca032e-c87a-11e5-868b-58fa25b8e6ce.jpg)

Maybe it could be something else?
