### ISSUE TITLE
UI issue: choose promotion window

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1189]
it's often annoying to choose a unit promotion because the widget doesn't capture the mouse. so if by chance an enemy unit is hiding behind the promotion icon, you get a combat preview and cannot click on the icon

**Comment by LoneGazebo** [comment]
No idea how to fix that, sadly.

**Comment by ilteroi** [comment]
yeah, not a major issue but annoying. i was hoping it's a simple flag somewhere in the xml

**Comment by LoneGazebo** [comment]
i don't think so. I can look, though.

**Comment by LoneGazebo** [comment]
Can't find a solution to this, closing.

**Comment by ilteroi** [comment]
there is a solution after all, don't know how to include it in the mod though:

[WorldView.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/141436/WorldView.zip)

these files need to replace the ones in assets\DLC\Expansion2\UI\InGame\WorldView

**Comment by ilteroi** [comment]
did you take a look at this yet?

ps: just pushed my latest. all merged.

**Comment by LoneGazebo** [comment]
Yeah, I just don't know where to implement it in EUI (because he changes so much of everything).

I've got your latest - mind giving  me a run-down of changes for the patch notes?

**Comment by ilteroi** [comment]
just use the commit message! no functional changes though, don't know if anybody cares.

**Comment by LoneGazebo** [comment]
Sounds good. I like to have thorough patch notes (and to give credit where credit is due). Also, if there's a bug in your code, I need an alibi so I can throw you under the bus! :dancer:  (just kidding)

**Comment by LoneGazebo** [comment]
Also, you'll love this: the latest EUI (while making some valuable optimizations) breaks the firetuner. I'm beginning to think that EUI is malicious.
