### ISSUE TITLE
Able to make peace when bribed.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1190]
I think you can test this with any war scenario, but basically if you have a war going on with your enemy and you just captured their city, then you can probably assume they're not give you peace that easily, but if one of the AI decides to pay you to make peace with your enemy. It is easily done.

**Comment by LoneGazebo** [comment]
I'm going to tighten up the function a bit, but this is not a 'bug' so much as just the function being a bit too loose at present.
