### ISSUE TITLE
AI capital lost to barbarians

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1193]
I'm not trying to be annoying, but helpful.
Regarding the issue I reported regarding AI German capital being lost to barbarians.
 Gazebo suspected it was caused by another mod I was running and so my report was flagged as "cannot reproduce".
The mods I run do not (should not) bring such outcomes. Those are:
-Useful oil mod
-Infoaddict
-Extra victory conditions
-Faster aircraft animation
-Improved air recon
-Great Prophet historical names
as well as three mods that optimize placement of Natural Wonders at map creation:
-Krakatoa fix, Lake Victoria fix and Gibraltar and Reef optimization
Here is the savegame right after Berlin fell to barbs: 
[Barbarian Berlin.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/111627/Barbarian.Berlin.zip)
Hope it helps.

**Comment by LoneGazebo** [comment]
It was probably a rebel that attacked it- it can happen. Very rare. It's not really anything I can 'do' anything about.

G

**Comment by Iamblichos** [comment]
I think it's actually kind of cool that it happened.
