### ISSUE TITLE
Movement bonus for Songhai

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1194]
Ilteroi,

From what I can tell, the Songhai (and by extension amphibious promotions) seem to gain more movement bonuses for crossing rivers than for moving along them. This seems backwards. Thoughts?

G

**Comment by ilteroi** [comment]
this is in GetCostsForMove() ... not exactly straightforward to understand what's happening.

in any case, there seems to be a distinction between trait and promotion

	bool bFasterAlongRiver = pTraits->IsFasterAlongRiver();
	if(pUnit != NULL)
	{
		bSuperAmphibious = pUnit->isRiverCrossingNoPenalty() && pTraits->IsFasterAlongRiver();
		bAmphibious = pUnit->isRiverCrossingNoPenalty();

**Comment by LoneGazebo** [comment]
Yeah, but I don't think the 'faster along river' part is actually working. Load up with songhai and get to a river. Warriors move two hexes only (used to be three) along a river, but get  more moves if they cross back and forth over the river.

**Comment by ilteroi** [comment]
you're right.

doesn't look like a bug though. 
*superamphibious gives you river crossing at road cost
*amphibious gives you river crossing at double road cost
*war canoe gives you movement into river tiles at cost one

so, how to resolve this? i think all of them should be cost one and that's it

**Comment by LoneGazebo** [comment]
Makes sense to standardize it all.

**Comment by ilteroi** [comment]
yeah, maybe people will complain because it's a net reduction

in other news: ice is passable if within borders, why not apply the same logic to mountains?

**Comment by LoneGazebo** [comment]
That'd be a pretty big nerf to the Inca, one they don't need. Ice is passable because of the continental nature of mapscripts (can't always circumnavigate because of it).

**Comment by ilteroi** [comment]
yeah, don't need to do it, nobody complained :)

**Comment by LoneGazebo** [comment]
hehe yep

**Comment by LoneGazebo** [comment]
Oh, also, I should note that civs with auto-city-connections (songhai and iroquois) have weird AI road building behavior according to funak. Take that for what it is worth.

G

**Comment by ilteroi** [comment]
not impossible.

anyway, war canoe is now "ignore terrain costs along river". amphibious is "cross rivers for one movement point".

pushed.

**Comment by LoneGazebo** [comment]
Sounds grand.

**Comment by Iamblichos** [comment]
Question regarding mountains and Inca:

Why not make mountains a passable entity at some tech level?

Do you consider that a nerf to Inca?

**Comment by LoneGazebo** [comment]
I would, yes.

**Comment by Iamblichos** [comment]
Inca: 10% combat bonus and double movement in mountains (w/ no terrain damage) 

Mountains: passable tech metallurgy(?)

Bring back terrain damage to mountains (-25, instead of vanilla -50).

**Comment by LoneGazebo** [comment]
They can be captured (cities and mountains with roads already passable by anyone).

G

**Comment by ilteroi** [comment]
@Iamblichos : terrain damage is bad, AI doesn't get it

also, for the record, i'm strongly against "treat X as road". note that "ignore terrain cost on X" is a different thing. in fact i'm half of a mind to change this for iroquois too and see how big the insurrection will be.

**Comment by LoneGazebo** [comment]
Ilteroi, I'm making it so that the siege tower acts like a Great General - works pretty well thus far, though I wonder, would it be possible (in the tactical AI 'movegreatgeneral' code) to have the IsCityAttackOnly() element of a unit make the unit (i.e. the Siege Tower) try to get a plot adjacent to a city?

In other words, could we have the Siege Tower, as passed into the movegreatgeneral function, look for safe plots adjacent to an enemy city instead of the second line behind?

**Comment by LoneGazebo** [comment]
Nevermind, I see the spot.

**Comment by Iamblichos** [comment]
huh....didn't realize plot damage was a big no-no.

yeah, I wasn't considering roads into mountains to be any kind of effective way to take a city since it's a one tile entrance.

**Comment by ilteroi** [comment]
i made it so that a city has to have at least one "conventionally passable" plot around it.

**Comment by Iamblichos** [comment]
Yeah I see that for sure...just doesn't seem like any kind of practical way to mount an assault against the Inca.

**Comment by ilteroi** [comment]
well, all mountain cities will be very poor, no chance to win the game that way, so it's not a big danger

**Comment by ilteroi** [comment]
regarding traits, it's confused (surprise!) we have 

* IsMountainPass() for unit movement (ignore mountain terrain cost)
* IsAbleToCrossMountainsWithGreatGeneral() and IsAbleToCrossMountainsWithRoad() -> used to determine whether you may enter a mountain plot at all
* IsRiverTradeRoad() for city connections (river plots count as route)
* IsFasterAlongRiver() for unit movement (ignore river terrain cost)
* IsMoveFriendlyWoodsAsRoad() for connections and movement

whimsical change: IsMoveFriendlyWoodsAsRoad() is now IsWoodlandMovementBonus(). forest and jungle movement cost ignored, count as route, regardless of plot ownership. so the net worth should be equal.

mountain trait naming / overlap is also unsatisfactory, but that's for another day

**Comment by LoneGazebo** [comment]
Cool. Does this affect the database in any way (aside from one you mentioned)?

**Comment by LoneGazebo** [comment]
All in 2-2.
