### ISSUE TITLE
AI World Congress Priorities

### ISSUE THREAD

**Issue by Kolaris8472** [LoneGazebo/Community-Patch-DLL#1196]
The AI seems to put too high a priority on Sanction votes (not proposals). Rome could have passed its World Religion proposal, or Songhai its Cassus Belli proposal, but they put all their votes into failing a Sanction Ottomons proposal. The Ottomons are in last place and aren't even friends or trade partners with either of the two.

**Comment by LoneGazebo** [comment]
Addressed this in latest patch.
