### ISSUE TITLE
observations in infoaddict

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1197]
denmark appears to be on a roll - they didn't conquer anything though. just beefed up their military

![image](https://cloud.githubusercontent.com/assets/1358966/12723940/e5c6eb92-c90b-11e5-8f63-9cdecd6a399c.png)

however, they cannot pay for it - this is suicide by maintenance

![image](https://cloud.githubusercontent.com/assets/1358966/12724050/620f6972-c90c-11e5-97c1-e7bbc5af82ae.png)

so this is what it looks like

![image](https://cloud.githubusercontent.com/assets/1358966/12724284/825d277c-c90d-11e5-8b0c-aacdbdcde2f9.png)

note they are still building more units! maybe there should be condition that you can't build units when your deep in negative gpt.

also, some civs don't spend their faith

![image](https://cloud.githubusercontent.com/assets/1358966/12723890/bc72a3bc-c90b-11e5-9044-a575364d788c.png)

venice has maxed out piety (although they never founded a religion), so they should be able to generate artists at the very least. but no great people at all appear in the production list.

babylon has a choice of four different types of great person, but apparently chooses none.

**Comment by LoneGazebo** [comment]
What version are you on? The AI is strongly discouraged from building units/buildings when in debt. I also fixed some faith purchase stuff in latest version.

**Comment by ilteroi** [comment]
that's 1/29 - so maybe it's fixed

another thing - incorrect number in UI

![image](https://cloud.githubusercontent.com/assets/1358966/12724975/bfdf031a-c910-11e5-9401-02a428803604.png)

![image](https://cloud.githubusercontent.com/assets/1358966/12724999/e04abe82-c910-11e5-95c7-ec11e9f66e08.png)

![image](https://cloud.githubusercontent.com/assets/1358966/12725016/f04616a6-c910-11e5-8eec-642aaa5b4279.png)

i guess it'd be best to always show 45

**Comment by LoneGazebo** [comment]
What's the center one? The happinessinfo.lua UI?

Yeah, 1/29 had some big problems with unit/building production. I fixed most/all bugs related to that. I'm really happy with AI prioritization now.

G

**Comment by LoneGazebo** [comment]
HomelandAI logs:

190, connection between Hamath and Ulsan because of sea blockade
190, The Huns, No connection between Ulsan and Sam’al because of sea blockade
190, The Huns, No connection between Ulsan and Boston because of sea blockade

Seeing stuff like this a lot in the homeland AI, unfortunately ulsan is a landlocked city, and there are no barbarians or enemy units even close to Hamath. Seems to be happening haphazardly (and without regard for landlocked nature of cities).

Thoughts?

**Comment by LoneGazebo** [comment]
Also, fixed the UI issue above.

**Comment by ilteroi** [comment]
did you get my message? tried to reply on the phone but i doesn't seem to have worked.

anyway. the logs were an attempt to check what's going on with the sporadically missing city connections. unfortunately, landlocked cities are sea-blockaded by default, to there's a lot of false positives in there.

i haven't had time to analyze the results yet. might take a while too, quite busy these days. you can disable the logs if it bothers you

**Comment by ilteroi** [comment]
another surprise. greece was quite successful, conquered their whole continent, but some time later their happiness plummeted.

![image](https://cloud.githubusercontent.com/assets/1358966/12766355/ba2d91f4-ca03-11e5-8396-c973b0227c4f.png)

may be fixed in latest version, but building selection in rhodes was obviously strange (no barracks, no university)

also no specialists despite gold focus

**Comment by LoneGazebo** [comment]
If the empire is unhappy and in debt it'll avoid excessive specialists and buildings, even with focii. Still, we may need more intelligent decision making there.

**Comment by LoneGazebo** [comment]
Is it possible that the auto-sea-blockaded element could affect the unhappiness from city connections modeling for trade routes?

**Comment by LoneGazebo** [comment]
Fixed UI bugs, we'll pick up connections later if the bug resurfaces.
