### ISSUE TITLE
Religious National Wonder not buildable/visible

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1198]
I'm blanking on what it's called (Holy Council in this case), but either I cannot build the wonder in my Holy City or the EUI update no longer shows it greyed out in the queue until I reach 20% global followers. The first would be a bug and the second a very unfortunate removed feature.

![2016-02-01_00004](https://cloud.githubusercontent.com/assets/11132095/12737567/4f2328ae-c91f-11e5-8d04-a0dff742449d.jpg)
![2016-02-01_00005](https://cloud.githubusercontent.com/assets/11132095/12737568/4f23a248-c91f-11e5-9848-de041243db7f.jpg)

This city is unique in that it was captured by America at one point and I had to recapture it, which has me concerned for a possible bug. Logs attached.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/113303/Logs.zip)

**Comment by joosegoose** [comment]
For what it's worth, I have not noticed this in any of my other games. Either it was connected to losing and recapturing the city in some way, or it was a strange one time rarity.

**Comment by LoneGazebo** [comment]
Possible, who knows. Going to close for now, but we'll come back to it someday if needed.
