### ISSUE TITLE
Clearing camps not generating culture with might opener.

### ISSUE THREAD

**Issue by Llednar-Twem** [LoneGazebo/Community-Patch-DLL#120]
When the barbs guarding it moved out of a camp to attack one of my units, I was able to move in with another unit and take it.  Doing so yielded no culture.  After that happened I started paying closer attention while killing barbs in camps and saw that while the barbarian gave the normal culture yield, the camp was giving nothing.

The might opener still claims that clearing camps gives culture, and not getting it is crippling might's culture gain, which was already weakened by moving culture on city capture to the finisher.  As such, I'm hoping this is a bug with the effect and not with the description.

**Comment by LoneGazebo** [comment]
Is bug. I'll fix for next version. 

Barb moving out of camp issue is simply bad tactics on the barb's part. It happens sometimes.
G
