### ISSUE TITLE
The Huns

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1202]
Not sure if bug or intended.
 Captured barbarian Horsemen (Hunnic UA to capture barbs) do not require Horse resource. 
 I at some point had more than 10 Horsemen and only 2 Horse resource. Despite that the units were healing ok and the tooltip didn't mention that the 2 Horse was used on the Horsemen.

**Comment by LoneGazebo** [comment]
That's fine - barb horsemen don't cost any resources.
