### ISSUE TITLE
CTD on CvCityBuildings* CvCity::GetCityBuildings()

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1203]
Got a crash dump on player do turn that pointed to this function: CvCityBuildings* CvCity::GetCityBuildings()

It traces into CvPlayerCulture::MoveWorkIntoSlot and then on to player do turn and CvDllupdate, etc.

Looking at the function CvPlayerCulture::MoveWorkIntoSlot, shouldn't there be a check for if pToCity and pFromCity. Adding the check passes without CTD.

**Comment by LoneGazebo** [comment]
Yes, but it shouldn't be passing in 'bad' values anyways...

**Comment by LoneGazebo** [comment]
Can you decipher if the bad pointer is for the 'to' or the 'from' city?

**Comment by Iamblichos** [comment]
hard to tell..still learning this....but it's definitely looking for the m_owner

**Comment by Iamblichos** [comment]
Well I know the function is working with my correction as the AI is swapping great works with and I'm getting the notifications.

**Comment by LoneGazebo** [comment]
Incorporated fixed in 2-2b
