### ISSUE TITLE
[CBP 23-01] AI try do give "nothing"

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#1205]
I'm playing with the Modpack 23-01 full EUI, so maybe the problem is no longer present in the last beta.

Sometimes, AI propose to give "nothing", and since you cannot accept "nothing" ("void" trade are not allowed), you have to refuse and have some dimplomatic penalties.

I'm not sure to have correctly enabled logs (first time) so I also join a save (you just need to load, press "End the Turn", and wait for the beginning of the new turn, it worked each times I've tried it)

[BUG_gift_nothing.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/114803/BUG_gift_nothing.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/114804/Logs.zip)

PS : I don't realy understand why you cannot accept "void" trades, and why refusing a gift make the AI hating you,

**Comment by LoneGazebo** [comment]
Modpacks have problems like this, not sure why. Not much I can do about it (as I don't make the modpacks).
