### ISSUE TITLE
Worlds Fair Projects Contributions

### ISSUE THREAD

**Issue by Kolaris8472** [LoneGazebo/Community-Patch-DLL#1209]
I remember seeing this issue reported before, but I can't find it now. If it's not fixable, apologies. 

Production levels going into the project -
![2016-02-03_00001](https://cloud.githubusercontent.com/assets/16279892/12777813/054fec6c-ca14-11e5-9568-b2e99eec3b71.jpg)

AIs production the turn I start the project. So it's not that they get "first go" at it. Plus it comes to me at 0%. 
![2016-02-03_00002](https://cloud.githubusercontent.com/assets/16279892/12777828/1f507fb4-ca14-11e5-96fb-5006501f2e3c.jpg)

My contribution going into the last turn is 6,327 - 
![2016-02-03_00004](https://cloud.githubusercontent.com/assets/16279892/12777846/3179a742-ca14-11e5-9132-06660cc4825b.jpg)

My final contribution is 6,327. I would have ended up with ~9,600. 
![2016-02-03_00005](https://cloud.githubusercontent.com/assets/16279892/12777877/5877a6dc-ca14-11e5-8e98-c8159055b4fb.jpg)

If you do the math you can see it came to Rome's turn at ~18, 560 and his contribution took it over the limit, instantly stopping the project before players after him get a chance to contribute. He even gets full credit for the overflow. Essentially, Rome gets 3 turns to contribute while I only get 2. 

Obviously this isn't ideal behavior; I'm going to go back and manipulate my contributions to see if I can game it into ending on me.

**Comment by LoneGazebo** [comment]
I'll take a look, but this code is untouched from BNW, so this may be intended behavior on Firaxis's side (not a justification, but also not a bug).

**Comment by Kolaris8472** [comment]
Alright, thanks. Maybe as a bandaid, substantially increase the total production required for projects like this? A 1-turn discrepancy becomes less of an issue if the project goes for more turns.

**Comment by LoneGazebo** [comment]
They are already substantially longer than BNW, with added length from era difference of project v. current era.

**Comment by Kolaris8472** [comment]
What about gamespeed?

**Comment by LoneGazebo** [comment]
Yep.
