### ISSUE TITLE
Scouts not gaining exp from natural wonders.

### ISSUE THREAD

**Issue by Llednar-Twem** [LoneGazebo/Community-Patch-DLL#121]
I've just confirmed what I already suspected was happening, but wasn't really sure of until now.  Discovering natural wonders with scouts doesn't seem to actually give them any experience.  I previously thought I had perhaps simply not been noticing, but this time I know it's the case as my newly trained scout was below five exp after the wonder's discovery.

**Comment by LoneGazebo** [comment]
I've noticed this, and fixed it for next version.
G
