### ISSUE TITLE
Bad citizen allocation

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1210]
With default focus, the governour would rather employ citizens as workers that working slots. 
Is this intentional, because workers don`t provide unhappiness and my empire is unhappy?

**Comment by LoneGazebo** [comment]
Correct.

**Comment by LoneGazebo** [comment]
Also has to do with food consumption of laborers v. specialists.

**Comment by Iamblichos** [comment]
It might be a chore for some, but you are going to want to fill some specialists to balance happiness issues for sure. Default is pretty good for growth and production, but may not always fill current needs.
