### ISSUE TITLE
Wrong citizen number

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1211]
My capital has two more citizens than it shows: 
![2016-02-03_00002](https://cloud.githubusercontent.com/assets/16065630/12796129/9040b0c8-cabd-11e5-82c4-8caa3e51c3a6.jpg)
Here is what I did:
The city was at zero food, and I build s settler, starving the city. When the settler finished, I got the starvation warning, and adjusted the city to positive food again.
Somehow it had already changed the citizen number to reflect the expected population loss, but this necer occured.
(The fact that it is off by two is because I did it twice).

**Comment by LoneGazebo** [comment]
Hmm...
