### ISSUE TITLE
Maintencance cost when diplo unit online

### ISSUE THREAD

**Issue by ricanuck** [LoneGazebo/Community-Patch-DLL#1213]
Observed this since 1.29, whenever you build a diplo unit the average maintenance cost jumps extraordinarily, and decreases again after diplo unit is used. I am talking huge jumps in percentage, to the point of making a +220GPT into a +120GPT after building ONE diplo unit. Far off, and not comparable with the number resulting of building any other unit instead, at that very same moment.

Easy to reproduce, so I don't attach anything.

**Comment by LoneGazebo** [comment]
Diplo units have extra maintenance associated with Era.

**Comment by ricanuck** [comment]
Yes, I understand that, but making GPT jump 100 or more gold for one unit is a too much to be WAD... or is it?

**Comment by LoneGazebo** [comment]
Well, it's not a bug, but rather balance.

**Comment by ricanuck** [comment]
Good to see it fixed, I had an ambassador just now that decreased my GPT from 290 to -17, a little too much for an ambassador...
