### ISSUE TITLE
Not able to pillage trade route

### ISSUE THREAD

**Issue by ricanuck** [LoneGazebo/Community-Patch-DLL#1214]
I had this one just happening to me: I am at war with Venice, and could not pillage a trade ship right in front of my ironclad (on top, I mean). Tooltip said that I cannot pillage a trade route before declaring war on the owner, but I was already at war with Venice.

Only particularity of the scenario was that the war was the result of a negotiation with Attila (peace with a CS ally of mine in exchange for a DoW on Venice from my part)... perhaps that traded DoW created a strange pseudo-war status that disabled the pillage function for me?

**Comment by ricanuck** [comment]
P.D.: this was version 2.1

**Comment by LoneGazebo** [comment]
What era? Had venice founded a corporation? One of the corps makes your trade units immune to pillaging.

G

**Comment by ricanuck** [comment]
Have to check about the corp, but the pillage tooltip stated in red that I could not pillage because I could not declare war on owner due to a deal I had (5 turns left) which was basically the counter for the Traded DoW... (which in fact, was traded as a DoW in 10 turns but became effective immediately, possibly being another bug that may trigger this one...?).

**Comment by LoneGazebo** [comment]
The tooltip may not have been accurate, not sure. Check the corp for me before I move on this.

**Comment by ricanuck** [comment]
UPDATE: checked corps, in fact I am the one that has Firaxite Materials (making my trade routes invulnerable).
Looks like a definite bug, possibly tied to the traded DoW (non-traditional DoW).

**Comment by LoneGazebo** [comment]
Bug is actually funny - having that corporation accidentally made it impossible to pillage enemy trade routes (wrong pointer used). Ha.
