### ISSUE TITLE
Great Improvements not providing strategic resources if placed upon pillage improvement

### ISSUE THREAD

**Issue by Guynemer** [LoneGazebo/Community-Patch-DLL#1215]
Seen in the 2/1 Beta:

Barbarians pillaged my horse pasture.
I settled a Great Scientist on the pillaged pasture, rather than repairing it with a worker.
The Academy provided science as normal, but did NOT provided the horses as it should.

Other mods used: InfoAddict, Quick Turns.

Away from gaming computer right now, I might be able to provide a save later if necessary.

**Comment by LoneGazebo** [comment]
Thanks!

**Comment by Guynemer** [comment]
Unfortunately, I will not be able to provide a save game.  That particular game CTD on me several turns later, and the autosave was overwritten when my wife played a bit yesterday.

**Comment by Guynemer** [comment]
Aha!  I was wrong.  It was still in the previous autosaves folder

The Academy to the SW of Amsterdam.

[0ldAutoSave_0230 AD-0850.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/118482/0ldAutoSave_0230.AD-0850.zip)

**Comment by LoneGazebo** [comment]
I think this is tied to #1126. Closing, as I've solved that issue.
