### ISSUE TITLE
UU Civpedia Strategy sections

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1216]
For reasons, I have some time and with access to an extra monitor, but not enough to really play, so I went through all the UUs and CS gift units and marked down all wrong stuff in the Strategy sections. This doesn't include any 'lack of information' stuff (ie Jaguars not mentioning being stronger) just things that are all the way incorrect. If you want both, I'll make another list. If not, I'll try to do UBs next. This kind of stuff is a lot easier when I can use the second monitor tho.

Companion Calvary say they are more powerful than Horseman, but are less 15 to 14.
Pathfinder isn't more expensive than Scouts.
Atlatlist still says it can attack twice.
Babylonian Bowman says it replaces and is stronger than the Archer. 
This might be a technicality, but the Legion isn't the strongest melee unit in the Classical with the Berserker and Maori on Metal Casting. Of course, that's the end of the Classical.
Maori Warrior talks about 'build early' as tho it is still a Warrior replacement.
Naga Malla says it can move thru terrain without penalty.
Cho Ko Nu says it is less powerful than the Crossbow, but it has more RCS 19 to 18 and the same CS.
Great Galleas says it can only be built by Venice. Also mentions cost even tho its unbuildable. Actually, unlike the other CS units it has a listed cost that isn't just 1. Battering Ram does too. Don't think that matters, but idk.
Mand Cav has one more CS than the Knight, not exactly the same stats.
Like Great Galls, the Turtle Ship has a listed cost.
Carolean are a Ren unit, not Industrial.
Janissary says it heals all damage on kill, the promotion says only 50.
Minuteman doesn't get a combat bonus in rough terrain.
Musketeer isn't 'the' most powerful Ren foot unit anymore, Impis and Caros on that level now.
Ships of the Line are the same cost as Frigates.
Tercio isn't stronger than the Musket and mentions build cost.
Comanche mention being cheaper.
Cossack isn't the same strength as Cavalry, a bit stronger at 42 to 40. When I played Russia, I didn't really find this that meaningful, but that's of course a separate deal.
Mehal Sefari don't get a bonus to rough terrain fighting. Both this and the Minuteman get Drill 1, which I guess used to be rough terrain bonuses?
Mehal Sefari replace Fuses, not Rifles, and are the same cost.
Khan mentions moving at same speed as the Keshik.

**Comment by LoneGazebo** [comment]
Awesome, thanks!
