### ISSUE TITLE
[Feature request] "City connection established"

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1217]
Would it be possible to mod the interface behaviour in the following way: 
 When clicking on a notification "City connection established" it brings you to the mentioned city. Makes lots of sense IMHO, especially when your empire grows big and you lose track of cities' names and  location.
![2016-02-04_00003](https://cloud.githubusercontent.com/assets/16341598/12806919/14a39632-cb13-11e5-9ec1-a8a7f0bc844a.jpg)

**Comment by LoneGazebo** [comment]
No, in the DLL there's no linker modeling for that Notification.
