### ISSUE TITLE
Pathfininding calculator

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1218]
It shows wrong number of turns to get to a point. E.g. it shows that unit will be further away after embarkation than it actually gets to.
![2016-02-04_00004](https://cloud.githubusercontent.com/assets/16341598/12809047/84942324-cb24-11e5-8767-d3733974aec5.jpg)
![2016-02-04_00005](https://cloud.githubusercontent.com/assets/16341598/12809048/8535b450-cb24-11e5-8648-85147dc9e8f7.jpg)

**Comment by LoneGazebo** [comment]
If you're on the modpack, it's out of date.

**Comment by saamohod** [comment]
To the best of my knowledge I'm not using the Multiplayer Modpack. It's Beta Feb-2 (well, at least Civilopedia entry on Haudraugt is in my game).
 Submods I use:
-Infoaddict
-Faster aircraft animation
-Extra victory conditions
-Improved air recon
-Great Prophet historical names
- Krakatoa Fix, Lake Victoria Fix, Gibraltar and Reef optimization (seem to be only needed at map creation)
-Useful oil mod

![2016-02-04_00009](https://cloud.githubusercontent.com/assets/16341598/12819109/65944bdc-cb62-11e5-956a-93ac4efcd5d2.jpg)

**Comment by ilteroi** [comment]
hmm. will try to reproduce but not before next week

**Comment by ilteroi** [comment]
ps: forgot to push my latest changes from a few days ago. (trait changes for iroquois and songhai)

**Comment by LoneGazebo** [comment]
I thought you pushed those?

**Comment by ilteroi** [comment]
should be fixed. whoever invented the movement rules for embarkation should be whipped
