### ISSUE TITLE
Holy Sites give no tourism

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1219]
Toggling a Holy Site landmark in City View doesn't change tourism yield (city's yield as well as general yield). Seems it doesn't provide the claimed +3 Tourism from the Landmark tile. The culture and faith are ok.
![2016-02-04_00006](https://cloud.githubusercontent.com/assets/16341598/12809111/04e01aba-cb25-11e5-9df8-ad398bccdaa9.jpg)
![2016-02-04_00007](https://cloud.githubusercontent.com/assets/16341598/12809113/05b954ba-cb25-11e5-9ea0-16e71c4bb79f.jpg)

**Comment by Kolaris8472** [comment]
It should update on the next turn. Not that that's how it _should_ work, but it's been consistent for me.

**Comment by saamohod** [comment]
Nope, it doesn't update the next turn, nor the turn after that.

**Comment by Kolaris8472** [comment]
But did it already update? Maybe the Tourism is independent of the tile being worked, so you've been getting the bonus from when the Holy Site is built. 

(Not trying to be contrarian, just trying to figure out why yours is working different than mine)

**Comment by saamohod** [comment]
No idea really. Just stating the fact that Culture and Faith yield work as supposed to, but Tourism seems to broken and gives no yield.

**Comment by LoneGazebo** [comment]
Works for me, sorry. If using the modpack, I'd recommend against it for now.

**Comment by saamohod** [comment]
To the best of my knowledge I'm not using the Multiplayer Modpack. It's Beta Feb-2 (well, at least Civilopedia entry on Haudraugt is in my game).
 Submods I use:
- Infoaddict
- Faster aircraft animation
- Extra victory conditions
- Improved air recon
- Great Prophet historical names
- Krakatoa Fix, Lake Victoria Fix, Gibraltar and Reef optimization (seem to be only needed at map creation)
- Useful oil mod

I attach here a savegame which might prove my point


[no yield.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/117649/no.yield.zip)
