### ISSUE TITLE
Not receiving free military units after random event

### ISSUE THREAD

**Issue by mmermerkaya** [LoneGazebo/Community-Patch-DLL#122]
For example when I pick the choice that lets me lose influence with a city state and receive a free unit, I lose the influence but don't receive the unit. 

I'm using all four of the core mods, Events and Decisions, EUI, More Luxuries, and Trade Routes Enhancements Mod.

**Comment by LoneGazebo** [comment]
This is an issue with E&D, and needs to be reported there.
G
