### ISSUE TITLE
CTD on CvAStar::AddToOpen

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1221]
Happened on AI turn:
![ctd](https://cloud.githubusercontent.com/assets/14372214/12824338/51533452-cb36-11e5-81b2-d49e184c4955.png)

**Comment by Iamblichos** [comment]
Also, couldn't reproduce it on a reload and not changing anything.

**Comment by ilteroi** [comment]
auto watch says the this pointer is invalid. seems to be some kind of memory corruption. not necessarily caused by the pathfinder itself. hard to tell.

**Comment by Iamblichos** [comment]
Interesting you said, as I rebooted and lowered my memory frequency. I'm running all slots full which can be taxing on the memory controller. Maybe that's all it was.

**Comment by Iamblichos** [comment]
Haven't seen this again....going to close out as I think it was a hardware issue on my side.
