### ISSUE TITLE
City:HasAnySpecialist()

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1222]
A hopefully simple and painless request for city:HasAnySpecialist(), for whenever you can. Basically, city:HasSpecialist() but without specifying what Specialist slot is filled specifically. Much obliged!

**Comment by LoneGazebo** [comment]
Yep. It'll be GetTotalSpecialistCount(), which you can use as a GetTotalSpecialistCount() > 0 statement.

This will give you the total number of specialists in the city as well, should that be useful.

**Comment by JFDaly** [comment]
Oh, well that would be immensely more useful. Thanks!

**Comment by LoneGazebo** [comment]
Yep!
