### ISSUE TITLE
Camel Archer and Heavy Skirmisher (v2/5 beta)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#1224]
1.
Camel Archers don't upgrade to Cuirassiers but to Volley guns.

cf.
(2) Community Balance Patch\Balance Changes\Units\UnitChanges.sql
Line: 450-452

```
	UPDATE Unit_ClassUpgrades
	SET UnitClassType = 'UNITCLASS_VOLLEY_GUN'
	WHERE UnitType = 'UNIT_ARABIAN_CAMELARCHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );
```

2.
It seems to me that Heavy Skirmishers are too vulnerable compared with Camel Archers.

Melee Combat Strength
- Heavy Skirmisher: 8
- Camel Archer: 18

Is this a typo or a balance issue?

**Comment by LoneGazebo** [comment]
I'll fix. Latter is a balance concern.

**Comment by 8h42** [comment]
Got it.
I'll give it a try.
Thank you!
