### ISSUE TITLE
Mongolian Cuirs

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1225]
Mongol Cuirs don't get the Steppe Nomads/Mongol Terror promotion. Since Mongolia used to be my very favorite side, I'm hopeful this isn't intentional lol.

Didn't realize my list the other day would lead to a few balance changes! Thought I was just helping with typos lol. Mehal still say they are cheaper tho, btw. Saw that cause I'm bout to finally try an Immortal Peacemonger Science game.

**Comment by LoneGazebo** [comment]
The balance changes were oversights on my part, trying to keep the same relative balance for units while also increasing stats for CBP, etc.

I'll fix the Mongols, yep yep.
