### ISSUE TITLE
Connected coal

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1226]
There is something very strange going on with coal. 
Two patches of 7 were revealed under Kashbas. 2 are from slater mill.
The weired thing is, that the ones under the Kashbas are shown as connected (the 7 is green), yet I don`t have them - I have only 2.
![2016-02-05_00002](https://cloud.githubusercontent.com/assets/16065630/12858433/7b43c856-cc50-11e5-92b9-4518c6bc13d8.jpg)

**Comment by LoneGazebo** [comment]
Huh.

**Comment by LoneGazebo** [comment]
Which version? Also, save?

**Comment by Der-Zorn-Gottes** [comment]
Version 2/2.

[Speicherstand.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/119863/Speicherstand.zip)

**Comment by TechpriestEnginseer** [comment]
This has been a bug since vanilla.

**Comment by LoneGazebo** [comment]
That helps, actually. I'll look at the reveal tech (I think it is in cvteam) and see what I can do.
G

**Comment by LoneGazebo** [comment]
Found the bug. The Team tech processing was never updated by Firaxis to account for non-specific linking improvements! Blegh.
