### ISSUE TITLE
Progress finisher doesn't scale with Gamespeed.

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#1227]
It seems to me that Progress finisher doesn't scale with gamespeed as in the title. As the birth rate and interval between it is highly dependent on game speed, this value be scaled

**Comment by LoneGazebo** [comment]
Should be, but I can check.

**Comment by LoneGazebo** [comment]
I checked, and it scales:

```
int iYield = GET_PLAYER(getOwner()).getYieldFromBirth(YIELD_GOLD) * iEra;
					iYield *= GC.getGame().getGameSpeedInfo().getTrainPercent();
					iYield /= 100;
```
