### ISSUE TITLE
Events and Decisions Support?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1229]
Maybe I forgot or something, but what ever happened to the Events and Decisions that was customized for CBP back November -ish?

I feel like working on it to make it compatible and balance since I'm more comfortable with LUA now.

**Comment by Hokath** [comment]
Here's a version i found
[Events and Decisions (CBP Version).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/120656/Events.and.Decisions.CBP.Version.zip)

**Comment by TechpriestEnginseer** [comment]
Ah this looks good. My plans are to as of now:

- Begin the process of having it updated to the latest version possible.
- Reforms the "Initiate Tax Reforms" into a toggled decision. (Gold per citizen yields + unhappiness modifiers) AIs is supposedly to toggle back their decision if they ever hit at least below 0 happiness.
- "Toggleable decisions" 
- Bring back unique units with decisions enacted.

**Comment by Hokath** [comment]
love your ideas
there's scope for some cold war esque decisions in the late game.

**Comment by LoneGazebo** [comment]
Make sure to run updates by the mod-maker - some modders are starting to get grumpy about modsmods these days.

**Comment by LoneGazebo** [comment]
Closing, as this should be discussed in the subforum. :)
