### ISSUE TITLE
Technology trade bug

### ISSUE THREAD

**Issue by mmermerkaya** [LoneGazebo/Community-Patch-DLL#123]
When the AI offers some stuff in exchange for a tech and I select accept, the tech disappears from my side of the deal, and the AI says something like "That's not a fair deal" because he thinks I proposed the same deal without the tech.

Something similar happened when a DoF'd civ offered me a free luxury resource. I accepted, and he did the same thing, telling me that the deal is not fair although he just offered it himself.

**Comment by LoneGazebo** [comment]
Using the latest version?
G

**Comment by mmermerkaya** [comment]
I was when I posted this. I'll try again with the new version in the next couple of days and let you know.

**Comment by Finarvi** [comment]
I have the same. When I find good offer for tech with AI it removes it from trade saying that it's unucceptable but when I add it back and click 'propose' then deal is made.

**Comment by LoneGazebo** [comment]
It sounds like a lua issue with the EUI implementation – in short, the buttons being pressed aren't submitting the right values to the DLL. I'll dig deeper and see what I can find. Thankfully, if it is a LUA issue, it'll be savegame compatible.
G
