### ISSUE TITLE
Cannot pillage enemy caravan when friendly caravan present

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1230]
Pretty rare "bug", probably dates back to vanilla I'm sure. As you can see I have an enemy caravan right in front of me, but I can't pillage due to another caravan coincidentally being on the exact same tile. Note: the screens don't make it clear now that I think of it, but I'm at war with the Inca.

![2016-02-07_00001](https://cloud.githubusercontent.com/assets/11132095/12871326/f0412e2a-cd39-11e5-9459-9de36d0cf924.jpg)
![2016-02-07_00002](https://cloud.githubusercontent.com/assets/11132095/12871327/f0414c8e-cd39-11e5-8e96-209af4ae6cdd.jpg)
![2016-02-07_00003](https://cloud.githubusercontent.com/assets/11132095/12871325/f040f6ee-cd39-11e5-8c25-c81cffb8b011.jpg)

**Comment by LoneGazebo** [comment]
Vanilla bug, yep (only looked at first unit on plot). Fixed.
