### ISSUE TITLE
Landship civilopedia entry 

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1231]
It mentions Tanks as an upgrade unit of Landship twice.
![2016-02-07_00001](https://cloud.githubusercontent.com/assets/16341598/12871909/2b84e36a-cd98-11e5-8954-e000ba9fb756.jpg)

**Comment by saamohod** [comment]
This can be achieved by entering Civilopedia from game setup menu. Right click (see the screenshot)
![2016-02-09_00001](https://cloud.githubusercontent.com/assets/16341598/12910354/c523d654-cf12-11e5-9af5-1464d00a2896.jpg)
.

**Comment by LoneGazebo** [comment]
Doesn't do it for me, sorry.
