### ISSUE TITLE
AI doesn't construct Towns (Merchant Improvements) on Roads/Trade routes.

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#1232]
Basically title, happened in two games in a row - once with Polynesia, and in another game also with Polynesia. They had roads to some cities but decided to just put the Great improvement in a seemingly random spot.

Towns were not only not on roads, but also in pretty weird places which I don't think any Caravan could reach, effectively turning those tiles from awesome into mediocre. AI should be encouraged to put the Towns on roads and send Food/Production caravans from city to city to get the Towns/Villages to give them lots of yields.

**Comment by LoneGazebo** [comment]
They know how. Happens some times. Humans do it too.
