### ISSUE TITLE
ill-fiiting diplomacy text

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1235]
i just defeated attila, and he asks for peace:

![image](https://cloud.githubusercontent.com/assets/1358966/12875942/75869ad2-cdf5-11e5-82fb-6b72d7c6f7e1.png)

but the text suggests that i'm the one to pay up. maybe personality, maybe a mix-up?

in other news: just pushed some fixes. less suicidal civilians.

**Comment by LoneGazebo** [comment]
Cool, I'll merge up. Did you happen to see #1233? Possibly related to the diplo changes you made last week? 
Also, any outstanding issues I can close? I'm always unsure as to which are close-able and which are still TBD.

G

**Comment by LoneGazebo** [comment]
One more thing - I'm having a hard time getting siege towers to make their way to the front lines (if not actively involved in an operation). Any ideas?
