### ISSUE TITLE
You are settling too close to us

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#1236]
Since the change to the function a few beta releases ago, the AI thinks that when they settle towards you, YOU broke your word and settled too near them.

here is a save.
https://drive.google.com/open?id=0B9Y5ivaA0M6dd00weWVxSWpWWk0

**Comment by LoneGazebo** [comment]
haha, yes.

**Comment by AnastaseAlex** [comment]
everyone hates me due to that

**Comment by AnastaseAlex** [comment]
Also, it seems they mainly want to settle towards me, while there are still huge areas of land with good resources they could be settling...

**Comment by LoneGazebo** [comment]
Because forward settling is a strategy! :) Anyways this should be fixed.
