### ISSUE TITLE
GetTotalSpecialistCount() issue

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1237]
I'm having some trouble with GetTotalSpecialistCount(), specifically, with getting it to work - so this isn't a problem with the CP, per se, but I was hoping you'd have some insight.

I had to reinstall CiV, but upon returning to everything, GetTotalSpecialistCount() has inexplicably stopped working; returning "attempt to call method... (a nil value)" - so as if the function didn't exist. This is with a fresh install of the 5th Feb. beta, tested both from the installer and from the direct download, deleted cache... It was working yesterday on this very version... Any thoughts?

**Comment by LoneGazebo** [comment]
Hmm...what's your database log look like? Any errors in that? Specialist database okay?

**Comment by JFDaly** [comment]
No database errors, and the Specialists are all there in the database.

**Comment by LoneGazebo** [comment]
Hmm...no clue, honestly. Trying it in firetuner or in lua? Might check to make sure the firetuner is in right state?

**Comment by JFDaly** [comment]
Tried both. The function is called from a Lua file, called by the City View. Invoking the function from Firetuner results in the same error. Real mystery.

**Comment by LoneGazebo** [comment]
That's bizarre. I'm releasing another beta tonight, so we'll see if that fixes it (maybe)?

G

**Comment by JFDaly** [comment]
Hope so - I'll let you know anyway.

**Comment by JFDaly** [comment]
As mysteriously as the bug emerged, so too it disappears with the latest beta.
