### ISSUE TITLE
City Player:GetCityByID(CityID city)

### ISSUE THREAD

**Issue by GrayPockets** [LoneGazebo/Community-Patch-DLL#1238]
The [City Player:GetCityByID(CityID city)](http://modiki.civfanatics.com/index.php?title=Player.GetCityByID_(Civ5_API)) method does not appear to be working correctly when the CPP is installed. I specifically tested with the CPB but without EUI. I did not attempt with Core only.

As discussed in [this comments thread ](http://steamcommunity.com/sharedfiles/filedetails/?id=281728572), this method is always returning nil. It was causing a problem with the [Extra Victory Conditions](http://steamcommunity.com/sharedfiles/filedetails/?id=281728572) mod.

**Steps to Reproduce**
1. Install CPP /w CPB no EUI
2. Install Extra Victory Conditions
3. Create a Religion
4. Review the Victory Progress overview
5. See that it shows no followers listed for that religion.

**Workaround** Use [iterator(City) Player:Cities()](http://modiki.civfanatics.com/index.php/Player.Cities_(Civ5_API))

This method was used by ReligiousVictory.lua. I am attaching two copies of ReligousVictory.lua, one working and one fixed.

[ReligiousVictory.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/122641/ReligiousVictory.zip)

**Comment by LoneGazebo** [comment]
This is some great work - actually reveals another bug we were experiencing. I'm going to page Ilteroi and try to fix this on the DLL side so that there's no workaround needed.

**Comment by ricanuck** [comment]
Smells like the City Banner religious tooltip freeze... is it?

**Comment by LoneGazebo** [comment]
Don't think so, but it might be.

**Comment by LoneGazebo** [comment]
It is related to the blank 'who's winning' popup, though.

**Comment by ricanuck** [comment]
Ha! Of course, the NIL makes the list empty! Genius.

**Comment by LoneGazebo** [comment]
Ilteroi, another thing: mods like Really Advanced Setup use custom code to 'setup' the game - this code should theoretically, work as designed, however loading a game with it on (and then starting the firetuner) reveals that the Player 1 and the Observer are the same person. This is bad.

Something's going on where the observer slot is not always 'reserved' in the DLL - I think this affects custom map scripts quite a bit.

**Comment by ilteroi** [comment]
well, thanks for the detailed bug report.

cannot reproduce the issue though. only time NULL is returned happens right after a city is conquered, because the ID of the city changes then. but next turn it's back to normal.

so let me ask the obvious question: are you sure the city ID is correct? and the method is called on the right owner and not somebody else?

cause if there really was a problem with this method, the game would be breaking left and right, it's that important.

**Comment by LoneGazebo** [comment]
Here's the bum LUA, ilteroi:

```
for cityIndex = 0, pPlayer:GetNumCities() - 1, 1 do
					local pCity = pPlayer:GetCityByID(cityIndex);

					if pCity ~= nil then
						followers = followers + pCity:GetNumFollowers(eReligion);
					else
						--print("Player "..pPlayer:GetName().." has a nil city");
					end
			end
```

So it seems like the problem is that the initial value of zero (cityindex) is breaking the function.

Question: could we have two separate city ID models? One for DLL functionality (as it works now) and one for loops like this? i.e. the function above should actually return the 'first' city the player owns.

**Comment by LoneGazebo** [comment]
Maybe we could have the LUA check for nil and, if so, return the first city in the loop, iterating around based on the # of the cityIndex?

**Comment by ilteroi** [comment]
ok that settles it - the city ID is not the city index.

if you want to iterate all cities, the suggested workaround is actually the correct solution.

**Comment by LoneGazebo** [comment]
Yes, but the CP needs to actually be compatible with things, though. :/

How about my second option? Check for nil, if so, then do a loop in the DLL? Seems fair.

**Comment by LoneGazebo** [comment]
Also, we really have to solve the observer issues, as they're (I believe) to blame for a few bigger problems, namely desyncs of data and odd AI behavior. 

G

**Comment by LoneGazebo** [comment]
Load up:  http://forums.civfanatics.com/showthread.php?t=486324

and start a CP game with it installed. Start autoplay and you'll see the issue.

**Comment by ilteroi** [comment]
woah. overload!

anyway i think it's mostly a naming problem leading to confusion here. ideally we would have GetCityByID() and additionally GetCityByIndex(). 

now you're telling me that GetCityByID() used to be GetCityByIndex()? i honestly can't remember. but the city IDs used to be really ugly hex numbers. now they are unique small integers. at no point were they consecutive integers starting at zero. also, GetFirstCity() and GetNextCity(), ugly as they are, would not have been needed with a working GetCityByIndex().

so i'm not convinced we actually need to do anything. it's the first report of this problem. everything else is working fine.

**Comment by LoneGazebo** [comment]
Well, the functionality appears in other base-game code (i.e. the 'who's winning' popup), which seems to indicate that something else is amiss here.

**Comment by ilteroi** [comment]
so an easy way out would be to make lGetCityByID() behave like GetCityByIndex() on DLL. confusing as hell though :)

**Comment by LoneGazebo** [comment]
Yeah, but as long as the back-end works, we can sequester it all away in the luaplayer function and never look there again. :dancer:

**Comment by ilteroi** [comment]
consider it done. looking at the Really Advanced Setup now

**Comment by GrayPockets** [comment]
I'm glad I reported it; didn't realize it affected more mods.

**Comment by ilteroi** [comment]
hold on a second ... you almost had me convinced!

but in the debugger you clearly see that the Lua argument is e.g. 1423 (the actual city ID) and not 2 (the city index). so if i change the interpretation, it will simply break in a different way. and probably much worse.

so, the most plausible explanation for me is that there are bugs in the base lua too. i'm shocked.

FYI: unit iteration works the same way. any known problems there?

**Comment by LoneGazebo** [comment]
Haha. Well, @ilteroi, why would't it work if you just treated 'cityindex' above as the number of loops needed to make the function? Treat it like grabbing an element out of a list, instead of a cityindex->ID, make it cityIndex-> iterator.

Sorry for the deluge, had some free time and decided to hit some bugs! Unfortunately some of them come up against things you've worked on, and I'm reluctant to change things I didn't implement (as the repercussions could be dire!).

**Comment by LoneGazebo** [comment]
Re: Really Advanced Setup, stuff like this: http://forums.civfanatics.com/showpost.php?p=14155725&postcount=37 seems linked to it as well. I'm worried there's a deeper issue with how major/minor/observer/player slots are handled, but I haven't studied it much.

**Comment by LoneGazebo** [comment]
Alright, fixed the cityID issue. This is the new lua:

```
//CyCity* getCity(int iID);
int CvLuaPlayer::lGetCityByID(lua_State* L)
{
	CvPlayerAI* pkPlayer = GetInstance(L);
	const int id = lua_tointeger(L, 2);
#if defined(MOD_BALANCE_CORE)
	CvCity* pLoopCity;
	int iLoop;
	CvCity* pTargetCity = NULL;
	for(pLoopCity = pkPlayer->firstCity(&iLoop); pLoopCity != NULL; pLoopCity = pkPlayer->nextCity(&iLoop))
	{
		if(iLoop == id)
		{
			pTargetCity = pLoopCity;
			break;
		}
	}
	CvLuaCity::Push(L, pTargetCity);
	return 1;
#else
	CvCity* pkCity = pkPlayer->getCity(id);
	CvLuaCity::Push(L, pkCity);
	return 1;
#endif
```

Now, if you can figure out the observer/minor/major woes, we're good to go (for now!) :dancer:

**Comment by LoneGazebo** [comment]
For interested parties, this fixes the 'dazzling cities' blank screen.

**Comment by Iamblichos** [comment]
Is this still the same function call in lua City:GetCityByID()?

**Comment by LoneGazebo** [comment]
Eh? It's all online now. I edited it slightly (as sometimes the proper value is actually retrieved). May not be perfect, but it at least provides compatibility for now. May need to look at it again soon.

**Comment by Iamblichos** [comment]
No. What I mean is, do we still call the function the same way from lua correct? Nothing changes on that end of it right?

**Comment by ilteroi** [comment]
this is the version i'd prefer:

	CvPlayerAI* pkPlayer = GetInstance(L);
	int id = lua_tointeger(L, 2);

	CvCity* pkCity = pkPlayer->getCity(id);

	//sometimes Lua city IDs are actually sequential indices
	if (!pkCity && id<1000)
	{
		if (id>0)
		{
			id--;
			pkCity = pkPlayer->nextCity(&id);
		}
		else
			pkCity = pkPlayer->firstCity(&id);
	}

	CvLuaCity::Push(L, pkCity);
	return 1;

it works with both ways of referencing cities. no need for changes on lua side.

**Comment by LoneGazebo** [comment]
@Iamblichos , that's correct.

@ilteroi , looks better than mine, yep (I didn't know that <1000 mattered, tbh). Shouldn't be an immediate issue, but I'll add that in to the next version.

Feel free to add to yours and I'll grab in the next merge.
G
