### ISSUE TITLE
Question regarding Resolutions

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1240]
A user raised the problem that any custom resolutions that I've added don't stick when passed, which I've now confirmed. Because you're the only one that has added non-Project resolutions, I thought I'd ask you whether or not there was something special I needed to do to get my resolutions to work. [Here](http://pastebin.com/ydxwufiZ) is an example of one - it is passable, but when a new resolution can be proposed thereafter, it appears in the list of passable Resolutions again and Game.IsResolutionPassed() returns false.

I'm not sure if it was ever possible to pass these custom resolutions, I added and tested them long ago and it may have been that I didn't pay close enough attention then. But just confirmation that I'm not doing anything noticeably wrong would be appreciated.

Passed:

![passed](http://i.imgur.com/c9En266.jpg)

Yet still passable:

![yetpassable](http://i.imgur.com/vwrK5dZ.jpg)

(same for International CC when I tried that).

**Comment by LoneGazebo** [comment]
Resolutions are hard-coded into the DLL, unfortunately. Unless you are using functions built-in to the the DLL, resolution effects will always be 'one-shot' in terms of functionality.

**Comment by LoneGazebo** [comment]
What're you trying to do, exactly?

**Comment by JFDaly** [comment]
I had already implemented three permanent effect Resolutions - one that bans Mercenaries in Mercenaries, one that bans Colonies in CID, and one that makes Organized Crime less likely in CID - but I mistakenly thought that permanent effect Resolutions worked. Resolutions are one of the more painful things to test (as IGE and Firetuner can't force sessions), so when I initially tested that they could be passed, I left it at that and didn't realise they didn't permanently pass.

Unless there's a function that could hook into whatever in the DLL determines whether a Resolution has been passed or not, I'll simply have to remove them. But thanks for the info.

**Comment by LoneGazebo** [comment]
What if I create luaevents for resolutions being enacted/repealed that you could hook into to turn on/off a bool you store on your end, one that would change the things you want?

**Comment by LoneGazebo** [comment]
Would that help?

**Comment by JFDaly** [comment]
Oh, actually, I think that already exists.
Yup: GameEvents.ResolutionResult.Add(function(iResolution, iChoice, bEnact, bPassed)
And there's this one to go along with it: GameEvents.PlayerCanPropose.Add(function(iPlayer, iResolution, iChoice, bEnact) return true end)

I can probably use that to then assign to players a dummy policy to act as that boolean, and then remove it if the resolution is repealed. Could you check is that game event works for repealed resolutions though?

**Comment by LoneGazebo** [comment]
Yep, the bEnact is the enact/repeal boolean.

**Comment by JFDaly** [comment]
Excellent, thank you. Thanks for your help on the matter.

**Comment by LoneGazebo** [comment]
Yep!
