### ISSUE TITLE
Build Error on clone

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1242]
Hi, I cloned this repo and made no changes (I'm trying to setup a dev build environment.

After a clean and build on Visual Studio C++ 2010 Express, I get the following error:

`
1>Lua\CvLuaPlayer.cpp(1886): error C2665: 'CvLuaMethodWrapper<Derived,InstanceType>::BasicLuaMethod' : none of the 4 overloads could convert all the argument types
1>          with
1>          [
1>              Derived=CvLuaPlayer,
1>              InstanceType=CvPlayerAI
1>          ]
1>          C:\Users\Michael\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLLUtil\include\CvLuaMethodWrapper.h(87): could be 'int CvLuaMethodWrapper<Derived,InstanceType>::BasicLuaMethod<bool,int,int>(lua_State *,ret (__thiscall CvPlayerAI::* )(arg1,arg2) const)'
1>          with
1>          [
1>              Derived=CvLuaPlayer,
1>              InstanceType=CvPlayerAI,
1>              ret=bool,
1>              arg1=int,
1>              arg2=int
1>          ]
1>          C:\Users\Michael\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLLUtil\include\CvLuaMethodWrapper.h(139): or       'int CvLuaMethodWrapper<Derived,InstanceType>::BasicLuaMethod<bool,int,int>(lua_State *,ret (__thiscall CvPlayerAI::* )(arg1,arg2))'
1>          with
1>          [
1>              Derived=CvLuaPlayer,
1>              InstanceType=CvPlayerAI,
1>              ret=bool,
1>              arg1=int,
1>              arg2=int
1>          ]
1>          C:\Users\Michael\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLLUtil\include\CvLuaMethodWrapper.h(39): or       'int CvLuaMethodWrapper<Derived,InstanceType>::BasicLuaMethod(lua_State *,void (__thiscall CvPlayerAI::* )(void) const)'
1>          with
1>          [
1>              Derived=CvLuaPlayer,
1>              InstanceType=CvPlayerAI
1>          ]
1>          C:\Users\Michael\Documents\GitHub\Community-Patch-DLL\CvGameCoreDLLUtil\include\CvLuaMethodWrapper.h(50): or       'int CvLuaMethodWrapper<Derived,InstanceType>::BasicLuaMethod(lua_State *,void (__thiscall CvPlayerAI::* )(void))'
1>          with
1>          [
1>              Derived=CvLuaPlayer,
1>              InstanceType=CvPlayerAI
1>          ]
1>          while trying to match the argument list '(lua_State *, overloaded-function)'`

According to [this post](http://forums.civfanatics.com/showpost.php?p=14154700&postcount=30) by Gazebo there should not be any issues with the build environment.

Please refer to line 1886 of CvLuaPlayer.cpp.

**Comment by LoneGazebo** [comment]
Did you grab the Solution (.sln) file as well?

G

**Comment by Iamblichos** [comment]
You should be able to do the build as I was able to do one this morning. Only thing I had to do was add the new CvAStarNode.cpp as part of the build from ilteroi's branch.

**Comment by mwhiter** [comment]
Okay  when I get home from work I think I'm gonna remove my local directory, and reclone the  current repository. I'll detail my steps if i still have an issue after I do that.

**Comment by LoneGazebo** [comment]
The solution file is key, as it'll load non-standard files (i.e. custommods.h, etc.) into the project, and set up the proper warning/error behavior.

**Comment by mwhiter** [comment]
Fixed the LuaPlayer.cpp issue. I had to download the Visual Studio 2008 Express Edition (but running on VS 2010). This is why you could not reproduce.

The next step is to add the new CvAStarNode.cpp. The source file is pointing to Downloads\Community-Patch-DLL-fefe. I'll import the new Node.cpp and redirect the file lookup?

**Comment by LoneGazebo** [comment]
Yeah, I borked the current github repo for that, but I've fixed it on my end (will upload later, hopefully). Having some quirks.
