### ISSUE TITLE
Production list disappers (EUI)

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1243]
Playing the latest Feb-9 version with EUI.
After capturing a city (in my case Palenque, before Palenque the same happened with Chichen Itza), I'm not given an option Raze/Occupy/Puppet, the city gets occupied automatically and all my cities lose production list in city view (see screenshot). The only way to get the production list back is to restart the game.
![2016-02-09_00003](https://cloud.githubusercontent.com/assets/16341598/12919313/339bca86-cf4c-11e5-9cd9-a5f3a6187cc1.jpg)
Here the savegame 
[QuickSaveGermany.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/123189/QuickSaveGermany.zip)
Mods used:
- Infoaddict
- Extra victory conditions
- Improved air recon

**Comment by Iamblichos** [comment]
Was there a civilian unit in the city when you captured?

**Comment by LoneGazebo** [comment]
Fixed, I know what's up (forgot to merge my puppetcitypopup lua! D'oh!). Pushing update shortly.

**Comment by saamohod** [comment]
Nice. Can't wait for the update.
