### ISSUE TITLE
Trait_BuildsUnitClasses

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1245]
Doesn't seem to work on a loaded game until you research the next tech. Cache has been cleared.

**Comment by LoneGazebo** [comment]
Care to elaborate?

**Comment by Iamblichos** [comment]
sure, units can build their improvement as it goes. But say you goofed, and you want to reload a turn before(or any other turn), they know longer can build their improvement until I hit the next tech, which usually fires these things being (re)enabled.

**Comment by LoneGazebo** [comment]
Hmm...

**Comment by LoneGazebo** [comment]
What are you building with it, exactly?

**Comment by Iamblichos** [comment]
a Yurt Camp, custom Improvement.

**Comment by Iamblichos** [comment]
So if I start a game here and build it:

![2016-02-09_00001](https://cloud.githubusercontent.com/assets/14372214/12931848/634f2a40-cf45-11e5-9fad-7ba98238b936.jpg)

And then reload the same turn, it's gone, but then will be available again when I hit the next tech.

![2016-02-09_00002](https://cloud.githubusercontent.com/assets/14372214/12931870/79e99498-cf45-11e5-80ea-e743f3d6bad0.jpg)

**Comment by Iamblichos** [comment]
Something tells me that it isn't caching on a load.

**Comment by joosegoose** [comment]
This reminds me of another (similar?) issue I keep forgetting to report. Say you have an auto-faith purchase set up (for missionaries or something else): it gets cleared upon reloading.

**Comment by LoneGazebo** [comment]
Hmm...Ilteroi, do you think this is an issue with player trait caching? From what I can tell, those traits are initialized, but aren't specifically saved/loaded on save game read. Might be the culprit.

**Comment by LoneGazebo** [comment]
Might be simple enough to have a 'refreshplayertraits' function that loads with the kstream, maybe?

**Comment by LoneGazebo** [comment]
Alright, fixed. Ilteroi, no need to worry about this (adding a cache refresh in the kstream solved it).
