### ISSUE TITLE
Interface messed up

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1246]
Impossible to play the very latest beta. (EUI).
![2016-02-09_00005](https://cloud.githubusercontent.com/assets/16341598/12930931/ce7dab14-cf83-11e5-9908-21093f27d22e.jpg)

**Comment by LoneGazebo** [comment]
Did you install the latest EUI (1.28c)? That's required (I don't distribute EUI anymore, per bc1's request).

**Comment by JFDaly** [comment]
Have you tried updating to the latest [hotfix?](http://forums.civfanatics.com/showthread.php?t=562777)

**Comment by saamohod** [comment]
To Gazebo.
Yes, updated manually to the latest 1.28c. Then ran the auto-installer of the latest beta. Interface corrupt the way it is in the screenshot.

**Comment by LoneGazebo** [comment]
Try downloading the auto-installer again.

**Comment by saamohod** [comment]
Did just now. Installed. Doesn't help. ((

**Comment by Kolaris8472** [comment]
The installer is leaving the LUA folder inside the (1) Community Patch folder

**Comment by LoneGazebo** [comment]
Not any more - installer threw an error I didn't see. Should be working 100% now.
