### ISSUE TITLE
Teams, Observers, and Whatnot

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1247]
Re: Really Advanced Setup, stuff like this: http://forums.civfanatics.com/showpost.php?p=14155725&postcount=37 seems linked to it as well. I'm worried there's a deeper issue with how major/minor/observer/player slots are handled, but I haven't studied it much.

Moving here from #1238 

G

**Comment by TechpriestEnginseer** [comment]
Isn't the stuff like this because the city-state hasn't settled a city yet, therefore creating a meeting screen?

**Comment by LoneGazebo** [comment]
Sometimes, but not always (the code should already know if a team is a minor/major before settling). Really Advanced Setup is clearly a bug with CP, though.

**Comment by ilteroi** [comment]
well, i'm not so sure about RAS.

this is the slot status without: 

Slot 0 is taken and assigned
Slot 1 is computer and assigned
Slot 2 is computer and assigned
Slot 3 is computer and assigned
Slot 4 is computer and assigned
Slot 5 is computer and assigned
Slot 6 is observer and unassigned

and this is the slot status with RAS:

Slot 0 is taken and assigned
Slot 1 is computer and assigned
Slot 2 is computer and assigned
Slot 3 is computer and assigned
Slot 4 is computer and assigned
Slot 5 is computer and assigned
Slot 6 is closed and unassigned

seems they didn't consider observer slots and set all non-used slots to closed. so that's why observer mode doesn't work.

**Comment by LoneGazebo** [comment]
That last part seems real dubious.

**Comment by LoneGazebo** [comment]
Any way to tell the DLL to create one more player DLL-side and make that the observer? Seems like the easiest solution.

**Comment by LoneGazebo** [comment]
i guess the problem is that I've now ran RAS with the base DLL and it doesn't have the same issue re: observer.

**Comment by ilteroi** [comment]
yeah, i've just implemented opening a new slot. seems to work so far.

don't understand how it can work in the base dll though.

**Comment by LoneGazebo** [comment]
Me either.

**Comment by LoneGazebo** [comment]
Any idea how this would affect (or if it will) the viability of increasing the max # of civs?

**Comment by ilteroi** [comment]
not at all. number of slots is the same. it's only that now a closed slot can be used for an observer as well.

fix is pushed. not very well tested for side effects, but shouldn't affect normal users either way

**Comment by LoneGazebo** [comment]
Cool. Thanks for looking into this. I'll keep an eye on it. Closing for now.

**Comment by Iamblichos** [comment]
G,
Doesn't whoward have some source code for max civs beyond the 22 limit?

**Comment by LoneGazebo** [comment]
It's just a simple data change in the base DLL. See here in utilldefines.h

```
#if defined(MOD_GLOBAL_MAX_MAJOR_CIVS)
#define MAX_PREGAME_MAJOR_CIVS                              (22)
#define MAX_MAJOR_CIVS										MOD_GLOBAL_MAX_MAJOR_CIVS
#else
#define MAX_MAJOR_CIVS										(22)
#endif
```

**Comment by Iamblichos** [comment]
I can't even find a file called utilldefines.h

**Comment by Iamblichos** [comment]
Never mind found it. This file is not included in the current build it seems.

**Comment by LoneGazebo** [comment]
Eh? Yeah it is, it's a core file. Right click MAX_MAJOR_CIVS anywhere and it'll take you there.

Anyways, I played around with this earlier today and the the 43 civ setting definitely works now. So you fixed it, @ilteroi ! :) 

G

**Comment by Iamblichos** [comment]
I found it. Is MOD_GLOBAL_MAX_MAJOR_CIVS even defined anywhere though?

**Comment by LoneGazebo** [comment]
You have to uncomment it in the custommods.h file to get it.

G

**Comment by Iamblichos** [comment]
Right, I didn't have an updated version yet of custommods.h to see it. Okay, in the instructions it mentions a '43 Civs CP MOD'. I didn't see that in the repository.

**Comment by LoneGazebo** [comment]
It's not read yet.

**Comment by LoneGazebo** [comment]
Ready*

**Comment by Iamblichos** [comment]
Okay, let me know. Would like to do some testing on it.

**Comment by LoneGazebo** [comment]
Will do.
