### ISSUE TITLE
Missing delegates

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1249]
I have 79 delegates, but can only assign 53. 
![2016-02-10_00001](https://cloud.githubusercontent.com/assets/16065630/12946836/97775506-cff7-11e5-96ef-f8feb15067f0.jpg)

**Comment by LoneGazebo** [comment]
Deals?

**Comment by LoneGazebo** [comment]
No follow-up, so I assume you had some deals made.
