### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1254]
maybe related to illteroi's custom civ going missing.
I tried to load up some of LS' custom civs, and I see many lua errors that read like:
`[585779.968] Runtime Error: C:\Users\user\Documents\My Games\Sid Meier's Civilization 5\MODS\[BNW] LS Civilization Set XIII (v 3)\Flanders\Flanders Civ Related.lua:69: attempt to call global 'load' (a nil value)`
I don't remember seeing these sorts of errors in the past. Any ideas?

**Comment by LoneGazebo** [comment]
No, but I'd report to JFD, not me.

**Comment by Hokath** [comment]
His modjesty says that "This is related to the use of SaveUtils."
I'm fairly sure this worked a month or two ago. Any idea what could have changed? This renders several  mods unusable with CBP otherwise (not the end of the world, but seems a bit odd)

**Comment by Iamblichos** [comment]
I use saveutils lots of places and don't these errors. Probably an error in its implementation.

**Comment by LoneGazebo** [comment]
I don't use saveutils.

**Comment by LoneGazebo** [comment]
It's the trigger. Will be gone soon.

**Comment by Hokath** [comment]
hasn't been fixed by 13/2 version

**Comment by LoneGazebo** [comment]
Others report it fixed.

**Comment by Hokath** [comment]
hmmm. I reinstalled the 13/2 several times, but now that I'm using the hotfixed version it works. Maybe a quirk of the installer? Who knows. Anyway, fixed now. Thanks a bunch G
