### ISSUE TITLE
Open Borders bug

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1255]
After I release my vassal Netherlands (by his demand), the diplomacy option to ask him for Open Borders is greyed out saying "They already allow us" while they actually don't. I cannot enter their land without the Declaration of War. It was actually me who gave him Open Borders while he was still my vassal, which still reflects in Current Deals window.

![2016-02-11_00004](https://cloud.githubusercontent.com/assets/16341598/12987732/12d62628-d106-11e5-8f6a-01aea4bb267b.jpg)
![2016-02-11_00003](https://cloud.githubusercontent.com/assets/16341598/12987737/16d49cf0-d106-11e5-8750-5667f556a668.jpg)

 Before you ask, it's not the same turn when the Dutch broke the vassalage.

**Comment by LoneGazebo** [comment]
How long had the Dutch been your vassal? Vassals give OB by default, wonder if the value wasn't restored. Could you still move into his land?

**Comment by saamohod** [comment]
No, I can't move into his land. "Declare War Yes/No" window pops up.
 I guess I need to have Embassy in his capital in order to ask for Open Borders. As seen on the screeshot I don't have Embassy.

**Comment by LoneGazebo** [comment]
When you get an embassy does it allow it?

**Comment by saamohod** [comment]
I can't get an Embassy, they dislike me ))

**Comment by LoneGazebo** [comment]
Well that's the problem - you need an embassy.
