### ISSUE TITLE
Can't upgrade in friendly territory

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1257]
Despite having adopted Imperialism policy tree, I can't upgrade my units (tested with naval units) in friendly territory. Upgrade **is possible** in waters of an allied City-State, but **not possible** in territory of my ally whom I "recalled to life" and who is waging exact the same wars that I do.
![2016-02-12_00006](https://cloud.githubusercontent.com/assets/16341598/13007885/bc2e4544-d19b-11e5-8a20-303e1d086a57.jpg)
![2016-02-12_00005](https://cloud.githubusercontent.com/assets/16341598/13007888/c267c3f4-d19b-11e5-9899-3b77e66bf0de.jpg)

**Comment by LoneGazebo** [comment]
Allied = CSs. Not sure what you're trying to do.
