### ISSUE TITLE
 Manhattan Project

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1258]
Probably not a bug but intended, therefore clarification is appreciated.
 After having built Manhattan Project I received the free Lab as promised but never got the Atomic Bomb. The point is that by the time I built the M. Project, I didn't havt neither Uranium nor the Nuclear Fission Tech. 
 Intended or bug?

**Comment by LoneGazebo** [comment]
Were you the first to do so?

**Comment by saamohod** [comment]
Probably not. I didn't read the description properly, my bad.

**Comment by LoneGazebo** [comment]
No worries.
