### ISSUE TITLE
Ranged Units extra Defensive Embarkation strength?

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1260]
I've noticed this for a while, and IIRC in the vanilla game as well, that ranged units embarked have "extra" defensive strength vis. their melee counterpart (when being attacked by planes or ranged ships). Am I missing something here?

![2016-02-12_00002](https://cloud.githubusercontent.com/assets/14372214/13020932/ba38b4e8-d19d-11e5-94cc-7fd3490a6f41.jpg)

![2016-02-12_00001](https://cloud.githubusercontent.com/assets/14372214/13020935/bd8f3c02-d19d-11e5-9166-6d0cb2e4b34d.jpg)

**Comment by ilteroi** [comment]
that's very strange.

strength is almost equal (but not quite - why?) but damage is wildly different.

probably a bug.

**Comment by Iamblichos** [comment]
Yeah it's weird. I'll bomb an embarked rocket artillery late game with 5 stealth bombers to take it down, but an embarked infantry unit can be done in one shot.

**Comment by ilteroi** [comment]
i can't reproduce it

![image](https://cloud.githubusercontent.com/assets/1358966/13026697/ac2c7562-d231-11e5-8746-d17b654aa354.png)

![image](https://cloud.githubusercontent.com/assets/1358966/13026699/c04fb900-d231-11e5-96dc-90868d200218.png)

notes/questions: 
- in my game, the combat strengths for the musket and the crossbow are 13, not 10. how come?
- the slight 0.04 difference is still there
- what is the %25 bonus against domain about

**Comment by Iamblichos** [comment]
I'm using more vanilla values for COmbat Strength. 13 for xbow and 24 for musketman. Not sure if that matters here.

**Comment by Iamblichos** [comment]
In your example with the -25% against domain for that Xbow, I wonder if we are looking at the same thing here.

**Comment by Iamblichos** [comment]
Okay my intuition is confirmed here I think. This is with the CP and IGE only. No other mods loaded:

![2016-02-13_00001](https://cloud.githubusercontent.com/assets/14372214/13031952/e3607794-d2a5-11e5-81ce-9c3cf8aee9eb.jpg)


![2016-02-13_00002](https://cloud.githubusercontent.com/assets/14372214/13031953/edc37966-d2a5-11e5-9c7a-5064f8af7321.jpg)

**Comment by Iamblichos** [comment]
The only thing I can think of that is the common denominator is that the RangedCombat Strength of the crossbowman is being accounted for in the Approx. DMG calculation...

**Comment by ilteroi** [comment]
found some things:

- the 0.04 offset in defense strength is a bug, should be 4. value is supposed to be 10 plus some off-hand value based on combat strength to help the AI (which is a bit of a hack)

- a bug where embarked defense was not used in damage calculation although the defender is embarked

- the 25% seem to be coming from here. i never knew about this and it seems rather arbitrary
 			// Ranged units take less damage from one another
			iDefenderStrength *= /*125*/ GC.getRANGE_ATTACK_RANGED_DEFENDER_MOD();

- but the 25% should only apply to non-embarked units, so either i'm mistaken as to the origin or it's a display error

**Comment by LoneGazebo** [comment]
that define is really arbitrary - shall we clear it out?

**Comment by ilteroi** [comment]
done - and pushed

**Comment by LoneGazebo** [comment]
if it grabs the value, and the value is zero, it'll just ignore it (so long as you didn't delete the define).

**Comment by ilteroi** [comment]
ah. but the value isn't zero. it's just not included in the calculation anymore

**Comment by LoneGazebo** [comment]
Ah. Well it doesn't appear in the lua, so no worries! :)

**Comment by Iamblichos** [comment]
I'm assuming you changed this in UnitCombats.cpp under Range-Range unit resolve? (Don't remember the formal name)

**Comment by ilteroi** [comment]
@Iamblichos : no, that's in CvUnit.cpp, you can grep for it: RANGE_ATTACK_RANGED_DEFENDER_MOD

**Comment by Iamblichos** [comment]
Yeah, I see your diff....lot of update for that.

**Comment by ilteroi** [comment]
hehe. yeah. i cleaned up a bunch of other stuff as well. i'm not good with putting everything in separate commits.

@LoneGazebo : where in lua did you look? i'd like to understand how this combat preview works ... put a bunch of breakpoints but i can't figure out how the combat modifier list is generated

**Comment by LoneGazebo** [comment]
enemyunitpanel.lua - they're all in there. it's a mess, though, so be careful! :)

In other news, I've rewritten a huge chunk of the diplo AI's approach functionality. Should be a lot more reasonable, while also giving all leaders a bit more personality. I may need a second pair of eyes, though.

**Comment by ilteroi** [comment]
nice.

is this by design, btw?

![image](https://cloud.githubusercontent.com/assets/1358966/13061426/3135f74e-d438-11e5-9a97-d3a5f49acb64.png)

**Comment by LoneGazebo** [comment]
No, it is not. I'll fix.
