### ISSUE TITLE
minor civ earning a great general

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1261]
![image](https://cloud.githubusercontent.com/assets/1358966/13023968/d3b03580-d1ee-11e5-9585-e75450605ffd.png)

i wouldn't mind, but i don't know if it's intended?

**Comment by Iamblichos** [comment]
you playing with the Barbarian GG/GA points on?

**Comment by LoneGazebo** [comment]
How? I wonder if related to Iamblichos's code.

**Comment by Iamblichos** [comment]
If he's not playing with the game option enabled, I'll take a look at code.

**Comment by ilteroi** [comment]
also note the misaligned icon of the garrison. don't think i did that. but i cannot guarantee it :) any takers?

**Comment by ilteroi** [comment]
regarding GG/GA points, i use the default setting, whichever that is

**Comment by LoneGazebo** [comment]
the misaligned garrison thing can happen if you are observing, I think?

**Comment by Iamblichos** [comment]
Actually I've been noticing misaligned garrison in all my games and not observing. Goes away if you move out and in of city. Comes misaligned again on upgrade of unit. Always thought it was the custom unitflagmanager I was using. Perhaps not.

**Comment by LoneGazebo** [comment]
Unit upgrades create a new unit - @ilteroi, perhaps an issue with garrison ID assignment?

**Comment by Iamblichos** [comment]
I can't remember but does the CBP still allow Sweden to gift great people to city states? Is Sweden in the game?

**Comment by Kolaris8472** [comment]
I get that icon problem when I airlift into a city as well.

**Comment by Iamblichos** [comment]
I can't see how that general was created by the city state doing battle. The code defaults to original values if that option isn't check boxed. But I'm somewhat baffled by the code anyways, there's nothing in CvUnit::changeExperience that precludes minors and if (bUpdateGlobal) == true that only precludes Combat with Barbarians--as defending or attacking unit -- from that part of the function firing.

**Comment by ilteroi** [comment]
i've only seen the misaligned icon in observer mode, that's true.

the offending unit has the garrisoned city set correctly however. IsGarrisoned() returns true. so it's probably more a lua issue?

**Comment by Iamblichos** [comment]
I ran a test game last night with the gameoption off to see if city states would produce a great general. Couldn't reproduce. So, I wonder if this general was gifted.

**Comment by Der-Zorn-Gottes** [comment]
Just a completely random guess: What happens if barbarians "catch" a GG from a major civ?

**Comment by LoneGazebo** [comment]
<crunch><crunch>
