### ISSUE TITLE
questionable building choices

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1262]
![image](https://cloud.githubusercontent.com/assets/1358966/13026896/d775390e-d239-11e5-9f14-4d562161c06a.png)

this is turn 242, and the city is missing most basic buildings. also no workboat

**Comment by LoneGazebo** [comment]
What version?

**Comment by ilteroi** [comment]
2/10

**Comment by LoneGazebo** [comment]
I did a little tweaking in latest. Let's see what it does.
