### ISSUE TITLE
inefficient use of resources

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1263]
there was a comment in another issue but it got buried:

_AI used 3 Guided Missiles to take down an embarked Machine Gun. Not a good use of resources._

may be true. but i don't think it's necessarily an AI issue. maybe the guided missile is simply too weak, or too expensive. Or both.

@LoneGazebo : care to change it?

**Comment by LoneGazebo** [comment]
I think I've fixed overspam of this unit type - should help.
