### ISSUE TITLE
vote commitment deal

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1266]
so boudica just offered me a sweet deal.

don' t have the screenshot but the logs. unfortunately many details missing.

132, The Celts, The Zulus, Vote Buy Offer
132, The Zulus, The Celts, , , ***** Vote Commitment: ID 3, Choice 0 *****
132, The Celts, The Zulus, , , ***** Resource Trade: ID 0 *****
132, The Celts, The Zulus, , , ***** GPT Trade: 5 *****

anyway, Nay to Treasure Fleet from me for 2 Iron and 5 GPT.

she must like me a lot. or maybe she overvalues this vote commitment?

**Comment by LoneGazebo** [comment]
That's not a terrible deal- how many votes did she get?

**Comment by ilteroi** [comment]
one :)

and the treasure fleet hurts nobody. for an embargo against her, i'd understand

**Comment by LoneGazebo** [comment]
You can see her vote perception value in the voting log - what's it stand at?

G

**Comment by ilteroi** [comment]
142, 1785,The Celts,- - -,Evaluating for Delegates,ENACT: Global Peace Accords,Nay,40
142, 1785,The Celts,- - -,Evaluating for Delegates,ENACT: World Religion: [ICON_RELIGION_BUDDHISM] Buddhism,Nay,50
142, 1785,The Celts,- - -,Evaluating for Delegates,ENACT: Treasure Fleet,Nay,40
142, 1785,The Celts,- - -,Committing Delegates,ENACT: World Religion: [ICON_RELIGION_BUDDHISM] Buddhism,Nay,3

first time i'm looking at this, so hard to tell what's the baseline here

**Comment by ilteroi** [comment]
anyway. some more small fry:

- i was a bit too late with the screenshot, but there's something off with the formatting here. when the notification first appeared, it seemed to be empty (no text)

![image](https://cloud.githubusercontent.com/assets/1358966/13030707/203e0efc-d2b4-11e5-801b-22be7bafed6f.png)

- some lack of expansion again. only in the year 1920 does anyone think to settle this prime spot

![image](https://cloud.githubusercontent.com/assets/1358966/13030730/c84a6e60-d2b4-11e5-8659-307cca478f94.png)

- pushed some more changes for tactical AI. shouldn't try to move around to attack a target next turn when another target is right nearby

**Comment by LoneGazebo** [comment]
I'll fix the text issue. Re: expansion, may need to loosen fertility a bit (Though, to be fair, I don't see the same thing you have in that pic every game).

Re: voting value, not sure. Did she have lots of iron and GPT?

**Comment by ilteroi** [comment]
re: iron and gold, can't tell for sure, the game is over. but i don't think so, the celts were fairly weak

re: settling, i don't think it's the fertility. they settled much worse spots. it's just a matter of not prioritizing building settlers enough. logic is a bit backward here, AI doesn't look at the quality of spots before building a settler, only if there is at least one.

also, that was communitas map, it seems to have a fixed size, maybe there simply were too few players.

**Comment by ricanuck** [comment]
@ilteroi ,
from the picture you are playing Large, yes? The change to MCR-4 has that effect, unfortunately, in exchange for more maneuverability which helps the Ai tremendously and makes the tactical game more fun.
Perhaps MCR-4 could be accompanied by a faster city cultural growth to compensate? I know you are referring to prime settling locations not being occupied, but sometimes it seems to me that with faster cultural growth those locations would not be prime anymore? I don't know.

**Comment by ilteroi** [comment]
don't think the minimum city range was the problem, there were many free spots and no takers.

but, you remind me of another thing, that game was with medieval start (from Really Advanced Setup). the city sizes, and culture borders were therefore a bit behind a normal game. 

so let's not overrate this.
