### ISSUE TITLE
Last build 13/2 some curious in code

### ISSUE THREAD

**Issue by Pusperk** [LoneGazebo/Community-Patch-DLL#1267]
I look in last build changes. In CvBuilderTaskingAI.cpp int CvBuilderTaskingAI::ScorePlot(ImprovementTypes eImprovement, BuildTypes eBuild)

is this code:

                        iNumWorkedPlots = pCity->getPopulation();
			//if population is higher than # of plots, increase value. Otherwise, reduce it.
			if(iNumWorkedPlots > iNumWorkedPlots)
			{
				iScore *= (iNumWorkedPlots - iNumWorkedPlots);
			}
			else
			{
				iScore /= max(2, (iNumWorkedPlots - iNumWorkedPlots));
			}

**Comment by LoneGazebo** [comment]
Oh Yeah that's a typo. Thanks!
