### ISSUE TITLE
small bug in Language_en_US

### ISSUE THREAD

**Issue by Pusperk** [LoneGazebo/Community-Patch-DLL#1268]
CPP BuildingChanges.sql COLISEUM 

WHERE Tag = 'TXT_KEY_CIV5_BUILDINGS_COLISEUM_TEXT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );

**Comment by LoneGazebo** [comment]
What's the bug? That's the original XML define for the text from firaxis.
