### ISSUE TITLE
possibly mistake

### ISSUE THREAD

**Issue by Pusperk** [LoneGazebo/Community-Patch-DLL#1269]
Functions in CvCity :ChangeNumImprovementWorked (:GetNumImprovementWorked) do not  take account of replacement one improvement for another by worker. (maybe pillaged too?).

In CvCity similar function CountNumWorkedImprovement(eImprovement) work right.

**Comment by LoneGazebo** [comment]
Since pillaged tiles are technically still the improvement, that's fine, but I will fix the replacement issue.

G
