### ISSUE TITLE
Cannot select unit

### ISSUE THREAD

**Issue by aht820** [LoneGazebo/Community-Patch-DLL#1270]
I have the 2/13 beta hotfix and am only using the CPP mods. I cleared cache and moduserdata before starting the game. I'm not able to select any units when I start up. 
![2016-02-14_00002](https://cloud.githubusercontent.com/assets/13701528/13036055/145c30f4-d323-11e5-8ead-7acefd249f44.jpg)
![2016-02-14_00001](https://cloud.githubusercontent.com/assets/13701528/13036054/145b9aae-d323-11e5-9be5-2cce65144b99.jpg)

**Comment by LoneGazebo** [comment]
Make sure you have EUI installed and no conflicting mods. Pretty clearly a mod conflict.

**Comment by aht820** [comment]
I used the installer and EUI is installed in the DLC folder

**Comment by LoneGazebo** [comment]
Then you probably have a mod, a custom civ I bet, that overwrites the lua panel. Since it works out of the box for everyone else, it's most definitely a mod conflict.

G

**Comment by aht820** [comment]
I do not have any custom civs installed. I'm only using the 6 CPP mods.

**Comment by Erikvv** [comment]
I have this same issue. 

Now I don't know if this is the root cause but I installed the CBP first and THEN Civ 5 (I thought I had it already)

When I installed them in the correct order it works.

**Comment by LoneGazebo** [comment]
Make sure your copy of civ is up to date, you have EUI in the proper spot, and you've got all DLC.

**Comment by aht820** [comment]
I reinstalled the latest stable version (1/23) and everything is working fine. I then installed the beta again and got the same issue.

**Comment by LoneGazebo** [comment]
Cleared cached? Not sure what to tell you - no other users are reporting this issue.
G
