### ISSUE TITLE
Double-Dipping Siege Tower Interaction

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1271]
![image](https://cloud.githubusercontent.com/assets/13937047/13058960/cd4bcb7a-d3db-11e5-8dea-a8b911f71ca5.png)
![image](https://cloud.githubusercontent.com/assets/13937047/13058955/c0fdfd8e-d3db-11e5-8cec-02d3d7921188.png)

**Comment by TechpriestEnginseer** [comment]
Also, any unit on top of the siege tower doesn't benefit from the Sapper city attack bonus.

**Comment by LoneGazebo** [comment]
It's actually just a lua quirk (the double dipping). I'll look at center plot issue.
