### ISSUE TITLE
Deal Processing issues

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1272]
@ilteroi , I've looked at this and can't figure it out. It seems that some AI deals can pass through the Diplo AI process yet fail to actually finalize:

Example:

```
224, The Celts, Ethiopia, 3rd Party WAR Offer
224, Austria, Germany, Wanna team up?
```

Normally it should look like this:

```
135, The Zulus, India, 3rd Party WAR Offer
135, India, The Zulus, , , ***** Third Party War Trade versus ID 7 *****
135, The Zulus, India, , , ***** GPT Trade: 19 *****, (value 665 - raw)
```

It's odd, happens for random stuff (not always 3rd party war). Any ideas?

**Comment by LoneGazebo** [comment]
I think I solved my own issue...INT_MAX and MAX_INT aren't the same (obviously), and my addled brain started flipping them, so the processing of the deal was breaking on things being 'bad' when they were 'good.'

I think this is the issue, anyways. We shall see.

**Comment by ilteroi** [comment]
hate to break it to you, but they are the same. just that one is defined in decimal and the other in hex :)

**Comment by LoneGazebo** [comment]
I get that, but the deal processor seems to get upset when you mix them in the deal AI.

**Comment by LoneGazebo** [comment]
Well I was wrong about that being the stopping issue anyway, so the SS Theory has sunk. I'm going to add some more logging to dealclasses, see if I can find the culprit.

**Comment by LoneGazebo** [comment]
Okay, so there's definitely something up with deal processing, and I cannot (for the life of me) figure it out. I've now added logging to the finalizedeal for broken deals, though, so we'll be able to see why it is breaking. 

Current prognosis: the function is breaking when it checks for the validity of the trade item being processed. It seems to break on a few types of items: third party war, resources, votes, and open borders. There's no common theme.

So here's a question: If the trade items pass through the validity-checker function in order to be available to trade in the first place, why do we need to pass them through a second time? Seems redundant to me, but I'm grasping at straws.

**Comment by J-d-H** [comment]
Hope I am right with my assumption that successful other deals are causing the issue.

**Comment by J-d-H** [comment]
I think you need to check the Deal validity in CvDiplomacyRequests::BeginTurn().
That will prevent invalid deals to pop up in notifications.

In addition I still would check the deals after a deal was accepted, because that may render other deals invalid too. In those cases you can easily get the notification through the lookup index inside the deal.

**Comment by LoneGazebo** [comment]
Sounds good, I'll give that a go.

**Comment by J-d-H** [comment]
I think I found the problem. Is a bit more complicated than my ideas above.
I am working on a pull request right now.

**Comment by LoneGazebo** [comment]
Awesome!

**Comment by J-d-H** [comment]
Just a short update: At the moment I am trying to keep it save file compatible. I need a bit more time analyzing the deal classes (and as I more and more understand what's going on there, I don't wonder why there was that Human to Human trade bug in there :grin: )

**Comment by LoneGazebo** [comment]
Fantastic. Don't worry about save game compatibility, as changes bundled into the next CP will already break save game compatibility.

**Comment by LoneGazebo** [comment]
@J-d-H , any updates on this? No rush, just curious.

**Comment by LoneGazebo** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/1366

**Comment by J-d-H** [comment]
I have some troubles debugging and testing. At the moment it crashes for me at game start.
Then I wanted to disable all by mine mod code. But that won't work, because the MOD_ defines are broken.

**Comment by LoneGazebo** [comment]
You can't disable MOD_BALANCE_CORE itself. That's a root function of all DLL changes.

That's fine, just let me know when you've got a fix. No rush.

**Comment by J-d-H** [comment]
You can't disable a lot other things too, because many defines depend on each other (or the wrong #if defined() directive is used)

**Comment by LoneGazebo** [comment]
Which one are you trying to disable? None of them interfere with the ACTIVE_AI define.

G

**Comment by J-d-H** [comment]
Today I started testing. I did not encounter any empty deals yet. But I found a bunch of other bugs that may lead to such problems.

**Comment by LoneGazebo** [comment]
Interesting. What have you found, specifically?

**Comment by J-d-H** [comment]
When the AI checked if it can send a request to a human player it used the HasActiveDealWithHuman function. But this function only returns true, if a human is currently in the diplo scene with that AI. Thus the AI may have send multiple requests to different humans leading to all kinds of possible problems (the same reason you may only send one request a time as a human to any other human).

In addition to that there may be a rare possibility that the order of deals is not matching the order of requests leading to a corruption that may also be the reason for the empty deals problem.

The more I fiddle around with it the more I regret that I didn't just rewrote the whole mess (proposedDeals in global GameDeals vs. DiplomacyRequests as part of CvPlayer).
But I'm on a good way to get rid of those problems soon and my changes will still be savegame compatible (I want to maintain savegame compatibility that, if a serious problem occurs the game may be continued without the active diplomacy enabled).
