### ISSUE TITLE
bad build choice

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1273]
the greeks just lost kwadukuza and ashur to the zulus, and they are building chanceries instead of units (same in sparta).

![image](https://cloud.githubusercontent.com/assets/1358966/13061251/2a8722de-d437-11e5-80fb-c6e48bb22c10.png)

also not that assur is being razed. how can that be? it changed hands a couple of times, but original capital is original capital, no?

**Comment by LoneGazebo** [comment]
I'unno - I've never seen a capital get razed before.

**Comment by LoneGazebo** [comment]
Re: build choice, I'll add some more checks.

**Comment by TechpriestEnginseer** [comment]
I've noticed this when I'm playing Venice but my puppets tend to not build at least half the buildings available and go straight immediately for processes.

An example would be doing the Art process when the puppet has 2 unhappiness from illiteracy even though the library isn't built yet. I shouldn't have to invest in a library to focus on my happiness issues, the "governor" should recognize this right away.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer , if you are in debt, the AI will look to processes.
