### ISSUE TITLE
trade route options bug

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1274]
In the latest version I see some strange behaviour with trade routes. In this picture the capital does not have the option to send a trade route to any of the pictured cities (though it can send it to a city slightly to the north).
![2016-02-15_00001](https://cloud.githubusercontent.com/assets/11889219/13061996/5c071a70-d433-11e5-974e-f16c8e5f9d57.jpg)
Just started with E&D again, but I somehow doubt it's that.

**Comment by LoneGazebo** [comment]
Getting any lua errors?

**Comment by LoneGazebo** [comment]
Also going to see if this might be a pathfiner issue - @ilteroi, any ideas?

**Comment by Hokath** [comment]
Last couple of hundred lines of Lua log are clean 

Sent from Yahoo Mail on Android 
 
  On Mon, 15 Feb, 2016 at 22:31, LoneGazebo<notifications@github.com> wrote:   
Also going to see if this might be a pathfiner issue - @ilteroi, any ideas?

**Comment by ilteroi** [comment]
need savegame

**Comment by Hokath** [comment]
https://mega.nz/#!sNkyTCII!HgVkC0JkAfIdZfpQYyvLYpiMehDByPFx1rakKPrBniw
Savegame and mods running.
(With the exception of E&D this has been the mods list forever)

**Comment by LoneGazebo** [comment]
http://forums.civfanatics.com/showpost.php?p=14168815&postcount=4522

**Comment by LoneGazebo** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/1309

**Comment by ilteroi** [comment]
savegame crashes on load with 13/2 dll. grr.

also, can't load the one from #1309 because of missing mods. grr.

**Comment by LoneGazebo** [comment]
Dang! Well, if I (or someone else) encounters it on the latest, I'll let you know and get you the save.

**Comment by LoneGazebo** [comment]
What DLC do you lack? the map packs?
