### ISSUE TITLE
crash in FSerialization

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1276]
i'm seeing this crash:

![image](https://cloud.githubusercontent.com/assets/1358966/13069270/5ff6f524-d483-11e5-87ab-e5bd151852b4.png)

unitsToCheck is empty. did you add that recently? i can't remember seeing it before

**Comment by LoneGazebo** [comment]
No, I didn't.

**Comment by ilteroi** [comment]
well then. first time i saw this issue. can't be so bad then.
