### ISSUE TITLE
Trait_BuildsUnitClasses

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1277]
Not seeing AI make use of this. Assigned to Japan, Melee Ship units, and Mongols, (all military land units).
![2016-02-16_00001](https://cloud.githubusercontent.com/assets/14372214/13083902/97e9f7a6-d49c-11e5-9a67-75a5e3276689.jpg)
![2016-02-16_00002](https://cloud.githubusercontent.com/assets/14372214/13083906/9df8762c-d49c-11e5-9340-838acedaa51d.jpg)

Have you had any success seeing it?

**Comment by LoneGazebo** [comment]
With reference to what, specifically? The AI is using it on the boats, yes. Can't specifically say re: land units (haven't used it that way), but the functionality is there.

**Comment by Iamblichos** [comment]
There's some open plots for fishing boats to be made, and Japan isn't making them. Mongols should've built some yurt camps.

**Comment by LoneGazebo** [comment]
Works on my end, but the function is only called in reviewunassignedunits for homeland AI. So if the AI doesn't have free units, it won't call it. I'll add a call to sentryunits to see if that picks it up.

**Comment by Iamblichos** [comment]
good deal! Thank you.
