### ISSUE TITLE
AI Operations succeeding, then pulling back

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1278]
@ilteroi,

I've noticed recently that AI city attack operations have a 'successful finish,' but tend to immediately pull back to friendly land after doing so. This usually happens if the target city is defended by a unit or two, or if the sneak attack is called early because the AI ran into a military unit.

Happens a lot on amphibious invasions (boats and emabarked alike fall back).

Any ideas? I'm thinking that it is an issue with the plotwithdraw moves not being sensitive to the fact that a city is a temporary zone target, but I could be wrong.

**Comment by ilteroi** [comment]
withdraw should only be called if the posture for the zone is withdraw. which it shouldn't be because the army is there.

needs to be checked in detail

**Comment by LoneGazebo** [comment]
Yeah - if I see it again, I'll try to get a save, but it's not consistent.

Ideally the 'withdraw' state should be impossible if a city is a temporary zone city.
