### ISSUE TITLE
kStream shenanigans

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1279]
@ilteroi ,

I've looked at these some, and they're real head-scratchers. 

1.) If barbs capture a city, and then the game is saved/loaded, information relating to the city disappears (including the citybanner). Seems related to ownership, which is odd, as the CvCity.cpp kstream/m_sync archives both run for all players. Unless I'm missing something simple.

2.) Multiplayer users report desyncs every turn during war between or with an AI. This leads me to believe it is an issue with the tactical AI (perhaps an issue with tactical analysis caching or unit movement?) Vague, yes, but that's all the information I have to go on. Seems to be the last major source of MP desyncs, though, so that's nice.

**Comment by LoneGazebo** [comment]
[net_message_debug.log.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/135011/net_message_debug.log.zip)

Here's an example of the MP issue (probably tied to the former somehow). Tons of 'out of sync' variables.

1.) Barbarians aren't being processed properly at all, and the 'm_iLastMoveTurn' value for units seems to constantly be out of sync. Same for 'm_iLastMoveTurn' and 'm_iEverSelectedCount.'

2.) Also "Game Random Number Generators are out of sync : local.seed=" is troubling.

Client side changes simply aren't being processed properly by the host player. Why - or how - this is happening is beyond me, but it's pretty clear that something is preventing these values from being sent across the game. My current theory is that the dLL call/sent/receive functions that underpin the DLL aren't directing traffic properly due to it being a custom DLL, but that's a dubious claim (as whoward's DLL, and the NQ DLL, don't have this problem).

**Comment by ilteroi** [comment]
hmm. i have to admit i'm stumped. haven't looked at that part of the code in a while ...

- what are m_iLastMoveTurn and m_iEverSelectedCount actually good for? can we do without?
- there's an option for RNG logging in the game ini file. was quite useful last time when i tried to make the game reproducable.

**Comment by LoneGazebo** [comment]
I think I can shed some light. The CvDllNetworkSynchronization.cpp file has the following functions:

```
//------------------------------------------------------------------------------
void CvDllNetworkSyncronization::SyncCities()
{
	FSerialization::SyncCities();
}
//------------------------------------------------------------------------------
void CvDllNetworkSyncronization::SyncPlayers()
{
	FSerialization::SyncPlayer();
}
//------------------------------------------------------------------------------
void CvDllNetworkSyncronization::SyncPlots()
{
	FSerialization::SyncPlots();
}
//------------------------------------------------------------------------------
void CvDllNetworkSyncronization::SyncUnits()
{
	FSerialization::SyncUnits();
}
```

These tie into the m_syncarchives of each type. We're storing lots more info in these than the base game, but the core functionality should transmit the data from these to all players as the sync request is called. 

Now, looking in these functions, there are calls for *if(archive.hasDeltas())*, which (I assume) looks for changes between clients, and then sends out the data appropriately. I might be wrong, but would there be anything intrinsically wrong with removing that check, and simply sending all data every time? Seems like a safer option.

**Comment by LoneGazebo** [comment]
Ultimately, everything related to desyncs goes through the FAutoVariable.h and FAutoVector.h files. So somewhere in these files, or in references to these files, proper data isn't being sent across the network.

**Comment by LoneGazebo** [comment]
re: "what are m_iLastMoveTurn and m_iEverSelectedCount?"
They're used in the Game.cpp to handle selection queries IIRC.

**Comment by LoneGazebo** [comment]
Another question (sorry for deluge): any idea what the true, false etc. in the m_syncarchive refer to?

i.e.

```
	, m_iJONSCultureCityModifier("CvPlayer::m_iJONSCultureCityModifier", m_syncArchive)
	, m_iJONSCulture("CvPlayer::m_iJONSCulture", m_syncArchive, *true*)
```

**Comment by LoneGazebo** [comment]
One final clue, then I'll stop:

Any idea what this (in PlayerAI) does? 

```
CvUnit::dispatchingNetMessage(true);
// The homeland AI goes first.
GetHomelandAI()->FindAutomatedUnits();
GetHomelandAI()->Update();
CvUnit::dispatchingNetMessage(false);
```

**Comment by LoneGazebo** [comment]
" maybe dump the result from saveDelta() and see what's being sent."

eh?

I'll try and remove the 'has deltas' element, see if that helps. If turn times take longer and/or lag goes up, that's a small price to pay for no resyncs.

**Comment by LoneGazebo** [comment]
Gosh, I wish we knew someone at firaxis that could give us the netcode!

**Comment by LoneGazebo** [comment]
http://forums.civfanatics.com/showpost.php?p=14167089&postcount=493 Well this is promising (the desync part, not the diplo crash part). I swear this game is actually the programming equivalent of the hydra.

**Comment by ilteroi** [comment]
that sounds good indeed!

what i meant with dump is the content of the FMemoryStream which holds the data to be sent out. but i guess that's irrelevant now.

**Comment by LoneGazebo** [comment]
Well, now other users are reporting less than stellar results. We shall see. But the future is bright(er).

i still don't know how to fix the barbarian issue (it's easy to reproduce - capture a city with a barb, save, and reload). No city banner or graphics.

G
