### ISSUE TITLE
A return to suicidal embarkations?

### ISSUE THREAD

**Issue by ricanuck** [LoneGazebo/Community-Patch-DLL#1280]
Hey both,
as of 2.13beta1 (hotfix), I am seeing a lot of AI embarkations in the face of my forces (usually navy), forces that are within sight of the AI (close to borders), only to be obliterated. I have not seen this behavior since forever after you patched the AI in early versions of CBP, that's why I noticed.
The change is very noticeable. Granted, it is only one game, but it happened all along the game so far (many wars).
Just wanted to let you know in case something changed and should be reviewed.

**Comment by ricanuck** [comment]
There is another posting claiming similar problems at the tactical level in thread "AI logic" of the forums. I have seen those silly moves too, a little more frequent than they used to be. I am under a relatively strong impression that the AI is weaker in this beta... and cannot find an explanation on my side (confirmation bias, etc.).

**Comment by LoneGazebo** [comment]
There's absolutely nothing in the AI's behavior that makes it weaker in the current beta relative to the last one in terms of changes we've made intentionally. Bugs are always possible, but I think this might be an issue of observation bias.

G

**Comment by Iamblichos** [comment]
Wait till they see the next beta/version with ilteroi gutting out the queue. The AI's ability to mount a city attack is much much better, along with hit and run tactics save that one little issue with them strangely falling back on success.

**Comment by ricanuck** [comment]
Well, I am all for it, I am not complaining about a strong AI, I am just sharing some observations that point the opposite way.

I try and identify possible observation bias, but I cannot. I really saw those moves, repeatedly. Granted, the map is a little funny (I am in a subcontinent separated from the rest of the landmass by two isthmuses, ala South America, but the AI was dealing with those fine in CBP before now. Both Persia and Denmark, my immediate neighbors, sent waves of units to death in front of my navy in two wars each, trying to bypass the fortified isthmuses, WITHOUT a navy to protect them.

Perhaps stronger checks for embarkation without naval support can be put in place?

**Comment by ilteroi** [comment]
savegame or it didn't happen.

and please no other mods besides cpp full.

i'm prepared to give it a look - but i need a savegame.

**Comment by LoneGazebo** [comment]
@ilteroi , I don't see suicidal behavior in latest, so don't worry about this.
