### ISSUE TITLE
Question about SpecialistFlavors

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1281]
I wanted to ask your DLL insights into whether the SpecialistFlavors table actually influences the AI's decision to use Specialists, or whether they base this entirely off of the Specialist yields themselves?

**Comment by LoneGazebo** [comment]
It doesn't, but it could. Right now it's hard-coded to look at specialists based on the type of GP they produce. But I could convert that to the specialist table. Makes more sense, anyways.

**Comment by JFDaly** [comment]
It would be useful if they could. I bring this up because I noticed that none of the AI use my Doctor specialists, which are a part of the Health component of Cities in Development.

I use FLAVOR_GROWTH in order to tempt the AI toward anything that yields Health, as Health and Food are interwoven, but this is the one area for which they simply don't care (probably beliefs, too, I suppose, but Specialists are more important as everyone has access to them).

**Comment by LoneGazebo** [comment]
Do you have any special flavors?

**Comment by LoneGazebo** [comment]
Also, what about crime/loyalty?

**Comment by JFDaly** [comment]
Not unique flavors for these systems, no, as I'd wager they'd be ignored. Instead, if use FLAVOR_HAPPINESS and FLAVOR_CULTURE for Loyalty and basically all the main flavours for Crime reducing Buildings (Gold, Religion, Science, Culture, Growth, Happiness, Production). 

It's not the tidiest, but the AI seems to cope well with Loyalty and Crime based upon that.

**Comment by LoneGazebo** [comment]
Makes sense. The flavor model (as it stands) will use small numbers for flavors - big numbers will artificially inflate the value of the specialist, so be careful. Keep the numbers between 1 and 5.

Engineer specialists will receive a flavor of 3 for FLAVOR_PRODUCTION, for example.

**Comment by JFDaly** [comment]
Right, I'll follow suit and keep it to 3.

**Comment by LoneGazebo** [comment]
If, for example, the doctor doesn't have other yields, bump it up to compensate.

The formula is this: SpecialistFlavorValue * Personality Flavor (for that type).

This value is added to the yield value of the specialist.
