### ISSUE TITLE
Unable to capture Incan cities on mountains

### ISSUE THREAD

**Issue by Zadkiel343** [LoneGazebo/Community-Patch-DLL#1285]
As the title states, while I can range barrage an Incan city on a mountain, I am unable to melee assault it for the capture. Based on my reading of Gazebo's posts on the civfanatics forum I believe that when you added the ability for them to settle on mountains that you also intended for them to be capturable, indeed Gazebo asked me to post it here as a bug.

Here is a screengrab showing that I am unable to attack a mountain city.

http://i.imgur.com/0daVmXK.png

**Comment by ilteroi** [comment]
reproduced it. which is odd, cause it used to work.

no time to fix right now unfortunately. but pushed a small update with other stuff.

**Comment by LoneGazebo** [comment]
Thanks. No worries on timing, take your time. We're in no rush. :)

**Comment by ilteroi** [comment]
hello again. fixed.

but it seems the plot info popup doesn't work on mountain cities, any idea how that could happen?

**Comment by Zadkiel343** [comment]
Cool, thanks.

**Comment by LoneGazebo** [comment]
Plot info?
