### ISSUE TITLE
43 Civ DLL - Test

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1286]
Hey all,

Also, I have a copy of the 43 Civ DLL here to test. Seems to work pretty well, though some leaderscreens aren't appearing for some reason. Perhaps someone can debug that. Anyways, here's the mod file - drop this in your MODS folder, and then copy then DLL from it and paste it into your CP folder. Enable all, and enjoy.

[43 Civs CP (v 1).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/135553/43.Civs.CP.v.1.zip)

**Comment by JFDaly** [comment]
It is a known issue that Leaderscenes are 22 don't show properly. But Gedemon provided a fix to accompany his DLL, which might be worth incorporating, and can be found [here](https://steamcommunity.com/sharedfiles/filedetails/?id=159305824).

**Comment by LoneGazebo** [comment]
Awesome, will do. Thanks!

**Comment by Kolaris8472** [comment]
What version of the CPP was this compatible with, if we wanted to test it further?

**Comment by LoneGazebo** [comment]
Not compatible at moment. I'll be making a 43 civ DLL for the next official version, though.
