### ISSUE TITLE
Scenario CTD with CBP+RtP active

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#1287]
Hi G

There's a bug with CPP and Rist to Power (RtP). I posted it here (and it was reported by other users too.) but unfortunately JFD says he cant help:
http://forums.civfanatics.com/showpost.php?p=14165338&postcount=1773

Basically I'm seeing a consistent CTD when loading a scenario with RtP version 16 enabled. It doesn't happen if I use start the game with a standard map script or if I use the scenario map without ticking on "Load Scenario". If I however tick on "Load Scenario" the game crashes with Microsoft Visual C++ Runtime Error. It was tested with CPP 2-13b (hotfix) but is still present with 2-17b.

Scenario+screendump included in the post at CivFanatics.

\Skodkim

**Comment by LoneGazebo** [comment]
If it doesn't produce a minidump, there's not much I can do.

**Comment by skodkim** [comment]
I know - what can I do?

**Comment by LoneGazebo** [comment]
I'll try to reproduce - if you can link me to the mods in your mods folder (aside from the CP ones) I'll see if hooking into the DLL before load gives me something.

What's the scenario?

G

**Comment by skodkim** [comment]
I've been testing this numerous times and it usually doesn't create a dump file. I did find this from yesterday however and it might be from this issue (but nothing from my test ½ hour ago...)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/135682/CvMiniDump.zip)

\Skodkim

**Comment by skodkim** [comment]
You can downloade the files here:

**Scenario **(custom map, civilizations+CS starting places assigned, ...):
http://forums.civfanatics.com/attachment.php?attachmentid=404245&d=1455700272

**RtP**:
https://www.dropbox.com/s/aqj6e2rn8edwpr8/JFD's%20Rise%20to%20Power%20(v%2016).civ5mod?dl=0

**Cultural Diversity**:
https://www.dropbox.com/s/0e43t61c103oezp/JFD's%20Cultural%20Diversity%20(Core)%20(v%206).civ5mod?dl=0

\Skodkim

**Comment by JFDaly** [comment]
It might have to do with TSL, actually. Does this same issue occur if you use the latest version of CID (27)? That now uses TSL, so if you get the same runtime error, it might be the cause.

Though unfortunately DarkScythe and Pazyryk the Mage Lord don't seem around much, so I'm not sure this would open an avenue for resolution.

**Comment by skodkim** [comment]
I've never used CIV but I'll test it now

**Comment by skodkim** [comment]
Doesn't happen with the six CPP mods+only CID active

\Skodkim

**Comment by LoneGazebo** [comment]
Reproduced the crash, and it seems to die somewhere in map generation (dealing with the destruction of plots). If this isn't critical, I'm going to assume that some vanilla scenarios simply aren't going to work well with that many mods, unfortunately. Might be best to use ones that do or, alternatively, beg the scenario-maker to remake in worldbuilder while in CP.

**Comment by skodkim** [comment]
Just tried creating a new scenario with only the mods above enabled. Worldbuilder crashes but this time it creates a dump file. Any chance you could have a look (if its relevant).

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/139047/CvMiniDump.zip)

\Skodkim

**Comment by skodkim** [comment]
Furthermore I tried loading my old scenario in the Worldbuilder and saved it again (was in doubt about that was what you meant by remaking it) and the result is the same: When I load the scenario (**only** when _load scenario_ is ticked on, not just by loading the map) CiV crashed with a runtime error.

BTW the crash in world builder happens no matter what map script I use (as long as RtP) is active).

\Skodkim

**Comment by LoneGazebo** [comment]
And if rise to power is not enabled?

**Comment by skodkim** [comment]
No problems if CtP is not enabled

On 20. feb. 2016 16.40.30 CET, LoneGazebo <notifications@github.com> wrote:
>Reopened #1287.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LoneGazebo/Community-Patch-DLL/issues/1287#event-557600912

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by LoneGazebo** [comment]
Then I hate to say it, but there's not much I can do about that. I'll help JFD how I can, but this isn't my jurisdiction.

**Comment by skodkim** [comment]
I'll notify him again. I did start by reporting it to him but he said he couldn't do anything about it as it was a runtime error. I then contacted you as it seems (to me) that it's dll related

On 20. feb. 2016 16.43.58 CET, LoneGazebo <notifications@github.com> wrote:
>Then I hate to say it, but there's not much I can do about that. I'll
>help JFD how I can, but this isn't my jurisdiction. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LoneGazebo/Community-Patch-DLL/issues/1287#issuecomment-186631335

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by LoneGazebo** [comment]
It's DLL related in that the mod is incompatible with the set of mods you are trying to use. If, however, another (comparable) world map scenario works, I'd use that one.

**Comment by skodkim** [comment]
Sorry, sorry, sorry, but I don't really get it. What's incompatible here?

I'm using only the cpp mod pack + CultDiv + RtP. The layer requires CultDiv and at least one if then requires cp.

And I'm not trying to do something special with the scenario but no matter what map script I use the world builder crashes when I try to create a map.

\Skodkim


On 20. feb. 2016 20.20.17 CET, LoneGazebo <notifications@github.com> wrote:
>It's DLL related in that the mod is incompatible with the set of mods
>you are trying to use. If, however, another (comparable) world map
>scenario works, I'd use that one.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LoneGazebo/Community-Patch-DLL/issues/1287#issuecomment-186668452

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by LoneGazebo** [comment]
What I'm saying is, if that it works with the CP's set of core mods, but then crashes with another mod, that's insanely difficult for me to track down, because I didn't write the other mod's code.

**Comment by JFDaly** [comment]
This can be closed now, I'd say, as the issue is now being discussed on my Rise to Power thread.

**Comment by LoneGazebo** [comment]
Cool.

**Comment by JFDaly** [comment]
Finally found the cause to this, and it appears to be a rough limit on the number of Social Policies. Any more than 249 Social Policies will cause this runtime error when trying to run a Scenario. No issues (other than the notification for SPs breaking discussed a while back) in normal games, AFAIK.

I'm not hopeful that anything can be done about this, but I have to defer to your expertise.

**Comment by LoneGazebo** [comment]
That's a lot of dummy policies!

**Comment by LoneGazebo** [comment]
You may want/need to shift some of them over to dummy buildings. I don't see a hard limit defined in the DLL, so it might be a hard limit in the scenario creation logic, maybe?

**Comment by skodkim** [comment]
Just for the record I had a look in the database and it seems E&D adds a lot of dummy policies too.

\Skodkim

**Comment by JFDaly** [comment]
Yes, you'll find a lot of modders (non-DLL, anyway) use dummy Policies. They are superior to dummy Buildings because you don't need to deal with other Civilizations capturing cities. Even if I shifted the Mercenary contracts from being dummy policies, I couldn't shift the Reforms, as so much depends upon them being persistent - and they alone breach the 250 limit.

**Comment by LoneGazebo** [comment]
Unfortunately there's nothing I know of that can fix this. Might be worth asking whoward, he tends to pull solutions out of hsi :dart:  sometimes. :)

**Comment by skodkim** [comment]
Just a notice: I sent a PM to W using CivFanatics (I didn't know where else to do it since I don't "know him that well" :smiley: ). Lets see if he responds.

\Skodkim

**Comment by TechpriestEnginseer** [comment]
I don't believe it's 250, but rather it's 256 that's a hard limit.

**Comment by skodkim** [comment]
Probably true since it works with 253 policies - which is the number we have when using CBP+RtP only.

Question is what we can do about it? If adding policies is the normal way to go for a lot of modders a lot of mods will soon be incompatible with scenarios.

\Skodkim

**Comment by LoneGazebo** [comment]
This is, incidentally, why nearly all CP functionality is in the DLL, not in dummy policies/buildings in the LUA. If the designers didn't intend for there to be more than 256 policies, there's probably not much we can do about it, unfortunately.

On the bright side, C++ isn't too difficult to pick up if you're seasoned with LUA.
