### ISSUE TITLE
city manager issues

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1289]
City manager sometimes can prefer labourers to proper specialists:
http://forums.civfanatics.com/showthread.php?t=563226

I also saw a city that would always work a marsh (3f) over a fish w/ lighthouse (4f, 1p)
Not sure why that was

**Comment by LoneGazebo** [comment]
In 2-17?

**Comment by Hokath** [comment]
They don't specify,
In my case, no.
