### ISSUE TITLE
City not showing tile yields

### ISSUE THREAD

**Issue by dennisdahlc** [LoneGazebo/Community-Patch-DLL#1290]
I have just finished a CBP game, and I noticed a strange UI bug.
I captured the capitol of the Ottomans (Istanbul) in my game which was placed fairly north on the map.
At first nothing was wrong, but at some point the tile yields of the city screen disappeared, but only for tiles above a certain longitude. This persisted all through the game.

It seems to me a policy or tech might have broken the view.

I have attached the save game. I am playing CBP from the 13-02-2016 with no other mods.

**Comment by Iamblichos** [comment]
I think is a EUI graphical bug. I've seen this before, IIRC, the yields are still there sometimes go in and out with zoom. In CityView, does the city list total yields?

**Comment by dennisdahlc** [comment]
Yes, I believe that the city list show the total yields.
I haven't tried zooming in and out in the CityView though.

**Comment by LoneGazebo** [comment]
Sounds like an EUI bug - I'd report to bc1, not to me.

G

**Comment by dennisdahlc** [comment]
How do I report to EUI ?

**Comment by LoneGazebo** [comment]
bc1 has a thread on civfanatics - it is his mod.
