### ISSUE TITLE
Tourism Victory in cooperation game

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#1291]
When playing in teams, you have to get influential over your teammate for culture victory. It leads to stupid gamestyle and is quite unconsistent (if I'm right then you don't have to conquer your teammate's capital to win by domination).

Link to thread: [(http://forums.civfanatics.com/showthread.php?t=563077)]

**Comment by LoneGazebo** [comment]
This isn't what I thought you were reporting, sorry. I'll look into this.

G

**Comment by LoneGazebo** [comment]
Since tourism is calc'd on a player by player basis, there is no method to change this without rewriting the culture system. Sorry, but not going to do that.

**Comment by Finarvi** [comment]
So maybe you could add some high tourism multiplier for teammates?

**Comment by LoneGazebo** [comment]
I could, yep.

**Comment by LoneGazebo** [comment]
Yep, added 200% bonus for teammates.
