### ISSUE TITLE
Some various deal quirks

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1292]
![2016-02-18_00001](https://cloud.githubusercontent.com/assets/14372214/13154166/42281c56-d63d-11e5-9ec8-6cc22440e064.jpg)
![2016-02-18_00002](https://cloud.githubusercontent.com/assets/14372214/13154171/461fa996-d63d-11e5-8222-cad6cabfde1b.jpg)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/136748/Logs.zip)

**Comment by Iamblichos** [comment]
No gift in the first one and the second pic we already have open borders.

**Comment by LoneGazebo** [comment]
Yeah - don't enable that in singleplayer.

**Comment by Iamblichos** [comment]
That might be the reason....I turned it off and recompiled.
