### ISSUE TITLE
It's working

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1293]
![2016-02-18_00005](https://cloud.githubusercontent.com/assets/14372214/13157191/18a06d66-d64c-11e5-91a5-0e46e0b05f90.jpg)

![2016-02-18_00004](https://cloud.githubusercontent.com/assets/14372214/13157195/1cc6679c-d64c-11e5-863b-642d6e04bb81.jpg)

Mongolia building that crap all the way into my territory!

**Comment by LoneGazebo** [comment]
Good to hear!

**Comment by Iamblichos** [comment]
Yes fantastic. Bravo. Military units building if they can and coming off it midway if they need to attack. Perfect.
