### ISSUE TITLE
Bug taking city

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1294]
![2016-02-18_00006](https://cloud.githubusercontent.com/assets/14372214/13158453/9104d1f6-d652-11e5-86bf-653826689edf.jpg)
Took Greece's city and not only did it not give me the option of puppet, annex or raze, but Greece also kept it.

This is with 2-17 CP

**Comment by Iamblichos** [comment]
Completely reloaded game and this time it gave me the option....strange.

**Comment by Iamblichos** [comment]
Okay, I figured this out. The samurai that took the city was in "invisible" (like the submarine). When he is within two tiles of a Japanese GG, he is invisible unless right up on him. So if there is no enemy unit within city "to observe" the unit, I guess it doesn't engage the city capture complete. This is an anomaly totally in my mod and not in the CP or CBP.

So is it possible to modify the code to allow "invisible" non-ranged combat units to complete city capture?

**Comment by Iamblichos** [comment]
I wonder if it is this code right here:

    bool CvUnit::canCoexistWithEnemyUnit(TeamTypes eTeam) const
    {
	    VALIDATE_OBJECT
	    if(NO_TEAM == eTeam)
	    {
		    return false;
	    }

	    if(isInvisible(eTeam, false))
	    {
		    return true;
	    }

	    return false;
    }

**Comment by Iamblichos** [comment]
and then these lines in CvUnit::SetXY

    // Moving into a City (friend or foe)
    if(pNewCity != NULL)
    {
        if(isEnemy(pNewCity->getTeam()) && !canCoexistWithEnemyUnit(pNewCity->getTeam()))
        {
            PlayerTypes eNewOwner = GET_PLAYER(getOwner()).pickConqueredCityOwner(*pNewCity);

            if(NO_PLAYER != eNewOwner)
            {

**Comment by LoneGazebo** [comment]
Really, an invisible unit probably shouldn't be allowed to 'coincide' with an enemy unit anyways. Let's ask ilteroi, I tend to muck up unit plot moves. :)

**Comment by Iamblichos** [comment]
If I'm not mistaken, cancoexistwithenemyunit is a check for invisibility, so we'll have to be careful. 

I'll do some work on it tomorrow and corroborate.

**Comment by LoneGazebo** [comment]
ok

**Comment by Iamblichos** [comment]
Pretty simple change it looks like just needs to change the above in CvUnit:SetXY to:

    // Moving into a City (friend or foe)
    if(pNewCity != NULL)
    {
    #if defined(MOD_BALANCE_CORE)
        if(isEnemy(pNewCity->getTeam()))
    #else
        if(isEnemy(pNewCity->getTeam()) && !canCoexistWithEnemyUnit(pNewCity->getTeam()))
    #endif
        {

I'll test out and see if I run into anything else about it.

**Comment by ilteroi** [comment]
maybe check if it's a melee unit? otherwise the change seems plausible

**Comment by LoneGazebo** [comment]
Let me know when you've got it sorted, @Iamblichos .

**Comment by Iamblichos** [comment]
Sure...I'll try to get all my commits done tomorrow. Got a little lazy coding this afternoon and played.

**Comment by LoneGazebo** [comment]
No worries, take your time. No rush at all.

**Comment by Iamblichos** [comment]
Commit done.
