### ISSUE TITLE
CountNumWorkedRiverPlots 

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1295]
Hopefully an easy request: city:CountNumWorkedRiverPlots() in order to count how many river tiles are being worked by a city. There already exists a CountNumRiverPlots(), so hopefully its a small step to this request. Thanks!

**Comment by LoneGazebo** [comment]
I'll see what I can do, yep!

**Comment by Pusperk** [comment]
Absolutely cool would be CountNumWorkedRiverPlots(eTerrain)

**Comment by LoneGazebo** [comment]
And done. 


CountNumWorkedRiverTiles()

If you leave it blank it returns all terrain types. If you add a terrain type, it'll return only that amount.

Will be in next beta.

**Comment by JFDaly** [comment]
Excellent, thank you!

**Comment by JFDaly** [comment]
Sadly, CountNumWorkedRiverTiles() appears to return all worked tiles if the terrain parameter is left blank, not just those with a river. It correctly counts the number of river tiles worked when a terrain is specified, however (and other requested features work, incidentally).

**Comment by LoneGazebo** [comment]
Okay, I'll take a look. I tested and it worked, but it might have been a fluke if the map.
