### ISSUE TITLE
Would this be possible?

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1296]
This is perhaps a bit of a robust request, so I'll start with the acknowledgement that I completely understand if it's not possible and/or too complicated. But anyway.

For Health, one feature I wanted was for Units with the 'Plagued' promotion to have a chance to transfer that promotion to units that they fight. Sort of like the Kris Swordsman thing, but for a specific promotion and to the enemy combatant. Do you think something like this would be possible without too much overhead? Or at all? I've looked at ways to do it in Lua, but Whoward's BattleStarted/Joined/Ended are a bit complicated, and UnitPreKill doesn't capture the killing unit.

No worries if it's not, but thanks for taking a look if you can.

**Comment by LoneGazebo** [comment]
Are you talking about it spreading via combat? Or proximity?

**Comment by JFDaly** [comment]
Via combat - Unit A with Plague attacks Unit B, Unit B has a chance to contract Plague (if Unit B didn't die).

**Comment by LoneGazebo** [comment]
Hmm...I'll take a look.

**Comment by LoneGazebo** [comment]
Alright, so waljk me through it - two melee units (cities as well?) engage in combat. If A has the plagued promotion, and B does not, there's a chance of A spreading it to B after combat? Only if it dies?

**Comment by JFDaly** [comment]
Exactly that, except it doesn't matter if there is a death or not. Just if Unit A engages in combat with Unit B, and Unit A has the plagued promotion and Unit B doesn't, Unit B has a chance to get the plagued after combat. Doesn't matter what type of unit they are, either.

No cities, just units.

**Comment by LoneGazebo** [comment]
I'll give it a look. And I assume just melee?

**Comment by JFDaly** [comment]
Do you mean melee as in UNITCOMBAT_MELEE (Warriors, Spearmen, Pikemen, Swordsmen, and Longswordsmen), or melee as in those that make contact (i.e. not ranged)? If the latter, then yeah.

**Comment by LoneGazebo** [comment]
Latter, yep.

**Comment by LoneGazebo** [comment]
Alright, so I think I've got this working for you. It's going to use two promotion modifiers;

IsPlague (a bool)
and
PlagueChance (an integer)

The way it works is pretty simple: IsPlague is the what you assign to the promotion you want to transfer. PlagueChance is what you assign to a promotion to make it possible to transfer any plagues on your unit. You can have these on the same promotion, but that's not required.

The higher the PlagueChance, the better chance of it spreading. I've also added a notification for plague spread this way (so users know what's up) and a bit of logging (so you can track how well it is working, if at all). Logging will appear in the tactical AI log (look for JFD or plague to find it).

Going to test, make sure it works. :)

**Comment by Iamblichos** [comment]
That's a pretty cool feature.

**Comment by LoneGazebo** [comment]
You could, theoretically, use this in lots of different ways. It could be an additional way of spreading a combat malus, though the only caveat is that, for ease of use/code, you can't spread more than one plague per combat. With promotionduration, though, you can pretty easily get the plague to start and stop with no lua! :dancer: :dancers: 

G

**Comment by LoneGazebo** [comment]
Just tested, worked well. By turn 100, Shock I had spread to most of the melee troops of city-states on this one island (thanks, Barbarian plague carriers!).

**Comment by JFDaly** [comment]
Awesome! Thank you so much.
