### ISSUE TITLE
Feature request: Workers can plant forest

### ISSUE THREAD

**Issue by El-SiD** [LoneGazebo/Community-Patch-DLL#1298]
Isn't that strange that workers can't plant forest ? This may help cities with open tundra tiles to get production.

**Comment by LoneGazebo** [comment]
Possibly, but that's an additional layer of AI behavior I'm not willing to tackle at this time.

**Comment by El-SiD** [comment]
But when you'll have time, you'll implement this ?

**Comment by LoneGazebo** [comment]
No, not planning to.

**Comment by Iamblichos** [comment]
Hmmm...is it really an additional AI behavior?...in my mod Iroquois workers seem to do it.

**Comment by LoneGazebo** [comment]
The issue is proper logic - they 'can' do it, but optimizing it can be difficult.

**Comment by Iamblichos** [comment]
I don't see the difficulty. I see more than "can"...otherwise it'd be similar to the problem we were seeing with the Trait classes building improvements. I actually see them actively build forests...for Iroquois this is just like building roads.

**Comment by Iamblichos** [comment]
I guess what I'm saying, how is this different than any other improvement per se.

**Comment by LoneGazebo** [comment]
Yields aside, forests are a tactical element.  That needs consideration.

G

**Comment by Iamblichos** [comment]
You mean for military placement?

**Comment by LoneGazebo** [comment]
Yep - and also military use by other civs.

**Comment by Iamblichos** [comment]
Well here I'm thinking of just a dummy improvement, once built, the plot is replaced with the FEATURE_FOREST (give the improvement a flavor for being built, seems to work). Doesn't plot placement for forest only considered after it would exist?

**Comment by LoneGazebo** [comment]
You misunderstand - if the AI starts planting forests without proper planning, it could otherwise hamper their optimal building model or make the empire more vulnerable to invasion.

**Comment by Iamblichos** [comment]
I don't understand....how does a forest make you more vulnerable, it makes you a difficult target. Units gain extra defense on them and opponents are slowed by rough terrain. All depends on how you flavor the improvement, if it is flavored for production, then it might be an optimal build if that is the need, plus you get growth with the herbalist. If you need growth, then it wouldn't be.

**Comment by LoneGazebo** [comment]
Makes you more vulnerable if you're up against a player with woodsman. Also breaks LoS. 
AI also doesn't 'reverse' the logic to know that an herbalist benefits from it. There are the types of things I'm talking about (and I don't intend to deal with).

**Comment by Iamblichos** [comment]
I see. Well I'm only considering as a feature of a civ that has the promotion as a part of their trait, like the Iroquois. Not a universal build, I agree that would not be a good idea. The reverse logic can work if you fool the build into thinking it gets growth as well (via a minor flavor for growth with a major flavor for production).

**Comment by LoneGazebo** [comment]
Perhaps. I just don't see the forest thing as being a CP/CBP concern.

**Comment by Iamblichos** [comment]
It's cool. My inquiry was mostly hypothetical.
