### ISSUE TITLE
Production Ruins

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1299]
Do they not scale with game speed or is there some weird formula or are they just not that great or am I crazy? I got one way back on turn 3, and it didn't do much at all it seemed like.

2/13 version still

**Comment by LoneGazebo** [comment]
They scale.

**Comment by pandasnail** [comment]
Oh. Guess I wasn't very helpful today, sorry about that. After getting killed on Immortal, I'm trying to get better at city management, guess that's why I noticed these things for the first time. Sorry.

Well, I'm here, the new tech tree is GREAT.

**Comment by LoneGazebo** [comment]
Glad you like it!
