### ISSUE TITLE
Authority Imperium question

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1300]
2/13 version, I'm playing basically the slowest game ever.

Has the culture gained from settling a city always gone into expanding that city's borders? My cities are starting with an extra tile, and I def don't remember that being the case before. Also, the very turn after I conquered a Polish city, Tenotich, Tenotix, Teno, err my capital as The Aztecs expanded, likely not a coincidence. Has it always been this way, and just maybe didn't scale properly last time I played Authority? Gonna feel dumb if its always been this way, and I just never noticed. But then, I'm not super observant at the city managing parts.

I'm playing with the same modlist I've been using all along, except I added Ice Free Coasts, which it would be weird if that mattered.

**Comment by pandasnail** [comment]
Forgot to mention that I can post some logs, at least of the city conquest, but I turned on a lot, so there are 47 files in the folder and idk whats useful

**Comment by LoneGazebo** [comment]
Yes.
