### ISSUE TITLE
Redundancy in LeftoverUnits.xml?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1302]
What's the purpose of having those units with Civilization_UnitClassOverrides and Cost being -1?

Wouldn't it help the game load a tiny bit faster if the Civilization_UnitClassOverrides tags for those units be removed since the cost is already -1 to make them untrainable?

Nonetheless, any custom civilizations makes the Civilization_UnitClassOverrides tag obsolete because it doesn't include the custom civilization. I would suggest removing these tags in LeftoverUnits.xml.

**Comment by LoneGazebo** [comment]
Probably - added those in forever ago to keep them out of the tech tree.

**Comment by TechpriestEnginseer** [comment]
Well, since I believe you need the technology to unlock the city-state's "secret" military secret anyway. I believe keeping them in the tech tree would be a nice feature.

**Comment by LoneGazebo** [comment]
Sounds good to me. I'll move the XML off to a graveyard in the event we need it again (probably should've done an SQL trigger, but I'm lazy).

**Comment by TechpriestEnginseer** [comment]
![image](https://cloud.githubusercontent.com/assets/13937047/13194651/94c20b64-d74d-11e5-8f06-b46bb0abfa71.png)
![image](https://cloud.githubusercontent.com/assets/13937047/13194653/bb139134-d74d-11e5-9146-5ffe61f6d55e.png)

What's the difference here if you're adding and removing them? I'm seeing this in most of the naval ships for some reason.

**Comment by LoneGazebo** [comment]
It was for early control. I had considered writing a new AI for naval explore (kinda like scout), but relented.

G

**Comment by TechpriestEnginseer** [comment]
I also believe SQL doesn't accept 'true' for booleans.
![image](https://cloud.githubusercontent.com/assets/13937047/13198401/a52e3968-d7bc-11e5-8522-0a80c081b94b.png)
![image](https://cloud.githubusercontent.com/assets/13937047/13198402/ac6ae050-d7bc-11e5-8a40-33003782ba89.png)

**Comment by LoneGazebo** [comment]
It turns them into 1, IIRC. I think I use them in a few places. But I can check.

G

**Comment by TechpriestEnginseer** [comment]
I don't believe that's how SQL reads it.
![image](https://cloud.githubusercontent.com/assets/13937047/13198722/4a235cfc-d7c5-11e5-9473-b175051c193f.png)

**Comment by Iamblichos** [comment]
You can use SQL 'true' or 1, or 'false' or 0, The DLL will treat them the same. Just tested this.

**Comment by LoneGazebo** [comment]
Yep. SQLite is very loose.
