### ISSUE TITLE
Beta 2/17 DLL Load Crash

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1303]
Hey, I merged my branch with the latest Beta 2/17 and it caused a crash on mod load (reminder: not using CBP, but using CP). That commit was huge so I'm not sure what caused the crash. I'm gonna stop pulling from master until we get a stable release build, but I wanted to let you know there was a potential issue.

**Comment by LoneGazebo** [comment]
Did you run the mini dump to see where it crashed?

**Comment by LoneGazebo** [comment]
The current 2/17 beta is 100% stable on my end, so it might be an issue with the merge overwriting something it shouldn't have.

**Comment by mwhiter** [comment]
No, I haven't. Where can I find that?

**Comment by mwhiter** [comment]
Crash at CvBuildingClasses.cpp line 978

`//TerrainYieldChanges
	{
		kUtility.Initialize2DArray(m_ppaiYieldPerXTerrain, "Terrains", "Yields");

		std::string strKey("Building_YieldPerXTerrainTimes100");
		Database::Results* pResults = kUtility.GetResults(strKey);
		if(pResults == NULL)
		{
			pResults = kUtility.PrepareResults(strKey, "select Terrains.ID as TerrainID, Yields.ID as YieldID, Yield from Building_YieldPerXTerrainTimes100 inner join Terrains on Terrains.Type = TerrainType inner join Yields on Yields.Type = YieldType where BuildingType = ?");
		}

		pResults->Bind(1, szBuildingType);

		while(pResults->Step())             /////// this line is crashing
		{
			const int TerrainID = pResults->GetInt(0);
			const int YieldID = pResults->GetInt(1);
			const int yield = pResults->GetInt(2);

			m_ppaiYieldPerXTerrain[TerrainID][YieldID] = yield;
		}
	}`

**Comment by mwhiter** [comment]
The crash is most likely related to the fact that I did not update the Community Patch files when table names were changed. I'm going to reset the entire Community Patch project to fit my needs and then try again! :D

**Comment by mwhiter** [comment]
Crash fixed, but an LUA. Dunno if there are others. Seems to be linked to being in CBP and not CP, but CP references them:

BombardRange in TechHelpInclude.lua

**Comment by LoneGazebo** [comment]
Oh, that's because I forgot to move some values over to the CP from the CBP. For now just delete the techhelpinclude.lua file from the CP and you are good to go.

**Comment by LoneGazebo** [comment]
Yeah, I should've informed you to check the CP's core files- my mistake!
