### ISSUE TITLE
Railroad and pathfinding issues

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1304]
Railroad seems to be bugged in 2-17 Version.
![2016-02-21_00006](https://cloud.githubusercontent.com/assets/16341598/13200289/1ad60f32-d84a-11e5-8a95-f6b466e185a9.jpg)
![2016-02-21_00005](https://cloud.githubusercontent.com/assets/16341598/13200290/215a26fe-d84a-11e5-9579-44a6ea948746.jpg)
![2016-02-21_00004](https://cloud.githubusercontent.com/assets/16341598/13200291/2395e192-d84a-11e5-887d-58b5881680d0.jpg)

 The first screenshot shows that a regular (2-tile movement) unit can move 5 tiles via regular road.
The second screenshot shows that the same unit can only move 4 tiles via railroad.
The third screenshot also shows bugged pathfinding which takes the unit off the railroad before the second turn.

**Comment by LoneGazebo** [comment]
Rails are a little slower than roads when first started. That's intentional.

**Comment by saamohod** [comment]
I see.
But the pathfinding is still broken as it seems.

**Comment by LoneGazebo** [comment]
@ilteroi , looks like turn-on moves might be a little wonky.

**Comment by LoneGazebo** [comment]
@saamohod , Please link a save-game.

**Comment by saamohod** [comment]
[Bugged railroad.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/139747/Bugged.railroad.zip)

**Comment by ilteroi** [comment]
fixed

**Comment by LoneGazebo** [comment]
Thanks ilteroi!
