### ISSUE TITLE
Religious city sorting

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1305]
The sorting by the number of cities following a certain religion is bugged. Doesn't show ascending/descending number of cities.
![2016-02-21_00003](https://cloud.githubusercontent.com/assets/16341598/13200318/31d593a0-d84b-11e5-8771-78b2286fc254.jpg)
![2016-02-21_00002](https://cloud.githubusercontent.com/assets/16341598/13200319/327b9b10-d84b-11e5-9520-851c41c83cd0.jpg)

**Comment by LoneGazebo** [comment]
CBP doesn't modify that Lua file. Another mod?

**Comment by saamohod** [comment]
No idea.
1. ZNW - Symbolic Ideology Tenets
2. Thal's Flag Promotions
3. Extra Victory Conditions
4. Calypso's Colored Religious Icons
