### ISSUE TITLE
Question about Game.DoMinorBullyUnit

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1306]
Is DoMinorBullyUnit hardcoded in the DLL to give a Worker unit? I searched the database a bit and suspect that it is. If so, would it be possible to push this to a GameDefine, as I'd like to change it? Thanks.

**Comment by Iamblichos** [comment]
I believe so JFD:
```
void CvGame::DoMinorBullyUnit(PlayerTypes eBully, PlayerTypes eMinor)
{
	CvAssertMsg(eBully >= 0, "eBully is expected to be non-negative (invalid Index)");
	CvAssertMsg(eBully < MAX_MAJOR_CIVS, "eBully is expected to be within maximum bounds (invalid Index)");
	CvAssertMsg(eMinor >= MAX_MAJOR_CIVS, "eMinor is not in expected range (invalid Index)");
	CvAssertMsg(eMinor < MAX_CIV_PLAYERS, "eMinor is not in expected range (invalid Index)");

#if defined(MOD_BUGFIX_UNITCLASS_NOT_UNIT)
	UnitTypes eUnitType = GET_PLAYER(eBully).GetSpecificUnitType("UNITCLASS_WORKER");
#else
	UnitTypes eUnitType = (UnitTypes) GC.getInfoTypeForString("UNIT_WORKER"); //antonjs: todo: XML/function
#endif

	gDLL->sendMinorBullyUnit(eBully, eMinor, eUnitType);
}
```

**Comment by LoneGazebo** [comment]
Trying to think of a good way to make this 'modular' aside from the define...

**Comment by JFDaly** [comment]
Would a GameEvent which registers when a City-State has been bullied, returning the unit ID, be a possible alternative? I could then just kill and replace the unit as needed.

**Comment by LoneGazebo** [comment]
I was just trying to think of a more permanent, modular solution, but a define would work. I guess the define would need to match the unitclass ID, which is potentially problematic. Anyways, the global define will be: UNITCLASS_FOR_CS_BULLY

This value should correspond to your unitclass ID #.

If this value is invalid, the DLL passes in a worker as the default.

**Comment by LoneGazebo** [comment]
You'll need to use an update SQL statement for it, as I'll define it as -1 in the CP.

**Comment by JFDaly** [comment]
Sounds good. Thanks.

**Comment by LoneGazebo** [comment]
Isn't it nice that they hardcoded that?
Also, don't forget to update the tooltip for the CS. :)
