### ISSUE TITLE
Minefield affecting land

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1307]
It seems that Minefield (despite description) also affects land unit movement. Movement of my land units near an enemy city costs twice the normal price (tank moves 2 tiles, infantry 1). First I thought the enemy has the Great Wall built. But then when I captured the troubled city I noticed it had Minefield in it and the enemy civ never had the Great Wall built.

**Comment by TechpriestEnginseer** [comment]
Not sure if this is intentional because there is no difference here of XML property between the Great Wall and Minefield.

OR the Minefield picture and/or description is misleading because it's a land/naval minefield.

**Comment by saamohod** [comment]
Shouldn't be intentional because the description only mentions naval units.

**Comment by LoneGazebo** [comment]
It's a typo.
