### ISSUE TITLE
 Can't attack enemy diplomats

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1308]
Not sure if a bug or intended.
 My Battleships can't attack enemy diplomats on land. Didn't test attack against embarked diplomats.
![2016-02-22_00001](https://cloud.githubusercontent.com/assets/16341598/13206011/52f2ba78-d8fe-11e5-9002-6cc1c7c4de22.jpg)

**Comment by LoneGazebo** [comment]
Sometimes stacked civilian units cause that to happen. Not sure why, but it's pretty rare.
