### ISSUE TITLE
Trade Routes: No Options

### ISSUE THREAD

**Issue by Frid2Dynamite** [LoneGazebo/Community-Patch-DLL#1309]
I have been using a caravan in my capital.  There are city states that are at least 9 tiles away from my city, but it didn't say I could send it to any of the city-states.  I built a new city even closer to one city-state with about 7 tiles in-between, but still yet I couldn't send them on a trade route.  Is there something I am missing?

**Comment by LoneGazebo** [comment]
What version?

**Comment by Frid2Dynamite** [comment]
The most recent version of Civ and version 72 of the community patch.

**Comment by ilteroi** [comment]
savegame?

**Comment by Frid2Dynamite** [comment]
Are you asking me to send it?

**Comment by LoneGazebo** [comment]
Yes, he is.

**Comment by Frid2Dynamite** [comment]
Sorry for the inconvenience, but it wont let me send the zip file.  How else can I get it to you?

**Comment by LoneGazebo** [comment]
You can just drag and drop a zip file here.

**Comment by Frid2Dynamite** [comment]
It says it doesn't support the .zip type.

**Comment by LoneGazebo** [comment]
Attach it to a post on civfanatics and link that here, or PM it to ilteroi on civfanatics.

G

**Comment by Frid2Dynamite** [comment]
Here you go, [http://forums.civfanatics.com/showthread.php?p=14173044#post14173044](url)

**Comment by LoneGazebo** [comment]
Thanks!
