### ISSUE TITLE
Marine vs Gunpowder bonus

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1310]
Marines got a unique promotion described as "Bonus vs Gunpowder(melee) 20%". But when mousing over a gunpowder unit in the combat odds window it mentions "Bonus vs Gunpowder 50%".
![2016-02-22_00002](https://cloud.githubusercontent.com/assets/16341598/13206276/2f7dfe40-d903-11e5-92ef-6927e091ee93.jpg)
![2016-02-22_00003](https://cloud.githubusercontent.com/assets/16341598/13206277/34ea83bc-d903-11e5-93f0-821ef30cc0a7.jpg)

**Comment by LoneGazebo** [comment]
Typo, thanks!
