### ISSUE TITLE
AI and fishing boats

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1312]
In some cases I notice that AI fails to build fishing boats on sea resources. 
 I found it strange but didn't pay attention to it. Later a couple of other people mentioned this too in civfanatics CBP thread and I thought I'd post it here.
 In my case Hungary didn't build fishing boats over fish resource near a long-established city.

**Comment by LoneGazebo** [comment]
I'll need a lot more information on this than that- logs, images, etc.
