### ISSUE TITLE
Siege Tower/Battering Ram Non-Sense Revisited: Perennial Winner(now)

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1313]
Just as a header this is a CP issue only and a solution for it (and not a CBP one).

In the mod I'm working on, I wasn't happy to go down the path of the CBP and relegate the Siege Tower to a civilian unit and the Battering Ram as a CS gift. To me they hold too much "uniqueness" of authorial intent (no disrespect to the CBP), but this leaves you with the nonsense. We all know what that is. If those two civs are at war (or even not at war), they will spend their build efforts pumping out Siege Towers and Battering Rams to no end. I've simmed games, where I've seen Atilla at war (and losing) employ 15 battering rams (at least) and maybe a couple of swordsman, and still building battering rams in every city. For a unique unit, one could give it a MaxPlayerInstance value and cap it, but I also didn't find that very balanced. For a unique unit, you might as well not even have it at all, or could you imagine having a MaxPlayerInstance of Impi's (not necessarily a fair comparison as Impi's are far more versatile whereas Towers and Rams are designed to do one thing only, but you get the idea). So I worked on a modifying this function that calls a new function of limiting the unit per city (as defined, in this case one per city, but can be set to 2 or 3, etc.):

```
bool CvPlayer::isUnitClassMaxedOut(UnitClassTypes eIndex, int iExtra) const
{
	CvAssertMsg(eIndex >= 0, "eIndex is expected to be non-negative (invalid Index)");
	CvAssertMsg(eIndex < GC.getNumUnitClassInfos(), "eIndex is expected to be within maximum bounds (invalid Index)");

	CvUnitClassInfo* pkUnitClassInfo = GC.getUnitClassInfo(eIndex);

	if(pkUnitClassInfo == NULL)
	{
		return false;
	}

#if defined(MOD_BALANCE_CORE)
	if(isUnitLimitPerCity(eIndex))
	{
		CvAssertMsg(getUnitClassCount(eIndex) <= (getNumCities() * pkUnitClassInfo->getUnitInstancePerCity()), "getUnitInstancePerCity is expected to be less than maximum bound of UnitInstancePerCity (invalid index)");
		return ((getUnitClassCount(eIndex) + iExtra) >= (getNumCities() * pkUnitClassInfo->getUnitInstancePerCity()));
	}
	else if(isNationalUnitClass(eIndex))
	{
		CvAssertMsg(getUnitClassCount(eIndex) <= pkUnitClassInfo->getMaxPlayerInstances(), "getUnitClassCount is expected to be less than maximum bound of MaxPlayerInstances (invalid index)");
		return ((getUnitClassCount(eIndex) + iExtra) >= pkUnitClassInfo->getMaxPlayerInstances());
	}
	else
	{
		return false;
	}
#else
	if(!isNationalUnitClass(eIndex))
	{
		return false;
	}
	CvAssertMsg(getUnitClassCount(eIndex) <= pkUnitClassInfo->getMaxPlayerInstances(), "getUnitClassCount is expected to be less than maximum bound of MaxPlayerInstances (invalid index)");

	return ((getUnitClassCount(eIndex) + iExtra) >= pkUnitClassInfo->getMaxPlayerInstances());
#endif
}
```
It seems to give a nice balance for an aggressive Hun/Assyria player instead of MaxPlayerInstances:

![8930_screenshots_2016-02-21_00001](https://cloud.githubusercontent.com/assets/14372214/13222888/9c471cde-d947-11e5-9a1b-860d9267d3e7.jpg)
That's the result in a sim game which looks to me to be a balanced composite army.

I know we don't touch units and buildings in the CP, but as the 'nonsense' will still exist there, this might be for the good to enhance player experience.

**Comment by LoneGazebo** [comment]
Rather than calling that in the cantrain function, why not add that to the unitsanity check in the unitproductionAI? Human players might find that frustrating (as it's not terribly clear).

G

**Comment by Iamblichos** [comment]
It is clear :)

```
#if defined(MOD_BALANCE_CORE)
			if(isNationalUnitClass(eUnitClass))
			{
				GC.getGame().BuildCannotPerformActionHelpText(toolTipSink, "TXT_KEY_NO_ACTION_PLAYER_COUNT_MAX", "", "", pkUnitClassInfo->getMaxPlayerInstances());
				if(toolTipSink == NULL)
					return false;
			}
			if(isUnitLimitPerCity(eUnitClass))
			{
				GC.getGame().BuildCannotPerformActionHelpText(toolTipSink, "TXT_KEY_NO_ACTION_PLAYER_CITY_COUNT_MAX", "", "", (getNumCities() * pkUnitClassInfo->getUnitInstancePerCity()));
				if(toolTipSink == NULL)
					return false;
			}
#else
			GC.getGame().BuildCannotPerformActionHelpText(toolTipSink, "TXT_KEY_NO_ACTION_PLAYER_COUNT_MAX", "", "", pkUnitClassInfo->getMaxPlayerInstances());
			if(toolTipSink == NULL)
				return false;
#endif
		}
```

Added new text file to tooltip if unit is that kind of limitation. This is in CvPlayer::canTrain. Does that work?

**Comment by Iamblichos** [comment]
I mean, I tried to make it incentive based, if you want to keep conquering you get to build more as you now have new cities, but if you only have 3 cities let's say, do you really need more than 3 rams/towers? In games, I've played as those civs, I usually never ran more than a handful or so with my armies. Catalogued this with other players too...

**Comment by LoneGazebo** [comment]
I guess I just don't see why a 'strategic' decision should limit a human like that. They're military units, so I feel like it should be discretionary. 

As long as tooltipsink is called in the function it should work, but - like I said- I really think this belongs in unitsanity, not the cvcity.

G

**Comment by Iamblichos** [comment]
Well it's more an aggregate decision based on experience of myself and other experienced players...they are military units, but they are only designed for one thing (unlike the Impi example). I'll keep the function as I think it is useful, and move the intent here over to unitsanity then.

**Comment by LoneGazebo** [comment]
Sounds good. I think, for the purpose of the CP, let's not force it in the cvcity, but rather in the AI unitsanity check. Makes a lot more sense for the CP, IMO.

**Comment by Iamblichos** [comment]
Right. I mean leave the function isUnitLimitPerCity (I will use it in my mod), for the CP I won't enact it for the Ram and Tower, I'll use your suggestion.

**Comment by LoneGazebo** [comment]
Well, it's called by cvcity in the cantrain function (the global cvplayer cantrain is a first-stop break for cvcity cantrain).

G

**Comment by Iamblichos** [comment]
gotcha.

**Comment by Iamblichos** [comment]
Looking at this in the unitproductionAI you already have:
```
//Sanity check for buildable support units.
	if(pkUnitEntry->IsCityAttackOnly())
	{
		int iNum = kPlayer.GetNumUnitsWithUnitAI(UNITAI_CITY_SPECIAL, true, true);
		if(iNum == 0)
		{
			return (iTempWeight * 5);
		}
		else
		{
			iBonus += 50;
		}
	}
```
...though the default Battering Ram and Siege Tower do no have those AI Types nor IsCityAttackOnly set in the UnitEntry so...

- Do you think this function is good? Didn't seem to be all that good, before I made my own unitclass per city restriction. Still saw 1000's battering rams all over the place. maybe could just rewrite and return a value of 0 if GetNumUnitswithAI("UNITAI_CITY_SPECIAL") >=kplayer.getNumCities. Or..

- Or just add a new step in the function with a new unitentry to restrict AI.

**Comment by LoneGazebo** [comment]
Rewriting that is fine by me - wrote that line specifically for the siege tower, but it is hard-capped at 3, so it violates my own rule. :)

Adding the 'CityAttackOnly' element to those units in the CP would allow you to tweak that function as needed.

**Comment by Iamblichos** [comment]
Should we also add UNITAI_CITY_SPECIAL to those units too in the UnitEntry table? or just write the function as UNITAI_CITY_BOMBARD (their default)?

**Comment by LoneGazebo** [comment]
Flipping it to city_special will cause it to behave like a GG, which we don't want. 

G

**Comment by Iamblichos** [comment]
K. then we have a clear path here.

**Comment by Iamblichos** [comment]
Okay Commit done.
