### ISSUE TITLE
Losing Gold notification

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1315]
The right side notification says 'If the empire reaches minus five gold per turn, some of your units will be forced to disband.' I have never ever seen this happen. I've played a good amount of games where I have negative GPT and make my money through Industry or conquest. Because I overbuild units, I've even played more than I should games where I'm losing gpt and at zero gold overall, and I've still never seen it happen. Maybe it can?, but the notification makes it sound like a bigger deal than it is imo.

**Comment by LoneGazebo** [comment]
You have to have a certain size army. It can definitely happen.
