### ISSUE TITLE
Aztec UA Golden Ages

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1316]
I thought this was maybe a balance choice, so I posted it on the forum, but Funak suggested it was a bug, so I'm posting it here too. I apologize if its not, but I generally trust Funak to know the balance choices.

At least on Marathon, the UA Golden Ages are only ten turns compared to iirc 20 for a normal GA. They also increase the cost of normal GAs, meaning I'm prob not going to get one all game.

**Comment by LoneGazebo** [comment]
S'abug.
