### ISSUE TITLE
Plundering enemy caravans

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#132]
In vanilla game if your unit ends turn in the same tile with enemy caravan, the caravan will be plundered during AI turn. It does not happen in CBP.

**Comment by LoneGazebo** [comment]
This was a bug in vanilla civ, as ending your turn consumes all moves, and plundering is supposed to consume a move.
G

**Comment by qqqbbb** [comment]
Plundering does not cost a move.

**Comment by LoneGazebo** [comment]
hmm...I'll look at it.

**Comment by LoneGazebo** [comment]
I've checked into this, and the code is as it should be.
