### ISSUE TITLE
city:ChangeHealRate()

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1322]
I wasn't going to post about this as I've already troubled you for some complicated things viz Health/Disease, but it would be ideal to avoid the workarounds to this issue that I have in mind.

Basically, city:ChangeHealRate(), which I suspect is supposed to change by how much a city heals each turn, doesn't appear to work at all - which is surprising, as FramedArchitect's Health & Plague uses this function. No integer, positive or negative, passed appears to affect the city's healing rate. So, could you please check to see if this actually does anything in the DLL?

I'm not asking for any changes necessarily; - unless there's some bug in the code - just clarification on how, or even if, this function works. Thanks for any help, when you get a chance.

**Comment by LoneGazebo** [comment]
It's all hooked up properly in the DLL. Not sure why it isn't working. The value changes how much the city garrison heals, not the city itself, mind you.

**Comment by JFDaly** [comment]
Oh, lel, I thought it was the city. Never mind then. Thanks for checking.

**Comment by LoneGazebo** [comment]
Yep, just units. Now, if you NEED something related to cities, we can discuss that at some point.
