### ISSUE TITLE
UB Strategy civpedias

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1323]
This one was a bit harder than UUs because being a warmonger I know those better. This is a bit more clashes between Game Info and Strategy sections. If a UB civpedia is off entirely, hopefully me or someone else will notice while playing the civ.

Longhouse Strategy says it increases the city's (apple food symbol) (word production) for each forest. Instead of putting both, you combined them. Also, doesn't mention jungles.
Walls of Babylon Strategy says +100 HP, really 75.
Basilica Strategy says 'use this building to guarentee the estasblishment of a religion' but the Byz UA itself already guarantees that.
Colosseum Game Info and Strategy disagree on what yields are added to Perfume and Olives.
Harappan Res Game Info says it adds 1 (hammer prod symbol) (word food) to Flood Plains.
Satrap's Court Strategy says its less Prod than the Courthouse, but its the same.
Mission Game Info and Strategy both mention making the city harder to convert by others, but aren't Spanish cities impossible to convert already? 
Ostrog Game Info mentions Great Wall esque effect, but nothing on quicker culture border expansion. Ostrog Strategy mentions quicker culture border expansions, but nothing on Great Wall esque effect. Honestly, idk if it has one or both, or even if it also affects tile gold price.
Doge's Palace Game Info says it contains a spot for a Great Work of Art, but it doesn't.
Great Cothon and Smithsonian Game Infos don't mention increasing in cost per city, which I assume they do.
Smithsonian Strategy is missing a space. Says 'The Smithsonianalso boosts'
I also noticed you moved all Diplomacy NWs over to the NW page besides the Printing Press. Obvi, you possibly have a reason, but I thought I'd throw it in here in case you just forgot.
Brazilwood Camp Game Info mentions scaling at Acoustics, but not the other places it scales. Actually, that's of the few scalings mentioned. With the new tech tree, I don't think any is needed really, just weird there's a couple.
Chateau Game Info has the wrong yields, and like Brazilwood Camp, only mentions one scaler. Yeah, these are the only two scalers mentioned.
This is such a technicality, but even in just your mod, there are ways for civs other then Port to build Feitorias thru Naus, CS gifts and Sea Beggar captures. I had a game where I built a ton, but that was with JFD Mercs. I'm prob just overthinking this bit.
Kasbah Game Info has the wrong yields.

**Comment by LoneGazebo** [comment]
Fantastic, thanks! Typos and mismatched text is one of the most time-consuming things, so you are a hero.

**Comment by pandasnail** [comment]
Awwww, thanks! Just trying to do what I can to help with this amazing mod y'all have made.
