### ISSUE TITLE
Can't build plantation on Coffee

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1324]
Playing the latest Feb-24 Beta. A worker cannot build a plantation on a coffee resource. The option to build a plantation is not present neither in worker's actions nor as a tile ghost hint. The Calendar Tech has been long discovered.
 
 
![2016-02-25_00001](https://cloud.githubusercontent.com/assets/16341598/13328683/aec3be7c-dbf8-11e5-995a-a9058cc9f1c7.jpg)

**Comment by LoneGazebo** [comment]
Sounds like an installation issue. Your database log is clean?

**Comment by saamohod** [comment]
I must admit I have little clue as to what it means.

**Comment by saamohod** [comment]
I deleted and reinstalled the mod. Now it seems to work.

**Comment by LoneGazebo** [comment]
Weird, sounds like a bad install or something.
