### ISSUE TITLE
AI not disbanding units

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1325]
this was in turn 300 after autoplay

![image](https://cloud.githubusercontent.com/assets/1358966/13332434/443046f2-dc02-11e5-88e4-866fb5588439.png)

world map was almost completely revealed - no use for these explorers any more

**Comment by LoneGazebo** [comment]
Interesting. I wonder, were these units still using the explorer AI, or had they been changed into something else? In either case, they should definitely have been disbanded.

**Comment by ilteroi** [comment]
fixed. turns out there was no code for disbanding explorers except if they are stuck. and the regular disband code wants units to be 4 (!) eras out of date before giving up on them. made that 3.

also fixed some annoying suicidal pathfinding :)
