### ISSUE TITLE
AI won't repair pillaged town

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1326]
At turn 295 I noticed that AI didn't repair pillaged towns. So I made a savegame and waited till turn 320.  AI never tried to repair, no matter if at war or at peace. 
![2016-02-26_00004](https://cloud.githubusercontent.com/assets/16341598/13342485/c332f92a-dc4a-11e5-8e09-215fe1ca36f7.jpg)
![2016-02-26_00003](https://cloud.githubusercontent.com/assets/16341598/13342486/c3a4c0be-dc4a-11e5-821a-0a209fdbfc13.jpg)

[pillaged town.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/147645/pillaged.town.zip)

**Comment by LoneGazebo** [comment]
Just towns? Academies?

**Comment by saamohod** [comment]
I only noticed concerning towns. 
Savegame attached.
