### ISSUE TITLE
UI: Pledge protection in CS diplo screens

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#1327]
> November 5th (11/5)
> http://forums.civfanatics.com/showthread.php?t=557942
> Offset protections data in CS diplo screens so it doesn't get cut off so easily
> 
> February 24th (2/24)
> http://forums.civfanatics.com/showthread.php?t=563523
> Added minimum military power (must be in top 60% of major civs) to do a PtP with a CS

Pledge protection would be less common than before.
How about reverting the position of protections data? (CityStateDiploPopup.xml)
Although it may be too early to do that, I prefer the old style.

![cs diplo screen](https://cloud.githubusercontent.com/assets/11933188/13352632/e162c164-dcd1-11e5-814a-4652b0dd7f44.png)
![10-29_2-24](https://cloud.githubusercontent.com/assets/11933188/13352646/fc408408-dcd1-11e5-96f6-cde70f2a41a4.png)

I can upload the version 10/29 if you need it.

**Comment by LoneGazebo** [comment]
I can adjust it back if needed, but I had it that way because 3 or 4 PtP would cause the line to bleed over into the divider line below. It's not a huge problem, but let's wait and see how PtP plays out.

**Comment by 8h42** [comment]
That's fine.
We need several more weeks or months.
Thank you for your reply.
