### ISSUE TITLE
Some resource trades not ending properly (possibly related to playing The Dutch)

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1329]
Instead of ending and freeing up the resources for new trades, certain resource trades for me show up in the deal history as Turn Ended -2 Turn Started -1 Duration -1 Turns. The resources traded still count to the Dutch UA (assuming its +8 in the medieval), happiness (if imported). I don't get them back to trade if exported, and can't acquire again if imported. The traded gold seems to be permanent as well.

But its not all trades, is the weird part. I think its related somehow to DoFs, the trades that end properly have all been with my three not-friends. But those three are also all civs I've been to war with, so that's another correlation. I canceled a DoF the turn before a trade ended, and it still went to the Turn Ended -2 stuff. Declaring war before it ends does cancel the deal properly. Declaring war after the fact does nothing, the old trades remain in the Turn Ended -2 state.

If logs work like I think they do, restarting each load, all I can post is one turn's worth, before and after such a trade, but not the whole breadth of trades. But if that's helpful, let me know which ones you want.

**Comment by pandasnail** [comment]
I always forget to put: playing with the 2/24 beta

**Comment by LoneGazebo** [comment]
Just the CP?

**Comment by pandasnail** [comment]
Oh, I always forget modlist too.

No, all your six, eui, plus Ice free coasts, celtic city names, iroquoian city names, randomize city names, flagpromotionsv4, more great works, noaltitudetraining, and my own version of the 'wario's rules' sql that was posted on the forum.

When I said the luxuries still count for the UA, I meant I'm getting the +8 culture per import or +8 gold per export still even for these -2 turn deal ended trades.

**Comment by pandasnail** [comment]
Kept playing and the next two trades to finish went fine. I've still got nine deals in history messed up, but the new ones are maybe fine idk. I didn't change or reinstall anything, maybe I should have but I was worried that would mess up the save file somehow. Idk. I'll post if it comes back, Between the work stuff you mentioned and thinking about the new science, hopefully you didn't think about this too much.

**Comment by LoneGazebo** [comment]
Okay, let me know.

**Comment by pandasnail** [comment]
Don't know if you remember this, but in case its taking a tiny tiny sliver of your mind or something: I'm playing one last game on the 2/24, and when it was happening, I thought it thru and I'm 95%  sure its because I recently enabled Human Vassalage. Somehow trades were looking to see if vassalage was involved, and when they saw vassalage was impossible due to tech era, this happened. Since that system has been overhauled, I imagine its a nonfactor now.
