### ISSUE TITLE
CP crash

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#133]
Game crashes during AI turn.
 Savegame and dump: https://dl.dropboxusercontent.com/u/28753474/CP%20crash.rar

**Comment by LoneGazebo** [comment]
What version? Also, what mods?
G

**Comment by qqqbbb** [comment]
Could CBP cause the crash? I'm not using any mods that affect gameplay.

**Comment by LoneGazebo** [comment]
It is probably an E&D issue.

G

**Comment by qqqbbb** [comment]
I'm not using E&D. My savegame requires 3 mods: CP, CBP and Really advanced setup.
