### ISSUE TITLE
Trireme not getting England's +2 movement bonus

### ISSUE THREAD

**Issue by cosmosgu** [LoneGazebo/Community-Patch-DLL#1330]
Dromon gets England's +2 movement bonus while trireme doesn't.
![Trireme](http://images.akamai.steamusercontent.com/ugc/315620766164700801/2181BBA664B99F0A95837D9CFD4C80EA8F10FD42/)
![Dromon](http://images.akamai.steamusercontent.com/ugc/315620766164700984/CAD793336B49695869F51DBB9E4600092032FD0C/)

Mod installed:
Community Patch - Modpack (Multiplayer Compatible) --- CPProject Full EUI 1/23

**Comment by LoneGazebo** [comment]
The MPP from 1/23 has an issue with savegames and that value.

G

**Comment by cosmosgu** [comment]
@LoneGazebo Got it. Thanks for the reply.
