### ISSUE TITLE
No trade route options.

### ISSUE THREAD

**Issue by zimeron** [LoneGazebo/Community-Patch-DLL#1331]
Loving the patch and all its various ancillary mods.  One problem:  I don't have any options for cities to send a cargo ship/caravan to in the menu.

The mods I am running are:

Community Patch
Community Balance Patch
City State Diplomacy
Civ IV Diplomacy Features
More Luxuries
CBP Compatibility files (EUI)
JFD's Civilization collection
Civ Names by Policies
Historical Religions
City Limits
Quick Turns
RED Modpack
Randomize City Names
Unique Cultural Influence

None of these should be affecting trade route interface AFAIK, except for the Community Patch stuff, and since I can't seem to find this issue on the interwebz, figured I would go ahead and post here.

I am running the latest Community Patch installed with the Auto Installer (version 1.1.23)

Here's screenshots of the empty menu:

Caravan (not sure it's close enough to anything, but it has tested to not work in other saves):
![notraderoutecaravan](https://cloud.githubusercontent.com/assets/6914501/13370837/267ed416-dce3-11e5-8115-489bbdfa7e7a.png)

Cargo Ship (definitely is in range):
![notraderoutecargoship](https://cloud.githubusercontent.com/assets/6914501/13370844/505e87a4-dce3-11e5-92f4-b5c12e4c400b.png)

Save file source of screenshots:
[NoTradeRoutesIvanIV.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/149202/NoTradeRoutesIvanIV.zip)

Let me know if you need logs and where to find them and I can pop them up for you.  Thanks guys, great mods otherwise.

**Comment by LoneGazebo** [comment]
What version of the CP?

**Comment by zimeron** [comment]
As I mentioned, it's version 1.1.23 installed using the automatic launcher found here.
http://forums.civfanatics.com/showthread.php?t=528034.

At least I assume it's 1.1.23, since that's supposedly the latest version listed on that thread.  It's whatever version was out for download on Feb 26 2016.

**Comment by JFDaly** [comment]
Issue with Hatshepsut.

**Comment by zimeron** [comment]
I haven't used Hatshepsut and have had this problem in multiple civs (So far Ivan IV and Washington).  Hatshepsut is installed, but have never played as her.

**Comment by JFDaly** [comment]
It can still occur without her being in the game.

**Comment by zimeron** [comment]
Really?  Does anyone know why?  I think I had her installed before updating the CP to current version several days ago and it worked fine.  I can try removing to see if that helps but I am skeptical.

**Comment by zimeron** [comment]
We'll I'll be damned.  That worked like a charm.  Sorry for wasting Gazebo's time haha.  Thanks mate!  Hopefully JFD's aware, that's an annoying little bug.

**Comment by JFDaly** [comment]
I think JFD's aware ;) It would be helpful if you could post your Lua log to my thread so that I can take a look.

**Comment by zimeron** [comment]
Where's that located?  Not familiar with the file structure.

**Comment by JFDaly** [comment]
If you mean your Lua log, see [here](http://forums.civfanatics.com/showthread.php?t=487482).
If you meant my thread, see [here](http://forums.civfanatics.com/showthread.php?t=474393).

If you have any problems with logging, please bring them up in my thread, so that Gazebo can close this issue.

**Comment by LoneGazebo** [comment]
Thanks!
