### ISSUE TITLE
Question re: PlayerCanFoundCity()

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1332]
This may be another case of my misunderstanding a function, but how is GameEvents.PlayerCanFoundCity() supposed to work? I figured it would allow me to block a player from being able to found a city at a particular spot, but this doesn't seem to be the case - even having the event default to false appears to have no effect. Appreciate any info about this event. Thanks.

**Comment by ilteroi** [comment]
just checked it, the event was hooked up in a strange place, i set the "site value" of the plot to zero, which is mostly interesting for the AI. but didn't actually stop you from founding.

so now i moved it to the correct (imho) place. code looks like this.

```
#if defined(MOD_EVENTS_CITY_FOUNDING)
	if (MOD_EVENTS_CITY_FOUNDING) {
		if (GAMEEVENTINVOKE_TESTANY(GAMEEVENT_PlayerCanFoundCityRegardless, GetID(), iX, iY) == GAMEEVENTRETURN_TRUE) {
			return true;
		}
	}
#endif

#if defined(MOD_EVENTS_CITY_FOUNDING)
	if (MOD_EVENTS_CITY_FOUNDING) {
		if (GAMEEVENTINVOKE_TESTALL(GAMEEVENT_PlayerCanFoundCity, GetID(), iX, iY) == GAMEEVENTRETURN_FALSE) {
			return false;
		}
	}
#endif
```

**Comment by JFDaly** [comment]
Awesome! Thank you.
