### ISSUE TITLE
Unit:GetOriginalCombatStrength() and Unit:GetOriginalRangedCombatStrength()

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1333]
Would it be possible to have this function where it would get the original base strength? I'm doing a Unit:SetBaseCombatStrength that changes periodically over time, but without an original integer, I enter a recursive function of infinite strength. I could just do a number for its original base strength, but I would rather have it on every unit.

**Comment by LoneGazebo** [comment]
Super-Saiyan mode not fun? 

INFINITE POWER!!

**Comment by TechpriestEnginseer** [comment]
So.. is it possible or no?

**Comment by LoneGazebo** [comment]
I'unno I'm not in town.

**Comment by LoneGazebo** [comment]
If you are changing base combat strength, you're changing the core modifiable variable. Sorry, nothing I can do about that.

**Comment by TechpriestEnginseer** [comment]
I want to utilize this LUA function.
````
Unit:SetBaseCombatStrength(Unit:GetOriginalCombatStrength+Variable)
````
I'm asking if LUA could extract the unit's original combat strength through the database rather than the unit itself.

**Comment by LoneGazebo** [comment]
Can't you just grab the unitinfo for that? No need for a new function.

G

**Comment by TechpriestEnginseer** [comment]
UnitInfo?

**Comment by JFDaly** [comment]
Wouldn't GameInfo.Units[unitID].Combat work for this purpose?

**Comment by LoneGazebo** [comment]
Yep, that's what I was referring to, @JFDaly.

G
