### ISSUE TITLE
Melee ships can't attack out of port

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1334]
As title says, I cannot order an attack with melee ships if they are inside a city.

**Comment by ilteroi** [comment]
that's by design. was changed in one of the latest versions.

**Comment by LoneGazebo** [comment]
Yep!

**Comment by ilteroi** [comment]
ah. i see what you mean. you cannot attack anything, even if the ship would have to move out of the city before attacking. will check

**Comment by ilteroi** [comment]
i cannot find an easy way to implement the "no attack from harbor" for melee units. so i reverted this part.

**Comment by Iamblichos** [comment]
weird....this doesn't do the job?

```
bool CvUnit::IsCanAttackWithMove() const
{
    VALIDATE_OBJECT
    if(!IsCombatUnit())
    {
        return false;
    }

    else if(getDomainType() == DOMAIN_SEA && !plot()->isWater())
    {
        return false;
    }

    else
    {
        return !isOnlyDefensive();
    }
}
```
