### ISSUE TITLE
city:CountNumWorkedRoutes(routeID)

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1335]
Similar to the CountNumWorkedRiverTiles, I'd like to request a CountNumWorkedRoutes(). This would calculate how many tiles with a specific route (road or railroad) are being worked by the city. Thank you!

EDIT: Sorry! Turns out I don't need this after all - I'm discovering that so much plot-wise works with Health naturally. Did something change? I swear they didn't work before. Regardless, nevermind this request.

**Comment by LoneGazebo** [comment]
I made a few key changes to yields so that less used yields get exposure on plots. You're welcome!

**Comment by JFDaly** [comment]
Awesome. Thanks indeed!
