### ISSUE TITLE
Scout stopped gaining experience from revealing territory

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1336]
As the title says, at some point my Scout stopped gaining experience from revealing new tiles despite possessing the Scout Promotion.

[Scout exp.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/149643/Scout.exp.zip)

![2016-02-28_00004](https://cloud.githubusercontent.com/assets/16341598/13376235/abb39798-ddbf-11e5-9c1e-41e18f2391d5.jpg)
![2016-02-28_00005](https://cloud.githubusercontent.com/assets/16341598/13376237/ac850c74-ddbf-11e5-94b1-ea72a3462e6f.jpg)

**Comment by Kolaris8472** [comment]
Yes, the limit is set in (1) Community Patch/Core Files/Core Values/Core Defines.sql, line 191.

**Comment by saamohod** [comment]
What kind of limit is that?
