### ISSUE TITLE
PolicyType on Units is broken.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1338]
Any policy unit that has its policy unlocked and technology researched will not be trainable at all.

**Comment by LoneGazebo** [comment]
You sure? Ones in CBP seem to work just fine.

**Comment by LoneGazebo** [comment]
If you have MinorCivGift enabled, they won't work. Must FYI.

**Comment by TechpriestEnginseer** [comment]
Something Something having FaithCost requires you having FaithPurchaseEnabled as well.

**Comment by LoneGazebo** [comment]
MinorCivGift is a unit attribute, makes them available via minor civ gift only.
