### ISSUE TITLE
still some wild building choices

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1339]
![image](https://cloud.githubusercontent.com/assets/1358966/13378261/38d8f826-de00-11e5-987b-f6e9796f9764.png)

this is in the capital of indonesia in the year 2000. many basic buildings still missing. never conquered. in fact, indonesia is the leader in this game.

latest version from github.

**Comment by LoneGazebo** [comment]
Does the building production AI have any oddities?

**Comment by ilteroi** [comment]
you lost me there ... that seems to be a rather big oddity :)

and it's not only in one city.

**Comment by LoneGazebo** [comment]
I guess what I mean is, are these buildings being dropped off of the POST list for all cities?
