### ISSUE TITLE
Friendly AI Civilizations offering empty "gesture of gratitude"

### ISSUE THREAD

**Issue by cosmosgu** [LoneGazebo/Community-Patch-DLL#1341]
Friendly AI Civilizations frequently offer me empty "gesture of gratitude". Clicking "Accept" has no effect and I am forced to click "Refuse", which results in an inevitable diplomatic penalty.
![1](http://images.akamai.steamusercontent.com/ugc/315620766170408441/0B7B3F24EF9DD6250BB838E80521C4A62874078B/)
![2](http://images.akamai.steamusercontent.com/ugc/315620766170408711/9A546F658EACEA6045B0D1363291FF6680CD828E/)
![2](http://images.akamai.steamusercontent.com/ugc/315620766170408862/D36089F44CF6692AD70C4ECF3099EEE7A35CEE26/)

Mod installed:
Community Patch - Modpack (Multiplayer Compatible) --- CPProject Full EUI 1/23

**Comment by LoneGazebo** [comment]
This is a modpack issue. Can't fix.

**Comment by LoneGazebo** [comment]
Or rather, someone else is in charge of the fix.

**Comment by cosmosgu** [comment]
@LoneGazebo Glad to hear it!
