### ISSUE TITLE
embarked defense

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1342]
i've recently fixed embarked defense to work as designed, strength is an era dependent base value (16) plus some percentage (33) of regular strength.

now, it seems this is a bit high:

cruiser ranged attack on embarked infantry:
![image](https://cloud.githubusercontent.com/assets/1358966/13378611/e708e6bc-de0b-11e5-8214-1f7a680b0ce4.png)

melee attack with a destroyer on same infantry:
![image](https://cloud.githubusercontent.com/assets/1358966/13378617/1ec8fb78-de0c-11e5-8ed7-39e1c65ffe27.png)

my feeling is that an embarked unit should be very vulnerable and be killed in one attack by a same-era unit. of course, AI being inscrutable as it is, this change might put them at a disadvantage (working on it ...) but what's the opinion on this, should embarked strength be reduced?

**Comment by LoneGazebo** [comment]
I think embarked units should have strength equivalent to prior era melee ships. This will make them more survivable, but that also helps the AI a lot, which is good.

**Comment by Iamblichos** [comment]
I agree with G, embarked units are a type of boat unit, so they should have some kind of defense and resistance.

**Comment by ilteroi** [comment]
so you think we're in a good spot right now? then i'm closing this issue

**Comment by LoneGazebo** [comment]
Yep. Sounds good.
