### ISSUE TITLE
CS Revolutions

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1343]
I hope I don't sound too whiney, but the revolution against master event is a bit overtuned...
![2016-02-28_00001](https://cloud.githubusercontent.com/assets/16065630/13379126/d64bc76a-de1d-11e5-8a4c-7f47211d0db5.jpg)
If this would be it, I wouldn't complain - but is actually the 5th such wave.

**Comment by LoneGazebo** [comment]
Has a randomizer in it. Sometimes bad randomizer is bad.

**Comment by LoneGazebo** [comment]
Reduced slightly.
