### ISSUE TITLE
third party war without notification

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1345]
i have a situation here where venice bribes the iroquios into declaring war on me, but there is no notification.

@g: is this issue solved already or do you need the savegame?

**Comment by LoneGazebo** [comment]
No notification how? You have to have a spy in either in order to get a notification explaining who bribed whom.

**Comment by ilteroi** [comment]
i expected a notification for the war declaration. or better yet, a popup ...

**Comment by LoneGazebo** [comment]
Should say 'x has declared war on you' on a notification in the corner. In any case, I'm adding a leaderhead popup for the next version.

**Comment by TechpriestEnginseer** [comment]
I can confirm this is bug that can be reproduced. I had 4 civilizations declare war on me with no notification except that they're just going to war.

**Comment by LoneGazebo** [comment]
Right, but you still get the DOW notification in the bottom-right, correct?
