### ISSUE TITLE
AI makes peace immediately after losing a city

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1346]
i thought there was a cooldown timer somewhere? or was that removed?

just conquered a city, offered peace in the same turn and they accepted.

**Comment by LoneGazebo** [comment]
There's a one turn timer if they have no operation to take it back.

**Comment by LoneGazebo** [comment]
Peace desire can overrule, though.

**Comment by ilteroi** [comment]
[embarked-capture.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/152252/embarked-capture.zip)

this is the savegame. might need to merge my latest for it to work. use the embarked infantry to capture the zulu city and offer peace immediately.
