### ISSUE TITLE
Incorrect zone-of-control calculation / Incorrect bridge calculation

### ISSUE THREAD

**Issue by cosmosgu** [LoneGazebo/Community-Patch-DLL#1347]
Both tiles are improved by road and a bridge is clearly visible. Yet, when I ordered my knight to move in one tile, it lost all of its movement points.
My guess:
This is either caused by incorrect zone-of-control calculation, or is caused by Incorrect bridge calculation.
![1](http://images.akamai.steamusercontent.com/ugc/315620766172392729/9C7EAD1CD46223D75D074B7C98ACF2C3982F6972/)
![2](http://images.akamai.steamusercontent.com/ugc/315620766172393106/AA59093F7073D42FAE60EC143AC620D8AC202AB1/)
![2](http://images.akamai.steamusercontent.com/ugc/315620766172393225/C60872D637C1716E050BC0553ED5291AD0ABA963/)

Mod installed:
Community Patch - Modpack (Multiplayer Compatible) --- CPProject Full EUI 1/23

**Comment by ilteroi** [comment]
there are two things can go wrong here:
- you do have the engineering tech, right? otherwise a river ends your turn, even if poland built the brigde
- you cannot use enemy roads, so if you're at war with poland (i.e. no open border) this would also be ok

**Comment by cosmosgu** [comment]
@ilteroi 
Thank you for replying!
- Yes, I do have engineering tech. I never know that without researching it myself I can't use other civilization's bridge!
- Got it! I never know that I can't use enemy's bridge/road during war with them.
This ticket can be closed.
