### ISSUE TITLE
Civ 4 Diplomacy Beta Integration

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1348]
Hello! :D

Civ 4 Diplomatic Features' latest updates is extremely close, and I mean tomorrow night or tuesday night, ready for integration into this Beta.

There are lots of things to consider here before I move on so I need your help before I actually make the pull request.

1. Should this be integrated into CBP's beta? Should I do this separate? It's stable on my end, but I develop with CP only, not CBP, so I have no idea if it'll be stable (although my gut tells me it will be!). I'm totally fine with hosting a separate "build" and integrating later if that's what you want.

2. I have a mod called "(1a) Community Patch - C4DF Addon) which is my custom build for Civ 4 Diplomacy. It's where I currently host all of my LUA SQL and XML changes for the mod. This needs to be included as part of the release package going forward (as it's the version I'll play) alongside C4DF CBP. How should I structure the package so that it integrates well with the existing mod structure and installer?

This may need more discussing, so I don't want to make any hasty moves.

Anyway, I'm very excited!

**Comment by LoneGazebo** [comment]
Sounds good. So what's happening to the actual C4DF mod (the one currently bundled into the full CPP package)? We should use that as the host for your new changes.

DLL-wise, I just need your changes so I can manually merge them.
G

**Comment by mwhiter** [comment]
Well for now I was developing with CP in mind only. C4DF was gonna receive an update once CP / CBP versions are stable (which sounds backwards, but I prefer to develop for this mod anyway now).

As far as I know, Top panel is the only LUA file that I've made changes to because it wasn't playing nice with CBP...but that shouldn't be too hard.

Where should the LUA files go for C4DF. Should my Community Patch - C4DF Addon mod only contain LUA files for the mod while the non-EUI compatibiltity mod hosts the other C4DF LUA files? And my Civ IV Diplomatic Features folder contain just the XML / SQL?

**Comment by LoneGazebo** [comment]
The C4DF shipped with the CPP full package is your old C4DF with all lua stripped out. So whatever XML/SQL changes you make should go in that. Lua changes should go in the EUI and No-EUI Compatibility file (should be merged with the existing lua files in both). The entirely new LUA (i.e. your vassal screen) should go in C4DF, as they won't be overwritten.

G

**Comment by mwhiter** [comment]
Okay, I used WinMerge to merge the files I needed to. I think I'm good to go. I'll make a pull request once I do a once-over and I'm confident it's correct.

**Comment by LoneGazebo** [comment]
Sounds good.

**Comment by mwhiter** [comment]
Regarding serialization, I incremented the DLL version in order to preserve save integrity, you may want to consider changing it to suit your needs. Just let me know what version # you want the serialization to have.

**Comment by LoneGazebo** [comment]
I'll increment up to your value whenever the merge takes place.

**Comment by LoneGazebo** [comment]
Merged and in 3/1. Let's see how it goes!

**Comment by mwhiter** [comment]
Yes! The only thing we're missing is the (1a) custom CP only project.

**Comment by LoneGazebo** [comment]
It is on github.

**Comment by LoneGazebo** [comment]
Did you want me to distribute it? I figured you wanted to handle that. Overlap of CP lua needs instructions from you.

**Comment by mwhiter** [comment]
The mod handles it's own LUA so you can distribute that. It blocks CBP so they can't use that and C4DF CBP at the same time. So yes :) 

Thank you for everything!

**Comment by LoneGazebo** [comment]
If the LUA files are the same as the CP's, they need to be deleted from the CP or you risk overwrite issues. That's why CP lua is deleted if you run the CBP, etc.

**Comment by mwhiter** [comment]
I was developing the whole time in CP and that special mod, I didn't run into any issues.
