### ISSUE TITLE
CTD on loading a modded game

### ISSUE THREAD

**Issue by DongWizard** [LoneGazebo/Community-Patch-DLL#135]
I hope I'm using this site correctly.
I have lost two 100+ turn games now, running only the community patch mods, minus health & plague and plus really advanced setup. 
The games play fine, and I was able to reload every save up to ~70 or so, but if I play and save past that I am unable to reload the game later. It will just crash to desktop without any dialog box. I can still start and play new games with these mods on, and that works, but cannot find a way to get back to my lost games.
Please help! :c

**Comment by LoneGazebo** [comment]
Try the latest version (3/6) and report back.
G
