### ISSUE TITLE
City ranged fire is not working correctly

### ISSUE THREAD

**Issue by cosmosgu** [LoneGazebo/Community-Patch-DLL#1350]
I have researched mathematics ("City ranged strike range increased by 1") and built castle ("indirect fire") in my city. Yet, my city can not fire over obstacles and can only strike two tiles away.
![1](http://images.akamai.steamusercontent.com/ugc/315620766173734814/D60E81195BDF63A5E1474F35669EBF92E411E148/)
![2]
(http://images.akamai.steamusercontent.com/ugc/315620766173734966/C98204A14F62BAF3C9D42C91CCD0A632D0A42CB3/)
![3](http://images.akamai.steamusercontent.com/ugc/315620766173735053/E0E80C5219C8113BC0D6C3C1148EA5D280533689/)

Mod installed:
Community Patch - Modpack (Multiplayer Compatible) --- CPProject Full EUI 1/23

**Comment by TechpriestEnginseer** [comment]
No, no it's gunpowder that makes you fire over obstacles. The castle tooltip is misleading.

**Comment by cosmosgu** [comment]
@LoneGazebo Thanks for following up. Is the two-tile attack range also intentional?

**Comment by LoneGazebo** [comment]
Yes. Starts at one. Two at math.

**Comment by cosmosgu** [comment]
@LoneGazebo Thanks! I thought it starts at two.
