### ISSUE TITLE
UNITCLASS_FOR_CS_BULLY oversight

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1351]
There's been a bit of an oversight about the UNITCLASS_FOR_CS_BULLY define that you added in the last patch. I want to change the Unitclass here to my Slave Unit Class, but because this is a modded unit, its ID is not static, so assigning a specific ID to this define is not feasible. 

Defines do not appear to need integers set for the value (despite the precedent) - so would it be possible to just specify the unit class by type?

**Comment by LoneGazebo** [comment]
I'll look into it.

**Comment by LoneGazebo** [comment]
Alright, so I've decided to actually fix this. Now, there will be an assignable 'bully unit' for each minor civilization in the game (currently defined as Unitclass_worker for all CSs). I've also made a pair of lua functions for you, SetBullyUnit(UnitClassTypes eUnitClass) and GetBullyUnit(). You'll call these for the individual CSs themselves, Should offer the granularity you want, while also allowing you to edit the value on the fly. Bonus: these values auto-populate in the CS diplo popup (i.e. the 'enslave a unit' button).

**Comment by JFDaly** [comment]
Erhm, ouch. But thanks! That sounds excellent.

**Comment by LoneGazebo** [comment]
Yep. Note that you'll need to pass the integer value of the Unitclass you want to set in the SetBullyUnit function.

G

**Comment by LoneGazebo** [comment]
@JFDaly , this is added in 3/1 beta.
