### ISSUE TITLE
AI still fires at city with 1HP and does not conquer it with melee units

### ISSUE THREAD

**Issue by cosmosgu** [LoneGazebo/Community-Patch-DLL#1353]
If I recall correctly one of the key changes of smart AI (which is part of CBP) is "AI should not attack over and over a city with 1 HP remaining. ". In my recent game Babylon still keeps firing at my city state ally with its ranged troops and does not conquer it with its melee troops.
Update:
They eventually captured that city after three turns. But in all four turns they keep firing at the city even when its health has completely been depleted (which behaves just like native AI).
![1](http://images.akamai.steamusercontent.com/ugc/315620766177546166/A7C2AA6A3B96BB0E80D4DFBE8C78996148AB174B/)
![2](http://images.akamai.steamusercontent.com/ugc/315620766177546348/FB3F0C3C0342D84A3889ADF0E950A62E17CF78A9/)

Mod installed:
Community Patch - Modpack (Multiplayer Compatible) --- CPProject Full EUI 1/23

**Comment by ilteroi** [comment]
please retest in the next (beta) version when it's out, there have been some changes in this area lately. should be better now

**Comment by cosmosgu** [comment]
@ilteroi Awesome! Thanks.

**Comment by Edaka** [comment]
Can confirm that it's still an issue in the 3/1 beta. The AI focuses all of its ranged units on a city that only needs to take one shot to be brought to 0 hp, even preferring that over shooting at my units nearby.

**Comment by LoneGazebo** [comment]
@ilteroi , perhaps a check for city HP should be made mid-city-attack, so as to free up units for unit-to-unit attacks?

**Comment by ilteroi** [comment]
there should be one already. but i'll double check.

**Comment by ilteroi** [comment]
the check is there ... need to set up a test case

**Comment by ilteroi** [comment]
ok, turns out ranged attacks never reduce a city below 1 hitpoint .. but the check was for 0.

**Comment by ilteroi** [comment]
huh. found a bug, the garrison protection was only implemented for melee attacks, not for ranged. fixed now.

**Comment by LoneGazebo** [comment]
Coolio.
