### ISSUE TITLE
Winning war as Arabia triggers variable amount of Historic Events

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#1354]
Won a war as Arabia, 4 historic events were triggered. Reloaded and made peace again, 2 historic events were triggered. Playing full CPP (w/EUI) made into a personal modpack (no active diplomacy or anything).

Modpack DLC - https://drive.google.com/open?id=0BxQ5ePZeOZ_UY2JpcEJOamdCOUk
![2016-03-01_00001](https://cloud.githubusercontent.com/assets/11132095/13447710/35a4ec7a-dfe3-11e5-8fce-1b806d653017.jpg)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/153914/Logs.zip)
[Historic Event.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/153916/Historic.Event.zip)

**Comment by LoneGazebo** [comment]
Found myself, fixed earlier. Is in 3/1 beta.
