### ISSUE TITLE
[Suggestion/Question] 3-tile range fire issue

### ISSUE THREAD

**Issue by cosmosgu** [LoneGazebo/Community-Patch-DLL#1355]
This is probably an issue with the native game. But I would like to ask if there is an existing fix for it.
As you might be able to see in the screenshot below, my volley gun has a fire range of 3 tile, but it cannot fire at that rifleman on the right side.
What bothers me is that, geometrically, that volley gun would have a smaller arc of fire (30 degrees) if he moves to the tile where my great general is. Yet, he will be able to fire at that rifleman over there.
![1](http://images.akamai.steamusercontent.com/ugc/315621401143541715/F4DFF98B2F896AFD286DE8EB7B163B8290D283E8/)

Mod installed:
Community Patch - Modpack (Multiplayer Compatible) --- CPProject Full EUI 1/23

**Comment by LoneGazebo** [comment]
The Mesa blocks it. It is a byproduct of how LoS works with hexes.

**Comment by ilteroi** [comment]
I think he means that there's a 3 tile path passing to the right of the mesa. which is kind of true.

but tell you one thing, i've made a lot of daring decisions, but i won't touch the visibility code :)

on the other hand, range 3 is quite powerful already, so i think it's fine as it is.

**Comment by cosmosgu** [comment]
@ilteroi Thanks for the reply.
