### ISSUE TITLE
possibly mistake

### ISSUE THREAD

**Issue by Pusperk** [LoneGazebo/Community-Patch-DLL#1356]
Last build

I miss this row in VassalageOverview.lua for function OnYes( type, iValue )

Controls.Yes:RegisterCallback( Mouse.eLClick, OnYes );  //THIS

**Comment by LoneGazebo** [comment]
I'll tell  putmalk

**Comment by mwhiter** [comment]
You're getting a runtime error there? What specific error? I'm not able to debug until I get home from work.

**Comment by Pusperk** [comment]
It is not mistake. I test this and all is right. You can close this task.
( when i first look at code i miss call this function. I found it later)
