### ISSUE TITLE
units without icons

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1359]
![image](https://cloud.githubusercontent.com/assets/1358966/13475954/d369d9c4-e0c5-11e5-894c-7842b5537278.png)

this happens time and again but i've never had two units with this problem next to each other. anybody know what could be causing this?

**Comment by LoneGazebo** [comment]
It happens to me too, and others as well. So far as I know it's a graphical engine bug. It can also happen where a unit's flag stays visible whether or not the unit is visible.

**Comment by ilteroi** [comment]
intentional is a stretch :)

**Comment by LoneGazebo** [comment]
Hehe, I didn't have an applicable label. I guess I should make a 'Firaxis Did It' one, no?
