### ISSUE TITLE
Assyrian UB and UU

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#1360]
UB doesn't give XP per Great Writing.
UU doesn't give an anti-city attack bonus to the unit on the same tile.

**Comment by LoneGazebo** [comment]
I just tested the Royal Library, and it worked for me.

**Comment by LoneGazebo** [comment]
Fixing other issue, though.

**Comment by Radost** [comment]
It clearly doesn't work in my game though.
This is my capital, Royal Library + Barracks:
![8930_2016-03-03_00006](https://cloud.githubusercontent.com/assets/1131228/13503097/9f1ff778-e18f-11e5-9041-aa84cb83e558.png)
This is a freshly built unit in my military center with Barracks and Armory:
![8930_2016-03-03_00007](https://cloud.githubusercontent.com/assets/1131228/13503125/c3076f0e-e18f-11e5-8e3f-6cf5759c968a.png)
This is a unit built from capital, with two Great Writings themed in the Royal Library:
![8930_2016-03-03_00008](https://cloud.githubusercontent.com/assets/1131228/13503130/c891495e-e18f-11e5-8a55-ec82689e9529.png)
So not only it doesn't work in any city, but also gives more than 5 xp per work.

**Comment by LoneGazebo** [comment]
It doesn't work, but it gives more than 5xp? That doesn't make sense.

**Comment by Radost** [comment]
It only works in the city where the UB was build and gives more than 5 xp. Because 15+2*5≠85

**Comment by Edaka** [comment]
Yep, it seems to be backwards at the moment: instead of getting +5 xp per GW in all cities, you get +5 xp per city with a GW in it. For example, if I have 3 cities and one GW in my capital, any unit trained there will receive 5*3 additional exp, but units in other cities will receive nothing in addition.

**Comment by LoneGazebo** [comment]
I see the goof! Fixed. I think it was working for me because GWs were distributed such that the function was working as it should, but only for that test. :dancer:
