### ISSUE TITLE
Some typos (3/1 beta)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#1361]
**1.Amphitheater/Acropolis**

> Amphitheater/Acropolis: removed 1 per culture...

Their per-citizen culture descriptions need to be deleted.

Related files:

- (2) Community Balance Patch\Balance Changes\Leaders\Vanilla\UBBuildings.xml (Line: 389)
- (6a) Community Balance Patch - Compatibility Files (EUI)\MoreLuxuries\MoreLuxuries.sql (Line: 38, 42)
- (6b) Community Balance Patch - Compatibility Files (No-EUI)\MoreLuxuries\MoreLuxuries.sql (Line: 38, 42)

**2.Roman Forum has different social policy requirements.**

Related files:
- (6a) Community Balance Patch - Compatibility Files (**EUI**)\CSD\CSDCompatibility.sql (Line: 367)
`UPDATE Buildings SET NumPoliciesNeeded = '5' WHERE Type = 'BUILDING_FORUM';`
- (6b) Community Balance Patch - Compatibility Files (**No-EUI)**\CSD\CSDCompatibility.sql (Line: 367)
`UPDATE Buildings SET NumPoliciesNeeded = '4' WHERE Type = 'BUILDING_FORUM';`

**3.UniqueUnits.sql contains UA info.**

Although this is not a problem, I let you know just in case.

Related files:
- (2) Community Balance Patch\Balance Changes\Units\UniqueUnits.sql

Portugal (Line: 749 - 751)
Venice (Line: 854 - 856)

Thank you for the great update!

**Comment by LoneGazebo** [comment]
Fixed! Thanks.
