### ISSUE TITLE
DLL compile

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1363]
![dll](https://cloud.githubusercontent.com/assets/14372214/13501772/9083920e-e12d-11e5-8f98-5bb696ee490a.jpg)
Is that supposed to be like that? This is the master repository.

notice how anything with #if defined (MOD_BALANCE....) is grey out.

**Comment by LoneGazebo** [comment]
Yep, the lua files always do that. Dunno why.

**Comment by ilteroi** [comment]
the lua adapter classes are in a subdirectory ... it seems intellisense has a problem with the include path.

if you put #include "../CvGameCoreDLLPCH.h" then it works

**Comment by LoneGazebo** [comment]
Oh, duh, that makes total sense. I'll add that change to the master file.

**Comment by Iamblichos** [comment]
Yeah but then it won't compile...>Lua\CvLuaCity.cpp(16): warning C4627: '#include "../CvInternalGameCoreUtils.h"': skipped when looking for precompiled header use
1>          Add directive to 'CvGameCoreDLLPCH.h' or rebuild precompiled header

**Comment by Iamblichos** [comment]
When I change all the lua .cpp's to #include "../CvGameCoreDLLPCH.h": I get this:

1>Lua\CvLuaArea.cpp(9): warning C4627: '#include "../CvGameCoreDLLPCH.h"': skipped when looking for precompiled header use
1>          Add directive to 'CvGameCoreDLLPCH.h' or rebuild precompiled header
1>Lua\CvLuaArea.cpp(10): warning C4627: '#include "CvLuaSupport.h"': skipped when looking for precompiled header use
1>          Add directive to 'CvGameCoreDLLPCH.h' or rebuild precompiled header
1>Lua\CvLuaArea.cpp(11): warning C4627: '#include "CvLuaArea.h"': skipped when looking for precompiled header use
1>          Add directive to 'CvGameCoreDLLPCH.h' or rebuild precompiled header
1>Lua\CvLuaArea.cpp(12): warning C4627: '#include "CvLuaCity.h"': skipped when looking for precompiled header use
1>          Add directive to 'CvGameCoreDLLPCH.h' or rebuild precompiled header
1>Lua\CvLuaArea.cpp(336): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "CvGameCoreDLLPCH.h"' to your source?

and then ad nauseum for the rest.

**Comment by ilteroi** [comment]
oops. i just checked the intellisense. didn't actually try compiling.

might need to add the Expansion2 folder to the project includes then

**Comment by LoneGazebo** [comment]
Lemme know if you get this sorted. :)

**Comment by ilteroi** [comment]
ok. never turn down a challenge!

it seems the problem is due to the fact that the include in question is the precompiled header file, which is somehow special. so the added ../ does not work for the compiler, although it does for intellisense.

you can include both "CvGameCoreDLLPCH.h" and "../CvGameCoreDLLPCH.h", which looks ugly, or you can include "../CustomMods.h" separately to get the defines right.

**Comment by Iamblichos** [comment]
How about just include all of 'em? :+1:

**Comment by Iamblichos** [comment]
I think this corrected some build issues for me....I had some strange things happening on EUI about what resources a civ had (on the right hand leader column). I'm not sure those lua's were working correctly.

**Comment by ilteroi** [comment]
nope

**Comment by LoneGazebo** [comment]
Nor I.

**Comment by Iamblichos** [comment]
I got something screwed up somewhere....grrrrrrr

**Comment by Iamblichos** [comment]
I fixed it....I have a specific great admiral that can build a sea fortress...in CvHomelandAI::PlotAdmiralMoves() I was iterating over all the naval resource targets and then seeing if admiral could build any of them and then reference him over to PlotWorkerSeaMoves...unfortunately the way I wrote it, it also gifted every single resource in the game (because I was iterating over all possible naval targets) when the player admiral was at war and then routed into ExecuteAdmiralMoves().....just needed to do the check for pUnit->getUnitInfo().GetUnitAIType(UNITAI_WORKER_SEA) and then send it over to PlotWorkerSeaMoves().

**Comment by J-d-H** [comment]
you could add a new CvGameCoreDLLPCH.h with the lua directory with the following content:
`#include "../CvGameCoreDLLPCH.h"`
