### ISSUE TITLE
invalid deal values passed from lua

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1366]
![image](https://cloud.githubusercontent.com/assets/1358966/13510379/7f6e6c4c-e190-11e5-9568-90865ea4c341.png)

look at the auto watches. don't know where this is coming from ...

**Comment by LoneGazebo** [comment]
Is your DLL optimized? Sometimes that'll throw back bad watch values.

Also, are they showing up in the DiplomacyAIMessages log as bad deals?

**Comment by ilteroi** [comment]
sorry, didn't keep the log.

was a single event, first time i saw this. debug build. in fact i only noticed because of a "smaller type" exception when the 32 bit deal value was stored in a 16 bit array. quite an interesting design there ;)
