### ISSUE TITLE
happiness graph is broken in infoaddict

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1367]
first time that has happened, all others are still fine. it shows only the human player.

![image](https://cloud.githubusercontent.com/assets/1358966/13512601/f220400c-e19b-11e5-9d23-7fe44dee5c72.png)

**Comment by LoneGazebo** [comment]
Getting a lua error?

**Comment by Radost** [comment]
Speaking of happiness graph:
![8930_2016-03-03_00002](https://cloud.githubusercontent.com/assets/1131228/13519137/825f4b72-e1f6-11e5-84f4-55b87109973e.png)

**Comment by ilteroi** [comment]
yep. seems that CvPlayer::GetExcessHappiness() const always returns zero for the AI players.

digging deeper, CvPlayer::CalculateNetHappiness() does nothing when
```
GC.getGame().getActivePlayer() != GetID()
```

this line was last changed by commit

SHA-1: 22d34527faf908426a0e367f05c4505ea8b1ed4e

* 2/29 beta

Includes latest C4DF from Putmalk

**Comment by ilteroi** [comment]
you gotta love git blame :)

removing it now, but what was it supposed to achieve?

**Comment by LoneGazebo** [comment]
I'm working on all that. It was a MP fix that isn't working.
