### ISSUE TITLE
ships can heal outside of owned territory

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1368]
it didn't use to be that way ... or did it?

**Comment by LoneGazebo** [comment]
No, unless they have the Grand Canal or the promotion that allows it.

G

**Comment by ilteroi** [comment]
no, none of the above.

took a look into the code: DoUnitReset() does not call canHeal() ... and that's the only place where isHealOutsideFriendly() is checked.

did somebody change this recently?

**Comment by LoneGazebo** [comment]
Haha. Well at least we know. :)

**Comment by ilteroi** [comment]
should be fixed.

by the way, you had an integer overflow in your now worker plot evaluation. i reduces some of the multipliers to make sure it doesn't happen any more ...

**Comment by LoneGazebo** [comment]
Cool. Thanks!
