### ISSUE TITLE
isn't it weird that an armored car is a ranged unit?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1369]
enough said

**Comment by El-SiD** [comment]
maybe better call it self-propelled gun ?

**Comment by LoneGazebo** [comment]
I guess, but it is part of our mounted ranged line.

**Comment by ilteroi** [comment]
thanks to wikipedia, now i know that cavalry was indeed replaced by armored cars. the name irritated me a bit, but i guess i'll get used to it

**Comment by LoneGazebo** [comment]
Haha, yep. Not ideal, but 'shoot and scoot' was the preferred tactic for armored cars, which is what our little armored car is designed to do. :)
