### ISSUE TITLE
Ice water tiles have yields

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1370]
I remember ilteroi mentioning this a long time ago in #988 . Seems to be back again.

Heck, it's been a while (:

**Comment by LoneGazebo** [comment]
It's because of the water, and the fact that they're features. I can add an exception.

**Comment by Edaka** [comment]
I'd personally like to see one, plain ice yielding up to 4 food (among other yields) is a little silly.

**Comment by ilteroi** [comment]
i think we never got around to fixing it? anyway, problem is impassable tiles don't have yields but ice inside your border becomes passable. i think we need to set the ice feature to zero yield + terrain override.

**Comment by LoneGazebo** [comment]
Yep.

**Comment by Iamblichos** [comment]
Isn't it realistic that people fish in ice though?

**Comment by Edaka** [comment]
Perhaps, but then other yields like gold make less sense - no good trade routes over ice! Anyway, I personally dislike the fact that ice makes no difference. If we want it to have yields, then it probably ought to have more distinct ones.

**Comment by Iamblichos** [comment]
How about Feature yield -1 Food for ice.
