### ISSUE TITLE
Unable to buy ships with faith

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1372]
It seems that ship units are the only ones unaffected by the Zealotry belief. Land and air units don't have that issue.

**Comment by LoneGazebo** [comment]
This is by design.

**Comment by Edaka** [comment]
Oh, okay. May I ask why, though? I initially suspected that it's intended, but changed my mind upon finding out that planes can be bought with faith.

**Comment by LoneGazebo** [comment]
I'unno. Firaxis design? I mean we could allow it. I've considered taking away planes. But I think it is funny, so it stays for now.

**Comment by Edaka** [comment]
Heh, maybe. By the way, any chance the faith costs around the late game could be lowered across the board? Units of the information era all costing around 6 - 8 thousands faith is a little too harsh, imo.

**Comment by LoneGazebo** [comment]
That's an upcoming change, yep. I'm already on it.

**Comment by Edaka** [comment]
Cool! (:

**Comment by Radost** [comment]
About faith purchases, #323 says Explorers are "naval" units but can be purchased with faith through Zealotry.
