### ISSUE TITLE
Council's interaction with pioneer/colonist founded cities & scaling 

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1373]
1. The council isn't pre-built in pioneer/colonist cities, even though the library is. I don't suppose including the council would be a bad idea.

2. Does it scale? I really don't know, couldn't figure it out since that science on completion doesn't have a world popup above the cities. Saw somebody on the forum mentioning this. I'm not sure it should, but I also don't see why it shouldn't. Right now, with the fact that it doesn't come pre-built past settlers, there's no reason to build it after Renaissance. I suppose it's actually fitting flavor-wise, but at the same time it's weird to have that dead weight in your building possibility list.

**Comment by LoneGazebo** [comment]
I'll add the council. It scales with gamespeed, but not era. That's by design.

G
