### ISSUE TITLE
HappinessPerGarrison

### ISSUE THREAD

**Issue by Pusperk** [LoneGazebo/Community-Patch-DLL#1374]
In last build me not to work HappinessPerGarrison right. I try debugging code and in CvCity row 
`int iHappinessPerGarrison = kPlayer.GetHappinessPerGarrisonedUnit();`
visual studio show me 
`kPlayer.GetHappinessPerGarrisonedUnit()0x53ad7230 CvImprovementEntry::GetImprovementUsage(void)`
and in function` int CvPlayer::GetHappinessPerGarrisonedUnit() const` can't set breakpoint.
Has similar problem with HappinessPerGarrison somebody else?

**Comment by Pusperk** [comment]
I solve problem bad calculation HappinessPerGarrison (last build change column in database IncreasedQuestInfluence on IncreasedQuestRewards. In my mod I had not change it.)
Still I have problem with debugging function GetHappinessPerGarrisonedUnit(). When I try set breakpoint in this function this brekpoint is redirect on another function.

**Comment by LoneGazebo** [comment]
If the DLL is fully optimized while debugging, this can happen.

G

**Comment by Pusperk** [comment]
Finally I found it. Problem was from too many changes from last build. I use clean CP but modify CBP (without new happy system and a few own changes include lua changes) and I did mistake at merge CBP (movement definition column database table from CBP to CP and rename one column).
Interesting is that game run normally and that is not work right, I found when I debugging something else. Sorry you can close it.

**Comment by LoneGazebo** [comment]
Glad you found it!
