### ISSUE TITLE
"We have diverging social policies"

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1376]
It seems the diplomatic modifier is acting a little wonky currently. You can see here that I (Catherine) and Gajah have practically identical policy choices, but the negative modifier is in place.
![2016-03-02_00002](https://cloud.githubusercontent.com/assets/12978597/13536096/a6bfc622-e246-11e5-9775-4498d6309b12.jpg)
![2016-03-02_00003](https://cloud.githubusercontent.com/assets/12978597/13536098/a8d28972-e246-11e5-8a1b-3f0565cae6ad.jpg)

Another one: we have nearly (almost) identical policy choices with Alex - the only difference I can tell here is me having a little rationalism and different ideologies, though they don't count for that diplomodifier, do they?
![2016-03-04_00001](https://cloud.githubusercontent.com/assets/12978597/13536051/5f936c18-e246-11e5-8d64-6435c062587b.jpg)
![2016-03-04_00012](https://cloud.githubusercontent.com/assets/12978597/13536056/621381bc-e246-11e5-9994-10232d39d1e9.jpg)

**Comment by LoneGazebo** [comment]
Yeah, I had max/min set wrong. It'll be fixed in upcoming.
