### ISSUE TITLE
Notre Dame theming

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1377]
The tooltip says that the two works should be created by players other than the owner (of the Notre Dame, I suppose). However, here I'm able to get the theming despite one of the works being created by myself. (Disregard the fact that the last screenshot shows no bonus for theming, that's by accident :P).
![2016-03-04_00008](https://cloud.githubusercontent.com/assets/12978597/13536168/1c396a8e-e247-11e5-8858-a553e4af6838.jpg)
![2016-03-04_00010](https://cloud.githubusercontent.com/assets/12978597/13536170/1d81f24e-e247-11e5-8c91-ceff85153911.jpg)
![2016-03-04_00009](https://cloud.githubusercontent.com/assets/12978597/13536171/1e72c872-e247-11e5-8861-98c49e2fd553.jpg)

**Comment by LoneGazebo** [comment]
Probably just missing the theming tag for it.

**Comment by LoneGazebo** [comment]
Yep, fixing.
