### ISSUE TITLE
range 1 units

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1381]
i like the basic idea. but

1. the chariot archer cannot move after attacking. intended?

2. in general, range 1 is not so nice for the AI, because those units now compete with melee units for plots. in some places (executeAttack) it should work but in others (hedgehog etc) it won't.

3. i've been meaning to rewrite the formation logic anyway. one more reason to do that now.

**Comment by LoneGazebo** [comment]
We'll keep it for an iteration or two, but yeah, it's definitely an AI-strain.
