### ISSUE TITLE
siege tower bonus does not work

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1385]
![image](https://cloud.githubusercontent.com/assets/1358966/13554290/2dc5fd22-e3a4-11e5-9ef9-e5ce15bff9b5.png)

note this happens only when the tower is directly adjacent to the city. if i move it away one plot, i get the 20% as expected

**Comment by LoneGazebo** [comment]
It's fixed for current version, I'll upload soon.
G
