### ISSUE TITLE
lots of disbanded workers in homeland AI log

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1386]
is that normal?

**Comment by ilteroi** [comment]
also, assyria prioritizes siege towers over building settlers. not very smart.

**Comment by LoneGazebo** [comment]
I'm not sure re: disbanding - I think the last time that was edited was months ago.

Assyria can only build two siege towers, but I may need to lower the modifiers for them. We'll see.

Also, latest 3/6 version has a lot of new caching and optimizations. A second pair of eyes on my caching work would be appreciated. UpdateCityYields is the function in CvCity.cpp.

Also, if you have a moment, take a look at DoReallocateCitizens in CvCityCitizens and see if my new check function makes sense.

Cheers,
G

**Comment by LoneGazebo** [comment]
I meant to ask - Whoward recently added a bugfix for 'radaring' 

https://www.reddit.com/r/nqmod/comments/34reu9/how_to_remove_radaring/

Is this something we can do in our aStar?

**Comment by ilteroi** [comment]
hmm.

he has a point about getBestDefender(). i updated it.

the same issue also affects the various CvPlot::isVisible*() functions.

the pathfinder is completely different now, it uses the isVisibleEnemyDefender() function, so it should be fine.

**Comment by LoneGazebo** [comment]
Cool, thanks. Seemed like a basic fix, figured you'd know if it was valid or not. :)

**Comment by ilteroi** [comment]
yeah, i'm not 100% sure because honestly it seems like a pretty big issue which should be glaringly obvious. also, there's a thing called getInvisibleVisibilityCount() which maybe catches the case. but with a name like that, who's to know.

anyway, seems like a harmless change. pushed my latest changes in case you do another hotfix soon.

**Comment by LoneGazebo** [comment]
Yep, got em. That's one heck of a tactical rewrite.

I'm also integrated Whoward's v74 which, among other things, makes experience a 100s value. Also adds a few events here and there, but not too much. Hopefully nothing breaks.

**Comment by ilteroi** [comment]
well, these were only the harmless changes .. i got plans, man :)

re: UpdateCityYields / DoReallocateCitizens - will give it a look

**Comment by LoneGazebo** [comment]
Oh, hey, another point. Users are reporting that trade units 'disappear' after going to/from cities. Doesn't seem to happen every time. I'll try to get you a save.
