### ISSUE TITLE
Faith and Culture Yields

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1388]
I think something has, indeed, gone a bit awry with your changes to Yield calculation. Faith and Culture no longer register as a part of city:GetYieldRate() (always returning 0), and GetYieldRateTimes100 returns the raw value, not multiplied by 100 (i.e. if I have 1 Culture, it returns 1 Culture). Inversely, Food, Science, Gold, etc. return the value x 100.

EDIT: Further investigation reveals some odd results. The GetYieldRateTimes100 only returns the raw value when called through Firetuner. In-game, it'll return an inconsistent number, for instance, 400 when the city's Culture output is 2.

GetBaseYieldRate() appears to work correctly, however, that obviously doesn't accomplish the same thing as GetYieldRate().

**Comment by LoneGazebo** [comment]
It's the caching issue. As I noted, it is a WIP, so there's some kinks to work out.

G

**Comment by JFDaly** [comment]
No problem.

**Comment by LoneGazebo** [comment]
Do any of your yields use single digits, or are they calc'd by the 100s?

**Comment by JFDaly** [comment]
They're all single digits.

**Comment by LoneGazebo** [comment]
Alright, fixed. I wasn't storing off culture/faith as 100s values, so they were being divided by 100 (thus returning zero).
