### ISSUE TITLE
Kris swordsman + logistics + recruitment

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#139]
Kris swordsman with recruitment promotion does not heal 20 HP after killing a barbarian ( bonus privided by logistics ).

**Comment by LoneGazebo** [comment]
The two abilities overlap, as they use the same function. This is an unavoidable side-effect.

**Comment by qqqbbb** [comment]
Maybe edit recruitment to heal kris swordsman after killing barbarians?
