### ISSUE TITLE
AI proposes trade deals too often

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1390]
Not a bug, but I figure I'd post here. I usually play on standard/small maps, but this time around tried out a large one. As soon as the congress was founded and everybody met everybody else, the trade proposal spam began. Literally almost every one of the 9 AIs would try to buy the same resource/open borders/etc. from me all on the same turn. They kept doing that until they cooled down a handful of turns later. The spam was real.

However, this also happens outside of the founding of the WC. For example, every time you improve a luxury tile and get the resource, it is safe to assume that you will be contacted by every single AI that's not hostile, or doesn't have that resource, with a deal. Needless to say, I (and I assume that most players do) refuse all the deals because you never know who'll to offer the most until you've clicked through all of those deals.

Is there any way a limit on how many deal proposals a player can receive in one turn could be set? Or perhaps a cooldown on how often each AI can propose deals (as right now they don't seem to hesitate to sometimes propose different deals twice during two consequent turns)? If that's too bothersome or unrealistic, I'd suggest lowering the AI's eagerness to trade a little. 

I really like what has been done to some of the AI diplomatic responses (e.g., reactions supporting/failing WC proposals, etc.) - they seem to only come once at a time now with significant spaces inbetween, so I wonder if something similar is possible for deals.

**Comment by LoneGazebo** [comment]
There's a 20 turn delay for offers of a certain type. Any more than that and I feel that the AI will be compromised.

**Comment by Edaka** [comment]
I see, that makes sense. I aassume that the cooldown is applied to each AI civ separately, right? That means that deals can come in huge waves as I described above - something (WC foundation, gaining access to a resource, etc.) can trigger all the AIs to propose at once, on the same turn. In practice those triggers can be many and bothersome, especially on larger maps.

I was thinking if it was technically possible to set a limit as to how many deals can a human receive from AI civs during one turn. No more than two deal proposals at once, for example. Hopefully, that wouldn't hinder AI too much.

**Comment by LoneGazebo** [comment]
Alright, I've added a global timer, but reduced the base rate. So messages more often in potential, but if one AI contacts you, the others will wait.

**Comment by Edaka** [comment]
I think that should be a major improvement, thanks!
