### ISSUE TITLE
Plots and Features

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1395]
In a recent update, you stated that you'd changed how some of the yields for plots register. This was fantastically convient and probably improved performance a tonne in Health. But of these, Features and Resources went somewhat unsupported, and this has caused some inconsistencies for me.

Basically, city:GetBaseYieldRate() will return the yield value of plots if a Building changes the yield of a Feature, but not for Beliefs, nor for nature Feature yields. However, plot:GetYield() (or whatever it is) will still return 0 in all cases. This means I have some problems with accurately reporting Health from Jungle. 

As an example, my Herbalist gives +1 Health on Jungle. I artificially tell the plot that it has Health on it, because it doesn't recognise it otherwise. But the city, on the other hand, does recognise that +1 Health, resulting in a report of a higher total health (+2 for every Jungle terrain) than there really is.

Although I can work around this by subtracting the artificial Health from the city's total Health, I'm hoping for a cleaner solution. So would it be possible to extend whatever you did to make terrains, rivers, and improvements register new yields naturally to Features and Resources? Resources are less important than Features, if both are too much extra work.

**Comment by LoneGazebo** [comment]
I'll work on it, yep!

**Comment by JFDaly** [comment]
Awesome, thanks much.
