### ISSUE TITLE
CTD on World Congress results

### ISSUE THREAD

**Issue by valentin-turcu** [LoneGazebo/Community-Patch-DLL#1398]
Around the ~600th turn on my Marathon game, after the first World Congress was successfully convened and voted on, the game crashes right when I try to click on the results popup. 
Mods: 
CBP Full Package (Installer with EUI) 12-18 version
Religion - Improved Customization (v 15)
Strange Religions (v 9)
Really Advanced Setup (v 15)
Ingame Editor (v 39)

I've attached the dump file generated on crash as well as the save game. But since GitHub doesn't allow uploads of zips despite what it says, I've changed the extensions of the attached file to .jpeg. If that doesn't work, I'll upload them somewhere else.
 
Dump (change extension to .dmp)
![cvminidump rename](https://cloud.githubusercontent.com/assets/6671776/13583164/2e6c6ee8-e4b0-11e5-9695-499d7122e172.jpeg)

Save game (change extension to Civ5Save):
![autosave_0540 ad-1200 rename](https://cloud.githubusercontent.com/assets/6671776/13583230/77be92c4-e4b0-11e5-9733-6998df15acd3.jpeg)

There was an extremely similar bug last year in March, it ruined another one of my saves back then. Hopefully there's a solution.

**Comment by LoneGazebo** [comment]
Breaks to lua, unfortunately. It's very difficult for me to debug crashes that have mods outside of the standard CBP set included in them.

**Comment by valentin-turcu** [comment]
Would it help if I attached an archive with said mods?

**Comment by LoneGazebo** [comment]
No, because breaking to disassembly (lua) means that the crash is occurring from a mod conflict.

**Comment by valentin-turcu** [comment]
I'm only using the 4 mods I mentioned, outside of the CBP package.

Strange Religions doesn't modify the beliefs, merely adds many custom icons
for when founding a religion.
Really Advanced Setup operates only at the map creation stage, doesn't
impact the game at all after that.
Ingame Editor doesn't change anything in the files, shouldn't conflict with
any mod.

The only remaining mod is Religion - Improved Customization, which adds the
bonus belief to all civs instead of just Byzantium. Could this be the
culprit?

**Comment by LoneGazebo** [comment]
Definitely possible, yes.

**Comment by Iamblichos** [comment]
Haven't seen the mod for religion customization, but that should only be a table edit. I wonder if the break on LUA isn't caused by EUI sometimes.

**Comment by valentin-turcu** [comment]
@lamblichos
Seeing that I've been using these same mods with past versions of the CBP
full suite successfully (no conflicts or CTDs) I would guess you might be
on to something.

**Comment by Iamblichos** [comment]
You may or may not not hit the CTD. If the culprit is what I think it is, it's hard to reproduce. EUI CTD's are not game breaking ones.

**Comment by valentin-turcu** [comment]
Well, I passed the World Congress successfully. Didn't CTD again.

Don't know if it was because of the mods I deactivated were causing a
conflict or the specific conditions simply didn't occur in a new game.

Anyway, since there's no more feedback that I can give at this point, I'd
say you can close the ticket.

**Comment by LoneGazebo** [comment]
Coolio.
