### ISSUE TITLE
Collection of issues from the forum since the 3/1 version

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1399]
As usual, most (if not all) of these you've already seen and probably adressed. Just in case it might serve as a safeguard, lest you miss any of the many reports.

1. Cavalry isn't affected by the Mongol UA.
2. Warriors coerced by the Huns' UA don't retain the Brute Force promotion.
3. God of Nature doesn't provide faith and culture for nearby mountains.
4. War Elephant has lower CS than Horsemen (I know you've seen it, but I'm enjoying making this list, so I'll leave this here anyway).
5. Units can't be given the command to heal if they have partly expended their movement points (was previously possible even though the unit wouldn't heal any hp that turn).
6. Skirmisher isn't unlocked at mathematics (when chariot archer gets obsolete).
7. Goddess of Springtime doesn't provide culture on tea tiles (might be affecting all plantations, though).
8. Epona, the Great Mare doesn't scale with era.
9. Statue of Zeus doesn't give a free forge (same as #1387 , I assume).
10. Cities founded by conquistadors don't receive a pre-built harbor if you don't have the tech for it (might be intentional).

These one I'll shamelessly copycat from Funak:
11. Hanse doesn't provide +2 raw culture.
12. Bazaar provides +1 raw faith.
13. Longhouse doesn't provide flat yields (culture, food).
14. Coffee House converts food into science like the Grocer used to.
15. Jelling Stones provide no yields at all (whatever that means).
13. Tabya doesn't provide culture to river tiles.

**Comment by LoneGazebo** [comment]
5 is intentional (it was a misleading button). Rest are either already fixed or I am looking at them now. Thanks!
