### ISSUE TITLE
Kris swordsman + recruitment

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#140]
Kris swordsman with recruitment promotion often heals 70 instead of 100 HP after killing an enemy unit.

**Comment by LoneGazebo** [comment]
I'm not sure I understand - the unit can only heal up to its maximum, whether that be 100hp or 70hp.

**Comment by qqqbbb** [comment]
Sometimes they don't heal to their maximum (which is 100 HP). Usually happens when they defend.

**Comment by qqqbbb** [comment]
I checked CIV5UnitPromotions_Expansion2.xml and this promotion actually heals 50 HP not 100 ( I got 70 because of logistics). So the description should be updated.

**Comment by LoneGazebo** [comment]
Ah - I'll fix the description.
