### ISSUE TITLE
Pointers pointing at the wrong thing... am I going mad?

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1400]
@ilteroi, I'm going insane. Debugging some UI stuff and I've encountered a situation where a lua call in luacity (getcultureratemodifier) is, for some unknown reason, pointing to GetCityPopulation() in the CvSmallAwardInfo!

What the heck? What have I/we done?
G

**Comment by LoneGazebo** [comment]
The point only happens if you are hooked into the game and following the stack. It is very clearly grabbing m_iCityPopulation and passing it through.

**Comment by ilteroi** [comment]
are you sure it's not just a debugger problem? sometimes with inlined functions i see garbage too.

could also be non-matching header files (though we don't link multiple libs here).

i'd turn off inlining (makes the game a bit slower) and rebuild all. then see if the problem persists.

in the worst case it's a problem with all the #ifdefs

**Comment by LoneGazebo** [comment]
Its definitely grabbing the wrong value. I think some changes were made to the header values , but I didn't check the merge. Possibly the culprit?

**Comment by LoneGazebo** [comment]
Also, just to note, I don't think that the city connection system is working properly for askia and carthage. The IsRouteToCapitalConnected() function isn't returning true for them until you have 'the wheel' researched, which (I thought) we were doing away with as a rule.

**Comment by LoneGazebo** [comment]
Nevermind re: routes, I've fixed.

**Comment by LoneGazebo** [comment]
It's also happening in other places, whether or not I have inline turned on.

**Comment by ilteroi** [comment]
running out of ideas then.

for me it works though. tried only lGetCultureRateModifier() so far, but it maps to m_iCultureRateModifier as it should.

**Comment by LoneGazebo** [comment]
Maps in the DLL, but in-game, when hooked into the DLL (and the lua itself), it isn't grabbing the data. You can test this by giving a city an Opera House with CBP, and then look at the tooltip for culture. No % Culture yield indicated, and if you do a stack trace, it grabs the small awards info.

**Comment by LoneGazebo** [comment]
What it grabs seems to actually be somewhat random. And it isn't just cultureratemodifier either. Trying to set a break point inside of getcultureratemodifier, for example, will throw the break point somewhere else entirely. I'm afraid this might be a memory issue, and that's really not good at all.

**Comment by ilteroi** [comment]
well, for me it works. i put a breakpoint inside lGetCultureRateModifier() and it did exactly what it is supposed to.

also tooltip looks good:

![image](https://cloud.githubusercontent.com/assets/1358966/13618959/048de034-e587-11e5-8df7-3b19a5b93899.png)

i'm still on 3/1 though. so either it's a recent change on your end, or something is broken with your project setup.

**Comment by LoneGazebo** [comment]
Did you hover over the culture tooltip on the left side?

**Comment by LoneGazebo** [comment]
While the DLL is attached to the game, try putting a break point inside of getcultureratemodifier in CvCity. For me, applying the break point immediately jumps the breakpoint elsewhere in the DLL.

**Comment by LoneGazebo** [comment]
For the record, my project setup is identical to yours (i.e. the vcproject info et. al. is merged with yours so that they're the same).

**Comment by LoneGazebo** [comment]
No ideas here. Maybe it is just the PDB acting up, or perhaps I'm just a madman. Anyways, I guess if numbers are coming out correct, the walker doesn't have to be correct.
