### ISSUE TITLE
Minor mistake in MOD_PROCESS_STOCKPILE

### ISSUE THREAD

**Issue by Pusperk** [LoneGazebo/Community-Patch-DLL#1401]
Build 1.3. Minor mistake in MOD_PROCESS_STOCKPILE.
Function int CvCity::getYieldRateTimes100(YieldTypes eIndex, bool bIgnoreTrade) const
In case delete #define MOD_PROCESS_STOCKPILE iYield will not be exist.
Miss #else and code for it

```
#if defined(MOD_PROCESS_STOCKPILE)  
	int iYield = getBasicYieldRateTimes100(eIndex, bIgnoreTrade) + iProcessYield;
//HERE MISS #else and code from Vanilla

#endif
	return iYield;
```

#if defined(MOD_PROCESS_STOCKPILE or MOD_BALANCE_CORE)  //Miss this before function
Function int CvCity::getBasicYieldRateTimes100(YieldTypes eIndex, bool bIgnoreTrade) const

In function ::getBasicYieldRateTimes100 delete this code (iProcessYield do not exist in this function)
```
#if !defined(MOD_PROCESS_STOCKPILE)
	iModifiedYield += iProcessYield;
#endif
```
Check call this function getBasicYieldRateTimes100 in code.

**Comment by Pusperk** [comment]
My mistake. In my code is bad placed #endif. 
Still remain problem in call function getBasicYieldRateTimes100.
In case delete #define MOD_PROCESS_STOCKPILE do not exist getBasicYieldRateTimes100.
Function int CvCity::GetBaseJONSCulturePerTurn() const and int CvCity::GetFaithPerTurn() const use it.

```
#if defined(MOD_API_UNIFIED_YIELDS)
	// Process production into culture
	iCulturePerTurn += (getBasicYieldRateTimes100(YIELD_PRODUCTION, false) / 100) * getProductionToYieldModifier(YIELD_CULTURE) / 100;

	// Culture from having trade routes
	iCulturePerTurn += GET_PLAYER(m_eOwner).GetTrade()->GetTradeValuesAtCityTimes100(this, YIELD_CULTURE) / 100;
#endif
```

**Comment by LoneGazebo** [comment]
I'm not exactly sure I understand.

**Comment by Pusperk** [comment]
Delete #MOD_PROCES_STOCKPILE and try compile dll. Compiler write error and all will be evident.

**Comment by LoneGazebo** [comment]
Why would I ever delete that, though? There's no need to, as it only triggers if set to 1 in the DLL.

G

**Comment by Pusperk** [comment]
When i never delete definition #MOD_PROCES_STOCKPILE then code in function getBasicYieldRateTimes100 that confuse me is useless
```
#if !defined(MOD_PROCESS_STOCKPILE)
    iModifiedYield += iProcessYield;   //iProcessYield - is not defined in function
#endif
```
Close it.  It has any effect on current build dll
