### ISSUE TITLE
Tourism reformation belief not giving tourism

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#1405]
Neither the buildings bought with faith nor the hermitage for the extra tourism and culture... essentially a useless belief, but still, we are in beta.

I LOVE the new science system, although I would prefer to shift from buildings that convert a % of yields into science to more science on the map. Granaries could give +1 science to wheat, etc, making the choice of which tiles to use more important. Sorry for not posting in the forums I cannot log in since last year.

**Comment by LoneGazebo** [comment]
Yep, noticed that yesterday, actually! Fixed in current beta.

I agree re: tile yields, though I want to let the current setup simmer for a bit before we move to next step.

re forums, you should make a dummy account and message the mods, they can reset your password for you.

G

**Comment by AnastaseAlex** [comment]
Huh. I am playing the current beta, and it still is not working :(

Glad to see you are of the same mind. At the moment the X% of yields buildings are auto-build either way, but it would be interesting to have a dichotomy of what buildings give what extra yields to different resources. Remains to be seen.

Keep up the good work G! I love what the game is shaping to be.

**Comment by LoneGazebo** [comment]
Wait, which thing isn't working? I thought you were talking about aesthetics.

**Comment by AnastaseAlex** [comment]
Reloaded, tried another reformation belief (to the glory of god) does not work either.

**Comment by AnastaseAlex** [comment]
Seems like way of transcendance does not work either :s

**Comment by LoneGazebo** [comment]
Yeah, it's all in need of a fix. No worries, I know why. There's a bigger issue, though...
