### ISSUE TITLE
A couple of Arabian quirks

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1409]
1. Bazaar doesn't seem to have +1 faith mentioned in the changelog.
![2016-03-08_00001](https://cloud.githubusercontent.com/assets/12978597/13619541/42af1116-e592-11e5-8a9f-41464fe28db2.jpg)

2. The special historic event notification mentions outdated +2 science.
![2016-03-08_00002](https://cloud.githubusercontent.com/assets/12978597/13619546/4470da5c-e592-11e5-915e-68b53afc2e64.jpg)

**Comment by LoneGazebo** [comment]
Fixed!
