### ISSUE TITLE
Amphibious promotion

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#141]
Units with amphibious promotion are supposed to move faster along rivers but they don't.

**Comment by LoneGazebo** [comment]
They should move a little faster - not substantially so, but marginally. I've tested this and it has worked in the past.

**Comment by qqqbbb** [comment]
It's useless if increase in movement speed is less than 50% since all melee units move only 2 tiles and mounted units can't get this promotion. I tested it and did not notice any difference even  when moving on railroads.
