### ISSUE TITLE
Barbarians vs cities issues (maybe?)

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1410]
Sorry in advance for not testing this one properly, as so far I only have unconfirmed suspicions that something might be wrong. Won't be able to test properly and contribute to bug hunting until a couple of days later, probably, therefore I've figured I'd post what I have on my hands right now.

There's something fishy going on with barbarians looting major civ cities. First of all, I've noticed a while ago that the looting doesn't always happen despite both barbarians and the city always taking damage should barbarians end their turn on an adjacent tile. Both parties will take damage, but no notificatioin for stolen food/production/etc. will appear (might be intentional).

Secondly, I think barbarian ships currently don't take damage when doing the described above. The city will lose its hp, but the barbarian ship won't (simply haven't tested land units). 

Thirdly, when some looting was finally performed by a barbarian ship, the city took damage twice. Might be the reason why Bismarck's coastal city was constantly in the red for a good dozen or another of turns.

I'm very uncertain about whether what I've seen so far were true occurences or illusions, so feel free to dismiss this in case what I've described is impossible.

**Comment by LoneGazebo** [comment]
Oh! There was a bug. You are not mad. Fixed.
