### ISSUE TITLE
Auto-Explore Woes

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1411]
Two reports of auto-explore breaking for players:

http://forums.civfanatics.com/showpost.php?p=14191873&postcount=4668

I can link the other if needed.
I'll try to get a save.

**Comment by ilteroi** [comment]
huh. will check. but no changes there lately.

anyway, what happened to the vanishing caravans?

and to your mystery pointers?

**Comment by AnastaseAlex** [comment]
It has been broken for at least 3 versions. Archeologists, Missionaries Diplomats and explorers at some points seem to consider there is no place to explore spread religion excavate or influence even when standing right next to one. Then two or three turns latter it it ok.

**Comment by LoneGazebo** [comment]
Mystery pointers remain mystery, but I fixed the in game display, so all's well that ends well. 

Caravans may still disappear, but I haven't seen a report on it from 3/8 yet.

**Comment by ilteroi** [comment]
indeed i found some oddities. fix is pushed.

**Comment by LoneGazebo** [comment]
Sounds good. I'll let the current 3/9 hotfix simmer for a bit, then move on. Not a huge issue (auto-explore).
