### ISSUE TITLE
Great Merchant/Engineer/Scientist/Artist/Musician/Writer Yields? (Request)

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1412]
Would it be possible to have the Great People points in yields for scenarios where you could do 1 great writer point for every 3 citizens?

Also has anyone ever tried out the Building_ScienceFromYield table adding science from science yield and see if it becomes recursive or not?

**Comment by LoneGazebo** [comment]
It would become recursive. 

Not sure I understand top point.

**Comment by TechpriestEnginseer** [comment]
Turn all Great People points into yields like how Great General Points and Great Admiral Points are yields.

**Comment by LoneGazebo** [comment]
Oh, gosh, it is possible, but I'm really reluctant to add any more yields to the yields table. Every new yield added results in many more CPU cycles for refreshing things.

**Comment by TechpriestEnginseer** [comment]
Would it be possible to make the <GreatPeopleRateChange> have stacking changes? As in multiple dummy buildings in the same cities to have the same effect?

**Comment by LoneGazebo** [comment]
Eh?

**Comment by TechpriestEnginseer** [comment]
I'm asking if dummy buildings have stacking "GreatPeopleRateChange" or Great People Points as in:

I have a dummy building that grants +1 great writer point. If LUA creates two dummy building in the same city, will the city be able to have +2 great writer points instead of +1 per turn?

**Comment by LoneGazebo** [comment]
As long as the buildings themselves don't overlap, yep.

**Comment by TechpriestEnginseer** [comment]
Overlap as in?

**Comment by LoneGazebo** [comment]
As in, as long as they aren't identical buildings. :)

**Comment by TechpriestEnginseer** [comment]
So, that's my feature request. Would it be possible to have two identical buildings have stacking bonuses? :)

**Comment by LoneGazebo** [comment]
They already do that.

**Comment by LoneGazebo** [comment]
I guess I just didn't understand what you meant, but you can assign multiple buildings flat 'GPP change' points just by assigning them a specialist type and then a GP change amount.
