### ISSUE TITLE
City Bombardment Issue

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1413]
According to Funak:

http://forums.civfanatics.com/showpost.php?p=14192362&postcount=77

**Comment by Edaka** [comment]
Yeah, undying garrisons were to be expected to cause some confusion. Although I can tell that as far as I've played, the garrisons stopped sharing damage with the city as they hit the 10 hp treshold. Didn't pay close attention to it, though.

**Comment by LoneGazebo** [comment]
Yeah, that's how it should work, and that's how I think it does work, but it isn't super clear, truth be told.

**Comment by ilteroi** [comment]
yeah, i replied to the comment, let's see how he takes the news

**Comment by LoneGazebo** [comment]
Doesn't seem to be popular. :) We may need to revert the change and just tell the AI not to move into an almost-dead city.

**Comment by ilteroi** [comment]
though i haven't tested it yet :)
