### ISSUE TITLE
God of Expanse does not scale anymore

### ISSUE THREAD

**Issue by Tascani** [LoneGazebo/Community-Patch-DLL#1414]
Full Release March 8th:
God of the Expanse faith gain was reduced from 25 to 20.
But it also does not scale with Era (anymore). I that intended?
If I remember correctly it did scale before that nerf.
So either I am simply mistaken, the non-scaling nerf isn't mentioned in the change log or its a bug. :)

**Comment by LoneGazebo** [comment]
It does not scale, and it isn't supposed to scale.
