### ISSUE TITLE
CS units don't heal

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1418]
Noticed a quirk with CSs' units that fortify outside their cities that happens during their turn. By the way unit animations play out, it looks that previously fortifie units de-fortify somehow without moving. I assume that because the unit icon (the one above the tile) changes from a shield (fortified state) to a round shape. Also, units like spearmen will lift break their defensive formation by lifting their spears (talking purely about visuals here). After that happens, units fortify back again, but don't heal for some reason.

It could be a specific case, as I've only seen it once - I was at war with a CS that had very little land around it (mostly water), so maybe the units were trying to go somewhere but couldn't, leading to that strange behaviour.

**Comment by LoneGazebo** [comment]
Not sure. Could just be a visual quirk.
