### ISSUE TITLE
AI still focus-fires badly

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1419]
Had an occurence while at war with a CS on an island. I had both land units (spearmen & a catapult) and ships (dromons & triremes) around the besieged city. The odd thing was that the city itself would always shoot at my spearmen, while the garrisoned composite archer inside would always shoot at my dromons and sometimes triremes. Sometimes if there were no ships nearby, the city would fire at one of my two spearmen, while the composite archer at the other one. The only time when that CS fired both shots at one unit was when one of my dromons lost enough hp to be killed in one turn - just when I got convinced that it's not able to do that. Maybe I just got played by the AI, hehe. Anyway, until the CS could do that, it avoided focus firing, which, needless to say, was beneficial to me.

Another thing: the whole time the siege was happening (10 turns at least) the CS never fired at my catapult. Possible due to the fact that it was one a hill while my other units didn't (therefore no defensive bonuses), so it could deal more damage to dromons/spearmen. As a siege unit, though, the catapult was the one to deal the most damage. I'm curious, does the AI prioritise attacking siege units more than others?

**Comment by LoneGazebo** [comment]
It prioritizes units that can capture the city.

**Comment by LoneGazebo** [comment]
Priority is assigned by target, not by source. Cities and units operate on the same target model, IIRC.

**Comment by Edaka** [comment]
I assume factors like damage output is taken into the assessment of priorities too, right? I'm a little curious as to how it works and why disharmonies like these happen. Too bad I can only leave it to the big man. (:

**Comment by LoneGazebo** [comment]
Correct.

**Comment by ilteroi** [comment]
haha. stealth fix. this change is probably in the latest beta. let's see if it makes a noticeable difference

**Comment by LoneGazebo** [comment]
Sneaky. Was it uploaded with your garrison change?
