### ISSUE TITLE
Cartographic commission 

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1420]
On the screenshots below you can see that two city states have given me the exploration quest. Each one points to a completely different place - one I've partially revealed and the other I haven't even been nearby. However, they both have the same completion rate (18%).

Might be the reason some people complained about the amounts of territory one has to explore to complete the quest. No wonder if all of them share the same territory (e.g. to complete one of the quests, you need to reveal both territories, including the one from that other quest).
![20160310162120_1](https://cloud.githubusercontent.com/assets/12978597/13673889/cf51e6dc-e6e3-11e5-9e26-e3bb883f1e4f.jpg)
![20160310162116_1](https://cloud.githubusercontent.com/assets/12978597/13673890/d151ea68-e6e3-11e5-8762-12f04ce40a22.jpg)

**Comment by LoneGazebo** [comment]
It is the same landmass, that's why you're seeing the same % for both.

**Comment by Edaka** [comment]
Oh, I get it now. Didn't expect those CS to want me to explore _that_ much. If I understand correctly, they will only ask to explore large landmasses like continents, no small islands or archipelagos... Or can they do that too?

**Comment by LoneGazebo** [comment]
They can ask you to explore anything. It's random.

**Comment by Edaka** [comment]
So the amount of territory they want you to explore is also random? Because this one seemed like a huge one, but that might be due to the large map size.

**Comment by LoneGazebo** [comment]
Well, they target an 'area' of the map, which is generally (but not always) an entire landmass. Depends on the map generator lua.

**Comment by Edaka** [comment]
Okay then. Hopefully, those desired territories to be explored aren't too enormous - I'm yet to complete one. Everything's as it should be, closing.
