### ISSUE TITLE
CS war with each other across the continent

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1421]
Not actually a bug - more of a question of adjustment, I think. The screenshow below depicts the quest where two CS at war with each other. I couldn't have taken it better because of just how far apart they were (they both have the little sword icons). If you look at the minimap, it's the one it the lower left corner of the map and the one just south from the Ottomans. I wonder what reasons for war they had to be ready to march that far! (Nobody marched anywhere, by the way, which isn't surprising).

Maybe the likeliness of that quest popping up could decrease with distance between the nearest CS, to the point of being minimal? It's the only extreme case I've seen so far, but It's not the first time a CS declares a war on another one much farther away than its closer neighbor, which I'd imagine should be the primary target.
![20160309135204_1](https://cloud.githubusercontent.com/assets/12978597/13674061/b2cea328-e6e4-11e5-8645-11875964523b.jpg)

**Comment by LoneGazebo** [comment]
It prioritizes the nearest CS, but some factors (like players being allied/friends with the CS) reduce the likelihood.

**Comment by Edaka** [comment]
Sometimes the nearest CS will be 5 tiles apart and sometimes - 30. The distance on the screenshot is far too long for a CS to want to cover on its warpath, realistically speaking, even if it was the nearest CS out there.

**Comment by LoneGazebo** [comment]
Right. Aberrations will happen when you code a function with exceptions. Since you are friends with the nearest CS, that CS isn't viable. I'd say 75% of wars like this break out between direct neighbors.

**Comment by LoneGazebo** [comment]
That's already included. They have to be less than 'distant' to apply. That one's considered 'far' in game terms.

G

**Comment by Edaka** [comment]
Heh, I find these terms entertaining. I suppose you've got it all covered, then. (:
