### ISSUE TITLE
Great people tile improvement yield discrepancy

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1422]
This one is a balance issue, but I don't feel like it's worth discussing on the forum. Well, I hope, rather (please have mercy if I'm deeply mistaken). (:

Anyway, is there a reason the manufactory is the only one to have only 4 base yields (4 production), while both the academy and the town are at 6 (6 science and 4 gold, 2 food, respectively)? Might be the reason the manufactory seems so underwhelming, but that might be just me. 

Furthermore, I think the academy is the only one to receive +3 yields from its tech scaling, while the others receive +2. I'm not sure if that's needed after the science rework, but we could also bring others to +3 instead of nerfing the academy. We could also leave it as is if that's fine, I guess, but I'll always have the itch because of the asymmetry.

Oh, by the way, it's worth to notice that the town's base yields can easily be brought up to 10 (not counting scalers). +1 gold and production for being on the road and just as much for having a caravan passing over it. Something to keep in mind.

**Comment by LoneGazebo** [comment]
Towns are really strong, yep. It is a balance issue, but I'll bring it up in the forums.

**Comment by Edaka** [comment]
Thinking it over, posting on the forum was a better idea, indeed. Sorry!

**Comment by LoneGazebo** [comment]
go for it
