### ISSUE TITLE
No XP

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1423]
Playing the latest full version, I noticed that my units don't gain XP any more, or at a greatly reduced rate. I have killed dozend of units, and my best unit has 14 XP.

**Comment by LoneGazebo** [comment]
Are you on 3/9 for the CP? The CP hotfix fixed that issue.

**Comment by LoneGazebo** [comment]
Savegame compatible.

**Comment by Der-Zorn-Gottes** [comment]
No, was 3/8. Didn't catch that there was an update. Thanks.
