### ISSUE TITLE
UI doesn't show converted yields

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1426]
![image](https://cloud.githubusercontent.com/assets/1358966/13686946/c228b456-e718-11e5-91c0-c56e20929629.png)

don't know if that's still present, i'm still on the 3/1 version, but the shrine e.g. doesn't show the science it generates.

**Comment by LoneGazebo** [comment]
City Yields = converted yields.

**Comment by LoneGazebo** [comment]
You should jump to 3/9! It is nice up here.

**Comment by LoneGazebo** [comment]
Oh, yeah there's no yield on the building, only the left tooltip (building yield isn't updated liked that).

**Comment by LoneGazebo** [comment]
Cool, no rush. I'm currently unifying all of the 'instant yields' into one centralized function. Lots of clutter. LOTS of clutter.
