### ISSUE TITLE
MP Desyncs

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1428]
Hey @ilteroi ,

So looking over some recent MP logs, I noticed that I'm seeing more and more of this:

`Game Random Number Generators are out of sync :`

This is obviously bad, but I'm not really sure why it is happening.

**Comment by LoneGazebo** [comment]
I'm a little worried it has to do with the changes to CvRandom...

**Comment by mwhiter** [comment]
Regarding random, one of the crashes i experienced a few days ago was directly related to random number generation.

**Comment by LoneGazebo** [comment]
Interesting. Yeah, I'm a little concerned by it.

**Comment by ilteroi** [comment]
by changes to CvRandom you mean the move to 64 bit, right? if there was a problem with it, it would fail all the time, not sporadically.

but maybe it's time for another reproducability check. that helped last time, iirc.

also there was a comment somewhere that barbarian camps spawning cause desyncs. don't know if that's cause or effect though.

**Comment by LoneGazebo** [comment]
The out of sync errors that generally seem to be causing issues in MP stem from that message above, which is tied directly into random. If there's no absolutely necessary advantage to 64 bit, perhaps we should revert? Unless there's another solution that I can't think of. My fear is that the network game-sync can't handle the 64 bit stream, and that its sending a broken packet.

**Comment by LoneGazebo** [comment]
Well, I take it back (for now). Seems the issue may be EUI! Stupid EUI.

**Comment by ilteroi** [comment]
I suspect EUI is responsible for most crashes etc we have. I'm clueless with Lua but would it be possible to rip out the city screen and throw away everything else? That's the most useful part IMHO. Don't really care about the rest.

**Comment by LoneGazebo** [comment]
Unfortunately no. He's got it all hardwired into a massive tooltip library.

**Comment by Iamblichos** [comment]
I'm telling you that EUI is junk. You can get CTD's just by holding cursor over the leader board(right hand side) late game. Among other things...

**Comment by mwhiter** [comment]
Why include it in the CPP then?

**Comment by Iamblichos** [comment]
Popularity for one. But I think there are some issues there that have been largely dormant that have alluded us in regards to CTD's and some other misc. bugs. I think it should be ditched. I finally narrowed down all my CTD's due to it and have not got a single one since I stopped using it at least those that break on disassembly.

**Comment by LoneGazebo** [comment]
I think it's the caching model, for one thing. He really, really likes his iterators, and that get's crazy laggy end game. If you watch Civ's memory/cpu use on certain actions, it spikes suddenly with certain actions. Those spikes probably affect the game clock and cause a CTD.

**Comment by ilteroi** [comment]
don't want to interrupt the EUI bashing, but there's definitely something wrong with the reproducability.

i have a save here where the AI acts differently after each load, depending apparently on where you scroll the map (!?) in observer mode.

screenshot of the diff between the RNG logs:

![image](https://cloud.githubusercontent.com/assets/1358966/13719461/313f8e90-e7f6-11e5-9268-49f3e65972cf.png)

will retest without EUI.

**Comment by Iamblichos** [comment]
It really does. If you run a sum game and let it go 200 turns and then move the map to where there was heavy action where you get all the injury and healing popups, you are guaranteed to get a crash.

**Comment by LoneGazebo** [comment]
Shh @ilteroi don't interrupt a lynch mob! :)

In all seriousness, that's really odd. What the hell is going on?

**Comment by ilteroi** [comment]
ok, the scrolling thing was coincidence. happens even when you don't do anything
