### ISSUE TITLE
Barbarians spawn 1 tile away from their camps

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#143]
There is barb camp on a 2 tile island near one of my cities. Barbs spawn not on their island but near my city in my territory. And I can't cross the ocean to get to their camp. They should be able to spawn on tile next to their camp. If no empty land tile available, only ships should spawn.

**Comment by LoneGazebo** [comment]
I'll look at this – barbarians are not supposed to be able to spawn beyond 1 space away.

**Comment by LoneGazebo** [comment]
Fixed.
