### ISSUE TITLE
Movement along rivers

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1430]
@ilteroi , will you double-check this?

http://forums.civfanatics.com/showpost.php?p=14194226&postcount=14

Songhai river movement bonus should be giving them at minimum 1 extra move along (but not across) rivers, right?

**Comment by ilteroi** [comment]
it's supposed to be "flat movement cost when moving along or crossing rivers".

just like inca is "flat movement cost in hills" and iroquis is "flat movement cost in woodland"

**Comment by LoneGazebo** [comment]
Ah, okay. I guess we need to update UA text then.
