### ISSUE TITLE
ExCE CTDs and MiniDump

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1432]
Good ol' ExCE is causing a CTD again, somewhere, but this time its impersistent. Could you please take a look at the [MiniDump](https://www.dropbox.com/s/007rcyut1f7hvqw/CvMiniDump.dmp?dl=0) here and tell me if its decompiling to Lua or if its something else. Thanks.

This is with only ExCE, CP (12/03), and IGE.

**Comment by LoneGazebo** [comment]
Does it crash on the latest version of CP? I'm going to have a hard debugging that old of a CP.

**Comment by JFDaly** [comment]
Oh, lol, you Americans. Sorry = it is the latest CP, the one you released yesterday (March 12th).

**Comment by LoneGazebo** [comment]
Oh. Right!

**Comment by LoneGazebo** [comment]
Alright, ran dump, it went to disassembly. So most definitely a lua bug. :/

**Comment by JFDaly** [comment]
Ugh. I wish there was something more I could do than blindly turn things off one by one and test - especially when it's irregular. Thanks anyway.

**Comment by JFDaly** [comment]
Is there a CvGameCoreDLL_FinalRelease2.pdb file that you have or something? According to [this](http://forums.civfanatics.com/showthread.php?t=506328) I might be able to read the MiniDump myself to find the part when it crashes, but I need that file. Of course, I might be entirely wrong here - but CID is causing some crashing too, now, and trying to diagnose is not enviable.

**Comment by LoneGazebo** [comment]
I think it would be a good idea for to setup visual studio 2010 and import the CP, then live debug it. Best way to catch a crash is live.

I can help setup if you need.

**Comment by JFDaly** [comment]
Yes, that would be helpful. Not sure where to start, though. Do I need to compile the CP DLL following Whoward's tutorial [here](http://forums.civfanatics.com/showthread.php?t=528319)?

**Comment by LoneGazebo** [comment]
Yeah, so you'll need to grab VS2010 express (is free), install it, then download the CP github repo. Copy and paste all of the files from the repo (ignoring the EUI/No-EUI/CP/CBP/CSD/C4DF mod folders - those aren't needed). Load up the project, and then turn optimizatin off (right click the project, go to properties-> optimziation and set full to off.

Build the project, then drag and drop the DLL you make (it'll appear in the /mods folder of the root where you put the github repo) into the CP folder in your MODS folder. Leave the PDB where it is.

All that done, load up the game, then - once all the mods are loaded (but before you start the map generation), 'hook in' to the game in VS by clicking Tools->attach to process (then choose the civ.exe running). At that point, if all was done correctly, a DLL break from CTD will show you the precise spot where it happens (unless it is a lua error - but even lua errors may break in the DLL sometimes!)

I hope that makes sense...

**Comment by JFDaly** [comment]
I couldn't find the optimization setting, but managed to set everything else up correctly. There were a tonne of warnings or errors in the build phase, but I'm not sure if they're serious.

I'll test this out, but Civ is now constantly freezing everytime I try to load the CP DLL (whether the one I built as per your instructions, or the regular one, it doesn't matter - this was happening prior to your instructions, so it's unrelated). I'll try to fix this, but any thoughts?

**Comment by LoneGazebo** [comment]
There are 30 warnings that appear every time. They're benign.

**Comment by LoneGazebo** [comment]
The optimization setting is available if you right click on the project on the left side (the expansion-2 project) and click options at the bottom.

**Comment by JFDaly** [comment]
I got an unhandled exception, which coincided with the game freezing (this could be normal; I'm not sure). Not really sure what I'm looking at: ![Callstack](http://i.imgur.com/fQ2pYmR.png) ![Output](http://i.imgur.com/SAijDx3.png).

**Comment by LoneGazebo** [comment]
Were you hooked into the DLL at the time? The fact that it doesn't point to a spot in the DLL specifically makes it more likely to be in the lua, which sucks.

**Comment by LoneGazebo** [comment]
First-chance exceptions are innocuous, btw.

**Comment by JFDaly** [comment]
Yea, I think so - I followed your instructions anyway. Does it highlighting the .exe mean anything? Because the last time it was a Lua error, it was related to the game not handling units upgrading into something without a production cost, so maybe its something similar this time.

Thanks for the help anyway.

**Comment by JFDaly** [comment]
This time it had a bit more [info](https://www.dropbox.com/s/ugf3u9btu1e5hpm/Capture.PNG?dl=0) (imgur decided to die, so its a screenshot in my dropbox). Is this significant?

**Comment by Iamblichos** [comment]
JFD, are you using EUI?

**Comment by JFDaly** [comment]
Nope.

**Comment by LoneGazebo** [comment]
Yes, interesting. Are you on the 3/14 CP? If not, download it, replace your CvGameCoreDLL_Expansion2 folder with the new one then try it again. Ilteroi rewrote some stuff in that function (sounds like it was grabbing a bad plot, maybe?)

Is the map flat - i.e. has black edges?

**Comment by JFDaly** [comment]
The maps I've been using are the Earth ones, so not flat.

I'll try out 14/3 and report back.

**Comment by LoneGazebo** [comment]
Cool.

**Comment by JFDaly** [comment]
On Earth map, 14/3 (March 14th) CP + ExCE (only Attrition component active), I get this:
!(http://i.imgur.com/n4vfHWS.png).

I ran a few games before without Attrition enabled, and had no issues, so maybe something is interacting badly between the plot-based stuff and routes? I'll disable my Lua in Attrition, leaving only the DLL-based attrition on Terrains/Features stuff, and report back.

**Comment by LoneGazebo** [comment]
What does the call stack on both of those look like? You can toggle that in the bottom right window - that's what we need to see.

**Comment by JFDaly** [comment]
I don't have the callstacks from those two instances, but I re-created the error easy enough:
!(test)[http://i.imgur.com/nJmcaiD.png]

**Comment by LoneGazebo** [comment]
At the top of IsValidMovePlot, add this:

```
#if defined(MOD_BALANCE_CORE)
	if(!this || this == NULL)
		return false;
#endif
```

**Comment by LoneGazebo** [comment]
So it'll look like this:

```
//--------------------------------------------------------------------
// in updateImpassable we check terrain and features (per plot), combined with technologies (per team). here we additionally look at traits (per player). 
// result is a simplified version of canMoveInto. since we don't know the particular of the unit, we are more restrictive here
bool CvPlot::isValidMovePlot(PlayerTypes ePlayer, bool bCheckTerritory) const
{
#if defined(MOD_BALANCE_CORE)
	if(!this || this == NULL)
		return false;
#endif
	if ( getRouteType()!=NO_ROUTE && !IsRoutePillaged() && (!isCity() || getOwner()==ePlayer) ) //if it's a city, it needs to be our city
		return true;
```

**Comment by LoneGazebo** [comment]
Save that, compile, and then try it.
Sounds like a script is trying to place a unit on a null tile.

**Comment by JFDaly** [comment]
Well, three test runs with Exploration+Attrition and three with Exploration+Attrition+Tribes (whole ExCE suite) and no issues (up to 300 turns, at least), so I think that's solved it. Would this have any adverse side-effects if implemented? Is there anything I need to/can do?

**Comment by LoneGazebo** [comment]
I've integrated into the 3/15 version, so you can update to that and all is well. I'm curious as to why it didn't show up in the dmp you sent me, but oh well. Glad it is working now!

**Comment by LoneGazebo** [comment]
No, not adverse side effects. Essentially what was happening was that the AI was, somewhere, starting an operation without a muster plot (probably a null plot) and that was being called.

**Comment by mwhiter** [comment]
But wouldn't calling NULL->isValidMovePlot() crash the game regardless?

**Comment by LoneGazebo** [comment]
I put in earlier checks to avoid that. The problem was that it was looking for route data on a plot that was bad.

**Comment by JFDaly** [comment]
As I gear up toward releasing Sovereignty, I want to run through some AI games and debug any possible crashes in real time. I've download the latest repository here, but can't see to be able to build the project. Any ideas? 

![screen](http://i.imgur.com/817jyZi.png)

**Comment by Iamblichos** [comment]
JFD, open the Vox Populi ... sln file in Visual Studio, set your solution configuration at the top pulldown to debug or Released depending on what you need.

**Comment by LoneGazebo** [comment]
@JFDaly, you should also grab VS Express 2013.

**Comment by LoneGazebo** [comment]
If you use that and download the current repo (and install the repo's solution file etc.) it should work out of the box.

**Comment by JFDaly** [comment]
Right, thanks. I'll try VS E 2013 and get back once its downloaded.

**Comment by JFDaly** [comment]
So, from here:

![s](http://i.imgur.com/WOSv11r.png)

and the attach to process? There's nothing in between I'm missing?

**Comment by JFDaly** [comment]
Okay, these the my errors:

!(errors)[http://i.imgur.com/hxDRmrR.png]

All I did was install VS E 2013, load up the Vox Populi sIn file from a newly downloaded copy of the repo, and set it to build. Did I need to turn off optimization again? I must be missing something.

**Comment by LoneGazebo** [comment]
Debug mode should be 'de-optimized' - make sure you have the fireworks folder installed from the repo.

**Comment by JFDaly** [comment]
In the FireWorks folder? I have that folder, sitting in the Community-Patch-DLL-master folder. Am I supposed to do something more with it to install it?

**Comment by LoneGazebo** [comment]
No, should just go in your folder as you did it. Hmm...

https://mega.nz/#!SQUHVApT!YUj1e816SdBtiOGvhyUmsGO9oAZ9fx3zA4N4mknFaqg

Try unzipping that into your repo folder, overwriting stuff as needed.

**Comment by JFDaly** [comment]
Still no luck.

**Comment by LoneGazebo** [comment]
That's really odd. When you loaded the repo, you did not select the 'convert this solution' option in the popup, did you?

**Comment by JFDaly** [comment]
I haven't seen that option, so I don't think so.

**Comment by JFDaly** [comment]
Oh hang on, maybe I did - I didn't pay much attention to the first load. I'll re-try.

**Comment by LoneGazebo** [comment]
Yeah, go ahead and start from scratch and don't upgrade the solution. Solution needs to use the original structure, just in 2013 for compile.

**Comment by JFDaly** [comment]
Hm, nope, I only got this:

![s](http://i.imgur.com/LBu6PoU.png)

No prompt to convert otherwise.

**Comment by LoneGazebo** [comment]
Yeah, cancel that.

**Comment by LoneGazebo** [comment]
do not do it.

**Comment by LoneGazebo** [comment]
Just make sure you still have VS 2010 (or 2008) installed

**Comment by JFDaly** [comment]
I have both still installed.

When I click cancel, it brings up this:

![s](http://i.imgur.com/8rUteim.png)

**Comment by JFDaly** [comment]
This look better? 

![s](blob:http://imgur.com/1f135c0f-f051-44f2-8890-05280b54a256)

After the previous error, I selected a 'fix errors' option and then the project appeared in the solution explorer. After rebuilding, I got this output, which, although looking intimidating to me, reckons that it was successful.

**Comment by LoneGazebo** [comment]
picture link is broken
if it is 56 errors, that is good.

**Comment by JFDaly** [comment]
Yea, dunno why they had to change imgur. Pic should be fixed now. That looks like 56 million errors, yea.

**Comment by LoneGazebo** [comment]
In 'error list' do you get o errors, 56 warnings?

**Comment by JFDaly** [comment]
Yeap

**Comment by LoneGazebo** [comment]
You are good to go, then.

**Comment by JFDaly** [comment]
Awesome, thank you for your help.

**Comment by LoneGazebo** [comment]
C++ easier than you think to read/work - you'd be a pro at it (as you are skilled with lua).

**Comment by LoneGazebo** [comment]
Very same concept(s), just slightly different vocabulary.

**Comment by JFDaly** [comment]
Civ VI might be an opportunity to get into it, yea.

**Comment by LoneGazebo** [comment]
Yeah, no need when you have me to write your code for you! :)

**Comment by LoneGazebo** [comment]
btw all latest requests from you worked, ja?

**Comment by JFDaly** [comment]
This is true :p 

Yes, everything is working perfectly. I'm nearing the finishing stages of Sovereignty, so I don't think there's really anything more that I'd need, short of anything that might be causing CTDs.

**Comment by LoneGazebo** [comment]
Sounds good.

**Comment by JFDaly** [comment]
Okay, so I got a CTD, but I'm not really sure where to find info about it. The old way of doing this had more info, that is, it would point to somewhere in the DLL where the crash occured. But the call stack seems a lot less informative this time. Thoughts?

![a](http://i.imgur.com/P3t1x28.png)

**Comment by LoneGazebo** [comment]
Did you build a new DLL and then put that in your CP folder in MODS? If not, do that. If you did, then this is a pure lua crash - not a lua crash as a result of a DLL pull.

**Comment by JFDaly** [comment]
Yea, I did. Hm, I'll have to comb the Lua then. Thanks.

**Comment by LoneGazebo** [comment]
Yeah, that's an unfortunate crash. Are you 'hooking in' VS to civ while it runs? Sometimes it grabs an error that the minidump misses.

**Comment by JFDaly** [comment]
By way of 'Attach to Process'? yea.

**Comment by LoneGazebo** [comment]
Yeah, that's the best way to test. You might also copy->paste the .pdb file from where the DLL is made into your CP folder.

**Comment by JFDaly** [comment]
I'll give it a shot. The CTD seems consistent from the turn that it last did it, and I previously did four tests without a CTD before I added ExCE onto the lot - so I should have somewhere to start.

**Comment by JFDaly** [comment]
Adding the pdb file didn't tell me anything more, unfortunately.

**Comment by LoneGazebo** [comment]
was afraid so - definitely a pure lua issue.
