### ISSUE TITLE
Instant gold for buildings (Industry) triggers in pioneer/colonist cities

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1433]
It's quite strange: a city built by a pioneer comes with 13 pre-built buildings, but industry's opener only triggers on 9 of them. Councils, libraries, wells and shrines don't trigger the instant gold for some reason. Anyway, the 9 other give so much gold that it doesn't matter. It isn't intended, is it?

**Comment by LoneGazebo** [comment]
Shouldn't trigger for any of them.

**Comment by LoneGazebo** [comment]
I can't reproduce this, sorry.
