### ISSUE TITLE
Bank's gold into science conversion

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1434]
Something's off with it - as an example, I got 40 science on investing 70 gold into a building. I had full industry policy, so purchase costs were 30% lower than normal - maybe that's not factored in? Although even then the investment would be 100 gold instead of 70, which still doesn't translate into 40 science if the conversion ratio is 15% as advertised on the bank.

**Comment by LoneGazebo** [comment]
I'll look, but it takes the items gold cost direct from the DLL and coverts it.

**Comment by LoneGazebo** [comment]
Oh, you know what I bet it is? I bet I didn't turn off era scaling!

**Comment by LoneGazebo** [comment]
Yup, that was it.

**Comment by Edaka** [comment]
Ah, I had that suspicion, too. (:

**Comment by LoneGazebo** [comment]
Era scaling is now a DLL bool, and I just forgot to de-scale it (much like my boiler).
