### ISSUE TITLE
Can't choose any beliefs

### ISSUE THREAD

**Issue by Jeankedezeehond** [LoneGazebo/Community-Patch-DLL#1435]
Everytime I try founding a religion I get an empty menu and I cant select anything on the right hand side. I will add in an image for clarity. http://imgur.com/lvms9U1

**Comment by LoneGazebo** [comment]
Please try the 3/9 beta.

**Comment by Jeankedezeehond** [comment]
Is there a DLC version of that one already? I also tried the non-EUI version and it works fine that way

**Comment by LoneGazebo** [comment]
No, the modpack was the problem.
