### ISSUE TITLE
Sun God pantheon

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1437]
Currently gives +1 culture and +1 faith from farms not only on wheat. Saw Mongolian farm on gold providing under effect.
![20160312203354_1](https://cloud.githubusercontent.com/assets/12978597/13724618/5d4ce8d6-e894-11e5-8eb2-141480c18262.jpg)

**Comment by LoneGazebo** [comment]
Odd, the bonus is specifically for wheat IIRC. I'll give it a look-see.

G
