### ISSUE TITLE
Holy city converts 8 times / turn

### ISSUE THREAD

**Issue by kennan1** [LoneGazebo/Community-Patch-DLL#1438]
I missed out on religions but captured the holy city Moscow and became the owner of a religion. I also worked to enhance the religion with a great profet. I have the belief the gives science every time a city converts to my religion. Every turn i get 8 pop ups the Moscow has converted to my religion and i receive 8 x 120 science. I am running the  March 12th beta with the hotfix. Only other mods are Info Addict and IGE.

[archive.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/170617/archive.zip)

**Comment by LoneGazebo** [comment]
Does the archive include your save? If so, I'll take a look later. Thanks!

**Comment by kennan1** [comment]
Yep! Just click net turn and Moscow will convert 8 times.

**Comment by LoneGazebo** [comment]
Got it, wasn't setting the adoption bonus properly. Done!
