### ISSUE TITLE
reproducability status

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1441]
i have a simple setup now: start game, load save, autoplay for 5 turns, reload autoplay again, observe differences. goal is a) better debugging b) hopefully (indirectly) fix some multiplayer desyncs

findings:

1. something is wrong in diplo AI, sneak attacks are either requested or not. this used to have a side effect because the military AI used the RNG to find possible attack plots. which obviously caused a divergence. so i removed the RNG element, but the root cause is still unknown
2. tactical zone stats have slight differences. may be caused by random moves for unassigned units. i also removed those, but that's only a symptom of the divergence.
3. unit IDs are slightly different between first and second load (?!)
3. currently the point of divergence in the RNG logs is city production choice. see image below. in the left log, only a regular building is chosen. on the right, first a wonder is chosen and then a building. obviously, this changes all later RNG outputs.

![image](https://cloud.githubusercontent.com/assets/1358966/13726365/4c4ee7c0-e8c4-11e5-813c-5a483a835127.png)

@LoneGazebo : any idea?

**Comment by LoneGazebo** [comment]
1. There's no RNG element in the diplo AI, so that's odd. Could be a factor of military power changing, maybe? Might be worth just doing a flat check for all the spots where jonrandnum appears.
2. I think that's still probably a factor of military power movements
3. Perhaps the unit iterator repasses through on load? I wonder if that's a problem with the kstream being closed...
4. The 'numchoices' element at the end of the building production choice causes that. Maybe the RNG seed is being reset on reload?

**Comment by ilteroi** [comment]
1. i think some variable is maybe not being reset correctly when loading a game. not necessarily RNG related. also see image below. once AI wants to trade embassies, next run it's strategic resources.
2. just implemented additional logs, we'll see
3. turns out in one run the AI bought a caravan, which changed the ID for all later units
4. RNG is reset, of course. but otherwise i cannot follow you. what could be a reason that in one run wonder production is considered and in the other run it isn't? RNG is only called when making the actual choice, by then the divergence has already happened.

![image](https://cloud.githubusercontent.com/assets/1358966/13728160/378579a8-e90f-11e5-8e6a-4bfc6bd86bba.png)

**Comment by LoneGazebo** [comment]
Well, I guess what I mean is, there's a function in civ with the 'refresh random seed on reload.' I wonder if that's being done every time (i.e. the seed information isn't being saved),

**Comment by LoneGazebo** [comment]
That was an element of Civ 4 I know,but I can't recall if it is in Civ 5.

**Comment by ilteroi** [comment]
did it mention that i like puzzles?

anyway it seems the wonder choice is because of a military strategy forcing a city strategy re-evaluation.

we have to go deeper!

**Comment by LoneGazebo** [comment]
Oh yeah, if city specializations are 'dirtied' the AI will reevaluate wonders and whatnot.

**Comment by ilteroi** [comment]
ok. next level.

the military strategy in question is mobilization. and it's becoming active because an army is being built (strange logic but true). the army is built (m_eArmyTypeBeingBuilt) because a sneak attack was requested from diplo AI.

so the root cause seems to lie there.

**Comment by LoneGazebo** [comment]
Where? In the diplo sneak attack?

**Comment by LoneGazebo** [comment]
The Diplo sneak attack call is real simple: if the AI has MAJOR_CIV_APPROACH_WAR as its approach, it will try to get a target on the civ. If it can, it'll request a sneak attack.

So, if that's where it is headed, then the RNG is actually in the military AI 'score target' functionality for choosing the best global military target.

**Comment by ilteroi** [comment]
indeed it seems m_cachedTargets was not reset properly.

quite a journey to figure that out :)

**Comment by LoneGazebo** [comment]
Haha. Oh, the places you'll go!

**Comment by ilteroi** [comment]
and maybe i had to rewrite a bunch of things along the way ...
