### ISSUE TITLE
Cooperation belief giving yields with population growth in cities without Religion

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#1442]
Was happening before the hotfix in both kinds of wrong situations, cities without Religion or cities with Pantheon (in cities with Religion is working fine), now only in cities without Pantheon, when a Pantheon is present is working fine not applying yields and it's happening in a new game started after applying the hotfix.

<img width="680" alt="civ5screen0000" src="https://cloud.githubusercontent.com/assets/13163824/13728507/a89fd03c-e91b-11e5-84cf-f0fd73604299.png">

![mods](https://cloud.githubusercontent.com/assets/13163824/13728496/24fcb1be-e91b-11e5-90e8-7ec7970469ff.JPG)

Save the turn before growing pop

[Dido_0104 BC-0275.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/170950/Dido_0104.BC-0275.zip)

**Comment by LoneGazebo** [comment]
Fixed.
