### ISSUE TITLE
[v3/12] Wonders missing NumPoliciesNeeded value

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#1449]
Using v 3/12 I noticed that the following 11 wonders (including CSD ones) lack a NumPoliciesNeeded value

BUILDING_BIG_BEN
BUILDING_BRANDENBURG_GATE
BUILDING_FORBIDDEN_PALACE
BUILDING_FORUM
BUILDING_HANGING_GARDEN
BUILDING_MOSQUE_OF_DJENNE
BUILDING_PARTHENON
BUILDING_PORCELAIN_TOWER
BUILDING_SUMMER_PALACE
BUILDING_TERRACOTTA_ARMY
BUILDING_UFFIZI

\Skodkim

**Comment by LoneGazebo** [comment]
The ones that are finisher unlocks from policy trees don't need them. And Forum/Summer Palace get them in the compatibility file.

**Comment by skodkim** [comment]
aah, that explains it :smile: 

\Skodkim
