### ISSUE TITLE
[3/14] Papermaker Happiness change

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#1450]
Paper makes reduces unhappiness from Poverty while libraries normally reduces unhappiness from Illiteracy. An oversight when converting it to a Library or intended?

\Skodkim

**Comment by LoneGazebo** [comment]
Oh, I flipped a switch but forgot to flip it back.

**Comment by LoneGazebo** [comment]
I'll fix it in post.
