### ISSUE TITLE
[3/14] University has Yield on Growth

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#1451]
From  (2) Community Balance Patch\Balance Changes\Buildings\BuildingChanges.sql

INSERT INTO Building_GrowthExtraYield
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_UNIVERSITY', 'YIELD_SCIENCE', 34);

Is this intended (I thought it was removed)?

\Skodkim

**Comment by skodkim** [comment]
Oh, Seowon has it too

**Comment by skodkim** [comment]
But Wat doesn't...

**Comment by LoneGazebo** [comment]
Wat is a constabulary, not a university. Growth Extra Yield is intended – that's not what you think it is.

**Comment by LoneGazebo** [comment]
GrowthExtraYield gives you 34% of the city's science per turn as instant science every time a citizen is born in the city.
