### ISSUE TITLE
Galleas Damage

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#1452]
Why do Galleas take so much damage?  In my last game as Japan, Galleas would do like 80 per hit; the lower CS was used to take the hit vs the higher RCS doing the damage.
3/12 Beta btw

![20160313235003_1](https://cloud.githubusercontent.com/assets/11430209/13753687/5add8ec8-e9ea-11e5-9351-644c0101c50c.jpg)

**Comment by LoneGazebo** [comment]
They're 'galleass cannons' :dancer:

**Comment by LoneGazebo** [comment]
(glass cannons) - I'm so sorry.

**Comment by phantommaxwell** [comment]
Or is this something we should discuss on the Forums?

**Comment by LoneGazebo** [comment]
Forums. It is WAD.
