### ISSUE TITLE
World Wonders and Later Era Starts

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1454]
I'm looking into something else, so I did some Modern Era starts, and I noticed that the policies the game lets you start with don't even come close to allowing era specific wonders. I realize no one actually plays serious games with later starts (other than maybe Classical?), so its not worth a ton of effort, but if there's maybe an easy fix to implement?

**Comment by LoneGazebo** [comment]
You could increase advanced start points, perhaps?

**Comment by pandasnail** [comment]
Oh, is that an setting a player can just edit? I didn't realize that if so. (I don't truly play this way, just use it to try and see if SQL changes I've made work or like earlier I was hoping 'RandCalls' log would tell me why I seem to never ever get War Weariness)

**Comment by LoneGazebo** [comment]
I think so yep, but the circumstances are pretty slight. Check in Eras or perhaps Difficulty settings.
