### ISSUE TITLE
Melee Naval can attack fort unit

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#1455]
Melee Naval can attack units stationed in fort. The damage table ( The one showing approx. damage and combat bonuses.) is not shown when selecting the attack unit, hovering the cursor over the defend unit.
E.g. A corvette(30CS, 30 damage) can attack a crossbowman (13CS, 30 damage).

**Comment by LoneGazebo** [comment]
@ilteroi , should we make domain exclusion checks for melee attacks?

**Comment by ilteroi** [comment]
well, that's a consequnce of the attacks on cities - forts and cities are treated equally. could be changed of course, but i'd rather not touch this again.

don't know what's up with the missing combat preview. maybe fix that instead?

**Comment by LoneGazebo** [comment]
Not really an issue of 'fixing' it – there's no hook for lua to look at cross-domain melee. Cities are treated as special objects in the lua, so it would break compatibility with any mod that edits the enemyunitpanel and uses the CP.

Why don't we just add a 'no cross-domain melee, except cities' exclusion?

**Comment by ilteroi** [comment]
because for melee movement == attacking, and we still want to be able to enter forts.

but it's not impossible, just tricky

**Comment by LoneGazebo** [comment]
canmoveinto and canattack at plot are different function calls, though, right?

**Comment by LoneGazebo** [comment]
Quick question: are ranged v. ranged attacks between sea units being treated as RCS v. CS, or RCS v. RCS? Because ranged units on land use RCs v. RCS, correct?

**Comment by ilteroi** [comment]
it's complicated  ...

this is the code:

		// If this is a defenseless unit, do a fixed amount of damage
		if (!pDefender->IsCanDefend(pTargetPlot))
			return /*4*/ GC.getNONCOMBAT_UNIT_RANGED_DAMAGE();

		if (pDefender->CanEverEmbark() && pTargetPlot && pTargetPlot->needsEmbarkation(pDefender))
		{
			iDefenderStrength = pDefender->GetEmbarkedUnitDefense();
		}
		// Use Ranged combat value for defender, UNLESS it's a boat or an Impi (ranged support)
		else if (!pDefender->isRangedSupportFire() && pDefender->getDomainType() != DOMAIN_SEA)
		{
			iDefenderStrength = pDefender->GetMaxRangedCombatStrength(this, /*pCity*/ NULL, false, false, pTargetPlot, pFromPlot);
			if (iDefenderStrength==0)
				iDefenderStrength = pDefender->GetMaxDefenseStrength(pTargetPlot, this, /*bFromRangedAttack*/ true);
		}
		else
		{
			iDefenderStrength = pDefender->GetMaxDefenseStrength(pTargetPlot, this, /*bFromRangedAttack*/ true);
		}

**Comment by LoneGazebo** [comment]
I think the line

`else if (!pDefender->isRangedSupportFire() && pDefender->getDomainType() != DOMAIN_SEA)`

should be 

`else if (!pDefender->isRangedSupportFire() && pDefender->getRangedCombat() > 0)`

whatever the pull for rangedcombat strength is. Feels much more logical.

**Comment by ilteroi** [comment]
yeah. no objections. make it so :)

**Comment by LoneGazebo** [comment]
Will do.

**Comment by LoneGazebo** [comment]
What about moveinto v. attackinto?

**Comment by ilteroi** [comment]
no time yet

**Comment by LoneGazebo** [comment]
That fine, I just meant in theory.

**Comment by qqqbbb** [comment]
Ships capturing cities also does not make sense.

**Comment by LoneGazebo** [comment]
That's not going to change - melee ships are necessary in order for naval invasions to even have a chance at success.

**Comment by ilteroi** [comment]
what the G man says ... that option has been discussed before. 

however, heretical scenario:
- all ships become ranged units
- embarked melee units are used for capturing

**Comment by LoneGazebo** [comment]
Blegh. That's worse than vanilla civ! :)

**Comment by Iamblichos** [comment]
Did we ever conclude what needed to be done on this one?

**Comment by LoneGazebo** [comment]
I fixed the range damage part. Other part is still open ended.

**Comment by Iamblichos** [comment]
So I gather here we need to do a lua hook for this.

**Comment by LoneGazebo** [comment]
Probably

**Comment by Iamblichos** [comment]
I'll see what I can do on this one G.

**Comment by Iamblichos** [comment]
Needed shore up these old requests.
