### ISSUE TITLE
Error in TradeLogic.lua

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1456]
[335861.609] Runtime Error: ....TradeLogic.lua:522: attempt to index field '?' (a nil value)

This is in the (6b) Community Balance Patch - Compatibility Files (No-EUI). 3/15 (but was also present in 3/14). Never had this issue before.

**Comment by LoneGazebo** [comment]
I think it only happens if you haven't met anyone (as the otherplayerbuttons table doesn't populate).

**Comment by Iamblichos** [comment]
It happens every time. I'm in the Modern era currently. It seems benign as the trade logic goes through fine....

**Comment by LoneGazebo** [comment]
Odd. I didn't see any bugs while debugging that. I fixed it so that unknown civs shouldn't appear in your DOW/DOP 3rd party lists.

**Comment by Iamblichos** [comment]
It's a modpack, dunno if that's why, but I used to never get that error...so something's up. But the trade deal seems to work though...

**Comment by LoneGazebo** [comment]
Ugh, modpacks.

**Comment by Iamblichos** [comment]
Started a new game and it went away...strange....

**Comment by LoneGazebo** [comment]
Spooky.
