### ISSUE TITLE
Corporation Overview Dev

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1457]
This is a separate thread cus it's not necessarily related to C4DF Beta anymore (since that should be done).

I found this thread while searching for another...

http://forums.civfanatics.com/showthread.php?t=547047

1) I wanted to quickly explain vassalagebenefits - when I first thought of that 3 years ago it was meant to be some sort of religion-like system where you could specify what benefits each vassal got, but never really got a good plan nor did I think it would work well, but maybe others thought differently? I'm curious to see (as an opinion) if anyone felt strongly one way or the other...

2) Gazebo, your post here: http://forums.civfanatics.com/showpost.php?p=14161106&postcount=70. Do you still want me to do something? If so, I can arrange that (as side work).

**Comment by LoneGazebo** [comment]
I think vassals are fine, bonus-wise. 

On the second, I was referring the AI's valuation of revoking vassalage and/or asking others to do it. Since you changed capitulation logic, thought you might want to look at that too.

**Comment by mwhiter** [comment]
Actually for the second I was referring to corporation lua

**Comment by LoneGazebo** [comment]
Oh, I see now! Read wrong part. I'd love it if you'd give it a sanity pass, see if it all makes sense. If you have any ideas on how to 'pretty' it up a bit, that'd also be welcome. I'm so bad at lua. :)

**Comment by mwhiter** [comment]
Can you give me a save so I can play around with it?

**Comment by mwhiter** [comment]
A screenshot of current corporations would also help so I can browse at work! (everything related to it)

**Comment by LoneGazebo** [comment]
Current corporation bonuses, or the current corporations lua?

**Comment by LoneGazebo** [comment]
When I get home from work, I'll send some pictures.

**Comment by mwhiter** [comment]
Everything! I need to educate myself on how corporations work.

**Comment by LoneGazebo** [comment]
Cool. I'll work something up.

**Comment by LoneGazebo** [comment]
Alright, here's a folder of pics:

https://mega.nz/#!XVVAkLrL!8N3ak_IW6LJibpYPW3_rHC_hpaFn7zmTLuCTeTIspU4

Gives you an idea of how the format is laid out. I'd love the layout to include corporation benefits in a panel (instead of a tooltip), and it'd be super-duper cool if current office bonuses were calculated here (Offices gain additional bonuses based on the number of franchises in the world). Let me know if you have questions.

**Comment by mwhiter** [comment]
Is there a place where I can view documentation of  a corporation?

**Comment by mwhiter** [comment]
Documentation of the Corporation system*

**Comment by LoneGazebo** [comment]
Yeah, it's all in the concepts section of the civilopedia. Should include the base data for each corporation, as well as the mechanics behind the system.

**Comment by LoneGazebo** [comment]
Essentially, though, it works like this:

Monopolies unlock access to certain Corporations
Corporations are wonders that are founded.
Once founded, you can build Corporate Offices (for the Corp you found) in all your Cities.
Trade Routes to or from cities with corporate offices will spread corporate franchises to the other city. So if there's a Corporate office for Giorgio Armeier in City A, and City B sends a trade route to City A, a corporation franchise of Giorgio Armeier will spread to City B when the trade route ends.
All corporations gain two benefits from spreading franchises: a bonus on every corporate office per franchise in the world, and a bonus for sending trade routes to cities that already have a franchise from cities with an office.

For example, the Giorgio Armeier Office generates +5% Great People in the city per franchise. So if you've established 4 franchises, all Giorgio Armeier Offices generate +20% great people.

If a city with a corporation HQ is conquered, the corporation is destroyed (and someone else can establish it).

The UI tracks your monopolies, foreign monopolies, as well as potential monopolies. It also tracks your franchises (And the franchise cap) as well as the cities you have offices and franchises in. It shows you the total # of franchises established by other civs with corporations and, lastly, the tooltip shows you the corporation's bonus.

Obviously the UI could offer more clear information, but I'm terribly uncreative with lua.

**Comment by mwhiter** [comment]
This is very helpful and I'll try to get a mockup done by Saturday, posted to the CPP Civfanatics page.

**Comment by mwhiter** [comment]
But what I'm thinking is this:

Remove Monopolies & Corporations from Economic Overview

Corporation Overview

**Initial view**
You cannot found a corporation until you have researched Corporations.

**Corporations Unlocked - No Corporation**
- separate a list with available and founded corporations.
- every possible corporation is displayed, with the resource monopoly required wonder (if we are building it, it displays a progress bar of much close it is to completion)
- if a corporation has been founded by a civ, display the founding civilization's icon next to it.

**Corporations Unlocked - Corporation Founded**
- Display Corporation
- Display city HQ
- Display list of Offices (city name)
- Display list of Corporation Franchises (city name, city owner icon)
- Display current benefit (from # of franchies)
  - tooltip displays info on how to increase benefit

**Monopolies Tab**
- Split into two views: Left (All resources and their current monopoly status), Right (detailed view, similar to what exists down, separated into our monopolies, potential monopolies, foreign monopolies, etc.)
- Explanation on what a monopoly is, and how to achieve one

**Comment by LoneGazebo** [comment]
Well that sounds lovely. Re: monopolies, the only caveat is that multiple civs can have a monopoly over a resource (some buildings/policies give resources that count towards your total owned (versus the total in the world). We'd have to control for that. Overall, though, I really like your conceptualization.

**Comment by mwhiter** [comment]
If you wanna give me live feedback as I develop the Corporations Overview, let me know. I'll be posting on civfanatics later with the results but for now [I'm streaming its dev](https://www.twitch.tv/slapshot781).

**Comment by LoneGazebo** [comment]
Neat! I'm about to have company, but I'll stop by for a moment.

**Comment by mwhiter** [comment]
Oh I just stopped for a bit, haha. :P

**Comment by LoneGazebo** [comment]
No worries, I'll catch up later.

**Comment by mwhiter** [comment]
http://forums.civfanatics.com/showthread.php?p=14205753#post14205753

**Comment by LoneGazebo** [comment]
Looking great!

**Comment by mwhiter** [comment]
Looks like Corporation Overview will break saves, had to add a new variable to syncArchive in CvPlayer: m_iCorporateFoundedTurn.

**Comment by LoneGazebo** [comment]
No worries, I've added a global define, and those don't play nice with saves either.

G

**Comment by mwhiter** [comment]
G on one of those Monopolies screenshots, Sweden has 112% of Wines. How is it possible to have more than 100% monopoly on a resource?

**Comment by LoneGazebo** [comment]
East India Company doubles your resources around a City. That's normal.

**Comment by LoneGazebo** [comment]
The doubling doesn't increase the base on-map amount of resources, just the amount owned (a la Russia's UA, or the Autocracy doubling of strategic resources).

**Comment by mwhiter** [comment]
Fair enough. Thanks!

**Comment by LoneGazebo** [comment]
Yep! Make sure to take a look at the Monopolies lua in the CBP to find all the IsFranchised(), HasOffice() etc. lua functions you were asking about.

**Comment by mwhiter** [comment]
I see them. This is easier. I am gonna to do a cleanup effort at some point.

I highly suggest we stop hardcoding monopoly resource values ASAP.

Suggested defines:

RESOURCE_GLOBAL_MONOPOLY_THRESHOLD = 50
RESOURCE_STRATEGIC_MONOPOLY_THRESHOLD = 25

**Comment by LoneGazebo** [comment]
The thresholds? That makes sense, sure.

**Comment by mwhiter** [comment]
The way I'll handle monopolies list is as follows:

Two dropdowns. One dropdown controls the type of monopoly (Global, Strategic, Potential, None); The other dropdown will control the civ display: All, or specific civs.

**Comment by LoneGazebo** [comment]
Sounds great.

**Comment by mwhiter** [comment]
Hiya, so I was out for the past two days while I installed my new SSD. I finally got everything working as I wanted to (major headache... fml). Either way, I'm back up and running. Will continue this as soon as I install all of my programs.

**Comment by LoneGazebo** [comment]
Sounds great. I love my SSD! :dancer:

**Comment by mwhiter** [comment]
This is ready to go, once again I am getting an unbelievable number of merge conflicts. I will have to hold this off, verify I've done everything, and once I get this working on my corp-helper branch, I will pull request off that.

**Comment by LoneGazebo** [comment]
Yeah, add to your developer branch and I'll manually merge. Github doesn't always play nice if the master is ahead of a branch. Thanks for this!

G

**Comment by LoneGazebo** [comment]
Latest CP has defines for Monopolies and Strategic Resources:

-- Monopoly Defines for CBP
INSERT INTO Defines (Name, Value)
SELECT 'GLOBAL_RESOURCE_MONOPOLY_THRESHOLD', '50';

INSERT INTO Defines (Name, Value)
SELECT 'STRATEGIC_RESOURCE_MONOPOLY_THRESHOLD', '25';

**Comment by mwhiter** [comment]
Excellent. Were those adopted into the source (i can check tonight, but...)

If not, I will adopt them to the source and add two new Game LUA functions!

Game.GetGlobalMonopolyThreshold()
Game.GetStrategicMonopolyThreshold()

**Comment by LoneGazebo** [comment]
Into the CP and DLL? Yep. You can grab those defines without the functions.

**Comment by mwhiter** [comment]
How? I wasn't aware of that?

**Comment by LoneGazebo** [comment]
local iGlobalMonopoly = GameDefines["GLOBAL_RESOURCE_MONOPOLY_THRESHOLD"];
local iStrategicMonopoly = GameDefines["STRATEGIC_RESOURCE_MONOPOLY_THRESHOLD"];

**Comment by LoneGazebo** [comment]
Should work.

**Comment by mwhiter** [comment]
Perfect! I honestly didn't know about that.

**Comment by LoneGazebo** [comment]
Yep! It's used a couple of times in the source lua, but not often enough that it's an easy reference to remember. I had to look it up.

**Comment by mwhiter** [comment]
The lua and ui reference is so terrible. And possibly outdated. I don't trust anything unless I see Firaxis using it.

**Comment by LoneGazebo** [comment]
Likewise!

**Comment by mwhiter** [comment]
"If a city with a corporation HQ is conquered, the corporation is destroyed (and someone else can establish it)."

Does this also mean cities acquired through trade and whatnot?

**Comment by LoneGazebo** [comment]
Yep, but technically the corp moves to the player's new capital if the capital is lost (like the palace). Only gets destroyed if the founding player gets wiped completely. If the city it is in is traded away the HQ is destroyed and the building is rebuilt in the capital (as least that's how it is theoretically supposed to work). There's a function in cvgame that does this, haven't looked at it in awhile.

G

**Comment by mwhiter** [comment]
There are a few flaws with that:

1. If a player that acquired the city already has a corporation, that violates the "one corporation per player rule"
2. That corporation is not available for others to build.

I've commented out that CvGame function, re-working the functionality. If a headquarters is acquired by any other player, then the corporation is destroyed (entirely) and available for someone else to found.

If there are objections to that, I'm definitely open to hearing them.

**Comment by LoneGazebo** [comment]
I don't think you need to do that. If the player acquires a city with a corp, the HQ is destroyed. It has the nevercapture rule.

**Comment by LoneGazebo** [comment]
The function checks once per turn to see if a corp founder has their requisite corp HQ - if they don't, the HQ is rebuilt in their capital.

**Comment by mwhiter** [comment]
Yes, but I'm doing a architecture overhaul - so it may be possible HQs lose that property. Right now, the function is commented out, things will happen immediately instead of waiting once per turn.

**Comment by LoneGazebo** [comment]
If you've got a better solution, go for it. I'm not partial to the current function. I wrote it largely just to 'get it done' back when I was tidying up 'whatif' scenarios for corps v.1.0.

**Comment by LoneGazebo** [comment]
@mwhiter, I'm seeing a lua error for the corp overview:

Runtime Error: ~Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Community Balance Patch (v 13)\Modular Elements\Corporations\CorporationsOverview.lua:1155: bad argument #1 to 'Compare' (string expected, got nil)

This happens when attempting to browse the franchise/office data for other civilizations.

**Comment by mwhiter** [comment]
Okay, thank you. How can I reproduce this issue? When you say other civilizations, do you mean through FireTuner (as in, this is happening in the your corporation tab?) Or is this occurring in the World Corporations tab? Can i see a more complete log?

**Comment by LoneGazebo** [comment]
Sorry, yeah, it's in the world corporations tab. I was running a game, stopped and took over for an AI, and perused the menu (making sure my merge went well). Noticed that the franchises pane was always empty, and saw the firetuner bug.

That was the only error in the log, unfortunately. As far as reproducing it, just run a small (or tiny) game into the 20th century, wait for someone to corp, and it should happen.

Also, I noticed that the SetCorporationFoundedTurn function wasn't being set when a corp was founded, so I added that to the CvPlayer.cpp function (Corps were being founded in 4000bc in the lua).

**Comment by mwhiter** [comment]
Thanks!

Hmm...maybe I'll investigate at some point tomorrow morning.

Yeah, that corporation founded turn was working when i implemented it, but it got left in the dust accidentally when i ported over to corp-helper.

I actually didn't want to see more runtime errors, just the calling function since they should all be printing. But since you tell me it's WC, I can reproduce when I try it. Thanks.

Can you please push the change to CvPlayer to master?

Any other issues?

**Comment by LoneGazebo** [comment]
None that I can tell thus far. I cleaned up the text a little (capitalized letters on Resources, added info to the tooltip, etc.) and made buttons for it for EUI and no-EUI:

![20160408212552_1](https://cloud.githubusercontent.com/assets/7849458/14400984/7be562fe-fdd0-11e5-94fd-4dca91529381.jpg)

**Comment by LoneGazebo** [comment]
I'll be updating the master shortly.

**Comment by LoneGazebo** [comment]
Updated - had to force push the git to get it to work.

**Comment by LoneGazebo** [comment]
Wodhann made us some icons! http://forums.civfanatics.com/showpost.php?p=14229046&postcount=47

**Comment by mwhiter** [comment]
Glorious! 

Why did you have to force push with git?

**Comment by LoneGazebo** [comment]
Merge incompatibilities. No big deal.

**Comment by mwhiter** [comment]
Okay so regarding that issue with the Lua Runtime error - do you have a save that will allow me to quickly verify it (without having to set it up in game)? Also, which version is it? Before master was updated, or after? I need to be able to load it. :)

I'll check after I get back home.

Regarding those icons, that will be great for a tech tree. Part of the architecture revamp will be assigning <CorporationsEnabled> to a tech (or an era, I'll support both). On the tech tree, having that on a tech will display all three icons.

**Comment by LoneGazebo** [comment]
Sounds good. Re: runtime error, It was on a build prior to the current master. If/when I reproduce, I'll link. In the meantime, you could probably reproduce it by using the firetuner to drop a corp HQ in a city, put a franchise in another, and then (from a third civ) look at the lua.

**Comment by LoneGazebo** [comment]
We could also use those icons as additive elements for Wodhann's corp icons (i.e. put the icon on the franchises/offices of those HQs). I do need to ask him to make another Giorgio Armeier - I just can't make myself use that goofy portrait of Sid. :)

**Comment by mwhiter** [comment]
I found an issue where clicking sort by headquarters on World Corporations tab caused the display to fail. It was because it was sorting on the city's lua table, instead of the city's name string. I just fixed that.

**Comment by mwhiter** [comment]
And yes - while we are a mod, I really like to strive to replicate Firaxis' professional standards, and having a joke icon does not suit well with me.

**Comment by mwhiter** [comment]
I cannot for the life of me reproduce that franchise issue, I am going to assume it's related to the headquarters one.

**Comment by mwhiter** [comment]
Actually, scratch that off, I CAN reproduce that issue, but it goes away if you hit one of the sort options - hmmm.

**Comment by mwhiter** [comment]
haha, I see a typo in the code!

**Comment by mwhiter** [comment]
okay, they are fixed on master - sorry about that!

**Comment by LoneGazebo** [comment]
Awesome! No worries. Thanks for the fix.

**Comment by mwhiter** [comment]
few outstanding tasks I can see off the top of my head, unrelated to my architecture change:

- could probably error-handle better, right now there are lot of assumptions being made about how corporations are defined
- probably didn't account for the Order policy on the franchise window - is there any logic that needs to be made here?

**Comment by LoneGazebo** [comment]
I don't believe so, no, as the Order policy should - IIRC - grab offices as franchises. I think. :)

**Comment by LoneGazebo** [comment]
As long as you are iterating through and using the isfranchised function (And you iterate through the active player as well).

**Comment by mwhiter** [comment]
No ill have to use that going forward. :)

**Comment by LoneGazebo** [comment]
Yeah, I haven't looked at the code lately, but I believe isFranchised checks for order status. If not, I can make it that way.

**Comment by mwhiter** [comment]
You can, but there's a high chance I'll re implement it as part of the architecture change in the future.

**Comment by mwhiter** [comment]
IsFranchised does not check for order status, and I will adjust it.

**Comment by LoneGazebo** [comment]
I think the order check function resets franchised statuses.

**Comment by mwhiter** [comment]
Okay, well I'll have to do more further investigation in the future.

**Comment by LoneGazebo** [comment]
So long as it is working as intended, it works for me. :)

**Comment by mwhiter** [comment]
Did you read my note on my latest pull request?

I don't have EUI, I can't test integration with it.

I also only develop the CPO with CP + CBP, would there be any integration issues with compatibility patch?

I.e. if people run just CP, CBP, C4DF, CSD, EUI Compatibility - will it break?

**Comment by LoneGazebo** [comment]
Yeah, I did. EUI shouldn't break it, but I do test EUI before release. The corp stuff broke last time because people were running JFD's corp (which I forgot he made) without your structure changes.

**Comment by LoneGazebo** [comment]
@mwhiter alright, all is in and looks to be working. We shall see as we move towards an open beta soon. Meanwhile, I think that there's a bugs and a request for the corporation overview:

1.) The Franchises tab of the 'World Corporations' menu is always empty, regardless of the existence of franchises in the world.

2.) The Corporations tab of the 'World Corporations' menu should also list (and be able to be sorted by) the # of franchises and offices for each corporation. That would really help users see who has the strongest late-game corporation.

**Comment by mwhiter** [comment]
Very fair. I'll work on it this weekend.

**Comment by LoneGazebo** [comment]
Sounds good. Neither is supremely critical, so do not fret if time gets away from you. I will be absorbed by a bbq smoker all day tomorrow.

**Comment by mwhiter** [comment]
I pulled from the latest master and it just doesn't work for me:

![image](https://cloud.githubusercontent.com/assets/4925402/15982059/cc9e4fc8-2f4c-11e6-965b-0291b9196a2f.png)

I don't understand, because none of these tables should exist anymore, or be referenced anywhere:

![image](https://cloud.githubusercontent.com/assets/4925402/15982065/e7cc35e4-2f4c-11e6-9cad-00ebc0c4d0f5.png)

Super confused as to why this is broken on my end.

**Comment by mwhiter** [comment]
^ the reason was that the DLL needed to be compiled and added to Community Patch.

**Comment by LoneGazebo** [comment]
Let me reupload latest. I've done more work since then. Keep in mind you also need the latest CP/CBP off of master.

**Comment by LoneGazebo** [comment]
Alright, 6/11 beta uploaded. Works perfectly on my end.

**Comment by LoneGazebo** [comment]
the fixes you uploaded to master are redundant (I fixed them as well on my end). I also added icon/tooltip support for corps in the techtree etc. Use all the new files as the baseline (including my relocation of the database table alterations to the CP).

**Comment by mwhiter** [comment]
well damn, okay. :(

**Comment by LoneGazebo** [comment]
Well maybe not all redundant. Try the latest and see what it looks like.

**Comment by mwhiter** [comment]
fixed the World Franchise bug, and i am under the impression the Corporation texts aren't up to date

**Comment by LoneGazebo** [comment]
I'm not sure - did you change the abilities of the corporations? I thought a lot of the text was pre-generated.

**Comment by LoneGazebo** [comment]
Is the version I posted working for you?

**Comment by mwhiter** [comment]
Yes it is working.

As for auto-generation, some of it is now, others isn't, there was a reason for that but I forgot. There is room for iteration.

**Comment by LoneGazebo** [comment]
Okay. Let's figure out what is correct and edit the rest.

**Comment by mwhiter** [comment]
a good place to start is my texts for corp-dev. Those texts were updated to match any changes I had made.

**Comment by LoneGazebo** [comment]
Done and done. All up to date and the text is proper. I've tested it all as much as I can and it seems to work. I had to do some more bugfixing and whatnot, but not too much.

**Comment by mwhiter** [comment]
Awesome. Thank you for all the help.

How is the system working out?
