### ISSUE TITLE
AI doesn't improve sea resources

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1458]
I've yet to see an AI build workboats in the last couple of versions. Sea luxuries are always the most demanded as a result. (:

**Comment by LoneGazebo** [comment]
@iamblichos, any ideas?

**Comment by Iamblichos** [comment]
Build the improvement or build fishing boat units?

**Comment by LoneGazebo** [comment]
AI will only ask for them if it thinks it can improve them...so maybe the homeland AI is messing something up?

**Comment by Iamblichos** [comment]
I'll take a look at it.

**Comment by Iamblichos** [comment]
Started a sim game just so I could see what was going on. FULL CPP only, no other mods, and the non-EUI version. Don't see any issues. Note the turns:

![20160316092439_1](https://cloud.githubusercontent.com/assets/14372214/13815631/5c198fd8-eb59-11e5-84ed-255e60348518.jpg)
![20160316092449_1](https://cloud.githubusercontent.com/assets/14372214/13815632/5f22de46-eb59-11e5-86d8-28839dba12b9.jpg)
![20160316092546_1](https://cloud.githubusercontent.com/assets/14372214/13815636/623e9d0e-eb59-11e5-8574-b9d339df4cfb.jpg)
[net_message_debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/176145/net_message_debug.zip)

**Comment by Iamblichos** [comment]
On another @LoneGazebo , for my work only, I've completely rewritten the Homeland AI, fishing boats are now "workers" (they don't die) and behave like them, and Plotworkerseamoves feeds into ExecuteWorkers and the builder directive with a domain case switch (e.g. workboats don't need to build roads, etc.), and got rid of the naval target resources (all handled by the building directive). Didn't like that non resource coast tiles couldn't be improved. Just something to consider....

**Comment by Iamblichos** [comment]
Continuing on @ turn 100, looking at the net_message_debug.log again. Japanese Caravels are building improvements too, so I really don't see an issue here.

**Comment by Iamblichos** [comment]
Around turn 165, I see a few that aren't getting built though.

**Comment by LoneGazebo** [comment]
I may just need to up the flavor a bit for work boats.

Thanks for the investigation!

**Comment by Iamblichos** [comment]
I did a test case with changing it back to the previous code, and it didn't change anything. In fact, they still got built at the same tile and in the same order. So I think just giving work boats more flavor will do it.

**Comment by LoneGazebo** [comment]
Coolio

**Comment by Edaka** [comment]
Huh, must be a problem on my end then. Probably a mod conflict, although none of what I use are supposed to interfere like that. I'll check.

**Comment by Iamblichos** [comment]
Can you tell me your mod list?

**Comment by Edaka** [comment]
Apart from the CPP pack (with EUI): 

- Global - Air Routes	Version	1;
- Global - Enable Magellan	Version	8;
- Global - Naval Nearest Water	Version	2;
(all of the above are Whoward's);
- Historical Religions Edit (BNW or GK)	Version	45;
- Hunnic City List	Version	1;
- Randomize City Names	Version	2;
- InfoAddict	Version	22;
- More Great Works	Version	3;
- Quick Turns	Version	10;
- R.E.D. Modpack	Version	27;
- Remove XCOM Squad	Version	1;
- UI - Destination (bugfixed by Serp)	Version	3.

Btw, anyone getting this in the lua log, or is it me again? 

> Runtime Error: C:\Users\Edaka\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Patch - Compatibility Files (EUI)\LUA\TradeLogic.lua:522: attempt to index field '?' (a nil value)

**Comment by Edaka** [comment]
It's only the major civs that don't improve their sea resources, city states don't have a problem with that. In case anyone's interested (: I've yet to check without these additional mods - the current game is so tempting to be played out till the end.

**Comment by Iamblichos** [comment]
Yeah I was getting that same Lua error in a mudpack, so it is still there and elusive.  Can't see anything real evident in those mods that would prevent work boats...strange. Like G, said it could be a flavor thing, also city states have less stuff to build and less to compete over...

**Comment by Edaka** [comment]
Re: the error I'm not using modpack, if that means anything.

**Comment by LoneGazebo** [comment]
Is it causing anything bad? I can't seem to replicate it.

**Comment by Edaka** [comment]
Nothing that I could notice.
