### ISSUE TITLE
city expansion plot priority

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1459]
Hills have lowest priority even if there is a resource. I have plot on river with hills + jungle + cocoa (3 food, 1 gold) next to my city  but city borders expand to a grassland plot (2 food) instead.

**Comment by LoneGazebo** [comment]
It is random.

**Comment by qqqbbb** [comment]
It's not random. Cities expand to plots that have more yields but only if they are not hills. I noticed this a long time ago. It did not happen just once.

**Comment by qqqbbb** [comment]
If a city has forest + grassland (2 food, 1 hammer) and a grassland (2 food) plots available, the grassland plot will be taken first.

**Comment by LoneGazebo** [comment]
No, there's definitely a random component as to which tile is selected in the list of possible tiles. In any case, hills are chosen after flat/river/road land, yep. This is by design.

G

**Comment by qqqbbb** [comment]
It is by design but this design does not work properly with CBP. Grassland tiles are chosen before grassland + forest tiles since they are supposed to have more food but CBP gives forrests +1 food. Tiles to be acquired first should be chosen according to number of yields they produce not their type.

**Comment by LoneGazebo** [comment]
Rough features take longer than non-rough features. That's the design.
