### ISSUE TITLE
Cities do not expand their borders if CITY_STARTING_RINGS define is 0

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1460]

**Comment by LoneGazebo** [comment]
Yeah, because there will be an integer overflow. 1 is minimum.

**Comment by qqqbbb** [comment]
are you gonna fix it?

**Comment by LoneGazebo** [comment]
Fix what? No, 1 is the absolute minimum.

**Comment by qqqbbb** [comment]
But it worked fine several months ago.

**Comment by LoneGazebo** [comment]
I haven't changed anything about it, so might be a bug in your change.

G

**Comment by qqqbbb** [comment]
I've just tested v6-29 and this bug is not there.

**Comment by LoneGazebo** [comment]
Don't know what to tell you. Send me the change you made and I'll try to reproduce.

**Comment by qqqbbb** [comment]
The only change I made is xml file that contains:
```
<GameData>
	<Defines>
		<Update>
			<Where Name="CITY_STARTING_RINGS"/>
			<Set Value="0"/>
		</Update>
	</Defines>
</GameData>
```

**Comment by LoneGazebo** [comment]
Fixed. Was a Firaxis code bug.
