### ISSUE TITLE
Hovering units don't embark anymore

### ISSUE THREAD

**Issue by LynnesCFC** [LoneGazebo/Community-Patch-DLL#1461]
Hello Ilteroi,

I've noticed that you've changed the behavior of hovering units so they never embark.
While this is a nice feature in theory, it breaks all mods that are built on whoward's existing ruleset for embarkation!
Until now, the following rules applied:

-without a promotion, hovering units embarked at coastal tiles
-with PROMOTIONS_DEEP_WATER_EMBARKATION (CustomModOptions) they could hover over coastal tiles and embarked when entering ocean tiles (see PNM-mod: Promotions - Terrain Crossing) (really cool feature!)
-with a promotion that includes `<CanMoveAllTerrain>true</CanMoveAllTerrain>` they can hover over all kinds of water tiles (see Units - Steampunk Airships) (just like it is now in the CP, but without losing their ability to attack)
-with UNITS_HOVERING_LAND_ONLY_HEAL they only heal over land tiles
-UNITS_HOVERING_COASTAL_ATTACKS allowed hovering melee-units to switch to ranged attacks over water tiles with a strength you can freely define (for example 1/2)
-and hovering ranged units were able to attack on water tiles just as they could on land

As you can see, the existing ruleset allowed really **every** combination you could wish for, and some friends and I are using mods that base on exactly these rules!
With the latest changes to hovering units, all these mods were rendered useless, plus it is a huge restriction to what you can do in future mods!

Even gameplaywise I'd consider it a real drawback, since (embarked) hovering units can't be protected by your ships anymore, while at the same time they also cannot defend themselves.
And it feels odd that they can freely move over water tiles, but suddenly cannot attack when hovering over a lake (even if they are ranged!).

So for the sake of the already existing mods, the gameplay and the choices you have when creating new units/ mods, could you **please** restore the old rules for hovering units, so that the standard is embarking at coastal tiles?
(When you want to make gunships to hover over sea you could just add a CanMoveAllTerrain-promotion in the CBP then? But please don't take away the choice for everything else!)

This would be really awesome.
If you need more info than you can find in this wall of text (sorry about that! ^^) just let me know. ;)

Lynnes

**Comment by ilteroi** [comment]
wall of text indeed, hope i don't miss anything.

honestly i didn't really understand the distinction between "hover" and "move all terrain". unfortunately the code was an unreadable, inconsistent mess.

in my opinion embarkation for hover units makes zero sense. if you want them to embark, use a land unit.

LAND_ONLY_HEAL is still there.

regarding attacks over water, that is not intended and i'll try to fix. also for melee attacks.

**Comment by Iamblichos** [comment]
@ilteroi, for attacking over water you could probably just change this:

```
#if defined(MOD_BALANCE_RANGED_ATTACK_ONLY_IN_NATIVE_DOMAIN)
    if(!isNativeDomain(plot()))
    {
        return false;
    }
#endif
```

to this:

```
#if defined(MOD_BALANCE_RANGED_ATTACK_ONLY_IN_NATIVE_DOMAIN)
    if(getDomainType() == DOMAIN_SEA && !plot()->isWater())
    {
        return false;
    }
#endif
```

and the other places where that is set.

**Comment by Iamblichos** [comment]
I agree, while the deep embarkation was kinda cool, I just don't think it makes any sense for Helicopters to embark. Wouldn't just giving them the ability to attack while hovering over water (melee or range) give you all the functionality that you need? Don't see any added value to embarking a heli.

**Comment by LynnesCFC** [comment]
Okay, 2 reasons for hover-embarkation: ;)

1.: In the real world, helicopters cannot cross oceans as well (unless they land on a carrier = embarkation!), because they would run out of fuel very soon and swim like a stone!
But still they are able to fly over coastal waters or lakes of course! (-> deep water embarkation)

2. According to whoward, hovering units that melee-attack over water tiles will cause graphical issues and CTDs, that's why he created the switch from melee to ranged in the first place.

So imo embarkation for hovering units makes perfect sense, logically and gameplay-wise!

When we use a land unit, all the cool features for hovering units (deep water embarkation, switch from melee to ranged, being able to cross all kinds of terrain,....) still won't work anymore and break the mods that rely on these features!

And isn't the CP only for fixing bugs and the AI, and the rule ob thumb is that all balance changes are done in the CBP? This is a balance change! If you think that embarkation for hovering units makes zero sense, why don't just add it to the CBP instead? :/
Remember: When you allow hovering units to attack on water tiles (and everything else doesn't make sense!), you would still have to change something about gunships in any case (CTDs and graphical issues when melee on water tiles)!

**Comment by LoneGazebo** [comment]
It wasn't perfect. It was deeply flawed code. 

@ilteroi, what about a promotion that forces embarkation on a unit? Gives you option to hover or embark that way.

**Comment by LynnesCFC** [comment]
With 'perfect' I was referring to the set of rules and how everything worked, not the code!

Hm... now that I think of it... Gazebo you are a genius!
A promotion that forces embarkation would be an even better and much cleaner solution!

When LAND_ONLY_HEAL is still there and attacking on water tiles (maybe even ranged **and** melee is now possible, now that the code is rewritten?) works again, this would open up all possibilities you had before without Ilteroi having to change anything, except adding the promotions of course. :)

If you should do it that way, could you please add one promotion for ocean tiles and one for all water tiles? Like `EmbarkedDeepWater` (this is how it was called previously, meaning you would retain compatibility to all mods!) and `EmbarkedAllWater` (emulating vanilla rules)?
This would be awesome!

**Comment by Iamblichos** [comment]
helicopters don't cause CTD's while attacking (melee) while on Coast, at least until they could before the NativeDomain check prohibitied it.

**Comment by Iamblichos** [comment]
To sum this up:

1) Give back deep embarkation for hover units,
2) Allow hover units to attack while on Coastal plots.

Is that correct?

**Comment by LynnesCFC** [comment]
Oh, it's great when melee attacks are already possible without crashing the game!
Regarding your questions:

1) Exactly. A promotion that forces embarkation at ocean tiles (deepwater embarkation) and maybe another one for all water tiles (vanilla-style)!
2) Not only on coastal plots, but on all water tiles as long as the unit is not embarked (when it can hover it also can shoot :) )

**Comment by ilteroi** [comment]
i'm hesitant to touch embarkation again. it was hard enough to get it right with only one type, and now you want two.

also, if i understand correctly, g's idea means touching all land units to to give them the embarkation promotion?

what's the problem with making the helicopter a land unit with "all terrain" promotion?

**Comment by LynnesCFC** [comment]
I think Gazebo was talking about hovering units.

When gunships are land units with 'CanMoveAllTerrain' they will never embark, not even on ocean tiles, which is not realistic and breaks all mods that rely on this functionality or whoward's Terrain Crossing mod! 
Example: another PNM mod, where the distinction between the different airships is that the smaller one can only hover over coastal tiles, while the large one can also cross oceans.

**Comment by ilteroi** [comment]
well, it turns out the helicopter is in fact not DOMAIN_HOVER but DOMAIN_LAND with a flag "isHoveringUnit". WTF

**Comment by LynnesCFC** [comment]
Not that you mention it:

the small airship is DOMAIN_LAND with `<HoveringUnit>true</HoveringUnit>` (hover coastal tiles only)

while the large one is DOMAIN_HOVER with `CanMoveAllTerrain` (hover on ocean tiles too)

Hm, so maybe even in the VMC-DLL the standard for DOMAIN_HOVER is to hover over **all** kinds of tiles, and only land-units with the hoveringunit-flag have some kind of embarkation available!

**Comment by LynnesCFC** [comment]
PS: Then there is also the `<EmbarkedDeepWater>true</EmbarkedDeepWater>` flag in the DeepwaterEmbarkation-promotion (Terrain Crossing mod), which is given to gunships and the small airship for example.

Wow, this really seems to be a difficult topic.
Still I'm sure you can handle it of course. :D

**Comment by LoneGazebo** [comment]
@ilteroi, the hoveringunit element is set before a unit spawns (see ::initwithnameoffset in cvunit). It is odd, yes. 

Ideally 'ishoveringunit' could apply only to land tiles, and then 'canmoveallterrain' when combined with ishoveringunit would allow for movement on coast/ocean tiles as an embarked unit.

**Comment by ilteroi** [comment]
fixed the impossible attack (could not test melee though - is there a hovering melee unit?)

the rest is a can of worms i won't touch right now. ain't nobody got time for that

**Comment by LynnesCFC** [comment]
helicopter gunships are melee units.

well, that's a shame. maybe whoward can help out here? I think he knows best about the domains/ flags, since he created the mods.

**Comment by LoneGazebo** [comment]
Be patient on the issue – he's not saying it's never going to change, just not at the moment. The spaghetti of embarkation and plot states is very difficult to work with.

**Comment by LynnesCFC** [comment]
Oh, I see! I misunderstood it and thought it's never going to happen, sorry! :)

**Comment by Iamblichos** [comment]
I can probably work on it. I know the embarkation stuff pretty well from doing my transport mod.

**Comment by LynnesCFC** [comment]
Really? 
Yay, this makes my day!! Thank you so much! :D

**Comment by Iamblichos** [comment]
Some Progress:

![20160316092546_1](https://cloud.githubusercontent.com/assets/14372214/13930928/fffd1084-ef6e-11e5-9382-77426949d199.jpg)

![20160321140758_1](https://cloud.githubusercontent.com/assets/14372214/13930931/01fed94e-ef6f-11e5-9017-bf2ad550da23.jpg)

**Comment by LoneGazebo** [comment]
Nice! Lynnes will be happy. How'd you do it  – a promotion?

**Comment by Iamblichos** [comment]
Yes using whoward's Promotion for deep water embarkation (for hovering units).
```
bool CvPlot::needsEmbarkation(const CvUnit* pUnit) const
{
	if (pUnit==NULL)
		return isWater() && !isIce() && !IsAllowsWalkWater();
	else
	{
#if defined(MOD_PROMOTIONS_DEEP_WATER_EMBARKATION)
		if (pUnit->IsHoveringUnit() && !pUnit->canMoveAllTerrain())
		{
			return isDeepWater();
		}
		else if (pUnit->getDomainType()==DOMAIN_LAND)
		{
#else		
		//only land units need to embark
		if (pUnit->getDomainType()==DOMAIN_LAND)
		{
#endif		
			return isWater() && !isIce() && !IsAllowsWalkWater() && !pUnit->canMoveAllTerrain() && !pUnit->canMoveImpassable() && !pUnit->canLoad(*this);
		}
		else
			return false;
	}
}
```

```
bool CvUnit::CanEverEmbark() const
{
	VALIDATE_OBJECT
	//return (getDomainType() == DOMAIN_LAND && IsHasEmbarkAbility() && !IsHoveringUnit() && !canMoveAllTerrain() && !isCargo() );
	return (getDomainType() == DOMAIN_LAND && IsHasEmbarkAbility() && !isCargo() && !canMoveAllTerrain());
}
```

those were the two functions I needed to adapt. All of the rest lot of it I had to go back into whoward's code and review it all line by line and fine where I could adapt it to the new stuff and/or add in the missing parts. There MIGHT be some very minor quirks in long range pathfinding over coast to land to coast, but since that is still in flux I think we can work through that as we go. Any hovering unit must not have move all terrain promotion set. I think we need to leave that promotion for any special unit that would never embark in any circumstance.

**Comment by LoneGazebo** [comment]
Makes sense to me. I'll bundle this into the next bugfix. Thanks for tackling the spaghetti, here's a prize: :spaghetti:

**Comment by LoneGazebo** [comment]
@LynnesCFC , does this do what you need it to do?

**Comment by Iamblichos** [comment]
Yeah give me another day to merge this into my CP (only project) and I'll upload into GitHub.

Also I didn't add in can cross Ice promotions and such, as the CP handles that much differently, don't really want to adapt all that or see the real need to.

**Comment by LynnesCFC** [comment]
Woah, thanks a lot!
So all hovering units can still move on all kinds of impassable tiles (with optional damage if they end their turn there), right?
And another thing I don't fully understand atm:
what is the difference now between a hovering unit without the DeepWaterEmbarkation-promotion and a hovering unit with CanMoveAllTerrain? Is there any? Since at the moment every hovering can move all terrain by default, which would make the explicit CanMoveAllTerrain-promotion redundant, wouldn't it?

**Comment by Iamblichos** [comment]
- Yes, hovering units will move on coast, and all kinds of terrain, and embark at ocean plots, with optional damage to whatever you (or whoward) have set.

- If you set a unit with promotion of move all terrain, it won't embark at all, ever.

**Comment by Iamblichos** [comment]
@LoneGazebo , as far as prize, don't hesitate adding me to the CP code team :+1:

**Comment by LoneGazebo** [comment]
Of course you're on the team!

**Comment by LynnesCFC** [comment]
> Yes, hovering units will move on coast, and all kinds of terrain, and embark at ocean plots, with optional damage to whatever you (or whoward) have set.

Okay, great! :)

> If you set a unit with promotion of move all terrain, it won't embark at all, ever.

Hm, I'm still confused.. ;) That's the default behavior in the current version for all hovering units (no matter if they have any promotion or not), right?
With your update, they will **only** embark when having the embark-promotion. So what's the difference then between _no_ embark-promotion and having CanMoveAllTerrain?

**Comment by Iamblichos** [comment]
If hovering units in the CBP have set move all terrain, they will need that removed. My checks are for IsHoveringUnit(), that should be set in the UnitInfo.

No embark promotion just doesn't allow units to embark onto water plots, Move all terrain, means you can go anywhere on the map, no restrictions.

**Comment by LynnesCFC** [comment]
Okay, my bad, I should have been more precise: I was talking about having no Embark**DeepWater**-promotion. This would result in units still being able to move on all tiles of terrain (without embarking at ocean tiles), no matter if they have a CanMoveAllTerrain-promotion or not, right?
Or are there any other tiles a hovering unit couldn't go to, so a CanMoveAllTerrain-promotion would make a difference, as long as there is no EmbarkDeepWater-promotion?

Or.. wait.. did you make it that from now on hovering units that don't have the EmbarkDeepWater- or the CanMoveAllTerrain-promotion embark at coastal tiles, just like land units do?

If it's still not clear what I'm trying to ask then nevermind, I'll just try it out. :)

Thanks a lot again for taking care of this issue! ;

**Comment by Iamblichos** [comment]
Nope, if you review the code above on NeedsEmbarkation you'll note that if you don't have that deepwater promotion MOD set (and I could add another check in there to ensure that the actual UNIT has the promotion set as well and not just the mod active), it'll embark at coast.

**Comment by LynnesCFC** [comment]
Ah, okay, now everything is clear! 
I wasn't aware that the default-behavior is embarking at coast now!
That sounds great! It's the perfect solution, really! :)

> and I could add another check in there to ensure that the actual UNIT has the promotion set as well and not just the mod active

This would be nice!

**Comment by Iamblichos** [comment]
I gotta give some praise to ilteroi here. His rewrite of the embark code made this really easy to put back in and the use of NeedsEmbarkation function (which doesn't exist in vanilla) made it so I didn't have to go back and edit this back in everywhere.

**Comment by Iamblichos** [comment]
Also, we probably don't want hover units embarking on deep water ice either.

**Comment by Iamblichos** [comment]
```
bool CvPlot::needsEmbarkation(const CvUnit* pUnit) const
{
	if (pUnit==NULL)
		return isWater() && !isIce() && !IsAllowsWalkWater();
	else
	{
#if defined(MOD_PROMOTIONS_DEEP_WATER_EMBARKATION)
		PromotionTypes ePromotionEmbarkDeepWater = (PromotionTypes)GC.getPROMOTION_DEEPWATER_EMBARKATION();
		PromotionTypes ePromotionEmbarkDeepWaterDefense = (PromotionTypes)GC.getPROMOTION_DEFENSIVE_DEEPWATER_EMBARKATION();
		if (pUnit->IsHoveringUnit() && !pUnit->canMoveAllTerrain() && (pUnit->isHasPromotion(ePromotionEmbarkDeepWater) || pUnit->isHasPromotion(ePromotionEmbarkDeepWaterDefense)))
		{
			return isDeepWater() && !isIce();
		}
		else if (pUnit->getDomainType()==DOMAIN_LAND)
		{
#else		
		//only land units need to embark
		if (pUnit->getDomainType()==DOMAIN_LAND)
		{
#endif		
			return isWater() && !isIce() && !IsAllowsWalkWater() && !pUnit->canMoveAllTerrain() && !pUnit->canMoveImpassable() && !pUnit->canLoad(*this);
		}
		else
			return false;
	}
}
```

**Comment by LoneGazebo** [comment]
Is that all the code? I can wait for a full push, no rush.

G

**Comment by Iamblichos** [comment]
nah, that's just the corrected one to show Lynne's. there's more to it than that.

**Comment by LoneGazebo** [comment]
Ah ok.

**Comment by LynnesCFC** [comment]
Really awesome! Thanks! :)

**Comment by Iamblichos** [comment]
Pushed. And pull request created! :) Be sure to review my notes on the pull request. Might want to test out before you release to ensure you have all the SQL/XML edits. Let me know if you need any help or have any questions.
