### ISSUE TITLE
[Feature request] Display building requirement in tooltip for purchasable units

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1462]
When you hover mouse cursor over trainable unit list in city view the tooltip tells you if unit requires a building but it does not do it for purchasable units.

**Comment by LoneGazebo** [comment]
Not sure o understand. If using EUI, issue requests to him, not me.

**Comment by LoneGazebo** [comment]
I*

**Comment by qqqbbb** [comment]
I'm not using EUI. Vanilla mouseover tooltip for archeologist in city view tells you that it needs university to be trained. But if a mod adds a unit that requires a building to be purchased (not trained), that building requirement is not shown in mouseover tooltip because there are no such units in vanilla game.

**Comment by LoneGazebo** [comment]
It's a hard-coded value, meaning that it can't be adjusted for other units. Sorry.
