### ISSUE TITLE
Missionary spreading causes Freezing and other CTD/Freeze Issues

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#1463]
I consider this problem machine-depend since I haven't seen others posting something related to the freeze. So here's my problem:

My game has been unstable recently. CTDs and Freezes occur more often. Missionary spreading causes CTD, Game freezes randomly with the cursor as a globe spinning. This time, missionary spreading causes texture corruption and hanging, which you cannot issue any actions to cities and units. Also, if you exit the game, it just stuck there.

My mod list:
1. EUI DLC
2. Community Patch
3. Community Balance Patch
4. CSD for CBP
5. C4DF
6. Community Patch Compatibility Patch w/ EUI
7. More Luxuries

Here's the image
http://postimg.org/image/gr9i5zd3p/

Thanks.

**Comment by LoneGazebo** [comment]
Sounds like a driver issue. Sorry, can't help you tony that.

**Comment by LoneGazebo** [comment]
With*

**Comment by XplosiveLun** [comment]
Thank you G. That narrows down the problem.
