### ISSUE TITLE
Investment for Units?

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1464]
Would it be possible to adapt the Investment system for use for Units? In my upcoming Slavery, I disable regular Unit purchasing for non-Mechanized Units. I can live with gold-rushing Mechanized Units (Tanks, Ships, etc.), but thought it would be more thematic if you could invest in them as you would a building. If it's a lot of work/not possible, it's no big deal - but I'd appreciate the possibility (I can handle the tooltip system update).

**Comment by LoneGazebo** [comment]
It'd be a new system set for the value, yeah. Perhaps not at the very moment, but in the near future I can tackle it.

**Comment by JFDaly** [comment]
No worries. Thanks for the info.

**Comment by LoneGazebo** [comment]
Keep this open so I can see it for later.

**Comment by JFDaly** [comment]
I had a look at the code in the DLL, and it looks like a lot of work (but then I don't understand half of it)! So do feel free to forget about this request. Otherwise, thanks and take your time.

**Comment by LoneGazebo** [comment]
Thankfully it'd just be a lot of copy-paste. Keep plugging along with your project and, if you find you really need it, let me know.

**Comment by LoneGazebo** [comment]
Alright, done. Will be in next version. The investment lua event will be split up:

GameEvents.CityInvested.Add(function(iPlayer, iCity, iBuildingClass, bValue) end)	GameEvents.CityInvestedUnit.Add(function(iPlayer, iCity, iUnitClass, bValue) end)

**Comment by LoneGazebo** [comment]
You'll need to do the lua (just mirror what I did for buildings), but all the core data is there. You'll also need to enable the element in the custommodoptions.xml file:  BALANCE_CORE_UNIT_INVESTMENTS

Also, the define for setting the % value: BALANCE_UNIT_INVESTMENT_BASELINE

This is also affected by the investment Trait and Policy modifiers (like buildings).

**Comment by JFDaly** [comment]
Really amazing, thank you!

**Comment by LoneGazebo** [comment]
No problem. The base value for BALANCE_UNIT_INVESTMENT_BASELINE is -50, as with buildings.

G
