### ISSUE TITLE
World religion

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1465]
Version 3/9.
I am not getting the delegates for following world religion (I checked that I am head of Protestantism).

![20160317084248_1](https://cloud.githubusercontent.com/assets/16065630/13859981/7acc7df4-ec86-11e5-9ef9-4f82b7878a0b.jpg)

**Comment by LoneGazebo** [comment]
And you've built the national wonder?

G

**Comment by Der-Zorn-Gottes** [comment]
I conquered it, but that shouldn`t matter. The votes from the wonder are called religious authority, and they are there as expected.

**Comment by LoneGazebo** [comment]
Oh, sorry, misunderstood your complaint. I'll look at world religion shenans.

**Comment by LoneGazebo** [comment]
Possible that you controlled the religion, but it wasn't your majority religion? In any case I've made it so that it can be either/or now.

G

**Comment by Der-Zorn-Gottes** [comment]
Hard to tell. Anyway, the fix is appreciated. :-)
