### ISSUE TITLE
France UA Marathon speed

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1466]
I liberated a CS from Mongolia, and got four turns of double culture. Since turn length things scale with game speed, and things are usually x3. So either its normally one turn on standard, or it doesn't scale.

Now with that said, if it were supposed to be 12 turns of double culture for every conquered city, I'd want that much much more then a couple GWs, so I'm not sure. Can't remember how many GWs you get, haven't gotten to that stage of the game yet. (And probably won't, I'm anxious to try the new Authority once it drops, plus Archers back at 6). Maybe I seriously underrate GWs pre-Museums?

**Comment by LoneGazebo** [comment]
It doesn't scale because culture already scales with gamespeed. I can change this, but it might break France for Marathon.

**Comment by pandasnail** [comment]
Instant yields I realize triple, but there's still the same per turn culture, isn't there? I mean, Monuments, Amphitheaters, Specialists, Chateaus, etc still give same per turn, there's just more turns. Also, certain comments on the forum here and there have made me think there's less production (relative to tech) on marathon than standard to build culture things, at least by the old rules. Literally never played a standard speed game to know for sure tho.

Does the UA affect the instant yields too? Didn't get any to test it out, and unfortch I'm now on a new game with the new version.

Now, yes, 12 turns of double would be an insane UA. But four feels lacking for a UA, and especially if its not instant yields too. Tho France does now have a second UA feature that's useful, so there is that, very good change getting rid of the theming bonuses imo.

**Comment by LoneGazebo** [comment]
We'll keep an eye on the value.

**Comment by pandasnail** [comment]
Since its wad, I'll close this and maybe bring it up at some point on the forum
