### ISSUE TITLE
Imperium Culture

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1468]
I can't find it in the Authority thread, but I was sure you said somewhere that the Imperium founding culture is still supposed to apply to the new city, but at least for me its applying to my capital.

**Comment by LoneGazebo** [comment]
Border growth applies to the new city, but the initial culture from founding applies in capital. This is because of how the function has to direct culture in a new city.

**Comment by pandasnail** [comment]
That's why I mean tho, border growth-every new city I put is giving Washington DC a new tile, not the new city.

**Comment by LoneGazebo** [comment]
You're referring to founding culture?  I fixed that in the hotfix.

**Comment by pandasnail** [comment]
Yeah, founding culture, that's what I said. Yay fixed!
