### ISSUE TITLE
Palazzo San Marco question

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1469]
Changelog says: Palazzo San Marco (replaces National Monument) - +2 Culture, Gold, Production, and Science.

But its really: +2 c f and p +1 s and c.

Not sure which its supposed to be.

**Comment by pandasnail** [comment]
Realized the culture is from the National Monument, so its just the science that's diff.

**Comment by pandasnail** [comment]
Err, no, confused myself there, culture, food, and science are all different. The first c should be gold. Good job, good effort self.

**Comment by LoneGazebo** [comment]
It is intentional – the changelog is the thing that is incorrect.
