### ISSUE TITLE
unit AI classes

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1471]
there's a long list of unit AI classes, which is largely ignored in the tactical AI. it decides what to do with a unit mostly based on its domain and whether it's a ranged unit.

so i was thinking about changing that. but i'm not so sure which classes are actually in use and whether they are assigned correctly.

do you have an easy way to get a list of unit and AI class from the database?

**Comment by LoneGazebo** [comment]
talking about UNITAI_X stuff?

**Comment by LoneGazebo** [comment]
That stuff is used quite heavily by the Homeland AI, GP AI, and the operational AI.

**Comment by ilteroi** [comment]
that is why i said tactical AI :)

**Comment by LoneGazebo** [comment]
You aren't planning on getting rid of it, but rather just not using it in the tactical AI, then?

**Comment by LoneGazebo** [comment]
The way that data is managed is actually in a table that is addressed via bool. Like this:
if(AI_getUnitAIType() == UNITAI_EXPLORE || AI_getUnitAIType() == UNITAI_EXPLORE_SEA).
You could grab the default unitAI, but that may not be the same AI the AI is currently using (as your exploration function changes this, for example, if a unit becomes an explorer).

I may be misunderstanding you. If so, my apologies.

**Comment by ilteroi** [comment]
on the contrary, i'm thinking about making use of this information in the tactical AI as well.

i know how to get the information in the DLL, but i don't feel like writing a lot of code to export it. is there an easy way to get the unit AI class for all units directly from the database?

**Comment by LoneGazebo** [comment]
Not that I know of, no. You could create a vector that is refreshed every turn and stores this data off for use throughout the tactical AI (have it run during the step in which units are recruited).

**Comment by ilteroi** [comment]
so i dumped some statistics, and it's interesting.

- unique units have a better price/performance ratio than their non-unique equivalents (good) but there is some variations among similar UUs (eg cossack vs hussar, legion vs maori) and some outliers (panzer not good, b17/zero almost too good).
- missile cruiser is rather expensive for its power, also it's classed as a ranged ship, but has RCS 0?
- bazooka / machine gun classed as defense, not ranged
- barbarian axeman has RCS 6, but is attack class - which is correct?
- marines are paratroopers? don't think so.
- there is no fast_ranged class, which is unfortunate
- classes attack/defense/counter are basically interchangeable

bonus image - perf/price ratio over era:
![image](https://cloud.githubusercontent.com/assets/1358966/13900315/8c2eaf3a-ee03-11e5-8ae9-9f10b7251515.png)

**Comment by LoneGazebo** [comment]
Settler production cost is set in a weird algorithm at the player level. Same for colonists and pioneers.
UUs are interesting, let's dig into that
Missile Cruiser should be melee
Bazooka and machine gun should both be ranged
Barb's are attack because of range 1, IIRC.
Marines are paratroopers in game, yep.
Yeah, it is unfortunate. Could use Counter for it.
Indeed, might be worthwhile borrowing counter for ranged melee.
