### ISSUE TITLE
paradrop and attack

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1472]
found this in the code: MOD_GLOBAL_PARATROOPS_MOVEMENT

it allows paratroopers to attack after dropping. that's a bad idea, AI wise. or conversely a big advantage for human players. i propose to remove it.

**Comment by LoneGazebo** [comment]
Well as long as it isn't enabled, it shouldn't hurt anything. If it is in the way, you can remove it, yep.

G

**Comment by ilteroi** [comment]
it's gone
