### ISSUE TITLE
Investment GameEvent

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1473]
I discovered - and it makes sense in hindsight - that CityConstructed doesn't register when a Building Investment is made. This causes a problem with my Charity belief in Piety, which awards Piety whenever a Building is purchased. I'd rather not disable this when Investments are active (as this is now the standard for my CID mod), so would it be possible to add a **GameEvents.CityInvested()** game event?

**Comment by LoneGazebo** [comment]
Add it within the investment function? Yeah. 

Oh, also, any interest in hooking into my 'doinstantyield' functionality at the player level? It is quite granular and there are a bunch of events you could trigger with it. Yields for CS bullying, yields for founding, yields for passing a WC proposal, etc.

**Comment by JFDaly** [comment]
Yup, to register whenever a player invests in a Building. Thanks!

I don't think the 'doinstantyields' would be any use for my yields. Piety is the only one that functions as an accumulated Yield like Faith or Culture, but, while there are 'on settle', 'on combat', etc. conditions, the Piety you get scales by how much Piety you have in total.

**Comment by LoneGazebo** [comment]
Sounds good. If this changes, let me know.
