### ISSUE TITLE
Stone revealed from the start?

### ISSUE THREAD

**Issue by cosmosgu** [LoneGazebo/Community-Patch-DLL#1474]
If I remember it correctly the only non-luxury resource that is revealed from the start is wheat: because you can build farm from the start. Yet in my recent game with CBP modpack (3/9/) stone is revealed from the start as well. Is this intended?

**Comment by LoneGazebo** [comment]
No - might be a custom civ or another mod you're running.

**Comment by cosmosgu** [comment]
@LoneGazebo CBP is the only modpack I used and I deleted my cache and moduserdata before copying it into my DLC folder.
I should have the save file from turn 1. I will load it some point later today and see if I can replicate it.

**Comment by cosmosgu** [comment]
@LoneGazebo I found the problem. Stone is revealed by researching "Mining", but in CBP "construction" is needed to construct a quarry on it.
The revealing of stone should be moved from mining to construction.

**Comment by LoneGazebo** [comment]
It's intentional, as revealing the stone gives you the base production bonus (indicating that you are using the stones, but the quarry is maximizing your use).

**Comment by cosmosgu** [comment]
@LoneGazebo Okay. Sounds slightly inconsistent with the rest of CBP (from my perspective the same argument can be made with all other resources that are hidden at first). Thanks for the reply and clarification.

**Comment by LoneGazebo** [comment]
Stone is different because stone doesn't require a tool (at first) to use - it is the tool. Unlike, say, fish.

**Comment by cosmosgu** [comment]
@LoneGazebo I am no expert of ancient history or game balance. But if stone does not require a tool to use (which makes perfect sense: similarly you get production from a plain hill with no improvement), then why do you need to research mining in order to see it?
I think both revealing it with agriculture (you don't need the tool to use it) and construction (revealing comes with improvement) make sense. Revealing it in a half-way technology is rather counter-intuitive.

**Comment by LoneGazebo** [comment]
It gives an incentive to research mining.

**Comment by cosmosgu** [comment]
@LoneGazebo Alright.
As a side note from my observation stone is rarely generated by the map script CBP used. For all the matches I played on CBP stone is consistently the least generated of all bonus resources, which also makes it much less lucrative to build stone works.

**Comment by LoneGazebo** [comment]
Communitas is an older map script that was made by a no-longer-active user. Most people prefer the PerfectWorld scripts now, I believe. I keep it there only out of request from some users.

**Comment by cosmosgu** [comment]
@LoneGazebo I am not aware that the map script of CBP is actually someone else's work! Thanks for the clarification.

**Comment by LoneGazebo** [comment]
Yep, I edited it to include Bison, but that's really it.

**Comment by cosmosgu** [comment]
@LoneGazebo Got it. Thanks.
