### ISSUE TITLE
Garrison killed

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1475]
My city was bombarded and my garrision died. I'll add a save from which the position of the killed unit can be confirmed.
[I don`t even.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/180827/I.don.t.even.zip)

**Comment by ilteroi** [comment]
what exactly is your complaint here? that's by design!

**Comment by Der-Zorn-Gottes** [comment]
Wait I think the design is that garrisons can't be killed any more? Was it reverted back?

**Comment by ilteroi** [comment]
yeah, there were complaints.

so now the strategy is that the AI should be smart enough not to re-garrison a city which is about to be captured.
