### ISSUE TITLE
Maya UA not starting at Calendar

### ISSUE THREAD

**Issue by goplaysoccer13** [LoneGazebo/Community-Patch-DLL#1476]
1000 years passed after researching Calendar and no Great people have been given to me.

**Comment by LoneGazebo** [comment]
Did your calendar update to the Long Count? In any case I think the Maya UA starts at Mathematics now, not Calendar.

**Comment by goplaysoccer13** [comment]
It did not update to the long count. In the google doc though with all of the changes to unique abilities and such, it stated that it should start at Calendar. The google doc should be updated to reflect that if it was changed

**Comment by LoneGazebo** [comment]
Did you not read the in-game UA, though?
