### ISSUE TITLE
Weird bugs with CP (v. 76) and CBP (v. 13) only

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1477]
Hi. I am using the most up-to-date code from the repository (from what Git says) and when I go to play CP and CBP together I get the following issues. The pictures are rather self-explanatory (except for the diplo screen one - City States are invoking major civ greetings when I just "refresh all" in FireTuner.

http://imgur.com/a/4nhU0

No save file needed, this occurs when I load up a new game in the Atomic Era (probably others).

**Comment by LoneGazebo** [comment]
Are you deleting the proper lua folders?

**Comment by mwhiter** [comment]
Why would I have to delete any Lua folders? I'm a bit confused on that.

**Comment by TechpriestEnginseer** [comment]
Say you have two UnitPanel.lua. One UnitPanel.lua is from some other custom civ mod and one is from the Community Patch. Apparently, both of these aren't even similar but yet they occupy the same file system. So, one will overwrite another. However this overwrite is critical to the stability of the game because if the custom civ is overwriting the CP's UnitPanel.lua then you could have issues with loading up your unit interface. 

This is why Gazebo made an installer, since people are "forgetful" in their deletion of LUA folders.

**Comment by mwhiter** [comment]
This shouldn't be an issue, though. The only mods enabled are Community Patch, and Community Balance Patch. Since Community Patch is a dependency of Community Balance Patch, the load order is clearly Community Patch, then Community Balance Patch, so Community Balance Patch's Lua files should be overwriting Community Patch's Lua files.

Also - there is no mention of what Lua folders need to be deleted and what doesn't. Everything in my repo is from the Github repository + three additional files (CorporationsOverview.lua, CorporationsOverview.xml, and the CorporationsText, none of which are files that ever existed outside of the mod.

So the GitHub code is out of date, improper, or something is TERRIBLY wrong locally, but the code repository was reset to the master version.

**Comment by LoneGazebo** [comment]
Unfortunately that's not how lua load order works. Lua load order can be messed up based on the order of the folders being added to the mods folder! I've done a lot of testing on this. It's crazy, but true.

If you are using the CP + CBP, delete the CP's lua folder. The CBP has all you need.

**Comment by mwhiter** [comment]
That is very frustrating. Alright then, I'll move it out when I'm ready to develop the Corps again (should be after I finish my regression testing).

**Comment by mwhiter** [comment]
Deleting the Lua folder in Community Patch did not solve the issue. i can investigate why it's not locating the IconString.

**Comment by LoneGazebo** [comment]
That's odd, not sure what's going on. Getting bugs in your database log?

**Comment by qqqbbb** [comment]
My tech tree looks like that too. No errors in database log. Where can I get older versions to figure out what broke it?

**Comment by mwhiter** [comment]
I'll investigate this when I get home today, if it's not too late. Maybe there's a weird XML issue when IconString is missing, if that's even an XML column. I'll need to investigate further.

**Comment by mwhiter** [comment]
It's also worth noting that I didn't see this issue when I was running with CP,  CBP, C4DF, CSD, CBP-CF mods on my C4DF-dev branch.  Only with CP and CBP.

**Comment by LoneGazebo** [comment]
I'll double-check that the techbuttons for CBP and CBP-compatibility are the same - may be an issue with a value not properly loading.

**Comment by mwhiter** [comment]
CBP:

`thisButton:SetToolTipString( Locale.ConvertTextKey("TXT_KEY_SPECIALIST_YIELD_CHANGE", GameInfo.Specialists[row.SpecialistType].Description , GameInfo.Yields[row.YieldType].Description, row.Yield, Locale.ConvertTextKey(row.IconString)));`

CBP Non-EUI:

`thisButton:SetToolTipString( Locale.ConvertTextKey("TXT_KEY_SPECIALIST_YIELD_CHANGE", GameInfo.Specialists[row.SpecialistType].Description , GameInfo.Yields[row.YieldType].Description, row.Yield, Locale.ConvertTextKey(GameInfo.Yields[row.YieldType].IconString)));`

I'll fix it.

**Comment by mwhiter** [comment]
Tested in game. All issues fixed with new code.

**Comment by LoneGazebo** [comment]
Cool, must've been an oversight, thanks!
