### ISSUE TITLE
Compatbility Oddities

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1478]
Hi,

Going through the compatibility files for Non-EUI and EUI, I noticed some weird things with C4DF and compatibility...

1) I have a pl_PL folder in C4DF Compatibility AND C4DF CBP. That doesn't seem to make sense. I deleted it. C4DF CBP will host a pl_PL folder with the most updated translations.
2) Conflict for GAME_CONCEPT_SECTION_26 with C4DF and CBP. I can do one of two things: Add a Replace tag for GAME_CONCEPT_SECTION_26 on C4DF (which I have done and am testing now), or just don't modify Corporation's tag, and move C4DF to GAME_CONCEPT_SECTION_27 for CBP only.
3) Not sure why pl_PL has its own separate compatibility text file.

What's up with this? How can we repair this to make it sensible?

**Comment by LoneGazebo** [comment]
The conflict for those sections goes away when it is updated in the compatibility file.
The pl_PL existed because I had no way to update the (4) C4DF mod.

**Comment by mwhiter** [comment]
Okay. Well now that's changed so this shouldn't be a problem anymore. pl_PL changes will go in the respective C4DF mods now.
