### ISSUE TITLE
Huns treat battering rams as ordinary land units.

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#148]
They try to use them to defend their cities.

**Comment by LoneGazebo** [comment]
I'll look at it, but this was behavior in BNW as well. I might simply give rams the ability to attack units, but at a penalty, to prevent the AI from being too dumb with them.
G

**Comment by qqqbbb** [comment]
How about this: they build battering rams only when there is a weak neighbour and sell them when they are attacked by a strong neighbour?

**Comment by LoneGazebo** [comment]
There's no easy way to code that, unfortunately.
G
