### ISSUE TITLE
Thanks for the settler, Hanoi!

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1481]
![image](https://cloud.githubusercontent.com/assets/13937047/13906844/25a028ca-ee9e-11e5-9794-614c783431bd.png)
Venetians shouldn't be getting settlers.

**Comment by LoneGazebo** [comment]
How?

**Comment by TechpriestEnginseer** [comment]
By being an ally of Hanoi, I presume.

**Comment by LoneGazebo** [comment]
But why did Hanoi give a civilian? That makes no sense.

**Comment by TechpriestEnginseer** [comment]
*shrug*

**Comment by LoneGazebo** [comment]
Shrug indeed.
