### ISSUE TITLE
mongol terror

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1482]
i'm playing as the mongols, and their heavy skirmishers are indeed the mongol terror. you might want to tone that +2 movement down to +1 ;)

**Comment by LoneGazebo** [comment]
You think? I like it. Terrifying.

**Comment by ilteroi** [comment]
ok then!

**Comment by LoneGazebo** [comment]
I mean, it is pretty much all they have...
