### ISSUE TITLE
Naval ranged units cannot fire whilst inside a friendly city

### ISSUE THREAD

**Issue by cosmosgu** [LoneGazebo/Community-Patch-DLL#1483]
Is this a new change or a bug? I searched through the Google Doc but cannot find it being mentioned.
CBP 3/9. No other mod.

**Comment by LoneGazebo** [comment]
It's a bugfix. Was in previous patch.

**Comment by cosmosgu** [comment]
@LoneGazebo Thanks!
Also, is there a real "unified changelog" somewhere? The "unified changelog" thread (to be accurate the Google Doc it leads to) in the forum is more a summary of the current status of mod than a changelog.

**Comment by LoneGazebo** [comment]
It's the most accurate we have, someone else keeps it updated for me. There's also the wiki (see my signature on civfanatics for the link, I don't have it at present).

**Comment by cosmosgu** [comment]
@LoneGazebo Thanks! I am aware of the wikia and the google doc. What I am looking for is a more traditional "changelog" (what was changed from the previous versions). Since CBP updates rather frequently I find it really hard to locate each individual release threads. It would be awesome if there were a single thread detailing the changes of each release.

**Comment by LoneGazebo** [comment]
I make a changelog for every new version on the subforum. They're all labeled by date, so it should be easy to find them.

**Comment by cosmosgu** [comment]
@LoneGazebo Yes..This is also the method I am using..
Little suggestion: When you are posting a new thread could you name them all "version" (to make it easier for searching)? The latest release (3/18) is named "hotfix" and in the future it might be really easy to miss this release.

**Comment by LoneGazebo** [comment]
Well, but it was - technically - a hotfix.

**Comment by cosmosgu** [comment]
@LoneGazebo I just realized that since all version are released by you, I can simply search for all posts made by you to find all release notes. So yes no need to worry about thread naming. :)
