### ISSUE TITLE
Ger gives science on border growth

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1484]
I don't think this is mentioned in the ger's description/tooltip, but apparently every time borders grow in a city with a ger, it receives 10 science that scales with era.

**Comment by TechpriestEnginseer** [comment]
It's not this easy to make an accident like that. I think it just needs a tooltip update.
![image](https://cloud.githubusercontent.com/assets/13937047/13910381/768df4f2-eede-11e5-8cf9-0210c857be99.png)

**Comment by LoneGazebo** [comment]
It shouldn't have that bonus anymore.

G

**Comment by LoneGazebo** [comment]
I'll fix.
