### ISSUE TITLE
Pathfinder Quirk

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1485]
http://forums.civfanatics.com/showpost.php?p=14207934&postcount=71

This is a bug I've been experiencing for the last several couple of versions - I don't know if it's you or Ilteroi who's working on this, but whenever I have a unit moving in foreign territory, moving the unit through a foreign city will consume all its movement when it exits the city. Here's a screenshot showing what I'm talking about - the unit stops when exiting Berlin, even though it should move several more hexes since all tiles have road.

Another movement issue which is not exactly a bug but rather an optimization issue, but still very annoying is the fact that a unit will walk off a road if it can't consume all its movement on a road because the tile it can reach on the current turn is occupied. This means the unit will use a full movement point moving back on the road on the next turn, causing it to reach its destination later than it would have, had it instead forfeit the last part of its movement on the turn before.

**Comment by ilteroi** [comment]
i think i know the reason.

it's a bit tricky though, don't really understand why that particular piece of code is even there.

so should i remove it or should i patch it up? hmm

**Comment by LoneGazebo** [comment]
Which piece of code? Is it something you wrote, or something Firaxis did?

**Comment by ilteroi** [comment]
just joking. original firaxis, later adapted by me. don't think it's really needed but i won't take any risks, it's harmless.

anyway, the function called is CvPlot::isValidDomainForLocation()

for the fix replace the existing case with

	case DOMAIN_LAND:
		return !isCity() || (isCity() && IsFriendlyTerritory(unit.getOwner()));
		break;

that should do it.

**Comment by LoneGazebo** [comment]
Hmm...will that cause a problem? Could be a real problem for war (instant-steal a city).

**Comment by ilteroi** [comment]
just checked, that case is caught in canMoveInto(). looking good

**Comment by LoneGazebo** [comment]
:dancer:

**Comment by ilteroi** [comment]
ah well. slept over it. maybe that fix will not help the missionary because it doesn't need open borders. needs further changes.

**Comment by LoneGazebo** [comment]
Take your time, no worries.

**Comment by ilteroi** [comment]
ah well, wasn't there a discussion recently whether civilian should be able to enter enemy territory at all? what was the verdict? might be a good time fix that too. needs an exception for generals though, so it isn't straightforward either.

**Comment by LoneGazebo** [comment]
It was an issue with Great Musicians, and I settled by giving it the rival territory promotion, same as missionaries.

**Comment by ilteroi** [comment]
that was quick :)

anyway this is the fix for the missionaries

	case DOMAIN_LAND:
		return !isCity() || (isCity() && (IsFriendlyTerritory(unit.getOwner()) || unit.isRivalTerritory()) );
		break;

**Comment by LoneGazebo** [comment]
Makes sense to me. Might be worthwhile to throw the  'use rival roads' one in there as well.

**Comment by ilteroi** [comment]
that's already handled in CvPlot::isValidRoute()

**Comment by LoneGazebo** [comment]
It'll cover the event of passing through a city? I guess, though, you wouldn't be passing through a city anyways if at war, so nevermind...

**Comment by ilteroi** [comment]
yeah it's not really logical, first we check whether the move would end the turn. if it doesn't we calculate the cost. non-owned city failed the first check, route or no route is handled in the second.

**Comment by LoneGazebo** [comment]
Sounds functional enough to me!
