### ISSUE TITLE
assorted bug complaints

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1487]
Things mentioned either in 3/18 thread or bug reports thread, I'll come back and do the other threads in a bit

CS allies still not included in peace deals automatically at least.
AI criticism of proposals when there was no proposal by the user. 
Venetian merchant apparently can be purchased through faith by other civs? no other detail provided, so I'm not confident it isn't some other mod or something 
Something about tourism not showing the right numbers, kinda confused me. You responded to this one, so I figure you have it handled.
People other me are having trade deals end in -1 turn duration, and stay forever. Don't know if you remember my post on that, but everything I hoped would make that go away didn't, whether disabling human vassalage or quitting eui. Since it seems like not everyone, I imagine its a hard fix, and all I can give you is this lua error I got one time, playing with EUI. (Without EUI, nothing even appeared in the lua log): [51538.421] NotificationPanel: Cannot restore deal trade	3	100	309	33	1	0	false	0

**Comment by pandasnail** [comment]
Looking thru the other threads, all I found is one user saying that their corporations vanish or self destruct every few turns

**Comment by LoneGazebo** [comment]
The trade issue sounds like an EUI bug, but I cant' reproduce it easily.

**Comment by LoneGazebo** [comment]
I'll take a look at others. I  think MoV issue was with GP spawning from CSs.

**Comment by pandasnail** [comment]
Playing a game without EUI, and I'm still getting a couple of those weird deals. Or does EUI somehow leave residue in the install itself somehow even deleting cache and all that? I guess that could be it if so..

I realize that if its not happening for you, you really can't diagnose it, and yeah, all I can give is those random looking numbers from above, or other complete guesses I've had.

Also, you probably saw it, but Funak says he's getting too many votes from having the World Religion.

**Comment by LoneGazebo** [comment]
It can, yeah. I'll keep an eye out for it, and I'll ask other players to look at it too.

**Comment by LoneGazebo** [comment]
Thanks for compiling this, huge help!
