### ISSUE TITLE
Question on curious in CvCityCitizens.cpp

### ISSUE THREAD

**Issue by Pusperk** [LoneGazebo/Community-Patch-DLL#1488]
Me bad work focus in city. i look into code and i do not understand this code in CvCityCitizens.cpp in function DoAddBestCitizenFromUnassigned
`
int iPotentialExcessTimes100 = m_pCity->getYieldRateTimes100(YIELD_FOOD, false) - (m_pCity->foodConsumption(false, 1) * 100);`

This function `getYieldRateTimes100(YIELD_FOOD, false)` return excess food in city (with third parameter automatic on true)
and
this function `foodConsumption(false, 1)` return food consuption in city including city plot (city plot has not food consuption)
Result is negative (example 3 population, total food in city 6, excess food 200 from function `getYieldRateTimes100(YIELD_FOOD, false)` , consuption 600 from function `foodConsumption(false, 1) * 100` result iPotentialExcessTimes100 = -400). 
If first function return excess food in city then second function is bad or first function has bad third parameter (would be false) and second function would be with second parameter 0 (consuption without city plot). Maybe.

**Comment by LoneGazebo** [comment]
I'm not exactly sure I understand – the functions you posted above are identical.

**Comment by Pusperk** [comment]
Result iPotentislExcessTimes100 give bad value

**Comment by LoneGazebo** [comment]
So your concern is that 'foodConumption' is counting as consuming food for the city plot, when it shouldn't?

**Comment by Pusperk** [comment]
Must be foodConsumption(false, 0) not 1

**Comment by LoneGazebo** [comment]
Oh I see your problem. The '1' in that value is intentional, though. It gives the consumption based on what the consumption will look like if the Citizen works a plot with zero food. This keeps the AI from stagnating its cities.

**Comment by Pusperk** [comment]
Then any specialist will be add into buidling because iPotentislExcessTimes100  is negatice always

**Comment by Pusperk** [comment]
Hmm i have bad value in StaticYield for food  i do test why

**Comment by Pusperk** [comment]
Hmm I understand why i have bad value in StaticYield . Before system call function  DoAddBestCitizenFromUnassigned so remove all population from worked plot. StaticYield are recount and call  function getYieldRateTimes100(YIELD_FOOD, false) get bad value.

**Comment by LoneGazebo** [comment]
But if there aren't any people working plots, then the value will always start out at negative. After the first citizen or two are assigned, though, the value should update.

**Comment by Pusperk** [comment]
Clear yet. Would be good do not count city plot into consuption only.

**Comment by LoneGazebo** [comment]
I'll check.

**Comment by Pusperk** [comment]
Thanks for help

**Comment by LoneGazebo** [comment]
I've checked function, and all is working as intended. Keep in mind that, the 'DoAddBestCitizenFromUnassigned' is generally called when all citizens are being re-evaluated. Thus, the first few calls are guaranteed to be negative (as, at that point, very few citizens in the city are being used at all). After the first citizen or two, though, the number becomes positive (the city is no longer starving itself), and then the function works normally.
