### ISSUE TITLE
Stele/Triumphal Arch Culture is still 2

### ISSUE THREAD

**Issue by theunholypotato** [LoneGazebo/Community-Patch-DLL#149]
They're even stronger now, as they also provide the increased tile spread from the baseline monument. This is true as of the 3/6 patch.

Edit: full mod suite. CEP+CBP+E&D+C4D+CSD+EUI

**Comment by LoneGazebo** [comment]
Thanks for this. I'll fix this in the next version.
G

**Comment by theunholypotato** [comment]
Excellent. Take care, Gazebo.

**Comment by powder0321** [comment]
Taking it down to 1? Nooooooo. This was an excellent reason to go might with Rome and grab the bonuses from tile expansion. Considering some of the other unique building bonuses in the game, like the Hansa providing a 30 to 40 percent production boost, by the time it comes around, the bazaar adding 3 faith per city, or the Mayan pyramid adding extra faith and science, I hardly think adding one extra culture per city to Rome and Ethiopia gives an unfair advantage.

**Comment by LoneGazebo** [comment]
An additional yield right off the bat (faith for Ethiopia, production for Rome) is bonus enough. +2 culture throws off the early game culture growth too much.
G

**Comment by powder0321** [comment]
I would point out that social policies can add quite a bit more culture (particularly with tradition) than the +1 to the monument yield to early game culture. But this may not be the place for this discussion so I'll leave it at that.
