### ISSUE TITLE
Provide a switch to allow easy "flipping" of GameOptions for RAs and Tech Trading

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1491]
Low priority.

Provide a switch to allow anyone to flip RAs and Tech Trading around for CPP. This should be an SQL setting. When enabled, "No Tech Trading" becomes "Tech Trading" and "Enable Research Agreements" becomes "No Research Agreements".

**Comment by Iamblichos** [comment]
Would be a nice to have at this point, but don't think this is necessary. ??

**Comment by LoneGazebo** [comment]
Agreed. Let's close.
