### ISSUE TITLE
Council of Elders (3/23 beta)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#1496]
`Receive a boost to current Science research when a city adopts your Religion.`

Council of Elders doesn't trigger tech boost except for a Holy city.

Active mods:
(1) Community Patch
(2) Community Balance Patch
(3) CSD for CBP
(4) Civilization IV Diplomatic Features - Community Balance Patch
(5) More Luxuries
(6a) Community Balance Patch - Compatibility Files (EUI)
EUI
Ingame Editor

Here is a save data for testing.
https://www.dropbox.com/s/f275eymk3urvnv3/Alexander_0002%20BC-3920.zip?dl=0

**Comment by LoneGazebo** [comment]
When the city adopts your religion, you get the boost in your Holy City.

**Comment by 8h42** [comment]
When I founded a religion, my Holy City received 40 science.
When I converted my 2nd city, I did not receive any science.

![1](https://cloud.githubusercontent.com/assets/11933188/14020892/76b619aa-f21c-11e5-8f67-e6476fc473a2.png)
![2](https://cloud.githubusercontent.com/assets/11933188/14020899/7ec0e954-f21c-11e5-9de5-4d11d79018e3.png)

**Comment by LoneGazebo** [comment]
I'll take a look.
