### ISSUE TITLE
VMC v77

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1497]
Just wanted to draw your attention to [DLL - Various Mod Components v77] (http://forums.civfanatics.com/showpost.php?p=14210926&postcount=1523) and ask whether or not the CP DLL can be updated (sometime) for it.

The 'Dummy Policy' switch is obviously already accounted for, but those player:GrantPolicy()/RevokePolicy()/SwapPolicy() sound ripe for how Sovereignty handles Reforms.

You may already have plans to update for v77, but it would be great in any case - though there's no pressing need atm, as Sovereignty is behind other priorities for me.

Thanks!

**Comment by LoneGazebo** [comment]
Yeah, I'll definitely be updating to v77 soon enough.

**Comment by Iamblichos** [comment]
You want me to handle that G?

**Comment by LoneGazebo** [comment]
I've done it :)

**Comment by TechpriestEnginseer** [comment]
So this fixes the dummy policies issue?

**Comment by LoneGazebo** [comment]
No, it does not. Hey @TechpriestEnginseer, check your PM on civfanatics :)

**Comment by JFDaly** [comment]
Oh, and will this include the Max HP moddability, too? I would very much like to make use of that.

**Comment by LoneGazebo** [comment]
Yep.

**Comment by Iamblichos** [comment]
It also look like Mr. Howard has corrected some things to vmc v77, v79 is up. Might want to note those.

**Comment by LoneGazebo** [comment]
Gah
