### ISSUE TITLE
EUI-Firetuner Issue

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1498]
Whoward passed along a fix to the Firetuner issue, preventing you from placing Improvements (I think it prevented access to the whole Map tab). I'm not sure if you're aware of it, but [here](https://www.dropbox.com/s/7kz1ts4ex83wh5b/WorldView.lua?dl=0) is the replacement WorldView with the fix incorporated in case.

CBP doesn't appear to replace the WorldView for any reason, but to save you headaches, it might be worthwhile doing so - not sure when/if bc1 will fix the issue on his end.

**Comment by LoneGazebo** [comment]
Yeah, he sent it my way via PM, and then I to you via PM! :)

G

**Comment by JFDaly** [comment]
Oh, sorry - forgot :p

**Comment by LoneGazebo** [comment]
No worries!
