### ISSUE TITLE
Traded resources sometimes don't refresh 

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1499]
http://forums.civfanatics.com/showpost.php?p=14207009&postcount=4815
http://forums.civfanatics.com/showpost.php?p=14212208&postcount=4823

tl;dr: when trading resources, sometimes you won't get the resource you'd been giving away back after the deal has ended, and sometimes the resources you've just traded will still be shown as available to trade. 

If I had to make my uneducated guess, I'd say that some sort of cache isn't being properly reset.

**Comment by LoneGazebo** [comment]
Which version?

**Comment by Edaka** [comment]
I myself am currently experiencing this on the 3/12 version, IIRC. Have you secretly worked on this ever since? In that case I'm sorry.

 I've asked the two other posters about their versions. However, one of them posted on 3/25 and said something along the lines of 'hope this gets fixed on the next version', so he might be up to date.

**Comment by LoneGazebo** [comment]
I haven't looked at it, honestly, as I don't touch the deal caching much. JdH worked on it some, and that may be the bug.

G

**Comment by LoneGazebo** [comment]
@Iamblichos , @ilteroi , @mwhiter ,

I'm calling in the troops on this one. This is something that has been a problem (off and on) for some time, but I can't seem to find the source. If any of you have interest in helping debug, I'd be thrilled.

**Comment by Iamblichos** [comment]
Will work on it this weekend.

**Comment by LoneGazebo** [comment]
Thanks, @Iamblichos. I've poured over the stuff multiple times, but can't pin down the culprit.

**Comment by Iamblichos** [comment]
First question, has anybody been able to reproduce this problem as of late?

**Comment by mwhiter** [comment]
I am juggling alot this weekend, but I can take a look if someone can reproduce it and post a save.

**Comment by LoneGazebo** [comment]
@Iamblichos , there are a couple of links in the bug reports thread from today and this past week.

**Comment by Iamblichos** [comment]
I see their posts now. Can't say that I've experienced this yet. (won't be til sunday that I can examine code). Has any of the Code Team been able to reproduce?

**Comment by LoneGazebo** [comment]
I have not, nope. And you're code team too! :)

**Comment by Iamblichos** [comment]
Yes, yes, the royal "we"...!

**Comment by LoneGazebo** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/1514

**Comment by Iamblichos** [comment]
Okay I reproduced this with EUI, I'm looking over the deal stuff and dimplamcy request ai and I can't tell where the hell this is coming from, nothing sticks out as really wrong. Anybody, reproduce without EUI?

**Comment by LoneGazebo** [comment]
That's my fear, that EUI is causing it. Could be an inconsistency with EUI and the tradelogic of EUI-CBP, which would mean that bc1's rewritten the trade logic such that it isn't compatible with vanilla code.

**Comment by Iamblichos** [comment]
I did comparisons of code all day yesterday (sometimes that's the best way to find a culprit), between CP, VMC, and Vanilla, and couldn't find anything that looked wrong. Going to see if I can reproduce without EUI, if not I'll dig into his trade logic lua and see if I can find it. This is definitely a needle in the haystack type of issue.

**Comment by Iamblichos** [comment]
BTW--the tradelogic.lua of the CBP-comp is vastly different than the EUI, I expect them to be different but I wasn't expecting them to be as different as they are. The CBP-comp doesn't even look like it is of a common code base.

**Comment by LoneGazebo** [comment]
It isn't. Or rather, it stems from a much earlier version of EUI. Still uses the same core functionality as the base game though.

**Comment by Iamblichos** [comment]
Okay, I cannot reproduce this without EUI, so I think it's safe to say that we have an EUI bug on our hands.

**Comment by Iamblichos** [comment]
Woops, take that back, just reproduced it....dang!

**Comment by WirelessKFC** [comment]
Some conditions that make the bug occur

last copy of resources are traded and whilst the trade is still on going the resource is lost (pillaged, land stolen, city lost). this should cancel the deal but sometimes the deal goes on and when duration finishes the bug occurs

**Comment by Iamblichos** [comment]
Yeah I see that, it's as if the resource no longer exists in the game.

**Comment by LoneGazebo** [comment]
JdH just pushed a new version of his active diplomacy stuff. @Iamblichos , since you are currently digging into this (and his code deals with a lot of deal related stuff), would you mind taking point on incorporating it into the CP? Most, if not all, should replace active_diplomacy code where I've already added it, so it shouldn't be too bad.

**Comment by LoneGazebo** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/pull/1519#issuecomment-203028317

**Comment by Iamblichos** [comment]
Absolutely, you want me to just merge his changes into my branch and then commit and merge my branch into CP?

**Comment by LoneGazebo** [comment]
Works for me. I hope we can sort out this deal issue, it's a deal-breaker (ha) right now, and frustratingly so! Thanks for taking this on, merges can be...less than fun.

**Comment by Iamblichos** [comment]
Okay, I got a hunch it's the changes he's made previously. It seems that error cropped up when he made his additions a couple weeks back.

**Comment by LoneGazebo** [comment]
Sounds good. Let's hope!

**Comment by Iamblichos** [comment]
Pullrequest created.

**Comment by LoneGazebo** [comment]
Awesome. Did the changes solve the issue?

**Comment by Iamblichos** [comment]
I can't say for sure yet. Need a full play through up to probably Renaissance to tell. I think we should proceed with release.

**Comment by Iamblichos** [comment]
Or if you want to wait, I can do a game tomorrow morning and test.

**Comment by LoneGazebo** [comment]
I've integrated the changes, as well as VMC 77-79. You can see the changes in the Alpha I just posted. Also note that the new CP:Events system is active in this Alpha. JFD and I are testing it. To disable, turn off 'BALANCE_CORE_EVENTS' in the CustomModOptions.xml file. This is a really exciting new feature, but isn't ready for primetime quite yet. :)

**Comment by LoneGazebo** [comment]
Marking fixed, until otherwise noted.

**Comment by Iamblichos** [comment]
Wow fascinating! Nice! Did JFD do a lot of this work for the Events?

**Comment by LoneGazebo** [comment]
No, it's all me. We've been going back and forth on it in terms of what should be included, but the DLL stuff is of my invention.

**Comment by Iamblichos** [comment]
Busy little bee!

**Comment by LoneGazebo** [comment]
Indeedily. Code seems fairly efficient, though I'm considering reworking the struct model for events/cityevents/eventchoices/cityeventchoices to borrow off of one 'parent' to save some memory overhead. Wouldn't be huge, though, so I'm not sure if it would be worth it. Looking at the cvinfos.cpp, what do you think?

**Comment by Iamblichos** [comment]
Let me try out a game and see how it flows. I kinda doubt it'll take that big of a hit. Lots of potential here though. You can finally incorporate your disaster events in game.

**Comment by LoneGazebo** [comment]
Yep! That's part of my eventual plan, actually. If I could strong-arm someone into making me a Sectoid 3d model for Civ...I'd totally add in an XCOM scenario in the end-game. :dancer:

**Comment by LoneGazebo** [comment]
There's only a couple of sample events in place right now, and they're designed to fire almost instantly (for testing purposes). Mainly I'm trying to find ways to cut back on stored memory overhead, as I imagine there will end up being over 100 instant events, and 100 choice events (not to mention events made by other players) once all is said and done.

The events XML is dead-simple to use. If you have any interest at all, making events is really easy.

**Comment by Iamblichos** [comment]
No doubt this is badass, we can even add some historical ones.

**Comment by LoneGazebo** [comment]
Indeed – it supports civ-specific events, so we can make some fun historical-scenario events this way. JFD's already converting his events over, but I haven't heard back from @TechpriestEnginseer.

**Comment by Iamblichos** [comment]
Eruption of theira, Santirini, -> Egyptian plagues, etc.

**Comment by LoneGazebo** [comment]
Yep! Look through the gameevents xml table, see if there are some elements missing that would facilitate what you envision. We can start brainstorming on that.

**Comment by Iamblichos** [comment]
What do you think about an event that is triggered via warscore (or something similar), where you can get a Hero unit, an Achilles or Thutmosis III

**Comment by LoneGazebo** [comment]
Hmm...There's an 'atwar' trigger already, could make it require a certain amount of stored culture or golden age points in order to spawn. Or perhaps it can only happen in an occupied city in resistance (i.e. recently conquered). A la:

"A warrior has distinguished himself in recent battles."

**Comment by Iamblichos** [comment]
Let's move to a new thread and we can begin cataloging what we'd like!

**Comment by LoneGazebo** [comment]
Sounds good.

**Comment by TechpriestEnginseer** [comment]
I'm atm moving most of Sukritact's Events over to our events.

**Comment by LoneGazebo** [comment]
Any update on this, @Iamblichos ? Did the fix work?

**Comment by Iamblichos** [comment]
I haven't reproduced yet.

**Comment by LoneGazebo** [comment]
That's...good, I guess. :)

**Comment by Iamblichos** [comment]
Since we haven't ever figured out exactly which function this is coming from, that's all I have to go on for now :/

**Comment by Iamblichos** [comment]
Bad news: it's still there.

**Comment by LoneGazebo** [comment]
Drat.

**Comment by J-d-H** [comment]
I'll also have a look into it while improving my MP Diplomacy code.

**Comment by LoneGazebo** [comment]
Thanks JDH.
