### ISSUE TITLE
No theming bonuses in 3/6, cavalry unlocked without lancers

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#150]
http://i.imgur.com/nCz3SnX.jpg

Pretty straightforward, theming bonuses aren't being applied.

Also (not really a bug) but I noticed cavalry can be unlocked without needing lancers. Figured I'd mention in case.

http://i.imgur.com/ddRMTu5.jpg

**Comment by LoneGazebo** [comment]
I'll take care of this.
G
