### ISSUE TITLE
Double attack on mounted archery units doesn't deplete all movement points

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1500]
Is it supposed to, anyway? Ships have their leftover movement depleted - haven't tested that lately, but that's how it's supposed to work - but my experience with heavy skirmishers has shown that they don't. Considering their mobility isn't any worse than the ships', I think they should be treated the same way.

**Comment by LoneGazebo** [comment]
They don't because of rough terrain. This is more of a balance question, though.

**Comment by Edaka** [comment]
Oh, I see. If it's WAD, then it's not as significant. In the end, I was playing as the Mongols when I noticed that, so that's why it seemed really powerful. (:
