### ISSUE TITLE
Imperium's scaling with city size

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1501]
Don't know if you've looked at this one already. Basically, conquering ~20 pop cities in classical era stlil gives 30 culture and 30 science. Doesn't seem to be affected by population, or the amount it scales off is too high.

**Comment by LoneGazebo** [comment]
I'll take a look.

**Comment by Hokath** [comment]
Yeah I saw this too, forgot to open bug report.

**Comment by LoneGazebo** [comment]
Code looks fine to me.

**Comment by Edaka** [comment]
Seeing the label, I'm curious if you eventually found a bug or if you simply made the conversion ratio more significant.
