### ISSUE TITLE
Can AI stop razing cities midway through?

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1502]
In my experience, every time AI decides to raze a city, it burns it to the ground completely, be it a 5 pop or a 30 pop one. Am I right assuming that the major deciding factor to make AI start razing is how unhappy they are? It seems to me that they can start razing when they're very unhappy, then have their  happiness recuperate, but that won't stop them from burning perfectly fine cities.

Example: France starts steamrolling Arabia, taking one city after another. While France's happiness is acceptable, it puppets/annexes all cities, regardless of size and location. However, once France has taken too much, it just starts razing every consequential city with high pop, luxuries, great person improvements etc. Then, having reduced cities that are being razed in pop significantly, France's happiness goes back to normal, but she still wipes rather decent cities off the Earth (the ones she has started razing).

**Comment by LoneGazebo** [comment]
They'll burn cities if they're unhappy, but also if they're really pissed at the player. Or if they're out to damage instead of capture.

**Comment by Edaka** [comment]
I suspected it wasn't as simple as I described. I just had the impression that France wants to expand since it saved the first couple of cities it took, including pretty mediocre cities with no resources around.Then at some point it started burning every high-pop city with great person improvements and luxuries. If I wanted to hurt somebody, I'd raze selectively, leaving decent cities for myself. 

I often notice this during lategame. It's as if the AI always starts out by leaving every captured city be, then at some point the raze switch goes on and it starts acting in a mirror-opposite way.

I'm sorry for my vulgar description, I can't seem to formulate my thoughts better. I also know nothing of the underlying code mechanics, so please correct me where I'm wrong.

**Comment by LoneGazebo** [comment]
I'll look at making the functionality more granular, but it has a lot of variables as-is.

**Comment by LoneGazebo** [comment]
It's about as efficient as it can be. Closing
