### ISSUE TITLE
Nau gathering around city states for no reason

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1504]
This nau party has been happening around Hong kong for the longest of times. You can't see other ships, but basically the whole Hong Kong's coastal territory was occupied by those ships. I'd just pick one at a time and a new one would come in its place on the following turn. Portugal and Hong Kong were not at war. Could it be that she was trying to build a feitoria, but couldn't because both coas tiles were occupied with irreplacable improvements (improved resource and a great person improvement)?
![20160324233156_1](https://cloud.githubusercontent.com/assets/12978597/14042600/0f6477f2-f284-11e5-83bf-a337314db2be.jpg)

The experience is anecdotal, though, so I don't know how reproducible it is.

**Comment by Iamblichos** [comment]
Building the Feitoria is pretty much automatic when doing the sell exotic goods mission. And it'll replace non-resource tiles with it, even on mountains too I believe.

**Comment by MoiMagnus** [comment]
The great diplomat unique improvement cannot be replaced (it's impossible) so it may be the cause of the problem.

**Comment by Iamblichos** [comment]
If there's no possible tile, it just won't build it, but it looks there is an available plot.

**Comment by LoneGazebo** [comment]
Nau Party!

**Comment by Edaka** [comment]
One more detail I forgot to mention: Hong Kong isn't actually Hong Kong - it's actually Wittenberg. Yeah. The latter captured the former at some point.Though IIRC, the city of Wittenberg itself didn't have a feitoria around, but it might have been that the tile improvement graphics hadn't updated in the fog of war.

**Comment by Iamblichos** [comment]
It's now part of Hong Kong's Minor City State empire.

**Comment by LoneGazebo** [comment]
Can't reproduce, sorry.
