### ISSUE TITLE
Capturing land units with horsemen as the Huns 

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1505]
A really, really minor issue. The battle preview says: "Capture Chance if Sunk", but you can't sink a land unit on land (duh). Could the tooltip say "Capture Chance if Defeated" instead?

**Comment by LoneGazebo** [comment]
For which?

**Comment by LoneGazebo** [comment]
ah gotcha. I'll take a look.

**Comment by TechpriestEnginseer** [comment]
![image](https://cloud.githubusercontent.com/assets/13937047/14056628/97790758-f2ab-11e5-94e0-64cfad33483e.png)

**Comment by mwhiter** [comment]
My advice? Change to something generic like "Capture Chance if Defeated: {1_Percent}%"
