### ISSUE TITLE
Natural Heritage sites

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1506]
Is there a reason this WC resolution never triggers any diplomatic response from AI? They neither hate it, nor love it, ever. Yet most of the time I seem to propose it, the AI votes "Nay". Even an AI that had a natural wonder in its territory voted against it in my game.

**Comment by LoneGazebo** [comment]
I'unno. It's a pretty neutral resolution.

**Comment by Hokath** [comment]
Yeah that's how it has always been, people don't ever seem to vote for it when it benefits them. I guess the benefit is very small.

**Comment by LoneGazebo** [comment]
Yep.
