### ISSUE TITLE
IsDummy for Buildings

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1509]
In similar manner as IsDummy for Policies, could you please add an IsDummy column for Buildings, and have those Buildings skipped from the city:GetNumBuildings() function. This would be very useful, if possible.Thanks!

**Comment by LoneGazebo** [comment]
Are you using the setnumfreebuilding function to add buildings, or setnumrealbuildings?

**Comment by JFDaly** [comment]
I'm using SetNumRealBuilding(). I have the boolean set to true - I'd forgotten about that boolean, but it doesn't appear to be working in any case.

**Comment by LoneGazebo** [comment]
I'll give er a go.

**Comment by LoneGazebo** [comment]
Done.

**Comment by JFDaly** [comment]
Excellent, thank you.

**Comment by JFDaly** [comment]
Confirmed to work. Thanks!
