### ISSUE TITLE
2 bugs, 3/6 version

### ISSUE THREAD

**Issue by Valvts** [LoneGazebo/Community-Patch-DLL#151]
I can trade 1 iron/horse for 250-300g, 2 games in a row already, it screws with the balance, playing on immortal -
http://puu.sh/gseLJ/d7c6fb42d6.jpg

If you right click on the Siam Wat in the set up game menu, that what shows up -
http://puu.sh/gsfii/7e71bd1948.jpg

Thanks!

**Comment by powder0321** [comment]
I had something similar but perhaps even more egregious occur in a recent game. One of my luxuries for one of his, plus 112 GPT. Playing on King.

http://i.imgur.com/eqY9wiY.jpg

**Comment by LoneGazebo** [comment]
The luxury was probably a WLTKD resource for Bismarck- they pay more for those, generally. I'll look at the strategic resource value, however I do have some questions:

Did he have any of the resource on his own?
Was he a neighbor?
Were you stronger or weaker than him, militarily?
Were you friends?

These values all effect the value of items.
G

**Comment by powder0321** [comment]
Might not make a difference but I was playing as Bismark. The AI player was Alexander.

He did not have any copies of the resource himself. I actually control 100% of that particular resource in this game.
He is on the other continent in a communitas continents map.
I was slightly stronger militarily at that point in the game (I was 5th he was 6th out of 8).
We were not friends at the time of the deal although we had decent relationship modifiers and became friends about 20 turns later.

Also, my case only involved luxury resources.

Hope this helps!

**Comment by Valvts** [comment]
On my second game as Siam, I traded regularly with Shoshone 300g for 1 horse :S
