### ISSUE TITLE
Food Consumption

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1510]
I've been struggling to balance the numbers for Plagues in Health, but one solution to all of my concerns would be to be able to have a Plagued city consume 3 Food per Citizen, like they did in Civ IV. So would it be possible to change how much Food a Citizen consumes, on a per city basis? 

The base define is this: FOOD_CONSUMPTION_PER_POPULATION, so perhaps a city:SetFoodConsumption(value) or something could be added, which changes this? Alternatively, a set of functions: city:SetIsPlagued(boolean)/city:IsPlagued() could be added and tied to a new, FOOD_CONSUMPTION_PER_PLAGUED_POPULATION define. Whichever would be easiest/most possible.

It's not a big deal if neither of these are possible, but I thought I'd ask before I considered my other options. Thanks.

**Comment by LoneGazebo** [comment]
Probably just easiest to make a variable that can be changed via lua that adds onto the food consumption value.

**Comment by JFDaly** [comment]
Awesome. That would be really helpful if doable. Thanks.

**Comment by TechpriestEnginseer** [comment]
Couldn't you just instead do stacking dummy buildings that does -1 food per citizen?

**Comment by JFDaly** [comment]
If doing so in the DLL is not possible, but it'd be nice if the tooltip could return the correct value in city:FoodConsumption()

**Comment by LoneGazebo** [comment]
City:GetAdditionalFood()
City:SetAdditionalFood(int iValue);

Works like you think it would - you can add any amount of food (+/-) to the food per citizen value.

**Comment by LoneGazebo** [comment]
The food per citizen won't report differently in the LUA (as it simply uses the define), so you'd need to edit the tooltip to add in the GetAdditionalFood() value.

**Comment by LoneGazebo** [comment]
But the consumption value will obviously adjust. You could add a lua element for GetAdditionalFood that adds something to the tooltip (i.e. "-x food from plague").

**Comment by JFDaly** [comment]
Awesome! This method will be much easier than would have been finding a dummy Building that subtracts food, subtract that from the -X from Buildings already in the tooltip, and then re-add it as from Plague - much easier. Thank you very much!

**Comment by JFDaly** [comment]
Just having tested its functionality on the alpha that you gave me, but GetAdditionalFood() returns a table ID (I think), instead of what's in SetAdditionalFood(). The number of tables that return correspond to the number set number in SetAdditionalFood() (e.g. SetAdditionalFood(3) and GetAdditionalFood() returns table: 658D0B80 table: 658D0B80 table: 658D0B80

**Comment by LoneGazebo** [comment]
Oh, I goofed and forgot to push the integer properly. Will fix and reupload.

**Comment by JFDaly** [comment]
That fixed it - and, to boot, the UI automatically registers the change. Thanks again!

**Comment by LoneGazebo** [comment]
Fantastic!
