### ISSUE TITLE
Units' quircks

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#1511]
I decided to look at unit stats and promotions again after all those changes and adding new units. I found some oddities in tech tree:

1. Almost all units has "Can Pillage Improved Tiles" promotion. It's unnecessary (we don't have "can heal" or "can forify" info because it's obvious).
2. Gunpowder units doesn't have "Ignore building defence" promotion.
3. Mercenaries have enormous cost to upgrade (1800 vs 700 for simillar units).
4. Zeppeling and Helicopter have "Embarkation", "Ocean Embarkation", "Embarkation with Ocean Movement" and "Embarkation with Defence" promos. Is it possible to just change it that fishing "Allows all land and hovering units to embark [...]"? Or at least stack all those promos into one... Right now it's really untransparent.
5. There is total incostistency at scout path. I don't even know how to fix it but some units have 3 movement, some have embarkation promotions, some have abillity to paradrop.
6. Armoured car is the only unit of his line which doesn't have "No rough terrain bonusses" promotion. I'd add it for consistency (mind that Tank line also have this promo).

And one more thing: could you explain what "No Bad Goodies" promo in scout path does? I can't find info about it and it looks like another bug.

**Comment by LoneGazebo** [comment]
1. Is required on many units because not all combat classes have it defined by default.
2. I think that's by design, as artillery gets stronger up to that point.
3. Upgrade to or from?
4. I could make a unified promotion, yep. 
5. It is by design. Things like paradrop should be lost on upgrade, though the two paradrop units are next to each other.
6. I'll take a look.

**Comment by LoneGazebo** [comment]
No bad goodies is a relic of Civ 4, in that goody huts could spawn barbarians.

**Comment by Finarvi** [comment]
3. Upgrade from Mercenaries to Mechanized Infantry.

**Comment by Finarvi** [comment]
And another thing: what means "+25% vs guns"? Which unit classes?

**Comment by LoneGazebo** [comment]
Gunpowder melee units.

**Comment by LoneGazebo** [comment]
Fixing 4&6
