### ISSUE TITLE
Deal Bug 

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1514]
These posts in the latest version thread: 
http://forums.civfanatics.com/showpost.php?p=14213095&postcount=54
http://forums.civfanatics.com/showpost.php?p=14213129&postcount=56
http://forums.civfanatics.com/showpost.php?p=14214137&postcount=59

Seems to be something iffy going on. I also noticed something weird in my game, I could ask for Silk from an AI (and they wouldn't give it to me for all the gold in the world, even though we were friends) but if I looked at my happiness overview, I already had Silk.

**Comment by mwhiter** [comment]
Is this related to https://github.com/LoneGazebo/Community-Patch-DLL/issues/1499 ?

**Comment by LoneGazebo** [comment]
Yep. Referencing there.
