### ISSUE TITLE
One City Challenge

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1516]
This was posted on the forum, but I don't see a thread here, and I know you prefer having stuff here.

In the OCC, the AI is choosing to not build settlers. In my test, Venice used their MoV, and The Pyramids builder used that settler, but that was it through maybe 80 standard speed turns.

I included the City Strategy Production log in case that is helpful.

[CityStrategyAIProductionLog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/190957/CityStrategyAIProductionLog.zip)

**Comment by LoneGazebo** [comment]
Thanks I'll take a look.
