### ISSUE TITLE
LUA way to check if a World Congress Resolution is active?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1518]
I know we have a method to know if a player can propose a resolution and a method that fires up when a resolution is passed/repealed, but is there a way to know if a resolution is actively doing its effect? (When it's passed)

I need to check whether or not through save games if the resolution is still active so that some LUA coding can still apply.

**Comment by LoneGazebo** [comment]
No, there's almost no lua for the world congress. We'd have to do some game_event work, if possible (I don't actually know if those values iterate every turn).

**Comment by TechpriestEnginseer** [comment]
Guess I'm stuck to an unreliable save/loader then.
