### ISSUE TITLE
Request per Lynnes, need to move the Deep Embarkation over to CBP

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#1521]
And this line needs to change in the function CvPlot::needsEmbarkation:

from this:

`return isWater() && !isIce() && !IsAllowsWalkWater() && !pUnit->canMoveAllTerrain() && !pUnit->canMoveImpassable() && !pUnit->canLoad(*this);`

to this:

`return isWater() && !isIce() && !IsAllowsWalkWater() && !pUnit->canMoveAllTerrain() && !pUnit->canLoad(*this);`

!pUnit->canMoveImpassable() will still prohibit Heli's and any other unit that has the promotion PROMOTION_HOVERING_UNIT from embarking on coast.

Pretty simple stuff.

**Comment by LoneGazebo** [comment]
Why move deep embarkation over? It's in the CP base, where it should be, right? Or is he wanting them to embark at the coast?

**Comment by Iamblichos** [comment]
He wants the CP to be like vanilla.

**Comment by Iamblichos** [comment]
Which is fine I would think...since hovering units don't do any kind of deep embarkation in vanilla game.

**Comment by LoneGazebo** [comment]
Gotcha. I'm making a 'catch-all' hovering promotion for the CBP (so that zeppelin/helicopters only have 1, instead of 4, embarkation-related promotions). I'll take the deepwater off of the helicopter in the CP, should fix it.

**Comment by Iamblichos** [comment]
don't forget about the function too, I could make a pullrequest, but too much work for one line.

**Comment by LoneGazebo** [comment]
I did.

**Comment by LoneGazebo** [comment]
(not forget, I mean) :dancer:
