### ISSUE TITLE
First citizen is not assigned as laborer if CITY_STARTING_RINGS define is 0

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1523]
Also, when city gets its first workable tile, the first citizen is not assigned to it.

**Comment by LoneGazebo** [comment]
I'll look at it, but that's not exactly a supported define value.

**Comment by LoneGazebo** [comment]
@ilteroi, any ideas? I haven't been able to reproduce.

**Comment by ilteroi** [comment]
is it really that important? probably fixed by the new citizen assignment logic. let's close it already.

**Comment by qqqbbb** [comment]
I've just tested lastest version. The bug is still there.

**Comment by Iamblichos** [comment]
I agree with ilteroi, is this necessary? Are you making a mod where City starts with only 1 border plot (the city plot)?

**Comment by LoneGazebo** [comment]
He is, yes.

**Comment by ilteroi** [comment]
anyway i don't have a clue about citizen assignement

**Comment by LoneGazebo** [comment]
No worries, I'll give it another look later.

**Comment by LoneGazebo** [comment]
In the absence of a solution (I've tinkered with this to no avail), I've decided that zero is not a supported XML value in this instance.
