### ISSUE TITLE
City panel graphics bug

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1524]
[city culture hex does not fit in the panel](https://dl.dropboxusercontent.com/u/28753474/CivilizationV_DX11%202016-03-30%2003-28-34-91.jpg)
CP+CBP, no EUI.

**Comment by TechpriestEnginseer** [comment]
Is that supposed to not happen?

**Comment by mwhiter** [comment]
This looks like additional items were added to a stack and it just moved the culture border icon down off the city view. To fix, resize the stack by row_size * 2in City View. 

I can't actually investigate the bug in person because I don't have access to my computer at the moment.

**Comment by LoneGazebo** [comment]
It's intentional.

**Comment by mwhiter** [comment]
To clarify what I said  assuming that two additional rows were added... I was just comparing with a screenshot off Google

**Comment by LoneGazebo** [comment]
Yeah, I liked the look of the hex hanging off, so I left it that way on purpose.
