### ISSUE TITLE
Replacing Pillaged Improvements Deduct Strategic Resources

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1525]
1. Have an iron source near a Moroccan city.
2. Have mine built.
3. Have mine pillaged by enemies.
4. Hit chivalry technology.
5. Begin to replace all nearby city tiles with kasbahs.
6. Attempt to replace the pillaged mine with the kasbah.
7. Get deducted iron resources.

**Comment by LoneGazebo** [comment]
I'll make a pillage check so that pillaged tiles are de-pillaged before the new improvement is set. Should fix it.
