### ISSUE TITLE
CP: Events – Development Thread

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1527]

**Comment by LoneGazebo** [comment]
Here's my current working list – not complete, and mainly just brainstorm ideas:

One-Shot 

	Bad:
		C A bad harvest (ends at fertilizer)
			Lose 20 food scaling with era
		C Mysterious plague (ends at scientific theory)
			Lose 1 population
		P Failed research (ends at scientific theory)
			Lose 20 research, scaling with era
		C Fire! (era-specific, ends at replaceable parts)
			Targets all era buildings, potential for loss at 15% for each
		P Dishonorable knight (starts at chivalry, ends at renaissance era)
			Lose 50 culture, 50 GAP
		C Windstorm (farm)
			Farm destroyed
		C Scarce game (camp)
			Camp destroyed
		C Mine collapse (mine)
			Mine destroyed
		C Hurricane (fishing boat, buildings) - coastal only
			Lose two fishing boats, 20% chance for buildings
		C Hard times (village)
			Village destroyed
		C Bandits (lumber mill)
			Lumber mill destroyed
		C Outlaws (only if unhappy) 
			2 barbs spawn
		C Rioting (only if unhappy)
			Resistance for 2 turns
		C Looters (only if unhappy)
			Lose 100 gold, scaling
		C Arsonists (only if super unhappy)
			10% chance of buildings destroyed
		P Inflation (ends at banking)
			Lose 100 gold, scaling
		P Artifacts lost (ends at archaeology)
			Lose 30 culture, scaling
		C Idolaters (ends with majority religion in city)
			Lose 30 faith, scaling
		Volcanic Eruption (near mountain)
			Destroy farm, camp, village, 20% building destruction, -2 pop
		
		
		Corporate espionage (requires corporations)
			Lose 500 gold
		Cyber-terrorism (requires computers)
			Lose 1000 gold, 1000 science
		
	Good:
		A bountiful harvest (requires farm)
			Gain 30 food, scaling
		impressive hunt (requires camp)
			Gain 30 food, scaling
		Sign from the heavens (ends at theology)
			Gain 20 faith, scaling
		Message from god (requires religion, starts at theology)
			Gain 50 faith scaling
		Immigrants (only possible for cities under size 15)
			Gain 1 population
		Baby boom (only possible for cities over 15)
			Gain 2 population
		Oral traditions (ends at printing press)
			Gain 20 culture, scaling
		Research breakthrough (starts at writing)
			Gain 30 science, scaling
		Festivals
			5 turns WLTKD
		Market day (ends at economics, no market in city)
			Free market for 10 turns
		Good catch (coastal)
			Gain 30 food
		Bountiful Oasis (no caravansary, has mathematics)
			City gains free caravansary
		Natural Wonder (has railroad, no hotel)
			City gains free hotel
		Natural Wonder
			Gain 50 culture, scaling

Choice 

Era-Specific
	Ancient
		C Market (requires market) 
			Polyglot: +1 culture, -1 gold
			Our language only: +1 gold
		C Monument (requires monument) 
			Our forefathers: +1 culture
			Our gods: +1 faith
		C Council (requires council) 
			Hereditary: +1 culture
			Merit: +1 science
		C Pyramids (requires archaeology)
			Science! +5 Science
			Tourism! +5 Tourism
			Heritage! +5 Culture
		C Nomads (ends at philosophy)
			Incorporate: +1 population, 3 turns of resistance
			Give land: + 50 border growth, -50 gold
			Do nothing
		C Council (requires council) 
			Side with council: -100 Golden Age Points
			Reject council ruling: 2 turns of resistance 
			Bribe councillors: -100 Gold
		C Fishing Expedition (coastal, fishing required)
			Food: +30 Food, -10 gold - 50% chance
			Trade: +50 Gold 50% chance
			Discovery: +30 science, -10 gold 50% chance
		P Cosmic Event (ends at astronomy)
			Stop looking at the sky! -100 Golden Age Points
			The Gods have forsaken us! -30 faith
			Do nothing! 2 resistance in all cities
		P Plague of Locusts (ends at civil service)
			Pay to restore the grain: -300 gold, lose 2 farms
			Pay to restore half the grain: -150 gold, -30 food in all cities, lose 3 farms
			Do nothing: -60 food in all cities, lose 4 farms
		P Itinerant Soothsayer (have pantheon)
			Invite to court: +30 culture 
			Sacrifice to gods: +30 faith
		Military Training (ends at chivalry)
			Focus on melee: melee gain drill I, or 15 XP if they have it.
			Focus on ranged: ranged gain accuracy I, or 15 XP if they have it.
			General training: all units gain 10XP
	Classical
		P Philosophical rift (starts at Philosophy, ends at scientific theory)
			Lose 40 science
			Lose 40 culture
			Lose 20/20
		P Poetic Saga Recorded
			Gain 50 culture
			Gain 50 faith
			Gain 50 tourism
		P Senates Demanded (chain event, requires Writing)
			Reject demand: 3 resistance in all cities, +2 gold in all cities
			Allow demand: +1 culture in all cities, -1 gold in all cities
		C Governor makes demands (requires unhappy, senates must be allowed)
			Accept: Lose 200 gold, 200 GAP
			Reject: 4 barbarian units rise up near city
		P Foreign Dignitaries
			Lavish: Lose 200 gold, gain 100 tourism
			Simple: Lose 100 gold, gain 50 tourism
			Reject: Gain 100 GAP
		C Dedicate a Memorial (starts at military theory, ends at chivalry, requires barracks)
			Praise Generals: gain 200 GG points
			Praise Admirals: gain 200 GA points
			Praise soldiers: gain 2 spearmen and 1 archer
			Praise sailors: gain 2 triremes
		C Amphitheater:
			Popular Dramas: +2 Gold
			Classical Dramas: +1 Culture
		C Baths
			Public Use: +2 Culture, -1 Production
			Patrician Use: +1 Culture,  +1 Gold 
		C Lighthouse
			Public upkeep: -1 Gold, +1 Production
			Private upkeep: +1 Gold
		
		
	Medieval
		Wonders
	Renaissance
		Wonders
	Industrial
		Wonders
	Modern
		Wonders
	Atomic
		Wonders
	Information
		Wonders

Map-Specific
	Coastal

	River
	
	Mine

	Lumber Mill

	Farm

	Fishing Boat

	Village

	Fort

	Academy

	Customs House

	Holy Site

	Landmark

	Manufactory	

Conditional
	
	Unhappy

	Puppet

	Razing

	Occupied

	Trade Route

	Religion

**Comment by Iamblichos** [comment]
One-Shot 
Event: National Hero: Reach level 10 promotion level, Heal adjacent units +5, adj mod 10, Unit gains +50% combat strength

Event: TributeMinor: +5 wltkd in Capital,+5 Gold from Temples

Choice:
Event: Hyperborean Traveler: discovered all civs on map

Event: TechResearchedFirst: Philosophy

Era Event: After Settling near Krakatoa: Eruption of Theira (bad), positive tourism Santirini.

**Comment by Adonis-VII** [comment]
C Flood (Requires floodplains)
Destroy X buildings on floodplain (not sure if its possible)

I assume no tile changes (e.g. Migrating whales have chosen this new location for breeding; Volcanic eruption: X number of coast/sea tiles become land)

**Comment by LoneGazebo** [comment]
Yeah, not possible for terrain types to change etc.

**Comment by TechpriestEnginseer** [comment]
Well, the terrain type could change via LUA.. but the graphical engine wouldn't support it without you reloading your map again.

**Comment by LoneGazebo** [comment]
Indeed, and that's not a viable solution. I think we'll be okay without that.

**Comment by TechpriestEnginseer** [comment]
All of these events are temporary.

Vigilantes: Crime in this city has risen to a new high. Civilians have formed a group that is known to prowl on the injustice of government corruption and crimes. What do you suppose we do?
- Perhaps we should cooperate with them and solve the injustice here.
 - Lose Culture
 - Gain City's Defense
 - +1 Happiness
 - +1 Morality
- Bah.
 - Gain City's Defense.
- Imprison them for their defiance over the local police.
 - Lose Golden Age Points.
 - Production Bonus
 - -1 Morality

Nation Investments: This nation has the highest poverty in the nation. We can invest in the local businesses and break up the lands of the landowners to give to the people. Or we can continue what we were still doing. What do you suppose we do?
- Well said, let us begin investing in the nation.
 - -25% gold cost off purchasing buildings and units.
 - Lose Golden Age Points.
- The landowners pay for our government. Out with this plan!
 - Gain Gold
 - Lose Golden Age Points.

Tax Surplus: It seems that we have a surplus in taxes, what do you suppose we do with it?
- Invest the excess in the arts department!
 - Reduce boredom nationally.
 - +2 culture in all cities.
- Invest the excess in the education department!
 - Reduce illiteracy nationally.
 - +1 science in all cities.
- Invest the excess in the commerce department!
 - Reduce poverty nationally.
 - +2 gold in all cities.
- Invest the excess in the defense department!
 - Reduce crime nationally.
 - +2 Defense in all cities.
- What surplus? I don't see it.
 - Gain Gold

**Comment by LoneGazebo** [comment]
Cool. There's currently no mechanism for affecting happiness or need modifiers in the events system without resorting to a dummy building or policy. That may change in the future, but for now let's try to stick to the existing frameworks. I'm hoping to keep the memory budget for events as low as possible.

**Comment by TechpriestEnginseer** [comment]
You clearly haven't see the CBP E&D's building list when you pop up IGE. ;)

**Comment by LoneGazebo** [comment]
Yep. I'll be seeding the next beta soon which has all that jazz hooked up to it.

**Comment by LoneGazebo** [comment]
Just updated beta 1 on github.

**Comment by qqqbbb** [comment]
To make things more interesting awards you get should be a random number. Instead of 20 food - a number between 10 and 30, for example.
What about E&D events that did not make it to the list? What about civ specific events?
Will there be a cooldown system for events? So that you don't get the same one twice in a row.

**Comment by LoneGazebo** [comment]
Not using random numbers, as they need to be reproducible in reverse for functions that expire. 

E&D is not my concern, @TechpriestEnginseer  is working on that. And yeah, there will be cooldowns, don't worry.

**Comment by Iamblichos** [comment]
Before we go hog wild with this:

1) Common Events, City, One Shot, Era, Etc. to all civs.
2) Civ Specific

And less is more.

**Comment by LoneGazebo** [comment]
Yep. I'm aiming for around 10 of each (choice and no-choice) per era to start. Once those are done, the we start on civ-specific.

**Comment by LoneGazebo** [comment]
I'm picking 3 buildings per era to give choices to. Choices will happen per city, unlike Beyond Earth's building decisions, to allow for more granular choices. They'll also be permanent changes for the city. Then around 4 good and 4 bad generic choices.

**Comment by LoneGazebo** [comment]
That reminds me, @TechpriestEnginseer and @JFDaly , you'll be able to use the lua elements for events as the baseline for your decisions as well - just have decisions fire events. No more (or at least far fewer) dummy buildings and policies for those as well!

**Comment by El-SiD** [comment]
Maybe this is a silly question, but will it work in MP (i assume event will be popup)?

**Comment by LoneGazebo** [comment]
@El-SiD , theoretically yes, however I don't have access to the network push elements we would really need to make it reliable. Events that do not require player choice will definitely work, but right now the DLL is set up so that events with choices are bypassed if you are in a networked game.

**Comment by LoneGazebo** [comment]
Closing this, as we'll be moving the discussion to the forums
