### ISSUE TITLE
art work too big for the screen

### ISSUE THREAD

**Issue by gonzalodev** [LoneGazebo/Community-Patch-DLL#1528]
I just created a great work of art but the image is too tall for the screen so i can't see the button to close the window that displays the picture.

The work of art is Aztec Gods. I cant make a screenshot.

**Comment by Iamblichos** [comment]
I don't understand. If you created the art work, can you size it appropriately to fix your issue?

**Comment by gonzalodev** [comment]
oh sorry, meant that i created in game, with a great artist, not that i designed it. When i finished the work, the pop-up that show the image was too tall and the close button that should be in the bottom of the pop-up window wasn't clickable.

I hope i made it clear now, sorry, english is my second language.

By the way, i closed it just pressing 'esc', but it took me a while to find out.

**Comment by gonzalodev** [comment]
I also found the screenshot (I was looking in the civ4 folder...). Do you want it? It is in .tga format

**Comment by LoneGazebo** [comment]
If you just hit 'esc' it'll close.

That can happen if you are running the game at a very odd or small resolution.

**Comment by gonzalodev** [comment]
resolution: 1600x900
