### ISSUE TITLE
Puppet AI

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1529]
Would it be possible to have the Puppet AI (Governor AI?) to prioritize Buildings that have been invested in? In CID: Colonies, you still had access to purchasing Buildings. My latest version of CID, however, switched on Investments as a default feature, which basically subverts that benefit. Being able to use Investments to somewhat direct the Puppet AI toward certain Buildings would be a sufficient substitute if this would be - eventually - possible.

**Comment by TechpriestEnginseer** [comment]
rip Venice

**Comment by LoneGazebo** [comment]
They do this already – invested buildings get a big bump in value.

**Comment by JFDaly** [comment]
Awesome, thanks for the quick response!
