### ISSUE TITLE
Faith from Religious Settlements pantheon not scaling with era

### ISSUE THREAD

**Issue by powder0321** [LoneGazebo/Community-Patch-DLL#153]
Unless this is by design and the description hasn't been updated. Faith from the Goddess of Love pantheon does seem to be scaling correctly as it doubles in the Medieval era and continues to scale upward from there. Faith from Religious Settlements does not.

**Comment by photonblaze** [comment]
I took this pantheon once and was disapointed

**Comment by LoneGazebo** [comment]
It scales, I just need to fix the popup (will fix in next version).
G
