### ISSUE TITLE
GameEvent.GetScenarioDiploModifier Feature Request

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1530]
````
GameEvents.GetScenarioDiploModifier1.Add(function(ePlayer1, ePlayer2)

	if (GetNumTokensOwned(ePlayer2) == 2) then
		return 20;
	end
	
	return 0;
end)

-- Large negative modifier when other player has more than 2 Titles (about to win)
GameEvents.GetScenarioDiploModifier2.Add(function(ePlayer1, ePlayer2)

	if (GetNumTokensOwned(ePlayer2) > 2) then
		return 70;
	end
	
	return 0;
end)
````
````
		<!-- Scenario-specific Diplomacy Modifiers-->
		<Row Tag="TXT_KEY_STEAMPUNK_SCENARIO_SPECIFIC_DIPLO_STRING_1">
			<Text>You have 2 Titles, and pose a threat to them in the League.</Text>
		</Row>
		<Row Tag="TXT_KEY_STEAMPUNK_SCENARIO_SPECIFIC_DIPLO_STRING_2">
			<Text>You have more than 2 Titles, and nearly control the League!</Text>
		</Row>
````

Could it be possible to have the 3 of these? I would like to use it for my moral alignment system from CBP E&D so that good civilizations like good civilizations, evil civilizations like evil, and diversifying morality upon other civilizations.

Also what TXT_KEY string is needed to use to make it appear among the diplomatic text since I noticed Into the Renaissance scenario had the same GameEvents style, but yet different XML syntax.

````
		<Row Tag="TXT_KEY_MEDIEVAL_SCENARIO_SPECIFIC_DIPLO_STRING_1">
			<Text>You follow a different religion.</Text>
		</Row>
```

**Comment by JFDaly** [comment]
Use the DiploModifiers table and GameEvents.GetDiploModifier(diploModifierID, fromPlayerID, toPlayerID) instead, which allows you to add whatever new diplo modifiers you want. CivFanatics is down for me atm, but the first google search of 'GameEvents.GetDiploModifier' should bring up the relevant thread with all the info on how to use it.

**Comment by TechpriestEnginseer** [comment]
ooh
