### ISSUE TITLE
disembark without penalty

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1531]
hello again.

units may disembark without penalty in cities. this leads to a problem:
- a regular land unit in the city has 2 moves
- the same unit embarked next to the city has up to 5 moves

--> the embarked unit can move much further on land than the non-embarked unit!

can't think of an easy solution, but i have little time these days. any ideas?

**Comment by LoneGazebo** [comment]
This happens as a result of technology - I think it's fine, personally, though you could cap the unit's movement upon disembarking at the unit's max land movement speed or it's remaining moves, whichever is higher (so if you come off of a move with 3/4 moves left, disembark, you'd either have your maximum land moves remaining, or 3, whichever is lower.

**Comment by ilteroi** [comment]
the cap is relatively easy, but it still seems like cheating to have the full moves on land after moving on water first. better than nothing i guess.

**Comment by ilteroi** [comment]
what exactly is the difference between isCityNoEmbarkCost() and isCityLessEmbarkCost()? in the code they seem to be equivalent ...

**Comment by ilteroi** [comment]
i have refactored CvUnitMovement. looks much cleaner now.

also tried to implement isCityNoEmbarkCost() and isCityLessEmbarkCost() correctly, although zero movement cost is a bit odd. is it really intended that way? it leads to some good pathfinding (units really prefer to use a city for embarkation) but also some bad pathfinding (temporary embarkation although there's a land path also).

also i think we need some documentation ... who gets these abilities? they come via CvTeam so it must be a tech, but I couldn't find anything in the 'pedia. same for road/railroad speed changes btw.

**Comment by LoneGazebo** [comment]
It is intended, yep. Unlocks come at steam power and, IIRC, combined arms. They are techs, yes. I could probably work up a movement explanation somewhere in the civpedia, yep.

**Comment by ilteroi** [comment]
pushed

**Comment by LoneGazebo** [comment]
Awesome!
