### ISSUE TITLE
AI overvalues world congress votes

### ISSUE THREAD

**Issue by Quanfinigon** [LoneGazebo/Community-Patch-DLL#1532]
Playing with all 6 CBP mods, AIs sometimes ask me to vote for their proposal, and are willing to give everything they own for it, including 100+ gpt and vassal state.

**Comment by TechpriestEnginseer** [comment]
Maybe you have a lot of votes and 20 votes means a lot to them or something?

**Comment by Quanfinigon** [comment]
The first time was when I had one vote, and I vassalized three AIs over the course of the game this way.
