### ISSUE TITLE
Can't sell buildings while razing

### ISSUE THREAD

**Issue by DanteValerian** [LoneGazebo/Community-Patch-DLL#1533]
I take a city, I start razing it. I sell a building. But then the next turn, and the turn after that, the sell building buttons are all gone. I can't sell more than one building, ever, on a city I'm razing.

**Comment by Radost** [comment]
AI doesn't do this, so shouldn't player.

**Comment by LoneGazebo** [comment]
Actually the AI does sell buildings during razing (I taught them this)! I thin, however, that this might be an EUI issue.
