### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#1536]
It always happens 2 or 3 turns after this autosave: https://drive.google.com/file/d/0B9Y5ivaA0M6dYjloVzI2SER5Z0E/view?usp=sharing

**Comment by AnastaseAlex** [comment]
Using the total package of CBP, with EUI compatibility. No other mods, latest version.

**Comment by LoneGazebo** [comment]
Your link is to a personal document - you may want to fix that! :) I did not read it, promise.

**Comment by AnastaseAlex** [comment]
oups. Corrected it! thnx!

**Comment by Artharon** [comment]
I have a smiliar issue, random crash to desktop while AI is loading (next round after this one). Using the latest package of CBP, no EUI, with all of JFD's new civs (all new civs and collaborations except "Oman"), Civ traits, Cultural Diversity, Events and Decisions and Yet Not Another Earth Map Pack. Need help! https://www.dropbox.com/s/t8886fsa5p1l54f/Dufour_0140%20-%200600%20n.%20Chr..Civ5Save?dl=0

**Comment by LoneGazebo** [comment]
Unfortunately I can't debug heavily modded saves like that. I can really only debug CTDs with the base set of mods.

**Comment by LoneGazebo** [comment]
@AnastaseAlex , the CTD went to disassembly, so I assume it is EUI.

**Comment by AnastaseAlex** [comment]
Ok. I will stop using it again. The only thing I really miss from it when
playing is the leaders profiles and city states+quests icons on the right
side. Saves a lot of time. But it is true that without EUI the game is
faster...

**Comment by LoneGazebo** [comment]
Yep. EUI can crash, though, especially late-game. It's just not a well-optimized mod, truth be told. Lua is expensive, and can be buggy.
