### ISSUE TITLE
Guerilla war

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1538]
I picked the guerilla war tenet and researched combined arms.
Still, I cannot build guerillias. They also don't appear on any tech.
The added experience from fighting in homeland also doesn't seem to work. I forgot to check the combat bonus.

**Comment by TechpriestEnginseer** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/1535

These two are connected.
