### ISSUE TITLE
UU and UB Tooltips in civ selection screen

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1539]
There should be tooltips for UU and UB in civ selection screen like in EUI.

**Comment by JFDaly** [comment]
Not really possible for the CPP, as the CivSelectionScreen files are unmoddable, except when overwritten in the DLC-format that EUI does it. This notwithstanding, the vanilla tooltips would have to be re-created for this express purpose, as the extant ones reference data which requires an active game (the Game. object, for instance). Not nearly as simple a request as you might think.

**Comment by qqqbbb** [comment]
What file from EUI does it?

**Comment by JFDaly** [comment]
It's facilitated by InfoTooltipInclude.lua, EUI_tooltip_library.lua, EUI_tooltips.lua, and the various files in the GameSetup folder.

**Comment by LoneGazebo** [comment]
Yep. Thanks for answering JFD, not going to do this request, as it is too much work (and already covered by EUI).
