### ISSUE TITLE
VIllage on city connecting road

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#154]
1. Biuld a village on a plot without a road. City that will be using the village is already connected to capital.
2. Construct a road on that plot.
3. Destroy another road so that plot with the new village connects the city to your capital.
4. The plot with the village does not get +1 gold for city connection.

**Comment by LoneGazebo** [comment]
Plots need a turn to update - did you allow for that? Also, when you go to strategic view and look at the 'city connections' overlay, does the yellow line cross the village?
G

**Comment by qqqbbb** [comment]
Yeah, it's OK after a turn.
