### ISSUE TITLE
Normalizing Corporations and making them more moddable

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1541]
Hey. Just pitching this idea to see what you think. Right now Corporations are rather denormalized and very coupled with buildings, and I'd like a way to denormalize them. Here is example code to show you what I mean:

```
 CREATE TABLE IF NOT EXISTS Corporations
 (
 	ID						integer 	AUTO_INCREMENT PRIMARY KEY											,
 	Type					text		NOT NULL UNIQUE														,
 	Description				text		DEFAULT NULL				REFERENCES Language_en_US(Tag)			,
 	HeadquartersBuilding	text		DEFAULT NULL				REFERENCES Buildings(Type)				,
 	OfficeBuilding			text		DEFAULT NULL				REFERENCES Buildings(Type)				,
 	FranchiseBuilding		text		DEFAULT NULL				REFERENCES Buildings(Type)				,
 	PortraitIndex			integer		DEFAULT -1															,
> 	IconAtlas				text		DEFAULT NULL				REFERENCES IconTextureAtlases(Atlas)
 );
 
 <Corporations>
 	<Row>
 		<ID>0</ID>					
 		<Type>CORPORATION_TRADER_SIDS</Type>				
 		<Description>TXT_KEY_CORPORATION_TRADER_SIDS</Description>
 		<HeadquartersBuilding>BUILDING_TRADER_SIDS_HQ</HeadquartersBuilding>
 		<OfficeBuilding>BUILDING_TRADER_SIDS</OfficeBuilding>	
 		<FranchiseBuilding>BUILDING_TRADER_SIDS_FRANCHISE</FranchiseBuilding>
 		<PortraitIndex>1</PortraitIndex>
 		<IconAtlas>CORP_ATLAS</IconAtlas>
 	</Row>
</Corporations>
```

This is work I'd do after the Corp Overview is done and reconciled. This will make it easier to manage and mod.

Thoughts?

**Comment by LoneGazebo** [comment]
That makes sense to me, yep. I considered that when first designing them, but decided against it (as all the data I absolutely needed could be stored in buildings).

**Comment by mwhiter** [comment]
@LoneGazebo RE: spreading franchises

Is it intended to be able to spread a Franchise to your own city? Are there any restrictions (other than max number of franchises you can build) to prevent this from happening?

**Comment by LoneGazebo** [comment]
Franchises only spread on international routes. If you're seeing the franchise count (or franchises in owned cities) go up, that's probably because the player took nationalization in Order.

**Comment by LoneGazebo** [comment]
And yeah, franchises go both ways, so your example is correct (except Player P can't spread franchises to owned cities).

Offices are for owned cities, Franchises are for foreign cities.

**Comment by mwhiter** [comment]
Okay thank you. That fact wasn't clear to me in the code. I'll add an explicit check for my new function.

What can modify the number of franchises? Isn't it a set number?

**Comment by mwhiter** [comment]
also, this snippet of code here confuses me:

```
int iBase = GetTrade()->GetNumTradeRoutesPossible();
	iBase *= 2;
	int iMax = (iBase * GC.getMap().getWorldInfo().GetEstimatedNumCities());
	iMax /= 100;
	if (iMax > iBase)
	{
		iMax = iBase;
	}
	int iBonus = 0;
	if (GetCorporationMaxFranchises() > 0)
	{
		iBonus = (iMax * (100 + GetCorporationMaxFranchises()));
		iBonus /= 100;
		iBonus -= iMax;
		if (iBonus <= 0)
		{
			iBonus = 1;
		}
	}
	iMax += iBonus;
	return iMax;
```

Was it intended that the trade routes * 2 be the maximum? Because the variable "iMax" is being bounded to that and can't be larger, but it's supposed to be the maximum. I'm not sure what rules are supposed to define the maximum number of Corporations. I'm confused. Base would imply that it's the starting point or lowest number you can have.

**Comment by LoneGazebo** [comment]
Yeah, map size varies greatly in terms of that variable, so I opted to have TRx2 be the limit. I'm not tied to it, so if you have an alternative scaler, feel free. Any more than around 12-15 franchises gets out of hand on terms of bonuses.

**Comment by mwhiter** [comment]
There is a lot of work and refactoring going into this (which will make it a joy to test and merge, yayyy!!!

However, this also reduces iteration by a ton. I think the game will be much faster (and more maintainable) when you don't have to loop through every building in the game.

**Comment by mwhiter** [comment]
Also, I see. I've changed the function to this:

```
// How many franchises can we establish?
int CvPlayerCorporations::GetMaxNumFranchises() const
{
	if (!HasFoundedCorporation())
		return 0;

	CvCorporationEntry* pkCorporationInfo = GC.getCorporationInfo(GetFoundedCorporation());
	if (pkCorporationInfo == NULL)
		return 0;

	int iReturnValue = 0;

	// We cannot have more franchises than twice the number of trade routes we can establish
	int iMaximum = m_pPlayer->GetTrade()->GetNumTradeRoutesPossible() * 2;

	iReturnValue = iMaximum * GC.getMap().getWorldInfo().GetEstimatedNumCities();
	iReturnValue /= 100;

	// Do not go above the defined maximum
	iReturnValue = std::min(iReturnValue, iMaximum);

	// Do not go above the defined maximum for this corporation info
	iReturnValue = std::min(iReturnValue, pkCorporationInfo->GetMaxFranchises());

	// Add in any "bonus" franchises from policies
	iReturnValue += GetAdditionalNumFranchises();

	return iReturnValue;
}
```

The biggest difference here is that instead of additional franchises being some sort of modifier (which didn't make sense to me when I tried to match the values, admittedly), you can just specify how many additional ones you get. Also I'll add the ability to make this a modifier (so you can specify how many % extra franchises you get, like double, etc.

**Comment by LoneGazebo** [comment]
Careful on that last point - the reason I used it as a modifier (instead of a flat value) was because it doesn't scale well with map sizes otherwise. That's used by ideological policies, and right now they scale with mapsize. You should set it to be:

iReturnValue  *= (100 + GetAdditionalNumFranchises();
iReturnValue /= 100;

G

**Comment by mwhiter** [comment]
I hear you. I will allow both, and have the default be 0 (might hook up other systems to be able to set both).

Really, a big point here to allow more modding, so some people may want to do that.

**Comment by LoneGazebo** [comment]
Sounds good, so long as the scaler value remains I'm fine with however you decide it should look.

**Comment by mwhiter** [comment]
If I am building Corporation A, can I build Corporation B in a different city?

If not should Corporation B appear greyed out in that city?

**Comment by LoneGazebo** [comment]
It should probably be greyed out, yep. I just need to have it check for the same building being constructed elsewhere.

**Comment by mwhiter** [comment]
You can check it for CBP, but the code that powers that screenshot is must different than what powers master.

I'll make it greyed out on my end. :)

**Comment by LoneGazebo** [comment]
Sounds good.

**Comment by mwhiter** [comment]
So if I'm right, if you wanted to make that change you need to include a !bTestVisible to the chunk of code that controls whether or not you can build headquarters if you're already constructing a headquarters in any other city in CvCity::canConstruct().

Tested it out in game with my code:

![image](https://cloud.githubusercontent.com/assets/4925402/14582732/3608203a-03db-11e6-9cd6-42f43c1ddcc0.png)

**Comment by mwhiter** [comment]
Also, getting this runtime error:

```
C:\Users\mjwhi\OneDrive\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch (v 79)\LUA\InfoTooltipInclude.lua:827: attempt to index local 'pCity' (a nil value)
```

Have you see this error before? Is it fixed in a later version that I should ignore?

**Comment by LoneGazebo** [comment]
That can happen if something is breaking in the getcityhappinesstooltip element - are you getting a database error?

**Comment by LoneGazebo** [comment]
And yeah, your testvisible element is correct.

**Comment by mwhiter** [comment]
i am getting database errors related to missing corporation texts, because I haven't defined them yet.

**Comment by LoneGazebo** [comment]
that might be causing the lua to break, not sure.

**Comment by mwhiter** [comment]
Does Globalization still provide 20% to the franchise maximum? Looking around in master and I see no references to it.

**Comment by LoneGazebo** [comment]
Not right now, no. I believe I removed the value when the struct changes were discussed.

**Comment by LoneGazebo** [comment]
You can just add <MaxCorporations>20</MaxCorporations> to it.

**Comment by mwhiter** [comment]
My question is -> is that intended? I just want to get to a state that replicates current functionality.

**Comment by LoneGazebo** [comment]
Yeah, that's intended, I just removed it for the time being.

**Comment by mwhiter** [comment]
![image](https://cloud.githubusercontent.com/assets/4925402/14588892/0a8ae3ca-04a3-11e6-868c-a74ec6a8bdf0.png)

feedback?

**Comment by LoneGazebo** [comment]
Snazzy! Very fancy, I dig it. On the 'Home Page' element, we should probably copy the concepts section I wrote for corporations and put it there.

G

**Comment by mwhiter** [comment]
![image](https://cloud.githubusercontent.com/assets/4925402/14590242/db9a8a40-04c3-11e6-876b-0651f310055a.png)

More complete version

**Comment by LoneGazebo** [comment]
Very cool. I like where this is headed. 

If there's any one thing I was on the fence about (from the very beginning) it was only allowing the player to found one corporation. With the struct system, we could structurally change that, but it would require a lot more UI manipulation in the corporation overview you created. I guess, theoretically, you could use the tab system (i.e. the little click drop down button menu) to switch between corporations, but it would be a chore. Not to mention that the corporation spreading system would be completely broken. I'm still happy with the one player: one found rule, but I'm not sure where you stand on it.

**Comment by mwhiter** [comment]
I'm treating Corporations like Religion: allowing a player to found more than one seems like it would just cause him to become an overwhelming force. Keeping it at one corporation can allow players to make more meaningful choices as well as making them easier to balance. Keep it as is!

**Comment by LoneGazebo** [comment]
Glad we agree on that. Do you still need that atlas? I can provide.

**Comment by LoneGazebo** [comment]
Here's a link: https://mega.nz/#F!TI0VyTpK!4i5vi06pvGLHbvOmHuPPWg

Overwrite the corp art files in the CBP modules folder. The icons are 22, 23, 24 in CORP_ATLAS.

**Comment by mwhiter** [comment]
Thank you! Will hook-up tonight!

**Comment by LoneGazebo** [comment]
Still waiting on wodhann for other images, though he may not budge on the weird sid graphic. As such, I may go ahead and work up the rest myself.

**Comment by mwhiter** [comment]
Take your time, there is so much more work to be done!

**Comment by mwhiter** [comment]
However I am pretty confident on the functionality of the overhaul, got it working for tge corporations overview ans everything seems so much easier to code and more stable

**Comment by LoneGazebo** [comment]
Awesome. I'm probably going to release an additional beta tonight for testing, and then I'll wait for your rework for the next beta (before an official release).

**Comment by mwhiter** [comment]
![image](https://cloud.githubusercontent.com/assets/4925402/14622147/f160a6ca-0595-11e6-9733-06d5c70ca683.png)

Hopefully looks good in-game!

**Comment by LoneGazebo** [comment]
Sweet! Did you have to create frames for it? I figured it auto-added the framing elements.

**Comment by mwhiter** [comment]
Nope, I had to create that manually! :(

**Comment by LoneGazebo** [comment]
Looks good!

**Comment by mwhiter** [comment]
someone else who is actually artistic can do a better job than I at this

**Comment by LoneGazebo** [comment]
Haha. I think it looks fine. If, however, it looks out of place in-game, let me know and I'll take a stab.

**Comment by mwhiter** [comment]
![image](https://cloud.githubusercontent.com/assets/4925402/14622377/7a889baa-0597-11e6-89f3-a02499093d2a.png)

![image](https://cloud.githubusercontent.com/assets/4925402/14622378/827ef2aa-0597-11e6-9be6-127318510b7b.png)

![image](https://cloud.githubusercontent.com/assets/4925402/14622384/91a6805e-0597-11e6-9bd5-bb41df157202.png)

**Comment by mwhiter** [comment]
It would appear that it is not consistent with BNW styling. :(

**Comment by LoneGazebo** [comment]
Oh no! Did you use the G&K example? The blue colors are G&K.

**Comment by LoneGazebo** [comment]
I can work on it for you later if you want to leave it for now.

**Comment by mwhiter** [comment]
yep. it works in-game. All that needs to be done is a graphical update, but i have the .dds file name.

which is civilopediatopbuttonscorporations.dds

**Comment by LoneGazebo** [comment]
Cool. I'll give it a whirl.

**Comment by mwhiter** [comment]
I definitely prefer offloading artwork to others - I am miserable at it.

**Comment by LoneGazebo** [comment]
haha. no worries, I've had to buckle down and get artsy over the years, so I don't hate it anymore.

**Comment by LoneGazebo** [comment]
[civilopediatopbuttonscorporation.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/225200/civilopediatopbuttonscorporation.zip)

Here's the icon set. I just made a new one using the gold template. Cheers!

**Comment by mwhiter** [comment]
thanks! looks great!

**Comment by mwhiter** [comment]
So this has been going slow because I don't have time to develop it. The weekend of April 30th, May 1st should probably be more convenient for me to work on it. Not sure how much work is left on this, probably a lot because it's still in its infancy in terms of being moddable (atm it's just a port of Corporations to a new backend with a new civilopedia and stabilized Corporations Overview).

It's such a big overhaul that I'll definitely need some proper testing and people testing it need to be aware that it's potentially very unstable - does it make sense to leverage the Beta's out of this? I feel like people treat Beta as a playable version and they get mad when it doesn't work, when it reality it should be a separate build from the main, stable version.

I honestly propose a separate alpha build (different mod ID of the CPP) for this purpose, because the normal Beta would be more stable that changes that I'll be making.

**Comment by LoneGazebo** [comment]
People get upset about everything. :) The beta is fine – I'm okay with telling every beta user that they're testing an unstable release (as I did with the CP:E). I've also been insanely busy as of late, and my schedule frees up around the time that yours does. If there's something I can help with at that time, let me know.

**Comment by mwhiter** [comment]
http://forums.civfanatics.com/showthread.php?t=567403

**Comment by mwhiter** [comment]
@LoneGazebo do you plan on updating master soon? i have created my helper branch with the latest master. should i expect to have to pull again? will the amount of changes i have ( a lot ) that would be a bad idea to have to pull again

**Comment by LoneGazebo** [comment]
I updated master last night.

**Comment by mwhiter** [comment]
That's fine, because I just pulled from it. I was wondering if you were planning to do it again in the near future that I should hold off on.

**Comment by LoneGazebo** [comment]
I'll be out of town for a week or so, so no, no plans in the near future.

**Comment by mwhiter** [comment]
okay. It's dawned on me i don't have enough time in the near future to do this and have a personal life. The reconciliation effort to port my code to the new master is very high (because auto-merging won't work) and integration will mean a lot of tests. I'll delay this for a month or so to early July when I'll be on a vacation.

**Comment by LoneGazebo** [comment]
No worries. I just got off a major project that I'm tidying up, and I'm behind on merges myself. Take your time!

**Comment by mwhiter** [comment]
:) 

Is there anyway we can fix this merging issue, or help the integration process?

**Comment by LoneGazebo** [comment]
Is the code on your end done? If so, just send me your DLL source files and I'll do a manual merge.

**Comment by mwhiter** [comment]
they are on my branch corp-dev

**Comment by mwhiter** [comment]
i can't confirm they are done because they're not tested with latest master. so merging into a helper branch (corp-helper) that is a clone of master is smarter

**Comment by LoneGazebo** [comment]
Now that we're done with this, I'm closing this issue.
