### ISSUE TITLE
Game.IsInReligion(beliefID, religionID) request

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1542]
Would a more specific function akin to Game.IsInSomeReligion() (a pre-existing method) be possible? This, something like **Game.IsInReligion(beliefID, religionID)**, would be used to check that a specific belief is in a specific religion. This would save my having to iterate Game.GetBeliefsInReligion(religionID) quite frequently to retrieve this information, though obviously there are more pressing moddings going on, so not a priority, if possible at all. Thanks!

**Comment by LoneGazebo** [comment]
Done. It'll be: Game.BeliefIsInReligion(eReligion, eBelief).

**Comment by JFDaly** [comment]
Brilliant, thank you!

**Comment by LoneGazebo** [comment]
I was just about to upload a beta, so it'll be yours shortly. :)

**Comment by JFDaly** [comment]
Did you mean to add this in the April 5th beta? If so, the method doesn't appear to have been exposed to Lua properly: "attempt to call field 'BeliefIsInReligion' (a nil value)"

**Comment by LoneGazebo** [comment]
It is, but I misspelled it! BeliefsIsInReligion (I'll change for next one to beliefis)
