### ISSUE TITLE
Can't compile DLL with Active AI enabled

### ISSUE THREAD

**Issue by LynnesCFC** [LoneGazebo/Community-Patch-DLL#1546]
@Iamblichos

Hello,
when I enable Active AI and try to compile the DLL, I get the following errors

> 1>  CvDiplomacyAI.cpp
> 1>CvDiplomacyAI.cpp(16072): warning C4805: '==': unsecure combination of type 'PlayerTypes' with type 'bool' in an operation
> 1>CvDiplomacyAI.cpp(18267): error C2065: 'DIPLO_HUMAN_PLAYERS': undeclared identifier
> 1>CvDiplomacyAI.cpp(38003): error C2065: 'DIPLO_HUMAN_PLAYERS': undeclared identifier
> 1>  CvDiplomacyRequests.cpp
> 1>CvDiplomacyRequests.cpp(478): error C2065: 'DIPLO_HUMAN_PLAYERS': undeclared identifier

It would be nice if you could have a look. :)
Thanks!

**Comment by Iamblichos** [comment]
@LoneGazebo is this thing ready for prime time yet?

**Comment by LoneGazebo** [comment]
What do you mean? I included it in the latest CP, though I did not check it for activation. Those bugs seem to appear when you enable the active AI diplomacy define. Possibly a merge error?

**Comment by Iamblichos** [comment]
I'll look into it.

**Comment by Iamblichos** [comment]
ah...it looks like G removed the enum for DIPLO_HUMAN_PLAYERS

**Comment by Iamblichos** [comment]
the first error is just a simple code error...can fix that.

**Comment by LoneGazebo** [comment]
I didn't remove nothing! :) Just made the merge.

**Comment by LynnesCFC** [comment]
Cool, can you please let me know when it's fixed on github? So I can upload the 4/5-modpacks. :)

**Comment by Iamblichos** [comment]
actually you did...I noticed you had the DIPLO_HUMAN_PLAYERS in the enum and then removed in one of the beta iterations on here for events (or might've been the alpha), was curious why it was removed.

**Comment by Iamblichos** [comment]
no biggie let me fix this up real quick.

**Comment by LoneGazebo** [comment]
I don't recall removing it – might've been a merge conflict, truth be told, as I had a bear of trouble getting it all online and up to date.

**Comment by Iamblichos** [comment]
okay I successfully built now with corrections.

**Comment by LoneGazebo** [comment]
Thanks @Iamblichos

**Comment by Iamblichos** [comment]
Bravo. Done.

**Comment by LynnesCFC** [comment]
Thanks a lot!

**Comment by Iamblichos** [comment]
Lynnes you can go grab the master repository and try your build now.

**Comment by LynnesCFC** [comment]
I already did, everything works fine now! :)
