### ISSUE TITLE
Issue with moving air units

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1549]
Related to movement/air unit changes as of late, or an EUI bug?
http://forums.civfanatics.com/showpost.php?p=14225071&postcount=4888

**Comment by ilteroi** [comment]
he says 3/23 so no new issue .. will check

**Comment by LoneGazebo** [comment]
Sorry, I guess by 'new' I meant 'since work was done on rebasing.'

**Comment by ilteroi** [comment]
i can confirm that you can rebase air units by right-dragging.

don't think that it used to be like that. but the turn is ended, so no problem? 

except that the indicator circle is red, so it looks like the move is not allowed, but it works.

**Comment by LoneGazebo** [comment]
Yeah, use the EUI in the auto-installer to get access to the firetuner again. bc1 hasn't updated it officially (and may be AWOL permanently), so the fix in the CPP distribution is the best we have for now.

**Comment by ilteroi** [comment]
nope - nothing to fix here, except the misleading indicator?

**Comment by LoneGazebo** [comment]
Okay, I'll close.
