### ISSUE TITLE
corporations art folder massive recursion!

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1553]
FYI

https://github.com/LoneGazebo/Community-Patch-DLL/tree/master/Community%20Balance%20Patch/Modular%20Elements/Corporations/Art

**Comment by mwhiter** [comment]
Fixed and pushed. Don't like doing that directly to master, but it was necessary.

**Comment by LoneGazebo** [comment]
That happens sometimes with modbuddy, is an ancient and stupid bug. Thanks for the fix!
