### ISSUE TITLE
Events are active for Community Patch

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1557]
Forgive me if I'm wrong, but is Events intended to be a feature enabled in the "Community Patch", not Community Balance Patch?

I am seeing the "Active Events Overview" with Community Patch and C4DF - CP enabled only.

**Comment by LoneGazebo** [comment]
It is enabled by default in the CP until testing is complete. Once complete, I'll be adding a check to remove UI stuff unless it is specifically enabled.

G
