### ISSUE TITLE
COM Pathing

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1559]
@ilteroi,

Seeing a lot of bad pathing in the latest:

Pathing lost en route due to a bad COM computation!

Happens primarily for naval moves, and is not a pre-ocean moves problem.

**Comment by LoneGazebo** [comment]
Update on COM issue @ilteroi , seems it actually is somehow related to ocean tiles and/or pathing that switches domains during the pathing process. I can't pin it down beyond that, but that should help some.

**Comment by LoneGazebo** [comment]
And one last thing (sorry for deluge, first day I've spent debugging non-event stuff in some time): I'm still seeing the AI 'dance' on the edge of a city's attack range instead of moving in for the kill. Switching tactical postures around a bit has helped some,but the AI seems extremely unwilling to engage on cities (especially with naval units, though that may be related to the pathing issue above).

**Comment by ilteroi** [comment]
hmm. been quite a while since i touched anything there

**Comment by ilteroi** [comment]
what i want to say is, i don't have the slightest idea what could be the reason

**Comment by LoneGazebo** [comment]
Walking along with the pathfinder in the generate path function, it appears that the pathfinder is simply not able to use the GetBest() function to grab a tile if it crosses an ocean and/or changes domain. I don't know if that is because the 'cost' of ocean tiles is too high, or something else, but the AI is clearly only moving its units (in formations) along the coastlines and/or on land.

**Comment by LoneGazebo** [comment]
It can move units across the ocean independently, which makes me think the bug might be with: 

	PT_GENERIC_SAME_AREA,		//plots must have the same area ID (ie only water or only land)
	PT_GENERIC_ANY_AREA,		//plots can have any area ID, simply need to be passable
	PT_GENERIC_SAME_AREA_WIDE,	//path must be 3 tiles wide (for armies)
	PT_GENERIC_ANY_AREA_WIDE,	//same for any area

**Comment by LoneGazebo** [comment]
If the path is looking at water tiles, it'll be really hard for a three-tile-wide path to exist directly to a city. Same if it is switching domains.

**Comment by LoneGazebo** [comment]
The AI is have zero problems on land with all of this, which is why my money is on the domain switch being a problem.

**Comment by LoneGazebo** [comment]
Removing references to _WIDE pathing logic above seems to have reduced the number of bad COM pathfinding errors by about 50%.

**Comment by ilteroi** [comment]
well, no surprise that a wide path is harder to find than a normal one.

will check

**Comment by LoneGazebo** [comment]
Indeed, but it didn't seem to adversely affect the AI. Either that needs to be changed, or we need to use a wide path pre check for operations so that the AI only targets cities it has a wide path towards to begin with.

**Comment by ilteroi** [comment]
well, maybe for naval ops the wide paths aren't so important - they are faster and there are no rough features slowing them down.

**Comment by ilteroi** [comment]
also, operations are only started if there's a wide path (depending on number of units). for land based operations :)

naval ops simply check if there is a trade path. if it passes through a fort or a similar bottleneck, there will indeed be a problem.

**Comment by LoneGazebo** [comment]
I did some really crunchy digging and found that one of the problems was if a city target was in a cove- i.e. there weren't three distinct water tiles next to the city. That seems like the likely culprit for the COM bugs. Switching away from wide seems to have fixed part of the problem, but I still see the AI hugging the coastline (to the point that the CoM distorts and moves onto land) even when it has ocean travel.

**Comment by LoneGazebo** [comment]
I also fixed some other bugs in the DLL related to operations and military targeting. Turns out that the refactoring of city strength made it so that all cities appeared horribly impossible to conquer (from the perspective of the scoretarget element of the militaryAI).

**Comment by LoneGazebo** [comment]
I also made it so that naval superiority moves on the defensive don't 'succeed' when they reach their target- they'll behave a bit more like hedgehog moves.

**Comment by ilteroi** [comment]
sounds good. pushing my changes right now.

reworked the logic regarding wide paths (only land ops now) and same area paths (only naval now). plus some other small changes. let's hope there isn't too much overlap with your changes.

i didn't switch to 4/5 yet, but you should be able to rebase my commit.

**Comment by LoneGazebo** [comment]
Shouldn't be. I'll just look at the commit and do a manuel merge. I added a military target cache clear whenever an AI operation aborts for a bad reason – the AI was often attempting the same failed operations over and over because the militaryAI was telling it to. 

Also, makes sense that land ops should be the only ones doing wide ops. I think that'll fix the biggest issue (as the AI was starting naval ops, then trying to get there and failing, over and over again).

Keep in mind that some mapscripts can allow for connected oceans to be different areas, but that's just life.
