### ISSUE TITLE
Corporations Overview and EventChoicePopup share same BUTTONPOPUP

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1560]
Title is as descriptive as it gets.

Both share BUTTONPOPUP_MODDER_10.

**Comment by LoneGazebo** [comment]
Oh boo, seems we each went after the second-highest button #. What _# does the vassal overview use? 11?

**Comment by mwhiter** [comment]
Yes, ButtonPopupTypes.BUTTONPOPUP_MODDER_11

I'm thinking we need to start defining our own ButtonPopupTypes.

**Comment by LoneGazebo** [comment]
Perhaps. The DLL claims that's a bad idea, though, probably because of the netcode.

**Comment by mwhiter** [comment]
After looking at it, it might be possible to modify, but we can't change that enum directly, have to use FString::Hash("BUTTONPOPUP....").

Further investigation (or perhaps if someone has successfully done it) is needed...

**Comment by LoneGazebo** [comment]
You could probably ping whoward on this, he tends to have answers for questions that I didn't know I needed to ask. :)

**Comment by LoneGazebo** [comment]
Fixed, I adjusted CorpOverview to use _5.

G

**Comment by mwhiter** [comment]
Alright, so we should close this?

**Comment by LoneGazebo** [comment]
Yep!
