### ISSUE TITLE
FreeBuildings column in Buildings question.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1561]
If I had a building that duplicated itself using the FreeBuildings, how would it react over time?
Ex. (We have only two cities and Building1. Building1 in City1 duplicated Building1 in City2 Would Building1 in City2 duplicate itself again in City1 creating errors?)

I'm trying to reduce the amount of turn processing by removing PlayerDoTurn to add buildings when someone settle or capture another cities. By having the FreeBuilding column of a building add itself. That way I don't need to worry about original capital cities lost or having to fire up functions for cities recaptured or founded.

**Comment by LoneGazebo** [comment]
I'm honestly not sure.

**Comment by TechpriestEnginseer** [comment]
Because what I'm afraid of is when they duplicate the same building, the duplicated building will duplicate the original building and hit a loop of duplicating until a global scale of duplication occurs.

**Comment by LoneGazebo** [comment]
There's only one way to find out...

**Comment by TechpriestEnginseer** [comment]
So, far I've played the game for 50 turns and it doesn't seem to be game-crashing yet.

**Comment by TechpriestEnginseer** [comment]
So, ironically a user did find a problem with FreeBuilding that was difficult to see. It has duplicate properties, but only on some of the tables. Apparently, a building of the free building of itself will produce double the unitcombatproduction modifier (+33% becomes +66%). This isn't an issue(I'll just have to import the buildings into events now) since I knew that a bug would break, but just for future documentation.

**Comment by LoneGazebo** [comment]
Interesting!
