### ISSUE TITLE
Free buildings from tenets

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1562]
A small thing I noticed:
I have the Order tenet that gives free museums.
However, some conquered cities don't have them.
Could it be that they had the building, it get's destroyed upon capture, and some timing issue prevents the tenet from placing the building then?

**Comment by LoneGazebo** [comment]
Free buildings are distributed after capture, not before, so it shouldn't be a problem. Any special circumstances?

**Comment by Der-Zorn-Gottes** [comment]
None that I noticed.
