### ISSUE TITLE
Negative Flavor

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1564]
How do AIs react to this?

I remembered a thread on Civfanatic where negative flavor would make the AI have a midlife crisis.

I'm interested because I'm looking if the AI is willing to favor some choices over other because they may have a penalty. (If I don't have any good production, maybe I shouldn't take this choice if it has a production penalty!)

**Comment by LoneGazebo** [comment]
For events?

**Comment by TechpriestEnginseer** [comment]
Yes.

**Comment by LoneGazebo** [comment]
They'll calc it just fine - goes into the sum total value for the choice, so negative will dissuade properly.
