### ISSUE TITLE
Fighter promotions

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1565]
There are two promotions with different names but exactly same effect:
![20160408202512_1](https://cloud.githubusercontent.com/assets/16065630/14404331/3936b8ba-fe73-11e5-9547-d80677ab0d7a.jpg)
![20160408202514_1](https://cloud.githubusercontent.com/assets/16065630/14404333/449fc728-fe73-11e5-9ec1-043462c42a06.jpg)

**Comment by LoneGazebo** [comment]
One can be earned, the other is bonus only. Intentional.

**Comment by Der-Zorn-Gottes** [comment]
What does bonus only mean?

**Comment by LoneGazebo** [comment]
Sorry, was on mobile. What I meant to say is, one comes from finishing Imperialism (IIRC) and, in order to prevent it from giving you access to the upper echelons of the promotion tree, I used a 'unique' promotion for the slot.

**Comment by Der-Zorn-Gottes** [comment]
But i picked order in this game, and I could select both as regular picks when the unit levelled up.

**Comment by LoneGazebo** [comment]
Huh, odd.

**Comment by LoneGazebo** [comment]
I'l take a look.

**Comment by LoneGazebo** [comment]
Did you also take imperialism?
