### ISSUE TITLE
AI users cleaning fallout

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1566]
Last game, there was fallout in AI territory. It sent a lot of workers to those tiles, but once I conquered the area, my workers still had to spend the full time to clean fallout. (AI workers spend several turns on the tiles).
Could it be that the damage they take each turn makes the AI interrupt the work and set them to heal, which would never succeed on a fallout tile?

**Comment by LoneGazebo** [comment]
Might've been at war, or dangerous territory.

**Comment by Der-Zorn-Gottes** [comment]
They were at war, but he didn't retreat them.They were standing on fallout times for several turns, but apparently didn't clear the fallout.

**Comment by LoneGazebo** [comment]
I'll keep an eye on it. I fixed a bug in this recently - which version were you on?

**Comment by Der-Zorn-Gottes** [comment]
Not the most recent - 18/3 I think. 
Sorry for not making it clear.

**Comment by LoneGazebo** [comment]
Let's keep an eye on it.
