### ISSUE TITLE
Behavioural Observation

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1568]
In my game India were quite fond of taking over city states. I thought this was strange as they had maxed statecraft. In one case, it was their own ally who was invaded by barbs, they took the city but puppeted instead of liberated. Seems sub-optimal to me.

**Comment by LoneGazebo** [comment]
If the AI feels cramped, or otherwise wants a city, they'll annex/puppet instead of liberating.
