### ISSUE TITLE
CS "Build Wonder" quest not completing in 9 April beta version

### ISSUE THREAD

**Issue by Guynemer** [LoneGazebo/Community-Patch-DLL#1569]
Received a quest from Bratislava to build Stonehedge.  Built it, but the quest did not complete, and remains active.  Other CS quests seem to be functioning normally.

Other mods used: Quick Turns, InfoAddict

[Aztec.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/211568/Aztec.zip)

**Comment by Radost** [comment]
May be related, but civilization ribbons don't show the Wonders they have:
![8930_20160410072222_1](https://cloud.githubusercontent.com/assets/1131228/14407704/31caebda-feed-11e5-976a-f87c12cb1898.png)
![8930_20160410072228_1](https://cloud.githubusercontent.com/assets/1131228/14407705/3404c2e0-feed-11e5-83bf-6197f87e346a.png)

**Comment by LoneGazebo** [comment]
Odd- I haven't touched that code, but I'll take a look. Thanks!

**Comment by LoneGazebo** [comment]
Fixed - a bad pointer was moving into the table. Shouldn't affect save games.

G
