### ISSUE TITLE
barbarian conquest of city states

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1570]
in my current game i see 4 city states conquered by barbarians.

one happened right in front of me. barbarian uprising. tried to help them, everything was looking good, city is not even damaged. but the next turn the barbarians own it. how can that be? is it intended that way?

**Comment by TechpriestEnginseer** [comment]
If a barbarian is in any city-state tile during the barbarian uprising. It is considered taken. Part of CSD's logic.

**Comment by ilteroi** [comment]
well then ...
