### ISSUE TITLE
great prophet conversion

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1571]
just tried to convert an enemy city to my religion.

the majority religion was eliminated - however the city did not convert to my religion but to a third one, which already had some followers in the city before.

is that intended?

**Comment by TechpriestEnginseer** [comment]
Maybe the third religion had such a strong religious pressure but wasn't strong enough to succumb the majority religion that your prophet led them to become the majority.

**Comment by LoneGazebo** [comment]
Yep!

**Comment by ilteroi** [comment]
how can there be two religions which are both the majority?

**Comment by TechpriestEnginseer** [comment]
Say I have a city with 1400 Christianity, 1100 Islam, and only 200 Judaism pressure.
I get this Judaism Great Prophet to delete some pressure off Christianity, let's say 800?
Now the city has 600 Christianity, 1100 Islam, and only 1000 Judaism. Now Islam becomes the majority despite the prophet adding in religious pressure from Judaism and eliminating the majority's pressure.

**Comment by ilteroi** [comment]
well. i thought a majority religion needs at least 50% of the population as followers?

i'm not sure what role pressure alone can play.

**Comment by Radost** [comment]
Of all three religions, which one had Resilience?

**Comment by ilteroi** [comment]
good point. it seems catholicism had resilience. but it seems there is a bug with it? it goes from 10 followers to 16!

before:

![image](https://cloud.githubusercontent.com/assets/1358966/14439640/6da3d64a-002c-11e6-858c-2ea9c6452959.png)

after:

![image](https://cloud.githubusercontent.com/assets/1358966/14439640/6da3d64a-002c-11e6-858c-2ea9c6452959.png)

**Comment by ilteroi** [comment]
indeed, catholicism has resilience? but it seems there's a bug with it?

before spreading zoroastrianism:

![image](https://cloud.githubusercontent.com/assets/1358966/14439696/c61c86fa-002c-11e6-84d6-90e3603149dd.png)

after:

![image](https://cloud.githubusercontent.com/assets/1358966/14439708/d244d5fe-002c-11e6-97ac-9c761db7655e.png)

**Comment by LoneGazebo** [comment]
I haven't looked at resilience, but it looks like the resilience code is designed to give equal and opposite pressure when you try to convert a city.

**Comment by ilteroi** [comment]
so is this intended or not? i find it a little counterintuitive that another religion would profit from my great prophet and go from 10 followers to 16.

**Comment by LoneGazebo** [comment]
I have no idea  – haven't look at the code.

**Comment by LoneGazebo** [comment]
I wiggled some code around a bit, maybe it'll fix it?
