### ISSUE TITLE
CityEventChoice_BuildingClassDestructionChance and EventBuildingClassDestruction

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1572]
1. Is it possible to put two more than CityEventChoice_BuildingClassDestrucitonChance into one event choice? (Ex. Can I have a choice where it destroys the market and the bank?)

2. How would more than two interact since they share the same function if 1 is actually possible.

**Comment by LoneGazebo** [comment]
Yes. It loops through all buildings in that table and the random value is done each time.

**Comment by LoneGazebo** [comment]
All those tables like that can support as many additional elements as desired.
