### ISSUE TITLE
Borked Bank description

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#1574]
![8930_20160411100749_1](https://cloud.githubusercontent.com/assets/1131228/14417358/a38525b6-ffcd-11e5-9a13-71d98e835e07.png)
I've got an event about "something artistic guilds decentralization" while having  0 Banks in the empire, if it's of any use.

**Comment by LoneGazebo** [comment]
Is this on the latest CP beta?
