### ISSUE TITLE
Issue with (City)EventCanTake()

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1577]
This event, which should allow the prevention of events, doesn't appear to work. Despite confirming that an event should not be able to trigger by tracing this game event through various print statements, it still does.

**Comment by TechpriestEnginseer** [comment]
Maybe it's what the GameEventTables says.
![image](https://cloud.githubusercontent.com/assets/13937047/14433928/2eaa1cd6-ffc5-11e5-99cd-48a866241272.png)

**Comment by LoneGazebo** [comment]
Here's what the lua function looks like in the DLL: 

```
//Lua Hook
			if (GAMEEVENTINVOKE_TESTANY(GAMEEVENT_EventCanTake, GetID(), eEvent) == GAMEEVENTRETURN_FALSE) 
			{
				continue;
			}

```

**Comment by LoneGazebo** [comment]
My text is correct in the table (a 'continue' is actually a 'false' within a for iterator, but that's not terribly clear viz a good continue). Anyways it should return false if you want it to not be allowed, and true if you want it to work properly.

**Comment by JFDaly** [comment]
Well, can you tell what's wrong with this code then:

function JFD_CulDiv_EventCanTake(playerID, eventID)
	local player = Players[playerID]
	local event = GameInfo.Events[eventID]
	if event.RequiredCulture then
		if JFD_GetCultureID(playerID) ~= GameInfoTypes[event.RequiredCulture] then
			print("returning false", event.Type)
			return false
		end
	end
	return true
end
GameEvents.EventCanTake.Add(JFD_CulDiv_EventCanTake)

If the player's Culture ID is different than the required Culture ID, the event shouldn't trigger - but it definitely still does.

**Comment by LoneGazebo** [comment]
Dunno, but I'll take a look later tonight. If you still have your DLL skills, you could stack walk at that point in the code and see where it goes to lua and back.

G

**Comment by LoneGazebo** [comment]
Also, stackwalker should totally be a Magic the Gathering monster type. 💃

**Comment by LoneGazebo** [comment]
I'll incorporate this change into the next DLL, btw. Let me know if it fixes it.

**Comment by JFDaly** [comment]
A rudimentary test proves optimistic - it looks like this change fixed the issue. We'll know for certain when I release these events for public testing.

**Comment by LoneGazebo** [comment]
Yay!

**Comment by LoneGazebo** [comment]
Closing and marking for now.
