### ISSUE TITLE
City:GetNumBuilding(buildingID) > 0

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1578]
It seems to me that any event building isn't technically real or something despite its effect and this seems to conflict with my modding heavily because I rely on title to determine whether or not the event building there exist to initiate something non-event related.

**Comment by LoneGazebo** [comment]
Are you on the latest 4/10 beta?

**Comment by TechpriestEnginseer** [comment]
4/9.

**Comment by LoneGazebo** [comment]
Hop on 4/10.

**Comment by TechpriestEnginseer** [comment]
I don't have the access to 4/10.

**Comment by LoneGazebo** [comment]
It is in the betas folder. I posted the hotfix yesterday.

**Comment by TechpriestEnginseer** [comment]
The problem is still persisting.

**Comment by LoneGazebo** [comment]
exist continue?

The getnumreal/getnumbuildings are working, so far as the core dll is concerned.

**Comment by TechpriestEnginseer** [comment]
Would the event continue on normally as it removed the lighthouse that never existed.*

**Comment by LoneGazebo** [comment]
it simply sets the value to zero, so if it is already zero, it doesn't matter.

**Comment by TechpriestEnginseer** [comment]
Never mind the problem was that I had two PlayerDoTurn with an older version and it was making that problem.

**Comment by LoneGazebo** [comment]
cool
