### ISSUE TITLE
UI Bug with 3/14

### ISSUE THREAD

**Issue by MorpheusAk** [LoneGazebo/Community-Patch-DLL#158]
I'm using EUI and all of the other mods in the compatibility suite. I've altered nothing from my mod directory except for deleting all of the old CBP-based files and installing the new ones.

In the new version, in the city view, all yields appear the green food icon.

**Comment by valentin-turcu** [comment]
I can confirm this bug exists in my save as well. Latest version, only the CBP mod pack.

**Comment by DomeFossil** [comment]
I also seem to have this bug. If you hover over the tile, the proper icons will show in the box, however
![2015-03-15_00002](https://cloud.githubusercontent.com/assets/11487030/6655972/9bd63652-cb17-11e4-8a93-4fe8f6e487ea.jpg)

**Comment by LoneGazebo** [comment]
Did you delete your cache?

**Comment by valentin-turcu** [comment]
Certainly, right before installing the new version of the CP and CBP. Started from scratch.

**Comment by valentin-turcu** [comment]
All right, so I'm just posting the solution I got from the civfanatics forums over here:

Navigate to: ~\Documents\My Games\Sid Meier's Civilization 5\MODS\Community Patch (v 66)\Core Files\PNM Mods DB\InGame and delete the two files in this folder.

It worked for me.

**Comment by mmermerkaya** [comment]
I still have this bug, and there is no InGame folder in my \Core Files\PNM Mods DB directory.

**Comment by banderolax** [comment]
i have got same situation like mmermerkaya. clearing cache outside mods folder didn't do the hob ;/

**Comment by earlyraven** [comment]
I too was having this issue... but I fixed it.  Here's how:  (the key for me was step 3)
1.  Exit game.
2.  Delete the cache (located in C:\Users\<User Name>\Documents\My Games\Sid Meier's Civilization 5\cache)
3.  Delete the folder C:\Users\<User Name>\Documents\My Games\Sid Meier's Civilization 5\MODS\Community Patch (6-27)\LUA
4.  Launch the game.
5.  Click Mod, check all desired mods, and click next/apply.
6.  Setup and start a game... everything should be good.

Note:  If loading you do have to go through the mod menu or other things might get messed up.

My source for discovering this fix was the 2nd and 3rd bullets from the "Final Install Steps" of http://forums.civfanatics.com/showthread.php?t=528034
"*If using the CBP, delete the LUA folder in the main Community Patch mod folder!
*If using one of the CBP Compatibility Mods, delete the LUA folder in the main Community Balance Patch mod folder!"

I had misread them as "one of these bullets applies" but actually it's "all of these bullets apply."

Hope this helps.
