### ISSUE TITLE
Crash to desktop during AI turn

### ISSUE THREAD

**Issue by pizzatroll** [LoneGazebo/Community-Patch-DLL#1580]
I've been playing my first game on the CBP (which is awesome by the way, major props!), and the game has been crashing to desktop during the AI turn. I have been able to replicate this very easily.

Active mods:
(1) Community Patch v.72
(2) Community Balance Patch v.13
(3) City-Sate Diplomacy Mod for CBP v.27
(4) Civ IV Diplomatic Features - CBP Edition v.10
(5) More Luxuries CBP Edition v.155
(6a) Community Balance Patch - Comopatibility Files (EUI) v. 1
JFD's Cultural Diversity (Core) v.3
EUI

There's a whole slew of inactive mods there too, but I don't know if that would affect anything.

I have attached the save file and the database.log file.

Thanks in advance!

[Civ 5 CBP Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/214031/Civ.5.CBP.Bug.zip)

**Comment by LoneGazebo** [comment]
As a rule, it is a good idea to remove inactive mods from your mods folder. The game can grab data from those mods even when inactive! 

I'll look at your report. Did you include the minidump file?

**Comment by pizzatroll** [comment]
I moved all of the inactive mods from the mods folder, and the crash still happened. Here's the most recent database.log file. Let me know if you need anything else. Thanks again.

[Database log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/214087/Database.log.txt)

**Comment by LoneGazebo** [comment]
You don't have logging enabled, unfortunately. Enable logging and try to load the game again. Then post your database.log.

**Comment by pizzatroll** [comment]
I updated to v7 because that was what you had in that link (and got a free gold resource by my capital on the update, score!), but it did crash again. I...think I got the logging right this time. I followed the instructions from [here](http://forums.civfanatics.com/showthread.php?t=487482) at least.. 
[Database log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/220062/Database.log.txt)
