### ISSUE TITLE
Trade Deal bug, but this time an actual LUA error showed up

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1581]
Still getting the -2 turns trade deal issue, but for the first time that I've noticed, there's an error in the LUA log about, hopefully this will tell y'all at least a little something. Here it is:

[345795.046] Runtime Error: C:\Users\James\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Patch - Compatibility Files (EUI)\LUA\TradeLogic.lua:522: attempt to index field '?' (a nil value)

**Comment by pandasnail** [comment]
Ok so since I'm a bit of a hoarder and forget to delete old versions, I did some digging. I used a website that highlights differences. Putting up that tradelogic.lua file from 2/15, which I'm 99% sure doesn't have it and 2/24, where I noticed it first, there's four differences, but really one: four times a new function is added starting with 'if ( g_pUsTeam:IsAtWar( g_iThemTeam ) ) then' around lines 1166, 1194, 1224, and 1248.

Now what's noteworthy about that is that I also haven't gotten War Weariness in months and months. I play not that many modern era games, so I thought maybe possibly it was RNG luck. But now here's another IsAtWar check possibly causing an error, so I would guess there's some underlying issue with that for some percentage of users.

**Comment by pandasnail** [comment]
Found this too from another user, possibly related to this IsAtWar:  The only thing that comes to mind is that she was allied with 6 City States, 2 of which didn't declare war on me when she allied them (possibly a BUG),

http://forums.civfanatics.com/showpost.php?p=14230172&postcount=212

**Comment by LoneGazebo** [comment]
War Weariness doesn't rely on lua to calculate, though, so that can't be an issue. Remember that it only happens once you have an ideology.

Your first issue - the lua issue - just sounds like a bad value being passed into a function. I'll look. But I don't think there is anything systemically wrong with

**Comment by pandasnail** [comment]
I'm not saying I think this LUA error is causing lack of War Weariness. I'm saying that something with IsAtWar might be causing this LUA error, and if something is up with IsAtWar then that would also explain why I don't get war weariness. Related problems with the same core issue, not one causing the other. I'm aware that it takes til the late game to get war weariness, but I've played enough games into there, that its at least weird that I literally haven't gotten a point of it in months. Especially especially so if an ideology but only in the industrial era should allot it as well, I am unsure of that detail tho.

**Comment by LoneGazebo** [comment]
Lua errors like that aren't because of DLL bugs, they're because of bad values being passed into the display UI. Probably just an undefined value.

**Comment by LoneGazebo** [comment]
@Iamblichos , did you ever get anywhere with the phantom missing resources issue?

**Comment by Iamblichos** [comment]
Nope...I have found nothing in regards to this, and not a clue where it is coming from.

**Comment by LoneGazebo** [comment]
Hmm...

**Comment by LoneGazebo** [comment]
I'll keep an eye on it.
