### ISSUE TITLE
Events Building Yield Change Bug

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1583]
Report from the latest beta thread: 
"In my current game with Spain, I have received three different monument bonus from events (+1 gold, +1 faith, +1 culture, one per city) and one malus, -2 gold in all cities, from Small Ice Age event.
But, when I check in each city screen, I may see the malus effects on gold production, but I don't see at all the bonus from monuments. Am I missing something?

Editing: it looks that gold and culture bonus are there, but I don't see the +1 monument's faith in Madrid: Faith +11 (+8 from Buildings and +3 from Religion)

Buildings in Madrid: Palace (+3), Angkor Wat (+1), Statue of Zeus (+1), Stonehenge (+3)"

I also saw this once while testing one of my events. It was meant to give yields to the harbor, it didn't. Ok I mistyped something. But I went on testing and destroyed the harbor with another event decision. When I rebuilt it, it had the increased yields. Odd.

**Comment by LoneGazebo** [comment]
What version of the CP are you on?

**Comment by Hokath** [comment]
When I experienced that I was on the one before the current.
This guy I assume is on most recent since he was posting in that thread.

**Comment by LoneGazebo** [comment]
Well, I fixed a bug related to this in the 4/10 hotfix.
