### ISSUE TITLE
Feature Request: Notification when a Coup is possible to perform

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#1585]
With 10+ spies on a large map it becomes a chore to track all the cooldowns.

**Comment by LoneGazebo** [comment]
That's a good idea, though do you think it would simply add to the 'notification noise' on a big map?

G

**Comment by Radost** [comment]
Well, it probably will. But the underlying problem is Espionage interface being very clunky to begin with.

At least it will allow to perform them on semi-auto pace just by clicking through the events, assuming it would bring the Espionage window upon clicking on the notification (which is only brought up by "New Spies are available" and "Spy X ranked up") and bundle with other spy-related events.
