### ISSUE TITLE
Corporation overview window doesn't show franchises

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#1586]
![8930_20160414001556_1](https://cloud.githubusercontent.com/assets/1131228/14506369/dc357e6e-01d6-11e6-9c94-c0d0bf301863.png)
![8930_20160414001619_1](https://cloud.githubusercontent.com/assets/1131228/14506370/de426eb0-01d6-11e6-8e9e-9fc85853eb68.png)

**Comment by LoneGazebo** [comment]
Are you getting a lua error in your lua log? @mwhiter  would probably love to know.

**Comment by Radost** [comment]
http://pastebin.com/3txVj6Bc

**Comment by mwhiter** [comment]
Hey, sorry if I'm missing something. Can you show me and example of a city which should have a franchise but does not currently have one? Does that franchise show up on the world corporations tab?

**Comment by LoneGazebo** [comment]
I think what @Radost is saying is that the franchise list is only looping through major civs, when it should also be looping through CSs to look at franchises in those cities.

**Comment by mwhiter** [comment]
Okay that makes sense. I missed that bit. That sounds like a one line change!

**Comment by LoneGazebo** [comment]
Cool! I figured it might.

**Comment by Hokath** [comment]
came to report just this! beat me to it, damn

**Comment by mwhiter** [comment]
I should be able to work on this tonight. This week has been busy, sorry.

**Comment by mwhiter** [comment]
G, unrelated note to this, but since I'm here -  why is when I pulled from master EventChoice.mp3 could not be built because it wasn't found?

exact error message:

> Error	1	Could not copy the file "Core Files\CoreLua\EventChoice.mp3" because it was not found.	C:\Program Files (x86)\MSBuild\Firaxis\ModBuddy\Civ5Mod.targets	76	10	Community Patch

Goes away when I delete it from the solution.

**Comment by mwhiter** [comment]
[image](https://cloud.githubusercontent.com/assets/4925402/14546132/471f5566-0271-11e6-8696-11478915bb72.png)

issue has been fixed

**Comment by LoneGazebo** [comment]
Probably because the gitignore file. I'll fix.

**Comment by Radost** [comment]
Franchises list doesn't need the capital icon, as doesn't have any relevance to franchise status.
