### ISSUE TITLE
Kuna fix

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1588]
https://dl.dropboxusercontent.com/u/28753474/Kuna.rar
Fixed decal texture bug. Fixed brightness. Made model a bit bigger so they are easy to see in jungle. Fixed pillage smoke scale. Compressed dds files.
These 2 file were never used and should be deleted: hb_kuna_diff.dds, kuna_diff.dds.
Code for GKLeaderChanges.sql:
```
INSERT INTO ArtDefine_Landmarks (Era, State, Scale,	ImprovementType, LayoutHandler,	ResourceType, Model, TerrainContour) VALUES
('Any', 'UnderConstruction', 1.0, 'ART_DEF_IMPROVEMENT_KUNA', 'SNAPSHOT', 'ART_DEF_RESOURCE_ALL',		'hb_kuna.fxsxml', 1	),
('Any', 'Constructed', 1.0, 'ART_DEF_IMPROVEMENT_KUNA', 'SNAPSHOT', 'ART_DEF_RESOURCE_ALL',		'kuna.fxsxml', 1),
('Any', 'Pillaged', 1.0, 'ART_DEF_IMPROVEMENT_KUNA', 'SNAPSHOT', 'ART_DEF_RESOURCE_ALL',		'pl_kuna.fxsxml', 1);
```

**Comment by LoneGazebo** [comment]
Neat, thank you!

**Comment by qqqbbb** [comment]
I just realized that kuna_Pillage.gr2 can be deleted if you replace "kuna_Pillage.gr2" with "kuna_HalfBuilt.gr2" in pl_kuna.fxsxml.

**Comment by LoneGazebo** [comment]
Just FYI, the current Kuna doesn't clear away very much forest...any fix for that?

**Comment by LoneGazebo** [comment]
(with your fix)

**Comment by qqqbbb** [comment]
What do you mean? It should remove forest when built?

**Comment by LoneGazebo** [comment]
Coolio, thanks!

**Comment by qqqbbb** [comment]
https://dl.dropboxusercontent.com/u/28753474/Kuna2.rar
Forest near kuna now removed.

**Comment by qqqbbb** [comment]
You inserted new code into GKLeaderChanges.sql but did not delete old one. So the scale is wrong.
Here is new version: https://dl.dropboxusercontent.com/u/28753474/Kuna%20v2.rar  Forest that overlaps kuna is now removed.

**Comment by qqqbbb** [comment]
You replaced eki code with new kuna code and now eki is broken. This code should be in GKLeaderChanges.sql:
```
INSERT INTO ArtDefine_Landmarks(Era, State, Scale, ImprovementType, LayoutHandler, ResourceType, Model, TerrainContour)
SELECT 'Any', 'UnderConstruction', 1,  'ART_DEF_IMPROVEMENT_EKI', 'SNAPSHOT', 'ART_DEF_RESOURCE_ALL', 'eki_UC.fxsxml', 1 UNION ALL
SELECT 'Any', 'Constructed', 1,  'ART_DEF_IMPROVEMENT_EKI', 'SNAPSHOT', 'ART_DEF_RESOURCE_ALL', 'eki_built.fxsxml', 1 UNION ALL
SELECT 'Any', 'Pillaged', 1,  'ART_DEF_IMPROVEMENT_EKI', 'SNAPSHOT', 'ART_DEF_RESOURCE_ALL', 'eki_PL.fxsxml', 1;
```

**Comment by LoneGazebo** [comment]
Oops, fixed.

**Comment by qqqbbb** [comment]
You forgot to add new version: https://dl.dropboxusercontent.com/u/28753474/Kuna%20v2.rar

**Comment by LoneGazebo** [comment]
I thought I did?

**Comment by qqqbbb** [comment]
You did not.

**Comment by qqqbbb** [comment]
You forgot to add new version: https://dl.dropboxusercontent.com/u/28753474/Kuna%20v2.rar

**Comment by LoneGazebo** [comment]
Oh, this is in my dev build, but I forgot to move it to release. Whoopsie.
