### ISSUE TITLE
[4-9b] Barbarians inactive

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#1590]
Hi
Using the 4-9b (hot fix from 4-10) I see barbarians idle at my city borders. They just seem to stand there doing **nothing**. 

I use a lot of other mods and I suppose one of them might conflict with CPP but as I saw another user posting the same issue on DivFanatics I'm posting it here without testing with CPP only.

\Skodkim

**Comment by skodkim** [comment]
Unless I provoke them by placing an unguarded civilian within their reach it seems :cry: 

\Skodkim

**Comment by LoneGazebo** [comment]
Odd. I wonder if they're getting shut out of the tactical AI. @ilteroi, any ideas?

**Comment by ilteroi** [comment]
yeah, i found a little snag ... should be better now

**Comment by ilteroi** [comment]
at least regarding attacks on units. don't know about plundering, never seen any passivity there

**Comment by LoneGazebo** [comment]
Plundering is auto-done based on their proximity to a city.

**Comment by LoneGazebo** [comment]
Question: is it possible that the barb AI's tactical moves and/or unit moves are being processed client-side, instead of 'host-side' in MP? I assume that the same barb outcome would occur every time, right, regardless? 

I'm specifically referring to the 'wandering' element of the tactical AI (i.e. where the barbs choose a random tile to move to en route to a target).

**Comment by ilteroi** [comment]
which random moves are you referring to?

i don't think there's a difference betweens barbarians and the other AI players. but i'm unsure if the AI players are run only on the host or on all machines.

**Comment by LoneGazebo** [comment]
I was thinking of this actually, which affects all players:

`// Make sure base priority is not negative
		if(iPriority >= 0)
		{
			// Finally, add a random die roll to each priority
			iPriority += GC.getGame().getJonRandNum(GC.getAI_TACTICAL_MOVE_PRIORITY_RANDOMNESS(), "Tactical AI Move Priority");

			// Store off this move and priority
			CvTacticalMove move;
			move.m_eMoveType = (TacticalAIMoveTypes)iI;
			move.m_iPriority = iPriority;
			move.m_name = barbarianMoveNames[iI];

			m_MovePriorityList.push_back(move);
		}`

**Comment by LoneGazebo** [comment]
Affects all players, perhaps we should toss that random element? I don't think there should be _any_ random rolls in tactical or operational moves.

**Comment by ilteroi** [comment]
well, removing it shouldn't hurt too much, but on the other hand i don't think it will help. after all, it affects all AI players, not only the barbarians

**Comment by LoneGazebo** [comment]
Does it? It only appears in the barbarian moves stuff.

**Comment by ilteroi** [comment]
you're right, i didn't check and remembered it wrong

**Comment by ilteroi** [comment]
there's even a define for it  .... MOD_CORE_REDUCE_RANDOMNESS

still don't believe it will help though

**Comment by LoneGazebo** [comment]
Maybe not. I'm just scratching my head for answers as to why barbs would be the root of desyncs, and I'm running out of ideas. :/

**Comment by ilteroi** [comment]
my guess: it's an uninitialized variable somewhere

**Comment by ilteroi** [comment]
just ran the vc2015 compiler with all static checks ... but no findings in CvBarbarians.cpp

one unrelated thing is here - is that intended?
		if(NO_BUILDING && GET_PLAYER(m_eAssignedPlayer).getNumCities() < iNum)

**Comment by LoneGazebo** [comment]
no, should be eBuilding == NO_BUILDING I'd imagine.

Uninitialized variables make me sad.

**Comment by ilteroi** [comment]
ok, cppcheck is very interesting.

there's a million unitialized member variables, many of them probably benign because there is an Init() method, but bad style and makes it hard to find the real issues ... i didn't see a red flag.

also stuff like that:
    Condition 'iPressureForAutocracy>=iPressureForFreedom' is always true

**Comment by LoneGazebo** [comment]
What did you use for that? 2015 VS?
