### ISSUE TITLE
[4-9b] Barbarians killed near CS message

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#1591]
With version 4-9b (4-10 hotfix) the message when you kill a barbarian near a CS says you gain 12 influence. You actually get 15.

\Skodkim

**Comment by skodkim** [comment]
The Text key you are looking for is this one:
		<Row Tag="TXT_KEY_NOTIFICATION_MINOR_BARB_KILLED">
			<Text>You have killed a group of Barbarians near {1_CivName:textkey}! They are grateful, and your [ICON_INFLUENCE] Influence with them has increased by 12!</Text>
		</Row>

**Comment by LoneGazebo** [comment]
Cool

**Comment by LoneGazebo** [comment]
Will fix, thanks.
