### ISSUE TITLE
Civilopedia Mausoleum  not in sync with effect

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#1592]
about the "holy site" thing:  

from building text:  
> <Row Tag="TXT_KEY_BUILDING_MAUSOLEUM_STRATEGY">
> 	<Text>Build the Mausoleum to gain [ICON_PEACE] Faith from casualties in war and to improve all Holy Sites. Constructing this National Wonder will also allow you to choose a Reformation Belief. May only be constructed in a Holy City, and only if at least 20% of the global population follows your Religion.</Text>
> </Row>

from religion text:  

> Unlocks Mausoleum National Wonder (+5 [ICON_PEACE] Faith, and gain [ICON_PEACE] Faith when an owned unit is killed in battle; unlocks Reformation Belief)

**Comment by LoneGazebo** [comment]
What's the problem?

**Comment by supermerill** [comment]
If the Mausoleum improve the city Holy site, it should be written in religion_text.sql

**Comment by LoneGazebo** [comment]
All religious national wonders do that. The data is left off to keep the founder text minimal.

**Comment by supermerill** [comment]
oh, ok. I never notice it. Checking the Building_text.xml, The Mausoleum doesn't have a +5F yield!

maybe consider adding "for all holy sites"? 
( "unlocks Reformation Belief" is also redundant)

> Unlocks Mausoleum National Wonder (+5 [ICON_PEACE] Faith **for all holy sites**, and gain [ICON_PEACE] Faith when an owned unit is killed in battle; unlocks Reformation Belief)

**Comment by LoneGazebo** [comment]
Sorry.
