### ISSUE TITLE
imbalanced army composition

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1593]
this is the danish navy:

![image](https://cloud.githubusercontent.com/assets/1358966/14543611/4eef11ea-0295-11e6-80c7-f34d4632e2ca.png)

only galeasses, no melee ships ...

also, in the late game i often see unit carpets where every single plot is occupied by a unit. granted, it's the late game, but at some point the AI should stop building units.

**Comment by LoneGazebo** [comment]
That's odd. On the 4/10 variant? There's a function to check army comp and/or smallest unit type owned by the player, I wonder if it is reporting wrong. What's the cityproduction log look like, weighting wise?

G

**Comment by ilteroi** [comment]
no clue. log is gone

**Comment by ilteroi** [comment]
but yes. latest version

**Comment by LoneGazebo** [comment]
I wonder if there's a quirk in Denmark's flavors, as that's twice he specifically has been mentioned for military goofs.
