### ISSUE TITLE
Event Happiness

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1594]
Is there a method to check happiness being given by an Event/CityEvent? I'd like to mark this in the Top Panel and City View's respective tooltips.

**Comment by LoneGazebo** [comment]
Not exposed to lua, no. I can do that for next time. Right now it is bundled into city happiness.

**Comment by JFDaly** [comment]
Would be great, thanks.

**Comment by JFDaly** [comment]
What's the function for this? Assuming it was added in the last update.

**Comment by LoneGazebo** [comment]
I think player:GetEventHappiness. It is in the toppanel.lua in the CP.

**Comment by JFDaly** [comment]
Hm, thought so. For some reason, the game supposes the method to be non-existant. Will investigate.

**Comment by LoneGazebo** [comment]
Hope I didn't forget to include it in Method...

**Comment by JFDaly** [comment]
It's there in the Top Panel. Someone would've found out if you didn't. I'll try re-downloading the beta.

**Comment by JFDaly** [comment]
Yup, that fixed it. I had the latest beta, but something must've gone screwy.

**Comment by LoneGazebo** [comment]
Sounds good!
