### ISSUE TITLE
Event "Old Man and the Sea" gold requirement scales with era but the given effect doesn't

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#1595]
![8930_20160412124602_1](https://cloud.githubusercontent.com/assets/1131228/14545572/471af816-02b9-11e6-8d9d-330c543515e3.png)
At this stage it's cheaper to invest and buy the Lighthouse normally, while food increments are pretty small.

**Comment by LoneGazebo** [comment]
I'll flip the bool to false. Thanks!
