### ISSUE TITLE
Corporations Overview text (4/9 beta)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#1597]
1.Some of the TXT_KEY_CORP_HELP_RESOURCE_BONUS*** are incorrect.
cf.
(2) Community Balance Patch\Modular Elements\Corporations\Text\en_US\CorpText.xml

<1> **Trader Sid's, Inc.**
Line: 377-378
```
		<Row Tag="TXT_KEY_CORP_HELP_RESOURCE_BONUS_TRADER_SIDS">
			<Text>[ICON_RES_WINE] Wine, [ICON_RES_TRUFFLES] Truffles, [ICON_RES_CITRUS] Citrus provide additional [ICON_FOOD] Food.</Text>
```
should be
```
		<Row Tag="TXT_KEY_CORP_HELP_RESOURCE_BONUS_TRADER_SIDS">
			<Text>[ICON_RES_SPICES] Spices, [ICON_RES_SUGAR] Sugar, [ICON_RES_SALT] Salt, [ICON_RES_NUTMEG] Nutmeg, [ICON_RES_CLOVES] Cloves, [ICON_RES_PEPPER] Pepper, and [ICON_RES_COCOA] Cocoa provide additional [ICON_GOLD] Gold.</Text>
```

------------------------------

<2> **Hexxon Refineries, Inc.**
Line: 487-488
```
		<Row Tag="TXT_KEY_CORP_HELP_RESOURCE_BONUS_HEXXON_REFINERY">
			<Text>[ICON_RES_COAL] Coal, [ICON_RES_OIL] Oil, [ICON_RES_INCENSE] Incense, [ICON_RES_URANIUM] Uranium provide additional [ICON_GOLD] Gold.</Text>
```

Hexxon Refineries HQ provides 3 Coal, Oil, and Uranium.

------------------------------

<3> **Civilized Jewelers, Inc.**
Line: 708-709
```
		<Row Tag="TXT_KEY_CORP_HELP_RESOURCE_BONUS_CIVILIZED_JEWELERS">
			<Text>[ICON_RES_GOLD] Gold, [ICON_RES_SILVER] Silver, [ICON_RES_GEMS] Gems, [ICON_RES_PEARLS] Pearls, [ICON_RES_JEWELRY] Jewelry provide additional [ICON_GOLD] Gold.</Text>
```

Civilized Jewelers HQ doesn't provide resource bonuses.

------------------------------

2.Most of the TXT_KEY_CORP_HELP_RESOURCE_BONUS*** need to be updated when using "**More Luxuries**".

![corporationsoverview](https://cloud.githubusercontent.com/assets/11933188/14559406/669d5dca-0343-11e6-95d9-79cacaae5fd6.png)

**Comment by mwhiter** [comment]
More Luxuries and any mods that modify corporations will have to update those texts itself, I cannot produce logic to handle that itself.

As for incorrect texts, I used what was provided in the Civilopedia as my base, so if those are wrong, then we were cooked from the start.

**Comment by mwhiter** [comment]
As for the trader sids with food -  that's odd, maybe a copy paste? I feel like that was absolutely gold when I first made that.

**Comment by LoneGazebo** [comment]
Did you define any new helper texts for the interface? If so, I'll need to make a variant on the file for more luxuries.

**Comment by 8h42** [comment]
How about inserting some lines to the **CBP Compatibility Files**.

cf.
(6a) Community Balance Patch - Compatibility Files (EUI)\Corporations\Text\CorpText_en_US.sql
(6b) Community Balance Patch - Compatibility Files (No-EUI)\Corporations\Text\CorpText_en_US.sql

sample
```
UPDATE Language_en_US
SET Text = '[ICON_RES_WINE] Wine, [ICON_RES_TRUFFLES] Truffles, [ICON_RES_CITRUS] Citrus, [ICON_RES_OLIVE] Olives, [ICON_RES_COFFEE] Coffee, [ICON_RES_TEA] Tea provide additional [ICON_FOOD] Food.'
WHERE Tag = 'TXT_KEY_CORP_HELP_RESOURCE_BONUS_TWOKAY_FOODS';
```

![sample](https://cloud.githubusercontent.com/assets/11933188/14562820/e3eba5d2-0359-11e6-8ac5-88296d292ca0.png)


Sorry for my bad English.

**Comment by mwhiter** [comment]
Yeo

**Comment by mwhiter** [comment]
Misclick on my phone. 

Yes i separated the helper text for resource office, and trade routes bonuses for each corporation.

**Comment by LoneGazebo** [comment]
Ah, I'll need to make More Luxuries variants, then.

**Comment by mwhiter** [comment]
So I saw the text bugs and fixed them, they should be applied in the latest pull request. I bet there are a lot more errors, so please highlight them!

(however, these are simple text bugs, so I do not need to fix them myself! They should be easy to sort out!)
