### ISSUE TITLE
[v3-14] No EUI tooltips in tech tree

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#160]
With version 3-14 I'm not seing any of the EUI tool tips on buildings, units, ... in the tech tree. Funny part is that it works fine in the city view. Nothing in lua.log - it just says the tech tree loaded fine.

Anyone else seing this?

\Skodkim

**Comment by skodkim** [comment]
Found the culprit: TechButtonInclude.lua is present in several of the mods from the release and it overrides EUI's version of the file. It used to be part of CPP in previous releases too, didn't it? Maybe the wrong version of the file was included?

\Skodkim

**Comment by LoneGazebo** [comment]
I'll fix in next version.
G
