### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1602]
Since barbarians start to appear at -20 happiness instead of the -10, could you please make it that the unhappiness icon switches from orange to red at -20 also?

**Comment by LoneGazebo** [comment]
Doesn't it?

**Comment by Der-Zorn-Gottes** [comment]
No, it's still the vanilla value of -10-

**Comment by LoneGazebo** [comment]
okies, i'll look.
