### ISSUE TITLE
Can't have more than one event pending.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1603]
I fear as the Event System may be reaching its perfection, it seems apparent that you can only have one event per turn and this is problematic if you have multiple LUA mods that may suddenly do its event on the same turn.

**Comment by LoneGazebo** [comment]
Correct, no more than one (Same for city production, unit production, policies, etc.). Can't control that, as that's how the notification system works.

G

**Comment by TechpriestEnginseer** [comment]
So you can't have two events(not notifications, but events) overall.

**Comment by LoneGazebo** [comment]
What do you mean? If multiple cities have events it'll queue them. But not for player events. Works like production button for cities, research button for player stuff.

**Comment by TechpriestEnginseer** [comment]
````
function NativePopup(iPlayer, iUnit, iUnitType, iPlotX, iPlotY)
	local pPlayer = Players[iPlayer]
	if not pPlayer:IsMinorCiv() or pPlayer:IsBarbarian() then
	local pSettledCity = Map.GetPlot(iPlotX, iPlotY):GetPlotCity()
	local iRandomSettleEvent = RandomSettleEvent[math.random(#RandomSettleEvent)]
	pSettledCity:DoCityStartEvent(iRandomSettleEvent)
	end
end
RandomSettleEvent = {GameInfoTypes.CITY_EVENT_NATIVES, GameInfoTypes.CITY_EVENT_ANTIGOV, GameInfoTypes.CITY_EVENT_SACREDRUINS, GameInfoTypes.CITY_EVENT_NEWDISEASE}
````
I've repeated this multiple time. If I settle two cities, only the event will appear for the first city, but the event for the second city will never appear at all.

**Comment by TechpriestEnginseer** [comment]
![image](https://cloud.githubusercontent.com/assets/13937047/14579511/c4c33dac-0361-11e6-9f49-93edddcec97d.png)
![image](https://cloud.githubusercontent.com/assets/13937047/14579512/ce2ba528-0361-11e6-9c37-f215f5e3adf1.png)
Good, it's working intended... if the first settled city has the event popup.
![image](https://cloud.githubusercontent.com/assets/13937047/14579516/df59c8e8-0361-11e6-807a-ea35300e7580.png)
Second city settled. It should be giving me an extra event as well, but...
![image](https://cloud.githubusercontent.com/assets/13937047/14579519/f59ab252-0361-11e6-9565-b681f0364ede.png)
Okay first city event settlement for York is looking good!
![image](https://cloud.githubusercontent.com/assets/13937047/14579523/01286a74-0362-11e6-835c-7a5e6ad42aba.png)
Wait where is the second event?


This doesn't however seem to be a problem if I do the event for York first before settling my city of Nottingham.

**Comment by LoneGazebo** [comment]
Interesting. If you try to add an event to the city manually, via the firetuner, does it stack them?

**Comment by LoneGazebo** [comment]
Using dostartcityevent

**Comment by TechpriestEnginseer** [comment]
Also, is the CityEventChoice's EventChoiceAudio broken all of the sudden? I remembered in 4/9, it would play the custom audio, but in 4/10, it's just going back to the default audio. Haven't seen this with EventChoice's EventChoiceAudio however.

**Comment by LoneGazebo** [comment]
not sure, JFD's the guy to ask on that.

**Comment by JFDaly** [comment]
Wait, 4/10? Is there a new version somewhere that I've missed? All I know is that I have a unique sound effect for all of my custom events so far, and they've never faltered, and this is on 4/9.

**Comment by LoneGazebo** [comment]
4/10 was a hotfix I pushed next morning after 4/9. Fixed building count bug.
