### ISSUE TITLE
Negative Coal Notification

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1604]
Notification for lacking coal says units can't heal, but I believe there's no coal units anymore. And there doesn't seem to be a penalty to buildings, which means no penalty at all. If there is it doesn't say it.

**Comment by LoneGazebo** [comment]
It should be giving you a penalty via maintenance hike. No notification for that? You have to have a coal building for it to appear.

**Comment by pandasnail** [comment]
No mention of notification for that no, just the unit healing. And at least the EUI display of maintenance is the same as normal-5 for coal plants, 4 for Trains and Seaports. Not sure if its somehow baked into the city I guess. (Played as England, so I did have zero factories)

**Comment by LoneGazebo** [comment]
It will affect your overall maintenance, not the maintenance on the building specifically. Can't update that value, as it is hard-coded.

**Comment by pandasnail** [comment]
Ah. The mine collapsed while real close to victory, wasn't exactly paying attention to my gold per turn, so it probably functioned properly then, just without the notification.
