### ISSUE TITLE
Next civpedia runthru

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1605]
Depending on how engrossing the basketball is, either Sunday or Monday, I should have time (and the extra monitor) to do another go thru of a civpedia section. Figured I might as well see if you have a preference. I've been noticing that a lot of tech's Game Infos are wrong, Cannons mentioned by Metallurgy for instance, and a lot of basic units not mentioned. So that's one thought, at least some sections of the techs. Or I could do another yield like I did science awhile back, either to the forum or straight to the wikia. Just right now realized I never updated that for the 4/10. Or I could just work on the wikia in general.

**Comment by LoneGazebo** [comment]
The tech help info isn't used anymore (at least not in any major way). Help on the wiki would be fantastic.

**Comment by pandasnail** [comment]
Okay. The tech Game Infos aren't a major problem, no, but I should still go thru them eventually. They are still what pop ups when a tech is researched after all. But for now, I'll do some more work on the wikia, yeah.

**Comment by pandasnail** [comment]
Civilizations page should be up to date except Venice. Took longer than I expected, hopefully I can look at the other pages later this week.

**Comment by LoneGazebo** [comment]
Awesome!
