### ISSUE TITLE
# of wonders indicator

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1607]
In the mouseover-info for leaders it is shown how many wonders they have, which is nice.
However, it always shows 0, regardless how many wonders the civ actually has.

**Comment by LoneGazebo** [comment]
You on 4/10 CP?

**Comment by Der-Zorn-Gottes** [comment]
4/9. Didn't notice a newer version (Actually I can't even find it now that I'm looking for it).

**Comment by LoneGazebo** [comment]
Just redownload the link for 4/9 and it has the 4/10. I posted the hotfix the next morning after 4/10.
