### ISSUE TITLE
[Minor] Tenet select highlight does not adjust for more than 1 row

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1609]
![image](https://cloud.githubusercontent.com/assets/4925402/14581554/d3aa0650-03bd-11e6-95d5-95ace9d3b605.png)

Believe this requires at most a three-line change to SocialPolicyPopup.lua, the ReligionOverview.lua shows an example of resizing.

Is this something I should waste my time on?

**Comment by LoneGazebo** [comment]
I wouldn't worry about it. I can look at it later.
