### ISSUE TITLE
CTD during war when 

### ISSUE THREAD

**Issue by Cyde042** [LoneGazebo/Community-Patch-DLL#1611]
Up to this point the game was going really well, I was Mongolia and moved my army near one of Spain's cities. I declared war, I start spamming heavy skirmishers and while I switch from 1 unit to another, the game crashes the instant I hover over one of the units or on the city (not sure if it's a coincidence but it happened twice when I hovered on my knight). 

First game in 9th of april version (the 10th ver was uploaded on the same link as the 9th? if so, then I have 10th ver). I went at war in previous versions and I didn't have this issue nor did I add any new mods.

http://www.filedropper.com/cvminidump

**Comment by LoneGazebo** [comment]
Might be an issue with EUI, unfortunately. Majority of bug reports posted lately have broken to disassembly, meaning that it is a LUA (i.e. UI) issue.

G

**Comment by Cyde042** [comment]
I saved each turn and figured out the cause. It isn't the unit but the city. When I hover on the city with the knight, it crashes. The unit vs city hp window doesn't even appear. 

The thing is, I was already at war and captured cities with knight this game.

**Comment by Cyde042** [comment]
I have full version installed. Is it enough to delete EUI or should the compatibility files be deleted also?

And then wouldn't the save simply not load?
