### ISSUE TITLE
EventChoices request

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1612]
Dear G,

May we have FeatureAnywhereRequired in the same vein as ImprovementAnywhereRequired?
I'd like to buff flood plains, for example, without having the AI take that when they have no flood plains.

**Comment by LoneGazebo** [comment]
Yeah, I'll add that.

**Comment by LoneGazebo** [comment]
In the meantime, you could write it as a city event.

**Comment by Hokath** [comment]
Yes I thought about that.
Quick question, does IsUnhappy still return true if IsSuperHappy is returning true?

**Comment by LoneGazebo** [comment]
Yeah, they stack. – IsUnhappy counts for less than 0, SuperUnhappy for less than -10. IsUnhappy includes SuperUnhappy, but not other way around.

**Comment by Hokath** [comment]
ok good :), thanks

**Comment by TechpriestEnginseer** [comment]
Is it possible to include in the Event and CityEvent table of RequiresWater and NoWater? Basically where the event needs ocean to activate, and the event does not activate if there is nearby oceans.

**Comment by LoneGazebo** [comment]
IsCoastal applies to city events. There's no way to do 'nowater/water' for player level events, as it doesn't check city-level procs like that. It'd be too intensive.

**Comment by TechpriestEnginseer** [comment]
Guess I'll use LUA to check if the city is coastal or not to give them the penalty. Cheer.

**Comment by LoneGazebo** [comment]
Wait, are you asking for an eventchoice check, or an event check?

**Comment by TechpriestEnginseer** [comment]
EventChoice.

**Comment by LoneGazebo** [comment]
Adding to Player-level events in next CP:

EventChoice

		<Column name="CoastalOnly" type="boolean" default="false"/>
	

EventChoice/Event

		<Column name="MinimumNumCoastalCities" type="integer" default="0"/>


Event/EventChoice

	<Table name="Event_MinimumFeatureRequired">
		<Column name="EventChoiceType" type="text" reference="EventChoices(Type)"/>
		<Column name="FeatureType" type="text" reference="Features(Type)"/>
		<Column name="Quantity" type="integer"/>
	</Table>
