### ISSUE TITLE
Clicking on the antiquity site notification puts up the Corporation & Monopoly Overview

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1613]
It's not a major bug, but when you discover 18 antiquity site on a large map, it gets annoying to close the corporation and monopoly overview everytime.

This is with the full CPP package, in case it matters.

**Comment by LoneGazebo** [comment]
Huh.

**Comment by LoneGazebo** [comment]
The current official version, or the beta version?

**Comment by biship** [comment]
Happens for me on the 4/10 build

**Comment by mwhiter** [comment]
are they shared buttonpopup ids?

**Comment by LoneGazebo** [comment]
I'm not sure, honestly. I need to look at it, but I'm indisposed at the moment.

**Comment by LoneGazebo** [comment]
Fixed.
