### ISSUE TITLE
stacked ai units

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1616]
i'm seeing a lot of this lately

cargo ships:
![image](https://cloud.githubusercontent.com/assets/1358966/14615085/5c9d92c8-05a4-11e6-902c-92338087ad49.png)

archeologists:
![image](https://cloud.githubusercontent.com/assets/1358966/14615168/af348276-05a4-11e6-9392-3fe86d777234.png)

also missionaries (not a good picture)
![image](https://cloud.githubusercontent.com/assets/1358966/14615210/de20b83e-05a4-11e6-83e7-3bc4d7de8d78.png)

and in rare instances, workers.

any recent changes which could cause this?

**Comment by LoneGazebo** [comment]
stacks on stacks on stacks
1: Trade units may be blocked from trading out of that city, maybe?
2: Probably no good targets, so they go to nearest safe city? AI should delete them soon enough if there are in fact no targets.
3: If a single city is the best target, and the AI has multiple missionaries, they'll preach it to death.

**Comment by LoneGazebo** [comment]
Quick note: running dll inspector shows that, during a game, the DLL is calling this function a lot:

![untitled](https://cloud.githubusercontent.com/assets/7849458/14616352/148fc54a-0578-11e6-8621-eb0b4f2cf41d.png)

**Comment by LoneGazebo** [comment]
Seems excessive.

**Comment by ilteroi** [comment]
1. at least internal traderoutes should have been possible
2. maybe. but why build 5 if there are no available targets?
3. guess for missionaries this bunching is ok. at least in the lategame

**Comment by ilteroi** [comment]
@performance: funny that you mention it. is fixed

**Comment by LoneGazebo** [comment]
1. Not sure- perhaps all moved there at same time?
2. May have built five and gone to war.

**Comment by LoneGazebo** [comment]
re: performance, yay! Best problems are solved before the problem is found :)

**Comment by ilteroi** [comment]
1. in any case it's probably not a smart move to re-base all your trade units to the same city

**Comment by LoneGazebo** [comment]
Probably true. I'll try to remember to look at it soon enough.

What's the performance fix btw?

**Comment by ilteroi** [comment]
CvUnit::baseMoves() was being called from the pathfinder like a million times because the intended caching was bypassed. and for embarked movement baseMoves() checks the policies for bonus moves.

also found a big issue in missionary targeting, a lot of unnecessary pathfinder calls, major lategame slowdown.

pushing now

**Comment by LoneGazebo** [comment]
Cool. Make sure that missionaries still go to the pathfinder before selecting a city, as otherwise they try (over and over again) to path to a bad city and never go anywhere.

**Comment by LoneGazebo** [comment]
Chatted up your AI improvements with Delnar yesterday and today, btw: https://www.reddit.com/r/civ/comments/4f636d/intelligent_ai/d27roeu?context=10000

**Comment by ilteroi** [comment]
re: delnar - he has a point - but unfortunately it's hard to implement - so it's a mostly academic discussion.

**Comment by LoneGazebo** [comment]
Indeed. I didn't want to point that out, but his arguments stemmed from an unrealistic expectation of a game.

**Comment by ilteroi** [comment]
well - that's actually worth a discussion. are there possible rule changes which would make the game more AI friendly?

**Comment by LoneGazebo** [comment]
1UPT is the biggest limiter, of course, but that can't be changed (and I wouldn't want to). When I look at the military AI, specifically the operational model, I see it functioning in a manner wholly inconsistent with how humans create armies. Humans rarely 'clump' their units into hex blocks and send them forth – they usually form lines to envelop and surround the enemy. I think, if we were to train the AI to do any one military thing better than they do now, it would be to have the AI organize proper sentries along borders with civs (i.e. every hex filled with a melee military unit), and then – if war is declared – have these lines of troops moving forward with ranged support behind them. The AI gets surrounded easily, and that hurts their ZoC manipulation and their ranged power.

I almost wonder if we should scrap all non-civilian AI operations (i.e. keep settler operations, etc.) and instead use the tactical AI map to create focus zones for the AI to move its troops towards. The tactical AI is very flexible and competent, whereas the operational AI is very static. Dropping operations in favor of 'zones of focus.'

We could have a few different zone focus types:

Line of offense: zone that is 2 hexes wide, and encompasses all domain-appropriate hexes either neutral or owned by an enemy. (limit to 8 hexes long probably)
Line of defense: same, but neutral or owned by player.
Defense target: 4x4 hex block of defense of neutral/owned hexes
Offense target: same, but enemy/neutral.
Strike target: single high value target (city, citadel, etc.) owned by enemy.
Turtle target: single high value target owned by player.

Assigning these zones at the start of war, or the change of ownership of territory, would make the AI think in a much more human fashion. We could get rid of the weird target calling system of the Military AI (but keep the scoring algorithm for setting strike targets and offense targets), and most of the clunky operational AI stuff. The Army AI would be unused too, except for single-hex operations.

**Comment by mwhiter** [comment]
Out of curiosity, because doing an AI change of this scale is extremely large and probably very difficult: is it worth it? Having a competitive AI is one thing, but do you, in your opinion, feel like it is a good use of effort to attempt to fix it? Is there going to be an immediate, noticeable benefit to a human player, who is most likely going to be smarter than the AI regardless of that effort?

It might be worth discussing that before proceeding here.

**Comment by LoneGazebo** [comment]
I'm not sure, and that's exactly what I was about to ask myself. :)

The AI is perfectly competent right now. It does a fine job in most situations. It's those glaring 'oops' moments that make you want to do these kinds of big changes.

That said, I'd say that roughly 50% of the work is already done. Creating the zone types, and assigning units via a value, is the only wholly unique element above. Everything else borrows off existing functionality.

**Comment by ilteroi** [comment]
i'm in it for the challenge :)

in general i'm not opposed to armies - they are simply a way to get a bunch of units from A to B. 

the comment about the AI being trapped easily is true - but battle lines are difficult to do with terrain and all. anyway, i've already started implementing some tactical AI ideas to improve positioning. doesn't work yet, but we'll see how it works out.

**Comment by LoneGazebo** [comment]
The key, I guess, is figuring out a way to get armies to adapt to the terrain and widen themselves a bit more...organically (buzzwords, ahoy!). Right now the stringency of CoM calls and movement logic makes remaining 'cohesive' more important than remaining tactically dominant. That's why I lean towards the zone model, as defining zones of action allows the tactical AI to be more freeform in its tile selection (CoM won't matter for zones as much, and CoM is static).

**Comment by LoneGazebo** [comment]
@ilteroi , the pathfinder in your latest build is being a bit odd. Should be easy to replicate. Grab a unit and try to move it. You'll notice that some moves that should only cost 1 cost two, and some moves that are more than one hex away break after moving a hex, thus causing the unit to only move one hex  at a time towards a target.

**Comment by LoneGazebo** [comment]
If you need a save, I can push my latest along with the save.

**Comment by LoneGazebo** [comment]
It is very easy to replicate with boats.

**Comment by LoneGazebo** [comment]
Also, seems the AI is embarking military units into the water out of danger again...sometimes, not always, but I've seen it a few times now. Mainly ranged units, but a few tercio did it as well.

**Comment by ilteroi** [comment]
don't know about the embarking but fixed the spurious stops in the pathfinding - seems the second layer was working too well :)

also migrated the pathfinder to an stl vector heap instead of a hand-written list. cleaner code and should improve performance.

**Comment by LoneGazebo** [comment]
I'll keep an eye on embarking, try and get some more specifics on it. It was odd – Mongolia was attacking a Korean coastal city, Korea had a nice defense force, and then – all of a sudden – Korea's 2 Tercio and 2 Horse Archer dove into the ocean.

stl vector heaps sound fun.

**Comment by LoneGazebo** [comment]
Regarding that cargo ship stack – did you step in to see if the civ was embargoed? Also, were there any valid TRs? I can't replicate the odd behavior, and that's definitely odd behavior.

**Comment by ilteroi** [comment]
re: cargo ships - i have a savegame, will check

**Comment by LoneGazebo** [comment]
Cool, thanks. Also see if the AI can move them somewhere else (i.e. if the transfer port function is functioning).

**Comment by LoneGazebo** [comment]
Also, let me know when you've pushed the pathfinder fix, I'd like to throw out a beta tonight if possible.

**Comment by ilteroi** [comment]
it seems PrioritizeTradeRoutes() returns only land routes, therefore the cargo ships are stuck. strange

**Comment by LoneGazebo** [comment]
Is that a pathfinder issue, or an AI logic issue in that function?

**Comment by ilteroi** [comment]
there are 700 possible trade routes (huge map) and only 9 of them are valid.

seems to be a logic issue

**Comment by LoneGazebo** [comment]
Hmm. Is it an issue with danger, maybe? Is the danger value causing routes to return a negative value? I know we had that problem once before.

**Comment by ilteroi** [comment]
haven't checked in detail yet, but it seems the function is just very restrictive - food only to the smallest city, production only to a wonder building city etc. maybe that should be loosened up a bit.

**Comment by LoneGazebo** [comment]
The whole function is very obtuse. I might write a secondary function that – if that one fails – sends the TR to the highest gold delta or closest internal city, just to get them moving.

**Comment by ilteroi** [comment]
pushed!

**Comment by LoneGazebo** [comment]
what's the verdict?

**Comment by ilteroi** [comment]
on what?

didn't do anything about the traderoutes in any case

**Comment by LoneGazebo** [comment]
Oh. I saw your enemy city point on TR cache lists, thought perhaps that caused a bug. I'll work on the TR stuff at a later date.

G

**Comment by ilteroi** [comment]
na that was just a simplification. because the trade route cache is used for a lot of things now it is better for it to contain all cities at all times

**Comment by ilteroi** [comment]
d'oh. emergency push. forgot one little thing :)

**Comment by LoneGazebo** [comment]
cool
