### ISSUE TITLE
Request GameEvents.TradeRouteCompleted

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1618]
I'd like to request for a GameEvent where if a trade route is completed, you can do some Lua coding with it. (Ex. I want an event to have a low chance of appearing after a trade route is completed and such)

Borrowing the GameEvent from PlayerCanCreateTradeRoute, I think the identifier of (iFromPlayer, iFromCity, iToPlayer, iToCity, iDomain, iConnectionType) would be needed.

**Comment by LoneGazebo** [comment]
GAMEEVENTINVOKE_HOOK(GAMEEVENT_PlayerTradeRouteCompleted, pOriginCity->getOwner(), pOriginCity->GetID(), pDestCity->getOwner(), pDestCity->GetID(), eDomain, pTradeConnection->m_eConnectionType);

**Comment by TechpriestEnginseer** [comment]
I don't see this documented in the CustomModOptions unless the EVENTS defines doesn't need to be enabled for this then?

**Comment by LoneGazebo** [comment]
I added it, but forgot to document.
