### ISSUE TITLE
Cities with Courthouse showing occupied unhappiness

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#162]
This one looks like a tooltip/lua issue with EUI, nothing wrong with game mechanics. This album here is pretty self-explanatory: http://imgur.com/a/pNj4C#0

Certain tooltips show unhappiness from occupation (incorrect, courthouse is built) but the game is not considering any cities to be occupied.

**Comment by LoneGazebo** [comment]
Already fixed for 3-19 version. Thanks for catching it, though!
G

**Comment by joosegoose** [comment]
I'm not positive if you see this since the issue is closed, but I'm seeing this bug in the 3-19 version. Just wanted to make sure it's in fact supposed to be fixed.

![2015-03-24_00001](https://cloud.githubusercontent.com/assets/11132095/6798710/e75b767e-d1dd-11e4-935b-83234af5e89b.jpg)

**Comment by LoneGazebo** [comment]
Hmm, I fixed this  (or I thought I did) in the 3-19 version. Using EUI, or no EUI version of the compatibility files?

**Comment by joosegoose** [comment]
EUI. I've spent a fair bit of time with this version and am pretty positive everything is installed correctly, too.

**Comment by LoneGazebo** [comment]
It's a bug - I missed a check. Will fix. Thanks!
