### ISSUE TITLE
barbarian city population explosion

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1620]
this was reported a while ago, we couldn't reproduce it, but this reminded me:

kyzyl was just conquered by denmark from the barbarians. it's the largest city in the world!

![image](https://cloud.githubusercontent.com/assets/1358966/14660021/49ab8ae6-06a1-11e6-853a-6217a33f41d5.png)

also, there are a lot of (major civ) cities conquered by barbarians (e.g. novgorod)

**Comment by LoneGazebo** [comment]
Yeah, I noticed the barb stuff – barbs seem to be able to capture cities since you fixed that barbarian tactical AI thing.

**Comment by LoneGazebo** [comment]
May want to reverse that in the tactical AI. Also, in the current tactical AI (as of your latest push) the AI is not capturing cities. They'll surround them with melee units and get them to zero, but they will not capture. Seems that _steamroll and/or _surgical_strike are not allowing for city capture for the AI.

**Comment by LoneGazebo** [comment]
Well, they'll occasionally capture the cities of other major civs, but not minor or barbarian cities for some reason. Really odd. Images below:

![20160420001608_1](https://cloud.githubusercontent.com/assets/7849458/14663285/38a79f1e-068d-11e6-9e7f-d238e180e5b1.jpg)
![20160420001543_1](https://cloud.githubusercontent.com/assets/7849458/14663286/38a8fd64-068d-11e6-89a0-27647a44deaa.jpg)

**Comment by LoneGazebo** [comment]
Honestly there's a lot of odd combat behavior going on - melee units and ranged units not firing at each other, etc. Seems like something is amiss in the tactical AI. :(

**Comment by Der-Zorn-Gottes** [comment]
Not fully on topic, but kind of: I noticed that garrisons in cities often will neither heal nor act. They gat shot down each turn. Then, once their hit points are really low, they start healing each turn. 
I don't even understand how they can avoid to be healed in the first place, since they didn't do anything, but that's what happens.

**Comment by ilteroi** [comment]
really? shouldn't be the case after my last commit. but i'll check

**Comment by ilteroi** [comment]
ok, found a bad bad bug. can't break eggs without making omelettes, right?

also, barbarian cities seems to have range 3, is that intended?

**Comment by LoneGazebo** [comment]
Barb cities should have range 2.

**Comment by ilteroi** [comment]
current game, large map, seven barbarian cities

![image](https://cloud.githubusercontent.com/assets/1358966/14691297/c38e8d9a-0750-11e6-8807-f7a5d8e82c75.png)

![image](https://cloud.githubusercontent.com/assets/1358966/14691306/cc5f718c-0750-11e6-8c88-538efd7ff678.png)

500 AD and they are again the largest cities in the world

**Comment by ilteroi** [comment]
yerevan is even growing while starving ???

![image](https://cloud.githubusercontent.com/assets/1358966/14691343/012b71fe-0751-11e6-92da-8f3e955b5909.png)

**Comment by ilteroi** [comment]
it seems it grows every time a unit is spawned?

![image](https://cloud.githubusercontent.com/assets/1358966/14691363/1fa4d83c-0751-11e6-9c11-8710f98e0848.png)

**Comment by LoneGazebo** [comment]
There's an element of the cvcity function that lets barb cities grow every time they spawn a unit (using the city unit spawn timer from cvbarbarians). Is it possible that the spawn timer was messed up?

**Comment by ilteroi** [comment]
so they don't grow normally?

maybe linking pop growth and unit spawn is not such a good idea.

at the very least they shouldn't grow while starving

**Comment by LoneGazebo** [comment]
I don't think they grow normally, at least they didn't used to. If they are now (for some reason) I can remove that code.

By the way, did you revert or alter the code that allowed barbarians to capture cities? I'm seeing a lot of non-minor cities getting captured by barbs. :)

**Comment by LoneGazebo** [comment]
The grow-on-spawn thing is an old CSD element.

**Comment by ilteroi** [comment]
afaik, there is no distinction between between major and minor targets?

so no, i didn't do anything. would want to introduce one either. real problem is, why is the AI unable to protect its cities?

**Comment by ilteroi** [comment]
and yes, i've also seen this a few times lately, but never "live", always after the fact.

**Comment by LoneGazebo** [comment]
I don't know. I know barbs weren't allowed to capture cities with melee units before, though. At least it wouldn't do so anyways.

**Comment by LoneGazebo** [comment]
Is it possible that barbs are pathing through cities and, by stepping on a city, capturing it?

**Comment by LoneGazebo** [comment]
I thought it might be an event issue, but I see no evidence of that.

**Comment by ilteroi** [comment]
i'm assuming they were just too stupid to capture :)

**Comment by LoneGazebo** [comment]
here's the function, btw:

void CvCity::DoBarbIncursion()

delete:
```

//Grow and strengthen, my precious!
			changePopulation(1);
			setFood((growthThreshold() - 10));
```

**Comment by LoneGazebo** [comment]
I have noticed that the AI is doing a shite job of garrisoning units lately...perhaps that's partially to blame?

**Comment by ilteroi** [comment]
hmm. i did a change recently to prevent them from re-garrisoning doomed cities. maybe that's not working properly

**Comment by ilteroi** [comment]
but i don't think that would explain the vulnerability. i mean, how many barbarian units would be attacking?

**Comment by LoneGazebo** [comment]
I'm not sure. I'm still curious to see if there's some ooky-spooky pathfinding or unit placement going on that's dropping barbs into cities.

**Comment by ilteroi** [comment]
also, AI is curiously unable to take capture the barbarian city states. been watching 800 year sieges.

**Comment by LoneGazebo** [comment]
Yeah, that's what I was talking about earlier – they just hang out around it and bombard them forever.

**Comment by ilteroi** [comment]
just found a bug in barb camp spawning -- instead of invisible plots they would go to visible plots only.

maybe that explains the recent change, but still a weak AI defense performance

**Comment by LoneGazebo** [comment]
That might be it – if a barb was a near a city, and a camp was spawning in visible only, the only viable spot might be a city.

**Comment by ilteroi** [comment]
there is an explicit check to prevent spawning on cities

**Comment by ilteroi** [comment]
also, i'm seeing a crash every time after i load a game and then try to end the turn.

invalid pPlot pointer coming from LUA side. EUI is a capricious beast

**Comment by ilteroi** [comment]
found a good test for the RNG btw - the hunnic city names are RNG dependent. they change after save / load. something is still not quite right

**Comment by LoneGazebo** [comment]
Interesting re: rng. Sounds like the random seed isn't being saved against the save data properly.

**Comment by LoneGazebo** [comment]
EUI is a capricious beast, yes.

**Comment by ilteroi** [comment]
found another bug ... pushing now

**Comment by LoneGazebo** [comment]
what's the rng word?

**Comment by ilteroi** [comment]
nothing yet on RNG

but i found some fallout from the removal of the ignore units pathfinder i need to fix.

will push later

**Comment by LoneGazebo** [comment]
Coolio, no worries. I poured over the random.cpp etc. last night and the only evidence I can muster is that, for some reason, is it possible that the 'new random seed on load' option is enabled on your end, and/or is being forcibly enabled in the DLL?

**Comment by ilteroi** [comment]
pushed. hope that finally does the trick.

re: RNG - couldn't reproduce it, guess i must have made a different move before

**Comment by LoneGazebo** [comment]
Interesting. Since the seed does 'evolve' as the RNG is called, perhaps another RNG call happened in-between actions. Who knows!

**Comment by ilteroi** [comment]
guess that's what happened.

anyway, the original issue is fixed. closing this. excited for the new release!

**Comment by LoneGazebo** [comment]
Coolio!
