### ISSUE TITLE
Generic +% Combat Strength bonus isn't shown in the combat preview against cities

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#1623]
Yet it works.
https://i.imgur.com/dmMdxVg.jpg

**Comment by LoneGazebo** [comment]
Danke

**Comment by Radost** [comment]
Now that I think about it even more, shouldn't the unit have 9 CS? 6 base +30% from Shock III and +20% from Blockade?

**Comment by LoneGazebo** [comment]
Blockade may be a red herring – supposed to only apply to naval units!
