### ISSUE TITLE
Unable to load a saved game

### ISSUE THREAD

**Issue by veljaaa** [LoneGazebo/Community-Patch-DLL#1624]
I have a game that is in turn 480+ already (on Epic), but I can not load the save file anymore.

A couple of major events that happened between this save and the last save from this game that I was able to load:
- I entered Modern era
- I adopted an Ideology
- I used Great General to steal some land on a Coal resource tile
- I created a Town using a Great Merchant

I've attached the save files (the last one that I'm able to load and the one I'm not), the Log folder and a Civilization mod that I made that is required for the game to load.
[Car Lazar (v 1).zip](https://github.com/LoneGaze
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/228745/Logs.zip)
bo/Community-Patch-DLL/files/228718/Car.Lazar.v.1.zip)
[Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/228741/Saves.zip)

**Comment by veljaaa** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/228748/Logs.zip)
Logs here

**Comment by LoneGazebo** [comment]
I'll take a look, thanks.

**Comment by veljaaa** [comment]
Hi Gazebo, it turns out it was due to Thals FlagPromotions, I disabled that mod, and everything works fine now.

It happened in two other games too, so you might want to consider marking that mod as incompatible. That said, it's one of the mods that doesn't affect savegames, so you could always just disable it if you get CTDs and load the game again.
