### ISSUE TITLE
Promotion bugs

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1625]
Bugs I noticed when I looked at promotion trees using Howard's Promotion Tree UI mod.
Logistics requires range promotion for ranged units. There is no blitz in shock branch. Logistics should not be available to chu-ko-nu since it already has extra attack. Logistics or blitz is not available to naval melee units and subs. PROMOTION_HOVER_UNIT has wrong atlas icon ( native tongue unique icon).

**Comment by LoneGazebo** [comment]
Those are all balance choices, actually. If you'd like to talk about them in the forums, there's a thread on promotions that's pretty busy right now.

**Comment by LoneGazebo** [comment]
The icon isn't, but it is the icon I wanted for it.

**Comment by TechpriestEnginseer** [comment]
I think this is a bug. Logistics should not be available to chu-ko-nu since it already has extra attack.

**Comment by LoneGazebo** [comment]
It can get up to three using that, though, I believe.

**Comment by TechpriestEnginseer** [comment]
![image](https://cloud.githubusercontent.com/assets/13937047/14733196/170a86a2-0816-11e6-9b2d-748426304579.png)

**Comment by LoneGazebo** [comment]
Ah, yeah. Hmm...may need to change what promotion the CKN gets.

**Comment by qqqbbb** [comment]
PROMOTION_INTERCEPTION_I,PROMOTION_INTERCEPTION_II,PROMOTION_INTERCEPTION_III,PROMOTION_INTERCEPTION_IV have no description. It's not clear what they do.

**Comment by qqqbbb** [comment]
All of them but PROMOTION_INTERCEPTION_I are used in vanilla game. CBP uses only one of them.

**Comment by LoneGazebo** [comment]
Are they referenced elsewhere in the promotions file? I think they might be a bonus against air units, but I'm not 100% sure.

**Comment by qqqbbb** [comment]
What's promotions file? They use InterceptChanceChange column.

**Comment by qqqbbb** [comment]
UNIT_KOREAN_HWACHA also has extra attack in CBP.

**Comment by qqqbbb** [comment]
Maybe rename PROMOTION_NAVAL_MISFIRE? 'Difficult target' sounds like the unit that has it is a difficult target.

**Comment by qqqbbb** [comment]
UNIT_GUERILLA has free promotion PROMOTION_SNEAK_ATTACK. This promotion is unique to kris swordsman and should be replaced with PROMOTION_FLANK_ATTACK_BONUS which has the same flank bonus.

**Comment by qqqbbb** [comment]
PROMOTION_FASTER_HEAL description should be updated for CBP. It makes units heal 15 more HP not 10.

**Comment by qqqbbb** [comment]
What does River column in UnitPromotions it do?

**Comment by qqqbbb** [comment]
Amphibious promotion description says "grants a movement bonus when moving across rivers." But it does not do that.

**Comment by ilteroi** [comment]
btw. is it intended that a zeppelin gets double moves in forest etc promotions?

**Comment by qqqbbb** [comment]
They don't have double movement in forest. They also don't have PROMOTION_NO_DEFENSIVE_BONUSES promotion which they should.
Zeppelins and helicopters have 2 promotions called 'hovering unit'. Why not combine them?

**Comment by qqqbbb** [comment]
UNIT_ASSYRIAN_SIEGE_TOWER and UNIT_HUN_BATTERING_RAM are melee units and can get promotions that don't make sense for them: amphibious, formation, medic, woodsman.

**Comment by LoneGazebo** [comment]
siege tower is a civilian unit, can't get promotions. Battering ram upgrades into melee, so it is fine.

**Comment by qqqbbb** [comment]
In vanilla game they upgrade to trebuchet.

**Comment by qqqbbb** [comment]
GLOBAL_PROMOTION_CLASSES can be used to fix them.

**Comment by qqqbbb** [comment]
Musketeer has lightning warfare promotion. This promotion's icon has a tank on it.

**Comment by qqqbbb** [comment]
PROMOTION_WITHDRAW_BEFORE_MELEE has ExtraWithdrawal value of 80. It's too high and makes the game annoying when you try to kill a unit but it retreats every turn.

**Comment by TechpriestEnginseer** [comment]
I think that last portion deserves a balance thread before editing its ExtraWithdrawal value.

**Comment by LoneGazebo** [comment]
Indeed. Also some things, like the lightning warfare thing, are fine.
