### ISSUE TITLE
Bonus Yields not scaling with era

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1626]
The bonus yields for council and organisation don't scale with era.
Also, it was reported in the forums that the German UA doesn't scale with era either.

**Comment by LoneGazebo** [comment]
Council is not supposed to scale.

Organization?

**Comment by Der-Zorn-Gottes** [comment]
It doesn't? I was under the impression all instant yields should scale.

Organization as in the progress policy.

**Comment by Edaka** [comment]
Checked all that was mentioned -all scales, at least in the latest beta.
