### ISSUE TITLE
"Font texture" error

### ISSUE THREAD

**Issue by Faerlin** [LoneGazebo/Community-Patch-DLL#1627]
I'm getting this problem after a few hours of game.
Sometimes my game CTD, sometimes it doesn't. The texture glitches are always there, though.

![20160421213208_1](https://cloud.githubusercontent.com/assets/18605250/14728309/c3f66456-0809-11e6-976c-677e1a033533.jpg)
![20160421213300_1](https://cloud.githubusercontent.com/assets/18605250/14728307/c3f5e634-0809-11e6-9071-84f9a006f2b4.jpg)
![20160421213845_1](https://cloud.githubusercontent.com/assets/18605250/14728310/c3f67b58-0809-11e6-99aa-04606abb86f5.jpg)
![error](https://cloud.githubusercontent.com/assets/18605250/14728308/c3f6239c-0809-11e6-97b4-06dec3b2710c.png)

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict. Make sure your copy of civ is up to date and that all other mods are compatible.

**Comment by Faerlin** [comment]
My CIV is updated. 
I'll check the other mods, thanks

**Comment by Faerlin** [comment]
Now I get this error
![image](https://cloud.githubusercontent.com/assets/18605250/14729762/12233e44-0817-11e6-93ba-7e351921db56.png)

**Comment by LoneGazebo** [comment]
That's innocuous for now.

**Comment by Faerlin** [comment]
You're right.
I'll be playing to see if the texture errors will appear again. Despite these error messages, I can play happy.
Thanks again for your help

**Comment by LoneGazebo** [comment]
Yep!

**Comment by skodkim** [comment]
Actually I've been seeing this too. I suspect that it's some kind of incompatibility with other mods, i.e.I know IGE shows up with some problems when I open it.

\Skodkim
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/231153/Logs.zip)
