### ISSUE TITLE
city hitpoints

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1629]
right from the start, even in ancient era, cities have 500 base hitpoints.

don't know if that was changed recently, but it seems to me to be a bit much.

maybe start with 200 or so and add 100 per era?

**Comment by LoneGazebo** [comment]
200 a little low. Probably 300 sounds about right.

**Comment by biship** [comment]
I am seeing this with the 4/23 beta. Ancient era city's with huge HP. 3 turns, 4 attacks and the green bar has barely moved. (I don't know how to see the actual HP).

**Comment by LoneGazebo** [comment]
Dropping it to 300.
