### ISSUE TITLE
Possible bug with Defensive pact

### ISSUE THREAD

**Issue by veljaaa** [LoneGazebo/Community-Patch-DLL#1630]
I was playing as the Shoshone with 12 other civs, two of them being Venice and Poland. I resurrected Venice in a shitty city and wanted to abuse them for Research agreements, so I made friends with them and we signed a Defensive pact to deter the other AIs from conquering them. I also conquered a lot of Polish cities so I was enemies with Casimir and I kept a lot of units on his borders, just to be safe.

Then Casimir asked me if I wanted to declare war on him, and I told him that my units were just passing through, as I really had no intention of attacking him. A couple of turns later, Casimir declared war on Venice, which means he was also declaring war on me. However the game treats this as me declaring war on Poland, so I got the diplomatic penalty for breaking my word even though Casimir was the one that really started the war. Is this a bug, or is it supposed to be like this?

**Comment by LoneGazebo** [comment]
That's normal, yes – because in a DP, you do attack them (as retaliation).
