### ISSUE TITLE
Pillaged farm from event remove all food yields

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#1631]
An event pillaged two farm on wheat: the tiels are reduced to 1 hammer.
![20160422162144_1](https://cloud.githubusercontent.com/assets/6536403/14744474/3ed543b6-08a7-11e6-9dd4-7b0b05bb85b6.jpg)
After repairing the farm: my 2 food are forever gone...
![20160422162427_1](https://cloud.githubusercontent.com/assets/6536403/14744467/34cc709c-08a7-11e6-97db-e5bf24d37b33.jpg)
I tried to remove & replace the farm, but i didn't work.

note: it occur also on bare tiles:
![20160421202948_1](https://cloud.githubusercontent.com/assets/6536403/14744554/8f2472ec-08a7-11e6-943d-a515fffa5c3e.jpg)

using only full ccp 1/10 beta via .exe

**Comment by LoneGazebo** [comment]
You sure it isn't the drought event that also hurts farm output by -2? That event has a duration.

G

**Comment by supermerill** [comment]
It seems so. Silly me.
