### ISSUE TITLE
EventChoice request

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1632]
Dear Santa,

Can we have EventFreeTechs in the same way as EventFreePolicies?

**Comment by LoneGazebo** [comment]
That's in the works, yeah.

**Comment by Hokath** [comment]
This request here.

Elaborate: A popup in the same way as Oxford University gives a Free Tech popup. If that is possible.
No rush.

**Comment by LoneGazebo** [comment]
Gotcha, definitely conflated that with prior request for eventtech

**Comment by LoneGazebo** [comment]
done.
