### ISSUE TITLE
Able to trade Liberation even though I can't liberate my vassals yet.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1633]
So, I'm able to get some good gpt off my vassal's friends if I vassalized him extremely early.

**Comment by mwhiter** [comment]
Hi TechpriestEnginseer.

Looks like IsPossibleToTradeItem() is missing a call to CvTeam::canEndAllVassal(), causing this issue. Thanks for the heads up!

**Comment by mwhiter** [comment]
So I tested in-game with my fix. I made a civ my vassal and then tried to trade him away. It won't work. You can only cancel all vassals after all of them meet the criteria for cancelling.. I'll push this to master.

**Comment by LoneGazebo** [comment]
Danke, will add to master.
