### ISSUE TITLE
Aeroplanes, they be sweepin'

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1634]
@ilteroi,

http://forums.civfanatics.com/showpost.php?p=14244911&postcount=21

Airplanes getting lots of sweeps? Maybe the sweep should kill movement afterwards or have a 'alreadyswept' bool check to prevent?

G

**Comment by ilteroi** [comment]
well, i can change it, but this is most definitely not a bug:

		// Spend a move for this attack
		kAttacker.changeMoves(-GC.getMOVE_DENOMINATOR());

**Comment by LoneGazebo** [comment]
Huh. Well. What do you think? Feels right that one turn = one sweep, IMO.

**Comment by ilteroi** [comment]
ok, let's do it

**Comment by ilteroi** [comment]
on the other hand, it might be nice to make it dependant on a promotion, just like for all other units (canMoveAfterAttacking)

opinion?

**Comment by LoneGazebo** [comment]
Makes sense. That'd give us another air promotion too, which we need.

**Comment by LoneGazebo** [comment]
Also, quick question – would it be possible to change the ranged combat or combat strength of a unit based on whether or not they've already attacked that turn? I'm thinking that, to balance to power of logistics (2x attack) the second attack should be at half strength.

**Comment by ilteroi** [comment]
should be one line

**Comment by ilteroi** [comment]
re: air units, there is already a piece of code there

		// Can't move or attack again
		if(!kAttacker.canMoveAfterAttacking() && kAttacker.isOutOfAttacks())
		{
			kAttacker.finishMoves();
		}

so it seems the problem is that fighters have multiple attacks by default?

**Comment by LoneGazebo** [comment]
ah, that makes sense.

**Comment by ilteroi** [comment]
pushed this and the half-strength change for additional ranged attacks

**Comment by LoneGazebo** [comment]
Coolio
