### ISSUE TITLE
archer can pillage but spearman cannot?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1636]
![image](https://cloud.githubusercontent.com/assets/1358966/14763074/76da071c-098b-11e6-8b20-9d99e9058028.png)

![image](https://cloud.githubusercontent.com/assets/1358966/14763075/812df278-098b-11e6-912a-1230ff3a9f45.png)

what's the deal?

**Comment by LoneGazebo** [comment]
That's odd. I did add a domain check for pillaging in the latest, but that was just to keep ships from pillaging forts on land.

**Comment by LoneGazebo** [comment]
Any update on this @ilteroi ?
