### ISSUE TITLE
crash after reload (was: AI military targeting)

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1637]
guess which city this army is trying to sneak up on? hint: it's akron!

![image](https://cloud.githubusercontent.com/assets/1358966/14763921/c5d2351e-09a5-11e6-99be-70f6e5be2c90.png)

**Comment by LoneGazebo** [comment]
lol. Too sneaky. Why did it not go for Tobolsk??

**Comment by LoneGazebo** [comment]
You got any ideas?

**Comment by ilteroi** [comment]
not really. since saving and loading doesn't work currently (any change in the beta from yesterday?) i simply play and note my observations for a change

**Comment by LoneGazebo** [comment]
Saving and loading isn't working??

**Comment by LoneGazebo** [comment]
No, the current beta is up to date.

**Comment by ilteroi** [comment]
i have a reproducable crash every time after i end the first turn of a loaded game (i.e. loading works only once per session). bad pointer passed in from lua. don't know if it's only me, but it sure is annoying

**Comment by LoneGazebo** [comment]
Odd. EUI? Tried w/o EUI?

**Comment by ilteroi** [comment]
guess it's EUI, yes

**Comment by AnastaseAlex** [comment]
I have the same issue without EUI.

**Comment by ilteroi** [comment]
don't know what to do about this crash. an old pointer seems to be cached on lua side, but i don't have a clue how to debug that

**Comment by LoneGazebo** [comment]
If you're hooked into the stack, where's the pointer coming from?

**Comment by ilteroi** [comment]
lGetPlotCity

**Comment by LoneGazebo** [comment]
Can we just add a null check in the luacity.cpp?

**Comment by ilteroi** [comment]
well that is exactly the problem. the pionter on thevlua stack is not null. but invalid.

**Comment by LoneGazebo** [comment]
Ohh gotcha. Misunderstood. Okay, well that's not good at all. If the problem also occurs in no-EUI, we can assume it is a DLL issue. Is it possible that, between loads, the IDs for owned units/cities change, but the player m_units or m)cities list does not?

**Comment by ilteroi** [comment]
the issue is a bad CvPlot pointer coming from lua side. i don't see the connection to unit IDs ... care to elaborate?

**Comment by LoneGazebo** [comment]
I'm spitballing. I guess my point was that, if it is grabbing a plot city by ID, and the ID of the city doesn't match the cached list of cities in cvplayer, that could result in a crash. I'unno. I haven't looked at the code. We're sure that it is both an EUI and a no-EUI bug?

**Comment by LoneGazebo** [comment]
If it is an EUI bug, that may be the end of EUI support for the CBP.

G

**Comment by ilteroi** [comment]
so you do not see that on your end? that's quite strange cause for me it's 100% reproducable.

with EUI only!

(plus JFDs Bavaria, but that shouldn't be relevant)

**Comment by ilteroi** [comment]
take this savegame, load it, end the turn, load it, end turn, boom

[Pocatello_0300 AD-1860.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/237340/Pocatello_0300.AD-1860.zip)

**Comment by LoneGazebo** [comment]
I do not, experience it, no.

**Comment by LoneGazebo** [comment]
What EUI are you on? The auto-installer version?

**Comment by ilteroi** [comment]
yep

**Comment by LoneGazebo** [comment]
Not sure. Does a similar situation occur w/o EUI?

**Comment by ilteroi** [comment]
nope. just tested that an hour ago. same savegame.

**Comment by LoneGazebo** [comment]
Well then we know it is EUI. Figures. I hate EUI.

**Comment by ilteroi** [comment]
yeah. frustrating. useful but not quite worth the trouble.

can you reproduce it?

**Comment by LoneGazebo** [comment]
I'll try later tonight.
