### ISSUE TITLE
What's the formula for calculating City's Defense Strength?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1638]
How is City:GetStrengthValue() gathered?
Quoted from a 5 year old post
````
6 base strength
1 strength per 4 pop
an exponentially increasing number based on number of techs (that goes up to 48 for all techs)
1/5th of a garrison's strength,
all raw + defense building mods,
and a 15% modifier for being on a hill
````

I know this isn't the case in the CBP anymore, so if anyone could help me find the formula for determining the city's defense strength?

**Comment by LoneGazebo** [comment]
@ilteroi , how'd we end up doing this?

**Comment by ilteroi** [comment]
as always, the answer is more complex than i'd like it to be.

there is a base strength value, computed from

- GC.getCITY_STRENGTH_DEFAULT()
- GC.getCITY_STRENGTH_POPULATION_CHANGE()
- m_pCityBuildings->GetBuildingDefense() * m_pCityBuildings->GetBuildingDefenseMod()
- GC.getCITY_STRENGTH_UNIT_DIVISOR() of garrison strength, double if general is present
- tech modifier GC.getCITY_STRENGTH_TECH*
- GET_PLAYER(getOwner()).GetCityStrengthMod()
- City State only: (GET_PLAYER(eAlly).GetPlayerTraits()->GetAllianceCSDefense() + GC.getBALANCE_CS_ALLIANCE_DEFENSE_BONUS())
- City State only: GC.getBALANCE_CS_PLEDGE_TO_PROTECT_DEFENSE_BONUS()
- Hill and Mountain Bonus GC.getCITY_STRENGTH_HILL_CHANGE()

and then there's the strength for ranged attacks, which includes additional modifiers

- GC.getCITY_RANGED_ATTACK_STRENGTH_MULTIPLIER()
- GET_PLAYER(getOwner()).GetGarrisonedCityRangeStrikeModifier()
- pReligion->m_Beliefs.GetCityRangeStrikeModifier(getOwner())
- GC.GetGameBeliefs()->GetEntry(eSecondaryPantheon)->GetCityRangeStrikeModifier()

**Comment by TechpriestEnginseer** [comment]
So, essentially where would I get these values then?

**Comment by ilteroi** [comment]
I don't know either. the uppercase values come directly from the database. the lowercase ones from traits and beliefs.

**Comment by TechpriestEnginseer** [comment]
So, getting it from the upper values in the CBP's database, 
CITY_STRENGTH_DEFAULT is 5 Combat Strength.
CITY_STRENGTH_POPULATION_CHANGE is 0.3 Combat Strength per citizen.
CITY_STRENGTH_UNIT_DIVISOR looks like 3.5 Combat Strength from any garrison or 35% or its garrison's strength which gets doubled if a Great General is also stationed.
CITY_STRENGTH_TECH looks confusing. 4.0^2.4 or something?
CITY_STRENGTH_HILL_CHANGE grants you 3 Combat Strength if the city is on a hill?

![image](https://cloud.githubusercontent.com/assets/13937047/14807076/b17391e2-0b2d-11e6-9fff-d0094b04af17.png)

**Comment by ilteroi** [comment]
for units the formula is 100/X, ie 350 works out to ~29% of unit combat strength.

the tech factor is indeed a bit tricky, your tech progress through the game is rated on a scale of 0 to TECH_BASE. this value is taken to TECH_EXPONENT power and then multiplied by TECH_MULTIPLIER. since the multiplier seems to be zero, it is all irrelevant though.
