### ISSUE TITLE
Corporations Overview text (4/23 beta)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#1639]
1.Another typo

cf.
(2) Community Balance Patch\Modular Elements\Corporations\Text\en_US\CorpText.xml

```
		<Row Tag="TXT_KEY_CORP_HELP_RESOURCE_BONUS_FIRAXITE_MATERIALS">
			<Text>[ICON_RES_IRON] Iron, [ICON_RES_ALUMINUM] Aluminum, [ICON_RES_MARBLE] Marble, [ICON_RES_COPPER] Copper, [ICON_RES_PORCELAIN] Porcelain provide additional [ICON_GOLD] Gold.</Text>
```

should be

```
		<Row Tag="TXT_KEY_CORP_HELP_RESOURCE_BONUS_FIRAXITE_MATERIALS">
			<Text>[ICON_RES_IRON] Iron, [ICON_RES_ALUMINUM] Aluminum, [ICON_RES_MARBLE] Marble, [ICON_RES_COPPER] Copper, [ICON_RES_PORCELAIN] Porcelain provide additional [ICON_RESEARCH] Science.</Text>
```

-----
2.More Luxuries

I tweaked the **CorpText_en_US.sql** to add More Luxuries to TXT_KEY_CORP_HELP_RESOURCE_BONUS***.
Gazebo, could you check whether it works or not?

http://www.dropbox.com/s/9o6uht82fakegu7/CorpText_en_US.sql?dl=0

cf.
(6a) Community Balance Patch - Compatibility Files (EUI)\Corporations\Text\CorpText_en_US.sql
(6b) Community Balance Patch - Compatibility Files (No-EUI)\Corporations\Text\CorpText_en_US.sql

![corporations overview_1](https://cloud.githubusercontent.com/assets/11933188/14765171/79363aaa-0a10-11e6-992c-1949edf56623.png)
![corporations overview_2](https://cloud.githubusercontent.com/assets/11933188/14765173/7ee84146-0a10-11e6-91bc-847384b442e4.png)

**Comment by mwhiter** [comment]
Thanks.

These are simple text fixes, can someone apply them to the master? I'd like to focus on getting a testable build of the corp architecture this weekend, if possible.
