### ISSUE TITLE
Event Database Issues

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1640]
I discovered a few database errors relating to events that presumably interact with CSD. These events are better off in CSD or in a CSD modmod, or otherwise they should only be added if CSD is active, so that these exceptions are avoided.

The errors are:
[45460.968] Invalid Reference on EventChoice_BuildingClassYieldModifier.BuildingClassType - "BUILDINGCLASS_CHANCERY" does not exist in BuildingClasses
[45460.968] Invalid Reference on EventChoice_BuildingClassYieldModifier.BuildingClassType - "BUILDINGCLASS_WIRE_SERVICE" does not exist in BuildingClasses
[45460.968] Invalid Reference on EventChoice_ResourceQuantity.ResourceType - "RESOURCE_PAPER" does not exist in Resources
[45460.984] Invalid Reference on EventChoice_FreeUnitClasses.UnitClassType - "UNITCLASS_ENVOY" does not exist in UnitClasses
[45461.218] Invalid Reference on CityEventChoice_ResourceQuantity.ResourceType - "RESOURCE_GLASS" does not exist in Resources

The last obviously relates to More Luxuries, but the same should be said of that one.

**Comment by LoneGazebo** [comment]
Those must be with Hokath's events he added.

**Comment by LoneGazebo** [comment]
@Hokath, mind separating out your events that use CBP/C4DF/CSD features so I can add them to those mods separately?

**Comment by Hokath** [comment]
Woooooops.
Will get right on that. In ModBuddy I put in the dependencies but obv I only gave you the xml. Well done me.

**Comment by Hokath** [comment]
[event_csd_text.xml.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/235131/event_csd_text.xml.txt)
[events more lux.xml.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/235130/events.more.lux.xml.txt)

[events_csd.xml.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/235132/events_csd.xml.txt)
[events_morelux_text.xml.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/235133/events_morelux_text.xml.txt)

hope that's everything

**Comment by Hokath** [comment]
[event_csd_text.xml.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/235137/event_csd_text.xml.txt)
[events more lux.xml.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/235139/events.more.lux.xml.txt)
[events.xml.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/235141/events.xml.txt)
[events_csd.xml.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/235140/events_csd.xml.txt)
[events_morelux_text.xml.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/235138/events_morelux_text.xml.txt)
[events_text.xml.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/235136/events_text.xml.txt)

Hope that's all

**Comment by GrantSP** [comment]
I'll just add some extra stuff to this issue rather than creating a new report.

The C4DF module's text files are trying to add entries into a table called:
**Language_zh_CN**
However that table does not exist and if a Chinese version is trying to be used it should be making entries into:
**Language_ZH_HANT_HK**

**Comment by LoneGazebo** [comment]
@GrantSP , please report that to @mwhiter

**Comment by LoneGazebo** [comment]
@Hokath , when you have a chance, upload your latest event files for me so I can update the CP. We should also put the CSD ones etc. in the CBP I guess.

**Comment by Hokath** [comment]
the links above are the latest

**Comment by LoneGazebo** [comment]
Cool.
