### ISSUE TITLE
Missing Unit SelectionSound

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#1641]
1.War Elephant

This code may fix a problem.

```
INSERT INTO UnitGameplay2DScripts (UnitType, SelectionSound, FirstSelectionSound)
	SELECT 'UNIT_CARTHAGINIAN_FOREST_ELEPHANT', SelectionSound, FirstSelectionSound
	FROM UnitGameplay2DScripts WHERE (UnitType = 'UNIT_SIAMESE_WARELEPHANT');
```

-----
2.Firaxis units (ex. Brute, Gatling Gun etc.)

How about incorporating whoward's Sound Corrections minimod?
http://www.picknmixmods.com/mods/CivV/Units/Sound%20Corrections.html

**Comment by LoneGazebo** [comment]
I'll look at whoward's minimod.
