### ISSUE TITLE
magic numbers in notifications.cpp

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1645]
Can someone explain (and comment these) what these are and why they are defined as such?

![image](https://cloud.githubusercontent.com/assets/4925402/14768698/3482d79a-0a17-11e6-912c-a98cec55c832.png)

I'm trying to debug an issue related to notifications and stumbled across those.

**Comment by LoneGazebo** [comment]
They're for events. Because the DLL hates static hashed enums that don't follow their special rule and this was the only way to get it to register the enum hash properly.

**Comment by LoneGazebo** [comment]
This was the only way to get them to work for both the CP without EUI and with EUI.

**Comment by mwhiter** [comment]
Hmmm, so there own comment is false?

![image](https://cloud.githubusercontent.com/assets/4925402/14768743/4c64f996-0a18-11e6-8c50-8bef7ca08290.png)

That's fine. Can we add a comment detailing what they're supposed to represent, because as magic numbers they are confusing.

**Comment by LoneGazebo** [comment]
Yeah, their comment is false because the static hash model only works for the ones they enum'd, and the enums don't work if you add a new static hash! I spent hours and hours futzing with it, only to finally realize that the raw hash numbers were the only solution.

**Comment by LoneGazebo** [comment]
Also, how do you manage to read dark-green-on-black text? You must have excellent eyesight.

**Comment by mwhiter** [comment]
It's actually not that bad on my screen, and I love the night theme, as it's easier on my eyes.

Regarding issues expressed via on this thread: http://forums.civfanatics.com/showthread.php?t=566324

I am going to add a check on the following:

![image](https://cloud.githubusercontent.com/assets/4925402/14768881/34e28ed0-0a1a-11e6-8aa9-7b1f9b0b7688.png)

So this only fires for monopoly notifications. I'd like to experiment and my own notifications up so that I can actually do what I wanted to do with vassalage.

**Comment by LoneGazebo** [comment]
I'd follow suit with what I did. It's a nightmare, but getting the proper hash requires some deft use of the stackwalker and a dummy notification (the hash generator they use - crc32 iirc - appears to not follow the standard crc32 hash generation system!).

**Comment by mwhiter** [comment]
how did you generate that integer? Also, if we're going to go that route, can we also include a comment like 0x013243124 // NOTIFICATION_EVENT_POPUP

so that we're all on the same page in terms of meaning?

And are you saying that FString::Hash("NOTIFICATION_HELLO") != FString::Hash("NOTIFICAITON_HELLO")???

**Comment by LoneGazebo** [comment]
Well the problem is manifold:
You can use FString::Hash like that and they'll equal each other. If, however, you're trying to set up notifications in the notification.cpp to function as a blocker, or in any other way, you need a static enum, and that value isn't static. Thus you need a real number, which you can't get by creating a hash, as the hash function differs if it is put in through lua (i.e. the notification interface) versus the DLL. Thus the only way to really, effectively get it to work is to grab the hashed value as an integer once it has passed from the UI, to the LUA, to the DLL (via Lua), and then to the notification.cpp file in the 'addnotification' function. Grabbing that integer, you have the static value you need.

**Comment by LoneGazebo** [comment]
So while those two fstring hash elements you described are equal in the DLL, they aren't equal if coming from lua, which is f***** maddening (I spent hours debugging it, only to find that the lua was creating a completely different hashed value!!)

**Comment by LoneGazebo** [comment]
If you just want a basic, no-frills notification (i.e. like my instant_yield notification), follow what I did for the instant_yield notification (you can find my static hash in the notification.h file).

**Comment by mwhiter** [comment]
Out of curiosity, you think it would be possible to only catch a string from lua (for example, "NOTIFICATION_WHATEVER" and wrap that in a Lua function that really just calls the DLL FString::Hash, and use that to compare values?

For example, in Lua:

```
-- add notification
Players[0]:AddNotification( Hash("NOTIFICATION_ACTIVE_PLAYER)", .... );
```

and on the DLL side have that function equal:

```
function Hash(CvString str)
{
   //...code
   lua_pushstring(FString::Hash(str));
   return 0;
}
```

I'm not sure if that could solve the problem or not?

**Comment by LoneGazebo** [comment]
The key is making sure that the value is static – the case: functions in notifications.cpp need a static enum. Also, that's not exactly how notifications are handled in the UI (notificationpanel), as they grab the value as it passed to them, but they also parse it.

**Comment by LoneGazebo** [comment]
I don't know if my solution is the only -or best- option, but it works. :)

**Comment by mwhiter** [comment]
I'm just throwing ideas out, but i don't agree they HAVE to be static/constant - whta about int the default block you just do an if-statement compare?

```
default:
   if(m_aNotifications[iIndex].m_eNotificationType == FString::Hash("NOTIFICATION_...."))
break;
```

I'm sure there's another solution. :)

**Comment by LoneGazebo** [comment]
Perhaps, but I don't see what's wrong with the hash integers. I tried a lot of permutations, including stuff like you are proposing, and things didn't always work as I hoped.

**Comment by mwhiter** [comment]
the only thing wrong is that they're not human-readable so a comment next to them will help with maintainability. Magic numbers are never great, maybe it's possible to just define a constant in CustomMods.h and use that const instead?

```
#define NOTIFICATION_EVENT 419811917
```

**Comment by LoneGazebo** [comment]
Could, yeah. I'll just commend for now.

**Comment by LoneGazebo** [comment]
comment*
