### ISSUE TITLE
Worker nolonger aware of danger

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1646]
Latest version.
AI doesn't move it's workers out of harms way any more.
Players workers don't awaken at the end of turn if they are in danger any more.

**Comment by ilteroi** [comment]
hmm. there was a bug but it should have been fixed. need to check

**Comment by Der-Zorn-Gottes** [comment]
So for example, the AI moved a worker on a hill to build a mine. 
I moved a unit next to it on my turn. 
Instead of moving away into a city, the worker stared mining.

**Comment by Radost** [comment]
You are supposed to avoid AI civilian units like a plague, so it's working as intended.

**Comment by ilteroi** [comment]
stupid question, but you were at war, right? or is it your expectation that they should flee on the assumption that you are trying to capture them in a sneak attack?

**Comment by Der-Zorn-Gottes** [comment]
No no, we were at war.

**Comment by ilteroi** [comment]
ok i think i found a possible problem - did you use a melee unit?

**Comment by ilteroi** [comment]
@LoneGazebo : just pushed the fix. danger calculation was broken for melee units ... when's the next release due?

**Comment by LoneGazebo** [comment]
I'm going to be quite busy over the next few days. If you'd like, you can push a hotfix out and post it on the forums. My time will free up dramatically after Friday, so if you want to wait, we can.

G

**Comment by ilteroi** [comment]
i'll be moving house on friday, so i'll be offline for a few days ... guess i'll better post a hotfix now

**Comment by LoneGazebo** [comment]
Cool. Congratulations! I haven't made any edits since 4/23, so yours is the latest. Make sure to merge up to Github when done.
