### ISSUE TITLE
SetAdditionalFood

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1647]
Quick question about SetAdditionalFood() - could it support values less than 1? e.g. 0.5? It doesn't seem to be the case at the moment, but perhaps it requires specific support? Thanks.

**Comment by LoneGazebo** [comment]
I'll check.

**Comment by LoneGazebo** [comment]
Yes, it supports positive and negative values.

**Comment by JFDaly** [comment]
That's not what I'd asked - I'd asked whether it supported decimal values (e.g. 0.5, 0.4, etc.). It's no problem though, I think I've found another way around the issue. Thanks.

**Comment by LoneGazebo** [comment]
Ha, I saw 'less than 1' and my brain said "ah yes, he means negative values." I could make it a hundreds value if that'd help.

**Comment by JFDaly** [comment]
Nah, I think it's fine. Thanks though.

**Comment by LoneGazebo** [comment]
Sounds good.
