### ISSUE TITLE
Social policy costs not increasing

### ISSUE THREAD

**Issue by HerbHertz** [LoneGazebo/Community-Patch-DLL#1648]
Using CP (No CBP) the social policy cost is not increasing after I adopt a policy. Are there any known mod conflicts that could cause this? As far as I know the only other mod I am using that affects social policies is "Civ Names by Policies". I also use EUI if that helps.

**Comment by LoneGazebo** [comment]
What version of CP?

**Comment by HerbHertz** [comment]
The most recent beta from yesterday. (v. 79 if I remember correctly)

**Comment by LoneGazebo** [comment]
Getting database errors?

**Comment by HerbHertz** [comment]
No database errors. After trying a bunch of different mob combinations I think I have narrowed it down to a conflict with Cultural Diversity. I guess I'll just have to play without CD.

**Comment by LoneGazebo** [comment]
I'd let JFD know.

**Comment by LoneGazebo** [comment]
@JFDaly

**Comment by JFDaly** [comment]
@JFDaly didn't seem to alert me :/

I've stumbled upon this as a consequence of CulDiv myself (specifically, the starting bonuses, which aren't being cached properly), so this issue can be closed. I'll be looking into ti.
