### ISSUE TITLE
Can't found a religion

### ISSUE THREAD

**Issue by SpoiledDumpling** [LoneGazebo/Community-Patch-DLL#1649]
I'm playing as the Incans and when I spent my first great prophet to found a religion, I am brought to the religion foundation menu like normal and I can choose from any icons (not already taken), customize my name, etc. but when I click on founder/follower beliefs there is just a blank space where you would normally be able to choose from the selection. Because it's the turn I found a religion, I cannot skip it, and therefore I am unable to advance the game until this is resolved.  
I am not using any other mods than the full CPP pack other than EUI.
The Aztecs founded a religion the turn before I did, so maybe that influenced something.
![image](https://cloud.githubusercontent.com/assets/18650136/14771676/a073b412-0a60-11e6-9708-2e475468d55a.png)

**Comment by LoneGazebo** [comment]
Lua Log?

**Comment by SpoiledDumpling** [comment]
http://pastebin.com/eyuB3Xup

**Comment by LoneGazebo** [comment]
[15989.431] Runtime Error: E:\Users\~\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Community Balance Patch\Modular Elements\ReligionPopup\ChooseReligionPopup.lua:159: bad argument #1 to 'Lookup' (string expected, got nil)

You're using the latest CBP in addition, yes?

**Comment by SpoiledDumpling** [comment]
I downloaded CPP from http://forums.civfanatics.com/showthread.php?t=528034 <- this page using the Automatic Installer and I didn't touch anything so I'm assuming so.

**Comment by LoneGazebo** [comment]
Odd! Try stepping back a save or two, see if getting to that same point causes it again.Or save and reload.

**Comment by SpoiledDumpling** [comment]
Alright, thanks. I've tried reloading and that had no effect on the issue.
It is worth mentioning that I did a single player game before this where I was able to found a religion no problem.
In between those two games, I did set up a multiplayer game with my friend using the MP CPP pack and that worked fine but we haven't reached religious stages of the game yet there so idk if that's causing conflict.
Thanks for the quick and helpful responses! Sorry for not getting a lua log in earlier, I had to figure out how to do that.

**Comment by LoneGazebo** [comment]
Oh! Is the modpack still in your DLC folder?

**Comment by SpoiledDumpling** [comment]
Yup

**Comment by LoneGazebo** [comment]
Remove it – don't run Mods and the modpack at the same time.

**Comment by SpoiledDumpling** [comment]
This fixed it. Thanks for being a huge help!
I can't believe it was something so simple - I even read that in the rules sometime back. Sorry to burden you.

**Comment by LoneGazebo** [comment]
Yay! Glad it worked. No burden at all.
