### ISSUE TITLE
Barbarian Horde CS Quest Stopping Early - Marathon Speed

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#1651]
Playing on Marathon I've noticed that the barbarians stop spawning after 20 turns in, while the horde event total lasts for 60 turns.

**Comment by pandasnail** [comment]
Wait, this is a bug?? Literally this whole time I thought this was an intentional choice to limit CS influence and on kill bonuses that can be gained.

Anyway, its four waves. Once the fourth wave is killed, no more spawn, whether it took four turns or 59.

**Comment by Der-Zorn-Gottes** [comment]
I would propose to have the duration of this event not scale with gamespeed. It's all about military operations, and those are gamespeed neutral.
As it stands, in 60 turns the barbs can almost be killed by city bombardment alone.
