### ISSUE TITLE
Stonehenge description needs an update

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#1654]
Version 4/23, using full CPP and nothing else. Stonehenge description on civilopedia, tech tree and build order states that it gives 30 faith as an instant yield. Should be 50.

**Comment by LoneGazebo** [comment]
Are you on a longer game speed?

**Comment by F0rst1** [comment]
Nope, standard speed.

**Comment by LoneGazebo** [comment]
I'll give it a look, thanks!

**Comment by GrantSP** [comment]
I went looking for this and although I see there is an issue with the text and the code for the building, I found a deeper issue.
The actual code to define the yield change is using this table:
```
<!-- Allows you to define an instant yield granted when a building is constructed. -->
<Table name="Building_InstantYield">
	<Column name="BuildingType" type="text" reference="Buildings(Type)"/>
	<Column name="YieldType" type="integer" reference="Yields(Type)"/>
	<Column name="Yield" type="integer" default="0"/>
</Table>
```
The problem with this is in my database there is no such table being created.
In fact **none **of the tables defined in the **_CoreTableAdditions.xml_** files are found in my database, this means none of the "INSERT INTO" code will work as there is no table insert into.

All of this is with the April 23 beta release and no other mods active, or installed.
Just did a complete delete of cache, moduserdata and then a re-install just to be sure no leftovers are found.

**Comment by LoneGazebo** [comment]
When you load the game, are you loading the debugdatabase?

**Comment by LoneGazebo** [comment]
That's where mod data is stored.

**Comment by GrantSP** [comment]
Yes I know. Debug database is missing those tables in my setup.

**Comment by LoneGazebo** [comment]
Getting a database error? Everything is fine on my end.

**Comment by GrantSP** [comment]
No, no database errors reported in the logs.

**Comment by LoneGazebo** [comment]
Not sure, sorry. Works for me. :/

**Comment by GrantSP** [comment]
Have a look, this is my database.
[Civ5DebugDatabase.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/237845/Civ5DebugDatabase.zip)

Weird that only my install is affected, unless the changes are too subtyle to see without looking.
You have parts 1,2,3,4,5 & 6a installed with nothing else?

**Comment by GrantSP** [comment]
Nevermind, mindfart on my end.
Just re-acquired the installer and re-installed, again, and then started a game and then examined the database.
All good, somehow a vanilla cache remained even after a re-install and that was what was what I was looking at.
Carry on.

**Comment by LoneGazebo** [comment]
That can happen – that's why it is important to clear the cache! :)
