### ISSUE TITLE
CTD (Specific Ship and Town combination)

### ISSUE THREAD

**Issue by Tsenna** [LoneGazebo/Community-Patch-DLL#1656]
Bug Reports - Please fill out the following form:

1. Mod Version (i.e Date - (4/23b)):
**4/23**

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 
**Crash while clicking a specific ship and mouseover a specific town.**

4. Steps to reproduce:
**Video: https://www.youtube.com/watch?v=B00JIfH6riY**

5. Additional information:
**All related Files: https://drive.google.com/folderview?id=0Bx_pqkxiwRYLLWRXaUpyOThnV1U&usp=sharing**

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
Can you post your minidump file?

**Comment by Tsenna** [comment]
All files (minidump, logfiles and savegame) are found in point 5. You can click the folder and watch their content, log files even dont need to downloaded and can be watched directly.

https://drive.google.com/folderview?id=0Bx_pqkxiwRYLLWRXaUpyOThnV1U&usp=sharing

**Comment by LoneGazebo** [comment]
Cool, thanks!
