### ISSUE TITLE
Crash on Turn 361 when selecting specific paratrooper

### ISSUE THREAD

**Issue by CosmicCommander** [LoneGazebo/Community-Patch-DLL#1659]
Bug Reports - Please fill out the following form:

1. Mod Version (i.e Date - (4/23b)):
4/23b

2. Mod List (if using standard CPP set, leave blank):
Civ-Linked Great Generals (v8)
Ethnic Units (v31)
Greatest Cities (v11)
Krakatoa Fix (v100)
Move Capital (v10)
National Parks (v1)
Reforestation (v8)
Sukiract's Events and Decisions (v3)
Unique Cultural Influence (v4)

3. Type of error (i.e. crash, interface bug, AI quirk): 
Sudden CTD upon selecting a specific unit or the game prompting me to move said unit. 

4. Steps to reproduce:
Load the attached save, select the paratrooper immediately to the North of Tomboctu. 

5. Additional information:
No error message accompanying this, if that's pertinent. Just a single quick CTD.

---------------------------

Supporting information:

[Paratrooper crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/235713/Paratrooper.crash.zip)

----------------------------

**Comment by LoneGazebo** [comment]
Someone else reported a similar issue while using Thal's Flag Promotions – are you also using that?

**Comment by LoneGazebo** [comment]
Also, EUI or no-EUI?

G

**Comment by CosmicCommander** [comment]
Not using the Flag Promotions mod. I am using EUI.

**Comment by LoneGazebo** [comment]
The crash went to lua, meaning that the bug is in lua, not the dll. That makes it tough to debug. I'll see what I can do.

**Comment by JFDaly** [comment]
@CosmicCommander You're logs appear to be empty. It's probably too late to re-create the issue, but in the future, see [here](http://forums.civfanatics.com/showthread.php?t=487482) to enable logging.

Re: the issue - in my experience, a sudden crash when trying to select a unit may point to a problem with the upgrade unit. For instance, when the upgrade unit does not have a prereqtech or production cost, this will cause said crash. Do other Paratroopers crash for you, or just this specific one? Do any of your mods change the Paratrooper's upgrade path (is the Paratrooper even in the vanilla game?)?

**Comment by CosmicCommander** [comment]
I had no mods installed that changed paratrooper upgrade paths, other than Community Balance; which makes some major changes as to when it appears in the game and its unit icon. As implied in the OP, it's just this paratrooper on this particular tile which does this.
