### ISSUE TITLE
Repeatable CTD on AI turn

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#166]
I'm getting a consistent, repeatable crash while the AI is taking its turn (T232). Logs are posted on civfanatics, and I'm using all of the main install links save for Health and Plague.

**Comment by LoneGazebo** [comment]
I'm working on a solution, but you may not like it, as it is going to need a DLL fix (some danger plot work from ilteroi seems to have a rare CTD).
G

**Comment by joosegoose** [comment]
That's okay, I kind of assumed any fix would break savegame compatibility
as it seemed like a dll issue. I just appreciate it being fixed :)

If you can fix it soon it would be nice to see a "hotfix" version with no
new features/balance necessarily added though. I'd love to do more
playing/testing, still trying to get a feel for GWAM balance.

**Comment by LoneGazebo** [comment]
Fix incoming in new version.
G
