### ISSUE TITLE
m_unit crash

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1661]
@ilteroi ,

Seeing a few minidumps with a similar crash:

![untitled](https://cloud.githubusercontent.com/assets/7849458/14806129/a6b97e54-0b3e-11e6-94c0-1b9b718ce092.png)

Seems it crashes on grabbing the m_unit ID in cvplayer - comes from the homeland AI and the 'opportunisticsettlermoves' function.

**Comment by ilteroi** [comment]
hmm. i don't see what could be wrong here.

most probably the this pointer is invalid? can you check?

**Comment by LoneGazebo** [comment]
Which pointer? in Homeland AI? The one pushed to this function? The iID was valid. – the only thing giving a bad value was m_units.

**Comment by ilteroi** [comment]
the CvPlayer* in getUnit(). or conversely the m_owner pointer in CvHomelandUnitArray

**Comment by LoneGazebo** [comment]
i'll check.
