### ISSUE TITLE
Not getting pantheon benefits

### ISSUE THREAD

**Issue by sdchargers17** [LoneGazebo/Community-Patch-DLL#1662]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)): Downloaded the newest version of the mod on 4/23/16
2. Mod List (if using standard CPP set, leave blank):
3. Type of error (i.e. crash, interface bug, AI quirk): Some form of major bug
4. Steps to reproduce: Select a pantheon. I chose many different pantheons with different civs and had the same problem-I didn't get anything at all from them.
5. Additional information: Here is a screenshot from my maya game. http://imgur.com/2XMLWey I should be getting plenty of culture and faith from the pantheon (I'm hovering over it but if you can't see it is the +1 faith and +1 culture from each jungle and forest around your city. There are at least 3 in the immediate vicinity and plenty more around, but I'm not getting any culture or faith. I built the stonehenge which is how I'm getting 4 faith per turn, but that's it. Again I tried this with different pantheons and different civs and had the same problem. India is the perfect civ to try this as you get a pantheon right away and I didn't get the bonus from any of them, even the ones that don't require any sort of improvement. Thanks in advance.

**Comment by LoneGazebo** [comment]
This was noted by another user as being related to one of JFD's mods, I believe Cultural Diversity. What is your mod list?

**Comment by sdchargers17** [comment]
I'm using just the Community Patch and I downloaded all of the mods that came with it (more luxuries, EUI etc.). All my other mods are deselected when i start the game.

**Comment by LoneGazebo** [comment]
Deselected, but still present? Try removing all non-selected mods from your MODS folder and then clear your cache.

**Comment by sdchargers17** [comment]
I think I found the problem. I had an old version of the community patch in my mods folder along with the new one I downloaded a few days ago and the game seems to have loaded the old version rather than the new version. After deleting that along with my other mods (though I don't think it had an impact as I only had IGE and diplomacy values downloaded) I now get the pantheon benefits. Thanks!
