### ISSUE TITLE
Nil value (?) in a lua file

### ISSUE THREAD

**Issue by Kavachi** [LoneGazebo/Community-Patch-DLL#1664]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
26 April 2016

2. Mod List (if using standard CPP set, leave blank):
Standard CPP (balance patch, diplomacy, EUI, Compatibility files, luxuries).

3. Type of error (i.e. crash, interface bug, AI quirk): 
CTD.

4. Steps to reproduce:
Happens midway through most games.

5. Additional information:
The lua log from this specific crash is from a game with all Civs (22) + max city states on Marathon.
The error I found was:
 [306526.078] Runtime Error: C:\Users\PRIVATE\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files\Core Values\TechHelpInclude.lua:442: attempt to index field '?' (a nil value)

I hope you can help me with this.
Thanks in advance

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by mwhiter** [comment]
About 100% sure that value won't cause a crash - but it is something to investigate. 

Minidumps will be the only thing helpful for debugging the crash.

**Comment by Kavachi** [comment]
Thanks, I didn't look at the minidump yet. I can't post it right now so I'll have to get back to you later.

**Comment by LoneGazebo** [comment]
Are you missing any DLC?
