### ISSUE TITLE
CTD on turn after the first WC

### ISSUE THREAD

**Issue by jah** [LoneGazebo/Community-Patch-DLL#1665]
1. Mod Version (i.e Date - (4/23b)):
April 23, 2016, beta

2. Mod List (if using standard CPP set, leave blank):
R.E.D. modpack (v. 27)

3. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

4. Steps to reproduce:
Happened at the end of a "Next Turn", in the turn when the first world congress votes would be computed to determine which proposals would take effect. Unsure if this is the actual cause of the CTD, but has happened every attempt to continue that turn.

5. Additional information:

Map type: Communitas
One of the civs that made a proposal (Ethiopia) was eliminated from the game by conquest.

---------------------------

[info.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/236721/info.zip)

----------------------------

**Comment by LoneGazebo** [comment]
Will give it a look, thanks!
