### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by sepsi77** [LoneGazebo/Community-Patch-DLL#1666]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

Using the beta version downloaded last Sunday. The description says v. 79 and 4/23b.

2. Mod List (if using standard CPP set, leave blank):

Full CPP set (including EUI that's part of the set)
InfoAddict (v.22)

3. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

4. Steps to reproduce:
Load the attached save and click next turn. The game will CTD when America completes the corporation.

5. Additional information:

Got well over a dozen CTDs during this game, including one that resembles another big report reported here recently:
https://github.com/LoneGazebo/Community-Patch-DLL/issues/1656

Was able to get through the other crashes by avoiding some actions. But this one seems impossible to avoid.

Can't upload a ZIP file here. Please find the requested logs, save and minidump here:
https://drive.google.com/open?id=0Bx2ZkeTh7NE_ZUd4QTdEd0JzdkE

**Comment by LoneGazebo** [comment]
Will give it a look, thanks!

**Comment by GrantSP** [comment]
This CTD report matches my experience the most so I'll add my crash dump here.
This is actually the 3rd crash in this particular game and I can't pinpoint an exact trigger.
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/244741/CvMiniDump.zip)

Except for InfoAddict my setup is the same.
