### ISSUE TITLE
Stacked garrisons

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#1667]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

4/23b

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 

I have 2 garrisons in a city and both were able to attack

4. Steps to reproduce:

Have a garrison and build a unit in the city. You don't get a "move stacked unit" command.

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed

[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/236908/Database.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/236909/Lua.zip)

2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

![20160426180354_1](https://cloud.githubusercontent.com/assets/18663580/14823031/a760e8ba-0bd9-11e6-9ed0-cb4b2565d978.jpg)

----------------------------

**Comment by F0rst1** [comment]
At the start of the next turn, one of the garrisons had teleported to a tile next to the city.

**Comment by ilteroi** [comment]
cannot reproduce.

there was a small bug in the pathfinder in the 4/23 version, which has since been fixed, maybe that was the cause.
