### ISSUE TITLE
Event Check Question

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1669]
Does (City)Event_MinimumResourceRequired work with bonus resources or only strategics (and luxes?)?

**Comment by LoneGazebo** [comment]
Should work with any resource, though I'm not 100% sure how cvplayer handles bonus resources from a numeric standpoint. I think it works the same as strategic and luxes, though.

**Comment by Hokath** [comment]
Cool. We'll find out in due course.
