### ISSUE TITLE
pathfinder is too smart for its own good

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1670]
pun fully intended :)

![image](https://cloud.githubusercontent.com/assets/1358966/14829694/0d9511d4-0bed-11e6-87dd-333c167d54e4.png)

normally, the pathfinder would not advance from the city when it kills the warrior.

however, since there is a penalty for attacking across the river, it prefers to take the roundabout way and ends up being killed by the second french warrior.

problem or not? it's a rather rare situation ...

**Comment by LoneGazebo** [comment]
It would be vulnerable to being killed, though, so it does come off as a 'dumb play' (if the AI did that, the player would see it is a bad move).

**Comment by LoneGazebo** [comment]
On the other hand, it isn't the worst decision ever. :)

**Comment by ilteroi** [comment]
ok, i found an easy fix, attack penalty cost is ignored when the unit is in a city
