### ISSUE TITLE
Unit movement interface bug

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#1671]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

Hotfix for 4/23 version

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 

Interface bug. Right-clicking (and holding) creates a blue circle around just one tile where the unit can move instead of all possible tiles. The tile that is highlighted is different if you do it again. 

4. Steps to reproduce:

Right-clicking a unit

5. Additional information:

I removed cache and mod user data, but it didn't help.

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed

[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/237778/Database.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/237779/Lua.zip)

2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

![20160427041926_1](https://cloud.githubusercontent.com/assets/18663580/14838976/9874728a-0c2f-11e6-934a-1f0d3b5f6db1.jpg)

----------------------------

**Comment by LoneGazebo** [comment]
@ilteroi , your patient is on the operating table. :)

**Comment by ilteroi** [comment]
damn. that's in fact harmless. just some debugging code i forgot to deactivate.

new build up soon
