### ISSUE TITLE
Stone wonder building boost not specified in Pedia.

### ISSUE THREAD

**Issue by alexb5dh** [LoneGazebo/Community-Patch-DLL#1672]
Not sure if stone boost was added in CBP as I haven't played vanilla Civ for a long time.

Marble description say about its boost to wonder building in Ancient and Classical eras, but similar info is missing for Stone.

There is no way player can now about this unless he get Stone in one of his cities.

Mod version: 4/23b

**Comment by F0rst1** [comment]
And even the marble description is wrong, since it actually boosts pre-industrial (or pre-renaissance?) wonders, not just ancient and classical.

**Comment by LoneGazebo** [comment]
I'll look.
