### ISSUE TITLE
Barracks/Forge yield icons not updated after building Arena

### ISSUE THREAD

**Issue by alexb5dh** [LoneGazebo/Community-Patch-DLL#1673]
Hope this is not an EUI issue and can be fixed in CPP.

Arena doesn't update yield icons in city view for Barracks and Forge. Order of building doesn't matter.
Description still states correct production yield.
It probably affects any buildings whose effects can be changed by another.

![image](https://cloud.githubusercontent.com/assets/4650832/14845276/d3b8fb46-0c65-11e6-8cd9-a6c1a50b3c26.png)

Mod Version: 4/23b

**Comment by LoneGazebo** [comment]
This is an EUI issue, I believe, as it does not occur without EUI.
