### ISSUE TITLE
God-King Pantheon bonus yield does not appear to be correct

### ISSUE THREAD

**Issue by junglerhino** [LoneGazebo/Community-Patch-DLL#1674]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)): CP .72

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): Bonus yields in capital do not appear to be calculated correctly.  My capital is population 5 with 3 Pantheon followers - so I would not expect to receive any bonus yet as I do not have 6 followers.  However the city screen is showing an additional +5 gold/faith/science/culture being generated per turn.

4. Steps to reproduce: 

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
It counts for all followers of your pantheon in all cities, not just in one city.

**Comment by LoneGazebo** [comment]
Do you have other cities?
