### ISSUE TITLE
Alternative aspect ratio for event art

### ISSUE THREAD

**Issue by XonyCiv** [LoneGazebo/Community-Patch-DLL#1677]
It would be nice if the Eventpopups allowed the use of a more square aspect ratio for the event art. That would allow a more gorgeous presentation of certain artwork like the Eiffeltower, which would elevate the enjoyment of events for me and hopefully also for others. It's not a priority of course, but just wanted to get it out here on github so maybe one of the awesome UI-coders here can see it. 

My rudimentary code back from the 4/5 beta:
```
if pEventArt then
		 Controls.EventArt:SetTextureAndResize(pEventArt)
			local iSizeEventArtX, iSizeEventArtY = Controls.EventArt:GetSizeVal();
			print(iSizeEventArtY)
			if iSizeEventArtY < 180 then
				Controls.ItemScrollPanel:SetSizeVal(500,380);
				Controls.EventArtFrame:SetTextureAndResize("EventFrame.dds");
				Controls.EventArtFrame:SetSizeVal(365,105);
				Controls.EventArt:SetSizeVal(350,100);
				Controls.EventArt:SetHide(false);
				Controls.EventArtFrame:SetHide(false);
			else
				Controls.ItemScrollPanel:SetSizeVal(500,460);
				Controls.EventArtFrame:SetTextureAndResize("EventFrame180.dds");
				Controls.EventArtFrame:SetSizeVal(365,185);
				Controls.EventArt:SetSizeVal(350,180);
				Controls.EventArt:SetHide(false);
				Controls.EventArtFrame:SetHide(false);
			end
		else
			Controls.EventArt:SetHide(true);
			Controls.EventArtFrame:SetHide(true);
		end
```

[Uploading EventFrame180.zip…]()

**Comment by TechpriestEnginseer** [comment]
I remembered Sukritact made his event popup adjustable to the user's resolution so that it never exploded nor were minimized because it relied on getting the X and Y values of another UI(since that UI would readjust itself) and then the coding would readjust itself, I'll look into it and see how he did it.

**Comment by JFDaly** [comment]
The UI already does readjust, but according to the size of the text.
