### ISSUE TITLE
Religious National Wonders and Mapsize

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1678]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)): First hotfix for 4/23

2. Mod List (if using standard CPP set, leave blank): Full CBP, no EUI, and other minor mods.

3. Type of error (i.e. crash, interface bug, AI quirk): Guess I'm not 100% sure this is a bug, and not a balance choice, but if its a choice I fundamentally disagree lol. Anyway, the consensus seemed to be move the required pop for a Religious National Wonder down on Huge maps. I didn't check right away, when I noticed someone else posted on this on the forum, I looked at mine, and it says needs 26% more global followers. Haven't checked what it is on the smaller maps, if it got flipped or if every map size is the same percentage.

4. Steps to reproduce:

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
May have been a bug on my end during generation. I'll check.
