### ISSUE TITLE
[3-19] 2 times Faith from Organized religion

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#168]
Just noticed that the policy Organized religion adds +2 faith two times for both Temple and Shrine in the Policy_BuildingYieldsClassChanges table (e.g. theres two entries giving +2 faith for shrines and two entries for temples). Don't know if it affects game play though.

\Skodkim

**Comment by LoneGazebo** [comment]
I'll fix – it is innocuous, but sloppy.
G
