### ISSUE TITLE
Temple Event: Grand Temple chooseable without enough gold

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1680]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)): 4/23 hotfix

2. Mod List (if using standard CPP set, leave blank): Full nonEUI CBP and some minor stuff

3. Type of error (i.e. crash, interface bug, AI quirk): In the other religions temple event, I could choose destroy the Temple, build a Grand Temple even tho I had 900something instead of the listed 1500. It did take all of it when I selected it at least.

4. Steps to reproduce:

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by Der-Zorn-Gottes** [comment]
That is also true for the tourism boost of the masterpiece event (from Amphitheater). (version 4/23)
