### ISSUE TITLE
[Suggestion] Citadel damaging submarines, both revealed and unrevealed

### ISSUE THREAD

**Issue by cosmosgu** [LoneGazebo/Community-Patch-DLL#1681]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
3/9 modpack

2. Mod List (if using standard CPP set, leave blank):
CBP

3. Type of error (i.e. crash, interface bug, AI quirk): 
Suggestion

4. Steps to reproduce:
Citadel will damage submarines regardless of whether they are revealed or not. It would be more immersive if only revealed submarines are damaged.

5. Additional information:
Nice template!

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by ilteroi** [comment]
makes sense. should be easy to do.

**Comment by cosmosgu** [comment]
@ilteroi Thanks ilteroi!
