### ISSUE TITLE
Event Request - <EventChoice_FreeUnit>

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1682]
We have <EventChoice_FreeUnitClasses>, but if I want to give say Longbowmen to England, or Berserkers to Sweden, I can't do it. Is a FreeUnit equivalent possible?

**Comment by LoneGazebo** [comment]
It could be added, but those units have their own unit classes in the CBP, no? If you're referring to the base CP, it'll give them the proper unitclass for their civ.

**Comment by Hokath** [comment]
Ah yes so it works for those retired units like the longbow, found that out.
`(UPDATE Units SET Class = 'UNITCLASS_LONGBOWMAN' WHERE Type = 'UNIT_ENGLISH_LONGBOWMAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );`

But the Berserker is the Danish UU still. It's UnitClass_Longswordsman with the UU override, so I can't give it to Sweden.

**Comment by LoneGazebo** [comment]
Ah. I'll look at freeunit.
