### ISSUE TITLE
TXT_KEY on all tooltips

### ISSUE THREAD

**Issue by Nichlenm** [LoneGazebo/Community-Patch-DLL#1683]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
4/23 + Hotfix DLL

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 
Tooltip Headings are all displaying TXT_KEY errors. most noticable ones on the the tech tree and on the diplomacy modifiers, but they seem to appear frequently elsewhere.
![2016-04-28 20 16 08](https://cloud.githubusercontent.com/assets/18715891/14879942/40cf7820-0d80-11e6-9448-9bb435e9d71e.jpg)
![2016-04-28 20 17 57](https://cloud.githubusercontent.com/assets/18715891/14880116/59387758-0d81-11e6-9b45-0fd3dc97f5ae.jpg)

4. Steps to reproduce:
I only have the Community Patch enabled (not CBP)

5. Additional information:
I usually play with a fair amount of mods, but I am still having this issue with just CP enabled (and after verifying game integrity through steam and clearing the cache). These photos were taken with just CP enabled. I have used EUI in the past but it is unistalled and have verified integrity etc. I have had this problem throughout the last few updates for at least the past month.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/240112/Logs.zip)

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
Did you clear your cache by deleting the contents of your documents/my games/civ 5/cache folder? Do you have any other mods in your mods folder?

**Comment by Nichlenm** [comment]
Yup i cleared my cache and verified integrity through steam. I have other mods in my folder but none of them are enabled. (these include JFDs mods, Historical religions, Events and Decisions, a few civs and other minor mods)

**Comment by LoneGazebo** [comment]
I'd remove them all. Also make sure there are no old copies of the CP in there.

**Comment by Nichlenm** [comment]
Ok so I removed everything and fresh installed the CP and now all is well. I will slowly add my other mods back so I can get rid of the culprit. Thanks for your help.
