### ISSUE TITLE
Event on City raze issue

### ISSUE THREAD

**Issue by Mixelplux** [LoneGazebo/Community-Patch-DLL#1685]
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/240887/Database.zip)
Bug Report Template

1. Mod Version (i.e Date - (4/23b)): 4/23a

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 
Had an event occur same round as a razed city got destroyed. The event icon stays active and can't be selected/removed. 20 turns later so far no new event has occurred. I will continue to play this save to see if any event will occur in the future in this situation.

Edit: New event occurred, but Event icon is still there.

Edit 2: Not sure if related, but at this point all city captures don't open the raze/annex/puppet dialog. No raze options in following turns either.
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/240891/Lua.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/240892/Database.zip)

4. Steps to reproduce:

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
Did the icon go away after the city was destroyed?

**Comment by Mixelplux** [comment]
No, I played about 50 turns past the event appearing and the Icon never went away, even after other events happened.

**Comment by LoneGazebo** [comment]
Odd.
