### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by cononderbee** [LoneGazebo/Community-Patch-DLL#1688]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)): 4/23

2. Mod List (if using standard CPP set, leave blank): CPP-EUI
InfoAddict
JFD's The Soviet Union (Lenin)

3. Type of error (i.e. crash, interface bug, AI quirk): Crash to desktop--occuring randomly during my turns, in the middle of an action.

4. Steps to reproduce:

5. Additional information:

---------------------------

Supporting information:

----------------------------

**Comment by cononderbee** [comment]
Sorry, GitHub isn't letting me upload the Zip files for some reason. I'll try to attach the logs tomorrow.

**Comment by LoneGazebo** [comment]
Minidump file?

**Comment by cononderbee** [comment]
Not sure why github isn't recognising the file properly, so find it here: https://www.dropbox.com/s/j2fv1g523uhfebc/Logs.zip?dl=0
