### ISSUE TITLE
BUGFIX_DUMMY_POLICIES from VMC

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1689]
This option requires Dummy column in Policies table.

**Comment by LoneGazebo** [comment]
Not sure what you're referring to. That isn't incorporated into the CP, as we have our own fix.

**Comment by qqqbbb** [comment]
What our own fix?
Method GrantPolicy is incorporated into CP and it  requires Dummy column in Policies table to work properly.

**Comment by LoneGazebo** [comment]
I don't know that we incorporated this BUGFIX_DUMMY_POLICIES into the CP. Cannot recall.

**Comment by JFDaly** [comment]
Yup, BUGFIX_DUMMY_POLICIES was added to the CP (April 9th, IIRC). The CP automatically sets up the IsDummy column, but I have started to use GrantPolicy as a precaution. I've felt no fault to this - @qqqbbb what's the issue you're having?

**Comment by qqqbbb** [comment]
I don't have any issues. I just expexted to find Dummy column and did not know about IsDummy.
 How does the game decides which policies should have IsDummy set to 1?

**Comment by JFDaly** [comment]
It checks that the PolicyBranchType is null and that it isn't given out as a free policy; opener or finisher.
