### ISSUE TITLE
Interface looks unmodded

### ISSUE THREAD

**Issue by Kerbolosh** [LoneGazebo/Community-Patch-DLL#1691]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
newest version, 2016-03-09

2. Mod List (if using standard CPP set, leave blank):
CPP
CBP

3. Type of error (i.e. crash, interface bug, AI quirk): 
interface not changing, looks still like unmodded Civ 5

4. Steps to reproduce:
I originally played the german version of Civ 5. For this  mod i changed it to english via steam. Then i used the installer as well as the manual installation steps mentioned in the .pdf from the forums. I activated the corresponding Mods in the menu in Civ 5.
I use Windows 10.

5. Additional information:
I tried to delete Civ completely and downloaded a fresh version from steam and changed the language to english before starting Civ for the first time.

If you need any more information or files, I will gladly provide them.

**Comment by TechpriestEnginseer** [comment]
Screenshots of how the interface is "not changing"?

**Comment by Kerbolosh** [comment]
Basically everything looks like normal Civ 5 without any mod. Meaning all tooltips, policy screen tech screen show the unchanged informations.

I am at the office at the moment, and can not upload a screenshot at the moment, but i can do it as soon as i get home.

**Comment by LoneGazebo** [comment]
Sounds like you aren't hitting 'next' on the mods menu. Are you? Or are you hitting back, then launching a single player game?

**Comment by Kerbolosh** [comment]
Yes, Thank you.
Sorry, that I am such an idiot for stealing your time, because of my stupidity. Never played a mod before and i didnt see the huge button, saying Single Player, I always clicked back,...
![image](https://cloud.githubusercontent.com/assets/18732599/14934718/58476cde-0eba-11e6-8e60-2dde5e49dd66.png)

Looking forward to try your mod now.

**Comment by LoneGazebo** [comment]
No worries! Glad it is working.

G
