### ISSUE TITLE
Right side notification for espionage  CS quest has no text

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1693]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)): 4/23 hotfix

2. Mod List (if using standard CPP set, leave blank): Full non Eui CBP and minor stuff. I guess at some point I'll list out this minor stuff, then I can copy paste from then on. But not for this minor bug lol

3. Type of error (i.e. crash, interface bug, AI quirk): The right side notification for an espionage shows no text besides the reward. Have to click the notification to even know what City State it is.

4. Steps to reproduce:

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
Cannot reproduce.
