### ISSUE TITLE
Player with no cities stays in the game

### ISSUE THREAD

**Issue by Jotaro31400** [LoneGazebo/Community-Patch-DLL#1696]
Bug Report Template

1. Mod Version : 4/23

2. Mod List : CBP full with EUI + No Ice on Coast

3. Type of error : Assyria hasn't got any city but still in the  game.

4. Steps to reproduce:

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

![20160429230456_1](https://cloud.githubusercontent.com/assets/18736009/14929865/1da74298-0e60-11e6-9efb-955f0a28d423.jpg)

----------------------------

**Comment by LoneGazebo** [comment]
@ilteroi , any recent changes to player status for kill?

**Comment by biship** [comment]
If "Require complete kills" is selected when setting up a game, this happens.

**Comment by ilteroi** [comment]
no changes. never seen this except if intended by game options
