### ISSUE TITLE
Policy_GoldenAgeYieldMod

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1697]
I notice that Issues are piling up, so I don't want to add any more to your queue than I must, but hopefully this is simple: Can you check that Policy_GoldenAgeYieldMod allows for negative yields? From my testing, I would guess there's a > 0 check. 

Also, relatedly, does city:GetModFromGoldenAge() return the value of the above? It doesn't appear to, even when the yield modifier is positive - perhaps it works for Building_GoldenAgeYieldMod only?

**Comment by LoneGazebo** [comment]
Yep! Most of the reports are just crashes, probably linked to the same issue.

I'm not sure re: getmodfromgoldenage. I'll check.

**Comment by LoneGazebo** [comment]
It did not, but it does now. :)

**Comment by JFDaly** [comment]
Thanks!
