### ISSUE TITLE
Hang on processing opponent's turn

### ISSUE THREAD

**Issue by JonathonAshworth** [LoneGazebo/Community-Patch-DLL#1699]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

3rd March (latest non-beta)

2. Mod List (if using standard CPP set, leave blank):

full CPP/CBP set w/ EUI

3. Type of error (i.e. crash, interface bug, AI quirk): 

Infinite hang on processing turns, can still go into menus and interact with the game, but the player's next turn never comes around. Trying to load a game while in this state causes a CTD. Loading an autosave and playing the turn again sometimes works, but 1-3 turns later the infinite hang will happen again.

4. Steps to reproduce:

Get about 10-20 turns into any game.

5. Additional information:

Operating system is Ubuntu 15.10 with Wine. Can't reproduce in an unmodded game.

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/243460/Logs.zip)
[CvMiniDump.dmp.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/243461/CvMiniDump.dmp.zip)

**Comment by a1nosweat** [comment]
I have the same issue.  trying with dx9 now.  only in sp, not hotseat (yet)

**Comment by a1nosweat** [comment]
reinstalled - still hangs.

Removed EUI - Fixed!

**Comment by LoneGazebo** [comment]
EUI can definitely cause problems. Closing, since it works now.

**Comment by a1nosweat** [comment]
ooops...happened again - less frequent now.  Also I'm not op.

**Comment by LoneGazebo** [comment]
Ilteroi's got a significant amount of bugfixes upcoming, so we'll see if that fixes these CTDs and hangs.

**Comment by JonathonAshworth** [comment]
Just thought I'd chime in with a comment, I tested with EUI disabled as suggested by @a1nosweat, still getting the same problem. I'll wait and see what happens with Ilteroi's fixes. If the problem persists, will this be reopened?

**Comment by a1nosweat** [comment]
I get good results with eui off and running dx9 with all graphics on low and other settings removed.  normal dx11 settings ctd.

Experimenting with middle ground now - Can't wait for next version.

**Comment by JonathonAshworth** [comment]
Still happening in the new version. With and without EUI.

Here's some updated logs.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/272302/Logs.zip)
