### ISSUE TITLE
Rise to Power requests

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#1700]
I have three/fourrequests for Rise to Power (the Currency/Sovereignty stuff you implemented a while back). I thought I'd ask it now, before you implemented the Mercenaries (also RtP) stuff.

First, I'd ask for you to add **YIELD_JFD_SOVEREIGNTY**, in similar manner to YIELD_JFD_PIETY et al. I alerted you a while back that I'd need this. And don't worry, this is the last yield I need (I said that for Loyalty last time, but that was for CID) - Sovereignty is my last big mod (and has been the one in the works for longest).

Secondly, I'd like to ask for a **player:SetProsperityScore(value)** and **player:GetProsperityScore()**. This would store a simple integer, which would only ever range between 0.0 to 1.0 (or 0 to 10 if single decimals are more demanding - I can just divde the value when I retrieve it). This is complementary to the Currency stuff that you worked on, and saves the game from having to calculate this score more than once per turn.

Finally, could you please check **player:GetPolicyGreatPeopleRateModifier()**. It would appear that this doesn't support negative values (but instead of just ignoring a negative one, it inverts it - so my -20% penalty becomes +20%).

Take your time, and much appreciated if you can add these! Please let me know if there's anything else I can help with in return.

**Comment by LoneGazebo** [comment]
On it!

**Comment by JFDaly** [comment]
Awesome, thanks much!

**Comment by LoneGazebo** [comment]
Alright, done. It'll be in the next version. It will be an integer, so you'll need to divide by 10 to get the decimal value (floats don't play nice with lua).

**Comment by LoneGazebo** [comment]
Also, the modifier only supports positive values, as it is a constant value (Firaxis did this with a bunch of their vanilla values). There's no easy way around that.

**Comment by JFDaly** [comment]
No worries then, that request can be skipped.

**Comment by LoneGazebo** [comment]
Yep! The prosperity functions will be in the next version.

**Comment by JFDaly** [comment]
Just checking in to confirm that the new Prosperity and Sovereignty things work great and help much! Thanks!

**Comment by LoneGazebo** [comment]
Awesome!
