### ISSUE TITLE
Development structure suggestion

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1701]
I have noticed a lot of my merge conflicts / errors stem from the Build/ files that are created by ModBuddy. I am of the opinion that they are rather unnecessary to version control, as those are automatically generated and don't need to be versioned. After I've stopped committing those to version control, I have noticed my merge conflicts to shrink considerably (also, I've been using helper branches to merge my code, which is going to be an absolute pain today due to the large amount of code I have).

Locally, I am going to [edit my .git/info/exclude](http://stackoverflow.com/questions/1753070/git-ignore-files-only-locally) to exclude any mod Build/ directories. Maybe this could be a discussion point, for someone to explain why it is as it is now, and how we can improve?

**Comment by LoneGazebo** [comment]
They should be excluded. I had it that way but I think a merge with another user's gitexclude at some point caused it to return.

**Comment by mwhiter** [comment]
@LoneGazebo Well that is refreshing. Let's make an effort to fix the repo. It's actually quite bloated with a lot of folders that I've never seen before and have no idea what they do. (What is the Corporations/ directory, for example)?

**Comment by biship** [comment]
Is there a chance you can add a folder (and code) and modbuddy solution for "(5) More Luxuries" & the missing modbuddy solutuion for "(3) CSD for CBP"?

Then we have everything we need to compile everything you distribute with the betas and stable 
releases.

\Corporations directory can be deleted as it looks to be in \Community Balance Patch\Modular Elements\Corporations and \* Compatibility Files

**Comment by LoneGazebo** [comment]
\Corporations is for the standalone version.

**Comment by mwhiter** [comment]
So for knowledge transfer's sake, is this standalone corporation being actively worked on at the 
moment?

**Comment by LoneGazebo** [comment]
Yes, but I'm not moving forward until you've got your structural rework in a state you are happy with.

**Comment by mwhiter** [comment]
Very nice. So I think I have one issue left with the civilopedia, then I have to run a series of tests to check that it works the way I want it to, and then I'm ready to release. It's been slow, because I've been swamped lately.

As for the projects thing - I've decided to not move the HQs to projects because it's a large cost for little benefit.

**Comment by LoneGazebo** [comment]
Sounds good to me. I'm just now tackling the issues backlog, so you are by no means behind schedule. :)
