### ISSUE TITLE
More Luxuries

### ISSUE THREAD

**Issue by Leotheo** [LoneGazebo/Community-Patch-DLL#1703]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

More Luxuries - CBP Edition (v.155)

2. Mod List (if using standard CPP set, leave blank):

CPP Newest Version: March 9th (1.3.9)

3. Type of error (i.e. crash, interface bug, AI quirk): 

If I switch on More Luxuries Mod, then my map is missing all Plantation type resourse, Whales and Crabs. Only Mine type resourses are visible. Other civs and CSs are also missing on the map, while I see them being scrolled after I end my turn. Barbarians are present. 
If I switch off More Luxuries, leaving all other CPP Mods on, everything works fine.

4. Steps to reproduce:

5. Additional information:

My CIV V game is in Russian language. After installing CPP Mods I replaced Language_en_US with Language_ru_RU in all .sql and .xml files as was advised at http://forums.civfanatics.com/showthread.php?t=539883, and it worked well.

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
This is a known issue if your copy of civ is not up to date. Please update your copy of civ to the latest (.279).

**Comment by LoneGazebo** [comment]
This is a known issue if your copy of civ is not up to date. Please update your copy of civ to the latest (.279).

**Comment by LoneGazebo** [comment]
This is a known issue if your copy of civ is not up to date. Please update your copy of civ to the latest (.279).

**Comment by LoneGazebo** [comment]
This is a known issue if your copy of civ is not up to date. Please update your copy of civ to the latest (.279).

**Comment by LoneGazebo** [comment]
This is a known issue if your copy of civ is not up to date. Please update your copy of civ to the latest (.279).

**Comment by LoneGazebo** [comment]
This is a known issue if your copy of civ is not up to date. Please update your copy of civ to the latest (.279).

**Comment by LoneGazebo** [comment]
This is a known issue if your copy of civ is not up to date. Please update your copy of civ to the latest (.279).

**Comment by LoneGazebo** [comment]
This is a known issue if your copy of civ is not up to date. Please update your copy of civ to the latest (.279).

**Comment by LoneGazebo** [comment]
This is a known issue if your copy of civ is not up to date. Please update your copy of civ to the latest (.279).

**Comment by LoneGazebo** [comment]
This is a known issue if your copy of civ is not up to date. Please update your copy of civ to the latest (.279).

**Comment by LoneGazebo** [comment]
This is a known issue if your copy of civ is not up to date. Please update your copy of civ to the latest (.279).

**Comment by Leotheo** [comment]
Thanks a lot. That helped indeed!
