### ISSUE TITLE
Ocean crossing Galleasses

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#1705]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
I noticed it on the 4/23b version but another user saw it in the 4/10 release.

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 
Galleasses of other AI players crossing oceans.

4. Steps to reproduce:
Unsure. Doesn't seem to be universal or observable in all games. Unable to see if the AI had researched anything or otherwise acquired this ability.

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by ilteroi** [comment]
can you please check whether they have the 'cannot enter deep ocean' promotion?

**Comment by GrantSP** [comment]
According to the database all gallasses have the PROMOTION_OCEAN_IMPASSABLE set as a free promotion.
None of my units can enter the ocean and the 2 civs that were observed doing so, Korea and Assyria, don't have any special traits that should override this. e.g. Polynesia

**Comment by ilteroi** [comment]
i know all galeasses are supposed to have that negative promotion, but did the offending ones really have it?

**Comment by GrantSP** [comment]
If I see it happen again, I'll check, but as for these times, sorry no way for me to check anymore.
Not exactly sure what would be able to remove that promo for only those civs? As the player's units, and that of other civs, could not enter the ocean.

**Comment by LoneGazebo** [comment]
If the unit was upgraded, it could lose it. Or it could be a spawning issue. We'd need more info.

**Comment by GrantSP** [comment]
Not sure how to gather that info?!
Are spawned units logged anywhere?
Why does upgrading it by the AI provide a result to the player? Most of my galleasses would have been upgraded dromons.
More to the point how could I know until I see them?

**Comment by LoneGazebo** [comment]
Well, we'd have to see it happen. If a unit, say a dromon, has the bonus, but then upgrades, it might lose the bonus. Could be a quirk. It'd have to be caught in-action.

**Comment by GrantSP** [comment]
In other words: extremely hard to catch and therefore fix?

**Comment by LoneGazebo** [comment]
Yep. :)
