### ISSUE TITLE
You have denounced a leader they have made a declaration of friendship with!

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1706]
Mod Version:
Any version since this was always a bug since vanilla.

Type of error (i.e. crash, interface bug, AI quirk): 
AI quirk.

Steps to reproduce:
Denounce a civilization that has DoFs.
Eliminate that said civilization.
Watch DoF's civilizations linger on their penalty until the end of the game or until the civilization is then liberated for it to expire.
This has always been prevalent in warmongering games even in vanilla where if you denounced a leader and the leader suddenly gets wiped out, the penalty of denouncing them will be permanent.

**Comment by LoneGazebo** [comment]
I'll look at it, but no promises. It's not necessarily a bad thing, a permanent malus.

**Comment by LoneGazebo** [comment]
Fixed.
