### ISSUE TITLE
Civ and entire computer crashes when clicking next on mods screen

### ISSUE THREAD

**Issue by nobody1313** [LoneGazebo/Community-Patch-DLL#1707]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
I'm using the mod version 1.3.9 (March 9th)

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 
When I enable the mods from the CPP on the mods screen then press next, the globe icon will spin for a minute or two, then my computer will crash with the erorr code DRIVER_POWER_STATE_FAILURE. This also happens when using the DLC modpack version of the mods.

4. Steps to reproduce:
I believe this issue is specific to my computer.

5. Additional information:
I have tried fully reinstalling the mods, DLC Modpack, all of Civ V, and reinstalling Steam. None of these have solved the issue. I have also updated all of my drivers as I thought it may be related to the error code, but it did not help.
I have also attached all the log files for the last time I launched Civ and pressed next on the mod selection screen (my computer crashed that time, too).
[Civ V Log files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/244408/Civ.V.Log.files.zip)

**Comment by nobody1313** [comment]
Also, here are three minidump files from when my computer crashed because of this issue.
[Minidumps for Github.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/244414/Minidumps.for.Github.zip)

**Comment by LoneGazebo** [comment]
That sounds like a computer issue ('driver error'). There's not much I can debug if you are having the issue prior to the mod fully loading.

**Comment by nobody1313** [comment]
I understand. Are there any recommendations you could give me on how to get it to work? It's only with this specific modpack, pretty much everything else civ-related works on my computer.
