### ISSUE TITLE
CTD in first 4-9 Turns (~1st policy, maybe choosing second tech)

### ISSUE THREAD

**Issue by Liebfraumilch** [LoneGazebo/Community-Patch-DLL#1708]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):  

1.3.9 

2. Mod List (if using standard CPP set, leave blank):

Everything via Autoinstaller including EUI.

3. Type of error (i.e. crash, interface bug, AI quirk): 

Game simply closes out without warning in first 10 turns, usually after adopting a policy or perhaps a tech.  I have done the following: 

1) deleted and reinstalled CPP set many times on Autoinstall, including twice manually setting EUI in place just in case
2) cleared cache (the one in the My Games path) many times, 
3) validated Civ with Steam many times, 
4) restarted computer many times after or before some of these actions, 
5) tried different advanced game setup settings many times in case one preference/combination was at fault, 
6) uninstalled and reinstalled Civilization V through Steam, tried it but CTD again, and did everything above even more times.

I don't know how to get past this turn 4-9ish crash, but I HAVE made it past.  Only three times out of countless attempts, though.  I even completed my first game, and then suffered the CTD next time I tried to start a new one after closing the program for the night.  

Cannot figure out what caused my three successful (past turn 15, say) games.  I just want to enjoy your awesome project!

4. Steps to reproduce:

5. Additional information:

I usually try to play a Highlands map.  First successful game was a Continents trial run with no Advanced set-up, second and third were a Highlands game with Advanced set-up.  All failures were Highlands maps, but that might not mean anything.

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/244508/CvMiniDump.zip)

[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/244509/Database.zip)

[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/244511/Lua.zip)

**Comment by LoneGazebo** [comment]
@ilteroi , are we getting an edge-of-map null issue here?

**Comment by ilteroi** [comment]
could not reproduce, even with highlands map ... and no recent changes regarding map edges

**Comment by Liebfraumilch** [comment]
If there's any further information I can provide to help, please let me know.  

Today I've made it past usual crash point (~Turn 9 or 10) 3/5 times after clearing cache and validating through Steam.  Started trial run on advanced set-up Tiny Islands okay, did two more successful trials on advanced set-up Highlands after exiting to main menu (not closing out of Civ entirely).  

1/2 CTDs were after loading Autosave Turn 4 on a game I'd already reached Turn 10 on just to see if it would still succeed.  Alas, CTD on founding second city directly after selecting first policy.  

I've logged almost 3,700 hours of Civ V since 2010.  I really want this project to work for me! :)

**Comment by ilteroi** [comment]
the version you are using is quite old by now, can you retry with the latest beta?
