### ISSUE TITLE
Combat AI suggestion

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1709]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):4/23

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): AI improvement suggestion

4. Steps to reproduce:

5. Additional information:

hey Ilteroi, last game I was really impressed by combat AI - used focus fire very well. 
But I also noted one flaw: If a melee unit next to a 1HP city is severely wounded, it will withdraw rather than capture the city. 
Taking the city is under most circumstances better, even if it could be recaptured immediately. Capture at 1HP should be default mode.

Otherwise, again, I was impressed.

**Comment by ilteroi** [comment]
yeah it's tricky because the AI is not so flexible regarding the order of operations. healing currently has the highest priority to save units and to make room for the ones which can still fight.

but i'll see what i can do.
