### ISSUE TITLE
Barbarian camps don't spawn any barbarians 

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#171]
And some camps appear on the map empty.
Community Patch version 3-24

**Comment by phantommaxwell** [comment]
They eventually appear

http://cloud-4.steamusercontent.com/ugc/31863547494397119/C7B2309BE509ACB8086A5282871180124E9E3651/

http://cloud-4.steamusercontent.com/ugc/31863547494400975/132EF9D4CF955E0331EA68A775A8728058777D9E/
