### ISSUE TITLE
CTD upon attacking AI (related to GG CS quest??)

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#1711]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
4/23 with dll fix

2. Mod List (if using standard CPP set, leave blank):
I know...
(1) Community Patch\
(2) Community Balance Patch\
(3) CSD for CBP\
(4) Civ IV Diplomatic Features\
(5) More Luxuries\
(6a) Community Balance Patch - Compatibility Files (EUI)\
Calypso's Colored Religious Icons (Basic) (v 4)\
CivWillard for BNW (v 2)\
CPP CivPack (v 22)\
CPP TweakPack (v 36)\
CPP WondersPack (v 17)\
Cultural Capitals (Brave New World Edition) (v 16_5)\
FlagPromotionsv4\
Global - City Working Distance (v 7)\
Global - Civilians Move After Purchase (v 2)\
Global - Espionage Mapping (v 7)\
Global - Fortify Almost Healed (v 1)\
Global - Local Generals (v 2)\
Global - Pro-rata Buildings Purchase (v 2)\
InfoAddict (v 22)\
Ingame Editor (v 39)\
JFD's Cultural Diversity (Core) (v 7)\
JFD's Rise to Power - EUI Compatibility Files (v 22)\
JFD's Rise to Power (v 22)\
LiveTuner - Unit Panel (v 4)\
LiveTuner_-_Tech_and_Policy_Panels_(v_13)\
R.E.D. Modpack (v 27)\
Religion - Recurring Purchase Notify (v 1)\
TerrainMod (v 6)\
UI - Gold Alerts (v 10)\
UI - Overlay Barbarians (v 8)\
UI - Promotion Tree (v 15)\
UI - Summary Specialists (v 11)\
UI - Trade Opportunities (v 28)\
UI - Unit List Enhancements (v 11)\
Units - Visible Trade Units (v 1)\
Wonder Race (v 3)\

3. Type of error (i.e. crash, interface bug, AI quirk): 
CTD when I attack Aztechs. Happened twice when I attacked aztech units. It may be related to the Aztechs gaining a great General, thereby allying with a CS (had active quest..?)

4. Steps to reproduce:
I don't think yul will with the amount of mods activated, but simple attack the aztechs 1-2 times

5. Additional information:
Minidump files attached
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/245124/CvMiniDump.zip)
[CvMiniDump_v2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/245123/CvMiniDump_v2.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/245260/Logs.zip)

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by skodkim** [comment]
Just did a little test. 

If I give myself a number af ambassadors using the fire tuner and ally with the CS I get no CTD even though the AI still get the GG, so it seems to be related to the AI allying with them (thus declaring war on me) rather than them gaining the GG:

\Skodkim

**Comment by LoneGazebo** [comment]
@ilteroi , can you debug this? I can't debug anything on your latest (as my compiler doesn't match).

**Comment by skodkim** [comment]
Just tested with the original dll and now I don't see the CTD. Maybe it's related to the changes in the hotfix?

\Skodkim

**Comment by ilteroi** [comment]
hard to do anything here without a savegame
