### ISSUE TITLE
'Goddess of Renewal' not giving culture/faith for worked forest/jungle

### ISSUE THREAD

**Issue by crdvis16** [LoneGazebo/Community-Patch-DLL#1712]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
4/23 (not sure if b?)

2. Mod List (if using standard CPP set, leave blank):
CBP full set with EUI included

3. Type of error (i.e. crash, interface bug, AI quirk): 
pantheon not working

4. Steps to reproduce:
Choose 'Goddess of Renewal' Pantheon and see that your culture and faith do not increase even though you are working 2 jungle and 2 forest tiles in your capital.

5. Additional information:
I can't for the life of me see what I could possibly have be doing wrong when I chose this pantheon.  My capital has 2 jungle tiles (both of them Cocoa, in case that matters) and 2 forest tiles (plain forest, no lumber mills or anything else) but I did not get the extra culture/faith even though I have citizens assigned to those tiles.  I waited a turn and still wasn't getting the culture/faith the following turn.  I'm not sure what else can explain it other than a bug.

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
The bonus applies to 2 jungle or 2 forest – you had 2 jungle or 2 forest worked at same time?

G

**Comment by crdvis16** [comment]
Yep- actually had 2 jungle AND 2 forest, all 4 actively worked.
On May 2, 2016 9:00 PM, "LoneGazebo" <notifications@github.com> wrote:

The bonus applies to 2 jungle or 2 forest – you had 2 jungle or 2 forest
worked at same time?

G

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/LoneGazebo/Community-Patch-DLL/issues/1712#issuecomment-216408194>

**Comment by LoneGazebo** [comment]
Just a pantheon, or a full religion?

**Comment by crdvis16** [comment]
just pantheon, happened early in a game.  I believe at least one of the
jungle tiles was cocoa, if that matters.

**Comment by LoneGazebo** [comment]
Shouldn't matter. Any other mods, aside from CBP set?

**Comment by crdvis16** [comment]
I have a few installed but not actively using them (they are not checked in
the 'mods' loading screen).  Only active stuff is CBP+EUI set.

**Comment by LoneGazebo** [comment]
Mods in your mods folder, but not active, can still interfere with the CP. Try removing them all and see if that fixes it (may not fix an already-active game though).

**Comment by crdvis16** [comment]
Ah OK, will do.

**Comment by CharlesDR** [comment]
I've experienced this issue - it doesn't update the yield until you manually assign a citizen to work a forest/jungle tile. Sometimes you have to deselect a forest tile and then put the citizen back on it for the pantheon to calculate.

**Comment by crdvis16** [comment]
Oh weird- I definitely didn't try removing and then re-assigning so that
could explain it.

**Comment by LoneGazebo** [comment]
Try that, yes. It should recalculate when you found, but sometimes it does not.
