### ISSUE TITLE
B17, Zero and Guerilla can not be trained.

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1719]
I have required ideology and tech but can not train them.

**Comment by LoneGazebo** [comment]
Also the tenet for them?

G

**Comment by qqqbbb** [comment]
I did not know they require tenets. Maybe update their pedia description?

**Comment by LoneGazebo** [comment]
I think it says that they need tenets, does it not?

G

**Comment by qqqbbb** [comment]
It only says they require ideology.
