### ISSUE TITLE
Faith from Stonehenge doesn't scale with gamespeed

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1720]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

4/23

2. Mod List (if using standard CPP set, leave blank):

-

3. Type of error (i.e. crash, interface bug, AI quirk): 

See title

4. Steps to reproduce:

-

5. Additional information:

-

**Comment by TechpriestEnginseer** [comment]
Does it not say it grants you 30 faith? Don't see why it should scale with gamespeed considering Gazebo said it was intentional.
