### ISSUE TITLE
(Promotion) Ironsides texture not loading

### ISSUE THREAD

**Issue by jah** [LoneGazebo/Community-Patch-DLL#1723]
1. Mod Version (i.e Date - (4/23b)):
Beta april 23rd (4/23b)

2. Mod List (if using standard CPP set, leave blank):
R.E.D. Modpack (v. 27)
Thal's FlagPromotions (v. 1)

3. Type of error (i.e. crash, interface bug, AI quirk): 
Interface bug: texture not loading for Ironsides promotion.

4. Steps to reproduce:
Search Ironsides on civpedia, probably also when a naval unit would receive this from Imperialism finisher.

5. Additional information:
Error message: "Unable to load texture [expansion2-256.dds]". No crash involved.

**Comment by alexb5dh** [comment]
Thal's FlagPromotions (v. 1) has some issues with textures.
[Here's the latest fixed version](http://forums.civfanatics.com/showpost.php?p=14197087&postcount=92).

**Comment by LoneGazebo** [comment]
Thanks, @alexb5dh. I'll mark as solved.
