### ISSUE TITLE
Skirmisher civpedia

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1725]
Skirmisher civpedia calls the unit 'Mounted Bowmen' and talks up the movement even tho its the same as every other horse unit, that's kinda subjective tho since it is a hit n run unit after all.

(Even more subjectively Spearmen don't really 'specialize' in mounted units, they specialize in being spammable if anything)

Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 

4. Steps to reproduce:

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
I'll fix bowman text, but spearman thing is valid (anti-mounted promotion).
