### ISSUE TITLE
cdt each turn (since turn 341)

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#1726]
1. Mod Version: 4/23b

2. mods: full cpp only, with eui

3. what?: 3 cdt in a row.

4. how to reproduce: load a save, do some actions with units (pillage, shoot, move) and a cdt can occur (75% chance per turn). If i change the order of my actions, the cdt can be avoided.

5. Additional information: minidump, logs and saves in this zip:
https://drive.google.com/file/d/0B0hygFT4YYf7VTNvU3cyNWJPb1U/view?usp=sharing

**Comment by LoneGazebo** [comment]
Using hotfix dll, or 4/23 dll? @ilteroi  if hotfix.

**Comment by supermerill** [comment]
After checking this pc, i can see it's the 4/10 version of the dll...  
Seems i didn't updated this pc. Sorry.
