### ISSUE TITLE
Cannot Close Corporation Screen after Loading Game with Founded Corporation

### ISSUE THREAD

**Issue by IllusVirus** [LoneGazebo/Community-Patch-DLL#1727]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

2. Mod List (if using standard CPP set, leave blank):
Quick Turns

3. Type of error (i.e. crash, interface bug, AI quirk): 
Interface Bug where the corporations screen cannot be closed on loading a game with a founded corporation.

4. Steps to reproduce:

5. Additional information:
Founded the LandSea Extractors corp.

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

[Lua.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/249753/Lua.txt)
[Corporations.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/249754/Corporations.txt)

----------------------------

**Comment by mwhiter** [comment]
i will try to reproduce later this week / this weekend.

Otherwise I'm not sure what's causing that, as your definitions look good.

**Comment by IllusVirus** [comment]
Thank you.

**Comment by mwhiter** [comment]
That's because that's what the default XML looks like. There is another lua issue - that's why I asked for your definition because I wanted to see if anything looked suspicious. 

I forgot to also ask for the Database.log and xml.log. :)

**Comment by IllusVirus** [comment]
Sorry, I was wondering whether the Database.log was also necessary. Here you go

[XML.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/249865/XML.txt)
[Database.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/249866/Database.txt)

**Comment by mwhiter** [comment]
Okay I don't see any issue with those logs. So nothing immediately obvious jumps out to me. I'll have to reproduce locally to figure out the problem. 

On another, unrelated  note - i do notice  a lot of missing CSD units in your xml.log. @LoneGazebo, I'm not familiar with CSD -  are those errors in his xml.log normal?

**Comment by LoneGazebo** [comment]
Yes, it is normal.

**Comment by mwhiter** [comment]
Repro confirmed.

**Comment by mwhiter** [comment]
@IllusVirus it appears LandSea Extractors is incorrectly defined in the XML. Please locate the following two entries in your Corporations.xml for an immediate fix:

BUILDING_LANDSEA_EXTRACTORS
BUILDING_LANDSEA_EXTRACTORS_FRANCHISE

and change the following tag from:

```
<CorporationID>1</CorporationID>
```

to

```
<CorporationID>7</CorporationID>
```

**Comment by mwhiter** [comment]
Next time when I look at .xml's, I should be more careful. :)

**Comment by IllusVirus** [comment]
ty very much!
