### ISSUE TITLE
[Question] What is the stance on using the LuaJIT dll available from CivFanatics?

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#1728]
Just read a couple of comments about this in the forum and would like to know the "official" stance on this.
I've used LuaJIT for many years and it has been in my installation all this time. Is it possible that it may be contributing to CTDs and other instabilities in my game due to CPP's further enhancements.

My initial thought is no since CTDs are not usually (never) due to Lua issues.

**Comment by LoneGazebo** [comment]
I do not use it, and I experience no crashes in the DLL. To be honest, unless you are heavily using LUA, it won't make that big of a gameplay difference. @ilteroi ran some tests with it last year, but I'm not sure how those tests would fare now that we've done some bigger optimizations to the DLL.

**Comment by GrantSP** [comment]
Thank you.
