### ISSUE TITLE
CTD when other Civs initiate diplomacy

### ISSUE THREAD

**Issue by Cosamaru** [LoneGazebo/Community-Patch-DLL#1730]
Bug Report Template

1. Mod Version:

Version 1.3.9b, downloaded 4/30

2. Mod List:

3. Type of error: 

CTD when another Civ initiates diplomacy.

4. Steps to reproduce:

When I reload, the diplomacy opens fine, but it will crash again the next time someone contacts me for a different issue. Reload, works again, so I can't reproduce any single CTD. I can tell because it crashes on different Civs turns', then the crash causing Civ will contact me on reload. It's happened at least 3 times with Ottomans, twice with Aztecs and Danish, and once with Inca.

5. Additional information:
The minidump is from (it looks like) Denmark crashing the game on their turn. The save is the turn prior.
[CivV Bug Report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/250028/CivV.Bug.Report.zip)

**Comment by LoneGazebo** [comment]
Are you using the hotfix DLL posted on civfanatics, or just the 4/23 version DLL?

**Comment by Cosamaru** [comment]
No I wasn't.

Although now I've realized I was being an idiot and selecting the "recommended" Windows 8 version when my machine is windows 10. I selected the DirectX 10/11 startup, and I'm not encountering the issue anymore, so my issue has been resolved. Thank you for your attention.
