### ISSUE TITLE
City Connection over Ocean with Harbor busted in my game

### ISSUE THREAD

**Issue by sammyg11** [LoneGazebo/Community-Patch-DLL#1731]
Bug Report Template

1. Mod Version : 4/23b

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 

interface bug

4. Steps to reproduce:

I had cities on two different continents, but they weren't making a city connection to my capitol despite having Harbors. The problem was with roads. If the city was isolated (no roads to other cities) it would connect over the Ocean with a harbor to my capitol, but the moment I connected that harbor city to an additional city via road the city connection would go away. I tested this by destroying roads to see if my city connection would come back and it did. Re-making the road the connection disappeared again.

5. Additional information:

I was playing as Indonesia on Emperor.

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
@ilteroi , is there an issue with the cached city connections here?

**Comment by ilteroi** [comment]
do you have a savegame?

**Comment by sammyg11** [comment]
I do! Download it here : 

https://drive.google.com/file/d/0B68MTk4TTHl-U1hEc1RyREFUZG8/view?usp=sharing

What you should look at are the cities across the sea from Jakarta. You'll see that the ones that are connected have the road next to their cities destroyed so they're not "connected" to the other cities on that continent. 

Hope that's helpful.

**Comment by ilteroi** [comment]
cannot load it - crashes with 4/23 as well as with the 4/29 hotfix version (although those two both have the same save format). are you sure about the version?

**Comment by sammyg11** [comment]
Yeah I definitely have the 4/23 beta version installed with the 4/29 hotfix.

**Comment by ilteroi** [comment]
seems the issue is on my end then, i happened also with another savegame. that's annoying.

**Comment by ilteroi** [comment]
ok, finally rewrote the whole city connection thing. it had been bothering me for quite a while anyway.

still testing but looking good so far. pushing now

**Comment by LoneGazebo** [comment]
Sounds good.
