### ISSUE TITLE
CTD during war

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1732]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
4/23

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 

During my turn, game crashes. 

4. Steps to reproduce:

5. Additional information:

Added lua.log, minidump and savegame.
[Crash Report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/250071/Crash.Report.zip)

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
hotfix dll or 4/23 dll?

**Comment by Der-Zorn-Gottes** [comment]
4/23 dll. 
Installing hotfix solved the issue. I figured from the description that the hotfix only concerns AI behaviour, or I would have instaled it before reporting.
