### ISSUE TITLE
Trade deals stuck in limbo

### ISSUE THREAD

**Issue by nOxrax** [LoneGazebo/Community-Patch-DLL#1733]
1. Mod Version
4/23b beta with dll hotfix

2. Mod List
CP
Custom Advanced Setup Screen (+ playing hotseat)

3. Type of error
Deal logic bug

4. Steps to reproduce:
Since it is a hotseat game, I'm not sure you can reproduce it, and I'm not sure how useful a save file is. But you might recognise what is wrong from a description and screenshot:
(a). Some trade deals between civs get stuck in a limbo state where they never expire. It happens seemingly randomly, and not for all deals but perhaps one in five. 
(b). I'm not sure exactly when the deals get stuck. It is not immediately. It could be when they are supposed to expire, but i'm not sure.
(c). These stuck deals disappear from the 'current deals' list and instead appear on the 'completed deals' list with the info that they started on 'turn -1' and lasted for '-1 turns' and finished on 'turn -2', also all specific info about the deal is gone.
(d). The deals continue to be in effect though, so if you have traded two luxuries you keep their luxury and they have yours.

5. Additional information:
(a). We have played hotseat (2 players) with CP for the last six months, and we saw this specific problem first in 3/23 beta. I can confirm that it still is a problem in 4/23b. Nothing else in our setup has changed so the problem ought to be related to CP.
(b). The bug is quite salient and yet no one else seems to have reported it, which makes me think it could be a problem specific for Hotseat games.

![civ5screen0010](https://cloud.githubusercontent.com/assets/19200822/15038941/c66053ba-12a8-11e6-8675-508bf62e885f.jpg)

**Comment by LoneGazebo** [comment]
@ilteroi @Iamblichos , could this be a means of testing the deal issue related to missing resources?

**Comment by Iamblichos** [comment]
You mean playing a hotseat game?

**Comment by LoneGazebo** [comment]
Yes.

**Comment by pandasnail** [comment]
One thing I've been observing is that it doesn't happen if the gold-payer is in the negative GPT when the deal is scheduled to end, ie if the deal can't be redone. Haven't seen this quite enough times to be 100% sure its a fact, but I think so, so I thought I'd post it now that there's a new thread about it.

**Comment by magner58** [comment]
Hay all, can confirm the bug for v. 4/23 (core only) + hotfix dll, see screenshot:

![civ5screen0000](https://cloud.githubusercontent.com/assets/13498110/15197959/b7dd2102-17d4-11e6-86ed-59b5684b77d6.jpg)

@nOxrax @LoneGazebo @Iamblichos I am playing single, so it's not only for hotseat.

P.S. Are there any workarounds by the way to force end those deals?

**Comment by Iamblichos** [comment]
I wonder if we should go back and do a diff and compare the TradeLogic.lua from before this bug cropped up.

**Comment by LoneGazebo** [comment]
I don't think it is a lua issue. I'm making some changes that may or may not help, we'll see.

**Comment by magner58** [comment]
@Iamblichos but as I said - I removed TradeLogic.lua in CPP folder, as it is already there in EUI.

**Comment by pandasnail** [comment]
In my first game with the 5/14, 100% of my trade deals went through right! It is only one game, and most were later in the game, which has always worked better I think, but, I mean, things working in the first game after you made changes to the trade system is hopefully not coincidental. I actually still get the LUA error about a nil value in the Trade Logic lua, but it doesn't seem to be affecting things anymore.

**Comment by LoneGazebo** [comment]
That's good. I think I found the culprit in the diplo AI - some changes to AI renewal logic that weren't ending deals as expected. So that's the fix you're seeing.

**Comment by Edaka** [comment]
Since it seems that the bug's been (possibly) fixed, I'll close until further notice.

**Comment by magner58** [comment]
@Edaka sorry, but I don't think that I follow - where the bug was fixed, in the next upcoming hotfix?

P.S. I also got comments from pandasnail per email notification, but don't see them here - do you know why?

**Comment by pandasnail** [comment]
Apparently I had been uploading too many screenshots or making too many reports in a short span or just checking the site a bit too much looking for something to do during AI turns, but some automated system decided I might be a spam robot, hence my posts vanishing for a bit. Oops. Anyway, the post you're missing is that I had no issues with trade deals in the 5/14 and now the 5/21 as well. Which is noteworthy because I had this bug as much as anyone during its lifespan. So it should be gone for you as well.
