### ISSUE TITLE
Colosseum civpedia

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1734]
Colosseum civpedia mentions only Great General points, leaving out Great Admirals

Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 

4. Steps to reproduce:

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
I see the mention.

**Comment by pandasnail** [comment]
I checked just now and yeah, I see that's in the XML, but at least in the EUI version everything in the parenthesis doesn't show up for me. I did doublecheck

ie  (+3 [ICON_GREAT_ADMIRAL] Great Admiral points if a Naval Unit)

**Comment by LoneGazebo** [comment]
Oh yep, duh, compatibility files. Fixed.
