### ISSUE TITLE
Hero of the People not producing great engineer

### ISSUE THREAD

**Issue by wiseguy107** [LoneGazebo/Community-Patch-DLL#1739]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

MP_Modspack_3-9_EUI
       

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 

4. Steps to reproduce:

5. Additional information:
Not sure how to get any of this other information, I will update if I can find the mod version.

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by wiseguy107** [comment]
I am using the modpack downloaded here: http://forums.civfanatics.com/showthread.php?t=553187
Not even really using it a mod.  Please tell me how to provide other useful information.

**Comment by LoneGazebo** [comment]
I can't debug the modpack, sorry.
