### ISSUE TITLE
Impi's free ranged attack

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#174]
PROMOTION_ANTI_GUNPOWDER does not work. It always deals 1 damage.

**Comment by LoneGazebo** [comment]
Should be fixed in 4/1 version.
G

**Comment by qqqbbb** [comment]
The bug is still in version 4/2.

**Comment by LoneGazebo** [comment]
Dang. Should be fixed. I'll message ilteroi as well. 
G

**Comment by ilteroi** [comment]
fixed and pushed. problem in the AUI port.

it's not considered for the combat preview though, but that was never the case as far as i can tell.
