### ISSUE TITLE
Have you made any changes to Corporations or World Congress Wonders in the last month or two?

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1742]
Its a lot harder to look at the EUI tooltip, which I much prefer using, for those; so I thought I'd just straight ahead ask you if you can remember making any changes

Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 

4. Steps to reproduce:

5. Additional information:

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by mwhiter** [comment]
I mean, for Corporations, I added the whole Corporations Overview, so that's a change....

**Comment by pandasnail** [comment]
I meant for the purposes of updating the wikia. The yields and such. Sorry for the confusion! 

(I quite like the overview btw, thanks for it)

**Comment by mwhiter** [comment]
:) glad it helps

**Comment by LoneGazebo** [comment]
No, they're the same.
