### ISSUE TITLE
Towns not connecting underlying resource

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#1743]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
4/23b with DLL hotfix

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 
Town created by Great Merchant is not connecting the resource (2x Iron) on the tile it is constructed on.

4. Steps to reproduce:
Generate a GM and use it to create a "Town" improvement on a resource tile.

5. Additional information:
The only UI element that correctly updates to show the resource is connected is the new "Corporations and Monopolies" panel. The TopPanel and Economic Overview both show totals without this new connection.
It isn't an update delay as even after several turns and even a save/reload results are the same.

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
cant' reproduce, sorry.
