### ISSUE TITLE
Beta bundled trade notifications closing other trades.

### ISSUE THREAD

**Issue by Mikkles** [LoneGazebo/Community-Patch-DLL#1744]
1. Mod Version (i.e Date - (4/23b)): 
MP_MODSPACK_4-23_EUI_beta (http://forums.civfanatics.com/showpost.php?p=14248307&postcount=790)
Playing Single Player.
No other mods.

3. Type of error (i.e. crash, interface bug, AI quirk): 
Interface bug.
When more than one AI civ tries to initiate a trade with you, their notifications are bundled (eg, 1/2: Japanese Empire...). Accepting one trade removes any others. 

This causes the player to be unable to answer two (or possibly more) civ trades.

4. Steps to reproduce:
Being in a situation where more than one AI wants to trade with you.
I've attached a save (AutoSave_0160) that begins in this situation.

5. Additional information:
My specific situation was during a single player game using the MP_MODSPACK_4-23_EUI_beta. Hiawatha wanted to negotiate me opening borders by sending 2gpt, and Nobunaga wanting to trade open borders. Clicking the notification (which read Hiawatha) opened Nobunaga's request in his leader screen. Clicking Accept returned to the map, and the full notification button had disappeared. Right clicking removed both. Refusing/ESC-keying the trade closed the leader screen like normal, and removed their entry in the notification bundle, allowing me to see the next trade. 
I tried going to Mods\(6a) Community Balance Patch - Compatibility Files (EUI) (v 1)\LUA\NotificationPanel.lua
and changing line 197 NOTIFICATION_PLAYER_DEAL_RECEIVED and removed "B" from the line. Reloading that turn, this stopped the bundling and gave two separate notifications, but accepting one trade removes the other notification as well. Opening one trade and refusing it allowed me to click and open the second trade.
If you refuse/escape the first trade, even with the notification gone, you can click on the second civ's face in the leader ribbon and it will open the trade screen as if you had clicked the notification. If you had right-clicked the notification to remove both, you can click on either civ's face to open the trade; however, accepting (not refusing/escaping) the trade stops this function from the other civ.
In vanilla, the trade requests opened on the respective AI Civ's turn; perhaps changing this to occur on the player's turn has messed something up? Like the post-accepted-trade dialog ("I find this acceptable") is supposed to close trade windows on that turn only, and thus since both trades are on the player's turn, it closes both. But I'm not a programmer.
I haven't had an opportunity to see what happens in the case of there being more than 2 trades active, or what happens if there are other types of AI Civ notifications besides trades, like denouncements or we-both-like-india-lets-be-bros.
I've included my net_message_debug.log because it also says 
[257346.296] Net SEND (0): size=177: NetDealAccepted(FromPlayer=0, ToPlayer=7)
[257346.296] Net RECV (0) :NetDealAccepted(FromPlayer=0, ToPlayer=7)
and I have no idea what that means but it seems relevant. 
[BundleBug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/251585/BundleBug.zip)

**Comment by LynnesCFC** [comment]
Can we add Jaii der Herr to this topic? I don't know his name on github!

**Comment by LynnesCFC** [comment]
@J-d-H

**Comment by Mikkles** [comment]
Bug #1745 may be related to this cause as well.

**Comment by J-d-H** [comment]
Is there any chance that accepting the first deal makes accepting the second impossible?
If not: I'll try to look into it as soon as possible (most likely in June)

**Comment by LynnesCFC** [comment]
There were also some posts about this in the modspack-thread, maybe including some additional information:

http://forums.civfanatics.com/showpost.php?p=14257913&postcount=809

**Comment by Mikkles** [comment]
> Is there any chance that accepting the first deal makes accepting the second impossible?
If not: I'll try to look into it as soon as possible (most likely in June)

I don't think so. In this situation, Hiawatha and Nobunaga were just trading OBs, and I don't think they hated each other enough to refuse OB with someone else. Also, with reloading, I tried accepting each one first, and both times it closed all the trades. What I haven't tested was refusing the deals and manually recreate them. (However, I know in the past, when I've accidentally refused a good deal, they won't necessarily accept if I recreate it, even on the same turn.) I'll test this out next time it occurs.

**Comment by LoneGazebo** [comment]
@J-d-H it sounds like, to me, that a 'cleardeals' or 'cancel all deals with player' function is being called during or after the finalizedeal step.
