### ISSUE TITLE
Crash on mouse over of unexposed city.

### ISSUE THREAD

**Issue by biship** [LoneGazebo/Community-Patch-DLL#1746]
Bug Report Template

**1. Mod Version (i.e Date - (4/23b)):**
4/30 fefe branch, compiled with VS2015 (no code changes, solution left as vs2010 format).

**2. Mod List (if using standard CPP set, leave blank):**

> 05/06/2016  07:28 PM    <DIR>          (1) Community Patch (v 79)
> 05/01/2016  11:22 AM    <DIR>          (2) Community Balance Patch (v 13)
> 05/01/2016  11:22 AM    <DIR>          (3) CSD for CBP
> 05/01/2016  11:22 AM    <DIR>          (4) Civ IV Diplomatic Features (v 11)
> 05/01/2016  11:22 AM    <DIR>          (5) More Luxuries
> 05/01/2016  11:22 AM    <DIR>          (6a) Community Balance Patch - Compatibility Files (EUI) (v 1)
> 04/26/2016  04:55 PM    <DIR>          (7) Events and Decisions (CBP) (v 8)
> 03/29/2016  06:43 AM    <DIR>          (BNW) Leugi's Barbarian Inmersion Enhancements (v 1)
> 04/24/2016  02:08 PM    <DIR>          AI - Great People Choices (v 1)
> 03/25/2016  06:56 AM    <DIR>          Buildings - Goldsmith (v 4)
> 04/24/2016  02:08 PM    <DIR>          Buildings - Lighthouse Near Sea (v 2)
> 03/25/2016  06:56 AM    <DIR>          Buildings - Textile Mill (v 4)
> 04/30/2016  06:24 AM    <DIR>          Calypso's Colored Religious Icons (Basic) (v 4)
> 04/30/2016  06:24 AM    <DIR>          Calypso's Colored Religious Icons (BNW Extended) (v 3)
> 04/30/2016  06:24 AM    <DIR>          Calypso's Colored Religious Icons (Extended) (v 5)
> 04/06/2016  10:43 AM    <DIR>          Civilization Selection Bonus Tooltips (v 3)
> 03/15/2016  06:21 PM    <DIR>          Diplomacy - Auto-Denounce (v 1)
> 04/07/2016  06:18 AM    <DIR>          Diplomacy - By Numbers (v 1)
> 03/15/2016  06:21 PM    <DIR>          Diplomacy - Tech Bonuses (v 1)
> 03/19/2016  04:12 PM    <DIR>          FlagPromotions (v 7)
> 04/26/2016  04:55 PM    <DIR>          Future Worlds (v 4)
> 03/25/2016  06:56 AM    <DIR>          Global - Air Routes (v 1)
> 03/15/2016  06:21 PM    <DIR>          Global - City Jungle Bonus (v 1)
> 03/15/2016  06:21 PM    <DIR>          Global - Civilians Move After Purchase (v 2)
> 03/15/2016  06:21 PM    <DIR>          Global - Commander Influence Borders (v 1)
> 04/07/2016  06:18 AM    <DIR>          Global - Enable Magellan (v 10)
> 03/15/2016  06:21 PM    <DIR>          Global - Espionage Reports (v 2)
> 03/15/2016  06:21 PM    <DIR>          Global - Fortify Almost Healed (v 1)
> 03/06/2016  04:01 PM    <DIR>          Global - GA Happiness (v 1)
> 03/15/2016  06:21 PM    <DIR>          Global - Jungle Production (v 1)
> 03/15/2016  06:21 PM    <DIR>          Global - Local Generals (v 2)
> 03/15/2016  06:21 PM    <DIR>          Global - National Wonders  Exclude Razing (v 1)
> 03/15/2016  06:21 PM    <DIR>          Global - Pro-rata Buildings Purchase (v 2)
> 03/15/2016  06:21 PM    <DIR>          Global - Raze Major Capitals (v 1)
> 03/15/2016  06:21 PM    <DIR>          Global - Religious Settlers (v 1)
> 03/15/2016  06:21 PM    <DIR>          Goody Huts - No Auto-Mapping (v 2)
> 03/15/2016  06:21 PM    <DIR>          Goody Huts - Tech Refund (v 7)
> 03/25/2016  06:56 AM    <DIR>          Improvement - Farm Replacement (v 1)
> 04/04/2016  08:13 PM    <DIR>          InfoAddict (v 22)
> 04/30/2016  06:24 AM    <DIR>          Quick Turns (v 10)
> 04/30/2016  06:24 AM    <DIR>          Really Advanced Setup (v 15)
> 03/15/2016  06:21 PM    <DIR>          Religion - Bonus Beliefs (v 1)
> 03/15/2016  06:21 PM    <DIR>          Religion - Recurring Purchase Notify (v 1)
> 03/15/2016  06:21 PM    <DIR>          Show Move-To (v 2)
> 04/07/2016  06:18 AM    <DIR>          Tech - Satellites Reveal Cities (v 10)
> 03/15/2016  06:22 PM    <DIR>          UI - City Happiness (v 17)
> 03/15/2016  06:21 PM    <DIR>          UI - City Religions (v 4)
> 03/15/2016  06:21 PM    <DIR>          UI - Enhanced Demographics (v 6)
> 03/15/2016  06:21 PM    <DIR>          UI - Enhanced Rankings (v 13)
> 03/15/2016  06:21 PM    <DIR>          UI - Great Work Manager (v 14)
> 03/15/2016  06:21 PM    <DIR>          UI - National Wonder Splash Screens (v 10)
> 03/15/2016  06:21 PM    <DIR>          UI - Overlay Barbarians (v 8)
> 03/15/2016  06:21 PM    <DIR>          UI - Overlay City Limits (v 8)
> 03/15/2016  06:21 PM    <DIR>          UI - Overlay Continents (v 8)
> 03/15/2016  06:21 PM    <DIR>          UI - Overlay Harbours And Airports (v 1)
> 03/15/2016  06:21 PM    <DIR>          UI - Overlay Luxuries (v 3)
> 03/15/2016  06:21 PM    <DIR>          UI - Overlay Resources (v 11)
> 03/15/2016  06:21 PM    <DIR>          UI - Overlay Road And Rail (v 9)
> 04/26/2016  04:52 PM    <DIR>          UI - Overlay Unimproved Tiles (v 1)
> 03/15/2016  06:21 PM    <DIR>          UI - Overlay Wonders (v 7)
> 03/15/2016  06:21 PM    <DIR>          UI - Project Splash Screens (v 8)
> 04/07/2016  06:18 AM    <DIR>          UI - Promotion Tree (v 15)
> 03/15/2016  06:21 PM    <DIR>          UI - Religion Spread (v 13)
> 03/15/2016  06:21 PM    <DIR>          UI - Summary Antiquities (v 2)
> 03/15/2016  06:21 PM    <DIR>          UI - Summary Barbarians (v 9)
> 03/15/2016  06:21 PM    <DIR>          UI - Summary City States (v 12)
> 03/15/2016  06:21 PM    <DIR>          UI - Summary Clock (v 11)
> 03/15/2016  06:21 PM    <DIR>          UI - Summary Luxuries (v 13)
> 03/25/2016  06:56 AM    <DIR>          UI - Summary Shipping (v 11)
> 03/15/2016  06:21 PM    <DIR>          UI - Summary Specialists (v 11)
> 03/15/2016  06:21 PM    <DIR>          UI - Trade Opportunities (v 28)
> 03/24/2016  03:32 PM    <DIR>          UI - Unit List Enhancements (v 11)
> 03/25/2016  06:56 AM    <DIR>          UI - Upgrade Tree (v 8)
> 03/15/2016  06:21 PM    <DIR>          UI - Wonder Planner (v 14)
> 03/25/2016  06:56 AM    <DIR>          Units - Rangers (v 11)
> 03/27/2016  10:02 AM    <DIR>          Units - Sound Corrections (v 1)
> 03/25/2016  06:56 AM    <DIR>          Units - Subs Ignore Borders (v 3)
> 04/07/2016  06:18 AM    <DIR>          Units - Super Carrier (v 11)
> 05/01/2016  11:22 AM    <DIR>          znicks overrides (v 1) (just sql changing difficulty tables)

**3. Type of error (i.e. crash, interface bug, AI quirk): **
Crash: 0xC0000005

**4. Steps to reproduce:**
Load up save game, mouse over the _city tile_ of Salamanca. Then crash.
If you move a unit closer to the city, exposing one row of tiles below the city, then the crash no longer occurs. (EDIT: hmmm the crash can still occur (for the same city), but doesn't look like always)
Does not occur on city banner.
Doesn't seem to occur for any other city.

[debug.dll.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/253185/debug.dll.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/253186/Logs.zip)
[AutoSave_0357 AD-1937.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/253187/AutoSave_0357.AD-1937.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/253188/CvMiniDump.zip)

**5. Additional information:**
In VS2015 debugger when attached to civ5 dx11 process:
debug output window:
```
Exception thrown: read access violation.
this was nullptr.
```

Call Stack:
`CvGameCore_Expansion2.dll!CvPlayer::GetGreatPersonExpendGold() Line 23959	C++
 	CvGameCore_Expansion2.dll!CvUnit::GetMaxHitPoints() Line 14648	C++
 	CvGameCore_Expansion2.dll!CvLuaUnit::lGetCombatDamage(lua_State * L) Line 912`

Debugger says its unable to _read memory_ for m_iGreatPersonExpendGold.

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by biship** [comment]
whoward69's 2 cents:

> Don't forget that an errant pointer won't show up until the code attempts to read something from it (in this case m_iGreatPersonExpendGold), so it's not that the contents of m_iGreatPersonExpendGold that is incorrect but the pointer that is being dereferenced by the attempt to obtain a value for m_iGreatPersonExpendGold.
> 
> The only pointer in that code is pGarrison. The HasGarrison() method is new and the GetGarrisonedUnit() method has been totally rewritten (although you can't tell this just by looking at CvCity.h as #if/#else/#endif blocking has been dumped). Also, from a quick scan of the code, it is possible that HasGarrison() could return true while the unit it thinks is the garrison has been killed, hence causing GetGarrisonedUnit() to return null.

**Comment by ilteroi** [comment]
thanks for the detailed analysis, i've been investigating the same issue, should be fixed.

**Comment by biship** [comment]
Thanks ilteroi. I'll check once you next push to github.
I look forward to see what code was changed to better my understanding of C++.
