### ISSUE TITLE
Extra Yields from events not shown in City screen

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#1749]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
4-23 with dll fix

2. Mod List (if using standard CPP set, leave blank):
The usual loooong list, but shouldn't be related to this...
Using EUI

3. Type of error (i.e. crash, interface bug, AI quirk): 
Graphical

4. Steps to reproduce:

5. Additional information:
Extra Yields from events are not shown in the buildings section of the City screen, i.e. the +1 Culture for Monuments is shown in the total Yield output of the city but not on the yield output from the monument.

--------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by JFDaly** [comment]
This is more of an EUI issue than it is a CP/CBP issue. You should report to the EUI thread that it is missing checks for player:GetPlayerBuildingClassYieldChange(buildingClassID, yieldID).

**Comment by skodkim** [comment]
I'm using the cpp version of eui so this is a file gazebo modifies for his
needing.

\Skodkim
Den 08/05/2016 08.27 skrev "JFDaly" <notifications@github.com>:

**Comment by LoneGazebo** [comment]
Works for me. Sorry skodkim.
