### ISSUE TITLE
Ironclads Obsolete Too soon

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#175]
Ironclads Obsolete at Combustion so no Melee Ships can be built for quite some time

http://cloud-2.steamusercontent.com/ugc/31863547505232868/17A8C2DD19922468A074D7B2C730F47F6F02F2CF/

**Comment by LoneGazebo** [comment]
Ah that's an oversight. I'll fix in next version.
