### ISSUE TITLE
Pottery will not grant Caravan or additional Trade Route

### ISSUE THREAD

**Issue by ErikSteiner** [LoneGazebo/Community-Patch-DLL#1753]
## 1. Mod Version (i.e Date - (4/23b)):
Community Patch Project 4/23b

## 2. Mod List (if using standard CPP set, leave blank):
- (1) Community Patch
- (2) Community Balance Patch
- (3) CSD for CBP
- (4) Civ IV Diplomatic Features
- (6a) Community Balance Patch - Compatibility Files (EUI)
- Architecture changes (v 1)
- Calypso's Colored Religious Icons (Basic) (v 4)
- Custom Advanced Setup Screen (v 5)
- FlagPromotions (v 7)
- Global Relations (v 7)
- JFD's Exploration Continued Expanded (v 15)
- JFD's The Commonwealth of Iceland (v 2)
- JFD's The Confederation of Switzerland (v 5)
- JFD's The Kingdom of Belgium (v 1)
- JFD's The Kingdom of Hungary (v 8)
- JFD's The Kingdom of Norway (v 6)
- R.E.D. - Smaller Landmarks (v 5)
- R.E.D. Modpack (v 28)
- Randomize City Names (v 2)
- Terrain Texture Enhancement 2k (v 3)
- TerrainTextureMod (v 2)
- Yet (not) Another Earth Maps Pack (v 24)

## 3. Type of error (i.e. crash, interface bug, AI quirk): 
After researching Pottery you will get informed about some new features e.g. what you can build etc. There are some information about an additional Trade Route and the possibility to build the Caravan. Both features are not present after researching this technology.

## 4. Steps to reproduce:
Research Pottery or have a look into the Civilopedia

## 5. Additional information:
![20160507195020_1](https://cloud.githubusercontent.com/assets/2684018/15093806/7c801898-1492-11e6-8aa8-d122ce12c3fc.jpg)

**Comment by LoneGazebo** [comment]
Looks like you are playing in German – English text does not always update correctly if the game's native language is not English, as the mod structure doesn't have support for DE yet.

**Comment by ErikSteiner** [comment]
It is maybe confusing for you seeing German text in Civ, but I am currently translating the text to German, so here and there are already translated texts. I can reproduce this issue by just using the original CPP and playing in English.

**Comment by pandasnail** [comment]
This is just a civpedia thing, not a functionality thing. Caravan and first route are both on Trade now. You're right that even in the English version the civpedia is wrong, enough of them are that I'm planning to go through them eventually. For now, I'd recommend using the tooltip on the tech tree itself if you want to know all the unlocks for your translating project.

**Comment by ErikSteiner** [comment]
Yes you are right, of what I read there are some entries that need an overhault. So there is already one entry that will not be forgotten ^^

**Comment by LoneGazebo** [comment]
I'm reworking this to use the tooltip, no need to fix.
