### ISSUE TITLE
Fishing icon is missing

### ISSUE THREAD

**Issue by ErikSteiner** [LoneGazebo/Community-Patch-DLL#1754]
### 1. Mod Version (i.e Date - (4/23b)):
Community Patch Project 4/23b

### 2. Mod List (if using standard CPP set, leave blank):
- (1) Community Patch
- (2) Community Balance Patch
- (3) CSD for CBP
- (4) Civ IV Diplomatic Features
- (6a) Community Balance Patch - Compatibility Files (EUI)
- Architecture changes (v 1)
- Calypso's Colored Religious Icons (Basic) (v 4)
- Custom Advanced Setup Screen (v 5)
- FlagPromotions (v 7)
- Global Relations (v 7)
- JFD's Exploration Continued Expanded (v 15)
- JFD's The Commonwealth of Iceland (v 2)
- JFD's The Confederation of Switzerland (v 5)
- JFD's The Kingdom of Belgium (v 1)
- JFD's The Kingdom of Hungary (v 8)
- JFD's The Kingdom of Norway (v 6)
- R.E.D. - Smaller Landmarks (v 5)
- R.E.D. Modpack (v 28)
- Randomize City Names (v 2)
- Terrain Texture Enhancement 2k (v 3)
- TerrainTextureMod (v 2)
- Yet (not) Another Earth Maps Pack (v 24)

### 3. Type of error (i.e. crash, interface bug, AI quirk): 
If you open the little menu that will inform you about the progress of researching a technology you will not have an icon for fishing, if you research this technology. However, in the tech tree the icon is visible. I have this issue for many month now in different version of CPP.

### 4. Steps to reproduce:
Research fishing.

### 5. Additional information:
![20160507195129_1](https://cloud.githubusercontent.com/assets/2684018/15093833/3345f52a-1493-11e6-87c2-a51acae0524c.jpg)

**Comment by ErikSteiner** [comment]
Do not wonder about seeing German Text here, this is the current state of translating the modules of CPP to German, so Fishing is already translated to the German word.

**Comment by LoneGazebo** [comment]
This happens with certain interface resolutions.

**Comment by LoneGazebo** [comment]
I'll see if I can fix in next version.
