### ISSUE TITLE
Major AI abuse when trading

### ISSUE THREAD

**Issue by GuntherSpell** [LoneGazebo/Community-Patch-DLL#1755]
Hey,

I found a huge abuse of the AI when it wants to trade with you. Basically, I managed to have 3 voluntary vassals and a few techs for free with this trick: when the AI wants to renew an old trade or, e.g., wants one of my luxuries/strategic resources, I just click on "vassal state" or any tech I want, I hit the "propose" button and the AI gladly accepts!

1. Mod Version : April 23rd - (4/23)

2. Mod List : standard CPP

3. Type of error: AI quirk

4. Steps to reproduce:
Enable vassalage and disable tech brokering
Wait for the AI to want to trade with you (especially shared open borders or renewing an old trade)
Add "Vassal state" or any technology they have to offer (should work with declare war)
Do NOT hit the "what would make this trade work?" button
Hit the "Propose" button
The AI should happily accept.

5. Additional information:
It worked for me with standard and quick speed on King difficulty. It's not linked to my military strength and, you may check with the attached save, I even managed to have the lead AI as my voluntary vassal just by sharing open borders (check the trade history).

Even though this is obviously an abuse you don't want to use because it breaks the game, I found it very disturbing. An important note: it seems that the AI is completly ignoring the value of what they give as Ausrtia even said "Really? Absolutely!" when she became my voluntary vassal for a few coals.

On a side note, it worked with the most recent stable version as well (1.3.9)
[AI vassal abuse.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/253585/AI.vassal.abuse.zip)

**Comment by mwhiter** [comment]
I'll look into it
