### ISSUE TITLE
Byzantium not able to found religion

### ISSUE THREAD

**Issue by DeclareGlory** [LoneGazebo/Community-Patch-DLL#1756]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
download date was 2016/03/25

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 
Byzantium not able to found religion, after annexing a holy city.

4. Steps to reproduce:
Annex a Holy city directly after conquering it.
Great prophet generated a couple turns later in 1st expand still following pantheon. 
Can only plant new prophet for tile enhancement.

5. Additional information:
I could not found religion in my capital or in the enemy capital/holy city. Religion screen showed i had founded same religion as conquered holy city with the same founder and 1st follower belief, but not their enhancements, and I could not enhance my new bugged religion.

If it matters I was going down Authority policies, fighting Korea.

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by l0rdbyte** [comment]
It's consistent, I have a save with the latest CPP installed as DLC, full install, no other mods:
[Alexander Great Prophet Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/256162/Alexander.Great.Prophet.Bug.zip)

A great Prophet just spawned, right religion, in the Holy City and I cannot use it to enhance my religion (well.... the religion I stole, and I'm the head of... Create religion appears but it doesn't allow me to do anything).

**Comment by LoneGazebo** [comment]
This happens with the modpack. I don't know why. Please inform Lynnes (the modpack maker) as I don't technically support, and cannot debug, the DLC version of the CPP.

**Comment by l0rdbyte** [comment]
What I meant is that I installed it for multiplayer, not as a mod, not as a modpack.

**Comment by LynnesCFC** [comment]
Hm, so the OP was also using a modpack?
Could someone please try it with the CPP-mods (no modpack) as well, so we can ensure if it's modpack-related or not?

**Comment by LoneGazebo** [comment]
This error only crops up with modpack users. I guarantee there's a lua error in his lua log related to the religionoverview.lua, but I don't know why.

**Comment by LynnesCFC** [comment]
Can someone who encountered this bug please post a lua.log?

**Comment by l0rdbyte** [comment]
I am trying with the normal mod but I keep accidentally getting a religion :(

**Comment by l0rdbyte** [comment]
I got it with the normal CPP packages. Savegame to prove it, it's consistently reproducible.
The moment you click on "Enhance religion" with the great Prophet it will go to the religion select screen, and whether there are still slots available or not (reproduced with no slots available, but I know it also happens when there's still slots available but you just took a Holy city), you cannot do anything. Cannot enhance the religion (or create a new one for that matter).
[Great Prophet Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/275276/Great.Prophet.Bug.zip)

**Comment by LynnesCFC** [comment]
Thanks for testing! :)

**Comment by LoneGazebo** [comment]
I need your lua log, @l0rdbyte.

**Comment by l0rdbyte** [comment]
Here you go
[Lua.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/275372/Lua.txt)
