### ISSUE TITLE
Reproducible CTD with save file and dump/logs

### ISSUE THREAD

**Issue by crdvis16** [LoneGazebo/Community-Patch-DLL#1757]
1. Mod Version (i.e Date - (4/23b)):
**4/23**

2. Mod List (if using standard CPP set, leave blank):
**Full CBP with EUI, NO other mods anymore**

3. Type of error (i.e. crash, interface bug, AI quirk): 
**CTD**

4. Steps to reproduce:
**I have a Sea Begger 1 hex to the right of captured Murcia.  It is in range to attack and kill a Trireme on the other side of Murcia.  When I attack it the CTD occurs (3 times in a row so seems reproducible).  My suspicion is that the game is freaking out when the Sea Begger captures the trireme such that it becomes my unit and maybe doesn't know how to handle the worker that is also in the Trireme's tile.**

5. Additional information:
**Attached the save file and Lua/Database/XML/minidump in case they are useful.**

**Comment by crdvis16** [comment]
I can't seem to attach the save file or logs... tried zipping them up but it still won't take it?  I just get a message saying "unfortunately, we don't support that file type", even though ZIP is one of the types they supposedly accept?

Is there a recommended program for compressing the files?

**Comment by Jotaro31400** [comment]
they don't take .rar.

Right click on your files, select " add to archives" you should be able to choose between .rar and .zip.
Pick zip and compress. Now you should be able to upload the file here.

**Comment by crdvis16** [comment]
I've tried with a .zip and I still get the same message.  It's a compressed zip file (called CTD.zip, so it has the .zip extension) and it still won't take it.  If it matters I used a trial version of winzip to create it.

**Comment by crdvis16** [comment]
The file I'm trying to submit is a .zip (called CTD.zip) so I believe it has an extension that is supposed to be accepted.  It was created using a trial version of winzip in case that matters.

**Comment by crdvis16** [comment]
Also just generated a .zip from the website http://www.ezyzip.com/ and still can't submit it, still get the same error message "unfortunately, we don't support that file type".

**Comment by GrantSP** [comment]
Are you sure you are actually attaching the *.zip files and not some other files as well, or instead of?
Open an explorer window and just drag/drop it onto this report. *.zips regardless of how they are produced will get uploaded as normal, no need for anything special.

**Comment by crdvis16** [comment]
I have a file called "CTD.zip" that I am attempting to drag and drop into this comment message.  I do so and then get the message in red text "Unfortunately, we don't support that file type".  I'm only dragging the .zip, right from my Desktop.  It is 100% a zip file with a .zip extension (I didn't do something stupid like name it 'CTD.zip' even though it's a .rar or something).  I have no idea why this isn't working.  Gazebo- if there is some other way for me to send you these logs/savefiles/etc let me know.

**Comment by GrantSP** [comment]
Okay I'll use this issue to add my own files as I too can repeat the CTD each time.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/254250/Logs.zip)
[Napoleon_0313 AD-1886.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/254251/Napoleon_0313.AD-1886.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/254252/CvMiniDump.zip)

This game is now impossible to proceed any further. Second time I got a game to nearing a culture victory with France only to have it CTD repeatably and render it broken.

The game is currently on turn 313 and no matter what happens as soon as the AI have their turns it crashes.

**Comment by ilteroi** [comment]
@GrantSP : what is your mod list? can't load the save

**Comment by GrantSP** [comment]
Sorry, forgot to add that in the description. CBP parts 1 - 6a and FlagPromotions v7
