### ISSUE TITLE
Can't see tech's after classical era in tech tree

### ISSUE THREAD

**Issue by Timur512** [LoneGazebo/Community-Patch-DLL#1760]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
CP - v.72
CBP - v.13

2. Mod List (if using standard CPP set, leave blank):

CP and CBP without EUI

3. Type of error (i.e. crash, interface bug, AI quirk): 

interface bug

4. Steps to reproduce:

open tech tree

5. Additional information:

[http://prnt.sc/b1xneu](url)
---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
You are missing required game DLC.
