### ISSUE TITLE
AI has a hard time making good decisions during War time and in the face of death

### ISSUE THREAD

**Issue by Cyde042** [LoneGazebo/Community-Patch-DLL#1761]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):4/23

2. Mod List (if using standard CPP set, leave blank): CBP (with EUI) and http://i.imgur.com/tAi2SpN.png

3. Type of error (i.e. crash, interface bug, AI quirk): AI quirk

4. Steps to reproduce: Not sure if it happens with any CIV, but Siam did it.

5. Additional information:
It was early game, standard speed, emperor diff. I was exploring and saw an unguarded Siamese settler and of course, I captured it.

I then sent my army of 3 archers and 2 warriors to his capital and started my siege. Until the end of it, Ramkahemfunnyface produced 2 warriors total besides the army he already had. But to my surprise, he thought it was a good idea to produce more settlers under heavy fire. One of them he left completely unguarded and sent it straight to my archers.

The 2nd one had a guard but while I was catching up to it, the settler ended its turn 1 tile behind the warrior, weirdly enough, there was no irregular terrain. The settler stopped in the plains but the warrior on the hill right next to it. So it also got captured and the warrior died.

In the meantime I sent my settler to found a city near his capital and it was far enough that the garrison wouldn't get it (but it was in his capital's territory so he could see it). Guess what, the fool valued the null possibility of him capturing the settler (it was unguarded) that the garrison left his Capital unguarded to my archer barrage and then died like an idiot. And that was the demise of Ramkahemagun.

So the AI doesn't really understand how deeply in shit it is sometimes. Since it was the ancient era, his city bombardment couldn't hit my archers, maybe that could be accounted for in their logic?

A similar incident happened in an older beta(from march) that Dido, after losing 9 of her 12 cities, with the 3 newest cities remaining, preferred building The Forbidden Palace instead of a garrison. I was persistently attacking and destroying her army. Her current capital had no units near it. In the end, she build the palace in the city during the turn right before I was to capture it.

**Comment by ilteroi** [comment]
make that "AI has a hard time making good decisions all the time" :)

your mod list is quite impressive, can you please try to reproduce this with only the CPP active?
