### ISSUE TITLE
Very short times to steal techs

### ISSUE THREAD

**Issue by nOxrax** [LoneGazebo/Community-Patch-DLL#1763]
1. Mod Version
4/23b beta with dll hotfix

2. Mod List
CP
Custom Advanced Setup Screen (+ playing hotseat)

3. Type of error
Balance

4. Description
In this beta, the time it takes to steal a tech has been markedly shorter, too short I think. It takes me 7-10 turns to steal techs. In previous versions of CP it would take me 15-30 turns in the same situations, which I think is a better time. I play on Deity/Epic and as a result I'm far behind in tech when you get the first spy, typically 5-10 techs behind the other civs. Also, it used to be only the first few techs you stole that was quick, and then the time would go up as I catched up, but now I have stolen five techs and are starting to catch up, but techs are still very quick to steal.

EDIT: The cities I steal from have very high potentials, 9 or 10. I guess the change is related to the rework of the system with potentials.

**Comment by LoneGazebo** [comment]
Extremely high potential cities are easier to steal from, yes.

**Comment by nOxrax** [comment]
But it is too easy to steal now. During the time my scientiest discover one tech, my spy steals three techs. I think that is unbalanced, and it changes the foundation of the game by making it less important to improve your own scientific output. It is too big of a change to the game for CP. I play on Deity because I want to be behind on tech and struggle to catch up, but now my spies make it very easy to catch up and it removes the difficulty.

And the problem is not only with extremely high potential cities. From a city with potential 10 it takes me 7 turns to steal, and from a city with potential 6 it takes me 10 turns, and there is no shortage of cities with 5+ potential. 

Is the steal-time linked to gamespeed?

**Comment by LoneGazebo** [comment]
The new potential system doesn't actually change the 'back end' of the espionage system, merely how it is presented to the player. I'll look at it.
