### ISSUE TITLE
era scaling on cityeventchoice

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1765]
The resistance option of gunpowder plot should be 5 turns on normal speed.
In this screenshot, he's playing on marathon, so 3x multiplier => 15 turns 
But it says 90. I'm guessing this is era scaling as well for another 4x multiplier. However, era scaling is false by default. Is this an error with the era scaling or the {4_Turns} text?

http://images.akamai.steamusercontent.com/ugc/271717169535436776/F5CE99EF2F73835774E68AED9DA5724CEA8C6E02/

**Comment by LoneGazebo** [comment]
I'm not sure, I'd need to check.

**Comment by LoneGazebo** [comment]
fixed.
