### ISSUE TITLE
Resources, strategic and luxury, aren't showing up

### ISSUE THREAD

**Issue by Matathew** [LoneGazebo/Community-Patch-DLL#1766]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

May 10, newest version on all five CPP mods

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 

Resources aren't showing

4. Steps to reproduce:

Just start a new game and research some strategic resource and luxury resource revealing techs

5. Additional information:
I have the most recent version of civ V and everything else works fine

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
Your copy of civilization is most likely not up to date.

**Comment by LoneGazebo** [comment]
You should be on version .279.
