### ISSUE TITLE
CTD during AI turn

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#1767]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

4/32b plus DLL hotfix

2. Mod List (if using standard CPP set, leave blank):

1 - 6a of CBP plus FlagPromotions v7

3. Type of error (i.e. crash, interface bug, AI quirk): 

CTD during the AI turn

4. Steps to reproduce:

Perform any of the remaining tasks in the last save before this crash and then end your turn.

5. Additional information:

Same CTD experience as previously posted with regard to my games as France.
(Sadly those reports are closed although unresolved)
[Harun al-Rashid_0325 AD-1905.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/258702/Harun.al-Rashid_0325.AD-1905.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/258703/Logs.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/258704/CvMiniDump.zip)

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
I'm closing all CTDs that have otherwise been dealt with or changes to code have rendered them invalid. This is indicative that potential fixes are on the way.
