### ISSUE TITLE
oddities in code

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1768]
@LoneGazebo : some questions for you

this is a piece of code from the trade route valuation. shouldn't it be += ?

```
		if(m_pPlayer->GetPlayerTraits()->GetTradeRouteStartYield((YieldTypes)iYieldLoop) > 0)
		{
			iScore -= (m_pPlayer->GetPlayerTraits()->GetTradeRouteStartYield((YieldTypes)iYieldLoop) / 2);
		}
		if(m_pPlayer->GetPlayerTraits()->GetYieldChangePerTradePartner((YieldTypes)iYieldLoop) > 0)
		{
			iScore -= (m_pPlayer->GetPlayerTraits()->GetYieldChangePerTradePartner((YieldTypes)iYieldLoop) / 2);
		}
```
		
this looks problematic, don't know who did it:
```
/// Gold per turn from international trade routes
int CvTreasury::GetGoldPerTurnFromTradeRoutes() const
{
	// needs fixin
	return 0;
	//return GetGoldPerTurnFromTradeRoutesTimes100() / 100;
}

/// Gold per turn from international trade routes times 100
int CvTreasury::GetGoldPerTurnFromTradeRoutesTimes100() const
{
	return 0;
	//return m_pPlayer->GetTrade()->GetAllTradeValueTimes100(YIELD_GOLD);
}
```		

this function looks only at plots where a city can be founded, i.e. several plots away from the actual city. is this intended?
```
void CvCitySpecializationAI::FindBestSites()
```

**Comment by LoneGazebo** [comment]
1.) That is correct (as it is in the internal TR score, and players that get a bonus per international TR should not send internal TRs if possible). The top part, the 'start' one, will be removed.

2.) That's a vanilla thing - the core DLL is that way as well. Not an issue, I guess?

3.) I haven't looked at the findbestsites() function.
