### ISSUE TITLE
how to execute lua calls in the firetuner?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1769]
stupid question, how does the lua console work?

e.g. i try to activate debug mode:

> Game:ToggleDebugMode()
Runtime Error: [string "_cmdr = {Game:ToggleDebugMode()}"]:1: attempt to index global 'Game' (a nil value)
stack traceback:
	[string "_cmdr = {Game:ToggleDebugMode()}"]:1: in main chunk

but the table browser, "Game" exists and it has an entry "ToggleDebugMode"

**Comment by LoneGazebo** [comment]
Did you set the lua state to ingame?

**Comment by LoneGazebo** [comment]
The drop down element on the top left side.

**Comment by ilteroi** [comment]
thanks, that was it - didn't know about the different lua states.
