### ISSUE TITLE
[Bug]Cultural Diversity's Horse is spawning at sea

### ISSUE THREAD

**Issue by wileyhk2001** [LoneGazebo/Community-Patch-DLL#177]
![clipboard04](https://cloud.githubusercontent.com/assets/5993201/6962964/44a264a6-d96c-11e4-9d46-4c3a3b0c5dcd.jpg)

As the Huns, I found that cultural Diversity's starting bonus spawns Horse at sea.

http://forums.civfanatics.com/newreply.php?do=newreply&noquote=1&p=13275590

**Comment by LoneGazebo** [comment]
This is a bug with mapgeneration, not the CBP – I'd let the author of the mod know.
G
