### ISSUE TITLE
observed quirks

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1771]
too many archeologists:

![image](https://cloud.githubusercontent.com/assets/1358966/15233330/29c6b5c0-18a8-11e6-9193-1b88f6bfffe9.png)

there are some dig sites around, but not soo many and in any case the archeologists are just idling.

**Comment by LoneGazebo** [comment]
Hmm...I'd need to see a few more examples of this to call it a bug...

**Comment by ilteroi** [comment]
yeah. no immediate action required, just collecting quirks.

other things i've seen:

- captured a worker a major AI had stolen from a minor AI (or captured from barbarians). anyway, released the worker but got no influence from the city state

- in the game above, the arabians apparently starved their capital down to about 4 citizens. don't know how, just caught it on the rebound

**Comment by ilteroi** [comment]
assyria is not settling the open space, although early expansion strategy is still active. they simply don't seem to build any settlers.

![image](https://cloud.githubusercontent.com/assets/1358966/15250547/a375f07a-1925-11e6-9aae-d059a1bb3152.png)


----

jewelry monopoly gives +5 happiness? that seems awfully easy, considering there's only one source for it ...

![image](https://cloud.githubusercontent.com/assets/1358966/15250586/cd5d3d1c-1925-11e6-8885-d1879ba05c4a.png)

**Comment by LoneGazebo** [comment]
Settler issue is because you disabled a big source of points for settlers in the unitproductionAI. I had to up the other numbers to get them settling again.

**Comment by ilteroi** [comment]
aha. good point.

well it turns out, the city site values are computed almost every turn anyway, so the check isn't that expensive after all.

just took a look and i noticed that you don't check for the "early expansion" strategy. is that by design? the name is misleading btw, it should be "expand on home continent".

also, the strategies themselves should adjust the flavor values, right? so does it make sense to have them influence the weights as well?

**Comment by ilteroi** [comment]
also, maybe too late to mention this, but i think harbors are extremely late at compass. sea trade routes were already common in antiquity, just think of the mediterranean. in fact, sea-based trade was viable long before land-based trade. maybe allow city connections over water with lighthouses? those come with sailing, just like cargo ships, so it all fits together.

**Comment by LoneGazebo** [comment]
I have them influence weights because it gives me more granular control over their effects. Flavors are not reliable in that regard.

Re: Harbor, that's something that would need to be discussed on the subforum.

**Comment by ilteroi** [comment]
which subforum? i'll just open a thread.

anyway, looking around i found the "holy grails" list ... by that metric, we actually quite good :)

**Comment by ilteroi** [comment]
so the harbor change seems to be accepted - can you do this? i don't know how :)

also, this just in:

![image](https://cloud.githubusercontent.com/assets/1358966/15277292/2f2bc244-1b00-11e6-84d2-448e1ffb4e69.png)

i think that was also reported elsewhere, AI does not seem to prioritize building military units when on the defensive. that's a pioneer in nottingham ...

**Comment by LoneGazebo** [comment]
What did the unitproduction log look like?

**Comment by LoneGazebo** [comment]
I can do the harbor flip, yep.

**Comment by Edaka** [comment]
I see the flip isn't there in the latest beta. I wonder if you decided not to do it, or you simply forgot or haven't had time for that.

**Comment by LoneGazebo** [comment]
This discussion happened just as I was releasing the last beta. Will be next beta.

**Comment by Edaka** [comment]
Cool. No rush, just clearing things up (:

**Comment by ilteroi** [comment]
so this still seems to be a problem:

the inca in danger but building no units.

![image](https://cloud.githubusercontent.com/assets/1358966/15518604/01d0a1ca-21fe-11e6-8ebf-06c004639910.png)

[CityStrategyAIProductionLog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/280441/CityStrategyAIProductionLog.zip)

**Comment by ilteroi** [comment]
some turns later:

![image](https://cloud.githubusercontent.com/assets/1358966/15518662/46d03894-21fe-11e6-95cb-338f73248b32.png)

**Comment by LoneGazebo** [comment]
They were probably broke.

**Comment by ilteroi** [comment]
hmm. didn't check. but shouldn't we override that check in a state of emergency?

**Comment by LoneGazebo** [comment]
It should already. I'd need to study the logs.
