### ISSUE TITLE
CTD when trying to generate level.

### ISSUE THREAD

**Issue by ARose8245** [LoneGazebo/Community-Patch-DLL#1773]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
(3/9)
Though same crash also occurs on my computer using(4/23)
Making me think this is a setting/hardware/bad previous uninstallation issue at my end.

2. Mod List (if using standard CPP set, leave blank):
full cpp/cbp with EUI

3. Type of error (i.e. crash, interface bug, AI quirk): 
CTD on attempting to generate level

4. Steps to reproduce:
On my machine, attempt to start a new single player game from inside the mods menu.

5. Additional information:

99% of time starting a game on my computer causes a CTD  to occur, on the very rare occasion the game does start, then in first few turns entire interface bceomes non responsive; the mouse is still mobile but clicking in game does nothing, and more worryingly, ctrl-alt-delete, alt-f4, windows key, ctrl-shift-esc, andalt-tab all become useless, meaning only way to get game to shutdown is to power off laptop. game sounds and music continues to play however, so not a total hang.

Options that may or may not be relevant(n.b. crashes have occurred when I have set these to other settings, but these are the changes from default in this crash.) :
Continents plus generator 
Research agreements on
Tech brokering on
human vassalage on

---------------------------

Supporting information:

Sorry these aren't zipped, but github refused to accept the zipped versions of these as valid zip files for some reason.

1. Log files: Database.log and Lua.log needed
[Database.log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/263611/Database.log.txt)
[Lua.log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/263609/Lua.log.txt)

2. Minidump file (located in your Civ5.exe directory)
[CvMiniDump.dmp.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/263613/CvMiniDump.dmp.txt)

3. Screenshots (if needed)
n/a
----------------------------

**Comment by Jotaro31400** [comment]
I've just updated my dll with the 04/23B version from the 04/23, and I've got three ctd on map generation, before, finally,to succeed once.

**Comment by GrantSP** [comment]
I have been experiencing these sort of hangs when using the 'Unit action' panel to assign actions.

**Comment by LoneGazebo** [comment]
Please try 5/14 version.
