### ISSUE TITLE
CTD on AI Turn

### ISSUE THREAD

**Issue by Grabbl** [LoneGazebo/Community-Patch-DLL#1774]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):
1.3.9

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 
CTD without any error message, warning or freezing

4. Steps to reproduce:
Klick "Next Turn".

5. Additional information:
[BugReport.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/264098/BugReport.zip)

---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

----------------------------

**Comment by LoneGazebo** [comment]
We're on 5/14 now for CTD debug baseline, so closing.
