### ISSUE TITLE
stuck turn

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1775]
just experienced the stuck turn problem firsthand. initially it seemed to be an engine / lua issue, i broke into the debugger about 10 times but never hit any DLL code.

poking around with the firetuner, it says it's waiting for china to end the turn. china was eliminated ages ago but recently came back to life when somebody liberated one of their cites. apparently that caused the problem ...

now, it seems the offending line is in CheckPlayerTurnDeactivate() - and it is hit in the debugger, just too quickly to catch without knowing where to put a breakpoint

```
	if(kPlayer.isEndTurn() || (!kPlayer.isHuman() && !kPlayer.HasActiveDiplomacyRequests()))		
```

isEndTurn() is false, but that seems to be normal for AI players. However, isHuman() returns true for China, which is wrong.

**Comment by ilteroi** [comment]
ok it seems China is in an observer slot. or rather, china's slot became the observer slot while they were dead. so it's caused by playing around with the firetuner, normal play shouldn't be affected.

did anyone else experience a lock-up without the firetuner?

**Comment by LoneGazebo** [comment]
That's odd.

**Comment by ilteroi** [comment]
well, i did this change some time ago for Really Advanced Setup, because it doesn't leave any observer slots, sets them all to closed. so instead i just grabbed the first closed slot for the observer. which obviously has side effects. but should be better now.
