### ISSUE TITLE
UI shows that Dromon is only buildable by the Byzantines

### ISSUE THREAD

**Issue by ErikSteiner** [LoneGazebo/Community-Patch-DLL#1776]
## 1. Mod Version:
Community Patch Project 4/23b

## 2. Mod List:
- (1) Community Patch
- (2) Community Balance Patch
- (3) CSD for CBP
- (4) Civ IV Diplomatic Features
- (6a) Community Balance Patch - Compatibility Files (EUI)
- Architecture changes (v 1)
- Calypso's Colored Religious Icons (Basic) (v 4)
- Custom Advanced Setup Screen (v 5)
- FlagPromotions (v 7)
- Global Relations (v 7)
- JFD's Exploration Continued Expanded (v 15)
- JFD's The Commonwealth of Iceland (v 2)
- JFD's The Confederation of Switzerland (v 5)
- JFD's The Kingdom of Belgium (v 1)
- JFD's The Kingdom of Hungary (v 8)
- JFD's The Kingdom of Norway (v 6)
- R.E.D. - Smaller Landmarks (v 5)
- R.E.D. Modpack (v 28)
- Randomize City Names (v 2)
- Terrain Texture Enhancement 2k (v 3)
- TerrainTextureMod (v 2)
- Yet (not) Another Earth Maps Pack (v 24)

## 3. Type of error (i.e. crash, interface bug, AI quirk): 
The quick info at the building menu will give me the info that only the Byzantines may build this ship, but I played as Greece and were able to build it.

**Comment by LoneGazebo** [comment]
I don't see this issue. Mod conflict, most likely.

**Comment by ErikSteiner** [comment]
The problem still occurs if I load the following mods only:

- (1) Community Patch
- (2) Community Balance Patch
- (3) CSD for CBP
- (4) Civ IV Diplomatic Features
- (6a) Community Balance Patch - Compatibility Files (EUI)

Is it possible if this entry could be the problem:
```
UPDATE Language_en_US
SET Text = 'Dominant Classical Era Naval Unit used to own the seas well into the Medieval Era with its ranged attack.'
	WHERE Tag = 'TXT_KEY_UNIT_HELP_BYZANTINE_DROMON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1 );
```

- I added a file for German that contains this:
```
UPDATE Language_de_DE
SET Text = 'Dominant Classical Era Naval Unit used to own the seas well into the Medieval Era with its ranged attack.'
	WHERE Tag = 'TXT_KEY_UNIT_HELP_BYZANTINE_DROMON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1 );
```

- So I added several files to (2) Community Balance Patch (v 13).modinfo, that contain the German text or the text that must be still translated: (2) Community Balance Patch\Balance Changes\Text\de_DE
Here for example. It contains a German UnitText.sql

- This is how it looks like in the modinfo (be aware that this is only a short version of the file):
```
  <Blocks />
  <Files>
    <File md5="8a38e915706a8c8c88ad655d84bca5e6" import="0">Balance Changes/Text/de_DE/UnitText.sql</File>
  </Files>
  <Actions>
    <OnModActivated>
      <UpdateDatabase>Balance Changes/Text/de_DE/UnitText.sql</UpdateDatabase>
    </OnModActivated>
  </Actions>
```

So both languages are supported, but if I load the game in English I will not have the information that only the Byzantines may build it. The German text will contain this information..

**Comment by LoneGazebo** [comment]
I'm not sure how Civ reacts if you are mixing language files, truth be told.

**Comment by ErikSteiner** [comment]
Thank you for taking your time. After some investigation I found out that something in my UnitText.sql must be wrong. This is the path to the file. I just copied the en_US folder and added this to the modinfo:
Mods\(2) Community Balance Patch\Balance Changes\Text\de_DE\UnitText.sql

[(2) Community Balance Patch (v 13).modinfo.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/269924/2.Community.Balance.Patch.v.13.modinfo.zip)

The strange thing is, that it will not work if I take the original UnitText.sql, past it into the de_DE folder and change the language_en_US to language_de_DE. I found out that if I go into my \de_DE\UnitText.sql delete everything and just add this string, it will show up correctly in German if I set the language of the game to German:
```
UPDATE Language_de_DE
SET Text = 'Dominant Classical Era Naval Unit used to own the seas well into the Medieval Era with its ranged attack.'
    WHERE Tag = 'TXT_KEY_UNIT_HELP_BYZANTINE_DROMON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1 );
```

I then tried out something different. I deleted everything again and added the first few strings of the original file, I hoped that I could find out what string will not work. I have the suspicion that one string, that will somehow not work, will block everything else. So this was the content of my UnitText.sql then:

```

	-- Civilians
	
	-- Great Merchant Text

	UPDATE Language_de_DE SET Text = 'If the unit is inside City-State territory that you are not at war with, this order will expend the unit.[NEWLINE][NEWLINE]You will receive a large amount of [ICON_GOLD] Gold and an instant ''We Love the King Day'' in all owned cities. This action will consume the unit.' WHERE Tag = 'TXT_KEY_MISSION_CONDUCT_TRADE_MISSION_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

	UPDATE Language_de_DE SET Text = 'The Great Merchant can construct the special Custom House improvement which, when worked, produces loads of [ICON_GOLD] Gold. The Great Merchant can also journey to a city-state and perform a "trade mission" which produces gobs of [ICON_GOLD] Gold, starts a ''We Love the King Day'' in all owned cities and, (if not using CSD) garners many Influence Points with the city-state. The Great Merchant is expended when used in any of these ways.' WHERE Tag = 'TXT_KEY_UNIT_GREAT_MERCHANT_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

	-- Changed how Musician Great Tour Works
	UPDATE Language_de_DE SET Text = 'The value of this action depends on your [ICON_TOURISM] Cultural Influence over the target Civilization.[NEWLINE][NEWLINE][ICON_BULLET]If [COLOR_MAGENTA]Unknown[ENDCOLOR] or [COLOR_MAGENTA]Exotic[ENDCOLOR]: Your [ICON_TOURISM] Tourism with the target Civilization is immediately raised to [COLOR_MAGENTA]Familiar[ENDCOLOR] status, and you receive 2 [ICON_HAPPINESS_1] Happiness in your [ICON_CAPITAL] Capital.[NEWLINE][NEWLINE][ICON_BULLET]If [COLOR_MAGENTA]Familiar[ENDCOLOR] or [COLOR_MAGENTA]Popular[ENDCOLOR]: Gain large amount of [ICON_TOURISM] Tourism based on your Tourism and Culture output as Cultural Influence over this Civilization (20% of this [ICON_TOURISM] Tourism is also applied to all other known Civs). Additionally, you receive [ICON_HAPPINESS_1] Happiness in your [ICON_CAPITAL] Capital (scaling with Era), and the target Civilization experiences ''We Love the King Day'' in all owned Cities, scaling with your Cultural Influence and Gamespeed. This action consumes the unit.[NEWLINE][NEWLINE]Cannot perform this action if at war with the target Civilization, or if your [ICON_TOURISM] Cultural Influence over the Civilization is [COLOR_MAGENTA]Influential[ENDCOLOR] or greater.' WHERE Tag = 'TXT_KEY_MISSION_ONE_SHOT_TOURISM_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

	UPDATE Language_de_DE SET Text = 'A Great Musician can create a Great Work of Music (generates both [ICON_CULTURE] Culture and [ICON_TOURISM] Tourism) that is placed in the nearest city that has an appropriate building with an empty slot (like an Opera House or Broadcast Tower).[NEWLINE][NEWLINE]A Great Musician can also travel to another civilization and perform a [COLOR_POSITIVE_TEXT]Concert Tour[ENDCOLOR]. The value of this action depends on your [ICON_TOURISM] Cultural Influence over the target Civilization.[NEWLINE][NEWLINE][ICON_BULLET]If [COLOR_MAGENTA]Unknown[ENDCOLOR] or [COLOR_MAGENTA]Exotic[ENDCOLOR]: Your [ICON_TOURISM] Tourism with the target Civilization is immediately raised to [COLOR_MAGENTA]Familiar[ENDCOLOR] status, and you receive 2 [ICON_HAPPINESS_1] Happiness in your [ICON_CAPITAL] Capital.[NEWLINE][NEWLINE][ICON_BULLET]If [COLOR_MAGENTA]Familiar[ENDCOLOR] or [COLOR_MAGENTA]Popular[ENDCOLOR]: Gain large amount of [ICON_TOURISM] Tourism based on your Tourism and Culture output as Cultural Influence over this Civilization (20% of this [ICON_TOURISM] Tourism is also applied to all other known Civs). Additionally, you receive [ICON_HAPPINESS_1] Happiness in your [ICON_CAPITAL] Capital (scaling with Era), and the target Civilization experiences ''We Love the King Day'' in all owned Cities, scaling with your Cultural Influence and Gamespeed.[NEWLINE][NEWLINE]Great Musicians are expended when used either of these ways. Cannot perform this action if at war with the target Civilization, or if your [ICON_TOURISM] Cultural Influence over the Civilization is [COLOR_MAGENTA]Influential[ENDCOLOR] or greater.' WHERE Tag = 'TXT_KEY_UNIT_GREAT_MUSICIAN_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );


	UPDATE Language_de_DE SET Text = 'The Great Admiral can immediately cross oceans for free, making it a useful (if vulnerable) exploration vessel. Furthermore, while in owned territory, the Great Admiral can be sent on a ''Voyage of Discovery'' that expends the unit and gives you two copies of a Luxury Resource not available on the current map.[NEWLINE][NEWLINE]The Great Admiral has the ability to instantly repair every naval and embarked unit in the same hex, as well as in adjacent hexes. The Great Admiral is consumed when performing this action. The Great Admiral also provides a 15% combat bonus to all player-owned naval units within 2 tiles. The Great Admiral is NOT consumed when he provides this bonus.' WHERE Tag = 'TXT_KEY_UNIT_GREAT_ADMIRAL_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );
```
[UnitText.sql.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/269945/UnitText.sql.zip)

I spawned a Great Merchant and the fist string was displayed correctly, but I didn't see the second string. I then spawned a Great Admiral to see if the entry was changed, but it wasn't.

All in all, I don't have an idea what is going wrong. I would assume that if I add a file (xml or sql) set it to German, that I would see the Text then, no matter if it is already translated or still in English. It was working for all files that I have already translated, even the ReligionText.sql is working.
[ReligionText.sql.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/269964/ReligionText.sql.zip)

I have no idea. I will try to create a mod for the translation of the CBP-Module, reverting the Module to the original state and have a look if my translation is working then. Maybe you have an idea what is going wrong with the file. I mean this is exactly what makes me mad, all files are working except this one... I have to add that if I change the language of the game to English, everything will show up correctly. So even if I used the original UnitText.sql change this from en_US to de_DE this file will not work if I play the game in German, but the original one with en_US will work if I set the game to English..

**Comment by LoneGazebo** [comment]
Yes, load-order is very important.

**Comment by ErikSteiner** [comment]
Ok thank you. I think we can close this issue then! Have a nice day!
