### ISSUE TITLE
RequiresReligion City Event Check

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1777]
Like RequiresPantheon but for religion meaning the event should check if the city has any religion instead of checking for a specific religion.

**Comment by LoneGazebo** [comment]
That already exists no?

**Comment by LoneGazebo** [comment]
I added that for JFD a while back.

**Comment by TechpriestEnginseer** [comment]
Is it RequiresAnyStateReligion?

Seems confusing if it is.

**Comment by LoneGazebo** [comment]
Should be hasreligion I think.

**Comment by TechpriestEnginseer** [comment]
Nope can't find it.

**Comment by LoneGazebo** [comment]
HasAnyReligion, yep!
