### ISSUE TITLE
Trade Route Values Not Modified By Player Buildings

### ISSUE THREAD

**Issue by ziadb** [LoneGazebo/Community-Patch-DLL#1779]
Bug Report Template

1. Mod Version (i.e Date - (4/23b)):

Using the Beta 4/23b

2. Mod List (if using standard CPP set, leave blank):

3. Type of error (i.e. crash, interface bug, AI quirk): 

Functionality bug

4. Steps to reproduce:

Check trade route values modifiers from player before making trade route
Build an economic building like Market or Bank
Check trade route modifiers from player. No change.

5. Additional information:

In the screenshots below, you'll see that the trade route to the nearby city state did not increase in value after a customs house was built. I tried to obtain hover information for the trade route but it didn't work. Basically, in both cases it's.

Gold Base: 1
Palenque Gold Per Turn: 0.1
Jerusaleum Gold Per Turn: 0.16
Different Resources: 
Horse 0.5
Next To River: 20%

So buildings don't affect trade route values.

Interestingly, trade values still increase if the AI builds economic buildings. In the third turn, the trade route to Egypt was increased to 5 when Gold Bonus From Buildings In Thebes: 3 appeared.
---------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

http://s32.postimg.org/gpd06xg51/Market_Only.png
http://s32.postimg.org/98m6aok51/Before_Customs.png
http://s32.postimg.org/jv2nu952t/Customs_House.png
http://s32.postimg.org/sxzeq0lpx/After_Customs.png
http://s32.postimg.org/vh1orphpx/Egypt_Increase.png
----------------------------

**Comment by ziadb** [comment]
Lol weird formatting sorry.

**Comment by LoneGazebo** [comment]
@ilteroi , did your caching logic affect this?

**Comment by ilteroi** [comment]
not that i know of. i just cache the path, not the yields

**Comment by ziadb** [comment]
If it helps, apparently Harbor and Caravansary still work, but what's different is that they use "Trade Route Land/Sea Gold Bonus 200" as opposed to the Trade Routes +1 ->   Trade Routes + 1 <- description.

![market](https://cloud.githubusercontent.com/assets/2494914/15332242/d60d11fc-1c32-11e6-98fe-59043d6eb3f7.png)
![caravansary image](https://cloud.githubusercontent.com/assets/2494914/15332259/e3a21d3a-1c32-11e6-9fa6-1fa007d17ea6.png)

**Comment by ilteroi** [comment]
it seems you need to call UpdateTradeConnectionValues() to get the bonus, but it's not called on building completion. so maybe you need to end the turn to get the bonus. did you do that?

**Comment by Edaka** [comment]
I think I know what's up. It's that extremely confusing desription again. Market, custom houses and even East India Companies aren't even supposed to work like that (I believe it was the same in vanilla). 

Here's what I've fished in the BuildingChanges.sql: the mentioned buildings have `TradeRouteRecipientBonus` and `TradeRouteTargettBonus` bits. This essentially means that when you have a market in your city, this happens: _Incoming trade routes generate +X Gold for both the recipient (you) and the owner of the trade route._ This makes the bonus extremely dependent on the will of your neighbors to trade with you, as it only takes effect when somebody sends a trade route to you.

Now, if we wanted markets et al. to generate additional gold for your own outgoing trade routes, they would need to have these bits in: `TradeRouteSeaGoldBonus` and `TradeRouteLandGoldBonus`. That's what I've added for myself to the market, bazaar, custom house, East India Company and Great Cothon. You can at least control the bonus that way, which is nice. 

Anyway, if market mechahnics not to be changed, I propose a name change to better reflect what it currently does. Something similar to what I've written above: _Incoming Trade Routes generate +1  Gold for both the sender and the recipient_, or simply _Incoming Trade Routes generate +1 Gold for both parties._

**Comment by ziadb** [comment]
@ilteroi Yes it persists through turns.

Although I believe Edaka has found the cause.

**Comment by Edaka** [comment]
I was looking through text files for some of the mentioned building and found that East India Company has the most appropriate description - something along the lines I've proposed above. This is what it says: _The East India Company increases the amount of [ICON_GOLD] Gold a city generates and reduces [ICON_HAPPINESS_3] Poverty. You also receive a free copy of all Luxury Resources around the City. **Trade routes other players make to a city with an East India Company will generate an extra 4 [ICON_GOLD] Gold for the city owner and the trade route owner gains an additional 2 [ICON_GOLD] Gold for the trade route**._ 

So yeah, the bolded part shows how it's supposed to work. If that's conceived precise and descriptive enough, I'd suggest replacing the current market and customs house description (which goes '_+X [ICON_GOLD] Gold to [ICON_INTERNATIONAL_TRADE] Trade Routes to or from City._) with that, gold values adjusted ofc.
