### ISSUE TITLE
messenger of the gods belief does not work

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#178]

**Comment by LoneGazebo** [comment]
How so? What's the context of the problem?

**Comment by AnastaseAlex** [comment]
I was playing with the latest version, in communitas map, with carthage. I took the messenger of the gods belief, hoping that it would give me +2 science and faith per city (I had 4 by that point), but instead I got neither.

**Comment by LoneGazebo** [comment]
Had you researched 'the wheel' yet?

**Comment by AnastaseAlex** [comment]
Yes. I tested it again.

**Comment by AnastaseAlex** [comment]
I had the wheel, and the cities were showing to be connected to the capital

**Comment by LoneGazebo** [comment]
kk. I think I've fixed. Small bug in cityconnection code.
