### ISSUE TITLE
[VP 14-5] Promotion tree

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#1781]
I've look at the new promotion tree, and I've notice some strange things : 

- Gunpowder Units : The promotion "Flak Targeting II" has number 2 for no reasons. (The promotion "Flak Targeting I" cannot be obtained throw XP)
- Recon Units : The promotion "Scouting I" and "Scouting II" does the same thing, and are unlock at the same level. I think that "Scouting II" shoud require "Scouting I". Moreover, the promotion "Scouting III" is no longer linked to the two previous, so renaming it would be an good idea.
- Carriers : "Flight Deck I" and "Flight Deck II" does the same thing (and are unlocked at the same time), but unlock differents promotions. That's not really user-friendly. There is maybe a missing link between the two (Maybe "Flight Deck II" should require "Flight Deck I")
- Submarines : "Wolpack I" has number 1 for no reasons, because "Wolpack II" and "Wolpack III" no longer exists.

I've used "Whoward's Unit Promotions UI" to find those minor problems.

I really like the new promotions tree, so thank you for all.

**Comment by pandasnail** [comment]
Anti Aircraft Guns start with Flak Targeting I, I think II is there for them and them only, tho I've still never  seen it. Maybe it could be on Shock as well if it does exist?

Scouting is because the WHoward doesn't show dependencies at the Advanced level. Not sure about Flight Deck.

**Comment by LoneGazebo** [comment]
Some of those issues aren't real, as whoward's minimod doesn't always work (As noted by @pandasnail).

**Comment by Edaka** [comment]
Went into the game to check up on these:

- Flak Targeting II is available after Drill III. 
- Scouting I is required to take Scouting II. Likewise, scouting III requires Scouting II and either Trailblazer III or Survivalism III.
- Flight Deck II requires Flight Deck I.
- There are three Wolfpacks.

Seems that Whoward's mod is not to trust completely, unfortunately.
