### ISSUE TITLE
Specialists and Improvements civpedia

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1783]
The home page for both the Specialists and the Improvements page lists out yields that are somewhat out-of-date. With the improved tech tree, I'd prob just get rid of it, but idk.

**Comment by LoneGazebo** [comment]
Mind helping me sort it out?

**Comment by pandasnail** [comment]
I wasn't sure if you would want to keep the info there, but since you do, yeah, I'll go through it during the basketball game tomorrow

**Comment by LoneGazebo** [comment]
Thanks!

**Comment by pandasnail** [comment]
Specialist Page

Says Rationalism Academics give +2 Science, its +1
Says Industry finisher gives 1 Production, its 2
Doesn't list Laborer at all which is this 
Base: 1 Production
Civil Service: +1 Gold
Industrialization: +1 Gold
Fertilizer: +2 Production

Improvements
Doesn't list Tradition finisher or Aesthetics National Treasurer 
Holy Site lists old yields instead of the current +3 to tourism culture and faith
Doesn't mention the bonus they get from the Religious NWs
Wrong Holy Site scalers too, current is 
Acoustics: +3 Faith
Archaeology: +3 Culture
Flight +3 Tourism 

Manufactory base prod says 4, its 5
