### ISSUE TITLE
Hand Axe isn't in the civpedia

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1784]
Did you remove it from the game?

**Comment by F0rst1** [comment]
It's not removed. It's been missing from civilopedia for quite some time.

**Comment by LoneGazebo** [comment]
It is in the game, but not the civpedia. Barb units aren't buildable, and they shouldn't be in the civpedia anyways.

**Comment by pandasnail** [comment]
Tbh I don't understand why you wouldn't have them in the civpedia-but in that case, the error is that the Brute and Galley are

**Comment by LoneGazebo** [comment]
They shouldn't be. I'll look.

**Comment by Edaka** [comment]
What's the reasoning behind the conclusion that barb units shouldn't be in the Civpedia? If it's the fact that they aren't buildable, then I'm personally against it. Firstly, the Huns can actually possess them. Secondly, as there often are situations when you fight against those units, so it's useful being able to access information about their CS and promotions (although, to be fair, this can also be accessed without civpedia). Lastly, it would be unnecessary to waste the related strategy and historical info sectional, imo.
