### ISSUE TITLE
Kasbah placement bugged?

### ISSUE THREAD

**Issue by Slobodan85** [LoneGazebo/Community-Patch-DLL#1788]
Is it intentional behaviour to be able to build six kasbahs around a city as Morocco? That's incredibly overpowered if so. Otherwise, it's bugged.

**Comment by pandasnail** [comment]
Obvi I'm not Gazebo, but nonetheless I do know this is intentional, yeah. If you think its OP, take it up in the leader subforum.

**Comment by LoneGazebo** [comment]
Yes. It is correct.
