### ISSUE TITLE
Obvious bugs from "Unit tree image" topic

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#179]
- XCOM squad: doesn't have "Ignores building defence" in it's description. I think that they have enough stuff to ignore every defence.
- XCOM squad: it has "Skyranger" promotion that is simmilar to Paratrooper promotions but there is no "No movement cost for pillage" included. I think that upgraded units should rather save their abilities so maybe lets add it?
- Lancer: Cavarly has been fixed but lancer still has Ignores Building Defence promotion. This makes no sense.
- Caravel: it has only 3 moves while it's predecessor and upgrade have 4 . It doesn't make sense that more advanced ships are slower. We talk about almost 3 era difference in time!
- Galleas: same as above. Only 3 moves.
- Destroyer: it haven't been moved to rocketry as it stands in changelog. Or there's something wrong with my version.
- Battleship: can't be upgraded to Missile Cruiser. They should be on the same upgrade path.
- Missile Cruiser: doesn't require any SR. I think that the most powerful ranged unit (and such a massive piece of ship) should require oil at least 
- Submarine: there is almost do difference in Submarine and Nuclear submarine / costs (50/40 respectively). This is strange as Nuclear submarine has: +15 strength, +1 move, +25 ranged, +1 range, extra sight and ability to hold 2 missiles. That's hmm quite a lot for 40 . 
- Zeros: as replacement of Fighter they're not that strong (+33% vs Fighters bonus). For example B17 (replacement of Bomber) has +5 ranged, Evasion 50% and Siege I what is significant buff. I'd suggest to give Zeros at least +5 ranged.
- B17: has Siege I promotion which gives +33% stregth aggainst cities. That's good but every other unit in game has unique promotion that gives percentage bonus to certain situations (what allows this unit to get promotions like "Siege" anyway). That's rather a detail but well 
- Gatling Gun: It doesn't have "Ignores Building Unit" promotion. Note that every other Industrial+ unit HAS this promotion.

**Comment by LoneGazebo** [comment]
Fixed.
