### ISSUE TITLE
‘God of the Sun’ pantheon

### ISSUE THREAD

**Issue by erikhuizinga** [LoneGazebo/Community-Patch-DLL#1790]
God of the Sun pantheon should give +1 culture and +1 faith from farms on wheat, but the extended tooltip suggests a farm on grassland without wheat also would yield this.

See attached screenshot.

![20160515175102_1](https://cloud.githubusercontent.com/assets/19374736/15275226/af972c1a-1ac5-11e6-9cf1-f7230448273d.jpg)

**Comment by LoneGazebo** [comment]
That's just because of EUI being dumb. Sorry, can't fix.
