### ISSUE TITLE
Stone Works Event has Monument event description

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#1791]
It's:

('CITY_EVENT_STONE_WORKS_DISCOVERY','TXT_KEY_CITY_EVENT_MONUMENT_DEVELOPMENT','TXT_KEY_CITY_EVENT_MONUMENT_DEVELOPMENT_HELP'

When it should be:
 ('CITY_EVENT_STONE_WORKS_DISCOVERY','TXT_KEY_CITY_EVENT_STONE_WORKS_DEVELOPMENT','TXT_KEY_CITY_EVENT_STONE_WORKS_DEVELOPMENT_HELP'

**Comment by LoneGazebo** [comment]
I'll fix.
