### ISSUE TITLE
Attila's border expansion

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#1794]
Mod Version (i.e Date - (4/23b)):
5/14, full CPP, nothing else.

Type of error (i.e. crash, interface bug, AI quirk):

Attila doesn't get adjacent plains tiles, when he gains a plains tile naturally. Probably happens with grassland tiles too, but I didn't pay attention to it.

**Comment by F0rst1** [comment]
Another user confirmed that the bug happens on grassland tiles too.

**Comment by LoneGazebo** [comment]
I see the bug, will fix.
