### ISSUE TITLE
Spain gets 2 happiness from discovery of natural wonder

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#1795]
Mod Version (i.e Date - (4/23b)):
5/14, full CPP, nothing else.

Type of error (i.e. crash, interface bug, AI quirk):

Spain gets 2 happiness from discovery of natural wonder. Others get just 1. This probably dates back to the time when Spain's UA gave them something extra from natural wonders.

**Comment by LoneGazebo** [comment]
I'll take a look.
