### ISSUE TITLE
Cannot start a new game.

### ISSUE THREAD

**Issue by CharlesDR** [LoneGazebo/Community-Patch-DLL#1796]
Mods: 5/14 full Vox Populi

Bug: starting a game through any menu causes the game to immediately become unresponsive.

First saw bug when attempting to use YnAEMP and Exploration Continued Expanded, but cleared cache and tried with just Vox Populi and continued to have the same issue.

[Database.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/265150/Database.txt)
[Lua.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/265151/Lua.txt)

**Comment by LoneGazebo** [comment]
@ilteroi, related to observer change?

**Comment by CharlesDR** [comment]
For further clarification, the game freezes as soon as you hit the "start game" button. No load screen appears and it does not crash to desktop. Have to stop the process through task manager in order to get out.

**Comment by ilteroi** [comment]
well, it works for me. haven't tried the mods above though.

in any case, observer mode should not affect a normal game.

**Comment by LoneGazebo** [comment]
Unless the game can't find a slot or something. I think there's always an observer slot reserved.

**Comment by dinwkey** [comment]
i attached debugger and looks like some memory corruption causing it stuck in the loop CvStartPositioner::ComputeRowFertility with negative ymin (input looks positive at first)?
![chopintotworegions](https://cloud.githubusercontent.com/assets/17967981/15280531/4ef8acf0-1aff-11e6-9cf5-ed59232e793e.PNG)
![computerowfertility](https://cloud.githubusercontent.com/assets/17967981/15280533/52d88ea8-1aff-11e6-8724-95b1fbb688e7.PNG)
![computerowfertility_negative](https://cloud.githubusercontent.com/assets/17967981/15280534/5604fe22-1aff-11e6-9b40-d240ce149e1d.PNG)

**Comment by dinwkey** [comment]
I think the changes calculateAreas function in CvMap.cpp causaed the boundary incorrect for custom map

**Comment by ilteroi** [comment]
ok, guess that's on me then. thanks for the hint ... are you going to fix it? in that case i'll gladly keep my hands off

**Comment by dinwkey** [comment]
I think it is easier for you to fix it since I don't know the reason of the calculateAreas  changes. Glad I can help to pin point the issue for you guys as I like to play yemap a lot :)

**Comment by ilteroi** [comment]
seems like i confused east and west ... and the plot value update assumed the players are already allocated ... fixed now
