### ISSUE TITLE
Can take Formation I as first promotion

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1797]
When my starting Warrior gained enough xp for a promotion, Formation I was a choice. Weird cause the WHoward mod had it behind Drill II. Using EUI now so I can't recheck the Whoward mod.

Full 5/14 version

**Comment by pandasnail** [comment]
I finally learned how to take a screenshot when it happened to the second warrior as well. 

And my modlist: Your six with EUI, FlagPromotionsV4, Civ Names by Policies, More Great Works, Great People Pack, Historical Generals,  More Great Musicians, Ice Free Coasts, Celtic City Names, Iroquoian City Names, Randomize City Names, NoAltitudeTraining (removes the Mt. Kilman promo), and my own version of Wario's Rules, which right now only deletes Goddess of Protection, and sets Barbarian exp to -1.

![20160515141318_1](https://cloud.githubusercontent.com/assets/16260521/15275996/e80a1d86-1aa8-11e6-81d1-32064cb2772b.jpg)

**Comment by MoiMagnus** [comment]
Same bug for me.
Mods = Vow populi (without EUI) + Infoadict + a lot of Whoward UI mod

**Comment by F0rst1** [comment]
I can confirm that this also happens without any additional mods, so it is caused by CPP.

**Comment by LoneGazebo** [comment]
I know why. Will fix in next.
