### ISSUE TITLE
Stone works tooltip description doesn't show requirement of improves Jade or Salt

### ISSUE THREAD

**Issue by erikhuizinga** [LoneGazebo/Community-Patch-DLL#1798]
See the Stone Works tooltip in the screenshot below, the text in red shows up. However, the city has improved salt, which is (and Jade too, but the city has no Jade) another possibility. The Civilopedia shows the correct info.

![20160515193929_1](https://cloud.githubusercontent.com/assets/19374736/15275850/0d3d48ca-1ad7-11e6-839a-40802e15318a.jpg)

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict.

**Comment by LoneGazebo** [comment]
Other mods?

**Comment by erikhuizinga** [comment]
Nope, nothing else, just 1,2,3,4,5,6a from CPP. Might be EUI not handling something well?
