### ISSUE TITLE
Possible bugs from "Unit tree image" topic

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#180]
- Mercenaries: can't upgrade to Mechanized Infantry. Other buyout units can upgrade so maybe it's not intended.
- Marines: Simillar problem. They could upgrade to Mechanized infantry because they go obsolete in Information Era.
- Volley Gun: It doesn't have "Ignores Building Unit" promo. I'm not sure if it should have it though (but if this promotion is for every gunpowder unit then it would make sense to add it).
- Ironclad has only 3 moves and "Double movement on coast" promotion. I think that this makes no sense. Why can't he just have 5 or 6 moves (like other units in his upgrade line) without this weird promotion? Not only this is weird but imbalanced: movement bonusses from wonders/englandUA/other sources gives this unit 2 additional moves, not 1. It's strange that this industrial unit can be faster than any other unit in game (except planes). Maybe I don't get the idea, why this unit is slower on oceans (I'd understand if it was ancient unit but this...).

**Comment by LoneGazebo** [comment]
Fixed
