### ISSUE TITLE
Market Event error

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1801]
So about 25% of Market events get this error for me. Now there's nothing in the logs unless this LUA error is somehow it, doesn't seem like it could be, but modding doesn't always make sense to me: [42323.828] Runtime Error: C:\Users\James\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\UnitPanel.lua:1536: attempt to call method 'GetNumFriendlyUnitsOfType' (a nil value)

My modlist: Your six with EUI, FlagPromotionsV4, Civ Names by Policies, More Great Works, Great People Pack, Historical Generals, More Great Musicians, Ice Free Coasts, Celtic City Names, Iroquoian City Names, Randomize City Names, NoAltitudeTraining (removes the Mt. Kilman promo), and my own version of Wario's Rules, which right now only deletes Goddess of Protection, and sets Barbarian exp to -1.

![20160515232436_1](https://cloud.githubusercontent.com/assets/16260521/15279732/9232fd5e-1af5-11e6-99f4-46942424d1d0.jpg)

**Comment by LoneGazebo** [comment]
I'll look.
