### ISSUE TITLE
Religious National Wonders Mapsize

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1802]
I guess this is another weird error that only impacts some people but I'm still getting a strange number of pop needed on my Religious National Wonder for a Large Size map. I guess it could just be a UI thing and it actually builds at the right number? Like the other report, nothing in the logs unless its this: [42323.828] Runtime Error: C:\Users\James\Documents\My Games\Sid Meier's Civilization 5\MODS(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\UnitPanel.lua:1536: attempt to call method 'GetNumFriendlyUnitsOfType' (a nil value)

My modlist: Your six with EUI, FlagPromotionsV4, Civ Names by Policies, More Great Works, Great People Pack, Historical Generals, More Great Musicians, Ice Free Coasts, Celtic City Names, Iroquoian City Names, Randomize City Names, NoAltitudeTraining (removes the Mt. Kilman promo), and my own version of Wario's Rules, which right now only deletes Goddess of Protection, and sets Barbarian exp to -1.

![20160515234116_1](https://cloud.githubusercontent.com/assets/16260521/15279929/0d1ce64a-1af8-11e6-8e20-285035925e12.jpg)

**Comment by LoneGazebo** [comment]
@ilteroi, did we change GetNumFriendlyUnitsOfType?

Re: % religion issue, I'll see if I can reproduce.

**Comment by ilteroi** [comment]
re: GetNumFriendlyUnitsOfType

i renamed the C version of the function for clarity - the lua name should have been the same but it seems i introduced a spelling error ;)

**Comment by pandasnail** [comment]
Regarding the RNW issue-one thing that probably doesn't matter, but just in case: I believe last time I was 5th or 6th founded out of 6, and this time I was fifth founded out five.

**Comment by GrantSP** [comment]
@pandasnail did you know that FlagPromotions is up to version 7? I suggest you grab the latest copy.
Totally unrelated to the issue at hand, just a heads up.

**Comment by pandasnail** [comment]
Thanks!

**Comment by pandasnail** [comment]
So I was able to 'fix' this by opening up the Worlds SQL and changing all the ReformationPercentRequired to the number for Large (80). That dropped my percent needed 14%. It had started at 30%, and 16% makes sense for the Large requirement. So the problem is that its automatically reading whichever map size is 30%, not sure if that's Duel, Tiny, or Small. And of course I have no idea why its reading the wrong one.
