### ISSUE TITLE
Getting Great General and Great Admiral points from Colosseum

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1803]
Posted the other two when I thought I was done playing for the night, but I apparently I just can't stop. Anyway.

My modlist: Your six with EUI, FlagPromotionsV4, Civ Names by Policies, More Great Works, Great People Pack, Historical Generals, More Great Musicians, Ice Free Coasts, Celtic City Names, Iroquoian City Names, Randomize City Names, NoAltitudeTraining (removes the Mt. Kilman promo), and my own version of Wario's Rules, which right now only deletes Goddess of Protection, and sets Barbarian exp to -1.

![20160516002019_1](https://cloud.githubusercontent.com/assets/16260521/15280243/38e75be4-1afc-11e6-9e1e-f58ba8b1ca0b.jpg)

**Comment by pandasnail** [comment]
Apparently last night I forgot to go back and actually describe the screenshot after adding it and copying the modlist.

The Legion north of Mogadishu just killed a Barbarian Archer, which gave me both Great General and Great Admiral points. And this isn't a one time thing, as Most Observant One that I am, I didn't notice until I had killed enough to actually get the Admiral.

(This screenshot also kinda sorta shows the effect the 20 turn hordes are having. At least on a map annoyingly uncrowded, four have been sacked already)

**Comment by pandasnail** [comment]
Just adding real quick that its happening when I kill Major Civ units as well

**Comment by LoneGazebo** [comment]
I'll look.
