### ISSUE TITLE
Event Dramatic Masterpiece might not scale with gamespeed

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1805]
I can't be sure, but you get to chose 100 great writer points. 100 is no multiple of 3, so that indicates it isn't scaled. 
If it is scaled and just rounded to 100, nevermind.

**Comment by pandasnail** [comment]
The nomad event gives 100 Great Musician points too.

**Comment by LoneGazebo** [comment]
They don't scale. And they aren't intended to.

**Comment by Der-Zorn-Gottes** [comment]
I can't see why, as one-time yields are always supposed to scale, but your call of course.

A somewhat related observation:

The negative food event (-X food for a city) scales with era - the corresponding postive event (+X food for a city) is constant.

**Comment by LoneGazebo** [comment]
I was thinking of a different event. this is @hokath 's event, and his input is needed.

**Comment by Hokath** [comment]
Did you post this in the right thread, @LoneGazebo?

**Comment by LoneGazebo** [comment]
I did, sorry.

**Comment by LoneGazebo** [comment]
@Hokath, is there a link to your updated event repo for your events?
