### ISSUE TITLE
Trade routes display

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1806]
No big deal, but I have 2 traderoutes, while the indicator says 1/2.
![20160516103224_1](https://cloud.githubusercontent.com/assets/16065630/15291564/dac0bdac-1b7e-11e6-9109-f60051cab646.jpg)

**Comment by F0rst1** [comment]
The problem is that internal trade routes aren't shown in the indicator. International trade routes work as they should.

**Comment by ilteroi** [comment]
need to check this. i changed the behavior of a function to do what its name says but maybe this screen depends on the old behavior

**Comment by LoneGazebo** [comment]
@ilteroi  I believe it does, yes.

**Comment by ilteroi** [comment]
ah. anyway there was a bug in GetNumberOfInternalTradeRoutes(). maybe that fixes it already

**Comment by ilteroi** [comment]
ok. both stories are true :)

there's also a lua method lGetNumInternationalTradeRoutesUsed() which did not return the number of trade routes but the number of trade units. i "fixed" that but apparently that was a bad idea.

should be better now.
