### ISSUE TITLE
Explorer Movement

### ISSUE THREAD

**Issue by hyogodan** [LoneGazebo/Community-Patch-DLL#1807]
Troops move slowly - only one soldier at a time rather than as a group.

**Comment by ilteroi** [comment]
can you please give some more details?

**Comment by hyogodan** [comment]
Sure, usually when a unit moves, the individual "people' in it move
somewhat as a staggered group. With the new explorer unit the staggering is
delayed a lot more. Each individual "person" moves at the same speed as
usual, but the delay between each one starting to move is longer. Does that
help?

**Comment by LoneGazebo** [comment]
This was solved in the latest beta.

**Comment by hyogodan** [comment]
OK, thank you.
