### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by adman120** [LoneGazebo/Community-Patch-DLL#1809]
I am playing with a few mods installed and all of the sudden I will crash without getting an error msg or crash log. Mod list is below

(1) Community Patch
(2) Community Balance Patch
(3) CSD for CBP
(4) Civ IV Diplomatic Features
(5) More Luxuries
(6a) Community Balance Patch - Compatibility Files (EUI)
Ayyubid Civilization (v 2)
Barbarians - Unlimited Exp (v 2)
Buildings - Upgrade System (v 12)
dirlist.txt
JFD's The Anglo-Saxons (v 1)
JFD's The Archduchy of Austria (Joseph II) (v 1)
JFD's The Commonwealth of Iceland (v 2)
JFD's The Commonwealth of Poland-Lithuania (v 2)
JFD's The Confederation of Switzerland (v 5)
JFD's The County of Flanders (v 1)
JFD's The Dominion of New Zealand (v 1)
JFD's The Duchy of Milan (v 3)
JFD's The Duchy of Normandy (v 1)
JFD's The Electorate of Saxony (v 1)
JFD's The Empire of Byzantium (Alexios I Komnenos) (v 4)
JFD's The Empire of Germany (Hitler) (v 9)
JFD's The Empire of Great Britain (v 4)
JFD's The Empire of Japan (Meiji) (v 1)
JFD's The Empire of Japan (Tojo) (v 3)
JFD's The Empire of Rome (Constantine) (v 1)
JFD's The Empire of Russia (Alexander I) (v 1)
JFD's The Empire of Russia (Nicholas II) (v 3)
JFD's The Empire of Russia (Peter the Great) (v 4)
JFD's The Empire of Sweden (Karl XII) (v 2)
JFD's The Germans (v 2)
JFD's The Grand Duchy of Lithuania (v 1)
JFD's The Grand Principality of Muscow (v 1)
JFD's The Holy Roman Empire (v 2)
JFD's The Khazar Khaganate (v 2)
JFD's The Kingdom of Armenia (v 3)
JFD's The Kingdom of Bavaria (v 2)
JFD's The Kingdom of Belgium (v 1)
JFD's The Kingdom of Bohemia (v 3)
JFD's The Kingdom of Denmark-Norway (v 1)
JFD's The Kingdom of Egypt (Akhenaten) (v 1)
JFD's The Kingdom of Egypt (Djoser) (v 1)
JFD's The Kingdom of England (Henry VIII) (v 1)
JFD's The Kingdom of France (v 4)
JFD's The Kingdom of Francia (v 6)
JFD's The Kingdom of Hungary (v 8)
JFD's The Kingdom of Italy (Mussolini) (v 4)
JFD's The Kingdom of Italy (Victor Emmanuel III) (v 2)
JFD's The Kingdom of Norway (v 6)
JFD's The Kingdom of Prussia (v 16)
JFD's The Kingdom of Sardinia-Piedmont (v 2)
JFD's The Kingdom of Scotland (v 2)
JFD's The Kingdom of the Vandals (v 6)
JFD's The Kingdom of Two Sicilies (v 1)
JFD's The Merchant Republic of Novgorod (v 2)
JFD's The Nri Kingdom (v 1)
JFD's The Papal States (v 10)
JFD's The Republic of Carthage (v 4)
JFD's The Republic of France (Clemanceau) (v 2)
JFD's The Republic of France (v 1)
JFD's The Republic of Poland (v 1)
JFD's The Russian Federation (v 1)
JFD's The Soviet Union (Lenin) (v 3)
JFD's The Soviet Union (Stalin) (v 13)
JFD's The Turks (Mehmed II) (v 2)
JFD's The United Kingdom (George V) (with Greater Europe) (v 2)
JFD's The United Kingdom of Great Britain and Northern Ireland (v 5)
JFD's The United Kingdoms of Sweden-Norway (v 1)
JFD's The United States (Teddy Roosevelt) (v 2)
JFD's The United States of America (Lincoln) (v 2)
JFD's The United States of America (Roosevelt) (v 4)
MC's Oman Civilisation (v 2)
Promotions - Ancient Ruins Choice (v 2)
Promotions - Expansion Pack (v 9)
Resource - Granary Includes Bison (v 3)
Ressource - Mint Include Copper (v 2)
Terrain - Brazilwood Camp Extension (v 3)
Terrain - Chateau Extension (v 3)
Terrain - Feitoria Extension (v 3)
Terrain - Kasbah Extension (v 3)
Terrain - Moai Extension (v 3)
Terrain - Motte-and-bailey Fort (v 5)
Terrain - Polder Extension (v 3)
Terrain - Pontoon Bridge (v 3)
Terrain - Poor Tiles Tweak (v 2)
Terrain - Terrace Farm Extension (v 3)
Terrain - Tipi (v 5)
Units - Airship and Land Ironclad (v 3)
Units - No Futuristic Units (v 1)
Units - Scout to Explorer (v 10)
Units - Starting Scout (v 1)
Units - Throwing Axeman (v 4)
War - Less Damaged Captured Cities (v 3)

**Comment by ilteroi** [comment]
can you please post a minidump?

also, it would be very helpful to try and cut down on the active mods to try and isolate the cause.

**Comment by adman120** [comment]
https://drive.google.com/file/d/0B7aqskM1L56OX3JuTjIzWkFIbG8/view?usp=sharing

**Comment by LoneGazebo** [comment]
That many mods makes it nigh-impossible to debug. Try using only the CPP and see if it crashes. If it does, we know that it is a mod conflict causing the issue.
