### ISSUE TITLE
crash when loading savegame

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1810]
@LoneGazebo : did you do anything with CvTeam serialization?

i'm getting a crash on load, but only after turn 160 or so. earlier saves are fine.

offending line is 

	CvInfosSerializationHelper::ReadHashedDataArray(kStream, m_aiForceTeamVoteEligibilityCount, GC.getNumVoteSourceInfos());

**Comment by LoneGazebo** [comment]
No, I didn't.

**Comment by LoneGazebo** [comment]
@mwhiter did you edit anything in cvteam recently?

**Comment by mwhiter** [comment]
Not to my knowledge. Git blame it?

**Comment by ilteroi** [comment]
good idea. no change on that line since the original commit two years ago. weird

**Comment by mwhiter** [comment]
is it possible to isolate some sort of event that begins serializing data at that point in time?

**Comment by ilteroi** [comment]
i added sentinel values to the save via the INITWRITE macro and check them in INIT_WRITE to see when we start to lose synchronization. but it doesn't trigger ...

**Comment by ilteroi** [comment]
hmm. now it doesn't even crash anymore. guess that's a good thing ...
