### ISSUE TITLE
Invisible Cities

### ISSUE THREAD

**Issue by hyogodan** [LoneGazebo/Community-Patch-DLL#1811]
When founding a new city with a pioneer the city is invisible until the game is reloaded. It can be selected and works fine otherwise. This would be a purely cosmetic bug.

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict. Lua.log?

**Comment by hyogodan** [comment]
I'll check when I have a chance.

**Comment by Der-Zorn-Gottes** [comment]
I noticed invisible cities too.
No mods other than standard CPB suite.

**Comment by hyogodan** [comment]
Do yours re-appear upon reload?

**Comment by LoneGazebo** [comment]
I need lua logs for when it happens.

**Comment by hyogodan** [comment]
OK, next chance I get.

**Comment by ARose8245** [comment]
not original poster, but same issue; lua.log  as shown below has error in last three lines of log. error at (6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\CityBannerManager.lua:971 in this log, however on previous run when checking logs, the error was the same (ish) error but on line 984.
Both times it's a attempt to index nil value field error.
[Lua.log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/268704/Lua.log.txt)
