### ISSUE TITLE
Cultural victory not triggering

### ISSUE THREAD

**Issue by Guynemer** [LoneGazebo/Community-Patch-DLL#1813]
I became influential over all remaining civs in the game, but the victory did not trigger.  I did not turn off culture victory in the game options (unless I stroked out and I'm having amnesia).  I'm also using Quick Turns, InfoAddict, and the Promotion UI from Pick 'n' Mix.

[Iroquois.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/267539/Iroquois.zip)

**Comment by Der-Zorn-Gottes** [comment]
You need to have an ideology.

**Comment by Guynemer** [comment]
Well, shit.

IGNORE ME.
