### ISSUE TITLE
Game crashing on loading save

### ISSUE THREAD

**Issue by Shuuvkopeck** [LoneGazebo/Community-Patch-DLL#1814]
I haven't tried modding Civ5 yet so unfortunately I don't think I can figure out what the exact error is.  I enabled logging and poked around but didn't see anything obviously useful.  I tried going back and loading older saves from this game but it seems like they all crash too.  :(

[Pacal_0218 AD-1540.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/268237/Pacal_0218.AD-1540.zip)

**Comment by LoneGazebo** [comment]
Need a mini dump file. It'll be in your civ exe folder.

**Comment by Shuuvkopeck** [comment]
Thanks LoneGazebo.  Here is the dump file.  Good luck!

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/269450/CvMiniDump.zip)

**Comment by Shuuvkopeck** [comment]
Just to let you know it seems like I am having problems loading ANY modded save file right now.  Looking around it seems this is a pretty common problem with Civ 5.  I am trying to go through the many forum posts to try to find a solution that works.

**Comment by supermerill** [comment]
Did you load the mod before loading the save?

**Comment by Shuuvkopeck** [comment]
Yes, I have been doing that and it still isn't working.  From forum
searches it seems this is a relatively common problem with Civ 5 in general
but so far none of the various solutions I've seen have worked for me.  :(

**Comment by Vyyt02** [comment]
I wanted to try a few things first before posting a report on GitHub, but now that I saw your post, I will add my recent experience here. After taking a short break from CiVving I updated CBP to the latest stable version (March 9th (1.3.9)) and played for a couple of hours. The next day I realised that **right after starting the game** I was unable to load a save from my game which had progressed to the Renaissance era. I got the screen with the leader intro for like 10 seconds and then got a CTD - no minidump file.

So I thought the 1 save file was corrupt and tried an older save - the same result. Then I tried loading the save from turn 5 and it loaded fine. Then I tried quitting to the main menu and loading the latest Renaissance save and - to my surprise - it worked!!! At first, I thought it was just a coincidence, but I have tried the same procedure for maybe 10 times already and it is always the same: After starting the game, I always have to load the save from the beginning of the game, then quit to the main menu and then I can load the latest save. This always works, trying to load the latest save right after starting the game (and of course going to the mods menu) always results in a CTD.

Apparently something has changed during my break. It could be the graphic card drivers (nVidia) which got updated, it could be CiV (probably not, Firaxis are not updating it anymore, do they?), it could be something in the newest CBP which does not get along with my computer. I will try to update my drivers or setting the game details to the lowest next time.

Would you try starting a new game (with CBP?), and then loading a save from some very early turn? Maybe you have the same problem as me ... ?

**Comment by Shuuvkopeck** [comment]
Vyyt, you are a godsend.  That procedure did work for me.  The very first
save of one of my games I was able to load, and then I quit and was able to
load the most recent save.  I'm glad to hear I wasn't the only one with the
problem.

Do you think this might have something to do with the mod after all then?
I'm happy enough to have a work around but the process is a little
Byzantine.  :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Vyyt02** [comment]
Haha, good to know I was not going crazy! It is very strange, isn't it?

I tried updating my Nvidia drivers, but it did not help. Apparently only a minority of us are having this problem, so what do we have in common?

My machine is i7, 8 GB RAM, NVIDIA GeForce GT 740M. Playing on Win10, DirectX 11 - I am pretty sure I have played CBP (earlier version(s)) after I upgraded from Win8.1 to Win10 in December.

Are you using any other mods? I am using quite a lot of mods, but they worked fine with CBP before.

And yes, I agree, the process is Byzantine - maybe because I am currently playing as Theodora :-)

**Comment by Shuuvkopeck** [comment]
I've got Windows 7 64 bit, DirectX 11, an Nvidia GeForce GTX 970 on a
fairly fresh install.  My drivers are current.  The only other mod I am
using is Ingame Editor.  Other than that the only oddity I can think of is
that I am not using the EUI part of CBP.  I have the Steam version of Civ5
with all the DLC.

Not sure what else to say.  I won a Mayan game I thought I would not be
able to finish thanks to your help.  :)

**Comment by Vyyt02** [comment]
Glad it worked for you! :-)

Yeah, good point, I am also playing without EUI and I do have IGE in the mods folder, but it is not active.

So what we have in common so far is:
- Nvidia graphics
- DirectX 11
- No EUI
(- IGE present in mods folder, but I do not think it matters)

Anyway, Gazebo mentioned fixing several CTD related issues in the changelog of the newest beta, so let's try it out first.

**Comment by Edaka** [comment]
Let's if that issue persists for you guys in the latest beta, then.

**Comment by Shuuvkopeck** [comment]
From looking at the change log I am hopeful.  I will try it as soon as I
finish my current game and let you know.

**Comment by alonrash** [comment]
After a long game that I could'nt load, I almost gave up about the patch.
Thanks for this amazing (?) solution!
I don't use the EUI, like you. Did you try to install the EUI in order to see if it resolves the problem?
More importantly - Does someone know if it is being checked by the developers? It's pretty frustrating, despite the solution.

**Comment by Vyyt02** [comment]
I updated to the latest version (5/21) played about 86 turns yesterday. I tried loading the latest save today and I am getting no CTDs. So I am cautiously optimistic that the issues Gazebo has fixed in the newest release fixed our load related problems as well.

**Comment by Edaka** [comment]
Did you get to the Renaissance era? Good news anyway! (:

**Comment by Vyyt02** [comment]
No, unfortunately not and I won't have time to play for about 2 weeks now. However, the CTDs after load had started much earlier than Ren for me before, so I think we are safe here. Also, I cannot see more load-related-CTD reports from other people neither on GitHub nor CivFanatics anymore, so I believe/hope this issue has been resolved.

**Comment by Edaka** [comment]
Let's hope so, then.
