### ISSUE TITLE
war elephant doesn't cost ivory

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1815]
although the tooltip says so

**Comment by TechpriestEnginseer** [comment]
Doesn't it just require ivory rather than cost ivory?

**Comment by ilteroi** [comment]
hmm. possible but unexpected. i think it would be the only unit to behave that way?

**Comment by LoneGazebo** [comment]
It is the only unit to behave that way, yes. Intentional.

**Comment by ilteroi** [comment]
ah. now i see. ivory is a luxury resource ... guess it's fine then
