### ISSUE TITLE
Formation and Battle Preview

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#1816]
![20160517173138_1](https://cloud.githubusercontent.com/assets/11430209/15340888/cb8301ca-1c59-11e6-85b2-847e649dc362.jpg)

Formation says it gives +25% but it's actually +33%  ( 50% base plus 2 33% promtions)

![20160517171441_1](https://cloud.githubusercontent.com/assets/11430209/15340891/cdddc81a-1c59-11e6-895f-5c10d2bcff75.jpg)

As you can see the bonus vs Mounted Range units doesn't show how much Formation and the Spears bonus is but is still being factored in

**Comment by LoneGazebo** [comment]
That's because the UI can't account for 'melee' promotions in a ranged situation. It is odd and dumb.

**Comment by LoneGazebo** [comment]
I'll fix formation I/II though.
