### ISSUE TITLE
Catapult can melee attack

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#1817]
Mistakenly moved a catapult to an adjacent enemy spearman without setting up prior, it killed and occupied the position. It seems to perform melee combat with RCS and its modifiers.

**Comment by ilteroi** [comment]
my bad. but i like to do fixes before breakfast.

**Comment by Edaka** [comment]
I might add that you can also melee attack an adjacent unit with a ranged ship out of a city. Got my dromon killed by a knight like that. (Don't ask why I tried to bombard from a city - still haven't got used to the fact ships can't do that anymore.)

**Comment by ilteroi** [comment]
yeah. same root cause.
