### ISSUE TITLE
Game crashes immediately after turn 9

### ISSUE THREAD

**Issue by Hesh71** [LoneGazebo/Community-Patch-DLL#1818]
When starting a new game, the game works perfectly until in between turns 9 and 10, when it immediately crashes to the desktop.
Other details: I'm playing as the Ottomans on a continents map on warlord difficulty and standard speed.

I will get the dmp file as soon as possible.

**Comment by Hesh71** [comment]
I forgot to mention that I'm using the Ethnic skins mod as well.

**Comment by Slobodan85** [comment]
I also had a straight crash to desktop on turn 9 today, coincidental or not?

Loading the autosave allowed me to continue though.

I wasn't running any mods besides the latest CBP and used planet simulator mapscript.

**Comment by Hesh71** [comment]
Good to know, I'll try that and see if it works out.

**Comment by Edaka** [comment]
Gazebo reported that he'd done some work on CTDs in the latest beta, you guys should see if it still crashes as before. Minidumps from an older version wouldn't be useful now.
