### ISSUE TITLE
Quest reward and resource monopoly values not shown in notifications

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1819]
Playing with the latest beta (5/14), Vox Populi with EUI and a bunch of other mods (that haven't been known to cause the issue previously).

Now, I haven't played in a while, but I recall whenever a city state quest emerged or got completed, a popup notification would inform you of what yields and how many or them you got as a reward. Same with monopolies - when somebody got one, a notification would inform of associated the monopoly bonus. In the current iteration, however, the notifications no longer contain information about that.

I suppose it might be due to the latest EUI - is anybody having the same issue without it? I might try the non-EUI version myself later on.

**Comment by LoneGazebo** [comment]
Not sure – works fine for me, I'd blame it on the increasingly-opaque EUI.

**Comment by Edaka** [comment]
Yeah, it works without EUI. Not going to fix, I assume?
