### ISSUE TITLE
AI's sometimes agree to declare war for free

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#182]
Observed three times in two games. 

1 - Gajah agrees to declare war on denounced enemy for free, already in another war.
2 - Alexander agrees to declare war on neighboring enemy who has top army. No other wars.
3 - Attila agrees to declare war on 4 out of 4 civs for free. Already in war with another civ.

Have save for occurences 2 and 3, it's the same save from a game started with 3-30 and continued with 4-1.

**Comment by LoneGazebo** [comment]
Thanks, I'll take a look. In the meantime, just don't abuse the poor AI, eh? :)
G

**Comment by LoneGazebo** [comment]
Fixed. Missing a multiplication bit.
