### ISSUE TITLE
Hurricane event notification bug

### ISSUE THREAD

**Issue by Slobodan85** [LoneGazebo/Community-Patch-DLL#1820]
When I get the hurricane event and can only pick the option to do nothing, I get a false notification that the event did not occur, even if it did.

**Comment by LoneGazebo** [comment]
The event may occur, but the population loss will not. That's what the 'did not occur' references.

**Comment by TechpriestEnginseer** [comment]
Wish we had a custom text file called FailedMessage like DisabledTooltip.

**Comment by LoneGazebo** [comment]
I think @jfdaly has one.

**Comment by Slobodan85** [comment]
Actually, I meant the situation where population loss *does* occur, but the notification still says otherwise.

**Comment by Slobodan85** [comment]
I had this event again and this time the notification correctly said "A hurricane has struck Delhi etc."

However, I'm puzzled by how to meet the criteria for preparing? I had more than enough gold, but none of the other options were available? In fact, I've never seen them available.

**Comment by LoneGazebo** [comment]
Tech requirements.
