### ISSUE TITLE
Iroquois Longhouses & Goddess of Renewal

### ISSUE THREAD

**Issue by kriskow** [LoneGazebo/Community-Patch-DLL#1821]
Bug Report Template

Mod Version (i.e Date - (4/23b)): CPProject Full EUI 3/9

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Iroquois Longhouses don't get the herbalist building enhancement from the Goddess of Renewal pantheon pick.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
What's the problem? You didn't say.

**Comment by LoneGazebo** [comment]
They're a buildingclass, so they should. There's no reason for it not to work. Probably an EUI issue.
