### ISSUE TITLE
AI getting extra trade routes

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1822]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/14

1. Mod List (if using standard CPP set, leave blank):Your six with EUI, FlagPromotionsV4, Civ Names by Policies, More Great Works, Great People Pack, Historical Generals, More Great Musicians, Ice Free Coasts, Celtic City Names, Iroquoian City Names, Randomize City Names, NoAltitudeTraining (removes the Mt. Kilman promo), and my own version of Wario's Rules, which right now only deletes Goddess of Protection, and sets Barbarian exp to -1.

2. Type of error (i.e. crash, interface bug, AI quirk): I don't know if this is related to the other trade route stuff, which I thought was just a display thing, or if this is actually an AI (emperor level) enhancement I never knew about, but Catherine and Wash have 7 trade routes with me even tho by tech they should have at most 4. Neither has Petra or Colossus either.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![trade](https://cloud.githubusercontent.com/assets/16260521/15414540/749c5d50-1e09-11e6-8370-faa144cf2ef8.jpg)

**Comment by Edaka** [comment]
I think this was most probably related to the trade route bug that Ilteroi has fixed. Could also be due to that merchant event. Either way, since the root cause is probably elsewhere, I'll close.
