### ISSUE TITLE
Maori warrior

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#1823]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/14

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

I'm not sure if this is a bug but I noticed that Maori warrior doesn't have bonus vs. mounted, even though it replaces pikeman. I wonder if they should have it and it was forgotten to add when it became a pikeman replacer instead of a longswordman replacer.

**Comment by LoneGazebo** [comment]
It has a general bonus versus all units. Intended.
