### ISSUE TITLE
Futher issue with GetDenounceMessage() in latest version

### ISSUE THREAD

**Issue by Typhlomence** [LoneGazebo/Community-Patch-DLL#1826]
This is a follow up to https://github.com/LoneGazebo/Community-Patch-DLL/issues/1660

In that issue, I had suggseted that some of the if statements that returned values for denouncing based on ideology be changed from **m_pPlayer->GetPlayerPolicies()->GetLateGamePolicyTree()** to **GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree()**.

It was my intention to suggest that only the statements that returned values 4, 5 and 6 be changed to use GET_PLAYER(ePlayer). However, in the newest committed code, this is changed for the ones that returned 1, 2 and 3 as well.

I apologise if my previous issue wasn't clear on this point. The final code for that whole section should be:
```
// Guy is a different ideology
if(GetDiploBalance() > 5 && (GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree() != GetPlayer()->GetPlayerPolicies()->GetLateGamePolicyTree()) && (GetPlayer()->GetPlayerPolicies()->GetLateGamePolicyTree() != NO_POLICY_BRANCH_TYPE) && (GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree() != NO_POLICY_BRANCH_TYPE) && GET_PLAYER(ePlayer).GetCulture()->GetPublicOpinionPreferredIdeology() == m_pPlayer->GetPlayerPolicies()->GetLateGamePolicyTree())
{
	if(m_pPlayer->GetPlayerPolicies()->GetLateGamePolicyTree() == GC.getPOLICY_BRANCH_AUTOCRACY())
	{
		return 1;
	}
	else if(m_pPlayer->GetPlayerPolicies()->GetLateGamePolicyTree() == GC.getPOLICY_BRANCH_ORDER())
	{
		return 2;
	}
	else if(m_pPlayer->GetPlayerPolicies()->GetLateGamePolicyTree() == GC.getPOLICY_BRANCH_FREEDOM())
	{
		return 3;
	}
}
else if(GetDiploBalance() > 5 && (GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree() != GetPlayer()->GetPlayerPolicies()->GetLateGamePolicyTree()) && (GetPlayer()->GetPlayerPolicies()->GetLateGamePolicyTree() != NO_POLICY_BRANCH_TYPE) && (GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree() != NO_POLICY_BRANCH_TYPE) && m_pPlayer->GetCulture()->GetPublicOpinionPreferredIdeology() == GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree())
{
	if(GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree() == GC.getPOLICY_BRANCH_AUTOCRACY())
	{
		return 4;
	}
	else if(GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree() == GC.getPOLICY_BRANCH_ORDER())
	{
		return 5;
	}
	else if(GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree() == GC.getPOLICY_BRANCH_FREEDOM())
	{
		return 6;
	}
}
```

**Comment by LoneGazebo** [comment]
Thanks! Yep, misunderstood your suggested fix.

**Comment by Typhlomence** [comment]
I'm not quite sure where I should put this so you could see it, so hopefully you do so here.

I was looking through CvDiplomacyAI.cpp again, and I think I just found that the changes I asked you to make in there were unnecessary.

It turns out, there are _two_ sets of the checks for which denounce response was chosen. I was looking at the _first_ one, which now I see to be some sort of fall back when the ePlayer parameter passed to the function equals NO_PLAYER. I don't think the changes will cause any new errors, though, since ePlayer _is_ given a value (of the currently active player) in this occurence.

The _second_ copy of the "denounce based on ideology" code that's in the "else" part of that statement (which is what will generally be used) actually seems to have been correct all along. It's currently (I believe) lines 27292 to 27322, and is identical to what it was when I first reported the issue, as I still had the old version of .cpp file around to check.

```
// Guy is a different ideology
if(GetDiploBalance() > 5 && (GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree() != GetPlayer()->GetPlayerPolicies()->GetLateGamePolicyTree()) && (GetPlayer()->GetPlayerPolicies()->GetLateGamePolicyTree() != NO_POLICY_BRANCH_TYPE) && (GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree() != NO_POLICY_BRANCH_TYPE) && GET_PLAYER(ePlayer).GetCulture()->GetPublicOpinionPreferredIdeology() == m_pPlayer->GetPlayerPolicies()->GetLateGamePolicyTree())
{
	if(m_pPlayer->GetPlayerPolicies()->GetLateGamePolicyTree() == GC.getPOLICY_BRANCH_AUTOCRACY())
	{
		return 1;
	}
	else if(m_pPlayer->GetPlayerPolicies()->GetLateGamePolicyTree() == GC.getPOLICY_BRANCH_ORDER())
	{
		return 2;
	}
	else if(m_pPlayer->GetPlayerPolicies()->GetLateGamePolicyTree() == GC.getPOLICY_BRANCH_FREEDOM())
	{
		return 3;
	}
}
else if(GetDiploBalance() > 5 && (GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree() != GetPlayer()->GetPlayerPolicies()->GetLateGamePolicyTree()) && (GetPlayer()->GetPlayerPolicies()->GetLateGamePolicyTree() != NO_POLICY_BRANCH_TYPE) && (GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree() != NO_POLICY_BRANCH_TYPE) && m_pPlayer->GetCulture()->GetPublicOpinionPreferredIdeology() == GET_PLAYER(ePlayer).GetPlayerPolicies()->GetLateGamePolicyTree())
{
	if(GET_PLAYER(ePlayer).GetCulture()->GetPublicOpinionPreferredIdeology() == GC.getPOLICY_BRANCH_AUTOCRACY())
	{
		return 4;
	}
	else if(GET_PLAYER(ePlayer).GetCulture()->GetPublicOpinionPreferredIdeology() == GC.getPOLICY_BRANCH_ORDER())
	{
		return 5;
	}
	else if(GET_PLAYER(ePlayer).GetCulture()->GetPublicOpinionPreferredIdeology() == GC.getPOLICY_BRANCH_FREEDOM())
	{
		return 6;
	}
}
```

As far as I can tell, though, the change in NewText.xml was still necessary, so my original report ([#1660](https://github.com/LoneGazebo/Community-Patch-DLL/issues/1660)) still managed to fix a bug.

Sorry for the inconvenience! I should have checked the code more carefully before making my initial report.

**Comment by LoneGazebo** [comment]
No worries. So where do we stand on this, @Typhlomence ?

**Comment by Typhlomence** [comment]
Hi Gazebo, sorry for not replying earlier.

However, I don't think any further action is needed anyway, since the actual behaviour is what it should be, and even though the code I asked you to change was incorrect, I'm not sure that will either crash or even be run anyway since I'm not sure there would be a circumstance in normal gameplay where the game tries to get a denounce message without a leader.

As long as you have kept the changes in NewText.xml so that the messages appear at the correct times, there shouldn't be any problems.

Thank you for your attention.

**Comment by LoneGazebo** [comment]
Sounds good thanks!
