### ISSUE TITLE
Strange DOW situations

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#183]
I was playing as Byzantium, denounced Marco and declared war on them.
I then tried to attack their dromon. The first attack triggered a "do you want to go to war" pop up while I was already in war. I declared again, and attacked the ship. Then the second ship I had tried to attack.
I go the same "do you want to go to war" pop up, only I could no longer declare war, I was sent to the diplomacy discussion screen where I could not do anything but exit, try to attack again etc...
Next turn I did no longer have this problem.

I also get from time to time crashes to desktop.
I am using EUI, E&D, have followed all the instructions faithully for the instalations.
I do not use other mods.

**Comment by LoneGazebo** [comment]
I fixed this in the 4/1 version - update to the latest version for the fix.
G
