### ISSUE TITLE
Conquered Arenas aren't becoming Colosseums 

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1831]
Bug Report Template

Mod Version (i.e Date - (4/23b)):5/14

1. Mod List (if using standard CPP set, leave blank): Your six with EUI, FlagPromotionsV4, Civ Names by Policies, More Great Works, Great People Pack, Historical Generals, More Great Musicians, Ice Free Coasts, Celtic City Names, Iroquoian City Names, Randomize City Names, NoAltitudeTraining (removes the Mt. Kilman promo), and my own version of Wario's Rules, which right now only deletes Goddess of Protection, and sets Barbarian exp to -1.

2. Type of error (i.e. crash, interface bug, AI quirk): Is this how the UA is supposed to work? Kinda weird if so.
![arena](https://cloud.githubusercontent.com/assets/16260521/15442172/59c4863e-1ead-11e6-8a26-4414ab0e811a.jpg)

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Yep - if the building is valid it won't replace it.
