### ISSUE TITLE
Submarines getting Coastal Raider

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1833]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21

1. Mod List (if using standard CPP set, leave blank): Non EUI VP and the Whoward promotion tree

2. Type of error (i.e. crash, interface bug, AI quirk): Submarines can pick Coastal Raider, which I thought was for Melee only, and also makes them I believe the only unit with three basic promotions (targeting and wolfpack the others). Apologies if intentional.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![sub](https://cloud.githubusercontent.com/assets/16260521/15450128/eed16350-1f61-11e6-9ff9-8f076bcc444e.jpg)

**Comment by TechpriestEnginseer** [comment]
That's new. Submarines invading cities. Perhaps they do some embargo but other than that...

**Comment by LoneGazebo** [comment]
International.

**Comment by LoneGazebo** [comment]
Intentional. Stupid phone. :)

**Comment by LoneGazebo** [comment]
To explain, since we can't have 'commerce Raiders' as a concept, I thought it made sense to have subs gain this role somewhat.

**Comment by pandasnail** [comment]
Okay. On the subject, the Whoward UI doesn't work for subs, did you add a fun new promotion for Wolfpack as well?

**Comment by LoneGazebo** [comment]
No, because they got coastal raider and its tier 4.

**Comment by pandasnail** [comment]
Makes sense

**Comment by LoneGazebo** [comment]
I might add one for them later though.
