### ISSUE TITLE
War Weariness

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1834]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21

1. Mod List (if using standard CPP set, leave blank): Non EUI VP and the Whoward promotion tree (which shouldn't be required if you open the save)

2. Type of error (i.e. crash, interface bug, AI quirk): I mentioned this somewhere else, but before I disappear to watch the French Open all day for two weeks, I wanted to do a test game to show how I just never get War Weariness. I started in the Modern Era and declared war on all five other civs once i met them. 75 or so hitting next turns later, USA has 12 war weariness, Mongolia 6, Persia 5, Sweden 5, Mayans 6, and me as Portugal 0. And I've been at war with all five while they haven't fought each other at all (don't actually know if number of enemies matters). And before you say that an RNG can get zero over and over, this is what always happens in both regular games and in test games. I used to assume it was just me and whatever I do hardly play the Modern Era, but some of the other things I thought were my awful computer turn out to reported by someone else, like I knew about Kasbahs not improving new Coal awhile before that was reported. So I'm trying to report everything now. 

I included the save and the lua log, which as far I can see has nothing, only that weird thing where it says 'not activated' when I DoW. That may make sense to someone who knows modding of course.

ie [82146.718] DiscussionDialog: DiploUIStateTypes.DIPLO_UI_STATE_WAR_DECLARED_BY_HUMAN
[82146.718] DiscussionDialog: DiploUIStateTypes.DIPLO_UI_STATE_WAR_DECLARED_BY_HUMAN NOT activated in DiscussionDialog

I also believe I have every single logging option enabled, so if there's something else that might be helpful, let me know.

Also, me declaring on new City States allies of my enemies worked fine in this game, must be pretty rare whatever it is.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed [portugalww.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/276009/portugalww.zip)
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![ww](https://cloud.githubusercontent.com/assets/16260521/15450424/19de0f4c-1f69-11e6-80c6-0aed483b0a4a.jpg)

**Comment by LoneGazebo** [comment]
@ilteroi mind taking a look?

**Comment by MoiMagnus** [comment]
Similar issue for me (but in an old beta, from the 23.03), in epic.
I was at war without break from late classic to atomic era, and after less than 10 turn of peace, I was again at war until the end of the game (mid information era), and no war weariness at all.

I don't know if it change someting, but I was even at war with somebody popular on me (and I was exotic on him), and he had war wearriness but not me.

**Comment by LoneGazebo** [comment]
@ilteroi, any thoughts on why war weariness stopped working?

**Comment by ilteroi** [comment]
it seems GetTurnIdeologyAdopted() returns -1 although the player has an ideology. next level of mystery

**Comment by LoneGazebo** [comment]
Great. I'll be merging and uploading everything this evening. 

G
