### ISSUE TITLE
Broken user interface.

### ISSUE THREAD

**Issue by Splendide-Mendax** [LoneGazebo/Community-Patch-DLL#1836]
Bug Report Template

Mod Version V. 72

1. Mod List 
-Community patch v. 72
-Ancient Building Pack
-City Limits V7
-CSD for BNW
-Civ V Focused AI
-Community Balance Patch
-Civ IV Diplomatic Features - CBP Edition
-Community Balance Patch -Compatibility Patch 

2. Type of error (i.e. crash, interface bug, AI quirk): 
No unit interface and cannot select units, although can move them by right click and dragging for a route.  Makes game unplayable of course, since I can't even make my first city xD

3. Steps to reproduce:
-Install Civ V with all DLC and above modlist, as well as Com-Patch-DLL

4. Additional Information:
-Fresh installed game and all required mod files, same error occured.
---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

Game does not crash, simply lacks user interface.
![list of current mods](https://cloud.githubusercontent.com/assets/12070792/15452196/73fc53d0-1fb4-11e6-9e54-94b393749171.png)
![ingame](https://cloud.githubusercontent.com/assets/12070792/15452199/78822d9e-1fb4-11e6-95ff-964535bb8078.png)

**Comment by TechpriestEnginseer** [comment]
Don't you need to use the CSD for CBP? not the standalone CSD?

**Comment by Splendide-Mendax** [comment]
What do you mean O.o I am using City State Diplomacy for Brave New World.

Also, it's giving me a new error now.  It's not letting me activate the Community Balance Patch because it's missing the Civ IV Diplomatic Features (V.11) dependency which I cannot activate because it's blocked by the Community Balance Patch (V.72).  Why are the mod's blocking their own dependencies?

**Comment by TechpriestEnginseer** [comment]
![image](https://cloud.githubusercontent.com/assets/13937047/15452498/1b3720d6-1fa5-11e6-9c07-a97e9e0b3aab.png)
Yours should be looking like this.

**Comment by Splendide-Mendax** [comment]
I install via Steam, not manually.  What folder of the Civ V directory is the mod folder under?
Also, could you give me a vip of the mods so I could install that way, since installing them via Steam seems to be broken?

**Comment by TechpriestEnginseer** [comment]
Why don't you use the installer? Much more convenient.
![image](https://cloud.githubusercontent.com/assets/13937047/15454810/69dbd040-1ff7-11e6-8cbd-a973f4cf7aa5.png)

**Comment by Splendide-Mendax** [comment]
What installer?  I've never heard of it.

**Comment by TechpriestEnginseer** [comment]
https://mega.nz/#!DB1gSCoD!NSmMmKHD5bbnMIxK5ZDIj8F_F_4lsTsK7Aj_F_pUYBI

**Comment by Splendide-Mendax** [comment]
Oh, that one.  Thought you had some mod manager I'd never heard of.
I've tried that installer 3 times on 3 fresh installs.  Just did it again.  Here's the results after activating the freshly installed mods ingame.

![image](https://cloud.githubusercontent.com/assets/12070792/15460002/4402c018-2079-11e6-95fa-9f83a9f804c9.png)
![image](https://cloud.githubusercontent.com/assets/12070792/15460035/8dd203b6-2079-11e6-9f72-e66d0fd243c0.png)

**Comment by TechpriestEnginseer** [comment]
I'd like your lua.log when you start the game like this again. This must be related to the UnitPanel.lua somehow if you're using a fresh install.

**Comment by Splendide-Mendax** [comment]
Location and file type?

**Comment by TechpriestEnginseer** [comment]
http://forums.civfanatics.com/showthread.php?t=487482

**Comment by Splendide-Mendax** [comment]
Here ya go.  It won't let me upload it here, so here's a link.
http://www.filedropper.com/logs_4

**Comment by TechpriestEnginseer** [comment]
Read the link again thoroughly, your Lua log should not be empty.

**Comment by Splendide-Mendax** [comment]
Okay, so which mod should I leave disabled?  The only mods I have enabled are the ones related to the Community Patch.

**Comment by TechpriestEnginseer** [comment]
That's not what I meant.

**Comment by Splendide-Mendax** [comment]
I know.  Just wanted to check on whether I should just start the game with all mods enabled.

**Comment by Splendide-Mendax** [comment]
Here ya go.  Followed instructions.
http://www.filedropper.com/logs_5

**Comment by Edaka** [comment]
Oddly enough, your Lua log is still empty. Still, judging by your screenshots you don't seem to have the right CSD installed. Looks like you'll have to try manual installation. Download '(3) CSD for CBP' from the link Enginseer provided.
![untitled](https://cloud.githubusercontent.com/assets/12978597/15534395/442c7404-2271-11e6-8f6a-72fcbd0797dd.png)
Then place it in Documents/My Games/Sid Meier's Civilization 5/MODS. Remove the old 'CSD for BNW'. Then delete the contents of cache folder (Documents/My Games/Sid Meier's Civilization 5/cache). Start a game and see if you still have the problem.

**Comment by Vyyt02** [comment]
In my experience, CiV can sometimes get wonky when you mix up mods subscribed via Steam with manually installed mods. The game strangely combines them or re-downloads manually deleted mods, etc. I would suggest doing the following before you start something complicated:

1) Unsubscribe from CSD for BNW at Steam
2) Delete any remnants of CSD in your MODS folder if there are any
3) Delete all the Community Patch related folders in the MODS folder
4) Delete the Cache folder and ModUserData as well
5) Run the auto-installer again

(all the above mentioned folders are in \Users\Your_username\Documents\My Games\Sid Meyer's Civilization 5\)

Also, when you debug, please do not use the other mods - do not know what "Civ V Focused AI" is, but suspect it may not be compatible or at least won't be balanced with the Community Balance Patch.

Just curious - can you found a city by pressing "B"?

**Comment by TechpriestEnginseer** [comment]
I'm wondering if he didn't unsubscribe the CSD for BNW which then replaced the CSD for CBP

**Comment by Edaka** [comment]
Oh yeah, that could be it. Didn't think about that. It's better to follow Vyyt's instructions, he's got it all covered (:

**Comment by tomKent2** [comment]
Good morning, 
hopefully you will be able to help me as my problem seems similar.I am new to steam and civization so not sure what is CSD / BNW

here is my problem: 

 I have just installed Steam and Civilization V brave new world (included a few DLC as we bought a "pack" for Christmas). We have a Windows 10 up to date). There is absolutely nothing on the left bottom corner. All we have is: on the right bottom corner, the "next turn" window but we can't click on it; if i click on "help" , nothing will open; if i try to access the "settlers" unit via the left top menu, nothing happens / nothing displays. If we exit the Civ game, we can not restart it without restarting the computer ( windows let me know that "app already running"). 
we also have difficulty to access the Task manager once Civilization V is running,..


I have tried to verify the game (no problem detected)
then I have tried to delete Civilization V and reinstall: problem still present
then i have tried to uninstall both civilization and Steam and delete the directory "My games/Sid Meier's Civilization 5"; I reinstalled Steam , Civ V and the problem is still here (running in admin mode, virus / firewall have been stopped).

I use the "recommended option for windows with touch enable"; then we use the top first option "start game" .

would anybody be able to point where I can find a solution? thanks

**Comment by TechpriestEnginseer** [comment]
Same thing as my response, did you use the installer?

**Comment by tomKent2** [comment]
Thanks for the quick reply. could you point out where to find the installer? thanks , very appreciated

**Comment by tomKent2** [comment]
hi could you point out where to find the installer? the "community patch does not have any installer... Thanks

**Comment by supermerill** [comment]
You can have the latest link to the installer here (for now).
https://forums.civfanatics.com/threads/new-version-december-13th-12-13.607229/
When installing, the program will ask you what to install, choose "community patch only" (if it's what you want).

If you used the steam workshop method, it should work fine. Be sure to only activate mods that are compatible with each other. If you see some problems, try to remove some mos to see if there are some compatibility problems.
