### ISSUE TITLE
Religion Enhancement Glitch

### ISSUE THREAD

**Issue by kriskow** [LoneGazebo/Community-Patch-DLL#1839]
Bug Report Template

Mod Version (i.e Date - (4/23b)):  CPProject Full EUI 3/9
1. Mod List (if using standard CPP set, leave blank):
2. Type of error (i.e. crash, interface bug, AI quirk):
Unable to continue game.
3. Steps to reproduce:
Played multiplayer game as the Ottomans, got a pantheon but did not get a religion before they were all founded.  Conquered England whom had founded Protestantism in London and also received a Great Prophet there as well.  Protestantism was showing in my (Ottomans) religion panel as a founded religion and the great prophet had the enhance religion ability available so i tried to enhance Protestantism.  Instead of enhancing the religion though, I was prompted to start a new one which i could not do because they had all been founded, thus creating a condition in which the game could not be progressed without reloading a previous autosave.

4. Additional information:
I'm not sure which part was functioning as intended and which was not.  If you do not have a religion and conquer another civ, are you supposed to gain theirs in the religion panel?  Was the prophet supposed to enhance Protestantism or was this ability supposed to be suppressed?  Save game file attached (I think):

[2016 CEP Weather.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/276332/2016.CEP.Weather.zip)

Thanks for all of your hard work.  Always happy to provide any additional information if it help.  :)
---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Using modpack or standard install?

**Comment by kriskow** [comment]
It's in the assets\DLC folder per the instructions. We all installed the same thing the same way. If there's a more recent (stable) patch or other method of installation we'd all be happy to give it a try. There's six of us who have been regularly playing CiV together for years.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by Edaka** [comment]
3/9 is quite an old version, and the bug you've described has been fixed in the latest beta versions. I'd suggest you try one of those.
