### ISSUE TITLE
Game freeze on setup screen (civilopedia)

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#184]
Using the 4/1 version, game seems to be working fine. Twice now I've clicked something on the game setup screen (for example, a unit or leader to take me to the civilopedia entry) and I get the attached screen. I have to manually close out of the game with something like task manager to get it to close.
![2015-04-02_00006](https://cloud.githubusercontent.com/assets/11132095/6977166/af20fc8c-d97d-11e4-82aa-caae71540533.jpg)

**Comment by LoneGazebo** [comment]
that's because some dll functions don't load until the game core is activated. This is a byproduct of EUI integration.
G
