### ISSUE TITLE
Drill to medic

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#1840]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Drill promotion line doesn't unlock medic I. I've got a unit with drill II who can't get medic even though in the previous version you could get medic with drill I. There is no mention of this change in the changelog, so I think it must be a bug.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

![20160522180838_1](https://cloud.githubusercontent.com/assets/18663580/15454670/42c62e5a-2048-11e6-872e-557c4fe1b101.jpg)

**Comment by LoneGazebo** [comment]
Intentional. Balance changes.
