### ISSUE TITLE
Barbarian horsemen

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#1841]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Some barbarian horsemen have 14 CS, should be 15. Those with 14 CS don't consume any horses when you capture them as Attila. I think I saw some with 15 CS in the previous version of the mod, even though the bug has been there before, so I'm not sure if all barbarian horsemen are bugged (although I'm not sure if it's possible that only some of them are).

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

![20160523052414_1](https://cloud.githubusercontent.com/assets/18663580/15470932/00b4d200-20fc-11e6-8974-5b43f875e656.jpg)
![20160523052500_1](https://cloud.githubusercontent.com/assets/18663580/15470934/07d7bb6a-20fc-11e6-8600-8a50de6c7a75.jpg)

**Comment by LoneGazebo** [comment]
Barb horses don't cost horse.

**Comment by LoneGazebo** [comment]
Barb horses have 1 point higher CS than normal horses.
