### ISSUE TITLE
Event doesn't seem to scale

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1842]
Bug Report Template

Mod Version 5/21:

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

 An event called Rich Vein doesn't seem to scale properly as the game progresses. At turn 355 one of the options is +2 culture per turn in a city for 40 turns when my overall culture per turn is 1500+.

**Comment by LoneGazebo** [comment]
It is not supposed to.

**Comment by saamohod** [comment]
I see. But it seems a bit underwhelming at this time in game. +2 culture for 40 turns when average gain per turn is in hundreds and leaders like me (Aesthetics finished) make more than 1500 per turn. Not sure I see a point of bothering with such an insignificant event.
