### ISSUE TITLE
Another EventChoice request

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1844]
Please could there be a form of 
`EventChoice_FeatureYieldChange`
which affects river tiles?

Many thanks

**Comment by LoneGazebo** [comment]
No, because rivers aren't features. That's an expensive check. Easier to use the building to give a free dummy building for it.

**Comment by Hokath** [comment]
Ok!

Sent from Yahoo Mail on Android 
 
  On Mon, 23 May, 2016 at 20:26, LoneGazebo<notifications@github.com> wrote:   
No, because rivers aren't features. That's an expensive check. Easier to use the building to give a free dummy building for it.
