### ISSUE TITLE
Mandatory DoW for entering CS lands

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#185]
Using 4/1 version, mods on How to Install page minus Health and Plague.
.
![2015-04-03_00001](https://cloud.githubusercontent.com/assets/11132095/6989479/78a5b9e6-da21-11e4-8ceb-943af2c50038.jpg)
No reason I shouldn't be able to enter La Venta's lands
![2015-04-03_00002](https://cloud.githubusercontent.com/assets/11132095/6989480/78a7216e-da21-11e4-8f51-67b715c8c7e4.jpg)
Entering requires a DoW.
![2015-04-03_00003](https://cloud.githubusercontent.com/assets/11132095/6989478/78a3ee7c-da21-11e4-9cc2-ee2b45a1ec2c.jpg)
This happens if I actually DoW.

**Comment by joosegoose** [comment]
Those images were from freshly launching the game and loading an autosave. I tried reloading again in game (typically a bad time), and it actually seemed to fix the issue.
![2015-04-03_00004](https://cloud.githubusercontent.com/assets/11132095/6989556/89f7ce18-da22-11e4-81db-e273fe5216c1.jpg)

I suppose the "issue" is considered solved, though I still have no idea why that would happen. Probably a limitation of the way the game handles saves I suppose?

**Comment by LoneGazebo** [comment]
Yep. Saves act funny with custom dlls when loaded in game. Not sure why.

**Comment by joosegoose** [comment]
The buggy images in the original post were from when I freshly loaded, not
ingame. The later image of my units being in the CS like they were supposed
to be came from loading ingame.

**Comment by LoneGazebo** [comment]
Odd. I'll let ilteroi know. He did the work on that in the past version. 
G

**Comment by ilteroi** [comment]
can't reproduce ...

**Comment by joosegoose** [comment]
I've experienced this in multiple games now, and have seen it mentioned on
the forums I believe. Specifically, loading a saved game prevents the
player from entering CS territory for the first turn. Subsequent turns work
perfectly fine. I have not tested to see if the issue is there every single
time a save is loaded, but it seems fairly reproducible on my end.

**Comment by ilteroi** [comment]
oh, i missed that about "first turn after loading". fixed. @G: and pushed
