### ISSUE TITLE
Hospital doesn't heal planes

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1854]
Bug Report Template

Mod Version (i.e Date - (4/23b)):5/15

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

I have 6 stealth bombers in a city with a free hospital.
If they pass the turn, they heal 20 HP each, which is default city healing rate. The hospital should add 15, but doesn't.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Edaka** [comment]
Intentional, I think. Hospitals aren't supposed to heal neither planes nor ships. I'm not sure if they heal mech units like tanks, helicopters, etc.
