### ISSUE TITLE
AI disregards Natural Wonders when settling

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1856]
http://forums.civfanatics.com/showpost.php?p=14280907&postcount=16

**Comment by LoneGazebo** [comment]
@ilteroi, thoughts?

**Comment by ilteroi** [comment]
haven't really seen that much. but maybe the value of exotic yields like culture etc should be increased.

**Comment by Edaka** [comment]
http://forums.civfanatics.com/showpost.php?p=14317915&postcount=65
Dunno if it's worth reopening, but I will just in case this can be improved upon.

**Comment by GrantSP** [comment]
Actually I think the entire city selection AI is a bit off.
In a recent game I conquered a new continent only to find cities founded in poor resource locations with untouched 'Iron' tiles well into the 'Industrial' era. Then in my current game Rome ventured into my territory and promptly settled in the southern most tile possible completely surrounded by ice, tundra and mountains with just 1 'fish' tile as its bonus, when only a few tiles away there were 2 '6x Iron' tiles up for the taking, but far too far for normal city growth to capture them.

**Comment by LoneGazebo** [comment]
One game does not an AI issue make. Nevertheless there are some deeper issues with unit missions that may be manifesting in bad AI play right now.

**Comment by GrantSP** [comment]
Technically my post is about 2 games. ;) Just kidding.
Anyway, that's why I tacked my experience onto an existing report. 
I've read about the unit missions in the other reports, very odd behaviour in many units/scenarios that you wouldn't ordinarily think be affected.

**Comment by LoneGazebo** [comment]
Yeah, ilteroi is on it, though. So no worries. We'll see how it shakes out over the next few days.
