### ISSUE TITLE
Foot Melee units (maybe Gunpowder?) units can take Mobility promotion

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1857]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21

1. Mod List (if using standard CPP set, leave blank): Your six with EUI, FlagPromotionsV7, More Great Works, Great People Pack, More Great Musicians, Ice Free Coasts, Celtic City Names, Iroquoian City Names, Randomize City Names, NoAltitudeTraining (removes the Mt. Kilman promo), and my own version of Wario's Rules, which right now only deletes Goddess of Protection, and sets Barbarian exp to -1.

2. Type of error (i.e. crash, interface bug, AI quirk): I didn't do quite enough war with swords to know either way, but my Tercios can take Mobility at Shock III now. Intentional?

(French Open has been boring so I guess I lied about disappearing, can't stay away from this mod lol)

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Yes intentional.
