### ISSUE TITLE
I thought I didn't get foreign Enhancer belief anymore?

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1858]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21

1. Mod List (if using standard CPP set, leave blank): Your six with EUI, FlagPromotionsV7, More Great Works, Great People Pack, More Great Musicians, Ice Free Coasts, Celtic City Names, Iroquoian City Names, Randomize City Names, NoAltitudeTraining (removes the Mt. Kilman promo), and my own version of Wario's Rules, which right now only deletes Goddess of Protection, and sets Barbarian exp to -1.

2. Type of error (i.e. crash, interface bug, AI quirk): I could have just misunderstood the religion change from a little while back, but I was under the impression Enhancer beliefs didn't help out non founders or holy city possessors. When Mongolia added Zealotry to Hinduism, I was able to buy units with faith as well. Also, getting his Spirit of the Desert pantheon yields too.

(Forgot to take screenshots, sorry)

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
City level beliefs are valid for all parties.
