### ISSUE TITLE
zone of control

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#186]
Ships' zone of control affects land units.

**Comment by qqqbbb** [comment]
Land units' zone of control affects embarked units.

**Comment by qqqbbb** [comment]
Or should I post it as a dll addition request?

**Comment by DanteValerian** [comment]
This isn't a bug, it has always been that way even in Vanilla.

**Comment by LoneGazebo** [comment]
this should be a feature request - I'll keep it in mind for the next version.
G

**Comment by wileyhk2001** [comment]
I like just the way it is.

**Comment by qqqbbb** [comment]
If Gazebo fixes it, I'm sure it will be optional.

**Comment by qqqbbb** [comment]
Are you sure you don't wanna fix this? It looks like a no-brainer to me.
Here is fix. The file is CvUnitMovement.cpp.


// line 475 					// this is valid
							// ships affect land units' movement only if they are embarked
							if(loop_unit_domain_type == DOMAIN_SEA && pUnit->isEmbarked())
							{
								// continue on
							}
#if defined(MOD_BUGFIX_HOVERING_PATHFINDER)
							// hovering units always exert a ZOC
							else if (pLoopUnit->IsHoveringUnit()) {
								// continue on
							}
#endif
							else
							{
								continue;
							}
						}


						// Embarked?
						if(unit_domain_type == DOMAIN_LAND && pLoopUnit->isEmbarked())
						{
							continue;
						}
						// land units do not affect embarked units' movement 
						else if(loop_unit_domain_type == DOMAIN_LAND && pUnit->isEmbarked())
						{
							continue;
						}

						// Loop through plots adjacent to the enemy unit and see if it's the same as our unit's Destination Plot
