### ISSUE TITLE
Various visual bugs

### ISSUE THREAD

**Issue by cononderbee** [LoneGazebo/Community-Patch-DLL#1862]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21 beta

1. Mod List (if using standard CPP set, leave blank):
CBO with EUI
InfoAddict
Reseed!
R.E.D
Ethnic Units
JFD's Empire of Great Britain
Tectonic Map Script

I also started the game with JFD's Kingdom of the Vandals loaded but didn't actually include them in the game.

Have been seeing a few odd happenings with visuals in my latest game.

1. The notification for monopolies no longer shows the bonus for the monopoly when hovering over it--I can find this information on the monopoly screen but it was nice to instantly know what had changed.

2. I traded stuff for a city that Rome owned, a former city-state, then liberated the city state (Panama City). Then a blank screen (with "leader not loaded" appearing in the top left corner) appeared and "Crom" thanked me for liberating his people. I either didn't notice or hadn't discovered the city-state when Rome conquered it so I don't know whether a barbarian horde previously held the city-state. When I'd previously liberated a barbarian-held city-state I didn't receive a leader screen.

3. A few turns after this, Alexander declared war on me. I received the same blank screen, but the text said that "Victoria" (i.e., me) was declaring war on me.

I've attached an autosave two turns before Alexander declares war on me--to replicate you may need to demand tribute from Lhasa. Also the logs folder, not the minidump because there's no crash but let me know if that's needed. I tried to include a screenshot but pasting it into paint it just came out black, not sure if there's a trick to screenshotting steam games I'm unaware of?

https://www.dropbox.com/s/qv2q6ypha7ixrc6/LogsSave%20%282%29.zip?dl=0

On a sidenote, there was a severe technology gap in this game--I'd discovered 30~ technologies while some civs only had 14. I'm not totally against this and I'm gonna post a thread in the main forum to open up a discussion about it, but if it's against the 'philosophy' of CBO it might be something also worth taking a look at.

**Comment by Edaka** [comment]
Press F12 to take a screenshot via Steam. Then after you've exited the game, it will offer you to upload them to the server, but you can also choose to 'View on disk', which will take you to the screenshot directory.

**Comment by mwhiter** [comment]
I play in windowed mode and have no issues with print screen. That is much faster than steam screenshot.

**Comment by Skaz881** [comment]
I had similar errors (blank leader screen, "Crom of Kiev" greeting me, leader not loaded) when I played with the non EUI set and ExCE.  It sounds like something in the latest beta doesn't like JFD's mods.....
