### ISSUE TITLE
Crash when building landships

### ISSUE THREAD

**Issue by SangcheonLee** [LoneGazebo/Community-Patch-DLL#1863]
Bug Report Template

Mod Version (i.e Date - (4/23b)): March 9th (1.3.9)

1. Mod List (if using standard CPP set, leave blank):
CPP Set 1-6a
Faster Aircraft Animations (v. 3)
Colonialist Legacies - The Pridelands (v. 1)
Barbarian Spawn Increase (v. 2)
Barbarians Evolved (v. 4) (Changed file to be compatible with CBP as shown here: http://steamcommunity.com/workshop/filedetails/discussion/485249197/412447331648843297/)

2. Type of error (i.e. crash, interface bug, AI quirk): 
Crash when finished building a landship in my city Zuberi

3. Steps to reproduce:
The turn is 567 and when I tried to finish my landship, the game crashes before reaching my turn. The savefile to reproduce this is named "Simba with Landship"

When I don't finish a landship in Zuberi and make it build something else, the game goes on without crashing After that, when I tried to finish my landship in turn 568, the game crashes again.

4. Additional information:
I attached the Database.log, Lua.log, and Minidump file in a zip folder. I also attached a screenshot:
![20160525102658_1](https://cloud.githubusercontent.com/assets/6588887/15544831/2750e418-2268-11e6-8037-820cac9ebbdf.jpg)
[CivSimbaLandshipFiles.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/282250/CivSimbaLandshipFiles.zip)

Thank you and good luck!
---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Vyyt02** [comment]
Just before someone starts looking into it, it seems that you are using some sort of mod changing the unit graphics - I am referring to the lions(?) instead of the Riflemen (WWI infantry). Are you sure you have listed all the mods? Maybe the graphics mod is changing the Landship and it is missing a texture or something ... ???

**Comment by SangcheonLee** [comment]
Here's a screenshot of the mods I used
![20160525123208_1](https://cloud.githubusercontent.com/assets/6588887/15548419/487d5be0-2276-11e6-98dd-745cd7d6bbe5.jpg)

The lions mod is the Pridelands civ here: https://steamcommunity.com/sharedfiles/filedetails/?id=453438148

Maybe it is the graphics mod changing it because I think I saw the Netherlands use a landship fine.

**Comment by Edaka** [comment]
I'd report this to the creators of that mod, either on Steam (thi link you've linked) or on Civfanatics (http://forums.civfanatics.com/showpost.php?p=14252155&postcount=4). I'd like to help you, but this is the best I can do due to my nigh non-existent modding skills, unfortunately.
