### ISSUE TITLE
More than 1upt temporarily 

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1866]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21

1. Mod List (if using standard CPP set, leave blank): Your six with EUI, FlagPromotionsV7, More Great Works, Great People Pack, More Great Musicians, Ice Free Coasts, Celtic City Names, Iroquoian City Names, Randomize City Names, NoAltitudeTraining (removes the Mt. Kilman promo), and my own version of Wario's Rules, which right now only deletes Goddess of Protection, and sets Barbarian exp to -1.

2. Type of error (i.e. crash, interface bug, AI quirk): When I move a bunch of units at once or if some get displaced for one reason or another, they sometimes end up occupying the same tile. When my next turn starts, they get moved to a free space, as the second screenshot shows. The third screenshot shows a Brazilian unit ending its turn in my city.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![upt1](https://cloud.githubusercontent.com/assets/16260521/15563017/9883a156-22d2-11e6-941f-718b255a8636.jpg)
![upt2](https://cloud.githubusercontent.com/assets/16260521/15563021/a17a3982-22d2-11e6-8228-4a6056d3d570.jpg)

![upt3](https://cloud.githubusercontent.com/assets/16260521/15563031/b3bf8d04-22d2-11e6-9ac6-ff5a13038dfa.jpg)

**Comment by ilteroi** [comment]
will check but i've never seen that. might take some time.

**Comment by ilteroi** [comment]
played around a bit but couldn't reproduce ... how do you mean, "move a bunch of units at once"?

savegame would be nice.

**Comment by pandasnail** [comment]
I just mean moving units on the same turn from the same general area to the same new general area. I don't mean I have some cool mod that lets highlight all and literally move a bunch at once.

I play with too many mods to post saves from my normal games I assume. If the issue persists, I'll try to do a separate game at some point.

**Comment by pandasnail** [comment]
Oh, I should say too that its specifically moving units to far away areas. The tiles I clicked to move to for all those boats are near the Eastern Brazil border, It didn't happen if I manually move units turn by turn
