### ISSUE TITLE
AI is too careful with its siege units (e.g., catapults)

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1868]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
5/21

1. Mod List (if using standard CPP set, leave blank):
Vox Populi with EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 
AI quirk. AI is too afraid to lose its siege units (e.g., catapults), which is detrimental to its city sieging capabilities.

3. Steps to reproduce:
Have a city attacked by a relatively small group of units. Say, it has a little bit of every type of unit, including 2 catapults. The AI will take positions with the catapults, have them set up. Then you bombard one catapult by a city and another by an archer that's garrisoned in it. Even though both attacks will deal about 20 damage each and the catapults wull be in no real danger of dying, both will withdraw from the siege (presumably to heal). 

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by ilteroi** [comment]
hmm. do you have a savegame?

**Comment by Edaka** [comment]
Ah, sorry, I didn't mention that I modify policies, buildings, etc. directly in the CBO's files, so you I don't think you will be able to run my save. Consider this ticket just a heads up.

**Comment by ilteroi** [comment]
too many tickets, closing this ...
