### ISSUE TITLE
DoF period mismatch

### ISSUE THREAD

**Issue by cononderbee** [LoneGazebo/Community-Patch-DLL#1871]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21b

1. Mod List (if using standard CPP set, leave blank):
CBO with EUI
Tectonic Map Script
RED
InfoAddict

2. Type of error (i.e. crash, interface bug, AI quirk): 
Playing on epic speed if that makes a difference. EUI tells me that I still have a declaration of friendship with Korea. However, I can't end the DoF as I normally can--Korea thinks we are not currently friends!

To be clear--I had previously looked at this screen and the option was available, 10-15 turns before.

![20160527174755_1](https://cloud.githubusercontent.com/assets/18727998/15590966/5f9b6afc-2392-11e6-9a5f-06af5e5ced9d.jpg)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by pandasnail** [comment]
If you press the button, it'll likely be that you can end the friendship, works that for me at least, its just the EUI screen text is wrong, I've always assumed this is bc's fault.
