### ISSUE TITLE
Completed CS liberation quest without liberating CS

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1872]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21

1. Mod List (if using standard CPP set, leave blank): Your six with EUI, FlagPromotionsV7, More Great Works, Great People Pack, More Great Musicians, Ice Free Coasts, Celtic City Names, Iroquoian City Names, Randomize City Names, NoAltitudeTraining (removes the Mt. Kilman promo), and my own version of Wario's Rules, which right now only deletes Goddess of Protection, and sets Barbarian exp to -1.

2. Type of error (i.e. crash, interface bug, AI quirk): Hanoi gave me a quest to liberate Malacca. The very next turn (I think), I got the reward for it tho Malacca is still under Turkish control. Now, not only have I liberated Malacca before (lots of times in fact, Brazil and I did an Army vs Navy battle over it), but strangely, I legitimately completed this very quest for the very same Hanoi once already.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![cslib](https://cloud.githubusercontent.com/assets/16260521/15591068/fc0f033c-2368-11e6-8d39-9ebfdaeb3e77.jpg)

**Comment by LoneGazebo** [comment]
Interesting. I'll look.
