### ISSUE TITLE
Agribusiness and Coal Plant aren't using up resources

### ISSUE THREAD

**Issue by Frozen-In-Ice** [LoneGazebo/Community-Patch-DLL#1873]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
March 9th I think? I used the automatic installer on May 22nd, and that page on CivFan says March 9th is the most recent build.

1. Mod List (if using standard CPP set, leave blank):
Community Patch v72
Faster Aircraft Animations v3
Info Addict v22
Ingame Editor v39
Quick Turns v10
Really Advanced Setup v15
Community Balance Patch v13
City State Diplomacy v27
Civ 4 Diplomacy - CBP Edition v10
More Luxuries - CBP Edition v155
Community Balance Patch - Compatibility for EUI v1 

2. Type of error (i.e. crash, interface bug, AI quirk): 
Agribusiness and Coal Plant buildings aren't using up horses and coal properly.

3. Steps to reproduce:
Playing as Poland on Communitas Map script included in CPP.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![20160527102138_1](https://cloud.githubusercontent.com/assets/19610489/15610889/a6a6fc96-23f5-11e6-96ab-75e5a764255f.jpg)
![20160527103436_1](https://cloud.githubusercontent.com/assets/19610489/15611126/dfae4066-23f6-11e6-8845-5422fa3a3d01.jpg)

**Comment by LoneGazebo** [comment]
That's just EUI - I don't think it shows a preview there for buildings, as bc1 didn't account for buildings using resources IIRC. Could be wrong, though.

**Comment by Frozen-In-Ice** [comment]
The UI is correctly deducting for Seaports and Factories in the second picture, so I'm not sure it's that. I guess I could try trading away all my horses and then try building an agribusiness to test it for certain though.

**Comment by Frozen-In-Ice** [comment]
I'm a complete newbie to to how these mods work but I was poking around BuildingChanges.sql and I noticed this section:

```
INSERT INTO Building_ResourceQuantityRequirements
	(BuildingType, ResourceType, Cost)
VALUES
	('BUILDING_WIND_PLANT', 'RESOURCE_ALUMINUM', 1),
	('BUILDING_SEAPORT', 'RESOURCE_COAL', 1);
```
Would there have to be Stockyard (I believe that's Agribusiness) and coal plant in here?

**Comment by LoneGazebo** [comment]
If you are on the 3/9 version, you're on an older version that has that fixed already.

**Comment by Frozen-In-Ice** [comment]
Ok, that's the issue then. Thanks for clarifying!
