### ISSUE TITLE
Zulu unique promotions

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#1874]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): The unique promotions of the Zulus don't seem to give any combat strenght to the calculations even though they should. This might be only presentational, but there is something wrong anyway. In the screenshot I have a unit that has all buffalo promotions, shock II and conscription, which should make 55% bonus to combat strenght. The calculations, however, show just 30% bonus. A unit with shock II and conscription but no unique promotions has the same combat bonus.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![20160528020818_1](https://cloud.githubusercontent.com/assets/18663580/15623146/60f89860-2479-11e6-9e07-de038a24c476.jpg)
![20160528021333_1](https://cloud.githubusercontent.com/assets/18663580/15623178/cfacc11e-2479-11e6-9dfd-65a316320f64.jpg)

**Comment by Der-Zorn-Gottes** [comment]
Also, why does great general give +25%? Should be 15%.

**Comment by F0rst1** [comment]
Shaka's UA increases combat bonus near great general by 10%.

**Comment by LoneGazebo** [comment]
Not sure - the combat preview doesn't always add things up as it should, for some reason or another.

**Comment by F0rst1** [comment]
You added the "need more information" label. Does it mean there is something I can do to help, as I'm not sure, what information I can provide in addition to what I have already written?

**Comment by LoneGazebo** [comment]
Ah, that's my way of saying 'I need to find more examples of this.' I did discover that the zulu promotions are working, but instead of using the flat combatpercent bonus from the XML they used the open/rough attack/defense modifiers for the 10% combat bonuses of those promotions. So the promotion text lies.
