### ISSUE TITLE
Assyrian UA (5/21 beta) 

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#1876]
Bug Report Template

Mod Version (i.e Date - (4/23b)):5/21

1. Mod List (if using standard CPP set, leave blank):
CP
CBO
IGE

2. Type of error (i.e. crash, interface bug, AI quirk): 
Ashurbanipal doesn't receive +2 science from a Great Work.
The Great Work itself indicates that it produces +2 science.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

![assyria 1](https://cloud.githubusercontent.com/assets/11933188/15627990/fcc293f2-252f-11e6-9081-02776e6111ff.png)
![assyria 2](https://cloud.githubusercontent.com/assets/11933188/15627992/019ccf8c-2530-11e6-9648-67fa52d113ce.png)
![assyria 3](https://cloud.githubusercontent.com/assets/11933188/15627993/04c2ec6e-2530-11e6-880c-5b280c02edbd.png)
![assyria 4](https://cloud.githubusercontent.com/assets/11933188/15627994/081051fe-2530-11e6-9f5b-ac883aca7e58.png)

**Comment by LoneGazebo** [comment]
I'll look.
