### ISSUE TITLE
CTD on next turn

### ISSUE THREAD

**Issue by scionkiller** [LoneGazebo/Community-Patch-DLL#1877]
I have a CTD, reported with your template below.

I would like to say first, though, that this mod is amazing and has rekindled my love of Civ 5 in a huge way. I can't believe that Gazebo has the time and effort to not only work on this, but also to handle bug reports. Kudos to you!

Bug Report Template

Mod Version (i.e Date - (4/23b)):
3/9, EUI Modpack version

1. Mod List (if using standard CPP set, leave blank):
No mods other than CPP set, other than two map scripts not being used in this game.

2. Type of error (i.e. crash, interface bug, AI quirk): 
Crash to Desktop

3. Steps to reproduce:
Load savegame and press next turn.

4. Additional information:
I enabled logging and have the logs, but a glance at them didn't tell me anything. I've also included the minidump file.

[CBP Modpack 3-9 CTD info.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/287788/CBP.Modpack.3-9.CTD.info.zip)

**Comment by scionkiller** [comment]
What should i do as a workaround? Go back a few turns and hope it doesn't happen again? I didn't see anything special about this stage of the game, there wasn't any wonders finishing or anything like that.

**Comment by Edaka** [comment]
When I get a crash I try to go back for just a couple of turns and do things differently from before. Sometimes it helps, sometimes it doesn't. Another workaround for occasions when a particular AI civ is causing the crash would be deleting all of its units with IGE (in-game editor, a mod).

**Comment by scionkiller** [comment]
Yeah, I went back 5 turns and managed to get around it, so so far this is not blocking me at least.
