### ISSUE TITLE
Food-Yield on terrace farm and mountains as Incas.

### ISSUE THREAD

**Issue by LAUCHKUCHEN** [LoneGazebo/Community-Patch-DLL#1878]
Mod Version: 5/21b

CPP, CBP

Unintended behaviour of food yield on terrace farm and mountains as Incas.

First:
According to wiki entry Terrace Farms should increase nearby farm and other terrace farms food-yield. 
However it does that only for regular farms.

Second:
According to wiki Incas trait is supposed to increase mountain yield of gold **and food**.
Right now it only has two stances: 
Lone Mountain, yield: 1 food, 1gold
One or more adjacent mountains, yield: 1 food, 2 gold

Steps to reproduce:
Play game with mods as Incas. Search for lone mountains and mountain chains and compare yield.
Build Terrace Farms adjecent to each other and notice food yield not increasing.

Possible fixes:
If (Inca)Mountain and/or terrace farm behaviour is working as intended Change tooltip and wiki entries.
If terrace farm is intended to increas adjacent terracefarms food-yield add:

```
INSERT INTO Improvement_YieldAdjacentSameType
	(ImprovementType, YieldType, Yield)
VALUES
	('IMPROVEMENT_TERRACE_FARM', 'YIELD_FOOD', 1);
```
into \(2) Community Balance Overhaul\Balance Changes\Leaders\DLC\DLCChanges.sql

If Mountain yield of food and gold is intended to increase further than 1 food and 2 gold as Inca,
increase the yield values in
```
INSERT INTO Trait_MountainRangeYield
	(TraitType, YieldType, Yield)
VALUES
	('TRAIT_GREAT_ANDEAN_ROAD', 'YIELD_GOLD', '2'),
	('TRAIT_GREAT_ANDEAN_ROAD', 'YIELD_FOOD', '1');
```
in file \(2) Community Balance Overhaul\Balance Changes\Leaders\DLC\DLCChanges.sql .
This bug might be caused from the way Trait_MountainRangeYield increases yield. (wich is not that intuitive)
```
	<!-- TRAIT: Allows you to define a yield that is gained from mountains based on the number of mountains adjacent to a mountain. 
	Yield here is maximum yield for mountain clusters. All mountains have a minimum of 1 yield from the value below, so the yield will be somewhere between 1 and x, where x is the maximum value or # of adjacent mountains. -->
	<Table name="Trait_MountainRangeYield">
```
(Quoted from \(1) Community patch\Core Files\Core Table\CoreTableAdditions.xml)

**Comment by LoneGazebo** [comment]
Terrace Farms aren't supposed to increase Terrace Farm yields, only Farm yields. They then get a bonus based on mountain adjacency.
