### ISSUE TITLE
Peace negotiation not taking effect

### ISSUE THREAD

**Issue by legenciv** [LoneGazebo/Community-Patch-DLL#1879]
Mod Version (i.e Date - (4/23b)):
5/21 beta

1. Mod List (if using standard CPP set, leave blank):
FlagPromotions (v. 7)

2. Type of error (i.e. crash, interface bug, AI quirk): 
Interface bug: peace negotioation not taking effect.
Secondary bug - cannot choose to have more than 1 unit of some strategic resources, unless proposed by the AI.

3. Steps to reproduce:
Savefile attached: attempt to negotiate a peace treaty with Pocatello. The treaty doesn't take effect despite his agreement.

4. Additional information:
Unsure of the conditions that led to this occurrence. Two other peace treaties were made without issues with other leaders.

---------------------------

[bug report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/288052/bug.report.zip)

**Comment by LoneGazebo** [comment]
I'm not sure what's causing this, you'd probably need to step back a turn or two and try it again.
