### ISSUE TITLE
No farm on flood plains

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#188]
![2015-04-04_00003](https://cloud.githubusercontent.com/assets/11132095/6995332/280b2ecc-db06-11e4-8962-d72d7c63bf05.jpg)

As you can see from the imagine, this tile is listed as flood plains and desert. Notably absent is the designation of a "river" tile (which doesn't make sense), so the game is treating it as desert and not allowing a farm. No idea if this is a CPP thing or just an issue with Civ 5 and map generation so I'm reporting in case.

Using 4/1 version, mods on how to install page minus health and plague, and continents map. IGE was opened only for confirmation, no terrain editing was used.

**Comment by LoneGazebo** [comment]
this is a mapgeneration issue - for example, sometimes mountains appear as plains, etc.
