### ISSUE TITLE
Min distance between cities changed?

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#1880]
Mod Version (i.e Date - (4/23b)):
Latest beta: 5/21

1. Mod List (if using standard CPP set, leave blank):
Basic non-EUI setup + bunch of my usual mods which should not affect rules (WHoward's, etc.)

2. Type of error (i.e. crash, interface bug, AI quirk): 
Playing on a huge map and min distance between cities is 3 - it used to be 4 - is this change intentional?

**Comment by Tsenna** [comment]
it was changed to 3 as intended to solve some issues, especially for archiple map.

**Comment by Edaka** [comment]
Yeah, 3 is back as the standard again.
