### ISSUE TITLE
Fog of War in Owned Territory, even on Tiles with my Units!

### ISSUE THREAD

**Issue by Frozen-In-Ice** [LoneGazebo/Community-Patch-DLL#1881]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
March 9th

1. Mod List (if using standard CPP set, leave blank):
Community Patch v72
Faster Aircraft Animations v3
Info Addict v22
Ingame Editor v39
Quick Turns v10
Really Advanced Setup v15
Community Balance Patch v13
City State Diplomacy v27
Civ 4 Diplomacy - CBP Edition v10
More Luxuries - CBP Edition v155
Community Balance Patch - Compatibility for EUI v1 

2. Type of error (i.e. crash, interface bug, AI quirk): 
Fog of war was sometimes coming into my city Krakow. Some of the tiles in the picture below even had units on them, and I still couldn't see the tiles.

3. Steps to reproduce:
It may have something to do with Cargo ships. This issue was only occurring in Krakow, and Krakow was my only city with Cargo ships. When I would make new trade route selections for cargo ships the fog would sometimes change around the city. Usually, once a cargo ship left Krakow, more fog tiles would occur.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![20160529102536_1](https://cloud.githubusercontent.com/assets/19610489/15634366/ff8fd954-258f-11e6-9927-4347d1ed5338.jpg)

**Comment by Der-Zorn-Gottes** [comment]
I experienced something similar. Also for my trade hub city.

**Comment by Edaka** [comment]
Did you both have the corporation that grants vision to trade units when that happened? I've had that as well with that corporation, but the issue is pretty benign.

**Comment by Frozen-In-Ice** [comment]
I wasn't aware that any corps gave vision to trade units, but in this game I had no idea how to use corps so that might be part of it. I had built TwoKay Foods.

**Comment by LoneGazebo** [comment]
Interesting. Sounds like fog is being disabled when it shouldn't be.
