### ISSUE TITLE
ai not building enough ranged ships

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1882]
![image](https://cloud.githubusercontent.com/assets/1358966/15634989/e29eaf9e-25d2-11e6-9fa4-c91ed7973540.png)

only corvettes. no frigates ... two galeasses but doesn't seem like they will ever upgrade.

[CityStrategyAIProductionLog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/288459/CityStrategyAIProductionLog.zip)

**Comment by Vyyt02** [comment]
Could it be that they do not have iron for frigates?

**Comment by ilteroi** [comment]
good point. didn't check that ...

in any case, this fleet is unsuitable for attacking (will be picked off by ranged defenders on land). positive: AI realizes that and retreats. negative: pointless waste of money.

unfortunately there is currently no ranged alternative to frigates ... so maybe remove the iron requirement and up the maintenance cost for ships in general? should give smaller fleets but with more balanced composition.

**Comment by Tsenna** [comment]
Maybe add a second line of ranged ships that are weaker, but dont require special ressources. 

For example land ranged units (beside of horses) exists for archer for non ressource consuming units and cannons as iron consuming range unit.

The same could be usefull for naval units too.
