### ISSUE TITLE
Unit moving to unowned city-tile

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#1883]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): I managed to move my cannon to the city-tile of a city state. The first unit I moved there automatically teleported to a tile next to the city state, where I already had a unit, ending up with 2 military units on the same tile. The second ended up in the city.

3. Steps to reproduce: Make a unit walk to a dinstant tile, where the shortest route would go through the city.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![20160529202439_1](https://cloud.githubusercontent.com/assets/18663580/15635017/164315e8-25dc-11e6-937e-cdcfb7ddb5ca.jpg)
![20160529202928_1](https://cloud.githubusercontent.com/assets/18663580/15635018/1bfd69c0-25dc-11e6-9af0-a4a43cf17455.jpg)

**Comment by Edaka** [comment]
I think this might be directly related to #1866

**Comment by ilteroi** [comment]
do you have a savegame?

**Comment by F0rst1** [comment]
I have one from the start of the turn. Here you go!

[Shaka_0202 AD-1420.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/291125/Shaka_0202.AD-1420.zip)

**Comment by ilteroi** [comment]
something is wrong with me ... apparently i cannot load any savegames from other people ... using master branch 5/21 of course. that has happened before but i couldn't find a solution. can anybody give me a hint?
