### ISSUE TITLE
Turn 5 CTD on every new game

### ISSUE THREAD

**Issue by ph1983** [LoneGazebo/Community-Patch-DLL#1884]
First of all: I absolutely LOVE the cpp project, I have logged almost 1000hours with Civ5 and I thought I was finally done with it, and then I found this gem... wow, it feels like a new game, and I am hooked once again. Thank you!

However, I had to reinstall and I am now encountering CTDs on every new game I start, always after finishing turn 5, waiting for the AIs to make their move. 
I already did a clean reinstall of Civ5 through Steam several times, made sure it's up to date and verified the game files etc., I also reinstalled the cpp patch (automatic installer) several times before deciding on posting this here. 

Bug Report Template

Mod Version (i.e Date - (4/23b)): 
3/9 EUI Version

1. Mod List (if using standard CPP set, leave blank):
default cpp set, nothing else

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:
As said, I just start a new game, doesn't matter which civ i choose or which other parameters I set, it happens every time. I can play until turn 5 and then, when computing the AI moves, i get a CTD

[Civ5 CTD Turn5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/288589/Civ5.CTD.Turn5.zip)

4. Additional information:

I uploaded the dump file and the logs, hope they can help finding the issue. 
When I initially tried the CPP I was able to play for hours and did not run into any issue whatsoever. A few days back I had to reinstall my computer and so I did a clean install of Civ5, made sure its up to date (Steam -> validate...) and then installed CPP with the automatic installer, no other mod is being used or even present in the mods folder)
I have already tried reinstalling several times.
And it does not matter which Civ i choose or what parameters I select for the game, it always crashes after turn 5. I can upload a save file if that helps.
When I run Civ5 without the cpp mods enabled it works fine, no CTD

**Comment by ilteroi** [comment]
which mapscript do you use?

also, the 3/9 version is ancient by now, did you try the latest beta?

**Comment by ph1983** [comment]
all hail the beta version, this fixes my issue... strange enough it did work with the "ancient" 3-9 before and it was rock-solid. thank you and keep up the good work on this!
