### ISSUE TITLE
Barbarians delete their units 

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1887]
Mod Version : may 21 beta
Do they do it  to reduce unit maintenance cost?

**Comment by LoneGazebo** [comment]
No, but I haven't seen this. Barbs don't have access to the disband logic in any case.

**Comment by qqqbbb** [comment]
I did some more testing. They don't delete their units, but they disappear when barbarians attack a city and reduce it's HP to 0.

**Comment by LoneGazebo** [comment]
They take damage from 'attacking' a city, yep.

**Comment by qqqbbb** [comment]
They don't just take damage, they are killed when city's HP reach 0.

**Comment by ilteroi** [comment]
by design. they don't capture cities but sack them. afterwards the attacking unit is removed.
