### ISSUE TITLE
Barbarians do not capture cities

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1888]
Mod Version : may 21 beta
Not sure if it's a bug but in previous versions of CBP they did.

**Comment by ilteroi** [comment]
need more information. are you talking about the "horde" events or regular conquest?

**Comment by qqqbbb** [comment]
Regular roaming barbarians. When they attack a city, they reduce its HP to 0 but do not capture it.

**Comment by ilteroi** [comment]
yeah that's by design. instead, the plunder a lot of gold as ransom.

**Comment by LoneGazebo** [comment]
I say we leave it as-is.
