### ISSUE TITLE
Policy doesnt work v 3/30

### ISSUE THREAD

**Issue by Shadzy19** [LoneGazebo/Community-Patch-DLL#189]
Hi,

The policy "empiricism" doenst seem to be working correctly, only the city's on my main continent seem to get the connection happy bonus from empiricism, the city's on other islands / continents dont get the happy bonus.
Railroad's production bonus does work.
Perhaps its linked to https://github.com/LoneGazebo/Community-Patch-DLL/issues/178 and is already fixed?

I also noticed a load of scouts and explorer units in this game , check the last screenshot from maya invading mongolia.

![civ5screen0000](https://cloud.githubusercontent.com/assets/11803298/6995798/51f27444-db5f-11e4-9cb8-b804f8762c46.gif)
![civ5screen0001](https://cloud.githubusercontent.com/assets/11803298/6995812/c0051a86-db5f-11e4-9ef8-d1404421afc6.gif)
![civ5screen0002](https://cloud.githubusercontent.com/assets/11803298/6995813/c0060ae0-db5f-11e4-8c1c-bde406ff8d49.gif)
![civ5screen0003](https://cloud.githubusercontent.com/assets/11803298/6995811/c001d0d8-db5f-11e4-999c-8106a7a524a2.gif)

**Comment by LoneGazebo** [comment]
This was fixed in the latest version (I also turned down flavors on explorers - it was a bit extreme).
G
