### ISSUE TITLE
AI players delete their starting units

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1892]
CP + CBO Version may 21 beta
When you start a game in late era AI found their capital city and immediately delete all their settlers. 
Lua code I used to test this:
```
function OnUnitPrekill(iPlayer, iUnit, iUnitCombatType, iX, iY, bDelay, iByPlayer)
	if bDelay == true then  -- UnitPrekill fires twice
		local pPlayer = Players[iPlayer]
		local pUnit = pPlayer:GetUnitByID(iUnit) 
		if iByPlayer == -1 then
			print('UnitPrekill '..pUnit:GetName()..' '..iX..' '..iY..' by '..iByPlayer)
		else
			print('UnitPrekill '..pUnit:GetName()..' '..iX..' '..iY..' by '..Players[iByPlayer]:GetName())
		end
	end
end
GameEvents.UnitPrekill.Add(OnUnitPrekill)
```

**Comment by qqqbbb** [comment]
Looks like game code replaces settlers with pioneers ( although AI has tech to build colonists) but it still deletes its pioneers.

**Comment by LoneGazebo** [comment]
@ilteroi, is this because they don't have spots to settle (as they haven't explored)?

**Comment by LoneGazebo** [comment]
Perhaps we should add a check to make sure that they don't delete if there is unexplored territory nearby?

**Comment by ilteroi** [comment]
i think this may be benign. when units are upgraded, the old one is killed and a new one is created in its place. so this might simply be a side-effect of turning settlers into colonists. don't know how the advanced start code works in this respect though.

afaik settlers are only killed if there are more than 3. if ever.

**Comment by LoneGazebo** [comment]
Cool. We'll consider it benign, then.

**Comment by qqqbbb** [comment]
It's not a side-effect of turning settlers into colonists. They delete their settlers, workers and military units even when they have only 1 of them. And it's not hard to test it.

**Comment by ilteroi** [comment]
hmm. just tested a modern era start.

i got three settlers. not pioneers. when founding a city, it nevertheless has barracks, colosseum (playing as rome), monument and granary.

then there's some sort of bug with the policy screen:

![image](https://cloud.githubusercontent.com/assets/1358966/15906750/7dc55984-2dba-11e6-9a6a-f75c8d067fe8.png)

and finally the AI starts upgrading their settlers to pioneers. that's when the "kills" happen. but no units are killed for real.

**Comment by qqqbbb** [comment]
This can be closed then. When I tested it I saw that AI deletes its settlers and the next turn deletes its pioneers. I thought the game replaces settlers with colonists but it replaces settlers with pioneers and then replaces pioneers with colonists.
What's the bug with policy screen?

**Comment by ilteroi** [comment]
piety is locked. and it the opener button doesn't have a label.

**Comment by qqqbbb** [comment]
Yeah, it's disabled in late starts

**Comment by Edaka** [comment]
On a second though, though: could later era starts be modified so that players start with pioneers/colonists if the appropriate techs are researched (instead of those modified settlers that we have now)? All that chain of upgrading seems like an unnecessary waste of resources.
