### ISSUE TITLE
Automatic religious purchase selector does not retain setting upon save load

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#1893]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
5/21b Vox Populi

1. Mod List (if using standard CPP set, leave blank):
+ FlagPromotions v7
+InfoAddict

2. Type of error (i.e. crash, interface bug, AI quirk): 
I'm not entirely sure this isn't also a vanilla oddity but the choice you set in the automatic religious purchase dialogue resets to 'no purchase' when a save is loaded

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by GrantSP** [comment]
So is this a vanilla thing or just a non-important VP thing?

**Comment by LoneGazebo** [comment]
It is a vanilla thing - the value isn't stored (it is a lua switch, not a DLL switch). I can't push the value to DLL memory, so there's no way to make it remember.

**Comment by GrantSP** [comment]
Thank you. I always like to know the reasons why reports are closed. I do though also understand that commenting on all of them takes time.

**Comment by LoneGazebo** [comment]
Yep. There were 161 open, I had to cull the herd with the new version.
