### ISSUE TITLE
A couple of 'Is this intentional?' type of questions

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1894]
Gathered from the forum.

- So the Harappan Reservoir doesn't give Lake Tiles +1 Food unlike the Aqueduct.
- Because of the -20% RCS from Logistics, the Ship of the Line now has a lower RCS than Galleass. The Slinger, the Chu-ko-nu and the Hwacha are also in the same boat (pun intended).

**Comment by qqqbbb** [comment]
Ship of the Line gets - 20% RCS from indirect fire which is really wierd. There are no hills at sea to justify the nerf.

**Comment by F0rst1** [comment]
This probably fits here:

- Ger doesn't have the base +1 food that granary has
