### ISSUE TITLE
Major graphical errors

### ISSUE THREAD

**Issue by Skaz881** [LoneGazebo/Community-Patch-DLL#1896]
Bug Report Template

Mod Version (i.e Date - (4/23b)):5/21 beta

1. Mod List (if using standard CPP set, leave blank):Vox Populi no EUI, RED v28 beta, JFD's Cities in Development v43, JFD's Rise to Power v24, JFD's Exploration Continued Expanded v16, JFD's Cultural Diversity (Core) v9, JFD's Cultural Diversity (Soundtrack) v1.
[Screenshots.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/291679/Screenshots.zip)

2. Type of error (i.e. crash, interface bug, AI quirk): 
Graphical, game freezing, interface.
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/291712/Database.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/291713/Lua.zip)

3. Steps to reproduce:
Redownloaded Vox Populi, tried with just the CP, still produced errors.  It seems to happen with any part of the CPP.

4. Additional information:
Errors range from icons being blacked out or wrong, leader screens being frozen, blank or blacked out, city names and other headings being replaced with redish-black boxes and especially the game freezing up due to "error loading font texture" messages.

---------------------------
Supporting information:
I tried with many other mods, I only got them when I used JFD's mods in conjunction with the CP.  I have attached a folder of screenshots to help.
Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/291736/CvMiniDump.zip)
 file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Vyyt02** [comment]
Have you tried lowering the graphics settings to the minimum?

**Comment by Skaz881** [comment]
At the moment switching the overlay to medium and turning off high texture strategic view and the gpu thing seems to have fixed it.

**Comment by Hokath** [comment]
Yeah I have seen this if I play for a 'very' long time, guess it is just overcooking the computer

**Comment by HalfEmptyMug** [comment]
I had the same issue, disabling R.E.D. resolved the problem for me. I'm not exactly sure why, but I imagine it's some sort of texture overflow since (for me at least) errors began to accrue over several turns until it was unplayable and needed to be reset. This would also support what Hokath said about this happening after playing for a while.
