### ISSUE TITLE
Gunpowder Plot event's 4th choice doesn't cost gold

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1897]
Mod Version (i.e Date - (4/23b)): 5/21

CITY_EVENT_GUNPOWDER_PLOT_CHOICE_4 seems to have CityEventChoice_MinimumStartYield set at 200 gold, but it doesn't have CityEventChoice_InstantYield of -200 gold, which makes the event choice free in practice.

**Comment by Hokath** [comment]
Thanks for holding me to rights Edaka.
I'll fix this [over here](https://github.com/TechpriestEnginseer/Community-Patch-Events-Development)

**Comment by LoneGazebo** [comment]
Calling this as fixed, @Hokath
