### ISSUE TITLE
Science yields from various ideologic tenets

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1898]
Mod Version (i.e Date - (4/23b)): 5/21

Military Industrial Complex (Autocracy) is supposed to grant +3 science to unique tile improvements, but it actually grants +1.

Another thing: Worker Faculties (Order) is supposed to grant +3 science to factories, but it actually grants +2.

**Comment by LoneGazebo** [comment]
I'll look.
