### ISSUE TITLE
Events - Resources not being granted after sucessful event

### ISSUE THREAD

**Issue by Adam3333** [LoneGazebo/Community-Patch-DLL#1899]
Mod Version - 5/21b

1. Mod List:
InfoAddict
Faster Aircraft Animations
FlagPromotions 

2. Type of error (i.e. crash, interface bug, AI quirk): 
Events - Results not happening as described

3. Steps to reproduce:
'Meteor' event was displayed giving a few options, one was along the lines of 'send it to the forge' (with a 50% chance of granting +2 Iron). This option was chosen and the following popup displayed the 'success' text. However, the additional Iron was not granted.

4. Additional information:
Screenshots and savegame attached
[Iron Events.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/293962/Iron.Events.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Depending on tech level, it may not show immediately.

**Comment by Adam3333** [comment]
Would you like any more information?
The extra resources still haven't shown up and I am now in the Medieval Era,is there a trigger date or technology?

**Comment by Edaka** [comment]
I think there simply isn't a EventChoice_ResourceQuantity linked to any of the meteor event choices.

**Comment by LoneGazebo** [comment]
I see one, wonder if something got copy-pasted wrong.

**Comment by Edaka** [comment]
That's weird. My 5/21 PlayerEvents.sql doesn't have it. The only  EventChoice_ResourceQuantity I see there is for the windmill modernization event.

**Comment by LoneGazebo** [comment]
Right, in that version I mean.
