### ISSUE TITLE
Events - Corruption Event (incorrect yields and no popup)

### ISSUE THREAD

**Issue by Adam3333** [LoneGazebo/Community-Patch-DLL#1900]
Mod Version - 5/21b

Mod List:
InfoAddict
Faster Aircraft Animations
FlagPromotions

Type of error (i.e. crash, interface bug, AI quirk): 
Events - Not notified event active, and creating different effects to those stated in 'events' screen

Steps to reproduce:
Whilst gathering screenshots for a separate issue, I noticed an active event in the 'events' window which I hadn't been notified about (no popup).
Also the actual yeilds in the affected city were not as shown in the events screen.

Event as follows:
Local Corruption (City of Dover) - minus 6 production for 30 turns
Actual yield in city - minus 3 production

Additional information:
Screenshots and savegame attached
[Corruption Event.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/293976/Corruption.Event.zip)

**Comment by LoneGazebo** [comment]
That is an event in which you choose an option – you sure you didn't just pass through it by accident?

**Comment by Adam3333** [comment]
Its certainly possible that I missed the event.
Are the differing yields intentional?

**Comment by LoneGazebo** [comment]
No, I'd need to look.
