### ISSUE TITLE
Recapturing your own former civilian units creates a diplomatic penalty

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1901]
Mod Version (i.e Date - (4/23b)): 5/21

A certain post on the forum reminded me of this. I once had a situation when some civ declared war on me and captured my worker. I immediately recaptured the worker on the next turn, for which I got the 'You enslaved our civilians!' diplomatic penalty with the civ. I don't play with transparent diplomacy, so I don't know how much of a penalty I got, but even getting one in the first place seems unnecessary in that kind of situation, Is this working as intended?

**Comment by LoneGazebo** [comment]
It is intentional – the AI views all owned civilians as 'theirs,' even if formerly yours. You'd do the same towards the AI, so yeah, it is correct.

G

**Comment by Edaka** [comment]
Yeah, I see your point. The situation I described is quite silly, but fixing it would probably be not worth it.
