### ISSUE TITLE
Tourism Shared Religion Modifier is Switched

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#1902]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

5/21

1. Mod List (if using standard CPP set, leave blank):

Vox Populi Complete with EUI
+
Faster Aircraft Animations Version 3
Global - City State Airbases Version 3
Global - Commander Influence Borders Version 1
InfoAddict Version 22
Quick Turns Version 10
Really Advanced Setup Version 15
Religion - Fixed Prophets Version 2
UI - Enhanced Demographics Version 6
UI - Summary Antiquities Version 2
UI - Summary Luxuries Version 13
UI - Summary Specialists Version 11
UI - Trade Opportunities Version 28

2. Type of error (i.e. crash, interface bug, AI quirk): 

Interface/Gameplay bug.

3. Steps to reproduce:

- Have a religion.
- Check Tourism modifier.
- Civs with another religion get the "shared religion" modifier.
- Civs with the same religion don't.
- Civs with no religion at all correctly don't have it.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Odd, I can't reproduce this.

**Comment by Oscar-IronTower** [comment]
For savegames it has to be only with the VP mods, right?

In any case, here's some extra info:

- I was playing Venice, and only had my Capital city. Russia had Buddhism, I had Catholicism (my founded religion), Poland Catholicism and Persia none.
- I had in my City around 18 Catholic citizens, and 4 Buddhists (a trade route influenced them).
- I had shared religion with Russia, and none with Poland and Persia.

Maybe for some reason the game thought I was Buddhist due to those citizens in my only city?

**Comment by LoneGazebo** [comment]
It might've - what did the Religion Ovewview say?

**Comment by Oscar-IronTower** [comment]
It was quite a few days ago, don't have a save anymore... If I see it again, I'll let you know. I'm quite sure it happened, but can't remember any more details.
