### ISSUE TITLE
City panels not appearing on map. 

### ISSUE THREAD

**Issue by EKHawkman** [LoneGazebo/Community-Patch-DLL#1903]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6/03/16

1. Mod List (if using standard CPP set, leave blank):
Standard with EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 
Interface bug

4. Additional information:
The city panel that appears over the cities isn't appearing. I can't click on it to go into the city, nor can I use it to bombard barbarians. Seems to be only a UI problem, and only in the balance patch as the unmodded game still has the enhanced UI fine. I redownloaded the compatibility folder. And I had used the automatic installer at first. Though I installed without the EUI at first as I didn't realize they weren't bundled together. After installing the rest of the game worked, but the city banner doesn't work. Thank you for your assistance. 

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Reinstall everything using the autoinstaller, doing the EUI install version. Make sure EUI ends up in your DLC folder.

**Comment by EKHawkman** [comment]
The reinstall seemed to fix it, at the very least the city panels appear now, but unfortunately it seems that the button to direct their ranged attack is still missing. It appeared when I first started, but it's ~70 turns later and now I can't bombard barbarians. 

Thank you for your help.

**Comment by Edaka** [comment]
Have you subscribed to CSD (City-State Diplomacy) via Steam perhaps? If so, you should unsubscribe and reinstall again.
