### ISSUE TITLE
Conquering Holy City + Great Prophet Issues

### ISSUE THREAD

**Issue by Kenpari** [LoneGazebo/Community-Patch-DLL#1904]
Bug Report Template

Mod Version (i.e Date - (4/23b)): March 9 v1.3.9

1. Mod List (if using standard CPP set, leave blank): r.e.d. Modpack 

2. Type of error (i.e. crash, interface bug, AI quirk): Game is unable to advance (stuck on "enhance religion")

3. Steps to reproduce: Conquer a Holy City of another civilization while having found no religion yourself (maybe unnecessary?) and having enough faith to produce a prophet. A prophet spawns in the newly conquered holy city and if you use the enhance religion feature, the game takes you to the "found religion" screen and no icons work. Game permanently stuck and unable to advance. Also notable:  the game lists you as "head" of the religion of the city you conquered. If you view the original founder, it also lists them as the head. This is also observable with AI conquering holy cities.

**Comment by Edaka** [comment]
This is a known bug in the 3/9 version that has long been fixed in the newer versions. I'm sorry, but the best fix would be upgrading to the latest beta.

**Comment by Kenpari** [comment]
Thank you for letting me know. Might I ask how stable the current beta version is? Never had any apprehension about using versions in dev, just want to make sure they're good.

**Comment by Edaka** [comment]
I can tell you that the latest beta (5/21) is more stable than 3/9. The last couple of 'betas' were almost purely bugfixes. (:

**Comment by Kenpari** [comment]
Thank you so much for the help :)
