### ISSUE TITLE
Declined Deals Between Human Players Never Go Away

### ISSUE THREAD

**Issue by kriskow** [LoneGazebo/Community-Patch-DLL#1906]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21 w/EUI

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
interface bug

3. Steps to reproduce:
Player A offers Player B a deal and Player B declines said deal.

4. Additional information:
The deal notification icon never goes away and those two players are never able to offer deals to each other for the remainder of the game.  Replicated error in two games.  If one of the players leaves the game and the AI takes over, deals with the AI are able to be made though the notification icon still never disappears.  If a human player resumes control, deals still cannot be made.  Have tried workarounds such as launching diplomacy from different menu screens but there does not seem to be any way around the problem.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
This is an issue with Active Diplomacy. You need to report this to Jai-Der-Herr.
