### ISSUE TITLE
Nomad event doesn't give Unique

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1907]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21

1. Mod List (if using standard CPP set, leave blank): I started to try out more mods so please obvi feel feel to say its too many to report unless its an issue worth me making a separate test game for.

Your six with EUI
Enginseer's E&D Version and its add on thing
Enginseer's Mod Compatibility thing (chateau change turned off), Medieval and Ren buildings, Industrial buildings,  Building Upgrades, National Wonder Collection, Neolithic Wonders
Enlightenment Era and Xony's Compat mod
JFD Mercenaries
Commander Influence Borders
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians
Ice Free Coasts
Celtic City Names, Iroquoian City Names, Randomize City Names
NoAltitudeTraining (removes the Mt. Kilman promo)
My own thing that does various things, setting Barbarian exp to -1, changing the City States names to be less Eurocentric, and most complicated, making Panzer a CS unit and giving Germany JFD's Jaegar unit.

2. Type of error (i.e. crash, interface bug, AI quirk): Playing as Persia and was excited to get the nomad event and get a free Immortal, but then I got a regular Spearman instead. :( If this is intentional or just the way the coding has to work, perhaps the wording could be changed a little?

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Hokath** [comment]
This is intentional insofar as it uses "FreeUnitsTechAppropriate", which does what it says. If you got the event later on, you might get a Pikeman instead, or a Crossbowman, etc. G could probably change it to know about uniques, but I'm not sure if it's worth it.

**Comment by LoneGazebo** [comment]
Hokath is correct, it is intentional.
