### ISSUE TITLE
Galleass can enter oceans, caravans event bugged.

### ISSUE THREAD

**Issue by Rafs041** [LoneGazebo/Community-Patch-DLL#1908]
Mod Version (i.e Date - (4/23b)):
Lastest beta, 5/21

1. Mod List (if using standard CPP set, leave blank):
Info addict + standard CPP

2. Type of error (i.e. crash, interface bug, AI quirk): 
-Galleass can enter ocean tiles when upgraded from dromons
-Caravan event that should give a caravan in the capital gives a caravan in each city, going over the limit of trade routes

3. Steps to reproduce:
To have a Galleass that can enter oceans, you need to upgrade it from a dromon, but not before getting astronomy (upgrading before astronomy results in normal galleasses that cannot enter oceans)
Caravan event just requires to chose the caravan instead of the gold tax or the +1 gold on coastal cities.

**Comment by Edaka** [comment]
I think the galeass issue only happens if you have Astronomy research. I've had that, too. If you upgrade a dromon to a galeass before Astronomy, it can't enter oceans.

**Comment by LoneGazebo** [comment]
Its because of how astronomy affects all units.

Caravan issue is known.

**Comment by Edaka** [comment]
Is it possible to have an exception check for the galeass?

**Comment by ilteroi** [comment]
well, that upgrade behavior seems to be by design ... if you upgrade a unit after astronomy, it loses the negative "cannot enter ocean" promotion. it's a bit strange, but i guess it makes sense, from a certain perspective :)

**Comment by LoneGazebo** [comment]
No, Edaka - it is by design, as ilteroi noted.

**Comment by Edaka** [comment]
Oh well, I suppose it does make sense. What's weird is that already existing galeasses (is that even a correct plural form?) don't gain the ability to enter oceans after researching astronomy. You have to upgrade them from dromons for that.

**Comment by LoneGazebo** [comment]
Yeah. Think of it is as targeted retrofitting. :)
