### ISSUE TITLE
seaport gives to few prod and more lux monopoly bug, latest version

### ISSUE THREAD

**Issue by Shadzy19** [LoneGazebo/Community-Patch-DLL#191]
Seaport is only giving 1 production in stead of 3, the monopoly resources from tea, coral, amber, jade and olive dont work.

Im guessing the moreluxuries.xml file in the CBP - Compatibility with (EUI) isnt working?
I havent tried the non EUI version.

Edit: Just copied the rows from moreluxuries.xml into my normal CBP resourcechanges.xml file and now they get their monopoly bonus.

**Comment by LoneGazebo** [comment]
Sounds like a bug in that XML file. I'll give it a look. Thanks!
G
