### ISSUE TITLE
The old man and the sea

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1910]
Bug Report Template

Mod Version (i.e Date - (4/23b)):5/21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

The price for the lighthouse scales with era.
While I am genrally a great fan of scaling, here it doesn't seem right. No way I would ever pay the scaled amount to get a lighthouse, ao after the medevieal age this optios is moot.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
I'll look.
