### ISSUE TITLE
Followers for religious wonder

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1911]
Bug Report Template

Mod Version (i.e Date - (4/23b)):5/21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

I play on huge map. An for my wonder, 26% more followers are required. It should bve way less than 20%.
I remeber it working correctly in another game, so I don't know what has happend. Could it be that there are different thresholds set for the different wonders? Just guessing here.

![20160604125018_1](https://cloud.githubusercontent.com/assets/16065630/15807197/a740e626-2b57-11e6-8933-5e3179a2dc72.jpg)

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Edaka** [comment]
Already noted in #1802 . It's a bug with the recent beta, most likely.

**Comment by pandasnail** [comment]
For me, its just reads whatever Small is in the WorldSizes SQL. I switched it to what Large should be midgame (and deleted the cache) and it worked fine, tho the AI never built theres that game, not sure if changing it messed up their strategy or what. But yeah, scroll down to Huge, see what it should be and put that for Small. Or even pick your own percent choice, the numbers are as a percentage of the 'standard' 20% needed, ie 80 for Large meaning 16% needed.

**Comment by pandasnail** [comment]
But i've tried different wonders and that doesn't have an effect for me-its just always that Small number

**Comment by LoneGazebo** [comment]
Very odd. I'll take a look.
