### ISSUE TITLE
Possible XP Bug?

### ISSUE THREAD

**Issue by Kenpari** [LoneGazebo/Community-Patch-DLL#1913]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21 beta

1. Mod List (if using standard CPP set, leave blank):
Full CPP/Vox Populi install, R.E.D. Modpack, Calypso's colored religious icons, IGE (was not enabled at this time), NoBanLuxury mod, InfoAddict

2. Type of error (i.e. crash, interface bug, AI quirk): Gained 17 promotions in 2 turns with unknown source. Seven on turn 183 and 10 promotions on turn 184. None of these units were in combat. Playing Sweden. No Great General was born, so it's not from the ULA. Units also did not heal (relevant to ULA).

3. Steps to reproduce: Unknown

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log & Minidump http://puu.sh/phZQD/65cac67a5b.zip
2. Screenshots (if needed): http://puu.sh/pi14R/1078e4e3e1.jpg http://puu.sh/pi1jt/fb63afaa1d.jpg

**Comment by Hyronymus77** [comment]
Looks to me like you fulfilled two city state quests in a row where each city state rewarded your units with XP.

**Comment by Kenpari** [comment]
Oh really? I wasn't aware that city-state quests could award XP. Thank you for clearing it up. I did indeed capture two French cities that two separate city-states wanted me to capture.
