### ISSUE TITLE
Zeppelin combat preview broken vs naval units

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1914]
CP + CBO Version may 21 beta
When you have zeppelin selected and mouse over an enemy naval unit, combat preview is not shown.

**Comment by LoneGazebo** [comment]
Because, IIRC, you can't attack them. At least @ilteroi said he was going to make it that way.

**Comment by qqqbbb** [comment]
Zeppelins can attack naval units.

**Comment by ilteroi** [comment]
why would i say such a thing? :)

**Comment by LoneGazebo** [comment]
@ilteroi I recall this discussion when we first added zepps - naval v. hover units shouldn't happen.

**Comment by qqqbbb** [comment]
Why it should not happen?

**Comment by LoneGazebo** [comment]
Because the UI can't support it.

**Comment by qqqbbb** [comment]
Helicopters don't have this bug

**Comment by ilteroi** [comment]
don't really recall that. was the target in deep water?

**Comment by qqqbbb** [comment]
Combat preview is broken vs any naval unit, no matter in coast or ocean tile. Combat preview works vs embarked units.

**Comment by ilteroi** [comment]
but the attack itself works? then i assume it's a lua issue. don't know how to debug that.

**Comment by qqqbbb** [comment]
The attack works.

**Comment by qqqbbb** [comment]
Making zeppelin ranged fixes this bug.
