### ISSUE TITLE
Hovering units

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1915]
1. Melee units should have huge combat penalty vs them. 
2. They should ignore enemy ZOC. 
3. Zeppelins should have PROMOTION_NO_DEFENSIVE_BONUSES.

**Comment by ilteroi** [comment]
a lot of points here - it would really help if you make this a numbered list. some should be easy fixes, others seem hard to implement

**Comment by LoneGazebo** [comment]
Some of these are balance issues, not 'bugs.' They should be discussed on the forum.

G
