### ISSUE TITLE
Armored car combat class

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1916]
UNIT_ANTI_TANK_GUN does not have combat penalty vs helicopters. Changing its combat class to  UNITCOMBAT_ARMOR should fix it.

**Comment by LoneGazebo** [comment]
what, the helicopter's class? But it isn't armor.

**Comment by LoneGazebo** [comment]
Helicopters are anti-tank - having anti-tank work against anti-tank feels counterintuitive.

**Comment by qqqbbb** [comment]
Changing armored car's combat class to UNITCOMBAT_ARMOR should fix it.

**Comment by LoneGazebo** [comment]
what is it now?

**Comment by qqqbbb** [comment]
UNITCOMBAT_GUN
