### ISSUE TITLE
Flak targetting promotion

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1918]
CP + CBO Version may 21 beta
PROMOTION_ANTI_AIR does not provide combat bonus vs helicopters ,zeppelins or air units.

**Comment by LoneGazebo** [comment]
@ilteroi , can you confirm?

**Comment by ilteroi** [comment]
is that "bonus vs helicopters"? which is supposed to give 150% against helicopters? that seems crazy. but then it's quite specific. the pedia seems to be incomplete here, doesn't mention fighters and bombers ... and there's also a PROMOTION_ANTI_AIR_II, which does not appear in the pedia at all.

anyway, it's a generic promotion, should be covered by unitCombatModifier() - but then there's a strange hack there especially for mounted units - @LoneGazebo : did you put that in? it seems there may be a problem with unitCombatModifier() or getUnitCombatType() in general.

**Comment by LoneGazebo** [comment]
@ilteroi yes, because mounted ranged units do not have a unique combat class (and they can't, because of how the animation engine works). So we are stuck with the hack.
