### ISSUE TITLE
Trade AI for renewals - look at

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#192]

**Comment by LoneGazebo** [comment]
Also look at forced damage hooks.

**Comment by Hokath** [comment]
More info on the trade AI issue:
I propose my Incense for his Dye. He says no. I ask what he wants. He says same deal but will also give me gold and open borders.
Don't know how it's coded but perhaps they are valuing it negatively somehow?
Ty G
