### ISSUE TITLE
Combat preview text for PROMOTION_NAVAL_MISFIRE

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1920]
When you have a unit with PROMOTION_NAVAL_MISFIRE selected and mouse over an enemy unit, combat preview says "Bonus VS Domain: -25%". It should be "Penalty VS Domain".

**Comment by LoneGazebo** [comment]
But it is a -25% 'bonus.' There's no logic for +/- bonus/penalty text in the lua, so it has to be this way.
