### ISSUE TITLE
CSD building costs +summer palace

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1921]
Modz: VoxPop install w/ all trimmings

I noticed that the Palace of Science took 1 turn to build, seems all those ideology related CSD buildings have very low production costs according to my EUI.

On a related point, the Summer Palace (whose production cost is fine) gives a free Chancery. However, the Chancery is unlocked a whole 4 columns earlier, so there is almost no way that it will not already have been constructed if you are interested in the Summer Palace. Perhaps change the free building to a Wire Service?

**Comment by LoneGazebo** [comment]
Wire Service from a medieval building doesn't make much sense.

**Comment by LoneGazebo** [comment]
I'll look at costs.

**Comment by Hokath** [comment]
Summer Palace is Acoustics: second tier Renaissance. Wire Service is at Steam Power, which has Acoustics as a Prerequisite. Agreed it doesn't make much IRL sense though

**Comment by LoneGazebo** [comment]
Renaissance, not Medieval, sorry. I think it is okay. The free promotion and paper more than makes up for it.

**Comment by Hokath** [comment]
Sure, was just an observation.

**Comment by LoneGazebo** [comment]
Yeah. Not ideal, but I tried to space out CSD buildings/wonders as much as possible.
