### ISSUE TITLE
Pillage Frequence

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1922]
VoxPop full install

I've noticed that the AI doesn't seem to be using the pillage functions much if at all. Many times units could have saved themselves with the heal, and obv they should be pillaging iron and horses and what have you. Both barbarians and AI. 

Has something broken (or is it just me)?

**Comment by LoneGazebo** [comment]
They'll pillage if they want to or need to. If they're going for conquest they won't do it much, because it is not in their interest. In any case, I'll ping @ilteroi on this.

**Comment by ilteroi** [comment]
well, pillage is pretty low on the priority list .. but i'll see if i can hook it up to heal moves.

in other news though, the AI pillaged the heck out of my strategic resources yesterday :)
