### ISSUE TITLE
Inquisitor/GP faith cost

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1923]
Bug Report Template

Mod Version (i.e Date - (4/23b)):5/21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

Buying Inquisitors increases the faith costs of Great prophets each time.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Using EUI? Sure you aren't mistaking the faith required/faith cost value for GPs?

**Comment by Der-Zorn-Gottes** [comment]
Yes, I use EUI.
An every time I click on the faith purchase button of the Inquisitor, the number on the faith purchase button of the GP increases. 
I'll see if I can get a few pictures next time I play.

**Comment by LoneGazebo** [comment]
The functions don't interact. At all. Quite odd.
