### ISSUE TITLE
Interception promotions

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1924]
PROMOTION_INTERCEPTION_I, PROMOTION_INTERCEPTION_II,  PROMOTION_INTERCEPTION_III, PROMOTION_INTERCEPTION_IV
They use column InterceptChanceChange. Searching code for it makes me think they are not used in the game.

**Comment by LoneGazebo** [comment]
I don't think the promotions are even available. Probably a holdover from Civ4.

**Comment by qqqbbb** [comment]
Some units have them. Look at Unit_FreePromotions table.

**Comment by LoneGazebo** [comment]
I'unno. @ilteroi, did interceptchance get cut out of the DLL during the airplane rework?

**Comment by qqqbbb** [comment]
InterceptChanceChange was not used in vanilla dll either,

**Comment by LoneGazebo** [comment]
Alright...so I guess we just take it off the units? Which units?

**Comment by qqqbbb** [comment]
UNIT_DESTROYER 
UNIT_TRIPLANE 
UNIT_ANTI_AIRCRAFT_GUN  
UNIT_FIGHTER
UNIT_JAPANESE_ZERO
UNIT_MOBILE_SAM
UNIT_JET_FIGHTER
UNIT_MISSILE_CRUISER

**Comment by LoneGazebo** [comment]
I've looked into this, and I clearly see that interception chance is used.to choose the best interceptor: GetBestInterceptor

So I'm not going to take this away.
