### ISSUE TITLE
PROMOTION_RECON_BANDEIRANTES

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1925]
It's clearly OP. When BANDEIRANTES explore they get 10-20 gold, culture and GG points every turn. One way to fix it : add 'chance' column to UnitPromotions_YieldFromScouting and setting it to 50 for that promotion.

**Comment by LoneGazebo** [comment]
Adding another variable massively expands the size of the promotions memory use. Not gonna do that.

**Comment by LoneGazebo** [comment]
I may just remove the GG points element.
