### ISSUE TITLE
CBP - Compatibility Files (EUI) is breaking EUI?

### ISSUE THREAD

**Issue by somohexuals** [LoneGazebo/Community-Patch-DLL#1927]
Mod Version (i.e Date - (4/23b)):
- 2016-03-09

Mod List
* (if using standard CPP set, leave blank):

Type of error (i.e. crash, interface bug, AI quirk): 
* Interface bug

Steps to reproduce: 
* I just used the CPP/CBP set with EUI.

Additional information: 
* City health bars and names aren't appearing (even vanilla civs)
* I enabled my mods one at a time and it only occurred when I enabled CBP - Compatibility Files (EUI).
* I've tried deleting LUA sub-folders in (1) CPP and (2) CBP, but nothing happened.
* I've tried deleting the CityBanners folder in EUI, but nothing happened.
* I've tried deleting UnitPanel.lua (mentioned in the error log), but nothing happened.
* I've tried deleting CityBannerManager (mentioned in the error log), but nothing happened.
* I've gone over uninstalling and reinstalling multiple times so I don't think I'm doing anything incorrectly on that front.
* Where I found the EUI files: http://forums.civfanatics.com/downloads.php?do=file&id=21929
* Where I found the CPP/CBP files: https://mega.nz/#F!LV9QxZ4Y!nlCyP2abCZYr_fwLndtnKA
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/300760/Lua.zip)

**Comment by LoneGazebo** [comment]
See my post on civfanatics. This is a bad install, use the autoinstaller and make sure that EUI ends up in your DLC folder.

**Comment by somohexuals** [comment]
I saw your post on civfanatics so I tried reinstalling multiple times, but it never worked. At first, the installer was acting wonky so I was doing things manually, but now all of a sudden it works perfectly. x.x

This fixed it, sorry for wasting your time. Thanks for all your work. :D

**Comment by LoneGazebo** [comment]
No worries! Not a waste at all. Enjoy!
