### ISSUE TITLE
Coal plant correct PovertyHappinessChange?

### ISSUE THREAD

**Issue by biship** [LoneGazebo/Community-Patch-DLL#193]
I know medical labs reduce Poverty, but it also looks like Coal plants do to?
Coal plants description in game is "Increases Poverty"

From BuildingHappinessMods.sql

UPDATE Buildings
SET PovertyHappinessChange = '-10'
WHERE Type = '-BUILDING_MEDICAL_LAB' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );

UPDATE Buildings
SET PovertyHappinessChange = '-6'
WHERE Type = '-BUILDING_COAL_PLANT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );

**Comment by LoneGazebo** [comment]
That's a bug. I'll fix.
G
