### ISSUE TITLE
Ilteroi and Putmalk

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#1930]
@ilteroi and @mwhiter,

Alright, I've manually merged the latest corp dev and fefe into the master branch. Only one bug: 

Warning	3	warning C4018: '<' : signed/unsigned mismatch	C:\Users\Jeff\Documents\Visual Studio 2008\Projects\CommunityPatch\CvGameCoreDLL_Expansion2\CvCityConnections.cpp	402

Ilteroi, this is yours, so I leave to you. Let's sync up on the master and debug this. @mwhiter, how far along is the corp project? Is this something I can fill in the gaps with, or is there still critical functionality missing here?

**Comment by ilteroi** [comment]
fixed and pushed

**Comment by mwhiter** [comment]
Really, just needs testing to make sure everything is functional. I need to dedicate time to doing this. It's big changes.

**Comment by LoneGazebo** [comment]
@mwhiter I've spent the better part of the day debugging it. It was actually pretty darn close to being done. Mainly lua cleanup of the DLL lua code and some overlapping things.

**Comment by LoneGazebo** [comment]
I'll push my fixes and changes once I'm happy with them.

**Comment by mwhiter** [comment]
Hope it wasn't too bad to debug. Thank you!

**Comment by LoneGazebo** [comment]
Not too bad, no. Mainly just trying to get all the lua to play nicely.
