### ISSUE TITLE
Puppeted cities don't build buildings much.

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#1931]
Mod version (i.e Date - (4/23b)): 5/21

http://forums.civfanatics.com/showpost.php?p=14303133&postcount=53
I've noticed that puppets seem to be very unenthusiastic about building buildings as well. All I see them make are processes.

**Comment by Jotaro31400** [comment]
I don't know if it's an issue, sometimes I prefer to have 5 puppet cities which are doing processes than trying to finish a chancellery in 20 turns.

**Comment by Kenpari** [comment]
Thanks for posting this as an issue. Wasn't sure if it was or not. 

And @Jotaro31400 Sure, but when you know they can build walls in 1 or 2 turns and have 5 unhappiness from crime, it's a problem.
