### ISSUE TITLE
Meteor event choice 1 doesn't grant the iron when successful

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#1932]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

5/21

1. Mod List (if using standard CPP set, leave blank):

Vox Populi Complete with EUI
+
Faster Aircraft Animations Version 3
Global - City State Airbases Version 3
Global - Commander Influence Borders Version 1
InfoAddict Version 22
Quick Turns Version 10
Really Advanced Setup Version 15
Religion - Fixed Prophets Version 2
UI - Enhanced Demographics Version 6
UI - Summary Antiquities Version 2
UI - Summary Luxuries Version 13
UI - Summary Specialists Version 11
UI - Trade Opportunities Version 28

2. Type of error (i.e. crash, interface bug, AI quirk): 

Event issue.

3. Steps to reproduce:

Meteor event choice 1 doesn't grant the iron when successful.

4. Additional information:

Looking at PlayerEvents.sql there is no reference to the iron resource regarding this event.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Edaka** [comment]
Very similar to #1899 , closing.
