### ISSUE TITLE
Formating issue in UIText.sql

### ISSUE THREAD

**Issue by ErikSteiner** [LoneGazebo/Community-Patch-DLL#1933]
### Mod Version (i.e Date - (4/23b)):
Vox Populi 5/21

### 1. Type of error (i.e. crash, interface bug, AI quirk): 

1. Navigate to: (2) Community Balance Overhaul\Balance Changes\Text\en_US\UIText.sql
2. In line 388, there is something off: or simply converting people to your one, t
rue faith.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]
4. The "t" is not connected to "rue", is this intended?

**Comment by LoneGazebo** [comment]
Looks correct to me on my end...
