### ISSUE TITLE
No City-state spawning

### ISSUE THREAD

**Issue by Grimnakar** [LoneGazebo/Community-Patch-DLL#1937]
Hello, I have tried to search for similar issue but could't find anything, I am having this really weird issue where no city state will spawn when starting a match, the map is pretty much empty with me and my opponent

Mod Version (i.e Date - (4/23b)): March 9th 1.3.9

1. Mod List (if using standard CPP set, leave blank):
 Standard CPP EUI automatic installer

2. Type of error (i.e. crash, interface bug, AI quirk): 
Upon the start of the game, no city state will spawn on the map, regardless of the number selected on the game starting screen

3. Steps to reproduce:
It does that on every single game, no idea how to do it independently

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Custom map? Sometimes this happens on special/custom maps.

**Comment by Grimnakar** [comment]
No regular auto-generated map, continent, pangea etc...
