### ISSUE TITLE
Accept embassy deals don't end

### ISSUE THREAD

**Issue by magner58** [LoneGazebo/Community-Patch-DLL#1938]
1) Mod Version:
5/21 beta

2) Mod List:
- CPP core (disabled events)

- Manually installed EUI removing duplicate lua's from my \MODS(1) Community Patch\LUA\
-- CityBannerManager.lua, CityBannerManager.xml
-- CityStateDiploPopup.lua
-- CityStateStatusHelper.lua
-- DiploList.lua
-- DiploTrade.xml
-- InfoTooltipInclude.lua
-- LeaderHeadRoot.lua
-- LeaderHeadRoot.xml
-- NotificationPanel.lua
-- NotificationPanel.xml
-- ProductionPopup.lua
-- TopPanel.lua
-- TradeLogic.lua
-- YieldIconManager.lua
-- YieldIconManager.xml

3) Type of error: 

Trade deal logic bug? But unlike in [1733](https://github.com/LoneGazebo/Community-Patch-DLL/issues/1733) there are no negative values for turns in trade history

4) Steps to reproduce:

**Embassy for embassy:**
- make "accept embassy" deal with AI exchanging it for their "accept embassy"
- the deal is displayed as ended on the same turn, but actually lasts forever

**Embassy for GPT:**
- make "accept embassy" deal with AI exchanging it for GPT
- when the deal ends you stop receiving GPT, but still missing "accept embassy" on your side of trade screen

5) Additional information:

[logs.ZIP](https://github.com/LoneGazebo/Community-Patch-DLL/files/305155/logs.ZIP)
![civ5screen0003](https://cloud.githubusercontent.com/assets/13498110/15901033/ed6edbac-2da1-11e6-90a8-5f234d4bce30.jpg)
![civ5screen0004](https://cloud.githubusercontent.com/assets/13498110/15901032/ed6c7330-2da1-11e6-8f28-9ea2182e2fcc.jpg)

**Comment by magner58** [comment]
@LoneGazebo bother to leave any comment? At least so I would not open similar issues if I did something wrong.

**Comment by LoneGazebo** [comment]
See other.
