### ISSUE TITLE
American borders naturally stealing land in 4/1 version

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#194]
Mentioning this because I believe it was stated as fixed in this version. For what it's worth, I've only noticed conquered cities stealing other civs' land. In this instance, I have an annexed city that is occupied at the moment. I already accidentally stole the coal from La Venta, and an poised to steal land from the Ottomans. To clarify, this is happening naturally (I'm aware you can steal with gold).
![2015-04-07_00001](https://cloud.githubusercontent.com/assets/11132095/7038256/7a5ba628-dd74-11e4-96d2-984628c1c952.jpg)

**Comment by LoneGazebo** [comment]
That's a bug (the code shouldn't allow for that, though I know why it does). I'll fix.

The bug I fixed was worse – you could buy the land under a city tile!
G
