### ISSUE TITLE
Embarked zeppelin can attack units in water tiles.

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1940]
CP + CBO Version may 21 beta

**Comment by ilteroi** [comment]
i guess this one is for @Iamblichos

**Comment by LoneGazebo** [comment]
Perhaps - why don't we just forbid hovering units from melee attacking non-domain-land units? Seems simple enough.

**Comment by Iamblichos** [comment]
But hovering units can also attack sea units and with no preview...another domain problem. Do we want to forbid that too?

**Comment by LoneGazebo** [comment]
That's what I was saying - make it so that hovering units cannot melee attack naval units and vice-versa.

**Comment by qqqbbb** [comment]
If melee ships can't attack hovering units, then you can use cheap zeppelins to block enemy ships from entering coast tiles.

**Comment by LoneGazebo** [comment]
@qqqbbb, yes, theoretically true. The problem is that I don't believe the UI can ever support naval->hovering UI information and/or combat animations. If it can, we'll just leave it so that hovering cannot attack naval, but naval can attack hovering.

**Comment by qqqbbb** [comment]
Why not just make zeppelin a copy of helicopter? Helicopters are not bugged.

**Comment by LoneGazebo** [comment]
They are otherwise identical, @qqqbbb, so I'm not sure how one differs from the other (unless it is an issue of missing animations for the zep)

**Comment by qqqbbb** [comment]
They are not identical. Zeppelin is melee, heli is ranged.

**Comment by LoneGazebo** [comment]
Hmm. Maybe Zeppelin should be made ranged.

**Comment by qqqbbb** [comment]
Making zeppelin ranged fixes this bug.

**Comment by LoneGazebo** [comment]
Well let's just call it at that, then, eh?

**Comment by LoneGazebo** [comment]
@Iamblichos @ilteroi we're going to take the easy way out here.
