### ISSUE TITLE
Pioneer, colonist and Found column in Units table

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#1941]
In Units table there is Found column. It's true for settlers but false for pioneers and colonists. This does not seem to affect gameplay but it's the easiest way for a mod to find units that can found cities.

**Comment by LoneGazebo** [comment]
Why not UNITAI_SETTLE?

**Comment by LoneGazebo** [comment]
That's what the DLL uses.

**Comment by qqqbbb** [comment]
OK
