### ISSUE TITLE
Can not move great works

### ISSUE THREAD

**Issue by Ozog** [LoneGazebo/Community-Patch-DLL#1942]
Bug Report Template
[Can not move great works.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/308360/Can.not.move.great.works.zip)

Mod Version (i.e Date - (4/23b)):
3-9

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Interface, I can not move any great works.  In additions, as of when the first city is built, under the tourism > your culture tab I can only see a single city (regardless of how many have been created) 
and it appears that a great works exists in a cathedral, national monument, heroic epic and library special build (regardless of the existence of these buildings).

3. Steps to reproduce:
Every time I start a game, only using the Community Patch Project (3-9) installer; have cleared cache names times and re-installed mods

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
You have a mod conflict with a custom civ.

**Comment by Ozog** [comment]
I thought that as well, so I deselected them all, cleaned out the cache (which, in my experience normally solves this sort of issue) and it did not resolve the problem.  The only mods I had running were the Community Patch, customs civs at all.  Do I need to clean out the whole Mods folder or something else?

**Comment by LoneGazebo** [comment]
Remove the non-used mods from your MODS folder. LUA can still load even if a mod is not selected.

**Comment by LoneGazebo** [comment]
I'd also reinstall the CPP, just to be safe.

**Comment by Ozog** [comment]
Thank you for the advice, I will close this issue as soon as I get home to do all that stuff
