### ISSUE TITLE
city connection icons missing

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1943]
from the forums ... cities do not have the "connected to capital" icons although they are in fact connected (m_bRouteToCapitalConnectedThisTurn is true).

also, possibly you don't earn gold from the connection, but there's no isolation unhappiness.

**Comment by LoneGazebo** [comment]
Odd. You taking point on this, or should I look at it? I guess we both can, technically.

**Comment by ilteroi** [comment]
i have a hunch ... so don't bother yet

**Comment by LoneGazebo** [comment]
Coolio.

**Comment by ilteroi** [comment]
fixed

**Comment by LoneGazebo** [comment]
What was it?

**Comment by ilteroi** [comment]
some old code i forgot to update when i rewrote the city connection logic a while back. just regular stupidity.

**Comment by LoneGazebo** [comment]
Cool.
