### ISSUE TITLE
luxury resources mod

### ISSUE THREAD

**Issue by gregorium56** [LoneGazebo/Community-Patch-DLL#1944]
Bug Report Template
N.B. I searched this site and Civ fanatics, but I can't find this problem anywhere, sorry If I missed a post about this issue.

Mod Version 10th of june 2016. Community patch v.72, Community balance patch v. 13 and More luxuries- CBP edition v. 155

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Whenever I start a new Civ 5 game with the mods mentioned above and I want to improve a luxury resource, I can only improve the standard ones already present in Civ 5 unmodded version. New resources like jade are shown on the map, but I can't improve them (no logo for it) even with the right tech discovered (mining i this case). All the other tile improvements work just fine.

3. Steps to reproduce:
Created 3 games with all other mods removed with different civs, map type etc.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Make sure you are on .279 of Civ 5.

**Comment by gregorium56** [comment]
I am playing on v. 1.0.3.279 and I just downloaded all the mods last week, so I think all my mods are up to date as well.

**Comment by LoneGazebo** [comment]
Make sure you are enabling all the mods from the CPP, make sure that there aren't any duplicates/old copies of the mods in your mods folder, and when you enable them in-game make sure you are hitting next and starting a game via the mods menu.

**Comment by gregorium56** [comment]
I removed all my mods and re-installed the complete pack of the mod pack (6 mods) and I get the same bug. Although now it says that I need to research, let's say mining, and after I've researched it, still no icon to improve the resource. The tile next to it with salt gives no problems.

**Comment by LoneGazebo** [comment]
I would not recommend it - quite odd that you are having that issue. I'd post a thread in the CPP subforum, see if another user has experienced said issue.

**Comment by qqqbbb** [comment]
Try clearing the cache.

**Comment by gregorium56** [comment]
@qqqbbb  do you mean clearing the cache via steam? I have done that already.
@LoneGazebo I think I will try that as well.

**Comment by qqqbbb** [comment]
I have no idea what clearing the cache via steam is. 
in "%USERPROFILE%\Documents\my games\Sid Meier's Civilization 5" folder there is cache folder. You should delete it every time you install new version of CP.

**Comment by gregorium56** [comment]
I have empty maps (downloads and images) and 19 database files. I only removed the Civ5 mods database file previously. Can I remove all of them?

**Comment by qqqbbb** [comment]
Delete the cache folder.

**Comment by gregorium56** [comment]
Still the same problem.
