### ISSUE TITLE
Tier 3 Autocracy Tenet Air Supremacy does not provide Airport

### ISSUE THREAD

**Issue by kenneth1221** [LoneGazebo/Community-Patch-DLL#1945]
Mod Version (i.e Date - (4/23b)): 5/21 Modpack

The Tier 3 Autocracy Tenet Air Supremacy did not provide free airports in newly conquered cities after providing airports to almost every other conquered city. Airports are still present in all other cities. The bug did not affect the factories granted by the Imperialism policy.

I am not entirely sure what caused this bug. However, I believe that between conquering cities that received an airport and cities that I did not, I took the Gunboat Diplomacy Tier 3 Autocracy Tenet. This is the only possible interfering factor I can think of.

**Comment by LoneGazebo** [comment]
How many cities total?

**Comment by kenneth1221** [comment]
3 cities did not receive an airport. 
I own 75 cities total. All civs together, including City-States, own 160 cities.

**Comment by LoneGazebo** [comment]
75? Dang. I think there's actually a memory limit on free buildings, you may have hit that. I'll need to look.

G

**Comment by kenneth1221** [comment]
For some reason github's not allowing me to attach a ZIP with just the savefile in it. Sorry for not getting back to you sooner, I didn't quite catch your meaning.
