### ISSUE TITLE
Game crashes frequently

### ISSUE THREAD

**Issue by Muzinzafrika** [LoneGazebo/Community-Patch-DLL#1946]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 1.3.9

1. Mod List (if using standard CPP set, leave blank):

Really Advanced Setup

2. Type of error (i.e. crash, interface bug, AI quirk): 

Game crashes randomly but frequently, most often when loading a save, returning to menu or after having played a few turns (regardless of which turn in the game it is)

3. Steps to reproduce:

Not tried to reproduce it, however as I said it happens randomly.

4. Additional information:

This has started to happen after I started using the full CBP. I have also realized that RAS does not cause it as it happens regardless of whether I use it or not.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe dire
ctory)
3. Screenshots (if needed)

**Comment by ilteroi** [comment]
did you try without EUI?

**Comment by Muzinzafrika** [comment]
No but how could it possibly cause crashes?

**Comment by ilteroi** [comment]
i don't have a clue but it's a fact

**Comment by Edaka** [comment]
I see the version you;re on is 1.3.9, which should be the equivalent of 3/9. It's a pretty ancient (though the last official) release now and some crashes have been fixed in subsequent beta versions since.
