### ISSUE TITLE
AI unit production

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1947]
they are over their supply cap but still producing units ...

during autoplay to see production:
![image](https://cloud.githubusercontent.com/assets/1358966/15990235/a6ecd8fc-308d-11e6-9373-9e915fb6487c.png)

afterwards to see the production penalty:
![image](https://cloud.githubusercontent.com/assets/1358966/15990213/0590a13c-308d-11e6-9fb7-36e39b8ee0fd.png)

**Comment by LoneGazebo** [comment]
AI supply cap is way higher than human depending on difficulty. Stepping in to AI will drop this down. The AI actually can't produce units over the cap (it is forbidden in the dll)
