### ISSUE TITLE
AI Archeologist use

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1948]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 5/21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

The Ai will alway chose a landmark improvement inside it's own territory - even if the respective tile is outside of the working radius of any city. In this case, the Archeologist is wasted, and clearly a artifact should have been chosen. 
Might sound like a corner case, but it happend several times in my recent game.

3. Steps to reproduce:

4. Additional information:

**Comment by LoneGazebo** [comment]
They probably don't have any slots in their empire for artifacts.
