### ISSUE TITLE
AI builds too many siege units

### ISSUE THREAD

**Issue by magner58** [LoneGazebo/Community-Patch-DLL#1949]
Mod Version: 5/21 beta

AI seems to build way too many siege engines - about equal to number of other units. I have horse as required resource for siege engines - could it be the cause?

**Comment by magner58** [comment]
@LoneGazebo bother to leave any comment? At least so I would not open similar issues if I did something wrong.

**Comment by LoneGazebo** [comment]
I noted on latest version  that I was closing all existing issues as they were all dealt with.

**Comment by magner58** [comment]
Ah, sorry, didn't notice that - I will give new version a try and see if the issues are reproducible.
