### ISSUE TITLE
DoF/common ideology bug

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#195]
4/1 version, all mods on how to install page save for Health and Plague.

I was friends with The Ottomans for a long time before they ended out friendship due to warmongering. A couple turns later, they picked Freedom (as I had done earlier) and were denounced by Portugal and Babylon for doing so. They also talked smack to me for associating with them, as if we were still friends.

The next turn, the RA we had was completed. The game still has us listed as friends (and is treating us as such), so I went to sign another RA. However, the game says we need a DoF to do so.

![2015-04-07_00002](https://cloud.githubusercontent.com/assets/11132095/7038334/d17878fe-dd75-11e4-8f34-109281a4bc2e.jpg)
![2015-04-07_00003](https://cloud.githubusercontent.com/assets/11132095/7038333/d175ed28-dd75-11e4-9cee-b69af37c002f.jpg)

I have also never asked them to not spy on me and have never demanded they not settle near me.

**Comment by LoneGazebo** [comment]
That's a bug in EUI, not the code (the DOF thing), as I don't think EUI refreshes properly when it should. I'll check.

Also not sure re: those tooltips. I've seen that reported, but I haven't encountered it yet. If you can upload your save, I'll give it a look (let me know what mods you have).
G

**Comment by joosegoose** [comment]
I'm using CP, CBP, CSD, C4D, More Lux, E&D, and Religion-Fixed Prophets (whoward). This is the 4/1 version, and obviously I am using EUI with compatibility.

Save file - https://www.dropbox.com/s/92spov9wb9is194/Check%20EUI%20diplo%20tooltips.Civ5Save?dl=0

For the record, I see tooltips such demanding not to settle with at least one civ probably every single game. I'd imagine it shouldn't be to hard to recreate.
