### ISSUE TITLE
cultural victory did not trigger

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1950]
playing a medieval start with poland.

now i'm influential on all other players (and have been for at least 10 turns), but still no victory ...

![image](https://cloud.githubusercontent.com/assets/1358966/15992344/ed72f220-30c9-11e6-9329-b1502dff8b3a.png)

**Comment by Edaka** [comment]
You have to have an ideology adopted and your people must be 'Content', if I remember correctly.

**Comment by ilteroi** [comment]
ah. good point. maybe that should be noted in the UI somewhere

**Comment by LoneGazebo** [comment]
It is. See victory screen. :)

**Comment by ilteroi** [comment]
ok then :)
