### ISSUE TITLE
New Social Policies Not Applied

### ISSUE THREAD

**Issue by tdors** [LoneGazebo/Community-Patch-DLL#1951]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 1.3.9 (3-9)

1. Mod List (if using standard CPP set, leave blank):  Only the CPP Set 1,2,3,4,5,6a

2. Type of error (i.e. crash, interface bug, AI quirk): Bug?  Social Policies do not Change to the new set.

3. Steps to reproduce:  Uninstalled Civ 5, Removed all Directories, reinstalled from Steam, reinstalled CPP Executable with all options, enabled all mods.

4. Additional information:
I installed CPP based on a friend's recommendation.  Worked great the first time.  I played one game for about 100 rounds, saved my game, came back the next day, that game would not open.  None of the autosaves from that game would open.  All other games would open and new games would work.  When starting new games, I noticed that the old Social Policies were still there, I tried removing the mods and adding them back.  No change.  I spent the afternoon today uninstalling Civ 5, removing all the directories in Program Files and My DOcs.  I reinstalled Civ 5 from Steam, and then installed the CPP from the executable with all options.  Went back into Civ 5 and enabled all the mods.  Started a new game from scratch - same thing, the old Social Policies are still there.  I followed all the instructions to a T.  removed the cache, logs, and moduser data folders just in case.

[Lua - Copy.log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/311016/Lua.-.Copy.log.txt)
[Database - Copy.log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/311017/Database.-.Copy.log.txt)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Are you loading the mods, enabling them, and starting a game through the mods menu?

**Comment by tdors** [comment]
Wow, thanks for the easy fix.  I'm new to running mods and didn't realize I needed to go through the mods feature each time.  Thanks.
