### ISSUE TITLE
Different Turns?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1952]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
5/21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Interface bug probably.

3. Steps to reproduce:
Just accept any agreement to declare war on a third-party civilization and the turns are different!

![image](https://cloud.githubusercontent.com/assets/13937047/15996620/7d49e0d4-30de-11e6-817c-9e29c3cf22a7.png)
![image](https://cloud.githubusercontent.com/assets/13937047/15996636/cf706824-30de-11e6-8f9a-8cdff25ebb1b.png)

**Comment by LoneGazebo** [comment]
10 is minimum duration, 15 for epic, IIRC. Looks like an EUI issue.

**Comment by TechpriestEnginseer** [comment]
but I'm playing on standard game speed however.

**Comment by LoneGazebo** [comment]
I'unno. I think it is still an EUI thing.

**Comment by LoneGazebo** [comment]
I looked and found. Vanilla bug, actually. Fixed.
