### ISSUE TITLE
Unit given by event error

### ISSUE THREAD

**Issue by holder8** [LoneGazebo/Community-Patch-DLL#1955]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
5/21

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Event Error

3. Steps to reproduce:

4. Additional information:
In inheritance event, I chose a son who caravan merchant in order to take one caravan unit on my capital city. 
But after I have chosen, Six caravans appear in my all cities even over the limit of trade routes. 

![civ5screen0000](https://cloud.githubusercontent.com/assets/19889762/16044863/1ed59224-3281-11e6-9b32-8147157e5cf6.jpg)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
This is a known issue, closing. Thanks for reporting.
