### ISSUE TITLE
AI offering empty deal

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#1958]
![image](https://cloud.githubusercontent.com/assets/1358966/16057594/185f2140-327b-11e6-8d07-ce537c3c514f.png)

this is supposed to be a peace deal ...

**Comment by LoneGazebo** [comment]
Hmm, are you getting a lua error?

**Comment by LoneGazebo** [comment]
@ilteroi,

In other news, I'm getting a fairly consistent crash here:

/// When nothing better to do, have units patrol to an adjacent tiles
void CvHomelandAI::PlotPatrolMoves()
{
#if defined(MOD_AI_SECONDARY_SETTLERS)
	if (MOD_AI_SECONDARY_SETTLERS && !m_pPlayer->isMinorCiv()) {
		// Find any units with a secondary role of settler and check for opportunistic city founding
		PlotOpportunisticSettlementMoves();
	}
#endif
	
	ClearCurrentMoveUnits();

	// Loop through all remaining units
	for(list<int>::iterator it = m_CurrentTurnUnits.begin(); it != m_CurrentTurnUnits.end(); ++it)
	{
                 UnitHandle pUnit = m_pPlayer->getUnit(*it);

happens at final point. Looks like a bad it iterator.

**Comment by ilteroi** [comment]
hmm. never seen that. also a pretty unlikely place for a crash, not much can go wrong there ... how to reproduce?

**Comment by LoneGazebo** [comment]
It is random. May have been an observer issue. We will see if anyone reports it.
