### ISSUE TITLE
Unit focus shifts to another unit midway through 1st unit's movement

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#1959]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
June 14 beta

1. Mod List (if using standard CPP set, leave blank):

+FlagPromotions v7
+InfoAddict v22

2. Type of error (i.e. crash, interface bug, AI quirk): 
Quirk in the unit movement and active unit focus.

3. Steps to reproduce:
Early on my scout gains the 1st promotion that grants extra movement in forest/jungle and whenever that unit has less than a whole movement point to expend the focus shifts to the next available unit. You then move that unit until all it's movement is expended and then the focus shifts back to the scout and you move one more time.

Additionally the unit icons are remaining highlighted, as though there are still moves left, for a few seconds before the bottom-right button changes to "Next turn". This gives the impression that you can still move it and the unconscious thing to do is continue to press the movement key which means the next turn that unit starts with that keypress, which effectively means after the AI have moved that unit only has 1 movement point. Dangerous if an enemy has moved into vision during the AI turn. 

4. Additional information:
I could provide logs but looking through them doesn't seem to show any indicators about this behaviour.
Let me know and I'll add them if needed.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by GrantSP** [comment]
Secondary quirk of this bug is if your promoted scout starts its movement in terrain that it is now quicker in, the focus is shifted away from it, or its icon becomes dulled and the "Next turn" button highlights even when there may be a complete turn left.
e.g. if there a 4 jungle/forest tiles that the scout may move through, which it can if promoted, the focus is removed after just 2 tiles are traversed and you need to manually select this unit again to move the next 2 tiles.

**Comment by LoneGazebo** [comment]
@ilteroi is this a consequence of your 'wait' break you added to unit missions?

**Comment by ilteroi** [comment]
possibly maybe. although i haven't seen this and i did play manually for a bit :)

**Comment by ilteroi** [comment]
i'll be busy in the coming days, so here's what i changed:

			//if the pathfinder inserted a stop node because the next plot is occupied
			//we see that the expected moves are greater than what we have right now
			//in that case don't execute the move
			if (pPathPlot && m_kLastPath.front().m_iMoves>getMoves())
			{
				return 0;
			}

disable this and you should be back at the previous behavior (which may result in illegally stacked units however)

**Comment by GrantSP** [comment]
Just in case that isn't the case, the error shows when the unit is embarked also.
ie. all embarked units move 3 tiles and the focus shifts away after only 2 so one of those variables in the above code snippet may be looking at the wrong value, e.g. the unit's default move value not the current.
