### ISSUE TITLE
New Version Explorer unit error

### ISSUE THREAD

**Issue by holder8** [LoneGazebo/Community-Patch-DLL#1960]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6/14

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

Explorer have no Flag icon in strategic view.

![civ5screen0001](https://cloud.githubusercontent.com/assets/19889762/16068059/7ccf4b1e-32fd-11e6-97b7-65d35ed96e57.jpg)

![civ5screen0002](https://cloud.githubusercontent.com/assets/19889762/16068061/83aa2094-32fd-11e6-9a92-cc30febad79e.jpg)

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
I'll look. Any other mods to speak of?

**Comment by holder8** [comment]
Nothing but IGE (to test this)

**Comment by Hokath** [comment]
Before this version, I noticed they used the Tercio icon in strategic view
Will check once I tech there in my game
