### ISSUE TITLE
Request For Help Empty Bug

### ISSUE THREAD

**Issue by Frozen-In-Ice** [LoneGazebo/Community-Patch-DLL#1961]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
June 14th

1. Mod List (if using standard CPP set, leave blank):
Full Vox Populi with EUI, plus IGE, Info addict, Really Advanced Setup, Faster Aircraft Anims, Quick Turns.

2. Type of error (i.e. crash, interface bug, AI quirk): 
Was asked for help from an AI, except the help screen was blank. Clicking accept did nothing, so I had to hit decline and so I incurred a diplomatic penalty.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

3. Screenshots (if needed)
![20160615003158_1](https://cloud.githubusercontent.com/assets/19610489/16068224/46506b4c-3292-11e6-9ccf-f7ae9f5e671f.jpg)

**Comment by LoneGazebo** [comment]
What version? If not on latest version, update to latest.

**Comment by holder8** [comment]
He said 6/14 the latest

**Comment by Frozen-In-Ice** [comment]
Yup, this was the latest 6/14 version

**Comment by LoneGazebo** [comment]
Gotcha. Lua log?

**Comment by Frozen-In-Ice** [comment]
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/317213/Lua.zip)

**Comment by LoneGazebo** [comment]
I don't see anything off...I'll look at the code.
