### ISSUE TITLE
CTD at End of Turn 1-3

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#1962]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6/14 (using installer .exe; Installed standard mod settings including EUI)

1. Mod List (if using standard CPP set, leave blank):
R.E.D. Modpack

2. Type of error (i.e. crash, interface bug, AI quirk): 
Crash to desktop during AI turns or when performing any action (like moving a unit over ruins) that brings up a GUI prompt.

3. Steps to reproduce:
Was able to reproduce consistently by starting a new game with standard game settings (Random Civ, Large Map, Prince difficulty, Epic game length). In 12 attempts, the CTD occurred during the AI turn processing after ending my first turn. In one attempt the CTD occurred in Turn 3 after walking over an ancient ruin tile. At first I was using the Communitas map, but decided to switch to a vanilla Continents map after having heard Communitas was unstable. CTD occurred consistently regardless of map type used.

4. Additional information:
Latest version of mod was installed using the automatic .exe installer. Previous versions of mod had been manually uninstalled prior to latest installation. Civ5 game is updated to latest Steam version and I have all DLC installed.

I have no screenshots or log files on hand, but I can add them to this report once I get back home in the evening.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Try it without RED.

**Comment by cdanger341** [comment]
Okay, I was wondering if that might be the issue. RED did not seem to interfere with the last beta build, but I will try it without RED this evening and see if the CTD is still reproducible.

**Comment by Vyyt02** [comment]
There are similar CTD reports like yours - they say their tech tree is messed up too. Would you check your tech tree? If it is messed up, then yours and these reports can be merged into one.

I am not really helping here, am I? :-)

**Comment by cdanger341** [comment]
Sure, I'll check the tech tree as well. I should be able to post an update around 5-6pm CST today.
