### ISSUE TITLE
some civpedia stuff

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1963]
Lighthouse strategy still mentions the sea resources bonus

The following resources aren't mentioned for resources in any of the new Corporation Overviews, (I'm assuming they still function right, haven't tested): amber coral jade lapiz lazuli tobacco

On the civilized jewelers page the resource jewelry is misspelled as jewelery

Giorgio's summary says one trade route, but its two 

Police Station's Game Info says it reduces enemy spy stealing rate by 25%, but its really 50%

Finally, the Grocer game info still says 25% instead of 15%. I should prob stop bothering you so much, I know you're busy, but I get OCD once I've started these kinds of things. I'll stop posting civpedia stuff if you want tho.

**Comment by LoneGazebo** [comment]
No worries. I look forward to your proofing. :)
