### ISSUE TITLE
Tech tree interface bug

### ISSUE THREAD

**Issue by Glidergun** [LoneGazebo/Community-Patch-DLL#1965]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

6-14

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

Interface bug

3. Steps to reproduce:

Start game, go into tech tree.

4. Additional information:

Scroll bar is missing, so there's no way to scroll. The "Classical era" header is dropped under the techs; I can't see any further to the right, so there's no way to tell what else is messed up. See attached image.

Does not happen with CP and CBO only.

May be related to [https://github.com/LoneGazebo/Community-Patch-DLL/issues/1964](url)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

![all mods](https://cloud.githubusercontent.com/assets/19953938/16084271/ca485450-32dd-11e6-899e-35c1c98fe3bc.jpg)

**Comment by LoneGazebo** [comment]
lua log?

**Comment by Glidergun** [comment]
Right! Sorry, I forgot I'd only put up logs for the other bug.
[Lua log.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/317544/Lua.log.zip)

**Comment by LoneGazebo** [comment]
Okay, I see the lua error, but I don't see what it references - tell me, are you using EUI or no-EUI compatibility files? If EUI, did you use the auto-installer, or did you do it manually? If manually, did you grab the latest EUI from the downloads folder?

**Comment by Glidergun** [comment]
No-EUI.

**Comment by LoneGazebo** [comment]
Alright, I think I've found it. I'll add it to the upcoming hotfixhotfix shortly.
