### ISSUE TITLE
Couple of promotion questions

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1966]
According to the WHoward mod at least, Medic is no longer on Barrage II and Drill I (or any Barrage or Drill). Tested out Drill I, and it in fact wasn't there. Intentional?

Similarly, it no longer lists Logistics for Boarding Party III. Shouldn't it be Blitz for melee units anyway?

The following ranged promotions all say Combat Strength instead of RCS, which I think is a typo, I mean they all work like I would expect from it being RCS I think: All three Barrages, Targetings, Bombardments, and Volley

**Comment by LoneGazebo** [comment]
The Whoward mod doesn't show all things properly. That said, Medic is only available from a few specific primary promotions now, not all of them.

**Comment by pandasnail** [comment]
I realize the Whoward mod isn't perfect, but usually it gets things like Medic right. And if my chart on promotions was right, Medic used to be on Drill I, and I attacked a barb camp long enough to confirm it isn't now. But if its intentional, okay, cool, was just checking.

**Comment by LoneGazebo** [comment]
Medic is on these promotions now:

<PromotionPrereqOr1>PROMOTION_SHOCK_2</PromotionPrereqOr1>
			<PromotionPrereqOr2>PROMOTION_SCOUTING_2</PromotionPrereqOr2>
			<PromotionPrereqOr3>PROMOTION_SURVIVALISM_1</PromotionPrereqOr3>
			<PromotionPrereqOr4>PROMOTION_BOARDING_PARTY_1</PromotionPrereqOr4>
			<PromotionPrereqOr5>PROMOTION_COASTAL_RAIDER_2</PromotionPrereqOr5>
			<PromotionPrereqOr6>PROMOTION_ACCURACY_1</PromotionPrereqOr6>
			<PromotionPrereqOr7>PROMOTION_WOODLAND_TRAILBLAZER_II</PromotionPrereqOr7>

**Comment by pandasnail** [comment]
Ok, looks like WHoward had it right then. Surprised you made Drill worse, but since its not a bug, I'll close this. (I'm assuming the Boarding Party one is intentional too as well.)

**Comment by LoneGazebo** [comment]
Yep! Drill's Tier IV is pretty solid, and also Drill gets Cover I earlier and Siege/Formation/Ambush are all unique to it. So it has perks.

**Comment by pandasnail** [comment]
Pressed reopen because I guess I do have bugs now:

Siege has this

<PromotionPrereqOr1>PROMOTION_SHOCK_3</PromotionPrereqOr1>
			<PromotionPrereqOr2>PROMOTION_DRILL_2</PromotionPrereqOr2>

and Ambush has

<PromotionPrereqOr1>PROMOTION_SHOCK_2</PromotionPrereqOr1>
			<PromotionPrereqOr2>PROMOTION_DRILL_2</PromotionPrereqOr2>

**Comment by LoneGazebo** [comment]
Sorry, misspoke. Meant to say that Drill gets them earlier (except Ambush, which I now recall making even because it is a late-game tech based promo).
