### ISSUE TITLE
Production Ruins don't scale with gamespeed

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#1967]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

1. Mod List (if using standard CPP set, leave blank): EUI Version

2. Type of error (i.e. crash, interface bug, AI quirk): 6/14

3. Steps to reproduce: Screenshot one is on quick speed, screenshot two is on marathon speed, they both give 40 production. And they really do both give 40, its not just the wrong number being displayed on the graphic

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![quick](https://cloud.githubusercontent.com/assets/16260521/16088756/9447771e-32f6-11e6-99d7-e1dacb86d4c2.jpg)
![marathon](https://cloud.githubusercontent.com/assets/16260521/16088762/9864d558-32f6-11e6-95fb-98508e9128af.jpg)

**Comment by LoneGazebo** [comment]
I'll look.
