### ISSUE TITLE
Unclosable corporation screen

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1968]
Bug Report Template

Mod Version (i.e Date - (4/23b)):6/14

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

After starting a new game, the corporation screen is open and cannot be closed.
![20160615203547_1](https://cloud.githubusercontent.com/assets/16065630/16092647/0225c14a-3339-11e6-87a1-24944fb2261a.jpg)

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Lua log?

**Comment by Der-Zorn-Gottes** [comment]
Here.
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/318614/Lua.zip)

**Comment by LoneGazebo** [comment]
Using any of JFD's mods? I know one of them adds a corporation.

**Comment by Xaragas** [comment]
Gazebo - I am getting the same bug.  Running non-EUI version and only the core 6 files.

The JFD mod that caused issues in the past was Exploration Expanded Continued.  I made sure that was not enabled
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/319588/Lua.zip)

**Comment by LoneGazebo** [comment]
You are getting database errors related to old mod content - make sure you cleared your cache and that you are only running the latest mods.

**Comment by Xaragas** [comment]
Running version 16-5-1.  Deleted the mods, re-ran the installer, cleared cache and still having issues.
[Database & Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/319762/Database.Lua.zip)

**Comment by LoneGazebo** [comment]
The lua and database errors you are getting are from old mod data blending with new lua. You are positive that all of the mods you are enabling are from the latest version? Clear your mods folder entirely and install it.

**Comment by Der-Zorn-Gottes** [comment]
I deleted mod folder, and unsubscribed two custom maps from steam workshop. Then I reinstalled, and that did the trick.
So maybe a conflict with - a map?

**Comment by LoneGazebo** [comment]
No, probably old content in the mod folder. Glad it worked!

**Comment by Xaragas** [comment]
Don't know if you look at the closed issues, but this worked for me also.

I scanned the mods folder and did not see any old content.  Clearing out the folder and reinstalling worked.

Thanks
