### ISSUE TITLE
Corporation typos (6/14)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#1969]
1.Jewelry

`[ICON_RES_JEWELERY] Jewelery`

should be

`[ICON_RES_JEWELRY] Jewelry`

cf. related files
(2) Community Balance Overhaul\Modular Elements\Corporations\Text\en_US\CorpText.xml
(6a) Community Balance Overhaul - Compatibility Files (EUI)\Corporations\Text\CorpText_en_US.sql
(6b) Community Balance Overhaul - Compatibility Files (No-EUI)\Corporations\Text\CorpText_en_US.sql

-----
2.Resource Bonus tags (Compatibility Files)

`TXT_KEY_CORP_HELP_***`

Should be

`TXT_KEY_CORPORATION_***`

cf. related files
(6a) Community Balance Overhaul - Compatibility Files (EUI)\Corporations\Text\CorpText_en_US.sql
(6b) Community Balance Overhaul - Compatibility Files (No-EUI)\Corporations\Text\CorpText_en_US.sql

This file may fix the second issue.
https://www.dropbox.com/s/9o6uht82fakegu7/CorpText_en_US.sql?dl=0

**Comment by LoneGazebo** [comment]
Thanks!
