### ISSUE TITLE
The Return of the CTD in the First Few Turns of a New Game

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#1971]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6-15 Hotfix version

1. Mod List (if using standard CPP set, leave blank):
R.E.D. Modpack

2. Type of error (i.e. crash, interface bug, AI quirk): 
Crash to desktop during 2-3rd Turn.

3. Steps to reproduce:
This is similar to the CTD issue in the previous version, but now the scripts for unit movement appear to be working. At least, my own units do not appear to think they have multi-turn movement orders even if I only move them 1-2 hexes. Moving on Ruins also no longer immediately causes a CTD, but something else is still causing within the first three turns of the game, regardless of chosen game options (map, map size, game speed, etc.).

4. Additional information:
Dump log: 
[CvMiniDump 201606152154.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/317586/CvMiniDump.201606152154.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
@ilteroi, still breaking at patrol moves, so there's still something up with it. I'm going to disable patrols for now.

**Comment by LoneGazebo** [comment]
Disabling patrols fixes the issue. Not sure what's up with that, and I haven't had time to debug it.

**Comment by cdanger341** [comment]
Just to have it said, using 6-15-1 has caused the CTDs to go away, but as you said, the patroling is disabled. This has caused the AI to begin leaving their military and scouting units in bizarre locations. For example, they move a unit to the end of a peninsula and then just leave it there until war or barbarians trigger them to move again, as if they are unwilling to move it back across hexes it has already traversed.

**Comment by LoneGazebo** [comment]
Yep. It is a temporary fix until ilteroi has time to sort it. Odd thing is that I can't replicate the CTDs anymore with it enabled. Odd odd...
