### ISSUE TITLE
Events Balance

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#1972]
Going to jot down the things I notice in my current game here.

1. Man and the Sea: The more expensive option that gives +2 food to fishing boats doesn't last long enough in my opinion. It is considerably more expensive than the other option, and you need to be working 4+ boats for it to give more food (before modifiers, dont know how they interact with flat yields)

**Comment by Hokath** [comment]
I noticed {4_GPChange} fails for Great Diplomats, in so far as it calls them Great Civil Servants

**Comment by LoneGazebo** [comment]
Oh, that's probably because the specialist is called a Civil Servant. I should probably change the name to Diplomat from Civil Servant. Re: Old man and the sea, we should probably start a thread on 'event balance.'

**Comment by LoneGazebo** [comment]
I fixed the Civil Servant issue, so the tooltips/notifications now grab the Great Person name.

**Comment by Hokath** [comment]
Senpai, notice me
http://forums.civfanatics.com/showpost.php?p=14339888&postcount=142

I think this would work nicely on top of the era scaling yields.
Please bear in mind, it took me forever :D

**Comment by Edaka** [comment]
Goodness gracious, Hokath! Isn't that a whole load of new events from you! Looks like you've put much good effort into those. I hope you don't mind if I try all of them out (including civ unique events, etc.).

**Comment by LoneGazebo** [comment]
Awesome! Sorry I missed this post!

**Comment by Hokath** [comment]
Thanks! Of course you may try them! I haven't tested all the civ unique ones yet so some of them may just die in the database, since im still making more. The readme is in chronological order, and I think they should work up to denmark for sure (subject to small errors of course). Would help a bunch if you could tell me any issues you found - you can open a post over on that github. All the best.

**Comment by Edaka** [comment]
Yeah, I definitely will report any odd event behaviour that I may find there. That being said, I think this ticket can now be closed.
