### ISSUE TITLE
No happiness is shown while running 6.15.1

### ISSUE THREAD

**Issue by gstew32** [LoneGazebo/Community-Patch-DLL#1974]
Bug Report Template

Mod Version (i.e Date - (4/23b)):6.15.1

1. Mod List (if using standard CPP set, leave blank): 

2. Type of error (i.e. crash, interface bug, AI quirk): I have been running BETAs of CPP successfully for several versions and after installing 6.14 yesterday and also 6.15.1 today I noticed that happiness is no longer showing up in my city screen either on the left side (used to be light blue in my non EU version) nor when I hover over the city name.  I followed the standard installation instructions so shouldn't
have any carryover bugs from previous games.  
![civ5screen0000](https://cloud.githubusercontent.com/assets/19974920/16117605/90175ffe-3398-11e6-913c-9d01df2aff37.jpg)
![civ5screen0001](https://cloud.githubusercontent.com/assets/19974920/16117606/94d52fda-3398-11e6-96d7-669bdd4a4711.jpg)

Furthermore when i reinstalled 5.21 the happiness display returned to my game.

3. Steps to reproduce: Happens every time I run a game.  Everything else appears to be working correctly.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Try reinstalling, make sure you are enabling the compatibility mod.

**Comment by LoneGazebo** [comment]
Also, update to the latest version.
