### ISSUE TITLE
TRADE_ROUTE_BASE_GOLD -100?

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#1975]
While merging the update (I keep some custom changes), I've noticed that TRADE_ROUTE_BASE_GOLD went from 50 to -100. Is this correct?

**Comment by LoneGazebo** [comment]
Yep. That's a city connection thing.

**Comment by Oscar-IronTower** [comment]
Cool :salute:
