### ISSUE TITLE
Improvement - Vassal Screen

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#1978]
This would be for Putmalk, I believe.

Basically, what I would like to see is an overview of the actual yield benefits in one place. Currently, to see the Science/Culture/Faith benefits I have to manually hover over each yield to see it. Also, it would be good to include the gold cost of maintaining them.

This would be both as a general info + for each vassal. Here is my suggestion for the screen:

http://i.imgur.com/W7QXixu.png?1

Thanks!

**Comment by LoneGazebo** [comment]
Since Putmalk is gone for good, I'm going to close this.
