### ISSUE TITLE
Heritage gives +4 tourism for each World Wonder instead of +2

### ISSUE THREAD

**Issue by Taikavapu** [LoneGazebo/Community-Patch-DLL#1979]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

1. Mod List (if using standard CPP set, leave blank):
Full CPP
Flag promotions
Ingame Editor (for testing purposes)

2. Type of error (i.e. crash, interface bug, AI quirk): 
Heritage policy from Aesthetics creates a "Tourism from city"-named category into the Tourism breakdown, which is equal to the "Tourism from World Wonders" category (also created by the policy). This effectively gives +4 tourism for each World Wonder.

3. Steps to reproduce:

4. Additional information:
Some testing I did with IGE.
As you can see from the picture, I have 2 GWs each giving +2 tourism, and one world wonder, Stonehenge which gives +2 tourism. However there is an extra +2 tourism from "Tourism from city" which was created by the Heritage. Creating an additional World Wonder increases both "Tourism from World Wonders" and "Tourism from City" by 2, effectively giving +4 tourism. Only policies are Tradition opener, Sovereignty, Aesthetics opener, Humanism, Refinement and Heritage. No techs after Agriculture. Picture below.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

![20160616181341_1](https://cloud.githubusercontent.com/assets/19976711/16122006/22f3466c-33ee-11e6-899b-b896bb729f6a.jpg)

**Comment by LoneGazebo** [comment]
Interesting. I'll take a look.

**Comment by LoneGazebo** [comment]
I see it. Fixed.
