### ISSUE TITLE
Chariot archer Can Not move after attack.

### ISSUE THREAD

**Issue by holder85** [LoneGazebo/Community-Patch-DLL#1981]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6/15-1

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
miss the promotion

3. Steps to reproduce:

4. Additional information:
**Even though Chariot archers are mounted range unit, they have no promotion that 'Can move after Attacking'. It makes them useless.**

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Intentional. They're early game weak units.

**Comment by holder85** [comment]
hmm... They have only 1 range so they always just shoot once and die next turn in battle field.

**Comment by holder85** [comment]
hmm.. They have only 1 range. so they just shoot once and die next turn. too useless in battle field.
