### ISSUE TITLE
AI Civ got a lot of Caravens

### ISSUE THREAD

**Issue by holder85** [LoneGazebo/Community-Patch-DLL#1985]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6/15-1

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
**I think it is sort of event error.**

3. Steps to reproduce:

4. Additional information:
**AI player has lots of Caravens over the trade routes limit.**
When I found this bug, I'm leading in every things than AIs include Wonder(**Petra and Colosus**)
and I have 6 trade routes available but AI(Poland) had at least dozen of Caravens.
I think it may be a Event error like 'Inheritance event bug' that occured last version.

![civ5screen0001](https://cloud.githubusercontent.com/assets/19889762/16146493/473b2adc-34b9-11e6-9c89-3cefab17ae4b.jpg)
![civ5screen0000](https://cloud.githubusercontent.com/assets/19889762/16146497/4ab05d90-34b9-11e6-9d34-3adb4a9e8ca4.jpg)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
That is a lot of caravans.

**Comment by Vyyt02** [comment]
I can confirm this. I am playing with the 5/21 version, **I deleted the events**. Me and Austria are both in the Medieval era, I can see 8 Austrian caravans in the screen while I can only build 4 and this includes the one from Petra.

**Comment by LoneGazebo** [comment]
Yeah it is not an event issue. Will need to investigate.

**Comment by holder85** [comment]
Oh god... **AI's Caravans increase Continuously**. Now The Polish have 28 Caravans.

![civ5screen0002](https://cloud.githubusercontent.com/assets/19889762/16174650/289ac174-3607-11e6-8ddc-e5b5be8232f2.jpg)

![civ5screen0003](https://cloud.githubusercontent.com/assets/19889762/16174651/2ef40fa8-3607-11e6-9f95-738aaa122b16.jpg)

**Comment by LoneGazebo** [comment]
Running any other mods?

**Comment by LoneGazebo** [comment]
If you have logging enabled, post your cityaiproduction logs.

**Comment by holder85** [comment]
Here is the lua.log

[Lua-log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/322107/Lua-log.txt)

**Comment by LoneGazebo** [comment]
I need the cityaiproduction log, not lua log.

**Comment by holder85** [comment]
sorry. could you tell me where is that file?

**Comment by LoneGazebo** [comment]
You may not have AI logging enabled, that's fine.
