### ISSUE TITLE
Tech and policies trees remain unchanged

### ISSUE THREAD

**Issue by FatalDeath1** [LoneGazebo/Community-Patch-DLL#1986]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
June 15th (1.6.15)

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Tech and policies trees remain unchanged even after applying all of the mods.

3. Steps to reproduce:

4. Additional information:
I am using the English version.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files:
[Database - Copy.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/320662/Database.-.Copy.txt)
[Lua - Copy.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/320663/Lua.-.Copy.txt)

2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Make sure you are hitting next and starting a mod from the mods menu.
