### ISSUE TITLE
Instant city capture

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#1987]
1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

3. Steps to reproduce:
Attack a city with a naval unit from NON-ADJACENT tile.

4. Additional information:
 The bug itself and its relation to already noted "retreating unit bug" is located here http://forums.civfanatics.com/showthread.php?p=14317832#post14317832

---------------------------

**Comment by LoneGazebo** [comment]
Linking to other report regarding unit movement for @ilteroi.

**Comment by Gidoza** [comment]
Offering additional support and information (in case it's already known) - it seems like attacking any unit at all from more than one tile away will push it; normal combat only occurs if I move a unit adjacent to my intended target, and then attack.

**Comment by ilteroi** [comment]
closing as duplicate
