### ISSUE TITLE
Can not Categorize the monopolies list as strategic

### ISSUE THREAD

**Issue by holder85** [LoneGazebo/Community-Patch-DLL#1990]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6/15-1

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
**Strategic monopoly type in Monopoly window shows the same list with the All monopoly type category.**

![civ5screen0000](https://cloud.githubusercontent.com/assets/19889762/16173221/2f10ed9e-35d5-11e6-862a-6e03eacc4d15.jpg)

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed

[Lua-log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/321930/Lua-log.txt)

2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by mwhiter** [comment]
I believe this may be related to same issue here: #https://github.com/LoneGazebo/Community-Patch-DLL/issues/1988#issuecomment-226958853 as the Lua.log reports the same errors.
