### ISSUE TITLE
Project construction % values are not equal across the UI

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#1992]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
June 14th beta

1. Mod List (if using standard CPP set, leave blank):
+FlagPromotions
+InfoAddict

2. Type of error (i.e. crash, interface bug, AI quirk): 
The % values for the various world projects don't seem to match when viewed in the different UI options.

I'm assuming this is due to the lua pulling values at different times.
Maybe the notification is grabbing the stored value from the end of the last turn and the city banner is using the current values. I haven't checked.

3. Steps to reproduce:
With a world project in construction mouseover the city banner to show the value and then compare it to the value shown in the notification

4. Additional information:
Global Wargames screenshot with the two UI elements merged into the same picture.
![global_wargames](https://cloud.githubusercontent.com/assets/3291695/16175513/ba8daec6-3633-11e6-9fd0-0654f88a2479.jpg)
World's Fair screenshot with the two UI elements merged into the same picture.
![worldfair](https://cloud.githubusercontent.com/assets/3291695/16175517/db3b1b04-3633-11e6-8f11-6602b81d5fd4.jpg)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
The notification is produced when the value is exceeded, not at load, so it can be inconsistent, yep. Its just because of when (in AI turns) the notification is created.

**Comment by GrantSP** [comment]
So the notification is generated when the value is above 100% but the text is using the value from where? I'm finding it hard to understand that explanation.
When the code is notified to create the notification shouldn't the value, >100%, be stored somewhere?
If so shouldn't the text variable draw from that table?

Or, is it a case that the notification should be delayed until the next turn, that way the figure will definitely be correct? Don't know if that is possible.

**Comment by LoneGazebo** [comment]
You can't delay a notification like that so it can't be fixed. Sorry
