### ISSUE TITLE
Some corporation franchise bonuses not working

### ISSUE THREAD

**Issue by Ta1kavarpu** [LoneGazebo/Community-Patch-DLL#1993]
Mod Version (i.e Date - (4/23b)):
6/15-1

Mod List (if using standard CPP set, leave blank):
- Full CPP
- Flag promotions
- Ingame Editor

Issue:
Franchise bonus of Centaurus Extractors, Firaxite Materials, Giorgio Armeier, Trader's Sid and TwoKay Foods for each global franchise of your corporation is not functioning. The value can be seen in the yield breakdown, but is not actually calculated in. Example below.

I have 1 global Firaxite materials franchise in this case. The +3 science is shown, but not calculated into the total. Same thing happens with the respective yields of all the corporations listed above.
![20160619141333_1](https://cloud.githubusercontent.com/assets/19976711/16177385/d7beff22-3633-11e6-911b-621f6746d975.jpg)

**Comment by mwhiter** [comment]
I'll investigate.

**Comment by mwhiter** [comment]
Reproduced and working on a fix now.

**Comment by mwhiter** [comment]
Fixed!

![image](https://cloud.githubusercontent.com/assets/4925402/16179503/dd323b2a-3635-11e6-9ef8-a90414bf59d1.png)

**Comment by LoneGazebo** [comment]
Cool. Fixed on master?

**Comment by mwhiter** [comment]
Yessir!

**Comment by mwhiter** [comment]
Oh, oops. Must've rejected my push. I need to pull first.

**Comment by LoneGazebo** [comment]
I saw the fixes I thought.

**Comment by mwhiter** [comment]
I just pushed it. :)
