### ISSUE TITLE
Corporation trade route bonuses not working properly

### ISSUE THREAD

**Issue by Ta1kavarpu** [LoneGazebo/Community-Patch-DLL#1994]
Mod Version (i.e Date - (4/23b)):
6/15-1

Mod List (if using standard CPP set, leave blank):
- Full CPP
- Flag promotions
- Ingame Editor

Issues:

1. Centaurus Extractors, Civilized Jewelers, Giorgio Armeier, Hexxon Refinery and TwoKay Foods give no extra yields when you send a trade route to a franchise city. Each should give +10% to a certain yield in the origin city but no such multiplier is created.

2. Firaxite Materials and Trader's Sid give their +100% science and +50% gold multipliers to the base yield of the city instead of the trade route yield when you send a trade route to a franchise city.
I have one trade route going to a city with a franchise in the picture below and it's doubling my city's science output while it should be doubling the trade route's science output (doing nothing in this case as the trade route gives 0 science). (Note that the +6 science from corporation is not actually calculated in. I made a separate report about that.)
![20160619151413_1](https://cloud.githubusercontent.com/assets/19976711/16177339/1f9d4a6c-3632-11e6-8ec7-566ff3309d57.jpg)

**Comment by mwhiter** [comment]
Can you post Database.log and Lua.log? I want to verify no database/lua issues before I dive into whether this is a back-end thing.

**Comment by LoneGazebo** [comment]
This was a 'me' bug. I've fixed.
