### ISSUE TITLE
Liberating CS

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#1995]
Bug Report Template

Mod Version (i.e Date - (4/23b)):6/15/1

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

Liberating a CS from a Civ is supposed to give 150 influence.
Liberating a CS from barbarians is supposed to give less.

I observed the following:
An AI conquerd a CS that was conquerd by barbs before. They didn't liberate, but kept it. When I conquered it in turn (yes that CS went through a lot of hands) I didn't get 150 influence, but like 50.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
The original capture sets the liberation value. If barbs take a city, it'll always give less.
