### ISSUE TITLE
CTD Upon Discovering New Civ Lands

### ISSUE THREAD

**Issue by Neon3d6** [LoneGazebo/Community-Patch-DLL#1997]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 6/15 (including recent hot fix)

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk):  CTD

3. Steps to reproduce: whenever a unit first moves next to the borders of another civ's land, the game crashes.

4. Additional information: has happened in multiple games despite reinstalls

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Edaka** [comment]
Would you post your minidump (cvminidump.dmp) please?

**Comment by Neon3d6** [comment]
After a fresh reinstall of the base game, the problem went away.  Thanks!

**Comment by Edaka** [comment]
Good to hear!
