### ISSUE TITLE
Aesthetics City Visual from Event Buildings

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#1998]
1. Get any events that involves free buildings, but that building changes the visual of the city. (Ex. Lighthouse event)
2. Have the free building built (Ex. Lighthouse)
3. Have no visual indicator of the lighthouse in the city on graphical map view, but the lighthouse does technically exist in the Building List.

**Comment by LoneGazebo** [comment]
Free buildings don't and can't affect the UI IIRC.

**Comment by TechpriestEnginseer** [comment]
So, it's not possible to have Events put up a regular building instead of a free building?

**Comment by LoneGazebo** [comment]
I could switch it but they would cost maintenance and so on.

**Comment by TechpriestEnginseer** [comment]
It would be nice to do so since they seem to not remove free buildings. (My case is where "being a good guy" event grants a permanent free building, but if you decide to not become a good guy, another event takes it out.)

**Comment by LoneGazebo** [comment]
Events skip them, yep. I could make all event buildings cost money, I guess.

**Comment by LoneGazebo** [comment]
That's something we need to discuss on forums, though.

**Comment by LoneGazebo** [comment]
I'll change it to real v. free.
