### ISSUE TITLE
GetCityHappinessTooltip missing from source code (causing CityView.lua issues)

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#1999]
Mod Version (i.e Date - (4/23b)):
Fetched the latest master.

1. Mod List (if using standard CPP set, leave blank):
(1) Community Patch
(2) Community Balance Overhaul

2. Type of error (i.e. crash, interface bug, AI quirk): 
Interface bug

3. Steps to reproduce:
a. Fetch latest master
b. Open CityView.lua

4. Additional information:
![image](https://cloud.githubusercontent.com/assets/4925402/16178836/f7bcbb00-3621-11e6-8676-ae14ef637d22.png)

![image](https://cloud.githubusercontent.com/assets/4925402/16178840/0b6349f8-3622-11e6-8ae9-b1c0efadfe5a.png)

![image](https://cloud.githubusercontent.com/assets/4925402/16178843/1eef5232-3622-11e6-8319-11b440135763.png)

**Comment by LoneGazebo** [comment]
Odd.

**Comment by LoneGazebo** [comment]
I'll look at that if you will take point on the corporation issues popping up. I tested a lot of stuff, but apparently I missed some things in my haste.

**Comment by mwhiter** [comment]
yup im looking into things. Good thing corp-dev still exists so I can see any oddities and sort out what I changed. :)

**Comment by LoneGazebo** [comment]
Sounds good. The master is identical to Corp dev except where I adjusted or fixed some things. Some I seem to have overlooked though ( or I assumed they worked looking at the code).

**Comment by LoneGazebo** [comment]
just FYI, GetCityHappinessTooltip is in the infotooltipsinclude.lua, not the DLL.

**Comment by mwhiter** [comment]
Thanks. This worked for me for no apparent reason. Unsure of what happened there.

**Comment by LoneGazebo** [comment]
Odd! Who knows.
