### ISSUE TITLE
CS has quest to liberate CS it captured

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#200]
This one just made me laugh :)

![2015-04-08_00001](https://cloud.githubusercontent.com/assets/11132095/7059845/c685e9fa-de3c-11e4-9d84-bea639bdd8af.jpg)

I'm torn on declaring war on them so I can complete their own quest.

**Comment by LoneGazebo** [comment]
That's amazing. I never considered that variable. I'll fix (is an easy one, finally!)
