### ISSUE TITLE
AI building way too many units and not enough defensive buildings

### ISSUE THREAD

**Issue by Stickerbrush** [LoneGazebo/Community-Patch-DLL#2000]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

1. Mod List (if using standard CPP set, leave blank):
JFD's cultural diversity mod
ethnic units

2. Type of error (i.e. crash, interface bug, AI quirk): 
AI being retarded

3. Steps to reproduce:
Play a game on any difficulty that's equal or higher to inmortal (not sure what's supposed to happen in lower difficulties but i'd like to assume the issue is there too)

4. Additional information:
The AI is just building MASSIVE amounts of units and not building any defensive buildings at all. Granted i have seen carpets this big in the last version of the mod, the difference now is that they are not building defensive buildings at all (unlike before) so it ends up with cities with like 20 pop with a defense of 10 or something. The only city that they sometimes build walls is on their capital, the other cities are always left with nothing.

I can only assume this is a bug and not a feature. Either way if it was a feature it'd be more fun for domination if the enemy had a moderate amount of units (not 32 gorillion weak units) and a respectable city defense (as opposed to the infamous 10 defense city by turn 200)                                        

As always, thanks for reading Gazebo i love ur mod and all ur work!
---------------------------
Supporting information:

I guess i'm not the only one having this issue, http://forums.civfanatics.com/showthread.php?t=569306 u can see that the user notque is reporting the same thing.

**Comment by Tsenna** [comment]
I can confirm this, AI dont build walls, also the AI to often abort the build of wonders/national wonders while there is no reason to do, this ends in a rotation for example manhattan project, which gets build in every city for one turn and repeat.
