### ISSUE TITLE
Caravans dont use roads for traveling

### ISSUE THREAD

**Issue by Tsenna** [LoneGazebo/Community-Patch-DLL#2002]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
**June 15th (1.6.15)**

1. Mod List (if using standard CPP set, leave blank):
**standard**

2. Type of error (i.e. crash, interface bug, AI quirk): 
**I have roads to connect several cities and on road tiles are vilages and towns and the caravans move next to road instad of on the road, that result in lost in econemy and production bonus for villages and towns.**
**The preview for traderoutes shows the right way using the roads, but after starting the traderoute, the caravan moves next to the road, there is no river around there far away, that could be the issue, there are only jungles.**

3. Steps to reproduce:

4. Additional information:
**Files:**
**https://drive.google.com/folderview?id=0Bx_pqkxiwRYLVjlTOFA1bGpVNWc&usp=sharing**

**Note: Its the same savegame as in #2001 **

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
@ilteroi, any ideas?

**Comment by ilteroi** [comment]
drawing a blank here, there is only one pathfinder for the preview and for real

**Comment by LoneGazebo** [comment]
I'll see if I can reproduce.

**Comment by Tsenna** [comment]
Its weird, i tried to reproduce the bug, it worked also to reproduce the bug, but now there is the weird part: i tried to capture the bug in a video, for this reason i have loaded the savegame and started the traderoute and now it uses the roads instead of jungle.

It seems the game dont reconize the construction of new roads until the savegame gets loaded.

**Comment by Tsenna** [comment]
I got it, you can reproduce it by yourself now:
1. Load the savegame TradeRoute from link above

2. Change the pattern of the road by remove one part of the road to another location to change the route.

3. Start the caravan, the preview of the caravan shows the new route with the new pattern of the road, the caravan itself uses the old road.

Here is a Video to show the result: https://www.youtube.com/watch?v=ABV4ulQ4egw

**Comment by ilteroi** [comment]
thank you for the video, i think that's a first :) anyway, i think i know what's happening now.

the (possible) trade connections are updated once per turn and may therefore be slightly outdated if you build or remove a road during the turn. the preview is calculated on-the-fly, so it may be different.

when creating the trade route, it uses the cached path from the beginning of the turn. also note that next turn, the cached path is updated but the caravan path is not, it stays the same until the trade route expires.

i think it would be the easiest solution to simply use the cached path also for the preview.

**Comment by LoneGazebo** [comment]
That makes sense to me @ilteroi

**Comment by Tsenna** [comment]
The issue happens all the time, regardly how long exists the path, so far it is in the same session (between the last load of game), so if the path exists for 100 rounds for example, caravans still dont use this path. 

In addition, if you connect a city state with a road to trade with it, you cant use the path, if it is out of range, until you load the game for path upgrades.
