### ISSUE TITLE
Top Right Panel EUI not working

### ISSUE THREAD

**Issue by BlackliteWrath** [LoneGazebo/Community-Patch-DLL#2006]
Bug Report Template

Mod Version (1.6.15):

1. Mod List (if using standard CPP set, leave blank):
All CPP mods with EUI support
JFD Civs that are compatible
JFD's Rise to Power

2. Type of error (i.e. crash, interface bug, AI quirk): 
Top right panel of the UI is missing, save for the Diplomacy menu button.

3. Steps to reproduce:

4. Additional information:
I followed all instructions to install CPP with EUI support, used the auto-installer, and double-checked that I did.

**Comment by LoneGazebo** [comment]
Incompatibility with JFD I'd imagine. Disable those and try again.

G

**Comment by BlackliteWrath** [comment]
It was JFD's Rise to Power that broke it. I didn't download the EUI Support for it. I feel like an idiot for everyone posting here without double-checking!

Thanks a ton for the help!

**Comment by LoneGazebo** [comment]
No worries.
