### ISSUE TITLE
[Question] Pedia entries for Corporations and Monopolies

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2007]
Have you purposely disabled the links from the "Game Concepts" page to the Corporations and Monopolies or is there an error?

I've noticed a few name changes that may be the cause of some issues, but the entire
`<GameData>
	<Concepts>
		<Row>`
block is missing as far as I can see in CorpText.xml.

Restoring that allows for the menu to expand properly but all the entries are empty.
Not sure what you want to do with that.

**Comment by LoneGazebo** [comment]
This may have been one of @mwhiter 's changes by accident. I did not mess with the civilopedia much.

**Comment by GrantSP** [comment]
Just did a history check and the _Community Balance Patch/Modular Elements/Corporations/Text/en_US/CorpText.xml_ from the "**Merge and Sync of Latest Fefe and Corp Dev (6/6)"** commit is where the code block was removed.

I'll leave it you to decide what you want to do with it.

There is so much duplication of elements across the different modules I'm still trying to piece it together in my head.

**Comment by LoneGazebo** [comment]
I'll fix it. I bet Putmalk didn't mean to delete it.
