### ISSUE TITLE
6.15.1 tech tree no scrolling

### ISSUE THREAD

**Issue by gstew32** [LoneGazebo/Community-Patch-DLL#2009]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 6.15.1

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): While running 6.15.1 with no other mods running other than CP and CBO the tech tree screen does not scroll for me.  This happens on all games in which i play.

Techs are selectable when the previous one is finished, I just can't look at the tree beyond the earliest techs. 

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
This was fixed in the most recent versions. Update and see if it is still happening.
