### ISSUE TITLE
AI stuck in DP loop

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#201]
4/1 version, all mods on How to Install minus Health and Plague.

Kamehameha asked to renew our DP after our previous one expired. He gets angry when I try to accept and won't actually okay they deal. This has happened several times now, he clearly wants another DP but won't actually accept it.

Edit: This is now happening with multiple AIs I previously held DPs with.

**Comment by LoneGazebo** [comment]
I'll take a look – sounds like the renewal logic isn't functioning correctly, which is odd, as it is identical to the code for Research Agreements.
G
