### ISSUE TITLE
Can't Liberate a city state

### ISSUE THREAD

**Issue by gstew32** [LoneGazebo/Community-Patch-DLL#2010]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 6.15.1

1. Mod List (if using standard CPP set, leave blank): (1) CP with (2) CBO non EUI version with Info Addict

2. Type of error (i.e. crash, interface bug, AI quirk): 
While engaged in a war when taking a former city state (Vatican City) I do not have the option to liberate or puppet the city, the city simply joins my empire.  

3. Steps to reproduce:
Replayed the save from right before the action multiple times with the same result.  City is taken by an embarked pikeman or a trireme.

I am able to puppet city of major civs, just not CS.

[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/323399/Lua.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/323398/Database.zip)

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
You've got a mod conflict and/or a bad install  - looks like you are missing CSD, for example.

**Comment by gstew32** [comment]
What is CSD?

The only Mods I am using are CP, CBO and Infoaddict.  I have noticed this issue with several instalations of the betas and I manually install rather than using the auto-installer.

**Comment by LoneGazebo** [comment]
Did you delete the LUA files in the CP?

**Comment by gstew32** [comment]
I did not delete the LUA files in the CP.  When I deleted the old CP file when upgrading I simply installed the entire new CP file as posted on the manual install page.

I am not using EUI do I still need to delete the LUA file in the CP after a new clear install of the betas?

**Comment by LoneGazebo** [comment]
If using CP + CBO, you need to delete the lua folder from the CP, yes. Don't worry about anything else lua-wise if not using EUI.

**Comment by gstew32** [comment]
I will do this for my next game.  I assume deleting now will break the gamesave?

**Comment by LoneGazebo** [comment]
It should not, if you are only deleting LUA. LUA changes are just the UI, and are savegame compatible.
