### ISSUE TITLE
Can't close corporations screen

### ISSUE THREAD

**Issue by maptap** [LoneGazebo/Community-Patch-DLL#2011]
Bug Report Template

Mod Version (i.e Date - (1.6.15 (latest)):

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

When starting a game the corporations screen appears and clicking on close does not make it close. There is no crash, I just cannot get the interface to close and therefore cannot play the game.

3. Steps to reproduce:
Start or load a game.

---------------------------
1. Log files: Database.log and Lua.log needed
[Database.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/323723/Database.txt)
[Lua.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/323719/Lua.txt)

2. Minidump file (located in your Civ5.exe directory)

3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
You are using an incompatible mod, probably one of JFD's that adds a corporation. Remove that and try again.

**Comment by maptap** [comment]
But the only mods I have activated are the ones from the automatic installer. Can other mods affect the game even when not activated?

**Comment by LoneGazebo** [comment]
Yes. Also, make sure you have removed old copies of (1) through (6a).

**Comment by notque** [comment]
I had to delete all my mods and reinstall to correct this issue. Once they redownloaded after deleteing the mod cache, everything was fine.

**Comment by maptap** [comment]
Ok Thank you

**Comment by mwhiter** [comment]
@LoneGazebo that corporation should be reconciled with the new code. I meant to work with JFD and never had time to get around it.

**Comment by LoneGazebo** [comment]
Should be, yes, but it is not currently. I haven't heard from @JFDaly in some time.

**Comment by JFDaly** [comment]
I've just removed the Scented Fragrances Corp. in the latest ExCE update. I've updated CID and ExCE to remove incompatibilities resulting from the change to how Corps. are implemented, so if users are using either of these and still experiencing issues, they should update to v18 of ExCE and v45 of CID.
