### ISSUE TITLE
Civilopedia stuff in need of update

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#2012]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 6/15/1 (latest hotfix)

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk):

- Stonehenge description states "30 faith when completed." Should be 50.

- The improvement yields of gems, aluminium and coal state "+1 production" twice. Only gives +1 production (probably intended).
- The improvement yield of oil states "+3 production" twice. Only gives +3 production (probably intended).
- The improvement yields of incence and pearls states "+1 culture" twice. Only gives +1 culture (probably intended).
- The improvement yield of salt states "+1 food" twice. Only gives +1 food (probably intended).

3. Steps to reproduce:

4. Additional information: Standard speed

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by pandasnail** [comment]
Oil is +3 on Oil Well or +3 on Offshore Platform
Gems, Aluminium and Coal are +1 for the mine itself and +1 specifically on those resources I believe.
Not sure why the yields are separated like that for the others either, but last time I had improved Incense, I could swear I had +3 Culture tiles. No?

**Comment by LoneGazebo** [comment]
I don't know what you are talking about here. Image?

**Comment by pandasnail** [comment]
Can't do an image myself right now, but he (or she) means the stuff on the left, where the actual yields are displayed, believe it even ties into the game data. Might have to be using the EUI version to get the weird half and half version for the yields in question.

**Comment by LoneGazebo** [comment]
That's odd. That data is pre-gen'd. Probably means the data is being duplicated in the SQL, but no idea why. Save/load quirk?

**Comment by F0rst1** [comment]
Yes, I use EUI. It shouldn't be a save/load quirk as this happens both when starting a new game and when loading an old one. It's been like this since the yields of the luxuries were reworked. It seems like the additional +1 production from mining resources comes from the mine itself as pandasnail said and you actually get the +2 production after all. This doesn't, however, apply to the resources that have 2 yields of food or culture displayed in the civilopedia.

Here are some pictures of stuff that seems odd in the civilopedia:
Stonehenge:
![20160621024224_1](https://cloud.githubusercontent.com/assets/18663580/16213837/283ee782-375b-11e6-92db-7b7b48b8cd62.jpg)

Resources:

![20160621024239_1](https://cloud.githubusercontent.com/assets/18663580/16213847/411e62aa-375b-11e6-963b-e5b356323331.jpg)

![20160621024305_1](https://cloud.githubusercontent.com/assets/18663580/16213850/46c16144-375b-11e6-8ac1-f3c89903eb43.jpg)

![20160621024312_1](https://cloud.githubusercontent.com/assets/18663580/16213855/4f5da786-375b-11e6-954e-081f246d6d9f.jpg)

Tech tree:

![20160621024433_1](https://cloud.githubusercontent.com/assets/18663580/16213928/e77f9092-375b-11e6-97f7-b698b2493a85.jpg)

![20160621025801_1](https://cloud.githubusercontent.com/assets/18663580/16213939/0875737a-375c-11e6-8219-29830c7a9bcd.jpg)

Even though it says +1 culture twice in tech tree and civilopedia, improving pearls for example only gives you 1 culture:

![20160621024859_1](https://cloud.githubusercontent.com/assets/18663580/16213959/3787ab1a-375c-11e6-8e3d-9342de1d792c.jpg)

**Comment by pandasnail** [comment]
So in Improvements Changes SQL, there are two of these, one up towards bonus resources and another towards the bottom (of the new values formula area) ('IMPROVEMENT_MINE', 'RESOURCE_SALT', 'YIELD_FOOD', 1). Not sure if you one is supposed to be another yield or what

As to Incense and Pearls, further down that same SQL there is this, and no other resources have it: 
-- Value Changes
UPDATE Improvement_ResourceType_Yields
SET YieldType = 'YIELD_CULTURE'
WHERE ResourceType = 'RESOURCE_INCENSE';

UPDATE Improvement_ResourceType_Yields
SET YieldType = 'YIELD_CULTURE'
WHERE ResourceType = 'RESOURCE_PEARLS';

Perhaps that is overwriting ('IMPROVEMENT_FISHING_BOATS', 'RESOURCE_PEARLS', 'YIELD_PRODUCTION', 1), and ('IMPROVEMENT_PLANTATION', 'RESOURCE_INCENSE', 'YIELD_FAITH', 1),

**Comment by LoneGazebo** [comment]
Might very well be. I'll look - I know I had a heck of a merge snafu a few versions back, may be a legacy of that.

**Comment by LoneGazebo** [comment]
Thanks for looking!

**Comment by pandasnail** [comment]
You're welcome! Props really go to Forsti tho, when I updated the wikia page for Resources, I just assumed this was an EUI quirk and moved on.

**Comment by LoneGazebo** [comment]
I think I've got it pinned down to just being a lua issue, not a database issue.

**Comment by pandasnail** [comment]
Pearls still give 1 culture from a fishing boat, nothing else and the civpedia still says +1 Culture +1 Culture. (only now it has Fishing Boats in parenth after each time.) I tried to test all three at once, but Really advanced setup mod only gave me the pearls for some reason. But Salt and Incense are in the pedia the same way as before as well, plus the improvement.

**Comment by LoneGazebo** [comment]
That's because of the way that fishing boats for samurai are handled. It is benign.

**Comment by pandasnail** [comment]
Hmm. Why would Pearls be the only sea resource it happens to then? And why would that affect Salt and Incense? Screenshot one (hopefully, I maybe could have zoomed in more) shows improved Salt and Incense giving +1 Food and +1 Culture respectively. Then two and three are their pages with the +1 +1 text. And screenshot four is Whales looking normal. I'll let it go now if you want, I just find the samurai explanation even more confusing tbh.

![20160626013638_1](https://cloud.githubusercontent.com/assets/16260521/16360749/cc9864ce-3b3f-11e6-9fc3-01dea8e367be.jpg)
![20160626013724_1](https://cloud.githubusercontent.com/assets/16260521/16360751/e662f5f4-3b3f-11e6-84c2-3421721b6eb6.jpg)
![20160626013730_1](https://cloud.githubusercontent.com/assets/16260521/16360752/ed7650ac-3b3f-11e6-876d-4c6194311b66.jpg)
![20160626013739_1](https://cloud.githubusercontent.com/assets/16260521/16360755/f2ab4db6-3b3f-11e6-8a74-23a00b9f23d5.jpg)

**Comment by pandasnail** [comment]
I lied, one more thing, even tho I know it doesn't even go here. If incense is really supposed to have just +1 culture on improvement and not the +1 culture +1 faith it says at first in the Improvement Changes page, then, considering how often it appears on Desert, I feel like it could use a buff perhaps.

**Comment by LoneGazebo** [comment]
All fixed now. :)
