### ISSUE TITLE
CTD during AI turn 

### ISSUE THREAD

**Issue by Overload** [LoneGazebo/Community-Patch-DLL#2013]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

**1. Mod List (if using standard CPP set, leave blank):**

CCP 1-6a
Faster aircraft animation (v.3)
SloMo Science 100 (v. 7)
Sven's Europe v1.5 (BNW) (v.5)
Wonder Race (v.6)

**2. Type of error (i.e. crash, interface bug, AI quirk):** 

CTD.

**3. Steps to reproduce:**

End the turn. Loading a game several turns back does _not_ solve the issue. Sadly, I've had this bug occur in the past 5 games, always at different stages of the game. I've not found a pattern.

**4. Additional information:**
[Nebuchadnezzar II_0204 AD-1440.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/324187/Nebuchadnezzar.II_0204.AD-1440.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/324170/Database.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/324172/Lua.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/324173/CvMiniDump.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Get rid of the other mods and try it. I can't debug custom setups.

**Comment by Overload** [comment]
Thank for your quick response and dedication to this project. 

Without the other mods (but including the map script Sven's Europe, as it won't load without it) the bug still occurs. As the logs differ from the once in the opening post, I've uploaded everything again. There are a whole bunch of invalid references which I'm sure you can interpret better than I can. Please let me know if there is anything I can to help.

[Database2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/324297/Database2.zip)
[Lua2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/324302/Lua2.zip)
[CvMiniDump2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/324305/CvMiniDump2.zip)

**Comment by LoneGazebo** [comment]
The database is prebuilt in the save, so removing mods from a savegame is a bad idea. I'm going to guess that the mapscript might be to blame - if you try a game without any other mods aside from 1-6, does it still crash?

**Comment by Overload** [comment]
Although I have had it occur ~5 times, none of them happened earlier than at least 1-2 hours into the game. Testing it might take it a while, but I'll see what I can do.

I've successfully completed games with CCP, Faster aircraft animation, and SloMo Science. That would provide evidence for excluding them, and their interaction.

Afaik I've never played a full game including Sven's Europe and/or Wonder Race. The Wonder Race mod seems so small (it only gives notifications, as far as I know) that it seems unlikely to cause frequent bugs.

That would leave Sven's Europe, and/or it's interaction with the other mods.

When I have more time I'll skip-turn through a game with just CCP, and with CCP+Sven's Europe to see if that helps to pinpoint it.

**Comment by Overload** [comment]
I was using an outdated version of CPP, my bad.

As far as I am concerned this can be closed. Should the issue occur again, I'll open a new ticket.
