### ISSUE TITLE
No decision events.

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#2015]
[achievements_debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/325621/achievements_debug.zip)
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6/15

1. Mod List (if using standard CPP set, leave blank):
standrd CPP with EUI
(7) EVents and decisions

2. Type of error (i.e. crash, interface bug, AI quirk): 
Never managed to get a decision. only get the events like market day, extra food from granary, destroyed improvements, volcano...

I have had this issue both with and without EUI and since the start of the Events system in CPP

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Not sure. There's code in the DLL to prevent choice events in MP games- you playing MP games?

**Comment by AnastaseAlex** [comment]
No. And it has been this way since the first release of Events in CPP. I
only noticed because I got involved with Techpriest's (7) Events and
decisions for CPP mod, and saw that there are events with choices. I was
very tirred of always having improvements destroyed every 50 turns or so
across the empire and sought out a way to make more events, and saw that I
have been experiencing only the choiceless events which are really no fun
if they keep happening over and over.

**Comment by LoneGazebo** [comment]
That's the only block, the MP check. Any custom settings or otherwise?

**Comment by AnastaseAlex** [comment]
None that I am aware of. I might once by accident clicked on multiplayer
game ages ago, but I have never played one.
I could try a full reinstall of civ, but my last one was only 3 month ago.

**Comment by AnastaseAlex** [comment]
And I do get the option to choose a great person when I build the leaning tower for example.

**Comment by AnastaseAlex** [comment]
Is there any more information I can provide?

**Comment by LoneGazebo** [comment]
Do you have reward popups turned off? That can cause issues.

**Comment by AnastaseAlex** [comment]
I do not think so, no. I will check to make sure, but normally not.

**Comment by AnastaseAlex** [comment]
Yep I had them turned off.

**Comment by LoneGazebo** [comment]
Turn them back on. I'll see if I can work around the limitation, but those popups are tied to event decision popups.

**Comment by AnastaseAlex** [comment]
yep that fixed it!

**Comment by LoneGazebo** [comment]
Cool.

**Comment by LoneGazebo** [comment]
Glad it worked.
