### ISSUE TITLE
CTD during Byzantium turn.

### ISSUE THREAD

**Issue by Flamenius** [LoneGazebo/Community-Patch-DLL#2016]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

1.3.9b

1. Mod List (if using standard CPP set, leave blank):

  

2. Type of error (i.e. crash, interface bug, AI quirk): 

CTD

3. Steps to reproduce:

End the turn. Loading a game several turns back does not solve the issue.

4. Additional information:

I played on a custom map which i attached.
(couldn't get the zip to directly upload)

https://mega.nz/#F!yhEmhAyQ!y7rhpF3Za0b8XLB1M23smA

--------------------------

Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Flamenius** [comment]
Update: I used IGE to wipe all byzantium units it solved the isssue temporarily, issue occured with another civ about 150 later.(i can of course wipe all units again but i would like to play the game not cheese through it )
So any idea how to fix issue pernamently ?

**Comment by LoneGazebo** [comment]
There's no silver bullet solution for a CTD. You never listed your mods.
