### ISSUE TITLE
Game Hangs at end of (or during) barbarian turn. Have to force close.

### ISSUE THREAD

**Issue by longtomjr** [LoneGazebo/Community-Patch-DLL#2018]
**Mod Version (i.e Date - (4/23b)):** _6/15_

**1. Mod List :** _Standard (with EUI)_

**2. Type of error:** _Game hangs_

**3. Steps to reproduce:** _Do not know how yet. Trying to figure out._

**4. Additional information:**
-Playing as Russia (Catharine)
-Game hangs right after (or during) barbarian turn. Happened twice now.
-At war with a couple of troops on my border.
-Have two cities who would have grown (Borders) when it became my turn
-DX 10 & 11
-Windows 10
[BugReport.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/325995/BugReport.zip)
*Contains lua.log, database.log and the minidump.

**Comment by longtomjr** [comment]
I found a bit more info about this. After I restarted my computer, the game stopped hanging. I played a ton more turns and nothing happened. I guess it was a issue on my end. Sorry for the false alarm. 
Thanks for the amazing mod(pack).
Longtomjr

**Comment by LoneGazebo** [comment]
No worries, glad it is working!
