### ISSUE TITLE
PROMOTION_HEAVY_CHARGE

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#202]
Comments in source code say that defender should not retreat to tiles adjacent to attacker but it does ( and receives extra damage nontheless).
Defender does not retreat to tiles occupied by enemy civilians. 
It would be fun if defender could retreat (embark) to water tiles.

**Comment by LoneGazebo** [comment]
Yeah, the problem with forced embarkation is that it results in odd behavior if the player doesn't, for some reason, have the ability to embark.

**Comment by qqqbbb** [comment]
How can a player have ability to embark? Embarkation is a unit promotion.
