### ISSUE TITLE
Can't press next turn button

### ISSUE THREAD

**Issue by obic123** [LoneGazebo/Community-Patch-DLL#2021]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 6-15 I think

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

When I click next turn nothing happens

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by obic123** [comment]
I should add that even when I reload from an earlier save, when I get to the turn I was on the problem still occurs. It's also happened in other games, and I also did a complete re-install and still have the same problem

**Comment by LoneGazebo** [comment]
You didn't include an required information.

**Comment by ilteroi** [comment]
it's interesting, i have the same problem but i thought it was only on the latest git. something is wrong with the unit focus. it used to jump to units with unfinished moves when pressing next turn but not anymore ...

**Comment by LoneGazebo** [comment]
I haven't touched it I swears it.

**Comment by LoneGazebo** [comment]
@ilteroi so here's something that may be related to the end turn issue - if two workboats are on a sea resource tile, neither of them can issue an order to build a fishing boat - the order just fails. And I know why. In PushMission iData1 and iData2 are being set as values that are, in continuemission, called on as x/y coordinates for a plot. Thing is, they aren't x/y coordinates (at least they're not created as such in the lua->dll transition) so it is failing.

**Comment by LoneGazebo** [comment]
Also, @ilteroi archaeologist seem to be broken in the current github build as well.

**Comment by ilteroi** [comment]
reproduced. will look at it on the weekend

**Comment by ilteroi** [comment]
just tried but the game doesn't break in PushMission when trying to build fishing boats. don't know whats going on. if it's a lua issue i'm clueless anyway. where did you put your breakpoint?

**Comment by LoneGazebo** [comment]
I put my breakpoint at line 504 of unitmission (::continuemission). I'm not sure why, but workboats and archaeologists (but not workers, for some arcane reason) are just looping indefinitely. It might be responsible for the end turn issue, as they're not spending their movement when you assign them to tasks.

**Comment by ilteroi** [comment]
ah. stupid mistake, i had modified CvUnit so the breakpoint wasn't were it appeared to be.

anyway this destination plot business only applies to move missions but right now it's checked for other missions as well - bad idea.

**Comment by LoneGazebo** [comment]
Oh. Well damn. One less problem, one more problem, eh?

**Comment by LoneGazebo** [comment]
I've spent some time debugging on the end turn button thing and I'm utterly stumped. Seems that there aren't any notification blockers causing it. Any ideas I could pursue to help with the process?

**Comment by LoneGazebo** [comment]
@ilteroi while you are looking at units, mind taking a quick look at settlement logic? AI seems shy when it comes to smaller islands and/or offshore settling.

**Comment by ilteroi** [comment]
re: settling ... no changes there lately
re: end turn ... also stumped. checking old versions now for differences

**Comment by ilteroi** [comment]
fixed and pushed

**Comment by LoneGazebo** [comment]
What was it?

**Comment by ilteroi** [comment]
when a unit reached its target, the mission was ended without "awakening" the unit

**Comment by ilteroi** [comment]
just pushed again - found a bad merge error in serialization - maybe that explains the "CTD on first turn" reports

**Comment by LoneGazebo** [comment]
Gotcha. Merging and testing now. Re: settlers, I'm just concerned that 1-4 tile islands are being ignored.

**Comment by LoneGazebo** [comment]
Seeing this: Warning	3	warning C4101: 'uiSentinel' : unreferenced local variable	C:\Users\Jeff\Documents\Visual Studio 2008\Projects\CommunityPatch\CvGameCoreDLL_Expansion2\CvRandom.cpp	175

**Comment by LoneGazebo** [comment]
Benign?

**Comment by ilteroi** [comment]
benign. it's the macro definition, change it to the one below:

#define MOD_SERIALIZE_INIT_READ_NO_SENTINEL(stream) uint uiDllSaveVersion; stream >> uiDllSaveVersion;

**Comment by LoneGazebo** [comment]
I changed it, yep. That's what I figured.
