### ISSUE TITLE
Evangelism not granting science

### ISSUE THREAD

**Issue by mikes61293** [LoneGazebo/Community-Patch-DLL#2022]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6/15-1

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Evangelism isn't granting any science on missionary spread.  The increased conversion power is still working.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Works for me - other city had foreign religion followers? Not your holy city?
