### ISSUE TITLE
CTD - AI Turn

### ISSUE THREAD

**Issue by thearesheep** [LoneGazebo/Community-Patch-DLL#2023]
Bug Report Template

Mod Version (i.e Date - (June 15 - (1.6.15)): Not the hotfix I don't think just the autodownload.

1. Mod List (if using standard CPP set, leave blank):
CP
CB
CSD
C4DF
More Lux
CBO comp files
EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:
Next turn from the save file turn.

4. Additional information:

[Database.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/327329/Database.txt)
[Lua.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/327330/Lua.txt)

[Save Game + Dump File.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/327341/Save.Game.Dump.File.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by thearesheep** [comment]
Why was this closed?

**Comment by Edaka** [comment]
Gazebo looks at all issues posted here, even when he doesn't note it. Closing usually means he has released a new mod version, which might or might not fix the problem.

**Comment by thearesheep** [comment]
Cool.  I was just curious.
