### ISSUE TITLE
Harbor Civilopedia does not match hover/effect

### ISSUE THREAD

**Issue by emperorfool** [LoneGazebo/Community-Patch-DLL#2027]
0. Mod Version (i.e Date - (4/23b)):

1-6-15 (June 15, 2016)

1. Mod List (if using standard CPP set, leave blank):

Full CBP/Vox Populi

2. Type of error (i.e. crash, interface bug, AI quirk): 

Civilopedia/Hover

3. Steps to reproduce:

Build a Harbor
Coast/ocean tile yields do not increase by +1 Gold
Hover over Harbor in city
Listed effects show +1 Food but not +1 Gold, but description says, "+1 Food and Gold"

**Comment by LoneGazebo** [comment]
It is just a text issue. I'll fix later.
