### ISSUE TITLE
Cuirassier cannot move after attacking

### ISSUE THREAD

**Issue by emperorfool** [LoneGazebo/Community-Patch-DLL#2028]
Mod Version (i.e Date - (4/23b)):

June 16th, 2016

1. Mod List (if using standard CPP set, leave blank):

none

2. Type of error (i.e. crash, interface bug, AI quirk): 

gameplay

3. Steps to reproduce:

Train a Cuirassier
Attack an enemy on flat ground
Should be able to move but cannot

**Comment by LoneGazebo** [comment]
See if works in new version.
