### ISSUE TITLE
Tech Tree Error - Cannot scroll right

### ISSUE THREAD

**Issue by Awoobz** [LoneGazebo/Community-Patch-DLL#2029]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
latest version of the auto installer vox populi 6-15-1, installed the patch (1) + balance changes (2)

1. Mod List (if using standard CPP set, leave blank):
Am using (1) and (2) and no other mods. cleared cache, logs,Moduserdata before installing

2. Type of error (i.e. crash, interface bug, AI quirk): 
interface bug, i cant scroll right in the tech tree

3. Steps to reproduce:

4. Additional information:
screenshot: https://imgur.com/koBJus3

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by mwhiter** [comment]
Please post lua.log

You have all dlc installed?

**Comment by Awoobz** [comment]
I do have all dlcs besides the Map Packs
Im not sure if it is the right thing I am posting, but in Logs/Lua is only this:  [608010.546] Initializing Lua 5.1.4

**Comment by Awoobz** [comment]
I also made the same installation on my brother's pc. He never had used any mods before and it is the same issue there

**Comment by Awoobz** [comment]
im really not sure if that is the right one. correct me if wrong 
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/330206/Lua.zip)

**Comment by mwhiter** [comment]
You'll need to enable logging before the lua.log shows anything useful. I can't open it on my phone, either. :(

**Comment by LoneGazebo** [comment]
I know why it is happening, If you are computer savvy, drop the file inside of this archive into your LUA folder in the CBO and overwrite the existing one.


[TechButtonInclude.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/330880/TechButtonInclude.zip)

**Comment by Awoobz** [comment]
Yep.. the new file definately works for me now! Thanks for the fast help guys :)

**Comment by LoneGazebo** [comment]
Yep!
