### ISSUE TITLE
Horse Resource in Coast Tiles

### ISSUE THREAD

**Issue by Ultrageddon** [LoneGazebo/Community-Patch-DLL#203]
I am playing with CP, CBP, CSD, C4D, EUI(CBP), CBP EUI Compatibility Pack & Communitas map script and I've come across a few instances of horse resource appearing in coast tiles. I have been scouring through the forums regarding this issue but to no avail. Any ideas what is causing this?

**Comment by LoneGazebo** [comment]
this is a consequence of map scripts, not the CP/CBP.
G

**Comment by Ultrageddon** [comment]
Thanks. I'm using the Communitas map script that is included in CBP. You wouldn't happen to know a work around, as I never experienced this bug when using the vanilla Communitas by itself?
