### ISSUE TITLE
Beliefs yields on city conversion not working

### ISSUE THREAD

**Issue by Magean0** [LoneGazebo/Community-Patch-DLL#2030]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

6/15 with hotfix

1. Mod List (if using standard CPP set, leave blank):

CPP set
Info Addict
Quick turns
R.E.D Modpack
R.E.D Just ethnic diversity (no rescaling of units)

also using Planet Simulator map script, latest version in here :
http://forums.civfanatics.com/showpost.php?p=14251370&postcount=69
but it doesn't affect the mod list

2. Type of error (i.e. crash, interface bug, AI quirk): 
[bug report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/330287/bug.report.zip)

Council of Elders used to work by granting science on city-conversion, but at some point it stopped working. I am not sure whether it is because I am converting city-states instead of own cities, or because of the era (Renaissance now).

Same issue for Tithes. I'm not receiving gold when converting new cities (but earlier on it worked).

3. Steps to reproduce:

To the West of my empire (Russia) in the save, you will find the city-state of Zanzibar. I have a missionary two tiles away that is ready to spread Eastern Orthodoxy and make it the majority religion in Zanzibar. You will see that Tithes and Council of Elder do not work.

4. Additional information:

None of the cities I had the bug on had been previously converted to my religion, so it really was the first conversion to my religion for each of them.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
See if works in new version.
