### ISSUE TITLE
No luxury resources on map, except Earth

### ISSUE THREAD

**Issue by tdlhicks** [LoneGazebo/Community-Patch-DLL#2031]
Bug Report Template

Mod Version: 6/15

1. Mod List:

2. Type of error: Interface Bug 

3. Steps to reproduce: Start a new game on any map except Earth, no luxury resources will be on the map.

4. Additional information:

**Comment by LoneGazebo** [comment]
Generally a consequence of not having your game up to date (.279) or missing a DLC pack.

**Comment by tdlhicks** [comment]
Not sure what the problem is then. Do you know what causes Earth map to work fine? Like could I use a map mod that has the same qualities Earth does?

**Comment by LoneGazebo** [comment]
The earth mod is a scenario, not a map script. Please enable logging, load a standard map, and then post your database and lua logs.
