### ISSUE TITLE
Map Script "Frontier"

### ISSUE THREAD

**Issue by Tsenna** [LoneGazebo/Community-Patch-DLL#2032]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
**June 15th**

1. Mod List (if using standard CPP set, leave blank):
**standard**

2. Type of error (i.e. crash, interface bug, AI quirk): 

3. Steps to reproduce:

4. Additional information:
**The description for this map says something about mountains, but i cant find any mountains there, also "Large Continent" and "Pangea" inside the mapscript seems to do wierd things. Are hills meant for mountains?**

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
I have nothing to do with mapscripts, sorry.
