### ISSUE TITLE
Enemy citys dont shoot my archers when they stand at 2 range and shoot at it

### ISSUE THREAD

**Issue by Awoobz** [LoneGazebo/Community-Patch-DLL#2033]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6-15-1 Vox Populi

1. Mod List (if using standard CPP set, leave blank):
CBP + CBO

2. Type of error (i.e. crash, interface bug, AI quirk): 
ai not returning fire on my archers

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Awoobz** [comment]
P.s. Archers just shoot normally. It feels like my enemies cities just have 1 range, while mine have 2

**Comment by LoneGazebo** [comment]
They probably haven't researched mathematics yet. That is normal.

**Comment by Awoobz** [comment]
Oops. Now I feel stupid. I didn't read about that anywhere though. Thanks for clarifying. Really enjoying your mod!!

**Comment by LoneGazebo** [comment]
Glad you like it! The Mathematics text has an icon on it that shows that cities increase range to two at that tech.
