### ISSUE TITLE
Can't Raze or Puppet Cities

### ISSUE THREAD

**Issue by themicah06** [LoneGazebo/Community-Patch-DLL#2034]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6/15

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

3. Steps to reproduce:

4. Additional information:
I wasn't sure if this was just a bug, or me doing something wrong but after capturing 5 cities they've all immediately turned to my empire without giving me an option to raze or puppet them. I also liberated a city state, which was also adopted to my territory without letting me give it back to them. Everything is updated and I have all the DLCs, if that helps. 

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Enable logging, and post your lua.log next time it happens.
