### ISSUE TITLE
Feature Request: Num Franchises + Num Offices on World Corporations screen

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#2035]
From https://github.com/LoneGazebo/Community-Patch-DLL/issues/1457#issuecomment-224953503

> 2.) The Corporations tab of the 'World Corporations' menu should also list (and be able to be sorted by) the # of franchises and offices for each corporation. That would really help users see who has the strongest late-game corporation.

**Comment by mwhiter** [comment]
@LoneGazebo how is the state of master at the moment? It's riddled with bugs for me (tech tree broken, crash on new turn).

**Comment by LoneGazebo** [comment]
Master should work fine. Works for me! I'm going to do a new upload soon though.

**Comment by mwhiter** [comment]
okay i'll reset my repository then

**Comment by mwhiter** [comment]
@LoneGazebo any crippling issues? If not then I'll be working on this over my vacation (for a bit, then picking up things peacemeal)

**Comment by LoneGazebo** [comment]
Nope, I've got the corporation stuff back under control, and the CTD issue is resolved. Master should be good to go. :)

**Comment by mwhiter** [comment]
:D

Do you have any feedback on it? Any suggestions for improvements and/or desired functionality?

**Comment by LoneGazebo** [comment]
I think everything is going well thus far. The UI suggestion is really all I can think of at the moment. I'll keep my eyes peeled. If you can think of any more interesting corporation mechanics (i.e. franchise interactions or whatnot), feel free to experiment.

**Comment by mwhiter** [comment]
@LoneGazebo pushed this to master. It's done.

* Added # Offices + # Franchises to World Corporations tab.
* Fixed bug where # Offices and # Franchises would not update when you found a Corporation.
