### ISSUE TITLE
AI handling of city states

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2036]
from an interesting thread in the forums:

- statecraft should make them protect city states, not conquer them
- should concentrate on aggressive neighbors (majors) when selecting attack targets
- liberate then conquer scenario
- check if siege weapons are mandatory for city state attack formation

**Comment by LoneGazebo** [comment]
Siege weps should be mandatory, but I think they share a slot w/ ranged units. I'll look at the diplo AI and adjust it accordingly.
