### ISSUE TITLE
AI defensive performance

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2037]
also from the forums. in general rapid response ops are now working for the first time, so hearing that comment now is a bit surprising, but there is room for improvement

- AI leaves cities exposed: useful unit distribution should be achieved by patrol moves. are they still disabled?
- AI doesn't cancel attacks for defense: we do cancel operations depending on the global situation. but when an army has already arrived at the target, its units are unavailable for recruitment into defensive ops for X turns. and tactical AI is a bit near-sighted, so it simply attacks the closest target ...

**Comment by LoneGazebo** [comment]
Patrol is enabled in release right now b/c of CTD. Will be enabled in new version.

**Comment by LoneGazebo** [comment]
I think we can close this. I've been working on it quite a bit.
