### ISSUE TITLE
AI city valuation

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2038]
forum comments:

- AI settling indefensible cities: seen that
- AI razing good cities, keeping inferior cities (may depend on the order if conquest?)
- AI values cities too high in trade deals. maybe allow only city vs city trades?

**Comment by LoneGazebo** [comment]
I've worked on city trades quite a bit in latest. Will push soon.

**Comment by LoneGazebo** [comment]
I think we should look at city settling a little bit, also AI 'responsiveness' to breaking off attack operations if an owned city is threatened. Probably just need to tweak the War_state types.

**Comment by GrantSP** [comment]
As far as city settling goes I think it would help the community examine this a bit more/better if it was outlined what the current criteria the AI uses are, in order of priority.
Many comments about strategic resources and Natural wonders being left alone.
Does the AI have some idea about where, yet to be revealed, resources are?

**Comment by ilteroi** [comment]
i made it so that cities with wonders will not be razed so easily.

don't see a problem with small islands though.

@GrantSP : the code is in CvCitySiteEvaluator::PlotFoundValue. regarding resources, i just checked, it seems they do cheat a little here.

**Comment by LoneGazebo** [comment]
Agreed. Perhaps just images of bad cities, pooled in a thread, with analysis?

**Comment by ilteroi** [comment]
valuation for small islands was improved. wasn't that the plot was bad but the total area value was relatively low.

the other issues seem under control too, so closing this

**Comment by LoneGazebo** [comment]
Cool thanks
