### ISSUE TITLE
Crash in early turns

### ISSUE THREAD

**Issue by Glidergun** [LoneGazebo/Community-Patch-DLL#2039]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

6-25

1. Mod List (if using standard CPP set, leave blank):

Full VP set, no EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 

Crash to desktop

3. Steps to reproduce:

Begin a new game, end turn a couple of times.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

[crashlog 6-25.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/333419/crashlog.6-25.zip)

**Comment by LoneGazebo** [comment]
@ilteroi, mind taking a look? I can't reproduce the crash, but the minidump file points directly at that same spot in PlotPatrolMoves (line 1791).

**Comment by ilteroi** [comment]
minidump is useless for me, different compiler settings ... need savegame

**Comment by LoneGazebo** [comment]
If you grab the latest version, does the mini dump not load?

**Comment by Glidergun** [comment]
Here's a savegame and its associated minidump. Crash happens for me when I hit End Turn.
[crashlog 6-25-1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/333617/crashlog.6-25-1.zip)

**Comment by ilteroi** [comment]
works for me ... no crash ... don't know if that's good or bad now

**Comment by Arathyum** [comment]
I also have this problem. I was following all the instructions to install it, even with the automatic installer the game crashes in the third turn.
I already deleted all mods and tried again, but still crashing.

**Comment by LoneGazebo** [comment]
@ilteroi, I'm separating out the secondary worker/settler code and making them formal HomelandAI moves. I'm hoping that that might help with the corruption we're (not) seeing.

**Comment by ilteroi** [comment]
sounds sensible - that was ugly anyway

**Comment by LoneGazebo** [comment]
Yeah. My thought, and maybe I'm crazy, is that the currentturn moves weren't being flushed properly and/or it was being flooded with bad requests, and thus it was breaking. I've got no other theories currently.

**Comment by Arathyum** [comment]
I still getting crashes in the third turn :(
I will be waiting then, thank you!

**Comment by LoneGazebo** [comment]
@ilteroi, 6-27 Version does not fix the crash. Still crashing at the same spot. :/

**Comment by ilteroi** [comment]
guess we need an instumented build which logs all modifications to currentTurnUnits. ideally with callstack

**Comment by LoneGazebo** [comment]
@ilteroi perhaps. I'm grasping at straws, but I have a theory:

Since the crash is happening at this point; 

UnitHandle pUnit = m_pPlayer->getUnit(*it);

I wonder if HomelandAI is being accessed by a non-initialized player, thus m_pPlayer is actually the CTD? If so, would an earlier check against non-initialized players fix this?

**Comment by LoneGazebo** [comment]
You would think that, if the iterator was the problem, that it would be crashing in CvPlayer (as you separated out getunit in cvplayer for this specific reason).

**Comment by LoneGazebo** [comment]
@ilteroi small breakthrough-  seems the crash is only happening for windows 7 users. I recall at some point that we had a similar issue in the past.

**Comment by LoneGazebo** [comment]
Looked back, found this line from you back in December regarding the same kind of un-reproduce-able crash.

"iterator invalidated by a remove call on an stl container"

http://forums.civfanatics.com/showpost.php?p=14059438&postcount=157

Same thing? Going to look at homelandAI with this in mind.

**Comment by LoneGazebo** [comment]
Alright, found a few spots where bad ids may have been corrupting the currentTurnUnits. We'll see if this works!

**Comment by Arathyum** [comment]
Oh ok, I will be waiting for your message.

**Comment by LoneGazebo** [comment]
It did not work. :) @ilteroi, same crash, same spot. Any chance that the FindPatrolTarget function is corruption m_currentturnunits?

**Comment by LoneGazebo** [comment]
More news (sorry for spam) - seems that the CTD is happening **after** the first patrol target loop for a civ. So the civ will get a proper patrol for one unit, and then the second loop is where the CTD is happening.

**Comment by LoneGazebo** [comment]
Perhaps we should restore the currentmoveunits push functionality for the patrol?

**Comment by LoneGazebo** [comment]
@ilteroi, all fixed I believe. Uploading fixed DLL shortly.

**Comment by Arathyum** [comment]
Very thanksssss!

**Comment by ilteroi** [comment]
wow - away for one day, now i've got like a million notifications - glad you found it, what was the problem?

**Comment by LoneGazebo** [comment]
Not using the homeland template of current turn units and currentmove units (with a plot/execute function pair) was corrupting the iterator.

**Comment by LoneGazebo** [comment]
Sorry abut spam! I didn't want you to start work on it and duplicate effort.
