### ISSUE TITLE
Happiness either bugged, or not written to handle wide civs

### ISSUE THREAD

**Issue by biship** [LoneGazebo/Community-Patch-DLL#204]
Sorry, do not have technical details, but as you can see from my forum posts, my CIV, with every building built, being advanced, with doubled CityHappiness.sql has over -200 happiness in 4/2 version.

http://forums.civfanatics.com/showpost.php?p=13765944&postcount=51

IMO, 20 cities is not wide.

**Comment by DLimited** [comment]
I have a similar issue - happiness no longer scales well for tall cities (not empires, cities). Even 25pop cities provide around 6 unhappiness per city with tech lead and every building built (ahead in defense strength, for example). Happiness answers currently either give a flat amount (Tradition) or don't scale sharply enough to offset the unhappiness or scale with city number, not population, which translates into lots of stagnated cities with Piety building happiness and constant warpath. Turtling it up is literally impossible right now.
