### ISSUE TITLE
civpedia stuff

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2040]
Just doing this right away, so I can play a lot tomorrow, only 2:

Carthage UA says 150 still, guessing you forgot you even changed it to a number instead of the old 'large sum' verbiage.

And, second, this:
![20160626003959_1](https://cloud.githubusercontent.com/assets/16260521/16360529/27bccaf6-3b37-11e6-9970-1b998d91552e.jpg)

**Comment by LoneGazebo** [comment]
Those helpers are placeholders, yep. Will be editing that later (wanted to get a new versino out).

**Comment by pandasnail** [comment]
Well, delightful choice getting one out for sure, yes! Does say 150 for me tho in the EUI at least

**Comment by mwhiter** [comment]
Interesting - I thought I removed that Corporations section and added my own. Was it readded?

**Comment by LoneGazebo** [comment]
I readded as there was nothing for it. If you did write something, mind reuploading it? I didn't see it.
