### ISSUE TITLE
Can't load any savegame

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2041]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 6-25

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

 Can't load any saves from a freshly started game v. 6-25. 

3. Steps to reproduce:

 Start a new campaign, makes savegames. Exit current game, try to load any saves (be it autosaves, quicksaves or regular saves)

**Comment by LoneGazebo** [comment]
Ah crap, I know why. I missed a merge point when moving to final. Reuploading the CP now.
