### ISSUE TITLE
CTD during AI turn

### ISSUE THREAD

**Issue by dinwkey** [LoneGazebo/Community-Patch-DLL#2042]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6-25

1. Mod List (if using standard CPP set, leave blank):
Yet (not) Another Earth Maps Pack (v 23)
Ynaemp City States for BNW (v 1)

2. Type of error (i.e. crash, interface bug, AI quirk): 
Crash to desktop

3. Steps to reproduce:
it just suddenly ctd during AI turn, also seems loading save would crash too (i.e #2041 happened to me too )

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

I did not turn on logging when it crash so I only have minidump and the save
[civ5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/333437/civ5.zip)

here is what I saw when I debug the minidump from Visual Studio
![image](https://cloud.githubusercontent.com/assets/17967981/16360655/81bacc2a-3b3b-11e6-9791-9be92ac920dd.png)

**Comment by LoneGazebo** [comment]
@ilteroi, crash looks like a bad hit during a settler mission.

G

**Comment by dinwkey** [comment]
do note because I am not not able to load the save to reproduce with debugger attached. I forced pdb generated to match the dll to open the dump so I don't know if stacktrace is really correct

**Comment by LoneGazebo** [comment]
Ah, may be wrong. We'll see.

**Comment by ilteroi** [comment]
yeah that callstack seems more than dubious ;)

**Comment by Tarzan737** [comment]
Have  CTD problem to!

version 6/25-1 non EUI version

other mods

No Mechs V3
Really advanced setup V15

[2016.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/333603/2016.zip)


save is just turn 25 i think and crashes next turn!

**Comment by ilteroi** [comment]
works for me. no crash.

**Comment by Tarzan737** [comment]
I tried to run dxsetup from civ folder and after that it hasent crashed! those who have this problem
should try and confirm! just tried 10 mins of playing but it´s 9 more minutes than before!

i have a new installed civ on this computer so maybye thats why?

**Comment by dinwkey** [comment]
so far I am not getting any crash with 6-25-1 (knock on wood). that said I am running my own compiled version sourced from git(just in case it crash I can use pdb to debug - although I would prefer if you would upload pdb to git too then I don't have to compile my own)
