### ISSUE TITLE
Some corporation franchise bonuses still not functioning

### ISSUE THREAD

**Issue by Ta1kavarpu** [LoneGazebo/Community-Patch-DLL#2044]
Mod Version (i.e Date - (4/23b)):
6/25

Issue:
Franchise bonus of Centaurus Extractors, Firaxite Materials, Giorgio Armeier, Trader's Sid and TwoKay Foods for each global franchise of your corporation is still not functioning. The value can now be seen in the yields of the office, but is again not calculated into the total. Example below.

I have 1 global franchise here.
Here you can see +4 gold in the Trader's Sid office.
![20160626183133_1](https://cloud.githubusercontent.com/assets/19976711/16363260/30640646-3bce-11e6-9fd6-ece256661f44.jpg)

But only the +5 gold from Palace is calculated into city's output.
![20160626183136_1](https://cloud.githubusercontent.com/assets/19976711/16363257/1fc47050-3bce-11e6-8ac5-0eb98263e180.jpg)

EDIT: if the office isn't free, this issue doesn't exist. So it's only for the headquarter city's office. Also had some additional supposed issues listed below as comments, but they ended up being just my own misunderstandings.

**Comment by Ta1kavarpu** [comment]
Seems like office doesn't actually cost any maintenance either.
![20160626185256_1](https://cloud.githubusercontent.com/assets/19976711/16363307/36502dae-3bcf-11e6-848f-03632306db21.jpg)

**Comment by Ta1kavarpu** [comment]
The supposed +2 gold to trade routes given by Trader's Sid's office doesn't work also.
![20160626185256_1](https://cloud.githubusercontent.com/assets/19976711/16363318/66830910-3bcf-11e6-97e8-563d331bdc4c.jpg)

**Comment by Ta1kavarpu** [comment]
Apparently if the office isn't free, the franchise bonus functions.
![20160626190141_1](https://cloud.githubusercontent.com/assets/19976711/16363371/9de08af8-3bd0-11e6-9ae1-478a3f954a2d.jpg)

**Comment by mwhiter** [comment]
I'll look into it. Thanks!

**Comment by LoneGazebo** [comment]
So issue is just free state ? That should be an easier fix.

**Comment by LoneGazebo** [comment]
@mwhiter, I created an update function (as the one you had set up was very cpu intensive), I'll see if I can fix.

**Comment by mwhiter** [comment]
@LoneGazebo FYI because I've been having problems with master I haven't been able to apply a fix that I wanted to.

There is an issue I noticed where when you found a corporation, the office update wasn't called, so on Turn 0 of a corporation founded it says you have 0 offices. There are probably other bugs but my build is unstable so I need to reset before I can fix them.

**Comment by LoneGazebo** [comment]
I'll fix that on the master. The function should have updated, but I think it wasn't grabbing the free building as a real building.

**Comment by LoneGazebo** [comment]
Yep, I think that's the problem.
