### ISSUE TITLE
The magnitude of Trader's Sid's trade route bonus

### ISSUE THREAD

**Issue by Ta1kavarpu** [LoneGazebo/Community-Patch-DLL#2045]
Mod Version (i.e Date - (4/23b)):
6/25

Issue:
It says everywhere that the Trader's Sid's trade route bonus is +50% gold to a trade route to a franchise city, but it actually gives +100%.

![20160626183049_1](https://cloud.githubusercontent.com/assets/19976711/16363394/36f03284-3bd1-11e6-8228-c009033da212.jpg)
![20160626183035_1](https://cloud.githubusercontent.com/assets/19976711/16363395/450b4106-3bd1-11e6-94d4-270fbccfa800.jpg)

**Comment by LoneGazebo** [comment]
@mwhiter, this is the offending DLL section:

if (bAsOriginPlayer)
	{
		bool bOfficesAsFranchises = GET_PLAYER(pOriginCity->getOwner()).GetCorporations()->IsCorporationOfficesAsFranchises();
		//If nationalized, we must be targetting our own city
		if (!bOfficesAsFranchises || pOriginCity->getOwner() == pDestCity->getOwner())
		{
			// Target only trade routes to cities with a Franchise - IsHasFranchise() also counts Nationalized Offices as franchises!
			if (pOriginCity->IsHasOffice() && pDestCity->IsHasFranchise(eCorporation))
			{
				iModifier += pkCorporationInfo->GetTradeRouteMod((int)eYield);
			}
		}

		// Do we have a building that grants a bonus toward cities with Franchises?
		if (pDestCity->IsHasFranchise(eCorporation) && pOriginCity->IsHasOffice() && pkCorporationInfo->GetTradeRouteMod((int)eYield) > 0)
		{
			iModifier += pkCorporationInfo->GetTradeRouteMod((int)eYield);
		}
	}
