### ISSUE TITLE
YNAEMP v24 Unknown # of Players 6-25-1 Release

### ISSUE THREAD

**Issue by ForAPrice** [LoneGazebo/Community-Patch-DLL#2047]
Bug Report Template

Mod Version 6-25-1:

1. Mod List (if using standard CPP set, leave blank):

Vox Populi suite + EUI
JFD's Teddy Roosevelt
YNAEMP v24

2. Type of error (i.e. crash, interface bug, AI quirk): 

Interface Bug

3. Steps to reproduce:

4. Additional information:

It was working fine in the release build previous to this one. None of the buttons fix the problem. I think it has something to do with the load order of YNAEMP and More Lux.

---------------------------
Supporting information:

![untitled](https://cloud.githubusercontent.com/assets/20154684/16363777/e3af7534-3b9a-11e6-97d6-956011b1933d.png)

**Comment by LoneGazebo** [comment]
Not sure. I'd try reinstalling all of your kids.

**Comment by LoneGazebo** [comment]
Mods. Ha.

**Comment by ForAPrice** [comment]
Reinstalled civ, the kids, and re-added tsl support for Teddy on greatest earth. Got past that screen, but now getting CTD 2 turns in repeatedly.
