### ISSUE TITLE
overseas colonization

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2048]
![image](https://cloud.githubusercontent.com/assets/1358966/16363858/aaae01f0-3bd7-11e6-8062-a04978c99fe6.png)

france has two operations waiting for a boat - but they aren't building one - this has been going on for at least 30 turns.

so either we need to reconsider the building logic or make the ASSAULT_SEA slot optional.

[CityStrategyAIProductionLog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/333728/CityStrategyAIProductionLog.zip)

**Comment by ilteroi** [comment]
so i just turned into napoleon for a minute and it turns out that they don't have sailing yet.

and won't ever have it one has to assumes because they have ruined their economy:

![image](https://cloud.githubusercontent.com/assets/1358966/16364029/856298d8-3bdd-11e6-9a01-2d143a326d90.png)

can't build caravans either. don't know if that's an outlier but anyway making the boat optional might be the better option.

**Comment by LoneGazebo** [comment]
I've thought about giving the AI a handicap for this. Minimal science per turn instead of suffering at zero. Thoughts?

**Comment by ilteroi** [comment]
yeah that would be acceptable i guess. 

observation though: paris had built all possible buildings. that's not a good idea when you're in the red already. so either sell and rebuild. or build only maintenance free things.

allowing the gold process earlier could also help.

**Comment by LoneGazebo** [comment]
I think that kind of collapse is rare enough that an AI handicap is okay.

**Comment by LoneGazebo** [comment]
Did you see the posts regarding unit pathing and DOW pop ups on trying to stack with enemy civilian units? Probably an unintended change.

**Comment by ilteroi** [comment]
testing right now ...
