### ISSUE TITLE
CTD in first turn

### ISSUE THREAD

**Issue by Tsenna** [LoneGazebo/Community-Patch-DLL#2049]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
06-25

1. Mod List (if using standard CPP set, leave blank):
standard

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:

4. Additional information:

[save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/333735/save.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/333733/CvMiniDump.zip)

**Comment by ilteroi** [comment]
works for me. no crash. assuming it's meant to happen on turn end.

**Comment by LoneGazebo** [comment]
Ilteroi, perhaps we should try turning off all logging and whatnot? There's got to be something on our machines causing it not to fail.

**Comment by Tarzan737** [comment]
try run dxsetup in your steam/civ folder it may work! my games hasent crashed (yet)

**Comment by ilteroi** [comment]
may also be due to optimizations in the release build. although we're single threaded, it can e.g. still happen that a pointer is uninitialized (in debug it would be zero, but not in release, so a null check wouldn't trigger).

**Comment by LoneGazebo** [comment]
I just can't figure out why that particular pointer would be bad, when it is identical code-wise to the other.

**Comment by LoneGazebo** [comment]
Would adding something as simple as if(m_CurrentTurnUnits.size() <= 0) return; fix it?

**Comment by ilteroi** [comment]
i haven't seen that patrol crash yet - anyway the size is unsigned, so <0 won't work i guess - if m_CurrentTurnUnits is corrupted, better try to find the point where it gets corrupted

**Comment by Tsenna** [comment]
It happens while at city states turn, if this info helps.
