### ISSUE TITLE
CTD turn after founding city

### ISSUE THREAD

**Issue by morario84** [LoneGazebo/Community-Patch-DLL#2050]
Crashes to desktop during AI's turn every time I start a game. It's always the turn after I found my 1st settlement..

Bug Report Template

Mod Version (i.e Date - (4/23b)):
1.6.25 installed via Vox Populi

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
crash to desktop

3. Steps to reproduce:
happens every time since I started using CBP

4. Additional information:

win7 64 bit

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

[6-26-log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/333903/6-26-log.txt)
[6-26-xml.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/333904/6-26-xml.txt)

**Comment by morario84** [comment]
I'm trying to upload ZIP files (adding to zip via 7zip) but it keeps saying that file type is not supported...

**Comment by LoneGazebo** [comment]
You can drag and drop zip files into the text box. I need your minidump file.

**Comment by morario84** [comment]
When I drag and drop zips into the text box, I get an error with red text 'unfortunately, we don't support that file type', even though its a zip file..

**Comment by LoneGazebo** [comment]
hmm, zips work for me. You can email it you thelonegazebo@gmail.com

**Comment by morario84** [comment]
Just so it's logged, I emailed the files to Gazebo
