### ISSUE TITLE
Game Crashing + City-State Declare Bug

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#2051]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

June 25th

1. Mod List (if using standard CPP set, leave blank):

Standard CPP set, but no EUI.

2. Type of error (i.e. crash, interface bug, AI quirk): 

Two issues.

#1 - Crashing.

#2 - Strange war declaration with a City-State.

3. Steps to reproduce:

Saved game file included.  Simply play what's left of the turn and end it - for me, it always crashes.

4. Additional information:

This crash isn't unusual - it's actually been happening to me in every game at some point, the point is just not consistent; but it always occurs during an AI's turn.  Once it happens, re-loading at any point and playing up to that point seems to result in the same matter (I'll include an Autosave as well).

With regard to #2 - I had an issue where Milan (my closest City-State) was solidly my ally for a long time.  On one turn, one of my Missionaries refused to move onto one of my allies' units, and a pop-up occurred asking me to declare war, indicating that the infiltrating unit was my Cargo Ship. (???!?)  I said "no."  The pop-up box simply re-appeared, and I kept saying no - it kept doing it until I had to say yes, war was declared, and then I immediately made peace - with a City-State that hated me, of course.

ALSO I need to apologize - the site isn't accepting my Zip files for some reason, so the File Uploader links are right here:

http://www.filedropper.com/james_2
http://www.filedropper.com/autosave0140ad-0600

THANK YOU!!!  :)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Did you include your minidump file? If not, that's what I need.

**Comment by saamohod** [comment]
I confirm the persistent "Declare War" window issue. It stated for no obvious reason, and now seems to never stop. During my turn whenever I press Enter to progress through turn I keep getting a stuck message window.
 Savegame attached. To replicate the bug load the savegame and press Enter.

![20160627131131_1](https://cloud.githubusercontent.com/assets/16341598/16376554/7a30adce-3c69-11e6-8309-04f0e334fda2.jpg)
[DoW.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/334600/DoW.zip)

**Comment by Gidoza** [comment]
What is a minidump file?  :o

**Comment by LoneGazebo** [comment]
Minidump file (located in your Civ5.exe directory)

**Comment by Gidoza** [comment]
I don't understand where that is.  Is there a guide somewhere?

**Comment by LoneGazebo** [comment]
Civ.exe directory is where civ is installed on your PC. usually c:/programfiles/steam/steamapps/common/civ5/

**Comment by Gidoza** [comment]
Hmmmmm...I don't see a minidump file there anywhere.

**Comment by Gidoza** [comment]
Oh I see, it's called CivMinidump, not just minidump.

Here's the link.  :)

http://www.filedropper.com/cvminidump_1
