### ISSUE TITLE
[Suggestion] No advanced weapon for scouts

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2052]
I might be by far not the only person who gets annoyed when my scout runs into Ancient Ruins and gets "promoted" to archer who can't get any more experience from exploration and scout-type promotions. Is it a valid suggestion that a scout shouldn't get promoted in a way that it changes their role? Can it be implemented?

**Comment by LoneGazebo** [comment]
Not really- not without them becoming OP explorers.
