### ISSUE TITLE
CTD in early AI turns

### ISSUE THREAD

**Issue by Grellou** [LoneGazebo/Community-Patch-DLL#2053]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
1.6.25 installed via Vox Populi

1. Mod List (if using standard CPP set, leave blank):
Standard

2. Type of error (i.e. crash, interface bug, AI quirk): 
Game crashes to desktop without any message during AI turn

3. Steps to reproduce:
Usually happens in between turns 5-10 during AI turn

4. Additional information:
Win7 x64
Tried to save and load the game before turn ~5 but it didn't helped
Vanilla works fine without any crashes

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

For some reason I'm not allowed to upload RAR/ZIP files here
This is Minidump file that I've uploaded: http://www.filedropper.com/cvminidump

**Comment by LoneGazebo** [comment]
Please upload a minidump file.

**Comment by Grellou** [comment]
It's not letting me to upload RAR/ZIP files here. I've uploaded it to filedropper.
http://www.filedropper.com/cvminidump
