### ISSUE TITLE
Early crashes

### ISSUE THREAD

**Issue by Glizinte** [LoneGazebo/Community-Patch-DLL#2055]
Bug Report Template

Mod Version (i.e Date - (4/23b)):6-25-1

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Tried 2 games. 1 CTD @ 2nd turn; 2 infinite loop @ 2nd turn

3. Steps to reproduce: Started game as Morocco.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Edaka** [comment]
Upload your minidump and a savegame, please.
