### ISSUE TITLE
CTD turn 2

### ISSUE THREAD

**Issue by Skidizzle** [LoneGazebo/Community-Patch-DLL#2056]
Mod Version: 6-25-1

[6-25-1 CTD turn 2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/335475/6-25-1.CTD.turn.2.zip)

1. Mod List:
(1) Community Patch (v 86)
(2) Community Balance Overhaul (v 13)
(3) City-State Diplomacy Mod (CSD) for Brave New World (v 27)
(4) C4DF - CBP (v 11)
(5) More Luxuries (v 155)
(6a) Community Balance Overhaul - Compatibility Files (EUI) (v 1)
(BNW) Leugi's Barbarian Inmersion Enhancements (v 1.5)
Capture Great People (v 2)
Civ Names by Policies (v 8)
Global - Local Generals (v 2)
Global - City State Airbases (v 4)
Global - National Wonders Exclude Razing (v 1)
Global - Units Awake In Danger (v 2)
Goody Huts - Tech Refund (v 7)
InfoAddict (v 22)
JFD's Cities in Development - EUI Compatibility Files (v 44)
JFD's Cities in Development (v 45)
JFD's Cultural Diversity (Core) (v 9)
JFD's Exploration Continued Expanded (v 18)
JFD's Rise to Power - EUI Compatibility Files (v 24)
JFD's Rise to Power (v 25)
Maps - Improved CS Luxuries (v 6)
Maps - Random Goody Huts (v 6)
More Great Works (v 3)
Music Changer (v 2)
Quest - Circumnavigate (v 1)
Quest - National Wonder (v 1)
Quest - Tourism Contest (v 1)
Quick Turns (v 10)
Really Advanced Setup (v 15)
Sukritact's Events and Decisions (v 3)
Thalns FlagPromotions-CPP Vers
Unit Path Viewer (v 10)
Units - Subs Immune Under Ice (v 2)

2. Type of error: 
CTD on turn 2, appears to be player 3 AI turn

3. Steps to reproduce:
finished turn 2, hit next turn

4. Additional information:
Win7 x64
Steam Civ5 dx11
Full screen mode
Building info tooltip lua error is JFD's RtP problem

**Comment by Edaka** [comment]
Just wondering, do you play in windowed mode?

**Comment by Skidizzle** [comment]
I play full screen

**Comment by ilteroi** [comment]
sorry, but with a mod list like that it makes no sense to try to replicate this. please try with VP only.
