### ISSUE TITLE
[Pedia] Corporation helper text is not being correctly added to the database

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2058]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
**June 25th**

1. Mod List (if using standard CPP set, leave blank):
+FlagPromotions
+InfoAddict

2. Type of error (i.e. crash, interface bug, AI quirk): 

3. Steps to reproduce:
The Game Concepts page that lists the seven types of corporations shows the TXT_KEY_ tags instead of the actual text.
The files do define the specific entries but I'm wondering if they don't show because the tags are defined in the same file as the page calls them but they are defined AFTER they are called?

_Community-Patch-DLL\Corporations\Corporations\Text\en_US\CorpText.xml_ calls them at line 180 but each corporation helper text is not defined until line 425 at the earliest.

I can't remember if that makes a difference but I'm thinking it should. 

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
This is known, and was already resolved. (Placeholders for other stuff).
