### ISSUE TITLE
[BUG][E&D] Attila's decision is not working.

### ISSUE THREAD

**Issue by wileyhk2001** [LoneGazebo/Community-Patch-DLL#206]
After a few games, I feel that E&D is so bugged..

One of Attila's decision: Demand for ransom against a warring civ.
After the peace treaty is "signed". I could never declare war against him again, not even after 15 turns when the peace treaty should have expired. In the Trade screen the "declare war" button disappeared.

**Comment by LoneGazebo** [comment]
Yeah, I can't fix this. This is an E&D issue.
