### ISSUE TITLE
6-27 CTD

### ISSUE THREAD

**Issue by ForAPrice** [LoneGazebo/Community-Patch-DLL#2060]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6-27

1. Mod List (if using standard CPP set, leave blank):

VP+EUI
IGE
JFD Teddy
YNAEMP v24

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:
Start game, crash on turn 2

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

[Dump+Lua+Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/336188/Dump.Lua.Database.zip)

**Comment by LoneGazebo** [comment]
Try with just the VP and report back.

**Comment by ForAPrice** [comment]
Still happens, as for "DX11 or DX9? Fullscreen/windowed? EUI/no EUI? ATI/Nvidia? Windows 10?"

DX11, Windowed, EUI, Nvidia, Win7 64bit

**Comment by LoneGazebo** [comment]
Blegh. I can't replicate, which makes this less than ideal to figure out. I'll keep slamming my head against it, though.
