### ISSUE TITLE
6-27 CTD

### ISSUE THREAD

**Issue by Txurce** [LoneGazebo/Community-Patch-DLL#2061]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6/27

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
crash

3. Steps to reproduce:
1-3 turns

4. Additional information:
game and mod reinstall + verify integrity
please note: crash files have incorrect dates
[civilizationv_dx11_395131_crash_2013_11_4T20_25_18C0.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/336210/civilizationv_dx11_395131_crash_2013_11_4T20_25_18C0.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Txurce** [comment]
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/337582/CvMiniDump.zip)

**Comment by Txurce** [comment]
As requested, here is the last game's minidump file.

**Comment by LoneGazebo** [comment]
Mind posting homelandAI file?

**Comment by Txurce** [comment]
Where is it?

**Comment by LoneGazebo** [comment]
logs folder.

**Comment by Txurce** [comment]
[PlayerHomelandAILog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/337607/PlayerHomelandAILog.zip)

**Comment by Txurce** [comment]
Thanks. Should be there now.
