### ISSUE TITLE
Community Patch CTD Celts attack Mongolians

### ISSUE THREAD

**Issue by tsmith7163** [LoneGazebo/Community-Patch-DLL#2063]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
3/2106 -version just loaded the begginng of June

1. Mod List (if using standard CPP set, leave blank):

 Community Patch Project ( 3-9.exe)
Info Addict v22
Quick Turns ( v10)

2. Type of error (i.e. crash, interface bug, AI quirk): 
Crashes to desktop the turn after the Celts declare war on the mongolians-  it crashes the turn after when during the Celts icon comes on the screen.  

3. Steps to reproduce: not sure what this means-  everytime the turn after the AI ( celts declare war on the Mongilans) the games CTD during their move-

4. Additional information:I had the same crash turns before so I loaded an older saved version per Gazebo advice I read online- and it worked for as the Celts did not declare war on the monglians so I was able to play another 20-30 turns which was awsome but then once the Celts declare war on the monglians then next turn when it is there turn to act ( ie their icon is on the screen) it CTD.  I updated my drivers, I got windows 10,  I delted the cache, logs and ModUserdata per instruction manuel and then reloaded the all the mods( a number of times),  I tried playing with all graphics to low or minimum.  My PC specs are CPU Intel Core i5-3.00 GZ- 8 GB Ram the the Nividia GeForce GTX 550 Ti graphics card.  I am very new to MODs and I have only played a few but the community patch is so unbelievably freaking awesome- it is so much more fun and better than vanilla CIV 5 its unbeliveable  - it is everything I wanted Civ to be- the EUI is perfect too, infor addicts is awsome, quick turns is the best everything I could think up is included-- I'm really desperate to finish my game- I got tons of hours invested.  I'm very inexperienced when it comes to this stuff so I am not sure if I attached what you needed and I don't really understand much of your  langague or how a lot of this stuff is possible ( even getting on Github was challenging)--  but I can follow directions.  Please help- or let me know if you need anything-- the game was so freaking great. And I would just load an earlier game but I think it is inevitable that the Celts will declare war on the monglians.

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/336399/CvMiniDump.zip)
[stopwatch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/336400/stopwatch.zip)
[4Augustus Caesar_0850 AD-1831.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/336404/4Augustus.Caesar_0850.AD-1831.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
There's no easy solution - you could install in-game editor and simply remove Celtic units so that they can't attack so that you can finish your game. Once a game has CTD'd (which can happen for lots of reasons), it is hard to recover.

**Comment by tsmith7163** [comment]
thank you-

**Comment by tsmith7163** [comment]
This worked perfectly --I deleted a celt city that was on the edge of the map that must have been causing a pile up.   Thank you so very much-- this mod is unbelievably fun and awesome- I did have one thing more but not a big issue- but the picture of my capital no longer shows but everything else runs find so I am ok-- I just like to see my capital grow with all the wonders around it--   I tried reinstalling no good-- I assume someone must have had the same issue but I could find it on-line so I just wondered if you had some quick hit wizardry that would bring the picture back-- no bigger if not.
But thank you so very much-  this is fantastic game( I can not stress that enough)  now the changes that were made are so very, very cool-- I just put down my first mine field-- which is so freaking awesome and started my own corporation-  
The AI is some much, much better,  but I still don't understand why they don't bring all their troops or at least a significant portion once I am attacking their cities or even when they declare war-- they clearly have the military might ( according to demographics) but they don't use it--  seems unusual-  no need to answer this, the AI is gazillion times better and more challenging-  but I have always wondered that-- I'm sure is just programming but it would seem that it you were about to lose a city you would throw everyone you could at stopping that-- again no need to answer this --  but awesome game- thank you.
