### ISSUE TITLE
Cannot liberate city, only Annex or Puppet.

### ISSUE THREAD

**Issue by StevenV205** [LoneGazebo/Community-Patch-DLL#2064]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

**3/19**

1. Mod List (if using standard CPP set, leave blank):

**Community Patch:
Community Balance Overhaul
JFD's Exe v14
JFD's Meji Japan CIV
Quick Turns v10
Info Addict**

2. Type of error (i.e. crash, interface bug, AI quirk): 

**Cannot liberate a Russian city what was previously captured by Spain. Thus I had to annex. In addition, it I cannot give back the city to Cathrine, she think I am joking and does not accept my gift**

3. Steps to reproduce:

**Capture the city Rostov**

4. Additional information:

My first game with CBP, but the most interesting so far :) 
Sorry if this has been resolved already, but did not find any relevant info on GIthub. Thanks.
---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**will upload later today**

**Comment by LoneGazebo** [comment]
If logging is enabled, please post your Lua log from that game.

**Comment by StevenV205** [comment]
[reports.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/338504/reports.zip)
Hope this helps.

**Comment by LoneGazebo** [comment]
There are database errors in your database log, however the lua log is empty. I'm going to guess a mod conflict and/or you didn't follow one of JFD's mod install instructions for compatibility.

**Comment by StevenV205** [comment]
Thanks, I would assume a conflict, since incompatibility was also the reason in the Battleship/Oil issue.

**Comment by Edaka** [comment]
Could also be isolated to using just the CP and CBO, though. Looks very similar to #210 . Anyway, @StevenV205: could you try to replicate the issue with just those two mentioned mods and post your logs?

**Comment by StevenV205** [comment]
I am afraid I couldn't since i playing with a Mod CIV [https://steamcommunity.com/sharedfiles/filedetails/?id=427276112] so I need to use that also.
BTW, how can I turn on the logging. My lua log was empty.
Thanks.

**Comment by Edaka** [comment]
Here's a tutorial by Whoward: http://forums.civfanatics.com/showthread.php?t=487482
Perhaps next time you start a new game, then.
