### ISSUE TITLE
AI (very probably) can build Battleship without Oil

### ISSUE THREAD

**Issue by StevenV205** [LoneGazebo/Community-Patch-DLL#2065]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

**3/19**

1. Mod List (if using standard CPP set, leave blank):

**Community Patch:
Community Balance Overhaul
JFD's Exe v14
JFD's Meji Japan CIV
Quick Turns v10
Info Addict**

2. Type of error (i.e. crash, interface bug, AI quirk): 

**Spain can build Battleship without Oil.
They dont have a single resource
Neither their CS allies .
In addition, they don't trade it form any other civs (based on Info Addict)**

3. Steps to reproduce:

**Check the city of Madrid with the spy on it.**

4. Additional information:

**Sorry if this has been resolved already, but did not find any relevant info on GIthub. Thanks.**

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
What about corporations?

**Comment by MoiMagnus** [comment]
I think battleships use iron, not oil. Oil is only used for air units and armored units.

**Comment by LoneGazebo** [comment]
@MoiMagnus Good call, I forgot about that! :)

**Comment by StevenV205** [comment]
Indeed, thanks for the fast response and sorry about the mixup. 
_The reason I thought they use Oil is that I use Jaoan (Meji) CIV where my Mikasa Battleship use Oil insted of Iron. [http://civilization-v-customisation.wikia.com/wiki/Japan_(Meiji)](url)_
_Looks like it is not fully compatible with the mod._

**Comment by LoneGazebo** [comment]
No worries!
