### ISSUE TITLE
AI difficulty bonus (6/27)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#2066]
Did you mix-up DifficultyBonus with AIFreeXPPercent?
Please check the **Immortal** value.

cf.
(2) Community Balance Overhaul\Balance Changes\Difficulty\DifficultyMod.xml

Immortal (Line: 411-412)
```
	<DifficultyBonus>100</DifficultyBonus>
	<AIFreeXPPercent>60</AIFreeXPPercent>
```

Deity (Line: 471-472)
```
	<AIFreeXPPercent>100</AIFreeXPPercent>
	<DifficultyBonus>80</DifficultyBonus>
```

**Comment by LoneGazebo** [comment]
Oh I did. Oops. I'll fix.

**Comment by 13ananas** [comment]
Well this might explain why I started having a ton of trouble on my usual difficulty. Hah.

**Comment by LoneGazebo** [comment]
hehe yeah, it might! :)

**Comment by LoneGazebo** [comment]
Should be: <DifficultyBonus>60</DifficultyBonus>
			<AIFreeXPPercent>75</AIFreeXPPercent>
