### ISSUE TITLE
Hunnic bugs and suggestions

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#2067]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
6/25/1

1. Mod List (if using standard CPP set, leave blank):
Standard CPP and Really Advanced Setup. All this happens without Really Advanced Setup too though.

2. Type of error (i.e. crash, interface bug, AI quirk): 

**Bugs:**

When the Huns conquer a barbarian encampment with a melee horse unit, they sometimes get 2 new units. It seems that both the ability to get units from encampments and the ability to capture units with melee horse units activate. I think they should only get one copy of the barbarian in the encampment i.e. the ability to capture units with melee horse units shouldn't activate if the opponent is standing in an encampment.

The horsemen captured from barbarians don't consume horses and their CS is 14 instead of 15. I already noted this in [#1841](https://github.com/LoneGazebo/Community-Patch-DLL/issues/1841) but I think my report wasn't explicit enough. The Huns can have a big army of horsemen without having access to horses due to this and this is what makes it a bug. Also, when you build Terracotta Army you can get 2 different horsemen, one that consumes horses and one that doesn't but has 1 CS less.

**Suggestions:**

With the Huns, you can get quite a few hand-axes in your army. The problem with the unit is that it upgrades to crossbowman. This makes it pretty much useless from early classical to early medieval era. Would it be possible to change the upgrade unit? I'd personally like to see them upgraded to skirmishers (horse archers), as it would create a nice synergy with the Huns and the are, in a way, similar units, as their range is 1. If that isn't possible, composite bowman would also make a better upgrade unit than crossbowman from my point of view.

3. Steps to reproduce:

Choose the Huns, get horse units, go wild

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

![20160628155825_1](https://cloud.githubusercontent.com/assets/18663580/16416142/80f47e20-3d49-11e6-8fc8-4683c3107f2b.jpg)
![20160628155841_1](https://cloud.githubusercontent.com/assets/18663580/16416146/85ef09a4-3d49-11e6-9b50-795e1c42880b.jpg)

**Comment by LoneGazebo** [comment]
I don't see the 2 units from a camp thing as being a bug - that's the UA (1) and the UA promotion (2) at work. Also barbarian horsemen do not cost horse - that is intentional (also barbarian horses are slightly stronger than normal horses). They're a different unit.

Re: Hand-axe, that needs to be discussed on the forums, not here.

**Comment by F0rst1** [comment]
If barbarian horsemen are a different unit, could they get a different name to help identify them? A simple solution would be naming them "barbarian horsemen". I guess it could be shorter, but I'm not a native English speaker and can't come up with anything better at the moment. Also, they are not stronger than normal horses but weaker, their CS is just 14.

I'll start a discussion regarding Hand-axe later.

Thanks a lot! :)

**Comment by LoneGazebo** [comment]
Makes sense re: name. I'll fix. Sorry, meant to say that regular horsemen are stronger b/c they use a strategic resource.
