### ISSUE TITLE
6-27-2b early ctd

### ISSUE THREAD

**Issue by 13ananas** [LoneGazebo/Community-Patch-DLL#2069]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 6-27-2b

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): ctd

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

LOGS:
https://drive.google.com/open?id=0B7CN67xROQzvQ0pJWWRMaEZ5Uzg

**Comment by LoneGazebo** [comment]
Minds posting your minidump file?

**Comment by 13ananas** [comment]
Thought I included it in the zip. Reuploaded it, link below. If this isn't the right file, let me know.

https://drive.google.com/open?id=0B7CN67xROQzvV2RDMTUyUEJoZDg
