### ISSUE TITLE
Is there a method in Lua to get the majority religion?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2070]

**Comment by LoneGazebo** [comment]
I believe it uses the existing function- check the religion overview Lua.

**Comment by TechpriestEnginseer** [comment]
Maybe I'm not using the right keywords but I can't seem to find it in the religion overview...

**Comment by LoneGazebo** [comment]
I believe you want: player:GetReligionCreatedByPlayer

**Comment by TechpriestEnginseer** [comment]
Yeah, but what if those religions weren't created by the players?

**Comment by LoneGazebo** [comment]
It grabs made first, then stolen, then majority. That's part of my rework.

**Comment by TechpriestEnginseer** [comment]
This may be problematic, but what if said Judaism was dominating in a civilization that founded Christianity? I'd like the function to grab the Judaism since the religion is the majority rather than Christianity.

**Comment by LoneGazebo** [comment]
Player:GetMajorityReligion().

**Comment by TechpriestEnginseer** [comment]
Actually last question: Would TradeReligionModifier in the policy column work for negative numbers like say -100? I'd like a dummy policy to block off complete religion(owner and foreign).

**Comment by LoneGazebo** [comment]
Should, yep. It is a != 0 test in the DLL.

**Comment by TechpriestEnginseer** [comment]
NoUnhappfromXSpecialists in the policy column, does it stack? Like say I have two policies that offers 4 specialist reduction unhappiness, would it stack to equal 8 specialist reduction unhappiness?

**Comment by LoneGazebo** [comment]
Yep.
