### ISSUE TITLE
Crash on turn following Settlement

### ISSUE THREAD

**Issue by ImZeRipper** [LoneGazebo/Community-Patch-DLL#2071]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

1. Mod List (if using standard CPP set, leave blank):

Yet (not) Another Earth Maps Pack (v 23)
       (although it crashes even without this mode loaded)

2. Type of error (i.e. crash, interface bug, AI quirk): 

Crash to desktop

3. Steps to reproduce:

End the turn after settling city

4. Additional information:

Windows 7 -64bit

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/338069/Lua.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/338072/Database.zip)

2. Minidump file (located in your Civ5.exe directory)

Where exactly is that?

3. Screenshots (if needed)

-----------------------------

If additional information is required, please let me know. (I also couldn't find the minidump files)

**Comment by LoneGazebo** [comment]
This is fixed, will be released soon.

**Comment by ImZeRipper** [comment]
Sweet, thank you.
