### ISSUE TITLE
Merchant delegation getting stuck at sea

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#2072]
@ilteroi, I've noticed that merchant delegations that disembark tend to get stuck. If you want a save for the 6-28 version (EUI), it is below: 
[Askia_0209 AD-1490.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/338329/Askia_0209.AD-1490.zip)

See Venice's MoV.

G

**Comment by LoneGazebo** [comment]
I think we can expanding this to any single-tile operation that cannot reach its target - the unit pair will simply wait on a tile indefinitely instead of moving on, retargeting, or ending the operation.

**Comment by ilteroi** [comment]
crashes on load - callstack is useless, it's not inside the dll - i really don't know what's wrong with me.

**Comment by LoneGazebo** [comment]
Ah, oh well. In any case, you can replicate pretty easily. Just watch for single tile operations that freeze up but keep trying every turn.

**Comment by ilteroi** [comment]
yeah i'll try ... maybe you didn't see because the issue is closed, what was the problem with the crash? i find it hard to believe that it should be due to windows 7 by the way

**Comment by LoneGazebo** [comment]
I responded. It wasn't 'due' to windows 7, but the iterator crash that was CTDing on W10 was only CTDing on W7. Look at the rewritten plot/execute patrol moves.

**Comment by ilteroi** [comment]
ok - kind of obvious in hindsight. annoying. come to think of it, i suspect there are multiple places where it's done the wrong way. might be worth to try and find them
