### ISSUE TITLE
Banderiantes combat movement oddities

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2073]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
June 28th

1. Mod List (if using standard CPP set, leave blank):
+FlagPromotions
+InfoAddict

2. Type of error (i.e. crash, interface bug, AI quirk): 
Bandierantes have an odd attack behaviour/

3. Steps to reproduce:
Move this unit towards the enemy, either from next to them or several tiles away, and if there is a forested tile next to the enemy this unit will circle around and attack from there, even if it means climbing over mountains or other obstacles to do so.
It also seems to not make any difference about the number of turns needed to complete it. You may have all or just one turn and they will still perform these extra steps.

I don't believe the combat is calculated with the forested bonuses as the combat overview panel is shown when the unit is on the correct tile, it's just an odd graphical matter, that and the fact that now the unit ends up in a different tile to that which you expected, if the battle doesn't end in victory.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Just the unit?

**Comment by LoneGazebo** [comment]
No other units do it?

**Comment by Edaka** [comment]
But the amount of turns to attack is the same in both situations, i.e. when attacking straight away from the unforested tile as opposed to taking extra steps to end up on a forested tile, right? Or does that extra movement slow your unit down? If not, attacking from a forest won't make the attack stronger, but it certainly will make defending easier on the turn after.

**Comment by LoneGazebo** [comment]
@ilteroi, is this an AI move thing bleeding over into human play?

**Comment by GrantSP** [comment]
Just that new unit, no other.
@Edaka does make a good point that the unit will now receive defense bonuses due to its new location.

**Comment by ilteroi** [comment]
yep that's a feature :)

**Comment by pandasnail** [comment]
I had a War Elephant take one step back in order to get around a river and attack a city from a different tile without the crossing a river penalty. Problem was that left a Slinger completely unguarded two tiles from the city. I mean the odds are small the enemy city would produce a unit the next turn, but if it had.

**Comment by pandasnail** [comment]
Err I'm an idiot, this is before Engineering, so no unit could get to the Slinger and I actually should have had the Elephant over there. Still weird the game did it for me tho.

**Comment by Edaka** [comment]
Yeah, I was amused when I discovered this myself - amused by the AI pathfinding, that is. Rather strategic, if I do say so. But it's weird when the game can come up with better moves that a human, while playing as a human. If it's easy enough, I'd vote for disabling the feature for humans.

**Comment by ilteroi** [comment]
@LoneGazebo : just pushed a one-line reversal of an experiment i forgot to undo yesterday ...

**Comment by ilteroi** [comment]
disabled the advanced pathfinding for humans. see if you like it better that way ... it considered defensive bonus, disembarkation penalty, river-crossing penalty.

@LoneGazebo : also pushed some other fixes.

**Comment by holder85** [comment]
I have noticed this issue too. The recon units like scout or explorer have same problem.
