### ISSUE TITLE
{5_Turns}

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#2074]
re: Funak's post on the forums.

The city event choice in this case has 5 turns of resistance, but the {5_Turns} option is picking up a much longer value of 30 turns. Not sure if enacting the option would actually cause this or if it is a fault with the hook?

Anyway, can you look into when you have time?

**Comment by TechpriestEnginseer** [comment]
Doesn't the gamespeed affect it?

**Comment by LoneGazebo** [comment]
Which event? Also which post?

**Comment by Hokath** [comment]
Yes the gamespeed will affect it, but I understand that marathon is 3x as long, but 5x3 = 15 not 30

This post: http://forums.civfanatics.com/showpost.php?p=14332977&postcount=6
It is the Gunpowder Plot event, but this has been reported for other events iirc

**Comment by LoneGazebo** [comment]
Gunpowder Plot Choice 3 has <EventDuration>15</EventDuration> as its duration. 15 * 2 is 30 (epic). 15* 3 = 45 (marathon).

The function is working as intended.

**Comment by Hokath** [comment]
Oh ofc it is grabbing duration.
Do things like WLTKDTurns and ResistanceTurns scale with game speed?

**Comment by LoneGazebo** [comment]
I believe so, yes.

**Comment by Hokath** [comment]
aha so if the event duration differs from WLTKDTurns or ResistanceTurns then I need to write "(scaling with game speed)" in the tooltip?

**Comment by Edaka** [comment]
I think it'd be better to remove scaling from those elements, ir possible.

**Comment by LoneGazebo** [comment]
@Hokath having the event choice duration match the WLTKDTurns/ResistanceTurns is the best bet. If you do that, it'll automatically adjust for the game speed in the tooltip. You only need to worry about 'duration' for the core event if you are concerned about keeping the event from firing too often.

**Comment by Hokath** [comment]
Yes I was thinking that. There are one or two places where this won't be possible but I'm sure I can come up with something.
