### ISSUE TITLE
Misspelling in CSD GameplayText.sql?

### ISSUE THREAD

**Issue by ErikSteiner** [LoneGazebo/Community-Patch-DLL#2075]
**Mod Version: 1.6.28**

## 1. Type of error: 
\(3) CSD for CBP\Gameplay\GameplayText.sql
WHERE Tag = 'TXT_KEY_CONGRESS_VICTORY_HEADING2_BODY'

`...Unlike other resolutions, the World Leader resolution cannot be proposed by a civilization. Instead, every other session of the Congress is dedicated to deciding it. During these sessions, which alternate with sessions of regular proposals, the World Leader resolution is automatically proposed to the Congress and no other proposals are made.[NEWLINE][NEWLINE]The amount of delegate support required to win depends on the number of civilizations and city-states in the game, and can be seen on the World Congress and Victory Progress screens. If no civilization receives enough support to win a World Leader resolution, the two civilizations that received the most support will permanently gain additional delegates.'`

I thought that the resolution is called Global Hegemony. If I read this text here, it seems like this is the vanilla text: "the World Leader resolution"

Please leave me a comment, because if true or not I have to alter the text in my translation then.

**Comment by LoneGazebo** [comment]
I'll fix it, yep.

**Comment by ErikSteiner** [comment]
kk, Thanks!

**Comment by ErikSteiner** [comment]
I have to add, that TXT_KEY_RESOLUTION_DIPLO_VICTORY_HELP in IdeologyChanges.sql has the same issue. This was originally the reason why I came to this thing..

**Comment by LoneGazebo** [comment]
Yeah, just Global Hegemony.
