### ISSUE TITLE
Tooltip errors

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#2077]
The mandir hover for more info still says 5%. It is now 10%

The railroad build tooltip on workers describes the +% production boost that has been moved the trainstation and seaport buildings.

**Comment by LoneGazebo** [comment]
Mandir shows 10% for me in the text.

**Comment by Hokath** [comment]
yeah, its the bit where you "hover over for details" in the religion overview

**Comment by LoneGazebo** [comment]
Gotcha, fixin it.
