### ISSUE TITLE
CTD on 6/28

### ISSUE THREAD

**Issue by Fakoleon** [LoneGazebo/Community-Patch-DLL#2078]
Bug Report Template

Mod Version (6/28):

1. Mod List

Full VP + EUI
Faster aircraft
Infoaddict
YnAEMP(v23)
city banner plus (I disabled it, someone told me it's not supposed to be compatible)

2. Type of error 

CTD at the exact same moment, from turn 103 to 104 when it's French AI turn

3. Steps to reproduce:

click next turn ~~

4. Additional information:

it's the first time I use EUI, but it works well, I tried with an installation without it, still crash
I tried with "Patrol" value set to -1, seem not to work too
Also I changed the "Language_en_US"  to my own language on *.sql files

[Patch_civ_change.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/340805/Patch_civ_change.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Did you post your mini dump file?

**Comment by Fakoleon** [comment]
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/341873/CvMiniDump.zip)
Sorry I forget this one
