### ISSUE TITLE
Broken Trade

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2079]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 6-28

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

 Trade bugged.

3. Steps to reproduce:

 - Load my savegame. 
 - Open a trade window with Darius. Put on his side the only silver he has. 
 - Put whales, jade and ivory on your side.
 - Ask him what would make this deal work.
 - He puts forth his offer.
 - Press "Agree"
 - The deal is still not made (Darius still possesses the silver)

[Broken Trade.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/340940/Broken.Trade.zip)

**Comment by LoneGazebo** [comment]
Getting a lua error?

**Comment by saamohod** [comment]
Tbh, I don't understand what's lua error.

**Comment by Edaka** [comment]
It's in your LUA log - if you have logging enabled, post that log here. Otherwise enable logging (there's a tutorial on Civfanatics), replicate the issue and post the lua.log.

**Comment by saamohod** [comment]
I see.
 No, logging is disabled in my game.

**Comment by LoneGazebo** [comment]
Can't help you if logging is disabled sorry.

**Comment by saamohod** [comment]
That's sad.
 What if I enabled logging just now according to instructions? Would that be too late to be relevant for my issue?

**Comment by Edaka** [comment]
Not if you manage to reproduce the issue once again. I suppose you could even load your own save to do that  - I don't think enabling logging breaks savegames. If you get into that situation, the lua.log will show any potential errors.

**Comment by saamohod** [comment]
Ok, nevermind. New version is out.
