### ISSUE TITLE
A Couple of API Requests

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#208]
I have a few (hopefully simple) requests, for whenever possible, listed in order of importance to me.

1) The Policy_BuildingClassYieldModifiers table doesn't currently support negative modifiers, but I would need to use negative values in my Prestige mod. The Policy_YieldModifiers table (added by CP; hopefully other tables added by CP supports negative values as well) supports negative modifiers, so hopefully this isn't a difficult thing to support (I know Policy_BuildingClassYieldChanges works with negative values).

2) Would it be possible to add a Policy_GoldenAgeYieldModifiers table, so that one could have other yields increased during golden ages, or even just to be able to increase the amount of culture or production. I've simulated this effect in Piety for Faith, but in Prestige I want to increase the Culture modifier via a policy, and thought it could be useful/more efficient as a table in the DLL. Though because it can be simulated in Lua, the other request is more important to me.

**Comment by LoneGazebo** [comment]
1 should now be fixed. I'll work on 2 later, as the code is a bit noodly for that.

**Comment by JFDaly** [comment]
Thanks. Please feel free to ignore the second request - it might just be easier to do it my way via Lua.

In any case, as it happens, Policy_BuildingClassYieldChanges doesn't work with Faith (probably Culture, too), so I'd be grateful if you could include a fix to that alongside the BuildingClassYieldModifiers fix.
