### ISSUE TITLE
City governor doesn't reassign citizens on water tiles after blockade is gone

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#2081]
Mod Version (i.e Date - (4/23b)):
May 21st

1. Mod List (if using standard CPP set, leave blank):

VP + some flavour enhancing mods (I don't think they are responsible for this, but I'll list if needed)

2. Type of error (i.e. crash, interface bug, AI quirk): 

When a city's coast tiles are blockaded, they yield nothing and are impossible to be worked, so the city governor reassigns them to other tiles. However, when the blockade is no more, the governor doesn't automatically reassign citizens to un-blockaded coast tiles for quite some time, even if the city is starving as a result. You have to do that manually.

3. Steps to reproduce:

Have a city be blockaded for a turn and then remove the element tha's causing the blockade. 

4. Additional information:

I know my version is old and I've got some additional mods running, so sorry for any inconvenience. I don't think I've seen anything that could've fixed it in the recent patchnotes - hopefully, I'm not wrong.

**Comment by LoneGazebo** [comment]
I'll add a check, see if it fixes it.
