### ISSUE TITLE
Rebels not spawning

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#2082]
Mod Version (i.e Date - (4/23b)):

May 21st

1. Mod List (if using standard CPP set, leave blank):

VP + a couple of cosmetic mods

2. Type of error (i.e. crash, interface bug, AI quirk): 

Rebels don't spawn when razing cities

3. Steps to reproduce:

Raze a city

4. Additional information:

I've only razed a couple of cities abouve 5 population lately and none of them spawned rebels - I thought that's either bad luck or the population was too low. However, I saw somebody else on the forum mention that despite razing often, no rebels have spawned in the last few versions.

**Comment by Edaka** [comment]
Oops, they're not called 'rebels', are they? I forget what they are. I don't mean the guys that spawn when you're unhappy, but the ones that spawn when you raze cities.

**Comment by LoneGazebo** [comment]
Partisans! Works for me - it isn't as painfully common as it used to be, as razing is already quite the chore.

**Comment by Edaka** [comment]
Okay then! (:
