### ISSUE TITLE
'You captured or killed their civilians!' for killing Great Generals

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#2083]
Mod Version (i.e Date - (4/23b)):

May 21st

1. Mod List (if using standard CPP set, leave blank):

VP + some cosmetic mods

2. Type of error (i.e. crash, interface bug, AI quirk): 

Not a bug, but I don't think it's intentional, either. Sorry if it is.

3. Steps to reproduce:

Capture an enemy's great general - get the diplomatic penalty.

4. Additional information:

I think that when this new feature was discussed, there was an agreement that killing great generals shouldn't generate the hate for killing civilian units. After all, they're great generals - killing them isn't the same as killing great scientists, merchants, prophets, etc. Killing generals is sometimes essential to win a war, and losing one is expected when you go to one.

**Comment by LoneGazebo** [comment]
That's how it works right now. You sure you didn't kill something else or raze a city?

**Comment by Edaka** [comment]
Huh, pretty sure I did just kill a general, and upon checking diplomatic modifiers with that civ a turn after, the penalty was there. I can test with the latest version and pure VP tomorrow.

**Comment by LoneGazebo** [comment]
There's a check to prevent generals from doing it, I just looked. Had you razed a city or captured anything else lately?

**Comment by Edaka** [comment]
Perhaps, I can't remember exactly. I was pretty sure that it was the general, but it was some time ago and I finally got to posting about it only now. The penalty for razed cities is a separate one, isn't it?

**Comment by LoneGazebo** [comment]
No, they're in the same thing.

**Comment by Edaka** [comment]
Couldn't reproduce what I've reported. I must've mixed it up with razing, then.
