### ISSUE TITLE
AI doesn't pick up ancient ruins on isolated islands

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#2084]
Mod Version (i.e Date - (4/23b)):

May 21st

1. Mod List (if using standard CPP set, leave blank):

VP + some cosmetic mods

2. Type of error (i.e. crash, interface bug, AI quirk): 

AI quirk

3. Steps to reproduce:

Have an AI spawn near an accesible (i.e., connected to the mainland by coast tiles) island that has ancient ruins on it. As time goes by, the AI doesn't seem at all enthusiastic to send a land unit specifically to pick up the ruins.

4. Additional information:

I lost my screenshots of this, but I often notice that AI, even if pretty late into the game (say, Renaissance), has like three-tile islands nearby with ruins on them, which they've definitely scouted (they often have ships lingering about). 

I have also noticed similar behaviour with barbarian camps that spawn on islands - the AI will kill the barbarians inside by ranged ships, but will never (in my experience) send a land unit to clear the camp. Maybe the priority is too low? (I wouldn't be surprised, since it's only 20 non-scaling gold.)

**Comment by LoneGazebo** [comment]
@ilteroi perhaps the recon algorithm is dissuading offshore looking?

**Comment by ilteroi** [comment]
only scouts care for ruins. but anti-barb teams are not scouts, so if they clear ruins it's by accident.

**Comment by LoneGazebo** [comment]
Maybe we should add a tactical value to ruins? Seems like the AI should snag them if it can. Could add a patrol priority to them.

**Comment by ilteroi** [comment]
ah. turns out that's not quite true. there's a homeland move for it, but it works only if the ruin is within 4 turns' range. that could be an explanation ...
