### ISSUE TITLE
CTD loading savegames

### ISSUE THREAD

**Issue by jordysiu915** [LoneGazebo/Community-Patch-DLL#2085]
Mod Version (July/01/2016):

1. Mod List (if using standard CPP set, leave blank):
Full VP+ no EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD on the moment click load savegame and autosavegames

3. Steps to reproduce:
-plays a new Huge map with 22 players, plays till more than 100-200 turns or more.
-save the game
-load the savegame on the next day or restarting the game.
-CTD upon pressing it to load

4. Additional information:
Although I'm pretty frustrated as I'm only 48 hours new to civ 5 from the steam summer sale. Love the mod. But pretty sad after a whole day playing it, then can't load it back.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Please post your minidump file.

**Comment by jordysiu915** [comment]
I try to upload the zip, but it said not support

**Comment by LoneGazebo** [comment]
You should be able to drag and drop a zip file into the text window.

**Comment by jordysiu915** [comment]
Yes I know, I zipped it by winRAR, but i still get, Unfortunately, we don’t support that file type.

**Comment by jordysiu915** [comment]
I can post my dxdiag, sorry please give me a moment to see whats going on to the zip...

[DxDiag.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/341951/DxDiag.txt)

**Comment by LoneGazebo** [comment]
Huh. Upload it elsewhere and link here. Can't help w/o it.

**Comment by jordysiu915** [comment]
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/341962/CvMiniDump.zip)

**Comment by jordysiu915** [comment]
got it seems something wrong with my winrar software. Thanks for your patients :)

**Comment by jordysiu915** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/341963/Logs.zip)

**Comment by LoneGazebo** [comment]
Thanks!

**Comment by jordysiu915** [comment]
P.S I installed the mod yesterday with VP+EUI, same thing happened, uninstalled mods and install VP+no EUI today, still CTD on loading savegame, so I think its nothing to with the EUI? Hope it helps.

**Comment by jordysiu915** [comment]
Here is one of my savegame that crashed on loading.

[Jordy Siu_0182 AD-1220.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/342034/Jordy.Siu_0182.AD-1220.zip)

**Comment by Avendis** [comment]
Hi jordysiu, how did you manage to upload a zip archive? It doesn't even let me upload text files... "Try again when file is not empty" :|

**Comment by jordysiu915** [comment]
Just use the most basic ones like the one come with initial window 8.1. It seems this web’s fi)e type detector don't recognize zip files from winrar.
