### ISSUE TITLE
That religious wonder thing...

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#2087]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 6-28

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

I am sorry that I have to report that in version 6-28 it still asks for 30% global followers on huge map.

3. Steps to reproduce:

4. Additional information:

**Comment by LoneGazebo** [comment]
Still can't replicate this, sorry. Not sure what you're doing wrong. :)

**Comment by LoneGazebo** [comment]
Ah, got it!

**Comment by Edaka** [comment]
I wonder what it was - something on the DLL side or an elusive typo in the sql?
