### ISSUE TITLE
Upgrading warrior unit to spearman unit

### ISSUE THREAD

**Issue by blueplanetwebdesign** [LoneGazebo/Community-Patch-DLL#2088]
Mod Version July 1st (7-1):
Can not upgrade warrior unit to spearman. Star icon upgrade per unit just randomly displays other actions like delete or sleep.

**Comment by blueplanetwebdesign** [comment]
Bug only happens when there is insufficient gold to pay for upgrade

**Comment by LoneGazebo** [comment]
Do you have a lua log? If not, enable logging and then try it again, then post your lua.log.

**Comment by blueplanetwebdesign** [comment]
It is on the tooltip popup when you hover over the upgrade icon, I will try the lua.log later on.

**Comment by LoneGazebo** [comment]
Not for me, that's why I need your log.

G
