### ISSUE TITLE
CityBoughtPlot bug

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#209]
Currently, CityBoughtPlot doesn't correctly return the X and Y co-ordinates of plots purchased with gold (returning instead the co-ordinates of the Capital) - but it does return them for culture. Whoward corrected this in his latest DLL, but the CP DLL lacks this fix. Could it please be added some time. See below for Whoward's fix.

http://forums.civfanatics.com/showpost.php?p=13770276&postcount=36

**Comment by LoneGazebo** [comment]
fixed
