### ISSUE TITLE
7-1 No settler in UI

### ISSUE THREAD

**Issue by Txurce** [LoneGazebo/Community-Patch-DLL#2091]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/1

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): interface bug

3. Steps to reproduce: get city to where it should be able to grow a settler

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/343761/QuickSave.zip)

4. Additional information:

When I autoinstalled 7-1, I didn't get the EUI. I tried twice. So I manually installed it.  In my MOS folder, I now have the 6 files preceded by a number, then the manually installed CASS v5, plus a UI_bc1 file.

---------------------------
Supporting info

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
UI_bc1 belongs in your DLC folder, not your MODS folder. DLC folder is in just off the root folder where your civ.exe is located.

**Comment by Txurce** [comment]
Hi Gazebo,

That worked -- thanks. Playing hotseat I had a couple of CTDs on reloads
that are not unusual. I dialed up some maps that perversely didn't have a
lot of civs to find, but I have eventually found a third. However, neither
of my capitals can build a settler until it's size 4. is this normal?

The reason I don't know is that I tend to go for Pyramids first, and so
don't notice. But I recall recently building settler in a second city with
less than 4.

If size 4 is the proper threshold, it looks like I'm finally ready to play
hotseat!

Thanks again,
Txurce

**Comment by MoiMagnus** [comment]
Are you sure that you had the tech ? Settler are now unlocked by pottery

**Comment by Txurce** [comment]
That's what it was. I did know the rule, but always research first. In this
test I just clicked on all the techs in a row to save time, and so hadn't
researched it by then. Thanks again for the quick response. I continue to
have my mind blown by this mod.

**Comment by LoneGazebo** [comment]
Cool, closing.
