### ISSUE TITLE
5 Bugs

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#2092]
June 28 version, standard set, no-EUI.

I have five errors in the present game that I have jotted down.  Perhaps not all are bugs, but some are oversights.

#1 - For some reason, Tea has no value to any other civilization.  When I attempt to trade it (with Diplomacy values turned on for reference), it changes nothing, and if I try to send it to an AI for free, even alongside another deal, the Tea never disappears from what I have available.  This is not an issue with any other Luxury item.  Yet, SOME AI's will be willing to trade it, but most it is a zero value.

#2 - I noticed this particularly when attempting to trade Coffee - the AI accepts Coffee as a real thing in the trade value, but when I hit "accept," I look again the next turn only to find out that nothing has been traded.  This happens pretty often.

#3 - There is an event about Universities that gives several options (+2 Sci in all Universities, +1 Faith in all Universities, and others).  Anyways, the "+2 Sci" selection actually *decreases* Science in all Universities by 2, instead of increasing it (my Sci dropped from 190 to 178 the moment I took the option).

#4 - When the appropriate tech came along, I had the opportunity to build a Train Station in my Capital.  I'm not sure if I should be able to build one in the Capital, but anyways - it had neither a Seaport nor a Train Station at the time, plenty of Coal available, so I invested in the Train Station and started building it.  Lo and behold on the next turn, the production stopped, the Train Station was nowhere to be found, and I no longer had the option to build it.  Furthermore, even my cities that are connected to the Capital by Railroad do not seem to have Train Stations available for construction.

#5 - The new Great Prophet scaling works before Industrial area, but no longer functions after it - the scaling needs to match in both cases (way off the scale as soon as we hit Industrial).

The save and the minidump are presently included.

Thank you!

http://www.filedropper.com/james_1

http://www.filedropper.com/cvminidump_2

**Comment by LoneGazebo** [comment]
I'll look at 1-2, but there's a good change that 3 is just because cities shifted specialists/tiles. 4 I'm not sure about (haven't seen elsewhere) - chance your city connections broke? 5 is not a bug, its the games intentional industrial design.

**Comment by Gidoza** [comment]
I know 5 isn't a bug - it was more of a comment that if we're going to make Prophets cheaper in Pre-Industrial, then we should probably have the same thing in mind post-Industrial.

As for #4 - no, my city connection was never broken.

**Comment by LoneGazebo** [comment]
5 is a balance issue, not a bug, though. Balance needs to be discussed on forums. Sorry, but I've tried and cannot replicate any of your reports.

**Comment by Gidoza** [comment]
Fair enough for #5 - I'll bring it up in the Holy Sites thread.  As for the
others, hmmmmm...what additional information would you need in order to
work with these?  (And did you not experience this in the game file I sent
you?)
