### ISSUE TITLE
CTD during Brazil's(AI) turn

### ISSUE THREAD

**Issue by Flamenius** [LoneGazebo/Community-Patch-DLL#2093]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

6-28

1. Mod List (if using standard CPP set, leave blank):

Full Vox populi (no EUI)

2. Type of error (i.e. crash, interface bug, AI quirk): 

CTD 

3. Steps to reproduce:

End turn.

4. Additional information:

Couldn't upload zip so i just saved it here.
https://mega.nz/#F!yhEmhAyQ!y7rhpF3Za0b8XLB1M23smA

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Please update to the latest version (7-1).

**Comment by Flamenius** [comment]
I have done so, unfortunately it crashed while trying to load.

**Comment by LoneGazebo** [comment]
You cannot use an old save on the latest version.
