### ISSUE TITLE
Coffee - Unable to Trade with AI

### ISSUE THREAD

**Issue by V3nomous** [LoneGazebo/Community-Patch-DLL#2094]
1st July

Coffee won't show up in some AI's trade menu ( they have no previous copy of it) , while it  works with others.

---------------------------

**Comment by LoneGazebo** [comment]
Lua.log? If logging not enabled, turn it on and check logs next time it happens.

**Comment by LoneGazebo** [comment]
Coffee works for me - sounds like an install issue.
