### ISSUE TITLE
Sun God Pantheon working besides Wheat

### ISSUE THREAD

**Issue by V3nomous** [LoneGazebo/Community-Patch-DLL#2095]
1st July Version

Normal farm working as intended.
Pillaged by Barbarians.
Research Iron Technology.
Discover Iron on top of Pillaged Farm Tile.
Repair Tile.
Sun God Pantheon now works on Farm.

![bug2](https://cloud.githubusercontent.com/assets/4964370/16530365/aed503d2-3fbf-11e6-89a5-63ea195646bb.png)

**Comment by LoneGazebo** [comment]
Cannot replicate, sorry. The issue however is that you built a farm on a tile that became a resource.

**Comment by LoneGazebo** [comment]
I'll be fixing that.

**Comment by Edaka** [comment]
Does this mean that you won't be able to build farms on any tiles that contain hidden SR, like coal, oil, etc.? If so, that will greatly impair adjacency bonuses.

**Comment by LoneGazebo** [comment]
No, just no pantheon bonus from it.
