### ISSUE TITLE
Crashes at specific turn - 7/1 version

### ISSUE THREAD

**Issue by logic2718** [LoneGazebo/Community-Patch-DLL#2096]
Bug Report Template

Mod Version- 7/1

1. Mod List - full with eui

2. Type of error-crash at specific turn

3. to reproduce - load the attached save game, advance to next turn and accept/refuse Germany's offer.
---------------------------

[Crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/344528/Crash.zip)

**Comment by thibaulthc** [comment]
I have a CTD every time I get to the third turn. No message at all.
I play with the Vox Populi automatic installation, with EUI (tried without, same crash)

Thanks for your amazing work!

**Comment by LoneGazebo** [comment]
I need your minidump file.

**Comment by logic2718** [comment]
CvMiniDump.dmp is in the attached zip file.

**Comment by thibaulthc** [comment]
I'm trying to send the mini dump, compressed in a ZIP file, but I don't succeed...


"Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."
What have I missed ??

**Comment by LoneGazebo** [comment]
Breaks to disassembly, but work is being done on some things.

**Comment by CivFanaticsGrowth** [comment]
CTD at turn 304 (Should be right after you talk to Spain)

Windows 10

Mods:
-     Vox Populi The Complete Experience
-     Faster Aircraft Animations (v.3)
-     Really Advanced Setup (v.15)
-     Thal's FlagPromotions (v.7)

Thanks for looking into it.

[Crash_Turn_304.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/348433/Crash_Turn_304.zip)

**Comment by thibaulthc** [comment]
For my part, it's becoming weirder and weirder...
I didn't change a thing and the game suddenly started to work. I could play till turn 140 in two different games and reload some savegames in the meanwhile. Then I left, quit the game, and now every time I try to load ANY savegames, CTD during the loading screen, no message. :-(
