### ISSUE TITLE
Liberated CS do Nothing

### ISSUE THREAD

**Issue by holder85** [LoneGazebo/Community-Patch-DLL#2097]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
7-1

1. Mod List (if using standard CPP set, leave blank):
R.E.D modpack

2. Type of error (i.e. crash, interface bug, AI quirk): 
Minor Civ AI

3. Steps to reproduce:
City-States(=Minor civs) that occupied by barbarian do nothing after they are liberated.
They don't make any units.
Hoewever, they seems to be able to command unit if Player give a unit to them.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by holder85** [comment]
I've tested about this issue with IGE mod. The minor civ that liberated can repair improvement with worker that given by IGE but can't build any units. They only can build science building and economic building like a puppet cities.

**Comment by LoneGazebo** [comment]
I'm thinking that this a vanilla issue related to whether or not someone puppeted  a city prior to liberating it - I don't think that the 'puppet' value was being reset properly.
