### ISSUE TITLE
Villages not getting bonuses for being on city-connecting roads

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#2099]
Yeah, a pretty much opposite version of what was being reported previously (:
http://forums.civfanatics.com/showpost.php?p=14339491&postcount=48

**Comment by LoneGazebo** [comment]
Works for me.

**Comment by LoneGazebo** [comment]
Mmm, your title is misleading. You meant 'it doesn't work for lighthouse connections.' @ilteroi, can we switch it so that road connections are prioritized over sea connections for cities?

**Comment by LoneGazebo** [comment]
So that, if a city has both a road and a water connection, the road connection is used?

**Comment by LoneGazebo** [comment]
@ilteroi I've fixed this. Adds an additional cycle to the cityconnection function, but is necessary. Also, any reason why we don't restrict minor civs from the cityconnection stuff?

**Comment by ilteroi** [comment]
don't know what you mean exactly, but the minors are there for quests.

i'd be down to take those out however, never liked them

**Comment by LoneGazebo** [comment]
I meant to say, why don't we restrict minors from checking city connections to themselves? I guess an easier one would be to check if a civ has more than 1 city before starting the function.

**Comment by ilteroi** [comment]
ok, that makes sense

**Comment by Edaka** [comment]
Sorry for the title, I was probably in a hurry. It meant to say (according to GamerKG) that sometimes if two cities are connected via lighthouses, then a road between them won't count for villages as a 'connecting' one, so no bonus yields.
