### ISSUE TITLE
Policy Turnpikes

### ISSUE THREAD

**Issue by Shadzy19** [LoneGazebo/Community-Patch-DLL#210]
The +4 gold land routes and the 5% cheaper rush costs seems to work but what is the -25% maintenance cost for improvements?

I choose it and neither my buildings maintenance became cheaper or my roads / railroads.
Improvements arent build faster either.
Afaik there are no improvements any more where u have to pay maintenance for considering forts are free to build and maintain.
I didnt see any benefit or is it bugged?

**Comment by LoneGazebo** [comment]
Yeah, routes are the only thing that cost currently, so it is a useless element. I'll replace.
