### ISSUE TITLE
AI unit don't step into an empty barbarian camp

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#2100]
Bug Report Template

Mod Version (i.e Date - (2016/7/1)):

AI unit don't step into an empty barbarian camp

1. Mod List :

2. Type of error : 
AI quirk

3. Steps to reproduce:
kill the barbarian unit on top of the camp with an archer, when surrounded by ai melee units.

4. Additional information:

**Comment by ilteroi** [comment]
couldn't reproduce - may depend on the mission the surrounding units have at the moment

**Comment by LoneGazebo** [comment]
Yeah, this is just 'a thing' that happens sometimes.
