### ISSUE TITLE
Changes for MoreLuxuries will be loaded, without having this mod active

### ISSUE THREAD

**Issue by ErikSteiner** [LoneGazebo/Community-Patch-DLL#2101]
**Mod Version: 1.7.1**

1. Mod List (if using standard CPP set, leave blank):
Vox Populi (Full Setup with EUI)
I deleted the folder (5) More Luxuries in the Mods folder, so it will not be loaded

2. Type of error (i.e. crash, interface bug, AI quirk): 
(6a) Community Balance Overhaul - Compatibility Files (EUI)
The mentioned module above will insert (update) text- strings for MoreLuxuries without having it activated, nor having MoreLuxuries in the Mods folder.

3. Steps to reproduce:
Navigate to:
(6a) Community Balance Overhaul - Compatibility Files (EUI)\MoreLuxuries\Text\

- Have a look into Text_en_US.sql
- Just read this text-string for instance:
```
UPDATE Language_en_US
SET Text = '+2 [ICON_TOURISM] Tourism once you research Philosophy. +33% [ICON_GREAT_WRITER] Great Writer Rate in the City, and all Writers'' Guilds produce +1 [ICON_GOLD] Gold.[NEWLINE][NEWLINE]Whenever you destroy an enemy unit, receive +5 [ICON_CULTURE] Culture in the City, scaling with Era.[NEWLINE]Nearby [ICON_RES_DYE] Dye: +1 [ICON_CULTURE] Culture, +1 [ICON_GOLD] Gold.[NEWLINE]Nearby [ICON_RES_SILK] Silk: +1 [ICON_CULTURE] Culture, +1 [ICON_GOLD] Gold.[NEWLINE]Nearby [ICON_RES_LAPIS] Lapis Lazuli: +2 [ICON_CULTURE] Culture.'
WHERE Tag = 'TXT_KEY_BUILDING_ODEON_HELP';
```
- Lapis Lazuli is mentioned here
- Now navigate to (2) Community Balance Overhaul\Balance Changes\Text\en_US
- Open BuildingText.xml and compare it with this string:
```
<Row Tag="TXT_KEY_BUILDING_ODEON_HELP">
			<Text>+2 [ICON_TOURISM] Tourism once you research Philosophy. +33% [ICON_GREAT_WRITER] Great Writer Rate in the City, and all Writers'' Guilds produce +1 [ICON_GOLD] Gold.[NEWLINE][NEWLINE]Whenever you destroy an enemy unit, receive +5 [ICON_CULTURE] Culture in the City, scaling with Era.[NEWLINE]Nearby [ICON_RES_DYE] Dye: +1 [ICON_CULTURE] Culture, +1 [ICON_GOLD] Gold.[NEWLINE]Nearby [ICON_RES_SILK] Silk: +1 [ICON_CULTURE] Culture, +1 [ICON_GOLD] Gold.</Text>
		</Row>
```
- So even if you haven't activated MoreLuxuries of Vox Populi, or having it in the Mods folder, the Text string of Text_en_US.sql will always overwrite the string of BuildingText.xml.

4. Additional information:
I made this screenshot in the setup menu, Lapis Lazuli is mentioned here.
Game language is English, no other Mods are active than those mentioned above.
Please correct me if I am wrong, but I always thought that MoreLuxuries is optional, so I wonder why those text strings will be changed..

![20160703152057_1](https://cloud.githubusercontent.com/assets/2684018/16545704/4ba1dde2-4133-11e6-9006-f20465ab0294.jpg)

---------------------------
OFF TOPIC:
Thank you for removing the German translation of CSD, but I noticed that some German translations are still there:
(6a) Community Balance Overhaul - Compatibility Files (EUI)\CSD\CompatibilityText\Compatibility_DE.sql can be deleted, too.

**Comment by LoneGazebo** [comment]
The more luxuries values are still loaded because that changed text is in the compatibility file, not more luxuries. They're interdependent. 

I also was not aware I needed to remove the German translations from elsewhere. I assume you want all removed?

**Comment by ErikSteiner** [comment]
Yes I want to remove this file, too. As far as I can see it, this is the last file containing German text in Vox Populi. The German text will be provided by the Language Pack now.

BTT: So is it correct, to have those information of MoreLuxuries ingame? I mean should one just ignore the Lapiz Lazuli information? I thought that it would cause more issues than just having an information about a resource that is not avaliable, due to removing MoreLuxuries from the Mods folder..

**Comment by LoneGazebo** [comment]
No, it does not cause any problems. Just text b/c more luxuries text files are loaded.

**Comment by ErikSteiner** [comment]
OK. Damn I worked for two days on this issue. I thought that I messed up something in the Framework or in my Language Pack, only finding out that it is still there in vanilla VP. LOL...
Thank you anyway.

**Comment by LoneGazebo** [comment]
Yep.
