### ISSUE TITLE
Random crashing during 10 player game

### ISSUE THREAD

**Issue by straightflushin** [LoneGazebo/Community-Patch-DLL#2102]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7-1

1. Mod List (if using standard CPP set, leave blank):
Vox Populi full + EUI
Faster Aircraft Animations
Quick Turns

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:
Happens at random moments in game

4. Additional information:
10 player game, crash is difficult to reproduce. minidump and logs attached. played a game with no mods after and no longer crashed, otherwise I would have suspected something else.

---------------------------
Supporting information: 

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

[https://mega.nz/#!hc4gSYjB](url)       (minidump and logs)

**Comment by LoneGazebo** [comment]
link does not work, sorry.
