### ISSUE TITLE
Can't pass "next turn" after WC

### ISSUE THREAD

**Issue by Fakoleon** [LoneGazebo/Community-Patch-DLL#2103]
Bug Report Template

Mod Version (7-1):

1. Mod List 

Full VP + EUI
Faster aircraft
info addict
Quick turn

2. Type of error : 

Press "Next turn" does nothing, it happens just after the last civ has been discover, and WC unlocked

3. Steps to reproduce:

Unlock WC?

4. Additional information:

Except the save, what kind of file can be usefull ?
[Ramkhamhaeng_0218 - 1540 ap. J.-C.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/345470/Ramkhamhaeng_0218.-.1540.ap.J.-C.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Try saving and loading the save. Otherwise, I need your logs.

**Comment by Fakoleon** [comment]
well, it seems it worked.. loading just before the last action make it, thanks!

**Comment by Fakoleon** [comment]
I think I know where it comes from, when I set a scout in auto explore, or let him "sleep" far aways, he can get stuck in new tile expansion from other civ, that "wake up" the unit, but you don't get the notification and can't press next.

I think it happen again later on, and when I reloaded the save, I begin in front of the scout

**Comment by LoneGazebo** [comment]
@ilteroi this seems like a fringe issue, but should there be a check for this?

**Comment by ilteroi** [comment]
hmm. i guess ideally we would always focus the unit without orders. don't know why that didn't happen here. when an automated scout is trapped, the automation is cancelled, which sets its status to AWAKE. so it should work.

a sleeping scout however shouldn't care if he's trapped or not (i think). so it wouldn't wake up but it wouldn't block the turn end.

**Comment by LoneGazebo** [comment]
Is it possible that the wake-up command is not triggering properly? i.e. if a unit mission isn't being cancelled properly, the ::update function might not see it as a true unit block.

**Comment by ilteroi** [comment]
i just added a CancelActivePlayerEndTurn() for the explorer. that might help. a general solution would be nice, but i'm not touching that mess ... the whole thing is just so nasty, take a look at CvGame::updateMoves() or CvPlayer::setEndTurn()

**Comment by LoneGazebo** [comment]
Oh yeah, it is gross.

Another thing: I've noticed that CvPathfinder:GetPlotsInReach has spiked in CPU demand recently. Is this a consequence of better pathfinding, or is there a potential bug that's leading to inefficiencies?

**Comment by LoneGazebo** [comment]
Same for CvAStar::FindPathWithCurrentConfiguration

**Comment by ilteroi** [comment]
well GetPlotsInReach is used quite a lot nowadays, but it replaced many other pathfinder calls, so it's a net win.

for explorer moves, there are no changes really - but what is your baseline? what are you comparing to?

in general i'm quite happy with the performance right now. the worst cpu hog is ExecuteGatherMoves, maybe that can be optimized a bit - i'll take a look ...

**Comment by LoneGazebo** [comment]
@ilteroi it may be that GetPlotsInReach etc. are simply more organized sources of use, thus they're peaking higher in the profiler. ExecuteGatherMoves is a little high, yep, but if you are happy with it I wouldn't fret.
