### ISSUE TITLE
CTD when accessing Tourism / Your Culture screen

### ISSUE THREAD

**Issue by wargamernw** [LoneGazebo/Community-Patch-DLL#2104]
Bug Report Template

Mod Version (i.e Date - (4/23b)):  
7/1/2016

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD when accessing the Toursim / Your Culture screen.
[CivVCrash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/345487/CivVCrash.zip)

3. Steps to reproduce:
Load the save game, select Tourism, then Your Culture.  

4. Additional information:
Also, if you end the turn, save the game, then try to load that save, it will CTD on load.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
minidump included?

**Comment by wargamernw** [comment]
Yes.  This crash is 100% repo, so let me know if you need anything else.  I can also do a separate one for the crash on load that happens to saves one turn after.  This was with EUI - I think I forgot to mention that in the report, but running without still causes a crash.

Date: Sun, 3 Jul 2016 21:21:09 -0700

**Comment by LoneGazebo** [comment]
Any other mods?

**Comment by wargamernw** [comment]
Just the ones that came from the automatic installer, CP v.88, CBO v.13,City-State Dip Mod v.27, C4DF-DBP v.11, More Luxuries v.155, and Community Balance Overhaul v.1


Date: Mon, 4 Jul 2016 10:24:16 -0700

**Comment by LoneGazebo** [comment]
I've tried to debug, but it breaks to disassembly. Try verifying your cache and loading a prior save.
