### ISSUE TITLE
[Question] Wonder production in 2 cities changes upon completion of one of them

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2105]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
**July 1st**

----------------------------------------
I had my capital and my next major city producing wonders at the same time, Great Library and Petra, and noticed that both were due to complete on the next turn.
As soon as that turn started I got the wonder completion for GL in my capital but was confused to see that New York was due to complete its wonder in 5 turns time.

So my question is:
Is there some function working here that I'm unaware of that sets back the production input after one wonder is completed or is this a quirk of the game engine.
What made it worse Petra was then completed elsewhere 3 turns later. 2 turns away from I now was but beforehand I would've completed it.

**Comment by GrantSP** [comment]
Okay I'm baffled. Reloaded an earlier save and this time the timing was completely different.
New York completed Petra 2 turns earlier than it would've before and Washington increased the time it would need to just 1 more turn. Weird!!

**Comment by MoiMagnus** [comment]
Each wonder built increase the cost of other wonders.
I'm not sure of the numbers, but its approximatively : 
+ 10% by wonder of the same era
+ 5 % by wonder of the previous era
(And older wonders doen't affect anything)

**Comment by LoneGazebo** [comment]
That's a feature.
