### ISSUE TITLE
Corporation tech tree items

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#2106]
Not a bug report, I just repaired my local installation. Looking through the latest tech tree, I noticed the tech Corporation has a bunch of Corporation icons:

![image](https://cloud.githubusercontent.com/assets/4925402/16563979/1aa507be-41d3-11e6-9400-49ccc293e98a.png)

Is this intentional? You'll never fit all corporation icons in there. Previously I had made it so that only the "Enables Corporations to be founded" appeared. At the moment it looks to me like it's unfinished or overflowing. I don't like "Enables Corporations to be founded" either, anymore.

How about just "Enables Corporation headquarters to be constructed"? Does it make sense to include a free trade route with this tech as well?

On a more bug-report note, the tooltips do not have names on them anyway, so they are confusing:

![image](https://cloud.githubusercontent.com/assets/4925402/16564058/7b934400-41d3-11e6-85e0-3802adbfa299.png)

Any thoughts?

**Comment by LoneGazebo** [comment]
That's intentional. And they have tooltips on my end - you are using all the latest mods yes?

**Comment by LoneGazebo** [comment]
Proper tooltips I should say.

**Comment by mwhiter** [comment]
Just used the latest master pull.

**Comment by LoneGazebo** [comment]
EUI?

**Comment by mwhiter** [comment]
No, I just run with CP + CBP
