### ISSUE TITLE
Random CTD. Not sure as to the trigger

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2108]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
July 1st

1. Mod List (if using standard CPP set, leave blank):
+FlagPromotions v7
+InfoAddict v22

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/346967/CvMiniDump.zip)

3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Breaks to disassembly, which makes it devilishly hard to debug. Could be a lua issue, could be a DLL issue regarding lua. Not possible to debug. We'll see if it replicates in next version.

**Comment by XplosiveLun** [comment]
Hi G,
I've been also experiencing random CTD. I doubt it is related to missionary spreading. I'm using FlagPromotions v7, which is the same as the OP's.
