### ISSUE TITLE
Ranged units combat preview 

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#211]
Ranged units combat preview does not work if you mouse over an enemy unit that is out of combat range.

**Comment by LoneGazebo** [comment]
Does it work in vanilla civ?

**Comment by qqqbbb** [comment]
Yeah, it works in vanilla game. To reproduce the bug select a ranged unit, mouse over an enemy unit with low HP that is within combat range. When you mouse over another enemy unit ( out of combat range), enemy HP on combat preview panel won't update, it will still show HP of the previous enemy unit.

Gazebo, when you close a fixed issue could you leave a comment like "fixed for CP v 4/15".

**Comment by LoneGazebo** [comment]
Yeah, I'll mark it and I'll look at this.
G

**Comment by LoneGazebo** [comment]
Can't seem to solve this. It is fairly innocuous, so I'm going to mark as 'wontfix.'
