### ISSUE TITLE
Can't attack a hostile unit when there is a non-hostile unit on the same tile

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2110]
![8930_20160705163125_1](https://cloud.githubusercontent.com/assets/1131228/16583525/88aeeeda-42cf-11e6-8ee8-f4942c9d0d8b.png)
In this screenshot the "Do you want to DoW Korea" window pops up, but nothing happens when I decline.

**Comment by saamohod** [comment]
IIRC this was an issue in previous versions, too.

**Comment by LoneGazebo** [comment]
@ilteroi I had this fixed a while back, but I think recent changes to the unit missions caused it to return. Care to take a look?

**Comment by LoneGazebo** [comment]
I fix. Me happy.
