### ISSUE TITLE
CTD in start of player 2's Turn.

### ISSUE THREAD

**Issue by AirsofterUK** [LoneGazebo/Community-Patch-DLL#2111]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
Vox Populi (7-1)

1. Mod List (if using standard CPP set, leave blank):
(1) Community Patch	Version	88
(2) Community Balance Overhaul	Version	13
(3) City-State Diplomacy Mod for CBP	Version	27
(4) C4DF - CBP	Version	11
(5) More Luxuries - CBO Edition (5-14b)	Version	155
(6a) Community Balance Overhaul - Compatibility Files (EUI)	Version	1
Calypso's Colored Religious Icons (Basic)	Version	4
Calypso's Colored Religious Icons (Extended)	Version	5
City Limits	Version	7
JFD's Cultural Diversity (Soundtrack)	Version	1
JFD's Cultural Diversity (Core)	Version	9
R.E.D. Modpack	Version	27
Really Advanced Setup	Version	15

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD in start of player 2's Turn Specificaly, but in genral I get CTD's over multiple installs.

3. Steps to reproduce:
Just End the turn, the CTD should occur the moment Player(AI) 2 turn starts.

4. Additional information:
Ive done a chace clear, full delete and reinstall of CIV and new D/Ls of Mods etc.  I think the CTD may be somehow related to the map (Communitas) as I get a CTD if I try to generate a 2nd map either in the game or going back to the Mod menu. Finaly I get CTD's like this without using JFD's Cultural Diversity mods in the past.

---------------------------
Supporting information:
[Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/348501/Save.zip)
[LogFiles.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/348502/LogFiles.zip)
[MiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/348508/MiniDump.zip)

**Comment by Tarzan737** [comment]
I actually get the same CTD but i have non EUI version and other mods!

its in late game for me and it crashes when i hit next turn on player nr 2´s turn, in my case Austria!

i attach my logs but it´s as i wrote i use other mods as well. but maybye you can find something similarities! 

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/349971/Logs.zip)

**Comment by AirsofterUK** [comment]
I just tried the EnableGameCoreThreading in Config.ini. I set it to off/0 from on/1 for me, still get the CTD.

**Comment by LoneGazebo** [comment]
That message was in response to the freezes, not a CTD.

**Comment by AirsofterUK** [comment]
Thought Id give it a try, one less thing it can be.
