### ISSUE TITLE
After Vox Populi installation with EUI, only EUI is active in game.

### ISSUE THREAD

**Issue by chaicracker** [LoneGazebo/Community-Patch-DLL#2112]
Mod Version: 7-1

1. Mod List (if using standard CPP set, leave blank):
Vox Populi Automatic installation with EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 
After installing Vox Populi (with EUI) and activating the mods in game in the right order (from 1 to 6), I can't see any kind of changes to the game except the new EUI interface.
The mods have been properly activated (hitting next after checking all boxes of all six mods).
I already tried the typical troubleshooting tricks, like check file integrity in steam, complete reinstall of the game on multiple drives (SSD and HDD), restart of PC, closing of all active background applications.
Also the Logs, MODS and ModUserData folders have been cleared.

3. Steps to reproduce:

4. Additional information:
As far as I know when the game is successfully modded and playing a modded game, pressing ESC there should be a little MODS line to click on to see the active mods. In all my games this MODS line on the other side of the DETAILS does not exist. It's just blank space.
EUI version and non-EUI version do not work. The only working part is the EUI in the EUI version.
After subscribing to info Addict on Steam Workshop and activating it in mod section at the main menu and starting a game, it didn't show up in game and also not on the ingame Menu.
It seems that mods don't work at all for any reason.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/348603/Logs.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
You are enabling the mods, hitting next, and then starting a game, yes?

**Comment by chaicracker** [comment]
Yes I do, sorry I forgot to write down this obvious step.

**Comment by LoneGazebo** [comment]
Just checking. Loading any other mods in your DLC folder? Windows? If all steps, then not sure.

**Comment by chaicracker** [comment]
I do not have any other mod installed. I'll soon try any Steam Workshop mod to see if any of them works.

**Comment by chaicracker** [comment]
UPDATE:
After subscribing to info Addict on Steam Workshop and activating it in mod section at the main menu and starting a game, it didn't show up in game and also not on the ingame Menu.
It seems that mods don't work at all for any reason.

**Comment by chaicracker** [comment]
Well...

So after finding [this reddit thread](https://www.reddit.com/r/civ/comments/348m35/steam_workshop_mods_not_working/cqtp6x3) I found out that you aren't supposed to click on back to go to the main menu and set up a new modded game.
No, you have to click on the Single Player on the top to set up a modded game.

So the problem is solved.

But, why isn't this major step written down anywhere on the official [Community Patch - How To Install](http://forums.civfanatics.com/showthread.php?t=528034) page?
I understand that this would be fairly obvious for any Civ veteran or someone who plays modded Civ, but with every new wave of new players with Steam sales and especially now when Civ VI is soon to be released, this question could be asked a lot for absolute newcomers to the Civ series or Civ modding.
It wouldn't hurt to write down a line on the How To Install page of the "obvious" step of how to actually start a modded game.

Cheers.

**Comment by LoneGazebo** [comment]
That's what I meant by hitting 'next' and then clicking single player. It is an honest mistake, don't feel bad. Happens quite a bit!
