### ISSUE TITLE
Random Gamefreeze during barbarian turn

### ISSUE THREAD

**Issue by Tsenna** [LoneGazebo/Community-Patch-DLL#2114]
Actually there is a random gamefreeze (not CTD) during barbarian turns, i had this twice in my game with newest Version of **7-1**.

After killing process with taskmgr and loading the game, all is fine ok until the next freeze several rounds later, so its not repdocueable and fairly random.

I dont know, if i can append files for this reason since its no crash, just a freeze.
It seems there is a random loop process anywhere, but dunno.

**Comment by AirsofterUK** [comment]
Ive also had this on 2 games in 7-1, usualy early game with the mods in my other post.

**Comment by LoneGazebo** [comment]
Depending on your computer specs, you may want to try enabling/disabling multicore threading in your config.ini file for civ.
