### ISSUE TITLE
CTD in pathfinder

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#2115]
@ilteroi,

Here's a CTD stackwalk for you. Images:

![untitled](https://cloud.githubusercontent.com/assets/7849458/16637731/0e353d5e-43af-11e6-9879-34c02069e508.png)
![untitled2](https://cloud.githubusercontent.com/assets/7849458/16637729/0e34b690-43af-11e6-821a-323f847d8afd.png)
![untitled3](https://cloud.githubusercontent.com/assets/7849458/16637730/0e3533fe-43af-11e6-94ef-d41d09e2fd5b.png)

**Comment by ilteroi** [comment]
hmm. hard to say. reproducable?

**Comment by LoneGazebo** [comment]
No not exactly. It happened once, and that's it.

**Comment by ilteroi** [comment]
funny, just had a similar crash with an invalid node pointer ...
