### ISSUE TITLE
Civpedia

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2116]
Religious National Wonders all still say they require 20% of the global population.
Blitz still says it has the minus to defense, your changelog says you took that out. (haven't tested)
Weird one, but I noticed one and then did a quick search of the files, and in the following places 'receive' is misspelled: Dojo Game Info, Dojo Strategy, Burial Tomb Game Info, and the Exploration policy (third of three 'receives' in that instance).

**Comment by LoneGazebo** [comment]
Religious National Wonders do require 20%. Changes based on map size, but standard is 20. 

I'll look at rest thanks.

**Comment by pandasnail** [comment]
Well, if you want to keep the Standard 20%, I think there should still be some kind of 'scaling with map size' phrasing.
