### ISSUE TITLE
SQL Bug

### ISSUE THREAD

**Issue by biship** [LoneGazebo/Community-Patch-DLL#212]
[47861.500] Invalid Reference on Policies.Description - "TXT_KEY_DECISIONS_ESTATES_GENERAL" does not exist in Language_en_US

\Events and Decisions\Events and Decisions (CBP Version)\Core\Decisions\Civ Decisions\CivDecisions.sql
Line 159:
('POLICY_DECISIONS_ESTATES_GENERAL',	    'TXT_KEY_DECISIONS_ESTATES_GENERAL'),

Fix(?):
UPDATE Policies
SET Description = 'TXT_KEY_DECISIONS_FRANCEESTATES'
WHERE Type = 'POLICY_DECISIONS_ESTATES_GENERAL' AND Description = 'TXT_KEY_DECISIONS_ESTATES_GENERAL';

**Comment by JFDaly** [comment]
That's an Events & Decisions issue, and quite clearly so. Should report those to Sukritact.
