### ISSUE TITLE
Faith Purchase costs not affected by Policies

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2120]
Using the latest version (7/7), but having also noticed this in a previous version (early June, IIRC), Faith costs seem to be unaffected by policies that reduce them. I've tested this with only the CP (although I also tried with the CBP, but no change) and IGE, and Faith purchase costs remain static regardless of having the Mandate of Heaven policy (which in vanilla reduces Faith costs) or not. Disabling the CP remedies this issue.

**Comment by LoneGazebo** [comment]
That code is untouched - I'll look, but are you sure that you're setting the value properly?

**Comment by JFDaly** [comment]
Hm? I'm not setting any value - this is the vanilla policy that reduces Faith costs.

**Comment by LoneGazebo** [comment]
Which faith purchase costs? Units and buildings? The code is the same as vanilla in those.

**Comment by LoneGazebo** [comment]
The policy does not affect great people.

**Comment by LoneGazebo** [comment]
Vanilla DLL has this:

if (pkUnitInfo->IsSpreadReligion() || pkUnitInfo->IsRemoveHeresy())

Meaning that only inquisitors and missionaries get the bonus. Same as CP.

**Comment by JFDaly** [comment]
(Religious) Units and buildings, yeah.

Vanilla (Before/After policy):
![Before](http://i.imgur.com/wcjLGgK.jpg)
![After](http://i.imgur.com/xGNpOmL.jpg)

CP (Before/After policy):
![Before](http://i.imgur.com/RMWJp3B.jpg)
![After](http://i.imgur.com/TJ0pzz5.jpg)

Really not sure what's going on then.

**Comment by LoneGazebo** [comment]
Odd. Is it a lua thing?

**Comment by LoneGazebo** [comment]
How much does it actually cost when you buy it? I'll take a look, of course, but the code is identical.

**Comment by JFDaly** [comment]
Still cost the whole 200 with the policy.

**Comment by LoneGazebo** [comment]
Odd.

**Comment by LoneGazebo** [comment]
Alright, so I tested it and it works, but you have to advance to the next turn (this is probably the same reason why engineer points weren't showing up for you).

@ilteroi, this section:

if (it!=mModifierLookup.end() && it->second.first==GC.getGame().getGameTurn())
		return it->second.second;

Is the culprit - it doesn't seem to refresh when you select a policy during your turn. Perhaps we should clear this cache when a policy is adopteD?

**Comment by LoneGazebo** [comment]
In int CvPlayerPolicies::GetNumericModifier(PolicyModifierType eType)

**Comment by ilteroi** [comment]
done

**Comment by JFDaly** [comment]
Awesome news!
