### ISSUE TITLE
Events Window available when Events disabled

### ISSUE THREAD

**Issue by ricanuck** [LoneGazebo/Community-Patch-DLL#2121]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 1.7.7

1. Mod List (if using standard CPP set, leave blank):
GR

2. Type of error (i.e. crash, interface bug, AI quirk): 
UI

3. Steps to reproduce:
PLay

4. Additional information:
The Events report window  and its button top right are available even if Events disabled in Advanced Setup.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by JFDaly** [comment]
Try replacing the EventsOverview.lua file in My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files\CoreLua with (this) [https://drive.google.com/file/d/0B2KfUlRX1owlYmF6cllFTERORFU/view?usp=sharing] one. If it works, report back, and Gazebo might implement the change (which is merely wrapping the Dropdown Addin in a check that Events are enabled).

**Comment by ricanuck** [comment]
No need to try it. That is exactly the solution. Was just a minor issue and easy to solve, so I wanted G to know it was there.
