### ISSUE TITLE
A Few Requests for Sovereignty

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2122]
As I've been devoting most of my modding time on Sovereignty (it being nearly complete now), I've picked up a few things that I hope will be simple requests. There will possibly be a few more in the near future, but I thought I'd get some of them out of the way now, so that the end result isn't a huge list.

First, the more important ones:

**CityStateCombatModifier** -- This is for the Policies table, and would grant a combat bonus for units fighting against units and cities belonging to City-States. I'm hoping this tag can be transfered from the Traits table (in which it is used by vanilla Mongolia) to Policies.
**GreatEngineerRateModifier** -- This is for the Policies table, and, like all other GreatXRateModifier, would increase/decrease the rate of Great Engineers (which is the only GP missing from the vanilla table).
**Policy_UnitCombatProductionModifiers** -- this doesn't appear to support negative values, and probably has a gratuitious > 0 check that I hope can be replaced with ~= 0.
**MinorQuestFriendshipMod** -- this one (Policy tag) I ask if you can check that it has support for negative values, as it's difficult to test.
**StrategicResourceMod** -- this doesn't seem to work for anything less than 200%. I would like to use it for 50% only, if that's possible. I'd also like to use it for a negative value, but that is less important.
**GameEvent.IdeologyAdopted(playerID, oldIdeologyID, newIdeologyID)** -- this would trigger when an Ideology is adopted, and should count when an Ideology is changed. There doesn't seem to be an existing event for this, and PlayerAdoptsPolicyBranch doesn't count when Ideologies are changed.

Finally, the ones that would be convenient and more efficient, but are not as important (as can be done in Lua): 
**Player:GetNumNationalWonders()** -- this will count the number of National Wonders the player has in total, akin to Player:GetNumWorldWonders(). This already exists on a city basis, so would seem to be relatively simple.
**Player:GetNumInternationalTradeRoutes()** and **Player:GetNumInternalTradeRoutes()** -- these two functions would count the number of outgoing Trade Routes, similar to GetNumInternationalTradeRoutesUsed(), but distinguishing between International (that is, TRs going to other civs/city-states) and Internal (TRs going between cities).

Any of this would be great, when you have the time (and for whatever works). Thanks!

**Comment by LoneGazebo** [comment]
Alright, done.

CityStateCombatModifier added - you'll need to add the combat enemyunitpanel.lua for this
GreatEngineerRateModifier -- added - should use existing GetGreatEngineerRateModifier lua
Policy_UnitCombatProductionModifiers -- should already support negative values, however the UI may not - check the lua?
MinorQuestFriendshipMod -- supports negative
StrategicResourceMod -- supports negative and any value - may be a lua issue?
GameEvent.IdeologyAdopted(playerID, newIdeologyID) -- added
GameEvent.IdeologySwitched(playerID, oldIdeologyID, newIdeologyID) -- added
Had to make them separate as oldideology ID is not carried into setpolicybranch unlocked

Finally, the ones that would be convenient and more efficient, but are not as important (as can be done in Lua): 
Player:GetNumNationalWonders() -- done
Player:GetNumInternationalTradeRoutes() and Player:GetNumInternalTradeRoutes() -- also done

Link will be below. Includes mercs stuff, so you have a lot of testing to do! :)

**Comment by LoneGazebo** [comment]
[(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/355350/1.Community.Patch.zip)

**Comment by JFDaly** [comment]
Fantastic!

I'll test out the Sov. requests shortly and report back.

I'll have to get back to you on Mercs., that'll take a few days to implement. One question: how does the system know to skip the Merc units from resource/maintenance reqs? I presume that I still create the unit in Lua when the contract is taken out, so how do the two technically relate?

**Comment by JFDaly** [comment]
Everything except GreatEngineerRateModifier seems to work. GetGreatEngineerRateModifier() neither returns anything other than 0, nor do Great Engineer Points (from specialists) have increased value.

Also, you hadn't added GreatEngineerRateModifier and CityStateCombatModifier to the CoreTableEntries.sql file. I added them myself, but I just wanted to let you know, in case you forgot and intend to add them.

StrategicResourceMod is really odd, though - it doesn't seem to be just UI, as I can only build as many (e.g. Swordsmen) for as much of the Strategic Resource I had before taking the policy with the effect. No matter, I can just change the effect, or balance a 200% increase.

Thanks for adding these!

**Comment by LoneGazebo** [comment]
I'll look at great engineer. Go ahead and build it as you want as I probably just flubbed the player memory toggle. I was rushing, in-laws were on the way over!!

**Comment by LoneGazebo** [comment]
Did you try GetPolicyGreatEngineerRateModifier ? That's the one you need to use. Seems setup properly.

**Comment by JFDaly** [comment]
Hm, tried that just now, and that makes no difference. But the actual points I get aren't conforming to the modifier, either. From one Engineer specialist, I should get 1 extra point every 3 turns (as I tested from the Great Scientist), but no go. The tag should be "GreatEngineerRateModifier", right?

**Comment by LoneGazebo** [comment]
Yeah that's the tag, however keep in mind that it is a modifier, so 3 x .25 will not change anything in terms of numbers because of rounding.

**Comment by JFDaly** [comment]
Yea. It doesn't change at all, however. And the GetPolicyGreatEngineerRateModifier() doesn't reflect any change either. The tag is definitely hooked up correctly to the Policy, and the Policy is definitely given to the player. So I really dunno what I could be doing wrong here.

**Comment by LoneGazebo** [comment]
Okay, reworking, will be in next version. We shall see! How about the rest of the changes? Also mercenaries?

**Comment by JFDaly** [comment]
Other changes were fine, yea - just that Great Engineer one. Haven't looked into Mercs. - just started back at uni after mid-trimester break, so settling in to a new routine. Did you see my question about units above? 

(One question: how does the system know to skip the Merc units from resource/maintenance reqs? I presume that I still create the unit in Lua when the contract is taken out, so how do the two technically relate?)

**Comment by LoneGazebo** [comment]
Sounds good.

 To answer question, the unit type is defined (using the lua hook into your table) for the contract and player that took it. All units of that type owned by the player, and all units created for the player (initunitwithnameoffset, etc.) are thus allowed to bypass resource/maintenance/supply checks.

**Comment by LoneGazebo** [comment]
Newest CP has the engineer change in it, BTW. Try it out and report back.

**Comment by JFDaly** [comment]
Yeap, that's fixed it. Thanks!

**Comment by LoneGazebo** [comment]
Awesome to the max. Closing this, as all should now be in.
