### ISSUE TITLE
Can't seem to get a monopoly with East India Company

### ISSUE THREAD

**Issue by Rafs041** [LoneGazebo/Community-Patch-DLL#2123]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
7-7

1. Mod List (if using standard CPP set, leave blank):
Standard cpp, info addict, really advanced setup

2. Type of error (i.e. crash, interface bug, AI quirk): 
Can't trigger a monopoly on marble (stuck at 4/9)

3. Steps to reproduce:
When I built the East India Company, I didn't go over 5/9 , I though it was due to the holy site or something, but when I started working the site to turn it into a quarry my marble went from 4/9 to 2/9 (I still had 3 marble improved though...)

4. Additional information:
I have tried improving all the marble sites with quarrys and/or great person improvements, but I still can't see to get the game to recognize all the marble+ the one duplicated by EAC.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Haven't seen this reported - it is an untouched vanilla function. You are sure the tiles weren't blockaded or anything?

**Comment by Edaka** [comment]
So you had 4 improved marble tiles before completing the EAC? Just in case, it only doubles the resources around the city where it is built - the bonus isn't empire-wide.

**Comment by Rafs041** [comment]
It's the first time this has happened to me, never had any issues with EAC. I know EAC won't duplicate luxuries outside the 3 tile radius, but all my marbles are within 3 tiles of a city, and the city with EAC is the only one that has access to that marble tile, so it isn't a shared marble tile or anything like that.
The tiles aren't blockaded or anything of the sort, I'm at peace at the moment, and I've checked plenty of times with workers on top if I could repair/finish the improvement but I can only do roads.

**Comment by Lerrissirrel** [comment]
I'll need to double check, but I just had a game where I believe I was in the same situation, expecting to go to 5/9 of one resource with EAC completion, and didn't get the additional lux and corresponding monopoly.

**Comment by LoneGazebo** [comment]
I'll check, but it is a vanilla untouched function.

**Comment by LoneGazebo** [comment]
Cannot reproduce this, sorry. Seems to work for me.
