### ISSUE TITLE
Game freezes at barbarian turn

### ISSUE THREAD

**Issue by Sekisetsu** [LoneGazebo/Community-Patch-DLL#2124]
Bug Report Template

Mod Version (i.e Date - (4/23b)): july 7th (7-7)

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): My Game freezes at barbarian turn. When I reload the game, it freezes around the same turn, sometime few turns earlier or later. 
I do nothing during AI turn.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/354108/Database.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/354109/Lua.zip)

2. Minidump file (located in your Civ5.exe directory)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/354121/CvMiniDump.zip)

3. Screenshots (if needed)

**Comment by Tsenna** [comment]
i have disabled barbarians in my game, since then dont have freeze in this turn.

https://github.com/LoneGazebo/Community-Patch-DLL/issues/2114

**Comment by LoneGazebo** [comment]
@ilteroi seeing a few of these reports – can we replicate?

**Comment by skarkov** [comment]
I have this issue too. 
For me it is not re-producable, but will happen every now and then at random. 

Only using CPP package.

**Comment by ilteroi** [comment]
never seen that, otherwise it would be fixed already ;)

seriously, need savegame.

**Comment by LordGhaleon** [comment]
Hey, first post here.

Having the same problem as well. In my current game it freezes every third or fourth turn, before I get 20 or 30 turns where it won't occur occur... only to have the issue happen again, eventually. I'll provide a savegame, but it uses three required mods (Info Addict, Historical Religions and Really Advanced Setup).

Anyway, here's a savegame.
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/360785/QuickSave.zip)

**Comment by Daltyn06** [comment]
I have this issue also from what i have tested it seems to relate to autosaves in some cases. I was getting stuck around turn 270 on epic speed. Then i set autosave to every 5 turns and got to 275 before crash. Then reloaded at 270 set auto save to 0 and played issue free until about 300 before i did a manual save and left the game.

**Comment by Tsenna** [comment]
Yeah, as you stated, it seems there is something weird with saving the game, in Barbarian Turn, the game saves and then freeze, while the Savegame is not broken and can be loaded. 

And since i have turned off Barbarian, i dont have any freeze anymore. 
So it might possible the freeze is related to Barbarians and Autosave or not, hard to say ;)

**Comment by ilteroi** [comment]
just played the savegame to turn 233, but no problem. good for me i guess, but bad for finding the problem

**Comment by LoneGazebo** [comment]
Possible that your debug stack walker stuff is messing with the DLL during auto saves? A lot of game-level data is crunched during the barbarian turn (not actually barb turns but barb logo remains until game level events end).

**Comment by LordGhaleon** [comment]
Started a new game, with Barbarians turned off and no auto-saves, yet the game still froze (at City-States' turn instead), although it took quite a while. First freeze at turn 270 (epic speed), then it seems to happen every fourth turn or so. 

So the answer lies elsewhere, at least for me. Here's another savegame, though I doubt it will help you.
[PortugalFreeze.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/362832/PortugalFreeze.zip)

**Comment by ilteroi** [comment]
stackwalker needs a compile flag to enable, which you don't use i think. could be a thing of debug build vs release build though.

does anyone of you guys who have the problem know their way around the visual studio debugger?

**Comment by LordGhaleon** [comment]
Err... I'm afraid not. Though I could learn, I guess.
