### ISSUE TITLE
GP cost

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#2125]
Bug Report Template

Mod Version (i.e Date - (4/23b)):7/1

1. Mod List (if using standard CPP set, leave blank):

-

2. Type of error (i.e. crash, interface bug, AI quirk): 

Each time I buy a missionary or a inquistito, GP costs increases. I reportet this a few weeks before, but this time I too pictures. 

![20160708202308_1](https://cloud.githubusercontent.com/assets/16065630/16698977/725c8406-4551-11e6-8d7b-578c66b45fb9.jpg)
![20160708202310_1](https://cloud.githubusercontent.com/assets/16065630/16698981/75e02a10-4551-11e6-9d3f-96e1ee75ffe2.jpg)
![20160708202311_1](https://cloud.githubusercontent.com/assets/16065630/16698984/775544d4-4551-11e6-8b5d-9d3b494ed88d.jpg)

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Cost isn't going up - difference between your faith total and the total needed for GPs is going up.
