### ISSUE TITLE
CTD on AI turn

### ISSUE THREAD

**Issue by namlesolbap** [LoneGazebo/Community-Patch-DLL#2126]
Mod Version:
7/7

1. Mod List (if using standard CPP set, leave blank):
-CPP with EUI
-Quick turns
-Faster aircraft animations
-Info addict

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:
Load save
Press next turn

4. Additional information:
-Crash occurs during AI turn one i haven't met.
-Tried disabling the faster aircraft animations and quick turns since they don't affect save games but crash still happens

---------------------------
Supporting information:

Google drive link because github won't let me upload a zip...

https://drive.google.com/open?id=0B_1GSRXwx7IXTWJVbzl1YWlXbWc

**Comment by ilteroi** [comment]
reproduced and fixed
