### ISSUE TITLE
Spawning City States without settlers in incorrect location with YnAEMP

### ISSUE THREAD

**Issue by Raptor-Llama** [LoneGazebo/Community-Patch-DLL#2127]
Bug Report Template

Mod Version (7/7):

1. Mod List (if using standard CPP set, leave blank):

Besides complete CPP with EUI,

*Civ names by policies
*Faster Aircraft Animation
*FlagPromotions
*Global Relations
*Historical Religions Complete
*Quick Turns
*R.E.D
* Yet (not) another Earth map pack (v.24)

Problem does not occur with all mods except CPP activated, thus CPP seems to be the culprit.

2. Type of error (i.e. crash, interface bug, AI quirk): 

Spawn error

3. Steps to reproduce:

A. Launch CPP with YnAEMP v.24 (be sure to edit Ynaemp.lua as seen here or else you will have a CTD:  http://forums.civfanatics.com/showpost.php?p=14242824&postcount=423) and IGE

B. On map setup select 41 City States, spawning TSL CS only.

C. Launch game

D. Complete the first turn so it is easier to see the City States that did successfully spawn

D. Reveal map with IGE and search around; two spots they appear often seem to be Ireland and Japan. You should see city state warriors without settlers spawning very far from their TSL. In my game a Wellington warrior was in Ireland. In another instance a Vatican warrior was in Japan.

4. Additional information:

Attached is log in the game where a Wellington warrior spawned in Ireland. In the Lua.log, Wellington could not be found, but there were several city states that read, for example:

[1640652.531] WorldBuilderMapLoader: Search starting position for Minor Civ : 58
[1640652.546] WorldBuilderMapLoader: No TSL for : 58

I assume Wellington was one of these and was supposed to not spawn but ended up doing so.

This error does seem particular to YnAEMP as it deals with its TSL placement and systems, but when YnAEMP was launched without CPP, all city states that spawned successfully spawned with settlers in their TSL. Thus there is some strange interaction with CPP that is causing this behavior.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/355294/Logs.zip)

**Comment by LoneGazebo** [comment]
I think TSL in general messes up with the CP b/c of scenario quirks in YNAEMP. Try one of the other earth map setups.

**Comment by ErikSteiner** [comment]
In my opinion the coordinates of those "Minor Civs" is just wrong, if I assume that a starting position should be on land. I for example found out that Wellington is on water on one map, so maybe they decided to drop the colonization of New Zealand.

**Comment by LoneGazebo** [comment]
Please report to the YNAEMP people, yep. Closing.
