### ISSUE TITLE
Question to ReligionText.sql - TXT_KEY_BUILDING_MANDIR_TOOLTIP

### ISSUE THREAD

**Issue by ErikSteiner** [LoneGazebo/Community-Patch-DLL#2128]
**Mod Version 1.7.7**

### 1. Type of error: 
Navigate to: (2a) Community Balance Overhaul INT (v 1)\Balance Changes\Text\en_US\ReligionText.sql
TXT_KEY_BUILDING_MANDIR_TOOLTIP
`+3 [ICON_PEACE] Faith, +2 [ICON_FOOD] Food[NEWLINE]+10% [ICON_FOOD] Food[NEWLINE]1 [ICON_GREAT_WORK]`

Is this intended to give +2 Food first and then +10% in addition? Providing a solid figure first and a modifier in addition, seems a bit strange to me..?

**Comment by LoneGazebo** [comment]
Intentional yes.
