### ISSUE TITLE
Blitz still has -20% CS while defending

### ISSUE THREAD

**Issue by Ta1kavarpu** [LoneGazebo/Community-Patch-DLL#2129]
Mod Version:
7-7

Issue:
Blitz still has -20% CS while defending. Wasn't it supposed to be removed?

![20160709115203_1](https://cloud.githubusercontent.com/assets/19976711/16707061/cf6a771e-45cb-11e6-95fc-cf9732c40b60.jpg)

**Comment by pandasnail** [comment]
I already reported this, but also, at least by my reading of PromotionChanges, its only a tooltip error and Blitz is penaltyless in functionality.

**Comment by LoneGazebo** [comment]
Is just text, already fixed.
