### ISSUE TITLE
Bombard UI

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#213]
When I bombard with a city/unit the UI does not function properly. Random squares light up red. This has no effect on gameplay. Using CP/CSD/C4DF/Whowards City bombardment mod
Issue goes away if I replace CP with DLL - various from pix'n'mix site.

**Comment by LoneGazebo** [comment]
Don’t use the bombardment mod as it is already incorporated (this is explained in the changelog of the mod).
G
Jeff Grooms
thewizardofwas@gmail.com

**Comment by Hokath** [comment]
Ah I must have missed all those incorporation. This is going to make clearing the cache a lot faster! Great!

**Comment by Hokath** [comment]
Are you sure this isn't only for the CBP? I don't see this effect, and when I run a search for City Bombard in the CP I don't find anything that would change the range as per Global City Bombard Range

**Comment by LoneGazebo** [comment]
This is for the CBP, yes. Are you only using CP?
G

**Comment by Hokath** [comment]
Currently I am using CP/CSD/C4DF and other mods, and the bug went when I changed CP for DLL as stated in the OP. I tested it with just CP+mod in the CP version previous to the one I am running. So I'm fairly confident it's coming from the CP.

Btw, are all those 'incorporations' only for the CBP as well?

**Comment by Hokath** [comment]
It's looks like this bug that I found searching the thread on fanatics: http://forums.civfanatics.com/showpost.php?p=13644896&postcount=1043

**Comment by LoneGazebo** [comment]
You can’t use the CP + CSD + C4DF without the CBP. CP+CBP sure, or CP alone, but not as you have it setup.

thewizardofwas@gmail.com

**Comment by Hokath** [comment]
Ah well that's not how I interpreted the How To Install page at all. I guess that's what "If you are using CSD, C4DF and EUI, you will need to use the CBP - Compatibility Mod (EUI Version)." means, though I interpreted that to mean 'if you want CBP and you have these other things...'

That's a bit sad :( I had always used CSD and CP in the past.

**Comment by LoneGazebo** [comment]
Sorry, I made that change recently to make updates and compatibility more manageable. Since 95% of users use the CBP, I felt it was a fair compromise.

thewizardofwas@gmail.com

**Comment by Hokath** [comment]
I understand. 
A final query, if you will, these Whoward mods that are 'incorporated', are they only for the CBP?

**Comment by LoneGazebo** [comment]
Many of them are CPB only. I believe I have marked them on the unified log. If not, let me know and I will check and do so. 

G

**Comment by Hokath** [comment]
I'm guessing the list on the Unified Log is all CBP. It doesn't specifically say when the transition occurs, but I assume that by that point we are into CBP territory. Thanks for taking the time to sort me out, G. Much appreciated.

Back on topic, the bug in the OP still stands.

**Comment by LoneGazebo** [comment]
That bug exists because of a change in directional enums in the CP. Try this: https://www.dropbox.com/s/0jwm3sfldxixn15/Bombardment.lua?dl=0

Download this file, and drop it in the UI folder of the Bombardment mod of Whoward, Should fix while using CP.

**Comment by Hokath** [comment]
Thanks G, that works a treat.

**Comment by LoneGazebo** [comment]
Glad to hear it! 
G
