### ISSUE TITLE
'Hurricane approaches' kills population even though it does not occur

### ISSUE THREAD

**Issue by Ta1kavarpu** [LoneGazebo/Community-Patch-DLL#2130]
Mod Version:
7-7

Issue:
The population in my city went down from 21 to 17 even though the hurricane did not hit.
![20160709134453_1](https://cloud.githubusercontent.com/assets/19976711/16707551/70d8a602-45db-11e6-9975-e1ac7cf67c7b.jpg)

**Comment by LoneGazebo** [comment]
Cannot replicate – works for me.

**Comment by F0rst1** [comment]
I've seen it happen several times. Whether the hurricane hits or misses, my city loses population. It also loses population even if I paid 500 gold to protect the people.

**Comment by Hokath** [comment]
i saw this just now also

**Comment by LoneGazebo** [comment]
Interesting. I'll try to replicate.
