### ISSUE TITLE
Buglist/Observations/Notes From July 1st

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#2131]
Hi!  Just finished compiling this list of things that I noticed in my July 1st version game.  I think one of the things was fixed in the July 7th version, but there's a number of notes that seemed relevant.  SOME MAY NOT BE BUGS!!!  But may just be confirming that something is really supposed to work that way.  Most are very straight-forward.  For reference, totally standard version, no other mods, NON-EUI.

1.  City-State Quests often ask for stuff you already have and are instantly fulfilled (e.g. longing for the Musician's Guild when it exists and has existed for hundreds of years, and I think it repeats itself, too).

2.  (think this was fixed for July 7th) I saw many AI Great Diplomats just sitting in their cities doing nothing.  I didn't own *all* City-States, so surely they could have used them on the remaining 5 to create alliances.  Furthermore - can a Great Diplomat create an Embassy with a City-State that is presently warring him?  If so, an escorted GD could easily help to swing votes like that.

3.  The retreating unit bug occasionally still occurs EVEN if graphics are off!  In the whole game, it only ever happened twice - but it still DOES happen!  I can't explain why, though.

4.  When an announcement pops up that you have just become the ally of a City-State (in this case, I noted that it was a Maritime province), the description says "4 Food in Capital, 2 food in all other cities," even though era scaling has gone way past that (wrong description).

5.  Horse units that have Double Attack (Logistics?) can still move after attacking the second time.  Is this intended?  If not - what is just described is what is happening.  On the other hand, if it is intended, then the description on the symbol for Logistics is incorrect (says that the unit loses all movement after 2nd attack).

6.  If using the cursor to hover over certain tiles that are providing Tourism or Golden Age points, the hover tooltip does not include the yields for Tourism and Golden Age points, even though the tile does.

7.  In the Faith bar (when you click on your Faith per turn and it opens a new window), after Industrial Era, it still says "Faith needed for next Great Prophet" even though Great Prophets are no longer acquired automatically, and also the value is not the same as the actual purchase value.

8.  As previously reported - really wacky behavior from Train Stations.  I had Railroad connections from cities to my Capital and couldn't build Train Stations in any of them (didn't have Seaports built).  Yet, I had cities on completely different islands, that had City Connection via Lighthouse, yet certainly no Railroad connection and absolutely no way to ever get one there (zero land connectivity), yet these cities could build Train Stations.  What the heck???

9.  Foreign Legion unit description says that it gets a combat bonus outside of friendly territory, when the combat bonus actually registers inside friendly territory.

10.  Puppeted cities are often not building anything but Gold (I don't mind their building Gold - as long as they finish all the other buildings first...).

11.  The Game Advisor suggests that putting a Railroad on a Strategic/Luxury Resource will connect the resource to your empire, even though Railroads don't do this.

12.  Paratroopers no longer have the Parachute icon.  I hope this is a bug, because it seems really sad.  :(

That's it - thanks!
-Gidoza

**Comment by pandasnail** [comment]
I really thought I had already reported the first one, but I can't find it, so I guess I forgot. Anyway, I've only seen it with NWs that can be built more than once, and never after the number has been reached. IE Guilds in VP. And like you say, I get the reward the very next turn.

**Comment by LoneGazebo** [comment]
1. I'll look. 
2. Fixed already.
3. May have had a promotion allowing it.
4. Vanilla notifications limitation, cannot fix.
5. Yes. I'll look at text.
6. EUI limitation, not my domain.
7. LUA limitation, vanilla issue. Not my domain.
8. Try latest version. Fixed already.
9. @ilteroi, we should check this. May also be a lua issue - is bonus actually working, or is it just UI snafu?
10. Won't build buildings if you are in debt.
11. Game Advisor is baloney.
12. Nope – went to later spec ops units who are also paratroopers. Intended.

**Comment by Gidoza** [comment]
Cool!  Thumbs up to all except #10 - I don't recall ever being in debt during that game, so this doesn't seem like an explanation.
