### ISSUE TITLE
VP-7-1: I cannot recapture my own city

### ISSUE THREAD

**Issue by erinaceus73** [LoneGazebo/Community-Patch-DLL#2133]
Bug Report Template

Mod Version: Vox Populi 7-1

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

My city is captured and then I cannot recapture it: 
my unit (musketman) attacks the zero HP city (zeroed by trebuchet)
but cannot enter... (when trying to move, denying red circle is on the city tile)

3. Steps to reproduce:

sorry, cant attach zip here

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Lerrissirrel** [comment]
musketmen are ranged units, and as such not able to capture cities, aren't they?

**Comment by erinaceus73** [comment]
Oh, sorry, you are right - I tried it with a fussiler there and it was OK, I could take the city - thanks, I will learn the new stuffs... :)

case closed
