### ISSUE TITLE
Selecting a move with a unit you own while it is not your turn game stops responding

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#2134]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

7/7

1. Mod List (if using standard CPP set, leave blank):

+ (7) events for CBP.

2. Type of error (i.e. crash, interface bug, AI quirk): 

Selecting a move with a unit you own while it is not your turn makes the game stop responding

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
@ilteroi, probably need a isgamecorebusy or 'isactiveplayer' check somewhere to prevent this, no?

**Comment by ilteroi** [comment]
reproduced - seems to be a deadlock because of a lua call from the pathfinder, which cannot execute because the main thread is blocked waiting for the pathfinder ;)

![image](https://cloud.githubusercontent.com/assets/1358966/16715267/1f206164-46db-11e6-80fc-f7f668347d6a.png)

need to think to find a good solution ...

**Comment by ilteroi** [comment]
ok - point fix seems to work. there is a special pathfinder exclusively for UI purposes, but it wasn't being used for unit swaps. hope this was the only place.

on the other hand, calling lua from the pathfinder (however indirectly) is an extremely bad idea, performancewise. it doesn't show in the profiler, so it guess it's rare, but it might explain some runtime spikes i've been seeing. but there's no easy way to prevent it at this point.
