### ISSUE TITLE
New Event Choice Tooltip error

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#2135]
The event choice auto tooltip thing is great!
Found an issue when testing my new events: 

![](http://i.imgur.com/bpckZEu.jpg)

I have a caravansary (requiredanywherebuildingclass)
but it lists it many times !
The real reason I cannot enact is the gold cost from EventCostYield

**Comment by LoneGazebo** [comment]
Is that the player-level event or city level? I just missed a break statement, seems like.

**Comment by Hokath** [comment]
player level

**Comment by LoneGazebo** [comment]
Figured. I know why will fix.
