### ISSUE TITLE
CTD accessing tourism screens & CTD loading recent saves

### ISSUE THREAD

**Issue by Lerrissirrel** [LoneGazebo/Community-Patch-DLL#2136]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/7

1. Mod List (if using standard CPP set, leave blank):

Standard EUI CPP
Colored religions
Infoaddict

2. Type of error (i.e. crash, interface bug, AI quirk): 

Initial crash happened going to tourism screen.  I was going to "optimize", but as I was noticing the optimize buttons were not there, it crashed.

After the initial crash, I found that all recent saves (back to about 20 turns) from that game all crash as they're loading.  Let me know if you're curious if any particular things happened "recently" in the game.

3. Steps to reproduce:

Crash on save game load.

4. Additional information:

I've got some other mods (custom civs, that I'm not using in this game and are not enabled) in my mods folder.  Once upon a time I was told just having these in the mods folder could cause problems.

This save is an autosave from about 20 turns before the "real time" crash but crashes on load.

---------------------------
Supporting information:

[lerrissirrel_7_7_CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/356072/lerrissirrel_7_7_CTD.zip)

**Comment by LoneGazebo** [comment]
If those buttons aren't there, you have a mod conflict. Please clear out mods not tied to VP and try again.

**Comment by alonrash** [comment]
I don't know if it's the same problem, but i'm also experiencing many CTD's (7/7 version, no other mods).
I didn't notice a repeating method that causes it. Every game just suddenly crashes.
I Also can't load any autosave, and if I load a "working" save, the game always crashes in a few turns.

I can't upload any files, though it's a ZIP, which should work. Any advice? And also what files do you need? I picked the ones that seem helpful, but don't really know what you need.

**Comment by LoneGazebo** [comment]
Repeating CTDs are not common. Make sure you are on latest civ and that your mod folder is clear of inactive mods.

**Comment by Lerrissirrel** [comment]
Not sure if you intended that clearing out the other mods my resurrect my game (I assume not) but just to be clear, the saves are still busted, although I did go back quite a few more turns and found one that still loads.  I'll start a new game without the other inactive mods.  Feel free to close this item if you want for now.

**Comment by Leviathan37** [comment]
I would add that, in my crash I got error loading *.dds files on tourism and diplomacy buttons, and a few (5<) more, after updating to current version old saves don't work anymore.

**Comment by LoneGazebo** [comment]
Old saves not compatible.
