### ISSUE TITLE
AI Venice can annex

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#2137]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
7/7

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
AI Venice has an occupied city. Shouldn't be possible since Venice shouldn't be able to annex. I haven't tried, if human player can also annex with Venice.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![20160709212542_1](https://cloud.githubusercontent.com/assets/18663580/16714421/1073dbe2-46cb-11e6-9856-88b86ecb2c3d.jpg)

**Comment by Hokath** [comment]
seconded

**Comment by Ta1kavarpu** [comment]
I saw this happening as well.

**Comment by TechpriestEnginseer** [comment]
rip venice unintentional buff gets removed.
