### ISSUE TITLE
Folower belief / Inspiration: unclear description

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#214]
The description of the Inspiration followr belief says:

"+1 culture for each follower (max 5 culture)"

It does not mean the max total from this belief is 5 culture, does it? Is it max 5 culture per city?

**Comment by LoneGazebo** [comment]
Per city.
thewizardofwas@gmail.com

**Comment by Vyyt02** [comment]
Ok, thanks for the reply, then I suggest to include the "per city" in the description.

**Comment by LoneGazebo** [comment]
Well, considering that all follower abilities are per city by design, that feels a bit redundant, no?
G

thewizardofwas@gmail.com

**Comment by 8h42** [comment]
Glad to hear that.
I believed that "each follower" meant each follower "citizens".

These beliefs also mean each follower "city"?
+1% Gold for each follower (max +10%)
+1% Science for each follower (max +10%)
+1 Faith for each follower (max 5 Faith)
+1% Food for each follower (max +15%)

From a non-English-speaking person.

**Comment by Vyyt02** [comment]
Redundat maybe, but would it hurt to include the "per city" in the descriptions for all relevant beliefs? I think this can be a bit confusing for new players.

If you want, I will update the texts for you - they are in FollowerText.sql, right?
