### ISSUE TITLE
Could Event Audio Prematurely End

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2140]
So, I'm adding a little background music which is up to 7 seconds on each of my events. But if the player decides to click whatever and choose it, the background music will play on along with the event choice audio. Which can be a little conflicting.

**Comment by LoneGazebo** [comment]
There's not, no. Once queued, there's no way to end an audio sample as we don't have control over the audio API.

**Comment by TechpriestEnginseer** [comment]
How do tech audio and wonder audio end prematurely early then?

**Comment by LoneGazebo** [comment]
They have special rules in the DLL. No really.

**Comment by TechpriestEnginseer** [comment]
So, special rules for the Event DLL system? :+1:

**Comment by LoneGazebo** [comment]
No, because audio is all run through Lua and special dll channels. Not possible. I'd ask JFD if he has any ideas.

**Comment by LoneGazebo** [comment]
@jfdaly any ideas?

**Comment by JFDaly** [comment]
No ideas either. I'd looked for a way to end tracks earlier, when I did a similar thing, but no luck.

**Comment by LoneGazebo** [comment]
I figured so - I'll close, as there is no solution to this.
