### ISSUE TITLE
No City States?

### ISSUE THREAD

**Issue by migalhas20** [LoneGazebo/Community-Patch-DLL#2141]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
7/7

1. Mod List (if using standard CPP set, leave blank):
CPP with EUI
Ingame Editor

2. Type of error (i.e. crash, interface bug, AI quirk): 
No city states in any of my games with this mod

3. Steps to reproduce:
Start a new game

4. Additional information:
Everything else seems fine but still no city states

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Sounds like an install bug. Clear out mods, install VP, update civ.

**Comment by migalhas20** [comment]
I did that twice already, i have all dlc and both expansions and if i start a normal game city states apear, if i start a modded game they dont apear, any fix?

**Comment by LoneGazebo** [comment]
Try a different map script. Sorry, this is a client-side issue, which means there's something up with your install/setup.

**Comment by migalhas20** [comment]
What do you mean by a different map script?

**Comment by LoneGazebo** [comment]
Continents instead of Pangaea, for example.

**Comment by migalhas20** [comment]
I tried the pangea, continents, fractal and communitas one but still no sign of city states.. I really want to play a game with Portugal with this mod but i need the city states.

**Comment by migalhas20** [comment]
Ok so i tried playing by turning one mod at a time and apparently the more luxuries mod is what removes the city states from my games, any reason why?

**Comment by LoneGazebo** [comment]
No. Sounds like you may be missing DLC though.

**Comment by migalhas20** [comment]
Impossible i have all the dlc.

**Comment by LoneGazebo** [comment]
Not sure. Can't help as can't reproduce. I'd post on forums.

**Comment by Vyyt02** [comment]
A very wild guess, but could it be that you have an older version of More Luxuries (maybe from a previous install of VP?) in your MODs folder? Or if you are subscribed to More Luxuries on Steam, first unsubscribe from it, then delete it from your MODs folder (could be under a name different from the one which is bundled with VP) together with all the VP components and then reinstall VP via autoinstaller again.

Also is your Civ5 up to date? The version under the main menu after launching the game should end with .279
