### ISSUE TITLE
CTD during AI Turn, immediatly after puppeting the last enemy city

### ISSUE THREAD

**Issue by chaosmate** [LoneGazebo/Community-Patch-DLL#2142]
Mod Version (i.e Date - (4/23b)): 1.7.7

1. Mod List (if using standard CPP set, leave blank):
Standard set with EUI, nothing else.

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:
- Load Savegame (doesn't matter if last quicksave or autosave)
- Conquer last City and make it a puppet (playing as Venice)
- Start AI Turn
(Doesn't matter how many turns  you wait before conquering it, CTD will come the next AI turn)

4. Additional information:
Game has no winning conditions, it is basically an endless game. Started with 2 vs 2, all random nations.
I additionally uploaded the location.log file, because it is the only one with errors, as far as I can tell.
In the second screenshot there is the graphical bug i have since 1.7.7: some enemy cities are invisible, but can still be targeted.
---------------------------
Supporting information:
Playing the DX11-Steam Version under Windows 10
1. Log files: Database.log and Lua.log needed
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/356175/Logs.zip)
2. Minidump file (located in your Civ5.exe directory)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/356176/CvMiniDump.zip)
3. Screenshots (if needed)
[screenshots.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/356179/screenshots.zip)

**Comment by ilteroi** [comment]
where is the savegame?

**Comment by chaosmate** [comment]
Meh, I'm sorry. I had to find an earlier savegame, because the one not functioning was my quicksave slot. Of course, after several replayed rounds... nothing happened, everything went good.
