### ISSUE TITLE
Couple Things

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#2143]
July 7th version, Standard, NO-EUI

#1 - Armored Cars have all the upgrades associated with a melee unit, even though they're a standard Cavalry-type ranged unit.

#2 - Had a Battleship that had the announcement every single turn that it needed to be promoted, but no promotion would ever occur.

(that's it)

**Comment by LoneGazebo** [comment]
# 2 - was it capped on promotions?

**Comment by Gidoza** [comment]
#2 - No, not even close.

**Comment by pandasnail** [comment]
I've had the second one before, only in a specific scenario, perhaps it was same for you. If I have Logistics on a unit and level up mid turn, its possible to take the next promotion before the right side notification appears. But it still does appear, and just as your instance, appears every turn until I quit and reload. So now I just wait it out.

**Comment by Gidoza** [comment]
More information:  I've actually had it occur on a number of Battleships, now.  It's not unique to Battleships, but it seems to be attracted to them.  Basically, one gets the promotion, uses it up, but the icon on the right side of the screen doesn't disappear till you right-click it, and then everything is okay again.

**Comment by LoneGazebo** [comment]
Is it logistics?

**Comment by Gidoza** [comment]
It might very well be.  Not in the situation anymore, but when I think about it, that makes alot of sense.

**Comment by LoneGazebo** [comment]
The code for that was never touched by us – could be an EUI snafu.
