### ISSUE TITLE
Rounding Up Error In EventChoices

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2144]
If I have ResistanceTurns set as 1 in an Event Choice and I play in Quick.

I have no resistance turn.

**Comment by LoneGazebo** [comment]
Everything rounds down in DLL. That's a C++ thing. I can set a minimum though.

**Comment by TechpriestEnginseer** [comment]
Would be nice for any events that have 1 resistance turn, but players will then report it as a "bug" if they're playing on Quick.

**Comment by LoneGazebo** [comment]
I'll edit for minimums.
