### ISSUE TITLE
Magical disappearance/suicide

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2145]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7-7 full CPP with EUI

1. Mod List (if using standard CPP set, leave blank):

Reseed! (doesn't affect savegames)

2. Type of error (i.e. crash, interface bug, AI quirk): 

Not sure if it's a bug or an intended feature. In any case I will be happy if this is explained.
There is a barbarian archer standing next to my horse archer on the border of a CS. During the end turn "Processing turn for barbarians" the archer unit mysteriously disappears. It wasn't killed by anyone, it just evaporated.
I was able to reveal all the map with the aid of Reseed! mod just to make sure there is no other unit standing nearby that may have killed the archer. In any case the archer disappeared during Barbarians' turn, therefore it's already clear it hasn't been killed.

3. Steps to reproduce:

 Load my savegame, look at the barb archer during end turn "Processing turn for barbarians". 

[Where did he go.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/357101/Where.did.he.go.zip)
![20160711153601_1](https://cloud.githubusercontent.com/assets/16341598/16731183/762cae50-477f-11e6-8c6f-215dd39be36a.jpg)
![20160711154033_1](https://cloud.githubusercontent.com/assets/16341598/16731187/796c412a-477f-11e6-8150-02241a479274.jpg)
![20160711154036_1](https://cloud.githubusercontent.com/assets/16341598/16731194/7c1383d4-477f-11e6-820a-3e5d60f56a7a.jpg)
![20160711154121_1](https://cloud.githubusercontent.com/assets/16341598/16731195/7d4f9256-477f-11e6-85f4-18c55e7dfa69.jpg)

**Comment by LoneGazebo** [comment]
Probably ran up to the city and killed itself against the city. That happens.

**Comment by saamohod** [comment]
I thought about it but there was my unit on his way. 
 And I was watching that archer closely during end turn (with animations turned on). He didn't go anywhere. He just disbanded himself as it seems.

**Comment by ilteroi** [comment]
you're right. it's being scrapped because of a lack of gold. guess the barbarians shouldn't care about that.

@LoneGazebo : any recent changes there?

**Comment by LoneGazebo** [comment]
No, no changes there for me.
