### ISSUE TITLE
CTD when capturing enemy ship on top of embarked archaeologist

### ISSUE THREAD

**Issue by kaspergm** [LoneGazebo/Community-Patch-DLL#2147]
Bug Report Template

Mod Version (CP 07-07):

1. Mod List (if using standard CPP set, leave blank):
CP + a range of whoward mods.

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:
Using a destroyer with the prize ship promotion (upgraded from dutch Sea Begger) to capture an enemy frigate sitting on top of an embarked archaeologist causes immediate CTD.

4. Additional information:
Not sure if this is caused by CP or is just a regular bug in the game. Either way this is a very peripheral issue, but reporting it just so you know.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
@ilteroi care to reproduce? Sounds like a bad unit pointer.

**Comment by ilteroi** [comment]
reproduced and fixed.  trying to show a plot popup on for a not-yet-initialized unit.
