### ISSUE TITLE
War weariness event triggers when not at war

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2149]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
7/7

1. Mod List (if using standard CPP set, leave blank):
+FlagPromotions v7
+InfoAddict v22

2. Type of error (i.e. crash, interface bug, AI quirk): 
My empire was not at war, neither with a major civ or any CSes yet this event triggered.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Sorry, can't reproduce.
