### ISSUE TITLE
Crash on Lategame

### ISSUE THREAD

**Issue by Leviathan37** [LoneGazebo/Community-Patch-DLL#2150]
Mod Version:
7-7, most recent installer

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Crash to Desktop

3. Steps to reproduce:
Loading autosave from turn 450 if more recent not working

4. Additional information:
Minidump file included in logs.zip, Saves included in logs.zip
using Random Seed, using full Vox Populi install
used dx9 version
Crashes don't always occur, might need a few retries
---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/358992/Logs.zip)

**Comment by ilteroi** [comment]
retries of what? simply end the turn?

**Comment by Leviathan37** [comment]
Yes, just ending the turn. It might or might not occur, for me it keeps happening after few turns, couldn't get past turn 460-ish.

**Comment by ilteroi** [comment]
why no burial tombs nowhere?

but i couldn't reproduce the crash. just played from turn 450 to 465 with no problem.

**Comment by Leviathan37** [comment]
Strange, i recall building burial tombs in just about every possible city. Now i'm a bit confused, as it could be some other problem i'm not aware of.

**Comment by Leviathan37** [comment]
EDIT: on old version i got on DX11 version error loading textures, it was something with diplomacy and tourism and something else, on recent version i can't load at all.
