### ISSUE TITLE
Typo in BuildingText.xml of CBO

### ISSUE THREAD

**Issue by ErikSteiner** [LoneGazebo/Community-Patch-DLL#2152]
**Mod Version:** 1.7.7

1. Type of error (i.e. crash, interface bug, AI quirk):  
```
<Row Tag="TXT_KEY_THEMING_BONUS_BROADCAST_TOWER_ALL">
			<Text>KGAZ 89.5FM - Eclectic Radio Mix</Text>
		</Row>
```

I don't want to be fuzzy, but I saw it during my translation.

**Comment by LoneGazebo** [comment]
What's the problem? Eclectic is a word! :)

**Comment by ErikSteiner** [comment]
Never heard of it :D

**Comment by LoneGazebo** [comment]
http://www.dictionary.com/browse/eclectic

**Comment by ErikSteiner** [comment]
Yes I saw it after you made a comment. What an elegant name for a radio station ^^
