### ISSUE TITLE
Can't found a city

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2153]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7-7 full CBP with EUI

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

This was happening in previous versions, too. A settler/pioneer/colonist doesn't have a button to establish a city.
 In my case a colonist has arrived on an island to found a city but the button to "unpack" the colonist is absent.

[Can't settle.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/359218/Can.t.settle.zip)
![20160712144043_1](https://cloud.githubusercontent.com/assets/16341598/16765825/1744095e-483f-11e6-957c-48bb38da67ac.jpg)

**Comment by ilteroi** [comment]
that's because your empire is very unhappy (below -10).

but since this is not the first time this issue comes up, maybe we can find a way to give better feedback to the user? simply greying out the found city icon instead of removing it would be a start ...

**Comment by saamohod** [comment]
Nice to know. I would never have guessed. 
 Thx.

**Comment by LoneGazebo** [comment]
Yeah we should move that check behind the show visible boil and use the tooltip sink.
