### ISSUE TITLE
Localization.log errors from the 7/1 version

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#2154]
I apologize in advance if some of these have been fixed in the 7/7 release. I hope this can be useful nonetheless.

1)

>  [6824.497] ERR: Missing argument 1. (Vassal For {1_NumTurns} Turns (Turn {2_TurnStarted}))
> [6824.497] ERR: Failed to evaluate parameter 1. Vassal For {1_NumTurns} Turns (Turn {2_TurnStarted})
> [6824.497] ERR: Missing argument 1. (Tax Rate: {1_Num})
> [6824.497] ERR: Failed to evaluate parameter 1. Tax Rate: {1_Num}

2) 

> [6827.492] ERR: Missing argument 1. (X-Axis Labels: {1_Num})
> [6827.492] ERR: Failed to evaluate parameter 1. X-Axis Labels: {1_Num}
> [6827.492] ERR: Missing argument 1. (Y-Axis Labels: {1_Num})
> [6827.492] ERR: Failed to evaluate parameter 1. Y-Axis Labels: {1_Num}

3) 

> [7040.668] ERR: Missing argument 1. (They will no longer give you military Units or Science! ({1_Science} [ICON_RESEARCH] Science))
> [7040.668] ERR: Failed to evaluate parameter 1. They will no longer give you military Units or Science! ({1_Science} [ICON_RESEARCH] Science)

4) 

> [7045.410] ERR: Missing argument 2. (({1_NumHappiness} [ICON_HAPPINESS_1] Happiness, {2_Gold} [ICON_GOLD] Gold))
> [7045.410] ERR: Failed to evaluate parameter 2. ({1_NumHappiness} [ICON_HAPPINESS_1] Happiness, {2_Gold} [ICON_GOLD] Gold)
> [7045.410] ERR: Missing argument 2. (({1_NumHappiness} [ICON_HAPPINESS_1] Happiness, {2_Gold} [ICON_GOLD] Gold))

5) 

> [9912.163] ERR: Missing argument 2. (The builders fromm {@2_Civ} are dazzled by your monumental construction efforts.)
> [9912.163] ERR: Failed to evaluate parameter 1. The builders fromm {@2_Civ} are dazzled by your monumental construction efforts.

**Comment by ErikSteiner** [comment]
Erm.. This is very creepy... I opened an issue some minutes ago, about the same issue ( 1) )..

**Comment by Edaka** [comment]
I play in English with a handful of mods, actually, but they are mostly cosmetic. Of course, that doesn't mean that the errors couldn't come from there, but it's unlikely. 

I am pretty sure that the 5-th error, for example, will only show up if you get the popup for completing the Construction Project quest from a city state (the notification actually comes blank, without text). Likewise, to get the 3-rd one, I think you have to attain a military city state as an ally and then lose the ally status. I'm not sure where 2) and 4) come from, though.

**Comment by ErikSteiner** [comment]
Yes you are right. I played the game a bit and got similar errors like you. I was at first only creating the game and played one turn, to find database issues.

**Comment by LoneGazebo** [comment]
closing b/c duplicate issue. Fixed unique element here though.
