### ISSUE TITLE
Espionage AI

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2158]
I noticed how they always put a spy in their capital and your capital, but I wonder if there's a better thinking around this that allows them to put the spies in other cities. Would you mind posting its coding here?

I was thinking using the EspionageState and EspionageResult to make an Espionage mod where having spies placed in cities other than the capital will give you negative events for the civilization in their cities.

**Comment by LoneGazebo** [comment]
I rewrote all that logic, yep. Mainly looks at vulnerability, and then opinion, and then CS Quests etc.

**Comment by LoneGazebo** [comment]
Easiest for you to navigate to it in the espionageclasses file.
