### ISSUE TITLE
Major AI civs not building workboats

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#2159]
I've reported this in the past ( #1458 ), but the problem got ruled out as a mod conflict on my side. I think I saw the AI build workboats after disabling some certain mods, so I carried on.

Now the issue is back again. I don't actually know when it came back - if it ever went away at all - since I don't play often. Now I've made sure that the AI doesn't build workboats even with the standard Vox Populi package and Ingame Editor (for testing purposes) enabled, so it shouldn't be a mod conflict. I have done some edits in the VP's sql and xml files here and there due to some personal preferences, but I haven't touched anything related to workboats/naval tile improvements. 

I am at a complete loss here - I've tried raising the flavor for workboats, but the AI still aren't building them, even with lots of ocean luxuries in their territories. Is anybody else experiencing this? I couldn't find out how to enable production AI logging, perhaps that'd help find out why it's happening? 

Just to clarify: city states build workboats just fine. It's just the major civs that don't.

**Comment by ilteroi** [comment]
cannot confirm

![image](https://cloud.githubusercontent.com/assets/1358966/16779496/cf139c06-4872-11e6-9bb8-aaa22664c576.png)

**Comment by Edaka** [comment]
That's peculiar. What about early game, are they also building workboats then? Your screenshot is from a significantly later era than I got to in my test games. Specifically, I tested up to about 100 turns on quick speed, i.e., not later than Renaissance.

Sorry to bother you, but could you possible provide a hint on how to enable AI production log? That way I'll at least be able to see what's going on, hopefully.

**Comment by pandasnail** [comment]
In the same config.ini as the regular logging enabling, there are more options under the regular enable. I think its likely this one, but not sure since I turned them all on.

Enable Builder AI logging
BuilderAILog = 1

**Comment by Iamblichos** [comment]
Yeah I've been noticing this same problem. I'm not seeing many workboats at all until after turn 100. Even when a city could get better naval growth, they just would not build them. Been working on my own DLL modifications to this with only limited success.

**Comment by Edaka** [comment]
@pandasnail Thanks, somehow that hadn't crossed my mind before. Duh. No, seriously (: I will try it out.

@Iamblichos Yeah, in my recent game I discovered the Celts on a small continents all to themselves with a global monopoly worth of pearls on their territory - all unimproved. Plenty of unimproved fish as well. That was around the compass tech, ~30 technologies into the game, I think. And then there also was Japan with unimproved fish within their borders. Underwhelming stuff.

Any ideas why this might be happening? Not that I might know, just curious. I've tried raising FLAVOR_NAVAL_TILE_IMPROVEMENT for workboats up to 50 - to no avail. When I was testing it (quick speed, deity difficulty, archipelago map, Classical era start) the city states built workboats as soon as turn 5, but there were none for major civs up to turn 50.

**Comment by Iamblichos** [comment]
On a large map, Archipelago, 14 civs and plenty of room, I've seen maybe 4 workboats total built before turn 100, and only 4 because I've done some tweaking (but hasn't been nearly good enough to what I want to see). For some unknown reason that I haven't figured out yet, cities just aren't choosing to use city and economic strategy: AICITYSTRATEGY_NEED_NAVAL_TILE_IMPROVEMENT.

**Comment by pandasnail** [comment]
So a maybe related I've been seeing in my current game is Work Boats just sitting on the resource, not being expending. I guess they are worried about being pillaged? But maybe too worried?

(7/7 version)

**Comment by LoneGazebo** [comment]
@pandasnail turn off workerAIlogging ASAP. It will destroy your hard drive space (gigs and gigs and gigs of logging).

**Comment by LoneGazebo** [comment]
I'll ramp up values in unitsanitycheck.

**Comment by pandasnail** [comment]
I've noticed the files aren't small, but its not 'gigs and gigs' for me, especially since it seems to overwrite itself each time. I mean, I don't need them, no, and you would know way more than me about computers, but I do have the space.

**Comment by LoneGazebo** [comment]
I had one hit 3.4gb for me one time, was a very long, very large game. Nevertheless, those logs are useless, as all essential worker info ends up in the homelandAI log.

**Comment by pandasnail** [comment]
I'll turn them off then, thanks for the heads up!

**Comment by LoneGazebo** [comment]
Yep!

**Comment by Iamblichos** [comment]
man I tried ramping up values some in unit sanity check in UnitProductionAI but only got very limited results.
