### ISSUE TITLE
France art work plunder

### ISSUE THREAD

**Issue by Naturae** [LoneGazebo/Community-Patch-DLL#216]
In my most recent game as France (4/2, More Luxuries, EUI) when I conquored a Dutch city with a Great Work of Art, EVERY French city with an open Great Work of Art slot got a copy of that great work. I'm not sure exactly how the French UA is supposed to work, but I'm fairly certain I wasn't supposed to have 12 identical copies of a painting.

**Comment by LoneGazebo** [comment]
I'll look. Any extra mods I should know about?
G

**Comment by Naturae** [comment]
Nope, just running the standard mods on the Community Patch page (CBP, CSD, Civ IV Diplo, Extra Luxuries, EUI, and the Compatibility files for EUI)
