### ISSUE TITLE
suicide by conquest

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2160]
my lastest AI game - morocco is winning, although carthage looks much bigger on the map - turns out they started conquering their neighbor and had a population boom while already quite unhappy

![image](https://cloud.githubusercontent.com/assets/1358966/16779015/d3c34f78-4870-11e6-8995-a08816333bea.png)

![image](https://cloud.githubusercontent.com/assets/1358966/16778957/9433fd12-4870-11e6-9147-5f34ef8c2704.png)

so, ideas:
- stop population growth when very unhappy? 
- don't start offensive wars when very unhappy? 
- invent a policy which gives a temporary happiness boost after conquering a city?

**Comment by GrantSP** [comment]
stop population growth when very unhappy? 
 -- Definitely the best option
don't start offensive wars when very unhappy? 
-- Not bad either, second choice
invent a policy which gives a temporary happiness boost after conquering a city? 
-- If there is a differentiation between a city captured in a defensive war, then fine. If not then this isn't an option as it will make offensive wars too easy to roll-on and conquer everything.

**Comment by MoiMagnus** [comment]
Stop population growth when very unhappy : 
+Why not
Don't start offensive wars when very unhappy : 
+Bad idea. In case of ideology pressure, war may be the only solution to unhappiness. Moreover, victory also solve unhappiness. But making less likely the AI declaring war is a good idea, and making them raze more cities would also be an idea.
+Invent a policy which gives a temporary happiness boost after conquering a city? Not convinced.

**Comment by LoneGazebo** [comment]
They already do those things, @ilteroi, but we may want to ramp them up even more.
