### ISSUE TITLE
suicide by army

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2161]
this is morocco - they seem to be winning, but it's only because of their large military. unfortunately it has a downside ...

![image](https://cloud.githubusercontent.com/assets/1358966/16779268/c3d6026c-4871-11e6-8d4a-8dfc2478a62a.png)

but notice the budget deficit - the scrapping logic doesn't seem to be working - and neither the build sanity checks

**Comment by GrantSP** [comment]
At least they seem happy about it! ;)

**Comment by ilteroi** [comment]
this is the breakdown

![image](https://cloud.githubusercontent.com/assets/1358966/16793421/30b4aee2-48d1-11e6-8ee5-0f7c818609a4.png)

they even made deals for minus 850 gold per turn. not bad eh

**Comment by Der-Zorn-Gottes** [comment]
I have received significant gpt gifts from the AI before. They do it if they like you.

**Comment by Vyyt02** [comment]
What a beautiful sight!!! Another thing to note is that it seems they do not have any armors (at least not in the screenshot).

**Comment by LoneGazebo** [comment]
AI sometimes goes bananas. Usually b/c they've run out of things to build. Anyways more aggressive scrapping logic seems needed.
