### ISSUE TITLE
Incorrect UI Images Appearing Over Time While Using EUI with VP

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#2163]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
7-7 (Windows 7 OS)

1. Mod List (if using standard CPP set, leave blank):
R.E.D. Modpack v27

2. Type of error (i.e. crash, interface bug, AI quirk): 
UI images (unit/building icons, misc. UI images, backgrounds, etc.) begin to "bug out" and display images from the wrong file/location once the number of images loaded into the game reaches a certain number. This bug only appears when installing VP with the included version of EUI.

3. Steps to reproduce:
This is a tricky one to reproduce as saving and loading a game fixes any current UI image errors, but the further one progresses in a game (and thus the more UI images have to be loaded from the game files) the faster and more frequently the errors occur.

For example: In a game progressing a Normal or Epic speed these UI errors first appear when the game has progressed to about the late Classical Age (when new units and wonders start appearing). However, in the mid- to late-game where all civilizations have been met and units span 2-3 tech eras, saving and loading a saved game will only allow for 5-10 turns of gameplay before enough new UI elements are loaded that the game begins loading images from the incorrect locations.

4. Additional information:
Again, the error here is that at some point in the course of an active game session, something in how EUI loads images for the UI is getting some offset introduced that slowly accumulates as more and more images must be loaded. Once a certain threshold is reached this offset causes the UI to begin loading images from the wrong files, so the UI begins filling with the wrong images or random garbage/nothing (if it tries to load an image from a location/file that doesn't exist or isn't an image).

Also, I have noticed this bug for the last several versions of VP (since late May version, I believe), but it appears to have gotten steadily more prevalent with each new version. I should note that I clear out all of the EUI files from the 'DLC' folder manually before each new version of the mod is installed to ensure that old EUI files are not accidentally retained.

I can provide screenshot examples if needed, but save games will not really help as loading a save clears all previous UI errors until enough new images can be loaded to cause another offset error.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Vyyt02** [comment]
Judging from your description, it is probably not related at all, but these glitches of yours do not sometimes involve strange black squares with random red artifacts inside over some icons (starting to appear only after some time), do they?

If yes, then these are caused by some graphics settings on Nvidia cards - I cannot remember which one it was - some texture shading or something like that. You can try setting all the graphics to the minimum and then gradually increase them step by step until the glitches start to appear - then you will know which setting it was.

**Comment by cdanger341** [comment]
Yes, I get the graphical aberrations you describe as well after playing for a couple of hours without reloading a save. The ones you describe show up on random patches of terrain and other in-game sprite animations as well.

They may be related, but I also get an issue where UI icons start getting replaced with the wrong image after so many UI images are loaded into gfx memory. The wrong icons begin as incorrect art from other icons and in-game assets but eventually include parts of specular and diffusion maps, almost like the code that constructs the UI is pulling images from the wrong location in the files.

This could be related with the Nvidia graphics glitch. If I have time to play around with graphics settings and narrow down what settings causes this I will let you know.

**Comment by LoneGazebo** [comment]
There's nothing in the code doing this. This is a display driver error. Essentially your video ram is capping out and old textures are being replaced falsely.

**Comment by cdanger341** [comment]
Ah, okay. Well that would explain a lot. I'm not sure how Civ5 would be maxing out my rather nice gpu, but I'll try turning down some of the texture-intensive graphics options and give it a try tomorrow when I have time to play around with VP again.

Thanks for the input, G.

**Comment by LoneGazebo** [comment]
Yep!

**Comment by Heinous-Hat** [comment]
I've seen this happen with the R.E.D. unit pack before when also running Gedemon's DLL.. 

If you have the GPU Texture Decode option selected in video options, toggle it off. The option loads all leaderhead scenes into VRAM for fast display which eats a giant pile of video memory. The speed difference will be nil if you're running the game from an SSD.

When troubleshooting this on my own machine, I had the impression that there was some internal (civ5) memory limit being surpassed. I have a 4GB card and with the option switched on, I'd get these graphical errors despite still having plenty of VRAM free (>1GB).
