### ISSUE TITLE
Arctic Expansion AI

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2164]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7-7

1. Mod List (if using standard CPP set, leave blank):

Tectonics Map Script
Thal's Flag Promotions 

2. Type of error (i.e. crash, interface bug, AI quirk): 

AI is settling useless arctic regions while ignoring much better tundra to the North.

![20160713182234_1](https://cloud.githubusercontent.com/assets/16341598/16808887/fe28c868-4926-11e6-9fcc-273ca99d2326.jpg)
[QuickSave (2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/361798/QuickSave.2.zip)

**Comment by ilteroi** [comment]
a savegame from just _before_ the city was founded would be perfect ... but yeah, that happens time and again, don't know why they love snow so much

**Comment by saamohod** [comment]
Sadly, I cannot provide a savegame for the required period. I only spotted these frozen cities long after they were founded. I will be keeping an eye though.

**Comment by saamohod** [comment]
[Expansion bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/362510/Expansion.bug.zip)
![20160713182234_1](https://cloud.githubusercontent.com/assets/16341598/16820880/f4a91f42-495b-11e6-8580-f16c00bb377b.jpg)

 Here is the savegame. It might help if you decide to investigate another manifestation of strange AI behaviour. As you can see in the screenshot the relatively nice area in tundra at the lake with some nice resources is not occupied in year 1916.

**Comment by ilteroi** [comment]
it could be that all the civs in the screenshot have a high bias for coastal cities ... but the ice-locked ones are still bad

**Comment by Der-Zorn-Gottes** [comment]
I don't even know - the deity AI can somehow grow these icetowns larger than my tradition capitol. Once I played against rome, which had more than o dozen of these, and it was the strongest AI I have ever met.

**Comment by ilteroi** [comment]
any plot you can build on is not so bad - in the lategame yield from improvement (especially great person improvements) completely dominates the natural yields. 

add to that the bonuses you get from buildings, then a size 20 city needs only 5 or 6 plots to work. 

AI also uses food trade routes a lot to get their new cities up to par.

but here's the thing, for the selection of the city location they consider only the natural yields (everything else is too speculative) so the score for these cities should be simply bad.

**Comment by LoneGazebo** [comment]
A simple 'x% of no-yield tiles = major penalty' function would probably suffice, @ilteroi .

**Comment by ilteroi** [comment]
that's already there. if there are too many "bad" tiles (no yield) we bail.

but then again what i was trying to express is that even a city in the artic can be fine with a little help. so especially if there are resources there it may make sense. but an ice-locked city shouldn't count as coastal maybe

**Comment by LoneGazebo** [comment]
I think ice features already block that, right?

**Comment by LoneGazebo** [comment]
I leave this to you. :)
