### ISSUE TITLE
Slater Mill

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2165]
Mod Version (i.e Date - (4/23b)): 7-7 with EUI

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

Description for the Slater Mill wonder says it provides "large boost to production" while it shows only +5 production bonus. Correct me if I'm wrong but +5 production doesn't sound "large" in Industrial Era.

**Comment by LoneGazebo** [comment]
Free factory.
