### ISSUE TITLE
Crash around turn 45-55 corrupts savefiles

### ISSUE THREAD

**Issue by EtherealBeaver** [LoneGazebo/Community-Patch-DLL#2166]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
July 7th (1.7.7)

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Game crashes pretty consistently around turn 45-55 and when it happens, the savegame is also corrupted, making it impossible to reload. It has happened in 5 out of 5 games in a row.

3. Steps to reproduce:
Start a new game with only the full community patch mod (UI and all), play 45-55 turns and the game crashes directly to desktop without a prompt 

4. Additional information:
It is a completely fresh install of Civ 5 and the community patch, just upgraded to win10, playing through Steam, game cache verified in Steam and I also manually cleared the Cache folder in the documents/my games/civ folder, but the crashing consists. Fresh install was done after upgrading to windows 10.
I added the latest autosave savefile of the game. The savename looks as if it didnt save at all after the first turn, but I know it saved a few turns before the latest crash.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
[Civ 5 crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/362295/Civ.5.crash.zip)

**Comment by ilteroi** [comment]
i can hardly believe it would crash no matter what happens in those 50 turns. 

also, are really all autosaves corrupted? can you please set the autosave interval shorter (in Civ5.ini) and provide the last one before the crash which works?

**Comment by jordysiu915** [comment]
sigh, similar or identical CTD to you :(

**Comment by Stef012** [comment]
Have similar CTD happening 1400 BC, must be in between turns 45-55, attached the logs and last save that still loads normally (interval 1)

[ctd.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/367987/ctd.zip)

**Comment by ilteroi** [comment]
too many mods in this savegame, sorry

**Comment by EtherealBeaver** [comment]
I did a bit of testing, and the savegames were in fact not corrupted. The game just wont recognize them and shuts down after a long loading time. Im guessing it just gets a run time error or something. 

I did find a work-around though. If I go to Mods, apply all the community patch mods again, start a new game (any setting) and after the game loads, then continue to load my original save file - then it works. It just takes an obscene amount of extra loading times unfortunately.

The point is, that it seems like the game wont apply all the mods automatically upon load, unless they are loaded manually first. Being a complete newbie to Civ 5 mods, I have absolutely no idea why this is unfortunately.

**Comment by LoneGazebo** [comment]
@EtherealBeaver, if your system is somewhat limited on memory, excessive mods can cause problems.

**Comment by EtherealBeaver** [comment]
I know my system is not the newest but this is taking much longer to load than it used to. For good measure, these are my specs: 16gb RAM, i7 2.4ghz quadcore, 64 bit windows, Intel HD Graphics 4600 (3990 on 3DMark). My total load time is 2min 35 seconds. My impression is that, this seems longer than it should

**Comment by LoneGazebo** [comment]
Not sure. If you are using lots of mods, pair it down to the essentials. If for no other reason than we cannot debug games that experience problems if users are using non-VP mods.

**Comment by EtherealBeaver** [comment]
I am not using any mods other than the community mods included, so no other mods are interferring at all. It is also a clean install of the game, with verified gamefiles and manually cleared game cache. Is there anything else I can do, to make sure that there are no other possible outside interferrences?

**Comment by LoneGazebo** [comment]
In your config.ini you can check to see if threading is enabled - if not, enable it. Other than that, it definitely sounds like a client-side issue (possibly hardware, not sure), as I'm not seeing reports of long load times anywhere else.

**Comment by biship** [comment]
I am having the same issue. Started around the 7/7 build. Early game works fine (saving and loading). When I get to around 200 AD, loading a save game crashes to desktop, without any error.

This guy is also reporting it:
http://forums.civfanatics.com/showthread.php?t=570852

MS Visual Studio debug reports this:
Exception thrown at 0x00E23DCB in CivilizationV_DX11.exe: 0xC0000005: Access violation writing location 0x00000000.

`00E23DBC CC                   int         3  
00E23DBD CC                   int         3  
00E23DBE CC                   int         3  
00E23DBF CC                   int         3  
00E23DC0 57                   push        edi  
00E23DC1 8B 4C 24 08          mov         ecx,dword ptr [esp+8]  
00E23DC5 8B 7C 24 0C          mov         edi,dword ptr [esp+0Ch]  
00E23DC9 33 C0                xor         eax,eax  					
00E23DCB 89 08                mov         dword ptr [eax],ecx       <--- crash
00E23DCD 5F                   pop         edi  
00E23DCE C3                   ret  
00E23DCF CC                   int         3  
00E23DD0 83 EC 3C             sub         esp,3Ch  
00E23DD3 8B 4C 24 40          mov         ecx,dword ptr [esp+40h]  
00E23DD7 8B 51 0C             mov         edx,dword ptr [ecx+0Ch]  
00E23DDA 53                   push        ebx  
00E23DDB 55                   push        ebp  `

**Comment by biship** [comment]
For what its worth, and it may not be unusual, but theres a shed load of "crash on loading game" posts here: http://forums.civfanatics.com/forumdisplay.php?f=409
Seem to be June onwards. Or could just be me reading between the lines.
