### ISSUE TITLE
Gandhi founded Gandhi

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2167]
Mod Version (i.e Date - (4/23b)): 7-7 full CBP with EUI

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

 Notification icon says "Gandhi has founded Gandhi! This corporation can no longer be established unless the other player's Corporation Headquarters is destroyed upon city capture"

![20160714025324_1](https://cloud.githubusercontent.com/assets/16341598/16823732/d4c957f6-496e-11e6-9725-bc119ed970aa.jpg)
[Gandi founded.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/362771/Gandi.founded.zip)

**Comment by GrantSP** [comment]
Same as #2148
