### ISSUE TITLE
Outside Friendly Lands issue

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#2169]
OutsideFriendlyLandsModifier for units seems to be malfunctioning - @ilteroi any ideas? Perhaps friendly/unfriendly land not applying properly?

**Comment by ilteroi** [comment]
there's not much can go wrong here (abridged):

		// Bonus for fighting in one's lands
		if (pMyPlot->IsFriendlyTerritory(getOwner()))
			iTempModifier = getFriendlyLandsModifier();
		// Bonus for fighting outside one's lands
		else
			iTempModifier = getOutsideFriendlyLandsModifier();

IsFriendlyTerritory() is also very simple. what exactly is malfunctioning? maybe it's just that the value of the modifier is zero?
