### ISSUE TITLE
Assyria UA

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2170]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/7

1. Mod List (if using standard CPP set, leave blank):
Full VP
Enginseer's version of Events and Decisions and its add on
Enlightenment Era and Xony's Compat mod
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Ice Free Coasts
Celtic City Names, Iroquoian City Names, Randomize City Names
NoAltitudeTraining (removes the Mt. Kilman promo)
My own thing that does various things, nothing with Assyria
Tectonic Map

2. Type of error (i.e. crash, interface bug, AI quirk): So in the Assyria page on the forum, you said this (back in March):

Assyria gets a big science boost if it can't steal a tech outright (sometimes a larger bonus than the tech you might steal).

I am not finding that at all. The science gain has been like a fourth of a tech. Now, I do think that at least at Marathon speed, the Assyrian set of specials is plenty good, and doesn't need to be better. But it seems to go against what you said. Unless its just as simple as being the rare thing that intentionally doesn't scale with Game Speed. (Only one screenshot, but its been around that ratio each time)

(unrelated this is somehow my first game trying the 'new' Siege Tower and I quite love it, so much better. Great work!)

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![nin science](https://cloud.githubusercontent.com/assets/16260521/16838738/ccc0571a-4998-11e6-82da-5d9be48b9b2e.jpg)

**Comment by LoneGazebo** [comment]
Scales on city population, era, and gamespeed. I'll bump up the multiplier a little.
