### ISSUE TITLE
Event Hardcap?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2172]
Does it exist at 256 or doesn't exist at all? I suddenly stopped developing when I realize this was a potential thing.

**Comment by LoneGazebo** [comment]
No cap so far as I know. Did you encounter one?

**Comment by TechpriestEnginseer** [comment]
Well, I've made about 219 event choices and 58 events, but I haven't had any testers yet to see if any buggy business has been made. I'll report later.

**Comment by LoneGazebo** [comment]
Cool. There's no reason for a cap, and I didn't add one.

**Comment by TechpriestEnginseer** [comment]
On another note, I'm trying to do Events that are opened to civilizations with the correct art style. But it seems to me that these two aren't the same despite that they are the same.

````
function ArtEvents(iPlayer)
	local pPlayer = Players[iPlayer]
	if pPlayer:IsMinorCiv() or pPlayer:IsBarbarian() then return end
	local ArtStyle = GameInfo.Civilizations[pPlayer:GetCivilizationType()].ArtStyleType 
	if ArtStyle == ARTSTYLE_EUROPEAN then
		print("this civ is european")
	elseif ArtStyle == ARTSTYLE_MIDDLE_EAST then
		print("this civ is middle east")
	elseif ArtStyle == ARTSTYLE_SOUTH_AMERICA then
		print("this civ is south american")
	elseif ArtStyle == ARTSTYLE_ASIAN then
		print("This civ is asian")
	elseif ArtStyle == ARTSTYLE_GRECO_ROMAN then
		print("the holy roman empire")
	end
end
GameEvents.PlayerDoTurn.Add(ArtEvents)
````
Using firetuner, I am unable to explain why the supposedly same string should print out statements.
![image](https://cloud.githubusercontent.com/assets/13937047/16863652/db282b40-4a09-11e6-83bd-91d774dfeb51.png)

**Comment by LoneGazebo** [comment]
Try using integers instead of ARTSTYLE_GRECO etc. So 0, 1 etc. based on their database order.

**Comment by LoneGazebo** [comment]
Did that work?

**Comment by TechpriestEnginseer** [comment]
It turns out I missed my variables chapter because ARTSTYLE_GRECO isn't ARTSTYLE_GRECO, but rather ARTSTYLE_GRECO is "ARTSTYLE_GRECO", so using integers or that would work either way.

**Comment by LoneGazebo** [comment]
gotcha.
