### ISSUE TITLE
AI stacks his Great Diplomat in capital

### ISSUE THREAD

**Issue by thibaulthc** [LoneGazebo/Community-Patch-DLL#2173]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7-1

1. Mod List (if using standard CPP set, leave blank): 

2. Type of error (i.e. crash, interface bug, AI quirk): AI quirk

3. Steps to reproduce: 

4. Additional information: AI seems to never use any of his Great Diplomats. I didn't see any Embassy. Every capital I invaded or saw was fullfiled with several GD. 

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Update to latest version.
