### ISSUE TITLE
Monopoly calculation

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2178]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/7
 

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk):  Formula bug

3. Steps to reproduce: Monopoly calculation - I have 4 of the 9 fur resources in the world thus <50%, no monopoly. Then I build Great Cothon that gives me 2 extra copies. The formula increases the numerator but not the denominator and says 6/9 = 66% you have a monopoly. Which is incorrect ; when luxury-doubler wonders like this are built, calculation should either ignore the free copies (e.g. still 4/9) OR increase both numerator and denominator (e.g. 6/11). I guess in this case either case would give me a monopoly, but may not be so in other cases. 

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Doubling via a bonus does not change the number of resources in the world, just your extraction efficiency. This is by design.

**Comment by oedali** [comment]
Hey - so consider this scenario: 

10 fur in world. I have 4, the AI civ has 6. I build great cothon and get 2 extra copies. Now we both have 6/10 = 60%. Does the game say it's a dual-monopoly? Both get monopoly bonuses?

**Comment by LoneGazebo** [comment]
Yes. Both get it. This scenario is valid.
