### ISSUE TITLE
Barbarians aren't attacking in bad situations and they refuse to retreat

### ISSUE THREAD

**Issue by ultrafilter** [LoneGazebo/Community-Patch-DLL#2179]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
July 15th (7-15)

1. Mod List (if using standard CPP set, leave blank):
R.E.D. Modpack (v 27)
Faster Aircraft Animations (v 3)

2. Type of error (i.e. crash, interface bug, AI quirk): 
Barbarians are not attacking military units.  I placed a warrior next to two barbarians for a few turns and the barbarians did not move and neither did they attack. I also observed a barbarian standing in place for a few turns. It did not patrol around. However, they do seem to be capturing civilians. I left a worker next to a barbarian and it immediately captured it. 

I couldn't test pillaging since the barbarians never moved from their spawn point except to capture civilians. 

3. Steps to reproduce:
Put a military unit next to a barbarian. 

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by TechpriestEnginseer** [comment]
Maybe it knows it can't win if the barbarian goes against your military unit, so it re-calculating its best chance of survival by fortifying?

**Comment by ultrafilter** [comment]
I tested it further. They'll attack if it's obvious they'll do better (say, four giant death robots vs a warrior), ignore if it's hopeless (warrior vs war elephant),  attack if it's okay (warrior vs warrior). These make sense. But it also ignores if it's slightly bad (warrior vs spearman). They also attack a city and ignore a hopeless fight but I assume that's not a bug.

**Comment by LoneGazebo** [comment]
They block tiles if they can. That's their purpose in life. This is all working as intended.

**Comment by Edaka** [comment]
Most of the time they end up blocking just the tiles right around their encampment, though. It's scary at first seeing an encampment with 2-3 barbarians hanging around, but then they just stand there until they get beaten up (unless, as @ultrafilter mentioned, they can get a favorable fight - then they do move around).

**Comment by LoneGazebo** [comment]
@ilteroi maybe we should make barbs ignore odds?

**Comment by ilteroi** [comment]
fixed
