### ISSUE TITLE
request: make "default" always work Great Person Tile Improvements?

### ISSUE THREAD

**Issue by wobuffet** [LoneGazebo/Community-Patch-DLL#2180]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
07/07

1. Mod List (if using standard CPP set, leave blank):
–

2. Type of error (i.e. crash, interface bug, AI quirk): 
quirk/request

3. Steps to reproduce:
Governor is not assigning a worker to an Academy for some reason (City is plenty big and food is well in the positives either way: +16 vs +20).

**Comment by LoneGazebo** [comment]
Not going to force something, no. Governor looks at valuation versus yields and makes its choices.
