### ISSUE TITLE
Barbarian unit moved to different tile after reload

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2181]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/7

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Bug

3. Steps to reproduce: Turn 22: I was next to a barb camp, with one barb inside the camp, and another that spawned on that turn to its left. I then went onto the next turn. Turn 23: I decided to reload the autosave from turn 22. When it loaded, the barb had MOVED to a different tile. 

4. Additional information: see screenshot

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![20160716115620_1](https://cloud.githubusercontent.com/assets/20485377/16895699/ea7e3bae-4b4c-11e6-9c71-5fd1b3156da3.jpg)

**Comment by LoneGazebo** [comment]
Autosaves save at the end of a turn, so you sure you didn't end up on the 'next' turn?

**Comment by oedali** [comment]
Yes I am pretty sure I loaded the correct save. There is no way to replicate unfortunately because I didn't manually save that turn... This screenshot is AFTER I reloaded that same turn (22)

**Comment by LoneGazebo** [comment]
No idea. Keep in mind that autosaves are not always reliable.
