### ISSUE TITLE
Civilopedia : false and missing informations

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#2182]
(Mod version : VP 7/7)

There is some little errors on the civilopedia : 

**On promotions**
In fact, it seems that the WHoward's promotion tree use the civilopedia to compute the tree, not the ingame promotion system. That is why some links of the tree are missing or false : 
- Scouting II should need Scouting I, instead of needing the same things as Scouting I
- Wolfpack II should need Wolfpack I, instead of nothing
- Flight Deck II and III should need something (probably Fligth Deck I and II)
- Flack Targeting II should need Flack Targeting I (not sure, I've never take this promotion so maybe the current links are good)

**On buildings**
Every building has "Corporation : Centaurus Extrators, Inc". They shouldn't

Moreover, there is some missing informations in the civilopedia.

**Important informations, easy to add**
- On the wonder home page : the fact that each wonder increase the cost of the next ones.
- On Great Peoples : Number of turns, on standard speed for the GA of the Great Artist, and the number of turn used to compute the value of the Great Writer, the Great Musician, the Great Scientist. Similarly, the formula for the production of Great Engineer, and the gold from the Great Merchant.
- On the Specialist and Great People page : put the augmentation of food cost before the augmentation of produced yields. A lot of people don't scroll to the end and miss this important information.
- On the Game Concepts / Cities panel : The initial yields of cities, depending of the land. 

**Other informations, easy to add**
- On the wonder home page : the fact that marble and stone boost them. (Already present on their ressource page)
- On the Game Concept / Diplomaty panel : a lot of things need declaration of friendship (such as trading cities). Adding thoses informations here would be a good idea.
- On the forest and jungle page, and the "Clearing land" page, the number of hammers obtained from clearing a forest or a jungle.

**Important informations, complex to add**
- Trade routes : what are used to compute their range (the fact that routes help them, ...)

**Other informations, complex to add**
- Diffilculty levels : what are exact bonuses (and what they mean)
- Religious pressure : how is it computed

I hope it will help.

**Comment by LoneGazebo** [comment]
Promotions issues are not valid, as whoward's viewer does not work properly for all trees.

**Comment by LoneGazebo** [comment]
The rest I will look at – I don't consider any to be 'high priority,' but once I get back into formatting I'll start on them.

**Comment by MoiMagnus** [comment]
No problem. Important was meaning "should be done before the final version of the mode", and Other was meaning "if you have time".
For the promotions, the part about the WHoward's tree was more a remark, I've not use it to make this post. The civiliopedia IS FALSE. For example, Wolpack II has no required promotion in the civilopedia (or at least, for me).

**Comment by LoneGazebo** [comment]
The civilopedia doesn't show prereqs for them because their XML format is different. I'll edit it. They do have them, though.

I've looked at your requests and implemented the ones that are feasible and/or (in my opinion) worthwhile. Thanks!
