### ISSUE TITLE
Hurricane Event Choice "send the military" has bugged result

### ISSUE THREAD

**Issue by kylorn** [LoneGazebo/Community-Patch-DLL#2183]
Bug Report Template

Mod Version : 7/15

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk):
Wrong event results for Hurricane - City gains 4 pops rather than loses them

3. Steps to reproduce: 
Hurricane event happens. Choose "send the military to protect property"

4. Additional information:

Civ was Spain with Ancestor Worship, Way of Transcendence, Cathedrals in case that matters.
City was Madrid, the Capital, but not Holy City.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Ha, oops, I know why. Silly me!
