### ISSUE TITLE
Multiplayer loading

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#2185]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
5/21 EUI

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
general bug

3. Steps to reproduce:
I attach logs from my game with friend, we stopped playing at turn 75 and loaded autosave, which skipped us to turn 76.

4. Additional information:
When loading game in multiplayer, one turn is skipped for players (yields, building queues etc. update, but players can't move their units). I know that it've been fixed for desynchs in multi, so I wonder if it could be fixed too?
This bug is game-breaking when loading in the middle of war.

---------------------------
Supporting information:

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/367813/Logs.zip)

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Does it do this for autosaves as well as normal saves? Autosaves are notoriously unreliable in MP. In any case, I don't see any changes in the code that could account for this, sorry.

**Comment by MoiMagnus** [comment]
I remember having this bug at the begining of the year.
I don't know if it was solved and it is a new one, or if it is the same.
If its still the same bug, it came from the "simultaneous turn" (Hybrid turns have the same problem). 
Sequential turns works well, but it is way longer to play.

**Comment by Finarvi** [comment]
Yes, we played on Hybrid turns. It seems that both: autosave and normal save skips one turn, but if you do whole turn and then load normal save then you don't loose anything because you'd skip turn anyway.

But it's still bad if you're forced to load autosave because it always skips whole turn (you didn't have time to do anything in turn).
