### ISSUE TITLE
notification text incorrect singular

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2186]
![image](https://cloud.githubusercontent.com/assets/1358966/16902473/eeb363d4-4c5f-11e6-80c9-07055f1492b0.png)

this error occurs for all empires which don't have a proper name (zulus, aztecs, ...)

in gametextinfos it says:

		<Row Tag="TXT_KEY_NOTIFICATION_SUMMARY_PLAYER_LOST_CAPITAL">
			<Text>{1_CivName:textkey} lost its [ICON_CAPITAL] Capital</Text>
		</Row>

but then there's also

		<Row Tag="TXT_KEY_NOTIFICATION_PLAYER_LOST_CAPITAL">
			<Text>{@1_CivName} {@1_CivName: plural 1?has; other?have;} lost {@1_CivName: plural 1?its; other?their;} [ICON_CAPITAL] Capital City! {2_NumPlayers} Civilizations remain in possession of their [ICON_CAPITAL] Capital.</Text>
		</Row>

so plural is supported. but maybe we should simply change the short description for all the affected civs, i.e. "shoshone empire" instead of "the shoshone"?

**Comment by LoneGazebo** [comment]
Isn't great, but it is also a bit minor, no?

**Comment by ilteroi** [comment]
finishing touch, i would call it :)

**Comment by LoneGazebo** [comment]
hehe. I'll  give it a look.

**Comment by LoneGazebo** [comment]
I'll just fix the plurality flipper
