### ISSUE TITLE
Trade Route Refresh

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2187]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/15

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk):   Bug

3. Steps to reproduce: When a new city is built, trade route doesn't always show up as "available". I save the game and re-load, and it shows up. This happened in 2 games already. It looks like the game is taking a shortcut by not re-evaluating trade possibilities unless user reloads up a saved game.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
@ilteroi we should refresh the cache when a trade unit is born.

**Comment by ilteroi** [comment]
is it possible you meant to say "when a city is founded"?

**Comment by oedali** [comment]
Yes that's what I meant. When a new city is founded, the trade route originating from it didn't show until did a re-load

**Comment by ilteroi** [comment]
i was talking to G, but anyway it should be fixed now

**Comment by LoneGazebo** [comment]
@ilteroi I was talking about unit init (as moving a trade unit, creating it, or ending a trade route 'inits' a new unit). Either way glad you fixed it.
