### ISSUE TITLE
Units Attack on Own

### ISSUE THREAD

**Issue by Zanteogo** [LoneGazebo/Community-Patch-DLL#2188]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
7/15

1. Mod List (if using standard CPP set, leave blank):
Red's Unit Mod
Red's Resource Mod

2. Type of error (i.e. crash, interface bug, AI quirk): 
Unit control

3. Steps to reproduce:
Move a unit beside a barbarian, press next turn. Sometimes unit will attack barbarian as if the AI has taken control. I believe it occurs when no new orders are given to unit. 

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by ilteroi** [comment]
savegame please

**Comment by GrantSP** [comment]
This may or may not be related but I have seen the combat resolution being resolved before the movement phase takes place. That's why scouts sometimes engage in combat instead of skirting around the barbarian camps.
Possibly the path-finding code sees all the possibilities but the combat resolution code kicks in before the final selection is made?

**Comment by pandasnail** [comment]
Made a save, included the Auto both before and after, tho I think you just want before. Watch the unit in the screenshot which I promise isn't told to attack, he's told to go to the tile to the right of the camp.

[AutoSave_0088 AD-0440.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/370207/AutoSave_0088.AD-0440.zip)

![barbhunt](https://cloud.githubusercontent.com/assets/16260521/16931685/2f703c3e-4d10-11e6-9870-77725e65b7a1.jpg)
