### ISSUE TITLE
Units bugs

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#219]
Another portion of bugs and balance suggestions:

- Naval units have really random moves range. For example Dromon is ranged and has 4 moves while Caravel is melee and have only 3 moves. It should be reversed (or at least aligned). From my standpoint:
Fix 1: Make ancient/classical/medieval melee naval units at about 4 moves and ranged at 3. Ranged ships have enough advantage and I don't see why they should be faster. By the way, melee units are usually "explorers" so more  should match their role well.
Fix 2: Make ancient/classical/medieval ships at same speed (3 or 4). I'd vote for 4 because naval units are faster than land as they don't need to rest.

- Siege units don't have "difficult target" promotion. I think that this promotion makes sense for ranged land units but this should include siege units too (at least before cannons).

- Explorer: has "Embarkation on ocean" promotion which doesn't make sense as it is unlocked in the same tech (sorry as it was mine thrown idea but I didn't know at which tech explorer will unlock). And it isn't written in unit's description but it is hidden in that promotion that this units gets +1 sight when embarked. I'd suggest to change "Embarkation on ocean" for "Embarkation with extra sight" to makes things clear.

- Zero: Zero doesn't require oil while any other (special or not) aircraft unit does.

**Comment by LoneGazebo** [comment]
I'll address these issues in the next version. Two points we'll need to discuss on civfanatics:

Siege units do not have 'difficult target' promotion because it gives the player an anti-ship defense from land.
The Zero is (by design) without an oil requirement.

G
