### ISSUE TITLE
System freeze issue has returned

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2190]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
July 15th

1. Mod List (if using standard CPP set, leave blank):
+FlagPromotions v7
+InfoAddict v22
+Leadership Reformation v4

2. Type of error (i.e. crash, interface bug, AI quirk): 
System becomes completely unresponsive, only by system restart can I regain control.

3. Steps to reproduce:
I see no significant events happening to trigger this. In fact after reloading an autosave I could get past the turn where it occurred the first time only to see it happen at another insignificant point.
Sometimes it is when I use the unitpanel to assign tasks or via hotkeys or even when I'm doing nothing and the game is processing the AI's turns.

4. Additional information:
Curiously, and this is only coincidental, the games are with France, as were the serious of crashes/freezes I had with the previous beta that I reported on.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Get rid of non-VP mods, try to reproduce.

**Comment by GrantSP** [comment]
Let's just leave this report open for a while and see if anyone else can add to it.
I've currently dropped that game and am trying another game as Japan.

**Comment by GrantSP** [comment]
#2204 appears to be another example of this.

**Comment by smokeeye** [comment]
After the latest update (7-15) it's happening with me as well. Never before, only just now.

Full CBP inc EUI + QuickTurns and R.E.D (smaller soldiers). As I've always run on previous installs.

**Comment by GrantSP** [comment]
Just experienced my first freeze with a game that wasn't France.
My system is Win10 64bit with an HDMI monitor driven by an AMD Radeon R9 390 series 8GB VRAM using the 16.150.2211.0 version of the driver.

**Comment by tu-79** [comment]
Definitely the same issue I had with Rome. I have Flagpromotions too, but I didn't remember cause it doesn't show in the Mod loading screen.
Would you say you have lots of units set to automated? Was your empire big?

**Comment by smokeeye** [comment]
In my experiences I've only had one unit on automatic (explore). Mostly a scout, but I remember one time with an quingereme as well. After I stopped using any auto function at all I've yet to experience this freeze bug.

**Comment by domeplsffs** [comment]
Bug Report Template

Mod Version:
**July 15th**

Mod List (if using standard CPP set, leave blank):

**as it comes with the auto-installer**

Type of error (i.e. crash, interface bug, AI quirk): 

**System becomes completely unresponsive. Happens allways at the Barbarians AI turn.** 

Steps to reproduce:

**reloading save and playing a few turns**

Additional information:

**Comment by ilteroi** [comment]
@domeplsffs : can you please attach your savefile?

**Comment by ilteroi** [comment]
ah - where exactly did you add it? i cannot find the link ...

**Comment by LoneGazebo** [comment]
Maybe he means on civfanatics?

**Comment by ilteroi** [comment]
just reproduced it ... we had a similar issue before, deadlock between GUI pathfinding and AI pathfinding. at least that's the deadlock i'm seeing.

**Comment by domeplsffs** [comment]
Erm, i tried to upload into my post (trying again with this one - seems it doesn't work ) 
Zip-File uploadet : 
http://www.file-upload.net/download-11794660/Bismarck_0043BC-2280.rar.html

**Comment by tu-79** [comment]
It also allows txt. You can add a txt extension to the filename and we can remove it to be able to read the file.
