### ISSUE TITLE
Monopolies window

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2191]
Mod Version (i.e Date - (4/23b)): 7-15 EUI

1. Mod List (if using standard CPP set, leave blank):

FlagPromotions(v.7)

2. Type of error (i.e. crash, interface bug, AI quirk): 
 
 Bug

3. Steps to reproduce:

Monopoly window seems to have gotten bugged in recent versions. 
"Strategic" and "All" are the same window (I presume Strategic applies to Strategic resources only, why do we see all resources there?)
"Potential" are all 0%
 Paper also listed as resource (which is not intended I presume)
 Difficult to find out whether you have a monopoly in effect and if not how many more % do you need.

![20160718204915_1](https://cloud.githubusercontent.com/assets/16341598/16924754/809ecb84-4d29-11e6-897c-8c5bad66c91a.jpg)
![20160718204646_1](https://cloud.githubusercontent.com/assets/16341598/16924756/82772758-4d29-11e6-904e-ecb49d85887b.jpg)
![20160718203602_1](https://cloud.githubusercontent.com/assets/16341598/16924757/83429d66-4d29-11e6-93c4-d471078b90d5.jpg)

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/369788/QuickSave.zip)

**Comment by LoneGazebo** [comment]
@mwhiter, care to give it a look-see?
