### ISSUE TITLE
Can't move directly onto tile with neutral citizen unit

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2192]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/15

1. Mod List (if using standard CPP set, leave blank): EUI version

2. Type of error (i.e. crash, interface bug, AI quirk):  If a tile has a neutral citizen unit I can't move onto either with the right click or thru the move mode. Nothing happens after hitting no on the 'does this mean war' popup. If I tell the unit to move to a tile where it happens to end its turn on the tile with the citizen unit, that works, but that's not always possible or desirable. Save included. 

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed [Casimir III_0047 BC-1180.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/370216/Casimir.III_0047.BC-1180.zip)
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![neut1](https://cloud.githubusercontent.com/assets/16260521/16931799/d722e62a-4d10-11e6-9796-1dbacabdd7b4.jpg)
![neut2](https://cloud.githubusercontent.com/assets/16260521/16931803/de423622-4d10-11e6-868e-1fe69aa0a909.jpg)

**Comment by Oscar-IronTower** [comment]
I can confirm this as well.

**Comment by ilteroi** [comment]
tricky but should be fixed - when moving onto civilians an explicit declaration of war is now required (no more popup)

**Comment by LoneGazebo** [comment]
@ilteroi makes sense - that's the way we had it at one point, but pathfinder changes may have altered/reverted it.
