### ISSUE TITLE
Religious pressure not displaying in trade routes

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2194]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/15

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Interface bug

3. Steps to reproduce: I have multiple trade routes almost all of which has some religious pressure going back & forth (I am sure - I noted multiple times when I set the route). But the religious pressure is not displaying on the trade screen. Screenshot attached. 

![20160718212253_1](https://cloud.githubusercontent.com/assets/20485377/16935535/442962ea-4d2e-11e6-8025-59dbd626da69.jpg)

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
@ilteroi, is this possibly affected by caching at some point? Pretty sure we never touched this code, however.

**Comment by ilteroi** [comment]
not necessarily an error - depends on the location of the target city whether any pressure is added. meaning if it's close enough that it already has the full pressure "naturally" then the TR won't add anything. so in case you built a harbor or a road, there might have been initial added pressure but it's no longer there.

**Comment by oedali** [comment]
Fairly certain it's a display big because the pressure showed right before I sent the route (on the route options screen), but not AFTER I sent it (on current trades screen)

Looks like you fixed it for upcoming version? Thx

On Jul 19, 2016, at 9:03 AM, ilteroi <notifications@github.com> wrote:

not necessarily an error - depends on the location of the target city whether any pressure is added. meaning if it's close enough that it already has the full pressure "naturally" then the TR won't add anything. so in case you built a harbor or a road, there might have been initial added pressure but it's no longer there.
