### ISSUE TITLE
Too many decimals next to yields - consider rounding up?

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2195]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/15

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Interface crowding

3. Steps to reproduce: Too many decimals showing next to yields on city screen. Do I really need to know that my public school is producing 10.0625 science per turn? If it were up to me, I am content rounding everything up to the integer (no decimals at all) Screenshot attached. 
![20160718200931_1](https://cloud.githubusercontent.com/assets/20485377/16935594/b62e7344-4d2e-11e6-9c64-b83c1de7e6a2.jpg)

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Eh, that's an EUI thing, not my domain. Besides, people would complain about the obscurity if I rounded stuff too hard.
