### ISSUE TITLE
Some Bad Events Still Triggering With No Bad Events On

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#2196]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

7-15

1. Mod List (if using standard CPP set, leave blank):

Vox Populi Complete with EUI
+
(7) Community Events (v 1)
Leadership Reformation (v 4)
Faster Aircraft Animations Version 3
Global - City State Airbases Version 3
Global - Commander Influence Borders Version 1
InfoAddict Version 22
Quick Turns Version 10
Really Advanced Setup Version 15
Religion - Fixed Prophets Version 2
UI - Enhanced Demographics Version 6
UI - Summary Antiquities Version 2
UI - Summary Luxuries Version 13
UI - Summary Specialists Version 11
UI - Trade Opportunities Version 28

2. Type of error (i.e. crash, interface bug, AI quirk): 

Minor Issue

3. Steps to reproduce:

These events happened when the "No Bad Events" option was set:

- Hurricane Approaches
- Forest Fire
- Floods

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by TechpriestEnginseer** [comment]
I'd like to note that my Community Patch Events aren't set to the proper event types yet, but you seem to have no concerns over it. (Barbarian Raid, Fire! Fire!, Jungle Fever is supposed to be considered "bad" event types).

**Comment by Oscar-IronTower** [comment]
Yeah, I realized that so I didn't include them in the report =)
