### ISSUE TITLE
assyria loving siege towers a bit too much

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2197]
![image](https://cloud.githubusercontent.com/assets/1358966/16950344/2301798a-4dc0-11e6-8b2c-b7ed63874ba0.png)

everybody else has 3 cities, assyria has 1 plus 2 siege towers ... and they might even have disbanded their worker. they are finally building a settler but they are already boxed in.

**Comment by Iamblichos** [comment]
Yep this is why I set them to 1 instance per city owned. Perhaps you could add to the CP:

See 'UnitInstancePerCity' in the DLL. I previously had made a sanity check in DLL that does the same thing, but using the former makes it impossible to do more.

**Comment by LoneGazebo** [comment]
Doesn't make much sense - there's a specific control to prevent the AI from building them if they don't have siege towers.

**Comment by ilteroi** [comment]
apparently that didn't work then ...

**Comment by ilteroi** [comment]
couldn't reproduce this by the way - which doesn't solve the mystery but maybe it's not so big an issue then

**Comment by LoneGazebo** [comment]
Not sure. I'll keep an eye on it.
