### ISSUE TITLE
Stuck AI worker

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2198]
Mod Version (i.e Date - (4/23b)): 7-15 full with EUI

1. Mod List (if using standard CPP set, leave blank):

FlagPromotions v.7

2. Type of error (i.e. crash, interface bug, AI quirk): 

AI quirk

3. Steps to reproduce:

In my savegame a Greek worker is standing inside of my Citadel for many turns. The main downside to it is that I'm unable to enter the Citadel with my military unit.
![20160719191038_1](https://cloud.githubusercontent.com/assets/16341598/16957415/ece803b2-4de4-11e6-8a3c-3beff7c3258a.jpg)
![20160719191022_1](https://cloud.githubusercontent.com/assets/16341598/16957419/ee47c63e-4de4-11e6-9d83-f9c5a9cd07c8.jpg)
[Stuck worker.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/371899/Stuck.worker.zip)

**Comment by saamohod** [comment]
Same here. Korean worker has been sitting in my city for several turns preventing me from putting my military unit in this city.
 Savegame attached.
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/372404/QuickSave.zip)


![20160719233024_1](https://cloud.githubusercontent.com/assets/16341598/16965487/02e6abb8-4e09-11e6-8c2b-74f7507bdcb3.jpg)

**Comment by ilteroi** [comment]
are they at war? they are probably hiding from enemies, or did at one point and now they aren't needed anywhere else. no real harm in that.

the problem with the blocked tile is solved.

**Comment by LoneGazebo** [comment]
@ilteroi we can probably safely disband a worker in foreign land that is unused.

**Comment by saamohod** [comment]
I'd like to add that in the second case it's not a worker but an archaeologist.
