### ISSUE TITLE
Event requests/questions

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#2199]
1) We have the table Building_ScienceFromYield
Does there exist/Is it possible to get, Building_YieldFromYield, where I can turn, say, culture into gold

2) I was going to make some positive & negative one shot events for camps, in the same way as we have for lumbermills and plantations and so on. If you were going to do that already let me know.

3 ) I'd like to make an EventChoice last forever. At the moment I'm just going to set it to 9999 turns. Is there a way of setting it be permanent, by entering -1 or something like that?

Should have lots and lots of events ready by the end of the week. Hopefully. Best regardz

**Comment by LoneGazebo** [comment]
1. Not possible - I tried, but the spaghetti code made recursion extremely hard to avoid. Sorry. :(
2. Go for it!
3. -1 or 0 = forever - has to be above 0 for it to register. Make sure to set OneShot to true for the choice so it doesn't fire again.

Awesome re: more events!

**Comment by Hokath** [comment]
ty for swift response

**Comment by LoneGazebo** [comment]
Yep!
