### ISSUE TITLE
How is Poverty Unhappiness Calculated?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2201]
I wish to do a system where each citizen yields out +1 gold, but I don't want to disrupt the poverty system. So, how much unhappiness modifier do I need to increase to make sure the poverty system is similar to one where citizens don't yield out +1 gold?

**Comment by LoneGazebo** [comment]
Well if all citizens generate +1 Gold, the global median will rise, so it should self-regulate.

**Comment by TechpriestEnginseer** [comment]
Fair enough.
