### ISSUE TITLE
Flanking bonus against embarked units

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2202]
Mod Version (i.e Date - (4/23b)): 7-15 full EUI

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

Bug (?)

3. Steps to reproduce:

 Inspired by this thread http://forums.civfanatics.com/showthread.php?p=14361312
 There is **no** flanking bonus when attacking embarked units with ships. It may be intended but I report it just in case.

**Comment by LoneGazebo** [comment]
Intended. Flanks only for land.
