### ISSUE TITLE
Some Pantheons (feature related) don't work

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2203]
Mod Version (15 july)

Standard CPP Vox Populi pretty much. (Did some tiny changes though like Aztec FG to 1 f/p for 3 pop from 2 pop etc)

Pantheons don't give their yields if linked to features that are not upgraded such as Atolls for God of the Sea, Lakes for God of Purity etc.

To reproduce
Pick God of Sea with atolls, or God of Purity with Lakes/Oasis. No bonus yields (unless it actually works for you and the mod installer did something wrong with my install).

(Also is Spirit of God of Desert supposed to not give its yields to Oasis? Because it doesn't and I think it used to. This might be broken too.)

**Comment by LoneGazebo** [comment]
God of Desert does not apply to Oasis, never did.
