### ISSUE TITLE
Pincer (naval melee unit promotion) does nothing because naval flanking doesn't exist (at least vs embarked units)

### ISSUE THREAD

**Issue by wobuffet** [LoneGazebo/Community-Patch-DLL#2209]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
07/07

1. Mod List (if using standard CPP set, leave blank):
()

2. Type of error (i.e. crash, interface bug, AI quirk): 
Pincer (naval melee promotion):  +50% bonus to Flank Attack Combat Strength bonus
Because naval melee units get no flank bonuses ever, this doesn't do anything.

Are naval flanking bonuses on the table? It would mostly help the AI, I think (AI is good at flanking and often has tons of units), plus it would make naval melee more useful in general. 
Thread discussing this and related issues here: http://forums.civfanatics.com/showthread.php?p=14365110

**Comment by LoneGazebo** [comment]
@ilteroi, mind looking at enabling flanking in naval?

**Comment by wobuffet** [comment]
@saamohod says here that flanking does exist when fighting naval units, but not embarked ones. To clarify, would it be possible to enable flanking bonuses against embarked units?
forums.civfanatics.com/showthread.php?p=14365426#26

**Comment by ilteroi** [comment]
yeah, should be working now ... but what's calculated and what's shown in the GUI are two different things unfortunately, so no guarantees on that.

anyway found another gem:

	// Boats do more damage VS one another
	if(pAttacker != NULL)
	{
		if(pAttacker->getDomainType() == DOMAIN_SEA && getDomainType() == DOMAIN_SEA)
		{
			iCombat *= /*40*/ GC.getNAVAL_COMBAT_DEFENDER_STRENGTH_MULTIPLIER();
			iCombat /= 100;
		}
	}

oh why?

**Comment by LoneGazebo** [comment]
That's a legacy of vanilla civ. I think it is set to 100 in defines  though.

**Comment by LoneGazebo** [comment]
@ilteroi I have a question: would it be possible to create an 'in-between' state for naval units that would allow them to move on ocean tiles, but not end their turns on them?

**Comment by ilteroi** [comment]
first of all, good idea, will sure help with the coastal traffic jams the AI is suffering from. but on the other hand, it will change the whole dynamic of the game (on certain mapscripts).

of course it's possible but it might be tricky with all sorts of unintended consequences. i'd rather not touch this whole passable/impassable thing again. right now there are only these two states.

but maybe i can hack it into the pathfinder though. i like challenges :)

**Comment by ilteroi** [comment]
seems to work ...

**Comment by wobuffet** [comment]
Hm, flanking with two naval melee ships definitely wasn't working against an embarked unit as of 07/07. I'll try again with the current version and post a screenshot if I can reproduce.

**Comment by LoneGazebo** [comment]
He's not talking about that wobuffet.
