### ISSUE TITLE
Ai Trade Logic

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#221]
Latest CP,
I offer Caesar Gems for Silver. He says no. I ask what does he want? He tells me that he would also like to give me 4 gold and open boarders as well. same issue as last version
However, overall the ai seems to have got a bit more sensible. wont give me silver for open borders and so on

**Comment by LoneGazebo** [comment]
this is normal. If the AI likes you, or the AI could benefit from this resource greatly (as with a WLTKD), they'll offer what they think is 'fair.' The AI won't usually swindle the player.

G

**Comment by Hokath** [comment]
oh really? because in vanilla I would offer less than what they wanted to get the positive diplomacy modifier. But I can't do this now? I don't know how I feel about this.

**Comment by LoneGazebo** [comment]
That modifier has largely been supplanted for use via trade routes. When you send a trade route to a civ, or vice-versa, you gain the 'we traded recently' bonus that you used to get through giving an AI more than the AI asked for.

**Comment by LoneGazebo** [comment]
I did this because it was, frankly, somewhat cheesy. If the AI gives a player more than the player wants, it didn't really change how the player felt about them, so why should the AI be any different?

**Comment by Hokath** [comment]
Yes that's probably better for gameplay
