### ISSUE TITLE
Theming bonus tooltip: explicitly state that "+4" means +4 Culture and Tourism? (feature request)

### ISSUE THREAD

**Issue by wobuffet** [LoneGazebo/Community-Patch-DLL#2210]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
07/07

1. Mod List (if using standard CPP set, leave blank):
()

2. Type of error (i.e. crash, interface bug, AI quirk): 
Seems odd to me (and confusing) that the tooltips for theming bonuses only specify the bonus yields (like Science and Gold) and don't explicitly state that the plain number ("+4") applies to both Culture and Tourism. (I feel this way about the tooltips both before and after theming has been accomplished.)

Current situation & suggestion (badly photoshopped) attached.
![20160719142126_1 - copy](https://cloud.githubusercontent.com/assets/19563806/17033846/e1c62efe-4f34-11e6-855d-d6c227dfad92.png)
![20160719142126_1 -2 copy](https://cloud.githubusercontent.com/assets/19563806/17033850/e5a6bd0e-4f34-11e6-9aec-613d7306fd46.png)

**Comment by LoneGazebo** [comment]
I'll look. No promises, as some of this stuff is hard to unhardcode.

**Comment by wobuffet** [comment]
Fair enough, thanks G!
