### ISSUE TITLE
Agribusiness: +15% Growth or Food?

### ISSUE THREAD

**Issue by wobuffet** [LoneGazebo/Community-Patch-DLL#2211]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
07/07

1. Mod List (if using standard CPP set, leave blank):
()

2. Type of error (i.e. crash, interface bug, AI quirk): 
Tooltip/description for Agribusiness says +15% Food, which suggests to me total Food before any is consumed by Citizens.
Actual behavior seems to be +15% Growth, which is obviously considerably weaker.

![20160721102708_1](https://cloud.githubusercontent.com/assets/19563806/17033940/5b0e1ca4-4f35-11e6-838b-7fa79973d87f.jpg)
![20160721112238_1](https://cloud.githubusercontent.com/assets/19563806/17033959/71269868-4f35-11e6-84c3-ec63b561c235.jpg)

**Comment by LoneGazebo** [comment]
It is flat food, but the modifier shows up in an odd spot (blame EUI).

**Comment by wobuffet** [comment]
Huh. You're right, of course; I should've done the math myself before submitting.
