### ISSUE TITLE
CTD after last Roman city is conquered by another civ, during the turns cycle 

### ISSUE THREAD

**Issue by mangust24** [LoneGazebo/Community-Patch-DLL#2212]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
7-15 beta

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
crash to desktop

3. Steps to reproduce:
after pressing end turn button, turn cycle begins. When it gets to Rome, the game crashes.

4. Additional information:

1. complete kills were enabled during advanced game setup 
2.Last roman city Ravenna was captured by Askia before I pressed end turn button
[files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/377205/files.zip)

 
---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump
[files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/377207/files.zip)

 file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by ilteroi** [comment]
cannot load the file. unfortunately it crashes on load, which is strange. usually 7-15 work for me ...
