### ISSUE TITLE
[Suggestion] Road from A to B, not a railroad

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2213]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

A very useful feature I miss from Civ4. I wonder would it be possible, and if yes, would it be easy to implement.
In Civ5 from the moment railroads are available I no longer can order a worker to build regular road from A to B. Only one button to build railroad to a certain tile. One can build regular road tile-by-tile, but obviously it's a pain is the arse.
Is it possible to introduce one more button to workers orders list so that we could have both "build road to..." as well as "build railroad to..."?
The reason for this is because often you need a minor city only connected but don't wanna to pay railroad maintenance.

**Comment by LoneGazebo** [comment]
There's no UI interface modeling for this, unfortunately.
