### ISSUE TITLE
No events in game

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#2215]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
7/15

1. Mod List (if using standard CPP set, leave blank):
I know...
(1) Community Patch\
(2) Community Balance Overhaul\
(3) CSD for CBP\
(4) Civ IV Diplomatic Features\
(5) More Luxuries\
(6a) Community Balance Overhaul - Compatibility Files (EUI)\
Calypso's Colored Religious Icons (Basic) (v 4)\
CivWillard for BNW (v 2)\
CPP CivPack (v 22)\
CPP TweakPack (v 39)\
CPP WondersPack (v 19)\
Cultural Capitals (Brave New World Edition) (v 16_5)\
FlagPromotions (v 7)\
Global - City Working Distance (v 7)\
Global - Civilians Move After Purchase (v 2)\
Global - Espionage Mapping (v 7)\
Global - Fortify Almost Healed (v 1)\
Global - Local Generals (v 2)\
Global - Pro-rata Buildings Purchase (v 2)\
InfoAddict (v 22)\
Ingame Editor (v 39)\
JFD's Cultural Diversity (Core) (v 9)\
JFD's Rise to Power - EUI Compatibility Files (v 24)\
JFD's Rise to Power (v 25)\
LiveTuner - Unit Panel (v 4)\
LiveTuner_-_Tech_and_Policy_Panels_(v_13)\
R.E.D. Modpack (v 27)\
Religion - Recurring Purchase Notify (v 1)\
TerrainMod (v 6)\
UI - Gold Alerts (v 10)\
UI - Overlay Barbarians (v 8)\
UI - Promotion Tree (v 15)\
UI - Summary Specialists (v 11)\
UI - Trade Opportunities (v 28)\
UI - Unit List Enhancements (v 11)\
Units - Visible Trade Units (v 1)\
Wonder Race (v 3)\

2. Type of error (i.e. crash, interface bug, AI quirk): 
In the last couple of games (using version 7/15 and 7/7, possible 6/30) I haven't seen ANY events at all. I suppose its a mod conflict, possibly something to to with CPP and JFD's mods. Haven't gotten anywhere on the forums, but maybe I just haven't seen the right post yet.

Do you know what's going on?

3. Steps to reproduce:
-

4. Additional information:
Log files attached

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/378221/Logs.zip)

**Comment by LoneGazebo** [comment]
You enabled them in the options, yes?

**Comment by skodkim** [comment]
Aren't they enabled by default? If so, yes.

On 22. juli 2016 20.24.44 CEST, LoneGazebo <notifications@github.com> wrote:
>You enabled them in the options, yes?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LoneGazebo/Community-Patch-DLL/issues/2215#issuecomment-234619189

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by LoneGazebo** [comment]
Check your game options.

**Comment by skodkim** [comment]
Just checked the Db and GAMEOPTION_EVENTS has values 1,1,1,1.

You can't change it in the options sql file, right?

**Comment by LoneGazebo** [comment]
No, you cannot. You can test using the firetuner if you want, though. Try the latest version and see if it works. If it doesn't, re-open the mod.

**Comment by skodkim** [comment]
Any hint as to how I test using the fire tuner?

On 28. juli 2016 08.32.19 CEST, LoneGazebo <notifications@github.com> wrote:
>No, you cannot. You can test using the firetuner if you want, though.
>Try the latest version and see if it works. If it doesn't, re-open the
>mod.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LoneGazebo/Community-Patch-DLL/issues/2215#issuecomment-235810873

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by LoneGazebo** [comment]
Players[0]:DoStartEvent(1);

Make sure firetuner is set to InGame at top left. Type this into bar at bottom. Should create an event.

**Comment by skodkim** [comment]
It works when I use the Fire tuer - so far so good - funny thing is that one of the mods I use seem to remove "InGame" from the Lua console though (but stlll it works...). In stead I have a couple of states called something like "c:\Users\PC\Documents\..." and "246". Do you think this could be related?

I've excluded a couple of them but there's still some digging to do if I wan't to narrow it down.

**Comment by LoneGazebo** [comment]
That is odd, but it shouldn't matter. If they're firing that way, shouldn't prevent it all from working.

**Comment by skodkim** [comment]
Just thought I'd let you know that events work with version 7-27 and same setup as before.

Once again thanks for the help!

\Skodkim

On 29. juli 2016 17.01.15 CEST, LoneGazebo <notifications@github.com> wrote:
>That is odd, but it shouldn't matter. If they're firing that way,
>shouldn't prevent it all from working.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/LoneGazebo/Community-Patch-DLL/issues/2215#issuecomment-236204384

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
