### ISSUE TITLE
Save/Load issue

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#2217]
@ilteroi ,

I'm at a loss on this one. It seems that autosaves 'play' a turn of the human player's game, such that an auto save on turn 0 will actually start on turn 1 (turn 0 being auto-played for the human). What gives?

**Comment by LoneGazebo** [comment]
@ilteroi another oddity: it seems that the

for(pLoopUnit = m_pPlayer->firstUnit(&iLoop); pLoopUnit != NULL; pLoopUnit = m_pPlayer->nextUnit(&iLoop))

loop doesn't actually look at all units owned by a player. It seems to skip about 1/2 of all owned units, give or take. Any idea why?

**Comment by LoneGazebo** [comment]
Something wrong with the first unit/next unit logic?

**Comment by ilteroi** [comment]
@autosaves: it has been like that for ages, my theory is that the save is generated at the end of the turn. so when you open it, you start playing the turn after. but nothing is really skipped. it least i never noticed.

@unit iteration: that's highly unlikely ...

**Comment by LoneGazebo** [comment]
@ilteroi something is up with it. A function that loops through and kills all contract units only kills half of them every time  I run the loop. Is the kill function putting holes in the list?

**Comment by LoneGazebo** [comment]
Ccontracts are for JFD

**Comment by LoneGazebo** [comment]
Alright, so testing.

	if(eContract == NO_CONTRACT)
		return;

	CvUnit* pLoopUnit;
	int iLoop = 0;

	int iNumContractUnits = 0;
	for(pLoopUnit = m_pPlayer->firstUnit(&iLoop); pLoopUnit != NULL; pLoopUnit = m_pPlayer->nextUnit(&iLoop))
	{
		if(pLoopUnit != NULL && pLoopUnit->getContract() == eContract)
		{
			iNumContractUnits++;
		}
	}
	if(iNumContractUnits > 0)
	{
		for(pLoopUnit = m_pPlayer->firstUnit(&iLoop); pLoopUnit != NULL; pLoopUnit = m_pPlayer->nextUnit(&iLoop))
		{
			if(pLoopUnit != NULL && pLoopUnit->getContract() == eContract)
			{
				pLoopUnit->kill(false);
			}
		}
	}
}

The first loop (just for debug) finds all 3 contract units on the map. The second function, however, only kills two of them. Any ideas?

G

**Comment by LoneGazebo** [comment]
Blegh, setting kill to delay solves it. Closing issue. :)

**Comment by LoneGazebo** [comment]
@ilteroi, I found this in the game kstream:

`// Get the active player information from the initialization structure
	if(!isGameMultiPlayer())
	{
		for(iI = 0; iI < MAX_CIV_PLAYERS; iI++)
		{
			if(GET_PLAYER((PlayerTypes)iI).isHuman())
			{
				setActivePlayer((PlayerTypes)iI);
				break;
			}
		}
		Localization::String localizedText = Localization::Lookup("TXT_KEY_MISC_RELOAD");
		localizedText << m_iNumSessions;
		addReplayMessage(REPLAY_MESSAGE_MAJOR_EVENT, getActivePlayer(), localizedText.toUTF8());
	}`

Also, just below it:
`//when loading from file, we need to reset m_lastTurnAICivsProcessed 
	//so that updateMoves() can turn active players after loading an autosave in simultaneous turns multiplayer.
	m_lastTurnAICivsProcessed = -1;`

I can't confirm it, but I imagine these two elements are responsible for the oddities with regards to autosaves skipping a player's turn in things like hotseat.
