### ISSUE TITLE
Rhiannon, the Celtic pantheon

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#2218]
Mod Version (i.e Date - (4/23b)): 7/15

1. Mod List (if using standard CPP set, leave blank):

VP+EUI with some mostly cosmetic mods

2. Type of error (i.e. crash, interface bug, AI quirk): 

The Rhiannon pantheon is supposed to provide + 2 gold, GAP and science for every owned city. That part is functioning well, as far as I know. However, there's another hidden part that copies God of All Creation's functionality - it also provides +2 of said yields for every founded pantheon.

By the way, the pantheon's description says '[+ yields] in every City', which is slightly misleading. The yields never show up in every city since they are all streamed into the capital. If that's the only possible way to do it, then I'd suggest changing the 'in every City' part in the description to 'for every owned City'.

**Comment by LoneGazebo** [comment]
I'm going to make it work like the 'culture per city' policy function, rather than pooling in capital.

**Comment by Edaka** [comment]
Awesome!
