### ISSUE TITLE
Not being able to dig up artefacts in other civs territory

### ISSUE THREAD

**Issue by dennisdahlc** [LoneGazebo/Community-Patch-DLL#2219]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

7/7

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

When I tried to send archaeologists to the territory of my neighbouring civs, I could not dig up normal artefacts at all. I could dig up hidden sites, but only inside the territory of civs which could not have dug them up themselves.

3. Steps to reproduce:

I had complete the aesthetics tree and researched archaeology. I send arches to other civs antique sites and the button for digging up did not appear. I then sent them to the hidden sites which was fine, unless I send them to a civ which could also dig them up.

I have attached a save where an archaeologist is located on top of a hidden sites inside Russian lands and he is not able dig up here.

[Egypt not able to dig up artefac.pdf](https://github.com/LoneGazebo/Community-Patch-DLL/files/380226/Egypt.not.able.to.dig.up.artefac.pdf)
 

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by oedali** [comment]
I see this is closed but the same thing just happened to me now. In other's civ's territory w/ open borders. Dig up artifact option does not come up. See screenshot
![20160807215830_1](https://cloud.githubusercontent.com/assets/20485377/17467247/2defad42-5cea-11e6-8d51-aeda08b68220.jpg)
