### ISSUE TITLE
Council of Elders stopped giving science

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2220]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/15

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk):  Bug

3. Steps to reproduce: In my current game I have the Council of Elders belief and it was working fine for a while. Not sure about the exact trigger but around Renaissance era / after adopting a reformation belief, it stopped giving me the science boost in the capital when I convert other cities. (AI or city states) 

EDIT: New find - it actually WORKS if I convert a city that has had no previous religion before. But it doesn't work if I convert a city to my religion from another religion. (even when I do it for the first time) 

4. Additional information: I can attach save games if it helps. Let me know what I can provide

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Will this was a dumb one. Seems Firaxis didn't account for multiple religions having adoption bonuses, Silly Firaxis.

**Comment by oedali** [comment]
I noticed the same bug currently happens with Tithe too - if city had previous religion, doesn't give the 200 gold. Will your fix address this as well?

**Comment by LoneGazebo** [comment]
Yes.

**Comment by LoneGazebo** [comment]
This is a vanilla bug that was uncovered by my rationalization of belief logic.
