### ISSUE TITLE
Event request

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#2223]
So I want to be able to have a player event reduce/increase the population in every city, but currently if I put Yield_population through EventCostYield or InstantYield then it only triggers in the capital. Is it currently possible/could it be possible to have one that affects all Cities? I've gone and written it into a whole set of events now :(

**Comment by LoneGazebo** [comment]
Yeah I'll look at it

**Comment by LoneGazebo** [comment]
There will be a new event choice bool to set true to make an instant yield affect all cities.

**Comment by Hokath** [comment]
nice!
