### ISSUE TITLE
out of memory crash

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2224]
maybe we have a memory leak somewhere ... i had several late game crashes (after autoplay)

one that i caught in the debugger, sure looks like an out of memory situation:

![image](https://cloud.githubusercontent.com/assets/1358966/17114022/70ab62b2-52ad-11e6-8750-9744bee5405d.png)

civ5.exe had a memory allocation of 2340 MB - admittedly on debug, but then it was a standard size map. this might explain some crash reports ...

**Comment by LoneGazebo** [comment]
Hmm...that's not good. Best bet would be the larger vectors (m_ppai etc.) that have built-in 'out of memory' functional checks during reset/uninit. Also we should look at corporation code, make sure it isn't  leaking somewhere.

**Comment by LoneGazebo** [comment]
I've checked CP-added functions many times, but might not hurt for us to go through them again.

I haven't been able to reproduce odd CoM quirk (yay?) but I have noticed that embarked units at sea have a default homeland AI movement of 'upgrade unit' - seems odd no?

**Comment by ilteroi** [comment]
re: com - i guess that's good ...

re: leak - need some tool support here, i tried that a while ago but it was difficult

**Comment by LoneGazebo** [comment]
https://msdn.microsoft.com/en-us/library/windows/hardware/ff560206(v=vs.85).aspx

**Comment by LoneGazebo** [comment]
I'm trying out Visual Leak Detector. Will let you know what I find. :dancer:

**Comment by LoneGazebo** [comment]
For what it is worth, my copy of civ is running at 1016mb, not 2340mb. Standard map.

**Comment by biship** [comment]
580MB, 2024AD, I have 40+ mods. Small Map.
