### ISSUE TITLE
Player event notifications

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#2225]
I remain convinced that player event notifications dont work from other players.
I see City notifications from other players fine on my events, but not Player ones.

If you have time, could you try to reproduce?

**Comment by LoneGazebo** [comment]
Keep in mind that the players must have met.

**Comment by LoneGazebo** [comment]
Send me the event you are working with and I will test it.

**Comment by Hokath** [comment]
[Austria.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/384403/Austria.zip)

**Comment by Hokath** [comment]
civ specific to austria

**Comment by LoneGazebo** [comment]
Got it, yep. Bool was being reset too early for event notifications that don't call on a playerID.

**Comment by Hokath** [comment]
Great, I wasn't crazy :D

**Comment by LoneGazebo** [comment]
Well, I can't verify that. :dancer:
