### ISSUE TITLE
Policy screen is not changed in different language(Traditional Chinese)

### ISSUE THREAD

**Issue by m9731526** [LoneGazebo/Community-Patch-DLL#2226]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
Lynnes' MP compatible Modpack 5/21 EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 
Interface bug

3. Steps to reproduce:
Any SP/MP game, Policy window

4. Additional information:
The policy window stay completely the same as original game, I'm playing in Traditional Chinese, I can understand you don't have Chinese localization support (maybe I can help with that if you want), but shouldn't it try to override the text with mod's text? Localization issue also occur to civilizations' feature.
I hope there's a way to eliminate the needs to switch out the game for CBP wikia... maybe add the information to in-game pedia?

**Comment by LoneGazebo** [comment]
It isn't ideal, however the only sure way to get proper info in-game is to play it in English. Hopefully mod language support will come soon enough (if you'd like to help, check out the civfanatics languages thread).

**Comment by m9731526** [comment]
So what about the Text/en-US folder? Will it work if I create a zh-TW?

**Comment by m9731526** [comment]
Alright, after many tests the method in the thread doesn't work.
I can understand that this may not be possible, but still want to figure it out.

Even if I replace all Language_en_US with other string like Language_zh_Hant_HK, nothing happens, the text still only shows up in English game.
I mean, why? these sql should be the only source of the updated in-game text, and if I change the language key, shouldn't it affect English game at least? It seems that the language key are doing nothing?

**Comment by LoneGazebo** [comment]
I'm honestly not sure. You should post in that threat, user Estebanium is pretty active and knows a lot more about language compatibility than I.

**Comment by m9731526** [comment]
Great, I've found out that the modpack use a override xml replace a lot of in-game text only to en_US, so that's why modifying sql doesn't work. I'll try to partially change the xml to correct policy tree.

**Comment by m9731526** [comment]
Nailed it!
I heard you are working on DLC version of a newer version of CBP?
This is how I fix the tech tree problem if you need it:
[Override/CIV5Unit_Mongol.xml](https://mega.nz/#!uZNXBaLT)

**Comment by m9731526** [comment]
But I failed to find any string of civilization feature description such as Bushido, do you have any idea?

**Comment by ErikSteiner** [comment]
I wrote you in the [[HowTo] Play the Game in a different language with CBP and CP ](http://forums.civfanatics.com/showthread.php?t=539883) thread. Please use this thread, because there is no issue with Vox Populi and so this issue can be closed.

**Comment by 8h42** [comment]
@m9731526

It is difficult to translate modpacks
I recommend you to translate the standard Vox Populi mods.

**Comment by m9731526** [comment]
I've already figured out why and partially fixed the modpack's translation issue, and shared it above.

The problems I currently have are 1) I can't find civilizations' feature text, so I can't correct that, 2) I am not sure is there any more text which is not match to mod content.

And yes the issue can be closed now, but I hope maybe someone knows something about civilizations' feature. I'll close it if no new reply in a day.
