### ISSUE TITLE
Hurricane Event Bug

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2228]
![after](https://cloud.githubusercontent.com/assets/20485377/17162458/4a7b9fda-5384-11e6-8d11-0a84c5237b00.jpg)
![before](https://cloud.githubusercontent.com/assets/20485377/17162457/4a7ab3cc-5384-11e6-9d52-e13f5a609860.jpg)

Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/15

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Bug

3. Steps to reproduce: There's something wrong with the hurricane event when it happens to the AI: instead of damaging their cities, their cities GROW exponentially overnight! It happened in one game and I dismissed it thinking my eyes were deceiving me... then it happened again in this game. I took a snapshot of the same city before and after the event, and it grew from pop 14 to pop 19 in one turn as a result of the event. See screenshots. 

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
This is a general bug with how I wrote that event - I've already fixed for next version.
