### ISSUE TITLE
[Question] Unique unit's promotion notifications visible through fog'o'war. 

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2229]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
July 15th

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Just noticed when moving a unit near the fog'o'war that one of those notices that rise up from the Kris unit appeared.
I'm also assuming this happens with a vanilla game.

**Is it something that may be looked at?**

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Siamese? You mean Indonesian?

**Comment by GrantSP** [comment]
Yeah. That's just my misfiring neurons. I'll change the title to more accurate.

**Comment by GrantSP** [comment]
I'm assuming it would also happen with the samurai.

**Comment by LoneGazebo** [comment]
Prolly, I'll loook.

**Comment by GrantSP** [comment]
I'm guessing it is such a random thing to encounter that it rarely, if ever shows up.
You need to have an opponent that has researched to the point of using those units, but still not to the point of Astronomy where the oceans are no longer a problem AND happen to be sailing a coast near enough to one of them at the same time that it has just fought AND gained experience enough for it to trigger.

So in the scheme of things, very very low on priority.
Just thought I'd ask.
