### ISSUE TITLE
Garrisoned unit's CS is not added to city's defence value.

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#223]

**Comment by LoneGazebo** [comment]
I'll look.

**Comment by qqqbbb** [comment]
see this post http://forums.civfanatics.com/showpost.php?p=13778459&postcount=1770

**Comment by LoneGazebo** [comment]
Yep. I left if that way and forgot to change it. I’ll fix for update tonight.
G
