### ISSUE TITLE
crash when discovering city states after finding map in ruins

### ISSUE THREAD

**Issue by EtherealBeaver** [LoneGazebo/Community-Patch-DLL#2230]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
1.7.15

1. Mod List (if using standard CPP set, leave blank):
nothing

2. Type of error (i.e. crash, interface bug, AI quirk): 
crash directly to desktop

3. Steps to reproduce:
move the scout left (so you find Sofia)

4. Additional information:
I found a Ruins which gave me the map of the surrounding area which revealed the two city states left of the scout. They weren´t discovered (so I didnt get the bonus for discovering city states) when I found the map, so I moved my scout towards them to get the bonuses. Then it crashed. It has crashed from this 4/4 times now.

quicksave file attatched here [crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/385933/crash.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by ilteroi** [comment]
works fine for me. no crash. but then there have been some changes in the code, maybe it's fixed already

**Comment by EtherealBeaver** [comment]
That is pretty wierd. I used to have some issues with my computer, but after a thorough cleansing and some new heat gel for the cpu, it is working like it should. Would it make sense to reinstall civ 5 again, keeping in mind that it is a week old install to begin with?

Also, I am trying to play without any mods at all, to see if it could be Civ itself, but thus far I am in a year 300AD rennisance and no problems what so ever has occured.

**Comment by ilteroi** [comment]
don't think that it was a temperature issue, being so reproducable for you. skip the re-install but do try the new 7/27 version!

anyway thanks for the good bug report, i was every one was like this.
