### ISSUE TITLE
AI city hitpoints

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2235]
i often see AI cities like this

![image](https://cloud.githubusercontent.com/assets/1358966/17203703/3989b18a-54a1-11e6-8b99-10faaea7bc94.png)

but there are no enemies around. where does this damage come from? always seems to be capital. is it some sort of event or a weird bug?

**Comment by LoneGazebo** [comment]
Spies probably. Or an event.

**Comment by ilteroi** [comment]
happens a lot ... but i guess that's ok then
