### ISSUE TITLE
Luxury’s added with "More Luxuries - CBO Edition  - 7/27 MP - Multiplayer with EUI

### ISSUE THREAD

**Issue by Reventus** [LoneGazebo/Community-Patch-DLL#2236]
Bug Report Template

Mod Version (i.e Date - (7/27)):

1. Type of error (i.e. crash, interface bug, AI quirk): 

I’m not able to build Improvement with Workers on the following Luxury resources.

Tea, olive, Jade, Coffee (Probably all Luxury’s added with "More Luxuries - CBO Edition “)

Great Person improvements are working and gives the Luxury.

Workers can only build roads on the Tiles.

2. Additional information:

 MP

**Comment by LoneGazebo** [comment]
Not sure. Id assume a bad install or a mod conflict.

**Comment by Reventus** [comment]
After a clean deinstall (complete Civ5).
No workshop mod active .
Only the MP-Patch unzipt.
I encounter the same bug.

**Comment by LoneGazebo** [comment]
Try the standard install instead of the modpack.

**Comment by Reventus** [comment]
Sorry there is a misunderstanding. I meant MP = Multiplayer :/ . 
So the standard install will not work.

**Comment by Josiah200** [comment]
Can confirm - Can't upgrade Indonesia's luxuries either.

**Comment by LoneGazebo** [comment]
Thanks for testing. I'll look into it. The modpack making program can be buggy.

**Comment by Reventus** [comment]
Update : 

The problems seems to occur  in the Modpack with EUI.

 The other version without EUI is working so far.

**Comment by LoneGazebo** [comment]
Ah, so it sounds like an EUI bug. Are you getting any lua errors with the EUI pack?

**Comment by joosegoose** [comment]
For what it's worth, I'm using a modpack with EUI and I'm able to improve the added luxuries just fine. The difference being it's a modpack I made myself...my guess is there's a bug with that specific modpack (bad compile?)

**Comment by Iamblichos** [comment]
Want me to start making the modpacks G? I do this all the time and I have no issues. (I only play with modpack).

**Comment by LoneGazebo** [comment]
@Iamblichos sure, that'd be swell

**Comment by Iamblichos** [comment]
I'll make one this afternoon for 7/30 hotfix

**Comment by LoneGazebo** [comment]
Hold off, I'm working on a release for today.
