### ISSUE TITLE
GetNumFriendlyUnitsOfType() issue

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2239]
I'm getting the 'attempt to call method 'GetNumFriendlyUnitsOfType' (a nil value)' error on the 27th July version of the CP. I have had this issue a while, and it seems to be a recurrant one that people have posted about on GitHub. Although those issues were closed, the issue itself doesn't appear to have been resolved. 

The issue seems to be a typo - the method is getNumFriendlyUnitsOfType() in the DLL. This is a problem where that method is used in its original spelling, with a capital 'G', such as in the UnitPanel.lua file. I can adjust this as I replace the UnitPanel myself, but it might be a problem for others if the typo is left as is.

**Comment by LoneGazebo** [comment]
I'll change it to the capital G - not sure why/when it was modified.
