### ISSUE TITLE
City attack (4-20)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#224]
An enemy city can bombard my unit several times in a row.
Active mods: CP(4-20), CBP(4-20), IGE.

This problem also occurs without CBP(4-20).
It seems that there is something wrong with CP(4-20).

**Comment by LoneGazebo** [comment]
Ilteroi made some changes to this code, I'll take a look.

**Comment by MasterOfMuffins** [comment]
This happens in all my games. Ive tried 3 different starts, though cities always seem to attack 4 times for me 

CP 			   4/20
CBP			   4/20
CSD			   4/15
C4DF		   4/15
EUI CBP 		   4/15
CBP CMod EU1V 4/20
More Luxuries
Events and Decisions	3/30
AntmanMike's LUAJIT

**Comment by MasterOfMuffins** [comment]
Update fixed this for me
