### ISSUE TITLE
FEFE Branch inconsistent with master.

### ISSUE THREAD

**Issue by biship** [LoneGazebo/Community-Patch-DLL#2240]
Branch fefe is very out of sync with master. Not only does this mean work in fefe is becoming invalid, it must suck for both you guys when merging changes. I know I am not responsible for either branch, but branch fefe should really be deleted and recreated. It thinks it is 254 changes ahead of master!

Take a look at fefes CvDealAI.cpp for example, this block of code is missing from master, yet it's not a new change:

	// Important: check invalid return value!
	if (iTotalValueToMe==INT_MAX || iTotalValueToMe==-INT_MAX)
		return false;

WinMerge shows ~20 other files in fefe that are not consistent with master. Some are merely formatting, some are uncommitted changes. This is just a suggestion to make merging easier, and it helps when we (or maybe just I) use fefe's branch for testing new changes.

**Comment by Iamblichos** [comment]
That bit of code from CvDealAI.cpp has been in both.  @ilteroi looks to have it twice. Once @ line 684 and again @ line 696. The other inconsistencies are either the top header line or that he has debugging turned on. I don't think this is an issue.

**Comment by biship** [comment]
It takes 2 mins to fix & this is the second time I've had to point out inconsistencies. Another time fefe was missing commits made to master months earlier. 254 changes ahead of master, when it is supposed to nearly identical to master, is not the right way to use github. Fixing this would make merging either direction much easier/cleaner for both branches.

**Comment by Iamblichos** [comment]
Well he gets 254 changes ahead of master because he makes his commits ahead of when Gazebo releases. Gazebo doesn't do his commits at once, he usually does a release and then updates the master. I really don't think its a big deal.

**Comment by biship** [comment]
Well it's up to Gazebo, however considering he doesn't use github like most developer's do, i suspect this issue will be closed and nothing resolved. Not that I really care, I just hate spending the time having to compare branches (and manually merging if necessary) because fefe isn't clean. I really just wanted to offer up advice, and point out the risks of the current situation.

**Comment by Iamblichos** [comment]
It can be a little frustrating I guess if your just looking for what files to merge. I've done this so many times that I know the CvDealAI.cpp has redundant code in FeFe and the rest is just having a "box" symbol or the proper copyright symbol in some of the top header files. If that's all, I don't think you have much of a case, but I guess you can see what they say here.

**Comment by LoneGazebo** [comment]
Fefe is an experimental build, essentially. It is fine that it exists in a quantum state of aheadbehind. Master is the only merged build, and I know what (of fefe) is experimental/wrong and what I want.

**Comment by LoneGazebo** [comment]
Latest master always includes relevant fefe changes.

**Comment by ilteroi** [comment]
it's a phantom problem because git doesn't know about G's manual merging. now i agree that it would make some things easier if we had a public merge history, but that's not my decision and it's not really that important.
