### ISSUE TITLE
CS worker issue

### ISSUE THREAD

**Issue by Txurce** [LoneGazebo/Community-Patch-DLL#2242]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/27

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): AI quirk -- Mombasa worker wanders around instead of working, and can't be captured, even after a DOW.

3. Steps to reproduce: 1) observe Mombasa worker; 2) DOW Mombasa, attempt to capture worker

4. Additional information: this is a hotseat game.

---------------------------
Supporting information: log files, minidump file, and .sav game attached
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/390656/CvMiniDump.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/390657/Lua.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/390658/Lua.zip)
[AutoSave_0045 BC-2200.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/390659/AutoSave_0045.BC-2200.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/390660/Database.zip)

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
@ilteroi, did your changes to 'warmove' for units make it impossible to capture CSs?

**Comment by ilteroi** [comment]
can't load the save (because of hotseat?)

anyway cannot reproduce. 

![image](https://cloud.githubusercontent.com/assets/1358966/17256114/65211402-55bc-11e6-9ef2-d81fdb50912f.png)

one worker is working and other one could be captured
