### ISSUE TITLE
Cannot found religion with increased max religion count

### ISSUE THREAD

**Issue by CharlesDR** [LoneGazebo/Community-Patch-DLL#2243]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
7/27/16

1. Mod List (if using standard CPP set, leave blank):
VP+EUI
YnAEMP
InfoAddict

2. Type of error (i.e. crash, interface bug, AI quirk): 
Mechanical/Logic Bug

3. Steps to reproduce:
- Increase max religion in world size file (I increased to 12 since YnAEMP is so huge)
- If AI founds enough religions, player cannot found new religion even if the max has not yet been hit, but the AI can.

4. Additional information:
- In my test, the AI had founded 9 religions, when the max was set to 12 and correctly displayed in game.
- I hit the faith required for a Great Prophet, the GP was properly given to me in my capital, but the Found Religion button/function was missing from the unit, so it was only able to create a Holy Site.

It seems like there's a limitation in the logic underlying the max religion mechanic that can't handle values over a certain threshold.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
There is - the number of founder beliefs in the game.

**Comment by CharlesDR** [comment]
@LoneGazebo, is that a dynamic value? If, for example, someone modded in more founder belief options, would that limit increase?

**Comment by LoneGazebo** [comment]
Yep!
