### ISSUE TITLE
Hanse (German UB) still has maintenance cost

### ISSUE THREAD

**Issue by kylorn** [LoneGazebo/Community-Patch-DLL#2244]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/27

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk):  inconsistency in buildings

3. Steps to reproduce:

Play as Germany or check Civilopedia

4. Additional information:

Probably forgot to adjust this UB when changing the Customs House in the most recent patch.

**Comment by LoneGazebo** [comment]
Yeup
