### ISSUE TITLE
Crossbowman weird promo option

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2246]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/27

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk):  Bug?

3. Steps to reproduce: My crossbowman has a "may not melee attack" promotion option w/ the fortress icon .. see screenshot

4. Additional information:
![crossbowman](https://cloud.githubusercontent.com/assets/20485377/17266116/b3b33b8a-55c2-11e6-819b-b6ef1123768a.jpg)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by GrantSP** [comment]
Same as #2238
