### ISSUE TITLE
Pikeman missing inherent "bonus vs mounted" promo

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2247]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/27

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Bug

3. Steps to reproduce: Pikeman doesn't already have the "bonus vs mounted" promo.. it came up as an option.
![pikeman](https://cloud.githubusercontent.com/assets/20485377/17266135/d2b9d840-55c2-11e6-8308-8707d305e98a.jpg)

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by GrantSP** [comment]
Probably related to #2238
