### ISSUE TITLE
Knight has defensive terrain bonus

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2248]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/27

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Bug

3. Steps to reproduce: Knight is missing the "no defensive terrain bonus" promo. It came up as an available promo to choose from, w/ the fort icon
![knight](https://cloud.githubusercontent.com/assets/20485377/17266282/528827d8-55c4-11e6-9697-0a1575ca3cc5.jpg)

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by GrantSP** [comment]
Probably related to #2238
