### ISSUE TITLE
Request for pUnit:IsWithinDistanceOfUnit() and pCity:IsWithinDistanceOfUnit()

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#225]
I would like to request two new boolean methods: pUnit:IsWithinDistanceOfUnit(bool, iUnitType, iDistance, bIsFriendly, bIsEnemy), to go along with the other IsWithinDistanceOfX methods. This would check if one unit is within X tiles of a specified unit type, with the option to check whether that unit belongs to the player or to a civ with whom the player is at war. The other would be the city equivalent: pCity:IsWithinDistanceOfUnit(bool, iUnitType, iDistance, bIsFriendly, bIsEnemy) (presumably a distance of 1 would want the unit to be in the city itself, which would be very useful as GetGarrisonedUnit() skips civilian units).

I'd like to start adding real support for CP to my civs, and these two methods would replace my prevalent method of using UnitSetXY and PlotIterators to check these things; hopefully improving stability and performance for my civs.

**Comment by LoneGazebo** [comment]
Sounds good. If you can, post an example of your lua here so I can make sure and get the syntax appropriate to your needs. I’ll see what I can do for the next iteration of the CP.
G
