### ISSUE TITLE
Trade system malfucntion after 100 turn occasionally

### ISSUE THREAD

**Issue by llamaark** [LoneGazebo/Community-Patch-DLL#2250]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7-27(latest)

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

  Trade system error with resource not returning to the pool

3. Steps to reproduce:

  Start with spain, everything is fine in the first hundred turns, after that resources sometimes gone missing. Checked the past trade deal in the diplomacy, the missing resources are within the failed trade deal. Normally when a trade is over, a closed trade deal showed when it's over, for instance horse trading deal with Carthage started in 77 turn ended in 127 turn, however the bugged deal would show like the deal started in -2 turn ended in -1 turn or something like that with a negative number. So the deal was never closed, the resources within the deal would never return to the pool.

  Replay another twice time, still the same thing, problems are mostly found after hundred turns, will this be any relation with new-added events? 

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Iamblichos** [comment]
Great. This thing is back again?
