### ISSUE TITLE
No City states added, however standard number is selected at setup

### ISSUE THREAD

**Issue by acsonka** [LoneGazebo/Community-Patch-DLL#2251]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

Used the vox populi 7-27 install on a fresh install of CIV5 (used with EUI enabled)

1. Mod List (if using standard CPP set, leave blank):

Standard modset with EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 

Could you please try to help me, I am unable to use the mods, and perhaps you already met this issue before.

City states are now spawning in the game, only the major civs, however at the game setup I have used the standard settings for the map (continents map) (16 city states for this game) also tried continents map large with 20 or 21 CS, and also archipelago with 20 CS, but non of the maps are spawning any CS for me. Also tried vanilla, but no issues there, in vanilla CS are spawning correctly.

3. Steps to reproduce:

Load the mods, setup a new game, select any CIV (for this particular I have tried russia, but also tried with others) use the standard settings and start the game. Found city at spot, reveal the map with the game console reveal all. No city states found.

4. Additional information:

I have attached a save game, could you please check the issue for me. I guess the issue

A/ shall be with my installation
B/ Somewhere the mod itself

Thanks a lot, Attila.
---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them.
[Catherine_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/391774/Catherine_0000.BC-4000.zip)

 If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by pandasnail** [comment]
From previous reports, it seems like this is an issue with not being on the latest version. Are you on .279?

**Comment by pandasnail** [comment]
Latest version of Civ 5 itself I mean, not VP.

**Comment by acsonka** [comment]
Hi pandasnail, Thanks for your quick comment. My version is 1.0.3.144. I suppose this means I need 1.0.3.279 ?! 
Attila.

**Comment by acsonka** [comment]
Hi again, Thanks a lot for your suggestion, I have installed 1.0.3.279 and I can confirm all is working fine, now CS are spawning on the map. All fine. Attila.
