### ISSUE TITLE
Defensive Pact overrules Peace Treaty

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2252]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/15 (the second most recent one, forget the exact day now)

1. Mod List (if using standard CPP set, leave blank):
Full VP
Enginseer's version of Events and Decisions and its add on
Enlightenment Era and Xony's Compat mod
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Ice Free Coasts
Celtic City Names, Iroquoian City Names, Randomize City Names
NoAltitudeTraining (removes the Mt. Kilman promo)
My own thing that does various things SQL type stuff
Tectonic Map

2. Type of error (i.e. crash, interface bug, AI quirk): Think this is supposed to go the other way, not sure tho. Anyway, Napoleon and USA made peace, two turns later Napoleon DoWed Arabia and USA entered thru the DP. Now it does say 'Napoleon DoWed USA when I thought DPs showed it the other way, but I'm taking that for an EUI strangeness.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![dppea1](https://cloud.githubusercontent.com/assets/16260521/17270385/6e643012-562f-11e6-86eb-8b7961c3281f.jpg)
![dppea2](https://cloud.githubusercontent.com/assets/16260521/17270386/70c15024-562f-11e6-945b-d6bb603efebe.jpg)

**Comment by LoneGazebo** [comment]
I think it is just EUI being odd.
