### ISSUE TITLE
scouting I and scouting II

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#2253]
These two promotions become available with the same prerequisites.
I assume either: scouting I is supposed to come as a tier 2 promo rather than tier 3
                        : or that scouting II is supposed to require scouting I, but right now it is an OR

**Comment by MoiMagnus** [comment]
Scouting II is supposed to require Scouting I

**Comment by GrantSP** [comment]
Do you have the July 30th Hotfix installed?

**Comment by XplosiveLun** [comment]
This bug still appears in the July 30th Hotfix

**Comment by dennisdahlc** [comment]
Yep. I can confirm that
