### ISSUE TITLE
Minor City-State Personality Question

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2257]
I know I can do an event where Lua can change the city-state's personality from friendly to anything, but how does it affect the game stability-wise? Does it start to change its quest or does it continue to give the same friendly quest rather than the irrationality it was changed to?

Also, we need an addition to GameEvent.EventChoiceActivated and GameEvent.CityEventChoiceActivated to have a boolean to see if the event was a failure or success.

**Comment by LoneGazebo** [comment]
CS Personality has little effect on the game - should be fine.

Care to elaborate on boolean?

**Comment by TechpriestEnginseer** [comment]
If event has a probability, I want the boolean to return true if it becomes successful, or return false if the event is a failure.

(Construction of a Lighthouse: Requires 300 gold, 50% chance of lighthouse, returns true if successful, returns false if not)

**Comment by LoneGazebo** [comment]
Oh, I see. They're voids, but I could probably edit that.

**Comment by LoneGazebo** [comment]
What about a lua hook in the randomchance function? That'd be easier for me to make compatible.

**Comment by TechpriestEnginseer** [comment]
That could work as well.
