### ISSUE TITLE
Vassel Overview shows Religion and Science of second vassal on first vassal's page

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2258]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/15

1. Mod List (if using standard CPP set, leave blank):
Full VP
Enginseer's version of Events and Decisions and its add on
Enlightenment Era and Xony's Compat mod
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Ice Free Coasts
Celtic City Names, Iroquoian City Names, Randomize City Names
NoAltitudeTraining (removes the Mt. Kilman promo)
My own thing that does various things SQL type stuff
Tectonic Map

2. Type of error (i.e. crash, interface bug, AI quirk):  I guess its mathematically possible Siam and Ethiopia have the same Faith per turn, but Siam is way behind on science, nowhere close to Printing Press

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![20160801034145_1](https://cloud.githubusercontent.com/assets/16260521/17287392/5db8bf8e-579d-11e6-98dd-d5f70b412953.jpg)
![20160801034150_1](https://cloud.githubusercontent.com/assets/16260521/17287393/60ea8250-579d-11e6-8870-9350cba0b8e1.jpg)

**Comment by LoneGazebo** [comment]
@mwhiter, care to chime in?

**Comment by pandasnail** [comment]
So when I reloaded and opened it up again, at first it said 0 Faith and 0 Science for Siam, then I looked at Ethiopia, then went back to Siam and Ethiopia's was still there. So maybe it just can't switch back to the zero somehow. 

Also, they only have 1 island city, so 0 science and faith per turn isn't impossible at all.

**Comment by pandasnail** [comment]
So actually thinking about it for 5 seconds, 0 Science makes no sense either, for some reason I thought it was less than 20% I get from them, and also given how high Ethiopia's number is, it must just show the number they earn per turn, not the amount I'm getting, and they should have at least the Palace Science.

**Comment by pandasnail** [comment]
Yeah, when Siam got themselves some Faith per turn, this issue went away. And I did at one point look in the one City Production log, and their only city listed Shrine as a build choice, so they probably really did have zero faith per turn.
