### ISSUE TITLE
CTD on mouseover of religion spread icon in Unit Panel in a Holy City that has a Faith Wonder (-20% Conversion Modifier)

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2259]
Bug Report Template

Mod Version (i.e Date - (7/30)):

1. Mod List (if using standard CPP set, leave blank):
Modified community patch DLL for my mod, but common code here.

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![ctd](https://cloud.githubusercontent.com/assets/14372214/17298659/7ef29d68-57d0-11e6-8f91-d55b95e19828.png)

**Comment by LoneGazebo** [comment]
hmm...was there no religion in the city? i.e. a majority?

**Comment by Iamblichos** [comment]
Tried it twice at two different points in the game. At one point there was a majority, later there wasn't. Both CTD'd on mouse over on prophet convert button.

**Comment by LoneGazebo** [comment]
Try this in ::simulateprophetspread

if (it->m_eReligion > RELIGION_PANTHEON && eReligion != it->m_eReligion)
		{
			const CvReligion *pReligion = GC.getGame().GetGameReligions()->GetReligion(it->m_eReligion, NO_PLAYER);
			if(pReligion)
			{
				int iPressureRetention = pReligion->m_Beliefs.GetInquisitorPressureRetention();  // Normally 0
				if (iPressureRetention > 0)
				{
					ePressureRetainedReligion = it->m_eReligion;
					iPressureRetained = it->m_iPressure * iPressureRetention / 100;
				}
			}
		}

Add the if(pReligion) element

**Comment by Iamblichos** [comment]
This time it crashed not on mouse over but hitting the button to convert/spread.

**Comment by LoneGazebo** [comment]
Did you add my recommendation?

**Comment by Iamblichos** [comment]
I did. The latest CTD is with your code (and I did remove the asteriks).

**Comment by LoneGazebo** [comment]
I can't replicate - you running any other mods? Have any bad lines in your religion database?

**Comment by LoneGazebo** [comment]
Add the same thing

```
const CvReligion *pReligion = GC.getGame().GetGameReligions()->GetReligion(it->m_eReligion, NO_PLAYER);
			if(pReligion)
			{
```

to the AddProphetSpread function.

**Comment by Iamblichos** [comment]
I can't replicate by starting a new game and giving my opponent a founder religion and religion wonder. Just happens in this instance.

No religion mods. Will try putting that in AddProphetSpread

**Comment by Iamblichos** [comment]
bINGO! Adding it as well to AddProphetSpread, conversion happened and no CTD.

**Comment by LoneGazebo** [comment]
Cool, glad that fixed it. Closing.
