### ISSUE TITLE
Trade Route Overview does not match available trade routes

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#2260]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7-30

1. Mod List (if using standard CPP set, leave blank): VP w/EUI, quick turns, local generals (in modpack form so I assume logs/saves are not helpful)

2. Type of error (i.e. crash, interface bug, AI quirk): interface bug

3. Steps to reproduce: When viewing trade routes, trade route screen does not necessarily match the actual available trade routes

4. Additional information: 
![20160801011856_1](https://cloud.githubusercontent.com/assets/11132095/17310466/370bf1a4-580a-11e6-91ae-1e3ba74818f4.jpg)
![20160801011901_1](https://cloud.githubusercontent.com/assets/11132095/17310465/3708a0d0-580a-11e6-8e12-c56e027cf241.jpg)

In the screens, a naval trade route from Delhi to Jeonju is clearly available. In actuality this isn't the case. I'm sorry if this isn't terribly helpful information.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/394865/Logs.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Not sure what logic whoward's lua uses, I'd need to look at the lua. Blegh.

**Comment by LoneGazebo** [comment]
@ilteroi any ideas here? The lua functions: GetTradeRoutesAvailable and GetPotentialInternationalTradeRouteDestinations are the ones being used, and both seem to reference the same set of routines below that level. Is this possibly a cache issue, i.e. the cache is only refreshing when units are made, not when this trade route overview tab is viewed?

**Comment by LoneGazebo** [comment]
@ilteroi, when you get a chance, mind taking a look at this? I've wracked my poor mind on this and I can't seem to figure out what would cause the discrepancy, as they both utilize the same core functions. Only difference I can see is that one hits the pathfinder.

**Comment by ReanKW** [comment]
Not sure if you guys noticed, but in the screenshot shown there's already a land route going from Delhi to Jeonju which if memory serves prevents you from also sending a coastal route the same way.

**Comment by ilteroi** [comment]
can't reproduce. need savegame.

but i did find some other oddities:

virtually all indian trade routes originate in lahore, while other cities suffer from poverty unhappiness. also all are caravans, no sea routes although it's a port city.

![image](https://cloud.githubusercontent.com/assets/1358966/18846118/be002bc6-8424-11e6-882f-4c31af339e6e.png)

**Comment by LoneGazebo** [comment]
@joosegoose can you still reproduce this?

**Comment by joosegoose** [comment]
Go ahead and close. If something like this pops up again for me I'll re-open with a savegame.

**Comment by LoneGazebo** [comment]
Cool.
