### ISSUE TITLE
CTD in EstablishHomelandPriorities():

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2261]
Got a CTD in CvHomelandAI::EstablishHomelandPriorities():

![ctd](https://cloud.githubusercontent.com/assets/14372214/17314067/0b6be9e2-5827-11e6-9c19-073fd320edf9.png)

**Comment by Iamblichos** [comment]
Looks like a divide by zero instance.

**Comment by LoneGazebo** [comment]
Good call, I'll add a max( statement in there.
