### ISSUE TITLE
CTD attempting to load a saved game from mods main menu

### ISSUE THREAD

**Issue by harra210** [LoneGazebo/Community-Patch-DLL#2262]
[CBP_CTD_080116.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/395103/CBP_CTD_080116.zip)

Bug Report Template

Mod Version (i.e Date - (1.7.30)):

1. Mod List (if using standard CPP set, leave blank):
Full Vox Populi set, installed as per Automatic Installer instructions.

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:
From main menu, select mods, have all mods set up, click load game. CTD.

4. Additional information:
OS: Windows 8.1
Verified game integrity, did not remedy.
Only mods installed is Vox Populi

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Try starting a game with mods, then loading the save once a new game is loaded. That sometimes works for issues like this.

**Comment by harra210** [comment]
[CTD_CBPLoadafterNewgame_080116.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/395148/CTD_CBPLoadafterNewgame_080116.zip)

I started a new game with mods enabled. Program was able to load the new game set but would crash upon attempting to click the Load game button. I'm guessing aside from random CTD's during the game I could play a game in one sit down.

**Comment by Iamblichos** [comment]
Do you have steam cloud saves disabled? It will crash if you load a game and that is disabled. The LUA makes a call to that.

**Comment by harra210** [comment]
> Do you have steam cloud saves disabled? It will crash if you load a game and that is disabled. The LUA makes a call to that

This was the cause. Recently reformatted and Steam turned off cloud support by default. Thank you so much in rooting out the cause!
