### ISSUE TITLE
Communitas CTD

### ISSUE THREAD

**Issue by BlackliteWrath** [LoneGazebo/Community-Patch-DLL#2263]
Bug Report Template

Mod Version: Latest

1. Mod List (if using standard CPP set, leave blank):
Standard CPP set, faster aircraft animations, historical religions, ethnic units, reseed, cultural diversity, EUI 

2. Type of error (i.e. crash, interface bug, AI quirk): 
Whenever attempting to start a Communitas map game, immediate CTD

3. Steps to reproduce:
Boot up mods, try to play Communitas

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Remove non CPP mods until you find the one that causes the CTD.

**Comment by BlackliteWrath** [comment]
Didn't realize there was 7-27 version. I was using the version prior to it. I'll try downloading the new version, use only CBP set of mods and try again.

**Comment by BlackliteWrath** [comment]
Downloaded new version, found the conflicting mod. JFD's Cultural Diversity doesn't work with Communitas.

**Comment by Iamblichos** [comment]
I would contact JFD too and let him know of the conflict. He's good about supporting issues with his mods.

**Comment by JFDaly** [comment]
Okay, so the CTD seems to come from here:

![ere](http://i.imgur.com/mS6a9MG.png)

Hopefully someone with more DLL knowledge can explain what this means.

**Comment by LoneGazebo** [comment]
It means that there's a plot call in communitas or CD that is 'plot:getx() where plot is a nil value.
