### ISSUE TITLE
Nationalization policy

### ISSUE THREAD

**Issue by logic2718** [LoneGazebo/Community-Patch-DLL#2264]
Bug Report Template

Mod Version: 7/30 hotfix of 7/27 version

1. Mod List: standard

2. Type of error: bug
I do not think the yields from my Trader Sid's Offices are being calculated into my gpt.

3. Steps to reproduce: Load the save and compute my gpt, noting that each Trader Sid's office is producing 48 gold.
Unfortunately I do not have a save from before adopting Nationalization, but I noticed almost no change in my gpt after adopting it. A rough estimate of my gpt should indicate that it's off by a factor of 2.

4. Additional information:

---------------------------
[Gajah Mada_0530 AD-1940-January.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/397215/Gajah.Mada_0530.AD-1940-January.zip)

**Comment by LoneGazebo** [comment]
The code is working, however I don't think it was refreshing properly. I'll look at it.
