### ISSUE TITLE
Units disobeying orders

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2265]
Mod Version (i.e Date - (4/23b)): latest hotfix 7-30

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
  
 This issue was brought up by me before in the forums but it wasn't dealt with due to apparent lack of evidence. Now I seem to have managed to track the unruly behaviour of a unit.
 Look at the screenshot. The scout is ordered to land on a hill tile marked by an arrow. What happens next is that the unit reaches the water tile next to the hill and the next turn it ... suddenly performs a amphibious attack on nearby barbarian (which is hidden in the fog of war!) instead of landing on the hill tile. When I decided to load previous saves I discovered interesting things:
 1. When I load an autosave one turn before the unauthorized attack, the scout unit behaves legitimately and **doesn't** attack the barbarians. (Save 1280)
 2. But when I load an autosave **two** turns before the attack, the scout does disobey my order and goes frenzy (Save 1320).
 

3. Steps to reproduce:

 Load "save-1280" to get the proper behaviour of the scout and "save-1320" to get the bugged behaviour.

![5_1](https://cloud.githubusercontent.com/assets/16341598/17338381/eb0f25aa-58ef-11e6-89a1-cc4ed498f86f.jpg)
 

![20160802203502_1](https://cloud.githubusercontent.com/assets/16341598/17338608/bbffec62-58f0-11e6-83dc-d9a4a131810e.jpg)

[AutoSave_0067 BC-1320.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/397697/AutoSave_0067.BC-1320.zip)
[AutoSave_0068 BC-1280.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/397698/AutoSave_0068.BC-1280.zip)

**Comment by LoneGazebo** [comment]
@ilteroi, not sure if this helps with tracking this down or not.

**Comment by ilteroi** [comment]
this has been fixed some days ago. apparently the fix wasn't included in 7/30 yet, but 8/2 should have it.

**Comment by LoneGazebo** [comment]
I saw and added the cached unit path element, so we'll see if it is fixed.
