### ISSUE TITLE
Modpack for 8-8

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#2267]
@Iamblichos, mind taking point on the modpacks for 8-2? Thanks!

**Comment by Iamblichos** [comment]
Yes sir! Will create tomorrow morning!

**Comment by Iamblichos** [comment]
@LoneGazebo , want me to upload it here and then you can put it on the front page?

**Comment by Iamblichos** [comment]
Just link this on the front page:

https://www.dropbox.com/s/ubc8ajcedma5ybn/Vox_Populi_MP.zip?dl=0

**Comment by Iamblichos** [comment]
Any questions direct them to this thread here or create a new Issues thread.

**Comment by LoneGazebo** [comment]
Did you make a no-EUI one as well? If not, mind whipping up one?

**Comment by Iamblichos** [comment]
No I did not. Sure thing!

**Comment by Iamblichos** [comment]
https://www.dropbox.com/s/zl3ig9326bwknfh/Vox_Populi_MP_NOEUI.zip?dl=0

**Comment by LoneGazebo** [comment]
Thanks, I'll add to other link.

**Comment by LoneGazebo** [comment]
@ilteroi and @Iamblichos

So barbs still do not work, even with RNG changes. I still think that the issue is related to barbarian data not being properly saved/shared in the cvunit element. That or barbarian moves in the tactical AI are still randomized somehow.

**Comment by Iamblichos** [comment]
Did somebody do a multiplayer game with ilteroi latest changes with the wrapper?

**Comment by LoneGazebo** [comment]
Yes I'd assume that's what this is for. 8-2 modpack includes ilteroi wrappers.

**Comment by Iamblichos** [comment]
It does? His commits are ahead of master.

**Comment by LoneGazebo** [comment]
It is. Fefe is always head.

**Comment by LoneGazebo** [comment]
I added the DLL so yes, I'm 100% sure it is in there.

**Comment by Iamblichos** [comment]
Okay just double checking. I forget you do a lot of your merging offline.

**Comment by LoneGazebo** [comment]
Yeah, I do all merging offline. I don't trust github merge, it has screwed me over so many times.

**Comment by ilteroi** [comment]
yeah should use kdiff and do a 3-way merge, it's a breeze!

**Comment by LoneGazebo** [comment]
@Iamblichos, modpack for 8-8? If @ilteroi wants to fix random unsigned int warning beforehand, hold off. Otherwise, go for it.

**Comment by Iamblichos** [comment]
Sure thing. This afternoon work?

**Comment by LoneGazebo** [comment]
Yar

**Comment by LoneGazebo** [comment]
@Iamblichos, I'm going to upload a new DLL with some smaller changes later today. Nothing major, just some things for JFD, a tweak for RNG for MP, and a few performance fixes.

**Comment by Iamblichos** [comment]
Sounds good, let me know here, when you have it done. If you could please, also, merge your changes on github so I can update my own mod.

**Comment by LoneGazebo** [comment]
I merged last night, but I'll be uploading again soon.

Also, when making modpack, don't forget to enable MP stuff in the custommods.h file. :)

**Comment by Iamblichos** [comment]
ah yes, diplo stuff in custommods.h?

**Comment by LoneGazebo** [comment]
Yurp

**Comment by Iamblichos** [comment]
We'll just need to notify users that they will not be able to use the modpack in single player then. Only multiplayer.

**Comment by LoneGazebo** [comment]
Sounds good. SP shouldn't be using Modpack anyways.

**Comment by LoneGazebo** [comment]
@Iamblichos 8-8-1 is up on github. EUI and No-EUI packs would be great. Feel free to open a thread on civfanatics and link them when you have completed them.

Thanks!
G

**Comment by Iamblichos** [comment]
I sure will. Might be tonight (if I have free time available), but definitely tomorrow. Gotta do some merging now.
