### ISSUE TITLE
Naval Melee can attack Fort Unit

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#2268]
Mod Version (i.e Date - (4/23b)): 7-30

1.  Mod List (if using standard CPP set, leave blank):

Whole CPP with EUI,
FlagPromotion(v7)
JFD's Cultural Diversity (Core) (v 9)
JFD's Cultural Diversity (Soundtrack) (v 1)
UI - Promotion Tree (v 15)
Unique Cultural Influence (v 4)
Unit Path Viewer

2.  Type of error (i.e. crash, interface bug, AI quirk): 

Naval Melee can attack Fort Units

3.  Steps to reproduce:

Order Naval Melee Unit to attack Units in a fort.

4.  Additional information:

Naval Melee seems to suffer from -50% CS amphibious penalty
No Combat Preview

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshot

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/398671/Logs.zip)

**Comment by ilteroi** [comment]
this is by design. forts are like cities, naval units can enter them. 

don't know whether the amphibious modifier should apply though.

**Comment by XplosiveLun** [comment]
I mean melee navy can attack units in fort. 

Here's a screenshot.
![20160803121523_1](https://cloud.githubusercontent.com/assets/12179253/17357000/172b038c-598d-11e6-8bc3-a1a9677b90a2.jpg)

**Comment by ilteroi** [comment]
i know. melee attack is movement. where you can move you can attack

**Comment by XplosiveLun** [comment]
Oh, now I got what you meant. It seems awkward for ships to attack land unit directly ( Units in cities are damaged indirectly).
Also, I overlook what might improve the CS of pikeman. Maybe it is the fortifying and combat bonuses.
