### ISSUE TITLE
Missing string in mercenary menu

### ISSUE THREAD

**Issue by MalekDeneith** [LoneGazebo/Community-Patch-DLL#2269]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

7/7

1. Mod List (if using standard CPP set, leave blank):

Full Vox Populi install
Calypso's Colored Religious Icons (Basic + Extended)
Faster Aircraft Animations
Fortress Borders
JFD's Cultural Diversity
JFD's Exploration Continued Expanded
JFD's Rise to Power
Quick Turns
Useful Oil Mod

2. Type of error (i.e. crash, interface bug, AI quirk): 

Missing string

3. Steps to reproduce:

4. Additional information:

One of the possible mercenary categories is showing TXT_KEY_UNIT_CUIRASSIER instead of a name. Attaching a screenshot.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

![20160731201857_1](https://cloud.githubusercontent.com/assets/20817627/17369477/cf992218-5998-11e6-88b7-edf9ee0eb03c.jpg)

**Comment by TechpriestEnginseer** [comment]
That's an JFD's issue. Not Gazebo.

**Comment by LoneGazebo** [comment]
I dun be makin that one, sir. Alert JFD.
