### ISSUE TITLE
Sometimes when I liberate a CS I get this weird screen

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2270]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 7/15

1. Mod List (if using standard CPP set, leave blank):
Full VP
Enginseer's version of Events and Decisions and its add on
Enlightenment Era and Xony's Compat mod
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Ice Free Coasts
Celtic City Names, Iroquoian City Names, Randomize City Names
NoAltitudeTraining (removes the Mt. Kilman promo)
My own thing that does various things SQL type stuff
Tectonic Map

2. Type of error (i.e. crash, interface bug, AI quirk):  So sometimes when I liberate a CS, I get the first screenshot. And I wouldn't care, but then trading can get strange, especially peace deals. Everytime I get the kind of weird peace deals seen in screenshot two its been after a liberation where I got screenshot one. Possibly coincidence,, but its been maybe ten fifteen times over the last few months. I think it happens when the CS was owned by barbarians for awhile on account of the name Crom and anecdotal evidence of always getting less influence, which one does when it used to be barbarian owned. I don't have evidence of this theory tho.

The second screenshot produced this LUA error, none for the first tho unfortch
[112124.125] Runtime Error: C:\Users\James\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\TradeLogic.lua:518: attempt to index field '?' (a nil value)
[112124.125] Runtime Error: C:\Users\James\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\TradeLogic.lua:2920: attempt to index field '?' (a nil value)
[

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![libpt1](https://cloud.githubusercontent.com/assets/16260521/17379614/3c304d64-5991-11e6-8f0e-4100e2f6b43a.jpg)
![libpt2](https://cloud.githubusercontent.com/assets/16260521/17379621/4155e6dc-5991-11e6-8ec1-2a57b7289ab3.jpg)

**Comment by TechpriestEnginseer** [comment]
That's typical because you haven't met the city-state before you liberated it. The way I see it, this problem only occurs if the city-state doesn't have a city. If so, the normal city-state UI shows.

**Comment by mwhiter** [comment]
Perhaps a check is needed to not fire an event if the city-state has no city? (just a notification?) A rare, but possible situation.

**Comment by pandasnail** [comment]
Well, it doesn't happen everytime I havn't met the CS I liberate, that's why I came up with a narrower explanation. Could be something else tho, even merely my computer being mad perhaps.

**Comment by TechpriestEnginseer** [comment]
Yeah, but it happens everytime if you try to meet a city-state who doesn't have a city which is usually the problem here.

**Comment by LoneGazebo** [comment]
I think I see where this is happening. I'll add a check.
