### ISSUE TITLE
AI Missionary issue.

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2271]
Mod Version - August the second

1. Mod List (if using standard CPP set, leave blank):
Standard full set (set with instant bonus resource reveal, and some tiny balance changes I've put) + custom religion icons from strange religions mod on Steam workshop (should still work without it I think)

2. Type of error - AI-related quirk

3. Steps to reproduce:
DO NOT found a religion (although sometimes happens even if you found if they want to convert you despite your complaints).
Get a city that is close to two people who have founded and/or just like Missionaries.
They'll be sending Missionaries endlessly to this city OR those close cities (if two on their "border") - one to convert it to his religion, the other to convert it back. They've wasted dozens upon dozens each by Renaissance and Enhanced very late because of it, but they're slowly calming down now as I conquered Bismarck. 

They shouldn't be wasting Missionaries endlessly just to constantly convert two cities back and forth I think.

4. Additional information:
I'm too sexy for my love too sexy for my love
Love's going to leave me

I'm too sexy for my shirt too sexy for my shirt
So sexy it hurts
And I'm too sexy for Milan too sexy for Milan
New York and Japan

And I'm too sexy for your party
Too sexy for your party
No way I'm disco dancing

**Comment by ilteroi** [comment]
well, what should they be doing instead?

**Comment by Enrico-Swagolo** [comment]
In my opinion city conversion  of two smallish cities is not worth spending dozens of thousands of faith over (they've sent, I think, 50+ Missionaries each by now), especially considering each of those two bordering cities had like 8-10 pop, and the rest of my empire got converted by Theodora - one of those two - anyway.

At the very least they should try sending it to different cities or just give up at some point. If I were one of them, I would've either declared war on the other converter or just sent my Missionaries elsewhere. I would even consider just  getting a Prophet and a holy site instead - with how much they've both wasted on those two cities, they'd have by now like 5-6 holy sites each I think.

I don't know why Theodora would care so much anyway  considering she already got her 20% buildings long, long ago.

**Comment by ilteroi** [comment]
i think we can agree that they should concentrate on pagan cities first. but after that, priorization starts to get tricky

**Comment by Enrico-Swagolo** [comment]
I agree. Theodora actually sort of did it (by pure chance though) - she converted those two pantheon cities first, then while Pocatello was busy converting those Two Cities back, she sent more Missionaries (while those two were converted) to the back of my empire to convert the rest I had. Since her religion was pretty good and far superior to Pocatello's, I expended one Missionary to get it to the remainder fast - I actually didn't get my religion because of being 1 turn too late so I had and still have very good faith generation.

It seems like both the civs consider those two cities the must-have before they spread it to others I own. They've been engaging in Two-City Conversion since Classical and it's Renaissance now. They won't be wasting faith for long though, I plan on conquering them anyway, I am Napoleon and I am about to unlock the Musketeers after all
