### ISSUE TITLE
Multi modpack 8/2 crash

### ISSUE THREAD

**Issue by astaentreri** [LoneGazebo/Community-Patch-DLL#2273]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8/2

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD, for both human players connected

3. Steps to reproduce:
Load save, click anything or just wait.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/401299/Logs.zip)

[AutoSave_0215 AD-1890.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/401302/AutoSave_0215.AD-1890.zip)

4. Additional information:
cleaning cache and loading earlier save allowed to progress

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Iamblichos** [comment]
can you post your minidump file as well?

**Comment by astaentreri** [comment]
weird thing is that it didn't generate a minidump

**Comment by Iamblichos** [comment]
How many turns did you get in before the crash?

**Comment by astaentreri** [comment]
it crashed on transition from 215 to 216

**Comment by LoneGazebo** [comment]
Are barbarians enabled?

**Comment by LoneGazebo** [comment]
If you were able to progress past it may have just been a game hiccup. Happens in MP sometimes!

**Comment by astaentreri** [comment]
disabled barbs, enabled ruins, enabled promotions/policy saving, enabled events, map is continents+ huge with 8 civs on it and max city states

**Comment by Iamblichos** [comment]
The fact that you got that far into the game is promising, and the fact that there was no minidump makes me think the crashed was induced by a desync.

**Comment by LoneGazebo** [comment]
Not exactly, as he disabled barbs. We need to see what barbs do.

**Comment by Iamblichos** [comment]
I haven't played many multiplayer games (vanilla) passed turn 100~150 without it crashing. Sometimes sooner.
