### ISSUE TITLE
Not able to choose option in Windmill event

### ISSUE THREAD

**Issue by dennisdahlc** [LoneGazebo/Community-Patch-DLL#2274]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

27-7

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

Not able to selection option

3. Steps to reproduce:

I have gotten this in the 7-7 build as well.
Everytime I get the event, I have had enough money to selection the third option for 500 gold, but the game wont let me, claiming that I have to little of the yield.
![not able to choose option](https://cloud.githubusercontent.com/assets/17319141/17399567/15677f7e-5a43-11e6-80c9-d810e3438a3f.png)

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
The tooltip is inaccurate- guessing you are playing epic/marathon, meaning that gold costs are inflated.

**Comment by dennisdahlc** [comment]
Yep. I always plays on marathon.

**Comment by dennisdahlc** [comment]
May I suggest that the event does only show up when the cheapest option can be chosen ? The event provides a quite nice boost to production, and for me it always seems to popup when I does not have the funds to choose anything.
