### ISSUE TITLE
Ice Age/Heat Wave Events Appearing with No Bad Events chosen

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#2276]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

2/8

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

Event issue.

3. Steps to reproduce:

Select no bad events, Ice age triggers, with the only choices for most of the game being bad ones (lose 2 gold, or lose 2 production).

Same with Heat Wave.

Maybe it's intended, but I consider events "neutral" when they take something but also give something. Paying to avoid a negative it's choosing between two different negatives.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
These events are neutral.

**Comment by LoneGazebo** [comment]
The sub-events are bad, but I'll just make them all bad for clarity.
