### ISSUE TITLE
Promotion wrong description

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2277]
Mod Version (i.e Date - (4/23b)): 8-2

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

 When hovering over promotion button it gives wrong description. 

![20160804210852_1](https://cloud.githubusercontent.com/assets/16341598/17412948/fe6207fa-5a87-11e6-81cb-33af89d8cdcf.jpg)
![20160804210905_1](https://cloud.githubusercontent.com/assets/16341598/17412949/fec4bec2-5a87-11e6-87b3-17a7f447feb3.jpg)

**Comment by LoneGazebo** [comment]
Post your lua log.

**Comment by LoneGazebo** [comment]
Still need that lua log, otherwise closing.

**Comment by saamohod** [comment]
Can't produce that log atm, sorry. Feel free to close.

**Comment by LoneGazebo** [comment]
ok
