### ISSUE TITLE
Battering Ram Cannot Attack Cities

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2279]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-2

1. Mod List (if using standard CPP set, leave blank):
Standard

2. Type of error (i.e. crash, interface bug, AI quirk): 
Game-breaking bug

3. Steps to reproduce: Build a battering ram, make it attack city. Unable to attack.

**Comment by Iamblichos** [comment]
```
//support units cannot attack themselves
	if (IsCityAttackSupport() && bIsEnemyCity)
		return -1;
```

**Comment by Iamblichos** [comment]
change to:

```
//support units cannot attack themselves
    if (IsCityAttackSupport() && !bIsEnemyCity)
        return -1;
```

**Comment by LoneGazebo** [comment]
lolol

**Comment by LoneGazebo** [comment]
lolol
