### ISSUE TITLE
Luxury resources become unavailable after the trade deal ends

### ISSUE THREAD

**Issue by NuttSo** [LoneGazebo/Community-Patch-DLL#2280]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-2

1. Mod List (if using standard CPP set, leave blank):
VP
Faster aircraft animation 
Infoaddict 
Really advanced setup

2. Type of error (i.e. crash, interface bug, AI quirk): 
Resources become unavailable after the trade deal ends.

![20160803140644_1](https://cloud.githubusercontent.com/assets/20857721/17437331/d54bb250-5b25-11e6-9028-9575fcf501c7.jpg)

![20160805153407_1](https://cloud.githubusercontent.com/assets/20857721/17437364/f565173e-5b25-11e6-9565-2965a86e7768.jpg)
![20160805145445_1](https://cloud.githubusercontent.com/assets/20857721/17437359/f19b4ba0-5b25-11e6-9725-035b1c896917.jpg)
![20160805145400_1](https://cloud.githubusercontent.com/assets/20857721/17437346/e3c31fd0-5b25-11e6-8b1b-ce8d0df82ce5.jpg)

3. Steps to reproduce:
Trade a luxury resource .

4. Additional information:
after the trade end ,the luxury resource doesn't show up in the diplomacy overview(deal history) but instead u have deals that "ended on  turn -2" .
I didn't have this issue before the update 7-27.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by pandasnail** [comment]
So if this is back for me too, I can make a test game save probably. Would you want it before the trade is made, the turn before it 'completes' or is this a situation where it would likely work normal on your machine and the test save would be worthless?

**Comment by oedali** [comment]
I am having the exact same issue. Trade deal ends, and the deal keeps lasting in effect but disappears from all screens and there's no record of it. No way to cancel it - gets stuck forever. I will post a report too.
