### ISSUE TITLE
I tend to lose my embassies occasionally

### ISSUE THREAD

**Issue by NuttSo** [LoneGazebo/Community-Patch-DLL#2281]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-2 

1. Mod List (if using standard CPP set, leave blank):
VP
Faster aircraft animation
Infoaddict 
Really advanced setup

2. Type of error (i.e. crash, interface bug, AI quirk): 
I tend to lose my embassies occasionally

3. Steps to reproduce:
trade an embassy and wait at least 250 turns 

4. Additional information:
I didn't have this issue before the update ~~7-27~~ 7-30.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Embassies go away, and have to be re-traded.

**Comment by NuttSo** [comment]
So if I trade trade an embassy for an embassy with an AI , after some time mine will be gone but not his!!

**Comment by pandasnail** [comment]
So um, in all my playing, I've never had to retrade embassies without a war or a denouncement. If you really mean embassies and not DoFs or Open Borders, then I've had a bug for a year.

**Comment by NuttSo** [comment]
since the last 2 updates , I've had to retrade my embassies every now.
