### ISSUE TITLE
Indonesia - Candi building 

### ISSUE THREAD

**Issue by NuttSo** [LoneGazebo/Community-Patch-DLL#2282]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-2

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

Playing as Indonesia if the player somehow losses his Candi building and build it again a new unique luxury resource will spawn , giving the player 3 unique luxuries in one city  
3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Yep. Intended.
