### ISSUE TITLE
ReligionOverview.lua Belief tab does not work in modpack...not sure about the standard method

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2283]
Fix: Comment out lines 615 and 568 where those lines read:

Tooltip = Locale.Lookup(belief.Tooltip),

change to:

--Tooltip = Locale.Lookup(belief.Tooltip),

**Comment by LoneGazebo** [comment]
Works in standard, but I've never been able to figure out why it fails in modpack. When you open database after loading modpack, what does the beliefs table look like?

**Comment by Iamblichos** [comment]
Beliefs table is full. Anything specific?

**Comment by LoneGazebo** [comment]
Any missing IDs?

**Comment by Iamblichos** [comment]
Nope nada. I have extra beliefs in my mod (but the issue exists in the VP as well as is). All ID's are consecutive and continuous

**Comment by LoneGazebo** [comment]
And all have a tooltip database element?

**Comment by Iamblichos** [comment]
You mean a Description and Short Description? Yep.

**Comment by Iamblichos** [comment]
I mean, it's no biggie as long as the modpack makes the corrections above, It works as it should.

**Comment by LoneGazebo** [comment]
Sounds good.

**Comment by Iamblichos** [comment]
Hang on with this....I didn't realize there was a column called 'Tooltip' for the Beliefs database. It's all empty. Ugh, might be on my end of the problem....let me rectify that and see if JFD's lua works as it should.

**Comment by Iamblichos** [comment]
Ugh...that fixed it populating the 'Tooltip' column. Problem was on my end.
