### ISSUE TITLE
Trade Deal never ends 

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2284]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/2

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Bug 

3. Steps to reproduce: I had two trade deals. One giving cotton and getting back amber from Celts, another giving silver and getting back copper from Maya. They both ended on turn 142 because I remember it was on the "current deals" screen with that end date. Turn 142 came and went, and the deals never got cancelled. But they mysteriously disappeared from the info screens.

See 1st screenshot - at bottom it says silver and copper are being imported, but the corresponding deal isn't show. Likewise, it says cotton and silver being exported, but corresponding deal not shown. 

Also see this 2nd screenshot - it says deal ended on turn -2 but doesn't even show what it was. I think these two were the "corrupted" deals

Caveat: it does not happen to every single deal. Some deals end just fine when the duration is over. These two deals somehow got bugged

![20160805191122_1](https://cloud.githubusercontent.com/assets/20485377/17452817/3d05ce38-5b41-11e6-8d94-8678ea65c065.jpg)

![20160805212011_1](https://cloud.githubusercontent.com/assets/20485377/17453869/9ea191fc-5b52-11e6-8ac3-19a5c794f4b1.jpg)

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Iamblichos** [comment]
G I know we've been wondering about this for a long time now? Do you have any idea where it is coming from?

**Comment by LoneGazebo** [comment]
I'm going to assume that its happening as a result of the AI's evaluation of a deal renewal. I've been looking into it and may have a fix for next time.

**Comment by NuttSo** [comment]
I didn't have this issue before the update 7-30 , I was looking download 7-27 version but it's not on mega
