### ISSUE TITLE
Policies InternalTradeGold entries

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2287]
Just using the CP, the gold bonus never shows up for me(or maybe not graphically). Using along with Vox Populi, it graphically displays the bonus is from the autocratic policies when this can be applied to any policies. It should be reworded from +gold from internal trade routes rather than +gold from internal trade routes(autokary)

**Comment by LoneGazebo** [comment]
Eh? It shows up as a bonus under city connections in the top panel UI.

**Comment by TechpriestEnginseer** [comment]
I meant
````
		<Row Tag="TXT_KEY_TP_GOLD_FROM_INTERNAL_TRADE">
			<Text>{1_Num} from [ICON_INTERNATIONAL_TRADE] Internal Trade Routes (Autarky).</Text>
		</Row>
````
Should be just
````
		<Row Tag="TXT_KEY_TP_GOLD_FROM_INTERNAL_TRADE">
			<Text>{1_Num} from [ICON_INTERNATIONAL_TRADE] Internal Trade Routes.</Text>
		</Row>
````

**Comment by LoneGazebo** [comment]
Ah gotcha.


Jeff Grooms
thewizardofwas@gmail.com

**Comment by TechpriestEnginseer** [comment]
Same thing for here.
````
		<Row Tag="TXT_KEY_PRODMOD_YIELD_PUPPET_POLICY">
			<Text>[NEWLINE][ICON_BULLET]Modifier for [ICON_PUPPET] Puppet from Martial Law: {1_Num}%</Text>
		</Row>
		<Row Tag="TXT_KEY_PRODMOD_YIELD_OCCUPIED_POLICY">
			<Text>[NEWLINE][ICON_BULLET]Modifier for [ICON_OCCUPIED] Occupied from Martial Law: {1_Num}%</Text>
		</Row>
````
should be
````
````
		<Row Tag="TXT_KEY_PRODMOD_YIELD_PUPPET_POLICY">
			<Text>[NEWLINE][ICON_BULLET]Modifier for [ICON_PUPPET] Puppet from Policies: {1_Num}%</Text>
		</Row>
		<Row Tag="TXT_KEY_PRODMOD_YIELD_OCCUPIED_POLICY">
			<Text>[NEWLINE][ICON_BULLET]Modifier for [ICON_OCCUPIED] Occupied from Policies: {1_Num}%</Text>
		</Row>
````
Due to TableEntries in PuppetProdMod and OccupiedProdMod in CP folder but the UI text is in CBP folder. (Users who are just using CP and using policies that rely on these entries might wonder where are their excess production are coming from)

I'd also like to make a request for a Golden Age Point yield icon for tiles for the Community Patch Events since some of the events improve natural wonders with golden age points.

**Comment by LoneGazebo** [comment]
I think there is a GAP yield icon.
