### ISSUE TITLE
Enhance Religion No Next Turn

### ISSUE THREAD

**Issue by phlipsmsu** [LoneGazebo/Community-Patch-DLL#2288]
Mod Version (i.e Date - (4/23b)): community patch v72 (3/9/2016)

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Can't go to next turn.

3. Steps to reproduce: 
Don't found religion (all religions founded).
Capture holy city of unenhanced religion.
Produce great prophet.
Enhance religion.
Enhance religion screen is non-functional.

4. Additional information:
There's no crash. I just can't move to next turn.
 I'm not sure if this is a bug from the base game or something that got overlooked in the CBP.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
[Log files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/405204/Log.files.zip)
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/405209/QuickSave.zip)

3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
That's an extremely old version of the mod. You need to update to the latest version.
