### ISSUE TITLE
Modding BarbarianBonus not working?

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#2289]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

8/2

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

Modding question.

3. Steps to reproduce:

Tweak barbarian bonus on DifficultyMod.xml, it doesn't change in a game in course. Needs a new game?

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Iamblichos** [comment]
Try a new game. Which difficulty did you apply the different bonus to?

**Comment by Oscar-IronTower** [comment]
Doesn't work in a new game either. I tweaked it to 25 on prince, hover over a barbarian unit, I get 73% bonus with warrior, that is, a 40% default.

**Comment by Iamblichos** [comment]
What did you change the value to? And I believe warriors have a promotion that gives them 33% bonus vs Barbarians. So that ought to be your reason.

**Comment by Oscar-IronTower** [comment]
Changed it to 25%. As I said above, the value is 73%, including the 33% bonus of the warrior, thus 40%... I don't have the Authority bonus either.

**Comment by Iamblichos** [comment]
Man I can't reproduce. I set it to 0 on all difficulties with only Honir receiving a bonus.

**Comment by Oscar-IronTower** [comment]
For some reason it seems I'm getting the bonuses set on CIV5HandicapInfos.xml on Sid Meier's Civilization V\Assets\DLC\Expansion2\Gameplay\XML\GameInfo

**Comment by LoneGazebo** [comment]
Changes to XML require a new game, yes.
