### ISSUE TITLE
CTD on mouseover happiness V2

### ISSUE THREAD

**Issue by Fakoleon** [LoneGazebo/Community-Patch-DLL#2291]
Bug Report Template

Mod Version 8/2

1. Mod List (if using standard CPP set, leave blank):

Full VP + EUI
quick turn
faster air craft
info addict
YnAemp

2. Type of error (i.e. crash, interface bug, AI quirk): 

I reported this on previous version, I still have the same issue, it happen after I take the Autocracy policie +25% attack for 50 turn, -50% war weariness modifier, and double razing speed.
Once again I suspect the war weariness modifier to cause conflict.
First time I took this policie, I didn't have CTD on mouseover happiness icone, but after few turn or after reload a save I'm not sure, I had this bug again.
I don't have crash file unfortunately , I'm checking in "Steam\SteamApps\common\CivV"
Here I found files like "civilizationv_dx11_403694_crash_2016_8_6T20_35_13C0.mdmp" but old one, not on the time I had CTD

3. Steps to reproduce:

Mouse over happiness icone

4. Additional information:

I have other issues not related to this one, should I make a new issue thread?
things like, when someone declare war to me, I have my own diplo screen, but empty, like this:

![image 005](https://cloud.githubusercontent.com/assets/14875810/17464078/5ff7b9a6-5cd6-11e6-90cb-3015db465ea0.png)
CTD when entering tech tree (when new turn begin)
etc

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
**Log files: Database.log and Lua.log needed
Minidump file (located in your Civ5.exe directory)**

**Comment by LoneGazebo** [comment]
This has nothing to do with War Weariniess FYI - there's something up with your install.

**Comment by Fakoleon** [comment]
[files_ctd.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/405704/files_ctd.zip)
here is the files, it might contain other games too

The odd thing is that it happen only when I take this policie, otherwise the whole game, I can check happiness normaly.
To be complete, I will add all the small tweak I add.
-Change "Language_en_US" in all mod file to my own language
-in (2) CBO > ComunityOptions.sql, change Purchases in city to 0 and Barbare can steal gold to 0

I always delete all related mod files + the EUI one in DLC folder before install, I don't know what I can change for now, maybe reinstall game in english version? not sure it has something to do with this

**Comment by LoneGazebo** [comment]
You don't have logging enabled.

**Comment by Fakoleon** [comment]
what I have to change to enable it?
I saw debug section in config.ini, not sure it's that 

Enable it, reload save and cause CTD intentionally could help?

**Comment by LoneGazebo** [comment]
yes, enable and make it CTD again.

**Comment by Fakoleon** [comment]
[log_ctdv2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/406982/log_ctdv2.zip)

Ok I think it's good now, tell me if it miss something

**Comment by LoneGazebo** [comment]
I don't see any immediate issues, though you do have a lot of missing text elements in your database log. You play in French, yes? Try switching your language in Civ to English, see if that works (just for testing purposes).

**Comment by Fakoleon** [comment]
Yes I change it to Language_fr_FR
I just tried set the game in english, change back to Language_en_US, reload and try mouse over, it still ctd, I tried different things, also load IGE and delete policie, but still have ctd
I think I should try from a whole new game with game set in english from start, and the 8/8 just came out !
Can't wait to try it anyway !

I post files in case
[log_ctdv3.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/407461/log_ctdv3.zip)

**Comment by LoneGazebo** [comment]
Yeah, changes to language may not take effect until new game. Try in English and report back. Thanks for patience.
