### ISSUE TITLE
SetUpToRangedAttack

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2292]
so i'm trying to rewrite the tactical AI and one thing that's been annoying me for a long time is the fact that some select ranged units (catapult, trebuchet, cannon) need to "set up" before firing.

i get what the mechanic is trying to achieve, namely, prevent siege units from moving and attacking in the same turn, while still giving them good mobility.

but
- it is annoying in the UI ("oh why can't i attack? damn, forgot to set up again!")
- it is difficult to code ("if the units moves over there to attack, assume it's not set up although it is right now but maybe then we don't have enough movement to attack this turn so is it even worth it")

so the question is, can't we have the same effect without the hassle? reduce the early siege units to 1 base move but give them a bonus on roads, for example. might even be more "realistic".

opinions?

**Comment by LoneGazebo** [comment]
Its a big change, though I think an 'if not setup, moves = moves - 1' check should work for that, no?

**Comment by ilteroi** [comment]
i know but it's a good change ... and it only applies to 3 units, so it cannot be so big.

this rule just makes the game more complex without giving an appropriate benefit. unfortunately it's not quite so easy get it right in the code ... for the stuff i'm trying to do.

i'm aware that rolling out the change in the CP might lead to widespread rioting and looting. but having it as an option would defeat the purpose.

so i might just do it on my own, if the resulting AI is good enough, people will see the light. and if it's not, then the experiment failed anyway.

**Comment by LoneGazebo** [comment]
I say try it out, see if you can make it work (roughly) the same way.

**Comment by LoneGazebo** [comment]
In other news, the RNG reduction attempts did not address barbarian desyncs in MP. Still definitely caused by barbs, either at the tactical or the unit level. I have no idea how to fix this.

**Comment by LoneGazebo** [comment]
I did notice this warning: 

Warning	2	warning C4146: unary minus operator applied to unsigned type, result still unsigned	~\Documents\Visual Studio 2008\Projects\CommunityPatch\CvGameCoreDLL_Expansion2\CvGame.cpp	9778

Not the worst problem, as we'll never hit min_int on a random call, but probably worth protecting against just to be safe.

**Comment by ilteroi** [comment]
it's already fixed, just replace the -x by x*(-1)

**Comment by LoneGazebo** [comment]
That's what I did this morning, wasn't sure if that would match your formula changes. Glad to know that's your solution as well! :)
