### ISSUE TITLE
Defensive pacts not shown in UI

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2293]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/2

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Interface bug

3. Steps to reproduce: Defensive pacts aren't shown on the hover over interface. See how in the 1st screenshot, no defensive pact mentioned. However on the regular diplo interface (2nd screenshot), it's shown. (Aztec has one w/ Ottomans) This is confusing because there has been time when I declared war on a civ not knowing and having to re-load an autosave. 

Additionally, when I ask a civ to declare war on a civ they have a defensive pact w/, option is greyed out but no reason given. (when hover over, it should say "has defensive pact w/ that civ", similar to when it says e.g. "you are friends w/ that civ). See 3rd screenshot - you cannot see the cursor for some reason but I was hovering over "montezuma" for declaring war. 

![20160807182306_1](https://cloud.githubusercontent.com/assets/20485377/17465661/379bb908-5ccc-11e6-8e0a-6b9a1f08d7dd.jpg)

![20160807182322_1](https://cloud.githubusercontent.com/assets/20485377/17465665/4f62b406-5ccc-11e6-934a-375d29df3ba1.jpg)

![20160807182333_1](https://cloud.githubusercontent.com/assets/20485377/17465676/8b675056-5ccc-11e6-8874-0f75f0d75939.jpg)

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
The second screen is my work, which is why it is correct. The other two are EUI, which is why they are incorrect. EUI is a quagmire and I don't edit its code any more.
