### ISSUE TITLE
Unable to close Corporations & Monopolies window at the start of a game

### ISSUE THREAD

**Issue by Dretherix** [LoneGazebo/Community-Patch-DLL#2294]
Mod Version (i.e Date - (4/23b)): August 2nd (1.8.2)

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Corporations & Monopolies window appears immediately at the start of a game and I'm unable to close it. 

3. Steps to reproduce: 

4. Additional information: I've read that this was an issue with JDF mods, so I've tried just using the CPP mods, but it still occurs. I used the Vox Populi automatic installer when installing CPP. 

---------------------------
Supporting information:
[CPP Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/405892/CPP.Logs.zip)

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Delete any mods in your mods folder not enabled, clear cache, try again.

**Comment by Dretherix** [comment]
That worked. Thanks!
