### ISSUE TITLE
Sovereignty requests

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2296]
I notice that you're getting through updates in rapid succession, so just in case they are a precursor to a slowing down of updates, I thought I'd throw in three requests for Sovereignty that I've been sitting on (I've implemented the majority of reform effects now, which is where the requests crop up).

**TradeRouteLandDistanceModifier** for the Policies table.
**TradeRouteSeaDistanceModifier** for the Policies table.

These tags exist in the Buildings table, so hopefully a simple matter of copying them over.

**EspionageModifier** for the Policies table.
Ditto the above. The tag (though as GlobalEspionageModifier) exists in the Buildings table.

Thanks, and no rush!

**Comment by LoneGazebo** [comment]
Done!
