### ISSUE TITLE
Insane Stream of Barb Horsemen out of nowhere

### ISSUE THREAD

**Issue by dylanstrategie** [LoneGazebo/Community-Patch-DLL#2299]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 

8/8 (Latest, using Auto Installer)

1. Mod List (if using standard CPP set, leave blank):

Full incl. EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 

Somehow, the Barbarians are generating 1+ (sometimes a group streams out of the forest) Horsemen per turn, along with the occasional Archer, and throwing them in my capital. This has been going on for somewhere around 15 to 20 turns, yielding multiple dozen of Horsemen and total devastation

3. Steps to reproduce:

Completely unsure. Wait for a CS to be taken over by Barbs, then wait a while for something ?

4. Additional information:

Vancouver was taken over a long while ago, since CS being taken over by Barbs is hilariously common and I just don't care much anymore

The bug happened a significant while after the Barbs officially took over the CS, and I only killed a stray Spearman on Barb capture. This must have been as much as 50 turns later

After a while I simply stopped playing since it was just going to be an endless uphill battle to simply stop the Barb Horsemen from draining everything every turn by slamming my capital, so that's a pretty serious issue

This was on Epic speed, Warlord difficulty, Standard map, no special settings outside of Time victory disabled

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

Logs + Minidump + All auto saves up to that point (was already late into the bug, but every single save should have the problem. I quit on the last one)

[Logging.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/407102/Logging.zip)

Just before closing the game, to show the effects of the bug. This is the case where a group of Horsemen streams out of somewhere (presumably the forest)

![20160808164058_1](https://cloud.githubusercontent.com/assets/6137403/17484387/d8448e4e-5d89-11e6-94e3-98e4348975ff.jpg)

**Comment by LoneGazebo** [comment]
I fixed a bug a few versions back that was keeping barb cities from spawning barbs. Now they can spawn barbs! Not a bug.
