### ISSUE TITLE
Statue of Emperor Augastus great work of art

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#230]
When you create it the game displays Rome leader scene picture ( augustus.dds ). I guess augustusstatue.dds has to be renamed to fix it.

**Comment by qqqbbb** [comment]
The same thing happens with ashurbanipalstatue.dds.

**Comment by qqqbbb** [comment]
You decided not to fix this?

**Comment by LoneGazebo** [comment]
I did fix it. 
G
