### ISSUE TITLE
trade deals and embassies 

### ISSUE THREAD

**Issue by NuttSo** [LoneGazebo/Community-Patch-DLL#2300]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-8

1. Mod List (if using standard CPP set, leave blank):
Info addict 
Reforestation 
IGE
Faster aircraft animation 
really advanced setup

2. Type of error (i.e. crash, interface bug, AI quirk): 
I am still having the same issues as before, trade deals get stuck ~~and I lose my embassies without DOW~~.

3. Steps to reproduce:

4. Additional information:
So far (200 turns) I have only noticed one deal get stuck 

![20160808220550_1](https://cloud.githubusercontent.com/assets/20857721/17492564/032c00bc-5db5-11e6-9637-09ec55051d07.jpg)

savegame at this stage 

[Haile Selassie_trade_deals_embas.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/407562/Haile.Selassie_trade_deals_embas.zip)

thanks 

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Re: embassy, looks like you still have it (as it is highlighted on your end).

**Comment by NuttSo** [comment]
yea you are right about embassy my bad ,sry
