### ISSUE TITLE
Captured AI Settler gets re-captured as a worker

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2301]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
August 8th

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
During my exploration of the map I crossed path with the Celts and took one of their Settlers to try to stop their forward expansion. Seeing a Pictish warrior closeby I moved my scout away and left the captured settler, now a worker of mine, alone. Next turn it was reported as "killed" in the notification and I quickly returned to see what happened.

3. Steps to reproduce:
This save is at a position with my Scout on the same tile as the Celtic Settler and if I declare war I capture it and can quickly retreat from the Pictish Warrior.
Next turn it is re-captured.
[Pedro II_0041 BC-2360.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/408058/Pedro.II_0041.BC-2360.zip)

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Iamblichos** [comment]
Isn't that how vanilla game works?

**Comment by LoneGazebo** [comment]
That is how it is supposed to work.

**Comment by GrantSP** [comment]
Really?! How come the player can get it back as a settler but the AI can't?

**Comment by GrantSP** [comment]
Since it is a vanilla oddity there is little reason to keep this open.
I've played so little vanilla and rarely have I seen this occur I just assumed.
