### ISSUE TITLE
Using gold doesn't purchase buildings

### ISSUE THREAD

**Issue by Dretherix** [LoneGazebo/Community-Patch-DLL#2302]
Bug Report Template

Version: August 2nd (1.8.2)

1. 
In addition to CPP, subscribed but not enabled.
Leugi's Musica Civilization
MC's Gallic Civ
More Frequent World Congress v.1
Promotions - Ancient Ruins Choice v.2
Promotions - Expansion Pack v.9
Really Advanced Setup v. 15
Reseed! v.11
Starting Worker v.1
Sukritact's Nabataean Civilization v.2
Units - Starting Scout v.1
Wonder Race v.4

2. 
Apologies, I posted an issue last night that was solved immediately, so I tried to troubleshoot this one more, but I'm still stuck. At the moment, using gold to purchase buildings does nothing. When I click the button, it removes the gold from my treasury, but I don't get the building. I tried deleting the cache, which is what solved my issue last night. I've also tried removing the list of subscribed by not enabled mods above so that I just had CPP, but I still can't get it work. I listed them just in case. Sorry if I'm missing something obvious; I only have about 1 hour to play after work and I would love to get this working. Thanks for your help!

3. I just quick start a game and wait until I have 70 gold to test.

4. Additional information:

[CPP Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/408083/CPP.Logs.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by pandasnail** [comment]
In CPP, buying with Gold doesn't purchase the building outright, it only does 50% (or so? not sure exact) You still have to produce through hammers the other 50%.

**Comment by Dretherix** [comment]
Ah, I see. However, nothing seems to be happening at all in my game. For example, let's say the shrine says 9 turns to complete. When I spend the 70 gold, it still says 9 turns. Does it just not have as much of an effect in the early game?

**Comment by pandasnail** [comment]
Oh...I see. Does it maybe show the turns halved the next turn? Sometimes cached stuff can be weird I think, If not, this issue's above my head, sorry,

**Comment by Dretherix** [comment]
... You know, I didn't wait until the next turn to see. I'll test it right now and update.

**Comment by Dretherix** [comment]
Son of a....

You don't even need to wait until the next turn; you just have to close the city window. If you click the button and leave the window open, the change doesn't register. However, if you close it and open it again, it shows the production time cut in half, like you said. 

Feel like an idiot, but thanks for responding.
