### ISSUE TITLE
Intentional Venice Nerf on Events?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2303]
Venice can't have access to PLAYER_EVENT_BANK_DECISION_CHOICE_1 nor PLAYER_EVENT_DEATH_MERCHANT due to the improvement requiring a Custom House, not a Venetian Custom House.

**Comment by LoneGazebo** [comment]
Not intentional, no. May need to rethink the requirement.

**Comment by TechpriestEnginseer** [comment]
Why not just make the Venice UA boost the yields of the Custom House improvement itself rather than making a new one?

**Comment by LoneGazebo** [comment]
Can't do that cleanly. Also can't make it give land etc without special snowflake code.
