### ISSUE TITLE
event request

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#2304]
Oh Great One,

I was wondering if `<FreeGreatPeople>` could be made to work like the Mayan bak'tun choice, whereby Great Prophets cannot be chosen before a Religion has been founded or the renaissance?

Many thanks

**Comment by LoneGazebo** [comment]
No, as the baktun element is completely unique and independent (and there's no filter for the UI for GP selection). Sorry!
