### ISSUE TITLE
Multiplayer Modpack Shoshone

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2309]
I know this has been a problem with the Pathfinder picking goody when they find a ruin and that it causes desyncs ever since whoward introduced this into his DLL and pick n mix, but is there any reason we can't fix this for multiplayer without a workaround?

**Comment by LoneGazebo** [comment]
I don't think there's a network/dll channel for the Shoshone pick. That's the problem. No way to send that data through the dll as we don't have access to the networking channels.

**Comment by LoneGazebo** [comment]
There are a couple of elements in Lynnes's modpack you should include I yours - they are mods that keep the Shoshone etc from causing desyncs.

**Comment by LoneGazebo** [comment]
@Iamblichos 8-9 Hotfix uplaoded, has your changes. For next modpack (sorry for flurry of modpack requests), grab the mod fixes from lynne's modpack for shoshone/GP selector desyncs.

Thanks!

**Comment by El-SiD** [comment]
Correct me if i'm not right, but in vanilla shoshone pathfinder works perfectly. What changed in CPP ?

**Comment by Iamblichos** [comment]
What the above poster said? I will include Lynne's fixes. But why does it work in vanilla?

**Comment by LoneGazebo** [comment]
MP pathfinder in vanilla caused desyncs.

**Comment by Iamblichos** [comment]
I don't recall that at all actually...but let's move forward. Maybe we should redefine that unit so we don't have to change its nature for multiplayer. That would be the best case I think.

**Comment by Iamblichos** [comment]
Badass! I love stuff I like this. I think I made a mental note of that page a while back but slept since then.

**Comment by LoneGazebo** [comment]
I'm shite with lua (well, less shite than I used to be, but whatever) - you want to take point on this? It doesn't seem too bad - just gotta build a table for all possible goody hut options and all possible GPs. Then make custom lua for the GP and Goody selector UIs that send those values across (instead of using the standard network code).

**Comment by Iamblichos** [comment]
Yeah I'll take point on this. Don't know when I'll get to it exactly, but I'll getter done.

**Comment by LoneGazebo** [comment]
Cool. In the meantime, I'd include Lynnes's modmods in your modpacks (otherwise we'll keep getting desync complaints).

**Comment by Iamblichos** [comment]
Yep I found them. Hopefully it's inclusive of changes of all GP changes since he last made the modpack.

**Comment by LoneGazebo** [comment]
I think so - I don't think I've added any 'free GPs' anywhere else. Well events, but choice events won't work in MP.

G
