### ISSUE TITLE
The game forces you to choose production for cities that are being razed

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#231]
Tried fixing it by editing PuppetCityPopup.lua. ```newCity:SetProductionAutomated(true)``` did not work but ```newCity:PushOrder (OrderTypes.ORDER_TRAIN, GameInfo.Units["UNIT_WORKER"].ID, -1, 0, false, false)``` did. It also should be fixable by editing dll source code.

**Comment by qqqbbb** [comment]
Tried fixing it with Lua. City:SetProductionAutomated(true) did not work but ```newCity:PushOrder (OrderTypes.ORDER_TRAIN, GameInfo.Units["UNIT_WORKER"].ID, -1, 0, false, false)``` did.

**Comment by LoneGazebo** [comment]
Is this a feature request?
G

**Comment by qqqbbb** [comment]
I think it's annoying and should be fixed. And fixing it in dll is better than editing PuppetCityPopup.lua.

**Comment by Radost** [comment]
You can stop razing at any time, but I agree, building queue should pop-up after the resistance period.
