### ISSUE TITLE
Pedia entries related to city connections.

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2310]
There are a couple of anomalies with the pedia regarding city connections over sea.

- Lighthouse text makes no mention of needing a lighthouse in the capital, or I'm assuming another city on the same landmass, as well as the city in which it is built.
- "Game concepts\Connections" still refer to harbours as a means to connect cities.
- "Sailing" should also list 'establishes a city connection across water' as one of the unique actions.

**Comment by LoneGazebo** [comment]
Sailing doesn't enable city connections across water - Lighthouses do that. I'll fix text issues.

**Comment by GrantSP** [comment]
@LoneGazebo I should point out I could make a lot of these changes but I've noticed the way you do your updates tends to overwrite all my changes.
I tend to make a lot of small commits focused on just one or two items, you tend to wait and do a monolithic commit.
Most, if not all, of my minor edits have been reversed overtime simply because of this.

**Comment by LoneGazebo** [comment]
Weird. Make an Issue when you make an update so I make sure and grab master before merging.

**Comment by GrantSP** [comment]
That's the weird thing though Git, or the GitHub app, should flag any changes in your master copy before you're allowed to make a commit.
No big deal though, the amount of commits I make don't warrant a change in your workflow.
