### ISSUE TITLE
Mayan Atlatl

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2311]
Strategy text says this:

> The Atlatlist is the Mayan unique unit, replacing the Composite Bowman. **Atlatlists are both cheaper than a Composite Bowman**, available earlier, and gains bonus damage from attacking wounded units. This advantage allows your archers to engage in hit-and-run skirmish tactics.

However the cost to produce them is identical.
Is the text or the database cost wrong?

**Comment by LoneGazebo** [comment]
Should be cheaper. I fix,
