### ISSUE TITLE
AI puppeting its own city

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2312]
![image](https://cloud.githubusercontent.com/assets/1358966/17543750/1a264e7a-5ed3-11e6-9617-affeb8a44665.png)

i liberated sao paulo for the brazilians about 100 turns ago. they puppeted it (strange decision in the first place) and have kept it that way since ...

**Comment by LoneGazebo** [comment]
If happiness is an issue they'll do this. Eventually might return it to normal status.

**Comment by LoneGazebo** [comment]
Oh wait I see. It was their city. They shouldn't need to.
