### ISSUE TITLE
Authority Honor Policy doesn't give units to cities in Resistance

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2314]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/9 (started with 8-8-1 tho)

1. Mod List (if using standard CPP set, leave blank):
Full VP
Enginseer's version of Events and Decisions and its add on
Enlightenment Era and Xony's Compat mod
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Redesigned Colors and Icons
Celtic City Names, Iroquoian City Names, Randomize City Names
NoAltitudeTraining (removes the Mt. Kilman promo)
My own thing that does various things SQL type stuff
Tectonic Map

2. Type of error (i.e. crash, interface bug, AI quirk): If cities are in resistance when Honor is chosen the ones already 8 don't get a free unit. And this matters  because there's an event, I think its one of Enginseer's admittedly not yours, called Social Reforms, that gives a ton of culture in exchange for resistance.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
I fix.
