### ISSUE TITLE
No notifications (who build what ans such things)

### ISSUE THREAD

**Issue by Kitsuu** [LoneGazebo/Community-Patch-DLL#2316]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

1. Mod List (if using standard CPP set, leave blank):
CP
CBO
C4DF - CBP
More Luxuries
City Limits
Buildings- upgrade system 
More active religions
More great musicians
More great works
Promotions Expansion pack
Quick turns
RED modpack
RED Xtreme
Reforestation
TreeGrowth

2. Type of error (i.e. crash, interface bug, AI quirk): 
Interface bug

3. Steps to reproduce:

4. Additional information:
It's not game breaking, but kind of annoying as I don't know if a wonder has been built already. Everything seems to work fine other than the fact that I get no notifications of events at all (I do get those events with choices of what to do with what happened.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict. Remove all mods except for VP set, then re-add them until you find the one causing it.

**Comment by pandasnail** [comment]
I don't see either of the comparability mods on your modlist, and if you really aren't using one, that's likely the problem

**Comment by pandasnail** [comment]
Didn't see Gazebo posted before me-listen to his advice always.

**Comment by Kitsuu** [comment]
Okay I found it. It was Tree growth. I don't know why though. BTW I know this is no place to ask, but in the original game without mods I used to play at King level, what about your mod? Which level do you recommend to someone at my level?:D

**Comment by Iamblichos** [comment]
Give Prince a shot

**Comment by Kitsuu** [comment]
Okay thanks.
