### ISSUE TITLE
Barbarian spawn rate very low

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#2317]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
Full package 8-9, but it was also there in 8-8-1

1. Mod List (if using standard CPP set, leave blank):
A lot as you know but I'm rather confident it's not related (at least none of them mod BARBARIAN_CAMP_ODDS_OF_NEW_CAMP_SPAWNING from GlobalDefines.xml)

2. Type of error (i.e. crash, interface bug, AI quirk): 
??

3. Steps to reproduce:
Just play I guess

4. Additional information:
It seems that the Barbarian spawn rate is **very low** in the last release. I hardly see any barbarian camps at all. You mentioned on the forums that Ilteroi introduced a new RNG system which may be related?

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by ilteroi** [comment]
i'll check - also seems like you can end up in an endless loop - need to rearrange a few things

**Comment by ilteroi** [comment]
ok should work now. the simplified RNG kept retrying the same plot over and over, even if it wasn't suitable for a camp

**Comment by skodkim** [comment]
Any chance of a hotfix or release? It kind of removes one of the fun elements from the game? Plus playing on Deity without the occasional gold from encampments is rather hard :cry:
