### ISSUE TITLE
Player:GetBaseBuildingMaintenance() and Player:GetBaseUnitMaintenance() Request

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2319]
Basically it grabs the maintenance that is the original and unmodified value by policies or buildings.

**Comment by TechpriestEnginseer** [comment]
No...?

**Comment by LoneGazebo** [comment]
I wasn't sure what you were asking.

GetBuildingGoldMaintenance already exists for Player.
CalculateUnitCost also already exists.

If you want the base value, I can work on that.

**Comment by TechpriestEnginseer** [comment]
Yeah basically, but one of my mod uses a dynamic maintenance modifier from dummy buildings and policies, but I need the original maintenance value added from all cities to help users with the tooltips when they decide to build this or enact this policy.
