### ISSUE TITLE
AI unit danger evaluation

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#232]
In my current game this happened: 
AI that I was at war with founded a city when its settler was surrounded by 3 of my units. On the next turn warrior that was protecting the settler moved out of the city, leavng it unprotected. So AI determined that it was not safe for its warrior to stay in the city but could not determine that it was not safe to found the city in the first place.

**Comment by LoneGazebo** [comment]
One odd behavior does not a bug make. If this is a repeat offense, sure, but things happen sometimes.

**Comment by qqqbbb** [comment]
AI also often sends his settlers to found cities without escort.

**Comment by LoneGazebo** [comment]
Now that is a known problem - I'll look into it.
