### ISSUE TITLE
"Request help"

### ISSUE THREAD

**Issue by Kitsuu** [LoneGazebo/Community-Patch-DLL#2320]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

1. Mod List (if using standard CPP set, leave blank):
CP
CBO
C4DF - CBP
More Luxuries
City Limits
Buildings- upgrade system
More active religions
More great musicians
More great works
Promotions Expansion pack
Quick turns
RED modpack
RED Xtreme
Reforestation

2. Type of error (i.e. crash, interface bug, AI quirk): 
Diplomacy

3. Steps to reproduce:

4. Additional information:
The option of "request help" is not replacing the "demand" on civilizations where I have a friendship. Does it require certain Age or technology?

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
You probably have a lua conflict with another mod - guess is that you are missing a compatibility pack for the VP.

**Comment by Kitsuu** [comment]
I can't tick it on because I'm not using EUI.

**Comment by Kitsuu** [comment]
uhm hello?

**Comment by LoneGazebo** [comment]
You need the no EUI compatibility pack.

**Comment by Kitsuu** [comment]
Well i used the installed, i`ve put the EUI now, and i`ve been trying to tick on the EUI patch but it says i`m missing required dependency, also the community patch and community balance overhaul have no LUA folders to delete!

**Comment by LoneGazebo** [comment]
Delete everything. Use auto installer. Do full install. Should work.

**Comment by Kitsuu** [comment]
It`s working now. Thank you sir.

**Comment by LoneGazebo** [comment]
Yep!
