### ISSUE TITLE
Promotion names that have a value as part of their name

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2321]
- **Bonus vs Gun(Melee)(25)** -- text says the bonus is only 20 -- also is this a %?
- **Combat Bonus in Forest/Jungle (33)** -- appears twice in the promotion pedia list.
- **Bonus vs Cities (200)** -- text says "+100% Bonus vs Cities"
- **Bonus vs Cities (300)** -- text says "+150% Bonus vs Cities"
- **Bonus vs Cities (50)** -- text says "Bonus vs Cities (50)" -- is this also a %?
- **Bonus vs Armored (25)** -- listed twice and both say they give "Bonus vs Armored (25)" yet one is shown as prerequisite for the other
- **Bonus vs Helicopters (150)** -- text makes no mention of the value of the bonus
- **Interception (20),(40),(50),(100)** -- the text should make mention that this is % to the "chance of interception" not the similarly named promos that increase CS

I know most of these are defined in the vanilla game but if we could make some adjustments to make them easier to discern, it might help a little.

If things like the **Bonus vs Helicopters (150)** one are straightforward I'll make these changes, but some of the more obscure ones may need attention.

**Comment by LoneGazebo** [comment]
Hmm, yeah, we just need to make those match up. I think your judgment is fine on these, truth be told.

**Comment by GrantSP** [comment]
I'll give 'em a go.

**Comment by LoneGazebo** [comment]
How did we end up on this?

**Comment by GrantSP** [comment]
Ah... well... not too far I'm afraid.
I've been involved with a lot of other matters lately and frankly lacked the motivation to actually do any work on it aside from noting some promotion names from Civ VI that we may steal/borrow/appropriate.

As for names that aren't easily changed it largely comes down to not being sure what the bonus actually does, the descriptions are vary vague or non-existent.

**Comment by LoneGazebo** [comment]
Well, so long as our current promotions are not incorrect, I say we leave it as-is.

**Comment by GrantSP** [comment]
I'll get around to it... eventually, so yeah need to do anything on your part, more important matters for you to do I'm sure.

**Comment by Iamblichos** [comment]
I can tell you, since these are vanilla descriptions, that they are all %'s.

**Comment by TechpriestEnginseer** [comment]
I'll actually try and work on this to rename these promotions.

**Comment by LoneGazebo** [comment]
I believe this is solved.
