### ISSUE TITLE
Everlasting Youth Promotion with no Natural Wonder

### ISSUE THREAD

**Issue by glaivemaster** [LoneGazebo/Community-Patch-DLL#2322]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8/12

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Wrong promotion type - Scout could pick the "everlasting youth" promotion (from Fountain of Youth?), but I haven't discovered any natural wonders at all.

3. Steps to reproduce:
Promoted scout from exploration, haven't tried with other units

4. Additional information:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/414762/Logs.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by AnastaseAlex** [comment]
Same error here.

**Comment by glaivemaster** [comment]
Having played further into the game, the Fountain of Youth **is** present on the map, don't know if that plays into it.

**Comment by GrantSP** [comment]
Should be fixed now for the next release.
It was missing the "cannot be chosen" tag.

**Comment by LoneGazebo** [comment]
Ah forgot to transfer that to release. I'll hotfix today.
