### ISSUE TITLE
Floating Garden and Well from Pioneer

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#2324]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/12

1. Mod List (if using standard CPP set, leave blank):

FlagPromotions (v7)
Historical Religion Edit (v45)
JFD's Cultural Diversity (v9) & soundtrack (v1)
UnitPath Viewer
UI - Promotion Tree
Unique Cultural Influence

2. Type of error (i.e. crash, interface bug, AI quirk): 

Playing as Aztec, floating Garden and well are both represent in a city found by Pioneer

3. Steps to reproduce:

Found city by pioneer as Aztec.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
http://images.akamai.steamusercontent.com/ugc/270600083981982505/DE729199225073414145C9F16BA1329482E29F66/

**Comment by GrantSP** [comment]
A Floating Garden is a type of Watermill so it is one of the buildingclasses that are built.
Grove, Granary, Market, Monument, Shrine, Barracks, Watermill, Library, Forge and Well.

**Comment by XplosiveLun** [comment]
Floating Garden normally cannot be built in city with well. So I thought it would be a balance issue.

**Comment by GrantSP** [comment]
Hmm... good point. The description for it says it replaces a watermill but it doesn't explicitly say having a well in the city invalidates it. What's more interesting to me is your screenshot seems to show there being no river or lake in that city. Is that the case?

**Comment by XplosiveLun** [comment]
No, that's not the case. Floating garden can be built anywhere unlike its counterpart. In this case, supposedly, you can't build floating garden after a well. You could only have either one.

**Comment by LoneGazebo** [comment]
It is fine - floating garden does not use rules of watermill, but benefits based on it,
