### ISSUE TITLE
Desync Loops in Multiplayer

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2326]
@ilteroi not sure if these are being caused by the new RNG or not, but the reports are to use 8-2 modpack (without barbarians). 8-9 seems to be causing lots and immediate desyncs.

http://forums.civfanatics.com/showthread.php?t=572558

**Comment by Iamblichos** [comment]
Yeah I just tried it myself. Can't get out of Turn 0, just constant looping of desyncing. Both barbs and no-barbs.

**Comment by ilteroi** [comment]
that sounds bad ... logs would be nice

**Comment by Iamblichos** [comment]
Logs this post: 
http://forums.civfanatics.com/showpost.php?p=14393185&postcount=12

**Comment by LoneGazebo** [comment]
Ilteroi, possible that the game m_i value you are referencing in random differs from player to player?

**Comment by Iamblichos** [comment]
I just loaded up a duel game no AI players, you can get past turn 0: 

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/416622/Logs.zip)

**Comment by Iamblichos** [comment]
Okay now Tiny map 2 AI and 2 Human players, desync loop turn 0 after you hit next turn:

[LogsTiny_2AI_2Human.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/416629/LogsTiny_2AI_2Human.zip)

**Comment by Iamblichos** [comment]
[LogsTiny_2AI_2Human_NoEvents.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/416632/LogsTiny_2AI_2Human_NoEvents.zip)

Same as above post, except I disabled events system. Results were the same.


In all my instances this morning Active Diplomacy is off in the DLL.

**Comment by Iamblichos** [comment]
Seems like if there is a mix of AI players and more than 1 human player it craters. If 2 human players only, it gets past turn 0.

**Comment by LoneGazebo** [comment]
My guess regarding the m_i value referenced in the RNG stands. I think it might be that. Essentially the new RNG has the same issue as the old seed issue.

**Comment by Iamblichos** [comment]
Yes but compounded. Now players can't get past turn 0 even.

**Comment by ilteroi** [comment]
@g: don't know what you mean exactly ... anyway the log shows differing random seeds (in jonRand) so it's more likely that the branch in CvGame::getRand() isn't working perfectly

**Comment by Iamblichos** [comment]
Not sure what you mean is this a config option or some core debugging in custommods.h?

**Comment by LoneGazebo** [comment]
Config option.

**Comment by Iamblichos** [comment]
K. Don't have time at the moment to setup a game on my comps but will deliver the goods tonight or tomorrow.

**Comment by LoneGazebo** [comment]
Cool. I'm thinking, @ilteroi, that the use of the global averages may be causing the problem. Those values can change during every player's turn, as the game function is called by all players during their respective turn. Perhaps we should add an 'ifmultiplayer and ifhost' check to those functions so that they only update on the host's machine?

**Comment by Iamblichos** [comment]
I have not forgotten about his. Just been delayed working on changes to DLL fixes and other additions.

**Comment by Iamblichos** [comment]
Sorry to ask again, but what is the variable I need to turn on in config.xml:

; Enables stack-trace collection on random number generators and FAutoVariables. Slightly slower and uses more memory
EnableOutOfSyncDebugging = 0

or 

; Random seed for game sync, or '0' for default
SyncRandSeed = 0

???

**Comment by LoneGazebo** [comment]
If you have logging enabled generally it should give you a netmessagedebug log.

**Comment by Iamblichos** [comment]
Yeah that log is provided in my zip files above.

**Comment by Iamblichos** [comment]
I see the variable that is causing out of sync.

**Comment by ilteroi** [comment]
so, which variable is it?

@g: may be i went a bit overboard with the sources of randomness i tried to pull in. should be easy to remove and retest. on the other hand, i checked it and the global averages seem to be updated only once per turn (in CvGame::doTurn())

**Comment by LoneGazebo** [comment]
That's when they're updated in SP, however in MP cvgame runs for all players and is 'sync'd' up - variable wise- if there's an error.

**Comment by ilteroi** [comment]
good point

**Comment by Iamblichos** [comment]
Starts here in the log labeled above LogsTiny_2AI_2Human.zip: 
[265873.703] DBG: Unit out of sync. Player=1, Name=Warrior, id=1285, X=17, Y=10
Variable Out Of Sync : CvUnit::m_iX


[265873.703] DBG: Unit out of sync. Player=1, Name=Warrior, id=1285, X=17, Y=10
Variable Out Of Sync : CvUnit::m_eFacingDirection


[265873.703] DBG: Unit out of sync. Player=1, Name=Warrior, id=1285, X=17, Y=10
Variable Out Of Sync : CvUnit::m_iEverSelectedCount


[265873.703] DBG: Unit out of sync. Player=1, Name=Warrior, id=1285, X=17, Y=10
Variable Out Of Sync : CvUnit::m_eActivityType


[265873.703] Net RECV (1p, 2c) : size=1200: Message chunk 1 of 3 for type 110
[265873.703] Net RECV (1p, 2c) : size=1200: Message chunk, 1 remaining
[265873.703] Net RECV (1p, 2c) : size=378: Message chunk, 0 remaining
[265873.703] Net RECV (1) :NetPlayerSyncCheck(Player=1), ArchiveDataSize=2742
[265873.703] DBG: Variable Out Of Sync : CvPlayer::m_iCapitalCityID

Game Turn : 0
[265873.703] DBG: Variable Out Of Sync : CvPlayer::m_paiUnitClassMaking
[265873.703] Net RECV (1) :NetRandomNumberGeneratorSyncCheck(Player=1, RandomNumberGenerator(seed=908677486)
[265873.703] DBG: Game Random Number Generators are out of sync : local.seed=4342466455451074287, remote.seed=6052798579669029230
	local.callCount=1523, remote.callCount=722
	local.resetCount=1, remote.resetCount=1

**Comment by LoneGazebo** [comment]
The unit variables are innocuous - the RNG is the issue.

**Comment by Iamblichos** [comment]
Yeah it shows the RNG seeds are different local to Player

**Comment by LoneGazebo** [comment]
Yeah, it is definitely clear that the RNG is the culprit.

**Comment by ilteroi** [comment]
nah, the RNG is the victim. one side calls it more often then the other. the question is when and why.

**Comment by LoneGazebo** [comment]
You could use totalpop + total # of cities as your variables.

**Comment by ilteroi** [comment]
maybe i have an idea ... barb camp spawning depends on the number of visible plots. in a multiplayer game with simultaneous turns, that number might be slightly different for each player .... and boom.

does that sound plausible? wouldn't know what to do about it though - counting unrevealed plots has the same problem

**Comment by ilteroi** [comment]
re: pop and cities - both change when a city is founded. but i think there's a good way, i'll force the caller to supply a seed.

**Comment by LoneGazebo** [comment]
Sounds good, let me know when your idea is pushed and I'll merge it up.

**Comment by ilteroi** [comment]
ok - it's pushed - give it a try

the visibility problem is still there though. if it's real - but then there would be several similar issues in other places

**Comment by LoneGazebo** [comment]
Yeah, EUI can also be a culprit.

**Comment by LoneGazebo** [comment]
I'm not seeing push - part of two prior pushes?

MP works like Single Player, in that all players run commands for all AI/Game elements. If at any point an AI/game element goes out of sync (i.e. client action does not match host action, etc.), a resync screen appears. It is incredibly dumb.

**Comment by ilteroi** [comment]
yeah, it's in the next-to-last commit. check the message.

anyway, about MP. aren't there multiple modes for MP? sequential, simultaneous, hybrid? the above would seem to describe simultaneous mode, sequential would be easy i guess. has anyone tested if it makes a difference?

so let's assume we have 4 players. A & B are human, C & D are AI. the turn begins. A makes his moves, and B makes his moves at the same time. C & D make their turns on A's machine and on B's machine independently.

now the important question is, when does the synchronization happen? 

solution A: once everyone has ended their turn, the "results" are compared. but how can they ever agree? the AI players have totally different inputs on the two machines! that would really be exceptionally stupid. and fact, that would make me give up on MP.

solution B: once all human players have ended their turn. but then how can there ever be a desync? all AI players have by definition the same inputs, including the random seeds. is there a downside here i don't see?

solution C: ???

**Comment by Iamblichos** [comment]
Yea you are totally right. And simultaneous is not "Civilization". Simultaneous is "Starcraft Civilization without Starcrafts incredible UI to comtrol multiple units at once so let's see who can use their index finger the fastest."

All my logs above were from simultaneous because that's what most people play. But let me try sequential and see what the results are. I've already incorporated your latest changes into my own so let me see what it does.
