### ISSUE TITLE
Medieval era policy trees are available right after filling the ancient one

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2327]

**Comment by LoneGazebo** [comment]
That's intentional. The tooltip highlights that.

**Comment by Radost** [comment]
What tooltip?
![8930_20160813015638_1](https://cloud.githubusercontent.com/assets/1131228/17637338/69332742-60fc-11e6-9b71-67979ed142a7.png)

**Comment by LoneGazebo** [comment]
Look at the tooltip for the locked branch  'unlock' buttons – they say how many policies you need, and how to unlock them.
