### ISSUE TITLE
CityStateDiploPopup.lua

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2328]
check typo on line 725 reads:

`if (minorPlayer:IsMinorCivDisplayedQuestForPlayer(activePlayerID, MinorCivQuestTypes.MINOR_CIV_QUEST_UNIT_GET_CITY)) then`

should be:

`if (pMinor:IsMinorCivDisplayedQuestForPlayer(activePlayerID, MinorCivQuestTypes.MINOR_CIV_QUEST_UNIT_GET_CITY)) then`

this is in NON-EUI compatibility files...not sure about EUI...might want to check that one too.

**Comment by LoneGazebo** [comment]
EUI uses pMinor, no-EUI uses minorPlayer. Because bc1 felt he had to change everything for fun. :/

I'll fix.

**Comment by Iamblichos** [comment]
I'm telling ya we should just make our own version (what we need and want) so we don't have everything going through that dumb core library. That thing is a hog.

**Comment by LoneGazebo** [comment]
Its something for sure. But boy golly do I hate interface work. Also bc1's made it clear that he does not want mod mods of EUI (we had quite the fight about my compatibility files being an 'infringement' on his code).

**Comment by Iamblichos** [comment]
Yeah but he doesn't have a monopoly on making UI interfaces for civ 5....I mean scrap the whole EUI. we don't have to copy his work. Just make our own(what we need).

**Comment by Iamblichos** [comment]
The other advantage of doing this is getting completely rid of the EUI and non-EUI versions.

**Comment by LoneGazebo** [comment]
We could. But people like EUI. A lot. And that's hard to break. People are stubborn, and most would still want EUI. :)

**Comment by Iamblichos** [comment]
Then we give them what they want without being EUI and without using any of his code. You know that thing is a POS.

**Comment by Iamblichos** [comment]
Btw- I still get late game crashes from it that break on the EXE and the UI thread.

**Comment by LoneGazebo** [comment]
Yeah. We could do an exploratory post asking users what the 'most essential' aspects of EUI are. Go from there.

**Comment by LoneGazebo** [comment]
EXE and the UI thread?

**Comment by LoneGazebo** [comment]
We could make an exploratory post regarding the 'essential' features of EUI, see what users really or feel necessary.

**Comment by Iamblichos** [comment]
Yes

**Comment by LoneGazebo** [comment]
Yes to what? Also, mind re-linking the crash? I haven't had a late-game crash in forever.

**Comment by Iamblichos** [comment]
Yes to making an exploratory post.

**Comment by LoneGazebo** [comment]
Gotcha.

**Comment by Iamblichos** [comment]
Yeah I don't have crash now but it's from actually playing the game and hovering over a city banner or picking a unit etc. usually involves a lot of data on the screen.

**Comment by Iamblichos** [comment]
Next time I have it again I'll let you know.
