### ISSUE TITLE
Messed up Trade Interface

### ISSUE THREAD

**Issue by nOxrax** [LoneGazebo/Community-Patch-DLL#2330]
Version: August 12th (8/12)
CP Hotseat

When going into the Trade Interface to deal with another Civ the Interface is messed up with, for example, the American Civ icon displayed for every different Civ and a lot of random text displayed in the deal field.

This is a recurring bug that has been present, and fixed, in several previous versions of the mod. I have made a clean install, cleared cache and I have no other mods it could conflict with.

**Comment by LoneGazebo** [comment]
I need Lua log. If logging not enabled , enable it and recreate bug, then post log.

**Comment by Branbados** [comment]
I have the same issue, and have also made a clean install and cleared the cache. I have a few mods, but none are enabled besides the basic community patch when this bug occurs.

http://pastebin.com/ukcScuWC

![image](https://cloud.githubusercontent.com/assets/21012396/17645042/82ece55e-614e-11e6-8f99-c29a8b2186d5.png)

**Comment by nOxrax** [comment]
I posted the log, and this entry might be the key:

[257609.437] Runtime Error: C:\Users\sven\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\LUA\TradeLogic.lua:946: attempt to index field 'DenounceButton' (a nil value)


[Lua_trade bug.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/416937/Lua_trade.bug.txt)

**Comment by LoneGazebo** [comment]
Ah are you just using the CP alone?

**Comment by LoneGazebo** [comment]
For now just delete the CP's Lua folder
