### ISSUE TITLE
Event Linkers

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#2331]
My events don't seem to be obeying the linker tables.

`<Event_EventLinks>`
`		<Row>`
`			<EventType>EVENT_AES_WAR_PLAYER_GOOD</EventType>`
`			<EventChoice>EVENT_AES_WAR_CHOICE_1</EventChoice>`
`		</Row>`
`</Event_EventLinks>`

So the way I understood the documentation: the EventType should only be able to trigger if the EventChoice is active for the player, since CheckForActive is default true?

However I saw the Event trigger in the first turns of my game, (long before the prerequisite choice could have been taken by anyone at all). Have I dun goofed?

Here are the events in question:
[VoxPop_AdvisorEventSets (v 1).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/416591/VoxPop_AdvisorEventSets.v.1.zip)

**Comment by LoneGazebo** [comment]
Make sure the linker is showing up properly in the database. I tested and it was working for me with my events.

**Comment by Hokath** [comment]
In the firetuner I asked 
`for row in GameInfo.Event_EventLinker() do print(row.EventType, row.EventChoice, row.CheckForActive) end`
And it all appeared. No errors in the database log.

Is there something else I can look at to check?

**Comment by LoneGazebo** [comment]
And in the database? Use a SQL query software like SQLite Database to look.

**Comment by LoneGazebo** [comment]
If all looks fine I'll check the function again in the DLL. I tested but it may have been circumstantial.

**Comment by Hokath** [comment]
I pointed it at Civ5DebugDatabase. Hope that's the right one:
![untitled](https://cloud.githubusercontent.com/assets/11889219/17643838/73dda2aa-616d-11e6-901b-43cdd2bffe8d.jpg)
1  and 0 instead of true and false, but I assume that should be ok...?

**Comment by LoneGazebo** [comment]
Try making it true in the XML just to be safe.

**Comment by LoneGazebo** [comment]
I may have to edit the Boolean to be more lenient if it can't take integers.

**Comment by Hokath** [comment]
Ok. Think I should set the default CheckKnownPlayer tags to false as well, just in case?

**Comment by LoneGazebo** [comment]
Yes.

**Comment by Hokath** [comment]
Didn't work.

**Comment by LoneGazebo** [comment]
To be clear, the 'checkactive' works such that defines the 'active/no active' test. So if you leave it false (as mine are), it'll check that the event/choice is NOT active. If you set it true, it checks to see if it IS active. Does that make sense?

**Comment by Hokath** [comment]
Yes. So in the example in the OP I have it set to true because I want the EventChoice to be taken before the player Event will fire.

So I have something like this:
`<Event_EventLinks>`
`		<Row>`
`			<EventType>EVENT_AES_FOREIGN_PLAYER_BAD</EventType>`
`			<EventChoice>EVENT_AES_FOREIGN_CHOICE_1</EventChoice>`
`			<CheckForActive>true</CheckForActive>`
`			<CheckKnownPlayers>false</CheckKnownPlayers>`
`		</Row>`
`	</Event_EventLinks>`

But it fired on turn 4. No one has taken EVENT_AES_FOREIGN_CHOICE_1

**Comment by LoneGazebo** [comment]
Weird. I'll take a look.

**Comment by LoneGazebo** [comment]
Try this. Make sure your linker data is AFTER the events/choices you made (as with parent event xml). Also make sure linker data (choices etc.) exist as values in the database, otherwise they will not work.
[(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/416909/1.Community.Patch.zip)

**Comment by Hokath** [comment]
So I looked at the EventChoices themselves in the database. The game doesn't seem to populate the list with more than 100 choices. (I think with your stuff alone its like 74 choices)
![image](https://cloud.githubusercontent.com/assets/11889219/17648081/36d18fc2-6201-11e6-87e3-4fba84650cc8.png)

If I ask the firetuner it lists all 442 choices.
Que pasa?

**Comment by LoneGazebo** [comment]
You got hit the 'next page arrow,' Ja?

**Comment by LoneGazebo** [comment]
Also did it work?

**Comment by Hokath** [comment]
lol ok, next page woops.

So right now I have, in order: Event->Event_EventLinks->EventChoices->Event_ParentEvents
You want me to change that to Event->EventChoices->Event_ParentsEvents->Event_EventLinks ?

**Comment by LoneGazebo** [comment]
Yeah. Just make sure that the data that goes into parent events and event links are all after their data.

**Comment by Hokath** [comment]
Testing now and the patch appears to have worked - so far. What did you do?

**Comment by LoneGazebo** [comment]
Made sure that the cvassert data had a proper iterator. Moving the event linker down was the key.
