### ISSUE TITLE
City captured and un-captured on same turn

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2332]
[Gajah Mada_0204 AD-1440.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/416604/Gajah.Mada_0204.AD-1440.zip)
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/12

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk):  Bug?

3. Steps to reproduce: Rome captured my city of Makassar on turn 203. I saw it change colors as AI was playing. But somehow during the same turn (while AI was taking turns), it changed BACK to me. See screenshot. So by the time it was my turn to play (turn 204), city was mine again. I cannot imagine the AI didn't keep it or liberated it (is that even an option anyway?).  Also attached the saves before & after.
[AutoSave_0203 AD-1430.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/416606/AutoSave_0203.AD-1430.zip)
. 

![20160813102300_1](https://cloud.githubusercontent.com/assets/20485377/17643722/807392e0-6140-11e6-810d-3af56595f533.jpg)
![20160813102224_1](https://cloud.githubusercontent.com/assets/20485377/17643725/91570a06-6140-11e6-8f9f-1d9f22038471.jpg)
![20160813102229_1](https://cloud.githubusercontent.com/assets/20485377/17643727/936d65e2-6140-11e6-8ca2-18e75dc5b229.jpg)

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by TechpriestEnginseer** [comment]
I think AI liberate other AIs, but not sure about AI liberating cities for the Player...

**Comment by oedali** [comment]
Right, plus there was no liberation notification either. It was literally captured and un-captured on the same turn

**Comment by LoneGazebo** [comment]
May have been a graphical anomaly. Perhaps as a unit moved into position the AI accidentally moved through the city when it couldn't. I'd chalk it up to that.
