### ISSUE TITLE
Ask for DOF remains even when DOF already active.

### ISSUE THREAD

**Issue by balthazaario** [LoneGazebo/Community-Patch-DLL#2334]
Bug Report Template

Mod Version: (version august 8-12)

1. Mod List:
Voxpopuli full install with EUI
Calypsos coloured religions with both extensions.
Really advanced set-up
info addict.

2. Type of error (i.e. crash, interface bug, AI quirk): 
Interface (I think). request to be friends remains even though friendship already established.

3. Steps to reproduce:
open "discuss" when interacting with Victoria.

4. Additional information:

---------------------------
Supporting information:
[TEMP.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/416712/TEMP.zip)

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Sounds like mod conflict.

**Comment by balthazaario** [comment]
It's similar to the other issue I've posted ie both are related to false information during AI interactions, they must be related issues. The mods I've listed are the only mods I use...... could it be info-addict?? It's the only mod that adds information and extra UI elements.
I'll try playing without info-addict my next game.... I just got stomped by Shaka so I'm salty for now lol (first time in years Ive lost to AI in war and a testament to a great mod)
