### ISSUE TITLE
The Inca UI Bug - Terrace Farms Adjacency Bonus Not Functioning

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#2335]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-12 Version

1. Mod List (if using standard CPP set, leave blank):
R.E.D. Modpack

2. Type of error (i.e. crash, interface bug, AI quirk): 
Terrace Farms (Incan Unique Improvement) tooltip and Civipedia entry claims that Terrace Farms get +1 Food per adjacent Terrace Farm, but in-game this effect does not appear to be working. Terrace Farms only get bonus food from adjacent mountains.

3. Steps to reproduce:
Playing as The Incas, researched Terrace Farms and began to build them on hills between mountains and pre-existing farms. Once Terrace Farm improvements were complete they received the expected bonus Food from mountain adjacency, and Farms received bonus Food from Terrace Farm adjacency, but Terrace Farms did NOT receive adjacency bonus from each other. (See attached screenshot for example)

![8930_20160813132223_1](https://cloud.githubusercontent.com/assets/19951628/17644907/db49940c-615a-11e6-9e88-246dffc8b6db.png)

4. Additional information:
This may not be a bug as Terrace Farms seem very good as-is, but if they should not be getting bonus Food for being adjacent to other Terrace Farms, then the tooltips and other UI descriptions should be updated.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
You misread - gives FARMS (not TERRACE farms) extra food.

**Comment by cdanger341** [comment]
That's just it, G, the tool tip for Terrace Farms specifically says that it gets +1 Food per adjacent Terrace Farm AND adjacent Farms get +1 Food.  So it sounds like the tool tip/ Civipedia entries are incorrect.
