### ISSUE TITLE
Trade Interface Bugged 

### ISSUE THREAD

**Issue by Branbados** [LoneGazebo/Community-Patch-DLL#2336]
Mod Version : 8/12
1. Mod List (if using standard CPP set, leave blank): 
    Basic Community Patch
2. Type of error (i.e. crash, interface bug, AI quirk): 
     interface bug
3. Steps to reproduce: 
    Open trade interface with any civ

Lua log: http://pastebin.com/ukcScuWC
Database log: http://pastebin.com/Q4rtX11b

![image](https://cloud.githubusercontent.com/assets/21012396/17645293/17e842aa-6156-11e6-8e66-a0e47ae0cddb.png)

**Comment by LoneGazebo** [comment]
You have a mod conflict.
