### ISSUE TITLE
Team AI dont build more than 1 worker

### ISSUE THREAD

**Issue by Tsenna** [LoneGazebo/Community-Patch-DLL#2337]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-9

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

3. Steps to reproduce:

4. Additional information:
I usually play teamed up with AI. (5x2 player teams)
The ai dont build more than 1 builder and lacks with improvement for terrains.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Teams has nothing to do with AI performance in this regard.
