### ISSUE TITLE
AI ends turn in ocean tile with no astrology.

### ISSUE THREAD

**Issue by Freaky-Freddy** [LoneGazebo/Community-Patch-DLL#2338]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 

8-12

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

AI quirk

3. Steps to reproduce:

Unknown

4. Additional information:

 Indian knight ends turn on an ocean tile, Inda only has 20 techs therefore doesn't have astrology yet. Bug?

---------------------------
Supporting information:

In zip file the save files before and after he ends his turn.

[saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/416814/saves.zip)

**Comment by LoneGazebo** [comment]
Can happen if a pathfinding element causes it. Normal and fine. AI will have to move back to coast next turn.

**Comment by ilteroi** [comment]
can't load the save ... screenshot?

the new rules for naval units don't apply for embarked units, but i think there's an exception from the astronomy requirement for ocean plot owned by the player.

**Comment by Freaky-Freddy** [comment]
> can't load the save ... screenshot?

http://imgur.com/a/Nbv6i

before and after

i forgot to mention i have RED modpack and faster aircraft animations along with vox populi

but yeah not a big deal, it didn't seem to happen with all units
