### ISSUE TITLE
Can't build Train Station in my capital

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2339]
It looks like this:
![8930_20160814152135_1](https://cloud.githubusercontent.com/assets/1131228/17648541/ed95aec4-6232-11e6-9682-464ff32a6197.png)
As you can see, I have 0 coastal resources and coastal tile yields are subpar to Colonias, so I'd definitely take +10% shekels over Seaport bonuses.

**Comment by LoneGazebo** [comment]
It is because you have no railroad based connection to an owned city from the capital.

**Comment by Radost** [comment]
The only thing it requires is "railroad connection to the capital". And the capital is connected to itself by default.
Also you need to check Train Station eligibility logic:
![8930_20160814201150_1](https://cloud.githubusercontent.com/assets/1131228/17650015/99508edc-625b-11e6-80a6-fdeb246ed421.png)
Both Tlaxcala and Teotihiacan are coastal cities but I can build Train Station in Teotihiacan and not in Tlaxcala because...?

**Comment by LoneGazebo** [comment]
Railroad connection to capital for Train Station requires a literal rail connection.

Re the other two, not sure. You built a seaport in one?

**Comment by Radost** [comment]
The Capital tile is a literal railroad tile though, can't be any more literal than that.

Tlaxcala - can only build Seaport.
Teotihuacan - can choose between Seaport and Railroad Station.

**Comment by LoneGazebo** [comment]
In strategic view for city connections, what does tlaxcala look like?

**Comment by Radost** [comment]
![8930_20160814213122_1](https://cloud.githubusercontent.com/assets/1131228/17650409/942eb59a-6266-11e6-8956-57196b9891de.png)

**Comment by LoneGazebo** [comment]
That's odd. And you've got railroad connections to all of them? If so, I'll ping @ilteroi on this, he worked on city connections most recently. Ilteroi, city connections should prioritize land over sea, otherwise connection-based bonuses don't work.

**Comment by ilteroi** [comment]
just checked the code, can't see a the problem. hmm.

what are the conditions for a train station, in the code?

**Comment by LoneGazebo** [comment]
Looking at the screenshot, the coastal cities should all have railroad connections between them (the yellow hexes).

The train station code requires a 'cityconnection' route plot adjacent to the city to make it available.

**Comment by ilteroi** [comment]
why not simply check IsIndustrialRouteToCapitalConnected()?

anyway savegame would be nice

**Comment by LoneGazebo** [comment]
Because that allows for coastal connections via lighthouses + railroad tech, and the Train Station needs an actual railroad connection.

**Comment by LoneGazebo** [comment]
You can set this up pretty easily - do small continents, have capital on one continent, build some cities on other continent and link w/ RR. Build lighthouses in all and tech up to railroad.

**Comment by ilteroi** [comment]
guess so but that takes half an hour i was hoping to save

**Comment by LoneGazebo** [comment]
I'd make you a save but I'm on a different build right now. You can use firetuner to do all of that pretty darn quickly...

**Comment by ilteroi** [comment]
i know, i just did. but couldn't reproduce.

![image](https://cloud.githubusercontent.com/assets/1358966/17679086/2d1b3b10-633a-11e6-90cf-00eec0fe4d8f.png)

**Comment by ilteroi** [comment]
ok, now here there's something interesting

![image](https://cloud.githubusercontent.com/assets/1358966/17679295/21ed76f8-633b-11e6-813e-090b91813502.png)

another lighthouse in szczecin.

**Comment by LoneGazebo** [comment]
Interesting. Well this fix makes it so that train stations will function - train stations need a 'yellow hex' adjacent to the city to be buildable. I didn't want to use the 'industrialroute' bool because lighthouse + railroad technology grants that bonus. Make sense?

**Comment by ilteroi** [comment]
hehe. just updated my previous post. the fix is not so easy.

**Comment by ilteroi** [comment]
yellow hex means city connection by the way, doesn't have anything to do with railroad

**Comment by LoneGazebo** [comment]
Right, but if it is both a city connection and a railroad tile, then the train station works. :)

**Comment by LoneGazebo** [comment]
`if(pkBuildingInfo->IsRequiresRail())
	{
		if(!IsIndustrialRouteToCapitalConnected())
		{
			return false;
		}
		else
		{
			//Check for an actual railroad here.
			bool bRailroad = false;
			for (int iDirectionLoop = 0; iDirectionLoop < NUM_DIRECTION_TYPES; ++iDirectionLoop)
			{
				CvPlot* pAdjacentPlot = plotDirection(getX(), getY(), ((DirectionTypes)iDirectionLoop));
				if (pAdjacentPlot && pAdjacentPlot->getRouteType() == ROUTE_RAILROAD && pAdjacentPlot->IsCityConnection(getOwner()))
				{
					bRailroad = true;
					break;
				}
			}
			if(!bRailroad)
			{
				return false;
			}
		}
	}`

**Comment by Radost** [comment]
Just to remind you of the main point of the issue: it's not clear at glance why one coastal city can build both Train Station or Seaport, while another - only Seaport. If you "hardware" stations to a city connection railroad, then it will get derpy when you can build TS in a coastal city for short while when the "main" coastal city connection gets broken for one reason or another.
And I don't see the issue with allowing Train Station in a strictly coastal city, since only coastal capital will have comparable benefits from TS versus Seaport.

**Comment by LoneGazebo** [comment]
I'll adjust the help text on the train station. The bigger issue here is that things like villages/towns rely on those road connections for bonuses - losing that is pretty significant.

**Comment by ilteroi** [comment]
ok, sleeping helps, fixed for good now and the code is simpler at the same time.

disadvantage is that the flag is now also set for dead end roads. but not for isolated roads. detecting dead ends is hard (at least i couldn't think of a good way).

**Comment by LoneGazebo** [comment]
what's that mean? city connection roads that 'branch' off of a real connection will light up?

**Comment by ilteroi** [comment]
yes. any road which has a connection to the capital will be marked.

**Comment by LoneGazebo** [comment]
Hmm. No way to have it grab just the shortest land and shortest sea route?

**Comment by ilteroi** [comment]
that would be possible but it is not the solution for the situation above. 

i realize that the new behavior could be gamed for additional yields. trying to think of a better way

**Comment by ilteroi** [comment]
so we could either test the shortest connection from each city to each other city (no only the capital), which has significant performance impact in large empires.

or we could teach the AI to build roads to villages. might bring back the "road spam" from the old days but on the other hand, better mobility and it kind of makes sense.

**Comment by LoneGazebo** [comment]
Right now the AI builds villages on city connection roads - flipping that logic seems a little daunting.

The issue really only crops up (with the current setup) for Capital -> Lighthouse : Lighthouse <- City 2 <-> Route <-> City 3 problems if City 3 is also coastal and has a lighthouse.

Ideally it'd look like this:

1.) Road/rail connection to capital? Prioritize.
2.) No direct road/rail? Road/rail to a city with a lighthouse? 
3. ) If road/rail to city w/ lighthouse, is that connected to a city or a capital that has a lighthouse?
3.) No road connection? Do you have a lighthouse of your own?
4.) If you have a lighthouse, that's your connection.

So there'd be 3 tiers of connection:

Direct road/rail.
Indirect road/rail.
Water connection.

**Comment by ilteroi** [comment]
please take a look at this image again:

![image](https://cloud.githubusercontent.com/assets/1358966/17679295/21ed76f8-633b-11e6-813e-090b91813502.png)

should the road between gdansk and wrozlaw be marked or not? assume the coastal cities all have lighthouses.

**Comment by LoneGazebo** [comment]
No, I don't think so, as it isn't the shortest route for a connection (assuming that Warsaw is capital and is off screen).

**Comment by LoneGazebo** [comment]
Looks fine to me, tbh.

**Comment by ilteroi** [comment]
ah, now i remember the problem. in the picture there is no lighthouse in krakow. that's why it's connected via szczecin (why oh why did i pick poland who have the wildest spelling?).

now if there were a lighthouse in krakow too, then wrozlaw would be connected via krakow and the route between wrozlaw and szczecin would be fallow. so you wouldn't be able to have a train station there.

so you are proposing to ignore the lighthouse in a city if it has a road connection to another lighthouse. seems a bit counterintuitive, but might just work.

**Comment by LoneGazebo** [comment]
If easier, I feel like road connections between non capital cities should count as city connections. It's more intuitive for players that way.

Maybe cities can have both - a potential water connection and a potential land connection?

**Comment by ilteroi** [comment]
so do we have a deal on the train stations?

i can make it so that the shortest connection between all pairs of owned cities is considered. it will have a performance impact, but we'll have to see how noticeable it is.

**Comment by LoneGazebo** [comment]
We can try it, see how it works.

Re train station - I'm fine with that I guess - it does make it possible to 'game' it by building a single RR tile next to the city, though.

**Comment by ilteroi** [comment]
last train to nowhere! 

thought about it some more ... when i do my change, yours shouldn't be necessary anymore, so you can relax.
