### ISSUE TITLE
siege units that don't have UNITCOMBAT_SIEGE combat class

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#234]
UNIT_ASSYRIAN_SIEGE_TOWER
UNIT_HUN_BATTERING_RAM

**Comment by LoneGazebo** [comment]
I'll fix.

**Comment by qqqbbb** [comment]
They're 'melee' units now. Is this why AI builds so many of them?

**Comment by qqqbbb** [comment]
These 2 units also have FLAVOR_RANGED for some reason.
