### ISSUE TITLE
Syndicalism does count towards the cap

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2340]
Despite saying otherwise in the description.
This is the window (notice derpy text alignment):
![8930_20160814181953_1](https://cloud.githubusercontent.com/assets/1131228/17649323/e10806b6-624b-11e6-9209-18493544819e.png)
21 out of 17

This is all cities with my franchise:
![8930_20160814182005_1](https://cloud.githubusercontent.com/assets/1131228/17649329/123100ee-624c-11e6-9bf7-b17f8d839ff7.png)
11 cities.

**Comment by LoneGazebo** [comment]
Are you popular with all those civs?

**Comment by LoneGazebo** [comment]
If you are influential with all but one that means 10*2 = 20 + 1 = 21

**Comment by Radost** [comment]
What does it have to do with the issue? It says 21/17 and I can't establish franchises past those 11 anymore because the tenet counts its effect towards the cap.

**Comment by LoneGazebo** [comment]
Ah I thought you were asking about the numbers adding up (your first post isn't clear). I'll make it so that the cap is lifted by the same amount to prevent that.
