### ISSUE TITLE
Can Airlift on water tiles

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2342]
![8930_20160814212447_1](https://cloud.githubusercontent.com/assets/1131228/17650402/405aea1a-6266-11e6-9ebd-3524ffc34b2c.png)

**Comment by LoneGazebo** [comment]
@ilteroi, a simple exclusion needed?

**Comment by ilteroi** [comment]
that seems to be due to MOD_GLOBAL_RELOCATION, don't know who did that

check CvUnit::canAirliftAt()

**Comment by LoneGazebo** [comment]
That's whoward's mod
