### ISSUE TITLE
UI Tooltip Inaccuracy - Incan Terrace Farm

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#2343]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8/12 version

1. Mod List (if using standard CPP set, leave blank):
R.E.D. Modpack

2. Type of error (i.e. crash, interface bug, AI quirk): 
According to Gazebo's last message in the previous Issue I created, the Incan Terrace Farm is working as intended, but the tooltip for the Terrace Farm UI is incorrect. The tooltip states that Terrace Farms receive +1 Food for each adjacent Terrace Farm AND provide +1 Food to adjacent Farms. See screenshot:

![8930_20160814112741_1](https://cloud.githubusercontent.com/assets/19951628/17650448/dfbcfd30-6213-11e6-8b38-f41cf86ddf46.png)

3. Steps to reproduce:
I was using EUI, so perhaps the tooltip is different when not using EUI?

4. Additional information:
Additionally, I double checked the Civipedia entry and it correctly describes how the Terrace Farms work. Only the mouse-over tooltip appears to be displaying inaccurate information.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
That's an EUI bug, not my territory to fix, sorry.
