### ISSUE TITLE
AI lacks of workers

### ISSUE THREAD

**Issue by Tsenna** [LoneGazebo/Community-Patch-DLL#2344]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-12

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 

3. Steps to reproduce:

4. Additional information:
It seems AI dont like to build Workers, AI start building worker very early and keeps the single one without adding additional workers if needed. 

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
This is second report on issue, and I cannot reproduce this, sorry.

**Comment by Tsenna** [comment]
Ill add a savegame, give me some hours please ;)

**Comment by Tsenna** [comment]
http://images.akamai.steamusercontent.com/ugc/1616050772321634232/5D29C5340B3539ED96DBF55FD5F16E1585F463EB/

In this SS you can see, the AI only has 1 builder after 118 rounds. 
The AI refuse to **build** more than 1 builder. If he get bonus Builder by capturing or policies, the AI keeps them, but dont build more than one after game start.

I dont know if this affects the other AI aswell beside of my team AI.

**Comment by Tsenna** [comment]
[lackOfBuilder.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/419143/lackOfBuilder.zip)
