### ISSUE TITLE
Too many spies breaks the espionage interface

### ISSUE THREAD

**Issue by Glidergun** [LoneGazebo/Community-Patch-DLL#2346]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

8/9

1. Mod List (if using standard CPP set, leave blank):

FlagPromotions

2. Type of error (i.e. crash, interface bug, AI quirk): 

Interface bug

3. Steps to reproduce:

 Get 11 spies. This can be done by, for example: being England, getting Bletchley Park, building the National Intelligence Agency, and taking the Informants policy and Covert Action tenet on a map with 12 city-states.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

http://images.akamai.steamusercontent.com/ugc/447366480860843832/43A74E21D6280F83094C61C6CA81425AD04D32A9/

Notice the lack of spies on the left-hand side of the interface, and the way that cities with spies in them are intermixed with the general city list rather than gathered at the top.

**Comment by LoneGazebo** [comment]
Please post your lua.log. If logging is not enabled, please enable it, reproduce the error, the post the log.

G

**Comment by Glidergun** [comment]
[spyLua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/417280/spyLua.zip)

**Comment by LoneGazebo** [comment]
Interesting. Will take a look.

**Comment by LoneGazebo** [comment]
@JFDaly, would you mind looking at the espionage.lua file? I don't see any immediate clues that break at 11+ spies.

**Comment by LoneGazebo** [comment]
Alright, the issue isn't # of spies, but rather the starting spy rank value being higher than the max number of ranks (due to bletch + england UA). So sorry, I'll fix for next version. Congratulations on your spy empire, though!

**Comment by JFDaly** [comment]
I was just about to test. Everything good then?

**Comment by LoneGazebo** [comment]
Yeah, sorry.

**Comment by LoneGazebo** [comment]
Thanks for the prompt check, though! :)

**Comment by JFDaly** [comment]
No worries; always happy to help where I can.

**Comment by Glidergun** [comment]
Interesting! Thanks for the quick investigation, sorry for the misleading title.

**Comment by LoneGazebo** [comment]
No worries! Sorry for the buffer value oversight.
