### ISSUE TITLE
When attempting to use local culture as a tile yield, you get food icons instead.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2347]
![image](https://cloud.githubusercontent.com/assets/13937047/17652255/a1b8c62c-622c-11e6-9f2a-3a68f824c1f8.png)

This is with EUI. I hope this isn't the same for Great Generals or Great Admiral Points as well.

Other than the graphics, the unified yields seem to be consistent.

**Comment by LoneGazebo** [comment]
There are no 'icons' for those things currently. I can do that, if there's a need.

**Comment by TechpriestEnginseer** [comment]
Well.. I do need one for local culture.. the icon could probably be EUI's border indicator...

**Comment by LoneGazebo** [comment]
I've got some for you:

![untitled](https://cloud.githubusercontent.com/assets/7849458/17652694/5753ed3a-6251-11e6-9ec3-7e0b28a294ae.png)

**Comment by LoneGazebo** [comment]
Local culture, general, admiral. I'll include in next version.

**Comment by TechpriestEnginseer** [comment]
Thanks!
