### ISSUE TITLE
CTD on AI turn

### ISSUE THREAD

**Issue by ili79** [LoneGazebo/Community-Patch-DLL#2349]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-12

1. Mod List (if using standard CPP set, leave blank):

![image](https://cloud.githubusercontent.com/assets/21032065/17656779/700cc87c-62c6-11e6-9028-677b5fbd0516.png)
![image](https://cloud.githubusercontent.com/assets/21032065/17656792/95da9e62-62c6-11e6-8197-7e42e74098aa.png)

2. Type of error (i.e. crash, interface bug, AI quirk): 

Crash To Desktop

3. Steps to reproduce:

Reloading the save game.
[CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/417592/CTD.zip)

4. Additional information:

Hitting the end turn and waiting for the AI going trough its turn.  Apparently the CTD will happen always on a unidentified player.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Can't debug it with that many other mods, sorry.

**Comment by ili79** [comment]
Hello!

Thank you for the reply. No problem. I'll try a new game with fewer mods.

BR,
ili
