### ISSUE TITLE
Friendly unit preventing city capture

### ISSUE THREAD

**Issue by ashendashin** [LoneGazebo/Community-Patch-DLL#2350]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-12

1. Mod List (if using standard CPP set, leave blank):
Faster Aircraft Animations (v 3)
FlagPromotions (v 7)
Quick Turns (v 10)

2. Type of error (i.e. crash, interface bug, AI quirk): 
AI quirk

3. Steps to reproduce:
![20160815021644_1](https://cloud.githubusercontent.com/assets/21032378/17657260/a7b7e64e-628f-11e6-94d4-fd2d355a1fa2.jpg)
![20160815021650_1](https://cloud.githubusercontent.com/assets/21032378/17657269/ae6d145a-628f-11e6-8f14-385244fcb1e3.jpg)

4. Additional information:
I tried to simply wait for it to move and now, after I'm finishing up with the other cities, it seems like that won't be happening. Anything I can do? Not sure if anyone raised this issue before.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
@ilteroi, we need to check for this?

I'd load IGE and delete the unit.

**Comment by ashendashin** [comment]
Completely forgot about that mod. Thanks for the answer and all of Vox Populi! Can't play the game without it.

**Comment by LoneGazebo** [comment]
You are welcome! We'll get this sorted out.

**Comment by ilteroi** [comment]
so i guess the problem is that a unit should not be able to end it's turn in a foreign city, even with open borders and all?

how about passing through?

**Comment by ashendashin** [comment]
I don't get a notification for your edits, but luckily enough, I checked back on this. I couldn't manage to reproduce it when I loaded a few turns before the caravel got stuck there. Maybe I had a ship blocking the path out of the city? Anyways if you really want a save before it gets stuck, I could go back and try to screw around with America's pathway. For now, here's a save after it went in the city.
[Bismarck_0393 AD-1766.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/422347/Bismarck_0393.AD-1766.zip)

**Comment by ashendashin** [comment]
So much for the screenshots I put in for steps to reproduce. I can't figure how to get it stuck again. Tried blocking the path and the ai just sat outside of the city until it was unblocked. As far as I can tell your code works and my experience was some anomaly. I'm far past that war so I can't remember my exact unit placement either. Nevertheless, I think I got it to close to how it was on this save.
[Bismarck_0389 AD-1758.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/423962/Bismarck_0389.AD-1758.zip)

**Comment by ilteroi** [comment]
ok, turns out it's an explorer with nothing left to explore and no way home. should be better now.

**Comment by ashendashin** [comment]
So all I had to do was let it do it's thing and wait for it to come back, rather than try to force the ai to do something it's coded not to do, like a sensible person? I sure feel like a jackass now. Anyways, nice catch! Might as well close this issue I suppose.
