### ISSUE TITLE
God-King

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2351]
Bug Report Template

Mod Version 12 August

1. Mod List (if using standard CPP set, leave blank):

2. Type of error - description

3. Steps to reproduce:

God-King description says it gives 1 for 8, but if you look at pantheons.sql, it gives 1 for 6, which is probably intended (I remember you agreed with people complaining about the nerf in 1 for 8 and said you changed it back to 6).

**Comment by LoneGazebo** [comment]
I'll fix text.
