### ISSUE TITLE
Game crashes at AI's turn

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2353]
Mod Version (i.e Date - (4/23b)): 8-12

1. Mod List (if using standard CPP set, leave blank): Thal's FlagPromotions

2. Type of error (i.e. crash, interface bug, AI quirk): Game crashes at AI's turn

3. Steps to reproduce:

 Savegame attached.

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/418272/QuickSave.zip)

**Comment by LoneGazebo** [comment]
I need your minidump file.

**Comment by saamohod** [comment]
I will gladly send you one as soon as you instruct me where to find it.

**Comment by LoneGazebo** [comment]
same place as your civ exe.

**Comment by saamohod** [comment]
I hope this is the one. 
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/419353/CvMiniDump.zip)
