### ISSUE TITLE
Zero can be purchased with Faith

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2354]
Even though my religion doesn't have anything to do with it.
It is however caused by my religion (which is Ancestor Worship + Ceremonial Burial + Mandirs + Mosques + Sainthood + To the Glory of God), because there is no faith purchase option for cities without it.

**Comment by LoneGazebo** [comment]
Ah, I'll fix. Sounds like I forgot to set the 'requiresfaithpurchaseenabled' bool for the Zero (prolly also the B17, I'll look).
