### ISSUE TITLE
Polder Adjacency Bonuses

### ISSUE THREAD

**Issue by paul-r-gall** [LoneGazebo/Community-Patch-DLL#2355]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/12

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
either interface bug or coding issue
Polders should have adjacency bonuses from villages, however, here all Polders are displayed as having the same value. In particular, polders next to villages should have more gold than polders not next to villages. Not sure if it's just an interface quirk or if I am actuallly gettting the wrong amount of gold. 

3. Steps to reproduce:
place polders as Netherlands

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
http://images.akamai.steamusercontent.com/ugc/269474483220556194/CEC1C01CC2DF4026D8B4DCB0F0D3056E1CDC8101/

**Comment by LoneGazebo** [comment]
Polders give a bonus to villages, they do not get a bonus from them.

**Comment by paul-r-gall** [comment]
Ohhhhhhhh ok sorry to bother you.

**Comment by LoneGazebo** [comment]
No worries!
