### ISSUE TITLE
bassies disappearing (this time with pics)

### ISSUE THREAD

**Issue by NuttSo** [LoneGazebo/Community-Patch-DLL#2357]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-12

1. Mod List (if using standard CPP set, leave blank):
Info addict
Reforestation
IGE
Faster aircraft animation
really advanced setup

2. Type of error (i.e. crash, interface bug, AI quirk): 

3. Steps to reproduce:
Trade an embassy.

4. Additional information:
![20160816002945_1](https://cloud.githubusercontent.com/assets/20857721/17680519/31bedb36-6349-11e6-89ab-4edea0a89769.jpg)
![20160816002949_1](https://cloud.githubusercontent.com/assets/20857721/17680520/31c2f590-6349-11e6-95cc-67343cccc4a6.jpg)
![20160816003125_1](https://cloud.githubusercontent.com/assets/20857721/17680521/31c3a350-6349-11e6-8fcf-4f077cf7391a.jpg)
![20160816003133_1](https://cloud.githubusercontent.com/assets/20857721/17680522/31c5313e-6349-11e6-8321-0a2cd5060aee.jpg)

Thanks 

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Sounds like an EUI issue - are you able to do embassy-required things via trade?

**Comment by NuttSo** [comment]
nope , embassy is required

**Comment by NuttSo** [comment]
it happened again same AIs same game (Alexander , Elizabeth ) .
![20160816140602_1](https://cloud.githubusercontent.com/assets/20857721/17697044/19a1f6ba-63bb-11e6-9b10-6c7613ba99e4.jpg)
![20160816140607_1](https://cloud.githubusercontent.com/assets/20857721/17697045/19a6ab42-63bb-,11e6-809a-ff7638b3a0e6.jpg)
![20160816141145_1](https://cloud.githubusercontent.com/assets/20857721/17697088/5ffdf62c-63bb-11e6-80c6-222729040917.jpg)
![20160816141138_1](https://cloud.githubusercontent.com/assets/20857721/17697089/5ffe0fcc-63bb-11e6-916c-0fb6a89b2fd8.jpg)
