### ISSUE TITLE
Encampment Jungle Clear Bug

### ISSUE THREAD

**Issue by paul-r-gall** [LoneGazebo/Community-Patch-DLL#2358]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/12

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
interface bug

3. Steps to reproduce:

4. Additional information:
Shoshone Encampment button says Metal Casting is required to cut jungle.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
http://images.akamai.steamusercontent.com/ugc/269474483220966258/3A7F691B65EFF5B19FF7114ED5771985A76111DE/

http://images.akamai.steamusercontent.com/ugc/269474483220965946/C3AF29BF172D7E4EBDB32513820777E1B0880AD0/

**Comment by LoneGazebo** [comment]
That is accurate. i fix.
