### ISSUE TITLE
Player "Beneficial" Peace Treaty Trade

### ISSUE THREAD

**Issue by ele3131** [LoneGazebo/Community-Patch-DLL#2359]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/12

1. Mod List (if using standard CPP set, leave blank):

VP No-EUI
Portuguese(BR) Translation

2. Type of error (i.e. crash, interface bug, AI quirk): 

Askia declared war against me (He really wanted my territories), few turns later another Civilization proposed to me the "end of the war" and even gave me gems. The problem is that who declared war in the first place was Askia, not me.

With this trade option (Gajah Mada offered me this trade) the player has a "very easy way" to end some wars if he wants it.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way. 

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

![peace trade](https://cloud.githubusercontent.com/assets/13533421/17687927/08a519d4-6350-11e6-96e9-1996d6f8619b.jpg)

**Comment by TechpriestEnginseer** [comment]
I don't see how this is a bug. Maybe he knows Askia is probably losing and wants to help his friend by asking the human player for peace.

**Comment by LoneGazebo** [comment]
that's perfectly fine, tbh.

**Comment by ele3131** [comment]
That's not the case, i don't play "military" games, Askia is a military A.I, when he declared war against me him military power was far greater than mine. The problem is the Logic, how one civilization can start war against the player (because want's territory) and like 2 - 3 turns later another civ "has the power" to end this... If i was who declared the war would makes sense, but again this isn't the case =/

**Comment by ele3131** [comment]
I see 2 options to improve this:

1-) Check if the Player exceeded the enemy military power (like TechpriestEnginseer was thinking), and just then a friedly A.I can proposes peace instead of the enemy Civ.

2-) See if was the player who declared war, if it isn't, don't show/allow this kind of trade.

Both could even be used to create a even more "realistic" scenario.

**Comment by Radost** [comment]
Yeah, third-party peace deals can be traded at the second turn of a war.
