### ISSUE TITLE
Korea (which wonders give the science boost?)

### ISSUE THREAD

**Issue by Shadzy19** [LoneGazebo/Community-Patch-DLL#236]
Hi, just trying the new korea in a game, already build several science wonders in my capitol and always got the boost, just new I finished the porcelain tower and I didnt get a science boost.
Is this intentional or a bug?

PS: Where can I find a list of all the wonders that should get the boost?
Been searching in the files but cant any info.

**Comment by LoneGazebo** [comment]
I'm not sure – I'll look at the code for it and see why it isn't working.
