### ISSUE TITLE
Greyed Out Event Problem

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2361]
As events are made in quantity rather than quality. Problems can arise. One of the most common problem that can arise is if all of the event choices are unable to be chosen making the player unable to go to the next turn. To circumvent this issue, if all event choices are unable to be picked, the event should be nullified or canceled with the reminder that the player should be notified to report this which should allow them to advance to the next turn.

**Comment by LoneGazebo** [comment]
I'll look at the issue, yep.

**Comment by LoneGazebo** [comment]
Well, there's already protection for this in the DLL.
