### ISSUE TITLE
Naval Invasion and Operations

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#2362]
Hey @ilteroi,

I've got a test and savegame for you. Here's the savegame:

[Ramesses II_0361 AD-1941.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/419604/Ramesses.II_0361.AD-1941.zip)

(It loads into Russia, don't worry.)

Watch Russia's naval invasion next to Novgorod. The naval units lead far, far out in front of the embarked land units, thus causing the operation to  rubber band as the CoM shifts back and forth. This is the naval issue I've been talking about.

Anyways, grab the latest master DLL stuff and use the mod zip below to run the save. Should work.

Mods:
https://mega.nz/#!KRcwmbIa!wkcGLh1arxZUaVUSn8xR5IwKB-PhfgLOSoFfABel6zg

**Comment by ilteroi** [comment]
crashes on load, even with your original dll. i'd really like to know why that keeps happening to me. but only on some versions - some others were fine. grrr

**Comment by LoneGazebo** [comment]
Did you use the mod download set I linked?

**Comment by ilteroi** [comment]
yeah

**Comment by LoneGazebo** [comment]
Alright, I did some checking and here's some oddities/suggestions:

ScoreDeploymentPlots (tactical AI) is returning 100s of 'valid plots' for naval operations with a range of 6. That seems really high, and way too loose for a naval op. We should tighten that up to 3, no? Also, even at a range of 6, 100+ valid plots seems high - possible that the same plot is being checked more than once?


FindClosestNavalOperationUnit in ExecuteNavalFormationMoves - don't you think we should separate the moves out so that the embarked land units move as far as they can first, and then all naval units move second (i.e. on top of the embarked units, where possible)? Seems like that would help control the rubber banding as well, as the minimum speed of the embarked units would dictate the outcome.

**Comment by LoneGazebo** [comment]
I think naval ops are simply too loose-  the fact that naval units and embarked units can stack means that they shouldn't have to be quite so tight.

**Comment by ilteroi** [comment]
they didn't use to be - at some point somebody decided to to up the "gather tolerance". for naval ops it's around 5, corresponding to 91 plots.

**Comment by LoneGazebo** [comment]
I think we should tighten it to 3, actually. Any lower than that and the AI spreads itself thin. I'd rather have operations fail that are too tight than have them floppily succeed.

**Comment by LoneGazebo** [comment]
I'm thinking:

```
`int iRange = OperationalAIHelpers::GetGatherRangeForXUnits(iNumUnits);

		//naval needs less space.
		if ( IsNavalOperation() )
			iRange--;

		for(int iX = -iRange; iX <= iRange; iX++)
		{
			for(int iY = -iRange; iY <= iRange; iY++)
			{
				CvPlot* pLoopPlot = GC.getMap().plot(pPlot->getX()+iX, pPlot->getY()+iY);

				if (!pLoopPlot)
					continue;

				if (!IsNavalOperation() && pLoopPlot->isWater())
					continue;

				if (IsNavalOperation() && !pLoopPlot->isWater())
					continue;

				if (IsNavalOperation() && !pArmy->IsAllOceanGoing() && pLoopPlot->isDeepWater())
					continue;

				if (pLoopPlot->canPlaceUnit(GetOwner()))
					iValidPlotsNearby++;
			}
		}

		// Find more valid plots than units?
		if(iValidPlotsNearby > iNumUnits)
		{
			// If so, just use normal range for this many units
			iRtnValue = iRange;
		}
		// Something constrained here, give ourselves a lot of leeway
		else
		{
			iRtnValue = iRange + 1;
		}`
```

**Comment by ilteroi** [comment]
//naval needs less space.
        if ( IsNavalOperation() )
            iRange--;

that's key i guess, the rest is the same right? not all naval ops have embarked units in them though.

also, i think the real problem is that embarked units are basically treated as ranged units - no attempt at stacking is even made.

**Comment by LoneGazebo** [comment]
Also, in CvUnit::TurnsToReachTarget, I'm seeing a MAX_INT for all MoveToEmptySpaceNearTarget calls for land units moving onto water tiles, probably because of this in TacticalAI::MoveToEmptySpaceNearTarget

```
	if (eDomain==pUnit->getDomainType())
		iFlags |= CvUnit::MOVEFLAG_APPROX_TARGET_NATIVE_DOMAIN;
```

In a prior function 

MoveToEmptySpaceNearTarget(pUnit, m_ChosenBlocks[iI].GetPlot(), pUnit->getDomainType(), 12);

so the domain type is being set based on the unit's type, not the chosen target plot's type, thus land units embarking are breaking on attempts to move at sea!

**Comment by LoneGazebo** [comment]
Yeah, the rest is the same. I also removed the highest tier of the 'gatherrangeforxunits' so that the highest tier is range 4, not range 5. 5 is way too much IMO.

**Comment by ilteroi** [comment]
so what about stacking? that's unfortunately not a point fix ...

anyway, i've got this side project, if it ever works out it could replace all that ScorePlot and ExecuteMove stuff. but it's kinda tricky, i wouldn't bet on it yet

**Comment by LoneGazebo** [comment]
Well, looking at the code again there is already logic for embarked units moving first, and then naval units second. 

I do think, however, that the problem is tied to that MOVEFLAG_APPROX_TARGET_NATIVE_DOMAIN flag, as moves across the ocean will inevitably fail if they're trying to stay on land.

**Comment by LoneGazebo** [comment]
I mean, am I crazy on that point, or misreading the code?

**Comment by LoneGazebo** [comment]
Alright, so changing this function in tacticalAI

`
```
/// Move up close to our target avoiding our own units if possible
bool CvTacticalAI::MoveToEmptySpaceNearTarget(UnitHandle pUnit, CvPlot* pTarget, DomainTypes eDomain, int iMaxTurns)
{
	if (!pUnit || !pTarget)
		return false;

	//nothing to do?
	if (plotDistance(pUnit->getX(),pUnit->getY(),pTarget->getX(),pTarget->getY())<3 && (eDomain==NO_DOMAIN || pTarget->getDomain()==eDomain))
		return true;

	int iFlags = CvUnit::MOVEFLAG_APPROX_TARGET_RING2 | CvUnit::MOVEFLAG_SAFE_EMBARK;
	if (eDomain==pTarget->getDomain())
		iFlags |= CvUnit::MOVEFLAG_APPROX_TARGET_NATIVE_DOMAIN;

	int iTurns = pUnit->TurnsToReachTarget(pTarget,iFlags,iMaxTurns);
	if (iTurns <= iMaxTurns)
	{
		bool bResult = MoveToUsingSafeEmbark(pUnit, pTarget, true, iFlags);
		TacticalAIHelpers::PerformRangedAttackWithoutMoving(pUnit.pointer());
		return bResult;
	}

	return false;
}
```

Specifically:

```
if (eDomain==pTarget->getDomain())
		iFlags |= CvUnit::MOVEFLAG_APPROX_TARGET_NATIVE_DOMAIN;
```

Seems to have fixed the naval issue. Between that and tightening up range, there are tight little naval invasions moving across the map. Beautiful!

**Comment by ilteroi** [comment]
sounds good! but do the ships stack with the embarked units? from my reading of the code, that would be a surprise ...

**Comment by LoneGazebo** [comment]
Somewhat, yes. They like to range in front of or on them - we could probably improve that some more, but seeing invasions work again is lovely.

**Comment by LoneGazebo** [comment]
Does the change I made make sense?

**Comment by LoneGazebo** [comment]
@ilteroi,

Oops, I think I closed/opened instead of posting. Anyways, does the change above. make sense for your intended use of that flag? The way the function was written eDomain was compared against the unit's domain, however (if used) eDomain was already the unit's domain, so it was always true. Seems like making it ptarget instead is what you wanted, no?

**Comment by LoneGazebo** [comment]
![20160817125939_1](https://cloud.githubusercontent.com/assets/7849458/17745723/fcce1602-647a-11e6-9361-d8994e53159f.jpg)
![20160817124255_1](https://cloud.githubusercontent.com/assets/7849458/17745724/fcce75f2-647a-11e6-8688-d94cdb4aaad4.jpg)
![20160817130207_1](https://cloud.githubusercontent.com/assets/7849458/17745727/fcd2a78a-647a-11e6-923f-170d491ba8f4.jpg)
![20160817130201_1](https://cloud.githubusercontent.com/assets/7849458/17745725/fccfccea-647a-11e6-9a88-4f91c1c1889c.jpg)
![20160817130145_1](https://cloud.githubusercontent.com/assets/7849458/17745726/fcd0b2e0-647a-11e6-90b9-d8c29b6b5959.jpg)

**Comment by LoneGazebo** [comment]
Operations looking better, however another issue arises. Once units reach their intended destination (in this case they were heading to Melbourne), those two embarked units (the gatling guns) abandon all and leave (and are not even assigned a tactical move by the AI) and the naval units just kinda...linger without a tactical move. Why? The lancers/gatling on the right are given 'offensive reposition' moves by the AI.

**Comment by LoneGazebo** [comment]
Is it an issue of range, perhaps? There aren't any open spots adjacent to Melbourne, so it seems like the AI may simply be abandoning this attack because it is too difficult.

**Comment by ilteroi** [comment]
well the first question is, why did they go to kathmandu instead of melbourne?

secondly, it's a sneak attack right? so they need to declare war. maybe that didn't happen for some reason.

thirdly, if melbourne is packed with units, it's maybe better to retreat. but i don't know if they would know that at this point without visibility there. and they're not really retreating either :)

**Comment by LoneGazebo** [comment]
It wasn't a sneak attack, no - it was a mid-war invasion. I'm just curious, as I've seen it a few times, even on sneak attacks. We'll see if new logic helps in a game that wasn't screwed with mid-invasion. :)
