### ISSUE TITLE
Ghost antiquity site

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2364]
Mod Version (i.e Date - (4/23b)): 8-12 EUI

1. Mod List (if using standard CPP set, leave blank):

ThalsFlagpromotions

2. Type of error (i.e. crash, interface bug, AI quirk): 
bug

3. Steps to reproduce:
 When trying to "unpack" a settler on a jungle tile a message appears "Are you sure you want to found a city? The current antiquity site will be permanently removed". The thing is there is no Antiquity site. Firstly, it's not visible. Secondly, I send a knight to the tile to get the A. Site, but there seems to be none.

4. Additional information:

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/420317/QuickSave.zip)

**Comment by Iamblichos** [comment]
Could be Hidden Antiquity site. But I'm not sure why you are getting that prompt if it's a Hidden Site.
