### ISSUE TITLE
Citystate War Issue

### ISSUE THREAD

**Issue by paul-r-gall** [LoneGazebo/Community-Patch-DLL#2365]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8/12

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
interface bug

3. Steps to reproduce:

4. Additional information:
Shoshone at war w/ Huns, Manila allied to Huns. Shoshone Frigate attempts to bombard Manila, gets the "Does This Mean War?" popup. 

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
At War With Huns:
http://images.akamai.steamusercontent.com/ugc/269474483223956875/5412B11B75766645092354CF9159756E84DBA41E/

Huns Allied to Manila:
http://images.akamai.steamusercontent.com/ugc/269474483223958107/D384051939433F72226C89627E14F60FBD7F85D2/

Manila Peace Blocked:
http://images.akamai.steamusercontent.com/ugc/269474483223958618/06218C283F17ABBE16AF10187A5CAB3AB8F0ED0E/

Does This Mean War?
http://images.akamai.steamusercontent.com/ugc/269474483223958380/528EFDB06D7F3C5FD87C1C738E23342318200405/

**Comment by LoneGazebo** [comment]
And if you click yes?

**Comment by paul-r-gall** [comment]
Then war gets declared - not a huge deal, but I think I should've already
been at war, right?

**Comment by LoneGazebo** [comment]
Yeah, not sure why. @ilteroi, does the 'declarewarmove' function check to see if you are already at war? :)

**Comment by pandasnail** [comment]
I know it says peace blocked, but he's likely not at war with Manila. I've seen this a few times, and been actually at peace or even been Friends with the CS in question. I've never posted because I never have a useful log or can make it happen on command for a save tho.

**Comment by LoneGazebo** [comment]
If you can get me a save, that'd be great.

**Comment by LoneGazebo** [comment]
Did the huns ally the CS during the war? Did you get a popup showing that war? Need way more info.

**Comment by paul-r-gall** [comment]
sorry :/ continued the game. Not a huge deal, but thought it was curious.

**Comment by paul-r-gall** [comment]
I'll check the auto saves.

**Comment by pandasnail** [comment]
Whenever I've seen it, its been a new ally made during the war, including a time they liberated from one of their other enemies. Always worked fine with allies made before the start.

A couple times when testing other things, I've put a bunch of CS in and tried to make it happen, but it just doesn't. If Paul doesn't have a save, I could perhaps play an only VP game, no other mod is truly essential. I assume even the #7 Community Events by Enginseer and Hokath is a no go for you to be able/willing to load a save?

**Comment by paul-r-gall** [comment]
reloaded an autosave and made it happen again. Manila is on the southwest
corner of the continent with the Huns. It says "Peace Blocked -59" but we
are NOT at war.

PG

**Comment by pandasnail** [comment]
Oh wait, by the time I could make the save, you'd def be AWOL sounds like. So maybe not then

**Comment by paul-r-gall** [comment]
And yes - Attila just allied Manila at this turn that is attached.

**Comment by LoneGazebo** [comment]
Okay, so he allied them during your war? That tells me where to look, thanks.

**Comment by LoneGazebo** [comment]
Any vassalage going on here?

**Comment by pandasnail** [comment]
Can't speak for Paul obv, but I vassalize somebody basically every game I play, so if that's the cause, that would explain both why I see it sometimes and why I can't reproduce in a test situation, yeah.

**Comment by paul-r-gall** [comment]
Yes, Sweden is my vassal.

**Comment by paul-r-gall** [comment]
FYI - playing another game and the same issue came up. Would you like that
save file as well as an additional data point?
