### ISSUE TITLE
Unit graphic on wrong tile still happens is one specific instance

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2366]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/9

1. Mod List (if using standard CPP set, leave blank):
Full VP
Enginseer's version of Events and Decisions and its add on
Enlightenment Era and Xony's Compat mod
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Redesigned Colors and Icons
Celtic City Names, Iroquoian City Names, Randomize City Names
NoAltitudeTraining (removes the Mt. Kilman promo)
My own thing that does various things SQL type stuff
Tectonic Map

2. Type of error (i.e. crash, interface bug, AI quirk): 
If the AI liberates a city I own for a different AI, the unit graphic of the liberating AI, Iroquois Knight, for instance, stays in the city even after it becomes, say, Indonesian, or even after I recapture it the next turn. Its like the other one with sight range tho, the unit is in fact on some other tile. Doesn't happen when I liberate a CS from an AI, haven't liberated a major civ city, and prob won't, that's not really part of my playstyle.

(Forgot to take a screenshot, but hopefully I explained it well enough)

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by ilteroi** [comment]
do you happen to have a savegame?

**Comment by pandasnail** [comment]
No, sorry, on account of those other mods.

**Comment by ilteroi** [comment]
yeah i wasn't too keen on installing all of those anyway :)

maybe i can guess the place where the animation is missing

**Comment by pandasnail** [comment]
Oh...I probably could get an old autosave later if you installing all those mods is a choice, I assumed it wasn't. This particular issue doesn't seem worth that you bothering with that amount of effort tho imo.

**Comment by ilteroi** [comment]
correct. i had kind of skipped over that list at the first reading ;)

**Comment by LoneGazebo** [comment]
Can confirm: 
![20160817175951_1](https://cloud.githubusercontent.com/assets/7849458/17754839/89f19026-64a4-11e6-8f80-dd213fab9ce8.jpg)

**Comment by LoneGazebo** [comment]
The spearman in Tyre is not real - it has no ID nor info on the tooltip for the plot. AI just captured it.

**Comment by ilteroi** [comment]
ok - i might have found the problem. let's see if the fix works.

**Comment by LoneGazebo** [comment]
Sounds good - lemme know when you've pushed.

**Comment by ilteroi** [comment]
merged and pushed

**Comment by ilteroi** [comment]
i think you build an endless loop in CheckTransitionToNextStage

						while(!bInPlace && pUnit)
						{
							for(iI = 0; iI < NUM_DIRECTION_TYPES; ++iI)
							{
								pAdjacentPlot = plotDirection(pUnit->plot()->getX(), pUnit->plot()->getY(), ((DirectionTypes)iI));

								if(pAdjacentPlot != NULL && ((pAdjacentPlot->getOwner() == m_eEnemy) || (pAdjacentPlot->getNumDefenders(m_eEnemy) > 0)))
								{
									pTarget = pAdjacentPlot;
									bInPlace = true;
									break;
								}
							}
						}

**Comment by LoneGazebo** [comment]
Yeah that's what I goofed. I did a bad
