### ISSUE TITLE
AI use of ranged units in cities

### ISSUE THREAD

**Issue by Zoidbergesq** [LoneGazebo/Community-Patch-DLL#2367]
**Mod Version:** 

Community Patch v. 88

**1. Mod List:** 

In addition to the Community Patch: InfoAddict (v. 22); NoAltitudeTraining (v. 1); R.E.D. Modpack (v. 27); Historical Religions Complete (BNW or GK) (v. 45).

**2. Type of error:** 

AI quirk: AI archers - and, I assume, AI ranged units in general - fortify and do nothing rather than attack.

**4. Additional information:**

When I have a strong AI city (its last one) surrounded by my archers, who are out in the open and vulnerable, the AI elects to fortify their single ranged unit (an archer) rather than bombard my ones who are attacking the city. With no other units out in the field and no possibility of reinforcements from elsewhere, the AI is essentially choosing to have its capital inevitably reduced to zero from my continuous archer bombardment rather than fighting back from the relative safety of a city by attacking my archers; it should be able to kill all three - maybe two - of my archers (who are out in the open, on flat terrain) without dying itself. 

In other words, in terms of three archers vs one archer in a city, the AI only ever seems to choose the option where it gains much less overall, choosing to remain fortified and eventually inevitably die rather than fight back and almost certainly win overall (and at least definitely kill an archer or two).

**Comment by Zoidbergesq** [comment]
I suppose I don't know if this is a deliberate choice, or a compatibility issue, or a bug..

**Comment by ilteroi** [comment]
thank you for the detailed description ... a savegame would be good to have

**Comment by Zoidbergesq** [comment]
[Dido_0165 BC-1850.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/423331/Dido_0165.BC-1850.zip)

**Comment by Zoidbergesq** [comment]
There it is. 

Does this issue sound familiar, or is something up with my game?

**Comment by Zoidbergesq** [comment]
Thanks very much for looking into this, by the way.

**Comment by Zoidbergesq** [comment]
Also, are marshes actually meant to yield 3 food (as it is in my game), rather than 1 (which is what it says in the Civilopedia)?

**Comment by pandasnail** [comment]
Marsh adds 1 food to the 2 food of Grassland, which I believe is the only place it can spawn.

**Comment by ilteroi** [comment]
yeah for some reason marshes are even better than grassland ... anyway the archer issue is not known, hope i can load the save, sometimes it's tricky

**Comment by Zoidbergesq** [comment]
Ah ok - seems a bit odd. Though I suppose they're a hassle to upgrade to farms which are, at least, eventually better than 3. And maybe back in the day marshes were decent for food.. lots of wild animals etc etc.

Yeah, I've found the archer issue in multiple games actually. So do you - in your games - get fired on by ranged AI units from cities if you're sieging it from a couple of tiles away (when the AI's field army has been defeated)? My melee doesn't get fired on either, even if they're in range of the archer (if not the city itself).

**Comment by ilteroi** [comment]
@LoneGazebo : damn, crashes on load again. care to give it a try? i really need to find out why that happens to me

**Comment by Zoidbergesq** [comment]
Is there any more compatibility info I can provide?

**Comment by ilteroi** [comment]
yes in fact. unfortunately save game compatibility is broken quite often so it is very important to know the exact version of the mod used to create it. 

even then i sometimes have trouble loading them, but seems to be a problem with my particular setup.

**Comment by Zoidbergesq** [comment]
I'm playing a new game with everything updated. I'll go to war and if it happens again I can upload that.. might be easier with everything properly up-to-date.

**Comment by Zoidbergesq** [comment]
Playing 8-12 and still the same issue: I have an AI city surrounded, from two tiles away, and it refuses to bombard me with its archer (even if I'm not attacking it), choosing instead to stay pointlessly fortified.

It even did this when I had a unit on very low health, which it could have just killed.

**Comment by Zoidbergesq** [comment]
Along with the constituent parts of the Community Patch - (1), (2), (3), (4), (5) and (6a) - I'm using Historical Religions, InfoAddict, R.E.D. Modpack and NoAltitudeTraining. Could it be an issue with any of these?

It's really frustrating! Makes combat far too east, even on immortal/deity..

**Comment by ilteroi** [comment]
in this case i don't think it could be the additional mods ... anyway, do you have a savegame from the 8/12 version?

**Comment by Zoidbergesq** [comment]
[Attila_0128 BC-2220.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/425542/Attila_0128.BC-2220.zip)

This is a situation where I have melee - rather than ranged - surrounding their city. I assume the same would happen if I had ranged units in place of the melee ones.

**Comment by ilteroi** [comment]
again no luck loading this. maybe the G can help.

i'll keep my eyes peeled for this, but i hardly have time to play anymore ...

**Comment by Zoidbergesq** [comment]
Any luck?

**Comment by ilteroi** [comment]
still figuring out #2411

**Comment by LoneGazebo** [comment]
@ilteroi any updates?

**Comment by ilteroi** [comment]
nah - are you able to load that save?

**Comment by LoneGazebo** [comment]
I can't load it either. I chalk it up to  mod conflict.

**Comment by ilteroi** [comment]
unfortunately this happens quite often, also with people who use VP and nothing else ...

**Comment by LoneGazebo** [comment]
Is your copy of Civ localized for Germany?

**Comment by Zoidbergesq** [comment]
It is not, no. It's UK.

**Comment by LoneGazebo** [comment]
Not you, sorry, @ilteroi.

**Comment by ilteroi** [comment]
good question. not sure - civ5.exe says it's english - and i play in english - but i never made a conscious choice.

**Comment by ilteroi** [comment]
@LoneGazebo : just to let you know, i'm having some problems right now, my machine crashed and visual studio is now broken it seems. since i'm juggling multiple windows sdk versions and visual studio versions it might take a while to get it back in working order.

**Comment by LoneGazebo** [comment]
Oh no! If you can give me a quick fix for the problem I mentioned on your latest fefe via github that'd be grand. If not, no worries (and no rush).
