### ISSUE TITLE
Autocracy Autarky policy doesn't give gold for internal trade routes

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#237]
http://i.imgur.com/N2KX1IZ.jpg
http://i.imgur.com/6hsUSBx.jpg
As you can see I didn't get more gold after setting the trade route to Madrid.
Moreover it seems to actually substract money instead of adding it.

**Comment by LoneGazebo** [comment]
I've now double-checked this and it works as designed. Keep in mind that the gold is added to the 'city connections' tooltip in the toppanel, not the trade UI panel.
G
