### ISSUE TITLE
Unable to close Monoploy screen 

### ISSUE THREAD

**Issue by youthinkforever** [LoneGazebo/Community-Patch-DLL#2370]
Bug Report Template

Mod Version (i.e Date - (4/23b)): Current version (1.8.12)

1. Mod List (if using standard CPP set, leave blank):

Using Vox Populi with EUI, automatic installer

2. Type of error (i.e. crash, interface bug, AI quirk): 
When I start up a game the Monoploy screen opens and i'm unable to close it. Iv'e looked over the other similar cases and tried to delete all the mods I didn't use, I've deleted my cache and it still doesn't work.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Mod conflict with ExCE. Update that mod.

**Comment by youthinkforever** [comment]
How?

**Comment by youthinkforever** [comment]
I've downloaded the newest version of the mod, doesn't that automatically update it?

**Comment by LoneGazebo** [comment]
I don't make ExCE, JFD does.

**Comment by youthinkforever** [comment]
What is the ExCE? I can't update it if I dont know what it is, sorry I don't really play with mods out of the workshop

**Comment by LoneGazebo** [comment]
I'm assuming you have it installed. If not, you need to reinstall the modpack and make sure no other mods are in your mods folder.

**Comment by youthinkforever** [comment]
I didnt have any mods in the folder, I had unsubed and deleted all of them because I had read the other similar thing with the screen. When I had reinstalled it i deleted the lua files for the community patch and the community overhaul. The time i did it just now i only deleted the lua from the community patch and the event screen was open and didnt close

**Comment by youthinkforever** [comment]
I didnt delete any lua files and it seems to be working now, thanks for putting up with me.

**Comment by LoneGazebo** [comment]
Yep. In the future, the auto-installer should do everything for you automatically, no file deletion required.
