### ISSUE TITLE
Can't build Barracks in Copenhagen for some reason

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2372]
And thus locking me out from the whole building line.
The save: https://mega.nz/#!mUEHHDAD!Qn1u80FnKb8g7Bi52pT6YtjyHMxzCIymL9GvI7ggmIs
Additional mods:
http://steamcommunity.com/sharedfiles/filedetails/?id=79000477
http://steamcommunity.com/sharedfiles/filedetails/?id=181362854
http://steamcommunity.com/sharedfiles/filedetails/?id=220250184

**Comment by LoneGazebo** [comment]
I couldn't load the save, even with the mods. Very odd. database.log?

**Comment by Radost** [comment]
https://mega.nz/#!KFNFRboY!MqfIa0MFQZlVDJZIuokIsaZ2whZ533rkFbKW7LyNVnk

**Comment by LoneGazebo** [comment]
I cannot reproduce this. Fluke?

**Comment by Radost** [comment]
That save was on the previous big version. I think it was 8/2 with all hotfixes.
