### ISSUE TITLE
high memory consumption while loading a savegame

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2375]
so i've been having this issue where the game crashes although the version of the savegame and the DLL match.

interesting data point: it may be an out of memory problem ....

this is while loading
![image](https://cloud.githubusercontent.com/assets/1358966/17763534/a3b2dc16-6519-11e6-86a5-952a2524ec40.png)

this is after loading succeeded for a change
![image](https://cloud.githubusercontent.com/assets/1358966/17763556/b68bd78e-6519-11e6-9512-aa7d23684905.png)

any idea where that memory might be going? is it the same for you?

**Comment by LoneGazebo** [comment]
No, mine is substantially lower than that. Are you getting any database errors?

**Comment by Freaky-Freddy** [comment]
I also been having crashes when loading saves, usually the 3ed or 4th time i load during a game. Don't know if it's related.

**Comment by ilteroi** [comment]
@Freaky-Freddy : that's a different issue, probably related to EUI and/or InfoAddict.

@LoneGazebo : don't think so, nothing substantial at least
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/425510/Database.zip)

**Comment by LoneGazebo** [comment]
I am curious about:

[3324904.751] no such table: LoadedFile
[3324904.751] no such table: LoadedFile
[3324904.767] no such table: LoadedFile

What's that link to you in your stopwatch.log?

**Comment by ilteroi** [comment]
[Logs-Backup.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/425610/Logs-Backup.zip)

this is with the save from #2350 - memory starts out at 800 MB with all mods loaded. then after i select the savegame to load, it creeps up to 2.2 GB (during the black screen phase). then when the actual loading screen with the leaderhead appears, it drops to 1.2 GB. when loading is finished, it's at 1.4 GB.

**Comment by ilteroi** [comment]
maybe a red herring ... just got a crash on the latest save from #2367 with very low allocation:

![image](https://cloud.githubusercontent.com/assets/1358966/17786105/bcb8dbce-6583-11e6-84fb-8c49c7145a16.png)

it happens while the map is being loaded:

![image](https://cloud.githubusercontent.com/assets/1358966/17786383/dfe03560-6584-11e6-8418-40be8da90c35.png)

all plots after 572 already have invalid values, at plot 646 (of 4480) the stream becomes invalid and boom. wtf.

**Comment by LoneGazebo** [comment]
Huh. What script?

**Comment by LoneGazebo** [comment]
Also memtest in your PC sounds like a good idea.

**Comment by LoneGazebo** [comment]
On your PC*

**Comment by ilteroi** [comment]
my memory is fine! what's my point again?

**Comment by Freaky-Freddy** [comment]
@ilteroi

Thanks for the heads up. I don't have infoadict but i am using EUI. Do you think it might be an installation problem or is it known bug?

PS: Sorry if i'm being annoying by crashing in on your conversation btw
