### ISSUE TITLE
Airlift to an enemy city

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2376]
Mod Version (i.e Date - (4/23b)): 8-12

1. Mod List (if using standard CPP set, leave blank):
 ThalsFlagPromotions

2. Type of error (i.e. crash, interface bug, AI quirk): 
 bug?

3. Steps to reproduce:
 When unlocking an Autocracy airlift tenet I'm now able to airlift my units to an enemy city. It might be intended, although it makes little sense IMHO. 
 Note that I'm able to airlift to one city and unable for another. Probably has to do with an airport present.

4. Additional information:

 
![20160818164330_1](https://cloud.githubusercontent.com/assets/16341598/17775999/7dd718a0-6563-11e6-833e-aa72730ee27b.jpg)

**Comment by ilteroi** [comment]
can't reproduce ...

![image](https://cloud.githubusercontent.com/assets/1358966/17839099/2155a22c-67de-11e6-8e79-fb98385df6e5.png)

**Comment by Edaka** [comment]
Perhaps neither Baghdad nor Medina had an airport?

**Comment by ilteroi** [comment]
oh. i missed that part ... need to retest then
