### ISSUE TITLE
AI not expanding

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2378]
Mod Version (i.e Date - (4/23b)):8-12

1. Mod List (if using standard CPP set, leave blank):
Thals FlagPromotions

2. Type of error (i.e. crash, interface bug, AI quirk): 
AI flaw

3. Steps to reproduce:
 After getting vassalized by me France has given up any attempts at expanding. For hundreds of years they have been pretty content with having a single city despite having a nice unoccupied continent next to them. 

![20160818175941_1](https://cloud.githubusercontent.com/assets/16341598/17778807/03609b22-656e-11e6-928f-4a32920a8a5b.jpg)

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/425225/QuickSave.zip)

**Comment by ilteroi** [comment]
and they do have a settler waiting, i think that's an issue gazebo has been mentioning as well ... taking a look right now

**Comment by LoneGazebo** [comment]
I've done a lot on this lately, ilteroi, hold off.

**Comment by LoneGazebo** [comment]
@ilteroi grab my latest (just uploaded DLL files and Community Patch to github). Merge up, some good stuff in there! :)

**Comment by ilteroi** [comment]
ok - anyway in my analysis it seems the escorts on an AI_OPERATION_FOUND_CITY_OVERSEAS seem to be optional, is that right? so none are recruited, and the operation is abort because the destination plot is not deemed safe. rinse and repeat.

406, France, AI_OPERATION_FOUND_CITY_OVERSEAS, 331, Started, Army: 9057, Units Recruited: 1, Max Formation Size: 4, Gathering Forces

**Comment by LoneGazebo** [comment]
I fixed that.

**Comment by ilteroi** [comment]
nice!

by the way, is it possible that for a diplomat mission the civilian is not in the first slot? i found that in my notes, don't know where to check this quickly ... if it's true it's bad, because by convention the civilian has to come first. care to check?

**Comment by LoneGazebo** [comment]
Uhh I'll check!

**Comment by LoneGazebo** [comment]
One thing also to look at - remove stuck units (in cv army) fires very often. Can't tell if a bug in inplementation or if army unit selection needs an adjustment.

**Comment by LoneGazebo** [comment]
Oh poo, there's an infinite loop in my code. Merging and pushing update real quick.

**Comment by ilteroi** [comment]
hehe. just found that out myself

**Comment by Iamblichos** [comment]
Yeah I got that too when I simmed your code. If I'm getting what you are talking about, I got a hard hang around turns ~25-40 thereabouts.

**Comment by Iamblichos** [comment]
Let me know when you upload again.

**Comment by LoneGazebo** [comment]
I updated.

**Comment by LoneGazebo** [comment]
Not on GitHub yet will fix shortly.

**Comment by LoneGazebo** [comment]
Merge and loop fixed.
