### ISSUE TITLE
Aesthetics Historic Event different tourism points than regular Historic Event

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2379]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/12

1. Mod List (if using standard CPP set, leave blank):EUI version

2. Type of error (i.e. crash, interface bug, AI quirk): I know this was mentioned already on the forums, but I wanted to see if I had it anyway, so I figured I'd post it with a save. If you open the Save, I've just chosen Aesthetics National Treasure, from there choose Great Artist, and the tourism points for getting the Artist will be different than the tourism from his or her Golden Age. I saved again after too, just in case its helpful.

[Pacal_0223 AD-1906.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/426204/Pacal_0223.AD-1906.zip)

3. Steps to reproduce: 

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![he1](https://cloud.githubusercontent.com/assets/16260521/17796970/db34ba64-6592-11e6-9228-2c06e5f6043f.jpg)
![he2](https://cloud.githubusercontent.com/assets/16260521/17796972/dfa5ef78-6592-11e6-8f14-95142b0de3a7.jpg)

**Comment by LoneGazebo** [comment]
Fixed in latest.
