### ISSUE TITLE
EUI queueing issues

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#238]
Especially with CBP espionage changes where I had to manage 30+ spies.
Right now it shows current event, but after the clicking on it, switches to the next event and activates it. Which doesn't make a diplomacy any easier when I have 10+ notifications in a row and I think it causes the bug when I can both warn them to not to spy and forgive for it. Though I don't know if it was the case with the same event or it were 2 different ones from the same leader.
This is not only espionage problem, it is just pronounced strongest in it.

Also queueing of claimed tiles notifications would be fine too. If I remember right bc1 had to go through loops because there are no notifications for claimed tiles in the base game. But you can make them a proper event in your mod, right? And remove tiles notifications on a city capture.

And the last, I think EUI queues should have some additional shortcuts: 
ctrl+RMB - remove only this item from queue
ctrl+LMB - activate the current event you are viewing without removing it (should be ignored in case of spy reports).

**Comment by LoneGazebo** [comment]
These are requests for EUI, and should be passed on to bc1, not me.
