### ISSUE TITLE
Community Patch Freezing Civ V

### ISSUE THREAD

**Issue by The-Big-O-Face** [LoneGazebo/Community-Patch-DLL#2382]
Bug Report Template

Mod Version (i.e Date - (4/23b)): Community Patch (8/12)

1. Mod List (if using standard CPP set, leave blank):

mix of this as a standalone, and the other default Vox Populi installed ones

2. Type of error (i.e. crash, interface bug, AI quirk): 

crash

3. Steps to reproduce:

I can get to the mods screen, activate the mods, then select my country.  The loading screen works fine, but when I hit the button that says "Begin Journey" the game crashes.  When in full screen, I have to physically shut off the laptop because I can not exit the application even with Alt+Tab.  To view the problem better, I played in windowed mode and opened my task manager.  I've noticed that, for this mod only, the disk utilization percentage becomes 100% when the application attempts to start the Civ Journey if you will.

Up until today, I hadn't had any problems with it.  I first noticed the error after attempting to restart a game (shit spawn location).  Ever since then, I haven't been able to use that particular mod.  When disabling it, other mods that don't depend on it work fine.  I've tried adjusting the graphics level, deleting the local cache, verifying the game cache, and even performing a clean install of the game from steam and a re-download of the mod.  None of those options made the Patch work.

I'm really at a loss as to why the game won't run this patch.

4. Additional information:

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/426287/Logs.zip)

**Comment by LoneGazebo** [comment]
Step up to the latest version. Also make sure that you have all DLC etc.

**Comment by The-Big-O-Face** [comment]
I have the latest version, and all of the available DLC.  Now it's crashing on other mods.  I seem to only be able to play the vanilla mode

**Comment by LoneGazebo** [comment]
If crashing on other mods, verify your integrity, make sure you are on latest version of civ.

**Comment by The-Big-O-Face** [comment]
Integrity verified, 1.0.3.279 is the version I have.  It's set to auto-update through steam.  And now I can't use any mods.  I don't know what happened.  The game was fine a few hours ago

**Comment by LoneGazebo** [comment]
Delete all mods, remove EUI from DLC folder, and then try again.

**Comment by The-Big-O-Face** [comment]
Vanilla works fine, using even one mod causes the game to irreversibly freeze forcing me to dump the process tree from the Task Manager

**Comment by The-Big-O-Face** [comment]
Mods deleted, don't see the EUI DLC
![image](https://cloud.githubusercontent.com/assets/21116953/17800416/101ddb8e-65b1-11e6-8a90-ee8806550d20.png)

**Comment by LoneGazebo** [comment]
It is in your dlc folder.

**Comment by The-Big-O-Face** [comment]
The above photo is of the DLC folder.  Unless it's listed as something else, or nested in one of the other folders, it's not in there.

**Comment by LoneGazebo** [comment]
Hmm. Search for UI_bc1 on your machine, see if it ended up somewhere else. In any case, redownload the latest auto installer and run it. Once run, make sure there are no other mods in your mods folder aside from (1) thru (6a). Enable them, hit next, and then start a game from the next page. Should work.

**Comment by The-Big-O-Face** [comment]
Didn't work :-/

![image](https://cloud.githubusercontent.com/assets/21116953/17829323/206ba250-6679-11e6-8ac1-6a86f48ebc6a.png)

I just don't understand what the issue is.  Even a clean install didn't change it.  It can't be a computer issue because other games and this one minus mods work fine.

Is there a certain site to download Vox Populi from?  Perhaps the site I used has a corrupt file.

**Comment by LoneGazebo** [comment]
Are you on civ fanatics? 

Sounds like you have a nonstandard civ install. Try the manual install instructions on civ fanatics.

**Comment by The-Big-O-Face** [comment]
I think the automatic download came from civ fanatics, but I get redirected to some site called MEGA hosted in New Zealand

**Comment by Iamblichos** [comment]
That's where Gazebo uploads the files for download.

**Comment by The-Big-O-Face** [comment]
Ok.  So I'm kind of a moron, and I'm going to blame some of it on you guys as well haha.  Shame on me for not reading the install manual for proper load order of the mods.  When Civ V opens in the mod screen, this is what I see:

![image](https://cloud.githubusercontent.com/assets/21116953/17832974/a11c73c8-66df-11e6-8b60-e9c21002b2b6.png)

I naturally thought that you mad the load order easier.  Turns out, More Luxuries needs to load last, not 5th.  Again, shame on me for not reading the manual, but I was totally confused, and I think it used to work fine in the past because on the original install a few weeks ago, I didn't have any problems.

Strange, but thank you!!

**Comment by LoneGazebo** [comment]
No worries!
