### ISSUE TITLE
No-EUI Compatibility Files breaks production

### ISSUE THREAD

**Issue by Glidergun** [LoneGazebo/Community-Patch-DLL#2384]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

8/18

1. Mod List (if using standard CPP set, leave blank):

Standard set, no-EUI version.

2. Type of error (i.e. crash, interface bug, AI quirk): 

Interface bug: cannot select production for cities, trying to bring up the menu does nothing.

3. Steps to reproduce:

Starts right as soon as you settle your capital. Does not occur with just CP, or CP+CBO, it's only when I get to the full suite that I get problems.

4. Additional information:

The Lua log ends with many lines consisting of: "Runtime Error:[...]Sid Meier's Civilization 5\MODS\(6b)  Community Balance Overhaul - Compatibility Files (No-EUI)\LUA\ProductionPopup.lua:861: attempt to call global 'DoUpdateProductionInfo' (a nil value)"
I expect this is the problem.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

[productionproblemlogs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/426407/productionproblemlogs.zip)

**Comment by LoneGazebo** [comment]
I'll take a look.
