### ISSUE TITLE
"City is ready for Poduction" icon stays forever

### ISSUE THREAD

**Issue by gendalv** [LoneGazebo/Community-Patch-DLL#2385]
Mod Version (i.e Date - (4/23b)): happened in all I've used I think
1. Mod List (if using standard CPP set, leave blank):
full install+eui
2. Type of error (i.e. crash, interface bug, AI quirk): 
UI
3. Steps to reproduce:
the easiest is to merchant of venice a city-state
4.
Reloading a current save removes it.
[screen](https://s4.postimg.io/x7uk16wjh/qwe.jpg)

**Comment by gendalv** [comment]
??

**Comment by LoneGazebo** [comment]
Mod conflict most likely.

**Comment by gendalv** [comment]
I'm using it with eui and infoaddict
installed via installer

**Comment by Edaka** [comment]
It's likely an ancient EUI bug, and the dev team doesn't deal with those. You should contact EUI's author.
