### ISSUE TITLE
AI offers peace deals that it does not accept

### ISSUE THREAD

**Issue by kenneth1221** [LoneGazebo/Community-Patch-DLL#2387]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-18

1. Mod List (if using standard CPP set, leave blank):
Historical Religions

2. Type of error (i.e. crash, interface bug, AI quirk): 
AI quirk

3. Steps to reproduce:
This may only apply during ancient & classical eras; I didn't get far enough to check otherwise.
When willing to make a peace deal, AI players will give offers that are "Impossible" from their end. This occurs both when they offer peace, and when the human player asks them what deal will end the war. This seems to only occur when the AI offers a city as part of the peace deal.

![20160819090356_1](https://cloud.githubusercontent.com/assets/18664482/17812886/0a851084-65f7-11e6-9a35-fa954ea9dba3.jpg)
![20160819092032_1](https://cloud.githubusercontent.com/assets/18664482/17812884/0a823a62-65f7-11e6-958f-8b4ff749f3cc.jpg)
![20160819092051_1](https://cloud.githubusercontent.com/assets/18664482/17812887/0a8562c8-65f7-11e6-873e-3dd19b45e87b.jpg)
![20160819092055_1](https://cloud.githubusercontent.com/assets/18664482/17812885/0a82e32c-65f7-11e6-9944-9ca0ac03eca2.jpg)

Screenshots show the variety of situations in which AI will offer these deals.

**Comment by LoneGazebo** [comment]
Interesting. I'll need to look at this later.

**Comment by LoneGazebo** [comment]
If you have a savegame, that'd be great.

**Comment by LoneGazebo** [comment]
@ilteroi and @Iamblichos, if savegame gets posted, mind taking a look?

**Comment by kenneth1221** [comment]
[AutoSave_0220 AD-0700.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/427488/AutoSave_0220.AD-0700.zip)

This is the latest save I have of that game. Should still be at war with both America and Sweden.

**Comment by Iamblichos** [comment]
Can't for a few days. Took my family to Florida. Will have Internet access but not til Monday.

**Comment by LoneGazebo** [comment]
Fixed in hotfix. Had a spare moment.
