### ISSUE TITLE
My Upcoming Absence

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#2388]
@ilteroi, @Iamblichos, and all others, I'm going to be out for a little while as of...now, so I'd greatly appreciate it if you two would take point on minor bugfixe and hotfixes for the CP over the next few days. 

Thanks!

G

**Comment by Iamblichos** [comment]
Man tough timing. I'll do what I can. But I'm on family vacation til Saturday the 27th.

**Comment by Iamblichos** [comment]
When I get back, I'll pick up the slack for sure.

**Comment by LoneGazebo** [comment]
No worries, usually any game breaking bugs are noted in first 24h. Thus far nothing bad!

**Comment by Iamblichos** [comment]
Congrats on your up coming baby and being a new daddy. Don't worry about github. Help your wife out, she'll need it. And you'll need to make time for rest when you can.

**Comment by LoneGazebo** [comment]
Thanks! Definitely not worried, just wanted to let everyone know that I'd be a little less available for a week or so.

**Comment by ilteroi** [comment]
i hope it all went well and you're having a good time!

greetings from bavaria ... spot the gazebo :)

![150439](https://cloud.githubusercontent.com/assets/1358966/17905447/5686d20e-6973-11e6-8ecc-00e912c2eec2.jpg)

**Comment by LoneGazebo** [comment]
All well thus far. A beautiful baby girl has arrived in my life. 

Don't anger that gazebo by shooting it with arrows or anything. :)

**Comment by LoneGazebo** [comment]
Quite the backlog building up around here...ill be back after it next week, so let's divide and conquer on the current open issues?

**Comment by Iamblichos** [comment]
Yes I'll be back in gear on Monday 29th. Still out on vacation.

**Comment by LoneGazebo** [comment]
Sounds good. That's what I figured, and is around the time that I'll be back in gear.

**Comment by LoneGazebo** [comment]
I'm back, going to start crunching through list of bugs. @Iamblichos you've been prowling the forums a bit more, any bugs/balance issues that haven't been brought up here?

**Comment by Iamblichos** [comment]
@LoneGazebo, I think we pretty much got them all here. The two main show stopper are the ability not to declare peace deals and for whatever reason the passive AI stuff. Everything else is really really minor.

**Comment by LoneGazebo** [comment]
Sounds good. I'm working on building/unit AI production logic right now, going to shift to peace deals/3rd party peace this afternoon.
