### ISSUE TITLE
Diplomacy Interface Bugged and Unusable

### ISSUE THREAD

**Issue by Branbados** [LoneGazebo/Community-Patch-DLL#2389]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 
    8/12
1. Mod List (if using standard CPP set, leave blank):
    Core Community Patch
2. Type of error (i.e. crash, interface bug, AI quirk): 
    Interface Bug
3. Steps to reproduce:
    Start new game, interact with any civ in the diplomacy screen
4. Additional information:
    I've been told this is the result of a mod conflict, but I've done a completely clean install, running only the core community patch, and this still happens. I'd very much like to be able to play this mod, could I get advice on how to fix this?
I found this in the Lua log that looks related:
[802667.031] Runtime Error: C:\Users\Brandon\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\LUA\TradeLogic.lua:203: attempt to call global 'DoClearTable' (a nil value)

---------------------------
Supporting information:

1. Log files:
    Database log: http://pastebin.com/bep0QuZ7
    Lua Log: http://pastebin.com/mptQ4brF
2. Minidump file (located in your Civ5.exe directory):
     Absent from game files
3. Screenshots (if needed):
     http://imgur.com/a/o7oON

**Comment by LoneGazebo** [comment]
Update to latest version.

**Comment by Branbados** [comment]
It works! Thanks for your help!
