### ISSUE TITLE
Error in the values calculated in techtree tooltip and pedia info box for Technologies

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2390]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
August 18th (also visible in earlier versions)

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Possibly a rounding error or an incorrect variable in the Lua.

3. Steps to reproduce:
If you mouseover a Tech in the TechTree, or view the page for a tech in the pedia, the values shown for the required science is always around 13% inflated to that which is defined in the database.

4. Additional information:
The text now shown in the "Game Info:" box in the pedia, which is the same as the tooltip on the TechTree, is displaying values that don't match that shown in the "Cost:" box to the left in the pedia.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Isn't that because of the cost added from cities?

**Comment by GrantSP** [comment]
No, it shows that way from the very beginning of each game, even without founding your first city.

**Comment by LoneGazebo** [comment]
Is it because of gamespeed research mods? The Lua uses the core DLL element.

**Comment by GrantSP** [comment]
This is only with the full VP package, no extra mods installed.
![pedia error](https://cloud.githubusercontent.com/assets/3291695/17827958/c18a6d10-66c9-11e6-97b4-8cf4a51d4d7a.png)

**Comment by LoneGazebo** [comment]
Value is correct - left side is unmodified, right is modified. DLL assumes 1 city for cost projection.

**Comment by GrantSP** [comment]
What?!
Okay, now I'm conflicted. I can see the value of showing these modified values but now I see that the base cost, and the modified value, for each tech is different based on game level. This means depending on what game level you are playing, the cost may be different.
So my question is this: as far as the wiki is concerned what needs to shown?
Secondly are we moving towards dropping the unmodified figure from the pedia?

**Comment by LoneGazebo** [comment]
We could, depends on how important that info is.
