### ISSUE TITLE
Building event bonus not applying to a building from colonists (8-12)

### ISSUE THREAD

**Issue by Freaky-Freddy** [LoneGazebo/Community-Patch-DLL#2392]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8-12 (don't know if it got fixed in 8-18 so posting just in case)

1. Mod List (if using standard CPP set, leave blank): 

RED
Faster Aircraft

2. Type of error (i.e. crash, interface bug, AI quirk): bug

3. Steps to reproduce:

I got the event that gives 15% production increase to windmills and it applies just fine to existing windmills and windmills that i build myself, but windmills that are built automatically by colonists are not getting the bonus.

4. Additional information:

Haven't tried it yet but selling it and building a new windmill is probably a good workaround. I can post screenshots if need.

**Comment by Edaka** [comment]
I'm not sure about this, but I think the building bonuses from events don't apply to new cities founded by any means, be it settlers, colonists, whatever, if they're founded after taking the event choice.

**Comment by Freaky-Freddy** [comment]
That doesn't make sense because like a i said, any windmills that i build myself **even after the event** get the bonus, it's just the ones that are built automatically by colonists that don't get it.

**Comment by LoneGazebo** [comment]
I'll take a look. Probably an issue with ordering (i.e. event bonus is being applied after free buildings are applied).
