### ISSUE TITLE
Crash on turn 395, 12/8 version

### ISSUE THREAD

**Issue by Valvts** [LoneGazebo/Community-Patch-DLL#2393]
[crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/428345/crash.zip)

Mod Version (i.e Date - (4/23b)):
12/8

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Crash on turn 395

3. Steps to reproduce:

4. Additional information:
One turn after Venice capital was captured, game crashed on Venice turn. It happen on the last version too, when Venice capital was captured. 

---------------------------
Supporting information:

**Comment by LoneGazebo** [comment]
I can't debug prior versions, sorry.

**Comment by Valvts** [comment]
Ill start a new game I guess, but can you check the think with Venice losing its capital? Because I had the same scenario happen to me previous version too, exactly the same.

**Comment by ilteroi** [comment]
if it's reproducable, create a new issue
