### ISSUE TITLE
BUILDINGCLASS for Venetian unique buildings

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2394]
Currently the 3 unique buildings for Venice are set to look for the generic National Monument as a prerequisite. If we create a new buildingclass: BUILDINGCLASS_PIAZZA_SAN_MARCO, this will allow the pedia to show the correct unique building for Venice as the Piazza San Marco instead of the generic.

Something to look at maybe?

**Comment by LoneGazebo** [comment]
Wait, generic what?

**Comment by Edaka** [comment]
I think he means that the 3 unique Venetian buildings currently have the generic National Monument instead of the Piazza listed as a prerequisite in the pedia.

**Comment by LoneGazebo** [comment]
Ah. That's not a huge deal (IMO).

**Comment by GrantSP** [comment]
Correct. It isn't a huge deal but it would make it easier to see what is actually happening.
I don't see any major obstacles to the database as nothing will be affected aside from the Venetian buildings, however as it isn't a vital change I though it prudent to raise the question first. If you don't think it is worth the change, that's fine.
