### ISSUE TITLE
Two Requests

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2395]
I have two requests.

**GameEvents.CityPuppeted(playerID, cityID)** -- this would trigger when a city is turned into a puppet.
**city:GetNumBuildings()** doesn't count buildings that are maintenance free (such as those given by Wonders). Would it be possible to make it so that it does?

Hopefully these are possible, but if not, let me know.

No rush, as always (esp. as you note an upcoming absence).

 Thanks!

**Comment by Iamblichos** [comment]
Yep. Will work on this next week JFD when I get back in town from vacation.

**Comment by LoneGazebo** [comment]
GetNumBuildings grabs a special int IIRC. You'll probably need a custom function to get that value.

**Comment by TechpriestEnginseer** [comment]
GameEvents.CityPuppeted(playerID, cityID) isn't documented in CustomModOptions.xml below for JFD's Piety or such and should be fixed for latest upcoming versions.
