### ISSUE TITLE
Resource trade deals messing up

### ISSUE THREAD

**Issue by MasterElements** [LoneGazebo/Community-Patch-DLL#2396]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
V. 88 with the vox installer

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Deals involving luxury and strategic resources don't "end" when I am exporting a resource. In the deals log they show a negative turn when completed. The Ai still has my resource but isn't paying me for it anymore.

3. Steps to reproduce:
Trade away a resource and wait.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Update to latest version. 8-18.
