### ISSUE TITLE
CTD when interacting with a Civ twice

### ISSUE THREAD

**Issue by M3T4** [LoneGazebo/Community-Patch-DLL#2397]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
08/18

1. Mod List (if using standard CPP set, leave blank):
Fallout - City States (v. 5)
InfoAddict GNK (v. 19)
Strange Religions (v.9)
Faster Aircraft Animations (v. 3)
Historical Religions (BNW or GK) (v. 55)
Sukritact's Events and Decisions (v. 3)
JFD's The Soviet Union (Stalin) (v. 13)
JFD's Cultural Diversity (Core) (v. 9)
and the CBP that is automatically installed.

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD

3. Steps to reproduce:
Interacting with a certain Civilization twice.

4. Additional information:
Every time I play with the Community Patch, there is one, just a single Civ, that causes a CTD. It's also not always the same, because the last three times I tried to start a new game it were first the Osman Empire, then India, and most recently France.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/428756/Logs.zip)

2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
You don't have logging enabled. Enable logging. replicate crash, then post logs.
