### ISSUE TITLE
AI negotiated Peace on my behalf.

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2398]
![8930_20160821182420_1](https://cloud.githubusercontent.com/assets/1131228/17837460/0128cfee-67cd-11e6-97bc-77fc87753858.png)
On the third turn of the war. Nothing even happened outside of me losing a scout.

**Comment by ilteroi** [comment]
who declared the war?

**Comment by Radost** [comment]
It was me.

**Comment by ilteroi** [comment]
ok - that changes the situation - but i'll keep my finger off that, it's Gazebos turf.

**Comment by Edaka** [comment]
How about making third party peace negotiations possible only with somebody who has a substantial war score, i.e just winning is not enough - REALLY winning is required. I think that would make the situation slightly better.

**Comment by LoneGazebo** [comment]
I'm fine with tweaks to this on the DLL side. The code is dead simple in deal classes. We can tighten those requirements if desired. We can also tighten AI proclivity towards making this deal.

**Comment by LoneGazebo** [comment]
I leave it up to your respective discretion
