### ISSUE TITLE
barbarian city has attack range of 3?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2399]
this comes from lua via GAMEEVENT_GetBombardRange()

is that intended?

**Comment by LoneGazebo** [comment]
No. I wonder if whoward's bombard range mod doesn't account for barbs?

**Comment by Iamblichos** [comment]
Gazebo, do barbs have a tech level?

**Comment by LoneGazebo** [comment]
I think so? They get same tech level as minors IIRC.

**Comment by ilteroi** [comment]
it was in classical era ...

**Comment by LoneGazebo** [comment]
Sounds like whoward's bombard stuff doesn't account for barbarian tech level, that's all.

**Comment by Iamblichos** [comment]
This will be an easy fix in lua.

**Comment by LoneGazebo** [comment]
@Iamblichos can you take point on this?

**Comment by Iamblichos** [comment]
yes....working on these all day.

**Comment by Iamblichos** [comment]
```
function Initialise()
  for row in DB.Query("SELECT ID, BombardRange, BombardIndirect FROM Technologies WHERE BombardRange > 0 ORDER BY BombardRange ASC, BombardIndirect ASC") do
    local iTech = row.ID
    local iRange = math.min(GameDefines.MAX_CITY_ATTACK_RANGE, row.BombardRange) * ((row.BombardIndirect == 1) and -1 or 1)
  
    gBombardTechs[iTech] = iRange
  
    for iTeam = 0, GameDefines.MAX_CIV_TEAMS-1, 1 do
      if (Teams[iTeam]:IsHasTech(iTech)) then
	    gTeamRange[iTeam] = iRange
	  end
	end
  end
end
```

I'm pretty sure that Barbs don't fit into MAX_CIV_TEAMS

**Comment by LoneGazebo** [comment]
It does: 

#define BARBARIAN_TEAM										((TeamTypes)MAX_CIV_TEAMS)

**Comment by Iamblichos** [comment]
Yeah just saw that...hmmmm.

**Comment by LoneGazebo** [comment]
So the -1 needs to be removed. Seems simple enough.

**Comment by Iamblichos** [comment]
Barb gets assigned 63 right?

**Comment by Iamblichos** [comment]
or 80 if it's really Max

**Comment by Iamblichos** [comment]
playing a game now...when a city state gets captured I'll rewrite the LUA and see if that does it.

**Comment by LoneGazebo** [comment]
Coolio. You can also just force it by plopping a barb unit on a CS.

**Comment by Iamblichos** [comment]
Fixed.

**Comment by LoneGazebo** [comment]
yay

**Comment by Iamblichos** [comment]
Yeah, this is an issue that has been there since day 1. Never really cared too much about it since sieging barb cities is a rarity.
