### ISSUE TITLE
Can't choose "View the city" option on capture with "Liberation" option present

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#240]
As the title says.

**Comment by LoneGazebo** [comment]
Can you clarify a bit more?

**Comment by Radost** [comment]
http://i.imgur.com/qPi9Hj2.jpg
http://i.imgur.com/wlST3TB.jpg
Basically if a city can be liberated and razed, the option for preview will be omitted.

**Comment by LoneGazebo** [comment]
Ah. This is unavoidable, as the lua box is only so large.
