### ISSUE TITLE
CTD during end turn processing

### ISSUE THREAD

**Issue by JimBobRedneck** [LoneGazebo/Community-Patch-DLL#2400]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/18 (w/hotfix) - EUI version

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): CTD

3. Steps to reproduce: Using attached savegame, simply hit End Turn. Decline trade deal proposal from England and CTD will happen a little later, possibly at very beginning of my next turn.

4. Additional information: Known things that will happen next turn - Treasure Fleet should complete, captured Assyrian city will finish razing.

[Civ5 CTD Egypt.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/429236/Civ5.CTD.Egypt.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Cannot load save. Odd.

**Comment by LoneGazebo** [comment]
Ah, I got it. I see what it is. I'll fix now.
