### ISSUE TITLE
'At war' flag does not turn off when war ends by conquering a civ's last city.

### ISSUE THREAD

**Issue by hugorune** [LoneGazebo/Community-Patch-DLL#2403]
Mod Version: (August 18th - hotfixed a couple of days later, noticed on other recent versions too)

1. Mod List (if using standard CPP set, leave blank):

JFD's Cultural Diversity (core) with bonuses switched off, Cultural Diversity (soundtrack), Randomize City Names

2. Type of error (i.e. crash, interface bug, AI quirk): 

When engaging in total war, if you do not formally sign peace but instead conquer the AI's last remaining city, you will remain at war forever.

3. Steps to reproduce:

As above.

4. Additional information:

The main consequence for this, from what I can see, is that being at war triggers different events. Unsure of the impact on the war weariness mechanic.

I reproduce this without Cultural Diversity as well. I haven't tried reproducing without Randomize City Names, but I don't believe a mod that simple would be responsible for this.

[Augustus Caesar_0234 AD-0890.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/429361/Augustus.Caesar_0234.AD-0890.zip)

---------------------------

**Comment by TechpriestEnginseer** [comment]
I'm unable to replicate this. How do you know the "at war" flag is not turned off? (I used the Firetuner to see whether or not my civ was still at war after capturing the enemy's capital swiftly in 1 turn)

**Comment by hugorune** [comment]
There are two symptoms of it. 1 is that you can read your advisors and your military advisor will say 'We are at war, etc'
2 is that the special events for wars will trigger when your empire is in this state, for example the one that gives bonus production in your cities and morale to your units, and the one that makes adjustments to hospitals.
I don't know what all the other impacts are.

On the other hand, you will not have war music playing, and you will not see any indication that you are at war in your diplomacy (as the civ you have the war flag set with is no longer on the map).

It is a state of both being at war and not being at war, if that makes sense.

**Comment by hugorune** [comment]
Trying to look through the source with my limited understanding of how it hangs together, but I'm not 100% sure where the problem is. I think the isAlive function probably isn't being called in two places where it should be, at least one in the advisor panel code, and two in the code that's driving the event system (e.g. it thinks you're at war with a civ and you are, but that civ is dead so it should be ignored).
I may be off track entirely though.
