### ISSUE TITLE
Work boats can be used on ice

### ISSUE THREAD

**Issue by JimBobRedneck** [LoneGazebo/Community-Patch-DLL#2404]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/18 (w/hotfix) - EUI version

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Invalid tile improvement

3. Steps to reproduce: Move a work boat to an ice tile in your territory. Option to improve the tile appears.

4. Additional information: Using the tile improvement option expends the work boat as normal, but the ice tile remains unworkable/no yields. The tooltip from hovering over the tile afterwards shows that the tile needs repaired.
![ice fishing](https://cloud.githubusercontent.com/assets/21163942/17844794/d2920c32-6802-11e6-88f2-6cfe48b5efb8.jpg)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by ilteroi** [comment]
it seems we need to set getFeatureInfo(...)->isNoImprovement() to true for ice.

also, getImprovementInfo(...)->GetFeatureMakesValid(...) is true for fishing boats and ice, which seems fishy :)

changing either one should fix this, but i don't know where to do that.

**Comment by Iamblichos** [comment]
This can be fixed easy in an update to database given the second function.

**Comment by LoneGazebo** [comment]
I'll add the noimprovement for ice.
