### ISSUE TITLE
Problems with Pacifism and One World, One Religion reformations in Renaissance Era

### ISSUE THREAD

**Issue by reffmcd** [LoneGazebo/Community-Patch-DLL#2405]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8-18

1. Mod List (if using standard CPP set, leave blank):
Vox Populi w/EUI 8/18
FlagPromotions v.7
InfoAddict v.22
Quick turns v.10

2. Type of error (i.e. crash, interface bug, AI quirk): 
Having Pacifism and One World, One Religion added in Religion reformations and enchanters, when I enter into the Renaissance Era the cost of missionaries and inquisitors raises up to 700 of faith (the turn before was 470) and when I spread Religion in others cities doesn't seem to erode the others religions (One World, One Religion gives this ability).

I don't know if this is a bug, but it seems that both reformations were disabled when entering the renaissance era.

3. Steps to reproduce:
As above.

4. Additional information:
The gamesafe added is situated on the last turn of medieval era in order to see the change.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

[(Bug) William_0564 AD-1320.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/429860/Bug.William_0564.AD-1320.zip)

**Comment by reffmcd** [comment]
Edit: missionaries erode religion, I was wrong, but it's very strange the faith cost raising.. so the problem seems to be in Pacifism enhancer

**Comment by LoneGazebo** [comment]
Faith costs increase per Era, that's a vanilla element.
