### ISSUE TITLE
Citizens not being assigned to buildings

### ISSUE THREAD

**Issue by Guynemer** [LoneGazebo/Community-Patch-DLL#2408]
Bug Report Template

Mod Version (i.e Date - (4/23b)):  August 18th

1. Mod List (if using standard CPP set, leave blank):  InfoAddict, Quick Turns

2. Type of error (i.e. crash, interface bug, AI quirk): In some, but not all, cities, some citizens are not being assigned to empty specialist slots, and are left as laborers.  See the city Lampang in the attached save file.

[GuynemerIndia.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/431540/GuynemerIndia.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Laborers do not cause unhappiness. That's why.

**Comment by Guynemer** [comment]
Unfortunately I don't have a save from ~20 turns earlier, but the same thing was happening then, with a net happiness of roughly +25.
