### ISSUE TITLE
"You promised not to buy land near them for 'x' more turns" preventing border growth

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#2409]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

1. Mod List (if using standard CPP set, leave blank):
VP+EUI+Community Events

2. Type of error (i.e. crash, interface bug, AI quirk): 
Mechanic bug

3. Steps to reproduce:
Made a promise to stop buying land near a civ and the borders of my city adjacent to their empire stopped expanding naturally. Upon conquering their city, borders began expanding again.

4. Additional information:
8-18 version but in modpack form so assuming files would not be helpful. Sorry for this, figured sharing the observation is better than nothing.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Odd. It shouldn't affect that at all.
