### ISSUE TITLE
Disembarked onto a city units retain the movement points of the embarked state

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#241]
My rocket artillery has 2 movement points on land and 5 - on water. After disembarking onto a city it get 4 movement points for one turn, provided it started the turn next to a city tile.

**Comment by LoneGazebo** [comment]
This is normal – at that point in the game, disembarking through a city gives your unit movement as if it is on a railroad, to make moving from water to land a bit easier.
