### ISSUE TITLE
Issue with events

### ISSUE THREAD

**Issue by theblindcritic** [LoneGazebo/Community-Patch-DLL#2410]
Mod Version (i.e Date - (4/23b)): 8-18

1. Mod List (if using standard CPP set, leave blank):
Vox Populi (with EUI), Communitas Map, Infoaddict, Sukritact's Events and Decisions.

2. Type of error (i.e. crash, interface bug, AI quirk):  Interface bug

3. Steps to reproduce: Whenever I get a CP city event event (which, unlike the normal events from the Events and Decisions Mod, have a golden prompt at the bottom and don't just pop up at the start of a turn), clicking the prompt to 'Make Event Decision' doesn't do anything and I'm stuck and can't move to the next turn.

4. Additional information: For the log files, I simply reloaded my game from the turn where I'm stuck.
[Events problem.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/431731/Events.problem.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by theblindcritic** [comment]
I've also identified that the problem is specific to the 8-18 version as I reverted back to the 8-12 version and it works without any problems.

**Comment by Edaka** [comment]
Could you try to reproduce with the 8-18 version of just Vox Populi please? There's a high probability it's a mod conflict, especially since you are also using Sukritact's E&D at the same time.

**Comment by theblindcritic** [comment]
I've already done that. I initially posted this thread with all the other mods active, then disabled them all except Vox Populi with EUI and E&D (because I was assuming that the events wouldn't show up if E&D was disabled) and the problem still persisted. I did not, however, update the logs. Do you need logs without the mods?

**Comment by LoneGazebo** [comment]
I need the lua.log. If you don't have logging on, enable it, replicate event, then post.
