### ISSUE TITLE
savegame crashing on load (although correct version)

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2411]
so i'm still trying to figure out this problem, finally noticed a very large gamecore.log (more than one million lines of this):

[326061.968] LOAD ERROR: Type not found for hash: 553677178
[326061.968] LOAD ERROR: Type not found for hash: 3260807890
[326061.968] LOAD ERROR: Type not found for hash: 734838665
[326061.968] LOAD ERROR: Type not found for hash: 1429122
[326061.968] LOAD ERROR: Type not found for hash: 3380820421
[326061.968] LOAD ERROR: Type not found for hash: 246472850
[326061.968] LOAD ERROR: Type not found for hash: 2970316073
[326061.968] LOAD ERROR: Type not found for hash: 3272937764
[326061.968] LOAD ERROR: Type not found for hash: 423323860
[326061.968] LOAD ERROR: Type not found for hash: 2901569980
[326061.968] LOAD ERROR: Type not found for hash: 2939665663
[326061.968] LOAD ERROR: Type not found for hash: 1593125469
[326061.968] LOAD ERROR: Type not found for hash: 1967411845
[326061.968] LOAD ERROR: Type not found for hash: 540459398
[326061.968] LOAD ERROR: Type not found for hash: 3693135069
[326061.968] LOAD ERROR: Unit Class Type not found
[326061.968] LOAD ERROR: Type not found for hash: 4155694158
[326061.968] LOAD ERROR: Unit Class Type not found
[326061.968] LOAD ERROR: Type not found for hash: 1389216914
[326061.968] LOAD ERROR: Unit Class Type not found
[326061.968] LOAD ERROR: Type not found for hash: 912843287

the first error occurs when loading the number of units per class ever created.

	UnitArrayHelpers::Read(kStream, m_paiUnitCreatedCount);

we expect 160 classes and the savefile claims to contain 160 classes, but the 146th entry cannot be resolved. the appropriate hash is not found in the database.

		int iType = GC.getInfoTypeForHash(uiHash);

the call above fails. what to do?

**Comment by Iamblichos** [comment]
I wonder if the 146th starts where new units that have been introduced into the mod that weren't in vanilla.

**Comment by Iamblichos** [comment]
I also wonder if this could be caused by gaps in ID's in the database.

**Comment by ilteroi** [comment]
now here it gets interesting. in my Civ5CoreDatabase there are 90 units, while in my Civ5DebugDatabase there are exactly 146 units (checking with SQLiteStudio)

but then when i start the game and trace the database contents i get this (IDs are offset by one):

```
id 146 val "UNIT_BARBARIAN_AXMAN" hash 1580148684
id 147 val "UNIT_XCOM_SQUAD" hash 1794153196
id 148 val "UNIT_CRUISER" hash 553677178
id 149 val "UNIT_MOUNTED_BOWMAN" hash 3260807890
id 150 val "UNIT_CUIRASSIER" hash 734838665
id 151 val "UNIT_GUERILLA" hash 1429122
id 152 val "UNIT_EXPLORER" hash 3380820421
id 153 val "UNIT_ZEPPELIN" hash 246472850
id 154 val "UNIT_PIONEER" hash 2970316073
id 155 val "UNIT_COLONIST" hash 3272937764
id 156 val "UNIT_BANDEIRANTES" hash 423323860
id 157 val "UNIT_EMISSARY" hash 2901569980
id 158 val "UNIT_ENVOY" hash 2939665663
id 159 val "UNIT_DIPLOMAT" hash 1593125469
id 160 val "UNIT_AMBASSADOR" hash 1967411845
id 161 val "UNIT_GREAT_DIPLOMAT" hash 540459398
```

so indeed it's the "new" units which seem to cause the problem. but where do they come from if they aren't in the sqlite?

also, tracing the load process points to a major mismatch between my DB and the DB from which the savegame was generated:

[crash-on-load.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/435641/crash-on-load.zip)

some of the hashes point to different IDs (suggesting a different ordering) and some don't occur at all.

**Comment by ilteroi** [comment]
does anyone know how this unit table is generated and how the order is determined?

**Comment by Iamblichos** [comment]
There are "skips" in ID's in the original. And apparently, as far as I know, the ID's for GWAM's need to stay the same. I'm not sure if Gazebo has done some reordering to this or not using the remapper.

**Comment by LoneGazebo** [comment]
Okay, so let's recap. There are holes in the unit mapper? There shouldn't be, as there are no longer any DELETE SQL calls for unit IDs.

**Comment by ilteroi** [comment]
what is the unit mapper? anyway, the order of units in the database seems to be different between my setup and the one used to create the savegame. there also seem to be additional unit types (whose hash doesn't even exist in my DB) and possibly missing ones (hard to tell because we lose sync after hitting the first unknown entry).

anyway, can you load the saves from the issues linked above?

**Comment by LoneGazebo** [comment]
It is odd that your database is different. Any chance that you're not loading CSD etc?

**Comment by ilteroi** [comment]
well, you can't load it either - so i guess we should check whether our databases at least are identical. anyway, check the excel sheet linked above, i think i have everything there.

**Comment by LoneGazebo** [comment]
I'll give er a look.
