### ISSUE TITLE
Some events weirdness(updated issue eror log)

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2412]
[logs+save.zip.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/434641/logs.save.zip.txt)
![event culture](https://cloud.githubusercontent.com/assets/21192402/17887791/59c49992-6928-11e6-9b62-a22cb1545ecd.png)
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/18( including last hotfix)

1. Mod List (if using standard CPP set, leave blank):
Im using whole modpack without EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 
from +2 culture PT from marble(temporal) i have now -2 permanently(and bad culture output count  in city at all), so nearest is interface.

also another event which after i chose gave me +200 points to GW, but surplus of points was lost after born,why?

3. Steps to reproduce:
have no idea what i should imagine under this

4. Additional information:

i cant find Minidump file anywhere in Civ5 in steam folder.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Edaka** [comment]
Could you elaborate on the GW part? If I understand you correctly, the issue is that due to events you can accumulate an amount of GW points that's way over the spawning treshold, like 400 out of 200, and when said GW is born, the points reset to 0 instead subtracting the treshold out of the accumulated points (400-200=200). Is that so?

**Comment by matlajs** [comment]
i know its normal lose it but  would be nice keep it. thats more suggestion than issue report, but im bad in english co it might sounds weird.
