### ISSUE TITLE
Suggestion : Allow to disable peace brokering

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#2413]
The peace brokering "feature" (I know it is not really a feature, but peoples see it as one) is one of the most "hated" feature of the current community patch.
Adding a option, either in CommunityOption.sql, either in the advanced settup, to disable it would be a good idea.

By disabling it, I mean that you would no longer be able to buy peace between major civilisations (peace with minor are ok).

It is probably not a higth priority problem, but a lot of people seems to have problems with the current state of the peace brokering.

Thank you.

**Comment by ilteroi** [comment]
alternatives in order to alleviate some complaints (Alice is at war with Bob, Eve is the mediator talking to Alice)

- improve warscore algorithm to make sure Bob actually wants to make peace
- do not make peace immediately but only force Alice to accept a future peace offer from Bob 
- set the peace duration for the Bob to zero so he can re-declare war immediately if desired

**Comment by Radost** [comment]
It's not "one of the hated", since it existed in vanilla and everyone abused it. Just needs a refinement so it would feel less gamey.

**Comment by supermerill** [comment]
And the rewards shouldn't be only a function of warscore but also of the current value of the loosing empire. Don't need to spend 100+ gpt to save a single 1pop ice city.

What are the name of the functions use by peace brokering? DoPeaceOffer?

**Comment by ilteroi** [comment]
i guess GetThirdPartyPeaceValue() is the place to look

**Comment by Vyyt02** [comment]
If it is not too difficult to code (I suppose it is not), why not have the option to turn the peace brokering off in the options file?

I personally do not care about this feature much, but it seems many people do, so why not make them happy? If I understand correctly, it is impossible to code that consent of both warring parties would be needed to broker peace.

What I think would make more sense than forcing peace on someone would be an option to pay a civ to improve their attitude towards someone else or reset the values needed for signing peace. But this would be a new feature.

**Comment by LoneGazebo** [comment]
I'm not disabling the function, but I will adjust the parameters somewhat.
