### ISSUE TITLE
Game.GetMinimumVassalTurns() and Game.GetMinimumVoluntaryVassalTurns() returns 0

### ISSUE THREAD

**Issue by Lillebo** [LoneGazebo/Community-Patch-DLL#2414]
1. Mod List (if using standard CPP set, leave blank):
Community Patch (v. 72)
Community Balance Patch (v. 13)
City-State Diplomacy Mod for CBP (v. 27)
Civ IV Diplomatic Features - CBP Edition
More Luxuries - CBP Edition (v. 155)
Community Balance Patch - Compatibility Files
Helicopters Can Fly Over Water (v. 3)
Improved Air Recon (v. 1)
InfoAddict (v. 22)
Longer Eras - Historic (v. 8)
Submarines Ignore Borders (v. 3)
Really Advanced Setup (v. 15)

2. Type of error (i.e. crash, interface bug, AI quirk): 
AI quirk

3. Steps to reproduce:
Mostly a problem when forcing an enemy to capitulate, but also an issue with voluntary vassalage. To reproduce, get a vassal with each method (capitulation and voluntary) and observe as the AI request an end to the master/vassal relationship the very next turn.

4. Additional information:
I believe this is due to the functions Game.GetMinimumVassalTurns() and Game.GetMinimumVoluntaryVassalTurns() returns zero (0). I believe this because the tooltip for the voluntary vassalage option on the trade screen says that voluntary vassalage may be ended after a minimum of 0 turns. While checking the source for those values I came across MODS\(4) Civ IV Diplomatic Features\SQL\NewColumns.sql (line 20-43) where the minimum turn values are set per game speed:

```
-- GameSpeedsInfos
UPDATE	GameSpeeds	SET	'ShareOpinionDuration' = 10			WHERE	Type = 'GAMESPEED_QUICK';
UPDATE	GameSpeeds	SET	'TechCostPerTurnMultiplier' = 20	WHERE	Type = 'GAMESPEED_QUICK';
UPDATE	GameSpeeds	SET	'MinimumVoluntaryVassalTurns' = 10	WHERE	Type = 'GAMESPEED_QUICK';
UPDATE	GameSpeeds	SET	'MinimumVassalTurns' = 33			WHERE	Type = 'GAMESPEED_QUICK';
UPDATE	GameSpeeds	SET	'NumTurnsBetweenVassals' = 67		WHERE	Type = 'GAMESPEED_QUICK';

UPDATE	GameSpeeds	SET	'ShareOpinionDuration' = 10			WHERE	Type = 'GAMESPEED_STANDARD';
UPDATE	GameSpeeds	SET	'TechCostPerTurnMultiplier' = 30	WHERE	Type = 'GAMESPEED_STANDARD';
UPDATE	GameSpeeds	SET	'MinimumVoluntaryVassalTurns' = 10	WHERE	Type = 'GAMESPEED_STANDARD';
UPDATE	GameSpeeds	SET	'MinimumVassalTurns' = 50			WHERE	Type = 'GAMESPEED_STANDARD';
UPDATE	GameSpeeds	SET	'NumTurnsBetweenVassals' = 100		WHERE	Type = 'GAMESPEED_STANDARD';

UPDATE	GameSpeeds	SET	'ShareOpinionDuration' = 15			WHERE	Type = 'GAMESPEED_EPIC';
UPDATE	GameSpeeds	SET	'TechCostPerTurnMultiplier' = 45	WHERE	Type = 'GAMESPEED_EPIC';
UPDATE	GameSpeeds	SET	'MinimumVoluntaryVassalTurns' = 15	WHERE	Type = 'GAMESPEED_EPIC';
UPDATE	GameSpeeds	SET	'MinimumVassalTurns' = 75			WHERE	Type = 'GAMESPEED_EPIC';
UPDATE	GameSpeeds	SET	'NumTurnsBetweenVassals' = 150		WHERE	Type = 'GAMESPEED_EPIC';

UPDATE	GameSpeeds	SET	'ShareOpinionDuration' = 30			WHERE	Type = 'GAMESPEED_MARATHON';
UPDATE	GameSpeeds	SET	'TechCostPerTurnMultiplier' = 90	WHERE	Type = 'GAMESPEED_MARATHON';
UPDATE	GameSpeeds	SET	'MinimumVoluntaryVassalTurns' = 30	WHERE	Type = 'GAMESPEED_MARATHON';
UPDATE	GameSpeeds	SET	'MinimumVassalTurns' = 150			WHERE	Type = 'GAMESPEED_MARATHON';
UPDATE	GameSpeeds	SET	'NumTurnsBetweenVassals' = 300		WHERE	Type = 'GAMESPEED_MARATHON';
```

The issue might be linked with the mod "Longer Eras - Historic", because there aren't values inserted for that gamespeed.

**Comment by LoneGazebo** [comment]
If you are running the game on historic, that's definitely the issue. I'll see about fixing that on the DLL side via a default value.
