### ISSUE TITLE
Mercenaries Issues (and a Request)

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2415]
Encountered some problems with Mercenaries and thought it best to open a new issue instead of reusing the old one.

**ContractStarted(PlayerTypes ePlayer, ContractTypes eContract, int iTurns, int iMaintenance)** doesn't return the parameters as reported. Where it says iTurns, it actually returns iMaintenance, and iMaintenance is null. Not a major issue, but would be nice to have fixed.

**Player:EndContract** doesn't seem to work at all. At least, Player:PlayerHasContract will still return true even after EndContract has been invoked.

**Contract turns** don't persist upon load. Re-loading the game and all Contract turns are reset to -1. However, PlayerHasContract still registered as true

Would it be possible to do a **Player:ChangeContractTurns(contractID, value)** function? So that I could extend the length of a contract whilst its still active? Not imperative, but players in the default Mercenaries are able to extend contracts for a small fee before they expire, and it would be nice to retain this.

Everything else is working beautifully though.

**Comment by LoneGazebo** [comment]
I'm on it.

**Comment by JFDaly** [comment]
Did you change anything viz. the GetContractUnit() function in the latest test build? Contracts don't seem to be populating as consistently as I recall. For instance, I have three contracts currently added, but sometimes only 1 will show with a unit, sometimes none.

**Comment by LoneGazebo** [comment]
I haven't touched that function, no.

**Comment by JFDaly** [comment]
Okay, so the issue I think is that I'm still confused about how the system works viz. what units are attached to the Contract.

This is how I understand it: GameEvents.GetNumContractUnit() is called every era. This iterates through all units with the intention that units that should go with the contract should return a value greater than 0 - this corresponds to how many of that unit the contract gives. 

For reference, this is my function:

function JFD_RTP_Mercenaries_GetNumContractUnit(contractID, unitID)
	local contract = GameInfo.Contracts[contractID]
	if (not contract) then return end
	if unitID == JFD_RTP_Mercenaries_GetContractUnit(contractID) then
		return contract.UnitCount
	end
end
if userSettingMercenariesCore then
	GameEvents.GetNumContractUnit.Add(JFD_RTP_Mercenaries_GetNumContractUnit)
end

So, JFD_RTP_Mercenaries_GetContractUnit(contractID) randomly chooses a unit that is valid for the contract and matches it to the iterated unitID. But then I'm not sure how to stop the iteration after this, so it continues to match up the randomize function with the unitID until GetNumContractUnit is finished iterating through the units table.

I think my best bet is to manually set it all using SetContractUnits(), whenever the contracts are freshed, but I'm assuming that I'm failing to understand something somewhere.

**Comment by LoneGazebo** [comment]
SetContractUnits is fine, however if I need to reorder the functions in the GetContractUnits() I can. Here's the function.

```
void CvGameContracts::DoUpdateContracts()
{
	GAMEEVENTINVOKE_HOOK(GAMEEVENT_ContractsRefreshed);

	//This is expensive, so do it sparingly!
	ContractList::iterator it;
	for(it = m_InactiveContracts.begin(); it != m_InactiveContracts.end(); it++)
	{
		CvContract kContract = (*it);
		for(int iI = 0; iI < GC.getNumUnitInfos(); iI++)
		{
			UnitTypes eUnit = (UnitTypes)iI;
				
			if(eUnit == NO_UNIT)
				continue;

			CvUnitEntry* pkUnitEntry = GC.getUnitInfo(eUnit);
			if(pkUnitEntry)
			{
				bool bIn = false;
				int iValue = 0;
				if (GAMEEVENTINVOKE_VALUE(iValue, GAMEEVENT_GetNumContractUnit, it->m_eContract, eUnit) == GAMEEVENTRETURN_VALUE) 
				{		
					if(iValue > 0)
					{
						GC.getGame().SetContractUnits(it->m_eContract, eUnit, iValue);
						bIn = true;
					}
				}
				if(!bIn)
				{
					//Zero out so we don't waste memory.
					GC.getGame().SetContractUnits(it->m_eContract, eUnit, 0);
				}
			}
		}
	}
}
```

So you can see how it works - this function is called when the human player enters a new era.

**Comment by JFDaly** [comment]
Yea, that'd be great if you switch it around, thanks.

**Comment by LoneGazebo** [comment]
If I move the Lua hook that should fix it.

**Comment by LoneGazebo** [comment]
Try this: https://mega.nz/#!vBtEGJoC!2xykAPvKDuvBYaLLqq-12EsyvByl-PDvdBS60hQIvic

**Comment by JFDaly** [comment]
That does it. Thanks for the quick turnaround!

**Comment by LoneGazebo** [comment]
Awesome! Yep!

**Comment by JFDaly** [comment]
Is there anyway to get the unit tied to a Contract directly? Iterating through all Contracts iterating through all units to check Game.GetContractUnits() > 0 is noticeably affecting performance when navigating my UI. Contracts definitely don't need more than one unit ID tied to them, so is there anyway to rework the system so that GetContractUnits() returns both the unitID and the unitCount set in SetContractUnits() ?

**Comment by LoneGazebo** [comment]
Yes, but it requires the use of a lua table because of how the data is stored. I've got that done now, however. There will be two functions:

GetInactiveContractUnitList()
and
GetActiveContractUnitList()

These tables do all of the contract/unit iteration and filtering for you, you just need to grab the following three fields from the lua table:
Contract
Unit
NumUnits

Uses the same lua table functionality as the replayviewer, for example.

**Comment by LoneGazebo** [comment]
Link for testing: https://mega.nz/#!PJFCURpR!PZBSC_jI5QkDXRpoeAU6F7SQB-Ym37MhKoFArWjlXlM

**Comment by LoneGazebo** [comment]
Hope this does what you wanted!

**Comment by JFDaly** [comment]
Link doesn't appear to be working. Not sure I quite understand how to implement, but I'll give it a shot.

**Comment by LoneGazebo** [comment]
Try this: https://mega.nz/#!PJFCURpR!PZBSC_jI5QkDXRpoeAU6F7SQB-Ym37MhKoFArWjlXlM

**Comment by JFDaly** [comment]
Nope, it just gets stuck on the M symbol and doesn't progress to a download. Same thing in a different browser.

**Comment by LoneGazebo** [comment]
Weird. Okay one more check:
[(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/457799/1.Community.Patch.zip)

**Comment by LoneGazebo** [comment]
Try that.

Lua table = the same table system that the chooseinternationaltradepopup lua and replayviewer lua use.

**Comment by JFDaly** [comment]
Ah might be the whole site (or something about my connection), as the VP from September link is also down. But the zip works, thanks!

**Comment by LoneGazebo** [comment]
Great! Let me know if you have questions.

**Comment by JFDaly** [comment]
Oh, you mean Game.GetActiveContractUnitList() works like player:GetTradeRoutes()? So it would work something like this:

for i,v in ipairs(Game.GetActiveContractUnitList()) do
	local contract = {
		ContractID = contract.Contract,
		ContractUnitID = v.Unit,
		ContractUnitCount = v.NumUnits,};

print(contractID, contractUnitID, contractUnitCount)
end

**Comment by LoneGazebo** [comment]
Yep! Should.

**Comment by LoneGazebo** [comment]
if it does not let me know and i'll debug.

**Comment by JFDaly** [comment]
Does Game.GetContractUnits(contractID, unitID) no longer work? I wanted to use it to test whether or not I did something wrong with the assigning of units function or Game.GetActiveContractUnitList() simply isn't working.

**Comment by LoneGazebo** [comment]
Try this: 
[(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/457905/1.Community.Patch.zip)

**Comment by JFDaly** [comment]
Hm, nope, same issues.

**Comment by LoneGazebo** [comment]
Okay, lemme do some work on it.

**Comment by JFDaly** [comment]
Thanks

**Comment by LoneGazebo** [comment]
[(1) Community Patch (v 88).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/457937/1.Community.Patch.v.88.zip)

Okay I've tested this one and I'm not seeing a nil value. Which part is returning the nil value?

**Comment by JFDaly** [comment]
Maybe I'm using it wrong then. 

When I use:

for _, contract in ipairs(Game.GetInactiveContractUnitList()) do print(contract) end

in FireTuner, it simply returns nothing.

**Comment by JFDaly** [comment]
Any thoughts? Don't mean to be impatient, but today is my last day for focusing on modding before I have essays to do. Perhaps the wrong version was linked, if it's all working for you?

**Comment by LoneGazebo** [comment]
Sorry, baby had a fussy night and I got swamped with work. I do think I have it fixed, though. Here's a tester:

[(1) Community Patch (v 88).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/460695/1.Community.Patch.v.88.zip)

I'm using the same method for the new event overview UI and it works perfectly there. Try it and, if it fails, I've got one more idea.

**Comment by JFDaly** [comment]
Yea, I've set up a test function in lua that copies how you've set up the events equivalent, but there's just nothing. At least Game.GetInactiveContractUnitList() isn't returning any errors now - though like ActiveUnit it simply returns nothing.

**Comment by LoneGazebo** [comment]
Okay, here's my next trick:

[(1) Community Patch (v 88).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/460809/1.Community.Patch.v.88.zip)

**Comment by JFDaly** [comment]
Partial success! Game.GetActiveContractUnitList still doesn't return anything, but Game.GetInactiveContractUnitList() is returning the list of units that belong to a contract.

**Comment by LoneGazebo** [comment]
Well active only works for active ones, so did you activate a contract?

**Comment by JFDaly** [comment]
Oh, my bad. I thought active was the difference between units tied to contracts and units not, but thinking about it, that doesn't make sense given the existing distinction between active and inactive contracts. In which case it all works now. Really, thank you for working through this!

**Comment by LoneGazebo** [comment]
Hooray! Crack open a beer for me.

**Comment by LoneGazebo** [comment]
I hope that it is more efficient in your user interface.

**Comment by JFDaly** [comment]
I expect so. I'll incorporate it in and post about how it goes.

**Comment by LoneGazebo** [comment]
sounds good

**Comment by JFDaly** [comment]
Okay, next issue is that these new lists don't preserve on re-load. However, it definitely performs much better.

**Comment by JFDaly** [comment]
Okay, next issue is that these new lists don't preserve on re-load (well SetContractUnits at least). However, it definitely performs much better.

**Comment by LoneGazebo** [comment]
They don't preserve? Weird!

**Comment by LoneGazebo** [comment]
Does the data behind it persist?

**Comment by JFDaly** [comment]
Contracts that have been taken out persist (so active contracts, incl. assigned unit, player, turns, mainteannce etc.), but upon re-reloading, no inactive contract has a unit assigned to it.

**Comment by JFDaly** [comment]
Before reload:
![before](http://i.imgur.com/DzndaiS.jpg)

After:
![after](http://i.imgur.com/7tP5CCE.jpg)

And if I manually check GetContractUnits() it indeed returns 0 as if the unit was cleared upon reload.

**Comment by LoneGazebo** [comment]
Let me know if it is rogue, otherwise there's a memory error I need to fix!

**Comment by JFDaly** [comment]
Nope, yea, that was the issue. I have Game.DoUpdateContracts() invoked when the load screen closes, in the event that the player starts a late game with Mercenaries already researched. But this was clearing all the contracts. I'll have to think about a way around this - probably get that Game.GetInactiveContractUnitList() is empty first. Sorry for the false alarm.

**Comment by LoneGazebo** [comment]
No worries!
