### ISSUE TITLE
Can pick Flak Targetting II Promotion

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#2416]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

8/18

1. Mod List (if using standard CPP set, leave blank):

FlagPromotions (v7)
Historical Religion Edit (v45)
JFD's Cultural Diversity (v9) & soundtrack (v1)
UnitPath Viewer
UI - Promotion Tree
Unique Cultural Influence

2. Type of error (i.e. crash, interface bug, AI quirk): 

Units can pick Flak Targetting II Promotion

3. Steps to reproduce:

4. Additional information:

I suspect these are the causes:
1. Researched Industrialization
2. Unit is gunpowder unit
3. Unit is Mehal Sefari

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
http://images.akamai.steamusercontent.com/ugc/268349544289481222/2042D572FEBF31536BFCDAEB7F0B1F957F13C18D/

**Comment by Freaky-Freddy** [comment]
I also had this bug in my 8/12 game.

**Comment by Iamblichos** [comment]
Can't reproduce this. You might have a mod conflict. I would try getting rid of a few of the mods there like UI promotion tree.
