### ISSUE TITLE
Gandhi's Technology have 0 value for trading

### ISSUE THREAD

**Issue by andrewl020** [LoneGazebo/Community-Patch-DLL#2418]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
1.8.18

1. Mod List (if using standard CPP set, leave blank):
Standard CPP set 
Leugi's Barbarian Inmersion Enhancements
Civ Names by Policies
InfoAddict
Longer Eras - Historic
More Great Works
R.E.D 
Yet (not) Another Earth Maps Pack

2. Type of error (i.e. crash, interface bug, AI quirk): 
Technology have 0 value for trading
![screenshot 6](https://cloud.githubusercontent.com/assets/13599632/17962402/3b49293a-6ae3-11e6-876f-0ead5132844b.png)
![screenshot 7](https://cloud.githubusercontent.com/assets/13599632/17962403/3b4c5dd0-6ae3-11e6-920b-c5a0db53a13e.png)

3. Steps to reproduce:
At the trading screen with other civ

4. Additional information:
I turned off Time, Science, Diplomatic victory types

edit: Gandhi's tech only
---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by TechpriestEnginseer** [comment]
Maybe Gandhi is too nice in handing over his technologies? Have you tried it with your worst enemy?

**Comment by andrewl020** [comment]
lol. Its only happen with Gandhi, but he is willing to give every tech lead he had to me which is 8 tech or so. He is leading in tech.
