### ISSUE TITLE
game randomly closes everytime turn 44 comes around

### ISSUE THREAD

**Issue by kuninator** [LoneGazebo/Community-Patch-DLL#2419]
Mod Version August 18th (1.8.18)

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
game shuts down to desktop

3. Steps to reproduce:
play game untill turn 44

4. Additional information:
off-topic question: it seems that all the ai's start off with a full social policies tree? is that supposed to be that way? because to me that doesn't make any sense.

[AutoSave_0040 BC-2400.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/437915/AutoSave_0040.BC-2400.zip)

**Comment by Vyyt02** [comment]
Looks like a bad install to me, the AIs should not be getting the free tree. What difficulty are you playing at?

I'd remove all the mods (even the inactive ones) from the MODs folder, clear cache and ModUserData, check if you are not subscribed to More Luxuries and Civ4Diplo on Steam (if you are, unsubscribe) and reinstall Vox Populi.

**Comment by kuninator** [comment]
Thanks for the quick reply!
I am playing on emperor. I will try this and see if that resolves it. Btw I
am using a custom scenario/map i made, maybe that has something to do with
it?

Op 25 aug. 2016 10:09 p.m. schreef "Vyyt" <notifications@github.com>:
>
> Looks like a bad install to me, the AIs should not be getting the free
tree. What difficulty are you playing at?
>
> I'd remove all the mods (even the inactive ones) from the MODs folder,
clear cache and ModUserData, check if you are not subscribed to More
Luxuries and Civ4Diplo on Steam (if you are, unsubscribe) and reinstall Vox
Populi.

**Comment by kuninator** [comment]
The issue is resolved it seems, thanks for your time

Op 26 aug. 2016 12:31 a.m. schreef "Koen Willemen" <kwillemen@gmail.com>:
