### ISSUE TITLE
War elephant requirement

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#242]
To train WE a city must have stables so besides ivory WE requires horse or sheep or cow which does not make sense. Why not change requirement from stables to barracks?

**Comment by LoneGazebo** [comment]
Stables do not require horses/sheep/cows to be built, but they benefit from it.

**Comment by qqqbbb** [comment]
Stable can be built only if one of city plots has pasture with horses, sheep or cows.

**Comment by LoneGazebo** [comment]
Fixed.
