### ISSUE TITLE
[AI] Not enough wars

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#2421]
Bug Report Template

Mod Version (i.e Date - (8/18)):

1. Mod List (if using standard CPP set, leave blank):
2. Type of error (i.e. crash, interface bug, AI quirk): 
AI behavior.

3. Steps to reproduce:
4. Additional information:

Many many users report games that are without any wars (even with shaka), love fest and no retaliation for the human player who warmonger. I didn't see it myself in the only game i played (i had some AI wars and an ai declare war on me to stop my diplo victory). But maybe the recent change in diplo ai made them not enough angry?

Funak think it's because sometimes (big maps) there are enough land for everyone. So no war.

I'm reporting this here to lot loosing track on this
---------------------------
http://forums.civfanatics.com/showpost.php?p=14414640&postcount=167
http://forums.civfanatics.com/showpost.php?p=14414441&postcount=163
http://forums.civfanatics.com/showpost.php?p=14409488&postcount=106
http://forums.civfanatics.com/showpost.php?p=14412997&postcount=145

**Comment by TechpriestEnginseer** [comment]
Can confirm. To test this, I've introduced myself the ultimate civilization who becomes the ultimate warmonger. With diplo penalties as high as -200, many AIs will fear that I will become the cause of the dark age. Yet, I haven't seen a single war declaration despite reducing my military strength significantly below the average.

**Comment by oedali** [comment]
I concur. This is very pronounced in every single game I have played with 8/18 version. I have observed the following:

- Virtually no wars until ~turn 300 when ideologies kick in. (Very few exceptions e.g. Shaka)
- Virtually ALL AIs friendly and DOW with each other. (Very few exceptions e.g. Elizabeth)
- AIs do not seem to give negative diplo penalty for close borders. They tolerate almost everything.  
- AIs do not attack even if you are extremely weak compared to them (<1/10 of their strength)
- AIs give you free gifts very often, even when you are ahead of them in score!

**Comment by matlajs** [comment]
about that last point it isnt problem for me. problem is, they dont do that bcoz  they want u help more.  they do so bcoz they are stucked same way like they are with normal trading( non ending trade offers and non ending refuse every turn).  in adition, they support you with cash/luxes even when actually you are in negative shape with them. and yep, im also for reduce that ridiculous expansion as i suggested in civfanatic make settlers production dependant on national population same as national wonders(not same stacking obviously). make it optional would be at least nice.

**Comment by steemroller** [comment]
I concur with most of oedali's points and would add that things that should be greater early game "friction" between civilizations, especially on Immortal or Diety, are not leading to early wars:

- differing beliefs
- coveted lands
- coveted resources

**Comment by TechpriestEnginseer** [comment]
I think we should have a vote whether we want heavily aggressive AI or passive AI since the community...

**Comment by oedali** [comment]
Does it have to be one vs the other? Both are extremes. This is not a new ask - there used to be a version while the AI behaved more "normal". At the least there should be variance instead of the love fest we are seeing right now

**Comment by Enrico-Swagolo** [comment]
I agree the AI is too non-aggressive which makes the game a bit easier. They do declare wars, but it's almost never. The Smurfy circle of friendship is back and stronger than ever - I mean I have killed Austria (friend of everyone), almost killed Pedro (friend of everyone), declared war on Polynesia, and I am still getting Friendship offers from their friends despite ignoring them and doing everything I can to aggravate them?

Back is also the problem of AI overexpanding. I constantly see Tradition AI build 8-10+ cities in/by Classical. What's the point? They have no infrastructure at all, they're just free gold and faith for my Hero Worship Denmark. I mean yeah, thanks for accelerating my economy Maria Theresa, but it's still a very bad idea to do what you're doing.

**Comment by LoneGazebo** [comment]
AI war proclivity hasn't been touched in some time.

@ilteroi, mind checking to see if AI sneak attack operations are successfully triggering as they move towards a target? I wonder if that's the issue (and not the diplo AI).

**Comment by ilteroi** [comment]
nah. they simply don't build armies.

![image](https://cloud.githubusercontent.com/assets/1358966/18078281/15a54618-6e8b-11e6-8350-3fdcd99dfdc7.png)

**Comment by oedali** [comment]
I think it's more than just armies & wars.. the AI diplomacy is over-tolerant, over-friendly, non-paranoid to the point of naive. See #2425 for example - they are not even threatened by nearby military.

**Comment by LoneGazebo** [comment]
Hmm. @oedali assumptions aren't useful without concrete data. Diplo logs are useful.

**Comment by LoneGazebo** [comment]
@ilteroi what's the production log looking like?

**Comment by oedali** [comment]
I can turn logging if it helps.. do I just do this in the config.ini file? LoggingEnabled = 1.

**Comment by LoneGazebo** [comment]
that and AI logging.
