### ISSUE TITLE
Attrition system bugs

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2423]
Somewhere along the line of CP updates, the Attrition system seems to have been broken. I've had a few reports about this, and have now tested this and do confirm. Basically, the **NegatesPromotion** tag in UnitPromotions appears to be broken - units with, for instance, immunity to Desert Attrition will still get promotion that handles Desert Attrition even though they shouldn't. ExCE hasn't been updated in a while (so it seems likely to be a CP issue) and this is on the 18-8 version of the CP, but possibly previous versions, too.

Thanks for looking into this issue, when you can!

**Comment by LoneGazebo** [comment]
Mm, I made some optimizations here but may have overdone it. Will check ASAP.
