### ISSUE TITLE
No land coveting + no military threat

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#2425]
Bug Report Template

Mod Version: 8-18

1. Mod List (if using standard CPP set, leave blank):
- a lot of mods, but none should be affecting AIs

2. Type of error (i.e. crash, interface bug, AI quirk): 
1) No civ is coveting my lands despite me forward-settling them and overall very close borders and quite a crowded continent
2) When my (small) army is passing right next to an AI border (for several turns), I do not get any negative diplo modifier - unlike before, when even a mere passing scout was considered a military threat

**Comment by Vyyt02** [comment]
Ok, sorry, looks like a glitch or the cache was not cleared correctly. I started a new game, passed by the Japanese territory with my warrior and they immediately saw it as a military threat.

**Comment by oedali** [comment]
I cleared my cache and reinstalled 8-18 but also seeing the same behavior. Even though my units are right at his capital doorsteps, no threat modifier. 

![20160830111405_1](https://cloud.githubusercontent.com/assets/20485377/18094907/2c3240ee-6ea3-11e6-8a1a-d32d3fd87cda.jpg)

**Comment by LoneGazebo** [comment]
The AI will only register a threat in certain circumstances. Should be WAD but i'll check.
