### ISSUE TITLE
buildings not sorted in order

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2427]
probably an EUI thing, but since there's talk of replacing it:

![image](https://cloud.githubusercontent.com/assets/1358966/18029533/ce44600c-6c9a-11e6-882c-4a41c4487eec.png)

these are only the specialist building, the "normal" ones seem to be in alphabetical order. makes it hard to find a particular building ...

**Comment by Edaka** [comment]
Seems that they are sorted by specialist type first, alphabet second.

**Comment by Iamblichos** [comment]
What's better organized by specialist or by building name?

**Comment by hugorune** [comment]
I really like the way it is now, organised by specialist (and alphabet after that). The order is still consistent, so it's just a matter of getting used to it.

**Comment by LoneGazebo** [comment]
@Iamblichos perhaps make a post on the thread. TBH I like the new cityview that maggi has made.

**Comment by Freaky-Freddy** [comment]
> perhaps make a post on the thread. TBH I like the new cityview that maggi has made.

Does it work well with VP and EUI? Is it Gazebo approved?

**Comment by Iamblichos** [comment]
I made a post about EUI in general in the forums, but not about this in particular. I will add this to that thread.
