### ISSUE TITLE
Persia offers peace but won't complete.  Also happiness balance issues late in game.

### ISSUE THREAD

**Issue by Glizinte** [LoneGazebo/Community-Patch-DLL#2428]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): AI offers peace but won't complete.  Late game with happiness balance issues.

3. Steps to reproduce:

4. Additional information:   Play as Morocco, Sandstorm, King.  Have won on this map and settings before, but with the last iteration have been stumped.

[xml-perf.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/440854/xml-perf.zip)
[Balance issues.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/440855/Balance.issues.zip)

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by ilteroi** [comment]
this is not a lot of information ... which version are you using? what are the balance issues?

**Comment by Iamblichos** [comment]
Well the Peace deal problem with a city state included is probably the issue, which we all know about now and is referenced in other Issues.

Other than that, we need to know what is wrong with the happiness.

**Comment by LoneGazebo** [comment]
Closing as we've got the 3rd party peace issue elsewhere, which is the problem.

**Comment by Glizinte** [comment]
Fine with me.  Sorry I didn't answer earlier  but I've been having
computer problems.

Richard Groll

On ‎8‎/‎30‎/‎2016 at 1:26 PM, "LoneGazebo"  wrote:

	Closing as we've got the 3rd party peace issue elsewhere, which is
the problem.
