### ISSUE TITLE
Great diplomat broke Austrian unique ability

### ISSUE THREAD

**Issue by avl8** [LoneGazebo/Community-Patch-DLL#2429]
Mod Version (i.e Date - (4/23b)): 8-18, latest patch atm

1. Mod List (if using standard CPP set, leave blank): none, only VP complete package, installed after I carefully deleted previous version.

2. Type of error (i.e. crash, interface bug, AI quirk): gameplay bug

3. Steps to reproduce:
3.1 Arrange a diplomatic marriage with a city-state.
3.2 Have enemy great diplomat hit a city state influence into negative values (-60 in my example)
3.3 "Enjoy" -60 influence for eternity without any recovery

4. Additional information:
In my recent Austria game (latest patch) Russian great diplomat reduced my influence in one of my married CS to 0. Then Assyrian great diplomat made it into -60 influence. Then influence with this CS had stalled for eternity at -60 without any recovery.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by TechpriestEnginseer** [comment]
So.. shouldn't you just get a diplomatic unit?

**Comment by avl8** [comment]
Usually when someone gets your influence to -60 you get it back by natural recovery. Its like +1 influence  per turn until you hit your influence cap (usually its 0, but can get higher by policies or religion).
In my situation theres no natural influence recovery.

Meanwhile Austrian UA looks like removing influence decay, not natural influence recovery :(

**Comment by Radost** [comment]
Yeah, Influence Decay ≠ Influence Recovery. UA only nullifies Influence Decay.

**Comment by TechpriestEnginseer** [comment]
Actually Influence Decay = Influence Recovery because it's the same mechanic just different integers. In code, if influence decay freezes, so does influence recovery as well. However, it is still a bug.
