### ISSUE TITLE
Desert Folklore for resource on Flood Plain || Forest has incorrect yield

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#243]
Desert Folklore doesn't give additional yield for resource on flood plain. For instance, when lncense on flood plain is improved, it should be 2Food,4Gold,1Faith as suggested by the pantheon (+1Faith,2Gold from desert tiles with improved resources) . Instead, it yields only 4Gold,1Faith as if it is desert tile, not flood plain.

Another problem is that Forest changes its yield during game. Like a forest in grassland would change its yield from 1Food,1Prod to 2Food. It is not tooltip error. The city earns exact yield from working it. Another example is that a Deer on tundra forest yields 2Food,1Prod initially. It changes to 2Food when I have settled a city 1~2 turns afterwards.

EDIT: I bought a tile with Deer on grassland forest. The yield changes from 2Food,1Prod to 3Food instantly.

EDIT2: The problem seems to apply on all tiles with resource with terrain feature. Irons on marsh yields 2Food,1Prod within city border.

**Comment by LoneGazebo** [comment]
I'll take a look - keep in mind that features replace the yields of a tile, so plains + forest does not get both yields, but rather just that of the forest.

**Comment by XplosiveLun** [comment]
Thanks.

**Comment by XplosiveLun** [comment]
I think the terrain feature glitch was caused by Cache. After I deleted the cache, the problem seems gone.
