### ISSUE TITLE
Puppet cities only go farming

### ISSUE THREAD

**Issue by BiteInTheMark** [LoneGazebo/Community-Patch-DLL#2430]
Bug Report Template

Mod Version (8/18):

1. Mod List : only CPP

2. Type of error: Puppet cities focus somewhat on food. Not even that, it only produces 3 buildings then go food production by farming (Its around 3 or exactly always 3 buildings). Even other buildigns would help in getting money or food.
Also "honor" from the authority tree doesnt trigger at puppet cities (no units spawn at 8 citizens).

3. Steps to reproduce: Start a game, conquer a city, puppet it and wait till you have build 3 buildings produced there.

**Comment by Enrico-Swagolo** [comment]
Same here! Puppets are absolutely worthless this version, occupation is a must.

**Comment by hugorune** [comment]
The tile selection is pretty horrific too. I've seen puppets work an empty grassland tile instead of an improved mine on a resource, when there is a high pop, big food surplus, and almost no production or gold.

**Comment by LoneGazebo** [comment]
I'll look. Puppets are supposed to be somewhat inefficient compared to real cities, however.

**Comment by Edaka** [comment]
I personally think they would inefficient enough with just the -25% city yield modifier and the inability to manage them, which is all already in place.

**Comment by BiteInTheMark** [comment]
Compare to "real" cities? I thought its a trade, no control over production and no purchase in puppets for the advancement of no unhappiness and no increase in culture cost....
Is there really a -25% in yields in puppets?
The normal AI is already not the best in city progress (no lighthouse even a lot of coast tiles etc.), and your talking about intentionally crippling puppets?

**Comment by matlajs** [comment]
they have -25% science and culture modifier +6% increase cost in techs and policies. this is pain in ass watching how AI managed citizens working all worthless tiles even it has nearby natural wonder with ton of cultur and faith.
