### ISSUE TITLE
EventBuildingClassGlobal

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2431]
Doesn't work. Pretty much that's it or doesn't work when I have only one city when I tested it.

**Comment by LoneGazebo** [comment]
What exactly is wrong?

**Comment by TechpriestEnginseer** [comment]
I'm unsure, but IGE can't seem to detect the event dummy buildings that EventBuildingClassGlobal is giving.

**Comment by LoneGazebo** [comment]
they aren't dummy (i.e. free) anymore- they're 'real' buildings.

**Comment by TechpriestEnginseer** [comment]
Yeah, that's the problem I'm having with.. but it could be that I'm setting the event cooldown off and on at an instant... 
````
function AddDummyBuildings(iPlayer, iChoice)
	local pPlayer = Players[iPlayer]
	if iChoice == GameInfoTypes.PLAYER_EVENT_DUMMY_CHOICE_4 then
		pPlayer:SetEventChoiceCooldown(GameInfoTypes.PLAYER_EVENT_DUMMY_CHOICE_1, 0)
		pPlayer:SetEventChoiceCooldown(GameInfoTypes.PLAYER_EVENT_DUMMY_CHOICE_2, 0)
		pPlayer:SetEventChoiceCooldown(GameInfoTypes.PLAYER_EVENT_DUMMY_CHOICE_3, 0)
		pPlayer:SetEventChoiceCooldown(GameInfoTypes.PLAYER_EVENT_DUMMY_CHOICE_4, 0)
		pPlayer:SetEventChoiceCooldown(GameInfoTypes.PLAYER_EVENT_DUMMY_CHOICE_4, 1500)
	end
end
GameEvents.EventChoiceActivated.Add(AddDummyBuildings)
````

**Comment by LoneGazebo** [comment]
Yeah, you need the cooldown if you are going to have them expire.

**Comment by TechpriestEnginseer** [comment]
SHOOT I realized the mistake I made was that a different event choice was giving the dummy building not the actual event choice intended.

**Comment by TechpriestEnginseer** [comment]
Actually it was because the buildingclass I had didn't have a default building.

**Comment by LoneGazebo** [comment]
Ah yeah, that's it.
