### ISSUE TITLE
Unhappiness doesn't show up anywhere (v-18)

### ISSUE THREAD

**Issue by TheHATEngineer** [LoneGazebo/Community-Patch-DLL#2432]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

8-18

1. Mod List (if using standard CPP set, leave blank):

Only extra civs + ethnic units and info addict

2. Type of error (i.e. crash, interface bug, AI quirk): 

The type of unhappiness doesn't show up anywhere

3. Steps to reproduce:

Just play the game untill unhapinessis produced

4. Additional information:

I really like the mod and I think its a giant upgrade to the game, but I can't fight unhappiness by just guessing

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by TheHATEngineer** [comment]
PS, it's a simmular issue as #718

**Comment by Iamblichos** [comment]
Got a save game point so I can take a look at this?

**Comment by TheHATEngineer** [comment]
Sorry I reinstalled the game (and deleted the saves cache moddata etc) and
now it does work

Op 30 aug. 2016 16:16 schreef "Iamblichos" <notifications@github.com>:

**Comment by TheHATEngineer** [comment]
Sorry for using some of your time, appearently reinstalling works for me

Op 30 aug. 2016 18:06 schreef "Tim Biesmans" <timbiesmans31@gmail.com>:

**Comment by Iamblichos** [comment]
Thanks. Go ahead and close this issue.
