### ISSUE TITLE
Am I supposed to get God of Creation bonuses all game, even after not founding and getting converted?

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2433]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/18

1. Mod List (if using standard CPP set, leave blank):
Full VP
JFD Exploration (everything but Resources turned off), JFD Cultural Diversity
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Celtic City Names, Iroquoian City Names, Randomize City Names
My own thing that does various things SQL type stuff
Tectonic Map

2. Type of error (i.e. crash, interface bug, AI quirk): I know its been awhile now, but I've never really understood the actual structure of the religion rework from months ago. Are this kind of 'global benefit' type of pantheon intended to stick around? All of my cites are following the Mayan religion. And it has Ritual, so there aren't like one or two pantheon followers hiding out somewhere. Normally I conquer a Holy City quickly enough to have never noticed I guess. Well, plus, I think God of Creation is still so OP in the early game imo that I have a rule against taking it, but I literally got beat to the fishing boat pantheon by one turn, so I decided to make an exception lol. (And I thought it was OP before even knowing the 8 happiness stays all game)

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by SpankMyMetroid** [comment]
I can attest to this, picked god of all creation in my game and the benefits stuck around when my cities started getting converted (including the capital)... the pantheon went away when I captured a holy city though.
