### ISSUE TITLE
Unable to liberate City States

### ISSUE THREAD

**Issue by gstew32** [LoneGazebo/Community-Patch-DLL#2436]
Bug Report Template

Mod Version (i.e Date - (4/23b)): version 8/18

1. Mod List (if using standard CPP set, leave blank):

Only Info addict other than standard Vox mods

2. Type of error (i.e. crash, interface bug, AI quirk): 

In multiple games over multiple versions whenever I attempt to liberate a CS I am unable to do so.  I capture the city without the puppet popup screen and I get an alert that I am unable to raze capitals.  Even when I get a request from a fellow CS to liberate one that has fallen to barbarians I get the same result.  This is nothing new and I have reported it before with no suggestions for how to fix the issue.  I experience NO other issues or bugs with the latest versions and do a complete clean install of the MOD with every new version.  When i capture an enemy city that is NOT a CS I am able to decide whether or not to puppet, raze etc.  The issue only happens with City States.

3. Steps to reproduce:

I have never been able to liberate a CS in ANY version of CP, CBP or VP.

4. Additional information:

This bug is the only one I am currently encountering.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Are you using any other mods? If you have logging enabled, post lua.log from game. If not, enable logging, replicate event, then post logs.

**Comment by gstew32** [comment]
I do have logging enabled, but have progressed past that point (I let a nearby CS that I am allied with take the city).  Will the issue still show up in the Log?  If so I will post when I get home otherwise I will try to find an auto save and replicate the issue.

**Comment by LoneGazebo** [comment]
Logs refresh when you reload the game, so it needs to be a log from the session that it happens in.

**Comment by gstew32** [comment]
i was able to replicate the issue by going back to an autosave.  Attached is the lua file
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/445802/Lua.zip)

**Comment by LoneGazebo** [comment]
Runtime Error: Assets\UI\InGame\PopupsGeneric\PuppetCityPopup.lua:64: Instance does not exist.

Why are you not running (4) (5) and (6)? There is no (7).

**Comment by gstew32** [comment]
Considering that I had just booted up that save and played a few turns how do I fix the run time error?

**Comment by LoneGazebo** [comment]
Well, you don't have the proper installation. As such, you don't have the proper lua files. I can't debug nonstandard installs.

**Comment by gstew32** [comment]
I have always done manual installations by downloading the files from your link and following instructions to the letter.  When i have used the .exe in the past i have NOT gotten correct installs either.  I will try to reinstall the mod using the .exe and see if the mod runs correctly.

**Comment by gstew32** [comment]
I wonder how I am getting a bad installation when I am following the instructions to the letter.  Any idea what file I am missing?

**Comment by gstew32** [comment]
I reinstalled the game, but i fear that I will not be able to run the old save game without encountering the same issue.  If/when I get the issue again I will let you know.

**Comment by LoneGazebo** [comment]
You need (1) thru (6b) (no-EUI) in your case. It will not be savegame compatible.

**Comment by Iamblichos** [comment]
If you are doing a manual install as well, you need to insure you delete the LUA folders from (1)CP and (2)CBP as well...if you aren't already doing this.

**Comment by gstew32** [comment]
After a reinstall running all the mods I was able to liberate a city state.  Obviously I was missing a file present in (6)

Thanks guys!

**Comment by LoneGazebo** [comment]
Yep!
