### ISSUE TITLE
Allied city states not DOWing enemies

### ISSUE THREAD

**Issue by SpankMyMetroid** [LoneGazebo/Community-Patch-DLL#2437]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/18

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): AI Quirk

3. Steps to reproduce: In the AI's case, some allied city states (maybe allied while I was at war with them?) did not attack me and were not attackable (however, peace was still blocked but they weren't fully angry at -60). In the player's case, specifically one CS I allied during a war would not attack enemy troops (and I didn't get flanking bonuses from their troops being next to the enemy).

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by oedali** [comment]
I am seeing the same issue. I am allied with 4 CS and at war w/ Poland. 3 of the 4 declared war on Poland but the 4th (Brussels) one did not. See screenshot. Poland continues to trade w/ them etc. 

![20160831223811_1](https://cloud.githubusercontent.com/assets/20485377/18153508/f508f9ee-6fcb-11e6-875b-083b660ee3cb.jpg)

**Comment by oedali** [comment]
FYI - my influence dropped to Friendly w/ Brussels. I sent an envoy and made them an ally again. Same as before, no war declaration w/ Poland.
