### ISSUE TITLE
CityEvents OneShot

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2439]
Are they locked to the city or to the player of the city? (If Arabia captures the city that has an one-shot event, is the Arabian-captured city able to get it again? If so, if the former city owner recapture it from Arabia, can the one-shot event fire up again?)

Or in another terms: Does the one-shot property restart upon different city owners.

**Comment by LoneGazebo** [comment]
It resets.
