### ISSUE TITLE
Franchises removed on second trade route

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#2440]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8/18

1. Mod List (if using standard CPP set, leave blank):
Infoaddicts, terrain colour, civ colour.

2. Type of error (i.e. crash, interface bug, AI quirk): 
Bug

3. Steps to reproduce:
Once I have a corporation, first trade route to a foreign city builds a franchise. Second trade route to the same city removes the franchise.

4. Additional information:
I noticed this playing Carthage on last version, but it could be happening before.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
There's no code for this, so technically it is impossible. Any corroborating evidence for me?
