### ISSUE TITLE
Natural Wonders owned by City States aren't increasing yields by Era

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2441]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/18

1. Mod List (if using standard CPP set, leave blank):
Full VP
JFD Exploration (everything but Resources turned off), JFD Cultural Diversity
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Celtic City Names, Iroquoian City Names, Randomize City Names
My own thing that does various things SQL type stuff
Tectonic Map

2. Type of error (i.e. crash, interface bug, AI quirk): Barringer Crater, Great Barrier Reef, and Fountain of Youth are all owned by City States and have starting yields even tho its the Ren and Ind for the leaders. (Guess I'm not sure exactly how minor tech progress even works.) Sri Pada and Lake Victoria are owned by majors, and have the enhanced yields.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![nw1](https://cloud.githubusercontent.com/assets/16260521/18129907/d7393792-6f5a-11e6-9657-fe0af834c086.jpg)

**Comment by LoneGazebo** [comment]
That's intentional - minors don't have the same tech progression as majors. Not a big deal, as minors play their own game most of the time.
