### ISSUE TITLE
EventChoice_SpecialistYieldChange Tooltip

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2443]
The event choices change the yield of the specialist, but doesn't dynamically change the tooltip to match the changed yield. So players are assuming their specialists aren't giving them the bonuses when in fact they are.

**Comment by LoneGazebo** [comment]
Should as long as you are using proper cityview lua files to support it (i.e. the 6a 6b files).

**Comment by TechpriestEnginseer** [comment]
![image](https://cloud.githubusercontent.com/assets/13937047/18147436/72993074-6f89-11e6-904c-de35f3018b5d.png)
![image](https://cloud.githubusercontent.com/assets/13937047/18147452/7f4ac0c6-6f89-11e6-98d1-ccaccca11ba2.png)

Users have 6a and have confirmed the tooltips aren't displaying there despite their choice are granting +1 gold from specialists.

**Comment by LoneGazebo** [comment]
And the tooltip for it? Also bad?

**Comment by TechpriestEnginseer** [comment]
Presumably.
