### ISSUE TITLE
Pioneer Has No "Settle a City" Ability

### ISSUE THREAD

**Issue by GhostScout42** [LoneGazebo/Community-Patch-DLL#2446]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8-18

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): INTERFACE BUG, MISSING PROMOTION

3. Steps to reproduce: PLAY GAME, ATTEMPT TO SETTLE CITY WITH PIONEER. (DIDO, POCATELLO) 

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/448588/Logs.zip)

2. Minidump file (located in your Civ5.exe directory
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/448593/CvMiniDump.zip)

3. Screenshots (if needed)
![20160831195510_1](https://cloud.githubusercontent.com/assets/21374235/18151480/12b08d20-6fb5-11e6-872a-8775968d13df.jpg)

**Comment by LoneGazebo** [comment]
You can't settle right there. Too close to Smolensk.

**Comment by GhostScout42** [comment]
Wow. im sorry i wasted your time then. in base game, dont units that settle have a promotion and shouldnt the settle a city option be there but greyed out? 

(im not sure when catherine settled smoleensk, ive had my eye on that spot for ages.)

**Comment by LoneGazebo** [comment]
There was never a 'settle' promotion - it is a unit attribute, not a promotion.

**Comment by GhostScout42** [comment]
okay, thanks alot man! you guys keep up the great work, this mod got me back into civ after a very long time away.

**Comment by LoneGazebo** [comment]
Glad you enjoy it!
