### ISSUE TITLE
CP: City State screen

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#2447]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
8/18

1. Mod List (if using standard CPP set, leave blank):
only Community Patch
without EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 
Tag error?

3. Steps to reproduce:
Check a City State screen.
Click the "Ask for Tribute".
You can see "**TXT_KEY_POPUP_MINOR_BULLY_UNIT_AMOUNT_CBP**".

4. Additional information:
cf.
(1) Community Patch\LUA\CityStateDiploPopup.lua

`buttonText = Locale.Lookup("TXT_KEY_POPUP_MINOR_BULLY_UNIT_AMOUNT_CBP", sBullyUnit, iBullyUnitInfluenceLost);`

should be

`buttonText = Locale.Lookup("TXT_KEY_POPUP_MINOR_BULLY_UNIT_AMOUNT", sBullyUnit, iBullyUnitInfluenceLost);`

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

![cs](https://cloud.githubusercontent.com/assets/11933188/18165305/71aad2e8-707f-11e6-9b34-b14101b9afeb.png)

**Comment by Iamblichos** [comment]
@LoneGazebo 
This is the UI text to do list stuff I was referring to.

**Comment by LoneGazebo** [comment]
Gotcha.
