### ISSUE TITLE
Game stops responding totally

### ISSUE THREAD

**Issue by Ssssusrgf** [LoneGazebo/Community-Patch-DLL#2449]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
August 18th (1.8.18)

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
Game stops responding to anything, no Windows "Task is not responding" though

3. Steps to reproduce:
[Savegame.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/450258/Savegame.zip)
Upon loading the savegame, click on "automatic exploration" on the selected scout.

4. Additional information:
Loaded the game twice with the same result each time. Game seems to enter an endless loop, can't close it or even minimize it to stop it through the task manager. Only way to exit the game was restarting the PC each time.
First game  I played with this mod. I only used the mods that the [automatic installer](http://forums.civfanatics.com/showthread.php?t=528034) installed, no others.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Reduce graphical settings, turn off core threading in config.ini.

**Comment by Ssssusrgf** [comment]
turning off core threading seems to resolve that, thanks!

**Comment by LoneGazebo** [comment]
Yep!
