### ISSUE TITLE
Archaeologists in rival territory interrupted by rival workers "improving" blank tile made by dig

### ISSUE THREAD

**Issue by SpankMyMetroid** [LoneGazebo/Community-Patch-DLL#2452]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 8/18

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): AI Quirk

3. Steps to reproduce: This has happened on occasion for a while over the last few patches but I never figured out the reason why and was hoping it would get patched. But this game, when I sent my archaeologist to a site in another civ's lands (with open borders), I noticed that it stopped digging when a worker was making an improvement on the same tile. I figured that since starting the dig gets rid of the improvement, which triggered the worker to go improve that tile again, there's something preventing a tile being "improved" by two units at once and their unit took priority. Sure enough, I let the worker finish the improvement, moved back onto the tile, and was able to finish the dig (it even saved my progress). So I don't know if this is intended but it gets annoying because in previous builds if my archaeologist stopped digging it would usually not be able to complete it again before an archaeologist belonging to the rival civ finished the dig (though you might be able to stop other civs from stealing your sites if you send a worker there too, I haven't tested it). And there are still one or two odd sites in every game that are never able to be excavated by anyone... but I think that's unrelated.  

On the same note I wasn't able to build an embassy in a city state on a tile that was being improved. I had to wait until the improvement was finished and then I was allowed to build it.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
Weird. Must be an issue with civilian multi unit per tile.

**Comment by Iamblichos** [comment]
I also have a feeling that 'IgnoreOwnership' is not working completely through in all instances.

**Comment by Iamblichos** [comment]
I wonder if we need an extra control path for bTestVisible

**Comment by LoneGazebo** [comment]
I already fixed, I believe. This was an AI issue, not a universal plot issue.

**Comment by Iamblichos** [comment]
Can you tell me what function you addressed?

**Comment by LoneGazebo** [comment]
buildertaskingAI was ignoring tiles being improved by other civs in owned territory,
