### ISSUE TITLE
RandomBarbarianSpawnNotUU

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2453]
Could we get a **RandomBarbarianSpawnNotUU** tag for the EventChoices and CityEventChoices tables, that basically functions as RandomBarbarianSpawn, but won't spawn unique units. 

Also, seems like the number of units spawned isn't accurate - I have 3 set to spawn, but only two do (and it doesn't seem to be a problem of visibility).

In addition, does FreeUnitsTechAppropriate also filter out unique units (other than the player's own)?

Thanks!

**Comment by LoneGazebo** [comment]
I'll make sure that both avoid UUs. I'll also check the number.

**Comment by Iamblichos** [comment]
how about the free units from events get xp production from pLoopCity?

**Comment by LoneGazebo** [comment]
@Iamblichos I can do that for city level, but not player level units.

**Comment by Iamblichos** [comment]
but player units spawn from pLoopCity...pLoopCity can point to get xp production.

**Comment by Iamblichos** [comment]
....or you could just do it from player capital.

**Comment by LoneGazebo** [comment]
Ah misunderstood what you were asking. I'll fix. Refactored that anyways.
