### ISSUE TITLE
EventChoice_FreeUnits and CityEventChoice_FreeUnits

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2454]
(Last request before the next update is out) Do you think you could add **PromotionType** to the **EventChoice_FreeUnits** and **CityEventChoice_FreeUnits** tables, so that a unit spawned via this method begin with the specified promotion (if valid)?

**Comment by LoneGazebo** [comment]
Hmm...it changes the table quite a bit, but I'm sure I can manage.

**Comment by LoneGazebo** [comment]
Well, actually, it'll greatly affect the overhead. What if I add a lua hook for when the unit is created? Would that work?

**Comment by JFDaly** [comment]
Yup, a lua hook would in fact be more useful, as when I had this table (before you added it officially), I had tags for extra XP, extra HP, etc.. It had crossed my mind, but I'd figured that would be more work than the tag. Thanks!

**Comment by LoneGazebo** [comment]
Yeah, the hook is easier (the table would have to be custom-formed otherwise). Lua hook will be:

EventUnitCreated(PlayerID, EventChoiceID, CvUnit* pUnit)
