### ISSUE TITLE
Pseudo-Natural Wonders

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2457]
http://forums.civfanatics.com/showthread.php?p=14419466

@LoneGazebo 

There was some interest here and so I integrated this guys code into my branch (plus all the places he needed to incorporate it for the AI). Think we should add it into the DLL?

![20160902162738_1](https://cloud.githubusercontent.com/assets/14372214/18218763/a5e50514-712a-11e6-9a3f-a87317fb4db4.jpg)

![20160902162747_1](https://cloud.githubusercontent.com/assets/14372214/18218768/aa9e3c42-712a-11e6-8872-d4903e1ae5b8.jpg)

![20160902162834_1](https://cloud.githubusercontent.com/assets/14372214/18218771/ae7ba4da-712a-11e6-88cc-4c939d4d76cd.jpg)

**Comment by Iamblichos** [comment]
![20160902162747_1](https://cloud.githubusercontent.com/assets/14372214/18218777/b8b98070-712a-11e6-90fb-bb5e441365bd.jpg)

**Comment by LoneGazebo** [comment]
Its interesting...might see if Estebanium is willing to create some more elegant-looking artwork for them before moving on it, though.

**Comment by Iamblichos** [comment]
Sure. That's all Database update work. But I got the code in place to be used.

**Comment by Iamblichos** [comment]
This is good to show the conceptual ability.

**Comment by Iamblichos** [comment]
Incorporated. Closing out.
