### ISSUE TITLE
Scout cannot cross ocean even though would end on visible coastal tile

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2459]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 9/2

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): Bug or deliberate rule change?

3. Steps to reproduce: Prior to this version, pre-Astronomy, my embarked land units could cross oceans as long as they started and landed on a coastal tile, and everything inbetween was visible. w/ this new version, this is no longer possible. See screenshot. Is this intended? Didn't see in the change notes

![20160902235823_1](https://cloud.githubusercontent.com/assets/20485377/18222576/b1124480-7169-11e6-8119-d3acc4390cfd.jpg)

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by LoneGazebo** [comment]
@ilteroi, unintended end-plot change?

**Comment by oedali** [comment]
(Naval units like triremes can still pass BTW.. I observed the change only w/ embarked land units)

**Comment by Iamblichos** [comment]
Intended. Was not implemented for embarked units.

**Comment by ilteroi** [comment]
it was only ever intended for "real" naval units - i fixed this along with the "end turn on ocean" bug. 

but i can bring it back if there's demand

**Comment by LoneGazebo** [comment]
One thing on this ilteroi. I've noticed that the functionality of this can be a little wonky. If you are trying to make a naval unit hop across an ocean tile via a multi turn move, the unit has to be adjacent to the ocean for the pathfinder to allow it. This makes moves that are legal seem illegal.

**Comment by oedali** [comment]
If it was intentionally like that perhaps better to keep it that way... I did abuse a lot in previous versions by fully scouting other continents prior to astronomy and even spreading my religion (w/o realizing it was unintended)

**Comment by ilteroi** [comment]
re: failing multi turn moves. i could reproduce it, but it seems it's not even necessary that it's multi turn.

i think the problem is that i recently disabled advanced pathfinding features for humans (because of user complaints - i guess it could be hard to understand why a unit suddenly took liberties executing an order) 

anyway that includes "voluntary" stops during pathfinding. it can happen that a unit needs to take a break because it can't cross the ocean this turn with the remaining movement points. but it is not allowed anymore. tricky.

**Comment by Iamblichos** [comment]
Multi turn moves ought to be discouraged anyways because it's poor play and bad strategy.

**Comment by LoneGazebo** [comment]
Encouraged or not the fact that the move appears impossible until the unit is in a specific spot does make it hard for newcomers to see some of our pathfinder changes. If too much hassle to fix don't worry about it. More of a QOL issue than an actual problem.

**Comment by ilteroi** [comment]
in it's current form the pathfinder does not have forward conditionals like "if the next plot is such and such, then do this and that". it only looks backwards after the fact, to see if the move was valid. switching it around might be possible and in fact more elegant ... need to think about it

**Comment by LoneGazebo** [comment]
If it is a huge task don't bother. If you think it is worth the work then I leave it to you.

**Comment by ilteroi** [comment]
well you know me - can't resist a challenge :)

**Comment by ilteroi** [comment]
ok i think i got it. not as complex as i had feared.

pushed. with my brand new vc2013 solution file btw, in case anyone fancies a fresher IDE :)

**Comment by oedali** [comment]
Does this mean embarked units will be able to cross as before, if I re-install 9-2 version? Or is it fixed for upcoming release?

**Comment by LoneGazebo** [comment]
No, we're not reimplmenting that for embarked units - this is a discussion about the pathfinder.

**Comment by oedali** [comment]
Ah ok thanks

**Comment by Edaka** [comment]
Sorry if off-topic, but related to voluntary stops: I've noticed a while back that trade units (caravans and cargo ships) started doing those stops, seemingly unnecessary. I mean, once you've sent out a trade unit on a trade mission, nothing can alter its path, yet it will take a short break from moving on every tile. Just a minor visual issue that doesn't affect gameplay, but drags for a couple of seconds that you have to wait out before you can end a turn every now and then.
