### ISSUE TITLE
Caroleans

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#246]
Caroleans (Sweden UU- Musketman) upgrades to Rifleman

**Comment by LoneGazebo** [comment]
They're supposed to upgrade to Riflemen, that's how all UUs work (they upgrade into the next unit in the tier, though they don't obsolete until two generations in).

G

**Comment by phantommaxwell** [comment]
the Upgrade path is Musketman - Fusilier - Rifleman

Also every Cavalry UU obsoletes at Combustion, which is the in the next line of Techs.

**Comment by LoneGazebo** [comment]
But Caroleans aren't cavalry. I'm confused. 
G

**Comment by phantommaxwell** [comment]
In an unrelated note... I noticed that about Cavalry; they obsolete right away
