### ISSUE TITLE
Ai not expanding

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2460]
2/9 version

![image](https://cloud.githubusercontent.com/assets/1358966/18223523/38c5e062-71ba-11e6-887a-fcbabddeec28.png)

this is turn 130 ... rome hasn't built a settler yet

130, Rome, Rome, PRE: Unit, Settler, 5450, 2
130, Rome, Rome, PRE: Process, Farming, 285, 1
130, Rome, Rome, PRE: Unit, Spearman, 266, 1
130, Rome, Rome, POST: Process, Farming, 570, 1
130, Rome, Rome, POST: Unit, Spearman, 266, 1
130, Rome, Rome, SEED: 6556112017587586107, CHOSEN: Spearman, Do not rush, TURNS: 1
130, Rome, Rome, PRE: Unit, Settler, 4984, 3
130, Rome, Rome, PRE: Process, Farming, 285, 1
130, Rome, Rome, PRE: Unit, Spearman, 234, 2
130, Rome, Rome, POST: Process, Farming, 581, 1
130, Rome, Rome, POST: Unit, Spearman, 234, 2
130, Rome, Rome, SEED: 10725792420892741809, CHOSEN: Farming, Do not rush, TURNS: 1

first, why is the selection done twice? secondly, why is the settler eliminated?

**Comment by LoneGazebo** [comment]
Has it explored much?

**Comment by Iamblichos** [comment]
Expanding all over the place for me.

**Comment by LoneGazebo** [comment]
Likewise @iamblichos

**Comment by ilteroi** [comment]
that was my first try ... 7 of 8 civs expanded fine. and rome did as well, eventually (around turn 170 iirc).

but they did explore fine:

![image](https://cloud.githubusercontent.com/assets/1358966/18226886/bf85a782-7213-11e6-8b7f-578e16f958f1.png)

**Comment by ilteroi** [comment]
just ran the game again from the initial save, this time rome built a settler on turn 42. so much for reproducability of AI play.

**Comment by ilteroi** [comment]
closing since not reproducable ...
