### ISSUE TITLE
infoaddict & steam

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2461]
so i'm a big fan of infoaddict - but infortunately it's been known to cause crashes on reloading, which is not so nice especially for debugging.

now i'm clueless about lua, so question @Iamblichos : do you think there's a chance to fix it?

also, @LoneGazebo : what about the steam release? we need to head off civ 6 :)

**Comment by Iamblichos** [comment]
Do you get a lua runtime error when it crashes?

**Comment by LoneGazebo** [comment]
Steam soon yes.

**Comment by ilteroi** [comment]
would would a runtime error look like? it crashes somewhere inside civ5.exe (iirc) almost everytime you load a game from within a running game.

**Comment by Iamblichos** [comment]
check your lua log. I'll take a look at its lua.

**Comment by ilteroi** [comment]
ok there were two crashes now:

1. started game without infoaddict, reload works fine. exit to main menu, activate info addict, try to load the same savegame, crash at cvluagame.cpp (1319): CvLuaGame::lGetActivePlayer (invalid pointer passed from Lua)

[Lua1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/453598/Lua1.zip)

2. started game with infoaddict from the get-go. load a game, load another game, end turn, crash here, again invalid pointer passed from Lua

![image](https://cloud.githubusercontent.com/assets/1358966/18227719/a5501058-722e-11e6-8101-73cd212b6d68.png)

[Lua2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/453646/Lua2.zip)

**Comment by ilteroi** [comment]
and another oddity. the tech tree is broken on first load. after reloading the same save, it's fine:

initial load
![image](https://cloud.githubusercontent.com/assets/1358966/18227816/54c29ffe-7231-11e6-907a-d0e66d6b2e8f.png)

reload
![image](https://cloud.githubusercontent.com/assets/1358966/18227819/62b2ba22-7231-11e6-974f-17d89a926323.png)

then another crash when exiting to main menu ... something is really rotten here

![image](https://cloud.githubusercontent.com/assets/1358966/18227826/e998499e-7231-11e6-90b9-067fa3ae9a05.png)

this is all with infoaddict and EUI, btw. i don't know which one is worse ... but at least in combination they are deadly. i applied the infoaddict path for EUI by the way, don't know what it's supposed to fix but apparently not stability.

**Comment by Iamblichos** [comment]
I can fix all that. Let me get through the weekend.

**Comment by Iamblichos** [comment]
I'll just make a custom version of info addict.

**Comment by Iamblichos** [comment]
Don't you justt love lua? It's easy but it's not. c++ much more intuitive.

**Comment by ilteroi** [comment]
wow, that's good news!

**Comment by Vyyt02** [comment]
Wow, thanks! By the way, I have never had the garbled research screen after reload. However, I get the CTD like 80% after reload with InfoAddict though.

**Comment by Weketor** [comment]
Do you guys use this compatibility file? InfoAddictHooks.lua

**Comment by Iamblichos** [comment]
I haven't had a chance to address this yet.

**Comment by Iamblichos** [comment]
A couple of things here. You can't start a game without infoaddict and then load it later with infoaddict(I believe you must start from the get-go with InfoAddict).

Weketor is correct about the compatibility file (tested it and no crashing). Apparently the work is already been done to fix this. So here's InfoAddict with the compatibility file:

[InfoAddict.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/467660/InfoAddict.zip)

**Comment by Iamblichos** [comment]
@ilteroi Let me know if that fixes everything for you, if not let me know and I'll do more digging.

**Comment by ilteroi** [comment]
as i wrote above, i already applied that patch - but i just did a diff and found a small difference in InfoAddictLib.lua, maybe that does the trick.

**Comment by Iamblichos** [comment]
ah I gotcha missed that part...path= patch

**Comment by Iamblichos** [comment]
If that doesn't work, we can try the DLC method of InfoAddict and see if that works.

**Comment by Iamblichos** [comment]
@ilteroi Never heard back on this one. Is it working for you?

**Comment by ilteroi** [comment]
seems to be better. maybe it was only that strange lua dll i had forgotten about

**Comment by ilteroi** [comment]
sorry for the fuss

**Comment by Iamblichos** [comment]
No problem. You can close out if you feel good about it now.
