### ISSUE TITLE
event bug

### ISSUE THREAD

**Issue by zahfares** [LoneGazebo/Community-Patch-DLL#2462]
Bug Report Template

Mod Version (i.e Date - (4/23b)):    Vox Populi (8-18)

1. Mod List (if using standard CPP set, leave blank):
- (1) Community Patch
- (2) Community Balance Overhaul
- (3) CSD for CBP
- (4) Civ IV Diplomatic Features
- (5) More Luxuries
- (6a) Community Balance Overhaul - Compatibility Files (EUI)
- InfoAddict (v 22)
- Ingame Editor (v 39)
- PerfectWorld 3 (v 4) (stuck even in normal maps BTW)
- UI - Trade Opportunities (v 28)
- Yet (not) Another Earth Maps Pack (v 22) (not active tho)

2. Type of error (i.e. crash, interface bug, AI quirk):   interface bug I suppose!

3. Steps to reproduce: 
>Morocco 
>turn 62 
>new event notification pop out in list (like new building order)
>I click, can't open, can't next turn!
>every game I get event decision, nor can I continue!

4. Additional information:
First time modding and using Vox Populi

tnx
---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Iamblichos** [comment]
Might want to try updating to the latest version.

**Comment by LoneGazebo** [comment]
Dont use UI trade opportunities and make sure civ up to date.

**Comment by zahfares** [comment]
When I checked in the Mods compatible with the CBP, I saw the UI trade opportunities is in the Incorporated into CBP list, but It was crossed over so I thoght now it's fine to add it :P sry for the trouble and tnx

**Comment by zahfares** [comment]
nope :(
>deleted UI trade opportunities
>new game
>Mongolia
>plains +
>turn 30ish 
>city event
>click, not-ing! can't open
+ Civ is .279 :P

**Comment by LoneGazebo** [comment]
Enable logging, reproduce bug, then post lua.log.

**Comment by LoneGazebo** [comment]
Still betting that it is a mod conflict or a bad install, however.

**Comment by Iamblichos** [comment]
He still needs to update to latest version b

**Comment by zahfares** [comment]
done.
bad install, EUI problem.
-reinstalled
turns out the events Overview tab (up right), had the info edict tab over it, now after reinstall, were all good each with own tab.
tnx and sry for the trouble.
