### ISSUE TITLE
CTD on AI turn

### ISSUE THREAD

**Issue by nOxrax** [LoneGazebo/Community-Patch-DLL#2463]
Mod Version (i.e Date - (4/23b)): 
**9-2 with hotfix**

1. Mod List (if using standard CPP set, leave blank):
**CP only, hotseat**

2. Type of error (i.e. crash, interface bug, AI quirk): 
**Crash**

3. Steps to reproduce:
In the autosave, press end turn for player 1 and then for player 2. It crashes during AI nr. 10's turn.
[CTD on AI turn.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/453613/CTD.on.AI.turn.zip)

**Comment by LoneGazebo** [comment]
Test this CP, see if you can get past crash; https://mega.nz/#!vBtEGJoC!2xykAPvKDuvBYaLLqq-12EsyvByl-PDvdBS60hQIvic

**Comment by LoneGazebo** [comment]
It is savegame compatible.

**Comment by nOxrax** [comment]
Yes, this works! Thank you.

**Comment by Vyyt02** [comment]
Wow, Gazebo you are a Godsend! You fix my bugs before they happen to me :) I got a CTD too and checked if I find anything here - and of course I did. Thank you!

Oh, but now I can see the most of the city stats in the left top part of the city view (current science, unhappiness, etc.) are missing - except hammers / production. Also, when I hover over the city banner in the map, I do not get the unhappiness breakdown, only religious.

I tried replacing CP with the old one again after a couple of turns. The stats are back, but I got a CTD again, right after pressing the next button. Mind you I did not dare to clear cache - I am using too many mods.

> **nOxrax**: Are you not experiencing the same thing?

**Comment by LoneGazebo** [comment]
Delete the Lua folder in the CP @vyyt02

**Comment by Vyyt02** [comment]
> **LoneGazebo**: Ahh, so that was it, got it. Well, I got utterly crushed by the Japanese (their injured bushido horseman sliced through my inexperienced warriors like a hot knife through butter - I can hear your evil laugh). I started a new game and all is working fine now.

Thanks!

**Comment by LoneGazebo** [comment]
Haha. Glad to hear it!
