### ISSUE TITLE
Coal not shown anywhere but on the map

### ISSUE THREAD

**Issue by Knecht-Ruprecht** [LoneGazebo/Community-Patch-DLL#2464]
After the necessary reseach is done, coal does show up as a resource on the map (with the correct tool tip) and can be acquired by constructing mines above it. It seems to be counted correctly in regards to the number of coal-utilising buildings that can be constructed.
However, it is neither shown as a strategic resource in the top bar, nor at the monopolies screen. It seems not to be available for trade deals, either.

Mod Version 8/18:

1. Mod List (if using standard CPP set, leave blank):
Standard VP 8-18 with EUI

2. Type of error (i.e. crash, interface bug, AI quirk): 
Interface bug

3. Steps to reproduce:
Set up game starting in Modern Era or later or research the tech showing coal as a resource

4. Additional information:

- cleaned up mods folder, EUI and database file

- tried on two different machines with different map types

- more advanced resources (oil, aluminium) are not affected

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict or something. Coal is otherwise treated normally.

**Comment by Iamblichos** [comment]
Never heard of this happening ever. Need more info.

**Comment by Knecht-Ruprecht** [comment]
I'll try to narrow this down when I get back home tomorrow.

**Comment by Knecht-Ruprecht** [comment]
After an absolutely clean install (completely removing the CiV folders from steamapps and "my games") and reinstalling the mod, this issue does not show up anymore. Strange enough, as it showed up on both of my machines and the current installation should - in theory - be in every aspect identical to the previous one.

**Comment by LoneGazebo** [comment]
Interesting. My guess is that two copies of EUI ended up in your DLC folder somehow.
