### ISSUE TITLE
EventPolicy from EventChoices have no effect

### ISSUE THREAD

**Issue by enimog** [LoneGazebo/Community-Patch-DLL#2465]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
09/02 hotfixhotfix

1. Mod List (if using standard CPP set, leave blank):
 - CPP/EUI standard

- RED Modpack

- Personal custom build of the following mods (mainly bugfixes / compatibility patch, a few additions, should not impact in any way the noticed issue, can provide sources if needed): 

 - Sukitract's Event and Decisions

 - JFD's cultural diversity

 - Wes's Civ 4 Leader Trait

 - ViceVirtuoso's Wish for the World

 - ViceVirtuoso's Hyperdimension Neptunia (All civilizations)

2. Type of error (i.e. crash, interface bug, AI quirk): 
Event gifted policy have no effect

3. Steps to reproduce:

- Add the following event in the game : 

```
----------------------------------------------------------------------------------------------------------
-- Old Sword in the Ruins
-- This event has a chance to trigger when the player finds an Ancient Ruin.
-- If the player chooses to keep the sword, they will be plagued by war and bloodshed...
----------------------------------------------------------------------------------------------------------

INSERT INTO Policies(Type,Description,PolicyCostModifier)
VALUES('POLICY_EVENT_NEPGEAR_GEHABURN_1','TXT_KEY_POLICY_GEHABURN_1',-25),
	  ('POLICY_EVENT_NEPGEAR_GEHABURN_2','TXT_KEY_POLICY_GEHABURN_2',0);
	  
INSERT INTO Policy_CapitalYieldChanges(PolicyType,YieldType,Yield)
VALUES('POLICY_EVENT_NEPGEAR_GEHABURN_2','YIELD_SCIENCE',2);

INSERT INTO Policy_CapitalYieldModifiers(PolicyType,YieldType,Yield)
VALUES('POLICY_EVENT_NEPGEAR_GEHABURN_2','YIELD_SCIENCE',50);

INSERT INTO Events (Type,Description,Help,EventAudio,RandomChance,RandomChanceDelta,NumChoices,EventClass,IsOneShot)
VALUES('PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD_DESC','AS2D_INTERFACE_CITY_TILE',0,0,3,'EVENT_CLASS_CIV_SPECIFIC','true');

INSERT INTO Event_ParentEvents (EventChoiceType,EventType)
VALUES('PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD_CHOICE_1','PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD'),
	  ('PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD_CHOICE_2','PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD'),
	  ('PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD_CHOICE_3','PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD');

INSERT INTO EventChoices (Type,Description,Help,EventChoiceAudio,EventPolicy)
VALUES('PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD_CHOICE_1','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD_OUTCOME_1','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD_OUTCOME_1_RESULT','AS2D_EVENT_CHOICE','POLICY_EVENT_NEPGEAR_GEHABURN_1'),
	  ('PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD_CHOICE_2','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD_OUTCOME_2','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD_OUTCOME_2_RESULT','AS2D_EVENT_CHOICE','POLICY_EVENT_NEPGEAR_GEHABURN_2'),
	  ('PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD_CHOICE_3','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD_OUTCOME_3','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD_OUTCOME_3_RESULT','AS2D_EVENT_CHOICE',null);

INSERT INTO EventChoice_Notification(EventChoiceType,NotificationType,Description,ShortDescription)
VALUES('PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD_CHOICE_1','NOTIFICATION_GENERIC','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD_OUTCOME_1_NOTIFICATION','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD'),
      ('PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD_CHOICE_2','NOTIFICATION_GENERIC','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD_OUTCOME_2_NOTIFICATION','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD'),
	  ('PLAYER_EVENT_PLANEPTUNE_NG_FIND_EVIL_SWORD_CHOICE_3','NOTIFICATION_GENERIC','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD_OUTCOME_3_NOTIFICATION','TXT_KEY_EVENT_VV_PLANEPTUNE_NG_FIND_EVIL_SWORD');
```
- Get the event and choose option 1. The player should see its policy cost dropped by 25%. In my case there is no chance in culture cost.

- Get the event and choose option 2. The player should see its capital having +2 science and +50% science. In my case there is no change to science yield in the capital or global.

 - Giving the Policy from lua using the following code gives the correct effect : 
```
			pPlayer:SetNumFreePolicies(1)
			pPlayer:SetNumFreePolicies(0)
			pPlayer:SetHasPolicy(GameInfoTypes.POLICY_EVENT_NEPGEAR_GEHABURN_1, true)
```

and 

```
			pPlayer:SetNumFreePolicies(1)
			pPlayer:SetNumFreePolicies(0)
			pPlayer:SetHasPolicy(GameInfoTypes.POLICY_EVENT_NEPGEAR_GEHABURN_2, true)
```
In my case this work properly.

4. Additional information:
For this event, there is currently 0% chance of having it. This is normal behavior, in my case there is lua code dedicated to trigger this event. For testing purpose, increase the value as you wish.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/453688/logs.zip)
2. Minidump file (located in your Civ5.exe directory)
N/A
3. Screenshots (if needed)
N/A

**Comment by LoneGazebo** [comment]
Going back to other posts, I'm fairly certain there's something in your local database or install that is wonky.

**Comment by enimog** [comment]
It's possible I wont deny it. At first glance I don't see anything wrong in it, but I'll try to find out on my own what might be the issue :) Might be something I don't do right when inserting my events and it cause an issue inside the dll somewhere

**Comment by LoneGazebo** [comment]
Do you know how to hook an SQL database reader into the debugcache? If not, check here: http://forums.civfanatics.com/showthread.php?t=559644

**Comment by enimog** [comment]
Yeah I'm using sqlitebrowser for that. I posted a screencap in another issue.

**Comment by enimog** [comment]
Closing issue because it was a bug on my side

**Comment by TechpriestEnginseer** [comment]
what did you do

**Comment by enimog** [comment]
I changed all references in lua for all my mods from
pPlayer:SetNumFreePolicies(1)
pPlayer:SetNumFreePolicies(0)
pPlayer:SetHasPolicy(..., true)
to
pPlayer:GrantPolicy(..., true)

**Comment by TechpriestEnginseer** [comment]
So, I have to resort to Lua either way. Oh well, thanks for the help!

**Comment by LoneGazebo** [comment]
i see the issue, actually. fixing. You don't need to resort to lua.
