### ISSUE TITLE
City event not happening

### ISSUE THREAD

**Issue by enimog** [LoneGazebo/Community-Patch-DLL#2466]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
09/02 hotfixhotfix

1. Mod List (if using standard CPP set, leave blank):
 - CPP/EUI standard

- RED Modpack

- Personal custom build of the following mods (mainly bugfixes / compatibility patch, a few additions, should not impact in any way the noticed issue, can provide sources if needed): 

 - Sukitract's Event and Decisions

 - JFD's cultural diversity

 - Wes's Civ 4 Leader Trait

 - ViceVirtuoso's Wish for the World

 - ViceVirtuoso's Hyperdimension Neptunia (All civilizations)

2. Type of error (i.e. crash, interface bug, AI quirk): 
City event never happens in the game

3. Steps to reproduce:

- Run the following code inside the game : 

```
function TestEvent(iPlayer)
	if iPlayer == 0 then -- if player is myself
		print("Testing event start")
		local pPlayer = Players[iPlayer]
		local capital = pPlayer:GetCapitalCity()
		capital:DoCityStartEvent(GameInfoTypes.CITY_EVENT_GOOD_HARVEST)
		print("Testing event end")
	end
end
GameEvents.PlayerCityFounded.Add(TestEvent)
```
- The player 1 should get the city event CITY_EVENT_GOOD_HARVEST. In my case he doesn't

4. Additional information:
This is also the case for every city event. City events are also not happening in a normal way. Player events work properly.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/453690/logs.zip)
2. Minidump file (located in your Civ5.exe directory)
N/A
3. Screenshots (if needed)

**Comment by Iamblichos** [comment]
Need if capital then check in lua code.

**Comment by enimog** [comment]
if capital was nil at least I would get a Lua error when running capital:DoCityStartEvent and then know why it doesn't work, which is not the case... Also the last print would not run, which it does. 

(Plus, I designed this code only to be able to quickly test all my events at the game start after using my settler and having a city, it is not *really* to play with it)

**Comment by LoneGazebo** [comment]
Can't debug custom builds. If you aren't getting Lua log errors then something is wrong with your database.

**Comment by enimog** [comment]
It might be something with my database then? I'll try to find what might be wrong and let you know if I find out, might be interesting to know for future people that write events.

**Comment by LoneGazebo** [comment]
enable logging and check your database.log.

**Comment by enimog** [comment]
database.log is included in the zip of this issue

One thing I noticed though looking inside the debug .db in the table Events and CityEvents is that the default boolean values are equal to 0 instead of true/false for the events I didn't fill the value (letting the default value takes place)
![database](https://cloud.githubusercontent.com/assets/11507070/18228537/1f5e8c34-7221-11e6-9416-b84ff78e443d.PNG)
I don't know if this could be a possible cause

**Comment by LoneGazebo** [comment]
Shouldn't be. Make sure you are assigning parent events and event linkers appropriately.

**Comment by enimog** [comment]
maaaaannnn I'm so embarassed, I did some error in my lua wrapper for events that inadvertently searched for player event when searching for city events, which is why they could not fire. So there was no bug for this one and the interface. Only the policy issue remains for me to find out the cause, but I'll close the three anyway. It's probably another lua bug somewhere.

**Comment by LoneGazebo** [comment]
No worries! Could happen to anyone. :)
