### ISSUE TITLE
No event is listed inside the event overview

### ISSUE THREAD

**Issue by enimog** [LoneGazebo/Community-Patch-DLL#2467]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
09/02 hotfixhotfix

1. Mod List (if using standard CPP set, leave blank):
 - CPP/EUI standard

- RED Modpack

- Personal custom build of the following mods (mainly bugfixes / compatibility patch, a few additions, should not impact in any way the noticed issue, can provide sources if needed): 

 - Sukitract's Event and Decisions

 - JFD's cultural diversity

 - Wes's Civ 4 Leader Trait

 - ViceVirtuoso's Wish for the World

 - ViceVirtuoso's Hyperdimension Neptunia (All civilizations)

2. Type of error (i.e. crash, interface bug, AI quirk): 
interface bug - event overview

3. Steps to reproduce:

- Start the game

- Get an event

- Chooses an option

- Look inside the event overview

4. Additional information:
N/A

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/453695/logs.zip)
2. Minidump file (located in your Civ5.exe directory)N/A
3. Screenshots (if needed)
![selectevent](https://cloud.githubusercontent.com/assets/11507070/18228244/1f8bf100-7213-11e6-9833-94a8d02ccdf3.PNG)
![afterevent](https://cloud.githubusercontent.com/assets/11507070/18228245/21823172-7213-11e6-8727-d5923a69170b.PNG)

**Comment by LoneGazebo** [comment]
you are looking at all three panels?

**Comment by enimog** [comment]
Yes, same things for the 2 others

**Comment by LoneGazebo** [comment]
enable logging and check your lua log. Also check your database.log. As I said, though, I can't debug custom builds (and these issues are not present on my build).

**Comment by enimog** [comment]
Closing issue because it was a bug on my side
