### ISSUE TITLE
Culture overflow with PolicyCost modifier (Vanilla Bug)

### ISSUE THREAD

**Issue by enimog** [LoneGazebo/Community-Patch-DLL#2468]
A bug that I know is in the DLL since forever, but I don't have enough knowledge to fix it myself.

Bug Report Template

Mod Version (i.e Date - (4/23b)):
09/02 hotfixhotfix

1. Mod List (if using standard CPP set, leave blank):
 - CPP/EUI standard

- RED Modpack

- Personal custom build of the following mods (mainly bugfixes / compatibility patch, a few additions, should not impact in any way the noticed issue, can provide sources if needed): 

 - Sukitract's Event and Decisions

 - JFD's cultural diversity

 - Wes's Civ 4 Leader Trait

 - ViceVirtuoso's Wish for the World

 - ViceVirtuoso's Hyperdimension Neptunia (All civilizations)

2. Type of error (i.e. crash, interface bug, AI quirk): 
Integer overflow inside the DLL (probably vanilla bug)

3. Steps to reproduce:

- Create a policy with a modifier of -25% policy cost

- Give it to yourself at game start at normal speed

- Normal behavior would be that the policy cost drop from 25 to 18.75 (I think). What happens is that the player get 2,147,483,647 culture instead.

4. Additional information:
This doesn't happens after when the player has a certain amount of accumulated culture (About 2 policies).

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
not really applicable in this case
2. Minidump file (located in your Civ5.exe directory)
n/a
3. Screenshots (if needed)
n/a

**Comment by LoneGazebo** [comment]
Not sure what you are describing. Elaborate?

**Comment by enimog** [comment]
Let's say I start a game (any civilization, any game speed, at ancient age). A mod in some way gives me a policy or a building that has the Property PolicyCostModifier set to -25 (For Buildings or Policy, it's the same column name in their respective table, and both cause the issue). What will happens is that the (global) culture value will overflow. So I'll be able to have all policies in the game enabled and more in one go. It's like having infinite culture. I hope this make it clearer for you.

(This can be reproduced by you by using unmodified Event & Decision and ViceVirtuoso's Nepgear civilization and finding an ancient ruin to trigger his bloody sword event that give a -25% policy cost reduction. You'll get this bug. Or create a building or a policy with this effect and give it to yourself)

**Comment by LoneGazebo** [comment]
You have to have zero culture? Or zero policies?

**Comment by enimog** [comment]
I'm not exactly sure if it is related to total policies or total culture. But it is not necessary to have exactly zero of both. What I found by trial and error is that after getting 2 policies at normal speed it doesn't overflow. After getting 1 policy it still overflow.

**Comment by LoneGazebo** [comment]
@Iamblichos or @ilteroi,

I've looked at this and can't find the culprit. 

Also, we need to look at the backlog of Putmalk's issues. I think he has gone forever. 👻

**Comment by Iamblichos** [comment]
I don't trust any of the stuff he has in those mods, too hard to track down if they are doing something wonky in LUA. I'll just make a dummy policy in an Honor open using this entry and see what happens.

**Comment by Iamblichos** [comment]
Okay so I just set PolicyCostModifier on the Honor Opener and then my second policy should be at count 25. It's now count 20. So I'm not sure what's going on here, unless you are adding that before you have any culture at all. Next I'll try making the Palace having that entry.

**Comment by Iamblichos** [comment]
![20160920164435_1](https://cloud.githubusercontent.com/assets/14372214/18689999/93328434-7f51-11e6-9572-7d7ceec18e76.jpg)

Here's it is with the Palace set. Everything looks like it's working right to me.

**Comment by LoneGazebo** [comment]
Alright, so it is one of his mods. As such, I'll close.
