### ISSUE TITLE
Swaptimize button doesn't swap.

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2469]
Right now I have enough works to fill the Oxford, but all it does is placing the works on the slots, when there are foreign works available for swapping.

**Comment by LoneGazebo** [comment]
It is an imperfect algorithm because of how slot patterns were designed by firaxis. I'll look at it again, but it is not 100% perfect.

**Comment by Radost** [comment]
I recall it was swapping fine back when first introduced. One of the updates broke something.

**Comment by LoneGazebo** [comment]
I haven't touched it since I released it.

G
