### ISSUE TITLE
Text Rendering Might and Imperialism Issue

### ISSUE THREAD

**Issue by tiberius58** [LoneGazebo/Community-Patch-DLL#247]
Whenever I mouse over the Might and Imperialism policy trees I am unable to view the new bonuses that were put in with the Patch. I can see them on every other policy tree. I'm not sure if there is anything I can do; I use Exploration Continued Expanded but have disabled the policy changes. Thanks

**Comment by LoneGazebo** [comment]
You deleted your cache, yes?
G
