### ISSUE TITLE
Great Prophet spam after conquering a Holy City

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2470]
I didn't have a religion, but after capturing a Holy City I've gotten 4 Great Prophets after one another. IMO the cost in this case should be raised as if GPs were spent on getting the religion to the full effect.

**Comment by LoneGazebo** [comment]
Prophet value is stored locally (i.e. player side), not religion-side, so there's no easy way to reorganize that data. I don't see it as a problem, truth be told, as otherwise a player might not understand why their prophet spawn time was suddenly doubled/tripled.

**Comment by Radost** [comment]
It won't be "sudden" because they can spawn none without religion.

**Comment by LoneGazebo** [comment]
Unless not all religions have been founded.

**Comment by pandasnail** [comment]
Situation Strigvir is talking about specifically precludes the possibility of founding a religion. If you are one of the first six to get to 1500 faith, you get a religion. (Not even sure if its technically possible to create a holy site with your first GP, but I'm sure no one does) But if six people beat you to 1500 faith, your faith then climbs and climbs and get can literally to 10000 if you wait long enough to take a Holy City.. Which leads to five Great Prophets spawning in five turns. Not sure why Strig thinks this is a bug tbh, even if it is a little weird. (I explain it immersively as a culture invigorated by its new faith I guess.) But I thought I would explain it out a little more for him nonetheless.

(numbers for marathon and huge maps, so really 500 faith and 3500 faith respectively I guess)

**Comment by pandasnail** [comment]
Situation Strigvir is talking about specifically precludes the possibility of founding a religion. If you are one of the first six to get to 1500 faith, you get a religion. (Not even sure if its technically possible to create a holy site with your first GP, but I'm sure no one does) But if six people beat you to 1500 faith, your faith then climbs and climbs and get can literally to 10000 if you wait long enough to take a Holy City.. Which leads to five Great Prophets spawning in five turns. Not sure why Strig thinks this is a bug tbh, even if it is a little weird. (I explain it immersively as a culture invigorated by its new faith I guess.) But I thought I would explain it out a little more for him nonetheless.

(numbers for marathon and huge maps, so really 500 faith and 3500 faith respectively I guess)

**Comment by pandasnail** [comment]
Ironically, almost immediately after loading my current game, I saw an example, might as well post. Two Hunnic GPs in one screenshot, and they enhanced the Swedish religion too.

![gp](https://cloud.githubusercontent.com/assets/16260521/18293518/400b3580-7461-11e6-82d1-e214e802b29a.jpg)
