### ISSUE TITLE
Recent Events tab sorts by city

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2471]
When it should sort from the latest to oldest.

**Comment by LoneGazebo** [comment]
That's intentional.

**Comment by Radost** [comment]
So it being useless is intentional?
It doesn't even sort alphabetically.

**Comment by LoneGazebo** [comment]
Intentionally useless, yep. You sure know how to woo a lady.

@jfdaly or anyone else (i.e. not me), if you've got spare time and don't mind ingratitude, mind taking a look at the event overview lua? Its been on my todo list for some time. Could be a useful screen for other event-related data as well if we ever get around to it.

**Comment by JFDaly** [comment]
I'll keep it in mind as something to look into, but I've got my hands full atm - just got back to uni from break and trying to get as much of my mods done before Civ VI.
