### ISSUE TITLE
CTD in VS

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2472]
Been getting some reports about CTDs with my recently released Events Compendium. Thought I'd test it out in Visual Studio, and indeed I get some crashes. Received this one in two separate games. This was using the latest repo of the CP and the latest version of my EC (the first time I tested and got this CTD I only used the latest version of my Cities in Development).

Here is a screenshot of VS.
![screen](http://i.imgur.com/gvZtAfE.png)

But let me know what more info you need.
EDIT: Just noticed the arrow pointing at the breakpoint - heh. Know what this is about? Could this be a lua issue? I'm supposing this is some problem with getting the owner of a city.

**Comment by LoneGazebo** [comment]
What's the call stack? On the bottom right hit the call stack button and trace it back to where the bad 'getplotcity' function is grabbed.

**Comment by LoneGazebo** [comment]
Essentially it looks like I made a bad getplotcity assumption somewhere.

**Comment by JFDaly** [comment]
Callstack:

![callstack[(http://i.imgur.com/K9EwRSW.png)

**Comment by JFDaly** [comment]
The second line with ExecuteGeneralMoves() points to here:
![h](http://i.imgur.com/Lew1jUm.png)

**Comment by Iamblichos** [comment]
This might be mine. I made some changes to Plotgeneralmos and execute general moves recently.

**Comment by JFDaly** [comment]
Any more info you need?

**Comment by LoneGazebo** [comment]
Mm. Yeah I haven't touched that. I'll add a plot check there for the next version. Once up I'll link and you can link to CTD users. Will be save game compatible.

**Comment by Iamblichos** [comment]
Never mind it was PlotEngineerMoves and ExecuteEngineerMoves I changed, but those only did unitai checks and combat unit checks.
