### ISSUE TITLE
4 Separate bugs same game.

### ISSUE THREAD

**Issue by Robertm1994** [LoneGazebo/Community-Patch-DLL#2474]
Bug Report Template

Mod Version (i.e Date - (4/23b)):

I think the 12th of august 2016 is the version i have atm? I was going to update to the newest version as soon as i finish the game im playing atm but the release notes say that saves aren't compatible.

1. Mod List (if using standard CPP set, leave blank):

Just the full vox populi mod pack

2. Type of error (i.e. crash, interface bug, AI quirk): 

1) Tile yields wont show half the time. in certain areas of the map. see below screenshot demonstrating this.

http://i.imgur.com/aL6YcCE.jpg

Notice how it sort of just cuts a line across the map and just says NOPE you aren't allowed to see this info.

Strangely enough, this can be worked around by moving the map slightly

 http://i.imgur.com/tiYjnds.jpg

This gets really annoying when trying to change how citizens are assigned in the city view however

http://i.imgur.com/5ZjURVr.jpg
http://i.imgur.com/ltDBGKl.jpg

2) When razing a city, the game would crash on the final turn of the razing. I have a sneaking suspicion this was due to the natural wonder being within its borders. I also had the religious tenet that gave wonders culture and faith

http://i.imgur.com/5oYHmS9.jpg

I originally wanted to raze both konya and erdine and place a single city between their locations so i wouldnt be losing so many tiles to germany (this was still very early into the game so i wasnt losing much by doing this. The ottomans were really slow at expanding for some reason)

3) AI being able to produce farms in tundra.

http://i.imgur.com/0qbv8GA.jpg

Maybe its because its near a river? idk. either way i dont see any mention of it on the civilopedia

4) Terrace farms not getting adjacency bonus's for being next to each other. On the tooltip during load-in if you hover the terrace farms it says they get extra food for being near other terrace farms. You can clearly see here that you don't.

http://i.imgur.com/F3jRPWC.jpg

Also, i'm not sure if they are supposed to or not, but they aren't giving me the cathedral gold bonus here.

3. Steps to reproduce:

I feel like ive covered everything honestly

4. Additional information:

Sadly i didn't have logging enabled for these. if you want, i can play a few turns tomorrow with it enabled. I have attached the save game though
[Inca op.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/454174/Inca.op.zip)

**Comment by LoneGazebo** [comment]
Most of these things have been fixed. The UI issues are either a mod conflict, bad install, or a graphics card issue.

**Comment by Robertm1994** [comment]
Hmmm. Shouldn't be a graphics card issue as the card I have is only a few months old. Was probably just a bad install.

If I use the patcher does that auto download the newest version? I'm tempted to just abandon this game and try again if the terrace farm bug is fixed but I also kinda wanna finish the game I'm playing

**Comment by Iamblichos** [comment]
No you download the new version to get it. These issues are fixed. I appreciate the effort in posting though.

**Comment by Robertm1994** [comment]
Alright I'll just abandon my current game.  I kinda wanna try a domination game where every civ has a unique tile improvement anyway.
