### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by Mlac99** [LoneGazebo/Community-Patch-DLL#2475]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
9-2

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
ctd

3. Steps to reproduce:
Ctd is during AI turn, I can uplaod savegame if it helps.

4. Additional information:
I'm also tried patch from issue #2463 , but widouth success.

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/455533/CvMiniDump.zip)

**Comment by LoneGazebo** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7849458/18259529/d26b0a22-73b2-11e6-9f9d-9bd1b439f415.png)

@ilteroi can you make heads or tails of this? Why would m_YieldWeights throw a bad pointer here?

**Comment by LoneGazebo** [comment]
@Mlac99, what's your mod list? If you have logging enabled, mind posting your database.log?

**Comment by Mlac99** [comment]
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/457277/Database.zip)

Nothing spevial, just Vox Populi with EUI.

**Comment by LoneGazebo** [comment]
You are missing DLC. Leader packs, etc.

**Comment by Mlac99** [comment]
No?

**Comment by Mlac99** [comment]
![20160906191921_1](https://cloud.githubusercontent.com/assets/22012391/18283825/80334a20-7467-11e6-9f22-613b1ad68abe.jpg)

**Comment by LoneGazebo** [comment]
Look at your database. Polynesia, inca both missing.

**Comment by Mlac99** [comment]
Yes, I'm wasn't aware that this two leaders are missing. Now I'm buy this two on Steam, install it, clear cache, and load savegame. But there is logs in database again, and civ chrases. Do I miss something ?
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/457481/Database.zip)

**Comment by LoneGazebo** [comment]
You can't load a savegame after adding a bunch of new leaders like that, sorry. Gotta start anew.

**Comment by Mlac99** [comment]
OK, thanks a lot.
