### ISSUE TITLE
endgame crash

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2476]
this seems to happen almost every time around turn 370 ... now i don't know if that is maybe due to autoplay, i rarely play so far in one go manually ... does that happen to anyone else?

![image](https://cloud.githubusercontent.com/assets/1358966/18256549/04b451e2-73b7-11e6-8d88-cce9c3e87b3d.png)

callstack seems to indicate that the game is being deallocated, but that doesn't really make sense?

**Comment by ilteroi** [comment]
oh yeah, forgot to add, it's not reproducable, after loading the last autosave everything proceeds fine

**Comment by Iamblichos** [comment]
Info Addict related?

**Comment by LoneGazebo** [comment]
I don't get that, no. I run autoplays to 500 all the time w/ no crash.

**Comment by ilteroi** [comment]
no infoaddict for me in its current state :)
