### ISSUE TITLE
Restart CTD

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#2477]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
9.2hotfixed

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): 
CTD when regenerating the map on turn 0

3. Steps to reproduce:
Try to restart on turn 0.

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by ilteroi** [comment]
cannot reproduce. special map script maybe?

**Comment by AnastaseAlex** [comment]
No, no other mods.
I moved my units before reloading both times this happened. Could that be the issue?

**Comment by Edaka** [comment]
Not using any additional mods? Your CvMiniDump.dmp would be helpful.

**Comment by AnastaseAlex** [comment]
I have since played another game, and am in the middle of my second one. I
will try to start a new one and reproduce.
Oh! wait! I also have (7) Events for CBP which I forgot to mention!
