### ISSUE TITLE
Benevolence (Japanese Dojotion) Bug (?)

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2478]
Bug Report Template

Mod Version (Latest, 2nd September)

1. Mod List (if using standard CPP set, leave blank):

2. Type of error (i.e. crash, interface bug, AI quirk): minor, description inaccurate, unforeseen interaction 

3. Steps to reproduce:
Get a guy with Benevolence.
Pillage a tile while near some hurt unit.
You heal, but the unit near doesn't get +5HP.
You don't get 5 HP more too despite being healed by the act of Pillaging

Or is it only supposed to work with March/regular fortify heal?

4. Additional information:

All toasters toast toast
Where there's smoke, there's fire
All smokers smoke smoke
Where there's toast, there's toasters

**Comment by LoneGazebo** [comment]
What's the benevolence description?

**Comment by LoneGazebo** [comment]
The healing one? If so, then yeah, pillaging does not give a boosted value.

**Comment by Enrico-Swagolo** [comment]
Aye that's the one that gives +5HP for you and all the friend neighbours whenever you heal.

**Comment by LoneGazebo** [comment]
yeah, that's only for real heals.
