### ISSUE TITLE
Interface bug No-EUI version

### ISSUE THREAD

**Issue by Damthe** [LoneGazebo/Community-Patch-DLL#2479]
Bug Report Template

Mod Version 9-2

1. Mod List; Community Patch + Community Balance Overhaul + InfoAddict and also in Vox Populi(No-EUI)

2. Type of error; **Interface Bug** Queeed buildings do not grey out in building list.

![cbo issue](https://cloud.githubusercontent.com/assets/21695940/18292074/11b4c8ee-7494-11e6-887b-380a0d8e8c57.jpg)

**Comment by LoneGazebo** [comment]
Vanilla is that way IIRC.

**Comment by Damthe** [comment]
@LoneGazebo Nope

![20160907013829_1](https://cloud.githubusercontent.com/assets/21695940/18293539/0502019a-749c-11e6-9ef1-45577c24c405.jpg)

**Comment by LoneGazebo** [comment]
I unno, I don't even mess with that in the lua file.
