### ISSUE TITLE
food icons replace tile yield value on every tile

### ISSUE THREAD

**Issue by banderolax** [LoneGazebo/Community-Patch-DLL#248]
I know that this already has a solution, but i do not have this \ingame folder in my community patch folder. Are there any other ways to deal with this bug? I cleared my game cache but it did not work.

**Comment by mmermerkaya** [comment]
A solution I found is to delete the YieldIconManager.lua and YieldIconManager.xml files from ~\Documents\My Games\Sid Meier's Civilization 5\MODS\Community Patch (5-2)\LUA directory.

That said, I don't know what exactly these files are there for, or if I'm breaking some other functionality by deleting these two files.

**Comment by LoneGazebo** [comment]
Please read install instructions. You are required to delete the lua folder in the CP and CBP if using the compatibility mods. 
G

**Comment by banderolax** [comment]
Sorry for not paying attention. Now it works! Thanks.
