### ISSUE TITLE
Not enough Paper notification

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2480]
Bug Report Template

Mod Version (i.e Date - (4/23b)): 9/2

1. Mod List (if using standard CPP set, leave blank):
Full VP
JFD Cultural Diversity
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Celtic City Names, Iroquoian City Names, Randomize City Names
My own thing that does various things SQL type stuff
Really Advanced Setup
Improved City View, EUI Version

2. Type of error (i.e. crash, interface bug, AI quirk): 
Not a major thing, but there's now an event (yours, Enginseer's or Hokath's I'm not sure) that gives an Emissary pre-paper at least possibly. So for the first time I've seen the not enough paper notification. And it talks about 'units fighting less effectively.' As far as I can tell, there is no consequence to it.

3. Steps to reproduce:

4. Additional information:

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)
![paper](https://cloud.githubusercontent.com/assets/16260521/18293346/427af072-7460-11e6-96b3-8df48c2ed663.jpg)

**Comment by LoneGazebo** [comment]
There's not, but it is a strategic resource so this can happen. <Shrug>

**Comment by pandasnail** [comment]
You're saying if someone made a modmod with a Paper military unit they would less effectively? Interesting. Okay.

**Comment by LoneGazebo** [comment]
haha technically yes.
