### ISSUE TITLE
AI lives even after getting killed, without cities

### ISSUE THREAD

**Issue by kenneth1221** [LoneGazebo/Community-Patch-DLL#2481]
Bug Report Template

Mod Version (i.e Date - (4/23b)):
9/2

1. Mod List (if using standard CPP set, leave blank):
Ynaemp v24
CL Inuit
CL Kimberley
Enginseer's Civic & Reform, E&D for Vox, Community Events
InfoAddict
Historical Religions
CulDiv Core

2. Type of error (i.e. crash, interface bug, AI quirk): 
AI appears to continue living after being "killed", even if it has no cities remaining. I defeated China as Mongolia, and some number of turns later they denounced me. There was one Chinese worker remaining. Complete kills was off.

3. Steps to reproduce:
I do not know for sure. However, if I had to guess, it was likely because some civ liberated a formerly Chinese worker from a barbarian camp. Is the game properly checking that the original civ was alive when this option is presented?

4. Additional information:
Unfortunately, I don't have a save or logs.

**Comment by TechpriestEnginseer** [comment]
I can't reproduce this.
