### ISSUE TITLE
CTD in 09-02 version (CP only)

### ISSUE THREAD

**Issue by shaglio** [LoneGazebo/Community-Patch-DLL#2482]
Bug Report Template

Mod Version (i.e Date - (4/23b)):   CP 09/02

1. Mod List (if using standard CPP set, leave blank):

CP
Civ IV Diplo Features
Dynamic Cultural Overview
Global - City Forest Bonus
Global - Passable Forts
Global - Pro-rata Building Purchase
Global - Truly Free Great People
JFD's Cultural Diversity
MC's Greek Split
MC's India Split
Naval Healing
Sukritact's Events & Decisions
Sukritact's Modular City Info Stack
UI - City Happiness
UI - Destination
EUI

Note: This mod cocktail worked perfectly fine though the 08/18 version of CP.

2. Type of error (i.e. crash, interface bug, AI quirk): CTD in 4 of 4 games started

3. Steps to reproduce:  see above

4. Additional information:  I looked all over for a MiniDump file and can't find one anywhere.  I even used Windows search :(

---------------------------
Supporting information:

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed

[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/458114/Database.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/458115/Lua.zip)

2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by shaglio** [comment]
I looked in "Steam/Steamapps/Common/Sid Meier's Civilization V" for a MiniDump file but I couldn't find anything.

**Comment by LoneGazebo** [comment]
If you can't find a minidump, its a lua crash (and not the CP's fault).

**Comment by shaglio** [comment]
Everything was working perfectly fine with the 08/18 version.  I upgraded to the 09/02 version and now every game I start gives me a CTD, which would suggest that there's something in the 09/02 version that is causing it.  When I reloaded the saves, it would continue to crash at the same point.

Was there anything notable in my logs?
Is the MiniDump similar to the logs, where I need to "enable logging" before anything shows up?
Is there anything else I can do to help pinpoint the issue?

**Comment by Edaka** [comment]
Just so you know, the exact file name is CvMiniDump.dmp. Also, even though all of your activated mods used to work fine together, disable them (except CP) and then try to reproduce the crash. Post your minidump here if you succeed.

**Comment by Edaka** [comment]
And no, you shouldn't need to do anything to enable minidump creation, it should happen automatically.

**Comment by LoneGazebo** [comment]
If the CP is crashing, that's something. If it is another mod crashing, I can't really help you.

**Comment by shaglio** [comment]
Found it!

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/460284/CvMiniDump.zip)
