### ISSUE TITLE
Citizens not being assigned to buildings--still present

### ISSUE THREAD

**Issue by Guynemer** [LoneGazebo/Community-Patch-DLL#2483]
Bug Report Template

Mod Version (i.e Date - (4/23b)):  Sept. 2nd version

1. Mod List (if using standard CPP set, leave blank):
Quick Turns
InfoAddict

2. Type of error (i.e. crash, interface bug, AI quirk): 
Laborers are not being assigned to empty specialist slots, despite abundant happiness.  In the attached save game, note the happiness is over +20, but citizens are assigned as laborers in both Rhodes and Eritrea despite empty specialist slots in both cities,

[CitizenAssignmentBug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/458259/CitizenAssignmentBug.zip)

Please note that you can attach .zip files to Issues by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files: Database.log and Lua.log needed
2. Minidump file (located in your Civ5.exe directory)
3. Screenshots (if needed)

**Comment by Knecht-Ruprecht** [comment]
Same here!
Mods used:
VP 8-18 with EUI
Faster Aircraft Animations
Improved Oil
R.E.D.

All cities set to "Default Focus" and tile/citizen/specialist management automated everywhere.

Only GreatPerson-generators (writers/artists/musicians/civil servants) seem to be assigned in most cities.
![20160909183319_1](https://cloud.githubusercontent.com/assets/21977081/18394995/c355f846-76bc-11e6-8582-a68497a55439.jpg)
![20160909183445_1](https://cloud.githubusercontent.com/assets/21977081/18394994/c34ea5a0-76bc-11e6-82fb-fb3048207697.jpg)

Sometimes, engineers are also assigned (note that the city here has no idle citizens left).
![20160909183430_1](https://cloud.githubusercontent.com/assets/21977081/18395144/849e668c-76bd-11e6-86d8-51274fc1417b.jpg)

Here is the according save:
[Bismarck_0539 AD-1944-July.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/464418/Bismarck_0539.AD-1944-July.zip)
