### ISSUE TITLE
Translation: Unit Class

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#2486]
Although I have translated TXT_KEY_NEED_UNITCLASS_TYPE, some of the {1_Desc} names appear in English.

cf.
(1) Community Patch\Modules\Events\Text\en_US\EventCore_en_US.xml
```
		<Row Tag="TXT_KEY_NEED_UNITCLASS_TYPE">
			<Text>[NEWLINE] [ICON_BULLET] Must have at least one {1_Desc} Unit</Text>
		</Row>
```
![unit class](https://cloud.githubusercontent.com/assets/11933188/18352762/a0c231ac-761a-11e6-9782-19a49837393e.png)

P.S.
When I translated JFD's Mercenaries mod, a similar issue happened.
According to him, Firaxis hardcoded the descriptions of the unit classes.

**Comment by LoneGazebo** [comment]
This is true. There's a set of hardcoded values like that in the unitclass definitions.

**Comment by 8h42** [comment]
I have just found these codes in JFD's Mercenaries mod.

```
UPDATE UnitClasses
SET DefaultUnit = 'UNIT_GALLEY'
WHERE Type = 'UNITCLASS_GALLEY';

UPDATE UnitClasses
SET Description = 'TXT_KEY_UNIT_ANTI_AIRCRAFT_GUN'
WHERE Type = 'UNITCLASS_ANTI_AIRCRAFT_GUN';

UPDATE UnitClasses
SET Description = 'TXT_KEY_UNIT_AT_GUN'
WHERE Type = 'UNITCLASS_ANTI_TANK_GUN';

UPDATE UnitClasses
SET Description = 'TXT_KEY_UNIT_ATOMIC_BOMB'
WHERE Type = 'UNITCLASS_ATOMIC_BOMB';

UPDATE UnitClasses
SET Description = 'TXT_KEY_UNIT_CHARIOT_ARCHER'
WHERE Type = 'UNITCLASS_CHARIOT_ARCHER';

UPDATE UnitClasses
SET Description = 'TXT_KEY_UNIT_HELICOPTER_GUNSHIP'
WHERE Type = 'UNITCLASS_HELICOPTER_GUNSHIP';

UPDATE UnitClasses
SET Description = 'TXT_KEY_UNIT_HORSEMAN'
WHERE Type = 'UNITCLASS_HORSEMAN';

UPDATE UnitClasses
SET Description = 'TXT_KEY_UNIT_LANCER'
WHERE Type = 'UNITCLASS_LANCER';

UPDATE UnitClasses
SET Description = 'TXT_KEY_UNIT_LONGSWORDSMAN'
WHERE Type = 'UNITCLASS_LONGSWORDSMAN';

UPDATE UnitClasses
SET Description = 'TXT_KEY_UNIT_ROCKET_ARTILLERY'
WHERE Type = 'UNITCLASS_ROCKET_ARTILLERY';

UPDATE UnitClasses
SET Description = 'TXT_KEY_CIV5_KOREA_TURTLESHIP_HEADING'
WHERE Type = 'UNITCLASS_KOREAN_TURTLE_SHIP';

UPDATE UnitClasses
SET Description = 'TXT_KEY_UNIT_MONGOL_KESHIK'
WHERE Type = 'UNITCLASS_MOUNTED_BOWMAN';
```

It seems to work well.
Would you mind incorporating it?
![unit class2](https://cloud.githubusercontent.com/assets/11933188/18364197/7cfeb37a-7648-11e6-9ca6-0642f2caa204.png)

**Comment by LoneGazebo** [comment]
Make a pull request for me?

**Comment by 8h42** [comment]
I'm not familiar with GitHub, unfortunately.
Can I leave it to you?

https://www.dropbox.com/s/qp881051rrw1jc9/UnitClasses.sql?dl=0

**Comment by 8h42** [comment]
Now I can produce Galleys.
I should have deleted these lines.

```
UPDATE UnitClasses
SET DefaultUnit = 'UNIT_GALLEY'
WHERE Type = 'UNITCLASS_GALLEY';
```

There might be other problems.

https://www.dropbox.com/s/ktdnymu27ojwncp/UnitClasses.sql?dl=0

**Comment by LoneGazebo** [comment]
Did you test this?

**Comment by 8h42** [comment]
Yes, I did.
I didn't notice any problems at least in my games.

**Comment by 8h42** [comment]
OK, I'll do it by myself, thanks!
