### ISSUE TITLE
Capturing Venice Bug

### ISSUE THREAD

**Issue by LyraTheStar** [LoneGazebo/Community-Patch-DLL#2488]
_1. Mod Version (i.e Date - 4/23):_
8-12

_2. Mod List (if using Vox Populi only, leave blank):_
Community Patch (v.88)
Community Balance Overhaul (v.13)
City-State Diplomacy Mod (v.27)
C4DF - CBP (v.11)
More Luxuries - CBO Edition (v. 155)
Community Balance Overhaul - Compatibility Files (EUI) (v.1)

_3. Error Description:_ 
Game Crashes the turn after I take Venice, reloaded autosave, had a whole different war, took a bunch of cities, nothing. Took Venice crashed the next turn again. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[Logs and Save and Cv MiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/462643/Logs.and.Save.and.Cv.MiniDump.zip)

3. Screenshots (optional):

**Comment by Knecht-Ruprecht** [comment]
Was able to reproduce this with 8-18 (own game, of course, not the 8-12 save from this issue).

**Comment by LoneGazebo** [comment]
Reproduce capturing venice?

**Comment by Knecht-Ruprecht** [comment]
Yes. Captured Venice, next turn it crashed while I was moving my units around. On a second try, I waited a few turns to see if this was a coincidence, then captured Venice, same as above happened the turn after that. The unit types last moved before the crash where also different (one was some military land unit, the other one a worker, both were just moved from one tile to another).

**Comment by Knecht-Ruprecht** [comment]
What I noticed so far: The game seems to crash sometimes after capturing any city (either during opponents turn or during unit movement in my next player's turn). This does not happen all the time (maybe 10 to 20%) and reloading helps (sometimes, I have to reload twice). After the next turn after a city was captured is completed, there seems to be no more danger of CTD.
