### ISSUE TITLE
naval blockades  'sapped' penalty 

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#249]
It does not work. Or combat preview does not show this penalty.

**Comment by LoneGazebo** [comment]
It works, but the preview is acting odd. I hate lua. 

G

**Comment by qqqbbb** [comment]
I tested version 5-3 and it looks like it's not working. Damage blockaded city receives from melee ships is the same as it was in version 4-22.

**Comment by LoneGazebo** [comment]
Hmm…I’ll take a look. The code input was fairly simple, so I’m not sure why it isn’t working. Anyways, it is a minor change, so shouldn’t be a big deal for now.
G

**Comment by LoneGazebo** [comment]
got it - forgot to update old function to use new simplified function (in original code, blockades can only happen in cities with a harbor - i've made a custom function that ignores that and simply looks to see if you have more naval units near the city than the other player).

**Comment by qqqbbb** [comment]
Does your function consider these options from Howard's dll?
GLOBAL_ADJACENT_BLOCKADES
GLOBAL_ALLIES_BLOCK_BLOCKADES
GLOBAL_SHORT_EMBARKED_BLOCKADES
