### ISSUE TITLE
Great General AI problems

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2490]
_1. Mod Version current, 2 september

_2. Mod List VP

_3. Error Description:_ AI.

_4. Steps to reproduce (optional):

Fight a war against an AI with GGs
They often move their GG in the reach of your troops despite having the possibility to cover it by some units, or just have it remain in the city.
it won't be visible if they have an absolute unit spam you can't handle because, well, in that case almost all the fighting tiles are covered with units anyway

Alternatively, the AI will place its GGs stupidly on their front troops, as if they didn't know the GG bonus affects all in surrounding tiles too. They can safely put him a bit in the back and still affect everyone, instead of putting him on a front unit, especially when said front unit can be easily shot at by my troops and then destroyed with my melee.

The fight AI itself is great, esp compared to vanilla, but it is not very good at managing its GGs.

**Comment by ilteroi** [comment]
if you have a savegame from just before the AI makes a stupid move, that would be great

**Comment by Enrico-Swagolo** [comment]
I don't (I have so many saves in my directory I wouldn't be able to find anything even if I had one too, I need to do some purging), but don't worry - I am always a warmongering menace to the world, I will just start another game, bully some AI and get it done for you.

**Comment by Enrico-Swagolo** [comment]
I've done it! I've got three saves with peculiar AI movements. Two are related to the subject.

ArrogantArcher - Swedish Archer just keeps moving around my Hoplites (who can oneshot him) trying to reach the city.  I've let him live because even if he shoots, he just tickles - I've got 3 alliances, soon to be 4. Unrelated, but IIRC from Arrogant Archer ExampleWorstAfter was made... Or it was made after EWA on my first/second retry, more about which below. I forgot.

Seems a bit related to GG movement, because it seems as if the AI attempts to move their GGs to support X unit somewhere, but it just lets the regular pathfinding do the job, even if it can see my troops stationed there.

ExampleWorstAfter - this is the primary thing I've made this thread for. Unfortunately, I didn't make a save every single turn this game, so I do not have the save before this, but you can see that the Great General just moved to give my Hoplites a hug, giving me an absolutely free Acropolis Culture bump for my empire. What a nice guy Gustavus is. SWEDEN YES

CHECKMATE - after ExampleWorstAfter, I loaded my autosave of the 2X1 turn and tried thrice to get the same situation. Once, the Great General did come on Spears, but this time I've neglected to do anything but click Next Turn and, as such when he appeared (on the EXACT SAME HILL SPOT as in EWA), he's got Spearmen there because, well, I wasn't killing or stopping anything from moving with my units which I've placed a bit badly due to not really moving them. I would've killed them, but it wasn't particularly bad.
The second time, I tried too hard, killed all Gustavus' unit and the General didn't come.

CHECKMATE is the third try to recreate the situation (I quicksaved every turn by this point), this one contains a different issue, AI moving his GG to a guy who will definitely die. Look at my Hoplites (you can make the situation more hopeless by moving some Hoplites above). Click next turn. He moves his guy to a Spear that is in contact with a Hoplite (and if you move my Hoplites in the conquered city above, will be surrounded not by the visible two, but also by 3 + catapult next turn)
Yes, it is the slightest example of bad movement, but I tried twice to recreate the EWA situation with the AI just moving their GG to hug your troops and failed.

Unfortunately, Checkmate is a very soft example of this thing happening, but recreation, as I've made it above, failed after X tries.

I think that either the frequency of the AI doing this sort of thing increases as the AI is absolutely wrecked by me, or it is more visible because AI has less units to cover their tiles up. I think the latter is most likely, as I've seen AIs that were my equals in power moving their GG just badly, often on the front of their army when moving them one tile back - even unguarded - would make them invincible for at least a turn.

ArrogantArcher and EWA, to me, seem like examples of AI trying to support themselves on one front, but not thinking far ahead and just moving their units to die. This is what I've seen through many games.

[Contains3Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/464842/Contains3Saves.zip)


I can try to recreate this situation again if you wish, I think it's possible, after some tries, that I could make me get a perfect "turn-before-EWA"

**Comment by Enrico-Swagolo** [comment]
BTW I use Vox Populi (EUI version) city view expanded by Meister Maggi, but IIRC you can load it regardless without it.

Also, I've changed my .ini to reveal all bonus resources instantly, but I think it loads regardless too.

**Comment by ilteroi** [comment]
thank you for the detailed report, but unfortunately i cannot load your save because of the old database incompatibility (at least i suspect that's the reason).

btw you can change the autosave interval in the config. but right now it's no use anyway.

**Comment by Enrico-Swagolo** [comment]
What's old database incompatibility? Aren't all VP versions the same?

Maybe try to load the Improved City View (EUI v) by Meister Maggi on the Steam Workshop. It'll be used in future VP versions anyway (unless Gazebo changes his mind). That's what I'm using. IIRC it loaded fine without that but it's worth a try...

Also try to change 
VALUES ('COMMUNITY_CORE_BALANCE_RESOURCE_REVEAL', 1); in (2) community balance to 0, because this is what I'm using to reveal all bonus resources instantly. Should load without though...

Failing that, I will try to make a save with no ICV(EUI), but that'll take me some time and I won't do it unless this database incompatibility is so severe it means there's no point

**Comment by Enrico-Swagolo** [comment]
In the same game Ash did something similar as Gustavus. He moved his Spear to be in contact with my Catapults + Hoplites, and moved his GG a tile back - I destroyed the Spear with Catapult + Hoplite and then took the GG with another Hoplite.

I could make pics too, of the previous situations, in all the saves.  Do you want pictures or would they not be useful?
