### ISSUE TITLE
Assorted promotion issues

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#2491]
_1. Mod Version (i.e Date - 4/23):_

8/18

_2. Mod List (if using Vox Populi only, leave blank):_
 -

_3. Error Description:_ 

Artillery: If you go down the promotion line that gives bonus vs cities, you get to pick sharpshooter (great bonus against wounded units) promotion after the third anti city promotion. This promotion should be atop of the promotion line against wounded units.

Ranged cavallery: They have the indirect fire promotion available, which is of no use for a range 1 unit. Even if they theoretically could pick up +1 range eventually, it should still be removed. It takes a lot of XP to get both, so it is more a trap for inexperienced players and not very fitting for the unit line anyway.

Air targeting: Seems to be missing an icon. If you can select it, it is represented by a random promotion or worker action icon (a different one each time)

_4. Steps to reproduce (optional):_

-

**Comment by Knecht-Ruprecht** [comment]
Adding to that: The Flak targeting promotion (+150% against air), at least with melee infantry, has the "remove road" icon.

**Comment by LoneGazebo** [comment]
re: promotion icon issues, please post lua log from when those appear. Enable logging if not enabled, reproduce, then post.

**Comment by pandasnail** [comment]
For number one, since Logistics is better than Range, Sniper should be better than Infiltrator imo. And giving back some of Barrage's bonus to the Accuracy line seems fine to me.

For number two, mounted archers are still regular UNITCOMBAT_ARCHER and I don't think can have their own unique promo line from foot archers.

**Comment by LoneGazebo** [comment]
@pandasnail is correct on both counts.
