### ISSUE TITLE
Hanging Gardens is not buildable?

### ISSUE THREAD

**Issue by StevenV205** [LoneGazebo/Community-Patch-DLL#2495]
_1. Mod Version (i.e Date - 4/23):_
**9-2**

_2. Mod List (if using Vox Populi only, leave blank):_
**Quick Turns**

_3. Error Description:_ 
**Hanging Gardens does not apper on the buildable wonder list, even so the requirements are met. Tradition is finished, Mathemetics is discovered and based on techtree nobody has built it yet.**

_4. Steps to reproduce (optional):_
**Load the save game**

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs fol
[Gandhi_0135 AD-0500.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/464581/Gandhi_0135.AD-0500.zip)
[Logs_0909.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/464580/Logs_0909.zip)

der, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

3. Screenshots (optional):

**Comment by StevenV205** [comment]
Hi Gazebo,

First I would like to thank you for your time and effort to have a look on my issue.
Could you please specify what do youmean by cannot reproduce
- the attached save file did not worked
- you was able to build hanging gardens
- other

Thanks in advance.

**Comment by LoneGazebo** [comment]
I got to a point where I could build the Hanging Gardens in a test game.

**Comment by StevenV205** [comment]
Well, OK. Thanks.
