### ISSUE TITLE
submarines error pop up

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2497]
_1. Mod Version (i.e Date - 4/23):_
9-2 

_2. Mod List (if using Vox Populi only, leave blank):_
everything included(CBP,CBO + rest)
faster aircraft animations
flag promotions(downloaded  via link from ,,how to instal'' thread in civfan.)

_3. Error Description:_ 
submarines missing picture for attack bonus promotion. its not CTD, i can click through those errors lvl it up and continue playing. Maybe outdated Flagpromotions duno.
![submarines1](https://cloud.githubusercontent.com/assets/21192402/18400393/fe2b0542-76d5-11e6-823a-ea07a73ead40.png)
![submarines2](https://cloud.githubusercontent.com/assets/21192402/18400406/0957c8f6-76d6-11e6-897f-c4535182f1be.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

3. Screenshots (optional):

**Comment by LoneGazebo** [comment]
guessing it is a flagpromotions issue.

**Comment by matlajs** [comment]
so should i write there?

**Comment by LoneGazebo** [comment]
Yes, I'm not the author of that mod.
