### ISSUE TITLE
EUI Top Panel: GA Tooltip

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#2498]
_1. Mod Version (i.e Date - 4/23):_
9/2

_2. Mod List (if using Vox Populi only, leave blank):_
VP (EUI set)
IGE

_3. Error Description:_ 
Just a request.
Would you change the arrangement of EUI GA Tooltip?
No-EUI style looks better.

---------------------------
![ga tooltip](https://cloud.githubusercontent.com/assets/11933188/18414607/dab6f562-780b-11e6-86da-f34cd0abfe55.jpg)

cf.
(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\TopPanel.lua
TXT_KEY_TP_GOLDEN_AGE_ADDITION_RELIGION
TXT_KEY_TP_GOLDEN_AGE_ADDITION_TRAIT
TXT_KEY_TP_GOLDEN_AGE_ADDITION_CITIES

**Comment by TechpriestEnginseer** [comment]
+1
