### ISSUE TITLE
GeneratePath Question

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#2499]
@ilteroi,

Quick question - shouldn't CvUnit::GeneratePath return true if piPathTurns = 0?

Point in question;

```
/// Use pathfinder to create a path
bool CvUnit::GeneratePath(const CvPlot* pToPlot, int iFlags, int iMaxTurns, int* piPathTurns)
{
	if(pToPlot == NULL)
		return false;

	bool bHavePath = false;
	if (HaveCachedPathTo(pToPlot,iFlags))
		//we can re-use the old path if we have one (and need one at all)
		bHavePath = at(pToPlot->getX(),pToPlot->getY()) || !m_kLastPath.empty();
	else
		bHavePath = ComputePath(pToPlot, iFlags, iMaxTurns);

	if(piPathTurns != NULL)
	{
		*piPathTurns = INT_MAX;

		if(!m_kLastPath.empty())
		{
			*piPathTurns = m_kLastPath.back().m_iTurns;

			//special: if we can reach the target in one turn with movement left, define this as zero turns
			if(*piPathTurns == 1)
			{
				if(m_kLastPath.back().m_iMoves > 0)
				{
					*piPathTurns = 0;
					return true;
				}
			}
		}
		else //we're already there!
		{
			*piPathTurns = 0;
			return true;
		}
	}

	return bHavePath;
}
```
The two return true statements are mine.

**Comment by LoneGazebo** [comment]
Fixing this and testing the AI seems to have flipped on a switch. A very good switch. I think this was one of those 'aha' bugs that seeped in. :)

G

**Comment by ilteroi** [comment]
bHavePath should be true in those cases anyway

**Comment by LoneGazebo** [comment]
It wasn't always doing that, oddly enough.

**Comment by LoneGazebo** [comment]
That was my assumption too, but adding those two true statements fixed the issue where units nearing a muster target would be removed from the army because of a lack of a path.

**Comment by ilteroi** [comment]
so you're saying the root cause is somewhere in ComputePath. which is possible though i've yet to reproduce it

**Comment by LoneGazebo** [comment]
Yeah. Good example here:

```
211, Babylon, AI_OPERATION_DIPLOMAT_DELEGATION, 36, PRE Gathering Forces, Army: 3340, Gather (37:18), variance (0.00:2.25), John Jay (Great Diplomat) 2744 at (36:17),Heavy Skirmisher 2648 at (36:20),
211, Babylon, AI_OPERATION_DIPLOMAT_DELEGATION, 36, Removing unit 2744 from army 3340 because no path to checkpoint
211, Babylon, AI_OPERATION_DIPLOMAT_DELEGATION, 36, Removing unit 2648 from army 3340 because no path to checkpoint
```

**Comment by LoneGazebo** [comment]
The plot that is 'unavailable' is right next to the unit, is clear of danger/other units, and is the same domain.

**Comment by LoneGazebo** [comment]
Mm, I think I see it. 

`bHavePath = at(pToPlot->getX(),pToPlot->getY()) || !m_kLastPath.empty();`

If m_kLastPath = 0 (i.e. less than one turn to get there), the cache returns false!

**Comment by LoneGazebo** [comment]
Pretty sure having using 'empty()' call for m_kLastPath on less-than-one-distance moves is a potential problem, though I've been wrong before. :)

**Comment by ilteroi** [comment]
nah. if the unit is at the plot, the second part of the expression isn't even evaluated. that's why the first part is there, in fact

**Comment by LoneGazebo** [comment]
But if the unit isn't at the plot, but is less than one turn from the plot, it returns false.

**Comment by LoneGazebo** [comment]
There's definitely something wrong with !m_kLastPath.empty() for moves, as valid moves for the AI break if the move does not consume the entirety of the unit's movement. This is also apparent in the ispartialmove cvunit function.

**Comment by ilteroi** [comment]
hmm. you might have a point in case the "approximate" flag is set

**Comment by LoneGazebo** [comment]
Yep - that's the problem I'm seeing.

**Comment by LoneGazebo** [comment]
Changing that one function above to m_kLastPath.size() >= 0 immediately stopped units from being removed from armies incorrectly (the diplomat in my above example started moving promptly). It might also explain why some units are having a hard time gathering/moving short distances as units, as some 'approx' checks are being invalidated.

**Comment by ilteroi** [comment]
ok - let me fix it the right way

**Comment by LoneGazebo** [comment]
haha of course, I was just noting that my temporary fix solved the issue on the 'front' end, thus there was something going on in the backend. :)

G

**Comment by ilteroi** [comment]
ok - should be better now. pushed. please remove your temporary fixes, else there will be merge conflicts i guess.

another desync test in 20 minutes?

**Comment by LoneGazebo** [comment]
I can test, sure.

**Comment by ilteroi** [comment]
ok, here goes

[Debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/466230/Debug.zip)

**Comment by LoneGazebo** [comment]
ah, i made one as well! We'll use yours.

**Comment by LoneGazebo** [comment]
Looked at code, compared things quite a bit. Outside of changes to RNG, I do not see anything that really stands out. I do, however, wonder if this is not a consequence of the RNG, but rather recent changes to the unit system. Namely, I noticed this in CvGame.cpp:

```
if(eEndTurnBlockingType == NO_ENDTURN_BLOCKING_TYPE)
		{
			if(!(activePlayer.hasBusyUnitOrCity()) && !(activePlayer.hasReadyUnit()))
			{
				// JAR  - Looks like popups are pretty much disabled at this point, this check will break
				// multiplayer games. Look at revision #27 to resurrect the old popup check code if/when
				// they are implemented again.
				if(!isGameMultiPlayer())
				{
					if((activePlayer.isOption(PLAYEROPTION_WAIT_END_TURN) && !isGameMultiPlayer()) || !(GC.GetEngineUserInterface()->isHasMovedUnit()) || isHotSeat() || isPbem())
					{
						GC.GetEngineUserInterface()->setCanEndTurn(true);
					}
				}
```

We can't test in-MP as it causes a desync, however I wonder if the DLL is hitting this point during an MP game?

**Comment by LoneGazebo** [comment]
Other big what-ifs:

Changing Game::GetGameTurn to a const value from a nonconst value - potential sync issue?
Removing the interface pathfinder?
