### ISSUE TITLE
Lake Victoria issue

### ISSUE THREAD

**Issue by Zoidbergesq** [LoneGazebo/Community-Patch-DLL#2500]
_1. Mod Version (i.e Date - 4/23):_
9-2

_2. Mod List (if using Vox Populi only, leave blank):_

_3. Error Description:_ 
Lake Victoria not being "see through" - you can't see land on the other side of it, from on flat ground or even elevated terrain.

I assume because natural wonders are, in code, "mountain" tiles that this means you can't see over/through them. I remember using a mod in the past, though - "Lake Victoria Fix" - that changed this by having the see-through value as 0 or 1. I think 1 meaning you can see over it from a hill, and 0 meaning you can see over it from flat ground. This doesn't seem to work now, though? Is there anyway around this (and for other natural wonders, too)?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

3. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
#156

**Comment by Zoidbergesq** [comment]
Ah ok. But I'm sure the mod I used had it so that you can't move over it (without embarking) but you can, nevertheless, see over it. Is there any reason this would no longer be the case, as #546 seems to suggest?

**Comment by Zoidbergesq** [comment]
Or, at least, that change (to allow shooting/seeing over) certainly doesn't seem to be implemented in version 9-2. Was it removed at a later point?

**Comment by Zoidbergesq** [comment]
In the code I think the Lake Victoria mod I used to use changes the "seethrough value" of the wonder tile specifically (rather than the impassibility), but when I've tried to use the mod with the community patch it seems to get over-ruled or for some other reason doesn't manifest itself in the game.

**Comment by Zoidbergesq** [comment]
@LoneGazebo

**Comment by Zoidbergesq** [comment]
@ilteroi

**Comment by Zoidbergesq** [comment]
@LoneGazebo

**Comment by LoneGazebo** [comment]
Mod conflict, sorry. Works on my end.

**Comment by Zoidbergesq** [comment]
This is without running any other mods though, that I can't see over/through it?
