### ISSUE TITLE
Natural Wonder line-of-sight

### ISSUE THREAD

**Issue by Zoidbergesq** [LoneGazebo/Community-Patch-DLL#2501]
_1. Mod Version (i.e Date - 4/23):_
9-2

_2. Mod List (if using Vox Populi only, leave blank):_
Just Vox Populi

_3. Error Description:_ 
Can't see over certain natural wonders, even from elevated ground.

A mod that used to work - for Lake Victoria, specifically - was described thus: _Reduces Lake Victoria's ''See Through'' value from 2 to 0, so that you can see across it like other bodies of water in game, instead of as if it were a mountain. Units can bombard across the lake as well._ 

Is this no longer possible? It seems like quite a simple fix, no?

**Comment by Iamblichos** [comment]
Well the issue is that Lake Victoria base plot is a Mountain. I'm not exactly sure why it is a Mountain really...we could just use ChangeCoreTileToFlatland = 1 in Natural_Wonder_Placement.

**Comment by Zoidbergesq** [comment]
Can it not remain a mountain but have its "see through" value changed (to 1 or 0)? I'm sure this use dto be quite easy to do. Has the hardcoding since changed?

**Comment by LoneGazebo** [comment]
All NWs are mountains in the DLL.

**Comment by Iamblichos** [comment]
@LoneGazebo Does this not override it? ChangeCoreTileToFlatland = 1 in Natural_Wonder_Placement

**Comment by LoneGazebo** [comment]
Not sure if it does, TBH. You could test. :)

**Comment by Iamblichos** [comment]
It seems to, that's why I was asking. I got a Pseudo Wonder with that flag set, and it seems to allow it.

**Comment by Iamblichos** [comment]
I'll do a test with Lake Victoria and see if that does it. I agree with the poster that you should be able to shoot over it.

**Comment by Iamblichos** [comment]
Ohi, kako, no beuno. Doesn't work....doesn't work with pseudo wonders either. About the only one that you can shoot over is the Reef, but that's a coast plot.

**Comment by Iamblichos** [comment]
....furthermore, I'm on the fence with fixing this deal too.

**Comment by LoneGazebo** [comment]
I think that natural wonders are hard-coded as mountains outside of DLL functionality. That's what I alluded to in the other post and this one.

G

**Comment by Zoidbergesq** [comment]
Sorry to keep going on about this!

Re: whether or not to fix, I suppose the main gripe is that an ordinary lake can be seen and shot over, and it doesn't look right when you have a unit adjacent to Victoria and the hex over the lake from you is not visible. 

This mod - https://steamcommunity.com/sharedfiles/filedetails/?id=160194319 - seemed to achieve it quite simply. I know next to nothing about coding, so I could be completely wrong here, but when I've looked through the code it seems to achieve the results by changing "see through" values (of the wonder, niot mountains in general). Does what you're saying about DLL functionality mean that this wouldn't work here?

Could someone have a look at how that mod achieved it, perhaps?

**Comment by Iamblichos** [comment]
Yeah I'll take a look but no promises here.

**Comment by Iamblichos** [comment]
Yeah even with SeeThrough set to 0 it still gives you no line of sight.

**Comment by Iamblichos** [comment]
It has to do with the core tile being a mountain.

**Comment by Zoidbergesq** [comment]
So strange because I remember it working before. Is the core tile being a mountain something that has changed, then? Because I definitely recall it being seeable through at some point in the past.

**Comment by Iamblichos** [comment]
Yeah I hear what you are saying, I remember in Vanilla you do what you suggested and it worked...I'll do a little digging.

**Comment by Zoidbergesq** [comment]
Any luck with the digging?

**Comment by Iamblichos** [comment]
Here's the code:

```
int CvPlot::seeThroughLevel(bool bIncludeShubbery) const
{
	int iLevel;

	CvAssertMsg(getTerrainType() != NO_TERRAIN, "TerrainType is not assigned a valid value");

	iLevel = (getTerrainType()!=NO_TERRAIN) ? GC.getTerrainInfo(getTerrainType())->getSeeThroughLevel() : 0;

	if(bIncludeShubbery && getFeatureType() != NO_FEATURE)
	{
		iLevel += GC.getFeatureInfo(getFeatureType())->getSeeThroughChange();
	}

	if(isMountain())
	{
		iLevel += GC.getMOUNTAIN_SEE_THROUGH_CHANGE();
	}

	if(isHills())
	{
		iLevel += GC.getHILLS_SEE_THROUGH_CHANGE();
	}

	if(isWater())
	{
		iLevel += GC.getSEAWATER_SEE_THROUGH_CHANGE();
	}

	return iLevel;
}
```

Now the seethrough gets defined for natural wonders by:

`iLevel += GC.getFeatureInfo(getFeatureType())->getSeeThroughChange();`

but since, all natural wonders are mountains it gets "leveled up" by:

`iLevel += GC.getMOUNTAIN_SEE_THROUGH_CHANGE();`

which is a global define which is set to 2 in Defines.

What we could do is add a final line at the end before the return which overrides it all that says:

```
if(isNaturalWonder(true))
{
iLevel = GC.getFeatureInfo(getFeatureType())->getSeeThroughChange();
}
```
with no added increment.

**Comment by LoneGazebo** [comment]
I've been playing with this, I think a solution would also be to simply have the isMountain() line checked alongside a (GetFeatureType == NO_FEATURE)

**Comment by Iamblichos** [comment]
that would be the easiest yes!

**Comment by Zoidbergesq** [comment]
This looks promising..
