### ISSUE TITLE
CS barbarian attack problem

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2502]
_1. Mod Version current

_2. Mod List (if using Vox Populi only, leave blank):_

_3. Error Description/steps:_ So, there was a coastal CS under attack. During the barbarian attack, a barbarian unit spawned out of my reach on another island (which was adjacent to CS border, but not in the border) and because I didn't have sailing I couldn't reach it.

It wasn't even in the CS territory, it was merely adjacent to it.

When the countdown went to 0, the CS which wasn't affected at all by the attack and still had its army got sacked. It makes no sense. That unit wouldn't defeat neither the city nor even half of the CS army, it wasn't even in the CS borders and wouldn't be able to swim there, but it somehow sacked the city? I did liberate it almost immediately, but nearly all my influence is gone now.

Recommended suggestion:

-make a CS not sacked after invasion if it still has allied military units in its borders, whether its its own or someone else's
-make the CS not be sacked by units not even in its borders at the end of barbarian invasion time

**Comment by LoneGazebo** [comment]
Barb threatening is a vanilla mechanic which that quest uses. If a barb is threatening a CS in that way at the end of the quest, it fails.

**Comment by Enrico-Swagolo** [comment]
Ah, I see. Would it perhaps be possible to make the barbarians spawn on the same landmass as CS if place is available?

I didn't have Sailing because it was too early in the game to get such a thing without Fishes.

**Comment by LoneGazebo** [comment]
Barbs will try if there is a space available, however the algorithm moves through plots in a specific order before finding one. Changing that order, or having it do an 'optimal' loop, would be a performance hog.

**Comment by Enrico-Swagolo** [comment]
I see and understand. Thanks for explanations!

**Comment by LoneGazebo** [comment]
Yep!
