### ISSUE TITLE
Zone Prioritization

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#2503]
@ilteroi,

Is it feasible for the tacticalanalysismap to process zone priorities for attacks v. minor civs as less valuable if also at war with the CS's ally? Trying to get the AI to focus more often on major civs if at war with a major AND their ally.

**Comment by LoneGazebo** [comment]
Also, moving these over from the closed issue:

Looked at code, compared things quite a bit. Outside of changes to RNG, I do not see anything that really stands out. I do, however, wonder if this is not a consequence of the RNG, but rather recent changes to the unit system. Namely, I noticed this in CvGame.cpp:

```
if(eEndTurnBlockingType == NO_ENDTURN_BLOCKING_TYPE)
		{
			if(!(activePlayer.hasBusyUnitOrCity()) && !(activePlayer.hasReadyUnit()))
			{
				// JAR  - Looks like popups are pretty much disabled at this point, this check will break
				// multiplayer games. Look at revision #27 to resurrect the old popup check code if/when
				// they are implemented again.
				if(!isGameMultiPlayer())
				{
					if((activePlayer.isOption(PLAYEROPTION_WAIT_END_TURN) && !isGameMultiPlayer()) || !(GC.GetEngineUserInterface()->isHasMovedUnit()) || isHotSeat() || isPbem())
					{
						GC.GetEngineUserInterface()->setCanEndTurn(true);
					}
				}
```

We can't test in-MP as it causes a desync, however I wonder if the DLL is hitting this point during an MP game?

Other big what-ifs:

Changing Game::GetGameTurn to a const value from a nonconst value - potential sync issue?
Removing the interface pathfinder?

**Comment by ilteroi** [comment]
re zones: you mean after the operation to bring the units over is finished? that's a tricky one, because a less well defended city is a more attractive target. so it's not a bad move, except for the part where you get caught in a two front war. i think we can do something but it may have unintended consequences.

re desync: none of these things sounds like a hot lead ...

**Comment by LoneGazebo** [comment]
@ilteroi not after the operation, but rather in the context of reposition/close on target moves for the tactical AI.

re: desyncs, I feel like the issue lies somewhere in that if(!(activePlayer.hasBusyUnitOrCity()) && !(activePlayer.hasReadyUnit())) element. The only major sync related things we've changed recently are the RNG (which I think we can consider 'potentially fixed,' based on yesterday's test) and the way that queued actions/unit missions function.

**Comment by Iamblichos** [comment]
re: desyncs, the main thing we changed between the 7-30 dll and 9-12 dll in CvGame.cpp is change void CvGame::updateGlobalAverage()

**Comment by LoneGazebo** [comment]
What was changed about it? I didn't see that.

**Comment by Iamblichos** [comment]
![image](https://cloud.githubusercontent.com/assets/14372214/18453904/fc67e8f0-7906-11e6-93ff-27d10e6ff533.png)

![image](https://cloud.githubusercontent.com/assets/14372214/18453912/099e8934-7907-11e6-9284-b57c679bb50d.png)

Then that function is called a couple of places in CvGame didn't check where else.

**Comment by LoneGazebo** [comment]
hmm.

**Comment by LoneGazebo** [comment]
I'm still also leaning on unitmission queuing as a problem. See the latest open issue.

**Comment by Iamblichos** [comment]
yeah I saw that but in your test games did you set any of your units on missions?

**Comment by LoneGazebo** [comment]
Yep, auto-explore.

**Comment by LoneGazebo** [comment]
We need to do another test. Care to whip up a no-EUI tester for us? I've got some time this week.

**Comment by Iamblichos** [comment]
I sure will. Won't be till later tonight though, gotta head home and pick up my girl from school.

**Comment by LoneGazebo** [comment]
Sounds good, take your time. I'll be around (keeping the newborn feed/watered/entertained/clean today).

**Comment by Iamblichos** [comment]
Good job daddy!

**Comment by LoneGazebo** [comment]
haha thanks!

**Comment by Iamblichos** [comment]
@LoneGazebo @ilteroi 

[9-12 Modpack NOEUI](https://www.dropbox.com/s/bqv4fskl6nnntw8/Vox_Populi_9-12_NOEUI.zip?dl=0)

**Comment by LoneGazebo** [comment]
Cool. Let me know when ready.

**Comment by LoneGazebo** [comment]
If you have time tonight. If not no worries. :)

**Comment by ilteroi** [comment]
so about the tactical zones again.

- tactical AI is for short range moves (typically 8 tiles)
- operational AI is for long range moves (take units all across the map if need be)
- units in an operation (i.e. in an army) are exempt from tactical AI
- once the army reaches its goal (which may be dynamic), it is disbanded and a "temporary" tactical zone is created at that spot
- the temp zone has a high priority (i.e. it will be processed first, when all available units still have moves to attack there) 

if everything works as intended, the attacking units should not be distracted from their intended target (before the temp zone expires, which is after 10 turns iirc). evidence to the contrary (savegame) is needed before any changes.

**Comment by LoneGazebo** [comment]
I think the issue was with neighboring CSs within 8 tiles, as there's an explicit check to prevent AI operations against CSs who are allies with a civ you war against.

**Comment by ilteroi** [comment]
every tactical zone is made up of the plots around a city. up to a certain distance. if two cities are within range, the closer one is chosen.

the units chosen for tactical moves in a zone do not actually have to be in the zone. so if the temp zone and the CS are close, it shouldn't matter. the units will spend their moves trying to attack in the high prio temp zone. only the leftovers will attack the CS.

**Comment by LoneGazebo** [comment]
I'll go ahead and add a check to reduce the base value of a zone if it is a CS (and you are at war with their ally) so that CS zones are always processed last. That might help.

**Comment by LoneGazebo** [comment]
@ilteroi, you are going to be the happiest person. I made a few more changes to the DLL and @Iamblichos and I are playing a MP game THAT IS WORKING!

**Comment by ilteroi** [comment]
awesome! what did you do?

**Comment by LoneGazebo** [comment]
Fixed two memory things and reverted a couple of smaller tweaks. I'll post the github diff shortly.

**Comment by LoneGazebo** [comment]
[Desktop.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/470742/Desktop.zip)

Logs from latest. A couple of desyncs, looks to be related to the AI's diplo decision-making.

**Comment by LoneGazebo** [comment]
From Iamblichos: [net_message_debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/470757/net_message_debug.zip)
From today's session.

**Comment by ilteroi** [comment]
ok, so the UI RNG was called from AI code?

**Comment by LoneGazebo** [comment]
Looks like it, yes.

**Comment by LoneGazebo** [comment]
The offending calls ("Diplomacy Rand") are actually async calls in CvGame.cpp - I wonder if we shouldn't make those calls sync calls, as they were probably not intended to be called in MP (as, in MP, the AI is not supposed to contact the player).

**Comment by Iamblichos** [comment]
Reference this for GoodHutPicker: http://forums.civfanatics.com/showpost.php?p=13902067&postcount=1

**Comment by Iamblichos** [comment]
Reference Gedemon's possibilities: http://forums.civfanatics.com/showthread.php?t=550217

**Comment by Iamblichos** [comment]
It looks to me like the Goodhut picker doesn't reference any call in the DLL....what if we just hardcoded all this into the DLL and have the gamecore call the user for response, and then overwrite the LUA with a blank one...

**Comment by LoneGazebo** [comment]
We could try that. I don't see any lua changes from whoward for that - only thing I see is a lua_event hook he added.

**Comment by Iamblichos** [comment]
Apparently he did something in v66, but it might've been removed since.

**Comment by LoneGazebo** [comment]
I see MOD_BUGFIX_GOODY_HUT_MESSAGES but that's pretty much it IIRC

**Comment by Iamblichos** [comment]
I think we just hardcode it into the DLL that way there is no desync....make a promotionentry for IsGoodHutPicker, etc.

**Comment by LoneGazebo** [comment]
that's pretty much how it already works, though.
