### ISSUE TITLE
Got a Won a War Historical Event from using Venetian Merchant to buy CS

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2506]
_1. Mod Version (i.e Date - 4/23):_9/12

_2. Mod List (if using Vox Populi only, leave blank):_
Full VP
Enginseer's version of E&D and Community Events
JFD Cultural Diversity
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Celtic City Names, Iroquoian City Names, Randomize City Names
My own thing that does various things SQL type stuff
Tectonic Map

_3. Error Description:_ 
I know its technically conquest, but of a City State

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

3. Screenshots (optional):
![20160912190551_1](https://cloud.githubusercontent.com/assets/16260521/18456524/9600246a-791f-11e6-8c31-e05b24289af3.jpg)

**Comment by pandasnail** [comment]
Oh, and the code I used to rename the CS is just this, nothing complicated or weird

<Update>
			<Where Tag="TXT_KEY_CITYSTATE_BOGOTA"/>
			<Set Text="Accra"/>
		</Update>
		<Update>
			<Where Tag="TXT_KEY_CITYSTATE_BOGOTA_ADJ"/>
			<Set Text="Ghanaian"/>
		</Update>
		<Update>
			<Where Tag="TXT_KEY_CIV5_BOGOTA_TEXT"/>
			<Set Text="Accra"/>
		</Update>

**Comment by LoneGazebo** [comment]
It's not wrong. You killed them.

**Comment by pandasnail** [comment]
I thought winning a war HE was only supposed to apply to majors tho? If not, then its working proper, yeah.

**Comment by LoneGazebo** [comment]
No, killing a player counts as a war victory.

**Comment by pandasnail** [comment]
Okay then, my bad.

**Comment by LoneGazebo** [comment]
No worries.
