### ISSUE TITLE
Netherlands attempt to renew "gifted" luxuries deal every turn.

### ISSUE THREAD

**Issue by Epicnessman9000** [LoneGazebo/Community-Patch-DLL#2507]
_1. Mod Version (i.e Date - 4/23):_
Complete Vox Populi Installation (+EUI) v.9.2
9/13/17

_2. Mod List (if using Vox Populi only, leave blank):_
AI no free tech v1
Faster aircraft animations v3
Historical Religions v55 (Netherlands did not found one)
Infoaddict v22 (With compatibility patch)
Ingame editor v39
R.E.D Modpack v27
Reforestation v8
Wonder Race v6.

_3. Error Description:_ 
I have given the Netherlands a luxury as they have requested from a friend, and the "deal" has recently expired. Yet every single turn, they attempt to renew the assistance provided as a trade deal, with the luxury on my side and nothing on theirs. If you accept the deal, even with changes, they will immediately request another luxury from you the next turn as "help". I have done this twice (gifting furs and gems). Accepting their offer to renew my export of furs had them instead ask to renew the gems "deal" every turn instead of furs.

I suspect this has something to do with their UA (and respective focus on importing/occasionally exporting luxuries), but this is insane. [](url)

I only have this problem with The Netherlands, I have gifted Russia and England luxuries as help when requested and they happily took it and didn't beg for more after the deal expired.

_4. Steps to reproduce (optional):_
I have not yet attempted this on a new save (due to it taking long amounts of time), but reproduction should be simple enough.

1. Get a DoF with the Netherlands.
2. Have them request a luxury from you.
3. Have the deal expire.
4. Enjoy having them knock down your door every turn asking to renew it.

Note about log files: Github doesn't seem to want to take mine, even after zipping the folder with 7z. The error message states they "do not take that file type" even though the file has been converted to a pure .zip file with no .7z association.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

3. Screenshots (optional):
![20160913074943_1](https://cloud.githubusercontent.com/assets/7888556/18457129/c79353f8-7988-11e6-841c-1f649646c73d.jpg)

**Comment by LoneGazebo** [comment]
Well this made me smile. I'll take a look but I need a save game from the 9/12 version doing it to really debug properly.

**Comment by Epicnessman9000** [comment]
My VP is actually the Sept 6th/9-2 installer version, not the newest Sept 12th/1.9.12.

Is the new version savegame compatible with older variants? If so, i'll move to the new version, play a turn, and send the save (and hopefully logs too) over.

I'm a tad surprised you guys got another update out in just 6 days also.

**Comment by LoneGazebo** [comment]
No, 9/12 is not compatible. Finish your current game and then move over. 

We work diligently!
