### ISSUE TITLE
Bad Pointer in CvPlayerEspionage::ProcessSpyMessages()

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2509]
![image](https://cloud.githubusercontent.com/assets/14372214/18460527/ed6559d8-7937-11e6-88c3-72c573933a8f.png)

**Comment by LoneGazebo** [comment]
Weird. Did it crash there?

**Comment by Iamblichos** [comment]
Yep.

**Comment by LoneGazebo** [comment]
mm I see why - silly me, I forgot to push that value into memory. Was it on a save/reload?

**Comment by Iamblichos** [comment]
Yep on a reload.

**Comment by Iamblichos** [comment]
Well to be clear its on a turnover right after a reload.

**Comment by Iamblichos** [comment]
So basically you need these?

```
loadFrom >> kMessage.m_strGWText;

saveTo << readFrom.m_aSpyNotificationMessages[ui].m_strGWText;
```

in their respective spots?

**Comment by Iamblichos** [comment]
oh and let me know if you have time for multiplayer this morning or early afternoon...I have time

**Comment by LoneGazebo** [comment]
Yeah.

**Comment by LoneGazebo** [comment]
I'll be around, hopefully.

**Comment by Iamblichos** [comment]
probably need to change this from const char* m_strGWText to CvString m_strGWText; same for AddSpyMessage

**Comment by LoneGazebo** [comment]
Makes sense. I tested it a few times with no error, but I did not think to save/load with the notification in the pipeline.

**Comment by Iamblichos** [comment]
yeah only happens on saves and reloads.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/470541/CvGameCore_Expansion2.zip)
Debug MP DLL for us to test. I'm free if/when you are this afternoon. Baby currently sleeps.

**Comment by Iamblichos** [comment]
I'm ready let me load up the mod and your gamecore dll.

**Comment by LoneGazebo** [comment]
Sounds good, loading up now.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/470680/CvGameCore_Expansion2.zip)

**Comment by Iamblichos** [comment]
[net_message_debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/470757/net_message_debug.zip)
From today's session.

**Comment by Iamblichos** [comment]
We can close this out but we got some references here, maybe wait til the next release.

**Comment by LoneGazebo** [comment]
Yeah we can wait.

**Comment by ilteroi** [comment]
@LoneGazebo :

is this the place you mean?

								int iWaitTime = 100;
								if(!isNetworkMultiPlayer())
								{
									iWaitTime = 10;
								}
								if(m_iTurnSlice - player.GetLastSliceMoved() > iWaitTime)
								{
									[.....]
								}

i never understood this turn slice concept. it seems to count the calls to CvGame::update() ... so it's not really a clock. also apparently CvGame::update() is called more than once per turn?

anyway, i'm not sure that setting it higher will help. after all, if the conditional is true, we simply forcefully end the turn for all units. that's it. same as issuing skip orders. and it would be logged, but i cannot find such a message.

**Comment by LoneGazebo** [comment]
That is the place, yes. It is the only place (I see) where 'wait time' is considered in the DLL, however. Might be worth bumping up dramatically for testing. I'm also worried about your Civ 5 installation - do you have luajit installed and/or anything else going on with your install?

**Comment by ilteroi** [comment]
now that you mention it, i'm still using luajit. will switch back to the original.

**Comment by LoneGazebo** [comment]
wonder if that's the culprit...

**Comment by LoneGazebo** [comment]
I wonder if that's also the source of your woes with infoaddict and EUI...

**Comment by LoneGazebo** [comment]
@ilteroi another curiosity:

in CvGame: do turn (line 8126) 

shuffleArray(aiShuffle, MAX_PLAYERS, getJonRand());

**Comment by LoneGazebo** [comment]
Do you think we really need that?

**Comment by Iamblichos** [comment]
I've found luajit to be incompatible with a lot of lua calls and I bet that is the real source of his desyncs.

**Comment by ilteroi** [comment]
i think it wasn't luajit after all, just some debug build of the regular lua 5.1. but still. back on stock now

**Comment by LoneGazebo** [comment]
I'd love to try again today if time, see if that was the issue.

**Comment by Iamblichos** [comment]
Getting close to getting active diplo done....I'd like to test that too...but will test in single player before.

**Comment by LoneGazebo** [comment]
I added the blocking notification system and whatnot last night, also added a function that checks all pending diplo deals and deletes them if a deal is made that invalidates said deal.

**Comment by Iamblichos** [comment]
@LoneGazebo 
Did you see my messages under 9/13 CTD fix?

**Comment by LoneGazebo** [comment]
Link?

**Comment by ilteroi** [comment]
![image](https://cloud.githubusercontent.com/assets/1358966/18565714/261ad4a0-7b91-11e6-885c-e3192f43112b.png)

**Comment by ilteroi** [comment]
notice the missing city banner

**Comment by LoneGazebo** [comment]
it goes away when you enter diplomacy with the AI in MP, as there are no leader screens in MP

**Comment by LoneGazebo** [comment]
@Iamblichos Ilteroi and I are testing now - turn 50 and no desyncs!

**Comment by Iamblichos** [comment]
@LoneGazebo Awesome!!

Link: https://github.com/LoneGazebo/Community-Patch-DLL/commit/b99e5c1f5f1c91b227b62ba1ba4384a4aea9cc36

scroll to bottom of page.
