### ISSUE TITLE
Natural wonders should be passable

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#251]
All NW should be passable so that your units can deny your enemy getting yields from them.

**Comment by LoneGazebo** [comment]
Most of them are. 
G

**Comment by qqqbbb** [comment]
Following are impassable:
FEATURE_FUJI
FEATURE_VOLCANO
FEATURE_GIBRALTAR
FEATURE_POTOSI
FEATURE_SRI_PADA
FEATURE_MT_SINAI
FEATURE_MT_KAILASH
FEATURE_KILIMANJARO

**Comment by LoneGazebo** [comment]
Aren’t all of those mountains? They shouldn’t be passable.


G

**Comment by qqqbbb** [comment]
If a tile can be worked , units should be able to occupy it. When an army besieges a city , units should be able to occupy every workable tile.

**Comment by LoneGazebo** [comment]
You should probably bring this up on the forum, as this isn’t a bug/balance issue, it is a gameplay change.
G

**Comment by Radost** [comment]
Mountains are the major pain in ass up until artillery rolls out. Which is exactly how real history worked out.

**Comment by LoneGazebo** [comment]
Forum consensus seems to be that all NWs should not be passable. I'm closing this thread.
