### ISSUE TITLE
CTD on turn

### ISSUE THREAD

**Issue by Glizinte** [LoneGazebo/Community-Patch-DLL#2512]
_1. Mod Version 9/12

_2. Mod List (if using Vox Populi only, leave blank):_

_3. Error Description:_ Crashes on hitting turn

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

3. Screenshots (optional):
[Civ V bugs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/470073/Civ.V.bugs.zip)

**Comment by LoneGazebo** [comment]
Can you explain?

**Comment by Glizinte** [comment]
I reload the save and push the next turn button and it ctd.  I've had
it also happen on another game I've been playing with the same 912
patch.  Beyond that I have no reasonable idea. Sorry.

Richard Groll

On 9/13/2016 at 11:41 AM, "LoneGazebo"  wrote:

	Can you explain?

**Comment by Glizinte** [comment]
I had this also happen on two (2) other saved games.  
I'm posting one more attachment where the game crashed on the next turn pushing the next turn button (not on a reloaded save, so perhaps a different problem, idk.)
Thanks. Love the mod by the way. :)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/478895/CvMiniDump.zip)
