### ISSUE TITLE
Spies in city states not increasing influence

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#2513]
_1. Newest (12th Sep)

_3. I've put a spy in a few city states. Each time they rig the election, the influence is not shifting.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

3. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Is there an Open Door, or a Sphere of Influence active in the CS? They can block things.

**Comment by TechpriestEnginseer** [comment]
But doesn't sphere of influence just locks the allied status(permanent ally regardless of influence) and open door the same(permanent friendly with all regardless of influence)?

**Comment by RockettSJ** [comment]
Hi guys, it was a brand new game so nothing like that was in effect

**Comment by Edaka** [comment]
How did you know that the influence wasn't being changed by rigging? Did you judge by the fact that you didn't become friendly (from being neutral)? Or did you check the actual numbers? Silly if this might seem silly, but I'm just making sure.

**Comment by Iamblichos** [comment]
I can't say for 9-12, but in the 9-13 build, influence by spies is working as intended.

**Comment by RockettSJ** [comment]
@Edaka I had a rig an election like three times, yet it was stuck at neutral. Tried it with another city state, still neutral.

@Iamblichos There's a 9-13 build? I don't see it on the official forum.

**Comment by Iamblichos** [comment]
RockettSJ, it's the in-work stuff that's been done since the release. It's the content in the repository. It's unreleased as of now. Hopefully, it'll be released soon. Big break through for Multiplayer (we hope).

**Comment by Edaka** [comment]
Rigging an election doesn't guarantee becoming friendly with a city state. I am not entirely sure about the exact numbers, but you get roughly 20 influence for rigging an election, and then the influence decays for about 15 turns until the next rigging. Spies are good for keeping relations with city states and decreasing them between city states and other civs, but not so good for getting a relationship status from scratch. I believe it was the same in vanilla BNW.

**Comment by RockettSJ** [comment]
Just tried it on a new game, it's working. Sorry about that.

**Comment by Edaka** [comment]
No problem.
