### ISSUE TITLE
Cannot liberate capture city states.

### ISSUE THREAD

**Issue by Snowthe1Wolf** [LoneGazebo/Community-Patch-DLL#2514]
_1. Mod version (i.e Date - 4/23):_
Mod version 9/12

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Cannot liberate capture city states.

_4. Steps to reproduce (optional):_
Any city-state that got capture by enemy cannot be liberate, or pick any building to build.

[xml.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/473404/xml.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Please post your lua.log. I assume this is a mod conflict.

**Comment by Snowthe1Wolf** [comment]
Hi, the zip file have EVERYTHING. And I am pretty sure it is not, as the only mod I have is the first 5 of the CBP mods.

**Comment by LoneGazebo** [comment]
Looks like you do not have EUI installed.

**Comment by Snowthe1Wolf** [comment]
Thank you, I actually do have EUI installed, but it was out of date.
