### ISSUE TITLE
Venice unplayable! Venice Puppet cities not building anything for 100+ turns. Puppet city buildings disappering and investing gold bugged!

### ISSUE THREAD

**Issue by Xyronos** [LoneGazebo/Community-Patch-DLL#2517]
_1. Mod version (i.e Date - 4/23):_

Vox Populi 9-12

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Puppeted cities are not building anything (Captured and merchants of venice) Only producing culture etc. (They built a couple of buildings at start but do not build anything for 100+ turns.) I know they sometimes prioritize food etc. over building until things stabilize but this is way over that.

When spending gold to build, all the invested buildings disapper as if completed instantly but do not appear anywhere again. And puppet city production still remains as culture etc.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Lua.log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/475275/Lua.log.txt)
[xml.log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/475274/xml.log.txt)
[Database.log.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/475276/Database.log.txt)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Enrico Dandolo_0160 AD-1000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/475279/Enrico.Dandolo_0160.AD-1000.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Xyronos** [comment]
Also completely unintalled Civ 5 and deleted all relavant files. And made a fresh install on both Civ 5 and vox populi

**Comment by Xyronos** [comment]
And forgot to mention another bug regarding Venice...

When using merchant of venice to puppet a city state. The production button appears regarding the new puppet city as if i could manually assing projects. It does disapper after the save is reloaded however.

**Comment by LoneGazebo** [comment]
I cannot replicate this, sorry.

**Comment by Xyronos** [comment]
Even on the save file?
Looking at Denpasar which should have about 10 buildings only has walls and market on the list. Could be a graphical bug, but no way to tell what happened to the invested buildings.

![desaparbug](https://cloud.githubusercontent.com/assets/22222707/18561695/9914105a-7b89-11e6-86db-3c3f26cc36bf.png)

**Comment by matlajs** [comment]
but you just invest to them, not completely build them. then they dissapear from purchase list ofc and for normal civs they are in production list with 50% of its cost. there is possibility manualy set building order with building queue on, bcoz after after purchase they appear in production list. but i dont use EUI, so i dont know what diferent there. however, puppets just build whatever they need to keep their unhappines closest to 0 when some relevant buildings are accesible. then they just prioritize money,culture,science making.

**Comment by Xyronos** [comment]
Of course, but the problem is that the buildings don't appear anywhere. They appear on the building queue they turn i invest in them. ie. i invest in 5 buildings they all appear on them queue of the puppet city with reduced build times.
The next turn they disapper completely, not on queue, not in buildable building nor in completed ones and the city just keeps on producing culture. Meaning 50 turns worth of buildings just disappeared completely and can't be built again.

I haven't had any issues with this mods previous versions as Venice.

**Comment by LoneGazebo** [comment]
That's very odd-  make a post on the civfanatics subforum to see if anyone else is experiencing the same thing. I can't reproduce the issue on my end.

**Comment by Xyronos** [comment]
Alright, i'll do that. I can play other civs normally, this one just happens to me when playing Venice.

Explaining the problem better:
![bububug1](https://cloud.githubusercontent.com/assets/22222707/18565319/06cb802a-7b98-11e6-86a9-421f9731a41a.png)

And the next turn.

![bubugu2](https://cloud.githubusercontent.com/assets/22222707/18565333/119e9ce4-7b98-11e6-9786-e6e91ba97228.png)

**Comment by TechpriestEnginseer** [comment]
I can't replicate this as well considering I'm an avid Venice player.

**Comment by Iamblichos** [comment]
Everything bad happens because of double semi-colons :)~
