### ISSUE TITLE
Tongue in Cheek

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2520]
@JFDaly @LoneGazebo  @ilteroi 

Here's what a Real(TM) Community Patch Germany Looks like:

![20160914154214_1](https://cloud.githubusercontent.com/assets/14372214/18591735/6dc47884-7bf9-11e6-99c9-e7ecf39934c9.jpg)

**Comment by LoneGazebo** [comment]
Well. Not sure how I feel about that.

**Comment by Iamblichos** [comment]
Probably nothin good!
