### ISSUE TITLE
funny combination of inca and indonesia

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2522]
nutmeg on a mountain

![image](https://cloud.githubusercontent.com/assets/1358966/18595223/100a2e3c-7c44-11e6-93f8-5d7fd80ea51b.png)

don't know how exactly this came about but should it be allowed?

**Comment by LoneGazebo** [comment]
Huh. There's an explicit check to avoid impassable. Perhaps because inca + road + candi?

**Comment by Iamblichos** [comment]
I'm a little bit baffled how that got there in the first place. Technically only Indonesia can spawn that resource on city found. So how did it end up on a mountain?

**Comment by LoneGazebo** [comment]
Oh I love this scenario. So:

Japan settles.
Inca capture, build road on mountain.
Indonesia capture, builds Candi.
Inca take back.

This is the only way, and I love it. Not changing this, too beautiful. :)

**Comment by ilteroi** [comment]
it gets even better ... indonesia conquered it back again!

![image](https://cloud.githubusercontent.com/assets/1358966/18606383/cb434ffc-7cae-11e6-9894-b56c5cfbeded.png)

now there's pepper on a mountain even without a road

**Comment by LoneGazebo** [comment]
Wonderful. I'll add a check for mountain.
