### ISSUE TITLE
Plot:AddArchaeologicalRecord Needs Clarification

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2525]
Would someone mind looking into how this code works?

````
Plot:AddArchaeologicalRecord(iArtifactClass, iEra, iPlayer1, iPlayer2)
````
For my code, I did...
````
GameEvents.BuildFinished.Add(function(iPlayer, x, y, eImprovement) 
	local pPlot = Map.GetPlot(x, y);
	if eImprovement == MCPyramids1 then
	pPlot:AddArchaeologicalRecord(GameInfoTypes.ARTIFACT_WRITING, Players[iPlayer]:GetCurrentEra(), Players[iPlayer], Players[iPlayer])						
	end
end)
````
and this pops up...
````bad argument #4 to 'AddArchaeologicalRecord' (number expected, got table)````
 I have no idea how this works, and it seems no one has actually used it. So, I don't know what to put as my main intent would be to just to add an archaeological record, so that Improvement_YieldPerEra can work.

**Comment by LoneGazebo** [comment]
I'm not exactly sure. I'll look and post translated Lua.

**Comment by TechpriestEnginseer** [comment]
And does this have any effect on artifact sites and hidden ones?

**Comment by LoneGazebo** [comment]
Should be:

  pPlot:AddArchaeologicalRecord(GameInfoTypes.ARTIFACT_WRITING, Players[iPlayer]:GetCurrentEra(), iPlayer)

**Comment by LoneGazebo** [comment]
Last one is an optint, defaults to NO_PLAYER

**Comment by TechpriestEnginseer** [comment]
I see it heavily affects how artifacts and hidden artifacts are spawned, but people won't mind if beads are plundered right?

**Comment by LoneGazebo** [comment]
I guess not, no?
