### ISSUE TITLE
so much wrong here

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2526]
![image](https://cloud.githubusercontent.com/assets/1358966/18609023/11e0674e-7cf8-11e6-9dad-71b3f1bf14ea.png)

root cause may be the unhappiness. seems to be cause by specialists. digging deeper ...

**Comment by ilteroi** [comment]
ok we're having 221900 specialists of type 7

**Comment by LoneGazebo** [comment]
Huh. That's really odd. There are explicit checks to prevent that.
