### ISSUE TITLE
Disable bad events still makes ice age appear

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2527]
_1. Mod version (i.e Date - 4/23):_

12th of September, Anno Domini 2016

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Title tbh. I disabled bad events but I still got ice age.

Could be intentional because IIRC it happens to everyone, not only one person.

_4. Steps to reproduce (optional):_

WHAT KILLED THE DINOSAURS? The Ice Age

Let's kick some ice

**Comment by LoneGazebo** [comment]
Ice age technically 'neutral.'

**Comment by Radost** [comment]
You can't call "neutral" something with only negative options.

**Comment by LoneGazebo** [comment]
I can call it whatever I want. :)
