### ISSUE TITLE
Promising to not buy land near a Civ makes them hate you.

### ISSUE THREAD

**Issue by Epicnessman9000** [LoneGazebo/Community-Patch-DLL#2529]
_1. Mod version (i.e Date - 4/23):_
Vox Populi 9/12 Full automatic installation W/EUI

_2. Mod list (if using Vox Populi only, leave blank):_
AI no free tech v1
Faster aircraft animations v3
Historical Religions v55
Infoaddict v22 (With compatibility patch)
Ingame editor v39
R.E.D Modpack v27
Reforestation v8
Wonder Race v6.

_3. Error description:_ 
Promising to not buy land near a Civ gives a massive -75 diplomatic penalty, reducing by 1 each turn (along with the time remaining counter). I have transparent diplomacy on.

This was instantly after I made the promise, I did not buy any land.

It seems the value is not cosmetic, as they started having border issues right after I made the promise, and thus the massive diplomacy hit.
_4. Steps to reproduce (optional):_
Pretty obvious.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20160918225103_1](https://cloud.githubusercontent.com/assets/7888556/18616706/2299d2a4-7df3-11e6-9d04-4b967494dbfa.jpg)

**Comment by LoneGazebo** [comment]
You misunderstand. That value is the duration of the promise. Because you enabled transparent diplomacy, that's what you see.

**Comment by Epicnessman9000** [comment]
So its not actually factored into diplomacy? Thats good to know.

I put this issue up because the civ in question asked me to stop buying land near them a few turns after I did so, multiple times at that. I thought it may have been a delayed response bug or something of the like.

**Comment by LoneGazebo** [comment]
No, it is purely a byproduct of transparent diplomacy not being able to parse values properly.
