### ISSUE TITLE
crash in lua

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2531]
![image](https://cloud.githubusercontent.com/assets/1358966/18617307/d4aeb1c0-7dcc-11e6-9100-be1354603c74.png)

don't know what wrong, never seen this before.

however, can you do me a favor and check if this "CanDeclareWar" hook is used? because it's rather slow. so if it's safe to remove, that would be great, two birds with one stone.

**Comment by ilteroi** [comment]
ah well, maybe it's also possible to cache the result

**Comment by LoneGazebo** [comment]
Dunno about that hook, but I do know that CanDeclareWar is used a lot as a DLL function (in diplo AI esp).

**Comment by LoneGazebo** [comment]
I'd ask @jfdaly if he uses it - if not, probably safe to edit out.

**Comment by Iamblichos** [comment]
I've never used that lua hook either.

**Comment by Iamblichos** [comment]
http://forums.civfanatics.com/showthread.php?t=515978

It seems to be a part of the GameEvents DLL hook though, so I'm not sure that it should be edited out..

**Comment by ilteroi** [comment]
i won't touch it as long as it doesn't crash again

**Comment by JFDaly** [comment]
Tes, my Nri and Novgorod civs use it.
