### ISSUE TITLE
TXT_KEY_BUILDING

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#2532]
_1. Mod version (i.e Date - 4/23):_
9/12

_2. Mod list (if using Vox Populi only, leave blank):_
VP EUI set (9/12)
Community Events (9/11)
IGE

_3. Error description:_ 
I found a few TXT_KEY_BUILDING tags when certain events occurred.
TXT_KEY_BUILDING_MONASTERY
TXT_KEY_BUILDING_STADIUM

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![monastery](https://cloud.githubusercontent.com/assets/11933188/18621241/3f1a4450-7e5b-11e6-8bf7-60cb551f10a6.png)

![stadium](https://cloud.githubusercontent.com/assets/11933188/18621245/43e1c9e0-7e5b-11e6-9607-6d145a57049c.png)

**Comment by LoneGazebo** [comment]
These are not my events, please contact enginseer or JFD (whoever made these).

**Comment by 8h42** [comment]
Well, Enginseer told me to ask Gazebo.

According to this thread, Thalassicus seemed to have a similar issue.
http://forums.civfanatics.com/showthread.php?t=432120

**Comment by TechpriestEnginseer** [comment]
Isn't it your Lua?

**Comment by LoneGazebo** [comment]
Ah, I was looking at thumbnails on my mobile. Probably an issue with const char vs cvstring. I'll look.

**Comment by GrantSP** [comment]
It's due to some TXT_KEYs being called as TXT_KEY_<buildingname> and others are called using TXT_KEY_<buildingname>_DESC.

Those two examples are called with the latter format.

**Comment by LoneGazebo** [comment]
Ah, I know what's up. Fixed.
