### ISSUE TITLE
BUG: Japan can't send internal trade routes

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2533]
_1. Mod version (i.e Date - 4/23):_

18th September

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):

Create Caravan
Granary/Stone Works

Can't send TRs to fellow cities, only to opponents/CSs

**Comment by LoneGazebo** [comment]
Ah bad merge missed my code. Damn. Thankfully I can hotfix.

**Comment by LoneGazebo** [comment]
Ah bad merge missed my code. Damn. Thankfully I can hotfix.
