### ISSUE TITLE
UNIT needs orders

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2534]
_1. Mod version (i.e Date - 4/23):_

Current, 18th of September

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Play the game.

Try to finish the turn.

It goes to have you move an unit.

If the last unit in the queue is moved in the way that leaves it with no movement left or fortified while it's a civilian, the end turn button will never appear. It will always be "an unit needs orders", never ending, not allowing you to proceed unless you reload.

At first it seemed to be okay, but when I got to turn 200~ it became like this

**Comment by LoneGazebo** [comment]
I think @ilteroi just fixed this...

**Comment by Enrico-Swagolo** [comment]
I don't think this was here last version? Or I didn't experience it

**Comment by ilteroi** [comment]
my fix was for AI units ... do you have a savegame?

**Comment by LoneGazebo** [comment]
Wouldn't auto-exploring units fall under that category?

**Comment by Enrico-Swagolo** [comment]
I will provide a savegame. As always, I use regular VP (with bonus resources insta reveal change) + VP semi-official Meister Maggi's extended EUI view, but it should load without. Will post against once I get my hands on the file

**Comment by Enrico-Swagolo** [comment]
The problem is there though - the game un-stucks itself  from the "can't proceed because unit that moved has to move" phase when loading the game.

I have one save which got stuck (but when u load, it gets unstuck...
And one save a few turns after. This time I tried for about 10 turns to go back to the "unit needs orders but can't get orders" phase but failed. It's very hard to catch.
[zipzap.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/480693/zipzap.zip)

**Comment by Enrico-Swagolo** [comment]
For Ilteroi one is one X turns after stuckness, the sdoda is stuck (unstucks itself upon loading)
