### ISSUE TITLE
Japan Bushido bug (?)

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2535]
_1. Mod version (i.e Date - 4/23):_

18th sept

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Play Japan.

Get Dojo and promo.

Hurt your unit while adjacent to a city and enemy unit

Mouse over the unit. The value will be, for instance, 8%+ CS from Bushido

Mouse over the city. The value will be 6% or 4%, for some reason lower

Is Bushido promotion supposed to not work normally against cities?

**Comment by Enrico-Swagolo** [comment]
I looked more at the values and it feels like Bushido is applied at its old values for cities, but at the new ones against units.

**Comment by LoneGazebo** [comment]
That's probably just a lua discrepancy on my end, whereas the actual bonus is the same. But I'll check.
