### ISSUE TITLE
Can't end turn

### ISSUE THREAD

**Issue by Sekisetsu** [LoneGazebo/Community-Patch-DLL#2536]
_1. Mod version (i.e Date - 4/23): 9/18

_2. Mod list (if using Vox Populi only, leave blank): really advanced set up; events & decisions

_3. Error description:_  I can't end my turn. pressing "next turn" button does nothing. same bug was in last version too. no unit has movement points left.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/480724/Database.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/480725/Lua.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):  
![aztecs](https://cloud.githubusercontent.com/assets/20355596/18642712/09b14150-7ea2-11e6-801e-ad82520f0460.jpg)

**Comment by LoneGazebo** [comment]
Post your savegame, if you did not already.

**Comment by Enrico-Swagolo** [comment]
It's the same as my bug, except in my case it has always shown me that I need to move a unit (while not moving me to that unit, because everything was moved and/or fortified)

**Comment by Sekisetsu** [comment]
after i closes the game and loaded the save game i could press the buttom. but a few turns later there was this again. 

save game: 
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/480804/QuickSave.zip)

but i don't think it is useful because loading the savegame after going to the desktop solves the problem. it will be a bit annoying if this happens too often.
