### ISSUE TITLE
Everlasting Youth promotion given to all units

### ISSUE THREAD

**Issue by ashendashin** [LoneGazebo/Community-Patch-DLL#2537]
_1. Mod version (i.e Date - 4/23):_
9-18

_2. Mod list (if using Vox Populi only, leave blank):_
JFD's Cultural Diversity (Core) (v 10)
JFD's Event Compendium (v 4)

_3. Error description:_ 
All of my units received everlasting youth, despite only one being built in the city with the NW. I assume this is related to the recent morale promotion change?

(On a side note, early on the ai is extremely suicidal with settlers, preferring to beeline towards their destination with a single warrior for defense, no matter the odds. Makes securing land in large games really easy. This is not the case if they're near their own borders)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Washington_0062 BC-2450.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/480957/Washington_0062.BC-2450.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Enrico-Swagolo** [comment]
I think it's intended? Two game total I've gotten the Fountain in youth in my borders (both 1-3 versions ago), always afterwards all my units had that free March thing.

Pretty broken but fun

**Comment by ashendashin** [comment]
So it's not new? Pretty insane given the fact that the Ottomans just get the one unit type with healing.
Hopefully it gets addressed. I'm probably gonna scrap my current game since emperor is easy enough for for land grabbing as it is.

**Comment by LoneGazebo** [comment]
Balance issues belong on the forums, not here.
