### ISSUE TITLE
Second Dojo promotion

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2538]
_1. Mod version (i.e Date - 4/23):_

18th

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

So, I've got this nice Knight. He is level 3, got a Dojo promotion and is nearing a level up.

Once he got to level 4, he got another promotion. Samurai aren't getting second Dojo promotions, only this one Knight. He is a true Japanese man of great virtues.

Is it intended?

**Comment by LoneGazebo** [comment]
Eh?

**Comment by Enrico-Swagolo** [comment]
I can get you a pic

He has two Dojo promotions, IIRC Loyalty + Righteousness

**Comment by LoneGazebo** [comment]
No idea. If it only happens once, I can't really debug that.

**Comment by Enrico-Swagolo** [comment]
I suppose it's not a problem if one Knight is very virtuous.

I wonder if he'll get a third one if I get him to lvl 8

**Comment by LoneGazebo** [comment]
we shall see.
