### ISSUE TITLE
MOD_EVENTS_ESPIONAGE

### ISSUE THREAD

**Issue by Jamforce** [LoneGazebo/Community-Patch-DLL#254]
--Events sents on espionage outcomes (v63)--
 GameEvents.EspionageResult.Add(function(iPlayer, iSpy, iResult, iCityX, iCityY) end) 
 GameEvents.EspionageState.Add(function(iPlayer, iSpy, iState, iCityX, iCityY) end) 

The first lua hook doesn't work, to fix this:

In CvEspionageClasses.cpp, line 6731, change

GAMEEVENTINVOKE_HOOK(GAMEEVENT_EspionageState, (int) eSpyOwner, iSpyIndex, iResult, m_pCity->getX(), m_pCity->getX());

to 

GAMEEVENTINVOKE_HOOK(GAMEEVENT_EspionageResult, (int) eSpyOwner, iSpyIndex, iResult, m_pCity->getX(), m_pCity->getY());

**Comment by LoneGazebo** [comment]
Will fix.
G
