### ISSUE TITLE
Crashing to desktop everytime on a specific turn.

### ISSUE THREAD

**Issue by KyonV2** [LoneGazebo/Community-Patch-DLL#2541]
_1. Mod version (i.e Date - 4/23):_ 8/2 MP 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Just crashing to desktop without any error whatsoever. Tried going back 10 turns and it still crashed. 

_4. Steps to reproduce (optional):_ Just go from turn 282 to 283 and it will crash.

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/482319/logs.zip)

**Comment by LoneGazebo** [comment]
Please update. That version is quite old.

**Comment by KyonV2** [comment]
The only reason we used this version was because a lot of people said it's the most stable one. Would it be possible to change the versions now, in middle of a game? We would love to finish this.

**Comment by Iamblichos** [comment]
We as in multiplayer? I'll have new modpacks out this hour. Will be your most stable version.

**Comment by KyonV2** [comment]
That's awesome!  

Yeah, we played MP, I did mention that in the first post. Do you think it would be possible  to change the packs mid game through though? Or should we just abandon this game.

**Comment by LoneGazebo** [comment]
I'd abandon. 8/2 worked for its day, but we've got something much better in store.

**Comment by KyonV2** [comment]
We just tested it with the new version, just instantly crashes. Guess we will just abandon this game.

**Comment by LoneGazebo** [comment]
Oh yeah, definitely not savegame compatible. Sorry.
