### ISSUE TITLE
Japan UA GG/GA faith bug

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2542]
_1. Mod version (i.e Date - 4/23):_ 18th September

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

GG/GA acquired not from combat, like Faith, don't grant Daimyo Patronage (50% of GWAM)

Doesn't seem intended to me? It's a bit of a needless nerf imho, especially since the UA description doesn't mention it's only for GGs from combat.

Not sure if Great Wall GG gives 50% of all GWAM, because AI is absolutely obsessed with that one,. same with Pisa's Leaning Tower

**Comment by Enrico-Swagolo** [comment]
Got Great Wall after I got 2 x Tea and monopoly in my capital (Great Library into Great Wall made it possible). No bonus points.

Those GG Daimyos must be some cheapskates to not give stuff.

**Comment by Enrico-Swagolo** [comment]
Leaning Tower of Pisa also gives no points? Or I didn't notice.

Japanese hate Pizza confirmed

**Comment by LoneGazebo** [comment]
Free GG/GAs should work. Faithbought GG/GA do not, however I can change that. I'm actually considering changing the UA slightly, making it so that _killing units_ near GG or GAs generates GWAM points (instead of spawning GA/GGs giving them points), in order to distinguish the ability a bit from Sweden's.

**Comment by Enrico-Swagolo** [comment]
Well, free GG from Great Wall definitely did nothing. Maybe I missed Pisa proc (not certain with this one), but GWall I'm 100% sure about.

I don't really like that idea tbh, it's too complicated. If you want to differentiate it from Sweden it'd be better to just give something like every GG/GA spawn, your capital gets permanent +2/3 GWAM points, scaling with era (?). Works similarly enough to the current one, but it'd allow Japan to calm down a bit after enough GG/GA were spawned, which'd be pretty unique among warmongery civs.

**Comment by LoneGazebo** [comment]
A promotion to randomly generate GW/GM/GA points in your Capital when gaining experience is pretty simple, IMO.

**Comment by LoneGazebo** [comment]
The current one is pretty solid, just need to fix the (apparently) missing bonuses from Wonders and Faith.

**Comment by Enrico-Swagolo** [comment]
Yeah I agree Japan is solid for sure. Dojo is now very strong, the Samurai is flawless, the UA is pretty good once it gets going.
