### ISSUE TITLE
Morale bug

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2543]
_1. Mod version (i.e Date - 4/23):_

19th september

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Get a Scout.

Upgrade him to an Archer.

He won't get Morale if you buy Orders/Heroic Epic.

Other Scouts get it, but if one is upgraded this way - he doesn't get anything. I wouldn't be surprised if tracking got likewise broken on all other  units upgraded through ruins.

Also starting Warrior never gets Morale, but then it's not like he is born in the capital.

**Comment by LoneGazebo** [comment]
I'll need to check if that data persists. It should, but who knows with spaghetti code
