### ISSUE TITLE
AI doesn't heal

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2545]
_1. Mod version (i.e Date - 4/23):_

19th september

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I'm fighting Polynesia as Japan.

I decided to attack him early because his Moai is crazy OP, I've been pillaging every single one of those unholy things viciously.

The problem is, sometimes AI will stop healing its units despite having them seemingly fortified... A warrior was inside the city and Kamehameha wasn't healing him, his HP was going down to my one archer. It only stopped once I've shown him another Archer, at which point the heals resumed.

**Comment by LoneGazebo** [comment]
No idea.

**Comment by Iamblichos** [comment]
I haven't seen this yet. Every now and then I'll see a stray unit not healing...but not very often.

**Comment by Der-Zorn-Gottes** [comment]
I have experienced this sort of behavior too.
Only happens when I besiege cities. The garrison does  neither act nor heal.
Has nothing to do with the recent patch, I remember this from months ago.
