### ISSUE TITLE
Shoshone Goodhutpicker (for Iamblichos to fix)

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2546]
Bang your dead:

```
			// Any valid Goodies?
			if(avValidGoodies.size() > 0)
			{
#if defined(MOD_BUGFIX_MINOR)
				// Fix the bug where the AI won't get anything for Goody Hut pickers!!!
				if (pUnit && pUnit->isHasPromotion((PromotionTypes)GC.getPROMOTION_GOODY_HUT_PICKER()) && GC.getGame().getActivePlayer() == GetID())
				{
#else
				if (pUnit && pUnit->isHasPromotion((PromotionTypes)GC.getPROMOTION_GOODY_HUT_PICKER()))
				{
					if(GC.getGame().getActivePlayer() == GetID())
#endif
					{
						CvPopupInfo kPopupInfo(BUTTONPOPUP_CHOOSE_GOODY_HUT_REWARD, GetID(), pUnit->GetID());
						GC.GetEngineUserInterface()->AddPopup(kPopupInfo);
						// We are adding a popup that the player must make a choice in, make sure they are not in the end-turn phase.
						CancelActivePlayerEndTurn();
					}
				}
				else
				{
```

**Comment by Iamblichos** [comment]
I think whoward fixed an AI issue but broke it in multiplayer.

**Comment by LoneGazebo** [comment]
I think just making it so that the AI does the random selection there would probably do it.

**Comment by Iamblichos** [comment]
if the game is played in simultaneous or hybrid multiplayer mode, calling .GetActivePlayer will have it return themselves, rather than the player intended by this function. It looks like it needs more control.

**Comment by LoneGazebo** [comment]
Makes sense.

**Comment by Iamblichos** [comment]
Will try and do some testing tomorrow.

**Comment by LoneGazebo** [comment]
I've got the renewal bug pinned down, but its tricksy. We'll see.

**Comment by Iamblichos** [comment]
FYI...http://forums.civfanatics.com/showpost.php?p=14001433&postcount=1232

It's not the goodies that have been added. Otherwise, if it was that whoward's would work since he's added no additional goodies.

**Comment by Iamblichos** [comment]
I got it!

**Comment by Iamblichos** [comment]
Okay I did this game with Raging Barbarians getting a lot of desyncs, (I think) related to Unitcombat against Barbarins:

[RNG.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/485454/RNG.zip)

**Comment by Iamblichos** [comment]
I also had the Game Option GG/GA points from Barbarians enabled, which is my mod. It might be that.

**Comment by Iamblichos** [comment]
Okay turned that off...still getting RNG's it looks like from UnitCombat with Barbarians.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/485558/Logs.zip)

**Comment by Iamblichos** [comment]
Okay started another one. No barbs and no desyncs. Could pick goody huts all day long with pathfinder. Even declared war on an AI and engaged in combat. No desyncs in combat there. Desyncs are definitely related to barb combat.

**Comment by Iamblichos** [comment]
For your viewing pleasure, this is what worked for Shoshone Pathfinder

```
#if defined(MOD_BUGFIX_MINOR)
				// Fix the bug where the AI won't get anything for Goody Hut pickers!!!
				if (pUnit && pUnit->isHasPromotion((PromotionTypes)GC.getPROMOTION_GOODY_HUT_PICKER()) && GET_PLAYER(pUnit->getOwner()).isHuman())
#else
				if (pUnit && pUnit->isHasPromotion((PromotionTypes)GC.getPROMOTION_GOODY_HUT_PICKER()))
#endif
				{
					if(GC.getGame().getActivePlayer() == GetID())

					{
						CvPopupInfo kPopupInfo(BUTTONPOPUP_CHOOSE_GOODY_HUT_REWARD, GetID(), pUnit->GetID());
						GC.GetEngineUserInterface()->AddPopup(kPopupInfo);
						// We are adding a popup that the player must make a choice in, make sure they are not in the end-turn phase.
#if defined(MOD_BUGFIX_MINOR)
						if (!GC.getGame().isGameMultiPlayer())
						{
							CancelActivePlayerEndTurn();
						}
#else
						CancelActivePlayerEndTurn();
#endif
					}
				}
				else
				{
```

**Comment by LoneGazebo** [comment]
Barb combat desyncs? Barbs don't use the RNG for combat anymore (unless you merged @ilteroi's latest, which I think uses JonRanVA.

**Comment by LoneGazebo** [comment]
If it does, we should go back to what I had done.

**Comment by Iamblichos** [comment]
I merged ilteroi's latest.

**Comment by Iamblichos** [comment]
That might be the problem.

**Comment by Iamblichos** [comment]
Re: Shoshone pathfinder, if you review CancelActivePlayerEndTurn(), you'll note that it CAN have a problem in MP Games (and I'm assuming here only Simult/Hybrid games). Instead of just getting rid of that completely, we could add in a new notification just to ensure the player doesn't end turn (in case they have auto end turns on OR if the AddPopup will not allow the turn to progress, then there is no issue).

**Comment by LoneGazebo** [comment]
Hmm, interesting. Not sure we need it, though.

Re: desyncs, revert to my fake num and alert ilteroi to the issue.

**Comment by Iamblichos** [comment]
Regarding ilteroi's latest, are you referring to this bit of code:

```
	// RNG quality test 



 
	/* 



 
	vector<int> result(1000, 0); 



 
	for (size_t i = 0; i < 1e6; i++) 



 
	{ 



 
		int j = m_jonRand.get(1000); 



 
		result[j]++; 



 
	} 
```



 
+	for (size_t i = 0; i < result.size(); i++) 



 
+	{ 



 
+		OutputDebugString(CvString::format("%03d\t%03d\n",i,result[i]).c_str()); 



 
+	} 



 
+	*/

**Comment by LoneGazebo** [comment]
No, look in unitcombat for RandNumVa.

**Comment by Iamblichos** [comment]
Don't see anything in his recent changes the modifies RandNum values in unicombat.cpp

The only thing that uses RandNum values in Unitcombat is Capture, Morale Break, Nukes, Interception, and Intercept Paradrop.

**Comment by LoneGazebo** [comment]
If that is so, then your merge returned some old, bad code to unitcombat.cpp. Look for RandNumVA in the Unitcombat.cpp file and remove it. I'll check my files and see if I can find the spot.

**Comment by Iamblichos** [comment]
Yeah when I did my merge the other day, I also merged fefe on accident. My bad...

**Comment by LoneGazebo** [comment]
May need to do a reversion, as that's not good at all. Did you merge into master?

**Comment by Iamblichos** [comment]
I merged into my master and then made a pull request to you.

**Comment by Iamblichos** [comment]
Instead of doing the reversion, just do a complete diff between prior to my pull request and after.

**Comment by Iamblichos** [comment]
Like a complete compare between 9-21 MP and 9-19.

**Comment by Iamblichos** [comment]
`iRoll = /*1200*/ GC.getGame().getJonRandNumVA(GC.getATTACK_SAME_STRENGTH_POSSIBLE_EXTRA_DAMAGE(), "Unit Combat Damage (%s at %d,%d)", getName().c_str(), getX(), getY() );`

**Comment by Iamblichos** [comment]
bad code in CvUnit.cpp

**Comment by LoneGazebo** [comment]
That's the spot.

**Comment by Iamblichos** [comment]
I'll make a pull request (and for Shoshone). Let me run through the rest real quick.

**Comment by LoneGazebo** [comment]
I think that's the only thing that slipped in.

**Comment by Iamblichos** [comment]
Okay Pullrequest created.

**Comment by Iamblichos** [comment]
Hard to believe we fixed all this MP stuff.

**Comment by LoneGazebo** [comment]
:)

**Comment by Iamblichos** [comment]
Getting a desync on Goody Tech:

`iValue = (1 + GC.getGame().getJonRandNum(10000, "Goody Tech"));`

**Comment by LoneGazebo** [comment]
Eh, make it a fakenum. No reason for a huge random number there.

**Comment by Iamblichos** [comment]
Got some others:

```
iGold = kGoodyInfo.getGold() + (kGoodyInfo.getNumGoldRandRolls() * GC.getGame().getJonRandNum(kGoodyInfo.getGoldRandAmount(), "Goody Gold Rand"));

int iRoll = GC.getGame().getJonRandNum(veUniqueLuxuries.size(), "Rolling for Mercantile city-state special luxury"); // range = [0, size - 1]
```

**Comment by LoneGazebo** [comment]
We had those working fine the other day – @ilteroi any recent changes to RNG? Something seems off.

**Comment by Iamblichos** [comment]
```
if (isBarbarian())
		{
			iRoll = /*1200*/ (GC.getGame().getSmallFakeRandNum(10, GetID()) * 120);
		}
		else
		{
			iRoll = /*1200*/ GC.getGame().getJonRandNum(GC.getATTACK_SAME_STRENGTH_POSSIBLE_EXTRA_DAMAGE(), "Unit Combat Damage");
		}
```

In RandomCalls.csv I'm still getting "Unit Combat Damage" ...pretty early don't think there is war yet. Just fighting barbs (I think).

**Comment by LoneGazebo** [comment]
Fighting against barbarians, most likely. Should be fine.

**Comment by Iamblichos** [comment]
yeah but it desynced right there.

**Comment by Iamblichos** [comment]
It must have been when a barb attacked a player.

**Comment by LoneGazebo** [comment]
If it is a barb unit, it should not.

**Comment by Iamblichos** [comment]
[RandCalls.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/486108/RandCalls.zip)

Here's the results from my latest session. Was better but still a few desyncs.

**Comment by LoneGazebo** [comment]
Well it was working fine. What's going on? Did the bad fefe merge do something else?

**Comment by Iamblichos** [comment]
I dunno....I'm thinking about starting back at 9-19 base and just add in the diplo changes (and shoshone) and leave fefe out.

**Comment by Iamblichos** [comment]
Next Tech Choices and Build Choices???

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/486349/Logs.zip)

**Comment by Iamblichos** [comment]
I'm going to try again and turn off events. Not sure if that stuff is firing in multiplayer.

**Comment by LoneGazebo** [comment]
Events cannot fire in MP. Specifically disabled regardless of options.

Gothic_Empire is running MP flawlessly in his test setup.

**Comment by Iamblichos** [comment]
Yeah I saw his post not sure what the heck I have wrong here.

**Comment by Iamblichos** [comment]
All working. Pathfinder. Everything.

**Comment by MoiMagnus** [comment]
> if the game is played in simultaneous or hybrid multiplayer mode, calling .GetActivePlayer will have it return themselves, rather than the player intended by this function. It looks like it needs more control. 

Could this be the reason why loading a MP game with simultaneous or hybrid mode skip one turn ?
(Or used to skip one turn. I've not played again in MP in the last version, so I don't know if you managed to solve this bug)
Maybe the game is just not able to find who is currently playing, so it go to the end of the turn by default.

**Comment by Iamblichos** [comment]
Skip a turn on a resync?

@LoneGazebo You can mark this as fixed for up coming version. No code changes except for what I have already provided for Shoshone. In regard to desyncs that I posted here, I had a lua script running that does an Era Restriction ( if you haven't completed all tech in a given era you can't proceed to the next era), that script was causing a desync in Multiplayer.

**Comment by MoiMagnus** [comment]
@Iamblichos Not on a resync. When loading a save (autosave or manual save), the player turn is skipped, and the AI play two times (one "before the save", and one "after the save"). It only happen in hybride or simultaneus, and only if players are not in the same team.

**Comment by Iamblichos** [comment]
I'll have to test that out and see if it's still there.

**Comment by LoneGazebo** [comment]
What was wrong iamblichos? You went from all hell breaking loose to perfect in 12 hours.

**Comment by Iamblichos** [comment]
I play with a mod script, or rather did.
```
function erarestriction(iPlayer, techTypeID)
	local prereqEra = GameInfo.Technologies[techTypeID].Era
	if prereqEra then
		local pPlayer = Players[iPlayer]
		local pTeam = Teams[pPlayer:GetTeam()];
		local pEra = GameInfo.Eras[prereqEra].ID
		if (pTeam:GetCurrentEra() < pEra)then
			return false;
		elseif (pTeam:GetCurrentEra() >= pEra) then
			return true;
		end
	end
	return true;
end
GameEvents.PlayerCanEverResearch.Add(erarestriction)
print("Complete Eras Active")
```

That's why I was getting a desync every time the AI player was choosing their next tech.

So I just modded the DLL with the intent above, and all was well. Played 3 hours last night against myself, with no desync.

**Comment by LoneGazebo** [comment]
perfect. did you win? :)

**Comment by Iamblichos** [comment]
Just barely...! Man it was a tough fight.

**Comment by Iamblichos** [comment]
Playing as Shoshone, I think I picked like 15 goodies. So nice to see that turnover. Was happy.

**Comment by Iamblichos** [comment]
Note fixed for future version. Closing out.
