### ISSUE TITLE
Crashes to desktop whenever I click End Turn

### ISSUE THREAD

**Issue by Zelniq** [LoneGazebo/Community-Patch-DLL#2547]
_1. Mod version (i.e Date - 4/23):_
Vox Populi (9-12)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Crashes to desktop (without a dialog/error box) whenever I try to end the turn on this save game. Turn 199.

_4. Steps to reproduce (optional):_

End the turn to crash the game.
---------------------------
Supporting information: [Harun al-Rashid_0199 AD-1390.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/484387/Harun.al-Rashid_0199.AD-1390.zip)
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Please update. Crash probably related to spies.

**Comment by Zelniq** [comment]
Ok, I updated to 9/19 and now it crashes to desktop when I try to load the save game, or any of my earlier save games.

**Comment by LoneGazebo** [comment]
9/19 is not savegame compatible (says so in the install thread).

**Comment by Zelniq** [comment]
Oh, ok. Thanks for the fast response.
