### ISSUE TITLE
Pillaging Moai doesn't remove combat bonus

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2548]
_1. Mod version (i.e Date - 4/23):_

19th of September, Anno Domini 2016

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Be a leader.

Fight Kamehameha to pillage his Moais and never make peace to ensure he doesn't ball out of control

Despite Moais being all pillaged, they still give a 20% combat bonus?

It seems like a bug. If I pillage a citadel, it gives no defence. Same with Feitoria, Chateau, etc. I don't see why the best UI in the game that is already superior to medieval era UIs should be even better by ignoring the unspoken rule of pillaged stuff gives nothing.

**Comment by TechpriestEnginseer** [comment]
Pillaging Moais compared to replacing Moais is a lot different codewise. My best guess is that the code only checks if the tile has a moai rather than actually check its pillaged status.

**Comment by Iamblichos** [comment]
It wouldn't be hard to do a check if pillaged. If it seems like a decent change for good gameplay, we can do it.

**Comment by LoneGazebo** [comment]
Already fixed.
