### ISSUE TITLE
East India Company causing miscount of local luxuries and loss of monopoly

### ISSUE THREAD

**Issue by Alaric410** [LoneGazebo/Community-Patch-DLL#2549]
Version 1.9.12.0 (9-12)

Vox Populi only.

On building the East India Company I lost my monopoly on incense.  I previously had 6/8 with two of the six being near the city of Edinburgh where I built the EIC.  After building the EIC the happiness tooltip still shows two incense near Edinburgh and four near other cities but the total shows as only four, which is also what shows up in the Corporations overview (it says I have 4/8 for 50%).   So not only have I not got my extra copies, I seem to have lost two that I already had.

Not sure if this may be related to previous bug #2123 (wasn't able to be reproduced) or #2386 (similar to that case, both my Edinburgh incense tiles are improved by GP improvements - but possibly a coincidence - they were working fine before the EIC).  I don't think it is related to #2523 - possible that was caused by not getting the extra copies but I don't think it included the disappearance of previous luxuries?

Attaching save file from immediately after building the EIC and getting the notification (Turn 483) and also a Turn 481 save showing me with six local incense.

[Boudicca_0483 AD-1893.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/484874/Boudicca_0483.AD-1893.zip)

[Boudicca_0481 AD-1891.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/484876/Boudicca_0481.AD-1891.zip)

**Comment by matlajs** [comment]
i already reported some days ago. no care. i also thought about GP improvements causing it, since i always plantation/camp luxuries improve with it when get some GP. rly duno. i didnt lost my monoply bcoz i controled 100% (9/9) but i had just 7 to sell instead of 11- maybe more. Actually i dont know how it works. If any of luxury type within 5 tiles of that city is copied, even if its worked by another own city. anyway, it doesnt work how its intended.

**Comment by LoneGazebo** [comment]
@matlajs actually I already fixed this because of your last report. He is on an old version. Please update @Alaric410.

**Comment by matlajs** [comment]
ok sorry then

**Comment by Alaric410** [comment]
Sorry.  I somehow got the idea that the issue was different to that posted by @matlajs.   I'll update for my next game.  For this one I'll just go back to turn 481 and go without the EIC.
