### ISSUE TITLE
Bug : Dojo level up yields only one per turn

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2550]
_1. Mod version (i.e Date - 4/23):_

19th of September

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Get 2 guys to level up on one turn after Dojo is up (of course they need to level up to lvl 3 or higher to get yields).

Only one pop-up will appear on the right, for the first level up. The second won't give a pop-up of any sort.

Even above the cities the yields do not appear if you level two guys in one turn, so I can't be quite certain the second level up even procs the yields.

**Comment by Enrico-Swagolo** [comment]
Correction - the yields are definitely added, but the pop-up doesn't always appear, though in those cases the sound of a pop-up is still made.

**Comment by LoneGazebo** [comment]
You can't have more than one of the same instant yield popup type at a time. That's a DLL limitation.
