### ISSUE TITLE
Cultural Victory Broken under specific conditions

### ISSUE THREAD

**Issue by Mallek-dev** [LoneGazebo/Community-Patch-DLL#2552]
_1. Mod version (i.e Date - 4/23): 9/19

_2. Mod list (if using Vox Populi only, leave blank): 

_3. Error description:

The cultural victory never triggers even though the victory condition is enabled in this game. I suspect this is either due to historical events causing the last civilization to swing to influential or it is a result of the treasure fleet project completing at the beginning of the next turn.

_4. Steps to reproduce (optional):

If all you do is hit next turn once using the saved game below the player will be influential with all civilizations in the game as a result of per turn tourism in combination with historical event tourism.  If the player hits next turn again they will not achieve cultural victory as expected.

I was not able to attach the saved game zipped to this ticket (assuming due to size). I have uploaded it here, http://s000.tinyupload.com/index.php?file_id=99686244725100268163

**Comment by LoneGazebo** [comment]
You have an ideology and your people are content, yes? Those requirements are highlighted in detail in the civilopedia and the victory screen.

**Comment by Mallek-dev** [comment]
No ideology is likely the reason then. Didn't remember that being a requirement and didn't think to check. Likely need another 20 turns or less and victory will trigger on ideology choice. Ticket can be closed as things appear to be working as intended.

**Comment by LoneGazebo** [comment]
Yep! As long as you are content it'll work.

Cheers.
