### ISSUE TITLE
Requests for text tags

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#2554]
I have a few problems with translation.

-----
**1 HEIST TIME**

Where is the string of HEIST TIME?
I can't find it in text files.
It would be great if you could move it to the CoreText_en_US.xml or something.

![heist](https://cloud.githubusercontent.com/assets/11933188/18742736/d07493b4-80f0-11e6-8384-3039b5d9d745.png)

-----
**2 CONQUEST_ASSYRIA**

Would you please move TXT_KEY_SCIENCE_BOOST_CONQUEST_ASSYRIA to the CoreText_en_US.sql?
I often forget to update the CoreDefines.sql.
Sorry for my laziness.

cf.
(1) Community Patch\Core Files\Core Values\CoreDefines.sql

```
INSERT INTO Language_en_US
			(Tag,										Text)
SELECT		'TXT_KEY_SCIENCE_BOOST_CONQUEST_ASSYRIA',	'Your soldiers found [ICON_RESEARCH] Science during the conquest of {1_Name}!'
WHERE EXISTS (SELECT * FROM CustomModOptions WHERE Name='ALTERNATE_ASSYRIA_TRAIT' AND Value= 1 );
```

**Comment by LoneGazebo** [comment]
Those are both CBO featues, but yes, I can move them (as they don't replace vanilla texts).

**Comment by 8h42** [comment]
Thank you.
