### ISSUE TITLE
Flak Targeting

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#2555]
_1. Mod version (i.e Date - 4/23):_

9/12
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Here is a screenshot where the flak targeting promotion is represented by a wrong icon. I did not save the lua log, but will provide it the next time the issue comes up.

![20160911132426_1](https://cloud.githubusercontent.com/assets/16065630/18757260/6a381d0c-80f3-11e6-81b4-311f1cc35a57.jpg)

_4. Steps to reproduce (optional):_
---

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.
1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Yeah, I need the lua log to decipher. Flak II has an icon. Nevertheless I did remove Flak II from units that don't already have Flak I.

**Comment by Freaky-Freddy** [comment]
I've also noticed this bug in past versions. It just seems to grab a random icon every time it appears.

**Comment by LoneGazebo** [comment]
Need Lua log.

**Comment by pandasnail** [comment]
Here's the LUA log error

[100803.078] UnitPanel: IconHookup error - icon index:	59	icon size:	45	atlas:	ABILITY_ATLAS	image control:	UnitActionIcon
[100808.265] UnitPanel: IconHookup error - icon index:	59	icon size:	45	atlas:	ABILITY_ATLAS	image control:	UnitActionIcon
[100809.593] UnitPanel: IconHookup error - icon index:	59	icon size:	45	atlas:	ABILITY_ATLAS	image control:	UnitActionIcon

**Comment by LoneGazebo** [comment]
@pandasnail is this still happening?

**Comment by pandasnail** [comment]
The above is still my most recent game that lasted that far in (easy win with Mong, Korea game I was waaaaaaay ahead in tech and quit, and recked by Shaka once and Rome once as Japan and Poly). Planning to start up as Siam after I make some pizza for dinner, and they aren't usually quick winners, I'll likely have to wait until the UN, so if Shaka would kindly not show up this time, I should have data for you for in a few days.

**Comment by LoneGazebo** [comment]
Sounds grand, thanks!

**Comment by pandasnail** [comment]
Ending up getting crushed again in that Siam game, and then winning a Brazil game before getting to the bottom of the Modern, so I decided to do a test game real quick, and its still the case yeah. Same error and everything. No other mods even. 

[89035.734] UnitPanel: IconHookup error - icon index:	59	icon size:	45	atlas:	ABILITY_ATLAS	image control:	UnitActionIcon

![20161101052400_1](https://cloud.githubusercontent.com/assets/16260521/19885185/b18b50ba-9ff3-11e6-87df-636f9507a9dc.jpg)

**Comment by LoneGazebo** [comment]
That's odd. It is a vanilla promotion, no changes (by me) to the icon info for that.

**Comment by pandasnail** [comment]
I looked int PromotionChanges and everything looks normal yeah.

Do we know it worked in Vanilla? I could do a test game with no mod besides one I make to increase barrack xp only.

**Comment by Iamblichos** [comment]
You don't have these promotions in vanilla.  Antiair in vanilla have a flat free promotion against air units.

**Comment by LoneGazebo** [comment]
The issue isn't the promotion, its the icon @Iamblichos.

**Comment by Iamblichos** [comment]
I'll take a look because these all work right in mine.

**Comment by pandasnail** [comment]
Alright, well, Iamb, if you come up with something to test, let me know, this kinda test takes five minutes at most.

(Also random fact: your namesake was my Enhancing Great Prophet in that Brazil game)

**Comment by Iamblichos** [comment]
The issue here is that these were never choose-able promotions (the one's with the triangle), so they likely do not have an icon for the Unitpanel promotion selection. I recommend using a different icon here instead.

**Comment by LoneGazebo** [comment]
I'll try changing that @Iamblichos.
