### ISSUE TITLE
Heist notification

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#2556]
_1. Mod version (i.e Date - 4/23):_

12/9

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

If a great work is sttolen from you, the notification text is off.

![20160920202550_1](https://cloud.githubusercontent.com/assets/16065630/18757299/98a755f4-80f3-11e6-8801-59332a48878f.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Getting a database.log error? Those texts exist, IIRC.

**Comment by LoneGazebo** [comment]
See here: https://github.com/LoneGazebo/Community-Patch-DLL/issues/2554

**Comment by Der-Zorn-Gottes** [comment]
Will look when I get to this stage of the game again.
