### ISSUE TITLE
AI wants a foreign religion to become world religion

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2557]
Indoa is the founder of Hinduism (surprise!) but they want me to vote for Catholicism (founded by Venice):

![image](https://cloud.githubusercontent.com/assets/1358966/18761709/5cd9681a-8106-11e6-85a1-b271422d0bbb.png)

**Comment by ilteroi** [comment]
even better: they themselves voted against the proposal

![image](https://cloud.githubusercontent.com/assets/1358966/18762258/405e0036-8108-11e6-832e-5c784c9aa917.png)

**Comment by ilteroi** [comment]
another observation: i stole about 5 techologies from venice in the course of about 30 turns. too easy i think. they don't seem to employ a defensive spy although they are the tech leader. no constabulary either.

**Comment by LoneGazebo** [comment]
Techs were in a normal game? Was Venice the most vulnerable city?

**Comment by LoneGazebo** [comment]
Re: Votes, the AI will do that if they want to meddle with you.

**Comment by ilteroi** [comment]
re spies: venice has a five star rating.

re votes: i don't get it. why should they want me to support something they don't want?

**Comment by LoneGazebo** [comment]
To make other civs not like you.

**Comment by LoneGazebo** [comment]
Not saying it is perfect, but that's the way it is currently implemented. I'll look at it.

**Comment by ilteroi** [comment]
well it's a tiny game with just 4 players. the last one is the shoshone. they have been converted to catholicism. so no point in trying to stir up trouble

**Comment by ilteroi** [comment]
and i've proceeded to steal 3 more techs

**Comment by LoneGazebo** [comment]
5 star cities are crazy easy to steal from. Is he that far ahead?

**Comment by ilteroi** [comment]
right now only 3 techs but it used to be 8

**Comment by Edaka** [comment]
Re: voting - I believe it's not possible to upset anybody by voting 'Yes' for a proposal. You can only do so by voting 'No' and then have the proposal actually fail, or by proposing (but not voting for) something that certain AIs won't like. So, in this case Gandhi wouldn't really undermine Ilteroi by striking the depicted deal.

**Comment by LoneGazebo** [comment]
Yes does anger people.

**Comment by Edaka** [comment]
But it isn't reflected in the tooltip with diplomatic bonuses/maluses when hovering over the relation status with a civ, or does it? There's a clear diplomatic modifier 'You helped our proposal fail' or 'Your proposal angers them' (wording is probably inaccurate), but there isn't a 'You helped to pass a proposal that angers them' as far as I remember. Forgive me for my ignorance if I'm wrong.

**Comment by LoneGazebo** [comment]
It Isn't a listed bonus/makes actually.

**Comment by LoneGazebo** [comment]
Malus*
