### ISSUE TITLE
Can't build AI's religious wonder

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2558]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

So, I've founded my religion (Shinto) as Japan, then I've decided that my enemies on the continent (which means everyone) need to be removed/turned into 1 bad city vassals to level my army up.

I've conquered William's holy city for Protestantism after he has already reformed his religion, but I didn't see  his religious national wonder neither after the conquest nor in the list as buildable.

Is it a bug, or can you only build religious wonders if they're the majority in your cities? Or is it not buildable again after reform even upon destruction?

**Comment by LoneGazebo** [comment]
You can only build if it is your official religion.
