### ISSUE TITLE
Your ranged unit attacks city notification

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#256]
When your ranged unit attacks a city there is no notification at the top of the screen. It's like this in vanilla game too.

**Comment by LoneGazebo** [comment]
I'm not sure I understand. Are you talking about the white text that appears?

**Comment by qqqbbb** [comment]
Yes, the white text that says "Your archer bombarded an enemy spearman"

**Comment by LoneGazebo** [comment]
I'll take a look.
