### ISSUE TITLE
Can UB that civilizations do not have access to unlock buildings that requires them?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2562]
Like can it be possible for an non-Arabian civilization to build a caravansary with a bazaar in their cities rather than a market? I think it could buff Rome's UA by also allowing Rome to capture unique buildings rather than re-convert them into regular buildings.

**Comment by Iamblichos** [comment]
It'd be a cool CIV/player trait to add to the DLL that when you capture a capital you can build that Civs uniques and keep their unique buildings.

**Comment by TechpriestEnginseer** [comment]
Well, it's more of a rather event-based suggestion. Because I have events that would destroy the default building and install in unique buildings, but the problem is that they can't build a armory if an Ikanada is in a non-Zulu city and such.

**Comment by LoneGazebo** [comment]
Rome already captures uniques like that.  And yeah you can because building class, not building type, is what matters for that check.

**Comment by TechpriestEnginseer** [comment]
![image](https://cloud.githubusercontent.com/assets/13937047/18809734/a66732e0-8238-11e6-83be-026d1f982933.png)
![image](https://cloud.githubusercontent.com/assets/13937047/18809740/bdaba04e-8238-11e6-980d-8aff7c55339f.png)
Then Stele isn't a monument-class.

**Comment by LoneGazebo** [comment]
It is. If you are usIng the BuildingClassNeededInCity it should work.

**Comment by TechpriestEnginseer** [comment]
![image](https://cloud.githubusercontent.com/assets/13937047/18810171/23438826-8244-11e6-95d4-52c23f41fa8a.png)
Nope. Non-Ethiopia Civs can't build their future buildings if a Stele is in their cities rather than a monument.

**Comment by LoneGazebo** [comment]
Just with the stele?

**Comment by TechpriestEnginseer** [comment]
With all UBs.

**Comment by LoneGazebo** [comment]
Oh I understand, you are asking about UBs connecting to buildings for non-UU owning civs. This is correct, and is a core game element that I can't (unfortunately) change.

**Comment by TechpriestEnginseer** [comment]
So, isn't Rome pretty much useless?

**Comment by LoneGazebo** [comment]
I don't believe that Rome has the problem, though perhaps it does? I don't think it does.

**Comment by LoneGazebo** [comment]
I think I actually edited it specifically for Rome's ability (it was a wonky workaround IIRC).

**Comment by TechpriestEnginseer** [comment]
Oh well.
