### ISSUE TITLE
[Question] Are lumber mills supposed to connect Coal?

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2564]
_1. Mod version (i.e Date - 4/23):_
September 19th

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Not really sure if it is bug or not. If this is supposed to happen then I have an additional question.
If Coal is supposed to be connected with lumber mills, why would I remove that improvement and build a mine? If I 'm understanding the yields correctly am I not getting more, and diverse, yields than if I built a mine?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![civ5screen0000](https://cloud.githubusercontent.com/assets/3291695/18811797/fc98b594-8300-11e6-84a3-2b214df06d7c.png)

**Comment by GrantSP** [comment]
Hmm... I'm really confused with this now. According to the toppanel resource UI this Coal tile was already connected, as I was said to have 7 Coal from it but I built a mine on it just to test and now the tootip for this tile shows coal as connected: 1F, 8P, 6G, 5Sc, 7Coal. However now the toppanel says I have 14 Coal, as though it was connected once and now it is again.

As to my secondary question, yes I think mines are better than lumber mills when Coal is found.

**Comment by GrantSP** [comment]
Nevermind, I'm reading the toppanel incorrectly. The figure for the tile next to Seoul was red, indicating a potential connection, now it is yellow and the total is 14 the confusion comes from coal being under the city and thus not immediately visible on the map.

**Comment by LoneGazebo** [comment]
Ah, gotcha. I like it when things work out in my absence!
