### ISSUE TITLE
Barbarian Hand-Axe

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#2566]
_1. Mod version (i.e Date - 4/23):_
9/19

_2. Mod list (if using Vox Populi only, leave blank):_
VP EUI set (non-modpack)

_3. Error description:_ 
I haven't seen Barbarian Hand-Axes for a while.
Do you know anything about that?

**Comment by MoiMagnus** [comment]
I think they no longer exist.
