### ISSUE TITLE
Long dead civ revived by having a Missionary returned (I think)

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2567]
_1. Mod version (i.e Date - 4/23):_
9/19

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP
Enginseer's version of E&D and Community Events
JFD Cultural Diversity Core
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Celtic City Names, Iroquoian City Names, Randomize City Names
My own thing that does various things SQL type stuff
Ice Free Coasts

_3. Error description:_ Ethiopia was dead for ages. India conquered the last Polynesia city, which happened to have a Missionary that was originally Ethi. I guess there could be a step I'm missing but somehow this ends in Ethi alive with the Missionary. They died again soon after, from either using it or it getting Attritioned I guess. Also not sure why Kamie left a Missionary alive for all that time.

(I play with the complete kills option off)

And, for the time they were alive they were getting the Religious Authority votes from their religion without the holy city. Should they?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20160925123026_1](https://cloud.githubusercontent.com/assets/16260521/18817084/8d8ce89e-8325-11e6-8135-6cb6ddc11df9.jpg)

**Comment by LoneGazebo** [comment]
Couldn't reproduce, but added check to prevent returning to a player that is not alive.
