### ISSUE TITLE
GreatScientistBeakerModifier Request, and Policy_WLTKDYieldMod Issue

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2569]
First, I'd like to request **GreatScientistBeakerModifier** to be added to the Policies table, with support for negative values if possible (not critical and understandable if not possible, however). It currently exists in the Buildings table, so hopefully can be easily transferred.

Second, I think **Policy_WLTKDYieldMod** isn't working. I have a policy that should give +15% Faith and -15% Food (and a policy that gives the reverse). Food does work as a positive, but Faith doesn't, and neither work as a negative. Additionally, if **city:GetModFromWLTKD()** is supposed to return these values, then it doesn't work either (same goes for Building_WLTKDYieldMod). Could you look into this?

This is on the 19th September CP.

Thanks for any help.

**Comment by LoneGazebo** [comment]
Alright, lua for WLTKD stuff fixed. Adding GreatScientistBeakerModifier now.

**Comment by JFDaly** [comment]
Brilliant, thank you.

**Comment by LoneGazebo** [comment]
Uploaded for testing. Link here:

https://www.reddit.com/r/civvoxpopuli/comments/55blyq/new_beta_version_september_30th_930/

**Comment by JFDaly** [comment]
Yup, works. Thanks again.

**Comment by LoneGazebo** [comment]
Nice!
