### ISSUE TITLE
TXT_KEY_TP_CARNIVAL_EFFECT

### ISSUE THREAD

**Issue by Chagui-** [LoneGazebo/Community-Patch-DLL#257]
it has a </Text> at the end that breaks MPMPM functionality.

**Comment by LoneGazebo** [comment]
Has a what at the end?

**Comment by Chagui-** [comment]
oh sorry, it didnt appear xD.

'Because of your unique Carnival bonus, Tourism output is currently +100% with all civilizations and you are earning Great People 50% faster.< /Text>'

It has a < / Text >

**Comment by LoneGazebo** [comment]
Got it, I’ll fix.
G
