### ISSUE TITLE
[Request] Hidden Garrison (graphic)

### ISSUE THREAD

**Issue by Heinous-Hat** [LoneGazebo/Community-Patch-DLL#2570]
Request: Hidden garrison [graphic]

A long time ago (at G&K release, I think) Firaxis removed the 'garrison' button and opted for automatic garrison by any unit present in a city.  As a side effect, the garrisoned unit is no longer hidden. This creates a fair amount of visual clutter that we were better off without, imho.

Any way to return to the old visual behavior? Or for that matter, simply hide all units in a city? I believe units in cities are actually hidden by default until they are selected.

**Comment by Iamblichos** [comment]
I think that's probably good idea. I kind of liked the vanilla hidden garrison graphic after you selected to garrison the unit.

**Comment by Heinous-Hat** [comment]
I wouldn't mind it as a mod (since someone would probably complain), but I'm guessing it isn't handled in lua.  At least, I don't see it in any of the UI scripts.

**Comment by LoneGazebo** [comment]
The element we are looking for is gDLL->GameplayUnitVisibility - seems that when Firaxis added invisible units in G&K it broke this. I guess we could have it check for garrision status before 'enabling' or 'disabling' visibility in this way.

**Comment by Heinous-Hat** [comment]
Ah, I see it there in cvUnit... they're supposed to be hidden on entry.

Can't remember how it worked previously... did it apply to all units, including civilian, GPs etc? I think it would be good to hide all, unless there's an animation/action. A clean city model is so much nicer, especially if you're hunting for wonders and such.

Thanks for considering the request :)

**Comment by LoneGazebo** [comment]
It applies to all units that enter the city, however I think the issue is that there's an 'invisibility check' that reveals them. May not be possible with current system.

**Comment by Iamblichos** [comment]
I see so since gDLL->GameplayUnitVisibility is kicked in for units that have the Invisible submarine promotion. I'll see what I can do to work around this.

**Comment by Iamblichos** [comment]
Working on this today, trying some new things out from viewing the pre-G&K code. I'm probably going to get it to work, bad news is, is that it might not be desirable. Will post screenshots and we can see if this is a game improvement.

**Comment by Iamblichos** [comment]
Well I managed to get the unit to go invisible when it enters (for a brief moment), and then the game engine then updates it to visible, don't think this is going to happen because there's something in the game engine code that is overriding it.

**Comment by LoneGazebo** [comment]
prolly the graphical DLL. Let's revert and close.

**Comment by Iamblichos** [comment]
Yep and I don't see any point going forward here. Spent a good 7 hours trying to fix this and the promotion issue and I believe they are both dead ends.

**Comment by LoneGazebo** [comment]
Dang! I hate dead ends. Thanks for work on this.
