### ISSUE TITLE
Minor issue with embarked unit withdrawing onto land and thinking it is still embarked

### ISSUE THREAD

**Issue by Alaric410** [LoneGazebo/Community-Patch-DLL#2574]
Version 1.9.19.0 (9/19).

Vox Populi and Quick Turns.

Very minor (and likely rare) issue, but figured to post as the fix may be easy.  My Scout has the Survivalism III promotion and when it was attacked by a barbarian naval unit, it withdrew...onto land.  I'm not sure if this was intended as a possibility, but it's the next bit that appears to be the possible (but minor) bug.  

While the scout was now on a land tile, it still thinks it is embarked.  If I hover over it, it has (Embarked) after the number of hit points and the unit does not heal (that was what brought the issue to my attention).  I moved it around on land tiles but that didn't fix it - it only resolved when I went back onto a water tile and then onto land again.  I'm guessing there is some sort of flag for "embarked" that didn't get toggled when the unit went onto land as part of a withdrawal.

The attached save game is from the period where it was in the confused state of being on land but thinking it was embarked (i.e. before I fixed it be going back into the water and onto land again).  The scout in question is located on the same island as the city state of Lhasa.

[AutoSave_0160 AD-1000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/497232/AutoSave_0160.AD-1000.zip)

**Comment by LoneGazebo** [comment]
Weird. @ilteroi we should probably disallow that promotion's effect for embarked units, eh?

**Comment by Iamblichos** [comment]
Can probably just do a check in CanWithdrawFromMelee for !isEmbarked(), won't affect ships that have that promotionentry since they aren't embarked.
