### ISSUE TITLE
Tagging Events

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2575]
As we know the event features is great, but there is a problem. How do players know which event was made by who?

@LoneGazebo, @JFDaly, @Hokath, and whoever is making events...
 should we tag events with brackets on who made it, so it is easier to diagnose who made it and give feedback on them or would this create too much of a popularity contest on who has the better events?

**Comment by JFDaly** [comment]
All of my events are tagged JFD_ - everything is that I add across my mods for that matter. I think it would be a good idea for others to do this, too.

**Comment by TechpriestEnginseer** [comment]
I meant graphically in-game rather than just code-wise.

**Comment by LoneGazebo** [comment]
i.e. like the little symbols on cards in a LCG to symbolize expansions? I guess we could add a little mark to the event popups...

**Comment by TechpriestEnginseer** [comment]
Yeah that could work.

**Comment by Hokath** [comment]
if you think it would really help matters

**Comment by LoneGazebo** [comment]
@JFDaly would this be useful?

**Comment by JFDaly** [comment]
Hm, I dunno. This might be immersion-breaking. Is there really that great a need?

**Comment by Iamblichos** [comment]
I'd leave it anonymous as is. Better energy spent elsewhere. Nothing else in the UI claims a unique author.

**Comment by LoneGazebo** [comment]
If only for debugging- not really essential.

**Comment by TechpriestEnginseer** [comment]
Now that I think about it, it's just a simple problem for too much hassle. Thanks for the feedback!
