### ISSUE TITLE
Autosaves and AI 'double turns' in MP

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#2576]
@ilteroi and @Iamblichos,

Let's solve this. I see this line in CvGame::Read:

```
//when loading from file, we need to reset m_lastTurnAICivsProcessed 
//so that updateMoves() can turn active players after loading an autosave in simultaneous turns multiplayer.
m_lastTurnAICivsProcessed = -1;
```

Seems, however, that this isn't happening. If you load ANY save, the AI gets to take a turn before the human player does, effectively skipping a human turn in the process.

Thoughts?

**Comment by ilteroi** [comment]
this is the signature for the function creating the save:

AutoSave(bool bInitial = false, bool bPostTurn = false)

notice the second flag. it's called in several places.

for manual play, we have

	case CONTROL_ENDTURN:
	case CONTROL_ENDTURN_ALT:

			if (!isNetworkMultiPlayer() && kActivePlayer.isHuman() && GC.GetPostTurnAutosaves())
			{
				gDLL->AutoSave(false, true);
			}

in autoplay mode, it's handled differently (before turn processing)

	if(getAIAutoPlay())
	{
		gDLL->AutoSave(false);
	}

and then in networked games again differently (after turn processing)

	if(isNetworkMultiPlayer())
	{//autosave after doing a turn
		gDLL->AutoSave(false);
	}

so there are different kinds of autosaves and i don't know if it's possible to tell them apart when loading

**Comment by LoneGazebo** [comment]
Think it would hurt to set that flag in the post turn call?

**Comment by Iamblichos** [comment]
This is just an issue with Simult/Hybrid right? Could we just differentiate that out above for that type of game?

**Comment by LoneGazebo** [comment]
I think so, yep. So perhaps?

**Comment by Iamblichos** [comment]
We'll have to experiment (I think), but let's start just adding in the post turn flag to true.

**Comment by LoneGazebo** [comment]
And so I have done it.

**Comment by Adonis-VII** [comment]
This issue is still around in the May 26th 2017 version. My friend and I play on epic, so our games usually last through a couple updates. We played a couple separate sessions, making saves as we go. We normally just load the last save from previous session and go from there. We noticed on our last session that all saves from the previous session would do a double turn on load, so we tested a number of them.

>302 - Double
302 - Works
298 - double
295 - double
292 - double
285 - double
283 - works
279 - double

Here is dropbox link to modpack and saves.
https://www.dropbox.com/s/0l4ji9dsy7jnm5i/Civ%20Double%20Turn%20Adonis.7z?dl=0

**Comment by LoneGazebo** [comment]
Are you loading quick saves, autosaves, or real saves?

**Comment by Adonis-VII** [comment]
They are all real saves. After many years of Bethesda games, I've grown to distrust autosaves.

**Comment by InapropriateUsername** [comment]
Me and my friend have this issue too, i didn't post it cause i thought it is an unfixable bug from vanila. Happens with all types of saves like 90% of time

**Comment by LoneGazebo** [comment]
Supposedly if you save, and then save again immediately (overwriting the save) it solves the issue. Care to test?

**Comment by InapropriateUsername** [comment]
Yes, sure, as soon as i will have time

**Comment by Adonis-VII** [comment]
We'll test this weekend.
