### ISSUE TITLE
Wat yields

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#2577]
_1. Mod version (i.e Date - 4/23):_ 
9/21 modpack 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Siamese unique building Wat gives you +1 culture when you're playing. When you are choosing a civ however, the screen from which you choose the civ and civilopedia say that Wat gives 4 culture.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20160929123526_1](https://cloud.githubusercontent.com/assets/18663580/18949358/c142009a-8643-11e6-86bb-98cf01c42619.jpg)
![20160929123528_1](https://cloud.githubusercontent.com/assets/18663580/18949371/ca6d9814-8643-11e6-9bf5-03ef6d4d83c2.jpg)
![20160929123605_1](https://cloud.githubusercontent.com/assets/18663580/18949380/d0c5e2f2-8643-11e6-9fae-b9f8577b77e2.jpg)
![20160929123613_1](https://cloud.githubusercontent.com/assets/18663580/18949382/d5de8f6e-8643-11e6-98a1-de4f421317a3.jpg)

**Comment by LoneGazebo** [comment]
Sounds like an EUI quirk.
