### ISSUE TITLE
Missing Great Diplomat points

### ISSUE THREAD

**Issue by gstew32** [LoneGazebo/Community-Patch-DLL#2578]
_1. Mod version (i.e Date - 4/23):_ Version 9-19

_2. Mod list (if using Vox Populi only, leave blank):_

Full VP with Info Addict

_3. Error description:_ 
I built the Roman Forum as the Iroquois a few turns ago and noticed that while I did receive a great diplomat my capital is not producing great diplomat points.  I cannot see great diplomat points listed as being earned in my capital (where I built the Roman Forum) nor on the GP list.

Further, after completing my scrivener's office and assigning a worker to work the GP slot, I still do not get any points toward Great Diplomats.

_4. Steps to reproduce (optional):_

[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/500854/Lua.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/500853/Database.zip)

[Hiawatha1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/500857/Hiawatha1.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict (i.e. the Great Diplomat bar simply isn't appearing in your cityview).

**Comment by gstew32** [comment]
I will attempt to reinstall and see what happens.  Considering that I have only been playing VP (through various versions) successfully I don't see what mod could be conflicting.

**Comment by gstew32** [comment]
Is there a quick way after reinstall to see if everything is working correctly?  Or do I need to play and wait till I can start to earn Great Diplomat points...

**Comment by LoneGazebo** [comment]
After reinstall you should be able to load your save. If you can't then it was definitely a bad install.

**Comment by gstew32** [comment]
Sigh.... I deleted and cleared the file assuming that i would need to start a new game.

**Comment by gstew32** [comment]
After a reinstall of v. 9-19 on a new game I was able see Great Diplomats being created when I built the Roman Forum.

Must have been a bad install the first time.

**Comment by LoneGazebo** [comment]
Sounds like it. I'm guessing a missing compatibility mod. Glad it is working!
