### ISSUE TITLE
damage vs embarked meele/ranged units

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2579]
_1. Mod version (i.e Date - 4/23):_
9/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
ranged/siege units can almost instakill embarked meele units( thats how it has been all the time) but have to spend about 4-5 shots for embarked skirmishers. some says all ranged units. so is this intended? is there some hidden defense moddifier for ranged units while embarked?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Thanks, will point @ilteroi to this.

**Comment by ilteroi** [comment]
can confirm there's a difference. question is, which behavior is the correct one?

from the code it seems that the "weak" defense should apply to ranged units as well. but then that would make embarked units easy prey again.

**Comment by Iamblichos** [comment]
Somewhere in the middle would be best I think.

**Comment by ilteroi** [comment]
i think i found a happy medium ...

**Comment by LoneGazebo** [comment]
Awesome. I've also got a major amount of updates to upload. Want me to do so now?

**Comment by Iamblichos** [comment]
Me too. Ton of updates. But I'm going to wait until next go around.

**Comment by LoneGazebo** [comment]
What all do you have @Iamblichos ?

**Comment by Iamblichos** [comment]
Mostly new stuff: Traits, Convertible domain units from land to water : water to land, Unitpromotion garrison yields, bunch of bugfixes here and there. But it can wait.

**Comment by Iamblichos** [comment]
I'm thinking about rewriting SetXY...that thing is a f'ing mess.

**Comment by LoneGazebo** [comment]
Fun! I've got the naval AI working quite well. For example:

![20160930161938_1](https://cloud.githubusercontent.com/assets/7849458/19005660/c1970a54-8729-11e6-9181-33d5c0ac8e52.jpg)
![20160930161944_1](https://cloud.githubusercontent.com/assets/7849458/19005661/c199ae12-8729-11e6-9d8d-50b7c466fe7e.jpg)
![20160930161930_1](https://cloud.githubusercontent.com/assets/7849458/19005659/c1968ade-8729-11e6-8ae0-8005d4f025bc.jpg)

**Comment by LoneGazebo** [comment]
Shame that it sounds like Civ 6's AI is still abysmal. Schooled by a team of after-hours programmers... :)

G

**Comment by Iamblichos** [comment]
Did you watch some gameplay with Civ 6 AI?

**Comment by LoneGazebo** [comment]
Yeah, the tactical AI is laughable. Lingers around, does nothing. Religion AI for a civ bought missionaries from two competing religions in two different cities and sent them to same city, flipping city back and forth. And so on.

**Comment by Iamblichos** [comment]
Re:  Missionaries. Oh that's brilliant. Just like a human player would do. Real good coding.

**Comment by LoneGazebo** [comment]
Well this is tragic. I have a new version ready to go but civfanatics is down. I'll probably post a link in the voxpopuli subreddit.
