### ISSUE TITLE
CP Only - Trading Post logic

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#258]
Version 4-15, the automated worker loves to put trading posts everywhere, and I don't mean just around gold-focus cities. Hills, forests, etc. It's poor play, and I suspect why city states don't seem to grow very large (previously reported) as they seem especially prone to it. Could this be because of logic from CBP, where trading posts function differently, being accidentally in the CP?

**Comment by LoneGazebo** [comment]
The logic regarding working placement is based on yield deltas b/w what the tile has and what it might have with the new potential improvement – there's no 'special code' for trading posts in that regard. It sounds like the AI is simply prioritizing gold deltas too much within the XML.
G

**Comment by Hokath** [comment]
Ah sounds like a bit of a balancing act. Up to you what to do with it.

**Comment by LoneGazebo** [comment]
I've edited the XML a bit to reduce interest in gold. We'll see if this helps a bit.

**Comment by Hokath** [comment]
Will let you know in my next game.
