### ISSUE TITLE
AI city selection seems odd?

### ISSUE THREAD

**Issue by GrantSP** [LoneGazebo/Community-Patch-DLL#2580]
_1. Mod version (i.e Date - 4/23):_
September 19th

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Very early game and I (Spain) took offence at the Mongols showing up so close and decided to start a war. Although it is very early on, I decided to start to build some forward cities to take advantage of the good Iron deposits.
Surprisingly they didn't, despite also having the necessary tech.
It seems to me odd that they would settle Turfan where they did when several better options are available, both with a view to resources, and strategically.
Settling to the NE of Belgrade would provide them with a *6 Iron tile and possibly Bison and Wheat as well as hindering my expansion towards the Jade rich hills further East.
Turfan at best gives them only that Wheat tile and possibly a coastal city. There are still much better coastal options than that.

So my question(s) is/are this/these:
Are the AI players founding cities with regard to future more important resources, Horses, Coal, Oil, Uranium etc. and not just on those that are available to them now?
Which leads to: does the AI know of ALL future resource locations without having to research it?

_4. Steps to reproduce (optional):_
![civ5screen0000](https://cloud.githubusercontent.com/assets/3291695/18977219/a0d3d03c-86fb-11e6-9aee-0db433d51e4c.png)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/501958/Logs.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by GrantSP** [comment]
Update:
Played a bit longer until I researched for Horses and it may be that this is the reason for the settlement.
There are 2 Horses within Turfan's boundaries and a 3rd city founded by them is also placed to pick up more Horses.
So it now looks like the settlement isn't so odd afterall. Clearly this is similar to all the forum questions posed by users with similar situations.

Still would like to know if the AI has knowledge of ALL resources regardless of research?

**Comment by ilteroi** [comment]
just checked. it seems the AI sees all the resources in advance. this part of the code is inherited from vanilla. would be a one-line change to set it to "revealed resources only". don't know how much of the score is determined by resources on the other hand, it's not the single dominant factor in any case.

**Comment by GrantSP** [comment]
Thank you that is very interesting. Do you reckon this makes any difference to the way the AI plays the game? ie. does it make some of the players actions: settling cities etc. more offensive since they see what we as players will get if we found a city there?
Might explain why some AI go to war over seemingly minor infractions into unclaimed territory.

**Comment by ilteroi** [comment]
afaik (but that is gazebo's turf) the "don't settle near us" message is simply triggered by proximity, it does not check "site quality"

**Comment by LoneGazebo** [comment]
That's correct @ilteroi.

**Comment by GrantSP** [comment]
Yeah I knew about the formula for settling "too close", at least with regards to the AI saying that we did. Still there may be times when the player settles on a resource rich location, yet outside that trigger zone, and the AI goes: Uh no! That's mine, prepare for war.

Any way the question is answered to my satisfaction. Thank you.
