### ISSUE TITLE
make carrier a ranged unit

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2582]
right now the carrier is melee, causing the AI to put it on the front lines. we should make it a (weak) ranged unit with the corresponding AI class instead, so it will stay in the back.

**Comment by Iamblichos** [comment]
Yeah it does put it up front. Weird since its AI is escort.

**Comment by LoneGazebo** [comment]
Makes sense.

**Comment by LoneGazebo** [comment]
Also I uploaded a bunch last night. Make sure to merge up!
