### ISSUE TITLE
Puppet AI broke again? 

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2583]
_1. Mod version (i.e Date - 4/23):_

30/9 (or 1/10?) (I saw you hackers doing weird code things, ensuring me you would download a car, so I used download in the <>CODE area and put the folders that were changed 20~ hours ago inside my 19/9 folders. The mod works. I can into merge...?!)

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description:_ 

Get a puppet.

It's gonna go full Food + Gold focus. Indian city refused to build Monuments/Councils/Barracks after it got Walls + Granary up, forcing me to annex in very early classical era.

**Comment by thunderbird14** [comment]
Try to reproduce the bug in the new beta version: https://www.reddit.com/r/civvoxpopuli/comments/55blyq/new_beta_version_september_30th_930/ .

**Comment by Enrico-Swagolo** [comment]
Had no clue there was a reddit of the mod

Will try again with the proper version
