### ISSUE TITLE
AI doesn't buy Spaceship parts

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#2584]
_1. Mod version (i.e Date - 4/23):_

9/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Venice had tons of money, all the techs and a boatload of freedom tenets (I cannot tell if he had space procurements, but as hes clearly going for science victory, he should).
Anyway they didn't build/buy a single spaceship part in a game they otherwise completely domintated.

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
Probably didn't have space procurements. If you have the AI hurry log from the game I can look.

**Comment by Der-Zorn-Gottes** [comment]
There is no such thing in the logs directory. Anywhere else I could look?

**Comment by LoneGazebo** [comment]
Should be something like AI_CityProduction_Hurry or thereabout. Look for the word hurry.

**Comment by Iamblichos** [comment]
Ensure you have AI logging enabled in config.ini.
