### ISSUE TITLE
UnitFreePromotion Issue

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2585]
If you have a unit spawn on an improvement that has an UnitFreePromotion due to a policy or a wonder, it'll apply the same promotion to all future units even if it's not created on an improvement.

**Comment by LoneGazebo** [comment]
Eh?

**Comment by Iamblichos** [comment]
Policy and Wonder promotions are player "wide" I believe.

**Comment by TechpriestEnginseer** [comment]
Never mind, I can't replicate it anymore.  (I was replicating for 3 random games) Probably random mod conflict or something.
