### ISSUE TITLE
City choices

### ISSUE THREAD

**Issue by Zoidbergesq** [LoneGazebo/Community-Patch-DLL#2587]
_1. Mod version (i.e Date - 4/23):_
September 19th

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When I get the city choice event, "Old Men and the Sea", I am able to choose "I'd rather invest in infrastructure" despite not having the requisite 600 gold. I had 460 but I was still able to choose this option, after which I was left with 0 gold and a harbor. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Running on quick speed?

**Comment by Zoidbergesq** [comment]
Nope - marathon.

**Comment by Zoidbergesq** [comment]
Do you know why this might be happening? And, also, might it be happening to other similar such city choices?

**Comment by LoneGazebo** [comment]
My only guess is that you've got a modified game speeds file. As the code grabs values from that file.

**Comment by Zoidbergesq** [comment]
No, nothing like that. Is it not just that the event has been coded so that the spend is "-600", so that even if you don't have it it doesn't minus into negative figures. There was somethign a bit weird in the wording of it..

**Comment by LoneGazebo** [comment]
The event grabs a scaled value from the DLL so the numbers are all database values. I'll look at the gamespeed ordering.

**Comment by Zoidbergesq** [comment]
Ah, that makes sense; good idea!
