### ISSUE TITLE
thrift broken

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2588]
_1. Mod version (i.e Date - 4/23):_
9/30 beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
thrift doesnt provide gold based on every followers, actually it providing 1gold per 2 followers. if this is change, it wasnt in changelog.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
That's the way thrift always was, IIRC.

**Comment by ashendashin** [comment]
It was changed to 1 per follower in 8/8.

**Comment by LoneGazebo** [comment]
Oh yeah, I remember now.

**Comment by LoneGazebo** [comment]
Looked at code, not set to 'halved followers' as of 8/8. You sure you aren't mistaken, @matlajs ?

**Comment by matlajs** [comment]
man i shuted game down now. but ye, im sure. i have 1 per 2followers in every city, tomorrow i will provide some screenshot. also i have some weird math in monopolies. its a first game in this version, and first game with planet simulator,no other changes in mod settings.

**Comment by matlajs** [comment]
here are some screens. i have  thrift and spirit of desert believes(should be counted as terain yield) producing gold and while all other cities has just 1 per 2 followers, my capital has some rly strange numbers there.  

![thrift1](https://cloud.githubusercontent.com/assets/21192402/19110771/3c44ea20-8afc-11e6-8b02-ab6ce996fb4b.jpg)
![thrift2](https://cloud.githubusercontent.com/assets/21192402/19110779/42b2c7f6-8afc-11e6-9f95-f322ad2a21e9.jpg)
![thrift3](https://cloud.githubusercontent.com/assets/21192402/19110780/476dda60-8afc-11e6-8699-3f3830a59f11.jpg)
![thrift4](https://cloud.githubusercontent.com/assets/21192402/19110782/4c244eae-8afc-11e6-9e6e-c9ed1d03cfb9.jpg)

**Comment by LoneGazebo** [comment]
I'll look.
