### ISSUE TITLE
Civilians still count towards your supply cap

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#259]

**Comment by LoneGazebo** [comment]
I'll check into it – the game checks supply cap in two locations, so I wonder if the supply function I edited is somehow being overwritten,

**Comment by LoneGazebo** [comment]
To be clear, are you talking about gold maintenance, or unit supply?

**Comment by qqqbbb** [comment]
Unit supply.

**Comment by LoneGazebo** [comment]
Yes. I'll look. I bet it is the redundancy I mentioned.
