### ISSUE TITLE
Indonesia bug?

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2592]
_1. Mod version (i.e Date - 4/23):_

9/30
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

indonesian special promotion Recruitment doesnt work together with Logistic policy. tested it twice vs barbarian, unit doesnt heal.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
They are mutually exclusive by virtue of how the DLL works. Can't adjust that.

**Comment by matlajs** [comment]
ok so just for information, it will ever prioritize indonesian promotion without logistic taking effect even for non-barbarian unit?

**Comment by LoneGazebo** [comment]
Eh?

**Comment by matlajs** [comment]
i will rather try it myself, even i didnt want DoW anyone.
