### ISSUE TITLE
more bugs

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2593]
![bug1](https://cloud.githubusercontent.com/assets/21192402/19133688/e12049b0-8b59-11e6-919b-a41e8c7bfb5d.png)
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
bug1- Global commandments believe doesnt provide said culture on passed proposal(tested and calculated 2 times)
bug2- Gustavus builded Parthenon without Progress- wtf?
![bug2](https://cloud.githubusercontent.com/assets/21192402/19133680/d9a1e3b0-8b59-11e6-9c7c-1d687e42f686.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
He probably captured the Parthenon.

Re: WC reformation, it works for me.

**Comment by matlajs** [comment]
that reformation works, but not properly. there is one more with this problem. he posted in 9/30 thread on civfanatics.

**Comment by matlajs** [comment]
any progress with Global commandments issue @LoneGazebo ?

**Comment by LoneGazebo** [comment]
@matlajs yeah, a simple SQL typo. Fixed for next version.
