### ISSUE TITLE
Dromon gets more RCS unreasonbly

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#2598]
_1. Mod version (i.e Date - 4/23):_

9/30

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Dromon gets 12 RCS in a game. After a few startup and cache cleaning, it gets 14 RCS, Though, I haven't explicitly observe.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I increased dromon RCS in latest version.

**Comment by MoiMagnus** [comment]
Changelog said "Buffed RCS on Dromon by 1, CS on Trireme/Galley/Quinqureme by 1", and it seems here to be "increased from 12 to 14". Is it normal ?

**Comment by XplosiveLun** [comment]
I don't clearly remember how it transform from 12 to 14.

Here's the prove.
http://images.akamai.steamusercontent.com/ugc/261597859308237304/A6A6D155209A4C044519201FA2AFF2EBD86E88FC/

**Comment by LoneGazebo** [comment]
No idea. Can only assume mod conflict.

**Comment by XplosiveLun** [comment]
I tried clearing cache and enable only Vox Popuil. Still the same.

**Comment by LoneGazebo** [comment]
Ah, I see, somehow dromon got bumped to 14 RCS. Should be 13. I'll fix for next.
