### ISSUE TITLE
God of Expanse bonus when city border grows suddenly stopped working

### ISSUE THREAD

**Issue by Navanod** [LoneGazebo/Community-Patch-DLL#2599]
_1. Mod version (i.e Date - 4/23):_9/30 beta

_2. Mod list (if using Vox Populi only, leave blank):_City limits v7, FlagPromotions v7, Historical Religions Edit v45, Improved City View for VP with EUI v9, InfoAddict v22, Quick Turns v10, Wondrous Nature v2

_3. Error description:_ Noticed faith wasn't increasing as it should when borders grew, loaded older saves to confirm. Found that the bonus stopped at turn 98, the last border growth before bug was at turn 95, where the bonus was given normally.

_4. Steps to reproduce (optional):_I am replaying this map by loading the 1st save and this issue did not occur in the last play-through. On turn 98 when the bug started, 3 events occurred. The discovery of the 2nd part of the Great Barrier Reef, discovery of tech (writing) and completion of monument at the city that had the border expansion, caused by the 10 bonus culture from Organization (Progress). I had ruled out the Great Barrier Reef by going back and discovering it earlier to see if it can cause the bug at turn 95. It did not.
I tried loading earlier auto saves and changing things around but the bug always happens when that particular city's (Turfan) borders first expands. I have attached the save from turn 95 which should reproduce the bug at turn 98.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Genghis Khan_0095 Prebug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/514300/Genghis.Khan_0095.Prebug.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20161007020244_1](https://cloud.githubusercontent.com/assets/22663272/19160432/63effb0a-8c37-11e6-88e5-0bc9b69f91ca.jpg)
![20161007020536_1](https://cloud.githubusercontent.com/assets/22663272/19160433/63f584f8-8c37-11e6-9c55-0f2b7639cb22.jpg)
![20161007020755_1](https://cloud.githubusercontent.com/assets/22663272/19160434/63f61d3c-8c37-11e6-891a-619ff26067d8.jpg)
![20161007013132_1](https://cloud.githubusercontent.com/assets/22663272/19160437/6409c170-8c37-11e6-8030-94854e073df1.jpg)
![20161007013442_1](https://cloud.githubusercontent.com/assets/22663272/19160435/63fbbdf0-8c37-11e6-9ae4-ce294eb52597.jpg)

**Comment by matlajs** [comment]
thats not bug. i found those cities after  you found religion. u havent there pantheon.

**Comment by Navanod** [comment]
OMG! I had a nagging feeling I forgot something!
Can't believe I missed that. Very sorry!
Getting so used to seeing all the bonuses I forgot entirely.
I really need to stop late-night civ gaming...the lack of sleep is starting to show!

**Comment by LoneGazebo** [comment]
No worries! Thanks @matlajs for fielding this one :)
