### ISSUE TITLE
new branch

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2601]
just pushed a new branch with a substantial rewrite of the tactical AI. not production ready, but if anyone wants to give it a spin, please post comments / observations here.

they way it works is that for a set of units trying to attack a target, multiple combinations of moves are simulated and the best one is chosen. that is, general bonuses and flanking bonuses should be maximized.  melee units should make way for ranged units, etc.

example debug output. the root node is the inital setup, the leaf nodes are the evaluated possibilities.
[graph.dot.svg.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/514883/graph.dot.svg.zip)

performance is about 20ms for 4 units in a debug build. quite acceptable. still the work is not finished, the current integration with the old code is geared towards backward compatibility, in the long run a lot of legacy code could be removed.

**Comment by LoneGazebo** [comment]
That is some impressive engineering, @ilteroi. Good news is that I'm freeing up a LOT of performance in the DLL using caching, so feel free to use a bit more for your tactical masterplan.

**Comment by ilteroi** [comment]
i also posted two small bugfixes in fefe branch in case you didn't see

**Comment by LoneGazebo** [comment]
Cool, I'll merge. I also posted a branch (Unstable branch) and I need help debugging it. I'm getting a crash on exit (random location in the uninit cycle for cvplayer), and also on loading a save. I think it is to do with my new caching model for the military AI (see line 409 of CvMilitaryAI). If you, @ilteroi, or @Iamblichos want to help debug that'd be great. Could also be an issue with save/load for player level contracts (seen a crash there too). Any thoughts would be great.

Goal of CvMilitaryAI cache for distance is to limit the number of calls we make to 'getnumplotsinpath' in the getbesttarget function.

**Comment by ilteroi** [comment]
why do you save the cache? isn't it enough to regenerate it on load? or use simple memoization?

**Comment by LoneGazebo** [comment]
@ilteroi

Okay, I'll skip saving and loading. I was afraid it would compromise performance. 

I'm still getting a crash on exit, and have been for a few versions. Not a huge deal I guess.

**Comment by ilteroi** [comment]
funny observation - terrain doesn't really matter anymore. buildings do!

![image](https://cloud.githubusercontent.com/assets/1358966/19203802/a5437f62-8cd9-11e6-9e03-485da46f6c58.png)

admittedly an extreme case but still i often find that cities don't work most of their plots. don't know if that is intended.

**Comment by LoneGazebo** [comment]
on the latest branch?

**Comment by LoneGazebo** [comment]
unstable*

**Comment by ilteroi** [comment]
my unstable, not yours. but it has been like that for quite a while. it's not a problem of the city governor, it's just that a lot of food is received from buildings etc, not from terrain. it's a hard balance to strike, especially considering all yields, not only food.

**Comment by Iamblichos** [comment]
@LoneGazebo, exit the game or exit to main menu or both?

**Comment by LoneGazebo** [comment]
exit game from game, or exit game and go menu. Either way it crashes. Random location too.

**Comment by LoneGazebo** [comment]
Was not crashing prior to your second-latest merge @Iamblichos.

**Comment by LoneGazebo** [comment]
Alright, found the crash spot (consistent):

![untitled 2](https://cloud.githubusercontent.com/assets/7849458/19209441/67e0d062-8cd8-11e6-8ddc-bc7ba5661b65.png)
![untitled 3](https://cloud.githubusercontent.com/assets/7849458/19209442/67e29e4c-8cd8-11e6-8e19-b4d0dd8205dd.png)
![untitled](https://cloud.githubusercontent.com/assets/7849458/19209440/67dfe242-8cd8-11e6-8e96-a507f6ccc25d.png)

**Comment by LoneGazebo** [comment]
It is  m_cities.RemoveAll(); that is causing it. Not sure why...

**Comment by Iamblichos** [comment]
Only thing I did in that latest that could affect it is recomputegreatperson modifiers from CvPlayer.

**Comment by Iamblichos** [comment]
Can't check at the moment but will later.

**Comment by LoneGazebo** [comment]
I checked my added code and I see nothing. Hrm.

**Comment by Iamblichos** [comment]
@LoneGazebo I'm not getting this on my latest changes and starting a game fresh and then exiting game entirely or main menu. Does this happen for you on Turn 0 or this happening while you have done a significant amount of turns or either?

**Comment by LoneGazebo** [comment]
which latest changes?

**Comment by LoneGazebo** [comment]
it doesn't matter - always crashes on exit.

**Comment by Iamblichos** [comment]
My last pull request to master...but I'm not working from the Unstable branch.

**Comment by LoneGazebo** [comment]
Did you make any memory additions to CvPlayer?

**Comment by Iamblichos** [comment]
I do in CvTraitClasses.cpp and by dint of that CvPlayerTraits...but not CvPlayer itself, no.

**Comment by LoneGazebo** [comment]
Mind making sure you've dotted all t's and crossed all i's? I'm looking at my code now to see if I missed a memory clear/reset...

**Comment by Iamblichos** [comment]
Might be these...need to add them to MOD_SERIALIZE_READ and MOD_SERIALIZE_WRITE


```
kStream >> m_piNumPledgesDomainProdMod; 
kStream >> m_piFreeUnitClassesDOW; 
```

 
```
kStream << m_piNumPledgesDomainProdMod; 
kStream << m_piFreeUnitClassesDOW; 
```

**Comment by Iamblichos** [comment]
m_eFreeUnitOnConquest looks like it needs to be reset too.

**Comment by LoneGazebo** [comment]
Did that fix it?

**Comment by Iamblichos** [comment]
Using Master as my baseline and the changes I did, I sim'ed a game up to around turn 190 and exited to main menu several times, never crashed except once resulting in this, don't know if it looks familiar to what you had:

![untitled](https://cloud.githubusercontent.com/assets/14372214/19216776/d63f5aa8-8d8f-11e6-9839-adbc735cd16d.png)

**Comment by Iamblichos** [comment]
I was also running IGE, dunno if that contributes to it or not.

**Comment by LoneGazebo** [comment]
Might. I've made the changes above, I'll see if that fixes the problem.

**Comment by Iamblichos** [comment]
You mentioned earlier you've been getting this from the last few version, right? Do you remember what version it started at?

**Comment by LoneGazebo** [comment]
Fixed. :)

**Comment by Iamblichos** [comment]
Alright! It was those changes?

**Comment by LoneGazebo** [comment]
Something else.

**Comment by Iamblichos** [comment]
Yeah I saw you did some clearing out in CvPlayer.cpp was wondering if that had something to do with fixing it. Good to know.

**Comment by LoneGazebo** [comment]
I think it was a mix of both.
