### ISSUE TITLE
GetArea Issue.

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2602]
@ilteroi 
In Firetuner under the InGame Pulldown using
Map.GetPlot( UI.GetMouseOverHex() ):GetArea();

Returns 1216 for Ocean and 1217 for Coast

They should be the same. This will affect subs firing to target plots that are different than its source plot, might affect other things too.

**Comment by ilteroi** [comment]
nice trick but cannot confirm

**Comment by LoneGazebo** [comment]
I wonder if it is a mapscript issue - @Iamblichos what map?

**Comment by Iamblichos** [comment]
Hmmm...I dunno...strange. I have a modified AssignStartingPlots that adds in titanium on coast but I'm not modifying any plot indexes....not sure.

**Comment by Iamblichos** [comment]
I'm just using the standard map scripts that come with the game.

**Comment by Iamblichos** [comment]
Well I loaded in an unmodified starting plots from CP, still got a different area number for coasts and ocean. WTF.

**Comment by Iamblichos** [comment]
I found it. I had this set to this:
UPDATE Terrains
SET Impassable = 1, PassableTechTerrain = 'TECH_ASTRONOMY', TurnDamage = 10
WHERE Type = 'TERRAIN_OCEAN';

Not sure which one did it. First two are redundant since that is defined elsewhere. Might be the turndamage that might differentiate an area....anyways, my bad, mea culpa, kyrie eleison.

**Comment by ilteroi** [comment]
just fyi, areas are contiguous passable / impassable groups of plots. so if ocean is impassable at game start when the areas are assigned, that would be the result.
