### ISSUE TITLE
cannot raze city

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2603]
_1. Mod version (i.e Date - 4/23):_
9/30

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

i miss the option raze the city. i conquered one carthage island city and cannot do that. any idea? will provide screen later.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Holy city? Capital?

**Comment by matlajs** [comment]
any of that. thats not only problem i found. another is, that concrete city also doesnt have boredom modifier for happines. i will provide screenshots when i end.

**Comment by LoneGazebo** [comment]
concrete city? It sounds like you've got a mod conflict.

**Comment by matlajs** [comment]
mod conflict? im using  RED,faster aircraft, flag promos, really advanced setup and now playing with planet simulator. nothing else.

**Comment by matlajs** [comment]
and to adition, i dont want open new issue, but kasbah does 5 dmg to every adjacent unit + to enemy units stationed on it(same like encampment). uhh to many weird things in this version.

**Comment by matlajs** [comment]
thats the first city i conquered, but i cannot raze any conquered city(now the same issue with morocan city). those are newly founded.
![bug1](https://cloud.githubusercontent.com/assets/21192402/19202675/dfcb561a-8cd3-11e6-9b9e-b966074c3bad.png)
![bug2](https://cloud.githubusercontent.com/assets/21192402/19202685/ee39180e-8cd3-11e6-8ddb-169234dff122.png)

**Comment by matlajs** [comment]
i dont know if i shuld just start new game in this version with changed settings.

**Comment by LoneGazebo** [comment]
It only shows the 'bored' modifier in that tooltip if your city is bored.
Re: conquest issue, I need your lua.log (you should always post lua log and database log).

Kasbah damage is intentional.

**Comment by matlajs** [comment]
im afraid in this curent logs will be useless, as i reinstaled my version and started new game, sorry.

**Comment by LoneGazebo** [comment]
The other happiness tooltip should say that, IIRC.
