### ISSUE TITLE
Game crushes after liberating a Venice puppet

### ISSUE THREAD

**Issue by avl8** [LoneGazebo/Community-Patch-DLL#2605]
1. Mod version (i.e Date - 4/23): 9/30

2. Mod list (if using Vox Populi only, leave blank): -

3. Error description: After liberating a Venice puppet, you get a blank screen with a trading with AI interface. If you confirm any option, like changing embassies, game crushes immediately after you click Ok button.

4. Steps to reproduce (optional): 
my game setup was: huge continents, immortal difficulty, portugal
I chose authority policy tree and liberated a Venice puppet shortly after getting Terracota Army. 
Later, during medieval era I've liberated another puppet and again got this blank window (no leader animation, just blacnk screen) with trading AI interface (your offer, their offer etc etc).

**Comment by LoneGazebo** [comment]
Please post minidump and logs. If logging not enabled, please enable and repeat error, then post logs. Can't help w/o more information.

**Comment by TechpriestEnginseer** [comment]
It's able to be replicated when you liberate any city-states that you haven't met. (the blank screen and such)

I can't replicate the crash because you would usually just exit out without agreeing to anything.

**Comment by avl8** [comment]
In this game I havent met both Venice puppets before liberating them. Probably thats the case.
