### ISSUE TITLE
Bug when completing Terracota Army

### ISSUE THREAD

**Issue by avl8** [LoneGazebo/Community-Patch-DLL#2606]
1. Mod version (i.e Date - 9/30): 9/30

2. Mod list (if using Vox Populi only, leave blank): -

3. Error description:
When completing Terracota Army world wonder you lose some units that you build in other cities in that particular turn. 
I.e., your capital finishes TA, 2 other cities finishes catapult and horsemen in that exact turn.
On the next turn you get all copies of your units appear near your capital. But you get no horseman and catapult copies . Even more - you get no horseman and  catapult from your other cities. Its building queae is just clear, no units out :(

4. Steps to reproduce (optional):
My setup was: huge immortal Portugal continents game, authority policy tree.

**Comment by LoneGazebo** [comment]
Can't reproduce bug.

**Comment by avl8** [comment]
Id like to add my savegame with Terracota, but I get an error message everytime I try. Is there a lifehack how to properly add savegame file here?

**Comment by Edaka** [comment]
Zip it up in an archive and then add here.
