### ISSUE TITLE
inca mountain yields are crazy

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2608]
![image](https://cloud.githubusercontent.com/assets/1358966/19207838/63a40048-8cf4-11e6-9975-eac920c7971f.png)

note that some mountains are 2f2g and some others are 3f3g. water doesn't seem to make the difference ... anyway, something like 2f1p1g would be good enough, no?

**Comment by ilteroi** [comment]
very small thing, but on the zulu loading screen it shows a city called mtubatuba ... no zulu city in the game has that name. can you add it?

**Comment by LoneGazebo** [comment]
That's old code - mountains work differently now.

I can add that Zulu city, yep. :)
