### ISSUE TITLE
Flavor Diplomacy

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2613]
What factors make the AIs more willing to take diplomacy flavored event choices than everything else? Number of City-States alive or need of World Congress? I'm noticing that this flavor outflavor most general flavors with the exception of wonder flavors. (Ex. Flavor_Diplomacy of 5 somehow is chosen over a Flavor_Gold of 40)

**Comment by LoneGazebo** [comment]
Flavor diplo is tied to the needs of the World Congress.
