### ISSUE TITLE
Caravans have unlimited range

### ISSUE THREAD

**Issue by oedali** [LoneGazebo/Community-Patch-DLL#2616]
_1. Mod version (i.e Date - 4/23):_ 10/9

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ It's very early game and my caravans have virtually unlimited range.. can get to ANY city on visible map. Once I set the route, the duration was something ridiculous like 60+ turns. 
See screenshots. 
![20161009172331_1](https://cloud.githubusercontent.com/assets/20485377/19220340/8a3c4ae6-8e55-11e6-8247-104c2f829d96.jpg)
![20161009192023_1](https://cloud.githubusercontent.com/assets/20485377/19220341/8a58539e-8e55-11e6-912f-26db1b59a92c.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi - what's up?

**Comment by oedali** [comment]
Also: not sure if this is related, but also seeing very exaggerated religious pressure numbers

**Comment by ilteroi** [comment]
i didn't do it

**Comment by LoneGazebo** [comment]
I'm an idiot! :)

**Comment by LoneGazebo** [comment]
That's what I get for trying to rock a baby to sleep and debugging at the same time. I'll patchfix.

**Comment by ilteroi** [comment]
guess this is fixed then
