### ISSUE TITLE
Reformation available for non-founders?

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2619]
_1. Mod version (i.e Date - 4/23):_

30/9, but it wasn't touched so should remain like so

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

So, I've founded a religion and didn't reform it yet. I've conquered Buddhist cities of Mongolia that were conquered by Spain and I've noticed I could faith rushbuy Universities in them for free as long as Buddhism was the primary religion there. Is it intended that non-founders have access to them or not?

**Comment by LoneGazebo** [comment]
Interesting scenario. What's your official religion?

**Comment by LoneGazebo** [comment]
Ah, it was missing a belief validity check. I'll fix for next time.
