### ISSUE TITLE
28 strength cataphracts turn 14 with the hotfix...

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#2620]
_1. Mod version (i.e Date - 4/23):_ 10 - 9 - 1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

The fix still has four 28 CS barbarian cataphracts on turn 14 just next to my capital...

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Horde event probably.

**Comment by TechpriestEnginseer** [comment]
Incompatibility Issues with the my CBP E&D since the cataphracts from the persian's UD make them available at the ancient era(huge bug)

**Comment by LoneGazebo** [comment]
Thanks @TechpriestEnginseer  – sorry for the change -> bug.
