### ISSUE TITLE
Auto explore and next turn.

### ISSUE THREAD

**Issue by martin26** [LoneGazebo/Community-Patch-DLL#2621]
_1. Mod version: all of them

_4. Steps to reproduce (optional): open event notif./log, try to click next turn, doesnt work, open again event notif./log, next turn now works.

After 5-10 turns the auto explore feature does simply not work on units.

Will make a video for you guys.

Thanks.

**Comment by LoneGazebo** [comment]
Please post mod list, logs, etc. Need more information than just a video.

**Comment by martin26** [comment]
Well, do what I said to reproduce the next turn bug, and let me know.

**Comment by LoneGazebo** [comment]
That's not how bugs work. :) 

I need logs, and I need you to reproduce this for me.

G

**Comment by TechpriestEnginseer** [comment]
I remembered being able to reproduce this often in previous versions, but I'm finding it difficult to produce for me or under your steps, mind clarifying?

**Comment by martin26** [comment]
Well start a fresh game, create your city, click on the event notifications/log in the menu, try to next turn, it will bug. 

@LoneGazebo I know, I will provide them once im home thankies :)

**Comment by ilteroi** [comment]
solved

**Comment by martin26** [comment]
Thanks!
