### ISSUE TITLE
Influence dropping rapidly after liberating Venice puppet

### ISSUE THREAD

**Issue by lucperrin** [LoneGazebo/Community-Patch-DLL#2622]
_1. Mod version (i.e Date - 4/23):_ 10/9 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ I liberated Venice's puppet (Ife) and influence is dropping at high rate of 4.02/turn.  See attached save
[Ashurbanipal_0306 BC-0440.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/518650/Ashurbanipal_0306.BC-0440.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by lucperrin** [comment]
At some point the rate decreased back to normal.  By turn 317 I noticed it is back at 0.67/turn.

**Comment by TechpriestEnginseer** [comment]
Could it be possible that since you're liberating it, it starts with less than 100% HP meaning influence will decay much rapidly?

**Comment by lucperrin** [comment]
Yep, that was the issue, since I was still pledged to protect it I think.

**Comment by LoneGazebo** [comment]
Intentional – allied CSs you have a PtP with will have big influence decrease if they're damaged (because they don't feel defended).
