### ISSUE TITLE
Improvement - Shrink Citadel a little

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#2623]
I've been playing several games with slightly smaller citadels and in my opinion they look better, as the originals "bleed out" too much into other tiles. I defer to your judgement, of course.

-- Shrink Citadel
SET Scale= '0.8'
WHERE ImprovementType = 'ART_DEF_IMPROVEMENT_CITADEL';

**Comment by Iamblichos** [comment]
Got a screenshot?

**Comment by TechpriestEnginseer** [comment]
I agree when I put these citadels on hills they look a little off, but with a 0.8 scale, it looks better.

**Comment by Oscar-IronTower** [comment]
![civ5screen0002](https://cloud.githubusercontent.com/assets/4163757/19253226/014df25e-8f20-11e6-9641-31b4aff7b338.jpg)
