### ISSUE TITLE
StealTechFasterModifier on GreatWorks

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2625]
Does it also allow spies to steal great works faster as well? I think it would be a nice buff. Otherwise, I'd like one of the last core table entry made to StealGreatWorksFaster.

**Comment by LoneGazebo** [comment]
No but I can add it

**Comment by TechpriestEnginseer** [comment]
Is documented as StealGWSlowerModifier and StealGWFasterModifier respectively.
