### ISSUE TITLE
Very few events (9/30)

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2626]
_1. Mod version (i.e Date - 4/23):_9/30

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP
Enginseer's version of E&D and Community Events
JFD Cultural Diversity Core
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Celtic City Names, Iroquoian City Names, Randomize City Names
My own thing that does various things SQL type stuff
Ice Free Coasts
WHoward: No Nukes, Map Pins, Auto Map Pins, Diary, Enhanced Demos, Military Log, Religion Spread

_3. Error description:_ 
Even with all options enabled, the only random events in an entire 9/30 game were Enginseer's city founding ones, MonstrousBeast (choose instant yield for a city), and Mercenary (get two units or barbs surround a particular city). None of the Core Events and none of Hokath's. Only mods changed in my list are the upgrade to 9/30 VP and the WHoward ones. Did find an error about Hokath's Russia event, but that's the same version as last event-filled game as well. Haven't tried with the new version, how fast you go, it'll likely be the next version before I have time to start up again.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi related to RNG rework for events?

**Comment by pandasnail** [comment]
Enginseer says he can't reproduce the Russia event database error, so maybe just something went wrong with my game? There's another on the forum mentioning similar, and I do delete the cache and whatnot constantly tho. Idk

**Comment by LoneGazebo** [comment]
Hmm. Okay keep me updated.

**Comment by TechpriestEnginseer** [comment]
I'm noticing this issue, but I can't seem to figure out why. (I usually get an event by 20 turns or so, but nothing now)...

**Comment by TechpriestEnginseer** [comment]
Has there been any changes made toward the GameEvents.EventCanTake logic? People are isolating the issue and believe my E&D has been ignoring most of the events.

**Comment by LoneGazebo** [comment]
Nope. I think the issue may lie in @ilteroi's recent change but I need to look.

**Comment by vermiciousknid** [comment]
Gah. I did multiple reinstalls thinking I had somehow inflicted this on myself.

**Comment by pandasnail** [comment]
In the 10/12, those two events (MonstrousBeast and Mercenary) are still making up 80 to 90 percent of random events (thru 150 standard speed turns). A few more are sneaking in, and events are happening more often-I also have more cities tho, but for instance, I haven't gotten a single pillaged farm, which used to be the most common one.

I see in the config file, there's this choice, would putting it on one of the settings provide useful info? Even if its one of these with a file too big to post, I can look thru it if I know what to look for.

Rand event logging bitfield.  bit 0 = on/off, bit 1 = log callstacks, bit 2 = log pregame calls, bit 3 = log asynchronous RNGs
RandLog = 0

**Comment by LoneGazebo** [comment]
That won't do anything no. EventLogging and EventCityLogging are useful, however.

**Comment by pandasnail** [comment]
Oh...I have that on already apparently.

[events log.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/530569/events.log.zip)

**Comment by pandasnail** [comment]
Oh, that database error I mentioned is a conflict with no nukes mod, that event wants atomic bombs to trigger, would that have somehow have greater consequences on unrelated events?

**Comment by LoneGazebo** [comment]
Shouldn't, no. I think I see the issue -there was a missing break, so of all valid events, the 'last' valid one in the list is selected.

**Comment by pandasnail** [comment]
Ah, okay. That makes sense.
