### ISSUE TITLE
AI offers peace deal they won't accept

### ISSUE THREAD

**Issue by lucperrin** [LoneGazebo/Community-Patch-DLL#2627]
_1. Mod version (i.e Date - 4/23):_ 10/9

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  AI is offering a surrender peace deal they won't accept.  I think this is due to refusing to trade away their last GPT.  I had to remove the GPT from the peace deal to make this go through.  If you load the auto save you will need to wait a few turns for the deal to be offered.

![impossible_peace_deal](https://cloud.githubusercontent.com/assets/380143/19258137/51c0bc6c-8f2a-11e6-8f5e-448fd8106dd6.png)
[AutoSave_0340 BC-0100.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/520941/AutoSave_0340.BC-0100.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Oh good point. I'll add a check thanks.
