### ISSUE TITLE
Great Admiral spawn gives England a We Love the Empress Day (from the forum)

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2628]
_1. Mod version (i.e Date - 4/23):_10/9 Hotfix 

_2. Mod list (if using Vox Populi only, leave blank):
Full NonEUI VP
Diplomacy Spinning Globe Fix (v 1) [Not even sure this is necessary anymore, but I've never started a game without it.]
No Hidden Bonus Resources (v 1) [Decisions from the start are crucial to me.]
Random City Names (v 2) [Variety.]
UI - Notification Options (v 13) [To remind me when cities grow and borders expand.]

_3. Error description:_ 
A Great Admiral spawning in London gave him one somehow, but a Great Merchant spawning in another didn't. For more, see: http://forums.civfanatics.com/threads/we-love-the-empress-day-in-london-is-this-intended.599385/

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Iamblichos** [comment]
I'll look into this one.

**Comment by Iamblichos** [comment]
found the problem, we just left out at line in creategreatadmiral in CvPlayer.cpp (ref. creategreatgeneral, it's correct).

**Comment by Iamblichos** [comment]
Note to self to update text: TXT_KEY_NOTIFICATION_CITY_WLTKD_UA to reflect 75% Growth boon.

**Comment by LoneGazebo** [comment]
I updated th text already.

**Comment by Iamblichos** [comment]
You updated it in 10-9.1 or in your working build? Looks like it is old in 10-9.1. I'm assuming you did it in your working build. Won't include that in pull request then.

**Comment by LoneGazebo** [comment]
Working build.
