### ISSUE TITLE
Ceilidh Hall (5/6)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#263]
Ceilidh Hall needs +1 Culture from Olives and +1 Gold from Perfume (like a Colosseum).
Please add these codes to the MoreLuxuries.sql in the Compatibility Files (EUI AND No-EUI).

INSERT INTO Building_ResourceYieldChanges (BuildingType, ResourceType, YieldType, Yield)
SELECT 'BUILDING_CEILIDH_HALL', 'RESOURCE_OLIVE' , 'YIELD_CULTURE' , '1';

INSERT INTO Building_ResourceYieldChanges (BuildingType, ResourceType, YieldType, Yield)
SELECT 'BUILDING_CEILIDH_HALL', 'RESOURCE_PERFUME' , 'YIELD_GOLD' , '1';

**Comment by LoneGazebo** [comment]
Thanks! Will fix.
