### ISSUE TITLE
Weird movement

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#2630]
_1. Mod version (i.e Date - 4/23):_
10.9.1

_2. Mod list (if using Vox Populi only, leave blank):_
InfoAddict, Clock

_3. Error description:_ 
For some turns, playing Persia, all my units were moving faster, like 3 or 4 steps. I wasn't in a golden age, but I was attacking Inca at the moment. Then it reverted to normal.

_4. Steps to reproduce (optional):_
I don't know what triggered it.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Iamblichos** [comment]
We will need a save game at the point you noticed the movement issue to debug this.

**Comment by LoneGazebo** [comment]
Sure it wasn't an event or something?

**Comment by matlajs** [comment]
didnt GA ended previous turn for you? bcoz units will reserve its bonus mp 1 turn after and vice versa. you will have just 2 mp in first run in GA. its bothering, units cant heal when GA begins, since they already wasted 1 mp.

**Comment by tu-79** [comment]
I play with events disabled. I cannot provide a savegame, cause I rage-quitted when hitting Next wouldn't work.

It can be what matlajs says, I'll watch it next time. And remember to keep a save if it misbehaves.
