### ISSUE TITLE
Cannot establish embassy in ,,new'' capital

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2632]
_1. Mod version (i.e Date - 4/23):_
10/9/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

After Askia took Kyoto from Japanese, i cannot establish new embassy in Japenese's new capital. already in place it says.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
That's not how embassies work - you should still have an embassy with Japan even if they lose their capital (it just won't reveal the new capital, as that only happens on est. the embassy in the first place).

**Comment by matlajs** [comment]
ok. anyway renewal bug is still present and our disscusion in my last  bugpost about boredom modifier-that surrplus of culture should appear in both modifier overviews, was true. but i didnt notice that issue in this version, yet i didnt take any city.

**Comment by LoneGazebo** [comment]
renewal bug?

**Comment by matlajs** [comment]
trade renewal. but i suppose it is something hard to eradicate. one version its gone, second its present and so on, or just some circumstances. yet it is just pedro desperate that i refuse sell him my arabian cofee. :D

**Comment by TechpriestEnginseer** [comment]
I can confirm trade renewal happens often on my strategic resources. In my testing, I've noticed this happens because the AIs were using strategic-required units and when I denied them once it expired, their strategic-required unit were suddenly at a penalty (maybe) alarming the AI to buy some strategic resources and such. But sometimes, if I do deny it; they'll take the denial.

**Comment by matlajs** [comment]
interesting is how reproductive it is. pedro asked me for coffe like 6 times, than break, than research agreement expired with him so he renewed it with me after 2 turn, than few turns break( i thought he lost taste on my double filtered cofee :( ), goh he didnt.

**Comment by LoneGazebo** [comment]
haha. I'll see what I can do. A savegame from the event would be grand.

**Comment by matlajs** [comment]
![harun al-rashid_0000 bc-4000 rar](https://cloud.githubusercontent.com/assets/21192402/19342797/a8468a5c-9133-11e6-81c4-246bbc32bec7.jpg)

here is the save. pls notice that i am using also Promo flag and RED modpack and faster aircraft.

**Comment by matlajs** [comment]
another thing i want to ask, again from previous bug post. You told me that Logistics and Recruitment(Indonesian unique promotion) are mutually exclusive and cant work together bcoz of dll nature. so why can logistics and bushido stuff work together?
