### ISSUE TITLE
Game ends on 1st turn with Cummunitas map

### ISSUE THREAD

**Issue by mcshame** [LoneGazebo/Community-Patch-DLL#2633]
_1. Mod version : Vox Populi (10-9-1)

_2. Mod list (if using Vox Populi only, leave blank):_

- 43 Civs CP V1

_3. Error description:

Game ends on 1st turn with Cummunitas map

_4. Steps to reproduce (optional):_

Start mods and in setup select 43 civs,  20 city states,, Communitas map, Huge.
Once you start, to will get the defeated message and screen on the start of the turn.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): **Attached**

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): **Can't, happens prior to save option.**

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/525932/Logs.zip)

Files/Steam/steamapps/common/Sid Meier's Civilization V): **Not applicable** 

4. Screenshots (optional): **Not required**

**Comment by LoneGazebo** [comment]
Some mapscripts may be incompatible with the 43 civ DLL because of hardcoded restraints. Use a standard map.

**Comment by mcshame** [comment]
That's too bad, I thought this map was one made within the Community patch team and could be fixed since it's delived with Vox Populi

**Comment by LoneGazebo** [comment]
It was an older map we revived, but we didn't make it - you should post in the 43civs thread to see if a mapscript modder can take a look (I don't do mapscripts).

**Comment by mcshame** [comment]
ExpiredReign advised to change the following in the Communitas.lua file under community patch/Mapscripts.

local overrideAssignStartingPlots = true

change to false.  This solved the problem.  Not sure what other effects this setting change will have
