### ISSUE TITLE
City-State Units bought from Merchant of Venice's Purchases are confused on their origin.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2634]
1) Buy a City-State (Ex. Budapest) with Military Units
2) Build a National Epic or Dojo(Ex. Anywhere really, but I chose Kyoto and Tokyo) that has no relationship between the city-state or the military unit at all.
3) City-State Purchased-Units get the promotion despite not being related to the city with the national epic or dojo.

**Comment by Iamblichos** [comment]
I believe the national epic is global in scope now. It's retroactive to every military unit that exists. The dojo should only apply to trained units in that city. Or if they are starting units, the origin city will be null, and if the capital builds a dojo, they should get the promotion. Need to take a look at purchase.

**Comment by LoneGazebo** [comment]
They should only get the bonus if they have an origin city, which - in this case - is probably your player capital.

**Comment by TechpriestEnginseer** [comment]
Which isn't the case since building a dojo in any city grants these city-state units the promotion.

**Comment by LoneGazebo** [comment]
huh.
