### ISSUE TITLE
Celt faith bug

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#2635]
_1. Mod version (i.e Date - 4/23):_ 10/12
_2. Mod list (if using Vox Populi only, leave blank):_
_3. Error description:_ The +3 faith per city does not works. (It was already the case in 09-19)
_4. Steps to reproduce (optional):_ Play as the Celts then take a pantheon
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/526630/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[BUG_Boudicca.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/526637/BUG_Boudicca.zip)

**Comment by LoneGazebo** [comment]
Hmm...I think I have a fix, let me send you a test DLL (savegame compatible) shortly.

**Comment by mcshame** [comment]
I am playing the Celts and I'm certain that I was receiving the faith for my pantheon in 3 cities.  Then when I converted then to a religion, I am quite certain my total faith dropped. Hmmm, needed to pay more attention.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/528657/CvGameCore_Expansion2.zip)

Test pls?

**Comment by MoiMagnus** [comment]
First test : CTD
Here is logs and mini-dump
[LogsAndDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/528994/LogsAndDump.zip)

**Comment by LoneGazebo** [comment]
Weird, I got it to work no-problem.
