### ISSUE TITLE
Sort of Cool...

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2636]
It has often struck me that UnitCombatTypes aren't a variable, and therefore not changeable in CvUnit.cpp on the fly (it has no variable). What if you had a Hero Unit (i.e. a Great General that was a Combat Unit) that started as a Mounted Unit and then became a Tank once it progressed to the appropriate era? So I made it a variable. Note the combat modifers for the barbarian units (my values are a little different from the CBP):

![20161013122754_1](https://cloud.githubusercontent.com/assets/14372214/19359715/feec9c0e-9140-11e6-8f05-a3061095ffa2.jpg)

then I immediately advanced myself to the modern era which triggered the unit in the DLL to have new database read values, barbarian no longer has bonus vs. mounted:

![20161013122907_1](https://cloud.githubusercontent.com/assets/14372214/19359740/1e06ee1e-9141-11e6-9ac3-7099abd664c2.jpg)

...but anti-Tank applies:

![20161013122914_1](https://cloud.githubusercontent.com/assets/14372214/19359753/2e4226d6-9141-11e6-8bb6-5d897b84946d.jpg)

Just to show that the variable is setting the CombatClass correctly for regular units:

![20161013122954_1](https://cloud.githubusercontent.com/assets/14372214/19359800/57cb1a80-9141-11e6-8f27-5017675b9cea.jpg)

**Comment by Iamblichos** [comment]
I could have just initialized a whole new database unit when I hit the modern era, but I didn't like that. It's just one UnitType entry and another table that reads values for new Era Combat Strength and New Era UnitCombat Type.

**Comment by matlajs** [comment]
interesting idea. same thing is in prehistoric mod, where ,,Hero'' is skirmisher and meele cavalry too. was funny, but there will be problem with stack him with another units, since he is military unit now?

**Comment by Iamblichos** [comment]
This unit can't stack because he's not a civilian unit. The challenge (which wasn't a huge challenge, just sorta cool ya know?), was to have a singular unit (not two units), that had two different CombatClasses (UNITCOMBAT_MOUNTED and UNITCOMBAT_ARMOR) in distinct Eras (Ancient - Industrial -> Mounted, Modern - Future -> Armor). I don't think that mod can do that with 1 unit without some DLL manipulation unless it's a unit that has a unitclass upgrade.

**Comment by matlajs** [comment]
i got one idea. absolutely no clue if it would be possible to do and if so, how dificult it would be.

**Comment by Iamblichos** [comment]
What do you have?

**Comment by matlajs** [comment]
what are those general/admiral points right now? that is some kind of special yields? can those be changed for GG/GA to something maybe faith related for them being rather purchasable than born when you filled pool.

**Comment by TechpriestEnginseer** [comment]
They are normal yields like culture and science.

**Comment by matlajs** [comment]
bad english as always. i didnt ment it this way. i ment it do those GG/GA yields like normal yields, which will not trigger born of those persons. but i have no idea what would replace those faith pruchases in authority/imperialism branch. or nothing what would not demand some complete rebalance or rework. rather i leave it for  profesionals :D

**Comment by Iamblichos** [comment]
You mean like when they hit the GG/GA threshold points, they become a trainable unit?
