### ISSUE TITLE
CTD after first contact with civ, reproduceable from savegame

### ISSUE THREAD

**Issue by CrankyCorvids** [LoneGazebo/Community-Patch-DLL#2637]
_1. Mod version (i.e Date - 4/23):_
10/12 

_2. Mod list (if using Vox Populi only, leave blank):_
Core Community Patch only.

_3. Error description:_
In the attached savegame, after end of turn, a Shoshone scout will come out of the fog of war, causing contact to be established with that civilization and their diplomacy screen to pop up. After dismissing the diplomacy screen, the game will crash to desktop.

I was able to avoid the crash by going back to an earlier point in the turn and moving my scout in the opposite direction so first contact didn't occur at that time; when I established contact with the Shoshone a couple of turns later, the game did not crash.

Log files, savegame and minidump attached below.

[ctd.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/527934/ctd.zip)

_4. Steps to reproduce (optional):_
Load the attached savegame. End the turn. Dismiss the diplomacy screen that pops up. The game should then crash.

**Comment by LoneGazebo** [comment]
Loaded save and advanced to meet the Shoshone, no crash for me. You might try turning off corethreading in civ's options ini file.

**Comment by CrankyCorvids** [comment]
I did some testing, and here's the tally:

* Still crashes on my end with EnableGameCoreThreading set to 0.
* Still crashes after a clean reinstall of the mod and a Steam validation of the game files.
* **Does not** crash when running the 'DirectX 10 & 11' version of the game instead of 'Windows 8 - Touch Enabled (Recommended)' from the launcher. I am on Windows 10.

I'm not sure there's any significant difference between the "recommended" version and the non-touch-enabled version other than the touchscreen support, which I don't use, so I guess that resolves the issue for my part.

**Comment by LoneGazebo** [comment]
I would definitely use the DX10/11 version.

**Comment by Iamblichos** [comment]
Yes when I used to play vanilla a long time ago, I've seen some unexpected crashes just like this using the touch enabled. It's probably an improperly coded UI in that build.
