### ISSUE TITLE
Jade not recognized for Stone Works Construction

### ISSUE THREAD

**Issue by mcshame** [LoneGazebo/Community-Patch-DLL#2638]
_1. Mod version (i.e Date - 4/23):
  Vox Populi (10-12)

_2. Mod list (if using Vox Populi only, leave blank):
43 Civs CP V1
InfoAddict (v 22)
Yet (not) Another Earth Maps Pack (v 24)
Quick Turns (v 10)

_3. Error description:

Noticed that Jade that was worked in the capital was not being recognized for building stonework. I selected the title on and off, not change.  Checked another Jade Tile in my secondary city and it is recognized and will allow Stone works to be constructed. Moved production of tile in the secondary city and back to Capital, stone works still can't be selected.  I'll attached game file for your viewing pleasure and a screen shot.

Note that I have not completed the working of the stone yet.

_4. Steps to reproduce (optional):

Go to Celt capital, try to build stone works.  Check other city and you'll see it can be selected there.

[Boudicca_0107 BC-0200.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/528041/Boudicca_0107.BC-0200.zip)
![jade not reconized for stone works](https://cloud.githubusercontent.com/assets/22803568/19364209/48987c28-915b-11e6-809e-37315d093e43.jpg)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Well that was a fun rabbit-hole. Turns out 'working city' wasn't being updated (in vanilla code) when you switched plot use for a different city. Anyways try this DLL:



[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/528532/CvGameCore_Expansion2.zip)

**Comment by mcshame** [comment]
Good stuff,

**Comment by LoneGazebo** [comment]
yay

**Comment by mcshame** [comment]
Hi Gazabo,  I only had a chance to test it now.  I copied the file (CvGameCore_Expansion2.dll) into the community patch mod folder and tried it.  It still did not offer me stoneworks.  I switched between the two cities, still same effect.  Did I need to delete a cache or something?

**Comment by LoneGazebo** [comment]
See above: You will need to toggle the city ownership of the tile b/w Cambridge and Edinburgh to see the effect.

**Comment by mcshame** [comment]
if you mean selecting the title to be worked in one city, then changing it back to the other, yes tried that, stonework was still grayed out.  It worked for you?

**Comment by LoneGazebo** [comment]
Yep, worked for me. Make sure you replaced the DLL in the 43Civ mod (and deleted the DLL in the CP).

**Comment by mcshame** [comment]
Ahh, I only did it in the Community patch and I guess it was getting overridden with the bad one from 43 Civs.  Worked like a charm, Unit tested and passes ;)

**Comment by LoneGazebo** [comment]
Cool.
