### ISSUE TITLE
still getting recommendations for academies on improved resources when other tiles are free

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2641]
title says it all

**Comment by pandasnail** [comment]
I like to post my GPIs on luxes sometimes esp with Tradition, Am I doing it wrong? I do like to work a lot of specialists..

**Comment by matlajs** [comment]
i plant GPI on plantation/camp luxuries but never on mine luxes. i rly hate take cities from AI which like plant manufactury on silver(thats the worst one, but pretty much whatever GPi they plant on mine resources)
