### ISSUE TITLE
spy rank is strange

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2643]
![image](https://cloud.githubusercontent.com/assets/1358966/19402905/2b1b3c62-9264-11e6-9ee8-bf186cf2c5e5.png)

paris has the highest rank, moscow a rather low one, despite similar size, buildings and science output.

and i cannot even steal techs from france, they have nothing i don't have.

is this intended?

**Comment by LoneGazebo** [comment]
Rank is both science and gold output. Not just scienc

**Comment by ilteroi** [comment]
hmm. didn't check gold. anyway not a big issue
