### ISSUE TITLE
City-State Unit gifts

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2645]
10/12
They spawn near a city-state gifting them:

![8930_20161014045656_1](https://cloud.githubusercontent.com/assets/1131228/19407397/5b31d11c-92ba-11e6-9688-6d58d77d2012.png)
![8930_20161014060830_1](https://cloud.githubusercontent.com/assets/1131228/19407400/611c1704-92ba-11e6-854f-019bff59d77d.png)
![8930_20161014063446_1](https://cloud.githubusercontent.com/assets/1131228/19407398/5e4040c8-92ba-11e6-8e4e-8f4bfc2f175e.png)

But it seems there is some range requirement involved, since when I captured the Zulu city south to Sofia, Atlatlists started to spawn in there.

**Comment by LoneGazebo** [comment]
I'll give er a look-see.

**Comment by Radost** [comment]
The bug is still in place
![8930_20161020065842_1](https://cloud.githubusercontent.com/assets/1131228/19545175/b25f9334-969d-11e6-9116-b258f30431e4.png)

**Comment by LoneGazebo** [comment]
Weird, I tested and it went fine. Granted the issues seem to be with CSs on islands. Lemme check that.
