### ISSUE TITLE
Um, did I imagine that Mongolian Melee horses lost their extra move?

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2646]
_1. Mod version (i.e Date - 4/23):_
10/13

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP

_3. Error description:_ 
Just finished a Mongol game and Horseman and Knights had 5 starting move, War Elephants 4. Its supposed to be normal, isn't it? Its not in the UA text anymore. I remember being bummed when you took it out, gosh, a year ago now. (at the time, even Cuirs didn't exist, but I'm rambling now) I thought it might be a weird conflict, so I (deleted the cache) and made a quick test, even have a save if you want.

Should also add if it is intentional, I won a Standard speed Standard size Emperor in 1480. I'm not actually that good, even accounting for a good start.

(edit: accidentally put normal modlist)

[Genghis Khan_0051 BC-0960.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/530854/Genghis.Khan_0051.BC-0960.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![monhorse](https://cloud.githubusercontent.com/assets/16260521/19408176/0b214016-9285-11e6-92bb-27eb993671b8.jpg)

**Comment by Radost** [comment]
Normal is 4 moves for cavalry and 3 moves for elephants.

**Comment by pandasnail** [comment]
Right, that's what I mean, I thought the Mongols lost this UA element and therefore it should be that 4 and 3 now.

**Comment by LoneGazebo** [comment]
I don't believe so, no – avoiding ZoC and +1 moves is their jam, IIRC.

**Comment by pandasnail** [comment]
Ranged mounted gets +2 move and avoids ZoC (Melee mounted actually doesn't ignore ZoC just has +1 move) is what the UA text says now. And I was getting that too, Skirms started 6 move and Horseman started 5 move.

**Comment by LoneGazebo** [comment]
Alright, so it is working as designed?

**Comment by pandasnail** [comment]
The UA text no longer says Mounted Melee get +1 move. But if they are supposed to +1 move-but not ignore ZoC-then its working as designed and only a civpedia type thing.

**Comment by LoneGazebo** [comment]
I'll double check.
