### ISSUE TITLE
Heavy Skirm didn't auto pillage enemy Caravan

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2648]
_1. Mod version (i.e Date - 4/23):_
10/23

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP
Enginseer's version of E&D and Community Events
JFD Cultural Diversity Core
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Celtic City Names, Iroquoian City Names, Randomize City Names
My own thing that does various things SQL type stuff
Ice Free Coasts
WHoward: No Nukes, Map Pins, Auto Map Pins, Diary, Enhanced Demos, Military Log, Religion Spread

_3. Error description:_ 
Knights did tho.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![hskirm](https://cloud.githubusercontent.com/assets/16260521/19408234/6205a68c-9286-11e6-8698-c79b4438116b.jpg)

**Comment by LoneGazebo** [comment]
Is auto-pillaging a thing?

**Comment by LoneGazebo** [comment]
@ilteroi any changes to unit missions that might've broken this?

**Comment by pandasnail** [comment]
Most of the time when a Caravan moves into an enemy unit, it gets pillaged that very second, yeah. And that did happen with my Knights.

**Comment by LoneGazebo** [comment]
Is that a melee-only thing?

**Comment by pandasnail** [comment]
I guess it could be? I never noticed a unit not do it until now, but then Mongolia is basically the only civ where my army is highly ranged.

**Comment by LoneGazebo** [comment]
Might be that - not at machine at moment to check, though.

**Comment by F0rst1** [comment]
Could this be related to #1800 ? Not all units can plunder a trade route, even though all units can pillage them.

While we're at it, the promotion "can plunder trade routes" etc. has gone missing recently(?) from the units that once were able to plunder trade units. I know that mounted melee units had the promotion and I'd guess mounted ranged units were able to do it too, but I'm not sure of it. Anyway, I have a knight in my current game and it doesn't have the promotion.
