### ISSUE TITLE
Civ liberated from me didn't get auto-vassalized

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2649]
_1. Mod version (i.e Date - 4/23):_
10/13

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP
Enginseer's version of E&D and Community Events
JFD Cultural Diversity Core
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Celtic City Names, Iroquoian City Names, Randomize City Names
My own thing that does various things SQL type stuff
Ice Free Coasts
WHoward: No Nukes, Map Pins, Auto Map Pins, Diary, Enhanced Demos, Military Log, Religion Spread

_3. Error description:_ 
Sorry for so many posts, and there was nothing in the logs about this one, and too many mods for a save. But yeah, Kamie freed Boudie, and she didn't get vassalized, which the 10/9 changelog says is how it works now.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![lib1](https://cloud.githubusercontent.com/assets/16260521/19408273/2f3118da-9287-11e6-8398-24851f2ff15e.jpg)
![lib2](https://cloud.githubusercontent.com/assets/16260521/19408277/346a2350-9287-11e6-954f-9e8d17054862.jpg)

**Comment by LoneGazebo** [comment]
That's weird, works for me.  I'll check.

**Comment by pandasnail** [comment]
I should add that by this point in the game, I had a Vassal of my own, which I remember somehow did something weird to City State allies declaring war. Since I don't understand the code of all that at all, I have no idea if this could be similar or not.
