### ISSUE TITLE
petra built without significant desert around

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2653]
AI wonder selection is not quite perfect ... the french built petra when working a single desert tile

![image](https://cloud.githubusercontent.com/assets/1358966/19413547/91cc0ab4-9330-11e6-876f-cc77b4d186fb.png)

**Comment by ilteroi** [comment]
and again. why do they love petra so much?

![image](https://cloud.githubusercontent.com/assets/1358966/19413713/ac40860e-9335-11e6-9878-29dc86b9f849.png)

**Comment by LoneGazebo** [comment]
The extra trade route is nice, and the tourism later in the game.

**Comment by ilteroi** [comment]
stilll think it's suboptimal. but not a big problem either
