### ISSUE TITLE
Puppet AI

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2657]
_1. Mod version (i.e Date - 4/23):_

Current, 12th Ocrtrober
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Puppet a city.

After a few buildings, it'll stop making more and go Farming (25% Prod to Food) despite there being possible to raise many buildings. It omits important buildings such as Barracks, Libraries, etc.

**Comment by LoneGazebo** [comment]
I need logz.

**Comment by LoneGazebo** [comment]
BuildingProductionAI log, please.

**Comment by Enrico-Swagolo** [comment]
Oh. I had them turned on some time ago, buuuuuuut... After Steam made Civ 5 impossible to open for a day, I've reinstalled it (didn't even help, as it was a Steam server problem) then and the setting is now off.

Care to remind me what and where should be changed to 1/0 etc?

**Comment by LoneGazebo** [comment]
enable AI logging in the config ini

**Comment by Enrico-Swagolo** [comment]
Found it! Does the thing, like, work for turns that logging wasn't turned on?

**Comment by LoneGazebo** [comment]
nope

**Comment by Enrico-Swagolo** [comment]
Oh well, gotta puppet some cities then. I bet Pedro will help me with this.

**Comment by Enrico-Swagolo** [comment]
Started another game with EnableAILogging = 1. Where can the files be found so I can upload them?

I've noticed that the AI just doesn't want to build Barracks. When it has built every other building, it just remains on No Production (doesn't even go into Farming~!) for X turns, then usually goes to Farming and bugs out.

**Comment by Enrico-Swagolo** [comment]
I've found a logs folder in Documents/My Games/Sid Meier's, but it doesn't contain the file?

I think you've told me wrong how to enable logging

**Comment by LoneGazebo** [comment]
; Enable message logging
MessageLog = 1

; Rand event logging bitfield.  bit 0 = on/off, bit 1 = log callstacks, bit 2 = log pregame calls, bit 3 = log asynchronous RNGs
RandLog = 1

; Enable AI logging
AILog = 1

; Enable AI performance logging
AIPerfLog = 1


If you load the save and progress a few turns with bad puppets that should do it.

**Comment by Enrico-Swagolo** [comment]
Okay! Will do.

**Comment by Enrico-Swagolo** [comment]
Okay, I've done it, loaded the save, progressed a few turns but the log folder still doesn't have the file. It's almost empty, aside from 1KB stuff. Is it the logs folder in my documents/my games/sid meier's civ 5?

I've noticed something weird. The Puppet cities will sometimes just go Farming to a few turns, then build some other building that was unlocked for them for eons, like Granary or Herbalist. Never Barracks.

**Comment by Enrico-Swagolo** [comment]
; Enable the logging system
LoggingEnabled = 1

Found that and you didn't mention it, will try again

**Comment by Enrico-Swagolo** [comment]
YEAH now I HAVE MANY FILES, like citybuildingstrategy

But there's no BuildingProductionAi log. There's lots of others. I think if I turn Builder AI logging to 1, I'd get the buildingproductionai.


; Enable Builder AI logging
BuilderAILog = 0

to 1?

**Comment by Enrico-Swagolo** [comment]
Update your advice with the fact it has contain that the following, which is much, much below in the config file

 ; Enable the logging system
LoggingEnabled = 1

Just enabling AI logging ddoesn't work because regular logging isn't there

I have ALL THE LOGS. Take them all, because BuildingProductionAI doesn't exist. There's CityStrategyAIProduction which seems to be the one you've mean.

The cities to look out for is Orleans. And IIRC Lyons? Some French city that appears around the same time.
[LogsForGooseby.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/532092/LogsForGooseby.zip)

**Comment by LoneGazebo** [comment]
Barracks is discouraged because they can't train units, thus the XP is wasted.

**Comment by Enrico-Swagolo** [comment]
Barracks gives +2Science though, +2 Production (with Arena) as well as lower Danger.
