### ISSUE TITLE
Authority bonuses not firing when barbs kill themselves against cities

### ISSUE THREAD

**Issue by Skidizzle** [LoneGazebo/Community-Patch-DLL#2658]
ver. 10-12
infoaddict 10
thals flag promos 1
more great works 3
unit path viewer 10 (would be great if something like this were integrated into Vox hint hint)

2 barb horsemen kamikazed into vacant capital and i didn't receive culture or science bonuses from authority policies. Policy text states when barbs are killed you should get yields. 

let barbs kill themselves against cities with authority policies active.

**Comment by LoneGazebo** [comment]
Well, you aren't killing them via combat, so it is working as intended.

**Comment by Skidizzle** [comment]
Units can only be killed by combat.. cities function just like an immobile ranged unit

**Comment by LoneGazebo** [comment]
But the unit kills itself via pillaging. That's not the same as you killing it in the DLL.

**Comment by Radost** [comment]
"Pillaging" involves attacking a city.
