### ISSUE TITLE
Game crashes when I meet a nation for the first time

### ISSUE THREAD

**Issue by tillito77** [LoneGazebo/Community-Patch-DLL#266]
Whenever I meet a nation for the first time, the game crashes (the application is closed without a warning).

When I load the game and meet the same nation again, it works fine. When I meet the next nation for the first time, it crashes again.

I figured out a workaround: when setting the video quality of the leader animations to minimum, everything works fine!

I have been playing with the latest version: Community Balance and More Resources plus its prerequisites. Beside that, only R.E.D. Modpack and some very small mods, like "no futuristic units" etc. which I have been using since ages ... playing large communitas map with Germany.

**Comment by LoneGazebo** [comment]
Sounds like a video card driver issue.
