### ISSUE TITLE
crash in CvCity::getEconomicValue()

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2662]
callstack:

\cvgamecoredll_expansion2\cvcity.cpp (7050): CvCity::getEconomicValue
\cvgamecoredll_expansion2\cvmilitaryai.cpp (2345): CvMilitaryAI::ScoreTarget
\cvgamecoredll_expansion2\cvmilitaryai.cpp (1869): CvMilitaryAI::FindBestAttackTarget
\cvgamecoredll_expansion2\cvmilitaryai.cpp (1619): CvMilitaryAI::FindBestAttackTargetCached

the usual suspects (invalid city pointer, invalid player ID) can all be ruled out, so i don't know what to make of this.

**Comment by LoneGazebo** [comment]
If the city was created/destroyed that turn, perhaps the value was not present? We might want to add a refresh of the economic value when a city is init'd.

**Comment by LoneGazebo** [comment]
Speaking of which, are you still getting a CTD on closing civ? I am.

**Comment by ilteroi** [comment]
i do too. tried to fix it, but no success.

**Comment by LoneGazebo** [comment]
It is problematic, as returning to the menu causes it as well. @Iamblichos you've been adding values to traitclasses and cvplayer lately, mind taking another look at them to make sure all new values are being reset and uninit properly?

**Comment by Iamblichos** [comment]
I sure will. Is it the same CTD Call Stack as before?

**Comment by ilteroi** [comment]
for me it crashes in the destructor of CvPlayer, don't even get a proper callstack

**Comment by LoneGazebo** [comment]
Yeah, CvPlayer is where it crashes, but CvPlayer includes PlayerTraits.

**Comment by Iamblichos** [comment]
Going back to mainmenu this is where I hit it just now:

![image](https://cloud.githubusercontent.com/assets/14372214/19446337/e7e7c734-945d-11e6-987a-4ef8cb39aebf.png)

**Comment by LoneGazebo** [comment]
That's new, haven't seen that - I know you've added a few things to improvementclasses lately, though, correct?

**Comment by Iamblichos** [comment]
Yeah but can't see anything wrong there.

**Comment by ilteroi** [comment]
are all these variables arrays? otherwise the wrong destruction macro is being called.

regarding the original issue, i'll add a size check for the vector of cached values ...

**Comment by Iamblichos** [comment]
Yep, they are. A lot of them there are fairly old.

**Comment by Iamblichos** [comment]
I think the improvement thing might have been a fluke. Had some bad database issues on my last loadup. But in re: the CvPlayer stuff, I think I found the problem and working up a fix. The problem was introduced with adding recomputing GP modifiers on denouncements, which was then gets referenced from CvPlayerTraits back to DiplomacyAI back to CvPlayer, kind of a weird little circle I had there.

**Comment by LoneGazebo** [comment]
Makes sense @Iamblichos.

**Comment by Iamblichos** [comment]
Okay a little update, I believe I have fixed the main menu / exit crash. The only caveat is that if you load up clean from a fresh game start, exit to main menu, and then load up through mods menu again, load the save and then exit to main menu a second time, I get the crash to CvPlayer or to:
```
void CvPlayerAI::freeStatics()
{
	SAFE_DELETE_ARRAY(m_aPlayers);
}
```
This could just be a limitation of the game and using a DLL mod. Thoughts?

**Comment by Iamblichos** [comment]
![image](https://cloud.githubusercontent.com/assets/14372214/19489309/55d2ebc0-9530-11e6-890e-e9e26d5c045f.png)

**Comment by Iamblichos** [comment]
Huh...well having said that, I'm not getting it now. Sitting here going back and forth load, do turn, save, main menu, reload, etc. Could it be an issue if all players haven't settled at some point on exiting?

**Comment by LoneGazebo** [comment]
Turn 0 save/load can do odd stuff to CvPlayer, yep.

**Comment by Iamblichos** [comment]
Still doing it occasionally on that second trip back to main menu after loading a save and doing several turns. But I'm not getting it on a fresh start and load and then back to main menu, which I think is good news.

**Comment by LoneGazebo** [comment]
As long as we're looking at multiple-returns-to-CTD as the outlier, I think we're good.

**Comment by LoneGazebo** [comment]
Definitely run extended tests and then test save/load (as sometimes changing initialized data and then saving it causes CTDs.

**Comment by Iamblichos** [comment]
Yeah I autosave setup to save every turn so that could be a reason too.

**Comment by Iamblichos** [comment]
But I'm not having any issues with saving and loading causing a CTD.

**Comment by Iamblichos** [comment]
Solid man, just multiple returns to main menu causes CTD if you loaded a save. No issues on save/load. Going to do pull request.
