### ISSUE TITLE
DefenseModifier

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2663]
Would it be possible to add a **DefenseModifier** tag to the **Buildings** table? This is akin to the GlobalDefenseMod that already exists, but would only increase the Defense of the city with that building.

Thanks.

**Comment by Iamblichos** [comment]
@JFDaly follow the variable m_iDefenseModifier, which is cached from the database result as
`m_iDefenseModifier = kResults.GetInt("Defense");`

Defense is your database entry which is used on your Walls, Castles, etc.

**Comment by JFDaly** [comment]
Right, should've known better than to expect consistency in naming :p Thanks. I'l amend my OP.

**Comment by Iamblichos** [comment]
It's good practice for naming convention to be consistent, but sometimes they aren't. Wouldn't have taken a lot of effort on Firaxis' part to add a description to the original XML entries, that way everybody knew exactly what the database entries were.

**Comment by Iamblichos** [comment]
Yep I'll do this for you. And add it to BuildingProductionAI as well.

**Comment by JFDaly** [comment]
Awesome, thank you. Please allow it to accept negative modifiers, too - although this is something the CP tends to do anyway.
