### ISSUE TITLE
AI goes 2 ancient era policy trees sometimes

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2664]
_1. Mod version (i.e Date - 4/23):_

12th October

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Sometimes, AI will finish one ancient era policy tree, only to follow another ancient era policy trees.

Through my games on this and previous version, I've seen AI go Progress > Authority, Tradition > Authority and Authority > Progress. Three or four times out of those five-six occurences, it was Shaka. I really don't get that guy.

It was usually if they went  wide, didn't have a majority religion when they've had to choose which I sort of see why (though the religion WAS in their reach, I/someone else was close nearby to convert them), but sometimes already converted AI does something stupid and chooses Authority/Progress over Piety - which is a very, very bad idea.  If you're wide, Piety is just better at everything to the point it's straight out insane to ignore it. If not wide, there's Aesthetics - and I'd dare say even it is better than Progress/Authority at wide. If messing with CS, there's Statecraft.

I mean, I get it - it won't have any benefit from Piety without religion - but if its neighbours have a religion, it should take Piety anyway because it just won't manage to compete if it takes a second Ancient policy tree anyway. If it's already converted and wide, Piety is always better than Progress/Authority and ancient era trees shouldn't even be considered.

Even Aesthetics would do better for wide empire than Progress/Authority, so even wide AI without access to religion should take it  instead (the same shouldn't apply to Statecraft, it's absolutely awful if you don't plan on messing with CS). Sure, half the bonuses will be underwhelming, but they'll still add up to be more than what Authority/Progress offers.

**Comment by LoneGazebo** [comment]
Sometimes the AI simply evaluates it that way - I'm not going to hard-code it (as even some humans do it).

**Comment by Enrico-Swagolo** [comment]
I can understand it, but that AI is pretty much condemning itself to irrelevancy. Granted it IS very rare - I've played hundreds of games on VP/CP, only seen it with 5 or 6 AI. That's about as rare as rare can be, so I admit it's pretty much a non-issue.

**Comment by MoiMagnus** [comment]
Before Autority's nerf, Progress -> Autority was not a always a stupid choice.
Theses are games where you should have taken Autority -> Piety, but for some reason you took Progress first, and you realise latter that you really need the militaristic bonuses.
With the new autority nerf, I don't think it still worth it.

But this is the only case I consider as possible : 
Autority -> Progress is weaker than Autority -> Piety/Aestetic
Autority -> Tradition, Progress -> Tradition and Tradition -> Progress are bad
And if Tradition -> Autority looks better than Tradition -> Aestetic, you will probably lose this game anyway

**Comment by matlajs** [comment]
for me it isnt a rare thing. i have those almost in every game progress-authority or viceversa. mostly warmongers do that and since few new versions, there are tradition-authority too.
