### ISSUE TITLE
AI doesn't pick ruins sometimes

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2666]
_1. Mod version (i.e Date - 4/23):_

12th

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

So, I'm walking with my Warrior, and I see China with a Scout just as my Warrior's movement ends. She can reach the ruin in one turn. I think to myself "she will pick it"

She doesn't. My warrior does 2 turns later.

It only happens sometimes, I don't know why. It's the second time this happened on current patch.

**Comment by F0rst1** [comment]
I've seen that too quite recently. Is it possible that the Chinese scout saw another ruins and went for it?

**Comment by Enrico-Swagolo** [comment]
The likelihood is very, very low. Sure, I didn't exactly see the tile he went to, but ruins that close to each other are rare and even if that is the case, he had 2 turns to come back and pick it up (because my warrior can't get there faster) and didn't.

Anyway, the other time that's happened, there was 99% certainly nothing else to pick for the enemy scout.
