### ISSUE TITLE
Friends Forever? (Never-ending DoF)

### ISSUE THREAD

**Issue by JimBobRedneck** [LoneGazebo/Community-Patch-DLL#2669]
_1. Mod version (i.e Date - 4/23):_
10/12 full w/ EUI

_2. Mod list (if using Vox Populi only, leave blank):_
Improved City View (Vox Populi w/ EUI)

_3. Error description:_ 
See screenshot. DoF with Venice at -23 turns left (so 23 turns past the time it was supposed to end).

_4. Steps to reproduce (optional):_
Unknown. Only known "out of the ordinary" thing was during the normal duration of the DoF, Venice did purchase a city state I was allied with and had a diplomatic marriage with.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20161018000102_1](https://cloud.githubusercontent.com/assets/21163942/19465284/8625f6f4-94c8-11e6-973b-b424bbe9020b.jpg)
[Maria Theresa_0221 AD-0715.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/535324/Maria.Theresa_0221.AD-0715.zip)

**Comment by LoneGazebo** [comment]
Marathon? Could be a UI snafu.

**Comment by JimBobRedneck** [comment]
Epic. Huge size if that matters (though I doubt it does).
