### ISSUE TITLE
idea of the day

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2670]
i just tried tracking down a bug - a ranged units was attacking a plot it cannot see. but it used to be able to see it, before moving away in order to attack from a safe distance.

now, one solution would be to change the way visibility works: every visible tile stays visible until the end of the turn. how about that?

i think it would help the AI, because right now it immediately forgets everything it has seen when a unit moves, when in fact the information is valid until the next turn. 

on the other hand, it's quite a significant change this late in the project. opinions please?

**Comment by LoneGazebo** [comment]
Hmm. That's a big change. How likely would a human be able to tell that the AI ranged unit can't 'see' the thing it is targeting? If the target is valid, does it really matter if the AI can still 'see' it?

**Comment by ilteroi** [comment]
well. that's an alternative i didn't even consider.

right now the range attack cannot be executed because of the failed visibility test. if we change that, the human player would notice that the AI can attack without line of sight, while a human can not.

**Comment by LoneGazebo** [comment]
Well if the attack fails, is it possible to simply have it check for LoS before it actually lines up the attack? Or would that freeze the unit's action for the turn/

**Comment by ilteroi** [comment]
that would be the boring solution :)

**Comment by LoneGazebo** [comment]
Haha – boring yes, but much easier for me to explain to the unruly civfanatics.

**Comment by Iamblichos** [comment]
Does this entail moving off a hill and being able to fire from flatland like indirect fire? Or would this now be an invalid target plot?

**Comment by ilteroi** [comment]
good point. i didn't consider indirect fire. it's hard to handle because i need to know whether another unit can see the plot. and that's difficult to find out

**Comment by Iamblichos** [comment]
It's almost like it needs a cached position of last turn enemy unit plots if it lost LOS, that might eat up a lot of processing though and memory space.

**Comment by ilteroi** [comment]
ok it's strange. this is the situation:

![image](https://cloud.githubusercontent.com/assets/1358966/19496625/9d2ced74-9588-11e6-903a-c0d35f3de9fa.png)

catapult moves W, tries to attack but fails because of visibility. then moves NW to safety. but visibility should be fine!

**Comment by LoneGazebo** [comment]
That's odd - I noticed you changed visibility in cvplot, did you perhaps make a mistake there with refreshing plots? Also, something to do with facing direction?

**Comment by Iamblichos** [comment]
What's the visibility range on a catapult? Don't they have a promotion that nerfs them?

**Comment by ilteroi** [comment]
@g: nah, i just moved the xp from scouting to the right place

@i: never understood this facing direction stuff. it's not really used, shouldn't make a difference.

stepping through it now ...

**Comment by ilteroi** [comment]
@i: you were right. it has a negative promotion, limited visibility. don't know if that makes sense ... but it explains the problem

**Comment by Iamblichos** [comment]
Get rid of that promotion?

**Comment by ilteroi** [comment]
don't know if it will solve the problem in all cases, trying to implement the correct solution now

**Comment by Iamblichos** [comment]
I think the facing direction is all cosmetic and then set so units don't look silly on battle plots when combat is resolved.

**Comment by ilteroi** [comment]
sure. but all the visibility functions take facing direction as parameter and then in the end it's somehow ignored

**Comment by LoneGazebo** [comment]
> sure. but all the visibility functions take facing direction as parameter and then in the end it's somehow ignored

You sound surprised. This is the civ DLL we're talking about. :)

**Comment by ilteroi** [comment]
it gets even better ... CvPlot::canSeePlot() somehow returns true when called with a visibility range of one for plots with a distance of two. wtf.

**Comment by Iamblichos** [comment]
If it's any help, my 4 year old said to throw the bad guys in the water.

**Comment by LoneGazebo** [comment]
That's odd @ilteroi, but don't forget that hills and mountains are visible beyond range!

**Comment by ilteroi** [comment]
@g: normal visibility is handled in a different function. this one is for line of sight checks and mostly used from lua. apparently some genius simply added one to the range instead of fixing the caller? and what's more, did that in the wrong place.

anyway solved that (put in a shim to maintain backward compatibility for lua) and pushed. keep an eye out for vision anomalies though.

**Comment by Radost** [comment]
I wouldn't mind limited vision gone from pre-Artillery artillery, since it makes fighting navy less painful and doesn't make sense without Indirect Fire.
