### ISSUE TITLE
City-State GP gifts trigger "We Love the Empress Day"

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2673]
_1. Mod version (i.e Date - 4/23):_
10/12
_3. Error description:_ 
When they spawn on owned cities. It doesn't seem to give 75% growth, but does increase WLTKD duration.
4. Screenshots (optional):
![8930_20161018230952_1](https://cloud.githubusercontent.com/assets/1131228/19506562/f8eac8b8-95e5-11e6-938e-67027f72a65e.png)

**Comment by LoneGazebo** [comment]
The occupied status might be the issue.

**Comment by LoneGazebo** [comment]
The trigger is intentional, FWIW.

**Comment by Radost** [comment]
Doesn't look very intentional since Statecraft doesn't mention anything about WLKTD on gift, I am playing as Alexander who is a King, and I don't even see the point of adding such a random bonus in the first place.

**Comment by LoneGazebo** [comment]
oh duh, I assumed china.
