### ISSUE TITLE
Generic unit as a Military CS gift

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2674]
_1. Mod version (i.e Date - 4/23):_
10/12
_3. Error description:_ 
This match has an unusually high number of them, could it be they ran out of possible UUs to gift? 
4. Screenshots (optional):
![8930_20161019050904_1](https://cloud.githubusercontent.com/assets/1131228/19506635/ac2cd22c-95e6-11e6-9986-1e1c7460ee6c.png)

**Comment by LoneGazebo** [comment]
Horse Archer == Hunnic UU, no?

**Comment by Radost** [comment]
Yeah, you are right. I guess I still label the whole category as "Horse Archers" and got confused.
