### ISSUE TITLE
Settling underneath a unit of a civ with Open Borders 

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2675]
Results in this:
![8930_20161019061758_1](https://cloud.githubusercontent.com/assets/1131228/19506768/8f49eb80-95e7-11e6-95bd-eb5546c639b2.png)
version 10/12

**Comment by LoneGazebo** [comment]
what's the issue? the unit icon?

**Comment by Radost** [comment]
My unit is standing at a city which isn't owned by me.
