### ISSUE TITLE
DLL Crash on Exit/Menu

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#2676]
@ilteroi and @Iamblichos,

I thought I had it fixed in latest, but when I set the DLL into release (instead of debug) for compilation it crashes on exit to menu/desktop. So perhaps it is a compiler setting?

**Comment by Iamblichos** [comment]
But absolutely no crash on debug build?

**Comment by ilteroi** [comment]
cannot confirm. i have 100% crash on exit in debug.

**Comment by LoneGazebo** [comment]
Likewise. Was apparently a fluke

**Comment by Iamblichos** [comment]
So we thought we had it and then it reappears. This sounds similar to my afternoon yesterday, thought I had it and then G and I spend a good junk of the evening hunting for it. Some variable gets triggered at some point in the game (either immediately or not) and then it fails on deleting player.

**Comment by Iamblichos** [comment]
Here's a bit of news. Doesn't crash with modpack.

**Comment by Iamblichos** [comment]
And I can see it on the Output screen exiting to mainmenu or exiting game. all the event handlers get cleared out.

**Comment by LoneGazebo** [comment]
Pushed some changes that seem to occasionally work. Sometimes it gets to the menu, sometimes it doesn't.

**Comment by LoneGazebo** [comment]
Latest w/ @ilteroi change and my changes still CTD on exit to menu. @Iamblichos want to help going through old  versions and finding one that doesn't CTD to menu? 

https://mega.nz/#F!6Rs2XDbL!Hw4vyBRqQI4lSi1RcsjmiA

**Comment by Iamblichos** [comment]
Unfortunately, yes, we are gluttons for punishment!

**Comment by Iamblichos** [comment]
Thing is it may or may not happen in the first 10 turns. Probably best to sim 40 turns first.

**Comment by LoneGazebo** [comment]
Yeah. Quick + 4 players can get to turn 100 pretty quickly.

**Comment by LoneGazebo** [comment]
If we can solve this damnable issue I've had enough of Civ 5 for one lifetime. :)

**Comment by Iamblichos** [comment]
Started with 7-30 simmed 100 turns exited to main menu couple of times and exited game...no crash. Moving along.

**Comment by LoneGazebo** [comment]
Starts at 10-12. Going to look at 10-9, see what changed.

**Comment by LoneGazebo** [comment]
![image](https://cloud.githubusercontent.com/assets/7849458/19547945/5e5d81a8-9669-11e6-8249-c2eca3a22848.png)

**Comment by LoneGazebo** [comment]
Like the hydra, it was slain. Two bad clears, a few bad kstreams, and a bad belief class value all fixed and BAM! It works again.

**Comment by Iamblichos** [comment]
Yeah I stopped after finishing 8-18 last night and had to bale to bed. I needed at least 1 non-zombie day this week.

For educational purposes, were these no good?

```
MOD_SERIALIZE_READ_ARRAY(88, kStream, &m_piNumPledgesDomainProdMod[0], int, NUM_DOMAIN_TYPES, 0);

MOD_SERIALIZE_READ_ARRAY(88, kStream, &m_piFreeUnitClassesDOW[0], int, GC.getNumUnitClassInfos(), 0); 

CvInfosSerializationHelper::ReadHashedDataArray(kStream, &m_ppiYieldFromTileEarnTerrainType[0], NUM_YIELD_TYPES);
```

I had them originally to what you ended up with, but I thought the way I did it above were more elegant templates for those arrays.

**Comment by LoneGazebo** [comment]
I had one crash on reload on them when I set a trait to one for a test, so I went back to what I know works.

**Comment by Iamblichos** [comment]
Good to know.
