### ISSUE TITLE
Combat preview when attacking cities

### ISSUE THREAD

**Issue by Grabbl** [LoneGazebo/Community-Patch-DLL#2677]
_1. Mod version (i.e Date - 4/23):_
10-19b

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The "combat preview" at mouseover doesn't show up when attacking cities (works when attacking units). I am using EUI, if that could be the problem.

_4. Steps to reproduce (optional):_
Mouseover an enemy city with military unit selected.

[MouseoverCombat.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/538671/MouseoverCombat.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
can confirm

**Comment by Iamblichos** [comment]
What does your LUA log say when you hover over city? I updated EnemyUnitPanel for all versions.

**Comment by Iamblichos** [comment]
I see what happened. @LoneGazebo. It looks like the stuff I did in the pullrequest for CvLuaPlayer.cpp/h didn't make it into your merge.

**Comment by Iamblichos** [comment]
CvLuaPlayer.cpp

`Method(GetTraitConquestOfTheWorldCityAttackMod);`


```
#if defined(MOD_BALANCE_CORE)
int CvLuaPlayer::lGetTraitConquestOfTheWorldCityAttackMod(lua_State* L)
{
	int iRtnValue = 0;

	CvPlayerAI* pkPlayer = GetInstance(L);
	CvPlot* pkPlot = CvLuaPlot::GetInstance(L, 2);
	if(pkPlot && pkPlayer)
	{
		if(pkPlayer->isGoldenAge())
		{
			CvCity* pPlotCity = pkPlot->getWorkingCity();
			if(pPlotCity)
			{
				if(!GET_PLAYER(pPlotCity->getOwner()).isMinorCiv())
				{
					iRtnValue = pkPlayer->GetPlayerTraits()->GetConquestOfTheWorldCityAttack();
				}
			}
		}
	}
	lua_pushinteger(L, iRtnValue);
	return 1;
}
#endif
```

CvLuaPlayer.h:

`static int lGetTraitConquestOfTheWorldCityAttackMod(lua_State* L);`

**Comment by LoneGazebo** [comment]
Blep. I'll fix.

**Comment by Radost** [comment]
Will the fix be save game compatible?

**Comment by LoneGazebo** [comment]
Should be yep.

**Comment by Iamblichos** [comment]
It is. Just tried it with your latest build 10-19-2
