### ISSUE TITLE
AI offers deal it won't accept

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2678]
![image](https://cloud.githubusercontent.com/assets/1358966/19518371/2b438cb6-9607-11e6-9890-91e802d1669e.png)

**Comment by LoneGazebo** [comment]
Was it a gift?

**Comment by ilteroi** [comment]
yep

**Comment by ilteroi** [comment]
ps: just pushed a small update - pillaging for attackers! - everything merged in fefe branch
