### ISSUE TITLE
AI peace quirks

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2679]
![image](https://cloud.githubusercontent.com/assets/1358966/19518550/22822ac8-9608-11e6-8a3a-cee8e290ea37.png)

liberated from indonesia just before

edit: ok, next turn the symbol vanished. changed issue title to make this clear

**Comment by ilteroi** [comment]
and by the way, making peace with AI is still quite difficult.

they declared war, started losing, offered peace. i didn't accept, conquered their city, now they don't want peace. but it's not like they have units around to conquer the anything back. and warscore is a flat 100.

**Comment by ilteroi** [comment]
![image](https://cloud.githubusercontent.com/assets/1358966/19518790/40f6330e-9609-11e6-84f9-1d6e07e8d7f8.png)

**Comment by LoneGazebo** [comment]
100 = capitulation offer

**Comment by ilteroi** [comment]
so why did they decline to discuss peace?

also, losing two minor cities should not cause vassalization, when they have 4 cities left.

does this peace logic take into account the zone dominance around the cities? that is, whether AI is about to lose a city or to capture a city?

**Comment by LoneGazebo** [comment]
>does this peace logic take into account the zone dominance around the cities? that is, whether AI is about to lose a city or to capture a city?

>so why did they decline to discuss peace?
There is a cooldown after losing a city that makes the AI less likely to make peace immediately (hope that they can take it back).

**Comment by LoneGazebo** [comment]
He will probably try to liberate himself from vassalage at the minimum time (50 turns IIRC).

**Comment by ilteroi** [comment]
what i'm trying to say is

- cooldown makes little sense, wouldn't it be better to check the dominance zones to see if there's a chance to take it back?
- offering capitulation has a very high value, you can usually get a city for that. which is not reversible so easily.

**Comment by LoneGazebo** [comment]
The cooldown doesn't prevent peace, but the longer the duration between city captures, the more the desire.

Re: Capitulation, we could probably reduce that value somewhat, yep.
