### ISSUE TITLE
Diplomacy screen glitch

### ISSUE THREAD

**Issue by Lhuhikwdwoo** [LoneGazebo/Community-Patch-DLL#268]
When meeting a civilization, the splash screen comes up, and the animations play normally, but none of the buttons are visible.

possibly related, upon encountering a city state, the city state diplomacy screen does not appear. Rather the expected gold or religion is deposited as normal and the hex of the city has a event glow show up as normal

**Comment by Lhuhikwdwoo** [comment]
my apologies for assuming this was a place where glitches in the patches could be resolved

**Comment by LoneGazebo** [comment]
Sorry, I assumed that you fixed this bug (did you not post in the Civfanatics forum saying that you fixed it?)

**Comment by LoneGazebo** [comment]
These bugs are lua related- did you delete the lua files from the CP/CBP as needed?
G

**Comment by Lhuhikwdwoo** [comment]
I only posted here. if someone did post there as Lhuhikwdwoo then someone created that account there to pretend to be me for some reason.

I went over the installation instructions carefully this time, and ran into a different issue, I can not find any files or folders named "DLC" to move the EUI into outside of those in the patches

**Comment by LoneGazebo** [comment]
The folder location should be:
C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Civilization V\Assets\DLC

You are using a Windows PC, yes?

**Comment by Lhuhikwdwoo** [comment]
yes,and all issues related to the original issue are fixed, but found that the Lua in health and plague for BNW version .19 is required for it to have the health and plague effects yet it causes the city screen to inaccessible. 

other addons are 
CSD v .26
C4DF v .10
CPB(EUI) v ,1
CBP v .13
CP v .66
Events and Decisions CPB v .1
JFD Exploration Continued Expanded v .6
More Luxuries v .155 
UI Trade Routes Enhancements v.6

**Comment by LoneGazebo** [comment]
You can’t use H&P with EUI – says so in the instructions.

**Comment by Lhuhikwdwoo** [comment]
I see, thank you
