### ISSUE TITLE
CTD when trying to exit to main menu

### ISSUE THREAD

**Issue by Glizinte** [LoneGazebo/Community-Patch-DLL#2680]
[CvMiniDump.dmp - Shortcut.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/539309/CvMiniDump.dmp.-.Shortcut.zip)
_1. Mod version 10-9-1

_2. Mod list Vox and Global Relations v7

_3. Error description:_ CTD when trying to exit to main menu.  Happens more often than not(sometimes doesn't.)  

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Known bug with beta. Working on it.
