### ISSUE TITLE
AI Barbarians are too uncertain

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2681]
_1. Mod version (i.e Date - 4/23):_

19th, Beta
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Barbarians can often just move back and forth when they see your soldiers, not attacking, just... Moving around them. Usually from one spot and back, and back to the spot and back.

**Comment by LoneGazebo** [comment]
I'll leave this to @ilteroi

**Comment by ilteroi** [comment]
can't confirm that. they usually attack. only if they have extremely bad odds they won't

**Comment by Iamblichos** [comment]
can't confirm either...move choices look good.

**Comment by ilteroi** [comment]
well now i have one who won't attack. rare but no bigfoot

**Comment by Enrico-Swagolo** [comment]
Yeah, I don't mean every barbarian, but sometimes they just move to a spot and back to their previous one. It's usually if my unit is on a hill/forest or they are on such terrain from my experience. They attack Scouts almost always, but do this weird dance if it's Warriors. Will try to get sum saevs of that occuring but probably tomorrow. Unless I start another game right now that is

**Comment by ilteroi** [comment]
ok fixed
