### ISSUE TITLE
Can't send TR to my capital

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2683]
_1. Mod version (i.e Date - 4/23):_

Current, 19th

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

So, for some weird reason I can send internal TRs to all my cities, with the exception of Rome, and only in Antium this appears.

The TR can go to the much further placed city which is on the right in the image (that one right to Brazilian Sao Paolo), but can't go to the Rome despite there being no TR existing between those two (because, well, I have one TR available)

[WHAT IS ROME.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/539624/WHAT.IS.ROME.zip)

**Comment by Enrico-Swagolo** [comment]
Also unless reinstalling VP changes the log settings, if they are required I can give.

**Comment by ilteroi** [comment]
savegame would be excellent. can't guarantee i'll be able to load it, but without there's little chance to fix

**Comment by Enrico-Swagolo** [comment]
I've reloaded the game, and the thing is fixed? Same turn (225), but now I can suddenly send route to Rome. I will try loading autosaves and check if I can replicate

**Comment by Enrico-Swagolo** [comment]
Yeah, unable to replicate. All's fine now? It seems to have been a problem only during the session that fixed itself afterwards.

**Comment by LoneGazebo** [comment]
Possible issue with the trade path cache, @ilteroi?
