### ISSUE TITLE
can't see tech cost

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2684]
_1. Mod version (i.e Date - 4/23):_
10/19b

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
can not see tech cost in tech tree or in tooltip in left upper  corner

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Unhelpful, man. I need logs.

**Comment by Iamblichos** [comment]
@LoneGazebo can confirm, but don't see any errors.
![image](https://cloud.githubusercontent.com/assets/14372214/19533795/de345f22-9606-11e6-88bb-8a27b7a3db1d.png)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/539990/Lua.zip)

**Comment by LoneGazebo** [comment]
I see why. I fix.

**Comment by matlajs** [comment]
i have few more. look at screens 
![20161019213209_1](https://cloud.githubusercontent.com/assets/21192402/19540491/2a69e674-9660-11e6-9e30-c9972611fde1.jpg)
![20161019232238_1](https://cloud.githubusercontent.com/assets/21192402/19540495/3266b028-9660-11e6-8531-79967d8921e7.jpg)

cities with their ranged attack/attacking cities dont pop up  combat info window.

and one aditional question, but its just question bcoz i play  Gandhi first time, but  shouldnt every follower in a city exert pressure no matter if in own or  foreign? bcoz i  smuggled 7 followers into one of russia city via trade route(over sea) and just decided send it into another city and they are exerting none.

**Comment by LoneGazebo** [comment]
Re: foreign trade pressure, no, as pressure is 'from' city to city, not internal to a city. So if it has no neighbors of the same faith, it can't spread.

Re: city attack, try latest hotfix.
