### ISSUE TITLE
AI moves GP weirdly

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2685]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
AI is moving its Great Prophet outside and inside my range instead of just using him to enhance. Sure, the city's about to fall, but maybe he could've picked something helpful.

I think the second (later) save is correct, but IIRC the GP already spawned on 226th turn. I use regular 19th beta, but with the improved city view mod - should load regardless.
[single.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/539826/single.zip)

**Comment by Enrico-Swagolo** [comment]
Oy, it's gotten even weirder! The Great Prophet?... That city he was around wasn't the Holy City! I thought "it's walled, it has a wonder, it's GOT to be the Holy City!", but nope. The capital is their holy city, not that one.

The AI has seriously sent its second prophet to... sort-of convert its cities, but it got sidetracked and made him dance the wild dance instead of enhancing or being useful.

He could've just put the Prophet in a boat (he must've had embarking, he had Dromons) and embarked away, but instead he's let me kill the GP he has pointlessly sent there.

**Comment by ilteroi** [comment]
did the city have a lot religious diversions?

**Comment by Enrico-Swagolo** [comment]
Well, it would have for sure since I've adopted Piety and had Cathedrals everywhere, and the city is pretty much  surrounded by my cities from the west, north and north-east. After XX-YYY turns I could've converted it the natural way for sure, unless he had also taken Piety.

But still, it's less expensive for the AI to just use Missionaries after it has enhanced. I wouldn't ever waste my second GP on not-enhancing, I'd just declare war on those who have too much pressure on my cities if I had problems (does AI consider that? I always declare war on Gandhi soon after he founds).
