### ISSUE TITLE
AI keeps Great General on front of his army

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2686]
_1. Mod version (i.e Date - 4/23):_
19th October

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Basically, AI kept moving his Great General on a unit close to my city.

The problem is my city was surrounded by my 2 Legions and a Catapult. That didn't end well.

Later save is what happened after and you can easily smack the hurt horse with a GG under it, previous turn one (autosave?) leads to a similar situation if  pretty much just end turn is clicked
[secundus.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/539846/secundus.zip)

I've also seen AI sometimes put ARchers in tile adjacent to my city even when I had a Legion or something strong inside.  It should try avoiding putting its troops in a position where they guy their opponents' cities with ranged. No save for that, though.

**Comment by LoneGazebo** [comment]
@ilteroi, something to look at?

**Comment by ilteroi** [comment]
well, general on frontline is forbidden (supposedly) and ranged unit on frontline is strongly discouraged.

will check

**Comment by Iamblichos** [comment]
strange...what's the crash dump look like when you try to load?
