### ISSUE TITLE
AI chooses a bad route to retreat

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2687]
_1. Mod version (i.e Date - 4/23):_
19th October

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Look at the Composite of the enemy somewhere in the lower east of the map, to the north-east of Rio DE Janiore. Despite being on a road and having lots of opportunities to retreat and heal, he'll instead move on the hill which my Legion can reach, ensuring his demise and free C/S/GAP/GGP for me.
[LOOKITDAARRERBOY.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/539986/LOOKITDAARRERBOY.zip)

**Comment by Enrico-Swagolo** [comment]
Oh, forgot to mention I use 
VALUES ('COMMUNITY_CORE_BALANCE_RESOURCE_REVEAL', 0);

in CommunityOptions.sql to improve comfyness of my games. That's the only thing I change.

**Comment by ilteroi** [comment]
can't load it, sorry. there's some sort of database incompatibility i've never been able to correct.

**Comment by Enrico-Swagolo** [comment]
I don['t know what it means. Is it me doing something wrong? Like, with my install? I can try make another game where I use all the basest version with no sql change

**Comment by ilteroi** [comment]
nah. tried that before. it just happens with some people. with other people it works. seems that IDs in the database are in a different order. don't know how that can happen or how to fix it.
