### ISSUE TITLE
"Unmet" CS Ally

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2688]
![8930_20161020064453_1](https://cloud.githubusercontent.com/assets/1131228/19545190/ced3ccd8-969d-11e6-822c-604deebaa0fd.png)
Shouldn't the contact with such City-States trigger the contact with their ally? They have LoS on allied CSes and thus can see my unit too.

**Comment by LoneGazebo** [comment]
Not in the code, no - LoS != contact, it is unit LoS that matters. Same with the fact that you can see an enemy city in fog of war but you don't meet them until LoS of units.

**Comment by Radost** [comment]
The vision provided by City-States isn't of "fog of war" kind.

**Comment by LoneGazebo** [comment]
I know, but the DLL treats 'owned' LoS (via units or cities) versus 'revealed' tiles (i.e. spies or allies) differently.
