### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2689]
_1. Mod version:_
10-19b with hotfix

_2. Mod list:_
https://mega.nz/#!qFciiKha!vTsBluu1WFerHtqSRJNW1-S2FtlxAdWxlzGpoH1Y-jM

_3. Error description:_ 
During Aztecs turn the game freezes while consuming more and more memory until it crashes.
I did have the problem with Aztecs on the previous turn, but it was only taking too long, not freezing.

---------------------------
Supporting information:
1. Log files:
https://mega.nz/#!fN0X1KKJ!cWJ2cGf1OVLRBV5EbH05-VVQ6jYtqbsA2IEj3Ycl1IQ
2. Save game :
https://mega.nz/#!vU8yQBaA!4VbIfUKXjTrCm2eMp6zZxzVaZJISuG1sVzh6dEdxv_w
3. CvMiniDump.dmp file:
https://mega.nz/#!iMEWVBbC!ZtCQpSMwbHjkutUTup07hfniPA1xJJnhfEXWTTUY628

**Comment by ilteroi** [comment]
cannot load it unfortunately.

but i do have an idea, will add a failsafe

**Comment by LoneGazebo** [comment]
Might've been the beliefclasses bug I fixed too.

**Comment by Radost** [comment]
@ilteroi 
The file you've posted indeed solved the crash, but it doesn't have a fix for #2677

**Comment by LoneGazebo** [comment]
We'll sync up our hotfixes later @Radost .

**Comment by bompus** [comment]
Same issue here. A couple of very slow end of turns, mem and cpu spike, unresponsive eventually.

**Comment by ilteroi** [comment]
savegame? maybe yours will work for me ...

**Comment by bompus** [comment]
@ilteroi I didn't get a save on the previous comment, but it happened again. Savegame on turn 300 https://www.dropbox.com/s/zwfsd21g1yvdlam/AutoSave_0300%20AD-2020.Civ5Save?dl=1.

It's either this turn or the next that required killing via task manager. Mem usage kept climbing steadily, I killed it once it got > 3GB. CPU spiked during the time as well, Civ5 unresponsive. Every time it happens, I get one really slow turn during AI moves, but it seems to recover. The following turn after this slowness is usually the fatal one, so it seems like something builds up.

**Comment by TechpriestEnginseer** [comment]
Yeah I have this same issue as well. I can't explain why, but the AIs seem to be definitely slow the more vassals there are.

**Comment by thunderbird14** [comment]
Had the same symptoms and tested the dll zipped above. It appears to be working (no more CTD's afterwards)

**Comment by LoneGazebo** [comment]
AI vassals can't even try to DOW, so it was probably that memory leak. It'll all get ironed out shortly.

**Comment by Radost** [comment]
He meant DoW'ing someone's else vassals probably.

**Comment by LoneGazebo** [comment]
That's also forbidden.

**Comment by TechpriestEnginseer** [comment]
but yeah ilteroi's hotfix fixed it.
