### ISSUE TITLE
Can't delete units

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#2691]
_1. Mod version (i.e Date - 4/23):_

10-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

Vox Populi Complete with EUI
+
Faster Aircraft Animations Version 3
Global - City State Airbases Version 3
Global - Commander Influence Borders Version 1
InfoAddict Version 22
Quick Turns Version 10
Really Advanced Setup Version 15
Religion - Fixed Prophets Version 2
UI - Enhanced Demographics Version 6
UI - Summary Antiquities Version 2
UI - Summary Luxuries Version 13
UI - Summary Specialists Version 11
UI - Trade Opportunities Version 28

_3. Error description:_ 

Pressing delete or the disband button doesn't disband units. Nothing happens.

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict.

**Comment by Oscar-IronTower** [comment]
Yeah, but i can't see which one, as I said on the other thread. Many thing seem out of place, as I don't get the option to capture/raze/puppet, nor I can't raze cities.

**Comment by Oscar-IronTower** [comment]
Yeah, but i can't see which one, as I said on the other thread. Many thing seem out of place, as I don't get the option to capture/raze/puppet, nor I can't raze cities.
