### ISSUE TITLE
No "Battle Results Preview" UI When Targeting Enemy Cities

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#2693]
_1. Mod version (i.e Date - 4/23):_
10-19b w/ EUI (fresh installation; did not overwrite previous mod installation)

_2. Mod list (if using Vox Populi only, leave blank):_
None.

_3. Error description:_ 
No "battle results preview" when targeting cities with military units. The UI element that displays the details of what the battle outcome should be for a military unit does not appear when targeting a city. Targeting other military units functions as normal.

_4. Steps to reproduce (optional):_
Battle Preview UI element does not appear when any unit type (melee, ranged, siege, etc.) targets a city for attack. Only tested using the whole run of Ancient/Classical units.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Did you grab the hotfix I posted yesterday evening?

**Comment by cdanger341** [comment]
I downloaded and installed whichever version that was live as of the evening of 10/19, at approximately 4pm CST. If a hotfix was posted after that time, I was unaware.

**Comment by LoneGazebo** [comment]
If the .exe for the installer is not 10-9-2, redownload and try it.

**Comment by LoneGazebo** [comment]
savegame compatible.

**Comment by cdanger341** [comment]
Okay, I will take a look and let you know once I get home this evening.

**Comment by cdanger341** [comment]
Okay, just checked and you were correct. It looks like I downloaded the version of 10-19 mere minutes before you uploaded the hotfix. I've got the hotfixed version now and the city UI appears to be working properly again.

**Comment by Enrico-Swagolo** [comment]
The 200-300 turns crash/memory leak hotfix breaks the city targetting UI though

**Comment by Iamblichos** [comment]
It'll all come together. Different fixes in two different DLL's.

**Comment by bompus** [comment]
@LoneGazebo I'm seeing this same issue in 11-6-1, except it is worse. I don't see the attack preview when hovering units or cities, previously it was just cities - any ideas?

**Comment by LoneGazebo** [comment]
Yeah, let me know.
