### ISSUE TITLE
City stack.

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2694]
`if(getMaxFriendlyUnitsOfType(pLoopUnit) > /*1*/ getUnitLimit() || isCity()) `

Looks like a problem here, as a unit in a city will get kicked out on doTurn. Was there a problem with the original code?

**Comment by Iamblichos** [comment]
getUnitLimit() checks for isCity()

**Comment by LoneGazebo** [comment]
Ah, that's my bad - I was testing an issue @radost brought up but forgot to remove that element.

**Comment by LoneGazebo** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/2675
