### ISSUE TITLE
GPT trade deal limitation works off AI GPT even if I am giving them the money.

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2695]
![8930_20161021034607_1](https://cloud.githubusercontent.com/assets/1131228/19586191/5a6835d0-976c-11e6-8a08-ae8aa3a57689.png)
![8930_20161021034613_1](https://cloud.githubusercontent.com/assets/1131228/19586198/6338c85a-976c-11e6-8003-22c2768181f3.png)
![8930_20161021034617_1](https://cloud.githubusercontent.com/assets/1131228/19586200/69fee11a-976c-11e6-8d49-c390cb147a63.png)

**Comment by joosegoose** [comment]
I'm not sure if it's related, but I'm noticing some funkiness with GPT deals as well.

![20161021144248_1](https://cloud.githubusercontent.com/assets/11132095/19609524/567bfdea-979d-11e6-9500-b7355377631d.jpg)
![20161021144243_1](https://cloud.githubusercontent.com/assets/11132095/19609525/56815c9a-979d-11e6-981a-87a80b387e60.jpg)

**Comment by LoneGazebo** [comment]
Yep, is known and will be fixed.
