### ISSUE TITLE
Freeze / CTD

### ISSUE THREAD

**Issue by Grabbl** [LoneGazebo/Community-Patch-DLL#2699]
_1. Mod version (i.e Date - 4/23):_
10-19b

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Game freezes / doesn't respond during AI turn (Inca). Can be closed only via Task Manager / Windows Prompt.
Log Folder and Save attached.
[CTD10_21_16.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/543854/CTD10_21_16.zip)

_4. Steps to reproduce (optional):_
Click "Next Turn", accept or refuse Assyria deal, game should crash when processing the turn of the Inca.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by matlajs** [comment]
same here on Indonesia turn. Game stop on Gajahs turn and after alt+tab to windows, game crashes/exits itself.

**Comment by ilteroi** [comment]
pretty sure it's the same issue as in #2689

mind trying the hotfix posted there?

it's only a workaround though, not a real solution, i hope i'll be able to load this savegame for a change

**Comment by matlajs** [comment]
do you want mine?

**Comment by ilteroi** [comment]
couldn't load the save from the OP, but i'd give yours a chance as well

**Comment by Grabbl** [comment]
the fix of issue #2689 seemed to work, getting over the critical turn now
