### ISSUE TITLE
growth bug

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2701]
![image](https://cloud.githubusercontent.com/assets/1358966/19612645/14dec156-97e8-11e6-8a71-1cfa08e21a3b.png)

this is turn 30!

**Comment by LoneGazebo** [comment]
hmm

**Comment by ilteroi** [comment]
![image](https://cloud.githubusercontent.com/assets/1358966/19613251/acbd1420-97eb-11e6-9875-08e5971002c6.png)

**Comment by ilteroi** [comment]
possibly my mistake - side effect from yesterday's distance calculation experiments

**Comment by LoneGazebo** [comment]
Ah, cool. I assumed something wacky had to be going on. :)
