### ISSUE TITLE
Upgrade costs

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#2703]
_1. Mod version (i.e Date - 4/23):_
 10/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Swordsmen have different upgrade costs. One costs 440 gold. For the other one I am charged 680.
The only difference I can think of is that, with me playing as huns, one comes from a camp and the other might come from a mouted unit.
I can rule out that either was build by me or provided by the autorithy policy.

![20161022150400_1](https://cloud.githubusercontent.com/assets/16065630/19620087/420c34f0-9875-11e6-8a43-a56750def403.jpg)

![20161022150413_1](https://cloud.githubusercontent.com/assets/16065630/19620080/2bb87dda-9875-11e6-9832-c3591a22b23a.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:

Save
[Upgrade enigma.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/545836/Upgrade.enigma.zip)

**Comment by LoneGazebo** [comment]
Yeah, swordsmen have a unique barbarian class for some reason. Is unfortunately intentional.

**Comment by Iamblichos** [comment]
So one of those units was a barbarian unit converted?

**Comment by Der-Zorn-Gottes** [comment]
I am not sure, but it`s my best guess.

So there is actually a difference between a unit that is converted and one that is created/gifted/build? Strange, but no big deal. Just wanted to report it just in case.

**Comment by Iamblichos** [comment]
Well the issue I believe is the fact that there are two database entries: UNIT_SWORDSMAN and UNIT_BARBARIAN_SWORDSMAN that have different costs. I'm assuming one of those is the latter that got converted by Hun trait. VP has done cost changes to units, and would not /did not change barbarian unit costs. So there you go.
