### ISSUE TITLE
City border growth grows towards a 4th ring tile first

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2705]
_1. Mod version (i.e Date - 4/23):_
19th 2b

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Try to get a city which has a wonder in its fourth tile (for whatever reason. I didn't notice that Barrier Reef first tile)

If you buy a tile before it on the third ring (or your border grows there), the city border growth AI will always go towards the 4th tile nat wonder first, ignoring the fact it can't even work it - no matter what other tiles it could be going for instead.

**Comment by ilteroi** [comment]
is that a problem?

**Comment by Enrico-Swagolo** [comment]
Dunno tbh, it just seems weird. But it's obviously not a big issue or something, just mentioning it in case it's considered a bug.
