### ISSUE TITLE
liberation=vassalage

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2706]
_1. Mod version (i.e Date - 4/23):_
10/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
i liberated one of Aztec city, captured by Japan and it made Monte my vassal, even though he is still in game and is average in score. i'll provide all needed after close game.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Hmm. I'll check. A bad 'resurrect' flag may have been set somewhere.

**Comment by matlajs** [comment]
![askia rar](https://cloud.githubusercontent.com/assets/21192402/19627740/9f20ecd8-994e-11e6-8d77-f60c287ea5dc.jpg)

**Comment by TechpriestEnginseer** [comment]
It's able to be replicated, just let a civ capture someone's city and liberate that.

The real question is if this bug continues what happens if its vassal liberate one of the master's city, who becomes the vassals then(I couldn't replicate this because the vassal is taking my city instead of liberating it)

**Comment by TechpriestEnginseer** [comment]
Not fixed, still able to be replicated. (There's a constant "Civilization_Name has agreed to be your vassal voluntarily everytime I liberate a city.)

**Comment by LoneGazebo** [comment]
But you were their original liberator, correct?

**Comment by TechpriestEnginseer** [comment]
Correct.

**Comment by LoneGazebo** [comment]
I'll fix.
