### ISSUE TITLE
Iroquois Forest City Connections not Working

### ISSUE THREAD

**Issue by muarB** [LoneGazebo/Community-Patch-DLL#2708]
_1. Mod version (i.e Date - 4/23):_
10/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I started 2 games as Iroquois and in both the forest/jungle tiles did not count towards a city connection.  The first game was mostly plains so I needed a mix of roads and forest tiles to make connections (which I noticed did not produce a connection symbol only after I had 5 cities.)  I started a second game and the start was heavily forested.  I made one settler and founded a city which had continuous forest tiles between it and the capital.  Again the symbol of a connection did not show up.  I don't know if it is only the symbol not showing up or connections are not being made.
_4. Steps to reproduce (optional):_
Just play Iroquois and make a 2nd city connected by forests or a combination of roads and forest and see if it works.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by muarB** [comment]
I tried your 10-24 version and it's still broken.  Here's a screenshot.
![iroquois1](https://cloud.githubusercontent.com/assets/23019463/19643628/12971952-99a0-11e6-9039-36103ef02c3d.png)

**Comment by muarB** [comment]
I tried to save some of the log but they are in a ".log" format which isn't allowed to be copied here.

**Comment by pandasnail** [comment]
I think its owned forests/jungles only. Don't play them much, so not 100.

Unrelated, how did you get rid of the left EUI ribbon? The right ribbon is outstanding, but I find the left unnecessary clutter most of the time.

**Comment by muarB** [comment]
I don't think my last game didn't needed owned forest tiles in the 10-12 version.  That was the first time I played them.  Owned tiles only would make the ability fairly useless, I hope that's not a change that was made.  A side benefit allowed caravans to go further in the early game in addition to the early cheap city connections.

You can un-check the unit display under options.

**Comment by pandasnail** [comment]
Yeah, if it was recently unowned tiles included, then its likely something else then.

**Comment by LoneGazebo** [comment]
I tried to replicate and couldn't. I'll

**Comment by LoneGazebo** [comment]
Ping @ilteroi get his thoughts (as he made some pathfinder and unit movement changes recently).

**Comment by muarB** [comment]
Ok great.  This mod has 24 hour support, incredible!  Let me know if you need any more data.  I tried to copy a game save file and some logs but I don't know how to get them in a format that the site will accept.

**Comment by pandasnail** [comment]
Github takes zip files, that's how I do it.

**Comment by ilteroi** [comment]
you probably need to extend the road into the forest on either side. that was an experimental change i forgot to mention ...

**Comment by muarB** [comment]
I tried the road extension and it works.  Was the change made to help with pathing or something?  The old way was much better.  I don't know if a new player will understand it let alone the AI.  But thanks for identifying the change.  Here's a save where I'm partially in the process of connecting cities.
[Hiawatha_0129 BC-0775.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/548012/Hiawatha_0129.BC-0775.zip)

**Comment by LoneGazebo** [comment]
@ilteroi ah I was already doing that, didn't realize that wasn't standard user practice. Let's revert if we can. Sorry for the aberrant 'Cannot Reproduce' tag @muarB.

**Comment by Iamblichos** [comment]
It does look stupid. The road has no direction with what would be the common forest path to the secondary city.

**Comment by LoneGazebo** [comment]
May look dumb, but it is a little unintuitive as it is now.

**Comment by Iamblichos** [comment]
Yeah I know...

**Comment by muarB** [comment]
The extra road sections needed in the new patch in some cases negates the forest connection ability depending on the forest layout.  I only saved one road section in one connection.  The random directionless roads are just a quirk to this one civ that gets free roads, it's kind of cool in a way.

**Comment by Iamblichos** [comment]
What's nifty too (for a future modder of CP), in the last patch I created an improvement entry in the DLL that allows an improvement to create a feature and then kills the improvement on build finish, and added to the BuilderTasking AI for Iroquois player to use this for route connection if it's set. Why build a road, just build a forest. :)

**Comment by TechpriestEnginseer** [comment]
Isn't this just what Reforestation's Lua from framedarchitecture does anyway. What's so different about this improvement entry?

**Comment by LoneGazebo** [comment]
The AI knows how to use it, I presume?

**Comment by Iamblichos** [comment]
The AI knows how to use it, plus the entry is generic not specific. A feature like that is better implemented in a DLL and not lua.

**Comment by muarB** [comment]
This topic is dead but I had a thought about the directionless single roads.  A forest trail sometimes comes to a clearing and people will set up "cairns' or piles of rocks to help pick up the trail again.  If you felt like it you could replace unconnected single road graphic for the Iroquois with something like that, or a totem pole, or a marked tree.  It's unnecessary in my view but if the single road bothers you that might solve it.
