### ISSUE TITLE
CTD w/Inca after turn 481

### ISSUE THREAD

**Issue by yarpirate** [LoneGazebo/Community-Patch-DLL#2709]
_1. Mod version (i.e Date - 4/23):_
10-19b

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
CTD after Inca turn 481. I've been able to get over the turn crash using the modified DLL linked in issue #2689 but I'm submitting this issue in case it provides more information for solving the crash itself.

_4. Steps to reproduce (optional):_
1. Load the attached save.
2. Click Next Turn
3. You should see all turns pass over until you reach the Inca's turn. The game should attempt to process this turn for a bit until crashing to desktop. The map can be navigated via the mouse so it doesn't appear anything freezes.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/546754/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[crashtest.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/546755/crashtest.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/546757/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by yarpirate** [comment]
Actually I should note that it seems that Inca's turns do seem to take a bit longer. They DO have the largest military in the game right now so that may be part of it, but I have noticed they take the bulk of the time for a turn to pass.

**Comment by ilteroi** [comment]
i've been able to reproduce the problem, the latest version has better handling for attacks with many units.
