### ISSUE TITLE
misc typos

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#271]
1. Splendor is still down as Landed Elite in the 'pedia
2. Stone works also has issues, with More Luxuries compatibility EUI says it lists Jade twice (+1 production, +2 production), and the TT is incorrect.

**Comment by LoneGazebo** [comment]
Fixed. Couldn't find the stone works bug, though. Looks fine in the SQL.

**Comment by Hokath** [comment]
Ah I found it, it was my fault, nothing to do with CBP
