### ISSUE TITLE
CS quest: liberate a city under our own control

### ISSUE THREAD

**Issue by Skidizzle** [LoneGazebo/Community-Patch-DLL#2710]
ver. 10-12
advanced setup 15
infoaddict 22
thals flag promos 7
more great works 3
unit path viewer 10

A hostile personality Hanoi wants me to liberate Antwerp, from Hanoi. Also, Hanoi doesn't have access to improved luxes in Antwerp territory.

Antwerp is overrun by barbs, Hanoi captures Antwerp. 

It would be amusing if this quest situation was left in for irrational type CD's

**Comment by LoneGazebo** [comment]
I mean, technically you can liberate it, but this is a simple issue of me not expecting CSs to capture other CSs!
