### ISSUE TITLE
Traded luxuries not being made available for trade agreement renewal

### ISSUE THREAD

**Issue by jantjeuh83** [LoneGazebo/Community-Patch-DLL#2711]
_1. Mod version (i.e Date - 4/23):_
24-10

_2. Mod list (if using Vox Populi only, leave blank):_
Only the Community Patch

_3. Error description:_ 
I'm having a weird issue with trading, specifically with other civs trying to renew an existing trade agreement for my luxuries. I get the trade screen where they ask to repeat the trade, say 10 GPT for Crabs, but the trade indicator says it's 'impossible' and when I click on 'Propose' the other leader also refuses the trade. It seems that the luxury in question (Crabs in this case) is not being made available (in advance) to repeat the trade, in the list with available luxuries for trade it's not shown either. I guess this only happens when only one 'copy' of the luxury in question is available for trading. Anyone else encounter this?

_4. Steps to reproduce (optional):_
Make a trade with a foreign civ for a luxury that you only have two copies in total of (so one copy available for trade). When the trade agreement expires, the other leader will request a prolongment of the trade, but the traded luxury does not become available for trading again, so you cannot confirm the trade.

Edit: added a save game below. Hit 'Next Turn'.

[Ramesses II_0360 AD-1700.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/548710/Ramesses.II_0360.AD-1700.zip)

**Comment by jantjeuh83** [comment]
I can attach a save if necessary?

**Comment by jantjeuh83** [comment]
Will add a save soon, when a trade agreement is about to expire.

**Comment by jantjeuh83** [comment]
Weird, this time the trade agreement did work, even though I only had two copies of the luxury in question. Seems like something else is causing the issue. I will make saves before any trade agreement expires, perhaps the issue will pop up again.

**Comment by jantjeuh83** [comment]
This only occurs when the trade renewal is attempted before the original trade deal runs out.

**Comment by jantjeuh83** [comment]
Added a save game. To reproduce the issue, load the save game and then hit 'Next turn'. Polynesia will attempt to renew a trade deal, which fails.

**Comment by LoneGazebo** [comment]
Thanks! Will debug.

**Comment by jantjeuh83** [comment]
I also think that the involved luxuries of the other civ do not get 'released' (to be tradeable again) after the renewal fails. At least, in some cases (not sure if it was all of them) I could not set up a new trade afterwards because the extra luxuries were missing from the other civ's resource list. Will investigate, maybe I'm mistaken.

**Comment by LoneGazebo** [comment]
The save above is behaving oddly. Do you have a slightly earlier save?

**Comment by jantjeuh83** [comment]
I'll attach an earlier save in a sec.

Note that I'm only using the Community Patch, no other mods.

**Comment by LoneGazebo** [comment]
Yep, I can load it, I just can't get it to advance a turn.

**Comment by jantjeuh83** [comment]
Here you go. I've added two saves, one 10 turns earlier (turn 350), the other one a single turn earlier (turn 359). The trade agreement with Polynesia expires in turn 360, so you should get a prompt for renewal when going into turn 361.

[Ramesses II_0350 AD-1650.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/549243/Ramesses.II_0350.AD-1650.zip)

[Ramesses II_0359 AD-1695.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/549244/Ramesses.II_0359.AD-1695.zip)

**Comment by LoneGazebo** [comment]
Thanks!

**Comment by LoneGazebo** [comment]
Drop in CP folder, replace DLL, test and report back: https://mega.nz/#!vdsXWZTD!_cFeECq75XfNW4Cl4dm541wWLSX_sA5bBRLuGTbViJw

**Comment by LoneGazebo** [comment]
(tested and worked for me)

**Comment by jantjeuh83** [comment]
Will do later today, thanks.

**Comment by Grabbl** [comment]
had the same bug, the modified DLL worked for me

**Comment by jantjeuh83** [comment]
Seems to work. Good job! Will re-open if the issue resurfaces.
