### ISSUE TITLE
Tithe founder belief does not work

### ISSUE THREAD

**Issue by jantjeuh83** [LoneGazebo/Community-Patch-DLL#2712]
_1. Mod version (i.e Date - 4/23):_
24-10

_2. Mod list (if using Vox Populi only, leave blank):_
Only CP

_3. Error description:_ 
I have founded a religion and selected Tithe as the founder belief, but I do not get any income from it. At least, it is not mentioned in the gold overview.

_4. Steps to reproduce (optional):_
See attached save.

[Ramesses II_0342 AD-1610.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/548637/Ramesses.II_0342.AD-1610.zip)

**Comment by LoneGazebo** [comment]
The gold is applied to the holy city.

**Comment by jantjeuh83** [comment]
Ah, so that the +% gold bonuses of the holy city are applied on top of that? Makes sense, good change.

**Comment by LoneGazebo** [comment]
Well, you've got conflicting information here. You say policy in the header, but founder belief in the text. Which is it?

**Comment by jantjeuh83** [comment]
Whoops, sorry about that. Confused the two terms. Talking about the Tithe founder belief.

**Comment by LoneGazebo** [comment]
That's the 'gain gold when you convert a city' one?

**Comment by jantjeuh83** [comment]
No, the one that gives you +1 gold for every 4 followers in converted cities.

**Comment by LoneGazebo** [comment]
Alright, so yeah, that gold should appear in your holy city's gold per turn in the city view screen. Formerly gold like that just appeared at the 'national' level (and thus could not be affected by modifiers et. a.l).

**Comment by jantjeuh83** [comment]
Yeah, that's a good change. Makes it more useful in the later game, now that the different bonuses can affect it. Also more realistic in a sense, I guess.

**Comment by LoneGazebo** [comment]
Yep! Report back if not working like that for you.
