### ISSUE TITLE
kStream issue

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#2714]
for some reason on loading a save, these either aren't getting read right or aren't writing right:

```
kStream >> iNumEntries;
m_aiNumPledgesDomainProdMod.clear();
for (int iI = 0; iI < iNumEntries; iI++)
{
	kStream >> m_aiNumPledgesDomainProdMod[iI];
}

kStream >> iNumEntries;
m_aiFreeUnitClassesDOW.clear();
for (int iI = 0; iI < iNumEntries; iI++)
{
	kStream >> m_aiFreeUnitClassesDOW[iI];
}
```

```
kStream << m_aiNumPledgesDomainProdMod.size();
for (uint ui = 0; ui < m_aiNumPledgesDomainProdMod.size(); ui++)
{
	kStream << m_aiNumPledgesDomainProdMod[ui];
}
kStream << m_aiFreeUnitClassesDOW.size();
for (uint ui = 0; ui < m_aiFreeUnitClassesDOW.size(); ui++)
{
	kStream << m_aiFreeUnitClassesDOW[ui];
}
```

Originally, when I wrote these, I had them setup just the way you edited in the last release. Never could get them to work on a loaded save. Had to read/write them straight in, but not sure why(?). They fire correctly as long as you don't save and reload.

**Comment by ilteroi** [comment]
this part is strange.

m_aiNumPledgesDomainProdMod.clear();
for (int iI = 0; iI < iNumEntries; iI++)
{
    kStream >> m_aiNumPledgesDomainProdMod[iI];

after clear() the size of the vector is zero. better use resize(iNumEntries,0) or similar

**Comment by Iamblichos** [comment]
There's quite a few set that way in the read function and I'm not sure what the rhyme or reason was/is.
For example:
```
kStream >> iNumEntries;
m_paiMovesChangeUnitClass.clear();
for (int iI = 0; iI < iNumEntries; iI++)
{
	kStream >> m_paiMovesChangeUnitClass[iI];
}
```
Trait_MovesChangeUnitClass

Don't see where that's used in the CBO.

**Comment by LoneGazebo** [comment]
We can revert to a strait kstream model if needed.

**Comment by LoneGazebo** [comment]
The real big issue was that MAX_INT in the processpolicy function.

**Comment by Iamblichos** [comment]
Yeah I changed it back....I'm curious about those others set with that format though.

**Comment by Iamblichos** [comment]
I guess I'm now INT_MAX man, the things you do when your flying by the seat of your pants.

**Comment by LoneGazebo** [comment]
#neverforget
