### ISSUE TITLE
Number of delegates available for voting in WC is incorrect

### ISSUE THREAD

**Issue by jantjeuh83** [LoneGazebo/Community-Patch-DLL#2716]
_1. Mod version (i.e Date - 4/23):_
24-10, with the bug fix for #2711 

_2. Mod list (if using Vox Populi only, leave blank):_
Only CP

_3. Error description:_ 
See screenshot. I have 4 delegates, yet can only vote with 3 (note that it says 'Delegates Remaining: 3', yet the icon above correctly lists 4 delegates).

![civ5screen0001](https://cloud.githubusercontent.com/assets/23015914/19685386/96c21e58-9abc-11e6-9190-d2ca8094faa7.jpg)

**Comment by jantjeuh83** [comment]
Will attach a save file when the next WC vote comes up.

**Comment by jantjeuh83** [comment]
I noticed after the votes were counted that apparently 1 of my delegates votes was automatically cast on the second proposal 'Ban Luxury: Citrus', thus explaining the missing delegate. The three I cast on the first proposal were correctly counted. Very odd.

**Comment by Radost** [comment]
Are you sure you didn't sell your vote at some point?

**Comment by jantjeuh83** [comment]
I'm stupid, that was it. I clicked it away.
