### ISSUE TITLE
CTD on Barbarian Turn

### ISSUE THREAD

**Issue by Katonda** [LoneGazebo/Community-Patch-DLL#2717]
_1. Mod version 1.10.24

_2. Mod list (if using Vox Populi only, leave blank):_

Vox Populi (Auto installed first, before any other mods)

All from the 'Compatible "out of the box"' list:

- Unit Path Viewer
- Quick Turns
- Civ Names by Policies
- Calypso's Colored Religious Icons (Basic)
- Reseed!
- Fortress Borders
- Promotions - Expansion Pack
- Reforestation
- Barbarians - Unlimited Exp
- Really Advanced Setup
- Ingame Editor
- Faster Aircraft Animations
- R.E.D. Modpack
- InfoAddict

_3. Error description:_ 
Marathon Game. Turn 72. Songhai. Raging Barbarians. 7 Players, 12 Cities, Inland Sea.

Ending my turn cycles through enemy players and city states as usual, crashes to desktop when barbarian turn starts. Reloaded one turn earlier from autosave. Bug still came up on turn 72.

---------------------------
Supporting information:

1. Log files
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/550736/Logs.zip)

2. Save game:
[AutoSave_0072 BC-2920.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/550710/AutoSave_0072.BC-2920.zip)

3. CvMiniDump.dmp is empty (can't be uploaded)

**Comment by WobblyWombat** [comment]
I had the same problem. Version 10/24, straight CTD on turn 72 on barb turn, empty MiniDump, and RED Modpack installed. Tried disabling RED, but still didn't work. Was playin on DLC Scrambled Italy map.

Deleted all user files, deleted all mod files, reinstalled from scrath (without RED to debug) and tried a new game. Now it works I don't have the save anymore because I deleted everything like a dummy. I remeber a line from the xml log tho: Missing Entry for UNIT_BARBARIAN_HORSEMAN (don't know if that alone it could cause a crash).

**Comment by ilteroi** [comment]
for some reason i have trouble loading other people's saves, but anyway it might be fixed already. can you try this dll here and report back?

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/551249/CvGameCore_Expansion2.zip)

**Comment by Katonda** [comment]
Sure, I can try it, but where do I put it?

**Comment by ilteroi** [comment]
replace the dll in the MODS/Community Patch folder

**Comment by Katonda** [comment]
the saved game still crashes. do I need to try a new game?

**Comment by ilteroi** [comment]
there are three ways now

1. look for a file called CvMiniDump.dmp in your Civ5 folder (steam\SteamApps\common\Sid Meier's Civilization V) and post it here (may need to zip it first)

2. put this file in the same folder as the dll above. now when it crashes, there should be file called callstack.log in your logs folder (Documents\My Games\Sid Meier's Civilization 5\Logs). post it here (may need to zip it first). the file may be empty, in that case this method doesn't work obviously.

[CvGameCore_Expansion2_pdb.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/551456/CvGameCore_Expansion2_pdb.zip)

3. hope that gazebo can load your save

**Comment by Katonda** [comment]
Hi, thanks for your feedback and help. The dmp file is empty, ie. 0kb. Can't zip it. Ran the game with the pbd file and new DLL and the callstack's timestamp updated, but is empty.

Here is the log from just now:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/551514/Logs.zip)
