### ISSUE TITLE
DifficultyMod.xml oddities

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#2719]
_1. Mod version (i.e Date - 4/23):_ 10/24
_2. Mod list (if using Vox Populi only, leave blank):_
_3. Error description:_ 

[VP difficulty.pdf](https://github.com/LoneGazebo/Community-Patch-DLL/files/552791/VP.difficulty.pdf)

Errors (in RED on the .pdf) : 
- AIBarbarianBonus is 50 in Settler, should be 30.
- AIWorldTrainPercent is 95 in Prince, should be 100.
- AIUnitUpgradePercent is 80 in King, should be 90.

Irregularities (in YELLOW on the .pdf) : 
- AdvancedStartPointsMod is 80 in Chieftain, 85 seems better.
(Because 90 -> 80 -> 80 -> 75 make no sense)
- ResearchPercent is 98 in Settler, 95 (or 90, or 100) seems better.
(Because 98 make no sense)
- NoTechTradeModifier is 20 in King, 15 seems better.
(Because 20 -> 20 -> 10  -> 5 make no sense)
- AITrainPercent, AIConstructPercent, AICreatePercent, AIUnitUpgradePercent are 90 in Emperor, 85 seems better.
(Because 95 -> 90 -> 90 -> 80 make no sense)
- AIGrowthPercent evolution is absurd. It switch between the values of  AIUnhappinessPercent and AITrainPercent. Taking always the AITrainPercent value seems better.
(So 100 instead of 95 in Warlord, 95 instead of 90 in Prince, and 85 instead of 90 in Emperor)
- AIAdvancedStartPercent is 150 in Warlord, 155 seems better.
(Because current evolution is 100 -> +35 -> +15 -> +20 -> +15 -> +15 -> +15 -> 15, so switching the +15 and the +20 feel better)

**Comment by LoneGazebo** [comment]
I'll give er a look. Daniel!

**Comment by LoneGazebo** [comment]
Danke.* My phone doesn't like that word.
