### ISSUE TITLE
UI and Culture

### ISSUE THREAD

**Issue by Erocco** [LoneGazebo/Community-Patch-DLL#272]
Three issues that I've noticed. I only have CP installed, I am only interested in CP.

1. No load button available if I want to load a game while I am in the game.

2. Every time I kill a Barbarian stationed in an encampment and have the Honor tree chosen I get awarded 20 culture on top of the culture for killing the barbarian unit. Outside the encampment the proper honor is awarded.

3. All ranged units don't properly show the red border when I want to range attack/bombard with them. I found this but the link is not available anymore.

"LoneGazebo commented 25 days ago
That bug exists because of a change in directional enums in the CP. Try this: https://www.dropbox.com/s/0jwm3sfldxixn15/Bombardment.lua?dl=0

Download this file, and drop it in the UI folder of the Bombardment mod of Whoward, Should fix while using CP."

**Comment by LoneGazebo** [comment]
https://www.dropbox.com/s/0jwm3sfldxixn15/Bombardment.lua?dl=0

Here's a link for you for the bombardment file. I'll add something to the 'how to install' page with this.

#1 is normal - you should never reload a custom DLL in-game.

#2 sounds like overlap with the CBP - I'll fix.
G
