### ISSUE TITLE
Incense

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#2721]
_1. Mod version (i.e Date - 4/23):_

10/19
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Just a minor thing, but Incense is not associated with any corporation.

**Comment by LoneGazebo** [comment]
Pretty sure it is tied to CORPORATION_HEXXON_REFINERY.

**Comment by Der-Zorn-Gottes** [comment]
Indeed.
Lesson learned, don't do research at night.
