### ISSUE TITLE
Problem with Great Artist

### ISSUE THREAD

**Issue by Pakur** [LoneGazebo/Community-Patch-DLL#2722]
_1. Mod version (i.e Date - 4/23):_Version 10-12 executable

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ On turn 432 I generated a Great Artist named Onatas.  When I tried to expend him to create a work of art, it opened a splash screen for "Grecian Pottery".  However, the splash screen image was so large that it filled most of my screen and there was no button viewable to click on that would allow me to close the splash screen.  This meant there was no way for me to proceed with the game.  Reloading did not help.  The only thing that worked was to instead use the Great Artist to start a golden age instead of creating a work of art.  Recommend that the splash screen image for "Grecian Pottery" be resized so it is smaller.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Just hit esc if that happens. Can happen in vanilla as well.

**Comment by Pakur** [comment]
Thanks for the tip!
