### ISSUE TITLE
unsneaky sneak attack

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2725]
this is supposed to be a sneak attack ... on sparta!

![image](https://cloud.githubusercontent.com/assets/1358966/19801601/255592ea-9d00-11e6-9be7-741d413aa718.png)

maybe target selection needs to be tweaked a bit

**Comment by LoneGazebo** [comment]
They should DOW the next turn though, as they've encountered the enemy. 

Also fixed a typo in setupsinglearmy. Naval attacks always fail because the pDeployPlot->iswater() should be negative, not positive!

**Comment by Enrico-Swagolo** [comment]
What are those yellow promo icons above? What is the mod called? Do tell me, for I desire to get them myself.

**Comment by ilteroi** [comment]
nah. they moved over to sparta, then made a demand i didn't want to fulfill, then declared war and turned on corinth after all. conquered it after two turns of siege. smooth, except for the lost time, which i could have used to build an army.

the mod is called flag promotions (not to be confused with thal's flag promotions, that one is not compatible)

**Comment by LoneGazebo** [comment]
That's odd, did we remove the trigger for the AI to 'successfully end' operations if they run into a target unit or target land?

**Comment by LoneGazebo** [comment]
That makes sense.

**Comment by ilteroi** [comment]
nevertheless corinth should have been the target in the first place. can you take a look?

**Comment by LoneGazebo** [comment]
Yeah, looking at it now. Going to amp up the desirability for the 'closest' city for a sneak attack.

**Comment by LoneGazebo** [comment]
@ilteroi, quick question - is StableSortItems in cvmilitaryAI sorting high > low, or high < low? I can't seem to find the code.

**Comment by ilteroi** [comment]
depends on the definition of operator < for the item type

**Comment by LoneGazebo** [comment]
Nevermind, looks fine, false alarm.

**Comment by LoneGazebo** [comment]
Another question: 

In int CvMilitaryAI::GetCachedAttackTargetLandDistance should a value of -1 be permitted as a cached value? Seems like it should, as land distances don't change (and aren't affected by things like ocean movement or coastal movement). Thoughts? (I see lots of calls to refresh the land distance cache in custommods.csv).

**Comment by ilteroi** [comment]
well, -1 would mean unreachable right? so it's valid. but it might change anyway because of open borders or razed cities. so you need to refresh it nevertheless.

**Comment by ilteroi** [comment]
switched to a visibility check and it works beautifully. no chance to defend.

**Comment by LoneGazebo** [comment]
Great!
