### ISSUE TITLE
AI is back to settling weird cities

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2726]
_1. Mod version (i.e Date - 4/23):_

Current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

AI in the current version will sometimes  settle questionable cities which barely have any useful tiles in the middle of my cities (basically if my 2 cities expanded their borders to the max, the city wouldn't be able to spawn). Sometimes, the tiles aren't that bad, but I've seen them settle near just irrelevant bonus resources. I can take it easily since I have a strong military (I often wait until it grows a bit before razing to maximise yield gain from Hero Worship).

Sometimes, they'll go through half the globe to settle an island city that - I admit - is not the worst, but it won't help them any since my Triremes + Dromons can take it anyway. That of course results in me getting free Hero Worship Faith+GA points.

**Comment by LoneGazebo** [comment]
@ilteroi, should we clamp distance further?

**Comment by ilteroi** [comment]
i'm seeing it too, sometimes even their second city is on the other side of their continent. on the other hand. they build their settlers rather late, so they have a larger radius. and i'm playing classical start, which might add to this effect.

anyway action items:

1. at least on advanced starts, you can found 4 cities in nice spots before the AI even gets going. AI needs to put higher priority on settlers.
2. distance dropoff formula needs to be revisited.
3. fleet deployment should consider those vulnerable island cities

**Comment by LoneGazebo** [comment]
1.) I'll up settler flavor a bit.
2.) Agreed
3.) There was a hard distance clamp placed on naval sentries recently (by you?) for performance reasons. We could increase that. I don't think it makes that much difference.

**Comment by ilteroi** [comment]
3. isn't there something else besides sentry moves? patrol? mobile reserve? maybe even garrison?

**Comment by LoneGazebo** [comment]
I don't think garrison or mobile reserve allow for naval units. Naval Patrol and Naval sentry are unique to naval units.

**Comment by ilteroi** [comment]
ExecutePatrolMoves should be doing exactly what we need. hmm

**Comment by ilteroi** [comment]
but it's sorting by proximity instead of danger. wonder if that is the best way

**Comment by LoneGazebo** [comment]
That's what navalsentry does.

**Comment by LoneGazebo** [comment]
i.e. PlotSentryNavalMoves uses naval sentry plots defined by danger/threat/bastion, etc.

**Comment by ilteroi** [comment]
danger was the wrong word. GetThreatenedCities() is what we need.

**Comment by jantjeuh83** [comment]
Just wondering, is this only in CBP or also in the CP? I've noticed the AI make some odd settlement choices as well.

**Comment by LoneGazebo** [comment]
@ilteroi right, that's what it does.
