### ISSUE TITLE
"Mastery" never activates itself if it is not triggered by the player

### ISSUE THREAD

**Issue by Sheepou** [LoneGazebo/Community-Patch-DLL#2728]
_1. Mod version (i.e Date - 4/23):_10/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
If you choose "Mastery" when you found your religion ( +2 yields per specialists ) the yields are never added unless the player remove and add at least 1 specialist.
If the player doesnt do this, the yields won't be added even after playing normally during xx turns.
For my test I had 1 artist, 1 scientist, 1 merchant and 1 engineer and even though you could see the new value on the right part of the city screen for gold for example, it is not updated on the left part, and never taken in count in your new gold per turn ( until you add or remove 1 specialist ) 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:

4. Screenshots (optional):
Here you can see on the right the visual update but on the left it is still 6 from building ( 5 + 1 ) and only 3 for the specialist ( and my gold didnt change bewteen before and after the religion until I did the trick ) 
![after prophet](https://cloud.githubusercontent.com/assets/23124937/19826195/0b9ac782-9d85-11e6-8598-9d36fb85a709.png)

Ps This is the first time I usse github, plz tell me if I did something wrong here

**Comment by Sheepou** [comment]
While I am at it just a minor thing. I was playing as Austria during this game and the loading screen says +15% great person when a marriage occurs. When I click on a city state and click on marriage it says +10%.

**Comment by LoneGazebo** [comment]
It works, but the tooltip just doesn't update.
