### ISSUE TITLE
Events issues

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#2729]
Latest version, thought I haven't been able to get a game in for a few versions now ( :( )
The events menu got a revamp at some point, but if the text spills over onto a newline it will overlap with whatever is below it. E.g.
![20161029151122_1](https://cloud.githubusercontent.com/assets/11889219/19830207/87b21716-9dea-11e6-9b3d-86cd5ed65f7f.jpg)

I also noticed the frequency of all events has gone down. I haven't seen a single farm get flooded or hit by pestilence yet. Is this intentional or am I experiencing severe bad(/good) luck?

**Comment by pandasnail** [comment]
A couple versions ago, there were basically no events, its gone back up some since then, but its still not what it was a month or so ago in frequency, yeah, at least as far as I can tell in the suddenly rare games where I don't get crushed early.

**Comment by LoneGazebo** [comment]
That's weird re: event window. @JFDaly I'm shite with lua, mind taking a look and helping me figure out what I've goofed?

@pandasnail event rarity should be back (roughly) to a little below 'normal.' The new system is more randomized than before, which is probably why it feels a little less frequent.

**Comment by JFDaly** [comment]
Sure, I'll take a look.

**Comment by JFDaly** [comment]
Ok, try replacing the original files with [these](https://drive.google.com/file/d/0B2KfUlRX1owlODdKSkhzOUlTS2s/view?usp=sharing). I just put the event info in a stack, so that they won't overlap with each other.

**Comment by LoneGazebo** [comment]
Awesome! I've also noticed that changes to resolution cause some oddities with the scroll bar - haven't been able to figure that out either. :)

**Comment by JFDaly** [comment]
Like smaller resolutions? Okay, I can check that out.

**Comment by JFDaly** [comment]
Alright, try [these] (https://drive.google.com/file/d/0B2KfUlRX1owlODdKSkhzOUlTS2s/view?usp=sharing), seem to do the trick on the lowest resolution. Let me know if there's anything else you need with the overview.

**Comment by pandasnail** [comment]
Well, its not just the total number of events I mean, it still seems like there is a smaller pool of events to choose from. Like, I got Brazil's Unique Event twice in a row, and often I get one UE the whole game, and like Hokath said, still no pillaged farms. Its not the largest sample of turns, but here's another events log if you want to take a look.

[eventslog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/560450/eventslog.zip)

**Comment by TechpriestEnginseer** [comment]
I've noticed this as well, but I'm liking this likelihood of events occurring. It's not too repetitive to snowball you in nor too repetitive to make you go crazy(when has we ever heard of a guy complaining about farms being destroyed)? However, there seems to be a definite smaller pool of events. Could this bug be the same from the old versions?

**Comment by LoneGazebo** [comment]
I'll check.

**Comment by LoneGazebo** [comment]
@JFDaly,

Event panel still acting up:

![20161102222556_1](https://cloud.githubusercontent.com/assets/7849458/19954102/5f9a9366-a14b-11e6-8b04-42a9122a1d47.jpg)

See how the event result is 'staggering' one event down?

**Comment by JFDaly** [comment]
How's [this?](https://drive.google.com/file/d/0B2KfUlRX1owlODdKSkhzOUlTS2s/view?usp=sharing) I made some additional changes to straighten up the event instances, but can undo them if you want. I included screenshots of said changes in the zip, as Imgur is dead. Let me know if you have anymore issues.

**Comment by LoneGazebo** [comment]
Looks great! You are a wizard.
