### ISSUE TITLE
trebuchet is too strong

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2730]
so i just got crushed by the songhai and their trebuchets. their play was quite impressive, so i'm happy, but still without setting up i think the trebuchets are too strong. CS (not RCS) needs to be reduced to make them a bit more vulnerable.

my feeling is that for normal ranged units (archer line), RCS / CS should be about 1.5. for siege units (catapult line) RCS / CS == 3 is appropriate.

so that means

catapult: currently 12/5 -> 12/4
trebuchet: currently 22/10 -> 24/8
cannon: currently 35/15 -> 36/12
artillery currently 45/22 -> 45/15

opinions?

**Comment by TechpriestEnginseer** [comment]
But if catapults are 4 CS that means scouts can literally take them out!

**Comment by Radost** [comment]
How about reducing their effectiveness against land units instead? I don't dig paper-thin units in a game with units having up to 5 movement points.

**Comment by ashendashin** [comment]
I agree with Radost. Siege units should remain just that; siege units. I barely use archers anyways.

**Comment by LoneGazebo** [comment]
I think a -25% against land units should suffice to bring them down a bit.

**Comment by ilteroi** [comment]
this is not about offense but about defense.

siege units are supposed to be powerful but fragile. at least in my mind.

weakening the offense is not the right way to handle it. we need to weaken the defense. against melee specifically. and that's CS. no need for fancy promotions.

**Comment by LoneGazebo** [comment]
I do worry about them being too glassy.

**Comment by ashendashin** [comment]
Hmm. Do you mind me asking what lead you to thinking siege units(I'd like to focus on the siege bit) should be glass cannons?

In my opinion, production and terrain make it difficult enough to keep a sieges flank covered around the time trebuchets are relevant. Making them even more vulnerable would spell disaster from mounted units in just about every situation that someone has them.

I can imagine certain units being more effective against them, such as skirmishers and infantry, but too much and I think it would make a siege much more expensive.

**Comment by ilteroi** [comment]
if siege units are not fragile, where's the difference to regular ranged units? why should anyone build a crossbowman over a trebuchet?

**Comment by ashendashin** [comment]
I completely agree that there should be a bigger distinction between the two. I don't believe making them vulnerable to all forms of melee damage to be the answer.

I mean, it would just make it more difficult for the AI than anything. Flanking would become the new big thing to break all sieges from superior armies. Or they'd just be set to finding alternative ways to lay a siege...raising the question "Why bother with trebuchets when my heavy skirmisher spam works and doesn't die instantly?"

**Comment by Iamblichos** [comment]
Crossbowman have fortification so that's a bonus on the outset. Trebs, if anything, should not be weak on attack city or no city. All else, they ought to have some sort of splash damage against surrounding units but they don't, so they shouldn't be nerfed. In reality, they should be stacked with a real military unit since they aren't a real unit but utilitarian hardware, but they are not (stacked). I think the best solution is to knock them down a combat strength or two as iilteroi. 10->8 or 9. Crossbowman are 13 CB which is much more defensive.

**Comment by Iamblichos** [comment]
I also think all siege units should either have indirect fire or indirect fire as an available promotion. Why do they, individually,need to see the enemy, when a spotter is all that would be needed to volley an attack in reality.
