### ISSUE TITLE
Succesful coup in a city-state you are at war due to war with their ally doesn't automatically switches their allegiance

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2731]
Instead it requires to manually stop the war with them to acquire the ally status.

**Comment by LoneGazebo** [comment]
Interesting – vanilla bug? I'll take a look. If you have a savegame that'd be nice.

**Comment by Radost** [comment]
No save, and I had this situation across several versions already, just didn't bother reporting it. Easiest to test is put a spy and then DoW its ally.

**Comment by LoneGazebo** [comment]
Takes a while to set that up. A save would be grand if you get one.

**Comment by LoneGazebo** [comment]
I think I've fixed w/o a save, we'll see.
