### ISSUE TITLE
can't make peace despite warscore 100

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2734]
![image](https://cloud.githubusercontent.com/assets/1358966/19836086/12c33b9e-9e97-11e6-9106-dab9840a61ee.png)

**Comment by ilteroi** [comment]
maybe i should add that this was more than 10 turns after conquering their capital.

**Comment by LoneGazebo** [comment]
That's weird. What does the diplo log for peace say for Darius?

**Comment by ilteroi** [comment]
164, Persia VS. ChinaValue Needed: 010. Value Have: -05.
