### ISSUE TITLE
Celtic Morrigan pantheon not proccing

### ISSUE THREAD

**Issue by thecrafybee** [LoneGazebo/Community-Patch-DLL#2736]
_1. Mod version (i.e Date - 4/23):_10/24

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP + EUI
VP 1-6
VP 7 Community Events
VP 8 Events & Decisions - CBO
IGE v39
Music Changer v2

Gameplay
JFD Cul Div + Soundtrack
Maps - Rotate Start Position v11
Quick Turns v10
World Congress Reformation v3

Custom Civs
Confederate States + CBO Patch
MC LITE's Nubia + CBO Patch
The Olmecs + CBO Patch

Custom Wonders
Brazilian Wonder Pack
Grand Bazaar
Gyeongbokgung Palace
Korean Wonder Pack
Milau Viaduct v2
National Wonders Collection v3
Valley of Kings
White Sands Missile Range v2
Wonder Race v6

Units
Unit - Herdsman v12

UI
Antiquity Site Icons
Flag Promotions v7
Improved City View v9
Info Addict v22
Map Labels v6
Meaningful City State Colours 
Pontoon Bridge V19
Reforestation v8
UI - Antiquity Tooltips v5
UI - City Production v15
UI - Enhanced Demographics v6
UI - Summary Specialists v11
UI - Trade Opportunities v28

_3. Error description:_ 
Not getting the Gold, Culture or GAP from kills despite taking the special Celtic Pantheon that gives those yields.

The Science and Culture procs from the Honour tree are proccing, as is the Faith on kill from my Pictish Warriors, but so far my Gold and GAP counters are not increasing and the Culture I get from kills is what I expect from just taking the Honour tree opener.

I noticed that they weren't proccing from barbarians so installed IGE and tried killing CS and major civ units but to no avail.

I reloaded and took Epona, the proc on border growth pantheon, and that worked.  Reloaded again and retook Morrigan and still not working.

_4. Steps to reproduce (optional):_
Start as Celts, take Morrigan pantheon, kill things.
---

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.
1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
4. Screenshots (optional):

**Comment by Radost** [comment]
Works fine for me:
![8930_20161031143923_1](https://cloud.githubusercontent.com/assets/1131228/19849987/e7eed8f6-9f77-11e6-9dcf-96d009a262c5.png)

**Comment by LoneGazebo** [comment]
Likewise – I assume that you've got a mod conflict in there somewhere. Thanks for confirming @Radost .
