### ISSUE TITLE
Visual issues in city view screen (non-EUI)

### ISSUE THREAD

**Issue by jantjeuh83** [LoneGazebo/Community-Patch-DLL#2739]
_1. Mod version (i.e Date - 4/23):_
28-10

_2. Mod list (if using Vox Populi only, leave blank):_
non-EUI VP 

_3. Error description:_ 

In the full-size city view (see below) the happiness 'resource' has been added to the 'resources' list, but the sizes of the grids (probably defined in CityView.xml) have not been properly updated to fit, causing misalignment of the background images in the top left.

![civ5screen0005](https://cloud.githubusercontent.com/assets/23015914/19856934/f123b780-9f7b-11e6-8eb5-399140311fd9.jpg)

In the small-size city view (see below) the value for the happiness 'resource' is not listed at all in the top left, though the other 'resources' are. Looks like CityView_small.xml also needs updating.

![civ5screen0006](https://cloud.githubusercontent.com/assets/23015914/19856937/f7873fa2-9f7b-11e6-9f44-b5a4643b4f62.jpg)

**Comment by LoneGazebo** [comment]
@jantjeuh83 the small-size city view does not support additional yields, which is why it was not updated.

**Comment by Iamblichos** [comment]
@jantjeuh83,
Let me make sure I understand your request clearly?
1)We need to resize the citizen window to accurately fit in the happiness resource in the normal city view?
2) Small City view needs an additional lookup for happiness?

**Comment by LoneGazebo** [comment]
There's no slot for happiness up there - if you want to adjust the culture hex icon and text a bit, that'd be grand.

**Comment by jantjeuh83** [comment]
@lamblichos: 

1) Look at the upper left of the first screenshot where the different 'resources' are listed. The box that contains the 'Food' information has one extra blank line. The box that contains the rest is too small, causing 'Production' and the 'Culture' bit to overflow.

2) Well the other 'resources' are all listed with icons and values in the small city view, but not 'Happiness'.

**Comment by Iamblichos** [comment]
In regards to #1 how does this fit your fancy:
Big:
![20161109154203_1](https://cloud.githubusercontent.com/assets/14372214/20156445/f6ece346-a695-11e6-969a-cd0ec2768f3f.jpg)

Small:
![20161109160208_1](https://cloud.githubusercontent.com/assets/14372214/20156447/fa8b8ec6-a695-11e6-8f3e-758163f97067.jpg)

**Comment by Iamblichos** [comment]
#2 is actually the productionpopup.xml/lua. I'll cook that one up as well.

**Comment by Iamblichos** [comment]
Here's 2)

![20161109170203_1](https://cloud.githubusercontent.com/assets/14372214/20158164/50627d02-a69e-11e6-8041-6e6bcc2d6a76.jpg)

if you are good with this, we can close out and I'll push.

**Comment by Iamblichos** [comment]
Note tourism is also missing in (2).

**Comment by jantjeuh83** [comment]
Looks a lot better!

**Comment by Iamblichos** [comment]
Should we add tourism to (2)?

**Comment by jantjeuh83** [comment]
Maybe if you can reduce the padding a bit around the existing resources. Otherwise the resource box might become too wide.

**Comment by Iamblichos** [comment]
@jantjeuh83, I think I'd run the risk of cutting to omuch pad where we would bleed into the next box with either two or three digit yields, otherwise maybe it's best to leave tourism out.

**Comment by jantjeuh83** [comment]
Yeah, it's not as critical as the rest.

**Comment by Iamblichos** [comment]
Okay thanks. I'll push out today, and you can expect in @LoneGazebo  's next update.
