### ISSUE TITLE
trade issue ( ended up with CTD)

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2740]
_1. Mod version (i.e Date - 4/23):_

10/28
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
i can trade luxes with poccatelo, which are already traded and trade value is acceptable. I can have 100 deals of same lux resources.

edit: so from seemingly a small issue  is big one. game crashed on pocattelos turn. god be praised for his immortal trade deals. he didnt sell any copy of his ivory, but i bet he had tons of same deals with each civ.

_4. Steps to reproduce (optional):_
 have no idea.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
![logs rar](https://cloud.githubusercontent.com/assets/21192402/19865823/109381f0-9f9e-11e6-8f05-a578da0e85b1.jpg)  minidump + quicksave included.

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20161031165320_1](https://cloud.githubusercontent.com/assets/21192402/19861178/df8663e6-9f8b-11e6-9006-1cf7bf1b5ae3.jpg)
![20161031165324_1](https://cloud.githubusercontent.com/assets/21192402/19861182/e54070e2-9f8b-11e6-8284-95d29c79625b.jpg)

**Comment by LoneGazebo** [comment]
Did you post your save game? I don't see it.

**Comment by matlajs** [comment]
its all in that rar.

**Comment by LoneGazebo** [comment]
There is no rar.

**Comment by matlajs** [comment]
![logs rar](https://cloud.githubusercontent.com/assets/21192402/19895242/4718b9cc-a050-11e6-92c7-30a609220758.jpg)

**Comment by LoneGazebo** [comment]
Thanks! Link in main wasn't working.

**Comment by matlajs** [comment]
lol this is also doesnt work for me.

**Comment by LoneGazebo** [comment]
Works for me if I save as a .rar.

**Comment by LoneGazebo** [comment]
I tried to replicate this and could not.
