### ISSUE TITLE
Naval Tradition not providing promotions

### ISSUE THREAD

**Issue by lucperrin** [LoneGazebo/Community-Patch-DLL#2741]
_1. Mod version (i.e Date - 4/23):_ 10/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ My newly trained naval units are not getting ironsides promotion is indicated in imperalism naval tradition policy.  Maybe I'm too early in the tech tree?

[Haile Selassie_0376 AD-1732.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/562278/Haile.Selassie_0376.AD-1732.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by oalzubbi** [comment]
I'm playing the 10/28 version and I am also getting this error!

**Comment by LoneGazebo** [comment]
Error on release- still unlocks with finisher though.
