### ISSUE TITLE
Honor doesnt provide free military

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2742]
_1. Mod version (i.e Date - 4/23):_
10/28

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
recently completed authority branch and i didnt get free soldier from 11 pop capital.

issue from same game like this #2740

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Can't reproduce. You may not have noticed the unit appear, or you may not have had a free spot near your city for the unit to appear in.

**Comment by matlajs** [comment]
i can reassure you, that in this phase of game i rly dont suffer with surplus of units that i couldnt find a free tile arround my city.

**Comment by LoneGazebo** [comment]
That may be, but I can't reproduce the bug (works fine for me).

**Comment by matlajs** [comment]
tbh it could be just some unlucky loaded game, but im worried try it again and loose another 8 hours.  btw. it works fine for you in my saved game?

**Comment by LoneGazebo** [comment]
Yep.
