### ISSUE TITLE
Shuttle AI movement.

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2746]
It's about the weird way AI units began to move since a couple of patches ago. Quite often AI units are seen moving back and forth until they finally expend all their movement. Quite often the spot where their movement ends looks way too suboptimal and it seems that given a dozen more moves it might have ended up in a more reasonable tile.

Yesterday during AI's turn I thought my game froze. Minute after minute Rome's turn kept going on with no apparent progress. Only later I noticed that the culprit was a land unit who kept embarking from a city and disembarking into the same city right after that. After a hundred or so moves back and forth it seemingly expended all his moves (or was forcefully stopped by some algorithm) and the turn moved on.

Sorry, no savegames or other proofs. Launching a game and watching AI move might suffice.

**Comment by lucperrin** [comment]
I've noticed this behavior with builders on auto-build with no work left to do in mid to late game.  I'll attach a save file when I have one.

**Comment by LoneGazebo** [comment]
@ilteroi, is this an issue with low cost routes/embarkation?

**Comment by ilteroi** [comment]
hmm. never seen that. but indeed there's a failsafe of 100 iterations on move orders per turn.

**Comment by lucperrin** [comment]
In my case it started to happen after I deployed railroads.. builders kept moving back in forth on them many times each turn.  It was so annoying I deleted all the builders that were doing it.

**Comment by saamohod** [comment]
In my case the bug has been the most obvious when I'm at war with another civ and he rearranges the front lines in front of my military units. Too much unreasonable back-and-forth movement

**Comment by Iamblichos** [comment]
Yep. Turn off quick movement and quick combat and you'll see it.

**Comment by HalfEmptyMug** [comment]
I managed to capture [these](http://imgur.com/a/N6qlR) while playing 10-19b (with hotfix from #2689), but I've also noticed this occurring in 10-24. Any unit capable of moving more than twice while at war tends to behave this way, so it's most noticeable with cavalry and naval units. Could it have anything to do with the new tactical AI implemented last patch?

**Comment by LoneGazebo** [comment]
@HalfEmptyMug its very clearly the tactical AI, given their proximity to the enemy. @ilteroi is it possible that a bad check for potential attack targets is being passed in?

**Comment by ilteroi** [comment]
hmm. now we have 3 scenarios:
- embark/disembark
- workers
- attacking

so we're looking at 3 different root causes here. not impossible but noteworthy

**Comment by LoneGazebo** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7849458/19953180/9c2cf9f4-a141-11e6-9c2c-4b6ce358551f.png)

Caught it @ilteroi.

**Comment by LoneGazebo** [comment]
That's the callstack.

**Comment by LoneGazebo** [comment]
Based on observations - the AI is trying, repeatedly, to embark/disembark units into an invalid spot - the action causes the loop, which then breaks at 100 and forces the unit to actually finish its move on its valid destination plot.

**Comment by ilteroi** [comment]
if the move is invalid, there won't be any shuffling ... so this is likely to be a different issue.

re: shuttle during attack - that one is actually funny, AI can earn points for making a good move, so if it has moves to spare, it simply makes the same move again and again :) mostly harmless.

**Comment by saamohod** [comment]
>AI can earn points for making a good move, so if it has moves to spare, it simply makes the same move again and again :) mostly harmless.

 In most cases IMHO AI should be rewarded for staying put and keeping fortification bonuses.

OFF TOPIC: the creepy way the AI identifies reward and acting on getting more of the reward once again rings one word in my head. Skynet.

**Comment by LoneGazebo** [comment]
>if the move is invalid, there won't be any shuffling ... so this is likely to be a different issue.

Perhaps, however I watched the AI do this. I'll get a clip for you.

**Comment by Adonis-VII** [comment]
I hadn't noticed land units as much, but almost every single enemy melee naval unit I was at war with would shuffle back and forth before attacking. I have saves at points where the AI would do it, but I also used Historical Religions, so you'd need that to test.

**Comment by ilteroi** [comment]
the issue is fixed for attacks, but so far i couldn't reproduce it for workers and embarking ...

**Comment by ilteroi** [comment]
ok shuttling workers should also be fixed

**Comment by LoneGazebo** [comment]
Hip hip!
