### ISSUE TITLE
Patronage + marchand of Venice

### ISSUE THREAD

**Issue by Sheepou** [LoneGazebo/Community-Patch-DLL#2748]
_1. Mod version (i.e Date - 4/23):_ 10/28

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
After completing the patronage branch I received a marchand of Venice ( I was playing England ) I was surprised but I didnt know if it was a bug. At this moment I decided to pupet one city state thanks to this marchand of Venice. A few turns later I decided to finally annex the city and I didnt have the possibility to buy a courthouse so I think I had no possibility to remove the 20ish constant unhapiness from the revolt. So I tried to raze the city and apparently I couldnt because it was considered as a capital. 

_4. Steps to reproduce (optional):_

---------------------------

**Comment by LoneGazebo** [comment]
That is a vanilla feature.

**Comment by Iamblichos** [comment]
Why wouldn't he be able to buy a courthouse though? That part makes no sense to me.

**Comment by LoneGazebo** [comment]
No idea. Assumption is mod conflict or he somehow hadn't researched courthouse.
