### ISSUE TITLE
Declaration of Friendship does not automatically expire

### ISSUE THREAD

**Issue by jantjeuh83** [LoneGazebo/Community-Patch-DLL#2749]
_1. Mod version (i.e Date - 4/23):_
28-10

_2. Mod list (if using Vox Populi only, leave blank):_
CP only

_3. Error description:_ 
Had a Declaration of Friendship with Siam which should have expired 3 turns ago, but did not. When I go to the Diplomacy Overview it states '-3 Turns Left' for the DoF. See screenshot below. Save game attached.

![civ5screen0000](https://cloud.githubusercontent.com/assets/23015914/19931553/33cb6690-a10d-11e6-9670-d5173bbaef66.jpg)

[Attila_0272 AD-1260.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/566727/Attila_0272.AD-1260.zip)

**Comment by Radost** [comment]
Display issue on speeds other than Standard. It doesn't take in account game speed multipliers.

**Comment by jantjeuh83** [comment]
Is that a vanilla issue?

**Comment by LoneGazebo** [comment]
vanilla issue, yep. I'll see if I can adjust.
