### ISSUE TITLE
city start screen is broken

### ISSUE THREAD

**Issue by sirhiggins** [LoneGazebo/Community-Patch-DLL#275]
I just started this mod up and followed instructions on the install thread and my city screen is pretty broken, I also cleared my cache as requested
any advice? 
![civ5screen0000](https://cloud.githubusercontent.com/assets/12399368/7571920/c026cfbe-f7e8-11e4-94cd-8320b51bba09.jpg)
![civ5screen0001](https://cloud.githubusercontent.com/assets/12399368/7571924/c40d2204-f7e8-11e4-8165-98feb115d51d.jpg)

**Comment by LoneGazebo** [comment]
You deleted the LUA files in the CP/CBP, yes?

G

**Comment by sirhiggins** [comment]
I deleted them in the CP, am I supposed to do that in the CBP as well?

**Comment by LoneGazebo** [comment]
Are you using EUI? If so, yes, and you also need the EUI compatibility mod (on the install page). If only using CP and CBP and not EUI, no, you do not.

**Comment by sirhiggins** [comment]
Thanks your fix worked
