### ISSUE TITLE
Luxury trading still has issues

### ISSUE THREAD

**Issue by jantjeuh83** [LoneGazebo/Community-Patch-DLL#2750]
_1. Mod version (i.e Date - 4/23):_
28-10

_2. Mod list (if using Vox Populi only, leave blank):_
CP only

_3. Error description:_ 
I've noticed multiple times now that other civs will ask to trade for a luxury (say, Copper), even though I had already set up a trade deal with that civ for that particular luxury. I'll try to figure out exactly when this occurs.

**Comment by jantjeuh83** [comment]
Here's a save game that shows there are still issues. Load it, and go to the Diplomacy Overview -> Trade History. You will see that I have a deal set up with Pacal (the Mayas), offering my Truffles + Marble for 11 GPT. Next, click on any of the Maya cities to open a new trade deal. You will notice that you can still offer Truffles and Marble to Pacal, even though there is already a trade deal for those.

[Attila_0339 AD-1595.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/567330/Attila_0339.AD-1595.zip)

**Comment by jantjeuh83** [comment]
Here some screenshots of such a duplicate deal. This should not be possible.

![civ5screen0001](https://cloud.githubusercontent.com/assets/23015914/19941063/fa91b632-a12e-11e6-8c6b-61132de1ce85.jpg)

![civ5screen0002](https://cloud.githubusercontent.com/assets/23015914/19941068/febd84c0-a12e-11e6-8c5a-b0167d4dd552.jpg)

**Comment by Sheepou** [comment]
I had the same thing in my last game. I noticed it happened because when 1 deal expired and I saw it I decided to renew it myself, then at the ai's turn the ai would try to renew it even though it had accepted my renewal during my turn. Maybe that was the same case for you ?

**Comment by jantjeuh83** [comment]
Yeah, that has happened to me as well. There are definitely multiple issues.
