### ISSUE TITLE
Great Generals and Great Admirals causing CTD

### ISSUE THREAD

**Issue by Zarathustra217** [LoneGazebo/Community-Patch-DLL#2751]
_1. Mod version (i.e Date - 4/23):_
10/28

_2. Mod list (if using Vox Populi only, leave blank):_

(1) Community Patch
(1a) Civ IV Diplomatic Features - CP (v 1)
(BNW) Leugi's Barbarian Inmersion Enhancements (v 1)
Custom Advanced Setup Screen (v 5)
Enlightenment Era (v 6)
Ethnic Units (v 31)
Example - Simple Clock (v 8)
Faster Aircraft Animations (v 3)
Gibraltar, Reef, and Krakatoa Fixes (v 101)
Ingame Editor (v 39)
Lake Victoria Fix (v 2)
Mercenary Army Expanded (v 1)
Missile Cruiser-- Indirect Fire (v 1)
More Luxuries (v 155)
More Moves for Units (designed for large Maps) (v 1)
PerfectWorld3 - Updated (v 5)
Quick Turns (v 10)
Religion - No AI Free Pottery (v 1)
Resource - Granary Includes Bison (v 3)
Ressource - Mint Include Copper (v 2)
Scouts ignore Borders (v 2)
Super Starter Settler (v 1)
Unit Iron and Oil Requirements (v 2)
Unit Path Viewer (v 10)
War - Less Damaged Captured Cities (v 3)
Workable Mountains (v 2)

I know this is a -very- long list, but most are simple and I've made sure there's no conflicts. 

At first, I suspected Leugi's Barbarian Inmersion Enhancements (yes, that's how it's spelled) but I've tested it extensively, adding more logging, and it doesn't seem related to this mod. 

_3. Error description:_ 

Two times I've experienced issues that I assume (but cannot tell for certain) are related. First is a game where simply selecting Great Generals would cause crashes to desktop, albeit only for one of the players in a hotseat game.

The second case is a similar CTD, also in a hotseat game, but this time happening during AI moving (in this case, the Huns). Using the Ingame Editor mod, I was able to remove a Great Admiral from the hunnic player, and this prevented the crash during the turn.

I couldn't find anything remarkable in the logs, but I've attached them anyway along with the save.

_4. Steps to reproduce (optional):_

Load the save, end turn and let the AI move until the CTD at the Huns.
[Debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/567185/Debug.zip)

I regret not being able to test it more systematically, but given its erratic nature, it's been hard to reproduce

**Comment by Zarathustra217** [comment]
If it's any help, I can see that the great admiral was there several turns before when it started causing the crash. The admiral's name is Andrea Dorea

I also vaguely recall that shortly before the great generals started causing crashes in the earlier game, they would show up as having carriage capacity 2, but it was something I saw in passing so I could be wrong there.

**Comment by LoneGazebo** [comment]
Are you getting any database or lua errors?

**Comment by Iamblichos** [comment]
He's got quite a few database errors and lots of errors in lua.log.

**Comment by Zarathustra217** [comment]
Yeah, as far as I can tell, most are text references and none seem directly related to this. You'll be able to tell much better than me though!

**Comment by Iamblichos** [comment]
Well man ought to be something to be surpassed, Spoke Zarathustra, but the Superman we are not.

Too many mods to debug. I'd like to help you with it, but I've never encountered this problem, and it's just too much effort to go and find all those mods to load up for this one.

**Comment by LoneGazebo** [comment]
Database errors, even if not listed as "GREAT_GENERAL_WILL_CTD_IF_CLICKED," are indicative of mod incompatibilities that could be breaking core aspects of other mods.

**Comment by Zarathustra217** [comment]
Alright, thanks, I'll try to run with less mods next time and see if that solves things.

Some of the errors I imagine pertain to me having disabled the polynesia DLC (because their ability to embark and cross ocean tiles really spoils a lot of the early game) - does this break the Community Patch?

**Comment by LoneGazebo** [comment]
Yes.

**Comment by Enrico-Swagolo** [comment]
Just use Really Advanced Setup to disable civs you don't want to see

I might disable Brazil myself because they've been appearing nearly EVERY SINGLE GAME for like 10+!

**Comment by Zarathustra217** [comment]
The issue with this is that I use the "Custom Advanced Setup Screen" mod because I play hotseat.
