### ISSUE TITLE
Landmarks only gives 1 culture + Can't dig sites

### ISSUE THREAD

**Issue by Sheepou** [LoneGazebo/Community-Patch-DLL#2752]
_1. Mod version (i.e Date - 4/23):_10/28

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
* Two of my landmarks were not improving my tiles ( both of them were on desert tiles )
![bat](https://cloud.githubusercontent.com/assets/23124937/19940255/5644cfe4-a12c-11e6-979c-455d97e65e26.png)

** I could'nt dig one site ( I don't know if it is relevant but it is on my vassal's territory ) 
![archeo](https://cloud.githubusercontent.com/assets/23124937/19940392/d029bbb2-a12c-11e6-9685-3b7a288e7427.png)

Sorry I'm stilll pretty new so I don't know if these are intended, vanilla bugs or VP bugs

**Comment by Iamblichos** [comment]
VP only? No other mods?

**Comment by Sheepou** [comment]
yes, VP only

**Comment by matlajs** [comment]
you can't dig  sites in foreign lands unless you both have borders opened to each other.

**Comment by LoneGazebo** [comment]
landmark culture is based on age of GW on spot.
