### ISSUE TITLE
AI is too daring with hurt troops, and sometimes moves Workers weirdly

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2753]
_1. Mod version (i.e Date - 4/23):_

Cur rent. 28th October

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Basically title. It'll often moe a hurt warrior/spear in front on my lvl 9 archer with a lvl 5 archer buddy and a lvl 8 horse nearby. Sure, this guy would have died regardless of HP and the situation was quite dire (I used one of my many GGs as Rome to create a foothold near his capital), but I've seen other cases of AI not just leaving its troops to heal instead of having them get simply wasted by my superior army. It'd be better if in such cases, the AI tried moving more than 1 unit at a time.

About Workers, AI will sometimes just move them through my lands. What happens is obvious - even an escort wouldn't really help. They might also start moving them through their lands (apparently to reach some spot in other side of their borders), but the way contains my troops... And so I capture a Worker with ease.

I've seen some reckless GG behaviour too, basically letting me freely take them either by putting them on a bad unit or just weirdly moving them around. It's way better than it used to be in this regard though, but still not too bright.

The behaviours (excl. worker-through-my-lands) mostly appear when the AI is losing a war, so it's not a really big deal (it just potentially speeds up their demise)

**Comment by ashendashin** [comment]
You forgot to mention that regular ranged units are practically doomed to the front as soon as they're made, besieged city or no. Works well enough when they have enough melee units to stick up front, but dying civs are just speeding it along, as you said.
Pretty accurate for what a human player would do though.

**Comment by LoneGazebo** [comment]
@ilteroi , thoughts?

**Comment by Enrico-Swagolo** [comment]
Also sometimes ranged units seem not to shoot? Like, a slightly hurt GreK Dromon just swam around my Dromon and didn't shoot for a few turns, only to scram as I saw the situation and shot him some time later.

**Comment by ashendashin** [comment]
@Enrico-Swagolo you're probably looking for #2746 on that one

**Comment by ilteroi** [comment]
most of the time this is due to poor visibility - AI simply is bad at "estimating" that there are enemies in the fog of war.
