### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by DimmyCiv5** [LoneGazebo/Community-Patch-DLL#2754]
10/28 VP 1-2-3-4-5-6a
JFD's Cultural Diversity Core v.11
Wonder race v.6

Game crash on 3rd player (VENICE) turn after mine. I tried playing several turns before the crash and changing my behaviour, played with options, crash still occurs. Thanks for your time. 

End the turn on the worker waiting for orders. Next turn begins. Crash occurs after 45 sec.

PS: I also have the warscore=100 no peace possible with VENICE as in the issue thread here about warscore.

PPS: Why the frig I can't upload my zipfile made with 7zip or winzip ? Oo
Here a direct link to my zip archive (DimmyCiv5CrashVeniceTurn.zip : 2.62 Mo)
https://1fichier.com/?y5r9321xbk

In the zip file :
database.log
lua.log
xml.log
Savegame file
CvMiniDump.dmp file

**Comment by Charlitron1** [comment]
I'm having a similar problem. I end my turn, Aztecs go, Etheopia goes, then during Zullu's turn, game crashes right to desktop.

I'm running VP 10/24 (no EUI).

Game ran fine, no issues until I ended turn 392. I tried disabling autosaves, turned on quick movement/combat, no luck... Was having a really fun game too :(

**Comment by LoneGazebo** [comment]
Your minidump crashes to lua, which means it is an issue with cultural diversity unfortunately.

**Comment by DimmyCiv5** [comment]
Sure, now maybe this mod should be removed from the mods compatibility list with CPD... :/ ;)

**Comment by DimmyCiv5** [comment]
Thanks again for your time, regards.

**Comment by LoneGazebo** [comment]
Well, crashes can happen. Mods can be compatible but still crash. I just can't debug this.
