### ISSUE TITLE
Vassal diplomacy

### ISSUE THREAD

**Issue by Sheepou** [LoneGazebo/Community-Patch-DLL#2755]
_1. Mod version (i.e Date - 4/23):_28/10

_2. Mod list (if using Vox Populi only, leave blank):_VP only

* Not sure if I can say bug, more like very irrational behaviour by my vassals. Dido my vassal keep proposing resolutions against my interest ( like removing the fact a city state is my ally ) but since she is my vassal she keeps voting nay for this resolution she asked for.

** Very very minor bug I feel like everything is put in place to hide the other civs until you meet them but at the start of my game I had a message like " an unmet civ has lost his capital. Catherine is now leading having 2 capitals" and I didnt meet her at this time.

*** Very very minor visual bug anti-aircraft gun promotions are sometimes the auto or the build road icons
![visu](https://cloud.githubusercontent.com/assets/23124937/19954721/f404a99a-a17a-11e6-8204-a081efc3d996.png)

**Comment by supermerill** [comment]
YourtThird issue is #2555 i think

**Comment by LoneGazebo** [comment]
Vassal proposals are weighted, but the AI can sometimes make odd choices. Thankfully the voting corrects this. Not easy to fix without hardcoding (which I loathe). 

Notification issue is a vanilla bug I've never been able to solve.

AA is fixed.
