### ISSUE TITLE
Game Freezing

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#2756]
_1. Mod version (i.e Date - 4/23):_
10/28

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP w/ EUI, Thals Flags, IGE (In game Editor), Info Addict

_3. Error description:_ 
Game freezing 

_4. Steps to reproduce (optional):_
After doing a few different actions (changing build queue, moving a unit, etc) the game freezes. I've tried reloading and doing things in a different order but it does not seem to do anything.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
[Supporting Files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/569805/Supporting.Files.zip)

**Comment by supermerill** [comment]
Did you tried without IGE (In game Editor) & Info Addict ?

**Comment by oalzubbi** [comment]
According to the list, those mods are "Out-of-the-box" Compatible with VP. And anyway, the game worked fine with them for about 250 turns and then started getting weird.

**Comment by LoneGazebo** [comment]
Probably related to unit shuttling issue. Fixed in upcoming version.
