### ISSUE TITLE
CTD on 10/28

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#2757]
_1. Mod version (i.e Date - 4/23):_
10/28

_2. Mod list (if using Vox Populi only, leave blank):_
![1capture](https://cloud.githubusercontent.com/assets/19291347/19995014/c32866e0-a229-11e6-8bc1-31e372fc8ebe.JPG)

_3. Error description:_ 
Game crashes on turn 178.

---------------------------

Can't upload zip files for some reason -- only .gz works ?_?

1. [Logs.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/570647/Logs.gz)

2. [12crash.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/570652/12crash.gz)

3.[CvMiniDump.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/570659/CvMiniDump.gz)

**Comment by LoneGazebo** [comment]
RED modpack uses a DLL.

**Comment by jimmymcperson** [comment]
Oh, okay.  Sorry!
