### ISSUE TITLE
Spirit of the desert and Iron

### ISSUE THREAD

**Issue by qpegasus** [LoneGazebo/Community-Patch-DLL#2758]
_1. Mod version (i.e Date - 4/23):_ 

10/28

_2. Mod list (if using Vox Populi only, leave blank):_

Only VP and Tectonic map script

_3. Error description:_ 

Playing as Russia and with the spirit of the desert pantheon, I noticed that my improved desert Iron resource was not giving the faith/food/gold bonus. Possibly a conflict with Russia's UA which gives +1 science to strategic resources (which I do receive).

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
Not flood plains, correct?

**Comment by qpegasus** [comment]
Correct, just desert. Save uploaded for you.

[Catherine_0098 BC-0425.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/571632/Catherine_0098.BC-0425.zip)

**Comment by LoneGazebo** [comment]
There's no conflict (as the bonuses are computed in two separate areas). In any case I tested and cannot reproduce. Mod conflict or simply a UI issue?
