### ISSUE TITLE
AI building selection

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2760]
i recently play a lot of advanced start games ... check this city. 

this is after 200 turns of autoplay. all the stuff in the build queue was added by me, AI was building a temple. no forge. no walls. no monument. no lighthouse.

![image](https://cloud.githubusercontent.com/assets/1358966/20030252/93b31502-a361-11e6-9af4-944a16fc3c9d.png)

this doesn't seem to be good play.

**Comment by LoneGazebo** [comment]
I've been making adjustments to that as well. The problem is also related to war - the AI was avoiding buildings like the plague during wars.

**Comment by ilteroi** [comment]
ah ok.

interestingly, they have also invested in a lot of building which they never built in the end.

and then this - i can't buy hussars, because no ducal stable. but that building isn't available.

![image](https://cloud.githubusercontent.com/assets/1358966/20030964/3cd93b26-a370-11e6-9c5f-b7b87478746b.png)

**Comment by LoneGazebo** [comment]
Isn't available? That's weird.

**Comment by ilteroi** [comment]
doesn't say so in the pedia. and the problem also occurs in a city that's literally founded on top of horses.

**Comment by ilteroi** [comment]
and another small glitch, AI just built an archeologist in a besieged city
