### ISSUE TITLE
moai's cs bonus

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2762]
_1. Mod version (i.e Date - 4/23):_
10/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
moai doesnt provide +20% CS, or atleast not vs barbarians.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
I don't believe they provide CS anymore since their UA got changed.

**Comment by matlajs** [comment]
im playing them first time. so it may be just bad description issue.

**Comment by LoneGazebo** [comment]
They still provide the CS (its in the Moai desc instead of UA desc). I can't replicate this issue.

**Comment by matlajs** [comment]
then Vp have to be absolutely broken combined with RED modpack, bcoz you cannot reproduce anything and those are not hard to reproduce. this or i have no other idea what could cause all my problems.

**Comment by LoneGazebo** [comment]
I think RED affects the unitcombat lua, so yeah, that could account for this issue.
