### ISSUE TITLE
Peace deal negotiation screen has visual issues

### ISSUE THREAD

**Issue by jantjeuh83** [LoneGazebo/Community-Patch-DLL#2765]
_1. Mod version (i.e Date - 4/23):_
28-10

_2. Mod list (if using Vox Populi only, leave blank):_
CP only

_3. Error description:_ 
See attached screenshot. Somehow all the various entries in the trade deal got shuffled to the right column. Also note the leader text going out of bounds.

![civ5screen0003](https://cloud.githubusercontent.com/assets/23015914/20032763/d7405e4e-a391-11e6-81ef-ac07f8213baa.jpg)

**Comment by LoneGazebo** [comment]
You've got a mod conflict breaking your deal screen.

**Comment by jantjeuh83** [comment]
I'm only using the CP patch?

**Comment by HalfEmptyMug** [comment]
Did you liberate a city state before making this peace deal?

**Comment by jantjeuh83** [comment]
Yeah. It might be related to #2767.
