### ISSUE TITLE
Scholars in Residence WC proposal

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#2766]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_
full VP+EUI, Info Addict, Thals Flag promotions, IGE, 

_3. Error description:_ 

Scholar's in residence text says it lowers Science costs by 20% + 5% per CS ally.

I have 6 CS allies, thus should have 50% reduction. However, the turn requirement for techs I was looking at went from 12 to 8, not 6 like it should be.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
It's worded weird just how workers can improve improvements +200% faster despite being mathematically impossible. Worker have an improve speed of 100 and +200% mean they have an improve speed of 300 which mean they can construct a farm which requires 750 improvement in 3 turns compared to 8 turns and such. My guess is that Scholar in Residence increases your science rate likewise. (Researching a technology requires 120 science, but you only have +10 science/turn meaning you have researched it in 12 turns while with Scholar with Residence will grant you +15 science/turn meaning you will have researched it in 8 turns)

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer is correct.

**Comment by oalzubbi** [comment]
Okay, the wording should be changed from -20% science costs to +20% science towards those techs.
