### ISSUE TITLE
Siege Unit Movement Penalty in Allied CS Territory

### ISSUE THREAD

**Issue by muarB** [LoneGazebo/Community-Patch-DLL#2768]
_1. Mod version (i.e Date - 4/23):_
10/28

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I was at war at the time and when moving trebuchet through an allied CS territory they were getting a movement penalty.  Maybe this is intended but it didn't make sense.

_4. Steps to reproduce (optional):_
I couldn't get my latest save or auto-save to open for that game, maybe its the amount of units overloading my old PC's memory.  So wasn't able to double check and test it more.  I'll try it another game.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Yep - outside owned lands you get a penalty.

**Comment by TechpriestEnginseer** [comment]
But it's allied, shouldn't it be technically owned?

**Comment by LoneGazebo** [comment]
@ilteroi how's this handled in the code?

**Comment by muarB** [comment]
Oh I see.  I thought maybe it was bugged and incorrectly giving a penalty thinking all CS territory was enemy territory.  But yeah that is consistent with the description of all un-owned territory.  I was thinking the penalty only applied to enemy territory.

**Comment by LoneGazebo** [comment]
Currently designed to only apply to owned territory. CSs don't count as owned, yep.

**Comment by muarB** [comment]
Maybe my installation is bugged but I'm able to move catapults 2 tiles in un-owned plains (11-6 version) between my civ and my enemy territory.  The movement penalty only kicks in when it enters enemy territory.  That's why the allied CS territory movement penalty seemed weird.  Not a big deal, just pointing it out.
