### ISSUE TITLE
Enemy ship won't move even though it's under bombardment

### ISSUE THREAD

**Issue by jantjeuh83** [LoneGazebo/Community-Patch-DLL#2769]
_1. Mod version (i.e Date - 4/23):_
28-10

_2. Mod list (if using Vox Populi only, leave blank):_
CP only

_3. Error description:_ 
See screenshot. Enemy Polynesian caravel is under attack by my two cannon, but stays routed on the spot, therefore is very easily destroyed. Would have expected it to move away. Save game also attached.

![civ5screen0006](https://cloud.githubusercontent.com/assets/23015914/20041602/5b5da72e-a46c-11e6-9411-57d24ac2e759.jpg)

[Wu Zetian_0383 AD-1746.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/574110/Wu.Zetian_0383.AD-1746.zip)

_4. Steps to reproduce:_

Load the save game, attack the caravel with the cannon, note that it won't move away in the next turn.

**Comment by ilteroi** [comment]
i was able to load this save for a change ... and the caravel moves away when i end the turn. so it seems it's already fixed.

**Comment by ilteroi** [comment]
also, @LoneGazebo : the AI sure loves their caravels ... the whole map is full of them

![image](https://cloud.githubusercontent.com/assets/1358966/20041969/0a39c49e-a472-11e6-83d1-791a380c4ca9.png)

**Comment by jantjeuh83** [comment]
@ilteroi: yeah, he has a vastly superior fleet of caravels, but doesn't do much with them. In fact, it runs away all the time, avoiding confrontation. See #2770 for that.
