### ISSUE TITLE
Enemy AI is too cowardly

### ISSUE THREAD

**Issue by jantjeuh83** [LoneGazebo/Community-Patch-DLL#2770]
_1. Mod version (i.e Date - 4/23):_
28-10

_2. Mod list (if using Vox Populi only, leave blank):_
CP only

_3. Error description:_ 
See screenshot. Note that I have two frigates and am facing a superior face of 6 caravels (used to be like 9 of them, but I've killed a few with my two frigates). Rather than overwhelming my small force, however, the enemy chooses to run away each time, even choosing to abandon their cargo ships to pillaging. Not sure if the AI is supposed to be this cowardly ;-)

![civ5screen0007](https://cloud.githubusercontent.com/assets/23015914/20041960/dd97aa82-a471-11e6-94fb-10957aa2ffec.jpg)

_4. Steps to reproduce (optional):_
Load the attached save game. Hit 'Next Turn'. Note how all the caravels run away bravely, abandoning the poor cargo ship (and more importantly, their capital!) to the mercy of my frigates.

[Wu Zetian_0392 AD-1764.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/574140/Wu.Zetian_0392.AD-1764.zip)

**Comment by ricanuck** [comment]
Haha! You made me laugh... your description sounds awfully like Civ6's AI... G, what did you do???

j/k, but it truly sounds like that... haven't been trying VP since Six's release (don't shoot me).

**Comment by ilteroi** [comment]
ok, turns out the caravels were treated as explorers and so ignored for any attack. this probably also explains the caravel swarms ... they were the survivors, all other units were killed fighting.

additionally, numerical superiority was not considered for setting aggressiveness. fixed now, so watch out for the killer swarms!

**Comment by ricanuck** [comment]
G, hotfix for this one?

**Comment by LoneGazebo** [comment]
Yeah.

**Comment by LoneGazebo** [comment]
Well I'm not sure if it'll be savegame compatible as @ilteroi added a variable to the kstream. Want to test? :)

**Comment by LoneGazebo** [comment]
In any case none of his changes are mission-critical, so I'll probably just push as a beta.

**Comment by LoneGazebo** [comment]
test https://mega.nz/#!aRkTWIQR!yPWNkklMEQjZwbVqmDM1NPrda-JaVK2SMT8A2Xi8hjY

**Comment by ricanuck** [comment]
he... was about to start a new VP game after you tempted me yesterday to leave Six alone and come back, so I checked before starting and found this one lurking... so no savegame to test, pretty sure it will be not save-compat... good that I waited a little, this one really sounded like an AI-weakener...

**Comment by Iamblichos** [comment]
Works for me.

**Comment by LoneGazebo** [comment]
@Iamblichos it is savegame compatible?

**Comment by ilteroi** [comment]
i didn't do anything to the savegame format. just fixed the loading of the tactical map.

**Comment by Iamblichos** [comment]
Yes no issues loading and saving with ilteroi's changes.

**Comment by Rottw** [comment]
"File missing" can't download :(
