### ISSUE TITLE
Wrong tooltip aid for worker

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#2771]
_1. Mod version (i.e Date - 4/23):_

VP 11/6
_2. Mod list (if using Vox Populi only, leave blank):_
Infoaddict, Tectonics, Clock.

_3. Error description:_ 
I have built a camp over some elephant. The resource is acknowledged and the building is showing in the map, but the worker assistant keeps saying that I should build a camp in the ivory resource. 

_4. Steps to reproduce (optional):_
Playing Greece, King, found issue in turn 44, moving to next turn doesn't solve it.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by tu-79** [comment]
After making a farm, the tooltip is suggesting now correctly camps on deers. Turn 52.

**Comment by LoneGazebo** [comment]
Not sure. Sometimes the advisor acts up. Nothing I can do about is as I can't control that.
