### ISSUE TITLE
Not relevant info in tech tree

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#2772]
_1. Mod version (i.e Date - 4/23):_

11/6
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

This is recurring for lattest versions (this time just there is fewer errors), see if it can be fixed. Right now, I'm informed of the following non-relevant info:
Calendar - Reveals Brazilwood (I'm Greece)
Economics - Colonia +2c
Fertilizer - Colonia +2f, Terrace Farm +1f

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Can't control for that as data is set at game load not map load.

**Comment by Edaka** [comment]
Setting SpecificCivRequired to 1 and CivilizationType to CIVILIZATION_VENICE for Colonia makes it disappear from the tech tree, unless you're playing as Venice. It makes it appear as a fourth unique component for Venice in the setup screen, though.

**Comment by LoneGazebo** [comment]
@Edaka right, which is why I avoid that. Generally I feel that all information on tech changes should be in the tree whether or not they directly affect you.

**Comment by Edaka** [comment]
True, but it can also clutter the more easily readable tech buttons. The entire information for each is displayed in the more detailed hover tooltip regardless of being or not being previewed on the tech buttons, in the event you may want or need it. 

Anyway, don't mind me - just weighing the pros and cons here (: .

**Comment by tu-79** [comment]
I don't get it. If I am playing Greece I don't need to see when Polynesia gets an extra culture on moais and I don't need to see when Terrace Farms get extra food. At least in my tech tree. It's me who is picking a tech to discover, I am not choosing for Venice. In my dictionary that's clutter.
I don't mind to see all the benefits for every civ in the new tech pop up window, though. And if I need to see what the uniques of the other civs that are playing the game are, there could be better places, like Civipedia or Diplo-screen.

**Comment by LoneGazebo** [comment]
@tu-79, to repeat:

>Can't control for that as data is set at game load not map load.

@Edaka's suggestion would only work if I broke the leaderscreen '2 Uniques' element. and that's not going to happen.

**Comment by tu-79** [comment]
Too bad. I guess that's the best you are allowed to do.

**Comment by Edaka** [comment]
Actually, while what Gazebo says is true for Venetian Colonia, there's a way out for other unique improvements, since they technically already have SpecificCivRequired and CivilizatonType defined. For my mod-mod I've deleted and then redone the whole Improvements_TechYieldChanges for all UIs. Don't know how, but that removed all irrelevant UI tech buffs from my tech tree. I'm guessing that's because some of them might be from vanilla and that's why they always show up?
