### ISSUE TITLE
Game crashes when loading save (after a few seconds of loading)

### ISSUE THREAD

**Issue by Badui** [LoneGazebo/Community-Patch-DLL#2774]
_1. Mod version (i.e Date - 4/23):_
10/24

_2. Mod list (if using Vox Populi only, leave blank):_
Vox+EUI and Ingame Editor

_3. Error description:_ 
Game crashes after a few seconds of loading and it really bums me out :(

I took a peek in the logs, but it looks relatively normal to me with some errors that (I think?) have always been in the base game.

_4. Steps to reproduce (optional):_
You should be able to reproduce it by just trying to load the game (assuming it isn't just me)

---------------------------
Supporting information:

[Civ crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/574553/Civ.crash.zip)

**Comment by LoneGazebo** [comment]
Game loads fine. Check your install folder make sure there aren't any mod conflicts. Also check for your civ install's integrity.

**Comment by Badui** [comment]
Integrity checks out, and I don't see any mod conflicts (again its just all this + IGE anyway). As far as I can tell everything is reporting to be fine...except it crashes to desktop with no way for me to find out what it is as there are no errors other than, I guess, that minidump which I really have no idea how to read properly.

But, if you can load it fine I guess it's gotta be something on my end...sigh. I deleted the items in the cache folder and the items in the ModUserData folder too just to be sure, but reloading the mods and trying still produces the same outcome.

:/ Fantastic. I appreciate the help though!

**Comment by LoneGazebo** [comment]
On a mac? 

Try it without IGE.

**Comment by Badui** [comment]
Nope, W10 PC.

Apparently I fixed it though by trying it in DX11 mode. I didn't know you were required to play it in DX11 when your card is capable of DX9 but, hey, I'm not gonna complain. Maybe that's a Windows 10 thing, or maybe DX9 is just so dinosaur to it by now.

I appreciate the help, and I'm sorry for opening an issue that isn't caused by you. Thanks again!

P.S. I would close it, but I'm not sure how, or if I could xD

**Comment by LoneGazebo** [comment]
Ah yeah dx9 is fickle.
