### ISSUE TITLE
Barbarians are pretty much just roadblocks

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2775]
_1. Mod version (i.e Date - 4/23):_

Current, but was there for a few versions

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Encounter a Barbie.

He won't ever attack your Warrior, he'll just walk around slowing you down. I get it, attacking would give him less HP, but it's really not fun. Even if your Warrior is surrounded by 3 Barbies who could kill him with ease, they won't attack him just because he's on a hill and the damage-damage exchange would be theoretically bad, despite the fact he would've died because he's surrounded and wouldn't be able to escape.

Barbies also just prefer walking around avoiding any fighting. The cowardice might sort-of make sense, but it's just a pain to fight against. They love just fortifying and then walking around pointlessly, just slowing your movement down.

As it is, Barbies only attack Scouts unless ranged or they're better units than warriors (who attack warriors but refuse to hit their civ equivalents), in which case the barbies are more like their old selves, loving to attack and not escaping even when possible. They're actually less threatening than a few versions ago if you think about it.

**Comment by LoneGazebo** [comment]
@ilteroi thoughts?

**Comment by ilteroi** [comment]
barbarians should be attacking with high aggressiveness (possible levels are low, mid, high) so that means they shouldn't care about the damage they take. need to check ...

**Comment by Enrico-Swagolo** [comment]
Yeah it used to be so, but one version it turned around to the point that now I seriously think AI is more aggressive with its troops than barbies are. Barbies are very reckless at making the pillage city events though, but attacking? Nope. If an unit is on a hill and of the same type, they won't bother (unless ranged, in which case they'll gladly shoot each other until the barbie dies, perhaps running away at 1 hp)

If there's a quickfix made (like to a file or something), I'd love to get my hands on it if such a thing would be possible. It's pretty unfun to deal with barbies as they are now.

**Comment by ilteroi** [comment]
can't reproduce - maybe fixed along with #2770

**Comment by Enrico-Swagolo** [comment]
Weird. Play the current version from civfanatics, you're sure to encounter it. Just put a warrior on a hill in front of a brute, brute won't do anything or will fortify.

**Comment by ilteroi** [comment]
the fix is not in the 11/6 version, you need the dll from #2770 to test
