### ISSUE TITLE
AI leaving ship inside a city that's going to fall

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2776]
_1. Mod version (i.e Date - 4/23):_

Current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

So I was playing as Nappy, and saw that the most dastardly dastard Pedro has built a city near me.

I've attacked it with a catapult. He's rushbought (or just transported in?) a dromon and landed it inside the city. I think cool as I shoot it, it'll go away soon because next turn I will be able to take the city with ease. 
But nope. Pedro has left the Dromon inside the city not moving it out for no reason, meaning my Horsie took not only the city, but also the Dromon inside it. It's not like he had no other cities - he has 7 - and it's not his last one. He has just lost a ship for no reason.

**Comment by ilteroi** [comment]
should be fixed now
