### ISSUE TITLE
Loss of tradition buildings after losing capital? 

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#2777]
_1. Mod version (i.e Date - 4/23):_
11/6

_2. Mod list (if using Vox Populi only, leave blank):_
Ingame Editor (v. 39)
FlagPromotions (v. 7)
Quick Turns (v. 10)

_3. Error description:_ 
Not necessarily an error, but after losing and retaking my capital I noticed that all buildings gained from the tradition tree were destroyed. I imagine most people don't wind up losing their capital, and if they do they just reload, but I'm more concerned with the AI since losing these buildings can be devastating early in the game. Would there be any way to make these buildings reappear in the capital upon it's liberation? 

----------------------
Edit:
[Error Logs and Save - Tradition Buildings.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/579747/Error.Logs.and.Save.-.Tradition.Buildings.zip)

If you load the save and hit next turn the capital will fall; the logs are for that turn. After the capital is taken only the palace is moved, nothing else, and the buildings remain lost even after several turns. Retaking the capital (either with units or IGE) doesn't cause them to return, and completing the tradition tree only causes the final two buildings to appear. Also, if a tradition building is built outside of the original capital, it remains in the city it was built in even if the original capital is liberated.

**Comment by TechpriestEnginseer** [comment]
Don't those buildings transfer over to the new capital hence upon liberation, they're not retransferred because they're in the new capital?

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer is correct, though I have not tested.
