### ISSUE TITLE
Emulating Event System

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2779]
I want to make a Lua system that pops an alternative stream of random events, although I have a few questions.

What determines how random events are popped at turn intervals? 30 turns for one event modified by gamespeed and by how much?

They say Modding.OpenSaveData() is a hindrance on performance by how much? I only want to open this data everytime a resolution gets passed/fails. Would this be too much of a burden for the performance?

If it's too much of a performance would it be possible to make a last Lua check to determine whether or not a resolution has passed or not passed?

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer not sure I understand - what you are trying to do is supported by the events system I built.

**Comment by TechpriestEnginseer** [comment]
~~Let's say Ban Luxury: Crabs is passed. A GameEvent will check for the passing of the proposal and I'll do a Modding.OpenSaveData() to save a value so that it can go through save games properly without issues and later if the ban luxury gets repealed.~~

~~For the sake of helping performance, the passing of the proposal will also make a variable equal true which will allow my suggestion...~~

~~An emulated event system. Working alternatively away from the..~~

Oh right I could have just used IgnoreGlobalCooldown from the current event system, although to make the event fire.. it would still require the proposed resolution to be passed..

**Comment by LoneGazebo** [comment]
Yeah, use ignore global cooldown and it should work just fine. 

Anyways something to test. Two new lua functions:

Game.DoEnactResolution(ResolutionTypes iResolutionType, int iChoice, PlayerTypes eProposer);

for iChoice: (-1 = no choice, 0 = no, yes = 1)
and

Game.DoRepealResolution(ResolutionTypes iResolutionType, PlayerTypes eProposer);

You can set Proposer to NO_PLAYER for both.

iResolutionType for repeal MUST be for an active proposal - you can use Game.IsResolutionPassed(iResolutionType, iChoice) to check for this.

Test version for you:

https://mega.nz/#!3Q1QRI5Z!8Nd6u125OZHSl9T0dV4ij3djyPeiR1oiYjXtmtWp0ag

**Comment by TechpriestEnginseer** [comment]
Well, I was looking for something like is Game.IsResolutionPassed(iResolutionTypes, iResourceType, iMinor, iMajor). As iResourceType helps determine which luxury got banned, iMinor determine which city-states are open-bordered, sphere of influenced, and iMajor helps determine which major civilizaitons are embargoed.

**Comment by LoneGazebo** [comment]
iChoice is what you are looking for - ichoice is an INT, and resources/minors/majors are ints too. So input the ID of the resource/player you want in that slot and it'll tell you if there's a resolution targeting them that's active.

**Comment by TechpriestEnginseer** [comment]
Glad to say it's working well. If only it worked pre-World Congress... but I can probably do some checks to make sure.

**Comment by LoneGazebo** [comment]
Cool. Can't work pre league unfortunately.

**Comment by TechpriestEnginseer** [comment]
Does the AI liberate its city-state faster than the Lua code itself?


````
bad argument #2 to 'DoEnactResolution' (number expected, got string)
````
````
citystateliberate = nil

function YouDecide(iPlayer, iChoice)
	local pPlayer = Players[iPlayer]
	if iChoice == GameInfoTypes.PLAYER_EVENT_CSVASSAL_CHOICE_1 then
		Game.DoEnactResolution(GameInfoTypes.RESOLUTION_SPHERE_OF_INFLUENCE, citystateliberate, Players[iPlayer])
	elseif iChoice == GameInfoTypes.PLAYER_EVENT_CSVASSAL_CHOICE_2 then
		Game.DoEnactResolution(GameInfoTypes.RESOLUTION_OPEN_DOOR, citystateliberate, Players[iPlayer])
	end
end

function VassalCityState(iPlayer, iOtherPlayer, iCity)
	citystateliberate = "none"
	local pPlayer = Players[iPlayer]
	local pOtherPlayer = Players[iOtherPlayer]
	if pOtherPlayer:IsMinorCiv() then
		pPlayer:DoStartEvent(GameInfoTypes.PLAYER_EVENT_CSVASSAL)
		citystateliberate = iOtherPlayer
	end
end

GameEvents.EventChoiceActivated.Add(YouDecide)
GameEvents.PlayerLiberated.Add(VassalCityState)
````

Perhaps I should reorder the Lua coding...

**Comment by TechpriestEnginseer** [comment]
Just one more suggestion is it possible to add Game.ResolutionThoughtsOn((ResolutionTypes iResolutionType, int iChoice, PlayerTypes eProposer, ThoughtFrom eOpinion) because I'd like to make the AI think about their decisions when they're choosing it in the event system.
Ex.
Game.ResolutionThoughtsOn(GameInfoTypes.RESOLUTION_SPHERE_OF_INFLUENCE, 42, 0, 3)
might be read as what is Korea (3) thoughts on an American(0) Sphere of Influence on Byblos(42) and it might return 0-5 value like
````
0 Neutral
1 Weak Nay
2 Strong Nay
3 Weak Yeah
4 Strong Yeah
````

**Comment by TechpriestEnginseer** [comment]
Game.DoRepealResolution(ResolutionTypes iResolutionType, PlayerTypes eProposer);

How would I repeal a Sphere of Influence with no iChoice in this function?
