### ISSUE TITLE
Deleting Stuff

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#278]
Hi Gazebo,

in seeking to resolve a CTD caused when using my Cultural Diversity mod with the CBP (and inspired by a crash reported on my Cultural Diversity thread), I discovered an underlying issue that I have confirmed to be the cause (of at least some) of the crashes resulting from using Events & Decisions (as well as probably other mods). Basically, when you delete items from the database (e.g. unit promotions) and then add new promotions, this leaves large gaps in the ID sequence in the database: so where Drill I's ID in vanilla is 0, it's ID is 234 in CBP (or close to). For whatever reason, when the database is queried by another mod, it will look for the original ID, and, if that's not there, it can result in a crash.

To resolve this, you need to re-sequence the IDs of any table in which you delete stuff from the vanilla game (especially lots of stuff, such as the UnitPromotions table). You can find a more credible explanation in the link at the end (dunno how to link in GitHub), but all you need to do is add to the bottom of any file in which items are deleted from the database the following, where UnitPromotions is replaced with the name of the table:

CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO IDRemapper (Type) SELECT Type FROM UnitPromotions ORDER BY ID;
UPDATE UnitPromotions SET ID =	( SELECT IDRemapper.id-1 FROM IDRemapper WHERE UnitPromotions.Type = IDRemapper.Type);
DROP TABLE IDRemapper;

UPDATE sqlite_sequence
SET seq = (SELECT COUNT(ID) FROM UnitPromotions)-1
WHERE name = 'UnitPromotions';

This I have confirmed to resolve (at least some) of the ctds, in relation to the UnitPromotions table. A user reported a CTD when using CBP when my "Warrior's Service" event popped up with using Cultural Diversity. This event has the option to reward you with a free unit which begins with the Shock 1 and Drill 1 promotions. Without remapping the IDs, the event will attempt to give the unit promotions with IDs corresponding to the original IDs of those promotions - however, because you delete all promotions, there are no promotions with those original IDs, resulting in the crash. After remapping the IDs, I retested this event - checked the database to ensure that the IDs were resequenced (and they were; instead of starting from 234, IDs started from 0) - and voila; no crash.

Hope this brings some much needed stability between E&D and CBP; it certainly has between CBP and CulDiv.

http://forums.civfanatics.com/showthread.php?t=463429

**Comment by LoneGazebo** [comment]
Fantastic. I hadn't considered this, but it makes total sense. I'll add this to next version. 

G
