### ISSUE TITLE
City States Indifferent about Barbs

### ISSUE THREAD

**Issue by throwtheway2** [LoneGazebo/Community-Patch-DLL#2780]
1. Mod version: 11/16 (not modpack)

2. Mod list (if using Vox Populi only, leave blank): 
RED v28b2 - However; loaded mid-game, just now, on turn 106. Problem persisted through first 105 turns and continues. On hindsight, I should have added it after taking a screenshot. Regardless, VP alone can be assumed.

3. Error description: City states do not post Barbarian Encampment quests. I discovered both the city states pictured below early on. The encampments have also been around for around ~20 turns. The stars indicate locations where I have cleared already encampments (after dillying, sometimes dallying, for the quest to appear) without the quests spawning in the end.

Notes:
I made sure that I actually met the city states, and not just the area through crude maps/otherwise. 
Both city states have had a quest to explore some region of the map since the beginning. Vancouver, additionally, wants me to connect jewelry.

Really slows down early game diplomatic play.
PS. Lake Victoria looks like a mess. Thank you all immensely for creating this mod.

4. Steps to reproduce (optional):

---------------------------
Supporting information:
1 screenshot.
![quest](https://cloud.githubusercontent.com/assets/23196107/20092720/c0f6196a-a5c3-11e6-9ed1-f032f4c95947.png)

**Comment by LoneGazebo** [comment]
CS quests are randomized.
