### ISSUE TITLE
Chateau (11/6)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#2781]
_1. Mod version (i.e Date - 4/23):_
11/6

_2. Mod list (if using Vox Populi only, leave blank):_
CP
CBO
IGE

_3. Error description:_ 

> Increased Food and Gold on Chateau by +1

Chateau doesn't receive +1 Food.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

4. Screenshots (optional):
![chateau](https://cloud.githubusercontent.com/assets/11933188/20103026/ac50b658-a60b-11e6-96e1-56504e5c62ee.jpg)

**Comment by Enrico-Swagolo** [comment]
Also, Amber was forgotten about and still gives 2 Science. Or so the monopoly thingamajig says.

**Comment by LoneGazebo** [comment]
3 and 3 are correct - changelog typo.
