### ISSUE TITLE
Celtic pantheon Bran doesn't provide city growth modifier

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#2785]
_1. Mod version (i.e Date - 4/23):_
10/28

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Upon adopting the Bran pantheon, city food output remains exactly the same. CityGrowthModifier in the Beliefs table is empty for this pantheon. The text description states that it should provide a 25% bonus.

**Comment by LoneGazebo** [comment]
You get a cookie! Ifix.

**Comment by Edaka** [comment]
Yay!
