### ISSUE TITLE
AI bribing to war bug

### ISSUE THREAD

**Issue by zetanist** [LoneGazebo/Community-Patch-DLL#2786]
1. Mod version (i.e Date - 4/23):
11/6, Vox Populi (EUI)

2. Mod list (if using Vox Populi only, leave blank):

Calypso's Colored Religious Icons (Basic) (v 4)
Calypso's Colored Religious Icons (BNW Extended) (v 3)
Calypso's Colored Religious Icons (Extended) (v 5)
Civ Names by Policies (v 8)
Faster Aircraft Animations (v 3)
Improved City View (Vox Populi - with EUI) (v 9)
InfoAddict (v 22)
JFD's Cultural Diversity (Core) (v 11)
JFDs Cultural Diversity (Soundtrack) (v 1)
JFD's Exploration Continued Expanded (v 18)
Maps - Rotate Start Position (v 11)
R.E.D. Modpack (v 27)
Really Advanced Setup (v 15)
RemoveBanLuxury (v 1)
Unit Path Viewer (v 10)
Wonder Race (v 4)
World Congress Reformation (v 3)
(7) Community Events (v 3)
(8) Events and Decisions (CBO) (v 13)

Non of these should have any conflicts as far as I know.

3. Error description:

Yeah, yeah, I know. I said that I won't create Github, but for the sake of this project and my uprising interest in Civ V, I did it. 

Sweden gifts me some recources and other stuff, but when I click accept, I am suddenly at war with civs like France, Austria and basically every civ he wanted me to be at war with. But his war proposal doesn't show in my trading box. This same issue happened to me several times, trader was always Sweden, since nobody else wanted to bribe me to war.

4. Steps to reproduce (optional):

Logs: [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/579528/Logs.zip)
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 

5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![20161108225251_1](https://cloud.githubusercontent.com/assets/23347013/20119960/68242584-a613-11e6-867f-bef4c13683b7.jpg)

**Comment by Grabbl** [comment]
Can confirm the bug, with just Vox Populi enabled.

**Comment by LoneGazebo** [comment]
I need a save from just before it happens @Grabbl.

**Comment by HalfEmptyMug** [comment]
If you still need a save: [Save - War Bribe.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/582542/Save.-.War.Bribe.zip) 
Mods:
11/6 (No-EUI)
Ingame Editor (v. 39)
FlagPromotions (v. 7)
Quick Turns (v. 10)

During the next turn Polynesia attempts to bribe you into a war with Greece, but the DoW is hidden.
