### ISSUE TITLE
Not Getting +3 Science for Markets with Piety Syncretism

### ISSUE THREAD

**Issue by Pakur** [LoneGazebo/Community-Patch-DLL#2787]
_1. Mod version (i.e Date - 4/23):_10/28/16

_2. Mod list (if using Vox Populi only, leave blank):_Flag Promotions v7, Global - Barbarian XP Level 6 v2, Policy - Free Archer v1, Promotions - Siege Defensive Terrain v2, Units - Cheap Workboats v2, Faster Aircraft Animations v3, Quick Turns v10, Scouts Ignore Borders v2, XP from Forts v2, UI - National Wonder Splash Screens v10, UI - Project Splash Screens v8, Calypso's Colored Religious Icons (Basic) v4, and Calypso's Colored Religious Icons (Extended) v5.

_3. Error description:_ After earning the Syncretism policy in the Piety tree, I did not see the promised +3 science when I built markets in cities that followed my religion.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Nebuchadnezzar II_0439 AD-2019.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/579765/Nebuchadnezzar.II_0439.AD-2019.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Enrico-Swagolo** [comment]
Are you sure about that? I sometimes take Syncretism when not even having access to Caravansaries, and even then after taking it I see an increase in my Science per turn.

**Comment by Pakur** [comment]
Well, it is possible that I was receiving the extra science, but it was certainly was not showing in the city screen as a building yield, which is why I thought it was not working.
