### ISSUE TITLE
Amber is still 2 science monopoly

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2788]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
titsle says it pretty much. The yellow rocks still only get 2 science each instead of 3, or so the monopoly thingamajig claims.

I know I've reported that on CP forums but it's better to have it as a file in order to ensure it's not forgotten

**Comment by LoneGazebo** [comment]
Just a typo in the TT.
