### ISSUE TITLE
Each colosseum gives +18 Golden age and admiral points instead of +3

### ISSUE THREAD

**Issue by LPT440** [LoneGazebo/Community-Patch-DLL#2791]
_1. Mod version (i.e Date - 4/23):_
10/28

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_
I was playing Rome, Marathon speed and Emperor difficulty. After killing a few barbarians on turn 425 I started getting Great Generals and Admirals at very fast pace. The reason was that each Colosseum I had just build gives +18 Golden age and admiral points. Descriptions in game say they should each give +3.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all 

supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Augustus Caesar_0425 BUG.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/581308/Augustus.Caesar_0425.BUG.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![colosseum_bug](https://cloud.githubusercontent.com/assets/23362207/20145335/6feb3c22-a6a8-11e6-8b46-385b038a34e7.jpg)

**Comment by Edaka** [comment]
The points most probably scale with game speed and they definitely scale with era. Marathon has a x3 multiplier (x1 for standard, x2 for epic, IIRC). By turn 425 you must be in the Medieval era, which has a x2 multiplier. Those two combined, you get 3 (base) x 3 x 2 = 18

**Comment by Enrico-Swagolo** [comment]
It's normal. It scales by era AND game speed, and you play on Marathon where IIRC the values of everything like that are tripled.

So 3 x 3 = 9, and since it's medieval you double the value. 18 GAP/GGP + 18 GAP.

**Comment by LPT440** [comment]
Well, that explains it. Thanks guys.

Have to say, feels pretty overpowered since Great Admiral is 400 points at that time, and I get 126 points for each barbarian I kill =) Will have to play it through to see how it balances.
