### ISSUE TITLE
strange diplo offer

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2795]
![image](https://cloud.githubusercontent.com/assets/1358966/20191041/206f9eb8-a784-11e6-817e-dca204eb1ed5.png)

seems like the "war on x" entry is not being displayed

**Comment by tu-79** [comment]
Same here! But it's even worse. Because 'make peace on X' isn't showing, either.

**Comment by LoneGazebo** [comment]
Try latest version.

**Comment by pandasnail** [comment]
In current version too. Unfortch, nothing in Lua log, is there another one I shoud check for an error on this?

![20161110211632_1](https://cloud.githubusercontent.com/assets/16260521/20202155/3072637a-a78b-11e6-9e7e-6bfd2e13089b.jpg)

**Comment by LoneGazebo** [comment]
lua log?

**Comment by LoneGazebo** [comment]
ahh, I see why. Test this compatibility file and see if it works. If so, I'll hotfix (savegame compat).

**Comment by LoneGazebo** [comment]
[(6a) Community Balance Overhaul - Compatibility Files (EUI).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/584900/6a.Community.Balance.Overhaul.-.Compatibility.Files.EUI.zip)

**Comment by pandasnail** [comment]
I'll download now, but I don''t have a save right before, and I don't know how to make it happen, so idk how long before I can report back myself. Hopefully someone else will be able to tho.

**Comment by LoneGazebo** [comment]
Okay. Should fix it, but we'll see. Thanks for debuggin!

**Comment by pandasnail** [comment]
Can confirm the fox works.

**Comment by LoneGazebo** [comment]
cool. Closing!
