### ISSUE TITLE
AI often having problems with GPT management

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2796]
_1. Mod version (i.e Date - 4/23):_

Current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

So, I'm playing as the baguettes and I am fighting my enemies. Then I take a look at Portugal and they're still at a 0 gold -XX GPT, and they've been in the red for about 100 turns on Epic.

Same with Spain. From the civs I know, only India and Siam are not insanely in the GPT and not backwards. Portugal has 8 techs and I as well as the king of evil, Gandhi, are nearing our  20th.

I don't even know how Portugal is doing it since Gandhi's religion with +2 GPT +3Faith per connection is dominating her, and that should alleviate it at the very least.

Then I see her suddenly send a carpet of horsemen, warriors and spears in my direction and I start suspecting she was making too many troops for her own good. AI should consider disbanding troops or selling unimportant buildings if such a thing occurs. I often might sell a Granary if I see I am about to lose Science, but I doubt AI considers that a choice.

**Comment by Enrico-Swagolo** [comment]
Yeah, Portugal's and Spain's debt is increasing. Only me killing their units is a thing helping them in not falling further. They're at -59 and -45 respectively. They should consider... changing something. Because clearly they're doing something wrong.

**Comment by Enrico-Swagolo** [comment]
Portugal and Spain are both Tradition btw. It all seems a bit connected with the previous versions' problem of Tradition overexpanding resurfacing.

It's weird, considering how much Portugal has over-expanded. Early, it had 10 cities when my Authority civ had only 7. Judging from the state of her cities as I get my hands on them, she really prefers just spamming units over making any buildings. While 7 to 10 when I've preferred fighting than settling is not that bad, she still was a bit... Weird. If you want to go that wide that early, go Progress. Now I'm fighting her warriors (why didn't she just disband a few?), spears and horses as I have knights and the landsknechts (I'm trying them out again, but they're - as always - not very impressive, even against just horsemen) as well as one Musketeer from a ruin.

AI should consider disbanding units in such a situation, and especially not go Tradition if they want to make 10 cities so fast.

**Comment by Enrico-Swagolo** [comment]
Yeah Portugal seems to be making hundreds of Spearmen. No wonder she's doing this badly, same with Spain. By this point they're becoming free-culture-and-science-and-heal-men for me.

**Comment by Enrico-Swagolo** [comment]
Anyone else with similar experiences?

Anyway, I want to add. I find it's not only because of units, but often because of unprofitable trade routes. Some AI will make unreasonably long tile roads to connect to a fresh city for no reason, even when they could just wait a bit and just make a Lighthose, effectively wrecking any need for a road.

Like, Authority/Progress can and should make roads (especially Authority due to discount and it making it easy to move troops), but Tradition should perhaps wait. It's not like an empire which is not very wide will have happiness problems and so it's not mandatory to make that road ASAP.

**Comment by ilteroi** [comment]
the trade route logic can be weird, i agree. it's kind of hard for the AI to balance all the different yields and priorities ... and there is actually a piece of code that sends a food traderoute to the smallest city in order to get it to grow. kind of makes sense, i guess.

**Comment by Enrico-Swagolo** [comment]
I've actually meant city connections , not trade routes though. My mistake

**Comment by ashendashin** [comment]
Tradition civs are indeed destroying themselves at the moment. Every single one near me has tanked on gold massively due to over expansion. The fact that I made the map much bigger really shows how broken they are right now.

**Comment by Enrico-Swagolo** [comment]
Yeah, almost all Tradition civs usually sink their GPT with roads that do not help them (too expensive), overexpand and are overly aggressive in both unit production and war declaration which just doesn't work for them this early. Authority can do it (less maintenance on roads and units), so can Progress (Gold), but it's just Tradition. Like, once they've finished Tradition and are taking Piety - okay, being aggressively expanding then is acceptable, you'll be doing okay. I've tried it myself.

What's weird is that in this version I've had more Tradition civs declare war on me than Authority ones. It's as if AI thinks Tradition is the go-to policy tree for those who desperately want to make unprofitable city connections and spam units while never getting any buildings. Like, nearly every time I play Rome and am surrounded by Tradition civs, I'm disappointed by my conquest as even their capital has almost no buildings. What they do have is thousands of Spears.
