### ISSUE TITLE
Trouble Stopping City Population Growth

### ISSUE THREAD

**Issue by Pakur** [LoneGazebo/Community-Patch-DLL#2799]
_1. Mod version (i.e Date - 4/23):_10-28-16

_2. Mod list (if using Vox Populi only, leave blank):_Various additional minor mods, but none that should affect food or population growth.

_3. Error description:_ Originally posted this as a question at Civ Fanatics, and was advised to post it here as a potential technical glitch.  My question basically was how to prevent a city from growing in population. I have been having excessive unhappiness lately when my cities grow too large. If I go into the city screen and mark the box that supposedly limits population growth, it doesn't seem to work properly. Instead of simply halting population growth, it instead usually shows a negative available food amount for the city, and indicates that the city is starving. If I then micro manage my city so there is not a negative food amount, the population keeps growing (it increases slowly, but still keeps growing). Please let me know what I might be doing wrong. Thanks. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
The 'lock growth' button slows growth down to its minimum potential (sometimes causing starving). That's how it is supposed to work.

**Comment by Pakur** [comment]
Thanks for the quick explanation.  

I had mistakenly thought the lock growth button would simply stop all city population growth without causing any starving.  My memory is not the best, but I think that is how it used to work in non-modded Civ-5.  (Please forgive me if I am remembering that incorrectly.)

Now that I better understand how this game mechanic works in Vox Populi, I will make sure to more carefully micro-manage the population growth in my cities before unhappiness zooms to high.

P.S.  Thank you very much for creating and constantly improving the terrific set of mods called Vox Populi.
