### ISSUE TITLE
Killing A Lot of City-States lead to a glitched Declaration of War.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2800]
_1. Mod version (i.e Date - 4/23):_
11/10

_2. Mod list (if using Vox Populi only, leave blank):_
(7) Community Events	Version	3
Civ Names by Policies	Version	8
Civic And Reform	Version	4
Community Patch Mod Compatibility	Version	14
Diplomacy - Tech Bonuses	Version	1
InfoAddict	Version	19
Ingame Editor	Version	39
Krajzen's Great Musicians Pack	Version	1
Leadership Reformation	Version	4
More Great Works	Version	3
Music Changer	Version	2
Neolithic Wonders	Version	1
Quick Turns	Version	10
Really Advanced Setup	Version	15
World Congress Reformation	Version	3

_3. Error description:_ 
Bad War Declaration Reason. I'm sure this isn't as gamebreaking, but irritating since you are plagued with a THERE IS NO SCENE FOR THIS LEADER. Other civilizations who have other intentions for declaring war don't have this error.

_4. Steps to reproduce (optional):_
Have a war justified on city-states?

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): All logs display normally.
https://files.fm/u/npnnz444

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
https://files.fm/u/7nnp4yc3

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://cloud.githubusercontent.com/assets/13937047/20209233/228269a0-a7a8-11e6-886c-9fcc9f8d0a43.png)

**Comment by LoneGazebo** [comment]
Seems like a mod conflict maybe? Never seen and that code is untouched for a long time now.

**Comment by TechpriestEnginseer** [comment]
I've been using the same mod list for the past 10 months.
