### ISSUE TITLE
Nuke spawned in a neighbour's city after researching Manhattan project

### ISSUE THREAD

**Issue by Dawnbringerrb** [LoneGazebo/Community-Patch-DLL#2801]
_1. Mod version (i.e Date - 4/23):_
Version Nov 10

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
After researching Manhattan Project (first one to reach it), nuke spawned in a neighbour's city (but I still own it...)

_4. Steps to reproduce (optional):_
No idea.

![where da nuke](https://cloud.githubusercontent.com/assets/22627148/20218934/eac9e55e-a7f4-11e6-9299-e135e7338a45.PNG)

**Comment by LoneGazebo** [comment]
Neat. Was the city full?

**Comment by Dawnbringerrb** [comment]
There were no aircrafts in my capital. There was a single military unit in there, and like 3 workers stationed. I think there was also a great engineer waiting.

**Comment by LoneGazebo** [comment]
Huh. @ilteroi recent changes to jumptonearestplot acting up?

**Comment by pandasnail** [comment]
When a city state gave me a Great Writer, it didn't go in a city like normal, but one tile outside a city. Maybe related.

**Comment by supermerill** [comment]
Same for the free worker from the liberty policy. in 10-28: inside the city, in 11-10: outside the city

**Comment by ilteroi** [comment]
i didn't touch it
