### ISSUE TITLE
Giorgio Armeier offices not giving culture

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#2802]
_1. Mod version (i.e Date - 4/23):_

11/10 (first noticed in 10/28)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Giorgio Armeier offices not giving culture, even though there are franchises present. I am using EUI as well, and the culture value I should be getting shows up in the description when I hover over office building. However, there does not seem to be an actual yield anywhere.

I tested Firaxite Materials and Civilized Jewelers. Both of those seem to work. Hovering over the science and great person bars respectively shows the correct additional yields/great person generation.

_4. Steps to reproduce (optional):_

Create Quick game with IGE enabled. Send trade route to foreign city from a city with an office. Click next turn a few times. The turn before the franchise is created, take note of the culture yields of the originating city. Compare with culture yields after.

**Comment by LoneGazebo** [comment]
I'll look. May just be a UI issue.

**Comment by Radost** [comment]
Does it mean it doesn't provide culture or it's only UI issue?

**Comment by LoneGazebo** [comment]
Both actually. Fixed for upcoming.
