### ISSUE TITLE
can build grand temple without meeting requirements

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2803]
it says it needs to be a holy city and there has to be a temple in every city of the empire.

i can build it in my capital, which is not a holy city and has the only temple.

**Comment by LoneGazebo** [comment]
Should only be that city - tooltip or help are incorrect.

**Comment by Enrico-Swagolo** [comment]
Can confirm, I can build Grand Temple wherever I wish, whether it is the capital or Whatever-Town as long as it has a Temple.

**Comment by LoneGazebo** [comment]
That's correct behavior. Seems a text file isn't being updated properly. Since Grand Temple is a national wonder and replaced by the founder temples for holy site stuff, it has same requirements as other national wonders.

**Comment by ilteroi** [comment]
seems the EUI compatibility mod was not active
