### ISSUE TITLE
AI very rarely pillages, and has problems recovering workers

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2804]
_1. Mod version (i.e Date - 4/23):_

Current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Basically title. AI moves a Spearman (who is 1+ era behind my units) in front of my city, fortifies him and he dies as my Honour-given pikeman inside mauls him. He didn't pillage the Cotton on which he was, which is weird.

About workers, I sometimes steal enemy workers and on purpose move it on front of enemy army. They try to avoid un-slaving their own former worker/settler for no reason. Same with my workers - they almost never take them. I get it, that makes them seen as warmongerers more, but that's not the case with their own ones. THey should always reclaim those instead of waiting for years and just allowing me to transport them to my domain.

**Comment by LoneGazebo** [comment]
@ilteroi, more opportunistic pillaging?

**Comment by ilteroi** [comment]
i can confirm the lack of enthusiasm for capturing civilians.

but the pillaging works ok as far as i can see

**Comment by Enrico-Swagolo** [comment]
Yeah I agree, most of the time the AI does a very good job, but sometimes - very rarely so - they just won't. Like the time I've mentioned, when a Spearman embarked, ended up on 1 tile next to me city (coast) with Cotton, and just fortified there while Pikeman + City shot at him for 2 turns instead of at least pillaging and perhaps trying to run away (though futile, maybe he'd survive in the water as cities aren't always effective against units).

**Comment by ilteroi** [comment]
i might have a fix for the civilian capture, the non-plundering seems to be rare
