### ISSUE TITLE
Too Much Religious Increasing Buildings

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2805]
_1. Mod version (i.e Date - 4/23):_
11/10

_2. Mod list (if using Vox Populi only, leave blank):_
EUI

_3. Error description:_ 
Pressure Number doesn't appear in the City's UI if you have too much religious buildings that increase pressure which can result if you capture a foreign religious city and you try to bring another religion into it with their buildings.

_4. Steps to reproduce (optional):_
Have a city with a religion producing normal pressure. Having a Church shows the boost in pressure. Having a Church + Cathedral shows the boost in pressure as well. However, if I added a Mandir or another religious building that increases pressure. The pressure number disappears despite citizens are still being converted. It's more of a UI bug.

**Comment by LoneGazebo** [comment]
@Iamblichos want to take a gander at this?

**Comment by Iamblichos** [comment]
Yep!

**Comment by Iamblichos** [comment]
I can't reproduce this using your steps to reproduce.

**Comment by TechpriestEnginseer** [comment]
The latest version changed it somehow. I was using (10/28) when making this report.
