### ISSUE TITLE
Do AIs understand Defensive Pacts when accepting wars

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2807]
I've asked an AI to declare war on someone who had 3 defensive pacts and he was willing to do so for so cheaply (20 GPT?) Do they even understand that declaring war on one means a war on their allies as well?

**Comment by HalfEmptyMug** [comment]
Also vassals. I've seen AI declare war on civs that they might be able to take on alone, but are horribly out numbered when their allies are considered.

**Comment by LoneGazebo** [comment]
They do. I'll up the value though.
