### ISSUE TITLE
Ironworks Science

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#2808]
_1. Mod version (i.e Date - 4/23):_
11/10

_2. Mod list (if using Vox Populi only, leave blank):_
With EUI Improved City View
Really Adv Setup

_3. Error description:_ 
Ironworks claims to give 50 Science per Building (Scaling per Era)
Only gives 25

_4. Steps to reproduce (optional):_
Build Ironworks
Build Buildings

**Comment by TechpriestEnginseer** [comment]
````
INSERT INTO Building_YieldFromConstruction
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_IRONWORKS', 'YIELD_SCIENCE', 25);
````
in NationalWonderChanges.sql

**Comment by LoneGazebo** [comment]
I fix text.
