### ISSUE TITLE
Royal Library

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2809]
_1. Mod version (i.e Date - 4/23):_

Current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Unlike the Philosophical School, the Royal Library doesn't provide +5 Culture and has 1 Gold maintenance on top. It's the only (IIRC) UU/UB that is worse at anything compared to the thing it replaces. It's not like having that +5 Culture and no GPT cost would break it - Great Cothon is a NW that's much, much better in comparison.

**Comment by LoneGazebo** [comment]
That's a bug for the national college- should only be +5 science, not +5 science +5 culture.
