### ISSUE TITLE
AI denounces the player if it demands from him to denounce another civ

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#281]
And it gets backstab penalty along the way.

**Comment by Radost** [comment]
Moreover, I get some unreal diplo penalties(100+, that's more than ideology difference) for "denouncing" that way.
https://i.imgur.com/FH8xbEh.jpg
https://i.imgur.com/VF8q3BS.jpg

**Comment by LoneGazebo** [comment]
And you refused? Not sure how you triggered that.

**Comment by Radost** [comment]
Yeah, I've gotten that bug for refusal.

**Comment by LoneGazebo** [comment]
Well it isn't a bug - the AI is coded to potentially denounce you if you refuse to denounce on their behalf. I've reduced the penalty a bit to compensate, but this is normal.
G

**Comment by Radost** [comment]
-100 is "normal"? AI doesn't declare a war on you if he asked to start a war with another civ, why should it denounce?
Basically I had to compel to their demand or forget about diplomacy?
