### ISSUE TITLE
Stuck AI

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2810]
_1. Mod version (i.e Date - 4/23):_ 11/10

_2. Mod list (if using Vox Populi only, leave blank):_
 FlagPromotions v.7, Faster Aircraft Animation

_3. Error description:_ 
The very beginning of a game, Hawaii AI stuck with its warrior and a scout at the capital, instead of  exploring the surroundings.

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/587797/QuickSave.zip)
![20161113163734_1](https://cloud.githubusercontent.com/assets/16341598/20246476/1e20d710-a9c0-11e6-94eb-62614ff71b0a.jpg)

**Comment by ilteroi** [comment]
can't load it ... may gazebo can check?

**Comment by Enrico-Swagolo** [comment]
I sometimes see AI stop moving an unit for X turns/forever too, but they usually restart movement if I threaten them/declare war.

**Comment by saamohod** [comment]
>can't load it ... maybe gazebo can check?
 Did you enable FlagPromotions v.7 ?

**Comment by ilteroi** [comment]
yeah. pure UI mods shouldn't make a difference anyway. it's a problem with my database, i can only load saves from some people. don't know why, spent way too much time investigating already

**Comment by saamohod** [comment]
>yeah. pure UI mods shouldn't make a difference anyway. 
 Well, it says in the mod's description that "it affects savegames"

**Comment by LoneGazebo** [comment]
Loaded save and they started moving normally. Quirk?
