### ISSUE TITLE
Crusader spirit(again sorry)

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#2811]
_1. Mod version (i.e Date - 4/23):_
10/24

_2. Mod list (if using Vox Populi only, leave blank):_
VP + RED

_3. Error description:_ 
Right now, cs is providing 20% combat bonus just in enemy lands and just in lands of foreign religion founders. I dont know if it is intended to work this way, but if so, i plead for rework so it would provide 10% vs foreign founder units anywhere AND 10% for enemy lands no matter of previous bonus. I feel this bonus pop up less than intended. thanks.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
The values rely on territory ownership for their bonuses, so the 'unit based' element is a no-go.

**Comment by LoneGazebo** [comment]
I'll fix other part though.
