### ISSUE TITLE
CTD when pressing buttons.

### ISSUE THREAD

**Issue by Nillo11** [LoneGazebo/Community-Patch-DLL#2812]
_1. Mod version 10/28

_2. Mod list 
Quick Turns by Krzyzyk

_3. Error description:_ 
I get a CTD whenever I press a button. Sometimes it when I try to setup a game other times its ending my turn or trying to save. It can happen at any time and the only consistent thing I can think of is that it happens after I go through the mods menu.  

---------------------------
Supporting information:
I've tried doing:
 -a complete reinstall 
-running the game without Quick Turns
-running the game without anything but CBP installed
-Deleting the cache and ModUserData folders
-Lowering graphics settings

[CTD Buttons.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/588058/CTD.Buttons.zip)

**Comment by LoneGazebo** [comment]
Updated to a newer version. Also, using DX11?

**Comment by Nillo11** [comment]
Yes, using DX9 does not cause any problems.

**Comment by LoneGazebo** [comment]
Use dx11

**Comment by Nillo11** [comment]
After trying a bunch of games it looks like its somehow related to the Communitas map. Trying to save, load, restart or even exit a game with that map type causes the game to crash for me.
