### ISSUE TITLE
zero world congress votes

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2813]
![image](https://cloud.githubusercontent.com/assets/1358966/20248794/cb31c36c-a9eb-11e6-95e7-c67fffb1801f.png)

is that supposed to be possible?

**Comment by LoneGazebo** [comment]
Are you poland? Do you have MOD_BATTLE_ROYALE turned on in the custommods.h file?

**Comment by ilteroi** [comment]
yes i was poland but i didn't modify anything

**Comment by LoneGazebo** [comment]
Is that value enabled in your dll?

**Comment by ilteroi** [comment]
ah yes, it is ... what does it do?

**Comment by LoneGazebo** [comment]
It is for TPangolin's upcoming battle royale. Disable it.

**Comment by supermerill** [comment]
oh... the secret project of TPangolin...
I'm looking forward to see more more ai battle with iteroi's tactical AI.

**Comment by LoneGazebo** [comment]
Shh! Secrets.

**Comment by ilteroi** [comment]
well ok then
