### ISSUE TITLE
Naga-Malla lacks the "Can Move after Attacking" promotion

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2815]
Unlike the Cuirassier which it replaces.

**Comment by LoneGazebo** [comment]
Intentional because it is an elephant.

**Comment by TechpriestEnginseer** [comment]
Should be stated on its tooltip if it's not that it sacrifices its ability to move after attacking for the feared elephant or something like this.

**Comment by Radost** [comment]
It is an elephant but also a replacement for ranged cavalry. -1 movement is already a huge penalty for them, since elephants can't do a "move in - double shoot - move out" trick. The lack of movement after shooting on top of that makes them worse than the unit they replace.

**Comment by LoneGazebo** [comment]
They hit like bricks and have a very high came though.

**Comment by LoneGazebo** [comment]
CS*

**Comment by Radost** [comment]
I wouldn't call +3 more RCS "hit like bricks", especially since it's harder to perform double attacks. As for CS, Cuirassiers can avoid the damage altogether, which is superior to bonus CS.

**Comment by LoneGazebo** [comment]
That's one view. In any case this is balance, should be brought up in thread on forum.
