### ISSUE TITLE
Game closes itself at around 500 turns

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#2817]
Has happened in two games of mine, both at about turn 500. Has anyone else experienced this?

**Comment by ilteroi** [comment]
not really ... some questions to make progress here:

- which version? any other mods?
- did you play all 500 turns in one session? 
- is the crash reproducable after loading an autosave from just before? 
- do you have a minidump file? (can be found in folder where civ5.exe is located)

**Comment by ilteroi** [comment]
closing this because of lack of information
