### ISSUE TITLE
AI doesn't focus on UBs enough

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2818]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

So, I'm Rome. I see naughty guys like Alex and Sully.

Alex is in medieval, and yet most of his cities do not have an Acropolis (can be seen not only by CS being low, but also by me not keeping it on conquest). I conquer his stuff way more easily thanks to that as it provides +10CS to a city. Same with Sully - I want to get some nice Ottoman Forges, but I conquer his cities and see lots of weird building choices (why build Granaries and Markets before OForge on an island surrounded with coast?).

While AI-lex has an excuse as his thing requires a Monument IIRC (and I doubt AI civs are told to focus buildings on a line which is connected to their UB, only UB itself), Sully has no excuse. He doesn't need anything before OForge is accessible, and he can enjoy bonus production and science as soon as it's up.

**Comment by TechpriestEnginseer** [comment]
More like the UBs aren't flavored correctly as seen here:
````
INSERT INTO Building_Flavors
	(BuildingType, FlavorType, Flavor)
VALUES
	('BUILDING_ODEON', 'FLAVOR_CULTURE', 20),
	('BUILDING_ODEON', 'FLAVOR_HAPPINESS', 15),
	('BUILDING_SIEGE_WORKSHOP', 'FLAVOR_MILITARY_TRAINING', 40),
	('BUILDING_SIEGE_WORKSHOP', 'FLAVOR_PRODUCTION', 20),
	('BUILDING_SIEGE_WORKSHOP', 'FLAVOR_CITY_DEFENSE', 10),
	('BUILDING_SIEGE_WORKSHOP', 'FLAVOR_HAPPINESS', 25);
````
if Odeon definitely gives out combat strength, then it needs to have a FLAVOR_DEFENSE to it to justify walls. Siege Workshop might also need a little FLAVOR_SCIENCE and FLAVOR_OFFENSE.

I think this is the same for all UBs considering that all have unique effects that aren't being flavored by the AI.

**Comment by Enrico-Swagolo** [comment]
Yeah, Odeonpolis needs Flavour Defense and probably a much higher flavour culture and maybe flavour tourism if it exists. It gives a total of 10CS, +2 Tourism, +3 Culture, and +5Culture per kill (scaling per era/game length).

Basically, IMHO many UBs need a look at. Gazebo needs to pray to Machine Spirit harder so He makes the AI's UBs built more frequently.

**Comment by LoneGazebo** [comment]
>I think this is the same for all UBs considering that all have unique effects that aren't being flavored by the AI.
Sorry, but you are both incorrect on this. Flavors are largely irrelevant given my sanity logic for buildings.

**Comment by Enrico-Swagolo** [comment]
B-but sanity is for the weak...

**Comment by TechpriestEnginseer** [comment]
Doesn't hurt though. ;)
