### ISSUE TITLE
Something is wrong with AI switch regarding vote trade deals

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2819]
_1. Mod version:_ 11/10

![8930_20161117125459_1](https://cloud.githubusercontent.com/assets/1131228/20385120/f0ed1784-acd7-11e6-8a97-8fff74e2d66e.png)
In this scenario I am trading with my vassal and choosing "Yea" makes the deal "impossible" while he is very willing to vote against my WC proposal.

![8930_20161117141101_1](https://cloud.githubusercontent.com/assets/1131228/20385216/744838d4-acd8-11e6-820b-f87cdb571925.png)
In this case friendly non-vassal AI made a trade proposal, again assuming "Nay" of my WC proposal is something I would agree to.

![8930_20161117143020_1](https://cloud.githubusercontent.com/assets/1131228/20385403/17422446-acd9-11e6-8c12-7064b6c80a89.png)
In this case vassal AI came up with these terms, not my WC proposal this time, but aimed directly against me. 

So it's safe to assume something is wrong with vote trading evaluation on AI end.

**Comment by LoneGazebo** [comment]
Well the AI is going to ask you to agree to something that _they_ want, not something that you want. That said, vassals should be allies in the WC.

**Comment by Radost** [comment]
It doesn't matter what _they_ want when the point of trade deals is giving out the terms _I_ would agree.

**Comment by LoneGazebo** [comment]
Not necessarily - humans offer the AI deals all the time that favor the human over the AI. The same exists for deals in this context.
