### ISSUE TITLE
Indonesia UA and UB don't ignore worker improvements in order to decide luxury placement

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#282]
So it can drop unique luxuries at least 2 tiles away from the founded city.

**Comment by LoneGazebo** [comment]
This is by design - the function searches for an open slot next to the city - if it can't find that, it will replace a non-resource improvement. The 2-tile maximum is dangerous, as the city might not have claimed the tile and then another player could get it.
G
