### ISSUE TITLE
Liberated City-States do not repair their pillaged improvements

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2820]
_1. Mod version:_ 11/10
![8930_20161117133532_1](https://cloud.githubusercontent.com/assets/1131228/20385609/f102aca0-acd9-11e6-8023-b8bc0f9c2d2e.png)

This city was liberated quite a while ago, yet hasn't build a single worker. It's not the first time I encounter this issue either.

**Comment by jantjeuh83** [comment]
Noticed this as well. Had to repair their stuff by myself, but couldn't clean up the Fallout (their city got nuked).
