### ISSUE TITLE
Can't dig an antiquity site on AI territory

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2821]
_1. Mod version (i.e Date - 4/23):_ 11/10

![8930_20161117150409_1](https://cloud.githubusercontent.com/assets/1131228/20385897/1dbfd80c-acdb-11e6-810c-2182cdb2090c.png)
This is my vassal, so I have Open Borders with him. I did dig on the territory of another vassal just fine, so it's not a bug related to vassals only.

**Comment by matlajs** [comment]
do you have borders opened to each other?

**Comment by LoneGazebo** [comment]
Did the other artifact have an improvement under it?

**Comment by Edaka** [comment]
It can be seen that there's a village built on that tile and there's no other units on that tile except for the archaeologist. 

I've seen somebody on the forum say that he could dig in foreign lands up until being asked to stop by the AI - and as soon as the player refused, he was no more able to dig in foreign lands. Could be just a coincidence. I've seen a good number of players bringing this general issue, though. 

Would savegames be useful in debugging this?

**Comment by LoneGazebo** [comment]
Yeah, they would.

**Comment by LoneGazebo** [comment]
There's nothing in the code explicitly forbidding the UI from showing the build option because of that agreement, I need to look further.

**Comment by throwtheway2** [comment]
I have the same problem.
Other mods - RED Modpack (v28b3)
Notes:
No war (never any war)
Open border 
No improvement under site 
No diplomatic agreement to not dig 
Happens with other civilizations
Finished Aesthetics
![aaa](https://cloud.githubusercontent.com/assets/23196107/20472160/9236a946-afe1-11e6-9577-57c05e52d68f.png)

[Wu Zetian_0278 AD-1816.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/602811/Wu.Zetian_0278.AD-1816.zip)

**Comment by LoneGazebo** [comment]
I still can't reproduce this in a game. If this happens again, please post a save.

**Comment by Radost** [comment]
I encountered this problem again and turns out you have to open the borders to the civ you want to dig in. Since vassalage enforces 1-sided open borders, hence the issue.
Kinda counterintuitive tbh.

**Comment by LoneGazebo** [comment]
@Radost you have to give them open borders to your land to go into theirs?

**Comment by Edaka** [comment]
Going by what @Radost said I think it goes like this: if somebody opens their borders to you, you can only go onto their land but not dig, unless you also open your borders to them.
