### ISSUE TITLE
CTD in ai turn

### ISSUE THREAD

**Issue by Sekisetsu** [LoneGazebo/Community-Patch-DLL#2822]
_1. Mod version (i.e Date - 4/23):_ 11/10

_2. Mod list (if using Vox Populi only, leave blank):_ Vox populi (full eui), really advanced setup, community events (v3)

_3. Error description:_  I got a CTD in turn 460. always in Arabian turn

_4. Steps to reproduce (optional):_ always at the same point after loading a save

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/597699/CvMiniDump.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/597701/Lua.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/597702/Database.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/597708/QuickSave.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
i've fixed a late-game crash which fits the description, don't know if it's the one though and we've since broken savegame compatibility ... closing this, reopen if it reoccurs
