### ISSUE TITLE
Building_YieldPerAlly and BuildingYieldPerFriend are mixed up.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2826]
They work properly, but their bonuses are mixed up instead. (CS friend provides the ally bonus, CS ally provides the friend bonus)

This is also misleading in the developer's notes(not that scaling with era is important)
![image](https://cloud.githubusercontent.com/assets/13937047/20428674/31db6fd6-ad3f-11e6-8d44-f698a6a9eef1.png)

**Comment by Iamblichos** [comment]
Where are they mixed up? In the C++ code, because it looks fine there...

**Comment by TechpriestEnginseer** [comment]
![image](https://cloud.githubusercontent.com/assets/13937047/20449041/e3cf50de-ad9b-11e6-8a79-6a46f8c50b40.png)

**Comment by TechpriestEnginseer** [comment]
The hotfix is 43 civ DLL-based.

**Comment by LoneGazebo** [comment]
weird. It shouldn't affect a normal game at all, but I don't know why the value defined out like that.

**Comment by TechpriestEnginseer** [comment]
Well it wouldn't affect a compatible save game, but it does happen when I'm trying to make a new game.
