### ISSUE TITLE
CBO: Can't liberate a City-state (11/17)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#2827]
_1. Mod version (i.e Date - 4/23):_
11/17

_2. Mod list (if using Vox Populi only, leave blank):_
CP + CBO (Automatic Installer)
IGE
without EUI

_3. Error description:_ 
When I captured a conquered City-state, the city was automatically annexed without a city-capture popup.

_4. Steps to reproduce (optional):_
Activate IGE
Switch your civilization
Select a City-state tile
Push a "Capture" button (please see below)
Deactivate IGE
Declare war on the Civilization
Capture the City (former City-state)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/599892/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Ramkhamhaeng_0007 BC-3720.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/599893/Ramkhamhaeng_0007.BC-3720.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![capture](https://cloud.githubusercontent.com/assets/11933188/20429871/8d46830c-add4-11e6-9c24-70c9f0caa957.png)

**Comment by LoneGazebo** [comment]
You've got a mod conflict with something, as you've got two lua errors that I can't easily diagnose.

**Comment by 8h42** [comment]
Though I started a new game without IGE, the same error occurred.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/600536/Logs.zip)
[Shaka_0202 AD-1420.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/600537/Shaka_0202.AD-1420.zip)
![active mods](https://cloud.githubusercontent.com/assets/11933188/20439548/5c15ef54-adff-11e6-9faa-ba644899a73d.png)

**Comment by LoneGazebo** [comment]
[PuppetCityPopup.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/600603/PuppetCityPopup.zip)

Aha I see. Drop this in your CBP->LUA folder.

**Comment by 8h42** [comment]
hmm....it is still not working, unfortunately.

**Comment by LoneGazebo** [comment]
[PuppetCityPopup.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/601210/PuppetCityPopup.zip)

Try this (same file, but rezipped).

**Comment by 8h42** [comment]
Fixed!
Thank you as always.

**Comment by LoneGazebo** [comment]
Good to hear. Will push to full update later on.


Cheers,

G
