### ISSUE TITLE
Remove "End Vassalage" dialogue option

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2828]
It is placed below the espionage intrigues AND doesn't have any confirmation window. I tend to accidentally release a vassal during full auto through spy intrigues.
There is a separate button for releasing them in the vassalage window anyway.

**Comment by TechpriestEnginseer** [comment]
More like make end vassalage option pop up a notification(like when you are about to denounce someone)

**Comment by LoneGazebo** [comment]
I'm not going to edit Putmalk's lua code.
