### ISSUE TITLE
Alhambra tracking bug

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2830]
_1. Mod version (i.e Date - 4/23):_
Current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Have two Horsemen made in one city, ensure they have no Drill. Upgrade one to Knight, the second one leave as he is. Get Alhambra in the city the Knight was from.

Drill won't be gotten by the Knight, but the Horseman will receive it. Apparently Alhambra loses track of who is from the city if the unit is upgraded? Not the case with Morale and Bushido from what I see, only Alhambra.

**Comment by LoneGazebo** [comment]
upgraded units retain this knowledge. My assumption is that the unit might have been a gift, or perhaps you are mistaken in its origin?

**Comment by Enrico-Swagolo** [comment]
That's impossible though. All the Knights have Morale while only one city has HEpic - the Capital, in which I've bought and produced the entirety of my army. They've all had 8 virtues before any other city I own got a Dojo, too.

**Comment by Enrico-Swagolo** [comment]
Weird that you can't reproduce it (I will attempt it in a game soon). The only thing I can think of that could have influenced it was water as there was lots of it around. Maybe being embarked at the time Alhambra is raised doesn't make you receive the promo? I will try and experiment.
