### ISSUE TITLE
Citadels not providing Defensive bonus

### ISSUE THREAD

**Issue by Xaviarlol** [LoneGazebo/Community-Patch-DLL#2831]
_1. Mod version (i.e Date - 4/23):_
13/11

_2. Mod list (if using Vox Populi only, leave blank):_
Infoaddict, Quickturns.

_3. Error description:_ 
Citadels not providing the +100% defensive bonuses

_4. Steps to reproduce (optional):_
Select a unit when at war. Mouseover a target unit in a citadel and look at the strength. The strength is unchanged and the damage is the same compared to not being on a citadel. See screenshot for more details.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![screens](https://cloud.githubusercontent.com/assets/23149984/20451557/e8338d12-ae4e-11e6-9ec5-9dac0ed7db40.png)

**Comment by LoneGazebo** [comment]
@ilteroi can you confirm?

**Comment by ilteroi** [comment]
no. works fine for me.
