### ISSUE TITLE
FPS drops when choosing production or purchasing

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#2832]
_1. Mod version (i.e Date - 4/23):_
11/17

_2. Mod list (if using Vox Populi only, leave blank):_
Ingame Editor (v. 39)
FlagPromotions (v. 7)
Quick Turns (v. 10)

_3. Error description:_ 
When assigning a production or making a purchase either in or out of city view the frame rate drops significantly (From 60 to just under 30 fps personally). This hit only occurs when the choose production/purchase window is open. Also, when choosing a production outside of city view (through the pop up over the next turn button) the camera is now constantly centering on the city, which may have something to do with it.

_4. Steps to reproduce (optional):_
Choose a production for a city. 

Hardware:
GPU - Nvidia 970m
CPU - Intel Core i7 4720HQ
Memory - 16gb

**Comment by LoneGazebo** [comment]
Flag promotions can cause FPS drops.

**Comment by HalfEmptyMug** [comment]
Issue persists with on CBP enabled

**Comment by LoneGazebo** [comment]
Shouldn't have any effect whatsoever. @Iamblichos care to test?

**Comment by HalfEmptyMug** [comment]
I managed to pinpoint the issue to line 304 in ProductionPopup.Lua under 
(6b) Community Balance Overhaul - Compatibility Files (No-EUI)

``Controls.Happiness:SetText( "[ICON_HAPPINESS_1]" .. city:getHappinessDelta() );``

Commenting this out solved the frame rate issue and prevented the camera from sticking to the city. 

When I said that the camera was *constantly* centering on the city, I meant that it seemed as though a command was constantly canceling the camera's movement while dragging the mouse, but the mouse's movement interrupted the command. This made the camera appear to jitteringly fight to stay focused on the city, which it was probably doing even when the camera was already centered.

This makes me think that since a delta is being fetched that a calculation is constantly being performed to obtain a value, which in turn is causing the camera to move. I could be completely wrong though, and it may just be an issue with my installation.

**Comment by LoneGazebo** [comment]
That explains the issue, as @Iamblichos rewrote that. I'm sure he'll figure it out. :)

G

**Comment by LoneGazebo** [comment]
@Iamblichos did you see this?

**Comment by Iamblichos** [comment]
Sorry been out of town. Will take care of this when I get back in town. Should be a simple fix.

**Comment by Iamblichos** [comment]
Fixed and pushed.
