### ISSUE TITLE
Can't Tribute a CS after going to next era for X turns

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2834]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So I am fighting Brazil and Antwerp is all orange (I can tribute). I think that going to next era will enhance my yields gotten from demanding, so I wait 3 turns until Steel is researched. I've been bullying the CS a lot, pretty much every time I've got the opportunity to do so.

Afterwards, Antwerp says I demanded tribute, has 800- and won't give me anything? Unless I did it without realising, that's weird. I will try again.

**Comment by LoneGazebo** [comment]
Techs cause city strength to change. Also when any player bullies a CS it affects their bully-ness.
