### ISSUE TITLE
Wierd Trade Route movement

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2836]
_1. Mod version (i.e Date - 4/23):_

Current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I saw someone mention the thing in my topic, but they didn't make a github topic so I made one. I can confirm that caravans love avoiding roads for no reason even if they're  made long after the road has been created, so I make the topic also by supporting it with my own experience.

**Comment by ilteroi** [comment]
please provide screenshots and ideally a savegame just before creating the trade route.

**Comment by Enrico-Swagolo** [comment]
[troute.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/602373/troute.zip)

I have savegames only during the trade route, but not before. The file only contains a screenshot.

**Comment by ilteroi** [comment]
i see the problem but i don't understand it. that really shouldn't be happening. roads are "cheaper" than rivers to move on.

**Comment by Enrico-Swagolo** [comment]
Other cities, further on the same road are using the road tile properly. In fact I wouldn't be surprised if, after the TR times out, it'd still be on the wrong pattern, but after moving it back to the city and outside of it, it also started respecting the road.

But the first time I've initiated this food-to-Osaka TR IIRC was when the road was on. It's a shame that you can't load my savegames, BUT

https://forums.civfanatics.com/threads/new-version-november-17th-11-17.605449/page-4#post-14572789

Look at Legedi's post, he has a savegame in which he claims he has the same problem. Maybe his savegame will work?

**Comment by ilteroi** [comment]
caching problem, the old route from before the road was built is still good so it's never updated
