### ISSUE TITLE
Tradition AI GPT management problem

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2837]
_1. Mod version (i.e Date - 4/23):_

Current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

It's basically the same as https://github.com/LoneGazebo/Community-Patch-DLL/issues/2796

Basically, Tradition AI are almost always doing very badly. They overexpand, make bad city connections that cost too much gold considering they shouldn't be having happiness problems anyway, get into huge -gpt, get almost no buildings and lots of worthless troops, becoming pathetically easy to beat later.

**Comment by ilteroi** [comment]
road building is now suppressed if the player has negative GPT

**Comment by phantommaxwell** [comment]
Good can report that I saw this early on.  Extra painful for the AI when the choose to forward settle.
