### ISSUE TITLE
Quantity of Coal not visible

### ISSUE THREAD

**Issue by bridger15** [LoneGazebo/Community-Patch-DLL#2838]
_1. Mod version (i.e Date - 4/23):_
11/17

_2. Mod list (if using Vox Populi only, leave blank):_
Colored religious icons (graphical adjustment only)
Global Relations
Quick Turns
RED Modpack
Show Move To
Units - Population

_3. Error description:_ 
(Playing as Catherine) Coal appeared on the map as normal when i researched the appropriate tech (dynamite?), but when hovering over the tile, it only lists "coal" and not "2 coal" or "4 coal" or whatever number should be there.  In addition, after creating a Mine on top of the coal in my territory, I do not see coal appear on the top right in my strategic resources section next to the iron and horses.

Attached zip file contains an image (you can also see it here: https://i.imgur.com/VUaAoNf.png), and the save file.  The above issue is true for all coal sites in my territory (4).

I will add that it appears that i do *have* the coal, because i can build a railroad station in cities that have been connected via railroad.  However, the only place i've found which lists how much coal i have is the monopolies screen, and even though I only built 2 mines it claims i have 36 of 53 coal?  I know catherine doubles the quantity of strat resources, but this is rediculous :P

[Downloads.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/604862/Downloads.zip)

**Comment by supermerill** [comment]
I had also this (visual) issue in my test game.

**Comment by bridger15** [comment]
Odd that you couldn't reproduce it.  I appear to still have this same problem in my current game using the 2/27 version.
