### ISSUE TITLE
Great Merchant AI without CP DLL

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2839]
I know that the CSD without the DLL uses the Great Merchant AI before.. but does it work? Does the AI show any example in attempting to train the diplomatic unit? I'm trying to incorporate a unique unit that'll optionally require a CP DLL.

**Comment by LoneGazebo** [comment]
CSD without the DLL uses the GM AI, yep. It uses flavors to train the diplo units.
