### ISSUE TITLE
CTD 11/10

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#2840]
_1. Mod version:
11/10
I know there's been an update but maybe this will sitll be relevent

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi
InfoAddict v27
Really Advanced Setup
Wonder Race v3

_3. Error description:_ 
Clicking a great work slot or going to the great work optimization window (through tourism icon on the top right of the screen) caused a CTD.  This would happen inconsistently.  Eventually, trying to load a previous save while in-game caused all recent saves of that game to CTD when loading.

---------------------------
Supporting information:

[Logs.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/608320/Logs.gz)

**Comment by Viitis** [comment]
I am having this same problem in 11-23 with only Vox Populi installed. I have attached a save file so you can try to replicate the issue. On the turn of the save game work fine but on the next turn opening a great works menu causes CTD.

[AutoSave_0336 AD-1916.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/618317/AutoSave_0336.AD-1916.zip)
