### ISSUE TITLE
CS buildings don't provide Friend bonuses for Allies

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2841]
_1. Mod version (i.e Date - 4/23):_

Currentt
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Title basically.

I've seen it on civfanatics but didn't bother to see myself if that indeed is the case despite befriending and allying CSs by the dozens with vicious abandon because it's too hard to count it. As the Friend bonuses are different yields than those on Allies, it'd make sense for Allies to get both Friend and Ally bonus.

**Comment by LoneGazebo** [comment]
The code does not support this report - it looks fine to me.

**Comment by TechpriestEnginseer** [comment]
Allies do already get the friendly bonuses. My Patronage Civic in Civics and Reform proves this itself.
