### ISSUE TITLE
Citadel kills grant no bonuses

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2844]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Kill someone with a Citadel.

Authority Science+Culture won't proc, bonuses like Roman GAP/GGP per kill also won't.

**Comment by LoneGazebo** [comment]
Correct. No one 'kills' them.
