### ISSUE TITLE
AI City Founded within 3 Tile Radius

### ISSUE THREAD

**Issue by muarB** [LoneGazebo/Community-Patch-DLL#2845]
_1. Mod version (i.e Date - 4/23):_
11/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Dutch founded an off-shore troll city on an island that was withing the 3-tile radius of my city.  Or to put it another way, I could have purchased the tile he put the city on.  Is this a bug or was something changed?  I tried for a screen-shot but they come out as black for some reason.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
You said island.

**Comment by muarB** [comment]
Oh I never knew that, it was an island.  Time to DOW on William.  Thanks.

**Comment by muarB** [comment]
Maybe there was a long discussion about the merits of reducing the island requirement that I missed, but my initial thought is, why make it different?

**Comment by LoneGazebo** [comment]
It is the same as vanilla.
