### ISSUE TITLE
Watermill yields

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2846]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

It's supposed to give 3p 3f. It gives 3p 2f. SQL only mentions 3 Production, what's needed is an identical line but with Food instead of Production.

**Comment by TechpriestEnginseer** [comment]
````
UPDATE Building_YieldChanges
SET Yield = '3'
WHERE BuildingType = 'BUILDING_WATERMILL' AND YieldType = 'YIELD_PRODUCTION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );
````
In SQL, if you take out the "AND YieldType = 'YIELD_PRODUCTION'", it would readjust to food as well.

**Comment by ricanuck** [comment]
I have the impression that the food yield is what G intended (same yield as the Well), and that the typo is in the changelog. Makes sense: the waterMILL's only advantage should be the extra production.

**Comment by LoneGazebo** [comment]
Typo is changelog yep.
