### ISSUE TITLE
Building_YieldPerAlly and Building_YieldPerFriend Tooltip needs to be reworded.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2847]
Example:
````"+1 [ICON_FOOD] Food in City for every City-State Friend, and +2 [ICON_PEACE] Faith for every Ally."````
Considering that some of Vox Populi user base aren't proficient in English or somewhat... This tooltip is misleading them to think that they would be losing the +1 Food if they upgraded their City-State friend toward an allied status. Based on my lurking, there have been 6 cases already of them misunderstanding them until they actually observed it or were notified of them.

I'd recommend the following tooltip instead or any better reworded alternative:`
````+2 [ICON_PEACE] Faith for every City-State Ally. +1 [ICON_FOOD] for every City-State Friend and Ally.````

**Comment by ricanuck** [comment]
Disagree. I think it's perfectly clear the way it is, and in line with other tooltips (Civ 6).
