### ISSUE TITLE
Desync with barbarian since 10-28

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#2848]
_1. Mod version (i.e Date - 4/23):_ 10-28 modpack, 11-17 modpack, 11-24 modpack

_2. Mod list (if using Vox Populi only, leave blank):_
vp modpack with eui

_3. Error description:_ 
desync every 2-7 turns with barbarians, no desync if no barbarians. Tested on multiple modpack (10-9, 10-28, 11-17 11-24) and with/without barbarian, (it took me, Dev4nt and il_separigio two day to figure it out, we even try with a complete reinstall of our civ5 game).

logs (on 10-28):
https://mega.nz/#!hthnHbqa!ngELhlAe7FdJspV_X5KSQDeDAJaNj2pdRcIxViT8d2w
https://mega.nz/#!dpBCkbIC!Tf4hEuBkp4gG3qLM9TseQ-5GbAO6AHvkDkh8iX7-OsQ

**Comment by LoneGazebo** [comment]
This happens with EUI. Use no-EUI.
