### ISSUE TITLE
 Great General Points and Great Admiral Points on UnitPanel.lua.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2849]
~~I haven't noticed any AI having any warmongering penalty despite me conquering an entire civilization? Are they just too friendly or deceptive now? I'm using EUI if that matters.~~

**Comment by TechpriestEnginseer** [comment]
Never mind there were being deceptive at hiding their warmongering penalty. (Gandhi who was just looking at me just declared war to stop my warmongering) Very smart AI!

**Comment by TechpriestEnginseer** [comment]
If I have a Build that say this improvement gives out GG or GA points, there'll be an error in displaying the yield.
````toolTip:insert( "[COLOR_POSITIVE_TEXT]+" .. L( g_yieldString[yieldID], yieldChange) )````
````bad argument #1 to 'L' (string expected, got nil)````

**Comment by LoneGazebo** [comment]
Not sure - I've had the GG/GA working fine for me.

**Comment by TechpriestEnginseer** [comment]
In another game it worked fine. In another game it doesn't. It's probably a mod conflict of some sort.

**Comment by TechpriestEnginseer** [comment]
Note the pull requests do not fix this because
````
[YieldTypes.YIELD_GREAT_GENERAL_POINTS or false] = "TXT_KEY_BUILD_GGP_STRING",
[YieldTypes.YIELD_GREAT_ADMIRAL_POINTS or false] = "TXT_KEY_BUILD_GAP2_STRING",
````
are marked all nil accordingly to YieldTypes.

**Comment by LoneGazebo** [comment]
They are hardcoded.

**Comment by TechpriestEnginseer** [comment]
Then, I'll do some further testing to see what can substitute for YieldTypes.GREAT_GENERAL_POINTS and YieldTypes.GREAT_ADMIRAL_POINTS for the UnitPanel.lua then...

**Comment by TechpriestEnginseer** [comment]
I'm revisiting this scene because it has a weird inconsistency.

**Comment by LoneGazebo** [comment]
The Unitpanel has a LUA related to yields IIRC.

**Comment by TechpriestEnginseer** [comment]
Which is the weird problem. I've looked into the differences.

UnitPanel calls for the yields differently than the yields in the other Lua. The other Lua can call up the ID for GGP and GAP thus properly displaying them while UnitPanel can't call GGP and GAP, but yet can call for Golden Age Points and Tourism which were new yields added from CP.

**Comment by LoneGazebo** [comment]
Make the text files referenced in the LUA exist?

**Comment by TechpriestEnginseer** [comment]
It had already existed.
````
		<Row Tag="TXT_KEY_BUILD_GGP_STRING">
			<Text>{1_Num}[ENDCOLOR] [ICON_GREAT_GENERAL] Great General Points</Text>
		</Row>
		<Row Tag="TXT_KEY_BUILD_GAP2_STRING">
			<Text>{1_Num}[ENDCOLOR] [ICON_GREAT_ADMIRAL] Great Admiral Points</Text>
		</Row>
````

**Comment by TechpriestEnginseer** [comment]
Eureka problem solved for UnitPanel!
