### ISSUE TITLE
Ranged units can't shoot over lake Victoria.

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#285]

**Comment by LoneGazebo** [comment]
That's because NWs are mountains. This can't be fixed. :(

**Comment by qqqbbb** [comment]
fix:
	<Natural_Wonder_Placement>
		<Update>
			<Where NaturalWonderType="FEATURE_LAKE_VICTORIA"/>
			<Set ChangeCoreTileToMountain="0"/>
		</Update>
	</Natural_Wonder_Placement>

**Comment by LoneGazebo** [comment]
Still shows as a mountain in dll (for range purposes), I believe. I'll check and see.

**Comment by qqqbbb** [comment]
I tested it and it works

**Comment by qqqbbb** [comment]
FEATURE_GEYSER, FEATURE_FOUNTAIN_YOUTH, and FEATURE_CRATER should probably be fixed too.

**Comment by LoneGazebo** [comment]
Fixed. Thanks! I've tested this before and it didn't work, but I think ilteroi made a change that fixed it in the DLL.

**Comment by qqqbbb** [comment]
Now units can walk on the lake. 
Fix: 	<Features>
		<Update>
			<Where Type="FEATURE_LAKE_VICTORIA"/>
			<Set Impassable="1"/>
		</Update>
 	</Features>
