### ISSUE TITLE
CTD during AI turn due to memory leak.

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2850]
_1. Mod version:_ 11/23

#2689 is back, although technically it was back two versions ago, I just didn't bother to report.
It goes like this: certain AI gets a "hiccup" during its turn (the screen freezes 2+ times) but then the turn gets through and the next turn goes without any problems. But on the turn after the "normal" one the game will freeze during the turn of the same AI and will consume memory until it crashes.

Saves (the one after the first hiccup and another before the leak CTD): https://mega.nz/#!ec9y0aaC!T2o_dd_QsGO5CSEVPRkgay1UlY4IYSC3HEyqcDfpcJw
Logs: https://mega.nz/#!yN81mJzQ!2kC0A84nBhbCEVN4JJe1i1Db-gwsN-WypbdeP6DjR5I
Additional mods: https://mega.nz/#!qFciiKha!vTsBluu1WFerHtqSRJNW1-S2FtlxAdWxlzGpoH1Y-jM

**Comment by LoneGazebo** [comment]
@ilteroi was this solved by recent bug fixes?

**Comment by ilteroi** [comment]
i fixed an out of memory problem (not really a leak) for 11/23 so this would be a different one? which is strange because we haven't had that in ages and now two at a time ...

can't load the save unfortunately.

**Comment by Radost** [comment]
Do you use luajit? I don't.

**Comment by LoneGazebo** [comment]
Could be an issue with localization, too. Never know. In any case we'll keep an eye out for memory leaks.

**Comment by ilteroi** [comment]
localization is the best bet ... some people's saves i can load, others crash. tried to debug it once, ended up with differences in database IDs, no idea how that can happen.
