### ISSUE TITLE
A few too many bugs

### ISSUE THREAD

**Issue by GSHFox** [LoneGazebo/Community-Patch-DLL#2852]
_1. Mod version (i.e Date - 4/23):_
11/24 ('merican)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
A crap ton of annoying bugs that happen by playing the game.

_4. Steps to reproduce (optional):_
Just enable any of the Vox mods in any order and play.

---------------------------
Supporting information:
Please note that you can attach .zip files by d.....

Yea no I don't know how to do any of that so I'm gonna copy paste my bugs that I've encountered.

 If I enable all mods, nothing in game works. From this point on I disabled the diplomacy mods. Barbarians only spawn ranged units, Pantheos/Religions have never worked, buildings only show trigger text instead of what it should be, every civilization loves everyone else and never declare war, scenarios crash after the first turn etc. If anyone could help me fix these bugs or tell me what to do that

**Comment by LoneGazebo** [comment]
best guess: 

- Your civ is not updated to .279. 
- You aren't actually starting a game through the mods menu.
- You didn't install it correctly.
- You have a mod conflict or two.
- You are missing DLC.
- You have a mod in your DLC folder causing issues.

**Comment by ricanuck** [comment]
Reduce to only one:
•Your civ is not updated to .279.

I am playing the latest version right now, not a single problem so far. Nothing even close to what you describe.

Update your version.
