### ISSUE TITLE
game hanging in Lua

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2855]
game and UI both are frozen, callstack says:

					if (LuaSupport::CallTestAny(pkScriptSystem, "CanLoadAt", args.get(), bResult))

can anyone take a look?

ps: i'm aware that this is not a lot of information :)

**Comment by Iamblichos** [comment]
what line in the call stack?

**Comment by ilteroi** [comment]
the lua callstack? no idea

**Comment by Vyyt02** [comment]
Wow, I just created a long post about my game freezing, stating that I cannot see any other reports like mine and then I found yours right after posting it. Do you mean the UI is frozen, but the game is still somewhat responsive?

A link to my report:
https://github.com/LoneGazebo/Community-Patch-DLL/issues/2866
