### ISSUE TITLE
AI settles too aggressively

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2856]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Basically, if there's free space to settle, the AI will do it (excl. rare cases). I see all AIs - Tradition, Progress, Authority - settle cities with too few tiles apart with no purpose.

I've noticed that the AI at first will make a mostly smart  city, but then they'll place another one 3 tiles apart because there's space available despite the new city not having anything of value that the other won't reach fast. The AI also is back to settling cities pretty much everywhere you leave a spot that can be settled - those cities that wouldn't exist if your cities expanded their borders just a bit? They're here in full force, but now only neighbours do that. The result is me razing the cities and swimming in free conquest yields.

**Comment by ricanuck** [comment]
Funny... I have a Japan now in my game that was the last one, by far, to settle the second and following cities... took like 150 turns to come out of the closet. Still doing OK though, managed to secure its part of the continent anyways.

**Comment by Enrico-Swagolo** [comment]
It's not about turns - they're raising them at an oaky speed most of the time (some slow, some fast) - it's more about their weird placement ideas. In time the AI will settle nearly any tile as long as it allows a city to be placed.

**Comment by TechpriestEnginseer** [comment]
It's because vanilla AI were punished for expanding aggressively and thus had to resort to forward settling in order to find some luxuries that the players were blessed for. In Vox Populi, the unhappiness mechanic were reworked and settler upgrades made it complementary for the AI to settle as much cities as possible. I even like that they have island cities if the mainlands were getting scarce for land.

**Comment by supermerill** [comment]
+1 with enrico, they will settle in very shitty place, like in the coast of the desert or ice, with only 2-3 resources but nothing else.

**Comment by ilteroi** [comment]
well, there's a natural wonder there. people have been complaining that the AI is ignoring them ... can't please everybody i guess.

also, with caravans to supply it and get the basic buildings up, a city actually needs very little "good" terrain to be viable. take a look at your best cities, between yields from buildings and specialist slots, they often work only 5 plots. so it's perfectly fine to settle close.

**Comment by Iamblichos** [comment]
My vote is to leave this as is. Better for AI to play aggressive than not.
