### ISSUE TITLE
Grabbing World Congress's Turns?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2861]
Game.GetLeague(m_iCurrentLeague):GetTurnsUntilSession() seems to be difficult for me to "catch" since m_iCurrentLeague is always printing nil or something that I can't just grab.

Can there be a Lua entry that allows me to grab the turns of the session? It's for that after the main World Congress convenes. A secondary or dummy World Congress then pops up an event.

**Comment by LoneGazebo** [comment]
What function does the interface use?

**Comment by TechpriestEnginseer** [comment]
Game.GetLeague(m_iCurrentLeague):GetTurnsUntilSession()

**Comment by LoneGazebo** [comment]
So why isn't that working for you?
