### ISSUE TITLE
Reoccurring CTD  using only Vox Populi 11/23.

### ISSUE THREAD

**Issue by Dlndstrm** [LoneGazebo/Community-Patch-DLL#2862]
_1. Mod version:_
11/23

_2. Mod list:_
Vox Populi Complete including EUI. I was using Faster Aircraft Animations and Quick Turns early on but disabled them; they do not affect saved games.

_3. Error description:_ 
CTD at turn 650 during AI operations, specifically after a public announcement from Rome.  Can't get past.
Have tried deleting cache/validating files/deleting&reinstalling VP to no avail. Game is updated and I've got all DLCs.

[Info.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/616368/Info.zip)

**Comment by Dlndstrm** [comment]
So I deleted Rome with IGE and continued playing to see if the bug would reoccur and it did, this time with Byzantium and at the same exact point, after a public announcement. At both times the civilizations causing the bug was the biggest one. Memory leak? 

[Info.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/622187/Info.zip)

**Comment by ilteroi** [comment]
can't load your saves unfortunately, but can you try the build below and tell me if it solves the issue?

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/622870/CvGameCore_Expansion2.zip)

**Comment by Dlndstrm** [comment]
I'll give it a try. Do you know why you can't load the saves.. ?

**Comment by Dlndstrm** [comment]
Unfortunately I couldn't open the save with the new dll. But perhaps you meant I should try with a new game?

**Comment by ilteroi** [comment]
unfortunately i can only load savegames from relatively few people, even when it's the same version - some sort of database incompatibility, best guess is a localization issue.

anyway, the linked DLL should be savegame-compatible with 11/23. don't really know what could be wrong. you can try with a new game, but of course that won't really answer the question.

**Comment by Dlndstrm** [comment]
.. and the logs didn't make anything clearer? i know nothing of these things, unfortunately. just figured they must be able to give some sort of info on the problem when the same thing occurred on two different occasions..?

**Comment by Dlndstrm** [comment]
i couldn't start a new game with that dll either :)

**Comment by Dlndstrm** [comment]
So, unfortunately this issue keeps repeating itself every game I play with VP installed so I have no choice but to stop playing with it. A tragedy since it's definitely one of the best overhauls of a game I've come across.

**Comment by LoneGazebo** [comment]
@Dlndstrm I rarely get CTDs these days. Make sure your civ is up to date and verify the cache.

**Comment by Dlndstrm** [comment]
I have done that.. many times :(

**Comment by LoneGazebo** [comment]
Figured so. I know it is not helpful, but I really can't replicate this on my end.
