### ISSUE TITLE
Battering Ram not getting a defense against ranged attacks?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2864]
This is with EUI. Also don't think they should be getting that -33% vs land units since they are battering rams.
![image](https://cloud.githubusercontent.com/assets/13937047/20684322/43cf25c0-b564-11e6-8da9-d8270b98c4b8.png)

**Comment by LoneGazebo** [comment]
I don't think all bonuses appear for barbs sometimes. Not sure why, never been able to reproduce.
