### ISSUE TITLE
Civ-Specific Events Occurrence?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2865]
Considering that Hokath's Civ-Specific Events are notched at 100% probability of occurring (RandomChance and RandomChanceDelta are set at 125). I find it suspicious that I haven't seen any one of them during my testing. Maybe I thought this was bugged and I decided to enable No Civ-Specific Events but they seem to yield the same results. Why are there no civ-specific events?

**Comment by LoneGazebo** [comment]
random chance scales off of 1000, not 100.
