### ISSUE TITLE
Midgame: screen freezes after few turns, but game still responsive

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#2866]
1. Mod version (i.e Date - 4/23): 10/28, but it first occurred with an earlier version (sorry, do not know which one, could be 9/19-ish)

2. Mod list (if using Vox Populi only, leave blank):
A lot of mods I have been using for over a year with VP, but I do not think the issue is related to mods

3. Error description:
Some time in early industrial era, the game screen gets stuck during my turn when I am panning through the map. The only thing moving is the mouse cursor. When I click, I can hear the sounds and the game seems to be responsive (e.g. when I click on the stuck "choose city production" button, I hear the click sound and then the sound of the voices and clutter in the city screen, when I press spacebar, I can hear units cycling), when I press the quicksave hotkey, the game is saved properly. When I kill the game in the task manager and reload, I can play for a few more turns and the same thing happens again. When it happened first, I was playing with the Ethnic Units mod, when I deactivated it, I could play for maybe 30-40 more turns (which could be a pure luck, but I doubt it) until the problem started to appear again. Lowering the graphics to the bare minimum did not help. I was always using the Win8 DX11 option when launching the game, when I tried with the ordinary DX11 option, it seemed to make the situation slightly better (I could proceed a few more turns). When I tried DX9, the game got stuck again, but this time I could pan the map while all the icons were leaving traces like this:

![civ-graphic-glitch](https://cloud.githubusercontent.com/assets/11929356/20773346/9f0fcd4c-b751-11e6-8221-a4dfb5a1553d.jpg)

Looks like the animation when you won the solitaire game in the old Windows, haha!

I am always playing on huge/large maps with more civs, so I am afraid that I am getting some graphic memory leaks. I have an i7, 8 Gb, nVidia GeForce GT 740M

4. Steps to reproduce (optional):
As I cannot see any such reports here on GitHub, I am afraid this problem is related only to my machine, do you have any idea, what could be causing it? I was not having these problems before (and I have been playing VP since the beginning). Things that changed recently for me:
- I started using the Tectonic map instead of Planet Simulator and Communitas. Tectonic maps are larger, but going from huge to large did not seem to help much as far as I can tell.
- I think I have updated my nVidia drivers (I updated them again to the newest one today - did not help)
- The thing first happened to me in a version shortly after the optimizations in the DLL which sped up the game greatly (amazing by the way!) - maybe it is just a coincidence

Cannot think of anything else, Any thoughts? I do not think that any logs would shed any light on this right?

**Comment by ilteroi** [comment]
impressive ... but i don't think that's something we can fix in the DLL, looks like a graphics engine problem.

**Comment by Vyyt02** [comment]
> impressive ...

umm ... thanks? :) Pretty isn't it? :)

Yeah, that's what I have been afraid of. The strange thing is it was not happening until August-ish - I don't have much time to play, so I am always skipping several versions. I suppose there is not log which would indicate what was going wrong, right?

By the is this the same issue you were describing in your post? I am not talking about the "abstract art" screenshot, but rather the screen becoming stuck while the game is still running and responsive.

**Comment by LoneGazebo** [comment]
We don't mess with the graphical engine @Vyyt02  - I'd check your drivers.

G

**Comment by ilteroi** [comment]
since i got a new gpu (nvidia instead of amd) i do got some glitches as well, like this:

![image](https://cloud.githubusercontent.com/assets/1358966/20876437/43811516-bac2-11e6-9be2-c2054b4245a3.png)

so yes, most definitely a graphics driver compatibiliy issue.

**Comment by LoneGazebo** [comment]
I'm on an nvidia card and I see no such glitches.

**Comment by Iamblichos** [comment]
GPU texture decode in video options make any difference (on/off)?

**Comment by ilteroi** [comment]
it's not a texture thing ... more like each vertex of a unit is connected to the origin with a straight line (the top left of the image is exactly the center of the map). funny effect.

**Comment by Vyyt02** [comment]
@ilteroi hmm ... yours is not bad either. I like the clean geometric looks of yours, while mine is more colourful and cheerful. Maybe we should paint together in multiplayer some time :) How do you deal with the problem? Do you reload? Or do you abandon the game? For me restarting the game and reloading fixes it only for 0-3 turns, then it gets stuck again.

@LoneGazebo I think I will try uninstalling the newest drivers and then downloading August-ish driver version instead. I hope it's possible. What is your GPU? Mine is GeForce GT 740M.

@Iamblichos I will try fiddling with the GPU settings first, but same as @ilteroi I don't think it is related to textures either. If playing with DX11, I am not getting the abstract painting, the screen just freezes while the game is still responsive (I can hear the sounds when cycling through units, I can quicksave, etc.)

Thanks for all the replies.

**Comment by LoneGazebo** [comment]
@Vyyt02 using a 960.

G

**Comment by Vyyt02** [comment]
Hmm. So I downgraded the drivers to the July 14th version, set the in-game graphics to the lowest, set the GPU to optimize for performance instead of quality and it got even worse. Now I load the game, zoom in and out a couple of times and then it gets stuck.

Oh well, I suppose I will have to play on smaller maps from now on :-(
