### ISSUE TITLE
Sometimes, City-states build nothing

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#2867]
_1. Mod version (i.e Date - 4/23):_ 11/23

_2. Mod list (if using Vox Populi only, leave blank):_ VP + city-state evolved

_3. Error description:_ 
from cityStrategyAiProductionLog:

```
018, Madagascar, Antananarivo, PRE: Unit, Worker, 180, 2
018, Madagascar, Antananarivo, PRE: Building, Barracks, 60, 4
018, Madagascar, Antananarivo, PRE: Building, Shrine, 50, 1
018, Madagascar, Antananarivo, PRE: Process, Farming, 15, 1
019, Madagascar, Antananarivo, PRE: Unit, Settler, 10675, 5
019, Madagascar, Antananarivo, PRE: Building, Arena, 2394, 6
019, Madagascar, Antananarivo, PRE: Building, Granary, 2359, 1
019, Madagascar, Antananarivo, PRE: Building, Walls, 1440, 4
019, Madagascar, Antananarivo, PRE: Unit, Dromon, 1303, 3
019, Madagascar, Antananarivo, PRE: Building, Monument, 1240, 1
019, Madagascar, Antananarivo, PRE: Unit, Trireme, 1208, 2
019, Madagascar, Antananarivo, PRE: Building, Council, 630, 1
019, Madagascar, Antananarivo, PRE: Unit, Catapult, 598, 3
019, Madagascar, Antananarivo, PRE: Unit, Archer, 563, 1
019, Madagascar, Antananarivo, PRE: Unit, Spearman, 484, 1
019, Madagascar, Antananarivo, PRE: Building, Forge, 360, 6
019, Madagascar, Antananarivo, PRE: Building, Well, 345, 2
019, Madagascar, Antananarivo, PRE: Building, Herbalist, 240, 4
019, Madagascar, Antananarivo, PRE: Unit, Worker, 180, 2
019, Madagascar, Antananarivo, PRE: Building, Lighthouse, 135, 6
019, Madagascar, Antananarivo, PRE: Building, Barracks, 60, 4
019, Madagascar, Antananarivo, PRE: Building, Shrine, 50, 1
019, Madagascar, Antananarivo, PRE: Process, Farming, 15, 1
020, Madagascar, Antananarivo, PRE: Unit, Settler, 10675, 5
020, Madagascar, Antananarivo, PRE: Building, Arena, 2394, 6
020, Madagascar, Antananarivo, PRE: Building, Granary, 2359, 1
```
no POST => it build nothing (even farming if i read correctly).

Should it have a failsafe to build something?

**Comment by LoneGazebo** [comment]
CSs do not use the sanity check for performance reasons.

**Comment by supermerill** [comment]
But it shouldn't happen to normal civs, no?

`
072, Ethiopia, Addis Ababa, PRE: Process, Farming, 225, 1
072, Ethiopia, Addis Ababa, PRE: Building, Pyramids, 170, 20
073, Ethiopia, Addis Ababa, PRE: Unit, Settler, 10325, 10
073, Ethiopia, Addis Ababa, PRE: Building, Granary, 3515, 6
073, Ethiopia, Addis Ababa, PRE: Building, Stele, 2360, 6
073, Ethiopia, Addis Ababa, PRE: Building, Shrine, 2200, 6
073, Ethiopia, Addis Ababa, PRE: Building, Herbalist, 1380, 11
073, Ethiopia, Addis Ababa, PRE: Building, Council, 1330, 6
073, Ethiopia, Addis Ababa, PRE: Building, Statue of Zeus, 675, 20
073, Ethiopia, Addis Ababa, PRE: Process, Farming, 225, 1
073, Ethiopia, Addis Ababa, PRE: Building, Pyramids, 170, 20
074, Ethiopia, Addis Ababa, PRE: Unit, Settler, 10325, 10
074, Ethiopia, Addis Ababa, PRE: Building, Granary, 3515, 6
074, Ethiopia, Addis Ababa, PRE: Building, Stele, 2360, 6
074, Ethiopia, Addis Ababa, PRE: Building, Shrine, 2200, 6
074, Ethiopia, Addis Ababa, PRE: Building, Herbalist, 1380, 11
074, Ethiopia, Addis Ababa, PRE: Building, Council, 1330, 6
074, Ethiopia, Addis Ababa, PRE: Building, Statue of Zeus, 675, 20
074, Ethiopia, Addis Ababa, PRE: Process, Farming, 225, 1
074, Ethiopia, Addis Ababa, PRE: Building, Pyramids, 170, 20
075, Ethiopia, Addis Ababa, PRE: Unit, Settler, 10325, 10
075, Ethiopia, Addis Ababa, PRE: Building, Granary, 3515, 6
075, Ethiopia, Addis Ababa, PRE: Building, Stele, 2360, 6
075, Ethiopia, Addis Ababa, PRE: Building, Shrine, 2200, 6
075, Ethiopia, Addis Ababa, PRE: Building, Herbalist, 1380, 11
075, Ethiopia, Addis Ababa, PRE: Building, Council, 1330, 6
075, Ethiopia, Addis Ababa, PRE: Building, Statue of Zeus, 675, 20
075, Ethiopia, Addis Ababa, PRE: Process, Farming, 225, 1
075, Ethiopia, Addis Ababa, PRE: Building, Pyramids, 170, 20
`

For this log, i'm running a test game with 43Civ / 28CS in ynaemp with cs evolved, so it may be my fault.
