### ISSUE TITLE
Possible bug with paper being VERY valuable

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#2868]
Sorry I'm on my phone so can't reproduce, but every AI civ is finding paper extremely valuable. In the early game when I got my first paper, I managed to get a 20GPT deal for one paper

Is this intentional?

**Comment by Radost** [comment]
You didn't mention what AI was it.

**Comment by RockettSJ** [comment]
My bad, this was Boudicca

**Comment by TechpriestEnginseer** [comment]
Notice the word early game when chanceries are unavailable and paper is only received from CSD wonders and the national wonder itself.
