### ISSUE TITLE
-Gold per turn civs (typically Tradition) causing their tech problems

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2871]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Basically title. Road AI change thingamajig didn't fix this at all. Every time I see, let's say, Egypt, and they pick Tradition, they'll proceed to swim in -GPT. Their cities do not have many or any buildings, they have an army but nothing is done with it and it soon becomes outdated as I reach even classical era. Some Authority civs it happens to too, but I don't think I've seen Progress civs with such an issue.

I mean, I do also get -10/20/30 GPT at some points in the game sometimes, but it's typically on top of my other Gold so it's not a hindrance, and I am smart enough to sell and rebuild stuff for profit, typically carrying me until I get Markets/Caravansaries/etc up.  I will even expend my last Great General in a wise spot and lose out on the CS bonus it provides to help me out.

What's weird is it wasn't here like 10 versions ago. Or rather, it wasn't happening often, The AI seems to be making units it can't afford if you're aggressive and they know you, even if they're far away,, is my best guess, but I could be mistaken? I don't even know. I've noticed that Portugal (Tradition) suddenly went into high -GPT when I've attacked someone to the north (and their lands were filled to the brim with units afterwards), which is why I've made such a conclusion.

I think the best solution at this point would be undoing that really old city connection nerf and probably the latest AI road refusal (without that old nerf, they will almost always be profitable).

**Comment by Vyyt02** [comment]
I also think keeping a positive (or rather not too negative) income in the early game is too difficult now - especially if going tradition. And I was wondering if the AI was able to deal with it. As you say, reverting the city connection nerf, or adding a +1 gold per city (or some early building) to some Tradition policy, might improve the situ a bit. I, as a human, am able to deal with it, if I focus heavily on gold production, but I think  the AI can get into trouble..

**Comment by LoneGazebo** [comment]
I can't replicate this - civs will go into negative GPT from time to time, but it is by no means endemic.

**Comment by Enrico-Swagolo** [comment]
It was in the previous version. I've only played it once on the current one and literally every AI went Progress and Authority, and those do not have such problems at such a frequency. If I encounter a situation like that, should I make screenshots or savegames? Together with those files in that folder you like that have to be enabled in a text file, which I forgot the name of at the moment? That's assuming the AI fixes didn't somehow influence the AI in that too.

**Comment by Enrico-Swagolo** [comment]
BTW the bigger the map, the worse it becomes. On Large, Tradition AIs in the previous version were nearly guaranteed to go into -50 GPT at one point and never go above 0 (unless you destroy all their units and conquer half of their cities). There were exceptions like Venice of course, it can't have problems like these as it won't get 5-8 cities fast.

Still gonna check if it's a problem in the current verison.

**Comment by LoneGazebo** [comment]
I tweaked the AI a little to not build units if in debt AND at 0 gold, so perhaps that'll help. Some deficit is going to happen (Esp. if there's a lot of early war).
