### ISSUE TITLE
Exception in latest git commit

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#2872]
_1. Mod version (i.e Date - 4/23):_ commit aa4c7764edf9fafbb5791f03717d74fff2dde237 (2016-12-3)

_2. Mod list (if using Vox Populi only, leave blank):_ vp modpack, see attach files

_3. Error description:_ when debugging the exception, it show me the chkstk.asm, with a stack trace from stackWalker files. It seems it fails to create the minidump. I'm not an expert in visual tudio debugging, do you know how to get the stack of the error that trigger the stackwalker?

I'm a bit stuck with this crash. It happens in all my games.

_4. Steps to reproduce (optional):_ use the modpack & the savefile. When loaded, pass 2 turns. It should crash in the mongolian turn. 

files: https://mega.nz/#!AhZW0bSK!JIQ-n728pFIQDpPwAJZRsddfjaP-oBMhqcIxT3wAahQ

**Comment by supermerill** [comment]
i know why: stackoverflow (no more memory on stack)

i don't think a 4000+ stack size is normal.
Maybe i should stick to release version when i modify things ^^
Do you work on this?

`  	ntdll.dll!RtlpLowFragHeapAllocFromContext()	Unknown
 	ntdll.dll!RtlpAllocateHeapInternal()	Unknown
 	ntdll.dll!RtlAllocateHeap()	Unknown
 	msvcr90.dll!malloc(unsigned int size) Line 163	C
 	CvGameCore_Expansion2.dll!operator new(unsigned int)	Unknown
 	CvGameCore_Expansion2.dll!std::_Allocate<std::_Tree_nod<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >::_Node>(unsigned int _Count, std::_Tree_nod<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >::_Node * __formal) Line 43	C++
 	CvGameCore_Expansion2.dll!std::allocator<std::_Tree_nod<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >::_Node>::allocate(unsigned int _Count) Line 145	C++
 	CvGameCore_Expansion2.dll!std::_Tree<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >::_Buynode(std::_Tree_nod<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >::_Node * _Larg, std::_Tree_nod<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >::_Node * _Parg, std::_Tree_nod<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >::_Node * _Rarg, const std::pair<enum PlayerTypes,int> & _Val, char _Carg) Line 1409	C++
 	CvGameCore_Expansion2.dll!std::_Tree<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >::_Copy(std::_Tree_nod<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >::_Node * _Rootnode, std::_Tree_nod<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >::_Node * _Wherenode) Line 1081	C++
 	CvGameCore_Expansion2.dll!std::_Tree<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >::_Copy(const std::_Tree<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> > & _Right) Line 1063	C++
 	CvGameCore_Expansion2.dll!std::_Tree<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >::_Tree<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> >(const std::_Tree<std::_Tset_traits<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> >,0> > & _Right) Line 531	C++
 	CvGameCore_Expansion2.dll!std::set<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> > >::set<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> > >(const std::set<std::pair<enum PlayerTypes,int>,std::less<std::pair<enum PlayerTypes,int> >,std::allocator<std::pair<enum PlayerTypes,int> > > & __that)	C++
>	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDanger(bool bPretendWarWithAllCivs, bool bIgnoreVisibility) Line 148	C++
 	CvGameCore_Expansion2.dll!CvPlayer::GetPlotDanger(const CvPlot & pPlot, const CvUnit * pUnit, AirActionType iAirAction) Line 42262	C++
 	CvGameCore_Expansion2.dll!CvUnit::GetDanger(CvPlot * pAtPlot) Line 8219	C++
 	CvGameCore_Expansion2.dll!PathEndTurnCost(CvPlot * pToPlot, const CvPathNodeCacheData & kToNodeCacheData, const UnitPathCacheData * pUnitDataCache, int iTurnsInFuture) Line 1181	C++
 	CvGameCore_Expansion2.dll!PathCost(const CvAStarNode * parent, const CvAStarNode * node, int __formal, const SPathFinderUserData & data, CvAStar * finder) Line 1306	C++
 	CvGameCore_Expansion2.dll!CvAStar::udFunc(int (const CvAStarNode *, const CvAStarNode *, int, const SPathFinderUserData &, CvAStar *) * func, const CvAStarNode * param1, const CvAStarNode * param2, int operation, const SPathFinderUserData & data) Line 348	C++
 	CvGameCore_Expansion2.dll!CvAStar::LinkChild(CvAStarNode * node, CvAStarNode * check) Line 589	C++
 	CvGameCore_Expansion2.dll!CvAStar::CreateChildren(CvAStarNode * node) Line 529	C++
 	CvGameCore_Expansion2.dll!CvAStar::FindPathWithCurrentConfiguration(int iXstart, int iYstart, int iXdest, int iYdest, const SPathFinderUserData & data) Line 378	C++
 	CvGameCore_Expansion2.dll!CvPathFinder::GetPlotsInReach(int iXstart, int iYstart, const SPathFinderUserData & data) Line 2461	C++
 	CvGameCore_Expansion2.dll!TacticalAIHelpers::GetAllPlotsInReachThisTurn(const CvUnit * pUnit, const CvPlot * pStartPlot, ReachablePlots & resultSet, int iFlags, int iMinMovesLeft, int iStartMoves, const std::set<int,std::less<int>,std::allocator<int> > & plotsToIgnoreForZOC) Line 11671	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDangerSingleUnit(CvUnit * pLoopUnit, bool bIgnoreVisibility, bool bRemember) Line 102	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDanger(bool bPretendWarWithAllCivs, bool bIgnoreVisibility) Line 176	C++
 	CvGameCore_Expansion2.dll!CvPlayer::GetPlotDanger(const CvPlot & pPlot, const CvUnit * pUnit, AirActionType iAirAction) Line 42262	C++
 	CvGameCore_Expansion2.dll!CvUnit::GetDanger(CvPlot * pAtPlot) Line 8219	C++
 	CvGameCore_Expansion2.dll!PathEndTurnCost(CvPlot * pToPlot, const CvPathNodeCacheData & kToNodeCacheData, const UnitPathCacheData * pUnitDataCache, int iTurnsInFuture) Line 1181	C++
 	CvGameCore_Expansion2.dll!PathCost(const CvAStarNode * parent, const CvAStarNode * node, int __formal, const SPathFinderUserData & data, CvAStar * finder) Line 1306	C++
 	CvGameCore_Expansion2.dll!CvAStar::udFunc(int (const CvAStarNode *, const CvAStarNode *, int, const SPathFinderUserData &, CvAStar *) * func, const CvAStarNode * param1, const CvAStarNode * param2, int operation, const SPathFinderUserData & data) Line 348	C++
 	CvGameCore_Expansion2.dll!CvAStar::LinkChild(CvAStarNode * node, CvAStarNode * check) Line 589	C++
 	CvGameCore_Expansion2.dll!CvAStar::CreateChildren(CvAStarNode * node) Line 529	C++
 	CvGameCore_Expansion2.dll!CvAStar::FindPathWithCurrentConfiguration(int iXstart, int iYstart, int iXdest, int iYdest, const SPathFinderUserData & data) Line 378	C++
 	CvGameCore_Expansion2.dll!CvPathFinder::GetPlotsInReach(int iXstart, int iYstart, const SPathFinderUserData & data) Line 2461	C++
 	CvGameCore_Expansion2.dll!TacticalAIHelpers::GetAllPlotsInReachThisTurn(const CvUnit * pUnit, const CvPlot * pStartPlot, ReachablePlots & resultSet, int iFlags, int iMinMovesLeft, int iStartMoves, const std::set<int,std::less<int>,std::allocator<int> > & plotsToIgnoreForZOC) Line 11671	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDangerSingleUnit(CvUnit * pLoopUnit, bool bIgnoreVisibility, bool bRemember) Line 102	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDanger(bool bPretendWarWithAllCivs, bool bIgnoreVisibility) Line 176	C++
 	CvGameCore_Expansion2.dll!CvPlayer::GetPlotDanger(const CvPlot & pPlot, const CvUnit * pUnit, AirActionType iAirAction) Line 42262	C++
 	CvGameCore_Expansion2.dll!CvUnit::GetDanger(CvPlot * pAtPlot) Line 8219	C++
 	CvGameCore_Expansion2.dll!PathEndTurnCost(CvPlot * pToPlot, const CvPathNodeCacheData & kToNodeCacheData, const UnitPathCacheData * pUnitDataCache, int iTurnsInFuture) Line 1181	C++
 	CvGameCore_Expansion2.dll!PathCost(const CvAStarNode * parent, const CvAStarNode * node, int __formal, const SPathFinderUserData & data, CvAStar * finder) Line 1306	C++
 	CvGameCore_Expansion2.dll!CvAStar::udFunc(int (const CvAStarNode *, const CvAStarNode *, int, const SPathFinderUserData &, CvAStar *) * func, const CvAStarNode * param1, const CvAStarNode * param2, int operation, const SPathFinderUserData & data) Line 348	C++
 	CvGameCore_Expansion2.dll!CvAStar::LinkChild(CvAStarNode * node, CvAStarNode * check) Line 589	C++
 	CvGameCore_Expansion2.dll!CvAStar::CreateChildren(CvAStarNode * node) Line 529	C++
 	CvGameCore_Expansion2.dll!CvAStar::FindPathWithCurrentConfiguration(int iXstart, int iYstart, int iXdest, int iYdest, const SPathFinderUserData & data) Line 378	C++
 	CvGameCore_Expansion2.dll!CvPathFinder::GetPlotsInReach(int iXstart, int iYstart, const SPathFinderUserData & data) Line 2461	C++
 	CvGameCore_Expansion2.dll!TacticalAIHelpers::GetAllPlotsInReachThisTurn(const CvUnit * pUnit, const CvPlot * pStartPlot, ReachablePlots & resultSet, int iFlags, int iMinMovesLeft, int iStartMoves, const std::set<int,std::less<int>,std::allocator<int> > & plotsToIgnoreForZOC) Line 11671	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDangerSingleUnit(CvUnit * pLoopUnit, bool bIgnoreVisibility, bool bRemember) Line 102	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDanger(bool bPretendWarWithAllCivs, bool bIgnoreVisibility) Line 176	C++
 	CvGameCore_Expansion2.dll!CvPlayer::GetPlotDanger(const CvPlot & pPlot, const CvUnit * pUnit, AirActionType iAirAction) Line 42262	C++
 	CvGameCore_Expansion2.dll!CvUnit::GetDanger(CvPlot * pAtPlot) Line 8219	C++
 	CvGameCore_Expansion2.dll!PathEndTurnCost(CvPlot * pToPlot, const CvPathNodeCacheData & kToNodeCacheData, const UnitPathCacheData * pUnitDataCache, int iTurnsInFuture) Line 1181	C++
 	CvGameCore_Expansion2.dll!PathCost(const CvAStarNode * parent, const CvAStarNode * node, int __formal, const SPathFinderUserData & data, CvAStar * finder) Line 1306	C++
 	CvGameCore_Expansion2.dll!CvAStar::udFunc(int (const CvAStarNode *, const CvAStarNode *, int, const SPathFinderUserData &, CvAStar *) * func, const CvAStarNode * param1, const CvAStarNode * param2, int operation, const SPathFinderUserData & data) Line 348	C++
 	CvGameCore_Expansion2.dll!CvAStar::LinkChild(CvAStarNode * node, CvAStarNode * check) Line 589	C++
 	CvGameCore_Expansion2.dll!CvAStar::CreateChildren(CvAStarNode * node) Line 529	C++
 	CvGameCore_Expansion2.dll!CvAStar::FindPathWithCurrentConfiguration(int iXstart, int iYstart, int iXdest, int iYdest, const SPathFinderUserData & data) Line 378	C++
 	CvGameCore_Expansion2.dll!CvPathFinder::GetPlotsInReach(int iXstart, int iYstart, const SPathFinderUserData & data) Line 2461	C++
 	CvGameCore_Expansion2.dll!TacticalAIHelpers::GetAllPlotsInReachThisTurn(const CvUnit * pUnit, const CvPlot * pStartPlot, ReachablePlots & resultSet, int iFlags, int iMinMovesLeft, int iStartMoves, const std::set<int,std::less<int>,std::allocator<int> > & plotsToIgnoreForZOC) Line 11671	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDangerSingleUnit(CvUnit * pLoopUnit, bool bIgnoreVisibility, bool bRemember) Line 102	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDanger(bool bPretendWarWithAllCivs, bool bIgnoreVisibility) Line 176	C++
 	CvGameCore_Expansion2.dll!CvPlayer::GetPlotDanger(const CvPlot & pPlot, const CvUnit * pUnit, AirActionType iAirAction) Line 42262	C++
 	CvGameCore_Expansion2.dll!CvUnit::GetDanger(CvPlot * pAtPlot) Line 8219	C++
 	CvGameCore_Expansion2.dll!PathEndTurnCost(CvPlot * pToPlot, const CvPathNodeCacheData & kToNodeCacheData, const UnitPathCacheData * pUnitDataCache, int iTurnsInFuture) Line 1181	C++
 	CvGameCore_Expansion2.dll!PathCost(const CvAStarNode * parent, const CvAStarNode * node, int __formal, const SPathFinderUserData & data, CvAStar * finder) Line 1306	C++
 	CvGameCore_Expansion2.dll!CvAStar::udFunc(int (const CvAStarNode *, const CvAStarNode *, int, const SPathFinderUserData &, CvAStar *) * func, const CvAStarNode * param1, const CvAStarNode * param2, int operation, const SPathFinderUserData & data) Line 348	C++
 	CvGameCore_Expansion2.dll!CvAStar::LinkChild(CvAStarNode * node, CvAStarNode * check) Line 589	C++
 	CvGameCore_Expansion2.dll!CvAStar::CreateChildren(CvAStarNode * node) Line 529	C++
 	CvGameCore_Expansion2.dll!CvAStar::FindPathWithCurrentConfiguration(int iXstart, int iYstart, int iXdest, int iYdest, const SPathFinderUserData & data) Line 378	C++
 	CvGameCore_Expansion2.dll!CvPathFinder::GetPlotsInReach(int iXstart, int iYstart, const SPathFinderUserData & data) Line 2461	C++
 	CvGameCore_Expansion2.dll!TacticalAIHelpers::GetAllPlotsInReachThisTurn(const CvUnit * pUnit, const CvPlot * pStartPlot, ReachablePlots & resultSet, int iFlags, int iMinMovesLeft, int iStartMoves, const std::set<int,std::less<int>,std::allocator<int> > & plotsToIgnoreForZOC) Line 11671	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDangerSingleUnit(CvUnit * pLoopUnit, bool bIgnoreVisibility, bool bRemember) Line 102	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDanger(bool bPretendWarWithAllCivs, bool bIgnoreVisibility) Line 176	C++
 	CvGameCore_Expansion2.dll!CvPlayer::GetPlotDanger(const CvPlot & pPlot, const CvUnit * pUnit, AirActionType iAirAction) Line 42262	C++
 	CvGameCore_Expansion2.dll!CvUnit::GetDanger(CvPlot * pAtPlot) Line 8219	C++
 	CvGameCore_Expansion2.dll!PathEndTurnCost(CvPlot * pToPlot, const CvPathNodeCacheData & kToNodeCacheData, const UnitPathCacheData * pUnitDataCache, int iTurnsInFuture) Line 1181	C++
 	CvGameCore_Expansion2.dll!PathCost(const CvAStarNode * parent, const CvAStarNode * node, int __formal, const SPathFinderUserData & data, CvAStar * finder) Line 1306	C++
 	CvGameCore_Expansion2.dll!CvAStar::udFunc(int (const CvAStarNode *, const CvAStarNode *, int, const SPathFinderUserData &, CvAStar *) * func, const CvAStarNode * param1, const CvAStarNode * param2, int operation, const SPathFinderUserData & data) Line 348	C++
 	CvGameCore_Expansion2.dll!CvAStar::LinkChild(CvAStarNode * node, CvAStarNode * check) Line 589	C++
 	CvGameCore_Expansion2.dll!CvAStar::CreateChildren(CvAStarNode * node) Line 529	C++
 	CvGameCore_Expansion2.dll!CvAStar::FindPathWithCurrentConfiguration(int iXstart, int iYstart, int iXdest, int iYdest, const SPathFinderUserData & data) Line 378	C++
 	CvGameCore_Expansion2.dll!CvPathFinder::GetPlotsInReach(int iXstart, int iYstart, const SPathFinderUserData & data) Line 2461	C++
 	CvGameCore_Expansion2.dll!TacticalAIHelpers::GetAllPlotsInReachThisTurn(const CvUnit * pUnit, const CvPlot * pStartPlot, ReachablePlots & resultSet, int iFlags, int iMinMovesLeft, int iStartMoves, const std::set<int,std::less<int>,std::allocator<int> > & plotsToIgnoreForZOC) Line 11671	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDangerSingleUnit(CvUnit * pLoopUnit, bool bIgnoreVisibility, bool bRemember) Line 102	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDanger(bool bPretendWarWithAllCivs, bool bIgnoreVisibility) Line 176	C++
 	CvGameCore_Expansion2.dll!CvPlayer::GetPlotDanger(const CvPlot & pPlot, const CvUnit * pUnit, AirActionType iAirAction) Line 42262	C++
 	CvGameCore_Expansion2.dll!CvUnit::GetDanger(CvPlot * pAtPlot) Line 8219	C++
 	CvGameCore_Expansion2.dll!PathEndTurnCost(CvPlot * pToPlot, const CvPathNodeCacheData & kToNodeCacheData, const UnitPathCacheData * pUnitDataCache, int iTurnsInFuture) Line 1181	C++
 	CvGameCore_Expansion2.dll!PathCost(const CvAStarNode * parent, const CvAStarNode * node, int __formal, const SPathFinderUserData & data, CvAStar * finder) Line 1306	C++
 	CvGameCore_Expansion2.dll!CvAStar::udFunc(int (const CvAStarNode *, const CvAStarNode *, int, const SPathFinderUserData &, CvAStar *) * func, const CvAStarNode * param1, const CvAStarNode * param2, int operation, const SPathFinderUserData & data) Line 348	C++
 	CvGameCore_Expansion2.dll!CvAStar::LinkChild(CvAStarNode * node, CvAStarNode * check) Line 589	C++
 	CvGameCore_Expansion2.dll!CvAStar::CreateChildren(CvAStarNode * node) Line 529	C++
 	CvGameCore_Expansion2.dll!CvAStar::FindPathWithCurrentConfiguration(int iXstart, int iYstart, int iXdest, int iYdest, const SPathFinderUserData & data) Line 378	C++
 	CvGameCore_Expansion2.dll!CvPathFinder::GetPlotsInReach(int iXstart, int iYstart, const SPathFinderUserData & data) Line 2461	C++
 	CvGameCore_Expansion2.dll!TacticalAIHelpers::GetAllPlotsInReachThisTurn(const CvUnit * pUnit, const CvPlot * pStartPlot, ReachablePlots & resultSet, int iFlags, int iMinMovesLeft, int iStartMoves, const std::set<int,std::less<int>,std::allocator<int> > & plotsToIgnoreForZOC) Line 11671	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDangerSingleUnit(CvUnit * pLoopUnit, bool bIgnoreVisibility, bool bRemember) Line 102	C++
 	CvGameCore_Expansion2.dll!CvDangerPlots::UpdateDanger(bool bPretendWarWithAllCivs, bool bIgnoreVisibility) Line 176	C++
 	CvGameCore_Expansion2.dll!CvPlayer::GetPlotDanger(const CvPlot & pPlot, const CvUnit * pUnit, AirActionType iAirAction) Line 42262	C++
 	CvGameCore_Expansion2.dll!CvUnit::GetDanger(CvPlot * pAtPlot) Line 8219	C++
 	CvGameCore_Expansion2.dll!PathEndTurnCost(CvPlot * pToPlot, const CvPathNodeCacheData & kToNodeCacheData, const UnitPathCacheData * pUnitDataCache, int iTurnsInFuture) Line 1181	C++`

**Comment by ilteroi** [comment]
hmm.  it think i now what's up ... try with 871dcf7ad9af877e99e9d67b3c0e115eebabd7b3 (fefe branch)

**Comment by supermerill** [comment]
it work! thank you.
