### ISSUE TITLE
Communitas map restart crash

### ISSUE THREAD

**Issue by Zymoz** [LoneGazebo/Community-Patch-DLL#2873]
_1. Mod version (i.e Date - 4/23):_
December 5th, 2016 (12/5).

_2. Error description:_ 
Game crashes when starting up a Communitas map and then instantly restarting. Only occurs on Communitas map, all other normal maps work fine with restarting.

_3. Steps to reproduce (optional):_
Very close to default setup except on the Communitas map. It only crashes 100% when you reload right after generating it. Loading the save works fine but then reloading it keeps crashing.

Setup:
![setup](https://cloud.githubusercontent.com/assets/24408287/20923507/0eae6b68-bbad-11e6-9722-d61454d85b07.PNG)

_4. Files:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/633528/Logs.zip)
[Crashes on restart Boudicca_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/633529/Crashes.on.restart.Boudicca_0000.BC-4000.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/633531/CvMiniDump.zip)

**Comment by Enrico-Swagolo** [comment]
Yeah, it happens like 80% of the time. Can confirm. I still use it because it's the most fun map generator.

**Comment by LoneGazebo** [comment]
@Zymoz 
The crash is in lua, meaning it is the script (or another mod you have installed) causing the issue. I can't debug that, sorry.

**Comment by Zymoz** [comment]
Enrico do you just run with whatever start you end up with or do you just setup a new game instead of reloading?

**Comment by Enrico-Swagolo** [comment]
Well, if I can tell on turn 0 that the game is going to not be fun or this realisation dawns upon me a few turns in, I attempt to reload in hope that it doesn't crash this time (in the second case, I typically load turn 0 autosave, and attempt restarting map). If it crashes, I reenter the game and make a new game. If it doesn't, I enjoy the fact I am now going to have a more enjoyable setting.
