### ISSUE TITLE
Cannot negotiate peace for other civs

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#2874]
_1. Mod version (i.e Date - 4/23):_
11/23

_2. Mod list (if using Vox Populi only, leave blank):_
vox populi
info addict 27
really advanced setup

_3. Error description:_ 
Cannot ask other civs to make peace with another civ, even if they have a higher warscore.  I asked early on and even after a lot of turns had passed.  This used to happen on older versions as well.

---------------------------
Supporting information:

Try asking Portugal to make peace with The Mayans

[bug.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/636402/bug.gz)

**Comment by LoneGazebo** [comment]
The AI has been tweaked on this front to only accept deals in certain situations - Portugal may have reasons to reject your offer.

**Comment by jimmymcperson** [comment]
In that case, shouldn't the interface at least let you queue up the option and have Portugal list it as "Deal Value: Impossible!"?  In addition, the tooltip for the civ you want to make peace for doesn't show up, as opposed to mousing over other civs, which will give a tooltip saying something like "Portugal's warscore must be higher" or "They are not at war." (Not exact words)  This makes it seem like a bug.

**Comment by LoneGazebo** [comment]
@jimmymcperson no, because you can't evaluate a deal within a deal like that - way too expensive.

G

**Comment by jimmymcperson** [comment]
Ok, cool beans.  At the very least I think there should be a tooltip explaining that the civ is not willing to make peace.

**Comment by LoneGazebo** [comment]
Ah there was a quirk. I'll fix.
