### ISSUE TITLE
Cannot purchase monastery if the city has no religion followers.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2875]
If a city has absolutely no religion pressure, but has the ability to purchase monasteries, the game won't let them.

**Comment by LoneGazebo** [comment]
Right, because technically cities require at least one believer to purchase anything with faith. That's a core mechanic.

G

**Comment by TechpriestEnginseer** [comment]
It's a shame how Piety isn't as appealing if you don't have a founded religion.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer the idea of piety is to get you a religion (by pulling one from neighbors) if you lack one. If you're that bad off at the finisher (no religion anywhere), Piety might not have been the one for you. As what are you pious about, exactly?

**Comment by TechpriestEnginseer** [comment]
That it is surprisingly difficult to get someone to spread a religion to you when map setting are on islands compared to insanely fast when civs are both on the same landmasses when someone adopts Piety. Oh well.
