### ISSUE TITLE
Notification queues don't scroll when clicking on them

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2877]
_1. Mod version (i.e Date - 4/23):_ 12/5

The save: https://mega.nz/#!qN8jEQYL!yEFT1AtTWz8uiFQYZ-amEQPywSXeELicgMYfYrOKPCQ
Additional mods: https://mega.nz/#!qFciiKha!vTsBluu1WFerHtqSRJNW1-S2FtlxAdWxlzGpoH1Y-jM

**Comment by LoneGazebo** [comment]
Can't load the save, but could you clarify?

**Comment by Radost** [comment]
EUI bundles similar entries into this:
![coal](https://cloud.githubusercontent.com/assets/1131228/20996798/18dec0e4-bd22-11e6-838f-7c473a6fbe2b.png)
Clicking on this combined entry scrolls between them, but at some point it stops working. At first I've noticed this behavior with espionage-related entries. However, it seems to work fine just after reloading, only to break later.

**Comment by LoneGazebo** [comment]
Huh. Unfortunately I'm not going to mess with bc1's code. It is absolutely awful.
