### ISSUE TITLE
Leader mouseovers show less info when they demand something

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2878]
_1. Mod version (i.e Date - 4/23):_ 12/5
![8930_20161207011346_1](https://cloud.githubusercontent.com/assets/1131228/20988047/c2cf7bfc-bcf0-11e6-8236-42512dfafd99.png)
![8930_20161207010753_1](https://cloud.githubusercontent.com/assets/1131228/20988053/c819985e-bcf0-11e6-8241-3b9b525d5c1c.png)

**Comment by LoneGazebo** [comment]
EUI. Not going to fix, sorry.

**Comment by Radost** [comment]
It was working fine in previous versions, so it's not EUI fault.
