### ISSUE TITLE
A coup didn't make me the ally of CS

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2879]
_1. Mod version (i.e Date - 4/23):_12/5

![8930_20161208021221_1](https://cloud.githubusercontent.com/assets/1131228/20988126/30c273b2-bcf1-11e6-86cb-e895c43b6dfc.png)

The save two turns before I did a coup: https://mega.nz/#!rJ8yFQ5b!-Vaz3UhdzI1rUsJgTh4sjtVho9rdlMGOdheHdl6Alco
Additional mods: https://mega.nz/#!qFciiKha!vTsBluu1WFerHtqSRJNW1-S2FtlxAdWxlzGpoH1Y-jM

**Comment by LoneGazebo** [comment]
Possible that the coup coincided with Spain gifting a unit, sending a diplo unit, or something else?

**Comment by Radost** [comment]
How could she do any of that on my turn? Besides, if it would be enough for her to become an ally, then the spy would coup spanish supporters.

**Comment by LoneGazebo** [comment]
I'll look - the code is pretty explicit about making the coup-er the new ally, but might be a quirk somewhere.

**Comment by LoneGazebo** [comment]
Looked through the code, can't see how this happened. If it happens again, I'll do more investigations.
