### ISSUE TITLE
Venice doesn't get -66% population requirements for National Wonders

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#288]

**Comment by LoneGazebo** [comment]
It isn't supposed to, as venice's population is based on its empire, puppets included (unlike other civs).

**Comment by Radost** [comment]
So why do the changelog say it has?
>National Wonders -Changes:
>All National Wonders now require a certain national population to be constructed (instead of 
needing a specific building in every city). For Venice or OCC, this amount is reduced by 66%. 
See tooltips for specific amounts.

**Comment by LoneGazebo** [comment]
That’s a changelog typo. Venice gets a bonus of being able to count its puppets towards its national pop (other civs do not).
G
