### ISSUE TITLE
Is there a way to force-add a city-state quest to a city-state with Lua?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2880]

**Comment by LoneGazebo** [comment]
There is now:

pMinor->SetMinorCivActiveQuestForPlayer(eQuestPlayer, eQuestType, iTurnQuestGiven, eCallingPlayer (def. to NO_PLAYER));

**Comment by TechpriestEnginseer** [comment]
It works, now if only there was a failsafe to make sure that there aren't two quests that could CTD the game.

**Comment by TechpriestEnginseer** [comment]
How is iTurnQuestGiven determined especially for the barbarian horde and revolution quest? They seem to differ upon gamespeed and map size apparently. (I enter a 5 and I get 5 in Quick and Tiny, but a 5 is -180 in Huge and Normal weirdly)
