### ISSUE TITLE
Faith of the Masses and Jesuit Education

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2881]
Do they allow non-founders to purchase these buildings with faith? Because non-founders seem to be only benefiting from the extra culture and science bonus.

Unless the CityView.lua from Meister Maggi doesn't add those in..

On another note, diplomats in other civilization's capitals seem to be boosting tourism despite the tooltip saying they need an ideology at least.

**Comment by Radost** [comment]
Only the founders (or the owners of the Holy City to be exact) supposed to benefit from reformation belief, anything else is a bug.

**Comment by LoneGazebo** [comment]
Sounds like a lua error, as the code is correct for this.
