### ISSUE TITLE
Some Civ AI's not expanding - bug?

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#2883]
_1. Mod version: Latest December patch

_2. Additional mods: Ingame Editor & Tectonic Map Script

_3. Error description: Experienced several times in my games, that even after 70+ turns, some civs will not build a second city. I've got a screenshot here of Greece (who I regarded as an aggressive expansionist) still has only one city after 1 43 turns on epic speed. I don't know if this is a bug or if there is some reasoning behind it?

http://imgur.com/gOJ3U5G

**Comment by ilteroi** [comment]
some are a bit late to the party, that's true. but they do expand eventually, so i guess it's ok

**Comment by LoneGazebo** [comment]
Yeah. I think its okay.

**Comment by LoneGazebo** [comment]
(Probably mainly barbs pressing in)
