### ISSUE TITLE
Incorrect city attack bonus on Drill promotion

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#2884]
_1. Mod version (i.e Date - 4/23):_
10/31 (I think)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Text strings for all three Drills claim that the city attack bonus is 20%, while actually seems to be 25%.

**Comment by TechpriestEnginseer** [comment]
Code says +25%, Drill got a buff?
