### ISSUE TITLE
empty deal offer

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2887]
![image](https://cloud.githubusercontent.com/assets/1358966/21074644/97562704-befe-11e6-9677-89d080064db0.png)

it's not possible to accept it

**Comment by ilteroi** [comment]
the only relevant thing in logs is:

146, Russia, Assyria, Open Borders Offer

but nothing in lua.log

**Comment by LoneGazebo** [comment]
I can't find anything in the DLL to make this possible...I'll add a size check for the deal, though.
