### ISSUE TITLE
Multiplayer desyncs

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#2888]
_1. Mod version (i.e Date - 4/23):_ 

12/5 multiplayer modpack (both Dev4nt's and Iamblichos' versions with EUI)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Several desyncs from the start, around one desync every three turns. It makes the game unplayable on multiplayer. It's been a long time since we played MP the last time but this bug used to be fixed. We saw barbarians teleporting before these desyncs so we thought it could be because of the extra barbarian spawning in camps, but enabling chill barbarians didn't help.

_4. Steps to reproduce (optional):_

Start MP game and play few turns.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/644099/Database.zip)
[xml.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/644100/xml.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/644101/Lua.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Try no EUI.

**Comment by F0rst1** [comment]
Tried. It works fine without EUI. Went 21 turns without desyncs, then my eyes started bleeding from the standard UI and we had to stop. :) EUI must be the cause of desyncs however.

**Comment by LoneGazebo** [comment]
Yep. EUI is evil.

**Comment by LoneGazebo** [comment]
@ilteroi rest easy knowing that it is EUI causing the issue.
