### ISSUE TITLE
Zealotry not giving extra strategic resources

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#2889]
_1. Mod version (i.e Date - 4/23):_

12/5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

The zealotry description text says you should get 25% extra strategics in your own land. However, you don't get them. I had 10 iron in my land and didn't get any extra. I was the founder of the religion and had spread it in all of my cities.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Enrico-Swagolo** [comment]
I think it only influences it per tile, so if you don't have 4 Iron/4Horse at least on a tile, you get nothing. I could be mistaken though.

**Comment by F0rst1** [comment]
That isn't the problem. I had an iron tile with 6 iron and didn't get the additional iron I should have got.

**Comment by LoneGazebo** [comment]
@Enrico-Swagolo is correct - I'm going to increase the bonus to 50% to correct for this.

**Comment by TechpriestEnginseer** [comment]
Still not fixed since the resource doesn't change after you had the resource already if your city became converted. However, if your city became converted first and then the resource was improved. It works properly, although if the city loses that religion, the strategic resource bonus becomes permanent.

**Comment by LoneGazebo** [comment]
I'll take a look when I return. Probably just need to add a refresh check.
