### ISSUE TITLE
academy built outside of working range

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2890]
![image](https://cloud.githubusercontent.com/assets/1358966/21080520/7f5d13e8-bfb1-11e6-91df-bc44c56df944.png)

there were apparently no other plots available - but in that case they should take the instant yields

**Comment by ilteroi** [comment]
seems to be a venetian problem:

![image](https://cloud.githubusercontent.com/assets/1358966/21080537/cec39e8e-bfb1-11e6-816c-1de7fcf4c94e.png)

don't see it anywhere else

**Comment by ilteroi** [comment]
they are still building improvements in the middle of nowhere ... this is with 12/14

![image](https://cloud.githubusercontent.com/assets/1358966/21216037/e3dc755c-c2a4-11e6-9b32-e6856fc9536c.png)

**Comment by LoneGazebo** [comment]
That's intentional because the colonia expands borders like a citadel.

**Comment by ilteroi** [comment]
but there aren't any resources there - i guess the merchant could have been put to better somewhere else.

also the villages outside of working range are something you never see with other civs, although they are basically harmless.

anyway, this is nitpicking ...

**Comment by LoneGazebo** [comment]
Yeah it wasn't perfect placement. Perhaps I should hook the colonia into the citadel placement logic instead...

**Comment by ilteroi** [comment]
it's sometimes hard to judge whether a citadel-colonia for border expansion is better than a town-colonia for the yields
