### ISSUE TITLE
Recurring CTD

### ISSUE THREAD

**Issue by Muzinzafrika** [LoneGazebo/Community-Patch-DLL#2893]
_1. Mod version (i.e Date - 4/23):_
12/5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Recurring CTD

_4. Steps to reproduce (optional):_
Loaded the same save three times the outcome was always the same: during the AI's turn (after having traded with Siam) when Portugal starts its turn the game simply crashes to desktop.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

[Files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/644755/Files.zip)

**Comment by ilteroi** [comment]
can't load the save as usual

@LoneGazebo : mind trying? it did fix a crash recently, maybe it's gone already

**Comment by LoneGazebo** [comment]
I did, it crashed to lua.

**Comment by Dlndstrm** [comment]
Sounds like the issue I'm having with every game I play with VP :/

**Comment by LoneGazebo** [comment]
Can't load, hopefully latest ilteroi fix is a fix.
