### ISSUE TITLE
Incorrect yields listed for Cathedrals in the Found a Religion menu.

### ISSUE THREAD

**Issue by Zymoz** [LoneGazebo/Community-Patch-DLL#2895]
_1. Mod version:_
December 5th.

_2. Error description:_ 
Cathedrals are listed as having +3 gold and +3 faith while checking them in the Follower Belief menu.
When I lated looked at their actual stats after having built one, it says +2 gold, +2 faith.
This may not be the only incorrect yield value since many beliefs have been buffed or nerfed.

_3. Screenshots:_
![in religion menu](https://cloud.githubusercontent.com/assets/24408287/21125931/4ac0f4c2-c0e9-11e6-9034-0ad3840d6222.png)
![in game menu](https://cloud.githubusercontent.com/assets/24408287/21125937/5208388a-c0e9-11e6-9cbe-8c12ba002dc4.png)

**Comment by LoneGazebo** [comment]
Duplicate, already dealt with.
