### ISSUE TITLE
Intelligence Update

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#2899]
_1. Mod version (i.e Date - 4/23):_12/5, but also others

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The right side notification for the Intelligence Update CS quest has never worked for me, literally since you added it (even before I changed a bunch of CS names), and I thought with the project nearing completion, I'd post an error, and if you ignore a minor visual issue, obvi that's fine.

Nothing in the logs.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20161213143438_1](https://cloud.githubusercontent.com/assets/16260521/21156015/4ee3303e-c142-11e6-80f5-fed0e02df30c.jpg)

**Comment by phantommaxwell** [comment]
Oh, you have to check that quest by going to CS and checking what quests they have available.

**Comment by pandasnail** [comment]
Going into the code, there is something that is supposed to be there, just never has for me. Like you say, everything works in the individual City State screen, therefore a visual issue in the notifications, not a gameplay issue

**Comment by LoneGazebo** [comment]
I see why, I'll fix.
