### ISSUE TITLE
American UB doesn't state in description it gives 10 culture 10 Tourism to Sacred Sites

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#2901]
_1. Mod version (i.e Date - 4/23):_ 12-13
![clipboard01](https://cloud.githubusercontent.com/assets/1131228/21171338/2e70e1c4-c1ed-11e6-8473-71d042abfcf7.png)

**Comment by Edaka** [comment]
Sacred Sites is the reformation belief that grants tourism to faith-bought buildings, as well as tourism and culture to the Hemitage (or its replacement, the Smithsonian). I think holy sites are the tile improvements you were thinking about.

**Comment by LoneGazebo** [comment]
@Radost I think @Edaka is correct, the building gains that if you take Sacred Sites (as it is a hermitage replacement).
