### ISSUE TITLE
Thrift giving half gold.

### ISSUE THREAD

**Issue by ElliotS-1** [LoneGazebo/Community-Patch-DLL#2906]
_1. Mod version (i.e Date - 4/23):_
12-14-16 with hotfix dll from ilteroi on 12-18-16

_2. Mod list (if using Vox Populi only, leave blank):_
Unit Path Viewer v10 by Black.Cobra
Edit: Removed commander borders, forgot I didn't use that this time. 

_3. Error description:_ 
Thrift is giving half gold. The mod's files don't appear messed up (In the follower beliefs .sql), but maybe it's because I chose the production one first?

Imgur gallery with photos: http://imgur.com/a/NubBf
[ElliotS-BugReport.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/662761/ElliotS-BugReport.zip)

_4. Steps to reproduce (optional):_
Not sure. It works sometimes, and other times it doesn't.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
[ElliotS-BugReport.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/662762/ElliotS-BugReport.zip)

**Comment by ElliotS-1** [comment]
Update: Got a save one the turn I can enhance (different game), I already have thrift. Choosing any belief that gives 1 per 2 followers also reduces thrift's gold.

Have yet to try with getting thrift second.
[Boudicca_0145 BC-0425.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/671400/Boudicca_0145.BC-0425.zip)

**Comment by TechpriestEnginseer** [comment]
Yup choosing any belief that gives 1 per 2 followers reduce Thrift and Ascetism's bonus.
