### ISSUE TITLE
Can't load save after obtaining world map

### ISSUE THREAD

**Issue by ashendashin** [LoneGazebo/Community-Patch-DLL#2907]
_1. Mod version (i.e Date - 4/23):_
12/14

_2. Mod list (if using Vox Populi only, leave blank):_
FlagPromotions v7
Quick Turns
Really Advanced Startup

_3. Error description:_ 
This is probably just my old PC not being up to the task. I'm bringing this here because I'm fairly certain I've loaded this much of the map before without issue and for the chance that someone may provide help towards allowing my game to load.

Again, likely a problem on my end and just hoping to find help here. I'm surprised that this is happening after recent optimizations though.
[Before and After with minidump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/662773/Before.and.After.with.minidump.zip) just in case. "After" being after the map trade. I tried loading IGE on the Before save and it kept crashing, which is why I believe it's likely on my end.

Oh, and I've already tried setting my graphics down to minimal settings. Ended up breaking the game but it didn't crash. I usually run medium-high without trouble.

**Comment by Vyyt02** [comment]
So you are getting consistent CTDs even when you try to load the game from the main menu (= not from the game)?

It is most probably something completely different, but I had had problems with screen freezing (while game being still responsive) in the recent optimized VP versions:

https://github.com/LoneGazebo/Community-Patch-DLL/issues/2866

I was also unable to load some of the late-game saves. I tried different graphic details, different GPU settings, downgrading my nVidia drivers to July 14th version. I do not want to jinx it, but it seems that something I changed in the config.ini (located in the Steam/Civ5 folder) helped. I could proceed about further 100 turns without the screen freezing and with no loading problems whatsoever. The thing is that I tried so many things that I am not sure which helped. I think it could be the setting which preloads the terrain textures while loading the game. Many of the variables in the config.ini are undocumented, so it is kind of a hit or miss, but hey, it seems that something in there fixed my game (or maybe postponed the problem - need to play more to ber sure).

**Comment by ashendashin** [comment]
@Vyyt02 I've actually experienced both of the pics you posted. It's the reason I turned down many of my settings to medium in the first place and it worked until now. The first one is exactly what happens if I try to load it with minimal settings. The game does become unstable after getting the map though, so it's a hit or miss if it plays properly afterwards. Just the save is impossible to load.

The weird thing is that I've gone much further in older versions and the CTDs were never as bad when it came to graphical issues. Lowered my settings and the game would usually continue unless it's some other problem.

Thanks for tip! I'll mess around with my config and give it a go.

**Comment by Vyyt02** [comment]
@ashendashin I played a bit more. I am in the WWII era now with like 98% of the map uncovered and the game is still working and saves are loading fine. If I re-add the Ethnic units (which are save-compatible), I cannot load the recent saves however. When I got too confident, I was running the game with several browser tabs open and a few more apps at one point alt-tabbing in and out a lot and even playing some YouTube videos - after several hours, the game suddenly became sluggish and then the terrain flipped to grey tiles and the screen froze again (while game still being responsive).

I should add that I have quite a powerful machine and the game runs quite smoothly even in the later stages of the game. I could play on huge maps with 18-22 civs until summer.

Any progress on your side? Do you want me to upload my config.ini for you somewhere?

**Comment by ashendashin** [comment]
@Vyyt02 Nothing on my end. I've tried all of the lines that stand out in both the config and graphic settings and none of it works, short of trying certain certain combinations. Next version I think I'll try without any changes to the communitas map whatsoever and hope for the best.

I suppose it wouldn't hurt to try your settings. You can just upload a zip file of your config and graphic settings on here, thanks. And just in case, can you try loading my After save? Could be worth checking to see if my changes to the map causes trouble for you.

**Comment by Vyyt02** [comment]
Sorry to hear that. Now I have realized that I have also tampered with the GraphicsSettingsDX11.ini (man, I tried everything, haha!) That's where the texture preloading settings are:

; Init whole terrain before loading game
BlockOnLoad = 1

And sorry for a wrong info, the ini files are not in the Steam/.../.../ folder, but in the Documetns/My Games/Civ 5 .../
The one in the Steam/.../... folder is only a link to the one above. But I think you already know that.

I attach my config.ini and GraphicsSettingsDX11.ini (do not forget to back up yours first)

[configs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/676276/configs.zip)

The graphics settings are in GraphicsSettingsDX11.ini, so I won't post them here.

Sure, I can try loading your save. But I am on the 12-5 VP version now and I would like to find out how far I can get with my current game until (/if) the problems re-appear. Now I am on turn 661, tech-wise I am in WWII. As stated above, I got the gray terrain screen freeze once when I was really mean and running too many apps and I was unable to load my recent saves if I activated the Ethnic Units mod. When I finish this game I will update to 12-4 and try your save.

And knowing how strangely sometimes Civ5 acts, I would definitely try a game on a more "standard" map than Communitas. I myself like Tectonics map the most now, but as I had thought it might have been causing the glitches before, my current game is on PlanetSimulator (large).

**Comment by ashendashin** [comment]
Welp, this game seems lost for me. The tweaks have a noticeable impact on the game, but nothing that allows a successful load, post-trade. I think I'll play on a different, perhaps non-huge map next time.
I appreciate the help though. I got to discover some neat tweaks, at least.

**Comment by Vyyt02** [comment]
:-( I tried a new game - this time on large Tectonic and the problem reemerged. I can't load a save on turn 362. I can see the loading screen, but after waiting for a long enough time, when I press enter, I can hear the in-game sounds (e.g. units rotating, etc.) - still just seeing the loading screen.

I will try a new game with PlanetSimulator again or revert to some old pre-optimization VP version and see how far I will get.

**Comment by ashendashin** [comment]
So it isn't consistent after all. Do you think it'd be worth starting a poll on civfanatics? Could be interesting to see how common this is.

**Comment by supermerill** [comment]
If you have cdt when loading, you can try with the firetuner launched (from the civ5 sdk), and with enableFiretuner = 1 set into your config.ini.
It help me to load unloadable save.

**Comment by ashendashin** [comment]
Firetuner didn't allow me to load by itself. However, it did show me this error:
UnitFlagManager: IconHookup error - icon index:	0	icon size:	16	atlas:	KRIS_SWORDSMAN_PROMOTION_ATLAS	image control:	Promotion3(along with 4 and 5)
I turned off flagpromotions and my game loaded perfectly with my regular settings.
Thank you! It's a shame that I had to remove such a great mod, but now I can play without near as much worry.
Not sure if it's safe to continue this old game though. Does flagpromotions actually affect save games? It says it does. Also, were you using that mod too @Vyyt02 ?

**Comment by Vyyt02** [comment]
Wow! Flagpromotions! Yes, always using it. I think you cannot turn it off mid-game. If I remember correctly I once tried turning it off and then loading a saved game and the game was still showing the promotion icons above units.

The game where I managed to make the graphic glitches and screen freezes go away, proceeded to the point when nukes were flying left and right, and I have had no problems with loading - but there was no Indonesia in that game. However, Indonesia is in my current game and I have seen a couple of their Kris guys (with their special promos displayed above them) - maybe it is just some of their special promos? I will keep an eye on them - Indonesia is doing quite well in this game and they are at war with their neighbours, so there is a good chance that they will produce more Kris swordsmen and get more promos.

Good tip about the Firetuner, @supermerill I will give it a shot if I get problems with loading saves again.

**Comment by ashendashin** [comment]
@Vyyt02 I was wrong about my first statement, actually. Turns out Fireturner was the only reason I was able to load without FlagPromotions in the first place haha.

**Comment by Vyyt02** [comment]
@ashendashin, good to know, I will try with the Firetuner if I run into to the problem with loading saves again.

**Comment by ashendashin** [comment]
@Vyyt02 Disregard that; I was being stupid. Loaded it up with Firetuner again and promotions were still visible and the game froze after some scrolling(must've gotten overexcited the the first time). The game loads up with the mod disabled either way, but remains unstable due to what I hope is the remnants of FP loading up. I'll leave this issue open, in case you run into anything

**Comment by LoneGazebo** [comment]
I'd love to help on this, but I don't have this issue, sorry. I do use a SSD, for what it is worth.

**Comment by ashendashin** [comment]
@LoneGazebo FlagPromotions doesn't have any similar errors for you? This just leaves me more in the dark. Damn. I don't know if it could be some faulty files that require a new download or if it could just be the sort of error that depends on your system. And it would require me to go through entire games to confirm anything... Yeah, I think I'll just go without and hope for the best. Besides, I've had other unstable games and FP is the only mod I've never removed.
