### ISSUE TITLE
Feature Request: Prevent Unit from being used as City-State Gifts.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2910]
Can there be a column in the Unit Table that prevents the unit from being gifted from military city-states at all? "To prevent E&D units from popping out of nowhere for military city-states"

**Comment by LoneGazebo** [comment]
Yes.

**Comment by TechpriestEnginseer** [comment]
What would it be called?

**Comment by LoneGazebo** [comment]
It'll be NoMinorCivGift
