### ISSUE TITLE
Wrong terminology in ReligionText.sql: "Great Work of Literature"

### ISSUE THREAD

**Issue by Maxxim69** [LoneGazebo/Community-Patch-DLL#2911]
_1. Mod version (i.e Date - 4/23):_
12/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
ReligionText.sql uses "Great Work of Literature" instead of "Great Work of Writing" when describing Mosque and Synagogue. These are the only two instances where this error occurs in the mod. The error is only in description and does not affect functionality.

---------------------------

**Comment by TechpriestEnginseer** [comment]
Is there a difference really?
