### ISSUE TITLE
Establishing an embassy with a CS ally grants an unrevealed strategic resource

### ISSUE THREAD

**Issue by Maxxim69** [LoneGazebo/Community-Patch-DLL#2912]
_1. Mod version (i.e Date - 4/23):_
12/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Using a Great Diplomat to establish an embassy with a city state ally grants an unrevealed, undiscovered strategic resource.

_4. Steps to reproduce (optional):_

1. Load the savefile (AutoSave_0231 AD-1605);
2. Move the Great Diplomat one tile east to the plains+fort tile near Brussels and construct an embassy;
3. Receive an "Oil from Brussels" notification;
4. Notice that oil is yet out of reach even for the most advanced civilizations;
5. Scratch head.

---------------------------
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/667398/Logs.zip)

[AutoSave_0231 AD-1605.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/667400/AutoSave_0231.AD-1605.zip)

**Comment by TechpriestEnginseer** [comment]
It's a feature of the Embassy. It reveals potential undiscovered resources.

**Comment by LoneGazebo** [comment]
I'll check the notifications.
