### ISSUE TITLE
Theming bonus retained after Great Work stolen by enemy spy

### ISSUE THREAD

**Issue by Maxxim69** [LoneGazebo/Community-Patch-DLL#2913]
_1. Mod version (i.e Date - 4/23):_
12/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Theming bonus on a Wonder is retained after a Great Work is stolen by an enemy spy.

_4. Steps to reproduce (optional):_
1. Load the savefile (AutoSave_0237 AD-1635);
2. Get the "Great Work Stolen" event;
3. Go to "Your Culture" screen and see the theming bonus on the Parthenon in St. Petersburg retained despite the missing Great Work.

[AutoSave_0237 AD-1635.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/667632/AutoSave_0237.AD-1635.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/667660/Logs.zip)

**Comment by TechpriestEnginseer** [comment]
But if you probably optimize it again or switching around the Great Works, it should properly update no?

**Comment by Maxxim69** [comment]
I had tried and it did update, but I didn't report it because I considered that fact unimportant: the bug's still there, after all. :)

**Comment by TechpriestEnginseer** [comment]
It's just that the tooltip isn't updating, but in the game itself, it should not be updating at all.

**Comment by Edaka** [comment]
@Enginseer What do you mean that in the game it shouldn't be updating at all? If it's just the tooltip, then it's benign, but if the actual yields stay as well - that's bad, although it should be rare.

**Comment by TechpriestEnginseer** [comment]
The tooltip doesn't dynamically update for the sake of performance, but the game itself should update appropriately.
