### ISSUE TITLE
"You are no longer ally with this City-State!"

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2914]
Notification that pops up everytime you have a sphere of influenced city-state's influence below 60.

**Comment by LoneGazebo** [comment]
mm, i'll check.

**Comment by TechpriestEnginseer** [comment]
Also appears as an annoying notification that "Germany might not be allied with this city-states" should Germany not have 60 Influence or higher when having a Sphere of influence.

**Comment by LoneGazebo** [comment]
Yeah.
