### ISSUE TITLE
wrong number of resources with ench +50%

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#2916]
_1. Mod version (i.e Date - 4/23):_
12-13

_2. Mod list (if using Vox Populi only, leave blank):_
WonderRace, InfoAddict, IGE

_3. Error description:_ 
Play for Russia.
Has plots with 2 resources of iron and 2 resources of horses. At least have only 4 iron and 4 horse.

_4. Steps to reproduce (optional):
Looks like if resource was added before religion spreads there, it will not increase(test only for Rus). Cause six turns later, will be added plot with 4 hourses.
Total amount will be 16 horses( 4 * 2+50%=12 + 2 * 2(but here I don't see dat 50%)=4 )

Save game:
[wtf.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/669602/wtf.zip)

**Comment by LoneGazebo** [comment]
Yeah I need to add a religion update check.

**Comment by bigcat88** [comment]
Don't sure but seems have some addition info.
The same is with the autocracy policy +100% quantity.
Different behaviour if we connect resource after we get policy or if it was connected before.
Write for Rus but seems that with all civs with that religion ench.
For example: has 2 resources, it will be 2 + 2 = 4 + 50% = 6
If we adopt autocracy then it will be 12 total.
If we connect resource after adopting policy(aluminium for example) it will be:
(2+2+2)+50% = 9
Something like that.
Maybe its possible to recalculate all resources after adopting that policy or city religion change.
