### ISSUE TITLE
CvUnit::initWithSpecificName and CvUnit::initWithNameOffset

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2919]
these two functions were created by copy and paste (never a good idea) and have diverged a lot. there are probably bugs hiding there.

in fact initWithNameOffset should probably simply choose a name and then call initWithSpecificName to avoid code duplication.

**Comment by LoneGazebo** [comment]
Yeah, I'll look at this at some point soon.
