### ISSUE TITLE
Enact an Open Door Policy doesn't reveal the City-State

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#292]
Despite me getting a notification that I am a friend with it.
Nor it shows up in the list of city-states.

**Comment by LoneGazebo** [comment]
This is by design - you don't get it revealed until you are allied.
G

**Comment by Radost** [comment]
Strange design, what is the friend notification supposed to be?

**Comment by LoneGazebo** [comment]
You get half of the bonus the CS gives out.
G

**Comment by Radost** [comment]
I know what this bonus means, the thing is I got "you are friends with X" notification without the city being revealed and thus didn't get the bonus. It either should reveal the city after enacting an open door or the friends notification shouldn't popup.
