### ISSUE TITLE
Getting tribute from CS after u annihilate it's protector.

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#2921]
_1. Mod version (i.e Date - 4/23):_
12-13

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Protection don't revokes after civilization was captured. I capture Carthage totally, but after that see when getting tribute: "-25 Has Pledge Of Protection"
But column "Pledge to protect" is empty, cause no one protect it now.
Can add save game if need.

**Comment by TechpriestEnginseer** [comment]
What if there was an unmet civilization still pledging its protection?

**Comment by bigcat88** [comment]
There cant be unmet civilization, cause that CS inside's my empire.
CS Quebec or Sofia for example. They both have "-25 resilient due to pledge"
[poprot.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/672123/poprot.zip)
