### ISSUE TITLE
Game CTD's during AI turn

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2922]
_1. Mod version (i.e Date - 4/23):_
 latest patch (12-13) with Iteroi's fix

_2. Mod list (if using Vox Populi only, leave blank):_
  Flagpromotions v.7

_3. Error description:_ 
 Game crashes to desktop at AI turn
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/671922/QuickSave.zip)

**Comment by supermerill** [comment]
Your mod list is VP_eui  with Flagpromotions v.7, or CP +Flagpromotions v.7 ?
Just to be sure.

**Comment by saamohod** [comment]
VP+eui

**Comment by supermerill** [comment]
call stack:

```
mssogg.asi!1a5d9707()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for mssogg.asi]	
 	mssogg.asi!1a5d825e()	Unknown
 	Mss32.dll!09418fef()	Unknown
 	[External Code]	
 	Mss32.dll!09408ead()	Unknown
 	Mss32.dll!09401a03()	Unknown
 	Mss32.dll!09401af9()	Unknown
 	[External Code]	
```
as it's not in the civ5 code, no minidump.

It sounds like a sound problem. I may look to it a bit more if i have time, but it's a complicated one.

**Comment by saamohod** [comment]
Thanks. Seems like it cannot be cured and my game is lost.

**Comment by ilteroi** [comment]
how about turning off the sound? did you try that?

**Comment by saamohod** [comment]
This may be a stupid question, but what do you mean by turning off sound? Do I turn it of in game, or do I disable sound card, or...?

**Comment by supermerill** [comment]
A sound may be played during ai turn like "wonder finish", i think.
