### ISSUE TITLE
No Bushido promo in certain conditions

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2925]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Get a level 3-4+ Swordsman. Research Steel. Upgrade him to Samurai. Once he's upgraded, build a Dojo (after promoting Sword to Samurai). He won't get a Dojo promotion. Not sure if the same occurs to Horsemen-Knights too.

Even after all cities have Dojo, there's 2 Samurai's now with no Dojo promotion.

**Comment by TechpriestEnginseer** [comment]
Most likely because a unit is deleted when they are upgraded.

**Comment by Enrico-Swagolo** [comment]
Worth mentioning those Swordmurai are also from Kyoto (which has Alhambra) but do not have Drill. Yeah, it seems units lose track of their origin city after "dying". I also have had it happen previously to a Horseman upgraded to Knight before Alhambra was built. I think you're right on why that happens because it makes sense.
