### ISSUE TITLE
UnitFreePromotion

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2927]
I'm unsure when did this happened, but UnitFreePromotion column in Improvements now applies a free promotion only if the unit belongs to the owner of the improvement which was sort of problematic on a pontoon bridge mod I was using which gave penalties to those on the pontoon bridge.

**Comment by LoneGazebo** [comment]
I did this for JFD - unfortunately there's no easy way to 'fix' this without some more code. I'll look at it later.

**Comment by LoneGazebo** [comment]
Going to add a IsOwnerOnly element to improvements - it'll default to true, so you'll have to make it false for your pontoon.
