### ISSUE TITLE
What does FoundsReligion do?

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#2928]
In the Buildings table there's a (I assume) vanilla column called FoundsReligion. I thought that it was supposed to make a building act like a trigger to founding a religion. In reality, building a building with this set to 1 doesn't trigger religion founding. Is it a broken vanilla function or have I misunderstood its purpose?

**Comment by TechpriestEnginseer** [comment]
It was probably broken from the start since vanilla didn't have a religion.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer is correct. It goes nowhere in the code.
