### ISSUE TITLE
City sacked during trade deal

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#2929]
1. Mod version (i.e Date - 4/23):
12/5

2. Mod list (if using Vox Populi only, leave blank):
vox populi
info addict 27
really advanced setup

3. Error description:
Obtaining a city through a trade deal destroys most of the city's infrastructure as if you had conquered it.

Supporting information:

Trade Austria for St.Polten

[bug.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/676803/bug.gz)

**Comment by TechpriestEnginseer** [comment]
This was rather intentional to prohibits multiplayer players to trade cities away to "teammates" to give them an advantage.

**Comment by jimmymcperson** [comment]
why can't we have nice things? :(
