### ISSUE TITLE
Can build roads and railroads on AI territory with Open Border agreement

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#293]

**Comment by LoneGazebo** [comment]
That's normal, IIRC.

**Comment by Radost** [comment]
Building the whole AI territory with roads is normal?

**Comment by LoneGazebo** [comment]
The ‘issues' tab is for issues with things that the CP/CBP has introduced. Your problem is something that exists in the base game. This is, therefore, a feature request. As such, I ask that you bring this up in the forum.

G
