### ISSUE TITLE
Intrigue Showed should be limited to recent discoveries.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2930]
Or else you get a long history that you may never read.
![image](https://cloud.githubusercontent.com/assets/13937047/21556882/9e5173bc-cdd9-11e6-8ebe-e2fd1f998c98.png)

**Comment by LoneGazebo** [comment]
It already checks only for stuff learned about in last 10 turns.

**Comment by LoneGazebo** [comment]
I'll tighten a bit.
