### ISSUE TITLE
Random generator overflow in fefe branch

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#2935]
In the commit 248f53d0f7255cf5b34049be4da87671440d6e33, you changed the random generator but now it can overflow to 0xFFFFFFFF in big map in the late game.

i've added:
```
--- a/CvGameCoreDLL_Expansion2/CvGame.cpp
+++ b/CvGameCoreDLL_Expansion2/CvGame.cpp
@@ -10025,6 +10025,10 @@ int CvGame::getAsyncRandNum(int iNum, const char* pszLog)
 int CvGame::getSmallFakeRandNum(int iNum, const CvPlot& input)
 {
 	int iFake = input.getX()*17 + input.getY()*23 + getGameTurn()*abs(input.getX()-input.getY()) + getGameTurn();
+
+	// If iFake² > 0xFFFFFFFF -> (iFake*iFake) % iNum = -1 (0xFFFFFFFF), so this line prevent this bug in big map at the end game 
+	if (iFake > 16383)
+		iFake = getGameTurn() + input.getX() * 3 + input.getY() * 11;
 	
 	if (iNum>0)
 		return (iFake*iFake) % iNum; 
-- 
```
To be sure to never have the problem again, but it's maybe better to revert to the previous version.

**Comment by ilteroi** [comment]
overflow shouldn't really matter, the only problem is iFake^2 turning negative. so using the absolute value would fix it.

**Comment by supermerill** [comment]
You can, but it's even less random (as the overflow is happening more and more as getGameTurn() go high)

**Comment by ilteroi** [comment]
integer overflow for signed types in undefined in the C standard, but with the VC2008 compiler the result of an overflowing multiplication is not always -1.

the square is just a small trick to include an element of non-linearity.

**Comment by supermerill** [comment]
Thank you for the explanation.
For the overflow/ correction, i trust you on this.
