### ISSUE TITLE
JumpToNearestValidPlot CDT

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#2936]
Version affected: latest fefe branch

Problem: when an aircraft carrier with ariplanes are on top of a civilan boat, it's considered as 'invalid' by RepositionInvalidUnits(). So it will Jump it to the same tile and this cause a CDT.

to repair it, i have added
```
+++ b/CvGameCoreDLL_Expansion2/CvUnit.cpp
@@ -5642,6 +5642,13 @@ bool CvUnit::jumpToNearestValidPlot()
 		}
 	}
 
+	//dirty fix for a cdt when we want to jump at the same plot with cargo
+	if (pBestPlot == plot())
+	{
+		CUSTOMLOG("tried to jumpToNearestValidPlot but it's the same plot!!");
+		return true;
+	}
+
 	if(GC.getLogging() && GC.getAILogging())
 	{
 		CvString strLogString;
-- 
```

but it will be better to repair getMaxFriendlyUnitsOfType()

**Comment by ilteroi** [comment]
you got me confused here ...

1. i don't know any function called RepositionInvalidUnits
2. what is wrong with getMaxFriendlyUnitsOfType()?
3. do the cargo units make any difference?
4. if the current plot is invalid, how come JumpToNearestValidPlot returns exactly that one?

**Comment by supermerill** [comment]
1) void CvPlayer::RespositionInvalidUnits() line 11149 of CvPlayer.cpp the real problem occur at line 11183.
2) if(pPlot->getMaxFriendlyUnitsOfType(pLoopUnit) > pPlot->getUnitLimit()) return true but jumpToNearestValidPlot() return the same plot where the unit is standing.
3) It may be a factor of why getMaxFriendlyUnitsOfType and jumpToNearestValidPlot can't agree with each other.
4) That's the problem. When the embark plane has to execute SetPosition() (after setXY and inside the setXY of the carrier), it crash the game engine.

My fix is very simple: if you have to move over yourself, do nothing instead. It avoid any problem (it's a reproducible crash, but as you have some difficulties to load saves...).

**Comment by supermerill** [comment]
The cdt occur in the civ5.exe, from a call in Unit.SetPosition(). For me, it was when the position passed in parameter is the same as the previous one for this unit and this unit is an airplane in a carrier.
SetPosition may create a cdt for any unit that want to jump from his position to the same place, i didn't test it.

My fix work because it avoid to call setXY() (which call  setPosition) when the unit didn't change his position. It's a very safe bugfix, as a similar problem may occur with an other unit configuration.

The root cause is in getMaxFriendlyUnitsOfType() but i didn't have the time to understand it.
