### ISSUE TITLE
Wrong leader scene on DOW

### ISSUE THREAD

**Issue by lucperrin** [LoneGazebo/Community-Patch-DLL#2939]
_1. Mod version (i.e Date - 4/23):_ 12/13

_2. Mod list (if using Vox Populi only, leave blank):_ Just VP

_3. Error description:_ Wrong leader scene when Rome declares war on turn 274 against me for being a warmonger.. shows that I am talking to myself.  Attaching last autosave before it happens.  

_4. Steps to reproduce (optional):_ Be a warmonger, get a DOW

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/679819/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[AutoSave_0270 AD-1250.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/679818/AutoSave_0270.AD-1250.zip)
3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://cloud.githubusercontent.com/assets/380143/21579109/7971206c-cf53-11e6-996a-02c48c1ad7f1.png)

**Comment by MoiMagnus** [comment]
Cela m'est déjà arrivé aussi, une ou deux fois cet été.
Par contre je n'ai pas de sauvegarde.

**Comment by TechpriestEnginseer** [comment]
I knew it I wasn't dreaming when I saw this weird bug.
