### ISSUE TITLE
Crash to desktop on same turn (even when loading earlier saves

### ISSUE THREAD

**Issue by serrath** [LoneGazebo/Community-Patch-DLL#2941]
_1. Mod version (i.e Date - 4/23):_
Late december 2015 (very recent version)

_2. Mod list (if using Vox Populi only, leave blank):_
Community balance patch + yet not another earth maps pack v.24 (with some configuration files changed to make it work with vox populi as per forums instruction: https://forums.civfanatics.com/threads/howto-play-yet-not-another-earth-map-pack-with-cpp.542560/ )

_3. Error description:_ 
On a giant earth map with 22 civs and on marathon speed, crash to desktop on turn 785
Crash occurs when processing Ethiopia's turn; all other civs process their turn normally but Ethiopia's turn takes several minutes to process during which time worker animation speed slows down and then speeds up before freezing and dropping me to desktop
I've tried loading an earlier save and then playing to turn 785; loading 3 turns ago and 21 turns ago causes same issue; turn 785, crashes during Ethiopia's turn
I thought it might be something Ethiopia is doing on this turn so I loaded a save 21 turns ago and declared war on Ethiopia in the hope that it would do different things on this turn but it causes the same problem
I'd like to find a way to get past this problem if possible; I've been playing this same game for a number of hours and it'd be frustrating not to be able to finish it

_4. Steps to reproduce (optional):_
Reproducing is easy; no matter what save I load, it crashes on the same turn at the same point in processing the AI's turns. I've attached a save game that was saved as Ethiopia's turn is processing so loading this save will result in the game thinking for several minutes and then crashing. However, because the game is using both vox populi and YNAEM with some configuration files changed, not sure if it's easily loadable

Anyone who give a suggestion that would allow me to get past this turn, I would be very grateful 

[Logs and save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/680462/Logs.and.save.zip)

**Comment by supermerill** [comment]
Can't load.
What is the exact version of VP you use? full VP with EUI? no other mods?

**Comment by serrath** [comment]
Full VP with EUI

Other mods include the yet not another giant map v.24 mod. Normally this mod is incompatible with VP however you can edit two configuration files in the earth map to make it work. Instructions to do so are found in this thread:

https://forums.civfanatics.com/threads/howto-play-yet-not-another-earth-map-pack-with-cpp.542560/

And the changed configuration files are found in this post:

[URL="https://forums.civfanatics.com/threads/howto-play-yet-not-another-earth-map-pack-with-cpp.542560/page-5#post-14518835"][HowTo] Play "Yet (not) Another Earth Map Pack" with CPP[/URL]

I was hoping my problem wasn't caused by an incompatibility between these two mods; the game played fine for more than 700 turns without a hint of a problem. In general, I just really like sprawling, meandering giant earth games on marathon that take me a long time to finish. This is the first time I've tried these two mods in combination since purchasing a new computer with the latest hardware.

Thanks for replying. If there is any other information I can provide, let me know; I'm very eager to try to get this save game working as I have a lot  of investment into this game that I have on the go.

**Comment by supermerill** [comment]
It's the 12-14 version hotfixed by gazebo or the 12-14 version with modifications from iteroi?

**Comment by serrath** [comment]
I want to answer your question but I'm not sure what you're asking. I downloaded VP from the civfanatics thread "community patch - how to install"; I have the version that precedes the 1.12.14 (I thought I had the Dec version but it says i downloaded it on Nov 16) so I have whatever version is before the Dec 13 1.12.14 version. I used the automatic installer within the thread contained in the following link to a forum post:

https://forums.civfanatics.com/threads/community-patch-how-to-install.528034/

Does that answer your question?

Do you think it could be a compatibility problem with the mods? I would have thought, if that was the case, I would have had a crash much sooner than this late in the game

**Comment by supermerill** [comment]
It's probably just a late-game bug. It may have been fixed in the later version. I will try again to load your save this night.

**Comment by serrath** [comment]
Thanks, it looks like the problem has been solved (well, sort of). I wasn't aware of the "in game editor" mod but someone pointed me towards it and I gave it a try. Deleting Ethiopia caused the turn to progress to the next turn; obviously they're the culprit so I'm going to try selectively deleting things of theirs to see if I can fix whatever was wrong.

thanks for looking into this problem, I appreciate it!

**Comment by serrath** [comment]
As a followup, I spent a long time with the in-game editor deleting things in a systematic way from Ethiopia to try to get the turn to progress. I thought it was Ethiopia's units but that didn't change anything however they had 9 cities (out of their 20 or so) that all had broadcast towers being built on the next turn. I deleted all of their cities that were finishing their construction on the next turn and that fixed the problem. I then deleted 4 of their cities and this also fixed the problem; I would have tried with 3 or less but I was sick of trying different things.

Don't know what the bug actually was but deleting 4 cities that were 1 turn to completing broadcast towers resolved the problem; i've since advanced 10 more turns with no signs of further difficulties

**Comment by Bloodrocution** [comment]
@serrath If you want to try to preserve the integrity of your game without resorting to deleting the city entirely, I suggest to try using the IGE to just put broadcast towers in all the cities that are going to finish building them on the next turn. To do this, just click on the city edit button tab of the IGE (second one from the left I believe; the skyscraper icons), click on each city and find the Broadcast Tower in the list of buildings segregated by tech era and then highlight it.

If it works, that will be far less drastic of a workaround than straight up deleting the cities. Best of luck. I can imagine how devastating it must be to encounter such a severe bug so late in your game.
