### ISSUE TITLE
Various requests for text corrections

### ISSUE THREAD

**Issue by ErikSteiner** [LoneGazebo/Community-Patch-DLL#2944]
_1. Mod version (i.e Date - 4/23):_
1.12.14

_2. Error description:_ 
(1) Community Patch\Core Files\Text\CoreText_en_US.xml

- Navigate to `<Row Tag="TXT_KEY_NOTIFICATION_QUEST_STEAL_FROM">`
The text seems to me like there is a word missing (maybe 'in'?).
I don't know where this thing is related to {@1_Civ}.
`If you complete [COLOR_POSITIVE_TEXT]{2_Num}[ENDCOLOR] Espionage actions _in_ {@1_Civ} (Advanced Actions or Technology Theft),`

I am going to edit the issue post, if I find more.

**Comment by TechpriestEnginseer** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/pull/2923

**Comment by ErikSteiner** [comment]
I am not sure if this is wrong, I do not want to look petty.
Navigate to: (3) CSD for CBP\Buildings\BuildingText.xml
`<Row Tag="TXT_KEY_BUILDING_FINANCE_CENTER_HELP">`
`Receive two votes for every [COLOR_POSITIVE_TEXT]Declarations of Friendship[ENDCOLOR]`
In my point of view, I think that the declaration must be singular, because the word every is used. Maybe I am wrong and one can use both..

**Comment by TechpriestEnginseer** [comment]
I think it's supposed to be Receive a vote for every 2 Declarations of Friendship but I'm unsure.

**Comment by ErikSteiner** [comment]
Navigate to:
(2) Community Balance Overhaul\Balance Changes\Text\en_US\UIText.sql
```
SELECT '[ICON_BULLET] [COLOR_NEGATIVE_TEXT]{1_NUM}[ENDCOLOR] due to due to [ICON_HAPPINESS_3] Unhappiness.', 'TXT_KEY_TP_CULTURE_LOST_FROM_UNHAPPINESS'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_NATIONAL_HAPPINESS' AND Value= 1 );
```
One 'due to' too much..

**Comment by ErikSteiner** [comment]
Navigate to:
(1) Community Patch\Core Files\Text\CoreText_en_US.xml
```
		<Row Tag="TXT_KEY_NOTIFICATION_COUP_FAILED_B_S">
			<Text>Your coup has failed, either because your spy has died or the is no longer a valid target. As such, the quest from {@1_Civname} was withdrawn.</Text>
		</Row>
```
It there a City-tag missing, between the and is?

**Comment by LoneGazebo** [comment]
fixed
