### ISSUE TITLE
iTurnQuestGiven

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2948]
SetMinorCivActiveQuestForPlayer(eQuestPlayer, eQuestType, iTurnQuestGiven, eCallingPlayer) seems to be inconsistent with its iTurnQuestGiven depending on the gamespeed and map size. Is there a formula?

**Comment by LoneGazebo** [comment]
No, its just a passed through value. nothing special.

**Comment by TechpriestEnginseer** [comment]
How come a barbarian horde seems to scale in turns then?

**Comment by LoneGazebo** [comment]
Hmm, that's odd. I'll look.

**Comment by LoneGazebo** [comment]
Code for horde events:

```
`#if defined(MOD_BALANCE_CORE)
	CvSmallAwardInfo* pkSmallAwardInfo = GC.getSmallAwardInfo((SmallAwardTypes)m_eType);
	if(pkSmallAwardInfo)
	{
		if(pkSmallAwardInfo->GetDuration() > 0)
		{
			int iDuration = pkSmallAwardInfo->GetDuration();
			// Modify for Game Speed
			if(m_eType == MINOR_CIV_QUEST_HORDE || m_eType == MINOR_CIV_QUEST_REBELLION)
			{
				return (m_iStartTurn + iDuration);
			}
			iDuration *= GC.getGame().getGameSpeedInfo().getGreatPeoplePercent();
			iDuration /= 100;
			return (m_iStartTurn + iDuration);
		}
	}	
#endif`
```

**Comment by TechpriestEnginseer** [comment]
what is m_iStartTurn and iDuration in a nutshell when referring to standard and epic on a comparison scale?

**Comment by LoneGazebo** [comment]
Start turn is whatever you input via lua. iDuration is the duration of the quest in the XML (look at the database for the duration info).

**Comment by TechpriestEnginseer** [comment]
That's weird putting in 0 for iTurnQuestGiven this time didn't crash the game! Oh well all is resolved!

**Comment by TechpriestEnginseer** [comment]
Future documentation for any modder left.. eCallingPlayer cannot be NO_PLAYER for barbarian hordes and rebellions or else no barbarians will spawn at all.

**Comment by LoneGazebo** [comment]
Yeah, def need a CallingPlayer :)

G
