### ISSUE TITLE
Bombers have the wrong logistic promotion.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2949]
They don't have Ranged Combat Strength, so logistic doesn't affect them negatively. I assume this may be the same for fighters.

**Comment by LoneGazebo** [comment]
They do have RCS, technically speaking. Or at least they used to.

**Comment by TechpriestEnginseer** [comment]
Well, when calculating combat odds it seems to show no difference.

**Comment by MoiMagnus** [comment]
Does the result of the combat is coherent with combat odds ? It may just be a bug in the combat preview
