### ISSUE TITLE
Embassy Inconsistency

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2950]
I can steal someone's embassy with a Great General citadel and place my own embassy inside the city-state. 
If I launched a nuke, an embassy can be pillaged as well.

The easiest solution for the first example could possibly be allowing Great Diplomats to build an embassy inside the city-state's tile itself.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer I considered latter, however the player would have a hard time knowing why they couldn't build an embassy if it wasn't a tile on the map. Nevertheless the other element is by design, and so is the pillaging from nukes.

**Comment by TechpriestEnginseer** [comment]
Well yeah on the city-state's tile.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer It isn't visible on the CS tile - leaving it to a tooltip only would be quite tedious.
