### ISSUE TITLE
Global - City Bombard Range

### ISSUE THREAD

**Issue by Erocco** [LoneGazebo/Community-Patch-DLL#2955]
_1. Mod version (i.e Date - 4/23):_
December 13th (1.12.14)​

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
City bombard range mod doesn't work as the original owner's description below:

"The bombard range of cities is a function of the tech known by the owning player
Agriculture: Range 1, no indirect fire (throwing rocks over the wall)
Mathematics: Range 2, no indirect fire (using catapults to hurl boulders)
Gunpowder: Range 2, indirect fire (using mortars to lob projectiles)
Dynamite: Range 3, indirect fire (artillery firing shells)"

Instead cities can bombard with range of 2 from game start.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@Erocco 

That particular mod is enabled by the Community Balance Overhaul, not the Community Patch - you'll need the VMC modmod for that. If using the CBO, the locations of those range upgrades are slightly different (as our tech tree is different).

**Comment by Erocco** [comment]
In other words the CP mod should not mess with the City Bombard mod. Well I am using only the Community Patch and as soon as I uninstall the CP the City Bombard mod works as it supposed to if I install the CP the City Bombard mod doesn't work as it supposed to anymore.

I am confused.

**Comment by supermerill** [comment]
@Erocco you use this mod http://www.picknmixmods.com/mods/CivV/Global/City%20Bombard%20Range.html?

Don't install the http://www.picknmixmods.com/mods/CivV/DLL/Various%20Mod%20Components.html, it's already inside the cp.

**Comment by Erocco** [comment]
Gazebo, I don't have VariousModComponents mod installed as I know it's included in CP and I am using WHoward's City Bombard Range mod. I also deleted the City Bombard Range mod and re-downloaded just to make sure I have a fresh copy but still have the same problem. Something in CP must be blocking the City Bombard mod.

**Comment by LoneGazebo** [comment]
@Erocco there shouldn't be any issue - my code is the same in the CP for that as the VMC. Check your database log for errors.
