### ISSUE TITLE
A settler can't find an escort and a warrior is sitting in the capital to explore without moving

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#2959]
_1. Mod version (i.e Date - 4/23):_ merge between latest gazebo and iteroi on 17/01/10

2_ mod list: only the community patch (with a special starting map)

_3. Error description:_ 
my settler doesn't move because it wait an escort. An archer is sitting next to it but an acher isn't powerful enough to escort a settler. A warrior is sitting next to it in the capital but it can't be grabbed because he has "pLoopUnit->AI_getUnitAIType() == UNITAI_EXPLORE" at true.
I think the AiType field of the unit isn't properly reset.
It seems GetNumUnitsWithUnitAI(UNITAI_EXPLORE) also count it.
This warrior doesn't move.
There are only one operation in the player map: the settling one.

I tried to find where the problem is, but i don't even know where the warrior is assigned to a city. Can you give me a clue?

note: the city doesn't want to build an escort.

_4. Steps to reproduce (optional):_
logs: [babylon_logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/697500/babylon_logs.zip)

my save: 
https://mega.nz/#!Q0gRmTya!ZlUn7CeeyWCoJCsLvkYQDa3ZBorljGmp0ofH17iHT8k
Babylon is in NZ, the warrior in question is at 114,7

**Comment by ilteroi** [comment]
once again i can't load the save, so this is kind of hard to diagnose.

you're saying "my settler" - but surely this is autoplay right?

so is the problem that the scout is not moving? did you set it to autoexplore? how did it end up in the city? was that before autoplay started or after? i'm not sure if this is a real problem for "normal" players.

warrior assignment to city would be PlotGarrisonMoves(). for some reason this exists twice, once in tactical AI, once in homeland AI. scouting is part of homeland AI, so the tactical garrison can inhibit the scouting because it's called first (and the code doesn't check whether the garrison is a scout).

i've added some checks regarding garrisons and scouts - it's pushed - can you see if this solves the issue?

**Comment by supermerill** [comment]
yeah, it's the babylonian settler

It's a warrior. It stay into the city, but if i call AI_getUnitAIType() in the debugger on it, it return UNITAI_EXPLORE.

Autoplay since turn 1.

I will check, thank you.

**Comment by supermerill** [comment]
Its seems it's not enough.
Some more logs (fromthe latest commit):
```
CvPlayer.cpp[10542]: CvPlayer::doTurn - Theodora has a city at 115 6
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Warrior at 96 6, duty: 10
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Warrior at 116 22, duty: 10
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Warrior at 115 6, duty: 6
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Warrior at 114 6, duty: 3
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Scout at 87 27, duty: 10
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Worker at 113 7, duty: 2
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Settler at 115 6, duty: 1
CvAIOperation.cpp[3992]: OperationalAIHelpers::IsUnitSuitableForRecruitment - check unit Warrior @96:6 : mission 10
CvAIOperation.cpp[3992]: OperationalAIHelpers::IsUnitSuitableForRecruitment - check unit Warrior @116:22 : mission 10
CvAIOperation.cpp[3992]: OperationalAIHelpers::IsUnitSuitableForRecruitment - check unit Warrior @115:6 : mission 10
CvAIOperation.cpp[3992]: OperationalAIHelpers::IsUnitSuitableForRecruitment - check unit Warrior @114:6 : mission 3

CvPlayer.cpp[10542]: CvPlayer::doTurn - Theodora has a city at 115 6
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Warrior at 97 7, duty: 10
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Warrior at 117 22, duty: 10
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Warrior at 115 6, duty: 6
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Warrior at 114 6, duty: 3
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Scout at 88 28, duty: 10
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Worker at 114 6, duty: 2
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Settler at 114 7, duty: 1

CvPlayer.cpp[10542]: CvPlayer::doTurn - Theodora has a city at 115 6
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Warrior at 99 7, duty: 10
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Warrior at 118 23, duty: 10
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Warrior at 115 6, duty: 6
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Warrior at 113 7, duty: 3
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Scout at 89 29, duty: 10
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Worker at 113 5, duty: 2
CvPlayer.cpp[10547]: CvPlayer::doTurn - Theodora has a Settler at 113 7, duty: 1
```
seems like the UnitAIType is changed somehow in the turn... but it go back to the good one after that.

code to replicate on any game (just wait a settler):
```
	// CvPlayer line 10539
	for (int i = 0; i < m_cities.GetCount(); i++){
		CvCityAI *city = m_cities.GetAt(i);
		CUSTOMLOG("%s has a city at %i %i", getName(), city->getX(), city->getY());
	}
	for (int i = 0; i < m_units.GetCount();i++){
		CvUnit *unit = m_units.GetAt(i);
		CUSTOMLOG("%s has a %s at %i %i, duty: %i", getName(), unit->getName().c_str(), unit->getX(), unit->getY(),
			unit->AI_getUnitAIType());
	}
```

```
// CvAIOperation line 3992
CUSTOMLOG("check unit %s @%i:%i : mission %i", pLoopUnit->getName().c_str(), pLoopUnit->getX(), pLoopUnit->getY(), pLoopUnit->AI_getUnitAIType());
```

Maybe it's normal. But for me, it's strange.
I will continue to look at it.

note: i can't load my previous save either, as the quicksaves are broken if they are made during an "autoplay" (launched from firetuner). Do I create a issue for that? (it's because it try to load the observer team and crash at it because there are none)

**Comment by ilteroi** [comment]
usually i can load (my own) autoplay autosaves, so something is strange here. 

regarding the back and forth, that should be solved by my latest change? garrison recruitment now ignores scouts ... also the line number you're giving me are a bit off, so i wonder what version you are using.

the main problem is the conflict between scouting and escorting. that is hard to handle. anyway once a unit is part of an army (escort + settler) it should be off limits for scouting.

**Comment by supermerill** [comment]
great!
Sorry for the line numbers, i forgot to revert to your branch (i'm using a merge from your branch, the master and some specific modifications for testing).
