### ISSUE TITLE
"Hooks" for Advanced Spy Options for Wonders/Buildings

### ISSUE THREAD

**Issue by Damirith** [LoneGazebo/Community-Patch-DLL#296]
I would like to make some wonders/buildings that go along with the Advanced Spy Options, some things I wouldn't mind playing around with include:

Stealing Science
1)	How to prevent all science from being stolen in the city the wonder is built in
2)	How to reduce the amount of science being stolen in all cities by 50%

Stealing Gold
1)	How to prevent all gold from being stolen in the city the wonder is built in
2)	How to reduce the amount of gold being stolen in all cities by 50%

Assassination
1)	How to reduce the chance for a GP to be assassinated in the city the wonder is built in
2)	How to reduce the chance for a GP to be assassinated in all cities by 50%

Production – Wonders/Buildings/Units
1)	How to reduce the amount of production lost towards Wonders/Buildings/Units in the city the wonder is built in
2)	How to reduce the amount of production lost towards Wonders/Buildings/Units in all cities by 50%

I also think having "hooks" to improve your spies in these areas could be cool. Like having a building that lets all of your spies steal more science than they normally would and another one that makes them better at Assassinating, etc. This way you can specialize your spies to some degree. Or simply allowing some "4th tier rank" could also work, they would just be better at everything.

**Comment by LoneGazebo** [comment]
This will take me a bit, but consider it 'on the list.'
G
