### ISSUE TITLE
AI too aggressive with barbie camps

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2963]
_1. Mod version (i.e Date - 4/23):_
12th januar y 
Current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm playing as Isabella. I just saw Theodora suicide her Scout by attacking a fortified barb camp  through river 3 turns in a row.

**Comment by bigcat88** [comment]
Yeah, see that for AI. Suicide not only scout, but warriors too )
Just attack and attack.

**Comment by Enrico-Swagolo** [comment]
I've also had Theodora attack my city (very close to her cities) with a Spearman while I was sieging her stuff with Archers and Horses.

**Comment by LoneGazebo** [comment]
@ilteroi did you give them all liquid courage?

**Comment by ilteroi** [comment]
nope. didn't touch anything related to combat. but i'll check

**Comment by Enrico-Swagolo** [comment]
In contrast, Barbies are now very passive. They refuse to attack forested warriors. They're just like they were a few versions ago.

Right now it's like... Regular civs behave like barbarians unit-wise while barbarians attempt to keep their units alive and refuse to attack against bad odds.

**Comment by ilteroi** [comment]
uh. turns out the AI self-preservation instinct has been broken since november 10th.

**Comment by ilteroi** [comment]
it's fixed but i don't know how it's possible that nobody noticed this before.

**Comment by Enrico-Swagolo** [comment]
I did notice but before this version, it just wasn't that visible. I never saw them outright pummel units forever and die like this. I thought them being so wacky with attacking cities was just something unfixable, and they rarely fought to death, usually retreating before dying. I think I've reported that before? Or something similar.

Anyway, great it's fixed. Canst thou link the corrected AI file for replacement?

**Comment by ilteroi** [comment]
yeah they would retreat after being attacked, or in high danger, but barbarians usually don't cause high danger levels ... can't reproduce barbarian passivity btw

anyway, try this here [CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/705499/CvGameCore_Expansion2.zip) and please give feedback

**Comment by Enrico-Swagolo** [comment]
Barbarians aren't that passive, it's just that sometimes with Forest + Spear (or even better troops) they refuse to attack. Once they didn't want to attack over a riverand moved around to attack without the penalty. Pretty smart and IMHO barbies are okay as they are.

I will try playing with the mod on and give you feedback.

**Comment by Enrico-Swagolo** [comment]
Already noticed a change - before the file, the AI kept pummeling a barbarian camp despite me having declared war on them (as a test) and having an unit near, allowing me to steal Culture from both the units. Now, when I've declared war on a Warrior attacking a Brute camp, the Warrior moved away from my scout, probably having recognised it'd endanger him. Seems fixed, but I will play more to tell for sure.

**Comment by ilteroi** [comment]
seems to be solved
