### ISSUE TITLE
Weird delayed notification bug

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2964]
_1. Mod version (i.e Date - 4/23):_
12 jan

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I've noticed that the notifications that should arrive when your turn startssometimes do not happen instantly and are delayed, same with their sound. Only after X/XX seconds after your turn starts do the notifications appear, and before they do - the turn is... sort of yours? SOME of the notifications appear, but some, typically those related to cities, don't. You also can't click some things, like the pick-your-policy purple notification arrived and was on the right, but clicking it didn't make the policy menu appear. Only a few seconds later, when city notifications related to citizens birth arrived, did it do anything.

Note - it was 300 turns in the game. And I've reloaded a few times to correct misclicks. That could have been a partial cause, but I am interested if others have seen something like that.

**Comment by Enrico-Swagolo** [comment]
It's been happening in a few games, sometimes starting from 200~ turns, sometimes a bit later.

**Comment by LoneGazebo** [comment]
Sounds like an EUI quirk.

**Comment by Enrico-Swagolo** [comment]
Maybe, though it wasn't happening before this version. Were there some changes implemented to EUI and/or interface/notifications between 12 Jan and December version?

**Comment by bigcat88** [comment]
This happens when u got units from vassals(when 2 units are in one city). I cant click in right icons, all becomes to work when I move one of those units.

**Comment by bigcat88** [comment]
Also "choose production" button in right corner blocks when unit conscripted by authority policy.
Don't remember such behaviour in previous patch.
When I manually choose the city, enter it and choose production, all becomes fine, right corner button starts to work.
