### ISSUE TITLE
Events Frequency

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2965]
I'm noticing that city events are popping up more often than regular events (3 city events than 1 regular event in a case) and this is only an OCC game.

**Comment by LoneGazebo** [comment]
They use nigh identical code.

**Comment by TechpriestEnginseer** [comment]
Could it be possible that lua-triggered events are reducing the player event frequency?

**Comment by LoneGazebo** [comment]
They can if you don't set the default cool down value to something other than default.

**Comment by TechpriestEnginseer** [comment]
Of course that makes so much sense! Thanks!

**Comment by TechpriestEnginseer** [comment]
Actually do EventDuration event matter as well? What's the requirement of a dummy event according to the frequency of event formula?

**Comment by LoneGazebo** [comment]
Duration simply affects the length of non permanent effects.

**Comment by TechpriestEnginseer** [comment]
Hmm, just gotta hope the dummy events for City-State Alliance doesn't break the frequency then...
