### ISSUE TITLE
43 Civ dll issues. No city states and almost no resources. 

### ISSUE THREAD

**Issue by Rottw** [LoneGazebo/Community-Patch-DLL#2966]
_1. Mod version (i.e Date - 4/23):_

1.12.1 with 43 Civ dll

_2. Mod list (if using Vox Populi only, leave blank):_

1) VP + 43 Civ dll 
2)IGE 

_3. Error description:_ 

When starting a new game using advanced setup the following happens;

• Texture for marsh I replaced with the texture for tundra.
• no city states at all! 

• minimal resources placement, even if abundant is selected. 

BUT:

1.) if I left all civs at random, including mine the game starts up and the above issues DOES NOT HAPPEN and the map looks fine and there are CS. 

2.) if I chose a Civ i.e. France the above issues occur.

_4. Steps to reproduce (optional):_

Reinstall vp, clear cache and all. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Rottw** [comment]
Seems to work correctly when More Luxuries are disabled ?!

**Comment by LoneGazebo** [comment]
[(5) More Luxuries - 43 Civs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/717768/5.More.Luxuries.-.43.Civs.zip)

@Rottw test this for me?

**Comment by LoneGazebo** [comment]
(replace more luxuries in your mods folder)

**Comment by Rottw** [comment]
I renamed the AssignStartingplots.lua in the More Luxuries folder and it works. 
I'll try your solution as well. Thanks!

**Comment by LoneGazebo** [comment]
Use the new auto-installer.

**Comment by Rottw** [comment]
Thanks! I'll do that!
