### ISSUE TITLE
Corporations and monopolies window stuck on new game

### ISSUE THREAD

**Issue by deadman96385** [LoneGazebo/Community-Patch-DLL#2968]
_1. Mod version (i.e Date - 4/23):_
1/12

_2. Mod list (if using Vox Populi only, leave blank):_
I have only added: mpmpm

_3. Error description:_ 
Coporations & Monopolies screen at the beginning of a new games is not closable i have cleared my cache after deleting the other mods that i didn't have enabled as per the other issue. It did not fix it.

If i select any of the tabs in the menu it acts normally but this is logged in the lua console

Runtime Error: C:\Users\name\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Community Balance Overhaul\Modular Elements\Corporations\CorporationsOverview.lua:481: attempt to call field 'GetGreatestPlayerResourceMonopoly' (a nil value)

 Runtime Error: C:\Users\name\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Community Balance Overhaul\Modular Elements\Corporations\CorporationsOverview.lua:224: attempt to call method 'IsCorporationsEnabled' (a nil value)

 Runtime Error: C:\Users\name\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Community Balance Overhaul\Modular Elements\Corporations\CorporationsOverview.lua:257: attempt to call method 'GetCorporation' (a nil value)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Means you have a bad install. Reinstall and follow install instructions.
