### ISSUE TITLE
#2914

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2969]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/2914

Same thing Sphere of Influences triggers a lot of false positives in MinorAlliesChanged. Not to mention trespassing into the City-State's sphere of influence(despite that you are the ally) also grants you the annoying notification as well. (You also gets blank notifications)
````
 TheBalanceDemandsIt: 29 (iMinor)
 TheBalanceDemandsIt: 0 (iMajor)
 TheBalanceDemandsIt: false (bIsAlly, is supposed to be true with a sphere of influence!)
 TheBalanceDemandsIt: -60 (iOldFriendship)
 TheBalanceDemandsIt: -59 (iNewFriendship)
---Repeat?
 TheBalanceDemandsIt: 29 (iMinor)
 TheBalanceDemandsIt: 0 (iMajor)
 TheBalanceDemandsIt: false (bIsAlly, is supposed to be true with a sphere of influence!)
 TheBalanceDemandsIt: -59 (iOldFriendship)
 TheBalanceDemandsIt: -60 (iNewFriendship)
````
![image](https://cloud.githubusercontent.com/assets/13937047/21959424/72439454-da7b-11e6-8324-4ee83be30932.png)

**Comment by LoneGazebo** [comment]
Weird. I tested this and didn't see it. I wasn't using EUI wonder if that's it.

**Comment by TechpriestEnginseer** [comment]
Also, last feature request could there be a GameEvents.MissionCompleted(iPlayer, iUnit, iMission) for detecting Diplomatic Trade Missions?

**Comment by LoneGazebo** [comment]
Custommissionstart is the same. Just look for mission_trade

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer also re: events and stuff you are using the cityevent and event logs to track stuff, correct?

G

**Comment by TechpriestEnginseer** [comment]
Correct.
