### ISSUE TITLE
HalvedFollowers removed

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2971]
In the last patch (12th), HalvedFollowers in the Beliefs table seems to have been removed, but I use this in Piety. Is there a particular reason this was removed?

**Comment by LoneGazebo** [comment]
Yeah it didn't work properly (affected all beliefs for a player). Use the new halved followers yield table. Sorry I should have told you I removed it. 

G

**Comment by JFDaly** [comment]
No problem. Thanks.
