### ISSUE TITLE
Cannot found religion despite having 300 faith

### ISSUE THREAD

**Issue by jbarthis** [LoneGazebo/Community-Patch-DLL#2972]
_1. Mod version (i.e Date - 4/23): Version 88-beta. Updated today

_2. Mod list (if using Vox Populi only, leave blank): JFD's Cultural Diversity (Core), JFD's Rise to Power, Caravansary Trade Routes 

_3. Error description: I started a game on a custom map as Rome, sent out warriors on explore to find some ancient ruins. Ancient ruins pumped up my faith to 300 and I got a Great Prophet by turn 26. When I select the Great Prophet, does not have the "Found a Religion" option available despite being stationed in the middle of my capital city.

_4. Steps to reproduce (optional): 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files:
[LogsZIP.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/706975/LogsZIP.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 
[AutoSave_0025 BC-3000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/706976/AutoSave_0025.BC-3000.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20170115181052_1](https://cloud.githubusercontent.com/assets/25140085/21967083/6027e85a-db4e-11e6-84a5-f9f48ebf4c38.jpg)

**Comment by LoneGazebo** [comment]
Mod conflict.

**Comment by jbarthis** [comment]
Ah, okay. Thanks for explaining it.
