### ISSUE TITLE
Crusader Spirit doesn't seem to work

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2974]
_1. Mod version (i.e Date - 4/23): 1-12-1

_2. Mod list (if using Vox Populi only, leave blank):_
FlagPromotions v.7

_3. Error description:_ 
 Crusader Spirit (Reformation pick) which gives different combat bonuses based on my and enemy's religion doesn't seem to work. At least the bonuses are not shown in the combat odds.

_4. Steps to reproduce (optional):_
savegame attached

[Cr.Spirit.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/708765/Cr.Spirit.zip)

**Comment by LoneGazebo** [comment]
Works for me – sure you don't have a mod conflict or an install issue?

**Comment by saamohod** [comment]
The savegame I attached exhibits the bug. Combat odds with units near Rostov do not mention Crusader Zeal. Funnily, later on when I was engaged in another war with another civ, the odds tooltip started working. The same mods, the same game, I didn't even restart it.
![20170116214454_1](https://cloud.githubusercontent.com/assets/16341598/21996973/66bacbd2-dc35-11e6-88c0-50619d91eac1.jpg)
![20170116214957_1](https://cloud.githubusercontent.com/assets/16341598/21997050/cfe209b8-dc35-11e6-8f84-f781d877f72a.jpg)

**Comment by LoneGazebo** [comment]
You getting a lua log error at that point?

**Comment by saamohod** [comment]
Not sure if I did everything correct, but this is what I did.
I enable logging according to instructions (https://forums.civfanatics.com/threads/how-to-enable-logging.487482/), loaded the game at the Cr.Spirit save I have attached here, progressed one turn and here is the log.


[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/711185/Lua.zip)

**Comment by LoneGazebo** [comment]
@saamohod load it again and try to make the combat window pop up. Lua will only show an error if/when the bad lua is triggered.

**Comment by saamohod** [comment]
Did as you suggested. Here is the log

[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/713813/Lua.zip)

**Comment by LoneGazebo** [comment]
Looking at code, it all looks fine. My guess is that the AI temporarily did not have a 'founded' or 'majority' religion and that led to the bonus not being applied. I'll add a catch for that.
