### ISSUE TITLE
Oil discovered doesn't cycly

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2976]
_1. Mod version (i.e Date - 4/23):_1-12-1

_2. Mod list (if using Vox Populi only, leave blank):_
FlagPromotions v.7

_3. Error description:_ 
Clicking on an icon ""Strategic Resource" discovered!" (Coal, Oil etc when researching a relevant technology) doesn't cycle between resource locations (in case I have multiple within my territory), but only shows one location

![20170116213220_1](https://cloud.githubusercontent.com/assets/16341598/21996711/379f4964-dc34-11e6-866c-8d39c18ed7c9.jpg)

**Comment by LoneGazebo** [comment]
that's an eui 'feature.' not mine to fix
