### ISSUE TITLE
Tourism should decrease when a civilization is unhappy.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2977]
Sort of doesn't make sense to have people visiting your country and enjoying their stay there or having people dreaming wishing their nation was like ours when you have civil resistance and rebels terrorizing the area no?

**Comment by LoneGazebo** [comment]
Boredom gives a modifier to others, so it already does.

**Comment by Radost** [comment]
Well, we have spooky russian hackers IRL when Russia is a third world shithole, so influence definitely doesn't have to depend on happiness.

**Comment by Edaka** [comment]
@LoneGazebo While boredom does give a modifier to others, your tourism is still untouched. In other words, being unhappy doesn't decrease your tourism output the way it decreases other yields. However, this is a matter of balance and should probably be discussed on the forum.

**Comment by LoneGazebo** [comment]
@Edaka true, however culture victory requires a 'content' population, so there's that. I could make it such that a player cannot be 'content' without a >= 0 national happiness.

**Comment by Edaka** [comment]
Good point. Re: happiness that could be interesting, although I'm not sure if there needs to be another condition for an already fairly convoluted victory type. On the other hand, that would make cultural victory harder in some circumstances, and people have been saying that it's too easy at the moment.
