### ISSUE TITLE
Initial autosave file not created upon starting a new game

### ISSUE THREAD

**Issue by dape6509** [LoneGazebo/Community-Patch-DLL#2978]
_1. Mod version (i.e Date - 4/23):_
1/12 hotfix version

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The initial autosave file is not created when the game is initialized. This is the first time I've encountered this bug with CBP/VP, I've been updating and playing through games with every new version for the past year. I autosave on every turn and this normally creates the file "Autosave_Initial_0000 BC-4000.Civ5Save" before/on turn 0 then "Autosave_0000 BC-4000.Civ5Save" before/on turn 1. With this patch, only the latter file is saved then every subsequent turn (Autosave_0001, 0002, etc.). This essentially means the game must be saved manually on turn 0 before moving units, settling cities, etc. to have the initial gamestate saved.

_4. Steps to reproduce (optional):_
Simply starting a new game and checking the autosave folder at turn 0, turn 1, etc. I have been able to reproduce the bug after manually clearing the cache and mod folder before reinstalling the mod. I also verified game cache in Steam. I made a ZIP file with my logs folder and saves but github is not accepting it as a supported file attachment for some reason. If these are necessary I will try my best to attach them.

**Comment by LoneGazebo** [comment]
@ilteroi I know you touched autosave recently. Thoughts?

**Comment by ilteroi** [comment]
i did - but not the initial save. from looking at the code, it's possible that the initial save is skipped when using a worldbuilder map (ie YNAEMP).  which map are you using?

**Comment by dape6509** [comment]
I am using the default map generator, specifically Continents

**Comment by ilteroi** [comment]
ok - my mistake - i was assuming the initial save is created in regenerateMap() but that is dead code, never called. fixed.

**Comment by dape6509** [comment]
Awesome! Thank you for addressing it so quickly. My regards to the whole VP team for evolving Civ 5 into one of the best games of all time.
