### ISSUE TITLE
question about flavors

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#2979]
i recently implemented a change where leaders' willingness to settle a bad spot depends on their expansion flavor.

now i was quite surprised to find boudicca settle in the arctic. apparently GetFlavorManager()->GetIndividualFlavor((FlavorTypes)GC.getInfoTypeForString("FLAVOR_EXPANSION")) returns 22. however in the Leader_Flavors table in the database it says only 7.

Where does this difference come from?

**Comment by LoneGazebo** [comment]
That's...really strange. That individual flavor should not be modified.

**Comment by LoneGazebo** [comment]
I'll try today.

**Comment by LoneGazebo** [comment]
Ah, I see what it is - getindividualflavor is grabbing the flavor that is modified by AI strategies. You have to use GetPersonalityIndividualFlavor to get the database flavors.

**Comment by ilteroi** [comment]
what's the range on the modified flavor? in fact it might be better to use that one - more variation.

**Comment by LoneGazebo** [comment]
-1000 to 1000 IIRC.
