### ISSUE TITLE
HappinessPerGarrisonedUnit and GoldenAgeDurationMod Un-Hardcodifying

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#298]
The tag HappinessPerGarrisonedUnit appears to hardcoded to only ever grant 1 Happiness (tested to see whether this was Local Happiness or not, too, so it's not that), regardless of the amount set. If this is indeed the case, could this be fixed so that the number set to the column is the amount of Happiness actually given.

I'd also like to ask that GoldenAgeDurationMod (from the policy table) be made to support negative values - so that it can be used to reduce the length of Golden Ages if specified.

Thanks for any help.

**Comment by LoneGazebo** [comment]
Fixed and fixed.
