### ISSUE TITLE
Units are not thrown out of borders and cant escape w/o declaring war 

### ISSUE THREAD

**Issue by InapropriateUsername** [LoneGazebo/Community-Patch-DLL#2980]
_1. Mod version_  
1/12 (with hotfix from 14th of January)

_2. Mod list (if using Vox Populi only, leave blank):_ 
Vox Populi only, but in a form of mp_modpack (it was single player game)

_3. Error description:_  
If AI settler settles near your unit - this unit is not thrown out of borders. Usually it can escape next turn, but with Shoshone perk it can't (technically it can, but with declaring a war)

_4. Steps to reproduce (optional):_ 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files 

didn't enable logs, but i'm sure you understood

2. Save game 

can't attach ziped savegame. don't know why. can email it or something

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://cloud.githubusercontent.com/assets/19764746/22037209/53b69494-dd07-11e6-8ab2-c6d5b4e44f26.png)

**Comment by InapropriateUsername** [comment]
Also worker managed to buid camp under my warrior

**Comment by TechpriestEnginseer** [comment]
I think this was a bugfix that started to repel people off when you liberated a city-state or a city to its original owner.

**Comment by LoneGazebo** [comment]
@ilteroi it should probably shove units out, no?

**Comment by ilteroi** [comment]
hmm. think so. 

there was an issue recently (#2936) which might be related. i fixed it by preventing recursion in CvUnit::setXY but maybe if you merged any of supermerill's changes, it could have side effects?

**Comment by ilteroi** [comment]
ok i see the problem. scratch the above - should be fixed

**Comment by InapropriateUsername** [comment]
Forgot to mention end-of-war case. Should be the same problem

https://forums.civfanatics.com/threads/community-patch-how-to-install.528034/page-115#post-14631072

**Comment by AnastaseAlex** [comment]
Same issue. My units got stuck in Attila's territory after he signed peace. I could no longer move. Felt too cheesy since I had totally surrounded his capital and he could not get units out of it.

**Comment by saamohod** [comment]
I confirm this. My units are stuck inside an enemy lands after I've signed peace with him. If I'm lucky he's willing to give me open borders, otherwise load previous autosave in order to remove my troops out of his territory prior to peace treaty.

**Comment by LoneGazebo** [comment]
@ilteroi let me know when merged to fefe.

**Comment by ilteroi** [comment]
it's done

**Comment by LoneGazebo** [comment]
@ilteroi on latest I'm seeing units getting thrown onto water unembarked from this:

![20170120143648_1](https://cloud.githubusercontent.com/assets/7849458/22162787/0718adde-df1e-11e6-8562-2d851c9ed809.jpg)
