### ISSUE TITLE
AI settlers do not settle in multiplayer

### ISSUE THREAD

**Issue by InapropriateUsername** [LoneGazebo/Community-Patch-DLL#2981]
_1. Mod version_ 
1/12 (with hotfix from 14th of January)

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi only, but in a form of mp_modpack (it was multiplayer game)

_3. Error description:_ 
I already posted this issue in "New Version - January 12th" thread on civfanatics. I'm not sure if you guys deal with multiplayer bugs, but i hope someone will take a look, cause multiplayer is uplayable now. And thanks again for creating such an interesting game!

AI players do not build cities at all, or build only 1 or 2 of them and they do it very late. 
Instead of that, they build settlers who suffer from some kind of mental disease. They walk in circles and back and forth or just do not move for 3 or 4 turns. 
Sometimes they manage to get to a place where a city was planned, if it happens - they found a city. On huge Pangea with 12-16 players, immortal or deity, AI usually has 1 or 2 or maybe 3 (very rare) cities, while i usually have 8-10 (around 100th-120th turn).
If i start singleplayer game with same settings - they seem to expand normally. It works **even if i start singleplayer game with mp_modpack**, not via "mods" button. But if i start the game via "multiplayer" button, no matter togther with someone or alone (one human) and AI players - the problem appears. 

_4. Steps to reproduce (optional):_
Create MP_MODPACK via Multiplayer Mods Workaround and Firetuner, start multiplayer game, wait 70-100 turns

---------------------------

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

cant upload zipped save, it says that it does not support that type of file. Can email it.

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
one game
![image](https://cloud.githubusercontent.com/assets/19764746/22075427/ff5a60a4-ddbc-11e6-88bd-3a45b0804a82.png)

one more game, different AIs and turns
http://image.prntscr.com/image/01354b9826514282bb760fd4bcf63748.png
http://image.prntscr.com/image/5adf8e42cc3b4dce891839e8f192fcf6.png
http://image.prntscr.com/image/907655c9cc4b4a509dd42a0145f1da45.png
http://image.prntscr.com/image/4bcf8fb019aa45f59a596b8f09f4850d.png
http://image.prntscr.com/image/75427b06bf174403af3350d363b9dbbe.png
http://image.prntscr.com/image/6ec96fcba2ee46e6b3358d21b8f8643c.png
http://image.prntscr.com/image/a9cf5db145db4f138a648ef4e77c4f1f.png

**Comment by LoneGazebo** [comment]
My first guess is that you didn't build the MP correctly, possibly leaving the DLL out or something.

G

**Comment by InapropriateUsername** [comment]
But why then it works correctly in singleplayer with modpack and without vox populi launched or even installed?

I just followed instructions, it worked previously, i play with my own modpacks for more than half a year

**Comment by InapropriateUsername** [comment]
I've just doublechecked. DLL is fine

**Comment by LoneGazebo** [comment]
well the AI performs identically in the DLL whether or not it is SP/MP, so you've got something funky going on on your end.

**Comment by InapropriateUsername** [comment]
I thought so too, but my friend is experiencing same problem, we both tried to create modpacks and we both tried to launch game in SP and MP together and alone... It seems really strange to me

**Comment by LoneGazebo** [comment]
@ilteroi any recent changes to this that might affect the AI's use of settlers?

**Comment by InapropriateUsername** [comment]
I've enabled logs and i think i might see the problem that may be related.  However this happened while i was checking logs for **singleplayer**. 

I saw that immortal Hiawata has 1 city on turn 76 while others have 3-4 cities. (another question is why didn't he build settlers): http://image.prntscr.com/image/8de85326440449c690c3d33fa2b2f25e.png

Here is what happened next:   

First settler goes guarded by spearmen normally, but thats when **settler and his guard are in one place.**

After that Hiawata gets 3rd settler and wants to build 3rd city, but this time settler goes **alone**

after that settler makes two steps forward, -> after that AI assigns escort to that settler -> escort and settler are not in the same place , so settler goes back to the capital and waits for the escort -> after several turns a scout assigned for escorting comes back and they go settle together. 

At the same time his 4th settler managed to get to the place, where he wanted to settle without escort and settled successfully

i messed up a bit with loading autosaves while doing this, so it will be quite hard to see the process from logs. I'll post info extracted from logs later

**Comment by LoneGazebo** [comment]
@InapropriateUsername mind posting the log?

**Comment by ilteroi** [comment]
yes i did to solve the CP-only stacking problem discovered by supermerill ... but it works fine for me

**Comment by InapropriateUsername** [comment]
Here i extracted info for Hiawata, and screenshots of the process:

[hiawata logs extracted.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/717741/hiawata.logs.extracted.txt)

As far as i see from logs - AI constantly changes escorting unit for that settler because there is no unit near the settler.

http://image.prntscr.com/image/cce2bf2258744e25a9f7a812bfa79090.png
http://image.prntscr.com/image/01759a2ca1dc45ecba4c9cd46820ead7.png
http://image.prntscr.com/image/354e0ba1525140f3b968eb537b4320b3.png
http://image.prntscr.com/image/9a0b957957834668bcecbb8021e94b22.png
http://image.prntscr.com/image/51f79fa48ed54237baed84b4cb88669a.png
http://image.prntscr.com/image/467bc920292f40169e53c8a4e62368b1.png

**Comment by LoneGazebo** [comment]
@InapropriateUsername do you have the operationAI and homelandAI logs?

**Comment by LoneGazebo** [comment]
also tacticalAI

**Comment by InapropriateUsername** [comment]
no sorry, dont see them in logs folder. How should i enable them?

**Comment by LoneGazebo** [comment]
; Enable AI logging
AILog = 1

; Enable AI performance logging
AIPerfLog = 1

in config.ini

**Comment by InapropriateUsername** [comment]
Ok, done, thanks.

 I'll now take a look on how does it work in MP, cause what intrests me more is why AI work completely different in SP and MP. One buggy Hiawata do not break the game, but when there is 14 of them suffering from that...

**Comment by ilteroi** [comment]
well, unescorted settlers are easily scared, e.g. if there was a barbarian somewhere around the planned settle site. then it goes back and a new operation is started, this time with an escort. inefficient but that's the way. can't image this happening to all AI players at once though.

**Comment by InapropriateUsername** [comment]
@ilteroi barbs were disabled - see first pack of screens in the issue

**Comment by InapropriateUsername** [comment]
Guys i do not see operationAI / homelandAI / tacticalAI in logs folder, where are they?
And why it says that it doest not support .zip files?

Anyway here are logs from MP game. Take any settler and search its id - you'll see that it constantly changes its mission like this:
[679855.375] DBG: UpdateMoves() : player 5 Theodora running AutoMission (MISSIONAI_ASSAULT) on Settler id=1231
[679892.078] DBG: UpdateMoves() : player 5 Theodora running AutoMission (NO_MISSIONAI) on Settler id=1231
[679915.343] DBG: UpdateMoves() : player 5 Theodora running AutoMission (NO_MISSIONAI) on Settler id=1231
[680025.781] DBG: UpdateMoves() : player 5 Theodora running AutoMission (MISSIONAI_ASSAULT) on Settler id=1231

[net_message_debug1.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/717866/net_message_debug1.txt)

**Comment by LoneGazebo** [comment]
You should see: PlayerTacticalAILog

**Comment by InapropriateUsername** [comment]
I have one more weird thing. I had no AI logs that you were talking about, so my idea was that probably AI logs are not created in MP. I decided to check it in singleplayer without modpack and then compare. With that in mind i deleted mp_modpack and attempted to start SP game with mods (via MODS button). And after i pressed start - game crushed. 

Finally, after verifying gamefiles integrity, restarting steam, reinstaling vox populi i found that if i set **AIPerfLog = 1** then everything works well. But if i set **AILog = 1** - game crushes at start. **Without mp_modpack, just SP.** And again this happens to my friend on different computer...

**Comment by krinitsin** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/720957/Logs.zip)
AIl logs for modpack (1-12-1) with broken settlers. Its a multiplayer game with 1 human and 11 AIs. No barbs/ruins.

**Comment by LoneGazebo** [comment]
@InapropriateUsername it sounds like you've got a problem as those settings do not cause that outcome on my machine.

**Comment by InapropriateUsername** [comment]
@LoneGazebo 

I've just replaced dll in 1-12-1 by ddl from 14-12 modpack and it works well. At least, with regards to AI settlers in MP. Don't know if it will break somewhere else or not

**Comment by InapropriateUsername** [comment]
@LoneGazebo i fixed AI logs, works correct now. Apparently it requires additional options in config.ini to be enabled. Sorry for that

**Comment by supermerill** [comment]
@krinitsin can we have an hint?
I looked at two civs and theirs settlers are moving correctly to the settle spots.
Where do we have to look (civ, turns) ?

**Comment by InapropriateUsername** [comment]
@supermerill 
I cant take a look at logs now, i'm not at home. As far as i understood they start to move, then they stop, then they start again, then they go back and repeat. Take a look at my log with Theodora above

**Comment by InapropriateUsername** [comment]
@supermerill 

Lets take OperationalAILog_China for example (and also net_message_debug). From OperationalAILog_China i can see that on turn 46 China has settler with id=1302 and she wants to build a city (if i'm not mistaken - settler has coordinats x=36 y=47, and China want a city at of x=37 y=42).  But then something happens and it says "047, China, AI_OPERATION_FOUND_CITY_QUICK, 2, Ended: No target" and then cycle repeats. The settler will be alive until turn 100

In net_message_debug and there is a chinese settler with the same id that firsty apperas on turn 43. On Turn 45 it has automission (MISSIONAI_ASSAULT) but on turn 46 it has automission (NO_MISSIONAI) and so on

**Comment by LoneGazebo** [comment]
Don't worry about the missionai_assault stuff. 

Quick will end if the target is dangerous. That's what is happening. Otherwise everything is working fine.

**Comment by InapropriateUsername** [comment]
@LoneGazebo 

But the target is not dangerous, we play without barbarians. Maybe it found the target dangerous for some reason, while its actually not?

 It can be clearly seen from logs that every AI has a settler or two that are trying to settle, but they live from 40-50th to 100th turn. Just like on my screenshots. I'm really sorry if i'm being annoying but we already tested this on 3 PCs with reinstalling civ5... Also we've tried modpack created by ElliotS. I would be happy if that was my personal problem.

**Comment by LoneGazebo** [comment]
@InapropriateUsername no worries, but what I'm trying to get at is that - your examples aside - I can't replicate this behavior consistently. Without replication (and even with logs) there's nothing for me to fix. I'll keep an eye out for it but otherwise this is a stagnant issue.

G

**Comment by InapropriateUsername** [comment]
@LoneGazebo you mean modpack is working correctly in multiplayer for you? Cause thats the part that completly don't understand, even theoretically - modpack in singleplayer works!

**Comment by supermerill** [comment]
you're right, your china is acting strangely. 
i like this line: 
065, China, Settler at (37,42). Moving normally towards (37,42) without escort.

**Comment by InapropriateUsername** [comment]
@supermerill you can compare it to America for example, it "successfully" founded 2nd city on 75th turn (after 30 turns of walking back and forth).

Any ideas on how could AI act differently in singleplayer and multiplayer with the same modpack? I've tried to replace .dll in this modpack by previous one and it works correctly (with regards to AI, lots of othe bugs ofcourse), so the problem is definetly somehere in the .dll, not my PC or something

**Comment by ilteroi** [comment]
@supermerill : that line is misleading, the log is printed only after executing the move ...

**Comment by InapropriateUsername** [comment]
@ilteroi is it possible to somehow revert AI to previous version while keeping the rest of the changes? For our personal use. My friend has experience in programming

Also here i compared AI behaivior in MP and SP http://image.prntscr.com/image/e0818c93223c4d7aab82ac82559423fa.png

**Comment by ilteroi** [comment]
it's not really clear to me which previous version you mean?

anyway these logs of yours are indeed suspicious - although i cannot imagine that the problem is related to multiplayer.  i rearranged some bits and added some more diagnostic logging to see where exactly the the target is lost. if you or your friend could pull the latest from fefe branch, build it and report back, that would be great!

**Comment by Adonis-VII** [comment]
I also have the same issue where certain civs seem to collect settlers in Multiplayer using Jan 12th build for our session last night. I didn't have logging turn on, but will do for our next session and report.

http://i.imgur.com/wPx8aGK.png
