### ISSUE TITLE
Enemy units entering borders

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2984]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I often see enemy units traverse through my border, or stay in them. Last game, a  Portugese Trireme was in my borders for a few turns, and a game before I saw a Spear and a Scout in them. I don't know how they do it. It was before Open Borders agreements even became possible, too.

**Comment by LoneGazebo** [comment]
Yeah, we've got the issue resolved (ilteroi does).
