### ISSUE TITLE
Weird road building

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2986]
_1. Mod version (i.e Date - 4/23): 1-12-1 EUI

_2. Mod list (if using Vox Populi only, leave blank):_
FlagPromotions v.7

_3. Error description:_ When given an order to build a road to a certain tile, a worker steps aside instead of making a shortest route to the designated point. (shown on screenshots 1 and 2)

_4. Steps to reproduce (optional):_ savegame attached

[AutoSave_0142 AD-0640.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/718009/AutoSave_0142.AD-0640.zip)
![20170119221814_1](https://cloud.githubusercontent.com/assets/16341598/22129204/37753400-dead-11e6-8a16-48469bf3405a.jpg)
![20170119221819_1](https://cloud.githubusercontent.com/assets/16341598/22129206/383b2250-dead-11e6-9ab1-14b6fb7c4897.jpg)

**Comment by LoneGazebo** [comment]
They're both 4-tile roads.

**Comment by saamohod** [comment]
>They're both 4-tile roads.
 Pardon, I can't see how they are both 4-tile roads. Ideally the worker should step into the tile where the spearman is and continue to the designated destination, which would make 3 tiles. But he steps to the side thereby lengthening the track by 1 tile.

**Comment by saamohod** [comment]
![20170119221814_11](https://cloud.githubusercontent.com/assets/16341598/22130310/d566cc4a-deb3-11e6-8b9c-c389f3b3e368.jpg)
![20170119221819_12](https://cloud.githubusercontent.com/assets/16341598/22130313/d641a018-deb3-11e6-886f-0d4fde11c682.jpg)

**Comment by LoneGazebo** [comment]
Oh I thought you were going between the cities. Not sure why he skipped that.

**Comment by ilteroi** [comment]
funny. i wasn't even aware that there's a "road to nowhere" option

**Comment by saamohod** [comment]
>funny. i wasn't even aware that there's a "road to nowhere" option

 You're right, there isn't one ;)
 But there is an option to build road "from point A to point B". And obviously AI sometimes ignores the shortest route from A to B. Not a major bug, no. But a bug nonetheless.

**Comment by ilteroi** [comment]
ok - the AI tags certain plots for city connections so that different workers can work on the road network independently, before the roads even exist. what happens here is that the worker tries to keep the new road superimposed with the not-yet-existing road to old sarai.

unsure how to fix this, after all it's a minor issue ...

**Comment by ilteroi** [comment]
i think i found an easy way. hard to test though. but at least the normal roadbuilding still works :)
