### ISSUE TITLE
Food tooltip 

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2987]
_1. Mod version (i.e Date - 4/23):_1-12-1 EUI

_2. Mod list :_FlagPromotions v.7

_3. Error description:_  Food yield tooltip (bottom left corner on the screenshot) says the farm adds +5 food (and +1 production) while in fact it only makes +1 food (and probably correct +1 production)

![20170119215235_1](https://cloud.githubusercontent.com/assets/16341598/22129281/ac6464de-dead-11e6-8fb6-ec76f7a5cbb2.jpg)

**Comment by TechpriestEnginseer** [comment]
Isn't this an EUI feature?

**Comment by saamohod** [comment]
No idea really.

**Comment by Radost** [comment]
It shows the yields with all possible modifiers for this particular improvement.
