### ISSUE TITLE
Colombian Worker Bonanza

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#2989]
_1. Mod version (i.e Date - 4/23):_
Current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Just look at this picture. There's like 8 workers there, near Colombo. They are in an endless circle of barbies replenishing Swordsmen, them being killed by City's bombardment and then the city never taking it. Once I get to travel through ocean with actual troops (not ships), Colombo will become a perma ally of mine just thanks to this.

[colmboo.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/720568/colmboo.zip)

**Comment by LoneGazebo** [comment]
Ha, that's nothing, I've seen stacks of 10 barb workers before.

**Comment by supermerill** [comment]
Enrico the great, the one who free all the colombo slaves.
