### ISSUE TITLE
Indonesian luxuries occasionally spawn under city and prevents razing

### ISSUE THREAD

**Issue by ashendashin** [LoneGazebo/Community-Patch-DLL#2990]
_1. Mod version (i.e Date - 4/23):_
1/12.1 43 civ dll

_2. Mod list (if using Vox Populi only, leave blank):_
Enhanced City-States
YnAEMP

_3. Error description:_ 
For some reason it seems common for conquered cities to have the UA spawn under it. Is this intentional? I haven't seen any mention of it.
![20170119223028_1](https://cloud.githubusercontent.com/assets/21032378/22169895/ef1301da-df45-11e6-97b0-e5060bc8917d.jpg)
![20170119223036_1](https://cloud.githubusercontent.com/assets/21032378/22169898/fd289866-df45-11e6-8a0a-26c53a5a50ed.jpg)

**Comment by LoneGazebo** [comment]
It only happens if there is otherwise no place to put the resource.

**Comment by ashendashin** [comment]
Plenty of free tiles in multiple cities.
![20170120211101_1](https://cloud.githubusercontent.com/assets/21032378/22171126/60d084c8-df55-11e6-93e4-0e32c60d323a.jpg)
![20170120211130_1](https://cloud.githubusercontent.com/assets/21032378/22171127/63e515e8-df55-11e6-9420-851f175267a0.jpg)

And what about the razing? I don't care about placement, but it's weird that it blocks razing. If you don't mind, why do conquered cities spawn these the first place? Seems counter-intuitive to the monopoly aspect, which is pretty much most of their worth.

**Comment by TechpriestEnginseer** [comment]
It seems more like a nerf if conquered city gains you a unique luxury because if it gets recaptured, the enemy gets a free luxury. Not to mention Candi seems to keep spawning them and when there's no space in the city, they spawn them toward my neighbors instead which they definitely love.

**Comment by saamohod** [comment]
In my game I too cannot raze Indonesian city(-es). The only options are Annex or Create a Puppet.

**Comment by TechpriestEnginseer** [comment]
I bet this is DLL-hardcoded due to Indonesia's old UA of having unrazeable cities.

**Comment by ashendashin** [comment]
Then I suppose the placement just needs fixing or removal, as it only happens with conquered cities.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer is correct, this is not something we can work around.

**Comment by TechpriestEnginseer** [comment]
Best way is probably to nerf the UA?
