### ISSUE TITLE
Strange City-State Borders Growth

### ISSUE THREAD

**Issue by InapropriateUsername** [LoneGazebo/Community-Patch-DLL#2991]
_1. Mod version (i.e Date - 4/23):_ 1-12-1

_2. Mod list (if using Vox Populi only, leave blank):_ flag promotions

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://cloud.githubusercontent.com/assets/19764746/22175358/2af16f52-e004-11e6-82ff-cf5ff204e428.png)

**Comment by InapropriateUsername** [comment]
Not a big deal, doesn't break the game, but still...

**Comment by TechpriestEnginseer** [comment]
It's not strange, the game prioritize strategic and luxury resources.

**Comment by InapropriateUsername** [comment]
Ye, i understand, but i was thinking that 4th tile away from city has very low priority... Anyway, as i said, not a big deal

**Comment by TechpriestEnginseer** [comment]
But are there any other good tiles within its working radius?

**Comment by Radost** [comment]
City-States crawling towards resources is a double-edged sword. With Statecraft and no other bonuses it's better to have resources on city-state care, but it's a loss otherwise (especially with Autocracy). On other hand, there are far too many situations when I saw an island city-state having aluminum/uranium just next to their border and they refuse to grab it.

**Comment by ilteroi** [comment]
it's hard to please everybody ... anyway i increased the penalty for plots which are outside of working range. should be better.
