### ISSUE TITLE
Cheating AI!

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2992]
I've been seeing archaeologists all around the hidden antiquity sites and wondering why they haven't dig it already. Well obviously it's because they don't have a completed aesthetic tree and have something else!

**Comment by LoneGazebo** [comment]
eh?

**Comment by Der-Zorn-Gottes** [comment]
I think he sais that the AI is blocking hidden arch. sites that it should not know about.
Question to TE: did you check that the AI indeed does not have 6 aesthetics policies or maybe it's just not digging because it currently lacks slots?

**Comment by TechpriestEnginseer** [comment]
Attila had completed Tradition, Progress, and about to finish Industry but has no relations to Aesthetics.
