### ISSUE TITLE
Crash on AI turn

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#2993]
_1. Mod version (i.e Date - 4/23):_

2/12

_2. Mod list (if using Vox Populi only, leave blank):_

-

_3. Error description:_ 

Reproducable crash on AI turn. Hadn't have on of those for a long while.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
[Crash Info.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/721915/Crash.Info.zip)

**Comment by supermerill** [comment]
many cdt have been corrected since december.
I will try to load your save, but no promise on a hotfix.
