### ISSUE TITLE
Request: GreatGeneralExtraBonus for Policies table

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#2994]
I'd like to request GreatGeneralExtraBonus from the Traits table to be adapted to the Policies table. This increases the Combat Bonus units get when near to a Great General by the specified amount. Just whenever you get the chance - thanks!

**Comment by LoneGazebo** [comment]
Done and done.

**Comment by JFDaly** [comment]
Awesome, thanks
