### ISSUE TITLE
City state gifted boat spawned in landlocked city

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#2995]
_1. Mod version (i.e Date - 4/23):_
1/12

_2. Mod list (if using Vox Populi only, leave blank):_
FlagPromotions (v 7)
Ingame Editor (v 39)
QuickTurns (v 10)

_3. Error description:_ 
A Nau gifted from Budapest was placed inside of a landlocked city (possibly related to #2980 and #2936).  

---------------------------
Supporting information:

![](http://i.imgur.com/LK1KpZu.jpg)

**Comment by ilteroi** [comment]
should be fixed
