### ISSUE TITLE
Great Admiral's Combat Bonus

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#2996]
_1. Mod version (i.e Date - 4/23):_1-12-1 EUI

_2. Mod list (if using Vox Populi only, leave blank):_  FlagPromotions v.7

_3. Error description:_ 
 Naval combat odds tooltip doesn't show the bonus a Great Admiral should provide (+15%).

Savegame attached

[Admiral.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/727482/Admiral.zip)

![20170124194552_1](https://cloud.githubusercontent.com/assets/16341598/22259505/44160fe4-e26e-11e6-9f0d-9404a613c222.jpg)
![20170124194612_1](https://cloud.githubusercontent.com/assets/16341598/22259506/45a2ea80-e26e-11e6-91af-15f54f7cd958.jpg)

**Comment by LoneGazebo** [comment]
@ilteroi do GA/GG aura bonuses recalculate as the unit moves?

**Comment by saamohod** [comment]
I've noticed that later in the game the bonus kept appearing and disappearing.

**Comment by ilteroi** [comment]
indeed, it seems the position is cached at the beginning of the turn, and not updated after moving ... will fix
