### ISSUE TITLE
Ideological Wonder Destruction

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#2997]
Upon an ideological revolution, should their respective ideology national wonder be destroyed to prevent the humans from abusing its diplomatic votes if possible?

On another note, National Intelligence Center has no cap (Unlike the ideologies..) on the addition of spies, so humans can build these in conquered cities and then raze them to get more spies to dominate the city-state theater.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer there's no easy way to prevent this, however you can't start razing a city after you'v conquered it so I'm not sure about your last point.
