### ISSUE TITLE
Mercantile CSs losing their Unique Luxury from being Sacked

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#2999]
From this Thread:  https://forums.civfanatics.com/threads/mercantile-cs-luxuries.609552/

Why do they disappear forever when conquered or sacked? 

If I capture a city that settled on coffee, I don't see that coffee disappearing. It also makes the monopolies associated with these luxuries pointless unless you're Venice, who for some reason can get away with assimilating and keeping the luxury... which I'm really turning my nose to. Why is it that only Venice can have these luxuries?

Seriously, just... Is there a weird reason behind this, or is this a long standing bug?

(Also, while I'm at it, Caravansary text has a typo in "neabry." I've stared at it for six months and I'm kinda sick of that one, too.)

Quoted from Takagi

**Comment by LoneGazebo** [comment]
Yeah, that's a vanilla thing for some reason. I'll look at it.
