### ISSUE TITLE
Mod UI conflict?

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#3000]
_1. Mod version (i.e Date - 4/23):_
1-26 (no-EUI)

_2. Mod list (if using Vox Populi only, leave blank):_
FlagPromotions (v 7)
Ingame Editor (v 39)
QuickTurns (v 10)

_3. Error description:_ 
The UI elements for QuickTurns and IGE seem to have disappeared, even though they are listed as being loaded. FlagPromotions works properly. Reinstalling 1-12 has them working properly.

_4. Steps to reproduce (optional):_
Try loading a mod that adds UI elements to the top bar or the "additional information" tab.

**Comment by LoneGazebo** [comment]
Fixed. Download hotfix. Savegame compat.
