### ISSUE TITLE
Feitoria Canals not working

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#3002]
_1. Mod version (i.e Date - 4/23):_
1/12

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Portuguese Feitorias do not allow naval units to cross through like a normal fort would.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Radost** [comment]
It's not a fort replacement.

**Comment by oalzubbi** [comment]
Well, my workers aren't able to build forts on the coast for some reason. I can only build feitorias when it's adjacent to sea

**Comment by Radost** [comment]
So you can't build a fort next to Feitoria?

**Comment by LoneGazebo** [comment]
Shouldn't matter

**Comment by oalzubbi** [comment]
I'm confused, what shouldn't matter? How is this supposed to work?

**Comment by LoneGazebo** [comment]
Feitoria's aren't forts.
