### ISSUE TITLE
Pacifism works for followers

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#3003]
_1. Mod version:_ 1/26.1

![8930_20170128040411_1](https://cloud.githubusercontent.com/assets/1131228/22390840/5ac7c194-e50f-11e6-9054-591a8afef0ba.png)
![8930_20170128040409_1](https://cloud.githubusercontent.com/assets/1131228/22390844/60035632-e50f-11e6-8a70-57a878ada4de.png)

Ethiopia is the founder and the current Holy City owner.

**Comment by LoneGazebo** [comment]
I'll look. May be missing a validity check.

**Comment by pandasnail** [comment]
I can never keep track of what nonfounders are and aren't supposed to get, so I don't know for sure this is related, but I'm getting God of War yields from having one city following the Byz religion and the rest my own pantheon still.

**Comment by LoneGazebo** [comment]
@pandasnail are you sure it is from that pantheon?

**Comment by pandasnail** [comment]
It didn't start happening until the Byz religion spread to that border city.

Two things I suppose to add:
I play with Historical Religions and Favorite Religion Randomizer. These mods are supposed to changed the names and icons and stuff, not mess with functionality. But one never knows.

That border city is probably my second best, and I had a ton of faith, so I immediately bought all three buildings Byz put on the Faith, Orders, Stupa, and a Mosque. Idk how that could matter.
