### ISSUE TITLE
Can't build universities with faith

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3010]
_1. Mod version (i.e Date - 4/23):_1-26-1

_2. Mod list (if using Vox Populi only, leave blank):_ FlagPromotions v.7

_3. Error description:_ There is no option to buy universities with faith despite reformation belief (which it says it should).

_4. Steps to reproduce (optional):_
Savegame attached

[Faith.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/738999/Faith.zip)

![20170130151436_1](https://cloud.githubusercontent.com/assets/16341598/22424480/6d0b0c7a-e6ff-11e6-96b9-d09f9906edba.jpg)
![20170130151452_1](https://cloud.githubusercontent.com/assets/16341598/22424483/6e22def8-e6ff-11e6-9332-d0de7bda55c2.jpg)

**Comment by LoneGazebo** [comment]
If it is not your founded religion, you do not get the benefits from the reformation.

**Comment by saamohod** [comment]
Oh, I never realized that. You learn something new every day.
Thanks.

**Comment by LoneGazebo** [comment]
Only follower.
