### ISSUE TITLE
American UA - Discount doesn't apply to annexed cities before the first tile purchase

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#3012]
_1. Mod version:_ 1/26.1

![8930_20170131055211_1](https://cloud.githubusercontent.com/assets/1131228/22448997/f6613150-e77e-11e6-92c7-18bd17d3bee9.png)
![8930_20170131055215_1](https://cloud.githubusercontent.com/assets/1131228/22448999/f9ef2962-e77e-11e6-8385-b54299d30fb0.png)

**Comment by LoneGazebo** [comment]
@ilteroi I have no clues here, do you?

**Comment by Radost** [comment]
What information do you need exactly?

**Comment by LoneGazebo** [comment]
Well, I don't see where this updates in the DLL - it should update when you click the gold button but it does not seem to.

**Comment by ilteroi** [comment]
i guess GetBuyPlotCost() would be the place to look but i don't see anything that could be causing this

**Comment by LoneGazebo** [comment]
@ilteroi likewise.
