### ISSUE TITLE
Garrisons never attack

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3013]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Find a city with a garrison. Regardless of if it has full health or not, it'll never attack. Archers in cities do not shoot, warriors do nothing even if 100% hp.

**Comment by Enrico-Swagolo** [comment]
Correction - they sometimes do attack (suddenly they started to), but sometimes they do not even if they're not healing.

**Comment by LoneGazebo** [comment]
@ilteroi is this an issue with tactical recruitment?

**Comment by Enrico-Swagolo** [comment]
Doesn't seem like they're freshly recruited to me. The 100% hp warrior  was inside the city and allowed my Survivalism 3 scout to pillage everything near it without attacking (despite bombardment + attack being a sure way to kill my guy), with my guy only receiving bombardment damage. Archers in another city also didn't care about my scout, and they didn't immediately react to the later archers too.

Da udda Arrer boyz iz unorky gitz iz my kan-klawshun.

**Comment by ilteroi** [comment]
indeed. wonder why nobody noticed that earlier ...

**Comment by ashendashin** [comment]
I seriously thought this was already known... I wonder how many small mishaps are till lying around that no one thought to bring up.

**Comment by Radost** [comment]
@ilteroi 
For me most of the wars involve wall vs. wall encounters. It's hard to notice a particular unit not attacking in its turn, especially with animations turned off.
