### ISSUE TITLE
Autocracy Tenet only gives free airport in limited number of cities

### ISSUE THREAD

**Issue by CharlesDR** [LoneGazebo/Community-Patch-DLL#3014]
_1. Mod version (i.e Date - 4/23):_
1/12/2017 (43civ patch)

_2. Mod list (if using Vox Populi only, leave blank):_
43 Civ DLL
full VP
YnAEMP

_3. Error description:_ 
No free airport is given beyond a certain number of owned cities. In this game, I own 94 cities and only 88 have airports - I have not manually built any airports. This seems to be related to (closed) issue #480. Is there an editable XML value that YnAEMP users could tweak themselves?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Should be unlimited, but in some maps of extremely large size (TM) memory will falter.
