### ISSUE TITLE
Capital Confused When Religion Founded at 2nd City

### ISSUE THREAD

**Issue by muarB** [LoneGazebo/Community-Patch-DLL#3015]
_1. Mod version (i.e Date - 4/23):_

1/26
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I've seen this in a couple games.  I founded a religion at a 2nd city.  When I spread the religion to my Capital it didn't take with one missionary.  My neighbors hadn't founded a religion.  I looked at the Faith detail in the city and there were two pantheon symbols, as if it had two competing pantheons.  I forgot to check if they were different.  So I sent a 2nd missionary and it worked then.  My neighbors were Siam and Zulu.  Seems like there's something messed up if your Capital founds the pantheon and another city founds the religion; or I am not understanding something.

I took screenshots from in game but they are in a ".tga" format in the screenshot folder.  Not sure how to open them or share them here.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi any ideas? Shouldn't matter, right?

**Comment by ilteroi** [comment]
hmm. never looked at that part of the code. hard to tell

**Comment by muarB** [comment]
![faith](https://cloud.githubusercontent.com/assets/23019463/22524935/17cd7c58-e87a-11e6-9307-83980219e8a3.png)
Here's a screenshot.  Not sure link works.

**Comment by ilteroi** [comment]
the lightning symbol is your pantheon and the eagle type thing is zoroastriansm. nothing wrong as far as I can see. your city has 9 citizens, so you need one more follower for zoroastriansm for it to become the majority.

**Comment by muarB** [comment]
Ok thanks.  I don't know the mechanics.  I'm not used to it taking 2 missionary clicks so early in the game.

**Comment by muarB** [comment]
But just to clarify, the pantheon is part of zoroastriansm, it was my pantheon.  Seems strange that it doesn't just upgrade with one mission.

**Comment by muarB** [comment]
It's normal to need 2 missionary missions to upgrade from your pantheon to your newly founded religion?  Ok then.
