### ISSUE TITLE
Krakatoa missing

### ISSUE THREAD

**Issue by F0rst1** [LoneGazebo/Community-Patch-DLL#3016]
_1. Mod version (i.e Date - 4/23):_

1/26

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I haven't seen Krakatoa in a very long time. It was already missing before the natural wonder rework was done and hasn't reappeared since. My friend has a similar experience. Together we have played probably hundreds of hours in the last 6+ months and haven't seen Krakatoa. Both of us play on continents map.

_4. Steps to reproduce (optional):_

**Comment by Enrico-Swagolo** [comment]
Now that I think about it, I haven't seen Krakatoa in more than half a year too. I've seen lots of Fountains of Youth etc but no Krakatoas.

**Comment by LoneGazebo** [comment]
Krakato-oh no! I'll look.

G

**Comment by jimmymcperson** [comment]
As someone who has only ever played CBP (never vanilla), Kraka-what?
