### ISSUE TITLE
AI are not guarding their settlers, letting their first settler get killed

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#3017]
_1. Mod version (i.e Date - 1/26):_

_2. Vox Populi with EUI, Ingame Editor, Really Advanced Setup, Flag Promotions

_3. Error description: Seen it happen numerous times, I meet an AI leader who has 0 cities because they have just let their settler get killed and don't bother getting them back. Screenshot here:

http://images.akamai.steamusercontent.com/ugc/97227270607542960/238D81489DC6C28C79789F3976C719A0692496C5/

**Comment by LoneGazebo** [comment]
Sounds like you are using an odd map. never seen this.

**Comment by RockettSJ** [comment]
Yeah I use Planet Simulator but I'm not too happy with it. Rather off-topic but what map do you use/recommend?

**Comment by ilteroi** [comment]
so who killed the settler? i don't see any barbarians and anyway they are supposed to settle by the third turn at the latest ...

**Comment by RockettSJ** [comment]
@ilteroi A barbarian did take the settler, Casimir just wasn't guarding it. (It's in an unexplored tile on that image)

As Gazebo said, it's likely a map issue

**Comment by Vyyt02** [comment]
Also using PlanetSimulator and never seen such thing (haven't played with the 1/26 version much yet though).

**Comment by bryan317** [comment]
I'd like to add I've experienced this bug since 1-26 thru the 2-6 version.  I'm using  Continents Plus.  Large Map.  Happens every game.

**Comment by ilteroi** [comment]
cannot reproduce. just tried on continents plus. 30 cities founded, only one settler captured.

**Comment by bryan317** [comment]
I'm not clear on all the exact rules, but even with the single settler captured, was the player eliminated from the game? I'm not sure if they're given a chance to have their settler liberated or not.  But isn't even one settler captured a bit strange early game?  To be overrun by barbarians?

**Comment by bryan317** [comment]
For the record i played thru once to capture the settler and they still were not eliminated.  If anyone finds themselves here,  changing the option in the mod folder to not allow settler movement at turn zero appears to be a workaround.  I'm enjoying a game now with no issues.

**Comment by ilteroi** [comment]
sorry i wasn't very precise. the captured settler was not a starting settler.
