### ISSUE TITLE
AI plot buying

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3018]
the AI currently almost never buys a plot, even in situations like this (the mountains prevent natural border growth towards the high-food tiles in the south west):

![image](https://cloud.githubusercontent.com/assets/1358966/22525445/783fd2b4-e8c7-11e6-8868-f70cd84fd83b.png)

anyway the key setting here is AI_GOLD_PRIORITY_MINIMUM_PLOT_BUY_VALUE. the default value is 150 and that is even confirmed in CoreChanges.sql, but then CSD overwrites it with 700, which is way too high in my opinion. why is that?

for reference, the wheat tile has a value of 133.

**Comment by LoneGazebo** [comment]
CSD’s override shouldn’t be overriding anything, I’ll look. The code does work, not sure why the AI isn’t buying as much.
