### ISSUE TITLE
Motherland Calls makes City Disappear

### ISSUE THREAD

**Issue by muarB** [LoneGazebo/Community-Patch-DLL#3019]
_1. Mod version (i.e Date - 4/23):_

1/26
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

In every version for the past few months, when I construct Motherland Calls, the city graphics disappear.  I kept forgetting to mention it here.  There's just the city flag with information and just empty terrain where the city once was.  I haven't verified the bug still exists in this 1/26 version but unless it was fixed it's probably still there.  I'm guessing there's some error with the graphic of the statue that would be displayed next to the city.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Huh that makes so much sense why adopting order always made my capital disappear in confusion!

**Comment by muarB** [comment]
I think there's one other wonder that does it but I can't remember which.  My current game will probably have it happen. Could be 4 evenly matched civs into the industrial age, pretty rare.
