### ISSUE TITLE
AI help request is unreasonable.

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#302]
http://steamcommunity.com/profiles/76561198009635802/screenshot/46506585706635807

Poland asked me to give -8001 gpt which results in money sucking into my treasury from void.
Then, they asked me to declare war on Aztec.

Thank you.

**Comment by Hokath** [comment]
yes I got this too but Askia also wanted my Sugar. The cheek.

**Comment by XplosiveLun** [comment]
Sometime, after accepting a deal which usually seems unfavoruable to AI, the deal will not take effect. AI would say "Anything Else?" instead of "You drive a hard bargain....".

Also, I noticed The compatibility module is not updated to version 6-2.

**Comment by XplosiveLun** [comment]
I tried to test if this glitch is caused by mod conflicts, I found that only using CPP mods (CP, CBP, C4DP, CSD) and clearing cache still cause problem.
