### ISSUE TITLE
Too much water-walking

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#3021]
_1. Mod version (i.e Date - 4/23):_ 1/26.1

![8930_20170202174616_1](https://cloud.githubusercontent.com/assets/1131228/22551120/45a1442e-e975-11e6-8ffb-250c22d28ef7.png)
![8930_20170202182624_1](https://cloud.githubusercontent.com/assets/1131228/22551123/4d3dd8d2-e975-11e6-9b5c-a301bacdd584.png)

**Comment by LoneGazebo** [comment]
@ilteroi I've seen this a few times too. Jump valid not checking for water and/or embarking properly?

**Comment by ilteroi** [comment]
hmm. need to check ...

**Comment by Enrico-Swagolo** [comment]
I've seen that too, first time it was by a Catholic Monthezuma. Seems he has learnt a lot from the teachings of Christ.
