### ISSUE TITLE
Aggressive civs aren't building enough walls

### ISSUE THREAD

**Issue by ashendashin** [LoneGazebo/Community-Patch-DLL#3022]
_1. Mod version (i.e Date - 4/23):_
1/12(seeing it in 1/26 too)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
![20170124023642_1](https://cloud.githubusercontent.com/assets/21032378/22557979/209edcbc-e93a-11e6-8cee-62e0eefbfd6f.jpg)

Most civs do fine on building defenses, but big ones keep holding them off for insane amounts of time. I'm doing a Venice game right now and it's really frustrating to wait for my purchased walls to come up. It's standard to immediately build walls on conquered cities. Even leaving it to frontline cities only would leave the rest of the empire to easily be sliced through.

Oh and just something I'd like to add that's not currently worth its own post:
![20170124024118_1](https://cloud.githubusercontent.com/assets/21032378/22558017/3aa1c3a4-e93a-11e6-9810-3c3877d31209.jpg)

**Comment by LoneGazebo** [comment]
@ashendashin what's the problem in #2?

**Comment by ashendashin** [comment]
Those musketmen made up for almost the entire eastern defense. Attila was warring a bunch of western civs so I think his best units were there, but it's weird that most of the frontline was muskets for the whole campaign.

**Comment by LoneGazebo** [comment]
They were probably in queue for upgrades, but the AI prioritizes fighting/frontline units.

**Comment by ashendashin** [comment]
@LoneGazebo I thought about the 2nd pic some more and none of it turns out right. Why is it that whenever the AI builds a certain unit in excess, it's ranged? They soften up targets for removal, but that's mostly where their role ends. Melee units are usually what makes up the bulk of my armies.

**Comment by Radost** [comment]
On defensive, ranged spam is superior to melee. It means 2 lines constantly doing damage while not taking any back, whereas melee units require constant reshuffling.

**Comment by ashendashin** [comment]
Yes but to fill in an entire defensive line I'd rather have melee as a higher priority to prevent breakthroughs. Fortification is no joke against an aggressor and the medic promotions makes up for shuffling. Range, as useful as it is, always comes second. This is especially important when you consider that the AI so often squanders their ranged units.

**Comment by ashendashin** [comment]
Here's a save from my current game (Community Events, Really Advanced Setup, and Enhanced City-States)
[Enrico Dandolo_0260 AD-1150.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/750479/Enrico.Dandolo_0260.AD-1150.zip)
Both the Mongols and my own puppets are holding off on walls. I forgot to turn logging back on but I can try and get some, if needed.

**Comment by saamohod** [comment]
Sweden in my current game doesn't like building walls either. About half of their cities have no walls, and those are not fresh cities. Seems like AI doesn't prioritize walls enough.
Mods used: FlagPromotons v.7

Savegame 
[no walls.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/762367/no.walls.zip)
![20170209031545_1](https://cloud.githubusercontent.com/assets/16341598/22765069/eddc7ca2-ee76-11e6-9148-c0a491f8fffb.jpg)
