### ISSUE TITLE
Tourism Modifiers do not affect Historic Event Tourism

### ISSUE THREAD

**Issue by Ta1kavarpu** [LoneGazebo/Community-Patch-DLL#3023]
Mod version: 1/26

Issue:
Tourism modifiers (from open borders, shared religion etc.) have no effect on tourism gained from historic events. It's pretty easy to test by buying a great person with faith or building a wonder with a Great Engineer.

If this is intentional, then my bad. However, considering that the vast majority of tourism is generated by historic events, these modifiers seem rather negligible right now.

**Comment by LoneGazebo** [comment]
They are not supposed to.

**Comment by LoneGazebo** [comment]
Although I could change that.
