### ISSUE TITLE
JFDLC CTD

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3024]
Using the latest VP, I have a CTD traced to GetNumFreeBuilding() from a building I add in one of my mods (I don't use GetNumFreeBuilding() in the mod).

![image](http://i.imgur.com/mBJxDXp.png)

Theres nothing unusual about the building, however, and others that are essentially the same don't cause any issues. So, any ideas what this means, or what could be the cause?

**Comment by LoneGazebo** [comment]
Best guess is that you are throwing a MAX_INT or a non-integer value into the table.

**Comment by JFDaly** [comment]
Hm, well, I managed to subvert this error by changing the HasBuilding() check to GetNumBuilding() > 0, but I'm not sure why this would be necessary or why it would solve the issue?

**Comment by LoneGazebo** [comment]
@JFDaly what caching values would you need?

PlagueLevel
LoyaltyLevel

?

**Comment by JFDaly** [comment]
These are the things I would need:

city:GetResistanceCounter()/SetResistanceCounter()/ChangeResistanceCounter()

city:GetPlagueTurns()/SetPlagueTurns()
city:SetPlagueCounter()/GetPlagueCounter()/ChangePlagueCounter()
city:IsPlague() -- checks if GetPlagueTurns() is greater than 0

city:GetLoyaltyLevel()
city:GetLoyaltyCounter()/SetLoyaltyCounter()/ChangeLoyaltyCounter()
city:GetDisloyaltyCounter()/SetLoyaltyCounter()/ChangeLoyaltyCounter() -- if we need to be conservative, my system can be changed slightly and this would be unneeded

These are all the components that use dummy buildings as counters and registers.

**Comment by LoneGazebo** [comment]
Definitely doable. Simple integers are easy to work with. I can also make you an enum set with states:

I.e. LoyaltyTypes GetLoyaltyState()

**Comment by JFDaly** [comment]
Awesome, this will help with stability alot. I'll write up a list of the functions needed and get back to you.

**Comment by LoneGazebo** [comment]
Sounds good.

**Comment by LoneGazebo** [comment]
If you want states just give me the list of potential states too.

**Comment by JFDaly** [comment]
Colonies:

**city:IsColony()** --returns boolean, not strictly needed but as I use a custom function to check this a lot (which requires making sure the required file is included) it would be really convenient.
**city:SetIsColony(true/false)** --either this, or a IsColony tag in Buildings similar to the Capital tag used by the Palace, as a Colony is defined by having a Governor's Mansion. Whichever is easier/more efficient.

Provinces:

**city:GetProvinceLevel()**
**city:SetProvinceLevel(ID)** -- this corresponds to a Province ID in the database. Would be useful if it can default to 0, but -1 works.
**GameEvent.ProvinceLevelChanged(playerID, cityID, oldProvinceLevelID, newProvinceLevelID)** -- triggers when SetProvinceLevel() is used.

Crimes:

**city:GetOrganizedCrime()**
**city:SetOrganizedCrime(ID)** -- this corresponds to an Organized Crime ID in the database. Will need to support -1, i.e. no Organized Crime.
**city:HasOrganizedCrime()** -- returns true if GetOrganizedCrime ~= -1

Happiness:

**city:ChangeResistanceCounter(value)**
**city:SetResistanceCounter(value)**
**city:GetResistanceCounter()**

Health:

**city:ChangePlagueCounter(value)**
**city:SetPlagueCounter(value)**
**city:GetPlagueCounter()**

**city:GetPlagueTurns()**
**city:ChangePlagueTurns(value)** 
**city:SetPlagueTurns(value)**
--It would be excellent if Plague Turns could decay by 1 automatically each turn, but otherwise I can do this manually.

**city:GetPlagueType()**
**city:SetPlagueType(ID)** -- this corresponds to a Plague ID in the database. Will need to support -1, i.e. no Plague.
**city:HasPlague()** -- returns true if GetPlague ~= -1

Loyalty:

**city:ChangeLoyaltyCounter(value)**
**city:SetLoyaltyCounter(value)**
**city:GetLoyaltyCounter()**

**city:ChangeDisloyaltyCounter(value)**
**city:SetDisloyaltyCounter(value)**
**city:GetDisloyaltyCounter()**

**city:GetLoyaltyState()**
**city:SetLoyaltyState(ID)** -- this corresponds to a Loyalty ID in the database, and it would be useful to default to 0 (Neutral). I'm not sure how states work in the DLL, but there are 5 different Loyalty states: LOYALTY_JFD_NEUTRAL, LOYALTY_JFD_PATRIOTIC, LOYALTY_JFD_ALLEGIANT, LOYALTY_JFD_REBELLIOUS, and LOYALTY_JFD_SEPARATIST.
**GameEvents.LoyaltyStateChanged(playerID, cityID, oldLoyaltyID, newLoyaltyID).** -- triggers when SetLoyaltyState() is used.

I added a few extra areas to cover, but this basically covers my Cities in Development mod in the way that Rise to Power was covered last year. Let me know if there are bits we need to cut out, otherwise, I really appreciate moving these to the DLL, as I'm curerntly working to merge CiD and RtP (and ExCE), so this is really well-timed.

Let me know if theres anything else you need, and of course please take your time adding anything here.

**Comment by LoneGazebo** [comment]
Alright, completed. Easier than it looks. Posting a debug DLL now. All lua commands and hooks are identical to your requests above. Plague turns decrements by 1 every turn if above zero.
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/755779/CvGameCore_Expansion2.zip)

**Comment by JFDaly** [comment]
Amazing, thank you. All the functions work, the only issues are that in:

GameEvent.ProvinceLevelChanged(playerID, cityID, oldProvinceLevelID, newProvinceLevelID)
GameEvents.LoyaltyStateChanged(playerID, cityID, oldLoyaltyID, newLoyaltyID).

the newProvince/LoyaltyID don't return the ID properly.

And could you please set it so that GetResistanceCounter/GetPlagueCounter/GetLoyaltyCounter/GetDisloyaltyCounter default to 0 instead of -1.

I'll let you know if something goes wrong as I implement these properly into the mod, but otherwise thanks muchly :3

**Comment by LoneGazebo** [comment]
Functions look correct on my end:

ProvinceLevel: GAMEEVENTINVOKE_HOOK(GAMEEVENT_ProvinceLevelChanged, getOwner(), GetID(), m_iProvinceLevel, iValue);

Loyalty: GAMEEVENTINVOKE_HOOK(GAMEEVENT_LoyaltyStateChanged, getOwner(), GetID(), m_iLoyaltyStateType, iLoyalty);

**Comment by JFDaly** [comment]
Oh, right, sorry, I meant the oldProvince/LoyaltyLevelID. I get something like 1835183928 in place of the old ID, but possibly I'm misunderstanding the use os the states?

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/755962/CvGameCore_Expansion2.zip)

See if this fixes/changes anything.

**Comment by JFDaly** [comment]
Nope, same issue. Its not major, I can work with just the new ID as these states are incremental. Thanks for changing the Counter defaults.

**Comment by LoneGazebo** [comment]
does it function correctly after one set?

**Comment by JFDaly** [comment]
No, same issue each time.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/756011/CvGameCore_Expansion2.zip)


Try this'n.

**Comment by JFDaly** [comment]
Perfect, that fixes it. Thanks.

**Comment by LoneGazebo** [comment]
Cool. I explicitly defined it instead of relying on the city variable. Let me know if you need anything else.

Death to all dummy buildings! :)

**Comment by JFDaly** [comment]
Just for conveniences' sake, could you please add:

**city:HasLoyaltyState(ID)**
**city:HasProvinceLevel(ID)**

These will return true/false if GetLoyaltyState/GetProvinceLevel corresponds to the specified ID. 

Thank.

**Comment by LoneGazebo** [comment]
Done.
