### ISSUE TITLE
Weird Peace Refusal

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3026]
I'm noticing this on a few autoplays that I take over by the middle of the game that if there is a city that the AI really favors in the war, they'll extend the war in an attempt to recapture that lost city, however I could just capture any other city that isn't that "favored" city and I could immediately make peace.

**Comment by LoneGazebo** [comment]
There's no 'really favored' cities in war like that.
