### ISSUE TITLE
City states on mountains

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#3027]
_1. Mod version (i.e Date - 4/23):_

26/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

CS occasionally start the game with their settler on a peak. There it remains until ranged barbs arrive and kill them.
A few versions back, CS could actualy found on top of peaks like the Inca, which was weird but fine with me.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization

4. Screenshots (optional):
![20170131194007_1](https://cloud.githubusercontent.com/assets/16065630/22603046/0c354524-ea46-11e6-953a-f61e75c675ed.jpg)

**Comment by TechpriestEnginseer** [comment]
tfw you will never fight the city-states people on the mountain top.

**Comment by LoneGazebo** [comment]
I've never seen this. Assuming weird map script?

**Comment by TechpriestEnginseer** [comment]
It would be nice if city-states could settle on mountains though right like before?

**Comment by ilteroi** [comment]
even if they spawn on a mountain, they should be able to move away from it ...

**Comment by Der-Zorn-Gottes** [comment]
They can - I poked them once with an archer and they moved off, settling the next turn. 
However, if left alone with the barbs, they will just die eventually.

The mapscript is highlands, so nothing too exotic.
