### ISSUE TITLE
Rialto District Bad Tooltip

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3028]
"caps at city-states ever alive" should be changed to "currently alive" because I noticed my delegates were going down despite me making more and more GPT. Then I realized Mongolia was taking over them like biscuits.

**Comment by LoneGazebo** [comment]
int iGPT = GET_PLAYER(ePlayer).GetTreasury()->CalculateGrossGold();
			if(iGPT > 0)
			{
				iGPTVotes = (iGPT / iVotesPerGPT);
				//Capped at 1/4 # of minor civs ever in game.
				int iCap = GC.getGame().GetNumMinorCivsEver();
				iCap /= 4;
				if(iCap <= 0)
				{
					iCap = 1;
				}
				if(iGPTVotes > iCap)
				{
					iGPTVotes = iCap;
				}
				iVotes += iGPTVotes;
			}``

**Comment by LoneGazebo** [comment]
Code looks fine to me...
