### ISSUE TITLE
Events in EventPolicy

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3030]
Only applies the policy if it has a policy branch which dummy policies don't possess unfortunately..

I know has the same issue due to the same bug.
https://github.com/LoneGazebo/Community-Patch-DLL/issues/2465

But I have absolutely no idea what his solution was beside using Lua. Because I know for sure the policy is given, but the policy's effects aren't applied. (There is a building that requires the dummy policy, and when the event is activated the building can be built, but no other effects of the policy is there!)

Or what does a dummy policy needs in order for EventPolicy to be exerting all of its effects? I have the usual Policies (Type, Description, PortraitIndex, IconAtlas, IconAtlasAchieved)

**Comment by LoneGazebo** [comment]
Branch should not matter - I'd ask that guy what he did.

**Comment by TechpriestEnginseer** [comment]
Resolved based on the fact that no one ever used EventPolicy at all and just preferred the Lua method.
