### ISSUE TITLE
Instant defeat no other mods enabled 

### ISSUE THREAD

**Issue by xxjaylutherxx** [LoneGazebo/Community-Patch-DLL#3031]
_1. Mod version (i.e Date - 4/23):_

latest mod vox populi with eui

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

whenever I start a game i am instantly defeated on turn one.

_4. Steps to reproduce (optional):_

removed all other mods, cleared game cache reinstalled civ after deleting game folder and steam files. 

[ModdedSaves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/752083/ModdedSaves.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/752084/Logs.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Make sure your version of civ is up to date (.279)

**Comment by bigcat88** [comment]
Communitas map and 43 civ? 
Have this trouble with communitas huge map and 30-33 civ + 20 CS. There is 40-60% chance that u will be defeated on first turn. Don't tested on other map types, but maybe its a map script bug.

**Comment by JFDaly** [comment]
I've also had this issue, mostly on pre-created maps. Maps generated via script seem to not cause this issue.

**Comment by LoneGazebo** [comment]
Some of the changes whoward made years ago to the VMC DLL had a deleterious effect on pregen maps.

**Comment by xxjaylutherxx** [comment]
Thanks for the advice. I installed the Not Yet Another Earth Map Pack and everything is working fine now. Im guessing it was indeed issues with pre-created maps. Thanks again!
