### ISSUE TITLE
Naval Units take damage from hostile Citadels

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#3032]
Even though they can't pillage them or heal inside an enemy territory without any of the 2 sources of healing.

**Comment by TechpriestEnginseer** [comment]
Pretty sure this is intentional and I believe naval units can enter citadels and forts and pillage them no?

**Comment by Radost** [comment]
They can't enter hostile citadels.

**Comment by TechpriestEnginseer** [comment]
Then you know what that means get some embarked units and destroy the fort from the inside.

**Comment by Radost** [comment]
Thanks, captain obvious. But the point is land units can rush and pillage it, and they can heal either naturally, albeit very slow, or by pillaging tiles. And there are a lot more tiles to pillage on land than on water.
It either can damage naval units and can be pillaged by them or can't damage and can't be pillaged.

**Comment by LoneGazebo** [comment]
Citadels = forts with coastal artillery. Makes sense to me.

**Comment by Radost** [comment]
Coastal forts which are somehow impervious to be destroyed by naval units?
