### ISSUE TITLE
God King culture to all cities

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#3033]
_1. Mod version (i.e Date - 4/23):_

2/4

_2. Mod list (if using Vox Populi only, leave blank):_

normal full VP instal and nothing else

_3. Error description:_ 

God-King pantheon provided culture on cities beyond capital (instantly +8 culture on freshly founded city)

_4. Steps to reproduce (optional):_

Take God King, Found cities :)

links to screenshot:
http://imgur.com/zXt6UgW
http://imgur.com/bIy1zVd

**Comment by RandomNub** [comment]
link to screenshot

http://imgur.com/zXt6UgW

**Comment by LoneGazebo** [comment]
I'll look.
