### ISSUE TITLE
Is this a bug? Can't purchase university with faith reformation belief

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#3034]
Version: Latest Feb 4th with EUI

Additional mods: Ingame Editor, Flag Promotions, Really Advanced Setup

Two screenshots here. It did work in my capital and another city, but not these newest cities.

![inca1](https://cloud.githubusercontent.com/assets/8049731/22626248/239ae190-eba1-11e6-8e26-b0763aca9e2e.jpg)
![inca2](https://cloud.githubusercontent.com/assets/8049731/22626249/278f3288-eba1-11e6-8edb-00f709945efd.jpg)

**Comment by LoneGazebo** [comment]
I'll look.
