### ISSUE TITLE
Research never finishes

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#3035]
_1. Mod version (i.e Date - 4/23):_
4-2-1

_2. Mod list (if using Vox Populi only, leave blank):_
Clock

_3. Error description:_ 
A technology doesn't get researched, even after the beakers are full.

_4. Steps to reproduce (optional):_

I was playing Germany. I completed enough beakers to finish Bronze Working, but turns and turns passed, showing that only 1 turn was left.
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by cdanger341** [comment]
I can confirm this bug. Just got the 4-2-1 hotfix and started a new game as Spain. Everything was going as expected except as I went to research Construction it "overshot" the Beakers requirement and showed as having 343/325 Beakers without having actually unlocked the technology. I let the game play for a few extra turns and it continued to accumulate Beakers without unlocking the technology. I tried switching to another technology for a turn and then switching back, and it still continued to "overresearch" Construction without ever unlocking it.

I am attaching my save file. No other mods installed but RED Modpack.
[Isabella_0134 BC-0650.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/753342/Isabella_0134.BC-0650.zip)

**Comment by Jotaro31400** [comment]
I've got the same issue, I'm stuck with bronze working, I don't know why I can't upload my save file :(

**Comment by Enrico-Swagolo** [comment]
Confirming, can't research Calendar

**Comment by bompus** [comment]
Same issue. Seems to have stopped at Construction and is now stuck. I have research past required on both Construction and Military Theory, but it never completes.

It won't let me attach the zip files, so grab them here. https://www.dropbox.com/s/zxraa5ld9u93qwh/Dido_0117%20AD-1140.zip?dl=1
https://www.dropbox.com/s/82e5o3bxug79ked/Logs.zip?dl=1

**Comment by LoneGazebo** [comment]
I'll look.

**Comment by LoneGazebo** [comment]
I see the issue - recursion in a spot. Fixing now. Hotfix shortly.
