### ISSUE TITLE
Military Near City State weirdness

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#3036]
_1. Mod version (i.e Date - 4/23):_2/5 hotfix

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP
Enginseer's version of E&D and Community Events
JFD Cultural Diversity Core
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Celtic City Names, Iroquoian City Names, Randomize City Names
My own thing that does various things SQL type stuff
Ice Free Coasts
WHoward: Map Pins, Auto Map Pins, Diary, Enhanced Demos
Starting Scout
Tectonic Map

_3. Error description:_ 
The CSes in pictures 1 and 2 are giving me +160 points each in military near CS for tributing, the one in picture 3, where my military is, only +40. And unless its far away, they don't have a larger army themselves, certainly to that degree, if that matters.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![mn1](https://cloud.githubusercontent.com/assets/16260521/22638048/c1e6acf4-ec13-11e6-9e6d-14beaf5984cd.jpg)
![mn2](https://cloud.githubusercontent.com/assets/16260521/22638057/c6e50dc2-ec13-11e6-8f38-57fc624c1aa3.jpg)
![mn3](https://cloud.githubusercontent.com/assets/16260521/22638092/f81158ba-ec13-11e6-8d62-84d54166920c.jpg)

**Comment by pandasnail** [comment]
So literally the next turn, even tho my units were barely moved, it jumped to +90, but that's still less than the two +160s.

**Comment by pandasnail** [comment]
Now that the diff isn't soooooo big, maybe its just that JFD CulDiv starts Kiev with Walls and nothing weird.

**Comment by LoneGazebo** [comment]
Sounds like that's it. Also keep in mind that CSs only weigh against known civs.
