### ISSUE TITLE
Zealotry only works for capital

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3039]
_1. Mod version (i.e Date - 4/23):_

currentt
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Can't buy with faith outside of capital.

**Comment by JFDaly** [comment]
You've spread your religion to your other cities? You can only Faith purchase when the city has that belief in their majority religion.
