### ISSUE TITLE
Monopoly modifier(rationalism) not updated

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3040]
_1. Mod version (i.e Date - 4/23):_
last

_2. Mod list (if using Vox Populi only, leave blank):_
The Reformation of the World Congress

_3. Error description:_ 
Got only one modifier for growth, except 2. Has monopoly on sugar and salt.(Total 55% growth)

_4. Steps to reproduce (optional):_
First I have only salt, was 20% as usual. Then I take rationalism policy and was 35%, as excepted.
But later when I got sugar monopoly from conquest, I see only 55% modifier. Looks like modifier policy don't apply, after it was taken.

[monopoly mod.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/755329/monopoly.mod.zip)

**Comment by LoneGazebo** [comment]
It is working as designed, as it is supposed to increase the total monopoly mod by a %, not each monopoly. I should update the policy info.
