### ISSUE TITLE
Golden Age Points adding during Golden Ages

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3042]
A few people have brought this up, so I thought I'd ask about it. 

It seems that Golden Age Points as added through the unified yields project (i.e. YIELD_GOLDEN_AGE_POINTS) continue to add toward the Golden Age Progress Meter even during a Golden Age. I was wondering if this was intentional or an oversight, and in either case whether it can be fixed/turned off?

**Comment by LoneGazebo** [comment]
This is intentional, yes. If needed I can disable it.

**Comment by JFDaly** [comment]
That would be useful, at least as a setting to be able to disable/enable as needed.

**Comment by LoneGazebo** [comment]
It'll be in the next CP. BALANCE_NO_GAP_DURING_GA in custom mod options.
