### ISSUE TITLE
Krakatoa is back but is useless

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3043]
_1. Mod version (i.e Date - 4/23):_latest EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  Not sure if it's got something to do with the map script, but I'll report it just in case. Today I saw Krakatoa after quite a long break (not sure I ever saw it in VP), but it's surrounded by water and cannot be used by anyone. I used Tectonics script for map generation.
 EDIT. There exists a minimod called Krakatoa Fix, but I didn't use it. It might help.

![20170207012343_1](https://cloud.githubusercontent.com/assets/16341598/22670969/83159ece-ecd4-11e6-8c23-d9bb7efa8053.jpg)

**Comment by Radost** [comment]
Only communitas map cares about NWs being in sensible spots. All others can put them wherever.
