### ISSUE TITLE
Atlatlist promotion doesn't transfer to upgrade unit. Intended?

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3044]
_1. Mod version (i.e Date - 4/23):_
latest EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Maya is one of the civs I haven't played yet, therefore it may be intended. Atlatlist special promotion Atlatl Strike is not transferred to the upgrade unit (crossbowmen).

**Comment by LoneGazebo** [comment]
Intended.

**Comment by Radost** [comment]
And the purpose of that intended feature is...?

**Comment by LoneGazebo** [comment]
Not all UU promos carry over.

G
