### ISSUE TITLE
More Luxury's additional luxuries don't have monopoly effects.

### ISSUE THREAD

**Issue by aldebaran1997** [LoneGazebo/Community-Patch-DLL#3045]
_1. Mod version (i.e Date - 4/23):_
2-5-1 full VP 43-civs version with EUI. (I think this problem happened since 1-26 or earlier.)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
There is no More Luxury's additional luxuries' monopoly effects though they are generated on the map. They aren't displayed on the Corporation Overview and their Civilopedia items and PlotHelpTexts(?) are missing monopoly effect description. bigcat88 has the same problem.

_4. Steps to reproduce (optional):_
Install full VP 43-civs version with EUI through auto installer. -> Run Civ 5 and activate all VP mods. -> Start a game and check the Corporation Overview and Civilopedia, etc.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
[Report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/756676/Report.zip)

**Comment by bigcat88** [comment]
Yeah, don't see amber/tea/coral in monopoly list. Just right now started a new map, open it with IGE, on map see them and in monopoly list no.

**Comment by ashendashin** [comment]
Same here. Took me so long to load up without instant defeat too...

**Comment by LoneGazebo** [comment]
[(1b) 43 Civs CP.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/758825/1b.43.Civs.CP.zip)

Try this.

**Comment by aldebaran1997** [comment]
It still doesn't work. I try to replace CP's dll with this one, or not. But it doesn't work, either.

**Comment by bigcat88** [comment]
+

**Comment by aldebaran1997** [comment]
Oh, I figured out AssignStartingPlot.lua has to be pulled out of the MoreLux folder. Now it works really well, thanks!
