### ISSUE TITLE
Request: AllowsProductionTradeRoutesAllCities

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3046]
If we're on a quest to eliminate dummy buildings, do you think an **AllowsProductionTradeRoutesAllCities** tag would be possible? This would essentially function like the Workshop's AllowsProductionTradeRoutes, but enable Production Trade Routes in all cities (I use it for a wonder in RtP).

Thank.

**Comment by LoneGazebo** [comment]
Yup.
