### ISSUE TITLE
CTD after turn 446

### ISSUE THREAD

**Issue by DarkoDarkovic** [LoneGazebo/Community-Patch-DLL#3047]
1. Mod version (i.e Date - 4/23):   Vox Populi (1-26-1)

2. Mod list (if using Vox Populi only, leave blank):   really_advanced_setup__v_15

3. Error description:  Game crashes after turn 446. I can go back to earlier save. Tried different things (like different moves, declaring war etc.) in hopes of preventing the crash but it always crashes on that turn.  

4. Steps to reproduce (optional): Load game, Click next turn.

---------------------------

Files: 

[files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/758318/files.zip)

**Comment by LoneGazebo** [comment]
You are on an old version.

**Comment by DarkoDarkovic** [comment]
I updated and it's still the same. I think the AI gets too big and the game just crashes. I managed to prevent the crash with Ingame Editor (v 39) by deleting 3 citys of AI but now after about 40 turns AI rebuilt citys and crashed happened again.
