### ISSUE TITLE
"God of All Creation" pantheon not working

### ISSUE THREAD

**Issue by Nok-26** [LoneGazebo/Community-Patch-DLL#3048]
_1. Mod version (i.e Date - 4/23):_
(2-6)

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi,
City States Evolved (v 3),
Krajzen's Great Musicians / Artists / Writers Pack,
Historical Religions Edit (v 45),
JFD's Cultural Diversity (core) (v 13) [effects disabled, thou],
JFD's Cultural Diversity (soundtrack)

_3. Error description:_ 
I enabled the "anybelief" option in Community Patch and started a game with 15 civs on huge. Lots of pantheons were founded and mine was kinda late. Problem is, I receive no bonus from God of All Creation, except for the extra 2 faith from the palace. This happened in a previous game once, but the bonus somehow appeared later on (first the culture bonus, then the happiness bonus).

No religion has been founded, and 14 pantheons were founded (including mine).

This is the turn before founding a pantheon (took from autosave, then I kept on playing and still had no extra culture nor happiness).
[beforeAllCreation.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/758933/beforeAllCreation.zip)

These are the logs and the actual save game after founding the pantheon.
[GodOfNoCreation.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/758907/GodOfNoCreation.zip)

_4. Steps to reproduce (optional):_

**Comment by Nok-26** [comment]
How is this already fixed? I'm pretty sure I have the most recently released version :P
https://forums.civfanatics.com/threads/new-hotfix-version-february-6th-2-6.610066/

**Comment by Edaka** [comment]
Have you tried the file from this post? 
https://forums.civfanatics.com/threads/new-hotfix-version-february-6th-2-6.610066/#post-14649615

**Comment by Nok-26** [comment]
Oh, somebody had the same problem and it was fixed. I can't test now, though. Thank you very much.
However, "already fixed" makes it look like it was fixed in an bundled release or something, kind of misleading. :P
