### ISSUE TITLE
Compressing DDS files

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#305]
I've compressed all dds images from CP using dxt1 compression with 1 bit alpha. For some files dxt5 compression with proper alpha was used to keep image quality.
https://dl.dropboxusercontent.com/u/28753474/Community%20Patch%20dds.rar

These 2 files are not used by CP: CommunityArt256 5.dds, CommunityArt256 C.dds.

I checked dds files from vanilla game and some of them are not compressed too. Should CP fix it?

**Comment by LoneGazebo** [comment]
Excellent, I'll include. Did the compression affect the file quality? I use gimp, and dxt5 compression wrecks the quality in that program.

**Comment by LoneGazebo** [comment]
Regarding latter point - we can, but it probably won't make much of a size difference. In the end it'd just make the CP bigger, and civ minimally smaller.

**Comment by LoneGazebo** [comment]
Added files - look fine, however they appear to have offset about 1-2 pixels to the right.

**Comment by qqqbbb** [comment]
I use gimp too and I never had any problems with image quality. After compressing to dxt5 you should not notice any difference in quality. Try updating dds plugin.

There is no offset. What you noticed is difference between 8 and 1 bit alpha channel. With 1 bit alpha (dxt1) a pixel can be either 100% opaque or 100% transparent. With 8 bit alpha (dxt5) pixel can has any level of  transparency. Compressing from dxt5 to dxt1 reduces file size to 50%.

**Comment by qqqbbb** [comment]
Here is compressed dds files from vanilla game.
https://dl.dropboxusercontent.com/u/28753474/compressed%20dds.rar
File size reduced to 10% after compression.

**Comment by LoneGazebo** [comment]
Seems that unit flags in strategic view become blank with compression. Mind checking for me?
G

**Comment by qqqbbb** [comment]
fixed unit flags: https://dl.dropboxusercontent.com/u/28753474/CP%20unit%20flags.rar
Looks like unit flag dimensions have to be power of 2 if you compress the image.

**Comment by qqqbbb** [comment]
About replacing vanilla files. If CP gets a proper installer, we can just copy compressed images to assets folder and set LooseFilesOverridePak = 1 in config.ini.

**Comment by qqqbbb** [comment]
You forgot to include compressed unit flags

**Comment by qqqbbb** [comment]
Some compressed images were not displayed becuase of their dimensions. I rescaled them.
https://dl.dropboxusercontent.com/u/28753474/Community%20Patch%20fixed%20dds.rar

You did not include fixed unit flags in the latest version.

**Comment by LoneGazebo** [comment]
Yeah, I'll include them in this next one. Sorry!
Thanks again for your hard work. If it wouldn't be too much trouble, I'd love to see the same compression applied to CSD's artwork, which is almost as numerous as CBPs!
G

**Comment by qqqbbb** [comment]
compressed dds files from CSD: https://dl.dropboxusercontent.com/u/28753474/Compressed%20CSD%20dds.rar

ProjectUN.dds is copy of wonderconceptun.dds and can be removed.
citizenCivilServant.dds is not used.

**Comment by LoneGazebo** [comment]
Got it! Thanks.

**Comment by LoneGazebo** [comment]
The CSD art works at all but the smallest size - the smallest  ones (i.e. tech tree ones) are blank.

G

**Comment by qqqbbb** [comment]
I tested them and everything was fine. Did you copy files from art/xml folder from my archive?

**Comment by LoneGazebo** [comment]
Yep. I'll try again, sometimes Modbuddy is evil.
G

**Comment by qqqbbb** [comment]
Updated compressed art for CSD:https://dl.dropboxusercontent.com/u/28753474/compressed%20art%20CSD.rar. Removed a duplicate file. EmbassyAtlas256.dds can now be deleted.

**Comment by qqqbbb** [comment]
Vanilla game has a lot of uncompressed dds files. You wanna include compessed copies in CP?
