### ISSUE TITLE
GameEvents.ResolutionResult

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3052]
Can this GameEvent be fired after the resolution is passed, not before? or at least somewhat includes the proposing player's ID into the argument because I'm having a lot of difficulties trying to get who proposed the sphere of influence on a civilization since Players[Players[iChoice]:GetPermanentAlly()] isn't giving me the ally, but rather after the resolution which makes this GameEvent feel useless.

**Comment by LoneGazebo** [comment]
will now be:  GameEvents.ResolutionResult.Add(function(iResolution, iProposer, iChoice, bEnact, bPassed) end)

**Comment by TechpriestEnginseer** [comment]
I forgot to mention, can this GameEvent trigger from forced Lua-based Resolutions as well or is that not possible?

**Comment by LoneGazebo** [comment]
Uhh. Maybe? :)

**Comment by TechpriestEnginseer** [comment]
Weird problem now.

**Comment by LoneGazebo** [comment]
True = 1. So could be yes/no event.

**Comment by LoneGazebo** [comment]
I'll look at it again.

**Comment by TechpriestEnginseer** [comment]
Except that iChoice is an integer and has to return the banned luxury or the city-state, and Sphere of Influence for sure isn't a yes/no event.

**Comment by TechpriestEnginseer** [comment]
Still not fixed.

**Comment by LoneGazebo** [comment]
Strange, I tested and it worked. I'll double-check master later.

**Comment by TechpriestEnginseer** [comment]
Also for a failure:
````
 TheBalanceDemandsIt: 16 -World Science Initiative (Works!)
 TheBalanceDemandsIt: 1 -Portugal Proposed it (Works!)
 TheBalanceDemandsIt: true Checks the iChoice. (I guess it should return true..?)
 TheBalanceDemandsIt: true (Guess it is being enacted not repealed.. maybe I should test it now)
 TheBalanceDemandsIt: nil (Should return false since it failed to pass)
````

**Comment by TechpriestEnginseer** [comment]
````
[2223024.184] TheBalanceDemandsIt: 4 (Proposing Banned Luxury)
[2223024.184] TheBalanceDemandsIt: 1 (Morocco)
[2223024.184] TheBalanceDemandsIt: true (Uhh what luxury was banned)
[2223024.184] TheBalanceDemandsIt: true (Right...?)
[2223024.184] TheBalanceDemandsIt: nil (It should have returned true)
````
````
[2223024.184] TheBalanceDemandsIt: 5 (Repealing Global Peace Accords)
[2223024.184] TheBalanceDemandsIt: -1 (No.. I proposed that we should repealed it...)
[2223024.184] TheBalanceDemandsIt: false (I guess it doesn't have a choice..)
[2223024.184] TheBalanceDemandsIt: true (No, it wasn't enacted, it was a repeal [BUG])
[2223024.184] TheBalanceDemandsIt: nil (It should have returned true as usual)
````

**Comment by LoneGazebo** [comment]
Ahh I dropped an i in master. I'll fix.

**Comment by TechpriestEnginseer** [comment]
So, does it work now before the next release comes up and then it has the same problems again. :S

**Comment by LoneGazebo** [comment]
Test the beta?
