### ISSUE TITLE
Impi do not benefit from Blitz promotion

### ISSUE THREAD

**Issue by 8bitBob** [LoneGazebo/Community-Patch-DLL#3053]
_1. Mod version (i.e Date - 4/23):_
Have not tested in some time. Apologies, but I cannot test at the moment.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The title is slightly misleading. Impi do not benefit from Blitz when combating enemy units rather than cities. I suspect this is because their ranged attack is being counted as the extra attack, which they do not use on cities. This makes Blitz Impi fairly disappointing in combat, which is sad for such an iconic unit.

Apologies if this is a balance choice and not a bug, but I couldn't get an answer on the matter.

**Comment by LoneGazebo** [comment]
I'll look at it.

**Comment by 8bitBob** [comment]
Hammered out a really quick test. Bug still present as of 1/26 release.
