### ISSUE TITLE
Cities ignore rich tile when expanding borders

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3054]
_1. Mod version (i.e Date - 4/23):_ 2-6

_2. Mod list (if using Vox Populi only, leave blank):_ FlagPromotions v.7

_3. Error description:_  In my particular case a rich oasis tile is ignored by cities' auto-expand. It chooses poor plains or coast tiles instead.

savegame [oasis ignored.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/762410/oasis.ignored.zip)

![20170209034206_1](https://cloud.githubusercontent.com/assets/16341598/22765657/313ecbbe-ee7a-11e6-9114-2f48027205e8.jpg)
![20170209034209_1](https://cloud.githubusercontent.com/assets/16341598/22765658/327deb7c-ee7a-11e6-90a9-753c00b50e2d.jpg)

**Comment by ilteroi** [comment]
desert tiles have a higher "influence cost" and the oasis yields aren't high enough to override that.
