### ISSUE TITLE
Galls upgraded after Astronomy don't have anti-ocean promotion

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#3055]
_1. Mod version (i.e Date - 4/23):_2/5 hotfix

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP
Enginseer's version of E&D and Community Events
JFD Cultural Diversity Core
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Celtic City Names, Iroquoian City Names, Randomize City Names
My own thing that does various things SQL type stuff
Ice Free Coasts
WHoward: Map Pins, Auto Map Pins, Diary, Enhanced Demos
Starting Scout
Tectonic Map

_3. Error description:_  Some of my Galls can enter ocean and some can't, and while I don't for sure know this is why, its the only variable that makes sense

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20170209033554_1](https://cloud.githubusercontent.com/assets/16260521/22775982/f6fe3a1e-ee7b-11e6-9f45-c052445e0b69.jpg)

**Comment by LoneGazebo** [comment]
Could be a mod conflict.

**Comment by pandasnail** [comment]
Yeah, maybe. I can test it out after I finish this game with just VP and Really Advanced Setup installed. It'll be a few days tho, esp since conquest-driven inevitable culture wins have been (understandably) axed, meaning I have to subdue at least Babylon and Ethiopia before I can declare myself victor.

**Comment by pandasnail** [comment]
Nope, not a mod conflict. Conceivably, a my computer sucks thing I suppose. Still present with only Really Advanced Setup (which I don't use normally and isn't in the screenshotted game). And, yeah, its researching Astronomy and then upgrading that does it.

![20170211195541_1](https://cloud.githubusercontent.com/assets/16260521/22858764/7fac1c18-f094-11e6-96e8-81a9b88ba59e.jpg)

**Comment by pandasnail** [comment]
Oh, and that test game is the new update, 2/10.

**Comment by pandasnail** [comment]
I wanted to look into some other things to plan my next, and I opened this autosave instead of a new game    and after the 'remerge' thing, its working as intended. Idk if you did work on it as well or my computer is being better or what.

**Comment by LoneGazebo** [comment]
@pandasnail I edited it.
