### ISSUE TITLE
Sometimes tech completion is delayed

### ISSUE THREAD

**Issue by DucDuNord** [LoneGazebo/Community-Patch-DLL#3056]
_1. Mod version (i.e Date - 4/23): Vox Populi (2-4-1). DLL only.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Sometimes tech completion hangs on '1 turn' for three to five turns. Most of the excess tech points are lost once the new technology is completed. 

See the attached screenshots, all from the same game.
![civ5screen0001](https://cloud.githubusercontent.com/assets/25659604/22777680/4f5b6a8c-eeb4-11e6-9220-a4f536983387.jpg)
![civ5screen0002](https://cloud.githubusercontent.com/assets/25659604/22777682/4f5ff750-eeb4-11e6-8603-c372e3353dea.jpg)
![civ5screen0003](https://cloud.githubusercontent.com/assets/25659604/22777683/4f60301c-eeb4-11e6-9491-99b1855188ed.jpg)
![civ5screen0004](https://cloud.githubusercontent.com/assets/25659604/22777681/4f5eae9a-eeb4-11e6-969c-0de52b9ab2df.jpg)
![civ5screen0005](https://cloud.githubusercontent.com/assets/25659604/22777684/4f615078-eeb4-11e6-86e2-d9a02e99dd80.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bryan317** [comment]
My understanding is that this has been fixed with the 2-6 version
