### ISSUE TITLE
Advisor tip about ruins appears before the first ruin is discovered

### ISSUE THREAD

**Issue by DucDuNord** [LoneGazebo/Community-Patch-DLL#3057]
_1. Mod version (i.e Date - 4/23):_Vox Populi (2-4-1). DLL only.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Adviser tip about ruins appears before the first ruin is discovered. Consequently, the 'find ruin' button does not work. 
![civ5screen0000](https://cloud.githubusercontent.com/assets/25659604/22777813/be5762b0-eeb4-11e6-90fd-bc50a7152908.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Advisor tips are unreliable.

**Comment by DucDuNord** [comment]
This doesn't happen in the vanilla game, though - as soon as one of your units spots a ruin the tip appears.

**Comment by LoneGazebo** [comment]
Right. But changes in the CP have made advisor dialogues unreliable. Best to disable them.

**Comment by DucDuNord** [comment]
OK, thanks!
