### ISSUE TITLE
Open Borders tooltip

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3058]
_1. Mod version (i.e Date - 4/23):_ 2-6 EUI

_2. Mod list (if using Vox Populi only, leave blank):_  FlagPromotions v.7

_3. Error description:_  Sometimes Open Borders tooltip in diplo-window gives bugged info. Greyed-out option doesn't explain why Open Borders can't be signed.

_4. Steps to reproduce (optional):_ savegame attached

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/763842/QuickSave.zip)
![20170209155557_1](https://cloud.githubusercontent.com/assets/16341598/22786340/c305e8b4-eee0-11e6-8e93-d27c3064747d.jpg)

**Comment by LoneGazebo** [comment]
How is that bugged?

**Comment by saamohod** [comment]
This is apparently a correct tooltip

![20170209171006_1](https://cloud.githubusercontent.com/assets/16341598/22789279/2ac086c6-eeeb-11e6-9772-323553fc4b8f.jpg)

**Comment by LoneGazebo** [comment]
Did you already have it with Sweden?

**Comment by saamohod** [comment]
Yes, with both. Actually I have Open Borders with a few civs, but in some cases the tooltip shows the red notice, in some it's absent.
