### ISSUE TITLE
Terracotta army bug

### ISSUE THREAD

**Issue by jsaak** [LoneGazebo/Community-Patch-DLL#3059]
_1. Mod version (i.e Date - 2/4):_

2/4 also the same was happening with the release before this one

_2. Mod list (if using Vox Populi only, leave blank):_

none

_3. Error description:_ 

When entering renaissance, and having Teracotta army built. I get every type of unit with 0 xp around my capital. Also I have a vassal too.

[AutoSave_0270 AD-1250.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/764585/AutoSave_0270.AD-1250.zip)
happens in turn 273

**Comment by LoneGazebo** [comment]
That's a perk of vassalage. Says so in the vassal tab.

**Comment by jsaak** [comment]
If that is the case. I miss a popup message stating this. I have seen a vassalage gifting units message, but this time it was missing. Also when you have a vassal it means you already have a sizeable military, i think there is no need to give you more units especially with 0 xp. I gifted them all to city states.

**Comment by LoneGazebo** [comment]
That's a balance decision that I'm not going to make, as C4DF is not my mod.
