### ISSUE TITLE
No confirmation on AI deals sent to me.

### ISSUE THREAD

**Issue by haydenhayden011** [LoneGazebo/Community-Patch-DLL#306]
http://images.akamai.steamusercontent.com/ugc/35247586651361296/72F18C12DEF6507E2AA0137B88FBFC5ED5E89A2C/ 

This is what happens when I click accept on an AI's deal. I'm using the latest version of EUI, the compatibility patches, Civ IV Diplo, more luxes, and CBP and CP as well as exploration continued expanded.

**Comment by HeathcliffWarriors** [comment]
Issue is still open after 4 years? :P

**Comment by haydenhayden011** [comment]
??????

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TheRealAyCe** [comment]
Looks similar to this: https://github.com/LoneGazebo/Community-Patch-DLL/issues/5450

**Comment by LoneGazebo** [comment]
I haven't ever been able to reproduce. Will close :)
