### ISSUE TITLE
Scholarship gives 1.5 science per follower

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#3060]
BELIEF_CHORAL_MUSIC is both in Belief_MaxYieldPerFollower and Belief_MaxYieldPerFollowerHalved.

**Comment by LoneGazebo** [comment]
Ah yep. Oh well, I'll fix for next time. Secret buff! :)

**Comment by Edaka** [comment]
Judging by how nobody has been eager to report it yet, I think somebody might be enjoying the "buff". (:

**Comment by LoneGazebo** [comment]
I fixed in 
Sat night nights hotfix. :)
