### ISSUE TITLE
43 civs More Luxuries is broken again

### ISSUE THREAD

**Issue by ashendashin** [LoneGazebo/Community-Patch-DLL#3061]
_1. Mod version (i.e Date - 4/23):_
2/10

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Same lack of monopolies as last time, except it also seems impossible for anything besides YnAEMP with true starting locations to spawn settlers.

**Comment by LoneGazebo** [comment]
I just put a new version up (https://mega.nz/#!yZdyQKhK!imTDPnYnhGr36snH-Pl_P3QguujUTS_jGKK62X__Pw4). Try it out.

**Comment by ashendashin** [comment]
More Luxuries is working. Dunno about the severity of the settler bug, as I only tried once so far and failed. I'll try a few more times later.
Thanks!

**Comment by LoneGazebo** [comment]
Cool. Assign starting does that, and that file was acting up. Also forgot that Civ loads mods alphabetically, so had to make 1a into 6c for more luxuries to go first.

**Comment by ashendashin** [comment]
Still can't load up without TSL. Maybe others have had better luck. Unless the new upload changed anything, it looks like I'm stuck with manually placed civs for now.

**Comment by LoneGazebo** [comment]
Works for me without issue every time. Might be a mod conflict.

**Comment by ashendashin** [comment]
Yeah it's a mod conflict. It conflicts with any mod that goes beyond the setup screen. Any at all.
Even quick turns breaks it...
Loads up perfectly on its own though.

**Comment by LoneGazebo** [comment]
My guess is that other mods aren't geared for 43 civs.

**Comment by ashendashin** [comment]
Settler spawns were possible on the last version, but it took some tries. Now that it's impossible with mods, I'm wondering if this should be a compatibility issue that people should be aware of. This bug also applies to the mod repository.
You've done an excellent job of making 43 civs work with VP. Is it an easy thing to make smaller mods built for it or is it a task best left to the authors discretion?

**Comment by LoneGazebo** [comment]
I'm not going to make compatibility mods for stuff outside of the VP. I will look at why they are causing issues though.

**Comment by ashendashin** [comment]
Sorry, I meant if there was something I could do myself. You definitely have more than enough to deal with already.

**Comment by ashendashin** [comment]
Ok so this was all on the fact that I didn't try anything besides YnAEMP and communitas the first time around(I was also making some edits that skewed things somehow). For some reason, YnAEMP random civ locations doesn't work with mods added to VP. I've no clue how it's so specific, but there it is.
Communitas just needed to have the assignstarting override set to false. I don't know why it was possible to load it on the last version, but I suppose it's irrelevant, since removing the line doesn't affect too much.

I apologize for not loading a vanilla map first. Didn't think something so specific could be tied to YnAEMP.
43 civ DLL is in full working order.
