### ISSUE TITLE
Lakes are valued too much

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3062]
_1. Mod version (i.e Date - 4/23):_

Current, 10th Feburyay
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Basically, my city has a choice between a lake tile or a horse tile. It always chooses lakes. In fact, most of the time it prefers lakes over everything, luxuries and strategics included.

**Comment by Enrico-Swagolo** [comment]
Same happens with bonus resources imho. They're valued as equal to luxuries/strategics which might highly delay their acquisition.

**Comment by LoneGazebo** [comment]
People complain when lakes aren't chosen. People complain when lakes are chosen. People complain. Lakes.

**Comment by Enrico-Swagolo** [comment]
Yeah, it's not that bad now and complaining will always be about everything, it is better than before when they weren't picked up at all though it'd make more sense if it took lakes after strategics/luxuries at least. 

Also, bonus resources seem to be valued equally to regular tiles sometimes? The same often occurs with strategic resource tiles. I don't get how it works now, but Wheat doesn't seem any more likely to be picked than a regular tile of the same ring.

**Comment by LoneGazebo** [comment]
There's a randomization at play, keep that in mind. The tile selection model _favors_ some things, but it will not always go for x/y/z.

**Comment by Enrico-Swagolo** [comment]
That explains it.

**Comment by ilteroi** [comment]
you guys are cracking me up
