### ISSUE TITLE
EUI_tooltip_library.lua error

### ISSUE THREAD

**Issue by awfulcalamity** [LoneGazebo/Community-Patch-DLL#3064]
_1. Mod version (i.e Date - 4/23):_
Vox Populi 2/4

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch
43 Civs CP
Community Balance Overhaul
CSD
C4DF
More Luxuries
CBP Compatability Files (EUI)

I started my game with teh following but the error recurs with them off:
Really Advanced Setup 
Mines on Flat Land
Fast Aircraft
RED Smaller Landmarks
RED Modpack

_3. Error description:_ 
Any non-vanilla buildings shows no tooltip, instead I got an error message that says "...\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatability Files (EUI)\LUA\EUI_tooltip_library.lua: 1378: attempt to call method '?' (a nil value)"

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
I deleted EUI and reinstalled the latest version. I deleted all my mods, cleared cache, and user data, reinstalled Vox Populi (43 civs EUI version). Funny thing was it did not automatically install the (6a) Commuity Balance Overhaul - Compatability Files mod, I had to manually download that one. The game runs just fine, no issues with gameplay, I'm just having trouble recalling what certain buildings do without the tooltips. 

Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/768598/Logs.zip)
[Abigail I_0214 AD-1520.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/768599/Abigail.I_0214.AD-1520.zip)
![20170211085822_1](https://cloud.githubusercontent.com/assets/25708408/22855214/74e00d72-f039-11e6-85ac-b3dbbd1c8b93.jpg)

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
If you are using the 43civs version do not install 6a. It isn't included for a reason.

**Comment by awfulcalamity** [comment]
Whoops! Thanks for the quick reply. This mod is the reason my Civ 6 playtime will be stuck at under 10 hours....

**Comment by LoneGazebo** [comment]
Hehe. Glad to hear it!!
