### ISSUE TITLE
Tradition and walls

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3065]
_1. Mod version (i.e Date - 4/23):_2-10 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
 
Watching a game in observer mode.
 Large map, 11 civs, Communitas map.
 
Some nations still ignore building a wall, even when bordering a strong hostile neigbour or in a coastal city. 

Аfter looking at it a bit longer I discovered a pattern. All these civs are Tradition civs. Normaly Walls (or higher) are built in their capital, but many important and vulnerable cities stay without walls until either pretty late in game (18-19th century or so) or until the city is easily captured by an enemy.

 Apologies for reporting it again. It seems this issue hasn't been resolved by the latest patch.

![20170211083526_1](https://cloud.githubusercontent.com/assets/16341598/22856040/ca111cf6-f092-11e6-978d-03ffac275156.jpg)
![20170211183040_1](https://cloud.githubusercontent.com/assets/16341598/22856055/efa86a46-f092-11e6-8e87-7e98ca616555.jpg)
![20170211185224_1](https://cloud.githubusercontent.com/assets/16341598/22856057/fab2e0ba-f092-11e6-9d31-990d8618f0d3.jpg)
![20170211192640_1](https://cloud.githubusercontent.com/assets/16341598/22856059/0395744a-f093-11e6-803e-ae9d7bf38937.jpg)
![20170211193235_1](https://cloud.githubusercontent.com/assets/16341598/22856062/0c77b69a-f093-11e6-9b5f-af9fd8383247.jpg)

**Comment by LoneGazebo** [comment]
The AI builds walls as a priority in 'bastion' cities. Not all cities are bastion cities.

**Comment by saamohod** [comment]
I see.
The point I'm trying to make is that Tradition AI seems to ignore walls in quite a few cities until late (or **too late**). I just launched another test game in observer mode with 12 civs. In 19th century wherever I find a developed city without wall defense, it's 100% cases a Tradition civ.

![20170212003720_1](https://cloud.githubusercontent.com/assets/16341598/22858069/0eb87eb6-f0bc-11e6-86fd-56a58cb6d299.jpg)
![20170212003803_1](https://cloud.githubusercontent.com/assets/16341598/22858070/10174454-f0bc-11e6-9813-a403cd462c70.jpg)

**Comment by saamohod** [comment]
I don't know what 'bastion' means in coding terms, but please take a look at the screenshot. Germany is losing miserably to China with the enemy army next to Frankfurt. Guess Frankfurt finally started building walls? No, it is building Artists Guild.
![20170212004802_1](https://cloud.githubusercontent.com/assets/16341598/22858135/56f21362-f0bd-11e6-995c-8cfa057ae2ba.jpg)

**Comment by Radost** [comment]
"Bastion" should be any town which touches the borders with another civ.

**Comment by LoneGazebo** [comment]
That's how bastion works, but the list of needs can be quite long.
