### ISSUE TITLE
Great Wall civpedia

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#3066]
Great Wall Game Info still says 1 extra move per tile instead of the new function you created, the 'Border Obstacle' as EUI calls is.

**Comment by LoneGazebo** [comment]
It says 'when entering,' does it not?

**Comment by pandasnail** [comment]
Well, it says, one extra move per tile  when entering, when I believe it takes all move when entering, then normal after that. No?

**Comment by LoneGazebo** [comment]
Yeah, 'when entering' i.e. crossing into borders. I'll clarify.
