### ISSUE TITLE
CiD Requests

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3067]
Continuing on from the other requests (I thought it'd be better to open a new issue), how possible do you think these would be:

**city:SetProductionModifierFromHappiness(value)/GetProductionModifierFromHappiness()**
**city:SetFoodModifierFromHealth(value)/GetFoodModifierFromHealth()**

These would set a yield modifier (positive or negative) on Production/Food,

**city:SetProductionFromHappiness(value)/GetProductionFromHappiness()**
**city:SetFoodFromHealth(value)/GetFoodFromHealth()**

These, on the other hand, would set a raw yield (positive or negative) of Production/Food.

I currently use dummy buildings to emulate these effects, but direct methods would be more efficient. However, as these manipulate yields, they might not be as simple as previously requested functions, so let me know if that's the case.

Meanwhile, would the following be possible as Policy tags (they're currently Buildings tags)?:

**TRSpeedBoost**
**TRVisionBoost**
**HappinessPerXPolicies**

**Comment by LoneGazebo** [comment]
[(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/769535/1.Community.Patch.zip)

See if this works for those things.

**Comment by JFDaly** [comment]
The Modifier functions work, but don't seem to have any actual affect on Food/Production. HappinessPerXPolicies doesn't seem to work either.

**Comment by LoneGazebo** [comment]
Oh, I thought you just wanted the data stored. Okay, I'll edit them to actually influence food/production. HappinessPerXPolicies uses the vanilla functionality, so it should work. Let me see.

**Comment by JFDaly** [comment]
Yes, if that's possible. I'd also like SetProductionFromHappiness and SetFoodFromHealth to influence raw Food/Production as well - I made this edit after you'd already looked at my request, I suppose. 

Out of interest (and because it might portend to whether I ask for things for Crimes), do you need to support each yield separately in the DLL or would it possible to do a SetYieldFromCrimes(yieldID, value)?

HappinessPerXPolicies is no big deal. But I can confirm that the TR functions work - which is no surprise seeing as you added them in the first place for Buildings :p

**Comment by LoneGazebo** [comment]
SetYieldFromCrimes(eYield, iValue) is easier and definitely preferred. One array > 12+ variables.

I see why happinessperx isn't working - technically it is, but firaxis hardcoded it to only update with building changes. Add a building to the city and you'll see it change. I'll force an update for it.

**Comment by JFDaly** [comment]
Okay, thanks. Then I'd also put in a request for:

**SetYieldFromCrimes(eYield, iValue)**
**GetYieldFromCrimes(eYield)** 
**SetYieldModifierFromCrimes(eYield, iValue)**
**GetYieldModifierFromCrimes(eYield)** 

which knocks off 12 dummy buildings. 

There's also:

**SetLocalHappinessFromCrimes(iValue)**
**GetLocalHappinessFromCrimes(iValue)**
**SetStrengthValueFromCrimes(iValue)**
**GetStrengthValueFromCrimes(iValue)**

Which would knock off the last two crime dummy buildings (Happiness and City Defense), but I'm not sure how doable these ones are comparatively.

And the final dummy buildings come from Development:

**SetLocalHappinessFromDevelopment(iValue)**
**GetLocalHappinessFromDevelopment(iValue)**

Sorry its a lot, but that really covers all the dummy buildings I've used.

**Comment by LoneGazebo** [comment]
Alright, so reworking it all a bit to reduce size. Sorry for delay. 

They'll all be arrays (so you could theoretically add in any yield, instead of just food/production). Anyways here's the new formulae:

GetYieldModifierFromHappiness(eYield)
SetYieldModifierFromHappiness(eYield, iValue)

GetYieldModifierFromHealth(eYield)
SetYieldModifierFromHealth(eYield, iValue)

GetYieldModifierFromCrime(eYield)
SetYieldModifierFromCrime(eYield, iValue)

GetYieldModifierFromDevelopment(eYield)
SetYieldModifierFromDevelopment(eYield, iValue)

GetYieldFromHappiness(eYield)
SetYieldFromHappiness(eYield, iValue)

GetYieldFromHealth(eYield)
SetYieldFromHealth(eYield, iValue)

GetYieldFromCrime(eYield)
SetYieldFromCrime(eYield, iValue)

GetYieldFromDevelopment(eYield)
SetYieldFromDevelopment(eYield, iValue)

tooltip for modifier ones above:

 TXT_KEY_YIELD_MODIFIER_HAPPINESS 
TXT_KEY_YIELD_MODIFIER_HEALTH
TXT_KEY_YIELD_MODIFIER_CRIME
TXT_KEY_YIELD_MODIFIER_DEVELOPMENT
(format it like other tooltips, i.e. with {1_Num} as the % value). 

You will need to make your own tooltips in lua for the non-modifier ones.

For the Happiness/Strength, I've used the same arrays as above (reduces memory overhead) with the yield YIELD_JFD_CRIME for Strength/Happiness from Crime and Development.
[(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/769624/1.Community.Patch.zip)


GetYieldFromCrime(YIELD_JFD_CRIME) and GetYieldFromDevelopment(YIELD_JFD_CRIME) == +/- Happiness
GetYieldModifierFromCrime(YIELD_JFD_CRIME) and GetYieldModifierFromDevelopment(YIELD_JFD_CRIME) == +/- Strength.

Make sense?

Both should be in small integers (i.e. 1, 5, 10, etc.) not 100s.

**Comment by JFDaly** [comment]
Yes, makes sense. Excellent, thank you. I'll give these a test and report back.

**Comment by LoneGazebo** [comment]
Awesome. Hoping that this improves stability for CP and CID users alike. :)

**Comment by JFDaly** [comment]
Hm, SetYieldFrom... seems to be inconsistent. Sometimes, setting one yield will set another (e.g. setting Science increased Gold, but this doesn't always happen). Values over 2 don't seem to store, but sometimes values don't store at all. Some of the methods do seem to also overlap, for instance, GetYieldFromDevelopment for Food returns 3 when Food was set via FromCrimes and FromHealth (as 2, so if they both stored in FromDevelopment then they didn't add correctly either). 

A bit tricky to explain, but let me know if you need more info. I'll look into the modifiers next.

**Comment by JFDaly** [comment]
YieldModifier... seem to have a similiar issue. Initially, I used SetYieldModifierFromHappiness(GameInfoTypes["YIELD_PRODUCTION"],6), but this didn't store anything. Same issue with FromCrimes/Development/Health for this yield. YIELD_FOOD had the same issue. However, YIELD_GOLD did work (using FromDevelopment), but again wouldn't accept anything above 2 - it also wouldn't accept 0 or 1 after 2 had been set. Setting Gold also caused the TXT_KEY for Food and Production to show up, so I rechecked Food and Production, and indeed they were now set at 2. Finally, I tested SetYieldModifierFromHealth(GameInfoTypes["YIELD_CULTURE"]) and this caused Gold to increase to 4 FromHealth, though I hadn't set Gold via this method before (and it had no effect on Culture).

**Comment by LoneGazebo** [comment]
Yields need to be this way YieldTypes.YIELD_CULTURE.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/769684/CvGameCore_Expansion2.zip)

Try this DLL.

**Comment by LoneGazebo** [comment]
(drop it in the CP I sent you earlier)

**Comment by JFDaly** [comment]
Okay, the modifier values are definitely stored consistently now. However, there's a slight problem with the Food one. For some reason, when I increase Food by 100% with FromDevelopment (same issue FromHealth, so I assume the others, too), it adds a "-4 Food from Trade Routes establishing to this city" in the Tooltip. This remedies on the next turn, but it seems a bit odd :p At 50%, it gave +6 Food from that source, again fixing itself on the next turn. 

Tourism as a modifier doesn't work as intended, as I assume it only modifie things that use YIELD_TOURISM rather than for instance the Tourism from Great Works. Unless there's an easy remedy for this, this is not a big deal, but in case there was, I thought I'd point it out.

Culture and Faith don't show the TEXT_KEY indicating that a modifier is present, but I think these two need this added manually? This is the case IIRC for other values like WLTKD mods that you added. This is easy enough.

Otherwise, everything seems to be working correctly now. Thank you! I'll let you know if I come across any other issues that have escaped me as I go ahead and implement these fully.

**Comment by LoneGazebo** [comment]
> However, there's a slight problem with the Food one. For some reason, when I increase Food by 100% with FromDevelopment (same issue FromHealth, so I assume the others, too), it adds a "-4 Food from Trade Routes establishing to this city" in the Tooltip. This remedies on the next turn, but it seems a bit odd :p At 50%, it gave +6 Food from that source, again fixing itself on the next turn.

Strange. May need to add an 'update yields' check in the Set function...

>Tourism as a modifier doesn't work as intended, as I assume it only modifie things that use YIELD_TOURISM rather than for instance the Tourism from Great Works. 

Tourism is a spaghetti yield. If you need it I can add it in pretty easily.

>Culture and Faith don't show the TEXT_KEY indicating that a modifier is present, but I think these two need this added manually? This is the case IIRC for other values like WLTKD mods that you added. This is easy enough.

 Correct, you'll need to do those in lua manually, sorry for not telling you that. Spaghetti s.

**Comment by JFDaly** [comment]
Yes, if you can add support for Tourism (at least from Great Works), that'd be great, as one of the organized crimes deals in lowering Tourism (organized crimes impact modifiers, regular crimes impact raw yields). Thanks!

**Comment by LoneGazebo** [comment]
Okay, fixed tourism and (I hope) fixed food.
TXT_KEY_CO_CITY_TOURISM_HAPPINESS_MODIFIER_CID
TXT_KEY_CO_CITY_TOURISM_HEALTH_MODIFIER_CID
TXT_KEY_CO_CITY_TOURISM_CRIME_MODIFIER_CID
TXT_KEY_CO_CITY_TOURISM_DEVELOPMENT_MODIFIER_CID

Same as other tooltips ( {1_Num} for % modifier).

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/769714/CvGameCore_Expansion2.zip)

**Comment by JFDaly** [comment]
Yeap, that fixed both Tourism and Food. Thanks.

**Comment by LoneGazebo** [comment]
Awesome!

**Comment by LoneGazebo** [comment]
@JFDaly all good?

**Comment by JFDaly** [comment]
Yeap, so far. Feel free to close the issue. I'll make a new one if anything unexpected happens.

**Comment by LoneGazebo** [comment]
Cool, will do.

**Comment by JFDaly** [comment]
Hm, when will these additions be added to the public CP? The last two updates (the 22nd beta and the 15th) don't appear to have them. I mainly ask so that I can download the right repository to hook into VS to test for CTDs.

**Comment by LoneGazebo** [comment]
I was waiting for final confirmation from you before I integrated.

**Comment by JFDaly** [comment]
Orite, fair enough. Will do.

**Comment by LoneGazebo** [comment]
If you're happy with the current state of the requests I'll integrate for the next full version.

**Comment by JFDaly** [comment]
Well so far I've only integration the Health and Happiness stuff, so it is a good idea to wait just in case. Will let you know when the rest are done.

**Comment by LoneGazebo** [comment]
Sounds good.

**Comment by LoneGazebo** [comment]
Also the new unit supply system I'm working on (in beta) may be something you're interested in for CiD. We'll see.

G

**Comment by JFDaly** [comment]
Strangely, the GetYieldFromCrime/Development/Health/Happiness values for Faith and Culture aren't being applied to the city's yields (not affecting them at all). The Modifier variants still work. Could you take a look?

**Comment by LoneGazebo** [comment]
Looks like I just never added those to faith/culture - I think I was under the impression they'd be for standard yields only. Anyways here's DLL with the fix. Let me know if it doesn't work.

G

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1514640/CvGameCore_Expansion2.zip)

**Comment by JFDaly** [comment]
Churs, that works perfectly now. Thanks for the quick fix.

**Comment by LoneGazebo** [comment]
Yep!

**Comment by LoneGazebo** [comment]
That's a debug DLL, but I'll issue a hotfix with an optimized one later today.

**Comment by JFDaly** [comment]
Hm, seems as though **GetYieldModifierFromCrime(YIELD_JFD_CRIME)** and **GetYieldModifierFromDevelopment(YIELD_JFD_CRIME)** == +/- Strength no longer holds true. These are now affecting the actual Crime yield rather than Defense.

**Comment by LoneGazebo** [comment]
@Infixo did you move these around?

**Comment by LoneGazebo** [comment]
I know you've tinkered with these modifiers quite a bit.

**Comment by Infixo** [comment]
Nope, I haven't touched any JFD-marked stuff.

However those Get...X functions seem to be disconnected from the rest of the code. I mean, no other function actually calls Set...X except for Lua Set...X. Value goes to the internal table and then is read. Where is that connection to Defense at all?

**Comment by LoneGazebo** [comment]
@Infixo they're not explicitly marked JFD - those two functions are lumped into the yield modifiers. I think you may have added modifier functionality for them without knowing what they're for. :)

**Comment by LoneGazebo** [comment]
Yep, I think I've fixed it I'll upload a hotfix DLL shortly @JFDaly for testin. It won't be savegame compatible because of other changes I'm making in the DLL, but that should be okay.

**Comment by JFDaly** [comment]
That's no problem, thanks.

**Comment by Infixo** [comment]
Maybe we're talking about other functions then, because those two above just do their own stuff.

**Comment by LoneGazebo** [comment]
I think in your rework of the modifier functions for UI two exceptions for _CRIME were removed/shifted. I've fixed. No worries! :)

**Comment by Infixo** [comment]
Ok then, good :)

**Comment by Infixo** [comment]
Ok, found those calls. If you mean paired calls in GetLocalHapiness() and updateStrengthValue(), then I haven't touch those neither.

**Comment by LoneGazebo** [comment]
> haven't touch those neither.
Ahh double negative! :)
I dunno when the change happened, then, but they're fixed now.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1701489/CvGameCore_Expansion2.zip)

**Comment by LoneGazebo** [comment]
Here's a tester. Has the WLTKD fix too.

**Comment by JFDaly** [comment]
Hm, the values seem a bit off. When setting a SetYieldModifierFromDevelopment() by 100%, it only increases the defense by 1 (city being at 11). When setting it at 1000%, it increases by 10, as I would expect 100% to do.

The Happiness doesn't seem to be working either. SetYieldFromX increases Crime instead.

**Comment by LoneGazebo** [comment]
I will look today.

**Comment by JFDaly** [comment]
Cheers, no rush.
