### ISSUE TITLE
Cities are specialistphobic

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3068]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Cities won't work specialists automatically unless the yield connected with them is the city's focus, so if you choose Gold focus they'll finally start using the Markets. Otherwise, tough luck. Cities would rather have people jobless labourers than turn them into Merchants even if you go heavily -GPT and have more pop than tiles, and they often choose to not work Forges even with Production focus when they have more pop than tiles under their control. Even focusing Great Person production with more people than tiles doesn't make them work any specialists,, not even Markets to help me get positive GPT.

It was much better a version ago. Right now the only way to have cities work on specialists in a way that makes sense is to micromanage every single one and go back to them when a new building is up, otherwise they always ignore them. I could trust the auto-management to make a more-or-less sensible decision pre-10th February, but now it just never makes any sense. It won't even work Diplomats which are by far the best GPs to use early, and before it always used them first.

**Comment by Enrico-Swagolo** [comment]
Great Person focus does nothing by the way. They never work any specialists with it and would rather them be +1 Production labourers, it's the same as general focus from what I see.

**Comment by LoneGazebo** [comment]
I don't see this issue, but I'll look.

**Comment by LoneGazebo** [comment]
![20170212133332_1](https://cloud.githubusercontent.com/assets/7849458/22864913/e9551924-f127-11e6-83b7-159103d3eec2.jpg)

**Comment by LoneGazebo** [comment]
Yeah, I can't corroborate this.

G
