### ISSUE TITLE
No Bad Events enable and still got one

### ISSUE THREAD

**Issue by dennisdahlc** [LoneGazebo/Community-Patch-DLL#3069]
_1. Mod version (i.e Date - 4/23):_

2/10

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I got a bad event regarding an Ice Age, while having disabled bad events.

http://steamcommunity.com/sharedfiles/filedetails/?id=863284185

**Comment by LoneGazebo** [comment]
The first ice age event is not bad. Just neutral.

**Comment by dennisdahlc** [comment]
I don't want to argue, but how is losing gold or production in all cities for 150 on Marathon unless you have railroad neutral ?
I have previously not turned off neutral events, but if this is a neutral event, I might have to in my next game.
