### ISSUE TITLE
New eki model

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#307]
![eki](https://cloud.githubusercontent.com/assets/6333704/8022519/227cfeae-0ce8-11e5-9816-79a607e1d5fd.jpg)

https://dl.dropboxusercontent.com/u/28753474/CP%20Improvements.rar
I also reduced file size of tipi icons.

**Comment by qqqbbb** [comment]
Farm has 3 different variations and I tried to do it for eki but could not. Is it hardcoded in graphics dll?

**Comment by LoneGazebo** [comment]
Awesome! I'm not sure about how the farm works, as we don't have access to the graphical DLL.
G

**Comment by qqqbbb** [comment]
reuploaded the model after I fixed couple of things.

**Comment by LoneGazebo** [comment]
Fantastic, thanks.
G

**Comment by qqqbbb** [comment]
Old files can be removed:
eki_hb_grnd.dds
eki_hb_grnd_h.dds
eki_hb_sref.dds
hb_eki.gr2
