### ISSUE TITLE
Unable to choose production or purchase as China

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#3071]
_1. Mod version (i.e Date - 4/23):_
2/10 (No-EUI) with "CityStateDiploPopup.lua:540: pActivePlayer" fix

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm unable to bring up the "choose production" or "purchase" windows after founding China's capital, preventing me from passing the turn. Other civs don't seem to be affected, and AI China appears functional.

Lua error when attempting to open either window: 

Runtime Error: D:\Users\\%Dir%\Documents\My Games\Sid Meier's Civilization 5\MODS\(6b) Community Balance Overhaul - Compatibility Files (No-EUI)\LUA\InfoTooltipInclude.lua:853: attempt to concatenate global 'strYieldBreakdown' (a nil value)

_4. Steps to reproduce (optional):_
Start a game as China and attempt to choose a production

**Comment by LoneGazebo** [comment]
Replace that line with this: 

strCultureToolTip = strCultureToolTip .. "[ICON_BULLET]" .. Locale.ConvertTextKey("TXT_KEY_YIELD_FROM_MISC", iYieldFromMisc, GameInfo.Yields[YieldTypes.YIELD_CULTURE].IconString);

Strange that my merge from master missed that. Ah, clerical errors.
