### ISSUE TITLE
Scicne from GP Impovements - Korea

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#3072]
_1. Mod version (i.e Date - 4/23):_
Feb 10 version

_2. Mod list (if using Vox Populi only, leave blank):_

![20170213201206_1](https://cloud.githubusercontent.com/assets/11430209/22914999/0a426a68-f229-11e6-8369-c350d7a92872.jpg)

_3. Error description:_ 
latest change clams "removed Science from GP UIs"

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![20170213201201_1](https://cloud.githubusercontent.com/assets/11430209/22915000/10b35ae2-f229-11e6-85f6-161740fd8086.jpg)

**Comment by LoneGazebo** [comment]
Strange, another master merge error. I wonder if my merge tool is acting up...
