### ISSUE TITLE
American UA doesn't mention it scales with gamespeed

### ISSUE THREAD

**Issue by ashendashin** [LoneGazebo/Community-Patch-DLL#3073]
_1. Mod version (i.e Date - 4/23):_
2/10

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
As the title says, America gets a whopping 30 production from purchases.
Making America Great Again, one typo at a time.

**Comment by Radost** [comment]
What speed?

**Comment by ashendashin** [comment]
@Radost I've been on a roll of stupidity lately. Epic, but 10 more seems a bit of an insane scale for the ancient era. I suppose I'll just revise this post instead of instantly closing more of my shame.

**Comment by Radost** [comment]
Why is it "bit too much" when epic has 1.5 higher production costs for everything?

**Comment by ashendashin** [comment]
I rarely play below epic so I kinda have a skewed view here. I suppose this belongs in the balance thread, but that production scale doesn't mean much on the ancient era because everything starts off low on numbers.
30 production is nearly a third of some very important early buildings.
Maybe I should close this. If I had bothered to use my head for one second then I'd realize that it's common sense to assume it scales.

**Comment by LoneGazebo** [comment]
:)
