### ISSUE TITLE
Pantheon persists after a religion with it has been founded

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#3074]
_1. Mod version (i.e Date - 4/23):_
2/6

_2. Mod list (if using Vox Populi only, leave blank):_
A whole bunch - I'll post if need be.

_3. Error description:_ 
I've noticed something that wasn't a thing before: it used to be that when you create a religion, your pantheon in the religion tab would be shown as incorporated into your religion. Now there are two instances of identical pantheons for founders (see pictures). Note double pantheons all over the place. 

![20170214211704_1](https://cloud.githubusercontent.com/assets/12978597/22946046/f1e0ff44-f2fe-11e6-9f82-c760d1b246e9.jpg)
![20170207223642_1](https://cloud.githubusercontent.com/assets/12978597/22946051/f4fd3b70-f2fe-11e6-8ada-715123d7fce9.jpg)

P.S. I think this could berelated to #3015 if the persisting pantheons create pressure against a newly founded religion.

**Comment by Edaka** [comment]
Oops, alrighty then. I just hadn't noticed that before (as in I don't think that's how it worked before).

**Comment by Edaka** [comment]
One thing, though, still: if I get it right, that means that your own pantheon will create resist the spread of your own religion, just like your pantheon would resist the spread of any other religion (a relatively new feature by Ilteroi), right?

**Comment by LoneGazebo** [comment]
Yeah, that's intentional.

**Comment by Edaka** [comment]
Gotcha, Makes sense if you think about it.
