### ISSUE TITLE
Too little barbarians spawned from Barbarian Horde

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#3075]
_1. Mod version (i.e Date - 4/23):_
2/6

_2. Mod list (if using Vox Populi only, leave blank):_
A whole bunch - I'll pos if need be.

_3. Error description:_ 
When a wave of barbarians spawns during the horde event, the wave is often just 1-2 barbarians. Doesn't seem to be an issue of space - in the screenshot attached there could have spawned at least 3 additional barbarians, but only 1 did (took the shot right after a 'wave' spawned). Sorry for the battle outcome tab that clutters the view.

![20170213182214_1](https://cloud.githubusercontent.com/assets/12978597/22946424/09a1b744-f300-11e6-9887-34c687f2a658.jpg)

**Comment by LoneGazebo** [comment]
The horde wave size is randomized, so this is fine.

**Comment by Edaka** [comment]
Ah, it seems to me that the waves used to be bigger in the good ol' days. The last couple of 'hordes' were quite the shadows of their former glory, but it could be anecdotal. I'll keep a close look on it.

**Comment by LoneGazebo** [comment]
please do.

**Comment by pandasnail** [comment]
So, ... its literally never been randomized in outcome for me. It used to be always four per wave and since the last few updates its always two per wave.

**Comment by LoneGazebo** [comment]
Code is this:

// In hundreds
	int iNumRebels = (GetPlayer()->getNumMilitaryUnits() * 60); //Based on number of military units of CS.
	int iExtraRoll = 100; //1+ Rebels maximum
	iExtraRoll += (GC.getGame().getCurrentEra() * 40); //Increase possible rebel spawns as game continues.
	iNumRebels += GC.getGame().getJonRandNum(iExtraRoll, "Rebel count rand roll");
	iNumRebels /= 100;

**Comment by pandasnail** [comment]
Tried, but I just can't read/understand that kind of code. But my experience really is this: I didn't play much in December and January. Before that, the only time a horde wave wasn't four is if there weren't four slots open even kinda close. And since I came back the last few weeks, they've all been two. Revolution waves have been different sometimes, but not the horde quest.

**Comment by Edaka** [comment]
Yeah, I too recently returned after a break - that's why I noticed there was some kind of a difference. I have been watching barbarian hordes ever since (although I don't play that much) and I can still say that they are significantly easier to deal with now. The amount of spawned barbs is certainly randomized, but for me it's either been 2 or 3 so far.

**Comment by pandasnail** [comment]
Did eventually get some 4s, but once it went to four, it never came back to 2 or even 3 (in not the largest sample of course). Don't know why its less random for me than Edaka.
