### ISSUE TITLE
A possibly wrong reaction from an AI to my refusal of their demand

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#3076]
_1. Mod version (i.e Date - 4/23):_
Prior to 2/6

_2. Mod list (if using Vox Populi only, leave blank):_
A whole bunch - I'll post if need be.

_3. Error description:_ 
Got a demand from Harun - rejected it - got this text as a reply, which doesn't seem right contextually to me. At the same time there appeared a 'We are trade partners' diplo modifier which I don't think was there before the demand.

![20170207193509_1](https://cloud.githubusercontent.com/assets/12978597/22946597/87028358-f300-11e6-8594-8c37757749df.jpg)

**Comment by LoneGazebo** [comment]
The response pulls from a pool of diplo responses that are occasionally odd. Happens. The other issue is legit I'll look.
