### ISSUE TITLE
EUI bug? - duplicate city icon on the left side ribbon for cities in resistance

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#3077]
_1. Mod version (i.e Date - 4/23):_
2/6

_2. Mod list (if using Vox Populi only, leave blank):_
A whole bunch - I'll post if need be.

_3. Error description:_ 
See the left hand side of the screenshot attached - there are two Sareisas. Only happened to me after capturing said city, and after the resistance ended the duplicate icon disappeared. Seems to be consistently reproducible.

![20170214181113_1](https://cloud.githubusercontent.com/assets/12978597/22946766/0ff80d04-f301-11e6-8923-32597d3b0bc0.jpg)

**Comment by LoneGazebo** [comment]
I'd report to EUI thread. Not sure why this is happening.

**Comment by Edaka** [comment]
Yeah, it's minor either way.
