### ISSUE TITLE
Can't open a city event choice list

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#3078]
_1. Mod version (i.e Date - 4/23):_
2/6

_2. Mod list (if using Vox Populi only, leave blank):_
A whole bunch - I'll post if need be.

_3. Error description:_ 
Got a city event popup, but clicking on it doesn't bring up the choice list, although I can hear the sound that plays when you open a choice list for a bad event. This is in the lua log: 
`[27461.573] Runtime Error: C:\Users\Edaka\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files/CoreLua/EventChoicePopupCity.lua:83: attempt to index local 'info' (a nil value)`

**Comment by LoneGazebo** [comment]
Getting a database log error? If using one of @TechpriestEnginseer's event mods, might be that?

**Comment by LoneGazebo** [comment]
This would only happen if an event is incorrectly assigned to the wrong type of popup.

**Comment by Edaka** [comment]
Yeah, using the Enginseer and co's event mod. In the database log there's only that:
`[562.836] no such table: Trait_PermanentYieldChangeWLTKD
[562.836] In Query - select Yields.ID, Yield from Trait_PermanentYieldChangeWLTKD inner join Yields on YieldType = Yields.Type where TraitType = ?`
Shouldn't be related, should it? I don't suppose there's a way how I could trace the error to the specific event causing it?

**Comment by LoneGazebo** [comment]
Do you have full logging enabled? If you do, you can see the cityeventlogging file.

**Comment by Edaka** [comment]
You have to have logging enabled before the event fires, right? I'll report back as soon as RNGsus lets me reproduce.

**Comment by Edaka** [comment]
Okay, this is looks like my fault entirely. The faulty event is the one that's originally yours that I modified. I don't know why, but it might be due to this thing I did:
`DELETE FROM CityEventChoices
WHERE Type = 'CITY_EVENT_CORRUPTION_CHOICE_3';`

**Comment by Edaka** [comment]
I wonder if there is another way of modding out an event choice without deleting it, then. I guess I could make it identical to one of the other event choices, but that would be ugly. 

Why is it that deleting an event choice breaks the lua, anyway? (I don't know lua, though. :( )

**Comment by LoneGazebo** [comment]
If there are fewer choices than indicated in the event itself it can cause issues.

**Comment by Edaka** [comment]
Ah, okay. Shouldn't be hard for me to fix, then. I'll try it later today. Many thanks!

**Comment by Edaka** [comment]
The problem turned out to be due to the fact that I deleted the event choice from CityEventChoices, but didn't delete it from CityEvent_ParentEvents . Doing the latter fixed it.

**Comment by LoneGazebo** [comment]
Gotcha. Yep, that'll cause it!
