### ISSUE TITLE
EUI bug? - left hand city yield breakdown in city view stops generating expanding hover tooltips after scrolling to a next city

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#3079]
_1. Mod version (i.e Date - 4/23):_
2/6

_2. Mod list (if using Vox Populi only, leave blank):_
VP with EUI and a whole lot of other mods - I'll post the list if need be.

_3. Error description:_ 
After opening the city view hovering over city yields generates an expanded tooltip. However, if the mouse stays inside the city yield box, these expanded hover tooltips stop being generated after you press  left or right on the keyboard. See screenshots - the first one was taken before pressing the right arrow button, the second one - after.

![20170214221552_1](https://cloud.githubusercontent.com/assets/12978597/22947491/e56f3bb8-f303-11e6-81f0-a485ce351dde.jpg)
![20170214221600_1](https://cloud.githubusercontent.com/assets/12978597/22947492/e71cfd74-f303-11e6-8fd5-19a0c27af4dc.jpg)

However, as the hover tooltip starts being generated again after: 1) exiting and re-entering the city view; 2) hovering over anything else in the city view other than city yields (units, buildings, tile purchase costs). Therefore the bug itself is just a minor annoyance, nothing big.

**Comment by LoneGazebo** [comment]
EUI quirk with how bc1 set it up, can't fix unfortunately.
