### ISSUE TITLE
I thought Volunteer Unit Legions didn't count for the cap either?

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#3080]
_1. Mod version (i.e Date - 4/23):_2/10

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP
Enginseer's version of E&D and Community Events
Show XP in Military Overview
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Celtic City Names, Iroquoian City Names, Randomize City Names
My own thing that does various things SQL type stuff
Ice Free Coasts
WHoward: Map Pins, Auto Map Pins, Diary, Enhanced Demos
Starting Scout
Tectonic Map

_3. Error description:_ It only says Maintenance free, but I thought it was no cap too, I barely ever go Freedom, so I certainly could be confused. If so, press close obvi. If they are supposed to be noncap, let me know, and I'll do a Mod Conflict test. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
They affect the cap, yes.
