### ISSUE TITLE
43 civs, in some cases AI dont settle at start

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3082]
_1. Mod version (i.e Date - 4/23):_
last(but in 10 feb, behaviour was the same)

Some AI(I see almost always one AI with such behaviour) don't settle at start, and settle in turn 40-50 or maybe later(in previous game with 10 feb version, Shongai when I found them in medieval era has only 2 cities and was in ancient era, when all others AI and me was in medieval)

In current game on turn 14 just look at screenshot. France from their start location go somewhere...

![20170216124217_1](https://cloud.githubusercontent.com/assets/13381981/23018082/61ac997c-f445-11e6-81b7-f045eaed808e.jpg)

**Comment by TechpriestEnginseer** [comment]
Maybe they're looking for a better start instead of that tundra start?

**Comment by bigcat88** [comment]
No, in next game Babylon from the best start I ever seen(marshes+lakes+rivers) go in some strange direction.
I will add screens from next games here, if will see such behaviour then, maybe I just misunderstood something.

**Comment by TechpriestEnginseer** [comment]
Actually I got this problem and it was only with 22 civs!

**Comment by aldebaran1997** [comment]
Same here.
Maybe they want to be barbarians, I wonder...

**Comment by TechpriestEnginseer** [comment]
I mean in worst case scenario, just do a force settle if they haven't settled within 10 turns. No point in trying to find the "perfect" starting spot.

**Comment by bigcat88** [comment]
Yeah, in my last game I use IGE on turn 30 to settle for Greece, cause his settler was crazy...
It's not barbarians, I remember such behaviour with disabled barbarians.

**Comment by ilteroi** [comment]
any particular type of map you are using?

**Comment by aldebaran1997** [comment]
I'm using Communitas map script in VP.

**Comment by ilteroi** [comment]
in my experiments they always settled, but it took up to 10 turns. so i put in a failsafe, now they will settle on turn 3 at the latest.
