### ISSUE TITLE
43 civs, DoW brings an unrelated civ with it

### ISSUE THREAD

**Issue by ashendashin** [LoneGazebo/Community-Patch-DLL#3083]
_1. Mod version (i.e Date - 4/23):_
2/15

_2. Mod list (if using Vox Populi only, leave blank):_
Community Events
E&D for CBO
Enhanced City-States
FlagPromotions
Really Advanced Setup
communitas map (might as well throw that out there)

_3. Error description:_ 
Japan made a demand of me, which I declined, and somehow I was at war with Russia too. This was at the ancient era. Might be related; I noticed that sometimes I would meet two civs at the same time, with the 2nd nowhere in sight. Maybe a mod conflict? Wouldn't doubt it at this point.
[save and logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/782592/save.and.logs.zip)
 
(Unrelated: damn FP is throwing out the icon error again. Probably E&D. On that; Enginseer, if you're reading this, I'd like to say that your events are killing me with their timing. Riots and 30 influence loss on city states in the first 50 turns? 2 Mamluks for just 225 gold? Gonna have to make a proper post on this after a full game)

**Comment by LoneGazebo** [comment]
Vassal?

G

**Comment by ashendashin** [comment]
I saw that pattern and noticed that for some reason my RAS had the team numbers all jumbled up. Absolutely no clue how that happened, given that I cleared moduserdata before this game.

**Comment by LoneGazebo** [comment]
Well there you go. :)
