### ISSUE TITLE
Modding Corporations: questions

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#3085]
1) In the Corporations table: MaxFranchises - I'm having a hard time understanding this. I thought the franchise cap at any given moment was determined by available trade routes and world size. Is this a hard cap, and if so, why is it needed?

2) Corporation_ResourceYieldChanges, Corporation_BuildingClassYieldChanges, Corporation_SpecialistYieldChanges - comments for these mention that yields stack (e.g. Applies X yield change to all cities with Corporation Headquarters and Offices (stacks)). Does this mean that in the city with the HQ you will get double yields?

3) There are four new corporation tables under the comment 'Non-functional ATM', however, one of them is Corporation_ResourceMonopolyOrs and another is Corporation_UnitResourceProductionModifier, both of which are used for the VP's corporations. I suppose if these are actually functial, are the other two functional, too? 

4) What does Building_FranchiseTradeRouteCityYield do? It isn't commented neither it is used in VP, as far as I know.

**Comment by LoneGazebo** [comment]
1. It is, yep. It is a hard cap to prevent ballooning franchises in late-game.

2. Don't think so, no. Believe I removed that.

3. They're all functional. Old tag.

4. It is legacy code that is there for memory purposes.

G

**Comment by Edaka** [comment]
You're the man, Gazebo! Thanks for the quick response! (:
