### ISSUE TITLE
Free buildings from ideologies persist if you switch ideologies

### ISSUE THREAD

**Issue by Emufarmers** [LoneGazebo/Community-Patch-DLL#3088]
_1. Mod version (i.e Date - 4/23):_
1/26

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
If you go order and use the bonus ideologies to get free military academies in every city, you get to keep them if you then switch to another ideology.  This doesn't really seem like the way it should be, though maybe it's unavoidable.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Unavoidable. It's a hardcoded policy effect.
