### ISSUE TITLE
Forgotten units

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3090]
_1. Mod version (i.e Date - 4/23):_ 2-15 EUI

_2. Mod list (if using Vox Populi only, leave blank):_ FlagPromotions v.7

_3. Error description:_ 
The Roman units on the screenshot were on route to land at Maya shore when Rome was at war with them. Then peace was brokered and Rome was engaged in a war against another civ, but these embarked units seem to be forgotten and stuck in the ocean for a long time now.

 Two savegames at different time lapse are attached.

![20170218192451_1](https://cloud.githubusercontent.com/assets/16341598/23095285/f788c24c-f60f-11e6-8e60-80f74bb9fccb.jpg)

[1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/785190/1.zip)
[2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/785191/2.zip)

**Comment by LoneGazebo** [comment]
They're probably waiting for an escort or staging for an attack.

**Comment by saamohod** [comment]
They've been staying afloat for way many turns. Dozens maybe.

**Comment by saamohod** [comment]
Units started moving a bit only 50 turns later. Up until that time they remained embarked, from ~turn 407 to ~457.


![20170219194556_1](https://cloud.githubusercontent.com/assets/16341598/23104739/49f3348c-f6dc-11e6-9f45-08cfe5607a17.jpg)

**Comment by ilteroi** [comment]
if you put this file [PlotHelpManager.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/786025/PlotHelpManager.zip) into (6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA the mouseover info will show you what the units are up to. care to try it?

**Comment by saamohod** [comment]
It's asking me if I want to replace it. Should I?

**Comment by ilteroi** [comment]
uh? that's unexpected ... did you restart the game?

**Comment by saamohod** [comment]
I did. It seems that some PlotHelpManager already exists in the designated folder, only it weighs 45kB. The one you game me is 35kB.
Maybe it has got something to do with the fact that the game was played with the Firetuner Autoplay (as an observer). No idea.

**Comment by LoneGazebo** [comment]
@ilteroi following up on this, I've now seen it happen.

Traced it to; 'Already in position, no move for' log in tactical AI.

![20170219214729_1](https://cloud.githubusercontent.com/assets/7849458/23110154/0d55b0fc-f6ed-11e6-834b-0443129713df.jpg)

Brazilian units were attacking and the city they were after was razed. At this point they stopped moving once the war was over, and have remained here ever since.

**Comment by LoneGazebo** [comment]
The Homeland AI isn't picking them back up for a return trip to Brazil.

**Comment by ilteroi** [comment]
@LoneGazebo : the log message you mention is from tactical AI, not from homeland AI ... otherwise it's believable
@saamohod : it's ok if it's smaller, i deleted a bunch of unnecessary bits - works fine for me, but i don't want to spend time debugging tools now

**Comment by LoneGazebo** [comment]
Yeah it is. But the homeland AI isn't picking them back up after war has ended because of distance.
