### ISSUE TITLE
My city being Razed, resistance units to Razer?

### ISSUE THREAD

**Issue by muarB** [LoneGazebo/Community-Patch-DLL#3091]
_1. Mod version (i.e Date - 4/23):_

2/10
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm not entirely sure this happened.  But it looked like resistance units spawned for Netherlands when they captured my city and started razing it.

I was playing Sweden.  Early in the game I captured a Shoshone island city, 1 tile.  Later after Shoshone were eliminated by Dutch, and I was fighting them, Dutch captured and began razing that city.  I saw a galleas appear near my shore, within city radius of razing city.  The galleas had that "matte" finish on the flag, similar to newly spawned units that haven't moved yet.  Is it possible the code is mixed up and giving free units to the AI doing the razing?  Sorry if it's a false alarm.  I saw something similar happen a couple times but not entirely certain what I was seeing.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Strange, I'll check.

**Comment by muarB** [comment]
It was probably the Sea Beggar killed my galleas and it appeared near my shore.  False alarm. sorry.
