### ISSUE TITLE
Where can I modify third party peace brokering warscore treshold?

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#3092]
I've been looking around both CP and CBO folders, searching for words like broker, third, party, etc., but couldn't find a value. Is there a define I could modify via sql/xml or is it a hard-coded value?

**Comment by LoneGazebo** [comment]
It is hard-coded. Why?

**Comment by Edaka** [comment]
Ah, okay. I wanted to give a lower value (say, 50) a try. As a matter of opinion, the current one is a little too rigid. I didn't think it was worth a balance discussion on the forum, but perhaps I'll come around to creating one eventually.
