### ISSUE TITLE
puppeting your own city?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3094]
this austrian city had been conquered by the germans, but now the austrians got it back

![image](https://cloud.githubusercontent.com/assets/1358966/23155137/949df720-f811-11e6-8f73-7a875253c0b9.png)

why is it a puppet?

**Comment by pandasnail** [comment]
Did it stay puppeted? Whenever, I or the AI liberates a city for somewhere else, the Icon shows up until the liberating receiver takes their turn, then it goes away.

**Comment by ilteroi** [comment]
it stayed that way

**Comment by LoneGazebo** [comment]
Chance it was actually sold back? There's a spot where I forgot to add a check for ownership on puppeting gifts.

**Comment by ilteroi** [comment]
i didn't watch at the exact time when it changed hands. might have been a sale. the city is currently damaged but the might have been somebody else's doing. did you just find this bug or is it supposed to be fixed?

**Comment by ilteroi** [comment]
btw, this is the same city about 100 turns later. building a chancery ... but still no fishing boats

![image](https://cloud.githubusercontent.com/assets/1358966/23181379/18141f90-f875-11e6-9c56-6113b0c73c1e.png)

**Comment by LoneGazebo** [comment]
Just found the bug today.

Also Funak noted that automated workers break for inca if on a mountain (i.e. in a mountain city) - mind checking?

**Comment by ilteroi** [comment]
can't confirm the inca issue.

![image](https://cloud.githubusercontent.com/assets/1358966/23184530/73525e48-f880-11e6-8c32-5b485879b373.png)

btw don't you think the mountains yields are a bit too high? the initial value 2g1s1f already seems high, but 6g3s3f in the renaissance seems a like a lot.

**Comment by LoneGazebo** [comment]
@ilteroi perhaps, but no one has brought it up as OP.

**Comment by TechpriestEnginseer** [comment]
The scaling seems too strong. It should be +1 Food and +1 Science every two eras along with +1 Gold every era.
