### ISSUE TITLE
Technology tree messed up and can't choose techs 

### ISSUE THREAD

**Issue by lordjani** [LoneGazebo/Community-Patch-DLL#3096]
_1. Mod version (i.e Date - 4/23):_
latest download from 21.02.2017

_2. Mod list (if using Vox Populi only, leave blank):_
check picture

_3. Error description:_ 
Technology tree corrupted, Can't choose or scroll advanced technologies...

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![civ5](https://cloud.githubusercontent.com/assets/25938163/23183837/19eb8ffe-f886-11e6-993e-69f42df11721.png)

**Comment by LoneGazebo** [comment]
Did you leave EUI in your DLC folder? Either that or you are missing DLC (Polynesia perhaps?)

**Comment by lordjani** [comment]
Sorry, i was missing some of the DLC's. Got them and problem solved ! Thanx.
