### ISSUE TITLE
Religion spreads despite DoW

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3099]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Declare war on someone. His religion still spreads to you.

Before, declaring war or having war declared upon stopped religion spread of your enemy.

**Comment by LoneGazebo** [comment]
It has never done that.

**Comment by Enrico-Swagolo** [comment]
But it did? I clearly remember India almost taking over my country with its bad religion, so I declared war and all passive spread of his cities went away (though influence from other, not-at-war nation's cities with that religion still was up, same with my cities of this religion). I did that many times and not only with India.

Was that the bug? But it was so intuitive...

**Comment by LoneGazebo** [comment]
That may have been a bug.

**Comment by ilteroi** [comment]
yes but no. there is no hard check for war, but religion spread depends on trade distance and movement through enemy territory is very expensive.

**Comment by Enrico-Swagolo** [comment]
Ah, that explains why sometimes the spread didn't disappear even those patches before. I bet even now it'll be the same as before. All's good then, thread can be closed.

**Comment by Edaka** [comment]
I can testify that war used to halt religious pressure from your enemy entirely.

**Comment by bryan317** [comment]
Actually that is happening in my current game. . Playing as Aztecs so I'm pretty much in a constant state of war, and it definitely halts religion both directions.

**Comment by LoneGazebo** [comment]
@ilteroi this seems a little strange no?

**Comment by ilteroi** [comment]
well it 10 times the cost so 2 enemy tiles pretty much stop it. a single tile wouldn't though

**Comment by TechpriestEnginseer** [comment]
I thought it was a neat feature because it would be hard for Islam to spread to Israel if they were in a war no?

**Comment by bryan317** [comment]
Would be interesting if it could spread faster based on war score.  The winning side might seem like the "right"  religion to the people getting slaughtered.
