### ISSUE TITLE
Supply cap suggestion

### ISSUE THREAD

**Issue by ricanuck** [LoneGazebo/Community-Patch-DLL#3101]
Hey G,

I was reading the reactions to your newest ideas about unit caps, and something caught my attention (btw, I was fine with the previous model but can see where you are coming from).

Did you consider flipping the solution upside down? Instead of changing the previous model as you did, why not apply differential multipliers for each unit type and era? I.e., early land units can continue to be 1 supply point (SP) per unit. You could also use a different multiplier for, say, naval units, to simulate that ships need less manpower than land units.

If the list iteration is a problem, then perhaps just use era multipliers to control the inflation of supply cap for later eras...?

I think it could work.

cheers,

**Comment by LoneGazebo** [comment]
Someone mentioned this and the problem is that the number of units is a fixed list size, and the AI would need lots of training.
