### ISSUE TITLE
Embassy Bug

### ISSUE THREAD

**Issue by DarkoDarkovic** [LoneGazebo/Community-Patch-DLL#3103]
_1. Mod version: 2/15

_2. Mod lis:  Really Advanced Setup (v 15)

_3. Error description: AI stole some land with citadel from city-state that had embassy on it and I lost the vote in congress. I can also build another embassy.

_4. Steps to reproduce:

---------------------------
Supporting information:

2. Save game: [zippyshare](http://www25.zippyshare.com/v/MSct467R/file.html)

4. Screenshots (optional): [imgur](http://imgur.com/a/a7lbf)

**Comment by LoneGazebo** [comment]
Yep. Not a bug.

**Comment by DarkoDarkovic** [comment]
In in game wiki it says: "An Embassy cannot be pillaged - once built, they can never be removed, and they will always grant their additional World Congress vote to the original builder."

**Comment by LoneGazebo** [comment]
Yep, if it remains in CS lands.

**Comment by DarkoDarkovic** [comment]
It is better this way but it is a bit unclear in wiki. Also what happens if I steal the land from allied CS with my Embassy? Do I also lose the vote? I also thought that even if AI defeats CS you still get the vote from embassy.

**Comment by LoneGazebo** [comment]
Yes. If the CS doesn't own it you don't have the vote.
