### ISSUE TITLE
CTD aftr

### ISSUE THREAD

**Issue by maptap** [LoneGazebo/Community-Patch-DLL#3105]
_1. Mod version (i.e Date - 4/23):_
2/15

_2. Mod list (if using Vox Populi only, leave blank):_
(8) CBO-EE Compatibility (v 3)
(8) events and decisions (CBO) (v 13)
Building - upgrade system (v 12)
Civic and Reform (v 6)
Community Patch Compatibility (v14)
(7) Community Events
enhanced city state (v 1)
Enlightenment Era (v 6)
Faster Aircraft Animation (v 3)
Industrial Building Pack (v 2)
JFD's cultural diversity (core) (v 13)
JFD's Event Compendium (v 4)
Medieval and Renaissance Building Pack (v 1)
National Wonder Collection (v 3)
Neolithic Wonders (v 1)
Promotion - Ancient Ruins Choice (v 2)
Strategic Buildings pack (v 2)

_3. Error description:_ 
(Washington's turn is right after me. He has declared war on me once already.) After the barbarians turn, right before me, he declares war on me again. I click on the reply, the view shifts from him to the world, and the game crashes to desktop.

_4. Steps to reproduce (optional):_
After reloading the autosave he declares war on me the same turn and the game crashes the same way. This happened 3 times in a row.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/797022/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[dfs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/797031/dfs.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files
/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/797041/CvMiniDump.zip)

4. Screenshots (optional):

Thanks so much!

**Comment by LoneGazebo** [comment]
Can't debug that many mods, sorry.

**Comment by TechpriestEnginseer** [comment]
What happens if you declare war on him first beforehand?

**Comment by maptap** [comment]
It still crashed before the next turn.
