### ISSUE TITLE
On CTDs

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#3106]
_1. Mod version (i.e Date - 4/23):_

2/10

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:

Since december, I get CTDs in nearly every game, around mediveal or rennaisance, with every version I tried.
But there is one thing I noticed (alltough the sample size is not that big):
I can finish games on "normal maps".
However, non wrapping maps like highlands or central sea will always crash. Could it be a issue with world wrap? I remember we had this problem a long time ago, could it have returned?

**Comment by LoneGazebo** [comment]
Perhaps. I'll test.

**Comment by LoneGazebo** [comment]
I think I found the bug. I'll fix and see if it stops flat-map null pointer CTDs.
