### ISSUE TITLE
Chariots/ranged horses don't run away

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3108]
_1. Mod version (i.e Date - 4/23):_

Current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So there's lots of flat land on this map, but the chariot has ended a turn next to my archer with an attack as I was sending more of them to support him. I've shot him with the archer. Instead of running away as he could've seen the rest of my ranged support coming in, the AI shot the archer again without moving from the spot, letting me kill the chariot.

Seems they really hate moving their troops away unless they're at 50~% HP.

Also, AI likes moving its troops out of cities for no reason. I get it, it's a Spearman and he's formidable early ancient era, but I've got 4x Archers there, it's a bad idea to do anything but keep him fortified.

**Comment by ilteroi** [comment]
did some adjustments ... at this point it's hard to make sure there are no regressions somewhere else, so i'm being careful.

anyway problem with the parthian moves is, the AI may lose sight of the enemy unit and promptly forgets about it ...
