### ISSUE TITLE
Crusader Zeal bonus applies to each city

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3109]
_1. Mod version (i.e Date - 4/23):_
2-25b

When u capture enemy city u  gain bonus in each ur city for capture(
![20170225213705_1](https://cloud.githubusercontent.com/assets/13381981/23334205/b03f1704-fba2-11e6-8737-dbcf2f56b757.jpg)

**Comment by LoneGazebo** [comment]
Try this hotfixed version: https://mega.nz/#!2ddSUSxQ!V8XFErL6I3T3nxAWuqITwMnbXYviCtTa8HDdeoEZx84
