### ISSUE TITLE
marsh has defense bonus

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#311]

**Comment by LoneGazebo** [comment]
That is by design.

**Comment by qqqbbb** [comment]
Why?

**Comment by LoneGazebo** [comment]
All other features have defense bonuses.

**Comment by qqqbbb** [comment]
In vanilla game marsh gives penalty to defense. By giving it defense bonus you encourage players not to avoid it like they should.
