### ISSUE TITLE
Can build Venice Unique Building as Carthage

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#3110]
Newest version (beta). Screenshot here:

http://images.akamai.steamusercontent.com/ugc/97229161714650253/8EE34169E5A76117BCE9F36307BC5B7C468A6753/

**Comment by TechpriestEnginseer** [comment]
But can you build it once researched? Science Tooltip is very weird when it comes to "soft-capping" unique buildings that aren't technically unique.

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict or something. I can't reproduce this.
