### ISSUE TITLE
Policy_YieldChangeWorldWonder Tooltip

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3111]
In EUI, I can add faith to world wonders via this policy, but the tooltip isn't updated to reflect that.

**Comment by LoneGazebo** [comment]
You'd have to add a tooltip element to the tooltip library. That ones isn't natively set up.

**Comment by TechpriestEnginseer** [comment]
Mhmm gotta change that bonus then.
