### ISSUE TITLE
MinorPlayer:GetAlly() breaks temporarily.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3112]
The Lua snippet somehow breaks within a turn when a city-state that was allied to you get conquered, so any GetAlly() function that grabs you returns nil instead of you during this turn.

**Comment by LoneGazebo** [comment]
Because as soon as th CS dies the data is deleted. Can't delay that.

**Comment by TechpriestEnginseer** [comment]
But other minor players that are aligned to you get their data deleted as well?

**Comment by LoneGazebo** [comment]
No, that data isn't touched - you sure you are accessing the right data?

**Comment by TechpriestEnginseer** [comment]
````
function NewPlayerDoTurn(iPlayer)
	if Players[iPlayer]:IsMinorCiv() then
		local minorPlayer = Players[iPlayer]
		if minorPlayer:GetAlly() ~= -1 then 
			local majorPlayer = Players[minorPlayer:GetAlly()] 
			if majorPlayer:GetEventChoiceCooldown(GameInfoTypes["PLAYER_EVENT_CHOICE_" .. GameInfo.MinorCivilizations[minorPlayer:GetMinorCivType()].Type]) ~= 0 then
				print(minorPlayer:GetName() .. minorPlayer:GetAlly())
				majorPlayer:SetEventChoiceCooldown(GameInfoTypes["PLAYER_EVENT_CHOICE_" .. GameInfo.MinorCivilizations[minorPlayer:GetMinorCivType()].Type], 2)
			end 
		end
	end
end
GameEvents.PlayerDoTurn.Add(NewPlayerDoTurn)
````
The code basically runs on the Minor Players' turns and check whether or not they have an ally. If so, extend their ally bonuses by +1. However, whenever a minor player gets conquered by a barbarian horde or such things; it seems that minorPlayer:GetAlly() no longer exist during that turn phase.

**Comment by LoneGazebo** [comment]
Why not check for alive status?

**Comment by TechpriestEnginseer** [comment]
same effect.

**Comment by LoneGazebo** [comment]
That's very strange. @ilteroi any reason why a civ living/dying would affect all the rest of the civs in the line?

**Comment by ilteroi** [comment]
no idea ...

**Comment by LoneGazebo** [comment]
@JFDaly have you ever seen this?

**Comment by JFDaly** [comment]
Hm, nope. I'll ask some others, see if they've had it.
