### ISSUE TITLE
Crusader Zeal

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3120]
_1. Mod version (i.e Date - 4/23):_
2-27

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
https://forums.civfanatics.com/threads/new-beta-version-february-21st-2-21.610792/page-13#post-14672446

_4. Steps to reproduce (optional):_
Add religion benefit to self with IGE, then capture by AI ur capital and conquer any city by yourself. Without holy city, bonus from conquer will be applied to all cities.
U will see such thing(as I write on forum yesterday):

![20170228154010_1](https://cloud.githubusercontent.com/assets/13381981/23407377/585f5982-fdcc-11e6-9239-00714358ab2a.jpg)

So in normal game, AI under ur religion will just get bonus in all cities.

**Comment by LoneGazebo** [comment]
@bigcat88 did you do all of this in one turn, or was there a delay?

**Comment by bigcat88** [comment]
Here as i remember, add beleif, set capture flag for portuguese, and on this turn - capture Goa. So yeah, in one turn.
But if u don't fix from yesterday(last beta with last fix on crusader zeal) - then its no matter. Cause yesterday - i play normal game, when AI under my religion just start to get insane amount of money and culture.
Maybe apply bonus from conquering to capitals?

**Comment by LoneGazebo** [comment]
Could be. Did you test on 2-27 version?

**Comment by bigcat88** [comment]
Yeah, last version. 2-27

**Comment by LoneGazebo** [comment]
Ah I see the issue - bad sign change parameter if no holy city, Will hotfix, Thanks for keen eye!

**Comment by LoneGazebo** [comment]
And hotfixed.
