### ISSUE TITLE
graphical glitch

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3121]
it seems i can't upload images right now ... see https://dl.dropboxusercontent.com/u/16988401/civ/supply_glitch.png

we are now officially in the nitpicking stage

**Comment by LoneGazebo** [comment]
Aah! Must pick that nit.

**Comment by bryan317** [comment]
You guys are gods among men.  Thanks for all the good gaming.  How do I support you?

**Comment by LoneGazebo** [comment]
Donate a few bucks/euros/pounds/ducats to a charity of your choice! :)

**Comment by LoneGazebo** [comment]
Oh, @ilteroi, ol Funak is complaining about religious pressure being oddly uniform across the map - possible that changes to dangerplots affected religious pressure?

**Comment by ilteroi** [comment]
no relation at all between dangerplots and trade distance. also i can't confirm that observation. need screenshot.

**Comment by LoneGazebo** [comment]
I didn't think so. I'll ask for some screenies.

**Comment by LoneGazebo** [comment]
@ilteroi per Funak,
https://mega.nz/#!yJVVlRKT!uESB2N1yONoiFCiTM5FMYQM2-Lmj7gEk62136_RoehM

From what I can tell, the issue is that pressure is extending way further than it used to (and much more uniformly). This smacks of a quirk in the trade range pathfinder, but I'm not 100% sure.

**Comment by LoneGazebo** [comment]
I've confirmed that all is well.
