### ISSUE TITLE
Ocean everywhere

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#3123]
Mod version: Newest 27th Feb

Additional mods: Really Advanced Setup, Flag Promotions, Ingame Editor

Screenshot: 
![image](https://cloud.githubusercontent.com/assets/8049731/23503473/d42dd77e-ff33-11e6-982f-182daa8d4737.png)

This happens every time I'm loading a save game. I'm not sure if this is CBP related, or perhaps it's EUI maybe? I've uploaded my save file so if anyone can check if it loads okay for them, that'd be great.

[OceanSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/813497/OceanSave.zip)

**Comment by LoneGazebo** [comment]
Strange. I've never seen this, and I load up saves often. 

Are you running the Waterworld mod, perchance?

**Comment by RockettSJ** [comment]
Hey @LoneGazebo, please do inform me which map you use to play. I'm suspecting this is a mapscript issue (I use Planet Simulator) and I always have these problems happening, random CTDs etc. As far as I know, you never have these problems so I would love a second opinion on map selection.

**Comment by LoneGazebo** [comment]
Sounds like a corrupt save, perhaps. Glad you fixed it.
