### ISSUE TITLE
Lose Pantheon benefits upon loading a save as Venice

### ISSUE THREAD

**Issue by 1-CityWonder** [LoneGazebo/Community-Patch-DLL#3125]
[AutoSave_0140 BC-0500.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/814517/AutoSave_0140.BC-0500.zip)

_1. Mod version (i.e Date - 4/23):_
2-27-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Lose Pantheon benefits upon loading a save.

Playing as Venice with only 1 city.  After loading a saved game, I can no longer benefit from my Pantheon.  My city has not been influenced by any other religion, nor has the majority changed at all.  Playing through after founding a new religion and I keep the Pantheon benefits.  I've tried a couple times and 100 turns into, still have benefits.  But if I save the game during any of those turns and close out and load the save, Venice no longer has Pantheon benefits.  

_4. Steps to reproduce (optional):_
Start a game w/ Venice.  Keep only 1 city.  Choose a Pantheon with obvious benefits.  Start a religion.  Save the game.  Load that save.  

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

**Comment by bigcat88** [comment]
Is pantheon displays after load(when it not works) when u put cursor on ur city?

**Comment by 1-CityWonder** [comment]
![venicereligion](https://cloud.githubusercontent.com/assets/26146152/23591214/f9d2075a-01ba-11e7-93c5-d572b1213619.jpg)

It shoes up as still a religious trait.  But the benefit is no longer there.
