### ISSUE TITLE
Lose Pantheon bonuses after founding Religion

### ISSUE THREAD

**Issue by cammcken** [LoneGazebo/Community-Patch-DLL#3128]
_1. Mod version (i.e Date - 4/23):_
2/27 (The installer file is named "Vox Populi (2-27-1)")

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Upon founding a religion, the pantheon bonuses (Goddess of Purity; +1 food and faith in marshes, lakes, and oases) disappear in the city where it was founded (the city in question has only marshes affected by the pantheon). The majority religion is the newly founded religion. Other city with the pantheon and without the new religion still receive bonuses (Only has lakes; no marshes.) Changes occur within the same turn.

_4. Steps to reproduce (optional):_
Use the great prophet to found a religion. Select Hinduism, Apostolic Tradition for founder, and Cathedrals for follower.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 

[BugReportLogs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/819109/BugReportLogs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

Includes a save from one turn before, and a save from the same turn, before the error.

[Saves for Bug report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/819110/Saves.for.Bug.report.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by cammcken** [comment]
Update: I continued the game anyway. When I spread the religion via missionary to the next city, it also lost the pantheon bonus, on the lakes. After some turns later, I didn't notice when, the bonus came back.

**Comment by bigcat88** [comment]
It's normal. Read forum. U lost pantheon bonus, till u spread ur new religion.
