### ISSUE TITLE
Denouncement for a denouncement demand

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#313]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/281
I still don't get why AI "should" denounce me, and get a backstab penalty in the process just because it asked me to denounce.
In the current situation Boudicca, with whom I have DoF, asked me to denounce Bismark, with whom I have DoF. Of course she backstabbed me for denial.

**Comment by LoneGazebo** [comment]
Well, you did make DOF with two enemy civs - either way you were going to piss someone off.

**Comment by Radost** [comment]
Why can't I do the same thing with them then?
