### ISSUE TITLE
Fearful City States Gain Resistance Spontaneously

### ISSUE THREAD

**Issue by 8bitBob** [LoneGazebo/Community-Patch-DLL#3130]
_1. Mod version (i.e Date - 4/23):_
2/27

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
City States which are Afraid, but you do not Demand Tribute from, appear to bug out and gain 900 Resistance from recent tribute without prompting and without giving you any yields.

_4. Steps to reproduce (optional):_
Just park a huge force of units next to a city state. I haven't tested extensively, but it seemed pretty consistent if they're already mad at you. It was so consistent that at first I thought it was an auto Demand feature, but then I noticed I wasn't gaining any yields.

**Comment by LoneGazebo** [comment]
Someone else asked for tribute.

**Comment by 8bitBob** [comment]
Oh whoa, I did not know it was a shared thing. My bad.

**Comment by LoneGazebo** [comment]
Yep.
