### ISSUE TITLE
Civilizations sometimes get overly fixated on one city-state

### ISSUE THREAD

**Issue by Emufarmers** [LoneGazebo/Community-Patch-DLL#3131]
_1. Mod version (i.e Date - 4/23):_
2-27

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Multiple civs had been trying (and failing) to launch a coup in Sidon whenever they could.  In the late game, Arabia finally succeeded, and as I sent a few ambassadors to see if I could take it back, I realized he was swarming them in far faster than me.  Even once his influence was thousands ahead of me, not only did he send ambassadors, he used at least two great diplomats.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
I mean nations are doing this thing in real life. I see no issue here. Lets you prioritize other city-states then.

**Comment by Emufarmers** [comment]
Well, it seemed so extreme that I figured it might be unintended.  How do I figure out what's a bug and what's an accurate modeling of human frailty? :p

**Comment by LoneGazebo** [comment]
I could probably tone it down some. :)

**Comment by Emufarmers** [comment]
Oh, I think one of the city-state events that make emissaries more effective might have been running for some of this.  Dunno if that would have played into it.

**Comment by LoneGazebo** [comment]
definitely would have.
