### ISSUE TITLE
Great Prophets Spawn for More than Six Religion.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3134]
I think Holy Sites are still fantastic to build for Great Prophets, so civilizations who were too late to found a religion with their prophet can still form a holy site to help them with tourism production. Instead Great Prophets are being restricted to only religious civilizations.

**Comment by LoneGazebo** [comment]
That's a pretty big gameplay change. Also, prophets spawning without a religion = potential null pointers abound.

**Comment by TechpriestEnginseer** [comment]
Prophets spawning without a religion can be given a "vision" or "revelation". Nevertheless, I'll take this to the forum and see the community's reaction.
