### ISSUE TITLE
Players not settling, city-state numbers limited to just 20

### ISSUE THREAD

**Issue by jbarthis** [LoneGazebo/Community-Patch-DLL#3135]
_1. Mod version (i.e Date - 4/23): 3/5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  I started a game and went to the advanced settings, but only 20 city-states were available. When I loaded the game and began to play only 7 of the 12 AI empires had established a city despite having plenty of space available to do so in the first turn in their preset positions. I found out the latter matter when I retired from the game and went to the map image.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.
[Export report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/819923/Export.report.zip)

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict or something, never seen this. Keep in mind the AI will often move 2-3 turns before settling if the starting plot is bad.

G

**Comment by jbarthis** [comment]
Hopefully changing the mods involved will eliminate the problem.

**Comment by MoiMagnus** [comment]
For the limit of 20 CS, If you still have this problem, you should check that you've taken the "normal" version and not the "43 civs 20 CS" version.
