### ISSUE TITLE
Cannot enter city state screen 

### ISSUE THREAD

**Issue by lorduc** [LoneGazebo/Community-Patch-DLL#3136]
_1. Mod version (i.e Date - 4/23):_

V88
_2. Mod list (if using Vox Populi only, leave blank):_

Box populi plus Ingame editor
Yet another giant map 
Some picknmixmods
_3. Error description:_ 
When I click on city states on the map, nothing happens. Also when I click on their name in diplomacy menu, again nothing happens. Played a game until industerial era with exact the same mods and map and it was fine, but after I started a new game, I noticed I couldn't enter the city state menu after clicking on their name. So I loaded some older saves, after going back to about 50 turns, it magically started working. So I kept playing from that point on, however as soon as I built the roman forum I no longer was able to enter the city state screen.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
mod conflict - check your mod list and make sure they are compatible.
