### ISSUE TITLE
Holy city status seems to have been lost

### ISSUE THREAD

**Issue by Emufarmers** [LoneGazebo/Community-Patch-DLL#3137]
_1. Mod version (i.e Date - 4/23):_
2-27

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I conquered Constantinople from Byzantium, and then France captured it from me.  Eventually I captured it back, but the holy city indicator seems to be missing from it now,  I'm not getting the happiness bonus from Clericalism, and I don't see any option to build the Grand Ossuary in Constantinople. D:

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Emufarmers** [comment]
[Isabella_0162 AD-1020.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/823020/Isabella_0162.AD-1020.zip)

**Comment by Vyyt02** [comment]
Do the French have their own religion? If yes, would it be possible that they converted all the Byz cities to their own religion and then removed the Holy City status with their Great Prophet?

**Comment by saamohod** [comment]
Happened to me, too. In my case a Holy City status was lost when a foreign religion was made a majority in the said city.

**Comment by LoneGazebo** [comment]
Inquisitiors do it IIRC.

**Comment by Emufarmers** [comment]
Well, I'm glad you've fixed that. :)

I don't think that's what was causing the problem here, though: I have a save from right before I captured Constantinople, where you can still see the holy city marker on it.  As soon as I capture it, it's gone.  Maybe there's something weird going on with the Spanish UA?
[Isabella_0142 AD-0640precap.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/826366/Isabella_0142.AD-0640precap.zip)

**Comment by LoneGazebo** [comment]
Well the logic that causes it to happen is a factory method. Here, try this debug DLL (it'll be slow, so it is just for this test) and see if it works.
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/826434/CvGameCore_Expansion2.zip)

**Comment by Emufarmers** [comment]
I replaced Assets\DLC\Expansion2\CvGameCore_Expansion2.dll with that, but it crashes on startup now.

**Comment by LoneGazebo** [comment]
oh, it won't work as a modpack, not happily. nevermind.
