### ISSUE TITLE
CTD in CvDiplomacyAI ::DoTurn()

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3138]
_1. Mod version (i.e Date - 4/23):_
3/7

_2. Mod list (if using Vox Populi only, leave blank):_
VP 1-6a, Enlightenment Era v6, CBO-EE v4.1 (attached)

_3. Error description:_ 
CTD on Pocatello's Turn 339

_4. Steps to reproduce (optional):_
Load attached save file and run AutoPlay in FireTuner for 10 turns. On Pocatello's T339 CTD.

---------------------------
[CTD CvDiplomacyAI.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/825099/CTD.CvDiplomacyAI.zip)
Supporting information:
The attached .zip contains: Save File, MiniDump, CBO-EE mod, 2 sets of Logs and analysis in Word.
I've got more examples, but I only attach the fresh one with latest VP. There are 2 sets log logs, one from playing from the start and the other from loading save file. They both end with CTD in exactly same place.

I did a thorough analysis of the logs and execution flow in DLL. The crash happens within CvDiplomacyAI ::DoTurn, between DoContactMinorCivs() and LogStatus(). I have examples of DoContactMinorCivs() **logging something** but LogStatus **never** logs anything on CTD's turn. You may find more details in Word, I put in green examples from logs showing that the function executed properly.
I have no means of debugging any further. This bug is somehow related to EE&CBO-EE but I have no idea **why Diplomacy is affected**. Also, the additional mods just add new buildings, units and few techs. Gameplay-wise they are working perfectly. I'd appreciate if you could debug further to find out what exactly is happening in Diplomacy during this turn and how is it related to CBO-EE?

Some other info:
- This error may be postponed if you start playing as human, but sooner-or-later it happens to another Civ - always on AI turn.
- It always happens after researching 2-3 initial techs from Industrial Era; it never happens during Enlightenment Era.
- It has nothing to do with Lua scripts. I disabled them once and it's still happened.

**Comment by LoneGazebo** [comment]
It appears that in the process of creating or modifying EE an empty space in the technologies list has appeared - ID 83 is missing. That means any call to a tech loop that is explicitly looking for all techs will crash on eTech = 83.

**Comment by Infixo** [comment]
How is it related to Diplomacy? Could it be somehow connected to tech trading, i.e. one civ is trying to sell/buy a tech and then hits this empty space?
Anyway, I'll correct it and check if it helps.

**Comment by LoneGazebo** [comment]
Probably - as I noted, that's the bug (the gap in the tech ID list). If it isn't one thing, it is something else.

**Comment by Infixo** [comment]
Fixed it! Thanks a lot for quick help. This was really driving me crazy for last few days :)

**Comment by LoneGazebo** [comment]
Yep!
