### ISSUE TITLE
AI doesn't improve fish resource

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3139]
_1. Mod version (i.e Date - 4/23):_3-7, was also present in previous version

_2. Mod list (if using Vox Populi only, leave blank):_ FlagPromotions

_3. Error description:_ 
 Coastal Civs ignore improving fish resource, even pretty late into game (I've seen medieval games with more or less developed cities with unimproved fish in city's range). 
 Even when a city is desperate for food (island tundra location), the AI doesn't seem to build fish boats for fish (coastal luxuries seem to be working ok). Out of dozens of fish locations who cry to be improved on the map in general, I notice only a couple boats working fish at about medieval time. Didn't observe till later because my game crashed (apparently KRIS_SWORDSMAN_PROMOTION_ATLAS Firetuner bug).

_4. Steps to reproduce (optional):_ 
 Launch an observation game at continents or similar coastal map and a dozen civs.

**Comment by LoneGazebo** [comment]
I'll up the algorithm a bit.
