### ISSUE TITLE
Submarine and Nuclear Submarine "Targetting" promotion

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#314]
- Submarine and Nuclear Submarine: have "Targeting" promotion which grants them something like +10% combat strength. I think that this is unnecessary as these units already have loads of promotions and it's difficult to figure out how they work. It's better to remove this promo or increase combat strength manually.

**Comment by LoneGazebo** [comment]
This is a balance issue, so I'd bring it up in the forums.

G
