### ISSUE TITLE
AI skips their second attack with naval logistics 

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#3140]
_1. Mod version (i.e Date - 4/23):_
2/27

_2. Mod list (if using Vox Populi only, leave blank):_
FlagPromotions (v 7)
IGE (v 39)
Quick Turns (v 10)

_3. Error description:_ 
The AI only attacks once with naval units that have the logistics promotion, even without moving before or after the initial attack. 

_4. Steps to reproduce (optional):_
Observe the AI using units with the logistics promotion. I'm unsure if ground units are affected, as I recall Wu Zetian using her chu-ko-nu UU well in previous versions, or if the blitz promotion is used properly.

---------------------------
Supporting information:

[Gif](https://i.imgur.com/FjraN4H.gifv)
North west of St. Petersburg is the offending Ottoman frigate.

**Comment by ilteroi** [comment]
hmm. confirmed for chokonu. seems the double attack is currently broken ...

**Comment by TechpriestEnginseer** [comment]
rip Incan slinger buff incoming.
