### ISSUE TITLE
Hiawatha is cutting his own forests

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3142]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I've seen Hiawatha cut down forest tiles in his empire, sometimes I saw the point (like 1 tree to make a farm triangle - acceptable decision) but sometimes he just does it despite the forest being obviously a better choice because farm or not, it won't make a triangle anyway. He's being silly by breaking his own stuff.

**Comment by TechpriestEnginseer** [comment]
maybe he wants that yummy wonder.

**Comment by cdanger341** [comment]
I've been playing a game in the 3/7 version and I am seeing this unusual behavior from Hiawatha as well. He started in a nice, heavily wooded portion of the map, but started chopping down his forest hexes to make farms and plantations. He had a lot of banana and citrus hexes around him, so chopping down the forests to make plantations makes sense, but by the late Medieval/early Renn eras he had literally chopped down every forest hex within his borders to make farms. Given the Longhouse bonuses, it seems very self-damaging for the AI to have removed all of forests. He was using my religion which did not have Cathedrals, so he had no good reason to focus on building farms over lumber mills. Just seemed really strange.

Also, Hiawatha went with Tradition but initially spread out and settled 9 cities during the Ancient/Classical eras. This happened while I was in a huge war with Denmark (can't let the Danes get a foothold!) and Hiawatha's expansion mixed with Tradition tanked his Tech/Policy rate. I "did him the favor" of capturing a few of his cities nearest to my borders, and surprisingly he actually became very friendly with me afterwards, almost like he was happy to lose those extra cities that were slowing his advancement down. Again, very weird game so far...

**Comment by LoneGazebo** [comment]
Tuned this down a bit.
