### ISSUE TITLE
Cartographic Commission Distance

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3143]
It's insanely too far. I'm playing on a small map and this city-state reveals a tiny area that shows where I am on the globe already (letting me know whether im at the center or even at the left of the map), it should have a distance restriction along with a reward reduction.

**Comment by Radost** [comment]
Also it likes to target areas on other ocean-separated continent. I don't think anyone besides Polynesia can accomplish them in a reasonable amount of time.

**Comment by LoneGazebo** [comment]
Shrinking this down a bit.
