### ISSUE TITLE
Mongol/Polynesian CS Units

### ISSUE THREAD

**Issue by Phalanx1** [LoneGazebo/Community-Patch-DLL#3145]
_1. Mod version (i.e Date - 4/23):_
3/7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Gifted unique units from city-states (i.e. Hussar and Turtle Ship) don't have the Mongol +2 movement or the ability to build Polynesian fishing boats.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Gifts are not units you created.

**Comment by Phalanx1** [comment]
It seems a bit inconsistent though, gifted non-unique units have the abilities AFAIK.

**Comment by LoneGazebo** [comment]
Ah, well that's because the player can't natively 'train' them, so they can't use their UA abilities. Odd, but follows game logic.

**Comment by Phalanx1** [comment]
Well, I disagree with you. Huns can still capture units with Companion Cavalry for example. Thanks for the help anyway.

**Comment by LoneGazebo** [comment]
Capturing isn't the same as a gifted unit in game logic.

**Comment by Phalanx1** [comment]
I meant that the huns can capture units with gifted uniques.

**Comment by TechpriestEnginseer** [comment]
Because the Hun's UA is attached to all units. Although it makes sense for Polynesia's UA to attach to all units as well to fit with consistency along with Mongolia's UA.

**Comment by Phalanx1** [comment]
Since this is open already, I would like to report that missile cruisers also don't work with the Polynesia UA. Regarding the removed UUs, can you look at their upgrade costs? They are higher than the purchase cost due to the units' production cost being zero.
