### ISSUE TITLE
Inca - No Trade Routes from Mountain cities

### ISSUE THREAD

**Issue by WilsontheRed** [LoneGazebo/Community-Patch-DLL#3147]
_1. Mod version (i.e Date - 4/23):_3/7

_2. Mod list (if using Vox Populi only, leave blank):_Really Advanced Setup

_3. Error description:_ Incan cities built on mountains can't send out caravans (haven't tested with Cargo ships). Attached turn 46 save game, screenshots of both cities (showing granaries present in each) and trade screen (showing only trade route from non mountain to mountain city available).

I have experienced this issue in a previous game as well, and other users (Funak being one) have reported in the fourms experiencing this as well.

[Inca Caravan.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/836863/Inca.Caravan.zip)

_4. Steps to reproduce (optional):_ 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
Yeah, I see such behaviour a few month ago. There also was problem with religion pressure when were cities on mountains(as I remember cities on mountains almost not receive pressure at all) but maybe pressure was fixed after that.

**Comment by ilteroi** [comment]
i couldn't reproduce it last time, but now i could. strange. anyway is fixed. this includes religion pressure, as it's based on trade distance.
