### ISSUE TITLE
AI hits barbie camps/cities for no reason

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3148]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I see this bug ic back. Basically, if an AI Scout or some unit sees a fortified barbie camp or an enemy city, it almost never is able to resist the temptation to attack. Then they either die if it's my city, or if it's a barbie camp they have to heal a biot. Last game IndonesAI  has sent a Horseman probably to scout my stuff, but instead of running away or at least pillaging my stuff, he has pointlessly attacked my City and got shot to death, and I see the Scouts attacking barbie camps as a substitute for a greeting nearly every single time.

**Comment by ilteroi** [comment]
cannot reproduce. screenshot or it didn't happen :)

**Comment by Enrico-Swagolo** [comment]
Pics or it didn't happen in current year +2? How could you even trust me when everything is in folders inside zips, maybe I'm the sort of guy who'd send you naughty pics instead? Or did you already fix it which is why reproduction is impossible, meaning the hidden not-suitable-for-github pics are what you want?  Or maybe you trust me because I've sent you many zips already? What if I was attempting to gain your trust for all this time, only to abuse it for a cheap laugh?

But to be more serious, I see it nearly every time myself. Whenever I play a regular game, move my warrior/scout anywhere near a camp and if there's an AI, they'll almost certainly attempt to pound the camp before deciding to heal and/or moving away. I could get a picture though, or a save but it doesn't ever work for us.

**Comment by LoneGazebo** [comment]
@Enrico-Swagolo if you have logging enabled, next time it happens, note the turn and post the relevant tacticalAI log.

**Comment by ilteroi** [comment]
relax, i was joking. but on the other hand, nothing i can do right now.

@g: mind pushing your latest?

**Comment by Enrico-Swagolo** [comment]
I was joking too though, I'm rarely serious
