### ISSUE TITLE
Phantom AI bonuses

### ISSUE THREAD

**Issue by superunicornfan** [LoneGazebo/Community-Patch-DLL#3151]
_1. Mod version 3/7_

_2. Mod list (if using Vox Populi only, leave blank):_
VP without more luxuries

_3. Error description:_ 
On king difficulty, AI get 20 gold, production, and food upon settling their first city. On immortal, the bonus is 30 of each. I haven't tested other difficulties.

_4. Steps to reproduce (optional):_
Checked using IGE. Happens with all AI.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

![20170313201325_1](https://cloud.githubusercontent.com/assets/25396420/23882113/9d8176d4-082c-11e7-8639-ffa4870fe0ed.jpg)
![20170313201902_1](https://cloud.githubusercontent.com/assets/25396420/23882114/9d8289ac-082c-11e7-821a-5ad6a9df94b4.jpg)
![20170313201908_1](https://cloud.githubusercontent.com/assets/25396420/23882115/9d839194-082c-11e7-8900-02be5c3d69e6.jpg)

I'm really just curious what's causing this. I've scoured difficultymod.xml and other files and haven't found anything. Could this be a bug or just a hard to find line of code?

**Comment by LoneGazebo** [comment]
you are looking for this in difficultymod.xml: <DifficultyBonus>0</DifficultyBonus>

**Comment by superunicornfan** [comment]
What?
