### ISSUE TITLE
AI still sends Great Diplomats to city-states with Open Doors

### ISSUE THREAD

**Issue by Emufarmers** [LoneGazebo/Community-Patch-DLL#3152]
_1. Mod version (i.e Date - 4/23):_
3/7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I don't know if it does this regularly, but I saw it do it in my last game, and it seems like it would almost always be a mistake.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Putting down embassies?

**Comment by Emufarmers** [comment]
No, it says it was a regular mission:
![20170314004447_1](https://cloud.githubusercontent.com/assets/1308219/23915613/fdea86b2-08bf-11e7-8b01-917e960eeb01.jpg)
![20170314004453_1](https://cloud.githubusercontent.com/assets/1308219/23915625/02cf4b5e-08c0-11e7-989d-18e128310254.jpg)
