### ISSUE TITLE
Japanese unit upgrade popups appear in unrevealed territory

### ISSUE THREAD

**Issue by Emufarmers** [LoneGazebo/Community-Patch-DLL#3153]
_1. Mod version (i.e Date - 4/23):_
3/7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When I scrolled over to where the other continent was under the fog, I was barraged with: 
![20170307161455_1](https://cloud.githubusercontent.com/assets/1308219/23887963/80b70dfa-085b-11e7-9d81-aa8be8574e54.jpg)

I don't know if this is fixable or just an engine bug, but, eh, worth a shot.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Radost** [comment]
#2229

**Comment by Emufarmers** [comment]
Yeah, I think I remember seeing it with the Indonesians (probably in vanilla, too).  I guess it was particularly noticeable here because of #3143. :)

**Comment by LoneGazebo** [comment]
It is a vanilla thing- I don't know that I can fix it.
