### ISSUE TITLE
AIs oversettling habits

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3158]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Title. I almost constantly see AIs see a few untaken tiles behind my empire, whether they're "islands" or onmy mainland, and with time they'll inevitably build a city there. This "issue" used to be here XX versions ago, but then got fixed - seems it made a comeback. If the AI had way superior military, I'd understand, but it usually doesn't. Needless to say, I nearly always raze their stuff afterwards. They settle at about the right rate (though Traditionalists might need to slow down a little, they expand too much early and might get hurt as a result)

**Comment by ilteroi** [comment]
care to post some screenshots of the terrain?

**Comment by Enrico-Swagolo** [comment]
[Desktop.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/847235/Desktop.zip)
Look at Bactra/Shushan.

**Comment by ilteroi** [comment]
well, those are perfectly fine spots for a city. but if you understand you correctly, you want them to stay away because they're too weak to defend those cities? and you feel boxed in, forcing you to take the diplo penalty for razing? how about buying up some territory around your cities?

**Comment by Enrico-Swagolo** [comment]
They are fine spots, but look at Shushan, founded by Babylon very, very far away from their lands, now owned by Polynesia because it's impossible to protect a fresh town so far away from the main territory. Same with Bactra and Persia, though at least Persia has a good military and is somewhat close, though the conquest happened long ago this one is at least justifiable.

**Comment by ilteroi** [comment]
the AI does prefer settling close to their own lands in the beginning of the game, but that restriction is loosened over time. the relative strength and attitude of the neighbors also plays a role. but it's not easy to get the balance right with different gamespeeds, maps sizes etc - i cannot rule out that there's a problem - so which size/speed is this?

also, which other spots were available for settling? maybe the AI simply had no other choice?

**Comment by Enrico-Swagolo** [comment]
Size Standard (I converted for your sins), Epic speed.

From what I can see, yeah they had no other real place to expand. That does explain it, though it's still not the smartest decision ever. They all went Authority - I, on their place, would declare war, conquer stuff and then use the settler (or use it while fighting over any cities in the way), getting a more rational, easier to defend border in the process rather than having 1 city so far away from my lands, but making a solution like that could, perhaps, make the AI too afraid or risk-taking or something.
