### ISSUE TITLE
AI Rapid Culture Dominance

### ISSUE THREAD

**Issue by muarB** [LoneGazebo/Community-Patch-DLL#3161]
_1. Mod version (i.e Date - 4/23):_

3/7
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I was cruising along in a game as the Celts.  Indonesia was a run away on the other landmass inaccessible by land units from me until astronomy.  The good news was I was exotic to them and had cedric halls built.  
![image](https://cloud.githubusercontent.com/assets/23019463/24029926/0845053c-0a97-11e7-83de-720d25c1ed3f.png)

I took the another capital and I was still exotic to Indonesia.  
![image](https://cloud.githubusercontent.com/assets/23019463/24029968/5c430d00-0a97-11e7-9601-8491131c7bb3.png)

In a span of 20 years (epic speed) Indonesia culture bombed the world somehow. 
![image](https://cloud.githubusercontent.com/assets/23019463/24030010/8db62264-0a97-11e7-8ab6-3657e546227e.png)

The game was about to get interesting.  I had defensive pacts with Russia and the Greeks and was trying to provoke a 3 vs 1 war and was building up a navy.  Then I notice a sharp happiness drop and look at the tourism screen and it looks like Indonesia is going to win a culture victory without a way to stop them.
![image](https://cloud.githubusercontent.com/assets/23019463/24030026/9e1ab3d6-0a97-11e7-8c3f-d620b713daa6.png)

I don't think it was a bug, but wouldn't it be more fun to delay this kind of victory somehow?  Maybe have it unlocked in tier 3 Ideologies? There was really nothing I could do.  He has an 8 tech lead so it will take some time to capture some of those culture cities and he will win before that, even if I survive the unhappiness waves.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by oalzubbi** [comment]
You should get info addict mod. It will allow you to see how much culture, tourism, gold, etc. each civ produces. You might be able to predict this type of thing (or at least trace it if it really is a bug)
