### ISSUE TITLE
Different information about specified tile output in two tooltips

### ISSUE THREAD

**Issue by Tesciu** [LoneGazebo/Community-Patch-DLL#3163]
_1. Mod version (i.e Date - 4/23):_
Mod ver.: March 7th (2.3.7)​, with EUI
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Different information about specified tile output in two tooltips as in screenshots. Worker has to be on the tile, to see second information/tooltip.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

[Pictures.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/853057/Pictures.zip)

**Comment by Radost** [comment]
The first tooltip shows the potential yields for all applicable improvements on this tile.
The second one show the total possible yields for the improvement already present on a tile.

**Comment by Tesciu** [comment]
Maybe im not understanding game interface. Im not sure. But look please at next two attached pictures below. **Food** output on the first tooltip (data1) is **bigger** than on the second tooltip (data2).
In my previous set of attached files it was reverse order: food was **smaller** on the first tooltip (obraz3) than on the second tooltip (obraz 4).
[Data.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/856102/Data.zip)
