### ISSUE TITLE
AI is obsessed with Cover

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3166]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Basically AI very often gets the Cover promotions on its troops. Even when I have not a single ranged unit and am preparing to swamp them with Horsies while I'm the only one they can fight with at that point, they'll insist on giving their Spears and Warriors Cover.

**Comment by TechpriestEnginseer** [comment]
Considering that most of the time, humans always win against AI due to their superior ranged troops I'm not surprised the AI favor this at all.

**Comment by Vyyt02** [comment]
Well, don't humans put cover on most of their frontline melee units as well? Also, maybe the AI does not know that you don't have any ranged - they cannot see inside of your territory.

I'd be in favour of more randomization of the AI promos though. If they put cover on everything, then it does not make much sense.
