### ISSUE TITLE
Bug with Tithes Enhancer Belief

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#3167]
_1. Mod version (i.e Date - 4/23):_
3/7 

_2. Mod list (if using Vox Populi only, leave blank):_
Thal's flags

_3. Error description:_ 
Tithes not giving 200 gold

_4. Steps to reproduce (optional):_

I'm playing as Babylon and I conquered the Holy City of Carthage. I had missed founding so I had tons of faith. The turn after I conquer I get a great prophet. I use that prophet to get tithes and Mandirs. The next turn I get another great prophet, who I send to go spread the faith. However, I do not get 200 gold per spread. What's strange though is that I'm still getting the gold and faith per 6 followers in a foreign city. I have fully annexed carthage and built a courthouse so the city wasn't in resistance either.
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
If the cities in question had already been converted at some point you won't get the bonus again.

**Comment by oalzubbi** [comment]
Right, but I'm not getting it from other cities either

**Comment by oalzubbi** [comment]
Would a save file and/or a log file be needed to better diagnose this issue?
