### ISSUE TITLE
Statecraft "Great Person" Finisher Providing other Civ's Unique GPs

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#3168]
_1. Mod version (i.e Date - 4/23):_
3/7 version

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Playing as Ethiopia and went for a Diplomatic victory, so went 6/6 in Statecraft and started receiving random Great People as part of the finisher. However, Venice and Mongolia were also in play, and over time I randomly received both a Merchant of Venice and a Great Khan as gifts from my CS Allies. I've never seen this happen before, and I'm not sure if this is a bug or a feature. It would make sense that "receive a random Great Person" means it could also be one of the GPs that are unique to certain Civs, but given that both Mongolia and Venice were in the game, I figured it might be a bug. Needless to say, having access to these Unique GPs as Ethiopia was a great boon.

I can post a save game with both GPs in effect if you want (although I used the Merchant of Venice to make a Colonia).

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
That's a feature - those are in the list. Same as vanilla.

G
