### ISSUE TITLE
Settlers as resistors

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#3171]
_1. Mod version (i.e Date - 4/23):_

3/7

_2. Mod list (if using Vox Populi only, leave blank):_

-

_3. Error description:_ 

When I burn down a city, I often see settlers apear as resisting units.

_4. Steps to reproduce (optional):_

**Comment by bigcat88** [comment]
yeah, I see that too in my last game.
