### ISSUE TITLE
Definite Correlation

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3172]
There's a definite correlation in event frequency when you apply events through Lua. If you apply a lot of player events through Lua, you will never see a player event randomly again.

**Comment by LoneGazebo** [comment]
Is this related to the cooldown stuff we discussed earlier? Are you setting all of your cooldown options to their lowest available values? If needed I can add a 'cooldown-agnostic' bool that allows an event to bypass all of that.

**Comment by TechpriestEnginseer** [comment]
I'm setting it to the lowest value of 1 and I believe since there are so many events being done through Lua. It plays a major part of event frequency.

**Comment by LoneGazebo** [comment]
Have you tried setting it to zero? I think zero is a supported value.

**Comment by TechpriestEnginseer** [comment]
Doesn't seem like that it helps.

**Comment by LoneGazebo** [comment]
Duh, I'd put in a minimum event cooldown threshold. Removing.
