### ISSUE TITLE
Lua error when mousing over Incan mountain city

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#3178]
_1. Mod version (i.e Date - 4/23):_
3/7 (No-EUI)

_2. Mod list (if using Vox Populi only, leave blank):_
IGE (v 39)
Quick Turns (v 10)

_3. Error description:_ 
Whenever you mouse over an Incan city that has been built on a mountain, whether in or out of combat, a lua error occurs in PlotMouseoverInclude.lua

Possibly related to #3147 

_4. Steps to reproduce (optional):_
While running FireTuner, mouse over a city built on a mountain by the Inca

---------------------------
_Supporting information:_

Runtime Error: D:\Users\\%user%\Documents\My Games\Sid Meier's Civilization 5\MODS\(6b) Community Balance Overhaul - Compatibility Files (No-EUI)\LUA\PlotMouseoverInclude.lua:14: bad argument #_1_ to 'LocaleLookup' (string expected, got nil)

stack traceback: 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;=[C]: in function 'LocaleLookup'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D:\Users\\%user%\Documents\My Games\Sid         Meier's Civilization 5\MODS\(6b) Community Balance Overhaul - Compatibility Files (No-EUI)\LUA\PlotMouseoverInclude.lua:14: in function 'GetImprovementText'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D:\Users\\%user%\Documents\My Games\Sid Meier's Civilization 5\MODS\(6b) Community Balance Overhaul - Compatibility Files (No-EUI)\LUA\PlotMouseoverInclude.lua:307: in function 'GetImprovementString'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Assets\DLC\Expansion2\UI\InGame\PlotHelpManager.lua:193: in function 'Level1Tip'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Assets\DLC\Expansion2\UI\InGame\PlotHelpManager.lua:80: in function <Assets\DLC\Expansion2\UI\InGame\PlotHelpManager.lua:52>

**Comment by LoneGazebo** [comment]
It is benign.
