### ISSUE TITLE
AIs are very peaceful

### ISSUE THREAD

**Issue by Sigral** [LoneGazebo/Community-Patch-DLL#318]
This one may or may not be related to CPP. It may be CSD, Civ IV Diplomacy, or the Less Warmonger Hate mod (the only other mod I have that pertains to the AI). 

Even after 200 turns, there were no wars for 15 of the 22 Civs in game (the other 7 were on the other side of the world and thus I could not monitor them). I had Mongolia, Zulus, Shaka, etc and prime targets for all of them. Still, there were no wars whatsoever. 

There was only war and that was between Siam and I, after he got upset I stole his CS alliance with Yerevan. 

Is this peacefulness a noted part of CPP?

**Comment by LoneGazebo** [comment]
Less Warmonger Hate may actually be pushing your warmonger scores negative. I wouldn't use it (you don't need it in CBP anyways).

G

**Comment by Sigral** [comment]
That could very well be the cause. In fact, every time I met a new Civ, they were automatically friendly (labeled as such in the diplomacy screen). Since this was my first CPP play through, I wasn't sure if it was unintended. 

I'll do another play through without LWH and try again. The mod affects ALL Civs and not just the player (I note this because even warmongers like Mongolian didn't prey on their neighbors).

**Comment by LoneGazebo** [comment]
Warmonger values are calc'd for all civs, AI included.
