### ISSUE TITLE
No resource on map!

### ISSUE THREAD

**Issue by Magelangrado** [LoneGazebo/Community-Patch-DLL#3180]
_1. Mod version (i.e Date - 4/23):  latest, by 04/06/17

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/901591/Logs.zip)

_2. Mod list (if using Vox Populi only, leave blank): non-EUI Vox Populi

_3. Error description:_ Maps can't load any or very few resources (usually 1 or 2 Wheat sources) I tried it in several maps, British Isles the only which displayed a bit more. Tried also in many "Resources" options (legendary balance, standard, abundant...), a bunch of map types and all sizes possible. Anyone got any ideia what might be going on? And how to fix this? I'm ataching my Logs file. :-)

**Comment by LoneGazebo** [comment]
Usually happens if your Civ isn't up to date. .279 is latest.
