### ISSUE TITLE
AI uses the player's leader scene to declare war

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#3183]
_1. Mod version (i.e Date - 4/23):_
3/7

_2. Mod list (if using Vox Populi only, leave blank):_
IGE (v 39)
Quick Turns (v 10)

_3. Error description:_ 
Playing as Denmark, while processing Brazil's turn, a blank leaderhead representing the player's civilization is used to make a DoW. The leaderhead's diplomatic relation does not match Brazil's or any other civ, and seems to represent the player's relation with themself.  After this occurs, the "There is no scene loaded for this leader!!" error appears on every civ's leaderhead despite functioning properly. The following turn Sweden declares war, but his scene is shown properly.

Similar to #2939 and #2800
 
_4. Steps to reproduce (optional):_
I'm not exactly sure what causes this, but passing the turn in the saves attached will cause this to occur.

---------------------------
Supporting information:

@TechpriestEnginseer mentioned

> Maybe it's rare that a major civilization has ever declared war on someone for breaking a promise while conquering it as well. 

Brussels, one of the city states protected by Brazil that I broke my promise of not bullying toward, is forced to declare war on Brazil due to my defensive pact with America, their ally. Choosing not to bully them or deleting this city state before passing the turn prevents Brazil from prematurely declaring war, avoiding the bug. Waiting for several more turns allows Brazil and Sweden to declare war simultaneously without issue, as they were already preparing to do so. Although I've been at war with this and other city states, I have not conquered any.

There seems to be only one related lua error, but it occurs for every game on startup:

> LeaderHeadRoot: This is the modded InfoTooltipInclude from CBP- CSD
> LeaderHeadRoot: Could not find discussing player!

Attached are three saves: the first, one turn before the bugged DoW and before I had bullied Brussels; the second, the turn of the bugged DoW and after I had bullied them; the third, the turn of the non-bugged DoW. Simply command all units to fortify/sleep and change all production to a yield for the earlier save. The bugged DoW occurs on turn 224, and the normal DoW on turn 227.

AI logs for Brazil and Brussels, along with the usual logs, are also included.
[LeaderHead error.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/905017/LeaderHead.error.zip)

Spooky Doppelganger
![](https://i.imgur.com/d9nlGCH.png)

Brazil, prior to declaring war
![](https://i.imgur.com/7057bGS.png)

Brazil, after his DoW
![](https://i.imgur.com/P59wKLF.png)

**Comment by bryan317** [comment]
This happened to me in my last game.  Resetting the game seemed to fix it for some reason.  I was surprised because i had never seen "Emotionless" as a stance before.  Which was referring to me of course lol.  Of course when another DoW would occur it would happen again.  Restart would fix it.

**Comment by LoneGazebo** [comment]
Can't reproduce, but it is probably related to quick turns or something pushing a graphical update before a turn is properly ended, thus the 'active player' logic for the UI is slightly behind.

**Comment by HalfEmptyMug** [comment]
Reproduced in the latest version (hotfix version 4/21, no-EUI) without IGE or Quick Turns enabled. This seems directly related to city state bullying; specifically, when you demand tribute from a city state multiple times and push their protector to declare war. In both cases I promised to stop bullying city states under a civ's protection, but continued to do so (the DoW occurs immediately after a demand is made, but not necessarily the first time the promise is broken). Also, in both cases the offending AI was already relatively hostile due to my warmongering, likely already preparing to declare war. I have only recently tried strategies that involve bullying several city states multiple times, which explains why I've only recently come across this. Whether the tribute is normal or heavy does not affect the error.

It's relatively difficult to reproduce, but attempt to play a warmongering civ who is very hostile to city states. When asked to stop bullying a city state under a civ's protection, agree, but continue to do so and push them to hostility through the conquest of other civs. When that civ is preparing to declare war on the player, demand tribute from one of their protectorates and this should occur. 

Attached is a save on the turn of the error. Bullying either Prague or Zanzibar will cause the error to occur when processing the turn for Polynesia. Passing the turn without bullying either city state will prevent the error, but bullying them on any of the following turns will cause it.
[LeaderHead error 2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/963188/LeaderHead.error.2.zip)

I'm not sure if @bryan317, @TechpriestEnginseer, or @lucperrin can corroborate this exact cause, but

>  it is probably related to quick turns or something pushing a graphical update before a turn is properly ended, thus the 'active player' logic for the UI is slightly behind.

Something about bullying a city state seems to _force_ their protector to declare war, where simply making them angry through discussion or other means doesn't. It's possible that more broadly breaking a promise (such as spying) under the right circumstances could also cause this, though I haven't experienced it. 

Also, I'm not sure if you were unable to reproduce the leaderhead error, or simply unable to load the saves, but the DoW itself may also be an issue.

**Comment by TechpriestEnginseer** [comment]
I can say the reason is exactly correct!

**Comment by LoneGazebo** [comment]
I'll look. I think that's a CSD triggered event that may not have ported over correctly.

**Comment by bryan317** [comment]
Nice work.  Now that you mention it, this was how it occurred.
