### ISSUE TITLE
Winged Hussar Heavy Charge

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3185]
_1. Mod version (i.e Date - 4/23):_

current and probably all before it
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I think this bug carries over from vanilla. Either WH deals no bonus damage if unit doesn't retreat, or at least there's no notification of such a thing in battle text. No noticeable difference though.

**Comment by TechpriestEnginseer** [comment]
Nope, they deal its damage.

**Comment by Enrico-Swagolo** [comment]
No they don't. Look at the text. All the bonuses/etc are from being lvl 10, nothing comes from Heavy Charge which I've proven as one screenshot has a clear spot the unit can retreat to (there were more but I didn't include to lower MBs).
[screenshots.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/921799/screenshots.zip)

If it's not included in the battle text, then please explain to me how much damage it does, in what conditions.

**Comment by TechpriestEnginseer** [comment]
What am I supposed to be seeing?

**Comment by Enrico-Swagolo** [comment]
...Ah okay, I didn't know that because it doesn't say about that. But how much does it actually do then? In an actual game (not against warriors with advanced start I did quickly to check) I didn't notice a real difference between non-retreating and retreating damage.

**Comment by Enrico-Swagolo** [comment]
Thanks for the extensive edit-explanation, seems pretty bad but not bugged. If it's that small a bonus damage it's no wonder I didn't notice without knowing it exists, especially since it not only requires those things but also for the unit to be so surrounded, it can't retreat.
