### ISSUE TITLE
[Suggestion] Pacifist AI / no-first-blood mode

### ISSUE THREAD

**Issue by wetfeet2000** [LoneGazebo/Community-Patch-DLL#3187]
_1. Mod version:_
12/14/16, 10/28/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Suggestion description:_ 
When disabling Domination victory in the multiplayer stock/no-mod game, the AI refuses to declare war or fight unless you declare war against it first. (this doesn't apply to barbarians of course) It acts as a nice handicap for people who essentially want to ignore the entire military aspect of the game and play a more relaxing version. I was bummed to find out that the AI will still declare war / draw first blood when disabling domination victory in this mod. 

Can you add an extra option on the setup screen that only applies when domination victory is disabled to replicate this behavior? Something along the lines of "no-first-blood" or "humans must attack first"?

**Comment by LoneGazebo** [comment]
This falls outside of the scope of the project - the AI will fight when it suits them.
