### ISSUE TITLE
If I meet the player, I should meet the vassal too.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3188]
If we're following the civ 4 system, that is. I just recently found out that Napoleon was the one behind the puppetmaster with his 5 vassals undiscovered in his continent..

**Comment by LoneGazebo** [comment]
5 vassals?!

**Comment by TechpriestEnginseer** [comment]
I was surprised they hadn't rebelled, but it was an island map so Napoleon must have considered the problems of maintaining a navy to capture all 5 capitals or something like that.

**Comment by LoneGazebo** [comment]
Recursive meetings like this are tricky to get right, so I'm going to leave as-is.
