### ISSUE TITLE
Diplomacy Screen goes "blank" after accepting a deal

### ISSUE THREAD

**Issue by Sigral** [LoneGazebo/Community-Patch-DLL#319]

**Comment by Sigral** [comment]
Accidentally hit submit before I could describe the issue. After an AI or the player accepts a deal, everything except their portrait goes blank. The normal "demand, trade, discuss, goodbye" buttons are missing. I have to press escape to leave, and that cancels the deal that was just signed.

**Comment by LoneGazebo** [comment]
It this in 6-9? Also, using any other mods than the 'standard' ones?

G

**Comment by Sigral** [comment]
Indeed it is. I just installed everything over the weekend, so everything on CPP page (non-EUI version).

**Comment by Hokath** [comment]
i get this too
