### ISSUE TITLE
Siege Accuracy

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3190]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

It says it gives +10% against full health enemies but it still provides +10% against cities instead. Applies to I II and III

**Comment by LoneGazebo** [comment]
Eh? Accuracy looks fine to me.

**Comment by Enrico-Swagolo** [comment]
Maybe you are on a different version than the one you've uploaded? Siege's Accuracy description says it provides +10% against Full HP, but it does what it should (10% against cities)

**Comment by LoneGazebo** [comment]
Accuracy I-III is the same for Siege and non-siege units. Not sure what you're seeing. Screens?

**Comment by Enrico-Swagolo** [comment]
Ahh, I get it. I misunderstood your post on civfanatics. I thought by saying
"Siege units still get the city attack bonus promotions as before. So they're unique. " you meant Accuracy for Siege is like it was previously. Misinterpretation, then.

But there is still a bug. I've been attacking a city with a Catapult with 1x Accuracy and he's definitely had displayed a bonus against cities when I've hovered over one before attacking it.

**Comment by LoneGazebo** [comment]
I'll look but it worked fine for me yesterday. And yeah 'city attack promotions' = Siege I and II

**Comment by Enrico-Swagolo** [comment]
Yeah, checked again and it definitely appears. When I've attacked with a Siege with Accuracy 2, it had some sort of 20% combat bonus appear when attacking the city. It levelled up the next turn, I picked up Accuracy 3 and the combat bonus turned to 30%.

**Comment by LoneGazebo** [comment]
Was there a full-health military unit in the city?

**Comment by Enrico-Swagolo** [comment]
Nope, it was hurt. It (and the city) was being pounded  for a long time, unless it has ninja-healed so much.
