### ISSUE TITLE
Alright my game works fine up until actually playing the game, i am playing the most recent version to date, now it works fine until I press the Begin journey button.  It then pops up the corporation tab, which would be fine if i could close it. Now the reason I can't close it is because it doesn't register that its even there because i can still move my units if I use the keyboard. Yet i can't found cities, nor can I see a single thing i'm doing. If i could get help that would be much appreciated

### ISSUE THREAD

**Issue by Generalfletch** [LoneGazebo/Community-Patch-DLL#3192]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
You have a mod conflict sounds like.

**Comment by Vyyt02** [comment]
Yeah, wasn't some older version of JFD's mods causing this? Cannot remember which mod it was (or maybe I am misremembering completely).
