### ISSUE TITLE
Weird luxury valuing (situational

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3194]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Sometimes AI will want to give you insane amounts of Gold for a luxury. I see Augustus on another continent and he considers the value of my Copper to be 3000 (!). He doesn't have any Gold or GPT to trade. I often see AIs that have no Gold have such weird Luxury desires, but haven't seen one with Gold value a luxury so much.

**Comment by LoneGazebo** [comment]
He could probably get a bunch of WLTKD from it.
