### ISSUE TITLE
crusader zeal

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3196]
_1. Mod version (i.e Date - 4/23):_
4-21

_2. Mod list (if using Vox Populi only, leave blank):_
world congress reinformation

_3. Error description:_ 
As I previously reported, crusader zeal still works for naval units, and in description there are only land units.
![20170423204234_1](https://cloud.githubusercontent.com/assets/13381981/25315896/912c59ae-2865-11e7-8080-525ebff218e7.jpg)

**Comment by LoneGazebo** [comment]
Are you sure the bonus is being applied, and that it isn't just a UI quirk?

**Comment by bigcat88** [comment]
how to know it clear? I just post what I see, how can I check if it is really applied?

**Comment by phantommaxwell** [comment]
Do the math;  30 * 1. 45 = 43.5 RCS 

It seems to be just a UI quirk

**Comment by bigcat88** [comment]
ah, ok - thanks )
