### ISSUE TITLE
Siege Units no longer need to setup

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3197]
This appears to be a change for the CBO that slipped into the CP, as it's a rather significant gameplay change. That is, that Siege Units no longer need to setup and instead have a penalty in enemy territory (allowing them to move and shoot in neutral and friendly). Could you disable this in the CP, or at least make an option to do so, when you're prepping the next update? Thanks.

**Comment by MoiMagnus** [comment]
I am not sure it is possible. If I've understand correctly, they need to have the same militaristic AI in CP and full-VP, so some gameplay changed that were needed to have an efficient AI, were added to VP, for example : 

- Siege Units no longer need to setup
- Naval unit, even in ancient era, can go into deep water, but cannot stop on it (deep water tiles behave as occupied tiles)

So I don't know if what you're asking for is possible.
(But if it is possible, I'm favorable to an option to do so)

**Comment by ilteroi** [comment]
correct. can't have the improved AI without some compromises. having too many options is not testable and not maintainable.
