### ISSUE TITLE
Didn't get called into Defensive Pact war

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#3198]
_1. Mod version (i.e Date - 4/23):_4/21

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP
Enginseer's version of E&D and Community Events
FlagPromotionsV7
More Great Works, Great Prophet Historical Names, Great People Pack, More Great Musicians, Civ Linked Great Generals
Favorite Religion Randomizer, Historical Religions
Celtic City Names, Iroquoian City Names, Randomize City Names
My own thing that does various things SQL type stuff
Starting Scout
Tectonic Map

_3. Error description:_ Shaka declared war on Brazil, who I had a DP with, but I didn't get called in.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20170425193553_1](https://cloud.githubusercontent.com/assets/16260521/25412279/a30af244-29ef-11e7-9794-852d951b6f5c.jpg)

**Comment by Zanteogo** [comment]
I can confirm this is occurring for myself as well. Unlike the original poster I have no other mods but Vox Populi.

**Comment by bigcat88** [comment]
Maybe I had the same issue, but I am without the save game, but I was with DP with Greece in my game, and when India dow Greece nothing happens for me(I wasn't in any war during game, so I was able to declare war on India)

**Comment by bigcat88** [comment]
Yeah, in my new game def pacts don't work. Darius declare war on Spain, i am with def pact with Spain. Darius was allied with CS Cahokia, and i got war only with Cahokia, not Darius. Need a savegame at turn after Darius declared war?
