### ISSUE TITLE
Buildings (v6-9)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#320]
1.Burial Tomb
It doesn't have the resource-based bonuses(Truffles ,Cotton and Fur).

2.Siege Foundry
Jungles don't gain +1 Production.

3.Stable and Ducal Stable
Would you please recheck their settings and descriptions?
Stable has +1 Base-Production. Pasture-resources gain +1 Production.
Ducal Stable has +3 Base-Production. Pasture-resources gain +3 Production & Gold.

**Comment by LoneGazebo** [comment]
Fixed, thanks!
