### ISSUE TITLE
mysterious CS air craft carriers

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3204]
![image](https://cloud.githubusercontent.com/assets/1358966/25516601/c375e57c-2beb-11e7-89e7-75ba2c8c96ba.png)

how did it get there?

**Comment by ilteroi** [comment]
but wait, there are more!

![image](https://cloud.githubusercontent.com/assets/1358966/25516648/0b43b3a2-2bec-11e7-9f32-b3a1379655d5.png)

![image](https://cloud.githubusercontent.com/assets/1358966/25516667/283e0d5e-2bec-11e7-9965-c8f48e601e87.png)

**Comment by Radost** [comment]
Vanilla AI loved to spam carriers with obvious results.

**Comment by LoneGazebo** [comment]
Ha. CS shouldn't be making carriers anyways. Bad me.
