### ISSUE TITLE
late game oddities

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3205]
so i left this game running in observer mode until 2300 AD. china has conquered the whole world and won long since. they have 33 cities with average population 85 and 350 military units. however, some things are odd:

- GPT is -21k, because of unit upkeep of 49k, meaning 140 gold per unit per turn!
- happiness is +5.2k, mainly because of +5.5k for "global building happiness", equivalent to roundabout 2 happiness per citizen!
- "population" seems to be INT_MAX

![image](https://cloud.githubusercontent.com/assets/1358966/25517340/3fd73564-2bef-11e7-8d03-82ff1c22d723.png)

**Comment by bigcat88** [comment]
Can u look at some games on AI's unit limit number? Cause in some my games I noticed that some AI has more units that limit allows and got penalty on production and growth. Usually from 2 to 6 units. I just sometimes use IGE to observe the world, and noticed this thing. This thing is not very often, see it in late ancient/classical era.

**Comment by LoneGazebo** [comment]
Well they get 10 happiness every time they research future tech. So that's that. Unit maintenance is also calculated by techs owned, which I think includes each iteration of a repeatable tech.

**Comment by ilteroi** [comment]
so global building happiness depends on tech? but anyway it would take several hundred future tech iteration to get to +5.5k ...
