### ISSUE TITLE
mysterious city state population explosion

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3206]
check cape town and zansibar. don't know how that happened, but it seems implausible

![image](https://cloud.githubusercontent.com/assets/1358966/25544588/6449cf9e-2c5b-11e7-850f-bb9d57551b8f.png)

**Comment by ilteroi** [comment]
turns out they get an "empire modifier" of +30% food. what's that for? on prince level. not every CS seems to get it ...

**Comment by TechpriestEnginseer** [comment]
Random Event? WLTKD? Golden Age?

**Comment by LoneGazebo** [comment]
Could also be the CS food modifier global value.

**Comment by ilteroi** [comment]
but only two citystates had that modifier. so it wasn't global.

**Comment by LoneGazebo** [comment]
Might've been WLTKD?
