### ISSUE TITLE
splash damage affects enemies with are out of range

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3207]
is that by design?

**Comment by LoneGazebo** [comment]
Yeah. It is a pure directional loop. Otherwise it'd be hard as a player to conceptualize damage.

**Comment by ilteroi** [comment]
is it? i don't think so: everything outside of the red ring should be safe.

**Comment by LoneGazebo** [comment]
We'll try it out.
