### ISSUE TITLE
AI visiblity

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3209]
so i hacked the observer mode to use the visibility of the player you want to come back as.

results are ... mixed. observe:

![image](https://cloud.githubusercontent.com/assets/1358966/25586889/bd307d9a-2ea1-11e7-9606-63e78f813b4d.png)

![image](https://cloud.githubusercontent.com/assets/1358966/25586903/d4a8d418-2ea1-11e7-91fa-2ef98679a7f0.png)

some tiles owned by assyria aren't even visible, while others are visible without an obvious reason. maybe there's a bug there?

**Comment by LoneGazebo** [comment]
When you actually step into the player, does it remain the same way?

**Comment by ilteroi** [comment]
need to test more. of course most probably the problem is with my hack.

anyway it seems the visibility count for one of the falsely visible tiles is zero (for assyria), as it should be.

**Comment by LoneGazebo** [comment]
My guess is that the hack isn't accounting for a unit that moved through there. In any case I like the idea of giving the AI artificially-larger 'vision' of tiles in its territory and outside of its territory. That should be easier for us to implement than a method of pseudo-remembering where units are/were in the FOW.

**Comment by ilteroi** [comment]
it fixes itself when observer mode ends. seems like the initial FOW state is set correctly but never updated afterwards. probably a bug in the engine, but then again the whole thing is rather undocumented.

**Comment by LoneGazebo** [comment]
Sounds like it.

**Comment by ashendashin** [comment]
I actually meant to bring this up and forgot.

![tile bug 1](https://cloud.githubusercontent.com/assets/21032378/25588147/284e511a-2e75-11e7-83cb-562dd9cfe9e7.PNG)
![tile bug 2](https://cloud.githubusercontent.com/assets/21032378/25588149/2b1a3e36-2e75-11e7-9902-777ca69e950f.PNG)
![20170410122002_1](https://cloud.githubusercontent.com/assets/21032378/25588164/35d34836-2e75-11e7-8311-0d05550484cd.jpg)
