### ISSUE TITLE
Barbie camp aggression

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3210]
_1. Mod version (i.e Date - 4/23):_
current 1st may

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
MOve a warrior next to a barbie camp, barbie will attack the warrior until it dies. Even over river.

**Comment by Enrico-Swagolo** [comment]
You don't even need to move next, a warrior just got to 10 hp attackingmy scout as soon as he saw him, after which I got free culture and claimed the camp.

**Comment by LoneGazebo** [comment]
@ilteroi we got angry barbies again, it seems. Or @Enrico-Swagolo is up to his old tricks.

**Comment by Enrico-Swagolo** [comment]
More things I've noticed - all barbies will leave their camps as soon as they see things they can attack in what their line of sight probably is. They'll go back to camp to heal once they're at lower red HP, unless they die when attacking which happened once when a brute was at higher red/lower yellow HP, attacking over river. They're reckless. Sometimes melee barbies will even attack at lower red HP, but that typically requires the enemy to also be in the red.

**Comment by bigcat88** [comment]
yeah, start a new game today and see such behaviour. barbarian just run from camp to me.

**Comment by ilteroi** [comment]
@g: can't reproduce, must be one of your changes ...

**Comment by LoneGazebo** [comment]
I didn't mess with barbs. But I'll look.

**Comment by ilteroi** [comment]
ah, i see you pushed an update ... flanking change wasn't good? guess the combat preview needs to change as well

**Comment by LoneGazebo** [comment]
Flanking counts for all tiles around the unit, not just the 'shared neighbors.' I restored it to the prior version but retained your other optimizations.

**Comment by ilteroi** [comment]
it was an experiment ... but the UI showed predictions based on the old model, so it wasn't good anyway

**Comment by ilteroi** [comment]
can reproduce it now, apparently they think my warrior is a civilian. must be due to your tactical target changes. the checks used to be hierarchical ... now they aren't anymore.

when did the barbs start to leave camp for capturing civilians btw?

**Comment by LoneGazebo** [comment]
There are redundancies in the tactical targeting now (I took out the hierarchy) because some things, like defensive bastions, were rarely getting called as other target types would 'claim' the plot. The weights should sort things out now. If we can see what barbarian tactical move is making the move we can see where the issue comes from.

**Comment by ilteroi** [comment]
i understand the rationale, but something seems to be broken ... they don't seem to pick up ruins (and maybe the many empty camps are also affected).

![image](https://cloud.githubusercontent.com/assets/1358966/25638060/684b543a-2f87-11e7-9b6b-ac5e9e63a54c.png)

**Comment by LoneGazebo** [comment]
Hmm, that is strange. I'll take a look. I didn't notice such problems last night but I also wasn't looking for them explicitly.

**Comment by ilteroi** [comment]
it's probably better to restore the exclusive logic and emphasize the defensive bastions by simply changing the order of the checks

**Comment by LoneGazebo** [comment]
For what it is worth the issue seems to be that barbarians were told to consider all units 'high priority civilians' regardless of whether or not they were civilians. So the attacks were actually attempts to capture civilians.

**Comment by ilteroi** [comment]
yeah, that much was clear .... but now it seems they aren't even building roads anymore?

![image](https://cloud.githubusercontent.com/assets/1358966/25640628/8b870378-2f90-11e7-9980-49a9fc9ca7d6.png)

this is with the YAEMP scenario .... 22 civs and not a single road tile

**Comment by LoneGazebo** [comment]
roads aren't tied to tactical AI, though. I haven't touched roads, that I can say for sure.

**Comment by LoneGazebo** [comment]
I see roads...

![image](https://cloud.githubusercontent.com/assets/7849458/25641473/406b39fa-2f62-11e7-9380-4f4da259295e.png)

**Comment by Mitchsp** [comment]
Sorry for the meddling. I'm following this issue and awaiting for starting a game with the new version.
Can we expect a hotfix today/in the next days? Thanks

**Comment by LoneGazebo** [comment]
@Mitchsp In a bit yep.

**Comment by Mitchsp** [comment]
Thanks for the quick answer and for being so diligent and altruistic with the project.
