### ISSUE TITLE
Crash upon pressing "next turn"

### ISSUE THREAD

**Issue by lorduc** [LoneGazebo/Community-Patch-DLL#3211]
_1. Mod version (i.e Date - 4/23):_
may 1st

_2. Mod list (if using Vox Populi only, leave blank):_
43-civ Vox Populi (no EUI)
Legendary Earth mod by Dark_Jedi06 (https://forums.civfanatics.com/threads/legendary-earth-mod-lem.386128/)
_3. Error description:_ 
on certain maps, such as "earth" "archipelago" and the maps mentioned in the mods, after founding my first city, choosing production and research, as soon as I press next turn, the game crashes to desktop!
however if I use the "giant earth" from yet not another earth mod, then the game works fine

I had a similar issue with older versions of Vox Populi, however it would just say "processing turn for barbarians" as soon as the map launched and then instant defeat!

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I need your database logs. Enable logging if you have not, attempt to run, and then post them.

**Comment by lorduc** [comment]
ok, so
before all these problems occurred, I had added a mod which added new resources, the mod was called exploration extended or something like that. 
i noticed some resources had wrong icons, or simply just blank white images, for example coral and lapis.

so I thought maybe its a mod conflict, so i deleted the new mod which added the new resources, however the icons for coral and lapis were still blank, so I went all out and fully reinstalled my game and Vox populi thinking its a weird interaction between mods. 
that fixed everything, great. HOWEVER, I edited the two WorldChanges.sql files in the mods folders, so i could put cities closer together, then again, i saw the icons for coral and lapis being fully white, and the game CTD upon pressing "next turn".
this time i just deleted everything in my MODS folder, and readded them.
that again fixed the issue, and i started a game without a problem.
HOWEVER :( after about 100 turns in game, it says processing turn for Canton pirates, then it freezes, then I get a windows error saying civ 5 has stopped working and then it crashes to desktop.

**Comment by lorduc** [comment]
Here are all the modes im using: 

(1) Community Patch
(2) Community Balance Overhaul
(3) CSD for CBP
(4) Civ IV Diplomatic Features
(5) More Luxuries
(6c) 43 Civs CP
[BNW] Colonialist Legacies - Vietnam ft. Trung Sisters (v 1)
[BNW] Colonialist Legacies Vietnam CBO Compatibility (v 1)
AI - Warmonger Adjustments (v 4)
Buildings - Storage Yard and Stockpile (v 2)
Canton Pirates CBO Compatibility (v 1)
Canton Pirates- Ching Shih (v 1)
Diplomacy - By Numbers (v 1)
Global - 2 Units Per Fort (v 1)
Global - 3 Units Per City (v 1)
Global - Air Routes (v 2)
Global - City State Airbases (v 4)
Global - City Working Distance (v 7)
Improvement - Airbases (v 12)
Improvement - Tunnel (v 5)
Ingame Editor (v 39)
Mechanized Infantry with Soldiers, Resized (v 2)
Music Changer (v 2)
R.E.D. Modpack (v 27)
Reforestation (v 9)
Resolutions - Political Voting (v 1)
Sukritact's Events and Decisions (v 3)
Tech - Satellites Reveal Cities (v 10)
UI - Trade Routes Enhancements (v 7)
Units - Brigantine (v 1)
Yet (not) Another Earth Maps Pack (v 24)

note that ive always been using these mods with older versions of Vox populi without any problem, EXCEPT for these mods:

Mechanized Infantry with Soldiers, Resized (v 2)
Music Changer (v 2)
R.E.D. Modpack (v 27)
Canton Pirates CBO Compatibility (v 1)
Canton Pirates- Ching Shih (v 1)
[BNW] Colonialist Legacies - Vietnam ft. Trung Sisters (v 1)
[BNW] Colonialist Legacies Vietnam CBO Compatibility (v 1)

so if there is a mod conflict its probably from these, but im too tired to test them out.

**Comment by LoneGazebo** [comment]
That's an awful lot of mods, I can't debug them. Remove the offending mods one by one until you find the crash.

G

**Comment by lorduc** [comment]
its probably one of these:

Mechanized Infantry with Soldiers, Resized (v 2)
Music Changer (v 2)
R.E.D. Modpack (v 27)
Canton Pirates CBO Compatibility (v 1)
Canton Pirates- Ching Shih (v 1)
[BNW] Colonialist Legacies - Vietnam ft. Trung Sisters (v 1)
[BNW] Colonialist Legacies Vietnam CBO Compatibility (v 1)

most likely the canton pirates since it crashes on "processing turn for Canton Pirates"
i also cant be bothered to check each one myself :D especially if i have to play at least 150 turns for each one(or who knows maybe even more)

ill just go ahead and attach my log files and my save games maybe that'll help

**Comment by lorduc** [comment]
how do i attach files D: it says "we dont support that file type" for both logs and saves

**Comment by lorduc** [comment]
[Oda Nobunaga_0139 BC-0525.zip.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/974085/Oda.Nobunaga_0139.BC-0525.zip.zip)
[Logs.zip.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/974087/Logs.zip.zip)

**Comment by ashendashin** [comment]
I think I tried out Canton Pirates once and ended up getting CTDs during their turn. @TechpriestEnginseer ?

**Comment by TechpriestEnginseer** [comment]
I'll have to think it is Canton Pirates due to their UA... that gives them a huge amount of ocean tiles.. and when they settle right next to an ocean...

**Comment by lorduc** [comment]
that's a shame I really wanted to play a game with Canton pirates in it!
Well I'll leave it to the civ expert Enginseer. if you ever feel like fixing it that would make my day 💃
please post it in Vox Populi Compatible Civilizations Showcase thread ill see it there!

**Comment by lorduc** [comment]
update: I used IngameEditor to delete her off completely, as ashendashin suggested, and the game no longer crashed, so Canton Pirates are definitely the problem!

**Comment by TechpriestEnginseer** [comment]
Yup problem solved. On low-end computers, Canton's UA triggering upon an ocean will cause a data overload to some computers will crash if they cannot handle the huge ocean tiles captured when settled by pioneers and colonists. I have restricted it to capturing coastal tiles only. Hopefully this should solve the problem. Sorry for the issue guys!

**Comment by lorduc** [comment]
That must be it! I have a laptop with a core i3 processor and Intel HD 3000 :(
have you posted the fixed version already ?
also thank you very much!!
