### ISSUE TITLE
Great People Abilities Dis-use

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3212]
Re-posting my post about the GP Ability problem as per the thread.

"This is definitely something introduced in the CP (or VMC), and from my testings IIRC it is to do with the DefaultUnitAI being different from the standard Great Person which has this ability. So, Germany's unique Great General has the GG AI, making it incompatible with the Great Scientist ability (science bulb). The same thing happens with de Gaulle's unique GG and the Great Writer ability (culture bulb)."

No rush to fix, but it seems to concern quite a few users.

**Comment by LoneGazebo** [comment]
I already fixed it in the 5/1 version. :)

G
