### ISSUE TITLE
Trade vLUES OFF

### ISSUE THREAD

**Issue by Txurce** [LoneGazebo/Community-Patch-DLL#3213]
_1. Mod version (i.e Date - 4/23):_5/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ trade values are too high

[Elizabeth_0118 AD-0075.sav.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/971585/Elizabeth_0118.AD-0075.sav.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
Can you elaborate ?
What do you mean by "too high" ? Does trade values are something as stupid as 9999999 for one ressource ? Or is it just  2 times too high or something similar ?
Does it concern any kinds of trade or just ressources ?
Does it goes in both ways ?
...

**Comment by Txurce** [comment]
Sorry, I was responding to Gazebo, and gave the details on the 5/1 thread.
Basically, it's turn 118 and I have two luxuries. Japan thinks they are
worth 238gpt. India values them at at 4495gpt and 4867gpt. Neither civ has
remotely that sort of gold on hand, of course.

Jorge

**Comment by ricanuck** [comment]
@Txurce : I checked your save, it was not 238 GPT, nor 4495 GPT... those were the values of the trade estimate, they do not translate 1 = 1 GPT. In fact, when adding the 2 GPT India had available, the trade became impossible. Something was off, but not as much as you are saying.

Anyways, hotfix is there, just wanted to clarify.

**Comment by Txurce** [comment]
Oh, good to know. Thanks for the clarification.

**Comment by ricanuck** [comment]
@Txurce : hey, good to help! By the way... Jorge? Si ese es tu nombre, obviamente hablamos espanhol, o no?

**Comment by Txurce** [comment]
Si, nací en Cuba.

**Comment by Txurce** [comment]
PS -

Y tú?

**Comment by ricanuck** [comment]
del Cono Sur... asumo que estas en los US? Donde?

**Comment by Txurce** [comment]
Vivo en Venice, California, pero esta semana estoy visitando a mi mama en
Miami... a si que no juego Civ hasta que regreso el proximo martes.

**Comment by ricanuck** [comment]
California, lindo! Yo vivo en British Columbia, Canada...

**Comment by Txurce** [comment]
My favorite photo of Vancouver.
