### ISSUE TITLE
Tooltip say puppet don't increase tech cost.

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#3215]
_1. Mod version (i.e Date - 4/23):_   
since 2/6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  
SET Text = 'Each ([ICON_PUPPET] non-Puppet) City you own will increase Technology costs by {1_Num}%.'

in UIText.sql, but i didn't see a changelog with this change, puppets increase tech cost, right? Maybe a copy/paste error?

reported initially by  https://www.reddit.com/r/civvoxpopuli/comments/68kp7r/are_puppet_cities_supposed_to_generate_the_huge/   
(with pics)

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
Puppets do not increase tech cost.

**Comment by supermerill** [comment]
You're right, a change i the 2-6 version.
As i didn't see it in your forum post, i missed it.
thanks
