### ISSUE TITLE
Tithe scales per city

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3216]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Get Tithes. The amount of Gold you get is following cities x 100, With 20+ ones in my grasp, converting a city got me 2000+ Gold.

**Comment by LoneGazebo** [comment]
Mm, forgot about Tithes scaling that way. I'll fix. Enjoy your boon. :)

**Comment by ricanuck** [comment]
hotfix or should I wait before starting a new one?

**Comment by LoneGazebo** [comment]
https://mega.nz/#!qNt0jCiL!6C-PsRTs9hGKm6mPIl2gXuWQsBs6yluxzNk9_182y2A

**Comment by ricanuck** [comment]
Genius.
