### ISSUE TITLE
settling on mountain yields should equal hill yields

### ISSUE THREAD

**Issue by kawyua** [LoneGazebo/Community-Patch-DLL#3219]
_1. Mod version (i.e Date - 4/23):_
version 5/2

_2. Mod list (if using Vox Populi only, leave blank):_
vox populi 
really advanced setup

_3. Error description:_ 
settling on mountain should have the same base yields as hills
right now it gives 1 more production than it should have with: 2f 3p 3g 1s 1f

_4. Steps to reproduce (optional):_
settle on mountain as inca

---------------------------
Supporting information:

Screenshots (optional):
<img width="678" alt="incamountain" src="https://cloud.githubusercontent.com/assets/12496046/25766524/0bedd370-31c1-11e7-8587-f5d73439e83c.PNG">

**Comment by Iamblichos** [comment]
Why should a mountain have less yield than a hill?

**Comment by LoneGazebo** [comment]
Balance issues for Inca in early game.
