### ISSUE TITLE
AIs throwing gpt at each other

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#322]
At first Ethiopia gifting me 471 gpt (which it declined afterwards due to https://github.com/LoneGazebo/Community-Patch-DLL/issues/321) was highly suspicious. 
https://i.imgur.com/LD05cGi.jpg
So I checked its gpt and it was like this:
https://i.imgur.com/8xU2R5f.jpg
Turns out Iroquois were feeding money to Ethiopia:
https://i.imgur.com/0BzmOt1.jpg
As you can see, they even have DoF, so Iroquois willfully given lots of money to the point they couldn't progress.

**Comment by LoneGazebo** [comment]
Are you sure the Iroquois gave this money? Did you look at the deal history?

**Comment by Radost** [comment]
Does the deal history even show AI-to-AI deals?
Anyway, there is no way to get 2k gpt at this stage without trading.

**Comment by valerian** [comment]
Some people also reported AI gifing gpt with a negative value

**Comment by Radost** [comment]
I haven't seen any gpt trade anomalies anymore so I presume the bug is gone.

**Comment by LoneGazebo** [comment]
Yay!
