### ISSUE TITLE
Food yield from allied maritime city states bugged.

### ISSUE THREAD

**Issue by Bloodrocution** [LoneGazebo/Community-Patch-DLL#3222]
_1. Mod version (i.e Date - 4/23):_
4/21

_2. Mod list (if using Vox Populi only, leave blank):_
![Active Mods list](http://puu.sh/vHmJF/4402d08921.jpg)

_3. Error description:_ 
Bonus food yield from allying a maritime city state for capital city is vastly reduced than the stated amount of food that is supposed to be added, and is nil (0) for all other cities.

![Maritime city state ally food received text](http://puu.sh/vHmPv/eebcadc0f7.jpg)

![Food from city states in capital city](http://puu.sh/vHnt6/1d3141b91f.png)

![Food from city states nil for other cities](http://puu.sh/vHnEF/02a2e2b662.jpg)
_4. Steps to reproduce (optional):_

I'm not sure if this has never not been occurring, since I only just recently on whim decided to take a closer look at the city breakdown of food yield and tally it all up. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Don't Maritime City-States add food to the capital/city's tile?

Those tooltips are from buildings that provide yield bonuses for having CS friendships or alliances.

**Comment by Bloodrocution** [comment]
>Don't Maritime City-States add food to the capital/city's tile?

>Those tooltips are from buildings that provide yield bonuses for having CS friendships or alliances.

Oh, I think you are right. The Scrivener's Office in my capital grants +1 Food in city for every city-state ally; I have 2 city-state allies, so that accounts for the 2 food there.

However, the food that I am supposed to be receiving in my cities and capital on the tiles is still not adding up with what the tool tip on the Maritime City-State ally screen says.

My capital city tile is producing 16 output of food:

- 7 are from Tradition social policies: +2 for opener, then +1(*5) for 5 policies unlocked = 7 food.

- 3 are from the base yield of the grassland tile it is founded on.

That's 10 food. According to the city-state screen, I am supposed to be receiving 7.5 food in my capital, yet I only have 6 food on the tile unaccounted for.

Similar story for my other cities in that they appear to be receiving only 1 extra food instead of the stated 2.5 food.

Good call on that, but there still appears to be something not quite right.

**Comment by TechpriestEnginseer** [comment]
grassland don't produce +3 food, they produce +2 food. 
Tradition only grants you +2 Food and +30% Growth(they were recently changed to buff late game)

That's +4 Food. +7.5 food = 11.5 food.

**Comment by Bloodrocution** [comment]
Yeah, my bad, 2 base food from the grassland.

This is what the Tradition policy is for the version of the mod I'm using says. I didn't update to the may hotfix yet, if that's where changes where made to it.

![tradition tree](http://puu.sh/vHqZM/7ab7b2be13.jpg)

**Comment by Bloodrocution** [comment]
Thanks for helping to clear that up. The only discrepancy now is 0.5 food. It seems like the game truncates the .5 value off of the 2.5 and 7.5 stated in the tooltip for the maritime ally.

**Comment by TechpriestEnginseer** [comment]
Well when you have a value of 0.5 and another 0.5 value, it'll equate to +1 Food. I'm uncertain however if 0.5 is rounded down or rounded up.

**Comment by LoneGazebo** [comment]
.5 rounds down. All works intentionally.
