### ISSUE TITLE
AI doesn't build Orders when attacked

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3223]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

So I am Spain. I got a nice religion in Orders + Mosques + God King. Despite my best efforts it has spread to a Swedish city just as I declared war on Gustavus, but when his city got converted, instead of getting an Order to make his walled city almost impossible to conquer with my weapons, he's decided to build several Inquisitors and Missionaries. 

When attacked, AI should always buy Orders in cities under attack imho. That's what I do.

**Comment by Enrico-Swagolo** [comment]
Correction - besides Inquisitors, he has built my Mosques too. Nice of him to spare me from having to use my own faith to get them up, what a nice guy.

**Comment by LoneGazebo** [comment]
I don't like to hard-code logic like that.

G

**Comment by Enrico-Swagolo** [comment]
I don't think it has to be hardcoded? Do Orders have a... defense value AI perceives? They're Walls in disguise so AI should realise that. Just like they focus military/defense buildings if under danger, so should they know Orders are a military/defense building. IMHO at least.
