### ISSUE TITLE
AI doesn't build units in besieged cities

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3224]
![image](https://cloud.githubusercontent.com/assets/1358966/25776576/059bbdf0-32c2-11e7-9a58-9a09258ecb40.png)

**Comment by TechpriestEnginseer** [comment]
Aren't they supposed to be using the process: Defense?

**Comment by LoneGazebo** [comment]
The AI won't change a building priority most of the time - otherwise the calls are too frequent for buildingproductionAI.

G

**Comment by ilteroi** [comment]
they only started the chancery during the siege. and next turn they started a workshop!

also we could update the build priority if the city is in an "enemyDominatedZone".

**Comment by LoneGazebo** [comment]
AI should update builds more frequently if sieged, and will do more unit building during that time.
