### ISSUE TITLE
spy action in the first turn?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3225]
![image](https://cloud.githubusercontent.com/assets/1358966/25781251/89568b78-3337-11e7-8cda-dd62e82a6755.png)

how is this possible? how can they even have a spy at this point?

**Comment by Bloodrocution** [comment]
lmao

They discovered enough ancient ruins free techs to get them to the Renaissance era in 51 turns?

**Comment by TechpriestEnginseer** [comment]
Patronage?

**Comment by LoneGazebo** [comment]
Advanced start? He may have bought up to patronage with his advanced start points (AI get more than a human).
