### ISSUE TITLE
Apostolic Tradition/Way of Pilgrim

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#3226]
_1. Mod version (i.e Date - 4/23):_5/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Civpedia says Apostolic has the WW policies reduce by followers, but you really gave it to Way of the Pilgrim in Founder.sql. Not sure which way its supposed to be.

UPDATE Beliefs
SET PolicyReductionWonderXFollowerCities = '8'
WHERE Type = 'BELIEF_TITHE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
It is supposed to be on Pilgrim. Fixed.
