### ISSUE TITLE
Gems monopoly doesn't work

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3227]
_1. Mod version (i.e Date - 4/23):_

Current

Basically get a Gems monopoly. They don't get +2 Science each once monopolised.

**Comment by Enrico-Swagolo** [comment]
I suspect it might not be only gems, I will check it out

**Comment by LoneGazebo** [comment]
I know why. It is savegame compatible, give me a minute. :)
