### ISSUE TITLE
Value of trade deals

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3228]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_

As thou hath demanded, here it cometh:

[single.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/993839/single.zip)

Earlier turn save has a deal with 1 to 1 resource +10 GPT deal, but just ask Willie and he'll gladly part with 32 GPT for Admiral Brazilwood with 1000 value left (can't take more from him). Later one has a 30 GPT 1 to 1 resource on-going. It's not the only time I see weird values, but it's the most prominent. I see AI overvalue most stuff.

I use regular mod with improved city view thing, but IIRC it should load anyway as it's a minor interface change only which makes specialists not spread, but put into one space - super convenient.

**Comment by LoneGazebo** [comment]
Ahh, he's overvaluing because he has the religious belief that gives him extra yields per luxury.

**Comment by LoneGazebo** [comment]
I'm going to deinflate luxury costs slightly, see if that corrects for his behavior a bit.

**Comment by LoneGazebo** [comment]
Mmm, I see the issue, I missed a min/max valuation limit. It wasn't allowing for proper valuation. That should fix it.
