### ISSUE TITLE
Explorer requires harbor in order to be bought

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#323]
Even in the land cities.

**Comment by LoneGazebo** [comment]
That's by design. Explorers are naval-focused.

**Comment by Radost** [comment]
Actually, explorers are amphibious.
Naval-focused are ships, which can't cross non-water tiles. Also they are far useful on land than in embarked state.

**Comment by LoneGazebo** [comment]
I understand that explorers are amphibious, but they're largely intended to explore overseas.

**Comment by Radost** [comment]
To explore oversea land tiles, to be exact.
By the same logic Knights are also naval-focused because they can embark and scout oversea locations.

**Comment by qqqbbb** [comment]
Costal city building as a requirement for a land unit is just wierd. Not every civ has coastal cities when astronomy is researched.
