### ISSUE TITLE
Colonialism doesn't work

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3230]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Basically what's in the title. Got Whales with +10% Science, but my Science didn't go up.  Cotton remains at 6 Gold, so it didn't get +3.

**Comment by LoneGazebo** [comment]
Hmm...I'll see. Worked for me but that was on test build.
