### ISSUE TITLE
Liberated CS issue

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3231]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I've liberated Monaco (it was taken by barbie incursion, then Shaka took it, then I liberated it). It's now apparently undergoing a weird barbarian incursion. There's no barbie attack icon, but barbies appear. Barbies don't attack Monaco and it's army that I've gifted, but Monaco also doesn't attack the barbies.

**Comment by Enrico-Swagolo** [comment]
Not exactly current, there's one hotfix I missed (the one with Ilteroi's stuff mixed in). Gotta update, though this issue wasn't mentioned as fixed.

**Comment by LoneGazebo** [comment]
Sounds like the BarbieCounter(TM) isn't being zeroed after death, even though the event is...

**Comment by Enrico-Swagolo** [comment]
For all I know it could be a bug due to me playing the game through various hotfixes. I've looked at Casimir's capital and it's blank. Warsaw's name suddenly disappeared, just like that, as if it was never there. Once I install the newest hotfix, even more spooky things might occur. 

Stiill, if that's not the case and it's an actual bug not due to saves, I do recall that once I liberated Monaco, my berserker was invisible and inside the city tile until I moved him away next turn. Maybe that is connected to the issue?

**Comment by LoneGazebo** [comment]
Saves shouldn't matter. Didnt touch memory elements.

**Comment by ilteroi** [comment]
i did though - always read the commit messages :)

**Comment by LoneGazebo** [comment]
I know you did - I didn't include that code, as it was innocuous. :) I'll add that to the next version.

**Comment by LoneGazebo** [comment]
I added a check. Should be fixed.
