### ISSUE TITLE
Outdated persia decisions

### ISSUE THREAD

**Issue by kawyua** [LoneGazebo/Community-Patch-DLL#3232]
_1. Mod version (i.e Date - 4/23):_
5/10

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi
Really advanced setup
_3. Error description:_ 
Both "Create the Savaran Calvary" and "Establish the Satropies" are not working to description

"Create the Savaran Calvary" is being allowed at trade although it requires "horseback riding". This is an issue now because what it does is allows persia to build cataphracts. Cataphracts though is 30 CS now and a whole era ahead, having the ability to get it in ancient era is bad bad business.

"Establish the Satropies" doesn't work.
_4. Steps to reproduce (optional):_
Noticed the text description being off and used really advanced setup to give me techs and stuff to see.

---------------------------
Supporting information:
I know this is for events... which I guess isn't your domain? Where should I refer to for this?
I haven't actually seen ai persia do this, but surely they can, right?

4. Screenshots (optional):
Finished trade, and clicked the decision, now cataphracts are available
<img width="685" alt="outdated persia" src="https://cloud.githubusercontent.com/assets/12496046/25983182/dcd48c2e-36b0-11e7-82a1-ed4bad9a6d9f.PNG">
<img width="685" alt="events" src="https://cloud.githubusercontent.com/assets/12496046/25983195/07523938-36b1-11e7-8fcd-6bcdb09a2e4d.PNG">

**Comment by pandasnail** [comment]
The version of E&D that Enginseer has updated to be compatible with VP has changed it to MandCavs. You really should be using that version, not the original.

https://forums.civfanatics.com/threads/cbp-events-and-decisions-compatibility.562935/

**Comment by kawyua** [comment]
ah im so behind sorry about that
