### ISSUE TITLE
Scout ancient ruin interaction (feature or bug?)

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3233]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

If a Scout turns into an archer via ruin and he's lvl 1+ meaning he has an ability, he will keep the ability but also get as many level ups as he has had levels while keeping his level/xp at exactly the same level at perviously.

Basically, get lvl4 Scout with 3x Survivalism, if he gets turned into Archer he keeps that and gets 3 level ups (you can take barrage III) on top of the previous stuff and he remains at level 4.

**Comment by LoneGazebo** [comment]
sounds like a bug b/c he changes classes. I'll look.
