### ISSUE TITLE
Hussar description

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3234]
_1. Mod version (i.e Date - 4/23):_latest hotfix

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
 Civipedia on Hussar unit says "It is slightly faster than Cavalry", which in fast is not. They both have the same speed of 4, but the Hussar is slightly stronger in both strength and ranged strength.

**Comment by LoneGazebo** [comment]
Hussar should be 5. Fixed.

**Comment by pandasnail** [comment]
The Hussar has five move already, but the extra move is from the Lightning Warfare promotion, not added base move.
