### ISSUE TITLE
Empiricism Incorrectly Functioning

### ISSUE THREAD

**Issue by OrkyBoss** [LoneGazebo/Community-Patch-DLL#3236]
_1. Mod version (i.e Date - 4/23):_
5/10

_2. Mod list (if using Vox Populi only, leave blank):_
Hyperdimension Neptunia - Core Files (v. 7)
Hyperdimension Neptunia - Lastation (v. 3)
Hyperdimension Neptunia - Lastation mk2 (v. 6)
Hyperdimension Neptunia - Leanbox (v. 9)
Hyperdimension Neptunia - Lowee (v. 7)
Hyperdimension Neptunia - Planeptune mk2 (v. 8)
Hyperdimension Neptunia - Soundtrack (v. 1)
Infoaddict (v. 22)
Madoka Magica Civilization Pack -- Rebellion (v. 12)
Madoka Magica Soundtrack (No Stupid Subtitles Edition) (v. 6)
Metal Gear ZEKE Gaint Death Robot (v. 1)

_3. Error description:_ 
Empiricism policy is not functioning. Visually changes research cost but actual cost remains the same resulting in cases of seeming "over" the required cost when researching new technologies for several turns. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/999100/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 
[Fix This Plox.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/999099/Fix.This.Plox.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): 

4. Screenshots (optional):
http://imgur.com/a/ktE0C

**Comment by bigcat88** [comment]
Yesterday, had the same issue, but in my case I just make a reload, and then all was fine.(I lost just 1 or 2 turns after I noticed that)
I don't post it on GitHub cause I think that it was only in my head (

**Comment by bigcat88** [comment]
U have this trouble on that tech when u get Empiricism? Cause in my current game, I again got the same when choose empiricism, but on next tech after that all becomes normal(or my science too big and I don't see that %). Maybe this will help to find a trouble.

**Comment by LoneGazebo** [comment]
I think it is just a UI issue - I'll make a change and see if it works.
