### ISSUE TITLE
strange wars

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3237]
here are some suspicious logs ...

situation is like this. only three players left - portugal and mongolia are the big ones, babylon is relatively small. game's running on autoplay, when i check on it i see:

- babylon has already lost a few cities in a previous war (to both of the others)
- babylon and portugal have a defensive pact
- babylon is at war with mongolia
- portugal is not at war with mongolia (meaning a bug or babylon declared, don't know what's worse)
- shortly afterwards, portugal also declares war on babylon, defensive pact or not
- in a few turns the remaining babylonian cities are conquered
- now portugal and mongolia have a defensive pact, although they are the only players left!

[Logs-Backup.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/999167/Logs-Backup.zip)

**Comment by LoneGazebo** [comment]
I'll fix the DP issue on the last point - the other element sounds like Portugal was being erratic and opportunist (which she is known for as an AI).

**Comment by ilteroi** [comment]
well it didn't last long anyway ... but for me the bigger question is actually how and why the babylonia/mongolia war got started. can you see that?

**Comment by LoneGazebo** [comment]
Mongolia declared war on Babylon before the DP was made - 

>324, Mongolia, , ***** WAR DECLARATION! *****, Babylon

> 339, Portugal, Babylon, , , ***** Defensive Pact Trade *****

**Comment by LoneGazebo** [comment]
Mongolia did it as I hoped too, as:
>299, Mongolia, Babylon, , , ***** Third Party War Trade versus ID TXT_KEY_CIV_ROME_DESC *****

So Mongolia bribed Babylon to wipe out Rome, meanwhile Mongolia was shifting from 'war neutral' to 'friendly' to 'war friendly,' which is - in essence - the deceptive position.

G

**Comment by ilteroi** [comment]
nice!

**Comment by LoneGazebo** [comment]
Yeah. The fact that Mongolia briefly went 'friendly' is probably because his empire was momentarily unhappy.
