### ISSUE TITLE
some old strange little bugs

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3239]
_1. Mod version (i.e Date - 4/23):_
current and previous

I don't know if that bugs are in interface or in core. So I just describe them, if u need I can post saves from my game that I will start now(I noticed that little bugs in every game)

First: tourism. If u have for example 3 cities, and conquer one city and annex it u will get penalty for 3 cities(after annexing it)(2% on my huge maps)
But if u then trade those city, and as I remember u if u raze it(not immediately after conquering-HERE I am not sure, but can test it) - u will still see - 6% penalty in city view for tourism. Looks like tourism penalty just not recalculating after trade deal with city.
And also tourism help says: "Every owned city" - that's wrong. Only every owned non puppet city as I remember. Puppet cities doesn't count. But in last version I don't check this.
Second: in last game I conquer a city, annex it, got an increased science and culture cost. After that I lost it. And see that science cost remains the same, like after annexing. I just write on paper cost for techs that I don't know, but they were next what I want to research in near future.
Before annexing it was: 17,053 18,603 After annexing: 17,374 18,954(number are just an example)
I lost city very quickly, one or 2 turns after annex(yeah, that was a such plan in that game): cost for tech remain the same: 17,374 18,954 It was not recalculating after my lost.
Current culture policy number was not recalculating too(but here I am not sure, cause I cant know what culture number for future policies, so I don't write it)

As I say, now I start a new game, and if u need I can post saves/screens from it). I sure that there will be the same situations :)

**Comment by ilteroi** [comment]
did you check the values again in the following turn? maybe it's just the interface wasn't updated immediately.

**Comment by bigcat88** [comment]
yeas, I check, even check after current tech research

**Comment by TechpriestEnginseer** [comment]
If you lose a city, the policy and science cost does not get reduced. This is an intentional feature of vanilla.

**Comment by LoneGazebo** [comment]
Tourism uses the same functionality as culture/science, so @TechpriestEnginseer's first point is correct.
