### ISSUE TITLE
GodKing typo/issue

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#3240]
5/10 with latest hotfix, full VP only: ''God-King'' pantheon description says the bonus yelds from followers are applied to the Capital, instead they apply to the Holy City. Typo? It'd be cool if they applied to your own capital should you conquer a GK Holy City, afterall the God palace is elsewhere :P
![persia108c](https://cloud.githubusercontent.com/assets/24731508/26057153/96344e24-3978-11e7-8f11-61dab2b3844c.png)

**Comment by LoneGazebo** [comment]
They apply to capital until you get a holy city, like all pantheons that are capital centric.
