### ISSUE TITLE
Consulates Policy error

### ISSUE THREAD

**Issue by Txurce** [LoneGazebo/Community-Patch-DLL#3241]
_1. Mod version (i.e Date - 4/23):_

5/10
_2. Mod list (if using Vox Populi only, leave blank):_
Quick turns

_3. Error description:_ 

Poland has 10 UN votes attributed to the Consulates Policy, but there were only 16 CS, so he should only have 2 max, right?  Regardless, how does he have 10?
_4. Steps to reproduce (optional):_

None needed. Just check the game.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Enrico Dandolo_0320 AD-1900.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1002274/Enrico.Dandolo_0320.AD-1900.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I think Consulates votes are lumped in with votes from the Forbidden Palace et. al.

**Comment by Txurce** [comment]
Okay, thanks. I won't worry about it.
