### ISSUE TITLE
Celtic pantheons not available

### ISSUE THREAD

**Issue by schmere** [LoneGazebo/Community-Patch-DLL#3242]
_1. Mod version (i.e Date - 4/23):_
v. 88 (May 5, 2017)

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch (v. 88)
Community Balance Patch (v.13)
City State Diplomacy mod for CBP (v. 27)
C4DF - CBP (v. 11)
Barbarians - Unlimited Experience (v. 2)
Community Patch Mod Compatibility (v. 14)
More Luxuries (v. 155)
Promotions - Ancient Ruins Choice (v. 2)
Units - Starting Scount (v. 1)

_3. Error description:_ 
When playing as the Celts, when I get to choose a Pantheon, only the normal pantheons show up - none of the Celtic options are available

_4. Steps to reproduce (optional):_
I played the game through twice to "Found Pantheon" as Celts - each time I had all the regular options, no Celtic options
[Logs (2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1014800/Logs.2.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![celtic pantheon error](https://cloud.githubusercontent.com/assets/28691507/26084784/b7e51f06-3993-11e7-9ae4-441a10a47baf.png)

**Comment by schmere** [comment]
Yes - other mods appear to be working fine - it's just the religion that 
doesn't appear to be working.

Although, I should note that I used to play (v.77) on King and win most 
games - now, with v. 88, I can't win at Prince.  The AI seems to be able 
to research and grow their cities way faster than me (for example, 
Mongolia has 15 techs when I have 6, and 39 people in 3 cities while I 
have 13 in 4...)

Best regards,

Rick Schultz, BA, CPA

New Leaf Consulting

778-991-8313  |  schultz.rick@gmail.com






------ Original Message ------

**Comment by LoneGazebo** [comment]
I edited out your personal info. :)

You don't seem to have logging enabled - enable it and load a game as the celts, then post your logs.

**Comment by LoneGazebo** [comment]
Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

**Comment by schmere** [comment]
Thanks - I'll get that in tonight.







------ Original Message ------

**Comment by schmere** [comment]
I"ve attached my Log folder and the most-recent save game which it 
references.





------ Original Message ------

**Comment by LoneGazebo** [comment]
Where'd you attach it?

**Comment by schmere** [comment]
I attached it to the email - I couldn't see any way to attach it to the 
original submission.

Best regards,

Rick Schultz, BA, CPA

New Leaf Consulting

778-991-8313  |  schultz.rick@gmail.com






------ Original Message ------

**Comment by schmere** [comment]
Here it is again.

Best regards,

Rick Schultz, BA, CPA

New Leaf Consulting

778-991-8313  |  schultz.rick@gmail.com






------ Original Message ------

**Comment by LoneGazebo** [comment]
You've got personal information here again. I don't see the attachment. You can copy and paste the zipped folder into the text box here on github.

**Comment by schmere** [comment]
Updated the log file on Github.

Best regards,

Rick Schultz, BA, CPA

New Leaf Consulting

778-991-8313  |  schultz.rick@gmail.com






------ Original Message ------

**Comment by LoneGazebo** [comment]
You've got some odd database conflicts: 

```
> [514477.765] table Buildings has no column named CorporationMaxFranchises
> [514477.765] 
> [514477.765] In XMLSerializer while updating table Buildings from file Modular Elements/Corporations/Corporations.xml.
> [514477.953] no such column: HalvedFollowers
> [514478.468] no such table: Trait_TradeRouteStartYield
> [514478.515] no such column: InspirationalLeader
> [514478.937] no such table: Building_CorporationResourceQuantity
> [514480.343] columns Language, Tag are not unique
> [514480.343] While executing - 'insert into Language_en_US('Tag', 'Text') values (?, ?);'
> [514480.343] In XMLSerializer while inserting row into table insert into Language_en_US('Tag', 'Text') with  values (TXT_KEY_ALREADY_INVESTED, [NEWLINE]You have already invested [ICON_GOLD] Gold in this building. This building's [ICON_PRODUCTION] Production cost is reduced by {1_Num}%., ).
> [514480.343] In XMLSerializer while updating table Language_en_US from file Balance Changes/Text/en_US/UIText.xml.
> [514480.343] columns Language, Tag are not unique
> [514485.781] Validating Foreign Key Constraints...
```

I'd recommend a reinstall of the VP using the auto-installer. Make sure there are no modpacks in your DLC folder as well.

**Comment by LoneGazebo** [comment]
Delete all mods in your MODS folder before reinstalling (you can move out the few you are using, then move them back in).

**Comment by schmere** [comment]
I'll try that - thanks!

Best regards,

Rick Schultz, BA, CPA

New Leaf Consulting

778-991-8313  |  schultz.rick@gmail.com






------ Original Message ------

**Comment by schmere** [comment]
Hi!  Looks like it's working now.  Also, the AI no longer has insane 
bonuses for growth & tech - back to a balanced game.  Thanks!






------ Original Message ------

**Comment by LoneGazebo** [comment]
Awesome! Glad I could help. :)
