### ISSUE TITLE
settlers spawns as partizans and strange airports things

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3243]
_1. Mod version (i.e Date - 4/23):_
5-10

_2. Mod list (if using Vox Populi only, leave blank):_
world congress reinform

_3. Error description:_ 
Sometimes settlers spawns as partizans. But I am also fighting india - india swapn normal troops(they spawn last mech infantry). Only see settlers from Ottomans.

![20170516135635_1](https://cloud.githubusercontent.com/assets/13381981/26102847/9169d590-3a3f-11e7-8cdc-940f638ed256.jpg)

**Comment by bigcat88** [comment]
Also another strange thing. I can airport my units to my enemies cities(we are all in last era, with all techs researched)
Looks like if I don't have vision on that city I can port my unit there. Here is a screen:
![20170516140712_1](https://cloud.githubusercontent.com/assets/13381981/26103201/0b4cd96a-3a41-11e7-8890-e0e2b80d2956.jpg)

**Comment by LoneGazebo** [comment]
Re: second image, the red ring around the city name means you are at war, not that you can airdrop there.

G

**Comment by bigcat88** [comment]
No - I check it, I can airport

**Comment by bigcat88** [comment]
I will check right now in a new game with clear reinstall of vox, but as u can see I have a ported unit there on second image(artillery). Also after that I ports giant robots to check )

**Comment by bigcat88** [comment]
So right now I reinstall vox populi from 43 civ version to standart and on first turn just open map,meet Germany, and add to my capital and to Germany an airport. Declare war. And airlift my units after declaring war. 
I think problem is not in mods, cause my mod list is very small:
Ingame Editor (v 39)
PerfectWorld3 - Updated (v 5) - it's map I played.
Really Advanced Setup (v 15)
RemoveBanLuxury (v 1)
Terrain - Poor Tiles Tweak (v 2)
Show XP in Military Overview (v 2)
Wonder Race (v 6)
World Congress Reformation (v 5)
![20170517101516_1](https://cloud.githubusercontent.com/assets/13381981/26142568/bf8fd10e-3ae9-11e7-97cf-a49d4d711530.jpg)
Here is a savegame(but faster will be to start a new game, I describe steps):
[AIRPORT.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1006837/AIRPORT.zip)

**Comment by LoneGazebo** [comment]
Airport issue looked at, cannot reproduce settler issue.

**Comment by bigcat88** [comment]
So bug with airports will be fixed?
