### ISSUE TITLE
(6c) 43 Civs CP causing city states to not be in the game

### ISSUE THREAD

**Issue by lorduc** [LoneGazebo/Community-Patch-DLL#3244]
_1. Mod version (i.e Date - 4/23):_

may second
_2. Mod list (if using Vox Populi only, leave blank):_

(6c) 43 Civs CP
_3. Error description:_ 

So i've been using the "Yet (not) Another Earth Maps Pack (v 24)" mod so far and their maps, but today i decided to use some vanilla maps (archipelago in particular).
with (6c) 43 Civs CP enabled, i can only have a maximum of 24 city states on that map. when I start the game, all the civs that i've chosen (I only put 8 in the game) are in the game, however no matter how many city states I choose to be in the game, none will appear. (there are no city state settlers when the game starts, and I cant see any city states using the IngameEditor.)
after disabling (6c) 43 Civs CP, I can choose up to 41 city states (same map, i.e archipelago), and all 41 city states appear in game!
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I'm guessing there's some kind of mod conflict.

**Comment by LoneGazebo** [comment]
Cannot reproduce.
