### ISSUE TITLE
Regimental Tradition applies to UIs?

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3245]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Well, I didn't see that myself, but someone in a civfanatics thread mentioned that. It could be wrong for all I know. Description mentions no such a thing.

**Comment by LoneGazebo** [comment]
Eh? Maybe he's confusing it with the order policy that buffs UIs?

**Comment by Enrico-Swagolo** [comment]
Dunno, I remember reading Terrace Farm got affected in a thread of some sort.
