### ISSUE TITLE
Redundant archeologists

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3246]
_1. Mod version (i.e Date - 4/23):_latest

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
 It seems AI fails to disband leftover archeologists late in game when all possible archeological sites have long been dug out. 

 I can't unconditionally prove it in my current game because I didn't go Aesthetics policy tree and can't see hidden sites, but in year 2029 with 11 players I find it extremely unlikely that there is any job for an archeologist left.

_4. Steps to reproduce (optional):_

![20170519152424_1](https://cloud.githubusercontent.com/assets/16341598/26247841/66e9f6cc-3ca8-11e7-919a-562be9f1c5d4.jpg)

**Comment by LoneGazebo** [comment]
Normal - AI keeps one or two around just in case they spot one.
