### ISSUE TITLE
Truffles found on a not-forested hill.

### ISSUE THREAD

**Issue by aldebaran1997** [LoneGazebo/Community-Patch-DLL#3247]
_1. Mod version (i.e Date - 4/23):_
Latest (5-11-1) 43 civs EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Civilopedia says that Truffles must be found on forest, jungle or marsh. But I found it on a not-forested hill. It wasn't deforestated because I found it on turn 8.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by aldebaran1997** [comment]
*I found another one on a not-forested plains.

**Comment by LoneGazebo** [comment]
What map? Some maps will place it outside normal bounds.

**Comment by aldebaran1997** [comment]
Oh, sorry. I forgot about this post. I always play Communitas map. Huge, all options are random, 2 random ocean.
