### ISSUE TITLE
Assigning Specialists During a Revolution

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3250]
Seeing as they only produce non-food yields. City governors should be taught not to assign specialists because specialists adds up to unhappiness even during a revolution!

**Comment by LoneGazebo** [comment]
Hmm, shouldn't be...

**Comment by TechpriestEnginseer** [comment]
Some of them put in laborers as correct but some of them still forget to take out their specialists.
