### ISSUE TITLE
Player:HasMonopoly Request

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3251]
I know the Lua in there does a different combo, but it has a much heavier usage whereas I just want a monopoly of a specific resource for this to roll rather than rolling for all resources for one monopoly.

**Comment by LoneGazebo** [comment]
Use this: GetResourceMonopolyPlayer(ResourceTypes eResource)

**Comment by TechpriestEnginseer** [comment]
That works as well.
