### ISSUE TITLE
it's the little things

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3254]
![image](https://cloud.githubusercontent.com/assets/1358966/26389543/b3e594b2-405a-11e7-9f66-dc5173a06e2d.png)

1. babylon needs to kill those barbarians and get an escort for their settler, but no, they build a work boat. they did buy a warrior the following turn and used it as an escort, but did nothing against the barbarians. and the escort died eventually.

2. they put their first two workboats onto the whales. maybe it would have been better to hook up the coral with the second boat.

**Comment by ilteroi** [comment]
turns out the workboat building is not reproducable. after reload they build an archer ... good, but also a bit worrying, because i like reproducability

**Comment by LoneGazebo** [comment]
huh, sounds like the RNG seed may have changed. Uh oh.
