### ISSUE TITLE
airports

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3256]
_1. Mod version (i.e Date - 4/23):_
last with hotfix

_2. Mod list (if using Vox Populi only, leave blank):_
World Congress Reinform

_3. Error description:_ 
Maybe it so intended and it is not a bug.
Airlifting says: "to a friendly city with an airport". But I cant airlift my unit to Celts AI capital. Their capital has airport, and I has vision on it(my xcom squad stays near their capital). We have Declaration of Friendship.
And yes, I can port to allied CS. But to friendly CS cant(I don't know is it right or not)

**Comment by LoneGazebo** [comment]
Friendly = owned or allied CS. I can clarify tooltip but yes it is working correctly.

G
