### ISSUE TITLE
Detect Instances of Event Choices through Lua.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3257]
As event choices can be repeated and thus stacked, are there ways to detect these stacks through Lua so I don't have the same Lua firing up the same event choices when the last one haven't expired yet?

**Comment by LoneGazebo** [comment]
Not _exactly_ sure what you're asking.

G

**Comment by TechpriestEnginseer** [comment]
Use Lua to apply a specific event choice that can expire, but has a specific condition of unlimited amount of turns.

However this specific event choice can be stacked. Although, I don't want it to stack too much like say +1 Culture on Villages. I want to be able to stack to +3 Culture using dummy events and such but there is no way of detecting the amount of the same event choice active in Lua. So this dummy event choice could stack up to more than +3 Culture on Village.

**Comment by LoneGazebo** [comment]
Ah, I see. Unfortunately that kind of tracking would require a hefty amount of memory (integers * num possible active events = lots of memory needed). You could use the IsEventChoiceActive logic to allow for a single duplication, or you could use GetEventCityYield with a yield like YIELD_JFD_LOYALTY (as it is not gained in such a way IIRC) and use this as a tracker value. Does that make sense?

Assign each dummy event a cityyieldvalue of x YIELD_JFD_LOYALTY, and at a certain value make it no longer possible.

G

**Comment by TechpriestEnginseer** [comment]
That seems fine.
