### ISSUE TITLE
CTD on Polynesia's turn

### ISSUE THREAD

**Issue by ashendashin** [LoneGazebo/Community-Patch-DLL#3258]
_1. Mod version (i.e Date - 4/23):_
5/22

_2. Mod list (if using Vox Populi only, leave blank):_
Community Events
CBO Enlightenment Era
Really Advanced Setup
Unique City-States

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1027905/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Bismarck_0189 AD-0235.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1027902/Bismarck_0189.AD-0235.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1027897/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by ashendashin** [comment]
Any idea what's causing it? I really want to continue this game without deleting Polynesia. Given up on a ton of Germany games on Deity and this is one of the most promising yet.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1030733/CvGameCore_Expansion2.zip)

Try this DLL. Drop in your CP.

G

**Comment by ashendashin** [comment]
It worked! Thanks!
Will the diplo fix require a new game when you finish the new version? Sounds serious and I might try for the same map to get my start again. Easy monopoly on both coffee and copper... Been waiting for this since you changed the luxury monopolies.

**Comment by LoneGazebo** [comment]
I can't guarantee compatibility, but I think it might work.
