### ISSUE TITLE
CTD on YNAEMP Giant Earth Map

### ISSUE THREAD

**Issue by CharlesDR** [LoneGazebo/Community-Patch-DLL#3259]
_1. Mod version (i.e Date - 4/23):_
5-22.1

_2. Mod list (if using Vox Populi only, leave blank):_
VP 43-Civ, YNAEMP latest version

_3. Error description:_ 
Crashes to desktop while processing AI turns

_4. Steps to reproduce (optional):_
Start game. The settings I use are:
Giant Earth map, 30 civs, random civ placement
Sometimes, it crashes during the first AI turn. Crash is more reproducible if you 'restart game' at least once before pressing End Turn.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1030580/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1030581/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I know why - I'll fix for next version.

G
