### ISSUE TITLE
AI has problems guarding civilians

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3261]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
AI seems to have taken a step back in this regard. I constantly see them move workers weirdly, often through my lands, apparently trying to reach the city they've foolishly settled behind my territory.

**Comment by ilteroi** [comment]
that's not a lot of information - and there haven't really been any changes there lately - but i think there's an easy fix
