### ISSUE TITLE
EventChoiceAudio being overridden by the default audio.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3262]
For CityEventChoices and EventChoices, no custom audio can be used because the default audio seems to override it.

**Comment by LoneGazebo** [comment]
That's a UI/LUA issue. @jfdaly any ideas?

**Comment by JFDaly** [comment]
Hm, my Events Compendium uses Audio extensively and they have always worked. Has anything changed in the UI files? If you're invoking the event through Firetuner, the Audio won't play unless you're superquick to switch to the Civ application.

The default doesn't play unless it fills out EventChoiceAudio tag in the table.

**Comment by TechpriestEnginseer** [comment]
Are you sure? The default plays despite the EventchoiceAudio is being filled.

**Comment by TechpriestEnginseer** [comment]
It's because your Event Compendium uses Event Audio extensively and not the most important one the CityEvent Audio. Fixed, if you want some work done, got to do it yourself.

**Comment by JFDaly** [comment]
Rood tbh - equating one mistake to having not done something well.

**Comment by TechpriestEnginseer** [comment]
Nah I'm just blaming myself for not having to solve the easiest mistake and waiting for you to fix it.

**Comment by LoneGazebo** [comment]
Thanks for solving this, guys. Now kiss and make up. :)

G
