### ISSUE TITLE
Units given from free events seems to make the player stuck.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3263]
Few people have reported the bug that when they get a free unit from events, the game takes a while to respond, so you can't do anything UI-related(clicking on production, science, culture overview whichever) but they usually resolve it by just moving a garrison back and forth which immediately resolves the problem.

**Comment by bigcat88** [comment]
Yeah, I see it in every my game. I hate authority finisher policy for that.
