### ISSUE TITLE
vassalage deals

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3264]
if vassalage is added to a deal, declarations of war on anyone the vassal is at war with should be added to the master's side. except the master itself of course.

open questions:
- how to link the items so that they cannot be removed separately?
- only for voluntary vassalage?

**Comment by LoneGazebo** [comment]
An easier solution was noted in the forums, that voluntary vassalage cannot happen during war. Capitulation on the other hand can, and should result in a 'reset' of diplomacy with the Civ as it does now.

**Comment by ricanuck** [comment]
Me thinks the best solution comes from Civ 4. A voluntary request for vassalage for the sake of protection (from a civ losing a war), gives the requested power a choice: reject the request for vassalage, or accept it and immediately join the war. That also makes all the sense in the world.

**Comment by ilteroi** [comment]
i'm fine with all of those solutions, G's proposal is probably the simplest to implement.

**Comment by LoneGazebo** [comment]
@rickanuck,

Only problem is AI evaluation. Can be tricky to get right. Easiest is first option.
