### ISSUE TITLE
AI never wants to settle inside its borders.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3267]
Even if there is a valid distance between each city, the AI will refuse to settle inside its borders. The player can do this yet the AI doesn't want to do it even if there is luxury that is unworkable without the city being settled. This doesn't become a problem but I figure it might for Attila who has really huge potential for acquisition of tiles.

**Comment by ilteroi** [comment]
more details please. screenshot?

**Comment by TechpriestEnginseer** [comment]
Never mind, I did some further testing by having Attila forced to raze some cities near his borders and spawned some pioneers and he settled them in his borders. It seems the AIs don't consider urbanization logic where few tiles are being less worked in the mid game and should take more consideration into settling cities where too many good tiles may not be worked.
