### ISSUE TITLE
"there was a crash on Turn 70 plsfix thx" :D

### ISSUE THREAD

**Issue by Wall93x** [LoneGazebo/Community-Patch-DLL#3269]
**_1. Mod version (i.e Date - 4/23):_**
VoxPop v.5-22-1

**_2. Mod list (if using Vox Populi only, leave blank):_**
Barbarians - Unlimited Exp. (v. 2)
Faster Aircraft Animations (v. 3)
Global Warming (for vanilla, GnK, BNW) (v. 7)
Global Warming Congress (for vanilla, GnK, BNW)(v. 2)
Historical Religions (BNW or GnK) (v. 55)
Increase City Radius  3 to 5 (v. 1)
InfoAddict (v. 22)
JFD's The Russian Federation (v. 2)
Promotions - Ancient Ruins Choice (v. 2)
Promotions - Expansion Pack (v. 9)
Quick Turns (v. 10)
R.E.D. Modpack (v. 27)
Resource - Granary Includes Bison (v. 3)
Ressource - Mint Include Copper (v. 2)
Terrain - Brazilwood Camp Extension (v. 3)
Terrain - Chateau Extension (v. 3)
Terrain - Feitoria Extension (v. 3)
Terrain - Kasbah Extension (v. 3)
Terrain - Moai Extension (v. 3)
Terrain - Motte-and-bailey Fort (v. 5)
Terrain - Polder Extension (v. 3)
Terrain - Poor Tiles Tweak (v. 2)
Terrain - Terrace Farm Extension (v. 3)
Trading Posts Grow into Town (v. 6)
Units - Airship and Land Ironclad (v. 3)
Units - Scout to Explorer (v. 10)
Units - Starting Scout (v. 1)
Yet (not) Another Earth Maps Pack (v. 24)

**_3. Error description:_** 
As topic/title said. There was a crash on turn 70 (200BC). Crashed after player 4 turns. (so it was a player 5 turn)

**_4. Steps to reproduce (optional):_**
Well... just press end turn and it happens (no special action , move or buildings)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.
> We don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

Hmmm i cannot put a .zip file on Github (dont know why). I try with .zip .rar and .7z....
so i put a link to [mega.nz](https://mega.nz/#!tNN3EJLa!EyGuTUtEftEaTtQzcNqjLkQOzbJZwcd681B1GwL2u5c)

1. Log files: ^link^ contains folder with logs.
2. Save game: ^link^ contains folder with save. (turn 69)
3. CvMiniDump.dmp file:^link^ contains folder with this file.
4. Screenshots (optional): no need

**Comment by LoneGazebo** [comment]
I can't debug that many extra mods, sorry.

**Comment by Wall93x** [comment]
Ok i understand. I start new game and try to remove/disable a few mods.
