### ISSUE TITLE
EventBuilding Bug

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3270]
Carthage has an active event that grants her free arsenals within all cities. If she captures a city, a free arsenal is made. If she settles a new city, a free arsenal is made. However...

Indonesia also has an active event that grants him free arsenals within his cities as well. If Carthage captures any Indonesian city, no free arsenal is made.

**Comment by LoneGazebo** [comment]
Events are unique to each city and player, so that shouldn't happen. Is strange, though. I'll look.

**Comment by TechpriestEnginseer** [comment]
I think it's more of a ordering bug where Carthage applies the event building before the conquest goes(which is okay), but since arsenals are always destroyed. The arsenals remain destroyed and EventBuilding can't spawn them since they only do a one-time test. I might have to test with different buildings if that's the case.

**Comment by LoneGazebo** [comment]
What lua hook are you using for the check? CityCaptureComplete happens at the very end of the acquire city process, might use that.

**Comment by TechpriestEnginseer** [comment]
I'm actually just inspecting the city for the check.

Carthage captures a Hunnic City with no active arsenal event, but has no arsenal. Carthage gets a free arsenal in that city.
Carthage captures a Hunnic City with no active arsenal event, but has an arsenal. Carthage still keeps the arsenal in that city.
However...
Carthage captures an Indonesian City with active arsenal event. Carthage doesn't get the free arsenal at all.

**Comment by LoneGazebo** [comment]
That's really strange.

**Comment by LoneGazebo** [comment]
Ahhh, I think I see. I'll upload a tester CP shortly.

**Comment by LoneGazebo** [comment]
[(1) Community Patch (v 88).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1056694/1.Community.Patch.v.88.zip)

Test this. Not savegame compatible.

**Comment by TechpriestEnginseer** [comment]
Oh hey you fixed it. I'm assuming this is in the beta version?

**Comment by LoneGazebo** [comment]
Yeah.
