### ISSUE TITLE
Crash to dekstop, possible Mughal fort audio issue

### ISSUE THREAD

**Issue by FredyZoR** [LoneGazebo/Community-Patch-DLL#3272]
_1. Mod version: May 26th

_2. Mod list: Vox Populi May 26th no EUI (1-6b), JFD RtP, JFD CiD, JFD Explo, JFD CulDiv

_3. Error description: Crashes to desktop at turn cycling, crashes at Spains turn i think.

[164733.796] Invalid Reference on Building_ConstructionAudio.BuildingType - "BUILDING_MUGHAL_FORT" does not exist in Buildings
[164733.796] Failed Validation.

After 4 attempts this is always the same line in the Database.log after the crash.

_4. Steps to reproduce (optional): 100% reproducible by just cycling the turn in my current game.

---------------------------
Supporting information:

Logs, Savegame and MiniDump in a zip below:
[GithubMughalCrash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1058455/GithubMughalCrash.zip)

**Comment by LoneGazebo** [comment]
database log forms when you load mods, not after a crash - most likely an issue with the other mods in the package.

G

**Comment by LoneGazebo** [comment]
Especially since that table is not a vanilla table - it was added by @JFDaly.

**Comment by FredyZoR** [comment]
Fair enough, i don't think JFD is even updating these mods anymore. Too bad the game is unplayable for me without them. :(

**Comment by LoneGazebo** [comment]
@JFDaly still checks github, give him time.

**Comment by FredyZoR** [comment]
Nice! That is great, sorry if it came off as a bitrude. Just a bit annoyed that my 7 hour tall Korea endeavor ended with a crash. Thanks for all your modding work making this age-old game still the best TBS out there.

**Comment by JFDaly** [comment]
I am updating them, I've just had my time especially stretched lately. Looks like the Mughal Fort has been removed by one of your mods?

**Comment by LoneGazebo** [comment]
CBO removes it (but has since the very beginning).

**Comment by JFDaly** [comment]
Okay, I'll had a failsafe for that.

**Comment by LoneGazebo** [comment]
Yeah - even then, not sure how that would cause a crash (As the building can't be built).

**Comment by FredyZoR** [comment]
Would just like to say have been able to play on for at least 10 turns from that save i uploaded. I have no idea why it didn't crash this time.
