### ISSUE TITLE
Frequent CTDs

### ISSUE THREAD

**Issue by Grabbl** [LoneGazebo/Community-Patch-DLL#3273]
_1. Mod version (i.e Date - 4/23):_
5/26

_2. Mod list (if using Vox Populi only, leave blank):_
Full Vox Populi, EUI Version

_3. Error description:_ 
I have frequent CTDs since about 50 turns, now almost every turn. They are not reproducible and occur usually when I try to give an input (for example move a unit, access info screens ore similar). In the attached folder, there are the logs of the most recent crash and a save. 

I could find no dependancy of EUI/ Non-EUI or graphic settings, also the task manager doesn't show too much stress on the system. But if you think it's a performance-related crash, delete this issue.

_4. Steps to reproduce (optional):_

[CTD_06_07_2017.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1058801/CTD_06_07_2017.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Any other mods?

**Comment by Grabbl** [comment]
No. (JFD's Exploration and Flag Promotions installed, but not activated)
