### ISSUE TITLE
Scout at turn 3.

### ISSUE THREAD

**Issue by aldebaran1997** [LoneGazebo/Community-Patch-DLL#3274]
_1. Mod version (i.e Date - 4/23):_
Latest (6/9) VP EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I found a Polish scout at turn 3. I played standard speed, Deity difficulty, huge Communitas map as Venice. Is it intended?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Goody hut upgrade.

**Comment by aldebaran1997** [comment]
I didn't even think about it.
