### ISSUE TITLE
Barbies are cocky out of camps

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3276]
_1. Mod version (i.e Date - 4/23):_
current beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Put a low HP unit next to a barbie camp
Barbie wants to impress Ken and kills the warrior. Doesn't return to camp. If you put another unit next to the Barbie and it's relatively healthy, it'll also attack. Attack the barbie, kill it and conquer the camp without having to break it with the fortification+heal bonus.

**Comment by Enrico-Swagolo** [comment]
Correction, reloaded the save and this time the Barbie decided to come back to the camp.

**Comment by Iamblichos** [comment]
I think we should make Camps like the "no follow up from Citadel/Fort option" upon a successful kill by a barb.

**Comment by ilteroi** [comment]
done
