### ISSUE TITLE
Weird spy stealing techs.

### ISSUE THREAD

**Issue by aldebaran1997** [LoneGazebo/Community-Patch-DLL#3277]
_1. Mod version (i.e Date - 4/23):_
Latest (6/9) VP EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I (Venice) had 25 techs and Japan had 32 techs and Ethiopia had 31 techs. I sent recruited spies to both capital and they had very high potential. Then what I saw was my spy stole tech per 2 turns from Ethiopia and need 15,133 turns to steal tech from Japan. I already stole 2 techs in 4 turns and also remained 2 turns to gathering intelligence from Ethiopia.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Potential does not reflect negative espionage modifiers, merely the raw potential.

**Comment by aldebaran1997** [comment]
But is it intended that gathering intelligence from someone who has 7 more techs than me needs over 15,000 turns at early Renaissance stage? If Japan has constabulary on their Capital, could it be possible that super low potential? Again, it was standard speed. Thank you for replying.

**Comment by LoneGazebo** [comment]
I can't reproduce, sorry.
