### ISSUE TITLE
CTD: Newly-Recieved Embarktion and Auto Explore as First Command

### ISSUE THREAD

**Issue by cammcken** [LoneGazebo/Community-Patch-DLL#3278]
_1. Mod version (i.e Date - 4/23):_
6/9/17 (also observed earlier)

_2. Mod list (if using Vox Populi only, leave blank):_
Using civfanatics user ElliotS's modpack. (DLC mod). Comes with flag promotions, improved city view, unique city states and unit path viewer. (However, I also observed this bug on a CBP-only install)

_3. Error description:_ 
Short answer: Pressed 'E' for auto-explore, and the game crashed to desktop.

Strong suspicions: Game crashes when 1) Without the embarkation promotion, a unit has exhausted all possible areas to explore 2) The unit is put to sleep (or similar) in owned territory 3) Fishing tech is researched, supposedly granting embaraktion to any units in friendly territory 4) The unit is commanded to explore as its first command, before any other movement.

P.S.
I know this is a silly issue to send a report in about, because it's so specific that it's easily avoided; however, this is the second time I made the mistake after stumbling on it during a different gameplay several versions ago. I forgot that I couldn't do that. Other people may forget too. 

_4. Steps to reproduce (optional):_
Kind of already described above is (3), but specifically for my save:
-put a pathfinder to sleep (there should already be one)
-end turn, and receive Fishing tech next turn
-Select a fortified/alert pathfinder
-Tell it to auto-explore

[Github Bug Report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1065650/Github.Bug.Report.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Any ideas @ilteroi ?

**Comment by ilteroi** [comment]
extremely detailed bugreport, color me impressed.

however, i can't reproduce it. also the provided savegame doesn't work (the usual problem).

@LoneGazebo : care to take a look into the crash dump?

**Comment by LoneGazebo** [comment]
I'll see if I can. What size map, @cammcken ?

**Comment by cammcken** [comment]
Large, 'Small Continents Plus' to be exact (from the DLC maps).
