### ISSUE TITLE
Siege Workshop ConquestProb

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#3279]
I've found that Siege Workshops have a ConquestProb of 0 compared to 66 of the Forge it replaces. This is present as of the first beta of 6/9. Mostly affects Rome I suppose. Intended?

**Comment by LoneGazebo** [comment]
You can't ever conquer a UB anyways except As Rome. And Rome always gets them.

**Comment by HungryForFood** [comment]
Yea, but ConquestProb of 0 means it is always getting destroyed from city capture, so Rome will not get the Siege Workshop.

It does affect other civs as well, the Siege Workshop should turn into a Forge on capture if it is retained, but due to the ConquestProb, you can never get Forges from conquering Ottoman cities.

**Comment by LoneGazebo** [comment]
I'll look.
