### ISSUE TITLE
Razing cities permanently cripples Science/Culture

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3280]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Raze city, Culture/Science costs are kept increased by 14% despite you not getting any benefit from the city.

**Comment by cammcken** [comment]
This has been the case since vanilla Civ5—the policy costs are increased base don the largest number of cities you *once* had. If you raze a city, then build a new one, you'll see that the cost only increases once.

**Comment by Enrico-Swagolo** [comment]
Ah ok
