### ISSUE TITLE
City States not spawning

### ISSUE THREAD

**Issue by Benjemim** [LoneGazebo/Community-Patch-DLL#3288]
_1. Mod version (i.e Date - 4/23):_ (v.88)(5-22-1)

_2. Mod list (if using Vox Populi only, leave blank):_
1. Contextual Unit Names
2. Health and Plague
3. Improvement -Airbases
4. Ingame Editor
5. JFD's Cultural Diversity
6. JFD's Exploration Continued Expanded
7. JFD's Rise To Power
8.  Minimum City Range 
9. Music Changer
10. NoSupplyPenalty
11. PerfectWorld 3
12. Promotions ; Expanded Pack
13. R.E.D Modpack and Hotfix
14. Really Advanced Setup
15. Reforestation
16, Strange Religions
17. Sukritact's Events and Decisions
18.Wonder Race Lost - Gives Hammers Back!
P.S. Not using EUI.

_3. Error description:_ 
I am using the Community Patch version of the City State Diplomacy mod but I experiencing a bug which doesn't allow city states to spawn at all. I have tried using the In game editor to reveal the map and look around just to make sure however I did not find a single city state. I tried changing maps but it didn't work. Any help would be appreciated. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Benjemim** [comment]
I tried disabling More luxuries , didn't work. Also Civ 4 diplomatic features wont work properly without Compatibility Files which in turn is not working without the City state diplomacy mod.

**Comment by Benjemim** [comment]
Ok so the Earth map has city states with no issues but all other still don't.

**Comment by lorduc** [comment]
I had the same problem, most likely its a mod conflict!
Try running Just VP and ingame editor, see if that fixes it and then try it with other mods to find the issue!
mine actually was from "(6c) 43 Civs CP"

**Comment by Benjemim** [comment]
Updated game to latest version then deleted the Civ v folder from documents now its running just fine.
