### ISSUE TITLE
CTD while AI is procesing its units

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#329]
I played 364 turns of version 6-2 (non-EUI, CSD 5-2, C4DF 6-1, More Lux) and jma's latest flavors downloaded on Jun 07. When I hit End turn, I get a repeatable CTD without any error message while the turn of Portugal AI is being processed (I am Germany).

I tried deleting groups of Portuguese units with IGE and found out that it was 2 embarked Mounted Bowmen causing the CTD. When I delete both mounted bowmen in question, the game will proceed to turn 365 without CTD. If I leave either of them in the game, I will get a CTD during the Portuguese AI turn.

I attach a screenshot - one of the guys is next to the Barb swordsman and the other one is next to Tavira city.

![mounted-bowmen](https://cloud.githubusercontent.com/assets/11929356/8146460/193ec740-1239-11e5-87fd-416f745b73d1.jpg)

Please note Portugal has another 3 mounted bowmen, but they are not embarked. They do not cause CTDs.

Gazebo, do you have any idea why these 2 mounted bowmen are causing CTDs? They are embarked and they share their tiles with naval units, so I did a small experiment. After deleting the 2 Mounted Bowmen causing CTDs, I created a new Portuguese Mounted Bowman on 1-tile island with IGE, then waited until AI Portugal embarked it and then put a new Galleas on top of it with IGE. I was sort of hoping that when I press End Turn, it will cause a CTD. Well, it did not ...

I do not know how to attach a zip file with the logs here, so I posted them on CivFanatics:
http://forums.civfanatics.com/showpost.php?p=13861204&postcount=2158

I am running some other mods too, but I do not think they would have any effect on this. Can you see anything interesting in the logs?

**Comment by DanteValerian** [comment]
Do you have a logfile? Are you running Firetuner?

**Comment by Vyyt02** [comment]
Yes, I have a log file, it is attached to the referenced post on CivFanatics - can you download it there? Sorry I do not know how to upload it here. I checked the OperationalAI log and it does not show anything strange. The last entry is related to a Portugues Great Merchant, so it sees it processed the Mounted Bowmen.

No, I am not running Firetuner. Would it help? I feel stupid, but where can I get it?? I cannot find it anywhere on Steam and when I google it, I only get WHoward's instructions on how to add new techs/policies with it, but there is no download link.

**Comment by LoneGazebo** [comment]
Download the civ sdk in steam. Go to the tools tab of your library.

**Comment by LoneGazebo** [comment]
Looking at your log, the error I see is probably related to a colonization operation. I rewrote a bunch of this in the latest version, so you probably won't see it again. I hope.
G
