### ISSUE TITLE
Dummy Buildings from Events

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3291]
Needs to have a failsafe where it doesn't trigger those construction bonuses in cases of dummy buildings and such.

**Comment by LoneGazebo** [comment]
Well, that's a big question. Should event buildings trigger bonuses on construction overall or not? There's no way to parse it in a 'granular' way, it has to be all or nothing.

**Comment by TechpriestEnginseer** [comment]
You have modders even JFD that utilize free event buildings for dummy buildings and this may activate some OP progress/industry building bonus for choosing these decisions.

**Comment by LoneGazebo** [comment]
I'll make them ignore construction bonuses by default. I think it makes sense.

**Comment by TechpriestEnginseer** [comment]
EUI tooltip always show you're getting instant yields from these "construction" bonuses of dummy buildings.

**Comment by TechpriestEnginseer** [comment]
This is not fixed. Even Buildings that have the IsDummy column will still fire up these construction bonus.

**Comment by LoneGazebo** [comment]
I think I marked it by mistake.
