### ISSUE TITLE
260 faith from ruins?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3292]
i just found a "secret religious community" worth 260 faith. in turn 21!

that's like 65 turns worth of regular faith generation. seems a bit excessive?

additional info: this was a classical start and i had just finished stonehenge the turn before, in case that counts for anything.

edit: next ruin was 15 culture ... how boring

**Comment by ilteroi** [comment]
also, assyria never conquers a city. they are much too passive, although their UA depends on conquest.

**Comment by LoneGazebo** [comment]
If you have a pantheon that's a possible bonus - I think it is a random number based on the amount needed to get a great prophet.
