### ISSUE TITLE
Olives monopoly not working

### ISSUE THREAD

**Issue by Alaric410** [LoneGazebo/Community-Patch-DLL#3294]
May 26th version.

Vox Populi only.

Title pretty much says it all.  I reached monopoly status on olives six turns ago but am not getting the bonus food on resources.  

Logs and save game attached.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1082439/Logs.zip)
[Boudicca_0211 AD-0565.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1082440/Boudicca_0211.AD-0565.zip)

**Comment by Alaric410** [comment]
Is the bonus meant to be on olives only?  On re-loading the save file I attached, it appears that I am getting it on olives, but the wording had me expecting it on other resources, or at least other luxury resources.  I suspect I've forgotten how the monopoly bonuses work.  That'll teach me for defecting to Civ VI for six months.  Apologies if I wasted your time on this one.

**Comment by LoneGazebo** [comment]
No, the bonus is for Olives only. :) No worries!

G
