### ISSUE TITLE
AI keeps on attacking encampments

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3295]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I just saw Huns suicide their pathfinder on a barbie camp, endlessly attacking it.

**Comment by ilteroi** [comment]
indeed. interesting effect. false path caching from the barbarian turn. fixed
