### ISSUE TITLE
Spain - UA doesn't proc on cities won through war

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3297]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Basically title. I got Cheongoinbdkrogh from Atilla in a peace treaty, but Madrid didn't get food+faith combo. I think Hero Worship procced, though, which is weird.

**Comment by Enrico-Swagolo** [comment]
I realise the text of the title is slightly misleading as I wanted to use "traded" instead of won, but it's too late to change it.

**Comment by LoneGazebo** [comment]
Well it only counts for conquest for non-settled cities. Trade cities != conquest.
