### ISSUE TITLE
CTD during processing of AI turns

### ISSUE THREAD

**Issue by Alaric410** [LoneGazebo/Community-Patch-DLL#3298]
May 26th version.

Vox Populi only.

CTD during end turn.  Appeared to be processing player 6 although one of the logs suggests player 5.

Replicated twice.  Save game, logs and dump are attached.  Save game is immediately before the issue - just need to hit End Turn to replicate.

[William_0081 BC-1975.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1083876/William_0081.BC-1975.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1083877/Logs.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1083881/CvMiniDump.zip)

**Comment by TechpriestEnginseer** [comment]
That's weird. I had a CTD during the Player 5-Player 6 processing.

**Comment by JBuckli** [comment]
Same here. I'm new to the VP-experience. Seeing player 4 being processed, then reproducible CTD.
Other mods in use besides the full splendor of VP43/EUI: Barbarians Evolved (v 5), InfoAddict (v 22), Really Advanced Setup (v 15), Tectonic Map Script (v 4), Calypso's Colored Religious Icons (Basic) (v 4), CIV-Linked Great Generals (v 11), FlagPromotions (v 7), Promotions - Ancient Ruins Choice (v 2), Promotions - Expansion Pack (v 9), Reforestation (v 8), Ressource - Mint Include Copper (v 2), Unit Path Viewer (v 10), Wonder Race (v 6).
No other civs encountered yet, so @TechpriestEnginseer might be on to something.
[Dido_0124 BC-2260.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1131861/Dido_0124.BC-2260.zip)

**Comment by AnastaseAlex** [comment]
I have similar CTD with the latest (16of July) version
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1156831/Logs.zip)
