### ISSUE TITLE
EUI Tooltip Bug Or...

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3299]
Have unhappiness above 20.

Tooltip will state you will lose 20%+ of your yields and soldiers will be 20%+ combat effectiveness.

Soldiers have a max cap of 20% combat effectiveness, so being in 100 unhappiness doesn't render them 0 combat strength with -100% Combat Effectiveness.

**Comment by LoneGazebo** [comment]
What's the specific tooltip line?

**Comment by TechpriestEnginseer** [comment]
TXT_KEY_TP_EMPIRE_VERY_UNHAPPY
