### ISSUE TITLE
City built 3 tiles from CS

### ISSUE THREAD

**Issue by Txurce** [LoneGazebo/Community-Patch-DLL#3300]
_1. Mod version (i.e Date - 4/23):_6-16-2b

_2. Mod list (if using Vox Populi only, leave blank):_Quick turns

_3. Error description:_ English built an island city (Norwich) 3 tilers from a CS (I forget the name, but it's dead north)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Enrico Dandolo_0234 AD-1620.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1086635/Enrico.Dandolo_0234.AD-1620.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
What's wrong? That's a valid spot.

**Comment by Txurce** [comment]
Am I crazy? I thought you need to be 4 tiles apart.

**Comment by pandasnail** [comment]
Its one less tile than normal when its an island

**Comment by Txurce** [comment]
I had no idea.. and that's a valuable rule to know.

Thanks a lot.
