### ISSUE TITLE
CTD when "Randomized Victory" Victory Condition is chosen

### ISSUE THREAD

**Issue by Grabbl** [LoneGazebo/Community-Patch-DLL#3301]
_1. Mod version (i.e Date - 4/23):_
beta from 6/17

_2. Mod list (if using Vox Populi only, leave blank):_
Full Vox Populi
Community Events
Calypso's Colored Religious Items + Extended
Buildings - Lighthouse Near Sea
Global Warming + Global Warming Congress
UI-Condensed Promotions
Unique City States

Furthermore, some civs (but none of them is in this game):
Vietnam Trung Sisters, Nubia, Canton Pirates, Wei Kingdom (all with Compatibility Patch, from the "Compatible Civs Showcase")

_3. Error description:_ 
Game crashes constantly when the splash screen "Randomized Victory condition chosen" appears (upon entering Information Era). It doesn't crash at the beginning of turn, as the "New Tech" splash screen shows up without problems, only when clicking the "continue" button and the next splash screen shows up. I tested this dependance by delaying Information Era another turn, it crashed again the turn I entered it.

Save, Minidump and Logs attached.

_4. Steps to reproduce (optional):_
Click "continue" on the "Ecology researched" splash screen (and any other splash screens appearing).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
[CTD_Randomized_Victories.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1088868/CTD_Randomized_Victories.zip)

**Comment by Grabbl** [comment]
I can confirm that the CTD remains also on the current beta (hotfix version).

**Comment by LoneGazebo** [comment]
I was not able to confirm - potentially a mod conflict?

**Comment by Grabbl** [comment]
I can reproduce it also with no (additional) mod. However, sometimes I have no CTD, I will do further testing. Also, there seems to be someone in the forum who has the same problem.

**Comment by dzsjollyjellyjollyjello** [comment]
Same for me with the exception that I always have CTD
Starting in information era makes the game 1 turn long
