### ISSUE TITLE
Request for Game.GetOriginalFounder()

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3302]
In the CP, the original founder of a Religion is shifted when the owner of the Holy City of that Religion changes. This is reflected in the Game.GetFounder() method, which, in vanilla, returns instead the original founder regardless of the Holy City controller. Would it be possible to add a means of retrieving the original founder of the Religion, such as a separate Game.GetOriginalFounder(religionID) function? It seems that the changes break Whoward's coloured Religions mod, which I incorporate into Piety, so it'd be useful to have something similar to what is in vanilla. Thank.

**Comment by LoneGazebo** [comment]
@JFDaly yeah I can do that.

G

**Comment by JFDaly** [comment]
Thank, much appreciated

**Comment by LoneGazebo** [comment]
@JFDaly from what I can tell GetFounder still returns the original founder. Code:
`
```
const ReligionTypes eReligion = static_cast<ReligionTypes>(luaL_checkint(L, 1));
	const PlayerTypes ePlayer = static_cast<PlayerTypes>(luaL_checkint(L, 2));

	const CvReligion* pReligion = GC.getGame().GetGameReligions()->GetReligion(eReligion, ePlayer);

	lua_pushinteger(L, (int)pReligion->m_eFounder);
	return 1;
```
`

Player:GetReligionCreatedByPlayer is however affected by this - if you want I could make an 'original' version of this.

**Comment by JFDaly** [comment]
Ah. Yeah, an original version of GetReligionCreatedByPlayer would be great, thanks.

**Comment by LoneGazebo** [comment]
done.

**Comment by LoneGazebo** [comment]
Player:GetOriginalReligionCreatedByPlayer()

**Comment by JFDaly** [comment]
Awesome

**Comment by LoneGazebo** [comment]
Fix is in beta I just posted.
