### ISSUE TITLE
movement issue

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3305]
_1. Mod version (i.e Date - 4/23):_
22 june

https://forums.civfanatics.com/threads/new-beta-version-june-22nd-6-22.619074/#post-14795110
https://forums.civfanatics.com/threads/new-beta-version-june-22nd-6-22.619074/#post-14795151
https://forums.civfanatics.com/threads/new-beta-version-june-22nd-6-22.619074/#post-14795170

**Comment by LoneGazebo** [comment]
@ilteroi, when back in town, will take a look.

**Comment by ilteroi** [comment]
hello again. the zero is just a matter of convention ... if the plot is reachable this turn with movement points left, it's defined as zero turns. up to now that was applied inconsistently and didn't show up in the UI. now it does, but not everywhere. i'll fix that.

can't reproduce the aborted moves though ... @G: care to push your latest version?

**Comment by bigcat88** [comment]
I have aborted moves every turn with just pathfinder. I say to pathfinder to move 2 tiles, he move 1 tile and stop...

**Comment by ilteroi** [comment]
ok i see it now
