### ISSUE TITLE
43 civs, found religion w/o pantheon bug

### ISSUE THREAD

**Issue by Tekamthi** [LoneGazebo/Community-Patch-DLL#3306]
_1. Mod version (i.e Date - 4/23):_

06/09 beta... 43 civs/20 CS in hotseat

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Great Prophet founded religion, but did not have pantheon (missed out on early faith but caught up).  Cannot actually complete and close the 'found religion' interface as a result.  Game is stuck.  (solved by reloading autosave and using proph for tile improvement instead... poor consolation).

_4. Steps to reproduce (optional):_

add modpack to civ 5 assets\dlc folder, place save in hotseat folder and load from that option in civ menus.

dropbox link: https://www.dropbox.com/s/6q01hbx4lq7kijm/43civreligionbug.zip?dl=0

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Yeah that's a consequence of the hard cap on beliefs.

**Comment by Tekamthi** [comment]
Any chance it would be a simple fix to allow a religion to be founded w/o pantheon belief in this situation???  While i woulda had a slightly neutered religion, this would still have been a great result in this game...  

My roommate and I tend to play marathon games that last months, and our civ politicking sometimes spills over into household life here... if things don't go well for me this game, could have serious implications lol...

Anyway thanks G!

**Comment by LoneGazebo** [comment]
No, as the game will crash with the pantheon missing. I am going to add a failsafe so that if all pantheons are gone, it allows you to select any pantheon. Not necessarily balanced, but them's the breaks.

G

**Comment by Tekamthi** [comment]
that fix is a close second from my perspective! Thanks again! It really took some unique effort to catch up on faith after missing pantheons, and seems a shame to otherwise have to pass on religion altogether.  

Re: balance, I realize this failsafe change makes it almost preferable to miss all pantheons and then catch up, rather than build faith strong right from the start.  So, for this failsafe, is it possible to make some kind of random pantheon assignment instead of allowing player to choose?  I think an RNG filter on this would effectively kill any perceived advantage this creates.  Or assign the last pantheon chosen (presumably the worst of the left overs from organic pantheon selections, again mitigating any "gaming" of the failsafe).
