### ISSUE TITLE
Suggestion: Slightly different color for heavy tribute on outliner

### ISSUE THREAD

**Issue by dennisdahlc** [LoneGazebo/Community-Patch-DLL#3308]
This is not a bug, but rather a suggestion if it is possible.

The orange indicator on city states saying if tribute is possible is great, but would it be possible to make a slightly different version if heavy tribute is possible ? That would help out a lot of aggressive players playing the Tribute game.

**Comment by LoneGazebo** [comment]
I try to avoid updating original assets, sorry.
