### ISSUE TITLE
EUI duplicating leader tooltip

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#331]
Upon reload EUI tooltips can randomly show any info twice or even three times.
https://i.imgur.com/L6eLo1a.jpg

**Comment by LoneGazebo** [comment]
Sounds like a bug with EUI. Report to EUI thread, not me.
G

**Comment by Radost** [comment]
I didn't encounter it even once on vanilla playthroughs though.

**Comment by LoneGazebo** [comment]
I understand, but the inner workings of EUI aren't modified by CBP. 
G

**Comment by LoneGazebo** [comment]
Did you find a solution?
G
