### ISSUE TITLE
Building_YieldFromGPExpend

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3310]
Expend GP with Building_YieldFromGPExpend

What Might Supposed to Happen: Food/Production added is in the building's city.

What Actually Happens: Food/Production goes to the capital because all national local yields goes to the capital.

**Comment by LoneGazebo** [comment]
It is WAD as the value is 'global' not local (i.e. the yield array data is stored at the player level, not the city level.
