### ISSUE TITLE
Civilopedia is broken (+ other minor UI glitch)

### ISSUE THREAD

**Issue by Zer0v0** [LoneGazebo/Community-Patch-DLL#3311]
_Mod Version:_
6-25

_Mod List:_ 
Vox Populi with EUI

_Error Description:_ 
Half of Civilopedia is missing. 
Starting from "Buildings" tab and onward, there are no entries except the tab's home page.

Might not be related, but also some of the UI goes black in bottom-left corner (where unit selection is) if you don't have any units. On starting a new game, delete all units except your last settler and then settle the city. Doesn't go away after the next turn.

_Steps to reproduce:_
Start in Industrial Era or later. Starting in Renaissance and before does not cause this issue.
(UI glitch does not follow this rule)

---------------------------
Link to download saves and logs: https://ufile.io/v5hih

**Comment by LoneGazebo** [comment]
You are missing DLC most likely.
