### ISSUE TITLE
Using Yet (not) Another Earth Maps Pack (v 24) limits city states to 20

### ISSUE THREAD

**Issue by lorduc** [LoneGazebo/Community-Patch-DLL#3313]
_1. Mod version (i.e Date - 4/23):_
latest hotfix 

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi
Yet (not) Another Earth Maps Pack (v 24)

_3. Error description:_ 

If I use Yet (not) Another Earth Maps Pack (v 24) and any component of Vox Populi (even just (1) Community Patch), I can only choose 20 city states in "Custom setup" screen
regardless of the map.
using (6c) 43 civ did not change anything
Yet (not) Another Earth Maps Pack (v 24) by itself allows me to choose more more 20
Vox populi without Yet (not) Another Earth Maps Pack (v 24) allows me to choose more than 20
if I use Vox populi and Yet (not) Another Earth Maps Pack (v 24) together but use the set up game option, then I can choose more than 20 city states, however it defeats the purpose of even enabling Yet (not) Another Earth Maps Pack (v 24) since you wont get the benefit of true start location and extra options
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Isn't it because you can only have 43 major players and 20 city-states? Probably that map restricts the number of city-states on purpose for those 43 civs.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer is right. 63-43 = 20.
