### ISSUE TITLE
The DLL doesn't compile

### ISSUE THREAD

**Issue by Mandritti** [LoneGazebo/Community-Patch-DLL#3314]
_1. Mod version (i.e Date - 4/23):_
June 22

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The DLL doesn't compile

_4. Steps to reproduce (optional):_
Notice that CvRandom.cpp @::get(unsigned long, const char*) line:121 has a reference to gStackWalker which isn't defined, anywhere in the file.

---------------------------

**Comment by ilteroi** [comment]
it's an extern included via CvGlobals so i don't think this should be a problem?

**Comment by Iamblichos** [comment]
It shouldn't be a problem. You loading up from the Vox Populi solution? Which branch are you trying to build?

**Comment by Mandritti** [comment]
I was trying to build with some changes to CvUnit::pillage and some Building database stuff, but didn't notice that the material I started with was invalid C.

I've tried in both the VP solution and the VS2010 solution.  Build complains in three places about undeclared gStackWalker 's and then fails.

**Comment by Iamblichos** [comment]
Yeah you could be missing some prereq stuff.

**Comment by Mandritti** [comment]
Setting Visual Studio to compile for Release instead of Debug fixed the issue.

What do you mean by prereq stuff?  Is CvGlobals and its declaration not getting into the header?
