### ISSUE TITLE
Misaligned MOD_BALANCE_CORE preprocessor insert

### ISSUE THREAD

**Issue by Mandritti** [LoneGazebo/Community-Patch-DLL#3315]
_1. Mod version (i.e Date - 4/23):_
June 22

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Line 24608 of CvCity.cpp  parses an an identifier iAdjUnitDefense which is only conditionally declared if the preprocessor define MOD_BALANCE_CORE exists.

_4. Steps to reproduce (optional):_

---------------------------
Suggestions:  Moving the  #endif below the next two lines should fix things up.

**Comment by TechpriestEnginseer** [comment]
So, it's only a problem if CBP isn't utilized?

**Comment by ilteroi** [comment]
na, that define is what separates CP from vanilla. but we've long since stopped applying it religiously, as the changes are just too many and there's no way going back anyhow. i expect if you undefine it, there will be errors and crashes all over the place.

**Comment by LoneGazebo** [comment]
Yeah. We abandoned our protocol when we decided to rewrite the whole damn thing from scratch (essentially). :)
