### ISSUE TITLE
Comment Errors

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3316]
````
-- Promotion grants additional combat strength if on a pillaged improvement
ALTER TABLE UnitPromotions ADD COLUMN 'ReligiousPressureModifier' INTEGER DEFAULT 0;
````
I have no idea what this does beside maybe missionary and Great Prophets may somewhat benefit from this maybe this unit provides religion pressure. Beats me.
````
-- Allows for All Units/Buildings to be purchased in puppet city
ALTER TABLE Buildings ADD COLUMN 'AllowsPuppetPurchase' BOOLEAN DEFAULT 0;

-- Allows for Building to be purchased in puppet city
ALTER TABLE Buildings ADD COLUMN 'PuppetPurchaseOverride' BOOLEAN DEFAULT 0;

-- Allows for Unit to be purchased in puppet city
ALTER TABLE Units ADD COLUMN 'PuppetPurchaseOverride' BOOLEAN DEFAULT 0;
````
Needs to be clarified that you need a modified CityView panel because EUI doesn't support these columns.

**Comment by Iamblichos** [comment]
I created the first entry. The label is wrong. Pretend it said this:

-- Promotion grants additional religious pressure when this unit is garrisoned in the city (if the player has a religion).

Works like a building with religious pressure except it is the garrisoned unit that creates it. There won't be a CityView breakout to differentiate how much the city is contributing to default religious pressure and how much the unit adds to that value. Just totals a value.

**Comment by TechpriestEnginseer** [comment]
But if I move out and in of a city, I can see at least the total religion pressure change right?

**Comment by Iamblichos** [comment]
I can't remember if it is that robust. But definitely updates on next turn.

**Comment by TechpriestEnginseer** [comment]
Ah fair enough! I'll use it for a modmod of mine now...

**Comment by LoneGazebo** [comment]
@Iamblichos I created a unit variable for this promotion so that it isn't looping through promotions every time the garrison changes. Generally loops like that should be avoided (it is a really expensive loop). :)
