### ISSUE TITLE
Barbarians have sacked [City State]

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#3317]
_1. Mod version (i.e Date - 4/23):_
22 June Beta

Seen this happen in two of my game. The city state does appear conquered the first time it's been sacked, but when it happens a second time, this happens. The CS is not actually conquered.

![image](https://user-images.githubusercontent.com/8049731/27738364-0a68356e-5da3-11e7-8a9a-100033b8898e.png)

**Comment by TechpriestEnginseer** [comment]
Maybe it's a naval thing. Can you replicate it where a barbarian was on a land tile?
