### ISSUE TITLE
Caravansary text bug.

### ISSUE THREAD

**Issue by TakagiHiro** [LoneGazebo/Community-Patch-DLL#3320]
_1. Mod version (i.e Date - 4/23):_
June 22 Beta (and probably every single version prior, tired of looking at this...)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
"Nearby" is spelled as "Neabry" when listing the yields furs would provide.

_4. Steps to reproduce (optional):_
Look at the Caravansary tooltip, profit. As an aside, would you be interested in more of these reports? I've noticed many different typos here and there and wouldn't mind compiling them.

**Comment by LoneGazebo** [comment]
Yeah, I appreciate them.
