### ISSUE TITLE
Siam's UB disabled with espionage setting off.

### ISSUE THREAD

**Issue by TakagiHiro** [LoneGazebo/Community-Patch-DLL#3322]
_1. Mod version (i.e Date - 4/23):_
June 22 Beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Siam cannot build their UB as it is a Constabulary replacement, and these are, apparently, disabled in "no espionage" games. Seems too harsh for them to be intended.

_4. Steps to reproduce (optional):_
Well, play a game with no espionage as Siam, unlock their UB, and try to build them. By the way, you'll fail, just a heads up!

**Comment by TechpriestEnginseer** [comment]
Wait but constabulary also reduces crime. The game is telling us that we should be grateful of spies for without spies means major crime!
