### ISSUE TITLE
Suggestion for AI roads.

### ISSUE THREAD

**Issue by TakagiHiro** [LoneGazebo/Community-Patch-DLL#3323]
If it is at all possible, please try to teach the AI to remove roads that provide no benefit to it, and prevent it from building extremely looong roads to a far off city. I tell you, it always hurts to see this happen, watching the AI absolutely destroy its economy on road costs and busying their workers with such a wasteful task. It's especially painful watching them build a road around a civ's borders, having the roaded tile be claimed by that civ, and breaking their connection.

I do understand if it's not possible to do, but something's really got to give. The AI game could be so much stronger with such a fix.

On another note, perhaps prevent the player from building roads in AI territory, as the player can sabotage 100% effectively if the AI never decides it should be removing these.

**Comment by ilteroi** [comment]
not building roads on unowned tiles adjacent to foreign territory: check

not building long roads through wilderness: check

preventing roads in foreign territory: check. city states excluded from the exclusion

removing useless roads: thought about that before, not impossible, but a) surprisingly hard to tell which roads are useful and which aren't and b) a lot of effort to hook this remove route mission into the AI. also  i'd probably need to promote some roads between non-capital cities to official city connections. which has side effects for human players as well. i'll hold off on that for now

**Comment by TakagiHiro** [comment]
That's amazing, great job through and through!
