### ISSUE TITLE
Retained sight for areas out of view.

### ISSUE THREAD

**Issue by TakagiHiro** [LoneGazebo/Community-Patch-DLL#3324]
_1. Mod version (i.e Date - 4/23):_
June 22 Beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Sight is retained in random spots of the map, despite having no units that can see the area. This does not refer to the recent change about seeing areas uncovered for the rest of your turn; this persists indefinitely.

_4. Steps to reproduce (optional):_
I... really have no idea. It just kinda happens.

**Comment by ilteroi** [comment]
do you have a screenshot or a savegame?

**Comment by TakagiHiro** [comment]
Not at present, but I'll provide on the next occurrence; it's actually fairly frequent.

**Comment by TakagiHiro** [comment]
Alright, you asked for it, you got it! Luang Prabang (bang!) has sight all around it and Vatican City, but I have no units in the vicinity that should be able to see the area. The scout over in the east never moved this turn, nor can it see that far from its location. Screenshot and save below.

![image](https://user-images.githubusercontent.com/29812136/27770717-e21a4b04-5f11-11e7-8685-45ba695d9898.png)

[AutoSave_0162 AD-1020.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1117849/AutoSave_0162.AD-1020.zip)

**Comment by Grabbl** [comment]
Perhaps it's not exactly the same thing, but probably related:

I retain sight around lost cities (also a few turns after), see screenshot. It doesn't happen everytime and with every city (see Dur-Kurigalzu above). Both Akkad and Babylon were lost multiple turns ago, not last turn.

Save & Logs: 
[Visibility_Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1117756/Visibility_Bug.zip)

Screenshot: 
![20170702130319_1](https://user-images.githubusercontent.com/19163988/27770547-b84a00a6-5f40-11e7-8eaa-541d72118411.jpg)

**Comment by TakagiHiro** [comment]
I think you lost the game. ;)
