### ISSUE TITLE
No Combat Odds when Ship is fighting non-embarked troops.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3333]
Naval units don't get a combat odd against units inside forts despite being able to attack them if they are inside a fort.

Same issue in the Civil War Scenario unaddressed when ironclads attempt to attack Union/Confederate troops on Pontoon Bridges.

**Comment by LoneGazebo** [comment]
Yeah, there's no LUA support for it baked-in. Lots of work for a niche issue unfort.
