### ISSUE TITLE
"Resources from Events"

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3335]
Can we have just a tooltip where it usually displays where the resources you are getting from which city in the TopView to have a resource received from resources or deducted away. I'm having trouble keeping track of how much "true iron" I have with Zealotry.

**Comment by LoneGazebo** [comment]
Maybe - that's a big task (lots of pseudo math).

**Comment by TechpriestEnginseer** [comment]
Well I was thinking you just subtract the total from all the cities.

**Comment by LoneGazebo** [comment]
Not sure what you are looking for exactly.

**Comment by TechpriestEnginseer** [comment]
I have 30 iron with the Zealotry belief(assuming I have the max follower or whatever Zealotry needs now for more resources) and some events gathered.

8 iron from Attila's Court
6 iron from Washington
so, we can conduct simple arithmetic
30-14 =
16 iron from Events/Beliefs
