### ISSUE TITLE
Retained Sight isn't Retained Sight.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3337]
Have a guy with Indirect Fire promotion. He shoots at a city 2 range from him, but the tile between them is a hill.

Scout goes up the hill and the guy can shoot at the city. Scout leaves the hill, guy can no longer shoot at the city despite having "retained" vision over the city.

**Comment by ilteroi** [comment]
cannot reproduce. screenshot?

**Comment by ilteroi** [comment]
try this build

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1122908/CvGameCore_Expansion2.zip)

**Comment by TechpriestEnginseer** [comment]
Yeah you must have fixed it. I can't reproduce it anymore as well with this hotfix. Maybe I'll go back to a previous game because artillery with dead zeppleins falling down from the skies were annoying me.
