### ISSUE TITLE
Cities built 3 spaces from each other

### ISSUE THREAD

**Issue by Txurce** [LoneGazebo/Community-Patch-DLL#3338]
_1. Mod version (i.e Date - 4/23):_6/25 (includes ilteroi hotfix)

_2. Mod list (if using Vox Populi only, leave blank):_

Info Addict, Quick Turns

_3. Error description:_ 

Byzantium built a city within 3 tiles of a CS

_4. Steps to reproduce (optional):_

take a look - Byzantine city is just south of Babylon, near a CS
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Nebuchadnezzar II_0122 AD-0175.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1128161/Nebuchadnezzar.II_0122.AD-0175.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
Was the city on another island ? City distance is 4 for cities in the same land mass, and 3 for cities on different islands.

**Comment by Txurce** [comment]
The cities were on different land masses. I would call them small
continents, not islands, but I'm sure it's the same thing for the code.

Now I finally understand how this works. Thanks a lot.
