### ISSUE TITLE
Defensive pacts may not work

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#3339]
_1. Mod version (i.e Date - 4/23):_ 6/22 with ilteroi dll (https://github.com/LoneGazebo/Community-Patch-DLL/issues/3337)
_2. Mod list (if using Vox Populi only, leave blank):_ VP+"(7) Community Events" from Enginseer.
_3. Error description:_ 
(Short) I've been declared war while with a defensive pact with the Inca, and they didn't declare war. It is reproducible.
(Long) Earlier in the game I made 2 DP (one with Sweden, the other with the Incas). Then Indonesia declared war to me, and both DP worked. No bugs for the moment. Then peace everywhere. Then Declaration of Friendship end with my two allied, but only Sweden accept to renew it. Then Indonesia and China declare war to me : 
-> Sweden, with a DP and a DF declare war to the two of them.
-> Inca, with a DP (but no longer any DF) do NOT declare war to any of them.

_4. Steps to reproduce (optional):_
Load the save, clic on "NEXT TURN", and watch.
[Casimir III_0558 AD-1954-January.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1133948/Casimir.III_0558.AD-1954-January.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
Logs : 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1133955/Logs.zip)

**Comment by LoneGazebo** [comment]
Most likely another deal blocked them from joining.
