### ISSUE TITLE
Jelling Stones naming

### ISSUE THREAD

**Issue by Phalanx1** [LoneGazebo/Community-Patch-DLL#3342]
_1. Mod version (i.e Date - 4/23):_
6/22

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This one is not a bug, just a suggestion. AFAIK, when the Jelling Stones were introduced, they were a National Wonder. This has since changed, and you can build one in every city. This situation is a bit inconsistent, seeing as Jelling is a city (which, by the way, is in Denmark's city list). I suggest renaming them to [Runestone](https://en.wikipedia.org/wiki/Runestone) , thus making the name more generic and compatible with every city which they are built in.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Agreed.
