### ISSUE TITLE
Aztec Starting Unit

### ISSUE THREAD

**Issue by Phalanx1** [LoneGazebo/Community-Patch-DLL#3344]
_1. Mod version (i.e Date - 4/23):_
6/22

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In the current mod version, the Aztecs start with a Pathfinder. In my opinion, it would be better if they had a Jaguar at the start, seeing as the Shoshone started with their unique Scout in previous versions, even though the standard starting unit was the Warrior.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Typically I'd agree, but the Aztecs hardly need an early game buff. The Shoshone did need one, however.

**Comment by LoneGazebo** [comment]
If you want, push the argument to the forums, see what they think.

**Comment by LoneGazebo** [comment]
Poll was not conclusive, closing.
