### ISSUE TITLE
**duplicate, and solved. please close** Reproducible error on T312 - Cannot proceed

### ISSUE THREAD

**Issue by a1nosweat** [LoneGazebo/Community-Patch-DLL#3345]
_1. Mod version (i.e Date - 4/23):_
22/6

_2. Mod list (if using Vox Populi only, leave blank):_
VP full-EUI.  Not just another earth pack

_3. Error description:_ 
Next turn button does not work on T312 - Devastated  Was really into this game :)

_4. Steps to reproduce (optional):_
Move units, end turn.  Have tried using autosaves, going back as far as 306 (so far).  Always ends on 312
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1149250/logs.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 

5. Make sure you have enabled logging before experiencing an error! Go here to find out how: 
http://forums.civfanatics.com/showthread.php?t=487482):

[saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1149243/saves.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSa
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1149246/logs.zip)
ves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

**Comment by LoneGazebo** [comment]
You don't actually have full logging enabled. Enable AI logging as well and try it again. If you can pinpoint which AI is causing it that helps.

G

**Comment by a1nosweat** [comment]
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1149501/logs.zip)
Okay - here we go - any suggestions on how to carry this game on would be most enjoyed.  Cheers G!

I don't think its an AI problem - It's like the game is expecting me to do something on my turn.  the !st Ai is either Mongolia or the Hun

**Comment by a1nosweat** [comment]
duplicate of #3329  Solved it - had two workers building roads towards each other!

**Comment by LoneGazebo** [comment]
Nice!
