### ISSUE TITLE
Typo: Glory of God (7/15)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#3347]
cf.
(2) Community Balance Overhaul\Balance Changes\Beliefs\Reformation.sql
Line: 185

> 	('BELIEF_TO_GLORY_OF_GOD', 'GREATPERSON_WRITER', 'YIELD_FAITH', 5);

should be

> 	('BELIEF_TO_GLORY_OF_GOD', 'GREATPERSON_WRITER', 'YIELD_FAITH', 2);

**Comment by LoneGazebo** [comment]
already fixed
