### ISSUE TITLE
Conquest effects don't work

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3348]
_1. Mod version (i.e Date - 4/23):_
current beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

The "get yields when conquering for first time only" thing made it never work at all. Try to conquer Nicomedia by hitting it with a Horsemean. My Denmark never had that city, but I won't get neither Hero Worship nor Authority Imperium yields.
[attacknicomedia.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1150276/attacknicomedia.zip)

And look at the Trireme, it randomly ended up there (not on the save, I accidentally moved it soon after I noticed it's placement but I've still made a screenshot). I've done it by moving the mouse fast between the ocean tile and regular tile, but I couldn't re-do it.
[20170715133554_1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1150278/20170715133554_1.zip)

Also the previously mentioned in other threads movement turn indicator is still broken. Sometimes it tells me an unit gets to tile X in one turn, but it's impossible etc.

**Comment by LoneGazebo** [comment]
fixed. hotfix inc.
