### ISSUE TITLE
Harappan Reservoir tooltip bug

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#335]
Harappan Reservoir: Something messed up with +30% population growth info.
Tea Pavilion: Same issue.

**Comment by LoneGazebo** [comment]
At what point? In the leader screen info? If so, with EUI, that's normal, as the text isn't fully initialized yet.

G

**Comment by Finarvi** [comment]
Yes, in leader screen.

**Comment by LoneGazebo** [comment]
That’s normal – can’t stop that, sorry.

G
