### ISSUE TITLE
Glory of God is 50% broken for followers

### ISSUE THREAD

**Issue by InapropriateUsername** [LoneGazebo/Community-Patch-DLL#3354]
_1. Mod version (i.e Date):_
6-22 with latest update from forum

_2. Mod list (if using Vox Populi only, leave blank):_
flag promotions
improved city view

_3. Error description:_ 
Not sure if this was adressed in latest version. Did not have time to check. Sorry if it was
Glory of God does not work properly for those who adopted religion. They get yields, but can't buy Great People for faith.

_4. Steps to reproduce (optional):_

---------------------------

**Comment by LoneGazebo** [comment]
It has to be your overall majority religion, has to be the local majority, and it has to be industrial or later.

**Comment by InapropriateUsername** [comment]
I know that, and it was. I had this twice, once i was founder and my friend took my religion, the other time i adopted religion founded by my friend

**Comment by LoneGazebo** [comment]
Ahh I see why. I missed an old check that forced it to look for founders. Fixed.
