### ISSUE TITLE
Iron Fist gives way more from vassals than advertised

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3355]
_1. Mod version (i.e Date - 4/23):_

15th after hotfixes, not 16
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I took the Iron Fist while I've had some Culture, Science and Faith from my 4 vassals, but after taking it I got way, way more than twice the stuff. I've confirmed that by loading before taking it, it's way bigger a gain. Both values are now deep in the hundreds. I didn't notice a sudden spike of the sort with CS values so they are probably fine.

**Comment by LoneGazebo** [comment]
It is WAD. It is 50% more than normal (which I think is 20%) - so it goes from 20% to 70% of their yields.

**Comment by LoneGazebo** [comment]
I guess the description isn't 100% clear - if it feels too strong I can make it a 50% modifier to the 20%, but that felt a little underwhelming to me.

**Comment by Enrico-Swagolo** [comment]
To be honest considering I have 4 vassals (one has 5 or 6 cities, one 5-6, one iirc 3, one 2) and 10 city state allies it doesn't seem OP at all, the game is already won anyway if you get to that point, I was just reporting it out of honesty, but good to find out.
