### ISSUE TITLE
Worker deadlock : automated worker will try (and fail) to upgrade road into railroads in forein territories

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#3356]
_1. Mod version (i.e Date - 4/23):_7/15 (41 civ)
_2. Mod list (if using Vox Populi only, leave blank):_"(7) Community events"
_3. Error description:_ 
I have a city connection that pass trought forein territory (using open borders), and all my automated workers are waiting on forein roads, unable to upgrade them. (Note that the "worker advisor" advice to upgrade the road into a railroad, but the action is not possible).
No crash or anything like that, just 8 workers waiting in a forein territory...

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1153275/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Bug_worker_Theodora_0462 AD-1872.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1153277/Bug_worker_Theodora_0462.AD-1872.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![screenshot](https://user-images.githubusercontent.com/8081919/28277911-9e417946-6b1b-11e7-99ea-99f48187ba44.png)

**Comment by LoneGazebo** [comment]
You can't modify tiles in foreign land.

**Comment by TechpriestEnginseer** [comment]
Which was patched because someone abused the "make road on every foreign tile" to abuse their economy.

Unfortunate but the AI can't be taught to make roads to foreign cities, so the chance of this restriction being lifted seems nigh impossible.

**Comment by MoiMagnus** [comment]
That is not the problem. The problem is that automated workers WANT to do so. And it is one of their top priorities so they will not repair my farms until this impossible railroad is finished...

**Comment by LoneGazebo** [comment]
Ahh, I see. I'll tell automated worked to STFU.

**Comment by ilteroi** [comment]
just exclude owned plots from m_aiNonTerritoryPlots
