### ISSUE TITLE
Mouvement issues

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#3357]
_1. Mod version (i.e Date - 4/23):_ 7/16
_2. Mod list (if using Vox Populi only, leave blank):_
_3. Error description:_ It is some issues that appear a lot in the forum (so you probaby already know about them), but they do not seems to have a Github page (which may be annoying), so here it is : 
1) When asking a unit to make a movement, this unit may stop in the middle of their movement, asking again for orders. This happen a lot, whithout good reasons (i.e no ennemis detected, or anything like that). In my games, it appear approximatively once per turn (different unit each time), so I don't have a particuliar save/log/screenshot. If you fail to reproduce it, I can launch a game and try to have the logs.
2) Preview of the number of turns for a mouvement is false. Currently (at least with EUI) : 
0 means that you will have remaining mouvement points.
1 means either that you will have no remaining MP, either that it will take one more turn and you will have remaining MP
2 means either that it will take one more turn and you will have no remainaing MP, either that it will take two more turns and you will have remaining MP
etc...
And it is not what you would want for the preview. 
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
what would you want for a preview?

**Comment by MoiMagnus** [comment]
I want "arrive this turn with no remaining MP" and "arrive next turn" to be different, because there is a crucial difference between finishing a unit, and stopping your mouvement next to it.
Either the Vanilla preview :
1 -> Arrive this turn (with or without remaining MP)
2 -> Need 1 more turn.
3 -> Need two more turns.
Or :
0 -> Arrive this turn
1 -> Need 1 more turn
2 -> Need 2 more turn
I will even be fine with a bastard :
0 -> Arrive this turn with remaining MP
1-> Arrive this turn with no remaining MP
2 -> Need 1 more turn (any remaining MP)
3 -> Need 2 more turns
Or if you have time to lose (but that would not probably be liked by a lot of people), for a 2 MP unit :
0.5 -> Will have 1 remaining MP
1 -> Arrive this turn without remaining MP
1.5 -> Need one more turn, but will have 1 remaining MP.
2 -> Need one more turn, no remaining MP.

**Comment by MoiMagnus** [comment]
(Note that from a personal point of view, the current state of the preview is not that annoying, since I've found the logic, but a lot of person on the forum consider it as a bug, and the goal of this issue was to report some problems recurring in the forum)

**Comment by ilteroi** [comment]
can't do fractional numbers, that's why i chose the current solution. i think it's important to see whether you will have movement left at target, so only the "bastard" variant remains, but in my opinion it's no improvement. maybe set up a poll?

**Comment by ilteroi** [comment]
the effort for all the integer-number variants is about the same.

i am very much against options though. we have too many options already and all the possible combinations create an untestable nightmare.

**Comment by MoiMagnus** [comment]
I see. So we will just wait for the result of the poll. (Currently in favour of the bastard solution.)

**Comment by LoneGazebo** [comment]
@ilteroi why can't we push floats to the UI? Or rather, what if we just scaled movement to 100 in the function and then divided in the UI for decimals? May be unwieldy.

**Comment by ilteroi** [comment]
the struct used to pass the data (CvDllPathFinderUpdateListData) takes only ints and we cannot change it since it's used in the DLL interface.

the scale factor trick might work if the display part is actually handled by lua. and if you can find it :)

**Comment by LoneGazebo** [comment]
Look at pathhelpmanager.xml/lua 

C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Civilization V\Assets\UI\InGame\WorldView

**Comment by MoiMagnus** [comment]
One problem of fractional number would be readability. If you go in that direction, is it easy to make the decimal part appear in "little", and the integer part appear in "big" ?

**Comment by LoneGazebo** [comment]
> One problem of fractional number would be readability. If you go in that direction, is it easy to make the decimal part appear in "little", and the integer part appear in "big" ?

No.

**Comment by ilteroi** [comment]
added the *10 + x on c++ side, but the problem is i have litte experience with lua, let alone debugging it. can you check why this script isn't working?

[PathHelpManager.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1158227/PathHelpManager.zip)

**Comment by LoneGazebo** [comment]
Yep. Also note that some users are reporting that civilian units are ending multi turn moves every turn. They're being interrupted by something.

**Comment by MoiMagnus** [comment]
Yes, that was the "1)" of my issue.

**Comment by LoneGazebo** [comment]
@ilteroi what is the lua function you edited doing/not doing? Code looks fine - how did you load it? Did you use a breakpoint in the DLL to see if that script is actually being accessed by the UI?

G

**Comment by LoneGazebo** [comment]
Edit: code does not look fine - you are missing a 'then' on line 36. And you don't need to put 'int' in there - int is assumed (local = auto).

**Comment by LoneGazebo** [comment]
![image](https://user-images.githubusercontent.com/7849458/28378182-4c9034bc-6c7d-11e7-9175-885ff7777218.png)

Always says 0.5, however.

**Comment by ilteroi** [comment]
thanks for the hint. the int is necessary for rounding though.

i know about the 5,

**Comment by ilteroi** [comment]
ok, also fixed the multiturn move missions.

all pushed. enjoy!

**Comment by LoneGazebo** [comment]
Will do thanks. Glad you got it figured out!
