### ISSUE TITLE
Espionage before enabled

### ISSUE THREAD

**Issue by deimerl** [LoneGazebo/Community-Patch-DLL#3358]
_1. Mod version (i.e Date - 4/23):_
7/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Espionage started before the renaissance era

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1154107/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[AutoSave_0180 AD-1200.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1154096/AutoSave_0180.AD-1200.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
1st screenshot, proof no one is able to spy yet:
[![Screenshot from Gyazo](https://gyazo.com/50bc4e59140e688c69c5ed204c3b05ea/raw)](https://gyazo.com/50bc4e59140e688c69c5ed204c3b05ea)
2nd screenshot, research stolen from my capital
[![Screenshot from Gyazo](https://gyazo.com/f5860cb057870156e52a99638339c993/raw)](https://gyazo.com/f5860cb057870156e52a99638339c993)

**Comment by LoneGazebo** [comment]
He got spies from statecraft.

G

**Comment by TechpriestEnginseer** [comment]
He's saying the tooltip should be fixed where you can get spies without the Renaissance Era now.

**Comment by LoneGazebo** [comment]
I don't think he is - nevertheless the text isn't wrong. :)

G
