### ISSUE TITLE
CTD possible when loading leaderheads or AI turns

### ISSUE THREAD

**Issue by Tarzan737** [LoneGazebo/Community-Patch-DLL#3359]
_1. Mod version (i.e Date - 7-16b

_2. Mod list (if using Vox Populi only, leave blank):_ 

Quick turns V10 (possible issue for me since it hasent crashed a test game without quickturn mod)

_3. Error description:_ 

CTD during AI turn, maybye when loading leaderscreen when meeting a new civ!
i can load a saved game and it doesent crash at the same point.

_4. Steps to reproduce (optional):_

try my savegame i use Vox populi without EUI

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1157406/Logs.zip)
[Test 2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1157410/Test.2.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Tarzan737** [comment]
I unchecked the vsync and gpu texture decode boxes in video options menu, i could play without testing more than 5-10 min but no CTD, i will try more when i have time. But could it be what causes my problem?
im on a Laptop currently but on the desktop computer at home i don´t use to have problems with CTDs

**Comment by Tarzan737** [comment]
i will let you know anyway! so you possible can remove this issue!

**Comment by Tarzan737** [comment]
i played 1 hour yesterday without any  crash! you can close this! it is something strange with graphic settings!

**Comment by LoneGazebo** [comment]
Cool.
