### ISSUE TITLE
Cannot choose production in capital 1st turn

### ISSUE THREAD

**Issue by sbbln314159** [LoneGazebo/Community-Patch-DLL#3363]
_1. Mod version (i.e Date - 4/23):_
7/19

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi with EUI and support for 43 civs

_3. Error description:_ 
Cannot complete first turn because, upon founding my capital, I cannot choose production in the city.  Also, icons are missing from the upper left corner of the screen (ie, monopolies, defense, cities, etc).  
I was able to reproduce the issue with 6 different civs, on different maps, at different game paces.  I think it might be an issue with the EUI, since it disappeared when I uninstalled Vox Populi and re-installed it without EUI.  I would prefer to play with EUI though.

Screenshots:
![cannot select production](https://user-images.githubusercontent.com/30299010/28383573-94931dc6-6c8f-11e7-92e2-97dc98ca19f7.jpg)
![display error - icons appear to be missing from upper left](https://user-images.githubusercontent.com/30299010/28383576-98d3d7cc-6c8f-11e7-855a-d01e2f439edb.jpg)

Logs:
[Logs - Copy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1160120/Logs.-.Copy.zip)

Thank you for your help!!
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482
[Logs - Copy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1160119/Logs.-.Copy.zip)
):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
My best guess is that EUI is not ending up in your civ DLC folder.

**Comment by TechpriestEnginseer** [comment]
Can't be exactly Vox Populi if he starts with a Warrior instead of Pathfinder?

**Comment by LoneGazebo** [comment]
Good point.

**Comment by MoiMagnus** [comment]
The logs say that he is at least playing with CP : "CvDllContext.cpp[162]: CvDllGameContext::DestroySingleton - Community Patch v88 (PNM v51+) - Shutdown"

**Comment by sbbln314159** [comment]
Gazebo was right, EUI was not in my civ DLC folder.  I added it manually using PrimEvalCIV's youtube video guide ( https://www.youtube.com/watch?v=Ud_wH4Q8W9I ).  However, I still had the same problem.  
I'd used the automatic installer, so I tried uninstalling everything and reinstalling it manually, in case there were similar, parallel problems.  No dice.  I also still started out with a warrior instead of a pathfinder, as TechpriestEnginseer pointed out.  
I have a nagging feeling I'm either selecting the mods incorrectly, or that something is still installed improperly.  Thank you all again for  your help!

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1163313/Logs.zip)

**Comment by a1nosweat** [comment]
I have this using "7-19-17 Innovative Tamaranian Modpack"  I don't know what causes it, but deleting and reinstalling fixed it...Sort of.  I came here to see if anyone has reported the bug I've found.  Just trying to replicate without ynaemp and enginseers events mods.

**Comment by LoneGazebo** [comment]
@sbbln314159 make sure you are installing it all, enabling the mods, then clicking next. Also make sure you have all relevant DLC and whatnot.

**Comment by sbbln314159** [comment]
Thank you all for your help!  I managed to fix it by uninstalling the mods, civ, and steam, then re-installing them all.  Don't know why it didn't install correctly before!

**Comment by LoneGazebo** [comment]
Great!
