### ISSUE TITLE
Ceremonial Burial Founder Belief not giving right amount of faith

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#3367]
_1. Mod version (i.e Date - 4/23):_
7/18 beta

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi, InfoAddict and R.E.D.  unit Modpack

_3. Error description:_ 
Getting right amount of culture but only 5 faith per Great Person expended

![20170719235125_1](https://user-images.githubusercontent.com/13261433/28401253-67316938-6cde-11e7-913f-a46f4e89466f.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Pretty sure it's +50 Culture from Tradition since you get 50 Golden Age Points from doing so.

So +5 Culture and +5 Faith seems right.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer is correct. The best kind of correct.

**Comment by oalzubbi** [comment]
I don't understand. It's supposed to be 5 culture and faith per follower, right?
