### ISSUE TITLE
EUI working but Not CBO in multiplayer ?

### ISSUE THREAD

**Issue by TriggeredTony** [LoneGazebo/Community-Patch-DLL#3368]
_1. As of July 19th 

_3.  I've been trying to start a multiplayer game in Civ V with Vox Populi mod on ( with EUI ) and for every game I've tried to see if it had changes like corporations , it only had the BNW civilopedia and tech tree . On the other hand , when I first installed VP and tried to run a multiplayer game , the corporations overview would pop up but would not close. I cant tell what Im doing that is causinf both issues. Im using the modpacks only 

_4. I never had a CTD , so I didnt think to check any logs or minidumps when CBO wasn't working. However for my second issue where the corporations overview wouldn't close I tried to replicate it in single player and I managed to ,  and searching around in the mods menu it said that I couldnt run C4D with CBO , but I could run a different  Civ 4 Diplomacy mod with it . Im not at my computer right now so I dont know the exact name. My next try will be to install no EUI

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Delete all mods from MODS folder and all modded content from your DLC folder. Clear your cache, reinstall the modpack, and try it all again.

**Comment by TriggeredTony** [comment]
@LoneGazebo   Single player is fine now ( attached screenshot ) , but multiplayer is giving me a tough time . The second screenshot is of the modpack in the DLC folder since I'm lost . To add on , after installing the modpack back there was no cache in the My Games > Civ 5 directory , which I think was because I didn't start the game again ? 


![20170720152401_1](https://user-images.git
![screenshot 1](https://user-images.githubusercontent.com/30310181/28435662-f9b85b62-6d61-11e7-9c0e-a5924eb5e35f.png)
hubusercontent.com/30310181/28435485-187467d6-6d61-11e7-916e-bce02c271534.jpg)

**Comment by LoneGazebo** [comment]
What's wrong with that MP picture? The modpack doesn't have an icon in the menu. Make sure you are on the latest version of civ (.279 IIRC).

**Comment by TriggeredTony** [comment]
I have version .279 , and I ended up hitting a wall in trying to replicate the corporation overview not closing in MP since that was when the mod was actually running , and ironically when EUI was not working properly and saying POLICIES:OFF where faith is supposed to be .

**Comment by TriggeredTony** [comment]
I managed to get it to work thankfully . Thanks for pointing out the modpack icon as it gave me a hint as to how to fix the issue .
