### ISSUE TITLE
BUG: game crashes when popping ancient ruins with a city

### ISSUE THREAD

**Issue by Muminus** [LoneGazebo/Community-Patch-DLL#3369]
_1. Mod version (i.e Date - 4/23):_
1. Community Patch v.88
2. Community balance overhalul v.13
3. City-State diplomacy mod for CBP v.27
4. C4DF - CBP v.11
5. More Luxuries - CBP Edition 5-14b v. 155
6. Community Balance Overhaul - Compatibility Files EUI v.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Game crashes to desktop when settling a city near ancient ruins.

_4. Steps to reproduce (optional):_
Find an unpopped ancient ruins, settle a city near it.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
What date version for CP?

**Comment by Muminus** [comment]
5-22-1

**Comment by Muminus** [comment]
[2Kamehameha_0193 AD-1330.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1164782/2Kamehameha_0193.AD-1330.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1164790/CvMiniDump.zip)
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1165699/logs.zip)

**Comment by LoneGazebo** [comment]
Please update to the latest version.

**Comment by Muminus** [comment]
After updating to version 7-18-1 I am unable to load the save from previous version (the game crashes to desktop on load). However, I started a new test game just to check if the bug exists and it seems it is fixed - I can settle near ruins. So thanks for fixing that,

Darek

**Comment by LoneGazebo** [comment]
No worries. And yeah, that jump is not savegame compatible.
