### ISSUE TITLE
[feature request] anarchy notification

### ISSUE THREAD

**Issue by qqqbbb** [LoneGazebo/Community-Patch-DLL#337]
Display a notification when your empire enters anarchy.

**Comment by LoneGazebo** [comment]
Explain? Doesn't it do so at the top of the screen?
G

**Comment by qqqbbb** [comment]
I mean notification on the right side of the screen, so you don't miss it when it starts.

**Comment by LoneGazebo** [comment]
I'll have it do so when it starts (less notifications = better).
G

**Comment by qqqbbb** [comment]
I tested it with lua method SetAnarchyNumTurns(2) but there is no notification.

**Comment by LoneGazebo** [comment]
LUA isn’t going to fire it, as notifications only fire when the events happen in-game, not through the ‘set’ commands (as the ‘set’ commands only change the integer, not run the notification function).

G

**Comment by qqqbbb** [comment]
Updated compressed art for CSD:https://dl.dropboxusercontent.com/u/28753474/compressed%20art%20CSD.rar. Removed a duplicate file.
