### ISSUE TITLE
CTD during city-states turn

### ISSUE THREAD

**Issue by ashendashin** [LoneGazebo/Community-Patch-DLL#3371]
_1. Mod version (i.e Date - 4/23):_
7/18-1

_2. Mod list (if using Vox Populi only, leave blank):_
Community Events
Quick Turns
Unique City-States
Really Advanced Setup

_3. Error description:_ 
Another successful game, another CTD. A fix would be awesome, if possible.
[Logs&Minidump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1166784/Logs.Minidump.zip)
[Bismarck_0237 AD-0920.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1166791/Bismarck_0237.AD-0920.zip)

**Comment by LoneGazebo** [comment]
I'll look at it when I have the chance.

G
