### ISSUE TITLE
AllowsProductionTradeRoutesGlobal no longer working

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3372]
On the latest version (July 18th) and on the last beta, AllowsProductionTradeRoutesGlobal in the Buildings table seems to have stopped working. It no longer allows Internal Trade Routes (Production) without a Workshop. Could you take a look and see if anything's changed when you get a chance? Thank.

**Comment by LoneGazebo** [comment]
Strange, not sure why the code was deleted. I'll re-add. I'll also add one for food routes just so that everything is possible.
