### ISSUE TITLE
City connection through citadel

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3373]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I'm playing Augustus and made a Lighthouse in Rome - to the right was a citadel connecting the coast Rome is near to another coast and it should make it connected with all the others. That doesn't work, alas. A road to the northern city should suffice, but it's still a weird interaction.

[romeAugustus Caesar_0184 AD-0160.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1167536/romeAugustus.Caesar_0184.AD-0160.zip)

**Comment by LoneGazebo** [comment]
City connections can't work that way.
