### ISSUE TITLE
Light Tank and Gunship considered "Archery Units (Mounted)"

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#3375]
_Mod version (i.e Date - 4/23):_
7/18-1

_Error description:_ 
The Light Tank should probably be considered an Armour unit, while the Gunship should be a Helicopter.

---------------------------
![](https://i.imgur.com/t43pijE.png)
![](https://i.imgur.com/zJcSl7N.png)

**Comment by LoneGazebo** [comment]
They have to be 'archery,' as they're ranged (and not siege). Unticombat roles.
