### ISSUE TITLE
I could use some help with Warscore help.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3377]
http://civ-5-cbp.wikia.com/wiki/Warscore#Peace_Treaty

I know that Capitulation Stage means they get to unlock Capitulation. White Peace is basically nothing literally happens and let's just make peace. No demands allowed.

Can I have some clarifications of what's behind the meaning of those key words and where you should be able to demand cities and such?

**Comment by LoneGazebo** [comment]
Not sure what you mean, exactly. Capitulation is forced vassalage. Are you wanting hard numbers?

G

**Comment by TechpriestEnginseer** [comment]
At what part do they trade cities, at what part do they trade luxuries and so on.

**Comment by LoneGazebo** [comment]
Go to line: 6246 in the DealAI.cpp (DoAddItemsToDealForPeaceTreaty): https://github.com/LoneGazebo/Community-Patch-DLL/blob/master/CvGameCoreDLL_Expansion2/CvDealAI.cpp

It is pretty well-documented there.

**Comment by TechpriestEnginseer** [comment]
Isn't it an issue that you can't get open borders because you would need embassies with them? Which breaks because war destroys embassies?

**Comment by LoneGazebo** [comment]
Yeah, that's just vanilla code I left in for posterity.
