### ISSUE TITLE
Typos from 6-17 update

### ISSUE THREAD

**Issue by ereturn** [LoneGazebo/Community-Patch-DLL#338]
Getting the following errors in the Database.log file:
1) Invalid Reference on Policy_Flavors.FlavorType - "FLAVOR_FLAVOR_INFRASTRUCTURE" does not exist in Flavors
2) Invalid Reference on Policy_Flavors.FlavorType - "FLAVOR_FOOD" does not exist in Flavors
3) Invalid Reference on Tech_SpecialistYieldChanges.TechType - "TECH_PLASTICS" does not exist in Technologies

The first one is in \Community Balance Patch\Balance Changes\Policies\Flavors\Flavors.xml, lines 53 and 88, extra FLAVOR_ in the name.

Second one is in the same Flavors.xml file as above, I think the FLAVOR_FOOD is supposed to be FLAVOR_GROWTH, but not completely sure. (couldn't find a reference for flavor_food anywhere)

The last one is in \Community Balance Patch\Balance Changes\Specialists\GPChanges.xml, line 55, TECH_PLASTICS should be TECH_PLASTIC.

**Comment by LoneGazebo** [comment]
fixed, fixed and fixed in 6-18 version. thanks!
