### ISSUE TITLE
Theodora not able to form another religion.

### ISSUE THREAD

**Issue by Cerest** [LoneGazebo/Community-Patch-DLL#3380]
_1. Mod version: 7/18

_3. Error description: 
Theodora not able to form another religion. Can't spawn a great prophet = can't form another religion, even though the UA says I can form it at any time.

_4. Steps to reproduce (optional): See savegame.

[AutoSave_0149 BC-0365.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1176122/AutoSave_0149.BC-0365.zip)

**Comment by MoiMagnus** [comment]
I had this bug in one game. The UA works : if you manage to spawn a GP using another way, you can found a religion (and immediately buy a GP to enhance it), but the GP will not appear naturally.

**Comment by LoneGazebo** [comment]
I need a bit more detail - any other mods? 43 civs?

**Comment by Cerest** [comment]
Nah, just the normal full installation. 3 other religions have already been founded (the remaining number is 0).

I can form a religion if I spawn a Great Prophet via Hagia Sophia but the Great Prophet isn't able to be purchased through faith.

**Comment by LoneGazebo** [comment]
purchased through faith? You mean via the top panel 'x faith needed to spawn?'

**Comment by Cerest** [comment]
Yes, the top toolbar with the faith screen doesn't allow me to select great prophets. When I go into the religious interface there's no way for me to select "great prophet" after the max # of religions is founded.

**Comment by LoneGazebo** [comment]
You can't select it - it has to happen naturally. The top bar should say the amount of faith you need to found.

G

**Comment by MoiMagnus** [comment]
I confirm that in my last game with Theodora, the GP didn't naturally appear : after the last founded religion, the EUI interface was no longer saying the number of turn needed. And after founding (by another way), I had far more faith than needed, and a GP appeared the turn after (allowing me to enhance the religion)

**Comment by Cerest** [comment]
No, the top bar doesn't say anything. After the max number of religions is found I could have 9999 faith but a Great Prophet will not spawn through faith. Are you seeing something else in the save game I provided?

**Comment by LoneGazebo** [comment]
I tested - you can still found at the normal amount, it just doesn't say so. I added a UI thing to prevent that.
