### ISSUE TITLE
More Luxuries Compatibility File not Installing

### ISSUE THREAD

**Issue by gabeorlanski** [LoneGazebo/Community-Patch-DLL#3381]
_1. Mod version (i.e Date - 4/23):_
.88

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
After using the VP installer, the #5 File is missing. It is the file for More Luxuries Compatibility 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
http://prntscr.com/g0r51u

**Comment by LoneGazebo** [comment]
install it manually from the manual installation folder directory folder: https://mega.nz/#F!fcsEhALY!XpWbkVod5utm-S1s-7TUhQ

**Comment by gabeorlanski** [comment]
It still isn't working. It does not show up in game :(

**Comment by LoneGazebo** [comment]
With the mods menu open in-game, drag it into, and out of, your MODS folder.

**Comment by MoiMagnus** [comment]
if it does not work, try deleting your MODS folder and the cache folder, and then reinstalling VP.

**Comment by gabeorlanski** [comment]
Ok, that worked @LoneGazebo

**Comment by gabeorlanski** [comment]
The only issue now is that it does not let me have a monopoly on the more luxuries luxuries
