### ISSUE TITLE
Auto-explore units can end their turn on occupied tiles.

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#3383]
_1. Mod version (i.e Date - 4/23):_ 7/18, 43 civs, EUI
_2. Mod list (if using Vox Populi only, leave blank):_
_3. Error description:_ My (roman) pathfinder on autoexplore ended its movement on a tile containing a french pathfinder.
_4. Steps to reproduce (optional):_ Load the save "Bug sup (before)" and clic on next turn, or load the save "Bug sup (after)". You should have two pathfinder on the same tile.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs_supperposition.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1180809/Logs_supperposition.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Save_supperposition.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1180811/Save_supperposition.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
can't load the save (again), can't reproduce it either

@g: care to take a look?
