### ISSUE TITLE
[43 civs, 20 cs] Huge maps have 24 cs by default

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#3384]
_1. Mod version (i.e Date - 4/23):_ 7/28, 43 civs, EUI
_2. Mod list (if using Vox Populi only, leave blank):_
_3. Error description:_ When selecting a huge map, the default number of CS is 24. You are then able to launch a game with 43 civs and 24 cs. Sometime, this game is an auto-loose (no units, and probably failure to generate correctly the map, so militaritic defeat), but not always. The problem is only the default value, since if you change the number of CS, you cannot go back to 24.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
That's a vanilla issue. Adjust the cs cap manually.
