### ISSUE TITLE
Religion Bug : 8 religion founded when max is 6.

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#3385]
_1. Mod version (i.e Date - 4/23):_ 7/28, 43 civ, EUI
_2. Mod list (if using Vox Populi only, leave blank):_
_3. Error description:_ Having 7 religion when max is 6 is normal when you play Theodora. Having 8 religion is a bug.
_4. Steps to reproduce (optional):_ 
1) Load the save "bug religion (before 6th)". There is one religion reamining to be founded. I am Theodora, so nobody else is theodora.
2) Clic on next turn, or load the save "bug religion (after 6th)". One more religion has be founded, but strangely, there is still 1 remaining religion to be founded.
3) Clic on next turn, or load the save "bug religion (after 7th)". One more religion has be founded, and no religion can be founded.
4) I've continued this game until founding my religion. No problem on that point, I can still found the 8th religion.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs_religion.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1183332/Logs_religion.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Save_religion.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1183334/Save_religion.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I see why...I'll hotfix.
