### ISSUE TITLE
Some Resource Icons disappear

### ISSUE THREAD

**Issue by TalasNetrag** [LoneGazebo/Community-Patch-DLL#3386]
_1. Mod version (i.e Date - 4/23):_
July 27th (2.7.27)​ (and the 7/18 has the same issue)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Some Resource icons disappear on a turn basis.
They also can reappear on a turn basis or sometimes when you move the camera.
The 5-26 version doesnt have this issue.
http://fs5.directupload.net/images/170729/gjllhho8.jpg
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
known issue and reproducable also, but i don't have a clue how to fix it.
