### ISSUE TITLE
Libery Opening Bonus stops working in game at some point

### ISSUE THREAD

**Issue by Stef012** [LoneGazebo/Community-Patch-DLL#3387]
_1. Mod version (i.e Date - 4/23):_

CP 7-18-1
[Liberty Opener.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1185070/Liberty.Opener.zip)

_2. Mod list (if using Vox Populi only, leave blank):_

RtP
CulDiv
EE
HR Complete
PeC

_3. Error description:_ 

Not sure of the exact trigger or which turn in the game it occurred but I noticed that at some point the Liberty Opener bonus (+1 culture per city) had stopped working. Worked at first, but then culture per turn dropped and it's no longer showing in city view either.

Think might have been around finishing Liberty policy tree or when opening a new social policy tree (Piety in this case)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stef012** [comment]
![image](https://user-images.githubusercontent.com/20503631/28746249-d9fee89e-7488-11e7-96db-93167b6fcef4.png)

**Comment by TechpriestEnginseer** [comment]
I can't recall Liberty's Opener ever giving +1 Culture to Cities.

**Comment by Stef012** [comment]
Yes indeed, only CP. Let me know if you need more info, will try another game to pinpoint more closely when this exactly occurs.
