### ISSUE TITLE
Encampement icon

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#339]
There is no encampement icon in strategy view. I don't know what's with other Unique Improvements but this makes it even more difficult to place enc. properly.

**Comment by qqqbbb** [comment]
fix: https://dl.dropboxusercontent.com/u/28753474/Tipi%20icon%20fix.rar
Fixed another thing: copies of the same file were used for strategic view and pedia, I edited IconsEncampment.xml so now 1 file is used. These can be deleted now: EncampmentAtlas256.dds, EkiAtlas256.dds, eki_hb_diff.dds.
