### ISSUE TITLE
CTD on Austria's turn [Turn 343]

### ISSUE THREAD

**Issue by IllusVirus** [LoneGazebo/Community-Patch-DLL#3392]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_
- Calypso's Colored Religious Icons, all 3 [basic, extended, BNW extended]
-Civ Name's by Policies
-Flag Promotions
-Info Addict
-Quick Turns

_3. Error description:_ 
CTD specifically on Austria's turn

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1192432/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Japan.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1192440/Japan.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1192428/CvMiniDump.zip)

4. Screenshots (optional):

5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

**Comment by LoneGazebo** [comment]
Probably flag promotions. Buggy.
