### ISSUE TITLE
top panel problem 

### ISSUE THREAD

**Issue by assassin332** [LoneGazebo/Community-Patch-DLL#3393]
Mod version (July 27th - (2.7.27)​ )
Mod list "  Vox Populi only "

Error description .. 
i install the mod correctly and there is a bug in my top panel .. and i install the mod on another pc and working fine 

this is the normal top panel for everyone 

![8930_screenshots_2015-04-28_00001](https://user-images.githubusercontent.com/30018151/28853834-7b5d4ba2-7733-11e7-9db5-bed8715b443c.jpg)

and this is my top panel !

![civ5screen0000](https://user-images.githubusercontent.com/30018151/28854736-359a6c7a-7739-11e7-8650-c700de23faa0.jpg)

**Comment by LoneGazebo** [comment]
C4DF wasn't loaded properly.

**Comment by assassin332** [comment]
and what the solution for that ?

**Comment by LoneGazebo** [comment]
Reinstall the mod, make sure you have no conflicting mods from the workshop.
