### ISSUE TITLE
Game Text Not Properly Loading into Game

### ISSUE THREAD

**Issue by myxanders** [LoneGazebo/Community-Patch-DLL#3394]
_1. Mod version:_
7-27

_2. Mod list :_
Only Vox Populi (including (6a) Community Balance Overhaul - Compatibility Files (EUI))

_3. Error description:_ 
It seems all the Game Text is not loading properly. For example, hovering over items shows "TXT_KEY..." instead of the item name. Same goes for help and some Civilopedia entries. The UA for each Civilization works as designed, I tested India and Iroquois, but their UA descriptions are from the Standard game.

_EDIT:_ It appears the Policy Trees are the standard trees as well, instead of the VP policies. (Wish I thought of grabbing a better/more informative shot. But I believe the errors too can be found in the Database log)
![20170801225537_1](https://user-images.githubusercontent.com/16855999/28857981-022b6400-7713-11e7-9f65-b5ee73625b3f.jpg)

_4. Steps to reproduce (optional):_
I cleared my cache and then downloaded the mod and autoinstalled it. I loaded up Civ 5 and enabled only the VP mods. Head into the game and on the DoM screen and an error pops up saying "Unable to load texture [civilopediatopbuttonscorporations.dds]". Then the rest of the errors become apparent.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

_Log files:_
[TextErrorLogs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1192587/TextErrorLogs.zip)

Contains Database, LUA, and stopwatch files

_Screenshots:_

![Example 1](https://user-images.githubusercontent.com/16855999/28856570-920ece90-7709-11e7-8ed8-d321d713b764.PNG)

![Example 2](https://user-images.githubusercontent.com/16855999/28856575-96fbd52e-7709-11e7-877f-93efa37793ee.jpg)

![Example 3](https://user-images.githubusercontent.com/16855999/28856576-99170e96-7709-11e7-8ac2-fab040256ad8.jpg)

**Comment by LoneGazebo** [comment]
Means that EUI wasn't installed in the right spot. Follow the manual install instructions.

**Comment by myxanders** [comment]
These are the manual install instructions I see, and I've followed all of them:

_Download all desired mods, placing them in your MODS folder._
That's where they are.

_If using the CBO, delete the LUA folder in the main Community Patch mod folder._
LUA folder gone.

_If using a CBO Compatibility Mod, choose one or the other, but not both, based on your use of EUI._
Chose 6a, for use with EUI

_If using one of the CBO Compatibility Mods, delete the LUA folder in the Community Balance Overhaul and Community Patch mod folders._
LUA folder gone from CBO and CP folders

_Make sure to delete all files in your cache (Documents/My Games/Sid Meier's Civilization 5/Cache) before starting a new game._
Deleted.


The UI_bc_1 folder is found in the DLC folder. I'm not sure what it is I'm not understanding.

**Comment by LoneGazebo** [comment]
Make sure there are no conflicting mods in your MODS folder, that there are no other modpacks in your DLC folder, and that you are clicking 'next' and starting a game from the mods menu.

**Comment by myxanders** [comment]
Deleted the files and reinstalled via the Auto-Installer and it works now. Didn't remove any other mods so not 100% what was fixed but thanks for the help.
