### ISSUE TITLE
RequiredEventChoiceType and RequiredCityEventChoiceType Request

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3395]
Just a column addition that prohibits buildings from being built without an active event choice.

**Comment by LoneGazebo** [comment]
Done.

**Comment by TechpriestEnginseer** [comment]
Doesn't exist.

**Comment by LoneGazebo** [comment]
That's strange, I added it.

**Comment by LoneGazebo** [comment]
Oh, I'm crazy. Here's the building values:
EventChoiceRequiredActive
CityEventChoiceRequiredActive

I just forgot to add them in the CP. You can add them if you want (for testing):


ALTER TABLE Buildings ADD COLUMN 'EventChoiceRequiredActive' TEXT DEFAULT NULL;
ALTER TABLE Buildings ADD COLUMN 'CityEventChoiceRequiredActive' TEXT DEFAULT NULL;

in the CoreTableEntries.sql file.
