### ISSUE TITLE
 Sudden loss of delegates 

### ISSUE THREAD

**Issue by Skidizzle** [LoneGazebo/Community-Patch-DLL#3396]
July 18th (7/18)
Vox Populi EUI 43
+
Capture Great People v2
FlagPromotions v7
Global local generals v2
InfoAddict v22
More Great Works v3
Unit Path Viewer v10

------

Sudden loss of 5 delegates out of 16.
2 from membership,
1 from hosting,
5 from city-state allies,
3 from embassies,
1 from religious authority,
1 from consulates policy,
3 from following world religion.

_4. Steps to reproduce (optional):_
at beginning of turn I selected 5 votes then exited to check something, came back to the assign delegates window and they were gone.

**Comment by LoneGazebo** [comment]
If you assign votes and exit the screen, it casts the votes.

**Comment by Skidizzle** [comment]
There's nothing in the interface to indicate that, nor a warning window pop up if you go to exit

**Comment by LoneGazebo** [comment]
That's a vanilla thing, can't really do anything about it.

**Comment by Skidizzle** [comment]
I played through and came to the next world congress. Opened the window for the first time and am still missing 5 votes, this time out of 18.
