### ISSUE TITLE
ColdWar WC propose dont work after save reload

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3397]
_1. Mod version (i.e Date - 4/23):_
27 July(but I see this during last 3-4 months)

_2. Mod list (if using Vox Populi only, leave blank):_
WorldCongressReinform

_3. Error description:_ 
Possibly to send trade routes to civs with different ideology, after savegame reload.

_4. Steps to reproduce (optional):_
I don't know, maybe problem is in WorldCongressReinform. If no one knows, then tomorrow I will try to reproduce such behaviour without it.
Today I just reload my savegame, and see(some turns later) that i have trade routes to me from other civs with different ideologies. And ColdWar propose is still active. After that I remembered! I saw such behaviour a couple of months ago, but forgot to post here.

**Comment by TechpriestEnginseer** [comment]
Trade Routes that existed prior to the Cold War don't disappear.

**Comment by bigcat88** [comment]
They disappear. Cause after ColdWar was passed, all my trade routes stops.
The problem that after reload(when CW already present) - Cold War just present in active resolutions(so yeah, I see that we are in Cold War), but has no effect.
