### ISSUE TITLE
Logistics promotions giving multiple alternate penalties 

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#3398]
_Mod version (i.e Date - 4/23):_
7/27

_Error description:_ 
Units with the Logistics promotion receive different penalties instead of the listed -20%. Chu-Ko-Nu's and Hwach'a's recieve -30% along with ranged naval units, while land ranged, siege, and mounted ranged units receive -15%. Aircraft receive no penalty from Logistics.

**Comment by LoneGazebo** [comment]
The -15 doesn't make sense, doesn't even appear. What you're probably seeing is the aggregate for the unit after taking a promotion to get there. (i.e. 45-30 = 15).

**Comment by LoneGazebo** [comment]
Air units don't receive a penalty, this is correct.
