### ISSUE TITLE
WC projects hammers problem

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3399]
_1. Mod version (i.e Date - 4/23):_
27 july

_2. Mod list (if using Vox Populi only, leave blank):_
WorldCongressReinform

_3. Error description:_ 
Problem in mid game:
AI has one more turn to finish WC project, than player. I very often see such situations when work on Tr. Fleet project, after first work turn we got 40-50% of project(together me + 9 AI), and on second turn I see that my donate was not added, and project run away from me. So it is impossible to win WC project in equal conditions with hammers. Even when player has more hammers it doesn't helps if project will be completed in 2 donates. Last donate from human will not be added.
I can post savegame for this from my next game(cause I see this all my last 2 games, and pretty sure then on next game will see this again)

Problem in late late game:
Player has no turn to work on WC project.(this situation I see first time)
Project was completed in one turn and my donate was not added(England)
![20170804211422_1](https://user-images.githubusercontent.com/13381981/28981556-e184e790-795a-11e7-9054-54e139f1ced3.jpg)

**Comment by LoneGazebo** [comment]
This is a vanilla bug, yeah. I think I have an idea...
