### ISSUE TITLE
Featurequest-Option to stop automated workers from building roads and railroads.

### ISSUE THREAD

**Issue by preyator** [LoneGazebo/Community-Patch-DLL#3405]

**Comment by supermerill** [comment]
you can add


print("IA_remove_roads");
-- remove road building for ai.
function DoNotBuildRoadYourself(iPlayerOwner, iUnitID, mission)
	if(mission == 58) then -- MISSION_ROUTE_TO
		local unit = Players[ iPlayerOwner ]:GetUnitByID( iUnitID );
		if(unit:IsCombatUnit() == false) then
			return false;
		end
	end
	return true;
end

GameEvents.CanStartMission.Add(DoNotBuildRoadYourself);

to an InGameUIAddin lua script.
