### ISSUE TITLE
Featurequest-Diplo screen shows which city states already have an embassy.

### ISSUE THREAD

**Issue by preyator** [LoneGazebo/Community-Patch-DLL#3406]

**Comment by TechpriestEnginseer** [comment]
If the UI can support it, you could just add it as a pseudo-quest where they can hover over the embassy icon and see who owns it.

**Comment by TechpriestEnginseer** [comment]
I think I got this solved already. Pulling a request now.

**Comment by TechpriestEnginseer** [comment]
I actually got a simple proposal for this. It may not be as what people expected, but it'll do considering optimal performance. Requesting a pull from it right now.

**Comment by LoneGazebo** [comment]
Happy to look at it.

**Comment by thecrafybee** [comment]
If you are able to make an icon for showing if there is an Embassy can you also add one for Feitorias too?  Just played a game with Portugal and sometimes found that it was difficult to see which CS had one.

**Comment by LoneGazebo** [comment]
It's a lot of work for limited gain, tbh - you can see where they are from your trade screen. Besides, scanning the map is half the fun! :)
