### ISSUE TITLE
Wall-less coastal cities

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3408]
_1. Mod version (i.e Date - 4/23):_ latest

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I raised this issue a while ago but devs decided it was ok and 'works as intended'
I'd like to make another attempt at showing why it's not ok.
I strongly believe AI should prioritize fortifying its coastal cities with walls and castles. In my example Ethiopia denounces me and next turn I DOW them. I easily take their coastal cities, it only takes ~2 hits of my caravel. I strongly believe one of the first things to do for AI is to fortify its coastal cities ASAP. This is the way any average human player does because we all know how quickly and easily one can lose unfortified coastal cities due to a sudden naval attack.

![20170806225756_1](https://user-images.githubusercontent.com/16341598/29006592-9ef4da96-7afb-11e7-800e-9d7d8bd3b2ca.jpg)

**Comment by LoneGazebo** [comment]
The AI knows to do so, but it lumps that into a list of priorities.

G
