### ISSUE TITLE
Game Not Recognizing Lighthouse for City Connection to Capital

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#3409]
_1. Mod version (i.e Date - 4/23):_
7/27

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Game not recognizing Lighthouse for creating city connection to capital.

_4. Steps to reproduce (optional):_
In the included screenshot and save file, Raiatea and Nuku Hiva are being disconnected from capital despite all three cities having Lighthouses built. Prior to the road existing between it and the capital, Tonga DID count as being connected via Lighthouse. ALSO, this has been the case since before Kanesh was settled or Assyria declared war on me. I just didn't have an early enough save file to show this bug prior those those in-game events. Also worth mentioning, I was able to build the Great Lighthouse wonder, so the Lighthouse in Honolulu was included for free as part of that.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Kamehameha Save Files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1203666/Kamehameha.Save.Files.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![8930_20170806203524_1](https://user-images.githubusercontent.com/19951628/29009260-5f13e9da-7ae7-11e7-800c-f5230240329d.png)

**Comment by cdanger341** [comment]
Also worth mentioning for the attached save file: Germany voluntarily became the vassal of the Netherlands a couple of turns after the Netherlands hit Medieval Era despite these Civs being allies again Assyria and Korea all game long. Is it normal behavior for Civs to voluntarily become vassals? I have seen this sort of behavior in other games this version and the previous, whereas I have never seen voluntary vassalship in any previous versions of the mod.

**Comment by LoneGazebo** [comment]
Best guess is that there's a barb or something on a FOW tile up there.

**Comment by cdanger341** [comment]
I thought that, as a barb camp did continue to spawn west of Ragusa ever now and then. I used to leave a couple of units up there to deal with the barbs, but had to move them due to the war with Assyria. But even when the area was clear of barbs the game still never "counted" there as being an ocean connection between Honolulu and the NW cities. I even bought the ocean tiles between Honolulu and Carchemish to ensure I'd have a "path" out of that narrow straight. In fact, I'm pretty sure that action is directly what led to Assyria DoWing me.
