### ISSUE TITLE
Creating a DLC modpack with Vox Populi 7-27

### ISSUE THREAD

**Issue by jwfoo555** [LoneGazebo/Community-Patch-DLL#3410]
_1. Mod version (i.e Date - 4/23):_

Vox Populi 7-27

_2. Mod list (if using Vox Populi only, leave blank):_

(1) Community Patch
(2) Community Balance Overhaul
(3) CSD for CBP
(4) Civ IV Diplomatic Features
(5) More Luxuries
(6a) Community Balance Overhaul - Compatibility Files (EUI)
Celtic City Names (v 2)
CIV-Linked Great Generals (v 11)
Culturally Linked Start Locations (v 4)
Faster Aircraft Animations (v 3)
Gibraltar, Reef, and Krakatoa Fixes (v 101)
Historical Religions Complete (BNW or GK) (v 45)
InfoAddict (v 22)
Lake Victoria Fix (v 2)
Less Warmonger Hate (v 10)
Mechanized Infantry with Soldiers, Resized (v 2)
More Great Works (v 3)
Quick Turns (v 10)
Quiet Diplomacy (v 7)
R.E.D. - Just Ethnic Diversity (v 27)
R.E.D. Modpack (v 27)
Show Move-To (v 2)
Unique Cultural Influence (v 4)

Multiplayer Mods Workaround (v 1)

_3. Error description:_ 

When trying to create a DLC modpack with this combination of mods as per https://forums.civfanatics.com/threads/mpmpm-multiplayer-mod-dlc-hack-updated.533238/, upon starting a game, a blank Corporations and Monopolies window appears, and is uncloseable. Proceeding to create a modpack only creates one that also opens up the Corporations window on startup. This combination of mods works fine without Multiplayer Mods Workaround (v 1) enabled.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1204787/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![cbp modpack](https://user-images.githubusercontent.com/30799209/29026848-35894a4e-7bc1-11e7-8ecd-45cd12dc9e82.png)

**Comment by ashendashin** [comment]
Oh so you had the problem after starting with just the modpack. Did you put the dll in the community patch folder?

**Comment by LoneGazebo** [comment]
Can't help with this, sorry. Ask on the forums (I didn't create the modpack maker).
