### ISSUE TITLE
Ships may teleport into landlocked lakes after Peace Treaty

### ISSUE THREAD

**Issue by cammcken** [LoneGazebo/Community-Patch-DLL#3413]
_1. Mod version (i.e Date - 4/23):_
7/20/17

_2. Mod list (if using Vox Populi only, leave blank):_
In addition to VP,
-Flag Promotions
-Global Commander Influence Borders
-Improved City View with EUI
-Unique City States
-Unit Path Viewer
This is the modpack kindly provided by ElliotS on civfanatics: https://forums.civfanatics.com/threads/7-19-17-innovative-tamaranian-modpack.620131/

_3. Error description:_ 
No error, perhaps, but an annoying outcome of a working feature. After signing a peace treaty, all units in enemy territory are teleported out, to the nearest possible tiles. This sometimes results in ships being teleported into landlocked lakes.
Comment: Please don't solve this by preventing naval travel through lakes. I would rather keep those canal possibilities open.

_4. Steps to reproduce (optional):_
Northeast corner of the world map, between Nanjing and Guangzhou, is the teleported ship

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
I don't believe these are necessary.

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Oda Nobunaga_0545 AD-1947-July.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1206671/Oda.Nobunaga_0545.AD-1947-July.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
No crash

4. Screenshots (optional):
![20170807112051_1](https://user-images.githubusercontent.com/26178723/29052718-d7fcb0d4-7bb9-11e7-864a-9475e9b853ed.jpg)

**Comment by LoneGazebo** [comment]
There's no solution to this if lakes are navigable.

**Comment by cammcken** [comment]
That's fine. I'll use IGE to solve these rare instances.
