### ISSUE TITLE
civipedia description

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3414]
_1. Mod version (i.e Date - 4/23):_latest

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Civipedia for Temple says "city must contain a Shrine (or a Pyramid) before a Temple can be constructed"

**Comment by saamohod** [comment]
Not sure if LoneGazebo got me right. I was wondering what kind of "Pyramid" was meant. Must be a typo from vanilla version.

**Comment by LoneGazebo** [comment]
Oh, it is the old Mayan UB.
