### ISSUE TITLE
"Enable Event System"

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3415]
What does this really do?

I had a lot of users reporting that my mods that are reliant on dummy events that some of their bonuses are permanent in cases where they shouldn't and almost all of them have reported that they disabled the Event System.

How can this be? If Enable Event System is not checked, dummy events shouldn't be applied via Lua then.

**Comment by LoneGazebo** [comment]
Enable/disable events prevents the function that assigns/triggers/decrements/cancels events at the player and city levels from firing. So the LUA will still work (as those functions can still be accessed), but all automation is gone.

**Comment by TechpriestEnginseer** [comment]
Is there anyway for the automation for canceling out events still work?

**Comment by LoneGazebo** [comment]
You can, yes.
