### ISSUE TITLE
Statecraft policies unchanged 

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#3416]
_Mod version (i.e Date - 4/23):_
8-7-2 no-EUI

_Error description:_ 
While the Fealty and Artistry branches were changed, Statecraft's remained the same (at least in terms of description).

Edit: 
EUI version is correct, and on the non-EUI version the effects are correct, but the descriptions were not updated. 

---------------------------
Supporting information:
![](https://i.imgur.com/LB5LdZ7.png)

**Comment by LoneGazebo** [comment]
Should already be fixed.
