### ISSUE TITLE
Some issues with Statecraft (EUI Version)

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#3417]
_1. Mod version (i.e Date - 4/23):_

8/7-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

There're problems with some policies:

- Foreign Service Earn Great Diplomats 25% faster instead 50%

- Trade Confederacy - +25% Yields for Trade Routes originating from your Capital or a Holy City. Only for internals trade routes, right?

- Exchange Markets - +1 Happiness for every active Trade Route isn't being applied

And a question about Opener - City-States Quest Rewards increased by +50%. This percent is already applied to the number showed as reward for the quest being this the final total (and so don't modifying already existing quests before selecting the policy) or is increasing the showed number in that percent after finish the quest?
According to my observation is the former, but better ask to confirm that it's working as intended, thanks.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
re: Trade Confederacy - no, all of them.

**Comment by Mitchsp** [comment]
I've tried 8-7-3 in a saved game and in a new using IGE and theses issues still persist (only VP without any other mod):

Foreign Service - Earn Great Diplomats 25% faster instead 50%

Trade Confederacy - Not giving bonus to any trade routes (external or internal, tested in a new game).

And can you please explain me how Opener would work so I can try to test properly? Thanks!

**Comment by LoneGazebo** [comment]
That's strange, both are working on my end. I'll check.
The rewards thing works when you get the quest- those values include your bonus for completion. It does not affect existing quests, though, just FYI.

**Comment by LoneGazebo** [comment]
Ugh, apparently my merge to master from beta missed three changes (no blame but myself) in the CBO and Compat files. I'll reupload, thanks for checking in.

**Comment by Mitchsp** [comment]
Don't see where reopen an issue, so I'll post here and if you dont' see this will open a New Issue later.
I've tested 8-7-4 and unfortunately G still there's a bug to squish!

Foreign Service - Earn Great Diplomats 25% faster instead 50%

Tried again in saved & new game.

**Comment by LoneGazebo** [comment]
Well hellfire.

**Comment by Mitchsp** [comment]
If it serves you to find where's the problem quicker, I'm trying to change Patronage.sql adding this:

-- Philanthropy
UPDATE Policies
SET GreatDiplomatRateModifier = '50'
WHERE Type = 'POLICY_PHILANTHROPY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

and is working for other GreatPersons, but not for Great Diplomats.

**Comment by LoneGazebo** [comment]
My merger is being dumb. Reupload all the files. Will still be 8-7-4.

**Comment by Mitchsp** [comment]
Glad to say it's working now fine, thanks!

**Comment by LoneGazebo** [comment]
Great!
