### ISSUE TITLE
Policy Names in Fealty

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#3419]
Just a aesthetic comment. The names for Divine Right and Nobility reflect one anothers' effects. Could you change them over w/ icons?

**Comment by LoneGazebo** [comment]
How now?

**Comment by Hokath** [comment]
Currently Divine Right boosts castles and armouries and so on, while Nobility makes you benefit from excess happiness. Seems to me like the Nobility are the ones who should be dealing with the castles, and the Divine Right pertains to the happiness of ones peasants.
