### ISSUE TITLE
Governor doesn't let me get more than 20 citizens 

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#342]
Even after I unblock it, governor still blocks afterwards.
![8930_2015-06-20_00006](https://cloud.githubusercontent.com/assets/1131228/8265961/cb709dc0-172b-11e5-920f-33b7e0b7efe3.png)
![8930_2015-06-20_00007](https://cloud.githubusercontent.com/assets/1131228/8265962/db2d5208-172b-11e5-9864-2e8af95b16e5.png)

**Comment by Radost** [comment]
Now I have another city and it is also locked to 20 citizens.

**Comment by LoneGazebo** [comment]
Yeah, it is because you are super unhappy (it was for the AI, but I forgot to set the AI-only parameter). I'll fix in next version.
