### ISSUE TITLE
Can't produce trade units

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#3420]
_1. Mod version (i.e Date - 4/23):_
8/7 - 3

_2. Mod list (if using Vox Populi only, leave blank):_
FlagPromotions

_3. Error description:_ 
Trade units don't show on city production window.

_4. Steps to reproduce (optional):_
Playing as Carthage, I started the game with 8/7 - 1, didn't get any trading technology, focused on Currency. Then installed 8/7 - 3. Now I have markets and 1 availabe trade route, and the trading window shows several available routes. My cities, however, cannot produce them, they don't show up.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by tu-79** [comment]
Started a new game with Inca, trade units can be purchased as usual, but my old game is lost :(

**Comment by LoneGazebo** [comment]
Sounds like a bad install or something.
