### ISSUE TITLE
Crash to desktop on AI turn

### ISSUE THREAD

**Issue by Mcantona** [LoneGazebo/Community-Patch-DLL#3421]
_1. Mod version:_8-7-3

_2. Mod list (if using Vox Populi only, leave blank):_
MC's Tunis
MC's Tunis Compatibility
MC and LITE's Nubia
MC and LITE's Nubia CBO Compatibility
Canton Pirates- Ching Shih
Canton Pirates CBO Compatibility
[BNW] Vietnam Civilization - Colonialist Legacies
[BNW] Colonialist Legacies Vietnam CBO Compatibility
Community Events
Unique City-States

_3. Error description:_ 
Crash to desktop on AI-turn (Canton Pirates).

_4. Steps to reproduce (optional):_
Tried to load an earlier autosave - the CTD always happens on the same AI turn

---------------------------

3.
[CTD-090817.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1212517/CTD-090817.zip)

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
guessing it is canton, someone else mentioned that as being buggy.

**Comment by TechpriestEnginseer** [comment]
Yeah I'm having extreme difficulties in figuring out why the Cantons are buggy. I'll have to do a deep analysis why and compare the civ to all other civs.

**Comment by Mcantona** [comment]
heres all the log files. I enabled logging in the config.ini this time.

Let me know if you need some more infos/files.
[ctd_100817.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1214810/ctd_100817.zip)

**Comment by Iamblichos** [comment]
Just briefly looking at this, I think this is crapping out on the Red Junk ship which has a very unnecessary complex algorithm to detect when it is next to another Red Junk ship (with the same promotion).

Question: at what turn are you getting CTD's? Is it before or right about around the Canton player has researched Privateers?

**Comment by Mcantona** [comment]
its on turn 102, thats too early for the red junk ship i guess

**Comment by Iamblichos** [comment]
Not really. What's the game speed?

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer what's the code for this ship? If you send me the general idea I could throw it into the DLL, save us all the headache.

**Comment by Mcantona** [comment]
standard

**Comment by TechpriestEnginseer** [comment]
There's no code for it.

**Comment by Iamblichos** [comment]
Changing its default Unit AI wouldn't cause a crash per se. It may not be due to this mod at all then.

**Comment by Mcantona** [comment]
i started a new game without the Pirate-Mod and it works just fine. Im on turn 190 now and there has been no problems at all so far...so I think it was indeed the Pirate-Mod that caused the crashes

**Comment by TechpriestEnginseer** [comment]
Would
````
	<Unit_AITypes>
		<Row>
			<UnitType>UNIT_RED_FLEET_JUNK</UnitType>
			<UnitAIType>UNITAI_ATTACK_SEA</UnitAIType>
		</Row>
		<Row>
			<UnitType>UNIT_RED_FLEET_JUNK</UnitType>
			<UnitAIType>UNITAI_RESERVE_SEA</UnitAIType>
		</Row>
		<Row>
			<UnitType>UNIT_RED_FLEET_JUNK</UnitType>
			<UnitAIType>UNITAI_ESCORT_SEA</UnitAIType>
		</Row>
		<Row>
			<UnitType>UNIT_RED_FLEET_JUNK</UnitType>
			<UnitAIType>UNITAI_EXPLORE_SEA</UnitAIType>
		</Row>
		<Row>
			<UnitType>UNIT_RED_FLEET_JUNK</UnitType>
			<UnitAIType>UNITAI_PIRATE_SEA</UnitAIType>
		</Row>
	</Unit_AITypes>
````
This conflict?

**Comment by LoneGazebo** [comment]
That XML makes my eyes hurt. 90% of that can be removed - if it uses a default value, you don't need to explicitly redefine it in XML.

Also, don't use the UNITAI_PIRATE_SEA. Doesn't do anything.

**Comment by TechpriestEnginseer** [comment]
@Mcantona 
Whether you have the time, try the new compatibility test in a tiny or larger match(with the canton in the game ofc)
[Canton Pirates CBO Compatibility (v 2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1219937/Canton.Pirates.CBO.Compatibility.v.2.zip)

Fast forward it as quick as you can into the medieval era where they unlock the Red Fleet Junks. You don't even need to play the game properly and report any CTDs here.

**Comment by Mcantona** [comment]
I will test it.. im off to my more or less well deserved holiday today though, so it's gonna take a while (back on the 23.)

**Comment by TechpriestEnginseer** [comment]
Any news @Mcantona

**Comment by Mcantona** [comment]
i just tried it...unfortunately i still get a CTD during Cantons turn. I tried a quick game and now it happens on turn 92 = 620  AD

**Comment by TechpriestEnginseer** [comment]
@Mcantona is it possible for you to just play the Canton Pirates without the compatibility? I'm super confused now.

**Comment by Mcantona** [comment]
i tried a game without any of the compatibility mods now: 
it worked just fine, i was able to build the gambling house as well as the red fleet junk without any crashes. 
So there might still be any problem with the compatibility mod i guess. Or the AI does anything weird when playing as Canton?? In order to safe some time i played quite passive, but i did try to attack with the red fleet junk and that didnt cause a crash either.

**Comment by TechpriestEnginseer** [comment]
It must be when I made one of the Lua obsolete then... there's an obscure lua reference somewhere then. Thanks for your help!

**Comment by Mcantona** [comment]
You are welcome! Just let me know if you need some more testing.
