### ISSUE TITLE
UI gets funky

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3424]
_1. Mod version (i.e Date - 4/23):_
Yields sometimes disappear from tiles, when conquering cities sometimes the annexation thing only appears after time... Something's suspicious with the previous-to-latest  version (just noticed -4 version is released today)? I don't know if it fixes that.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_

**Comment by LoneGazebo** [comment]
yields disappearing is something @ilteroi has been struggling with. Probably not a solution to it. Ending the turn solves it, though.

Don't have any problems with the annexation thing, though. Lua log from a game where it happens?

G

**Comment by Enrico-Swagolo** [comment]
I've got something better than a lua log, it's something I've reproduced on a save. Even after current hotfix, the weirdness is still in.
[busanmIsabella_0254 AD-1090.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1214790/busanmIsabella_0254.AD-1090.zip)

Ask Sejong for Busan in a peace treaty, weird stuff happens after. Annex/puppet/raze pannel appears to disappear half a second later, then text is below but it shows the map as if Sejong's leader screen didn't load, then annex/puppet/raze reappears.

**Comment by Enrico-Swagolo** [comment]
You only wanted lua log? Here it comes
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1218626/Lua.zip)

**Comment by LoneGazebo** [comment]
The lua log looks fine. Are you using luajit, perchance?

**Comment by Enrico-Swagolo** [comment]
Nope, never heard of that. The only thing I use is the improved city view for VP  (or something like that)

**Comment by LoneGazebo** [comment]
Not sure - that UI mod _could_ be the issue but I'm not sure. I need others to corroborate the experience before I can say it is caused by VP and not an end-user bug.
