### ISSUE TITLE
Conquest things don't proc on city trade deals

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3425]
_1. Mod version (i.e Date - 4/23):_
Before latest hotfix

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm playing Spain with both Hero Worship and the UA, but Sejong giving me his Busan procs neither.

**Comment by TechpriestEnginseer** [comment]
You didn't conquer the city, you just received it.

**Comment by Enrico-Swagolo** [comment]
But I remember it proccing in one version? I don't think even Imperium (Authority) procced, though I didn't exactly check my Culture/Science number.

**Comment by LoneGazebo** [comment]
If you receive a city via a trade deal, it doesn't count as conquest. Gotta flip it with blood.

**Comment by Enrico-Swagolo** [comment]
Okay I understand, that makes sense.
