### ISSUE TITLE
Pantheon Bug

### ISSUE THREAD

**Issue by bustedbunny** [LoneGazebo/Community-Patch-DLL#3426]
_1. Mod version (i.e Date - 4/23): 8-7-4

_2. Mod list (if using Vox Populi only, leave blank): VP without EUI
Emigration (modded version for VP)
Global - Influence borders for Commander
InfoAddict
IngameEditor
QuickTurns
Unit Path Viewer

_3. Error description:_ 

Bug doesn't let me continue.
I got enough faith to found a pantheon, but it seems like all of them are already taken. That's why i can't choose it to continue.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 

[Ahmad al-Mansur_0114 BC-2360.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1215271/Ahmad.al-Mansur_0114.BC-2360.zip)
Played, using FAKE DLC modpack.

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![screenshot_5](https://user-images.githubusercontent.com/30902981/29175906-04acef8c-7df3-11e7-8426-2b6c5ca5ec85.png)

**Comment by LoneGazebo** [comment]
What are all the exclamations on the right for? Also, are you using the 43 civ version?

**Comment by bustedbunny** [comment]
Yes, it is 43 civ version.

**Comment by LoneGazebo** [comment]
Need an answer to the first question.

**Comment by bustedbunny** [comment]
That means, that pantheon already taken. I tried all of them. All of them avalible on the list, but when i pick any exclamation appear.

**Comment by LoneGazebo** [comment]
I'll look into it. For now I'd just use an autosave and IGE to get around the bug.

**Comment by bustedbunny** [comment]
Any advive how to use IGE to get around the bug? I mean, i need pantheon, so i can't just skip it.

**Comment by LoneGazebo** [comment]
This is the peril of using the 43 civ DLL (it is largely experimental, as noted on civafanatics). You'll have to do without the pantheon. Just wait until another civ founds and seeds faith to you.

G
