### ISSUE TITLE
Something in Fealty ninja-adds +1 Faith to Temples

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3427]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I've noticed that after taking either the Monastery or Castles policy, my Temples turned into +4 Faith, and that's before Grand Temple (they'll probably be 5F 1C after that). It's hardly a big problem though.

**Comment by LoneGazebo** [comment]
Ah yep, forgot that the +1 faith was a vanilla addition. Will remove.
