### ISSUE TITLE
Problem with monopolies using Statecraft: Exchange Markets

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#3428]
https://forums.civfanatics.com/threads/new-version-august-7th-8-7.620957/page-4#post-14838501

**Comment by LoneGazebo** [comment]
Elaborate on the steps you took.

**Comment by Mitchsp** [comment]
Create a new game and Reveal All with IGE.

ISSUE 1 - CREATING A MONOPOLY ONLY WITH RESOURCES OBTAINED FROM CS

Fill Statecraft tree and create GD to obtain an alliance with mercantile CS and a possible monopoly easy to check like +5 happines.

![imagen](https://user-images.githubusercontent.com/13163824/29190233-a106f8ca-7e19-11e7-8e90-af6ff7823d84.png)

![imagen](https://user-images.githubusercontent.com/13163824/29190300-dd5095fc-7e19-11e7-8c33-7ba039e2a2d3.png)

Try next turn in case

![imagen](https://user-images.githubusercontent.com/13163824/29190346-0843176c-7e1a-11e7-8c7c-3b5345d8ee9f.png)

But not monopoly notification neither bonus.

Ignore Issue 2, repating now to documenting is working after removing mods Unique City States and Community Patch Events, issue 1 still persits without them.

ISSUE 2 - CREATING A MONOPOLY WITH RESOURCES OWNED AND OTHERS OBTAINED FROM CS

Add in capital resources existing in a allied CS, in my case Coral.

![imagen](https://user-images.githubusercontent.com/13163824/29190801-baa31910-7e1b-11e7-990c-ebc04ff70f7a.png)

![imagen](https://user-images.githubusercontent.com/13163824/29190833-db85481a-7e1b-11e7-8bff-d6cb28ff5daa.png)


Give with IGE appropiate technology (fishing) and improve 3 Corals at Capital

![imagen](https://user-images.githubusercontent.com/13163824/29190925-29a2ba5a-7e1c-11e7-881c-7e2899834471.png)

**Comment by LoneGazebo** [comment]
Issue 1 is WAD- you can't get a monopoly if you do not personally own at least one tile you can't get a monopoly. Just like with great admirals.

**Comment by LoneGazebo** [comment]
Issue 2 is a mod conflict? Let enginseer know.

**Comment by Mitchsp** [comment]
Ok, he's probably reading this now here redirected from forum. Anyway Enginseer before you look this will try again mod by mod, because I had others in use that i think that are cosmetics, but just in case will try again with detail.

**Comment by TechpriestEnginseer** [comment]
I don't get the mod conflict here.

**Comment by Mitchsp** [comment]
I'm still testing, but is happening to me with both Unique City States and Community Patch Events (3/7), with only UCS is working.

![imagen](https://user-images.githubusercontent.com/13163824/29193581-42c3f666-7e26-11e7-8779-b0843b85f3b1.png)

![imagen](https://user-images.githubusercontent.com/13163824/29193595-57186804-7e26-11e7-9199-d33b861c508d.png)

![imagen](https://user-images.githubusercontent.com/13163824/29193612-6b00d572-7e26-11e7-9a11-18e5507e7381.png)

![imagen](https://user-images.githubusercontent.com/13163824/29193727-cbcaed16-7e26-11e7-83ee-fcd0ffb2f506.png)

**Comment by TechpriestEnginseer** [comment]
Looks fine to me.

**Comment by Mitchsp** [comment]
Enginseer
If you don't improve the luxury in the allied CS how can you possibly expect to get the resource from them?

------
Looks like a visual bug with IGE, because in the image you're referring Singapore's Coral is improved (can be verified with the yields showed) although the fishing boat graphics isn't showed.

I'm my tests still happens the same, when Community Patch Events is active trying with IGE  the policy isn't working to obtain the monopoly using resources owned and resources from the CS neither in a saved game or one new.

If it's working right for you I suppose is a local problem on my side, will try again a full reinstall and trying later testing in a proper game.

**Comment by saamohod** [comment]
Apologies for the off-topic.
What map script do you use? The continents look nice.

**Comment by TechpriestEnginseer** [comment]
Yeah I don't see the issue here. I can't reproduce this at all.

**Comment by Mitchsp** [comment]
After try in a new game is working right with VP alone and using UCS and Community Patch Events so yes, was a problem on my end.
