### ISSUE TITLE
Puppet governors favour specialists too much

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#343]
![8930_2015-06-20_00008](https://cloud.githubusercontent.com/assets/1131228/8266018/29fa69e4-1730-11e5-984a-797c7a5bce7d.png)
IMO puppets should fill non-merchant slots the last.

**Comment by LoneGazebo** [comment]
Fixed, at least in that I encouraged the AI to grow a bit more before specializing.
