### ISSUE TITLE
Byzantium UA Giving Access to 2 Pantheons Instead of 2 Follower Beliefs

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#3430]
_1. Mod version (i.e Date - 4/23):_
8-7-4

_2. Mod list (if using Vox Populi only, leave blank):_
None

_3. Error description:_ 
Byzantium was last to found a religion on a Huge map, and rather than picking 2 Follower Beliefs as usual, picked 2 Pantheons.

_4. Steps to reproduce (optional):_
I have only seen the AI do this. I have not tried to repro it by playing as Byzanthium.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Double Pantheon Byzanthium Save 20170810.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1216915/Double.Pantheon.Byzanthium.Save.20170810.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![8930_20170810230651_1](https://user-images.githubusercontent.com/19951628/29201289-9ac446c6-7e22-11e7-8c30-fbd6683b967e.png)

**Comment by TechpriestEnginseer** [comment]
They could always choose any belief including founder belief.

**Comment by cdanger341** [comment]
Really? I thought their UA just let them select 2 Follower Beliefs upon founding a religion. They can instead pick a second pantheon or Found Belief?

**Comment by bigcat88** [comment]
The can pick second pantheon/follower or second enchance.

**Comment by LoneGazebo** [comment]
Yep, they can get whatever they want! :)
