### ISSUE TITLE
Never ending city state turn

### ISSUE THREAD

**Issue by Marqiz22** [LoneGazebo/Community-Patch-DLL#3431]
_1. Mod version (i.e Date - 4/23):_
v. 88 (5-22-1)

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch
Community Balance Overhaul
CSD
Civ IV Diplomatic Features
More Luxuries
Enlightenment Era (with compatibility)
Civ States Evolved
Civ Names by Policies
Extra Victory Conditions
Global Warming
InfoAddict
Quick Turns
Reforestation
Events & Decisions
Useful Oil
Hex Conquer and Release

I've played with this mods several games and quite a lot of turns in overall, so I'm almost sure, it's not their fault.

_3. Error description:_ 
Playing as Venice at normal speed. At one moment, after my turn, AI turns was going as usual until City States turns. It was lasting forever. The game did not freeze or crash, it simply was endless city state turn. It was possible to float around the map and open some windows. It was possible to save/load game, and after saving-loading it, the game will start at this city state turn without problems - it will be completed. Then after around 5 turns all repeats. Started somewhere at 105 turn.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1218741/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1218744/QuickSave.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Cannot reproduce.
