### ISSUE TITLE
Can't dig

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#3433]
_1. Mod version (i.e Date - 4/23):_
8/7 - 3

_2. Mod list (if using Vox Populi only, leave blank):_

FlagPromotions
_3. Error description:_ 
Can't make the archaeologist dig.

_4. Steps to reproduce (optional):_
I've got shared open borders. Indonesia is the only one that allows me to pass.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![cant_steal](https://user-images.githubusercontent.com/7407102/29234816-fa7d0a9e-7ef9-11e7-8aa2-f604f6dbdca2.png)

**Comment by LoneGazebo** [comment]
There are some improvements you can't remove.

**Comment by TechpriestEnginseer** [comment]
mrw to build forts blocks archaeological sites.

**Comment by tu-79** [comment]
Ah, ok.
