### ISSUE TITLE
On interface only the diplomacy option appear

### ISSUE THREAD

**Issue by AnabolicRetard** [LoneGazebo/Community-Patch-DLL#3435]
_1. Mod version (i.e Date - 4/23):_
88 - beta

![civ 1](https://user-images.githubusercontent.com/31001547/29265354-11eace12-80e1-11e7-8798-8887a764cd3a.jpg)
![civ2](https://user-images.githubusercontent.com/31001547/29265355-11edb9ce-80e1-11e7-992f-55817ee9fe98.jpg)

_2. Mod list (if using Vox Populi only, leave blank):_
See screenshot 2

_3. Error description:_ 
As stated in headline, see screenshot 1

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Sounds like just a bad install. Just reinstall.

**Comment by AnabolicRetard** [comment]
It was. But thanks for the answer :)
