### ISSUE TITLE
SpecialUnit_CarrierUnitAI

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#3437]
Do you know if this code is used anywhere? I can't see that it is.

```
bool CvSpecialUnitInfo::isCarrierUnitAIType(int i) const
{
	CvAssertMsg(i < NUM_UNITAI_TYPES, "Index out of bounds");
	CvAssertMsg(i > -1, "Index out of bounds");
	return m_pbCarrierUnitAITypes ? m_pbCarrierUnitAITypes[i] : -1;
}
```

**Comment by LoneGazebo** [comment]
UNITAI_CARRIER is used for carriers, yeah.

**Comment by Iamblichos** [comment]
Well it reads into this table SpecialUnit_CarrierUnitAI. I can't see where that function call is referenced anywhere.

**Comment by LoneGazebo** [comment]
Don't think it is. I think it is leftover civ4 code.
