### ISSUE TITLE
No resources on generated maps

### ISSUE THREAD

**Issue by lorduc** [LoneGazebo/Community-Patch-DLL#3439]
_1. Mod version (i.e Date - 4/23):_
latest VP no EUI
IGE
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
on maps like continents, no resources appear. there was only one single stone on one occasion.
if I disable VP and load a map, then save the map, then load VP and use the saved map, then there are resources, however there will be no ancient runes

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by DonMatano** [comment]
I too hard the same problem. But when I unticked the  Community Balance Overhaul - Compatibility Files (EUI) mod the resources started showing
