### ISSUE TITLE
AI Stupidity

### ISSUE THREAD

**Issue by Sigral** [LoneGazebo/Community-Patch-DLL#344]
I'm not sure if this is a CPP related issue, or just AI in general (I have no mods that even touch AI besides CPP) but here we go. Even on Emperor, it seems that the AI is shooting itself in the foot. I was steamrolling ahead as Japan on TSL Earth. Without ever impeding on Chinese territory, they only built a third city after 150 turns.Three cities to my eight (I had spread along Taiwan, and other Malaysian/Pacific islands). I also popped open IGE to look at their social policies: China adopted both Tradition and Liberty, investing in one policy from the first, and two from the latter. 

When I found Persia later that same game, they still had one city. 190 turns and vast amounts of land before them, and they still had not founded another city. 

Another issue I find is that the AIs can't seem to understand what techs best benefit them. Indonesia goes over 150 turns (on Historic Eras) without ever researching Fishing, and thus dooming them to their tiny five-tile-island. Japan, England, Denmark, Indonesia: these AIs ought to beeline straight for fishing to escape their pitiful islands. I'm no modder, but is there a way to fix this? So any Civ that is trapped on a tiny island knows to go for the tech that will set them free?

**Comment by Sigral** [comment]
Worth noting that this is on the 6/17/15 version.

**Comment by Radost** [comment]
There are constant AI changes even in-between minor versions. The case with policies was fixed in the latest patch.

**Comment by LoneGazebo** [comment]
Sounds like you are using an older version and/or a mapscript that is tough on the AI. We tend to take for granted what the AI should or should not be able to do, but remember, the AI can't 'see' the map - all they get are numbers, numbers, and more numbers thrown at them.
