### ISSUE TITLE
Naval units not being affected by Medic promotions

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#3440]
_1. Mod version (i.e Date - 4/23):_
8-7-4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I've seen [this](https://forums.civfanatics.com/threads/community-patch-how-to-install.528034/page-129#post-14841574) and tested in current version to verify that it's still happening.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Naval units with medic? Or naval units adjacent to a land unit with medic? Because medic does not cross domains for the bonus.

**Comment by Mitchsp** [comment]
Naval units with medic

**Comment by LoneGazebo** [comment]
Code looks fine to me.

**Comment by Mitchsp** [comment]
Looked again in the actual turn of my current game and it worked, but I'm sure that when I tried, after reading the post and remembering I thought it happened turns ago, it didn't.

Will monitor during next turns and post here with images if I see again under special circumstances.




and the next turn

**Comment by LoneGazebo** [comment]
okay.

**Comment by Mitchsp** [comment]
Ok, now I remember, it's happening when a unit is inside a city (being the unit with Medic or adjacent to a one with), still is healing 20 HP.

Galleass with 16 HP

![imagen](https://user-images.githubusercontent.com/13163824/29338286-d27cf180-8214-11e7-8607-b07520eafa08.png)

Caravel with 23 HP

![imagen](https://user-images.githubusercontent.com/13163824/29338302-df2ae266-8214-11e7-962e-ced1778f2d77.png)

Adjacent Caravel with Medic and Medic II

![imagen](https://user-images.githubusercontent.com/13163824/29338329-f125b702-8214-11e7-9731-7a25e4bc1a70.png)

and the next turn

![imagen](https://user-images.githubusercontent.com/13163824/29338370-2b45c846-8215-11e7-8ae5-2855280fbacd.png)

Galleass inside the city healed 20 HP

![imagen](https://user-images.githubusercontent.com/13163824/29338405-58cff124-8215-11e7-8862-350e3a519777.png)

**Comment by LoneGazebo** [comment]
Here's the code:

`
```
//	--------------------------------------------------------------------------------
int CvUnit::healRate(const CvPlot* pPlot) const
{
	VALIDATE_OBJECT

	const IDInfo* pUnitNode;
	CvCity* pCity = pPlot->getPlotCity();

	CvCity* pClosestCity = NULL;
	const CvUnit* pLoopUnit;
	CvPlot* pLoopPlot;

	int iExtraHeal = 0;
	int iExtraFriendlyHeal = getExtraFriendlyHeal();
	int iExtraNeutralHeal = getExtraNeutralHeal();
	int iExtraEnemyHeal = getExtraEnemyHeal();
#if defined(MOD_BALANCE_CORE_BELIEFS)
	int iReligionMod = 0;
	if(MOD_BALANCE_CORE_BELIEFS)
	{
		if(GET_PLAYER(getOwner()).getCapitalCity() != NULL && (plot()->getOwner() == getOwner()))
		{
			ReligionTypes eMajority = GC.getGame().GetGameReligions()->GetFounderBenefitsReligion(getOwner());
			if(eMajority == NO_RELIGION)
			{
				eMajority = GET_PLAYER(getOwner()).GetReligions()->GetReligionInMostCities();
			}
			if(eMajority != NO_RELIGION)
			{
				const CvReligion* pReligion = GC.getGame().GetGameReligions()->GetReligion(eMajority, getOwner());
				if(pReligion)
				{
					CvCity* pHolyCity = NULL;
					CvPlot* pHolyCityPlot = GC.getMap().plot(pReligion->m_iHolyCityX, pReligion->m_iHolyCityY);
					if (pHolyCityPlot)
					{
						pHolyCity = pHolyCityPlot->getPlotCity();
					}
					iReligionMod = pReligion->m_Beliefs.GetFriendlyHealChange(getOwner(), pHolyCity);
					BeliefTypes eSecondaryPantheon = GET_PLAYER(getOwner()).getCapitalCity()->GetCityReligions()->GetSecondaryReligionPantheonBelief();
					if (eSecondaryPantheon != NO_BELIEF)
					{
						iReligionMod += GC.GetGameBeliefs()->GetEntry(eSecondaryPantheon)->GetFriendlyHealChange();
					}
					iExtraFriendlyHeal += iReligionMod;
				}
			}
		}
	}
	else
	{
#endif
	// Heal from religion
	int iReligionMod = 0;
	if(!pCity)
	{
		pClosestCity = pPlot->GetAdjacentFriendlyCity(getTeam());
	}
	else
	{
		pClosestCity = pCity;
	}
	if(pClosestCity && pClosestCity->getOwner() == getOwner())
	{
		ReligionTypes eMajority = pClosestCity->GetCityReligions()->GetReligiousMajority();
		if(eMajority != NO_RELIGION)
		{
			const CvReligion* pReligion = GC.getGame().GetGameReligions()->GetReligion(eMajority, getOwner());
			if(pReligion)
			{
				iReligionMod = pReligion->m_Beliefs.GetFriendlyHealChange(getOwner());
				BeliefTypes eSecondaryPantheon = pClosestCity->GetCityReligions()->GetSecondaryReligionPantheonBelief();
				if (eSecondaryPantheon != NO_BELIEF)
				{
					iReligionMod += GC.GetGameBeliefs()->GetEntry(eSecondaryPantheon)->GetFriendlyHealChange();
				}
				iExtraFriendlyHeal += iReligionMod;
			}
		}
	}
#if defined(MOD_BALANCE_CORE)
	}
#endif
	// Heal from units
	int iBestHealFromUnits = 0;
	pUnitNode = pPlot->headUnitNode();
	while(pUnitNode != NULL)
	{
		pLoopUnit = ::getUnit(*pUnitNode);
		pUnitNode = pPlot->nextUnitNode(pUnitNode);

		if(pLoopUnit && pLoopUnit->getTeam() == getTeam())
		{
			int iHeal = pLoopUnit->getSameTileHeal();

			if(iHeal > iBestHealFromUnits)
			{
				iBestHealFromUnits = iHeal;
			}
		}
	}
	for(int iI = 0; iI < NUM_DIRECTION_TYPES; iI++)
	{
		pLoopPlot = plotDirection(pPlot->getX(), pPlot->getY(), ((DirectionTypes)iI));

		if(pLoopPlot != NULL)
		{
			if(pLoopPlot->area() == pPlot->area())
			{
				pUnitNode = pLoopPlot->headUnitNode();

				while(pUnitNode != NULL)
				{
					pLoopUnit = ::getUnit(*pUnitNode);
					pUnitNode = pLoopPlot->nextUnitNode(pUnitNode);

					if(pLoopUnit && pLoopUnit->getTeam() == getTeam())
					{
						int iHeal = pLoopUnit->getAdjacentTileHeal();

						if(iHeal > iBestHealFromUnits)
						{
							iBestHealFromUnits = iHeal;
						}
					}
				}
			}
		}
	}
	iExtraHeal += iBestHealFromUnits;

	// Heal from territory ownership (friendly, enemy, etc.)
	int iBaseHeal = 0;
	if(pPlot->isCity())
	{
		iBaseHeal = GC.getCITY_HEAL_RATE();
		iExtraHeal += (GET_TEAM(getTeam()).isFriendlyTerritory(pPlot->getTeam()) ? iExtraFriendlyHeal : iExtraNeutralHeal);
		if(pCity)
		{
			iExtraHeal += pCity->getHealRate();
		}
	}
	else
	{
		if(!IsInFriendlyTerritory())
		{
			if(isEnemy(pPlot->getTeam(), pPlot))
			{
				iBaseHeal = GC.getENEMY_HEAL_RATE();
				iExtraHeal += iExtraEnemyHeal;
			}
			else
			{
				iBaseHeal = GC.getNEUTRAL_HEAL_RATE();
				iExtraHeal += iExtraNeutralHeal;
			}
		}
		else
		{
			iBaseHeal = GC.getFRIENDLY_HEAL_RATE();
			iExtraHeal += iExtraFriendlyHeal;
		}
	}
#if defined(MOD_BALANCE_CORE_RESOURCE_MONOPOLIES)
	if(MOD_BALANCE_CORE_RESOURCE_MONOPOLIES)
	{
		const std::vector<ResourceTypes>& vStrategicMonopolies = GET_PLAYER(getOwner()).GetStrategicMonopolies();
		for (size_t iResourceLoop = 0; iResourceLoop < vStrategicMonopolies.size(); iResourceLoop++)
		{
			ResourceTypes eResourceLoop = vStrategicMonopolies[iResourceLoop];
			CvResourceInfo* pInfo = GC.getResourceInfo(eResourceLoop);
			if (pInfo && pInfo->getMonopolyHealBonus() > 0)
			{
				iExtraHeal += pInfo->getMonopolyHealBonus();
			}
		}
	}
#endif

	// Base healing rate mod
	int iBaseHealMod = GET_PLAYER(getOwner()).getUnitBaseHealModifier();
	if(iBaseHealMod != 0)
	{
		iBaseHeal = ((100 + iBaseHealMod) / 100) * iBaseHeal;
	}
	CvAssertMsg(iBaseHeal >= 0, "Base healing rate not expected to be negative!");

	int iTotalHeal = iBaseHeal + iExtraHeal;
#if defined(MOD_BALANCE_CORE)
	TerrainTypes eTerrain = plot()->getTerrainType();
	if(eTerrain != NO_TERRAIN)
	{
		if(isTerrainDoubleHeal(eTerrain))
		{
			iTotalHeal *= 2;
		}
	}
	FeatureTypes eFeature = plot()->getFeatureType();
	if(eFeature != NO_FEATURE)
	{
		if(isFeatureDoubleHeal(eFeature))
		{
			iTotalHeal *= 2;
		}
	}
#endif
	return iTotalHeal;
}

```
`

**Comment by LoneGazebo** [comment]
If you see anything awry here, let me know, but I sure don't.

**Comment by Mitchsp** [comment]
Sorry, but I don't know coding (only some VBA for macro elaboration with Office)

**Comment by TechpriestEnginseer** [comment]
````
	iExtraHeal += iBestHealFromUnits;

	// Heal from territory ownership (friendly, enemy, etc.)
	int iBaseHeal = 0;
	if(pPlot->isCity())
	{
		iBaseHeal = GC.getCITY_HEAL_RATE();
		iExtraHeal += (GET_TEAM(getTeam()).isFriendlyTerritory(pPlot->getTeam()) ? iExtraFriendlyHeal : iExtraNeutralHeal);
		if(pCity)
		{
			iExtraHeal += pCity->getHealRate();
		}
	}
````

**Comment by LoneGazebo** [comment]
It is += not =, therefore it is additive.

**Comment by TechpriestEnginseer** [comment]
Can @Mitchsp replicate this with only land units? It may be a domain and terrain issue then.

**Comment by Mitchsp** [comment]
With Land units is working fine Enginseer,

With Medic
![imagen](https://user-images.githubusercontent.com/13163824/29362185-2ef184b4-828b-11e7-841f-521b3178859e.png)

or Medic II

![imagen](https://user-images.githubusercontent.com/13163824/29362329-c9ae6828-828b-11e7-9aa6-b5229f2d5ac6.png)

**Comment by TechpriestEnginseer** [comment]
There's something wrong with the iBaseHeal then if not iExtraHeal. Because as far as I know ships has a different base heal than land units so there must be a correlation there.

**Comment by HalfEmptyMug** [comment]
>  Because medic does not cross domains for the bonus.

So I did a quick test with forts and found something interesting: a naval unit in a fort also won't benefit from the medic promotions of a naval unit in sea, but if _both_ the medic unit and the damaged unit are in an adjacent city and fort/citadel (or 2 forts through plot editing) then the damaged unit will heal more quickly while naval units in adjacent sea won't. Also, if a land unit is next to a naval medic unit in a city/fort it too will heal faster.

![](https://i.imgur.com/Pu73VYK.png)

Units (both naval and land) heal +30 HP in cities, so I don't think it has to do with the city overriding the heal.

I think the issue might have to do with the way forts allow ships to pass through and the change that prevent's ranged ships from attacking within cities and forts. Since melee naval units can attack land units in forts, this might mean that they're crossing domains when entering these plots. 

Code wise I'm not familiar with what each variable and object represents, but:


	for(int iI = 0; iI < NUM_DIRECTION_TYPES; iI++)
	{
		pLoopPlot = plotDirection(pPlot->getX(), pPlot->getY(), ((DirectionTypes)iI));

		if(pLoopPlot != NULL)
		{
			if(pLoopPlot->area() == pPlot->area())
			{
				pUnitNode = pLoopPlot->headUnitNode();

				while(pUnitNode != NULL)
				{
					pLoopUnit = ::getUnit(*pUnitNode);
					pUnitNode = pLoopPlot->nextUnitNode(pUnitNode);

					if(pLoopUnit && pLoopUnit->getTeam() == getTeam())
					{
						int iHeal = pLoopUnit->getAdjacentTileHeal();

						if(iHeal > iBestHealFromUnits)
						{
							iBestHealFromUnits = iHeal;
						}
					}
				}
			}
		}
	}

When checking eligible units to heal around the medic, it checks that the plot type of both units match through `if(pLoopPlot->area() == pPlot->area())` rather than checking unit type (I think, unless it's already implied?). Since the ship is technically on land, this would mean that other units on land would also benefit.

**Comment by TechpriestEnginseer** [comment]
wew smarter than me and Gazebo. That seems about right.

**Comment by LoneGazebo** [comment]
The area check makes sense - I'll remove it and instead have it check that both units are of the same domain (so land units won't give their bonus to naval units, etc.).
