### ISSUE TITLE
The 3rd tier policies look disabled

### ISSUE THREAD

**Issue by ZenyaIse** [LoneGazebo/Community-Patch-DLL#3441]
_1. Mod version (i.e Date - 4/23):_
7-18-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
After getting 12 policies, the policies of the 3rd tier (Industry, Imperialism, and Rationalism) become available, but look disabled in the social policies panel (see the screenshot).
However they look normal if one of the below conditions is met:
1) mouse over the policy tree area (see the screenshot);
2) the Industrial Era is reached;
3) a policy can be unlocked this turn.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20170816155539_1](https://user-images.githubusercontent.com/14177264/29362149-afbae70e-82c5-11e7-9f60-11d07d8c8ad3.jpg)
![20170816155557_1](https://user-images.githubusercontent.com/14177264/29362170-cfb6e846-82c5-11e7-898a-235f99e6fc5d.jpg)

**Comment by TechpriestEnginseer** [comment]
I'm guessing you haven't reached the Industrial Era since that UI relied on the era requirement rather than social policies needed.

**Comment by ZenyaIse** [comment]
Yes, I believe this is purely UI bug.
By the way, may be it would be a good idea not to allow jumping to the 3rd tier without unlocking a number of policies from the 2nd tier.

**Comment by TechpriestEnginseer** [comment]
This was the case a year ago, but the idea of encouraging social policies in the ancient tree became more important and versatility was what VP strives for.

**Comment by LoneGazebo** [comment]
UI design by firaxis, can't fix.
