### ISSUE TITLE
CTD problem

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3442]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_
nothing except VP

_3. Error description:_ 
I click next turn, it crashes on AI's turn. happened twice in a row after the turn, though I always settle the settler first.
[AutoSave_0095 BC-1625.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1228558/AutoSave_0095.BC-1625.zip)

**Comment by Enrico-Swagolo** [comment]
It's on Sweden's turn now that I looked at it. It crashed a third time.

**Comment by LoneGazebo** [comment]
I just ran your save, no crash. You have a crash log?

**Comment by LoneGazebo** [comment]
Also Petra in your capital? Madman.

**Comment by Enrico-Swagolo** [comment]
Wait, try this one then, maybe it's because of some other actions. This one crashes every time for me on next-turn. Or maybe your version is a bit "improved" compared to the one on civfanatics?

[cliHarald Bluetooth_0096 BC-1600.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1228906/cliHarald.Bluetooth_0096.BC-1600.zip)

Petra was supposed to be a settler, though even Petra wouldn't be bad - still +culture, GP point, free trade route.



...Where are crash logs?

**Comment by LoneGazebo** [comment]
The dump file will populate into your root civ folder in steamapps. I'll try that save and see what happens.

**Comment by Enrico-Swagolo** [comment]
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1228928/CvMiniDump.zip)
Cv mini dump, yes? It's here, as I promised. Yours for the taking.

**Comment by LoneGazebo** [comment]
No crash on that other one. And nope, same version as you.

**Comment by LoneGazebo** [comment]
humor me, though: 
[lua51_Win32.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1228946/lua51_Win32.zip)

Rename your file of the same name in your root civ folder and drop this in.

**Comment by Enrico-Swagolo** [comment]
Still crashed. Suspicious, maybe I should re-install the mod or check file integrity?

**Comment by LoneGazebo** [comment]
I would yeah.

**Comment by Enrico-Swagolo** [comment]
Verifying didn't help. Reinstalling the mod didn't help.

Removing Civ 5, entire folder in documents and reinstalling helped though, all's good now and I went to the next turn.

**Comment by HalfEmptyMug** [comment]
CTD on Germany's turn with the no-eui version, complete reinstall of the game and mod didn't fix the issue, nor did the alternate lua51 file. Oddly enough I'm getting a CTD on Sweden's turn too on both of Enrico's saves. 

Save and logs:
[CTD files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1229935/CTD.files.zip)

**Comment by Enrico-Swagolo** [comment]
Hmmm, could be. I've had MessageLog enabled but after reinstalling such settings aren't saved. That could've been the source of the problems all along.

**Comment by LoneGazebo** [comment]
Except that I use message logging all the time.

**Comment by a1nosweat** [comment]
deleting config.ini fixes it for me .  maybe something to do with the modpack posted on civfanatics?
