### ISSUE TITLE
AI non-expansion

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3443]
check this out:

![image](https://user-images.githubusercontent.com/1358966/29371492-c09dc446-82a8-11e7-9615-a61894875e23.png)

the chinese have completely explored the western continent, have high positive happiness, nevertheless show no inclination to found additional cities.

the pioneer is filtered out repeatedly:

287, China, Beijing, PRE: Unit, Pioneer, 12375, 3
287, China, Beijing, PRE: Building, Public School, 6101, 5
287, China, Beijing, PRE: Unit, Caravan, 2190, 1
287, China, Beijing, PRE: Process, Arts, 1695, 1
287, China, Beijing, PRE: Process, Farming, 455, 1
287, China, Beijing, PRE: Process, Research, 385, 1
287, China, Beijing, PRE: Process, Wealth, 325, 1
287, China, Beijing, PRE: Process, Defense, 100, 1
287, China, Beijing, POST: Building, Public School, 6541, 5
287, China, Beijing, POST: Unit, Caravan, 2000, 1
287, China, Beijing, POST: Process, Farming, 888, 1
287, China, Beijing, POST: Process, Arts, 848, 1
287, China, Beijing, POST: Process, Research, 816, 1
287, China, Beijing, POST: Process, Wealth, 591, 1
287, China, Beijing, POST: Process, Defense, 187, 1
287, China, Beijing, SEED: 16104165751576405732, CHOSEN: Public School, Do not rush, TURNS: 5

291, China, Beijing, PRE: Unit, Pioneer, 12125, 3
291, China, Beijing, PRE: Building, Arsenal, 2825, 5
291, China, Beijing, PRE: Process, Arts, 1695, 1
291, China, Beijing, PRE: Process, Farming, 455, 1
291, China, Beijing, PRE: Process, Research, 385, 1
291, China, Beijing, PRE: Process, Wealth, 325, 1
291, China, Beijing, PRE: Unit, Fusilier, 300, 3
291, China, Beijing, PRE: Unit, Cuirassier, 300, 2
291, China, Beijing, PRE: Unit, Lancer, 270, 1
291, China, Beijing, PRE: Unit, Musketman, 210, 2
291, China, Beijing, PRE: Unit, Chu-Ko-Nu, 120, 1
291, China, Beijing, PRE: Process, Defense, 100, 1
291, China, Beijing, POST: Building, Arsenal, 563075, 5
291, China, Beijing, POST: Unit, Fusilier, 995, 3
291, China, Beijing, POST: Process, Farming, 904, 1
291, China, Beijing, POST: Process, Arts, 864, 1
291, China, Beijing, POST: Process, Research, 831, 1
291, China, Beijing, POST: Unit, Musketman, 761, 2
291, China, Beijing, POST: Unit, Chu-Ko-Nu, 679, 1
291, China, Beijing, POST: Process, Wealth, 604, 1
291, China, Beijing, POST: Process, Defense, 191, 1
291, China, Beijing, SEED: 1383291522286766129, CHOSEN: Arsenal, Do not rush, TURNS: 5

293, China, Beijing, PRE: Unit, Pioneer, 12125, 3
293, China, Beijing, PRE: Process, Arts, 1695, 1
293, China, Beijing, PRE: Process, Farming, 455, 1
293, China, Beijing, PRE: Process, Research, 385, 1
293, China, Beijing, PRE: Process, Wealth, 325, 1
293, China, Beijing, PRE: Unit, Fusilier, 300, 3
293, China, Beijing, PRE: Unit, Musketman, 210, 2
293, China, Beijing, PRE: Unit, Chu-Ko-Nu, 120, 1
293, China, Beijing, PRE: Process, Defense, 100, 1
293, China, Beijing, POST: Unit, Fusilier, 995, 3
293, China, Beijing, POST: Process, Farming, 900, 1
293, China, Beijing, POST: Process, Arts, 860, 1
293, China, Beijing, POST: Process, Research, 827, 1
293, China, Beijing, POST: Unit, Musketman, 761, 2
293, China, Beijing, POST: Unit, Chu-Ko-Nu, 679, 1
293, China, Beijing, POST: Process, Wealth, 601, 1
293, China, Beijing, POST: Process, Defense, 185, 1
293, China, Beijing, SEED: 3858501475613864215, CHOSEN: Fusilier, Do not rush, TURNS: 3

296, China, Beijing, PRE: Unit, Pioneer, 12125, 3
296, China, Beijing, PRE: Process, Arts, 1695, 1
296, China, Beijing, PRE: Process, Farming, 455, 1
296, China, Beijing, PRE: Process, Research, 385, 1
296, China, Beijing, PRE: Process, Wealth, 325, 1
296, China, Beijing, PRE: Unit, Fusilier, 300, 3
296, China, Beijing, PRE: Unit, Musketman, 210, 1
296, China, Beijing, PRE: Unit, Chu-Ko-Nu, 120, 1
296, China, Beijing, PRE: Process, Defense, 100, 1
296, China, Beijing, POST: Process, Farming, 904, 1
296, China, Beijing, POST: Unit, Fusilier, 898, 3
296, China, Beijing, POST: Process, Arts, 864, 1
296, China, Beijing, POST: Process, Research, 831, 1
296, China, Beijing, POST: Unit, Musketman, 779, 1
296, China, Beijing, POST: Unit, Chu-Ko-Nu, 607, 1
296, China, Beijing, POST: Process, Wealth, 604, 1
296, China, Beijing, POST: Process, Defense, 186, 1
296, China, Beijing, SEED: 2759114840370039653, CHOSEN: Fusilier, Do not rush, TURNS: 3

also i wonder how they managed to finish the 5 turn arsenal in 2 turns!

**Comment by LoneGazebo** [comment]
If they're being filtered out, that most likely comes from this:

int iSettleValuation = m_pCity->GetNearbySettleSiteValue();
if(iSettleValuation <= 0)
{
	return 0;
}

Which is set every turn here: CvPlayer::UpdateNearbySettleSites

This function uses the plot found value logic - perhaps we need to loosen the constraints on distance in the mid-game a bit more?

**Comment by LoneGazebo** [comment]
Tweaked the formula and the AI is building settlers now, however their operations aren't launching. That one is on you.  :)

Here's the new formula if you want to drop it in and test:

```
void CvCity::UpdateNearbySettleSites()
{
	if(GET_PLAYER(getOwner()).isBarbarian() || GET_PLAYER(getOwner()).isHuman() || GET_PLAYER(getOwner()).GetPlayerTraits()->IsNoAnnexing())
	{
		return;
	}

	//if we want to go to other continents, we need a very large search radius
	EconomicAIStrategyTypes eStrategyExpandToOtherContinents = (EconomicAIStrategyTypes)GC.getInfoTypeForString("ECONOMICAISTRATEGY_EXPAND_TO_OTHER_CONTINENTS");
	EconomicAIStrategyTypes eStrategyReallyExpandToOtherContinents = (EconomicAIStrategyTypes)GC.getInfoTypeForString("ECONOMICAISTRATEGY_REALLY_EXPAND_TO_OTHER_CONTINENTS");
	bool bWantOffshore = GET_PLAYER(getOwner()).GetEconomicAI()->IsUsingStrategy(eStrategyReallyExpandToOtherContinents) || GET_PLAYER(getOwner()).GetEconomicAI()->IsUsingStrategy(eStrategyExpandToOtherContinents);

	int iSettlerDistance;
	int iDistanceDropoff;
	int iValue;
	int iDanger;
	int iBestValue = 0;
	m_iNearbySettlerValue = 0;

	int iSettlerX = getX();
	int iSettlerY = getY();

	int iEvalDistance = GC.getSETTLER_EVALUATION_DISTANCE() * 3;
	int iBeginSearchX = iSettlerX - iEvalDistance;
	int iBeginSearchY = iSettlerY - iEvalDistance;
	int iEndSearchX   = iSettlerX + iEvalDistance;
	int iEndSearchY   = iSettlerY + iEvalDistance;

	CvMap& kMap = GC.getMap();

	TeamTypes eUnitTeam = getTeam();

	CvCity* pCapital = GET_PLAYER(getOwner()).getCapitalCity();
	int iCapArea = NULL;
	if(pCapital != NULL)
	{
		iCapArea = pCapital->getArea();
	}

	for(int iPlotX = iBeginSearchX; iPlotX != iEndSearchX; iPlotX++)
	{
		for(int iPlotY = iBeginSearchY; iPlotY != iEndSearchY; iPlotY++)
		{
			CvPlot* pPlot = kMap.plot(iPlotX, iPlotY);
			if(!pPlot)
			{
				continue;
			}

			//if (!pPlot->isVisible(pUnit->getTeam(), false /*bDebug*/))
			if(!pPlot->isRevealed(eUnitTeam))
			{
				continue;
			}

			// Can't actually found here!
			if(!GET_PLAYER(getOwner()).canFound(iPlotX, iPlotY))
			{
				continue;
			}

			// Do we have to check if this is a safe place to go?
			if (pPlot->isVisibleEnemyUnit(GET_PLAYER(getOwner()).GetID()))
				continue;


			//check for new continent
			const CvArea* pArea = GC.getMap().getArea(pPlot->getArea());
			bool bNewContinent = (pArea && pArea->getCitiesPerPlayer(getOwner()) == 0);
			bool bOffshore = (pArea && pCapital && pArea->GetID() != pCapital->plot()->getArea());
			if (!bOffshore || !bNewContinent)
			{
				bWantOffshore = false;
			}

			iDanger = GET_PLAYER(getOwner()).GetPlotDanger(*pPlot);
			if (iDanger > 1000 && !bWantOffshore)
				continue;

			//take into account distance from existing cities
			int iDistance = plotDistance(getX(), getY(), pPlot->getX(), pPlot->getY());
			int iRelevantDistance = min(iDistance, GET_PLAYER(getOwner()).GetCityDistanceInEstimatedTurns(pPlot) * 2); //times 2 to get the approximate plot distance
			int iScale = MapToPercent(iRelevantDistance, iEvalDistance, GC.getSETTLER_DISTANCE_DROPOFF_MODIFIER());

			//on a new continent we want to settle along the coast
			if (bNewContinent && !pPlot->isCoastalLand())
				iScale = 1;

			//if we want offshore expansion, distance mostly doesn't matter, use a flat scale below a threshold
			if (bWantOffshore && bOffshore)
				iScale = max(iScale, 70);

			iValue = GET_PLAYER(getOwner()).getPlotFoundValue(iPlotX, iPlotY) / 100;

			iValue = (iValue*iScale) / 100;
			
			if(iValue > iBestValue)
			{
				iBestValue = iValue;
			}
		}
	}
	m_iNearbySettlerValue = iBestValue;
}
```

**Comment by ilteroi** [comment]
i'm not sure this check is actually needed ... it seems pretty redundant ... after all, there's already CvPlayer::HaveGoodSettlePlot() and CvPlayer::setAveragePlotFoundValue() which hook into the economic strategies.

if the point is to enforce building the settler close to the target, we need to find a measure of avg distances. or just skip this part, i feel the added value is low, it's more important to finish the settler quickly.

**Comment by LoneGazebo** [comment]
I use this to keep the AI from spooling the 'havegoodsettleplot' code over and over in the unitproductionAI.

G

**Comment by ilteroi** [comment]
HaveGoodSettlePlot() is not so bad ... anyway the point i'm trying to make is that the call is not needed at all, we can simply check for Strategy_EnoughExpansion

**Comment by LoneGazebo** [comment]
We can, but I also use the found value that is cached for urgency, as it increases the value of the unit.

**Comment by ilteroi** [comment]
i went for the simple version ... seems to work fine. didn't see any stuck settlers either.

any idea how the AI can finish a 5 turn building in 2?

**Comment by LoneGazebo** [comment]
Instant yields?

**Comment by ilteroi** [comment]
maybe ... but how would you get so many instant hammers? does the AI spend engineers on non-wonders?

anyway, found a stuck settler, ball's back in your court, this code fails for a naval op with just two units:

		//naval needs less space with ocean travel.
		if (IsNavalOperation())
		{
			if (GET_PLAYER(pArmy->GetOwner()).CanCrossOcean())
			{
				iRange--;
			}

just kidding, i'll just remove the decrement then it's fine.

also found a second bug for settlers with multiple escorts, but that should be rare.

**Comment by LoneGazebo** [comment]
Haha, thanks for the fix. I'll remove that update code and just use the basic check (and fudge the number).

**Comment by ilteroi** [comment]
oh, don't touch it, otherwise there'll be merge conflicts ... pushing soon

**Comment by ilteroi** [comment]
so settling on remote continents still doesn't really work for the AI, i suspect it's because they are typically infested with barbarians, which kill scouts (also naval) and deter settlers. 

tried to loosen up the conditions for barb-camp removal ops, let's see how it goes. may also need some more naval superiority ops, but that's difficult with the enemy units in the fog of war,

**Comment by LoneGazebo** [comment]
I see a few overseas settlements here and there, but yeah, generally sparse. I'm not too worried about it.

**Comment by LoneGazebo** [comment]
@ilteroi I wonder if we should allow CSs to barb hunt if there are no majors on the continent?

**Comment by ilteroi** [comment]
don't think that's necessary, seems to be better now. pushed.
