### ISSUE TITLE
Religious Pressure Bonus from Policies and everything else

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3448]
Are they to be assumed that they'll provide the pressure bonus for all religion or majority religion?

**Comment by LoneGazebo** [comment]
They should work for all religions, EXCEPT for ones tied to trade routes.

**Comment by TechpriestEnginseer** [comment]
Even the one with promotions that when garrisoned provides pressure?
