### ISSUE TITLE
"Declare war on CS" notification (for vassal) when actually make peace

### ISSUE THREAD

**Issue by ZenyaIse** [LoneGazebo/Community-Patch-DLL#3449]
_1. Mod version (i.e Date - 4/23):_
7-18-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
After making peace with a major civ and CSs, "Declare war on CS" notification appears for my vassal while he actually made peace.

_4. Steps to reproduce (optional):_
How to confirm from the attached save:
- Mouse over the notification icon (on the right of the screen) "Japan declares war on CS"
- Confirm (for example from Diplomacy panel) that Japan is not actually in war with these CSs.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Gustavus Adolphus_0385 AD-1750_b.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1235945/Gustavus.Adolphus_0385.AD-1750_b.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
That's just an EUI bug. Can't fix.
