### ISSUE TITLE
Puppet increases policy and tech cost

### ISSUE THREAD

**Issue by BorussiaVox** [LoneGazebo/Community-Patch-DLL#3451]
_1. Mod version (i.e Date - 4/23):_
8-16

_2. Mod list (if using Vox Populi only, leave blank):_
InfoAddict (v 22)
Really Advanced Setup (v 15)

_3. Error description:_ 
When I conquer and puppet the greek city Ephesus it increases tech and policy costs as if I had annexed it. If I annex it after that the costs remain the same. 
If I annex my other puppets the costs increase (because I think they did not increase when i puppeted them. The bug occurs here with Ephesus the first time I think).
[puppet cost bug - logs and savegame.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1236863/puppet.cost.bug.-.logs.and.savegame.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by BorussiaVox** [comment]
Another issue with this savegame is that Germany becomes the voluntary vassal of India the next turn even though both are equally strong, India is far away and Germany in no danger from anyone. Is that intended?

**Comment by LoneGazebo** [comment]
You are just seeing the value update as a result of other cities, as the cost only updates when you take a city (regardless of what you do). Is working as intended.
