### ISSUE TITLE
Can build oil units without having discovered oil

### ISSUE THREAD

**Issue by lorduc** [LoneGazebo/Community-Patch-DLL#3453]
Basically, I researched flight, but not combustion that allows you to discover oil. I could build bombers and triplanes that require oil.  tooltip (on top of the screen) did not show an oil icon
turns out, I had made an embassy on top of an oil reserve in one of the city states that was my ally. 

So I was being granted oil from a city state even though I hadn't discovered oil yet.
However, another civ had discovered oil already (Arabia)

**Comment by LoneGazebo** [comment]
GP Improvements grant revealed resources to the owner, so the CS knew it was there and you did not. This is normal.
