### ISSUE TITLE
Mine Field problem

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3455]
_1. Mod version (i.e Date - 4/23):_
8/16

Looks like something was changed in mine field. Now it always work, no matter workable is tile or not.
If I remember right, earlier it works only on workable tiles(as description says).

![20170821193327_1](https://user-images.githubusercontent.com/13381981/29529337-f6e6c6f8-86a7-11e7-9003-7c0d2a9893cf.jpg)

![20170821193336_1](https://user-images.githubusercontent.com/13381981/29529342-fb2e3606-86a7-11e7-88e4-076e15a19473.jpg)

**Comment by LoneGazebo** [comment]
Affects tiles owned by the city.

**Comment by bigcat88** [comment]
ah, ok.
then I just misunderstood description. "if they move into a tile worked by a city"
