### ISSUE TITLE
CTD on AI turn

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#3457]
![image](https://user-images.githubusercontent.com/14372214/29538182-2b19d9ce-868a-11e7-8a1c-0f7bb2be9c4a.png)

**Comment by LoneGazebo** [comment]
That kind of crash usually means that there was a memory error on the user's computer.

**Comment by ilteroi** [comment]
nah, looks like accessing an invalid CvUnit pointer.

question is, where would it come from. ExecuteMoveToPlot() checks for null pointers, so apparently it's not null. then again the problem seems to occur in a call to std::map, but setMoves() doesn't do anything with maps.

so, not enough information ... is it reproducable? do you have a savegame?

**Comment by Iamblichos** [comment]
I've reproduced it on multiple machines. So I don't think its a memory error. I don't have a savegame unless you want to take the time to build my branch, but our code is common here at all the stack points, and I can't figure out why it's getting a bad pointer as it seems all the calls check for that.

**Comment by ilteroi** [comment]
if you can reproduce it,  just set a breakpoint and watch what happens ... i haven't seen this issue on my end, that much i can say

**Comment by Iamblichos** [comment]
I found the problem.

**Comment by LoneGazebo** [comment]
and?

**Comment by Iamblichos** [comment]
Watching the break points helped.

```
if(isConvertUnit())
		{
			CvUnit* pConvertUnit = NULL;
			for (int iI = 0; iI < GC.getNumPromotionInfos(); iI++)
			{
				const PromotionTypes eLoopPromotion = static_cast<PromotionTypes>(iI);
				CvPromotionEntry* pkPromotionInfo = GC.getPromotionInfo(eLoopPromotion);
				if(pkPromotionInfo)
				{
					if(pkPromotionInfo->GetConvertDomainUnit() != NO_UNIT)
					{
						if((pNewPlot->getDomain() == pkPromotionInfo->GetConvertDomain()) && (this->isHasPromotion(eLoopPromotion)) && (pkPromotionInfo->getRequiredUnit() == this->getUnitType()))
						{
							UnitAITypes eAIType = NO_UNITAI;
							const CvUnitEntry* pkUnitType = GC.getUnitInfo(pkPromotionInfo->GetConvertDomainUnit());
							if(pkUnitType != NULL)
							{
								eAIType = (UnitAITypes)pkUnitType->GetDefaultUnitAIType();
								CvUnit* pNewUnit = GET_PLAYER(getOwner()).initUnit(pkPromotionInfo->GetConvertDomainUnit(), this->getX(), this->getY(), eAIType, NO_DIRECTION, true, true, 0, 0, NO_CONTRACT, false);
								pConvertUnit = pNewUnit;
							}
						}
					}
				}
			}
			if(pConvertUnit != NULL)
			{
				this->kill(true, NO_PLAYER, true);
				pConvertUnit->finishMoves();
			}
		}
```

This is some code I have in DLL that I use but you don't unless you have a unit that does this. The unit (in this case a general) converts to an admiral when it moves to a sea tile and vice versa. So the old unit gets killed prior to running ExecuteMoveToPlot.

**Comment by Iamblichos** [comment]
The code above is executed within setXY

**Comment by Iamblichos** [comment]
Alright that was an easy fix. Changing this:

this->kill(false, NO_PLAYER, true);

to this:

this->kill(true, NO_PLAYER, true);

fixed it.

**Comment by Iamblichos** [comment]
Only problem I have now is doing a delayed death increases unit supply just from land->water or water->land. I'll have to figure that out.

**Comment by Iamblichos** [comment]
Okay I got this all sorted.
