### ISSUE TITLE
When an improvement gets pillaged by an Event, it should pop a notification of where the improvement was destroyed!

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3459]
I feel many people are complaining about the issue because when they see their 3-5 farms destroyed, they don't exactly know where if they have a large empire and this can become an issue if two city events repeat itself and you're wondering where and where.

**Comment by LoneGazebo** [comment]
tbh I think we should replace these events with a dialog choice of 'pay gold to restore immediately' or 'do nothing and let them be pillaged.' A la civ 4:
```

Event1
	Forest Fire
	Prereq: Forest in city fat cross
	Obsolete: None
	Active/Weight: 70/100
		Result:
1.you pay 10 gold
2.you pay 4 gold and lose 1 forest
3.you pay nothing, lose one forest and gain 1 angry face (lasts as long as whip anger)
```

**Comment by TechpriestEnginseer** [comment]
That's fine.

**Comment by preyator** [comment]
Will the forest be lost permanently?

**Comment by preyator** [comment]
I think a permanent forest loss is frustrating

**Comment by TechpriestEnginseer** [comment]
No this is just an example. If we made forest fires, everyone would have pitchforks.

**Comment by preyator** [comment]
Thank god! :D

**Comment by ashendashin** [comment]
Forest fires would be interesting though. Especially if new forests pop up after a while. 

Along with stuff like unhappy empires experiencing highwaymen, who increase road maintenance for a time if you choose to deal with them or have barb camps spawn near roads every now and then if not. Weather events that are less straightforward, like hurricanes that damage naval units, work boats, and cargo ships within a set of tiles at sea, but I don't know if events can be attached to units. Famine forcing your people to try their luck at your neighbors.

The current negative events feel lacking in creating dynamic scenarios. They mostly cost yields and create some extra micromanagement, with the really bad ones only creating crippling situations. At least that's how it leaves me feeling about them.

**Comment by TechpriestEnginseer** [comment]
We had thought about dynamic negative events, but went against it because of how the community can't see the clockwork behind the negative events. We would always then have confirmation bias that these events are detrimental to the gameplay or something.

**Comment by ashendashin** [comment]
But then there's so little fun in negative events. Barbs sometimes make me reconsider my unit commitment, yet there's nothing else that makes negative events feel like they go hand in hand with the positive. It's a sharp contrast, nothing more. Balancing the positive to allow adapting to dynamic scenarios could be better than a simple give and take set. Right now it's the negative balancing the positive, which is plain annoying.

**Comment by TechpriestEnginseer** [comment]
We can't exactly just use the "pay gold to not have improvement pillaged". It's too generic.

**Comment by TechpriestEnginseer** [comment]
I think this was fixed already.
