### ISSUE TITLE
"Fortify until healed" issue

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#346]
It doesn't alert the player when a unit takes more damage than it heals.
Happens often with scouts getting wrecked by stray archers and axe throwers. At best there is a short notice "scout took 20 damage" showing for several seconds at the enemy turn.

**Comment by LoneGazebo** [comment]
Not sure what you are asking for here - for the unit to 'wake up?'
G

**Comment by Radost** [comment]
Indeed, so instead of fortify it would use alert mode while healing.

**Comment by LoneGazebo** [comment]
I'll just have the unit 'wake up' and become alert when attacked. Should fix.
