### ISSUE TITLE
AI not building escort for settler

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3460]
90 turns in and france is already losing because they can't be bothered to build escorts for their settlers:

![image](https://user-images.githubusercontent.com/1358966/29585129-55cb13ca-8786-11e7-99aa-a7cd24268695.png)

similar thing is happening to mongolia, they have units but recruit them for a sneak attack, which seems to take precedence:

![image](https://user-images.githubusercontent.com/1358966/29585227-b008afb4-8786-11e7-84c9-60743a5a5076.png)

do you see a way to fix this?

[CityStrategyAIProductionLog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1243234/CityStrategyAIProductionLog.zip)

**Comment by LoneGazebo** [comment]
There are checks for pending operation units but I may need to increase the priority.
