### ISSUE TITLE
Workers stop working after one tile of road is built

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3463]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So far, I have to tell them to continue working on further roads every tile they change.

**Comment by Enrico-Swagolo** [comment]
Sometimes it's after two. No land barbies in sight.

**Comment by LoneGazebo** [comment]
@ilteroi any ideas?

**Comment by ilteroi** [comment]
oh no, not again ... i'll check it
