### ISSUE TITLE
new world expansion still a problem

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3467]
latest testgame. stepped into germany's shoes at turn 300, the world is fully explored, but the new world is still sparsely settled.

![image](https://user-images.githubusercontent.com/1358966/29732022-1113c8f4-89e7-11e7-9766-805ea3ff0094.png)

germany is at +41 happiness and could easily afford some expansion, but they won't even consider building colonists.

[CityStrategyAIProductionLog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1252967/CityStrategyAIProductionLog.zip)

why is that?

one factor is probably that they are at war ... but it seems to be a stalemate, and they do have the leisure to build a guild in frankfurt.

![image](https://user-images.githubusercontent.com/1358966/29732136-987490d0-89e7-11e7-8ce0-642691881cbb.png)

seems like the priorities are not quite right.

**Comment by ilteroi** [comment]
also, this is the map from polynesia's perspective at turn 180:

![image](https://user-images.githubusercontent.com/1358966/29740468-c17b7e88-8a57-11e7-9c07-978eca9b3a00.png)

they are currently at +16 happiness, but are also very slow to expand. maybe they need an adjustment to make better use of their UA? happiness bonus? more expansionist?

**Comment by LoneGazebo** [comment]
What kind of flavors are they running? Anything for Continent Expand or Expand Like Crazy?

**Comment by LoneGazebo** [comment]
Most of the boosts in the unit production AI stem from those city and economic strategies.

**Comment by ilteroi** [comment]
currently polynesia is running ENOUGH_EXPANSION because of unhappiness. which is mostly due to unfortunate decisions like not building lighthouses in overseas cities for more than 100 turns. 

can you bump this up? i've seen issues like that before, happiness management seems to be lacking a bit.

what's the logic for a settler unit to appear in the PRE section of the city production log? it's really rather rare for a city to even consider building a settler ...

**Comment by LoneGazebo** [comment]
I'll look at that, yeah. PRE exclusion of settlers would probably be from unhappiness. No other restrictions really apply to it.

G

**Comment by ilteroi** [comment]
ok, fixed a bunch of nasty corner cases. it's as good as it gets now.

with better happiness management we should be golden.
