### ISSUE TITLE
Partizans

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#3469]
_1. Mod version (i.e Date - 4/23):_
8/16

_2. Mod list (if using Vox Populi only, leave blank):_
VP
RED

_3. Error description:_ 
City spawned a settler as a partizan unit during razing.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Settler partisans!

**Comment by matlajs** [comment]
they work like refugees, or what?

**Comment by bigcat88** [comment]
I think it is a rare bug ) I saw such thing, but for 2 last month stop to see, when I start to play peaceful.
In that games when I see this, AI just was out of military cup due to warscore. But maybe I am wrong.
AI that is invaded by u has a big negative warscore?
