### ISSUE TITLE
Liberating a CS captured by barbarians

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#347]
![8930_2015-06-22_00004](https://cloud.githubusercontent.com/assets/1131228/8278726/4c307068-18e7-11e5-93aa-f865f2a65b5c.png)
![8930_2015-06-22_00005](https://cloud.githubusercontent.com/assets/1131228/8278729/54074ea6-18e7-11e5-80f3-61ceb5eb3e8b.png)
![8930_2015-06-22_00006](https://cloud.githubusercontent.com/assets/1131228/8278732/5a678e46-18e7-11e5-858e-f478666d8757.png)

It was already captured before I discovered it, so upon liberation it was my first contact with Florence.

**Comment by LoneGazebo** [comment]
That's a known bug - I've hopefully fixed in upcoming version. Thanks!
G
