### ISSUE TITLE
Backstab Penalty for Vassals which Follow Master to War

### ISSUE THREAD

**Issue by cammcken** [LoneGazebo/Community-Patch-DLL#3470]
_1. Mod version (i.e Date - 4/23):_
8/16/2017

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
No error, I believe. I'm only questioning how intentional.

A vassal who has a DoF with another civ will receive back-stab reputation for going to war against that civ, when it was the master civ which declared war in the first place. The vassal only joined in by obligation.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
Sorry, I don't think it's necessary. If you can't reproduce it, I'll see what I can do.

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Still counts.

**Comment by TechpriestEnginseer** [comment]
The vassal can break the DoF and is freely able to do so.
