### ISSUE TITLE
Penalty for capturing civilians when conquering city

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3472]
_1. Mod version (i.e Date - 4/23):_
last

Is this a error or a new feature(don't remember that this happens in june versions(at that time I played warmonger))?
Cause inside city there was no any worker or anything except garrison, and I get -50 penalty for capturing.

**Comment by LoneGazebo** [comment]
That's normal - you sure you didn't kill a great person?

**Comment by bigcat88** [comment]
Yes, there was no workers, emmisaries, GPs...

**Comment by LoneGazebo** [comment]
Only appears at certain AI opinion thresholds.
