### ISSUE TITLE
Influence decay to slow

### ISSUE THREAD

**Issue by Grabbl** [LoneGazebo/Community-Patch-DLL#3473]
_1. Mod version (i.e Date - 4/23):_
8-23

_2. Mod list (if using Vox Populi only, leave blank):_
Community Events
Shu, Wei, Tunis Civilizations + Compatibiliy Patch (as far as I know, none in this game)

_3. Error description:_ 
My influencs with Mombasa decays at 0.56 points/turn despite me having over 300 influence. Game is on epic (so it should decay at 66% of the standard rate, plus the 1% penalty from influence over 100). I have no Statecraft or other decay modifiers (I think). Also, it is not just a notification bug, influence really decays that slowly.

I apologize if I got something wrong and the decay should be like that.

[InfluenceDecay_Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1254543/InfluenceDecay_Bug.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
I maybe has the same trouble. Epic speed. I don't know from what it depends. Both CS "friendly".

![20170827215132_1](https://user-images.githubusercontent.com/13381981/29753053-fb1fb53a-8b71-11e7-9596-daff960af93c.jpg)

![20170827215135_1](https://user-images.githubusercontent.com/13381981/29753056-0683602a-8b72-11e7-9027-9e76648b7fef.jpg)

**Comment by TechpriestEnginseer** [comment]
Correction: Influence Decay Scale does not exist.

**Comment by LoneGazebo** [comment]
There is a game speed mod, yes.
