### ISSUE TITLE
Stable in city on resource

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3475]
_1. Mod version (i.e Date - 4/23):_
last

I has city that builded on sheep. And I cant build stable, cause game think that resource is unimproved.
City must have a possibility to build stable or don't display it in possibly buildings.

And I think better will be to allow cities build stables if 3 tiles from city on your territory is present sheep\cattle\horse. Cause those micromanagement when one res between two cities and u first build stable in one city, then reassign tile and build stable in second city - is a little annoying. If it is possible.

**Comment by LoneGazebo** [comment]
This is design. Stone works needs a quarry, for example.

**Comment by bigcat88** [comment]
I am not sure about stone works, will check in next game. As I remember I can build stone works when city is on marble... will check after game end.

**Comment by Grabbl** [comment]
I can confirm that I can build stoneworks in cities on a stone resource (with no other stone/marble/anything).

**Comment by bigcat88** [comment]
I think city must be able to build stables(as querry) or just hide the possibility of building.

**Comment by LoneGazebo** [comment]
Can't reproduce.
