### ISSUE TITLE
Suicide embarkanation

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3476]
_1. Mod version (i.e Date - 4/23):_
23 aug

_2. Mod list (if using Vox Populi only, leave blank):_
World Congress Reinformation
PoorTilesTweak

_3. Error description:_ 
Ottoman just embark and die.

_4. Steps to reproduce (optional):_

![20170828140851_1](https://user-images.githubusercontent.com/13381981/29771221-69777a3e-8bfb-11e7-8727-e84e0b0c8d7f.jpg)

![20170828141355_1](https://user-images.githubusercontent.com/13381981/29771231-6d4cc0ec-8bfb-11e7-8e02-efa39a449d14.jpg)

Here is 2 saves, for each screenshot.
[single.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1256592/single.zip)

Also in my previous game I see more funny thing. Indonesia with airports just lift units(tanks and others) on tiles near city that is on water and die,die,die in one shot. Same as on this screens(don't remember from what game, but Indonesia has 3 or 4 coast tiles, so every turn 4 shots -> 4 dead bodies)
![20170824190856_1](https://user-images.githubusercontent.com/13381981/29771393-2e6c2f74-8bfc-11e7-8e88-2b1c68c2ea4e.jpg)
![20170824192422_1](https://user-images.githubusercontent.com/13381981/29771409-3ec84b1e-8bfc-11e7-88bb-69999a2aa8d1.jpg)

**Comment by ilteroi** [comment]
the airlift onto water issue was introduced by MOD_GLOBAL_RELOCATION
@LoneGazebo : is that an essential feature or a bug?

**Comment by LoneGazebo** [comment]
I'll just remove the water thing. Teleporting onto a pontoon bridge is hardly worth the problem.

**Comment by ilteroi** [comment]
second that!

anyway as usual i cannot load the savegames, so it's impossible to debug the embarkation problem. sorry.

**Comment by bigcat88** [comment]
Airlifting on water is much bigger problem.
I don't see much suicide embarkation to say that it is a big problem.
