### ISSUE TITLE
Add up total vote during a yay and nay on a resolution.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3478]
In the notification you might see...

Casus Belli was not passed!
6 for Nay from England
3 for Nay from Ethiopia
2 for Nay from The Huns
1 for Yay from Austria
9 for Yay from Mongolia

I would do it myself but I can't find the Lua notification that reference the text file or my filefinder isn't working properly and I would like it changed to 

Casus Belli was not passed! ([COLOR_POSITIVE_TEXT]10[ENDCOLOR]-[COLOR_NEGATIVE_TEXT]11[ENDCOLOR])
6 for Nay from England
3 for Nay from Ethiopia
2 for Nay from The Huns
1 for Yay from Austria
9 for Yay from Mongolia

To show how much total votes was actually calculated without having to add everyone's votes up. It's helpful when you have 43 civs voting on such crazy things and you're wondering how close you were in lobbying a resolution to pass or get repealed.

**Comment by LoneGazebo** [comment]
Bafflingly firaxis abandoned Lua for brave new world and did most of the UI stuff in the DLL. Look in the VotingClasses .cpp file.

**Comment by TechpriestEnginseer** [comment]
I can't exactly access .cpp files.

**Comment by LoneGazebo** [comment]
Why not? The source is right here.

**Comment by LoneGazebo** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/blob/master/CvGameCoreDLL_Expansion2/CvVotingClasses.cpp
