### ISSUE TITLE
Puppet building units

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#348]
![8930_2015-06-22_00008](https://cloud.githubusercontent.com/assets/1131228/8285666/3ef51624-191e-11e5-97a3-7de9b709bb4a.png)
And it didn't switch to buildings until I annexed it and changed myself.
That was, by the way, the last arabian city.

**Comment by LoneGazebo** [comment]
Odd. I'll take a look - the only thing I can think is that the governor didn't reset. Did it produce multiple crossbowmen, or was this the first one it tried to do?

**Comment by Radost** [comment]
It produced several of them and didn't intend to stop.

**Comment by LoneGazebo** [comment]
Ok, I'll look.
