### ISSUE TITLE
AI happiness management

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3481]
basically everyone is extremely unhappy ... how can that be?

![image](https://user-images.githubusercontent.com/1358966/29835083-2812e2f8-8cf1-11e7-9166-5f6064319946.png)

i'm seeing this quite often when stepping into a late-phase game. it's not due to war weariness:

![image](https://user-images.githubusercontent.com/1358966/29835057-0aaef224-8cf1-11e7-827f-144c87721b54.png)

(this is the mayan empire, for the others it looks similar)

example chichen itza:

![image](https://user-images.githubusercontent.com/1358966/29836800-95ea4c4e-8cf6-11e7-8e88-c02fe130daf4.png)

notice that food focus and "manual specialist control" is active, don't know if that's an artifact of autoplay ... anyway disabling it and setting the city to gold focus helps a little bit:

![image](https://user-images.githubusercontent.com/1358966/29836927-f76c214a-8cf6-11e7-97b8-1aad077bc14c.png)

since happiness is based on the global median yields, who is pulling them up so high? note that the maya are last in tech, so the tech modifier cannot be the reason. their trade routes are maxed out as well. outliers like holy cities should not affect the median.

for comparison, this is dortmund, an overseas german city. the germans are the only ones with positive happiness (next to venice). manual specialist control is off here!

![image](https://user-images.githubusercontent.com/1358966/29839059-449f2542-8cfd-11e7-94f6-8acdd72e3c63.png)

this is the happiness breakdown for germany. they also have very bad cities but apparently enough positive happiness to offset it.

![image](https://user-images.githubusercontent.com/1358966/29839409-65c79474-8cfe-11e7-9e89-57735effc9a0.png)

even for germany more than half their citizens are unhappy. the main reasons are poverty, illiteracy, boredom (the specialist yields ...). is that the way it's supposed to work?

**Comment by LoneGazebo** [comment]
The AI avoids specialists somewhat if it is very unhappy (as they can often contribute more unhappiness than they can offset). Poverty and crime are perennial problems, yes. Illiteracy can become a problem if the global mean rises too fast (which it definitely can after ideologies take off). My best guess is that a war started, seeing as they all dropped at roughly the same time.

G

**Comment by ilteroi** [comment]
i checked, there's no war weariness.

specialists do help in general, so that should at least be tested, no?

food focus also seems suboptimal for cities with high unhappiness.

otheewise i wonder if there's simply something wrong with the threshold calculation.

**Comment by MoiMagnus** [comment]
Do the fall of happiness coincide with a change of era ? Since specialist become more and more expensive in food, it may not help the situation.
