### ISSUE TITLE
Diplomatic Mission infuence mismatch

### ISSUE THREAD

**Issue by ZenyaIse** [LoneGazebo/Community-Patch-DLL#3482]
_1. Mod version (i.e Date - 4/23):_
7-18-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The help says that Diplomat conducts diplomatic mission with influence 100. Actual influence is 75 (with all promotions).

**Comment by LoneGazebo** [comment]
bonuses from policies are not calc'd in tooltip.
