### ISSUE TITLE
Puppeting city increases policy cost

### ISSUE THREAD

**Issue by ZenyaIse** [LoneGazebo/Community-Patch-DLL#3484]
_1. Mod version (i.e Date - 4/23):_
7-18-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Puppeting a captured city increases the policy, science, and golden age costs the same way as annexing city (no difference).

_4. Steps to reproduce (optional):_
a) Open the attached save.
b) Capture Sippar with an Ironclad.
c) Confirm that the policy, science, and golden age costs change the same way whether you puppet or annex the city.

This is the science (Sc), culture (C) and golden age (GA) cost values.
Before capture:
Sc=32604
C=54130
GA=11065

After capture, but before making decision:
Sc=33528
C=54130
GA=11155

If puppet:
Sc=33528
C=55990
GA=11155

If annex:
Sc=33528
C=55990
GA=11155

---------------------------
Supporting information:

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Gustavus Adolphus_capture_city.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1270574/Gustavus.Adolphus_capture_city.zip)

**Comment by bigcat88** [comment]
I saw such behaviour very often in my games. Interesting is this a bug or just so intended...
If someone need saves with such thing(increasing culture) from me - I can upload them. I found that such thing is usual when conquer cities in a row(more then one city in 2-3 turns).
