### ISSUE TITLE
Maya Culture

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#3488]
_1. Mod version (i.e Date - 4/23):_

8/23

_2. Mod list (if using Vox Populi only, leave blank):_

-

_3. Error description:_ 

It's turn 83 on Marathon. Everyone has 2 Policies. Pacals has 9.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

[AutoSave_0082 BC-2770.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1272685/AutoSave_0082.BC-2770.zip)

**Comment by ilteroi** [comment]
do you have the logs as well?

**Comment by Der-Zorn-Gottes** [comment]
No, sorry I forgot about that.
