### ISSUE TITLE
Natural Golden Age Wasted

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#3489]
A natural golden age occurring during a golden age caused by a great artist does not extend the duration.  It also increases the amount of points needed for the next GA.

**Comment by bigcat88** [comment]
I don't see such behaviour in my games... Natural golden age occur after your previous golden age ends. 
There will be in golden age points something like that 9000/8000 - means u have 1000 golden age points more then u need for start and after your current golden age ends, the new will start.

**Comment by jimmymcperson** [comment]
I was mistaken; I didn't know Great Artists increased the required points for Golden Age.  Could this be changed?  It's pretty unintuitive as it is.
