### ISSUE TITLE
Conscription gives fusiliers instead of volley guns

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#349]
![8930_2015-06-22_00010](https://cloud.githubusercontent.com/assets/1131228/8285808/42e6af9e-191f-11e5-9c81-98076c1f6699.png)
Also it didn't spawn an archer near the capital when I took it.

**Comment by LoneGazebo** [comment]
You don't get units from conquest, only city founding. At least you shouldn't.
G

**Comment by Radost** [comment]
But that was a city I found.

**Comment by LoneGazebo** [comment]
You stated "Also it didn't spawn an archer near the capital when I took it." That's what I was referring to.

I'll look at fusilier versus volley gun.

**Comment by Radost** [comment]
When I took the policy I meant.
It is supposed to spawn an archer in the capital and in all subsequently founded cities.

**Comment by LoneGazebo** [comment]
Ah yes. Gotcha. I'll double check. It defaults to a melee unit if it can't produce a ranged one.
G
