### ISSUE TITLE
Own tiles in fog of war

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#3490]
![20170903123047_1](https://user-images.githubusercontent.com/21192402/30002535-be15aff2-90ab-11e7-9593-587beb596b37.jpg)
_1. Mod version (i.e Date - 4/23):_
8-23

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Some tiles that should be revealed, such as my own city tile or  cs ally tiles are  greyed like they would be in fog of war. Those tiles, that are occupied by my units, are uncontrolable by clicking tile, only through unit list.
![20170903123037_1](https://user-images.githubusercontent.com/21192402/30002534-ba22aae4-90ab-11e7-903e-8dfc76035809.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by matlajs** [comment]
ok. launching a trade route do that. any ideas?

**Comment by ilteroi** [comment]
well the screenshot is undeniable ... but i can't reproduce it. with traderoutes and all. guess we need to watch this.

**Comment by matlajs** [comment]
need to say that it started since industrial maybe.

**Comment by LoneGazebo** [comment]
Did you have a corporation?

**Comment by ilteroi** [comment]
still no repro. with civilized jewelers, but what difference does it make?

**Comment by matlajs** [comment]
i will post a save if it help.

**Comment by matlajs** [comment]
[Ahmad al-Mansur_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1287548/Ahmad.al-Mansur_0000.BC-4000.zip)

**Comment by ilteroi** [comment]
ah, that's the initial save? but the problem only occurs in the industrial age?

**Comment by matlajs** [comment]
that is a late game save, just not renamed. problems occur ,,since'' industrial.  maybe since corporations. now i am playing new Theodora game. will see if it occurs again.

**Comment by matlajs** [comment]
I forgot to mention, that with latest version in my Japan game i haven't had this problem with civilized jewelers corp. So i do not know if this problem is related only arround Two kay food or Morroco(maybe something with their UA+ corp?)

**Comment by ilteroi** [comment]
honestly i'd be very surprised if this is related to any corporation ... hotseat sounds plausible, but debugging multiplayer is a pain

**Comment by matlajs** [comment]
my game was singleplayer, but it doesn't matter anymore.

**Comment by Voker57** [comment]
I confirm that happens with TwoKay Foods at least in 1.21. Problem is probably that TwoKay foods reveals tiles around cargo ships, they probably don't get properly updated or something.

**Comment by Voker57** [comment]
http://dump.bitcheese.net/files/cynywoh/visible.Civ5Save 1.21 save illustrating the issue (load as Voker57, look at tiles near Delphi)

**Comment by ilteroi** [comment]
hmm. i don't see any obvious problem with the trade units. but that's just from looking at the code

**Comment by ilteroi** [comment]
ok, this was quite a chase. did i mention i never want to touch the vision code again?

fixing this (hopefully for good) required some changes regarding the handling of vision range zero. previously it was basically treated like vision range 1. therefore there was special code for trade units. now zero is taken to mean only the current unit plot becomes visible. 

this affects both regular trade units (where it's a nice effect) and embarked units (where it may lead to unit stacking problems). therefore i have overridden visibility range for embarked units, i.e. EMBARKED_VISIBILITY_RANGE is ignored if <1.

**Comment by LoneGazebo** [comment]
Oh my. Good work, @ilteroi !
