### ISSUE TITLE
Cannot trade World Map

### ISSUE THREAD

**Issue by ZenyaIse** [LoneGazebo/Community-Patch-DLL#3495]
_1. Mod version (i.e Date - 4/23):_
7-18-1

_3. Error description:_ 
In my recent game I was never ever able to sell or buy World Map (they just refuse without reason). Aren't the prerequisites too tough?
(I remember that I could trade maps in a version about a year ago...)

**Comment by bigcat88** [comment]
Maybe AI already know all u have in Trade Map?

**Comment by LoneGazebo** [comment]
They only trade if it is beneficial to them.

**Comment by ZenyaIse** [comment]
Mmm... But they even refuse to accept my World Map for free. It seems unreasonable.

**Comment by LoneGazebo** [comment]
If they already know more than you do they'll refuse.
