### ISSUE TITLE
Martial Law policy not giving bonuses to Wat

### ISSUE THREAD

**Issue by TooManyCords** [LoneGazebo/Community-Patch-DLL#3496]
_1. Mod version (i.e Date - 4/23):_ 8/23

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Imperialism's 'Martial Law' tenant says 'Constabularies add +1 happiness' - however when I am playing as Siam, whose UB is the Wat (a constabulary replacement offered earlier in the tech tree) this bonus does not apply upon adopting that policy.

Shouldn't it do so? If not, it makes playing Siam wide somewhat more difficult from a happiness perspective.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TooManyCords** [comment]
Okay, now I see a +1 happiness icon next to the Wat in the City Screen. However when I adopted the policy I didn't get the bump I should have.

Perhaps a false alarm, can someone confirm?

**Comment by TechpriestEnginseer** [comment]
The happiness value doesn't update dynamically within seconds, it updates rather within intervals.

**Comment by TooManyCords** [comment]
Seems like typically when I adopt a +happiness policy, eg Equality or Discipline the boost is instant. 

Anyways, feel free to close this one out, the mechanic seems to be working now.
