### ISSUE TITLE
AI not spending faith

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3497]
this is lisbon. the portuguese don't have a their own religion, so they're not spending on missionaries. don't spend their faith on anything else either though:

![image](https://user-images.githubusercontent.com/1358966/30131758-424119a2-934e-11e7-8daf-6de0c00263bd.png)

(they could go for great people as well ...)

**Comment by LoneGazebo** [comment]
Religion log - are they saving up for something ? 


G

**Comment by ilteroi** [comment]
ok, the log says

261, 1966, Portugal, Saving up for a Prophet, as we need to convert Non-Puppet Cities.
261, 1966, Portugal, Saving up for a Prophet, as we need to convert Non-Puppet Cities., Faith: 9607

so it seems they do have a holy city, but have been overwhelmed by the indonesians. maybe a special case. pretty sure they could have bought a prophet for far less, but since they don't have a city with the right religion, they're stuck.

**Comment by LoneGazebo** [comment]
Yeah it is tough to tell the AI when to give up on an owned religion.

**Comment by ilteroi** [comment]
took a look at the code but i don't understand it ... when you buy a prophet, which religion does he adhere to?

**Comment by LoneGazebo** [comment]
your 'currentreligion' which is always your founder religion if you've founded one and still own the holy city.
