### ISSUE TITLE
Road connection to a city with harbor doesn't give a connection to capital

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#350]
![8930_2015-06-22_00014](https://cloud.githubusercontent.com/assets/1131228/8285847/86944f08-191f-11e5-9671-85f5c18461f6.png)

**Comment by LoneGazebo** [comment]
I'll look. Ilteroid messed with this some.

**Comment by ilteroi** [comment]
i suspect this is due to changes in CvCityConnections::UpdateRouteInfo() on March 6th by Gazebo, but it's strange that nobody would notice this for so long.

I don't know what you were trying to achieve, so please take a look yourself.

**Comment by LoneGazebo** [comment]
You sure it isn't related to your rewrite of the 'capital connected' logic in the last update? I haven't touched this since I did it, and I know it has worked since then.
G

**Comment by LoneGazebo** [comment]
(I made that change because villages were losing their route bonus, as the game drew harbor connections first, thus removing land connections).

**Comment by ilteroi** [comment]
my only change was in RouteValid(), which has nothing to with harbors. but maybe it's some weird side effect, i'll check

**Comment by LoneGazebo** [comment]
I'm going to add a third pass to the connection test to have it test land routes again after finding water routes. This may fix.
G

**Comment by ilteroi** [comment]
hmm. desperate measures :)

can you reproduce it? maybe there was a blockade somewhere along the way?

come to think of it, why is there no "blockade" check in WaterRouteValid()?

**Comment by LoneGazebo** [comment]
There is one in the UpdateRouteInfo() function
G

**Comment by ilteroi** [comment]
but only for the city and not for the route. don't know if that's intended. but checking it for every plot would be a performance drag anyway.

while you're at it: the pLoopCity->SetRouteToCapitalConnected(false) in the beginning of UpdateRouteInfo() is also quite inefficient, causes an unnecessary recalculation of the religions, for whatever reason.

**Comment by LoneGazebo** [comment]
Well, there's a belief that looks at city connections.
G

**Comment by ilteroi** [comment]
ok, so that's the reason. but in 99% of cases the current status won't change and we will recompute twice for nothing.

**Comment by Radost** [comment]
Also railroad connection doesn't provide 25% production boost.

**Comment by ilteroi** [comment]
fixed the railroad also. pushed to my repo

**Comment by LoneGazebo** [comment]
Yeah, that's intended - seems like a fair buff.
G
