### ISSUE TITLE
Iron fist gives too much vassal happiness

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#3500]
_1. Mod version (i.e Date - 4/23):_
Aug 23, 2017 build.

_2. Mod list (if using Vox Populi only, leave blank):_

![capture](https://user-images.githubusercontent.com/19291347/30181586-c34e9fae-93e1-11e7-97d0-9bf504441ea1.PNG)

_3. Error description:_ 
Iron Fist increases vassal happiness by too much. (something like 100 happiness)

_4. Steps to reproduce (optional):_
Take Iron Fist policy and pass turn.

[33_bug.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/1285888/33_bug.gz)

**Comment by LoneGazebo** [comment]
code is fine, it just needs to be nerfed.
