### ISSUE TITLE
Scholars in Residence science cost reduction mismatch

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#3501]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Tooltip says -15% cost reduction but the WC resolution itself states a -20% cost reduction and an extra -5% for every CS ally. In the screenshot, I have 3 allied CS. Should be getting -35%

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20170907121839_1](https://user-images.githubusercontent.com/13261433/30182250-c56e1b26-93db-11e7-9c78-628a1fd9234f.jpg)

**Comment by LoneGazebo** [comment]
The Tooltip is not from the WC, it is just the 'natural knowledge' amount.


G
