### ISSUE TITLE
Diplomatic Unit Automation

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3502]
A failsafe should be added that the diplomatic unit automation should at least find the closest city-state to expend themselves within some certain amount of turns because CSD was primarily to localize more city-state influence, but using this automation shows that the AI use this automation as well and these units sometime will travel half the world to ally a city-state only to realize that someone got there first and now their automation is searching for the other half of the world again and the cycle goes on.

**Comment by LoneGazebo** [comment]
It uses the AI routine, I'm not writing a co-routine for it. That's the cost of automation.
