### ISSUE TITLE
Japan's UA gives Faith and Culture instead of Faith and Science

### ISSUE THREAD

**Issue by lorduc** [LoneGazebo/Community-Patch-DLL#3503]
_1. Mod version (i.e Date - 4/23):_
latest

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

as the title.
**_Personal opinion: I think these buildings should give science and culture instead_**

**Comment by LoneGazebo** [comment]
It's just a typo. Culture and faith is correct.
