### ISSUE TITLE
Goddess of Beauty bug + typo

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#3504]
September 7th version

The old effect is still there (wonders from ancient-medieval no longer have a # policy req.
The main screen GUI is also very confusing, not properly taking into account the 3 GA/GE points

![civchinabug](https://user-images.githubusercontent.com/24731508/30213236-6faceac8-94a8-11e7-8fc9-5fca4a3f6dfd.png)

**Comment by RandomNub** [comment]
Commenting this out/deleting it should be enough to fix the bug but I'm quite clueless about the bugged GUI.
...\Sid Meier's Civilization 5\MODS\(2) Community Balance Overhaul\Balance Changes\Beliefs
Pantheons.sql

-- Monuments to the Gods

[...]

UPDATE Beliefs
SET IgnorePolicyRequirementsUpToEra = 'true'
WHERE Type = 'BELIEF_MONUMENT_GODS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET ObsoleteEra = 'ERA_RENAISSANCE'
WHERE Type = 'BELIEF_MONUMENT_GODS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

**Comment by MrFestis** [comment]
Just noticed the GUI discrepancy aswell

**Comment by LoneGazebo** [comment]
Already fixed.
