### ISSUE TITLE
Polynesia:  Galleass upgraded from dromon cannot end turn on ocean, bought/produced can.

### ISSUE THREAD

**Issue by vide0gamer** [LoneGazebo/Community-Patch-DLL#3506]
_1. Mod version (i.e Date - 4/23):_
9/7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
See title.
[Kamehameha_0155 AD-0900.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1289178/Kamehameha_0155.AD-0900.zip)
In save, the three Galleasses nearest Tahiti were upgraded.  The one nearest Nuku Hiva was purchased.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Can you replicate this with the same upgrade-line with all ships that can't end their turn on ocean?

Like say a trireme to a caravel?

**Comment by vide0gamer** [comment]
?  A caravel can cross ocean anyway.  I think dromon to galleass is the only one that is can't cross to can't cross.

**Comment by TechpriestEnginseer** [comment]
Ah that's the problem, the Polynesian promotion for crossing ocean is lost on upgrade or something.

**Comment by vide0gamer** [comment]
Yes, exactly.
