### ISSUE TITLE
Division of Labor

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3508]
_1. Mod version (i.e Date - 4/23):_
last
_3. Error description:_ 
It don't give +5% of prod\gold. But mercantilism does. Like on screenshot.

![20170910082624_1](https://user-images.githubusercontent.com/13381981/30246410-0b62055c-9602-11e7-9279-fd87f9594ef5.jpg)

**Comment by bigcat88** [comment]
And another thing. I don't understand mercantilism.
It says 3% of science and culture from...
But I see only 6% for science buf and 9% for culture.(culture is fine as it should be) Where I lost my 3% of science? Maybe here?
![20170910083631_1](https://user-images.githubusercontent.com/13381981/30246458-74e32014-9603-11e7-9a84-59ccb40a5c6f.jpg)

**Comment by bigcat88** [comment]
Ok, I found it. In file Commerce.sql((2) Community Balance Overhaul\Balance Changes\Policies\Commerce) Line 134(INSERT INTO Policy_BuildingClassYieldModifiers). There are both these bugs.

**Comment by TechpriestEnginseer** [comment]
![image](https://user-images.githubusercontent.com/13937047/30247704-b6fdf922-95ce-11e7-8cb7-33bd52632880.png)
Gazebo also forgot to delete those yields.
