### ISSUE TITLE
Social Realism order tenet gives free public schools

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#351]
Instead of free museums.

**Comment by LoneGazebo** [comment]
Ah that's by design, but I forgot to edit the text! Damn.

**Comment by Radost** [comment]
Also Academy of Sciences gives free universities instead of public schools.
It's pretty strange level 2 tenet provides lower grade buildings than level 1 tent.

**Comment by LoneGazebo** [comment]
Yep fixed both. Was typo on my end.
G

**Comment by Radost** [comment]
Moreover, Academy of Sciences overwrites Social Realism and removes free public schools.
