### ISSUE TITLE
Crash on game load

### ISSUE THREAD

**Issue by lilmaddiekins** [LoneGazebo/Community-Patch-DLL#3510]
_1. Mod version (i.e Date - 4/23):_ 9/7 with 43 civs

_2. Mod list (if using Vox Populi only, leave blank):_

![image](https://user-images.githubusercontent.com/25156282/30282496-52195720-96ca-11e7-98ee-6ae9207dcb38.png)

_3. Error description:_ 

Crash on game load

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1293056/CvMiniDump.zip)
[Nebuchadnezzar II_0133 BC-0675.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1293059/Nebuchadnezzar.II_0133.BC-0675.zip)

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
Try it without FAA or unique city-states.

**Comment by lilmaddiekins** [comment]
It won't let me load this game without those mods enabled/installed.  Is there a trick to do that?

I have played other saved games with these mods enabled without any issues.

**Comment by LoneGazebo** [comment]
No, there's no trick. Try loading an earlier autosave.
