### ISSUE TITLE
MP desyncs with Barbarians again:( 

### ISSUE THREAD

**Issue by InapropriateUsername** [LoneGazebo/Community-Patch-DLL#3511]
1. Mod version: 9-7-2

_2. Mod list (if using Vox Populi only, leave blank):_
Unit path viewer
Flag promotions
Improved City View

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Well the bug is well-known, if anything else is needed - let me know

**Comment by LoneGazebo** [comment]
try it w/o the other mods.

**Comment by InapropriateUsername** [comment]
But it worked with this mods in previous versions...

Anyway, tested, doesn't work

**Comment by LoneGazebo** [comment]
Logging enabled? If so, send the net logs from your logs folder.

@ilteroi the only possibility I can think of is that changes to pathfinder caching, or tactical caching, are affecting barbarian play. If we rule out RNG (and we should, as barbs always use the spoofed RNG) that really only leaves things like the tactical AI.

**Comment by ilteroi** [comment]
bleh. very hard to debug this. don't have any idea

**Comment by LoneGazebo** [comment]
Likewise. Without logs, there's really no easy way to know what is causing it. I've got two windows machines, might try some testing on my end on LAN.

**Comment by ilteroi** [comment]
you could try and disable MOD_CORE_CACHE_REACHABLE_PLOTS, see if that makes a difference

**Comment by InapropriateUsername** [comment]
I,ll do logs tomorrow, today I'm drunken

**Comment by InapropriateUsername** [comment]
Hey, i have logs! There is a lot of "unit out of sync" messages
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1304159/Logs.zip)

**Comment by ilteroi** [comment]
can you please enable random logging in civ.ini on both machines? pregame logging is probably not needed, but there should be a file called RandCalls.csv 

@G: probably also need a build with MOD_CORE_DEBUGGING enabled and no optimizations (to see the proper stack traces).

we also could make this warning: "GUI is accessing the synchronous random number generator while the game core is running" visible to the user. Maybe a MsgBox?

**Comment by LoneGazebo** [comment]
@ilteroi I did make it so that the barbarians cannot access the RNG seed (they use the fake number) throughout the DLL. I think the fact that the barbarian RNG use seed does not propagate to the client correctly is what is causing the desync. Limited testing at home with 2 PCs running MP on LAN shows that this change has eliminated resyncs (only tested first 50 turns, but that's also heavy barb time).

**Comment by ilteroi** [comment]
seems like a hack but fine with me :)

**Comment by LoneGazebo** [comment]
if it works, it works

**Comment by MoiMagnus** [comment]
Does that mean that the advanced option to reroll the random seed when loading a game no longer works for barbarians ?
(If yes, is it MP only or MP and SP ?)
That's not a problem if that's the case, but I'm curious.

**Comment by LoneGazebo** [comment]
Correct. Barbs now no longer touch the seed.
