### ISSUE TITLE
Denmarks UA 25% cs on pillaged tiles

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#3512]
_1. Mod version (i.e Date - 4/23):_

8/23modpack- singleplayer game
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I dont see that 25% cs on pillaged tiles anywhere. 
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20170911235612_1](https://user-images.githubusercontent.com/21192402/30298973-d47fc798-974d-11e7-8a50-c64deea2aad6.jpg)

**Comment by LoneGazebo** [comment]
It increases your base strength, it is not a % modifier per se.

**Comment by matlajs** [comment]
so it is invisible bonus.is it attack on pillaged tile or from?

**Comment by matlajs** [comment]
aha ok. close this. i missed that, usually just look at dmg output.
