### ISSUE TITLE
Vassals Screen Text Bug

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#3514]
_1. Mod version (i.e Date - 4/23):_
8/26

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

The conditions for vassals to liberate themselves have the wrong text, from the way the game works for me it should read instead:
1. Vassal for x turns (depending on game speed)
2. One of the following conditions
a) Vassal City count LESS than 75% of initial count ----- not "more" as it says
b) POPULATION count more than 300% of inital count ----- not "City" count as it says
c) [is correctly stated I think]

This is pretty confusing for new players since the text description is simply wrong and it takes some time to figure out what is going on.
How do I know this is wrong? a) only turns green when city count is less (i.e. the master has not adequately protected his vassal) and it also doesn't make sense otherwise since it would be the same as b) only active much sooner...b) is supposed to be Cities not Population since this is the value it shows...can be verified by looking at the value below that description in the menu or in EUI or by checking when it turns green

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
b is correct, actually. I'll fix a.

**Comment by UndeadDevel** [comment]
Now playing version 9/17 and while a is fixed, b is still wrong...please check again!
For me it reads as this:
`
a) Vassal's team has 75% or less of Cities when vassalage started
b) Vassal's team has 300% or less of Cities when vassalage started
`
see the problem? a) is a subset of b) so it doesn't make sense. 
Also, the numbers shown to the right of the sentences "(currently xxx)" are different numbers for a) and b); the number next to a) corresponds with the "Current City Percent" in the vassalage screen and this seems to be correct when checking in game; the number next to b) corresponds to the "Current Population Percent" in the vassalage screen and this also seems to be correct when checking other info in game. This is why the sentence will turn green and the "Can declare independence" part turns to "Yes" when the Population reaches 300% of the original value when vassalage started.
Furthermore, the reason for b) as it should be is that it signifies that the civilization is now much larger than it was and with increasing maturity is clamoring for sovereignty, which is plausible.

**So, I reiterate the OP: b) should read "Vassal's team has 300% or more of Population when vassalage started."**

I should also mention that I never had a vassal attempt to declare their independence before so I don't know whether the code that this text is supposed to describe is actually correct and reflects the what the text implies (maybe that's the real problem here and not the text?).

**Comment by LoneGazebo** [comment]
I see the issue - the lua in the DLL was wrong (duped text). Fixed for b.) It looks correct in XML which is why I didn't change it there.

G
