### ISSUE TITLE
Archaeology Site Misnomer

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#3515]
_1. Mod version (i.e Date - 4/23):_
8/26

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Okay this one is really a tiny bug:
Archaeology sites are often found on the tiles where cities were razed earlier in the game (which is awesome) but they always display the wrong text. Specifically they always confuse the founder of the city with the conqueror (in the little screen that pops up to choose what to do with the site once an Archaeologist has excavated it). At first I thought that maybe it's just a random choice but since I started paying attention it always lists the civs that were actually involved in that conflict and it always confuses the founder with the conqueror. I know this is really minor but since this modpack is nearing completion it might as well get fixed to increase immersion in the game and stop the game from spreading alt-history fake news propaganda about past war atrocities ;)

_4. Steps to reproduce (optional):_
Raze some cities.
Play until discovering Archaeology.
Excavate site where city was razed.
Founder and Conqueror descriptions are switched with respect to the actual (game-)historical context.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Sad.
