### ISSUE TITLE
Limited follower beliefs?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3517]
When choosing a religion (the first to found) it seems there is a cap of beliefs in the lua. So certain beliefs cant be seen and picked until other religions are founded. However Byzantine UA does not have this cap in their bonus belief panel.

So you might not see the additional beliefs added via external mods if you were the first to found your religion since there seems to be a limit somewhere.

**Comment by LoneGazebo** [comment]
Did you figure this out?

**Comment by TechpriestEnginseer** [comment]
Faulty Lua issue.
