### ISSUE TITLE
Events Updates

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#3518]
@TechpriestEnginseer 
I noticed following a flood triggering in my game today that you have added non-pillage options to that set of bad city events. It didn't seem like the alternative lose yield option was anywhere near punishing enough. You might want to up the numbers.

Oh and also they didn't have any flavor text. It was just "pestilence" or "pestilence curbed".

**Comment by Hokath** [comment]
Actually the more I compare with positive events, these numbers seem alright. Guess the pillage really feels worse than it is.

Point on the text stands

**Comment by TechpriestEnginseer** [comment]
I could have swore I replied to this already.... You can do a pull request to the events if you want. I think the yields are fine. They can potentially shave off 7 turns off a citizen's growth or 2 turns off that important wonder that the AI was also getting in 1 turn.

**Comment by Hokath** [comment]
Makes sense. I'll write some text and send a pull.

Are we anywhere closer to modmod integration?

**Comment by TechpriestEnginseer** [comment]
Modmod integration? Probably very unlikely going to happen with just the two of us and I would rather just integrate basic events that ppl just enjoy for fun instead of civ or ideological events into the main mod itself.
