### ISSUE TITLE
Non-dismissable Monopolies screen appears on saved file reload

### ISSUE THREAD

**Issue by purplecucumber** [LoneGazebo/Community-Patch-DLL#3519]
_1. Mod version (i.e Date - 4/23):_

15 Sept most recent

_2. Mod list (if using Vox Populi only, leave blank):_

Vox Pop full install+ Smart AI

_3. Error description:_ 

When loading a saved game after exiting the game, the monopoly/corporations screen appears and is non-dismissable. Not really a crash, but you can't continue playing behind the menu. 

_4. Steps to reproduce (optional):_

1. Save game (no obvious conditions around game length or type, has happened every time since the most recent two patches)
2. Exit Civ
3. Restart Civ
4. Load just saved game
5. Select continue from civilisation flavour text overlay
6. Corporations screen will load
7. Close button does not work, nor does any other obvious way of removing the screen

**Comment by LoneGazebo** [comment]
Enable logging and post the Lua log from when you load the save.

**Comment by ashendashin** [comment]
He's using Smart AI.

@purplecucumber VP has the community patch, which has its own dll that both mods state should not be replaced.

**Comment by purplecucumber** [comment]
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1309242/Lua.zip)

Will stop running Smart UI alongside but I don't *think* the clash is causing this issue, my limited technical knowledge looking at the logs suggests it's a VP thing but happy to be told otherwise.

**Comment by LoneGazebo** [comment]
If you are using another DLL mod they will not work together.

G
