### ISSUE TITLE
Can't attack a city with civilian unit from another non-hostile civ stationed inside

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#352]
![8930_2015-06-23_00009](https://cloud.githubusercontent.com/assets/1131228/8305244/9a9ffe78-19c6-11e5-8a81-5976ff94fcab.png)
![8930_2015-06-23_00010](https://cloud.githubusercontent.com/assets/1131228/8305245/9aa047fc-19c6-11e5-998f-6291499d671c.png)

**Comment by LoneGazebo** [comment]
This was fixed once before, not sure why it is back. I'll look.
G
