### ISSUE TITLE
Building still invested after an event destroyed it

### ISSUE THREAD

**Issue by lilmaddiekins** [LoneGazebo/Community-Patch-DLL#3520]
_1. Mod version (i.e Date - 4/23):_ 9/15 beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ I can't demonstrate via a save game but my city was hit by a hurricane, council was destroyed but was still invested from the first time I built it

_4. Steps to reproduce (optional):_

**Comment by TechpriestEnginseer** [comment]
Can be easily reproducable with IGE.
