### ISSUE TITLE
Food gone from the city tiles for all cities

### ISSUE THREAD

**Issue by Rafs041** [LoneGazebo/Community-Patch-DLL#3521]
_1. Mod version (i.e Date - 4/23):_
9-7-2

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi + InfoAddict (v22)

_3. Error description:_ 
All my cities lost the food they produce (took me a while to notice to be honest...), so I'm not getting the base food from terrains (2-3 food), nor the food from complete fealty (6 food), nor food from allied/friendly maritime city states either.

_4. Steps to reproduce (optional):_
First time it happens, sorry I can't be of more help.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1312502/Lua.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20170919002323_1](https://user-images.githubusercontent.com/19327087/30567764-25cbe6a2-9cd2-11e7-90d7-2dd0a28095a8.jpg)
![20170919002337_1](https://user-images.githubusercontent.com/19327087/30567768-29daf878-9cd2-11e7-82bc-2a7a830b4d3f.jpg)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1312502/Lua.zip)

**Comment by LoneGazebo** [comment]
You probably got hit with a bad event or something and didn't notice.

**Comment by Rafs041** [comment]
Hello Gazebo,
I only play with Good events on ,no bad or neutral (because the constant pillaged tiles on big empires make it rather annoying for me with neutral and bad events on). Any idea what could be causing this? As I've said its rare because I've played a lot of games and it's the first time.

**Comment by LoneGazebo** [comment]
Possible that the amount of food on the tile exceeds the yield max for the tile. Any other mods?

**Comment by Rafs041** [comment]
Only InfoAddict (v22) on top of Vox Populi.

**Comment by LoneGazebo** [comment]
Can't reproduce, sorry.
