### ISSUE TITLE
Featurequest- Option to turn off bonus yield notifications. The notification area is very crowded in wide play.

### ISSUE THREAD

**Issue by preyator** [LoneGazebo/Community-Patch-DLL#3522]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bryan317** [comment]
If it where actually possible to restrict certain ones that would be great. 20+ notifications that a citizen was born or border expand is a bit annoying.

**Comment by LoneGazebo** [comment]
Not feasible. Already condensed as much as the UI allows. Blame firaxis for a terrible UI concept.

**Comment by bryan317** [comment]
Thanks as always G!

**Comment by preyator** [comment]
I am not talking about disabling specific bonus yield notifications. Isn't it possible to disable all bonus yield notifications?

**Comment by LoneGazebo** [comment]
No.
