### ISSUE TITLE
Yields Bonus from unrevealed resources coming from other sources

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#3523]
_1. Mod version (i.e Date - 4/23):_
Current

_2. Mod list (if using Vox Populi only, leave blank):_
Unique City States

_3. Error description:_ 
Come frome [here](https://forums.civfanatics.com/threads/unique-city-states.607883/page-7#post-14868799). As suggested by @TechpriestEnginseer (in case can be a DLL problem) I inform that when Zanzibar (+1 gold to resources) alliance is active, gold bonus is being given to all resources, revealed or not.

![imagen](https://user-images.githubusercontent.com/13163824/30587952-450bbc32-9d35-11e7-8606-93b900c1ea9d.png)

![imagen](https://user-images.githubusercontent.com/13163824/30587993-5f8085c0-9d35-11e7-881c-1401f35176aa.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@enginseer sounds like an issue with unique city states.

**Comment by TechpriestEnginseer** [comment]
Disagreeable this occurs with all event effects and unrevealed resources.

**Comment by LoneGazebo** [comment]
Hold on. This IS triggered by your mod. But I don't know how you trigger your unique city states stuff via the CP. Using events? buildings?

**Comment by TechpriestEnginseer** [comment]
UCS is triggered via dummy event choices. When someone is allied with Zanzibar. Zanzibar lua sends an event choice effect to the ally.

**Comment by TechpriestEnginseer** [comment]
Zanzibar event choice effect adds 1 gold to all resources.
