### ISSUE TITLE
Temple of Artemis 

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#3524]
The latest beta thread was going in a different direction, so I thought I would copy this comment by Ziad here so it doesn't get lost. In short, I agree that the granary now feels out of place.

> Hey Gazebo, I have a question that has been bugging me for a while.
> 
> Why is Temple of Artemis the only wonder to provide a building from a previous tech tier?
> 
> Presently the only way to mitigate the loss of building a Granary is to focus on expansion and military before building the wonder. However for those who start with Tradition, it can be an annoyance as Granary is somewhat of a priority to support the specialists, especially when you have Wheat/Deer/Bison/Bananas nearby. 
> 
> It just takes A LOT of time to research a tier 2 technology for a tier 1 building from a tech that isn't even a prerequisite!
> 
> Wouldn't it be better for it to provide a free Barracks, at least for consistency with all the other wonders in that era that provide buildings from the same tech/tier? Think of it as training soldiers in the hunt rather than storing meat from said hunts

**Comment by LoneGazebo** [comment]
That's a balance question not a bug. Bounce it back to the forums.

**Comment by Hokath** [comment]
Yes boss
