### ISSUE TITLE
Galleasses able to enter Ocean tiles

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#3525]
17th September Beta

![civnedbug3](https://user-images.githubusercontent.com/24731508/30620822-f5ca003e-9da7-11e7-8b20-618fc2175c30.png)

They somehow lost the 'cannot enter ocean' promotion, I think it triggered upon researching Astronomy but not sure. Happened vs multiple civs.

**Comment by lilmaddiekins** [comment]
I think it's only those upgraded from dromon that can do it.

**Comment by RandomNub** [comment]
fun fact, they gain back the promotion once stolen with a sea beggar :D

**Comment by LoneGazebo** [comment]
Isn't it 'cannot enter until astronomy' anyways?

**Comment by LoneGazebo** [comment]
If so, that's WAD.
