### ISSUE TITLE
CS unit not attacking, not healing, just standing in place

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3528]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Title explains, look at the warrior of a CS near the barbie camp.
[warriorIsabella_0061 BC-2475.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1319336/warriorIsabella_0061.BC-2475.zip)

**Comment by LoneGazebo** [comment]
I think @ilteroi 's latest bugfixes may have helped...
