### ISSUE TITLE
AI makes odd city razing evaluations 

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#3529]
_Mod version (i.e Date - 4/23):_
9/17 beta

_Error description:_ 
The AI seems to make odd choices when choosing whether to keep or raze a city.

---------------------------
Supporting information:

Here Persia managed to capture a pretty great city from the Maya (they may not know the coal is there, but the Kunas and Town still make it compelling), yet they raze it despite having a fairly average empire
![](https://i.imgur.com/mmPHKoR.png)
![](https://i.imgur.com/C8xMxt4.png)

Then, when I approached them willing to take the city off of their hands, they evaluate it as 'impossible'
![](https://i.imgur.com/UBomwTB.png)

And again from version 9/7, China takes a pretty great city from Rome with several great person and unique improvements, but decides to raze it (They also most likely haven't discovered coal).
![](https://i.imgur.com/UF4bEfI.png)
![](https://i.imgur.com/nZdOQ6J.png)

I can understand them wanting to avoid giving another civ more power, but if they think the land isn't even worth puppeting I would expect them to accept _something_, if not from me then from another civ.

**Comment by ilteroi** [comment]
just took a look at the code, if the AI is very unhappy (<-10) they will burn any city, no matter how good it is ... there used to be a piece of code which stopped razing if unhappiness had become better, but i can't find it anymore. strange.
