### ISSUE TITLE
"Cannot steal great work" text notification 

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#3530]
_Mod version (i.e Date - 4/23):_
9/17 beta (Non-EUI)

_Error description:_ 
Text key error for the "Spy can't steal great work" notification

![](https://i.imgur.com/z1glOAO.png)

**Comment by LoneGazebo** [comment]
Getting any database errors?

**Comment by bigcat88** [comment]
I have the same issue in previous versions.

**Comment by bryan317** [comment]
I have seen this.  But I've also had a severely glitched out game.  Will be full reinstalling before playing a new game.

**Comment by HalfEmptyMug** [comment]
I'm not sure. This should be the database file from when this occurred, but nothing seems out of the ordinary.
[Database_log.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1322519/Database_log.zip)

**Comment by ZenyaIse** [comment]
I have the same issue.
Version 7-18-1

**Comment by HalfEmptyMug** [comment]
I'm still getting this issue in the latest version, but I think the issue is beyond just the text-key:

Here, after attempting a heist and receiving the same broken notification, the thief is shown as "Disrupting plans" despite there being several great works in the city to steal (and plenty of slots in my empire to fill).
![](https://i.imgur.com/ngdJr6B.png)

Then, nearly 70 turns later, the thief is still "Disrupting plans" depite the same great works being in the city.
![](https://i.imgur.com/QdKcdFI.png)
 
Switching out spies has the same result, but the notification appears immediately after establishing surveillance. Oddly enough though, assigning a spy to a different city I haven't attempted to steal from yet has the spy properly preparing for a heist.
![](https://i.imgur.com/tiZoiaD.png)

**Comment by LoneGazebo** [comment]
@HalfEmptyMug posting in a closed thread doesn't always show notifications, just FYI.

**Comment by LoneGazebo** [comment]
I tested this out earlier but didn't test it in the way you did - I'll see if I can replicate.

**Comment by matlajs** [comment]
interesting. he closed my own thread here with same problem with words ,, it seems fine to me'' probably it is not?

**Comment by LoneGazebo** [comment]
>he closed my own thread here with same problem with words ,, it seems fine to me'' probably it is not?

> **I tested this out earlier but didn't test it in the way you did**

One of these statements came after the other...

**Comment by matlajs** [comment]
so again my question. is an AI able to steal great works from capital? because it did in 9/7 version. weird things happen arround this feature. really. sometimes i complain about problem that i realise after awhile was my mistake, but this is not the case. a say to you, that i have lost gw of art from capital, while notification said, that it has been stolen from another city and i am sure i did not have two such notification on same turn and i did not lack anything in a city, which notification talked about.

**Comment by bigcat88** [comment]
I have a slightly different missing notifications(but sometimes they are displayed fine)(last version):
![20171012141425_1](https://user-images.githubusercontent.com/13381981/31494455-0889a2f4-af5c-11e7-985b-46f63050013c.jpg)

**Comment by LoneGazebo** [comment]
AI cannot steal great works from capital, no.

**Comment by LoneGazebo** [comment]
I think I've got it sorted now, we'll see.
