### ISSUE TITLE
Freeze/Crash: City States expanding

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#3531]
I twice experienced a game freeze upon Ragusa turn, the first turn after it expanded (and puppeted) into another city. 

![civnedcrash](https://user-images.githubusercontent.com/24731508/30692199-c532caae-9eca-11e7-93fe-cc644311da42.png)

Here I checked with IGE and it looked like Ragusa was 1 turn away from training a musketman, maybe it conflicted with Kilimangaro's Altitude Training promotion? The city was mine the turn before.

![civnedcrash2](https://user-images.githubusercontent.com/24731508/30692288-259eb79a-9ecb-11e7-873e-7f526de2771c.png)

Here instead I conquered the city from the Iroquis 2 turns before, they liberated it but then Ragusa sneaked with a corvette and conquered it for itself. 

Both times the debug stops at this line, with the game evaluating city states turn and me having to close CiV from the task menager:
[160490.812] DBG: changeNumGameTurnActive(1) m_iNumActive=1 : setTurnActive() for player 57 Ragusa

Both conquered cities were small and had just 1 turn resistance that disappeared just before the freeze. Fwiw Hong Kong many turns earlier expanded into an enemy city (a bigger one, in case resistance plays a factor) just fine so it's not a general issue.

Saves in the following .rar (only mod, last september beta):

https://www.dropbox.com/s/647ddq5vdsnm5in/CScrashes.rar?dl=0

**Comment by RandomNub** [comment]
Update: went back some turns and avoided taking Montreal, Ragusa conquers it on its own, 2 turns passed and then game froze again, stuck processing Ragusa turn forever.

**Comment by LoneGazebo** [comment]
I can't load the save, unfortunately. I'll keep an eye out for this to reproduce again.
