### ISSUE TITLE
Promise not to buy land is a negative diplo modifier

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#3533]
![2capture](https://user-images.githubusercontent.com/19291347/30733152-c1ec3be0-9f43-11e7-96e8-514c5aa13b0c.PNG)

I remember this from a long time ago but never reported it.  The modifier is like -x points where x is the number of remaining turns.

I think this is a bug because other promises (troops just passing by, not spying) do not have the same line on the diplo screen.

**Comment by bigcat88** [comment]
I think just other promises must be displayed in such way as this promise.
Cause when u promise to move troops from borders, after some turns later u need to do save and check if promise was forgotten.

**Comment by LoneGazebo** [comment]
It is not a negative modifier, the 'transparent diplomacy' is just showing you the promise duration.
