### ISSUE TITLE
New Deal tenet from Freedom doesn't work

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#3534]
Too lazy to post file and such.  Will post if requested.

**Comment by TechpriestEnginseer** [comment]
What exactly doesn't work?

**Comment by jimmymcperson** [comment]
My great people improvements do not gain more yields (Town, Academy, Citadel).

**Comment by HalfEmptyMug** [comment]
Do you have a screenshot? I just used the policy and it seems to work fine.

**Comment by jimmymcperson** [comment]
Alright I'll just do the report properly.

_1. Mod version (i.e Date - 4/23):_
9-17 beta

_2. Mod list (if using Vox Populi only, leave blank):_
![ahhh](https://user-images.githubusercontent.com/19291347/30771130-2e084fa6-a00e-11e7-8ba8-1313b65e3c5b.PNG)

_3. Error description:_ 
New Deal does not grant increased yields.

[Logs.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/1326352/Logs.gz)

Try picking up new deal in this save.  It doesn't do anything even after you pass a turn with it.

**Comment by TechpriestEnginseer** [comment]
I really can't replicate this in any new games. You must have a faulty installation with that save.

**Comment by jimmymcperson** [comment]
It may be worth noting that the World congress policy for great improvements is in place.
