### ISSUE TITLE
Not gaining majority religion

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#3535]
1. Mod version (i.e Date - 4/23):
9-17 beta

2. Mod list (if using Vox Populi only, leave blank):
![ahhh](https://user-images.githubusercontent.com/19291347/30771158-c84fbf04-a00e-11e7-8004-f0fea7e90c56.PNG)

3. Error description:
Not gaining majority religion even when all my cities are of that religion.  (Cannot buy Great Prophets)

![ahhh2](https://user-images.githubusercontent.com/19291347/30771264-0245bc16-a011-11e7-984c-150845a0051b.PNG)

![ahhh](https://user-images.githubusercontent.com/19291347/30771182-1902b41a-a00f-11e7-978d-3fbb59509b6a.PNG)

[Logs.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/1326356/Logs.gz)

**Comment by LoneGazebo** [comment]
You don't get a majority religion like that unless you own the holy city.
