### ISSUE TITLE
How do AIs react if a Unique Great Admiral gets a potential Improvement?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3536]
I know the Roman Legion was able to utilize their improvement properly, but how do exactly do unique Great Admirals from other "civs in the workshop" function if they have 3 orders to either: Lead like a Great General, Repair a Fleet in devastation, or Take a Voyage.

Now I know there are 2 Unique Great Admirals that give them the option to build a unique improvements in the Workshop.. but I'm unsure how the CP AI is able to use them or will they over-use them over their 3 regular orders.

**Comment by LoneGazebo** [comment]
GPs use a special set of hard-coded functions in CvPlayerAI to determine ability usage like that. So, no, it won't know what to do.

G
