### ISSUE TITLE
More problems

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#3537]
_1. Mod version (i.e Date - 4/23):_
9/7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
a)Goddess od beauty pantheon(adopted, not found myself) does provide +2F only to Palace and GW, not ty WW.
b) why could Sweden found a city like this? 
![20170923212439_1](https://user-images.githubusercontent.com/21192402/30777370-38482e7c-a0b9-11e7-9f5e-6726c609eb4b.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HalfEmptyMug** [comment]
Regarding Sweden: a city can be settled within 4 tiles of another city if they are both on separate landmasses.

**Comment by paramenides** [comment]
Yeah, this is expected behavior. Check the iron.

**Comment by matlajs** [comment]
,,Regarding Sweden: a city can be settled within 4 tiles of another city if they are both on separate landmasses.''   Thanks for info. I didn't know a rule about diferent landmass.

**Comment by matlajs** [comment]
Should I get +2F from world wonders from adopted Goddess of beauty?

**Comment by LoneGazebo** [comment]
You are getting it, it just isn't showing up in the tooltip.
