### ISSUE TITLE
GP Improvement Issue

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3538]
Tradition Finisher does not grant +1 Food to Embassy.
Knowledge Through Devotion does not grant +3 Faith/+1 Culture to Embassy(Although it would be +4 Faith/+4 Science now?)
New Deal does not grant anything to Citadels. Perhaps it should grant that unused "appropriate" Great General Points? ;)

Do we consider Paper a strategic resource? Should Zealotry amplify that?

**Comment by LoneGazebo** [comment]
No, Paper doesn't count towards it.
