### ISSUE TITLE
Antiquity Sites notifications are duplicated

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#354]
![8930_2015-06-23_00001](https://cloud.githubusercontent.com/assets/1131228/8305372/c88cc518-19c7-11e5-9095-3db130e382f6.png)
![8930_2015-06-23_00002](https://cloud.githubusercontent.com/assets/1131228/8305371/c88c9c28-19c7-11e5-8221-1449b63c7309.png)
There were only nine sites.

**Comment by LoneGazebo** [comment]
That sounds like an EUI notification bug, not a CP/CBP bug. I don't mess with sites at all.
G
