### ISSUE TITLE
Hagia Sophia prophet spawn bug

### ISSUE THREAD

**Issue by eddwilliams** [LoneGazebo/Community-Patch-DLL#3541]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Hagia Sophia spawning missionaries on city conquest

_4. Steps to reproduce (optional):_
India conquers Venice eliminating them from game; liberate Venice but immediately on capture am left with 3 missionaries of Venice's religion. India conquers Venice again, process repeats indefinitely,

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I don't exactly understand, as 'one-shot' bonuses only fire once from wonders. Are the missionaries from venice persisting after it is killed? Do you have complete kills turned on?

**Comment by eddwilliams** [comment]
Its happening on city capture, I liberate the city but end up with 3 missionaries despite never actually owning it... the india recaptures, i liberate, 3 more missionaries

**Comment by LoneGazebo** [comment]
Who are you playing as? The Hagia Sophia doesn't provide missionaries like that.
