### ISSUE TITLE
Broken modifier for military threatening

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#3542]
_1. Mod version (i.e Date - 4/23):_
9/27

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I have got this broken promise modifier with civs, that i haven't met when i broken my promise? is that right?
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20170929181634_1](https://user-images.githubusercontent.com/21192402/31025601-715ef4b4-a543-11e7-90a7-aab0e187af41.jpg)
![20170929181644_1](https://user-images.githubusercontent.com/21192402/31025604-73f205fe-a543-11e7-829a-815de168c103.jpg)
![20170929181648_1](https://user-images.githubusercontent.com/21192402/31025606-75d7bfee-a543-11e7-9e50-5507ab4dc1e5.jpg)
![20170929181656_1](https://user-images.githubusercontent.com/21192402/31025608-7789cb52-a543-11e7-9472-6ebda1d08466.jpg)

**Comment by LoneGazebo** [comment]
Sounds like you broke a promise.

**Comment by matlajs** [comment]
I did, but should it apply on recently discovered civs?

**Comment by LoneGazebo** [comment]
Yes. All are told of your sins :)

**Comment by matlajs** [comment]
Ok, how long will that last? hope it isn't same like do not settle close :D  Also, i think these matters of broken promises should be internal matter. But ok.

**Comment by jimmymcperson** [comment]
Broken promises of military threat will last forever for all civs, even if discovered afterwards.

**Comment by matlajs** [comment]
and for how long i can not attack to not get this?after telling lie ofc.

**Comment by LoneGazebo** [comment]
50 turns IIRC.
