### ISSUE TITLE
Workers constantly ask for orders when building roads

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3543]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Title says it all. The bug was there a few versions ago and it seems to have returned - after I tell a worker to build a road from X to Y, he will often ask me what to do every tile.

**Comment by pandasnail** [comment]
Well, workers wake up whenever a Barb unit can capture it, whether the player can see the Barb or not. Are you sure you're not just building roads within six or so tiles of a fancy promo Horseman sitting in a barb camp?

**Comment by Enrico-Swagolo** [comment]
Not the case, it's for every tile of road from what I see.

**Comment by ilteroi** [comment]
confirmed ... but i can't fix it right now, i need G to push his latest code first :)

**Comment by LoneGazebo** [comment]
Latest was/is 9-27, though I made a small hotfix (that only affected the CBO). What else do you need?

**Comment by ilteroi** [comment]
nothing, but 9/27 wasn't on the public repo until just now

**Comment by ilteroi** [comment]
hmm. can't reproduce it now. seems to happen only sporadically, usually that's a bad sign

**Comment by ilteroi** [comment]
should be better now
