### ISSUE TITLE
Air Unit Kamikaze feature or bug?

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#3544]
_1. Mod version (i.e Date - 4/23):_
9/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Bombers attacking one of my cities seem to do much more damage than they should, but only if they die on interception. Detailed description:
- Annexed city with some fighters on intercept mode stationed in it, no nearby AA units; buildings relevant to air units in city: none (NO Airport, NO Military Base, NO Bomb Shelter); city is only slightly damaged and has courthouse (no resistance).
- after binding all my interceptors with clever Triplane Sweeps the AI attacks the city with a few Bombers and does moderate (normal) damage.
- in the next turn I keep all fighters on intercept to prevent this from happening again; AI this time does not sweep but attacks with a single Bomber only; the Bomber is shot down but damages the city anyway with a LOT of damage (approx. 5 times the damage a single bomber was doing before); this happens again in the next turn.

Question: is this some new feature that makes Kamikaze style attacks happen when air units are shot down or is it a bug? If it is intentional I believe the damage is WAY to big...also, the game presented a text message during the attack (the simple screen overlays that disappear after a few seconds) writing something about more than 1000 damage though I wasn't quick enough to read it.

Another Bomber that my interceptors shot down attacked a unit and also did quite a bit of damage though not crazy amounts...I thought Bombers or Fighters that get shot down are not supposed to do much damage, they are breaking apart during the attack after all.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
you can re-read the notifications by hovering the mouse over the notification icon in the top right corner (the scroll)

can you please retest this and post a screenshot?

**Comment by UndeadDevel** [comment]
I was able to load an autosave from before the attack but unfortunately the notifications were gone and I wasn't able to reproduce the attack since I don't remember exactly how I had moved my units and India didn't attack the city like that again. However, I managed to capture another attack that I think shows the same problem:
Behold my Panzer with full health
![civ5screen0011](https://user-images.githubusercontent.com/30495439/31133735-97f7f984-a860-11e7-9847-67d8f00e87e1.jpg)

It was attacked by a single Bomber (the weak, earliest version in that tier) which was shot down on attack without being attacked by anything else as you can see in the log:
![civ5screen0008](https://user-images.githubusercontent.com/30495439/31133902-078e5158-a861-11e7-9f2e-1ea5df442cc6.jpg)

Behold the result (this is when the notification in the previous screenshot was generated):
![civ5screen0006](https://user-images.githubusercontent.com/30495439/31134016-52ca1bf2-a861-11e7-93b3-ad2eff8070e8.jpg)

and just to show the exact HP after this one attack:
![civ5screen0009](https://user-images.githubusercontent.com/30495439/31134092-86597788-a861-11e7-86c7-865018886d1a.jpg)


So one Bomber that was shot down on attacking my Panzer dealt so much damage (78) that it almost killed this very strong late game unit (75 CS). Unfortunately the notification didn't show any damage numbers but I swear that it showed something with 1600 damage when my city was attacked (the attack I wasn't able to reproduce now) although the actual damage was more like 100 (which is still way too much IMO especially if the air unit is shot down).

Let me know if you need further info...

**Comment by LoneGazebo** [comment]
@ilteroi should

int iAttackerDamageRatio = GC.getMAX_HIT_POINTS() - ((getDamage() - iAssumeExtraDamage) * iWoundedDamageMultiplier / 100);

be int iAttackerDamageRatio = GC.getMAX_HIT_POINTS() - ((getDamage() + iAssumeExtraDamage) * iWoundedDamageMultiplier / 100);

?

(Line 16736 of CvUnit.cpp)

**Comment by ilteroi** [comment]
yes indeed
