### ISSUE TITLE
CS unit doesn't heal despite being fortified

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3545]
_1. Mod version (i.e Datc - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The title doth explain it.
[rigaBismarck_0041 BC-2975.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1346675/rigaBismarck_0041.BC-2975.zip)

**Comment by ilteroi** [comment]
can't load the save ... but can't reproduce it either. which type of unit is it? does is require a strategic resource?

**Comment by Enrico-Swagolo** [comment]
I think it was a warrior.

**Comment by Enrico-Swagolo** [comment]
I've seen that near a barbie camp I think? The CS warrior was near that.

**Comment by Enrico-Swagolo** [comment]
Also I forgot to mention the warrior unit was completely adjacent to a barbie camp. I think outside the CS territory.

**Comment by ilteroi** [comment]
hmm. melee barbarian or ranged barbarian? anyway a CS unit should not just be camping out there ...

**Comment by Enrico-Swagolo** [comment]
melee, brute

**Comment by ilteroi** [comment]
doesn't seem to be very common, but i applied some tweaks just in case. propose to close this and open a new one if required

**Comment by Enrico-Swagolo** [comment]
Okay, closed then.
