### ISSUE TITLE
Embassy! Embassy!

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3547]
Murano Glassworks does not provide +2 Food or +2 Tourism to Embassy. This is a hypothetical scenario in which Venice somehow obtains an Embassy to work, but should still be added because it is a Great People Improvement.

On another note, this suggestion is met with positive feedback so far. https://forums.civfanatics.com/threads/venice.540351/page-34#post-14879221 Perhaps, this can be easily addressed with barely any changes.

**Comment by LoneGazebo** [comment]
I'll look at it.

**Comment by TechpriestEnginseer** [comment]
Also Authority tooltip is broken.

You don't get 30 Culture from Tribute. You get 25 Culture.
