### ISSUE TITLE
Request: GameEvent for espionage

### ISSUE THREAD

**Issue by theazuresoul** [LoneGazebo/Community-Patch-DLL#3548]
I'm working on a compatibility mod, and I would be greatly helped if you could add in an GameEvent for when a spy completes an action. The EspionageResult game event works fine, but it doesn't give any indication for what kind of action a spy completed. Would it be possible to add an event that tells the type of action (stealing a tech, advanced action, rigging elections, gathering intrigue, etc.) a spy completes?

Thanks muchly.

**Comment by LoneGazebo** [comment]
Best I can do is this;

#if defined(MOD_EVENTS_ESPIONAGE)
	if (MOD_EVENTS_ESPIONAGE) {
		GAMEEVENTINVOKE_HOOK(GAMEEVENT_EspionageNotificationData, iCityX, iCityY, eAttackingPlayer, m_pPlayer->GetID(), iSpyResult, eStolenTech, eBuilding, eUnit, bUnrest, iValue, iScienceValue, bRebel, iGreatWorkIndex);
	}
#endif

This will trigger _every_ time a notification is created for m_pPlayer->GetID() - data here isn't necessary valid (i.e. eBuilding can be -1).
