### ISSUE TITLE
Crash to Desktop with save version 9/27

### ISSUE THREAD

**Issue by paramenides** [LoneGazebo/Community-Patch-DLL#3549]
_1. Mod version (i.e Date - 4/23):_

9/27
_2. Mod list (if using Vox Populi only, leave blank):_
Faster aircraft animations (there are no aircraft yet in this save)
[civ 5 crash log and save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1347660/civ.5.crash.log.and.save.zip)

_3. Error description:_ 
Game crashes to desktop, not sure what causes it, but it is repeatable.
_4. Steps to reproduce (optional):_
It happens within 2 turns of the save.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by paramenides** [comment]
Hi Gazebo, could you update me on what this is? I doubt faster aircraft animations mod is causing this, so I assume something in vox or the base game.  This is the second crashing save I have had with Gajah Madah. Do i need to switch civilizations?

**Comment by MechanizedCheese** [comment]
+1 on this, almost identical log
additionally, my game crash on barbarian AI turn

**Comment by Der-Zorn-Gottes** [comment]
Also crash with this version. Save and logs attached.
[Crashinfo.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1356839/Crashinfo.zip)

**Comment by bigcat88** [comment]
I don't know , my fun game crashes almost at end(me in start of information era) on Spanish AI turn(Spanish starting build hubble). tried 3 times, always crash.
logs + saves:
Terrain - Poor Tiles Tweak (v 2)
Wonder Race (v 7)
World Congress Reformation (v 5)
standard install + eui.

[crash on spanish turn.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1366449/crash.on.spanish.turn.zip)

**Comment by bryan317** [comment]
I'm crashing with Indonesia as well.  And I was SO far lol.  I reported an extremely glitched out game with this game already so I wasn't reporting my CTD...i should have already abandoned this game.  I don't know if this is the issue but the game is crashing as the Zulus try to take the Mongolian capital... of Istanbul.  Long story but this is their final city so the Zulus are attempting to eliminate them from the game.  CTD everytime.
