### ISSUE TITLE
Request: minor civilization diplomatic notification

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#3550]
As i have wrote in forum, i would gladly see diplomatic actions turned off, or at least merged into few ones, rather  than click through every single DoW or peace brokering between cs. It is bothering and unnecessary, when i can simply look in diplomatic overview, which cs i am at war. Same for major civ pledge of protection notification, again, when i am going to tribute cs or head to get positive diplo modifier for pledge i can simply look by whom they are protected. Maybe EUI offers that, but i do not like the rest outfit of UI and i think, that this would appreciate more players than just me.

**Comment by LoneGazebo** [comment]
Not feasible given the notification engine.
