### ISSUE TITLE
Great Writers are not equal

### ISSUE THREAD

**Issue by InapropriateUsername** [LoneGazebo/Community-Patch-DLL#3553]
_1. Mod version - 9/27

_2. Mod list (if using Vox Populi only, leave blank):_
Flag promotions
Impoved City View
Unit path viewer
Modpack, but singleplayer

_3. Error description:_ 
Great Writer purchased with faith give less culture that Great Writer that was born naturally

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[AutoSave_0350 AD-1650.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1353351/AutoSave_0350.AD-1650.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/19764746/31140904-92ea80b0-a87e-11e7-826f-362760a4e5b0.png)
![image](https://user-images.githubusercontent.com/19764746/31140926-a6436776-a87e-11e7-89a1-70079e378fe7.png)

**Comment by InapropriateUsername** [comment]
Same thing with Great Scientists.

At least Scientist that i got from Empire State Building gives 50% less science than Scientist that was bor naturaly

**Comment by MoiMagnus** [comment]
I have this bug too.

**Comment by bigcat88** [comment]
I think all have this. I also sometimes have GreatWriters/Musicians that are not able to create GreatWork(with free slots in city). And I seen situation where I born GW that gives me 12k of culture - spend him on great work. Next GreatWriter(it was about 10-13 turns after,on Epic)(I don't remember wich I buyed for faith and wich was gained naturally) - have a possibility to give me much less culture(7 or 8k). I was very surprised. But it was maybe in August or July...

**Comment by bryan317** [comment]
I just kinda thought this was a normal feature.  My purchased Great Scientists are usually about half the strength as naturally born ones.

**Comment by bryan317** [comment]
As well as the writers

**Comment by cdanger341** [comment]
Great Writers/Scientists/Engineers/etc got their instant yields reduced a few patches ago, but with the stipulation that they get bonus instant yields for each Great Work/Tile Improvement of their type that exists before they're "born". So a Writer (of a given Era) created after you already have 4 Great Works of Writing in your Civ will generate more instant Culture than if you had 0 Great Works of Writing.

So, I'm wondering if Faith-bought or "free" Great Xs are not getting these bonus instant yields for some reason. That could explain this as it only seems to happen with Great Xs capable of generating instant yields.

**Comment by InapropriateUsername** [comment]
I have zero Great Works in my game

**Comment by LoneGazebo** [comment]
I don't  see any evidence for this in the DLL.

G

**Comment by MoiMagnus** [comment]
I've reproduced the bug with Great Scientist. 
+I have two saves : One before buying by faith and natural born, and one after. Their values are 3333 and 1714 (quick speed, no EUI, no other mods). 
[Save_Bug_GS.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1360335/Save_Bug_GS.zip)
+I also have the logs of the complete game.
[Logs_Bug_GS.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1360333/Logs_Bug_GS.zip)
You should not have any problem to reproduce it from those saves.

**Comment by LoneGazebo** [comment]
So this is actually a vanilla bug. Firaxis didn't account for a special case that happens every time a unit draws on a certain table. Anyways, fixed.

**Comment by bryan317** [comment]
This was actually a nerf I was quite used to and had considered normal gameplay.  Guess it's time to up my difficulty Lol.  Thanks G!
