### ISSUE TITLE
AI galleases can cross ocean

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3555]
_1. Mod version (i.e Date - 4/23):_
9-27

_2. Mod list (if using Vox Populi only, leave blank):_
WorldCongressReinformation
PoorTilesTweak

_3. Error description:_ 
I don't know, maybe it is a new future but in my game looks like all(including CS!) except me can cross oceans on galeases...
Galeas must have 3 negative promotions, and all AIs galeases has 2...
Maybe it is not a bug, but for me interesting what is this.

_4. Steps to reproduce (optional):_
I don't know how, I just create a fun game to test some changes( I changed values in TechCostChanges.sql(https://forums.civfanatics.com/threads/technology-cost-of-history.607548/)) and see such behaviour.

---------------------------
![20171004163311_1](https://user-images.githubusercontent.com/13381981/31178538-11f4262e-a922-11e7-897d-38a24faeda31.jpg)
![20171004163157_1](https://user-images.githubusercontent.com/13381981/31178537-11e6551c-a922-11e7-8685-6c34103b022d.jpg)

[Bismarck_0301 AD-1405.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1355969/Bismarck_0301.AD-1405.zip)

**Comment by MoiMagnus** [comment]
As a little check : 
Did you try with both newly created Galeas and upgraded Galeas ?
