### ISSUE TITLE
Liberated Vassal becomes again your vassal 

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3556]
_1. Mod version (i.e Date - 4/23):_
9-27

_2. Mod list (if using Vox Populi only, leave blank):_
WorldCongressReinform
PoorTilesTweak

_3. Error description:_ 
1. Morroco's city Rabat was liberated by Germany(from Iroques). Morroco becomes voluntary vassal.
2. Very short peace time.
3. Germany declares war on Iroques to liberate 2 other cities. 
4. Morroco immediately ask for Independence. Germany says ok.
5. Germany liberate city of Fes.
6. Morroco again Germanies vassal? I think on this step a bug present. Or maybe it is present on step 4. 
Cause there was no a possibility to liberate Morroco on turn 3 or 4. How can they ask for independence then? Screen from most early autosave:
![20171005100153_1](https://user-images.githubusercontent.com/13381981/31214576-77b6c470-a9b4-11e7-852e-3887629ce8de.jpg)

_4. Steps to reproduce (optional):_
I have an autosave before turn where Morroco becomes again a vassal from just liberating a city.

[AutoSave_0477 AD-1887.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1358260/AutoSave_0477.AD-1887.zip)

A bug in 3 screens:
![20171005094601_1](https://user-images.githubusercontent.com/13381981/31214370-8a998ba0-a9b3-11e7-828f-c3a8c5052dd4.jpg)
![20171005094731_1](https://user-images.githubusercontent.com/13381981/31214377-8e40e820-a9b3-11e7-9ef6-24d2e0283188.jpg)
![20171005094742_1](https://user-images.githubusercontent.com/13381981/31214380-906237a8-a9b3-11e7-83e5-22a8dea9fc7d.jpg)

**Comment by LoneGazebo** [comment]
Might've been a global liberation even, or another player asked for it in a deal. Valid.

**Comment by bigcat88** [comment]
So why then it becomes again my vassal, when i just liberate the second city?

**Comment by bigcat88** [comment]
If i grant them independence and after that liberate another city i didnt see why game think that they my vassal again! And look at first screen, they are not my vassal on it - but there is no number to open borders end
