### ISSUE TITLE
Everyone chooses freedom

### ISSUE THREAD

**Issue by BH5496** [LoneGazebo/Community-Patch-DLL#3558]
_1. Mod version (i.e Date - 4/23):_
2017-9-27

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch (with and without C4DF Addon)

_3. Error description:_ 
I was playing a full game on quick, standard size, king, communitas map, and several other mods in an MP Modpack to get achievements. I was first to get an ideology and chose autocracy, but everyone else chose freedom, not one other order or autocracy. The other civs were Russia, Ethiopia, Carthage, Inca, Maya, Aztec, and America. Wondering if it was one of the other mods that caused this, I tried to test it using only CP by starting in a late era, and lo and behold the AI's all choose freedom. I know it's not to spite me because I chose freedom in one of the tests and they still did it. 

_4. Steps to reproduce (optional):_
start in any era past industrial and go 2 turns to see what the AI picks

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
test save.Civ5Save

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Just means they all had the same grand strategy. Not a bug.

**Comment by BH5496** [comment]
Does it not seem a bit odd that they all had the exact same grand strategy though? Every time I test it, almost every civ goes Freedom, with the occasional Autocracy, and rarely (never tbh) Order. It seems like it hurts variety when every civ goes the same ideology, and if you want to do something different, most of the world ends up hating you. This seems especially bad on higher difficulties where there is less change to have a high tourism/culture shield so pressure ruins the game you were going for. Is there really no small tweak that could be made?

**Comment by LoneGazebo** [comment]
The issue you see is not as universal as you claim.
