### ISSUE TITLE
No tooltip when a Great Musician does a tour in your borders.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3560]
There's no "short tooltip" basically.

**Comment by LoneGazebo** [comment]
Care to elaborate?

**Comment by TechpriestEnginseer** [comment]
There's a notification of when a Great Musician plays a concert tour in your territory, there is no ShortDescription for the notification. So it appears empty in the title, but otherwise has the description that "Japanese" Musicians perform a concert tour and was well-received. This is with EUI.
