### ISSUE TITLE
Annulling a Pledge of Protection

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3561]
Means I aggressively attack the city-state if I was unable to maintain my military in time ?

By annulment I meant having the pledge of protection expire due to a lack of military as well, not as a chance to revoke it.

They also make it impossible to pledge because they say you need 19 influence to compete probably because of the -20 influence from "aggressively" attacking it.

**Comment by LoneGazebo** [comment]
Clarify?

**Comment by TechpriestEnginseer** [comment]
If your Pledge of Protection gets annulled, but have a sphere of influence with the city-state there can be some issues with them(not picking up the allied status) when you repledge.
