### ISSUE TITLE
GameEvents.PlayerCanPropose

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3562]
This resolution seem to have stopped working Lua-wise. Using them to return false on all resolutions does not prevent any resolution at all from being proposed. Civilizations can still propose like normal.

**Comment by LoneGazebo** [comment]
Code looks fine to me - you've got MOD_EVENTS_RESOLUTIONS enabled?

**Comment by TechpriestEnginseer** [comment]
Yup.

Anyway GameEvents.PlayerCanBuyOut seems to be broken. It never prints any statements at all in this code when I station a MoV in the City-state's territory.
````
function NoMoreVenice(iPlayer, iCS)
	if Game.IsResolutionPassed(iOpen, iCS) then
		print("Stop buying city-states!")
		return false
	end
	print("But you can buy this one however!")
	return true 
end
GameEvents.PlayerCanBuyOut.Add(NoMoreVenice)
````
And EVENTS_MINORS_INTERACTION is enabled because these code below work.
````
function StopBullyGold(iPlayer, iCS)
	if Game.IsResolutionPassed(iOpen, iCS) then
		return false
	end
	return true 
end

function StopBullyUnit(iPlayer, iCS)
	if Game.IsResolutionPassed(iOpen, iCS) then
		return false
	end
	return true 
end

GameEvents.PlayerCanBullyGold.Add(StopBullyGold)
GameEvents.PlayerCanBullyUnit.Add(StopBullyUnit) 
````

**Comment by LoneGazebo** [comment]
Where is iOpen defined? iPlayer seems unnecessary in the context.

**Comment by TechpriestEnginseer** [comment]
iOpen is defined in the Lua file.
````
local iOpen = GameInfoTypes.RESOLUTION_OPEN_DOOR
````

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1385781/CvGameCore_Expansion2.zip)

**Comment by LoneGazebo** [comment]
Added some missing lua hooks for vanilla proposal types. May have been the issue.

**Comment by TechpriestEnginseer** [comment]
CanBuyOut still doesn't work at all.

**Comment by TechpriestEnginseer** [comment]
More bugs as well:
````
function Nonono(iPlayer, iResolution, iChoice, bEnact)
	if iResolution == iSphere and not bEnact then
		print("yoohoo")
		print(iResolution)
		print(iChoice)
		print(bEnact)
		return false
	end
	return true 
end
GameEvents.PlayerCanPropose.Add(Nonono)
````
PlayerCanPropose works fine in denying a Sphere of Influence, but when when trying to deny a Repeal on Sphere of Influence? Doesn't exist.

**Comment by TechpriestEnginseer** [comment]
Also this code
````
function Resolutiontest(iResolution, iChoice, bEnact, bPassed)
	print("work!")
	print(iResolution)
	print(iChoice)
	print(bEnact)
	print(bPassed)
end
GameEvents.ResolutionResult.Add(Resolutiontest)
````

Gives me these weird errors and inconsistencies.
````
[990171.059] SphereOfInfluences: work!
[990171.059] SphereOfInfluences: 21 --Decolonization (1st player)
[990171.059] SphereOfInfluences: 0 -- No.. not decolonize the 0th player, but rather the 1st player...
[990171.059] SphereOfInfluences: 1 -- Propose not Repeal
[990171.074] SphereOfInfluences: true -- This was passed.
[990171.074] SphereOfInfluences: work!
[990171.074] SphereOfInfluences: 6 --Scholar in Residence
[990171.074] SphereOfInfluences: 1 -- Hmm.. see comment below.
[990171.074] SphereOfInfluences: -1 -- I guess it wasn't passed, so it goes nil?
[990171.074] SphereOfInfluences: true --Pass? This thing got rejected!
````
iChoice in ResolutionResult seems to be iPlayer basically. Not iChoice while bEnact seems to work correctly I suppose, but bPassed fails the test completely.

**Comment by LoneGazebo** [comment]
Hmm. Okay that helps. I’ll see what I can do.

**Comment by LoneGazebo** [comment]
Okay, first off, the documentation is wrong. This is correct:



Second the repeal never passed a choice, as there was no choice in the default function. I've added it, so we'll see. Will upload a test DLL for you shortly.

G

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1386034/CvGameCore_Expansion2.zip)

**Comment by TechpriestEnginseer** [comment]
````
function Nonono(iPlayer, iResolution, iChoice, bEnact)
	if iResolution == iSphere and not bEnact then
		print("yoohoo")
		print(iResolution)
		print(iChoice)
		print(bEnact)
		return false
	end
	return true 
end
GameEvents.PlayerCanPropose.Add(Nonono)
````
Same issue.

**Comment by LoneGazebo** [comment]
Can you just send me what you are working on? It'd be easier for me to replicate this rather than playing DLL badminton.

**Comment by LoneGazebo** [comment]
Ahh, well, I do see a bug. I'm also going to add an 'ichoice' variant to DoRepealResolution that lets you specify a decision type (i.e., for Sphere of Influence, the CS being targeted) and only return the proposal if that's the target one.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1388593/CvGameCore_Expansion2.zip)

Try this. DoRepealResolution is now (iResolution, iPlayer, iChoice);

**Comment by LoneGazebo** [comment]
Success?

**Comment by TechpriestEnginseer** [comment]
Seems to work with some success. I'm debugging more for any further "what-if" scenarios.

**Comment by LoneGazebo** [comment]
Good. The WC stuff in the DLL is so awful to work with. Written by a hack.

**Comment by TechpriestEnginseer** [comment]
Ok the only concern now is GameEvents.PlayerCanBuyOut

It never seems to fire up at all and I'm trying to use it to prevent Venice to buy city-states.

**Comment by LoneGazebo** [comment]
Do you have EVENTS_MINORS_INTERACTION enabled?

**Comment by LoneGazebo** [comment]
For the second part, false = repeal, true = propose. The bool determines whether or not it is being created or destroyed as a resolution.

**Comment by TechpriestEnginseer** [comment]
EVENTS_MINORS_INTERACTION are enabled if 
    
    
work fine and perfectly.

Second part:
````
function Nonono(iPlayer, iResolution, iChoice, bEnact)
	if iResolution == iSphere and not bEnact then
		print("yoohoo")
		print(iResolution)
		print(iChoice)
		print(bEnact)
		return false
	end
	return true 
end
GameEvents.PlayerCanPropose.Add(Nonono)
````
Same code doesn't work then.

**Comment by LoneGazebo** [comment]
>EVENTS_MINORS_INTERACTION are enabled if work fine and perfectly.
Eh?

Second part should work, the code looks fine on my end. Line 3333 of VotingClasses.cpp if curious.

**Comment by TechpriestEnginseer** [comment]
CanBuyOut is a nonexistent GameEvent.

The second part only works if iPlayer is -1 and iResolution is Sphere of Influences. As bEnact returns true on repealed and proposal resolutions.

**Comment by TechpriestEnginseer** [comment]
So, I'm actually going to phase out the useless CanBuyOut GameEvent, but I still can't figure out what's the difference between a repealed resolution and a proposed resolution. Maybe PlayerCanPropose only works for proposed resolutions and not repealed resolutions.

**Comment by LoneGazebo** [comment]
CanBuyOut exists, it is in the MinorCivAI file (Line 15735)

**Comment by LoneGazebo** [comment]
Going to try a small tweak to PlayerCanPropose for the repeal stuff.

**Comment by TechpriestEnginseer** [comment]
CanBuyOut exist, but it doesn't seem to function at all.

You can even use
````
function NoMoreVenice(iPlayer, iCS)
	print("supposedly works")
	return false
end
GameEvents.PlayerCanBuyOut.Add(NoMoreVenice)
````
And the CanBuyOut won't print anything nor stop you from buying a city-state.

**Comment by LoneGazebo** [comment]
Oh, that's because the 'buyout' there has _nothing_ to do with Venice - it's for Austria. :)

**Comment by TechpriestEnginseer** [comment]
So can there be a GameEvent to stop MoV purchases? :)

**Comment by LoneGazebo** [comment]
Done. Same code. :)

**Comment by TechpriestEnginseer** [comment]
I can't find the new code.

**Comment by LoneGazebo** [comment]
It uses the same PlayerCanBuyOut method.

**Comment by TechpriestEnginseer** [comment]
Also Repealed Sphere of Influences can still be repealed with the same code.
````
function Nonono(iPlayer, iResolution, iChoice, bEnact)
	if iResolution == iSphere and not bEnact then
		print("yoohoo")
		print(iResolution)
		print(iChoice)
		print(bEnact)
		return false
	end
	return true 
end
GameEvents.PlayerCanPropose.Add(Nonono)
````
However, you can block repealed resolutions that aren't city-states specific with this Lua.

**Comment by LoneGazebo** [comment]
If using the canbuycitystate lua function, make sure you have visible set to false!

**Comment by LoneGazebo** [comment]
Not sure what your previous statement re: SoI meant.

**Comment by TechpriestEnginseer** [comment]
````
If using the canbuycitystate lua function, make sure you have testvisible set to false!
````
?

PlayerCanPropose > Return False on all Sphere of Influences Resolutions > ALREADY Proposed Sphere of Influence still repealable.

**Comment by LoneGazebo** [comment]
This seems to have withered, so I'm closing it.

**Comment by TechpriestEnginseer** [comment]
Withered because the code still does not work yet strangely. :\
