### ISSUE TITLE
Entering in Trade Deals larger than 4 digits.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3565]
The AI can enter in 10k gold during a peace deal, but I am unable to change anything 9999+. This seems like a UI issue.

**Comment by LoneGazebo** [comment]
Yeah, but it can't easily be resolved without a whole bunch of resizing. Fringe issue, not going to address.

**Comment by TechpriestEnginseer** [comment]
Couldn't you just allow it to enter in more than 4 digits without resizing like how bc1 did with renaming limit? I'm sure people aren't just going to intentionally enter in 5 digits and be surprised.

**Comment by LoneGazebo** [comment]
I'd rather not mess with it TBH - you say that it won't confuse people, but it will. :)
