### ISSUE TITLE
Statecraft\GlobalMonopolies is so intended?

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3567]
_1. Mod version (i.e Date - 4/23):_
9-27

_2. Mod list (if using Vox Populi only, leave blank):_
WorldCongressReinform
PoorTilesTweak

_3. Error description:_ 
I cant see the effect from monopoly. But I see monopoly in monopolies list. 

_4. Steps to reproduce (optional):_
Here is an example. What I see in monopoly list:
![20171006222359_1](https://user-images.githubusercontent.com/13381981/31294822-1633e6ce-aae5-11e7-9171-0f9f3b1ee9b9.jpg)

What I see in city production:
![20171006222505_1](https://user-images.githubusercontent.com/13381981/31294881-370a3b96-aae5-11e7-9cdd-66e4e3e6bf0f.jpg)

The same is with global monopoly happies. I have one own monopoly on wine , and two monopolies form CS(glass and jewelry). But see only: +5 from Resource monopolies in happy stats(I think it is from my wine).

Looks like monopolies are displayed in monopolies window, but has no effect... And I open with IGE right now corporations tech - I cant build corporations on monopolies from CS. Only corporations from luxuries that I own.

**Comment by bigcat88** [comment]
Ok, I think that I understand what the problem.
After I liberate CS with Glass I got monopoly(from statecraft). Maybe here are the same problem, like with Hexxon Refineries(I always forgot to report about it). 
As I know when u got resources from hexxon corporation u can get even 26% but no get monopoly, till u ReImprove(I usual do that with great people improvement) some res on your base. Or just with IGE , remove improvement from coal for example and then place improvement back.
So I think here is the same problem

**Comment by bigcat88** [comment]
Yeah, I declare war on 2 CS with glass(there are total 3 cs with glass , all are my allies), on next turn I see in monopoly list that I have 33% -  but I still have monopoly. 
Maybe CheckForMonopoly function need to call every time that player\AI get CS as ally or lost ally status.

**Comment by MoiMagnus** [comment]
I remember reading somewhere that in order to have a monopoly, you need : 
1) 50% of the initial ressources on the map
2) More than any other civ
3) At least one ressource tile of that kind (restriction made to nerf Great Amiral expedition)
It is quite possible that the last condition is bugged.

**Comment by bigcat88** [comment]
U don't need a tile with resource(in summer version that's 100%). U need that resource was present in a world, but not in your territory. And that always works perfect.

Gazebo, I look at code, maybe this will help(if I understand the code in right way):
I don't see a notifications, so CheckForMonopoly function is not called when I become an ally of CS.
I look at:
  file: CvMinorCivAI.cpp
  line: 12016
  function: DoUpdateAlliesResourceBonus

I think CheckForMonopoly (or changeResourceImport) must be called there.

**Comment by LoneGazebo** [comment]
I'll look.
