### ISSUE TITLE
CTD on Ai turn

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#3568]
_1. Mod version (i.e Date - 4/23):_

9/27
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
CTD on Ai turn. My new Celtic game ruined. My previous Japan late game ruined and save corrupted by graphical glitches(rendering issues). I don't  care so much about this game, because its just early game, but i am desperate about those graphical glitches. I bought new machine and i can't even play on same settings like on the old. And i don't know where to shuffle with settings anymore. I don't remember, when i have played last time such unoptimized game.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[logs +save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1364430/logs.save.zip)

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
VP does not mess with the graphical engine. Sorry but that’s not caused by our mod.

**Comment by matlajs** [comment]
i would not blame Vp for that ever. i just say i am desperate because i don't know what to do with that. i thought with new computer, it will be much better gaming experience, but it is worse. Before i have dealt just with  low fps in late game.

**Comment by LoneGazebo** [comment]
There are threads on this on CivFanatics. Make a new thread asking for help.

**Comment by matlajs** [comment]
I have made new thread on civfanatics tech sub thread. so i will hope.

**Comment by ilteroi** [comment]
try switching to DX9, it works better (for me at least)

**Comment by matlajs** [comment]
i tried it. but it did not save my japan save.
