### ISSUE TITLE
Question: AI's difficulty "cleverness"

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#3569]
If I remember correctly, when making a decision, an AI of difficulty N choose randomly between the 9-N best possibilities.
What is the name of this "cleverness" parameter in DifficultyMod.xml ?
For example, if I want to modify the King AI to have the Immortal's cleverness, Can I obtain it by modifying the King's AI, or am I forced to change the Immortal's AI instead ?

More generally, does VP support the adding of new difficulty levels (for example, multiple version of Deity with different bonuses) ? Or does difficulty levels are explicitely used in the code ?

**Comment by LoneGazebo** [comment]
'NumOptionsConsidered' stuff is what you are looking for.
You can add new difficulties but I don't know if EUI updates their text correctly.

**Comment by MoiMagnus** [comment]
If 'NumOptionsConsidered' is what I am looking for, why does the value is '3' whathever the difficulty ?
(Except AI_DEFAULT where it is 2, but it doen't count)
I though the Deity AI was supposed to always take the best decision.

**Comment by LoneGazebo** [comment]
Because I was testing something and forgot to reset it in the difficultymod.xml file. :) Should be 1 for immortal/deity, 2 for prince-emperor, 3 for rest.

G
