### ISSUE TITLE
Iron Curtain order tenet doesn't give a free courthouse upon annexing a puppet

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#357]
The city was captured after I took the tenet.

**Comment by Radost** [comment]
Turns out it ignores cities captured through the trade window. Except Civilizing Mission policy from Imperialism does place free factories upon traded cities.

**Comment by LoneGazebo** [comment]
I'll fix the latter - should only be getting free factories from conquered cities, not traded ones.

**Comment by Radost** [comment]
But why? The only time the civ trades cities is only during a truce.
If anything, trading cities should proc all conquer-based bonuses. Otherwise that "resistance" period after trading doesn't make sense.

And how about I conquered a city, but didn't get the courthouse afterwards? That city was Venice and I eliminated the civ after conquering it. Also I liberated it at some time before the war.

**Comment by LoneGazebo** [comment]
Because the purpose of the policy function is to reward conquest during war, not peace time trades.
G

**Comment by Radost** [comment]
I've never seen AI trading cities during peace.
