### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#3571]
_1. Mod version (i.e Date - 4/23):_
9/27

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
CTD in AI turn.

_4. Steps to reproduce (optional):_
From the save game, I've founded religion, picked Apostolic Tradition, Way of the Pilgrim and Churches. Next turn it crashes.

[AutoSave_0125 AD-0250.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1368820/AutoSave_0125.AD-0250.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1368825/CvMiniDump.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by matlajs** [comment]
interesting. my celt game has crashed after Russia enhanced their religion.
