### ISSUE TITLE
Different Icon Color for Thief and Spy

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3572]
Just a QoL suggestion aside for the usual "conducting advanced actions of either stealing a technology or a great work"

**Comment by LoneGazebo** [comment]
Unfortunately that panel doesn't support the icon swapping of the other panels.

**Comment by TechpriestEnginseer** [comment]
Weird since it would support diplomat/spy. Oh well.
