### ISSUE TITLE
Unable to progress to next turn

### ISSUE THREAD

**Issue by theazuresoul** [LoneGazebo/Community-Patch-DLL#3573]
_1. Mod version (i.e Date - 4/23):_
10/9

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Ethiopia, turn 104. I am unable to advance to next turn (clicking "next turn" doesn't do anything). Doesn't seem to depend on my actions on turn 103 or 104. At the end of turn 103, a neighboring city-state is captured by barbarians; I suspect that could be causing the issue.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1370915/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[Haile Selassie 10-9-2017.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1370903/Haile.Selassie.10-9-2017.zip)

4. Screenshots (optional):

In addition to the above issue, there's an additional graphical issue that I've been noticing, that has popped up previously. I couldn't fully reproduce it this time, due to being unable to advance to next turn, but you can see the start of it in the attached screenshot. Whenever a city-state is captured by barbarians, a phantom barbarian unit is displayed on the UI (you can see that the icon for the barbarian spearman is doubled up in the screenshot). This phantom display persists after the city-state is liberated, and only goes away on reloading the game.

![image](https://user-images.githubusercontent.com/14305768/31373879-8ebb32ce-ad50-11e7-8f57-597a142e6b92.png)

**Comment by theazuresoul** [comment]
The second zip file is my save game; sorry, accidentally put it on the wrong spot.

**Comment by Enrico-Swagolo** [comment]
Same problem, if you tell a worker to make a road from city X to city Y, once he makes the final road tile and  goes inside city Y, you won't be able to click him while he'll demand orders.

**Comment by LoneGazebo** [comment]
@ilteroi any ideas?

**Comment by ilteroi** [comment]
d'oh. might be a side effect of my recent fix. will check

**Comment by ilteroi** [comment]
fixed and pushed

**Comment by Jotaro31400** [comment]
yes i've got this issue too , I hope we will get the fix soon ^^
