### ISSUE TITLE
AI won't mount operations against barbarian cities

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3574]
in FindBestAttackTargetGlobal() and also in UpdateOperations() it says:

	for(int iPlayerLoop = 0; iPlayerLoop < MAX_CIV_PLAYERS; iPlayerLoop++)

which excludes the barbarians. is that by design?

the last change of that line was yours - though almost two years ago

**Comment by Enrico-Swagolo** [comment]
Confirming, in my current game Indonesia has several troops near the city, but that's because they're fighting me. They won't take it despite the fact it'd be pathetically easy and maybe net them an easy Ally.

**Comment by LoneGazebo** [comment]
That's not by design, no.

G

**Comment by LoneGazebo** [comment]
I'll adjust it.
