### ISSUE TITLE
Japan UA Not Generating Great Persons Correctly

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#3576]
_1. Mod version (i.e Date - 4/23):_
10-9-1

_2. Mod list (if using Vox Populi only, leave blank):_
Ethnic Units

_3. Error description:_ 
Great Artists/Writers/Musicians are not being born by the birth of the second Great General/Admiral. The GP bars fill up in the capital (325/325 for example), but the GPs are not actually born until the 3rd Great General/Admiral is born (bringing the GP bars over the "limit".

_4. Steps to reproduce (optional):_
Of note, I was able to complete Authority and grab the first policy of Artistry prior to the birth of my second Great General, thus applying the +25% GP rate from the Opener. Perhaps this is confusing the calcs for how much GP points the GGeneral birth should produce?

Save file included that is several turns AFTER my second GG was born. Notice how all of the GA/GW/GM bars are full in the capital, but none are being born in the following turn.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Oda Nobunaga_0224 AD-0760.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1374165/Oda.Nobunaga_0224.AD-0760.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Zarrk** [comment]
Same version, I'm encountering the same issue with France, all bars filled but Great people not appearing, on my next conquest points were added and the bars are at 150% of their value but nothing happen.

I ran a few tests and found that adding a source of the corresponding GPP or working Specialist would correctly spawn a Great People. Looks to me the game will only check citie's GP progression if they were GPP added during the start of the turn 'Collection Phase'.
