### ISSUE TITLE
AI needlessly uses defense process

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#3577]
I notice this quite often when spying enemies at war, they waste production when they're not in danger at all. Those units stationed around the capital are also a bit overkill.

![civchinabug1](https://user-images.githubusercontent.com/24731508/31452480-517f1d20-aeaf-11e7-9178-b5e3605b88e0.png)

![civchinabug2](https://user-images.githubusercontent.com/24731508/31452482-51faa6de-aeaf-11e7-8949-b13b708e1cfc.png)

**Comment by TechpriestEnginseer** [comment]
defense process isnt accurate as well 300 production does not translate to 30 defense strength but rather 3.
