### ISSUE TITLE
Espionage still broken?

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#3578]
_1. Mod version (i.e Date - 4/23):_
9/7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
My thiefs can not steal great works regardless they are present in a targeted city. AI thiefs steal greatworks even from capital. is that normal? IIRC they could not steal GWs from capital before. Interresting is, that notification has told me, that GW was stolen from St. Petersburg, while i have lost GW and theme bonus from Sistine Chapel in Moscow.......

To adition, i am not willing to create new thread. is this normal?
![20171011201141_1](https://user-images.githubusercontent.com/21192402/31458573-c28b732c-aec0-11e7-8c3f-addf6e500f39.jpg)

**Comment by pandasnail** [comment]
The ice part is normal, ships can enter owned ice tiles.

**Comment by matlajs** [comment]
that is little bit unfair for my ironclad :(

**Comment by LoneGazebo** [comment]
I checked espionage, looks fine to me.
