### ISSUE TITLE
newly founded city grows like crazy

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3579]
prince difficulty. rome founds a city on my doorstep. it grows every turn up to size 10:

Rome,178,Arpinum,1,7,9,0,0,2,0,0,0,7.00,9.00,0.00,0.00,2.00,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,6,6,0,0.00,
Rome,179,Arpinum,2,10,9,0,0,2,0,0,0,5.00,4.50,0.00,0.00,1.00,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,7,7,0,0.00,
Rome,180,Arpinum,3,12,10,0,0,0,0,0,0,4.00,3.33,0.00,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8,8,0,0.00,
Rome,181,Arpinum,4,14,11,0,0,0,0,0,0,3.50,2.75,0.00,0.00,0.00,0.00,0.00,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,8,8,0,0.00,
Rome,182,Arpinum,5,16,18,0,0,3,0,2,0,3.20,3.60,0.00,0.00,0.60,0.00,0.40,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,9,9,0,0.00,
Rome,183,Arpinum,6,21,19,0,0,3,0,2,0,3.50,3.17,0.00,0.00,0.50,0.00,0.33,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,9,9,0,0.00,
Rome,184,Arpinum,7,23,19,0,1,4,0,2,0,3.29,2.71,0.00,0.14,0.57,0.00,0.29,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,9,9,0,0.00,
Rome,185,Arpinum,8,25,19,0,1,6,0,2,0,3.13,2.38,0.00,0.13,0.75,0.00,0.25,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,9,9,0,0.00,
Rome,186,Arpinum,9,27,19,0,1,6,0,2,0,3.00,2.11,0.00,0.11,0.67,0.00,0.22,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,9,9,0,0.00,
Rome,187,Arpinum,10,27,20,0,1,6,0,2,0,2.70,2.00,0.00,0.10,0.60,0.00,0.20,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,9,9,0,0.00,

how is that possible?

**Comment by LoneGazebo** [comment]
Anything interest in the homelandAI log related to overflow or difficulty?

**Comment by ilteroi** [comment]
well, 45 starting bonus, nothing more.

127, Rome, MOD - overflow production from policy/belief/trait/ruin/etc added: 45 in Arpinum.
129, Rome, MOD - Investing in building: Monument in Arpinum. Cost: 100, Balance (before buy): 452
134, Rome, MOD - Investing in building: Council in Arpinum. Cost: 100, Balance (before buy): 301
134, Rome, Conscripted Pikeman spawned at Arpinum. Population: 8
144, Rome, MOD - Investing in building: Market in Arpinum. Cost: 150, Balance (before buy): 352
159, Rome, MOD - Investing in building: Walls in Arpinum. Cost: 150, Balance (before buy): 398

you have to add 50 to the turns apparently to make it match, it was an advanced start.

unfortunately there's no proper logging in CvCity::doGrowth(). maybe i can dig deeper tonight if you don't have a rational explanation either ...

**Comment by LoneGazebo** [comment]
I don't, no. no CBP AI DIFFICULTY BONUS FROM or anything?

**Comment by ilteroi** [comment]
it looks like they get a bonus from finishing buildings (45) and another from expanding borders (120) ... that's snowballing!

![image](https://user-images.githubusercontent.com/1358966/31514351-aaa5e464-af91-11e7-9e6d-01b2d439c510.png)

![image](https://user-images.githubusercontent.com/1358966/31514440-e85bc3a0-af91-11e7-8a5d-afa8d7ecea59.png)

the result is:

128, Rome, Arpinum is growing to 2. Net food per turn is 505/100. Have 170 food, need 10. Will consume 10.
129, Rome, Arpinum is growing to 3. Net food per turn is 582/100. Have 285 food, need 19. Will consume 19.
130, Rome, Arpinum is growing to 4. Net food per turn is 636/100. Have 273 food, need 29. Will consume 29.
131, Rome, Arpinum is growing to 5. Net food per turn is 642/100. Have 415 food, need 42. Will consume 42.

so it's not a real bug, but maybe a balance issue. these bonuses do seem a bit extreme to me.

**Comment by LoneGazebo** [comment]
Perhaps, though I haven't seen anyone complain that the AI bonuses function that way. In reality I think it is just the circumstances of the synergy + the founding city bonus for the AI that caused it (not necessarily this extreme in all cases).

**Comment by ilteroi** [comment]
a single border expansion is enough to grow from 1 to 5 citizens. doesn't seem right to me!

maybe the bonuses should depend on city size. alternatively we could eliminate the food overflow on growth.

**Comment by LoneGazebo** [comment]
Cutting out overflow makes sense - works for other mechanics in the game as well.

**Comment by ilteroi** [comment]
no problem, i'll limit overflow to production + kept food.

**Comment by ilteroi** [comment]
btw, this reminds me of another issue: there are too many bonus yields. makes it real hard to predict the effects of various choices for the players. and what's more, all the estimations for economy, production, science etc are based on the per turn values and basically unreliable if half the yields are not counted there. what's your take on this?

**Comment by bigcat88** [comment]
if u will limit overflow what will be with apostolic tradition(food in capital for religion spread)?
I always play it and collect 8-10 missionaries and then use them at one turn to start converting city with another religion. will after that I only get food for one citizen(in current version I always get 3-4 citizen grow after that)?

**Comment by MoiMagnus** [comment]
> btw, this reminds me of another issue: there are too many bonus yields. makes it real hard to predict the effects of various choices for the players. and what's more, all the estimations for economy, production, science etc are based on the per turn values and basically unreliable if half the yields are not counted there. what's your take on this?

I confirm that if you take progress, the indicators of number of turns remaining are useless. It was quite pertubating at first, but I've just stopped caring and stopped trying to make optimizations that rely on everything happening at exactly the good turn. I would not be against replacing most instant yields to constant yields, but I'm not sure it is worth it. 
The 'ideal' way of handling it would be to have an UI able to predict all the instant yields that are predictable (those from new citizens birth, ...), but it does not seems reasonably feasable. Having the UI shows the average number of yields earned during the last 10 turns is more doable, but I don't think it would be really usefull to the player (since it would behave strangely each time you expand a great person).

**Comment by LoneGazebo** [comment]
@ilteroi I think it just a consequence of the UI and Civ’s reliance on yield buckets. At this point I’d rather not mess with it - it isn’t perfect, but most users seem okay with it.

**Comment by ilteroi** [comment]
i propose to include it as an experimental change in the next release and see what the feedback is like. it might slow down growth a little bit, but people have been complaining about the game progressing too fast anyway.
