### ISSUE TITLE
Firaxite materials corp does not protect your TRs

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#3580]
_1. Mod version (i.e Date - 4/23):_
9/7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Title says it all. It does not work. Everyone happily plundered my trade routes with this corporation.

**Comment by bigcat88** [comment]
Yes, in my game the same. I can plunder Japans AI(he has Firaxis) caravans.
