### ISSUE TITLE
Random CTDs

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3582]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Whatever the reason, this version seems more easily CTD-happy than the previous ones. Usually when playing 100-200 turns in a row, a crash will occur. It's not possible to reproduce at all, so I don't think saves will be of assistance - after crash, reloading the same turn makes the crash not happen. Sometimes it occurs when doing base actions like moving an unit and/or promoting it and only rarely is it during loading of the next turn, but, again, reloading to the turn, performing the exact same things doesn't crash it. It's as if the more you play, the more likely you are to crash.

**Comment by Enrico-Swagolo** [comment]
CvMiniDump because last time it was wanted?
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1383847/CvMiniDump.zip)

**Comment by LoneGazebo** [comment]
That _sounds_ like a memory leak, so I'll keep an eye on it.
