### ISSUE TITLE
Tabya and Salt (10/17)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#3586]
_1. Mod version (i.e Date - 4/23):_
10/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Tabya still grants +1 Production and +1 Gold to Salt.

https://github.com/LoneGazebo/Community-Patch-DLL/blob/63fbd8ba0c6f02f3677f7349a36087917be14daf/Community%20Balance%20Patch/Balance%20Changes/Leaders/Vanilla/VanillaLeaderChanges.sql#L801-L802

It should be +2 Gold.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

4. Screenshots (optional):
![ss](https://user-images.githubusercontent.com/11933188/31659860-753728e6-b370-11e7-9487-02b94c7ff09e.png)

**Comment by LoneGazebo** [comment]
Yes, this was intentional.

**Comment by 8h42** [comment]
Eh? Wrong text?
Stone Works grants +2 Gold to Salt.

https://github.com/LoneGazebo/Community-Patch-DLL/blob/ec9395828a146c7b5ab21127e80f115c8168b240/Community%20Balance%20Patch/Balance%20Changes/Buildings/BuildingChanges.sql#L882

**Comment by LoneGazebo** [comment]
Right and Tabya keeps the production as part of its focus on production.

**Comment by 8h42** [comment]
Fair enough.
