### ISSUE TITLE
CTD turn 2

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#3588]
_1. Mod version (i.e Date - 4/23):_
Vox Populi 10-17

_2. Mod list (if using Vox Populi only, leave blank):_
Many, some modified by me .

_3. Error description:_ 
CTD TURN 2

_4. Steps to reproduce (optional):_
change some options in advanced menu panels
 Playing with no advanced menu or resetting advanced menu panels to default - works fine (bigcat88)
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1392360/Logs.zip)

**Comment by databot1701** [comment]
I am experiencing a similar issue with 10-17

1. Mod version (i.e Date - 4/23):
Vox Populi 10-17

2. Mod list (if using Vox Populi only, leave blank):
No other mods

3. Error description:
The game will crash on the first turn or two, or as soon as I click my first social policy.

4. Steps to reproduce (optional):
Not using the advanced game setup seems to help a bit, but it still crashes after a few turns.  With advanced game setup options enabled, it crashes after choosing the first social policy.

I have uninstalled/wiped all Civ folders/reinstalled/reinstalled VP with the official 10-17 installer, same behavoir.

Log files:  [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1392438/Logs.zip)

Dump file:  [CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1392437/CvMiniDump.zip)

**Comment by LoneGazebo** [comment]
>No other mods

>Not using the advanced game setup seems to help a bit

Which is it?

**Comment by databot1701** [comment]
I mean the advanced game/map setup where you can change the number of players, city states, and other game/map options

**Comment by Padre19** [comment]
Seems to be a problem with top panel star icon added in this version. Ctd when you put mouse cursor on it.

**Comment by SFero** [comment]
Just wanted to report the same thing. CTD when hovering over the new star icon that was added with this version.

**Comment by databot1701** [comment]
> Just wanted to report the same thing. CTD when hovering over the new star icon that was added with this version.

I hadn't even noticed this - mine does the same thing - CTD immediately when hovering the mouse over the new star icon

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1392564/CvGameCore_Expansion2.zip)

**Comment by LoneGazebo** [comment]
Unzip, drop this in your CP (1) folder. If it works, I'll hotfix (users with custom yields added that don't fulfill all necessary criteria could cause a CTD - I'm protecting for that now).

**Comment by databot1701** [comment]
I've replaced the .dll file, still getting CTD when I hover over the star icon

**Comment by SFero** [comment]
Same here, still CTD.

**Comment by LoneGazebo** [comment]
Please upload your minidumps from the latest and a savegame.

G

**Comment by databot1701** [comment]
Latest dump file:
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1392595/CvMiniDump.zip)

Autosave file:
[AutoSave_Initial_0082 AD-0260.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1392599/AutoSave_Initial_0082.AD-0260.zip)

**Comment by SFero** [comment]
Dump:
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1392641/CvMiniDump.zip)

Save:
[TestSaveFile.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1392642/TestSaveFile.zip)

**Comment by saamohod** [comment]
I confirm 2nd turn CTD.
No mods used except FlagPromotions .7

A couple of new games created on large Communitas map script crash, although one created on medium size didn't crash and I was able to proceed around 8 turns before I quit.

**Comment by LoneGazebo** [comment]
ahhh, I see the issue. You crazy 'no max turn' users. :) I'll hot fix.

G
