### ISSUE TITLE
Oil in Classical Era

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3589]
_1. Mod version (i.e Date - 4/23):   _10-17-1

_2. Mod list (if using Vox Populi only, leave blank):_ FlagPromotions .7

_3. Error description:_

City State tooltip says it is granting me Oil. The problem is that it's Classical Era time, and no actual oil is being added as per strategic resources UI. 

![20171018201421_1](https://user-images.githubusercontent.com/16341598/31732482-54581262-b441-11e7-89a6-e1b064ad8b16.jpg)

**Comment by LoneGazebo** [comment]
Yeah it is because they settled on it. Blame EUI, not me. :)
