### ISSUE TITLE
Consistent CTD

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#3591]
_1. Mod version (i.e Date - 4/23):_
 
10/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

CTD

_4. Steps to reproduce (optional):_

Load this save and press next turn

[dumpsave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1397177/dumpsave.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I loaded the save and it ran fine for a few turns. Minidump points out of the DLL, so it isn't a DLL issue so far as I can tell.

**Comment by deadstarre** [comment]
I enabled logging, crashed again and am attaching those here. Hopefully the info you need shows within
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1400831/Logs.zip)

**Comment by deadstarre** [comment]
Invalid Reference on ArtDefine_Landmarks.LayoutHandler - "SPECIAL" does not exist in ArtDefine_LandmarkTypes     appears to be it, yes?

**Comment by deadstarre** [comment]
what exactly did the minidump indicate was the problem?

**Comment by LoneGazebo** [comment]
The mini dump just pointed elsewhere, not to the DLL.

**Comment by deadstarre** [comment]
I dont have the proper software to read dmp files handy, i was asking where it pointed I.E. the cause of crash

**Comment by deadstarre** [comment]
logs show it happens just as indias turn begins, i wasnt seeing anything in the way of explanation for that though

**Comment by deadstarre** [comment]
k, here is how you reproduce the crash - go to Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Community Balance Overhaul\Balance Changes\Difficulty

the XML

change the value for Deity AIUnitSupplyPercent to 20 and voila, will crash on next turn every time. rather strange considering thats a value already in use for the prince difficulty, not to mention i got through 188 turns just fine with that value, but there it is. changing that value to 25 allows proceeding to the next turn.

**Comment by deadstarre** [comment]
ffs, on an entirely untweaked clean vp install it crashes on this save next turn every time now.  before, where adjusting that singular value made the only difference on my being able to press next turn without crashing on turn 188, 2 turns later it is again crashing regardless with a clean vp install. attached 

[savedump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1403508/savedump.zip)

**Comment by LoneGazebo** [comment]
Bingo, got it. Divide by zero error in a _very_ specific circumstance for the AI when doing a hurry purchase. Fixed DLL will be uploaded shortly, should let you continue playing. :)

Cheers,
G

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1403698/CvGameCore_Expansion2.zip)

**Comment by LoneGazebo** [comment]
Unzip and drop that in CP (1).

**Comment by deadstarre** [comment]
Top notch! Resolved, cheers =) 

![bingo](https://user-images.githubusercontent.com/15820785/31849824-ea51708e-b616-11e7-8591-ecad51e4b434.jpg)
