### ISSUE TITLE
idea: city bonus yields scale with population not era

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3592]
title says it all. do you think that's feasible?

**Comment by ilteroi** [comment]
i think it's much more natural than this abrupt inflation with era changes. reduced overflow issues are but a side effect.

**Comment by LoneGazebo** [comment]
Problem is that era-scaling is embedded in the framework of the project - it'd be a big shift in gameplay functionality (and also readability for the user - way easier to know that 30 science is 30 science until medieval, when it becomes 60, etc.) I agree that, had we started this way, it would have been better, but I don't think it is feasible at this point.

**Comment by ilteroi** [comment]
fair

**Comment by LoneGazebo** [comment]
Definitely an issue of 'that's a better way to do it, but I think we crossed that bridge long ago...' :)
