### ISSUE TITLE
CP AI ideology choice

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#3595]
_1. Mod version (i.e Date - 4/23):_ 10/17
_2. Mod list (if using Vox Populi only, leave blank):_ CP-only, IGE.
_3. Error description:_ at least 50% of the AIs choose Freedom, even without any pressure toward it. It is about 75% in the test games I've started a game at Information Era.
_4. Steps to reproduce (optional):_ Start a game with CP only. For example with 22 civs at Information Era. Unlock any ideology. Meet everyone (using IGE, for exemple). Look at the proportion of Freedom. 

Note : I didn't play enough games to be sure of that imbalance. However, some people on the forum were claiming it, so I've runed 1 full game and 2 information era start games to confirm it.

**Comment by LoneGazebo** [comment]
If you have logs enabled, the PolicyAI logging file would be useful.

G

**Comment by MoiMagnus** [comment]
I will probably play and generate the logs around wednesday.
