### ISSUE TITLE
CTD on (10-17)

### ISSUE THREAD

**Issue by Legedi** [LoneGazebo/Community-Patch-DLL#3597]
_1. Mod version (i.e Date - 4/23):_
(10-17)

_2. Mod list (if using Vox Populi only, leave blank):_
All Vox Populi, 
(7) Community Events (v 4)
Really Advanced Setup (v 15)
Tectonic Map Script (v 4)
Ingame Editor (v 39)

_3. Error description:_ 
CTD during AI turn. Reloaded and tried again, crashed same spot.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1404357/Logs.zip)
[AutoSave_0128 AD-0325.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1404359/AutoSave_0128.AD-0325.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1404410/CvGameCore_Expansion2.zip)

Unzip, drop in (1) CP, replace DLL. Try it out. Should fix.

**Comment by Legedi** [comment]
Thanks! I'll try tonight

**Comment by R3P0FFXI** [comment]
@LoneGazebo where is the CvGameCore_Expansion2.dll located exactly I dont see it under C:\Users\Username\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch

**Comment by LoneGazebo** [comment]
If you are running the 43 civ version a.) this won't work for you and b.) it is in 6c.

G

**Comment by R3P0FFXI** [comment]
ah bummer, o well was hoping this would fix my crash issue but alas guess not

**Comment by Legedi** [comment]
Fixed the CDT for at least that turn. Don't have time to try further turns right now. But fix that exact bug. Thanks.

**Comment by LoneGazebo** [comment]
cool.
