### ISSUE TITLE
Maya Free Policies

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#3598]
https://forums.civfanatics.com/threads/maya.544399/page-6#post-14898282

See there for screenshots. Maya get a free policy upon researching ancient techs.

**Comment by RandomNub** [comment]
![civmaya3](https://user-images.githubusercontent.com/24731508/31855187-b355cf46-b6a5-11e7-98ef-9ce570852965.png)

**Comment by LoneGazebo** [comment]
Tested, could not reproduce.

**Comment by RandomNub** [comment]
Me neither so I guess safe to close, weird stuff.
