### ISSUE TITLE
Community Patch Crash

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#3599]
_1. Mod version (i.e Date - 4/23):_
Vox Populi (10-17-1)

_2. Mod list (if using Vox Populi only, leave blank):_
Really Advanced Setup

_3. Error description:_ 

Game crashing while using community patch project

_4. Steps to reproduce (optional):_
Load Autosave game it will crash in 3 turns during AI turns

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

https://www.dropbox.com/s/9qi8k6fwr40x5iz/Logs.7z?dl=0

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

https://www.dropbox.com/s/ph2ik790uqzswvj/AutoSave_0350%20AD-0001.Civ5Save?dl=0

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Ran 10 turns, no crash. Since you aren't on the 43-civ DLL try that DLL I linked in the other thread (the one you commented on).

**Comment by R3P0FFXI** [comment]
@LoneGazebo where do I place it exactly im not getting asked to overwrite any files when I try to place it in either of those 2 directories

**Comment by LoneGazebo** [comment]
Did you unzip it? You need to unzip the folder and place the CP in your (1) Community Patch folder in your MODS directory.

**Comment by R3P0FFXI** [comment]
@LoneGazebo please see the image my directory I do not see the a DLL there to replace.  All that I see in these folders are XML, LUA, or SQL files made when creating the mod.

https://imgur.com/a/Y6oS9

**Comment by LoneGazebo** [comment]
What does your full directory look like? The MODS directory?

**Comment by R3P0FFXI** [comment]
@LoneGazebo Here is the mods DIR and the 6a dir

**Comment by LoneGazebo** [comment]
Did you install the mod manually? Your install is missing the DLL! Anyways just drop the .dll into your CP folder. Looks like something is missing, though, possible that an antivirus program saw the DLL and deleted it without your permission.

G

**Comment by R3P0FFXI** [comment]
No I did  the automatic exe install, I actually do not have AV installed @LoneGazebo

**Comment by R3P0FFXI** [comment]
@LoneGazebo thanks the dll definitely fixed the issue thanks for the help now I must go kill Egypt because well I can

**Comment by LoneGazebo** [comment]
Sounds good!
