### ISSUE TITLE
War Weariness counter adds up even though I am not at war

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#360]
![8930_2015-06-24_00004](https://cloud.githubusercontent.com/assets/1131228/8337270/9db775fc-1ac3-11e5-8d95-3c3ecad63b50.png)
![8930_2015-06-24_00006](https://cloud.githubusercontent.com/assets/1131228/8337271/9f7f8410-1ac3-11e5-8e5d-db1d821e91c8.png)
I am not sure weariness mechanic is needed in the first place, looks like AI doesn't care about it and thus shoots itself in the foot.

**Comment by LoneGazebo** [comment]
It goes down with time - it does not instantly stop when not at war.

G

**Comment by Radost** [comment]
It went up by one point after I wasn't at war.

**Comment by ilteroi** [comment]
could we maybe make it so that war weariness is immediately reduced by half after making peace and the rest then slowly fades? i feel like there should be some immediate relief

**Comment by lukeroge** [comment]
+1 to ilteroi

**Comment by wileyhk2001** [comment]
+1 to ilteroi

**Comment by DanteValerian** [comment]
I agree, a peace treaty should instantly erode some portion of war weariness with that civ once it's executed. Maybe not half, I'm thinking a third. But half would be reasonable too.

**Comment by Danaan** [comment]
War Weariness does not go down at all even though I made peace with every nation and city state. Instead it kept going up for several dozen turns as population growth increased weariness cap.
