### ISSUE TITLE
Crash with VoxPopuli 10-17-1 after round 240

### ISSUE THREAD

**Issue by kiryph** [LoneGazebo/Community-Patch-DLL#3600]
_1. Mod version (i.e Date - 4/23):_

 **10-17-1**

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Crash to Desktop without any error message

_4. Steps to reproduce (optional):_

Use safe file and end turn

---------------------------
Supporting information:

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1404684/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Augustus Caesar_0240 AD-1650_ERR.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1404686/Augustus.Caesar_0240.AD-1650_ERR.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1404688/CvMiniDump.zip)

**Comment by LoneGazebo** [comment]
Just tested, cannot reproduce. Try this DLL, however, see if it fixes:

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1405552/CvGameCore_Expansion2.zip)

**Comment by kiryph** [comment]
Too bad that you cannot reproduce it.
However, crash to desktop (CTD) disappeared with dll from #3597. What is the difference between
https://github.com/LoneGazebo/Community-Patch-DLL/files/1405552/CvGameCore_Expansion2.zip
https://github.com/LoneGazebo/Community-Patch-DLL/files/1404410/CvGameCore_Expansion2.zip
