### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#3601]
_1. Mod version (i.e Date - 4/23):_
10/17
CTD on AI turn.
[CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1404821/CTD.zip)

**Comment by LoneGazebo** [comment]
Can't load your save. Modlist?

**Comment by matlajs** [comment]
flag promotions and RED. Anything diferent compared to older CTD reports.

**Comment by LoneGazebo** [comment]
Yeah you can’t leave out your mod list if you expect me to debug.

**Comment by matlajs** [comment]
sorry, next time i will do.
