### ISSUE TITLE
Civilopedia Failure if starting era is Industrial or later

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#3602]
_1. Mod version (i.e Date - 4/23):_ 10/17
_2. Mod list (if using Vox Populi only, leave blank):_ VP with EUI
_3. Error description:_ The civilopedia panels other than the first 5 panels no longer works. This bug only appear in games where starting era is Industrial or later (Rennaissance and before is fine)
_4. Steps to reproduce (optional):_ Start a game at industrial era. Open the civilopedia.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1404853/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![screenshot](https://user-images.githubusercontent.com/8081919/31861626-07bf691c-b731-11e7-8945-ed5f48a6a459.png)

**Comment by LoneGazebo** [comment]
Lua.log would be helpful.

**Comment by MoiMagnus** [comment]
It isn't already in the logs  I've send ?

**Comment by LoneGazebo** [comment]
It is an issue with the buildings list not showing up, the problem is that I don't know why it happens as the LUA is not explicit...

**Comment by MoiMagnus** [comment]
#3768
