### ISSUE TITLE
Corps, diplomacy and buildings

### ISSUE THREAD

**Issue by Miketsw** [LoneGazebo/Community-Patch-DLL#3603]
_1. Mod version (i.e Date - 4/23):_10-17-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I have recently installed the mod, (fresh civ 5 install and using the automatic installer, for VP with EUI) and several items do not appear to be working:
1. Clicking on the diplomacy button does nothing, no window opens.
2. Corporation screen - this doesnt list all the resources, only ever 1 (seemingly random) and does not have a tooltip, when you hover over the %, and the % id always at 0 even when you have a monopoly.
3. Several buildings seem to have conflicting benefits in the write, and do not seem to correctly apply: i.e University says that it add 1 science to forest/jungle, but i still get the old +2 science to jungle only. This error applies to many buildings, such as the herbalist which odes not appears to do anything.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
Quick debug :
1) Did you try reinstalling the mod. Sometimes it just happens
2) Make sure you don't have any steam version of the mod, such that the steam Community Patch, or the steam More luxuries. They conflict with the auto-installer. Similarly, if you had EUI by another way than the auto-installer, delete it.
3) Make sure you have the last version of the game, all the DLC (except map packs), and that you are playing the English version of the game.

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict to me.

**Comment by Miketsw** [comment]
Thanks for your response I uninstalled and reinstalled and now it is
working correctly,

Regards

Mike
