### ISSUE TITLE
Can Buy Archaeologists with Faith Without 'Knowledge Through Devotion'

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#3604]
_1. Mod version (i.e Date - 4/23):_
10-17-1

_2. Mod list (if using Vox Populi only, leave blank):_
Ethnic Units

_3. Error description:_ 
Once Archaeology is researched, Archaeologists can be purchased with Faith in cities with Public Schools even though 'Knowledge Through Devotion' was not selected for my religion.

_4. Steps to reproduce (optional):_
See provided save file for example. Of note: 'Knowledge Through Devotion' has not been selected by ANY Civ in this particular game, yet the option is still there to Faith-buy Dr. Jones.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[William_0394 AD-1768 Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1405286/William_0394.AD-1768.Save.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/3564
hmm...

**Comment by LoneGazebo** [comment]
I tested and can't reproduce this.

**Comment by cdanger341** [comment]
Did you check the save I attached? I loaded it again to double check and could still use my faith to purchase Archaeologists, even though my Reformation Belief was 'One World, One Religion'. Perhaps it's an EUI issue?

**Comment by LoneGazebo** [comment]
Link to ethnic units?

**Comment by cdanger341** [comment]
It's Nutty's continuation of the R.E.D. Modpack. Download link for version I use (v29b4): http://www.mediafire.com/file/fcvoo2uici9ogkv/Ethnic+Diversity+v29b4.zip

Forum location for it:  https://forums.civfanatics.com/threads/ethnic-diversity-r-e-d-unofficial.449070/

Also, I forgot to list it in the original ticket, but I have Flag Promotions mod turned on for that save file.

**Comment by LoneGazebo** [comment]
Still won't let me load.

**Comment by cdanger341** [comment]
Strange... You activated all 3 .civmod files for Ethnic Units, I assume?

I'm also using a terrain texture pack, but it's not a mod. It's one of those texture packs where you copy the texture files into your Civ5 install folder and overwrite the default textures, so I figured that wouldn't affect save files. Specifically, it is Terrain Texture Enhancement 2k v11 found here: https://forums.civfanatics.com/threads/terrain-texture-enhancement-2k.570307/
