### ISSUE TITLE
GameEvents.CityPrepared.Add doesn't work

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#3606]
_1. Mod version: 10-17-1

_2. Mod list: Own 3rd and 4th unique component for Poland and Iroquois

_3. Error description: I needed to keep track on great persons my cities generate (great diplomat). I wanted to use GameEvents.CityPrepared.Add(function(iPlayer, iCity, iSpecialist)
function but after using print statements and fire tuner it turned out it doesnt react. I also used similar functions GameEvents.CityTrained.Add(function(iPlayer, iCity, iUnit) and 
GameEvents.CityConstructed.Add(function(iPlayer, iCity, iBuilding) and they work well. They show me player and city after unit is trained or building constructed. There's no more content inside those statements.

Code I used for testing:
```
GameEvents.CityPrepared.Add(function(iPlayer, iCity, iSpecialist)
	local pPlayer = Players[iPlayer]
	local pCity = pPlayer:GetCityByID(iCity)

	local sPlayer = pPlayer:GetName()
	local sCity = pCity:GetName()

	print("1")
	print(sPlayer)
	print(sCity)
end)

GameEvents.CityConstructed.Add(function(iPlayer, iCity, iBuilding)
	local pPlayer = Players[iPlayer]
	local pCity = pPlayer:GetCityByID(iCity)

	local sPlayer = pPlayer:GetName()
	local sCity = pCity:GetName()

	print("2")
	print(sPlayer)
	print(sCity)
end)

GameEvents.CityTrained.Add(function(iPlayer, iCity, iUnit)
	local pPlayer = Players[iPlayer]
	local pCity = pPlayer:GetCityByID(iCity)

	local sPlayer = pPlayer:GetName()
	local sCity = pCity:GetName()

	print("3")
	print(sPlayer)
	print(sCity)
end)
```

And results:
1.Building finsished:
https://zapodaj.net/2981fec1d26c6.png.html
2.Unit finished:
https://zapodaj.net/7211f05cca9e6.png.html
3.Someone finished great person:
https://zapodaj.net/65610da1ac80d.png.html
4.I got Great Diplomat:
https://zapodaj.net/f6eec44abc07c.png.html

**Comment by LoneGazebo** [comment]
Going to rework it so that it, well, works. It will now be:

GameEvents.CityPrepared.Add(function(iPlayer, iCity, iSpecialist, iAmount, iNeeded)

**Comment by LoneGazebo** [comment]
iAmount = GP rate per turn; iNeeded = GP threshold

**Comment by adaneslavo** [comment]
Great. Thank you.

**Comment by adaneslavo** [comment]
I tested last patch you prepared. This function still doeasn't react:
```
function GiveDiplomaticReciprocityPromotion(iPlayer, iCity, iSpecialist)
	local pPlayer = Players[iPlayer]
	
	print("dziala dawanie")
	if pPlayer:GetName() == "Hiawatha" then
		local pUnit = pPlayer:GetUnitByID(iSpecialist)
		print("daje progress")
		if pUnit:GetUnitType() == GameInfoTypes.UNIT_GREAT_DIPLOMAT then
			local pCapital = pPlayer:GetCapitalCity()
			print("jest wielki dyplomata")
			if pCapital:IsHasBuilding(GameInfoTypes.BUILDING_IROQUOIS_SACHEMS_COUNCIL) then
				print("jest sachem wiec daje")
				pUnit:SetHasPromotion(GameInfoTypes.PROMOTION_UNIT_IROQUOIS_DIPLOMATIC_RECIPROCITY, true)
			end
		end
	end
end

GameEvents.CityPrepared.Add(GiveDiplomaticReciprocityPromotion)
```
Did you change something or left it for later times?
