### ISSUE TITLE
Production Focus not working

### ISSUE THREAD

**Issue by Albuquerquegithub** [LoneGazebo/Community-Patch-DLL#3607]
_1. Mod version (i.e Date - 4/23):_
10/18/17

_2. Mod list (if using Vox Populi only, leave blank):_
(1) Community Patch (v 88) (NOT Vox Populi)

_3. Error description:_ 
In the city screen, under citizen management, the production focus is clearly bugged and it wont change the citizen to the desired high production tile as it should. This problem is solved when I start a game without loading the mod.

_4. Steps to reproduce (optional):_
Start new game, settle capital, and change citizen to production focus (make sure there is a high production tile in the radius).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
The city will not drop below a certain food per turn threshold at small sizes. This is by design.

G
