### ISSUE TITLE
SetHappiness(int iHappiness) problem

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#3608]
_1. Mod version: 10-17-1

_2. Mod list: Own 3rd and 4th unique component for Poland and Iroquois

_3. Error description: I wrote line of code like below:
```
pPlayer:SetHappiness(pPlayer:GetHappiness() + iHappiness)
```
in the function and then called it using:
```
GameEvents.PlayerDoTurn.Add(defensivePactOrWar)
```
Problem I encoutered you can see in the picture below (iHappiness = 3):
https://zapodaj.net/cd9c7cdd3995e.png.html
As you can see my flat "iHappiness" is added to the value of "Happiness from the difficulty level", but it's not taken to the calculations. Final value should be:
```
8 (basic happiness) + 3 (iHappiness) - 5 (unhappiness) = 6
```
but because my iHappiness isn't taken into calculations the value equals 3. SetHappiness function is then useless now. My value of iHappiness will dynamically change each turn so this function is vital for my work. Can this be repaired?

**Comment by LoneGazebo** [comment]
It’s not useless but you have to update the top panel Lua to include your bonus in the final calculation. I’m not going to do that for you.

**Comment by adaneslavo** [comment]
So the final result of player happiness is 6 if understand correctly. The only thing is to make it appear on the top panel, right?

**Comment by LoneGazebo** [comment]
What you are trying to do (if recalculating it every turn) won't work as you intended, and there's not really a good way to do it so abruptly. Better to do a building or city effect than a player level effect. Even a dummy building would work better.

**Comment by adaneslavo** [comment]
Ok. Thank you. I was afraid that dummy building will be my next problem to resolve. But you need to admit that this function doesn't work as it is supposed to be and this is probably issue since vanilla civ 5. Maybe it would be good to make it work? Nevertheless, I will try to fight this problem by myself. Cya.
