### ISSUE TITLE
Belief Wording

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#3609]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

Goddess of festivals effect is worded poorly for what it actually does. says it gives bonuses for "resources you control" but if you control 1 cocoa, then trade that copy, you lose your belief bonuses from it. also, just because i gain access to a luxury from a city state ally or through buying it doesnt mean i "control" it, but those will give bonuses.

simple change of wording from "resources you control"  to "resources you currently have access to" would make clear beyond any doubt how this works.  Ive been playing for years and never chose that belief, but I had to do testing when I did pick it just to find out how it actually functions

also, it should be made clear the bonuses are for your capital only

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by deadstarre** [comment]
actually, in keeping with the same wording that the happiness tooltip already uses it should read " xx bonus for every unique luxury resource you have a source of"

**Comment by matlajs** [comment]
i have actually picked this in my Netherland game for the same reason, just try it out. same confusion.

**Comment by cdanger341** [comment]
Yes, the first time I played with Nu Netherlands I tried this Pantheon thinking it worked on the same logic as the Netherlands UA, but it does not. The tricky part comes in the terminology of "controlling a luxury resource", as you can "control" a resource and then trade it away, making it controlled (as far as monopolies go) but unavailable to your population. The Pantheon only counts luxury resources that are actually available for use by your citizens, but are also not imported. If the Pantheon was changed to still "count" luxuries you traded away, then we could keep the "controlled" wording, otherwise it's not entirely accurate. It's not a super-great Pantheon anyway, so maybe this change could be made?

**Comment by matlajs** [comment]
i actually do not know how does it work. i got more faith than i had unique luxuries(by that time just spices and olives), more than improved luxury tiles, but little less than overall all luxuries i have had(imported from cs, bought from another leader).

**Comment by LoneGazebo** [comment]
I'm just going to change the mechanic behind it to count all resources controlled, including exports and, if valid, imports (i.e. from UA or CS policy)

**Comment by deadstarre** [comment]
The only other instance of the word "control" anywhere is in the monopoly window, so to keep things unambiguous and clear there is no reason to use the word "control" still if it pertains to luxuries you import- imported luxuries are not sources you control.

**Comment by RandomNub** [comment]
If the yelds are going to be as they're now, that's going to make the pantheon incredibly weak during the early game, if you're not NED. Or OP, if with 'all resources controlled' you mean multiple copies as well.

It was an okay pantheon balance wise, the issue was it being poorly worded.
