### ISSUE TITLE
Surveillance results stacking up

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#361]
![8930_2015-06-24_00007](https://cloud.githubusercontent.com/assets/1131228/8354300/803ab398-1b60-11e5-98bf-d1bc6473492d.png)
![8930_2015-06-25_00001](https://cloud.githubusercontent.com/assets/1131228/8354301/811de0aa-1b60-11e5-9375-aecfaa43b706.png)
Provided they give 0 in-game benefit (99% of operations get canceled), it's pretty strange they can give more diplo modifier value than even the same ideologies.

**Comment by LoneGazebo** [comment]
99%?  Not exactly. Maybe 30%. A lot of the 'aborts' are actually the end of successful operations.
Anyways, that's so high because Firaxis didn't put a cap on the value. I've capped it at 3x the initial value (-60). That seems fair.

G

**Comment by Radost** [comment]
I mean they don't have any in-game value compared to defensive pacts, DoF, DoW and basically anything and serve as almost free diplo modifier.

**Comment by DanteValerian** [comment]
I agree that the share intrigue modifiers seem OP at the moment. Capping the stacking modifiers should fix it.
