### ISSUE TITLE
AI negative GPT

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3613]
_1. Mod version (i.e Date - 4/23):_
17 october

_2. Mod list (if using Vox Populi only, leave blank):_
WorldCongressReinform
PoorTilesTweak

_3. Error description:_ 
Map: Huge , 16 players, 32 CS, Immortal, Epic speed, Events on, Barbarians on.
Babylon AI has Huge negative GPT, I noticed it only at turn the screen is.
It is some event or what? Look at "-1 output of all cities"
Top AI that I know has 18 techs, me 14 techs, Babylon 7 techs (
I think he got some event(-2 to gold in each city and it ruin all for Babylon(maybe he was in Golden Age when select that event and after GA ends he start to go in deep gpt loss)

![20171026130646_1](https://user-images.githubusercontent.com/13381981/32047514-d1de9d74-ba4e-11e7-9c93-a803135d6488.jpg)

**Comment by LoneGazebo** [comment]
Yeah, probably. Event fades.
