### ISSUE TITLE
Feature Request: City View

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#3614]
-1 Feature Request: I can see that you improve EUI components step by step. When I play I am often annoyed by one thing. When I add something to city building queue, the icon (with gold number) which allow making investment disappears. Then if I want to invest in that building (assuming it is still possible) I need to unqueue that building and check the gold amount needed to do so. Then if I have enough gold I invest on it, queue it again and wait to finish.

So my question is: Could you add a possibility to invest on queued features without taking them out from queue?

**Comment by LoneGazebo** [comment]
Not possible sorry. I avoid touching EUI like the plague. 

G

**Comment by adaneslavo** [comment]
Ahh, ok. No problem. This just would make play more intuitive. Only for your information, because maybe someday you will change your mind, I saw something like that in mod "Improved City View v9". This could help you some then.
