### ISSUE TITLE
Issue with Future Tech progression

### ISSUE THREAD

**Issue by BoxJockey** [LoneGazebo/Community-Patch-DLL#3615]
_1. Mod version (i.e Date - 4/23):_

9/27

_2. Mod list (if using Vox Populi only, leave blank):_

Info Addict v 22
Faster Aircraft Animations v 3
Map Pins v 17

_3. Error description:_ 

Playing Japan/Immortal/Marathon . Tech progression is normal until I hit Future Tech (Fusion took 19 turns to research at approx 10k science). Once I'm on Future Tech though I'm getting many advances per turn, 6 or so at the start of the turn, 1 or 2 for rush building, etc.

Science progress towards FUTURE TECH 453761 / -211563

_4. Steps to reproduce (optional):_

Save attached

[AutoSave_1038 AD-1950-January.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1419933/AutoSave_1038.AD-1950-January.zip)

[net_message_debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1419956/net_message_debug.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I can't reproduce this...
