### ISSUE TITLE
workers trying to make road throw vassal's land

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3616]
_1. Mod version (i.e Date - 4/23):_
17-10

_3. Error description:_ 
Automated workers try to make road throw my vassals land. But as I know, it is impossible now. 
So they just stay and stay and do nothing. :(

![20171026234849_1](https://user-images.githubusercontent.com/13381981/32076321-390bff10-baa8-11e7-8fd7-b9e8717b3832.jpg)

**Comment by bigcat88** [comment]
and something that not related to vassals: if road just go to other city(not even friendly) - workers spend free time(?) on road(waiting for war to die?)
maybe I see such thing when I was on island and build a road to citadel(for fast embark) - workers just stay on each tile to citadel(that game was maybe month ago)

And there is undefined red square on worker, when select it(looks like unknow tile recommendation, maybe he propose to remove road?)

![20171030174615_1](https://user-images.githubusercontent.com/13381981/32180353-650d69a6-bd9a-11e7-93dc-7e1b0997befc.jpg)

**Comment by deadstarre** [comment]
this is a really annoying bug right now actually, i can hardly automate workers cause they just end up on the borders of my empire doing nothing standing on roads that lead to nowhere, even while there are things they could be improving instead
