### ISSUE TITLE
Organized Relgion does not provide faith cost reduction

### ISSUE THREAD

**Issue by rahenry** [LoneGazebo/Community-Patch-DLL#3619]
EDIT: Reinstalling VP fixed the problem, apologies! I swear I had tried reinstalling previously :|

_1. Mod version (i.e Date - 4/23):_
10-7

_2. Mod list (if using Vox Populi only, leave blank):_
VP (all components)
FlagPromotions
Historical Religions
Improved City View
InfoAddict
Really Advanced Setup
Reseed

_3. Error description:_ 
Organized Religion (Fealty policy) does not apply the faith reduction to anything as far as I can tell.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
in my game it works(as I remember), if will have later time, will check for sure

**Comment by rahenry** [comment]
Reinstalling VP fixed it, sorry for the non-issue.

**Comment by bigcat88** [comment]
there is a button  "close" )
