### ISSUE TITLE
Can't attack a ship in a fort with a melee ship

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#362]
But attacking "forted" ships with land melee units works just fine.
![8930_2015-06-25_00005](https://cloud.githubusercontent.com/assets/1131228/8354490/e77c5060-1b61-11e5-8539-6e1cdd57e23a.png)

**Comment by LoneGazebo** [comment]
That's a restriction of how the 'use forts as canals' function works. Sorry.
G
