### ISSUE TITLE
Events Requirement 

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#3622]
G,
Does `<HasTradeConnection>true</HasTradeConnection>` mean that the City must have an internal trade route sent to it?

**Comment by LoneGazebo** [comment]
No, refers to trade connection period (internal or external).

**Comment by Hokath** [comment]
Ok. I'm not sure it is working. Then today in a thread someone also noted that the event with this in had never occurred for them.

**Comment by LoneGazebo** [comment]
`if(pkEventInfo->hasTradeConnection() && !HasTradeRouteFromAnyCity() && !HasTradeRouteToAnyCity())
		return false;`

code looks fine (line 4116 of cvcity.cpp)

**Comment by Hokath** [comment]
Must just be a fluke. Thanks for checking.
