### ISSUE TITLE
VP wiki feature request

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#3624]
I don't know where to modify the template of the VP wiki.
I would want to add a case "purchase cost" to the unit template : 
![wiki](https://user-images.githubusercontent.com/8081919/32220063-937fcf90-be30-11e7-825a-298f7f10c65a.png)
It already exists for faith, but I don't know how to add it for gold.

Note that it may already exists, but since I don't know where is the documentation of the wiki, I don't know what I am supposed to type in the code editor.

**Comment by MoiMagnus** [comment]
Same thing with upgrade cost.

**Comment by LoneGazebo** [comment]
Ask @techpriestenginseer

**Comment by TechpriestEnginseer** [comment]
Aren't purchase cost and upgrade cost considerably unreliable as they can fluctuate within later eras? Nevertheless I can add this in the template if this is wrong.

**Comment by MoiMagnus** [comment]
I think upgrade cost do not vary.
However, it is true that buying cost of units such as workers vary a lot. But for standard militaristic units, since they are available only during one-two eras, it should not cause problems.

**Comment by TechpriestEnginseer** [comment]
Done, use purchasecost and upgradecost

**Comment by MoiMagnus** [comment]
Thank you. Next time I have some time to lose, I will complete the wikia with the values.
