### ISSUE TITLE
Fishing Boat Movement

### ISSUE THREAD

**Issue by thecrafybee** [LoneGazebo/Community-Patch-DLL#3628]
_1. Mod version (i.e Date - 4/23):_

Using latest version 17th Oct? but have had this issue for an age
_2. Mod list (if using Vox Populi only, leave blank):_

Civic Reforms
IGE
VP Compatability Patch with Unique Policy Buildings/Neolithic Wonders/Pontoon Bridge
Unique City States
World Congress Reformation
Events and Decisions - 7 & 8
Quick Turns
Reforestation
Antiquity Sites Fillers
Meaningful CS Colours
Really Advanced Setup
VP Improved City View
Whoward's City Religion; City Production; Diary; Specialist Summary; Enhanced Demos

_3. Error description:_ 

When directing my fishing boats to move to a certain area, it will usually only move 1 tile and then switch to the next unit needing attention.  It doesn't always do this and sometimes works properly.  I think it happens more often when I want a fishing boat to go around a peninsula, but I'm not sure of the pattern of this happening, but it happens a lot.  I'm used to it now but it is still slightly annoying and I'm not sure if it is a problem in the base game as I have played VP exclusively for a long time.

I mainly use Hellblazer's Pangaea map script, but I'm vertain I had the problem with Communitas and Planet Sim too.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
This was an old issue with regards to danger, see if the latest fixed it.
