### ISSUE TITLE
Mongol UA Triggers to Easily

### ISSUE THREAD

**Issue by DanteValerian** [LoneGazebo/Community-Patch-DLL#363]
Although this has been debated before, and I realize it may be working as intended, the way the Mongol UA works is just a nuisance. Furthermore it hampers Genghis if he's at negative unhappiness, which is quite often.

I turn Mongolia off in my games to prevent runaway craziness with CS's being kidnapped out of nowhere, without warning, one after another (I'm putting this here at Gazebo's request)

**Comment by LoneGazebo** [comment]
I actually figured this out - I had forgot to set a bool test for the mongols when they triggered this in their diplo AI turn, so they were doing it illegally! D'oh.

I've also set a 30 turn cooldown (Scaled to game speed) after a minor civ is liberated during which time it'll be impossible to bully them.

G
