### ISSUE TITLE
Placing a unit in an allied city won't increase the city defense

### ISSUE THREAD

**Issue by l29ah** [LoneGazebo/Community-Patch-DLL#3631]
_1. Mod version (i.e Date - 4/23):_
10/17

_2. Mod list (if using Vox Popu
![Uploading screenshot-memphis-8.png…]()

li only, leave blank):_

_3. Error description:_ 
Placing a unit in an allied city won't increase the city defense strength.

![screenshot](https://a.doko.moe/nvviyn.png)

**Comment by TechpriestEnginseer** [comment]
They're not exactly garrisoned(Unit UI stationed to the left of the City Defense) and therefore cannot increase the city defense strength.

**Comment by l29ah** [comment]
what

**Comment by l29ah** [comment]
They just die w/o any resistance when the city is taken. This doesn't look like a sensible behaviour.

**Comment by LoneGazebo** [comment]
What you are doing is undefined behavior. Never supposed to have units in other people’s cities unless you are conquering them.

**Comment by l29ah** [comment]
On Fri, Nov 03, 2017 at 01:35:03PM +0000, LoneGazebo wrote:
> What you are doing is undefined behavior. Never supposed to have units in other people’s cities unless you are conquering them. 

I've sold the city with my unit standing in it.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by afwbkbc** [comment]
You aren't supposed to sell damaged city.
Please make damaged cities untradeable.
Otherwise he just gifts cities with 1hp to vassal and city immediately gets 150hp. At least it doesn't get defense bonus from unit he had there.
He's just a cheater and game bug abuser, plz ignore him.
