### ISSUE TITLE
Combat functions problem

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#3636]
_1. Mod version: 11-1
_2. Mod list: own mod.
_3. Error description: I used code like below:
```
function Leiomano(iAttackingPlayer, iAttackingUnit, attackerDamage, attackerFinalDamage, attackerMaxHP, iDefendingPlayer, iDefendingUnit, defenderDamage, defenderFinalDamage, defenderMaxHP)
	print("works after battle")
end

function test(iPlayer)
	print("test")
end

GameEvents.CombatResult.Add(Leiomano)
GameEvents.CombatEnded.Add(Leiomano)
Events.RunCombatSim.Add(Leiomano)
Events.EndCombatSim.Add(Leiomano)
GameEvents.PlayerDoTurn.Add(test)
```
I also turned on custom mod options:
```
--Koa Combat
UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'EVENTS_RED_COMBAT'

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'EVENTS_RED_COMBAT_RESULT'

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'EVENTS_RED_TURN'

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'EVENTS_RED_COMBAT_MISSION'

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'EVENTS_RED_COMBAT_ABORT'

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'EVENTS_RED_COMBAT_ENDED'
```
The only funtion which react in this code is PlayerDoTurn placed there for testing purpose. What triggers the rest of them? I tested attacking vs Barbarians and nothing happened.

**Comment by LoneGazebo** [comment]
I didn't write any of this code, you'd need to ask whoward on the forums.

**Comment by adaneslavo** [comment]
Ok. And If I want to run only "GameEvents.CombatResult.Add" event then do I need to turn on only "EVENTS_RED_COMBAT_RESULT" value or all six of them?

Those two:
```
Events.RunCombatSim.Add(Leiomano)
Events.EndCombatSim.Add(Leiomano)
```
are default functions from modiki. Did you turn them off because they also didn't trigger.

Anyways I will probably write to Whowards.

**Comment by Padre19** [comment]
GameEvents.CombatEnded.Add  works for me with:

UPDATE CustomModOptions SET Value=1 WHERE Name='EVENTS_RED_COMBAT';

UPDATE CustomModOptions SET Value=1 WHERE Name='EVENTS_RED_COMBAT_ENDED';

**Comment by TechpriestEnginseer** [comment]
````
GameEvents.CombatResult.Add(Leiomano)
GameEvents.CombatEnded.Add(Leiomano)
Events.RunCombatSim.Add(Leiomano)
Events.EndCombatSim.Add(Leiomano)
````

These should never have the SAME function names.

**Comment by adaneslavo** [comment]
@Padre19 How do you trigger that function? I tested all 4 alone and after performing combat neither print statement shows up. I have all 6 EVENT_RED options enabled. Could you post your code?

**Comment by Padre19** [comment]
function OnCombatEnded (iAttackingPlayer, iAttackingUnit, _, _, _, iDefendingPlayer, iDefendingUnit, _, defenderFinalDamage, defenderMaxHP, _, _, _, plotX, plotY)
    if iAttackingPlayer == -1 then return end
	local delay = 0
	local attackingPlayer = Players[iAttackingPlayer]
	local defenderPlayer = Players[iDefendingPlayer]
	local attackingUnit = attackingPlayer:GetUnitByID(iAttackingUnit)	
	local defenderUnit = defenderPlayer:GetUnitByID(iDefendingUnit)
	local defenderHealth = defenderMaxHP - defenderFinalDamage
    local c = 0

	if attackingPlayer:HasPolicy(GameInfo.Policies["POLICY_RESOLUTION_ABOLITIONISM"].ID) or attackingPlayer:IsBarbarian() then
		return;
	end
	if defenderUnit and defenderHealth <= 0 then				
			if attackingUnit:IsHasPromotion( GameInfo.UnitPromotions["PROMOTION_CAPTURE_VERY_EARLY"].ID ) then c = c + 12;        
			
			elseif attackingUnit:IsHasPromotion( GameInfo.UnitPromotions["PROMOTION_CAPTURE_LATE"].ID ) then c = c + 14;
			
			elseif attackingUnit:IsHasPromotion( GameInfo.UnitPromotions["PROMOTION_CAPTURE_SECOND"].ID ) then c = c + 17;
			
			elseif attackingUnit:IsHasPromotion( GameInfo.UnitPromotions["PROMOTION_CAPTURE_EARLY"].ID ) then c = c + 21;
			
			elseif attackingUnit:IsHasPromotion( GameInfo.UnitPromotions["PROMOTION_CAPTURE"].ID ) then c = c + 25;
			end
			local finalfactor = math.ceil(c + (((defenderPlayer:GetUnhappinessFromWarWeariness()) * 0.1) * c))
			if (attackingPlayer:HasPolicy(GameInfo.Policies["POLICY_ARISTOCRACY"].ID)) and not defenderPlayer:IsBarbarian() then finalfactor = finalfactor * 1.2
              end
			local finalfactorH = finalfactor
			if (attackingPlayer:IsPolicyBranchUnlocked(GameInfoTypes.POLICY_BRANCH_HONOR)) and defenderPlayer:IsBarbarian() then finalfactorH = finalfactorH * 1.25
	end
			local finalfactorfinal = finalfactorH
		if (defenderPlayer:HasPolicy(GameInfo.Policies["POLICY_PROFESSIONAL_ARMY"].ID)) then finalfactorfinal = finalfactorfinal * 0.75
	end	
	local finalfactorfinalhuman = finalfactorfinal
			if attackingPlayer:IsHuman() then finalfactorfinalhuman = finalfactorfinalhuman * 0.8
			end
		
			if JFD_GetRandom(1,100) < finalfactorfinalhuman then
						local newUnit = attackingPlayer:InitUnit(GameInfoTypes["UNIT_SLAVE"], attackingUnit:GetX(), attackingUnit:GetY() )
						newUnit:JumpToNearestValidPlot();
						LosepopCitySlv(defenderPlayer);
				
					Events.AddPopupTextEvent(HexToWorld(ToHexFromGrid(Vector2(attackingUnit:GetX(), attackingUnit:GetY()))), "[COLOR_POSITIVE_TEXT] Slave captured! [ENDCOLOR]", delay)
                                delay = delay + 0.5
					if attackingPlayer:IsHuman() then				  
					Events.AudioPlay2DSound("AS2D_SOUND_JFD_SLAVERY");
				end
			end
	    end
end

**Comment by adaneslavo** [comment]
I placed your code. Unfortunately after attacking barbarian unit right from start nothing happens.

What version of VP do you use? I mean which components? I use 43-civ EUI version from 11-1. Could this be a problem?

**Comment by Padre19** [comment]
VP 11-1 EUI
 In my mod just some units (with moded personal promotions  ) have chance to capture slave.
Without these promotions chance is 0.

**Comment by Padre19** [comment]
For testing change local c = 100 and Unit slave with unit worker.

**Comment by adaneslavo** [comment]
Problem resolved. RED functions work. In SQLs semicolons were missing. Anyways thank for your time and I'm sorry I bothered you.
