### ISSUE TITLE
spirit of desert is not giving bonus for oasis

### ISSUE THREAD

**Issue by lapuvida** [LoneGazebo/Community-Patch-DLL#3638]
_1. Mod version: 11-1-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
-no food bonus for oasis upon choosing spirit of desert; other bonuses for improved resources work as supposed (tested with wheat/farm only so far)

_4. Steps to reproduce (optional):_ 
- new game until pantheon choice, pick spirit of desert, have no food bonus for oasis (only tested two times with harun)

**Comment by LoneGazebo** [comment]
Mm, yeah. Going to require me to rework SoD a little bit...
