### ISSUE TITLE
Stupa providing full yields without required tech (architecture)

### ISSUE THREAD

**Issue by Rauzer** [LoneGazebo/Community-Patch-DLL#3642]
_1. Mod version (i.e Date - 4/23):_
11/1 latest hotfix (grabbed it on 11/4)

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi with NoEUI version

_3. Error description:_ 
Stupa gives tourism and golden age points before architecture is researched

Couldn't figure out why the huns had 40 tourism a turn on turn 100, eventually when he spread religion to one of my cities and i bought a Stupa, my tourism and golden age points per turn also jumped up. Huns aren't at architecture yet, and i most definitely am not. Huns don't have reformation belief either

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

n/a, no error and i don't have logging turned on

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

no error but attached a save game where i just bought the Stupa (camera should be ontop the city, but if not, it's Lublin, top left from my capital)

[Casimir III_0152 AD-0840.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1444208/Casimir.III_0152.AD-0840.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

n/a

4. Screenshots (optional):

https://snag.gy/Nt27E5.jpg city overview with the tourism yield highlighted

**Comment by cdanger341** [comment]
I would like to add that this bug also appears to be affecting other buildings that gain a Tourism yield later once a certain tech is researched (like the Arena). I am using version 11-1-3 with the EUI version of VP installed.

**Comment by LoneGazebo** [comment]
It is WAD, the tooltips are simply out of date.
