### ISSUE TITLE
Maybe it is a trouble with statecraft branch and GreatAdmiral resources

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3644]
_1. Mod version (i.e Date - 4/23):_
11-1-3

_3. Error description:_ 
Looks I found some strange situation. Only one CS in world with glass.
I was planning to take statecraft and get that monopoly for corporation.
After I take statecraft, my spy died during coup. I send diplomats, they make me happy. But I don't get monopoly(yeah I see those my 100% of glass in monopolies).
After that(one hour later after I understand what happens) I created a duel map, trying to reproduce the same - but all was ok, monopoly was granted after diplomats(tested on porcelain). So the reason was not in diplomats.
I load my game, open IGE - place DeadRobots - capture CS and don't get monopoly after capturing.
After that I see that Rome has 2 glass(looks like from GreatAdmiral) and has his 200%.
So maybe that why I cant get monopoly? Is it so intended? Or it is a bug? I don't know how to reproduce this(maybe in hotseat multiplayer with IGE?) Or I can attach savegame(there are no mods, except one) if u needed. I am not sure that problem in Rome's glass, but I don't see any other reason for that.

**Comment by LoneGazebo** [comment]
If the resource is not physically on the map, you can't get a monopoly from it. i.e. admirals.

**Comment by bigcat88** [comment]
I know about that. Resource is on map, CS owns it.

**Comment by LoneGazebo** [comment]
Yes, only one player can have it.

**Comment by bigcat88** [comment]
So situation when only one CS with glass , u got it with statecraft, then someone use GA and got 2 glass, then u lost CS for somereason. After that u will not be able to get monopoly if become an ally of cs or if u will conquer it. Am I undesrstand right? Cause someone will have already monopoly with 200% of resource and u only 100%.
And if so, then will a player lost monopoly in the same turn when someone will get it with GA ?

**Comment by LoneGazebo** [comment]
well, you should never get glass from an admiral GA.

G

**Comment by bigcat88** [comment]
Well in my current game both me and Denmark AI has monopoly on coffee. Coffee is the only in the world.
Denmark has 300%(conquered those my CS with coffee + admiral) , I have 200%(just admiral).
So 2 people have monopoly. From my current turn:
![untitle2d](https://user-images.githubusercontent.com/13381981/32467381-1c0d6968-c353-11e7-8237-9bc504546626.png)

**Comment by LoneGazebo** [comment]
Well Admirals can't give luxuries that are on the map, so that's not entirely supported by the code...if you've added resources to the map via IGE that can cause this kind of bug to happen.

**Comment by bigcat88** [comment]
No. I don't know how to add resources like glass with IGE (

I understand what happens and why this games differs from others. I play map throw preset, I press "save map" and then load it throw "set up a new game". Looks like this was a bad idea(cause I have some strange tourism problems with boredom) - now I know, saving a map and play it is a bad idea.

But this is good, now I know that this leads to bugs and so I will not do it. Sorry for distracting, thanks for the help. Just need to forget about the "save map" button from the save menu)

**Comment by LoneGazebo** [comment]
No worries.

**Comment by bigcat88** [comment]
And a little comment: GA gives you resources that are present on map(untouched map, no resources were added throw IGE). First they give u resources that are not present, after that they can give u resources from map. So maybe there can be such situation like in this topic.

**Comment by bigcat88** [comment]
In new game without mods(only ReallyAdvancedSetup - without any options) - the same. Looks like the trouble is in statecraft policy(maybe some data that holds which res are present on map breaks when res begins to count from CS allies?). After I see that first AI get monopoly from statecraft - I used my 4 GA(I was Rome) for res and got 2 res from map. Before that(before some AI get full statecraft branch) 3 GA gives me Brazilwwod,Brazilwood and one more res that wasn't present on map)
In a few days - can make a test game for this
