### ISSUE TITLE
YIELD_TOURISM in UnitPromotions_YieldsFromKills doesn't work

### ISSUE THREAD

**Issue by theazuresoul** [LoneGazebo/Community-Patch-DLL#3645]
_1. Mod version (i.e Date - 4/23):_
11/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm trying to add a custom promotion that gives tourism on kills.
INSERT INTO UnitPromotions_YieldFromKills
			(PromotionType, YieldType, Yield)
VALUES		('PROMOTION_TOURISM', 'YIELD_TOURISM', 200);
When a unit with the promotion completes a kill, a tourism gain is displayed.
![image](https://user-images.githubusercontent.com/14305768/32425794-91127846-c26a-11e7-9314-1980891da160.png)
But in the culture overview, I find that I have not gained tourism against any of the other civs.
![image](https://user-images.githubusercontent.com/14305768/32425806-a9672fb8-c26a-11e7-9e59-6244944c0210.png)

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
Yeah, it won't, not hooked up. Not all yields are unified like that, too much spaghetti.
