### ISSUE TITLE
Random mass promotions

### ISSUE THREAD

**Issue by Reffy2** [LoneGazebo/Community-Patch-DLL#3653]
_1. Mod version (i.e Date - 4/23): Version date: 11-1-3

_2. Mod list (if using Vox Populi only, leave blank): Info Addict, EUI, Simple Clock (which is unnecessary, since EUI adds a better clock) 

_3. Error description: Al my units get promoted and I don't know why. I did nothing. Also, I'm at war with Maya and they send their great general alone to my city which has lots of units.

_4. Steps to reproduce (optional): Click next turn. 

[Random promotions save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1462559/Random.promotions.save.zip)
![promotions](https://user-images.githubusercontent.com/19254614/32675952-ff7381f8-c658-11e7-950e-cd056f6873e8.jpg)

**Comment by Voker57** [comment]
Could it be that you fullfilled city-state quest "capture a city"? It gives all units XP.

**Comment by Reffy2** [comment]
You are correct. 

I'm not familiar with city state quests. So, it's not a bug after all. 

Thanks.
