### ISSUE TITLE
Road maintenance cost aren't included for unfinished roads

### ISSUE THREAD

**Issue by l29ah** [LoneGazebo/Community-Patch-DLL#3657]
This encourages micro-management: gradually build the road between cities except the last building turn, then finish it all at once.

**Comment by bigcat88** [comment]
And what u want? Unconnected tiles with roads with no cost?

**Comment by Voker57** [comment]
Tiles with unfinished roads for full cost.

**Comment by LoneGazebo** [comment]
Can’t do that.
