### ISSUE TITLE
ExperiencePercent in UnitPromotions not allowing Negative Values

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3659]
Could you check to see if ExperiencePercent allows for negative values? That is, reduces the amount of XP a unit gains from combat. If not, could you allow it to do so for the next update. Thanks.

**Comment by LoneGazebo** [comment]
It did not, but it does now.

**Comment by JFDaly** [comment]
Awesome, thank you.
