### ISSUE TITLE
Navy units can't enter alert mode while being stationed in a city.

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#366]

**Comment by LoneGazebo** [comment]
I think that's by design – naval units can't 'fortify,' especially on land.
G

**Comment by Radost** [comment]
But they can enter into alert mode in a coastal tile.
It's less about fortify and more of waking up the moment the spot the enemy.

**Comment by LoneGazebo** [comment]
Gotcha, misunderstood your intent. I'll take a look.
G
