### ISSUE TITLE
Influence decay still -1 when above 100

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#3661]
_1. Mod version (i.e Date - 4/23):_

6/11

_2. Mod list (if using Vox Populi only, leave blank):_

Tested only with Vox Populi and IGE to avoid any possible conflict originated by Unique City States.

**Comment by TechpriestEnginseer** [comment]
1000 not 100.

**Comment by Mitchsp** [comment]
Oh I was almost sure that was changed to > 100 after the initial implementation where it decayed even under 100. Thanks for the clarification, my mistake.
