### ISSUE TITLE
Massive boost to yields after founding a pantheon.

### ISSUE THREAD

**Issue by Regularitee** [LoneGazebo/Community-Patch-DLL#3662]
A user called "Moi Magnus" from the CivFanatics forum asked me to cross post my forum post here. Said it was an outstanding issue that has happened before to others, but a lack of cause prevented it from being resolved. So I'm posting this here as he asked.

Now to the bug itself. The short version is that nations that AIs that found a pantheon will get +150 food, hammers, science, and gold per turn (I found this out by using IGE (InGame Editor) to swap seats and inspect their cities) for a number of turns. The tooltip for all these bonuses reads, "from religion". I don't know if this is capital only, or applies to all cities, since this point in the game is usually early enough they have only one city. This +150 to yields causes the game-breaking issue of them researching multiple techs per turn, or producing wonders every few turns.

I just download the CPB pack yesterday from this link ( https://mega.nz/#F!DMsxkDYI!zSpR9CHpmAfWyIvMXaN3pw ). 

No save available, since I overwrote it when trying to toggle various mods on and off to narrow down the cause of the bug. But if it helps, my mod list:

> (1) Community Patch
> (2) CB Overhaul
> (3) City-State Diplomacy...
> (4) C4DF - CPB
> (5) More Luxuries - CBO Edition
> 
> All the above were downloaded yesterday, so assume most recent version. I also had other 3rd party mods installed, but they were mostly cosmetic or superficial for the most part:
> 
> - In-Game Editor
> - City limits (lets you see city working radius)
> - InfoAddict (graph-maker)
> - Strange Religions (cosmetic mod)
> - Buildings - Upgrade System (by BlouBlou). Just adds duplicates of existing buildings with higher bonuses and upkeep, so I don't think it's the cause.

**Comment by Regularitee** [comment]
Update: 

Did some more testing by starting a new game in marathon mode and using IGE to assign pantheons. My tests seem to hint it's caused by "God of All Creation" pantheon (+1 foods, hammers, science, and gold per two existing pantheons).

I haven't ruled out other pantheons also causing this issue, or the issue originating in a mod conflict of some sort -- but the "God of All Creation" pantheon seems to be a consistent trigger of this bug.

**Comment by Regularitee** [comment]
I suspect I may have found the cause, not absolutely certain, but: 

I think it's caused when the God of All Creation spawns first, which might be causing a division error. I've had difficulty reproducing the bug when the pantheon spawned as one of the later pantheons, but it seems perfectly reproducible when it's one of the first pantheons that spawn.

Can anyone else verify?

**Comment by deadstarre** [comment]
I picked GOAC first in my most recent game, im sure because it was momentarily annoying to pick it and then get zero yields because nobody else had a pantheon yet  -  nothing abnormal happened when I picked it first, and all worked as intended

**Comment by Regularitee** [comment]
May I ask what game speed and map size you were running on? I'm wondering if yield scaling multipliers from map size and game speed might have an impact.

**Comment by deadstarre** [comment]
standard / standard

**Comment by MoiMagnus** [comment]
@Regularitee You said you tested and reproduced it, so I have few questions : 
1) In the mod list you posted, there is no mod "(6a) Compatibility files" or (6b) or (6c) (depending of version of the mod you are using). It is probably just a copy-past problem, but if you don't have any of those mods, it is clearly the problem.

2) In you tests, did you try without any other mods than VP and IGE, or did you use the remaining of your mods too ? (It would not be the first time that a mod that has no reasons to be incompatible turn out to be incompatible...)

**Comment by Regularitee** [comment]
In the first test I did forget (6a). However, in subsequent tests I did verify I had it, and the bug still appeared.

What's VP? In subsequent tests I did remove the building upgrades mod, since it was the only mod I had that caused gameplay changes (and thus was the most likely candidate for mod conflicts). But I still managed to get the bug.

**Comment by MoiMagnus** [comment]
Ah, yes, sorry. VP = Vox Populi is somtimes also named "Community Balance Patch", "Community Patch Project", ... It is just the name of : 
Community Patch + Community Balance Overaul + City-State Diplomacy + Civ 4 Diplomaty Featues + More Luxuries
