### ISSUE TITLE
Sipahi / Melee Mounted units unbuildable 

### ISSUE THREAD

**Issue by TooManyCords** [LoneGazebo/Community-Patch-DLL#3665]
_1. Mod version (i.e Date - 11/06):_

_2. Mod list (if using Vox Populi only, leave blank):_

Also using a number of JFD's civilizations, but haven't encountered any bugs with them thus far. 

_3. Error description:_ 
I'm playing as the Ottomans with Suleiman - the Sipahi unit simply doesn't show up in the build queue once I've researched metallurgy (they are a Lancer replacement). In fact, no mounted melee character shows up as buildable (Knight, Lancer, etc). I could successfully upgrade my Knights to Sipahi, so the unit seems to be in the game, but obviously I'd like to build more for world conquest, etc.

EDIT: Yes, I've tried, saving, exiting, restarting etc.

_4. Steps to reproduce (optional):_

Promise not to laugh at my lack of skill?
[Suleiman_0342 AD-1610.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1465636/Suleiman_0342.AD-1610.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Enable logging and post your database log after loading the game.

**Comment by TooManyCords** [comment]
Enjoy.

[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1469491/Lua.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1469492/xml.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1469493/Database.log)

**Comment by LoneGazebo** [comment]
Looks like a conflict with a JFD civ. 

G

**Comment by TooManyCords** [comment]
Any idea which one? I looked through the files, but it wasn't clear to me. JFD might want to know about the conflict.

**Comment by LoneGazebo** [comment]
duplicate column name: JFD_ReligionTheme
[770228.781] Invalid Reference on Buildings.TrainedFreePromotion - "PROMOTION_NAVAL_COLLEGE" does not exist in UnitPromotions
[770229.031] Invalid Reference on Buildings.Help - "TXT_KEY_BUILDING_JFD_STOREHOUSE_HELP_CBO" does not exist in Language_en_US
[770230.484] Invalid Reference on Policies.Description - "TXT_KEY_DECISIONS_JFD_PRUSSIA_EMPOWER_JUNKER_CLASS" does not exist in Language_en_US
[770232.984] Invalid Reference on UnitPromotions.PediaEntry - "TXT_KEY_PROMOTION_JFD_HUSCARL_INFO" does not exist in Language_en_US

**Comment by TooManyCords** [comment]
I'm still not clear how that conflicts with the Turkish Sipahi (a non-JFD civ), but thanks.

**Comment by LoneGazebo** [comment]
If he edits a unit, it may break the CBO, and vice-versa.

G
