### ISSUE TITLE
Jewelry does not provide a monopoly bonus.

### ISSUE THREAD

**Issue by Regularitee** [LoneGazebo/Community-Patch-DLL#3667]
I was playing the game with the Community Events submod. One of the events grants the player a choice of having a copy of a otherwise restricted resource (glass, jewelry, porcelain, etc). I chose jewelry, and my trade network gained a copy of the resource. There are no other city states on the map trading this resource, so this would have been a monopoly.

The civilopedia entry claimed this was supposed to grant me a happiness bonus from having a monopoly. It did not. Furthermore, I checked the "corporations and monopolies" list to find that jewelry wasn't even listed there.

So one of the two issues needs to be fixed:
If jewelry **is not** intended to grant a monopoly bonus, the reference to monopoly bonuses in its civilopedia entry should be removed.
If jewelry **is** intended to grant a monopoly bonus, well, it should be added to the monopolies list and grant the bonus it's supposed to.

**Comment by LoneGazebo** [comment]
Jewelry can give it, but monopoly rules state that the resource must be physically on the map for them.

**Comment by Regularitee** [comment]
Doesn't that mean a monopoly _is_ impossible then, since you can't find jewelry on the map as a deposit?

**Comment by LoneGazebo** [comment]
No, jewelry appears under a CSs capital city. Same with porcelain.
