### ISSUE TITLE
Request: alert mode for air units

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#367]
So they would woke up the moment there is a visible enemy unit in the bombing range.
Right now having several cities with 10+ air units in each is a pain to manage. Especially when bombing radius gets 10+ tiles far.

**Comment by LoneGazebo** [comment]
The problem is that those checks( 'range checks') are expensive, and calling them every turn, for every air unit, would be a drastic performance hog.

G

**Comment by Radost** [comment]
Then reduce their bombing range? Negating UPT in the UPT-based combat is a thing in itself.

**Comment by LoneGazebo** [comment]
It's not that easy, man. Cut me some slack and let me research it a bit.
G
