### ISSUE TITLE
No pantheon in the city after taking it back from another civ

### ISSUE THREAD

**Issue by l29ah** [LoneGazebo/Community-Patch-DLL#3673]
_1. Mod version (i.e Date - 4/23):_
11/6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I have a pantheon picked, but my city lost it after being taken by an enemy civ.
Saved game (join as Rome): http://dump.bitcheese.net/files/baxugum/nj-voker-l29ah-filip-bug.Civ5Save

**Comment by Voker57** [comment]
I think that is intended behaviour.

**Comment by l29ah** [comment]
Is it documented anywhere?

**Comment by l29ah** [comment]
Huh, why is this closed?
According to civilopedia, pantheon expands to all my cities until i found a religion.

**Comment by LoneGazebo** [comment]
Cities you found - it doesn't affect cities you capture/retake.

**Comment by l29ah** [comment]
I founded it, and it's surprising capturing a city instantly and permanently makes its population atheists (until major religion comes, if any).

**Comment by LoneGazebo** [comment]
If the other player has founded a religion that can happen.

**Comment by l29ah** [comment]
On Mon, Dec 04, 2017 at 02:42:43AM +0000, LoneGazebo wrote:
> If the other player has founded a religion that can happen.

None of the two players have founded a religion.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
