### ISSUE TITLE
AI not building defensive units

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3674]
![image](https://user-images.githubusercontent.com/1358966/32988187-1facb1d6-ccff-11e7-9726-16a9714bd370.png)

ravenna is a bit isolated and has been under siege for quite a while. there are not reinforcements on the way, but instead of building/buying a garrison unit, the AI simply continues with the research lab.

i think for performance reasons the build choice is not re-evaluated every turn, but maybe for cities in non-friendly tactical zones we can make an exception.

don't know what the logic is for buying (or which log file to look at). in any case they eventually bought another nuclear sub, which of course is a rather unfortunate choice in this situation.

**Comment by LoneGazebo** [comment]
It is also possible that Rome was at its supply cap. That can happen. 

G

**Comment by ilteroi** [comment]
maybe it's the supply cap. but nevertheless an exception for cities needing a garrison could be justified. also the nuclear submarine was a really bad choice.
