### ISSUE TITLE
various late game observations

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3675]
![image](https://user-images.githubusercontent.com/1358966/32989594-a7d5c15a-cd19-11e7-825f-8e37205f52bb.png)

rome is obviously very dominant in this game, however world ideology is autocracy, not order. question: why does only rome get a pubic opinion penalty?

everybody but rome has huge unhappiness problems. the main reasons for that are war weariness and poverty.

![image](https://user-images.githubusercontent.com/1358966/32989970-bc875ff8-cd20-11e7-81c1-cafbac398705.png)

why don't they make peace? this is absolutely crippling on both sides!

Rome, 367,  --- War Weariness: 68. Longest War: 22. Rising: 75. Falling: 0. Current Supply Cap: 34
Austria, 367,  --- War Weariness: 32. Longest War: 26. Rising: 35. Falling: 27. Current Supply Cap: 26
The Iroquois, 367,  --- War Weariness: 91. Longest War: 23. Rising: 100. Falling: 83. Current Supply Cap: 4
Greece, 367,  --- War Weariness: 6. Longest War: 9. Rising: 0. Falling: 4. Current Supply Cap: 32
Carthage, 367,  --- War Weariness: 46. Longest War: 27. Rising: 100. Falling: 0. Current Supply Cap: 14
Polynesia, 367,  --- War Weariness: 10. Longest War: 16. Rising: 13. Falling: 5. Current Supply Cap: 16

regarding poverty, AI doesn't seem to value building stock exchanges very high:

318, Carthage, Carthage, PRE: Building, Wire Service, 8955, 3
318, Carthage, Carthage, PRE: Unit, Cargo Ship, 7940, 1
318, Carthage, Carthage, PRE: Building, Stock Exchange, 6340, 3
318, Carthage, Carthage, PRE: Building, Airport, 5580, 5
318, Carthage, Carthage, PRE: Unit, Caravan, 4720, 1
318, Carthage, Carthage, PRE: Building, Factory, 4276, 2
318, Carthage, Carthage, PRE: Building, Stadium, 2424, 2
318, Carthage, Carthage, PRE: Building, Police Station, 2375, 4
318, Carthage, Carthage, PRE: Unit, Ambassador, 2320, 1
318, Carthage, Carthage, PRE: Building, Ironworks, 2050, 1
318, Carthage, Carthage, PRE: Building, Medical Lab, 1760, 4
318, Carthage, Carthage, PRE: Process, Wealth, 1560, 1
318, Carthage, Carthage, PRE: Process, Research, 754, 1
318, Carthage, Carthage, PRE: Process, Arts, 495, 1
318, Carthage, Carthage, PRE: Process, Farming, 220, 1
318, Carthage, Carthage, PRE: Unit, Archaeologist, 150, 1
318, Carthage, Carthage, PRE: Process, Defense, 100, 1
318, Carthage, Carthage, PRE: Unit, Carrier, 75, 4
318, Carthage, Carthage, POST: Building, Stadium, 40884, 2
318, Carthage, Carthage, POST: Unit, Caravan, 26420, 1
318, Carthage, Carthage, POST: Unit, Cargo Ship, 25920, 1
318, Carthage, Carthage, POST: Building, Wire Service, 24551, 3
318, Carthage, Carthage, POST: Unit, Ambassador, 23000, 1
318, Carthage, Carthage, POST: Building, Stock Exchange, 21536, 3
318, Carthage, Carthage, POST: Building, Police Station, 20467, 4
318, Carthage, Carthage, POST: Building, Factory, 13325, 2
318, Carthage, Carthage, POST: Building, Medical Lab, 11440, 4
318, Carthage, Carthage, POST: Building, Airport, 10317, 5
318, Carthage, Carthage, POST: Unit, Archaeologist, 1050, 1
318, Carthage, Carthage, POST: Process, Farming, 389, 1
318, Carthage, Carthage, POST: Process, Wealth, 164, 1
318, Carthage, Carthage, POST: Process, Research, 80, 1
318, Carthage, Carthage, SEED: 8985709647830647685, CHOSEN: Caravan, Do not rush, TURNS: 1

also, and this might be a quirk of observer mode, but when i step into an AI, they often work zero specialists and "manual specialist control" is checkmarked.

nor do they build many villages (respectively replace other improvements by villages). of course they also have few trade routes because of all the wars.

finally, i often see supply limits lower than the number of cities! maybe put in a guaranteed minimum there?

**Comment by ilteroi** [comment]
update on poverty. carthage needs an astonishing 9.7 gold per pop:

![image](https://user-images.githubusercontent.com/1358966/32990109-e142d5b8-cd23-11e7-9e82-b692eb9c5e1f.png)

carthage has one town, zero villages:

![image](https://user-images.githubusercontent.com/1358966/32990165-d45fbebe-cd24-11e7-9a85-7c35096276a3.png)

anyway, comparing:

![image](https://user-images.githubusercontent.com/1358966/32990183-1eab5cbc-cd25-11e7-8872-bf7d311aa7ba.png)

this factor of 2 is due to tech level of course, but i wonder if that shouldn't be relative tech level instead of absolute tech level (which is already reflected in the global average after all)

**Comment by bigcat88** [comment]
Other don't get public opinion, cause Rome has more influence with his Order then Global Resolution. Resolution always has a power of 2 and top civ in world usually power of 2/3 and sometimes 4.

But there are strange thing in ideologies(or maybe it is EUI mistake when I look at this). Situations that was in September. See several times(civA,civB,civC - all has three different ideologies) when civA has 2 points of ideology pressure on civB. civB are content, cause ideology pressure is "falling". Then civC which has only 1 point of ideology pressure on civB get "Rising" status on civB and civB gets penalty from civA and revolution goes to civA ideology.
And if civC will not rush tourism events, then civB will sit with own ideology without revolution, cause civA cannot get Rising status. In that game I was civC, after revolution in civB I loaded 20 turns earlier save and stop purchasing Great People - didn't get Rising status on civB and game goes another way...

**Comment by ilteroi** [comment]
yeah this rising/falling status doesn't take into account instant yields afaik, so it's not very reliable.

**Comment by LoneGazebo** [comment]
There is a method to check if civ’s are working specialists. It is in the city citizen specialist log. Also keep in mind that the AI gets happiness handicap modifiers so when you step into the AI you are seeing the ‘full’ human penalty, not the AI’s handicap. So things may look worse than they actually are
(which is why the AI may not have made drastic changes to things to fix problems that are or are not there). 

The custommods log has data on happiness for each player. 

G

**Comment by ilteroi** [comment]
unfortunately this issue mixes a lot of topics, i already regret it :)

anyway, what's your stance on the following points:

1. value stock exchanges higher, or more generally any happiness-generating building.
2. use relative tech level for yield threshold adjustment
3. war weariness should increase AI willingness to make peace (more than now)
4. more comprehensible assignment of public opinion unhappiness

**Comment by LoneGazebo** [comment]
1. The valuation model does this, but I can amp it up a bit more.
2. It would result in a big change to the happiness algorithm - I'd rather teach the AI to figure it out better than change the model (as humans can do it pretty well as-is).
3. It does, but yeah, we could increase it further.
4. What's incomprehensible about it?

**Comment by ilteroi** [comment]
2. imho the current model is wrong and the reason nobody noticed is because it only becomes apparent in the late game. i'll try to find a better one, shouldn't be too hard.

4. how can the civ with the highest influence receive a public opinion penalty? shouldn't it be the other way around? i didn't really understand bigcats explanation either ...

**Comment by LoneGazebo** [comment]
2. I'm fine with experimenting with it, sure.
3. Did those other civs recently switch or adopt? There's a cooldown period of no dissidents.

**Comment by bigcat88** [comment]
@ilteroi  I think Austria was able to pass World Ideology, that's why Rome get Dissidents.

**Comment by ilteroi** [comment]
btw, does the AI take into account which kind of unhappiness they are suffering? i'm seeing them build a stadium when poverty is the problem.

**Comment by LoneGazebo** [comment]
Yes, they do check. You can see the values in the BuildingProductionAI check. 

I’ll look at the scaler.
