### ISSUE TITLE
Just War belief showing as TXT_KEY in combat screen

### ISSUE THREAD

**Issue by Stef012** [LoneGazebo/Community-Patch-DLL#3677]
_1. Mod version (i.e Date - 4/23):_

11/6

_2. Mod list (if using Vox Populi only, leave blank):_

CP v88 6-Nov
CD v15
RtP v46
EE v6
E&D v3
EC v5
HR v45
More Luxuries
Ireland (JFD civ)

_3. Error description:_ 

With above mod list (using latest JFDLC/RtP) the Just War belief results in a TXT_KEY_EUPANEL_ENEMY_CITY_BELIEF_BONUS_CBP in the combat screen. 

_4. Steps to reproduce (optional):_

- Have Just War belief
- Be in war with AI
- Attack within AI territory

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[CP Just War TXT KEY.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1485634/CP.Just.War.TXT.KEY.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[High King Brian Boru_0136 AD-0520.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1485638/High.King.Brian.Boru_0136.AD-0520.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20503631/32991757-035812f8-cd42-11e7-84b7-396c91be19f8.png)

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict the.

**Comment by JFDaly** [comment]
Yeap, found and fixed the issue on my end.
