### ISSUE TITLE
Event bugged

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#3678]
_1. Mod version (i.e Date - 4/23):_
11/6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The event (sorry for not remembering the name) where a city of a different religion revolts after conquest is bugged. The first option "They never expect the inquisition" should reduce the city by 4 pop. However, since a few releases, if you select it, nothing happens, the city does not lose population. I have not checked the other options.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
This is an @enginseer event.

**Comment by TechpriestEnginseer** [comment]
Yah, i'll fix within next update.

**Comment by TechpriestEnginseer** [comment]
Already fixed. No point in having it open here.

**Comment by TechpriestEnginseer** [comment]
Just realized it's not one of my event, but rather it's my responsibility on one of the event.
