### ISSUE TITLE
Governour using citizens

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#3679]
_1. Mod version (i.e Date - 4/23):_

11/6
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I observed this for a while: Occasionally the gouvernor will assign citicens (the basic specialist, which just gives +1 production) even if better specialist slots or just tiles are available. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Any context clues? Perhaps the city was sieged?

**Comment by l29ah** [comment]
The governor does this even in medieval age when specialists consume as much food as peasants, so this is still a bug (it prefers to produce one hammer instead of three hammers being an engineer for me atm). The food is plentiful and this is my capital at peaceful time.
