### ISSUE TITLE
How PROCESS_DEFENSE is activated?

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3682]
How is the Defense Process activated in the CBO? There doesn't seem to be a column for its function in the Processes table, so is it a game define or is the Process hardcoded using that said? Thank for any info.

**Comment by LoneGazebo** [comment]
It is currently hardcoded (i.e. there's just a set value that it looks for in the DLL), but I can make it extendable if desired.

**Comment by JFDaly** [comment]
That would be great if you could, yeah. Thank.

**Comment by LoneGazebo** [comment]
Cool, yep, will do.

**Comment by LoneGazebo** [comment]
It'll be 'DefenseValue' column of the process table which is a % value of the city's production ouput. For CBO it'll be 100 (i.e. 100% of the city's production). Make sense?

**Comment by JFDaly** [comment]
Yeap, thanks.
