### ISSUE TITLE
CTD on AI turn

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3683]
_1. Mod version (i.e Date - 4/23):_
last

_2. Mod list (if using Vox Populi only, leave blank):_
World Congress Reformation (v 5)
Terrain - Poor Tiles Tweak (v 2) - don't need to load save
Wonder Race (v 7) - don't need to load save

_3. Error description:_ 
My fun game, but the game was interesting(
CTD in Information Era on Rome AI turn(tried 3 times).

_4. Steps to reproduce (optional):_
Press: End Turn

[CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1486042/CTD.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1486047/Logs.zip)

Strange, but minidump for this crash is zero size.

**Comment by LoneGazebo** [comment]
If the minidump has no size that means it isn't a DLL crash (OR it is an infinite loop...). Did it hard crash or hang?

**Comment by bigcat88** [comment]
Long waiting - then just "application stop working" as I remember when in window mode, and in fullscreen mode it just closed. Crash is fully repeatable.
