### ISSUE TITLE
Inconsistent behavior when swapping units over a rival civilian (worker)

### ISSUE THREAD

**Issue by abmpicoli** [LoneGazebo/Community-Patch-DLL#3684]
_1. Mod version (i.e Date - 4/23):_ vox Populi 1.11

_2. Mod list (if using Vox Populi only, leave blank):_UI BC1

_3. Error description:_ Inconsistent behavior: Swapping locations into a location that has a worker under it triggers war dialog, making movement impossible without declaring war. Swapping "out" of a location that has a worker under it, doesn't.

_4. Steps to reproduce (optional):_ Place one military unit adjacent to each other, and place one another player  worker under one of them. Try to swap locations between the two military units by moving the free unit over the tile that has the worker under it. 
Expected behavior: units would be swapped; enemy worker would not be captured;
Actual behavior: The dialog "does this means war" appears: If you click "no", no movement happens.
![20171120124607_1](https://user-images.githubusercontent.com/1733170/33024735-0b468de4-cdf3-11e7-8ea1-570085b5b8db.jpg)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
first of all, exemplary bug report.

but.

i can only reproduce it with a minor civ worker in minor civ territory though. quite strange. additionally, since it's possible to do the swap the other way around the impact is rather low. therefore i'd rather not risk breaking anything else with the fix.
