### ISSUE TITLE
Civilopedia articles that need updating

### ISSUE THREAD

**Issue by Regularitee** [LoneGazebo/Community-Patch-DLL#3685]
A few things I've found that are incorrect or missing info:

- The tourism articles fail to mention that tourism from trade routes boost city growth
- The coal refinery article fails to mention it's mutually exclusive with solar/nuclear plants. Likewise, the solar and nuclear plant articles don't mention they can't be built with a coal refinery in the city.
- The corporations guide doesn't clarify that the "Headquarters" wonder also receives all the same bonuses as "Offices" buildings, which can be misleading. All references to city bonuses only mention offices, not headquarters.

Other things that could use improvement:
- Fallout production mechanics. Sometimes a single bomb will produce multiple tiles of fallout. Other times multiple nuclear missiles won't create a single fallout tile. Adding some information on how fallout production works would be really useful, especially if there's differences between atomic bombs and nuclear missiles.

**Comment by LoneGazebo** [comment]
Corp says:
> These buildings come with special bonuses similar to your Corporation's Headquarters

re: fallout, it is hardcoded randomness.
