### ISSUE TITLE
Inconsistent espionage potential?

### ISSUE THREAD

**Issue by Regularitee** [LoneGazebo/Community-Patch-DLL#3686]
I generally play on large maps on marathon game speed, if it matters. And these have been during one-city challenges with a city of 60-90 population.

I've found that between the beginning of the espionage becoming available and the end of the game, my capital's espionage potential fluctuates inexplicably between minimum (0.5 stars) and maximum (5 stars) at least 2-4 times throughout the entire game. Never anything in between those two values.

Now the strange part is there is no real explanation for this behavior. During this time no new espionage-defense buildings are built, no events triggered, no wars to damage infrastructure or city prosperity, and self-sufficient luxury gathering (meaning no sharp changes in unhappiness from losing trade routes).

Are there any undocumented factors besides city prosperity, happiness, and buildings/wonders at play here, or could this be a bug?

**Comment by LoneGazebo** [comment]
Probably means he moved a counter spy into the city - counter spies affect potential (Since the AI knows about stuff like this, I included this content in the potential bar for humans too).

**Comment by Regularitee** [comment]
It was my own city, during a one-city challenge. And no, I don't think counter-spies played into it.

I could go 100+ turns without having any counter-spy in the city and without my espionage potential rising above 0.5 stars. Unless counter-spies leave a lingering affect for a prolonged period after being withdrawn.

**Comment by LoneGazebo** [comment]
Well, potential is based on global values, so it sounds like your city was simply moving up and down the rankings.

**Comment by Regularitee** [comment]
Oh, it's all graded relatively? 

So in other words, my city's espionage potential could go from 0.5 to 5 stars despite nothing changing, but because other civs are undergoing unhappiness or war or some nonsense?

**Comment by bigcat88** [comment]
There is some internal events for espionage - they popup in right of screen sometimes. Like: "city XXX is especially vulnerable for foreign spies". U are saying about them?

**Comment by LoneGazebo** [comment]
Correct.
