### ISSUE TITLE
Hexxon Refinery resource balancing

### ISSUE THREAD

**Issue by Regularitee** [LoneGazebo/Community-Patch-DLL#3687]
Any chance that Hexxon Refinery's corporation bonus could include at least a little iron or aluminium? 

Right now it grants only coal and oil, which means  it only lets you build additional melee units (destroyers, cruisers, tanks), but none of the resources for ranged units (iron for battleships and artillery, aluminum for submarines and gunships). The end result is military that's pretty lopsided and unbalanced.

If Hexxon granted iron or aluminium in quantities equal to half -- or even a quarter -- of what it currently grants for coal/oil, it would go a long way to letting players have a more reasonable balance of unit types.

**Comment by LoneGazebo** [comment]
This is not really a question for github...this is for bug reports.

**Comment by Regularitee** [comment]
Sorry, didn't realize. When I worked on other games' githubs, they usually included balancing discussion and proposed rebalancing changes through issue tickets. Where should they go instead if you don't want them here?

**Comment by LoneGazebo** [comment]
No worries. The civfanatics subforum.
