### ISSUE TITLE
Cavalry UU

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#369]
Many Cavalry UU still obsolete at Combustion instead of Combined Arms

**Comment by LoneGazebo** [comment]
List them?

**Comment by phantommaxwell** [comment]
Cavalry and Comanche obsolete properly (@Combined Arms)

Cossacks, Hussars, and Berbers don't (@Combustion)

**Comment by LoneGazebo** [comment]
danke!
