### ISSUE TITLE
Request for Unit:GetTurnCreated()

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3690]
Do you think a function like **unit:GetTurnCreated()** would be possible to add - maybe there already is one in the DLL that can be pushed to lua? That is, one that returns the game turn that the unit was created on.

**Comment by LoneGazebo** [comment]
That exists already: GetGameTurnCreated()

G

**Comment by JFDaly** [comment]
Oh, awesome.
