### ISSUE TITLE
AI not building settlers

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3691]
![image](https://user-images.githubusercontent.com/1358966/33114290-73e95e02-cf5c-11e7-82bc-8c4dab27f993.png)

assyria hasn't built a settler in a hundred turns, so now they are boxed in by enemy cities.

typical log: the settler is always present in PRE (though with a rather low score) but filtered out in POST.

176, Assyria, Kar-Tukulti-Ninurta, PRE: Building, University, 14550, 4
176, Assyria, Kar-Tukulti-Ninurta, PRE: Building, Chancery, 7745, 4
176, Assyria, Kar-Tukulti-Ninurta, PRE: Building, Caravansary, 7350, 3
176, Assyria, Kar-Tukulti-Ninurta, PRE: Building, Well, 4900, 1
176, Assyria, Kar-Tukulti-Ninurta, PRE: Building, Circus Maximus, 4450, 1
176, Assyria, Kar-Tukulti-Ninurta, PRE: Unit, Emissary, 3270, 1
176, Assyria, Kar-Tukulti-Ninurta, PRE: Building, Grocer, 3225, 7
176, Assyria, Kar-Tukulti-Ninurta, PRE: Building, Herbalist, 3140, 1
176, Assyria, Kar-Tukulti-Ninurta, PRE: Building, Temple, 1800, 3
176, Assyria, Kar-Tukulti-Ninurta, PRE: Building, Castle, 1625, 1
176, Assyria, Kar-Tukulti-Ninurta, PRE: Unit, Cuirassier, 1582, 4
176, Assyria, Kar-Tukulti-Ninurta, PRE: Unit, Worker, 1560, 1
176, Assyria, Kar-Tukulti-Ninurta, PRE: Process, Wealth, 1225, 1
176, Assyria, Kar-Tukulti-Ninurta, PRE: Unit, Settler, 1200, 2    <---------------------
176, Assyria, Kar-Tukulti-Ninurta, PRE: Process, Research, 1040, 1
176, Assyria, Kar-Tukulti-Ninurta, PRE: Unit, Cannon, 858, 4
176, Assyria, Kar-Tukulti-Ninurta, PRE: Process, Arts, 750, 1
176, Assyria, Kar-Tukulti-Ninurta, PRE: Building, Armory, 700, 2
176, Assyria, Kar-Tukulti-Ninurta, PRE: Unit, Lancer, 560, 4
176, Assyria, Kar-Tukulti-Ninurta, PRE: Process, Farming, 460, 1
176, Assyria, Kar-Tukulti-Ninurta, PRE: Building, Garden, 300, 4
176, Assyria, Kar-Tukulti-Ninurta, PRE: Unit, Explorer, 290, 2
176, Assyria, Kar-Tukulti-Ninurta, PRE: Process, Defense, 100, 1
176, Assyria, Kar-Tukulti-Ninurta, POST: Building, Castle, 31932, 1
176, Assyria, Kar-Tukulti-Ninurta, POST: Building, Circus Maximus, 28333, 1
176, Assyria, Kar-Tukulti-Ninurta, POST: Building, University, 10917, 4
176, Assyria, Kar-Tukulti-Ninurta, POST: Building, Well, 9948, 1
176, Assyria, Kar-Tukulti-Ninurta, POST: Building, Temple, 9320, 3
176, Assyria, Kar-Tukulti-Ninurta, POST: Building, Herbalist, 8946, 1
176, Assyria, Kar-Tukulti-Ninurta, POST: Building, Chancery, 8527, 4
176, Assyria, Kar-Tukulti-Ninurta, POST: Building, Armory, 8119, 2
176, Assyria, Kar-Tukulti-Ninurta, POST: Building, Caravansary, 7911, 3
176, Assyria, Kar-Tukulti-Ninurta, POST: Building, Garden, 5157, 4
176, Assyria, Kar-Tukulti-Ninurta, POST: Building, Grocer, 4484, 7
176, Assyria, Kar-Tukulti-Ninurta, POST: Unit, Emissary, 4000, 1
176, Assyria, Kar-Tukulti-Ninurta, POST: Unit, Worker, 4000, 1
176, Assyria, Kar-Tukulti-Ninurta, POST: Unit, Cuirassier, 2160, 4
176, Assyria, Kar-Tukulti-Ninurta, POST: Unit, Cannon, 1449, 4
176, Assyria, Kar-Tukulti-Ninurta, POST: Unit, Lancer, 1297, 4
176, Assyria, Kar-Tukulti-Ninurta, POST: Process, Arts, 1056, 1
176, Assyria, Kar-Tukulti-Ninurta, POST: Process, Farming, 512, 1
176, Assyria, Kar-Tukulti-Ninurta, POST: Process, Research, 444, 1
176, Assyria, Kar-Tukulti-Ninurta, POST: Process, Wealth, 432, 1
176, Assyria, Kar-Tukulti-Ninurta, POST: Unit, Explorer, 342, 2
176, Assyria, Kar-Tukulti-Ninurta, POST: Process, Defense, 118, 1
176, Assyria, Kar-Tukulti-Ninurta, SEED: 607494571100303443, CHOSEN: Castle, Do not rush, TURNS: 1

**Comment by ilteroi** [comment]
btw happiness is not their problem, this is the historical data on that (with the new threshold scaling):

![image](https://user-images.githubusercontent.com/1358966/33114448-2df97c3c-cf5d-11e7-8eea-b4327159f7e9.png)

**Comment by LoneGazebo** [comment]
Did it have anywhere to build? That’s one of the few checks that removes settlers from the build list. 

G

**Comment by ilteroi** [comment]
the whole area to the north of assyria used to be empty. but they ignored it and let others settle there.

**Comment by LoneGazebo** [comment]
These are the only filters for settlers:

`````
#if defined(MOD_BUGFIX_MINOR_CIV_STRATEGIES)
		EconomicAIStrategyTypes eCanSettle = (EconomicAIStrategyTypes)GC.getInfoTypeForString("ECONOMICAISTRATEGY_FOUND_CITY");
		if (EconomicAIHelpers::CannotMinorCiv(m_pCity->GetPlayer(), eCanSettle))
#else
		if(kPlayer.isMinorCiv())
#endif
		{
			return 0;
		}

		EconomicAIStrategyTypes eNoMoreExpand = (EconomicAIStrategyTypes)GC.getInfoTypeForString("ECONOMICAISTRATEGY_ENOUGH_EXPANSION");
		if (GET_PLAYER(m_pCity->getOwner()).GetEconomicAI()->IsUsingStrategy(eNoMoreExpand))
		{
			return 0;
		}

		int iFirstUnitID = 0;
		//There's a settler waiting here? Abort!
		if(m_pCity->plot()->getNumUnitsOfAIType(UNITAI_SETTLE, iFirstUnitID) > 0)
		{
			return 0;
		}
		//Don't build a settler if we're about to grow.
		if(m_pCity->getFoodTurnsLeft() <= 1)
		{
			return 0;
		}
		//Or if we're small.
		if(m_pCity->getPopulation() <= 4)
		{
			return 0;
		}
		if(kPlayer.isBarbarian() || kPlayer.GetPlayerTraits()->IsNoAnnexing() || (GC.getGame().isOption(GAMEOPTION_ONE_CITY_CHALLENGE) && kPlayer.isHuman()))
		{
			return 0;
		}
		if(kPlayer.IsEmpireSuperUnhappy())
		{
			return 0;
		}
		//Already have a settler out? Ignore.
		int iNumSettlers = kPlayer.GetNumUnitsWithUnitAI(UNITAI_SETTLE, true, true);
		if(iNumSettlers > 1)
		{
			return 0;
		}
```

**Comment by ilteroi** [comment]
mysterious. most of these checks are already present in ECONOMICAISTRATEGY_ENOUGH_EXPANSION btw, plus a few more, e.g.

	MilitaryAIStrategyTypes eBuildCriticalDefenses = (MilitaryAIStrategyTypes) GC.getInfoTypeForString("MILITARYAISTRATEGY_LOSING_WARS");
	// scale based on flavor and world size
	if(eBuildCriticalDefenses != NO_MILITARYAISTRATEGY && pPlayer->GetMilitaryAI()->IsUsingStrategy(eBuildCriticalDefenses) && !pPlayer->IsCramped())
	{
		return true;
	}

	if(pPlayer->GetDiplomacyAI()->IsGoingForCultureVictory() && (pPlayer->GetNumCitiesFounded() > (pPlayer->GetDiplomacyAI()->GetBoldness())))
	{
		return true;
	}

no wars either, that game was a total lovefest, so i guess they were going for culture victory? don't think they stand a chance there, but maybe that explains it.

**Comment by LoneGazebo** [comment]
I don't think they have a boldness of zero, so that can't be it. And they were definitely cramped.

**Comment by ilteroi** [comment]
not quite, the founded 4 cities after all. but their boldness is 6, so it still doesn't check out. the mystery continues.

**Comment by LoneGazebo** [comment]
You could toss some debug notes in the function, see where it pops up. Or just toss breakpoints on the return 0 elements with his playerID as the filter.

**Comment by ilteroi** [comment]
yeah yeah yeah.

so CheckUnitBuildSanity() returns -90k. problem is that iFlavorExpansion ends up at -18. initially it's 6 but that almost doesn't matter because the modifiers are crazy high, spaceship victory gives -10, and finally:

		//not special and we're in the middle ages? deemphasize.
		else if (MOD_BALANCE_CORE_DIPLOMACY_ADVANCED && (int)kPlayer.GetCurrentEra() >= GC.getInfoTypeForString("ERA_MEDIEVAL", true /*bHideAssert*/))
		{
			iFlavorExpansion -= 20;
		}

i cleaned it up a bit, and moved the non-negativitity check to the end, that should help a bit

**Comment by LoneGazebo** [comment]
cool. sounds like it was a weird quirk, as I rarely see an AI not expand. Good eye, though.
