### ISSUE TITLE
Are Great Works hardcoded for the AI?

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3695]
Do you know if Great Works are hardcoded such that the AI would fail to use them if a new one (i.e. Film) was added? A cursory but ill informed look in CvCultureClasses suggests that swapping is hardcoded, but do you know if other things such as theming, using a Great Person to produce said new Great Work, etc. would be hardcoded? Thanks for any insight.

**Comment by LoneGazebo** [comment]
Tricky. Firaxis mixed both scaling and hard-coded stuff. For example, there's GreatWorkType, which is a class (so you can make more of them). However logic for moving/theming these great works is restricted to the three big types - lit/music/art&artifact. It's a real dumb system, but it is definitely hardcoded on that front. If you wanted to add a new GW type, you'd need to either do some C++ additions or accept that they can't move or be themed.

G

**Comment by JFDaly** [comment]
Good to know. Being unable to move or theme them is no problem. Most important thing is that the AI will actually expend the Great Person for them. Thanks for the info.

**Comment by LoneGazebo** [comment]
@JFDaly they should, yes - if they don't, let me know and I'll at least make sure that works.

G
