### ISSUE TITLE
Heritage policy design weirdness

### ISSUE THREAD

**Issue by Zarrk** [LoneGazebo/Community-Patch-DLL#3696]
_1. Mod version (i.e Date - 4/23):_
11-6 Non EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Heritage gives a flat reduction of 3% to the per city tourism malus, the problem is this malus is also affected by map size. At normal size it's 4, 7 for duel and only 2 at huge. This create a quite serious difference in usefullness depending of the game speed, I suppose it's an oversight and that nullifying the malus was not intended.

**Comment by LoneGazebo** [comment]
It is always capped at a minimum of 1%, so yes, it is intended.

G
