### ISSUE TITLE
Progress opener missing culture boost for completed tech

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#3697]
_1. Mod version (i.e Date - 4/23):_

11/6 current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

on the first turn you adopt progress opener, you get an instant boost of science for the existing pop in your capital - which pushes you to complete a tech immediately - but the completed tech does not grant a culture boost that having adopted progress should now give. 

It is only a problem on the first turn you adopt progress/instantly a complete tech-  i am guessing the bonuses are just not triggering in the correct order?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
They can't - I tried working this but, because of how the DLL stack works, it generates an overflow and crashes. I can't work around it because of the way that the DLL is designed.

G

**Comment by deadstarre** [comment]
who knew! thanks

**Comment by LoneGazebo** [comment]
yep.
