### ISSUE TITLE
Indonesia extremely reluctant to sell their racial luxury resources

### ISSUE THREAD

**Issue by philip-bl** [LoneGazebo/Community-Patch-DLL#3698]
_1. Mod version (i.e Date - 4/23):_
2017-11-06

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In multiple games (I think in all of them) whenever I tried to buy indonesian luxury resources (nutmeg, cloves) from them, they assigned very large negative value to selling them, even if they have more than 1 copy. Larger than countries usually assign to resources they have 1 of (e.g. 1250 vs 700), much larger than countries usually assign to resources they have 2+ of (1250 vs 320). I think it's irrational for Indonesia to not sell these resources.

---------------------------
2. An example of save game:
http://dump.bitcheese.net/files/lepecod/indonesia_not_selling_luxuries_1.Civ5Save

**Comment by LoneGazebo** [comment]
There's nothing unique to those resources in the DLL - are you sure they aren't just upset with you in general?

**Comment by Voker57** [comment]
They have the same prices for me IIRC and I'm their best friend.

**Comment by LoneGazebo** [comment]
As I noted, there's nothing unique to them for that. If they have higher prices it is because they want more money.

G

**Comment by philip-bl** [comment]
Is it posible then that Indonesia always wants a lot of money for any luxury resources? Anyway, I'll keep track of Indonesia and their prices in my games and will report here if I find some more evidence of their irrational price.

**Comment by LoneGazebo** [comment]
Sounds good.
