### ISSUE TITLE
happiness modifiers

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3699]
my happiness experiments continue ... and i noticed that you can apparently reach a modifier of -100 on the poverty threshold. does that make sense? the medical lab alone is -50. why should that reduce poverty at all?

the size of the modifiers is extreme in other cases as well:
research lab -50 to illiteracy
stadium -50 to boredom
police station -75 to crime

i guess that only makes sense if you get +200 from tech level on the other side. so with the new model, many modifiers can be reduced (typical maximum for both city size and tech level modifier is around 30) or removed (unless you want them on the buildings to give them more flavor).

obviously i like my model better, but i see now that it has wider implications. so it's your call whether to go this way or not, you know best which additional knobs would need to be turned.

**Comment by LoneGazebo** [comment]
Well, that is what I was worried about. :) The tech modifier (as it stands now) allows for '-100+' modifiers to function - tweaking every building that has a modifier (or policies, etc.) is fairly complex, especially since the model as it stands is very functional.

Any way that you could retool the median-based scaler as it stands now to scale up to existing values? The one major positive is that the global average/median is less prone to swings.

G

**Comment by ilteroi** [comment]
honestly, i consider these extreme modifiers as bad design. a value -10, -20 is ok, but first inflating the thresholds hugely and then reducing them in giant steps seems clunky.

of course i can inflate my modifiers just as much, but i'd like to avoid that because it creates swings. also the tech modifier right now only applies to civs with above-average tech level.

and i wouldn't claim the model is perfect right now, i see a happiness crash in the late game every time as the thresholds explode. and then you need the magic building to magically fix it (which the AI often fails to build but that's a different topic). this is what's causing sudden swings.

**Comment by LoneGazebo** [comment]
Hmm. Perhaps, but as a counterpoint the modifiers used to be very slight (-5/-10%) but players complained that they couldn't feel the effects of the buildings. Thus the bigger numbers, and the bigger modifiers. I will agree that it can create swings, however the swings are in a _positive_ direction, which feels much, much better from a player's point of view.

G

**Comment by LoneGazebo** [comment]
Also, to note, I've been making tweaks to the AI's building selection model using the existing system and a lot of the late-game unhappiness issues are going away for the AI.

**Comment by ilteroi** [comment]
i give up. too late to change it now. i'll revert my changes.

**Comment by LoneGazebo** [comment]
I think it was and is an interesting concept, but it definitely has a lot of knock-on consequences.
