### ISSUE TITLE
Order tenet Guerilla Warfare dont increase experience

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3704]
_1. Mod version (i.e Date - 4/23):_
6 november

_2. Mod list (if using Vox Populi only, leave blank):_
WorldCongressReinform

_3. Error description:_ 
My Machine Gun and my Cruiser still get only 2 experience when attacking an enemies cruisers/corvettes. But I see that +15% to strength. 
Can post a save, but I think faster to check this in a new game on a small map...

**Comment by LoneGazebo** [comment]
It is experience 'in friendly borders,' not just in general.

G

**Comment by bigcat88** [comment]
Must it work in my own borders? I will recheck tomorrow in a clear game...

**Comment by LoneGazebo** [comment]
Yes.
