### ISSUE TITLE
2 Celts pantheons errors?

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3705]
_1. Mod version (i.e Date - 4/23):_
26 november

`('BELIEF_OGMA', 'BUILDINGCLASS_CIRCUS', 'YIELD_SCIENCE', `**4**`),`
`<Text>+1 [ICON_RESEARCH] Science for every 3 [ICON_CITIZEN] Citizens in a City. +3 [ICON_RESEARCH] Science, [ICON_CULTURE] Culture, and [ICON_GREAT_SCIENTIST] Great Scientist Points in [ICON_CAPITAL] Capital. `**+5**` [ICON_RESEARCH] Science from Ceilidh Hall</Text>`
		

`	('BELIEF_MANANNAN', 'BUILDINGCLASS_CIRCUS', 'YIELD_GREAT_ADMIRAL_POINTS', `**2**`),`
`			<Text>+3 [ICON_FOOD] Food, +3 [ICON_PRODUCTION] Production, and +4 [ICON_GOLD] Gold in coastal Cities. `**+5**` [ICON_GREAT_ADMIRAL] Great Admiral Points from Ceilidh Hall</Text>`

So somewhere here is a mistake...

**Comment by LoneGazebo** [comment]
Just a pair of tooltip text typos. I'll fix.
