### ISSUE TITLE
Goddess of Protection doesn't give +1 Science to Palace

### ISSUE THREAD

**Issue by tinozhang17** [LoneGazebo/Community-Patch-DLL#3708]
_1. Mod version (i.e Date - 4/23): 11-26 (the most recent one)

_2. Mod list (if using Vox Populi only, leave blank):_ info addict, enhanced terrain texture 2k, R.E.D Modpack

_3. Error description:_  Pantheon for Goddess of Protection (the one that gives +10HP in friendly territory) is supposed to give palace +1 science. But it's not doing so.

_4. Steps to reproduce (optional):_ Select Goddess of Protection and view the science output in the city screen and you will see the science output remain the same.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
That's just a text typo in the pantheon description. Will fix.
