### ISSUE TITLE
Question about GetReligionToFound; Request for GetBeliefToFound

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3709]
Would the GameEvent **GetReligionToFound** allow one to prevent the AI from founding a Religion? Such as by returning -1 or nil for the religion to found? I've run some tests, and setting it to return -1/nil appears ineffective, so I'm guessing not, but I can't say I've delved into the DLL there. 

Would it be possible to allow for such a thing?

On a related note, would it be possible to create an event like **GetBeliefToFound**, so that you could intercept the AI's belief choices? I'm trying to repurpose Byzantium's bonus belief, but am unable to restrict the AI's choices for it.

Thanks for any help.

**Comment by LoneGazebo** [comment]
Per Whoward (Who wrote this):

```
#if defined(MOD_EVENTS_FOUND_RELIGION)
		if (MOD_EVENTS_FOUND_RELIGION) {
			int iValue = 0;
			if (GAMEEVENTINVOKE_VALUE(iValue, GAMEEVENT_GetReligionToFound, ePlayer, eCivReligion, HasBeenFounded(eCivReligion)) == GAMEEVENTRETURN_VALUE) {
				// Defend against modder stupidity!
				if (iValue > RELIGION_PANTHEON && iValue < GC.getNumReligionInfos()) {
					// CUSTOMLOG("GetReligionToFound: Before=%i, After=%i", eCivReligion, iValue);
					eCivReligion = (ReligionTypes)iValue;
				}
			}
		} else {
#endif
```

**Comment by JFDaly** [comment]
Otru, rip. I suppose I can always kill off their Prophet if I need to. Any thoughts about the Belief override?

**Comment by LoneGazebo** [comment]
That's a bit trickier, as the belief selection happens in six different functions (Firaxis threw out all semblance of factory methods...in 2001), one for each of the different belief types. Which would you need?

G

**Comment by JFDaly** [comment]
Just the Bonus Belief that Byzantium normally has (which I want to repurpose). It's the 4th Belief ID that the Game.SendFoundReligion() event parses, if that helps.

**Comment by LoneGazebo** [comment]
Hmm...try this: 

Value, GAMEEVENT_GetBeliefToFound(PlayerID, ReligionID)

Should work, let me know if not.

[(1) Community Patch (v 88).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1523536/1.Community.Patch.v.88.zip)

**Comment by JFDaly** [comment]
Yeap, that does it. Do you think you could rename the event to GetBonusBeliefToFound for the next CP patch? Just for posterity's sake. Thank.

**Comment by JFDaly** [comment]
Oh, actually, it looks like the AI is founding the returned belief from that event in addition to the Bonus Belief.  Which works better actually, since it means I don't have to give every civ the BonusReligion in their trait - and thus the event as named makes sense.

**Comment by LoneGazebo** [comment]
@JFDaly yeah it works for any belief that you want to 'hook into' it with.
