### ISSUE TITLE
combat preview is unreliable

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3710]
initial preview:

![image](https://user-images.githubusercontent.com/1358966/33506251-5c499074-d6ef-11e7-9f34-3830d2c530a8.png)

actual result more like this:

![image](https://user-images.githubusercontent.com/1358966/33506265-66cfd62a-d6ef-11e7-8518-4e6ed509ed54.png)

the first problem is that the preview doesn't have the correct unit adjacency bonuses, because the unit has to move before attacking.

turns out it's mostly due to the flanking modifier:

```
		// Flanking
		if(!bIgnoreUnitAdjacencyBoni)
		{
			int iNumAdjacentFriends = pOtherUnit->GetNumEnemyUnitsAdjacent();
			if(iNumAdjacentFriends > 0)
			{
				iTempModifier = /*15*/ GC.getBONUS_PER_ADJACENT_FRIEND() * iNumAdjacentFriends;
				iModifier += iTempModifier * ((100 + GetFlankAttackModifier()) / 100);
			}
		}

```

it's a bit strange because it applies to both parties, so it often cancels out. so i propose to set BONUS_PER_ADJACENT_FRIEND to zero, which should help to make the preview more accurate.

**Comment by ilteroi** [comment]
oh no, that's not a good idea. need to think more.

**Comment by Voker57** [comment]
I think it's intended behaviour, compensating flank bonuses of attacker with proper positioning.

**Comment by ilteroi** [comment]
well, there's two problems with defensive flanking - it leaks information to the attacker and the AI isn't very good at it. but too late to change it, seems it has been like that forever.

so it's just the "flank attack" wording that's misleading. maybe fix the pedia?

anyway fixing the lua to take into account the actual battle plot is outside of my domain ... the GetMaxAttackStrength function does have a parameter to set the attacker plot, it's just that EnemyUnitPanel.lua always uses the current unit plot. 

i've fixed up GeneratePath() so that it should work from lua side and return an array of plots (table i guess in lua speak - but's it's copypaste and untested). so is there any lua expert who wants to have a go at it?

**Comment by LoneGazebo** [comment]
@JFDaly might be willing to look at it, maybe. He's the best LUAman involved in the project.

**Comment by JFDaly** [comment]
@ilteroi The UpdateCombatOddsUnitVsUnit function passes both the object and the subject plots, so passes the battle plot via pTheirUnit/pMyUnit according to who is attacking. What exactly do you need to know?

**Comment by ilteroi** [comment]
yeah, so this all happens in EnemyUnitPanel.lua - my main problem is that I don't know how to properly debug lua scripts whereas for somebody with the right setup this should be a 5 minute job.

the basic idea would be (for a melee attack where attacker and defender are not adjacent) to generate a path from attacker to defender and use the penultimate plot in the path as pFromPlot. maybe also highlight it somehow.

can you do that?

path generation function signature is Unit:GeneratePath(CvPlot* pToPlot, int iMaxTurns). the movement flags allow stacking, so it should still work if there are other units in between. the resulting table has the following structure:

```
	for (int i = 0; i < newPath.length(); i++)
	{
		const SPathNode& kNode = newPath.vPlots[i];

		lua_createtable(L, 0, 0);
		const int t = lua_gettop(L);
		lua_pushinteger(L, kNode.x);
		lua_setfield(L, t, "X");
		lua_pushinteger(L, kNode.y);
		lua_setfield(L, t, "Y");
		lua_pushinteger(L, kNode.moves);
		lua_setfield(L, t, "RemainingMovement");
		lua_pushinteger(L, kNode.turns);
		lua_setfield(L, t, "Turn");
		lua_pushinteger(L, 0);
		lua_setfield(L, t, "Flags");
		lua_pushboolean(L, newPath.get(i)->isVisible(pkUnit->getTeam())==false ); //don't have that info, make it up
		lua_setfield(L, t, "Invisible");
		lua_pushboolean(L, newPath.get(i)->isAdjacentNonvisible(pkUnit->getTeam()) ); //don't have that info, make it up
		lua_setfield(L, t, "AdjInvisible");
		lua_rawseti(L, -2, iCount++);
	}
```

not 100% sure about the order, might be back to front or front to back. code is pushed, debug build of the dll is here
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1525255/CvGameCore_Expansion2.zip)

**Comment by JFDaly** [comment]
This should work. pFromPlot will now be the last plot generated by your function before the one occupied by the enemy unit/city, and highlights the two spots on which combat takes place. If you want something changed, or something goes wrong, let me know.

I've marked by changed with JFD if you need to copy it over. This UnitPanel.lua is taken from the December 1st (6b) Community Balance Overhaul - Compatibility Files (No-EUI) folder. 

https://drive.google.com/file/d/1CHsPVdj5PWPBpOcSMPs6w8ybUJBuZVo0/view?usp=sharing

![preview](https://i.imgur.com/OYspKmu.jpg)

**Comment by ilteroi** [comment]
thank you! this is great!
