### ISSUE TITLE
Still got religion unhappiness after Rationalism's Free Thought

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#3712]
_1. Mod version (i.e Date - 4/23):_Nov 25, but I'm just now realizing I never dled the hotfix

_2. Mod list (if using Vox Populi only, leave blank):_
Full EUI VP
Randomize City Names, Celtic City Names, Iroquian City Names
Civ Linked Great Generals, Great People Pack. Great Prophet Historical Names, More Great Musicians, More Great Works
Favorite Religion Randomizer, Historical Religions
Flag Promotions
My own thing, which these days only removes the barb xp cap and renames some City States

_3. Error description:_ 
When I selected Free Thought, my religion unhappiness went from 8 to 5, not 8 to 0.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
The text is a little bit wonky, because technically a 100% reduction does, in fact, halve your minority unhappiness (i.e. 8 * 100 / (100+100) = 4; I'll change the text in the policy to reflect this.
