### ISSUE TITLE
Wrong production overflow with Wonders

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#3714]
_1. Mod version (i.e Date - 4/23):_

12/1

Predicted overflow +3 

![imagen](https://user-images.githubusercontent.com/13163824/33518129-14f94e02-d790-11e7-856e-efb6132658b7.png)

Finally being +16.8

![imagen](https://user-images.githubusercontent.com/13163824/33518156-b43caa22-d790-11e7-8e7b-160ca4422662.png)

**Comment by LoneGazebo** [comment]
Overflow prediction doesn't take into account the change in production of the city after the wonder is completed (i.e. the fact that you jumped to 20 from 16p). It also adds in the production cost of the wonder, which is inflated by the % to the cost of the wonder

**Comment by Mitchsp** [comment]
The increase from 16 to 20p is because +25% bonus to Cargo Ship from Progress, so not base production change and not justification going from 168/181 (+3 overflow estimated) to +16.8 overflow.
I'll observe this during the game and report if I've further info.

**Comment by Mitchsp** [comment]
Again with the next Wonder, from 1.8 to 7.8

![imagen](https://user-images.githubusercontent.com/13163824/33519535-fd5fb98e-d7a8-11e7-88ea-7ec1985a5a21.png)

![imagen](https://user-images.githubusercontent.com/13163824/33519544-23bac498-d7a9-11e7-8952-072a342bc212.png)

**Comment by LoneGazebo** [comment]
Ahhhhh I see the issue. Will toss on hotfix.
