### ISSUE TITLE
Incorrect improvement's turns calculation (at least with Liberty)

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#3715]
_1. Mod version (i.e Date - 4/23):_

12/1

7 turns needed
![imagen](https://user-images.githubusercontent.com/13163824/33518239-fb13bd68-d791-11e7-8d25-2e082f5b1375.png)

and still 7 turns after perfoming the action. Isn't readjusted the next turn. I think that only happens when an improvement is started, not if it's resumed later

![imagen](https://user-images.githubusercontent.com/13163824/33518267-655ae520-d792-11e7-9475-23d8db970739.png)

**Comment by LoneGazebo** [comment]
That's because they update at the end of your turn, not at the beginning. It is working as intended, but the interface only updates at the start of the turn.

**Comment by Mitchsp** [comment]
You can see the improvement is started during turn 84, 7 turns needed so it would be finished at turn 90.

![imagen](https://user-images.githubusercontent.com/13163824/33519624-a0eb9e78-d7aa-11e7-8493-b1033f52db96.png)

Turn 85 and still 7 turns left

![imagen](https://user-images.githubusercontent.com/13163824/33519816-e797459e-d7ae-11e7-9b54-d0e2ac431708.png)

Turn 88, 4 turns left, so it'll be finished at turn 91 instead of 90.
![imagen](https://user-images.githubusercontent.com/13163824/33519841-861ac754-d7af-11e7-9691-e6f091979432.png)

I reiterate that the problem is the turn starting the improvement not being counted (again at least with Liberty policy). This didn't happened before, so maybe it's being caused with the changes added to avoid multiples workers improvement the same tile.

**Comment by LoneGazebo** [comment]
I think I see why...we shall see if my fix fixes it

**Comment by Mitchsp** [comment]
Working fine G, great!

**Comment by LoneGazebo** [comment]
Yay.
