### ISSUE TITLE
Errors in Civilopedia with diplomatics units influence description

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#3717]
Gameinfo is showing the old influence value.
On the other side (3) CSD for CBP\Units\Units.xml production cost don't longer match ingame ones, so now they're stored in other place, right?

**Comment by LoneGazebo** [comment]
?

**Comment by Mitchsp** [comment]
Influence
Emissary's promotion now grants 30 influence, so GameInfo isn't updated.

Production cost
For Emissary, ingame 110 in 3) CSD for CBP\Units\Units.xml 100

![imagen](https://user-images.githubusercontent.com/13163824/33520798-4593ea22-d7c2-11e7-9981-7464d1426fb6.png)

![imagen](https://user-images.githubusercontent.com/13163824/33520792-196b53fe-d7c2-11e7-803e-05235e0e0b2d.png)
