### ISSUE TITLE
Parfume missing Monopoly Global Effect  description

### ISSUE THREAD

**Issue by Lurker69** [LoneGazebo/Community-Patch-DLL#3718]
_1. Mod version Vox Populi (11-26-2)

Parfume is missing monopoly description in CivPedia and there is no pop up window on Monopoly Screen.
I dont know if bonus is applied or or only description is missing. 

Based on http://civ-5-cbp.wikia.com/wiki/Monopolies bonus should be +5 global happiness.

**Comment by bigcat88** [comment]
In my game all is fine with perfume. +3 gold from monopoly description, cant say anything about bonus cause have no monopoly on it )

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict to me.
