### ISSUE TITLE
Request: CityStateStatusHelper.lua (12/1-1)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#3719]
Two strings are hardcoded.
Could you make it possible to translate them?

-----
1. **Embassy Established.**

(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\CityStateStatusHelper.lua
Line: 439

(6b) Community Balance Overhaul - Compatibility Files (No-EUI)\LUA\CityStateStatusHelper.lua
Line: 319

-----
2. **Establish an Embassy Available!**

(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\CityStateStatusHelper.lua
Line: 441

(6b) Community Balance Overhaul - Compatibility Files (No-EUI)\LUA\CityStateStatusHelper.lua
Line: 321

**Comment by LoneGazebo** [comment]
I didn't realize @TechpriestEnginseer hardcoded them. Yeah, I'll see what I can do for next time.
