### ISSUE TITLE
Unhappiness and Unit Supply missing.

### ISSUE THREAD

**Issue by Wonderbunny** [LoneGazebo/Community-Patch-DLL#3720]
_1. Mod version (i.e Date - 4/23):_
12/1 (Also happened with 11/26)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Top panel mouse-over displays current happiness, but no unhappiness.  Just says 0 from cities, 0 from population.  Also there is no Unit Supply information.  This is on a clean install of civ 5 (twice) with a fresh auto install of vox populi, only CP and CBP are checked in the mods screen in-game.  If I disable CBP and only use CP, the unhappiness displays correctly.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization
[Civ 5 Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1525024/Civ.5.Logs.zip)

5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
This is caused by either a bad install or a mod conflict. You need to make sure you are enabling all aspects of Vox Populi (not just (1) and (2).

**Comment by Wonderbunny** [comment]
Enabling all of them did fix the issue, thank you.  
However, I need to point out that even when I selected only the CP and CBP on the auto installer (so those were the only 2 mods I had at all) this same thing would happen.  That may need to be looked into.
Thanks again for the help, and for the timeliness of your response.
