### ISSUE TITLE
UnitPromotions_YieldChanges request

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3722]
Could you add a **UnitPromotions_YieldChanges** akin to the existing UnitPromotions_YieldModifiers, but for raw yields? There is a UnitPromotions_GarrisonYields, but this only works for garrison(ed/able) units, and thus not for units like Missionaries or Great People that are stationed in the city (for which _YieldModifiers does work). Thank.

**Comment by LoneGazebo** [comment]
Yep. Lua exposed as pCity->GetYieldFromUnitsInCity(eYield)
Table is:

<Table name="UnitPromotions_YieldChanges">
		<Column name="PromotionType" type="text" reference="UnitPromotions(Type)"/>
		<Column name="YieldType" type="text" reference="Yields(Type)"/>
		<Column name="Yield" type="integer"/>
	</Table>

Zipped CP (coming below) has a debug DLL in it - let me know if it doesn't work. Should work for any yield type.

**Comment by LoneGazebo** [comment]
[(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1525549/1.Community.Patch.zip)

**Comment by JFDaly** [comment]
This time, Culture and Faith worked well, but none of the standard yields (nor Golden Age Points) actually add to the city yields. Though they register correctly via GetYieldFromUnitsInCity.

**Comment by LoneGazebo** [comment]
Weird. I’ll check.

**Comment by LoneGazebo** [comment]
Fixed.

**Comment by LoneGazebo** [comment]
[(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1528202/1.Community.Patch.zip)

**Comment by JFDaly** [comment]
Yeap, that does it. Thanks.
