### ISSUE TITLE
Question about CombatBonusFromNearbyUnitClass

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3723]
I'm having some trouble getting CombatBonusFromNearbyUnitClass to work.

Basically, I have a Promotion that has CombatBonusFromNearbyUnitClass filled out with UNITCLASS_MISSIONARY, with a NearbyUnitClassBonusRange of 1 (though tested with 2) and a NearbyUnitClassBonus of 10 (though tested with 100), and it doesn't seem to take effect. I was wondering if the functionality was limited in some way (say, to only combat unit classes giving the bonus)? 

I did notice that CombatBonusFromNearbyUnitClass asks for an integer, but UNITCLASS_MISSIONARY to the ID of the Missionary didn't resolve the issue.

Any enlightenment would be great.

**Comment by LoneGazebo** [comment]
![untitled](https://user-images.githubusercontent.com/7849458/33533990-af1a72da-d872-11e7-8280-46cd8ffbe27a.png)

**Comment by LoneGazebo** [comment]
I just tested with this promotion, worked fine for me.

```
<Row>
			<Type>PROMOTION_DEBUG</Type>
			<Description>TXT_KEY_PROMOTION_PROMOTION_DEBUG</Description>
			<Help>TXT_KEY_PROMOTION_PROMOTION_DEBUG_HELP</Help>
			<Sound>AS2D_IF_LEVELUP</Sound>
			<CannotBeChosen>true</CannotBeChosen>
			<OrderPriority>1</OrderPriority>
			<NearbyUnitClassBonusRange>1</NearbyUnitClassBonusRange>
			<NearbyUnitClassBonus>50</NearbyUnitClassBonus>
			<CombatBonusFromNearbyUnitClass>UNITCLASS_MISSIONARY</CombatBonusFromNearbyUnitClass>
			<PortraitIndex>57</PortraitIndex>
			<IconAtlas>PROMOTION_ATLAS</IconAtlas>
			<PediaType>PEDIA_SHARED</PediaType>
			<PediaEntry>TXT_KEY_PROMOTION_PROMOTION_DEBUG</PediaEntry>
		</Row>
```

**Comment by JFDaly** [comment]
Ah, seems I had two issues. One, I'd misspelled UNITCLASS_MISSIONARY as UNITLCASS_MISSIONARY, and two, I don't have GetNearbyUnitClassModifierFromUnitClass in the unitpanel. I'll have to add support. Sorry for the false alarm, it all works perfectly. Thanks for checking it out.

**Comment by LoneGazebo** [comment]
No worries!

**Comment by LoneGazebo** [comment]
To note you can’t currently give a unit more than one promotion like this. If you need support for that later let me know.
