### ISSUE TITLE
GameEvent for rigging elections and city-state coups?

### ISSUE THREAD

**Issue by theazuresoul** [LoneGazebo/Community-Patch-DLL#3726]
Not a high priority, and I don't know if it would be worth the effort, but it would be helpful if a Lua event were triggered when an election is rigged and/or a coup succeeds.

**Comment by JFDaly** [comment]
I think the existing GameEvents.EspionageResult(iPlayer, iSpy, iResult, iCityX, iCityY) might do for what you want. I'm not sure what IDs the spy actions such as rigging elections have though.

**Comment by theazuresoul** [comment]
I tried EspionageResult. It doesn't trigger for city-state actions.

**Comment by LoneGazebo** [comment]
Done. Added as 'ElectionResultSuccess' and 'ElectionResultFailure'. Note that SpyID in ElectionResultFailure can be null or -1. Same layout as EspionageResult.
