### ISSUE TITLE
great diplomat cannot build embassy

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3727]
![image](https://user-images.githubusercontent.com/1358966/33593090-1d2b0714-d98e-11e7-97c4-bdd76f8e46eb.png)

what's up?

**Comment by cdanger341** [comment]
Maybe it's tied to stacked Worker units sometimes disappearing from the UI until other units move on top of them or move away from them? If a Worker was building/repairing that Cow resource then the GD can't place an embassy there, and it's possible the Spearman is "hiding" the active Worker from the UI.

**Comment by LoneGazebo** [comment]
Does Ormus own another city that has an embassy?

**Comment by ilteroi** [comment]
no hidden worker, no secondary city ... guess i'll have to fire up the debugger

**Comment by TechpriestEnginseer** [comment]
Isn't it that you can't build Embassy above resources?

**Comment by ilteroi** [comment]
indeed, this check is the problem:
```
	ResourceTypes thisResource = getResourceType( ePlayer!=NO_PLAYER ? GET_PLAYER(ePlayer).getTeam() : NO_TEAM );
	// The functionality of this line is different in Civ 4: in that game a "Valid" Resource ALLOWS an Improvement on a Tile.  In Civ 5 this makes a Resource REQUIRE a certain Improvement
	if(thisResource != NO_RESOURCE &&
	        !pkImprovementInfo->IsBuildableOnResources() &&	// Some improvements can be built anywhere
	        !pkImprovementInfo->IsImprovementResourceMakesValid(thisResource))
	{
		return false;
	}
```

this is a bit strange because the embassy differs from other great person improvements in this respect.  also it isn't mentioned in the pedia ... so what now?

**Comment by bigcat88** [comment]
It is always was like this. And that's why better to establish embassies before coal & aluminium & oil will be revealed, with abundant number of res there is almost always one kind of these resources that block embassy on nice tile near CS )
For me it will be better to allow establish embassy on all resources, if embassy on some plantation will not raise glitches(like citadel)

**Comment by LoneGazebo** [comment]
@ilteroi for some reason the embassy causes really bad graphical glitches on resource tiles. That’s why I did it that way originally.

**Comment by ilteroi** [comment]
well then it's probably best to fix the 'pedia and that's it
