### ISSUE TITLE
Pillage ommission in CountNumWorkedImprovement()

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3729]
Sorry for the recent slew of requests; just going through some outstanding issues in the lead-up to JFDLC's public release for christmas.

Could you please have city:CountNumWorkedImprovements() omit pillaged improvements? Or, if its more sensible, add an IgnoresPillaged boolean check to the function so that it can be used that way.

Thanks.

**Comment by LoneGazebo** [comment]
Added bool, but it defaults to true (true == ignore pillaged improvements) so you shouldn't have to change your code.

G

**Comment by JFDaly** [comment]
Awesome, thanks.
