### ISSUE TITLE
Conscription Triggers on Selecting a Policy

### ISSUE THREAD

**Issue by DanteValerian** [LoneGazebo/Community-Patch-DLL#373]
I have the Conscription policy from the Might tree. When I selected the Piety opener, the Conscription policy triggered in my capital, like it did when I first picked it.

I am running ExCE, with most options disabled for compatibility.

EDIT: The conscription policy is triggering on every policy I pick after I complete the Might tree. I'm simply disbanding the units right now.

**Comment by joosegoose** [comment]
I haven't completed Might yet, but for what it's worth I received absolutely nothing when selecting the Conscription policy. Completely different error from the same policy.

**Comment by joosegoose** [comment]
I'm having the same issue in the new version. To clarify, no unit appears in the capital when selecting the policy, but the ranged unit in every subsequent founded city works just fine.
