### ISSUE TITLE
Runtime Error (12/6)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#3732]
_1. Mod version (i.e Date - 4/23):_
12/6

_2. Mod list (if using Vox Populi only, leave blank):_
VP + EUI (Automatic Install)

_3. Error description:_ 
When I check Civilopedia, the pages of diplomatic units don't show up correctly.
Lua error?

> [3474.423] Runtime Error: D:\Users\a8541\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\CivilopediaScreen.lua:2860: attempt to compare number with nil

_4. Steps to reproduce (optional):_
Open Civilopedia
Check the pages of diplomatic units

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1538999/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![pedia](https://user-images.githubusercontent.com/11933188/33715008-6939f8b0-db94-11e7-8c3e-309e895a7cf6.png)

**Comment by LoneGazebo** [comment]
Weird. I didn’t touch that.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer's trigger did it. Will remove.
