### ISSUE TITLE
tecnology tree bug

### ISSUE THREAD

**Issue by danicola** [LoneGazebo/Community-Patch-DLL#3734]
_1. Mod version (i.e Date - 4/23):_12/6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ can´t see most tecnologies in the tech tree, but i can pick them without entering in the tree. it seems like the tech tree cant complile or cant order properly in the window. the game dont crash and i dndt see any other problems.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Vyyt02** [comment]
Haven't played for a while, but this is typically happening when you are missing a DLC, have a mod conflict, there are some strange leftovers in the game cache. Are you new to VP? Did the tech tree work for you before?

**Comment by Zarrk** [comment]
I'm a too encountering a broken tech tree:
1) Version 12-6-1
2) Vox Populi No-EUI (the EUI version show a working tech tree)
3) Most of the tech 'boxes' are missing and no possibilty to navigate the tree. 
![brokentree](https://user-images.githubusercontent.com/29424034/33744317-fb9fd85c-dbb0-11e7-8272-26705bff927f.png)
It looks a lot like a bug from mid-June (issue #1965) I even found an error in lua.log


[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1540984/Logs.zip)

**Comment by danicola** [comment]
Yap, same problem Zarrk. And i can confirm that it only occurs with the no-eui version, the eui works perfectly.

**Comment by LoneGazebo** [comment]
Try updating to the hotfix.

**Comment by Zarrk** [comment]
Thanks, all is good now.
