### ISSUE TITLE
Runestone civpedia (or maybe balance idk)

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#3737]
Runestone says it gives plus 25 percent to melee ship construction, but its really 50 percent.

**Comment by Infixo** [comment]
DLCChanges.sql

INSERT INTO Building_UnitCombatProductionModifiers
	(BuildingType, UnitCombatType, Modifier)
VALUES
	('BUILDING_JELLING_STONES', 'UNITCOMBAT_MELEE', 25),
	('BUILDING_JELLING_STONES', 'UNITCOMBAT_NAVALMELEE', 50);
