### ISSUE TITLE
Feature Request: Belief Buildings

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#3738]
Is it possible to make a religious building like the cathedral accessible via a new event choice option? Presumably having an `EventBelief` element like `EventPolicy` would be weird, but would it be possible to cook up an `UnlocksBuildingClass` sort of thing? If it were could it also use `Expires` in such a way that it is no longer to build said building class, but ones that had been built were not removed?

Many thanks

**Comment by TechpriestEnginseer** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/3395

**Comment by Hokath** [comment]
I'm trying to solve my problem by using the feature added in #3395 to make pseudo-religious buildings.
They appear in the civilopedia (under Religious Buildings) and the firetuner shows that <EventChoiceRequiredActive> is correctly pointing to the event choice I want. However if I use the firetuner to activate that event choice, they don't appear in the city list as available to purchase.

Any ideas?
I saw this thread referencing <Belief_BuildingClassFaithPurchase> and wondered if anyone knew anything further: https://forums.civfanatics.com/threads/purchasing-unique-units-buildings-with-faith.530577/

**Comment by TechpriestEnginseer** [comment]
I exactly don't get the problem here. If I naturally get the event choice(like every players should), the building should show up provided you have a majority religion active and such.

**Comment by Hokath** [comment]
ah it required majority religion. Working now, ty.
