### ISSUE TITLE
Annoying bug

### ISSUE THREAD

**Issue by GeneralsAlert** [LoneGazebo/Community-Patch-DLL#3739]
_1. Mod version (i.e Date - 4/23):_
December 1st
_2. Mod list (if using Vox Populi only, leave blank):_
COTU Combine
Vietnam (with path)
Fallout NCR and Legion
Kyrat
Rook Island
Arstotzka
Better Helicopters
Diplomacy values 
Dr. Wily
naval units for Vox
Faster aircraft
Historical Religions
Hyperon's Finland
Improved air recon 
Industrial  building pack
Ingame Editor
 JFD Hitler, Tojo, Mussolini, Republic of France, Republican of Poland, Russian Federation, Soviet Union, UK of Great Britain, and USA (Roosevelt) 
Gwyn
medieval and renaissance building pack
More Luxuries
Music Changer
Natural  wonder collection
Pretorian Civ
 Really advance sit up
Red Alert 2 Allied and Soviet Civ
Reseed
SRF Yugoslavia
 Special Forces upgrade for marines
  strategic   resource buildings
 Super Mario Bros Bowser
Team Fortress
Team Gurren
Atlantic Federation BNW
Eastern European Imperial Alliance
The Goths
The Sims
trading post turns into towns
Uighur Caesar's North Korea
Valkriya Chronicles Gallia 
woodland and forest paratrooper Camo
Empire of Rising Sun
Yuri Psychic empire 
Yuri Slave Miner
Zootopia
 
_3. Error description:_ 
After like turn 30 or a Parthenon belief is made, Me and the AI would get free 1 Great scientist and General Every..Single...Time. 

What's going on? this worked just fine in earlier  Vox versions

_4. Steps to reproduce (optional):_
Start in Ancient Era, and try to get to around turn 20-30 or get a Parthenon belief 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1544034/Logs.zip)

Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1544047/Saves.zip)

**Comment by LoneGazebo** [comment]
That’s way too many mods to debug.

**Comment by MoiMagnus** [comment]
You put "more luxuries" in the list. Having both VP (which include mores luxuries) and the steam's more luxuries installed (even not enabled) is known to cause problems.
However, this is not linked to your pantheon problem.

Try without any other mods (in game editor is ok).
