### ISSUE TITLE
Isolation unhappiness in capital

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#374]
I know this has been around a while so apologies if it's already being looked at, but the capital appears to still be incurring isolation unhappiness in the 6/27 version. I'm running the CPP bundle w/ EUI compatibility.

**Comment by DanteValerian** [comment]
I'm getting isolation in the capital as well. Disappears when I make my first city connection to the capital.

Also the same thing happens for Railroads I think. There seems to be a problem there too.

**Comment by LoneGazebo** [comment]
Ilteroi looked at this for the second-to-most-recent patch. I'm not sure why it is still occurring. I'll make sure he knows. In the meantime, I've added some simple checks to prevent the most glaring errors (underlying problem is unresolved).
G
