### ISSUE TITLE
Dynamite and the Great Wall

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#3740]
_1. Mod version (i.e Date - 4/23):_latest

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_   It seems that discovery of Dynamite doesn't disable the Great Wall effect. I've discovered dynamite a while ago but my units still spend all their moves upon entering the territory of a Civ that has the Great Wall built.

**Comment by LoneGazebo** [comment]
The effect applies when they discover it, not you.

**Comment by saamohod** [comment]
Good to know. Case closed :)
