### ISSUE TITLE
eStolenTech is still always returning -1 on GameEvents.EspionageNotificationData

### ISSUE THREAD

**Issue by theazuresoul** [LoneGazebo/Community-Patch-DLL#3741]
Behavior is the same as the previous version.

The new ElectionResultSuccess is working great though. Thanks much!

**Comment by LoneGazebo** [comment]
Don't know what to tell you...there's no other changes I can make to it.

**Comment by theazuresoul** [comment]
Could you please elaborate on that? Is it t cynical limitations? Unable to reproduce? What were the changes you made last time, and did they work?

**Comment by theazuresoul** [comment]
*technical

**Comment by LoneGazebo** [comment]
The code draws on eStolenTech, and eStolenTech is passed into LUA. It is a very simple check, and the notification system works (thus it should work for you). There's nothing else I can change to it.

**Comment by theazuresoul** [comment]
I’ll try again. Does the event return the correct values on your end?

**Comment by LoneGazebo** [comment]
Yes, it does. The lua injection occurs in the same function as the notification for a stolen tech, so - since that works - there's nothing stopping the lua injection from working.

**Comment by theazuresoul** [comment]
Tried it again, and still doesn't work, for either the player or the AI. I guess I'll just have to find a workaround.
