### ISSUE TITLE
Defense production giving absurd amount of city CS.

### ISSUE THREAD

**Issue by ElliotS-1** [LoneGazebo/Community-Patch-DLL#3745]
_1. Mod version (i.e Date - 4/23):_
12/6

_2. Mod list (if using Vox Populi only, leave blank):_
Improved City View
Unit Path Viewer
Unique City States
Flag Promotions

In a Modpack

_3. Error description:_ 
When the AI (Or presumably human, I didn't check) focuses defense, the city will get an absurd amount of defense CS. We're talking going from 30 to 70 in medevial era. It's absurd.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1545814/Logs.zip)

[AutoSave_0126 AD-0275.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1545815/AutoSave_0126.AD-0275.zip)

**Comment by notque** [comment]
Change submitted as a pull request to take it from 100 to 10 as expected.
