### ISSUE TITLE
Partial reward from CS quest "War breaks between X and Y"

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#3747]
The problem happens when obtaining the alliance status with the influence received from another quest (in this case construction project for Vancouver) the partial reward from Ormus is received correctly but isn't the case from Vancouver, receiving the reward from first quest (construction project) but not the partial reward.
I've tried to obtain the alliance by other means and both partial rewards are correctly granted.

![imagen](https://user-images.githubusercontent.com/13163824/33810035-e094981c-ddff-11e7-9e3f-26a44e5a79a4.png)

**Comment by LoneGazebo** [comment]
Can you elaborate?

**Comment by Mitchsp** [comment]
Situation 1 (working fine)
Turn 98
Being allied with Ormus, obtaining allied condition with Vancouver without the influence received from a quest, for example using emissaries.
Turn 99
Vancouver has made peace with Ormus!  Partial reward is granted from both CS.

Situation 2 (working wrong)
Turn 98 
Being allied with Ormus, finishing a quest for Vancouver (construction project) 
Turn 99
Obtaining alliance with Vancouver with the influence obtained from a quest finished previous turn (construction project).
Vancouver has made peace with Ormus! 
Partial reward is granted from Ormus, nothing from Vancouver.

**Comment by LoneGazebo** [comment]
Hmm, it's because of how the 'stack' works for processing a quest - the quest ordering is processed such that I can't really prevent this. It is a pretty fringe case...

G
