### ISSUE TITLE
Terracotta Army gives both Pathfinder and Scout

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#3748]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by pandasnail** [comment]
It gives you one copy of everything you own. If you have unupgraded chariots or warriors, you'll get one of those as well.

**Comment by LoneGazebo** [comment]
Yup.

**Comment by Mitchsp** [comment]
Ok, I thought it was one unit from each category you had (Recon, Archer, Melee land, Skirmisher...) and not one copy from each type of unit (Pathfinder, Scout, Warrior, Spearman...).

Anyway if this isn't a bug, probably is a matter of balance and too much value for the cost, obtaining 200 culture, +1 supply for city plus a lot of units.
