### ISSUE TITLE
GameEvent.MissionStarted/Completed()

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3749]
Would a GameEvent for when a unit performs (or completes) a mission be possible? I see that Gedemon added a GameEvents.PushingMissionTo() event, but I'm not sure how or if this functions in the CP as it didn't seem to yield the result I'm looking for (i.e. just letting me know when a GP does a mission). 

Depending on how possible that is, a GameEvents.MissionPossible() would also be needed alongside it.

**Comment by LoneGazebo** [comment]
Would you also need MissionImpossible? :)

**Comment by LoneGazebo** [comment]
I think this already exists: MOD_EVENTS_CUSTOM_MISSIONS

GAMEEVENT_CustomMissionSetActivity
GAMEEVENT_CustomMissionPossible

**Comment by JFDaly** [comment]
Kek.

CustomMissions only work on CustomMissions, they don't catch the base game ones (e.g. MISSION_FOUND_RELIGION). So maybe it'd be easier to allow them to do so, I'm not sure.

**Comment by LoneGazebo** [comment]
Yeah, so he had them at the end of an 'else if' chain - I remove the else if. I won't be able to look at it again until tomorrow so let me know if this works (or does anything strange). If not, I'll do something more advanced.

Link incoming.

**Comment by LoneGazebo** [comment]
[(1) Community Patch (v 88).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1546579/1.Community.Patch.v.88.zip)

**Comment by JFDaly** [comment]
Hm, unfortunately not. CustomMissionPossible() definitely goes through the missions, but seems to pay no heed to the boolean at the end of the function, so doesn't actually disable/enable the missions. And MissionStarted()/MissionCompleted() don't fire at all.

No rush to look into this, but much appreciated when you get a chance.

**Comment by LoneGazebo** [comment]
Figured. I’ll see what I can do.

**Comment by LoneGazebo** [comment]
Okay, so here's what Whoward has for those functions:

` if (GAMEEVENTINVOKE_TESTANY(GAMEEVENT_CustomMissionPossible, hUnit->getOwner(), hUnit->GetID(), iMission, iData1, iData2, 0, -1, pPlot->getX(), pPlot->getY(), bTestVisible) == GAMEEVENTRETURN_TRUE)`

**Comment by LoneGazebo** [comment]
(tell me what of this data is needed, and what is/is not being used by you)

**Comment by LoneGazebo** [comment]
```
#if defined(MOD_EVENTS_CUSTOM_MISSIONS)
		if (MOD_EVENTS_CUSTOM_MISSIONS) {
			int iValue = 0;
			if (GAMEEVENTINVOKE_VALUE(iValue, GAMEEVENT_CustomMissionSetActivity, hUnit->getOwner(), hUnit->GetID(), pkQueueData->eMissionType, pkQueueData->iData1, pkQueueData->iData2, pkQueueData->iFlags, pkQueueData->iPushTurn) == GAMEEVENTRETURN_VALUE) {
				if (iValue == CUSTOM_MISSION_ACTION ) {
					bNotify = true;
				} else if (iValue == CUSTOM_MISSION_DONE ) {
					bDelete = true;
				} else if (iValue == CUSTOM_MISSION_ACTION_AND_DONE ) {
					bNotify = true;
					bDelete = true;
				}
			}
		}
#endif
```

**Comment by LoneGazebo** [comment]
```
#if defined(MOD_EVENTS_CUSTOM_MISSIONS)
			if (MOD_EVENTS_CUSTOM_MISSIONS) {
				int iValue = 0;
				if (GAMEEVENTINVOKE_VALUE(iValue, GAMEEVENT_CustomMissionStart, hUnit->getOwner(), hUnit->GetID(), pkQueueData->eMissionType, pkQueueData->iData1, pkQueueData->iData2, pkQueueData->iFlags, pkQueueData->iPushTurn) == GAMEEVENTRETURN_VALUE) {
					if (iValue == CUSTOM_MISSION_ACTION) {
						bAction = true;
					}
				}
			}
#endif
```

**Comment by LoneGazebo** [comment]
```
#if defined(MOD_EVENTS_CUSTOM_MISSIONS)
		if (MOD_EVENTS_CUSTOM_MISSIONS) {
			int iPlotIndex = -1;
			if (GAMEEVENTINVOKE_VALUE(iPlotIndex, GAMEEVENT_CustomMissionTargetPlot, hUnit->getOwner(), hUnit->GetID(), pMissionNode->eMissionType, pMissionNode->iData1, pMissionNode->iData2, pMissionNode->iFlags, pMissionNode->iPushTurn) == GAMEEVENTRETURN_VALUE) {
				if (iPlotIndex >= 0 ) {
					CvPlot* pPlot = GC.getMap().plotByIndex(iPlotIndex);

					if (pPlot) {
						return pPlot;
					}
				}
			}
		}
#endif
```

**Comment by LoneGazebo** [comment]
```
#if defined(MOD_EVENTS_CUSTOM_MISSIONS)
		if (MOD_EVENTS_CUSTOM_MISSIONS) {
			int iValue = 0;
			if (GAMEEVENTINVOKE_VALUE(iValue, GAMEEVENT_CustomMissionTimerInc, hUnit->getOwner(), hUnit->GetID(), kMissionData.eMissionType, kMissionData.iData1, kMissionData.iData2, kMissionData.iFlags, kMissionData.iPushTurn) == GAMEEVENTRETURN_VALUE) {
				if (iValue != 0) {
					iTime += iValue;
				}
			}
		}
#endif
```

**Comment by LoneGazebo** [comment]
```
#if defined(MOD_EVENTS_CUSTOM_MISSIONS)
		if (MOD_EVENTS_CUSTOM_MISSIONS) {
			if (GAMEEVENTINVOKE_TESTANY(GAMEEVENT_CustomMissionCompleted, hUnit->getOwner(), hUnit->GetID(), kMissionData.eMissionType, kMissionData.iData1, kMissionData.iData2, kMissionData.iFlags, kMissionData.iPushTurn) == GAMEEVENTRETURN_TRUE) {
				return true;
			}
		}
#endif
```

**Comment by JFDaly** [comment]
I'd need the ownerID, unitID, missionID, and bTestVisible. The plots would be good but not necessary since they can be retrieved from the unit.

**Comment by LoneGazebo** [comment]
So, for example, here: 

if (GAMEEVENTINVOKE_TESTANY(GAMEEVENT_CustomMissionPossible, hUnit->getOwner(), hUnit->GetID(), iMission, iData1, iData2, 0, -1, pPlot->getX(), pPlot->getY(), bTestVisible)

With all of the required values put in place, the function doesn't grab your custom mission?

**Comment by JFDaly** [comment]
Hm, not sure I'm following. That event does grab and delimits custom missions fine, but not base game ones.

**Comment by LoneGazebo** [comment]
I guess I'm not following either. I thought you wanted to inject an event _period_, and the custom events were blocking it because of the 'else if' issue (i.e. they were only looking at non-standard events). Is this wrong?

**Comment by JFDaly** [comment]
I do want CustomMissionPossible to pass all missions, yeah. With your fix yesterday, it does do that, however, CustomMissionPossible should also return whether or not the mission can be performed - which doesn't currently work with non-standard missions.

**Comment by LoneGazebo** [comment]
Hmm...there's a core lua scripting element in here as well:

```
// Prevented by scripting?
	ICvEngineScriptSystem1* pkScriptSystem = gDLL->GetScriptSystem();
	if(pkScriptSystem)
	{
		CvLuaArgsHandle args;
		args->Push(hUnit->getOwner());
		args->Push(hUnit->GetID());
		args->Push(iMission);

		// Attempt to execute the game events.
		// Will return false if there are no registered listeners.
		bool bResult = false;
		if(LuaSupport::CallTestAll(pkScriptSystem, "CanStartMission", args.get(), bResult))
		{
			// Check the result.
			if(bResult == false)
			{
				return false;
			}
		}
	}
```
Not helpful?

**Comment by JFDaly** [comment]
Oh wow, that's exactly what I wanted, yeah. Maybe it was introduced in BNW since I didn't find it on the Wiki. Cool. So it'd just be the MissionStarted()/MissionCompleted() event that'd I'd need then, unless something like that already exists undocumented.

**Comment by LoneGazebo** [comment]
i'll look.

**Comment by LoneGazebo** [comment]
[(1) Community Patch (v 88).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1549423/1.Community.Patch.v.88.zip)

Try this maybe?

**Comment by JFDaly** [comment]
hm. GameEvents.MissionStarted() right? Didn't seem to trigger.

**Comment by LoneGazebo** [comment]
No, use the custom missions for the other two you wanted.

**Comment by LoneGazebo** [comment]
CustomMissionStart
CustomMissionCompleted

**Comment by JFDaly** [comment]
Ah, right. Should've thought of that. Yeap, those work perfectly. Thanks, this'll be very useful.

**Comment by LoneGazebo** [comment]
awesome!
