### ISSUE TITLE
strange AI WC votes

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3750]
so i've got this test game with runaway spain, they picked freedom and seemed to go for cultural victory.

anyway they repealed the travel ban resolution, then tried to pass the passport system, which i stopped.

now i proposed travel ban again and they voted _for_ it. could there be a good reason for that or is it a bug?

**Comment by LoneGazebo** [comment]
The AI can shift gears on a proposal if they change their grand strategy - that can happen if two strategies are fairly close together value-wise, and one isn't working out. Have the grandstrategy AI log?

**Comment by ilteroi** [comment]
unfortunately not, restarted in the meantime ...

right now they go for diplomatic victory:

340, Spain, AIGRANDSTRATEGY_CULTURE, 2415, 0
340, Spain, *** AIGRANDSTRATEGY_UNITED_NATIONS, 2837, 0
340, Spain, AIGRANDSTRATEGY_SPACESHIP, 2153, 0
340, Spain, AIGRANDSTRATEGY_CONQUEST, 1, 0

but indeed it seems fairly close to culture in their preference

**Comment by LoneGazebo** [comment]
Did she sell her vote?

**Comment by LoneGazebo** [comment]
World congress log has scoring too.

**Comment by ilteroi** [comment]
unfortunately the world congress log is also rather short. note that spain is sanctioned - most of the time their own proposal is simply to repeal the sanctions but sometimes they choose something else.

336, 1966,Spain,- - -,Evaluating for Delegates,ENACT: Travel Ban,Yea,1806
336, 1966,Spain,- - -,Evaluating for Delegates,ENACT: Spaceflight Regulations,Nay,86
336, 1966,Spain,- - -,Evaluating for Delegates,REPEAL: Open Door: Hanoi,Yea,1194
336, 1966,Spain,- - -,Committing Delegates,REPEAL: Open Door: Hanoi,Yea,13
336, 1966,Spain,- - -,Committing Delegates,ENACT: Travel Ban,Yea,11 <---- this is what made me suspicious

336, 1966,Congress,- - -,Proposal Passed,REPEAL: Open Door: Hanoi,Yea,Won by 13
336, 1966,Congress,- - -,Proposal Passed,ENACT: Travel Ban,Yea,Won by 58
336, 1966,Congress,- - -,Proposal Passed,ENACT: Spaceflight Regulations,Yea,Won by 1

337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,United Nations,,15719
337, 1967,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Sanction,,1069
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,World Religion,[ICON_RELIGION_CHRISTIANITY] Catholicism,819
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,Byzantium,669
337, 1967,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Global Peace Accords,,519
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,Egypt,519
337, 1967,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Open Door,,395
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,France,369
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Bogota,219
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Bratislava,219
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Kyzyl,219
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,La Venta,219
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Vatican City,219
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Milan,219
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Samarkand,219
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Kyzyl,213
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Bogota,213
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Bratislava,213
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,La Venta,213
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Vatican City,213
337, 1967,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Spaceflight Regulations,,205
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Samarkand,193
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Milan,193
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_IVORY] Ivory,119
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,Assyria,119
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Sofia,119
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_GOLD] Gold,119
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_INCENSE] Incense,119
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_SALT] Salt,119
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,Egypt,119
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_CITRUS] Citrus,119
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,Byzantium,119
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_COFFEE] Coffee,119
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Cold War,,119
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,The Shoshone,119
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,The Huns,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_FUR] Furs,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_JEWELRY] Jewelry,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_PORCELAIN] Porcelain,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_COPPER] Copper,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Natural Heritage Sites,,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,City-State Sanctions,,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Byblos,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Sydney,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Hanoi,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Lhasa,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,Persia,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Global Wargames,,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,France,69
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_WHALE] Whales,19
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_COCOA] Cocoa,19
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Endowment for the Arts,,19
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_CRAB] Crab,19
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_PEARLS] Pearls,19
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_SILK] Silk,19
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_MARBLE] Marble,19
337, 1967,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Cultural Heritage Sites,,19
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Three Gorges Dam,,0
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Hollywood,,0
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Choose Host,,0
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_GEMS] Gems,0
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,The Cultural Revolution,,0
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_GLASS] Glass,-1
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_OLIVE] Olives,-1
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_SUGAR] Sugar,-1
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Global Liberation,,-11
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,World Science Initiative,,-31
337, 1967,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Sphere of Influence,,-161
337, 1967,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Sphere of Influence,,-161
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Scholars In Residence,,-231
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Sofia,-453
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,World Religion,[ICON_RELIGION_ORTHODOX] Eastern Orthodoxy,-511
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,World Religion,[ICON_RELIGION_BUDDHISM] Buddhism,-511
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Sydney,-613
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Lhasa,-651
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,Persia,-801
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,The Shoshone,-801
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,The Huns,-801
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,Assyria,-801
337, 1967,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Historical Landmarks,,-861
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Byblos,-1043
337, 1967,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Hanoi,-1131
337, 1967,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Travel Ban,,-1731

343, 1973,Spain,- - -,Evaluating for Delegates,ENACT: International Games,Yea,59
343, 1973,Spain,- - -,Evaluating for Delegates,ENACT: World Religion: [ICON_RELIGION_BUDDHISM] Buddhism,Nay,599
343, 1973,Spain,- - -,Evaluating for Delegates,REPEAL: Sanction: Spain,Yea,1039
343, 1973,Spain,- - -,Committing Delegates,REPEAL: Sanction: Spain,Yea,25

343, 1973,Congress,- - -,Proposal Failed,REPEAL: Sanction: Spain,Nay,Won by 2
343, 1973,Congress,- - -,Proposal Failed,ENACT: International Games,Nay,Won by 1
343, 1973,Congress,- - -,Proposal Passed,ENACT: World Religion: [ICON_RELIGION_BUDDHISM] Buddhism,Yea,Won by 7

344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,United Nations,,15706
344, 1974,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Sanction,,1066
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,Byzantium,666
344, 1974,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,World Religion,,546
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,Egypt,506
344, 1974,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Open Door,,428
344, 1974,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Global Peace Accords,,326
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Milan,318
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,France,226
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Samarkand,208
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Samarkand,206
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Kyzyl,198
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Bratislava,198
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Bogota,198
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,La Venta,198
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Vatican City,198
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Kyzyl,196
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Bogota,196
344, 1974,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Spaceflight Regulations,,196
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Vatican City,196
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,La Venta,196
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Bratislava,196
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,Byzantium,136
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,Assyria,136
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,The Shoshone,136
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,Egypt,136
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Cold War,,116
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_JEWELRY] Jewelry,96
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_PORCELAIN] Porcelain,96
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_INCENSE] Incense,86
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_SALT] Salt,86
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_CITRUS] Citrus,86
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_COFFEE] Coffee,86
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_GOLD] Gold,86
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,Persia,86
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Global Wargames,,86
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,The Huns,76
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Sofia,66
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Endowment for the Arts,,46
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Hanoi,46
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Sydney,46
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,City-State Sanctions,,36
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_IVORY] Ivory,26
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_FUR] Furs,26
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,International Games,,26
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_COCOA] Cocoa,26
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,France,26
344, 1974,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Cultural Heritage Sites,,26
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_WHALE] Whales,26
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_COPPER] Copper,26
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_MARBLE] Marble,6
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_SILK] Silk,6
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_CRAB] Crab,6
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_PEARLS] Pearls,6
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Natural Heritage Sites,,6
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_GEMS] Gems,6
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Three Gorges Dam,,0
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Choose Host,,0
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Hollywood,,0
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,The Cultural Revolution,,0
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_GLASS] Glass,-4
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_OLIVE] Olives,-4
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Ban Luxury,[ICON_RES_SUGAR] Sugar,-4
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Lhasa,-4
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Global Liberation,,-24
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Sphere of Influence,Byblos,-34
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,World Science Initiative,,-64
344, 1974,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Sphere of Influence,,-184
344, 1974,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Sphere of Influence,,-184
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Milan,-250
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Scholars In Residence,,-384
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Sofia,-450
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Lhasa,-600
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Sydney,-636
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,Persia,-794
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,The Huns,-794
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,The Shoshone,-794
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Decolonization,Assyria,-794
344, 1974,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Historical Landmarks,,-834
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Byblos,-1006
344, 1974,Spain,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Hanoi,-1384
344, 1974,Spain,- - -,Evaluating for Proposal, REPEAL, POST SORT,Travel Ban,,-1714

**Comment by LoneGazebo** [comment]
Is someone else closer to a tourism victory than Spain? That's the biggest reason why the AI would vote in favor of it (even if it defies their grand strategy choice).

**Comment by ilteroi** [comment]
not really. but their current strategy is diplomatic victory, so apparently they sided with the people who want to stop their tourism. kinda makes sense i guess.

**Comment by LoneGazebo** [comment]
Yeah - that explains why they want it - they're probably right on the edge between the two grand strategies and just happened to realign for that vote.
