### ISSUE TITLE
Trade bug

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#3751]
12-6-1 latest version.

Really Advanced Setup & Vox Populi with EUI

Got multiple trade deals with William. Look at "current deals" on the far right. They're all for my Copper. Not sure how this could be replicated. If I need to upload my save or anything else I'll be happy to.

![image](https://user-images.githubusercontent.com/8049731/33901031-68171ed6-df68-11e7-95af-be279169e617.png)

**Comment by pandasnail** [comment]
The Dutch UA allows that now. Trade too many and he'll steal your monopoly bonus from you too.
