### ISSUE TITLE
Buildings.IsNoWater blocks also Rivers (despite the fact that there is IsNoRiver with that purpose)

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3752]
_1. Mod version (i.e Date - 4/23):12-6-1
_2. Mod list (if using Vox Populi only, leave blank):_
_3. Error description:_ 
VP adds to Buildings two conditions: IsNoWater and IsNoRiver. I assumed that these work as opposites to IsWater and IsRiver.
I needed a unique condition for a mod, so I did some testing.
IsNoWater blocks build if there is Water (sea or lake) - this is ok. It also blocks if there is a River - which is not ok, I suppose? If I want to block access to River,  would use IsNoRiver. 
Anyway, currently you cannot create a condition that says: city is not near a chunk of water (sea, lake). 
_4. Steps to reproduce (optional):_
Create a simple building with that flag, settle a 2 cities inside the land (not coastal), both with no lake. One with River and one with no River. That building can be built only in the second city. It means that River is interfering somehow.

---------------------------

**Comment by ilteroi** [comment]
there seems to be some name confusion here,

* IsNoWater is actually treated as the opposite of IsFreshWater. 
* freshwater access is defined as adjacent to river, lake or oasis, so river tiles are a subset of freshwater tiles. 
* IsWater means adjacent to ocean, aka coastal. 
* there is no "IsNoFreshWater" flag.

so i don't know how to handle this.

**Comment by Infixo** [comment]
IsWater is also for Lakes, with MinAreaSize=1. That is why I thought IsNoWater means "no access to area water". Had to idea that is has to do anything with IsFreshWater, very confusing. Solution?
IsNoRiver / IsNoFreshWater / IsNoWater, all being a negative of a respective Is...

**Comment by ilteroi** [comment]
well, isNoLake would be (isWater(min ocean size) and not isWater(1)) or not isWater(min ocean size)

ugly but true

otherwise, for backward compatibility we can't redefine isNoWater, so i'm loath to change anything here

**Comment by Infixo** [comment]
Those flags I'm talking about are for fields in Buildings table, not Lua calls. In DB there is only one MinAreaSize, so you can't do a lake :(
And yeah, I've implemented Lake conditon via Lua using ( pCity:IsCoastal(1) and not pCity:IsCoastal(10) )
