### ISSUE TITLE
FYI - Deleted some old remote branches and check in

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#3753]
Hi,

This is an FYI - I deleted my old remote branches corp-dev and C4DF-dev as they've been merged and are unnecessary clutter to your repository.

If I recall correctly (it's been a while since I've contributed to this project) you use GitHub issues for all development related discussion for CPP? There wouldn't be another forum for this, correct?

Anyway, I thought it would be good to check-in and wonder if there are any requests for C4DF or other stuff I could take a look at while I'm on vacation.

Thanks,
Putmalk

**Comment by LoneGazebo** [comment]
Hey there! We still use civfanatics for 99% of discussion - the Issues tab is just for bug reports and feature requests.

https://forums.civfanatics.com/forums/community-patch-project.497/

I don't know of any current requests, but you might make a post there. Be prepared for a deluge of requests, though. :)

G

**Comment by mwhiter** [comment]
Cool, done! Will close this then! :)
