### ISSUE TITLE
Ability to tax Strategic Resources from vassals

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#3755]
[Users Tarzan737 and Infixo](https://forums.civfanatics.com/threads/any-requests-for-development.625480/#post-14947256) have suggested the ability to tax strategic resources from Vassals. I will review and design a proposal for how this might work.

**Comment by RecursiveVision** [comment]
Well, I don't think this is happening anytime soon.

If Putmalk returns one day he can reopen this!
