### ISSUE TITLE
Can Liberate Vassals after 10 turns even though the prerequisite is 50 turns

### ISSUE THREAD

**Issue by mwhiter** [LoneGazebo/Community-Patch-DLL#3756]
In the Diplomacy UI, you can liberate your vassals after 10 turns, although it should be after 50 turns of vassalage. This case was discovered with Voluntary Vassalage.

**Comment by LessRekkless** [comment]
You can also liberate your own vassal after 10 turns in the Vassals UI. I thought this was a feature, not a bug.  Is there a reason these two cases should be different? The 50 turn minimum is for the vassal to declare independence, not to voluntarily be let go by the master.
