### ISSUE TITLE
AI production choice, again

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3760]
so this is india at turn 74, with one city when others have four.

![image](https://user-images.githubusercontent.com/1358966/34071776-1fd6e6da-e27c-11e7-9993-8424ded7a3e9.png)

the two settlers are waiting for their escorts, while the spearman&archer are waiting for a third unit to complete an anti-barbarian team.

meanwhile the city is merrily building other stuff. this is what they did so far:

000, India, Delhi, SEED: 12795250227130703892, CHOSEN: Market, Do not rush, TURNS: 10
007, India, Delhi, SEED: 8930644698101204513, CHOSEN: Chariot Archer, Do not rush, TURNS: 4
011, India, Delhi, SEED: 10587675235756860787, CHOSEN: Stonehenge, Do not rush, TURNS: 11
012, India, Delhi, SEED: 9812328816688218464, CHOSEN: Walls, Do not rush, TURNS: 7
016, India, Delhi, SEED: 17995677248762912710, CHOSEN: Shrine, Do not rush, TURNS: 2
018, India, Delhi, SEED: 16064415611980090975, CHOSEN: Horseman, Do not rush, TURNS: 7 --> became a scout
025, India, Delhi, SEED: 4420604857288370080, CHOSEN: Spearman, Do not rush, TURNS: 12 --> last unit build
032, India, Delhi, SEED: 13617729150927684457, CHOSEN: Arena, Do not rush, TURNS: 15
049, India, Delhi, SEED: 12993588110029169077, CHOSEN: Settler, Do not rush, TURNS: 9 --> waiting for 26 turns now
056, India, Delhi, SEED: 18227653832988598592, CHOSEN: Caravan, Do not rush, TURNS: 5
062, India, Delhi, SEED: 281600032637733165, CHOSEN: Caravan, Do not rush, TURNS: 5
063, India, Delhi, SEED: 12360152730771528718, CHOSEN: Settler, Do not rush, TURNS: 8
069, India, Delhi, SEED: 16700025668288692500, CHOSEN: Baths, Do not rush, TURNS: 5

note that this isn't bad luck with the RNG, the escorts get filtered out in POST!

example:

063, India, Delhi, PRE: Unit, Settler, 12100, 8
063, India, Delhi, PRE: Operation unit, Spearman, 6366, 5
063, India, Delhi, PRE: Building, Granary, 4877, 4
063, India, Delhi, PRE: Building, Council, 4200, 4
063, India, Delhi, PRE: Building, Water Mill, 2420, 10
063, India, Delhi, PRE: Building, Herbalist, 1500, 7
063, India, Delhi, PRE: Building, Forge, 1290, 10
063, India, Delhi, PRE: Building, Barracks, 640, 7
063, India, Delhi, PRE: Building, Monument, 570, 4
063, India, Delhi, PRE: Building, Roman Forum, 355, 16
063, India, Delhi, PRE: Process, Farming, 320, 1
063, India, Delhi, PRE: Unit, Catapult, 132, 7
063, India, Delhi, PRE: Building, Pyramids, 125, 14
063, India, Delhi, PRE: Unit, Spearman, 116, 5
063, India, Delhi, PRE: Process, Defense, 100, 1
063, India, Delhi, PRE: Unit, Archer, 51, 4
063, India, Delhi, POST: Unit, Settler, 126624, 8
063, India, Delhi, POST: Building, Forge, 6884, 10
063, India, Delhi, POST: Building, Barracks, 6871, 7
063, India, Delhi, POST: Building, Water Mill, 6127, 10
063, India, Delhi, POST: Building, Granary, 2858, 4
063, India, Delhi, POST: Building, Council, 2120, 4
063, India, Delhi, POST: Building, Herbalist, 1632, 7
063, India, Delhi, POST: Building, Roman Forum, 901, 16
063, India, Delhi, POST: Building, Pyramids, 696, 14
063, India, Delhi, POST: Process, Farming, 326, 1
063, India, Delhi, POST: Process, Defense, 102, 1
063, India, Delhi, SEED: 12360152730771528718, CHOSEN: Settler, Do not rush, TURNS: 8

further ideas:
- increase the priority for promised units?
- de-emphasize the second settler when another settling operation is in recruiting phase

**Comment by LoneGazebo** [comment]
The emphasis is already pretty high for promised units- was the civ in negative GPT?

**Comment by ilteroi** [comment]
i don't know but building a bath is also a money loser ...

**Comment by ilteroi** [comment]
ok, turns out they were at the supply limit, leading to a negative score. i turned it into a soft limit: start clamping down at +3 supply and reach zero at -3 supply.

**Comment by LoneGazebo** [comment]
Ah. Yeah that’ll do it.
