### ISSUE TITLE
test build for AI (15/12)

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3761]
two main changes here, i'd like to get this out for people to test before christmas

- AI doesn't give up cities in peace deals so easily. there was a bug/feature where they would always (after warscore passed a threshold) give you at least one city, no matter how good it is. so in early wars you could really abuse them. now they check the value.
- AI would occasionally send units on suicide plunder missions when enemies are around

bugfixes:
- no distance scaling for internal trade routes
- no AI bonuses for founding the capital
- AI still building units even if close to the supply limit

the dll simply replaces the one in the mods/community patch folder. compatible with 15/12 version.

regular build:
[CvGameCore_Expansion2-release-20171215.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1574760/CvGameCore_Expansion2-release-20171215.zip)

43 civ version:
[CvGameCore_Expansion2-release43-20171215.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1576769/CvGameCore_Expansion2-release43-20171215.zip)

feedback welcome, especially on the peace deal behavior, but also on any other tactical AI quirks.

**Comment by LoneGazebo** [comment]
I’ve already left on holiday, unfortunately. If you want, make a 43civ and a non-43civ DLL and post them on the forum, feel free. Make sure you merged with my 12-15 from yesterday, however.

**Comment by ilteroi** [comment]
it's merged, no worries

**Comment by bigcat88** [comment]
Another compiler? Or debug version? Size is bigger by 2mb(4->6)

**Comment by ilteroi** [comment]
some more experiments. guided missiles cannot attack cities, only units, but also when they are "hiding" in a city. missiles can also kill civilians with a single hit.

[CvGameCore_Expansion2-regular.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1584480/CvGameCore_Expansion2-regular.zip)
[CvGameCore_Expansion2-43civ.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1584481/CvGameCore_Expansion2-43civ.zip)

the combat preview is not updated yet ... i hate lua.

**Comment by LoneGazebo** [comment]
>missiles can also kill civilians with a single hit.
🤕
