### ISSUE TITLE
Stealing Settlers on DoW spawns additional Workers.

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#3762]
_1. Mod version (i.e Date - 4/23):_
December 1st, 2017

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Declaring War on an opponent while one of your units is on a settler (don't know if it happens with workers), allows you to immediately return the unit to the opponent.

Frequently, this causes additional workers to spawn under your control. The result is that your opponent gets his settler (converted into a worker) back, and you also get an additional worker (with the prisoner of war promotion). In my most recent game, I received three of them!

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Pacal_0154 BC-0290.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1566153/Pacal_0154.BC-0290.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20171216215107_1](https://user-images.githubusercontent.com/34615525/34076678-8aed8850-e2ab-11e7-9c77-9a1f284a27ae.jpg)

**Comment by ilteroi** [comment]
reproduced but no additional workers in my case.

also hard to debug, can't find how the civilian return popup is triggered ...

**Comment by LoneGazebo** [comment]
@ilteroi find setcapturingplayer (i think that’s it) in CvUnit and follow it around. There’s a function that takes human input that calls setcapturingplayer.

**Comment by LoneGazebo** [comment]
My guess is that the captured unit, after being returned, isn’t successfully jumping to an adjacent tile, so the game triggers a theft multiple times.

**Comment by ilteroi** [comment]
well that's the thing, war is declared, the captured unit is created and control passes back to the UI.

only then there's the "captured civilian" popup and a call to ResponseReturnCivilian(). callstack doesn't even contain lua. so i'm not sure whether it's even possible to fix this.

i've got no explanation why additional workers would spawn.

**Comment by LessRekkless** [comment]
I went back to reproduce what happened in the screenshot I attached.  Here's the save file:
[Pacal_0154 BC-0290.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1566150/Pacal_0154.BC-0290.zip)

You shouldn't need to do anything but end the turn and let the settler walk on top of the horseman near Uxmal, make a DoW on Carthage on turn 155, and return the unit after capture.
