### ISSUE TITLE
City-State Trade Historic events don't trigger

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3764]
_1. Mod version (i.e Date - 4/23): 12-15
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:
Well, as the title says - they don't seem to trigger at all. I've checked the log and found out that just by chance. 171 events, 60 turns, 16 land/sea TR events, and no CS events. CS trade was NOT banned and my Civ had a route open with one CS all that time.
Possible cause. I was looking through code (for some other reasons) and found this in CvTradeClassess.cpp:
if(GET_PLAYER(pDestCity->getOwner()).isMinorCiv() && GET_PLAYER(pOriginCity->getOwner()).GetEventTourismCS() > 0)
I think that GetEventTourismCS() always return 0, because I haven't found any code to change that value from initial 0.

**Comment by LoneGazebo** [comment]
It isn’t supposed to trigger. Happens too often.

**Comment by LoneGazebo** [comment]
It changes from policies anyways.
