### ISSUE TITLE
Custom Tutorial System

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3765]
I'm not sure if this is something you'd be interested in, but I've hacked into the vanilla Tutorial system so that JFDLC can be better explained to new users. It uses a database system to create the Tutorial information, but a custom LuaEvent to trigger them.

I figure it might be something of use to the CBO, and if so, you're welcome to use or integrate it. I'm still working out the kinks, but if this is something you'd like, I'll pass it over once I'm sure it's ready.

![screen](https://i.imgur.com/r21wpA7.jpg)

**Comment by LoneGazebo** [comment]
That’s really cool. Yeah, once you’ve got it working send that my way!

**Comment by bklick** [comment]
Oh, this is so nice.

**Comment by JFDaly** [comment]
Yeah, sorry for the delay. I've gutted JFDLC and been rewriting it from the ground up, to improve performance and such, so it'll be a bit before its up and running.
