### ISSUE TITLE
Barrage/Accuracy effect swapped?

### ISSUE THREAD

**Issue by Udutont** [LoneGazebo/Community-Patch-DLL#3766]
1. Mod version 12-15

2. Mod list: Remove ghost routes v2, Commander Influence Borders v2

3. Error description: Accuracy and/or Barrage promotions are not working properly. Barrage is stronger than Accuracy against units above 50 HP and vice versa. See the screenshots.
[Error.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1576648/Error.zip)

**Comment by Infixo** [comment]
I did some code browsing while discussing this on forum. Finally got into CvUnit::GetMaxRangedCombatStrength() function, which is supposed to modify RCS according to promotions and defender. It accounts for Kamikaze, EmpireUnhappy, StratResPenalty, near GG, improvements, anti-unit class promos, anti-unit combat promos, domain modifier, wounded, fortified, anti-minor, and terrain situation. There is nothing about a unit being below or above 50 HP. Those promos simply aren't programmed, I think.

**Comment by Infixo** [comment]
Scratch my previous comment. The function accounts for half-HP, but the operator is wrong, so the effects are indeed swapped. I fixed that.
