### ISSUE TITLE
useless guided missiles

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3767]
india declared war on me and unleashed a barrage of guided missiles against a city of mine, but did hardly any damage:

![image](https://user-images.githubusercontent.com/1358966/34225456-de8c7890-e5c6-11e7-9ec9-7f13fe69ad44.png)

there were about 15 attacks but too many notification so i could only capture some of them.

that seems awfully little damage for their price. should we make them more powerful? 

the AI seems to love them in any case :)

**Comment by LoneGazebo** [comment]
That is pretty low, but they are specifically designed to go after units, not cities. Perhaps we should encourage that.

**Comment by ilteroi** [comment]
well, the projected damage against a battleship (34) is less than against a city (35 in my test). and against land units is less again (24 against rocket artillery).

tbh, i'd rather remove them from the game completely.

**Comment by LoneGazebo** [comment]
But those units have less health than a city. That’s 1/3 of the ship’s health.

**Comment by TechpriestEnginseer** [comment]
Why not just make Guided Missiles do reduced AoE damage(splash) within one tile? Then for cities, make it do extra damage versus garrisons.

**Comment by ilteroi** [comment]
@LoneGazebo : that's still a bad deal considering the cost of the units ... missile 1200, battleship 1800, rocket artillery 2200.

@TechpriestEnginseer : imho splash damage doesn't really fit - surgical strikes and all that.

**Comment by LoneGazebo** [comment]
I mean, we could increase their damage. That’s an easy change. 

G

**Comment by ilteroi** [comment]
or reduce the cost ... but then they will become tedious to manage for humans. anyway, i don't really see what they add to the game.

**Comment by ilteroi** [comment]
so i have just the idea. guided missiles cannot attack cities but they can hit the garrison. how about that?

**Comment by LoneGazebo** [comment]
@ilteroi if the AI gets it, sure.

**Comment by ilteroi** [comment]
they still need to be stronger but the rest is implemented
