### ISSUE TITLE
Nuke attacks don't use Intercept/Evasion mechanism

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3770]
_1. Mod version (i.e Date - 4/23): 12-15
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 
As in title. You can shoot down a plane, a missile but not Nuke. Atomic Bomb is carried by airplane and Nuclear Missile is a missile, but they are exluded from Interception/Evasion combat logic. 
Also: both Nukes have promotions (Evade I). But they are useless apparently.

Possible explanation
When attack is nuclear (getMISSION_NUKE), a special mission type is called (AttackNuclear). The core routine (GenerateNuclearCombatInfo) doesn't take into consideration any Intercept/Evasion logic, nukes always hit.
As a comparison: when Airplane (DOMAIN_AIR) moves and attacks (UnitAttackWithMove), it is considered (AttackAir) and (GenerateAirCombatInfo) is called. This routine checks for Evasion and Interception. 1st - if you evaded (probability roll), 2nd - if you were intercepted (again, 2nd roll). I suppose in older versions of the game (before Exp2) Nukes could be treated this way because they are DOMAIN_AIR as well. But now, they attack via a different action ('N') and a different logic is applied.

**Comment by LoneGazebo** [comment]
Yes they are. By design.
