### ISSUE TITLE
Can't improve resources added by Vox Populi

### ISSUE THREAD

**Issue by TheGoodHunter** [LoneGazebo/Community-Patch-DLL#3771]
_1. Mod version (i.e Date - 4/23):_
12-15

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi (with EUI)
Enlightenment Era (v6)
VP-EE Compatibility (v5)
InfoAddict (v 22)
JFD's Cultural Diversity (core) (v13)
JFD's Cultural Diversity (soundtrack)
Meaningful City State Colors (v1)
Quick Turns (v10)
R.E.D. Modpack (v 27)
Redesigned Colors and Icons V 2.0

_3. Error description:_
Resources added by "more luxuries" section of Vox Populi are unable to be improved.  Before I have calendar it says "requires calendar" and afterwards it doesn't, however the worker is still unable to make a plantation.  I've already tried deleting all of my mods, verifying game cache, reinstalling vox populi then all my mods, and seeing if it fixes it and it didn't.

Supporting information:

1. Log files: (Sorry for this - I couldn't post my log folder as a .rar and I don't know how to zip it up).
[modding.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581224/modding.log)
[net_message_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581225/net_message_debug.log)
[SteamCloud.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581226/SteamCloud.log)
[stopwatch.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581227/stopwatch.log)
[system_init.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581228/system_init.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581229/xml.log)
[xml-perf.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581230/xml-perf.log)
[achievements_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581231/achievements_debug.log)
[APP.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581232/APP.log)
[CustomMods.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581233/CustomMods.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581234/Database.log)
[init_host.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581235/init_host.log)
[Localization.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581236/Localization.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1581237/Lua.log)

4. Screenshots (optional):

![20171221204815_1](https://user-images.githubusercontent.com/34757784/34282073-f0d19420-e690-11e7-9ac2-9d9b93096318.jpg)
![20171221204906_1](https://user-images.githubusercontent.com/34757784/34282084-f95e3e54-e690-11e7-8c90-2ce823ca92b9.jpg)

**Comment by TheGoodHunter** [comment]
I'd also like to note that I've already tried deleting all of my mods and verifying cache then reinstalling all my mods.

**Comment by Infixo** [comment]
Well, I had similar problem and found out that Calendar is not enough. There is another condition, but the tooltip doesn't show it. It was some time ago, I don't remember exactly what was it. Check if they are NOT in a forest or jungle. If so, you need tech to remove trees also.

**Comment by TheGoodHunter** [comment]
Well if there is another requirement I can't figure out what it is via the internet or the civopedia in-game.  Also the resources are not in forest or jungle, they are grasslands (in the screenshots) so that rules that out.  Damn.

**Comment by MoiMagnus** [comment]
1) Have you subscribed to "More Luxuries" from STEAM. If yes, unssubscribe and reinstall VP. For some reasons, steam does not like when you have More Luxuries from STEAM and from VP both in the mod folder, even disabled...
2) Do you have this problem with only VP ? (get rid of ALL the other mods, and try without). You would be suprised of how many "simple mods" are incompatible with Vox Populi.

**Comment by TheGoodHunter** [comment]
1. No I haven't
2. I just tried doing this (as well as uninstalling and reinstalling the game for good measure) and even with only VP I can't improve the resources added by it.

**Comment by LoneGazebo** [comment]
Remove all non VP mods, see if it works. Add in other mods until it stops working. Make sure you are on .279 of civ.

**Comment by TheGoodHunter** [comment]
As I said in the previous comment, I have just tried this and it didn't work.

**Comment by MoiMagnus** [comment]
Can you upload a save and logs from a game whithout any other mods ? (and where you can't build an improvement, of course)

**Comment by TheGoodHunter** [comment]
@MoiMagnus Yes, here:


(Heyyyy I just figured out how to zip up folders and files, +10 to science skill)

The Save: [AutoSave_0020 BC-2800.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1584459/AutoSave_0020.BC-2800.zip)

The Logs:  [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1584460/Logs.zip)

**Comment by TheGoodHunter** [comment]
@MoiMagnus Absolutely, here:

(Side note: I just figured out how to zip files and folders up, woot!)

Save: [Test Game.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1584464/Test.Game.zip)

Logs: [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1584466/Logs.zip)

And for good measure, here's a couple screenshots: 
![20171223170521_1](https://user-images.githubusercontent.com/34757784/34322978-0da53e66-e804-11e7-91fa-38b38b98a841.jpg)
![20171223170537_1](https://user-images.githubusercontent.com/34757784/34322981-22d12d5e-e804-11e7-90ae-7751e21e1e21.jpg)

**Comment by Infixo** [comment]
I just want to notice that Tobacco, Tea, Coffee, Parfumes, and Olives are not listed in „Can be built on” part of tooltip.

**Comment by Infixo** [comment]
Well, I've just loaded the save file Test Game and I can build plantation. Also tooltip lists all possible resources in that "Can Be Built On" section. The logs files are incomplete - your DB doesn't check constraints (*** SKIPPING Game Database Validation. ****). The only problem I see is that you have a ton of "insert into ArtDefine_StrategicView" errors that come from game's DLCs and Expansions. There shouldn't be any.
