### ISSUE TITLE
Barbarian Worker got Prisoners promotion, Barbarian Settler didn't

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#3772]
_1. Mod version (i.e Date - 4/23):_regular 12/15, not ilteroi's version

_2. Mod list (if using Vox Populi only, leave blank):_
Full EUI VP
Randomize City Names, Celtic City Names, Iroquian City Names
Civ Linked Great Generals, Great People Pack. Great Prophet Historical Names, More Great Musicians, More Great Works
Favorite Religion Randomizer, Historical Religions
Flag Promotions
My own thing, which these days only removes the barb xp cap and renames some City States

_3. Error description:_ 
I would imagine it should be the same for both, either way. 

(Neither belonged to me originally)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Only happens if the unit you capture was originally a worker.

**Comment by pandasnail** [comment]
Oh, didn't realize all settlers were immune, guess I haven't captured one straight from an AI since yet. Okay.

**Comment by pandasnail** [comment]
Now I'm more confused, maybe I misunderstood you because while I don't have the precapture shot to prove it, this worker was a Chinese Settler. This game is with the Ilteroi changes fwiw.

![screenshot 1](https://user-images.githubusercontent.com/16260521/34310152-c04a2220-e723-11e7-8a56-d848f0887437.png)

**Comment by LoneGazebo** [comment]
You only get the POW worker right now if it was a worker you captured. I can change that later.
