### ISSUE TITLE
GetTradeRouteRange()

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3773]
_1. Mod version (i.e Date - 4/23): 12-15
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 
CvPlayerTrade::GetTradeRouteRange() has 2 possible problems.

1. Policy range change not included:
```
	case DOMAIN_LAND:
	iTraitRange = m_pPlayer->GetPlayerTraits()->GetLandTradeRouteRangeBonus();
#if defined(MOD_BALANCE_CORE)
	m_pPlayer->getTradeRouteLandDistanceModifier();
#endif
```
Well, that m_pPlayer->getTradeRouteLandDistanceModifier(); just don't do anything. This cannot be tested as of now because no policy uses those modifiers.

2. Caravansaries and Harbors range change not accounted for
```
	iRange = iBaseRange;
	iRange += iTraitRange;
	iRange += iExtendedRange;
#if defined(MOD_TRADE_ROUTE_SCALING)
	iRange = (iRange * iRouteModifier) / 100;
#endif
	iRange = (iRange * (100 + iRangeModifier)) / 100;
	return iRange;
```
Caravansaries and Harbors are handled via iRangeModifier which is excluded from the code now.

As for now this function only accounts for Technology distance changes, player Traits and world size scaling.

**Comment by ilteroi** [comment]
i think i fixed that, but since you seem to know your way around the code, what's stopping you from creating a patch and a pull request?

**Comment by Infixo** [comment]
I have years of experience in software development, so I can read code easily. But tinkering with it, especially with parts changed by others, without any documentation or knowing the intention behind some changes is a whole different story.

**Comment by ilteroi** [comment]
well, everybody has to start somewhere ... contributions are welcome. in the end we're all just messing around with other people's code.

**Comment by Yozarian22** [comment]
Is this what's causing Caravansary to drop all your trade route yields to 1?

**Comment by Infixo** [comment]
@Yozarian22 I don’t think so. This just breaks Caravansaries’ and Harbors’ ability to make longer trade routes. But all routes that are within range should behave normally. Maybe open new issue and attach a savegame with logs.
