### ISSUE TITLE
diplo AI bug?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3775]
in the current game, two AI civs are at war, nevertheless

m_pPlayer->GetDiplomacyAI()->GetMajorCivOpinion(ePlayer)

returns MAJOR_CIV_OPINION_FRIEND

should this be possible?

**Comment by LoneGazebo** [comment]
Is ‘real feelings’ an optional bool?

**Comment by ilteroi** [comment]
eh? never heard of that, never touched that.

**Comment by LoneGazebo** [comment]
Civs have a real versus fake opinion based on whether or not they’re being deceptive.

**Comment by ilteroi** [comment]
if you mean GetMajorCivOpinion() then no, it doesn't have any optional parameters ...

**Comment by LoneGazebo** [comment]
Weird. May have been a defensive pact ‘I don’t want to kill you but I must’ situation.
