### ISSUE TITLE
Building_YieldPerXTerrainTimes100

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#3777]
G,

The coretableadditions.xml suggests Building_YieldPerXTerrainTimes100 functions based off the number of tiles within working radius, but it seems to actually function like the belief_ version, i.e. the tiles must in fact be worked by the city.

If it is going to stay this way, could you make terrain_snow function like terrain_mountain, and not have to be worked to gain the effect? (like the observatory)

Thanks in advance.

**Comment by Hokath** [comment]
Which change did you go for in the end?

**Comment by LoneGazebo** [comment]
Works like mountains. Test and let me know.

**Comment by Hokath** [comment]
snow now behaves as mountains and everything else is as it was, can confirm
