### ISSUE TITLE
GetTradeRoutesAvailable() does not list an active TR

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3779]
_1. Mod version (i.e Date - 4/23): 12-15
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 
As in the title. 
_4. Steps to reproduce (optional):_
Load attached save file.
[Oda Nobunaga_0273 AD-1806.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1588032/Oda.Nobunaga_0273.AD-1806.zip)
I have an active TR from Satsuma to Jeonju. It is listed correctly when using GetTradeRoutes() but NOT when using GetTradeRoutesAvailable().
Check in Firetuner:
```
> for i,v in pairs(Players[0]:GetTradeRoutesAvailable()) do if v.FromCityName=="Satsuma" and v.FromID ~= v.ToID then print(v.FromCityName,v.ToCityName) end end
 InGame: Satsuma	Antioch
 InGame: Satsuma	Varna
 InGame: Satsuma	Edzna
 InGame: Satsuma	El Mirador
 InGame: Satsuma	Huamanga
 InGame: Satsuma	Vilcabamba
 InGame: Satsuma	Andahuaylas
 InGame: Satsuma	Kaesong
 InGame: Satsuma	Copan
 InGame: Satsuma	Lamanai
 InGame: Satsuma	Uaxactun
 InGame: Satsuma	Bogota
 InGame: Satsuma	Cape Town
 InGame: Satsuma	Jerusalem
 InGame: Satsuma	Malacca
 InGame: Satsuma	Malacca
 InGame: Satsuma	Sydney
> for i,v in pairs(Players[0]:GetTradeRoutes()) do if v.FromCityName=="Satsuma" and v.FromID ~= v.ToID then print(v.FromCityName,v.ToCityName) end end
 InGame: Satsuma	Jeonju
 InGame: Satsuma	Huamanga
 InGame: Satsuma	Andahuaylas
```

**Comment by LoneGazebo** [comment]
Available means possible - an existing trade route is not possible.

**Comment by Infixo** [comment]
Nope. The page Trade Routes Available that uses this function lists all TRs, together with active ones. It’s always been like this. There’s even a column that shows how many turns is left to finish a TR if it’s active one. Also, those other 2 active TRs are correctly listed.
Jeonju route is the only one that is not listed.

**Comment by TechpriestEnginseer** [comment]
So, what's exactly the issue?

````
function RefreshYourTR()
	local pPlayer = Players[ Game.GetActivePlayer() ];
    
    --print("RefreshYourTR");
	SetData(pPlayer:GetTradeRoutes());
	SortData();
	DisplayData();
	
end
g_Tabs["YourTR"].RefreshContent = RefreshYourTR;

function RefreshAvailableTR()
	local pPlayer = Players[ Game.GetActivePlayer() ];

    SetData(pPlayer:GetTradeRoutesAvailable());
	SortData();
	DisplayData();
end
g_Tabs["AvailableTR"].RefreshContent = RefreshAvailableTR;
````
Looks fine to me.

> Also, those other 2 active TRs are correctly listed.
Also could mean that Satsuma -> Huamanga/Andahuaylas can be connected via naval or land trade routes.

**Comment by Infixo** [comment]
Tere is no bug in UI lua script, i am talking about DLL function.
Issue is that Jeonju route is not listed. 2 active routes are listed, but not Jeonju. All routes are Sea, except for Malacca. Malacca has both types and is listed correctly twice. I, Japan, am on big island only with Malacca. 
Also, another strange thing I noticed, is that this is the only route for which distance (length) cannot be calculated. I mean, the function returns -1 or nil, cant remember now.

**Comment by Infixo** [comment]
Ok, I think I know the explanation for this situation.
It seems that AStar PathFinder considers plots that are dangerous to be more costly for a unit to cross. That way I suppose it can find ways that bypass some dangerous places. But once the path is established as valid, that higher cost is considered a route Length, despite the fact that its actual Length is lower.
In my case I had 2 active routes from Satsuma that went through Harald's territory - to Huamanga (length 38) and Jeonju (length 44). Few turns later Harald DoWed me and this route to Huamanga is now 43 length, but it is still within Satsuma's range which is 45. Notice however that this route _still goes through the same tiles as previously_, the game just considers it _longer_. I think route to Jeonju is now ~50 length and this is more than 45 range, hence it is considered as not-valid and not listed.
To compare: the 3rd route, to Andahuaylas, was not going through any hostile territory and its Length remained the same (38).
