### ISSUE TITLE
Tiles not staying locked down

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#378]
This issue is definitely new to the 6/29 version for me. Using CPP bundle, no additional mods.

Tiles are not staying locked. What's interesting is the tile that becomes unlocked depends on the focus the city is set to.

![2015-06-30_00005](https://cloud.githubusercontent.com/assets/11132095/8427855/34a70fde-1ee0-11e5-95d2-e7443c47c373.jpg)
![2015-06-30_00004](https://cloud.githubusercontent.com/assets/11132095/8427854/34a22bae-1ee0-11e5-9e62-27265e79a31f.jpg)
![2015-06-30_00006](https://cloud.githubusercontent.com/assets/11132095/8427856/34a7b330-1ee0-11e5-9e4b-ec38e268b493.jpg)
![2015-06-30_00007](https://cloud.githubusercontent.com/assets/11132095/8427857/34b0f3e6-1ee0-11e5-931e-df7c72471307.jpg)

I've noticed it in situations other than those demonstrated in the screenshots (usually after improving a tile).

**Comment by LoneGazebo** [comment]
Hmm. There's a function in the DLL that removes forced working plots, but only if there are more forced plots in the city than there are citizens. It's only called from LUA as well, so it sounds like it might be a LUA issue (somehow).
G
