### ISSUE TITLE
Never Ending Social Policies. Yay? No!

### ISSUE THREAD

**Issue by FNDIII** [LoneGazebo/Community-Patch-DLL#3780]
_1. Mod version (i.e Date - 4/23):_

Newest version

_2. Mod list (if using Vox Populi only, leave blank):_

Vox Populi, JFD Cultural Diversity/Soundtrack

_3. Error description:_ 

I loaded up my game and it was working fine until randomly I was told to pick a social policy, not sure if I had enough culture points to buy it but if I reload the game to a previous year where I definitely do not have enough culture points it still makes me pick one, and then let's me proceed to keep picking social policies to unlock and doesn't let me hit next turn.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Replicate without JFD's mod?

**Comment by FNDIII** [comment]
Do you mean load the game with only Vox Populi enabled?

**Comment by MoiMagnus** [comment]
Have you logging enabled, or a save from before the bug ?

**Comment by FNDIII** [comment]
I didn't have it enabled prior to starting this game. I have the save game file but every time I load it the same issue happens.
