### ISSUE TITLE
HandicapInfos.BarbarianBonus

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3781]
_1. Mod version (i.e Date - 4/23): 12-15
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:
I ran in ~~Firefox~~Firetuner this:
`for h in GameInfo.HandicapInfos() do print(h.Type,h.BarbarianBonus,h.AIBarbarianBonus) end`
and got results:
```
 InGame: HANDICAP_SETTLER	70	75
 InGame: HANDICAP_CHIEFTAIN	60	70
 InGame: HANDICAP_WARLORD	50	60
 InGame: HANDICAP_PRINCE	40	60
 InGame: HANDICAP_KING	30	60
 InGame: HANDICAP_EMPEROR	20	60
 InGame: HANDICAP_IMMORTAL	10	60
 InGame: HANDICAP_DEITY	0	60
 InGame: HANDICAP_AI_DEFAULT	40	60
```
The values in DB are DIFFERENT. E.g. for Prince it is 30 and 40, for Deity 0 and 70. The values listed are actually the vanila ones. Am I missing something here?
BTW, this messes up Combat Preview (at least against Barbarians). E.g. for Prince Lua shows +40% bonus, but the strength is calculated correctly as +30% by DLL.

**Comment by Mitchsp** [comment]
Yes, I noticed this time ago and thought it was my local problem, so I changed
\Sid Meier's Civilization V\Assets\DLC\Expansion2\Gameplay\XML\GameInfo\CIV5HandicapInfos.xml to mirror VP values.

**Comment by Infixo** [comment]
Geeez, I thought I was going crazy when I’d noticed that. I’ve been working with DB and mods for some time and this is the first. Is it common then?

**Comment by Infixo** [comment]
This problem is related to how game caches DB tables. It affects tables used for the game setup screen:
Worlds, HandicapInfos, and GameSpeeds. I found this post from [Thalassicus](https://forums.civfanatics.com/threads/lua-not-accessing-modded-database.503661/#post-12674277)
It also gives a workaround for it.

**Comment by LoneGazebo** [comment]
For database lookups use an sql browser. There’s one for Firefox that works well. Make sure you browse the DEBUG database not the main one, as the debug one is what the game reads from with mods.

**Comment by Infixo** [comment]
The database is perfectly fine. Issue is about Lua reading wrong values from not-updated memory cache for specific tables.

**Comment by Infixo** [comment]
Oh, I’ve just noticed that I wrote Firefox in 1st post. I meant Firetuner... Now I get that answer about using Firefox... I use SQLiteStudio, btw.
