### ISSUE TITLE
Lancer doesn't match its Civipedia Information

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#3785]
_1. Mod version (i.e Date - 4/23):_
December 1, 2017

_2. Mod list (if using Vox Populi only, leave blank):_
<>

_3. Error description:_ 
Civilopedia Game Info:
"Mounted Unit specialized in defeating enemy Mounted Units"
Strategy:
"The Lancer is the Renaissance horse until that comes between the Knight and the first mechanized vehicle, the Landship. It is faster and more powerful than the Knight, able to sweep the once-might units from the map. The Lancer is a strictly offensive weapon; it gets a combat penalty when defending."

While the Lancer does upgrade to the Landship, the other information is incorrect as the Lancer is just a Knight with +10 CS.

_4. Steps to reproduce (optional):_
Open the Civilopedia, compare to unit in game.

**Comment by TechpriestEnginseer** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/pull/3795
