### ISSUE TITLE
Inconsistencies in Unit Promotions

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3787]
_1. Mod version (i.e Date - 4/23):12-15
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 
There are several inconsistencies between promotion Description (help text) and actual DB values. Nothing game breaking, just very confusing when trying to understand Combat Preview info.
I will list them in the format: promotion: help text => DB value. *none* means that help doesn't say about a feature that is in DB

-- melee
Ambush I & II: +25% armor, +10 rough => +33% armor, +15% rough [fixed]
Bonus vs Gun (25): +20% vs gun => +25% vs gun [fixed]
Formation I & II: +25% vs mounted => +33% vs mounted [fixed]
SpearThrow: *none* => +25% vs gun [fixed]
Withering Fire: 20% chance => 25% chance [fixed]
-- ranged
Accuracy I, II & III: +5% rcs => +10% rcs [fixed]
Coup de Grace => *none* => max 1 range? adjacent? [OK]
Covering Fire I: -50% vs armor => -25% vs armor [fixed]
Covering Fire II: +15% defense => +10% defense [fixed]
Parthian Tactics: *none* => max 1 range? adjacent? [OK]
Range: *none* => does -20% apply only to long shots? 2 min range? [OK]
Ranged Support Fire: *no idea what it does based on description* [OK uses same flag as Impi - ranged attack before melee attack]
-- naval
Astronomy Needed: Navigation => Compass [fixed]
Bonus vs Naval: *doesn't say how much* => 50% [fixed]
Bonus vs Submarines (75): 75 => 75 strength BUT 100 attack [fixed]
Extra Sight While Embarked: *doesn't say how much is "further"* => +2 range [OK, vanilla unchanged]
Prize Rules: gets gold => no DB flag/value for that? [OK]
Supply: heal 15 => heal 5 [fixed]
-- scouting
Flag Bearers: bonus => no DB flag/value for that? [OK]
-- air
Air Ambush I & II: *none* => +33% vs armor [fixed]
Air Repair: -10% defense => no DB value for that [fixed]
Bonus vs Fighters (33): fighters => Jet Fighter not included [fixed]
Bonus vs Helicopters (150): bonus => no DB values for any bonus [NOT USED]
Evasion(100): it is actually Evasion(80) [fixed]
Flak Targeting I & II: vs air units => missiles are DOMAIN_AIR, not included [fixed]
Logistics (air): -30% RCS => *none* [fixed]
Repair: -10% defense => *none* [fixed]
--- shared
Embarkation With Ocean Movement: +1 sight => +2 sight [fixed]
Hovering Unit: can move over / *none* => *none* / +100% defense when embarked [fixed]
Imperial Seal: *none* =>+1 move [fixed]
Indirect Fire: *none* => long shots? min 2 range? [OK]
Master Diplomat: *none* => +2 move [fixed]
Morale: *there 2 promos with this name, and they have overlapping Combat Types assigned* [OK, PROMOTION_MORALE_EVENT is a copy of PROMOTION_MORALE]
-- attributes
Bonus vs Cities(200): it is actually +100% [fixed]
Bonus vs Cities(300): it is actually +150% [fixed]
Coercion: *none* => insta heal [fixed]
Fallout Immunity: doesn't say how much damage is ignored [OK, depends on Feature]
Golden Age from Victories: doesn't say how much GAP is earned [fixed]
Heals at double rate: confusing, it heals +10 HP always [OK, vanilla unchanged]
Hill Walkers: double movement on hills => not granted [fixed]
Longboat: *none* => +25% cs on pillageg [fixed]
Naval Leadership: *none* => +1 move [fixed]
Raider: +100% flank => +200% flank [fixed]
War Canoes: see further => doesn't say how much [OK, vanilla unchanged]

I can correct them, but I need to know which version (help/DB) is the right one. Also, in *none* situation, I need to know if DB feature should be removed or text modified to match DB.

**Comment by LoneGazebo** [comment]
Whew. That's a lot of inconsistencies. In all cases, the database is king.

**Comment by Infixo** [comment]
That is actually even better, I will only correct text then.

**Comment by MoiMagnus** [comment]
@LoneGabezo
Some of them are quite weird (bonus against richer does not works against jet fighter, ...)  So I think the data base is not always correct and we just found a collection of bugs.

**Comment by Infixo** [comment]
Same with Bonus vs Helicopters (150) and Flak Targeting.

**Comment by LoneGazebo** [comment]
Any that you find that just plain don't work set aside and we can fix those later. Keep in mind that quite a few promotions are actually unused.

**Comment by Infixo** [comment]
Questions.
----------
Formation I & II: +25% vs mounted => +33% vs mounted
It is applied to 2 combat mods, with different %. Mounted +33, armored +25. Text says both +25.
----------
Coercion: none => insta heal
Is it really supposed to Insta Heal 50 HP?
----------
Coup de Grace => none => max 1 range? adjacent?
Parthian Tactics: none => max 1 range? adjacent?
Those two have MaximumRangeRequired=1. I don't know what it does.
----------
Range: none => does -20% apply only to long shots? 2 min range? [?????]
Indirect Fire: none => long shots? min 2 range? [?????]
Those two have MinimumRangeRequired=2. Does it mean that this malus only applies to shots at 2 or more tiles? Shots to adjacent tiles are normal CS then?
----------
Ranged Support Fire: no idea what it does based on description
Uses same flag as Impi - ranged attack before melee attack. Seems UNUSED. Pls confirm.
----------
Prize Rules: gets gold => no DB flag/value for that?
Flag Bearers: bonus => no DB flag/value for that?
I don't know how those promos work, there's no DB value for them.

**Comment by LoneGazebo** [comment]
Formation I & II: +25% vs mounted => +33% vs mounted
It is applied to 2 combat mods, with different %. Mounted +33, armored +25. Text says both +25.

**Should both be 25**

Coercion: none => insta heal
Is it really supposed to Insta Heal 50 HP?

**No, will fix.**

Coup de Grace => none => max 1 range? adjacent?
Parthian Tactics: none => max 1 range? adjacent?
Those two have MaximumRangeRequired=1. I don't know what it does.

**Means the AOE only applies to ranged attacks.**

Range: none => does -20% apply only to long shots? 2 min range?

**No, any attack.**

Indirect Fire: none => long shots? min 2 range?

**No, any attack.**

Those two have MinimumRangeRequired=2. Does it mean that this malus only applies to shots at 2 or more tiles? Shots to adjacent tiles are normal CS then?

**Means that they can only be acquired by units with a range of 2 or more**

Ranged Support Fire: no idea what it does based on description
Uses same flag as Impi - ranged attack before melee attack. Seems UNUSED. Pls confirm.
**Is impi trigger, leave alone.**

Prize Rules: gets gold => no DB flag/value for that?
**Hardcoded**

Flag Bearers: bonus => no DB flag/value for that?
**Yes there is - it's the plot reveal promotion stuff for bandeirantes**
I don't know how those promos work, there's no DB value for them.

Morale: there 2 promos with this name, and they have overlapping Combat Types assigned [PROMOTION_MORALE_EVENT is a copy of PROMOTION_MORALE]
Seems that there is an event that grants this promotion? It may happen that units will get 2x Morale.

**Can't - one of them is for an event.**
