### ISSUE TITLE
Typo in Nebuchadnezzar's dialogue

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#3788]
_1. Mod version (i.e Date - 4/23):_
Dec. 1, 2017

_2. Mod list (if using Vox Populi only, leave blank):_
<>

_3. Error description:_ 
Upon a negotiating a good deal with Babylon:
"Very well. Not that it will help either of us in the long run  we all die, you know.Excellent. It is agreed."

Perhaps change it to:
"It is agreed. Not that it will help either of us in the long run. Death comes to us all."

_4. Steps to reproduce (optional):_
Negotiate a good deal with Babylon.

---------------------------
Supporting information:
4. Screenshots (optional):
![20171230191718_1](https://user-images.githubusercontent.com/34615525/34460350-cdfbe75e-edc8-11e7-8cc1-fa40c10cffe8.jpg)

**Comment by Infixo** [comment]
I rather read that as „Not that it will help either of us. In the long run we all die, you know.”

**Comment by LessRekkless** [comment]
Proper grammar would have your suggestion read "Not that it will help either of us. In the long run, we all die."

**Comment by LoneGazebo** [comment]
It's a vanilla dialog.
