### ISSUE TITLE
Evangelism Description unintuitive.

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#3789]
_1. Mod version (i.e Date - 4/23):_
December 1st, 2017

_2. Mod list (if using Vox Populi only, leave blank):_
<>

_3. Error description:_ 
Evangelism states "Holy City gains Science when owned Missionaries spread this Religion to Cities of other Religions based on the population of the target City."
The science gain is actually based on the number of *followers* of the Majority Religion *after* the spread action. If there is no Majority Religion, or the city gets converted to your Religion, the science gain does not trigger.
Perhaps a change to the description:
"Missionary conversion strength +25%. Holy City gains Science when owned Missionaries spread this Religion to Cities of other Religions based the number of followers of that Religion in the target City."

**Comment by TechpriestEnginseer** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/pull/3795
