### ISSUE TITLE
Still no railroad connection bonus

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#379]
![8930_2015-06-29_00009](https://cloud.githubusercontent.com/assets/1131228/8429664/625f5248-1f43-11e5-8c67-5288c3d204f8.png)

**Comment by DanteValerian** [comment]
Agreed, this is still a problem, and quite a significant one at that.

**Comment by LoneGazebo** [comment]
I didn't promise a fix for it in this version. There's still an issue for it below, so I'm closing this one. This was Ilteroi's code, so I'm leaving it to him for now.
G
