### ISSUE TITLE
Perfume monopoly bonus is missing.

### ISSUE THREAD

**Issue by AdmFischer** [LoneGazebo/Community-Patch-DLL#3790]
_1. Mod version (i.e Date - 4/23):_
Vox Populi without EUI, 12/15 hotfix obtained from [the official download page](https://forums.civfanatics.com/threads/new-hotfix-version-12-15.625537/page-17#post-14964926),

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Monopoly bonus for Perfume is missing. Not just interface message but actual in-game effects as well. I suspect the non-EUI module has something to do with this issue, but I have no proof to confirm this.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Infixo** [comment]
Could be related to #3718

**Comment by Infixo** [comment]
There are disrepancies between EUI and NonEUI version of MoreLuxuries.sql. Assuming that EUI version is the correct one, the NonEUI:
- gives to perfume 2 culture instead of 3 gold
- tea gets gold instead of culture
- perfume misses the description

As a side note: why are there changes to DB in UI parts of VP? The game should behave the same, no matter if I choose EUI or NonEUI interface.

**Comment by LoneGazebo** [comment]
@Infixo it's just a merge error on my end.

EUI/No-EUI compatibility (5) and (6) include database changes to merge in More Luxuries, C4DF and CSD. It's the safest way to guarantee last-pass updates in Civ (as the mod list dependency structure is not reliable).

**Comment by Infixo** [comment]
Hm. Lets say, ML as example. It has CP & CBO as dependencies, so it will load always after them. MoreLuxuries.sql contains only changes to new luxuries introduced by ML. From VP perspective - they are one sub-module. The only scenario (unlikely) I can imagine is that someone would like to use original ML mod and that could mess up things. But a) moving part of changes to another sub-module will not fix that b) you can easily block original ML module in .modinfo.
Anyway, not a big problem after all.

**Comment by LoneGazebo** [comment]
The blocking stuff in modbuddy doesn't work - mods are loaded in the order they're placed in the mods folder. This was discovered a long time ago.
