### ISSUE TITLE
Defense "buidling" ranged bonus can be triggered early by entering/leaving the city

### ISSUE THREAD

**Issue by Voker57** [LoneGazebo/Community-Patch-DLL#3791]
_1. Mod version (i.e Date - 4/23):_

12.15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Defense building is supposed to increase city strength and restore hitpoints. However, strength part can be triggered early by entering or leaving city with any unit, and then defense building removed again from the queue, wasting no resources.

_4. Steps to reproduce (optional):_

Set up building "defense"
leave/enter the city
watch the strength rise

**Comment by TechpriestEnginseer** [comment]
Pretty sure this is a tooltip bug. Replicate it with how an enemy attack.
