### ISSUE TITLE
another mysterious building choice

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3792]
![image](https://user-images.githubusercontent.com/1358966/34471404-0a8a6c6e-ef49-11e7-945c-55dab83ff6f5.png)

this is beautiful argos, which doesn't have a crime problem at all. nevertheless AI chose to build a constabulary instead of useful basic buildings like monument/council/well.

152, Greece, Argos, PRE: Building, Harbor, 10750, 5
152, Greece, Argos, PRE: Building, Caravansary, 8750, 3
152, Greece, Argos, PRE: Building, Council, 5950, 1
152, Greece, Argos, PRE: Unit, Caravel, 4125, 2
152, Greece, Argos, PRE: Building, Bank, 3795, 7
152, Greece, Argos, PRE: Unit, Galleass, 3580, 3
152, Greece, Argos, PRE: Building, Monument, 2450, 1
152, Greece, Argos, PRE: Building, Aqueduct, 2380, 3
152, Greece, Argos, PRE: Unit, Heavy Skirmisher, 2188, 3
152, Greece, Argos, PRE: Unit, Longswordsman, 2146, 2
152, Greece, Argos, PRE: Unit, Knight, 2142, 3
152, Greece, Argos, PRE: Unit, Hoplite, 1692, 1
152, Greece, Argos, PRE: Building, Well, 1675, 1
152, Greece, Argos, PRE: Building, Stable, 1580, 4
152, Greece, Argos, PRE: Unit, Pikeman, 1390, 2
152, Greece, Argos, PRE: Building, Granary, 1256, 1
152, Greece, Argos, PRE: Process, Arts, 1225, 1
152, Greece, Argos, PRE: Building, Armory, 1200, 4
152, Greece, Argos, PRE: Unit, Composite Bowman, 1128, 2
152, Greece, Argos, PRE: Building, Constabulary, 875, 7
152, Greece, Argos, PRE: Building, Workshop, 855, 5
152, Greece, Argos, PRE: Unit, Trebuchet, 796, 3
152, Greece, Argos, PRE: Building, Herbalist, 740, 2
152, Greece, Argos, PRE: Process, Research, 680, 1
152, Greece, Argos, PRE: Process, Wealth, 675, 1
152, Greece, Argos, PRE: Unit, Envoy, 640, 3
152, Greece, Argos, PRE: Process, Defense, 100, 1
152, Greece, Argos, PRE: Process, Farming, 85, 1
152, Greece, Argos, POST: Building, Constabulary, 10161, 7
152, Greece, Argos, POST: Building, Council, 9260, 1
152, Greece, Argos, POST: Building, Granary, 8980, 1
152, Greece, Argos, POST: Building, Well, 6437, 1
152, Greece, Argos, POST: Building, Herbalist, 5556, 2
152, Greece, Argos, POST: Building, Caravansary, 5258, 3
152, Greece, Argos, POST: Building, Aqueduct, 5226, 3
152, Greece, Argos, POST: Building, Armory, 5128, 4
152, Greece, Argos, POST: Building, Bank, 4535, 7
152, Greece, Argos, POST: Building, Stable, 4518, 4
152, Greece, Argos, POST: Unit, Envoy, 4390, 3
152, Greece, Argos, POST: Building, Harbor, 4251, 5
152, Greece, Argos, POST: Building, Workshop, 4017, 5
152, Greece, Argos, POST: Process, Arts, 976, 1
152, Greece, Argos, POST: Unit, Hoplite, 750, 1
152, Greece, Argos, POST: Unit, Caravel, 662, 2
152, Greece, Argos, POST: Unit, Longswordsman, 662, 2
152, Greece, Argos, POST: Unit, Pikeman, 662, 2
152, Greece, Argos, POST: Unit, Composite Bowman, 662, 2
152, Greece, Argos, POST: Unit, Galleass, 605, 3
152, Greece, Argos, POST: Unit, Heavy Skirmisher, 605, 3
152, Greece, Argos, POST: Unit, Knight, 605, 3
152, Greece, Argos, POST: Unit, Trebuchet, 605, 3
152, Greece, Argos, POST: Process, Research, 388, 1
152, Greece, Argos, POST: Process, Wealth, 376, 1
152, Greece, Argos, POST: Process, Farming, 79, 1
152, Greece, Argos, SEED: 4860304420559843135, CHOSEN: Constabulary, Do not rush, TURNS: 7

partly RNG dependent of course, but why does the constabulary have such a high score?

**Comment by LoneGazebo** [comment]
Did you walk through the buildingsanity function to see what's beefing it up?

G

**Comment by ilteroi** [comment]
autosaves are gone unfortunately ...

**Comment by Infixo** [comment]
Well, 1875 points might come from: Defense=500/4=125 * 15 = 1875. (IsBastion comment Coastal and we can embark across oceans? Check for lake, otherwise make a bastion (better safe than sorry)).
