### ISSUE TITLE
Pantheons: Celts always choose Nuada

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3796]
_1. Mod version (i.e Date - 4/23): 12-15
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 
I have checked the ReligionLog for Celts and I found this:

```
29 | -2840 | The Celts | Belief | Nuada | 26503
29 | -2840 | The Celts | Belief | Morrigan | 2194
29 | -2840 | The Celts | Belief | Ogma | 336
29 | -2840 | The Celts | Belief | Lugh | 324
29 | -2840 | The Celts | Belief | Rhiannon | 182
29 | -2840 | The Celts | Belief | Epona | 123
29 | -2840 | The Celts | Belief | Mannanan | 40
29 | -2840 | The Celts | Belief | Bran | 35
29 | -2840 | The Celts | Belief | Dagda | 2
29 | -2840 | The Celts | Belief | Cernunnos | 0
29 | -2840 | The Celts | CHOSEN | Nuada |  
27 | -2920 | The Celts | Belief | Nuada | 25697
27 | -2920 | The Celts | Belief | Ogma | 362
27 | -2920 | The Celts | Belief | Lugh | 325
27 | -2920 | The Celts | Belief | Rhiannon | 205
27 | -2920 | The Celts | Belief | Epona | 188
27 | -2920 | The Celts | Belief | Bran | 121
27 | -2920 | The Celts | Belief | Cernunnos | 72
27 | -2920 | The Celts | Belief | Dagda | 24
27 | -2920 | The Celts | Belief | Morrigan | 0
27 | -2920 | The Celts | Belief | Mannanan | 0
27 | -2920 | The Celts | CHOSEN | Nuada |  
29 | -2840 | The Celts | Belief | Nuada | 24817
29 | -2840 | The Celts | Belief | Ogma | 375
29 | -2840 | The Celts | Belief | Lugh | 341
29 | -2840 | The Celts | Belief | Rhiannon | 238
29 | -2840 | The Celts | Belief | Epona | 183
29 | -2840 | The Celts | Belief | Bran | 51
29 | -2840 | The Celts | Belief | Cernunnos | 30
29 | -2840 | The Celts | Belief | Dagda | 24
29 | -2840 | The Celts | Belief | Morrigan | 0
29 | -2840 | The Celts | Belief | Mannanan | 0
29 | -2840 | The Celts | CHOSEN | Nuada |  
26 | -2960 | The Celts | Belief | Nuada | 30678
26 | -2960 | The Celts | Belief | Rhiannon | 411
26 | -2960 | The Celts | Belief | Ogma | 284
26 | -2960 | The Celts | Belief | Cernunnos | 224
26 | -2960 | The Celts | Belief | Bran | 60
26 | -2960 | The Celts | Belief | Epona | 30
26 | -2960 | The Celts | Belief | Dagda | 24
26 | -2960 | The Celts | Belief | Lugh | 6
26 | -2960 | The Celts | Belief | Morrigan | 0
26 | -2960 | The Celts | Belief | Mannanan | 0
26 | -2960 | The Celts | CHOSEN | Nuada |  
```
The score for Nuada is so huge that is certainly bugged.

**Comment by Infixo** [comment]
Score for Player is huge.
TotalBeliefScoringReligionLog
029, -2840, The Celts, Belief, Morrigan, Harbinger of Strife, Plot: 0, City: 12, Player: 1800, Rand: 416
029, -2840, The Celts, Belief, Epona, the Great Mare, Plot: 0, City: 150, Player: 0, Rand: 7
029, -2840, The Celts, Belief, Nuada, the Silver-Handed King, Plot: 0, City: 42, Player: 26400, Rand: 95
029, -2840, The Celts, Belief, Cernunnos, the Horned Stag, Plot: 27, City: 12, Player: 0, Rand: 0
029, -2840, The Celts, Belief, Lugh, the Skilled One, Plot: 0, City: 288, Player: 0, Rand: 70
029, -2840, The Celts, Belief, Rhiannon, Goddess of Sovereignty, Plot: 152, City: 30, Player: 0, Rand: 39
029, -2840, The Celts, Belief, Mannanan, Son of the Sea, Plot: 0, City: 72, Player: 0, Rand: 2
029, -2840, The Celts, Belief, Ogma, the Learned, Plot: 0, City: 330, Player: 0, Rand: 40
029, -2840, The Celts, Belief, Bran, the Sleeping Guardian, Plot: 0, City: 60, Player: 0, Rand: 9
029, -2840, The Celts, Belief, Dagda, the All-Father, Plot: 0, City: 36, Player: 0, Rand: 0
027, -2920, The Celts, Belief, Morrigan, Harbinger of Strife, Plot: 0, City: 12, Player: 0, Rand: 0
027, -2920, The Celts, Belief, Epona, the Great Mare, Plot: 0, City: 168, Player: 0, Rand: 32
027, -2920, The Celts, Belief, Nuada, the Silver-Handed King, Plot: 0, City: 42, Player: 21166, Rand: 4501
027, -2920, The Celts, Belief, Cernunnos, the Horned Stag, Plot: 75, City: 12, Player: 0, Rand: 2
027, -2920, The Celts, Belief, Lugh, the Skilled One, Plot: 0, City: 288, Player: 0, Rand: 49
027, -2920, The Celts, Belief, Rhiannon, Goddess of Sovereignty, Plot: 157, City: 30, Player: 0, Rand: 35
027, -2920, The Celts, Belief, Mannanan, Son of the Sea, Plot: 0, City: 12, Player: 0, Rand: 0
027, -2920, The Celts, Belief, Ogma, the Learned, Plot: 0, City: 330, Player: 0, Rand: 44
027, -2920, The Celts, Belief, Bran, the Sleeping Guardian, Plot: 0, City: 108, Player: 0, Rand: 25
027, -2920, The Celts, Belief, Dagda, the All-Father, Plot: 0, City: 36, Player: 0, Rand: 0

**Comment by LoneGazebo** [comment]
Yeah I know why. Already fixed.

**Comment by Infixo** [comment]
This one?

```
if ((pEntry->GetRequiredCivilization() != NO_CIVILIZATION) && (pEntry->GetRequiredCivilization() == m_pPlayer->getCivilizationType()))
{
	iRtnValue *= 100;
}
```

**Comment by Infixo** [comment]
Also, another weird case:
016, -3360, The Netherlands, Belief, Goddess of Festivals, Plot: 0, City: 2029440, Player: 0, Rand: 495053

I suppose it is related to TRAIT_LUXURY_RETENTION.
In the code iTotalRtnValue *= 2; happens each time for every GetYieldPerLux, so 3x. Then within that for: IsImportsCountTowardsMonopolies, GetYieldFromImport, and GetYieldFromExport. That would account for 5x total. Times loop = 15x. It is power of 2, so 2^15.

I think that is the reason why Festivals are chosen so often, not even by Netherlands. CrazyG commented that this is rather weak pantheon, but the score gets multiplied 8x whatever its value is. Plus its base is increased by 5*numLuxuries every time. So, it will end up quite high every time.

**Comment by Infixo** [comment]
Goddess of Love. Gain Faith and GAP every time a Citizen is born. It seems that this Belief should be always scored somehow, right? People are always born, so yields will always be given. So, in 45 cases in my logs, it gets 180 points from City in 19 cases and 0 in 26 cases.
