### ISSUE TITLE
YIELD_JFD_* is not evaluated regarding plots and the AI Governors

### ISSUE THREAD

**Issue by notque** [LoneGazebo/Community-Patch-DLL#3798]
The YIELD_JFD_* yields are listed for buildings, and grandstrategy, but not plot evaluation, causing the AI to work disease tiles as a positive. 

Would it make the most sense to add the yields to the global database table, then globals, then connect it to plots, or would you prefer to hardcode some values in the CvCityCitizens.cpp

**Comment by LoneGazebo** [comment]
It gets tricky, as expanding tile yields eval beyond the base set adds a ton of CPU overhead. Probably best to do some special coding.

**Comment by TechpriestEnginseer** [comment]
Also what's wrong with using Yield_Flavors to flavor them?
