### ISSUE TITLE
Issue with Community Patch Crashing on Game Start

### ISSUE THREAD

**Issue by Valasania** [LoneGazebo/Community-Patch-DLL#3799]
_1. Mod version (i.e Date - 4/23):_
1/2/2018 (Last reported update was 8/9/17 as reported by the steam page)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
-Crash upon start of the game
-As another earlier issue, before the game began to crash, I was using the Community Patch in conjunction with other mods (which had previously worked correctly with it), and there was an issue where by around turn 10 or so (could go as high as 20, or as low as 8 sometimes) one or two random AI would suddenly leap ahead in GPT, Science, Production, etc. by several hundred per turn. Never found out what caused the issue before the game started crashing on startup.

_4. Steps to reproduce (optional):_
-With only Community Patch mods installed, tried to start the game up and it crashed upon beginning a new game.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1599417/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

(N/A - Game Crashes on game start before saving is possible)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

(No such file exists in my Civilization V folder)

4. Screenshots (optional):

(Nothing to show, sorry)

**Comment by Infixo** [comment]
Use the current version, which is 12-15. You can find it on CivFanatics as part of Vox Populi.
I have just started a game with CP only and played 20 turns with no problems.

**Comment by Valasania** [comment]
I thought I'd installed that already, but I'll give it another go.

**Comment by LoneGazebo** [comment]
if your game is updated, and you're using the installer with no other mods, it should work.

**Comment by Valasania** [comment]
I'll give it a cold restart and uninstall-reinstall everything and see how it goes.

**Comment by Valasania** [comment]
Update to the problem; deleting all mods and reinstalling both the game and the community patch has resolved the issue. Thank you for the patience and time looking at the problem - I'm not very good at dealing with the technical parts of games.
