### ISSUE TITLE
Melee ships getting moved in random cities upon city liberation

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#380]
Mine ironclad has gotten from here
![8930_2015-06-30_00008](https://cloud.githubusercontent.com/assets/1131228/8429685/873d7e82-1f43-11e5-9728-da3f066ed377.png)
to there
![8930_2015-06-30_00009](https://cloud.githubusercontent.com/assets/1131228/8429701/a28047e2-1f43-11e5-8666-c4ddd54496a4.png)
That's not even the closest city to liberated one.

**Comment by DanteValerian** [comment]
all units get expelled from CS territory when someone liberates them. Though it does seem odd that you ended up in that city. My theory: the game tried to move you to that tile north-northeast of Cahokia, but then you'd be blocked in by Tombouctu's border, so it sent you to some city.

**Comment by LoneGazebo** [comment]
Yep. Dante is correct. It uses the pathfinder.
G

**Comment by DanteValerian** [comment]
I am Delekhan from the CivFanatics boards FYI :)

**Comment by LoneGazebo** [comment]
Right! Yes. I knew that. :)

G

**Comment by Radost** [comment]
I haven't checked with ships on the newest version, but liberation with land units just places them near the city, so there is/was something wrong with liberation by a ship mechanics.
https://www.youtube.com/watch?v=SttHMbNBKK4
