### ISSUE TITLE
Unable to choose production or enter purchase screen (No-EUI)

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#3803]
_Mod version (i.e Date - 4/23):_
1/3 No-EUI

_Error description:_ 
In the No-EUI version, after founding a city you can't choose a production or purchase anything; the EUI version seems to be fine.

When trying to enter either screen, this lua error is thrown: 
...\Sid Meier's Civilization 5\MODS\(6b) Community Balance Overhaul - Compatibility Files (No-EUI)\LUA\InfoTooltipInclude.lua:1259: attempt to index global 'city' (a nil value)

Line 1259: 
`local trfaith = city:GetYieldModifierTooltip(YieldTypes.YIELD_FAITH)`

---------------------------
Save just before settlement and logs from after (Morocco used, but also tested with Greece)
[Vox_prod_bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1604366/Vox_prod_bug.zip)

**Comment by LoneGazebo** [comment]
Mmm yeah that’s my bad. I’ll fix.
