### ISSUE TITLE
Strange entry in Instant Yields list

### ISSUE THREAD

**Issue by TadhgEomonn** [LoneGazebo/Community-Patch-DLL#3804]
_1. Mod version (i.e Date - 4/23): (1/3) 2018

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description: When placing mouse over instant yields star, one entry in the list displays a culture icon followed by TXT_KEY_YIELD_JFD_LOYALTY: 107

_4. Steps to reproduce (optional):

**Comment by Infixo** [comment]
This yield is granted whenever a CS quest is completed that grants Influence.
There are few JFD yields and they seem to be granted by various CS quests, along with normal rewards.
Influence -> YIELD_JFD_LOYALTY
Experience -> YIELD_JFD_SOVEREIGNTY
GP things -> YIELD_JFD_HEALTH
I suppose they can be switched off with BALANCE_CORE_JFD set to 0 in CustomModOptions table.

**Comment by LoneGazebo** [comment]
@Infixo yes I'm using them as spoof yields for tracking. Just need to turn them off for text parser for tooltip.
