### ISSUE TITLE
Game crashing during AI turns

### ISSUE THREAD

**Issue by americ1999** [LoneGazebo/Community-Patch-DLL#3805]
_1. Mod version (i.e Date - 4/23):_  
December 13

_2. Mod list (if using Vox Populi only, leave blank):_
Civ name change based on policy

_3. Error description:_ 
When the AI is doing its turn, the game suddenly crashes. No freezing or anything. Sometimes it randomly happnes, other times it has crashed at the exact same time (when the same civ is doing its turn) whenever I upload the save.

_4. Steps to reproduce (optional):_
I have gotten rid of the mod listed above and run just vox populi, still crashes. I have unistalled and reinstalled Vox populi, still happens.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization
[New Compressed (zipped) Folder.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1605015/New.Compressed.zipped.Folder.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[America.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1605022/America.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1605028/CvMiniDump.zip)

4. Screenshots (optional):

*NOTE: I'm not an expert at all this files stuff, so I zipped the files since they seemed to be the only way to upload them. If they don't work let me know.

**Comment by Infixo** [comment]
This MiniDump is from CivilizationV_Tablet.exe (Windows 8?)
Can you run it with Civ5 DirectX 11 version and attach the MiniDump from that?

**Comment by jdw8z** [comment]
I seem to be having a similar problem. I think it's linked to the diplomacy screen. Sometimes the game crashes when I open diplomacy with a Civ, and sometimes it happens during AI turns. It doesn't always happen, but I can't tell what the cause is.


[Catherine_0176 AD-0040.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1627055/Catherine_0176.AD-0040.zip)

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1627060/CvMiniDump.zip)
