### ISSUE TITLE
default governor starves city

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3806]
first testgame with the new version ... several AI players are not expanding.

![image](https://user-images.githubusercontent.com/1358966/34591725-d84875b0-f1bf-11e7-9c1c-39309c854015.png)

settler is actively filtered out:

078, Assyria, Assur, PRE: Unit, Settler, 11225, 4
078, Assyria, Assur, PRE: Unit, Siege Tower, 7060, 3
078, Assyria, Assur, PRE: Building, Granary, 3623, 2
078, Assyria, Assur, PRE: Building, Council, 2975, 2
078, Assyria, Assur, PRE: Unit, Caravan, 2150, 2
078, Assyria, Assur, PRE: Building, Forge, 2130, 2
078, Assyria, Assur, PRE: Unit, Catapult, 1212, 3
078, Assyria, Assur, PRE: Unit, Spearman, 1012, 2
078, Assyria, Assur, PRE: Unit, Archer, 823, 2
078, Assyria, Assur, PRE: Building, Hanging Gardens, 380, 6
078, Assyria, Assur, PRE: Process, Defense, 100, 1
078, Assyria, Assur, PRE: Process, Farming, 55, 1
078, Assyria, Assur, POST: Building, Hanging Gardens, 12648, 6
078, Assyria, Assur, POST: Building, Council, 3161, 2
078, Assyria, Assur, POST: Building, Forge, 3117, 2
078, Assyria, Assur, POST: Building, Granary, 2901, 2
078, Assyria, Assur, POST: Unit, Catapult, 2401, 3
078, Assyria, Assur, POST: Process, Farming, 57, 1
078, Assyria, Assur, SEED: 6737955200976210488, CHOSEN: Hanging Gardens, Do not rush, TURNS: 6

btw, assur has pop 3 in turn 80 ... don't know how they did that, maybe the new specialization isn't working properly?

![image](https://user-images.githubusercontent.com/1358966/34591781-2df5d30e-f1c0-11e7-8e8c-5d39364dae5d.png)

**Comment by LoneGazebo** [comment]
If the settler is being thrown out in POST, that's because the AI doesn't have a good spot to settle-  I saw you made some smaller changes to site settler, any chance that caused an issue?

**Comment by ilteroi** [comment]
ok in the case of assur, the problem is simply that the city is too small. there's a population requirement of 5. seems high to me.

in the case of arabia, they're going for a spaceship victory, so building settlers is de-emphasized. maybe too early for that.

in the case of mongolia, they do have a settler out, can't tell right now why they didn't build one earlier.

**Comment by ilteroi** [comment]
but something's wrong with the governor in assur

![image](https://user-images.githubusercontent.com/1358966/34603874-00b7bc9a-f206-11e7-8efc-cac544f1952d.png)

**Comment by LoneGazebo** [comment]
Did a bad event hit them?

**Comment by LoneGazebo** [comment]
I’ll take a look. Did you see my slowdown report on your latest? Something in the tactical AI is really slowing things down in the latest.

**Comment by LoneGazebo** [comment]
(Late game)

**Comment by Infixo** [comment]
Settlers seems ok. When I was testing pantheon changes, I ran few early games. Basically up until turn 50-60. Some civs settle cities, some not. I had Siam with 3 cities. Also always few settlers are looking for spots around that time.

**Comment by ilteroi** [comment]
events are always disabled for me ...

i didn't see any slowdown report? anyway, some slowdown is to be expected because of the latest changes in danger calculation (basically doing two iterations now instead of one) and combat simulation (hard to judge the effect here, but may be significant if many units are involved).

**Comment by ilteroi** [comment]
ok, new screenshot without observer mode. may be a special case, but the default governor definitely should put more emphasis on growth as long as there's excess happiness.

![image](https://user-images.githubusercontent.com/1358966/34623587-42301fcc-f252-11e7-88e2-2cff50b53c9d.png)

**Comment by Infixo** [comment]
Seems like Culture is more important than Food.

**Comment by LoneGazebo** [comment]
Already fixed.
