### ISSUE TITLE
Tile Purchase Costs for Annexed City Weirdly High

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#3807]
_1. Mod version (i.e Date - 4/23):_ 
Latest as of 1/5/2018

_2. Mod list (if using Vox Populi only, leave blank):_
Improved city view v9
infoaddit v22
ingame editor v39
really advanced setup v15
reseed! v11

_3. Error description:_ 
Tile purchase cost is very high for annexed cities.  The bug fixes itself after you purchase a tile.  I was America if that makes a difference.

_4. Steps to reproduce (optional):_
Look at tile costs in the rightmost annexed city (near Babylon).  Notice the high price (300~ gold) and purchase.  Prices are now x3 less (100~gold).

---------------------------
[Logs.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/1606187/Logs.gz)

**Comment by Infixo** [comment]
I managed to reproduce that error for Germany, so it is not Civ related. I think I know how to fix it, will try.

**Comment by Infixo** [comment]
In CvCity::GetBuyPlotCost() this part returned INT_MAX:
```
	int iRefDistance = GetCheapestPlotInfluenceDistance();
	if (iRefDistance==INT_MAX)
		iRefDistance = 0;
```
So, all tiles were valued as if they were further from the city than actual distance (already acqured tiles ignored). Basically they were 2x or 3x more expensive, depending on location.
After you buy a tile, the routine DoUpdateCheapestPlotInfluenceDistance() is called and it fixes it, so next tiles are correctly valued.

**Comment by LoneGazebo** [comment]
Must be an ancient vanilla bug.
