### ISSUE TITLE
Mosque does not give 20% extra culture in a GA

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#3808]
_1. Mod version (i.e Date - 4/23):_
Latest as of 1/5/2018

_2. Mod list (if using Vox Populi only, leave blank):_
Improved city view v9
infoaddict v22
ingame editor v39
really advanced setup v15
reseedv11

_3. Error description:_ 
A mosque does not give 20% extra culture during a GA like it says in the description.  The mosque was obtained by building University of Sankore.

_4. Steps to reproduce (optional):_
Check my capital city. culture.  Pass turn (GA next).  Check capital.  It only receives the standard 20% from GA -- not the extra 20% from Mosque.

---------------------------
[Logs.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/1606209/Logs.gz)

**Comment by LoneGazebo** [comment]
There is no standard 20% from GA at the city level...

**Comment by LoneGazebo** [comment]
There is no standard 20% from GA at the city level...

**Comment by jimmymcperson** [comment]
Wow.  I am dumb!!!
