### ISSUE TITLE
Can interact with a city-state I am at war with

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#381]
![8930_2015-06-30_00003](https://cloud.githubusercontent.com/assets/1131228/8429741/fb0190a6-1f43-11e5-9708-89cb44a26cbb.png)
![8930_2015-06-30_00004](https://cloud.githubusercontent.com/assets/1131228/8429743/02f28c20-1f44-11e5-8572-8243367bd649.png)

**Comment by LoneGazebo** [comment]
Sounds like a LUA bug. Using any mods outside the standard set?
G

**Comment by Radost** [comment]
InfoAddict
More luxuries
Archaeologist Dig Sites
