### ISSUE TITLE
CTD in CvTacticalAI when logging

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3810]
_1. Mod version (i.e Date - 4/23): 1-3
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 
CTD during AI turn due to call to NULL variable.

[pZone problem 0132.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1607561/pZone.problem.0132.zip)

In CvTacticalAI.cpp when trying to log something pZone is NULL.

```
if (GC.getLogging() && GC.getAILogging())
{
  CvString strLogString;
  strLogString.Format("Zone %d, too early for capture of %s, required damage %d, expected damage %d", 
  pZone->GetDominanceZoneID(), pCity->getName().c_str(), iRequiredDamage, iExpectedDamage);
  LogTacticalMessage(strLogString);
}
```
Fixed it.

**Comment by Infixo** [comment]
No CTD, the log shows:
```
133, Assyria, Zone 11, City of Cape Town, is in enemy dominated zone - won't attack, X: 8, Y: 20, 
133, Assyria, Zone 14, City of Sukhothai, is in enemy dominated zone - won't attack, X: 27, Y: 23, 
133, Assyria, Zone -1, too early for capture of Cordoba, required damage 350, expected damage 138
133, Assyria, Zone 18, City of Cologne, is in enemy dominated zone - won't attack, X: 22, Y: 27, 
133, Assyria, Zone 19, City of Hamburg, is in enemy dominated zone - won't attack, X: 26, Y: 28, 

```

**Comment by LoneGazebo** [comment]
Pretty sure that was already fixed, I found the same thing.

**Comment by LoneGazebo** [comment]
One tile island maybe?

**Comment by ilteroi** [comment]
good point. probably should look at the water zone then. for "damage city" we have two functions for that reason, but for capture there's no distinction. i'll fix.

**Comment by Infixo** [comment]
If you mean Cordoba, then this is canal city on a peninsula.

@LoneGazebo I took master code yesterday (Beta 1-3). Does it contain those hotfix changes you made?

**Comment by ilteroi** [comment]
@Infixo : please don't do anything in these functions, else we'll get merge conflicts

**Comment by LoneGazebo** [comment]
@Infixo no it does not - I've got some other fixes in the pipeline as well, will upload this evening.

**Comment by Infixo** [comment]
@ilteroi Sure thing, wasn't even going to.

**Comment by LoneGazebo** [comment]
@ilteroi with the tactical changes you just made, I'm seeing a lot more passivity from the AI. They're simply not attacking/engaging. You sure you didn't introduce a bug in plot selection for the tactical AI?

**Comment by LoneGazebo** [comment]
Uploaded my latest. @ilteroi if you get a chance take a look at the landbridge/chokepoint code - some cities are being triggered for these that aren't actually land bridges or chokepoints. Also, with my latest, I'm seeing some odd unit distributions - units heading to the opposite side of an empire during a war, for example. Small quirks, though.

**Comment by ilteroi** [comment]
found the problem with the passivity / leaving the muster point. don't drink and code, guys!

re: chokepoints, do you have an example screenshot of a false positive?

**Comment by LoneGazebo** [comment]
I can get you one. The one I saw was a city on a coast that had 4 land tiles around it, all on one side. I’ll send when I’m back home.

**Comment by LoneGazebo** [comment]
@ilteroi did you upload fix?

**Comment by ilteroi** [comment]
it's done. merged and pushed. nothing about the chokepoint though

**Comment by LoneGazebo** [comment]
Danke. I'll keep an eye out for the chokepoint issue.

**Comment by ilteroi** [comment]
d'oh. just had an impossible crash. fix is pushed.

**Comment by LoneGazebo** [comment]
Yeah, I had it too, same place(s) as well.

**Comment by ilteroi** [comment]
turns out that happens with temp zones ... so it's not quite impossible ... obviously.

**Comment by LoneGazebo** [comment]
Ah, yeah, that makes sense.

**Comment by LoneGazebo** [comment]
@ilteroi shouldn't

if ((iExpectedDamage - GC.getCITY_HIT_POINTS_HEALED_PER_TURN()) > (iRequiredDamage / iRequiredDamageDivisor))

be 

if ((iExpectedDamage - GC.getCITY_HIT_POINTS_HEALED_PER_TURN()) < (iRequiredDamage / iRequiredDamageDivisor))

in CvTacticalAI::PlotDamageCityMoves() ?

**Comment by LoneGazebo** [comment]
In essence if the civ can do _too_ much damage to a city, it currently makes the AI abort the attack! :D

**Comment by LoneGazebo** [comment]
Yeah, fixing that fixes the AI city passivity issue, yay!

**Comment by ilteroi** [comment]
uh. indeed. classical copy/paste error, the logic used to be

if (condition) then attack

but now its

if (condition) then abort
