### ISSUE TITLE
CTD while calling Player:GetScienceTimes100()

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3812]
_1. Mod version (i.e Date - 4/23): 1-6 Beta
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 
CTD during a call to Player:GetScienceTimes100() from Firetuner.
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1608778/CvMiniDump.zip)
This is NULL.
```
bool CvModCityEventInfo::hasPlayerMajority() const
{ return m_bHasPlayerMajority; }
```

I ran 82 turns before that, calling that function multiple times (I use it in one of FT panels of my own).

**Comment by Infixo** [comment]
That function was called from a place where another function was supposed to be called (checking number of free units, to adjust science for GPT). Looks like linker problem - is it possible? I've rebuilt entire DLL and it didn't happen again. Weird.

**Comment by LoneGazebo** [comment]
Sounds like a linker issue. What VS you using?

**Comment by Infixo** [comment]
VC++ 2010 Express and VC++ 2008 Express for tools

**Comment by LoneGazebo** [comment]
Try 2012? Load but don’t convert the project.
