### ISSUE TITLE
Minimum City Distance Sometimes Violated on Islands

### ISSUE THREAD

**Issue by grmagne** [LoneGazebo/Community-Patch-DLL#3813]
_1. Mod version 12/15

_2. Mod list (if using Vox Populi only, leave blank):_
(9) Wonders Expanded (v1)
Tectonic Map Script (v4)
Unique City-States (v2)

_3. Error description:_ 
Sometimes an island city can be built too close to another city, but I've never see it on a large continent. I change the WorldSizes file as described below in Step_4. Occasionally the AI is able to build an island city only 3 spaces from another city. I've seen this exact thing happen about 5 times during the past year, always on small islands. This happened yesterday in version 12/15 and I couldn't raze this particular island city even though I was able to raze all other cities without a problem.

_4. Steps to reproduce (optional):_

I modify the **WorldSizes** SQL file as follows:

-- Huge - 3 Minimum for Major, 2 for Minor

UPDATE Worlds
**SET MinDistanceCities = '4'**
WHERE Type = 'WORLDSIZE_HUGE';

UPDATE Worlds
**SET MinDistanceCityStates = '4'**
WHERE Type = 'WORLDSIZE_HUGE';

UPDATE Worlds
SET ReformationPercentRequired = '60'
WHERE Type = 'WORLDSIZE_HUGE';

-- Default value that the values above can never exceed (minimally)

-- Min City Range
UPDATE Defines
**SET Value = '4'**
WHERE Name = 'MIN_CITY_RANGE';

**Comment by ilteroi** [comment]
this is by design ... the limitation only applies to cities on the same continent.

**Comment by LoneGazebo** [comment]
If it was settled on a unique resource you can't raze it.

G
