### ISSUE TITLE
Typo: EUI_tooltip_library.lua (1/3 Beta)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#3815]
_1. Mod version (i.e Date - 4/23):_
1/3 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
VP+EUI (Automatic install)
IGE

_3. Error description:_ 
I found a weird tooltip; **TXT_KEY_AIR_STRENGTH_DEFENSE**.

_4. Steps to reproduce (optional):_
Open the production panel.
Hover over a unit that has Air Strike Defense.

---------------------------
Supporting information:

4. Screenshots (optional):

![ss](https://user-images.githubusercontent.com/11933188/34644728-73cac202-f37f-11e7-9599-5786d6ebdc53.png)

---------------------------
cf.
(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\EUI_tooltip_library.lua
Line: 295

https://github.com/LoneGazebo/Community-Patch-DLL/blob/a2695ac1534fbf7caf2f1466aa3453131fe79502/EUI%20Compatibility%20Files/EUI%20Compatibility%20Files/LUA/EUI_tooltip_library.lua#L295

**Comment by LoneGazebo** [comment]
That TXT file is defined in EUI - sounds like a database error on your end?

**Comment by 8h42** [comment]
I should have deleted bc1's original EUI_text_en_us.xml.
Now it works fine.
Thank you!

**Comment by LoneGazebo** [comment]
Yep!
