### ISSUE TITLE
barbarian cities

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3816]
so first of all, i notice that AI players show little inclination to liberate city states ... can you confirm that? i feel like it used to be different, no so many barbarian cities around.

![image](https://user-images.githubusercontent.com/1358966/34644853-11090682-f33f-11e7-86d7-e4207e614127.png)

also, one of these cities is annexed, the other isnt' ... why? does it make a difference?

edit: funny, now they're actually building a barbarian courthouse in valetta

**Comment by LoneGazebo** [comment]
haha. The AI should go for liberation - perhaps the tactical AI is ignoring the cities? I haven't touched any other code related to them.

**Comment by ilteroi** [comment]
don't know about the annexation thing, but AI should actually set up operations targeting barbarian cities now. because they didn't ...

**Comment by LoneGazebo** [comment]
I already fixed that... oh well, I'll see if your fix is the same as mine.
