### ISSUE TITLE
unit supply inconsistencies

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3818]
i tried to plot some data to see whether the AI keeps exceeding the limit, but the results were highly confusing, there are many numbers and they just don't seem to add up.

i have added some new columns to MilitaryLog.csv and invite everybody to take a look. in my case, Carthage is totally crippled because they consistently over the supply limit by 16 units. the others do better ... but still there are interesting observations (note on the graphs, these are 80 turns for 8 players consecutively, so the graphs "resets" 7 times - the x axis labels are misleading)

1. free units seems to be quite variable?

![image](https://user-images.githubusercontent.com/1358966/34644989-cea15cfa-f342-11e7-8659-3a6433c4430b.png)

2. GetOutOfSupplyUnits counts civilians, is that by design? see the difference here:

![image](https://user-images.githubusercontent.com/1358966/34645038-36137cfa-f344-11e7-8455-23bfad925883.png)

3. CheckUnitBuildSanity does not consider free units?

4. getNumUnitsNoCivilian() has an extremely misleading name or it's just buggy?

5. the statusbar doesn't seem to count civilians ... where do those numbers come from?

**Comment by Infixo** [comment]
Hm. Are Caravans, Cargo ships and Workboats supposed to be Military Units?

**Comment by Infixo** [comment]
Also, I think that IsCivilianUnit() treats Nuclear Missile, Atomic Bomb and Assyrian Siege Tower as civilian units because they have Combat = 0 and RangedCombat = 0.

**Comment by ilteroi** [comment]
further digging ... the carthaginians ruin themselves between turn ~80 and ~100:

![image](https://user-images.githubusercontent.com/1358966/34649121-e8432e0c-f3a8-11e7-9a07-bbf310fc1103.png)

the red curve is the bad one. funny thing is though, they don't actually build any military unit during that timeframe:

075, Carthage, Carthage, SEED: 3938508409898476193, CHOSEN: Settler, Do not rush, TURNS: 4
075, Carthage, Saguntum, SEED: 16496767044449533126, CHOSEN: Well, Do not rush, TURNS: 1
076, Carthage, Utique, SEED: 13884189613042779999, CHOSEN: Scrivener's Office, Do not rush, TURNS: 6
076, Carthage, Hippo Regius, SEED: 2584902013012182444, CHOSEN: Forge, Do not rush, TURNS: 9
076, Carthage, Gades, SEED: 11086165143126303242, CHOSEN: Shrine, Do not rush, TURNS: 4
076, Carthage, Saguntum, SEED: 575549122207087227, CHOSEN: Monument, Do not rush, TURNS: 7
078, Carthage, Carthage, SEED: 8021780450629884572, CHOSEN: Heroic Epic, Do not rush, TURNS: 3
080, Carthage, Gades, SEED: 23535597086996862, CHOSEN: Arena, Do not rush, TURNS: 6
081, Carthage, Carthage, SEED: 1860602619797693702, CHOSEN: Worker, Do not rush, TURNS: 2
082, Carthage, Carthage, SEED: 13139476011283519371, CHOSEN: Oracle, Do not rush, TURNS: 8
082, Carthage, Utique, SEED: 7303341088769740904, CHOSEN: Temple, Do not rush, TURNS: 4
082, Carthage, Hippo Regius, SEED: 692349159871044737, CHOSEN: Walls, Do not rush, TURNS: 2
082, Carthage, Gades, SEED: 14575215484396364070, CHOSEN: Forge, Do not rush, TURNS: 9
082, Carthage, Saguntum, SEED: 10815185125605155175, CHOSEN: Shrine, Do not rush, TURNS: 1
083, Carthage, Saguntum, SEED: 2463557243520946596, CHOSEN: Market, Do not rush, TURNS: 8
084, Carthage, Hippo Regius, SEED: 13808654264563837199, CHOSEN: Shrine, Do not rush, TURNS: 3
086, Carthage, Utique, SEED: 7926330608280180366, CHOSEN: Castle, Rush if possible, TURNS: 16
087, Carthage, Carthage, SEED: 6624911660813832633, CHOSEN: Great Cothon, Do not rush, TURNS: 6
087, Carthage, Hippo Regius, SEED: 254877794620922366, CHOSEN: Temple, Do not rush, TURNS: 8
088, Carthage, Carthago Nova, SEED: 15472826693665862846, CHOSEN: Arena, Do not rush, TURNS: 15
089, Carthage, Gades, SEED: 11307508960173359500, CHOSEN: Stable, Do not rush, TURNS: 14
089, Carthage, Saguntum, SEED: 5761170692516577493, CHOSEN: Walls, Do not rush, TURNS: 5
092, Carthage, Carthage, SEED: 1305804802652451668, CHOSEN: Settler, Do not rush, TURNS: 4
093, Carthage, Hippo Regius, SEED: 634645702136863896, CHOSEN: Angkor Wat, Rush if possible, TURNS: 19
094, Carthage, Saguntum, SEED: 1581837199515923350, CHOSEN: Forge, Do not rush, TURNS: 11
096, Carthage, Carthage, SEED: 13973622474810180593, CHOSEN: School of Philosophy, Do not rush, TURNS: 7
097, Carthage, Hippo Regius, SEED: 1149725197272948602, CHOSEN: Monument, Do not rush, TURNS: 3

so apparently the bad units were bought?

**Comment by ilteroi** [comment]
to confuse the story even further, there's also a slight discrepancy between the reported unit counts ....

![image](https://user-images.githubusercontent.com/1358966/34649127-17f15944-f3a9-11e7-8018-88226c865633.png)

**Comment by Infixo** [comment]
@ilteroi See my comments. Few unit tyoes are counted differently in various functions. I.e. Cargo, caravan, workboat, atomic stuff.

**Comment by ilteroi** [comment]
well moat of these are not military units so they shouldn't count in either metric.

also interesting, carthage has completed authority and therefore probably got a few free units. they only have 5 cities though, so that doesn't explain everything.

**Comment by LoneGazebo** [comment]
Keep in mind the AI gets a handicap bonus of supply as well. Are you keeping track of that?

**Comment by ilteroi** [comment]
well, i'm assuming that's included in getnumfreeunits. in fact that's why i was suprised to see it oscillate like that. anyway the production modifier etc depend only on getoutofsupplyunits, so that'a what we shouldnbe looking at. 

question is, do you intend to do anything about this mess or should i take a stab at it?

and: who created this getnumunitsnocivilian function and what were they thinking?

**Comment by LoneGazebo** [comment]
@ilteroi I did, gods know how long ago, and it was supposed to be just for LUA. TBH I'm not even sure why it's being used. I'm going to work on all of this today.

G

**Comment by ilteroi** [comment]
ok, relax and merge :)

i just did some changes ...

1. unit build sanity now considers free units
2. getoutofsupplyunits doesn't count civilians anymore
3. unit scrapping should work

not very well tested, but pushed nevertheless :)

what remains is:

1. check statusbar
2. check getnumunitsnocivilian 
3. check "military support" flag

**Comment by LoneGazebo** [comment]
Yeah, I saw your merge. I think the issue is that I had the 'freeunit' function setting the change at the player level, not the unit level, but not all units are created at the player level first. That was dumb of me.

**Comment by ilteroi** [comment]
oh, that was a different fix, 

now it's pushed for real, wanted to wait at least for 5 turns :)

**Comment by LoneGazebo** [comment]
haha.

**Comment by LoneGazebo** [comment]
The old 'it worked for five turns? time for a public beta!' approach. A standby of mine.

**Comment by ilteroi** [comment]
oh yeah, one more thing, the military stats are now in the military summary log. makes more sense and easier to plot. over and out!

**Comment by LoneGazebo** [comment]
Good idea.

**Comment by Infixo** [comment]
Caravans, Cargo ships and Workboats - are they still going to be counted as military units?

**Comment by ilteroi** [comment]
@Infixo : i would prefer them not to count ...

anyway, here's the latest plot, looking better:

![image](https://user-images.githubusercontent.com/1358966/34661564-dd8944c2-f44a-11e7-8b37-818227fd64df.png)

carthage is still not quite fixed though (order is arabia, brazil, carthage, ...)

**Comment by Infixo** [comment]
There's a function CvUnit::IsCivilianUnit() that counts only units that have Combat >0 or RangedCombat >0 as civilian. It is used with changeNumFreeUnits(). So, basically the problem is still with Atomic weapons and Siege Tower, which have MilitarySupport set to '1' but are considered civilian for the purpose of civilian counting. Maybe Carthage is building Siege Towers?

Anyway. I would make a simple rule: MilitarySupport flag should decide whether it is military unit or not. Flexible, can be set on unit level.
Then NumMilitaryUnits returns true number, that can be checked against SupplyCap directly.

**Comment by LoneGazebo** [comment]
I’ve fixed the civilian unit issue in my build.

**Comment by ilteroi** [comment]
ok, it seems most of the excess units come through BuyEmergencyUnit(). should be possible to put some safeguards around it.

one interesting piece of code is MakeOffensivePurchases() though. i really don't get the logic here:

```
	// Are we winning all the wars we are in?
	MilitaryAIStrategyTypes eStrategyAtWar = (MilitaryAIStrategyTypes) GC.getInfoTypeForString("MILITARYAISTRATEGY_AT_WAR");
	if(!IsUsingStrategy(eStrategyAtWar) || m_pPlayer->GetDiplomacyAI()->GetStateAllWars() == STATE_ALL_WARS_WINNING)
	{
		// Do we have a high offensive personality flavor and our military could be larger?
		if (m_pPlayer->GetFlavorManager()->GetPersonalityIndividualFlavor((FlavorTypes)GC.getInfoTypeForString("FLAVOR_OFFENSE")) >= 7 &&
			(GetPercentOfRecommendedMilitarySize() < 100 || m_eNavalDefenseState > DEFENSE_STATE_ENOUGH))
```

buy more units when at peace or you're already winning? does this make sense at all?

**Comment by LoneGazebo** [comment]
We should just disable that.

**Comment by ilteroi** [comment]
*poof*

it's gone

**Comment by ilteroi** [comment]
what does MOD_BALANCE_CORE_UNIT_INVESTMENTS do? and what about MOD_BALANCE_CORE_BUILDING_INVESTMENTS?

**Comment by LoneGazebo** [comment]
They do the 50% invest logic. 

G

**Comment by ilteroi** [comment]
ah ok. but the unit investment is disabled by default. makes sense.

**Comment by LoneGazebo** [comment]
Yeah that was for jfd.
