### ISSUE TITLE
Gifted khans don't give a healing bonus 

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#382]

**Comment by LoneGazebo** [comment]
Explain? Not sure what you're referring to. I think that ability may be unique to the Mongolians, perhaps?
G

**Comment by Radost** [comment]
But khans have healing in their promotions.
![8930_2015-07-01_00002](https://cloud.githubusercontent.com/assets/1131228/8455723/27864bbc-2020-11e5-94fa-ffddb7b35d18.png)

**Comment by LoneGazebo** [comment]
I honestly don't know, as there's nothing in the code that should prevent this.

G
