### ISSUE TITLE
production AI quirks

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3820]
so maybe this is because of my classical starts, but i've got another victim ...

000, Arabia, Mecca, SEED: 2296063415279551719, CHOSEN: Bazaar, Rush if possible, TURNS: 19
016, Arabia, Mecca, SEED: 5106579695506662965, CHOSEN: Monument, Do not rush, TURNS: 11
023, Arabia, Mecca, SEED: 6716789073987358515, CHOSEN: Mausoleum of Halicarnassus, Do not rush, TURNS: 12
032, Arabia, Mecca, SEED: 100644044444528077, CHOSEN: Petra, Do not rush, TURNS: 11
047, Arabia, Mecca, SEED: 14409541385238330765, CHOSEN: Great Library, Do not rush, TURNS: 15
057, Arabia, Mecca, SEED: 6951960975556111415, CHOSEN: Arena, Do not rush, TURNS: 9
067, Arabia, Mecca, SEED: 4560708227229859493, CHOSEN: Walls, Do not rush, TURNS: 3
074, Arabia, Mecca, SEED: 16785695970584824625, CHOSEN: Water Mill, Do not rush, TURNS: 4

almost the whole world is settled by now but arabia still has only one city.

example for individual scores here:

067, Arabia, Mecca, PRE: Unit, Settler, 10600, 8
067, Arabia, Mecca, PRE: Unit, Worker, 5700, 5
067, Arabia, Mecca, PRE: Building, Granary, 4867, 4
067, Arabia, Mecca, PRE: Building, Aqueduct, 3790, 14
067, Arabia, Mecca, PRE: Unit, Caravan, 3490, 6
067, Arabia, Mecca, PRE: Building, Water Mill, 3000, 5
067, Arabia, Mecca, PRE: Building, Hanging Gardens, 2945, 19
067, Arabia, Mecca, PRE: Building, Herbalist, 2440, 7
067, Arabia, Mecca, PRE: Building, Walls, 2200, 3
067, Arabia, Mecca, PRE: Building, Forge, 1980, 10
067, Arabia, Mecca, PRE: Unit, Composite Bowman, 1143, 6
067, Arabia, Mecca, PRE: Unit, Spearman, 1126, 5
067, Arabia, Mecca, PRE: Building, Shrine, 900, 4
067, Arabia, Mecca, PRE: Building, Council, 805, 4
067, Arabia, Mecca, PRE: Building, Barracks, 660, 3
067, Arabia, Mecca, PRE: Unit, Catapult, 597, 7
067, Arabia, Mecca, PRE: Process, Farming, 445, 1
067, Arabia, Mecca, PRE: Building, Roman Forum, 260, 19
067, Arabia, Mecca, PRE: Unit, Scout, 180, 6
067, Arabia, Mecca, PRE: Process, Defense, 100, 1

067, Arabia, Mecca, POST: Building, Water Mill, 189582, 5
067, Arabia, Mecca, POST: Building, Walls, 30611, 3
067, Arabia, Mecca, POST: Building, Shrine, 20180, 4
067, Arabia, Mecca, POST: Unit, Catapult, 15464, 7
067, Arabia, Mecca, POST: Unit, Scout, 13875, 6
067, Arabia, Mecca, POST: Unit, Settler, 12776, 8
067, Arabia, Mecca, POST: Building, Barracks, 12034, 3
067, Arabia, Mecca, POST: Unit, Spearman, 10721, 5
067, Arabia, Mecca, POST: Unit, Composite Bowman, 10017, 6
067, Arabia, Mecca, POST: Building, Forge, 9101, 10
067, Arabia, Mecca, POST: Unit, Worker, 3898, 5
067, Arabia, Mecca, POST: Unit, Caravan, 3772, 6
067, Arabia, Mecca, POST: Building, Council, 2718, 4
067, Arabia, Mecca, POST: Building, Granary, 2494, 4
067, Arabia, Mecca, POST: Building, Herbalist, 2070, 7
067, Arabia, Mecca, POST: Building, Roman Forum, 1325, 19
067, Arabia, Mecca, POST: Building, Hanging Gardens, 801, 19
067, Arabia, Mecca, POST: Building, Aqueduct, 141, 14
067, Arabia, Mecca, POST: Process, Farming, 88, 1
067, Arabia, Mecca, SEED: 4560708227229859493, CHOSEN: Walls, Do not rush, TURNS: 3

watermill is way out of range ... also maybe it's in general not a good idea to build wonders when you have only one city

**Comment by Infixo** [comment]
138, Indonesia, Denpasar, POST: Building, Water Mill, 178235, 6
147, Barbarians, Vancouver, POST: Building, Water Mill, 386474, 20
In my log from 160 turns WM gets usually 6000-15000.

Also Stone Works get quite high sometimes.
132, Indonesia, Denpasar, POST: Building, Stone Works, 407656, 6
119, Carthage, Carthago Nova, POST: Building, Stone Works, 122552, 7
150, Indonesia, Samarinda, POST: Building, Stone Works, 458681, 7
151, The Aztecs, Calixtlahuaca, POST: Building, Stone Works, 1081279, 5
But usually 1000-8000.

But Arena is a leader:
120, Indonesia, Makassar, POST: Building, Arena, 2332055, 10
128, Songhai, Nicaea, POST: Building, Arena, 929849, 15
130, Indonesia, Batam, POST: Building, Arena, 878238, 9
146, The Aztecs, Calixtlahuaca, POST: Building, Arena, 1125982, 1
151, The Aztecs, Xochicalco, POST: Building, Arena, 1125982, 1
157, Indonesia, Samarinda, POST: Building, Arena, 594022, 20
But usually gets 10000-50000.

**Comment by ilteroi** [comment]
another thing, arabia has bad barbarian issues.

![image](https://user-images.githubusercontent.com/1358966/34648522-f45ffa66-f39a-11e7-9555-33592971270a.png)

military AI knows it too, GetBarbarianThreatTotal() is 160 ... but they aren't building units.

**Comment by LoneGazebo** [comment]
Why start in classical btw? It definitely leaves th  AI a bit behind.

**Comment by ilteroi** [comment]
well, because i've seen the ancient era a bit too often. also,
somebody should test it, right? otherwise let's disable it. 

anyway, what is it that's tripping up the algorithm here?

**Comment by LoneGazebo** [comment]
My guess is that the city's starting size and lack of buildings causes the 'average' yields for the city to be far enough below the criteria threshold that the AI overvalues buildings that give yields to compensate for that.
