### ISSUE TITLE
Top Panel Great People doesn't account for Goddess of Beauty (even after turns have passed)

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#3822]
_1. Mod version (i.e Date - 4/23):_1/3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I know, I know, EUI. Just making the report, and if you hit it with the Not Going to Fix, I won't say nothing.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![screenshot 4](https://user-images.githubusercontent.com/16260521/34646548-079c0a3c-f339-11e7-85ed-e5b7b2c8f914.png)

**Comment by Infixo** [comment]
I've fixed it. There were differences in the code from CityView, TopPanel didn't account for all modifiers and extra GPP.
While at it, I also fixed GPList (small window in the top left). It had rounding errors that caused turns to be calculated wrong.

**Comment by LoneGazebo** [comment]
danke @Infixo. you quick!

**Comment by LoneGazebo** [comment]
@Infixo are you going to do the same for the CBO/No-EUI panels and info? I'd appreciate it.

**Comment by Infixo** [comment]
Sure, only tomorrow.

**Comment by Infixo** [comment]
Done.

**Comment by Infixo** [comment]
TopPanel - modified in EUI versions (2), NonEUI doesn't have this info
GPList.xml - all are the same
GPList.lua - modified all versions to properly calculate Turns using precise ProgressTimes100. This function is available in all DLLs.
