### ISSUE TITLE
Crazy city healing using version 15-12 hotfix

### ISSUE THREAD

**Issue by besset** [LoneGazebo/Community-Patch-DLL#3824]
_1. Mod version (i.e Date - 4/23):_

15-12 hotfix version.

_2. Mod list (if using Vox Populi only, leave blank):_

Everything vox populi + infoaddict

_3. Error description:_ 

I declared war on The Netherlands, took one of his cities. When i was about to start attacking his capital (using 3 super upgraded field cannons, loads of musketmen/cuirassers) i took his capital to about 75% in one turn, but it healed for 174 hp each turn. I think the city had a knight and GG in it. I never saw this amount of city healing ever in any of my games, the city only had about 76 defense. I think this guy had the same problem: https://forums.civfanatics.com/threads/possible-bug-city-healing-100-hit-points-every-turn.625930/

I also checked my Set DefenseValue and it said "10" like it should be. This is also a new save using this version.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[APP.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1609797/APP.log)
[CustomMods.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1609798/CustomMods.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1609799/Database.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1609800/Lua.log)
[modding.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1609801/modding.log)
[net_message_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1609802/net_message_debug.log)
[stopwatch.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1609803/stopwatch.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1609804/xml.log)
[xml-perf.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1609805/xml-perf.log)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Haile Selassie_0256 AD-1730.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/1609812/Haile.Selassie_0256.AD-1730.txt)

changed file extension

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![20180107005139_1](https://user-images.githubusercontent.com/18007186/34649955-f4eba1ce-f3b8-11e7-9e9d-852fd213b0de.jpg)

That's the city that is healing 174 each turn. Just cant seem to capture it

**Comment by Voker57** [comment]
Can reproduce with 1.3. In this save: https://dump.bitcheese.net/files/mymyvav/atk.Civ5Save (Load as russia) Moscow with defense focus heals for 33 + 37 (100%production) instead of 33 + 3.7 as it should.

**Comment by Infixo** [comment]
Fixed.
As a temporary solution you can either disable the process by setting its DefenseValue to 0 or minimize HP gains by setting it to 1. In the latter case the city will heal at the rate of 10% of production (and receive only 1% of stregth increase).
