### ISSUE TITLE
Max peace values 0 or very low despite war score 90 - 100

### ISSUE THREAD

**Issue by Kierkegaard89** [LoneGazebo/Community-Patch-DLL#3825]
_1. Mod version (i.e Date - 4/23):_
1/3

_2. Mod list (if using Vox Populi only, leave blank):_
/

_3. Error description:_ 
In this game I declared war upon Portugal. I conquered her 3 biggest cities and her capital and had a warscore of 100. When I went to make peace the max peace value only had values from 0-8.
Clearly since I am destroying her this should be way higher.

_4. Steps to reproduce (optional):_
I declared war upon her again later (see screenshots). I have a war score of 90 and the max peace value is 0. She still has 4 cities and can offer to be a vasal. Yet this can't happen since the max peace value is 0.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1610370/Database.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1610371/Lua.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1610372/xml.log)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
I have three save files, but don't see moddedsaves as this is regarding a MP game with my partner.
https://www.dropbox.com/s/2n4w5xwjgtaylae/Askia%20peacedeal%201.Civ5Save?dl=0
https://www.dropbox.com/s/ibbhj5ycrqsqsyo/Askia%20peacedeal%202.Civ5Save?dl=0
https://www.dropbox.com/s/bkw7mu5ks2l67ll/Askia%20peacedeal%203.Civ5Save?dl=0

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![peacedeal 1](https://user-images.githubusercontent.com/29987696/34656193-00842cc4-f3cb-11e7-9314-3e86d3b982b1.png)
![peacedeal 2](https://user-images.githubusercontent.com/29987696/34656194-00b80f76-f3cb-11e7-875e-ad08d5fa371b.png)

**Comment by LoneGazebo** [comment]
Where are your banners, etc? Game looks odd.

**Comment by Kierkegaard89** [comment]
I am in the diplomatic screen. 
I can't recall from previous games but in a new game they are not there in the diplomatic screen.

**Comment by MoiMagnus** [comment]
This interface is standard in MP games (but should not occur in a SP game).
