### ISSUE TITLE
Player:FindPathLength() broken

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3826]
_1. Mod version (i.e Date - 4/23): 1-6
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 
There's an exposed to Lua function findPathLength() supposed to return number of techs required to get to the given one. This function was counting techs multiple times during recursive calls returning totally wrong results. Also counted techs in the queue (but not researched) as researched.
I need it in a mod, so I've fixed it.

**Comment by ilteroi** [comment]
talking about misleading names ... care to change it? apparently nobody was using it anyway :)

**Comment by Infixo** [comment]
Lua uses the same name, and it is an original function. Not the best name, I agree, but there might be mods using it. Better leave it and I will add some comments explaining what it does.

**Comment by ilteroi** [comment]
you will be breaking those mods anyway if they relied on the bad result. best not to do it silently.
