### ISSUE TITLE
CityView: comparable yields and clean-up

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3828]
_1. Mod version (i.e Date - 4/23): 1-6
_2. Mod list (if using Vox Populi only, leave blank): none

PART 1 COMPARABLE YIELDS
Not an error, rather optional change. Deadstarre post will explain it:

> In city view, when you hover over a specialist slot it displays a tooltip showing the yields working that specialist gives. right now, those yields are affected by city modifiers so for example people think working a scientist can give them 13.6 science, while they might also be evaluating an academy on the terrain that displays 9 science as yield. problem is, the terrain is never modified, so while working the specialist appears to give more science, if you work the academy instead and then do the math on your output you'll often see working the academy was in reality better.
> The singular function of displaying tooltips for specialists is so people can do comparisons between working the specialist, and working the land. when one number is modified and the other isn't, this sows chaos and confusion and you get posts like this https://forums.civfanatics.com/thre...rther-development.626012/page-5#post-14969881 - he's trying to help but has no idea the numbers in the tooltip are wrong to compare to terrain values. 
> 

There is a way to check raw specialist's yields if you hover over the building in the city screen. Which is probably even more confusing because a) there is a tooltip for "empty specialist slot" which shows a different number b) if you activate this specialist, the yields shown by the building icon will grow much more than shown in the building tooltip.

Anyway, to make yields from specialists and buildings comparable to those from tiles, the modifiers need to be turned off in 2 places. It is actually very easy change.

PART 2 CLEAN UP
Some minor fixes and more tweaks found during work with CityView.
1. Specialist tooltip will show food consumed by a specialist.
2. Buildings will show base yields, except 2 cases:
2a. Yield per pop from a building.
2b. Additional yields from building modifier, if it has one.
~3. (todo) Yield tooltips are not 100% in sync with DLL data.~
~4. (todo) Production yield rate has rounding errors (up to 1 prod/turn difference).~
5. Separated food% and growth% modifiers, food consumed is shown just after base food.
6. Added missing 4 tooltips tha allow to properly show Wltkd and GA tooltips.
7. Added yields from process.

**Comment by LoneGazebo** [comment]
The issue isn’t ease, it’s that most users like it the way that it is.

**Comment by deadstarre** [comment]
by any quality of life measure, there is no chance users prefer to have the modified specialist tooltips when comparing to terrain. poll would bear that out quickly and a good number of users dont even know this is currently happening, thats why u get posts complaining about high special yields.

**Comment by Infixo** [comment]
Assuming that work on tile yields will continue (e.g. manufactury, forests, farms) and at the same time specialists are tweaked, it would be better to have a chance to accurately compare boths.

**Comment by LoneGazebo** [comment]
@deadstarre @Infixo make a poll, then. Yours @deadstarre is the only complain I've seen. If others agree, we make the change.

G

**Comment by deadstarre** [comment]
@LoneGazebo you nixed the conversation by saying in november you wern't gonna take a look at the EUI files because it was "a labyrinth you refused to go back into". nobody is gonna complain if they think theyre forcing you to put in more effort and do things you dont want to do, but if you had instead been honest at that time and said itd be easy to do but you wouldnt do it cause thats what you *felt* players wanted, you'd have seen differently and there'd have been a conversation. and no mine i'm not the only one feels that way but honestly i'm all out of enthusiasm for now; i already had the fix, @Infixo just improved it (sincere thank you for taking a look at it) so im good; do as you please man.

**Comment by LoneGazebo** [comment]
I didn't say anything about it being easier now than then, or that it is suddenly easy to fix - I loathe messing with lua because, as it stands, there are 5 different UIs being maintained for VP at a time. Changing one means changing them all. Getting them all working right takes a good deal of time. Infixo only made changes to 1 out of 5 total interfaces.

**Comment by Infixo** [comment]
I posted the poll. Let’s wait for 20+ responses.

@LoneGazebo Btw, pls commit 1-8 to master.

**Comment by Infixo** [comment]
It seems that majority of voters (68%) wants comparable yields both for specialists and buildings. Definetely thus for specialists (89%).
Funny thing is that Non-EUI interface doesn't have this issue - it only displays raw yields. Modifiers were added in EUI.

**Comment by LoneGazebo** [comment]
Yeah it was an EUI feature. Fine with me. As I noted my issue was only that I hate working with EUI and it generally takes a stupid amount of trial and error to get it to work.

**Comment by Infixo** [comment]
The more I dig into CityView, the more errors I find. Damn. I've fixed food yields displayed near the buildings. There was some funky food calculation for specialists and application of BuildingYieldModifier for net yield, not base. Also, found a bug in Science tooltip, yet to be fixed.

The main problem is that it uses DLL values (meaning, taken directly via a dedicated Lua, which I assume are correct and will reference them in case of doubts) and at the same time calculates many things manually. Not always the correct formula is used. Plus rounding errors (sometimes it uses Times100 values and sometimes rounded integers).

I will try to clean it up a little, so more changes will come.

**Comment by ilteroi** [comment]
how do these changes affect the improved city view mod-mod? if at all?

**Comment by Infixo** [comment]
@ilteroi It uses an eui version of cityview.lua and has the same issues. I am actually using it, so I make changes there too, „unofficially”. I can share it later once i’m done.

**Comment by ilteroi** [comment]
how about folding the improved city view into the vp eui component? is there anyone who doesn't like it?

**Comment by LoneGazebo** [comment]
Works for me. If we're gonna go for gold let's do it all. :)

G

**Comment by Infixo** [comment]
I've made a new version of ICV and posted it to CivFanatics. As for now there are not so many downloads that would deem prudent to make it into base VP yet, I think.
I will be fixing EUI CityView if more errors are found and keep that new ICV in sync so it can be easily integrated into VP in the future.
