### ISSUE TITLE
City state AI stuck

### ISSUE THREAD

**Issue by Voker57** [LoneGazebo/Community-Patch-DLL#3829]
_1. Mod version (i.e Date - 4/23):_

1.3

_2. Mod list (if using Vox Populi only, leave blank):_

VP + Tectonic map https://steamcommunity.com/sharedfiles/filedetails/?id=121243367

_3. Error description:_ 

City State AI gets stuck on its turn until it gets killed. Relevant log piece:
```
[290915.576] DBG: UpdateMoves() : player.AI_unitUpdate() called for player 23 Mombasa
[290915.675] DBG: UpdateMoves() : player.AI_unitUpdate() called for player 23 Mombasa
[290915.778] DBG: UpdateMoves() : player.AI_unitUpdate() called for player 23 Mombasa
<repeated over 9000 times>
[290915.778] DBG: GAME HANG - Please show Ed and send save. Stuck units will have their turn ended so game can advance. [DETAILS: Player 23 Mombasa. First stuck unit is Trireme at (27, 17)]
```

_4. Steps to reproduce (optional):_

1. Load save
2. For example, load as Boudicca, kick other humans
3. End turn
4. Watch Mombasa's trireme get really puzzled

---------------------------
Supporting information:

1. Log files: http://dump.bitcheese.net/files/dujozaf/logs.zip

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): http://dump.bitcheese.net/files/cewohyf/mombasaloh.Civ5Save

**Comment by ilteroi** [comment]
can't load the save, but may be fixed already ... do you have a screenshot of the situation around mombasa?

**Comment by Voker57** [comment]
http://dump.bitcheese.net/files/vopoxyd/trireme.png problematic trireme is topmost one

**Comment by ilteroi** [comment]
let's turn the tables, try this build and tell me if it's fixed!
[CvGameCore_Expansion2-navyfix.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1620213/CvGameCore_Expansion2-navyfix.zip)

**Comment by Voker57** [comment]
Yes, it appears to fix the problem.
