### ISSUE TITLE
AI doesn't perform sanity checks on its trade roads

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#383]
![8930_2015-06-29_00001](https://cloud.githubusercontent.com/assets/1131228/8429921/aeb0ff28-1f45-11e5-80c9-8bf3fa52c887.png)

**Comment by LoneGazebo** [comment]
It does, but I'll bump the value up a bit more.
G

**Comment by DanteValerian** [comment]
That's only two tiles of road, and frankly not such a bad idea. If invaders block the western road you can use the eastern road through the mountains to reinforce, or move to flank. Make a village on one of the roads and you're out just 1 GPT for that extra road.

**Comment by Radost** [comment]
What are you smoking? Roads get auto-pillaged once they stumble upon a hostile unit.
