### ISSUE TITLE
Floating Gardens (1/8 Beta)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#3830]
cf.
(2) Community Balance Overhaul\Balance Changes\Leaders\Vanilla\VanillaLeaderChanges.sql
Line: 762-763

```
INSERT INTO Building_YieldChangesPerPop
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_FLOATING_GARDENS', 'YIELD_FOOD', 25),
	('BUILDING_FLOATING_GARDENS', 'YIELD_PRODUCTION', 25),
```

This means +1f/p per **4** citizens, doesn't it?
Its description says +1f/p per **5** citizens, though.

cf.
(2) Community Balance Overhaul\Balance Changes\Text\en_US\CivText.sql
Line: 115

`SET Text = '+1 [ICON_FOOD] Food and [ICON_PRODUCTION] Production for every 5 [ICON_CITIZEN] Citizens in the City. Each worked Lake tile provides +2 [ICON_FOOD] Food, and River tiles produce +1 [ICON_FOOD] Food.'`

Which is correct?

**Comment by LoneGazebo** [comment]
I'll fix text.
