### ISSUE TITLE
Piazza San Marco missing National Monument instant yields

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#3834]
_1. Mod version (i.e Date - 4/23):_
1/8

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Piazza San Marco does not have the GAP from policy unlock and the culture from citizen birth of the National Monument.

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
Intentional.
