### ISSUE TITLE
Units heal even if negative number of resources

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#3836]
1. Mod version (i.e Date - 4/23): 1/3

2. Mod list (if using Vox Populi only, leave blank):
- several UI mods, nothing dealing with units or resources

3. Error description:
- the enemy pillaged my horses, so I am in the negative horse supply now (-2), yet my horsemen are still healing

**Comment by ilteroi** [comment]
i'll check this

**Comment by Vyyt02** [comment]
Sorry, what do you mean by medic? You mean if there is a unit with the medic promotion next to the horseman it can heal the horseman even if no horses are available?

Maybe I do not understand the way it should work - I thought when I do not have enough of the strategic resource, none of the units requiring it heal under any circumstances - am I wrong?

**Comment by ilteroi** [comment]
you're right - i misread the code, medic shouldn't work either. which means i'm out of ideas.

**Comment by Vyyt02** [comment]
Hmm, so maybe it is one of the mods I am using along with VP ...

When I get some free time, I will try to simulate the situation with IGE in pure VP and let you know how it goes.
