### ISSUE TITLE
Can't end turn

### ISSUE THREAD

**Issue by Palid22** [LoneGazebo/Community-Patch-DLL#3837]
_1. Mod version (i.e Date - 4/23):_ 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ I just recently started using this mod and after a random amount of turns, usually within 60 it just stops letting me end my turn and the button does absolutely nothing. yes I've also tried saving and restarting it does nothing. please help! thank you

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Infixo** [comment]
Are you aware that you have not provided any useful information to help you? No save file, no logs, no mods’ list. Not even VP version.

**Comment by Palid22** [comment]
Yes, but I don't know how to check what version it is, I'm just using VP with no EUI.

**Comment by Palid22** [comment]
[Catherine_0022 BC-2680.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1621318/Catherine_0022.BC-2680.zip)
