### ISSUE TITLE
Possible to make SCIENCE_FLAT_BONUS etc. modular?

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3838]
Would it be possible to allow access to the SCIENCE_FLAT_BONUS defines for a new City-State type? CBO uses this but it is currently tied to militaristic city-states.

Additionally, would it be possible to replicate the Food methods for Production, so that a Production type could also be created? I attempted to fork the repository and duplicate everything but this resulted in some crashes and tbh I have no idea what I'm doing in the DLL :p 

If either or both are too much hassle, then I can use dummy buildings, but I thought I'd ask beforehand in case it was a simple enough request.

Thanks for any help.

**Comment by LoneGazebo** [comment]
Well the CS types are technically hard-coded, but if you tell me what/how many types you want I can try adding some new enum types in. 

I could also maybe do a lua hook where a civ looks for yields from minors? Would that be easier?

G

**Comment by JFDaly** [comment]
There would be three, but only two would need support since the third is a special case applying to only one City-State. That's, Industrious (MINOR_CIV_TRAIT_INDUSTRIOUS) and Scholastic (MINOR_CIV_TRAIT_SCHOLASTIC).

Yeah, that'd would probably be better. The third is meant to give Golden Age Points, and if that is done in a more modular way, then it'll all be easier.

**Comment by LoneGazebo** [comment]
Alright, so I did the lua stuff. Everything else is way too hardcoded. Here's how it will work:

Lua function: GetYieldPerTurnFromMinors(eYield, pCity) - this is for UI. pCity can be null - if null, the bonus is calculated at the player level. If not null, it is calculated at the city level.

GAMEEVENTINVOKE_VALUE - GetMinorCivAllyBonus(iBonusValue, MajorCivID, MinorCivID, MinorCivTrait, eYield, bool bIsCapital, bool bCityLevelBonus)
GetMinorCivFriendBonus(iBonusValue, MajorCivID, MinorCivID, MinorCivTrait, eYield, bool bIsCapital, bool bCityLevelBonus)

The function 'GetYieldPerTurnFromMinors calls these hooks every time it is requested - you can then use these hooks to set how/where the bonus is applied to the civ depending on whether or not pCity is defined in the UI lua function and/or the Lua hook.

Make sense?

**Comment by JFDaly** [comment]
Yeap, that makes sense. Awesome, thank you.

**Comment by LoneGazebo** [comment]
Let me know if this does/does not work, I did not test it. :)

**Comment by JFDaly** [comment]
Hm, okay, so I'm not quite clear on how it works after all.

It seems that player:GetYieldPerTurnFromMinors() won't allow null for pCity, as the method returns the complaint 'instance does not exist.'

And then I guess I'm not sure how to use the GameEvents.

I thought something like this:

```
function GetMinorCivFriendBonus(playerID, minorID, minorTraitID, yieldID, value, isCapital, isCityLevelBonus)
	print(playerID, minorID, minorTraitID, yieldID, value, isCapital, isCityLevelBonus)
	-- if yieldID == GameInfoTypes["YIELD_SCIENCE"] then
		print("yield is science")
		return playerID, minorID, minorTraitID, yieldID, 10, isCapital, isCityLevelBonus
	-- end
end
GameEvents.GetMinorCivFriendBonus.Add(GetMinorCivAllyBonus)
```

So, the event returns the value of the yield, but that doesn't seem to be the case; whether or not with the yield == science condition. I also tried just returning the value of the yield.

I'm probably missing something obvious, for which I'll blame the heatwave :p

**Comment by LoneGazebo** [comment]
GameEvents.GetMinorCivFriendBonus.Add(GetMinorCivAllyBonus)

Isn't this incorrect?

**Comment by JFDaly** [comment]
Yeah, I had another for Ally as well. Neither work, after retesting with the correct function name for Friend as well.

**Comment by LoneGazebo** [comment]
Fixed the null bug. Try this one: 
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1658434/CvGameCore_Expansion2.zip)

**Comment by LoneGazebo** [comment]
I also had an extra character in the linker string - removed it.

**Comment by JFDaly** [comment]
Kk, will do. Thank.

**Comment by JFDaly** [comment]
Awesome, thats all working then. Thank you again.

**Comment by LoneGazebo** [comment]
Both functions? Awesome.

**Comment by JFDaly** [comment]
Yeap, both.

**Comment by LoneGazebo** [comment]
Great! Let me know if you need anything else.
