### ISSUE TITLE
Few small bugs I found

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#3839]
1. Mod version: Beta 1-8 and earlier
2. Mod list: none
3. Error description: few small bugs or inconsistencies I found. Below there's code I created to repair it.
List of bugs:
- double Siege Inacuracy promotion on Field Gun,
- double Extra Sight promotion on austrian Hussar,
- 4 buildings had ConquestProb > 0 even if they have NeverCapture = 1,
- 9 buildings had NeverCapture = 0 even if they have ConquestProb = 0,
- 3 missing texts: 
-- TXT_KEY_AIR_STRENGTH_DEFENSE, 
-- TXT_KEY_EUI_BUILDING_SUPPLY_CAP_LOCAL,
-- TXT_KEY_EUI_BUILDING_SUPPLY_CAP_GLOBAL,
- database.log missing landmark values.

I also noticed that:

- Venice Custom House, Eki and Encampment have 15 Production for removed jungle instead of 20 and 20 Production  for forest instead of 30
- Embassy has value 0 Production for everything
- Polder has remove forest time 3 turns instead of 4
- Encampment and Eki has remove jungle 7 turns instead of 5 like all
- Encampment and Eki has remove forest 4 turns instead of 6 like all

4. Steps to reproduce: load VP
5. Code:
[Fix.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/1624152/Fix.txt)

Hope this helps.
Adam

**Comment by LoneGazebo** [comment]
Danke!
