### ISSUE TITLE
AI is cheating with purchases

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#384]
![8930_2015-06-29_00004](https://cloud.githubusercontent.com/assets/1131228/8430585/0377696a-1f4c-11e5-88ae-eec15ba6c33f.png)
That city had walls built around 2-3rd turn after it was founded.

**Comment by LoneGazebo** [comment]
Why is that cheating?
G

**Comment by Radost** [comment]
Because there is now way for player to build walls in such a short span?

**Comment by LoneGazebo** [comment]
I wrote the code for the purchase system, I can guarantee that the AI isn't cheating.
G

**Comment by LoneGazebo** [comment]
#if defined(MOD_BALANCE_CORE_BUILDING_INVESTMENTS)
										if(MOD_BALANCE_CORE_BUILDING_INVESTMENTS)
										{
										const BuildingClassTypes eBuildingClass = (BuildingClassTypes)(pkBuildingInfo->GetBuildingClassType());
										pLoopCity->SetBuildingInvestment(eBuildingClass, true);
										}
										else
										{
#endif
										pLoopCity->CreateBuilding(eBuildingType);
										pLoopCity->SetPurchaseCooldown(pkBuildingEntry->GetCooldown());
}

**Comment by Radost** [comment]
And I saw walls built on the 2rd turn after settling.

**Comment by DanteValerian** [comment]
Have you considered that maybe the AI built the city on a forest, getting a pile of production that turn? Combined with investing, it is possible. If they have the +15% production from investment policy from Industry, then you can easily get walls up in one turn on a new city.

**Comment by Radost** [comment]
There was no forest.
