### ISSUE TITLE
Monopoly percentage change

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3840]
_1. Mod version (i.e Date - 4/23): 1-8
_2. Mod list (if using Vox Populi only, leave blank): none
Something that boggled my mind from the first day of using VP: having >100% of resources. 
![monopolyissue](https://user-images.githubusercontent.com/25866684/34850052-63f1693a-f71c-11e7-8433-d860a75814bf.jpg)

Ofc I know why it is like that in terms of mechanics, but imho they should be corrected. Unless there is some deep logic and meaning that I don't see - I have changed it to work as it should imho: percentage is calculated against all "activated" resources in the world. Example. We have 8 on the map of which 6 are connected and 5 from other means (GA, CS, bonuses, etc.). The percentage will be calculated not against 8 but against 11. It wil never be >100%.

**Comment by LoneGazebo** [comment]
Don’t. That screws the utility of the EIC.

**Comment by Infixo** [comment]
In what way? Balance or CTD?

**Comment by LoneGazebo** [comment]
Balance. The whole point of the EIC is to let you secure or maintain a monopoly by going over 100%.

**Comment by Infixo** [comment]
You can secure monopoly by going >50%. EIC is still good about it.
As a nice bonus, this allows for a real fight about monopoly, since the percentage may change as more copies appear in the world. It means that you can actually loose one if other civ will "generate" more of a given resource.

**Comment by LoneGazebo** [comment]
Don’t mess with this, please. There’s no need.

**Comment by Infixo** [comment]
Put it on hold then. I’ll run the idea on the forum, maybe there’s really no need.

**Comment by Infixo** [comment]
You pulled my changes into master but this revert didn't make it. It is not optional yet, so it needs to be reverted.
