### ISSUE TITLE
interaction between inca and neuschwanstein

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3841]
macchu piccu has built neuschwanstein:

![image](https://user-images.githubusercontent.com/1358966/34864135-118ca98c-f773-11e7-91f3-d3462250aa37.png)

small issue, but would it be possible to put neuschwanstein on a tile which is not the city tile?

i assume the same would apply if macchu piccu built macchu piccu :)

**Comment by LoneGazebo** [comment]
Unfortunately the art code is hard-coded. :(
