### ISSUE TITLE
Settler Option in CommunityOptions Not Working

### ISSUE THREAD

**Issue by Questdog** [LoneGazebo/Community-Patch-DLL#3842]
_1. Mod version (i.e Date - 4/23):_1/8

_2. Mod list (if using Vox Populi only, leave blank):_Civ_Linked Great Generals (v11), Contextual Unit Names (v2), Contextual Unit Names-UI Add On (v1), Ethnic Units (v31), FlagPromotions (v7), Global- Coastal Waters Only (v2), Global-Units Awake In Danger (v2), InfoAddict (v22), Mechanized Infantry with Soldiers, Resized (v2), Religion-Recurring Purchase Notify (v1)

_3. Error description:_ Setting SETTLER_COMMUNITY to 0 in CommunityOptions.sql does not remove Pioneers from the game.  It only allows Settlers to still be built after Pioneers are researched.  

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
yeah, that's an outdated option. it is obsolete and shouldn't be used.
