### ISSUE TITLE
Hun Horsemen Captures Two Barbarians in 1 Attack

### ISSUE THREAD

**Issue by grmagne** [LoneGazebo/Community-Patch-DLL#3845]
_1. Mod version 1-8

_2. Mod list (if using Vox Populi only, leave blank):_
(9) Wonders Expanded (v1)
InfoAddict (v22)
Tectonic Map Script (v4)

_3. Error description:_ 
I've captured 4 different barbarian encampments using a Hun Horseman. Three out of four times the horseman captured two pieces in a single attack. I think what's happening is that it captures the unit (horseman ability) and then captures it again in the encampment (Hun UA ability). One of the captured units is always damaged and the other is completely healthy.

_4. Steps to reproduce (optional):_

**Comment by Infixo** [comment]
I managed to replicate it. It's random ofc, I had to clear 3 camps and the 4th one spawned 2 converted Brutes.
The problem is with clashing promotion Coercion and the Hun's trait. When an encampment is attacked, in the first phase (combat), the Coercion is activated here (CvUnitCombat):
```
else if (iAttackerTotalDamageInflicted >= iDefenderMaxHP && kAttacker.IsCaptureDefeatedEnemy() && kAttacker.AreUnitsOfSameType(*pkDefender)) 	{
			int iCaptureRoll = GC.getGame().getJonRandNum(100, "Capture Enemy Roll");
			if (iCaptureRoll < kAttacker.GetCaptureChance(pkDefender)) {
				bAdvance = false;
				pkCombatInfo->setDefenderCaptured(true); } }
```
The unit is marked for delayed death and during this process it is "recreated" as a captured unit.
But then the the game goes into trait checking in CvUnit:
```
// Is there a camp guard that will convert to our side here, if so have special routine to handle it
if (!kPlayer.GetPlayerTraits()->CheckForBarbarianConversion(this, pNewPlot))
```
The camp is cleared and somehow after that another unit is created. I can't locate an exact place however :(

**Comment by LoneGazebo** [comment]
It's not technically a bug, as you get the extra unit for taking the camp, not killing the unit. So it isn't duplicating, you're just getting a coercion unit AND a camp unit.

**Comment by Infixo** [comment]
Yup. Makes sense. Maybe some clarification in Trait description would make it less confusing then. Like „clearing a barbarian camp may grant an additional unit”. And lower the percentage maybe... those units really spawn fast if you are lucky.

**Comment by LoneGazebo** [comment]
It is relatively rare to have horsemen clearing camps anyhow. I don't think it's an issue TBH.

G

**Comment by Infixo** [comment]
Not so rare if they make it to GitHub...

**Comment by TechpriestEnginseer** [comment]
It's 1 player. Not several threads of DEFENSE PROCESS OP TOO MUCH.

**Comment by Infixo** [comment]
You don’t really think that VP is played only by that 50+ people that are active on forum and GitHub, do you?
