### ISSUE TITLE
Workers duplicate when captured

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#3848]
_1. Mod version (i.e Date - 4/23):_ 
1/3

_2. Mod list (if using Vox Populi only, leave blank):_
![capture](https://user-images.githubusercontent.com/19291347/34910606-b7866256-f886-11e7-9263-2384d5e9fab2.PNG)

_3. Error description:_ 
Workers duplicate when captured (possibly on war dec?).

_4. Steps to reproduce (optional):_
Move my worker under morrocan landship.  Start war with Morroco.  Worker turns into a ton of workers.

---------------------------
[Logs (2).gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/1628802/Logs.2.gz)

**Comment by MoiMagnus** [comment]
This is a known bug, but we failed to replicate it last time it was raised.
If you have a save from just before the bug, it could help.

**Comment by jimmymcperson** [comment]
The save is included in the archive file

**Comment by LessRekkless** [comment]
Likely related to https://github.com/LoneGazebo/Community-Patch-DLL/issues/3762

**Comment by LoneGazebo** [comment]
I witnessed this yesterday when a paratrooper dropped on a unit and captured it, but I couldn't figure out why. @Infixo @ilteroi any ideas?

**Comment by Infixo** [comment]
I can't paradrop on a unit...

**Comment by LoneGazebo** [comment]
Paradrop + move, I guess.
