### ISSUE TITLE
Unreasonable peace treaties from AI

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#385]
They tend to declare a war on whim, but agree to peace only after I destroy all of their forces, even if their country is on other side of the globe.
Otherwise they will have deals like this:
![8930_2015-06-29_00010](https://cloud.githubusercontent.com/assets/1131228/8430713/e0d1a3c0-1f4c-11e5-93dc-bfd4a4cb11f1.png)

**Comment by LoneGazebo** [comment]
I'll take a look.
G
