### ISSUE TITLE
Missle Cruiser lost missiles when capture a city

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3850]
_1. Mod version (i.e Date - 4/23):_
1-8

_3. Error description:_ 
After liberating a CS, missile cruiser lost missile :(
See such thing on previous versions too.

**Comment by LoneGazebo** [comment]
@ilteroi possible to have cargo not be lost during a melee move like this?

**Comment by ilteroi** [comment]
cannot reproduce.

![image](https://user-images.githubusercontent.com/1358966/35198028-f77a70e2-fee8-11e7-85e4-78d82367d4e9.png)

**Comment by ilteroi** [comment]
oh. i didn't test liberation ...
