### ISSUE TITLE
Civilopedia: Diplomacy Promotions

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3851]
_1. Mod version (i.e Date - 4/23): 1-14
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 
The Diplomacy Promotions are listed in Shared Promotions section. The Promotions.xml file which is installed into MODS is different that the GitHub file Community-Patch-DLL/CSD for CBP/Promotions/Promotions.xml. The first puts them into Shared, the latter into Diplomacy.

**Comment by Infixo** [comment]
@LoneGazebo Bump
There is another file, ImprovementText.xml that is also different from master. There is a corrected text for modifier. Release version of VP still has an old text.

**Comment by LoneGazebo** [comment]
I'll make a push of CSD.

**Comment by LoneGazebo** [comment]
Done.

**Comment by Infixo** [comment]
Done. I took CSD stuff and re-apply those changes. They are in ByInfixo.

**Comment by LoneGazebo** [comment]
okies
