### ISSUE TITLE
AI bonus yields

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3853]
so i've tried a advanced start again (prince, medieval era) .. and it seems impossible to keep up with happiness. the thresholds are just too high. did you change anything there?

anyway it turns out, about half of all AI cities have really impressive food yields on their city plots.

![image](https://user-images.githubusercontent.com/1358966/34920161-9ba594e2-f96e-11e7-9861-3fba8e2aad3f.png)

then there's science and GAP (assumed to be from artistry) but they seem to vary from turn to turn:

![image](https://user-images.githubusercontent.com/1358966/34920122-d5589b9a-f96d-11e7-9d97-ba45cbbc7b03.png)

![image](https://user-images.githubusercontent.com/1358966/34920233-bdc6d292-f96f-11e7-97f4-6e97dea7e5f2.png)

or maybe that's just a graphical glitch? can anyone confirm?

**Comment by ziadb** [comment]
I notice they have 6 artistry. Wouldn't that provide the science and tourism you see in the impressive cities?

Did you start the game in Medieval?

**Comment by ilteroi** [comment]
haha. you're right, science and GAP are coming from artistry policies. still doesn't explain the food or why the yields seem to come and go from turn to turn and from city to city. but maybe that's simply a graphical glitch.

 i'll edit the post to reduce confusion.
