### ISSUE TITLE
Minor polish request

### ISSUE THREAD

**Issue by aldebaran1997** [LoneGazebo/Community-Patch-DLL#3854]
Even though grocer comes at Renaissance era, its icon looks like kinda modern supermarket and it doesn't fit in with other buildings.
Also in current civilopedia, some promotions' categories are messed up and very hard to track promotion tree.
It is really minor to post elsewhere, so posting here.

**Comment by Infixo** [comment]
Maybe try out this modmod by adan_eslavo https://forums.civfanatics.com/threads/promotion-overhaul-for-vp.626728/ .

**Comment by LoneGazebo** [comment]
A lot of buildings are not era appropriate in appearance. It’s fine I think.

**Comment by aldebaran1997** [comment]
So be it, if you say so.
Ty Infixo and G! You are always the best!
