### ISSUE TITLE
CTD Issues

### ISSUE THREAD

**Issue by jdoug312** [LoneGazebo/Community-Patch-DLL#3855]
_1. Mod version (i.e Date - 4/23):_
Jan 3rd

_2. Mod list (if using Vox Populi only, leave blank):_
Full Vox Pop + EUI
Community Events v4
Events and Decisions v14
C4DF Era Change
Faster Aircraft Animations v3
FlagPromotions v7
MC and LITE's Nubia v3
MC and LITE's Nubia CBO Compatibility v1
Quick Turns v10
RED Modpack v28
Tectonic Map Script v4
World Congress Reformation v5

_3. Error description:_ 
I've been having this issue across multiple versions. I've been experimenting with my mod list, reducing mods in order to find the culprit. No success yet, so it must be in one of these (my core list of mods). I've experienced this with AND without: Red Modpack, Tectonic, presumably eliminating those as possibilities. **TYPICALLY the CTD issues** (CTDs happen during my turn at random but frequent intervals come late game, as well as on load after a while) **are paired with graphic glitches as well.**  I haven't had this problem yet this game, just the CTDs.

_4. Steps to reproduce (optional):_
Load up game, end turn. If the CTD has not happened this turn, it is basically guaranteed to happen the next (always happens for me).

---------------------------
Supporting information:

[APP.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1629927/APP.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1629928/Database.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1629929/Lua.log)
[modding.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1629930/modding.log)
[net_message_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1629931/net_message_debug.log)
[stopwatch.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1629932/stopwatch.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1629933/xml.log)
[xml-perf.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1629934/xml-perf.log)

Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

Not attaching, says "We don't support that file type"

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): 

Same issue as above

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
I've not loaded your game, but if it is post-industrial era, here is a possible origin of the crash : 
+ VP ask for a lot of resources, particularly in late game
+ Civ 5 is 32-bit, meaning that it cannot use the full power of your installation
+ Mods such as 2K-terrain-textures, RED, flag-promotion (surprisingly), ...,  ask for a lot of resources too
=> Memory overflow => Graphical glitch and/or CTD, depending of the computer (so mostly not fixable)

**Comment by Vyyt02** [comment]
Mind posting a screenshot to find the glitches? I was having similar problems post-industrial on large Tectonic with RED and FlagPromotions in summer. My screen was getting stuck, mouse cursor creating funny trails or getting CTDs after a few turns after a reload. Then I got rid of RED and FlagPromotions and managed a game until Modern era without any problems. Mind you I have quite a powerful machine. So what Moi Magnus says is probably the cause of your problems. 
I know it is just 1 game, but I really think it solved my problems. I got too busy and when I finally got some time and started playing again around Christmas, my hard drive died. I already have a new one, am almost in industrial in my current game so far so good. Will let you know when I advance further if I get any problems.

**Comment by LoneGazebo** [comment]
RED + Flag Promotions + VP is essentially a no-go. Civ can't support the memory overhead.

**Comment by jdoug312** [comment]
Thank you all for the insight. I will run a new game without Flag Promotions and RED. Would you like me to report back in this thread if the issues linger in the new game, given that it'll be a new version? Sounds like Vyyt02 plans to comment in this thread about his game.

MoiMagnus it has indeed always been post-industrial, so it sounds like you are spot on. Terrain textures is a must have for me, so the concessions will have to be from RED (unfortunately) and FlagP.

Vyyt02, the CTD issues popped up before the glitches did, so no screenshots unfortunately. I can certainly describe them though: Theodara was frankly scary for one; the skeleton of her jaw was visible, her eye was a different color (forget which exactly, but it wasn't something you'd miss lol). Wrongly colored backgrounds for Brazil, Inca, Maya etc (like red background, unable to see the characters sometimes, whole screen painted a different, solitary color at other times).

Gazebo, sucks to hear, but great to know; thank you. Flag Promotions isn't a must have for me if that's the case. Do you know offhand if Red+VP alone would be problematic? I will of course test this out myself but I figured I'd ask to maybe save a future game.

**Comment by Vyyt02** [comment]
@LoneGazebo if you want to make sure to get in trouble you can also play on huge Tectonic (which is huger than normal huge) with the above mix of mods :-)

@jdoug312 Yeah, this sounds like problems with memory. You can also try lowering the graphics and removing RED - these may let you play a bit longer, but then the glitches will re-appear. I am personally most sad about the FlagPromotions, I find them extremely useful. The good news for you is that, **I think**, RED is save-compatible, so you should be able to start the game with RED and then turn the RED off once you notice something odd. Also, see the mods compatibility thread - if I remember well, you have to delete something about the riflemen (= the WWI infantry) or you will get a CTD.

Good luck!

Oh, and my games usually take weeks or even months to finish, so do not wait for me and play :-) I will let you know if I get to Modern or Information era safely, but it may take some time form me to get there.

**Comment by ryanmusante** [comment]
I'm glad I found this information because the graphical glitches I was experiencing on a previous game were limited to the mini-map. I don't have screenshots because I deleted the save out of frustration. The colors would change between each turn and strange lines would show in place. And my mod list has been similar RED, FP, 2K Textures. So, I will do away with RED and FP for future games. Although, I wish I knew beforehand if removing RED would be enough.

**Comment by jdoug312** [comment]
Just wanted to check in. I just finished a Jan 14 game without RED or FlagPromotions. The game ended on turn 398 by science. I had a couple of random ctds, but nothing like before and no graphical glitches. I'll def keep playing this way for a while, maybe try to re-add RED at some point to test, but I'm content for now.

**Comment by LoneGazebo** [comment]
Cool.
