### ISSUE TITLE
governor starves city after building a settler

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3858]
![image](https://user-images.githubusercontent.com/1358966/34956095-e0efd6b6-fa27-11e7-941d-ee86255819ec.png)

this is with the default governor. after changing the emphasis (any setting works) we get this:

![image](https://user-images.githubusercontent.com/1358966/34956145-27019342-fa28-11e7-82a3-a20edd46908e.png)

**Comment by LoneGazebo** [comment]
Odd.

**Comment by phantommaxwell** [comment]
I would "starve" the city when building Settlers as it would train the settler faster working production than food tiles.  Was the Governor starving the City while training the Settler?

**Comment by LoneGazebo** [comment]
City can't starve, technically, while creating a settler, as all food goes to production. My bet is that the governor isn't resetting from food production
