### ISSUE TITLE
Trade Caravan not displaying routes properly

### ISSUE THREAD

**Issue by bridger15** [LoneGazebo/Community-Patch-DLL#3859]
_1. Mod version (i.e Date - 4/23):_
1-14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
There seems to be something wrong with the trade/caravan system in the most recent version.  I have a single trade caravan currently trading between Soul and Brandtford.  This information is being displayed properly in the trade tool tip on the top right and in the "Your Trade Routes" tab: https://i.imgur.com/nZxprhY.png

However, the "Available Trade Routes" tab has an issue where the Soul to Brandtford route is not listed (normally it would be listed along with the number of turns left): https://i.imgur.com/zxUlLvE.jpg

In addition, I have just moved a caravan to Buson this turn and it does *not* give me the option to setup a route from Buson to Brandtford (despite the fact that this exact route is displayed as the most valuable in the above screenshot): https://i.imgur.com/kjaGNxQ.jpg

Buson is, in fact, many hexes *closer* to brandtford along a road (you can see the other route in the above screenshot) so distance does not appear to be the problem factor.

_4. Steps to reproduce (optional):_
Save File: https://drive.google.com/open?id=1xapXRvzDMxWjZceLgY0u3ujAUZHsXWSV

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@Infixo is this related to your additions?

**Comment by Infixo** [comment]
I don’t think so. Timers are calculated correctly and I didn’t touch anything else.
I have registered exactly the same issue some time ago #3779 . However, after some deep investigatuon I found out that it is entirely possible that an active route is not listed in Available Routes. See the post for details.
And 2nd part is obvious - there is already a route to Brandtfort, so you cannot get another from Busan, that is why it is not listed in the chooser.

**Comment by Infixo** [comment]
Basically, Available TR uses a function that recalculates available routes each time it is called. If Seoul to Branddort is not listed, it means that NOW you woudn’t be able to establish it, given the chance again. For many reasons: danger zone, barbarians, pillaged road, etc.
Also, once the TR is establish, this effect is never checked again. The route is active until completion or somebody pillages it.

**Comment by bridger15** [comment]
Was that a change in one of the recent patches?  It used to be that you could only have one route between any two cities (so you could only have one route from Soul to Brandfort), but now you can only have a single route to any given city?  Does this also apply to internal trade routes?  Can in only have a single trade route pumping up a newly started colony with hammers/food?

**Comment by Infixo** [comment]
@bridger15 You may try this: https://forums.civfanatics.com/threads/ui-filters-in-trade-route-overview.625570/
