### ISSUE TITLE
Archer ZOC giving Free Movement to Enemies

### ISSUE THREAD

**Issue by Questdog** [LoneGazebo/Community-Patch-DLL#3860]
_1. Mod version (i.e Date - 4/23):_1/14

_2. Mod list (if using Vox Populi only, leave blank):_Contextual Unit Names (v2), Contextual Unit Names-UI Add On (v1), Ethnic Units (v31), FlagPromotions (v7), Global- Coastal Waters Only (v2), Global-Units Awake In Danger (v2), InfoAddict (v22), Mechanized Infantry with Soldiers, Resized (v2), Religion-Recurring Purchase Notify (v1) UI - Improved City View (Vox Populi EUI) (v 10)

_3. Error description:_ 
I am seeing my archers are giving opposing units an extra move.... Instead of stopping them due to ZOC (which I think they should not have), they are giving them an extra move as if the ZOC tile is costing 0 MP to move through. This should not be; the enemy should still have to pay the normal costs of movement through the tile.
 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi thoughts?

**Comment by ilteroi** [comment]
highly improbable ... also hard to debug without a savegame or at least a screenshot

**Comment by MoiMagnus** [comment]
> How do you take a screenshot of that? 

Take a screenshot before and after the bugged movement.

> Am I the only one who is seeing this?

This is the first time someone report this. So it is either a mod conflict on your side, either a bug introduced recently. People rarely use the ZOC of archers since they are easily killed, so you may be the first one to see this bug.

**Comment by ilteroi** [comment]
cannot reproduce. and there's nothing in the code that differentiates and archer's ZOC from any other unit's ZOC.

![image](https://user-images.githubusercontent.com/1358966/35058197-79385c14-fbb7-11e7-8e69-003a7407fa8d.png)

however some units have an ignore ZOC promotion. maybe that's the case here?

**Comment by Questdog** [comment]
Okay, I am not seeing this in my current game.  In my previous game (I am not hallucinating or lying) it happened twice.  Once when I was trying to catch an unescorted settler in a heavily forested sector, I had him caught between two archers but he slipped right between them and moved two hexes through forest.  The other time I was trying to catch a heavily wounded spearman with an archer in the same forest sector and had him caught up against a wall of mountains but he slipped right by the arches moving two hexes through forest to save his skin.  I use Flag Promotions and checked and he had no promotions that would either allow him to move two hexes through forest or ignore ZOC.  The settler had no promotions at all.  If I ever see this again, I will try to make a save and/or a video of it.

So archers are supposed to exert ZOC on nearby hexes the same as melee units?
