### ISSUE TITLE
Caravans and Cargo Ships Counting as Military Units

### ISSUE THREAD

**Issue by Questdog** [LoneGazebo/Community-Patch-DLL#3861]
_1. Mod version (i.e Date - 4/23):_1/14

_2. Mod list (if using Vox Populi only, leave blank):_Contextual Unit Names (v2), Contextual Unit Names-UI Add On (v1), Ethnic Units (v31), FlagPromotions (v7), Global- Coastal Waters Only (v2), Global-Units Awake In Danger (v2), InfoAddict (v22), Mechanized Infantry with Soldiers, Resized (v2), Religion-Recurring Purchase Notify (v1) UI - Improved City View (Vox Populi EUI) (v 10)

_3. Error description:_ Cargo Ships and Caravans are counting against the military unit cap

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Questdog** [comment]
Also Fishing Boats are counting as Military Units

**Comment by Infixo** [comment]
See also #3818 .

**Comment by ryanmusante** [comment]
Aren't CUN and EUI are incompatible because the edit the same lua? Not that I am saying this particular problem could be associated.

**Comment by Questdog** [comment]
CUN overwrites the EUI and has a different unit view, but that does not mean they are incompatible in the sense that they will not work together.  I think the version I use was made specifically to be used with EUI.
