### ISSUE TITLE
Slow Unit Production Epic Industrial

### ISSUE THREAD

**Issue by muarB** [LoneGazebo/Community-Patch-DLL#3862]
_1. Mod version (i.e Date - 4/23):_

1/8
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Unit production takes longer than buildings.  In a large city with factory, windmill, forge, workshop etc I can build an Arsenal in 17 turns and a Rifleman in 18 turns.  This is epic speed and has happened in several of my games.  Seems to happen starting in industrial era.  Makes sense to only purchase units which is limiting when trying to upgrade units as well.

_4. Steps to reproduce (optional):_
Most of my games and all recent patches have really long production values for units.  This happens even when I'm at positive happiness.
I can include some saves but not sure how to make them zip files.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Ahmad al-Mansur_0486 AD-1896.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1633589/Ahmad.al-Mansur_0486.AD-1896.zip)
[Ahmad al-Mansur_0445 AD-1855.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1633590/Ahmad.al-Mansur_0445.AD-1855.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![units](https://user-images.githubusercontent.com/23019463/34970511-8fbb10ce-fa29-11e7-830d-0a11ac58cd12.png)

**Comment by Infixo** [comment]
Arsenal costs 1000 hammers, Rifleman costs 900. If you have a Windmill, then producing buildings is 15% faster. And there are many other modifiers that can be activated. It is entirely possible that you can build Arsenal faster that Rifleman. Check the tooltip for production yield, it will tell you which modifiers are used when producing a specific unit or building.

**Comment by muarB** [comment]
Maybe it's working as designed.  If that's the case it should be looked at.

Seems wrong I could spend 25 turns to build a Tri-plane which can die versus 21 turns to build a permanent Military Academy.  If I built a Tri-plane that's putting my city 25 turns behind in building city infrastructure.  The Tri-plane should be taking somewhere between 5 and 10 turns in a high population city with all the production buildings present.  Seems bugged.  Like maybe unit production is not getting proper production modifiers.

So that means just purchasing new units.  If you have an 80 unit military that means no upgrades for veterans.

A second buggy thing I saw was I could purchase Archaeologists with faith even though my religion doesn't have that ability.  I continued playing the game into the 1900's and that ability disappeared.  Not sure how I was able to purchase them in the mid 1850's.

**Comment by Infixo** [comment]
Cost of things is a balance duscussion, not an error. Better take this topic to forum.
Archaeologists - just open a new ticket, with some usual supporting material.

**Comment by muarB** [comment]
When I can build Manhattan Project twice over in my capital before a Tri-plane in one of my good cities, that's an error until someone proves otherwise.  I can research a tech in 25 turns before completing said Tri-plane.  If you want this ticket removed go ahead and get it removed.
