### ISSUE TITLE
Small bug in CvMinorCivAI::DoFirstContactWithMajor()

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3865]
_1. Mod version (i.e Date - 4/23): 1-14
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 

In CvMinorCivAI::DoFirstContactWithMajor() there is at the end a piece of code that triggers Lua GameEvent:
```
if (MOD_GLOBAL_CS_GIFTS && MOD_EVENTS_MINORS_GIFTS){
// Send an event with the details
GAMEEVENTINVOKE_HOOK(GAMEEVENT_MinorGift, GetPlayer()->GetID(), ePlayer, iGift, iFriendshipBoost, 0, bFirstMajorCiv, false, szTxtKeySuffix);}
```
However, it seems that MOD_EVENTS_MINORS_GIFTS is somehow connected to main Option "Use Events System". When you turn it off, this flag is set to 0 and the Lua GameEvent will not trigger despite the fact that the gifts were actually made.

Is it bug or (somehow) intended?

**Comment by LoneGazebo** [comment]
There's no connection between those functions.

**Comment by Infixo** [comment]
So it's set to 0 by default? Weird.

**Comment by Infixo** [comment]
@LoneGazebo I have a question, little offtopic.
Do you know how to make more tables load into GameInfo? I’ve looked through the code and I cannot find anything related to this.

**Comment by LoneGazebo** [comment]
LuaEnums.h

**Comment by LoneGazebo** [comment]
It’s in the GameUtils folder IIRC

**Comment by Infixo** [comment]
I found that one, but it only deals with enumerations. So, it creates tables like DomainTypes, so you can the use DomainTypes.DOMAIN_AIR in Lua code. But there's nothing about "real" tables and GameInfo.
My suspision is that it happens somewhere in game engine. I don't think any new table added in CP is actually available in GameInfo, only vanilla tables are there.

**Comment by LoneGazebo** [comment]
Mm, I see what you're wanting. Yeah, there's a reason the lua hooks exist - other tables are, I believe, 'parsed' in the net dll that we lack access to.
