### ISSUE TITLE
Venice chooses Progress

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3867]
_1. Mod version (i.e Date - 4/23): 1-14
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:
Venice chooses Progress. From PolicyAILog:
019, Venice, Branch 1, 190
019, Venice, Branch 0, 187
019, Venice, Branch 2, 186
019, Venice, CHOSEN, Branch 1
The differences in valuation are very small and this might be due to the fact that Venice unique Trait's features are ignored by valuation routine (CvPolicyAI::WeighPolicy). Basically:
- IsNoAnnexing
- IsIgnorePuppetPenalties
- GetNumTradeRoutesModifier
are not used to determine Civ's "style". IsExpansionist, IsWarmonger, IsNerd, IsDiplomat, IsSmaller, IsTourism, IsReligious - none of them uses those 3 checks.

If we agree where to add them, I can fix it. I propose:
- IsNoAnnexing - to IsSmaller
- IsIgnorePuppetPenalties - to IsExpansionist
- GetNumTradeRoutesModifierto - to IsDiplomat

**Comment by LoneGazebo** [comment]
Makes sense to me. I forgot about poor Venice when doing AI selection criteria. :)

**Comment by Infixo** [comment]
Ok, after some testing I added IsIgnorePuppetPenalties to IsWarmonger and only when !IsNoAnnexing. Otherwise Venice got both IsExpansionst and IsSmaller, which is contradictory a bit and actually started to choose Authority every time. So now, if somebody will create a Trait that has IgnorePuppetPenalties=1 but NoAnnexing=0, it will be recognized as Warmonger which makes more sense. Expansionist is more focused on internal growth, as I see in the code (tile purchase, worker rate, etc.)
After changes Tradition is valued usually the most, with Liberty at 2nd place.
