### ISSUE TITLE
City View quirks

### ISSUE THREAD

**Issue by ricanuck** [LoneGazebo/Community-Patch-DLL#3868]
_1. Mod version (i.e Date - 4/23):_1.14.2.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
City View includes a purchase button with the "Finished X" display at bottom of production. Also, font is too small.

_4. Steps to reproduce (optional):_
Play.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@Infixo this your baby?

**Comment by Infixo** [comment]
Already fixed here https://github.com/Infixo/Community-Patch-DLL/commit/739a199aefa63ce03270961c0b8108984f0fd8a5.
The font will be smaller to fit Gold button for the first item in te queue, this is intended.
