### ISSUE TITLE
Game.CreateGreatWork Documentation

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#3869]
Game.CreateGreatWork(GreatWorkType, GreatWorkClass, PlayerTypes, EraTypes, szCreator)

- GreatWorkType: (May be direct or indirect, could possible duplicate Great Works be created because of this? Does the natural Great Works disappear when this is used? Who knows.)
- GreatWorkClass: Seems easy to utilize, just shouldn't have class mismatch with the type.
- PlayerTypes: I guess which player gets it. Better restrict it to major civilizations only. I wonder what happens when a slot is full? 
- EraTypes: Only relevant for those you find in sites.. but what if paintings were discovered in this type? Will investigate.
- szCreator: no clue, might fiddle with this.

Will be testing this out to see how it works since it technically exist in the system.

Can a Great Work disappear awkwardly as well? :thinking:

**Comment by LoneGazebo** [comment]
I have no idea...let me know what you discover.

**Comment by HungryForFood** [comment]
I went to take a look, and szCreator seems to be the name of the great person who created it. Here's the relevant code if you are interested.

Lua\CvLuaGame.cpp
```
int CvLuaGame::lCreateGreatWork(lua_State* L)
{
	GreatWorkType eType = (GreatWorkType)lua_tointeger(L, 1);
	PlayerTypes eOwner = (PlayerTypes)lua_tointeger(L, 2);
	EraTypes eEra = (EraTypes)lua_tointeger(L, 3);
	CvString szCreator = lua_tostring(L, 4);
	
	int iGWindex = 	GC.getGame().GetGameCulture()->CreateGreatWork(eType, CultureHelpers::GetGreatWorkClass(eType), eOwner, eEra, szCreator);

	lua_pushinteger(L, iGWindex);
	return 1;
}
```

CvCultureClasses.cpp
```
// Factory method to create a Great Work, returns index of the new work
int CvGameCulture::CreateGreatWork(GreatWorkType eType, GreatWorkClass eClass, PlayerTypes ePlayer, EraTypes eEra, CvString szCreator)
{
	CvGreatWork newGreatWork;
	newGreatWork.m_eType = eType;
	newGreatWork.m_eClassType = eClass;
	newGreatWork.m_eEra = eEra;
	newGreatWork.m_ePlayer = ePlayer;
	newGreatWork.m_iTurnFounded = GC.getGame().getGameTurn();
	newGreatWork.m_szGreatPersonName = szCreator;

	int iNumGreatWorks = m_CurrentGreatWorks.size();

	m_CurrentGreatWorks.push_back(newGreatWork);

	return iNumGreatWorks;
}
```
