### ISSUE TITLE
Weird farm on hill yields

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#387]
![8930_2015-06-28_00003](https://cloud.githubusercontent.com/assets/1131228/8431152/f9a56e46-1f50-11e5-8be3-23f83a0ad247.png)
![8930_2015-06-29_00003](https://cloud.githubusercontent.com/assets/1131228/8431158/0ccf8448-1f51-11e5-865d-46e4c4f52725.png)

**Comment by LoneGazebo** [comment]
It's because, IIRC, jungles aren't supposed to spawn on hills like that. Sounds like a mapgen bug (in short, the hill is being ignored).

G

**Comment by Radost** [comment]
![8930_2015-07-22_00007](https://cloud.githubusercontent.com/assets/1131228/8856280/4ecc766e-3183-11e5-8f42-77a5e1a21fb8.png)
Is it the same bug? Looks like communitas map needs some fixing then.
