### ISSUE TITLE
Arena high valuation

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3870]
_1. Mod version (i.e Date - 4/23): 1-14
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 
Spain's just settled a city and it started to produce Arena. Just to be clear - there are no Olives nor Perfume in the area.
```
111, Spain, Santiago, POST: Building, Arena, 228019, 13
111, Spain, Santiago, POST: Building, Granary, 135564, 4
111, Spain, Santiago, POST: Building, Baths, 76313, 18
111, Spain, Santiago, POST: Building, Forge, 74343, 13
111, Spain, Santiago, POST: Building, Market, 63590, 8
111, Spain, Santiago, POST: Building, Water Mill, 61370, 13
111, Spain, Santiago, POST: Building, Herbalist, 52795, 8
111, Spain, Santiago, POST: Building, Shrine, 19844, 4
111, Spain, Santiago, POST: Building, Monument, 10987, 4
111, Spain, Santiago, POST: Building, Council, 3555, 4
111, Spain, Santiago, POST: Building, Aqueduct, 2283, 18
111, Spain, Santiago, POST: Building, Walls, 1854, 8
111, Spain, Santiago, POST: Building, Barracks, 1768, 8
<units>
111, Spain, Santiago, SEED: 15953038917747410991, CHOSEN: Arena, Do not rush, TURNS: 13
```
I am tracking the problem in Sanity function.

**Comment by Infixo** [comment]
Seems that GetBuildingYieldValue for PRODUCTION returns 42750 and since this is a small city it gets multiplied by 5 later, giving 213750. Yup, Arena is crazy good production building...
The problem is here:
```
	//And here's what the value represents.
	//Era = higher era, less valuable in game.
	iActualIncrease = (iFlatYield * (100 - (iEra * 5)));
	iActualIncrease /= max(1, iDelta);
	iYieldValue += iActualIncrease;
```
Before that part iFlatYield is 450 (90*5 due to iDelta<0) and iDelta = -83. iEra = 1 and iFlatYield gets multiplied by 100, but there is a missing divisor iActualIncrease /= 100 to scale it back. iDelta comes in play only if >0 and that means that City produces much more yields than boosted value for that building, so basically it is not needed much.

**Comment by Infixo** [comment]
I think that could be the reason why there were all the time huge valuations, I gave some examples some time ago. After the fix valuations look much more reasonable.
```
111, Spain, Santiago, POST: Building, Granary, 3755, 4
111, Spain, Santiago, POST: Building, Monument, 2550, 4
111, Spain, Santiago, POST: Building, Herbalist, 2502, 8
111, Spain, Santiago, POST: Building, Market, 2479, 8
111, Spain, Santiago, POST: Building, Council, 2456, 4
111, Spain, Santiago, POST: Building, Arena, 2377, 13
111, Spain, Santiago, POST: Building, Shrine, 2267, 4
111, Spain, Santiago, POST: Building, Walls, 1868, 8
111, Spain, Santiago, POST: Building, Barracks, 1232, 8
111, Spain, Santiago, POST: Unit, Emissary, 1122, 9
111, Spain, Santiago, POST: Building, Forge, 948, 13
111, Spain, Santiago, POST: Unit, Work Boat, 847, 2
111, Spain, Santiago, POST: Building, Baths, 841, 18
111, Spain, Santiago, POST: Building, Water Mill, 711, 13
111, Spain, Santiago, POST: Building, Aqueduct, 534, 18
<units>
111, Spain, Santiago, SEED: 4073592712765301008, CHOSEN: Granary, Do not rush, TURNS: 4

```

**Comment by LoneGazebo** [comment]
Ahh, yeah, didn't bring it back out of the thousands, the /100 is missing. Good eye.

**Comment by Infixo** [comment]
As a side note, I think that valuation for Unique Buildings might be a bit too high. They get *10 somewhere at the end of the process and this really boosts them a lot. After fixing that /100 divisor valuations tend to end up in thousands (like 1-10 th.) *10 for UB puts them immediately at the top, even for fresh cities. I continued the game and noticed that in the next city Spain started with Mission (!) for 30 turns (!) It's her UB and was valued @21000+ There were nice valuations for Walls, Council, Monument, etc. but all in range 3000-7000. 
I would decrease that multiplier. No UB is "worth" 10x the normal building, I'd say *2 or *3 at most. What do you think?

**Comment by LoneGazebo** [comment]
The Mission is especially good for her early, though, due to the birth bonus.

**Comment by Infixo** [comment]
Sure, but waiting 30 turns to get it? She could build entire basic infrastructure in that time. Is it really worth x10 more?

**Comment by LoneGazebo** [comment]
Could scale it off population - so cities under 10 pop get an increasingly smaller bonus, up to x10 above 10 pop.

**Comment by Infixo** [comment]
Good idea. I'll try if pop < 10 then *pop else *10

**Comment by LoneGazebo** [comment]
Sounds good. 99% of the time you want a UB up ASAP.

**Comment by Infixo** [comment]
Works like a charm. Salamanca built Well (could be Granary), then Monument (again, Granary was 2nd) and then Mission for 16 turns. Was at 7 pop at the moment. Walls were 2nd.

**Comment by LoneGazebo** [comment]
Cool.
