### ISSUE TITLE
Defender of faith dont work for follower?

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3875]
_1. Mod version (i.e Date - 4/23):_
14/1

_2. Mod list (if using Vox Populi only, leave blank):_
no mods

_3. Error description:_ 
Maybe the same thing with crusader. See the same in December versions maybe. Don't work if is not the owner of holy city.
Or maybe I am wrong, but if someone has time to check... Maybe it is just EUI bug?

![20180121021758_1](https://user-images.githubusercontent.com/13381981/35189355-6e7c24e4-fe51-11e7-9502-1d4776872885.jpg)
![20180121021838_1](https://user-images.githubusercontent.com/13381981/35189356-6e99259e-fe51-11e7-8663-b10112b6d9e8.jpg)

Germany is the founder. All cities of Japan are the same religion, but don't see the bonus.

**Comment by TechpriestEnginseer** [comment]
I don't think Enhancer don't grant followers the benefits the founder do no?

**Comment by LoneGazebo** [comment]
It is a reformation. And I know whyyyyyyy. Fixed.

**Comment by bigcat88** [comment]
Great to hear that Crusader of Spirit and Defender of Faith will rise again )
Was very surprised in one game not to have bonus from Defender when i was not a founder :)

**Comment by LoneGazebo** [comment]
They work. It was just a UI issue.
