### ISSUE TITLE
Typo in Well Civilopedia entry

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#3876]
_1. Mod version (i.e Date - 4/23):_
1-14-1

_2. Mod list (if using Vox Populi only, leave blank):_
<>

_3. Error description:_ 
The Civilopedia states +1 Food per 5 citizens when it should be +1 Production per 5 citizens.

_4. Steps to reproduce (optional):_

![1-14-1 well typo](https://user-images.githubusercontent.com/34615525/35192208-c1b0c810-fe4a-11e7-87ff-a1cbd55fdca8.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by tu-79** [comment]
In fact, Gazebo showed a changelog where he said well was going to scale on food, and produce a little bit of production, but in game well is still like the old one.

**Comment by LoneGazebo** [comment]
It’s supposed to be production, for some reason my text didn’t update.

**Comment by Mitchsp** [comment]
Still happening with current version, showing Food instead of Production

![imagen](https://user-images.githubusercontent.com/13163824/35309934-38940cc4-00af-11e8-8517-81fd598e8e49.png)

**Comment by LoneGazebo** [comment]
'fixed for upcoming version'

**Comment by tu-79** [comment]
You sure you don't want the well scaling on food? That recurrent typo can't be a coincidence...

**Comment by LoneGazebo** [comment]
Positive.
