### ISSUE TITLE
city:GetNumGreatWorksFilled(slotType) request

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3877]
Could you add a **city:GetNumGreatWorksFilled(slotType)** method, that returns the number of Great Works of a specific type filled in a city? The only current method is GetNumGreatWorksInBuildings, and iterating through every building seems a bit much. And hopefully it'd work for custom Great Work slot types, as that is what I need it for.

Thank.

**Comment by LoneGazebo** [comment]
Done!

**Comment by JFDaly** [comment]
Hm, this doesn't seem to be working on the latest version. The method is there, just always returns 0 even when I definitely have filled great work slots in a city. Unless I'm using it wrong, as per below:

Players[0]:GetCapitalCity():GetNumGreatWorksFilled(GameInfoTypes["GREAT_WORK_SLOT_LITERATURE"])

**Comment by LoneGazebo** [comment]
Oh, duh, I'm a moron. I know why. I'll upload a DLL here for you, will hotfix the main DLL later.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1650886/CvGameCore_Expansion2.zip)

**Comment by JFDaly** [comment]
Excellent, thanks. That works now.

And one last thing. Could you please push **city:GetNumAvailableGreatWorkSlots(slotType)** to lua. That seems to be an existing method, and none of the BNW ones accept an argument.

**Comment by LoneGazebo** [comment]
Done!
