### ISSUE TITLE
crazy culture for morocco

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3878]
this might be more of a balance issue, but:

i tried to play a game with a culture-focused france (inspiration, some holy sites, artistry, chateaux, some conquests for great persons). but it turns out morocco beats me in culture-generation almost 3:2 (574 to 420 cpt to be precise).

next to the kasbahs, they have 8 traderoutes to cs allies which net them 16 cpt each. is that intended?

also, i get a lot of unhappiness from boredom. which shouldn't be an issue really - i'm second in culture and morocco has only 8 cities, which should affect the threshold. tech level is also quite similar. this makes me a bit suspicious.

**Comment by LoneGazebo** [comment]
I’m tweaking happiness for next release, but Morocco is a good culture civ. France is weaker until chateaus.

**Comment by ilteroi** [comment]
yeah, kasbahs > chateaux. but: from inspiration you get around 5 or 6 culture per turn per city (renaissance). that's not even half of what morocco is getting per trade route. seems extreme.

**Comment by LoneGazebo** [comment]
I think it's worth bringing up in Morocco's thread, see if anyone else sees it (also see if France needs love)
