### ISSUE TITLE
City Tile Management changes locked tile itself.

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#388]
http://steamcommunity.com/profiles/76561198009635802/screenshot/446203587829091200
In that city, I switched the citizen from working the marsh to hill to gain extra hammers.

http://steamcommunity.com/profiles/76561198009635802/screenshot/446203587829090762
After leaving the city screen, the city unlocked the citizen working the hill, going back to work the marsh.

Whenever the city has below 2 food, it happens. 

Also, in the last game, playing as China, a city with automatic management with priority in great person didn't work specialist slots. Instead, it works citizens as labors.

**Comment by LoneGazebo** [comment]
Odd, as I don't mess with forced citizens at all. I'll make a tweak to the AI logic for that and see if it fixes it.
G

**Comment by XplosiveLun** [comment]
Hi again, I'm here to give further information of this bug. My cities suddenly stop working on food tiles themselves and go into starvation. Happiness went from -50 to -100 in one turn because of "starvation".

Here's the screenshot. I will now try disabling other mods I have and experiment with it since it doesn't look like CP's fault.

I will open a new thread to catch attention if Lord G didn't read/reply 3 days later.

**Comment by XplosiveLun** [comment]
I'm sorry. I missed the 7-1 quick fix. Now the problem seems gone. 

Thank you Lord Gazebo.
