### ISSUE TITLE
Tradition neglected by AI

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3880]
_1. Mod version (i.e Date - 4/23): 1-14 with changes up to 1-20
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 
3 games, standard size, Communitas map, Emperor. All cases (but 1) Tradition is rated lowest by a large margin. That 1 case - India - barely made it to the top (234 vs. 232).
I haven't looked into that yet, but it looks like systematic error i.e scaler is missing somewhere? Simple *2 would put it in competetive range of other 2 branches.
```
010, Polynesia, Branch 2, 322
010, Polynesia, Branch 1, 320
010, Polynesia, Branch 0, 156
011, England, Branch 2, 465
011, England, Branch 1, 304
011, England, Branch 0, 142
012, Mongolia, Branch 2, 506
012, Mongolia, Branch 1, 314
012, Mongolia, Branch 0, 119
015, The Aztecs, Branch 2, 399
015, The Aztecs, Branch 1, 249
015, The Aztecs, Branch 0, 115
015, Korea, Branch 1, 213
015, Korea, Branch 2, 203
015, Korea, Branch 0, 148
016, Japan, Branch 2, 259
016, Japan, Branch 1, 230
016, Japan, Branch 0, 114
018, The Netherlands, Branch 1, 233
018, The Netherlands, Branch 2, 202
018, The Netherlands, Branch 0, 176
011, Sweden, Branch 2, 522
011, Sweden, Branch 1, 336
011, Sweden, Branch 0, 103
012, Denmark, Branch 2, 524
012, Denmark, Branch 1, 344
012, Denmark, Branch 0, 114
012, India, Branch 1, 248
012, India, Branch 2, 240
012, India, Branch 0, 221
012, China, Branch 1, 290
012, China, Branch 2, 279
012, China, Branch 0, 192
012, China, CHOSEN, Branch 1
014, Polynesia, Branch 2, 259
014, Polynesia, Branch 1, 237
014, Polynesia, Branch 0, 114
016, Egypt, Branch 1, 271
016, Egypt, Branch 2, 211
016, Egypt, Branch 0, 190
017, The Ottomans, Branch 1, 225
017, The Ottomans, Branch 2, 204
017, The Ottomans, Branch 0, 149
011, Ethiopia, Branch 1, 269
011, Ethiopia, Branch 2, 213
011, Ethiopia, Branch 0, 200
013, India, Branch 0, 234
013, India, Branch 1, 232
013, India, Branch 2, 232
013, Indonesia, Branch 2, 289
013, Indonesia, Branch 1, 288
013, Indonesia, Branch 0, 125
015, Korea, Branch 1, 232
015, Korea, Branch 2, 208
015, Korea, Branch 0, 152
015, England, Branch 2, 435
015, England, Branch 1, 278
015, England, Branch 0, 131
017, Rome, Branch 2, 406
017, Rome, Branch 1, 256
017, Rome, Branch 0, 135
018, Sweden, Branch 2, 514
018, Sweden, Branch 1, 340
018, Sweden, Branch 0, 128
```

**Comment by LoneGazebo** [comment]
Since most of Tradition’s power is buildings, the building sanity checks in PolicyAI are what need a tweak. I’ve been working on those and the BuildingSanity fix you did is what is causing tradition to suffer. Bring the divisors up.

**Comment by Infixo** [comment]
What do you mean? Change /100 into something else?
If BuildingSanity gives correct results, and we want to boost bulding power for Policies, maybe it is simply better to start with higher weight. Policies use CheckBuildingBuildSanity(eBuilding, 2, 10, 10, 10, false, true, true), so the initial weight is 10 always.

**Comment by LoneGazebo** [comment]
No, the returned value of a building is reduced in the policy AI because buildings return high values. I'll fix it.

**Comment by Infixo** [comment]
Ok!
