### ISSUE TITLE
WLTKD and Golden Age duration improper scaling with Gamespeed

### ISSUE THREAD

**Issue by ziadb** [LoneGazebo/Community-Patch-DLL#3881]
1. Jan 14 beta version non-hotfix

2. VP, Civic and Reform, Ethnic Units, JFD CulDiv + Soundtrack, some aesthetic mods

3. WLTKD and Golden Age duration are not scaled in the same manner as everything else. They appear to follow a different rule. 

On Standard, triggered WLTKD lasts 20 turns. GA last 10 turns.
On Marathon, triggered WLTKD lasts 30 turns. GA lasts 20 turns.

The scaling is not handled like the rest of the scaling in the game. 

My suspicion is that the duration is increased by 5 on each gamespeed, rather than being multiplied by a scalar.

4. 
Start a Marathon game.
Wait for WLTKD prompt
Trigger WLTKD with resource
Observe duration

Similar for GA.

**Comment by LoneGazebo** [comment]
There are specific scalers for those in the game speed info firaxis made IIRC.

**Comment by ziadb** [comment]
Oh so can't be modified then?

**Comment by Infixo** [comment]
You can modify it via GameSpeeds.GoldenAgePercent. But the point is that VP uses vanilla values, nothing changed here.

**Comment by ziadb** [comment]
What I distinctly remember WLTKD being 30 turns on Marathon. Perhaps my memory is fuzzy then.

**Comment by ziadb** [comment]
GAMESPEED_MARATHON 300
GAMESPEED_EPIC 150
GAMESPEED_STANDARD 100
GAMESPEED_QUICK 67 (or just 70).

Would this be better? I don't see why they settled on those numbers.... and as I said, with the changes to happiness in VP, would be appropriate to change as well.

**Comment by ziadb** [comment]
I think the main issue with WLTKD not scaling is that deal durations are tripled on Marathon, so you have to put out a lot of money in order to get all these different resources.

**Comment by ziadb** [comment]
Haha thanks Gazebo
