### ISSUE TITLE
Unit production too fast?

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3882]
_1. Mod version (i.e Date - 4/23): 1-14 with changes up to 1-20
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 

First my observations from 2 games (all standard settings), at turn 70. Not sure if you see similar things or maybe it's just a random thing.
1. Huge number of Melee and Pathfinders. Total units in game is approx. 180, out of which 110+ are warriors and spearmen and ~25 pathfinders. Marginal archers (~10), ~25 workers. Almost no horsemen nor chariot archers (single cases).
2. Cases were a city produces a monument, 2 pathfinders and then 6 warriors in a row. This usually happens to Authority civs. It would be ok if they were used for anything, but no - no wars, they just stand idle.
3. Cases were Civs produce 6-7 pathfinders. This happens to leaders with recon flavor 7+. 

All of the above are connected but also have some specific reasons, I think.
Ad. 1. I suppose this is connected to building sanity fix #3870. Many buildings dropped down, so on average units now get selected more often.
Ad. 2. Extensive Warrior production starts just after taking Dominance. It gives a free promotion and this single promotion boosts unit valuation hugely (x10 of its weight) Supply scaler is too weak to stop it, they produce them until ~90% of supply limit is reached. Funny thing - Archers don't get that promotion and that is why they are valued much less than melee - leading to huge disproportion in production. And since Warriors eat up supply as first avaialable units, then there is also not much room left for other unit types later.
Ad. 3. Well, nothing fancy here. EconomicAI calculates how many recon units are needed based on undiscovered number of tiles and until they are ready, their valuation get boosted. I think the problem is simply in that calculation - I don't think anyone ever needs 6-7 pathfinders.

I have been playing around with some tweaks to address the above. Tested them, and they seem to work. 
Ad. 1. Basically reduce entire unit valuation by lowering starting sanity value from 400 to 300. It affects all units, same as building fix affected all buildings. And I haven't found any scaler or modifier for units that would work on entire unit.
Ad. 2. Tone down a bit that promotion booster x8 instead of x10.
Ad. 3. I have added a parameter MAX_PLOTS_PER_EXPLORER that is the base for those calculations. Default is 20. Tested other values, 27 produces best results imo. Basically instead of 6-7 pathfinders, they produce 3-5. And since it is used as 1/x later, it doesn't affect much those who already produced 2-3 units.

The results from those test games are:
- Total units went down a bit to ~160. But the structure is changed. Less melee (~70), bit more archers (~15), plus horsemen and chariot archers (~10 each)
- Pathfinders total ~20, no cases of 6-7 units per civ (max. 5 in 1 case, usually 2-4)

**Comment by LoneGazebo** [comment]
That sounds about right to me. I was doing similar tweaks to the unit sanity check last night.
