### ISSUE TITLE
Freeze on barb turn.

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#3884]
_1. Mod version (i.e Date - 4/23):_
2018-01-14

_2. Mod list (if using Vox Populi only, leave blank):_
InfoAddict
Tectonic
Improved city view (v10)

_3. Error description:_ 
Freeze on barb turn.

_4. Steps to reproduce (optional):_
Turn 85. Temple of Artemis has been built the turn before. A barbarian trirreme is just showing up.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you h
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1650004/Logs.zip)
[AutoSave_0080 BC-0875.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1650005/AutoSave_0080.BC-0875.zip)

ave enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
cannot reproduce. please provide a savegame where all i have to do is press end turn ... otherwise my actions may influence the random number generator and thus the course of the game.

**Comment by tu-79** [comment]
Sorry, it happened on turn 65, last savegame was turn 60.

**Comment by ilteroi** [comment]
i know. you could reduce the autosave interval or make a manual save.

**Comment by tu-79** [comment]
Will do.

**Comment by tojothethief** [comment]
I'm getting freezes during barb turns too.
