### ISSUE TITLE
Why can't I settle there?

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#389]
![settle](https://cloud.githubusercontent.com/assets/1131228/8457742/b7195876-202c-11e5-8fb6-1daefe8243ee.png)

**Comment by LoneGazebo** [comment]
Can't settle on borders of an AI civ. I added that check for humans/AI a while back to keep the AI from gimping itself.
G

**Comment by Radost** [comment]
What about this one?
![8930_2015-06-30_00001](https://cloud.githubusercontent.com/assets/1131228/8459982/4f3f89b0-203a-11e5-8a46-1c1042d4d79a.png)

**Comment by LoneGazebo** [comment]
Which? Neither of those cities are directly situated on the edge of another player's empire.

G

**Comment by Radost** [comment]
What exactly defines "the edge"? Those cities are two tiles away, it can't be any more edgy than that.

**Comment by LoneGazebo** [comment]
Edges over water act different in the DLL - water counts as half the distance (Don't ask me why Firaxis decided that).

G

**Comment by Radost** [comment]
Where is the edge on the first screen then? Carthage once built a city, which was 3 tiles away from 2 of my cities.

**Comment by DanteValerian** [comment]
The rule is simple: If there is a border belonging to a civ other than yours and your settler is adjacent to it, your settler cannot found a city. If that condition doesn't apply, then normal 4-hex settling rules apply, UNLESS the settler is on a continent other than the nearest city, in which case it can settle 3 hexes away.

Hope that clears it up. Everything is working as intended.

**Comment by Radost** [comment]
Nope, it didn't clear up anything. How many tiles at minimum is "adjacent to it"? I am 2 tiles away from babylon borders. Even after settling the city our borders wouldn't touch.
Again, your reasoning doesn't explain the case with Carthage settling on a pretty tough spot, which was the only one available between 2 of my cities.

**Comment by DanteValerian** [comment]
The word "adjacent" means "next to in any direction", so adjacent in the example above means 1 tile away. If your settler is 1 tile away (next to) another civ's border you cannot settle the city no matter what.

In both your images above the game is working as intended, there is no problem here. Just follow the logic in my post above, it explains the rules for settling.

**Comment by Radost** [comment]
I can't follow the logic, because there is none.
![8930_2015-06-28_00003](https://cloud.githubusercontent.com/assets/1131228/8463712/1d44f3ac-2056-11e5-9f2c-2da90b70f207.png)
This is another Carthage city, which was settled basically next to my border.
Also the spot I was talking about (Panormus) is there:
![8930_2015-06-29_00012](https://cloud.githubusercontent.com/assets/1131228/8463770/a58e7440-2056-11e5-99f1-673841241189.png)

**Comment by DanteValerian** [comment]
Bactra and Panormus are both 4 tiles away from other cities.

There is no issue here.

**Comment by XplosiveLun** [comment]
I think Gazebo means you cannot settle cities within 4 tiles in the same continent in CBP. However, cities on different continents or islands have the minimal distance reduced to only 2 tiles. Therefore,  Yaroslave and Linz can be 2 tiles away. While Your pioneer cannot settle between cities of Assyria and Babylon.

And that's what happens in my previous game, as China, I wanted to settle a city 4 tiles away (The minimal distance) from America. It doesn't allow me to do that. After a long time, I sent a pioneer to an island chain where a empty plot with a city-state 2 tiles away in another island. It was supposed to allow settlement but it doesn't, probably because of the new "Settling Logic".

**Comment by Radost** [comment]
@DanteValerian 
Let's count again:
![numbers](https://cloud.githubusercontent.com/assets/1131228/8475968/123e36fa-20d6-11e5-8f2e-782f60bf9354.png)
Note that Panormus was founded after I took Utique and Gades, aka it was literally on the edge of my territory.

**Comment by DanteValerian** [comment]
4 tiles. Seriously, why do I have to explain this. Say you have an Archer in Gades and want to get him inside Panormus. How many moves does the Archer need to make to get inside panormus?

1st grade stuff, man.

**Comment by LoneGazebo** [comment]
The 4th plot away is Panormus, otherwise it would be a 5-plot minimum.
G

**Comment by Radost** [comment]
@DanteValerian 
Are you doing it on purpose? On the very first screen the distances are the same as any other, except I can't settle for some reason.

**Comment by NiteCyper** [comment]
I also don't understand why they can't settle in that first pic. They have fulfilled the minimum distance in all conditions.

**Comment by supermerill** [comment]
@DanteValerian I don't understand your reasoning. A boat also have to make 4 moves from Mari to the settler in the first pic.
I'm like NiteCyper and Radost, i don't understnad why he can't settle in the first pic, i can't see any ai border nearby.

**Comment by NiteCyper** [comment]
@supermerill I smell gas...lighting.
