### ISSUE TITLE
Coffee House (1/21 Beta)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#3890]
_1. Mod version (i.e Date - 4/23):_
1/21 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
VP+EUI (Automatic install)
IGE

_3. Error description:_ 
Coffee House doesn't grant +2 gold to bananas.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![ss](https://user-images.githubusercontent.com/11933188/35222282-baf0645a-ffc0-11e7-9cfc-b865634b3890.jpg)

**Comment by LoneGazebo** [comment]
You don’t eat bananas in a coffee house?

**Comment by 8h42** [comment]
I order Banana Parfait!
Then, you need to remove Bananas from its description.
![ss2](https://user-images.githubusercontent.com/11933188/35228557-5c2d5644-ffd4-11e7-9850-7d500abc8d91.png)

cf.
(6a) Community Balance Overhaul - Compatibility Files (EUI)\MoreLuxuries\Text\Text_en_US.sql
(6b) Community Balance Overhaul - Compatibility Files (No-EUI)\MoreLuxuries\Text\Text_en_US.sql
Line: 31

Interestingly, CBO TXT_KEY_BUILDING_COFFEE_HOUSE_HELP doesn't mention Bananas.
