### ISSUE TITLE
Interface missing on screen yields

### ISSUE THREAD

**Issue by ryanmusante** [LoneGazebo/Community-Patch-DLL#3891]
_1. Mod version (i.e Date - 4/23):_
1/21

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
On Screen Yields Begin To Disappear When There Is  Active Movement Over Tiles By Other Civ Units (Friendly, Barbarian).

_4. Steps to reproduce (optional):_
Turn Yields on (Y)
Proceed Several Turns (With Active Neighbor Civs)
Turn Yields Off
Turn Yields On Again

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

Before (Y) Screen Refresh (Notice Blank Tiles Near City And To The Upper Right)

![before](https://user-images.githubusercontent.com/26808646/35227642-efb665ca-ffd1-11e7-871d-1903df2793f2.png)

After (Y) Screen Refresh (Tiles Now Showing Proper Yields)

![after](https://user-images.githubusercontent.com/26808646/35227647-f1de3f8a-ffd1-11e7-8248-a6d418d981a5.png)

**Comment by LoneGazebo** [comment]
Yep. Engine bug. Can’t fix.
