### ISSUE TITLE
Texture glitch using Community Patch

### ISSUE THREAD

**Issue by Hitsuomy** [LoneGazebo/Community-Patch-DLL#3892]
_1. Mod version (i.e Date - 4/23):_
I tried with the latest december stable version and today's beta version.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Texture glitch with a lot o things, happening only with community patch, I can set up and play a game without mods just fine but it's impossible with community patch due to the visual glitches. Already tried changing resolutions, installing with and without EUI, reinstalling the game completely, verifying the files via steam, nothing works.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
https://i.imgur.com/SBODEft.jpg

**Comment by LoneGazebo** [comment]
Evidence suggests that you lack DLC, and/or that your civ is not up to date (.279).

**Comment by Hitsuomy** [comment]
Yeah, but it nothing is missing and the Civ is up to date, here everything I already tried and what I did to make sure the problem was only when using the community patch:
https://forums.civfanatics.com/threads/bug-need-some-help-with-visual-glitches.627262/

**Comment by LoneGazebo** [comment]
Is there anything extra in your DLC folder? C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Civilization V\Assets\DLC

Should only have this stuff in it
![untitled](https://user-images.githubusercontent.com/7849458/35242370-638ae660-ff87-11e7-9b89-e63673d2cf1e.png)

**Comment by Hitsuomy** [comment]
Exactly the same folders that I have.

**Comment by LoneGazebo** [comment]
Hmmm....okay. And you are definitely enabling the mods, hitting next, and starting a game from _within_ the Mods menu, correct?

**Comment by LoneGazebo** [comment]
Do me a favor. Enable logging, and send me your database.log after you enable it and load the mods.

**Comment by Hitsuomy** [comment]
Okay, I'm definitely doing that, Well, I cleared the logs and the cache, then I went and created a game with the mods enabled. Here are the logs:
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1653525/Database.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1653526/Lua.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1653527/xml.log)

**Comment by LoneGazebo** [comment]
Okay, everything looks fine there...

Since it is an AMD card, there's got to be something going on with your video adapter. Mipmap settings or something. I found this thread from 2010 with identical issues: https://forums.2k.com/showthread.php?90199-Graphic-Glitch-in-menu-and-on-some-icons

**Comment by Hitsuomy** [comment]
Well, I also though of that but there are just some problems with that, I can set up and play a game normally without the mods and every other game I tested is running without any problems even with more resource demanding settings. 
I also used to play Civ V a lot until around mid November and back then I was using this exact same PC and O.S. and I was playing without any problems using the Community Patch, can't see why this problem started now only when I'm using the Patch.

**Comment by LoneGazebo** [comment]
Well nothing related to icons/images in the game has changed for VP, so - unfortunately - the variable here is your hardware. I'd see if there's a beta AMD driver or something you can load, see if that's the culprit. Since this is the first we've seen this particular error, there's not much else I can say except that it is client-side.

**Comment by Hitsuomy** [comment]
Okay, it happens, I can't think of anything else, I already changed my video driver, I was using the latest beta but reversed to the latest stable, same thing, I'm trying to tweak the profile and customize some settings to see if there is any way to fix this annoying glitch but nothing so far.

**Comment by LoneGazebo** [comment]
If you see anything about texture filtering optimization or gpu decoding, disable those things.

**Comment by Hitsuomy** [comment]
Well I managed to "fix", I switched to DX9 mode and it's working now, no idea why since I use DX11 to run Dota 2 without problems. Anyway, at least it's working again.

**Comment by Vyyt02** [comment]
Just curious, on Civfanatics you say you tried reinstalling DirectX, but have you tried running the game with DX9/10/11? Always the same results?

**Comment by Hitsuomy** [comment]
I was trying always to run with DX11 like I used to back in November without any success, now I just changed to DX9 and everything went back to normal, but it's weird, I always used the DX11 without problems.
