### ISSUE TITLE
Helicopter promos overwritten into Archers

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3895]
_1. Mod version (i.e Date - 4/23): 1-21
_2. Mod list (if using Vox Populi only, leave blank): EE/VPEE
_3. Error description:_ 
In PromotionChanges.sql there is:
```
UPDATE UnitPromotions_UnitCombats 
SET UnitCombatType = 'UNITCOMBAT_ARCHER' WHERE UnitCombatType = 'UNITCOMBAT_HELICOPTER';

```
It messes up with Promotions from other mods. Is it intended or bug?

**Comment by LoneGazebo** [comment]
Helicopters are part of the mounted ranged line, so yes, intended.
