### ISSUE TITLE
AI policy adoption rate

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3899]
![image](https://user-images.githubusercontent.com/1358966/35299795-acaec3e8-0086-11e8-9535-54701d6a7beb.png)

see the jumps where the AIs get three new policies in the space of two turns? poland even gets six in three turns! how is that possible?

this is prince btw, there shouldn't be any bonuses ...

**Comment by MoiMagnus** [comment]
Were events enabled ?
I think most of the "2 policies in one turns" are great writers (but they should not give that much culture...). However the 3 or 6 policies in a row seems a little strange.
Are the "per turn culture" reasonnable (so it is the fault of instant yields), or does the "per turn culture" is going crazy ?

**Comment by LoneGazebo** [comment]
Is that Poland getting an ideology maybe?

**Comment by LoneGazebo** [comment]
Because Poland gets free tenets at that point, and it can happen if you get 18 policies before modern.

**Comment by ilteroi** [comment]
no events.

also ideology should give 3 max, right? one earned, one for early adopter, one bonus.

**Comment by LoneGazebo** [comment]
Poland gets two extra at adoption.

**Comment by ilteroi** [comment]
well, that makes 4 then ...

**Comment by LoneGazebo** [comment]
I'm not 100% sure - completion of the world congress event that gives a free policy, maybe? You can check your AI handicap logs and see if they're getting an extreme amount of culture - it's all documented in that log.

**Comment by MoiMagnus** [comment]
It seems that info-addict count finisher as policies.
So 19 (before jump) is 6(+1)+6(+1)+5.
When finishing the third tree, the civ is at 21: 6(+1)+6(+1)+6(+1).
The following turn, the civ adopt an ideology, so 22: 6(+1)+6(+1)+6(+1)+1
Except for Poland which has 2 free tenets at this point, so 24: 6(+1)+6(+1)+6(+1)+3

If Poland chosed Order, the Great Leap Forward gives 2 free techs, so possibly a new era -> the last policy.

**Comment by ilteroi** [comment]
nice analysis! 

unfortunately the logs are gone by now, i guess this is something to watch out for in the future. then we'll see if it was a fluke or if it's a real problem.
