### ISSUE TITLE
Endowment for the Arts & World Science Initiative tweaks

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3906]
The code for those resolutions is really weird. Two things:
1. Resolutions apply to civs with global score below median (that we all know).
2. The actual modifier used to calculate yields is not related to parameters in DB (i.e. ArtsyGreatPersonRateMod / ScienceyGreatPersonRateMod are ignored). It is calculated based on difference between civ's global scorce and best score and trimmed into 10..30 range (that I didn't know).

I have made the following changes.
1. Endowment for the Arts will use "cultural" score, i.e. from Policies and Great Works. World Science Initiative will use "science" score, i.e. from Techs and Future Tech. Those score are basically proportional to num of policies, GWs and techs. Then the median calculation will be applied.
2. The actual modifier will be using DB field. It will be proportional to difference in scores, but scaled to percentages. E.g. worst score will grant 100% of the Parameter (i.e. +33% now), and best score 0%. Since median is not equal to average, the modifier for civs receiving Aid will be somewhere in range ~10..33%.
3. I've modified accordingly Resolution valuation, so the civ with low "cultural" score will value Arts more, and vice versa for "science" scores. This will no longer be related to global score.

Gonna do some testing now.

**Comment by LoneGazebo** [comment]
Sounds good. Let me know how the tests go.

**Comment by Infixo** [comment]
Beside the main topic, I think we could change the modifiers used scoring. So that global score would reflect "power" and "development" of the civ little better now. Now it's almost like population score...
```
iScore += GetScoreFromCities();       --> getNumCities() * 8
iScore += GetScoreFromPopulation();   --> getTotalPopulation() * 4
iScore += GetScoreFromLand();         --> getTotalLand() * 1
iScore += GetScoreFromWonders();      --> GetNumWonders() * 25
iScore += GetScoreFromPolicies();     --> GetNumPoliciesOwned() * 4   // counts Finishers
iScore += GetScoreFromGreatWorks();   --> GetNumGreatWorks() * 4
iScore += GetScoreFromReligion();     --> GetNumBeliefs() * 5 + GetNumCitiesFollowing() * 3
iScore += GetScoreFromTechs();        --> GetNumTechsKnown() * 4
iScore += GetScoreFromVassals();      --> 50% of Vassals' Land and Pop scores
iScore += GetScoreFromMinorAllies();  --> % Allied of (Total Minors * 25)
iScore += GetScoreFromMilitarySize(); --> GetMilitaryMight() / (30+#cities) // complex, used to tributes as well
iScore += GetScoreFromFutureTech();   --> +10 each time FUT tech is researched
```
Weird things:
- Pop is overrated much. 50%+ of the score is usually pop.
- 1 citizen is "worth" the same as 1 tech and 1 policy, 2 pop = 1 city.
- Policies = Tech but there are ~4x more techs to get than policies, so tech weights much more.

I propose:
- Set 1 pop as 1 point of score (kind of reference), also comparable to 1 tile (1 tile = 1 point)
- Set Policy weight to 15, so it's worth ~4 techs
- Boost Military score a bit (20 instead of 30 in divisior).

**Comment by LoneGazebo** [comment]
Sounds fair - I haven't really messed with score much, aside from adding a few types.

**Comment by Infixo** [comment]
One more question. How is Science modifier supposed to work? I mean - where is it applied? To base yield? Because it's kind of messy here as well.

**Comment by LoneGazebo** [comment]
It is applied at the player level - i.e. it should appear in the top panel tooltip.

**Comment by LoneGazebo** [comment]
That's all collaborative code that another user and I did about 4 years ago...I didn't have a ton of oversight on it, it probably is pretty messy.

**Comment by Infixo** [comment]
Ok, got it. I will just check if calculations are correct, I am not going to change the algorithm.
And the modifier is displayed in the tooltip, so it is ok.
Culture is applied on city level, and the modifier will be displayed there. Not a big problem as long as all adds up.

**Comment by Infixo** [comment]
Do those resolutions still affect great persons? I can’t find the code for that. Just yields, no GPP.

**Comment by MoiMagnus** [comment]
> So that global score would reflect "power" and "development" of the civ little better now. Now it's almost like population score...
I think that the importance of population in the score was to represent the infrastructure development: improvements+buildings.
If you make population irrelevant, there is no difference between a highly developed city and a newly conquered city.
(I guess counting the number of buildings to compensate could be an idea, but it probably require new code)

**Comment by LoneGazebo** [comment]
@Infixo yes - the sciency/artsy rates do.

**Comment by Infixo** [comment]
Ha! Sweden (2nd in Policies) just voted against Arts and Korea (2nd to the last) voted for it.
Modifiers are calculated and displayed correctly - science in Top Panel, culture in City View.
