### ISSUE TITLE
isStart for **CityBeginsWLTKD**

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3913]
This is something I should've requested when I initially asked for the game event to be added, but didn't think about it at the time. Could you add a **isStart** boolean to the **GameEvents.CityBeginsWLTKD(playerID, plotX, plotY, WLTKDTurns)**. Alternatively, a separate **CityEndsWLTKD** might be easier/make more sense. Either way, this'd be really useful. Thanks.

**Comment by LoneGazebo** [comment]
Yup.

**Comment by JFDaly** [comment]
Hm, how does CityEndsWLTKD trigger? It doesn't seem to if a WLTKD started via ChangeWeLoveTheKingDayCounter method ends in a city.

**Comment by LoneGazebo** [comment]
Looks like it got removed in a merge. I'll readd.

G

**Comment by JFDaly** [comment]
Ah, cool. Thanks.

**Comment by pineappledan** [comment]
Does giving WLTKD turns via ChangeWeLoveTheKingDayCounter() trigger CityBeginsWLTKD?

If I were going to add extra turns of WLTKD via ChangeWeLoveTheKingDayCounter on an CityBeginsWLTKD event, would that cause an endless recursion and crash the game?
