### ISSUE TITLE
Internal table m_DangerPlots is not initialized

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3914]
_1. Mod version (i.e Date - 4/23): 1-21
_2. Mod list (if using Vox Populi only, leave blank): Really Advanced Setup v15
_3. Error description:_ 
CTD when going into Auto-play.
Internal table m_DangerPlots is not initialized (NULL). The crash happens in AddKnownAttacker.
According to some comments in the code this may only happen with RAS active.

@ilteroi I've made only a temporary fix to enable auto-play for games with RAS. If you fix it in a more permament way, then I will revert the changes.

I have also noticed that activating auto-play for such a game and thus calling those Inits for several players takes huge amount of time. Really, I thought for a moment that the game froze - it took literally 8 minutes. And I have quite a good comp. Granted it was on a Huge map, but it really took long.

**Comment by ilteroi** [comment]
well, that's a very comprehensive solution, but it should work.

since the case doesn't occur in normal play, i think it would have been enough to add

	if (!m_bArrayAllocated || !pUnit)
              return;

to AddKnownAttacker().

**Comment by Infixo** [comment]
Great. I also added the same check for IsKnownAttacker, just to be on the safe side. 
Tested it, working ok.
