### ISSUE TITLE
Building_BuildingClassYieldModifiers

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3916]
Would a **Building_BuildingClassYieldModifiers** akin to the existing Building_BuildingClassYieldChanges be feasible? I'm currently using a dummy policy to simulate this, but it'd be great if it were a table in itself. Thanking.

**Comment by LoneGazebo** [comment]
It is feasible, however I'll wait to add it in until my next release as it'll break savegames.

**Comment by JFDaly** [comment]
Sounds good, thanks.

**Comment by LoneGazebo** [comment]
This will be included next version. To note, the lua UI for this uses the same UI function as 'GetPolicyBuildingClassYieldModifier' - it adds the new value to this, so you shouldn't have to change your UI code.

**Comment by LoneGazebo** [comment]
[(1) Community Patch (v 88).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1680379/1.Community.Patch.v.88.zip)

Debug DLL. Includes request above. Let me know what does/does not work. :)

G

**Comment by JFDaly** [comment]
Cool, everything seems to be working. Thanks.

**Comment by LoneGazebo** [comment]
Perfect. UI too?

**Comment by JFDaly** [comment]
The Per Turn details update correctly yeah.

**Comment by LoneGazebo** [comment]
What about on the modified buildings themselves?

**Comment by JFDaly** [comment]
Yeap, works on the building too.

**Comment by LoneGazebo** [comment]
Cool! Closing then.
