### ISSUE TITLE
GetNumUnitsNoCivilian removed?

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3918]
The function **player:GetNumUnitsNoCivilian()** was in previous versions. On the latest from Jan 26th, however, it seems to have been removed or otherwise no longer works with Lua. Could you check? Thanks.

**Comment by ilteroi** [comment]
hmm yes, i renamed it to GetNumUnitsToSupply() because the old name was misleading.

**Comment by JFDaly** [comment]
Ah, cool. Thanks.
