### ISSUE TITLE
Building/Policy_GoldenAgeYieldModifiers

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#392]
Would it be possible to add a Building_GoldenAgeYieldModifiers(buildingType, yieldType, Modifier) and an equivalent Policy_ table? This would function like Building/Policy_YieldModifiers, but only apply the effect during Golden Ages. Anticipating its use in my Prestige mod (but more immediately I aim to use it in Piety), I'd appreciate support for negative modifiers (the regular YieldModifiers support as much).

**Comment by LoneGazebo** [comment]
Yep, shouldn't be too hard. I have one for religion already, so porting the logic over for that should be fairly easy. It may be a little bit though, as I'm heading out of town tomorrow. 

G

**Comment by JFDaly** [comment]
Thanks!
