### ISSUE TITLE
Infinite Tribute 

### ISSUE THREAD

**Issue by Grabbl** [LoneGazebo/Community-Patch-DLL#3920]
_1. Mod version (i.e Date - 4/23):_
1/26

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I can demand tribute infinitely of Riga. (with other city states, it worked like intended).
The "Recently asked for tribute" modifier appears, and numbers indicate that I shouldn't be able to demand tribute, but I somehow can.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Gustavus Adolphus_0280 AD-1300.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1671653/Gustavus.Adolphus_0280.AD-1300.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20180128225420_1](https://user-images.githubusercontent.com/19163988/35487726-3ad9a9e8-047f-11e8-9e91-432c8e20deae.jpg)
![Uploading 20180128225406_1.jpg…]()

**Comment by LoneGazebo** [comment]
Any other mods?

**Comment by Grabbl** [comment]
No, just VP with EUI from the Installer.
