### ISSUE TITLE
Endowerments Of Arts dont increase GP rate

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3922]
_1. Mod version (i.e Date - 4/23):_
last

_3. Error description:
It decreased my GP as always, but don't increase(screens).
Maybe it is intended, don't remember was this resolution changed in last version or not. 
Just pass a resolution in game and see after it:

Here as always decreased Scientis - OK

![20180129154244_1](https://user-images.githubusercontent.com/13381981/35513266-2236abca-050b-11e8-9e1d-2f086351f6de.jpg)

Here is not increasing artists - BAD or not?

![20180129153847_1](https://user-images.githubusercontent.com/13381981/35513257-1cd49994-050b-11e8-81a0-23d610c86ddf.jpg)

I am top in score. Maybe it was changed and now increased artists/writers only for low score players?
If so then it is good idea to change a tooltip of it.

**Comment by Infixo** [comment]
It has been changed. GPP rates scale the same way as Yield rates now, depending on tech/policy relative score. The tooltip is changed e.g.:
_Increases up to 33% generation of Great Writers, Artists, and Musicians. Decreases up to 33% generation of Great Scientists, Engineers, and Merchants. Civilizations with Scores from Policies and Great Works below the global median will receive a boost to Production and Culture up to 33%. Details: The boosts are proportional to the difference between the score of the Civilization and the leader._

If you have top culture score then: no boost yield (only civs below median receive it) and GPP rate for GWAM is +0%. Worst civ will receive +33% yield and +33% GPP rate. E.g. you are worst in Tech score hence +33% in GPP rate for SciEngMer.

**Comment by bigcat88** [comment]
Ah, ok, I understand. Thanks.
