### ISSUE TITLE
Stoneworks Required Resources differs from Tooltip

### ISSUE THREAD

**Issue by bridger15** [LoneGazebo/Community-Patch-DLL#3923]
_1. Mod version (i.e Date - 4/23):_
1-26 

_2. Mod list (if using Vox Populi only, leave blank):_
VP version of Improved City View

_3. Error description:_ 
See this image: https://i.imgur.com/iFcA2OZ.jpg

The stone works tooltip seems to imply that it improves Stone/Marble/Salt/Jade.

However, at the top of the tooltip it shows that it requires either stone/marble/salt/Lapis/Uranium/Amber (but *not* Jade).

I assume this is merely a tooltip bug.  I've attached a save file:
[Stone Works Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1674574/Stone.Works.Bug.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Infixo** [comment]
Nothing wrong here. SW improves 4 resources but requires one of 6 listed nearby. Uranium is weird here, I agree. I'll leave it to @LoneGazebo to decide if it should improve all 6 or require only 1 of 4. Or maybe the current situation is intended, idk. I would go for Stone, Marble, Salt, Jade option and remove Uranium, Amber and Lapis from reqs.

**Comment by bridger15** [comment]
Ah, well, the tooltip at the bottom specifies that it must have "one of these resources nearby" (implying it requires the 4 improved ones).  The additional 3 at the top and the lack of Jade made me think something was wrong.

**Comment by bridger15** [comment]
Confirmed: If Jade is the only improved resource around a city the stoneworks is NOT buildable, despite the fact that the tooltip suggests it should be.

**Comment by deadstarre** [comment]
I just ran into the same thing @bridger15 haha went to build stoneworks to improve my jade and i couldnt. If youre in the middle of a game you can save, exit, and add this line of code to the moreluxuries compatibility file in (6a) to fix it and continue on

INSERT INTO Building_LocalResourceOrs
	(BuildingType, ResourceType)
VALUES
	('BUILDING_STONE_WORKS', 'RESOURCE_JADE');

**Comment by Infixo** [comment]
The tooltip doesn't suggest that it should be buildable around Jade. It clearly says that it improves Jade and 3 other resources, but requires a different set of resources nearby.
And I agree that those sets probably should be the same to avoid confusion.

**Comment by bridger15** [comment]
It definitely says that it is buildable around Jade.  Read the last sentence of the tooltip.  "City must have at least one of these resources improved," of which, it just listed, among others, Jade.
