### ISSUE TITLE
late game observations

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3924]
still can't reproduce the dreaded freeze, but here's something else from my latest autoplay game.

ethiopia conquered siam, china and the zulus, it's 2040 AD and they have completed the tech tree.

![image](https://user-images.githubusercontent.com/1358966/35532512-c7e7d38a-053a-11e8-87e5-7e3c7aa82583.png)

observations: 

* they have a cash flow problem, but are happily building units (in owned cities) and infrastructure (in puppets). why no wealth process?
* happiness is too easy right now.
* 10 happiness from future tech doesn't seem to work, or at least it changed nothing when i granted them some more

![image](https://user-images.githubusercontent.com/1358966/35532536-db66be80-053a-11e8-858e-c67b91d37681.png)

![image](https://user-images.githubusercontent.com/1358966/35532554-e5223d78-053a-11e8-88e7-33b08bb6a2df.png)

production AI log for owned city
<details>
432, Ethiopia, Dire Dawa, PRE: Process, Research, 1909, 1
432, Ethiopia, Dire Dawa, PRE: Unit, Guerilla, 1824, 2
432, Ethiopia, Dire Dawa, PRE: Process, Wealth, 1770, 1
432, Ethiopia, Dire Dawa, PRE: Unit, Mechanized Infantry, 1701, 2
432, Ethiopia, Dire Dawa, PRE: Unit, XCOM Squad, 1380, 3
432, Ethiopia, Dire Dawa, PRE: Unit, Helicopter Gunship, 1368, 3
432, Ethiopia, Dire Dawa, PRE: Unit, Worker, 1170, 1
432, Ethiopia, Dire Dawa, PRE: Unit, Jet Fighter, 1140, 3
432, Ethiopia, Dire Dawa, PRE: Unit, Mobile SAM, 1110, 2
432, Ethiopia, Dire Dawa, PRE: Unit, Stealth Bomber, 1044, 3
432, Ethiopia, Dire Dawa, PRE: Unit, Rocket Artillery, 912, 3
432, Ethiopia, Dire Dawa, PRE: Unit, Bazooka, 906, 2
432, Ethiopia, Dire Dawa, PRE: Process, Arts, 510, 1
432, Ethiopia, Dire Dawa, PRE: Unit, Nuclear Submarine, 465, 3
432, Ethiopia, Dire Dawa, PRE: Process, Farming, 435, 1
432, Ethiopia, Dire Dawa, PRE: Unit, Archaeologist, 330, 1
432, Ethiopia, Dire Dawa, PRE: Process, Defense, 100, 1
432, Ethiopia, Dire Dawa, POST: Unit, Mobile SAM, 24395, 2
432, Ethiopia, Dire Dawa, POST: Unit, XCOM Squad, 17202, 3
432, Ethiopia, Dire Dawa, POST: Unit, Rocket Artillery, 13872, 3
432, Ethiopia, Dire Dawa, POST: Unit, Bazooka, 11772, 2
432, Ethiopia, Dire Dawa, POST: Unit, Guerilla, 6917, 2
432, Ethiopia, Dire Dawa, POST: Unit, Mechanized Infantry, 6917, 2
432, Ethiopia, Dire Dawa, POST: Process, Research, 1424, 1
432, Ethiopia, Dire Dawa, POST: Process, Wealth, 1424, 1
432, Ethiopia, Dire Dawa, POST: Process, Arts, 1424, 1
432, Ethiopia, Dire Dawa, POST: Process, Farming, 1384, 1
432, Ethiopia, Dire Dawa, SEED: 11454684161304664014, CHOSEN: Mobile SAM, Do not rush, TURNS: 2
</details>

---
puppets are strange:

puppet A (buildings in PRE but not in POST)
<details>
434, Ethiopia, Nongoma, PRE: Building, Seaport, 19650, 6
434, Ethiopia, Nongoma, PRE: Building, Factory, 5453, 3
434, Ethiopia, Nongoma, PRE: Building, Wind Plant, 3950, 9
434, Ethiopia, Nongoma, PRE: Unit, Work Boat, 3380, 1
434, Ethiopia, Nongoma, PRE: Building, Agribusiness, 2080, 5
434, Ethiopia, Nongoma, PRE: Unit, Carrier, 1925, 8
434, Ethiopia, Nongoma, PRE: Process, Wealth, 1720, 1
434, Ethiopia, Nongoma, PRE: Process, Research, 1149, 1
434, Ethiopia, Nongoma, PRE: Building, Mine Field, 900, 6
434, Ethiopia, Nongoma, PRE: Process, Arts, 660, 1
434, Ethiopia, Nongoma, PRE: Unit, Nuclear Submarine, 465, 10
434, Ethiopia, Nongoma, PRE: Unit, Archaeologist, 330, 1
434, Ethiopia, Nongoma, PRE: Process, Farming, 260, 1
434, Ethiopia, Nongoma, PRE: Process, Defense, 100, 1
434, Ethiopia, Nongoma, POST: Process, Arts, 3008, 1
434, Ethiopia, Nongoma, POST: Process, Research, 2408, 1
434, Ethiopia, Nongoma, POST: Process, Wealth, 2396, 1
434, Ethiopia, Nongoma, POST: Process, Farming, 1583, 1
434, Ethiopia, Nongoma, POST: Process, Defense, 569, 1
434, Ethiopia, Nongoma, SEED: 3118619152238934244, CHOSEN: Research, Do not rush, TURNS: 1
</details>

puppet B (buildings in PRE and one left in POST)
<details>
433, Ethiopia, Sukhothai, PRE: Building, Stock Exchange, 8605, 2
433, Ethiopia, Sukhothai, PRE: Building, Factory, 6613, 1
433, Ethiopia, Sukhothai, PRE: Building, Hydro Plant, 5050, 3
433, Ethiopia, Sukhothai, PRE: Building, Agribusiness, 3680, 2
433, Ethiopia, Sukhothai, PRE: Unit, Worker, 3570, 1
433, Ethiopia, Sukhothai, PRE: Process, Wealth, 1995, 1
433, Ethiopia, Sukhothai, PRE: Process, Research, 1229, 1
433, Ethiopia, Sukhothai, PRE: Process, Arts, 910, 1
433, Ethiopia, Sukhothai, PRE: Process, Farming, 460, 1
433, Ethiopia, Sukhothai, PRE: Unit, Archaeologist, 330, 1
433, Ethiopia, Sukhothai, PRE: Process, Defense, 100, 1
433, Ethiopia, Sukhothai, POST: Building, Stock Exchange, 6311, 2
433, Ethiopia, Sukhothai, POST: Process, Arts, 1532, 1
433, Ethiopia, Sukhothai, POST: Process, Wealth, 920, 1
433, Ethiopia, Sukhothai, POST: Process, Farming, 880, 1
433, Ethiopia, Sukhothai, POST: Process, Research, 812, 1
433, Ethiopia, Sukhothai, POST: Process, Defense, 200, 1
433, Ethiopia, Sukhothai, SEED: 13679811952545592187, CHOSEN: Stock Exchange, Do not rush, TURNS: 2
</details>

puppet C (building and units ins PRE, multiple buildings left in POST)
<details>
432, Ethiopia, Umgungundlovu, PRE: Building, Seaport, 23150, 2
432, Ethiopia, Umgungundlovu, PRE: Building, Stock Exchange, 8705, 3
432, Ethiopia, Umgungundlovu, PRE: Building, Factory, 6573, 1
432, Ethiopia, Umgungundlovu, PRE: Building, Wind Plant, 4950, 4
432, Ethiopia, Umgungundlovu, PRE: Building, Airport, 4890, 4
432, Ethiopia, Umgungundlovu, PRE: Unit, Work Boat, 3380, 1
432, Ethiopia, Umgungundlovu, PRE: Building, Medical Lab, 3280, 4
432, Ethiopia, Umgungundlovu, PRE: Building, Agribusiness, 3280, 2
432, Ethiopia, Umgungundlovu, PRE: Process, Wealth, 2020, 1
432, Ethiopia, Umgungundlovu, PRE: Building, Mine Field, 1900, 2
432, Ethiopia, Umgungundlovu, PRE: Unit, Guerilla, 1824, 3
432, Ethiopia, Umgungundlovu, PRE: Unit, Mechanized Infantry, 1701, 5
432, Ethiopia, Umgungundlovu, PRE: Unit, XCOM Squad, 1380, 7
432, Ethiopia, Umgungundlovu, PRE: Unit, Helicopter Gunship, 1368, 6
432, Ethiopia, Umgungundlovu, PRE: Unit, Worker, 1170, 1
432, Ethiopia, Umgungundlovu, PRE: Process, Research, 1149, 1
432, Ethiopia, Umgungundlovu, PRE: Unit, Jet Fighter, 1140, 6
432, Ethiopia, Umgungundlovu, PRE: Unit, Mobile SAM, 1110, 5
432, Ethiopia, Umgungundlovu, PRE: Unit, Stealth Bomber, 1044, 6
432, Ethiopia, Umgungundlovu, PRE: Unit, Rocket Artillery, 912, 6
432, Ethiopia, Umgungundlovu, PRE: Unit, Bazooka, 906, 3
432, Ethiopia, Umgungundlovu, PRE: Process, Arts, 810, 1
432, Ethiopia, Umgungundlovu, PRE: Unit, Nuclear Submarine, 465, 6
432, Ethiopia, Umgungundlovu, PRE: Process, Farming, 410, 1
432, Ethiopia, Umgungundlovu, PRE: Unit, Archaeologist, 330, 1
432, Ethiopia, Umgungundlovu, PRE: Process, Defense, 100, 1
432, Ethiopia, Umgungundlovu, POST: Building, Medical Lab, 10112, 4
432, Ethiopia, Umgungundlovu, POST: Building, Airport, 8215, 4
432, Ethiopia, Umgungundlovu, POST: Building, Stock Exchange, 5771, 3
432, Ethiopia, Umgungundlovu, POST: Process, Arts, 1808, 1
432, Ethiopia, Umgungundlovu, POST: Process, Wealth, 1220, 1
432, Ethiopia, Umgungundlovu, POST: Process, Farming, 1156, 1
432, Ethiopia, Umgungundlovu, POST: Process, Research, 1088, 1
432, Ethiopia, Umgungundlovu, POST: Process, Defense, 269, 1
432, Ethiopia, Umgungundlovu, SEED: 728260067531932805, CHOSEN: Medical Lab, Do not rush, TURNS: 4
</details>

----

you might be tempted to say this is not relevant for normal play but i like to look at the extreme cases for sanity checks.

**Comment by LoneGazebo** [comment]
Have they not won the game already?

**Comment by LoneGazebo** [comment]
Re: puppets, puppets will not build buildings that have strategic resource requirements.

**Comment by bigcat88** [comment]
@ilteroi pls teach AI not to build(or just remove that building) space factories if Science victory is disabled.

After I will solve my freeze problems I can post my saves/screens from games in 2020-2030 AD in future.

**Comment by ilteroi** [comment]
i'd be happy if they build wealth all the time while bankrupt (ie zero gold, negative gpt)

**Comment by LoneGazebo** [comment]
Is the game over, or no? I can increase interest in wealth if <0 GPT and <0 income. That's the only real issue I see here - the puppet stuff is intended.

G

**Comment by ilteroi** [comment]
don't know if it's over and it doesn't matter imho. they built themselves a hole.

and it's funny how there is basically no poverty but at the same time they can't even pay their building maintenance.

**Comment by LoneGazebo** [comment]
Adjusted process proclivity. We shall see.
