### ISSUE TITLE
Unlimited Social Policies in VP 1-26

### ISSUE THREAD

**Issue by myles1718** [LoneGazebo/Community-Patch-DLL#3925]
_1. Mod version (i.e Date - 4/23):_
VP 1-26

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Now in my 5th attempt at playing the new version of VP 1-26 and after building my first city I am getting unlimited Social Policies.  After acquiring 12 game freezes.
Culture amount shown in Top view say 39 but checking Policies
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1677081/Lua.zip)

 Tree says I have 21,474,808

_4. Steps to reproduce (optional):_

[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1677081/Lua.zip)
[xml.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1677094/xml.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1677097/Database.zip)
[IGE1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1677101/IGE1.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Infixo** [comment]
Please provide a save file.

**Comment by myles1718** [comment]
After some trial games have managed to get games working without using the following mods -
259c3593-34dd-4fdd-bd7d-8ed67cc0797c (v 25)
af398f38-90a0-45f0-9831-6c712c86061b (v 5)
