### ISSUE TITLE
Text Typo - Arena Tourism Yields (Using EUI)

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#3928]
_1. Mod version (i.e Date - 4/23):_
1-26 (although I have noticed this typo for the last several versions)

_2. Mod list (if using Vox Populi only, leave blank):_
N/A

_3. Error description:_ 
The Arena lists that it produces +2 Tourism in the UI description, but the building does not actually produce any Tourism yields. This has been the case for several months now, and I am assuming that the +2 Tourism listing in the UI is erroneous because the Civipedia entry does not mention this building having Tourism yields. Perhaps this is a hold-over from when Arenas used to produce Tourism once Archaeology was researched?

_4. Steps to reproduce (optional):_
Using EUI version of VP, build an Arena. The UI description of the building says is produces +1 Culture and +2 Tourism (in addition to it's other special effects), but once built the city yields will only increase by +1 Culture.

I can provide screenshots later if necessary.

**Comment by Infixo** [comment]
As for now, Arena IS granting +2 Tourism (there's an entry in SQL). The EUI tooltip is correct.
The description is missing that info.
The Civilopedia entry doesn't show Tourism on the left side because Civilopedia doesn't handle unified Tourism yield at all. This one I can easily fix.

**Comment by LoneGazebo** [comment]
@infixo I’m not sure if the basic Yield change table actually works for tourism. Needs testing.

**Comment by Infixo** [comment]
Tested it quickly. It's working, DLL properly adds those yields. Also - there are multiple entries, like Cristo Redentor for 25. People would quickly noticed if it didn't worked...

**Comment by cdanger341** [comment]
If the arena is properly adding Tourism, then why do my 10+ city empires with arenas in every city yield less than 20 Tourism per turn on the UI? Also, if I go into the city viewer the per-city yields are showing +0 tourism from buildings. I always assumed Arenas only gave Culture and the +2 Tourism was a typo because the Tourism yields never seemed to actually apply at any point.

**Comment by Infixo** [comment]
Maybe you have some other problem... Please provide a save file and logs (when the save file is loaded), I’ll take a look.

**Comment by cdanger341** [comment]
I can provide a save file once I get home this evening, but I know this just can't be me. I've watched several let's plays of VP using the 12-25 and 1-16 versions and their Arenas do not generate Tourism either, only Culture. This is why I thought it must be a building UI text typo rather than a broken yield.

For example, in Martin Fencka's playthrough of Byzantium using the 12-25 version he has 20+ cities with arenas in every city, but is only producing 2 Tourism per turn according to his UI. So either the Arenas are producing tourism and the UI isn't counting it, or the building is not producing tourism yields and the UI is working just fine.

**Comment by Infixo** [comment]
Just did a moment ago on 1-26 version, no other mods.

![arena tourism](https://user-images.githubusercontent.com/25866684/35639742-73453c5a-06bb-11e8-93b0-3d735260933b.jpg)

**Comment by Infixo** [comment]
And another one after 10 turns, to check the influence is actually increasing and the game processes tourism correctly.
![arena tourism after 10 turns](https://user-images.githubusercontent.com/25866684/35640280-fdac5e36-06bc-11e8-8ebb-0521e69e6c1d.jpg)

**Comment by cdanger341** [comment]
The Arena shows up in the UI as having tourism yields for me too, but the tourism isn't being added/counted for the city output (only for the Arena, not for other buildings/wonders that produce Tourism). I don't have access to my saves until I get home later, but here is a screencap from Martin's LP using the 12-25 version (with no other mods). I'm seeing the same behavior in the 1-16 and 1-26 versions.

![arena-not-working](https://user-images.githubusercontent.com/19951628/35640531-0dcc8b04-0683-11e8-9836-c9faaac1c292.jpg)

**Comment by Infixo** [comment]
And Martin has tourism from Arenas. https://www.youtube.com/watch?v=SZQlc2zv4n8. Go to 51:14 and you can see +2 Tourism in the city (this is the 1st Arena he built).

**Comment by Infixo** [comment]
Anyway, get the files when you are at home. It's no hurry.

**Comment by Infixo** [comment]
Also, a possible explanation could be that you or Martin have negative modifiers that decrease the output value. Check the tooltip for details.

**Comment by cdanger341** [comment]
What negative modifiers could possibly be decreasing tourism output to 0 for cities with arenas in them? Martin has arenas in nearly every city and yet his tourism output is only 2 per turn. It's not a puppet city, and he has positive happiness. I'm still seeing the exact same thing in the 1-26 version.

**Comment by Infixo** [comment]
To answer that questons I need the files.

**Comment by cdanger341** [comment]
Okay, so I think I figured out where my confusion is coming from. It looks like the -% tourism penalty for # of cities is rounding down to the next whole integer for even the smallest of percentages. So in the early game when the Arena is likely the only building you have that produces tourism, the +2 tourism yield is getting lowered to +1 in each city. In the attached example, I have over a dozen cities in my empire and this is a non-puppet city with only an Arena as a source of tourism. If it were a puppet city the additional -50% would round it below 1 and it would drop to 0. So this appears to be why I thought the +2 tourism on Arenas was not applying.

![8930_20180131184823_1](https://user-images.githubusercontent.com/19951628/35658097-63dc0e74-06c5-11e8-9268-3193dbf20044.png)
