### ISSUE TITLE
Asserts

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3929]
_1. Mod version (i.e Date - 4/23): 1-26
_2. Mod list (if using Vox Populi only, leave blank): none

In the aftermath of the Slain Like The Hydra Infamous Freeze Bug, I have fixed all asserts in the code. But to enable them we need an additional preprocessor define added to Debug config, because _DEBUG doesn't work (linker errors).
I've added VPDEBUG that if defined, enables all Asserts and AI-PERF log. What do you think?

**Comment by Infixo** [comment]
I'll post changes for review.
Also - installed VS2013, have Debug/Release options and finally can compile StackWalker properly.

**Comment by Infixo** [comment]
There are few asserts that use non-existing functions that I wasn't sure how to fix, so commented them out.
@ilteroi One is in CvDangerPlots.cpp.

**Comment by LoneGazebo** [comment]
I'll leave open for Ilteroi, otherwise merging.

**Comment by ilteroi** [comment]
acknowledged, but no need for further changes from my perspective
