### ISSUE TITLE
Conscription still not creating free unit on policy pick

### ISSUE THREAD

**Issue by DanteValerian** [LoneGazebo/Community-Patch-DLL#393]
Running CPP, CBP, C4DF/CSD, and ExCE (most options disabled).

**Comment by LoneGazebo** [comment]
That's crazy. I tested this multiple times. Now I'm worried that my optimization compiler is messed up. 

G

**Comment by DanteValerian** [comment]
On the bright side, the infinite unit per policy bug is fixed. I only get units on founding new cities now, but never in the capital.
