### ISSUE TITLE
VictoryProgress.lua fix

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#3932]
_1. Mod version (i.e Date - 4/23): 2-1
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 

VictoryProgress.lua contains a recursively called function GetPreReqs(). It is used to identify all techs that are needed to research Apollo Project tech. Then this list is used to display progress indicator.
Problem is that the more techs and tech prereqs are in the tech tree, the longer this function takes to execute. I noticed that when using EE mod, because it adds 8 new techs and ~25 new tech prereqs. The loading times were approx. 140 seconds longer than pure VP which loads in approx. 31 sec (on my machine, standard size map).

I have prepared the fix that utilizes FindPathLength, so no recursive Lua calls are needed. This not only solves EE issue but also speeds up VP itself. It loads in 21 seconds now (compared to 31). For small size maps it is 16 vs. 24 (before fix).

**Comment by ryanmusante** [comment]
Good work! You're talking about a loading time during AI turns speed up?

**Comment by Infixo** [comment]
No. When you start a new game or load a save file. This is the moment when this function is used.
