### ISSUE TITLE
Luxury Happiness Tooltip Issue

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#3935]
_1. Mod version (i.e Date - 4/23):_
2/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Either the luxury population from happiness is capping or the tooltip is incorrect. Until I get to 2 happy per luxury, the tooltip increases in increments. 1.5, 1.6, etc etc. Once it hits 2, it never increases further, even though it tells you the next population number you will hit a bump on.

In this example it had told me I would get a bump at 198. Now at 198, its saying I need 201, etc.

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/35773086-ca1d6472-090d-11e8-9133-63915b4b3d24.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
So technically the code is working, but it does become problematic as you reach higher populations. I've been meaning to revisit this function and sanitize it, will do so for next release.
