### ISSUE TITLE
CTD on AI turn

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3938]
_1. Mod version (i.e Date - 4/23):_
last

_2. Mod list (if using Vox Populi only, leave blank):_
Enchanced Naval Warfare
Really Advanced Setup

_3. Error description:_ 
Crash on Japan AI turn.

_4. Steps to reproduce (optional):_
Press next button. I checked 2 times, crash is repeatable :(

[cCatherine_0408 AD-1796.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1693243/cCatherine_0408.AD-1796.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1693244/CvMiniDump.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1693245/Logs.zip)

**Comment by Infixo** [comment]
You are running additional SQL:
`[1214524.140] , 					Update Database - Small changes.sql, 0.012010`
What is it?

**Comment by bigcat88** [comment]
[Small changes.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1695540/Small.changes.zip)

That's just file with a few sql requests for my games. Nothing that can break the game, just a small tourism decrease.

**Comment by Infixo** [comment]
Yup, not important, just wanted to make sure.
The issue is in DLL, null pZone pointer while AI is doing its "thinking".
I'll try to prepare a workaround for you.

**Comment by Infixo** [comment]
Use that DLL (backup an original one just in case)
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1695773/CvGameCore_Expansion2.zip)

**Comment by Infixo** [comment]
@ilteroi 
The situation is as follows. Japan attacks the city Chuito (Inca). This city is a bit weird - it is a 2-tile island, where the city tile is a mountain and the other one is Rock of Gibraltar. GetZoneByCity(pCity, false) in line 2032 returns a non-NULL land zone, but the it goes into GetZoneByCity(pCity, true) in 2038 to retrieve a water zone, which returns NULL. It is logged as "408, Japan, Zone -1, attempting capture of Chuito, required damage 41, expected damage 583" Then the CTD in line 2119.
Interesting thing however, that later this city is properly recognized as water zone with ID=-9599. Line 2032 returns NULL, then line 2038 returns non-NULL and all is fine. Log: "408, Persia, Zone -9599, City of Chuito, is in enemy dominated zone - won't try to capture, X: 86, Y: 14, "
So, it seems that initial assessment as a land zone is wrong (?), later it gets somehow fixed.

**Comment by bigcat88** [comment]
So this fix is temporary? Dat Inca always make a problems :)
Anyway thanks for that, it works!

**Comment by Infixo** [comment]
Temporary = for @ilteroi to decide what to do with it; the root cause is somewhere else probably and I am not familiar enough with Tactical AI to find it.

**Comment by ilteroi** [comment]
uh oh, classic copy/paste error: pZone is redefined inside the conditional branches in L2038 and L2153, shadowing the outer definition.

**Comment by Infixo** [comment]
They match comments, the first call is for land, the second is for water, they seem ok. It must be somewhere where these zones are established in the first place.

**Comment by ilteroi** [comment]
the logic is: try the land zone first, if it's no good look at the water zone. if the water zone is good, overwrite the pointer. but that last part doesn't happen.

**Comment by Infixo** [comment]
What should be the correct situation here? Land zone non-NULL and no check for water-zone? Because now null-water-zone overwrites non-null-land-zone.

**Comment by ilteroi** [comment]
(not null) != (good)

trust me, just remove the inner CvTacticalDominanceZone*

**Comment by Infixo** [comment]
Oh, I get it. It doesn't overwrite the pointer, because it is a local var.
