### ISSUE TITLE
East India company doesn't provide a trade route

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#3940]
_1. Mod version (i.e Date - 4/23):_
Latest

_2. Mod list (if using Vox Populi only, leave blank):_
VP + IGE for testing purposes

_3. Error description:_ 
Title. Attached below is a save 1 turn before constructing an EIC.

[East India company.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1695287/East.India.company.zip)

**Comment by bigcat88** [comment]
Free trade route was removed AFAIK.

**Comment by Edaka** [comment]
Oh, if so, I didn't know that. However, that means that the text description is outdated, because it still states that it does provide a TR.

**Comment by LoneGazebo** [comment]
I fix text
