### ISSUE TITLE
Stables not requiring horses

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#3942]
_1. Mod version (i.e Date - 4/23):_
2018-01-26

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I can build stables in cities without any connected horses, is this intended?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1696363/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Austria.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1696364/Austria.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![stables without horses](https://user-images.githubusercontent.com/7407102/35822915-11fea6b0-0aae-11e8-9fae-ca569bbf3087.jpg)

**Comment by tu-79** [comment]
My guess is that horses from StateCraft is what allows my stables to be built.

**Comment by Bloodrocution** [comment]
Since your city is surrounded by water, maybe you have some "sea-horses"... -_-
