### ISSUE TITLE
Trade Route Speed

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#3943]
Lots of long trade routes being reported. Let's confirm:

a.) @Infixo: is the Lua UI function that gives out TR turn times accurate?
b.) @ilteroi: should we perhaps modify the TR distance calculation for routes? Right now routes allow TRs to be longer in distance, but they increase route turn length disproportionately (as trade units don't move faster on roads, they have a flat movement of 2/4).

Right now routes are set at a circuit minimum of 2, which I think is fine (means the absolute minimum for a caravan is 30 turns at standard). Is there a way we can return the number of route (or coast, for cargo ship) tiles to the function (without having to iterate over the route again in the TR length function) to give TR units a speed boost on them?

**Comment by Infixo** [comment]
UI doesn't compute anything, it takes num of turns from DLL directly.
Ideally it would be best to make caravans move faster on roads. It's weird that they move always 2 turns.
But the easiest way is to set min. 1 circuit. You still have min 30 turns, so it won't go down below that. That 30 turns is an additional condition, not related to num of circuits.

**Comment by LoneGazebo** [comment]
I believe it still can go below, as the target turns function is divided by the unit's move speed. Also, the -1 in that function (your note) is because the unit gets a free move on turn 0 (the -1 turn from the route).

**Comment by Infixo** [comment]
Free move on turn 1 means that the correct formula should be: iTurnsPerCircuit = (iDistance*2)/iRouteSpeed-1; But I was rather wondering if path.length() includes the starting tile. Because if it does and we get a free move, then it should be ((iDistance-1)*2)/iRouteSpeed-1.

That max in line 1139 assures that you won't go down below minimum num of turns.

**Comment by LoneGazebo** [comment]
the max makes sure (right now) that you do 2 circuits, so essentially it guarantees that your turns per circuit will be doubled, effectively negating the /2 for movespeed for caravans. such that Distance -1 * 2 is the route's length.

**Comment by LoneGazebo** [comment]
Since distance != the number of actual tiles (as some tiles are worth less/more), perhaps we should just change the route lookup for the pathfinder here to ignore terrain variables?

**Comment by Infixo** [comment]
If turns per circuit are already >= min turns, then there is no need to double it? Maybe such a check would be ok.
Distance is that routine IS number of tiles. This is actually different than usual meaning of distance. Check path.length(), it returns number of elements in a path table.

**Comment by ilteroi** [comment]
yeah this probably is a side effect of the normalized distance being used instead of tile distance. caravans should move faster if there is a route. need to check.

**Comment by ilteroi** [comment]
looking at the code, it's strange, it seems like caravans move exactly one plot per turn? 

	if (kTradeConnection.m_bTradeUnitMovingForward)
	{
		kTradeConnection.m_iTradeUnitLocationIndex += 1;
	}

but i know that's not true. so there's a secret here. can anyone shine a light on this?

**Comment by ilteroi** [comment]
ok, pushed a fix. not a 100% effective because of rounding. 

limited testing, and breaks savegames, but should work :)
