### ISSUE TITLE
Curiosity from Torment: Tides of numenera

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#3944]
Sorry to post here.  It's just easier to put an image.
![gazebo in a tombstone](https://user-images.githubusercontent.com/7407102/35872357-e72a4368-0b66-11e8-9a82-b97d47127a0b.jpg)

**Comment by tu-79** [comment]
It must be a cousin, because he's called Dread Gazebo, not Lone Gazebo.

**Comment by LoneGazebo** [comment]
Love it!

**Comment by LoneGazebo** [comment]
You know of the story of Eric and the Dread Gazebo, right? Is my namesake. :)

**Comment by tu-79** [comment]
Well, yeah. I knew the story. I read it in a comic long ago. Here the comic is called "Los caballeros de la mesa cuadrada" (the square table knights), about a group of DnD players. But I didn't know what Gazebo meant in spanish, so it wasn't until another player wrote the short story in the forum that I remembered.

By the way, there are about 3000 tombs there, it was just luck to find this.
