### ISSUE TITLE
Policy_(GreatWork)YieldChanges support for custom Great Work slots

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#3948]
Would it be possible to support my two new Great Work slots - Films and Relics - via the specific YieldChanges from Policies. 

Adding a **GreatWorkSlotType** to **Policy_GreatWorkYieldChanges** might work, or just **Policy_FilmYieldChanges** (GREAT_WORK_SLOT_JFD_FILM) and **Policy_RelicYieldChanges** (GREAT_WORK_SLOT_JFD_RELIC) ala ArtYieldChanges, depending on the complexity of either. 

Would save a bit of awkward Lua I have going now, which otherwise needs inserting everywhere the total of a given yield is calculated.

**Comment by LoneGazebo** [comment]
The second is easier, but - for the sake of my sanity - I had to make a few new type constants for it to work. 

Your great work slot types need to be called GREAT_WORK_SLOT_RELIC and GREAT_WORK_SLOT_FILM
and
Your great work types need to be called GREAT_WORK_FILM and GREAT_WORK_RELIC.

This should make them supported by everything in the DLL.

**Comment by JFDaly** [comment]
Neato, that works, thanks.

**Comment by LoneGazebo** [comment]
If it becomes necessary later on for you to be able to swap them around, that's a lot more fiddle-code, but I can do it.

**Comment by LoneGazebo** [comment]
[(1) Community Patch (v 88).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1704813/1.Community.Patch.v.88.zip)

**Comment by LoneGazebo** [comment]
Includes (hopefully) fixes for CID stuff.

**Comment by JFDaly** [comment]
Hm, seems that, whilst the yields for the Great Works do show on the Great Work tooltip, they don't actually get added to either the city yield total nor the player yield total; so the yields aren't actually being given.

Re. the CID stuff, this time, SetYieldModifierFromDevelopment/Crime appears to give raw Defense instead of a Defense modifier. I could work with this if there's no way back to the original way, though it's not ideal.

SetYieldFromDevelopment/Crime (that gives Happiness) is all good though.

**Comment by LoneGazebo** [comment]
Okay. For CID, I thought you wanted raw. I'll set it to a modifier (I think it has always been raw, maybe?).

**Comment by LoneGazebo** [comment]
For yields, are you setting a GreatWorkYieldType for buildings that have the GW slots?

**Comment by JFDaly** [comment]
Thanks. Can't really remember now, but it was intended as a modifier.

Yeah, they have the default Culture. Those base yields (Culture and Tourism) work, just not yields added through the new Policy tables. You can see what I mean below: the yields show up in the tooltip, but that's all.

![Text](https://i.imgur.com/BM4aD3q.jpg)

**Comment by LoneGazebo** [comment]
Ben-Hur in 4000 BC- Sci-fi, I guess? :)

**Comment by LoneGazebo** [comment]
Link me your mod(s) and I'll test. I need to walk the stack, see why it is balking.

**Comment by LoneGazebo** [comment]
Wait, nevermind, I see what's up.

**Comment by JFDaly** [comment]
Gah, am too slow. Sorry, was in the middle of setting up a tester mod since getting you to download all of JFDLC just for that is a bit much.

**Comment by LoneGazebo** [comment]
ohno, my bad.

**Comment by JFDaly** [comment]
Not a problem, I'll just be glad to have it working.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1705037/CvGameCore_Expansion2.zip)

**Comment by LoneGazebo** [comment]
Try that. Also made defense crime/development thing a modifier for you.

**Comment by LoneGazebo** [comment]
If that doesn't work, send em the tester mod you were making. :)

G

**Comment by JFDaly** [comment]
Yeap, that all seems to work now - Great Works and Defense modifier. Thanks much.

**Comment by LoneGazebo** [comment]
Fantastic!

**Comment by LoneGazebo** [comment]
if you decide you need swapping or whatnot, let me know. I may need to find some beer, though. :)

**Comment by JFDaly** [comment]
Kek, I'll keep it in mind but I don't think it's necessary. Thank.

**Comment by LoneGazebo** [comment]
🍻
