### ISSUE TITLE
movement bonuses

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3949]
i've always hated the whole "double movement in x" thing. why on earth should you be moving faster in bad plots than in good plots?

how about we change these promotions to:

* start with an extra move in feature x
* ignore feature costs (but not terrain costs)

should be fairly simple to implement, but of course it might have repercussions for iroquois/songhai

**Comment by LoneGazebo** [comment]
It's not great, but - since it is a balance concern - it probably makes more sense as a community call. I worry that opening this can of worms will make others think we're keen on changing all the movement promotions. :)

G

**Comment by ilteroi** [comment]
too much work

**Comment by LoneGazebo** [comment]
No worries - I think it is/was a good idea, but the effort is pretty major.
