### ISSUE TITLE
[CivFanatics] Cleanup of sticked threads ?

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#3951]
[KEEP] mean "to keep", [DELETE] mean "un-stick it because it takes place for nothing", and [???] mean I don't know.

[KEEP] "Community Patch - How to install" -> Good. Maybe rename it in "Vox Populi & Community Patch, How to install". Maybe add a link to the wiki somewhere ?

[KEEP] "DLC Modpack and 43-Civ Version Repository" -> The fact that it talks about multiplayer is far from obvious in the Title, and the 43-civ part is no longer needed now that it is in the auto-installer. If you can rename it, maybe "Modpack for multiplayer and singleplayer" would be better.

[KEEP] "Mods compatible with the Vox Populi (VP)" -> Good

[KEEP] "How to build and contribute to the Community Patch DLL" -> Good

[???] "Unified Changelog" -> Completely obsolete. Maybe edit the post to say it, so that new player know not to trust it too much.

[???] "Community Patch for BNW" -> Is it up-to-date ? Is this thread still useful ?

[DELETE] "Balance patch discussion and goals" -> That's OLD. Not sure this thread is needed now that we have a General balance sub-forum.

[DELETE] "Welcome to the Community Patch" -> So old... "The Community Patch project is going to be divided into two separate mods:1) The Community Patch 2) The Community Balance Patch..." Probably redundant with the "How to install" thread.

[???] "DLL Addition and request" -> is this post still used ?

[DELETE] "EUI Compatibility Files (11/16)" -> Probably redundant with the "How to install" thread

[KEEP] "Bug Report, Please Read !" ->  GOOD! The only improvement to do would be to give more details on "enabling the logs", because the linked tutorial does not say to enable all the logs, just one kind of log.

[DELETE] "Bug Report Wiki" -> Redundant with the thread "Bug Report, Please Read"

[DELETE] "Github Repository" -> Redundant with "Bug Report, Please Read" and ""How to build and contribute to the Community Patch DLL"

**Comment by Infixo** [comment]
I would suggest creating more precise instructions on how to enable logging, especially AI logs. People are constantly asking about it.

**Comment by tu-79** [comment]
Agree. Github things can be combined in "Bug Reports and Github Repository"

**Comment by LoneGazebo** [comment]
Done. Thanks for research!
