### ISSUE TITLE
Typo (2/7)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#3952]
_1. Mod version (i.e Date - 4/23):_
2/7

_2. Mod list (if using Vox Populi only, leave blank):_
VP+EUI (Automatic install)
IGE

---------------------------
1. Workshop
Workshop doesn't reduce poverty.
Please add BUILDING_WORKSHOP to the **BuildingHappinessMods.sql**.

cf.
(2) Community Balance Overhaul\Modular Elements\Happiness Mod\BuildingHappinessMods.sql
https://github.com/LoneGazebo/Community-Patch-DLL/blob/7982872e66d6f325e13229b3d0960c524bf328a1/Community%20Balance%20Patch/Modular%20Elements/Happiness%20Mod/BuildingHappinessMods.sql
![workshop](https://user-images.githubusercontent.com/11933188/35978084-1b8a5180-0d28-11e8-8584-87da22325eba.png)

---------------------------
2. Hanse
You need to add ''Reduces [ICON_HAPPINESS_3] Poverty.'' to the **TXT_KEY_BUILDING_HANSE_HELP**.

cf.
(2) Community Balance Overhaul\Balance Changes\Text\en_US\CivText.sql
https://github.com/LoneGazebo/Community-Patch-DLL/blob/7982872e66d6f325e13229b3d0960c524bf328a1/Community%20Balance%20Patch/Balance%20Changes/Text/en_US/CivText.sql#L428
![hanse](https://user-images.githubusercontent.com/11933188/35978101-23199794-0d28-11e8-985d-a9ec34b971d9.png)

---------------------------
3. Stone Works
You need to remove ", and reduces Poverty" from the **TXT_KEY_BUILDING_STONE_WORKS_HELP**.

cf.
(2) Community Balance Overhaul\Balance Changes\Text\en_US\BuildingText.sql

https://github.com/LoneGazebo/Community-Patch-DLL/blob/7982872e66d6f325e13229b3d0960c524bf328a1/Community%20Balance%20Patch/Balance%20Changes/Text/en_US/BuildingText.sql#L111

**Comment by LoneGazebo** [comment]
Thanks, just text typos (and a typo in the changelog). Workshop doesn't actually get the reduction.

**Comment by LoneGazebo** [comment]
The bank does. :)

**Comment by 8h42** [comment]
That’s good to know.
Thank you.

**Comment by 8h42** [comment]
4. Ostrog

You added SET DefenseHappinessChange = '-30' to the **BUILDING_KREPOST**.
Is it intended?
Ostrog doesn't replace Military Base.
![ostrog](https://user-images.githubusercontent.com/11933188/36022864-f20f1290-0dcd-11e8-8088-b74135457144.png)

**Comment by LoneGazebo** [comment]
Hmm. I’ll look.
