### ISSUE TITLE
AI ranged units have longer range

### ISSUE THREAD

**Issue by Voker57** [LoneGazebo/Community-Patch-DLL#3953]
_1. Mod version (i.e Date - 4/23):_
2.7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Units like Cruisers and Bazooka have range 2 instead of 1 when owned by AI (barbarians or civs)

**Comment by LoneGazebo** [comment]
They probably bought Range promotion.

**Comment by LoneGazebo** [comment]
Oh, wait, both those units have Range 2 anyways. Cruisers are Range 1 but start with Range promotion.

**Comment by Voker57** [comment]
Yeah, my mistake. I was under the impression that all naval units were nerfed to 1.
