### ISSUE TITLE
Stone works requirements

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#3954]
_1. Mod version (i.e Date - 4/23):_
2018-02-07

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
It seems that connecting Jade is not enough to build Stone Works. Is it intended?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![stone works jade](https://user-images.githubusercontent.com/7407102/35987399-d96ba5c8-0cfb-11e8-9a70-2c0b2b4d1361.jpg)

**Comment by Infixo** [comment]
Same as #3923

**Comment by LoneGazebo** [comment]
I think fixed with 2-7-2
