### ISSUE TITLE
Crashing immediately upon pressing the generate game button with Vox Populi pack

### ISSUE THREAD

**Issue by MrFestis** [LoneGazebo/Community-Patch-DLL#3955]
_1. Mod version (i.e Date - 4/23):_
February 7th 2018

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Crashing immediately upon trying to generate a game with only the Vox Populi pack installed, which I updated just today. Haven't played VP since the fall, but I wasn't expecting such a direct crash like this one when getting back into the game.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

[VP logs and dumpfile.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1708587/VP.logs.and.dumpfile.zip)

**Comment by MoiMagnus** [comment]
Looking at the database.log, it seems that for some reason all the tables/rows are duplicated, meaning that you are trying to load 2 times VP (or a similar mod).

Most probable issue is that you forgot an old modpack in the DLC folder.

**Comment by MrFestis** [comment]
I do have a a custom VP modpack lying around probably in the DLC folder. That's probably it.

**Comment by MrFestis** [comment]
Yes, I had an old modpack lying around. Thanks for helping a dummy.
