### ISSUE TITLE
trade route duration

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3956]
there's something wrong ... for an internal route to a neighboring city (4 road tiles) the preview shows duration 38 turns (seems a bit high on standard speed) but then it's finished after one turn and i have to select a target again. no time to dig deeper right now.

**Comment by LoneGazebo** [comment]
I fixed it in hotfix. Will upload my stuff later.

**Comment by LoneGazebo** [comment]
It’s at least a temp fix.

**Comment by Enrico-Swagolo** [comment]
Can confirm, if it's needed.

**Comment by LoneGazebo** [comment]
Even on the hotfix @Enrico-Swagolo ?

**Comment by Enrico-Swagolo** [comment]
Aye. Not 1 turn, but 2-5, so I guess the time it takes to make a full round from target to origin?

**Comment by LoneGazebo** [comment]
@ilteroi my guess is that the movespeed function you made is making the trade unit complete its max circuits too quickly, thus it is prematurely ending the route.

**Comment by ilteroi** [comment]
the speedup factor for roads is 5. so if the normal duration is 30 turns, we should end up at 6 turns for an all road trade route. not 1.

**Comment by LoneGazebo** [comment]
That's still way too fast, it should bottom out at the minimum duration of 30. That's probably where things are going wrong, then.

**Comment by ilteroi** [comment]
it's fixed. integer truncation problem when speed>distance.

anyway 30 turns seems like a long time ... i realize it's probably been that way forever, but now that it's so visible i don't like it :)

**Comment by LoneGazebo** [comment]
@ilteroi yeah, but let's keep it that way for now, as it has an impact on tourism/ottoman balance. :)

**Comment by LoneGazebo** [comment]
Let me know when you've pushed to github and i'll get to work on the hotfix.

**Comment by ilteroi** [comment]
it's pushed. i'll be back next weekend!

**Comment by LoneGazebo** [comment]
Tschüß!
