### ISSUE TITLE
God of All Creation Pantheon Belief Bug

### ISSUE THREAD

**Issue by Bloodrocution** [LoneGazebo/Community-Patch-DLL#3957]
_1. Mod version (i.e Date - 4/23):_

12/15

_2. Mod list (if using Vox Populi only, leave blank):_

![Mods used](http://puu.sh/zjJZk/5988097b40.jpg )

_3. Error description:_ 

_GoAC_ Belief is supposed to give +1 to food, production, gold, and science in the capital for every **two** Pantheons ever founded. Supposedly, that "every two" **_should_** also include the _God of All Creation_  Pantheon itself, as it is indeed a Pantheon that has been founded (if this is not the case, then that should be specified in the description of the belief imo). 

However, I noticed that in a 10 player game, after all 10 Civs founded their Pantheons, I am not receiving the expected (10/2)= +5 to those yields, but only +4 instead.

10 Pantheons founded ( could it be due to the fact that I haven't met the last 2 Civs  yet, perhaps? If so, is that itself working as intended?):
![Ten Pantheons](http://puu.sh/zjKkk/8bd5d85a72.jpg)
But only "+4 from religion" (10/2 = 4?):
![10 / 2 = 4?](http://puu.sh/zjKoQ/3c40d61cab.jpg)
![10 / 2 = 4?](http://puu.sh/zjKpN/f2ca8d0d3f.jpg)
![10 / 2 = 4?](http://puu.sh/zjKqt/c5860f2050.jpg)

et cetera. 

_4. Steps to reproduce (optional):_

Will attach my save file if necessary, but this one should be pretty straightforward to reproduce. 
[^why did my font get so big here? O.o]
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
It caps at 8 Pantheons. Been that way forever, I think it even says so on the tin?

**Comment by Bloodrocution** [comment]
On the tin? This is the Civilopedia entry: 
![GoAC](http://puu.sh/zjWav/3cb2352b9c.jpg)

**Comment by LoneGazebo** [comment]
Mm I’ll add back in the max text. Thanks
