### ISSUE TITLE
No Option to End War with Aztec

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#3958]
_1. Mod version (i.e Date - 4/23):_
2/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I had a 3 way war, and eventually the other two sued for peace. However, many turns later I don't even have the option to make peace with Monty. The make peace button doesn't even exist.

![image](https://user-images.githubusercontent.com/20593976/36013587-b00d0ac6-0d2a-11e8-8b2e-2a201decd924.png)

_4. Steps to reproduce (optional):_
Only interesting note is that Monty had 2 city flips go to me. Since that is the latest mechanic (and already had a few bugs), it might be there.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
No button mean "a contract forbid them to make peace".

If it's been less than 10 turns (scaling with gamespeed) of war, it's normal.

**Comment by LoneGazebo** [comment]
Yup.
