### ISSUE TITLE
Unsure bug or feature - Internal land trade routes amount of food granted increased with distance

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#396]
Same settings as #394 
To clarify, all my land internal food routes are giving the same amount of food, but the land route bewteen the two farthest cities is giving a greater amount.
Not sure Gazebo if these kind of topics is better post here or in the bug thread at civfanatic, please tell me for future situations, thanks.

**Comment by LoneGazebo** [comment]
I'll take a look. I know that internal routes scale s bit with era. Could it be that?

**Comment by Mitchsp** [comment]
Yes, but at the same moment/same era i've multiples land routes all giving I think 5,6 food and the longest route giving I think 7,1.
