### ISSUE TITLE
AI doesn't use recon units to fight even if it's a good idea

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#3960]
_1. Mod version (i.e Date - 4/23):_current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Basically title. I've fought a few wars where an AI has a Scout, often with 3x Shield skill (so heals 20 per turn), but refuses to use him against a group of rabble like my warriors and archers when there'd be nothing I could do as he'd be quite a wrench put in my plans as he's technologically superior.

**Comment by ilteroi** [comment]
they will attack if there's only one enemy that can be killed in a single attack. otherwise they are very careful with scouts.

**Comment by Enrico-Swagolo** [comment]
Yeah, I'd get if they were Pathfinders, but Scouts pretty much eat Warriors/Archers for dessert. Half the benefit of getting an upgrade ruin on a Pathfinder early is how strong the unit is with that vision and power. Catherine's had 1 scout 1 pathfinder hiding from my two archers, when the scout could kill them with his own bare hands as I think he's had heal every turn already. No point to going that route if you won't fight.
