### ISSUE TITLE
Tooltip not properly showing buildings which improve Plantation Luxuries (and possibly more?)

### ISSUE THREAD

**Issue by bridger15** [LoneGazebo/Community-Patch-DLL#3962]
_1. Mod version (i.e Date - 4/23):_
2/7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When hovering over certain resources, not all "boosting" buildings are being listed.

Example: https://i.imgur.com/aIXLY9r.png

This tooltip correctly shows that building a Granary (currently researched and therefore listed by itself in orange/brown) will boost this Bison tile.

However: https://i.imgur.com/aIXLY9r.png

Tobacco tooltip lists *no* buildings which will improve the title, despite the fact that the civolopedia clearly lists which building will improve it: https://i.imgur.com/DyFSCfu.png

In the above example, I have not yet researched Chemistry, so in the tooltip it should say "[blue]Chemestry [brown] Grocer" in the same way that the bison tile lists "[blue]electronics [brown] wind plant"

This appears to be a problem with most of the Plantation luxuries (buildings listed in civilopedia, and buildings themselves show the bonus, but the title tooltip is missing the building from the list).

Copper, for instance, works fine: https://i.imgur.com/VOtnBb4.png

To make things more confusing: https://i.imgur.com/OYvVvrZ.png and https://i.imgur.com/G3XUjw6.png

These two cities each have Silk adjacent to them.  Both cities are owned by me.  Each one has a plantation.  Neither of these cities has an Amphitheater (the silk boosting building).  Yet one tooltip clearly lists the Amphitheater and wind plant as boosting the tile while the other leaves out these buildings.

Attached is the save file for this particular game, but this is true of every game I've played in the last few weeks.  It's only recently that I've started to pay attention to which ones were problematic.  

[Silk Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1713505/Silk.Bug.zip)

**Comment by LoneGazebo** [comment]
EUI is unreliable in this regard. Nothing I intend to do. @Infixo might be interested in this, though.

**Comment by Infixo** [comment]
EUI in its tooltips uses GameInfo tables for quick and convienient access. Unfortunately not all DB tables are cached in GameInfo. Basically only Firaxis ones, not added by modders. So, new VP tables are not in GameInfo and are not displayed by EUI. E.g. in building tooltip you won’t find info about „specific GP rate increase” because this is a new table. I will check this particular case.

**Comment by bridger15** [comment]
Hmm, odd then that one silk resource shows the appropriate building but the other doesn't?

**Comment by Infixo** [comment]
@bridger15 I cannot load the save, because you are using Show Move-To (v 2) mod. Pls zip it and post here.

**Comment by Infixo** [comment]
This is something else, the table that holds that info is cached in GameInfo and EUI processes it. But there are other conditions checked. Only buildings that you actually can build are displayed (tech excluded).

**Comment by bridger15** [comment]
Attached.  Sorry, I didn't realize that one would cause issues loading saves.

[Show Move-To (v 2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1714798/Show.Move-To.v.2.zip)

**Comment by Infixo** [comment]
Fixed it :) Pls. test it. Put this file into (6a) EUI dir.
[PlotHelpManager.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1714846/PlotHelpManager.zip)
