### ISSUE TITLE
Default City Governor about to get impeached

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#3968]
![civ5screen0004](https://user-images.githubusercontent.com/15820785/36203451-a1ed29b0-1155-11e8-961b-773217ce9a6b.jpg)
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I cant see any reason why he wants to work engineer over the marble tile

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by deadstarre** [comment]
again with the engineer, but beyond that he prefers a 3F 1g tile to a 3F 3H tile. dude governs like Rob Ford on cocaine! 
![civ5screen0005](https://user-images.githubusercontent.com/15820785/36204296-c1eed224-1158-11e8-8232-5e043eb1c11e.jpg)

**Comment by Voker57** [comment]
You can't really expect city governors to be _that_ clever... That's what manual specialist control is for.

Governor here is attracted by science and GE points, I think. Safe default behavior.

**Comment by deadstarre** [comment]
no science, thats on the forge. 2nd pic showed he preferred engineer to a 2f 5h quarry - so that means hes willing to sacrifice 4 yields + lose an extra food just for GE points, thats nuts. but when i purchased the mission and it became 2f 6h that made up his mind for him and he started on the tile.

**Comment by Voker57** [comment]
Yeah maybe GE points are too valuable

**Comment by LoneGazebo** [comment]
I don’t see any issues. The governor tries to balance yields and have a few specialists at default.

**Comment by deadstarre** [comment]
you think the 3f 1g tile being preferred to 3f 3h is without issue as well?

**Comment by LoneGazebo** [comment]
Singular, odd tile choices are impossible to work with. Has to be systemic for me to bug hunt. My hundreds of spot checks have never revealed this kind of choice.

**Comment by deadstarre** [comment]
first pic shows him sacrificing 4 yields for engi, 2nd pic shows him wanting to lose 5 - that was in 2 turns in 2 dif cities, i dont think its a bug but rather hes giving too much weight to what id say is a wrong choice. the gold thing i see regularly in coastal cities, he wants to fight poverty is what im thinking so he prefers water tiles all the time to better land ones. if youre not seeing it though youre not seeing it, what can i say. thanks for the reply.

**Comment by ilteroi** [comment]
i think this is fairly reproducable ... here apparently 1f < 6p

![image](https://user-images.githubusercontent.com/1358966/36340916-7fb46280-13e6-11e8-9c05-10f4539ac2b6.png)

**Comment by LoneGazebo** [comment]
@ilteroi how close is the city to growth or starvation? That’s a big factor especially for very small cities.

**Comment by ilteroi** [comment]
unfortunately the details are lost to the mist of time, but you can barely see that the city only a single building and no specialists. so pop 3 and +3f. seems like a good opportunity to trade 1f for 6p.

**Comment by LoneGazebo** [comment]
@ilteroi it depends on how close the city is to growing, then. If an extra food can get you a new citizen one turn early at that size, the AI will often switch to that. Small cities tend to show the biggest flaws because of the low food requirements for growth - the AI wants a larger city as soon as possible in most situations.

G

**Comment by ilteroi** [comment]
don't think it was about to grow - pretty sure i observed this for several turns before taking a screenshot.

but anyway, this should be an easy situation to set up and check.

**Comment by LoneGazebo** [comment]
It's not high on my radar, as the governor does fine 95% of the time, but I'll put it on my list.

**Comment by Evutal** [comment]
![20180221183312_1](https://user-images.githubusercontent.com/36708387/36495833-d6f15a00-1736-11e8-848e-82923279beea.jpg)
Similar issue I think... There's no reason why the unimproved fish tile in the northwest should be worked over the improved fish tile in the southwest. There was also a turn when my capital had a ton of laborers instead of putting them towards tiles or specialist slots, unfortunately I didn't screencap that.

modversion 2.7.3, no other mods

**Comment by Voker57** [comment]
Did you skip the turn or click "redistribute" after improving the fish?

**Comment by Evutal** [comment]
> Did you skip the turn or click "redistribute" after improving the fish?

It's been improved for a while. I'm Venice and cannot redistribute in my puppets. So the automated assignment being not only somewhat iffy but just plainly preferring lower yields of the same type is kind of a big deal. It "fixed itself" after I improved the other fish next turn: stopped working the 2f1p field in the east and all was well.

But I do not check every puppet every turn so who knows how often these hiccups happen.

I just wanted to contribute that it's not only about obscure priorities leading to dubious choices like what deadstarre submitted, but seemingly a more fundamental problem.
