### ISSUE TITLE
[2-7-3] Improvement building time is off in EUI tool tips

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#3969]
_1. Mod version (i.e Date - 4/23):_
2-7-3

_2. Mod list (if using Vox Populi only, leave blank):_
(1) Community Patch\
(2) Community Balance Overhaul\
(3) CSD for CBP\
(4) Civ IV Diplomatic Features\
(5) More Luxuries\
(6a) Community Balance Overhaul - Compatibility Files (EUI)\
Calypso's Colored Religious Icons (Basic) (v 4)\
CivWillard for BNW (v 2)\
CPP CivPack (v 28)\
CPP TweakPack (v 47)\
CPP WondersPack (v 25)\
Cultural Capitals (Brave New World Edition) (v 16_5)\
FlagPromotions (v 7)\
Global - City Working Distance (v 7)\
Global - Civilians Move After Purchase (v 2)\
Global - Espionage Mapping (v 7)\
Global - Fortify Almost Healed (v 1)\
Global - Local Generals (v 2)\
Global - Pro-rata Buildings Purchase (v 2)\
InfoAddict (v 22)\
Ingame Editor (v 39)\
JFD's Cultural Diversity (Core) (v 13)\
JFD's Rise to Power (v 34)\
LiveTuner - Unit Panel (v 4)\
LiveTuner_-_Tech_and_Policy_Panels_(v_13)\
Religion - Recurring Purchase Notify (v 1)\
Sukritacts Events and Decisions (v 3)\
TerrainMod (v 7)\
UI - Gold Alerts (v 10)\
UI - Overlay Barbarians (v 8)\
UI - Promotion Tree (v 15)\
UI - Summary Specialists (v 11)\
UI - Trade Opportunities (v 28)\
UI - Unit List Enhancements (v 11)\
Units - Visible Trade Units (v 1)\

_3. Error description:_ 
EUI tool tips concerning turns to build improvements seems to be off. When I look at the tool tip it says e.g. Pasture 6 turns while it in fact takes 15 turns.  Haven't tested without other mods

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![bug_improvementturns](https://user-images.githubusercontent.com/6018459/36309799-4de839e0-1326-11e8-8cbb-eb0469faf7c4.jpg)

**Comment by LoneGazebo** [comment]
Probably a mod conflict.

**Comment by skodkim** [comment]
Probably. Do you know which (lua) file I should look for?

\Skodkim

⁣Sendt af BlueMail ​

Den 16. feb. 2018 18.16, fra 18.16, LoneGazebo <notifications@github.com> skrev:

**Comment by skodkim** [comment]
They're private mods I made myself (but partly based on other mods), i.e. tweaks to vanilla, Vox Populi (reference to the mod), building, civ and wonder additions etc. 99% pure sql, no interface related lua.

\Skodkim
