### ISSUE TITLE
PLAYER_EVENT_ADVISOR_DEBATE event CHOICE_3

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3970]
_1. Mod version (i.e Date - 4/23):_
last

_3. Error description:_ 
From description:
"Gain an injection of {2_InstantYield}. Banks permanently increase [ICON_GOLD] Gold output by 5%."

But when I choose event I get only gold increased in capital by that 5%. In others cities don't see increased gold and 5% gold modifier(all cities has banks).
Can post save if needed.

**Comment by LoneGazebo** [comment]
This is an enginseer event, send to him not me.

**Comment by bigcat88** [comment]
This is from basic events from VP. @TechpriestEnginseer  are you here?

**Comment by LoneGazebo** [comment]
Sorry, should clarify - the changes to this event were not done by me.

G

**Comment by TechpriestEnginseer** [comment]
I know why but it needs a rework on the effects then.

I can't exactly have it grant an instant yield of gold per city and increase 5% gold on all banks.

**Comment by TechpriestEnginseer** [comment]
@Hokath, do you have an alternative solution?

**Comment by Hokath** [comment]
So this has CapitalEffectOnly turned on? Just turn it off then? InstantYield of gold is empire wide, so it won't scale per city unless you turn on YieldBonusAllCities, no?

**Comment by Edaka** [comment]
Should be fixed now.
