### ISSUE TITLE
incorrect happiness breakdown

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3973]
check the picture:

![image](https://user-images.githubusercontent.com/1358966/36342998-7ebc215e-1406-11e8-968b-bf7912e858cc.png)

sigtuna has 8 unhappiness, that's correct. but the breakdown shows 16. city population is 8, if that has anything to do with anything.

**Comment by LoneGazebo** [comment]
Weird. My guess it that it is adding the value twice, maybe.

G
