### ISSUE TITLE
CTD with 2-7-3

### ISSUE THREAD

**Issue by grogzoid** [LoneGazebo/Community-Patch-DLL#3974]
_1. Mod version (i.e Date - 4/23):_
2-7-3

_2. Mod list (if using Vox Populi only, leave blank):_
 Active MOD:	d1b6328c-ff44-4b0d-aad7-c657f83610cd	(1) Community Patch	Version	88
 Active MOD:	8411a7a8-dad3-4622-a18e-fcc18324c799	(2) Community Balance Overhaul	Version	13
Active MOD:	eead0050-1e3f-4178-a91f-26cf1881ac39	(3) City-State Diplomacy Mod for CBP	Version	27
Active MOD:	c7bf7064-d1b1-4708-9e93-7a1560868582	(4) C4DF - CBP	Version	11
Active MOD:	24923240-e4fb-4bf6-8f0e-6e5b6cf4d3c2	(6a) Community Balance Overhaul - Compatibility Files (EUI)	Version	1
Active MOD:	be2d13ee-d18d-410e-8f04-7cd19cd99a98	More Luxuries	Version	155
Active MOD:	a4117a74-1a55-413d-bc64-88efa3cb37e3	Communitas Map	Version	1

_3. Error description:_ 
After a busy turn (I defeated Austria and Vassalized them, Then Montezuma DOW on Denmark, Denmark finishes Trader Sid's) The game hangs for ~2 minutes then finally CTDs during Denmark's turn.
Oddly the CvMiniDmp file is size 0.
[DenmarkCTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1734011/DenmarkCTD.zip)

_4. Steps to reproduce (optional):_
Load quicksave file, hit next turn

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Infixo** [comment]
It seems you have the wrong Luxuries mod. It should be (5) More luxuries.
