### ISSUE TITLE
tourism wtf

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#3975]
so as you might be able to tell, i'm currently enjoying an actual non-autoplay game of civ.

here's the next oddity (imho).

brazil is influential with almost everyone, except their immediate neighbors and one-time vassals indonesia.

![image](https://user-images.githubusercontent.com/1358966/36345356-09c96942-1429-11e8-9d04-b123165c4f20.png)

but how come? their tourism output is only half of mine (ethiopia), but i'm influential with only one.

![image](https://user-images.githubusercontent.com/1358966/36345438-92630118-142a-11e8-8e55-0983a6731269.png)

![image](https://user-images.githubusercontent.com/1358966/36345359-27e45388-1429-11e8-8399-fd6a43d2170b.png)

**Comment by LoneGazebo** [comment]
Their UA - the tourism output (+x) in the interface doesn't include their instant yields. It probably should, though...
