### ISSUE TITLE
Infinite CS tribute at turn after liberating

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#3976]
_1. Mod version (i.e Date - 4/23):_
last

_2. Mod list (if using Vox Populi only, leave blank):_
Enhanced Naval Warfare

_3. Error description:_ 
After I liberated a CS at that turn(I checked on next turn the same) I can demand tribute for any amount of times.(Imperialism+Autocracy)
In DiplomacyAI_MinorCiv_Log.csv there are such lines:

> 513, Denmark, Mogadishu, Unit Bully: Worker, Friendship: 175 to 218, Culture, MINOR_CIV_MOGADISHU, Success!, Bully Score: 12025
513, Denmark, Mogadishu, Unit Bully: Worker, Friendship: 218 to 272, Culture, MINOR_CIV_MOGADISHU, Success!, Bully Score: 2025
513, Denmark, Mogadishu, Unit Bully: Worker, Friendship: 272 to 340, Culture, MINOR_CIV_MOGADISHU, Success!, Bully Score: 2025
513, Denmark, Mogadishu, Unit Bully: Worker, Friendship: 340 to 425, Culture, MINOR_CIV_MOGADISHU, Success!, Bully Score: 2025
513, Denmark, Mogadishu, Unit Bully: Worker, Friendship: 425 to 531, Culture, MINOR_CIV_MOGADISHU, Success!, Bully Score: 2025
513, Denmark, Mogadishu, Unit Bully: Worker, Friendship: 531 to 663, Culture, MINOR_CIV_MOGADISHU, Success!, Bully Score: 2025

4. Screenshots (optional):

![20180218140519_1](https://user-images.githubusercontent.com/13381981/36351570-cd2c97d4-14b4-11e8-9572-d8b877422b11.jpg)

**Comment by bigcat88** [comment]
After CS build(or someone gift) usual fusilier - all becomes fine, so with 1 unit all is ok.

**Comment by LoneGazebo** [comment]
You didn’t state which version.

**Comment by bigcat88** [comment]
2-7
