### ISSUE TITLE
Trade Unit speed

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#3977]
@ilteroi trade units are doing a weird thing at short distances on roads in which they do 3-4 cycles at a time. You can replicate easily by setting two cities 4 tiles apart and put roads between them. Have a caravan trade between them and watch the drag race. Any ideas?

G

**Comment by ilteroi** [comment]
the speedup factor you get from roads is 5. so a caravan will move 10 tiles instead of the regular 2.

so one fully circuit plus a little bit per turn in your example. anything more is a bug, but then again who cares? i've never seen this but then i play with quickturns.

**Comment by LoneGazebo** [comment]
I think it causes long turn times for people who don’t use quick turns. But that’s a pretty small subsection of humans.

**Comment by Edaka** [comment]
What makes turns really long is that caravans and cargo ships move 1 tile at a time, stop, move again, stop again, rinse and repeat until the distance is covered. It was much quicker when they used to go the whole distance at a time.

**Comment by ilteroi** [comment]
ok, i removed the intermediate stops. that was vanilla behavior by the way, so actually they never moved the full distance in one go?

also, i've reduced the road speedup factor to 4 and the railroad speedup factor to 6. that does have some repercussions on religion spread etc. so you might want to ignore that change.

**Comment by Edaka** [comment]
Nice. I suppose the caravan movement is handled differently from all other land movement? Don't they get sped up on roads with technologies that make road movement faster? Is a fixed speedup factor the only feasible solution?

**Comment by ilteroi** [comment]
yeah, it's completely different code, but i'll check
