### ISSUE TITLE
Foreign Service Statecraft Policy bug

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#3979]
_1. Mod version (i.e Date - 4/23):_
2/7

_2. Mod list (if using Vox Populi only, leave blank):_
VP+InfoAddict

_3. Error description:_ 
Lowers quest rewards instead of increasing as stated.
![20180218200357_1](https://user-images.githubusercontent.com/13261433/36360181-2e729020-14e7-11e8-8fbb-4576fad1e236.jpg)
![20180218200347_1](https://user-images.githubusercontent.com/13261433/36360188-34c9be44-14e7-11e8-9736-886c05e60d4d.jpg)
![20180218200335_1](https://user-images.githubusercontent.com/13261433/36360195-3e0f0a68-14e7-11e8-8cef-5cc6f099d0a2.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
When you re-roll the quests after taking that policy, re-roll randomizer is rolled as well, so it can be lower. Is not a bug, just rare.
