### ISSUE TITLE
Getting raided on turn 7

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#3981]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

boy does this suck

![civ5screen0012](https://user-images.githubusercontent.com/15820785/36392691-765d2e16-157a-11e8-849c-77b85dfcf823.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
What difficulty ? (To see if its a bug or a balance concern)

**Comment by deadstarre** [comment]
deity. i dunno if its technically a bug or not but it definitely sucks =)

**Comment by LoneGazebo** [comment]
<EarliestBarbarianReleaseTurn>5</EarliestBarbarianReleaseTurn>

**Comment by Bloodrocution** [comment]
Had it happen to me before (yes, it's the worst). But I've also seen it happen to the AI too >:)

**Comment by deadstarre** [comment]
I dont see what it adds to the game if I build a unit as my first pick, and am getting raided before it can even finish, preventing the unit from completing. if i had to keep my starting unit home, id get zero ruins, then i may as well disable them- its just silly honestly. 


but anyway "earliest barb release turn" actually sounds to me like the first time a new barb could spawn from a camp, that is meant specifically for the earliest turn raiding is available to them?

**Comment by MoiMagnus** [comment]
If I remember correctly, It is the earliest turn barb can enter in your lands.

**Comment by deadstarre** [comment]
I tried looking it up, found a thread from 2013 where someone from the CEP is claiming its the first turn barbs could leave their camps (spawn a new one, in other words i do believe). but VP added extra barb outside of camps, so i wonder how that value affects those guys behavior, if at all. I know those 'extra' barbs are happy to chase my pathfinders around before turn 5

but if the value does boil down to the first turn any of them could enter my lands, then yeah thatd be great.

**Comment by Bloodrocution** [comment]
I'll throw another solution idea out there:
_Barbarian Resilience_ : City gains +20% ranged strength versus barbarians each time it is raided, capping at [x]%. Decays after 5 turns if not raided.
