### ISSUE TITLE
Movement circle graphic

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#3984]
https://forums.civfanatics.com/threads/quick-questions-quick-answers.573489/page-131#post-15043462
 A very insignificant issue. Basically, the circle would change colors in vanilla, but not anymore. Related to the relatively recent changes to how the turn amount to get to a location is displayed?
The vanilla behavior: http://www.grogheads.com/aar-civvpix/civV-279.jpg

**Comment by ilteroi** [comment]
yeah that's a side effect of the recent distinction between "can reach plot in X turns" and "can reach plot in X turns with moves left".

to do that we had to return fractional turn values from the pathfinder and modify PathHelpManager.lua accordingly. unfortunately the interface only allows for ints, so i simply multiply the turns by 10. apparently that turns the whole path grey. don't know where the colors are set. anyone?

**Comment by ryanmusante** [comment]
This is a shot in the dark, but does it have something to do with "MovementRangeBorder"?

```
Events.SerialEventHexHighlight( hexID, true, turn2Color, "GroupBorder" );
Events.SerialEventHexHighlight( hexID, true, turn1Color, pathBorderStyle );
```
