### ISSUE TITLE
Iroquois scouts are the worst

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#3989]
![iroqscout](https://user-images.githubusercontent.com/24731508/36499930-01ea4c10-1743-11e8-948c-3e4eb68dfeba.png)

Trailblazer 1 + Woodsman = only 3 moves in forests, I have no words :P

**Comment by ilteroi** [comment]
unfortunately those two promotions don't stack. the code is rather involved. i won't open that can of worms again.
