### ISSUE TITLE
 Dagda the Allfather not working when part of a religion.

### ISSUE THREAD

**Issue by jsaak** [LoneGazebo/Community-Patch-DLL#3992]
_1. Mod version (i.e Date - 4/23):_

2/7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Celt unique pantheon Dagda the Allfather not working when part of a religion.

_Savefile:_
[dagda.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1751146/dagda.zip)

**Comment by jsaak** [comment]
My bad. Sorry, i expected the yields on every city. But it seems capital gets it all.

**Comment by LoneGazebo** [comment]
Yep, it all goes to the capital/holy city.
