### ISSUE TITLE
Civilopedia inconsistenty with monastery

### ISSUE THREAD

**Issue by jsaak** [LoneGazebo/Community-Patch-DLL#3993]
_1. Mod version (i.e Date - 4/23):_

2/7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

In Civilopedia Monastery has a scientist slot, but it does not.

**Comment by Enrico-Swagolo** [comment]
Not only Civilopedia mentions a Scientist, the Monastery icon (when you can click to Faithbuy it) also does. I don't think the Policy screen mentions it, though.
