### ISSUE TITLE
Some Zulu units have two instances of the Morale Promotion?

### ISSUE THREAD

**Issue by Bloodrocution** [LoneGazebo/Community-Patch-DLL#3995]
_1. Mod version (i.e Date - 4/23):_
2/7/3

_2. Mod list (if using Vox Populi only, leave blank):_
![mod list](https://puu.sh/zrz7O/a9112bec98.jpg)

_3. Error description:_ 

![Morale x 2?](http://puu.sh/zv2CL/86e299150e.png)

Isn't Morale supposed to be a unique promotion? Moreover, the only two ways to get it are from the Heroic Epic Wonder and from building Orders as far as I know, and Zulu didn't have access to Orders in my game (and even if they did, from my past experiences, the Order's Morale did not stack with the Heroic Epic's unless that has been changed)....

_4. Steps to reproduce (optional):_

Not sure if this is exclusive to the Zulu, but I haven't ever seen this before, and no units besides the Zulu's in my game have more than one Morale on them.

**Comment by bigcat88** [comment]
Can you check without flag promotions mod?

**Comment by Bloodrocution** [comment]
How do I do that? Flag promotions mod is the only way to see what promotions enemy units have because it allows you to mouse over the icon. Otherwise, you have to guess purely based off the icon alone, and that doesn't help when several different promotions share the same triangle icon.

**Comment by LoneGazebo** [comment]
It’s from an event. There’s an event that gives a temporary extra morale.

**Comment by Bloodrocution** [comment]
Ah thanks. Mystery solved. Any possibility of adding a "turns-remaining" counter on the temporary Morale tooltip? It's a nightmare fighting against these units, stalemating against Shaka's Classical era units with my Medieval ones.

**Comment by LoneGazebo** [comment]
Not possible in the code sorry.

**Comment by Bloodrocution** [comment]
Gotcha.

**Comment by Bloodrocution** [comment]
@bigcat88, if the units belong to you, yes the promotion can be mouse's over on the UI, but not if the unit belongs to someone else (I wasn't playing as the Zulu in my case). Thanks though.
