### ISSUE TITLE
Crash to desktop late game

### ISSUE THREAD

**Issue by kingjm** [LoneGazebo/Community-Patch-DLL#3996]
_1. Mod version (i.e Date - 4/23):_
2/7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In the late game (> turn 350), crash to desktops happen when clicking tech tree.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[achievements_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756002/achievements_debug.log)
[APP.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756003/APP.log)

[CustomMods.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756004/CustomMods.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756005/Database.log)
[Gamecore.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756006/Gamecore.log)
[init_host.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756007/init_host.log)
[leaderboards.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756008/leaderboards.log)
[Localization.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756009/Localization.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756010/Lua.log)
[modding.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756011/modding.log)
[net_message_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756012/net_message_debug.log)
[SteamCloud.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756013/SteamCloud.log)
[stopwatch.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756014/stopwatch.log)
[system_init.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756015/system_init.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756016/xml.log)
[xml-perf.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1756017/xml-perf.log)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Alexander_0423 AD-2003.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1758494/Alexander_0423.AD-2003.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Infixo** [comment]
Attach save file with this situation. That is the only way to do anything about it.

**Comment by kingjm** [comment]
@Infixo It's not letting me upload the save file due to the format it's in

**Comment by Edaka** [comment]
Zip it into an archive and then attach.

**Comment by deadstarre** [comment]
G is aware of this already, he said it is because of EUI not clearing data as often as it should so it stores too much info, and then you load in a couple hundred images from the tech tree and it causes a memory crash

**Comment by kingjm** [comment]
@deadstarre that makes sense. I had tons of units in both games btw. If I install the non-EUI version, could I finish those games? Or would it not work?

**Comment by deadstarre** [comment]
its happened to me about a million times, it is never persistent so you should be able to load the latest save, click the tech tree and not immediately crash. as the game goes on, get in the habit of saving before you open the tech tree this way if it crashes you can just load back to the same spot

**Comment by Infixo** [comment]
Loaded, played 20 turns, no crash.
