### ISSUE TITLE
Hurricane Event Choice Availability

### ISSUE THREAD

**Issue by Evutal** [LoneGazebo/Community-Patch-DLL#3997]
_1. Mod version (i.e Date - 4/23):_ 2.7.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  The hurricane event triggered. I was unable to choose to "send in the military" despite having a garrison unit present and 1042 gold. However, the tooltip reads that I require 500 gold and I lack the required funds, so the game gives me no explanation as to why the choice is unavailable.
Attached screenshot shows the event window.
![hurricane_bug](https://user-images.githubusercontent.com/36708387/36644313-8fe6a636-1a58-11e8-9406-9cf3d4954a76.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Game setup is: Venice civ, Continents map, Huge size, King difficulty, Marathon speed.  Event triggered in a puppeted City. 
This happened once before in the same game, however since I had exactly 500g in the treasury I assumed it was just some weird timing thing, e.g. the event triggered before my gold was updated or something. But now I think the check for gold or the tooltip is incorrect. My best guesses would be that it checks for 500 gold/ turn instead of what you have or the cost is higher because of gamespeed scaling and the tooltip shows the cost for standard speed.

**Comment by MoiMagnus** [comment]
It is the gamespeed scaling.
The cost for this event in marathon is supposed to be 1500 if I remember correctly
