### ISSUE TITLE
AI naval units moving on snow

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#3999]
_1. Mod version (i.e Date - 4/23):_

2018 - 02 - 07
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Notice those two moroccan cruisers? They escaped and now are stationed over snow tiles, so my ironclads cannot hit them.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1760584/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Austria.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1760583/Austria.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![moving over snow](https://user-images.githubusercontent.com/7407102/36700970-c79e320c-1b51-11e8-829d-f3dede777475.jpg)

**Comment by bigcat88** [comment]
It is normal. In your borders your units can pass throw ice.
