### ISSUE TITLE
Olives plantation not visible (2/7)

### ISSUE THREAD

**Issue by TyborPL** [LoneGazebo/Community-Patch-DLL#4004]
_1. Mod version (i.e Date - 2/7):_
2/7

_2. Mod list (if using Vox Populi only, leave blank):_
Custom Advanced Setup;
Ingame editor

_3. Error description:_ No olives plantation visible

Save: https://mega.nz/#!jw1UmSYJ!Ma8oSnSuAxNDNe-3QkFY9iA0MNV1sBZiKTy12YjPyWo
Screenshot: https://steamuserimages-a.akamaihd.net/ugc/929302942062799066/7F81365DDB41BF25E2CA74BD3C67A9198CCC4D22/

**Comment by LoneGazebo** [comment]
Looks fine to me - are you sure you don't have a mod conflict somewhere?

**Comment by TyborPL** [comment]
Never used any other mods than VP and those two as support. When I finish this campaign, I'll install newest version and check it out again. Not so big issue after all...

**Comment by Edaka** [comment]
Can confirm the invisible plantations.

**Comment by LoneGazebo** [comment]
I see why, looks like it got turned into a farm somehow. ? Strange.
