### ISSUE TITLE
"I do not settle" promise giving negative opinion (2/7)

### ISSUE THREAD

**Issue by TyborPL** [LoneGazebo/Community-Patch-DLL#4006]
_1. Mod version 2/7

_2. Mod list (if using Vox Populi only, leave blank):_
Custom Advanced Setup
Ingame editor

100% sure was not settling new cities after the promises. (only buying tiles far away from them)

Screenshots: https://steamuserimages-a.akamaihd.net/ugc/929302942062801241/923830245A00F021EE756F798B027A1E8ECDA7FC/
https://steamuserimages-a.akamaihd.net/ugc/929302942062800374/224246E876F5D7564A811B2149EA6919509C6C26/

Save: https://mega.nz/#!jw1UmSYJ!Ma8oSnSuAxNDNe-3QkFY9iA0MNV1sBZiKTy12YjPyWo

**Comment by LoneGazebo** [comment]
That's just because of transparent diplomacy - it's telling you the turns until it ends, not the diplo mod.
