### ISSUE TITLE
Some breathing room for the tech tree

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#4010]
Three things:
1) I wonder why paper has a defined revealing technology, which is writing. Does it _need_ to have a reveal tech? I've been using a little mod-mod of my own where I've removed this feature and I haven't noticed any adverse repercussions yet. 

2) Same for Brazilwood. IMO, it doesn't actually need a reveal tech, as it is only created when you build the brazilwood camp that's unlocked at calendar, anyway.

3) The colonia issue, related to #3966 . I noticed you didn't add the CIVILIZATION_VENICE tag to it, did you forget or is there a different reason?

Resolving the 1 and the 3 would clean up some cluttered (>5 unlocked items) technologies for everybody. The 2 is for me, as I'm planning to release a mod-mod that modifies which resources are and which aren't revealed at the start and unlocked by the ancient techs, and freeing up a slot at Calendar is pretty big.

**Comment by LoneGazebo** [comment]
The 'reveal' tech on the tree is actually needed for trade. Paper isn't traded anymore, so it could go, but brazilwood is.

Colonia doesn't have the tag, as - if it does - it shows up on the leader screen and causes graphical issues.

**Comment by Edaka** [comment]
Re: trading, weird, brazilwood is the only luxury that currently has a reveal tech, yet we can trade all of them. 

Good point on the colonia, I forgot about that, although it doesn't look too horrible:
![image](https://user-images.githubusercontent.com/12978597/36922090-7016804a-1e6f-11e8-98d7-a7d0980bd48d.png)
I think that's a net improvement over occupying 3 different techs on everybody's tech tree.

**Comment by Edaka** [comment]
Oh, I see there's a column 'TechCityTrade' - is that what unlocks resource trading? It's different from 'TechReveal'.

**Comment by LoneGazebo** [comment]
Hmm. I think both are needed. Could be wrong.

**Comment by Edaka** [comment]
Yep, none of the regular luxuries, and neither the Indonesian ones, currently have a TechReveal, but they all have a TechCityTrade set at the same tech as their tile improvement.

**Comment by LoneGazebo** [comment]
Okay, we can scrap that then.
