### ISSUE TITLE
CS Quest failure feedback missing

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#4011]
2/27 (and olders)

![csquest](https://user-images.githubusercontent.com/24731508/36923440-9f33d642-1e6b-11e8-893c-8f090f652f8d.png)

I swear in vanilla it used to display the winner name(s) just fine; note: I already met all AI leaders.

**Comment by LoneGazebo** [comment]
It's just an EUI thing - it shows up in the notification log IIRC.
