### ISSUE TITLE
Caravansary description isn't updated

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#4013]

**Comment by LoneGazebo** [comment]
Where?

**Comment by Mitchsp** [comment]
Missing "added '+1 food and gold for every 3 desert or 3 tundra tiles worked by city' (2:1 for Burial Tomb)" and still appearing "Connection Gold Bonus".

![imagen](https://user-images.githubusercontent.com/13163824/36967519-42399160-2060-11e8-9414-252fa95d985f.png)

![imagen](https://user-images.githubusercontent.com/13163824/36967755-e76c2ecc-2060-11e8-887a-6da222d0a854.png)

**Comment by deadstarre** [comment]
@Mitchsp  my mod overwrites the caravansary description, to update the info for truffles yield etc. I havnt updated it since 2/27 released and i probably wont be until the next version release or sometime after that

**Comment by Mitchsp** [comment]
Upps, didn't think about. Just used your mod for first time in this game and didn't correlation that it was the offender. Btw, I'm liking it!
Sorry G for the false report.
