### ISSUE TITLE
Able to buy archeologists with faith without "Knowledge Of Devotion"

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4015]
_1. Mod version (i.e Date - 4/23):_
last

_2. Mod list (if using Vox Populi only, leave blank):_
Naval Warfare

_3. Error description:_ 
I choose Crusader Spirit. But I am able to buy archaeologists with faith...

_4. Steps to reproduce (optional):_
Will post savegame if needed.

**Comment by MoiMagnus** [comment]
Not the first time I see this reported. Each time "Not Reproducible", so a save may be useful

**Comment by LoneGazebo** [comment]
I need a save.

**Comment by bigcat88** [comment]
Very strange. Trying to find a save and in all saves I cannot purchase them. But I am sure that I purchased them with faith. Don't understand what happens. Looks like the bug disappears after save/load. In next game I will look at this closer. I will reopen if some new info will arrive.
