### ISSUE TITLE
Combat UI is wrong

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#4018]
_1. Mod version (i.e Date - 4/23):_

12/13

_2. Mod list (if using Vox Populi only, leave blank):_

InfoAddict

_3. Error description:_ 

First, both me and Songhai have authority's 10% combat bonus. My explorer also has morale (10%).

I. Explorer's withdraw chance shows up as combat bonus.
II. Explorer's final strength / raw strength: 22.5 / 15 => 50% bonus. I only see 35%, which is what it should be. Therefore final strength is incorrect.
III. Tercio's final strength / raw strength: 46.25 / 25 => 85% bonus. I only see 70%, which is also what it should be. Therefore final strength is incorrect.

![000](https://user-images.githubusercontent.com/4227288/36937452-6d2a67bc-1ee1-11e8-9887-e95e93c63d5a.jpg)

**Comment by LoneGazebo** [comment]
1. Is normal - that's just the UI being weird
2/3. Do you have the reformation for 15 CS? I wonder if the UI is being odd with that again.

G

**Comment by gamask** [comment]
Nope. We both have knowledge through devotion.

**Comment by LoneGazebo** [comment]
@Infixo you tinkered with the enemyunitpanel recently, any ideas?

**Comment by Infixo** [comment]
Not much. I just fixed the „below/above 50% health” issue.
But this code reads promos from DLL and also by its own, there might be some effects counted twice. The final value is taken from DLL however.
@gamask In both cases 15% is unaccounted for. Either some flanking issue or they have more bonuses that are not listed by UI.

**Comment by gamask** [comment]
I can't think of any bonuses that they should have that aren't already showing.

**Comment by LoneGazebo** [comment]
Do you have the save from this moment?

**Comment by gamask** [comment]
No, unfortunately.
