### ISSUE TITLE
Golden age production is lost on last turn

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#4019]
_1. Mod version (i.e Date - 4/23):_

12/13

_2. Mod list (if using Vox Populi only, leave blank):_

InfoAddict

_3. Error description:_ 

When you end a turn with 1 turn of golden age remaining, when next turn comes, golden age expires first, and THEN production is calculated. I didn't bother testing culture/gold.

Here's some proof.

![20180302230729_1](https://user-images.githubusercontent.com/4227288/36937492-25b2f2d6-1ee2-11e8-8dae-99d3fa8e1c09.jpg)
![20180302230759_1](https://user-images.githubusercontent.com/4227288/36937493-2762c5de-1ee2-11e8-8429-bd3a41a44929.jpg)
![20180302230922_1](https://user-images.githubusercontent.com/4227288/36937494-28e0c884-1ee2-11e8-8a7b-e3be46a292f8.jpg)

After 3 turns, our accumulated production is exactly Px3x1.2.
After 4 turns, it's exactly Px3x1.2 + P.

For natural golden ages I guess this isn't an issue, 'cause if the same logic applies (turn starts -> first golden age logic -> production logic) then you get one "free" turn at the start.
But for ones you start with a great artist, such as what you see in the screenshots, you clearly lose a turn.
To lose 1 out of 4 turns is a pretty big deal.

----------------
Now some tangential ramblings.

I suspect the same also happens with trade routes. Many times I've tried to finish a wonder with minimal overflow, only to be short one turn. Yes, I double check my math. Events always disabled. And yes I do account for instant yields, or barbs blocking tiles, or whatever. Things just don't add up.

I don't know if this is something deeply ingrained in the game logic, but it's worth looking at.

Ideally, whatever you see as your current production/science/culture/everything at the end of a turn, that should be what you get, without one thing then affecting the other.

The most annoying thing is when you have several trade routes that are curbing some poverty unhappiness, and they expire, sending you into the red, or below 10 for one turn. I'm reasonably confident that your science/culture for that turn are not what you were shown last turn, but the recalculated value. I've been short 1 turn on techs and policies before when on the previous turn it shows 1 turn to completion.

Does the same thing happen as with golden ages?
1. Trade routes expires, happiness is recalculated.
2. You get reduced yields 'cause you're suddenly unhappy. Possibly you don't even get the last turn of the trade route yields. Not 100% sure.

This particular issue is made even worse by the fact that the UI is pretty much never correct about trade route duration.

**Comment by LoneGazebo** [comment]
Unfortunately the game is designed to have player level things (like golden ages) end before cities are processed. There's no way around this.

**Comment by gamask** [comment]
Well that sucks. I expected as much, but was hoping maybe some magic is possible.
