### ISSUE TITLE
Double razing speed (from autocracy's martial spirit policy) doesn't work

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#4021]
_1. Mod version (i.e Date - 4/23):_

12/13

_2. Mod list (if using Vox Populi only, leave blank):_

InfoAddict

_3. Error description:_ 

Last time I observed this was with a city that was captured before the policy was taken.
But I don't think I ever saw this work in the normal situation of having the policy first, either.

**Comment by LoneGazebo** [comment]
Code looks fine to me.

**Comment by gamask** [comment]
Hmm, I'll check it out with the latest version. Soonish. And will post a save if it happens.

**Comment by LoneGazebo** [comment]
k

**Comment by gamask** [comment]
Extension changed to gif.

![bla4](https://user-images.githubusercontent.com/4227288/36940821-2d75ae54-1f1a-11e8-8560-60d424be9e7f.gif)

End turn, watch both Mongolian cities lose only 1 pop.

**Comment by gamask** [comment]
[BLA4.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1778781/BLA4.zip)

**Comment by LoneGazebo** [comment]
Aha, I see the bug. Fixed!
