### ISSUE TITLE
Taking honor policy while over supply doesn't grant any units

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#4023]
_1. Mod version (i.e Date - 4/23):_

12/13

_2. Mod list (if using Vox Populi only, leave blank):_

InfoAddict

_3. Error description:_ 

Took this policy in the late game, expecting two dozen free units. Got nothing.
Reloaded, made peace, waited for supply cap to rise (dissipating war weariness), took policy, got my two dozen units as expected.

**Comment by LoneGazebo** [comment]
You can't get units over your supply, that's intended.

**Comment by gamask** [comment]
1. It should clearly say that then.

2. If I'm under supply, then take this policy, I can units from all qualifiying cities, regardless of whether that puts me over supply (which it did, massively). Is that also intended?

**Comment by LoneGazebo** [comment]
can't say for certain, I'd need saves to test.

**Comment by gamask** [comment]
Now with 2/27 version.

**Comment by LoneGazebo** [comment]
Those files aren't readable - zip the saves and post them that way.
G

**Comment by gamask** [comment]
Right click -> save as -> rename worked just fine for me?

[DERKA.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1778778/DERKA.zip)

**Comment by LoneGazebo** [comment]
Got it, I see the issue. WIll fix.
