### ISSUE TITLE
Endowment for the arts buggy

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#4024]
_1. Mod version (i.e Date - 4/23):_
2/27

_2. Mod list (if using Vox Populi only, leave blank):_

VP + infoaddict
_3. Error description:_ 
Percentages are not correct. I've seen the GWAM bonus be different percentages, changing per turn

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20180301172019_1](https://user-images.githubusercontent.com/13261433/36940074-b95e55ec-1f01-11e8-9548-f0fbfb42362a.jpg)
![20180301172014_1](https://user-images.githubusercontent.com/13261433/36940075-c2481be8-1f01-11e8-9e64-396676f1cf0a.jpg)

**Comment by LoneGazebo** [comment]
The bonuses are different based on the values at stake, IIRC. @Infixo worked on this recently, he may chime in.

**Comment by Infixo** [comment]
They are correct. Bonuses for yields and GPs rate are scaled from 0 to 33% depending of relative score (basically techs and policies).

**Comment by LoneGazebo** [comment]
Okay, cool, just wanted to double-check.

**Comment by Edaka** [comment]
Looking at the screenshots, is it okay that the great writer gets +4%, while the engineer -22%, all on the same turn, same city? Shouldn't they mirror each other?

**Comment by Infixo** [comment]
No. There are 2 resolutions, one boosts GWAMs and nerfs Scientists, Engineers and Merchants, the other does the opposite. GWAMs are measured against "policy score" and GSEMs are measured against "tech score". If your relative score is different, you will get different numbers for each group.

**Comment by Edaka** [comment]
So in this particular case could it be that only +4% to GW means a high policy score and -22% to GM also means a high tech score?

**Comment by Infixo** [comment]
@Edaka Precisely. Endowment for Arts for GWAM is 0% if you are best up to +33% if you are worst with policies. And -33% for GSEMs if you are best with techs and 0% if you are worst.

**Comment by Edaka** [comment]
Thanks for the clarification! (:
