### ISSUE TITLE
when asked to stop buying land

### ISSUE THREAD

**Issue by BorussiaVox** [LoneGazebo/Community-Patch-DLL#4025]
_1. Mod version (i.e Date - 4/23):_
2-27

_2. Mod list (if using Vox Populi only, leave blank):_
Really Advanced Setup (v 15)
InfoAddict (v 22)
_3. Error description:_ 
If I comply with his request to stop buying lands next to him I get a -74 diplomatic modifier the next turn.
If I refuse to stop buying land I just get -15.

So this means he hates me more when I give in to his demands!?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![ignore 8930_20180304015441_1](https://user-images.githubusercontent.com/31174386/36940971-1443db44-1f48-11e8-9574-30f71514286b.png)
![promise 8930_20180304015207_1](https://user-images.githubusercontent.com/31174386/36940972-25365fbc-1f48-11e8-9b87-be88f4e2e059.png)

**Comment by LoneGazebo** [comment]
That is just a quirk of transparent diplomacy- what you see if the countdown for the promise, not actually a penalty.
