### ISSUE TITLE
Pioneers construct complementary buildings

### ISSUE THREAD

**Issue by JohannesGaessler** [LoneGazebo/Community-Patch-DLL#4029]
Mods: Community Patch Project 2/27, Wonder Race v.7, Faster Aircraft Animations v.3

The Aztecs get the Floating Gardens special building which is an improvement over the Water Mill building but can be built anywhere.
A city can still only have either a Well building or a Floating Gardens building.
However, when using a Pioneer to found a city that is not next to a River, both buildings will be constructed.

**Comment by LoneGazebo** [comment]
It happens because of the stack for the process of buildings, but - ultimately- it's fine.
