### ISSUE TITLE
Blank dialogues

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#403]
![8930_2015-07-05_00001](https://cloud.githubusercontent.com/assets/1131228/8513693/ce87f674-238e-11e5-9e0b-29cffbf41814.png)
![8930_2015-07-05_00002](https://cloud.githubusercontent.com/assets/1131228/8513694/d09da3be-238e-11e5-8d41-df7a52180535.png)
![8930_2015-07-05_00003](https://cloud.githubusercontent.com/assets/1131228/8513695/d3434772-238e-11e5-8703-5de5164f5232.png)
![8930_2015-07-05_00004](https://cloud.githubusercontent.com/assets/1131228/8513696/d7eff66c-238e-11e5-96b6-3c08263f4eb3.png)

**Comment by LoneGazebo** [comment]
Context?

**Comment by Radost** [comment]
Hard to guess the context when I don't know what they are saying.

**Comment by LoneGazebo** [comment]
Well, what era/time period?

**Comment by Radost** [comment]
The last screenshot shows the renaissance era and of all strategic resources only iron and horses are available for trade.

**Comment by LoneGazebo** [comment]
Do you have logging enabled from this save? If so, send me the diplomacy_messages file.

G

**Comment by Radost** [comment]
I followed whatever instruction was on the forums, however I don't have diplomacy_messages in my logs folder.

**Comment by LoneGazebo** [comment]
File is called DiplomacyAI_Messages_Log.csv

**Comment by Radost** [comment]
Don't have that file.
