### ISSUE TITLE
Request: show tooltip information for icon of building/unit also after production has finished

### ISSUE THREAD

**Issue by jantjeuh83** [LoneGazebo/Community-Patch-DLL#4038]
_1. Mod version (i.e Date - 4/23):_

2/27

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

When you are building something, and you mouse over the icon of the building/unit being produced, you get a nice tooltip with a lot of relevant information. However, once production is finished, the icon is still shown, but now it simply says 'No Production' on mouseover. I suggest showing the tooltip instead. See attached screenshot.

![tooltip](https://user-images.githubusercontent.com/23015914/37115287-047a6312-224b-11e8-948e-fee5627b6a6f.jpg)

**Comment by LoneGazebo** [comment]
That's an EUI quirk, not sure it can be addressed.

**Comment by jantjeuh83** [comment]
Ah, darn. It's rather annoying, especially when building stuff you're not 100% familiar with yet.

**Comment by TechpriestEnginseer** [comment]
It could be just it just needs someone to dive into that EUI code and find it.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer the key is whether or not the tooltip cache's the objects information or if it just caches the image. If just the image, there's no way for the UI to 'know' what was just stored without expanding the cache, which is a bad idea.
