### ISSUE TITLE
Tea Pavillion description/effect mismach

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#404]
It says 1 food per 2 citizens while it's actually 1 food per 4.
![8930_2015-07-05_00015](https://cloud.githubusercontent.com/assets/1131228/8513708/2917fc2e-238f-11e5-87a5-4be588d106b1.png)

**Comment by Radost** [comment]
This bug is still in place.

**Comment by LoneGazebo** [comment]
Forgot to change in compatibility files. Danke!
