### ISSUE TITLE
nonsensical promotion for barbarians

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4040]
![image](https://user-images.githubusercontent.com/1358966/37172583-89d94c50-2311-11e8-92fb-846ed1f496b5.png)

why do they get the brute force promotion?

**Comment by LoneGazebo** [comment]
That's weird.

**Comment by LoneGazebo** [comment]
Oh I know why, it's so that when attila picks them up he has the promotion bonus.
