### ISSUE TITLE
Sun God Pantheon Flood Plains +1 science not working

### ISSUE THREAD

**Issue by balla20** [LoneGazebo/Community-Patch-DLL#4049]
_1. Mod version (i.e Date - 4/23):_

3/11

_2. Mod list (if using Vox Populi only, leave blank):_

IGE(to speed up testing). Wasn't using when first encountered bug.
Really Advanced Setup

_3. Error description:_ 

No science yields from working floodplains for city with Sun God pantheon.
Wondering if this is a similar issue to the Goddess of Renewal bug that was recently fixed

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1801320/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Sun God Bug_Gandhi_0002 BC-3950.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1801327/Sun.God.Bug_Gandhi_0002.BC-3950.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![sungodbug](https://user-images.githubusercontent.com/8145711/37264453-6c7a8fa4-257b-11e8-9175-5041d5dccccb.png)

**Comment by balla20** [comment]
This still isn't proc'ing for me Just tested again with the new 3/11 version. Is this in an upcoming unreleased fix?

**Comment by LoneGazebo** [comment]
I'll look.
