### ISSUE TITLE
CTD while MP

### ISSUE THREAD

**Issue by Arsonil** [LoneGazebo/Community-Patch-DLL#4051]
_1. Mod version (i.e Date - 4/23):_
MP_MODSPACK_VP_3-7(No_EUI)

_2. Mod list (if using Vox Populi only, leave blank):_
(1) Community Patch (v 88)
(2) Community Balance Overhaul (v 13)
(3) City-State Diplomacy Mod for CBP (v 27)
(4) C4DF - CBP (v 11)
(5) More Luxuries - CBO Edition (5-14b) (v 155)
(6b) Community Balance Overhaul - Compatibility Files (No-EUI) (v 1)

_3. Error description:_ 
Crash after turn 36. All AI moves. It crashes on the barb turn. I guess they creating a new camp but I am not sure about that. Does it interfere with my Honor-policy? Loading a previous save doesn´t solve my problem it just crashe on the same turn.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
  

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1804136/Logs.zip)

4. Screenshots (optional):

**Comment by Arsonil** [comment]
Would be great if anyone is willing to help me <3

**Comment by Rinywd** [comment]
Barbs in multiplayer are notorious for crashing just fyi.  That and ruins.  Though to be fair ive been crashing in multi even with them off.

**Comment by MoiMagnus** [comment]
Never had crash in MP. (Always desync instead). Rarely, one player crash, but since we play in Pitboss, that's not a problem when it's not the host.

**Comment by Arsonil** [comment]
I also heard about this events. Do you turn them off? Or how do you handle events?

**Comment by Rinywd** [comment]
I turn off Barbs and Events and still get CTD

**Comment by ashendashin** [comment]
That modpack is really old and there has been some work on multiplayer since (as much as could be done anyhow). [Make one yourself](https://forums.civfanatics.com/threads/mpmpm-multiplayer-mod-dlc-hack-updated.533238/) (it's quick and easy!) or at least get one of the more recent ones later in modpack repo thread.

**Comment by MoiMagnus** [comment]
@ashendashin  I'm not sure the modpack is old. It says 3/7, so last week. (unless it means 3 of july, but I don't think so)

**Comment by ashendashin** [comment]
There's no 3-7 version this year. That's the title for the one I made for last years 3-7 release, which @LoneGazebo hasn't replaced in his post, possibly because no one bothers to consistently upload both EUI and without.

**Comment by Arsonil** [comment]
Anyone knows if there is a newer version of this modpack?

**Comment by MoiMagnus** [comment]
https://forums.civfanatics.com/threads/dlc-modpack-and-43-civ-version-repository.609278/page-12

> Latest EUI version with Religion Spread, Improved City View and Info Addict: https://ufile.io/kl53y

**Comment by Arsonil** [comment]
thx bro i´ll give it a try
