### ISSUE TITLE
Unlimited Social Policies

### ISSUE THREAD

**Issue by myles1718** [LoneGazebo/Community-Patch-DLL#4052]
_1. Mod version (i.e Date - 4/23):_
VP 3/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Getting unlimited Social Policies 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1804262/Database.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1804265/Lua.zip)
[xml.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1804267/xml.zip)
[IGE3.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1804273/IGE3.zip)

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
List of mods used:

> (1) Community Patch	Version	88
(2) Community Balance Overhaul	Version	13
(3) City-State Diplomacy Mod for CBP	Version	27
(4) C4DF - CBP	Version	11
(6a) Community Balance Overhaul - Compatibility Files (EUI)	Version	1
(7) Community Events	Version	4
(9) Wonders Expanded	Version	2
Buildings - Textile Mill	Version	4
Buildings - Upgrade System	Version	12
City Limits	Version	7
City States Evolved	Version	3
Civ 5 Extended City Radius	Version	1
Civic And Reform	Version	6
Community Patch Mod Compatibility	Version	14
Enhanced Naval Warfare for Vox Populi	Version	1
Enlightenment Era (Vox Populi)	Version	1
Faster Plot Expansion	Version	1
Free Buildings When Researched	Version	4
Global - 3 Units Per City	Version	1
Global - 5 Units Per Tile	Version	2
HNR Lite	Version	3
Improvement Upgrades	Version	1
Improvements in Water Tiles	Version	2
Industrial Building Pack	Version	2
Ingame Editor	Version	39
JFDLC (7) - JFD's Cultural Diversity (Core)	Version	16
JFD's Exploration Continued Expanded	Version	20
JFD's The Empire of Germany (Hitler)	Version	9
JFD's The Empire of Japan (Tojo) for VP	Version	7
JFD's The Russian Federation	Version	2
JFD's The United Kingdom of Great Britain and Northern Ireland	Version	5
JFD's The United States of America (Roosevelt) for VP	Version	4
Maps - Improved River Systems	Version	1
Maritime Battles+ (VP)	Version	18
Mechanized Infantry with Soldiers, Resized	Version	2
More City-Sates Luxuries	Version	3
More Luxuries	Version	155
National Wonder Collection	Version	3
Quick Turns	Version	10
R.E.D. Modpack	Version	27
Really Advanced Setup	Version	15
Renewable Energy	Version	1
Ressource - Mint Include Copper	Version	2
Strategic Buildings Pack	Version	2
Submarines Ignore Borders	Version	3
Sukritact's Events and Decisions	Version	3
Trading Posts Grow into Towns	Version	6
UI - TopPanel Changes (BNW)	Version	2
Uighur_Caesar's North Korea	Version	1
Unique City-States	Version	2
Units - Subs Ignore Borders	Version	3
Useful Oil Mod	Version	10
World Congress Reformation	Version	5

**Comment by MoiMagnus** [comment]
I already see an important problem: you don't have "(5) More Luxuries" as an enabled mod, and have "More Luxuries Version 155" instead. Which mean you are encountering a known bug of Civ mod manager (not Vox Populi fault)

You need to unsubscribe from the steam version of More Luxury, and delete its folder in your mod folder, and possibly reinstall Vox Populi. As long as the mod "(5) More Luxuries" is not loaded correctly by the Civ mod manager, you will have bugs.

**Comment by ashendashin** [comment]
Well yeah that's **A** problem. One of many, starting with mod count. I suggest cutting out everything besides ige, really advanced setup, quick turns, maybe cultural diversity and jfd civs (certainly remove exploration expanded), and everything from the mods repository.
