### ISSUE TITLE
minor empires

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4053]
is it intended that city states create armies now?

![image](https://user-images.githubusercontent.com/1358966/37360186-c7d8933a-26ef-11e8-9b00-2661746a7cc4.png)

and quite successfully ... check this four city empire!

![image](https://user-images.githubusercontent.com/1358966/37362510-ab208a94-26f5-11e8-85a1-32516d7588a1.png)

**Comment by LoneGazebo** [comment]
Yes, why not? That's a great little empire.

G

**Comment by ilteroi** [comment]
just asking - i like it

**Comment by jantjeuh83** [comment]
I love it, had a city state conquering the entire German empire after I supplied it with a few GDR's.
