### ISSUE TITLE
Tourism Anomoly

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4055]
_1. Mod version (i.e Date - 4/23):_
18-1-14

_3. Error description:_ 
The instant yields calculator on the top bar states that I've generated 108,158 tourism over the past 10 turns:
![18-1-14-1 instant yields](https://user-images.githubusercontent.com/34615525/37385153-693467fe-2718-11e8-9b09-0b5535356ada.png)
But I've only generated 115,175 tourism to Babylon (my first met and most influenced civ) over the entirety of my game (which would include any tourism bonuses I have with him. I would have had to generate less than 7017 tourism (not counting the bonuses I've had with Babylon) in the other 367 turns of my epic game. Does this seem possible?
![18-1-14-1 tourism screen](https://user-images.githubusercontent.com/34615525/37385175-7f62f040-2718-11e8-9b0a-0226e2ff1419.png)

---------------------------
Supporting information:
1. Log files:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1809749/Logs.zip)

2. Save game:
[Augustus Caesar_0377 AD-1734.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1809746/Augustus.Caesar_0377.AD-1734.zip)
[Augustus Caesar_0360 AD-1700.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1809748/Augustus.Caesar_0360.AD-1700.zip)

**Comment by LoneGazebo** [comment]
Probably a multiplication error. I’ll look.
