### ISSUE TITLE
Invisible Plantation on Olive

### ISSUE THREAD

**Issue by Zarrk** [LoneGazebo/Community-Patch-DLL#4057]
_1. Mod version (i.e Date - 4/23):_
3-11-1

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi No Eui

_3. Error description:_ 
Another user reported this issue 2 weeks ago, the problem has been identified and flagged resolved but apparently the fix hasn't been integrated in the current build. 
I had no problem hotfixing my game by switching the ImprovmentType from farm to plantation.

---------------------

**Comment by LessRekkless** [comment]
Screenshot taken with 18-3-11-1:
![18-3-11-1 olive plantation](https://user-images.githubusercontent.com/34615525/37572108-d94a82ce-2acb-11e8-8d88-50e821dd5239.png)

**Comment by UndeadDevel** [comment]
Happens for me as well on 2/27.

**Comment by Zarrk** [comment]
Problem corrected in the 03-31 beta build, I'm closing.
