### ISSUE TITLE
AI still moving siege units next to my cities

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#4058]
_1. Mod version (i.e Date - 4/23):_
3-11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The AI still moving siege units next to my cities.

_4. Steps to reproduce (optional):_
Forgot to save logs, will try to again.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
😠

**Comment by LukaSlovenia29** [comment]
Thanks for the reply. I haven't seen it science, so perhaps it's something that's been fixed 99,999999999999999% by you and I just stumbled onto the rarest of occurrences.
