### ISSUE TITLE
Monastery description incorrect

### ISSUE THREAD

**Issue by jantjeuh83** [LoneGazebo/Community-Patch-DLL#4059]
_1. Mod version (i.e Date - 4/23):_

3/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Description states it has 1 Scientist slot, but the building does not have a specialist slot.

_4. Steps to reproduce (optional):_

**Comment by UndeadDevel** [comment]
Duplicate of issue #4036
