### ISSUE TITLE
Freedom tenet Universal Healthcare doesn't give a free hospital to cities captured/founded after taking the policy

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#406]

**Comment by recred** [comment]
I also have this issue. 7/1 Version, CP/CBP/CSD/C4DF/EUI+Compat, More Lux, Infoaddict, Really Advanced Setup, Tectonic map script, Huge map, 18 civs, 34 CSs, Epic speed, Immortal, standard global difficulty.
