### ISSUE TITLE
Great Generals and Great Admirals not increasing Unit Supply when expended

### ISSUE THREAD

**Issue by CharlesDR** [LoneGazebo/Community-Patch-DLL#4061]
_1. Mod version (i.e Date - 4/23):_
3-11 (2018)

_2. Mod list (if using Vox Populi only, leave blank):_
VP, a few custom civs, YNAEMP

_3. Error description:_ 
Neither Great Generals nor Great Admirals increase unit supply when building a Citadel or performing a Voyage of Discovery.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Serind92** [comment]
Bug came with newest Hotfix, previous version was fine.
