### ISSUE TITLE
Game freezes during the AI turn

### ISSUE THREAD

**Issue by JohannesGaessler** [LoneGazebo/Community-Patch-DLL#4062]
_1. Mod version (i.e Date - 4/23):_
(3/11)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The game freezes during the AI turn (Greece)

_4. Steps to reproduce (optional):_
Load the game, press next turn.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1820062/Logs.zip)

5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[FREEZE.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1820073/FREEZE.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Edaka** [comment]
Sorry, crash reports from older versions usually aren't informative.
