### ISSUE TITLE
Player warmonger penalty far too high

### ISSUE THREAD

**Issue by SeyrenW** [LoneGazebo/Community-Patch-DLL#4063]
_1. Mod version (i.e Date - 4/23):_
3-11 (hotfixed)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

On the few marathon (map = large ) games I've tried so far, the AI does not incur seem to incur much (if any) warmonger penalties for conquering 1/4 to 1/3 of the map.

Yet, the human player upon taking just 2-3 cities along with some modest strategic pillaging of the enemies' fringe tiles will incur warmonger penalty far too quickly.

At one point, Zulu had taken over 1/3 of the landmass, but when I attacked them and only took a single city (puppet) while liberating a captured city state, their units had as much as +40~% anti-warmonger combat bonuses which is ironic and a little broken. Additionally, I was looking at anywhere between a 40-100+ diplomatic penalty across most civs, even from AI civ who were being conquered by the Zulu.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
Which difficulty?
Anti-Warmonger bonus is at most level^2 (so 7*7=49 in Deity)
It is halved in neutral territory, and null in ennemy territory.

Using only the infos you've given, I deduce you are most likely encourntering a bug.

**Comment by SeyrenW** [comment]
It's on Immortal difficulty.
