### ISSUE TITLE
AI city not building anything

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4064]
japan hasn't built a settler yet and right now they are not building anything at all ...

![image](https://user-images.githubusercontent.com/1358966/37540396-10e1c614-2957-11e8-8649-be2fc855a22f.png)

<details>
<summary>city production logs</summary>
<pre>
000, Japan, Kyoto, PRE: Unit, Worker, 150, 12
000, Japan, Kyoto, PRE: Building, Monument, 90, 10
000, Japan, Kyoto, PRE: Building, Shrine, 75, 10
000, Japan, Kyoto, PRE: Unit, Warrior, 44, 6
000, Japan, Kyoto, PRE: Unit, Pathfinder, 42, 7
000, Japan, Kyoto, PRE: Process, Farming, 25, 1
000, Japan, Kyoto, POST: Building, Monument, 1476, 10
000, Japan, Kyoto, POST: Unit, Warrior, 745, 6
000, Japan, Kyoto, POST: Unit, Pathfinder, 370, 7
000, Japan, Kyoto, POST: Building, Shrine, 112, 10
000, Japan, Kyoto, SEED: 9393584186023810375, CHOSEN: Warrior, Do not rush, TURNS: 6
006, Japan, Kyoto, PRE: Unit, Worker, 1800, 12
006, Japan, Kyoto, PRE: Building, Monument, 1550, 10
006, Japan, Kyoto, PRE: Building, Shrine, 1325, 10
006, Japan, Kyoto, PRE: Unit, Warrior, 244, 6
006, Japan, Kyoto, PRE: Process, Farming, 50, 1
006, Japan, Kyoto, PRE: Unit, Pathfinder, 42, 7
006, Japan, Kyoto, POST: Building, Monument, 4165, 10
006, Japan, Kyoto, POST: Unit, Warrior, 1745, 6
006, Japan, Kyoto, POST: Unit, Worker, 429, 12
006, Japan, Kyoto, POST: Building, Shrine, 375, 10
006, Japan, Kyoto, POST: Process, Farming, 50, 1
006, Japan, Kyoto, POST: Unit, Pathfinder, 25, 7
006, Japan, Kyoto, SEED: 4287590771366807154, CHOSEN: Monument, Do not rush, TURNS: 10
015, Japan, Kyoto, PRE: Unit, Worker, 1800, 9
015, Japan, Kyoto, PRE: Building, Shrine, 1325, 7
015, Japan, Kyoto, PRE: Unit, Warrior, 284, 5
015, Japan, Kyoto, PRE: Process, Farming, 50, 1
015, Japan, Kyoto, PRE: Unit, Pathfinder, 42, 5
015, Japan, Kyoto, POST: Unit, Warrior, 2174, 5
015, Japan, Kyoto, POST: Unit, Worker, 521, 9
015, Japan, Kyoto, POST: Building, Shrine, 456, 7
015, Japan, Kyoto, POST: Process, Farming, 50, 1
015, Japan, Kyoto, POST: Unit, Pathfinder, 29, 5
015, Japan, Kyoto, SEED: 9226602997854337020, CHOSEN: Warrior, Do not rush, TURNS: 5
020, Japan, Kyoto, PRE: Unit, Worker, 1800, 9
020, Japan, Kyoto, PRE: Building, Shrine, 1325, 7
020, Japan, Kyoto, PRE: Unit, Warrior, 284, 4
020, Japan, Kyoto, PRE: Process, Farming, 200, 1
020, Japan, Kyoto, PRE: Unit, Pathfinder, 42, 5
020, Japan, Kyoto, POST: Unit, Worker, 521, 9
020, Japan, Kyoto, POST: Building, Shrine, 456, 7
020, Japan, Kyoto, POST: Unit, Pathfinder, 394, 5
020, Japan, Kyoto, POST: Process, Farming, 202, 1
020, Japan, Kyoto, SEED: 10148045394038151226, CHOSEN: Worker, Do not rush, TURNS: 9
029, Japan, Kyoto, PRE: Building, Council, 3305, 7
029, Japan, Kyoto, PRE: Building, Shrine, 1325, 7
029, Japan, Kyoto, PRE: Unit, Worker, 300, 9
029, Japan, Kyoto, PRE: Unit, Warrior, 264, 4
029, Japan, Kyoto, PRE: Process, Farming, 200, 1
029, Japan, Kyoto, PRE: Unit, Pathfinder, 42, 5
029, Japan, Kyoto, POST: Unit, Warrior, 4143, 4
029, Japan, Kyoto, POST: Building, Shrine, 456, 7
029, Japan, Kyoto, POST: Process, Farming, 202, 1
029, Japan, Kyoto, POST: Building, Council, 155, 7
029, Japan, Kyoto, POST: Unit, Pathfinder, 116, 5
029, Japan, Kyoto, SEED: 17272940719045965935, CHOSEN: Warrior, Do not rush, TURNS: 4
036, Japan, Kyoto, PRE: Building, Council, 3005, 7
036, Japan, Kyoto, PRE: Building, Shrine, 1325, 7
036, Japan, Kyoto, PRE: Unit, Spearman, 1094, 7
036, Japan, Kyoto, PRE: Process, Farming, 50, 1
036, Japan, Kyoto, POST: Unit, Spearman, 4155, 7
036, Japan, Kyoto, POST: Building, Shrine, 456, 7
036, Japan, Kyoto, POST: Building, Council, 155, 7
036, Japan, Kyoto, POST: Process, Farming, 50, 1
036, Japan, Kyoto, SEED: 7401317950807490311, CHOSEN: Spearman, Do not rush, TURNS: 7
043, Japan, Kyoto, PRE: Building, Statue of Zeus, 7490, 19
043, Japan, Kyoto, PRE: Building, Council, 2905, 6
043, Japan, Kyoto, PRE: Building, Shrine, 1325, 6
043, Japan, Kyoto, PRE: Unit, Spearman, 1164, 7
043, Japan, Kyoto, POST: Unit, Spearman, 2809, 7
043, Japan, Kyoto, POST: Building, Statue of Zeus, 722, 19
043, Japan, Kyoto, POST: Building, Shrine, 487, 6
043, Japan, Kyoto, POST: Building, Council, 165, 6
043, Japan, Kyoto, SEED: 11041672826137606753, CHOSEN: Statue of Zeus, Rush if possible, TURNS: 19
060, Japan, Kyoto, PRE: Building, Council, 2905, 6
060, Japan, Kyoto, PRE: Building, Walls, 2040, 5
060, Japan, Kyoto, PRE: Building, Shrine, 1325, 3
060, Japan, Kyoto, PRE: Unit, Spearman, 1080, 6
060, Japan, Kyoto, PRE: Building, Mausoleum of Halicarnassus, 415, 21
060, Japan, Kyoto, POST: Building, Walls, 6210, 5
060, Japan, Kyoto, POST: Building, Shrine, 2320, 3
060, Japan, Kyoto, POST: Building, Council, 163, 6
060, Japan, Kyoto, POST: Building, Mausoleum of Halicarnassus, 92, 21
060, Japan, Kyoto, SEED: 9139758135135338433, CHOSEN: Shrine, Do not rush, TURNS: 3
063, Japan, Kyoto, PRE: Building, Council, 2905, 5
063, Japan, Kyoto, PRE: Building, Walls, 2240, 4
063, Japan, Kyoto, PRE: Building, Mausoleum of Halicarnassus, 915, 21
063, Japan, Kyoto, PRE: Unit, Spearman, 780, 6
063, Japan, Kyoto, POST: Building, Walls, 6667, 4
063, Japan, Kyoto, POST: Building, Mausoleum of Halicarnassus, 223, 21
063, Japan, Kyoto, POST: Building, Council, 175, 5
063, Japan, Kyoto, SEED: 10109275277279273201, CHOSEN: Walls, Do not rush, TURNS: 4
067, Japan, Kyoto, PRE: Building, Council, 2905, 4
067, Japan, Kyoto, PRE: Building, Forge, 2370, 9
067, Japan, Kyoto, PRE: Unit, Spearman, 780, 4
067, Japan, Kyoto, PRE: Building, Mausoleum of Halicarnassus, 615, 15
067, Japan, Kyoto, POST: Building, Council, 2467, 4
067, Japan, Kyoto, POST: Building, Mausoleum of Halicarnassus, 1936, 15
067, Japan, Kyoto, POST: Building, Forge, 74, 9
067, Japan, Kyoto, SEED: 12747227653472520574, CHOSEN: Council, Do not rush, TURNS: 4
071, Japan, Kyoto, PRE: Building, Forge, 2370, 11
071, Japan, Kyoto, PRE: Unit, Spearman, 780, 5
071, Japan, Kyoto, POST: Building, Forge, 453, 11
071, Japan, Kyoto, SEED: 6191835286322959767, CHOSEN: Forge, Do not rush, TURNS: 11
080, Japan, Kyoto, PRE: Unit, Spearman, 1070, 4
080, Japan, Kyoto, PRE: Building, Temple of Artemis, 1010, 8
080, Japan, Kyoto, PRE: Process, Defense, 100, 1
080, Japan, Kyoto, POST: Building, Temple of Artemis, 10373, 8
080, Japan, Kyoto, SEED: 16487058929893967211, CHOSEN: Temple of Artemis, Do not rush, TURNS: 8
086, Japan, Kyoto, PRE: Unit, Spearman, 1070, 3
086, Japan, Kyoto, PRE: Process, Defense, 100, 1
087, Japan, Kyoto, PRE: Unit, Spearman, 1070, 3
087, Japan, Kyoto, PRE: Process, Defense, 100, 1
088, Japan, Kyoto, PRE: Unit, Spearman, 1070, 3
088, Japan, Kyoto, PRE: Process, Defense, 100, 1
089, Japan, Kyoto, PRE: Building, Terracotta Army, 28575, 10
089, Japan, Kyoto, PRE: Building, Arena, 1970, 3
089, Japan, Kyoto, PRE: Unit, Spearman, 1070, 3
089, Japan, Kyoto, PRE: Building, Water Mill, 915, 5
089, Japan, Kyoto, PRE: Process, Defense, 100, 1
089, Japan, Kyoto, POST: Building, Arena, 4348, 3
089, Japan, Kyoto, POST: Building, Terracotta Army, 618, 10
089, Japan, Kyoto, POST: Building, Water Mill, 174, 5
089, Japan, Kyoto, SEED: 7165975372950360371, CHOSEN: Arena, Do not rush, TURNS: 3
090, Japan, Kyoto, PRE: Building, Terracotta Army, 28575, 8
090, Japan, Kyoto, PRE: Unit, Spearman, 1070, 2
090, Japan, Kyoto, PRE: Building, Water Mill, 915, 4
090, Japan, Kyoto, PRE: Process, Defense, 100, 1
090, Japan, Kyoto, POST: Building, Terracotta Army, 697, 8
090, Japan, Kyoto, POST: Building, Water Mill, 186, 4
090, Japan, Kyoto, SEED: 5687178454377835453, CHOSEN: Water Mill, Do not rush, TURNS: 4
094, Japan, Kyoto, PRE: Building, Terracotta Army, 28575, 7
094, Japan, Kyoto, PRE: Unit, Spearman, 1070, 2
094, Japan, Kyoto, PRE: Process, Defense, 100, 1
094, Japan, Kyoto, POST: Building, Terracotta Army, 743, 7
094, Japan, Kyoto, SEED: 4748019260785130937, CHOSEN: Terracotta Army, Do not rush, TURNS: 7
100, Japan, Kyoto, PRE: Unit, Spearman, 710, 1
100, Japan, Kyoto, PRE: Process, Defense, 100, 1
101, Japan, Kyoto, PRE: Unit, Spearman, 710, 1
101, Japan, Kyoto, PRE: Process, Defense, 100, 1
102, Japan, Kyoto, PRE: Unit, Spearman, 410, 1
102, Japan, Kyoto, PRE: Process, Defense, 100, 1
103, Japan, Kyoto, PRE: Unit, Spearman, 410, 1
103, Japan, Kyoto, PRE: Process, Defense, 100, 1
104, Japan, Kyoto, PRE: Unit, Spearman, 410, 1
104, Japan, Kyoto, PRE: Process, Defense, 100, 1
</pre>
</details>

**Comment by LoneGazebo** [comment]
That's weird. Never seen that bug before - did it persist after load or into the next turn?

**Comment by ilteroi** [comment]
check the logs ... it persisted for a while longer, finally they started building stuff again but of course they've already lost

**Comment by ilteroi** [comment]
[kyoto-no-production.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1820592/kyoto-no-production.zip)

here you are, hope it works for you. i think i'm still on 2/27 by the way.

**Comment by LoneGazebo** [comment]
ah, ok. 3-11 isn't compatible, so I'll see if I catch this happening. I can probably include a failsafe.

**Comment by ilteroi** [comment]
you can use a build from my branch but yeah, seems to be rare.

last thing they built was terracotta army, so probably they were in negative gpt ... maybe that blocks settlers too? also maybe they simply didn't have pottery yet. which is also bad, but in a different way.

**Comment by ilteroi** [comment]
ok, another push to shiny. improved AI army gathering. or rather, more aggressive removal of stalled units.

**Comment by LoneGazebo** [comment]
cool. fefe and bugfix are dead, long live shiny?

**Comment by ilteroi** [comment]
well i might need bugfix again but right now i'm happy. good night!

**Comment by LoneGazebo** [comment]
Night! I don't see your push, though. :)

**Comment by LoneGazebo** [comment]
Is it the 'minor changes' push?

**Comment by ilteroi** [comment]
another day, another update ... but this is the real deal, i swear

**Comment by LoneGazebo** [comment]
@ilteroi it breaks savegames, unfortunately - I'm going to issue the prior as a hotfix, and then make a beta branch.

**Comment by ilteroi** [comment]
really? i haven't broken compatibility for at least two weeks :) true story!

**Comment by LoneGazebo** [comment]
the new addition to CvArmy breaks it, unfortunately. :)

**Comment by ilteroi** [comment]
oh. right. well i've been sitting on that change for a while :)

**Comment by LoneGazebo** [comment]
ha.

**Comment by bigcat88** [comment]
From my last game start with last version(3-17): all civs has 3+ cities(some 5 cities) and Japan has only one city and doesn't have pottery. Is it normal?
[Logs - look at japan techs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1823026/Logs.-.look.at.japan.techs.zip)

**Comment by deadstarre** [comment]
my current game every civ has 5+ cities and japan still has only 1. it would appear something is up with japan
