### ISSUE TITLE
Exchange Markets Monopolies are Lost and Gained on Tech Research

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4069]
_1. Mod version:_
18-1-14

_3. Error description:_ 
Whenever a tech is researched, any monopolies gained from city-states using Exchange Markets are lost then immediately regained, once for each city state that has a luxury contributing to the monopoly:
![18-1-14-1 city state monopolies](https://user-images.githubusercontent.com/34615525/37549163-1fe7dc8e-2943-11e8-91eb-df442898f0ae.png)
This screenshot only shows Coral and Horses, but throughout the game, it's shown a bunch of the other city-state luxury monopolies as well.

_4. Steps to reproduce (optional):_
Gain a monopoly through Exchange Markets, then research a tech.

---------------------------
Supporting information:
1. Log files:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1821065/Logs.zip)

2. Save game:
[Caesar Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1821063/Caesar.Saves.zip)

**Comment by LoneGazebo** [comment]
You're on a very outdated version.

G
