### ISSUE TITLE
WC resolution Cold War periodically resets all trade routes with city-states

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#407]

**Comment by LoneGazebo** [comment]
Does anything trigger this? Changing alliances or whatnot?

**Comment by Radost** [comment]
It resets all and only CS trade routes, routes with other civs weren't affected.

**Comment by LoneGazebo** [comment]
When, specifically? When the resolution is passed?

**Comment by Radost** [comment]
The resolution was passed.
All trade routes get reset.
After reassigning all of them to CSes, they get reset again after some time.
Reassign some of them to civilizations, some to CSes.
On the next "cycle" only CS trade routes reset.

**Comment by LoneGazebo** [comment]
What do you mean by 'cycle?' That's what I'm trying to get at.
G

**Comment by Radost** [comment]
It resets every n turns. I didn't count exact amount of turns.

**Comment by LoneGazebo** [comment]
Was it regular intervals, or random?

G
