### ISSUE TITLE
Ice-locked Antiquity Sites

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4070]
_1. Mod version:_
17-12-1-1
_3. Error description:_ 
Antiquity sites can spawn in ice-locked snow:
![17-12-1-1 snow antiquity site](https://user-images.githubusercontent.com/34615525/37549652-f0112c0e-2947-11e8-9b15-b2ed47d89b2c.png)
I think this is a map-based problem, and has been an issue since Archaelogy was introduced.

Might I suggest that embarked Archaeologists gain the Ice-Breakers promotion along with Work-Boats at Ballistics?

**Comment by LoneGazebo** [comment]
Yup.
