### ISSUE TITLE
Siam doesn't get city-state influence bonus when first met

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4073]
_1. Mod version:_
18-3-11-1

_3. Error description:_ 
Is it intended that the bonus influence a Civ gets when first meeting a city-state is overridden by the Siamese UA instead of added?
![18-3-11-1 siam meets city state](https://user-images.githubusercontent.com/34615525/37558264-c4cf8920-29d6-11e8-855a-a2fe8be7040f.png)

**Comment by LoneGazebo** [comment]
Yes.
