### ISSUE TITLE
Wonder production penalty not applied?

### ISSUE THREAD

**Issue by FrankUnger** [LoneGazebo/Community-Patch-DLL#4075]
_1. Mod version (i.e Date - 4/23):_
3/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

UI explains the production penalty for the n-th wonder at length (which I like as an idea BTW) - but the additional 90% of production dont seem to be actually applied.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![20180318121931_1](https://user-images.githubusercontent.com/37502666/37565406-2eda64c0-2aa9-11e8-901b-d2b7c562c637.jpg)

**Comment by LoneGazebo** [comment]
It is. It is baked into the cost. Compare to civilopedia.

**Comment by FrankUnger** [comment]
It's baked into civilopedia cost as well, which led me on the wrong path. Nevermind...

**Comment by LoneGazebo** [comment]
Ah, must've been a change someone else did to the civilopedia, then. In any case, the base cost for the Great Wall is 250, so - 90% in addition is 475, guessing you're on Epic speed, thus the extra amount to 595.
