### ISSUE TITLE
inconsistency between GP improvements

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4076]
why does each manufactory add a bonus to the "hurry" ability of a great engineer but eg academies don't change anything about great scientist effectiveness?

**Comment by LoneGazebo** [comment]
Academies do affect it.

**Comment by LoneGazebo** [comment]
Towns as well IRC.

**Comment by ilteroi** [comment]
ok, then it's just about the tooltips which don't mention it

**Comment by tu-79** [comment]
How do Towns affect to Trading Mission?
