### ISSUE TITLE
fleet composition

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4077]
watch this excellent multi-party offensive against rome ... but unfortunately the fleets are almost exclusively frigates. so in the end they failed to capture antium and ravenna.

for a human a single melee ship would be enough but the AI should probably build some more.

![image](https://user-images.githubusercontent.com/1358966/37568307-b01bf7e0-2ad3-11e8-8a8b-eb8282df3103.png)

**Comment by LoneGazebo** [comment]
```
"MUFORMATION_PURE_NAVAL_CITY_ATTACK"	"UNITAI_ATTACK_SEA"	"UNITAI_RESERVE_SEA"
"MUFORMATION_PURE_NAVAL_CITY_ATTACK"	"UNITAI_ATTACK_SEA"	"UNITAI_RESERVE_SEA"
"MUFORMATION_PURE_NAVAL_CITY_ATTACK"	"UNITAI_ASSAULT_SEA"	"UNITAI_RESERVE_SEA"
"MUFORMATION_PURE_NAVAL_CITY_ATTACK"	"UNITAI_ASSAULT_SEA"	"UNITAI_RESERVE_SEA"
"MUFORMATION_PURE_NAVAL_CITY_ATTACK"	"UNITAI_ASSAULT_SEA"	"UNITAI_RESERVE_SEA"
"MUFORMATION_PURE_NAVAL_CITY_ATTACK"	"UNITAI_CARRIER_SEA"	"UNITAI_RESERVE_SEA"
"MUFORMATION_PURE_NAVAL_CITY_ATTACK"	"UNITAI_ATTACK_SEA"	"UNITAI_RESERVE_SEA"

```

We coud take 'reserve' out of here and/or only assign the reserve_sea AI to specific types of ships. Right now, any ship type fits reserve. In the past we had it this way because the AI was _horrible_ at organizing fleets. If they're better now (which it appears they are) a change makes sense.

**Comment by ilteroi** [comment]
well that's one way to improve, but why aren't they building more melee ships in the first place?

**Comment by LoneGazebo** [comment]
Because they're building units to fulfill those operations, and they're preferentially building ranged because they like to use strategic resources.

**Comment by ilteroi** [comment]
ok, new push, now they can capture antium :)

**Comment by LoneGazebo** [comment]
what did you do?

**Comment by ilteroi** [comment]
the particular problem here was that only one water plot is adjacent to antium, so you need to move in, shoot, move out again. this unit swapping in tight spaces didn't really work well. it's better now. not perfect but better.

**Comment by LoneGazebo** [comment]
cool!

**Comment by LoneGazebo** [comment]
This is pretty funny: https://youtu.be/1RDOnafzWy8

He's on the verge of losing his capital very early.

**Comment by MoiMagnus** [comment]
At this subject, is having the ice age event normal when disabling bad events ? Or is it a bug as claimed by Marb in the video ?

**Comment by LoneGazebo** [comment]
Technically Ice Ages are neutral.

**Comment by deadstarre** [comment]
AI catapult got distracted by stray units instead of maintaining its focus on the city. it could have 1) killed the garrison through attacking the city, and then taken the city. instead it settled for damaging peripherals

**Comment by deadstarre** [comment]
right here. actually shot over the city to hit the pathfinder behind it

![11](https://user-images.githubusercontent.com/15820785/37574091-b48a4afe-2af4-11e8-8f5f-3414ca02c6d2.png)

**Comment by LoneGazebo** [comment]
@deadstarre that's because the AI likes to sweep out potential new garrisons if it can.

**Comment by deadstarre** [comment]
if it was an archer thatd make great sense, but for a unit with %100+ city attack bonus which translates into massive damage on the garrison, its the rare occasion when attacking city and killing the current garrison while also hurting city HP isnt the correct move. I dunno if tactical can distinguish plans between siege units and regular ranged tho.

the other unfortunate thing, catapult missed a turn of attacking city on the way in. it didnt have to use last movement point crossing river adjacent to washington, but could have stopped 1 shy of there next to his horse and used the last movement to shoot from there. Wasnt lack of sight, horse was already there to light the way but i assume thats what ilteroi been working on lately

Marb is playing a god awful game tho lol I thought he deserved to lose right there =)

**Comment by LoneGazebo** [comment]
Went back and watched again and yeah the catapult should have hit the city. @ilteroi can we give city attack units a priority to hit cities?

**Comment by ilteroi** [comment]
well, there's already a tactical posture "surgical strike" where the AI is supposed to go for the city and ignore enemy units. but it's unclear whether that applied here.

other than that, attacks are scored by damage done, so the catapult naturally should prefer to attack the city (and any other unit should behave according to its specific set of bonuses). i need to set up a testcase and see, but maybe it's improved already with my latest changes, so hard to check.

**Comment by LoneGazebo** [comment]
@ilteroi in the event that a catapult can do more numbers damage to a unit than a city, however, I still think it should prioritize hitting the city. But yeah, let's see what newcode does. I'm testing it right now, going to toss a beta out soon. Any last minute changes?

**Comment by ilteroi** [comment]
nope

**Comment by LoneGazebo** [comment]
Awesome.

**Comment by ilteroi** [comment]
turns out there's a special check to prevent premature attacks on cities:

				//don't attack cities if the real target is something else
				if (currentPlot.isEnemyCity() && getTarget()->GetPlotIndex() != currentPlot.getPlotIndex())
					continue;

seems the attacks on cities were actually too lucrative :)

**Comment by LoneGazebo** [comment]
@ilteroi seems like a candidate for checking if the target-seeking unit is a good city attacker or not.

**Comment by ilteroi** [comment]
well the check is mostly for the benefit of melee units ... i think i can safely remove it for ranged.

pushed.

**Comment by LoneGazebo** [comment]
@ilteroi re settlement logic for the AI, I wonder if we could use the city connection method to estimate road distance for cities on the same continent? If, for example, a city would require a road that's over a certain value (or can't even make a road due to plopping a city inside someone else's empire), it won't do it. Same for overseas settlements and trade routes - if a TR can't reach the city from an owned city, don't plant it.
