### ISSUE TITLE
Lancer CS and Combat Multiplier Issue

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#4080]
_1. Mod version (i.e Date - 4/23):_
3-11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I see a Lancer in my current game that has a 43 base combat strength. Further, the final CS doesn't seem right. The multiplier of 106% on 43 should be 88, but the final result is 95.

Looking at a 2nd lancer, the base strength and combat stats are normal. I have not hit the next turn button, so these units are appearing with different stats at the same time.

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/37635099-ae54679a-2bc7-11e8-98f4-39fa61b3df58.png)

![image](https://user-images.githubusercontent.com/20593976/37635063-63825c86-2bc7-11e8-928e-60376e9864e8.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Need a save
