### ISSUE TITLE
Typo in William's (Netherlands) Dialogue

### ISSUE THREAD

**Issue by SeyrenW** [LoneGazebo/Community-Patch-DLL#4081]
_1. Mod version (i.e Date - 4/23):_
Latest hotfix but not the newest beta branch.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When you trigger war with William, he says 'So bet it' instead of 'So be it'.

**Comment by LoneGazebo** [comment]
He likes to gamble.
