### ISSUE TITLE
Morocco no longer able to pillage caravans during peace

### ISSUE THREAD

**Issue by SeyrenW** [LoneGazebo/Community-Patch-DLL#4082]
_1. Mod version (i.e Date - 4/23):_
Latest hotfix but not newest beta branch.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Playing as Morocco, you are unable to pillage trade routes during peace. Doesn't matter whether in neutral or your own territory, the pillage trade route option does not show up. 

Also, during war, you can only pillage trade routes if your unit is occupying the same tile as the trade unit. I don't think it's always been like that.

**Comment by LoneGazebo** [comment]
the latter has always been that way - are you sure you are on the unit while at peace?

**Comment by LoneGazebo** [comment]
I've checked, works fine. If they're sending the routes to you, you can't pillage them, just FYI.
