### ISSUE TITLE
city governor may be drinking again

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#4083]
_1. Mod version (i.e Date - 4/23):_

3/20

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

rob ford be hittin that tequila again, or maybe a fringe case? dont know but this is what turn 2 on 3/20 looked like 

![cg](https://user-images.githubusercontent.com/15820785/37688501-e0916500-2c76-11e8-9b2f-d6e3b2a4f0dd.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by deadstarre** [comment]
I locked the correct tiles, and on turn 3 all 3 were working the food tiles. looks like city gov thought food wasnt important because bucket was filled due to Spain UA

**Comment by deadstarre** [comment]
next game same deal
![33](https://user-images.githubusercontent.com/15820785/37688887-945e75c2-2c78-11e8-9970-e0a86b50b4c3.png)

**Comment by deadstarre** [comment]
seems to be in a bad habit of working the wrong tile close to growth. here we can grow in just 1 turn if he works the forest, because hes close to filling bucket he chooses the inferior tile though 

![33](https://user-images.githubusercontent.com/15820785/37690070-25798ed8-2c7f-11e8-9849-93ea0548e53f.png)

**Comment by LoneGazebo** [comment]
seems like an overflow issue for the food bucket. I'll look.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1832050/CvGameCore_Expansion2.zip)

Test.

**Comment by deadstarre** [comment]
it appears youve sobered him up

**Comment by deadstarre** [comment]
I havn't seen the starving thing at all with new dll, but I am seeing this right now. I don't understand why he wants to work the 2yield tiles vs the available 3 yield tiles

and on the next turn after growing, he automatically works the 3 yield tiles again

![civ5screen0018](https://user-images.githubusercontent.com/15820785/37759346-ae4c8e8a-2d89-11e8-8b5f-1b56a9b0ace4.jpg)

**Comment by LoneGazebo** [comment]
The city tries to hit targets for growth speed and yield averages. My guess is that the city is right on the edge of food and production average, so the city growth turns timer is pushing it over and under the edge for food v production.

**Comment by deadstarre** [comment]
@LoneGazebo still no bad issues with gov now, this DLL is a huge improvement over every gov i can remember at the moment

In my last game though I had diligence (1p per 2 citizen ) and earth mother (1p per 3 citizens)  and progress, along with an iron monopoly because it was all in my area. my cities were ridiculous production powerhouses and had to be way ahead of their goals for P, but i was still seeing them regularly choose on default an unimproved 2p hill over tiles which held 2f 1p, and also over 3f 1g coast. 

this created micro for me of course, but i have to note I only started noticing it happening around 8 citizens and beyond. before that, they were properly ignoring those hills in favor of the higher total yield tiles.

**Comment by LoneGazebo** [comment]
Cities do try not to 'overgrow' themselves - could be that.

**Comment by deadstarre** [comment]
perhaps, hopefully it could be rectified though. im looking at my 11pop capital right now, they prefer an unimproved hill over a 3f 1p tile. when i switch to food focus, they ditch my luxuries (and the hill) in favor of the 3f 1p tiles heh. 

i hear AI is a beast already, but this kind of micro for my cities will certainly give me an edge if the AI is happily trading 3f for 1p in their cities.

**Comment by LoneGazebo** [comment]
In the CP/Core Files/Core Changes/CoreChanges.sql, you'll find this:

```
--7
UPDATE Defines
SET Value = '18'
WHERE Name = 'AI_CITIZEN_VALUE_SCIENCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

--14
UPDATE Defines
SET Value = '10'
WHERE Name = 'AI_CITIZEN_VALUE_FOOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

--18
UPDATE Defines
SET Value = '14'
WHERE Name = 'AI_CITIZEN_VALUE_PRODUCTION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

--8
UPDATE Defines
SET Value = '12'
WHERE Name = 'AI_CITIZEN_VALUE_GOLD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

--15
UPDATE Defines
SET Value = '16'
WHERE Name = 'AI_CITIZEN_VALUE_CULTURE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

--5
UPDATE Defines
SET Value = '8'
WHERE Name = 'AI_CITIZEN_VALUE_FAITH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );
```

Try tinkering with the food/production values here, see if that changes anything in your situation. Right now production is rated higher than food because of its utility, but it may make sense to have them remain at parity.

**Comment by LoneGazebo** [comment]
It’s not 1:1.

**Comment by deadstarre** [comment]
some testing shows prod value 10 to be a big improvement, and the naked hill issue is gone even in a healthy surplus of food to the city. gov still appears to weight towards P overall though, because he preferred a 3P hill to a 2f 1p jungle which actually was giving 2.5f 1p due to herbalist. so.. long story short, i think 10 is good.

**Comment by deadstarre** [comment]
annnnd now im looking at a 5 pop city, a +9 food surplus and yet he chooses the 2f 1p over a 1f 4p tile. 

is there no middle ground with this guy =(

**Comment by LoneGazebo** [comment]
12 maybe?

**Comment by deadstarre** [comment]
12 seemed to be the point where the naked hill issue started. i've been exiting, changing the value and reloading a lot today...

anyway, at 6 pop he righted the ship and correctly chose 1f 4p over 2f 1p, still with the 10 value. i can live with that... if it must be something, thats preferable i think. 

do you think if the values were both 6 or 8 instead of ten, itd make a difference? its hard to trial and error without the understanding of the full picture on his thinking

**Comment by deadstarre** [comment]
ideally there is some value for food/prod that could be set that, barring other logic overrides, makes food and prod true equals. this way, he always go with the tile that grants the most yield on default, but would still be mindful of starving etc.

**Comment by LoneGazebo** [comment]
Well food evaluation changes based on growth rate, so it won’t always be equal.

**Comment by deadstarre** [comment]
This can't have anything to do with the production weight, if he trades 5p for 1f its obvious hes in desperation mode for food but in this case its premature, we aren't starving yet and the city can easily make that trade and be afloat in the same situation (looong turns to growth), but much better off going with a better tile that doesn't have food.
![civ5screen0023](https://user-images.githubusercontent.com/15820785/38467243-747e61ec-3b03-11e8-962b-85dde85b3705.jpg)

**Comment by deadstarre** [comment]
so i think its clear right, the code works by evaluating the longer the turns to grow, the more he weighs food yes? evaluating off of actual food surplus I think would be t
![civ5screen0027](https://user-images.githubusercontent.com/15820785/38468337-39180cac-3b12-11e8-9090-c64ae9af3c1a.jpg)
he way to go

**Comment by LoneGazebo** [comment]
I don't see an issue in either of those cities tbh - at 'default' the AI tries to balance it so that it's growing reasonably while also getting other yields. In both, dropping food for raw hammers would greatly slow down growth.

**Comment by ilteroi** [comment]
i for one would always prefer +5p3g over +1f, unless starving.

**Comment by LoneGazebo** [comment]
I'm going to soft cap the growth turns multiplier at 2x the citizen value of food. So it'll be a range of food value to food value x2. Should help control for situations like this while also making sure the AI grows reasonably (and that's why I have this at all - without it the AI can often neglect growth).

**Comment by deadstarre** [comment]
last note for prod value 10 - if the gold value isn't lowered as well, he seems to generally prefer 3f 1g to 3f 1p. 

setting the gold value to 10 as well seems to change that.

**Comment by LoneGazebo** [comment]
@deadstarre there's a soft minimum on the value, if you've reduced the food priority too much it will cause the governor to ignore food even if starving.

**Comment by deadstarre** [comment]
heres what is different though - Gov isn't automatically switching to better tiles now, its like the endofturn check he does to be on the best tile stopped working.

im a few turns into building a settler, gov is working a 1f 1p tile. now my borders expand and i pick up a 3f 1p tile. gov doesn't take it, turn ends. next turn, hes still not working it, turn ends. next turn I click on the city center button, now he automatically moves to the 3f 1p tile and my city gains 1p toward the settler production, that P he missed for multiple turns because he never checked there was a better tile.

**Comment by deadstarre** [comment]
well, now im not building a settler and when borders expand he picked up the better tile. no explanation for before though

**Comment by LoneGazebo** [comment]
@deadstarre it checks if it is 'dirtied.'

**Comment by LoneGazebo** [comment]
Ha - just means an external event 'dirtied' the data and told the city manager to recheck tiles.

**Comment by deadstarre** [comment]
naturally expanding borders are an external event right? normally they expand, and he takes it into account. for my settler-building example above he didn't though, i dunno if its related to settler building or something sporadic. i saw the other day a city with -0.4 in their food bucket, starving after a pop growth, automatically working the wrong tiles to make them starve, until I clicked City Center, and then he automatically moved onto the right tiles.

**Comment by LoneGazebo** [comment]
@deadstarre just looked and there's no check for changing tiles from acquiring a tile. That's...odd. I'll fix.
