### ISSUE TITLE
Strange "Corporations & Monopolies" UI issue on startup

### ISSUE THREAD

**Issue by geberriz** [LoneGazebo/Community-Patch-DLL#4085]
_1. Mod version (i.e Date - 4/23):_ 3/20 (beta)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ When I start the game up after initializing the core VP mods, regardless of map size, difficulty, or civ I pick, the game starts with the Corporations & Monopolies window open and it cannot be closed. Restarting the game from the menu does nothing; once, having quit out to the main menu, reloaded mods, and started up again, the error did not duplicate, but that only happened once. See screenshot and logs.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[civ 5 geberriz VP error log 3-20.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1831809/civ.5.geberriz.VP.error.log.3-20.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![corporations and monopolies ui problem](https://user-images.githubusercontent.com/31494990/37691534-08f35c12-2c89-11e8-8aee-a0851aa7359d.png)

**Comment by LoneGazebo** [comment]
mod conflict or bad install.

**Comment by deadstarre** [comment]
I saw the same bug on a corrupted save file, laptop had blue screened mid-game and thats what i was able to load back into, unplayable cuz the window wouldnt go away.

**Comment by MoiMagnus** [comment]
1) If you are playing with the "multiplayer modpack workaround" in order to create a modpack, this is normal, just continue the process and the resulting modpack will be ok.

2) In other cases, this is  almost certainly a mod conflict, so disable all the other mods, and check that you don't have any old modpack installed.

3) If that's not a mod conflict, just try reinstalling vox populi.

**Comment by geberriz** [comment]
I'm a dumbass! Somehow I had a non-VP version of CSD leftover from an earlier install. Sorry to trouble you with this. Lemme shoot you a paypal for your excellent work on this mod, by the way. Thanks so much.
