### ISSUE TITLE
GG not providing +2 supply with Citadel

### ISSUE THREAD

**Issue by Legedi** [LoneGazebo/Community-Patch-DLL#4086]
_1. Mod version (i.e Date - 4/23):_
3/11

_2. Mod list (if using Vox Populi only, leave blank):_
IGE

_3. Error description:_ 

game has one citadel that doesn't provide +2 supply, and one great general, that if planted also does not provide +2 supply.

_4. Steps to reproduce (optional):_

open game and plant GG

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[AutoSave_0164 AD-1040.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1831288/AutoSave_0164.AD-1040.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
#4061

**Comment by LoneGazebo** [comment]
this was fixed in the hotfix.
