### ISSUE TITLE
Weird border expansion

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#4087]
_1. Mod version (i.e Date - 4/23):_
18-3-20b

_2. Mod list (if using Vox Populi only, leave blank):_
Only UI mods

_3. Error description:_ 
My capital has expanded towards 2 stones and 1 cattle, ignoring 1 gold on grassland.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1834510/logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Babylon.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1834511/Babylon.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![expanding borders gold](https://user-images.githubusercontent.com/7407102/37727415-0dfbbff6-2d38-11e8-9383-f723e14d1268.jpg)

**Comment by LoneGazebo** [comment]
there's RNG in it, not a bug

**Comment by tu-79** [comment]
Ok, thanks!
