### ISSUE TITLE
Impi Spear Throw ability ignores rules for attacking out of cities

### ISSUE THREAD

**Issue by JohannesGaessler** [LoneGazebo/Community-Patch-DLL#4088]
_1. Mod version (i.e Date - 4/23):_
(3/17)

_2. Mod list (if using Vox Populi only, leave blank):_
Faster Aircraft Animations v3
Quick Turns v10
Wonder Race v7

_3. Error description:_ 
By default melee units that attack and kill a unit out of a city do not move into the tile of the killed unit.
When an Impi kills a unit with its Spear Throw attack it ignores this rule and moves out of the city.

_4. Steps to reproduce (optional):_
-Place an Impi in a city
-Kill an enemy unit with the Spear Throw attack

With the included save there is a city at the top of the map called Samoa where the bug can be reproduced.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1835474/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Impi Spear Throw bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1835472/Impi.Spear.Throw.bug.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
fixed
