### ISSUE TITLE
Settler Logic

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#4089]
@ilteroi ,

I spent a little while walking the stack in the plot evaluator for settling, and here are some things I observed:

1.) Area found values are in the millions and billions. Huge, huge numbers. Perhaps we should deflate values for tiles overall to get more sane numbers? I think the large values are causing any of the % modifiers (such as strategic modifiers) to grossly throw site evaluation out of whack.
2.) the function GetCityDistanceInEstimatedTurns seems to return erratic values, most often 42 (meaning of life?). I can't figure out why, but it doesn't seem to be working correctly.
3.) the m_iRingModifier array has uninitialized values in it that are max int values. They don't seem accessible, but we should probably init them to 0.
4.) the // where is our personal sweet spot? section is fine, but it doesn't penalize plots outside of our sweet zone. I think it should, scaling with distance. This will probably help deflate area values as well.

Cheers,
G

**Comment by ilteroi** [comment]
1 - no problem as long as there's no overflow, and there should be a protection against that
2 - 42 is the maximum and basically means "far far away"
3 - ok
4 - bonus within the preferred range is equivalent to a penalty outside

**Comment by ilteroi** [comment]
anyway, regarding the points from the forum discussion

* distance check: don't see any necessity for changes in the distance calculation (bugs notwithstanding). forward settling can be a smart move, but maybe should correlate to AI personality more closely. which flavor is relevant here? 
* development level / economic power of neighboring cities -> what is the reference? don't do this. look at military instead.
* cooldown for plot buying -> what's your opinion? could you implement this? maybe an exception for washington? also disable plot buying for pop 1 cities in general?
* failing to expand -> did you do anything about this?
* failing to defend -> there should already be a temporary tactical zone around a new settled city, but it's unclear what good it does. could also create a more heavily escorted settle operation, but what we really need is a permanent military presence. i'll look at the threat calculation.
* bad cities -> there is already a min hammers/min food check, i can increase that a little bit. also penalize plots adjacent to enemy territory. should we require at least one resource within ring 2 or so?

**Comment by LoneGazebo** [comment]
@ilteroi failure to build settlers seems to stem from the absence of a target (the ‘enough expansion’ strategy is turned on), which is why I moved to looking at the site selector code. Even then, in my test Persia was on a large island alone, built two settlers, but didn’t use them 100 turns later. Strange stuff. Your code looks good, so I don’t know what we’re missing.

**Comment by ilteroi** [comment]
any comments on the other questions?

**Comment by LoneGazebo** [comment]
Sorry, was away all day.

distance check: boldness is already included - perhaps we could look at grand strategy guesses? Not 100% accurate, but we can say that it is safer to forward settle a diplomat or a scientist than a warmonger. Can also look at how many cities they own that they didn't found (i.e. conquests).

development level / economic power of neighboring cities -> I think it's worthwhile for the AI to avoid settling a city in which it's ring 2 is within ring 3 of a neighboring civ, friendly or not.

cooldown for plot buying -> what's your opinion? we could add a cooldown, yes. we could also scale the cost based on city population in addition to owned adjacent tiles instead.

failing to expand -> i can't , really, until we figure out why the AI is sometimes - in the early game - not able to find a suitable city site nearby (as that's what is causing settlers to 'zero out.'

failing to defend -> we could set all ring1 tiles of a newly founded city as sentry spots.

bad cities -> i think a more stark distance drop-off is all we need. the AI picks decent spots overall, it just tends to settle too far away (or, in the mid-game, too often with little gain).

**Comment by ilteroi** [comment]
no worries. i added some tweaks, let's throw that out and get reactions first. it's pushed. testing ongoing ...

i really like the idea of a cooldown for plot buying, this something AI isn't too good at, so we need to nerf it :)

**Comment by LoneGazebo** [comment]
Yeah. I’ll look at a cooldown. Shouldn’t be too bad.

**Comment by ilteroi** [comment]
made some rash changes yesterday, please merge again

**Comment by LoneGazebo** [comment]
I’ve told you, never code angry. :)

**Comment by LoneGazebo** [comment]
Latest build looking good @ilteroi - I don't see any aberrant behavior.

**Comment by LoneGazebo** [comment]
Is this better, @ilteroi  
![image](https://user-images.githubusercontent.com/7849458/38067746-e34b8ee0-32db-11e8-983a-dd6c95fa51c5.png)

**Comment by LoneGazebo** [comment]
Venice on the warpath, yo.
