### ISSUE TITLE
Hidden antiquity sites appear under GPTI

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#4090]
_1. Mod version (i.e Date - 4/23):_
3-11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Hidden antiquity sites appear under GPTI, such as Academies. Not sure if a bug or intentional, but if it's intentional, I'd strongly urge a reconsideration of this or a discussion on civfanatics.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
As I know antiquity appears(creates by game) only in Industrial Era. So if improvement was constructed before Industrial - it is ok. But if improvement was constructed after someone reach Industrial(digs are already generated be game but is not visible) - there is a chance that there will be dig under GPTI.

**Comment by MoiMagnus** [comment]
Depend on when the GPTI was build. If it is an old GPTI, then it is a bug. If it is a recent one, it is probably in the category "bug that will not be fixed".

However, note that GPTI (and forts) are "indestructible", meaning that forein archeologist cannot dig on the tile.

**Comment by LukaSlovenia29** [comment]
I've been able to "destroy" AI's GPTI&forts by digging up hidden antiquity sites underneath them. That seems like a very powerful option, too powerful.
