### ISSUE TITLE
Moving into a city from a Road costs 1 movement point

### ISSUE THREAD

**Issue by JohannesGaessler** [LoneGazebo/Community-Patch-DLL#4094]
_1. Mod version (i.e Date - 4/23):_
(4/20b)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Moving into a city from a Road/Railroad costs 1 movement point rather than the reduced amount for Roads/Railroads.
Presumably this is unintended.
Moving out of a city still gives the reduced cost.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1843433/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Road into City.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1843434/Road.into.City.zip)

**Comment by ilteroi** [comment]
fixed
