### ISSUE TITLE
Great Generals and Great Admirals not giving unit supply

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#4095]
_1. Mod version (i.e Date - 4/23):_
3-11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Not getting unit supply 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![inked20180323211332_1_li](https://user-images.githubusercontent.com/13261433/37859404-3b36fb5c-2ee1-11e8-9357-f70d01a8d242.jpg)

**Comment by LoneGazebo** [comment]
this was fixed in the 3-17 hotfix.
