### ISSUE TITLE
Colonialism Policy bug

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#4096]
_1. Mod version (i.e Date - 4/23):_
3-11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I have two Monopolies that grant +10% production. With Colonialism, I should be getting +40% in total from those. However, you can see that my city is only getting +30%

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20180319184030_1](https://user-images.githubusercontent.com/13261433/37859484-6b329360-2ee2-11e8-96a5-447687d4b063.jpg)
![20180319184042_1](https://user-images.githubusercontent.com/13261433/37859485-6b438b34-2ee2-11e8-92be-8ec0d5627185.jpg)
![20180319184047_1](https://user-images.githubusercontent.com/13261433/37859486-6b72ff18-2ee2-11e8-9a89-5220bc0daa54.jpg)
![20180319184056_1](https://user-images.githubusercontent.com/13261433/37859487-6b891604-2ee2-11e8-9b05-a0491a5ad185.jpg)

**Comment by LoneGazebo** [comment]
It's not a bug, it's just that the policy text is worded somewhat oddly - it doesn't intrinsically double the bonuses, it simply gives you 10% more on top of whatever you get.

**Comment by TechpriestEnginseer** [comment]
Which is his problem. He thought the policy would grant +10% Production to EACH monopoly he got rather than to the same type of monopoly.

**Comment by LoneGazebo** [comment]
Right. But it’s not a bug! :)
