### ISSUE TITLE
Making an equal deal with more CS Allies counts as Winning a War

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#4099]
_1. Mod version (i.e Date - 4/23):_
March 17, 2018 version

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Made peace with Portugal after I was payed to go to war with them.  Never fought them.  Peace was equal, except I had a CS Ally which was included in the deal. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![20180324163702_1](https://user-images.githubusercontent.com/11430209/37870068-f1cc9778-2f81-11e8-8ac9-580b367ece54.jpg)

**Comment by LoneGazebo** [comment]
Not exactly the case - the issue is that the AI lost the war but didn't have anything to offer, so it looks like a white peace, but it technically wasn't.

G

**Comment by LoneGazebo** [comment]
Anyways I've been meaning to tie it to warscore, seems like a good time to do so.

**Comment by LoneGazebo** [comment]
Fixed.
