### ISSUE TITLE
Imperialism: Ironsides displayed as bushido

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4100]
_1. Mod version (i.e Date - 4/23):_
20b March

Subj. Can it be replaced with "ironsides" name?

![20180325120729_1](https://user-images.githubusercontent.com/13381981/37873425-57ae6c08-3025-11e8-9a69-c24c02588556.jpg)

**Comment by TechpriestEnginseer** [comment]
I believe it is Japan's old UA name for it considering that's ironside's effect. It should be replaced with something generic instead of Ironsides like a motto to represent fighting harder when harmed.

**Comment by LoneGazebo** [comment]
Fixed.
