### ISSUE TITLE
Imperialism: Civilizing Mission -  EUI bug 

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4101]
_1. Mod version (i.e Date - 4/23):_
20b March

Look at screen:

![20180325162306_1](https://user-images.githubusercontent.com/13381981/37875515-4a29d558-3049-11e8-87f2-b4193f8363f5.jpg)

**Comment by bigcat88** [comment]
Ok, it is just an EUI display bug. @Infixo can u do something with it in future?

**Comment by bigcat88** [comment]
Ok, I build courthouse but nothing changed. No boost from it as it displayed. No matter what building from what era. Need a savegame?(only Naval Warfare mod is present, so almost no mods)

**Comment by bigcat88** [comment]
The same in puppet cities(only now I looked at them). Boost displayed in them, but has no effect at all. So it's not and EUI bug.

**Comment by Infixo** [comment]
@bigcat88 Can you pls explain what is the issue? I can't get it just from looking at the screen, sorry.

**Comment by bigcat88** [comment]
No, it is not an EUI bug as I understand. Look at screen on production:
56.75 + 110% != 85.12
But if we don't calculate that 60% from Imperialism policy we get what we see in total: 
56.75 + 50% = 82.12 
So production % from policy is displayed by EUI but doesn't count in total. Is it bug in dll?

**Comment by Infixo** [comment]
Ok, i see now. 60% is displayed but not applied.
I modified all tooltips so they basically display data from dll. If EUI adds something, it has a bit different format. Anyway. I’ll take a look into dll.
What is this Civilizing mission? I need to track it in the dll.

**Comment by Infixo** [comment]
Just as I suspected, the 60% was retrieved and put into the tooltip but not added into the actual multiplier. Easy fix.

**Comment by bigcat88** [comment]
And another thing. Maybe it is now a question for Gazebo or maybe Infixo u can answer. Description says: "puppet city or occupied city with a courthouse" - but on screen you can see that I haven't a courthouse. 
So it will be fixed(or maybe already) or it another bug?

**Comment by Infixo** [comment]
Yeah, that piece of code has some logic related to Puppet Cities. I don't know how exactly how it is supposed to work, sorry. @Gazebo pls look into that.

**Comment by LoneGazebo** [comment]
I've fixed.

**Comment by LoneGazebo** [comment]
Thanks @Infixo for looking into it.
