### ISSUE TITLE
Expansion promise broken by revolution

### ISSUE THREAD

**Issue by lilmaddiekins** [LoneGazebo/Community-Patch-DLL#4102]
_1. Mod version (i.e Date - 4/23):_    3/20b

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  I acquired a city through unhappiness revolution, which broke my promise not to expand in another civ's territory.

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
Hmm. Unfortunate, but there's not really an easy way to change this, as the update logic can't account for cities acquired through revolution.

**Comment by bigcat88** [comment]
Instead of `Raze` option we need `Cancel`. If it is possible.
Strange that city is unhappy and want to join another civ that will genocide/raze them.

**Comment by LoneGazebo** [comment]
Not feasible due to the network model. In the abstraction of civ, it's best to assume that the people flipping are desperate. :)
