### ISSUE TITLE
Don't Build these Buildings

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4103]
City-State quests can conflict with custom civs who have dummy units and non-dummy buildings that are dummies. There should be an entry to be added in Buildings for these CS quests to ignore.

**Comment by LoneGazebo** [comment]
There is -> IsDummy

G

**Comment by TechpriestEnginseer** [comment]
Huh, I forgot that could work to non-dummy buildings too.
