### ISSUE TITLE
Forced Deals

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4109]
Just like how you can force peace, war, denouncing, and DoF through Lua.

Would it be possible to force capitulation, vassalization, trade deals, and open borders the same way through Lua?

**Comment by LoneGazebo** [comment]
Unfortunately no, as there's a ton of pseudoclass and struct work that has to happen for the DLL to register the events. You could trigger the bools for open borders or vassalage through lua, but not trade deals.

**Comment by TechpriestEnginseer** [comment]
Well the bools for open borders and vassalage is my intentions anyway.

**Comment by LoneGazebo** [comment]
I can expose them to lua if they're not already.

**Comment by LoneGazebo** [comment]
edit: looks like SetOpenBorders for Teams already exists. Same for DoBecomeVassal and DoEndVassal

**Comment by TechpriestEnginseer** [comment]
Aren't open borders assigned to players? So Player B of Team A can still keep their borders closed to Player C if Player A decides to open his borders to Player C.

**Comment by LoneGazebo** [comment]
Yes. So you'd have to set/unset both at the same time if you want bilateral treaties.

**Comment by TechpriestEnginseer** [comment]
Fair enough.

**Comment by TechpriestEnginseer** [comment]
DoBecomeVassal and DoEndVassal do they distinguish on Capitulation and Voluntary Vassalization?

**Comment by TechpriestEnginseer** [comment]
Never mind.
