### ISSUE TITLE
Vassalage UI quirks

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#4111]
According to Borussia: 
*Vassals give 20% happiness, but the tooltip does not show it,
*Vassal independance tooltip "75% or more cities" ... seems to have no effect and should be removed.

Sorry if you've fixed this already, this is from the 2/27 thread.

**Comment by LoneGazebo** [comment]
@Infixo mind looking at the TopPanel.lua files for me, see why this is missing?

**Comment by Infixo** [comment]
Ok, I'll look into it.

**Comment by Infixo** [comment]
@Edaka Can you pls post a screenshot and explanation what is wrong? I.e. what is the tooltip showing / not showing. I don't have any vassal games, so I can't verify the problem.

According to the code, the tooltip should display a line like this:
[code]
{1_Num} from Vassal Happiness.
[/code]

1. Does this line appear at all or not?
2. If does - does it show a correct value or a wrong value?

**Comment by Edaka** [comment]
@Infixo I'm really sorry, I know you can't do much this way, but I just copied other user's report from the forum. When I get to the game I'll try to make screenshots - I think I know what he meant.

**Comment by UndeadDevel** [comment]
the part of the tooltip that says "75% or more cities" actually does work only it's supposed to say "75% or less cities...". It's the condition that checks whether the master protected his vassal sufficiently; if the vassal loses enough cities during the master's wars, he can use that to force liberation.
So it's the description that needs to change...

**Comment by LoneGazebo** [comment]
This one? [TAB][ICON_BULLET]Vassal's team has {1_CityPercent}% or more of Cities when vassalage started. (currently {2_Percent})

**Comment by UndeadDevel** [comment]
Looks right...it turns green when the vassal loses too many cities not when he gains them so I assume the "more" should simply be replaced with "less".
