### ISSUE TITLE
incorrect village yield

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4114]
so i've built a village on a city connection, supposed to give +4g

![image](https://user-images.githubusercontent.com/1358966/38056226-39ea3472-32dc-11e8-97fa-c8fc2697c53b.png)

but observe:

![image](https://user-images.githubusercontent.com/1358966/38056283-60c1344c-32dc-11e8-91f2-c42297b7b7e5.png)

what's up?

**Comment by LoneGazebo** [comment]
Did a TR finish? The village gets a bump from the connection, and a bump from TRs that pass over it.

**Comment by Enrico-Swagolo** [comment]
Bump from TRs? Does that mean a single village can get buffed by more than one trade route? I don't remember that.

**Comment by LoneGazebo** [comment]
No, just one triggers it.

**Comment by ilteroi** [comment]
so, is it the tooltip that's wrong or the actual yields?

**Comment by ilteroi** [comment]
ps: this game is too hard right now. i'm losing on prince. hard.

**Comment by LoneGazebo** [comment]
The tooltip is wrong, but I don't know why at the moment. I'd need to look. And yeah, we've made a monster @ilteroi. Prince is very tough.

**Comment by Edaka** [comment]
I notice that the tooltip also lists +2 science and culture as if from that certain Rationalism policy, however these also don't appear on the tile. Also, the tooltip lists +2 production just from the village, but then the tile has 2 production total with 1 of it being base (plains). So it seems that the tooltip shows maximum _potential_ yields?

**Comment by LoneGazebo** [comment]
Fixed -issue was that the function was doing an 'optimal' check once it was built so the tt would show the policy changes even if the player had not unlocked said policy.

**Comment by deadstarre** [comment]
quick question G if you would since you just looked at it, where is the define that controls the bonus granted by caravans passing over? I had made a thread but no replies, guessing nobody knew but i dont think it was a vanilla feature right

**Comment by LoneGazebo** [comment]
I forget the table but look at the code changes for the trading post in the CBO. There should be a table in the ImprovementChanges.sql file for it.

**Comment by LoneGazebo** [comment]
That is how it works - it does double-duty.

G

**Comment by deadstarre** [comment]
ok, thanks
