### ISSUE TITLE
City revolt shenanigans

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#4115]
Happened on 3/17. A long time annexed city flipped from me to its original owner after I was below 20 happiness for a good amount of turns. It all makes sense, except for 2 caveats:
1) This notification states that a part of the culprit was not having the Content public opinion. However, that wasn't true. I had an ideology chosen and the public opinion was Content both the turn before and the turn after the flip. The only problem was constant over -20 unhappiness. 
![image](https://user-images.githubusercontent.com/12978597/38058781-b9e0d464-32ec-11e8-9e00-5428cf644612.png)
Either the notification is inaccurate or public opinion isn't factored correctly.
2) I got absolutely no warnings about the flip, none up until it happened. 

I'd love to share a savegame, but that would mean having to downgrade to 3/17, as well as installing a few of the mods I use. I can zip it all up if you want.

**Comment by LoneGazebo** [comment]
I just need to update that text. It's 20 unhappiness and/or discontent. Question: was Mongolia a dead civ that was revived?

**Comment by Edaka** [comment]
Ah, okay. Nope, wasn't dead, in fact that city revolted to me from him about a century beforehand.

**Comment by LoneGazebo** [comment]
You positive you didn't get a message beforehand? Maybe just missed it? Because there's a message that sends out when the revolt counter is seeded.

**Comment by Edaka** [comment]
Fairly positive, I'd say. That's what made me create the issue. I'll try asking others around on the forum some more.

Is it supposed to be sent out once or, like CS protection jeopardy, every turn before it happens?

**Comment by LoneGazebo** [comment]
It is sent out once. I could probably tell it to send out every turn tho.

**Comment by Edaka** [comment]
Then it's more likely that I missed it. Dunno, but flipping seems significant enough to warrant a warning every turn. More significant that CS protection, for sure.
