### ISSUE TITLE
Broken Replay Viewer

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#4116]
To my LUA-friendly modder heroes:

VP breaks the lua for the replay viewer: [30187.093] Runtime Error: Assets\UI\InGame\Popups\ReplayViewer.lua:246: attempt to compare number with nil

I don't know why, and I'm confused by this lua script. Any ideas My guess is that an added replay data type is causing the issue (I added tourism per turn for backend calculations).

**Comment by LoneGazebo** [comment]
@JFDaly @Infixo you guys got any ideas?

**Comment by Infixo** [comment]
I went through Lua and didn’t see anything suspicious. It seems that some bad data might be coming from the dll, but I can’t locate it just by browsing. Can we observe this error like with a save file or cia some hall of fame file?

**Comment by LoneGazebo** [comment]
If you just end a game and look at the replay viewer the error pops up.
