### ISSUE TITLE
Puppets don't get reduced Tourism

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#4117]
Similar issue to #4112. In this case, it is shown in the UI but the actual yield is not reduced correctly.

I looked in the codes, and the problem is that the unified yield project is only half complete for tourism; the tourism calculations for cities (in CvCultureClasses.cpp) does not actually take into account getBaseYieldRateModifier (from CvCity.cpp), which is also where the puppet penalty is calculated.

I've fixed the problem on my end as I needed to use some unified yield stuff for tourism. Will post a pull request (along with other stuff for the civ I'm working on) in the next few days if nothing goes wrong with the game.

Posting this here so we don't go about fixing the same thing.

**Comment by LoneGazebo** [comment]
Let me know how this works out!
