### ISSUE TITLE
Some General Thoughts...

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#4118]
Back and ready to do some VP work if need be so hit me up. I'll take on some issues here that seem fit. 

The tactical AI for land units seems better than I have ever witnessed, so much so that I find the AI make some interesting (and better moves) than I would have done(and thusly, I've learned something from there moves, striking for someone who has 12,000 hours of Civ play). Naval Assaults are good, except with one caveat, if I am meeting my opponent with an equal force of naval units (e.g. 10 on 10 mix of ranged and melee ships) the AI won't take me on. I can sit there and punish their ships, swap in healthy ships and beat them down. The AI will do this same type of tactic with land units, but backs down with naval ships. Have you witnessed the same?

**Comment by deadstarre** [comment]
yes, AI navy played scared and inept in my last game. denmark declared on me and had a huge force heading toward my city, i spent the next turn rush buying, then he decided not to come at all. on the other sea, AI was using caravels in a hopeless attempt to capture a city way too strong for them. I had only one navy ship there since i was unconcerned, and they allowed it plus the city to eventually kill all their units and they never came close to accomplishing anything. didnt even pillage my boats

**Comment by Iamblichos** [comment]
Yep. It seems that on Naval-on-Naval, they won't take me on less they got like max flanking bonus (like completely surrounded) and has a guaranteed kill shot -- or if a unit is isolated an exposed. They ought to be like land units taking some risks and swapping out. I'm seeing this timid-ness even when they got full anti-warmonger fervor!

**Comment by ilteroi** [comment]
well, i'll take that as a compliment. the first part.

regarding naval combat, i need to check ... on the high seas it's possible that they adopt a passive stance even when they're locally dominant.

@deadstarre : i need a savegame or tactical ai logs. otherwise no chance to analyse

**Comment by ilteroi** [comment]
interesting. what did these zanzibarian ships do? did they attack?

@deadstarre : i have to admit i forgot about that other issue. never seen it myself and usually i can't load other people's saves ... say hi to your mom though :)

**Comment by Iamblichos** [comment]
Started a new game. Early naval triremes. Enemy has 4, I have 5. They are playing aggressive like they should. I wonder if they only back down if the AI player is affected by war weariness?

**Comment by LoneGazebo** [comment]
@Iamblichos in the tacticalAI log, what's the stance for the area? I wonder if the tactical analysis map isn't updating the estimated power of the region correctly and it's running the withdraw tactical subroutine.

**Comment by UndeadDevel** [comment]
I've seen some odd behavior of ships as well: after a war ended and the ships of the AI sailed back to his cities, they assembled there in a sort of diamond formation, which was half outside of his borders, though, and remained like that for around 30 turns. The weird thing being that some of those ships were badly damaged but the AI never rotated them inside his borders to heal up so they just stood there, damaged and without movement.
Don't have any logs but I can see if I can get a save if you need one.

**Comment by Iamblichos** [comment]
@LoneGazebo let me reproduce it again. Won't take long and I'll get the log so we can discuss. Don't have the log anymore of the initial one I posted on.

**Comment by Iamblichos** [comment]
![20180402094856_1](https://user-images.githubusercontent.com/14372214/38200794-4e7360b2-365b-11e8-8298-70cad0547b76.jpg)

See those scrappy two Polish Caravels and one in reserve? How did they not get taken on?

How do I get the tactical AI log enabled? I see everything but that...

**Comment by Iamblichos** [comment]
Is it PlayerTacticalAILog.csv we need?

**Comment by Iamblichos** [comment]
[PlayerTacticalAILog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1868524/PlayerTacticalAILog.zip)

Looks like they are withdrawing from any possible tactical moves to Fes and holding in position.

**Comment by Iamblichos** [comment]
Only time I see these guys fight hard on naval is before they are ready for peace. Once they want peace or to capitulate, they give up.

**Comment by Iamblichos** [comment]
Can’t remember which commit @ilteroi did subsequent to this but I’m seeing much improvement.
