### ISSUE TITLE
William luxury trade value

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#4119]
_1. Mod version (i.e Date - 4/23):_
3/20

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
multiple happenings of William valuing others luxuries at 0 worth- just ignoring that they there in the trade deal, as if they were untradeable

he always knows his stuff has value, but often enough he seems to have zero interest in buying others luxuries. really strange because have not seen this for anyone except William specifically. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Maybe he already has those luxuries(and has already stolen those monopolies already so no need for them).

**Comment by bigcat88** [comment]
He has zero values sometimes even for resources he has no monopoly(but already has a copy).

**Comment by LoneGazebo** [comment]
@deadstarre: here's the reason: William doesn't want resources (for monopoly purposes) that would push him towards a tile monopoly IF he doesn't have any tiles he would gain monopoly yields from. That's most likely what is going on here.

**Comment by deadstarre** [comment]
@LoneGazebo  is this something you hardcoded that specific luxuries with tile-yields he wont be interested in, or does the code recognize any mods that affect monopolies as well?

example : current game, playing with a mod that adds % modifier to jade , william offers nothing for jade (he owns no jade tiles himself, but he should be interested in pursuing the monopoly I think? or is he offering nothing because he recognizes he has zero chance at acquiring the monopoly?

**Comment by LoneGazebo** [comment]
the latter
