### ISSUE TITLE
UI glitch: tile yields on the map do not match tile yields actually produced

### ISSUE THREAD

**Issue by recred** [LoneGazebo/Community-Patch-DLL#412]
7/1 Version, CP/CBP/CSD/C4DF/EUI+Compat, More Lux, Infoaddict, Really Advanced Setup, Tectonic map script, Huge map, 18 civs, 34 CSs, Epic speed, Immortal, standard global difficulty

I randomly get weird UI glitches where the tile yields displayed on the map do not match the tile yields actually being produced. Example: in this screen shot, the map displays 3 Food 1 Gold on a farm tile that is actually producing only 3 Food.

![Screenshot](http://images.akamai.steamusercontent.com/ugc/689398254033866097/82C51CC60272EC562CB5B69F1DECBB20B5E184A0/)

**Comment by XplosiveLun** [comment]
I encountered this glitch too. It definitely is a UI error. Farms are not supposed to produce gold. The problem happens on "some" cities only. It can even yield culture or science on pasture.

**Comment by LoneGazebo** [comment]
Both of you post your policies, beliefs, traits, and tenets held at the time. If there's a match, that might help me narrow this down.

**Comment by XplosiveLun** [comment]
I'm terribly sorry. I don't have the glitched save right now. But soon I should post one.

As far as I can recall, that happens on multiple games. Some commons are: No Ideology tenets was adopted. I play as China.

**Comment by recred** [comment]
Looks like you found a fix before I could reply? Sorry about that! Anyway, if it still helps, in the screenshotted save, I had filled Tradition, the right side of Liberty, and gotten a few into Aesthetics. I had Mastery, Cooperation, Clericalism, and Ceremonial Burial as beliefs. I've also run into the issue other times where the phantoms yields have varied among the possible yields.
