### ISSUE TITLE
England dont want to build Alhambra

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4120]
_1. Mod version (i.e Date - 4/23):_
20b March

_2. Mod list (if using Vox Populi only, leave blank):_
Naval Warfare

_3. Error description:_ 
England is the only civ that go Authority(after that they go Fealty). But we are almost all in Industrial Era and they don't build Alhambra. Just my suggestion why:
With fealty they fast build usual castles and they don't want to build 'useless' Alhambra.

 Here is some logs:
368, England, London, PRE: Building, Alhambra, 7055, 2
368, England, London, PRE: Process, Wealth, 1225, 1
368, England, London, PRE: Process, Research, 800, 1
368, England, London, PRE: Unit, Tercio, 765, 3
368, England, London, PRE: Process, Arts, 700, 1
368, England, London, PRE: Unit, Ship of the Line, 600, 3
368, England, London, PRE: Unit, Corvette, 600, 3
368, England, London, PRE: Unit, Musketman, 595, 3
368, England, London, PRE: Unit, Lancer, 357, 3
368, England, London, PRE: Unit, Cannon, 255, 3
368, England, London, PRE: Unit, Cuirassier, 170, 3
368, England, London, PRE: Process, Farming, 145, 1
368, England, London, PRE: Process, Defense, 100, 1
368, England, London, POST: Process, Research, 620, 1
368, England, London, POST: Unit, Cannon, 502, 3
368, England, London, POST: Process, Arts, 488, 1
368, England, London, POST: Process, Wealth, 476, 1
368, England, London, POST: Unit, Ship of the Line, 262, 3
368, England, London, SEED: 6683296779668348672, CHOSEN: Research, Do not rush, TURNS: 1

368, England, York, PRE: Building, Alhambra, 4520, 5
368, England, York, PRE: Unit, Tercio, 2457, 2
368, England, York, PRE: Unit, Musketman, 2101, 3
368, England, York, PRE: Process, Wealth, 1080, 1
368, England, York, PRE: Unit, Cannon, 1028, 3
368, England, York, PRE: Process, Research, 1024, 1
368, England, York, PRE: Unit, Lancer, 945, 3
368, England, York, PRE: Unit, Cuirassier, 381, 3
368, England, York, PRE: Process, Arts, 300, 1
368, England, York, PRE: Process, Defense, 100, 1
368, England, York, POST: Process, Arts, 834, 1
368, England, York, POST: Unit, Cannon, 828, 3
368, England, York, POST: Process, Research, 608, 1
368, England, York, POST: Process, Wealth, 488, 1
368, England, York, SEED: 18199448198372991801, CHOSEN: Arts, Do not rush, TURNS: 1

_4. Steps to reproduce (optional):_
I can post savegame & any other logs if needed.

**Comment by LoneGazebo** [comment]
Do you have CustomMods.csv log?

**Comment by bigcat88** [comment]
Yes, but I didn't find there any city production reference. It is much later logs(from Modern Era)(I can load earlier save and generate logs from there) - but England is still didn't build it :)
[CustomMods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1864819/CustomMods.zip)

**Comment by bigcat88** [comment]
I found one more reference to Alhambra in CitySpecializationLog.csv
[CitySpecializationLog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1864833/CitySpecializationLog.zip)

**Comment by LoneGazebo** [comment]
Well custommods.h should tell us which city the AI set as the wonder city for alhambra.
