### ISSUE TITLE
One worker becomes 20 workers after capture by AI

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4121]
_1. Mod version (i.e Date - 4/23):_
20b March

_2. Mod list (if using Vox Populi only, leave blank):_
Naval Warfare

_3. Error description:_ 
One worker -> Twenty workers!

_4. Steps to reproduce (optional):_
Press Next.

Save game:
[BUG WORKER.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1863567/BUG.WORKER.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1863565/Logs.zip)

Screenshots (optional):
Before pressing Next:
![20180330152850_1](https://user-images.githubusercontent.com/13381981/38137888-3e729af2-3430-11e8-9fa1-3ed610666177.jpg)

After AI turn(Morroco declares war):
![20180330152946_1](https://user-images.githubusercontent.com/13381981/38137875-21d75ec8-3430-11e8-9b52-67558e29eed4.jpg)

**Comment by Iamblichos** [comment]
I've seen this happen too. I'll take a look at capture definition.

**Comment by UndeadDevel** [comment]
Seen this after I captured an archeologist I think; it originally belonged to another civ and when I clicked 'return unit' the same popup appeared again...had to click around 20 times and realized that either I just captured 20 archeologists at once or they cloned themselves as a defence mechanism to evade my valiant troops.

**Comment by LoneGazebo** [comment]
I think I know why - or rather, I think I have a solution.

**Comment by HungryForFood** [comment]
I noticed the multiple worker bug happens if you have a military unit on top of another player's settler, then you declare war on that player. Not sure if it happens every time, but it seems to be the same situation as the screenshots.
