### ISSUE TITLE
CS Faith Quest description

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#4123]
3-30b

![faithquest](https://user-images.githubusercontent.com/24731508/38152658-0e4b3f44-3469-11e8-9def-8953b7c96c2d.png)

It needs updated description/conversion tooltip

**Comment by LoneGazebo** [comment]
Ah, I'm missing an else.

**Comment by RandomNub** [comment]
Is the quest working at all btw? I get the Influence reward, but no GPP.

Here I just founded a new town with a colonist when the quest triggered, but no GPP increase except the +3 from specialist.

![gpquest](https://user-images.githubusercontent.com/24731508/38163196-0dd7148e-34f0-11e8-8c83-5f286dcfe463.png)

I went back one turn to check if the bonus applied elsewhere, but no changes in the capital either.

![jakarta186](https://user-images.githubusercontent.com/24731508/38163203-2c070676-34f0-11e8-890e-c95374fc8d80.png)

**Comment by LoneGazebo** [comment]
Should be.

**Comment by RandomNub** [comment]
Do you mean the 0 GPP issue is fixed for upcoming version as well?

**Comment by LoneGazebo** [comment]
No, as in, it should be working.

**Comment by RandomNub** [comment]
Providing +GPP to the progress of all great people in all towns, or distributed among all possible great people beign trained? Either way, I never noticed any (meaningful, or any at all) GPP increase the few times I completed this quest but never got around reporting it. Today it was just obvious.

**Comment by RandomNub** [comment]
![bugsinthecode](https://user-images.githubusercontent.com/24731508/38165363-62eda74a-3512-11e8-8a7d-22a50df57b10.jpg)

can't wait for the next fix then!
