### ISSUE TITLE
Hurricane event choice blocked despite fulfilling prerequisite

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#4125]
_1. Mod version (i.e Date - 4/23):_
2/27

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The 'Hurricane approaches' event triggered for me on turn 489 (Epic speed) and the option to evacuate the city was greyed out despite me having more than the required 1000 Gold in my treasury.
In the tooltip it says "You lack the required Yields to make this choice" but it doesn't tell me what I need beyond the 1000 Gold, which I have.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Are you in the modern era?

**Comment by UndeadDevel** [comment]
At the time of the event I was, yes. I was 1 turn away from completing the last Industrial Era tech but I had already researched Combustion from the Modern Era set.

**Comment by LoneGazebo** [comment]
text was't scaling - cost is actually 1500 on epic.

**Comment by UndeadDevel** [comment]
okay that makes sense since I had just shy of 1400
