### ISSUE TITLE
Morocco AI & Improvements

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#4128]
![marrakech](https://user-images.githubusercontent.com/24731508/38164350-4038fb5a-3503-11e8-9139-c40d7cb8bcf5.png)

In feel Morocco is building too few kasbah in my current game.

- GPI like that manufactory in the first ring are a bad choice for him, plenty of better tiles around (assuming he planted it in the first 50 turns, from tradition capital, there should have been some open space in 2nd ring for sure); that town could have been mved further down the road as well.
- a farm providing 4f1p and not contributing to the creation of any triangle farm, instead of a kasbah, terrible choice imo.

Now sure, it's deity and the AI has plenty of production and gold, Ahmad is top culture as well. Still, building the UI might give him an edge on defense, wonder if you can teach him to plan in advance home improvements.

**Comment by bigcat88** [comment]
Screen from my game(all is fine in Morocco lands):
![20180331192350_1](https://user-images.githubusercontent.com/13381981/38165247-40e00344-3519-11e8-9c75-903c8caf5edd.jpg)
But in previous game I see in two morocco cities two improvements(towns) near city.

**Comment by LoneGazebo** [comment]
It's not super feasible to code, as the AI doesn't 'know' it has an improvement (in the implicit sense of the word, for the builder at the time) that it's going to have an adjacency UI later.

**Comment by Iamblichos** [comment]
Is it worth doing a revaluation every turn to re-work a plot when you get the tech for the adjacency bonus?

**Comment by LoneGazebo** [comment]
Problem is you don't want to nuke GP improvements. I'm going to tinker with adding a predefined bool to limit it for Morocco (technically any cityadjacent-only improvements) - we'll see.

**Comment by Iamblichos** [comment]
Sure but the check could always be inclusive to ignore GPI.
