### ISSUE TITLE
City connection road religion spread

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4130]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Roads increase faith spread much more than before, like 2-4 times more. Is it intentional? The patch notes only mentioned Trade Routes (TRs), not city connections so it appears not to be, especially since it's way too strong IMHO. As it is, your religion spreads like a wildfire if you have roads. I converted 5 of my own cities, and Darius' nearby/further cities have 30-40 religion conversion thingy, constantly growing.

**Comment by LoneGazebo** [comment]
I’ll look.

**Comment by deadstarre** [comment]
pressure from roads still seems high for 4/5
