### ISSUE TITLE
Japanese Eight Virtues

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4131]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Is it really working as intended, or is RNG a bit weird here? There's eight promos to choose from, but for all my units, so far I have 2x Sincerity, 3x Righteousness and 7x Courage. Not a single one who has any of the other five. It appears to be improbable, especially since almost all new units I make get Courage.  Are those more likely than the others? I've noticed similar stuff in my previous games as well.

**Comment by Enrico-Swagolo** [comment]
3 more Courages, haven't seen respect, benevolence, loyalty etc yet. Pretty nice as respect/loyalty are the worst, but it's suspicious, what are the likelihoods for each promo? Something's wrong for sure, it's slowly venturing outside the realms of mere improbability and RNG.

**Comment by LoneGazebo** [comment]
It truly is RNG.

**Comment by Enrico-Swagolo** [comment]
I no longer believe that. I have like 15 Courage (would be more if a few didn't die because of severe unhappiness and warmonger penalty), 7 Sincerity and 5 Righteousness now, though the UI on the left being weird means I could easily have made mistakes in calculations.  Not a single other one. Can you please check the code if something didn't go wrong? I can provide you with a save, even.
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1866671/QuickSave.zip)

**Comment by Iamblichos** [comment]
Did you build those pairs in different cities on the same turn? I know G's using that small fake rand on that stuff, probably to see if it's better for multiplayer...

**Comment by Enrico-Swagolo** [comment]
Now that I think about it, I've bought two Knights with faith lately (you can see them in the mid part of the empire, continent I own) so I could destroy unhappiness-spawned rebel spearmen and both got Sincerity. Almost every unit, bar one garrison Landsknecht, like two archers and guys gotten from Authority's final policy are from Kyoto the capital. I really want that Morale, so it's the origin of my military.

**Comment by ilteroi** [comment]
i think there's a problem with the usage of getSmallFakeRandNum(). in various places.

it's called like this:

getSmallFakeRandNum(iNumChoices, iNumChoices);

but the second parameter should introduce some randomness (unit id, plot index, etc). here we get the same result every time the function is called in the same turn.

who wants to fix this?

**Comment by LoneGazebo** [comment]
I've already fixed it. I just introduced to the unit ID number into the function parameter.

**Comment by ilteroi** [comment]
but what about the other ~30 places?

**Comment by LoneGazebo** [comment]
Most of them don't matter because the mud around and introduced is pretty minuscule. But will keep an eye out for any sort of outliers.

**Comment by ilteroi** [comment]
mud?

anyway, i meant to type 300 .... i'm afraid some bugs will be hiding there.

for example: 

GC.getGame().getSmallFakeRandNum(1,8) <= iFlavor in AI_chooseProduction() seems fishy? it will always return true unless the flavor is zero.

and so on and so on ...

**Comment by Iamblichos** [comment]
Yeah he meant the firaxis RNG is mud. 👎

**Comment by Enrico-Swagolo** [comment]
Is the fix in 5/4 version? I don't think it is. I got a Dojo, declared war on the same turn, attacked with 4 units and all got Courage.

**Comment by Enrico-Swagolo** [comment]
In fact even as I attack on later turns with the remaining guys from Dojo'd Kyoto, everyone keeps getting Courage. I think the fix made it worse than it was in the current state.

**Comment by ilteroi** [comment]
hmm, the choice depends on the current turn, the number of units in the game, and your current economic power.

so if you attack with a bunch of units in the same turn, that will actually give the same result. i'll fix.

**Comment by Enrico-Swagolo** [comment]
There's another problem. Yet again, I'm only getting Sincerity/Righteousness/Courage. Units made later than before Dojo is up get either Sincerity, Righteousness or Courage. I still don't have another promo. Even a few units outside Kyoto got only one of these, though with them there's likelihood of it being RNG (only like 3 of them)

**Comment by LoneGazebo** [comment]
@ilteroi why don't we use the unit's ID as the extravalue for the RNG? That'll always be unique.

**Comment by ilteroi** [comment]
possible, right now i'm using the plot index as extra seed

**Comment by ilteroi** [comment]
see #4168
