### ISSUE TITLE
Road building - various issues

### ISSUE THREAD

**Issue by rudpes** [LoneGazebo/Community-Patch-DLL#4134]
_1. Mod version (i.e Date - 4/23):_
3/31

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Various issues
- pervasive icon advice to remove roads when connecting cities of own empire, seams advice is followed almost religiously by automated AI
- connect a road to a city state (city state road connection quest is on): city state worker will religiously remove the road you just constructed
- road to city state: after road quest is completed, automated workers remove the road from clostest city to empire border
- Religious pressure on connected cities increased, especially visible with"Ritual" enhanced belief

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Turn on ‘workers will not remove improvements’ in options. The AI does what the AI thinks it should do, not what you think it should do.

**Comment by deadstarre** [comment]
I was wondering if that option affected the AI's game or just my workers. 

It seemed weird to me if it affected them though because I can turn on the option, and yet still remove or replace improvements whenever I want to, but then the AI can't... and sometimes its the right thing to do.

**Comment by LoneGazebo** [comment]
It affects his workers, but not any other AI.

G

**Comment by rudpes** [comment]
Apologies for the report on my own territory, I did a fresh install and I thought I had the option (always turn it on).
will try to setup a road and see if the city state worker removes the road on his own end

**Comment by Padre19** [comment]
Confirm. City state worker removes the road. ( options workers will not remove improvements is on).

**Comment by deadstarre** [comment]
road removal in general is a really niche scenario, there is almost never a reason to do it which didn't involve a simple human mistake, the kind of mistake AI isn't capable of.  even when losing a city somewhere, having road that continues to run there in your territory is a great idea. im scratching my head to think of why the AI should ever like to remove roads at all

**Comment by lucperrin** [comment]
Also confirming city states removing the roads during build a road quest.

**Comment by ryanmusante** [comment]
Road building loop with latest patch. Auto-workers build roads connecting between the two cities and than remove and rebuild in endless loop. The only way to correct is to select, force build road, wait until connection is made to the capital and than set them back to work again.

![roads](https://user-images.githubusercontent.com/26808646/38460611-2f91ba1c-3af8-11e8-8acc-c8e5404886de.png)

**Comment by LoneGazebo** [comment]
will look.

**Comment by ryanmusante** [comment]
It still has the AI auto-worker removing a road if the connection isn't complete. In this one, the last two road strips were finished and as soon as they completed, they switched to remove. Meanwhile, the first one was still working on completing. As soon as the first completes, it will begin to remove and than the cycle will repeat in a loop.

Construction

![constuct](https://user-images.githubusercontent.com/26808646/39046739-2538d99a-44d2-11e8-9b9d-8090065a998b.png)

Removal

![remove](https://user-images.githubusercontent.com/26808646/39046748-30848fd8-44d2-11e8-953a-258d225d1cdc.png)
