### ISSUE TITLE
Trade with William seems broken

### ISSUE THREAD

**Issue by SeyrenW** [LoneGazebo/Community-Patch-DLL#4135]
![20180403023910_1](https://user-images.githubusercontent.com/37452208/38209900-53a4c804-36e8-11e8-9976-8d69d2053f6b.jpg)
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In the screenshot, you can trade multiple copies of gold to him even though he has already acquired the luxury. He also values iron and horses at zero. This is still in the ancient era.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Not a bug. That's his UA (the multi trade stuff).

G
