### ISSUE TITLE
Archaeological Record Issue

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#4136]
Got a little issue with this code:

```
if (newImprovementEntry.IsPermanent() || newImprovementEntry.IsCreatedByGreatPerson())
{
	ClearArchaeologicalRecord();
}
```

I had a Manufactory that I set in the medieval era on a hill. A dig site formed under it when I got the appropriate tech later in the game, however when I worked it with an Archaeologist, I got a Lua error: Runtime Error: Assets\DLC\Expansion2\UI\InGame\Popups\ChooseArchaeologyPopup.lua:115: attempt to index field '?' (a nil value)

Which that code reads: szDateString = Locale.ConvertTextKey(GameInfo.Eras[pPlot:GetArchaeologyArtifactEra()].Description);

The record is getting cleared because there's no artifact associated with the dig site, but there's still a dig site....strange....

**Comment by Iamblichos** [comment]
We might want to add to that code above...

```
ResourceTypes eArtifactResourceType = static_cast<ResourceTypes>(GC.getARTIFACT_RESOURCE());
ResourceTypes eHiddenArtifactResourceType = static_cast<ResourceTypes>(GC.getHIDDEN_ARTIFACT_RESOURCE());
if (getResourceType() == eArtifactResourceType ||  getResourceType() == eHiddenArtifactResourceType)
{
	setResourceType(NO_RESOURCE, 0);
	ClearArchaeologicalRecord();
}
```
just in case someone has already tech'ed to it.

**Comment by LoneGazebo** [comment]
makes sense.

**Comment by LoneGazebo** [comment]
that really should be a part of the cleardarchrecord function actually

**Comment by Iamblichos** [comment]
It is when you have cities plotted onto potential digsites....I'll make pull request.

Full code:

```
#if defined(MOD_BALANCE_CORE)
			ResourceTypes eArtifactResourceType = static_cast<ResourceTypes>(GC.getARTIFACT_RESOURCE());
			ResourceTypes eHiddenArtifactResourceType = static_cast<ResourceTypes>(GC.getHIDDEN_ARTIFACT_RESOURCE());
			if (newImprovementEntry.IsPermanent() || newImprovementEntry.IsCreatedByGreatPerson())
			{
				if (getResourceType() == eArtifactResourceType || getResourceType() == eHiddenArtifactResourceType)
				{
					setResourceType(NO_RESOURCE, 0);
					ClearArchaeologicalRecord();
				}
				ClearArchaeologicalRecord();
			}
#endif
```
I'll keep that second Clear just in case nobody has tech'ed to Archaeology yet, just to make sure it gets cleared.

Or we can add that setResourceType(NO_RESOURCE, 0); to the clear function. Up to you. We can clear out it's redundancy where's it's used elsewhere.

**Comment by LoneGazebo** [comment]
i'm all for killing redundancy.

**Comment by Iamblichos** [comment]
Sounds good. I'll get it done.

**Comment by Iamblichos** [comment]
#4154
