### ISSUE TITLE
Sanction resolution prevents peace deals 

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#4137]
_Mod version:_
3/31 No-EUI

_Mod list:_
IGE, Quick turns

_Error description:_ 
While the sanction policy is in place, the affected civ cannot make peace deals (along with non-goods deals such as accept embassy or open borders, but that's probably intended).

Edit: Warscore might be a factor, as a peace deal with Napoleon on the same turn shows the values, but is still un-tradable

_Steps to reproduce:_
Allow yourself to be sanctioned and attempt to make peace, or attempt to make peace with a sanctioned civ (haven't tested the later).

---------------------------
Supporting information:
Harald, warscore 11
![](https://i.imgur.com/kvV40Dw.png)
Napoleon, warscore 30
![](https://i.imgur.com/xvk1NWO.png)

**Comment by LoneGazebo** [comment]
@HalfEmptyMug I tested and didn't see this, but i'll test again. hold the savegame, as if there's a fix it'll be savegame compat.

**Comment by Jotaro31400** [comment]
I've got the same issue ^^ 
I will wait the fix then

**Comment by bigcat88** [comment]
waiting for fix(save game compat) too.
