### ISSUE TITLE
Game speed scaling for reseach and golden age at epic

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#4139]
I noticed that ResearchPercent and GoldenAgePercent are 200 for epic, rather than 150 like everything else (eg TrainPercent). I remember the game speed scaling stuff was changed quite recently though, so is this intended?

**Comment by LessRekkless** [comment]
It's odd because Epic Gold Ages actually in-game seem to be the proper 150% of Standard, while Research costs are clearly 200%.

**Comment by HungryForFood** [comment]
Are you sure? Because I remember Golden Ages being 20 turns on epic, as opposed to 10 on standard.

**Comment by LessRekkless** [comment]
Oh, Golden Age length. GA Points required for the next Golden Age is at 150%, I didn't think to check Length.

**Comment by TechpriestEnginseer** [comment]
It's fine because that's how it was meant to be.

**Comment by LessRekkless** [comment]
Absolutely everything in Marathon is at 300 except for Improvement construction times.
