### ISSUE TITLE
God of Commerce (Belief)

### ISSUE THREAD

**Issue by raphaell666** [LoneGazebo/Community-Patch-DLL#4141]
_1. Mod version (i.e Date - 4/23):_
03/31

_2. Mod list (if using Vox Populi only, leave blank):_
Only VP+EUI with UI mods and EE era from Infixo

_3. Error description:_ 
God of Commerce belief does not add +2 Gold and +2 Faith to Capital, as the description says.

_4. Steps to reproduce (optional):_
Start as India, choose belief, verify no bonus in the capital was gained. Other bonuses from cities with connections seem to work fine.

---------------------------
4. Screenshots (optional):
![god_of_commerce_bug](https://user-images.githubusercontent.com/25795774/38340134-35d190a8-3848-11e8-9211-dba93f6339ec.png)

**Comment by bigcat88** [comment]
You need to found a second city to start get +2f/2g from this pantheon.

**Comment by LoneGazebo** [comment]
Yup.

**Comment by raphaell666** [comment]
So, if I understood it correctly, the description is wrong? 

Or is it misleading, as in you need a city connection in order to receive the bonus both in the capital and in the city?

I am going to test it again to understand it better.

**Comment by bigcat88** [comment]
No, description is ok(maybe it need a rework a bit, from first time it is hard to understand how it works) - but pantheon works as it should be(in January I picked it).

**Comment by raphaell666** [comment]
Understood it now, as soon as I founded my second city, the Capital got the bonus. I assume it is not possible/balanced to have the belief giving gold and faith in the Capital as soon as you get it?

It does nothing at the beginning of the game for Venice, as they can't found cities.

Thank you for the explanation by the way.

**Comment by MoiMagnus** [comment]
I agree with raphaell

The description says "+2fg in Capital, and in cities with a city connection".
The natural way of understanding it is:
+2fg in Captital, without any restriction
+2fg in cities with a city connection
=> And I think the pantheon should have this effect, if possible.

The less natural way of understanding it is:
+2fg in Captital once connected to another city
+2fg in non-capital cities once connected to the captital
=> If we want that effect, I think "+2fg in cities with a city connection, including the capital if connected" would be probably easier to understand.

**Comment by raphaell666** [comment]
The exact way it currently works is:
+2fg in Capital provided at least one other city is founded/conquered (not necessary to be connected)
+2fg in cities once connected to the Capital

I do not believe (may be wrong) that this is working as expected. I am trying to look at the code to understand why it works like this currently, and why it does not activate as soon as you get it.

This is mostly an issue for e.g. Venice, as they will take longer to found/conquer a second city and activate this belief (again, connection doesn't seem to be necessary to get the bonus in the Capital, you only need to control more cities than only the Capital for some reason).

**Comment by raphaell666** [comment]
I'm using my impressive beginner modding skills, and it seems that this belief is called "BELIEF_MESSENGER_GODS" by the game files, and I noticed the description seems to have changed in the 04/05 version? It now says:

`+1 Faith for every +20 Gold per Turn you produce. +2 Faith and Gold in Cities with a City Connection, and in your Capital (after first Connection)`

So, I assume this issue has been looked into?

I cannot find where the beliefs are in the original game files, but it seems that VP only changed the yields from Science to Gold with:

`UPDATE Belief_YieldChangeTradeRoute SET YieldType = 'YIELD_GOLD' WHERE BeliefType = 'BELIEF_MESSENGER_GODS' AND YieldType = 'YIELD_SCIENCE';`

So it seems that this deal with requiring a second city was not an addition of VP?

Only thing left is that the bonus at the capital does not actually require a city connection, it only requires a second city to be founded or conquered, see the screenshot without city connection, but bonus active on the capital:
![god_of_commerce](https://user-images.githubusercontent.com/25795774/38437235-3590b0cc-39ad-11e8-8880-fbfab148b638.png)

Either way this is more nitpicking, it is considerably less misleading now, thanks!

**Comment by raphaell666** [comment]
My suggestion to be as clear as possible, based on how it currently works in-game, would be to change the description to:
```
UPDATE Language_en_US
SET Text = '+1 [ICON_PEACE] Faith for every +20 [ICON_GOLD] Gold per Turn you produce. +2 [ICON_PEACE] Faith and [ICON_GOLD] Gold in Cities with a [ICON_CONNECTED] City Connection, and in your [ICON_CAPITAL] Capital after gaining a second City'
WHERE Tag = 'TXT_KEY_BELIEF_MESSENGER_GODS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );
```

**Comment by LoneGazebo** [comment]
that seems fine to me.
