### ISSUE TITLE
good news

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4146]
venice doing quite well

![image](https://user-images.githubusercontent.com/1358966/38407569-47692bae-397a-11e8-876a-54427b2976bb.png)

but then this happens

![image](https://user-images.githubusercontent.com/1358966/38407585-58c8a88e-397a-11e8-9f9c-c16aa0294864.png)

easy come, easy go

**Comment by Iamblichos** [comment]
Poor Venice....strive so hard to be a normal civ...
