### ISSUE TITLE
AIPriority for Sydney Opera House theming bonuses

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#4147]
The AIPriority (under Building_ThemingBonuses) for the the wonder is currently too low, because it does not get changed by CBO. Sydney Opera House currently has a priority of 1, lower than Broadcast Tower's 2, even though its a wonder and it gives slightly more theming bonus. Should probably be 3. There is also Broadway, which is also 2 at the moment. Should slots on wonders always be prioritised?

AIPriority is used by the optimize button in culture overview, and I think the AI, so a change is warranted.

**Comment by LoneGazebo** [comment]
If you could help me compile a list and suggested values that would be helpful.

**Comment by HungryForFood** [comment]
It's really those two that I think need changes, so in summary:

| Building | AIPriority |
| --- | --- |
| Sydney Opera House | 4 |
| Broadway | 3 |

Above is for if you feel that AI should always prioritise wonder slots. Technically the theming bonus per great work in Broadway is less than Broadcast Towers, so going by the bonus only it would be something like 3 and 2.
