### ISSUE TITLE
Modded gov issue with Renewal-type pantheon bonus

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#4150]
_1. Mod version (i.e Date - 4/23):_
4/5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Modded in a pantheon which gives 1 faith per 2 forest worked, but gov is blind to it when choosing tiles. I think he is now correctly trained to identify food / culture / gold differences via caravansary herbalist etc., but if possible would be cool if he could see the difference for only faith as well

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Iamblichos** [comment]
Or it is weighted properly, and it just not enough to offset other needs. The yield for each modded forest might not be enough....what population was your city in your test case?

**Comment by deadstarre** [comment]
an early game 4 pop city with multiple jungle, forest and wheat, all identical base yields. He chose 1 wheat, 1 forest, 1 jungle and my gold luxury. when i take him off the wheat and lock him onto a 2nd forest, the only difference was me gaining 1 faith

**Comment by deadstarre** [comment]
up to 5 pop, no other changes. also gives 1 culture per 3 forests and so heres what im looking at now - hes working 2 forests, 2 jungles, and the wheat. if i take him off the wheat and lock him onto a third forest the only difference is me gaining 1 culture. 

*flips table*.... starting to question if the yieldperterrainx100 are worth the headache

**Comment by LoneGazebo** [comment]
Well, actually, I did find a small overoptimization - if a tile had no natural yield for a yield the yield bonus from per100x stuff wouldn't apply. :)
