### ISSUE TITLE
venice endless loop

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4151]
here's the save

[AutoSave_0432 AD-2012.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1885399/AutoSave_0432.AD-2012.zip)

**Comment by ilteroi** [comment]
don't bother, that's just for gazebo to validate his fix

**Comment by Iamblichos** [comment]
was it that diplomacy loop bug?

**Comment by LoneGazebo** [comment]
no, it's a loop for army AI shenanigans
