### ISSUE TITLE
PATHFINDER GETTING DOUBLE PROMOTION

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4153]
_1. Mod version (i.e Date - 4/23):_

latest hotfix

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

This bug used to occur months ago when I was binge playing VP. I made a break and decided to launch the latest version today. So again the same bug with a pathfinder. Whenever he accumulates enough exp by exploration to get promotion, the promotion fires two times. No, he didn't accumulate loads of exp in a single turn to be eligible for double promotion, he was just walking through the jungle in the first turns of a fresh game.
It doesn't happen all the time, it happens randomly. Not very often, but not too rare either.

P.S. I just realized it happens to scouts, too.

**Comment by LoneGazebo** [comment]
without a save on 4/5 I can't help you.

**Comment by Iamblichos** [comment]
I've seen it too. I'll take a look.

**Comment by Iamblichos** [comment]
Code looks fine. You sure you aren't accounting for the GoodyHutYieldBonus?

**Comment by saamohod** [comment]
Pretty sure. When this happened my pathfinder had nothing to do with goody huts in previous turn(s). I'll try to catch this bug once again and post a savegame.
