### ISSUE TITLE
Archaeological sites failing to give artifact or landmark

### ISSUE THREAD

**Issue by Guynemer** [LoneGazebo/Community-Patch-DLL#4154]
_1. Mod version (i.e Date - 4/23):_ 4/5 Beta

_2. Mod list (if using Vox Populi only, leave blank):_ complete VP, Quick Turns, Info Addict, Tectonic Map Script

_3. Error description:_  When completing certain archy digs, the screen to choose an artifact or landmark is malfunctioning, not offering the choice, stopping the game from advancing any further.

[single.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1886804/single.zip)

4. Screenshots (optional):

![untitled](https://user-images.githubusercontent.com/17055842/38461266-7d1fa9c4-3a99-11e8-802d-c468e7dcc7c8.png)

**Comment by bigcat88** [comment]
@LoneGazebo I write about the same, but I see this with hotfix version(hotfix was installed in ancient era)
Look like many people see that. 
Now I am installed 4-5 version and after sleep will start a new game. Will I see this bug on new version and better to wait a new hotfix for version 4-5 too, or 4-5 version is not affected by this?

@Guynemer is this happened with hotfix or with 4-5 version ? On forum you wrote:
"Just came in to report the same; only having used the hotfixed version, got an "empty" archy site. Reloaded, and I got the "FLIBBY 4" thing."
So you used hotfix or new beta?

**Comment by Guynemer** [comment]
I believe 4-5 beta.  I'll have to check the download on my gaming rig later to be sure

**Comment by Guynemer** [comment]
Confirmed, it is the 4-5 beta

**Comment by myles1718** [comment]
I can confirm this as well

**Comment by Iamblichos** [comment]
Huh.

**Comment by LoneGazebo** [comment]
I'm going to work on this today.

**Comment by Iamblichos** [comment]
@Lonegazebo, this was the error I saw. I’m not sure why they are still seeing this now.

**Comment by Iamblichos** [comment]
I dunno. I have 1000’s of hours and haven’t seen this until now. We have something measured up somewhere.

**Comment by myles1718** [comment]
I put the Update in as stated above and for some strange reason it now loads Gods and Kings

**Comment by ryanmusante** [comment]
I wouldn't put that update in, I'd wait for it to be merged by Gazebo.

**Comment by myles1718** [comment]
ok Thanks  Think I just reinstall VP from scratch then

**Comment by bigcat88** [comment]
Any ideas what to do with this problem? After hotfix version didn't help, I started a new game with 4-5 version, but here the same as I understand(currently I am only in Classical Era). Automatic archeologists can help me when I will reach Industrial era in my game? Does AI affected by this or not? I can just try to skip digging for myself...

**Comment by Iamblichos** [comment]
I'm trying to reproduce it at the moment to see what is going on. I'm not sure where G is at on it. I know this is a show stopper.

**Comment by Iamblichos** [comment]
What was the issue?

**Comment by LoneGazebo** [comment]
randomly-populated dig sites weren't having their player2 value set properly, thus causing the LUA error and a CTD if player2 was selected. A bad while loop on my end (mea culpa) caused the game to ignore setting player2.

**Comment by bigcat88** [comment]
will it be a hotfix or a new version?

**Comment by LoneGazebo** [comment]
hotfix.

**Comment by LoneGazebo** [comment]
i'm adding an implicit check when GWs are created (and sought) that replaces NO_PLAYER with barb player. So you'll get barb artifacts if things are going crazy (which is fine - barbs can have art too!)
