### ISSUE TITLE
Paging Dr. Ilteroi - Pathing Inefficiency 

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#4156]
_1. Mod version (i.e Date - 4/23):_

4/5
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

he wants to reach city in 3 turns via land, i'm there in 2 if embark.

_4. Steps to reproduce (optional):_
![civ5screen0019](https://user-images.githubusercontent.com/15820785/38466328-a6b6b4f6-3af5-11e8-8b89-ad20efecaba3.jpg)
![civ5screen0020](https://user-images.githubusercontent.com/15820785/38466329-a8615b3a-3af5-11e8-8993-3d2c19bf09bd.jpg)
![civ5screen0021](https://user-images.githubusercontent.com/15820785/38466378-3eb93530-3af6-11e8-9882-38614213ea73.jpg)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
It may be intended.
One year ago, people were complaining that their units in auto-move were embarking and being killed by ennemy units too easily.

**Comment by ilteroi** [comment]
yeah, that's by design. ending a turn in embarked state is bad. 

also the difference is small. in turn 3 you'll have 2 moves in the city whereas the AI will have 1 move.

**Comment by deadstarre** [comment]
well then =)
