### ISSUE TITLE
crashes to desktop during late game 3/17 version

### ISSUE THREAD

**Issue by tripleducky** [LoneGazebo/Community-Patch-DLL#4158]
_1. Mod version (i.e Date - 4/23):_ 

3/17

_2. Mod list (if using Vox Populi only, leave blank):_

camera rotation and WASD controls (BNW) v. 2
hellblazers Pangea map v. 18

_3. Error description:_ 

game freezes sometimes while loading a fresh game. Also, during late game, and only during late game, the game is crashing a lot. (quits to desktop without warning) I'm not sure precisely when it started but safe to say the second half of game. Only crashes after hitting next turn and during the time before your next turn begins. I have played other versions of the mod, and they all crashed sometimes during late game, but this edition seems bad.

_4. Steps to reproduce (optional):_

play game past turn 250, I guess.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1887646/Database.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1887647/xml.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/1887648/Lua.log)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[savedgameb4crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1887655/savedgameb4crash.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

in the previous zip file.

4. Screenshots (optional):

**Comment by tripleducky** [comment]
It actually got to the point where it crashed every single time tried to do anything in the game, even during my turn. Game is scrapped. :'(

**Comment by tripleducky** [comment]
[savedgameb4crash2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1888348/savedgameb4crash2.zip)

Here is a saved game before it crashes literally every time I try to do anything.

**Comment by tripleducky** [comment]
okay I think the game freezing when loading a fresh game was the NQ map. Not sure about the rest though.

**Comment by LoneGazebo** [comment]
Late game crashes are generally due to memory issues.

**Comment by tripleducky** [comment]
What does that mean? Something is wrong on my end? Can I fix it?

**Comment by LoneGazebo** [comment]
unfortunately not much you can do  - civ's a 32-bit app so 4gb is it's maximum allocation. Huge maps and lots of civs/minors can overcome that cap and cause out-of-memory errors.

**Comment by Iamblichos** [comment]
Also if you're using heavy UI mods like Promotion flags, terrain textures mods, or even EUI contributes to this. If you use EUI, I wouldn't use any other [heavy] UI mod.
