### ISSUE TITLE
Mountains incorrectly displayed as other base terrain, vice versa.

### ISSUE THREAD

**Issue by cammcken** [LoneGazebo/Community-Patch-DLL#4159]
_1. Mod version (i.e Date - 4/23):_
4/5/2018 — the hotfix for the previous version, not the new beta version

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Some tiles which are hills and marshes are rendered as mountains on the normal display. A tile which is mountains rendered as hills. Switching to strategic view shows the true terrain.
[Bug Report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1888008/Bug.Report.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20180408170949_1](https://user-images.githubusercontent.com/26178723/38473406-9a6010ea-3b5d-11e8-8e5f-371e27d1c90c.jpg)
![20180408171016_1](https://user-images.githubusercontent.com/26178723/38473407-9a81802c-3b5d-11e8-8703-6ca7d656dced.jpg)
![20180408183916_1](https://user-images.githubusercontent.com/26178723/38473408-9a9869a4-3b5d-11e8-9a7d-6e01fda189ac.jpg)
![20180408183919_1](https://user-images.githubusercontent.com/26178723/38473409-9ab31df8-3b5d-11e8-8176-fe5eaa2380d5.jpg)

**Comment by deadstarre** [comment]
i saw grassland that looked like desert hills earlier

**Comment by LoneGazebo** [comment]
vanilla visual DLL bugs, can't do anything about it.
