### ISSUE TITLE
goddess of nature

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4160]
![image](https://user-images.githubusercontent.com/1358966/38517819-7a6f5d8e-3c3b-11e8-94df-b791d9ca5e2b.png)

by my count there are 8 mountains within 3 tiles, so i expect +4 food/gold/faith. why do i only get +1 of each?

**Comment by LoneGazebo** [comment]
Yeah, capped at pop.

**Comment by ilteroi** [comment]
oops, always read until the end :)
