### ISSUE TITLE
Code cleaning: current influence on player

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#4162]
_1. Mod version (i.e Date - 4/23):_
18-04-05

So, this is the current code:
// Current influence trend on this player

    InfluenceLevelTrend CvPlayerCulture::GetInfluenceTrend(PlayerTypes ePlayer) const
    {
        InfluenceLevelTrend eRtnValue = INFLUENCE_TREND_STATIC;

        CvPlayer &kOtherPlayer = GET_PLAYER(ePlayer);

        // PctTurn1 = InfluenceT1 / LifetimeCultureT1
        // PctTurn2 = InfluenceT2 / LifetimeCultureT2
    
        // So if looking at is PctT2 > PctT1, can see if  (InfluenceT2 * LifetimeCultureT1) > (InfluenceT1 * LifetimeCultureT2)
        int iLHS = GetInfluenceOn(ePlayer) * kOtherPlayer.GetCulture()->GetLastTurnLifetimeCulture();
        int iRHS = GetLastTurnInfluenceOn(ePlayer) * kOtherPlayer.GetJONSCultureEverGenerated();

        if (kOtherPlayer.GetCulture()->GetLastTurnLifetimeCulture() > 0 && kOtherPlayer.GetJONSCultureEverGenerated() > 0)
        {
            if (iLHS > iRHS && m_pPlayer->GetCulture()->GetOtherPlayerCulturePerTurnIncludingInstant(ePlayer) < m_pPlayer->GetCulture()->GetTourismPerTurnIncludingInstant(ePlayer))
             {
                eRtnValue = INFLUENCE_TREND_RISING;
             }
            else if (iLHS < iRHS)
            {
                eRtnValue = INFLUENCE_TREND_FALLING;
            }
        }
        
        return eRtnValue;
    }

**********************************************

// Now, my proposal (may require some LUA savvy to fix my grammar errors).

     // Current influence trend on this player
     InfluenceLevelTrend CvPlayerCulture::GetInfluenceTrend(PlayerTypes ePlayer) const
     {
        // Influence Trend is Static by default. This initializes the variable too, so I rather don't touch.
        InfluenceLevelTrend eRtnValue = INFLUENCE_TREND_STATIC;

        CvPlayer &kOtherPlayer = GET_PLAYER(ePlayer);

        // PctTurn1 = InfluenceT1 / LifetimeCultureT1
        // PctTurn2 = InfluenceT2 / LifetimeCultureT2
        // So if looking at is PctT2 > PctT1, can see if  (InfluenceT2 * LifetimeCultureT1) > (InfluenceT1 * LifetimeCultureT2)
        // Assuming InstantInfluence and InstantCulture are the accumulated values on the last ten turns
        // including instant values, and none of the variables in this piece are NAN.
        // InstantInfluence > InstantCulture for Trend to be raising
        // So, mixing both worlds, we'll compare InfluenceT2 * LifetimeCultureT1 * InstantInfluence to
        // InfluenceT1 * LifetimeCultureT2 * InstantCulture

        kInfluenceTrend = GetInfluenceOn(ePlayer) * kOtherPlayer.GetCulture()->GetLastTurnLifetimeCulture() * m_pPlayer->GetCulture()->GetTourismPerTurnIncludingInstant(ePlayer) - GetLastTurnInfluenceOn(ePlayer) * kOtherPlayer.GetJONSCultureEverGenerated() * m_pPlayer->GetCulture()->GetOtherPlayerCulturePerTurnIncludingInstant(ePlayer);

        if (kInfluenceTrend > 0)
        {
            eRtnValue = INFLUENCE_TREND_RISING;
        }
        if (kInfluenceTrend <0)
        {
            eRtnValue = INFLUENCE_TREND_FALLING;
        } 
        // So, when kInfluenceTrend == 0, it takes default value (Static)

        return eRtnValue;
    }

// Compared to the old code, there's only one call to the functions to build our only variable here.
// if kInfluenceTrend is deleted after exiting the code, as it should, then no values are stored in
// database. There are no unnecesary sanitary checks, and only two easy comparisons are made.

// Note, this does not solve automatically the problem of big instant values older than 10 turns,
// but should be better.

**Comment by LoneGazebo** [comment]
That's essentially what I wrote last night:

```
/// Current influence trend on this player
InfluenceLevelTrend CvPlayerCulture::GetInfluenceTrend(PlayerTypes ePlayer) const
{
	InfluenceLevelTrend eRtnValue = INFLUENCE_TREND_STATIC;

	CvPlayer &kOtherPlayer = GET_PLAYER(ePlayer);

	// PctTurn1 = InfluenceT1 / LifetimeCultureT1
	// PctTurn2 = InfluenceT2 / LifetimeCultureT2
	
	// So if looking at is PctT2 > PctT1, can see if  (InfluenceT2 * LifetimeCultureT1) > (InfluenceT1 * LifetimeCultureT2)

	int iLHS = (GetInfluenceOn(ePlayer) + m_pPlayer->GetCulture()->GetTourismPerTurnIncludingInstant(ePlayer)) * kOtherPlayer.GetCulture()->GetLastTurnLifetimeCulture();
	int iRHS = GetLastTurnInfluenceOn(ePlayer) * (kOtherPlayer.GetJONSCultureEverGenerated() + m_pPlayer->GetCulture()->GetOtherPlayerCulturePerTurnIncludingInstant(ePlayer));

	if (kOtherPlayer.GetCulture()->GetLastTurnLifetimeCulture() > 0 && kOtherPlayer.GetJONSCultureEverGenerated() > 0)
	{
		if (iLHS > iRHS)
		{
			eRtnValue = INFLUENCE_TREND_RISING;
		}
		else if (iLHS < iRHS)
		{
			eRtnValue = INFLUENCE_TREND_FALLING;
		}
	}
		
	return eRtnValue;
}

```

We'll see if it helps.

**Comment by tu-79** [comment]
Almost the same, yes (I admit I didn't see this code). Though for iLHS and iRHS values I'd use multiply signs instead of additions. Mathematically makes more sense (you should not add variables of different dimensions).
Here you have two conditions to say the trend is rising:
PctTurn2 > PctTurn1 && InstantPctTurn(last 10 turns) > 0

Both can be expressed as
(InfluenceT2 * LifeTimeCultureT1) > (InfluenceT1* LifetimeCultureT2) && (InstantInfluence > InstantCulture)

And again can be expressed as
InfluenceT2 * LifeTimeCultureT1 * InstantInfluence > InfluenceT1* LifetimeCultureT2 * InstantCulture
(note they are multiply operations, not additions, and this only works because they all are positive values)

You can use two variables if you like (iLHS and iRHS), but it can be expressed in a single variable, as I did. Sounds silly, but usually those tricks release memory and speed up operations.
InfluenceT2 * LifeTimeCultureT1 * InstantInfluence - InfluenceT1* LifetimeCultureT2 * InstantCulture > 0


Also, I'm still wondering why you need this check:
    if (kOtherPlayer.GetCulture()->GetLastTurnLifetimeCulture() > 0 && kOtherPlayer.GetJONSCultureEverGenerated() > 0)

Those values are going to be >0 really soon, they are never negative and there's no (crash) problems when they are 0 (or even if they ever become negative by a bug) because no division is ever made.

Finally, the comments need to be updated too. They are not explaining what happens now.

**Comment by LoneGazebo** [comment]
@tu-79 normally I'm all in favor of optimization, but since this is only called by the UI it'll barely register (in terms of performance). 

This is c++ not LUA btw - LUA is just the UI interface.

**Comment by tu-79** [comment]
Of course, you are right: When performance is not critical, clarity beats optimization. In other words, don't optimize if it means that the code is turning illegible, optimize otherwise.

However I find it more clear to have one single local variable called iInfluenceTrend that is positive when the trend is rising and negative when it is falling, than having two local variables called LHS and RHS, that I may guess are acronyms for LeftHandSide and RightHandSide, after reading the comments because I didn't understand the code at first sight. It is faster too, since the machine is quite good at making basic algebra operations, but not so good at doing memory allocations. The only reason I see for keeping the current structure is that these variables iLHS and iRHS are being used outside of this function. In that case, the solution is easy:

    iInfluenceTrend = iLHS - iRHS;

Speaking of clarity, the if block is easier to understand not using 'else', specially since this part adds nothing to the result. (When the trend is not rising, 'else' means that influence is static or falling. Else is a useful structure to avoid doing a logical comparison again, but here you are not saving any logical comparison with its use. The only thing that could optimize this would be to use an exact comparison 'iInfluenceTrend == 0' somewhere, which you don't want to do). So you can put it as
    if (iInfluenceTrend > 0) then RISING;
    if (iInfluenceTrend < 0) then FALLING;
the text is clear and nothing is lost.

If nothing else, use multiply signs in iLHS and iRHS instead of sum signs, or that part will be wrong.

Side note: I see. So LUA compiles with gcc too. When I tried to learn Python, there were some claims that the compiler for Python (also a layer to C++) could do some magic for bad code, doing automatic optimizations when the optimized alternative was clear. I though LUA behaved similarly, not worrying about low level optimizations.

**Comment by wobuffet** [comment]
Please ignore if I don't understand something, but could the "STATIC" option trigger within some close-to-zero band (say, LHS and RHS are within 2% of each other)?

**Comment by tu-79** [comment]
Yeah, sure. Just put this
    if (iInfluenceTrend > 0.05) RISING
    if (iInfluenceTrend < 0.05) FALLING

So anything less than a 5% difference is considered STATIC.
