### ISSUE TITLE
Can see Historical Sites before Archaeology is researched

### ISSUE THREAD

**Issue by InapropriateUsername** [LoneGazebo/Community-Patch-DLL#4164]
_1. Mod version 4-5 beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Can see Historical Sites before Archaeology is researched (after i captured Archaeologist)

Not a big deal, but still

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/19764746/38573661-736af074-3cff-11e8-99d3-9fabbf6f64d0.png)

**Comment by LoneGazebo** [comment]
It's an EUI thing. @Infixo any ideas? I hate EUI.

**Comment by Infixo** [comment]
It's not EUI. Those pink markers are from "Global - Archaeologist Dig Sites" mod incorporated into CBO. The script has not checked if a tech that revealed artifacts at all had been researched.

**Comment by LoneGazebo** [comment]
aha, forgot about that included modmod. Thanks!
