### ISSUE TITLE
Missing lines in CityView.lua and EUI_tooltip_library.lua

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#4165]
_1. Mod version (i.e Date - 4/23): 4/11
_2. Mod list (if using Vox Populi only, leave blank): none
_3. Error description:_ 

In Version 4-5 the following lines were added in GitHub rep to CityView.lua (876-879):
```
-- Yield bonuses to World Wonders
if city:GetNumWorldWonders() > 0 and Game.IsWorldWonderClass(buildingClassID) then 
    buildingYieldRate = buildingYieldRate + cityOwner:GetExtraYieldWorldWonder(buildingID, yieldID)
end
```
However, the released CityView.lua in (6a) subdir doesn't contain those lines.

Same situation with EUI_tooltip_library.lua. Similar lines were added, but they are not present in released version.

**Comment by LoneGazebo** [comment]
Weird.

**Comment by Infixo** [comment]
But are they supposed to be there or not? I need to know if I should update Improved City View if so.

**Comment by LoneGazebo** [comment]
I think so? I don’t remember if I baked that into the cost model or not.

**Comment by HungryForFood** [comment]
I added it, in #4129, as Trait_YieldChangeWorldWonder was not showing up in the UI (yields added correctly).

**Comment by Infixo** [comment]
Lines are present in 4-20.
