### ISSUE TITLE
Purchasing Archaeologists with faith for any Reformation

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#4167]
_1. Mod version (i.e Date - 4/23):_

4/5
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

In my play I've noticed it repeatedly, and a brief test showed the wrong reformations allow purchasing Arch with faith. I believe this is whats missing from the code files

UPDATE Units
SET RequiresFaithPurchaseEnabled = '1'
WHERE Type = 'UNIT_ARCHAEOLOGIST';

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
In my current game the same, I can buy archeologists but I has Crusader Spirit reformation.

**Comment by LoneGazebo** [comment]
Huh. Add that code @deadstarre and report back.

**Comment by deadstarre** [comment]
yeah it fixes it. but i dont think anybody is going to be happy when this gets fixed lmao

**Comment by LoneGazebo** [comment]
Heh.
