### ISSUE TITLE
Japan's Eight Virtues is only three virtues

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4168]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
On the newest patch, I went Japan, gave myself crazy bonuses to quickly spam Pikemen with Dojo, and made 18, swiftly  getting them promos. There's about 8 Courages, 7 Sincerities and 3 Righteousnessness, so the same as in the previous thread - this is the third game in a row only those three can be gotten (and previous games had a much bigger sample and weren't made with Really Advanced Setup, so more legit), though two games were before the patch. What happened to Benevolence, Respect, Loyalty, etc? Are they cut out from the code?

**Comment by deadstarre** [comment]
![respect](https://user-images.githubusercontent.com/15820785/38625242-ffc7ca2e-3d77-11e8-953d-6f32425b0c98.jpg)

**Comment by LoneGazebo** [comment]
No. I didn’t get a chance to heavily test the code for this. It’s on my list though.

**Comment by ilteroi** [comment]
let's just use the regular old RNG for this?

on the other hand, maybe i should instrument the fake RNG and see if it can be improved, because that would affect many usecases.

**Comment by Enrico-Swagolo** [comment]
I think Japan's RNG was fine a year or two ago. I haven't played them much since, but I think a year ago a game I quit because of balling too hard due to the start I think something similar happened. As it was long ago my memory might be wrong, but I clearly remember I felt something was wrong with the promotions and I remember lots of Righteousnesses. It started happening around the time the multiple Dojo promos bug was fixed. RIP in Respect super dojo guys

**Comment by LoneGazebo** [comment]
@iltero I don’t trust the built in RNG. Especially not for MP.

**Comment by LoneGazebo** [comment]
@ilteroi* :)

**Comment by Iamblichos** [comment]
I figured that having it RNG on the *plot would've given those units plenty of variety. I know getting early ruins seems much improved...

**Comment by ilteroi** [comment]
ok, did some checks. there is definitely a math problem here. for example the fake RNG for [0;3[  never returns 2.

so apparently my method was too naive. i'll use some official hash function and see if that's better.

**Comment by Enrico-Swagolo** [comment]
So you mean 0;3 randomised only returns 0, 1 and 3? I don't know much about the code, but notice there's three results of your thing and also only 3 Virtues you can get. Maybe it only considers the first two and the very last possibility (or possibility number 3)?

**Comment by raphaell666** [comment]
I think he used [ for open interval, so we would expect [0:3[ would return 0, 1 and 2, but he said it never returns 2.

**Comment by ilteroi** [comment]
much better now. example for [0;8[ - not perfect but good enough

value | count
0 | 61
1 | 58
2 | 64
3 | 40
4 | 65
5 | 64
6 | 65
7 | 62

**Comment by ilteroi** [comment]
unrelated, but observe the venetian empire:

![image](https://user-images.githubusercontent.com/1358966/38766056-a6963740-3fcc-11e8-80ab-c901f09f88a2.png)
