### ISSUE TITLE
Crashes when founding World Congress

### ISSUE THREAD

**Issue by dwild428** [LoneGazebo/Community-Patch-DLL#417]
7/1 Version, CP/CBP/CSD/C4DF/EUI+Compat, More Lux.  No other mods.

The game is consistently crashing when I click the "Make a Proposal" button when I am about to found the first world congress

Here is my crash dump and log files: https://www.dropbox.com/s/o9nh0og93470pi9/ErrorDetails.zip?dl=0

**Comment by LoneGazebo** [comment]
I can't decipher anything here, as the crash dump leads to lua, and the database files are inconclusive. I'll see if I can reproduce, but for now, I'll mark this as unresolveable.

G
