### ISSUE TITLE
Building_ImprovementYieldChangesGlobal  Yield for GA/GG's

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#4170]
_1. Mod version (i.e Date - 4/23):_

4/5
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Trying to put Great General points onto an improvement using Building_ImprovementYieldChangesGlobal and YIELD_GREAT_GENERAL but it doesn't seem to be functional. May be designed that way and no options otherwise but figured i'd ask anyway
 
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Yeah that table isn’t initialized for those yields unfortunately.

**Comment by deadstarre** [comment]
ok np

**Comment by LoneGazebo** [comment]
I guess someone else initialized it, then, because on creation I excluded some yields. :)

G
