### ISSUE TITLE
Fealty does not give production/gold

### ISSUE THREAD

**Issue by maptap** [LoneGazebo/Community-Patch-DLL#4173]
_1. Mod version (i.e Date - 4/23):_
4/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

The description in the fealty policy says that each level  gives one food, production and gold; however, this did not happen in game. Upon checking the code I could not find the code for increase in production or gold. Thanks!

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by raphaell666** [comment]
I think you are having some mod conflict? Or misunderstanding? The description of Fealty says:
```
Each Fealty unlocked grants:

+1 Food and +3 Defense in every City.
```

It does not grant neither production nor gold when unlocking Fealty policies.

**Comment by maptap** [comment]
Oh, must be a mod conflict then. Thanks for letting me know.
