### ISSUE TITLE
Some new games have much longer load times

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4177]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Most of my new games start near instantaneously, but sometimes I start a game and it takes many, many times longer. Like, 10-20-30 times longer, the announcer guy usually can be stopped by his first sentence as the game loads, but with some games he can finish all his lines and the game's still not loaded. I assume it might be related to some civ that appears in the game... If I restart, the new game creation will take just as long, and hitting Restart on the very first turn doesn't change player races. Here's such a save.
[longloadCasimir III_0000 BC.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1904527/longloadCasimir.III_0000.BC.zip)

It's been happening for... around since the new post march beta? Some games it happens, some it doesn't.  Starting that particular game, restarting game (from the in-game menu on turn 0), even loading is affected.

**Comment by bigcat88** [comment]
Hm, in my games I didn't notice that(restart games or just starting new)(I didn't at PC right now so can check your save).
Have you checked with old version(early feb for example) before posting, to exclude some hardware/software troubles(maybe some soft that slow PC was installed from that time or CPU fan start to die)? Just to be sure that problem is somewhere in Vox. Sry if you did that already.

**Comment by Enrico-Swagolo** [comment]
I don't think so, if it was a malfunction why would it only happen to particular games?  I can get a super long load game, then close Civ 5, run it again, start a new one and the load time will be the usual fast.

If after starting a new game it doesn't load long, restarting won't change it no matter how many times it occurs, only if the first time it loads long then it'll keep through restarts (unless you go to main menu, which changes civs). If I load or restart one which loads long, it'll load super long every time. Try the save (11th hotfic).

**Comment by LoneGazebo** [comment]
@Enrico-Swagolo one thing you can do is this: install http://www.codersnotes.com/sleepy/
Run civ. Run VS. Tell it to monitor Civ 5.exe. Load your game. Once loaded, End the session, then let it process. Click file, save as, then post. :)

**Comment by Enrico-Swagolo** [comment]
wut I did it, installed the thing, opened civ, did stuff to make VS appear, chose it to profile Civilization5 11dx exe because I didn't see civ5 exe, configuring game data to load mods took like 2/3 times longer than usual (no doubt since the program was inspecting it), even load time was  even longer, then as I close civ 5 it said there's an error and if I want to abort or stop, I chose stop because it said it'd tell me about threads but it lied, VS profiler thingy didn't appear. I should go to VS and tell it to stop before closing Civ 5 I guess, will try again

**Comment by Enrico-Swagolo** [comment]
[for geese.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1906769/for.geese.zip)

Okay here it is? I think? I told it to inspect as the game was starting to load after choosing DX11 in the menu.

**Comment by LoneGazebo** [comment]
Yeah sorry you need to end the process for VS then close civ.

**Comment by Enrico-Swagolo** [comment]
Aye I figured it out, the zip i pnrevious post contains the file

**Comment by LoneGazebo** [comment]
Unfortunately can't really reproduce this reliably.
