### ISSUE TITLE
GP Tiles from Custom Civs don't contribute to bulbing

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4179]
_1. Mod version (i.e Date - 4/23):_4/11

_3. Error description:_ Great people bulbs scale with the number of previous great person tiles
Towns increase WLTKD
Manfactories give more hurry production
Academies give more research

This currently affects 2 modmods: 
4UC has a unique Celtic Town replacement
Olmec mod for VP gives players Colossal Head GP improvement

If the bulbing bonus was exposed to SQL with a new table, then modders could add new GP tiles to their creations. Maybe they could also create non-GP UIs which contribute to bulbing

**Comment by Iamblichos** [comment]
Should be fairly straight forward to implement.

**Comment by LoneGazebo** [comment]
I'll see what I can do.
