### ISSUE TITLE
Request: merge 2 archaeology-related mods into the CBP

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#418]
http://www.picknmixmods.com/mods/44b7cffb-9c0a-42df-b0f8-5037780e60cb/mod.html
http://www.picknmixmods.com/mods/868e845c-a185-4e00-b0f9-f0c971e0ec1c/mod.html
As of right now it highlights hidden sites when Imperialism is finished as opposed to Aesthetics.
Even better would be if selecting an archaeologist will show only sites icons.

**Comment by LoneGazebo** [comment]
Done.
