### ISSUE TITLE
late game observations

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4181]
so it seems venice is performing much better. check this:

![image](https://user-images.githubusercontent.com/1358966/38766117-dee98e20-3fcd-11e8-8f3c-92da20569aee.png)

however, they got a number of these cities via revolts, so in the next version the picture might be different.

the real problem is that they have hardly any military. altough they could well afford it.

![image](https://user-images.githubusercontent.com/1358966/38766203-16b49af6-3fcf-11e8-98cb-09936d700ebc.png)

the have 14 units free and 6000+ gold. but no garrisons nowhere. why not buy some units?

war weariness penalty is confusing right now: percent or absolute number?

![image](https://user-images.githubusercontent.com/1358966/38766379-aaf11c06-3fd1-11e8-8ceb-4bc6f5e6eed2.png)

also, happiness is a bit silly right now with the latest puppet changes. without war weariness they'd be at +230.

**Comment by ilteroi** [comment]
this is germany, their main competitor:

![image](https://user-images.githubusercontent.com/1358966/38766310-7d995314-3fd0-11e8-8bac-0e5f8adf314c.png)

how come they have 20k gold but -700 gpt?

![image](https://user-images.githubusercontent.com/1358966/38766317-aaf81cc8-3fd0-11e8-9aca-c36fe3cc2b14.png)

**Comment by Iamblichos** [comment]
My criticisms of naval operations seems improved too. I’m seeing them dying with their boots on if your gonna die.

**Comment by LoneGazebo** [comment]
@ilteroi instant yields from events, possibly also trade deals could account for the treasury spikes. Re: Venice, do you have the hurry production logs? I could see what they're rating unit purchases.

**Comment by ilteroi** [comment]
re logs, those are yuuuuge. there may be a bug somewhere?

in turn 497 each venetian city running hurry choice 16 times apparently. example satsuma:

<pre>
497, Venice, Satsuma, PRE: Building, Seaport, 9382, 8
497, Venice, Satsuma, PRE: Building, Recycling Center, 3324, 20
497, Venice, Satsuma, PRE: Building, Research Lab, 3719, 10
497, Venice, Satsuma, PRE: Unit, Guided Missile, 2146, 13
497, Venice, Satsuma, PRE: Unit, Cargo Ship, 5160, 1
497, Venice, Satsuma, PRE: Building, CERN, 134, 51
497, Venice, Satsuma, PRE: Building, Factory, 2518, 7
497, Venice, Satsuma, PRE: Building, Wind Plant, 1179, 14
497, Venice, Satsuma, PRE: Unit, Caravan, 2510, 1
497, Venice, Satsuma, PRE: Building, Train Station, 1156, 7
497, Venice, Satsuma, PRE: Building, Medical Lab, 603, 14
497, Venice, Satsuma, PRE: Building, Agribusiness, 949, 7
497, Venice, Satsuma, PRE: Unit, Bazooka, 544, 13
497, Venice, Satsuma, POST: Building, Research Lab, 1312575, 10
497, Venice, Satsuma, POST: Unit, Guided Missile, 536575, 13
497, Venice, Satsuma, POST: Unit, Bazooka, 36562, 13
497, Venice, Satsuma, POST: Unit, Cargo Ship, 29250, 1
497, Venice, Satsuma, POST: Unit, Caravan, 29250, 1
497, Venice, Satsuma, POST: Building, Medical Lab, 3280, 14
</pre>

this repeats 16 times (for all cities). same result each run.

then in 498 and 499 i only see a single "pre" line for each city ...

<pre>
498, Venice, Osaka, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Florence, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Satsuma, PRE: Unit, Archaeologist, 1006, 2
498, Venice, Lhasa, PRE: Unit, Archaeologist, 1006, 2
498, Venice, Boston, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Atlanta, PRE: Unit, Archaeologist, 1006, 2
498, Venice, Kabul, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Almaty, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Antananarivo, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Vilnius, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Genoa, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Geneva, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Nippur, PRE: Unit, Archaeologist, 1006, 2
498, Venice, Bogota, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Yakutsk, PRE: Unit, Archaeologist, 1006, 2
498, Venice, Vladivostok, PRE: Unit, Archaeologist, 1006, 2
498, Venice, Chicago, PRE: Unit, Archaeologist, 1140, 1
498, Venice, New York, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Ondini, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Kyoto, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Smolensk, PRE: Unit, Archaeologist, 1140, 1
498, Venice, Borsippa, PRE: Unit, Archaeologist, 1006, 2

499, Venice, Florence, PRE: Unit, Archaeologist, 1140, 1
499, Venice, Satsuma, PRE: Unit, Archaeologist, 1006, 2
499, Venice, Lhasa, PRE: Unit, Archaeologist, 1006, 2
499, Venice, Boston, PRE: Unit, Archaeologist, 1140, 1
499, Venice, Atlanta, PRE: Unit, Archaeologist, 1006, 2
499, Venice, Kabul, PRE: Unit, Archaeologist, 1140, 1
499, Venice, Almaty, PRE: Unit, Archaeologist, 1140, 1
499, Venice, Antananarivo, PRE: Unit, Archaeologist, 1140, 1
499, Venice, Vilnius, PRE: Unit, Archaeologist, 1140, 1
499, Venice, Genoa, PRE: Unit, Archaeologist, 1140, 1
499, Venice, Geneva, PRE: Unit, Archaeologist, 1006, 2
499, Venice, Nippur, PRE: Unit, Archaeologist, 1006, 2
499, Venice, Bogota, PRE: Unit, Archaeologist, 1140, 1
499, Venice, Yakutsk, PRE: Unit, Archaeologist, 1006, 2
499, Venice, Vladivostok, PRE: Unit, Archaeologist, 1006, 2
499, Venice, Chicago, PRE: Unit, Archaeologist, 1140, 1
499, Venice, New York, PRE: Unit, Archaeologist, 1140, 1
499, Venice, Ondini, PRE: Unit, Archaeologist, 1140, 1
499, Venice, Kyoto, PRE: Unit, Archaeologist, 1140, 1
499, Venice, Smolensk, PRE: Unit, Archaeologist, 1140, 1
499, Venice, Borsippa, PRE: Unit, Archaeologist, 1006, 2
</pre>

the last 50k lines from the log are here:
[short.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1911996/short.zip)

**Comment by LoneGazebo** [comment]
Well. That’s strange.
