### ISSUE TITLE
Disabled Open Borders Agreement Option

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4183]
_1. Mod version (i.e Date - 4/23):_ latest

_2. Mod list (if using Vox Populi only, leave blank):_ FlagPromotions

_3. Error description:_ 
Unable to ask Sweden for Open Borders, neither can offer it (Open Borders option in diplomacy window is greyed out and no red text explains why). Both embassies are built on either side and no Open Borders agreement is active at the moment.

_4. Steps to reproduce (optional):_

savegame attached 

[NoOpenBorders.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1910650/NoOpenBorders.zip)

**Comment by bigcat88** [comment]
Sanction proposal?

**Comment by saamohod** [comment]
>Sanction proposal?

Could you elaborate?
