### ISSUE TITLE
[graphic bug]After CS sucked by barbs

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4184]
_1. Mod version (i.e Date - 4/23):_
last and previous(see in Feb versions the same)

_3. Error description:_ 
Look at screens, there is no barb(strategic view is correct). After I reload game, the barb unit icon will disappear. 

_4. Steps to reproduce (optional):_
If you cant reproduce it, maybe I will try to make a save before this thing appears.

![20180414201841_1](https://user-images.githubusercontent.com/13381981/38770843-b21a85b2-4021-11e8-9274-eb1213f31821.jpg)

![20180414202033_1](https://user-images.githubusercontent.com/13381981/38770844-b5a72f5a-4021-11e8-8359-932206835b3c.jpg)

**Comment by LoneGazebo** [comment]
Classic UI bug, never able to solve w/o reload, even in vanilla.
