### ISSUE TITLE
Bugged ranged attack hexes

### ISSUE THREAD

**Issue by CannedJuice** [LoneGazebo/Community-Patch-DLL#4185]
_1. Mod version (i.e Date - 4/23):_
2018/03/17

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch
EUI
_3. Error description:_ 
With EUI properly installed (removing the CP LUA folder), ranged units have bugged ranged hexes when they go to attack. This issue is fixed, provided that you leave Bombardment.lua in the CP LUA folder. When you do this, however, the city banner gets a bit messed up, and units you're at war with lose their red outline.
![lmhh](https://user-images.githubusercontent.com/25729096/38775067-871c1dd8-4046-11e8-981f-36ee8332e92b.jpg)

**Comment by ilteroi** [comment]
easy fix: use the EUI version included in the VP installer. others are not supported.

**Comment by CannedJuice** [comment]
The installer specifically? Or is the manual install folder linked on the CP page up to date? I just now grabbed the EUI file from the manual folder and that, too, had the same issue as before. Along with that, I tried the one from the installer and that also presented the same issue.

**Comment by Infixo** [comment]
I have installed EUI like 2 years ago, version with letter „g”, can’t remember numbers now. Since then I literally have not touched the EUI folder, like ever. Every time a new VP comes out, i remove all old folders 1-6, clear cache and install a new version (VP with EUI). That is all. And every single time it works perfectly, I never had any problems after installation.

**Comment by CannedJuice** [comment]
When I tested using the VP and EUI install from the installer it worked fine. The issue I was having is specifically presented with the CP and EUI. If you keep all of the lua files from the CP, EUI breaks. If you remove the lua files from CP, then the ranged attack hexes break. The only way I found to fix it was to use the Bombardment.lua file from the CBO compatibility mod, as detailed above.
