### ISSUE TITLE
No barbarians on the newest version

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#419]
Not even camps show up.
The only non-CBP mod I use is InfoAddict.

**Comment by LoneGazebo** [comment]
They work for me...

**Comment by Radost** [comment]
What settings did you test?
I am playing on huge communitas maps, epic speed and warlord difficulty.

**Comment by LoneGazebo** [comment]
Basic maptype. I didn't try the communitas map, but it doesn't have a unique assignstartingplots.lua IIRC. I'll check.
G

**Comment by LoneGazebo** [comment]
Checked communitas map, works for me. Must be an issue with your install.
G

**Comment by Radost** [comment]
I didn't change anything from the usual installation procedure though.

**Comment by LoneGazebo** [comment]
Not sure then. Like I said, barbs are showing up for me - tested multiple maps.
G

**Comment by Nylok87** [comment]
Did a fresh install of CP/CBP, CSD, Civ 4 Diplo, and the non EUI patch. No barbarians on Communitas or YNAEMP Giant Earth. Though it seems to only happen when I have 22 civs. Less than that results in barbarians.

**Comment by Radost** [comment]
@Nylok87 
Moreover, the 22nd player starts as "visible" to the player from the turn one.
So this bug interconnects with that https://github.com/LoneGazebo/Community-Patch-DLL/issues/426 one.

**Comment by ilteroi** [comment]
yep, most probably same root cause as #426 - although this one i don't completely understand yet
