### ISSUE TITLE
Feature request - local yield changes table for great works

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4195]
There is a table to change the yields from all great works **on empire**: Building_GreatWorkYieldChanges

It would be nice for modders if there was a **local** equivalent to this table, which only affects GWs in the city where the building is located.

If these tables could be broken up by type (GW music/writing/art/artifact) as well, that would add a lot more flexibility for modders.

**Comment by deadstarre** [comment]
I think that table had some weird behavior when adding tourism I tested it the other day, i was actually gaining +2 tourism instead of the +1 I entered and the EUI attributed the extra yield to "tourism from city" - it didnt make any sense to me, i ended up just using a different yield

**Comment by LoneGazebo** [comment]
added for 4-20/ Also fixed that table @deadstarre 

G
