### ISSUE TITLE
Crash Late Game on Particular civ's turn.

### ISSUE THREAD

**Issue by Jamesuh** [LoneGazebo/Community-Patch-DLL#4196]
_1. Mod version (i.e Date - 4/23):_
Beta 4/5

_2. Mod list (if using Vox Populi only, leave blank):_
Of course Vox Populi, the only way to go.

_3. Error description:_ 
Freezing when it's Japan's turn. Have tried multiple "view/fast move" options.

_4. Steps to reproduce (optional):_
Game is saved up to the point of pressing next.

PS. Lurker on the forum, so I want to use this opportunity to say thank you Gazebo and others that made Vox Populi possible. I've never been so obsessed with any other game, it's just freakin brilliant. Really appreciate the time and effort you put into this project. If you're ever in Charleston, SC please let me know. It be an honor to treat you to more than a few beers!
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

[crash save file.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1917028/crash.save.file.zip)

**Comment by LoneGazebo** [comment]
Have you tried stepping into strategic view mode?

**Comment by Jamesuh** [comment]
Yes. I also tried loading a earlier auto save and lowered Japan's taxes as well as moving military to different taxes.. Got the thank you screen from Japan, and it still freezes like before.

**Comment by Jamesuh** [comment]
I'm on the processing turn from Japan screen. I'm able to move my mouse over the hexes and I get the black box that expands into more info just fine. Not sure if that's helpful. And I just clicked once and it's frozen. Are you getting the same thing gazebo?

**Comment by Jamesuh** [comment]
Here is a save file for turn 634. Error between 636/637.
[turn 634.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1918117/turn.634.zip)

**Comment by Jamesuh** [comment]
Installed gazebos latest patch for fillyb and it solved the problem!
