### ISSUE TITLE
Show number of turns remaining for "move your troops from the border" (new feature)

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#4197]
Hello. I'd like to ask for a QoL feature: When an AI asks you to move your troops from the border, would it be possible to display the number of turns remaining like with the promise not to buy tiles near them? Thank you.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@Infixo mind taking a look?

**Comment by Infixo** [comment]
@LukaSlovenia29 What window are we talking about here? Can you pls tell where is the number of turns remaining for the promise not to buy tiles near them shown?

**Comment by Infixo** [comment]
@TechpriestEnginseer 
DiploOverview -> Global Politics displays: Wars, Denounced (this one shows turns), Vassalage, DoFs, Defensive Pacts, Marriages, Allied to Minors.
The tooltip for a civ displays diplo modifiers but shows any value only if you have Transparent Diplomacy on. Also, these are not number of turns.

@LukaSlovenia29 I am still curious where you can see those turns.

**Comment by Infixo** [comment]
This tooltip is actually misleading. Promise itself doesn't affect an opinion weight, yet the tooltip shows number of turns as negative opinion modifier. Only broken promise or ignored request for a promise affect the opinion.
I will fix that, too.

**Comment by LukaSlovenia29** [comment]
Sorry, I've been busy with work. I'm glad that you found out the answer, and it's great to know that you'll be fixing the misleading tooltip. I was always worried that promising to not buy land would have a great instant impact on my relations with the AI. It's reassuring to know that if I promise & keep it, I'll be ok. Thanks again for your work&time!

**Comment by Infixo** [comment]
Changes:
- I've added support for 2 promises: military promise (move away your troops, lasts for 20 turns by default) and stop spying on me (lasts for 50 turns by default)
- Number of turns for military promise moved to Defines
- All 4 promises (the 2 above + buy land + settle near) are displayed in tooltips as Gray text (default color for diplo modifiers with 0 value)
- I also added them to Diplo Overview window

![tt](https://user-images.githubusercontent.com/25866684/39017804-8980c362-4424-11e8-8eda-f440530f17dc.jpg)
![rel1](https://user-images.githubusercontent.com/25866684/39017810-8f47465e-4424-11e8-88bd-12001946d14d.jpg)

**Comment by LoneGazebo** [comment]
rad

**Comment by LukaSlovenia29** [comment]
Looks awesome, thanks for the great work!
