### ISSUE TITLE
AI can vassalage sanctioned civs

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4198]
_1. Mod version (i.e Date - 4/23):_
last

_3. Error description:_ 
Subj. I cant propose anything to sanctioned civ with any war score and AI successfully vassalage after war.

**Comment by LoneGazebo** [comment]
Vassalage was part of a peace deal?

**Comment by bigcat88** [comment]
Yes

**Comment by bigcat88** [comment]
@LoneGazebo , you wrote on forum: "Peace deals are excluded from sanction stuff."
So that what it is. Then it just a bug, all my wars I was not able to propose anything as a reparations with a sanctioned civs.

**Comment by seth4u** [comment]
I noticed the same: I am affected by sanctions, even in a peace deal. Can only trade peace, nothing else.
