### ISSUE TITLE
[feature request] Hover to see Influence gap with 2nd-place challenger when you are top/Allied with a CS

### ISSUE THREAD

**Issue by wobuffet** [LoneGazebo/Community-Patch-DLL#4199]

**Comment by LoneGazebo** [comment]
If the AI is on top it doesn't get this info, so the player shouldn't either.

**Comment by TechpriestEnginseer** [comment]
However this has already existed based on Sukritact's code.
[img]http://i.imgur.com/zEIoLbV.png[/img]

**Comment by LoneGazebo** [comment]
So the aI does know about this, but we'd need to decide whether or not this is worth adding. @Infixo you seem to enjoy UI stuff...want to take a stab at importing sukritact's code?

**Comment by Infixo** [comment]
So, does AI do anything with that info? Like evaluate for something, compare with something, etc. If AI doesn't do anything with it then it's just the same as not knowing it. In that case I would strongly opt to NOT provide that info to the player.

**Comment by LoneGazebo** [comment]
Yes, the AI does use it to evaluate where to send diplo units.

**Comment by LoneGazebo** [comment]
CvPlayerAI line 2320

**Comment by Infixo** [comment]
Only 2nd best or does it analyze all relations?

**Comment by Infixo** [comment]
2293-2307 highest friendship level (but not knowing who)
Call to IsCloseToNotBeingAllies() is only about us to check if we're close to lose the status.
I'd say that only the level of the 2nd best should be displayed. Players can then evaluate the gap and decide if somebody is after them or how far they are from the top. Same as AI.

**Comment by Infixo** [comment]
Also, to make it easier, maybe just showing the gap would suffice?

**Comment by LoneGazebo** [comment]
@Infixo that'd be a fine compromise.

**Comment by Infixo** [comment]
A new line "Contender:" contains influence of the 2nd best or the best if there's no ally yet.
![20180503193401_1](https://user-images.githubusercontent.com/25866684/39593817-32c6d2b8-4f0b-11e8-982e-0a47c59ea1a1.jpg)

**Comment by LoneGazebo** [comment]
“Coulda been a contendah”

**Comment by adaneslavo** [comment]
Is it the final alignment of the Contender line, or it was already moved to the right, to make all colons make one line?

**Comment by Infixo** [comment]
Can't make colons in one line, already tried. The .xml here is a stack with labels within labels. They autoalign like this.

**Comment by adaneslavo** [comment]
Strange because the bottom three text lines under the thick line are well aligned. Maybe it would be better to move it to the same line as Ally? It's good to see such info, but it looks not so good. But ok, if you think it caanot be done that way, let it stay.

**Comment by TechpriestEnginseer** [comment]
I just thought you would just hover over the Ally: You or whatever and it would say you have a contender nearing 20 influence near yours or something like that.
