### ISSUE TITLE
Razing speed is doubled

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4202]
_1. Mod version (i.e Date - 4/23):_
last flibby

_2. Mod list (if using Vox Populi only, leave blank):_
Naval Warfare

_3. Error description:_ 
Look at screen ^)
Before taking that policy, previous city was razed normal(1 citizen per turn and in last turn 2 citizens)
pop:8,7,6,5,4,3,2,razed
Here I was expected to see:
8,6,4,razed

Logs & Savegame are present, will post if you need.

4. Screenshots (optional):

![20180417203740_1](https://user-images.githubusercontent.com/13381981/38886706-68acfe0e-427f-11e8-9b8e-236a4982c6f0.jpg)

**Comment by bigcat88** [comment]
And when I select promotions on units near Istanbul(I finish CS quest for capture) I got a repeatable crash. But I think it is related to that city with pop 0. Before I raze it all was stable and perfect.
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1920981/CvMiniDump.zip)

**Comment by bigcat88** [comment]
@LoneGazebo did you fix this in 20/4 version?

**Comment by LoneGazebo** [comment]
I was not able to recreate the issue, unfortunately.

**Comment by bigcat88** [comment]
What code you changed when fixed this:
https://github.com/LoneGazebo/Community-Patch-DLL/issues/4021
A month ago when policy was bugged, all was fine :)

**Comment by bigcat88** [comment]
I repeat it but without a crash(maybe I need many units/tiles near city to make governor crazy like before)
After razing number of citizens must be 8. 
Here is save from duel map(before razing start), no mods except really advanced setup and ige.
Steps to reproduce:
conquer with robot city, number of citizens will be 8, start raze, take policy(there are free policy I added throw IGE)
[t1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1934733/t1.zip)

![20180421184316_1](https://user-images.githubusercontent.com/13381981/39086013-41b3b8e8-4594-11e8-89c3-3c7764a25276.jpg)

**Comment by bigcat88** [comment]
Maybe check
`if(GetRazingTurns() <= 0 || getPopulation() <= 1)`
in CvCity::DoRazingTurn must be after:
`changePopulation(-iPopulationDrop, true);`

And banner says that city will be raised in 4 turns.

**Comment by LoneGazebo** [comment]
I'll look.
