### ISSUE TITLE
Possible UI bug or yield calculation error with Town + new (same turn) Trade Route [Caravan]

### ISSUE THREAD

**Issue by dape6509** [LoneGazebo/Community-Patch-DLL#4203]
_1. Mod version (i.e Date - 4/23):_
4/5

_2. Mod list (if using Vox Populi only, leave blank):_
Flag Promotions
Map Labels
Info Addict
R.E.D. Modpack
Strange Religions
Favorite Religion Randomizer

_3. Error description:_ 
Towns do not appear to gain +1g and +1p according to the city/empire yield totals on the same turn that a Caravan Trade Route over its tile is initiated, despite the tile graphic and tile tooltip changing to reflect the new yields, I understand that the +1g/p from being on a Road is not available as I am still in the process of connecting the road to my other cities. I will also note that the tile graphic and tooltip had still not updated on the following turn when I initially segued from this turn, but when I reloaded the following turn from menu, both the tile graphic and tooltip had updated correctly. I will include both the previous and subsequent turn saves for comparison. I know there was a hotfix on 4/11 but I did not see any changes related to yields so I have not tried applying the hotfix yet.

P.S. If anyone can tell me how to make Favorite Religion Randomizer include the additional religions from Strange Religions etc., I'd greatly appreciate it! :+1: 

_4. Steps to reproduce (optional):_

1) Plant a Town in workable radius.
2) Build a road tile through it connecting to new TR origin city (This is only necessary for my case or a similar case as I made sure to have this road section up by the time my previous Caravan TR expired so that the new TR would cross over the Town, as in the previous route it did not.) Account for the +1g/+1p  in Town yields from Road if it connects two owned city, otherwise ignore as in my case.
3) On turn that a new Caravan becomes available in the relevant city (new Caravan bought/built, previous CTR expires, Caravan changes home city from previous turn, etc.) and before the TR is assigned, check tile yields for Town in graphic and tooltip against total city Production/empire Gold tooltips.
4) Compare to graphic/tooltip and totals for other worked tile if Town not worked that turn (the Fishing boat north of Constantinople in my example. This is likely optional but helped me recognize the bug. In my case the Town had +2g and -1p compared to the Fishing Boat before the TR, +3g after the TR).
5) Assign TR to route that crosses Town, compare graphic/tooltip yields for Town to yield totals in city Production/empire Gold. Compare to yields from Citizen working other tile if necessary.
6) Complete turn, compare yields on next turn to this turn. Yields should now be updated properly in all graphics and tooltips, though may require a reload as in my case (not sure if that is reproducible)
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1921525/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1921532/Saves.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![8930_20180417134722_1](https://user-images.githubusercontent.com/19981950/38896730-d186081e-4250-11e8-86fc-da865c8f8663.png)
![8930_20180417134819_1](https://user-images.githubusercontent.com/19981950/38896731-d1968946-4250-11e8-8de1-3d4e1e3d73da.png)
![8930_20180417134824_1](https://user-images.githubusercontent.com/19981950/38896732-d1aa636c-4250-11e8-97c4-3a574ac4b5b0.png)
![8930_20180417134847_1](https://user-images.githubusercontent.com/19981950/38896733-d1bc73fe-4250-11e8-9a44-4060d4bacf5a.png)
![8930_20180417134853_1](https://user-images.githubusercontent.com/19981950/38896734-d1cb7868-4250-11e8-881a-15cf3dd87625.png)
![8930_20180417134914_1](https://user-images.githubusercontent.com/19981950/38896735-d1dc5e3a-4250-11e8-9e83-4e218168207a.png)
![8930_20180417135012_1](https://user-images.githubusercontent.com/19981950/38896736-d1ed231e-4250-11e8-883e-f71103a836fe.png)
![8930_20180417135029_1](https://user-images.githubusercontent.com/19981950/38896737-d1fe7ab0-4250-11e8-9c72-5d3b13592dd7.png)
![8930_20180417135135_1](https://user-images.githubusercontent.com/19981950/38896738-d2119f32-4250-11e8-8adf-03667ad9b176.png)
![8930_20180417135141_1](https://user-images.githubusercontent.com/19981950/38896739-d2247de6-4250-11e8-8ede-9e664c78c7fa.png)
![8930_20180417135154_1](https://user-images.githubusercontent.com/19981950/38896740-d235a044-4250-11e8-9e8c-dfdcac0e7056.png)
![8930_20180417135205_1](https://user-images.githubusercontent.com/19981950/38896741-d2478e62-4250-11e8-99d7-06031923ff36.png)
![8930_20180417135614_1](https://user-images.githubusercontent.com/19981950/38896742-d259715e-4250-11e8-8e7c-8f10b2531cf0.png)
![8930_20180417135652_1](https://user-images.githubusercontent.com/19981950/38896743-d26d81d0-4250-11e8-8dc1-88cdd1eff49f.png)
![8930_20180417135701_1](https://user-images.githubusercontent.com/19981950/38896744-d28158c2-4250-11e8-938c-5f2e7c71d36b.png)
![8930_20180417135719_1](https://user-images.githubusercontent.com/19981950/38896745-d29d0d1a-4250-11e8-9a98-be7c511a5a86.png)
![8930_20180417135745_1](https://user-images.githubusercontent.com/19981950/38896746-d2ba6a36-4250-11e8-87c6-7ed3814c7691.png)
![8930_20180417135753_1](https://user-images.githubusercontent.com/19981950/38896747-d2cf3a2e-4250-11e8-9bab-c4acc1dd5d88.png)
![8930_20180417135806_1](https://user-images.githubusercontent.com/19981950/38896749-d2e573a2-4250-11e8-8251-861cbc2edfc2.png)

**Comment by LoneGazebo** [comment]
Thanks for the detailed write-up. This is normal behavior - the tile data can't update until the next turn, whereas the UI can because the UI is simply grabbing the tile yields (not recalculating the whole city).

G

**Comment by dape6509** [comment]
I see, thank you! Just to be clear, does this mean the additional yields from the TR path are included in the actual calculations at the end of the same turn or not? Just want to know if I need to remember to take this into account in the future. By the way, I just remembered that I tried to send two trade routes to the same city-state and was confused why the route showed up in the Available Trade Routes list but not in the Establish Trade Route menu until I remembered the limit of one TR per city from a few patches ago. Not sure if this is documented in-game anywhere or not, if so I have missed it but just wanted to check if a tooltip warning could be added or anything like that. Cheers!

**Comment by dape6509** [comment]
In case anyone else is wondering,  I checked and the additional yields were not calculated for that turn when I worked the Town. I had the tile yield graphic still not updating on the subsequent turn unless I reloaded but the yields did calculate on that turn and the graphic updated properly on the turn after that.

**Comment by ryanmusante** [comment]
<CustomModOptions>
		<Update>
			<Where Name="RELIGION_NO_PREFERRENCES"/>
			<Set Value="1"/>
		</Update>
		<Update>
			<Where Name="RELIGION_RANDOMISE"/>
			<Set Value="1"/>
		</Update>
	</CustomModOptions>
