### ISSUE TITLE
AI units not removed from territory when declaring war

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#4204]
_1. Mod version (i.e Date - 4/23):_
flibby hotfix + info addict

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Denmark and Vassal Portugal had open borders with me when he declared war, but their military units were not expelled from my borders

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20180417194229_1](https://user-images.githubusercontent.com/13261433/38905676-b6e77d40-4277-11e8-8b90-47997fac3184.jpg)

**Comment by HalfEmptyMug** [comment]
Issue also present in hotfix version 4/24, without EUI or other mods.
