### ISSUE TITLE
Last tech does nothing (2/7)

### ISSUE THREAD

**Issue by TyborPL** [LoneGazebo/Community-Patch-DLL#4205]
_1. Mod version 2/7

_2. Mod list :
Ingame Editor
Custom Advanced Setup

_3. Error description:_ 
Last tech does not give happiness boost. When the tech is finished it could be researched again and again in the constant loop.

_4. Steps to reproduce (optional):_

Screenshots:
![1](https://user-images.githubusercontent.com/36968943/38956108-f7589b54-4356-11e8-8b0f-259f04baeb60.jpg)
![2](https://user-images.githubusercontent.com/36968943/38956127-031d5c40-4357-11e8-986d-94442a6721e3.jpg)
![3](https://user-images.githubusercontent.com/36968943/38956143-09b8d728-4357-11e8-9108-2b67d7e39c24.jpg)

Download this save (**hotseat save**) and spend available scientist to research last tech.
Save:
[2-7 bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1925682/2-7.bug.zip)

**Comment by Jamesuh** [comment]
I am also experiencing this problem.
