### ISSUE TITLE
VP CTD

### ISSUE THREAD

**Issue by myles1718** [LoneGazebo/Community-Patch-DLL#4208]
_1. Mod version (i.e Date - 4/23):_
Latest VP with 4/11 with Flibby hotfix

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Complete reinstall of BNW and VP. All mods load then the game CDT
[xml.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1927981/xml.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1927983/Database.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1927984/Lua.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
More info?
CTD during your turn? during AI turn?
When opening a panel or doing something?
Early game? Late game?

**Comment by Iamblichos** [comment]
A save game would be good if you can so I could attach it to Visual Studio.

**Comment by myles1718** [comment]
Mods load, check advanced set up details, press Play Game - CTD

**Comment by MoiMagnus** [comment]
Looking at the database log. The mod is not correctly loaded.
Make sure that after loading the mods, you see in the menu exactly 6 mods numbered (1), (2), (3), (4), (5) and either (6a) or (6b) or (6c).
(You can add a screenchot here).
If the mods are not numbered correctly (or missing), then the installation is faulty.

**Comment by myles1718** [comment]
Havee mods 1, 2, 3, 4, 6a, 7, 7r, 8, 9  No Number 5

**Comment by MoiMagnus** [comment]
If I'm not mistaken, (5) is supposed to be More Luxuries, and you are most likely encountering a bug from Civ mod manager. Here is a way to avoid it:

Go into your MODS folder, and delete any folder that have More Luxuries (or something similar) in its name. Go into steam workshop, and UNsubscribe to any mod that have More Luxuries (or something similar) in its name. Reinstall VP (with the auto installer), and try to load VP again.

First try only with the mods 1 to 6a. While the mods 7, 7r, 8 and 9 are supposed to be compatible, they may have some bugs, so first try to make work the base of VP before adding them.

**Comment by MoiMagnus** [comment]
As a general rule, avoid to have in your MODS folder different copies of the same mods (obtained by different means, here steam and auto-installer), the civ mod manager is buggy.

**Comment by TechpriestEnginseer** [comment]
7 requires 5 8 and 9 requires 5 as well

**Comment by myles1718** [comment]
VP 1, 2, 3, 4, 5, 6a, 7, 7r, 8, 9, Comms Mod Patch Comp, IGE,   still CDT when try to start game
[xml.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1928579/xml.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1928580/Lua.zip)
[xml-perf.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1928582/xml-perf.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1928585/Database.zip)
[Gamecore.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1928586/Gamecore.zip)

**Comment by Infixo** [comment]
Your first error is here:
[108137.687] table Buildings has no column named ExtraMissionaryStrengthGlobal

This is from a core VP file - CoreTableEntries.sql. If it throws an error, it means that your VP install is bad. Very bad.
