### ISSUE TITLE
Cannot become the head of another religion after founding your own

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#4213]
_1. Mod version (i.e Date - 4/23):_
4/11 w/ hotfix — non-EUI

_2. Mod list:_
IGE
Quickturns

_3. Error description:_ 
If you found a religion, but conquer another holy city and replace your religion with that one's, you are still considered the head of your original religion 

_4. Steps to reproduce:_
After founding a religion, capture another holy city and replace your religion with the second holy city's throughout your empire.

---------------------------
Supporting information:
Here, I've capture the holy city for Hinduism and converted all of my cities to that religion, but... 
![](https://i.imgur.com/oAIRb60.png)
I'm still considered the head of Confucianism, and can't benefit from the founder beliefs of Hinduism.
![](https://i.imgur.com/9NLeu4x.png)

**Comment by TechpriestEnginseer** [comment]
Your Original Religion Triumphs any other religion that you captured. Intentional.

**Comment by HalfEmptyMug** [comment]
@TechpriestEnginseer Why is that intentional? And is this the case for the first religion you capture if you haven't personally founded?

**Comment by pandasnail** [comment]
No, for captured religions, its most followers in your entire empire, no matter when conquered.

**Comment by MoiMagnus** [comment]
Priority is:
1) The religion you founded.
2) The religion of a holy city you control
2a) If multiple, priority to enhanced ones
2b) If multiple, priority to the majority one (don't remember if it is number of cities or number of follower)
3) The religion half of your cities are converted to
4) Your pantheon

**Comment by HalfEmptyMug** [comment]
Why should your founded religion have priority over point 2? There are several instances where adopting another would be preferable, such as capturing one founded by Byzantium or The Celts, or in my case, where the captured religion is the majority on the continent and has more suitable beliefs (specifically pacifism to help with my lower happiness and allow me to work more specialists).

**Comment by HalfEmptyMug** [comment]
I assumed that it wouldn't be possible to actively choose a religion via an option, but this is done manually by converting your cities with missionaries and inquisitors.

I'm not suggesting a founded religion be able to be killed, only that if you own multiple holy cities that you have the option to become head of which ever one is your majority, _Which is already the case if you haven't founded_ (so essentially, keeping the priority list, but switching point 1 and point 2).

In terms of AI: as this doesn't happen too often, and the AI seems to handle the acquisition of multiple holy cities just fine now without founding its own, that it's valuation could remain relatively unchanged and prefer whichever is already it's majority (If neither majority, then default to founded, or if none founded, however it already works). The player would technically gain a slight edge, but it would be marginal over what's already possible and more intuitive.

**Comment by MoiMagnus** [comment]
@LoneGazebo An opinion?

**Comment by LoneGazebo** [comment]
it works as intended.
