### ISSUE TITLE
VP 4/20 CTD

### ISSUE THREAD

**Issue by myles1718** [LoneGazebo/Community-Patch-DLL#4215]
_1. Mod version (i.e Date - 4/23):_

VP 4/20
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Fresh install of new version of VP 4/20
Mods load but still CTD when trying to start game
Difficulty
[xml-perf.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1930918/xml-perf.zip)
[xml.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1930920/xml.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1930921/Database.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1930923/Lua.zip)

 level in ING setup will not change from Chieftain 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
The logs are quite similar to #4208.

**Comment by myles1718** [comment]
I know.  Did a complete pc overhaul, down loaded civ 5 again and verified it
Down load VP 4/20 fresh install
Used just VP mods
Started game  CTD
Now playing civ 5 with no VP activated working perfect

**Comment by Infixo** [comment]
The game is clearly trying to load other mods. Never heard of Suburbs or Yagem in VP. Yagem is something from JFD ExCE, btw.
[39607.250] no such table: MinorCiv_YagemStartPosition
[39609.671] In XMLSerializer while inserting row into table insert into Improvements('Type', 'ImprovementUpgrade', 'UpgradeTime') with  values (IMPROVEMENT_FARM, IMPROVEMENT_SUBURB, 100, ).
Plus the same issue with the core files as previously.
