### ISSUE TITLE
Tradition not granting buildings in capital

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#4216]
_1. Mod version (i.e Date - 4/23):_
4/20

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I noticed that Tradition does not give the free buildings correctly now. I think its related to commit 4dd2ee2, because the Tradition policies use the NewCityFreeBuilding column. @Iamblichos you're more familiar with that section of the code. Is it the cause?

_4. Steps to reproduce (optional):_

**Comment by HungryForFood** [comment]
Ideology free buildings also uses the same column, and I remember Hospitals not spawning correctly for Freedom too.

I guess the column got fixed to work as the name suggests. So, a new FreeBuilding column for policies is needed?

**Comment by Iamblichos** [comment]
Yeah I made NewCityFreeBuilding for cities that you are or will found, not existing cities. We have an entry for all cities. Policy_FreeBuilding which uses BuildingClassType.

**Comment by Iamblichos** [comment]
When I originally created NewCityFreeBuilding the intent was the way it is now, somehow it got changed to all existing cities that you own.

**Comment by bigcat88** [comment]
Yes, tested in new game, tradition buildings are missing right now.

**Comment by Iamblichos** [comment]
It's an easy hotfix.

**Comment by Iamblichos** [comment]
Swap these lines:

```
UPDATE Policies
SET NewCityFreeBuilding = 'BUILDINGCLASS_CAPITAL_ENGINEER'
WHERE Type = 'POLICY_ARISTOCRACY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET NewCityFreeBuilding = 'BUILDINGCLASS_PALACE_TREASURY'
WHERE Type = 'POLICY_MONARCHY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET NewCityFreeBuilding = 'BUILDINGCLASS_PALACE_GARDEN'
WHERE Type = 'POLICY_LANDED_ELITE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET NewCityFreeBuilding = 'BUILDINGCLASS_PALACE_COURT_CHAPEL'
WHERE Type = 'POLICY_OLIGARCHY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET NewCityFreeBuilding = 'BUILDINGCLASS_PALACE_ASTROLOGER'
WHERE Type = 'POLICY_LEGALISM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET NewCityFreeBuilding = 'BUILDINGCLASS_PALACE_THRONE_ROOM'
WHERE Type = 'POLICY_TRADITION_FINISHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );
```
With this in Tradition.sql:

```
INSERT INTO Policy_FreeBuilding
			(PolicyType,			BuildingClassType,				Count)
VALUES		('POLICY_ARISTOCRACY',	'BUILDINGCLASS_CAPITAL_ENGINEER',	1),
			('POLICY_MONARCHY',	'BUILDINGCLASS_PALACE_TREASURY',		1),
			('POLICY_LANDED_ELITE',	'BUILDINGCLASS_PALACE_GARDEN',	1),
('POLICY_OLIGARCHY',	'BUILDINGCLASS_PALACE_COURT_CHAPEL',	1),
('POLICY_LEGALISM',	'BUILDINGCLASS_PALACE_ASTROLOGER',	1),
('POLICY_TRADITION_FINISHER',	'BUILDINGCLASS_PALACE_THRONE_ROOM',	1);
```

This will also need to be done for Freedom, Autocracy, and Order. We need to rewrite Policy_FreeBuilding to give an indefinite count instead of a hard value but for Freedom, Autocracy, and Order set the Count to 200 for now, and possibly a Capital Only check for Tradition. This will get your game going before a hotfix is released.

**Comment by Iamblichos** [comment]
Here I made the changes for you so you can just overwrite the existing files in your mods folder. Be sure you put them in the right place.
[Policies.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1932134/Policies.zip)

**Comment by bigcat88** [comment]
@Iamblichos thanks, I already replaced with previous post, tradition works well. Thanks, now I can start a game! GJ!

**Comment by raphaell666** [comment]
Irrelevant question: why are the files named Freedom.sql, Autocracy.sql and  Order**Changes**.sql?  

Does no one else here have at least light OCD? :laughing:

**Comment by Iamblichos** [comment]
Communism gotta meme where communism can meme bruh.
