### ISSUE TITLE
Typo: Buffalo Loins (4/20)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#4218]
`Flank attack bonus increased by 50%.`

should be

`Flank attack bonus increased by 25%.`

![buffalo loins](https://user-images.githubusercontent.com/11933188/39051424-927702b4-44e3-11e8-9fc5-b1bdaaa6c884.png)

cf. (2) Community Balance Overhaul\Balance Changes\Text\en_US\PromotionText.sql
Line: 415
https://github.com/LoneGazebo/Community-Patch-DLL/blob/94e275ba1b3b9792d49f2b34521c230f90be0b1d/Community%20Balance%20Patch/Balance%20Changes/Text/en_US/PromotionText.sql#L414-L416

-----
By the way, could you update **(3) CSD for CBP.zip** and **(4) Civ IV Diplomatic Features.zip** in the Vox Populi **Manual** Install Folder​?

**Comment by TechpriestEnginseer** [comment]
You may commit a pull request to these folders to which we can approve.

**Comment by 8h42** [comment]
@TechpriestEnginseer
I'm not very familiar with Github, unfortunately.

**Comment by Zarrk** [comment]
Actually there are two redundant descriptions for buffalo chest and loins in this file.
