### ISSUE TITLE
Church belief description wrong

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4219]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm hovering over Churches belief, and they don't mention the Culture. The building itself as well as Civilopedia do mention it, however.

**Comment by raphaell666** [comment]
The Church also has a 40% pressure modifier rather than 25% as the description in the Civlopedia states. I think this is just because the description hasn't been updated yet.
