### ISSUE TITLE
Put a semicolon.

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#4220]
UPDATE UnitPromotions
SET Help = 'TXT_KEY_PROMOTION_FASTER_HEAL_HELP'
WHERE Type = 'PROMOTION_FASTER_HEAL'

Forgot the ;

**Comment by Infixo** [comment]
Fortunately it's the last statement in the file :)

**Comment by raphaell666** [comment]
Oops that was actually my mistake here: https://github.com/LoneGazebo/Community-Patch-DLL/issues/4178

Sorry. :smiley:
