### ISSUE TITLE
Venetian Merchant and Unit_ScalingFromOwnedImprovements

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#4223]
Should this unit be getting this for Towns and their own unique Town?

**Comment by LoneGazebo** [comment]
Well they can’t plant towns right? I forget

**Comment by LoneGazebo** [comment]
They only get bonuses for owned improvements that are planted by the player.

**Comment by Iamblichos** [comment]
I forget too. Yeah, the unique town. Should they get the scaling bonus?

**Comment by Iamblichos** [comment]
...and do you want me to go fix Policy_FreeBuildings in the DLL to give a indefinite amount or do you like it giving a definite amount.

**Comment by Iamblichos** [comment]
We'll need another entry in CvPolicies for Capital Check for Tradition though, otherwise every tradition city will get those capital buildings...FYI.

**Comment by LoneGazebo** [comment]
@Iamblichos that already exists.

**Comment by Iamblichos** [comment]
Yep I saw the check in CvBuildingClasses.cpp.

So I decided I'm going to leave Policy_FreeBuildings alone....some modder might be using it and/or they only want a limited amount of buildings vis. vanilla tradition with the culture and food buildings. I made a new entry which requires a new variable in CvPlayer....so that breaks save game compatibility. I think it's best for now we just go with using Policy_FreeBuildings for the hotfix as I suggested in the other thread and then on next release we can implement what I have done.

**Comment by LoneGazebo** [comment]
that's the plan for the hotfix. 

In the future, it'd be a good idea for all of us to make an issue post letting others know if they change a pre-existing mechanic's functionality, hard to keep track when we're all making edits.

Also you're a collaborator now, so you can merge stuff on your own. Cheers.

**Comment by Iamblichos** [comment]
Sorry about that, I thought I was the only one using NewCityFreeBuilding in modding....I thought you were using Policy_FreeBuilding for Tradition.

**Comment by LoneGazebo** [comment]
No worries! Not the first time it's happened, and I've done it to other people. :)

G

**Comment by Iamblichos** [comment]
I can't either but...I guess for consistency.

**Comment by Iamblichos** [comment]
Done. Closed.
