### ISSUE TITLE
Tradition capital buildings not showing up

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#4226]
4/20

Picked Sovereignty, no chapel/artist slot/whatever. Reloaded, tried with Justice, no unique building either. Gave up before further testing.

**Comment by raphaell666** [comment]
For convenience the fix mentioned is here, scroll down a little bit to the last @Iamblichos posts: https://github.com/LoneGazebo/Community-Patch-DLL/issues/4216
