### ISSUE TITLE
TradeLogic.lua

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#4227]
Change line 599 from:

`if (player:IsEverAlive() or player:IsPotentiallyAlive()) then`

to:

`if (pLoopPlayer:IsEverAlive() or pLoopPlayer:IsPotentiallyAlive()) then`

**Comment by Iamblichos** [comment]
Look in the (6c) 43 Civs CP, not sure about the non-43.

**Comment by Infixo** [comment]
@LoneGazebo Seems like an issue with installer, similar to #4165 
I checked EUI compatibility files and GitHub has a correct version, but (6a) component has an incorrect line Wrong variable name, just like @Iamblichos posted, in line 512.

**Comment by Infixo** [comment]
43-Civ EUI has a correct variable in GitHub. So, again probably installer was not updated (?)

**Comment by Iamblichos** [comment]
It's not line 512 in (6c) 43 Civs CP, it's line 599.

**Comment by Infixo** [comment]
599 for (6c), 512 for (6a). 43-civ code has some additional lines that support more leader icons.

**Comment by Infixo** [comment]
I can confirm that (6a) has the correct version in 4-20-4 release.
`if (pLoopPlayer:IsEverAlive() or pLoopPlayer:IsPotentiallyAlive()) then`

**Comment by Iamblichos** [comment]
So it's just 6c. easy peasy.

**Comment by LoneGazebo** [comment]
blegh, sounds like I just missed a 6c change. I'll update.
