### ISSUE TITLE
Recently liberated -100000 modificator when asking for tribute between turns 31 and 51

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#4228]
_1. Mod version (i.e Date - 4/23):_

With current version and hotfix I'm encountering this appearing in several test games in turn 31 and ending always in 51.
It's a undocumented change, a bug or some problem with another mod that it's interacting with City States as UCS?

**Comment by LoneGazebo** [comment]
more info?

**Comment by Mitchsp** [comment]
Don't think about any other detail that can be relevant or haven't detected other pattern that previously indicated, but I'll try to detail more.

Can try ask for tribute normally before turn 31. In tooltip appear normal modificators and can do successfully, but reaching turn 31 "Recently liberated" -100000 modificator is added to all City States imposibiliting tribute.
This last until turn 51 when disappear, happening the same in the same turns in several games.

**Comment by LoneGazebo** [comment]
I see why, silly me.

**Comment by LoneGazebo** [comment]
I'll fix for a release soonish.

**Comment by Mitchsp** [comment]
Thanks, I was further testing after clearing cache and removing mods triying to find any clue.

**Comment by LoneGazebo** [comment]
I didn’t touch it yet.
