### ISSUE TITLE
No antiquity sites

### ISSUE THREAD

**Issue by obsidiantower1** [LoneGazebo/Community-Patch-DLL#4229]
_1. Mod version (i.e Date - 4/23):_ 4/1/18 (homemade modpack with no other mods) 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Upon discovering Archeology, zero antiquity sites are spawned, while many hidden antiquity sites are created (52 on a large 10 civ Terra map)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[Uploading Antiquitybug.zip…]()

4. Screenshots (optional):

**Comment by Iamblichos** [comment]
This is due to the Custommodoptions entry not being entered.

**Comment by obsidiantower1** [comment]
Is that something I did, and is it something I can fix?

**Comment by Iamblichos** [comment]
Nah you didn’t do anything wrong. Get the latest hot fix in the forum.

**Comment by obsidiantower1** [comment]
I tried but the game failed to load. The patch notes from the 4/20 version say it's not backwards compatible and, in this game is on the 3/30 version. But I didn't make a Modpack this time, I tried to activate the newest hotfix from the mods menu, and then when I went to load the save game it hung up on a "setting up game data please wait" screen

**Comment by Iamblichos** [comment]
Ah dang. Well yeah, you’d have to start a new game with the new version.

**Comment by Infixo** [comment]
You need to add 1 line to custommodoptions.xml
Look in #4221
