### ISSUE TITLE
Unoptimized production focus

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#423]
![2015-07-17_00001](https://cloud.githubusercontent.com/assets/11132095/8745043/76daee34-2c41-11e5-9aa4-e74f29209b0a.jpg)

It makes sense to have cities grow early on, but production focus should provide the most hammers possible without starving. In this case the city would actually still grow if a hill was worked, yet it doesn't get worked.

**Comment by LoneGazebo** [comment]
The value of food goes down as the need versus production difference diminishes. Early on food is therefore quite valuable. At size two, it should be trying to grow AND produce, which is what is happening here (otherwise the AI will invariably screw itself with small cities).

**Comment by joosegoose** [comment]
But, it could still grow AND produce by working a hill. It wouldn't grow as quickly (or be as optimal overall in the long term) but it would still grow.

Does the AI use production focus all that often? I'm only concerned with production focus, as there's now no way to rush wonders outside of manually locking tiles. For default or other focuses it makes perfect sense to put extra priority on early growth, but production focus seems pointless if it doesn't actually maximize production.

**Comment by LoneGazebo** [comment]
It does, yes, though generally only when at war, building a wonder, or rushing a settler.
Like I said, though, a size two city isn't a fair model, as the AI has to grow to at least size 10 before it'll even consider a specialization.
G

**Comment by joosegoose** [comment]
Does that imply that the AI won't even consider a specialization focus at such a low population?

If so, then my understanding is that an example like this at low populations only affects humans and it would be nice to "fix" the logic for low-population specializations.

**Comment by LoneGazebo** [comment]
Correct, though the logic is still passed through by the AI (city citizen logic uses multipliers that are weighted by specializations, which are an entirely separate AI). 

G

**Comment by joosegoose** [comment]
So, to try and simplify as much as possible (only way I will probably understand ;) ), production focus needs to be handled the way it currently is (i.e. growth favored at low pop) or else it can hamper AI in other aspects of city management?

Also, related:
![2015-07-19_00002](https://cloud.githubusercontent.com/assets/11132095/8768156/6464a974-2e3b-11e5-9570-5b7eedd7c98f.jpg)

I see no reason for 2 food to be favored over 3 food. This seems more like a true "bug."

**Comment by LoneGazebo** [comment]
Yes. Like I said, the 'problem' here resolves itself as the city reaches larger sizes, so the diminished efficiency diminishes quickly.

G

**Comment by joosegoose** [comment]
Got it. I always manually lock tiles anyways so I'll forget about it now, just making sure it wasn't something that needed improvement.

**Comment by LoneGazebo** [comment]
Yep. It's one of those rare situations where AI needs directly affect the player's control. Not ideal.
G
