### ISSUE TITLE
implausible unhappiness and other observations

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4230]
so this is the 4/20 version. the songhai have eaten up assyria and greece, then fell into a hole and are about to lose to china even though they have twice as many cities as them.

anyway. the happiness breakdown says:

![image](https://user-images.githubusercontent.com/1358966/39083447-13926246-4564-11e8-93aa-3e830d002e43.png)

0.93 seems implausible. 93 might be a bit high either though? i count about 180 pop in puppet cities.

![image](https://user-images.githubusercontent.com/1358966/39083512-3efa5faa-4565-11e8-8187-778462dbe824.png)

further observations:
- they didn't annex one conquered city
- they have been in negative gpt / happiness for more than 100 turns
- apparently they continued constructing buildings in spite of their economic problems
- in particular they are choosing growth buildings in cities avoiding growth
- should puppets use gold focus if the situation demands it?
- should puppets use avoid growth if the situation demands it?
- why haven't there been a bunch of revolts?

![image](https://user-images.githubusercontent.com/1358966/39083518-6ad5c038-4565-11e8-89a9-8eb6e1e64c1f.png)

![image](https://user-images.githubusercontent.com/1358966/39083522-745d4cde-4565-11e8-90de-90022c31b74e.png)

![image](https://user-images.githubusercontent.com/1358966/39083569-3cc9673e-4566-11e8-8173-d692f3a3f4e6.png)

finally, the puppet yields don't add up?

![image](https://user-images.githubusercontent.com/1358966/39083605-00266b14-4567-11e8-8c86-a9c5cc5c16de.png)

according to my math, the base yield should be 89.5 and -75% should give a final yield of 22.38 ... apparently the yield from the research process is added only after modifiers. but even then, the result should be 32,13?

**Comment by LoneGazebo** [comment]
Looks like I need to multiply the UI unhappiness by 100.

**Comment by LoneGazebo** [comment]
Re everything else, good questions. I’ll look. Not sure about lack of revolts.

**Comment by LoneGazebo** [comment]
they didn't annex one conquered city
>that's a bug, I know why
apparently they continued constructing buildings in spite of their economic problems
>its the only way to get out of the happiness hole, though
in particular they are choosing growth buildings in cities avoiding growth
>that's odd - possible that they reduced poverty too?
should puppets use gold focus if the situation demands it?
>puppets aren't allowed to use processes I believe
should puppets use avoid growth if the situation demands it?
>also a reason to annex
why haven't there been a bunch of revolts?
>there should be - cityrevolutions.csv log empty?

**Comment by Iamblichos** [comment]
I've seen puppets, in previous version, use a process like gold.

**Comment by LoneGazebo** [comment]
That sounds right. They may just need a bump in priority, then.

**Comment by ilteroi** [comment]
processes are one thing but governor focus is another.

logs are gone unfortunately.

in the taghaza example they were constructing an agribusiness, so pure growth.

**Comment by Iamblichos** [comment]
Ah I see what you mean now.

**Comment by LoneGazebo** [comment]
@ilteroi yeah that's a bad call, I'll add an explicit penalty to yield food value if the city is locked to not grow (there isn't one currently).
