### ISSUE TITLE
puppet unhappiness vs annexation unhappiness

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4231]
does it make sense that unhappiness after annexation is worse than before?

currently you get pop/4 from puppets while you get pop/2 + other sources from annexation.

**Comment by LoneGazebo** [comment]
Well annexation is temporary until courthouses are made.

**Comment by ilteroi** [comment]
i know but it seems illogical that they would be more unhappy after finally becoming a full member of my great empire

**Comment by LoneGazebo** [comment]
only until you build a courthouse, though! :)

**Comment by LoneGazebo** [comment]
otherwise they're under the terrible Martial Law of Ilteroi the Scourge.
