### ISSUE TITLE
City Management Bad AI

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4232]
_1. Mod version (i.e Date - 4/23):_4-20 hotfix

_2. Mod list (if using Vox Populi only, leave blank):_FlagPromotions

_3. Error description:_ 

"Default focus" city management AI chooses certain poor tiles (circled red) over the much nicer tiles (circled blue). Apparently a bug in AI logic.

Savegame attached

![inked20180421143500_1_li](https://user-images.githubusercontent.com/16341598/39085656-8eb8b572-458e-11e8-8144-8297856d0f11.jpg)
 

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1934443/QuickSave.zip)

**Comment by LoneGazebo** [comment]
Did you recently have enemy units blockading tiles?

**Comment by saamohod** [comment]
IIRC I haven't been warring for a while neither any barbarians showed up in the vicinity.

**Comment by deadstarre** [comment]
city is about to grow, was it the same after getting to 8pop?

**Comment by saamohod** [comment]
Not exactly

![inked20180421190528_1_li](https://user-images.githubusercontent.com/16341598/39086225-32e0f36e-4597-11e8-813a-f77abc15dda6.jpg)

**Comment by saamohod** [comment]
Another case from the same game. When on "Food Focus" it does the following:

![inked20180421192552_1_li](https://user-images.githubusercontent.com/16341598/39086441-0462d2fc-459a-11e8-87d7-29583485c6af.jpg)


![inked20180421193112_1_li](https://user-images.githubusercontent.com/16341598/39086486-c44f9a5a-459a-11e8-87ed-6a0484ec94ad.jpg)

savegame:
[wrong food focus.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1934780/wrong.food.focus.zip)

**Comment by LoneGazebo** [comment]
Weird, I'm not seeing this at all. I'll look at the save, any other mods? If so, zip it and stick it here as well.

**Comment by saamohod** [comment]
These are the mods, all of which should be harmless and irrelevant and save-compatible.

![20180422013914_1](https://user-images.githubusercontent.com/16341598/39089369-4a09c854-45ce-11e8-872b-97a6ee3e60ad.jpg)

**Comment by ryanmusante** [comment]
@saamohod Question unrelated to topic, is the "Colored Religions" mod fully compatible with VP per Toft? I can't get any response from him since he left Civfanatics forums.

**Comment by LoneGazebo** [comment]
really wants culture for border growth? That's my guess.

**Comment by raphaell666** [comment]
>really wants culture for border growth? That's my guess.

But shouldn't the default focus value 6F+1P+2G more than 2F+4P?

**Comment by LoneGazebo** [comment]
same would apply for culture, especially since the city is close to finishing the harbor.

**Comment by raphaell666** [comment]
And border growth is still 59 turns away, even working those two culture tiles. It would have to be an insanely good tile to outweigh 59 turns working those two weak culture tiles.

**Comment by ilteroi** [comment]
6f1p beats 1c in almost any situation. that city has stagnated at pop 3 for a long time. this cannot be right.

**Comment by LoneGazebo** [comment]
Not saying it’s right, just saying that’s probably why it is doing that. Is your CP up to date? I altered the value defines quite a bit recently.

**Comment by LoneGazebo** [comment]
CP mod, not DLL*

**Comment by saamohod** [comment]
>Not saying it’s right, just saying that’s probably why it is doing that. Is your CP up to date? I altered the value defines quite a bit recently.

The question is apparently not addressed to me, but I'd like to note that the bug is from a previous version( 4-20 IIRC). I haven't tested the latest fix on this matter.

**Comment by ilteroi** [comment]
well it's kinda hard to say, i think i'm on 4-20-2

**Comment by LoneGazebo** [comment]
@ilteroi just make sure your CP defines files are up to date- if they aren’t, the food will be valued way too low because I changed the food value scaler quite a bit.
