### ISSUE TITLE
Borbudur description error(or bug)

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4238]
_1. Mod version (i.e Date - 4/23):_
20 April

_2. Mod list (if using Vox Populi only, leave blank):_
Naval Warfare

_3. Error description:_ 
Descriptions says: "and all Missionaries gain 1 additional Rel Spread"
In my game missionaries from Capital where Borbodur have 3 spreads, but when I buy missionaries in another city they are usual with 2 spreads.
Maybe it is just a description error.

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
Oh it should say 'in the city.'
