### ISSUE TITLE
A star means "A star"

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4239]
_1. Mod version (i.e Date - 4/23):_latest hotfix

_2. Mod list (if using Vox Populi only, leave blank):_ FlagPromotions

_3. Error description:_ 

A minor glitch but the glitch nonetheless. When hovering over a star sign in the city bar, in case the city used to be a capital of a civilization I never met, it just shows another star in the tooltip.

![inked20180421191223_1_li](https://user-images.githubusercontent.com/16341598/39086333-8a613332-4598-11e8-9b20-a4bce7833afb.jpg)

**Comment by ilteroi** [comment]
ha. i was worried for a second that you might have found a pathfinder bug :)

**Comment by LoneGazebo** [comment]
@ilteroi me too!!

@saamohod it's always been that way.
