### ISSUE TITLE
"Promised not to spy"

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4240]
_1. Mod version (i.e Date - 4/23):_latest hotfix

_2. Mod list (if using Vox Populi only, leave blank):_FlagPromotions

_3. Error description:_ 

The tooltip on other civs reads like I promised not to spy on them, but seemingly it was them who promised not to spy on me. More discussion here https://forums.civfanatics.com/threads/promised-not-to-spy.631615/

Savegame attached

[Saam_0225 AD-1575.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1934774/Saam_0225.AD-1575.zip)

**Comment by LoneGazebo** [comment]
@Infixo worked on this recently.

**Comment by Infixo** [comment]
Seems that only NoSpying is working the opposite way. I've checked again and all others are fine.

**Comment by Infixo** [comment]
The issue with spying is that there are 2 situations in the game:
a) human asks an AI to stop spying - this is referred as StopSpyingRequest in the code
b) an AI caught / killed our spy and asks us to stop spying - this is referred as BrokenSpyPromise or IgnoredSpyPromise
The counter is only used in a) and not for a human - it is used by AI to asses type of an answer. The situation b) doesn't have a counter - once you give a promise, it seems to be indefinite.
