### ISSUE TITLE
"Fortify" when "Do nothing" is pressed

### ISSUE THREAD

**Issue by rustyshackle** [LoneGazebo/Community-Patch-DLL#4244]
1. Mod version: 

4/20

2. Mod list:

3. Error description:

In the original BNW, when a unit is issued the order "Do nothing" (spacebar hotkey), it does not automatically fortify. Naturally, such behaviour is unexpected and annoying, since why should a unit not receive a defensive bonus when it can (had "Fortify" or "Alert" been pressed)? I am not sure if this issue has been fixed in VP, and my apologies for bringing this up if it has been fixed.

It would be great if a unit issued the "Do nothing" command would fortify (receive 20% defensive bonus), but the unit would still remain in auto-cycle the next turn. Then, if it has fortified with "Do nothing" the previous turn, it does not move the next turn, and "Do nothing" is issued again, the full 40% defensive bonus would be applied.

What seems to be even worse is that "Alert" could potentially be used as a partial substitute to my proposed behaviour (at least auto-cycle works with enemies nearby), but, for ~~idiotic~~ mysterious reasons, "Alert" is capped at 20% defensive bonus, so even two turns of "Alert" won't yield 40%.

The system was perfect in Civilization IV and now it's just a mess, only being able to fortify properly by putting the unit to sleep and inevitably forgetting about its existence.

**Comment by ilteroi** [comment]
could even make it so that combat units can build forts and not workers. forts which are entered by enemy units are removed, just like barbarian camps, end the enemy unit ends its turn. just spitballing.

**Comment by Iamblichos** [comment]
Nice!

**Comment by rustyshackle** [comment]
What seems to be even worse is that "Alert" could potentially be used as a substitute to my proposed behaviour (at least auto-cycle works with enemies nearby), but the unfortunate thing is that apparently when the unit in "Alert" state gets alerted and woken up, it loses all fortification bonuses :laughing:

**Comment by Iamblichos** [comment]
Here’s another spitball idea. Make it only for non mounted/armor units can build forts. mounted and armor have something in their promotion tree for attacking fortified units.

**Comment by Infixo** [comment]
I always imagined Fortify as soldiers building trenches, not actual Fort or any other significant construction.

**Comment by rustyshackle** [comment]
I don't think there's any need to reinvent the wheel with forts and what not. I find the current system is good, just that Firaxis made it terribly difficult to use the system. If technical limitations do not allow to make "Do nothing" work as it should, even changing the "Alert" defensive cap from the current 20% to 40% would be a huge improvement on the ease of use front.

**Comment by deadstarre** [comment]
in my experience the only AI who can make meaningful use of the Fortify mechanic is a barbarian in an  encampment... so please feel free to re-invent the wheel lol. Now if forts followed the same spacing requirements as city placement, and didn't replace features or other improvements... now we're talking! =)

**Comment by ilteroi** [comment]
well that's maybe a question for the forum.

removing the fortification bonus is easy. in fact the whole mission is redundant then. alert is enough.

the rest (combat units building forts etc) is unfortunately a lot of effort, especially concerning the AI. i'm not too keen on it.

**Comment by Albertolona** [comment]
Infixo is right.

Fortify represents troops digging in. 

I would hate to see this removed.

**Comment by ilteroi** [comment]
you missed about 100 messages on the forum ... no worries!
