### ISSUE TITLE
"Route to" not working

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4250]
_1. Mod version (i.e Date - 4/23):_ 4-20 hotfix

_2. Mod list (if using Vox Populi only, leave blank):_FlagPromotions

_3. Error description:_ 
 **Sometimes** workers refuse to build route to a tile when commanded with the button "Route To Mode".
In my case there is a worker west of Kukia city who doesn't want to build road to the desert tile where the canon is stationed.

Savegame attached

[route to not working.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1934835/route.to.not.working.zip)
 

![20180421205510_1](https://user-images.githubusercontent.com/16341598/39087249-fbd2119a-45a6-11e8-8b29-7fdcb309e0d5.jpg)

**Comment by ilteroi** [comment]
can't reproduce. in my own game.

are you by chance at war with songhai?

**Comment by saamohod** [comment]
Nope
