### ISSUE TITLE
Unidentified CS mission

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4251]
_1. Mod version (i.e Date - 4/23):_ 4-20 hotfix

_2. Mod list (if using Vox Populi only, leave blank):_FlagPromotions

_3. Error description:_ 

One of the apparently newest CS missions has no explanation. See the screenshot.

![20180421212443_1](https://user-images.githubusercontent.com/16341598/39087502-aa34c428-45aa-11e8-9308-6ba45e7ba456.jpg)

[unknown CS mission.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1934858/unknown.CS.mission.zip)

**Comment by LoneGazebo** [comment]
@saamohod if you have logging enabled post your lua.log. That's the religious quest, but it was working on my end last test.

**Comment by bigcat88** [comment]
The same. CS Cahokia
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1936228/Lua.zip)

**Comment by LoneGazebo** [comment]
Thanks will investigate.
