### ISSUE TITLE
Problem with new influence decay calculation under and over 100 threshold - All CS have same personality

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#4253]
_1. Mod version (i.e Date - 4/23):_
4/20 - 3

Wrong too with influence < 100, for example with 93 influence decay is 1,93

![imagen](https://user-images.githubusercontent.com/13163824/39090804-aa7c0eee-45e8-11e8-9054-106716be8e49.png)

**Comment by LoneGazebo** [comment]
there's no 'threshold' now - it's a linear decay equal to 1% of your total.

**Comment by Mitchsp** [comment]
Yes, I remember this being talked and the @tu-79 proposal, but the problem is the implementation. Actually isn't 1% but 1 + 1%, that diminish drastically value of early diplomatics units during early game being so difficult and costly to maintain alliances now.

Another change is that now all City States have Neutral personality.

After trying actual values, I think, don't would be better maintain the old decay of -1 for influence < 100 and 1% for values above? and if the change to personality isn't intended one proposal is to add a little variation, with Friendly City States reducing this by 10%, Hostiles increasing 20% and Irrational a random modificator between previously values, determined either each turn or a constant value at the start of the game.

Btw this change is missed from patchnotes.

**Comment by LoneGazebo** [comment]
I’ll look at the formula. 

All city states are neutral? That’s weird. Coincidence?

**Comment by Mitchsp** [comment]
Not a coincidence, tested two times without others mods except IGE and all were Neutral.

**Comment by Mitchsp** [comment]
Happening to others guys with all Friendly or Hostile

https://forums.civfanatics.com/threads/new-version-april-20th-4-20.631575/page-6#post-15107929

**Comment by tu-79** [comment]
When I suggested 1 + 1%, I thought it was rounded down to integeers. If it is going to be a number with two decimals, it could be changed to 0.5 + 1%, so it rounds to 1 when influence is 50. Not that there is anything wrong with the first value, but the second would give numbers closer to what we are used to.

**Comment by raphaell666** [comment]
I might be misunderstanding but what is the issue of it being exactly a percentage rather than a number + percentage? E.g. with 1% if the influence is -50, it increases by 0.5 per turn. If the influence is +50, it decreases by 0.5 per turn. Otherwise could we increase it to 2%, with e.g. influence at -50 increasing by 1 per turn?

Does this make sense?

**Comment by Mitchsp** [comment]
Yes, 0,5 + 1% could be a fine middle point without altering drastically cost/influence/value obtained of early emmisaries.

**Comment by raphaell666** [comment]
Idea: there is also the possibility of using setprecision(1) so that it rounds the number to one decimal place, isn't there? Not sure if two decimals are necessary and not just adding clutter to the number.

**Comment by deadstarre** [comment]
surely theres a mathematical way to express 1 + 1% of any influence _over_ 100?

**Comment by deadstarre** [comment]
what MoiMagnus said I believe, this is what I thought was the goal for what we'd be getting when the change was made. seems to make the most sense, avoids the "infinite" conundrum of using a purely % based approach while basically being just that, and maintaining the status quo.

**Comment by Mitchsp** [comment]
With 4-20-5 isn't working that way G. Is 1 decay under 100 and 1+1% above 100.

**Comment by LoneGazebo** [comment]
Hmm. I’ll look I wonder if my fix didn’t merge through.

**Comment by LoneGazebo** [comment]
```
//Influence decay increases the higher your influence over 100;
		if (MOD_DIPLOMACY_CITYSTATES_QUESTS &&  iBaseFriendship > 100)
		{
			float iInfluenceTotal = GetBaseFriendshipWithMajorTimes100(ePlayer) * .01f;

			if (iInfluenceTotal != 0)
				iChangeThisTurn += (int)iInfluenceTotal*-1;
		}
```

Current system. 
Am I crazy or is this not what we wanted?

**Comment by deadstarre** [comment]
Mitchsp example above of 104 influence should translate to 1.04 decay, i believe thats what we wanted.

**Comment by LoneGazebo** [comment]
Mm, I see, then I need to make the value .001, not .01, for the model.

**Comment by tu-79** [comment]
"iChangeThisTurn += (int)iInfluenceTotal*-1;"
Can this be done without parenthesis? I mean *-. I thought those operators cannot be expressed together.

Wouldn't it be more simple just
iChangeThisTurn -= (int)iInfluenceTotal; ?

Also.
GetBaseFriendshipWithMajorTimes100(ePlayer) is 100 times base friendship with majors? Or what? If it is 100 times influence, a 1% would be 10000 times lower. What is that 'f' at the end of the number? Saying that this number is a float? I can't find it in any lua guide.

**Comment by LoneGazebo** [comment]
f= float yeah.
