### ISSUE TITLE
Can't build Train Station

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4260]
_1. Mod version (i.e Date - 4/23):_4-20 hotfix

_2. Mod list (if using Vox Populi only, leave blank):_FlagPromotions

_3. Error description:_ 
I don't have a build option for a Train Station in my capital. Railroad tech is discovered long ago, I have coal, my capital is not coastal and therefore doesn't have a Seaport. A bug?

[NoTrains.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1935522/NoTrains.zip)

![20180422143558_1](https://user-images.githubusercontent.com/16341598/39094619-fcc07242-463a-11e8-956f-1310c9b9af32.jpg)

**Comment by bigcat88** [comment]
Maybe you need a railroad? Where is railroad from capital?

**Comment by saamohod** [comment]
>Maybe you need a railroad? Where is railroad from capital?

As soon as I discover Railroad Tech a railroad tile appears underneath each of my cities (according to the tooltip). AFAIK I only need railroad to the capital from a city in order to build Train Station in that city .
