### ISSUE TITLE
"You promised not to spy on them" when you ask them not to spy on you

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4261]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So ENGLAND is on my continent. She spied on me, I asked her not to do it, she consented. Then I look at the relations between our two peoples, and in gray it says I promised not to spy on them for XX turns. It's what she has done, not me, I cannot spy.

**Comment by LoneGazebo** [comment]
@infixo sounds like a backward check?

**Comment by Infixo** [comment]
Same as #4240
