### ISSUE TITLE
[Suggestion] Voyage of Discovery delay

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4265]
Would it be nicer if the Voyage of Discovery (expending a Great Admiral) didn't give a luxury immediately but after ~5 turns (or so), same as when a military unit is gifted to a CS? The reason behind this is obvious: the admiral needs some time to perform the voyage to the exotic countries, he hasn't got luxuries in his ship's hold right away.

**Comment by LoneGazebo** [comment]
time is an abstraction, though, and that's a weird amount of micromanagement.

**Comment by ryanmusante** [comment]
@saamohod Expending great persons is supposed to give instant yields. It would actually go against the norm to impose a time limit.

**Comment by raphaell666** [comment]
Considering that one turn is equivalent to the span of hundreds of years in the game, I do not think increasing the number of turns before gaining luxuries is necessary at all.

**Comment by LoneGazebo** [comment]
Agreed.
