### ISSUE TITLE
Former AI cities and religion, no way to ask to stop conversion

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4267]
_1. Mod version (i.e Date - 4/23):_
current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I've conquered Carthage's city. I inquisitored it (it was falling to my overwhelming pressure anyway), but Dido keeps on sending Missionaries trying to convert it. I have no option when talking to her to ask her to stop. I've seen no option in other games I've had, too, but only in certain cases, so I assume one cannot ask for a stop to conversion of their city if it used to belong to the converter previously. Concerning the bug, I wonder if in case I own a city that used to belong, let's say, Ahmad (who still is a founder) and Boudicca (founder) sends her missionary there, will  I get the option to ask her to stop the conversion, will Ahmad, or will no one?

[casimir.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1936216/casimir.zip) saves if needed, hope I got the right files so I got two. Click next turn, a missionary or two will probably appear and do no good.

**Comment by LoneGazebo** [comment]
I’ll look - I haven’t actually checked the code for that in some time. I may just make it  a default option.

**Comment by Enrico-Swagolo** [comment]
Weird, she tried to convert the city north of that city which I founded, and I still didn't get the option to ask her to stop. Some games I get it, s ome I don't.
