### ISSUE TITLE
Constant crash after turn 300+. Pangea, epic speed, deity, standard size.

### ISSUE THREAD

**Issue by RedHotTomato2** [LoneGazebo/Community-Patch-DLL#4268]
1.  Version 4/30

2. - 

3. Constant crash. Cant load save game

_4. Steps to reproduce (optional):_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1936550/CvMiniDump.zip)

[AutoSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1936544/AutoSave.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Infixo** [comment]
Cannot load any of the saves.
Each time CTD when reading using ReadHashedDataArray(), but each time in a different place. For RedHotTomato2 in CvTeam.cpp, for bigcat88 in CvGame.cpp.

**Comment by bigcat88** [comment]
@Infixo can you load my first save with name "Askia_0298 AD-1390.Civ5Save"? I tested it right now, and I am able to load, if you cant that it is strange. It is save before first city revolt as I remember.

**Comment by Infixo** [comment]
@bigcat88 Well, I cannot. What else can I say? 
We won't know for sure if revolts are an issue until we actually find the bug. Civ save file is a binary file, 1 wrong number and all goes to hell.

**Comment by LoneGazebo** [comment]
I have games saving and loading after a revolt without issue. What’s your theory @infixo?

**Comment by Infixo** [comment]
See #4247

**Comment by Infixo** [comment]
I have games saving and loading after a revolt without issue.

Hm. I think there are 2 paths, one is when the city becomes a City-State, and one when a city joins somebody (via ideology?) In the latter case the error should not happen because no new team is created.
