### ISSUE TITLE
Misleading worker improvements building times

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#427]
![8930_2015-07-18_00006](https://cloud.githubusercontent.com/assets/1131228/8760702/7d0bd50c-2d45-11e5-9dd5-e0f8906dc70c.png)
![8930_2015-07-18_00007](https://cloud.githubusercontent.com/assets/1131228/8760703/8267af44-2d45-11e5-91d0-ab05965a6ad4.png)
![8930_2015-07-18_00008](https://cloud.githubusercontent.com/assets/1131228/8760704/869383c2-2d45-11e5-8ebf-a71e4663bede.png)
Turns out 13 turns is the right amount.
I have both pyramids and Civil Engineers, so the bug with improving may also be at work.

**Comment by LoneGazebo** [comment]
That code is untouched in the CP/CBP, so it must simply be an issue with EUI.

G
