### ISSUE TITLE
GameEvents.GetCityStateToSpawn() Request

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#4270]
Would it be possible to get a GameEvent to control what City-State is spawned from the Game.DoSpawnFreeCity(pCity) function; something like a **GameEvents.GetCityStateToSpawn()**? It currently appears to take the first (available) City-State in the order it appears in the database, so, for vanilla, Bratislava (at index 0), then Budapest (at index 1), etc. 

Tying the City-State created to the civ (or to it's culture with my mods) with a Lua hook would help with immersion, here. Though, given it's hard to control that City-States spawn at game start, I entirely see that this might not be possible; so no worries if that's the case.

Also, if there is not already, a method to tell if a city-state was spawned as a free city would be great. Something like **pPlayer:IsFreeCity()** .

**Comment by LoneGazebo** [comment]
The free city thing is possible if you check for the player: IsPotentiallyAlive status. 

For city spawning, the table of possible CSs is set in pre-game. I don’t know if lua hooks can access pre-game; if they can, I can add the check there.

**Comment by JFDaly** [comment]
Does IsPotentiallyAlive() return true for anything else other than free cities?

Some can access Pre-Game, like those setting nicknames (PreGame.SetCivilizationDescription, and the like). It'd be great if it's possible, but otherwise no worries. 

Thanks.

**Comment by LoneGazebo** [comment]
Potentially Alive is only for CSs spawned or able to be spawned as a free city.

**Comment by JFDaly** [comment]
Excellent.

**Comment by LoneGazebo** [comment]
@JFDaly uploading a debug DLL here, with a lua hook in pregame
FreeCitySelector(playerID, eMinorCivType)

This is called in pre-game when the eMinorCivType is selected for a playerID - so you can use this (hopefully) as you wanted to set specific slots to be specific CSs.

Just drop this into the latest CP:

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1948685/CvGameCore_Expansion2.zip)

**Comment by JFDaly** [comment]
Thanks. I'll give it a go when I can and let you know how it goes.
