### ISSUE TITLE
Blockade not applying?

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4272]
_1. Mod version (i.e Date - 4/23):_
current 
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Take a pee at Hippo Regius, in spite of 80 trillion units around it blockade applies not. Even putting an unit inside of that 1 tile water it has doesn't make it a blockade, probably because you can only put a regular landed embarked unit there, never a ship.
[hipporeCasimir III_0297 AD-1385.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1938221/hipporeCasimir.III_0297.AD-1385.zip)

**Comment by bigcat88** [comment]
Putting there a helicopter or a updated explorer will block it.

**Comment by supermerill** [comment]
> The Great Lake of Supply

https://en.wikipedia.org/wiki/Siege_of_Leningrad#Supplying_the_defenders

**Comment by ilteroi** [comment]
yes, we could exclude lakes. but i think it's fine as it is
