### ISSUE TITLE
Civpedia for Great Scientist

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4275]
It seems the VP Civpedia entry for Great Diplomat has vanilla description

![20180423011345_1](https://user-images.githubusercontent.com/16341598/39131859-24aeda26-4719-11e8-9e1f-a5b9428ad078.jpg)

**Comment by supermerill** [comment]
Did you mean the VP Civpedia entry for Great Diplomat has (vanilla) Great Scientist description?

**Comment by saamohod** [comment]
>Did you mean the VP Civpedia entry for Great Diplomat has (vanilla) Great Scientist description?

Pardon, I meant Great Scientist.

**Comment by Infixo** [comment]
@saamohod Maybe you can propose a new text?

**Comment by saamohod** [comment]
@Infixo 
Sure I could. But I'd rather leave it for a person who speaks English as a first language (or at the same proficiency) :P 
I somehow feel that my text will be lacking in some way or the other.

**Comment by tu-79** [comment]
Replace with this:

"The Great Scientist can construct the special Academy improvement, which produces lots of science. Further, Scientist's Discover ability is worth ten turns (??) of global (or player's) science, increased by 10% for every constructed Academy. The Great Scientist is expended when used in any of these ways."

**Comment by saamohod** [comment]
Great Scientist civpedia entry still mentions Golden Age.
