### ISSUE TITLE
Duplicated Pantheon

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4276]
_1. Mod version (i.e Date - 4/23):_ 4-20-4

_2. Mod list (if using Vox Populi only, leave blank):_ FlagPromotions 

_3. Error description:_ 

It seems some AI Civs are allowed to pick up a pantheon belief if it had already been taken by another Civ. (God-King in my case)

![20180423180226_1](https://user-images.githubusercontent.com/16341598/39135327-57d3ba68-4721-11e8-994c-572449dfe2a3.jpg)

[Doubled pantheon.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1938842/Doubled.pantheon.zip)

**Comment by Enrico-Swagolo** [comment]
Not a bug, Byzantium can take all religion-related stuff regardless if somebody took it. They make it impossible for others to ape them, but they can follow into others' footsteps.

**Comment by saamohod** [comment]
@Enrico-Swagolo  Oh, I should've guessed it. Thanks.
