### ISSUE TITLE
Feature Request - Free Building from Belief table

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4277]
Would it be possible to create a table for beliefs identical to the Policy_FreeBuilding table?

This would allow modders to add dummy buildings to beliefs, so they could augment in-city effects much more easilly, and in a way that is hidden from the UI

**Comment by TechpriestEnginseer** [comment]
No need. Can use Lua.

ReligionFounded(with the right belief) triggers a PlayerDoTurn or fires up a dummy global event that'll begin checking for beliefs.

**Comment by pineappledan** [comment]
Does something similar trigger for CityConverted()?

**Comment by pineappledan** [comment]
That's precisely the issue. I could fire a global event on the religions founding, but I can't have certain traits "track" a religion from city to city

**Comment by TechpriestEnginseer** [comment]
The problem is that you are ignoring the global event's feature. The global event can detect which belief is in the religion. Once you do that, you can then save this data and activate a CityConvertedEevnt which will say hey this religion has the belief!

**Comment by LoneGazebo** [comment]
@pineappledan unfortunately the code doesn't 'track' cleanly for that in terms of beliefs adding/removing buildings
