### ISSUE TITLE
[Feature Request] Track turns left on Prisoners of War promotion.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#4278]
No idea if it's even possible, but it'd be nice to know how long my worker is going to be useless for.

**Comment by LoneGazebo** [comment]
Not possible, can't send integers to the promotion texts.

**Comment by Iamblichos** [comment]
It’s in CvUnit. It’s related to PromotionDuration.

**Comment by LoneGazebo** [comment]
It could be made accessible but not to the tooltip for the promotion itself.

**Comment by Infixo** [comment]
Num of turns remaining will be added for all promos that have PromotionDuration > 0.

![20180424143319_1](https://user-images.githubusercontent.com/25866684/39187572-f25dcbb2-47cd-11e8-86db-2a4f2dab48bd.jpg)

**Comment by Iamblichos** [comment]
Man that's awesome.

**Comment by LoneGazebo** [comment]
Nice. Last time I tried adding integers to the tooltips I started getting crashes in EUI (which is why I didn’t do it). Let’s hope it works now (as that was a long time ago). Is stable @infixo?

**Comment by Infixo** [comment]
Lua usually breaks when there’s a nil involved. Those functions from CvUnit return 0 or a positive value. I just expose them to Lua and process using localization. It’s actually very simple code. Took me more time to find where to put it than writing it...

**Comment by Iamblichos** [comment]
@LoneGazebo me too. It's possible as he did, but real finicky if you don't get it just right the way it wants it.

**Comment by LoneGazebo** [comment]
Code is simple, nearly identical to what I tried a year ago. Started getting UI crashes. May have been unrelated and I excised too much.

**Comment by ridjack** [comment]
Well damn. <3 you guys.
