### ISSUE TITLE
Crashe'd game after setup

### ISSUE THREAD

**Issue by epic-gamers** [LoneGazebo/Community-Patch-DLL#4279]
_1. Mod version (i.e Date - 4/23):_ most recent as of 4/23

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The game crashed after i clicked next on the mod menu, set up my game, and clicked start.

_4. Steps to reproduce (optional):_

Get to nodding game setup with (full vox populist enabled with eui)

Map: earth
Map size: huge
Leader: Bismarck
Difficulty: chieftan
Pace: standard
Events:off
Click start game
Game crashes
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
Logging not enabled
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

None, the game crashed before a save was made.

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
Folder is not there upon search
4. Screenshots (optional):

**Comment by supermerill** [comment]
> Folder is not there upon search
It's the main civ5 folder, if you don't have it, you can't have civ5.  It's where the .exe is.
Look where your steam library is.

**Comment by LoneGazebo** [comment]
Yep - verify, reinstall.
