### ISSUE TITLE
Civs sit at one city and don't expand

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#428]
![8930_2015-07-18_00014](https://cloud.githubusercontent.com/assets/1131228/8760837/5d25c116-2d4b-11e5-91d4-5c3d92d90be1.png)
![8930_2015-07-18_00015](https://cloud.githubusercontent.com/assets/1131228/8760838/6244e3fc-2d4b-11e5-844c-4a4cbed47740.png)

**Comment by LoneGazebo** [comment]
I don't see this problem, at all. Using any mods outside the standard set?
G

**Comment by Radost** [comment]
InfoAddict
Morroco later expanded, while Byzantium put 2 more meager cities and proceed to be bad further.

**Comment by LoneGazebo** [comment]
One game does not a bug make, but in all the games I've been testing over the past week the AI has consistently had 4+ cities by turn 100. May just be an odd situation.

**Comment by Radost** [comment]
Doesn't seem to be fixed.
![8930_2015-07-23_00006](https://cloud.githubusercontent.com/assets/1131228/8855671/e4777e7e-317f-11e5-981c-789c426684e2.png)
![8930_2015-07-23_00001](https://cloud.githubusercontent.com/assets/1131228/8855733/37750718-3180-11e5-85b2-415ce76d7914.png)
Notice how huns and shoshones are sitting at one city too.
