### ISSUE TITLE
ctd with modpack

### ISSUE THREAD

**Issue by a1nosweat** [LoneGazebo/Community-Patch-DLL#4280]
_1. Mod version (i.e Date - 4/23):_

I've used the following modpack
http://dump.bitcheese.net/files/tufekif/MP_MODSPACK_VP_4-20_eui_mods.rar
VP 4-20 EUI
with
1. Unit Path Viewer (v 10)
2. UI - Improved City View (Vox Populi EUI) (v 10)
3. UI - Religion Spread (Vox Populi) (v 1.0)
4. UI - Filters in Trade Route Overview (Vox Populi) (v 1)
5. UI - Show XP in Military Overview (v 2)
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
CTD on end of ai turn, after city states but before barb turn

_4. Steps to reproduce (optional):_
Choose production for cities and then hit next turn. crashes regardless of peace deal option
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1940451/Logs.zip)

[Harald Bluetooth_curious bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1940454/Harald.Bluetooth_curious.bug.zip)

Normally I'd save just before hitting next turn, but I use the DX9 civ for full screen and dx11 for windowed view and the dx11 version has a different bug, I cannot build anything in cities.  I shall offer some input to the modpack forum chat on fanatics.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ryanmusante** [comment]
Is this the same modpack as referred to in https://forums.civfanatics.com/threads/dlc-modpack-and-43-civ-version-repository.609278/page-16?

Apparently there are duplicate folders of ICV causing a conflict. It was improperly created.

**Comment by Infixo** [comment]
I can confirm that this an actual DLL error.
In CvHomelandAI.cpp:
```
if (pUnit->isEmbarked())
{
	pTargetPlot = TacticalAIHelpers::FindSafestPlotInReach(pUnit, true);
	pUnit->PushMission(CvTypes::getMISSION_MOVE_TO(), pTargetPlot->getX(), pTargetPlot->getY());
	return true;
}
```
pTargetPlot returned from FindSafestPlotInReach() is NULL and the next lines throws an exception. Happens while trying to move an embarked Worker.

**Comment by Infixo** [comment]
@a1nosweat If you want to continue your game, pls. put those files into the modpack.
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1942511/CvGameCore_Expansion2.zip)

[DiploGlobalRelationships.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1942515/DiploGlobalRelationships.zip)

**Comment by Infixo** [comment]
@ilteroi FindSafestPlotInReach() is used several times and not all cases are secured with != NULL check.

**Comment by ilteroi** [comment]
i checked but that was actually the only instance which could cause a problem.

i'd prefer if you didn't merge that fix, because that function looks quite different now on my end with the fortification changes. so there will be conflicts.

**Comment by Infixo** [comment]
Oh, I already did...

**Comment by LoneGazebo** [comment]
don't worry, I'll manually merge.
