### ISSUE TITLE
Warlord difficulty gives old +50% damage bonus versus barbarians

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#429]
![8930_2015-07-18_00013](https://cloud.githubusercontent.com/assets/1131228/8760845/b698295a-2d4b-11e5-903a-7388428b54ab.png)

**Comment by LoneGazebo** [comment]
I'll check.
G

**Comment by LoneGazebo** [comment]
I checked the code and all looks well.
G

**Comment by Radost** [comment]
Are you sure there aren't any hardcoded shenanigans?

**Comment by LoneGazebo** [comment]
The values in the XML are correct, and the function in the DLL is a simple % bump.
