### ISSUE TITLE
The tooltip on my former cities that were conquered says that I can liberate them to make my own civ happy

### ISSUE THREAD

**Issue by ekolis** [LoneGazebo/Community-Patch-DLL#4290]
_1. Mod version (i.e Date - 4/23):_
v88?

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi / Community Patch, Calypso's Colored Religious Icons (Basic), City Limits, City States Leaders for BNW (Flags)

_3. Error description:_ 
If one of my cities is conquered, it has my flag on it sort of grayed out and if I hover this flag it says that liberating the city will make *my empire* happy. This doesn't make much sense...

_4. Steps to reproduce (optional):_
Let one of my cities get conquered. Hover mouse over my flag on that city.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ryanmusante** [comment]
City state leaders for BNW is not compatible with VP currently. I am in conversation with Nutty about it.
