### ISSUE TITLE
Crash During AI turn

### ISSUE THREAD

**Issue by Nishiee** [LoneGazebo/Community-Patch-DLL#4292]
_1. Mod version (i.e Date - 4/23):_
Mod Version is the new hotfix for VP just released 24th of April (4/24).

_2. Mod list (if using Vox Populi only, leave blank):_
I'm currently using the following:
-Quick Turns
-Faster Aircraft Animations
-R.E.D Modpack
-Example - Removing Giant Death Robot

_3. Error description:_ 
At the end of the turn, when Venice AI is playing the game crashes without any notification. It happens without fail. Also worth mentioning that in my previous game as Denmark (Previous version of VP) the game crashed while loading a saved game, which forced me to go 20 turns back. It did not happen after that. This time around I saved right before this turn and I'm now stuck as it keeps crashing. Even after going back 5 turns, it would still crash in the same turn, while Venice was playing.

_4. Steps to reproduce (optional):_
[Egypt goes wild.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1948595/Egypt.goes.wild.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1948598/Logs.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1948599/CvMiniDump.zip)

To experience the crash just click Next Turn. I've also tried this in a different computer using this same save, it also crashed.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
Note: if you start having random crash, play without RED.

Since this crash is systematic, it is probably not the source of the problem.

**Comment by LoneGazebo** [comment]
RED most certainly the culprit.
