### ISSUE TITLE
Local happines / Neuschwanstein / Spanish Mission issue

### ISSUE THREAD

**Issue by StevenV205** [LoneGazebo/Community-Patch-DLL#4293]
_1. Mod version (i.e Date - 4/23):_

**4-11**

_2. Mod list (if using Vox Populi only, leave blank):_

**(1) Community Patch\
(2) Community Balance Overhaul\
(3) CSD for CBP\
(4) Civ IV Diplomatic Features\
(5) More Luxuries\
(6a) Community Balance Overhaul - Compatibility Files (EUI)\
(7) Community Events (v 4)\
InfoAddict (v 22)\
Quick Turns (v 10)\
Unique City-States (v 2)\**

_3. Error description:_ 

**Playing as Spain, Mission got the extra happiness from Neuschwanstein but it does not counted in the city local happiness number.**

_Maybe there is a limitation that one building cannot get buff from different sources, because in my case Mission already produce +1 happiness from Fealty.
_

_4. Steps to reproduce (optional):_

**Just, please check one of my cities where Mission exist.**

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[single.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1949734/single.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Infixo** [comment]
Because it is counted as Global Level.
See #3939

**Comment by StevenV205** [comment]
Hi, thanks for the quick replay. However, I am not sure you checked my save file because in my case it did not counted in global level as well.
![mission](https://user-images.githubusercontent.com/20181503/39344305-e6b7a6e6-49e1-11e8-9de7-64495990ab26.jpg)

In addition, you wrote in the reference thread that is will be fixed in the next version so I am a bit confused :)

- is it should be counted in the global level
- or it is a know bug and will be fixed

Thank you in advance.

**Comment by Infixo** [comment]
It was fixed in February, then broken in March. I’ve fixed again 3 days ago.
You are using 4-11 and this version has the error.

**Comment by StevenV205** [comment]
Ah ok, now I understand.

Is this something that can be savegame compatible? If so I would be greatful if you could let me know what files was changed and I will check the differencies and try to fix it by myself. It would be really good if I could continue my game.

Thanks again.

**Comment by Infixo** [comment]
The change is in the DLL. If you were playing 4-20 then you could probably use latest hotfix, but with 4-11 it is not possible. So, unfortunately, no.
