### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by myles1718** [LoneGazebo/Community-Patch-DLL#4294]
_1. Mod version (i.e Date - 4/23):_
VP 4/20/5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
No promotion box for units
Run Time Error 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
Runtime Error: C:\Users\Myles\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\UnitPanel.lua:1239: attempt to call method 'GetPromotionDuration' (a nil value)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1950419/Lua.zip)

4. Screenshots (optional):

**Comment by Infixo** [comment]
VP not updated properly.
GetPromotionDuration is a new Lua method introduced very recently and your DLL doesn’t have it.

**Comment by myles1718** [comment]
Thanks for info

How do I correct this ?

**Comment by supermerill** [comment]
To ensure a clean install:
unsubscribe CP steam mod (if needed)
Delete all mods folders. (and EUI in the asset folder of civ5)
Install vp with the installer.
launch civ5.
