### ISSUE TITLE
Tourism output of Concert Tours (Great Musician) too high

### ISSUE THREAD

**Issue by sz7331** [LoneGazebo/Community-Patch-DLL#4295]
_1. Mod version:_
4-20-5

_2. Mod list_
InfoAddict: https://forums.civfanatics.com/resources/info-addict.15725/
Appropriate Names:  https://forums.civfanatics.com/resources/civilization-appropriate-great-general-and-admiral.23029/

_3. Error description:_ 
Whenever I run a concert tour, I expect my tourism to increase by the 'strength' of the Musician. The actual output is a lot higher (expected value * 20).

_4. Steps to reproduce (optional):_
Load the savegame (Musician is pre-selected and ready to go) and perform the concert tour.

Thanks!

---------------------------

Supporting information:

_Savegame:_ 
[Savegame](https://github.com/LoneGazebo/Community-Patch-DLL/files/1952040/TourismOutput.zip)

_Screenshots:_ 
Musician and expected tourism increase:
![image](https://user-images.githubusercontent.com/15248830/39317298-86c6e172-497b-11e8-89ad-5a81106718fb.png)

Tourism according to tooltip (three times higher than expected value):
![image](https://user-images.githubusercontent.com/15248830/39317312-8edc6ef4-497b-11e8-853e-ea1fe53b256c.png)

Tourism before tour: 
![image](https://user-images.githubusercontent.com/15248830/39317326-979ae4b2-497b-11e8-9e89-71a132bfc9d7.png)

Tourism after tour: (that's almost 300000 of additional tourism)
![image](https://user-images.githubusercontent.com/15248830/39317343-a467886c-497b-11e8-882c-5e7db29b5840.png)

**Comment by TechpriestEnginseer** [comment]
You must have a lot of great works of music then!
