### ISSUE TITLE
Civil Servant Specialist Flavor

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#4297]
I was browsing the debug database when I came across the SpecialistFlavors table, and noticed that Civil Servants have significantly higher flavor values. 

![alt text](https://i.imgur.com/S8jWmOF.png "SpecialistFlavors table")

Which would explain why the mayor seems to really like assigning Civil Servants. For uniformity, perhaps it should only have FLAVOR_DIPLOMACY of 3? Or maybe FLAVOR_DIPLOMACY of 2, and then FLAVOR_GOLD and FLAVOR_SCIENCE  of 1 (Culture yield only comes at Internet).

**Comment by TechpriestEnginseer** [comment]
We could just raise the flavor of the other specialist by 1...
