### ISSUE TITLE
Feature Request - tile priority for home unit

### ISSUE THREAD

**Issue by Tekamthi** [LoneGazebo/Community-Patch-DLL#4299]
_1. Mod version (i.e Date - 4/23):_
n/a

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
no error, just a request, if its feasible w/o major code rework.  From observation in-game (forgive me if I haven't nailed existing-state here): recent AI pathfinding will occasionally move units into already-occupied tiles.. game then bumps these just-moved units out to nearby tile.

Would be preferable for QoL in own territory in open borders situation, and could mitigate open borders abuse in other civ's wars, if tile-owning unit stayed in place, and "visiting" unit was bumped, regardless of who was last to move.  (ie Civ A and B have open borders; tile owned by civ A but occupied by civ B; civ A tries to move unit to this tile, should bump B out, instead of getting bumped itself, in its own territory).  Having this apply to human moves as well, not just AI, would also be helpful in managing internal roads and strategic tiles.  

If such a tile-ownership priority were possible, a similar priority given during war-time might further eliminate some open borders abuse that I get tempted into often (ie civ A owns tile occupied by civ B unit.   civ B is at peace with civ A and civ C, but C and A are at war with each other; civ C unit that tries to move into B-occupied tile should similarly get priority to conduct his war and eliminate civ B "peacekeeping", which is a human-only behaviour, generally.) 

Thanks for considering!

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
uh. i don't know what's going on here.

do you have a screenshot or a savegame? i've never seen that (admittedly i don't play a lot these days).

definitely not an intended behavior.

**Comment by raphaell666** [comment]
I see this a lot too, the units that are moved this way release those "spawn" particles (I believe the same as when you buy units). Are there any conditionals to prevent the AI from moving multiple units on the same tile? This is pretty hard to catch as the movement is instant, I will see what I can find.

**Comment by Iamblichos** [comment]
@ilteroi it's very easy to reproduce. Play 20 turns and you'll see AI units do it.

**Comment by Iamblichos** [comment]
You'll see it early too with scouts moving around.

**Comment by Tekamthi** [comment]
sorry, I thought too this was by-design, and was fairly obvious.. it seems to me to have coincided with better AI pathfinding changes from a few months back now, but I couldnt say exactly.

I didn't keep a specific save, though it should become obvious by early mid-game, if you watch the AI move.. def happens here and there in the early scouting era, too, especially as the 2nd and 3rd cities go down and the areas available fill up.

I'll be back in-game this wknd, and will upload a save then

**Comment by Iamblichos** [comment]
@ilteroi  Nah, I mean just play a game for 20 turns, you'll see it. You can't miss it.
