### ISSUE TITLE
EUI doesn't preview corporations bonuses when a luxury gets in the borders

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#430]
![8930_2015-07-18_00003](https://cloud.githubusercontent.com/assets/1131228/8760862/63427750-2d4c-11e5-9226-803ade3373ee.png)
![8930_2015-07-18_00002](https://cloud.githubusercontent.com/assets/1131228/8760863/63742c5a-2d4c-11e5-8e21-f430a2150958.png)

**Comment by LoneGazebo** [comment]
That's an issue with EUI that I need to fix.

**Comment by Radost** [comment]
It doesn't seem to be fixed. Though the whole info did popup for several turns in industrial era, but for the most time it doesn't show tile bonuses on an improved resource.

**Comment by LoneGazebo** [comment]
What do you mean 'for the most time?'

**Comment by Radost** [comment]
For the most time = all turns it didn't preview bonuses.

**Comment by LoneGazebo** [comment]
Well, the code is identical to EUI's code for that, except that I added the 'nofreshwater' filer. I hate LUA with a fiery passion, so I'm not terribly excited by the process of working on this.
