### ISSUE TITLE
Some Building production costs not going down with tech

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#4302]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

this is rather minor, but I noticed a granary is 65 production when i get the tech, but goes down to 63 when i've completed all tech in Ancient era. same with the other starter buildings, except for Monument which stays at 65. 

i didnt check every building in the game, but it seems most everything including wonders gets cheaper as you go along (excluding monument I noticed)...its kind of weird they change cost at all honestly, but if theyre gonna, they all should right? =)  

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mitchsp** [comment]
As far I know the reduction in cost is 5% by era, but this don't affect to Monument and Shrine because being available since beginning and not tied to any tech.
So it's a minor inconvenience, if it could be fixed great, but in the other way isn't gamechanging at all.
Btw I remember that had to ask you about Vox Populi Luxuries Re-Worked+, will post now in the thread.
