### ISSUE TITLE
belief_yieldfromconversion misbehaving notifies

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#4304]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

for using this in an Enhancer, lots of false notifications. 

since enhancing comes late, cities are already established under the religion - so on the turn of adopting you'll see multiple notifies about getting the bonus, but only 1 will apply (confirmed for science). 

 then in subsequent turns it seems to apply the bonus once per turn, working retroactively for cities already converted

but say, if i took it as a founder with a value of 5 gold with 5 cities converting I would get - 5 gold, 10 gold, 15 gold, 20 and 25.

as an enhancer, it applies like this -   25, 25, 25, 25, 25. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by deadstarre** [comment]
I figured the numbers were WAD but thought id mention it, however the notifications on side panel are acting wonky. 

if the bonus applies once per turn, the notify should be limited to show once per turn. currently ill get a bunch of notifies at once (but not all the yield at once) and then the actual bonus kicks in on a later turn which had no notify telling me about it.

**Comment by LoneGazebo** [comment]
I've made an adjustment, may fix the issue. We'll see. It's benign.
