### ISSUE TITLE
CTD late game on same turn

### ISSUE THREAD

**Issue by username-9001** [LoneGazebo/Community-Patch-DLL#4305]
_1. Mod version (i.e Date - 4/23):_
4-20-5

_2. Mod list (if using Vox Populi only, leave blank):_
(1) Community Patch
(2) Community Balance Overhaul
(3) CSD for CBP
(4) Civ IV Diplomatic Features
(5) More Luxuries
(6c) 43 Civs CP
Terrain Names Corrected (v 2)
Reforestation (v 8)
Community Patch Mod Compatibility (v 14)
Ethnic Diversity (vanilla scale) (v 29)
Ethnic Diversity Unit Pack for Mods (v 29)
Ethnic Diversity Unit Pack (v 29)
Global Warming Congress (v 2)
Global Warming (v 7)
Emigration (VP)
Units - No Futuristic Units (v 1)
Quick Turns (v 10)
Ingame Editor (v 39)
InfoAddict (v 22)
Faster Aircraft Animations (v 3)
Buildings - Upgrade System (v 12)
Civ Names by Policies (v 8)

_3. Error description:_ 
Crashes on the same turn every game (turn 165). A city state diplomacy menu will show up then crash. Not sure if it crashes on AI or my turn because it happens too fast. I'm just observing the AI play against each other, so I have a workboat off the side to not interfere with gameplay. 
Map: Pangaea Plus 
Size: Small
Difficulty: Emperor
Speed: Quick
I have played other games with these same settings and they CTD around late game time frame. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1958413/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[AutoSave_0160 AD-1675.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1958414/AutoSave_0160.AD-1675.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1958415/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by username-9001** [comment]
I read somewhere disabling events can prevent these issues. I did for this game and still have the same problems.

**Comment by Iamblichos** [comment]
IGE is grand mod, but I don't recommend you run that your entire game. It taxes the UI thread heavily. Do what you need to do and get out of it.

**Comment by username-9001** [comment]
I took out Global Warming and Global Warming Congress. It CTD once, but I reloaded and it didn't happen again. What a shame it would have been a nice mod to play. I noticed it was on the compatible mod list, so I'm not sure if it's not compatible anymore or if it's just the combination of mods.

**Comment by LoneGazebo** [comment]
I’d report it to the thread, they might want to know.
