### ISSUE TITLE
Beliefs SpyPressure not working

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#4306]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I ran a quick test to find out what the amount of pressure actually was, to my surprise it was non existent, for both diplomats and spies

target city had no religion nor pantheon, if that matters.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Issue you are probably seeing is that you have to have at least one follower to get the bonus. That's undocumented, so I'm removing that stipulation.

**Comment by deadstarre** [comment]
absolutely, and that makes an enormous difference too i think - now spies can actually create followers where there were none before, without that aspect their use was rather limited Id suppose. 

top notch, thank you =)

**Comment by LoneGazebo** [comment]
Right now it multiplies by the adjacent city pressure value (in GameSpeeds). In CBO that's a 5x modifier (so +35 pressure from a spy alone). That...seems high, no?

**Comment by deadstarre** [comment]
it only exerts on the city hes in, its not radiating out from there as well right? and considering spies are rather limited until later in the game when religion gets pretty much cemented anyway... 35 wouldnt seem out of line to me. seems like itd be a great way to hold religion over a lonely city state. and its just one enhancer.. but i dunno. needs testing i guess? =)

**Comment by LoneGazebo** [comment]
we'll see.

**Comment by LoneGazebo** [comment]
and yeah, it doesn't radiate.
