### ISSUE TITLE
EUI doesn't preview building-related tile yield bonuses

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#431]
![8930_2015-07-18_00019](https://cloud.githubusercontent.com/assets/1131228/8760927/86e0a1c4-2d50-11e5-8665-2578f4f079a9.png)
![8930_2015-07-18_00020](https://cloud.githubusercontent.com/assets/1131228/8760928/8af4510c-2d50-11e5-91dd-5f552baec4c7.png)

**Comment by LoneGazebo** [comment]
Same as corp problem.
G
