### ISSUE TITLE
"Highest Culture" trade route filter doesn't work

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4310]
_1. Mod version (i.e Date - 4/23):_ latest

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

When filtering trade routes available for a given Caravan or a Cargo Ship, the "Highest Culture" filter doesn't apply properly (doesn't show highest culture yield routes on top). "Highest Gold" and "Highest Science" work fine.

**Comment by ridjack** [comment]
I've noticed this, too. Thought I was misunderstanding something so didn't think to report it.
