### ISSUE TITLE
Feature Request: Make 'City List' panel visible during trades.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#4311]
Wanting a way to see my cities' demands, particularly when the AI offers a trade on their turn and I can't just close the trade and look real quick.

**Comment by ridjack** [comment]
Is there no way to prevent the buttons making the call during AI screens? I know the DiploList usually doesn't work during AI turns, although it also does sometimes.

**Comment by LoneGazebo** [comment]
No, as the calls are pushed through by lua and there aren't checks against it.

**Comment by ridjack** [comment]
Damnit. Oh well, thanks for the quick response.
