### ISSUE TITLE
Is "Esprit de Corps" working?

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4313]
_1. Mod version (i.e Date - 4/23):_4-30

_2. Mod list (if using Vox Populi only, leave blank):_FlagPromotions

_3. Error description:_ 

Percentage bonuses and maluses breakdown when hovering over a unit I'm going to attack don't show +10% attack bonus modifier. (I'm playing as France and testing it on a unit I'm about to attack for the first time during my turn).

**Comment by LoneGazebo** [comment]
You get it for subsequent attacks. Not the first.

**Comment by saamohod** [comment]
Oh, ok. 
The wording must be too hard for me to grasp :D  
Maybe the key word "subsequent" could make the sentence more clear? Or is it just the poor skill of my English?

**Comment by LoneGazebo** [comment]
It's correct - each time you attack, it adds 10% to the next attack. So 1st = 0, 2nd = 10, etc.
