### ISSUE TITLE
Random units spawn when entering Atomic Era

### ISSUE THREAD

**Issue by ziwdon** [LoneGazebo/Community-Patch-DLL#4314]
_1. Mod version (i.e Date - 4/23):_
4/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When researching 'Radio' and entering the Atomic Era, a bunch of random units spawn next to my capital without any apparent reason (at least none that I could find).
Also, if I use a Great Scientist or a tenet to level an alternate technology, other than 'Radio', the behaviour is different (only spawns about 2 units).

_4. Steps to reproduce (optional):_
Just skip to next turn. You can also use a Great Scientist (sitting next to the capital) or adopt the level 2 tenet that grants 2 free technologies.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Sejong_0720 AD-2035-January.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1964199/Sejong_0720.AD-2035-January.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
That’s a bonus from vassalage. See the vassalage screen.

**Comment by ziwdon** [comment]
Oh I see! Thanks.
But is it normal for different technologies to grant a different amount of units though?
