### ISSUE TITLE
Stone Works no longer require improved resoureces

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4315]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Current version, Stone Works can be built as long as the city's borders it grows to contain a quarry resource even without improvement. the description says it's only for improved ones, though.

**Comment by LoneGazebo** [comment]
#4318 
Fixed. Will hotfix (savegame compat)
