### ISSUE TITLE
City management bad AI

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4316]
_1. Mod version (i.e Date - 4/23):_4-30

_2. Mod list (if using Vox Populi only, leave blank):_FlagPromotions

_3. Error description:_ 

It seems there are issues with city governor AI still . "Food focus" doesn't work properly, see the screenshot. The 6-food tile is consistently ignored in favor of crappy 2-food or 1-food/1-prod tiles.

EDIT: Also see the juicy coastal tiles being ignored!

 Savegame attached.

![inked20180501185520_1_li](https://user-images.githubusercontent.com/16341598/39480743-ce57c08e-4d71-11e8-9fe8-6e5fc875fcbf.jpg)

[food focus.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1964318/food.focus.zip)

**Comment by LoneGazebo** [comment]
I cant replicate your consistent issues with this, my guess is a mod conflict is messing with management flavors.

**Comment by saamohod** [comment]
I realize it is not your duty to know, but could you guess which mod(or mods) is to blame?

![20180501200034_1](https://user-images.githubusercontent.com/16341598/39483287-894cde6c-4d7a-11e8-8991-e89506e303a3.jpg)

**Comment by LoneGazebo** [comment]
I don’t know the code sets of other mods like those unfortunately.

**Comment by deadstarre** [comment]
the map script? nothing else looks even remotely relevant

**Comment by saamohod** [comment]
@deadstarre 

Interesting. Could it mean that one of the most popular and most praised Tectonic Map Script is screwing up Vox Populi?

**Comment by saamohod** [comment]
I'm no programmer and have next to zero clue how modding is made, but...
Could it make things clear if some of you guys who know what to do, could you just load the save I provided and check it up? I mean, if you load it and confirm that governor AI behaves oddly (as seen with the Orleans city and some others), can you track the bug down?

**Comment by LoneGazebo** [comment]
I'm not going to track down 20+ mods, so you'd need to zip up your mods folder and share it. I just simulated a setup similar to yours and I didn't have the same issue. Are you per chance using IGE or another mod to give yourself tiles?

**Comment by TechpriestEnginseer** [comment]
The problem is that we are unable to reproduce it. It's very difficult to load up the save and load up the mod because of how the load order can differ even if we have the same mod and the same version. Thus what many developers tries to do is try to replicate the situation and analyze how the replication and your original scenario produce the same result.

**Comment by saamohod** [comment]
>Are you per chance using IGE or another mod to give yourself tiles?

Nope. Not a clue what IGE means.
Just the mods shown in the screenshot (most of which are graphical and animation mods, apart from QuickTurns and Tectonic Map Script, as far as I can judge).

**Comment by ryanmusante** [comment]
I apologize if this is off topic but, according to Planet Generator: 
`Built on top of Cephalo's Perfect World 3 (well, my updated version of it) with code inspired by Tectonic Map Script by Haftetavenscrap and Tectonics by LDiCesare.`
Does this mean that Perfectworld3, Tectonics and Planet Generator would be susceptible to these problems if they share similar code base?

**Comment by ridjack** [comment]
My wife and I both use Tectonic and have both seen the same issue consistently. Obviously does not confirm anything, but it at least credence to the possibility, particularly since she and I don't really have too many other mods in common.

**Comment by LoneGazebo** [comment]
It is possible. @infixo May be working on it.
