### ISSUE TITLE
F on coastal embarked

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4317]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Before, if I clicked F on my board of keys, the unit stopped moving - the game counted it as if I chose to just forfeit my turn on that embarked unit. Now, the unit doesn't consider it an order for embarked at all, and the end turn "do your action before end turni" thing doesn't go away after clicking F.

**Comment by ilteroi** [comment]
well. embarked units cannot fortify, and neither is fortify equal to skip. so i'm inclined to argue that the current behavior is more correct than before?

**Comment by Enrico-Swagolo** [comment]
They weren't fortifying before, they just stopped actions. As it is, the
hotkey doesn't work and that's all that changed - it is inconvenient.

**Comment by ilteroi** [comment]
well, it sure is easier to hit the space bar than the F key :)

**Comment by Enrico-Swagolo** [comment]
I didn't know you can hit space, does it still fortify? Will try much later.

**Comment by ilteroi** [comment]
ok, misunderstanding, you were talking about sleep not fortify ... fixed that.

anyway skip turn will give you the fortify bonus since the 4/30 version.
