### ISSUE TITLE
Unfinished farm gets destroyed by road construction

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4319]
_1. Mod version (i.e Date - 4/23):_4-30

_2. Mod list (if using Vox Populi only, leave blank):_ Tectonic Map Script

_3. Error description:_ 

I reassigned a worker who was one turn short of completing a farm on a wheat resource to a different task (sheep tile to the left) and ordered another worker to build a road to the wheat tile (by pressing "Route To Mode" button, screenshot 1). The next turn all the progress on farm is zeroed. (Screenshot 2)

savegame attached (before the order to continue the road is given)

![20180501223925_1](https://user-images.githubusercontent.com/16341598/39490381-5cdbe2e4-4d91-11e8-8694-462afbda9e2c.jpg)

![20180501223830_1](https://user-images.githubusercontent.com/16341598/39490395-646da77c-4d91-11e8-9cbc-0124dc9a9f99.jpg)

[killed farm.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1964971/killed.farm.zip)

**Comment by LoneGazebo** [comment]
completing a build on a tile resets build times for all objects on the tile - pretty sure it's always been this way.

**Comment by saamohod** [comment]
>completing a build on a tile 

My point is, my worker **didn't complete** a build (farm). He was moved one turn before the farm would be completed (as seen on screenshot 1 where it shows that one turn is left before the completion). Then another worker stepped in and started building a road on the tile. **The next turn** the build progress on the farm is lost and it shows that it again requires six turns to build it. The game behaves as if I gave an order to build an **incompatible** improvement (mine, camp etc) which of course would kill the progress of a previous work (farm). But it's not the case. Road can coexist with a farm obviously and there is no call for the farm progress to be zeroed. Despite being illogical, I can't remember this happening in previous versions.

**Comment by TechpriestEnginseer** [comment]
I believe it's because of the build queue. There's no separate queue for route and improvements, so if you decided to build a road mid-way of building a farm, it's going to clear the farm queue and begin a new improvement for roads.
