### ISSUE TITLE
Civilopedia crashes if entered from civ selection

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#432]
If I go to civilopedia page from civ selection by right-click, empty civpedia page appears and I can't close it. It forces me to exit game. It became tedious as I often accidentaly right-click in menu.
I don't know if it is problem with EUI or CPP but it breaks no matter what I right-click in menu.

**Comment by Radost** [comment]
It's EUI problem.

**Comment by LoneGazebo** [comment]
You can't do that, as the database isn't fully loaded in a mod with EUI.
G
