### ISSUE TITLE
[BuildingText.sql] Entry is duplicated.

### ISSUE THREAD

**Issue by ErikSteiner** [LoneGazebo/Community-Patch-DLL#4320]
_1. Mod version (i.e Date - 4/23):_
3.4.20.5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Look for this entry, in 3.4.20.5 you will find it twice.

_4. Steps to reproduce (optional):_
(2) Community Balance Overhaul\Balance Changes\Text\en_US\BuildingText.sql

`WHERE Tag = 'TXT_KEY_WONDER_BIG_BEN_HELP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );`

---------------------------
Didn´t check the new update yet, maybe the issue was resolved.

**Comment by LoneGazebo** [comment]
Yeah I'd already fixed, thanks though!
