### ISSUE TITLE
Newly created units not allowed to embark. A bug?

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4322]
_1. Mod version (i.e Date - 4/23):_4-30

_2. Mod list (if using Vox Populi only, leave blank):_Tectonic Map Script

_3. Error description:_ 

A single-tile island city cannot finish production of a unit (in my case a skirmisher), and a message says "No room for a new unit! Philadelphia tried to place Skirmisher, but there is no tile to move it to".
Aren't newly created units simply allowed to embark into water if the garrison place is occupied? A bug, a new feature or did I simply never pay attention to it?

![20180502011945_1](https://user-images.githubusercontent.com/16341598/39496583-b6fb46aa-4da7-11e8-9eb9-d308c1d46414.jpg)

**Comment by LoneGazebo** [comment]
It's always been that way - if there's no valid spot, they can't appear. @ilteroi can confirm though as he may have made changes to this.

G

**Comment by ilteroi** [comment]
it has been like that forever ... embarked units are too vulnerable
