### ISSUE TITLE
4-30-1 Cant bild stables

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4324]
_1. Mod version (i.e Date - 4/23):_
With 4-30 can build, the same save with 4-30-1 cant. City has improved horses and sheep.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
did you hop to the hotfix I pushed today?

**Comment by bigcat88** [comment]
Wow, there 4-30-2. Will test now, give me 5 min.

**Comment by LoneGazebo** [comment]
Fixed. Will reupload shortly. You may have to reconnect the resource to get it to show.

**Comment by bigcat88** [comment]
Ok, will wait. Thanks anyway :)

**Comment by LoneGazebo** [comment]
done.

**Comment by bigcat88** [comment]
It works and I don't need to reconnect resources. Great!

**Comment by LoneGazebo** [comment]
Woot woot
