### ISSUE TITLE
Borobudur

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4325]
_1. Mod version (i.e Date - 4/23):_
4-30-4

_3. Error description:_ 
Borobudur don't give 3 spreads. Only to those 2 missionaries that he spawn. All new missionaries(no matter in Holy City or not) has only 2 spreads. Old missionaries receive additional spread - that is ok.

**Comment by LoneGazebo** [comment]
Weird. Oh well will fix later.

**Comment by LoneGazebo** [comment]
I see what happened, my manual merge dropped my code from the unit initializer for missionaries for the global bonus. @infixo mind taking a look while I’m away? You can always hotfix and drop the dll on civfanatics if anyone needs it. It’s not urgent though.
