### ISSUE TITLE
Quick razing of cities

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4326]
_1. Mod version (i.e Date - 4/23):_4-30

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Has the razing time of cities been shortened dramatically? Once I captured a city with 4 population and chose to raze it, it was gone the next turn. A bug or a feature?
(The city dropped from 4 to 3 population after the capture). So the city of 3 disappears the next turn due to razing.

![20180502175144_1](https://user-images.githubusercontent.com/16341598/39530683-1e56f134-4e32-11e8-8a5b-d9eea0923b07.jpg)
![20180502175236_1](https://user-images.githubusercontent.com/16341598/39530684-1f828d5c-4e32-11e8-95a3-072b95ea9db4.jpg)

**Comment by LoneGazebo** [comment]
@infixo or @iamblichos or @ilteroi mind looking? I made a last minute change to razing to fix a CTD and may have mucked something out. Gone until next week.

**Comment by saamohod** [comment]
Another possible bug can be seen on the screenshot. A unit stationed in the city (in my case a Horseman) gets expelled out of the city tile after the city has been razed, so that the Horseman ends up in the water the next turn.

**Comment by bigcat88** [comment]
Units expelled out is the standard behaviour.

**Comment by ilteroi** [comment]
reproduced ... fix tomorrow

**Comment by ilteroi** [comment]
try this - contains this fix and a bunch of other goodies too

[CvGameCore_Expansion2_20180503.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1969821/CvGameCore_Expansion2_20180503.zip)

**Comment by bigcat88** [comment]
@ilteroi this is the old topic https://github.com/LoneGazebo/Community-Patch-DLL/issues/4202

**Comment by LoneGazebo** [comment]
@ilteroi the crash is protecting against a city of size zero.

**Comment by ricanuck** [comment]
is the fixed dll somewhere to be dl?

**Comment by saamohod** [comment]
>here you are. also contains some other goodies

Does it go to Assets/DLC/Expansion2 ?

**Comment by ilteroi** [comment]
na. it goes into mods/community patch

**Comment by ricanuck** [comment]
thanks man!
