### ISSUE TITLE
GetNumTradeResourceImports function doesn't count Minor Cities' resources

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#4327]
1. Mod version: 4-30
2. Mod list: MUCfVP
3. Error description:
One of new abilities in MUCfVP didn't work properly. Checked lua code and while modifying and checking logs it turned out that function "GetNumTradeResourceImports(PlayerID player)" doesn't count resources imported from allied minor cities (iron in my case). Instead I used "GetNumResourceAvailable(ResourceType resource, bool includeImport)" with bool state set on 1 and it worked well.

**Comment by LoneGazebo** [comment]
Well it should only check that if you have the relevant ability I believe.

**Comment by LoneGazebo** [comment]
I don't understand what you are getting at here.
