### ISSUE TITLE
Conscription policy not always working

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#433]
As talked here http://forums.civfanatics.com/showpost.php?p=13904207&postcount=2515

 Originally Posted by Furkhail
"I got conscription the previous turn to a city growing to 6 citizen. No unit. City has garrison in case that matters.

Neither the next city that got to 6. Maybe conscription starts at 12? Capital just got to 12 population. No unit."

In my game with 7/15V2 it worked right at the beginning, but later (I think that when retaking the game other day) not longer.

**Comment by Mitchsp** [comment]
Still happening in 7/21 version.

**Comment by LoneGazebo** [comment]
7/21v2? Send me your save with it. 

G

**Comment by Mitchsp** [comment]
7/21v1, haven't tried v2 and according to the changelog of v2 thought that these two issues weren't touched in that version.
Do you need a 7/21v1 save? In other case I'll install and try v2 today or tomorrow to see if these bugs are gone.

**Comment by Mitchsp** [comment]
Tried to load the old game with 7/21v2 after clearing cache and so on, and both problems still there. I'll try to start a new game tomorrow.

Here is a save just the turn before a city grow to 6 and a pasture being finished and giving 1 gold.
http://www43.zippyshare.com/v/ImxHXLrI/file.html

and here the mods useds:
![captura](https://cloud.githubusercontent.com/assets/13163824/8826002/7bc0ebc4-3083-11e5-8e82-e3a3d004eaa2.JPG)

**Comment by Mitchsp** [comment]
Sorry to be the bearer of bad news, but still not working correctly in 7/24 v2. More details here http://forums.civfanatics.com/showpost.php?p=13910863&postcount=2563

**Comment by Mitchsp** [comment]
I've tried now 7/24 v3, clearing cache, and in the first time a new unit has to appear, has been a Trireme, so I guess isn't intended ;)

<img width="680" alt="sin titulo" src="https://cloud.githubusercontent.com/assets/13163824/8891207/6f809f54-3320-11e5-9ad2-001af7cc9d63.png">

**Comment by LoneGazebo** [comment]
Not necessarily. It is a melee unit, technically, and a trireme could be conscripted. If people don't like that I can change it to land only.

**Comment by Mitchsp** [comment]
Ok, excepting that (all my others conscripted units have been boats (all my cities are coastal), the policy has been working great.
Maybe an option to leave the player control about what kind of unit he wants could be "Conscription will recruit by default a melee unit, but in coastal cities if city tile is garrisoned by a melee unit, one boat will appear instead". What do you think about?

**Comment by LoneGazebo** [comment]
There's not an easy way to enforce options like that. Easiest would be to make it a little more random or all land.

**Comment by Mitchsp** [comment]
Then probably random with a heavy bias toward melee with some sporadic boat for variety, like 80/20 75/25, could be great.
