### ISSUE TITLE
Feature: new tooltip info.

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#4332]
I talked to @Infixo and he said that thing I wand to ask you for is possible to do. What exactly?

Tolltips for some buildings and wonders say: "FREE Council", "FREE Monument" etc. It mean that when you construct building it will build that other one automatically. Problem is that that other building is earlier, sometimes much earlier in tech tree and with mods and changing environment I need to check each wonder separately to see if it has that small FREE building inside. Very often I build something and then when I achieve technology with some wonder of my interest it turns out that it gives me building I already have. So, is it possible for you to add info in those small building lets say Council that says: "is granted for free by: Stonehenge"? It would be really helpful.

**Comment by LoneGazebo** [comment]
Well it is probably possible but you’d have to cross reference all other buildings to see it. So it would be heavy on the loops.

**Comment by Infixo** [comment]
Only once, on startup to cache the values. Then it’s normal table access.

**Comment by davenye** [comment]
No idea how I managed to accidentally reference this issue, sorry.

**Comment by LoneGazebo** [comment]
@infixo for EUI yes, but for all others, no.

**Comment by Infixo** [comment]
![tooltips](https://user-images.githubusercontent.com/25866684/39820773-df7cacfe-53a6-11e8-8be5-ce9d5a0c6d86.jpg)

**Comment by LoneGazebo** [comment]
Rad.

**Comment by adaneslavo** [comment]
Awesome! Thanks.
