### ISSUE TITLE
Change Trade Unit Home City UI View  Visual Mod Issue

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#4334]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
did not see this until recently (at least I dont think I did but i notice it now)

I use

UPDATE Buildings
SET AllowsProductionTradeRoutes = '0'
WHERE Type = 'BUILDING_STONE_WORKS';

then run a quick test, I put Stone Works in Madrid and it has nothing else

then UI show Madrid with a hammer, because it knows Madrid has a Stone Works but is not recognizing it can't send hammers due to the changed code above.

![1](https://user-images.githubusercontent.com/15820785/39593990-6c27fb18-4ed9-11e8-92d8-2bb2b358d8b1.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Infixo** [comment]
ChooseTradeUnitNewHome.lua has hardcoded conditions for: BUILDINGCLASS_CARAVANSARY, BUILDINGCLASS_HARBOR, BUILDINGCLASS_GRANARY, BUILDINGCLASS_WORKSHOP, BUILDINGCLASS_STONE_WORKS.

It was taken from 'UI - Trade Route Enhancements' mod.

**Comment by deadstarre** [comment]
can't send production, no.

I was hoping the UI wouldn't have hard coded conditions for the buildings but rather could read which buildings had set AllowsProductionTradeRoutes or not, i suppose that isn't possible and/or necessary for VP

so if im gonna use the code, i need to also edit the ChooseTradeUnitNewHome.lua. understood, thank you =)
