### ISSUE TITLE
 CvCity::IsHasResourceLocal doesn't make sense

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4336]
what is the bTestVisible parameter about?

```
	if (!bTestVisible)
	{
		return m_paiNumResourcesLocal[eResource] > 0;
	}
	else
	{
		return (m_paiNumUnimprovedResourcesLocal[eResource] + m_paiNumResourcesLocal[eResource]) > 0;
	}
```

this seems very suspicious.

**Comment by LoneGazebo** [comment]
It’s used for the interface to determine whether or not an item appears in the queue greyed our or not.

**Comment by LoneGazebo** [comment]
It’s used all over the place for the can build x functions.

**Comment by Infixo** [comment]
Yup, i confirm. Just happened to walk through these lines today.

**Comment by Infixo** [comment]
It is doing what it’s intended to do.
E.g. allows for a tooltip „resource x required for a building”. If you have an unimproved resource then one call gives true, one false.

**Comment by ilteroi** [comment]
ok so the parameter should be named bIncludeUnimproved? is that it?

**Comment by LoneGazebo** [comment]
The name reflects what the game is looking for - visibility for the UI (I.e. is the resource visible but not improved) versus total resource ownership by the city.

**Comment by ilteroi** [comment]
i still don't get it but i don't care anymore
