### ISSUE TITLE
Naval unit garrison and Authority's Discipline yields

### ISSUE THREAD

**Issue by legenciv** [LoneGazebo/Community-Patch-DLL#4337]
_1. Mod version (i.e Date - 4/23):_
4-30

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Authority's Discipline applies its yields inconsistently when a city is garrisoned only with a naval unit. Sometimes, garrisoning a naval unit only grants culture; in a later turn, that city may receive both culture and happiness.

I tried to find any relation with captured cities or courthouses, but it happens at times with regular cities as well.

**Comment by LoneGazebo** [comment]
@ilteroi this bud’s for you

**Comment by ilteroi** [comment]
tried it, couldn't reproduce ...

**Comment by Iamblichos** [comment]
I wouldn’t expect a problem here since the code in terms of garrison is completely indifferent to DOMAIN_LAND or DOMAIN_SEA.
