### ISSUE TITLE
"You received tribute very recently" sudden increases

### ISSUE THREAD

**Issue by legenciv** [LoneGazebo/Community-Patch-DLL#4338]
_1. Mod version (i.e Date - 4/23):_
4-30

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

There are times when a city-state may increase the value of its "You received tribute very recently" from 0 to another value, despite no tribute being taken by the player. May happen when the city-state is afraid. Unsure of the pattern behind it.

**Comment by Enrico-Swagolo** [comment]
Noticed that, it might one turn go from 0 to 225 IIRC. It's usually CSs you tributed before, so it's good to watch them - if they turn orange, tribute or you might have to wait long turns to ask them again .

**Comment by LoneGazebo** [comment]
Tribute is managed globally so if anyone does it, it alters that value.
