### ISSUE TITLE
Feature Query/Request

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#4339]
I was wondering if it were possible to make a trait that trigger an historic event whenever a city was first converted to your religion. It seems like that would be a real hassle to keep track of in lua(?), but the DLL does that sort of check already with things like GoldPerFirstCityConversion and so on.

So my question is: is there a way to access the information of whether a city has been converted to a religion before or not with lua?
If the answer is equivalent to no, feature request: could such a Trait_ be added?

Thanks in advance you wonderful people/garden ornaments

**Comment by LoneGazebo** [comment]
I can just expose the lua for the conversion check. Will do later.

**Comment by LoneGazebo** [comment]
city:HasConvertedToReligionEver(eReligion)

Note that it only updates if the city has paid an adoption bonus - there is no check in the DLL for the first time a city adopts a religion_period_.
