### ISSUE TITLE
Excess production after building a World Wonder not being carryover

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#434]
Is only happening me with World Wonders, not National Wonders, buildings or units.

<img width="674" alt="sin titulo" src="https://cloud.githubusercontent.com/assets/13163824/8763710/4ce78ec8-2dab-11e5-8301-8170759f25c6.png">

in theory 11 production carryover, in pratice 0, that 5 are for border growth and Might policy.

<img width="673" alt="sin titulo2" src="https://cloud.githubusercontent.com/assets/13163824/8763714/7a39f51e-2dab-11e5-957e-c9fb183b264e.png">

mod package 15/7 v2
![mods](https://cloud.githubusercontent.com/assets/13163824/8763715/85856d86-2dab-11e5-8f95-583248b4ef1a.JPG)

and as an additional question, are AnC-flavors (v9) actually recommended? Thanks

**Comment by LoneGazebo** [comment]
This is part of the base code for world wonders (they don't carry over production because of the way that engineers work).

G
