### ISSUE TITLE
Specific Map Crash

### ISSUE THREAD

**Issue by Adonis-VII** [LoneGazebo/Community-Patch-DLL#4341]
_1. Mod version: 4/30

_2. Mod list: Play the World Extended Map (https://forums.civfanatics.com/threads/civ5map-lua-play-the-world-extended-brave-new-world-edition.503633/)

_3. Error description:_ 
When starting a game, in both SP and MP, with Play the World Extended as the map, Civ instantly crashes (only the host in case of MP). I have a modified version to adjust for VP's changes, but both the modified and original crash in 4-30. We have been using this map for >2 years on and off with VP, and it worked on our previous 3-17. 

_4. Steps to reproduce (optional):_
Load VP 4-30
Select Play the World extended
[VP Crash Report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1976372/VP.Crash.Report.zip)

Click Start Game
Crash

---------------------------
Supporting information:

1. Log files: Attached for both working and crashing VP versions

2. Save game: N/A

3. CvMiniDump.dmp file :
Civ isn't creating a new .dmp file if I delete the old one, but I've attached the existing .dmp if for some reason it will only edit the existing file.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	CivilizationV_DX11.exe
  Application Version:	1.0.3.279
  Application Timestamp:	546cd0a8
  Fault Module Name:	CvGameCore_Expansion2.dll
  Fault Module Version:	3.0.3.0
  Fault Module Timestamp:	5ae7e409
  Exception Code:	c0000005
  Exception Offset:	00498177
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	a70a
  Additional Information 2:	a70ad3f4a871054f86ffd48751b93924
  Additional Information 3:	9417
  Additional Information 4:	9417b439df6b375a1335029e17483503

4. Screenshots (optional):

**Comment by ilteroi** [comment]
i did find a crash but only after 120 turns ;)

**Comment by Adonis-VII** [comment]
I've tried with the updated 4-30-4 and still get instant crash.
I've gone and tried 4-20-5, which was the latest before 4-30, and it loads as expected, so there is definitely something particular to the 4-30 compile

I've tried loading the map from both \My Games\Sid Meier's Civilization 5\Maps\ and \steamapps\common\Sid Meier's Civilization V\Assets\Maps with no difference in result.

**Comment by Adonis-VII** [comment]
I've tried with other .lua mapscripts such as Planet Simulator and the others still work fine.  

Could the issue possibly be due to the odd way Play the World Extended creates the maps interacting with the staging room changes in  #4289?

**Comment by Adonis-VII** [comment]
Would #4257 have any effect on GetCivilizationType()?

**Comment by ilteroi** [comment]
did you try the build from #4326 ?

that's more or less the version i used

**Comment by Adonis-VII** [comment]
@ilteroi 
The build linked on #4326 (05-03) works. So I guess this issue was fixed at some point between 04-30 and 05-03

**Comment by Infixo** [comment]
@ilteroi Has this been solved like for sure?
Because I can confirm that it crashes with current 4-30-4 version. Engine goes into an infinite loop between CvUnit::GetDanger(), CvPlayer::GetPlotDanger() and CvDangerPlots::UpdateDanger().

**Comment by Infixo** [comment]
![obraz](https://user-images.githubusercontent.com/25866684/39824913-cf07fe32-53b0-11e8-9342-cfd2dcee1a8e.png)

**Comment by Infixo** [comment]
int CvUnit::GetDanger(const CvPlot* pAtPlot) const
	return GET_PLAYER( getOwner() ).**GetPlotDanger**(*pAtPlot,this,set<int>());

int CvPlayer::GetPlotDanger(const CvPlot& pPlot, const CvUnit* pUnit, const set<int>& unitsToIgnore, AirActionType iAirAction)
	if (m_pDangerPlots->IsDirty())
		m_pDangerPlots->**UpdateDanger**();


void CvDangerPlots::UpdateDanger(bool bKeepKnownUnits)
...
		if (pLoopUnit->IsCombatUnit() && **pLoopUnit->GetDanger()** > pLoopUnit->GetCurrHitPoints())

**Comment by ilteroi** [comment]
uh. endless recursion. nice.

the only way for this to happen (as far as i see) is when calling GetDanger() before initialization. which matches adonis' story.

so, can you try this and see if it helps?

```
/// Updates the danger plots values to reflect threats across the map
void CvDangerPlots::UpdateDanger(bool bKeepKnownUnits)
{
	if (!m_bArrayAllocated)
		return;

	CvPlayer& thisPlayer = GET_PLAYER(m_ePlayer);
	set<int> plotsWithOwnedUnitsLikelyToBeKilled;
```

**Comment by Infixo** [comment]
Seems to be working. I started a game and played several turns with no issues.
