### ISSUE TITLE
God of the open sky and citizen management AI

### ISSUE THREAD

**Issue by Mzimoxs** [LoneGazebo/Community-Patch-DLL#4343]
Version: Vox Populi 30/4 + Community Events

I chose the God of the open sky pantheon (culture for every 2 worked plains/grassland tiles + some yields for pastures)
The city governor then goes bananas and values plain/grass tiles over everything. You can choose between an empty plains tile or a 8 food/5 prod/7 gold/1 faith/1 culture fishing boat? Govenor picks the former. It doesn't matter which city focus I choose. (This also applies to specialist slots. I don't think I have ever had a game with so few great people...)

Maybe this is also related to issue #4316.

The screenshot I attached might not be the best. It's late in the game and my cities are big enough to also work the good tiles. But I think you can see the problem nonetheless.
Should be easy to reproduce, just choose said pantheon, found a city somewhere between plains/grass and non-plains/grass and watch the governor.

![ex2](https://user-images.githubusercontent.com/39007474/39664219-256557cc-5080-11e8-85b1-ea589e26862f.jpg)

**Comment by saamohod** [comment]
What Map Generator do you use?

**Comment by Mzimoxs** [comment]
It's clearly an issue with the pantheon, see screens below.

![p1](https://user-images.githubusercontent.com/39007474/39676088-a3a553c8-5164-11e8-8346-c575f59d38cc.jpg)
![p2](https://user-images.githubusercontent.com/39007474/39676089-a3c878f8-5164-11e8-8e81-f9f2e5a88739.jpg)

But to answer the question, Turkey DLC map.

**Comment by ryanmusante** [comment]
Late game and no religion?

**Comment by Mzimoxs** [comment]
What? Pantheons are integrated in religions
