### ISSUE TITLE
Evangelism

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4344]
_1. Mod version (i.e Date - 4/23):_4-30-4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

It seems Evangelism is still not working. I do not get any science in my capital for spreading my religion in cities of other religions. I'm using the .dll fix given by ilteroi in this thread: https://github.com/LoneGazebo/Community-Patch-DLL/issues/4326

EDIT: After some testing I've come to the conclusion that Evangelism does work, but only with **foreign** cities. Not sure if this is how it's supposed to be, but the description for Evangelism doesn't mention **foreign** cities, it only says "spreading your religion to cities of other religions".

**Comment by LoneGazebo** [comment]
It is foreign only, yes. Will fix text.
