### ISSUE TITLE
AI doesn't build plantations

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4345]
_1. Mod version (i.e Date - 4/23):_4-30-4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

AI doesn't build plantations on relevant luxuries. In my case Pocatello's sugar and spices(which could give him monopoly bonus) are not improved. He is somewhere between Renaissance and Industrial.

![inked20180505202521_1_li](https://user-images.githubusercontent.com/16341598/39665872-6d11f922-50a3-11e8-9dde-6cd728ce029a.jpg)

[plantations.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1976894/plantations.zip)

**Comment by ilteroi** [comment]
cannot reproduce ...

![image](https://user-images.githubusercontent.com/1358966/39667373-d2d63b0e-50b4-11e8-97c9-63e595a62da3.png)

**Comment by saamohod** [comment]
Must be Tectonic Map Script again. Looks similar to https://github.com/LoneGazebo/Community-Patch-DLL/issues/4316
