### ISSUE TITLE
City attack range not increasing after Gunpowder.

### ISSUE THREAD

**Issue by Vortok** [LoneGazebo/Community-Patch-DLL#4348]
_1. Mod version (i.e Date - 4/23):_
4-30-4

_2. Mod list (if using Vox Populi only, leave blank):_
![image](https://user-images.githubusercontent.com/34967157/39668725-afb34112-509b-11e8-959f-5fe5e1440015.png)

_3. Error description:_ 
As shown from the bottom screenshot, I've finished Metallurgy, which has Gunpowder as a pre-req.  Gunpowder's tooltip indicates that it should increase city attack range, but my city's range in all directions is still just 2.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
I'll turn them on... someday... -.-

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Rome_VP_4-30.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/1977205/Rome_VP_4-30.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/34967157/39668703-05f0e3aa-509b-11e8-9680-573c95bfd086.png)

**Comment by deadstarre** [comment]
its for indirect fire upgrade, not range, but it reads as range... i assume it had to be that way

**Comment by Vortok** [comment]
It'd be a bit unfortunate if the system had a limitation like that (Mathematics lists just range), but it'd be cool if it's just a simple case of a misleading tooltip.  4 range cities was sounding... not quite right, though.

**Comment by LoneGazebo** [comment]
@deadstarre not exactly sure what you’re asking. Anyways I’ll look at the sql later.

**Comment by deadstarre** [comment]
UPDATE Technologies SET BombardRange=1 WHERE Type='TECH_AGRICULTURE';
UPDATE Technologies SET BombardRange=2 WHERE Type='TECH_MATHEMATICS';
UPDATE **Technologies SET BombardRange=2**, BombardIndirect=1 WHERE Type='TECH_GUNPOWDER';
UPDATE Technologies SET BombardRange=3, BombardIndirect=1 WHERE Type='TECH_DYNAMITE';

in bold, if the BombardRange=2 wasn't set for the second time when inserting BombardIndirect=1, would the city lose its range. my guess was yes
