### ISSUE TITLE
[Feature Request] "No and stop asking" in response to open borders spam?

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#4349]
This has been an issue since vanilla; it's _better_ in VP, but the last couple of games I've played have had one or two particularly obnoxious Civs who just will not drop it.

Is it possible to maybe add something in the 'Discuss' screen, similar to the 'stop spying' option that says something like, "I don't want to open our borders at this time."? To be honest, I wouldn't even care if it came with a small diplomatic penalty; I just really want the spam to stop.

**Comment by adaneslavo** [comment]
It is similary annoying like: 
- Will you declare war on XXX? (Value of the offer: **25000**, sic!)
- No?
- Ok.
(few turns later)
- Will you declare war on XXX?

Why even such thing with value over couple of thousands even appear? Desperate?

I think there should be some delay between two the same proposals f.e. if you suggest open borders treaty and guy will decline, then you cannot add open borders suggestion for let's say 20 turns. It should prevent spam.

**Comment by ryanmusante** [comment]
Also, with a refusal comes diplomatic penalty. So, would a non-answer count as refusing and add concurrent to the hit to your track record with said civ?

**Comment by ridjack** [comment]
I don't think refusals in the trade screen have a diplomatic penalty.

**Comment by LoneGazebo** [comment]
Not going to do this, sorry. The AI needs to be able to ask when it wants to, just like a human.
