### ISSUE TITLE
QoL petition - bonus yields happening at the start of a turn not being lost when absence of item queued

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#435]
For example production or science from Liberty's policies are lost if not production/tech queued and previous item is finished the same turn that happens born citizen/borders expands.

Actually i'm used to doublecheck before ending turn, but later in the game is pretty tedious.

**Comment by Radost** [comment]
Does the science burst from Great Scientist get lost when you expend him while not having a tech selected?

**Comment by Mitchsp** [comment]
Don't know, haven't tested.

**Comment by LoneGazebo** [comment]
This is unavoidable, because city functions fire at different times. I'd have to completely reorganize the functions of cities to avoid this.

G
