### ISSUE TITLE
Strange settler behaviour.

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#4350]
Mod version: 4-30
Mod list: many, see attached file
![mods](https://user-images.githubusercontent.com/33016300/39671236-58da9f74-5114-11e8-9d88-9928a958563b.png)
Error description:
See image: 
![20180506000610_1](https://user-images.githubusercontent.com/33016300/39671242-7370cb2e-5114-11e8-9920-94ebcae0e608.jpg)
Do you have any idea why Babylon sent settler almost at the beginning of the game (red arrow), and then was just walking (green arrow) without setling? He has nice spots to settle in that area (blue crosses), but even if he wanted he could settle near his capital (1 or 2 spots), but after this he didn't built any more settlers and he seems to be stuck at 1 city. I settled in one of places marked with blue cross between mountains and he still is there looking for something. Other countries are good, have even more cities than I do. It is first time I can see such thing. Database or lua logs do not show anything.

**Comment by Iamblichos** [comment]
Oh my....whew....

**Comment by ilteroi** [comment]
hard to say anything with that many mods involved.

i haven't seen that in core vp. the marked spots aren't too great though, so maybe the settler wants to go somewhere else in fact but is trapped because it can't embark.

**Comment by adaneslavo** [comment]
So why he didn't go further to look for new location? I understand that he couldn't get back because there was barbarian camp, but  saw him during some initial turns and he was moving without escort. That seems like AI issue and none of mods changes that aspect.

**Comment by LoneGazebo** [comment]
Remember he can’t necessarily see what you see.

**Comment by ridjack** [comment]
I have so, so many questions about that mod list. Are those 'fixed' mods all mods you fixed yourself, or are they available elsewhere?

**Comment by adaneslavo** [comment]
I fixed or modified them by myself for my own personal use for now. Im creating some kind of stable and balanced modpack.
