### ISSUE TITLE
Promotion Overhaul incorporation.

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#4351]
I really like playing VP and admire your work. The only thing that really concerned me was style of promotion icons and descritpion. I talked to @Infixo about that and he suggested me making small modmod to rework them. It turned out that there more issues in that matter to fix. So I did such modmod and @Infixo doing some small VP updates (civilopedia cathegories, small changes) make it possible to finish. What it does?
- rewritten 314 promotion descriptions from VP (they are now more similar, follow ONE pattern, and same style promotions have same descriptions),
- renamed 107 promotions from VP (new names are trying to reflect what promotion does, no more names like: Evasion (XX), Can Move After Attack),
- moved 155 promotions from VP to other categories (all promotions are sorted to appropriate categories and there aren't promotion connected to ABILITY category (all new categories from @Infixo are used)),
- split 43 promotion descriptions from names (no more promotion description same like its name),
- tied 70 promotion pedias to names (now all pedia names are the same like promotions names),
- changed 97 promotion icons (all positive effect icons have now icon different than triangle (gold or silver), some icons were swapped to reflect the ability better, added few new icons).

Unfortunately I have no skill to incorporate this mod into VP. It was made to make the game clean and allow easier incorporation for other users (everything is written, needs only moving from one place to another). What do you think?

It should be up to date with latest VP changes and fixes.
[link](https://forums.civfanatics.com/threads/promotion-overhaul-for-vp.626728/)

**Comment by ilteroi** [comment]
sounds great. let's wait until G is back

**Comment by Infixo** [comment]
I feel compelled to cite myself from the past:
There are 7 files in VP that deal with Promotions, 4 sqls and 3 xmls. It's not easy to "upload" this, you can't copy & paste anything, all changes must be done manually. Plus you've added new icons, they need to be treated separately. So, I am rather reluctant to do all this.

I like the new names in many cases, but there are also many cases that are actually confusing. It's better than earlier versions, but still...
I'd say this mod would be much better if you actually just corrected / polished the promos, and not go into a big overhaul. Less changes is better here, imo.

**Comment by LoneGazebo** [comment]
I’m fine with updating descriptions and icons, but I don’t know about the changes to promotion names. Players rely on them being similar to vanilla for some semblance of familiarity.

**Comment by adaneslavo** [comment]
Fine, by me. If you add something then tell me - I will simplify my mod then to have only name changes.

**Comment by ridjack** [comment]
Is there any place in VP where there's any level of familiarity? Not even being sarcastic; it's been long enough now that I genuinely don't remember the differences.

**Comment by adaneslavo** [comment]
True @ridjack. I have never played vanilla and I cannot imavine playing without vp. I think familiarity with vanilla is not the purpose of vp which changed almost every aspect of the game. Honestly saying no one has enough patience to clean text things. Thats why I decided to help in this.

**Comment by adaneslavo** [comment]
I saw flags mod that had tgis featute. I cannot use it because flags mods needs lots of resources. So I also would bee happy to see sich feature. Maybe @Infixo could add this. He is busy but he likes ui challenges.

**Comment by LoneGazebo** [comment]
@tu-79 not in the base DLL, no - you’d have to somehow create a promotion collator in lua. Yucky.

**Comment by Iamblichos** [comment]
That flag mod is really heavy on the UI thread. I mean it crushes the late game.

**Comment by tu-79** [comment]
Weird.

My idea was replacing 
"Drill II : +10%CS + 25% vs city"
with
"Drill II: loses Drill I, +20%CS +50% vs city"

Then replace
"Drill III: +10%CS +25% vs city"
with
"Drill III: loses Drill II, +30%CS + 75% vs city"

And those promotions that currently require Drill I would require any Drill I or Drill II or Drill III. Promotions that currently require Drill II would require any Drill II or Drill III.

Does it really need to be changed in lua?

The same could be done with Explorer's free promotions. Instead of adding promotions, replace the old ones with stronger versions. It's less clumsy.

**Comment by LoneGazebo** [comment]
@tu-79,

That’d require a rethink of how promotions stack in the DLL. Not exactly feasible.

**Comment by Infixo** [comment]
@Iamblichos Only the part that displays hundreds of those small icons is problematic.
Displaying promotions in the UnitPanel is one-time action when you select a unit, the merging would happen here. The original mod adds a new field to Promotions table that controls which promos merge with which ones, so there's no complex logic here.
Maybe we could use the code from Akamal's version of the mod as he already tweaked it into VP/EUI. I don't know if it would work with NonEUI version (probably not).

**Comment by tu-79** [comment]
@LoneGazebo, I guess that's too much work, for a minor advantage. :'(

**Comment by Adonis-VII** [comment]
That feature in flags is from one of WhoWard's minimods: http://www.picknmixmods.com/mods/CivV/UI/Condensed%20Promotions.html

**Comment by ryanmusante** [comment]
So is the plan to incorporate descriptions only?

**Comment by adaneslavo** [comment]
Descriptions can be first step. Some of them need new text entries because they share the same field as names (fe Can Move After Attack). After that next part can be done fe sorting civilopedia categories. There are many polishing in the mod but names should be added as a final stage and there should be some poll about most difficult names if so. Let the people decide about that. I did this because Im not so tied to vanilla, and itbis not only my opinion. I suppose people could like it if it was incorporated. As a modmod they probably neglect it.

**Comment by Tekamthi** [comment]
fwiw whoward's 'condensed promotions' seems to work fine with VP, as mentioned a few posts back... this would be what i'd look at for cleaning up unit panel, not the other 'flag promotions' mod
