### ISSUE TITLE
Request -- Ocean tiles should not be claimable by cities

### ISSUE THREAD

**Issue by ryanmusante** [LoneGazebo/Community-Patch-DLL#4353]
_1. Mod version (i.e Date - 4/23):_
4/30

_2. Mod list (if using Vox Populi only, leave blank):_
Infixo's UI Mods

_3. Error description:_ 
Ocean tiles should not be claimed by cities. If units require compass for traversing ocean tiles, why can a city claim an ocean tile for work (extremely low yields)?

**Problems with cities having ocean tiles:**

1. Extremely low yields
2. Blocks early/mid-game travel for civs uncovering fog of war
3. Blocks mid game travel for establish sea trade routes
4. Creates deadlocks for ships at sea leading to wars otherwise unnecessary
5. Prevents artificial dead spots in between owned territories
6. Comparable to moden day Maritime Law/Admiralty Law, civs do not have so much of the ocean claimed as owned territory

FIX: Global - Coastal Waters Only Mod:

UPDATE CustomModOptions SET Value=1 WHERE Name="EVENT_CITY_BORDERS"; 
along with GlobalCoastalWatersOnly.lua 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

**Comment by ilteroi** [comment]
so your're proposing to include this mod or to replace it?

in general lua hooks aren't great for performance.

**Comment by ryanmusante** [comment]
I'm proposing to include the mod. According to latest version from 2016:

`Cities may only acquire water plots if they are adjacent to land or contain a workable feature (atolls, et al) or visible resource (fish, whales, et al)`

**Comment by Iamblichos** [comment]
If it's to be included, let's do the work in C++ and not Lua. @ilteroi is right, Lua hooks are a poor way to make a feature work.

**Comment by ryanmusante** [comment]
Indeed, cpp is the way to go.

**Comment by ilteroi** [comment]
well, that piece of code raises a few questions:

- there is also "shallow water" which is not adjacent to land. i would include that in the definition of coastal.
- there is no check for player tech? i was assuming that after a player can cross ocean the restriction would be lifted.

**Comment by ilteroi** [comment]
before compass. or whatever the relevant tech is ...

**Comment by TechpriestEnginseer** [comment]
Wasn't it that you could traverse your own ocean's tiles or was that just a version later too late? That's my inquiry.

**Comment by ilteroi** [comment]
polynesia is fine. can buy/claim from the start.

the other question i don't understand

**Comment by TechpriestEnginseer** [comment]
Ships can't travel ocean tiles that are not owned by their cities pre-Compass.

**Comment by ilteroi** [comment]
1. i think that's obsolete with the may-traverse-ocean-but-cannot-end-turn-there rule.
2. how would you settle those one-tile islands?

**Comment by ryanmusante** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/6555
