### ISSUE TITLE
Wrong description for Great Cothon

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#4355]
Great Cotton says:
- +X Gold for outgoing TRs, +Y for incoming TRs

Steam Mill says:
- TRs other players send to player makes that player earn additional X Gold and Owner of TR Y.

These are to different definitions and they use exactly the same Value in Buildings table. Which is true? I know you wanted to differentiate it somehow but in that case and probably few others it is really missleading.

**Comment by Infixo** [comment]
OK, checked it. Steam Mill is OK but Great Cothon description doesn't match DB data.
Since this is an EIC replacement, I assume it should be similar to EIC.
"Incoming TRs generate +5 gold for the City, and +3 gold for TR owner"
