### ISSUE TITLE
Feature Request: Modified XPBonusFromGGBirth Trait

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#4358]
There is a trait field used by Sweden that gives XP to all units when a Great General is born.

Would it be straightforward to add a second field that allows the specification of the great person type? 
(So that one could have XP on Great Prophet birth, for example)

**Comment by LoneGazebo** [comment]
Not without yet another GP table in traits. Probably easier to use the GP born lua hook

**Comment by Hokath** [comment]
Alright!

**Comment by Hokath** [comment]
Question:
Searching the repo I find
GameEvents.GreatPersonExpended.Add(function(iPlayer, iUnit, iUnitType, iX, iY) end);
Whereas on the googles people use 
GameEvents.GreatPersonExpended(playerId, eGreatPersonType);

Is my google-fu out of date? Or has the CP changed this hook to take more arguments?
I tried 
`function TrialFunction(iPlayer, iUnitType)
	local pPlayer = Players[iPlayer]
	pPlayer:ChangeFaith(1000)
end

GameEvents.GreatPersonExpended.Add(TrialFunction)
`
But no cigar
