### ISSUE TITLE
Morocco UA doesn't work

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#436]

**Comment by LoneGazebo** [comment]
Yes it does - just checked.

**Comment by Finarvi** [comment]
You're right. Actually, it was interface bug. Culture and gold are displayed correctly, but golden age tooltip says only "X is added per turn due to happiness". But I'm OK with that if it is intentional.
Other thing that mislead me is that Palace tooltip says that it add +3 culture which is wrong (it should be +1).

**Comment by LoneGazebo** [comment]
Unless you took Tradition, at which point it does become +3 culture.

The Traits for Morocco appear in the culture and gold tooltips of the top bar. There's no way to calc 'trait golden age points' on the toolbar, as they aren't yielded the same way as actual yields.
G

**Comment by Finarvi** [comment]
OK but with this tradition policy I have +3 from palace, +2 from throne room, +1 from policy and +1 from trait what sums up to... 5. This +2 culture is doubled.

**Comment by LoneGazebo** [comment]
Culture is not added to the capital from the trait. It is added straight to your empire total.
