### ISSUE TITLE
[Feature Request] Allow Inquisitors to function in city-states.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#4360]
Morocco keeps converting my local CS allies, which is annoying since I have Clericalism as a belief. Currently, my only defense is local pressure and counter-spam; since Inquisitors and other civilian units can enter CS' cities, it'd be nice to be able to Remove Heresy and station them like I can with my own cities.

**Comment by adaneslavo** [comment]
Or at least allow this in ALLIED CSs, not all.

**Comment by Voker57** [comment]
Disagree. They are still not under your control, no reason to have an easy way to boss your religion around. Also, this is a balance change, not FR, and belongs on the forum.

**Comment by ridjack** [comment]
> Also, this is a balance change, not FR

Not sure how you come to that conclusion. It's definitely a new feature; Inquisitors have never been allowed to work in CS.

**Comment by supermerill** [comment]
If you created a modmod and needed some dll code to make it work, it belongs here. 
If you want a gameplay/balance modification of vp, it belongs to the forum.
(imho)

**Comment by Voker57** [comment]
If you want something that changes balance of the game (and requires discussion) it belongs on the forum.
If you want to report a bug or request straightforward feature, github,

**Comment by ridjack** [comment]
Alright then.
