### ISSUE TITLE
happiness crunch

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4367]
people have been reporting this occasionally, i just observed something similar ... from PlayerHappinessStats

![image](https://user-images.githubusercontent.com/1358966/39882503-49afe69e-5484-11e8-9cf0-b8443f4a6340.png)

france on autoplay, wrecked by rebellions right now. interestingly the actual unhappiness didn't increase so much, but the total nevertheless dropped by 30 in the course of a few turns (no war weariness)

here's the plot of the global averages. seems fine as expected.

![image](https://user-images.githubusercontent.com/1358966/39883114-30931bfc-5486-11e8-9c91-04e669e63b49.png)

so apparently the problem is with the sources of happiness. where can i look that up? in the UI the only suspicious bit is the fact that they only get 12 extra happiness from 10 luxuries and a population of 178. is that correct? could that cause the happiness crunch?

![image](https://user-images.githubusercontent.com/1358966/39883273-a4c9a1b2-5486-11e8-874d-a20ab5ffe9da.png)

also: why do we have these strange population thresholds for the luxury multiplier? why not use a fractional multiplier?

**Comment by LoneGazebo** [comment]
I'm not happy with that luxury function either, reworking it soon.

**Comment by Infixo** [comment]
Is this related?
https://forums.civfanatics.com/threads/mucfvp-ee-compatibility-patch.631865/#post-15125028

**Comment by LoneGazebo** [comment]
Shouldn't be - that's just an overflow value. That can really only happen if there's an overflow being fed into the global average function (or enough of them that it spikes the median). So that's not on us, as it doesn't happen in vanilla VP.
