### ISSUE TITLE
Request -- EUI new version changes merged

### ISSUE THREAD

**Issue by ryanmusante** [LoneGazebo/Community-Patch-DLL#4369]
_1. Mod version (i.e Date - 4/23):_
4/30

_3. Feature description_
A **new** version of EUI has been released with performance improvements and bugfixes. 
Request that those parts be added to the EUI version of VP in upcoming patch.

https://forums.civfanatics.com/threads/enhanced-user-interface.512263/page-143#post-15125129
```
Enhanced User Interface v1.29beta17

This beta version includes the following changes:
- performance improvements
- minor tooltip improvements
- minor bug fixes
- ActionInfoPanel: enter key goes to next end blocking task
- ActionInfoPanel: the icon of players who are not yet done with their turn
- flashes in the civilization ribbon
- InGame: shows predictive unit firing range from where the unit will end up
- (red highlight), when checking unit moves with the path indicator while
- right click is pressed or in move mode...

```

**Comment by LoneGazebo** [comment]
I have zero interest in doing this, if someone else (@Infixo et. al.) want to work on it, it'd be appreciated.

G

**Comment by ryanmusante** [comment]
I don't know what actual bug fixes are entailed with the update, but I thought since it involved the user interface, it might be a useful addition.

**Comment by TechpriestEnginseer** [comment]
Considering that I love EUI. I'll take a gander. What's the version that this VP currently use before it got made compatible? I'll do some comparison and look into it.

**Comment by ryanmusante** [comment]
EUI_context.xml in /UI_bc1/Core/ of VP 4-30 is dated 2016-03-21. It would seem likely that the base version VP uses is EUI v1.28g 21mar2016.

**Comment by LoneGazebo** [comment]
1.28c IIRC

**Comment by LoneGazebo** [comment]
maybe it is g- either way it was near the tail-end of bc1's changes before his departure.

**Comment by LoneGazebo** [comment]
I don't recall 100% techpriest - easiest way to know would be to winmerge compare the LUA from 6a with EUI's LUA - if the file is very different, then it is not EUI.

**Comment by Iamblichos** [comment]
How's this coming along? You need some help? I hate EUI, I also hate not using it, so if it's improved...that's at least a net good.

**Comment by TechpriestEnginseer** [comment]
Well, I just got off my college semester. I'm gonna work on adding extra events before this two-year's anniversary of what I "promised" to do. Then, I'll work on this.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer coming out of temporary retirement eh? welcome back! _I knew you couldn't quit us._

**Comment by TechpriestEnginseer** [comment]
@LoneGazebo as I'm working on merging them. What's bc1's views on VP taking over EUI and modifying it again? I remembered a common knowledge in the community was that VP EUI was very different from the normal EUI(No Diplo lua and so on). I think incorporating @Infixo's City View UI would be useful as well into the VP EUI since it is much of a QOL UI compared to EUI's current version right now. However it would mean that for the installer we have to remind users to have SmallAsset set to 1 after they install VP. Any thoughts?

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer bc1 requested we not ship a customized EUI - rather, we have to overwrite stuff (as I do in 6a/6c).

Re: SmallAsset, let's leave @Infixo's out unless there's a method to change that value through the installer - not sure if I can (or want) to mess with .ini files in the installer.

**Comment by TechpriestEnginseer** [comment]
Progress Bar
- [ ] ActionInfoPanel (Surprisingly the most difficult since this is EUI's new feature)
- [X] Art Assets
- [ ] CityBanners
- [ ] CityStatePopup
- [ ] CityView
- [ ] Core
- [ ] FrontEnd
- [ ] GameSetup
- [ ] Improvements
- [ ] InGame
- [ ] LeaderHead
- [X] Options
- [ ] PlotHelp
- [ ] TechTree
- [ ] ToolTips
- [ ] ToolPanel
- [ ] UnitFlagManager
- [ ] UnitPanel
- [ ] YieldIconManager
- [X] General Text File

**Comment by Iamblichos** [comment]
And that LeaderHead was completely rewritten. Gonna be a grind on some of it.

**Comment by LoneGazebo** [comment]
@Iamblichos I wouldn't touch leaderhead - VP doesn't use EUI's leaderhead stuff anyways.

**Comment by Iamblichos** [comment]
Well that’s great.

**Comment by Iamblichos** [comment]
Looks like some good progress by TechPriest.

**Comment by ryanmusante** [comment]
Very nice work!

**Comment by TechpriestEnginseer** [comment]
When I'm about to release a beta version to the public and then he updates his interface. >:(

**Comment by ryanmusante** [comment]
I saw that, beta 18. It appears that he merged city state leaders mod. I'm curious what other bug fixes.

**Comment by LoneGazebo** [comment]
If you do a merge compare between versions @techpriestenginseer you can see what he changed and see if it is worthwhile or not.

**Comment by TechpriestEnginseer** [comment]
It's too worthwhile cuz the "performance improvements" are basically a lot of variable changes. I think I'll wait a week before he re-updates again.

**Comment by ryanmusante** [comment]
I was discussing with Nutty compatibility with CSLII mod + VP. He was working out a beta at one point. Is there plans to incorporate this part of EUI into VP or will it be excluded in lieu of the more important changes and revisions?

**Comment by TechpriestEnginseer** [comment]
Maybe.*

**Comment by ryanmusante** [comment]
This menu navigation looks interesting, what does that entail?
```
bc1 updated Civ5 Enhanced User Interface v1.29beta20

Changes since v1.29beta19:
- easier main menu navigation (LOAD GAME reduced from 2 to 1 step, MOD launch reduced from 6 to 3 steps)
- city states leaders can be enabled or disabled for low end rigs
- fallback for missing city states leaders (e.g. when using 2014 mod)
- improved city banner flag display
- minor fixes
```

**Comment by TechpriestEnginseer** [comment]
Unfortunately, I cannot tell if bc1 is intentionally doing these "performance fixes" on purpose or not, but it means we'll have to rewrite the new ui addition made into the new version which will take longer than just winmerging it.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer I swear he intentionally designs his code to be difficult to tinker with. We had quite a few heated exchanges a few years back and he was adamant that I 'wasn't allowed' to mess with his code. K.

**Comment by ryanmusante** [comment]
For an explanation of the EUI core library and C4DF from a previous conversation, I don't know if this might help some. 

https://forums.civfanatics.com/threads/issue-with-cp-eui.561596/

**Comment by ryanmusante** [comment]
In the beginning the gods created the mods...

https://www.reddit.com/r/civ/comments/20c0p8/this_is_the_enhanced_user_interface_mod_this_will/

> LoneGazebo Lead Designer of Vox Populi
> bc1 is a great modder. Not only has he created an awesome mod, he goes out of his way to design his UI with compatibility for most of the high-use mods such as

**Comment by LoneGazebo** [comment]
@ryanmusante haha, dug too deep.

**Comment by TechpriestEnginseer** [comment]
Since bc1 keeps at sudden intervals updating along with the VP UI additions as well, I will hold this project off until the VP UI is "solid" for at least 3 months.

**Comment by TechpriestEnginseer** [comment]
Progress Bar for EUI v1.29beta28 from v1.28c or v[1.28beta3]
- [ ] **ActionInfoPanel**
- [ ] **Art Assets**
- [ ] CityBanners 
- [ ] **CityStatePopup**
- [ ] CityView
- [ ] **Core**
- [ ] FrontEnd
- [ ] GameSetup
- [ ] Improvements
- [ ] InGame
- [x] ~LeaderHead~
- [ ] Options
- [ ] PlotHelp
- [ ] TechTree
- [ ] ToolTips
- [ ] TopPanel
- [ ] UnitFlagManager
- [ ] UnitPanel (Will never touch this)
- [ ] YieldIconManager
- [ ] General Text File Compatibility
- [ ] Public Testing as 6aa and people saying wow literally no ((bugs))

Ok there's actually a lot added compared to where I was just pulling and requesting. My #1 priroity should be those in bold... hoping this be done within a month before Christmas...

**Comment by ryanmusante** [comment]
![screenshot from 2018-11-24 11-51-57](https://user-images.githubusercontent.com/26808646/48963854-75ecd180-efdf-11e8-8bf1-a76a53b14e96.png)
Thank you!

**Comment by MRS-OBAMA** [comment]
where can i see the progress? i'd like to help although i doubt i can =)

**Comment by TechpriestEnginseer** [comment]
don't worry, the update to the new version aren't exactly news-worthy to be waiting for since they'll just contain performance improvements.

**Comment by MRS-OBAMA** [comment]
Oh, It's because i tried porting for myself the new yieldiconmanager (as the improvement icon were really cute and a nice addition, but there are way too many variables that get switched and moved around so even just winmerging it is hard lol, i'll keep waiting i guess

**Comment by ryanmusante** [comment]
This sounds interesting. 

https://forums.civfanatics.com/resources/civ5-enhanced-user-interface.24303/updates
```
InGame: shows predictive unit firing range from where the unit will end up (red highlight), when checking unit moves with the path indicator while right click is pressed or in move mode

InGame: highlight city working limits for city settlement planning when pressing "x" key or while moving a settler
```
