### ISSUE TITLE
Different luxuries valued vastly differently

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#437]
Forgive me if this is not a bug, and merely just the way AI values different luxuries based on CS quests or "we love the king day."

I was able to trade furs (only copy) for pepper (2), straight up. I then wondered if I could do a trade for nutmeg as well, and...

![2015-07-19_00001](https://cloud.githubusercontent.com/assets/11132095/8768175/415e1306-2e3c-11e5-9990-4db5f8f822f6.jpg)

The disparity between types of luxuries is staggering. With possible returns this great, it adds much more unfun micromanagement to trade diplomacy as every copy should be constantly shopped. Don't know if this is a bug or design.

Edit: Related, might be an actual bug:

![2015-07-19_00002](https://cloud.githubusercontent.com/assets/11132095/8769130/638a3062-2e5b-11e5-815a-527977992bbd.jpg)

No idea why the 2 food grassland is being worked over 3 food coast.

**Comment by LoneGazebo** [comment]
I'm not sure re: the grassland issue. I'll take a look. 

Regarding the trade issue, it is because the AI (I imagine) could get a WLTKD from that resource.

G

**Comment by joosegoose** [comment]
Whoops, meant to put the grassland issue in the production focus issue (just closed).

I figured it had something to do with WLTKD, but didn't know since it's such a large offer. If that's the case, it encourages players to shop around every single turn if the payoff is potentially (and randomly, from the perspective of the player) that large. I would say that's quite undesirable from a tedium perspective, but if it's not a bug I'll leave it alone for now.

**Comment by LoneGazebo** [comment]
It isn't a bug, but if players want to shop they can. The AI does (I taught them that).

G
