### ISSUE TITLE
possible bug in city governor

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4375]
so we have CvCityCitizens::GetPlotValue(CvPlot* pPlot, bool **bUseAllowGrowthFlag**, ...)

but it's called like this:

iValue = GetPlotValue(pLoopPlot, **bWantBest**, iExcessFoodTimes100);

does that make sense?

**Comment by LoneGazebo** [comment]
Hmm...

**Comment by LoneGazebo** [comment]
Looking at the code, I don't even think we need that bool.

**Comment by LoneGazebo** [comment]
Removing it.

**Comment by ilteroi** [comment]
you sure? it seems to me that it's called once to find the worst worked plot and once to find the best unworked plot. so surely some flag is needed?

**Comment by LoneGazebo** [comment]
the bool name is misleading, as the functions they're called in do the sorting, not the value getter. It's just a bad name for a function we don't need.
