### ISSUE TITLE
improvement info for mine says mine doesn't give production?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4378]
* so i have an iron resource (id 0) on a desert hill. look up the matching improvement:

CvImprovementEntry* pImprovement = GC.GetGameImprovements()->GetImprovementForResource(eResource);

and check the yields

pImprovement->GetImprovementResourceYield(eResource, YIELD_PRODUCTION);

problem is, this returns zero. how come? what is the correct way to do a lookup?

* even stranger, apparently the mine would give a boost to science?

![image](https://user-images.githubusercontent.com/1358966/39960127-4d6d9340-561d-11e8-8dd7-61cfa4d048cd.png)

* in the database everything looks good. 1 base hammer per mine, increasing with certain techs.

**Comment by LoneGazebo** [comment]
hmm, not sure. let me see if i can replicate
