### ISSUE TITLE
1 Gold being added wrongly to certain tiles 

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#438]
In my game it has started happening right the turn that I have choose the fifth policy (City Planning).

<img width="680" alt="1" src="https://cloud.githubusercontent.com/assets/13163824/8787430/55145b0a-2f34-11e5-8707-f69ce6ef913f.png">

<img width="680" alt="2" src="https://cloud.githubusercontent.com/assets/13163824/8787438/5c8f23f6-2f34-11e5-8988-23cbef62d9b6.png">

<img width="680" alt="3" src="https://cloud.githubusercontent.com/assets/13163824/8787440/5f622d26-2f34-11e5-9bfc-ab647e9adc77.png">

<img width="680" alt="4" src="https://cloud.githubusercontent.com/assets/13163824/8787446/6401751c-2f34-11e5-9e05-0ae08d925fe4.png">

and isn't only visual
<img width="680" alt="5" src="https://cloud.githubusercontent.com/assets/13163824/8787447/678a5ea6-2f34-11e5-91c9-27478e248774.png">

Further testing:

Exiting the game and clearing the cache haven't solved the problem.
Chosen any policy during turn 72 shows the additional gold in pastures, camps and farms over wheat.
Skipping policy pick with Allow policy saving  show it during turn 73 anyways.

Save included here http://forums.civfanatics.com/attachment.php?attachmentid=396640&d=1437431130

**Comment by LoneGazebo** [comment]
I've worked on this a bit in the plot.cpp, so we'll see if it is fixed in the next version.

G

**Comment by Mitchsp** [comment]
Still happening in 7/21 version.

**Comment by LoneGazebo** [comment]
Same thing- send me your save game.
