### ISSUE TITLE
Tooltip - Castle - Food from Fealty>Nobility not displaying

### ISSUE THREAD

**Issue by Vortok** [LoneGazebo/Community-Patch-DLL#4381]
_1. Mod version (i.e Date - 4/23):_
4/30

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The +1 Happiness from the policy shows up on the tooltip, but the Food does not (appears to still actually be giving Food).  Potential Food from an event (Fealty + war?), when selected, did show up on the tooltip.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Edaka** [comment]
@Vortok Do you play with EUI? I myself use EUI and Improved City View for VP, if that matters, and I see the food.

**Comment by Vortok** [comment]
I don't use EUI.  Given that this was on a pretty old version, I'm unsure if the issue would still be there.  I don't have 4-30 installed anymore, so can't load the save.

I apologize for the weaksauce report, lol.  Barely included any useful info.  Not even the mod list.

[Babylon_VP_4-30.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2342201/Babylon_VP_4-30.zip)

I believe that's my save.  Unfortunately, I had a few minor mods running, but they're not too UI intrusive.  It's been awhile, but I think it was Infoaddict (v 22), Speedy Starting Settler (v 1), and Faster Aircraft Animations.
