### ISSUE TITLE
Stuttering movement animations

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#4383]
_1. Mod version:_
4-30-4

_2. Mod list:_
IGE

_3. Error description:_ 
When moving with animations on, before the final move the unit first comes to a complete stop, then moves to the destination tile (might be related to the change to fortification).

-----------------------------------

[Gif](https://i.imgur.com/DvTH8dd.mp4) 
It's a bit fast, but you can tell the unit has to make a complete stop before reaching it's destination. If the unit can move across multiple tiles, it only stops on the second to last tile.

**Comment by Iamblichos** [comment]
Will be fixed in next release.
