### ISSUE TITLE
AI not improving Strategic/luxury resources outside of workable area 

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#4385]
_1. Mod version:_
4-30-4

_2. Mod list:_
IGE

_3. Error description:_ 
If a resource is pillaged outside of a city's workable area, the AI doesn't seem to make an attempt to repair/replace it.

---------------------------
Both of these tiles have been unimproved for dozens of turns, With the Aztec worker staying put in their citadel... 
![](https://i.imgur.com/aacQXKZ.png)

and Ethiopia making no effort to reimprove their pearls (they may never have been improved though).
![](https://i.imgur.com/G7M0CJX.png)

**Comment by bigcat88** [comment]
With pearls the same was in my last game too
