### ISSUE TITLE
Little Help

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#4388]
I'm trying to finish up rewriting the DoNearbyUnitPromotions function to improve performance. Right now I've written this code in CvPlot:

```
bool CvPlot::IsInWarSawPactTerritory(PlayerTypes eSovietPlayer, const CvUnit* pUnit) const
{
	if (eSovietPlayer == NO_PLAYER)
		return false;

	if (!GET_PLAYER(eSovietPlayer).GetPlayerTraits()->IsWarsawPact())
		return false;

	CvPlayerAI& kPlayer = GET_PLAYER(eSovietPlayer);
	if (GET_TEAM(pUnit->getTeam()).isAtWar(GET_TEAM(kPlayer.getTeam()).GetID()))
	{
		if ((getTeam() != NO_TEAM && getTeam() == GET_TEAM(kPlayer.getTeam()).GetID()) || (getOwner() != NO_PLAYER && GET_PLAYER(getOwner()).isMinorCiv() && GET_PLAYER(getOwner()).GetMinorCivAI()->GetFriendshipLevelWithMajor(kPlayer.GetID()) >= 1)
			|| (getOwner() != NO_PLAYER && GET_PLAYER(getOwner()).HasSameIdeology(kPlayer.GetID()) && GET_TEAM(getTeam()).IsAllowsOpenBordersToTeam(GET_TEAM(kPlayer.getTeam()).GetID())))
		{
			return true;
		}
	}
	return false;
}
```

Basically the following criteria:

1) is enemy unit in Soviet Territory
2) is enemy unit in a minor territory that is allied with Soviet
3) is enemy unit in a territory that has same ideology as Soviet (and has open borders with Soviet).

When I call this code from CvUnit, I need to cache eSovietPlayer so I don't have to loop through all players to see if they exist in the game. Either in CvPlayer or CvPlayerTraits I would think I could create a variable when that trait is active to cache the player. Something like:

```
PlayerTypes CvPlayer::SetSovietPlayer()
{
    if(GetPlayerTraits()->IsWarSawPact())
    {
        m_eSovietPlayer = GetID();
     }
}
```

Would that do the trick?

**Comment by ilteroi** [comment]
i don't understand what you are trying to do but GET_TEAM(kPlayer.getTeam()).GetID()) is funny in any case :)

**Comment by Iamblichos** [comment]
I want to track if a enemy unit is in Soviet Territory. Here is the original code which if Stalin is in my game, it is a performance problem (for reference see DoNearbyUnitPromotions in your code):

```
if(pkPromotionInfo->IsEnemyLands())
				{
					for(int iJ = 0; iJ < MAX_PLAYERS; iJ++)
					{
						CvPlayerAI& kPlayer = GET_PLAYER((PlayerTypes)iJ);
						if(kPlayer.GetPlayerTraits()->IsWarsawPact())
						{
							if(GET_TEAM(getTeam()).isAtWar(GET_TEAM(kPlayer.getTeam()).GetID()))
							{
								if((pPlot->getTeam() != NO_TEAM && pPlot->getTeam() == GET_TEAM(kPlayer.getTeam()).GetID()) || (pPlot->getOwner() != NO_PLAYER && GET_PLAYER(pPlot->getOwner()).isMinorCiv() && GET_PLAYER(pPlot->getOwner()).GetMinorCivAI()->GetFriendshipLevelWithMajor(kPlayer.GetID()) >= 1) || (pPlot->getOwner() != NO_PLAYER && GET_PLAYER(pPlot->getOwner()).HasSameIdeology(kPlayer.GetID()) && GET_TEAM(pPlot->getTeam()).IsAllowsOpenBordersToTeam(GET_TEAM(kPlayer.getTeam()).GetID())))
								{
									setHasPromotion(eLoopPromotion, true);
								}
								else
								{
									setHasPromotion(eLoopPromotion, false);
								}
							}
							else
							{
								if(HasPromotion(eLoopPromotion))
								{
									setHasPromotion(eLoopPromotion, false);
								}
							}
						}
					}
				}
```

**Comment by Iamblichos** [comment]
Two problems, DNUP (DoNearbyUnitPromotions function) is called in SetXY...so every time a unit moves, assuming Stalin is an active player, we loop through promotions (I can cache that in PlayerTraits no problem), and then we loop through all players to see if they are active, every time on unit movement. No Bravo.

**Comment by Iamblichos** [comment]
Code in CvPlayer:
```
PlayerTypes CvPlayer::GetSovietPlayer() const
{
	return m_eSovietPlayer;
}
void CvPlayer::SetSoveietPlayer(PlayerTypes ePlayer)
{
	if (GetSovietPlayer() != ePlayer)
	{
		m_eSovietPlayer = ePlayer;
	}
}
bool CvPlayer::IsInWarSawPactTerritory(const CvPlot* pPlot, const CvUnit* pUnit) const
{

	if (!pUnit || !pPlot || pPlot->getOwner() == NO_PLAYER)
		return false;

	PlayerTypes ePlayer = (PlayerTypes)GetSovietPlayer();
	if (ePlayer = NO_PLAYER)
		return false;

	CvPlayerAI& kPlayer = GET_PLAYER(ePlayer);

	PlayerTypes ePlotOwner = pPlot->getOwner();
	if (GET_TEAM(pUnit->getTeam()).isAtWar(GET_TEAM(kPlayer.getTeam()).GetID()))
	{
		if ((GET_TEAM(GET_PLAYER(ePlotOwner).getTeam()).GetID() == GET_TEAM(kPlayer.getTeam()).GetID()) || (GET_PLAYER(ePlotOwner).isMinorCiv() && GET_PLAYER(ePlotOwner).GetMinorCivAI()->GetFriendshipLevelWithMajor(kPlayer.GetID()) >= 1)
			|| (GET_PLAYER(ePlotOwner).HasSameIdeology(kPlayer.GetID()) && GET_TEAM(GET_PLAYER(ePlotOwner).getTeam()).IsAllowsOpenBordersToTeam(GET_TEAM(kPlayer.getTeam()).GetID())))
		{
			return true;
		}
	}
	return false;
}
```

code in DoNearbyUnitPromotions function:
if(pkPromotionInfo->IsEnemyLands())
				{
					CvPlayer& pUnitPlayer = GET_PLAYER(getOwner());
					if (pUnitPlayer.IsInWarSawPactTerritory(pPlot, this))
					{
						setHasPromotion(eLoopPromotion, true);
					}
					else
					{
						setHasPromotion(eLoopPromotion, false);
					}

**Comment by ilteroi** [comment]
well i'm still not sure, but i can tell you this:

* IsInWarSawPactTerritory() should be a member of CvUnit, not CvPlot
* what is the relation between eSovietPlayer, the plot owner and the unit owner?
* SetSovietPlayer() does not make sense at all
* what you can definitely do: don't iterate all players but only those the unit is at war with. available via .... wait for it .... GetPlayersAtWarWith()
* the loop over the promotions is annoying. you should introduce a global flag which disables the loop if there are no such promotions in the game.

**Comment by Iamblichos** [comment]
So now in CvPlayer.cpp I have something like this on CvPlayer::init:

```
if (GetPlayerTraits()->IsWarsawPact())
		{
			SetSoveietPlayer((PlayerTypes)m_eID);
			if (GetPlayerTraits()->GetEnemyWarSawPactPromotion() != NO_PROMOTION)
			{
				for (int iJ = 0; iJ < MAX_PLAYERS; iJ++)
				{
					CvPlayerAI& kPlayer = GET_PLAYER((PlayerTypes)iJ);
					kPlayer.SetEnemyWarSawPactPromotion((PromotionTypes)GetPlayerTraits()->GetEnemyWarSawPactPromotion());
				}
			}
		}
```
the related call in CvUnit::DoNearbyUnitPromotions can be reduced to this:
```
CvPlayer& pUnitPlayer = GET_PLAYER(getOwner());
		if (pUnitPlayer.IsInWarSawPactTerritory(pPlot, this))
		{
			setHasPromotion(pUnitPlayer.GetEnemyWarSawPactPromotion(), true);
		}
		else
		{
			setHasPromotion(pUnitPlayer.GetEnemyWarSawPactPromotion(), false);
		}
```

No more looping...we just loop one time on CvPlayer::init to have the promotion ready to be set when we need it.

Haven't tested this out yet, all hypothetical.

**Comment by Iamblichos** [comment]
If I get it to work, I'll tighten it up with GetPlayersAtWarWith().

**Comment by Iamblichos** [comment]
Okay this might be a thousand times easier:

```
CvPlayer& pUnitPlayer = GET_PLAYER(getOwner());
		const std::vector<PlayerTypes>& vEnemies = pUnitPlayer.GetPlayersAtWarWith();
		for (std::vector<PlayerTypes>::const_iterator it = vEnemies.begin(); it != vEnemies.end(); ++it)
		{
			CvPlayer& kPlayer = GET_PLAYER(*it);
			if (kPlayer.GetPlayerTraits()->IsWarsawPact())
			{
				if ((pPlot->getTeam() != NO_TEAM && pPlot->getTeam() == GET_TEAM(kPlayer.getTeam()).GetID())
					|| (pPlot->getOwner() != NO_PLAYER && GET_PLAYER(pPlot->getOwner()).isMinorCiv() && GET_PLAYER(pPlot->getOwner()).GetMinorCivAI()->GetFriendshipLevelWithMajor(kPlayer.GetID()) >= 1)
					|| (pPlot->getOwner() != NO_PLAYER && GET_PLAYER(pPlot->getOwner()).HasSameIdeology(kPlayer.GetID()) && GET_TEAM(pPlot->getTeam()).IsAllowsOpenBordersToTeam(GET_TEAM(kPlayer.getTeam()).GetID())))
				{
					setHasPromotion((PromotionTypes)kPlayer.GetPlayerTraits()->GetEnemyWarSawPactPromotion(), true);
				}
				else
				{
					setHasPromotion((PromotionTypes)kPlayer.GetPlayerTraits()->GetEnemyWarSawPactPromotion(), false);
				}
			}
		}
```

**Comment by Iamblichos** [comment]
@ilteroi Removed all those other pieces of code. Just this code in DoNearbyUnitPromotions function:

CvPlayer& pUnitPlayer = GET_PLAYER(getOwner());
		if(pUnitPlayer.IsAtWar())
		{
			const std::vector<PlayerTypes>& vEnemies = pUnitPlayer.GetPlayersAtWarWith();
			for (std::vector<PlayerTypes>::const_iterator it = vEnemies.begin(); it != vEnemies.end(); ++it)
			{
				CvPlayer& kPlayer = GET_PLAYER(*it);
				if (kPlayer.GetPlayerTraits()->IsWarsawPact())
				{
					if ((pPlot->getTeam() != NO_TEAM && pPlot->getTeam() == GET_TEAM(kPlayer.getTeam()).GetID())
						|| (pPlot->getOwner() != NO_PLAYER && GET_PLAYER(pPlot->getOwner()).isMinorCiv() && GET_PLAYER(pPlot->getOwner()).GetMinorCivAI()->GetFriendshipLevelWithMajor(kPlayer.GetID()) >= 1)
						|| (pPlot->getOwner() != NO_PLAYER && GET_PLAYER(pPlot->getOwner()).HasSameIdeology(kPlayer.GetID()) && GET_TEAM(pPlot->getTeam()).IsAllowsOpenBordersToTeam(GET_TEAM(kPlayer.getTeam()).GetID())))
					{
						setHasPromotion(kPlayer.GetPlayerTraits()->GetEnemyWarSawPactPromotion(), true);
					}
					else
					{
						setHasPromotion(kPlayer.GetPlayerTraits()->GetEnemyWarSawPactPromotion(), false);
					}
				}
			}
		}


Just cached out the promotion as a part of the Trait. No looping for promotions. Just loop vEnemies. Much cleaner.

**Comment by Iamblichos** [comment]
Not sure if I need to do that first check for IsAtWar() as that loops through all teams. Lemme know.

**Comment by LoneGazebo** [comment]
Considering vEnemies is a list of players, it'll just return 0 (and loop out), so it's unnecessary.

G

**Comment by Iamblichos** [comment]
Thanks.
