### ISSUE TITLE
Probably won't work

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#4389]
in 5-14 merge:

UPDATE Building_ClassesNeededInCity
Set BuildingClassType = 'BUILDINGCLASS_HOTEL'
WHERE BuildingType = 'BUILDING_TOURIST_CENTER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_NATIONAL_WONDERS' AND Value= 1 );

does that buildtype exist in database yet, I don't think so. Probably need to insert it.

**Comment by Iamblichos** [comment]
@LoneGazebo did you see this one? I said database but I meant table. I don’t think the tourist center exists in that table yet.

**Comment by LoneGazebo** [comment]
Yes.
