### ISSUE TITLE
We love the king day not working, and question about unhappiness growth modifier

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#439]
Wasn't a temporary error, WLTKD not worked in previous or following turns.

<img width="680" alt="sin titulo" src="https://cloud.githubusercontent.com/assets/13163824/8814984/838d853a-3013-11e5-9be6-23dde8ec3630.png">

<img width="680" alt="sin titulo2" src="https://cloud.githubusercontent.com/assets/13163824/8815033/fb71ad56-3013-11e5-82e3-cb88ec4c3944.png">

related to https://github.com/LoneGazebo/Community-Patch-DLL/issues/438 , here can be seen the only tile where 1 gold is appearing, isn't happening in others pastures or improvements in general.

The question about unhappiness, every point is giving -1% to others yields (Science, Faith, Culture, Gold), but -2% to Growth. Is some recent change or a bug?

**Comment by LoneGazebo** [comment]
WLTKD does not apply if you are unhappy. That is part of the base code (i.e. I haven't changed it).

The doubling of unhappiness bonuses from Growth is a bug.

G
