### ISSUE TITLE
city governor, again

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4391]
i'm seeing a lot of revolts in my test games. which is good, but then many of them seems to be avoidable and only happen because AI is a bit challenged when fighting unhappiness.

example: tours is suffering from poverty and illiteracy. no boredom. yet they build a zoo.

![image](https://user-images.githubusercontent.com/1358966/40159914-ad257bae-59ab-11e8-9b5c-167446da2191.png)

example: troyes has three main sources of unhappiness, total empire is at -24. yet they chose a growth building.

![image](https://user-images.githubusercontent.com/1358966/40160017-185705b4-59ac-11e8-8407-53eddae87c0f.png)

logs here: [france-prod.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2011855/france-prod.zip)

also, all cities have the "manual specialist control" checkmark set after autoplay. no specialists. is that be design?

**Comment by LoneGazebo** [comment]
Hospitals do help with poverty, but I’ll look.

**Comment by LoneGazebo** [comment]
@ilteroi 
I think it's an issue of the RNG selector:

	```
Line 1418: 321, France, Tours, POST: Building, Public School, 16058, 14
	Line 1419: 321, France, Tours, POST: Building, Zoo, 4422, 14
	Line 1420: 321, France, Tours, POST: Building, Grocer, 2891, 7
	Line 1421: 321, France, Tours, POST: Building, Constabulary, 2862, 7
	Line 1422: 321, France, Tours, POST: Building, Seaport, 2388, 20
```

Public School was far and away the best option (and the city knew that), but it chose Zoo because of the RNG selector for 'choose from top X). It'd be nice if we had a method within that RNG system to automatically select the top value IF it was significantly higher than the other elements in the list.

**Comment by ilteroi** [comment]
no problem

**Comment by ilteroi** [comment]
did you see this in ChooseFromTopChoices()? does that make sense?

```
		// Random roll up to total weight
		if (GC.getGame().isNetworkMultiPlayer() || GC.getGame().isReallyNetworkMultiPlayer())
		{
			elem = m_pItems[0];
			return elem.m_Element;
		}
```

**Comment by LoneGazebo** [comment]
I think that was intended to skip the RNG and just use the top value for MP?

**Comment by ilteroi** [comment]
sure. but do we want that?

**Comment by LoneGazebo** [comment]
@ilteroi if the RNG is MP safe now (seems to be) we can remove that.

**Comment by tu-79** [comment]
"It'd be nice if we had a method within that RNG system to automatically select the top value IF it was significantly higher than the other elements in the list."

You may weight the chance for picking one option based on its relative position in the order list. For example, consider 6 ordered items. 1st to 6th. Get the base as 1 + 2 + 3 + 4 + 5 + 6 = 21. Then, give a RND number between 1 and 21. Depending on the dice, choose the following option:
1st: 1 - 6
2nd: 7 - 11
3rd: 12 - 15
4th: 16 - 18
5th: 19 - 20
6th: 21

There's always a small chance to pick the worse option, but it's very unlikely, while the better options are chosen more often.

**Comment by ilteroi** [comment]
this "weighted pick" was exactly how it worked. 

but now i additionally added a cutoff if the n-th element is less than half as good as the one before.

**Comment by tu-79** [comment]
> but now i additionally added a cutoff if the n-th element is less than half as good as the one before.
I don't mind AI making mistakes from time to time, if it's very minor. Why don't you just consider a cutoff at a fixed percentage of the list? If the list has N elements, cut the last 0.3 * N elements, when elements > 1. I think it would be safer than what you are trying to do. It also replicates human behaviour, as the longer the list the fewer attention we pay to it.
