### ISSUE TITLE
RNG Issue (?) with nutmeg and Arabian UA

### ISSUE THREAD

**Issue by pzapza** [LoneGazebo/Community-Patch-DLL#4392]
_1. Mod version (i.e Date - 4/23):_
4-30

_2. Mod list (if using Vox Populi only, leave blank):_
1. Unit Path Viewer (v 10) 
2. UI - Improved City View (Vox Populi EUI) (v 10)
3. UI - Religion Spread (Vox Populi) (v 1.0)
4. UI - Filters in Trade Route Overview (Vox Populi) (v 1)
5. UI - Show XP in Military Overview (v 2)

_3. Error description:_ 
RNG Issue?
- Players reported only getting great writers as arabia from it's UA. I can confirm, got 10x great writer points in a row, never anything else, in multiplayer. Tradition start.
- Three out of three games i had only one type of ressource (didnt keep track which one, i think it was always nutmeg) spawning when founding a city as indonesia. SIDENOTE (probably different bug): It happened twice in those games, that founding an indonesian city didn't spawn a luxury at all, although plenty of tiles.
(See below for screenshots)

.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![indobug](https://user-images.githubusercontent.com/38469319/40189451-cd1d0336-59fc-11e8-91ca-fb8fd762a12f.jpg)
![indobug2](https://user-images.githubusercontent.com/38469319/40189607-3141d04e-59fd-11e8-9b95-360ad7d9929d.jpg)

**Comment by ilteroi** [comment]
well, the luxury placement code has some problems, that's for sure.

need to check the great people issue

**Comment by ilteroi** [comment]
fixed

**Comment by Iamblichos** [comment]
@ilteroi I went through the rest of them in loops and fixed them. Pushed in my branch. Commit: 5df8c6f

**Comment by woolymuffler** [comment]
Just to clarify, the Great People (Arabia UA) is also fixed? Or was that in fact related to the Indonesia Resource Spawn issue? Thanks!

**Comment by Iamblichos** [comment]
Both.

**Comment by woolymuffler** [comment]
Awesome! Thanks for your work!
