### ISSUE TITLE
903 food from terrain

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#4395]
@ilteroi no way can we get to 903 food from terrain. Something is off:

![20180517185519_1](https://user-images.githubusercontent.com/14372214/40209326-21c61a42-5a04-11e8-9488-4f3b08a6da71.jpg)

**Comment by LoneGazebo** [comment]
Loaded a save? What's the story?

**Comment by Iamblichos** [comment]
Auto game. Stopped at turn 100 quick.

**Comment by Iamblichos** [comment]
Been seeing it ever since he did the calculate yield fast in Cvplot. But it only happens to one civ in the game. Everybody else is normal.

**Comment by Iamblichos** [comment]
I noticed that in all the CvPlot.cpp calculate(nature)yieldfast we are using a type qualifier (const) for pOwningCity but in UpdateYieldFast we aren't:

void CvPlot::updateYieldFast(CvCity* pOwningCity, const CvReligion* pMajorityReligion, const CvBeliefEntry* pSecondaryPantheon)

Would that be an issue?

**Comment by LoneGazebo** [comment]
I've run dozens of tests and haven't seen this at all - you sure there isn't a modmod conflict? Is it happening on a specific turn?

That const shouldn't matter.

**Comment by Iamblichos** [comment]
Well I only recently started seeing this. I don't think it is a mod conflict since I control all my stuff which is all database entries no lua stuff other than what is in the VP. Its never civ specific. It'll be some Civ in the game (and only one). I might compile to the non-43 and see if that has anything to do with it.

**Comment by LoneGazebo** [comment]
I've been debugging on non-43 and haven't seen it. Might be a bad cache for 43 civs, maybe?

**Comment by Iamblichos** [comment]
I'll try non-43 in the morning and see what happens.

**Comment by ilteroi** [comment]
it's improbable that my changes would cause this. of course i have to say that ... but all i did was pull some lookups out of the innermost loop.

**Comment by Iamblichos** [comment]
No indictment my friend. I looked at your code all night and don't see an issue with it. I'm wondering now if it's the 43 civ thing, which if it is, we have a problem somewhere else...

**Comment by ilteroi** [comment]
it's entirely possible that there's another (rare) bug there, which you managed to hit.

in fact i'm pretty sure there's something going on. put a breakpoint on the "houston, we have a problem" line and you'll see.

**Comment by Iamblichos** [comment]
Do I need to build to Debug mode to hit that String?

**Comment by Iamblichos** [comment]
Reproduced it again with non-43 civs (never hit that break point though):

Here's Ethiopia's empire:

![20180518080643_1](https://user-images.githubusercontent.com/14372214/40236315-c2ed52b4-5a72-11e8-88f2-f1174886a33a.jpg)

Lailebela looks normal:

![20180518080707_1](https://user-images.githubusercontent.com/14372214/40236334-d99bab0a-5a72-11e8-876d-6c200659bc1f.jpg)

As does the Capital:

![20180518080724_1](https://user-images.githubusercontent.com/14372214/40236345-e20fc1ae-5a72-11e8-81d5-90e7f0be10bf.jpg)

Not Harrar and Harrar is about to explode:

![20180518080735_1](https://user-images.githubusercontent.com/14372214/40236357-ebd839e6-5a72-11e8-927f-7176b44f1e3c.jpg)

Gonna trace it back a few turns but it looks to happen right when Ethiopia founded a religion.

**Comment by Infixo** [comment]
@Iamblichos Can you post a save-file for non-43? Also, which VP, 4-30-4 or the current master?

**Comment by Iamblichos** [comment]
No variables that you don't have. Just switch cases in BuilderTaskingAI and a new function in HomelandAI ExecuteWorkerSeaMoves (like ExecuteWorkerMove). Stuff that is irrelevant to the problem AFAIK.

**Comment by Infixo** [comment]
Should be save file compatible then.

**Comment by Iamblichos** [comment]
I take that back I did recently add a variable in CvUnit for a culturebombunit (like the artist from pre-GnK), which I haven't made that commit yet.

**Comment by Iamblichos** [comment]
Started a fresh auto game hit the debugger "Houston, we have a problem"

**Comment by Iamblichos** [comment]
at

**Comment by Iamblichos** [comment]
It happened right as I suspect, when the first civ founded a religion.

**Comment by LoneGazebo** [comment]
Weird that I can’t replicate.

**Comment by LoneGazebo** [comment]
I’ll try again.

**Comment by Infixo** [comment]
I ran few games (using current master) for 100-150 turns and I can't get it neither.

**Comment by Iamblichos** [comment]
Very frustrating. It's very possible I have something screwed up. Or I have something that is incompatible with the change. At any rate, I will find it.

**Comment by Iamblichos** [comment]
I'm using this for MaxActiveReligions which is more than VP...any chance that could cause an issue:

UPDATE Worlds
SET MaxActiveReligions = '4'
WHERE Type = 'WORLDSIZE_TINY';

UPDATE Worlds
SET MaxActiveReligions = '6'
WHERE Type = 'WORLDSIZE_SMALL';

UPDATE Worlds
SET MaxActiveReligions = '8'
WHERE Type = 'WORLDSIZE_STANDARD';

UPDATE Worlds
SET MaxActiveReligions = '10'
WHERE Type = 'WORLDSIZE_LARGE';

UPDATE Worlds
SET MaxActiveReligions = '12'
WHERE Type = 'WORLDSIZE_HUGE';

**Comment by LoneGazebo** [comment]
Shouldn’t matter. I’ll do some intensive testing today.

**Comment by Iamblichos** [comment]
I have an idea of what it might be. I wonder if there is an order of operations problem. I’m away for the day. Thinking here relationship between Building processes improvement yield changes, religion/pantheon founding.

**Comment by LoneGazebo** [comment]
@ilteroi does your fast cache stuff for city yields update properly when a tile improvement's yields change from techs, golden ages, adjacent tile changes, etc.? I'm seeing the 'houston we have a problem' issue with SetWorkingPlot and ChangeBaseYieldFromTerrain, as the function is removing more yields from the tile than exist on the tile.

**Comment by Iamblichos** [comment]
@LoneGazebo I have more beliefs than VP, some common, some not. I play with a higher max religion count. Nothing extraordinary, all stuff that is in the DLL.

**Comment by LoneGazebo** [comment]
@Iamblichos I get that - I'm just trying to pinpoint if it's a belief that grants city yield change or tile yield change that's causing it. We need a constant in this to start figuring out what is causing the issue.

**Comment by Iamblichos** [comment]
I give you the tables, if you want more I'll give you more:

Belief_BuildingClassHappiness
Belief_BuildingClassYieldChanges
Belief_CityYieldChanges
Belief_CityYieldPerXTerrainTimes100
Belief_EraFaithUnitPurchase
Belief_FeatureYieldChanges
Belief_GreatPersonExpendedYield
Belief_ImprovementYieldChanges  <---I wonder about this one...
Belief_MaxYieldModifierPerFollower
Belief_ResourceYieldChanges
Belief_SpecialistYieldChanges
Belief_TerrainYieldChanges
Belief_YieldChangeAnySpecialist
Belief_YieldChangeNaturalWonder
Belief_YieldChangeWorldWonder
Belief_YieldChangePerForeignCity
Belief_YieldChangePerXForeignFollowers
Belief_YieldChangeTradeRoute
Belief_YieldFromHost
Belief_YieldFromKills
Belief_YieldFromProposal
Belief_YieldFromWLTKD

**Comment by LoneGazebo** [comment]
@Iamblichos I'm specifically asking about the religious beliefs in the city that messed up in the game above...is that same belief the culprit in each of your cases?

**Comment by Iamblichos** [comment]
Ah! Yes, I think so....Belief_ImprovementYieldChanges, Belief_ResourceYieldChanges. But I need to run another test game to verify. This one:

UPDATE Language_en_US
SET Text = '+1 [ICON_FOOD] Food and +2 [ICON_GOLD] Gold for each Farm, Banana, Citrus, Spice, Salt, and Wheat resource'
WHERE Tag = 'TXT_KEY_BELIEF_SUN_GOD';

**Comment by Iamblichos** [comment]
How about this:
old: void CvPlot::updateYield()
int iNewYield = calculateYield((YieldTypes)iI

new: void CvPlot::updateYieldFast
int iNewYield = calculateYieldFast(eYield,false,pOwningCity,pMajorityReligion,pSecondaryPantheon);

no iteration around iI.

**Comment by LoneGazebo** [comment]
@Iamblichos that shouldn't matter, as eYield == (YieldTypes)iI.

**Comment by Iamblichos** [comment]
I don't get it....I'm comparing the code to the old way and I don't see why this shouldn't work or trigger the Houston thing.

**Comment by Iamblichos** [comment]
Just ran another auto-game same pantheon that sun god one that gives +1 [ICON_FOOD] Food and +2 [ICON_GOLD] Gold for each Farm, Banana, Citrus, Spice, Salt, and Wheat resource.

**Comment by LoneGazebo** [comment]
@Iamblichos my best guess is that, somewhere, the cache isn't getting updated as it should, so...

worker builds improvement and city starts working - +3 gold from terrain
something (i.e. belief) increases improvement to +4 gold, but cache remains at +3 gold
city stops working tile, gets real value of 4 gold and subtracts that from city value, so now -1 (Houston)

**Comment by Iamblichos** [comment]
I removed all citizens from plots and city has +162 gold from terrain and +72 food, only city plot is worked. It actually has more gold when the city doesn't work any plots and only the city plot is worked!

**Comment by Iamblichos** [comment]
Call stack on break:
![image](https://user-images.githubusercontent.com/14372214/40259568-3858b234-5abc-11e8-8155-94a8eaffcb4b.png)

**Comment by LoneGazebo** [comment]
very strange

**Comment by Iamblichos** [comment]
Worse. It snow balls because it gets more gold and more food from terrain every turn regardless if there is a new plot to work or if an improvement is built. I wonder if this also could have something to do with your large autosaves late game?

**Comment by Iamblichos** [comment]
Question if it’s going -1 and Houston why would terrain being increasing or does that entail what I see in city view screen just mean that it has no idea what the real value ought to be?

**Comment by LoneGazebo** [comment]
@Iamblichos the value in the city screen should be mirrored, not sure why it's not showing the negative value.

**Comment by Iamblichos** [comment]
I wonder if m_aiYield is getting updated properly before we do this:

pOwningCity->ChangeBaseYieldRateFromTerrain(eYield, getYield(eYield) - iOldYield);

Ran another autogame, it's that same darn pantheon everytime.

**Comment by Iamblichos** [comment]
So it’s not just food, it’s any yield. Russia in the Renaissance era had 6 great works, conquered some cities and had -4 tourism.

**Comment by LoneGazebo** [comment]
>I wonder if m_aiYield is getting updated properly before we do this:

Not sure.

**Comment by Padre19** [comment]
My game. Idonesian capital 350 prod in Industrial era. 15 tech ahead.( prince ).

**Comment by Iamblichos** [comment]
Well I wish I had good news but I don't. But here's a possible telltale sign. Again, it's the same pantheon as before that causes the problem, and only in Cities that have wheat related to that pantheon.

+1 [ICON_FOOD] Food and +2 [ICON_GOLD] Gold for each Farm, Banana, Citrus, Spice, Salt, and Wheat resource.

So a wheat tile gets a food change and a gold change for BOTH being a farm and for being wheat. I'm not certain the code is handling that right. I bet if I were to remove Farm from that pantheon, I might not have an issue, but it is still a principled problem. This also probably why it's not readily apparent in standard VP, as you probably don't have a condition like that.


Things don't look as crazy though:

![20180519064557_1](https://user-images.githubusercontent.com/14372214/40268377-c9bb8312-5b31-11e8-9c7b-74693287ec7c.jpg)
Food should be in the 50's.

Gold is worse though:

![20180519064611_1](https://user-images.githubusercontent.com/14372214/40268389-fdf4463c-5b31-11e8-8c04-d78991c4ca3c.jpg)

Another city with a wheat all citizens removed:
![20180519064947_1](https://user-images.githubusercontent.com/14372214/40268403-3b0d5b6c-5b32-11e8-8f7e-a57c4fe93d86.jpg)
26 gold from terrain? should be 1.

**Comment by Iamblichos** [comment]
God I feel like an idiot...I send you guys on a run around here. I have wheat, bananas, and citrus in the database Belief_ResourceYieldChanges twice for food and gold. I bet that's the issue. Damn. mia culpa.

**Comment by LoneGazebo** [comment]
@iamblichos

Possibly, but why would I be seeing ‘Houston’ on standard VP?

**Comment by Iamblichos** [comment]
I see that too but later than the religion stuff kicking off and for other yields. I think we have two different problems here. Gold and food explosion is related to my blunder. I wish the database check would throw up a problem when something like that occurs for a redundant database entry but it doesn’t.

And then I think the Houston thing is happening for something else, more subtle and I’m seeing that issue for a variety of yields unrelated to the OP. 

Running some more tests to confirm I have the OP fixed.

**Comment by Iamblichos** [comment]
Well...nope...still there. Damn.

**Comment by Iamblichos** [comment]
BuilderTaskinAI VP:
```
UpdateCurrentPlotYields(pPlot);

		AddRouteDirectives(pUnit, pPlot, iMoveTurnsAway);
		AddImprovingResourcesDirectives(pUnit, pPlot, iMoveTurnsAway);
		AddImprovingPlotsDirectives(pUnit, pPlot, iMoveTurnsAway);
		if (pUnit->AI_getUnitAIType() == UNITAI_WORKER)
		{
			AddChopDirectives(pUnit, pPlot, iMoveTurnsAway);
			AddScrubFalloutDirectives(pUnit, pPlot, iMoveTurnsAway);
			AddRepairTilesDirectives(pUnit, pPlot, iMoveTurnsAway);
			AddRemoveRouteDirectives(pUnit, pPlot, iMoveTurnsAway);
		}
```

My Working Solution:

```
UpdateCurrentPlotYields(pPlot);
		switch(pPlot->getDomain())
		{
		case DOMAIN_LAND:
			if (pUnit->getDomainType() == DOMAIN_LAND && pUnit->getUnitInfo().GetUnitAIType(UNITAI_WORKER))
			{
				AddRouteDirectives(pUnit, pPlot, iMoveTurnsAway);
				AddImprovingResourcesDirectives(pUnit, pPlot, iMoveTurnsAway);
				AddImprovingPlotsDirectives(pUnit, pPlot, iMoveTurnsAway);
			}
			if (pUnit->AI_getUnitAIType() == UNITAI_WORKER && pUnit->getDomainType() == DOMAIN_LAND)
			{
				AddChopDirectives(pUnit, pPlot, iMoveTurnsAway);
				AddScrubFalloutDirectives(pUnit, pPlot, iMoveTurnsAway);
				AddRepairTilesDirectives(pUnit, pPlot, iMoveTurnsAway);
				AddRemoveRouteDirectives(pUnit, pPlot, iMoveTurnsAway);
			}
			break;
		case DOMAIN_SEA:
			if (pUnit->getDomainType() == DOMAIN_SEA && pUnit->getUnitInfo().GetUnitAIType(UNITAI_WORKER_SEA))
			{
				AddImprovingResourcesDirectives(pUnit, pPlot, iMoveTurnsAway);
				AddImprovingPlotsDirectives(pUnit, pPlot, iMoveTurnsAway);
			}
			if (pUnit->AI_getUnitAIType() == UNITAI_WORKER_SEA && pUnit->getDomainType() == DOMAIN_SEA)
			{
				AddRepairTilesDirectives(pUnit, pPlot, iMoveTurnsAway);
			}
			break;
		}
```

Just gives directive...I can't see how that would be affected.

**Comment by Iamblichos** [comment]
@Infixo to mimic what I did, did you update your database to mirror this:

+1 [ICON_FOOD] Food and +2 [ICON_GOLD] Gold for each Farm, Banana, Citrus, Spice, Salt, and Wheat resource.

**Comment by Infixo** [comment]
Pls post sql for these changes.

**Comment by Iamblichos** [comment]
assuming sun god of vanilla game: Banana, Citrus, and Wheat already have +1 food.

INSERT INTO Belief_ResourceYieldChanges
			(BeliefType,					ResourceType,			YieldType,			Yield)
VALUES			('BELIEF_SUN_GOD',				'RESOURCE_BANANA',		'YIELD_GOLD',		2),
			('BELIEF_SUN_GOD',				'RESOURCE_CITRUS',		'YIELD_GOLD',		2),
			('BELIEF_SUN_GOD',				'RESOURCE_WHEAT',		'YIELD_GOLD',		2),
			('BELIEF_SUN_GOD',				'RESOURCE_SPICES',		'YIELD_FOOD',		1),
			('BELIEF_SUN_GOD',				'RESOURCE_SPICES',		'YIELD_GOLD',		2),
			('BELIEF_SUN_GOD',				'RESOURCE_SALT',		'YIELD_FOOD',		1),
			('BELIEF_SUN_GOD',				'RESOURCE_SALT',		'YIELD_GOLD',		2);

INSERT INTO Belief_ImprovementYieldChanges
			(BeliefType,					ImprovementType,				YieldType,			Yield)
VALUES 			('BELIEF_SUN_GOD',				'IMPROVEMENT_FARM',				'YIELD_FOOD',		1),
			('BELIEF_SUN_GOD',				'IMPROVEMENT_FARM',				'YIELD_GOLD',		2);

**Comment by Infixo** [comment]
There's already +3 food from Farms in DB from this pantheon, so you should use UPDATE probably.

**Comment by Iamblichos** [comment]
My ModBuddy solution is A LOT different than base VP....so don't copy paste...Just reflect the intent of what I have.

**Comment by Iamblichos** [comment]
Just ran another test game...Nobody selected that pantheon....no issue. So strange.

**Comment by Iamblichos** [comment]
I think I see a problem. I don't have set RequiresImprovement for Sun God.

**Comment by Iamblichos** [comment]
Okay someone explain this to me: what is the relationship between Belief_ImprovementYieldChanges and RequiresImprovement? Some beliefs that are in Belief_ImprovementYieldChanges don't have RequiresImprovement and some do.

**Comment by Infixo** [comment]
The table was present in vanilla, i think. RequiresImprovement and RequiresResource was added in CP. Also, they are set to 0 as default. Weird, maybe it's not used at all.

**Comment by Infixo** [comment]
Anyway, I tested duplicate entries in Belief_ImprovementYieldChanges and they are handled properly, i.e. the improvement simply gives more yields. No houston, no excessive yields generated.

**Comment by Iamblichos** [comment]
@Infixo I'm not using either of these FYI:

UPDATE Beliefs
SET RequiresResource = '1'
WHERE Type = 'BELIEF_SUN_GOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET RequiresImprovement = '1'
WHERE Type = 'BELIEF_SUN_GOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

**Comment by Iamblichos** [comment]
@Infixo yeah regarding duplicates...that changed nothing...but I'm curious about RequiresResource now.

**Comment by Infixo** [comment]
Did some more testing and I take back what I said about Belief_ImprovementYieldChanges. Duplicate entries here do break something, have not located what exactly yet.
Anyway, I added +5 food to a farm. So, there were 2 entries +3 and +5. After improving the wheat, only +5 was recognized. Interesting thing happened when I removed manually all workers - there should be always a residual food from capital tile. This time it was gone, zero. The capital in my example should give +2 food, and I suppose this was netted out with difference between duplicated yields in the table.

**Comment by LoneGazebo** [comment]
@Infixo from what I can tell Belief_ImprovementYieldChanges is only used (at the plot level) in calculateImprovementYieldChange, and that appears to only be updated in CvPlot::calculateYieldFast for Culture. Perhaps that's an issue? I'm not able to fully test today, just browsing the github repo.

**Comment by Infixo** [comment]
I will look into calculateImprovementYieldChange too.
However, normal usage of Belief_ImprovementYieldChanges is via m_ppiImprovementYieldChanges[][] which is loaded at startup. Duplicate entries simply overwrite existing ones, so later when somebody uses CvBeliefEntry::GetImprovementYieldChange() it returns a proper value. Just an explanation why only +5 was recognized in my test. But anyway, 2 food was lost somewhere.

**Comment by Iamblichos** [comment]
@Infixo I still reproduced the problem when I removed duplicate entries.

**Comment by LoneGazebo** [comment]
@Infixo because beliefs 'pool' their attributes into a general value for the religion, if two different beliefs have different tile attributes (i.e. requires resources or requires improvement) _all_ of them will gain the new attribute. So if you have one with requires resource, and one with requires improvement, taking both will apply this bool to both. This is how Firaxis setup the entire system, and - though I sanitized it - I left this functionality intact because database lookups are intensive at runtime. So it is possible that this explains why you are losing yields (as valid yields suddenly become invalid if you add one of these bools in some situations).

**Comment by Infixo** [comment]
@Iamblichos Maybe you need to start a new game or reload a save from before duplicates. I checked that scenario, and once I entered an improvement with duplicate entries, and then corrected the DB, it still caused an issue. I never got an issue in the first place when using proper setup in the table.

**Comment by Iamblichos** [comment]
@Infixo you set that pantheon identical to the way I have it with a mixture of farms and resources? I’m not using that requires thing. Yes I corrected database and reran a fresh game. Still reproduced. But here’s where I’m at. I removed farms completely from that belief so now it’s just resources. I haven’t gotten anybody to pick that pantheon now but I’m not reproducing. I think that pantheon is a unique problem because of the mixture I noted.

**Comment by Infixo** [comment]
I am not getting problems with original vp setup when using this pantheon (current master). This duplication situation is the very first time I got anything that gives any issues. But this was done on purpose, like "let's make some wrong params and see what happens". Well, problems happened, which is not very surprising, right?
What boggles me more is that @LoneGazebo said he'd got houston call when using standard vp.

**Comment by Infixo** [comment]
@LoneGazebo It seems that only pantheons use those 2 flags. I don't see any other beliefs with that. So, there should not be a case of a flag being overwritten by a flag from a different belief. Also, in my test the other 2 beliefs in the religion are not related to improvements nor resources (science from followers and tourism/culture from spreading).

**Comment by LoneGazebo** [comment]
@Infixo don't know what to tell you, other than it happened a few times during a game. Oddly enough, though, I didn't notice any discrepancies in the UI related to it. @ilteroi you have any ideas?

**Comment by Iamblichos** [comment]
On Building_YieldPerXTerrainTimes100, is that something that the yield is to the building in the city? or does that get updated on the map?

**Comment by ilteroi** [comment]
ok, i kinda lost track of all the developments here. just a few comments.

* i did not implement any new caches which could be out of sync. i simply pulled out the working city and religion lookups from the inner loop, as they are constant for a given city
* initally i flipped two parameters in a function call, so i got weird effects and put in that "houston" line to help track it down. since i fixed that, i haven't had problems
* nevertheless the houston check keeps triggering sometimes when re-assigning citizens. that shouldn't happen, but i'm almost 100% sure that is not a new problem
* this whole tile yield code is a mess and i hope one of you understands it, cause i sure don't

**Comment by Iamblichos** [comment]
I really think now that I have something wrong in my database that is causing my strange yields. So I don't think this is a VP problem.

**Comment by Iamblichos** [comment]
@LoneGazebo @Infixo where does Belief_ImprovementYieldChanges (function: int CvBeliefEntry::GetImprovementYieldChange) actually get used for a pantheon, not a secondary pantheon nor a majority religion? I don't actually see where it does.

**Comment by Iamblichos** [comment]
Only thing I see for pantheon qua pantheon is int iValue = pPantheon->GetTerrainYieldChange(getTerrainType(), eYield); and adding that over and over for those Booleans (e.g. RequiresResource, RequiresImprovement). And then there is iReligionChange += pReligion->m_Beliefs.GetPlotYieldChange(getPlotType(), eYield, ePlayer, pOwningCity); that also applies.

The rest of the functions get culled under if(pReligion). This is such a head scratcher.

**Comment by LoneGazebo** [comment]
I've taken some time this evening to completely refactor the yield code, moving things into proper functions, etc. Should speed things up AND make it easier to track this down.

**Comment by Iamblichos** [comment]
While you are doing that, I’m scrubbing my database table by table.

**Comment by LoneGazebo** [comment]
Posted my cleaned up code, Much easier to see what's going on in the plot yields. 

That said, I was wrong, the issue persists. I can trigger it pretty easily with a civ like Carthage - there's something going on in which plot values are being updated without altering the terrainworked CvCity value, such that, when the city stops working (or starts working) the tile, the value being received is off from the value of the tile's yields. I don't see it, and I've been staring at it until I'm going blind. So @ilteroi , @Infixo and @Iamblichos , I hope you have better luck.  I'm sure it's something dead-simple. 

To note, I have good luck with Carthage triggering it because I think the issue is somehow related to yield increases for tiles from things like buildings (see Carthage's free lighthouse) not updating the worked tile value underneath it. At least, that's my theory anyways.

G

**Comment by ilteroi** [comment]
well, one thing that is strange: as far as i can see, there is no check if the working city of the plot is the actual city whose yields we are updating.

previously, the plot would do the lookup and the yields would be attributed to the correct, if unrelated city. now with the pre-set city pointer it's possible that the yields go to the wrong city?

if that's true it means we should see issues with closely-spaced cities. then again, i've never understood how this "plot borrowing" between cities works.

**Comment by Iamblichos** [comment]
Guys,
I won’t be able to do much code hunting today. @ilteroi that’s exactly what I thought about the updated plot. I’ll be working on this all day tomorrow.

**Comment by Infixo** [comment]
@LoneGazebo It would be easier if you posted a save file that gives an issue.

**Comment by LoneGazebo** [comment]
@infixo indeed. I’m pretty confident in my code cleanup, but I think it revealed more defects in the existing system.

**Comment by Infixo** [comment]
Also, I get it for City States. Single city case, so it is rather not related to switching tiles between cities.

**Comment by Iamblichos** [comment]
I just got a chance to browse the change but haven’t studied it yet. I still do not understand where pantheon yields get done on plots. Majority religions, yes. Secondary Pantheons, yes. But where are pantheons prior to and apart from any of that actually get done on CvPlot?

**Comment by Infixo** [comment]
Weird thing is that even if I lock all citizens to specific tiles (so, no reassignments should happen) it still happens. And every turn it systematically decreases / increases yields. I've got 2 cities. In one production goes up each turn by a fixed amount and in the other it goes down by a fixed amount. Different amounts however (+3 vs. -7). This would suggest some recalculation problems.
Another observation is that I was having a strange behavior with a mine. It didn't update yields immediately (i mean graphics, on the tile). So, I had a situation where the tooltip said +3 prod but it showed +6 on the screen. It was like this for a few turns, then it was gone.

**Comment by Infixo** [comment]
@Iamblichos Pantheons are processed as part of the city's majority religion. Religion sums up all its beliefs. That is why @LoneGazebo said that those 2 boolean flags could be overwritten. It doesn't happen in standard VP because only pantheons use these flags and there can be only pantheon per religion.
That is also why a secondary pantheon logic is added separately but it is mostly a copy-paste from religion code.

**Comment by Iamblichos** [comment]
So it appears now that we really do have a principled problem apart from what my mod does. I think one of the reasons it is more apparent for me, is that almost every building in my game that is associated with growth, production, gold, is modifying improvement yields, resource, sea plot yields, sea resource yields, or some combination. That gives me a more frequent turnover of exacerbating the problem.

**Comment by Iamblichos** [comment]
@Infixo yeah I see that I mentally noted that yesterday. So, for my own benefit, how does those summations actually fire if the city doesn’t have a majority religion or hasn’t even spawned a prophet? Are you saying a pantheon is thusly a majority religion in the city? Is GetMajorityReligion(function off the top of my head) inclusive of what it means to only have a pantheon in the city?

**Comment by Infixo** [comment]
Despite all citizens locked into tiles, the game constantly calls CvCity::updateYield() on many occasions (golden age update, religion update, etc.) This goes into CvPlot::updateYieldFast() and eventually CvCity::ChangeBaseYieldRateFromTerrain(). Many of these calls have iChange > 0 which should NOT happen because there's literally no change in city's situation. Each such call increases m_aiBaseYieldRateFromTerrain[]. Already got into 145 production for a 7 pop city.

**Comment by Infixo** [comment]
@Iamblichos Check CvCityReligions::ComputeReligiousMajority(). I think it uses followers, so pantheons would do too.

**Comment by Iamblichos** [comment]
@Infixo. Thank you. I haven’t studied much of the religion code in the game, so I appreciate the clarification.  My frustration of the issue rests on an equivocation because what we call a religion many time in the game and in other parts of the code (e.g. “MaxReligions”) excludes pantheons and so I figured a majority religion in a city meant actually founding a religion (i.e one of the major religions in the game, Islam, etc.) I knew the code for pantheons worked just not that it worked or how.

**Comment by LoneGazebo** [comment]
Who all is currently, actively working on this issue?

**Comment by Infixo** [comment]
I am trying to pinpoint the situation where the additional yields are added.

**Comment by Infixo** [comment]
Actually narrowed it down to CvPlot::calculateYieldFast() but this function is called so many times and only very calls produce bad results.

**Comment by Iamblichos** [comment]
@LoneGazebo got a chance to break away and update code and run a test game:
![20180520125332_1](https://user-images.githubusercontent.com/14372214/40281939-0afc835c-5c2d-11e8-961c-e7790de0ac76.jpg)
21 food from terrain. should be 6.


![20180520125339_1](https://user-images.githubusercontent.com/14372214/40281954-21ada964-5c2d-11e8-8cd4-2260f3fff356.jpg)
-6 gold from terrain, should be 0.

**Comment by LoneGazebo** [comment]
@Infixo I also think the issue is that cvCity:UpdateYield is not checking to see if it is the owning city of a plot when it goes to update a yield.

**Comment by LoneGazebo** [comment]
line 3296

**Comment by LoneGazebo** [comment]
that's the only place where updateyieldfast is called outside of plot (so it's the only place where the const cvcity isn't guaranteed to actually be the working city)

**Comment by LoneGazebo** [comment]
uploading my fix now - also caught a situation where yields could be recalculated out of sync in cvCityCulture.

**Comment by LoneGazebo** [comment]
Not sure if this will fix it but it is definitely a bug.

**Comment by LoneGazebo** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/commit/708810aa01969c3b4f03880ec9c152c8412d760d

**Comment by Infixo** [comment]
Yeah, this loop @ 3298 calls these updates many times, some of those updates are incorrect. I have a breakpoint here actually. Will test if this addition will fix the situation.
if (pLoopPlot != NULL && pLoopPlot->getOwningCity() == this)

**Comment by LoneGazebo** [comment]
@Infixo no more houstons on the current debug game. That's a good sign.

**Comment by Iamblichos** [comment]
@Infixo so you were actually able to reproduce a yield increase every turn despite no real change? That's the first I've heard outside myself.

**Comment by LoneGazebo** [comment]
@infixo is that on my latest?

**Comment by LoneGazebo** [comment]
I'm calling this fixed as of my latest. Two speedy test runs showed no calls to houston and no overages on yield valuation.

**Comment by Infixo** [comment]
I have replayed several turns which were problematic. Seems ok. I am not getting any extra yields nor houston calls.

**Comment by LoneGazebo** [comment]
well but not all tiles have all yields.

**Comment by LoneGazebo** [comment]
i think what was happening is that two different cities would update the same tile (with different city-based parameters, or even player-based parameters if it was two neighboring civs), but only the city working the tile would get the terrainyieldchange call - so it would add and subtract tile yields based on that exchange.

**Comment by Infixo** [comment]
Ok, last thing before I forget. If we ever got something similar: my another working theory was that somehow buildings that grant yields to improvements are involved in that. I observed, at least in my game, that all those bad calls were related to tiles with improvements and additional yields from buildings. Problematic was Mine with Siege Foundry and Plantation with Herbalist.

**Comment by LoneGazebo** [comment]
that makes sense though - if one city has a forge and another doesn't, then its going to constantly alter that plot's yields (and affect the working city).

**Comment by Iamblichos** [comment]
@Infix that’s what I’m thinking I looked closely and saw it was happening with or without religion. I use improvement yield changes frequently and earlier than what default VP does.

**Comment by Iamblichos** [comment]
I’m re running another test game with most up to date code.

**Comment by Infixo** [comment]
Hm... Because this loop "for (iI = 0; iI < GetNumWorkablePlots(); iI++)" goes through all tiles around the city what was missing was actually CvCityCitizens::IsWorkingPlot().
Seems that CvPlot keeps its owning city and CvPlot::updateYieldFast() actually should not need the first parameter, i.e. pOwningCity. Then each call would update the tile using the correct owning city data.

**Comment by LoneGazebo** [comment]
@Infixo that's what @ilteroi moved out for performance reasons.

**Comment by ilteroi** [comment]
ouch. so it was my fault after all?

sorry about that .. at least my dream tonight was right :)

**Comment by LoneGazebo** [comment]
@ilteroi but the end result is much faster and cleaner cvplot code, so you just did us a favor :)

**Comment by Iamblichos** [comment]
Makes me wonder if the bug had always been there before, or no....

**Comment by Iamblichos** [comment]
Confirmed. Fixed.

**Comment by Iamblichos** [comment]
Thanks everybody for digging into this.

**Comment by Iamblichos** [comment]
It looks like the sina qua non of the problem was pLoopPlot->getOwningCity() == this in CvCity::updateYield?

**Comment by LoneGazebo** [comment]
@Iamblichos I think it's part of it - it was sporadic because not all of the yield calculation functions used the const city to calculate (some had it baked in) so only certain yield types would trigger it. When I sanitized the functions they all used the const, thus it became immediately more apparent.

**Comment by Iamblichos** [comment]
So....was this @ilteroi version of INT_MAX ? Ha, couldn't resist....
