### ISSUE TITLE
City Tourism Tooltips are 100x too high

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4396]
18-4-30

Just a quick multiplication error in the Tourism display in City View:
![18-4-30 city tourism](https://user-images.githubusercontent.com/34615525/40211917-8aa28edc-5a0a-11e8-86dc-f553eaac6239.png)

**Comment by LoneGazebo** [comment]
That's because you are using that other cityview mod - you need to tell the author to update it (as tourism for cities is now calculated in the hundreds and divided by 100 in LUA.
