### ISSUE TITLE
Tooltip for Castle Mismatched Info

### ISSUE THREAD

**Issue by bridger15** [LoneGazebo/Community-Patch-DLL#4398]
_1. Mod version (i.e Date - 4/23):_
4/30

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
See Image: https://i.imgur.com/KSMkeWq.png

Text on top area of tooltip implies +10% military supply cap from population.  Text on bottom section reads only a +5%.

**Comment by Infixo** [comment]
Fixed in 5-20.
