### ISSUE TITLE
No WLTKD Icon Showing for Capital

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#4401]
_1. Mod version (i.e Date - 4/23):_
4-30

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
My capital is no longer showing the ability to get a WLTKD. As you can see in the screenshots, the icon is gone in both the city summary and the city detailed area.

Other cities seem to be fine. I've given it 5 turns just to see if it would clear, but it lasted so far.

_4. Steps to reproduce (optional):_

![no_wltkd_1](https://user-images.githubusercontent.com/20593976/40260329-a358df98-5abf-11e8-9cab-046caa514778.png)
![no_wltkd_2](https://user-images.githubusercontent.com/20593976/40260336-a90bf772-5abf-11e8-98cc-36913cdf8255.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by NewFellow** [comment]
I have experienced this too, and I think I am experiencing it in my current game. :/

**Comment by NewFellow** [comment]
But i tried to use a great merchant to get it going, and after that it seems to work properly again.

**Comment by NewFellow** [comment]
Even so, it's an incredible deelay of WLTDK and a waste of merchant. This bug seem to happen to one of my cities each game; though 95% of the time my capital is affected by it and I have to waste the circus to get it going. Too bad nothing can be done to it yet.

**Comment by ryanmusante** [comment]
Mod version 4-30?
