### ISSUE TITLE
AI with a majority of WC votes mismanages its voting allocation

### ISSUE THREAD

**Issue by Omen-of-Peace** [LoneGazebo/Community-Patch-DLL#4403]
_1. Mod version (i.e Date - 4/23):_ 04/30

_2. Mod list (if using Vox Populi only, leave blank):_ modpack from the Modpack thread (with some UI mods)

_3. Error description:_ In my Emperor game on a Small map, the Austria AI had about 30 votes and the rest of the other civ combined something like 20.
When voting against a proposition it didn't like, it often chose an overkill amount of votes (e.g. 28-30).

If not complicated to implement: the AI, when it has more than half of the total votes in the WC, should never allocate more than [total of other civ's votes + 1] votes to the proposal that it deems more important (without the +1 even, if it favours the status quo).
(It could even allocate slightly fewer votes, banking on the fact that not all other civ will allocate ALL their votes to the other side of that proposal... But this gets more complicated to manage.)

Then it can allocate the remaining votes elsewhere.
(I won't presume to know the rest of the voting logic...)

**Comment by LoneGazebo** [comment]
Makes sense. I'll look at it.
