### ISSUE TITLE
Multiplayer CTD

### ISSUE THREAD

**Issue by Squishyy** [LoneGazebo/Community-Patch-DLL#4404]
_1. Mod version (i.e Date - 4/23):_
4-30-4

_2. Mod list (if using Vox Populi only, leave blank):_
Modpack of Vox Populi (including EUI), no other mods but Vox Populi, created following [this](https://www.reddit.com/r/civvoxpopuli/wiki/modpack) guide.

_3. Error description:_ 
CTD during the AI's turn in a multiplayer game. Loading the most recent autosave and the one prior still resulted in a crash, with and without the other person I was playing with. Clearing the cache also didn't help.

Logs folder, minidump, and autosave of the turn right before the CTD:
[files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2020003/files.zip)

The MP_MODSPACK and UI_bc1 folders used for the game:
[modpack.zip](https://drive.google.com/open?id=1yzQV1NuGOyIqppW4BmlAStYt1_soG4It)

_4. Steps to reproduce (optional):_
Load the save, finish the turn, then hit next turn. The game will crash during the AI's turn.

**Comment by John12000** [comment]
This is a multiplayer game with 2 people and 10 AI. I'm the 2nd player. Not sure if you need my logs, dump, and modpack but here they are:
Logs:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2020008/Logs.zip)

Crash Dump:
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2020009/CvMiniDump.zip)

Modpack:
[modpack.zip](https://drive.google.com/open?id=1FfLfhH9vMDzmCkP1R-IVWbGnMk4nD9fE)
