### ISSUE TITLE
liberating a vassal's city

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4405]
so i was at war with japan, who had take over most of the roman empire before and made them their vassal.

i conquered rome and liberated it. result: rome got their city back but are at war with me and next turn i'll have to conquer it again, for real this time.

so liberating makes no sense here. should the liberate option be disabled if it's a vassal city?

**Comment by LoneGazebo** [comment]
@ilteroi shouldn't be able to liberate to a player you are at war with, period.

**Comment by ilteroi** [comment]
so that's a bug?

**Comment by LoneGazebo** [comment]
Kinda? :)

**Comment by ilteroi** [comment]
ok, i'll fix it
