### ISSUE TITLE
[Outdated notification] Carnival notification stating "+20% Culture", instead of +25%

### ISSUE THREAD

**Issue by legenciv** [LoneGazebo/Community-Patch-DLL#4407]
_1. Mod version (i.e Date - 4/23):_
4-30-4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Outdated notification for Carnival: it states that cities will produce +20% Culture (old value). Current value is +25%.

4. Screenshots (optional):
[carnivalInfo.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2020676/carnivalInfo.zip)

**Comment by Iamblichos** [comment]
Fixed in 5-20.

**Comment by legenciv** [comment]
Uh, I think there was a misunderstanding. The correct value is +25% Culture, not +20%. The tooltip to be corrected isn't the one appearing in the civ selection screen, it's the one that pops when a Golden Age is triggered.
