### ISSUE TITLE
Goddess of Nature Pantheon gives bonus to Dyes, Incense and Cities

### ISSUE THREAD

**Issue by Grabbl** [LoneGazebo/Community-Patch-DLL#4409]
_1. Mod version (i.e Date - 4/23):_
5-20

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP, UI-Small resource Icons, UI-Improved City View, UI-National Wonder Splashscreens

_3. Error description:_ 
![20180521122718_1](https://user-images.githubusercontent.com/19163988/40303458-1a973cdc-5cf3-11e8-981d-922bc40f563d.jpg)

The Goddess of Nature pantheon gives the bonus it should give to natural wonders (+2 culture, +3 faith) to Incense, Dyes, and Cities. 

Save and Logs:

[PantheonBug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2022220/PantheonBug.zip)
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Padre19** [comment]
Confirm. + 2 Culture and + 3 Faith to all tile with resources.

**Comment by Iamblichos** [comment]
Any tile that has resources, regardless of resource type?

**Comment by Padre19** [comment]
Bonus and luxury resources. I did not play till the discovery of iron.

**Comment by Iamblichos** [comment]
Could you go ahead and verify if it happens on iron?

**Comment by Iamblichos** [comment]
@Infixo yeah I know, I suspect it's giving yield to any resource. I don't know why we just don't remove parameter const CvCity* pOwningCity from calculateReligionNatureYield since CvPlot already has its own function for CvCity* getOwningCity() const;.

**Comment by Padre19** [comment]
After reload autosave...... ( i have some extra mods )
![civ5screen0000](https://user-images.githubusercontent.com/32882007/40309613-c166533a-5d12-11e8-9f22-132e54b8d139.png)

**Comment by Iamblichos** [comment]
looks to me like it's giving the yield bonus to any terrain feature or no feature if indeed those plots don't have resources either (which they all probably don't).

**Comment by LoneGazebo** [comment]
I’ll look.

**Comment by Infixo** [comment]
There's a check missing in calculateReligionNatureYield() if the tile is actually a NW. It gives yields to all worked tiles. I should fix it in a moment.

**Comment by LoneGazebo** [comment]
@infixo thanks, figured it was that.

**Comment by Iamblichos** [comment]
Yep. good call.
