### ISSUE TITLE
Multiple civs choosing same pantheon

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#4410]
Newest version, only using VP

https://i.gyazo.com/e3c9d35e9059ab0bdd859d4ff0087577.png

**Comment by LoneGazebo** [comment]
Byzantium can do that.

**Comment by Padre19** [comment]
Seems to be something else. 
God King - twice
Ancestor Worship - three times

**Comment by Infixo** [comment]
This window displays all pantheons twice. Once as pantheon and once as part of religion beliefs.
