### ISSUE TITLE
Godess of nature in 5-20 bonus yields on every tile

### ISSUE THREAD

**Issue by pzapza** [LoneGazebo/Community-Patch-DLL#4411]
_1. Mod version (i.e Date - 4/23):_
5-20

_2. Mod list (if using Vox Populi only, leave blank):_

1. Unit Path Viewer (v 10)
2. UI - Improved City View (Vox Populi EUI) (v 10)
3. UI - Religion Spread (Vox Populi) (v 1.0)
4. UI - Filters in Trade Route Overview (Vox Populi) (v 1)
5. UI - Show XP in Military Overview (v 2) 

_3. Error description:_ 
Goddess of Nature increases every tiles' yield by the amount only natural wonders should be increased (+2culture, +3 faith) (Screenshots below were taken on the same turn that i selected the pantheon and founded Si Satchanalai. One turn later, every tile had bonus yields in capital.)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![goddess of nature](https://user-images.githubusercontent.com/38469319/40310013-c6c231f2-5d0b-11e8-812c-2890e5b402c2.jpg)
![goddess of nature2](https://user-images.githubusercontent.com/38469319/40310014-c6ec0f04-5d0b-11e8-9920-2badb6131cd6.jpg)

**Comment by Iamblichos** [comment]
#4409
