### ISSUE TITLE
City tile's increased yield when founding

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#4412]
_1. Mod version (i.e Date - 4/23):_
Using only 5/20

Fresh Water: 5F 1H
Non fresh Water: 4F 1H 1G
Hill: 2F 3H

**Comment by Iamblichos** [comment]
Yep...I'm getting this too. It doesn't have the calculation problem that we had either (it's calculating), looks like we added something somewhere. Will look.

**Comment by Iamblichos** [comment]
Okay, I see the problem. The way we are adding up yields.
iYield = std::max(iYield, kYield.getMinCity()); this gets added to the terrain yields...and then gets added to the special cases of terrain type iYield += kYield.getMinCityFlatFreshWater();, etc.

So now we need to adjust our values for MinCity and the Min...Special Terrain cases....

**Comment by LoneGazebo** [comment]
@iamblichos yeah that seems right.

**Comment by Iamblichos** [comment]
Just to talk it out here:

MinCity by default (which VP doesn't change is ) 2F, 1P.

If we leave that alone, on flat grass we get 4F, 1P. If it is freshwater, we get +1F. So now 5F, 1P.

On flat plains, we get 3F,2P. If freshwater, we get +1F. So now 4F, 2P.

If we reduce MinCity to 1F, 0P, then flag grass gets 0P. No good.

If we had in a 1P to !isHills to gain that back then, falt plains gets 2P.

Either way you slice it grass gets 1 more food, and plains gets 1 more P.

My vote here is to just leave it alone and allow the terrain to dictate that yield and give the city the additional boost. I mean after all, it is the city plot.

**Comment by Iamblichos** [comment]
Hills don't get anything at all in VP except by way of MinCity...so hills will always be 2F, 3P. What I did in my mod is I wanted an end result to always be the same. If hill no fresh water, then MinCity (2F,3P) +1 Gold to get us to a total of 6.

default VP:
UPDATE Yields
SET MinCityFlatNoFreshWater = 1, MinCityMountainNoFreshWater = 1
WHERE Type = 'YIELD_GOLD';

Mine:
UPDATE Yields
SET MinCityFlatNoFreshWater = 1, MinCityHillNoFreshWater = 1, MinCityMountainNoFreshWater = 1
WHERE Type = 'YIELD_GOLD';

And if freshwater VP has:
UPDATE Yields
SET MinCityFlatFreshWater = 1, MinCityMountainFreshWater = 1
WHERE Type = 'YIELD_FOOD';

Mine:
UPDATE Yields
SET MinCityFlatFreshWater = 1, MinCityMountainFreshWater = 1, MinCityHillFreshWater = 1
WHERE Type = 'YIELD_FOOD';


This way values will be consistent.

**Comment by LoneGazebo** [comment]
An easier method would probably be to have the primary ‘calculateYield’ function simply check if it is a city tile or not. If it isn’t, it works as it does now. If it is a city tile, it doesn’t check nature yields and instead just gets the improvement yield as it’s base. Make sense?

**Comment by Iamblichos** [comment]
That's fine too... either way you want it...…...but......I kind of like the additive terrain yield underneath a city. It gives that plot a little more flavor.

**Comment by LoneGazebo** [comment]
Early game balance is a delicate beast though.

**Comment by Iamblichos** [comment]
True it could throw off getting to 6 pop quicker or hammering out that early building on plains, though, it is fair across the board.

**Comment by Iamblichos** [comment]
….unless you get desert or tundra. You have a less than advantageous city plot position.

**Comment by Iamblichos** [comment]
@LoneGazebo I'll put iYield = calculateNatureYield(eYield, ePlayer, false); under calculateYieldFast with a check !getPlotcity or !isCity()

**Comment by ilteroi** [comment]
don't use getPlotCity() if you don't actually need the pointer, it does a lookup, bad for performance

**Comment by Iamblichos** [comment]
I used !isCity() but I don't see how it is any better:
```
bool isCity() const
	{
		if((m_plotCity.eOwner >= 0) && m_plotCity.eOwner < MAX_PLAYERS && m_plotCity.iID>0)
		{
#if defined(MOD_CORE_DEBUGGING)
			 if (MOD_CORE_DEBUGGING && (GET_PLAYER((PlayerTypes)m_plotCity.eOwner).getCity(m_plotCity.iID)) == NULL)
				 OutputDebugString("warning: inconsistent plot state! bad city ID.");
#endif
			 return true;
		}

		return false;
	}
```


```
CvCity* getPlotCity() const
	{
		if((m_plotCity.eOwner >= 0) && m_plotCity.eOwner < MAX_PLAYERS)
			return (GET_PLAYER((PlayerTypes)m_plotCity.eOwner).getCity(m_plotCity.iID));

		return NULL;
	}
```

**Comment by Iamblichos** [comment]
Would it be better to do pOwningCity->plot()?

**Comment by Iamblichos** [comment]
Never mind I gotcha.

**Comment by Iamblichos** [comment]
Done and committed to master.
