### ISSUE TITLE
Disabling events issue

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#4414]
_1. Mod version (i.e Date - 4/23):_
2018-05-20

_2. Mod list (if using Vox Populi only, leave blank):_
UIs

_3. Error description:_ 
When setting up a new game, untickling Events does not unselect other Event options anymore (No bad events, No good events, sfsf)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
It never did.

**Comment by MoiMagnus** [comment]
They were unselected by default.

**Comment by tu-79** [comment]
Ah, ok. Then, why was it changed? Now it comes selected by default.

**Comment by MoiMagnus** [comment]
I don't know. "Enable Event system" is ticked by default, which is normal, but I don't know why "No Good/Bad/Neutral/... Events" is ticked by default. Sound like a bug to me.

**Comment by ryanmusante** [comment]
Checking to 1 has no effect on advanced startup options in setup screen. Should it not show if events is set to 0?
```
--UPDATE GameOptions SET "Default" = 1 WHERE Type = 'GAMEOPTION_EVENTS_NO_GOOD';
--UPDATE GameOptions SET "Default" = 1 WHERE Type = 'GAMEOPTION_EVENTS_NO_NEUTRAL';
--UPDATE GameOptions SET "Default" = 1 WHERE Type = 'GAMEOPTION_EVENTS_NO_BAD';
--UPDATE GameOptions SET "Default" = 1 WHERE Type = 'GAMEOPTION_EVENTS_NO_TRADE';
--UPDATE GameOptions SET "Default" = 1 WHERE Type = 'GAMEOPTION_EVENTS_NO_CIV_SPECIFIC';
```

**Comment by ZenyaIse** [comment]
I noticed that all events (bad, good, neutral, and trade) became disabled by default in the advanced game options since version 4/30.
Also asked in the forum (without any response though).
https://forums.civfanatics.com/threads/new-version-april-30th-4-30.631936/#post-15116528
UI bug?

**Comment by ricanuck** [comment]
My experience: when I disable ALL event-related checkboxes to disable the event system in my games, the first game I play still has events ON. After that, the other games respect the settings. In other words, every time there is a new version or beta. my first game has to be a dummy to really set the event system to OFF.

**Comment by tu-79** [comment]
It seems solved in 10-10-2!
Installed the beta, unchecked events and they remained unchecked from the first game.

**Comment by ryanmusante** [comment]
Yes, new options in 10-10-2, problem solved.
