### ISSUE TITLE
Strange Food Calculation

### ISSUE THREAD

**Issue by moshpitwar** [LoneGazebo/Community-Patch-DLL#4415]
_1. Mod version (i.e Date - 4/23):_ 5/20

_2. Mod list (if using Vox Populi only, leave blank):_ VP + Unique City-States (v 2)

_3. Error description:_ 
I have 6 tiles activated generating 24 food. But the calculation shows stagnation even with 12 food left over.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2023831/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Ahmad al-Mansur_0066 BC-2350.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2023820/Ahmad.al-Mansur_0066.BC-2350.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![food_issue](https://user-images.githubusercontent.com/39499777/40325726-3430f3b6-5d13-11e8-837f-ddcd748a7ce7.png)

**Comment by LoneGazebo** [comment]
I was just about to say, it's because you're building a settler. :)

**Comment by Iamblichos** [comment]
Whew.
