### ISSUE TITLE
CTD fix

### ISSUE THREAD

**Issue by Squishyy** [LoneGazebo/Community-Patch-DLL#4416]
I was trying to debug [this](https://github.com/LoneGazebo/Community-Patch-DLL/issues/4404) issue, and although I have no experience modding civ (or anything for that matter), the game crashes in PlotHealMoves() in CvTacticalAI.cpp, seemingly due to an iterator being invalidated:

```
/// Assigns units to heal
void CvTacticalAI::PlotHealMoves()
{
	list<int>::iterator it;
	m_CurrentMoveUnits.clear();

	//not all units go through ExecuteHeals
	std::set<int> passiveAggressive;

	// Loop through all recruited units
	for(it = m_CurrentTurnUnits.begin(); it != m_CurrentTurnUnits.end(); it++)
	{
		CvUnit* pUnit = m_pPlayer->getUnit(*it);
		if (!pUnit || pUnit->TurnProcessed())
			continue;

		//the really bad cases have already been added in CommandeerUnits
		//now we need to take care of the units which are damaged and have nothing else to do

		CvPlot* pUnitPlot = pUnit->plot();
		if (pUnitPlot == NULL)
			continue;
		int iAcceptableDamage = 20;

		//allow some more damage outside of our borders
		if (pUnitPlot->getOwner() != pUnit->getOwner())
		{
			iAcceptableDamage = 40;
			if (pUnit->getDamage() > iAcceptableDamage && pUnit->getArmyID() == -1)
			{
				if (pUnit->pillage())
				{
					if (!pUnit->canMove())
					{
						UnitProcessed(pUnit->GetID());
						continue;
					}
				}
			}
		}


		if (pUnit->getDamage() > iAcceptableDamage && pUnit->getArmyID() == -1 && FindNearbyTarget(pUnit, 5) == NULL)
			m_HealingUnits.insert(pUnit->GetID());

		//units with area damage if fortified should fortify as much as possible if near enemies
		if (pUnit->GetDamageAoEFortified() > 0 && pUnit->canFortify(pUnitPlot) &&
			pUnit->getDamage() >= pUnit->healRate(pUnitPlot) && pUnit->GetDanger()<pUnit->GetCurrHitPoints() &&
			pUnitPlot->IsEnemyCityAdjacent(pUnit->getTeam(),NULL)==false &&
			pUnitPlot->GetNumEnemyUnitsAdjacent(pUnit->getTeam(), pUnit->getDomainType()) > 0)
		{
			passiveAggressive.insert(pUnit->GetID());
			pUnit->PushMission(CvTypes::getMISSION_FORTIFY());
		}
	}

	//can't do this directly, otherwise we invalidate the iterator for m_CurrentTurnUnits
	for (set<int>::iterator it = passiveAggressive.begin(); it != passiveAggressive.end(); ++it)
		UnitProcessed(*it);

	if(m_HealingUnits.size() > 0)
	{
		ExecuteHeals();
	}
}
```

The problem being here:
```
		//allow some more damage outside of our borders
		if (pUnitPlot->getOwner() != pUnit->getOwner())
		{
			iAcceptableDamage = 40;
			if (pUnit->getDamage() > iAcceptableDamage && pUnit->getArmyID() == -1)
			{
				if (pUnit->pillage())
				{
					if (!pUnit->canMove())
					{
						UnitProcessed(pUnit->GetID());
						continue;
					}
				}
			}
		}
```

In the loop iterating m_CurrentTurnUnits, UnitProcessed is called, which removes the unit with the given ID from m_CurrentTurnUnits. As far as I'm aware, erasing the element that a list iterator is pointing to will invalidate it, and it does seem like the crash happens around here.

I created a set, then added the IDs to it and called UnitProcessed on each element _after_ the m_CurrentTurnUnits loop, changing the function to this:
```
/// Assigns units to heal
void CvTacticalAI::PlotHealMoves()
{
	list<int>::iterator it;
	m_CurrentMoveUnits.clear();

	//not all units go through ExecuteHeals
	std::set<int> passiveAggressive;

	//store units to process until loop is finished, so we don't invalidate the iterator
	std::set<int> unitsToProcess;

	// Loop through all recruited units
	for(it = m_CurrentTurnUnits.begin(); it != m_CurrentTurnUnits.end(); it++)
	{
		CvUnit* pUnit = m_pPlayer->getUnit(*it);
		if (!pUnit || pUnit->TurnProcessed())
			continue;

		//the really bad cases have already been added in CommandeerUnits
		//now we need to take care of the units which are damaged and have nothing else to do

		CvPlot* pUnitPlot = pUnit->plot();
		if (pUnitPlot == NULL)
			continue;
		int iAcceptableDamage = 20;

		//allow some more damage outside of our borders
		if (pUnitPlot->getOwner() != pUnit->getOwner())
		{
			iAcceptableDamage = 40;
			if (pUnit->getDamage() > iAcceptableDamage && pUnit->getArmyID() == -1)
			{
				if (pUnit->pillage())
				{
					if (!pUnit->canMove())
					{
						unitsToProcess.insert(pUnit->GetID());
						continue;
					}
				}
			}
		}


		if (pUnit->getDamage() > iAcceptableDamage && pUnit->getArmyID() == -1 && FindNearbyTarget(pUnit, 5) == NULL)
			m_HealingUnits.insert(pUnit->GetID());

		//units with area damage if fortified should fortify as much as possible if near enemies
		if (pUnit->GetDamageAoEFortified() > 0 && pUnit->canFortify(pUnitPlot) &&
			pUnit->getDamage() >= pUnit->healRate(pUnitPlot) && pUnit->GetDanger()<pUnit->GetCurrHitPoints() &&
			pUnitPlot->IsEnemyCityAdjacent(pUnit->getTeam(),NULL)==false &&
			pUnitPlot->GetNumEnemyUnitsAdjacent(pUnit->getTeam(), pUnit->getDomainType()) > 0)
		{
			passiveAggressive.insert(pUnit->GetID());
			pUnit->PushMission(CvTypes::getMISSION_FORTIFY());
		}
	}

	//process units outside of loop so we don't invalidate the iterator
	for(set<int>::iterator it = unitsToProcess.begin(); it != unitsToProcess.end(); ++it)
		UnitProcessed(*it);

	//can't do this directly, otherwise we invalidate the iterator for m_CurrentTurnUnits
	for (set<int>::iterator it = passiveAggressive.begin(); it != passiveAggressive.end(); ++it)
		UnitProcessed(*it);

	if(m_HealingUnits.size() > 0)
	{
		ExecuteHeals();
	}
}
```

That appears to fix it, the save works fine now, no CTD. However, since I have no experience with vox populi or modding civ in general, I don't know if it would cause issues elsewhere, so I'm hoping someone can take a look at this.

Also, I suppose I could've just used passiveAggressive instead of making a new set, but I wasn't sure what the exact purpose of it was so I left it alone. Also unsure if it's necessary to use a set as opposed to say, a vector, but I don't know what impact it could have, and when in Rome...

**Comment by Iamblichos** [comment]
I believe @ilteroi fixed this crash which is included in 5-20 and on.

**Comment by Squishyy** [comment]
Do you know what the fix was? I checked the current version of PlotHealMoves() here on github before posting and it hadn't been changed, but maybe the issue was actually elsewhere? The newest version isn't savegame compatible so unfortunately I can't see if it still exists.

**Comment by Iamblichos** [comment]
These two:
https://github.com/LoneGazebo/Community-Patch-DLL/commit/cf4e99ad87a45fb6ad72ae3bb9d3b27cc5d98109

https://github.com/LoneGazebo/Community-Patch-DLL/commit/9743541c438450673f0fe19f589a5ee2d49f8914

**Comment by Squishyy** [comment]
Hmm... I don't think any of the changes in those commits would fix this problem, of course I could be completely wrong about that though. Sorry if I'm overlooking something, but as it is now I don't see how the excerpt I posted could run without invalidating the iterator and causing issues.

Do you know what exactly makes new versions not savegame compatible? Seems like the best way to see if it has been fixed is to apply those changes and see if the crash is still there, but since the new version isn't savegame compatible that wouldn't work.

**Comment by LoneGazebo** [comment]
Best person to ping on the tacticalAI is @ilteroi

**Comment by Iamblichos** [comment]
What makes games save incompatible is when we add variables that are now part of the memory foot print.

**Comment by Squishyy** [comment]
Callstack in bottom right:
![civ5_crash_callstack](https://user-images.githubusercontent.com/38708154/40338565-0900a8e2-5d33-11e8-9642-951965247539.png)

**Comment by Iamblichos** [comment]
Okay, yeah, we'll see what @ilteroi says, but as far as I can tell you have a valid fix. But I would just use the passiveaggressive set to insert them into instead of a new set. They'll get updated with the rest on that final processing loop.

**Comment by Squishyy** [comment]
Okay, I figured the passiveAggressive set would work since it seems to do the exact same thing, but wasn't completely sure. Hopefully this will fix some of the other CTDs people have been having.

That's alright, they do have pretty similar names!

**Comment by ilteroi** [comment]
well, i'm pretty sure this pUnit->pillage() block is not my code. also i've never had a crash there, but your reasoning is correct. 

i'll take care of it.

**Comment by ilteroi** [comment]
ok turns out somebody added at least two additional pillaging hooks for the AI sometime around christmas.

unfortunately both of them were buggy. whoever you are, please be more considerate in the future. two bugs in four lines of code is impressive.

**Comment by LoneGazebo** [comment]
Wasn’t me I don’t touch the tactical AI! :)

**Comment by Iamblichos** [comment]
Cheers to you Ghost Writer!
