### ISSUE TITLE
Puppet Unhappiness too low by Factor 100

### ISSUE THREAD

**Issue by Grabbl** [LoneGazebo/Community-Patch-DLL#4417]
_1. Mod version (i.e Date - 4/23):_
5-20

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I have two puppets with 8 citizens each - those should give 4 unhappiness, however the tooltip when hovering over happiness shows only 0.04 unhappiness from puppets (consistent with the sum). Economic overview shows appropriate 2 happiness from each of the puppets, but the numbers for each city add up to 16 unhappiness, not the 12 I get in the tooltip.

![20180522010846_1](https://user-images.githubusercontent.com/19163988/40334472-48331aa6-5d5e-11e8-8fe3-d7cdfe0db024.jpg)

Save + Logs:
[PuppetHappinessBug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2024360/PuppetHappinessBug.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by wistak103** [comment]
I think that i had it on 4-30
