### ISSUE TITLE
Settling cities on resources doesn't give bonus yields

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#4418]
_1. Mod version (i.e Date - 4/23):_
5-20-1

_2. Mod list (if using Vox Populi only, leave blank):_
Historical Religions Edit (BNW or GK) (v 45)
JFDLC (07) - JFD's Cultural Diversity (Core) (v 16)
JFDLC (07a) - JFD's Cultural Diversity (Soundtrack)
Unit Path Viewer (v10)

_3. Error description:_ 
I settled a city on tobacco. Doesn't receive bonus gold on city tile.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

[Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2025764/Saves.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2025765/Logs.zip)

**Comment by Infixo** [comment]
@Iamblichos There’s been additional if added before calculateNatureYield() that prevents it from being called. And that routine accounts for resources.

**Comment by Iamblichos** [comment]
@Infixo yep I’ll take a look today.

**Comment by Iamblichos** [comment]
I'm just glad we fixed the monster. These are just batting cleanup duty.

**Comment by Iamblichos** [comment]
@Infixo which routine are you talking that accounts for it prior to calculateNatureYield()?

**Comment by Iamblichos** [comment]
@Infixo in old code (prior to us making the big change to yield calc) this gets done in calculateNatureYield() here:


```
if(eTeam != NO_TEAM)
	{
		eResource = getResourceType(eTeam);

		if(eResource != NO_RESOURCE)
		{
			iYield += GC.getResourceInfo(eResource)->getYieldChange(eYield);
#if defined(MOD_BALANCE_CORE_RESOURCE_MONOPOLIES)
			if(MOD_BALANCE_CORE_RESOURCE_MONOPOLIES && pWorkingCity != NULL && GET_PLAYER(pWorkingCity->getOwner()).HasGlobalMonopoly(eResource))
			{
				int iTemp = GC.getResourceInfo(eResource)->getYieldChangeFromMonopoly(eYield);
				if(iTemp > 0)
				{
					iTemp += GET_PLAYER(pWorkingCity->getOwner()).GetMonopolyModFlat();
					iYield += iTemp;
				}
			}
#endif
			// Extra yield for religion
			if(pWorkingCity != NULL && eMajority != NO_RELIGION)
			{
				const CvReligion* pReligion = GC.getGame().GetGameReligions()->GetReligion(eMajority, pWorkingCity->getOwner());
				if(pReligion)
				{
					int iReligionChange = pReligion->m_Beliefs.GetResourceYieldChange(eResource, eYield, pWorkingCity->getOwner(), pWorkingCity);
					if (eSecondaryPantheon != NO_BELIEF)
					{
						iReligionChange += GC.GetGameBeliefs()->GetEntry(eSecondaryPantheon)->GetResourceYieldChange(eResource, eYield);
					}
					iYield += iReligionChange;
				}
			}

#if defined(MOD_API_UNIFIED_YIELDS)
			if(m_eOwner != NO_PLAYER)
			{
				iYield += GET_PLAYER((PlayerTypes)m_eOwner).getResourceYieldChange(eResource, eYield);
				iYield += GET_PLAYER((PlayerTypes)m_eOwner).GetPlayerTraits()->GetResourceYieldChange(eResource, eYield);
			}
#endif
		}
	}
```

this then got fed into calculateYield() as iYield = calculateNatureYield(eYield, ePlayer); then it's filtered for is or is not city.

In new code we are no longer doing that. I think we need to run calculateNatureYield() through calculatePlayerYield() and perhaps do some code changes that are appropriate. I could just hack resources into calculatePlayerYield() but I think we might have some more unforeseeable missing pieces.

**Comment by Iamblichos** [comment]
Okay I got it.

**Comment by Infixo** [comment]
This one.
```
if (pPlotCity == NULL)
		iYield += calculateNatureYield(eYield, ePlayer, false);
```

**Comment by Iamblichos** [comment]
Yeah I know. We put that there so the Terrain yield doesn't get added into the city plot. Gives Plains and Grass an advantageous city plot yield over everything else (i.e. 2F for grass + MinCity (2F, 1P) + special cases of isHills() or isFreshWater()). We just need to remove calculateNatureYield from calculateYieldFast and add it into calculatePlayerYield from the beginning.

**Comment by Infixo** [comment]
So... you're making a confusing code again? I think it was a good move to split terrain/res/other geo into "nature" routine and traits/other player related things into "player" routine. Why would calculateYieldFast not containt this part? Isn't it supposed to containt entire yield calculation?

**Comment by Iamblichos** [comment]
It's still all split. I'm just changing the call operations. calculateNatureYield gets added into the total calculation from calculatePlayerYield so it can get filtered for being a city plot or not.

**Comment by Infixo** [comment]
If I understand correctly how settling a city works, there's a minimum yield that the city gives. It is applied to a raw tile, so basically only terrain should be considered. All you need to do is apply std::max on that min-yield and the default terrain yield. So it is not about adding or not a terrain yiled, but choosing a bigger value.
If there's a feature - it is removed anyway. If there's a resource - it is connected.

**Comment by Iamblichos** [comment]
@Infixo The way you describe it is the way we had it yesterday in the release. player city plot yield starts with what you describe: iYield = std::max(iYield, kYield.getMinCity());


In the current master code--assuming we remove this if (pPlotCity == NULL) for sake of argument in calculateyieldfast()-- iYield will always equal the kYield.getMinCity() (plus whatever special case additions for hills, mountains, and fresh water additions) and not the previous additions. Why? Because we no longer have "added up" iYield to some higher value which used to be in the old code for calculateYield. So what then happens now when we get to calculateYieldFast()? calculatePlayerYield (the MinCityYield + whatever) gets added to calculateNatureYield. So now we haven't matched the end result for the city plot that we had back in 4-30 and prior. It's a higher overall yield accounting for everything that the tile has, terrain (though not features), resources, traits, policies, all of it.

**Comment by Iamblichos** [comment]
The other option we can do (but we must have the if (pPlotCity == NULL) in calculateYieldFast) is hack in the city plot resources underneath this code:


```
if (pPlotCity != NULL)
	{
		iYield = std::max(iYield, kYield.getMinCity());

		if (!bDisplay || pPlotCity->isRevealed(GC.getGame().getActiveTeam(), false))
		{
			iYield += kYield.getCityChange();

			if (kYield.getPopulationChangeDivisor() != 0)
			{
				iYield += (pPlotCity->getPopulation() + kYield.getPopulationChangeOffset()) / kYield.getPopulationChangeDivisor();
			}
		}

		// Mod for Player; used for Policies and such
		iYield += GET_PLAYER(getOwner()).GetPlayerTraits()->GetCityYieldChanges(eYield);

		// Coastal City Mod
		if (pPlotCity->isCoastal())
		{
			iYield += GET_PLAYER(getOwner()).GetCoastalCityYieldChange(eYield);

			iYield += GET_PLAYER(getOwner()).GetPlayerTraits()->GetCoastalCityYieldChanges(eYield);

		}

		if (MOD_BALANCE_YIELD_SCALE_ERA)
		{
			//Flatland City Fresh Water yields
			if (!isHills() && !isMountain() && isFreshWater())
			{
				iYield += kYield.getMinCityFlatFreshWater();
			}
			//Flatland City No Fresh Water yields
			if (!isHills() && !isMountain() && !isFreshWater())
			{
				iYield += kYield.getMinCityFlatNoFreshWater();
			}
			// Hill City Fresh Water yields
			if (isHills() && isFreshWater())
			{
				iYield += kYield.getMinCityHillFreshWater();
			}
			// Hill City No Fresh Water yields
			if (isHills() && !isFreshWater())
			{
				iYield += kYield.getMinCityHillNoFreshWater();
			}
			// Mountain City Fresh Water yields
			if (isMountain() && isFreshWater())
			{
				iYield += kYield.getMinCityMountainFreshWater();
			}
			// Mountain City No Fresh Water yields
			if (isMountain() && !isFreshWater())
			{
				iYield += kYield.getMinCityMountainNoFreshWater();
			}
			if (pPlotCity->HasGarrison())
			{
				CvUnit* pUnit = pPlotCity->GetGarrisonedUnit();
				if (pUnit != NULL && pUnit->GetGarrisonYieldChange(eYield) > 0)
				{
					int iGarrisonstrength = pUnit->GetBaseCombatStrength();
					iYield += ((pUnit->GetGarrisonYieldChange(eYield) * iGarrisonstrength) / 8);
				}
			}
		}

		int iTemp = GET_PLAYER(getOwner()).GetCityYieldChangeTimes100(eYield);	// In hundreds - will be added to capitalYieldChange below

		// Capital Mod
		if (pPlotCity->isCapital())
		{
			iTemp += GET_PLAYER(getOwner()).GetCapitalYieldChangeTimes100(eYield);

			iYield += GET_PLAYER(getOwner()).GetPlayerTraits()->GetCapitalYieldChanges(eYield);

			int iPerPopYield = pPlotCity->getPopulation() * GET_PLAYER(getOwner()).GetCapitalYieldPerPopChange(eYield);
			iPerPopYield /= 100;
			iYield += iPerPopYield;

			if (GET_PLAYER(getOwner()).GetCapitalYieldPerPopChangeEmpire(eYield) != 0)
			{
				int iPerPopYieldEmpire = GET_PLAYER(getOwner()).getCurrentTotalPop() / GET_PLAYER(getOwner()).GetCapitalYieldPerPopChangeEmpire(eYield);
				iYield += iPerPopYieldEmpire;
			}
		}

		iYield += (iTemp / 100);

		
	}
```
and now becoming something like:
```
if (pPlotCity != NULL)
	{
		iYield = std::max(iYield, kYield.getMinCity());

		if (!bDisplay || pPlotCity->isRevealed(GC.getGame().getActiveTeam(), false))
		{
			iYield += kYield.getCityChange();

			if (kYield.getPopulationChangeDivisor() != 0)
			{
				iYield += (pPlotCity->getPopulation() + kYield.getPopulationChangeOffset()) / kYield.getPopulationChangeDivisor();
			}
		}
		TeamTypes eTeam = (ePlayer != NO_PLAYER) ? GET_PLAYER(ePlayer).getTeam() : NO_TEAM;
		if (eTeam != NO_TEAM)
		{
			ResourceTypes eResource = getResourceType(eTeam);

			if (eResource != NO_RESOURCE)
			{
				iYield += GC.getResourceInfo(eResource)->getYieldChange(eYield);
#if defined(MOD_BALANCE_CORE_RESOURCE_MONOPOLIES)
				if (MOD_BALANCE_CORE_RESOURCE_MONOPOLIES && pWorkingCity != NULL && GET_PLAYER(pWorkingCity->getOwner()).HasGlobalMonopoly(eResource))
				{
					int iTemp = GC.getResourceInfo(eResource)->getYieldChangeFromMonopoly(eYield);
					if (iTemp > 0)
					{
						iTemp += GET_PLAYER(pWorkingCity->getOwner()).GetMonopolyModFlat();
						iYield += iTemp;
					}
				}
#endif
			}
		}
		// Mod for Player; used for Policies and such
		iYield += GET_PLAYER(getOwner()).GetPlayerTraits()->GetCityYieldChanges(eYield);

		// Coastal City Mod
		if (pPlotCity->isCoastal())
		{
			iYield += GET_PLAYER(getOwner()).GetCoastalCityYieldChange(eYield);

			iYield += GET_PLAYER(getOwner()).GetPlayerTraits()->GetCoastalCityYieldChanges(eYield);

		}

		if (MOD_BALANCE_YIELD_SCALE_ERA)
		{
			//Flatland City Fresh Water yields
			if (!isHills() && !isMountain() && isFreshWater())
			{
				iYield += kYield.getMinCityFlatFreshWater();
			}
			//Flatland City No Fresh Water yields
			if (!isHills() && !isMountain() && !isFreshWater())
			{
				iYield += kYield.getMinCityFlatNoFreshWater();
			}
			// Hill City Fresh Water yields
			if (isHills() && isFreshWater())
			{
				iYield += kYield.getMinCityHillFreshWater();
			}
			// Hill City No Fresh Water yields
			if (isHills() && !isFreshWater())
			{
				iYield += kYield.getMinCityHillNoFreshWater();
			}
			// Mountain City Fresh Water yields
			if (isMountain() && isFreshWater())
			{
				iYield += kYield.getMinCityMountainFreshWater();
			}
			// Mountain City No Fresh Water yields
			if (isMountain() && !isFreshWater())
			{
				iYield += kYield.getMinCityMountainNoFreshWater();
			}
			if (pPlotCity->HasGarrison())
			{
				CvUnit* pUnit = pPlotCity->GetGarrisonedUnit();
				if (pUnit != NULL && pUnit->GetGarrisonYieldChange(eYield) > 0)
				{
					int iGarrisonstrength = pUnit->GetBaseCombatStrength();
					iYield += ((pUnit->GetGarrisonYieldChange(eYield) * iGarrisonstrength) / 8);
				}
			}
		}

		int iTemp = GET_PLAYER(getOwner()).GetCityYieldChangeTimes100(eYield);	// In hundreds - will be added to capitalYieldChange below

		// Capital Mod
		if (pPlotCity->isCapital())
		{
			iTemp += GET_PLAYER(getOwner()).GetCapitalYieldChangeTimes100(eYield);

			iYield += GET_PLAYER(getOwner()).GetPlayerTraits()->GetCapitalYieldChanges(eYield);

			int iPerPopYield = pPlotCity->getPopulation() * GET_PLAYER(getOwner()).GetCapitalYieldPerPopChange(eYield);
			iPerPopYield /= 100;
			iYield += iPerPopYield;

			if (GET_PLAYER(getOwner()).GetCapitalYieldPerPopChangeEmpire(eYield) != 0)
			{
				int iPerPopYieldEmpire = GET_PLAYER(getOwner()).getCurrentTotalPop() / GET_PLAYER(getOwner()).GetCapitalYieldPerPopChangeEmpire(eYield);
				iYield += iPerPopYieldEmpire;
			}
		}

		iYield += (iTemp / 100);

		
	}
```

**Comment by Infixo** [comment]
Like I said - perhaps I really don't understand english. My comment was about that:
"We just need to remove calculateNatureYield from calculateYieldFast and add it into calculatePlayerYield from the beginning."

All I am saying is that yields related to city settling should be calculated in "nature" sections, not "player" because they are related to a terrain not a player. So you actually need to move getMinCity() from calculatePlayerYield into calculateNatureYield, not shuffle around when calculateNatureYield is called.

**Comment by Infixo** [comment]
I leave my comments to your consideration, have nothing more to add.
