### ISSUE TITLE
Yield improvements from techs / policies don't work

### ISSUE THREAD

**Issue by Grabbl** [LoneGazebo/Community-Patch-DLL#4419]
_1. Mod version (i.e Date - 4/23):_
5-20-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Serfdom policy (of the Fealty tree) and the Steel tech don't improve pastures / mines, possibly also other yield improvements. Yields from buildings (like forge) seem to work.

![20180522122317_1](https://user-images.githubusercontent.com/19163988/40357158-8d283166-5dbb-11e8-93bd-9644e6f64a5a.jpg)
The mine next to the Dyes has +1 production (base) + 2 from Forge. Steel is researched and should give another +1 production.

![20180522122308_1](https://user-images.githubusercontent.com/19163988/40357215-bd210ba4-5dbb-11e8-9a09-f6b12c607d5d.jpg)
The pastures all have their base yields. Serfdom is adopted (a few turns ago, not recently) and should give +1 gold/production. The other part of Serfdom works.

Save / Logs:
[YieldBug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2026179/YieldBug.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Iamblichos** [comment]
I'm on it.

**Comment by Infixo** [comment]
I think the problem is here:
```
	if(bOptimal || ePlayer == NO_PLAYER)
	{
		for(iI = 0; iI < GC.getNumTechInfos(); ++iI)
		{
			iYield += pImprovement->GetTechYieldChanges(iI, eYield);
```
bOptimal is usually false, so GetTechYieldChanges() is called only for tiles without owner which is the opposite of what we want here. Changing condition into ePlayer != NO_PLAYER should probably fix it.

**Comment by Iamblichos** [comment]
@Infix you want me haul the player tech and traits from calculatePlayerYield() above into calculateImprovementYield()?

**Comment by Iamblichos** [comment]
This piece right here:
```
CvTeam& kTeam = GET_TEAM(kPlayer.getTeam());

			iYield += kPlayer.getImprovementYieldChange(eImprovement, eYield);

			if (!kPlayer.GetPlayerTraits()->IsTradeRouteOnly())
			{
				iYield += kPlayer.GetPlayerTraits()->GetImprovementYieldChange(eImprovement, eYield);
			}
			iYield += kTeam.getImprovementYieldChange(eImprovement, eYield);

			if (isFreshWater())
			{
				iYield += kTeam.getImprovementFreshWaterYieldChange(eImprovement, eYield);
			}
			else
			{
				iYield += kTeam.getImprovementNoFreshWaterYieldChange(eImprovement, eYield);
			}
```

used to be under calculateImprovementYieldChange() now calculateImprovementYield()

**Comment by Iamblichos** [comment]
in calculateImprovementYield() is there even a reason to do this at all, what's the purpose? Does this get used for evaluating buldertaksing for tiles outside of our borders?

```
if(bOptimal || ePlayer == NO_PLAYER)
	{
		for(iI = 0; iI < GC.getNumTechInfos(); ++iI)
		{
			iYield += pImprovement->GetTechYieldChanges(iI, eYield);

			if(bIsFreshWater)
			{
				iYield += pImprovement->GetTechFreshWaterYieldChanges(iI, eYield);
			}
			else
			{
				iYield += pImprovement->GetTechNoFreshWaterYieldChanges(iI, eYield);
			}
		}

		for(iI = 0; iI < GC.getNumPolicyInfos(); ++iI)
		{
			const PolicyTypes ePolicy = static_cast<PolicyTypes>(iI);
			CvPolicyEntry* pkPolicyEntry = GC.getPolicyInfo(ePolicy);
			if(pkPolicyEntry)
			{
				iYield += pkPolicyEntry->GetImprovementYieldChanges(eImprovement, eYield);
			}
		}
	}
```
If not, I don't see a reason to do this we just do:

```
CvPlayerAI& kPlayer = GET_PLAYER(ePlayer);
		CvTeam& kTeam = GET_TEAM(kPlayer.getTeam());

		iYield += kPlayer.getImprovementYieldChange(eImprovement, eYield);
		iYield += kTeam.getImprovementYieldChange(eImprovement, eYield);

		if(bIsFreshWater)
		{
			iYield += kTeam.getImprovementFreshWaterYieldChange(eImprovement, eYield);
		}
		else
		{
			iYield += kTeam.getImprovementNoFreshWaterYieldChange(eImprovement, eYield);
		}
```

Leaving the player trait improvement yields in calculatePlayerYields().

**Comment by Iamblichos** [comment]
I think the reason this exists "if(bOptimal || ePlayer == NO_PLAYER)" is if a city gets razed, and there's no owner of the plots, the improvements keep their existing tech and policy yields or so I assume.

**Comment by LoneGazebo** [comment]
I think it’s for display @iamblichos for stuff like EUI’s predictive yields.

**Comment by Iamblichos** [comment]
I've got it fixed. Just tiding up the book keeping.

**Comment by Iamblichos** [comment]
Pushed to master. @Infixo will start implementing your ticket suggestion next time. I did my fix push and sync up to master in one push.
