### ISSUE TITLE
can't build pioneers

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#442]
on 7/21/v2 version:

pioneers can be selected in city build list, but when finished the unit never appears.

any ideas?

**Comment by LoneGazebo** [comment]
That's odd. Is it tossing out any errors?

**Comment by ilteroi** [comment]
not that i can see ... i guess i need to start digging, any hints where to look first?

**Comment by LoneGazebo** [comment]
I tried it last night and it worked fine for me. Hmm...

**Comment by ilteroi** [comment]
oops. it turns out they were silently removed from the build queue because my empire was unhappy. quite confusing. maybe for a human we should not do this but simply prevent founding.
