### ISSUE TITLE
Incorrect XP reward for City State 'Capture City' Quest

### ISSUE THREAD

**Issue by Skrunchy-0** [LoneGazebo/Community-Patch-DLL#4420]
_1. Mod version (i.e Date - 4/23):_
4/30

_2. Mod list (if using Vox Populi only, leave blank):_
Various Global and UI mods from WHoward's Pick'N'Mix

_3. Error description:_ 
Tool tip states I am to receive 150 xp for my units.  Actually receive 450 or more.

_4. Steps to reproduce (optional):_
Fulfill city state Capture City quest

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
What game speed? Marathon?

**Comment by MoiMagnus** [comment]
Yes, it was marathon (see https://forums.civfanatics.com/threads/new-version-april-30th-4-30.631936/page-20).
I think the problem is that marthon scaling is applied twice:
Quest has base value 50XP, but marthon scale it to 150XP (as the tooltip says), and the real value is 450XP.

**Comment by MoiMagnus** [comment]
I don't know about why the base value is 50. It may not be the case (it was just a theory from the numbers).
I think the CS personality influence the value, so if the random scored the maximum value on an irrational CS, maybe it can reach 50?

**Comment by cdanger341** [comment]
I can confirm that this "bug" has been in the game since unit XP per level scaling based on game speed was added. I play on Epic so the bug isn't as obvious, but I watched a few Marathon speed games and it does appear to be doubly applying the game speed scalar.

By default the reward should be between 10-20 XP, so if 20 XP was randomly picked, this value would display as "60 XP" in the quest description on Marathon speed, but then give each unit 180 XP when the quest is completed.

**Comment by Skrunchy-0** [comment]
Noticed it's been tagged as Fixed for upcoming version!  Thanks!


Anyway I can fix it now for my current game or is this hard coded?

**Comment by LoneGazebo** [comment]
hard coded

**Comment by LoneGazebo** [comment]
and the value is set when the quest is created, so enjoy your super-powered units for a game (or delete a few)

**Comment by Skrunchy-0** [comment]
:( Darn.

Any idea when the fix is coming?  Next patch update?

**Comment by LoneGazebo** [comment]
yes

**Comment by Skrunchy-0** [comment]
Feels like cheating... playing Russia...9 techs ahead of everyone... 126 units fully maxed on promotions...
