### ISSUE TITLE
Workers constructing farms ask for action after save load

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4421]
_1. Mod version (i.e Date - 4/23):_
5-20-1

Subj. Workers that construct roads/mines are fine.
And worker don't have an order to construct, but on next turn after load all becomes good.
![20180522204449_1](https://user-images.githubusercontent.com/13381981/40380215-179de6e8-5e01-11e8-897d-7b727f538e3e.jpg)

**Comment by LoneGazebo** [comment]
Might be a consequence of the danger cache reset - @ilteroi is that possible?
