### ISSUE TITLE
Councils of Elders gives wrong yields

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#4425]
_1. Mod version (i.e Date - 4/23):_
5-20-3

_2. Mod list (if using Vox Populi only, leave blank):_
Historical Religions Edit (BNW or GK) (v 45)
JFDLC (07) - JFD's Cultural Diversity (Core) (v 16)
JFDLC (07a) - JFD's Cultural Diversity (Soundtrack)
Unit Path Viewer (v10)

_3. Error description:_ 
My understanding is that when converting cities, it gives 30/30, 60/60, 90/90 and so on. However in my case, it only gives 30/30 and 60/60 for the first and second cities. The rest only adds 1/1 or 2/2 cumulatively. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Aztec logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2029412/Aztec.logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Aztec saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2029411/Aztec.saves.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
That is no longer how it works. Now it is exponential:
base value (30 * (100 + (numcitiesfollowing*numcitiesfollowing)) / 100

G
