### ISSUE TITLE
Oasis not giving fresh water bonus

### ISSUE THREAD

**Issue by Rustonreddit** [LoneGazebo/Community-Patch-DLL#4429]
_1. Mod version (i.e Date - 4/23):_
5-20-3

_2. Mod list (if using Vox Populi only, leave blank):_
Infoaddict

_3. Error description:_ 
Any yield adjacent to an oasis shows the correct value but the calculations dont add up those bonuses.

In the screenshot:
1. Should be:
3F from City + 1F Horses + 3F Oasis + 4F Farm wheat + 3 Religion (god of the sea) = 14 Total

2. Its only getting:
2F from City + 1F Horses + 3F Oasis + 3F Farm wheat + 3 Religion = 12 Total
![oasis](https://user-images.githubusercontent.com/39557837/40424467-fce6c348-5e95-11e8-99f9-45b75e15b6e2.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Rustonreddit** [comment]
![oasis 2](https://user-images.githubusercontent.com/39557837/40424914-2f3911b0-5e97-11e8-9618-9c391523ad19.png)

Loading the game again Farm Wheat now shows 3F (the real value is summing up) instead of 4F

**Comment by Rustonreddit** [comment]
Im freaking out. Probably doing something wrong.

Lakes only give 2 Food / 0 Hammers
![lake](https://user-images.githubusercontent.com/39557837/40425699-607c25d0-5e99-11e8-9e2e-3dcac175dbe6.png)
![lake 2](https://user-images.githubusercontent.com/39557837/40425716-6c8d711c-5e99-11e8-82d7-39e4c0275eb0.png)

**Comment by Rustonreddit** [comment]
And river cities only 2 F
![river](https://user-images.githubusercontent.com/39557837/40425752-86d450c2-5e99-11e8-85fc-e7013f3af8a6.png)

**Comment by Iamblichos** [comment]
Can you give me a save so I can see what’s going on?

**Comment by Rustonreddit** [comment]
Started a new game. Everything works perfect.
![new game](https://user-images.githubusercontent.com/39557837/40426158-a163d272-5e9a-11e8-843b-650fdf21c98b.png)

Is the other game corrupt or something?

**Comment by Iamblichos** [comment]
Do some improvements and build some buildings or do some policies that change improvements, and then get back to me. I can tell you right now that I'm playing into the late game and I have a modmod that is very sensitive to yield calculations and everything is perfect on yield calculations (though I haven't looked into the oasis thing).

**Comment by Rustonreddit** [comment]
Ok. Lol. I just press next turn and everything that was incorrect changed to correct. All yields are ok now. wtf

**Comment by Rustonreddit** [comment]
I just went back to another save point and the same happened. The bonus yield (rivers, lakes, etc) didnt show until i press next turn. Maybe the game needs to get running to show the real yields. Thanks for the support  anyways. My bad if i wasted your time with this.

**Comment by Rustonreddit** [comment]
Are the cities on hills suppose to give 2F/3H? That is what im getting now. I thought it was 2F/2H

**Comment by Iamblichos** [comment]
@LoneGazebo upped the yield on city plot hills by 1P. Yep.

**Comment by Rustonreddit** [comment]
Thanks. It was already good 2F/2H, so i guess no reason to not settle on hills now. Just for curiosity, whats the reason for the +1? (I guess this things are better to talk on the real forum, no?)

**Comment by Iamblichos** [comment]
I think because hills weren't getting anything like flat land was.
