### ISSUE TITLE
I keep getting a late game crash on DoLiberatePlayer

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#4430]
![image](https://user-images.githubusercontent.com/14372214/40446194-0542a9c8-5e94-11e8-934b-999112d9bd1f.png)

![image](https://user-images.githubusercontent.com/14372214/40446199-0e1c74ac-5e94-11e8-80b4-1ee43ce5ea15.png)

**Comment by Iamblichos** [comment]
I remember getting this crash same place on 4-30 as well.

**Comment by ilteroi** [comment]
apparently pNewCity is NULL.

don't know if that indicates a problem in acquireCity or not

**Comment by Iamblichos** [comment]
I added in a check for if (pNewCity) right before we do that in DoLiberatePlayer but no dice.

I then tried:

```
int iWarmongerOffset = CvDiplomacyAIHelpers::GetPlayerCaresValue(GetID(), ePlayer, pNewCity->isCapital() ? true : false, pNewCity, GetID(), true);
					if (iWarmongerOffset != 0)
						GET_PLAYER(eMajor).GetDiplomacyAI()->ChangeOtherPlayerWarmongerAmountTimes100(GetID(), -iWarmongerOffset);
```

and that seemed to work...

**Comment by ilteroi** [comment]
that's cargo cult programming ... anyway another possibility is that pNewCity is invalid, ie referencing a city which has since been deleted. typically pOldCity. in that case the null check wouldn't help. and it wouldn't even crash every time, if the memory content is still there.

**Comment by Iamblichos** [comment]
Yeah I know...but I'm just trying to get passed it haven't had much success trying something else. The city doesn't get deleted, because it's a city state. Not sure if it went back and forth between Denmark and Japan trying to wrestle it away (and in the latter's case liberate it).

**Comment by Iamblichos** [comment]
And you're right, you can load up the same save and try it multiple times. Sometimes you pass, sometimes not...so yeah, you're intuition about is right.

**Comment by LoneGazebo** [comment]
Looking at the stack, it seems that a captured unit is spawning in the city, causing it to instantly flip the city( possibly flipping it to another player), no?

**Comment by Iamblichos** [comment]
It should just be a civilian unit though, like a worker getting captured, unless they returned the unit?? Shouldn't cause the city to flip.

**Comment by LoneGazebo** [comment]
No idea, just spitballing.

**Comment by Iamblichos** [comment]
In this function what if we put at the top
```
CvPlayerAI::AI_conquerCity()

if (!pCity)
		return;
```

**Comment by ilteroi** [comment]
here's the thing: any time a city changes ownership, a new one is created. some stuff is copied over from the old one. then the old one is deleted.

**Comment by Iamblichos** [comment]
I think the capture definition is a redherring, because that happens all the time with civilians. Here's what I think is going on.
Both civs that were conquering that city state get a free building from NewCityFreeBuilding (via policy). THAT building does a Building_FreeUnit (which grants a free worker). I dunno but my hunch is that initializing a new fresh unit in there every time is screwing it up.

**Comment by Iamblichos** [comment]
No, if you look in the call stack, there is a captureunit call (it's a civilian or a bunch of 'em). On city capture, it creates that capture definition. Is that the problem? I doubt it. I think the problem is elsewhere with Building_FreeUnit in this scenario. Goes something like this: Player -> conquers an old existing city state (which has a major player owner) -> Gets Free building "NewCityFreeBuilding" from policy -> that building grants a free unit -> unit initializes on city plot -> Bringing city back to conquerer? -> AI_conquerCity -> Liberates -> pNewCity = NULL.  Or so I'm thinking....

**Comment by Iamblichos** [comment]
Basically I think @LoneGazebo is right but not for the reasons otherwise we'd be crashing all the time capturing cities with civilians in them. But is hunch is correct--or so I am assuming--an initializing unit on that city plot is causing a problem when the AI does AI_conquerCity.

**Comment by ilteroi** [comment]
ah. sounds plausible. but the comment in SetXY seems to be aware of potential issues here:

```
										// If we're capturing the unit, we want to delay the capture, else as the unit is converted to our side, it will be the first unit on our
										// side in the plot and can end up taking over a city, rather than the advancing unit
										CvUnitCaptureDefinition kCaptureDef;
										if(bDoCapture)
										{
											if(pLoopUnit->getCaptureDefinition(&kCaptureDef, getOwner()))
												kCaptureUnitList.push_back(kCaptureDef);
											pLoopUnit->setCapturingPlayer(NO_PLAYER);	// Make absolutely sure this is not valid so the kill does not do the capture.
										}
```

and consequently acquireCIty() is called before createCapturedUnit(). 

what's more, i think a civilian can't even capture?

anyway this needs more research ...

**Comment by Iamblichos** [comment]
Yeah a civilian can't capture anything. That doesn't support my theory. What's being captured is a couple of workers and a couple of generals. All civilians. And then what is initialized from Building_FreeUnit is another worker. But you guys haven't gotten this kind of crash right? So the only difference I can tell is Building_FreeUnit where that BuildingType is free for newly acquired city. It still shouldn't crash though. I don't get the crash every time I try to repeat that same turn, but I don't think the AI in AI_conquerCity is making the same choice to liberate it every time either...so...
