### ISSUE TITLE
No pop-ups after install of 5-20

### ISSUE THREAD

**Issue by gstew32** [LoneGazebo/Community-Patch-DLL#4432]
_1. Mod version (i.e Date - 4/23):_version 5-20-3

_2. Mod list (if using Vox Populi only, leave blank):_1,2,3,4,5,6b, (7) Community events, (8) E&D, (9) Wonders Expanded, info adict, More unique components v30, Unique city states v2

_3. Error description:_ 
After upgrading the mod from 4-20 to 5-20 I have noticed that I get no popups in game, including when building wonders or when contacting city states.  I think I've heard on this happening in the past, but don't recall how to fix it.  I have reinstalled VP and tried on various games.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
My guess is a mod conflict. Install just VP and see what happens. Then add in other mods until you find the culprit.
