### ISSUE TITLE
Embarknig without entering my teritory

### ISSUE THREAD

**Issue by wistak103** [LoneGazebo/Community-Patch-DLL#4434]
_1. Mod version (i.e Date - 4/23):_
5-20-3

_2. Mod list (if using Vox Populi only, leave blank):_
Promotions Flag EUI
UI Destination, Filters in Trade.. , Improved City View, Promotion and Uprage Tree, Religion Spread, Show XP in Military..
Unique City States

_3. Error description:_ 
My units can embark without entering my teritory after researching fishing

**Comment by ilteroi** [comment]
it's not a bug, it's a feature!

**Comment by Iamblichos** [comment]
Yes so much better...what a hassle to drag some unit out in the middle of nowhere all the way back to your territory just to be able to embark. blah.

**Comment by MoiMagnus** [comment]
@wistak103 Did you found any outdated text about that?

**Comment by wistak103** [comment]
Yep I think that in tech is phrase:
" every unit that enter friendly territory "

**Comment by wistak103** [comment]
I don't see it in changelog

**Comment by ilteroi** [comment]
yeah the changelog is an incomplete summary of inaccurate commit messages
