### ISSUE TITLE
Hopeless to attempt to liberate or return a city (CP-Only)

### ISSUE THREAD

**Issue by 1-CityWonder** [LoneGazebo/Community-Patch-DLL#4435]
_1. Mod version (i.e Date - 4/23):_
4/30

_2. Mod list (if using Vox Populi only, leave blank):_
Just Community Patch

_3. Error description:_ 
Capturing a city-state that I have always been allied with that was captured by another player, there is no option to liberate the city-state.  It always simply conquers the city-state in late (200+ turn) game.  

_4. Steps to reproduce (optional):_
In this save game, any attempt to conquer the city state Milan will end up taking it over.  No option to liberate.  I am pretty sure if I tried to conquer any city that used to be another player (in this game, Japan or Spain) then it would also only conquer the city and no option to raze or return to original owner.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Sejong_0404 AD-1984.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2040021/Sejong_0404.AD-1984.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by wistak103** [comment]
I have this on my multiplayer games several times on v 4-30 too
Sometimes popups show in next turn but usually auto annex

**Comment by wistak103** [comment]
Rather in midlate game

**Comment by ilteroi** [comment]
maybe my fault. need to check

**Comment by ilteroi** [comment]
nope, works for me

![image](https://user-images.githubusercontent.com/1358966/40562799-bdde1d9e-6062-11e8-9c56-b5ca9d4e9a46.png)

**Comment by LoneGazebo** [comment]
@ilteroi if you trigger a CS to spawn using revolt and then do it, does it still work?

**Comment by ilteroi** [comment]
unfortunately i don't know how to do that, but the only important thing is the original owner. and judging from the icon in the city banner, that is set correctly after a revolt

**Comment by TechpriestEnginseer** [comment]
@ilteroi  https://github.com/LoneGazebo/Community-Patch-DLL/issues/4106

**Comment by LoneGazebo** [comment]
Game.DoSpawnFreeCity(Players[1].GetCapitalCity()) in firetuner will flip the capital of player 1 to a CS....

**Comment by wistak103** [comment]
I am playing now with 5-20-3 and 
My first conquered city has this same issue
But second and third worked fine (I think that I had it only on multiplayer) 
I'll try to get a save

**Comment by wistak103** [comment]
Also occupied cities don't add unhappiness

**Comment by 1-CityWonder** [comment]
Not reproduced in the savegame or in one from scratch?  Because I noticed this happens more in late game while at start sometimes seems to work fine.

**Comment by MoiMagnus** [comment]
Note that this bug is probably no new, and not reproducible (reload may fix it).

I remember seeing multiple time in the last year "I captured a city and it was auto-annexed, so I reloaded at the beginning of the turn and captured again, then no problems".

**Comment by 1-CityWonder** [comment]
It's definately quite a bug though.  Because I have gone over many different auto save moments and it's always happening.  And not only does it force a capture, but it shuts down my capital as well.  Both cities become unusable.

This is with just the Community Patch. 

![forced to capture milan](https://user-images.githubusercontent.com/26146152/40578304-af57cb44-60df-11e8-8af7-0c09be6cf488.jpg)
![capital unusable](https://user-images.githubusercontent.com/26146152/40578305-b1aa2586-60df-11e8-9393-8f50aa52a2c0.jpg)

**Comment by Iamblichos** [comment]
Seems like a UI quirk.

**Comment by 1-CityWonder** [comment]
This UI quirk is a huge bug for those who play CP-only!  It's impossible to continue playing after this comes up.  So it's not just not being able to return cities, but it's making my capital useless as well.  

**Same Thing Again - This is my former capital city (now useless)**
![same thing again - capital city](https://user-images.githubusercontent.com/26146152/40850071-a7c41520-6591-11e8-8bdb-bd6032dd0e54.jpg)

**This is the Formerly Japanese city that I captured from America**
![same thing again - japan city captured by america](https://user-images.githubusercontent.com/26146152/40850128-cdb927b6-6591-11e8-81ef-cee662d6ecfe.jpg)

This save, from different times.
[CP-Only Capture Captured Cities Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2063295/CP-Only.Capture.Captured.Cities.Bug.zip)

**Comment by LoneGazebo** [comment]
Can't help without lua.log. Enable logging, replicate the event, then post those logs.

G

**Comment by 1-CityWonder** [comment]
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2064135/Lua.log)

> [87166.343] TopPanel: Finished loading EUI top panel	108.781
[87186.640] Runtime Error: Assets\DLC\UI_bc1\CityBanners\CityBannerManager.lua:272: Instance does not exist.
[87187.640] InGame: OnInterfaceModeChanged
[87187.640] InGame: oldInterfaceMode: 1
[87187.640] InGame: newInterfaceMode: 11
[87189.109] InGame: OnInterfaceModeChanged
[87189.109] InGame: oldInterfaceMode: 11
[87189.109] InGame: newInterfaceMode: 1
[87189.546] Runtime Error: Assets\DLC\UI_bc1\CityBanners\CityBannerManager.lua:272: Instance does not exist.
[87192.968] Runtime Error: Assets\DLC\UI_bc1\CityBanners\CityBannerManager.lua:272: Instance does not exist.
[87203.765] Runtime Error: Assets\UI\InGame\PopupsGeneric\PuppetCityPopup.lua:61: Instance does not exist.>

**Comment by Iamblichos** [comment]
The Community Patch only packaged with the installer does not have an option for EUI install. Yet you are using EUI. And the CityBannerManager packaged with the Community Patch only is incompatible with EUI.

**Comment by vand3537** [comment]
I have similar error:
Assets\UI\InGame\PopupsGeneric\PuppetCityPopup.lua:61: Instance does not exist.
I don't get the CityBannerManager errors though
I can never liberate a city, it auto-annexes, and after, I can no longer see the list of things to build in cities.  game over
