### ISSUE TITLE
Barbarians cause resyncs again

### ISSUE THREAD

**Issue by Voker57** [LoneGazebo/Community-Patch-DLL#4436]
_1. Mod version (i.e Date - 4/23):_

5-20.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

With Barbarians enabled, game resyncs every other turn and fighting events appear to be out of sync (units become wounded, disappear, etc.)

_4. Steps to reproduce (optional):_

Start new MP  game with at least two players, enable Barbarians, play several turns

**Comment by LoneGazebo** [comment]
Nothing was changed on this front from 4-20, so this is probably client-side.

**Comment by wistak103** [comment]
hmm we had the same problem 

well 1 of 3 players was diffrent so it may be reason why 
I will post when we test on the same players who played 4-30

before 4-30 last version with working barbarians was 7-20 from 2017 and i didn't saw any changes on this front in changelogs on any version till 4-30 so this may be something in other place

**Comment by supermerill** [comment]
@wistak103 see https://github.com/LoneGazebo/Community-Patch-DLL/pull/4331

**Comment by LoneGazebo** [comment]
@davenye care to chime in?

**Comment by MoiMagnus** [comment]
I start seeing other people talking about barbarian desync, so that's probably not a client issue.

**Comment by ilteroi** [comment]
helpful forum post says 5-20-2 was good but 5-20-3 is bad. that narrows it down ...

**Comment by LoneGazebo** [comment]
@ilteroi @iamblichos last time this was related to tactical and trade AI caches not resetting properly. @davenye does that sound about right?

**Comment by Iamblichos** [comment]
Only thing I saw between 4-30 and 5-20 was a change to plot visibility that Dave did.

**Comment by MoiMagnus** [comment]
Plot visibility was a huge things causing Desync in multiplayer.
(If I understood correctly, it was not propagated correctly to other players, so barbarians camps where not spawned at the same position for everybody)
That makes this change a very probable culpric.

**Comment by Iamblichos** [comment]
@LoneGazebo do you need help pin pointing the change? Or do you have a handle on it?
