### ISSUE TITLE
Feitoria not providing adjacency bonus

### ISSUE THREAD

**Issue by GhettoSpud** [LoneGazebo/Community-Patch-DLL#4438]
_1. Mod version (i.e Date - 4/23):_
5-20-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Feitoria description incongruent with behavior:
* Can be built next to any coastal OR lake tiles (states only coastal)
* Does not provide +1 gold to any adjacent coast/lake, only provides this if fishing boats are present (in addition to the +1 production)
  * Additionally, while description states both lake/coast should receive +1 gold, bonus box in civilopedia only lists coast

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
[details.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2042271/details.zip)

**Comment by Iamblichos** [comment]
@LoneGazebo here's the problem with this one.

In calculateImprovementYield() we have:
```
iYield = pImprovement->GetYieldChange(eYield);

	if (ePlayer != NO_PLAYER)
	{
		CvPlayerAI& kPlayer = GET_PLAYER(ePlayer);

		if (iYield > 0)
		{
			int iAdjacentYield = pImprovement->GetYieldAdjacentSameType(eYield);
			if (iAdjacentYield > 0)
			{
				iYield += ComputeYieldFromAdjacentImprovement(*pImprovement, eImprovement, eYield);
			}

			int iTwoAdjacentYield = pImprovement->GetYieldAdjacentTwoSameType(eYield);
			if (iTwoAdjacentYield > 0)
			{
				iYield += ComputeYieldFromTwoAdjacentImprovement(*pImprovement, eImprovement, eYield);
			}

			if (eYield == YIELD_CULTURE)
			{
				iYield += kPlayer.GetPlayerPolicies()->GetNumericModifier(POLICYMOD_EXTRA_CULTURE_FROM_IMPROVEMENTS);
				iYield += kPlayer.GetPlayerPolicies()->GetImprovementCultureChange(eImprovement);
			}
		}
```
But if plot doesn't at least have one yield already from pImprovement->GetYieldChange(eYield), than it never passes iYield > 0 check.

**Comment by LoneGazebo** [comment]
Just need to shunt the yield through this function as well, good eye.

G
