### ISSUE TITLE
too many wonders?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4440]
just a little oddity i noticed:

it's turn 138 and japan built 4 wonders but no settler so far. probably a losing strategy ...

![image](https://user-images.githubusercontent.com/1358966/40599258-9d6772a4-624c-11e8-886e-af3189d47e12.png)

logs here
[CityStrategyAIProductionLog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2043766/CityStrategyAIProductionLog.zip)

**Comment by pineappledan** [comment]
In 5/30 version, I had a game where Songhai built 2 wonders and declared war on his neighbor (Austria) before ever building a settler. I had 5 cities before he had 2. He lost.

**Comment by Iamblichos** [comment]
The build sanity is pretty tight in 6/14. Not seeing this anymore.
