### ISSUE TITLE
Events and Dead Civs

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4441]
Does the event data for dead civs recently re-liberated disappear? It seems unfortunate that permanent events won't seem to be permanent if they're brought back to life or some other mere revival magic. (While I wonder if temporary events still countdown and expire normally.)

**Comment by LoneGazebo** [comment]
I don't see anything in the code that resets these values...you sure they go away?

**Comment by TechpriestEnginseer** [comment]
It's a weird consistency, I'll have to figure out the underlying primary cause of this issue. I'll get back to this later should the particular modmod rise up.
