### ISSUE TITLE
Citadels and other improvements that cause nearbyenemydamage()

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#4444]
bool CvPlot::IsNearEnemyCitadel(PlayerTypes ePlayer, int* piCitadelDamage) const
{
	VALIDATE_OBJECT

	int iCitadelRange = 1;
	CvPlot* pLoopPlot;

	ImprovementTypes eImprovement;
	int iDamage;

	// Look around this Unit to see if there's an adjacent Citadel
	for(int iX = -iCitadelRange; iX <= iCitadelRange; iX++)
	{
		for(int iY = -iCitadelRange; iY <= iCitadelRange; iY++)
		{
			pLoopPlot = plotXYWithRangeCheck(getX(), getY(), iX, iY, iCitadelRange);

			if(pLoopPlot != NULL)
			{
				eImprovement = pLoopPlot->getImprovementType();

				// Citadel here?
				if(eImprovement != NO_IMPROVEMENT && !pLoopPlot->IsImprovementPillaged() && GC.getImprovementInfo(eImprovement)->GetNearbyEnemyDamage() != 0)
				{
					iDamage = GC.getImprovementInfo(eImprovement)->GetNearbyEnemyDamage();
					if(pLoopPlot->getOwner() != NO_PLAYER)
					{
						if(GET_TEAM(GET_PLAYER(ePlayer).getTeam()).isAtWar(pLoopPlot->getTeam()))
						{
							if(piCitadelDamage)
								*piCitadelDamage = iDamage;
							return true;
						}
					}
				}
				// Unit here that acts like a citadel?
				else if (pLoopPlot->getNumUnits() != 0)
				{
					for (int iZ = 0; iZ < pLoopPlot->getNumUnits(); iZ++)
					{
						CvUnit* pLoopUnit = pLoopPlot->getUnitByIndex(iZ);
						if (pLoopUnit != NULL && pLoopUnit->getNearbyEnemyDamage() != 0 && GET_TEAM(GET_PLAYER(ePlayer).getTeam()).isAtWar(pLoopUnit->getTeam()))
						{
							iDamage = pLoopUnit->getNearbyEnemyDamage();
							if (piCitadelDamage)
								*piCitadelDamage = iDamage;
							return true;
						}
					}
				}
			}
		}
	}
	return false;
}

We want to get the strongest damage here but it's going to return true to the first plot that gives enemy damage, that may not be the strongest one. I recommend rewriting this function, as an example:

Something like this:
```
int CvPlot::GetDangerPlotDamage(PlayerTypes ePlayer) const
{
	VALIDATE_OBJECT

	int iCitadelRange = 1;
	CvPlot* pLoopPlot;

	ImprovementTypes eImprovement;
	int iDamage = 0;
	int iTemp;
	int iTemp2;
	// Look around this Unit to see if there's an adjacent Citadel
	for(int iX = -iCitadelRange; iX <= iCitadelRange; iX++)
	{
		for(int iY = -iCitadelRange; iY <= iCitadelRange; iY++)
		{
			pLoopPlot = plotXYWithRangeCheck(getX(), getY(), iX, iY, iCitadelRange);

			if(pLoopPlot != NULL)
			{
				eImprovement = pLoopPlot->getImprovementType();

				// Citadel here?
				if(eImprovement != NO_IMPROVEMENT && !pLoopPlot->IsImprovementPillaged() && GC.getImprovementInfo(eImprovement)->GetNearbyEnemyDamage() != 0)
				{
					iTemp = GC.getImprovementInfo(eImprovement)->GetNearbyEnemyDamage();
					if(pLoopPlot->getOwner() != NO_PLAYER)
					{
						if(GET_TEAM(GET_PLAYER(ePlayer).getTeam()).isAtWar(pLoopPlot->getTeam()))
						{
							if (iTemp > iDamage)
								iDamage = iTemp;
						}
					}
				}
				// Unit here that acts like a citadel?
				if (pLoopPlot->getNumUnits() != 0)
				{
					for (int iZ = 0; iZ < pLoopPlot->getNumUnits(); iZ++)
					{
						CvUnit* pLoopUnit = pLoopPlot->getUnitByIndex(iZ);
						if (pLoopUnit != NULL && pLoopUnit->getNearbyEnemyDamage() != 0 && GET_TEAM(GET_PLAYER(ePlayer).getTeam()).isAtWar(pLoopUnit->getTeam()))
						{
							iTemp2 = pLoopUnit->getNearbyEnemyDamage();
							if (iTemp2 > iDamage)
								iDamage = iTemp2;
						}
					}
				}
			}
		}
	}
	return iDamage;
}
```

**Comment by Iamblichos** [comment]
I saw this in the forum, and just looking at the code it makes sense why they had an issue:

https://forums.civfanatics.com/threads/shoshone-encampment-and-citadel-bug.632961/

**Comment by LoneGazebo** [comment]
@Iamblichos it'd probably make the most sense to simply get the largest, not the cumulative. Otherwise 3 adjacent citadels would do 90 damage, etc. etc.

G

**Comment by Iamblichos** [comment]
It's not cumulative. Just comparative. iTemp is your possible candidate, whichever one is the largest plot gets to be iDamage.
