### ISSUE TITLE
Lakes are not providing production

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#4446]
5/20

Despite the hammer icon, lake tiles do not increase my city production. Screenshot shows switching from 2F1P to (theoretical) 3F1P lake tile and production dropping.

![tiles](https://user-images.githubusercontent.com/24731508/40764872-c8cfa6ea-64aa-11e8-890a-698350f797fc.png)

**Comment by Enrico-Swagolo** [comment]
I've seen flood plains with Petra not provide me +1 Gold, and the +1 Gold icon didn't even appear over the tile before a few turns later.

**Comment by Iamblichos** [comment]
Will look into this today. To save time, can you send me your save file so I can tinker with the problem?

**Comment by Enrico-Swagolo** [comment]
I don't have a save with Petra, because I saw the same thing (also with Petra) reported in another thread.

**Comment by OpusMaius** [comment]
If I may I would like to add that despite I didn't realize this issue sooner, I did a test reloading a savegame from quite early in my current run (Vox Populi EUI, no events, no 43 civs, no ruins, no other mods though I was running Infixo's UI mods before the test, lakes map, playing Russia so no special interaction with lakes) and noticed the exact same problem PLUS a food one as you can notice: 

![foodfromlakes](https://user-images.githubusercontent.com/39679446/40783371-7a20bb46-64e2-11e8-9e2d-aea35bca5eb0.png)

It's a bit like lakes had the same yield as basic deep ocean tiles to say +2 Food only

Thank you. Super stable version by the way.


[Catherine_0122 AD-0175.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2058296/Catherine_0122.AD-0175.zip)

**Comment by Iamblichos** [comment]
I count 15 from food on the top one. You agree?

**Comment by MoiMagnus** [comment]
Maybe the herbalist is counted (half a food per forest) is counted in Terrain. That would make 16.

**Comment by OpusMaius** [comment]
Oh dear I forgot to include the plains/ horses tile in the East that gives +1 food in this screen. Was checking the aqueduct on the second city and it seems like the food yields given by the lakes are still +2 food only but I guess I miss something. Thank you for your help!

**Comment by OpusMaius** [comment]
Cleared cache, uninstalled etc and on reload and pass turn everything is OK, the aqueducts are fine and so are the yields, the +1 production ones from the lakes too by the way. Sorry for the fake alert! Thank you very much for your time.

**Comment by RandomNub** [comment]
[Haile Selassie_0015 BC-3400.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2059437/Haile.Selassie_0015.BC-3400.zip)

Clearing cache and reloading didn't fix my issue tho. Never had food problems, just production.

**Comment by Iamblichos** [comment]
@LoneGazebo I think this code isn't going to update until IsWorkingPlot(I) changes and that may not happen until a few turns later, it doesn't seem to update on the fly when you manually change citizen plots:

```
if (bRecalcPlotYields)
	{
		int iI;
		for (iI = 0; iI < GetNumWorkablePlots(); iI++)
		{
			CvPlot* pLoopPlot = GetCityCitizens()->GetCityPlotFromIndex(iI);

			if(pLoopPlot != NULL && GetCityCitizens()->IsWorkingPlot(iI))
			{
				pLoopPlot->updateYieldFast(this, pReligion, pPantheon);
			}
		}
	}
```

**Comment by ilteroi** [comment]
maybe this will fix it? but at the cost of processing unworked plots multiple times if there are multiple cities around

```
		for (int iI = 0; iI < GetNumWorkablePlots(); iI++)
		{
			CvPlot* pLoopPlot = GetCityCitizens()->GetCityPlotFromIndex(iI);
			if(!pLoopPlot)
				continue;
			
			if (GetCityCitizens()->IsWorkingPlot(iI))
				pLoopPlot->updateYieldFast(this, pReligion, pPantheon);
			else if (!pLoopPlot->isBeingWorked()) //if another city is working the plot, it's their responsibility
				pLoopPlot->updateYieldFast(NULL,NULL,NULL);
		}
```

**Comment by LoneGazebo** [comment]
@ilteroi @Iamblichos should there be an update check in 'setworkingplot' in cvPlot instead? So that, when the bool is flipped, the plot updates itself, maybe?

**Comment by Iamblichos** [comment]
@LoneGazebo I was thinking of that too.


But there's another issue, directly related to this, too. Not just for manual update of citizens.

Let's suppose I choose a pantheon that gives a yield to gold and lapis. I have in my working city plots, 2 gold and 1 lapis (1 city). Currently the citizens are working the gold and not the lapis. I choose my pantheon, the gold gets updated, though not the lapis. The lapis should update, regardless of manual citizen assignment. And sometimes, neither update until the plot is improved. And not because the belief is an improvement yield but rather a resource yield regardless of improvement.

**Comment by ilteroi** [comment]
well the yield display for unworked plots must also be correct

**Comment by Iamblichos** [comment]
@ilteroi yep.

**Comment by LoneGazebo** [comment]
perhaps GetCityCitizens()->IsWorkingPlot(iI)) should actually be replaced with a check to see if the city 'owns' the plot and it _isn't_ owned by someone else, not a check to see if it is being worked?

**Comment by ilteroi** [comment]
well, this is what i have now:

```
		for (int iI = 0; iI < GetNumWorkablePlots(); iI++)
		{
			CvPlot* pLoopPlot = GetCityCitizens()->GetCityPlotFromIndex(iI);
			if(!pLoopPlot)
				continue;
			
			//we're trying to avoid CvPlot::GetWorkingCity() as it's rather slow and this gets called a lot
			if (GetCityCitizens()->IsWorkingPlot(iI))
				pLoopPlot->updateYieldFast(this, pReligion, pPantheon);
			else if (pLoopPlot->getOwner()==getOwner() && !pLoopPlot->isBeingWorked()) 
				//if another city is working the plot, it's their responsibility
				pLoopPlot->updateYieldFast(NULL, pReligion, pPantheon);
		}
```

but it needs some knock-on changes, give me a few minutes so we don't get merge conflicts

**Comment by LoneGazebo** [comment]
I won't touch it.

**Comment by Iamblichos** [comment]
Yeah. I'm good at that.

**Comment by Iamblichos** [comment]
@ilteroi that fixed the religion thing we discussed. Now our lake issue.

**Comment by Iamblichos** [comment]
Not getting correct yield calculation from terrain. @ilteroi are you?

**Comment by Iamblichos** [comment]
@LoneGazebo Okay I have a fix. But use mine in incoming pull request as @ilteroi will calculate an extra yield (though displayed correctly) at the City's plot.
