### ISSUE TITLE
City attack preview.

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#4448]
(see Vortok's screenshots here: https://forums.civfanatics.com/threads/tradition-guide-from-beginner-to-intermediate.631263/page-5)

The preview is misleading, since the strength displayed is the combat strength of the city, and not the effective ranged attack combat strength of the city.
(Which is combat strength, not counting the defensive buildings, and times 40%, as said here https://forums.civfanatics.com/threads/low-end-city-attack-damage.632942/page-2)

**Comment by Iamblichos** [comment]
Well I don't think we've touched CvCity::rangeCombatDamage() in a long time? You sure this is a problem the ratio between that city and the unit is almost flat.

**Comment by MoiMagnus** [comment]
I think that's a vanilla issue. The strength use for city attack is not the same as the strength used for city defense in the code. In the preview, the resulting damages is correct, but the "strength" displayed is the wrong one.

**Comment by Iamblichos** [comment]
Nothing has changed their from vanilla in the EnemyUnitPanel.


local myCityMaxHP = myCity:GetMaxHitPoints();
	local myCityCurHP = myCity:GetDamage();
	local myCityDamageInflicted = myCity:RangeCombatDamage(theirUnit, nil);
	local myCityStrength = myCity:GetStrengthValue();

**Comment by MoiMagnus** [comment]
So that's a vanilla issue. There is two different city strength:

> //    --------------------------------------------------------------------------------
int CvCity::getStrengthValue(bool bForRangeStrike) const
{
    VALIDATE_OBJECT
    // Strike strikes are weaker
    if(bForRangeStrike)
    {
        int iValue = m_iStrengthValue;
        iValue -= m_pCityBuildings->GetBuildingDefense();
        CvAssertMsg(iValue > 0, "City strength should always be greater than zero. Please show Jon this and send your last 5 autosaves.");
        iValue *= /*40*/ GC.getCITY_RANGED_ATTACK_STRENGTH_MULTIPLIER();
        iValue /= 100;
        if(HasGarrison())
        {
            iValue *= (100 + GET_PLAYER(m_eOwner).GetGarrisonedCityRangeStrikeModifier());
            iValue /= 100;
        }
        // Religion city strike mod
        int iReligionCityStrikeMod = 0;
        ReligionTypes eMajority = GetCityReligions()->GetReligiousMajority();
        if(eMajority != NO_RELIGION)
        {
            const CvReligion* pReligion = GC.getGame().GetGameReligions()->GetReligion(eMajority, getOwner());
            if(pReligion)
            {
                iReligionCityStrikeMod = pReligion->m_Beliefs.GetCityRangeStrikeModifier(getOwner(), GET_PLAYER(getOwner()).getCity(GetID()));
                BeliefTypes eSecondaryPantheon = GetCityReligions()->GetSecondaryReligionPantheonBelief();
                if (eSecondaryPantheon != NO_BELIEF)
                {
                    iReligionCityStrikeMod += GC.GetGameBeliefs()->GetEntry(eSecondaryPantheon)->GetCityRangeStrikeModifier();
                }
                if(iReligionCityStrikeMod > 0)
                {
                    iValue *= (100 + iReligionCityStrikeMod);
                    iValue /= 100;
                }
            }
        }
        return iValue;
    }
    return m_iStrengthValue;
}

**Comment by MoiMagnus** [comment]
And the one used in the preview is the wrong one (with boolean false, instead of true)

**Comment by Iamblichos** [comment]
Ah! bingo you're right. Good call.

**Comment by Iamblichos** [comment]
We might need two of them then. One for the City Banner and the other for Ranged Striking in Enemy Unit Panel.

**Comment by MoiMagnus** [comment]
You are right, since one is the "defensive value", and the other one the "offensive value".

**Comment by Iamblichos** [comment]
I think we can do it with just one Lua function we just need to hook up push the Boolean if we need to.

**Comment by Iamblichos** [comment]
No Walls:
![20180531153511_1](https://user-images.githubusercontent.com/14372214/40807141-19b0ec2a-64e9-11e8-96f8-ab3493fa843b.jpg)
Walls:
![20180531153954_1](https://user-images.githubusercontent.com/14372214/40807148-1dba089c-64e9-11e8-9722-859825fbad52.jpg)
Castle:
![20180531154116_1](https://user-images.githubusercontent.com/14372214/40807150-1fec6cea-64e9-11e8-90bc-5b923a8f5deb.jpg)
Better?

**Comment by MoiMagnus** [comment]
Thank you! (Though that now that player can see the true strength, I guess we will see people asking frequently why does their city strength is weaker than expected)
