### ISSUE TITLE
Laborers giving more production than they should?

### ISSUE THREAD

**Issue by Chandler-Civ** [LoneGazebo/Community-Patch-DLL#4452]
_1. Mod version (i.e Date - 4/23):_
Modpack of 20-5-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Laborers should be giving 4 production at this point of the game, and they seem to be giving 6.

_4. Steps to reproduce (optional):_
I had only 5 cities for the World's Fair, so I tried to get as many hammers from each city as I could. Then I found that laborers were giving me as much production (6) as a completely improved plain horses pasture (6, up to that point). Unfortunately,  have no clue for how long has this been going on, as I usually try not to have any laborers at all. Also, I think the production from the pasture (at least this pasture) is fine. I've done the calculation, dividing by the modifiers, and it seems to be giving 6, as it should.

![produccion 1](https://user-images.githubusercontent.com/39574786/40854099-8f9b1126-65d0-11e8-8185-208df6686f89.jpg)
![produccion 2](https://user-images.githubusercontent.com/39574786/40854104-9770e862-65d0-11e8-8a84-312b5c91e4e3.jpg)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
This one might be wrong. I have enabled logging after seeing this issue.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2064320/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Harun al-Rashid_0397 AD-1774.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2063767/Harun.al-Rashid_0397.AD-1774.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Probably just a missing tooltip element in that custom cityview panel.

**Comment by Chandler-Civ** [comment]
So the laborers should actually be giving 6 production at that point? That's more than many of my improvements. I thought it wasn't the tooltip because 6 "for nothing" seems too much.

**Comment by supermerill** [comment]
>  6 "for nothing" seems too much.

It cost some food, and you use a pop that can work a nice tile.
compare your 6f, 6p vs 6p, 2g, -2f
It's better than plain sea tile, but that's it.
