### ISSUE TITLE
plot flags

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4454]
plots have some "neighborhood flags" for performance reasons:

* m_bIsAdjacentToOcean
* m_bIsAdjacentToLand

now there's some ambiguity concerning the default values here.

* is a land plot adjacent to land by default?
* is a water plot adjacent to water by default?

**Comment by Iamblichos** [comment]
On 'is a water plot' I found your code here to be a safe assumption: m_bIsAdjacentToOcean = !m_bIsLake;

**Comment by ilteroi** [comment]
so you're saying m_bIsAdjacentToLand should always be false for land plots, and m_bIsAdjacentToOcean should always be false for ocean plots?
