### ISSUE TITLE
Goddess of Purity doesn't give yields to all concerned tiles

### ISSUE THREAD

**Issue by DivermanCiv** [LoneGazebo/Community-Patch-DLL#4455]
_1. Mod version (i.e Date - 4/23):_
5/20

_2. Mod list (if using Vox Populi only, leave blank):_
InfoAddict
Really Advanced Setup

_3. Error description:_ 
Some lakes and marshes tiles don't give the correct yields with the Goddess of Purity pantheon

_4. Steps to reproduce (optional):_

[Goddess of Purity bug files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2065168/Goddess.of.Purity.bug.files.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Iamblichos** [comment]
Fixed in up coming version.
