### ISSUE TITLE
Order of operation problem on UpdateYieldFast()

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#4456]
@LoneGazebo if you get a policy that updates an improvement yield, e.g. +1 Culture  to a GP improvement, that won't be updated because calculateImprovementYield() comes before calculatePlayerYield().

```
iYield += calculateImprovementYield(eImprovement, eYield, iYield, ePlayer, false, eRoute);
iYield += calculatePlayerYield(eYield, iYield, ePlayer, eImprovement, pOwningCity, pMajorityReligion, pSecondaryPantheon, bDisplay);
```

We can't pass iYield to improvement because calculatePlayerYield comes last.

**Comment by Iamblichos** [comment]
```
if (eYield == YIELD_CULTURE)
{
	iYield += kPlayer.GetPlayerPolicies(POLICYMOD_EXTRA_CULTURE_FROM_IMPROVEMENTS);
	iYield += kPlayer.GetPlayerPolicies()->GetImprovementCultureChange(eImprovement);
}
```

We should probably just put these in player yields.

**Comment by Iamblichos** [comment]
Ugh...let me correct my first post. It's an order of operations problem but not because of calculateYieldFast(), but rather my second post I think has the answers. We need to move that to player yield even though its associated with an improvement.

**Comment by LoneGazebo** [comment]
@Iamblichos that makes sense, I'll move that. 

G

**Comment by LoneGazebo** [comment]
I also moved the isgoldenage check to the end of the calculate player one. I'll post my fixed code in a bit.

**Comment by Iamblichos** [comment]
In player yield I wouldn’t put I behind a check for current yield though in case you are adding a fresh new yield from a policy.

**Comment by Iamblichos** [comment]
Also in getyieldwithbuild() we should probably add up the yield calculation in the same order we do in calculateyieldfast()
