### ISSUE TITLE
Losing a city does not reduce your technology cost back

### ISSUE THREAD

**Issue by Voker57** [LoneGazebo/Community-Patch-DLL#4459]
_1. Mod version (i.e Date - 4/23):_
5.20-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
If you capture a city, your tech/culture cost rises. If you later raze it/lose it, your cost does not lower back.

However, if you immediately raze it to the ground, cost does not rise. And if you stop razing and resume, it rises.

_4. Steps to reproduce (optional):_
Load save: (single player) http://dump.bitcheese.net/files/sysyjap/pretaking.Civ5Save
Note tech cost, take Memphis, annex, note cost, raze it, note cost after razing fully.
Should be: 92, 100, 92
Actually is: 92, 100, 100

**Comment by Voker57** [comment]
You mean intentional? Sounds like very arbitrary penalty.

Also, what about paused razing problem?

**Comment by Voker57** [comment]
Additionally, not lowering tech prices actually applies penalty to warmongers' victims.

**Comment by afwbkbc** [comment]
Same for when others conquer city.

**Comment by bigcat88** [comment]
ask, @LoneGazebo for that. Six month ago he said that it is intentional.

**Comment by LoneGazebo** [comment]
It is intentional, but it 'resets' to your actual city count the next time you settle/conquer.

**Comment by HungryForFood** [comment]
I'm inclined to agree with @Voker57 here, my impression is that it punishes the victim more than the warmonger.

**Comment by LoneGazebo** [comment]
You’ll have to ask Jon shafer. Anyways it’s vanilla code and it’s designed as such without an easy means of change. It’s been there since 2008. Closing this.

**Comment by l29ah** [comment]
what

**Comment by LoneGazebo** [comment]
https://en.wikipedia.org/wiki/Civilization_V

**Comment by ryanmusante** [comment]
@l29ah 
How can you have any pudding if you don't eat yer meat?
