### ISSUE TITLE
Aztec golden age UA does not work in multiplayer

### ISSUE THREAD

**Issue by Voker57** [LoneGazebo/Community-Patch-DLL#4460]
_1. Mod version (i.e Date - 4/23):_
5-20.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Golden age does not start on favorable peace treaty in multiplayer. In single player, works as advertised.

_4. Steps to reproduce (optional):_
Load multiplayer save http://dump.bitcheese.net/files/femavuw/deal.Civ5Save, choose Aztec, take something from Gandhi for peace (default "what will make this work" works).

**Comment by LoneGazebo** [comment]
There's a cutoff for the warscore value for a 'successful' war - I think it is 25%.

G

**Comment by Voker57** [comment]
The warscore in the save is 58%.

Also, attached wrong save, here's the right one http://dump.bitcheese.net/files/hakafyk/ddeal.Civ5Save

**Comment by LoneGazebo** [comment]
I see why - I'll fix.
