### ISSUE TITLE
notification log

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4461]
this one is for the lua experts ... would it be possible to give some love to the notification log to make it easier to parse?

![image](https://user-images.githubusercontent.com/1358966/40889836-91032d7a-676d-11e8-88c2-35445b33eb8c.png)

* maybe a bit wider so there are fewer linebreaks?
* some sort of bullet point in front of each individual message?

**Comment by LoneGazebo** [comment]
@Infixo you want to take point?

**Comment by jnzs13** [comment]
Excuse me, just a few ideas to contribute to this great project. Is it possible or feasible?

![not_log_color](https://user-images.githubusercontent.com/40181252/41251386-2915bb50-6d90-11e8-8c1e-2dba399d0b22.png)
![not_log_white](https://user-images.githubusercontent.com/40181252/41251390-2a81d51e-6d90-11e8-8992-236c97c0e45a.png)

**Comment by ilteroi** [comment]
nice!

but i'm not sure, is this a mock-up or do you have actual code you want to contribute?

**Comment by jnzs13** [comment]
Just mock-up. Unfortunately I am not aware of codes, just interface design.

**Comment by LoneGazebo** [comment]
```
Controls.MultiPull:ClearEntries();

	Controls.MultiPull:RegisterSelectionCallback(function(id)
		local entry = additionalEntries[id];
		if(entry and entry.call ~= nil) then
			entry.call();
		end
	end);
		 
	for i,v in ipairs(additionalEntries) do
		local controlTable = {};
		Controls.MultiPull:BuildEntry( "InstanceOne", controlTable );

		controlTable.Button:SetText( v.text );
		controlTable.Button:LocalizeAndSetToolTip( v.tip );
		controlTable.Button:SetVoid1(i);
		
	end
```

This the (vanilla) code, untouched by EUI etc. - I followed the rabbit trail down and it appears that it's simply grabbing the full 'chunk' of notification bodies from the current notification pool and applying them simultaneously as a single tooltip. So I don't believe there is a point in which we can separate them out for individualization.

**Comment by ilteroi** [comment]
notification pool sounds interesting ... which file is that?

**Comment by LoneGazebo** [comment]
That’s DiploCorner.lua

**Comment by LoneGazebo** [comment]
![image](https://user-images.githubusercontent.com/7849458/41312955-845db97e-6e56-11e8-8abf-212875a01fed.png)

**Comment by jnzs13** [comment]
great!

**Comment by LoneGazebo** [comment]
Unfortunately this is not feasible - for some reason the notification log breaks for some output types if you put font mapped characters in the text. Awesome, Firaxis.
