### ISSUE TITLE
Feature request - highlighted words on pantheon select menu

### ISSUE THREAD

**Issue by a1nosweat** [LoneGazebo/Community-Patch-DLL#4462]
When I choose a pantheon - I know what the terrain is - and I know what I'm looking for in a pantheon.  If I've got stone then I'm looking for the god of craftsmen. 

But I can never remember the names of all the pantheons, or exactly how they work, and looking down the middle of the menu breaks immersion a little.

Would it be possible to highlight the improvements, buildings...conditions for bonuses to make this easier?  I include a pic to show what I mean - although underlining in red would not be my formatting choice.

Actually - could  the adviser system be resurrected to help this? Have a red symbol showing that your military adviser recommends God of war, and your economic adviser recommending Earth mother (If you've got lots of hills?)
![image](https://user-images.githubusercontent.com/15791659/41111128-0df23e9a-6a73-11e8-9892-1c405927901f.png)

**Comment by TechpriestEnginseer** [comment]
There's something about consistency if we do consider your request which means all religion beliefs have to be affected.

There's no automation for this type of feature request, however...

In \...\Sid Meier's Civilization 5\MODS\(2) Community Balance Overhaul\Balance Changes\Text\en_US\ReligionText.sql

````
UPDATE Language_en_US
SET Text = '+2 [ICON_FOOD] Food and +1 [ICON_PEACE] Faith from Shrines, Watermills, and Wells. 25% faster [ICON_FOOD] Growth Rate'
WHERE Tag = 'TXT_KEY_BELIEF_FERTILITY_RITES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );
````
You can find a snippet of this code and apply changes of a particular text to be highlighted to...
````
UPDATE Language_en_US
SET Text = '+2 [ICON_FOOD] Food and +1 [ICON_PEACE] Faith from [COLOR_HIGHLIGHT_TEXT]Shrines[ENDCOLOR], [COLOR_HIGHLIGHT_TEXT]Watermills[ENDCOLOR], and [COLOR_HIGHLIGHT_TEXT]Wells[ENDCOLOR]. 25% faster [ICON_FOOD] Growth Rate'
WHERE Tag = 'TXT_KEY_BELIEF_FERTILITY_RITES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );
````

**Comment by LoneGazebo** [comment]
I'm not going to do this, as I don't feel it is necessary (and I dislike random highlights).
