### ISSUE TITLE
Feature Request - City Improvement Plan(CIP)

### ISSUE THREAD

**Issue by ProtoNoob** [LoneGazebo/Community-Patch-DLL#4463]
Worker automation, as an idea, is great as it offloads minutia and makes empire building a little less tedious.  Unfortunately, the AI and myself often disagree on what is to be done on any given plot (thus rendering the option moot).  My suggestion is to be able to create a City Improvement Plan(**CIP**) that any worker who is told to "Work Nearest City Plan" will take the plan that you have devised and complete it to the best of its ability (if determining nearest city is problematic, make this option available only IN the city hex).  This would be a separate button from "Automate", but you would still have that option. 

How would we input the **CIP**?  I was thinking maybe we could use some of the UI code underlying the city screen (like when purchasing plots or doing manual "Citizen Management"(**CM**)) and develop another layer that allows you, to choose where improvements get placed by clicking on the little circles at the top of the hexes.  The circles could cycle through the available improvement options until you get to the one you want.  Repeat for each hex and you have a city plan. The only thing I can't figure out is how you would tell them to put roads AND and improvement somewhere.

If possible, another layer could be added to suggest what order they are to be done in (much like the production cue), or conversely to automate priority selection by the worker (focusing on shortest path or highest output change, this focus could be selected by the player just like **CM** auto focuses).

This would allow for a high level of control, without having to be interrupted by dozens of workers every turn in Huge map games.

Anyways, I could see where this would be too hard as it would require changes to UI, city screen, AI, etc. etc.... so if it is too much to do, I understand, BUT I think it would be a HUGE boon to people would like to create HUGE empires.

**Comment by ProtoNoob** [comment]
Fair enough.  Is there a modder that I should maybe seek out that would have the chops for something like this or should I just put it out there for all?

**Comment by ilteroi** [comment]
i think there was a way to give multiple consecutive missions to a unit? doesn't that solve the issue?

**Comment by tu-79** [comment]
Maybe. In some other games, there's a way to add orders to the unit queue, like pressing Shift while ordering. If player could issue three orders to any worker, that would partially solve the problem.
