### ISSUE TITLE
Incorrect Maritime CS yields in capital

### ISSUE THREAD

**Issue by Omen-of-Peace** [LoneGazebo/Community-Patch-DLL#4465]
_1. Mod version (i.e Date - 4/23):_ 5/25-3

_2. Mod list (if using Vox Populi only, leave blank):_ UI mods included in the [Modpack](https://forums.civfanatics.com/threads/dlc-modpack-and-43-civ-version-repository.609278/page-17#post-15135023) (from the forum)

_3. Error description:_ When allied to a Maritime CS, the capital doesn't receive the amount of food from it indicated by the CS' tooltip. I think it received the same amount of food as other cities (I can double-check later on if needed). 

Save (Modpack required): [Napoleon_0191 AD-1310.Civ5Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2086383/Napoleon_0191.AD-1310.Civ5Save.zip)
I'm allied with Ur the Maritime CS. Check out the Food tooltip in Paris.

**Comment by LoneGazebo** [comment]
It does. It goes to the city tile though.

**Comment by Omen-of-Peace** [comment]
Now I get it: I was thrown off by a "+1 from City States" in the Food tooltip, but that's due to the Scrivener's Office - I recall that Chancery bonuses are displayed like this as well.
It's a bit confusing, but no big deal.

Issue closed.
