### ISSUE TITLE
implausible amount of food

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4466]
maybe we still have a yield bug?

![image](https://user-images.githubusercontent.com/1358966/41191038-73f409b8-6be9-11e8-8991-58818c274103.png)

i count around 75 food ... not 252

**Comment by ilteroi** [comment]
nevermind, old version

**Comment by Iamblichos** [comment]
Dude. Don’t scare a brother like that!
