### ISSUE TITLE
Scientists bonus culture isn't shown in their tooltip

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#447]
![8930_2015-07-23_00002](https://cloud.githubusercontent.com/assets/1131228/8856210/c92bd86a-3182-11e5-938b-9e9d6d058b0e.png)
![8930_2015-07-23_00004](https://cloud.githubusercontent.com/assets/1131228/8856215/cde15768-3182-11e5-8d04-7d7cf132e376.png)
![8930_2015-07-23_00003](https://cloud.githubusercontent.com/assets/1131228/8856218/d16b49a2-3182-11e5-9866-64b40740e211.png)

**Comment by Finarvi** [comment]
Was about to post it. I confirm.

**Comment by LoneGazebo** [comment]
Are the cities getting the culture from them? If so, sounds like an interface error (ugh).

**Comment by Finarvi** [comment]
Yes, it's only tooltip problem.

**Comment by LoneGazebo** [comment]
Great. Just. Great. I hate lua.
