### ISSUE TITLE
calculatePlayerYield() issue

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#4470]
6-12 beta code:

```
if (eImprovement != NO_IMPROVEMENT && eYield == YIELD_CULTURE && (iYield > 0 || iCurrentYield > 0))
	{
		iYield += kPlayer.GetPlayerPolicies()->GetNumericModifier(POLICYMOD_EXTRA_CULTURE_FROM_IMPROVEMENTS);
		iYield += kPlayer.GetPlayerPolicies()->GetImprovementCultureChange(eImprovement);
	}
```
@LoneGazebo don't think this is going to work. If the yield is not a current yield or not an existing yield from iYield and the yield is a new yield added by the policy itself, it'll never get added. I would leave off the last check. You don't need it.

```
if (kPlayer.isGoldenAge())
	{
		if ((iYield + iCurrentYield) >= kYield.getGoldenAgeYieldThreshold())
		{
			iYield += kYield.getGoldenAgeYield();
		}
	}
```

I think this one is fine. We just need iYield + iCurrentYield to equal 1 to get over the hump.

**Comment by LoneGazebo** [comment]
@Iamblichos a similar check was in place for that code in the pre-refactor version, though.

**Comment by Iamblichos** [comment]
Yeah I know and I noted it then. It will not give the yield in the scenario I suggest.

**Comment by Iamblichos** [comment]
@LoneGazebo see my second to the last comment here. I had already done some testing to verify that statement. https://github.com/LoneGazebo/Community-Patch-DLL/issues/4456
