### ISSUE TITLE
Next turn does not work, even after reloading

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#4471]
_1. Mod version (i.e Date - 4/23):_

2018.05.20-3
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Sometimes Next turn button does nothing, but I'm able to play again by reloading. Not this time.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2098837/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Babylon - debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2098854/Babylon.-.debug.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
not sure - tried the shift + enter?
