### ISSUE TITLE
Typo in Leader Dialogue: Arabia

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4472]
_1. Mod version (i.e Date - 4/23): Latest version (5-20-3)

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description: Typo in leader text.

Row Tag="TXT_KEY_LEADER_HARUN_GREETING_HOSTILE_HELLO_2"
You are foolish to "by" my enemy?

_4. Steps to reproduce (optional): Get Harun to hate you and talk to him a bunch. :S Don't think I need to attach a save file for this one.

---------------------------
Supporting information: N/A

**Comment by supermerill** [comment]
what is the correct phrase?

**Comment by HeathcliffWarriors** [comment]
You are foolish to _be_ my enemy.
