### ISSUE TITLE
City Combat Strength Didn't Update After City Capture

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4474]
_1. Mod version (i.e Date - 4/23): Latest version (5-20-3)

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description: The city I renamed "District 24", after I captured it from Arabia earlier (followed by his immediate capitulation), remained at 5 combat strength despite a Fusilier being in the city. It remained so for many turns. In the file 'Pre Iron Fist', you can see this. Between 'Pre Iron Fist' and 'Post Iron Fist', I adopted Autocracy, the Iron Fist tenet, moved the Fusilier out of the city and moved another Fusilier in - then set them both to "Do Nothing" before saving. This fixed the issue - not sure if it's simply a graphical glitch.

_4. Steps to reproduce (optional): I didn't think to take a save and report the issue when it initially occurred - which was approximately 9 turns ago according to the Vassal Overview since Harun capitulated on the same turn I captured his capital with the Fusilier (renaming the capital did nothing to change the combat strength). You might not be able to reproduce it. However I have the two save files, in case this is useful to you.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2100750/Logs2.zip)

(I deleted the existing logs after reporting the previous issue, then loaded the file 'Pre Iron Fist' where the bug exists, then quit.)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): The bug is in the file 'Pre Iron Fist'.
[Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2100754/Saves.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional): From the file 'Pre Iron Fist'.
![screenshot 7266](https://user-images.githubusercontent.com/38794241/41391197-2e7b138c-6f67-11e8-89a6-9944d6e19186.png)

**Comment by LoneGazebo** [comment]
Iron fist doesn't do anything to a city's strength, though...
