### ISSUE TITLE
Inaccurate Difficulty Handicap Info in Economic Overview

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4475]
_1. Mod version (i.e Date - 4/23): Latest version (5-20-3)

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description: Economic Overview provides inaccurate information about unit, building and road maintenance on difficulties below Prince. Specifically, it uses the values from Civ5HandicapInfos.xml (or it might be hardcoded text), rather than the ones from DifficultyMod.xml.

_4. Steps to reproduce (optional): I included a save game to demonstrate, but you can see it on any game as follows:
1. Start any game on Settler, Chieftain, or Warlord difficulty (new or loaded).
2. Enter the Economic Overview.
3. Mouse over the values for Unit, Building and Road maintenance.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2100786/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 
[Text Fix.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2100787/Text.Fix.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): N/A

4. Screenshots (optional): These are on Chieftain difficulty.
![screenshot 7267](https://user-images.githubusercontent.com/38794241/41391644-c4618618-6f69-11e8-9095-2184f145b9eb.png)
![screenshot 7268](https://user-images.githubusercontent.com/38794241/41391645-c46fa428-6f69-11e8-95d4-0e86bb3a9105.png)
![screenshot 7269](https://user-images.githubusercontent.com/38794241/41391646-c47fc0ce-6f69-11e8-94c0-135597fc64c3.png)

**Comment by LoneGazebo** [comment]
It's hardcoded to use a bad database. @Infixo worked on this some elsewhere.
