### ISSUE TITLE
Slinger RNG?

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4477]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So far it appears to me if the first time you attack a Slinger it runs away, there's no point trying more the same turn, it's always going to flee if there's a tile it might escape to. If however your first attack during a turn succeeds and the annoying guy doesn't die, the second always will hit the target as well.

**Comment by LoneGazebo** [comment]
@ilteroi RNg woes?

**Comment by ilteroi** [comment]
nope. just checked the code, the RNG roll depends on the current plot of the defender.

how often did you test this? which units did you use for the attack (mounted or not)?

**Comment by Enrico-Swagolo** [comment]
Jaguars, I hit many of those. Almost none ever died. 
RNG depends on current plot? That'd explain why every time a Slinger got hit by my Jaguar, a second hit also connected. It could be correct, the likelihood to hit them is so very low (20% chance, no matter melee unit type) that every time I hit it twice in a turn it dodged could be a coincidence. Over all, I'd assume I made like 20-40 attacks, and hit no more than 4 times. 

I have a fix suggestion to fix the RNG problem being current turn/plot based.  Just remove the promotion. The unit can go through mountains, hits twice, levels up twice as fast, has fast hill movement and is also nearly impossible to kill with melee and mounted even if it's positioned badly. That I can't even hit them with melee 99% of the time doesn't mean the 1% of the time they're not on mountains Inca should just get a free get-out-of-jail card.

**Comment by LoneGazebo** [comment]
@ilteroi we may need to add an extra parameter if it just plot then, no?

**Comment by Enrico-Swagolo** [comment]
My solution was the most elegant and simplest though. No new code needed.

**Comment by LoneGazebo** [comment]
"Doc, this guy has a sore throat, should we-"
"Amputate it. All of it."

**Comment by Enrico-Swagolo** [comment]
More like
"Doc, this guy will release incredibly awful, toxic gases poisoning all around him unless we remove that third arm that grew because of mutation, should we-"
"Amputate it. All of it."

**Comment by ilteroi** [comment]
including the current hitpoints should do it. i'll fix
