### ISSUE TITLE
EUI errors while creating modpack

### ISSUE THREAD

**Issue by wistak103** [LoneGazebo/Community-Patch-DLL#4478]
_1. Mod version (i.e Date - 4/23):_
6-14 beta

_2. Mod list (if using Vox Populi only, leave blank):_
VoxPopuli only with EUI from Installer

_3. Error description:_ 
When i try to create modpack 
fireturner showing this EUI errors

 ```
TopPanel: Finished loading EUI top panel	138.812
 PlotHelpManager: GameInfo.PolicyBranchTypes[-1] is undefined
 Runtime Error: C:\Users\wistak\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\UnitPanel.lua:1321: attempt to call method 'GetChargesLeft' (a nil value)
 Runtime Error: C:\Users\wistak\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\TopPanel.lua:457: attempt to call method 'GetGAPFromReligion' (a nil value)
 Runtime Error: C:\Users\wistak\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\TechButtonInclude.lua:217: attempt to call field 'AnyoneHasWonder' (a nil value)
 Runtime Error: C:\Users\wistak\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\UnitPanel.lua:1321: attempt to call method 'GetChargesLeft' (a nil value)
 Runtime Error: C:\Users\wistak\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\TopPanel.lua:457: attempt to call method 'GetGAPFromReligion' (a nil value)

```

Happen only when i enable multpilayer mods workaround mod
but first line PlotHelper.. happen also when no using it

And modpack works so its no big deal (i think)

_4. Steps to reproduce (optional):_
try to create modpack

**Comment by LoneGazebo** [comment]
you will get errors while the modpack is being made. That's normal.

**Comment by wistak103** [comment]
Ok

**Comment by wistak103** [comment]
and that one about 
PlotHelp?

**Comment by LoneGazebo** [comment]
normal.

**Comment by wistak103** [comment]
Ok thanks

**Comment by Iamblichos** [comment]
Just so you know the reason why this happens is because the Modpacks’s DLL duke is used in the creation of the modpack so their are a lot of LUA functions that DLL doesn’t know. It’s harmless and irrelevant during initialization at game start and for creating the modpack. Once the modpack is created you restart up with the CP DLL all is well.
