### ISSUE TITLE
CTD - due to trade request (AI)

### ISSUE THREAD

**Issue by Justi86** [LoneGazebo/Community-Patch-DLL#4479]
_1. Mod version (i.e Date - 4/23):_
6/14 (Beta) and 5/20/3 

_2. Mod list (if using Vox Populi only, leave blank):_
only CP and CBO

_3. Error description:_ 
It keeps crashing randomly as soon as an AI is getting in contact with me. (mostly for trading)
e.g. trading agreement runs out and the next round it crashes due to the trade request of the AI
Reloading helps but it crashes next time

_4. Steps to reproduce (optional):_
waiting for trade request or anything else

Sorry, no log files

**Comment by MoiMagnus** [comment]
Could you give a save just before a crash (and the version of this save), and the CvMiniDump.dmp of your crash? (Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V)

**Comment by Justi86** [comment]
[Civ.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2105310/Civ.zip)
Here I have a save right before the crash. (next round) However reloading helps to fix it.

**Comment by Justi86** [comment]
I guess I figured it out. I used another starting option (Direct X 10/11 instead of the Win 8 option which is recommended) and since then I had no crashes at all.
