### ISSUE TITLE
TXT KEY EUI BUILDIN SUPLY CAP and GRANTED

### ISSUE THREAD

**Issue by wistak103** [LoneGazebo/Community-Patch-DLL#4480]
_1. Mod version (i.e Date - 4/23):_
6-14

_2. Mod list (if using Vox Populi only, leave blank):_
VoxPopuli with EUI from installer

_3. Error description:_ 
on many buildings there are 
TXT_KEY_EUI_BUILDING_SUPLY_CAP (GLOB too on Himeji)
and ..._GRANTED

I think that was happening on older versions too
Languege english

4. Screenshots (optional):
![screenshot 290](https://user-images.githubusercontent.com/32599249/41436351-b449db6e-7021-11e8-9a28-7d4275e8edc6.png)

**Comment by LoneGazebo** [comment]
Means you aren't importing the EUI text correctly.

**Comment by wistak103** [comment]
hhmm just installed with installer removing old versions both Vox and EUI so im not sure where i could do something wrong

**Comment by wistak103** [comment]
ok after removing all civ files and clean install civ it is working so it really was my foult sorry
