### ISSUE TITLE
Grand ossuary requires 24% more global followers

### ISSUE THREAD

**Issue by wistak103** [LoneGazebo/Community-Patch-DLL#4481]
_1. Mod version (i.e Date - 4/23):_
6-14

_2. Mod list (if using Vox Populi only, leave blank):_
Multiplayer Mods Workaround (v 1)
	
Promotion Flags EUI (v 1.1)
UI - City Production (v 15)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Improved City View (Vox Populi EUI) (v 10)
UI - Promotion Tree (v 17)
UI - Religion Spread (Vox Populi) (v 1.0)
UI - Show XP in Military Overview (v 2.3)
UI - Upgrade Tree (v 9)
Unique City-States (v 2)

_3. Error description:_ 
look on screen on Grand ossuary require 24%more followers but in descritpion it requires 20%

![screenshot 296](https://user-images.githubusercontent.com/32599249/41441289-44e4104e-7032-11e8-8d69-f237cb6e7284.png)
![screenshot 297](https://user-images.githubusercontent.com/32599249/41441291-46f9a574-7032-11e8-837d-9bf8749cd358.png)

**Comment by LoneGazebo** [comment]
It scales based on map size.

**Comment by wistak103** [comment]
So it should also on description changee no?

**Comment by LoneGazebo** [comment]
It does, but it was missing from the compatibility file.
