### ISSUE TITLE
Update texts

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#4482]
_1. Mod version (i.e Date - 4/23):_
6/14 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
VP+EUI (Automatic install)

_3. Error description:_ 

-----
1. Exchange Markets (**Compatibility_en_US.sql**)
`+2 [ICON_HAPPINESS_1] Happiness for every active [ICON_INTERNATIONAL_TRADE] Trade Route.`
should be
`+1 [ICON_HAPPINESS_1] Happiness for every active [ICON_INTERNATIONAL_TRADE] Trade Route.`
https://github.com/LoneGazebo/Community-Patch-DLL/blob/2e70e5bd8f03995c6c20adc34e12aabc0a18b44f/EUI%20Compatibility%20Files/EUI%20Compatibility%20Files/CSD/CompatibilityText/Compatibility_en_US.sql#L109

cf.
(6a) Community Balance Overhaul - Compatibility Files (EUI)\CSD\CompatibilityText\Compatibility_en_US.sql
(6b) Community Balance Overhaul - Compatibility Files (No-EUI)\CSD\CompatibilityText\Compatibility_en_US.sql
(6c) 43 Civs CP\EUI\CSD\Compatibility_en_US.sql
(6c) 43 Civs CP\No-EUI\CSD\Compatibility_en_US.sql

TXT_KEY_POLICY_CULTURAL_DIPLOMACY_HELP

-----
2. Aqueduct
![aqueduct](https://user-images.githubusercontent.com/11933188/41465502-5a773c2c-70d9-11e8-8e04-cd7385b6eb54.png)

cf.
TXT_KEY_BUILDING_AQUEDUCT_STRATEGY

-----
3. UIText.sql

`{@1_CityName}`
should be
`{1_CityName}`

https://github.com/LoneGazebo/Community-Patch-DLL/blob/2e70e5bd8f03995c6c20adc34e12aabc0a18b44f/Community%20Balance%20Patch/Balance%20Changes/Text/en_US/UIText.sql#L543

cf.
(2) Community Balance Overhaul\Balance Changes\Text\en_US\UIText.sql
Line: 543

**Comment by supermerill** [comment]
The "and a large boost to Production" may refer to the +4 production.
