### ISSUE TITLE
Maritime City States

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#4483]
_1. Mod version (i.e Date - 4/23):

6/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I am allied with 5 Maritime City States, so I should get hundreds of food from them in my capital. 
However, tooltip says I only get 5 food from CS.
On the other had, I do get almost 100 food from terrain, but I am working hardly any food tiles. 
Maybe the two errors are related?

https://steamuserimages-a.akamaihd.net/ugc/918053662024881080/9BE0F27E59EE2445CB3EE01F9C5A87BED7929172/

[Food.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2109231/Food.zip)

**Comment by LoneGazebo** [comment]
Food for maritime goes under your city tile.
