### ISSUE TITLE
Coup Chance

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#4484]
_1. Mod version (i.e Date - 4/23):_

6/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I have a negative coup chance. 

https://steamuserimages-a.akamaihd.net/ugc/918053662024881286/8816EE5550A756355AE9BFFC518A22B5D4DD6A10/

**Comment by bigcat88** [comment]
I have such things in previous versions too(but my values was -3% or -4%(for 3 lvl spy)). On this version didn't test yet, game in progress, will write if see such thing.
