### ISSUE TITLE
Cant free enemy vassal

### ISSUE THREAD

**Issue by Chikitek** [LoneGazebo/Community-Patch-DLL#4485]
_1. Mod version (i.e Date - 4/23):_
05-30, 3rd

_2. Mod list (if using Vox Populi only, leave blank):_
Nop

_3. Error description:_ 
At war with Siam who has a vassal. Taken their cap and 100% warscore, but no way to release vassal or to have them capitulate.

_4. Steps to reproduce (optional):_
Win war with a civ who has a vassal?

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[CantVassalizeSiam.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2109363/CantVassalizeSiam.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Probably had Iron Fist - you can't force them to let go, and you can't capitulate a civ with vassals.
