### ISSUE TITLE
5/20 crash on load game

### ISSUE THREAD

**Issue by ryanccook** [LoneGazebo/Community-Patch-DLL#4486]
Version 5/20

Game crashes at "load game" in the main menu, and when pressing "load game" during a game. (I know other people aren't having this issue so I'm not sure what the deal is)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2109448/CvMiniDump.zip)

dump file attached

**Comment by m4ti140** [comment]
Same here, game crashes when I click load even on saves as early as turn 90. Very early saves (turn 0, 1 etc.) seem to work.
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2112696/CvMiniDump.zip)

**Comment by ryanccook** [comment]
Hmm guess I'm not the only one. Though saves on 0 or 1 don't  work for me. Or even just pressing the load button in the main menu before starting a game crashes it too.
