### ISSUE TITLE
Neighbour keeps declaring war on my vassal

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#4488]
_1. Mod version (i.e Date - 4/23):_
6/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I get reports from my spy that Siam is going to attack my  vassal. Then he attacks and make peace in the same turn, "over and over again". This keeps happening throughout the game.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[WAR AGAINST VASSAL and PEACE.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2110436/WAR.AGAINST.VASSAL.and.PEACE.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/41524950-9ab333ce-72df-11e8-99b8-c5f65991045b.png)

**Comment by ridjack** [comment]
I'm experiencing a very similar issue; in my case, it's England's vassal rather than my own.

**Comment by ridjack** [comment]
I'm experiencing the same thing with some AIs; Arabia is the Vassal of England, and Rome keeps declaring war and peace in the same turn. None of these declarations have included England; knowing nothing else, I would assume this fact is at the root of the issue.
Version 6/14
Save: [auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2142348/auto.zip) _(According to my log, the first declaration was on turn 166. I have included ten turns worth of autosaves just in case.)_
Logs: [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2142313/Logs.zip)
Mods: 

_(These same mods have been used for many VP versions now.)_

```
- (1) Community Patch	Version	88
- (2) Community Balance Overhaul	Version	13
- (3) City-State Diplomacy Mod for CBP	Version	27
- (4) C4DF - CBP	Version	11
- (5) More Luxuries - CBO Edition (5-14b)	Version	155
- (6a) Community Balance Overhaul - Compatibility Files (EUI)	Version	1
- (9) Wonders Expanded	Version	2
- (Z) Change VP Options	Version	1
- CIV-Linked Great Generals	Version	11
- Ethiopia Color Fix	Version	1
- Global - Capture Great People	Version	1
- Global - Civilians Move After Purchase	Version	2
- Global - Commander Influence Borders	Version	2
- Global - Local Generals	Version	2
- Historical Religions (BNW or GK)	Version	55
- JFDLC (07) - JFD's Cultural Diversity (Core)	Version	16
- More Unique Components for VP	Version	32
- Really Advanced Setup	Version	15
- Strange Religions	Version	9
- Tectonic Map Script	Version	4
- UI - Filters in Trade Route Overview (Vox Populi)	Version	1
- UI - Great Work Manager	Version	14
- UI - Improved City View (Vox Populi EUI)	Version	10
- UI - Notify Exit Resistance	Version	1
- Promotion Flags EUI	Version	1
- UI - Promotion Tree	Version	17
- UI - Upgrade Tree	Version	9
- Unit Path Viewer	Version	10
- Units - Missiles No Supply	Version	1

```
![image](https://user-images.githubusercontent.com/22875626/41989926-faa426cc-7a0e-11e8-8402-5830a71e5831.png)
![image](https://user-images.githubusercontent.com/22875626/41989949-0ebda6c4-7a0f-11e8-977d-a889f984ce09.png)
![image](https://user-images.githubusercontent.com/22875626/41989965-19a7aaee-7a0f-11e8-9642-21175c9befa1.png)
![image](https://user-images.githubusercontent.com/22875626/41989980-227f9f46-7a0f-11e8-9dd5-468c9490feca.png)
![image](https://user-images.githubusercontent.com/22875626/41990044-50aef52e-7a0f-11e8-8fc7-4164026525ce.png)

**Comment by ridjack** [comment]
Another game with the same thing occurring; this time with me as Babylon and Korea declaring on my vassal, the Celts.

Logs and save: 
[AutoSave_0176 AD-1160.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2150206/AutoSave_0176.AD-1160.zip)
