### ISSUE TITLE
AI hasn't bothered to improve resources

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#4489]
_1. Mod version (i.e Date - 4/23):_
6/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I conquered a few cities and noticed that the AI hadn't bothered at all to improve her spice (turn 184). 
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/41525335-efd945ae-72e0-11e8-8219-4ce28782f9b6.png)

**Comment by cdanger341** [comment]
This is a problem I have been seeing on and off with plantation luxury resources for the last several updates of VP. In my most recent game I had a neighbor chop a forest to connect one copy of Silk, but then they left all of their other Silk tiles that spawned on forests unimproved up through the Industrial Era. They didn't have the Forest/Jungle pantheon or any other obvious reason for doing so. It is not a consistent behavior though, as most of the AI seem to be improving plantation luxuries with no hitches. Later in the game I saw that another Civ on another continent had done the same thing. They had a few plantation luxuries spawn on forests and flood plains and had left the forest tiles unimproved and had turned the flood plain luxury tiles into farms.

Perhaps it has something to do with the forest/jungle chopping being moved to a different tech and the base chop time increasing?

**Comment by ryanmusante** [comment]
I'm seeing this in my current game, noticeable just from keeping workers on automatic. I'll attach screenshots later.
