### ISSUE TITLE
Texture loading errors in Civlopedia

### ISSUE THREAD

**Issue by m4ti140** [LoneGazebo/Community-Patch-DLL#4490]
1. Mod version: 5/20

2. Mod list:
Vox Populi: Patch+Balance+EUI+43 civs (1,2,3,4,5,6c)
City Limits v7
Faster Aircraft Animations v3
Gibraltar, Reef and Krakatoa fixes v101
Improved Air Recon v1
Improvement - Airbases v14 - with the fixed xml
Improvement - Tunnel v5
Lake Victoria fix v2
Mechanized Infantry with Soldiers, Resized v2
Promotions - Flagship v2

3. Error description:
When browsing Civlopedia I get error messages. E.g. for Pathfinder, I get: Texture Load Error - Unable to load texture [expansion2-64.dds] (might be wrong on the exact name of the file, writing from memory). I do have all the expansions and dlcs installed save for the final map dlcs.
 
4. Steps to reproduce (optional): 
Start a game and open Civlopedia. Open e.g. Pathfinder and see what happens.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2112725/Logs.zip)

**Comment by supermerill** [comment]
It may be because your civ5 has run out of memory. It can happen when there are too many things.

**Comment by LoneGazebo** [comment]
@supermerill is correct.
