### ISSUE TITLE
Incorrect puppet yields with Imperialism/Martial Law

### ISSUE THREAD

**Issue by Omen-of-Peace** [LoneGazebo/Community-Patch-DLL#4492]
_1. Mod version (i.e Date - 4/23):_ 6/14 (modpack from the forum)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ the text of the Martial Law policy (Imperialism tree) indicates that the puppet penalty is reduced to -50%. However, when checking a puppet, the penalty is -55%.
(I think it used to reduce penalties by 25% - maybe it was never changed even though the text was?)

**Comment by supermerill** [comment]
20% + 25% = 45%

I don't understand your problem
