### ISSUE TITLE
Settling on a hill: base yields of 2F, 3H instead of 2F, 2H?

### ISSUE THREAD

**Issue by Omen-of-Peace** [LoneGazebo/Community-Patch-DLL#4494]
_1. Mod version (i.e Date - 4/23):_ 6/14 (modpack from the forum)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ I noticed it in 5/30 but unlike other yield issues it doesn't seem to have been fixed. Or maybe I misremember?
IIRC, I think base city yields should be as follow (when NOT settling on a resource):
1) Hill -> 2F, 2H (currently: 2F, 3H, so 5 yields total instead of 4 in the options below)
2) Fresh water -> 3F, 1H
3) other -> 2F, 1H, 1G

With resources, there are many more cases. In a recent game, I settled on a Marble hill and it gave me 2F, 4H - which would have been 2F, 3H in earlier versions I think.

**Comment by LoneGazebo** [comment]
the extra hammer is from the resource, and it's intentional.

**Comment by Omen-of-Peace** [comment]
@LoneGazebo Just to re-confirm: it's intended that settling on a resource-less hill gives a total of 5 yields (2F, 3H), when it used to be (2F, 2H) in previous versions and in vanilla, if I'm not mistaken?

When settling on marble, it's now (2F, 4H) when it used to be (2F, 3H).

That makes settling on hills MUCH better than on flat terrain.
