### ISSUE TITLE
Outdated "official modpack"

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#4495]
The "official" modpack is highly outdated (one year).
I've made a modpack with 2018-06-14, no other mods, with the happiness fix here: https://mega.nz/#F!FbZzVQAA!zv0NaE0Qw43NLkMDOVHHXA

@LoneGazebo We can also wait for the next version to update it. Just ask me when you think the version is stable enough.

**Comment by LoneGazebo** [comment]
once we have RNG fixed I will.

**Comment by LoneGazebo** [comment]
Cool thanks!
