### ISSUE TITLE
Going for Gold: Theming Bonus yields??

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4496]
_1. Mod version: 6/14 & Final version

This is a reminder to take stock of what yields are linked to Building_ThemingYieldBonus, so that we can determine what is/is not feasible for potential yields on theming bonuses for gold version of VP

In particular, confirm if extra tourism, food and GAP can be added as bonuses to buildings when themed.

If not, this may be a feature request so modders have the freedom to add these to their own creations

**Comment by supermerill** [comment]
YIELD_CULTURE
YIELD_GOLD
YIELD_SCIENCE
YIELD_FAITH
YIELD_PRODUCTION
YIELD_GOLDEN_AGE_POINTS

curently, other yields are only available when BALANCE_CORE_JFD is set to 1. But it can be enable in 10 sec (or a bit more if i have to add an other switch).
These other yields (for info):
	YIELD_GREAT_GENERAL_POINTS,
	YIELD_GREAT_ADMIRAL_POINTS,
	YIELD_POPULATION,
	YIELD_CULTURE_LOCAL,
	YIELD_JFD_HEALTH,
	YIELD_JFD_DISEASE,
	YIELD_JFD_CRIME,
	YIELD_JFD_LOYALTY,
	YIELD_JFD_SOVEREIGNTY,

**Comment by pineappledan** [comment]
Great, so everything is allowed then! This can be closed, since there’s nothing else to be done
