### ISSUE TITLE
Peace offer pulled back.

### ISSUE THREAD

**Issue by Txurce** [LoneGazebo/Community-Patch-DLL#4497]
_1. Mod version (i.e Date - 4/23):_ 6/14

_2. Mod list (if using Vox Populi only, leave blank):_ Info Addict, Quick Turns

_3. Error description:_ 
 England rescinds peace offer.

_4. Steps to reproduce (optional):_

Ask England for a peace deal.
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Dido t358.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2125669/Dido.t358.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Could use more information on this.

**Comment by Txurce** [comment]
In essence, the English say they want peace, but won't offer anything,
despite being on the cusp of having to capitulate.

Earlier you guessed that the problem may arise when the civ offers a city
-- it then can't follow through.

**Comment by TechpriestEnginseer** [comment]
I'm confused because I can't load the save game at the moment (screenshots are extremely helpful in these cases)

Are you saying your war score is 100, but they won't surrender to you?

**Comment by Txurce** [comment]
The game is long gone, so I'm sorry but no screenshots.

The score was around 80. I asked England to surrender. They offered a peace
deal, including one of their cities. But the trade screen said "impossible"
for their offer, and when I tried to accept, England said "No." The only
offer they would accept was a white peace.

I had the identical situation occur a few patches back.

Your guess was that the offer of a city was the problem. Subsequent to that
game, I've had plenty of capitulations, but none involved the offer of a
city.

**Comment by HeathcliffWarriors** [comment]
I just experienced the same issue. In case it's helpful I'll attach a save and logs.

How to replicate: Hit "Next Turn".
Save: 
[Peace Treaty Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2174226/Peace.Treaty.Bug.zip)
Logs: 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2174227/Logs.zip)

Screenshots:
![screenshot 8531](https://user-images.githubusercontent.com/38794241/42425211-ee7ed824-82e7-11e8-82ab-f2a76c9980f6.png)
![screenshot 8533](https://user-images.githubusercontent.com/38794241/42425212-ee9573e0-82e7-11e8-94e4-b0cd09da9b71.png)
![screenshot 8534](https://user-images.githubusercontent.com/38794241/42425213-eea91d3c-82e7-11e8-90d2-574980328e8a.png)
![screenshot 8535](https://user-images.githubusercontent.com/38794241/42425214-eeba0d68-82e7-11e8-84c9-6a2c7138956b.png)
![screenshot 8537](https://user-images.githubusercontent.com/38794241/42425215-eecfddbe-82e7-11e8-8535-a5b7211ec991.png)

**Comment by HeathcliffWarriors** [comment]
Bonus text bug: "We decline ."

**Comment by HeathcliffWarriors** [comment]
Also, "Peace Deal Value" shows up on both the left and right side of the "deal value bar". Could be related.
