### ISSUE TITLE
Puppets increase culture cost by 7%

### ISSUE THREAD

**Issue by Cozzolino92** [LoneGazebo/Community-Patch-DLL#4498]
_1. 6/14 (also encountered on 5/20)

_3. Puppeting a city will increase culture cost by 7%. I didn't check the effect of further puppets and it doesn't affect Science cost. 

_4. Puppet any enemy city.

Screenshots: 
![civ5screen0022](https://user-images.githubusercontent.com/39533968/41776652-e555a51e-7628-11e8-8025-bb1ba57c3162.jpg)
![civ5screen0024](https://user-images.githubusercontent.com/39533968/41776657-ec38e6ca-7628-11e8-99da-265ccbff1c9c.jpg)

### Update: the second puppet didn't come with culture cost increase

**Comment by supermerill** [comment]
When you take a new city, it increase the cost if it up you to a higher count of 'no-puppet" cities.
But when you sell / choose puppet / destroy a city, it doesn't decrease the cost.
Gazebo say he won't change that.

**Comment by Cozzolino92** [comment]
I don't understand. So, taking a city temporarily increase the culture cost until you decide what to do with it. Then, if I decide to puppet it, the culture cost won't go back to the previous value. But why would that be the case for the first puppet only?

**Comment by LoneGazebo** [comment]
It’s been that way for 6 years. It’s a design core of vanilla.
