### ISSUE TITLE
Culture Victory description incomplete

### ISSUE THREAD

**Issue by Ikaros82** [LoneGazebo/Community-Patch-DLL#4499]
_1. Mod version (i.e Date - 4/23):_ vox-populi-20-05-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Culture victory entry of civilopedia does not mention the Citizen Earth Protocol, available with Telecommunications, and necessary to win.

![civculturalvictory1](https://user-images.githubusercontent.com/23363427/41806436-38b9d280-76be-11e8-85ef-b0dbe3059240.png)

![civculturalvictory2](https://user-images.githubusercontent.com/23363427/41806437-407631a8-76be-11e8-8a5d-30c7e87afd46.png)

**Comment by supermerill** [comment]
It's fixed since the 2018-06-12
