### ISSUE TITLE
Fort missing production bonus at Mobile Tactics

### ISSUE THREAD

**Issue by Zarrk** [LoneGazebo/Community-Patch-DLL#4500]
_1. Mod version (i.e Date - 4/23):_
6/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Citadel gains two production bonus with Mobile Tactics but Fort gains nothing because there is a typo in ImprovementChanges.sql line 234: it should be IMPROVEMENT_FORT.

_4. Steps to reproduce (optional):_

**Comment by TechpriestEnginseer** [comment]
Danke!
