### ISSUE TITLE
[ICON_CULTURE_LOCAL]

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#4501]
This doesn't exist. Is there a way of getting the pretty blue culture symbol?

**Comment by Hokath** [comment]
Doesn't seem to have worked. (I cleared the cache)

**Comment by LoneGazebo** [comment]
Mmm, yeah, there's no IconFontMapping XML for it as I never made a DDS file for the icon font map. It gets complex and requires DDS exporting power. If you can do that I can guide, otherwise I'll add it to my backlog.

**Comment by Hokath** [comment]
Only DDS I'm familiar with is diaminodiphenyl sulfone, so probably best you handle it 👍 
Completely not urgent in any way.
