### ISSUE TITLE
FindBestCultureBombExpend?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4502]
what is FindBestCultureBombExpend() about?

also, please merge, found a bad bug (recently introduced)

**Comment by ilteroi** [comment]
never mind, i removed it

**Comment by Iamblichos** [comment]
I created it. Remember the artist from vanilla. Unit bombs a plot like a citadel but doesn’t create an improvement.

**Comment by Iamblichos** [comment]
@ilteroi

**Comment by LoneGazebo** [comment]
I'll keep it in master, you two decide what to do with it. :)

**Comment by Iamblichos** [comment]
We can consolidate one function probably.

**Comment by ilteroi** [comment]
no worries, i merged the two functions, so it should work with and without an improvement.

however, it's only called for generals and venetian merchants - it's not quite clear to me how it's supposed to work for an artist type unit

**Comment by Iamblichos** [comment]
It has to be a general. The idea here is to couple this with a promotion that gives nearby enemy damage and give defense mod to military unit on top of it. So instead of building a citadel, The unit is a citadel...or almost for balance reasons since it can move.

**Comment by Iamblichos** [comment]
@ilteroi During the iteration to score the best plots will these cause a problem for the unit that doesn't do the build?


```
if(!pAdjacentPlot->canBuild(eBuild, GetID()))
				continue;

			//citadel special
			if (pkImprovementInfo && pkImprovementInfo->GetDefenseModifier() > 0)
			{
				//we want to steal at least one plot
				if (!pAdjacentPlot->IsAdjacentOwnedByOtherTeam(getTeam()))
					continue;

				if (pAdjacentPlot->GetDefenseBuildValue(GetID()) <= 0)
					continue;
			}
```

**Comment by ilteroi** [comment]
ok, the canBuild() check is a bug, should be moved inside the conditional

but this part confuses me: "The idea here is to couple this with a promotion that gives nearby enemy damage and give defense mod to military unit on top of it. So instead of building a citadel, The unit is a citadel...or almost for balance reasons since it can move." --> it sounds like you should take a look at the "FIELD_COMMAND" directive, instead of the "USE_POWER" directive.

**Comment by Iamblichos** [comment]
No I think it is right. I should've added that it doesn't build an improvement with a culture bomb, just acquires the tiles and dies if we are using power. If field command, the general is "citadel-like" for the military unit on top of it. So the general is a "moving citadel," and since it is so, it doesn't get to build a citadel for balance reasons, yet retains the ability to culture bomb.

**Comment by ilteroi** [comment]
well, kind of ... once the special general is expended, there are no more area effects?

just asking because you stressed those area effect but didn't mention the tile acquisition at all :)

**Comment by Iamblichos** [comment]
You have to add other promotions entries for getting the area effect (e.g. IsNearbyPromotion, GiveDefenseMod, NearbyEnemyDamage). This code here just handles when general wants to use power to culture bomb. Yes, if the general is expended. No area affects, No citiadel built, no more acting like a citadel. Just tile acquisition and unit supply, etc.

**Comment by LoneGazebo** [comment]
Where did we leave this?

**Comment by ilteroi** [comment]
uh, i think it's fine. i merged the two functions into one.

**Comment by LoneGazebo** [comment]
Cool. Just making sure.

**Comment by Iamblichos** [comment]
There's still the issue I noted above about the build check within the iterator.
