### ISSUE TITLE
Vassals Get Backstabbing Penalty When Master Declares War on their Friend

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4503]
_1. Mod version (i.e Date - 4/23): Most recent (6/14)

_2. Mod list (if using Vox Populi only, leave blank): IGE, but it happened in a game with just VP as well - I used IGE to replicate it faster

_3. Error description: When a vassal civ (Civ A) makes a declaration of friendship with another civ (Civ B), and then their master declares war on Civ B (forcefully dragging Civ A into the war), Civ A gets a backstabbing penalty with other civs, and a "Backstabbed Civ B" note shows up on their EUI panel.

Vassals shouldn't be penalized for their master's war declarations.

**Secondary Bug Note:** We made a "Declarations" of Friendship and then declared war on them! (This is actually a vanilla text bug as well)

(As well, "declared war" in the second message and "Declared War" in the first message - the grammatical inconsistency bugs me, OCD though it may be.)

_4. Steps to reproduce (optional): Vassalize a civ and then declare war on that civ's friend.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): Don't think needed.

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 
[Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2130321/Saves.zip)

4. Screenshots (optional): I used IGE to have Rome denounce Egypt, thus allowing me to show that they received an opinion adjustment for the master's war declaration.
![screenshot 7775](https://user-images.githubusercontent.com/38794241/41814474-60dd4cbc-771b-11e8-85c5-a9fa4ad1287a.png)
![screenshot 7776](https://user-images.githubusercontent.com/38794241/41814466-15947ffa-771b-11e8-8590-9d91ca1df287.png)
![screenshot 7777](https://user-images.githubusercontent.com/38794241/41814467-15a44638-771b-11e8-88d7-9f5697006f68.png)

**Comment by TechpriestEnginseer** [comment]
You lose your political independence upon becoming a vassal. This is a feature intended as you are free to break the DoF off at any time.

**Comment by LoneGazebo** [comment]
Yeah, this is intended by Putmalk.
