### ISSUE TITLE
Pagoda yields not adding up

### ISSUE THREAD

**Issue by Cozzolino92** [LoneGazebo/Community-Patch-DLL#4510]
_1. Mod version:_ 6/14

_2. Mod list:_

_3. Error description:_ Pagoda incorrect yields

_4. Steps to reproduce:_ Build a Pagoda anywhere, let different religions sink in for a few turns 

Pagodas do not seem to be working as intended. There's 4 religions in my capital yet I only get 2 of each yield from Pagoda (sometimes 1 but I can't tell what changed exactly

![civ5screen0027](https://user-images.githubusercontent.com/39533968/41971491-e3f358c6-7a0e-11e8-9b13-61a5d04cb574.jpg)

![civ5screen0031](https://user-images.githubusercontent.com/39533968/41971557-2cf3139a-7a0f-11e8-93d0-c6bdbd83e93d.jpg)

In the first screenshots, 4 religions are in my capital with at least 1 follower at the same time. In the second, you can see Pagoda yields not adding up.

**Comment by TechpriestEnginseer** [comment]
Isn't it +1 Yield per Religion?

**Comment by MoiMagnus** [comment]
@TechpriestEnginseer Not sure to understand. There is 4 Religion in the city, and the Pagoda seems to only give +2 Yields. So it seems that there is something wrong.

**Comment by LoneGazebo** [comment]
Pagoda yields don't appear under the city - they appear in the city view tooltip.

G
