### ISSUE TITLE
Air Defense and fighters not intercepting bombers

### ISSUE THREAD

**Issue by Rock1975** [LoneGazebo/Community-Patch-DLL#4511]
_1. Mod version (i.e Date - 4/23):_
5/20

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
My fighters and anti air craft are not shooting down bombers at all.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
yeah there were a bunch of code changes in the last release and the promotions need to be cleaned up for interception to work again.

**Comment by LoneGazebo** [comment]
What all does that entail?

**Comment by ilteroi** [comment]
check #4451

**Comment by LoneGazebo** [comment]
@ilteroi i've looked at the promotions and I don't see, specifically, what the issue is with them. Actually, I think the issue may be the RNG in the interception function - it was a small RNG of 10 x10, so it is possible it was always failing the RNG test.
