### ISSUE TITLE
Vassals proposes sanction against Master

### ISSUE THREAD

**Issue by Tarzan737** [LoneGazebo/Community-Patch-DLL#4514]
_1. Mod version (6/14)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Vassals keep on proposing for sanction against master and always votes yes if someone else propose it. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Not a bug. Your vassal hates you.

**Comment by Tarzan737** [comment]
Voluntary vassal? It was not like this in earlier versions or civ4 diplo stand alone.. see thread at forum, even if they hate me they sanction themselves!
