### ISSUE TITLE
txt_key_eui_building_supply_cap_local

### ISSUE THREAD

**Issue by marcoatk85** [LoneGazebo/Community-Patch-DLL#4515]
_1. Mod version (i.e Date - 4/23):_
5-20

_2. Mod list (if using Vox Populi only, leave blank):_
Info Addict
Civ5 Enhanced User Interface v1.29beta17

_3. Error description:_ 
I have an issue with EUI and I am so dummy to know how to fix it. As you can see I see some codes on the building screen. Can you tell me how can it be fixed? 

![20180701220253_1](https://user-images.githubusercontent.com/40754177/42150093-45f2c4a0-7de1-11e8-9daf-c40c354bcb1c.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Usually happens if you double-install EUI, as those text files are included in the EUI compatibility file.
