### ISSUE TITLE
Scaling Luxury happiness isn't multiplied, but added

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4517]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Basically description. If it goes +1 from luxuries, it only adds a base 1. No matter if you have 1, 3 or 5 luxuries, the amount will be increased by a base 1, so the luxuries do not start adding 2 each, but 1 each with a bare 1 happiness being just added on. You implied it's a bug so I posted

**Comment by LoneGazebo** [comment]
Not a bug, but also not a fair system. Adjusting.
