### ISSUE TITLE
Wonder Help Text Mixups

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4518]
1. version 6/14

The Taj Mahal wonder help text is Chichen Itza's
Chichen Itza's Help text is the Pyramids'
The Pyramid's help text is the Taj Mahal's

The three wonders have had their texts swapped

**Comment by LoneGazebo** [comment]
That’s a vanilla thing.

**Comment by pineappledan** [comment]
ooooh....
