### ISSUE TITLE
Nuke Costs

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#4519]
_1. Mod version (i.e Date - 4/23):_
Beta 14/6/2018 Version

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Noticed this in a video that Nukes cost half as much Gold as Production.
Checked the latest Beta and that hasn't changed.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![2018-07-03](https://user-images.githubusercontent.com/11430209/42237178-1539d69c-7ecb-11e8-97a6-75b74fcb0e7c.png)

**Comment by LoneGazebo** [comment]
They probably had a unit purchase modifier policy or wonder/building. There's no code specific to unit gold costs.
