### ISSUE TITLE
I'd like to have some code included in the CP

### ISSUE THREAD

**Issue by iskaandismet** [LoneGazebo/Community-Patch-DLL#4522]
I recently released a mod that I want to make compatible with the CP / VP (https://steamcommunity.com/sharedfiles/filedetails/?id=1430590312), which has its own DLL edits. They're quite minor and I've marked my edits; can I ask that they be included in the next version of the CP, and if so, where is the correct place to ask?

These are my edited dll files: https://drive.google.com/open?id=1N693z2NOpvdBL8KJ_usosbDAXZQA15n5

Some of the edits maybe should be made conditional to check if my policy branch has been loaded, but I'm actually not a skilled enough coder to do that without a lot of trial and error first.

**Comment by LoneGazebo** [comment]
ideally you would use this platform (github) for this. However, since you didn't fork the VP code, I can't guarantee that the location where you added code will be the same on our end. The best method for you would be to download the VP dll files from here, find your edit place, edit the code, and then create your own branch to make a merge request. I know it seems like a lot, but it's all pretty straightforward.

G

**Comment by iskaandismet** [comment]
Okay, so just to make sure I have the right idea:

-Download Zip from the Code tab in Github
-Create new Visual Studio project from downloaded files
-Compile to make sure it works
-If it does, add my code to the proper places in the new project
-Compile and check if it works
-Upload the downloaded new VS project with my changes here, somehow

amidoingitirite?

**Comment by iskaandismet** [comment]
I'm sorry, I've never used github before, and all those terms sound very unfamiliar to me. Could you explain it with a little more nuance, or is it all very obvious? I'm at work or I'd poke around and see what's what

**Comment by ilteroi** [comment]
you already have a github account, so you're almost there :)

press the fork button on the top right of the VP page. you now have your own repo you can commit to.

next step would be to install git and tortoisegit on your home machine.
then clone your forked repo. this creates a local copy. play around with it.

commit your changes, push them to your public repo. there are millions of git tutorials showing how to do this.
