### ISSUE TITLE
[Question] How does the AI determine what tiles to buy?

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#4523]
If I'm understanding this correctly, tile purchases are handled by DoPlotPurchases in CvEconomicAI.cpp. Specifically, the tile is bought when BuyPlot is called by pBestCity, with iBestX and iBestY as the being the coordinates of the tile to be purchased.

iBestX and iBestY are from the for loop to find the best city to buy a plot, where it takes the values of iTempX and iTempY. However, I don't see where iTempX and iTempY are defined. Aren't they still at the default value of 0?

**Comment by ilteroi** [comment]
GetBuyPlotScore() passes its parameters by reference, so they can be modified inside the function.

**Comment by HungryForFood** [comment]
Ah, didn't know that there's such a thing. I understand it now, thanks.
