### ISSUE TITLE
AddedFromNearbyPromotion in UnitPromotions Table

### ISSUE THREAD

**Issue by Tekamthi** [LoneGazebo/Community-Patch-DLL#4524]
_1. Mod version (i.e Date - 4/23):_
6/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
not sure if this is an error, or removed intentionally.. in some past modding, I've made use of the "AddedFromNearbyPromotion" field in the UnitPromotions table.  Seems to be no longer available?  The corresponding IsNearbyPromotion and NearbyRange are still showing in table.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Tekamthi** [comment]
thanks for clarifying.. i guess i should assume its not coming back, and adjust my mod?  I can probably accomplish what i need in lua anyway (albeit very amateurishly)

**Comment by Iamblichos** [comment]
Yeah I reworked all that stuff. Check the CoreTable entries for instructions.

**Comment by Iamblichos** [comment]
If you want some particular bonus to a unit that is near another unit that has the area effect of "IsNearbyPromotion", then let me know. I reworked all this for performance reasons. Basically the way this works now is same way a great general works, units get some given bonus in an area effect that you define by setting the nearbyrange.

**Comment by Tekamthi** [comment]
Been chipping away at modding in and balancing an alternative to some naval units, in particular modding how zeppelins and helicopters fly, allowing them to cross water unembarked for example.  To limit this upgrade somewhat, I've made it impossible for these units to heal outside friendly.  Using the addedfromnearby stuff, I had promos that would trigger when w/in x-range of a carrier (carrier had unique promo to enable this), restoring ability to heal.

My usage was thus a rather minor aspect, and I can live w/o, I can imagine how this check would be somewhat resource intensive

**Comment by Iamblichos** [comment]
I can add in the ability to heal when near some distance of the unit that gives out this ability. Just let me know what you would like for me to do.

**Comment by Tekamthi** [comment]
thats awesome! thanks!

Here's how I envision this might work, though of course I'm not familiar with the dll on any deep level.  If its too much code or too resource-intensive, I'll figure out something else, its cool.  

Ideally I'd like to have the option here to buff the various healinfriendly, healinneutral, healinenemy (i can't recall these tags from unitpromotions exactly, let me know if you need the exact labels) independently, w/in proximity of carrier (ie my old addedfromnearby promo buffed healinneutral by 10, and healinenemy by 5, to counter a base promo on the unit).  I'd only use 4 range under the scenario i described, but from a broader modding perspective, it would be nice to set the range, too.  I could work with this enabled between either individual unit types themselves, maybe through another table (this would probably be ideal), but also just using unitcombats (i'll be using unitcombat_carrier and unitcombat_helicopter for this), or even just built-in to the carrier.  I don't know that its worth your time to do that last option if that were somehow the only one viable, though.. too specific/narrow

while we're chatting about .dll, I wonder if it would be possible to duplicate the "withdraw before melee" with an similar "withdraw before ranged".  

thanks for considering!

**Comment by Iamblichos** [comment]
And this healing is not like march where you heal regardless of movement action/attack, right? You want to get additional healing when that unit decides to heal where it is in said territory. Yes I can work that up for you. The way it'll work will be like this:
Promotion Entries:
1)"IsNearbyPromotion" -- which is the special unit that gives out the ability to some unit, this is our "general"

2) "NearbyRange"-- this is our area of effect of plots, which have units, that get the bonus

3) "GiveDomain" -- which domain units can receive the bonus?


Those top 3 already exist, so I'll add something like this to the same promotion with additional entries:
"NearbyHealEnemyTerritory"
"NearbyHealNeutralTerritory"
"NearbyHealFriendlyTerritory"

So one promotion will have the top 3 and then you add in, the additional entries as you see fit to the promotion. Just to recap, the unit that gets the promotion is the special unit that gives out the ability, you units that receive the ability don't get a promotion. The bonus happens under the hood as it were.

**Comment by Tekamthi** [comment]
Thanks! sorry I'm checking back here a little late.
I wonder if instead of 'giveDomain', could it have 'giveUnit_combat' or even give unit_type?  The domain version won't work as a stand-in for my purposes

**Comment by Iamblichos** [comment]
I decided to stick to the domain only. I don't really like the design implementation of specific combat type or unittype, specifically for boats since there aren't that many to begin with. It's much simpler to just apply it to the whole domain.

**Comment by Tekamthi** [comment]
hey if the check is too intensive, i get it.. but this just won't fit for my purposes.  appreciate the thought anyway
