### ISSUE TITLE
More Backstabbing Penalty Shenanigans

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4526]
_1. Mod version (i.e Date - 4/23): 6/14 Beta

_2. Mod list (if using Vox Populi only, leave blank): Quick Turns, UI - Filters in Trade Route Overview

_3. Error description: If you backstab two of your AI friends, the modifier "We made a "Declarations" of Friendship with them and then declared war on them!" is replaced by "You have Declared War on leaders you've made Declarations of Friendship with!" with both of the leaders you backstabbed.

Shouldn't _both_ modifiers remain in place? i.e. You backstabbed us (which is a more powerful modifier), and you also backstabbed your other friend?

_4. Steps to reproduce (optional): 1. Make two AI friends.
2. Backstab one of them, observe the diplomacy modifiers.
3. Backstab the second one, observe the diplomacy modifiers.

Note that in the example below, I actually had three AI friends. I declared war on one, and then declared war on the second, which triggered a Defensive Pact with my third friend. Not sure if that affected the results.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2165420/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 
[Pre Backstabbing.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2165422/Pre.Backstabbing.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): N/A

4. Screenshots (optional):

After declaring war on Friend #1 (Brazil)
![screenshot 8142](https://user-images.githubusercontent.com/38794241/42308867-f46af3f2-8004-11e8-9cf4-bce9a780b083.png)
![screenshot 8143](https://user-images.githubusercontent.com/38794241/42308868-f47b03b4-8004-11e8-8b52-fc2faa2f6622.png)

After declaring war on Friend #2 (Mongolia). Mongolia's DP with England (Friend #3) activated.
![screenshot 8144](https://user-images.githubusercontent.com/38794241/42309297-341553a2-8006-11e8-866b-d84dc5c9b552.png)
![screenshot 8145](https://user-images.githubusercontent.com/38794241/42309298-3426acc4-8006-11e8-830a-167527048f43.png)

As you can see, the modifier for declaring war on them disappears. If I'm not mistaken this issue is present in vanilla as well.

**Comment by HeathcliffWarriors** [comment]
I've also identified a second possible bug. I was friends with both Mongolia and England at the time of declaring war on Mongolia.

However, though the notifications say I declared war on both of them...
![screenshot 8152](https://user-images.githubusercontent.com/38794241/42310381-48203206-8009-11e8-8ab6-7a8f3bbb8675.png)

I only receive a backstabbing penalty for declaring war on Mongolia, not England, even though they were both my friends. So, if you have two AI friends who have a Defensive Pact with each other, you can choose which one to receive a backstabbing penalty for...probably a bug.
![screenshot 8151](https://user-images.githubusercontent.com/38794241/42310473-82d2c13e-8009-11e8-9bed-3542e99e6640.png)

**Comment by HeathcliffWarriors** [comment]
Bug #3: Denouncing leaders you're friends with also has some issues.

First of all, the grammar mistake is present there too: "We made a Declarations of Friendship and then denounced them!".

There is also more grammatical inconsistency, although this is nitpicking:
"We made a Declarations of Friendship and then denounced them!"
"We made a Declarations of Friendship _with them_ and then declared war on them!"

And finally, the more substantive issues.
Issue #1 - AIs forget (or don't display) that you backstabbed other friends if you also backstab them.

After backstabbing Brazil, before backstabbing Genghis:
![screenshot 8158](https://user-images.githubusercontent.com/38794241/42312739-1a9de728-800f-11e8-8438-43392b3f99f0.png)

After backstabbing Genghis:
![screenshot 8159](https://user-images.githubusercontent.com/38794241/42312740-1ab06f74-800f-11e8-80a7-ccbc13005e3d.png)

Issue #2 - They forget (or don't display) that you backstabbed someone by denouncing them if you subsequently backstab someone by declaring war on them (including if you denounce them, which gives them a malus with other civs, and then declare war on someone else).

Relations with Mongolia, England and Brazil - after backstabbing Mongolia (denounced).
![screenshot 8162](https://user-images.githubusercontent.com/38794241/42313605-295112e8-8011-11e8-8fd8-e7f91fbd5173.png)
![screenshot 8163](https://user-images.githubusercontent.com/38794241/42313606-29621f7a-8011-11e8-91f2-35a9d81d6c41.png)
![screenshot 8164](https://user-images.githubusercontent.com/38794241/42313607-2976308c-8011-11e8-872b-c1878667b740.png)

I got the "We backstabbed them" modifier with Mongolia, and the "We backstabbed others" modifier with other civs.

However, if I then declare war on Brazil, all three of them forget that I denounced Mongolia and simply apply the "You have DoW'd leaders you've made DoFs with" modifier (Brazil applies the "We declared war on them" modifier and ignores the denunciation of Mongolia).
![screenshot 8165](https://user-images.githubusercontent.com/38794241/42313711-5b8e9758-8011-11e8-8e7f-997ee2eb7c89.png)
![screenshot 8166](https://user-images.githubusercontent.com/38794241/42313712-5ba0b636-8011-11e8-893a-c0a25c320b6a.png)
![screenshot 8167](https://user-images.githubusercontent.com/38794241/42313713-5bb068ce-8011-11e8-8941-65031cb4a822.png)

Mongolia in particular probably shouldn't forget that I backstabbed them just because I also backstabbed Brazil. Or if they don't forget, they should still display it.

**Comment by HeathcliffWarriors** [comment]
My suggested fixes:

1) Change the modifiers for denouncing/declaring war on other civs to:
- You have Denounced other civs you've made Declarations of Friendship with!
- You have Declared War on (or "attacked") other civs you've made Declarations of Friendship with!

And don't make them mutually exclusive, but keep the penalty cumulative like it is now.

2) Apply an additional penalty if you Denounced/Declared War on them.
- We made a Declaration of Friendship and then Declared War on them!
- We made a Declaration of Friendship and then Denounced them!

And make this additional penalty not mutually exclusive with the other penalties.


And finally, 3) Do the usual "Your recent diplomatic actions disappoint them." penalty when you break a DoF by denouncing/declaring war and update their approach immediately.

4) When you denounce a civ, their approach should be updated immediately anyway, if possible.

**Comment by LoneGazebo** [comment]
No- one supersedes the other.

**Comment by HeathcliffWarriors** [comment]
In that case, I don't see why "You have Declared War on leaders..." supersedes "We made a Declaration of Friendship and then Declared War on them!" - you'd think the AIs would care more about someone targeting them in particular.

Same with the denunciation - just because another AI is backstabbed through DoW doesn't mean they should ignore the fact that you made a DoF and then denounced them.

I think it'd make more sense if the penalties for targeting them in particular were separated, but DoW superseded denouncing for the general penalty all AIs get. I could see the reasoning behind that.

The other issues still stand though.

**Comment by LoneGazebo** [comment]
I checked the code, and the issue is that the UI concats itself after sorting. So the penalties are still there, but there isn't room to show them all. I'll fix the text issue, but otherwise the code is functioning correctly.

You can't merge these penalties because the counters must be maintained separately for data sanity.
