### ISSUE TITLE
[UI Feature Request] Backstabbing - Show Denounce Timer

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4527]
Currently, when a player (human or AI) backstabs someone they have a DoF with by denouncing them, their EUI diplomacy panel doesn't show the turns remaining on said denunciation, but it does show it for the recipient of the denunciation.

I see no real reason why this should be the case. Can the denunciation timer be restored for the player who backstabbed?
![screenshot 8155](https://user-images.githubusercontent.com/38794241/42320472-6ee79dc4-8023-11e8-8d5e-18597b02b18c.png)
![screenshot 8156](https://user-images.githubusercontent.com/38794241/42320473-6f25bdf2-8023-11e8-83e7-1a42d7d82ec9.png)

**Comment by LoneGazebo** [comment]
@infixo you tinkered with this. Want to finish it out?
