### ISSUE TITLE
"Request Help" - Strange AI Valuation

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4528]
_1. Mod version (i.e Date - 4/23): 6/14 Beta

_2. Mod list (if using Vox Populi only, leave blank): Quick Turns, UI - Filters in Trade Route Overview, IGE

_3. Error description: England is being weird about the Request Help feature.
1. The button to request help is still labelled "DEMAND". Shouldn't it be "REQUEST"?

2. I can request 0 Gold from Elizabeth (the only request she's willing to fulfill). She tells me "May this gift bring prosperity to your people." If I try to request something that isn't 0 Gold after that, she tells me "It's been too soon since our last show of generosity." despite having given me literally nothing.

Furthermore, "It's been too soon since our last show of generosity." shows up even if the AI leader rejected your request, just like a demand.

3. Elizabeth values a request of 1 Gold as "Impossible!", 2 Gold as -2, 5 Gold as -5, 50 Gold as -50, etc. What's the issue with 1 Gold specifically?

_4. Steps to reproduce (optional): Unknown.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2166681/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 
[Pre Backstabbing.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2166682/Pre.Backstabbing.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): N/A

4. Screenshots (optional):
Issues 1 and 2
![screenshot 8172](https://user-images.githubusercontent.com/38794241/42325243-9fa48372-8033-11e8-93e3-ed1decaaf007.png)
![screenshot 8173](https://user-images.githubusercontent.com/38794241/42325244-9fb825d0-8033-11e8-8a02-83e7d8f2aa3d.png)
![screenshot 8175](https://user-images.githubusercontent.com/38794241/42325277-c278bcce-8033-11e8-948c-3428526d0620.png)

Issue 3
![screenshot 8176](https://user-images.githubusercontent.com/38794241/42325285-cb411d4c-8033-11e8-9bd7-d3ab1e2f9491.png)
![screenshot 8177](https://user-images.githubusercontent.com/38794241/42325286-cb54f0b0-8033-11e8-8313-53bf3bac2e8d.png)
![screenshot 8178](https://user-images.githubusercontent.com/38794241/42325287-cb6510e4-8033-11e8-89e3-ce9b4ee55779.png)

**Comment by LoneGazebo** [comment]
It only becomes 'request help' if you're friends.
