### ISSUE TITLE
City State UI - Contender

### ISSUE THREAD

**Issue by Mzimoxs** [LoneGazebo/Community-Patch-DLL#4529]
Using only Vox Populi, 14/6 and 30/5 have this error.

The contender UI always says "error".

![contender1](https://user-images.githubusercontent.com/39007474/42384341-009427e4-813a-11e8-8541-41ace9f23435.jpg)
![contender2](https://user-images.githubusercontent.com/39007474/42384343-00d79074-813a-11e8-9e73-3996e812ae02.jpg)

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer ideas?
@Mzimoxs we need logs. Enable logging, post lua.log

G

**Comment by Mzimoxs** [comment]
I played a few turns, and opened a few city state screens. 
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2171848/Lua.log)

**Comment by TechpriestEnginseer** [comment]
Ah ik why you are not using EUI. The code in the non-EUI version is copied and pasted from EUI.
