### ISSUE TITLE
Information Age Start - Settlers vs Pioneers (new info

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#4531]
_1. Mod version (i.e Date - 4/23):_
6/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
G, I saw your notes on the previous issue. However, its not so cut and dry. I did a test. When you first start the game, you can upgrade a settler to a pioneer for 10 gold.

The screenshot I have attached shows my 2 new cities made at exactly the same time. One with a pioneer, the other with a settler. First, the population and borders are not the same. Second, the pioneer starts with a shrine for free (which probably doesn't matter since there is no religion), the settler does not.

In the grand scheme, it may not make enough difference to matter, but there is a subtle difference.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/42398722-8da1e2ac-8130-11e8-8f4d-b94244295bf1.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
That's because the pioneer has it's own unique set of buildings it can create- for advanced starts, however, each building is set on its own. It's a strange system, but it'd require tinkering with hardcoded loadout stuff (that could break scenarios, for example). Not going to touch.
