### ISSUE TITLE
Crash on end turn (version 5-20-3)

### ISSUE THREAD

**Issue by Reffy2** [LoneGazebo/Community-Patch-DLL#4534]
**Mod version**
5-20-3

**Error description**
Crash when ending turn. Also had crashes a few turns before this save. It's about a 90% chance to crash. 

In attachment a zip file containing a save file, and logs folder.
[End Turn Crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2172700/End.Turn.Crash.zip)

**Comment by LoneGazebo** [comment]
Unfortunately I'm debugging on the beta now, which is savegame incompatible with that version.
