### ISSUE TITLE
CS City Acquisition Quest Doesn't Work with Liberation

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4537]
_1. Mod version (i.e Date - 4/23): 6/14 Beta

_2. Mod list (if using Vox Populi only, leave blank): Quick Turns + Trade Route Overview Filters

_3. Error description: Zanzibar has a quest to capture the city of Tyre (CS captured by the Ottomans). Capturing and then liberating the city triggers several bonuses for the capture (Hero Worship bonus, Civilizing Mission bonus, France's UA) but not the bonus from completing the quest, because the CS was liberated rather than puppeted or annexed. This also happens if a major civ's city is captured and then liberated. The quest stays there.

I think this is a bug since all the other bonuses triggered except that one.

If this is intentional, I have to say it's unfriendly for a diplomatic victory, seeing as it's one of the very few quests that reward you with military XP and you did go to all the trouble of conquering the city in the first place, which could have involved a lot of warfare. The quest description doesn't say you need to _keep_ the city, just gain possession of it. And you can't later liberate a city-state you captured, nor the captured city of a dead civ.

_4. Steps to reproduce (optional): Use the Tank near Tyre to capture and liberate it. Hit "Next Turn".

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2174384/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 
[CS Quest Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2174385/CS.Quest.Bug.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): N/A

4. Screenshots (optional):
Before capturing and liberating Tyre:
![screenshot 8558](https://user-images.githubusercontent.com/38794241/42426965-fe75fdfe-82f9-11e8-9720-97e100dec613.png)
![screenshot 8559](https://user-images.githubusercontent.com/38794241/42426966-fe86583e-82f9-11e8-8abe-533e05e29e62.png)

Capturing and liberating Tyre (new notifications on the right trigger immediately upon city capture, before any decision is made):
![screenshot 8560](https://user-images.githubusercontent.com/38794241/42426979-0bd443d4-82fa-11e8-825f-6a4390885b9f.png)
![screenshot 8561](https://user-images.githubusercontent.com/38794241/42427043-591ea4a4-82fa-11e8-9c1a-3cf44e6ddbbc.png)
![screenshot 8562](https://user-images.githubusercontent.com/38794241/42427045-59317282-82fa-11e8-9bb1-fc2ca9ae3e82.png)

Next turn: Zanzibar does not record that I captured Tyre because I liberated it:
![screenshot 8565](https://user-images.githubusercontent.com/38794241/42427050-5eae4b5e-82fa-11e8-9e08-e5cae0adfe46.png)

**Comment by LoneGazebo** [comment]
The point of the quest is capture, not liberation. there's a separate quest for liberation.

**Comment by HeathcliffWarriors** [comment]
I think it's a good idea, but can the quest either:
1) Not trigger for cities which have already been conquered by another civilization (only giving the liberation quest) - or at least not for City-States, or;
2) Disappear if you decide to liberate it rather than annex it? Otherwise the quest stays there pretty much forever unless you decide to declare war on the questgiver, which is not friendly to a diplomatic victory or Germany, since you'd rather liberate CSs a good deal of the time.

**Comment by LoneGazebo** [comment]
The quest is fairly rare, and - unfortunately - minors can't track inter-turn actions like that (so the quest can only look to see who owns the city currently, not 'who captured and liberated it during a turn.'

**Comment by HeathcliffWarriors** [comment]
Hmmm....I've never seen a quest requesting me to capture a City-State directly, only when it's been captured by a major civ. I've also never seen a quest requesting me to capture an original capital. And I do see this quest at least 2-3 times a game.

Since the city-state will not target these cities while they're in control of their original owners (I think), can it simply be made to not target them even while they've been captured by another civ?

I think it should be possible to do, as city-states and original capitals are the only cities that can't be razed, so it could simply check "is this city razeable?" or "was this city a capital?" before offering a quest for it.

Better for diplomatic victory (since IMO it's not fun to have to choose between strengthening your military and a new CS ally because the quest can't detect it) and for avoiding getting hated by the AI (since getting control of capitals usually results in some powerful negative modifiers).

**Comment by HeathcliffWarriors** [comment]
Setting it up so that captured cities get liberation quests and uncaptured cities get capture quests (thus resulting in a balance of conquest and liberation quests) would also give the AI more of an incentive to liberate cities occasionally.

**Comment by LoneGazebo** [comment]
I'll see what I can do, but no promises.
