### ISSUE TITLE
[Feature Request] Block World Map Trade When There's No New Land

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4539]
Currently when you try to sell/buy a world map when there's no new land that the other party has explored, it just sets the Deal Value to "Impossible!"

However, wouldn't simply blocking the option (with the tooltip saying something like "We've already explored all of the lands they've explored." in red text) be a better way to handle it? I make a map trade about once or twice a game, and at all other times the option is just there to make the deal value Impossible if selected.

It'd also differentiate between "We've already seen everything they've seen" and "They don't want us to see what they've seen for military reasons"; if the AI actually does that, anyway.

The difference in that case would be that you could demand the map (whereas it's worthless to demand it if you've already explored everything they have).

![screenshot 8583](https://user-images.githubusercontent.com/38794241/42448486-4b95221c-834b-11e8-85e5-3c9fefdf6a49.png)

**Comment by LoneGazebo** [comment]
Not going to add the TT (as it's a PITA to do through LUA, but I can grey it out.

G
