### ISSUE TITLE
Constabulary culture bonus from New World Order tenet isn't shown in the build menu

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#454]
![8930_2015-07-25_00009](https://cloud.githubusercontent.com/assets/1131228/8885170/bbb09d20-3276-11e5-9041-110a37927af9.png)
But it is in the completed buildings list:
![8930_2015-07-25_00010](https://cloud.githubusercontent.com/assets/1131228/8885175/d95ed15c-3276-11e5-8eab-91a2cc731a9d.png)

**Comment by LoneGazebo** [comment]
That's because of how EUI handles city bonuses from policies. It can't call on the city until it has done the buikd, IIRC.
G
