### ISSUE TITLE
Landmark Diplomacy Bonus Issue

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4542]
The code for this modifier:
"You built a Landmark in their territory."

Doesn't factor in whether the Landmark is still in their territory, or whether you captured the city that contained it.

In my most recent game, I was at war with Russia, decided to excavate an artifact that was in a captured City-State's land, turned it into a Landmark (giving me the diplomacy bonus), liberated the City-State from Russia, transferring ownership of the Landmark to the City-State; and the bonus remained there. It continued to remain there as I conquered all of Russia's lands. Seems to be permanent, and I believe this is the case in vanilla as well. Intentionally kept?

**Comment by LoneGazebo** [comment]
The bonus doesn't last forever - only as long as a standard deal duration x2

G

**Comment by HeathcliffWarriors** [comment]
That opens up another issue:
![screenshot 8618](https://user-images.githubusercontent.com/38794241/42478587-3bc95828-83a3-11e8-87b3-253c5970f8dd.png)
