### ISSUE TITLE
More Typos

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4544]
_1. Mod version (i.e Date - 4/23): 6/14 Beta

_2. Mod list (if using Vox Populi only, leave blank): Quick Turns + Trade Route Overview Filters

_3. Error description:_ 
![screenshot 8599](https://user-images.githubusercontent.com/38794241/42475632-305c3c6c-8399-11e8-8f41-bccfe38dd5bb.png)
![screenshot 8601](https://user-images.githubusercontent.com/38794241/42475634-3071e15c-8399-11e8-8d1e-da9aea8e3958.png)

**Comment by HeathcliffWarriors** [comment]
Might also want a period after "choice"?

**Comment by LoneGazebo** [comment]
None of the bullets have punctuation (since most are incomplete sentences).

**Comment by LoneGazebo** [comment]
Also you must be as OCD as I am. :)
