### ISSUE TITLE
Spy intrigue diplo bonus can still be stacked up

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#455]
![8930_2015-07-25_00006](https://cloud.githubusercontent.com/assets/1131228/8885223/03d3e2ec-3277-11e5-91f4-ff407626913b.png)
![8930_2015-07-25_00007](https://cloud.githubusercontent.com/assets/1131228/8885225/05e3cb1a-3277-11e5-9262-05e646093107.png)

**Comment by LoneGazebo** [comment]
That's intentional (I didn't cut it off), but I'll reduce it some more.

G
