### ISSUE TITLE
Hanse TR effect

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#4550]
The German UB has "+5% [ICON_PRODUCTION] Production for each Trade Route your civilization has with a City-State." in the description. But despite my best efforts I can't find where this is declared in the code. Please could someone with better eyesight than me point it out?

Ty in advance.

**Comment by HungryForFood** [comment]
Its the column 'CityStateTradeRouteProductionModifier' under Buildings. As this suggests, it is very hard-coded; the only thing you can change is the percent.

I don't think VP changed this, so you should not find this in VP codes.

**Comment by LoneGazebo** [comment]
@HungryForFood is correct.

**Comment by Hokath** [comment]
Ah the hardest of codes. Thanks guys.
