### ISSUE TITLE
[Possible Bug] Winning Wars with Less than 25 Warscore Still Triggers Historic Event

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4552]
_1. Mod version (i.e Date - 4/23): 6/14 Beta

_2. Mod list (if using Vox Populi only, leave blank): TR Overview Filters, Quick Turns, Faster Aircraft Animations, IGE

_3. Error description: The Palace (and the notification that pops up) say that winning a war with a warscore > 25 gives you a Tourism bonus, however the Tourism bonus, or at least the notification for it, sometimes triggers if you win a war with your warscore being less than 25.

_4. Steps to reproduce (optional): I've encountered this bug before but I just attempted to replicate it and did not succeed; however, I know I've seen someone else mention it as well.

Can you make sure the code for the historic event properly checks to see if the current warscore is greater than 25?

**Comment by bigcat88** [comment]
Bug is still present in last version(15 July) too. In my last game see it 2 times.

**Comment by austin-wangyu** [comment]
Have been getting this as well (v.5-20-3), I have warscores just barely positive and well under 25 but I still get historic event notification. No extra mods, just VP.
