### ISSUE TITLE
Puppets improved by Martial Law only generate 45% instead of 50%

### ISSUE THREAD

**Issue by BiteInTheMark** [LoneGazebo/Community-Patch-DLL#4553]
_1. Mod version (i.e Date - 4/23):_
6/14

_2. Mod list (if using Vox Populi only, leave blank):_
-

_3. Error description:_ 
Puppets improved by Martial Law only generate 45% instead of 50%

_4. Steps to reproduce (optional):_
http://www.bilder-upload.eu/upload/4cffc5-1531332724.jpg

**Comment by LoneGazebo** [comment]
already reported and dealt with.
