### ISSUE TITLE
[UI Feature Request] Make it so wonders are visible to see before other items on techs with more than 5 items

### ISSUE THREAD

**Issue by chicorbeef** [LoneGazebo/Community-Patch-DLL#4554]
_1. Mod version (i.e Date - 4/23): 6/14 Beta

_3. Feature Request: Certain techs, show the buildings and units available and effects of the tech but not the wonder, for example Sailing shows the Lighthouse but not the Great Lighthouse when you hover over it. This is a problem because then I have no way of hovering over the tech to see if the Wonder is built or not. So I'm requesting that wonders always be made visible in the tech tool tip so that the player can know whether it is built or not.

**Comment by LoneGazebo** [comment]
Not feasible because of how iterators work.
