### ISSUE TITLE
Minuteman Golden Age On Kill giving +25 instead of +100

### ISSUE THREAD

**Issue by GhettoSpud** [LoneGazebo/Community-Patch-DLL#4555]
_1. Mod version (i.e Date - 4/23):_
6-14 Beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Minuteman unique "Golden Age From Victories" promotion states +100 Golden Age points per unit killed.
Actual yields are +25 golden age points (Does the +25 scale with gamespeed or is this mislabeled?)
Additionally, this promotion is also not mentioned in the civilopedia info text.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

- Logs & Savegame:
[details.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2187158/details.zip)

- Screenshots:
Promotion Label:
![20180711235131_1](https://user-images.githubusercontent.com/39657155/42613499-d7efba20-8566-11e8-9dd0-08a6481f0e2b.jpg)
Before:
![20180711235247_1](https://user-images.githubusercontent.com/39657155/42613501-d820a586-8566-11e8-8ff9-38180bb25f5d.jpg)
After killing 2 enemies:
![20180711235643_1](https://user-images.githubusercontent.com/39657155/42613498-d7ddd5c6-8566-11e8-926d-844ca47ba824.jpg)

**Comment by HalfEmptyMug** [comment]
The yield scales based on the strength of the unit killed (a Tercio has 25 strength, so it gives +25 golden age points)

**Comment by HeathcliffWarriors** [comment]
If that's the case, it shouldn't say "100 GAP" in the promotion label, though...
