### ISSUE TITLE
Question Re: Difficulty Handicaps

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4556]
How do BarbarianLandTargetRange and SeaTargetRange function?

You described them as the distance for the Barbarian pathfinder to search for visible trade routes - so does that mean that if my BarbarianLandTargetRange is 8, Barbarians can detect trade routes within 8 tiles of the nearest Barbarian unit...or encampment...or...?

It's the only difficulty handicap value I'm confused about.

**Comment by LoneGazebo** [comment]
They just control the distance the pathfinder looks for targets for barbs.
