### ISSUE TITLE
AI votes for global liberation when "Iron fist" is active

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#4558]
_1. Mod version (i.e Date - 4/23):_

6-14
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Vassal votes for global liberation, (obviously against me since I control 6 out of 9 AIs) even though the policy "iron fist" prevents them from being liberated.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/42657912-ff940da2-8623-11e8-90ba-2ea1938d83b8.png)

**Comment by HalfEmptyMug** [comment]
I believe Global Liberation is suppose to still work despite having the Iron Fist policy. It only prevents liberation through peace deals and independence requests from vassals.

**Comment by NewFellow** [comment]
It didn't, no one was liberated. I was still their master after the votes had passed.
