### ISSUE TITLE
Landsknecht Unit Purchase Description Inconsistency

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4559]
![screenshot 8651](https://user-images.githubusercontent.com/38794241/42661991-dd5cc182-85fd-11e8-8bce-d87f524e69d1.png)

This likely applies to Foreign Legions and Mercenaries as well. Might not be feasible to fix.

**Comment by LoneGazebo** [comment]
It's an auto-applied TT, so not feasible.
