### ISSUE TITLE
Units can be be instantly airlift upon disembarking

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#456]
![8930_2015-07-25_00005](https://cloud.githubusercontent.com/assets/1131228/8885238/2d45e738-3277-11e5-91eb-0a200ae1efb0.png)

**Comment by LoneGazebo** [comment]
How is it at surplus (5/3) movement?
G

**Comment by Radost** [comment]
#241

**Comment by LoneGazebo** [comment]
Gotcha, misunderstood your original post. I'll see if I can fix.
