### ISSUE TITLE
Great Scientist directive

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#4560]
When the AI is at war and they're not winning all of their wars, they are programmed to bulb their Great Scientists, even when its very early game.

I suppose the theory is that the science boost will then allow the AI to build more advanced units to possibly turn the war. However, in practice:

1. If the AI doesn't have enough gold and production, it might not get the advanced units out quick enough
2. Bulbing Great Scientists in the early game gimps your science too much.
3. The AI might not be researching a relevant military tech at that moment anyway.

I propose that we remove the war check from GetDirectiveScientist(), or at the very least only have that check after the Industrial Era or so.

Relevant code snippet from CvPlayerAI.cpp:

```
GreatPeopleDirectiveTypes CvPlayerAI::GetDirectiveScientist(CvUnit* /*pGreatScientist*/)
{
	if (!IsAtWarAnyMajor() || GetDiplomacyAI()->GetStateAllWars() == STATE_ALL_WARS_WINNING)
	{
		ImprovementTypes eAcademy = (ImprovementTypes)GC.getInfoTypeForString("IMPROVEMENT_ACADEMY");
		int iFlavor = GetFlavorManager()->GetPersonalityIndividualFlavor((FlavorTypes)GC.getInfoTypeForString("FLAVOR_SCIENCE"));
		iFlavor += (GetPlayerTraits()->GetWLTKDGPImprovementModifier() / 5);
		for (int iYield = 0; iYield < NUM_YIELD_TYPES; iYield++)
		{
			YieldTypes eYield = (YieldTypes)iYield;
			if (eYield == NULL)
				continue;
			iFlavor += GetPlayerTraits()->GetYieldChangePerImprovementBuilt(eAcademy, eYield);
		}
		iFlavor += GetFlavorManager()->GetPersonalityIndividualFlavor((FlavorTypes)GC.getInfoTypeForString("FLAVOR_GROWTH"));
		//This is to prevent a buildup of scientists if the AI is having a hard time planting them.
		iFlavor -= (GetCurrentEra() + GetNumUnitsWithUnitAI(UNITAI_SCIENTIST));
		// Even if not going spaceship right now, build academies up to your flavor.
		int iNumImprovement = getImprovementCount(eAcademy);
		if (iNumImprovement <= iFlavor)
			return GREAT_PEOPLE_DIRECTIVE_CONSTRUCT_IMPROVEMENT;
	}

	// a tech boost is never bad
	return GREAT_PEOPLE_DIRECTIVE_USE_POWER;
}
```

**Comment by supermerill** [comment]
That may be true in vox populi but not in vanilla, where bulbing a scientist gp isn't harmful.
 if(vp){ don't bulb } else { bulb } ?

**Comment by LoneGazebo** [comment]
changing it to

if (!IsAtWarAnyMajor() || GetDiplomacyAI()->GetStateAllWars() != STATE_ALL_WARS_LOSING)

should fix it.
