### ISSUE TITLE
Clicking on Nation States doesn't bring up next screen

### ISSUE THREAD

**Issue by Annan0480** [LoneGazebo/Community-Patch-DLL#4561]
_1. Mod version (i.e Date - 4/23):_
5/20/18 version

_2. Mod list (if using Vox Populi only, leave blank):_
Barbarians evolved (v3)
Calypso's colored religious icons basic (v.4) and extended (v.5)
City States Evolved (v 3)
Civ names by Policies (v. 8)
Donald J. Trump (v. 1)
Enlightenment era (vox populi) (v.1)
Extra Victory Conditions (v 1)
Faster Aircraft Animations (v 3)
Fortress Borders (v 2)
InfoAddict (v 22)
National Wonder Collection (v 3)
Promotions - Expansion Pack (v 9)
Quick Turns (v 10)
RED Modpack (v27)
Really Advanced Setup (v 15)
Redesigned Colors and Icons RCI (v 4)
Ships no city Capture (v 1)
Tectonic Map Script (v 4)
Unique City States (non-EUI) (v 2)
World Congress Reformation (v 5)
ZNW - Symbolic Ideology Tenets (v 1)

_3. Error description:_
When I click on a nation state city to access the screen where I can see quests and bully, nothing happens.  Does not matter whether clicking on the city itself or via the diplomacy screen. I have tried saving and reloading, clearing cache and starting new game, and redownloading latest CBP version, but I still get the same problem.  It also doesn't matter if a unit is close to the nation state or not. When i click on the city I hear the audio acknowledgement, but the next screen never appears. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Mod conflict. Uncheck all of the non VP mods and add them back in until you find the culprit.
