### ISSUE TITLE
Poland with 1963 POP in one city

### ISSUE THREAD

**Issue by AntonasBitsonas** [LoneGazebo/Community-Patch-DLL#4564]
_1. Mod version (i.e Date - 4/23):_
6_14 modpack

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In late game (turn 400) I liberated one of my many vassals.
It has only one city of Krakow.
In few turns it's population reached 1963 citizens
and then they became №1 in the chart of civs

_4. Steps to reproduce (optional):_
-download this modpack https://mega.nz/#F!FbZzVQAA!zv0NaE0Qw43NLkMDOVHHXA 
-keep playing for America and grab some vassals, better leave them with only one single city (not capital)
-in the lategame, liberate vassal
-???
-or just download this savegame 
[AutoSave_0412 AD-2132.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2195197/AutoSave_0412.AD-2132.zip)

4. Screenshots (optional):
![photo_2018-07-14_22-07-57](https://user-images.githubusercontent.com/17548101/42727734-59fda6a4-87b4-11e8-988b-90e26bb3d465.jpg)
![photo_2018-07-14_22-07-55](https://user-images.githubusercontent.com/17548101/42727736-5d7718f6-87b4-11e8-8e7f-3b973dc46b66.jpg)

**Comment by LoneGazebo** [comment]
I don't debug modpacks, sorry.
