### ISSUE TITLE
Citadel buffed twice at Mobile Tactics.

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#4565]
_1. Mod version (i.e Date - 4/23):_
6/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

@ mobile tactics citadels get +2 production and then another +1. It seems that the +1 is actually supposed to be for forts.

**Comment by LoneGazebo** [comment]
already reported and fixed.

**Comment by Edaka** [comment]
Oh, sorry, my bad. I only searched among open tickets.
