### ISSUE TITLE
City state ask to conquer a city whom I haven't met yet

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#4567]
_1. Mod version (i.e Date - 4/23):_
6-14

_2. Mod list (if using Vox Populi only, leave blank):_
A bounch of UI's only.

_3. Error description:_ 
City-state "UR" ask me to conquer Pi-Ramsses, a city belonging to a civilization I haven't met yet.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/42738343-a67faabc-8882-11e8-935e-3e3e52de7b0b.png)

**Comment by Mzimoxs** [comment]
Are you sure this isn't just one of the Hunnish cities..?

**Comment by NewFellow** [comment]
I don't have the save anymore, do, the hunns have a city going by the same name as the egyptians?

**Comment by Mzimoxs** [comment]
Huns don't have city names at all apart from Attila's Court, hence they borrow names from other civs in game.

**Comment by NewFellow** [comment]
There might not be a problem here then. But due to my sloppiness I didn't upload a "save" so we'll never know that for sure, except that it's _probably_ the case.
