### ISSUE TITLE
CIV6_ROADS not working as intended

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#4568]
_1. Mod version (i.e Date - 4/23):_
6/14

Calling @supermerill ! I've just posted about this in your thread on the Civ6 additions mod, but I'm going to copy the same thing here if you excuse me.

Hello again merill, hope you're doing well. I've just installed the 6/14 VP version and there seems to be a problem with the automatic road building.

First of all, roads are getting build under caravans right as they move, not at the end of the trade route duration. For example, if a caravan moves two tiles, two roads will get constructed that turn.
Secondly, each time a caravan passes over a neutral territory, you get -1 gold for road maintenance, as if another road has just been build. Every time. So, for example, if your caravan crossed a neutral tile 20 times, you will see -20 gold for road maintenance just for that one tile. And it keeps stacking up. Removing that road tile with a worker will only remove -1 gold.

I know that your original intent was to remove road maintenance altogether, but it used to work fine some time ago, so I'm hoping that maybe you will have time to look into that.

**Comment by Iamblichos** [comment]
I changed this up to do exactly what Civ6 does in building roads. We can just change how maintenance works.

**Comment by Edaka** [comment]
Ah, okay. That makes road building by workers even more obsolete, then. I think I personally liked it more when you had to wait for the road to be completed, it kinda added a strategic layer. But that I can live with. 

So yeah, maintenance is the real deal. Why does it only add up each time a caravan passes a neutral tile, even when there's already a road? It doesn't do that in your own lands. I noticed when I was paying 22 gold per turn for a something like 8 tile long road, the only one I had, and the cost kept creeping up almost every turn.

**Comment by supermerill** [comment]
Sorry, i'm not at home right now. I will have to do some serious maintenance on my modmods since P has evolved a lot since then. I can't promise anything, but it's on my list.

**Comment by Edaka** [comment]
Take your time, man. :)
