### ISSUE TITLE
Barbarian assault capturing high amounts of science/gold

### ISSUE THREAD

**Issue by ryanmusante** [LoneGazebo/Community-Patch-DLL#4569]
_1. Mod version (i.e Date - 4/23):_
7/15

_2. Mod list (if using Vox Populi only, leave blank):_
UI Mods, Change VP Options, Terrain Texture Pack, Promotion Flags EUI

_3. Error description:_ 
Barbarian assaults on cities stealing high amounts ranging sometimes normal lows to extremely high 50+. First noticed with most recent build 7/15

_4. Steps to reproduce (optional):_
1. Build city
2. Await Barbarians 

---------------------------
![barbs](https://user-images.githubusercontent.com/26808646/42766870-80c1dd2a-8956-11e8-8853-3658a35c1960.png)

**Comment by HeathcliffWarriors** [comment]
I've experienced this as well, they stole 3 turns of research with one attack. Probably has to do with the changes to pillaging?

**Comment by Enrico-Swagolo** [comment]
Saw the same thing. Weirdly, sometimes they get  what appears to be the old values that aren't crippling, but other times I see myself or an enemy city that suddenly lost 50~% of it's HP when a civ couldn't have been responsible and I know what happened there. Barbies are out of control in this regard.
