### ISSUE TITLE
Diplomats don't start at full movement upon creation.

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#457]
And because of that they can't be airlift on the turn of creation.
![8930_2015-07-25_00003](https://cloud.githubusercontent.com/assets/1131228/8885267/7e0642a8-3277-11e5-9bb4-bb1eac13410d.png)

**Comment by LoneGazebo** [comment]
Did you build a diplo building that turn? Sometimes that happens with promotions that are granted on the same turn as a unit is built.

**Comment by Radost** [comment]
I've built several diplomats after building a diplo structure and all of them had this problem.

**Comment by LoneGazebo** [comment]
I've added a check to make sure units are given their full movement on creation. Civilian units are handled differently in some cases, so it may not be a full solution. We'll see.
