### ISSUE TITLE
Graphical Corruption on tiles in block like formation

### ISSUE THREAD

**Issue by ryanmusante** [LoneGazebo/Community-Patch-DLL#4570]
_1. Mod version (i.e Date - 4/23):_
7/15

_2. Mod list (if using Vox Populi only, leave blank):_
UI Mods, Change VP Options, Terrain Texture Pack, Promotion Flags EUI

_3. Error description:_ 
Random tiles next to cities have block sized graphics corruption produced when starting new game. 

_4. Steps to reproduce (optional):_
Perhaps it is only my configuration because I am running wine+steam and it could be a regression in wine staging. 

Posted in case others are seeing and it can be reproduced. 

---------------------------
![graphics_corruption](https://user-images.githubusercontent.com/26808646/42766995-cb3d3d40-8956-11e8-912e-cad9f82c4cfb.png)

**Comment by ilteroi** [comment]
this is the rock of gibraltar. sometimes it's corrupted. can't be fixed but harmless

**Comment by LoneGazebo** [comment]
Yup.
