### ISSUE TITLE
Nukes destroyed by Nukes

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#4571]
_Mod version (i.e Date - 4/23):_
7/15 w/EUI

_Mod list (if using Vox Populi only, leave blank):_
IGE, QuickTurns

_Error description:_ 
When Nuking a city with either an ICBM or Atomic Bomb, any of either nuke stationed in the target city is destroyed 

---------------------------
Supporting information:
Both Fez and Rabat had 2 ICBMs and 2 ABs, but all in Rabat were destroyed when hit with an AB
![](https://i.imgur.com/nuMXu2d.jpg)

**Comment by supermerill** [comment]
Like in BnW civ5, no?
You think pre-emptive strike should be banned?

**Comment by HalfEmptyMug** [comment]
@supermerill It was suppose to be changed in the current version
> Units
> ICBMs now invulnerable to nuclear strikes (does not apply to atomic bombs)

**Comment by supermerill** [comment]
oh! a new version!
my bad, sorry.

**Comment by Vyyt02** [comment]
How do I change the ICBMs back to "destroyed by nukes"? Thanks!

**Comment by supermerill** [comment]
@Vyyt02 
in UnitChanges.sql, delete the line with PROMOTION_NUCLEAR_SILO

**Comment by Vyyt02** [comment]
Thanks, @supermerill !
