### ISSUE TITLE
Wonder fail notification

### ISSUE THREAD

**Issue by Mzimoxs** [LoneGazebo/Community-Patch-DLL#4572]
Vox Populi 15/7

Every time I fail to build a wonder, I get an ugly un-dismissable notification as seen twice on the right in the picture. Reloading removes it, though.

![beaten](https://user-images.githubusercontent.com/39007474/42787029-e7ac6dc8-8958-11e8-8196-fded76b1130c.jpg)

**Comment by LoneGazebo** [comment]
That’s a mod conflict. Probably with a custom civ missing an icon size.

**Comment by Mzimoxs** [comment]
We can savely exclude that because I don't use other mods. Do you need a save?

**Comment by LoneGazebo** [comment]
Do you own all DLC?

**Comment by Mzimoxs** [comment]
Yes of course. This notification is _additional_ to the usual notification you get.

**Comment by HalfEmptyMug** [comment]
I think it's an issue with the no-EUI version, since I also had the same issue on 6/14. It works correctly with EUI.

**Comment by pineappledan** [comment]
I am using the EUI version of 6/14, and I have had this same notification. 

It's not always the Hagia Sophia icon, but it's always the Hagia Sophia if it's the first wonder you've ever been beaten to. If this is your 2nd, or third time losing a wonder race, the notification is either Hagia Sophia, or an icon for a wonder you lost before.

**Comment by jnzs13** [comment]
Excuse me here, i did not want to open another ticket, because I had a similar problem using 7/15 EUI.

When I lost the race to build the pyramid for another civilization, the notification came with the icon of the stohenge.
