### ISSUE TITLE
Question about oil and aluminum placement on the tech tree

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#4573]
Not a bug, rather a question. So, the techs that unlock oil and aluminum are placed in a peculiar way. I say that because in order to unlock any unit in the game that requires a strategic resource, you must first unlock the strategic resource itself. This works for every strategic resource, except for oil and aluminum. 

So I ask: is this done intentionally for balance reasons? Because if nobody's actually too attached to the current way, I'd change it so that these two work like all the other strategics. Why? I think that, in this case, streamlining techs like that may be both beneficial to the AI and for the enjoyment of the game by human players (I can vouch for... myself).

Here's a list of units that one can unlock without unlocking their prerequisite strategics first: triplane, bomber, light tank, carrier, helicopter gunship. Now, this would get rectified if these techs got juggled: *switch electricity with corporations,
*switch ballistics with flight,
*switch penicillin with refrigerators,
*switch academy yield boost with carrier.

As you can see, this is supposed to be an innocent switcharoo with little conceivable impact on balance. Well, except for, maybe, the carrier/academy boost switch, because that would allow carriers to be unlocked at the same time as nuclear bombs. Anyways, I could do a pull request of the edited version for you if you'd like that.

**Comment by LoneGazebo** [comment]
I think this belongs on the sub forum. It’s not a big report.

**Comment by Edaka** [comment]
Okay, I'll repost there.
