### ISSUE TITLE
How do I open and edit the Community Patch Visual Studio Solution?

### ISSUE THREAD

**Issue by iskaandismet** [LoneGazebo/Community-Patch-DLL#4574]
Okay, so I'm getting around to this: https://github.com/LoneGazebo/Community-Patch-DLL/issues/4522

As ilteroi helpfully suggested, I pressed the fork button, created a repository, and cloned the repository to create a local copy. However when compiling CvGameCoreDLL.vs2010.sln with VS2010, I get the error:

1>  StackWalker.cpp
1>stackwalker\StackWalker.cpp(82): fatal error C1083: Cannot open include file: 'CvGameCoreDLLPCH.h': No such file or directory

I'm not very familiar with this sort of thing. Help?

**Comment by ilteroi** [comment]
wrong / old solution file -> try with VoxPopuli_vs2013.sln

**Comment by iskaandismet** [comment]
Okay, so I downloaded VS 2013 and opened VoxPopuli_vs2013.sln with it, when building I got these warnings: 

1>FireWorksWin32.lib(FMemoryStream.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FMemHooks.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FCrc32.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>CvWorldBuilderMapWin32.lib(CvWorldBuilderMap.obj) : warning LNK4099: PDB 'vc90.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\CvWorldBuilderMap\lib\\CvWorldBuilderMapWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\vc90.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FEndian.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FDebugHelper.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FIFile.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>CvWorldBuilderMapWin32.lib(CvWorldBuilderMapModData.obj) : warning LNK4099: PDB 'vc90.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\CvWorldBuilderMap\lib\\CvWorldBuilderMapWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\vc90.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FString.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FILogFile.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>CvWorldBuilderMapWin32.lib(CvWorldBuilderMapTypeDesc.obj) : warning LNK4099: PDB 'vc90.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\CvWorldBuilderMap\lib\\CvWorldBuilderMapWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\vc90.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FAutoVariableBase.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FDialogTemplate.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(StdAfx.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FStlContainerSerialization.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FTempHeap.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>CvWorldBuilderMapWin32.lib(CvWorldBuilderMapTypeGroup.obj) : warning LNK4099: PDB 'vc90.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\CvWorldBuilderMap\lib\\CvWorldBuilderMapWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\vc90.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FDataStream.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FAutoArchive.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FError.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FCriticalSection.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>FireWorksWin32.lib(FTimer.obj) : warning LNK4099: PDB 'cvgamecorefireworksfinal releasewin32.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FireWorksWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\cvgamecorefireworksfinal releasewin32.pdb'; linking object as if no debug info
1>CvWorldBuilderMapWin32.lib(CvWorldBuilderMapPCH.obj) : warning LNK4099: PDB 'vc90.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\CvWorldBuilderMap\lib\\CvWorldBuilderMapWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\vc90.pdb'; linking object as if no debug info
1>CvGameCoreDLLUtilWin32.lib(CvAssert.obj) : warning LNK4099: PDB 'vc90.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\CvGameCoreDLLUtil\lib\\CvGameCoreDLLUtilWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\vc90.pdb'; linking object as if no debug info
1>CvGameCoreDLLUtilWin32.lib(CvEnumSerialization.obj) : warning LNK4099: PDB 'vc90.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\CvGameCoreDLLUtil\lib\\CvGameCoreDLLUtilWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\vc90.pdb'; linking object as if no debug info
1>CvGameCoreDLLUtilWin32.lib(CvStringUtils.obj) : warning LNK4099: PDB 'vc90.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\CvGameCoreDLLUtil\lib\\CvGameCoreDLLUtilWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\vc90.pdb'; linking object as if no debug info
1>FLuaWin32.lib(FLuaCommon.obj) : warning LNK4099: PDB 'vc90.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FLuaWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\vc90.pdb'; linking object as if no debug info
1>FLuaWin32.lib(FLuaTypes.obj) : warning LNK4099: PDB 'vc90.pdb' was not found with 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\FirePlace\lib\\FLuaWin32.lib' or at 'C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Debug\vc90.pdb'; linking object as if no debug info
1>  VoxPopuli.vcxproj -> C:\Users\sacul\Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\\BuildOutput\Debug\CvGameCore_Expansion2.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

and then after creating a test mod to check my dll, civ5 would crash on loading the mod. Any more suggestions?

**Comment by LoneGazebo** [comment]
If it succeeds with 56 debug warnings (or 28 release warnings) its working correctly.

**Comment by ilteroi** [comment]
the build is fine, these warning are just for the SDK libs without debug symbols.

as for the crash, I don't know what you did, but you should probably drop the resulting DLL into the "mods/community patch" folder for testing.

**Comment by iskaandismet** [comment]
Okay, so I compiled the DLL by opening VoxPopuli_vs2013 in Visual Studio 2013 and then right clicking VoxPopuli (Visual Studio 2008) in the Solution Explorer and selecting Build. Then I installed the latest Community Patch only, and then copied my compiled DLL (CvGameCore_Expansion2.dll, from the BuildOutput folder in VS2013/Projects/etc.) into it (the (1) Community Patch folder), overwriting the existing one, and then tried to load the mod. CTD. 

Am I doing anything wrong? I noticed that my compiled DLL is ~12,000 kb and the one in the CP folder is ~6,000. Is that an indicator of something?

**Comment by Iamblichos** [comment]
You have it set on debug mode.

**Comment by iskaandismet** [comment]
Some quick google-fu isn't helping. How do I turn debug mode off?

**Comment by LoneGazebo** [comment]
Should be a drop down up on the top bar of VS that says ‘Debug’ - switch it to ‘Release.’

**Comment by ilteroi** [comment]
to be clear, debug build vs release build explains the size difference, but not the crash.

that really shouldn't be happening - do you have all the expansion packs and DLCs?

**Comment by iskaandismet** [comment]
Gah, I'm still getting a ctd :(.

My exact steps were:
-Avoid repo issues for now by going to LoneGazebo/Community-Patch-DLL, clicking Clone or download, download zip.
-Extract zip, open VoxPopuli_vs2013 project in VS 2013 Express. Change from debug to release. Right clicked VoxPopuli (Visual Studio 2008) in the Solution Explorer and selected Build.
-Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped
-DL latest cp (5-20-3), install cp only
-Copy CvGameCore_Expansion2.dll from Documents\Visual Studio 2013\Projects\Community-Patch-DLL-master\BuildOutput\Release to MODS\(1) Community Patch

When enabling and clicking next in the mods menu, few seconds of loading and then ctd. My dll is 6,077 kb without my having made any changes. The one in  5-20-3 is 6,071. Does that mean anything? I'd really like to make my mod compatible with the CP, and it's kinda frustrating that this isn't working for me. Any suggestions?

**Comment by iskaandismet** [comment]
PS: Yup, I have all the DLC. (Except maybe a couple of map scripts?)

**Comment by ilteroi** [comment]
so you're using a CP build from may with the latest DLL? that would explain the crash.

the versions need to match. you can download the latest beta build from the forum ...

**Comment by iskaandismet** [comment]
Okay, I got it to work! Thanks so much guys for your help and patience. Will open new issue soon with wip.

**Comment by LoneGazebo** [comment]
🎉
