### ISSUE TITLE
Auto-purchase with faith doesn't include Zeros 

### ISSUE THREAD

**Issue by CppMaster** [LoneGazebo/Community-Patch-DLL#4575]
_1. Mod version (i.e Date - 4/23):_
6/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I can't set to automatically purchase Zeros in Religion Screen. I have Zealotry and Air Supremacy tenet. I can set it to auto-buy Fighters and Heavy Bombers so I assume it's just overlooking. The same issue might be with Guerrilla Fighters and B17 Bombers as they are also unlocked via tenets.

_4. Steps to reproduce (optional):_
Take Zealotry belief, take Air Supremacy tenet, research Radar Technology and open Religion Screen.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Code is the same as B17.

If you can't build it in your capital, you can't set it for your auto purchase. That's the code, anyways.

**Comment by CppMaster** [comment]
But I can build it in capital. Also I can buy it with faith and gold in capital and every city with my religion. I just can't set it for auto purchase.
