### ISSUE TITLE
Culture on buildings not exposed to UI

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4577]
Policies sometimes give culture to buildings. 
This is predominantly done with Policy_BuildingClassCultureChanges
Policy_BuildingClassCultureChanges does not appear to be exposed to the UI, so any building affected by one of these policies does not show that it gets more yields
Another table exists which DOES show the yields directly on the affected building: Policy_BuildingClassYieldChanges

As an example, Fealty gives +3 food to Castles, and you can see the food when you hover over the castle in the city screen
Order has a tenet which gives +3 culture to public schools. This culture is invisible

So 2 options: 
1. Retire the Policy_BuildingClassCultureChanges, and replace it with Policy_BuildingClassYieldChanges in all cases
2. expose Policy_BuildingClassCultureChanges to UI

If Policy_BuildingClassYieldChanges already allows culture to be added, I see no reason to use it at all. The code would be more streamlined and easier for human readers if culture wasn't pinched off on its own table

Affected policies: 
INSERT INTO Policy_BuildingClassCultureChanges
	(PolicyType, BuildingClassType, CultureChange)
VALUES
	('POLICY_SOCIALIST_REALISM', 'BUILDINGCLASS_PUBLIC_SCHOOL', 3);

INSERT INTO Policy_BuildingClassCultureChanges
	(PolicyType, BuildingClassType, CultureChange)
VALUES
	('POLICY_CREATIVE_EXPRESSION', 'BUILDINGCLASS_OPERA_HOUSE', 2),
	('POLICY_CREATIVE_EXPRESSION', 'BUILDINGCLASS_MUSEUM', 2),
	('POLICY_CREATIVE_EXPRESSION', 'BUILDINGCLASS_BROADCAST_TOWER', 2),
	('POLICY_CREATIVE_EXPRESSION', 'BUILDINGCLASS_AMPHITHEATER', 2);

INSERT INTO Policy_BuildingClassCultureChanges
	(PolicyType, BuildingClassType, CultureChange)
VALUES
	('POLICY_FORTIFIED_BORDERS', 'BUILDINGCLASS_CONSTABLE', 3),
	('POLICY_FORTIFIED_BORDERS', 'BUILDINGCLASS_POLICE_STATION', 3);

INSERT INTO Policy_BuildingClassCultureChanges
	(PolicyType, BuildingClassType, CultureChange)
VALUES
	('POLICY_NAVAL_TRADITION', 'BUILDINGCLASS_BARRACKS', 2),
	('POLICY_NAVAL_TRADITION', 'BUILDINGCLASS_ARMORY', 2),
	('POLICY_NAVAL_TRADITION', 'BUILDINGCLASS_MILITARY_ACADEMY', 2);

Tradition opener (affects palace)

**Comment by TechpriestEnginseer** [comment]
You could make a pull request for this issue instead of having it be noticed. :)
