### ISSUE TITLE
Interface and Leader screen bugs

### ISSUE THREAD

**Issue by jnzs13** [LoneGazebo/Community-Patch-DLL#4578]
1. Mod version: 7/15

2. Mod list:

3. Error description:

- When I leave the mouse on a hex to know the information, nothing appears. 

- When I finish trading with another leader, I have to exit the screen by pressing "esc" and not "goodbye" (the screen does not appear anymore) 

- I can not access the discussion screen with a leader. The button is simply not clickable.

4. Steps to reproduce (optional):
Interface bug: hover over any tile.
Leader screen: Make a deal and try to finalize or click in "discuss buttom"

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2207787/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): [AutoSave_0090 BC-0625.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2207786/AutoSave_0090.BC-0625.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Sounds like a bad install.

**Comment by jnzs13** [comment]
Hmm, this has never happened to any other version using auto install, weird

**Comment by jnzs13** [comment]
Yeah, bad install confirmed. Sorry for the inconvenience, thank you.
