### ISSUE TITLE
Sacred Site Reformation Belief doesn't work

### ISSUE THREAD

**Issue by Littlefellow** [LoneGazebo/Community-Patch-DLL#4580]
**Mod version:**  
7/15 Beta

**Mod list (if using Vox Populi only, leave blank):**  

- [UI - Improved City View (Vox Populi EUI) (v 10.5)](https://forums.civfanatics.com/resources/ui-improved-city-view-vox-populi-with-eui.26679/)
- [UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)](https://forums.civfanatics.com/resources/ui-filters-in-trade-route-overview-vox-populi.26641/)
- [UI - Religion Spread (Vox Populi) (v 1.0) ](https://forums.civfanatics.com/resources/ui-religion-spread-vox-populi.26683/)
- [UI - Show XP in Military Overview (v 2.3)](https://forums.civfanatics.com/resources/ui-improved-military-overview.25924/)
- [Wonders Expanded (v 2.0)](https://forums.civfanatics.com/resources/vox-populi-wonders-expanded.26604/)
- [VP Promo Icons (v 1.1)](https://forums.civfanatics.com/threads/vp-promo-icons.633731/)

All of these mods are from infixo except *VP Promo Icons* but it only changes the aesthetic aspect of the Promotion Icons. So no conflict.

**Error description:**
Sacred Site Reformation belief does not work. Hotels and Hermitage should gain a tourism bonus (cf. screenshot belief. It's not the case.

---------------------------
 **Save:** 

[Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2215188/QuickSave.zip)

**Screenshots (optional):**

![20180720204603_1](https://user-images.githubusercontent.com/39731523/43021124-c8459650-8c62-11e8-9e23-3ce63721fca1.jpg)
![20180720204643_1](https://user-images.githubusercontent.com/39731523/43021125-c8b12ae6-8c62-11e8-900b-fc236f9bbb6c.jpg)
![20180720204705_1](https://user-images.githubusercontent.com/39731523/43021127-c8dfe2b4-8c62-11e8-8fdd-d2ad9b17cae2.jpg)

**Comment by LoneGazebo** [comment]
It doesn't show up on the building itself, only in the tourism tooltip.
