### ISSUE TITLE
City tile yields changes after load.

### ISSUE THREAD

**Issue by jarpiekar** [LoneGazebo/Community-Patch-DLL#4585]
_1. Mod version (i.e Date - 4/23):_
88 - beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
City tile yields changes after load. One food changes into 1 gold. If not saving/loading after founding new city it will have one more food and one less gold (values just after city founding)

_4. Steps to reproduce (optional):_
Start a new game, found city. Check on city screen yield of city tile. For example if it is grassland it will be 3F/1H. Save game and load. Check its yields again. It should change into 2F/1H/1G. 

It also changes AI yields - checked by demography screen, as best crop value drops by 1.

**Comment by jarpiekar** [comment]
Litte update. After city growth it changes back to 3F/1H. And again, after save load it changes to 2F/1H/1G

**Comment by MoiMagnus** [comment]
From memory, 3F1P is for fresh water (except hills) cities, and 2F1P1G is for non fresh water ones.

Is there an adjacent sea, river, lac or oasis?

**Comment by Adonis-VII** [comment]
An exiting issue for this exists here: https://github.com/LoneGazebo/Community-Patch-DLL/issues/4504

**Comment by jarpiekar** [comment]
There is river adjacent only. City on grassland.

**Comment by ilteroi** [comment]
fixed
