### ISSUE TITLE
pILLAGE VALUES

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4586]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I got 4 gold from academy yet again, there's a screenshot proving the anomaly does occur
[GEESE.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2225456/GEESE.zip)

**Comment by Edaka** [comment]
This should be fixed, I think. If somebody encounters it again, create a new ticket.
