### ISSUE TITLE
Cities gradually lose all their food in a few turns

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#4587]
_1. Mod version (i.e Date - 4/23):_
7-15
_2. Mod list (if using Vox Populi only, leave blank):_
Calypso's Colored Religion Icons v1
Gloabal Commander influence Borders v2
JFD's ExCE Resources for Vox Populi v1
Promotion FLags EUI v1.1
Quick Turns v10
RCI_V2-0_beta
Tectonic Map Script v4
UI Filters in Trade Route Overview
UI Overlay Luxuries v3
UI Promotion Tree v17
UI Religion Spread v1.0
UI Small Resource Iconsv4
UI Upgrade Tree v9
VP Promo Icons v1.1

_3. Error description:_ 
All cities lose all their food under the city. In 1710 a.d. capital got 15 food, next turn only 4, the turn after that 0 food (as can be seen in the three screenshots)! This gradually losing of food happens to all cities. This might be connected to allying the maritime city-state UR through _sphere of influence_, since it started happening after that - on the other hand - it doesn't seem to resolve it self when I repealed the resolution.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[TURN BEFORE LOSS OF FOOD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2226569/TURN.BEFORE.LOSS.OF.FOOD.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/43180544-f1785f70-8fd8-11e8-96c9-1050a515bd7d.png)
![image](https://user-images.githubusercontent.com/20144751/43180632-69c5d462-8fd9-11e8-975a-a9493b6ee95c.png)
![image](https://user-images.githubusercontent.com/20144751/43180693-bde166f6-8fd9-11e8-80c7-49620a5185a6.png)

**Comment by bigcat88** [comment]
It is an old bug, related to this:
https://github.com/LoneGazebo/Community-Patch-DLL/issues/3689

**Comment by NewFellow** [comment]
_Apparently the bug is there without using "the world congress mod"._ I'll never vote for sphere of influence on a maritime city-state again - or, wait - I will, but I'll reload if the bug popps up, and I'll check if the bug is connected to _some_ city-states and not others. This has probably happened to me before without me paying notice to it. Now I really did, since I was in need of food, and was really eager to have a few maritime city-states as allies. Luckily I won the game anyways. It could have completely ruined it if I had been in a worse position than I was (oh well, there is always the option to "reload").

**Comment by bigcat88** [comment]
Now I just know that it was not a bug of **TechpriestEnginseer** , but was a bug of a game.
In that topic I described how to replicate the issue. Don't know will it work with the current version, but if someone need I can check, again.

**Comment by LoneGazebo** [comment]
I recommend reporting this to techpriest in his thread.

**Comment by TechpriestEnginseer** [comment]
The issue is that the food city-states are not in the allied status when a sphere of influence is established. The other types of the city-states are unaffected as the game constantly updates these yields while for performance sake updates the tile yields at certain gameevents. That's why you are losing food.

**Comment by bigcat88** [comment]
So can someone fix this issue? I can generate a save with clear vox populi with this bug if needed.
