### ISSUE TITLE
Ranged unit cannot target valid hexes

### ISSUE THREAD

**Issue by dajtxx** [LoneGazebo/Community-Patch-DLL#4588]
_1. Mod version (i.e Date - 4/23):_

May 20th (3.5.20.3)​

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

My ranged and siege units cannot target the hexes I think they should be able to. This has happened in at least the last two games.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![rangedlos](https://user-images.githubusercontent.com/7575182/43181574-49f07064-9021-11e8-8277-5de1aaa00a12.jpg)

**Comment by ilteroi** [comment]
well that's certainly strange. first time anybody reported that too.

is it reproducable for you? for a specific unit? or does it depend on the plot somehow?

**Comment by dajtxx** [comment]
It has happened in at least my last two games, and I saw it with catapults and archers. Can't remember if skirmishers did it.

**Comment by ilteroi** [comment]
that's not a lot to go on ... anyone else has seen this?
