### ISSUE TITLE
How do I add a custom mod option for my mod?

### ISSUE THREAD

**Issue by iskaandismet** [LoneGazebo/Community-Patch-DLL#4589]
Okay, So I'm getting around to adding my ideology functions to the CP, and all of the edits in the CP DLL are marked with a #if defined(MOD_etc) #endif, which I suppose prevents code from firing when a mod isn't loaded. So I guess I have to add these blocks around my own code to prevent it from firing when my mod isn't loaded. But where how do I set my mod as defined, and how do I do it? < CustomModOptions > seems to be the place to do it, do I just add a corresponding setting to the table from my own mod? I.E. block my dll code with #if defined(MOD_ISKA) #endif and and an xml entry Class="2" Name="ISKA_MOD" Value="1" DbUpdates="1"?

**Comment by LoneGazebo** [comment]
if you right click any of the MOD_BALANCE_ items and go to reference, you'll see where you add it (custommods.h and custommods.cpp) - add all the required references and add one to CustomModOptions.xml in the CP. You then need to enable it with 1 in an SQL statement.

**Comment by iskaandismet** [comment]
IT WORKS! https://imgur.com/a/NcA56oY Hallelujah!
