### ISSUE TITLE
Church and/or Temple decrease my religion pressure where my religion is in majority

### ISSUE THREAD

**Issue by StevenV205** [LoneGazebo/Community-Patch-DLL#4590]
_1. Mod version (i.e Date - 4/23):_

**7-15**

_2. Mod list (if using Vox Populi only, leave blank):_

**Civ Names by Policies (v 8)\
Global Warming (v 7)\
InfoAddict (v 22)\
Quick Turns (v 10)\
Terra Incognita (v 1)\**

_3. Error description:_ 

In a city where my founded religion is in majority, buying church and building temple in the same turn decreased!!! my religion pressure. Before the building my religion has +36 pressure while the competitor has +102. After the buildings my pressure was only +27 and the competitor +82

_4. Steps to reproduce (optional):_

Sell temple and/or buy church to see the effect

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Maria Theresa_0177 AD-1170.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2229402/Maria.Theresa_0177.AD-1170.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by StevenV205** [comment]
Please use this save. You have enough faith to buy a church or cathedral and see the changes. Thx.

[Maria Theresa_0175 AD-1150.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2230417/Maria.Theresa_0175.AD-1150.zip)

**Comment by ilteroi** [comment]
well, that's not impossible - the pressure also depends on local faith yield - a city with a lot of "indigenous" faith is harder to influence from outside. 

the pressure modifier from the temple only affects other cities, not the one where it's built.
