### ISSUE TITLE
How to upload my code to github

### ISSUE THREAD

**Issue by iskaandismet** [LoneGazebo/Community-Patch-DLL#4591]
Accidentally closed last issue. It works! https://imgur.com/a/NcA56oY

How do I upload my files? I chose the four and went through some github screens and ended up here https://github.com/iskaandismet/Community-Patch-DLL/pull/1 with a lot of green "you're goods", but it doesn't seem to be showing up on the main "Pull Requests" tab

Hope to get feedback from you guys on my mod soon, as it's now compatible with the civ5 holy grail of mods (:

**Comment by iskaandismet** [comment]
Accidentally left out a couple of files. All 6 are here: https://github.com/iskaandismet/Community-Patch-DLL/commit/9374911e68d72b780ea82a3018308e4dff3f2bc2

amidoingthisrite? (I know I'm not, how am I supposed to do this right)

**Comment by LoneGazebo** [comment]
Well, if you forked the master branch via github, you need to push your changes to your fork, and then make a pull request on the master branch. I know it's a lot of random lingo, but that's what it takes.

**Comment by iskaandismet** [comment]
Okay, from LoneGazebo/Community-Patch-DLL I hit Fork, top right, which takes me to iskaandismet/Community-Patch-DLL. I hit Upload Files, to the left of Clone or Download. From there I drag the folder of my files into the thingamajig and hit commit. This takes me to my fork, where https://github.com/iskaandismet/Community-Patch-DLL/commit/d7cc4fb9039a610adae2e5d9953986c30ce0cfb2 is a link at the top. From there I hit New Pull request and follow the dialog to make it to https://github.com/LoneGazebo/Community-Patch-DLL/pull/4593 

Is this it?

**Comment by LoneGazebo** [comment]
getting closer - the 6 'cp roh dll' shouldn't be in there - you should be editing the files _within_ the existing fork, not adding new versions of the same files.

**Comment by iskaandismet** [comment]
Thank you so much supermerill!! I really appreciate it! This is exactly what's needed for idiots like me! I suggest that you add that to the README.md if you have the authority, it would really help to document the process for newbies. I'll get around to this later today if I have the time

**Comment by supermerill** [comment]
On https://github.com/, the first big button is the tutorial, explaining that in detailed.
No need to modify the readme.
