### ISSUE TITLE
Able to buy Great Persons with faith before Industrial as Byzantinum

### ISSUE THREAD

**Issue by Grabbl** [LoneGazebo/Community-Patch-DLL#4594]
_1. Mod version (i.e Date - 4/23):_
7-15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I am able to buy Great Persons (Prophets and the ones my policy trees allow me (currently Great Writers)) despite being in Medieval Era.
Furthermore, it would be good to know if a hotfix will come for this before the next version (I don't assume that, but just to be sure, for the challenge).

_4. Steps to reproduce (optional):_
Just bought a Great Writer. The prices and GP are shown in the list. Save attached.
[Theodora_0192 AD-1320.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2229759/Theodora_0192.AD-1320.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
That's part of her UA, yo. The only thing that is prevented is buying non-unlocked ones through the Glory of God.

**Comment by Grabbl** [comment]
Ok, sorry for that. I misunderstood the changelog and panicked :)
