### ISSUE TITLE
Capital mysteriously lost 2 food - went from growing to stagnant.

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#4599]
_1. Mod version (i.e Date - 4/23):_
7-15

_2. Mod list (if using Vox Populi only, leave blank):_
Mods:
Calypso's Colored Religion Icons v1
Gloabal Commander influence Borders v2
JFD's ExCE Resources for Vox Populi v1
Promotion FLags EUI v1.1
Quick Turns v10
Tectonic Map Script v4
UI Filters in Trade Route Overview
UI Religion Spread v1.0
UI Small Resource Iconsv4
VP Promo Icons v1.1
JFD's henry the VIII
JFD's the united states of america (roosevelt)
[BNW] LS Civ Set 17 - CBO or JFDLC compatible version (v 6)

_3. Error description:_ 
I noticed that my capital suddenly had become _stagnant_ when it was supposed to be growing (first picture). Then I found an _older save_ where the city wasn't stagnant and was still growing (second picture). So for some unknown reason the city lost 2 food.

I then tried to play to the next turn from the "non corrupted save" and the city _wouldn't_ lose it's food as it had done in the autosave from _before_. Acctually the autosave seems to have corrupted it self, because the city had _kept gathering food for quite a while before becoming stagnant_, almost ready to hit the next lvl (4). But in the corrupted autosave, it's far from turning into a size 4. So how can it corrupt itself, and if so, how come the autosave from the turn before that didn't get corrupted aswell if reloaded?

So providing a save here, can't be about providing one, before it happend, because as I said, the files seem to corrupt themselves for what ever reason, and will be showing this loss of 2 food, much earlier than it acctually happened. It didn't happen the turn after the non corrupted 3960 save (second picture) it happened _alot_ later, but all saves after 3960 will show this loss of 2 food anyways. So I'll provide one containing the missing food.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[AutoSave_0016 BC-3360.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2233124/AutoSave_0016.BC-3360.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/43279558-aa96c240-910e-11e8-922d-b1dd6fb79682.png)
![image](https://user-images.githubusercontent.com/20144751/43279593-cd897810-910e-11e8-91dc-b0d25ae171c8.png)

**Comment by LoneGazebo** [comment]
Already fixed for next version.

**Comment by NewFellow** [comment]
Thanks, does this mean that one should avoid building cities next to "fresh water" until next patch is released?

**Comment by Iamblichos** [comment]
No, because it'll update correctly when you do your turn.

**Comment by NewFellow** [comment]
ahh good thanks, I was a bit worried there.
