### ISSUE TITLE
Hall of Honor shows Ballistics as a requirement for the tourism yield

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#460]
But Ballistics is required for building it to begin with.
![8930_2015-07-24_00008](https://cloud.githubusercontent.com/assets/1131228/8885421/cf109bfc-3278-11e5-98df-ece7f3ae5521.png)

**Comment by LoneGazebo** [comment]
That's just because of how tourism is handled on buildings. Is WAD.
