### ISSUE TITLE
Gandhi Seems to Have A Nuke Flavor Lower Than 12

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#4600]
So I was reading through (2) Community Balance Overhaul/Balance Changes/AI/Flavors.sql

And I noticed that the file appears to override the vanilla AI flavors for building and using nukes based on one of several personality types: Conqueror, Coalition, Diplomat or Expansionist, which seem fairly sensible. So far so good.

And then adds certain leader-specific overrides to reflect their unique traits/units:
![96a243d75d3ff12f9fcefb8cf07754bc](https://user-images.githubusercontent.com/38794241/43295030-6177a4e2-9110-11e8-9a35-c4de1b08a966.png)

However, there _seems_ to be an **IMMENSE** problem with the current system: it gives Gandhi a flavor of 10 for Growth and Religion, but **NOT** a flavor for Nuke and Use Nuke of 12 (or at least 10).

_If_ this is not overridden elsewhere in the code, somewhere I'm not aware of (I'm not as familiar with the code, obviously), then I have a message:

I consider this an outrage, and antithetical to the entire franchise of Civilization. The players of Vox Populi deserve better than this, Gazebo! When Gandhi is angry, he MUST flood our lands and cities with radiation. That has been the law of Civilization since time immemorial, and VP shouldn't break this time-honored tradition.

For the sake of VP and to the glory of Sid Meier himself, _please_, I beg it of you; make Gandhi have no hesitation to use nuclear weapons! It's needed to channel the spirit of the game!

**Comment by LoneGazebo** [comment]
lol
