### ISSUE TITLE
Austria payed me to Embargo her

### ISSUE THREAD

**Issue by Archangel1117** [LoneGazebo/Community-Patch-DLL#4601]
Austria sent me a trade deal that offered 39 gold a turn in exchange for voting to Embargo Austria in the world congress. I don't have a screenshot and the only other mod I use with VP is the Civ name by policy and IGE.

**Comment by TechpriestEnginseer** [comment]
Because they know your vote in other resolutions might be more deadly than a resolution to embargo themselves because they know it won't pass.

*tap head with finger*

**Comment by HeathcliffWarriors** [comment]
And that's worth 39 GPT?

It's not impossible, but may want to check that it's indeed the case. Deal AI regarding WC was changed in the 7-15 version.

**Comment by LoneGazebo** [comment]
They make you an offer based on what they think you might be inclined to do. The AI uses these votes to estimate what the other players will do.
