### ISSUE TITLE
Some things not showing up 

### ISSUE THREAD

**Issue by Taposton** [LoneGazebo/Community-Patch-DLL#4604]
_1. Mod version is the most up to date downloaded on the 27

_3. Error description:_ 
There are almost no luxury/strategic/bonus resources and no city stats i can find....i have only played to classical is this normal? Do city states spawn in?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Sounds like a bad install.

**Comment by Vyyt02** [comment]
This is typically happening if your Civ5 is not up to date. The latest version is .279. (you can see it under the main menu when you launch the game). Update your Civ5 from Steam
