### ISSUE TITLE
does council of elders work as expected?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4608]
i have 3 cities with my religion (buddhism with CoE). shouldn't i be getting 90 science/hammers for converting my 4th city?

![image](https://user-images.githubusercontent.com/1358966/43423527-fb796eec-944c-11e8-9e51-8c12a69409fb.png)

**Comment by JanSobus** [comment]
The scaling has been changed a patch or 2 ago. IIRC it goes 30 per age flat + some function of city number which increases pretty slowly (you would get sth like 66 for 5th city)

**Comment by LoneGazebo** [comment]
I'll fix the text.
