### ISSUE TITLE
Stolen workers no longer have the penalty

### ISSUE THREAD

**Issue by jitozippiexcom** [LoneGazebo/Community-Patch-DLL#4609]
1. Mod version:
7/15.

2. Mod list:
No additional mods.

3. Error description:
When a worker is stolen from an enemy civilisation or a city state, that worker does not have the promotion (can't recall the name) that temporarily decreases its efficiency.

**Comment by LoneGazebo** [comment]
If it was formerly your worker, it won't.

**Comment by jitozippiexcom** [comment]
I do realise that the penalty does not apply to former workers. I was referring to workers that have not been previously owned by the player's civilisation. I doubt that this is related to a corrupted install on my part, but it would be great if somebody else tested and confirmed or debunked this issue.
