### ISSUE TITLE
Incorrect lake hex yields 

### ISSUE THREAD

**Issue by Udutont** [LoneGazebo/Community-Patch-DLL#4612]
_1. Mod version 7-15

_2. Mod list: remove ghost roads v2, commander influence borders v2

_3. Error description: UI shows that lake hexes produce 3 food + 1 hammer (ancient era) but the hexes only provide 2 food according to city screen overview ( which shows total food and hammers). 
[lake-error.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2256222/lake-error.zip)
 See the attached screenshots

**Comment by ilteroi** [comment]
already fixed for next release
