### ISSUE TITLE
Problem with (no) Air and ground interceptions

### ISSUE THREAD

**Issue by SOEBxxxx** [LoneGazebo/Community-Patch-DLL#4619]
_1. Mod version (i.e Date - 4/23):_
[Vox Populi (5-20-3)]:
(1) Community patch (v.88) (5-20)
(2) CBO (v.13) (5-20)
(3) CSDM for CBP (v.27) (9-27)
(4) C4DF – CBP (v.11) (9-27)
(5) ML – CBO Edition (5-14b) (v. 155) (6-14)
(6a) CBO – Compatibility Files (EUI) (v.1) (5-20) 
and
[InfoAddict (v.22)]

_2. Mod list (if using Vox Populi only, leave blank):_
[Vox Populi (5-20-3)]:
(1) Community patch (v.88) (5-20)
(2) CBO (v.13) (5-20)
(3) CSDM for CBP (v.27) (9-27)
(4) C4DF – CBP (v.11) (9-27)
(5) ML – CBO Edition (5-14b) (v. 155) (6-14)
(6a) CBO – Compatibility Files (EUI) (v.1) (5-20) 
and
[InfoAddict (v.22)]

_3. Error description:_ 

>>
Problem with (no) Air and ground interceptions:
Was playing first with additional Mods; And noticed that my interceptors and/or my anti-air guns didn't engage enemy airplane when they where attacking my units and cities! This was frustrating because I had played for over 650 turns, and that the intercept mechanic is critical in the endgame.

Yesterday I only run the mods stated above, in an attempt to reproduce. I deleted all cache files first (\Documents\My Games\Sid Meier's Civilization 5\cache). I started a small game, starting in the information era. 

So, if you run the save file 'No Air or Ground Intercept'. During the next turn Portugal will send several 'heavy bombers' to my capital 'Marrakes'. In my capital there is a 'Jet Fighter' stationed on intercept. Additionally there is a Mobile SAM unit in the city. Portugal successfully performs bomb-runs without any interceptions! 

I really like the mod patch you created!    
<<

_4. Steps to reproduce (optional):_
Only try the next turn! During the next turn Portugal will send several 'heavy bombers' to my capital 'Marrakes'. In my capital there is a 'Jet Fighter' stationed on intercept. Additionally there is a Mobile SAM unit in the city. Portugal successfully performs bomb-runs without any interceptions!   

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

[No Air or Ground Intercept.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2265812/No.Air.or.Ground.Intercept.zip)

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![no air or ground intercept](https://user-images.githubusercontent.com/42121103/43769575-5b96c78c-9a3a-11e8-8cfb-43fe55f7e70b.jpg)

**Comment by bigcat88** [comment]
Too old version, it is already reported as fixed in July version.

**Comment by SOEBxxxx** [comment]
Before starting a new game I did install the latest: 
“Newest Version: 
May 20th (3.5.20.3)​“

@bigcat88: do you suggest I download the beta version instead?

**Comment by ProCatGamer** [comment]
I too am having this same problem both on the May 20th edition and on the new 8/6 bata version...

**Comment by LoneGazebo** [comment]
Tested it last night and it works fine.

**Comment by SOEBxxxx** [comment]
I’m playing a game now with the new patch... I have to see if it works.

I will close this for the moment.
