### ISSUE TITLE
God of Wisdom

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4622]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Something's weird.. I'm playing on Epic, and someone founded a religion on turn 56. It's Ethiopia according to the logs, but that's impossible. It's like it's giving him the full 25 Faith which is the cap... Maybe even per city.

**Comment by Enrico-Swagolo** [comment]
He has 33 Faith in ONE city according to economicmonitorlog

**Comment by TechpriestEnginseer** [comment]
There's no log to accord and contrast with. :)
