### ISSUE TITLE
Cities without resource can build stone works

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#4624]
Mod version: 8-6 

Bug: My capitol has stone and marble, and my other cities **without any of the required resources can build a stone works.**

![image](https://user-images.githubusercontent.com/8049731/43833533-fbd0a4d4-9b02-11e8-825f-2efcb385ea8a.png)

**Comment by bigcat88** [comment]
Amber allow you to do that.
