### ISSUE TITLE
CTD after loading saved game, clicking next turn

### ISSUE THREAD

**Issue by bompus** [LoneGazebo/Community-Patch-DLL#4626]
_1. Mod version (i.e Date - 4/23):_
8-6-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Crash to desktop

_4. Steps to reproduce (optional):_
After loading a saved game, when I click Next Turn, I am getting a crash to desktop. I've also tried from an autosave at the beginning of the same turn, same result. Autosave on previous turn, same result. Definitely seems to be a loaded game issue.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2270643/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Maria Theresa_0141 AD-1510.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2270609/Maria.Theresa_0141.AD-1510.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2270631/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by BorussiaVox** [comment]
I had this CTD when I installed the hotfix and loaded a 8-6 save.
8-6-1 is obviously NOT savegame compatible.

**Comment by bompus** [comment]
I don't recall installing 8-6, only 8-6-1. It works fine until I end turn, then crash.

**Comment by bompus** [comment]
I started a new game, save on first turn, exit to main menu, load. No crash when ending turn. Tried the same on the following turn, no crash. So I'm not sure what's up with my save game I posted, but hopefully you can figure out what caused it.

**Comment by LoneGazebo** [comment]
8-6-1 is most certainly savegame compatible.

**Comment by Just-Harry** [comment]
I am experiencing the same issue on a saved game. Started on 8-6-1, loading turn 245 and clicking next-turn will begin processing the first AI turn, and will then crash to desktop. The same happens with all other turns from the same game.

This started happening when I attempted to load a previous turn whilst in-game, the game crashed to desktop during the loading. Then when I loaded in after starting the game again, it started crashing when beginning a new turn.

---

Here are my logs and whatnot if it helps in debugging:

[Logs](https://github.com/LoneGazebo/Community-Patch-DLL/files/2272508/Logs-fd66255e-6b0e-4157-a099-772be3bbadc7.zip)
[CvMiniDump](https://github.com/LoneGazebo/Community-Patch-DLL/files/2272510/CvMiniDump-fd66255e-6b0e-4157-a099-772be3bbadc7.zip)
[Saves](https://github.com/LoneGazebo/Community-Patch-DLL/files/2272513/Saves-fd66255e-6b0e-4157-a099-772be3bbadc7.zip)
[Save-affecting mods](https://my.mixtape.moe/ochbay.zip)

**Comment by XplosiveLun** [comment]
Have the same problem with 8-6-2.

Mods:
Historical Religions Edit (BNW or GK) (v 45)
JFDLC (07) - JFD's Cultural Diversity (Core) (v 16)
JFDLC (07a) - JFD's Cultural Diversity (Soundtrack)
Promotion Flags EUI (v 1.1)
Unit Path Viewer (v 10)

Here's my logs and save
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2274434/Logs.zip)
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2274436/QuickSave.zip)

**Comment by Viralvoid** [comment]
Have the same problem with 8-6-2 (reuploaded).
I started a new game with that version, and the CTD occurs everytime I load the savefile.

[auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2278146/auto.zip)

**Comment by Killtech80** [comment]
The same problem here.  CTD on the next turn after loading save game file.
Version 8.6.2.
Mods:
-Vox Populi no EUI
-InGame Editor v39
-Info addict v22
-Improved air reacon
-faster aircraft animation
-Units - cheap workboats
-Units - Mech Infantry
-Units - No Mech

Playing with these mods for a year, never had CTD.
the strange thing: I had CTD on my first 8-6-2 game two days ago. Then I reinstalled and started new game. Yesterday I save the game before exiting (Turn 130) and tried to reload it right after and it worked (went to turn 131). Today I loaded the same save game file, but the I got CTD right after pressing the ´Next turn´ button. the same happens now with auto saves.
Maybe a cache issue?

**Comment by Edaka** [comment]
@LoneGazebo Not trying to push or anything, but is there any chance we could see a (somewhat) hot fix? It seems that a good number of people, me included, are having this issue, and it seems to be gamebreaking. At least I couldn't find any workaround to salvage my current game, which I'd really like to finish.

**Comment by LoneGazebo** [comment]
@Edaka it's known, but i'm not in a position to work on it at the moment.

**Comment by ilteroi** [comment]
try this build. it should fix the crash.

also contains some changes to defensive behavior for AI units, so please post pictures if you notice obvious errors (eg bad positioning or too timid)

[CvGameCore_Expansion2_20180818.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2299333/CvGameCore_Expansion2_20180818.zip)

**Comment by Edaka** [comment]
What did we do to deserve you, ilteroi? :) Very much appreciated, it isn't crashing where it used to now. I'll be on the lookout for any errors you mentioned.

**Comment by LoneGazebo** [comment]
Hey. Thanks ilteroi. Yeah I’m busy this day but will release a formal hotfix soon.

**Comment by ilteroi** [comment]
no rush ... i want to get feedback on my combat changes :)

anyway i have some other small fixes lined up, will push later.

**Comment by bigcat88** [comment]
What else I need to install ? Cause with this DLL my civ crash during start menu load...

**Comment by NewFellow** [comment]
WHAT! I was about to abandon my "CTD game on next turn", but with this fix, it started working again!!! Thanks alot!

**Comment by Edaka** [comment]
@bigcat88 make sure you place it in the right directory: Documents\My Games\Sid Meier's Civilization 5\MODS\Community Patch (1),
it should look like this on Windows 10.
![image](https://user-images.githubusercontent.com/12978597/44304163-db844e80-a35c-11e8-8475-5b001d38ada2.png)

You could delete the old one first and then place the new one there, just to be sure.
