### ISSUE TITLE
Bran the Sleeping Guardian gives no ranged combat buff

### ISSUE THREAD

**Issue by LordGoogle** [LoneGazebo/Community-Patch-DLL#4628]
As per title. Pantheon reads as +100% Combat strength. Testing Archer vs Archer in PVP shows that Ghandi's basic Archers with 0 combat buffs (including from Faith or Policies) do the same damage as Boudica's.

**Comment by LoneGazebo** [comment]
From city ranged strikes, not all ranged strikes.
