### ISSUE TITLE
Pioneer Cost

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#463]
On Standard Speed:

Settlers cost 106 Hammers

Pioneers cost 720 Hammers

Colonists cost 600 Hammers

Was this intended?

**Comment by AnastaseAlex** [comment]
Also the selection of buildings the settler upgrades give seem a bit random: why would the new city not have a basic wall???

**Comment by Radost** [comment]
@AnastaseAlex 
To prevent spamming cities right under the enemy nose.
I have PTSD from communitas, when the freshly spawned cities had ~50 strength and AI was shoving them at the every inch of a map.

**Comment by LoneGazebo** [comment]
No, it isn't intended. I'll address it later.
