### ISSUE TITLE
AI beats me to Great Lighthouse and notification is stuck until reload

### ISSUE THREAD

**Issue by Albertolona** [LoneGazebo/Community-Patch-DLL#4630]
_1. Mod version (i.e Date - 4/23):_

VP 8-6-2
_2. Mod list (if using Vox Populi only, leave blank):_

Tectonic map script
_3. Error description:_ 
notification is bugged

_4. Steps to reproduce (optional):_
should occur on the next turn

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Elizabb17.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2275122/Elizabb17.zip)
[Elizabb17.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2275128/Elizabb17.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
logs?

**Comment by Mzimoxs** [comment]
This is the same issue as #4572.

**Comment by LoneGazebo** [comment]
Can’t help any of you without logs.

**Comment by Albertolona** [comment]
Forgot to enable logging after reinstall.

Do you want the logs anyway?

**Comment by Albertolona** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2281278/Logs.zip)

**Comment by TechpriestEnginseer** [comment]
Has nothing of value since the log clears after every restart of the client. We need the logs when the notification occurs.

**Comment by Albertolona** [comment]
So why does Gazebo need the logs?

The notification is due to appear in a turn or two.

**Comment by TechpriestEnginseer** [comment]
Because the bug here is a UI bug not a DLL bug. It's easier to find out when the bug appears in the DLL than in the UI since everyone's DLL should be exactly the same. I can't seem to replicate the problem at all which is why we need you to open up your save, replicate the bug, and send us those logs.

**Comment by Albertolona** [comment]
[Elizabb17PostBug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2281303/Elizabb17PostBug.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2281304/Logs.zip)

Here

**Comment by LoneGazebo** [comment]
C:\Users\user\Documents\My Games\Sid Meier's Civilization 5\MODS\(6b) Community Balance Overhaul - Compatibility Files (No-EUI)\LUA\NotificationPanel.lua:307: attempt to index field '?' (a nil value)

@TechpriestEnginseer I'm out today, any chance you could look at what's not being indexed properly in the no-EUI lua?

**Comment by TechpriestEnginseer** [comment]
@Albertolona , I'll need your C:\Users\user\Documents\My Games\Sid Meier's Civilization 5\cache\Civ5DebugDatabase.db

Don't worry you don't have to reload the bug, if you haven't played Civ 5 after this. This debug database should give what I need. If you have played another Civ 5 after the bug, you can upload another one after you activate all of the mods again and exiting out immediately (after all the mods are loaded).

**Comment by TechpriestEnginseer** [comment]
It's hard to replicate since sometimes it happens and sometimes it doesn't.

**Comment by Mzimoxs** [comment]
Considering it happens every time someone beats me to a wonder, I tend to disagree. If there's anything I can do to help, please just say it.

**Comment by TechpriestEnginseer** [comment]
Do you happen to have a slow computer? Some computers who aren't optimally performing for Civ 5 may hamper UI performances.. as such in this case when I noticed that if my computer isn't performing at its best, the bug shows up more often.

**Comment by Mzimoxs** [comment]
Nah, I'm way over the recommended specs.

**Comment by Mzimoxs** [comment]
Of course not, you've asked that before...

As I understand it, this notification is supposed to provide the information "City x can no longer work on wonder y, the lost production is converted to z culture". (Because this information is missing since those erronous notifications popped up.) If you cannot fix it, what about removing it and putting this line back to the top notifications. You know, where combat result and other stuff is.

**Comment by Albertolona** [comment]
@TechpriestEnginseer I don't have a slow pc and this instance of the bug is 100% reproducable although I have been beaten to other wonders and not seen it.

@LoneGazebo Definitely have all dlc.

@Mzimoxs It seems the bug is in indexing the picture of the wonder hence the black circle. Have you used either EUI or wonder race mod in your current install and since stopped using it?

**Comment by TechpriestEnginseer** [comment]
I have a feeling this is an old vanilla bug that we left unaddressed because it wasn't that huge of a concern(but now we're running out of concerned bugs now)... I'll have to investigate into Civ 5's history of bugs then.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer it's possible that this is a missing art asset bug. If a wonder does not have the required resolutions for all of its states, it can bug out the notification panel.

From the SDK:

Each icon atlas is partitioned by the individual size of the icon itself. 
Various icon types have their own unique set of atlases and sizes that they use.  

Here are some example sizes:

Promotions		256, 64, 45, 32
Buildings		256, 128, 64, 45
Citizens		256, 128, 64, 45, 32
Civ Symbols		256, 128, 80, 64, 45, 32
Difficulties		128, 64, 32
GameSpeeds		128, 64, 32
Leaders			256, 128, 64
Natural Wonders		256, 128, 80, 64, 45
Policies		256, 64
Resources		256, 80, 64, 45
Technologies		256, 214, 128, 80, 64, 45
Terrain			256, 64
Unit Actions		64, 45
Units			256, 128, 80, 64, 45
Unit Flags		32
World Sizes		128, 64, 32
World Types		128, 64, 32
