### ISSUE TITLE
Conscription gone very wrong

### ISSUE THREAD

**Issue by BorussiaVox** [LoneGazebo/Community-Patch-DLL#4631]
_1. Mod version (i.e Date - 4/23):_
8-6-2

_2. Mod list (if using Vox Populi only, leave blank):_
InfoAddict (v 22)
Really Advanced Setup (v 15)

_3. Error description:_ 
As you can see in the screenshot my city Ohrid without any water tile conscripted a caravel into a one tile lake five tiles away next to the city of Busan. 
Imo cities that can not produce naval units should not be able to conscript naval units. And conscripted naval units should not be placed in lakes.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![8930_20180809194423_1](https://user-images.githubusercontent.com/31174386/43917158-021c9404-9bff-11e8-8c31-7b9fd514c592.png)

**Comment by Enrico-Swagolo** [comment]
I saw my land-locked Amsterdam conscript a Dromon, but thankfully it was put inside a coast so no biggie...

**Comment by LoneGazebo** [comment]
There's a check against putting boats in lakes, must be a map quirk.

**Comment by bigcat88** [comment]
![inked20180811234319_1_li](https://user-images.githubusercontent.com/13381981/43995904-a97f7c8a-9dc0-11e8-9210-cd312c330176.jpg)

**Comment by ilteroi** [comment]
spot the problem ...

![image](https://user-images.githubusercontent.com/1358966/44312052-a1fe2280-a3f2-11e8-99c8-a55b42129198.png)

**Comment by pineappledan** [comment]
I didn't think to take a picture, but I got a penteconter in a 1-tile lake next to my capital as well
