### ISSUE TITLE
Barbie axemen don't attack

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4633]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ basically the axe throwers don't throw their axes no matter what. They fortify when faced with danger or run away, they'll try to reach a city (if no unit is seen by them), but they won't attack unless they're placed in a camp, in which case they might.

**Comment by LoneGazebo** [comment]
@ilteroi is the tactica man.

**Comment by ilteroi** [comment]
yeah i can imagine why. will fix next week

**Comment by LoneGazebo** [comment]
@ilteroi want me to revert your last commit in master?

**Comment by ilteroi** [comment]
i think it's the previous change in fact. check ExecuteAttackWithUnits. there's a condition to skip the attack if it's a single unit attacking etc. maybe add a non-barb check there.

**Comment by LoneGazebo** [comment]
```
//careful with single units walking into traps
		if (vUnits.size() == 1 && !m_pPlayer->isBarbarian())
```

**Comment by LoneGazebo** [comment]
like this?

**Comment by ilteroi** [comment]
looking good

**Comment by LoneGazebo** [comment]
yay I did it, master of the tactical AI!
