### ISSUE TITLE
UnitPromotions_GarrisonYield

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4639]
Can we have this apply to forts and citadels as well or is that not feasible? They are technically "garrisons"

**Comment by LoneGazebo** [comment]
They’re not city garrisons, and theres no code to garrison a non city.

**Comment by TechpriestEnginseer** [comment]
Fair enough. I'd assume the garrison code would be similar since you can't both exit out when you attack from a fort/city.

How about UnitPlotExperience in the UnitPromotions, but it's able to grant non-localized yields(like culture, great admiral points and the likes) when the person is on it.
