### ISSUE TITLE
Scientist specialist tooltip not showing culture

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#464]
![2015-07-25_00001](https://cloud.githubusercontent.com/assets/11132095/8888397/3d7c8234-3271-11e5-9a44-283c12db1358.jpg)

Pretty self-explanatory, I think. Giving 2 culture but not showing up on the tooltip.

**Comment by LoneGazebo** [comment]
Thanks. Already reported. I'll close this one for now.
