### ISSUE TITLE
Choose Science Notification Unresponsive

### ISSUE THREAD

**Issue by Albertolona** [LoneGazebo/Community-Patch-DLL#4642]
_1. Mod version (i.e Date - 4/23):_

VP 8-6-2
_2. Mod list (if using Vox Populi only, leave blank):_

Tectonic map script
_3. Error description:_ 

_4. Steps to reproduce (optional):_

Next Turn
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2288486/Logs.zip)
[Elizabb21.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2288487/Elizabb21.zip)
[Elizabb21ScBUG.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2288489/Elizabb21ScBUG.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Hmmm no error in the lua logs.. oh it's the last policy of Authority tree. Just move a soldier back and fourth and you should be fine.

**Comment by Albertolona** [comment]
It was always fine because I could still access the science tree. Nothing game breaking.

I was just reporting the bug. That is what you want right?

**Comment by TechpriestEnginseer** [comment]
Yeah then that's fine. It's a weird glitch with the Honor policy that constantly appears and disappears. I won't really know until I get into reworking the UI for EUI. Thanks for reporting!
