### ISSUE TITLE
Disable disbanding troops

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4644]
Is there a way for a promotion or some lua to prevent disbanding of a unit? I'm looking to hire "heroes" for an event that should never die nor are they deleted.

**Comment by ilteroi** [comment]
well there is a function CvUnit::canScrap() which could be modified to check for eg a promotion.

**Comment by TechpriestEnginseer** [comment]
Can it be in lieu of a gameevent lua then?

**Comment by LoneGazebo** [comment]
Can what be?

**Comment by TechpriestEnginseer** [comment]
Turn the function CvUnit::canScrap() as a GameEvent lua where it checks the iUnit for anything.

**Comment by TechpriestEnginseer** [comment]
Any progress on this?

**Comment by LoneGazebo** [comment]
Adding two lua hooks for you:

#define GAMEEVENT_PlayerCanDisband				"PlayerCanDisband",				"i"
#define GAMEEVENT_PlayerCanDisbandUnit			"PlayerCanDisbandUnit",			"ii"

PlayerCanDisband fires in the Player::DoDeficit() function, and takes ePlayer as it's variable
PlayerCanDisbandUnit fires in the Unit:canScrap() function, and takes ePlayer and UnitID as it's variables

**Comment by TechpriestEnginseer** [comment]
Awesome!
