### ISSUE TITLE
crash in deal AI

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4647]
so i have a crash here, related to the fact that GC.getGame().GetGameDeals().GetTempDeal() returns an "empty" CvDeal with NO_PLAYERs as participants.

call stack here:

![image](https://user-images.githubusercontent.com/1358966/44156392-0cab08be-a0b0-11e8-9ce4-b9c7e83bc90c.png)

i guess i can put safety checks inside CvDeal::IsPossibleToTradeItem() but is eFromPlayer==NO_PLAYER or eToPlayer==NO_PLAYER a valid state for CvDeal? have there been any recent changes here causing this behavior?

note that this "temp deal" thing is horrible design anyway and might cause all sorts of serialization / synchronization issues. ideally it should be removed completely.

**Comment by LoneGazebo** [comment]
Temp deals are a bad design, but the whole DealAI leans on it. Can’t imagine the time it would take to undo all of it. 

 Strange I haven’t seen a crash there- was it a loaded save? That ‘PlayerDemandAttractive’ code is mine but I’ve run many games on it with no crashing...

**Comment by LoneGazebo** [comment]
A null or empty check makes sense I guess.

**Comment by ilteroi** [comment]
yeah it happened after loading a save and ending the turn. the workaround helps ... but i have a really bad feeling about this temp deal thing now that i learned about it

**Comment by LoneGazebo** [comment]
It’s all over the DiploAi and DealAI.

**Comment by LoneGazebo** [comment]
I wonder if we need to explicitly clear the temp deal cache every turn at the start, just to keep unsuccessful deals out.
