### ISSUE TITLE
CTD for a game. Was sent here from the forum

### ISSUE THREAD

**Issue by CrazyGerman** [LoneGazebo/Community-Patch-DLL#4648]
_1. Mod version (i.e Date - 4/23):_

8/6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I click next turn and the game crashes.
I tried loading saves from earlier turns and they didn't work either.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
I don't have logging enabled

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
In the Zip
[Files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2298076/Files.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
In the Zip above
4. Screenshots (optional):

**Comment by Edaka** [comment]
See #4626 for the fix.
