### ISSUE TITLE
When city has no religion - it can't buy Great People from policy trees

### ISSUE THREAD

**Issue by InapropriateUsername** [LoneGazebo/Community-Patch-DLL#4649]
_1. Mod version (i.e Date - 4/23):_
8-6-2

_2. Mod list (if using Vox Populi only, leave blank):_
![image](https://user-images.githubusercontent.com/19764746/44289740-3c892500-a27e-11e8-9497-36fcb4a24cce.png)

_3. Error description:_ 
I don't think many people face this, so it might as well be left as is, 
However in my game my religion was outpressured by another one and since it was OCC i could not get it back. 
After that i was not able to buy Engineers/Musicians/Merchants provided by Tradition/Artistry/Industry that i had. I think it is kinda wrong cause they are  provided by policy trees, not religion...

![image](https://user-images.githubusercontent.com/19764746/44290020-7575c980-a27f-11e8-9260-6be205230dcc.png)

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
Yeah, you have to have at least some kind of faith to use faith.
