### ISSUE TITLE
Staggered dual DoW

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#465]
Don't know if this is even a bug or just AI behavior, but I agreed to a dual DoW with Rome in 10 turns. About 5 turns later he declared war on Carthage by himself, but still asked me to join him at the end of the 10 turns. I'm not sure I've seen this before and don't know if it's normal AI behavior, so reporting in case.

![2015-07-25_00002](https://cloud.githubusercontent.com/assets/11132095/8888574/c1985726-3278-11e5-8839-66168931aa17.jpg)
![2015-07-25_00003](https://cloud.githubusercontent.com/assets/11132095/8888575/c1987eea-3278-11e5-94d4-3e4af9eb04fe.jpg)

**Comment by LoneGazebo** [comment]
It is normal, yeah. Sometimes if the AI waited for too long once it was 'in position' it would simply abort the army movement but still DOW with the player. This way the AI goes to war when it is ready with the guarantee of a second player with them.
