### ISSUE TITLE
Safe missionary acts if  he's not and won't spread religion.

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#4651]
_1. Mod version (i.e Date - 4/23):_
8-6-2

_2. Mod list (if using Vox Populi only, leave blank):_
Calypso's Colored Religion Icons v1
JFD's ExCE Resources for Vox Populi v1
VP Promo Icons v1.4
UI Filters in Trade Route Overview
_3. Error description:_ 
Greece keeps going to this neighbour of his with the intent of spreading his religion, but seeing me close by (we are at war) he takes "attrition" and moves back from where he came without spreading. The next turn he makes another try, but immedieately moves back due to me staying put with my scout, thus wasting his missionary [attrition], when he in fact COULD spread since I have to declare war on the ottomans to make a move on him (which I obviously won't). He's perfectly "safe" within their borders but still acts like he's not.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[greece won't spread religion.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2299685/greece.won.t.spread.religion.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/44299502-8cf09900-a2f7-11e8-8aa2-4b2c1a85f1b3.png)

**Comment by ilteroi** [comment]
interesting. AI should be aware whether you are allowed to enter their plot or not.
