### ISSUE TITLE
icon mismatch

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4652]
another player finished the hanging gardens, while i was building the same wonder. now there's two notifications, but the second one (conversion to culture) shows the icon for the pyramids? 

![image](https://user-images.githubusercontent.com/1358966/44299395-1f436d80-a2f5-11e8-9a69-917835cc9a35.png)

**Comment by LoneGazebo** [comment]
yeah there should be a log item in your lua.log about this.

**Comment by ilteroi** [comment]
i don't understand ... is this a known issue? anyway i don't have the logs anymore.

**Comment by LoneGazebo** [comment]
It’s a random issue some users have. Can’t pinpoit why though.
