### ISSUE TITLE
Cannot liberate a city

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#4653]
_1. Mod version (i.e Date - 4/23):_
8-19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I eliminated Indonesia from the game. Shortly afterwards, Persia captured one of the former Indonesian cities and annexed it. A few turns later I recaptured the city, and was given only the options of annex, puppet, raze and view the city, but not to liberate it (i.e. return it to Indonesia, thus resurrecting Indonesia).

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
Few version ago, a check was added to forbid liberating a city of a Civ you are at war with. (It was causing a lot of strange stuff)

My guess is that you are still considered at war with Indonesia, even though they are dead.

It might be intended to work like that, but I doubt it.

**Comment by Mzimoxs** [comment]
You cannot liberate a civ you have eliminated. It has been that way since Civ5 release and I think it should not change.
