### ISSUE TITLE
PillageBonusStrength table not working

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4654]
_1. Mod version 8/06

_3. Error description:
PillageBonusStrength Does not seem to work. I tested it on a custom civ, and it doesn't actually add any CS to the unit. 

I created a dummy promotion to test it, which should give +20% if standing on a pillaged tile. I receive the +20% from Shock I and Shock II, but none from the new promotion (the lightning bolt symbol in the unit window).

PillageBonusStrength is used for the Danish Viking promotion, so I'm guessing it does not work there either. 

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/33136027/44318735-19cd4c80-a3f5-11e8-857e-fdfce6e92f82.png)

**Comment by bigcat88** [comment]
From my current Danish game(8-6 version). 
Without pillage:
![20180820132953_1no](https://user-images.githubusercontent.com/13381981/44335563-8b50dd80-a47d-11e8-82cc-a3046eb7f44f.jpg)
Pillaged:
![20180820133026_1yes](https://user-images.githubusercontent.com/13381981/44335593-a4f22500-a47d-11e8-929b-1c28e460af3e.jpg)

Looks like all is ok. ^)
