### ISSUE TITLE
Unreachable City state asking for road

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#4656]
_1. Mod version (i.e Date - 4/23):_

8-6-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
city state surrounded by mountains requests road, I later explored around it and there is no way to reach it

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20180817204031_1](https://user-images.githubusercontent.com/13261433/44501343-90b35100-a652-11e8-965d-7af5c8a59d16.jpg)

**Comment by myles1718** [comment]
Build a tunnel

**Comment by bigcat88** [comment]
Try to capture an Inca worker ) But yea, this is a small bug...

**Comment by TechpriestEnginseer** [comment]
https://forums.civfanatics.com/threads/worker-mountaineering.630237/

Could download this mod.
