### ISSUE TITLE
Rome UA bug, buildings not retained on conquest

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#4657]
_1. Mod version (i.e Date - 4/23):_
8-6-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
missing buildings that should be there. I conquered a city with oracle but it had no temple. captured marrakech and it was missing basic buildings like monument, council...

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20180818015959_1](https://user-images.githubusercontent.com/13261433/44501465-ebe54380-a652-11e8-80fa-d7c79cbcb9d9.jpg)
![20180822212439_1](https://user-images.githubusercontent.com/13261433/44501542-47afcc80-a653-11e8-8791-971819bf5384.jpg)

**Comment by LoneGazebo** [comment]
Some buildings are never capture, those are not captured.

**Comment by TechpriestEnginseer** [comment]
Perhaps we should reword the UA because this has been a misunderstanding one too many times.
