### ISSUE TITLE
Stable production bonus missing on heavy skirmishers

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#4658]
_1. Mod version (i.e Date - 4/23):_
8-6-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
knights get the bonus but not skirmishers. intended?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20180820201228_1](https://user-images.githubusercontent.com/13261433/44501599-86de1d80-a653-11e8-8281-bc2f6ec91c5d.jpg)
![20180820201242_1](https://user-images.githubusercontent.com/13261433/44501619-a37a5580-a653-11e8-90b4-684ce22a644b.jpg)

**Comment by phantommaxwell** [comment]
The Stable does specify:  Mounted MELEE.

**Comment by Edaka** [comment]
@phantommaxwell I don't think it does, I got confused about it the other day, too.
![image](https://user-images.githubusercontent.com/12978597/44888874-ff8c4c00-acdb-11e8-8904-03ce4620fac7.png)

**Comment by LoneGazebo** [comment]
It is mounted melee only, because mounted ranged are technically _ranged_ class.
