### ISSUE TITLE
Policy/Tenet buildings not always spawning in new cities.

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#467]
I thought that this probem had been fixed, but both with freedom's hospitals and order's museums, new cities on small islands did not get these. Could it be an incompatibility with settler upgrades and tenets?

**Comment by LoneGazebo** [comment]
Shouldn't be, as they are separate functions. Is it just small islands? Also, how many cities do you have in your empire?
G

**Comment by AnastaseAlex** [comment]
On communitas map, after getting ideologies in CBP I generally settle either the small islands or a remote polar region rich in strategic resources. By that point I typically have settled 4-5 cities in ancient/classical times, 1 when I discover banking, and conquered 1-4 cities at around that time. I also might be in a war with a neighboor and be conquering also at that point, but generally I never have more than 15 cities when I settle the remote ones, and they tend not to have the free building.

Next time it happens I will keep a save for you.

**Comment by LoneGazebo** [comment]
A save would be great.

**Comment by AnastaseAlex** [comment]
I did not have that problem in the last two games where I tried to reproduce it. I will send a save if I run across that again, but we should probably close this ticket as it stands.

**Comment by LoneGazebo** [comment]
Excellent. Thanks for looking into it!
