### ISSUE TITLE
CTD on a turn when an AI is at war

### ISSUE THREAD

**Issue by Viralvoid** [LoneGazebo/Community-Patch-DLL#4675]
_1. Mod version (i.e Date - 4/23):_
8-19-1
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
"On-war CTD: When an AI is at war, I'm getting CTD, but when I declared war on that AI, or brokered someone to declare with that AI, the CTD won't occur.
Very long turn time (about 20 minutes): I fixed the issue by using IGE, an AI (Elizabeth) has too many units, and realized that some battleships were stucked at the polar region and can not move, I deleted the units, and the turn time returned to normal." from Civfanatics

On my current game, it became more frequent and can't be fixed through brokered war.
The CTD occurs the turn before the attached save file, I brokered Assyria to declare war on Russia, the CTD does not occur on that turn, on the next turn, the CTD occurs again.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2339809/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Viralvoid** [comment]
[auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2339826/auto.zip)

Reuploaded.

**Comment by InapropriateUsername** [comment]
In my current game I had lots of CTDs when being at war in the late game. But logs disabled, also i play with Modpack, so couldn't report

**Comment by Viralvoid** [comment]
I played another game without the bugfix, and the CTD doesn't occur.

**Comment by LoneGazebo** [comment]
@InapropriateUsername that's usually because of EUI. EUI can cause spikes in memory buffer use and cause CTDs.
