### ISSUE TITLE
Unlocking Ideology with poland

### ISSUE THREAD

**Issue by pzapza** [LoneGazebo/Community-Patch-DLL#4676]
_1. Mod version (i.e Date - 4/23):_
8-6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
At least in MP (not sure about SP), chosing an Ideology is only possible one turn after you complete 18 policies. The main reason this is a problem is because poland receives a free policy when you finish the 18th policy, and you cannot chose an ideology trait in that turn.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![poland](https://user-images.githubusercontent.com/38469319/44922511-cdafcf80-ad45-11e8-8d00-e52ea5f33ab3.jpg)

**Comment by bigcat88** [comment]
Yes, but for ideology Poland has another Free Policy. It's intended.

**Comment by LoneGazebo** [comment]
Clunky, but yes, this is correct - the UI only updates the option at the start of the turn.
