### ISSUE TITLE
Inquisitors restoring wrong religion

### ISSUE THREAD

**Issue by blackears** [LoneGazebo/Community-Patch-DLL#4678]
_1. Mod version (i.e Date - 4/23):_

3.7.15.0

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Created a great prophet early in the game (Soroastrianism).  Later, my religion was completely overrun by neighboring empire's religion.  Later in the game, used great prophet to restore my religion in one city.  Then bought a bunch of inquisitors.  Inquisitors display as being members of Zoroastrianism.  However, when I used them to remove heresy, Teregrinism is spread to city instead.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2342975/Logs.zip)

[Ashurbanipal_0424 AD-1828.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2342976/Ashurbanipal_0424.AD-1828.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Inquisitors do not 'restore' religion, they hit religions not affiliated with your own. In that case, they hit the other faiths, but they left Tengriism as the largest remaining faith. Only prophets spread religion _and_ reduce others.

**Comment by bigcat88** [comment]
@LoneGazebo are you sure? I always use inquisitors to restore inquisitors religion. If there were no pressure from that religion at all, then city becomes no religion.

And never seen about what topicasters says, in my games on last patch all was the same, inquisitor always cut off all religions followers except own.

**Comment by TechpriestEnginseer** [comment]
Inquisitors have a religious strength for a reason. No?

**Comment by LoneGazebo** [comment]
The pressure they have is used to calculate the power of their purge.
