### ISSUE TITLE
TEMPORARY DOWNLOAD LOCATION - COMMUNITY PATCH PROJECT

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#468]
Since Civfanatics is in the dark (the horror!), I've posted a link to the folder where I store the mods below:

https://www.dropbox.com/sh/88rkwjo3lwuj1xb/AAD6-v59xUfY-siBAlaqPAHDa?dl=0

**Comment by Radost** [comment]
Fyi communitas has all useful links placed right at the main page: https://github.com/Thalassicus/cep-bnw
And all releases: https://github.com/Thalassicus/cep-bnw/releases
So I think it's time to integrate CBP with github more.

**Comment by wileyhk2001** [comment]
this is a nightmare...

**Comment by jeffpierce** [comment]
If anyone here has the contact info of the site admins, send it to me?

I'm a DevOps engineer -- getting their site properly configured shouldn't be that difficult, assuming they're willing to spend the scratch to get the right hosting plan.
