### ISSUE TITLE
Multiplayer incredibly unstable again 

### ISSUE THREAD

**Issue by bklick** [LoneGazebo/Community-Patch-DLL#4680]
_1. Mod version (i.e Date - 4/23):_

Vox Populi 8-6, with EUI

_2. Mod list (if using Vox Populi only, leave blank):_

1. Unit Path Viewer (v 10)
2. UI - Improved City View (Vox Populi EUI) (v 10)
3. UI - Religion Spread (Vox Populi) (v 1.0)
4. UI - Filters in Trade Route Overview (Vox Populi) (v 1)
5. UI - Show XP in Military Overview (v 2)

_3. Error description:_ 

Very frequent resynchs and player drops.

_4. Steps to reproduce (optional):_

Play an internet multiplayer game with two or more players normally. Expect resynchs and disconnects on pressing "end turn."

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
duplicate to #4713
