### ISSUE TITLE
AI missionary attrition

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#4681]
Forgive my ignorance for I don't know how AI missionaries are coded at the moment. I talk from my experience, because I often see AI missionaries take attrition that I, as a player, could have avoided. Sometimes missionary attrition is unavoidable, however almost any border city can be missionary bombed without attrition with a simple condition:
- if possible, missionaries should only end turn in unfriendly territories by spreading, i.e., not running out of movement,
Examples of how that can be achieved:
- traveling on water, even if it means a longer route (no difficult terrain and water borders are often more narrow),
- ending turn on an unclaimed spot locked inside somebody's territory, even if it means a longer route. That may imply circumnavigating borders to enter from a side where this is possible (going longer distances) or not spending all movement points on any given turn (taking longer to cover distances),
- going as far into unfriendly territories as possible in one turn before spreading, even when it's possible to start spreading earlier. This can sometimes enable you to reach the next unfriendly city and spread at once, without taking attrition.

Another tip, but it gets more nuanced:
- even when you mostly want to convert unfriendly cities, always try to only use the last spread on them, use the first (and possible the second if it's not the last) on still unconverted city states/own cities. 
- this also works the other way around: even when you mostly want to convert own cities, try to use the last spread on unconverted unfriendly ones.

If anybody sees this behavior, feel free to post screenshots here, briefly explaining how AI missionaries could have moved better. I may post my own later.

**Comment by ilteroi** [comment]
there is already some logic to keep missionaries from ending their turn in non-friendly territory. in fact, i found a bug in that piece of code recently - the fix should be included in the 8-19-1 hotfix version. so please only report on that version.

i didn't have time to test the behavior thoroughly, so it's well possible that there still are problems.
