### ISSUE TITLE
Cheesy tactic: selling cities to AI

### ISSUE THREAD

**Issue by supermerill** [LoneGazebo/Community-Patch-DLL#4683]
_1. Mod version (i.e Date - 4/23):_
?

_2. Mod list (if using Vox Populi only, leave blank):_
?

_3. Error description:_ 
>I found a rather broken tactic through the use of settlers. If the AI has any open land for settling near their base, you can build with your settler and then sell it for everything they can trade.
>
> A 1 city population newly found city is worth around 40K value. I traded that one city for 150 gpt + 3 luxury resources + all their strategic resources they would trade. And I still had around 28K in net value going towards them. So not only did I completely scam the AI, but because they got such a "good" deal they gave me a massive diplomacy boost (+40).
>
>This is in Medieval era and on immortal difficulty.
>
>Anyone else do this? Its really broken especially if the AI has nearby 1 tile islands. Build and sell.

source: https://www.reddit.com/r/civvoxpopuli/comments/9cezdo/learn_this_one_easy_trick_to_sell_a_settler_for/

**Comment by ilteroi** [comment]
hmm. it's not easy to judge the (strategic) value of a city ... maybe we should simply restrict the deals so that you can only buy back your own cities. unless it's a peace deal. but the values are quite high, that's for sure.

**Comment by bigcat88** [comment]
@ilteroi then must be an exception for captured cities. value smaller for captured puppets and bigger for already annexed. 
Maybe a good topic where all can say their opinion on civfnatics will be a good idea.
But trading cities is a very interesting part of game, imho.

**Comment by bklick** [comment]
I honestly don't see the issue. The AI can make better use of cities than the player anyway, right?

**Comment by ilteroi** [comment]
i made it so that freshly founded cities can't be traded
