### ISSUE TITLE
Shaka unit promotions.

### ISSUE THREAD

**Issue by Negush** [LoneGazebo/Community-Patch-DLL#4684]
_1. Mod version (i.e Date - 4/23):_
8-19

_2. Mod list (if using Vox Populi only, leave blank):_
Using the required pack of mods for vox populi such as 42 civs, more resources. Using EUI.

_3. Error description:_ 
Playing as Shaka after first experience gain pathfinder gets every single possible promotion. After that any unit trained in city also gets all the promotions. This is without any buildings. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
Thanks,

1) Are you using the auto-installer, you are you using a DLC-modpack? For Vox Populi to be complete, you need 6 mods numbered (1), (2), (3), (4), (5) and either (6a), (6b) or (6c). Check in the folders if you have those 6 mods, and report the other mods you may have.

2) Some installed mods may cause problems, even if they are disabled (civ 5 mod manager is crap). So unsubscribe from any steam mods named "community patch" or "more luxuries", they will be duplicate with your installation and cause problems.

3) Have you a screenshot, a save file, some logs, or anything?

**Comment by Negush** [comment]
I removed the unnecessary mods and it works correct. Thank you.
