### ISSUE TITLE
Diplomatic Mission 1 EUI Bug

### ISSUE THREAD

**Issue by DoItTomorrow** [LoneGazebo/Community-Patch-DLL#4685]
_1. Mod version (i.e Date - 4/23):_
8/19-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
All diplomatic units have an indicator for 1 gold and 100 influence instead of new line and bullet point for -1 Paper

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
https://i.imgur.com/UKuyHp8.jpg

**Comment by TechpriestEnginseer** [comment]
But don't other units requiring other resources not have a bullet point? The -1 paper isn't connected to the Trade Mission. It's connected to the Unit.

**Comment by LoneGazebo** [comment]
that's not an issue - those are two separate sets of stats.
