### ISSUE TITLE
[Tooltip]Ban Luxury and breaking monopoly bonus

### ISSUE THREAD

**Issue by legenciv** [LoneGazebo/Community-Patch-DLL#4687]
_1. Mod version (i.e Date - 4/23):_
9-6

_3. Error description:_ 
The Ban Luxury proposal does not mention that it also denies the monopoly bonus of the luxury.

![banluxury](https://user-images.githubusercontent.com/19234279/45190367-00f5d100-b214-11e8-84a9-45ead6883df2.PNG)

**Comment by ricanuck** [comment]
Maybe it shouldn't? Or else, the proposal would be overpowered... probably a bug.

**Comment by LoneGazebo** [comment]
It is intentional - that's also not the updated text from the CBO. Mod conflict?

**Comment by jimmymcperson** [comment]
I also have the exact same (wrong) description.  Here are my mods.

![capture](https://user-images.githubusercontent.com/19291347/45253543-19124100-b337-11e8-90a2-961af41f37a3.PNG)
