### ISSUE TITLE
Enable Events System sentient self-aware

### ISSUE THREAD

**Issue by ricanuck** [LoneGazebo/Community-Patch-DLL#4688]
_1. Mod version (i.e Date - 4/23):_
6-9, but noticed many versions earlier

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I disable all event related checkboxes for my games, yet the first game I launch in every new version, has the "Enable Events System" checkbox enabled.

_4. Steps to reproduce (optional):_
Start a new game with a new install of latest version, disable all event-related checkboxes, and you will have "Enable Events System" re-enable itself.
I know the AI has been vastly improved, but nowhere does it say it has become sentient, self-aware and obnoxious at that.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2358605/CvGameCore_Expansion2.zip)

Clear your cache. Drop this in CP. Try and see if it still happens.

**Comment by ricanuck** [comment]
Will try at the earliest possibility, thanks.

**Comment by ricanuck** [comment]
Tried. Worked. What was it? Looked like all the "No event x" checks were disabled by default, which was not the case in all latest versions... was that it?

**Comment by LoneGazebo** [comment]
No - the issue was that I'd made a game option cache for speed optimizations, but it was caching before the game started and not updating until the _next_ game start.

**Comment by LoneGazebo** [comment]
So exactly what you were seeing.

**Comment by ricanuck** [comment]
I only yesterday realized that by just going back one step to the main menu and then entering again, you could work around it without having to start that first dummy game, but too late, you fixed it now...
