### ISSUE TITLE
Rights of Man Rationalism policy gives too much food

### ISSUE THREAD

**Issue by Zealot81** [LoneGazebo/Community-Patch-DLL#4689]
_1. Mod version (i.e Date - 4/23):_
9/6

_2. Mod list (if using Vox Populi only, leave blank):_
UI mods, Quick Turns, Wonder Race, Reseed! and Info Addict

_3. Error description:_ 
After taking Rationalism "Rights of Man" policy my Venice city gets a few thousand food/turn more than it deserves.

_4. Steps to reproduce (optional):_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2361517/Logs.zip)

I'm sorry if I do something wrong posting here, this is my first Github post and contribution to VP but I think this error is serious - it made my game unplayable.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![venice](https://user-images.githubusercontent.com/43071427/45227109-54bdf400-b2c0-11e8-9e10-53986f6ac3f7.jpg)

**Comment by LoneGazebo** [comment]
Good catch. Bagged it, tagged it, will hotfix. 🏅
