### ISSUE TITLE
Unit icons not showing up on map

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#469]
This isn't a CPP bug, but it's something that has driven me nuts and I'm not sure if it could be fixed.

Occasionally, no idea the trigger, a unit's icon does not show up on the map. It can lead to "hidden" units and surprise attacks.

![2015-07-25_00004](https://cloud.githubusercontent.com/assets/11132095/8891418/7a856cf4-32ee-11e5-8e87-49e8512132c4.jpg)

**Comment by LoneGazebo** [comment]
This is the UI engine, which we cannot, unfortunately, modify. :(

**Comment by joosegoose** [comment]
:( I had a bad feeling.
