### ISSUE TITLE
surprisingly high yields from trade route

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4691]
is this intended? turn 434 in standard speed ...

![image](https://user-images.githubusercontent.com/1358966/45238948-d6734900-b2e3-11e8-9467-eb54dca3ca28.png)

sure arabia is the tech/culture leader, but this seems a bit much? they are ahead by 14 techs and 8 policies btw

**Comment by LoneGazebo** [comment]
That’s probably right? Could step through the equation in trade classes.

**Comment by ilteroi** [comment]
it's linear scaling with tech difference / culture difference ... i'd prefer a sqrt?
