### ISSUE TITLE
Can't "discuss" with leader

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#4692]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_
9-6

_3. Error description:_ 
Going to the "discuss" option for another civ doesn't do anything, just says "go ahead"

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ricanuck** [comment]
Mine is working.

**Comment by LoneGazebo** [comment]
lua log

**Comment by HalfEmptyMug** [comment]
Reproduced in 9-6-2, specifically when a civ was stacking units along my border and the "Please move your troops" discuss option would be available. Lua log comes up with this runtime error:
`Runtime Error: *Mod Path*\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\DiscussionDialog.lua:327: bad argument #2 to 'ConvertTextKey' (Argument must be [boolean, number, or string].)`

Cross referencing with version 7-15 showed that in DiscussionDialog.lua the section "END VASSALAGE" under "Discussion Root Mode" and "Human-invoked discussion" under "BUTTON 1" were removed in the current version. Local strLeaderName was defined under the "END VASSALAGE" section, leading to this error. placing this code immediately under `if (g_iInvokedDiscussionMode == g_iModeDiscussionRoot) then` seems to fix the issue and is save game compatible:

```
if (g_iInvokedDiscussionMode == g_iModeDiscussionRoot) then

	local strLeaderName;
	if(pAIPlayer:GetNickName() ~= "" and Game:IsNetworkMultiPlayer()) then
		strLeaderName = pAIPlayer:GetNickName();
	else
		strLeaderName = pAIPlayer:GetName();
	end
```

I'm not sure if the other bits that were removed will cause any issues, but here are the 7-15, original 9-6, and modified 9-6 versions of the file with my logs:

[DiscussBug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2363408/DiscussBug.zip)

**Comment by LoneGazebo** [comment]
Ah damn. I knew I needed to fix that and forgot. I’ll fix later.

**Comment by ricanuck** [comment]
savegame compat, I hope?

**Comment by LoneGazebo** [comment]
Yeah it's just lua.
