### ISSUE TITLE
Spain "Discuss" Diplomacy Screen Not Working

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#4694]
_1. Mod version (i.e Date - 4/23):_
9/6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When I click the discuss button with Spain, I either get a box saying "Go On" with no options, or a large list of the exact same text option. I have not replicated this with any other civ except Spain so far.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Lua log?

**Comment by Stalker012345** [comment]
Here is the lua right after I saw the message. I see an error right at the bottom so that is likely the cause.

[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2363626/Lua.log)
