### ISSUE TITLE
AI Grateful for Banning Their Luxury

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#4696]
_1. Mod version (i.e Date - 4/23):_
9-6

_2. Mod list (if using Vox Populi only, leave blank):_
VP
flagpromo7
commander influence borders 1
improved city view 9
infoaddict 22
really advanced setup 15
reseed 11

_3. Error description:_ 
I propose to ban someone's Luxury and they like it.

**Comment by ryanmusante** [comment]
How so? What message do you receive?

**Comment by jimmymcperson** [comment]
When hovering over the proposal they are listed under "grateful".  Proposing it gives them a positive diplo mod too.

**Comment by ryanmusante** [comment]
To temporarily disable, use this. I've been running with remove ban luxury mod for months simply because I disagree with the idea behind it. 
```
<GameData>
	<Resolutions>
		<Delete Type="RESOLUTION_BAN_LUXURY_HAPPINESS"/>
	</Resolutions>
</GameData>
```

**Comment by LoneGazebo** [comment]
‘Their’ luxury. Did it hurt someone else more?
