### ISSUE TITLE
City Governor AI Ignore Great Improvements

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#4697]
_1. Mod version (i.e Date - 4/23):_
9-6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Looking at the screenshot below, you can see that the default governor is not working 2 great improvement tiles. Even the ivory tile is very good, but I could excuse that. However, the GI are clearly better than a specialist at the moment, but it has chosen to work all specialists instead.

I am not under any situational GP boosts that might explain why it would choose to do it at the moment.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/45255889-f3dffb80-b353-11e8-9c7e-547f7b1ced5a.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Specialists for more GPS.

**Comment by Stalker012345** [comment]
My argument would be that the weight of GPs is too high in that case (which may be a debate point on the forums).

**Comment by supermerill** [comment]
What i found strange, is that it prioritize the 7f 1g against a 6f 2p 8g
