### ISSUE TITLE
Extreme Food Bonus

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#4699]
_1. Mod version (i.e Date - 4/23):_
9-6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Unfortunately I didn't see when it was first triggered, I went back 5 turns of autosaves and it was still there.

My cities have an extreme amount of food, much more than they should be producing. The base food looks right, but after multiplication its an order of magnitude more than it should be.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/45258766-80ee7900-b383-11e8-9d48-b9dd78a764d2.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Looking at the AI it appears to have the same issue. Hehe 71 pop capitals!

**Comment by LoneGazebo** [comment]
Fixed in the hotfix I posted last night.
