### ISSUE TITLE
Feature request: Ability to view AI promises

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#470]
AI promises (settling, buying tiles, etc) have a fixed length just like other diplomatic deals, but no way to  actually view them anywhere. Would difficult would it be to make them visible?

**Comment by LoneGazebo** [comment]
Maybe, maybe not - depends where you want them. I could probably put them in the global relations tab.

**Comment by joosegoose** [comment]
I want them anywhere possible, :) Easiest method of implementation is more than fine.

**Comment by LoneGazebo** [comment]
I've looked into it, and it isn't possible without a significant rewrite of how the counter data is managed for promises in the DiploAI (for some reason, Firaxis decided to store all counter data EXCEPT for promises as separate values). Sorry, but I don't think this is feasible at present.

**Comment by joosegoose** [comment]
That's unfortunate to hear, but I appreciate you looking into it.

Would it be possible to at least display the length of the promise when you first make it? For example, you promise not to settle new lands and the dialogue box says right then and there it will be for 50 turns or whatever (kind of like agreeing to war says you'll wait 10 turns). That way users could at least easily write down the expiration dates themselves.

**Comment by LoneGazebo** [comment]
Yeah, I can do that.
