### ISSUE TITLE
Bugs with captured Holy Cities?

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#4703]
_1. Mod version (i.e Date - 4/23):_
9-6

_2. Mod list (if using Vox Populi only, leave blank):_

![45259353-c23d5380-b398-11e8-9e3e-026666386570](https://user-images.githubusercontent.com/19291347/45270237-19125e00-b469-11e8-87e2-567b52f076a3.PNG)

_3. Error description:_ 
Not sure if these are bugs:

No negative diplo mod for capturing a Holy City.  I remember this being a change a long time ago?  Or am I crazy.

Do not gain the ability to purchase all GP after capturing a Holy City with To the Glory of God (tried to purchase them from Holy City but it only shows the ones I've unlocked through policies)
.

**Comment by LoneGazebo** [comment]
You only get the bonus if the holy city's religion becomes your majority.
