### ISSUE TITLE
promotion logic

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4704]
```

	iTemp = pkPromotionInfo->GetGoodyHutYieldBonus();
	if (iTemp != 0 && GC.getGame().isOption(GAMEOPTION_NO_GOODY_HUTS))
	{
		iExtra = movesLeft();
		iTemp += (iExtra * 10);

		iValue += iTemp + iFlavorRecon * 4;
	}
```

isn't that supposed to be "if ! no_goody_huts" ?

also, and this concerns many other promotions as well, what role does "movesLeft()" play here? why should it be important?

**Comment by LoneGazebo** [comment]
AI always promotes at start of turn, so it’s a measure of speed. 

That is a typo. The ! missing.
