### ISSUE TITLE
Draft Registration Not Maintaining Extra XP

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#4705]
_1. Mod version (i.e Date - 4/23):_
9-6-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Apologies I missed the screenshot of this one. Last game I got draft registration and purchases a panzer, only receiving 2 promotions. 1 turn late the produced panzer came from the same city and had 3 promotions.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
More elaboration?

**Comment by Stalker012345** [comment]
Draft Registration is supposed to allow you to buy units and maintain their full XP. I found that after taking it and buying Panzer tanks that the effect was not working. I was still losing a level of xp compared to producing the unit.l

**Comment by LoneGazebo** [comment]
Ah gotcha. I'll look.
