### ISSUE TITLE
(AI) Chu-ko-nu only fire once

### ISSUE THREAD

**Issue by joosegoose** [LoneGazebo/Community-Patch-DLL#471]
This goes back to the base game and isn't the easiest to verify without a combat log (ugh Firaxis on both counts), but the AI seems to only be capable of Chu-ko-nu firing once, even if they don't move.

**Comment by LoneGazebo** [comment]
I'll point ilteroi to this, as he's been working on the tactical AI lately.
G

**Comment by ilteroi** [comment]
cho ko nus are killing machines now

**Comment by LoneGazebo** [comment]
Excellent.

**Comment by joosegoose** [comment]
Awesome! And I only just thought of this, but does this logic now apply to
other units with logistics as well?

**Comment by ilteroi** [comment]
it should work for all units. attacks are queued until the attacker runs out of attacks or moves
