### ISSUE TITLE
AI wasting Great Diplomat on Sphere-of-Influenced City State

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#4711]
_1. Mod version (i.e Date - 4/23):_
9-6-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Brazil used a GD on my CS perma-ally

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20180911115902_1](https://user-images.githubusercontent.com/13261433/45388106-9e1e8400-b5dd-11e8-8ee7-ca67e1643b53.jpg)
![20180911115855_1](https://user-images.githubusercontent.com/13261433/45388114-a70f5580-b5dd-11e8-83d7-ee79eb7f410c.jpg)

**Comment by LoneGazebo** [comment]
No better target, wanted the Paper, wanted friend status. All possibilities.
