### ISSUE TITLE
Desynchs & crashes in multiplayer

### ISSUE THREAD

**Issue by bklick** [LoneGazebo/Community-Patch-DLL#4713]
_1. Mod version (i.e Date - 4/23):_
Sept. 6 2018

_2. Mod list (if using Vox Populi only, leave blank):_
VP modpack with no  other mods attached, no EUI

_3. Error description:_ 
After the host ends the turn, the game will resynch. Non-host players will have their settlers moved elsewhere on the map. After this happens, non-host players will not have rewards fire from social policies, such as tech from gaining population in the capital. This is what I am referring to as a "desynch."

This can be averted by creating the game, leaving, and then hosting a saved game from the initial autosave. Rewards will fire as expected. However, resynchs remain frequent and random, and non-host players' instance of Civ V will crash at unpredictable intervals.

_4. Steps to reproduce (optional):_

Host any multiplayer game with a MPMPM modpack made from VP and nothing else. Make sure the other player also has this modpack and nothing else. Try to play normally.
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2373100/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2373099/auto.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I will have a DLL test for you soon.

**Comment by pzapza** [comment]
![1](https://user-images.githubusercontent.com/38469319/45444349-8a4f4c80-b6c7-11e8-97a7-36e1eedc0296.jpg)
![2](https://user-images.githubusercontent.com/38469319/45444348-8a4f4c80-b6c7-11e8-935f-b2ab80cbe20f.jpg)

so this just happened in the first round of world congress. of course, it resynched

**Comment by bklick** [comment]
what am I looking it?

**Comment by pzapza** [comment]
My friend, playing china, was seeing that arabia had picked "casus belli" (and coudnt pick it himself).
I, as siam and host, was seeing that arabia had picked "sanction: denmark". I would have been able to pick "casus belli", if i wanted.
Of course, as a result, the game reloaded the next turn.

i thought it belonged here somehow. if not, mea culpa, ill open a new issue.

**Comment by bklick** [comment]
Ahh, ok. Thanks for clarifying.

**Comment by ilteroi** [comment]
can you guys please check if the 9-15 release is good? i'm very curious. it might even be possible to play with barbarians ...

**Comment by bklick** [comment]
I'm hoping to be able to test it with a buddy tonight or tomorrow. Will
keep you informed.

**Comment by pzapza** [comment]
we're on it too. first test seemed pretty stable, but that was without barbs.

**Comment by bklick** [comment]
I am getting resynchs as early as turn 2 and then every few turns on from that.

**Comment by bklick** [comment]
Turning barbarians off definitely makes the game stable tho. Great work! Thanks so much.

**Comment by bklick** [comment]
Guy connecting to me is getting crashes that he doesn't get in single player. I'm trying to get him to turn on logs tho...

**Comment by bklick** [comment]
Also we are playing in Pit Boss, but it still says the AI is taking control when he crashes.

**Comment by bklick** [comment]
Are we sure it's barbs and not war versus players? The barbs are always at war with players, but do we get lots of crashes during any war, or just versus barbarians?

If it is barbs, could it have to do with encampment placement?

**Comment by LoneGazebo** [comment]
barbs don't touch the RNG, so they shouldn't cause desyncs there. Either there's a core flaw in our RNG method, or there's something that isn't caching correctly for MP WRT barb tactical behavior.

**Comment by bklick** [comment]
There something I could do to help eliminate one or the other as a possibility?

**Comment by bklick** [comment]
We're getting about 1 resynch every ten turns, but whatever was making my friend's civ crash went away.

We're playing with Barbs on, and it feels significant that I've only seen one camp in that time, despite a LOT of space for them to have spawned into. Not sure how significant that is.

**Comment by bklick** [comment]
Ok, so it's about every two turns now. I suspect it's tied to being at war, somehow.

**Comment by bklick** [comment]
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2395393/logs.zip)
I got a pretty random crash. I'll take this opportunity to attach logs and a save.

**Comment by bklick** [comment]
We've gone from that save to turn 87 without any resynchs and it's behaving really well. Makes me think the first time around was something on my end that wasn't this patch.

**Comment by LoneGazebo** [comment]
It could. If the browser is blocking packets it can result in packet loss and desyncs.

**Comment by LoneGazebo** [comment]
Civ is very sensitive to packet loss.

**Comment by bklick** [comment]
In that case, I wish I had a better testing environment. My internet comes from tethering my laptop to my phone, which is almost certainly being throttled at any given moment.

When I closed my browser, it felt like we got a lot of stability in exchange.
