### ISSUE TITLE
Conquer Spain religion missionary bug

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4714]
_1. Mod version (i.e Date - 4/23):_
current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So  I had a bad AIsabella found the last religion. After that, my Netherlands empire conquered her capital (the only city under her religion, the Holy City) and inquisitioned it.  Now the two cities she has left have the pantheon and since her religion is pretty much gone and no one can resurrect it, she is receiving my Religious Pressure normally, but I cannot use a Missionary on her cities.

**Comment by LoneGazebo** [comment]
You can't missionary her, period. 💃 

G
