### ISSUE TITLE
My code seems to have broken again. Please help!

### ISSUE THREAD

**Issue by iskaandismet** [LoneGazebo/Community-Patch-DLL#4719]
So, a while back I made some effort and introduced my DLL code from [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1480797731): into the CP DLL. At the time, I remember it working / it seemed to work. A few weeks later, I uploaded a bit more code to fix a bug and I remember it working. However, when using the latest CP beta / compiling the main repository, the code no longer seems to work. 

I've just spent the last hour or so going over the code in the CP, and it all seems to be close enough to my original changes (there seem to be additional checks for the existence of my mod?), which I know work, which can be found [here](https://drive.google.com/open?id=1N693z2NOpvdBL8KJ_usosbDAXZQA15n5). My method checking of the code is working is updating the game data base with the following sql line:

`INSERT INTO CustomModDbUpdates(Name, Value) VALUES('ISKA_HERITAGE', 1);`

, and then deleting CvGameCore_Expansion2.dll from Iska's Reign of Heritage (v 3), then loading my mod + (1) Community Patch. + IGE. Grant 500 Faith the first turn, then on the second turn pop the prophet and found a religion, then before ending turn use Firetuner to switch to any other player. The first player's Ideology should be Heritage, but isn't. 

I'm pretty frustrated, and would really appreciate the help of anyone who can navigate this code easily and knows what bugs and common errors look like who could give me a hand. Thanks in advance!!

**Comment by LoneGazebo** [comment]
@iskaandismet your best bet is going to be to compile the code in debug, then link civ to visual studio and attach a breakpoint to the section of code not working.
