### ISSUE TITLE
game is not reproducable

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#472]
i've been trying to find the reason why the (autoplayed) game is progressing differently each time. and indeed i found a call to a wrong (i.e. non-serialized) RNG. fixing that allows about 100 turns of perfect replay ... but then strange things start to happen.

first blip - attack target selection:

run 1:

128, Denmark, Trireme, Damage=0, ArmyID=-1, X=51, Y=39, DistFromCap=6
128, Denmark, Trireme, Damage=0, ArmyID=-1, X=67, Y=39, DistFromCap=20
**Evaluating attack on Copenhagen from base in Monaco. Approach is 0.60. Distance is 98 (weight 1.00), desirability 3.75, strength ratio 10.00, economic value 9.31 --> score 20938**
Evaluating attack on Copenhagen from base in M'banza-Kongo. Approach is 0.60. Distance is 101 (weight 1.00), desirability 3.75, strength ratio 0.81, economic value 9.31 --> score 1697
Evaluating attack on Copenhagen from base in Monaco. Approach is 0.60. Distance is 98 (weight 1.00), desirability 3.75, strength ratio 10.00, economic value 9.31 --> score 20938
128, Venice, 3, 0, 7, 138, 9, 0, 13, 6, 0, 0, 12, 
128, Venice, Naval Invasion Under Construction

run 2:

128, Denmark, Trireme, Damage=0, ArmyID=-1, X=51, Y=39, DistFromCap=6
128, Denmark, Trireme, Damage=0, ArmyID=-1, X=67, Y=39, DistFromCap=20
Evaluating attack on Copenhagen from base in M'banza-Kongo. Approach is 0.60. Distance is 101 (weight 1.00), desirability 3.75, strength ratio 0.81, economic value 9.31 --> score 1697
Evaluating attack on Copenhagen from base in M'banza-Kongo. Approach is 0.60. Distance is 101 (weight 1.00), desirability 3.75, strength ratio 0.81, economic value 9.31 --> score 1697
128, Venice, 3, 0, 7, 138, 9, 0, 13, 6, 0, 0, 12, 
128, Venice, Naval Invasion Under Construction

second blip - unit deployment:

run 1:

136, Persia, no zone, Deploying Horse Archer, To X: 62, To Y: 22, At X: 67, At Y: 23, Distance Before Move: 3
136, Persia, no zone, Deploying Immortal, To X: 63, To Y: 23, At X: 65, At Y: 26, Distance Before Move: 3
136, Persia, no zone, Deploying Immortal, To X: 64, To Y: 22, At X: 67, At Y: 22, Distance Before Move: 3
136, Persia, no zone, Deploying Immortal, To X: 62, To Y: 21, At X: 67, At Y: 20, Distance Before Move: 4
136, Persia, no zone, Deploying **Immortal**, To X: 65, To Y: 22, At X: 69, At Y: 19, Distance Before Move: 4
136, Persia, no zone, Deploying Horse Archer, To X: 61, To Y: 22, At X: 66, At Y: 15, Distance Before Move: 5
136, Persia, no zone, Deploying **Horse Archer**, To X: 61, To Y: 21, At X: 67, At Y: 14, Distance Before Move: 5

run 2:

136, Persia, no zone, Deploying Horse Archer, To X: 62, To Y: 22, At X: 67, At Y: 23, Distance Before Move: 3
136, Persia, no zone, Deploying Immortal, To X: 63, To Y: 23, At X: 65, At Y: 26, Distance Before Move: 3
136, Persia, no zone, Deploying Immortal, To X: 64, To Y: 22, At X: 67, At Y: 22, Distance Before Move: 3
136, Persia, no zone, Deploying Immortal, To X: 62, To Y: 21, At X: 67, At Y: 20, Distance Before Move: 4
136, Persia, no zone, Deploying **Horse Archer**, To X: 65, To Y: 22, At X: 68, At Y: 16, Distance Before Move: 4
136, Persia, no zone, Deploying Horse Archer, To X: 61, To Y: 22, At X: 66, At Y: 15, Distance Before Move: 5
136, Persia, no zone, Deploying **Immortal**, To X: 61, To Y: 21, At X: 69, At Y: 19, Distance Before Move: 5

afterwards, the logs diverge rapidly.

can you take a look at the code and check whether there is any unplanned randomness there? i don't see anything.

maybe it's in the sorting somewhere? if std::sort is multithreaded (not sure), maybe we should be using std::stable_sort instead?

second theory would be a bug in the pathfinder ... don't have any idea where to start looking though.

**Comment by LoneGazebo** [comment]
Hmmm…

For the first issue (the attack target selection), the only thing I can think is that the AI was allied in the first run, but not the second run. If not that, then the function to make the AI only evaluate open borders CSs needs to be adjusted. 

Not sure why it is running the same evals twice in a row, though - what do you think? The Military AI is, in my opinion, utterly bonkers from a code logic perspective, but that’s another story…

Second one might be an issue with the 'directionalization' of the pathfinder regarding west, northwest, etc. - if the ‘num_direction_types’ isn’t returned to zero on doing a pathfinder check, it’ll pick up wherever the most recent element in that function ended, thus potentially throwing off the ordering of the test.

These are just guesses, of course. I’ll do some research and get back to you.

G

**Comment by LoneGazebo** [comment]
Oh, hey, since we have no other way to communicate (while civfanatics is down), I've tagged a few of the issues here in the CP with 'help wanted.' They are areas of the DLL where you've edited stuff and/or you've been working recently, so I thought you might be able to know how to fix the issues. Let me know which if any you wish to work on and I'll assign them to you.

**Comment by ilteroi** [comment]
do you still have that savefile? which version is it compatible to?

**Comment by LoneGazebo** [comment]
I don't have it, sorry (current version is in flux, I'd have to go back and recreate that DLL version to make it compatible for you). You can reproduce by setting a worker to automation and/or a scout to recon. There is variability - not every time, but sometimes.

**Comment by LoneGazebo** [comment]
FYI: the Relative scoring stuff in religionclasses.cpp is causing some weird super-high values, but only on follower beliefs:

109, -150, Polynesia, Belief, Mandirs, -1786133732
109, -150, Polynesia, Belief, Cathedrals, 2105360416
109, -150, Polynesia, Belief, Mosques, 1893831932
109, -150, Polynesia, Belief, Stupas, 1405518802
109, -150, Polynesia, Belief, Synagogues, 1148876040
109, -150, Polynesia, Belief, Scholarship, 1061282681
109, -150, Polynesia, Belief, Veneration, 1061282681
109, -150, Polynesia, Belief, Asceticism, 1061282681
109, -150, Polynesia, Belief, Diligence, 1061282681
109, -150, Polynesia, Belief, Inspiration, 1061282681
109, -150, Polynesia, Belief, Mastery, 1061282628
109, -150, Polynesia, Belief, Cooperation, 1061282612
109, -150, Polynesia, Belief, Orders, 16225370
109, -150, Polynesia, Belief, Pagodas, 0
109, -150, Polynesia, CHOSEN, Cathedrals
109, -150, Polynesia, Belief, Holy Law, 915
109, -150, Polynesia, Belief, Theocratic Rule, 525
109, -150, Polynesia, Belief, Ceremonial Burial, 505
109, -150, Polynesia, Belief, Mandate of Heaven, 225
109, -150, Polynesia, Belief, Council of Elders, 225
109, -150, Polynesia, Belief, Hero Worship, 105
109, -150, Polynesia, Belief, Apostolic Tradition, 90
109, -150, Polynesia, Belief, Way of the Pilgrim, 0
109, -150, Polynesia, CHOSEN, Theocratic Rule

**Comment by ilteroi** [comment]
hmm, that's an overflow right there in the first line. not good

**Comment by LoneGazebo** [comment]
Eh?

**Comment by ilteroi** [comment]
the negative number ... something is wrong in the calculation

**Comment by LoneGazebo** [comment]
What negative number? Eh?

**Comment by ilteroi** [comment]
now i'm confused too ... did you remove a comment of yours? there was one about belief scoring. in the first line, the score was was negative.

**Comment by LoneGazebo** [comment]
A while back (maybe a week or so), yeah I did, as it was simply a nested loop that I had messed up on. 

Current DLL version uploaded. Make sure to merge changes before continuing to work. Stable so far, however I've ran into two un-reproduceable 'hangs' (not full CTDs) in the late game. Feels like an endless loop causing a memory overflow.

**Comment by LoneGazebo** [comment]
Crap, upload didn't sync. I'll have to do it when I get back from office.

**Comment by ilteroi** [comment]
ok, it turns out you should not use pointers in sorted stl containers - the resulting order is unpredictable. this led to different units being selected for moves and in the end wildly diverging outcomes. 

took me a while to get to the root cause. i incorporated a call stack tracing tool for this, could be useful for other issues as well. maybe hook it up to the minidump handler? you'd need to ship the pdb file for it to work though.

the sorting is fixed now. however, some points remain:
- the very fact that whole civilizations can be wiped out or thrive depending on the order in which units are processed is quite worrying
- AI has a bias towards northwest plots and units with low IDs because of the iteration order (often the first matching candidate is used)
- some state is not serialized (m_cachedTargets, m_knownUnits) so there will still be differences between playing from beginning and loading a savegame (maybe fix later)
- minor differences still observed in the logs but without permanent effects:
      - single city strategy check for barbarian city missing
      - one sneak attack skipped in military target selection

**Comment by LoneGazebo** [comment]
Excellent. Pushed to github, I presume? 

Regarding the errors:

If a civilization's survival is dependent on one unit's movement, I don't think the civ was destined for greatness.
I wonder if we could modify iteration by intentionally assigning higher CS units with lower IDs? Do we have any control over what IDs are chosen to be assigned?

**Comment by LoneGazebo** [comment]
Also, this will probably cause the multiplayer desyncs to drop dramatically, as AI behavior is, IIRC, handled and sync'd on each machine (probably causing the desyncs when two different units make two different moves, even though the AI only wants to make one move).

**Comment by ilteroi** [comment]
i have been thinking about multiplayer, but people reported seeing desyncs from the very beginning of the game. the different move orders typically occur in the mid-game when you have multi-unit operations. so it's worth a try, but i'm not sure that it will be the silver bullet

**Comment by ilteroi** [comment]
regarding iteration order ... it's not sooo bad because typically multiple factors are taken into account when selecting a unit. the ID is only relevant when all other conditions are met.

messing with the unit IDs is a recipe for trouble, it would e.g. mess up assignments to armies. units are stored in a FFreeListTrashArray<>, but I don't really understand how it works ... probably the only way would be to replace it by something sane like a std::map and a std::vector to define iteration order. then reorder the vector according to need (randomly or in rising/falling CS order).

but that's a tall order, maybe another day :)

**Comment by LoneGazebo** [comment]
Well, I think it'll definitely help. I need to check in on the MP users to see if the changes we've made recently have helped at all with early game desyncs.

**Comment by LoneGazebo** [comment]
Oh, also, you didn't include your stackwalker file. Mind uploading that?
G

**Comment by ilteroi** [comment]
indeed. my bad. it's done
