### ISSUE TITLE
CTD on AI's turn

### ISSUE THREAD

**Issue by czaurel** [LoneGazebo/Community-Patch-DLL#4720]
**1. Mod version (i.e Date - 4/23):**
9-6-2

**2. Mod list (if using Vox Populi only, leave blank):**
Standard VP with EUI, nothing extra.

**3. Error description:**
After hitting next turn, Denmark's turn begins then lasts until CTD. Huge memory consumption starts showing right before the crash, up to 3.5 GB from around 1GB before. Happens the same way from autosaves 1 and 2 turns before.

**4. Steps to reproduce (optional):**
Load the save, end the turn (a missionary might have some moves left).

Save and logs (the dump file was completely empty, might be a side effect of an out-of-memory error?):
[20180914_CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2381224/20180914_CTD.zip)

Thanks for your time!

**Comment by LoneGazebo** [comment]
This will be addressed in the next version.
