### ISSUE TITLE
Panzers unlock at Ballistics

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#4721]
_1. Mod version (i.e Date - 4/23): 5/20

_2. Mod list (if using Vox Populi only, leave blank): Lot of mods, but should not have any impact

_3. Error description:_ 
Seems the German Panzer is unlocked at Ballistics. I think it should unlock at Combined Arms as Tanks.

Solution:
UPDATE Units SET PrereqTech = 'TECH_COMBINED_ARMS' WHERE Type = 'UNIT_GERMAN_PANZER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

**Comment by bigcat88** [comment]
No, description says that it is avalaible earlier then Tanks.

**Comment by Vyyt02** [comment]
Ohhh, ok, got it, my bad then. They just looked a bit inappropriately among all those "ancient" landships (I got  the panzer from a military CS).
