### ISSUE TITLE
Diplomacy "discuss" issues rarely don't appear or are unknown 

### ISSUE THREAD

**Issue by SpankMyMetroid** [LoneGazebo/Community-Patch-DLL#4725]
_1. Mod version (i.e Date - 4/23):_
9-6

_2. Mod list (if using Vox Populi only, leave blank):_
Communitas V1.4.4, Infoaddict

_3. Error description:_ 
Very rarely in my recent game (the 3rd played on this patch, and this is the first time encountering it) diplomacy options under "Discuss" sometimes won't appear for a long number of turns for a particular leader. Other diplomatic options worked. I can't reproduce it going back through autosaves. It's impossible to correlate but both civilizations this happened with were "false" friendly (declared war on me shortly after despite having a friendly modifier). After the wars I looked again and found these dialogue options I've never seen before... the repeating "perhaps we can offer you something..." choices all gave different responses to various normal requests. For example, the 7th from the top asked to stop spying, 6th asked to move troops from borders, 5th to stop converting cities, etc. Going back through autosaves, this is the result I get from these leaders instead of the "blank" diplomacy options.      

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20180916005715_1](https://user-images.githubusercontent.com/20096768/45593163-8d5b6e80-b94d-11e8-8abd-1ca0518d9c94.jpg)

**Comment by SpankMyMetroid** [comment]
Seems like it's happened before https://www.reddit.com/r/civ/comments/3aagur/screenshots_so_i_was_told_i_would_love_the_civ_iv/

**Comment by ryanmusante** [comment]
Communitas mod?

**Comment by TechpriestEnginseer** [comment]
This is where lua.logs can help diagnose the issue a lot.

**Comment by LoneGazebo** [comment]
Fixed in 9-15
