### ISSUE TITLE
People's Army Order tenet has incorrect information (or is bugged)

### ISSUE THREAD

**Issue by SpankMyMetroid** [LoneGazebo/Community-Patch-DLL#4726]
_1. Mod version (i.e Date - 4/23):_
9-6

_2. Mod list (if using Vox Populi only, leave blank):_
Communitas V1.4.4, Infoaddict

_3. Error description:_ 
People's Army says it grants a free military academy in the capital, but instead grants a free military academy in every city. 
![20180916143158_1](https://user-images.githubusercontent.com/20096768/45599660-89673500-b9bd-11e8-8896-4aaf9e7afef7.jpg)
![20180916143149_1](https://user-images.githubusercontent.com/20096768/45599661-8cfabc00-b9bd-11e8-8ad6-904415307e87.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Fixed already in 9-15
