### ISSUE TITLE
Wild swings in happiness

### ISSUE THREAD

**Issue by paramenides** [LoneGazebo/Community-Patch-DLL#4731]
_1. Mod version (i.e Date - 4/23):_

9/15
_2. Mod list (if using Vox Populi only, leave blank):_
faster airplane animations

_3. Error description:_ 

Not an error. Just a HUGE swing in turn to turn happiness.
_4. Steps to reproduce (optional):_

None, but save games are below
[AutoSave_0694 AD-1598.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2390615/AutoSave_0694.AD-1598.zip)
[Ashurbanipal_0696 AD-1602.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2390616/Ashurbanipal_0696.AD-1602.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Yes, formulas to happiness can adjust very rapidly... however this has been addressed in the latest version already so.
