### ISSUE TITLE
AI Still Declaring War on Vassals

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#4732]
_1. Mod version (i.e Date - 4/23):_
9-15

_2. Mod list (if using Vox Populi only, leave blank):_
![capture](https://user-images.githubusercontent.com/19291347/45660181-88b9c600-bac5-11e8-876b-283e8ecf1471.PNG)

_3. Error description:_ 
Germany declared war on my vassal Russia.  They peaced a turn after.

**Comment by LoneGazebo** [comment]
That's the least amount of information. How? Through a diplo popup?

G

**Comment by jimmymcperson** [comment]
No special situation from what I can see.  They straight up declare war on the vassal and then immediately sign a peace treaty just like last patch.

Vassals and city states are following me to war however so that seems fixed.

**Comment by bigcat88** [comment]
I saw the same in my game yesterday, but it was only a few turns, cause GlobalLiberation was in progress.
In my game: One AI declared war on vassal's of another AI... Master wasn't in war.
If I will see this again in that game, I will post more info.

**Comment by jimmymcperson** [comment]
Been playing with hotfix and it seems to be fixed.
