### ISSUE TITLE
Infinite paratrooper 

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4735]
_1. Mod version (i.e Date - 4/23):_
last with hotfix

_2. Mod list (if using Vox Populi only, leave blank):_
NavalWarfare

My paratrooper can paratroop 4 times(I think as many times as I need). Here is it promotions:
![20180918182639_1](https://user-images.githubusercontent.com/13381981/45698390-8d878400-bb70-11e8-897d-9b0bb1fb8aa6.jpg)

I think the problem is that paratroop don't remove last move turn. This paratrooper is a scout upped from the beginning of fun game.
If needed I will generate a test save for that.
On screen this is a paratrooper that already paratroop 4 times to reach that point. Only first paratrooping cost a move.

**Comment by LoneGazebo** [comment]
@ilteroi any ideas? Is paratroop not removing all moves?

**Comment by SpankMyMetroid** [comment]
This was present in 9-6 too but I thought it was intentional so I didn't post anything.

**Comment by bigcat88** [comment]
Just inform: In hotfix 19 September it is still present.
