### ISSUE TITLE
AI Gandhi is picking Universalism

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4736]
_1. Mod version (i.e Date - 4/23):_
9-15-1

_2. Mod list (if using Vox Populi only, leave blank):_
none

_3. Error description:_ 
In my 9-15 game, Gandhi was the first civilization to enhance, and he chose Universalism. Is this belief still good enough without the ability to use missionaries?

**Comment by TechpriestEnginseer** [comment]
Yes, sometime the AI will pick it to deny beliefs to others as well.
