### ISSUE TITLE
Inconsistent header's font and colour

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#4737]
Mod version: 9-15 and earlier.

Now, during some modscripting I noticed that many windows have differnt pattern of headers: font, size, capital letters etc. They should follow same pattern imo. Cleaning is advised.

Few examples (I didn't check them all):
![20180918222946_1](https://user-images.githubusercontent.com/33016300/45715671-144e5800-bb95-11e8-83b4-96dfedfedfc3.jpg)
![20180918222951_1](https://user-images.githubusercontent.com/33016300/45715672-144e5800-bb95-11e8-81e9-98ac35537f2b.jpg)
![20180918222955_1](https://user-images.githubusercontent.com/33016300/45715673-144e5800-bb95-11e8-923b-30729673f71b.jpg)
![20180918223000_1](https://user-images.githubusercontent.com/33016300/45715674-144e5800-bb95-11e8-9461-916170bb2237.jpg)
![20180918223004_1](https://user-images.githubusercontent.com/33016300/45715675-14e6ee80-bb95-11e8-95b4-141f228d3f51.jpg)
![20180918223014_1](https://user-images.githubusercontent.com/33016300/45715676-14e6ee80-bb95-11e8-8367-9453421b3181.jpg)
![20180918223029_1](https://user-images.githubusercontent.com/33016300/45715679-14e6ee80-bb95-11e8-837d-c4aa4be7c458.jpg)

**Comment by LoneGazebo** [comment]
Eh. This is vanilla design stuff, but it doesn't really matter. I defer to others.
