### ISSUE TITLE
Hotfix turns on events even if they were off in-game

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#4739]
_1. Mod version (i.e Date - 4/23):_
9-15-2

_2. Mod list (if using Vox Populi only, leave blank):_
![capture](https://user-images.githubusercontent.com/19291347/45723680-849eae80-bb80-11e8-89ed-6cf5cb4eced2.PNG)

_3. Error description:_ 
I had all events turned off in Really Advanced Setup and the hotfix re-enabled them when I loaded a save.

**Comment by ryanmusante** [comment]
As of 9-15-2 it has changed to the following:

-- uncheck "Enable Events System" by default 
UPDATE GameOptions SET "Default" = 0 WHERE Type = 'GAMEOPTION_EVENTS';
-- check "No Good Events" by default
UPDATE GameOptions SET "Default" = 1 WHERE Type = 'GAMEOPTION_GOOD_EVENTS_OFF';
-- check "No Neutral Events" by default
UPDATE GameOptions SET "Default" = 1 WHERE Type = 'GAMEOPTION_NEUTRAL_EVENTS_OFF';
-- check "No Bad Events" by default
UPDATE GameOptions SET "Default" = 1 WHERE Type = 'GAMEOPTION_BAD_EVENTS_OFF';
-- check "No Trade Events" by default
UPDATE GameOptions SET "Default" = 1 WHERE Type = 'GAMEOPTION_TRADE_EVENTS_OFF';
-- check "No Civ-Specific Events" by default 
UPDATE GameOptions SET "Default" = 1 WHERE Type = 'GAMEOPTION_CIV_SPECIFIC_EVENTS_OFF';

**Comment by jimmymcperson** [comment]
Are you saying that I can disable events in my current save?
