### ISSUE TITLE
CTD Issue.

### ISSUE THREAD

**Issue by jeffpierce** [LoneGazebo/Community-Patch-DLL#474]
Windows 8, Steam version of Civ 5 with all DLC.

Save is located at http://coldflare.net/Save.zip

Using CP 7-24v3, CBP 7-24v2, More Luxuries + compat, and Events and Decisions (3-30).

To repro, load save, end turn, accept Friendship with Kamehameha, respond to Morocco with "Sorry this has caused a divide between us."  Can do that either right away or after being rude once, crashes either way.

Let me know if I can get you any more info.

**Comment by jeffpierce** [comment]
Oddly enough, I enabled debug mode and logging to get you more info, and when I tried to repro, no crash.

I'll leave this open in case you feel it's an interesting edge case, otherwise, close it.

**Comment by LoneGazebo** [comment]
I messed with the save, but I can't reproduce. Does the crash occur when you click an interface button, or simply during the AI's turn?

**Comment by jeffpierce** [comment]
It occurred immediately after clicking the "Sorry" response interface button to Morocco complaining about meeting buddy buddy with Sidon.

Odd part was that it stopped happening (on that particular one) after enabling debug mode and logging, but it still happened on a few other dialogue interface buttons.

Are there any steps you'd like me to try on my rig?  I took a look over the lua code, and nothing immediately jumped out at me, so I'm inclined to think it's my local setup -- but now it's going to bug me until I figure out why (such is the curse of a DevOps engineer).  Even just pointing me in the right direction would be helpful.

Thanks for the awesome work, by the way.  Breathed new life into the game for me.  As someone who did a stint in the game industry, consider it a professional compliment on balancing design.

-- Jeff

**Comment by LoneGazebo** [comment]
'Still' meaning after enabling debugging? If it happens again, send me your lua.log, database.log, and, if there's a minidump file in your civ 5 root directory, link that as well.

**Comment by jeffpierce** [comment]
Yeah, after enabling logging.

I'll start up a session once I'm home from work and see if I get anything.

**Comment by jeffpierce** [comment]
So, after two more days of playing, I've gotten a few more CTDs when using dialogue choices that happen during the CPU turns, but with less frequency and no real pattern other than it happens during CPU turns, but rarely.

I'm installing on my other computer as we speak to see if it happens there.  If it does, I'll proceed with getting files to you.

**Comment by LoneGazebo** [comment]
Sounds great. If you get a repeat crash, send me the save file. Otherwise, send me your log files and the minidump file (if the crash makes one).

Thanks!

**Comment by LoneGazebo** [comment]
Any luck?

**Comment by Samitian** [comment]
I'm having a similar CTD issue, 

Windows 7, Steam version, All DLC

Mods Used: 
Community Balance Patch 7-24 
Community Patch 7-24v3
City State Diplomacy Mod 6/19
Civ 4 Diplomacy Features 6/19
Community Balance Patch Compatability Files (EUI) 7-24
Enhanced User Interface (CBP) 7-21
Events and Decisions (CBP) 3-30
Infoaddict (v22)
More Luxuries (v155)
Reduced Unit Graphics (v9)

Infoaddict is required by the save file to load, so I cannot test with that disabled. 
I removed Reduced Unit Graphics and problem still occurs. 

Crash occurs during conversation with the Celts after turn ends, and choosing the "Yes, Let us work together" option. 

Save File: https://www.dropbox.com/s/nitpkqlbgnri9r7/AutoSave_0131%20AD-0400.Civ5Save?dl=0
Crash Dump: https://www.dropbox.com/s/5zhsj3i5vdwt05i/CvMiniDump.dmp?dl=0
