### ISSUE TITLE
Stuck on Choose Production After City Trade

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#4744]
_1. Mod version (i.e Date - 4/23):_
9-15-2

_2. Mod list (if using Vox Populi only, leave blank):_
![capture](https://user-images.githubusercontent.com/19291347/45813162-ddb13400-bc9f-11e8-9d7d-4140b470de14.PNG)

_3. Error description:_ 
I returned my vassal Russia's capital to her while it had nothing in production queue.  The game then expects me to Choose Production even though I've already set all my cities production queue.  Nothing happens when I click this button and the game cannot progress.

**Comment by TechpriestEnginseer** [comment]
Save and restart.

**Comment by LoneGazebo** [comment]
What @TechpriestEnginseer said.

**Comment by jimmymcperson** [comment]
Was able to continue with that one weird trick,

**Comment by LoneGazebo** [comment]
doctors hate it
