### ISSUE TITLE
Order's Tenets Still Give Free Buildings to All Cities

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#4745]
_1. Mod version (i.e Date - 4/23):_
9-15-2

_2. Mod list (if using Vox Populi only, leave blank):_
![capture](https://user-images.githubusercontent.com/19291347/45814998-641c4480-bca5-11e8-8678-cc3a89ff7de9.PNG)

_3. Error description:_ 
Order's tenet still gives free research labs.  I didn't pay attention but I think Military Academy is still free too, since it's listed as (FREE) at my cities.  Might want to check.

**Comment by LoneGazebo** [comment]
You get a free one of each in capital. Otherwise no change.

**Comment by jimmymcperson** [comment]
Just tested with IGE.

![capture](https://user-images.githubusercontent.com/19291347/45854422-07f30800-bd19-11e8-8f58-058873962054.PNG)

**Comment by bigcat88** [comment]
Yeah, in my game I see the same, in all cities I received mil academ

**Comment by TechpriestEnginseer** [comment]
The problem is the table itself Policy_FreeBuilding. I added giving a free council for only 4 cities for opening with tradition and this bonus applied in every city. Not just 4.
