### ISSUE TITLE
Stuck on AI Turn

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#4747]
_1. Mod version (i.e Date - 4/23):_
9-19

_2. Mod list (if using Vox Populi only, leave blank):_
![capture](https://user-images.githubusercontent.com/19291347/45851021-b2156480-bd06-11e8-8be7-7363971ad5c6.PNG)

_3. Error description:_ 
The game stays on "Processing Turn For The Huns" indefinitely when I press Next Turn, denying me sweet victory from a tough game.

[Logs.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/2403317/Logs.gz)

I tried declaring war before passing the turn and that seems to allow the game to progress normally, but still worth looking into.

**Comment by TechpriestEnginseer** [comment]
We had this kind of issue before and it's usually when the AI is stuck in a (pathfinding glitch) somewhere that we can't exactly explain why it's doing so which is why declaring war or doing something to suddenly change its pathfinding will fix this issue.
