### ISSUE TITLE
Can't pillage enemy trade unit if neutral trade unit is on the same tile

### ISSUE THREAD

**Issue by SpankMyMetroid** [LoneGazebo/Community-Patch-DLL#4748]
_1. Mod version (i.e Date - 4/23):_
9-6

_2. Mod list (if using Vox Populi only, leave blank):_
Communitas V1.4.4

_3. Error description:_ 
Probably very unlikely to happen naturally but the neutral trade unit can "stack" over the enemy one, meaning you're not able to pillage it. It might not be even worth fixing considering how rare it could be, but figured I'd point it out. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20180920182004_1](https://user-images.githubusercontent.com/20096768/45851778-8b592d00-bd0a-11e8-8fc1-4d5d834ed750.jpg)

**Comment by TechpriestEnginseer** [comment]
Unfortunately, the code behind plundering will plunder all trade routes (without checking its status), so I suggest just tracing its footstep.
