### ISSUE TITLE
Gazebo please save me some time

### ISSUE THREAD

**Issue by iskaandismet** [LoneGazebo/Community-Patch-DLL#4751]
So I went through my code arduously line by line to see what was making it not work. For some reason, changing 
`if (MOD_ISKA_HERITAGE && ePlayerReligion > RELIGION_PANTHEON)`
to
`if (ePlayerReligion > RELIGION_PANTHEON)`

fixes the code. I don't know why, but that seems to be the one line that was preventing it from working, and that line isn't in my original code. Which I'm pretty someone (Gazebo) added it. Best of intentions I'm sure, but a bit frustrating that I don't know why it is that this makes it not work, and that it was made to not work in the first place.

Anyway I opened up a pull request but seem to have boned that right up, so if someone (Gazebo) who knows what they're doing could spare me some time and just add THAT ONE LINE in instead of making me run in circles trying to get github to work for me, I would really appreciate it.

Hope that wasn't awfully belligerent, I rewrote it a couple of time. I appreciate the Community Patch and all the work that goes into it, you guys are the best <3

**Comment by LoneGazebo** [comment]
I'll look at it. :)

I added that as a preventative check - it shouldn't be causing issues - are you enabling ISKA_HERITAGE in the custommodoptions.xml file?

G

**Comment by iskaandismet** [comment]
`INSERT INTO CustomModDbUpdates(Name, Value) VALUES('ISKA_HERITAGE', 1);`

**Comment by iskaandismet** [comment]
In fact, doing more testing, it looks like the tooltip generation isn't working either. I think your
`if (MOD_ISKA_HERITAGE &&`
broke my code in more than one place.

**Comment by iskaandismet** [comment]
Unless, and this is a real forehead-smacker, do I have to update two different dbs?

**Comment by iskaandismet** [comment]
mfw all I needed to do was add the xml lines
`<GameData>
	<CustomModOptions>
		<Update>
			<Set Value="1"/>
			<Where Name="ISKA_HERITAGE"/>
		</Update>
	</CustomModOptions>
</GameData>`
for it to work. Argh. I didn't realize I needed to update two different variables. Totally my bad Gazebo, I'm a terrible programmer.

**Comment by LoneGazebo** [comment]
No problem! I hate that you spent so much time on, I should have explained to you that I added a control define to the custommodoptions.xml file. Sorry. :/
