### ISSUE TITLE
City UI issue and a top hotbar issue (?)

### ISSUE THREAD

**Issue by ProCatGamer** [LoneGazebo/Community-Patch-DLL#4752]
_1. Mod version (i.e Date - 4/23):_

9/20

_2. Mod list (if using Vox Populi only, leave blank):_

![20180921134707_1](https://user-images.githubusercontent.com/42237212/45862693-83020000-bda5-11e8-87ea-154857e51760.jpg)

_3. Error description:_ 

![bug](https://user-images.githubusercontent.com/42237212/45862812-06bbec80-bda6-11e8-9d9b-c6134b081192.jpg)

The city left description is bugged not showing values etc.
Also at the top of the UI there is something called instant ? Which seems to have no purpose and took up the space which tells me my unit cap

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
The field "INSTANT" is supposed to be indicating the average yield per turn you have from instant yields.

**Comment by TechpriestEnginseer** [comment]
The issue here is that his UI is bugged, have you tried reinstalling and deleting bc1 files inside your civ5 folder?

**Comment by ProCatGamer** [comment]
> The issue here is that his UI is bugged, have you tried reinstalling and deleting bc1 files inside your civ5 folder?

Yup I've tried reinstalling Civ 5 and the issue is still there

**Comment by ProCatGamer** [comment]
> The field "INSTANT" is supposed to be indicating the average yield per turn you have from instant yields.

OH I SEE
I thought it was a glitch as the unit limit was replaced by it

**Comment by ProCatGamer** [comment]
This only like happened to me for the 
"Hotfix for barb crazies and a bit more RNG work for MP incoming. Called 9-19" one 
but if I use the previous beta one with the installer its all fine

**Comment by TechpriestEnginseer** [comment]
Has the bug been fixed for you?
