### ISSUE TITLE
Can Purchase Spaceship Parts with Gold without 'Space Procurements' Tenant

### ISSUE THREAD

**Issue by cdanger341** [LoneGazebo/Community-Patch-DLL#4754]
_1. Mod version (i.e Date - 4/23):_
9-6

_2. Mod list (if using Vox Populi only, leave blank):_
None

_3. Error description:_ 
It has been a while since I tried for a Science Victory, but I noticed from Martin Fencka's most recent LP (see link below) that he was able to purchase SS Parts using gold even though he went Order instead of Freedom. He even comments upon it in his videos.

https://www.youtube.com/watch?v=XmwYkuclwPc

_4. Steps to reproduce (optional):_

Play a game to Information Age and pick Autocracy or Order as your Ideology, then build a Spaceship Factory. SS Parts are buyable with Gold.

**Comment by LoneGazebo** [comment]
I fixed that in 9...15? I can't remember, but it should be fixed now. If you can still replicate let me know.
