### ISSUE TITLE
Settler from Conscript policy

### ISSUE THREAD

**Issue by CppMaster** [LoneGazebo/Community-Patch-DLL#4756]
_1. Mod version (i.e Date - 4/23):_ 9/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I got a settler from Conscript policy, when my city reached 20 population.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![settler conscript bug](https://user-images.githubusercontent.com/8946274/45915652-d97c4680-be58-11e8-876e-04d4890f9be2.png)

**Comment by TwoPodRay** [comment]
I also recently got a couple workers from conscript. I was coming back and adopting Authority tree later in the game after finishing my Ideology to transition into more war for Domination Victory. Most of my cities were over 20 pop by then.
