### ISSUE TITLE
Morroco Cannot Pillage Trade Routes To Themselves During War

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#4757]
_1. Mod version (i.e Date - 4/23):_
9-19

_3. Error description:_ 
Morroco's UA doesn't allow pillaging trade routes toward them but I think they should be able to if they are at war with the trade route owner.

**Comment by LoneGazebo** [comment]
Not part of the UA. Besides you can’t send trade routes to players you are at war with.

**Comment by jimmymcperson** [comment]
I declared war vs william who had two trade routes to me and they continued.  I couldn't pillage them and I thought that was strange.

**Comment by LessRekkless** [comment]
I too am seeing that trade routes that were established to a civ before that civ declares war will still continue until they are pillaged.

**Comment by LoneGazebo** [comment]
They only persist for a round, then they are recalled.
