### ISSUE TITLE
Askia cities not connecting via rivers in MP

### ISSUE THREAD

**Issue by DisgruntledPotato** [LoneGazebo/Community-Patch-DLL#4758]
_1. Mod version (i.e Date - 4/23):_
9-19

_2. Mod list (if using Vox Populi only, leave blank):_
1. Unit Path Viewer (v 10) 
2. UI - Improved City View (Vox Populi EUI) (v 10) 
3. UI - Religion Spread (Vox Populi) (v 1.0) 
4. UI - Filters in Trade Route Overview (Vox Populi) (v 1) 
5. UI - Show XP in Military Overview (v 2) 

_3. Error description:_ 
In MP (nonhost) as Askia, founding cities on the same river as capital neiter show a "city connected to capital" icon nor produce gold.
Oddly enough, these cities don't suffer from isolation.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![grafik](https://user-images.githubusercontent.com/43501254/45919881-c55a3880-be9c-11e8-9069-3e86597d6158.png)

**Comment by ilteroi** [comment]
very strange. can anyone else reproduce this?

**Comment by LoneGazebo** [comment]
@ilteroi a few other users have reported plot-related quirks in MP. It’s on my long term list to look at as well.
