### ISSUE TITLE
City Connections

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#476]
Take a look at foreign cities with OB blocking connections.

**Comment by ilteroi** [comment]
stupid question, but what is OB?

**Comment by LoneGazebo** [comment]
Open borders.

**Comment by ilteroi** [comment]
hmm. i had thought about that, but how can open borders block a connection? what does foreign mean anyway, afaik you can't have city connections with other players?

i guess what i'm saying is, i don't have a clue what the problem is here. do you have a screenshot?

**Comment by LoneGazebo** [comment]
The problem being reported is that, if a player has open borders with another civ, their roads should be useable to create a city connection between two civs. In DLL terms, non-player-owned tiles shouldn't block the routefinder if you have open borders with the owner.

**Comment by ilteroi** [comment]
nice - i had just started to look, but superficially everything seemed to be in working order. what was the problem?

**Comment by LoneGazebo** [comment]
Harbors simply weren't registering properly. We'll need more testing for fringe cases, but overall I think it is back in working order.

**Comment by ilteroi** [comment]
ah, i meant the roads through open borders

**Comment by LoneGazebo** [comment]
On another note, merged your changes. You've got an 'unreachable code' error in the 'updateTeamStatus' function in the cvteam.dll file

**Comment by LoneGazebo** [comment]
roads through open borders need more testing.

**Comment by ilteroi** [comment]
the unreachable code must be a merge error ...

**Comment by LoneGazebo** [comment]
You sure? The function was merged as a whole section.

**Comment by ilteroi** [comment]
well, i just compiled it ... but anyway, new commit is coming soon, hold on a second

**Comment by LoneGazebo** [comment]
It'll only show as a warning, not an error, just FYI.
