### ISSUE TITLE
Lancer description still incorrect

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4761]
_1. Mod version (i.e Date - 4/23):_
9-15-2

Both the Lancer's in-game description and strategy still say that it has a penalty on defence, which is not the case.

**Comment by TechpriestEnginseer** [comment]
And I can't find any code that says so here unless proven otherwise.

**Comment by TechpriestEnginseer** [comment]
This is vanilla.
![image](https://user-images.githubusercontent.com/13937047/46873650-f8348400-cdeb-11e8-8cc9-853d19bf2e26.png)

![image](https://user-images.githubusercontent.com/13937047/46873664-fff42880-cdeb-11e8-88f4-f1d8e941bfe9.png)

**Comment by LessRekkless** [comment]
And I have ... neither of those, so it seems like I still have an intermediate Civilopedia update. What steps do I need to take to fix this?

**Comment by TechpriestEnginseer** [comment]
Probably fresh reinstall. It could also possibly be a external mod updating the description.
