### ISSUE TITLE
God of sun effect on grassland w/out wheat

### ISSUE THREAD

**Issue by marcoatk85** [LoneGazebo/Community-Patch-DLL#4764]
_1. Mod version (i.e Date - 4/23): 9-19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When I look to a grassland, it shows "god of sun" effect as an improvement even though there is no wheat on it. Instead it should take the advantage of the open sky. 

_4. Steps to reproduce (optional):_
![8930_screenshots_20180924220320_1](https://user-images.githubusercontent.com/40754177/46004609-f8c6de00-c0bb-11e8-825e-17fb3fec0e53.jpg)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by marcoatk85** [comment]
The mod is 9-15 meanwhile not 9-19 of course :)

**Comment by LoneGazebo** [comment]
Just an EUI quirk.
