### ISSUE TITLE
Invincible Melee Ships

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#4766]
_1. Mod version (i.e Date - 4/23):_
9-25

_2. Mod list (if using Vox Populi only, leave blank):_
![capture](https://user-images.githubusercontent.com/19291347/46077514-21ec7a80-c15f-11e8-8343-e2f4d6e70009.PNG)

_3. Error description:_ 
![capture](https://user-images.githubusercontent.com/19291347/46077405-c7531e80-c15e-11e8-8d1e-7078e1363efb.PNG)

Attacking a ship over and over caused damage to be reduced to 0.  Skirmisher did like 27 damage, Catapult did around 29, Comp Bow 3, and Comp Bow 0.  Enemy trireme is sporting Dreadnought 1

**Comment by LoneGazebo** [comment]
Testing now, not happening on my end. Let me keep trying to replicate.
