### ISSUE TITLE
Mandekalu Cavalry still at 15 CS 

### ISSUE THREAD

**Issue by chicorbeef** [LoneGazebo/Community-Patch-DLL#4769]
1. Mod version (i.e Date - 4/23): 9/25

2. Error Description: Horsemen were adjusted to 14 CS but Mandekalu Cavalry still retain 15 CS. 
--------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
but it is a unique unit that mandekalu cavalry probably should run the early game whereas the horseman was basically overused in every civ

**Comment by LoneGazebo** [comment]
Intended
