### ISSUE TITLE
CTD upon settling first city

### ISSUE THREAD

**Issue by jcmsmith** [LoneGazebo/Community-Patch-DLL#477]
The patch itself works fine, alone and with CBP, and without it I can install plenty of other mods, but when I try to use the compatibility files with CSD, C4DF, and more luxuries it immediately crashes to desktop when I try to settle.  I'm using non-EUI.

Please help, this patch sounds amazing, and I don't really want to play without those extra mods.  

Sorry in advance if I missed something obvious or something, I'm not used to installing mods outside of Workshop :p

**Comment by LoneGazebo** [comment]
Are you using the copies of CSD and C4DF that are made for the CBP?
Also, did you delete the necessary lua folders from the CP and CBP once you've installed the non-EUI compatibility files?
G
