### ISSUE TITLE
Great Lighthhouse don't grant Navigator I to Dromon

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#4770]
_1. Mod version (i.e Date - 4/23):_
Latest hotfix

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Neither already existing or new created. It works with Trireme.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
That's correct, Navigator I is a melee naval unit promotion.

**Comment by Mitchsp** [comment]
It's technically possible then maintain the original promotion for Great Lighthouse (so it can still benefit melee and ranged ships) and make it block Navigator II (to avoid excessive +movement bloating)?

**Comment by bigcat88** [comment]
Yeah, was disappointed when saw this in my game. Description says: "all military naval units" and it works only on melee. :(

**Comment by TechpriestEnginseer** [comment]
Mhmm, this is a balance nerf. Not a technical bug.
