### ISSUE TITLE
AI Still Declares War On Vassals

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#4771]
_1. Mod version (i.e Date - 4/23):_
9-25-1

_2. Mod list (if using Vox Populi only, leave blank):_
![capture](https://user-images.githubusercontent.com/19291347/46182086-b823bc00-c297-11e8-80ea-f40a537f7a3c.PNG)

_3. Error description:_ 
AI declares war against a vassal and then peaces out next turn.

![capture](https://user-images.githubusercontent.com/19291347/46182103-da1d3e80-c297-11e8-806e-3b13a7ab488f.PNG)
![capture](https://user-images.githubusercontent.com/19291347/46182121-ebfee180-c297-11e8-8e8b-f6d05826cd83.PNG)

**Comment by LoneGazebo** [comment]
Pictures don't help, need logs.

G

**Comment by jimmymcperson** [comment]
In this save, Germany declares war on Russia's vassal Portugal.

[Logs.gz](https://github.com/LoneGazebo/Community-Patch-DLL/files/2426441/Logs.gz)
