### ISSUE TITLE
Massive unhappiness drop

### ISSUE THREAD

**Issue by SpankMyMetroid** [LoneGazebo/Community-Patch-DLL#4772]
_1. Mod version (i.e Date - 4/23):_
9-15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
https://forums.civfanatics.com/threads/sooo-happiness.631678/page-8#post-15227637

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[turn311logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2426400/turn311logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[AutoSave_0310 AD-1880.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2426389/AutoSave_0310.AD-1880.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
I believe this has been resolved at the latest version...
