### ISSUE TITLE
Liberate CS from barbarians

### ISSUE THREAD

**Issue by prosaiccode** [LoneGazebo/Community-Patch-DLL#4773]
_1. Mod version (i.e Date - 4/23):_
9 something (just downloaded it 3 days ago)

_2. Mod list (if using Vox Populi only, leave blank):_
EUI (without 6)

_3. Error description:_ 
Can't liberate city state after it being conquered by barbarians 100 turns ago.

_4. Steps to reproduce (optional):_
Raging Barbarians on Highland (ridgeline, dense), play as Inca (this will isolate the issue easier).
Explore the map
Wait for CS to get conquered.
Wait some more.
Attack the barbarians!

[Pachacuti_0197 AD-1370.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2426670/Pachacuti_0197.AD-1370.zip)

Side note, I have Alhambra and none of my pikes / spears / knights / elephants received Drill 1. (It's in the second city)

**Comment by TechpriestEnginseer** [comment]
Have you conquered the CS beforehand?

**Comment by TechpriestEnginseer** [comment]
The save game, unfortunately, doesn't tell me if you met the CS in the past or conquered it beforehand(which is the case to why you can't usually liberate city-states), and the OP seems to have been unresponsive. Closed.
