### ISSUE TITLE
Stuck on Policy Selection

### ISSUE THREAD

**Issue by cskimpel** [LoneGazebo/Community-Patch-DLL#4774]
_1. Mod version (i.e Date - 4/23):_
9/15

_2. Mod list (if using Vox Populi only, leave blank):_
Only Vox Populi 1,2,3,4,5,6a and Tometehk's Summer for VP

_3. Error description:_ 
This has happened to me twice in different starts, but only when I get awesome starting locations and am excited about the game: I get to the first policy selection, select a policy, close the policy screen and the somehow the selection was not registered, so I cannot continue to the next move. I can selected many more policies but none trigger policy was selected event or whatever it does to signal that I did complete a selection. I have had two games that worked as always. This might be a CIV 5 bug, but I am up to date on CIV 5 patches believe and I think that bug was fixed a long time ago in CIV 5.

_4. Steps to reproduce (optional):_
Load one of the saved games and complete a turn or two until the policy selection is granted. Select a Policy. Try to end that turn.
[CivCBP9-15-PolicyBug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2429088/CivCBP9-15-PolicyBug.zip)

[AutoSave_0037 BC-2520.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2429095/AutoSave_0037.BC-2520.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
I'm aware that Tomatekh's Sumer has an issue with policies issue...
