### ISSUE TITLE
Unselectable choice in Eclipse event

### ISSUE THREAD

**Issue by Zarrk** [LoneGazebo/Community-Patch-DLL#4775]
_1. Mod version (i.e Date - 4/23):_
Vox Populi (9-25-3) No-EUI

_2. Mod list (if using Vox Populi only, leave blank):_
(7) Community Events (v 4)
(8) Events and Decisions (CBO) (v 14)
Really Advanced Setup (v 15)
Ingame Editor (v 39)
some UI elements from WHoward collection (so nothing related to the event system)

_3. Error description:_ 
Despite having the prerequisite for the second choice: Pantheon, not researched Theology and having in the city's foodpile more food than the choice cost (still ancient time), i'm unable to select the option to "Quick make a sacrifice", and the tooltip is unable to explain why. All others choices works when I unlock the correcponding Tech, the tooltip event warns me the second option become locked after unlocking Theology. Can't seems to find what's wrong here. 

_4. Steps to reproduce (optional):_

**Comment by TechpriestEnginseer** [comment]
I keep forgetting but the pantheon is bugged, you have to have a national majority as your pantheons.

**Comment by Zarrk** [comment]
Turn 79, still no religion in the game, there are 11 followers out of a total population of 15 and in the capital 5 of 7.  So I don't think it's a pantheon majority problem.

**Comment by TechpriestEnginseer** [comment]
Interesting well for the second choice of Eclipse, you need...

25 Food in the Capital(and City).

**Comment by TechpriestEnginseer** [comment]
I'm thinking it's because they try to take 25 food out of all your cities, but this shouldn't be the problem...

**Comment by Zarrk** [comment]
I tried lowering the cost value to 1 and/or changing from food to gold, but it dindn't work (except for the tooltip updating).

Dropping the 'RequiresPantheon' flag produced also no result.

I swapped 'EventChoice_EventCostYield and 'EventChoice_InstantYield' for PLAYER_EVENT_ECLIPSE_CHOICE_1' and 'PLAYER_EVENT_ECLIPSE_CHOICE_2', it still didn't allow me to select the sacrifice option but by choosing the default option it effectively traded 25 food (only) in the capital for 50 faith. So the problem is indeed elsewhere.

In the end I grow tired and decided to continue my game but ended overwriting by mistake the save of the turn the event fired.

**Comment by TechpriestEnginseer** [comment]
You can't exactly make changes in a save game.

**Comment by TechpriestEnginseer** [comment]
It's because it checks for all food in every cities.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer is that a bug or a feature? Not sure what's being used for the code.

**Comment by TechpriestEnginseer** [comment]
Player Event used to check for just the Capital's food/production, but if you don't enable the capitaleffectonly, then it'll check for all cities' food and production.

**Comment by RecursiveVision** [comment]
Fixed now.
