### ISSUE TITLE
GameEvent.PlayerCanPropose on Enacted Sphere of Influences and Enacted Open Doors

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4776]
After doing a few more print tests, I've noticed that these two resolutions are "picked up" in being unable to be restricted once they are enacted.

````
function Nonono(iPlayer, iResolution, iChoice, bEnact)
	if iResolution == GameInfoTypes.RESOLUTION_SPHERE_OF_INFLUENCE then
		return false
	end
	return true 
end

function Nonono2(iPlayer, iResolution, iChoice, bEnact)
	if iResolution == GameInfoTypes.RESOLUTION_OPEN_DOOR then
		return false
	end
	return true 
end

GameEvents.PlayerCanPropose.Add(Nonono)
GameEvents.PlayerCanPropose.Add(Nonono2)
````
When I apply this code, then I should assume that all resolutions of Open Door Policy and Sphere of Influence, whenever enacted or not, should be unable to be proposed.

But when testing this simple function, all enacted resolutions of Open Door Policy and Sphere of Influence are still able to be proposed, while the un-enacted versions are unproposable. This lead me to do some testing with PlayerCanPropose and the results were shocking with this code:

````
function Nonono3(iPlayer, iResolution, iChoice, bEnact)
	if iResolution == GameInfoTypes.RESOLUTION_OPEN_DOOR or GameInfoTypes.RESOLUTION_SPHERE_OF_INFLUENCE then
		print("The iPlayer in question is... " .. iPlayer)
		print("The iChoice in question is... " .. iChoice)
		print(bEnact)
		return true 
	end
	return true 
end

GameEvents.PlayerCanPropose.Add(Nonono3)
````
This code should pick up on all possible SoI and OD resolutions and print them out, but when it came to the enacted resolution in question, it never picked them up making me wonder if they exist at all!

**Comment by TechpriestEnginseer** [comment]
Yikes.

**Comment by LoneGazebo** [comment]
All ok?

**Comment by TechpriestEnginseer** [comment]
Not that huge of a concern was going to make a mod that prevents proposing the same resolution twice, but if I can't grab those enacted SoIs/ODs (shrug), it might be the same for grabbing enacted banned luxuries as well. Unsure.
