### ISSUE TITLE
CTD when hovering over happiness

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#4777]
_1. Mod version (i.e Date - 4/23): 5-20

_2. Mod list (if using Vox Populi only, leave blank):_ Many mods, but mostly QOL

_3. Error description:_ 

I get a CTD when I hover over the happiness overview in the top bar. Epic, huge PerfectWorld3 map. I am in the Modern era. Possibly some sort of memory overflow.

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2430994/CvMiniDump.zip)

**Comment by TechpriestEnginseer** [comment]
I can't replicate even with your mod list.

**Comment by TwoPodRay** [comment]
I had something similar happen about a month and a half ago when I was playing the 5/20 patch. I was doing Marathon/Huge/22Civs and had close to 1000 happiness at that point in Information Era. I wanted to take a screenshot while hovering over happiness to see all the sources to ask if my happiness should really be that high but my game started CTDs and then I couldn’t load the game long enough to even take a screenshot. It would load in then CTD if I even moved the screen at all.

**Comment by Vyyt02** [comment]
Yeah, I am in a prolonged war and I have already conquered over half of the world and each source of unhappiness goes to tens, sometimes over a hundred. When subtracted from the total happiness, my current result/total happiness is exactly -1.

The rest of the game seems to be running fine, the city happiness breakdown (when hovering over the city banner) is working, the top bar happiness also updates when I shuffle around specialists, etc., so I think it is only affecting the happiness breakdown. Oh, and I am using EUI.

**Comment by Vyyt02** [comment]
After several turns, the happiness breakdown stopped CTDing and started to work properly again. Gazebo, do you need anything else than the Civ dump?

**Comment by Vyyt02** [comment]
And after a few more turns, hovering over the happiness in the top bar started CTDing again.

**Comment by TechpriestEnginseer** [comment]
I'm assuming your Lua.log is needed since you have an overflow of integers somewhere... or an overcalculation causing late games to crash.

**Comment by Vyyt02** [comment]
Thanks, I will upload the Lua log once I get to play the game. Don't know what the 4 GB patch is...?

**Comment by briantjack** [comment]
I would like to know about the 4GB patch, too.

I've googled the internet and searched CivFanatics, only to learn that Civ 5 appears to have a 4GB-limit for virtual memory. However, no one else has mentioned a direct fix for the issue.

**Comment by supermerill** [comment]
that?

https://forums.civfanatics.com/threads/increase-memory-on-64bit-machines.544026/

**Comment by TechpriestEnginseer** [comment]
Supposedly... as it has LAA to detect it, but the 4GB patch would just force it to go 4 GB instead of 'detecting' and possibly failing the 'detection' logic.

**Comment by Vyyt02** [comment]
Sorry for the long silence, have been away on a business trip. Here is the LUA log. Lots of icon errors - does it make any sense to you guys?

[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2550366/Lua.log)
