### ISSUE TITLE
Dauntless promotion is healing when damage is <5

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#4779]
_1. Mod version (i.e Date - 4/23):_
Latest

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
You sure you're on the hotfix?

**Comment by Mitchsp** [comment]
Yes, using [this](https://forums.civfanatics.com/threads/new-beta-version-september-25th-9-25.636800/page-3#post-15227808)  and almost sure it's a new game started after the patch, not a previous save.
Will test after the work with IGE in a new game.

**Comment by Mitchsp** [comment]
Tested, happening in a new game with last hotfix.

**Comment by bigcat88** [comment]
I see the same in my game, I cant kill Arabia trireme...

**Comment by TechpriestEnginseer** [comment]
Has this been replicated now or no?

**Comment by LoneGazebo** [comment]
Should be fixed.
