### ISSUE TITLE
Harbor not establishing city connection

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#478]
Is happening with two cities, both with clear sea route to capital, having waiting 10+ turns, closing the game and clearing cache during the process. One land route in another city worked right.
In previous versions never had problems with sea connections.

**Comment by LoneGazebo** [comment]
I'll take a look. Issue is already known (somewhat).
G

**Comment by Mitchsp** [comment]
Now (8-6) they're giving city connections, but not gold from that connection, at least with free harbors from Carthage.
