### ISSUE TITLE
Cultural Victory Explanation

### ISSUE THREAD

**Issue by TwoPodRay** [LoneGazebo/Community-Patch-DLL#4781]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

We’ve changed the requirements for Cultural Victory a few times now but I can’t seem find any explanations for how to achieve it in game or in the civilopedia in game. While I know what the requirements are, there are still very frequent reports from folks who are either new to VP or recently updating to a newer version of VP who do not have an indication of how to finish a cultural victory after becoming influential with everyone. Suggest adding a description in civilopedia, in the CEP text, maybe somewhere related to ideologies, etc. to make that more clear.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ryanmusante** [comment]
I think maybe one of the things some of us could do is fork VP, make the edits and do pull requests for simple things like this. I might start doing that on my days off on the weekends to help out.

**Comment by TwoPodRay** [comment]
I’d be happy to pitch in when I have time, but I’d worry that might create config management issues for the integrator (i.e. Gazebo). Yeah I noticed that, quite funny!

**Comment by MoiMagnus** [comment]
I think it sould also be present in the "victory pannel". When you influence everyone, it should not say "Victory possible", it should say "Citizen Earth Protocol required for victory" or something like that.

**Comment by TechpriestEnginseer** [comment]
I believe it's you need 2 ideology tier 3 tenet to build the Citizen Earth Protocol.
