### ISSUE TITLE
[Tooltip]

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#4783]
Naga-Malla Indian Elephant's tooltip states that it cannot move after attacking, but it does in fact have this promotion! Not sure which way round it should be, probably it should move as it currently does?

**Comment by TechpriestEnginseer** [comment]
It's a ranged(mounted) unit...

Hmm..

**Comment by LoneGazebo** [comment]
It should. Just a wrong TT.
