### ISSUE TITLE
Steam Mill has 3 base hammers instead of 5

### ISSUE THREAD

**Issue by chicorbeef** [LoneGazebo/Community-Patch-DLL#4784]
1. Mod version (i.e Date - 4/23):9/25

3. Error description: Steam Mill has 3 base hammers instead of the 5 the Factory has. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Some UB may not get buffed from its replacements' buffs simply because it's stronger than it is already.

(Steam Mill will automatically out-produce on any cities with 5 citizens compared to a Factory)

Usually, however, he would leave a note for this kind of change...

**Comment by TechpriestEnginseer** [comment]
But in other cases, he didn't!
