### ISSUE TITLE
Infinite Great Diplomat generation

### ISSUE THREAD

**Issue by xxaidasxx** [LoneGazebo/Community-Patch-DLL#4786]
Downloaded yesterday through the recommended installer (10/05)

Mod List: 
 Vox Populi (EUI)
1. Wonders Expanded (VP)
2. Community Events
3. City States Evolved
4. Wonder Race
5. Info Addict
6. Greatest Cities
7. R.E.D Modpack
8. Extra Victory Conditions

 About turn 50 the game starts infinitely generating Great Diplomats, because they have millions of great people points (Doesn't happen with other great people, only Great Diplomats)

**Comment by bigcat88** [comment]
Try disabling some mods, looks like mod conflict.
And what is the version 10/5?
Current version 9-25...
https://forums.civfanatics.com/threads/new-beta-version-september-25th-9-25.636800/

**Comment by xxaidasxx** [comment]
> Try disabling some mods, looks like mod conflict.
> And what is the version 10/5?
> Current version 9-25...
> https://forums.civfanatics.com/threads/new-beta-version-september-25th-9-25.636800/
> or direct link:
> https://mega.nz/#F!DMsxkDYI!zSpR9CHpmAfWyIvMXaN3pw
