### ISSUE TITLE
Peacetime vassalization

### ISSUE THREAD

**Issue by Omen-of-Peace** [LoneGazebo/Community-Patch-DLL#4787]
_1. Mod version (i.e Date - 4/23):_ 09/25, latest hotfix

_2. Mod list (if using Vox Populi only, leave blank):_ only UI mods
(pza's modpack version from [here](https://forums.civfanatics.com/threads/dlc-modpack-and-43-civ-version-repository.609278/page-25#post-15230985))

_3. Error description:_ 
From one turn to the next, Egypt becomes the vassal of India though they are not at war. I believe it happened earlier in the game as well when Portugal became the vassal of India, but I didn't reload to check.
It happened earlier in a separate game as well, I think it was on the 09/19 version.

I understood that this wasn't supposed to happen anymore, that vassalization required a war score of 75 or more.

_4. Steps to reproduce (optional):_
[Saves pre and post peacetime vassalization.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2453407/Saves.pre.and.post.peacetime.vassalization.zip)

**Comment by LoneGazebo** [comment]
It can happen, anyone can ask for it.

G
