### ISSUE TITLE
Problem with city ranged combat strength vs Dromon

### ISSUE THREAD

**Issue by DoItTomorrow** [LoneGazebo/Community-Patch-DLL#4788]
_1. Mod version (i.e Date - 4/23):_
8/19-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
As can be seen the screenshot, the firepower of the city and the strength of the city do not match. When the city is not garrisoned, the RCS is 2.5 instead of 25.

_4. Steps to reproduce (optional):

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

[Screenshots.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2453653/Screenshots.zip)

**Comment by MoiMagnus** [comment]
The fact that they do not match is normal. 

This is a vanilla thing, but the UI was patched. (So in vanilla, the attack of a city was also lesser, but nobody was aware of it)

However, 2.5 seem very low.

From memory, the formula is:

CS of the city. Minus all defensive building (they don't count for attack). Then 40% of it.

Can you check if it is a bug or a balance issue?

**Comment by DoItTomorrow** [comment]
Thank you. 2.5 looks correct then (~6*0.4). All city shots become 10 dmg, so at least it's symetrical. It is however quite different from what I have come to expect having played civ 6. Was this a conscious balancing decision?

**Comment by TechpriestEnginseer** [comment]
Imagine if a city with 40 CS had to defend itself versus a fleet of the medieval era.

Your city would be one-shotting them everytime.

**Comment by DoItTomorrow** [comment]
That makes sense. I guess I was just surprised at the 2.5 RCS.

**Comment by DoItTomorrow** [comment]
I would like to request a reopening of this issue. All cities have a constant 2.5 RCS regardless of target or era. I have updated to 10-10-2, Vox with EUI (6a) and am running no other mods.

![screenshot 8](https://user-images.githubusercontent.com/43004683/47290927-48091b80-d634-11e8-81c9-57694a8f5e81.png)
[AutoSave_0092 BC-2620.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2501203/AutoSave_0092.BC-2620.zip)
