### ISSUE TITLE
Air units (not) attacking ships

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#4789]
_1. Mod version (i.e Date - 4/23):_
9-25

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Fighters&heavy bombers cannot attack ships, neither can helicopter gunships.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
It is only when they are low HP with promotion for health.(in my game)

**Comment by bigcat88** [comment]
My heavy bombers\fighters can attack anything, except low level melee ships.(don't check on submarines)

P.S.: Heavy bombers still can still be upgraded on aircrafts... :(

**Comment by bigcat88** [comment]
Looks like UI don't allow me to attack. EUI thinks that ship has 0 hp points.
![20181008200334_1](https://user-images.githubusercontent.com/13381981/46623157-6bf93700-cb35-11e8-8039-b96f9fb81cc3.jpg)
And a second small proof(updated heavy bomber(stealth) on aircraft):
![20181008200527_1](https://user-images.githubusercontent.com/13381981/46623203-8df2b980-cb35-11e8-9b2b-44e504335899.jpg)

**Comment by matlajs** [comment]
Having this problem too.
