### ISSUE TITLE
The Netherlands and monopoly calculation bug

### ISSUE THREAD

**Issue by den9** [LoneGazebo/Community-Patch-DLL#4793]
_1. Mod version (i.e Date - 4/23):_
9-19

_2. Mod list (if using Vox Populi only, leave blank):_
only ui/info

_3. Error description:_ 
I bought from Inca 5 copies of lapis lazuli out of 9 total, got 55% monopoly but it still says "potential" and no bonus given.

Still only potential even if buy all 9 out of 9.  All copies bought one after another, on same turn as peace treaty with Inca made (since it is cheap on this turn).

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[monopoly_bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2454312/monopoly_bug.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20181007232655_1](https://user-images.githubusercontent.com/1615968/46586699-b671a980-ca8a-11e8-9bc7-ff366e2fd41e.jpg)
![20181007232742_1](https://user-images.githubusercontent.com/1615968/46586700-b70a4000-ca8a-11e8-970d-601d3244d1b4.jpg)
![20181007232746_1](https://user-images.githubusercontent.com/1615968/46586701-b70a4000-ca8a-11e8-8bc1-312e84304d8d.jpg)

**Comment by TechpriestEnginseer** [comment]
Isn't it a monopoly bug then? Since the overview is supposed to show who has the monopoly bonus, not if the Netherlands has an equivalent bonus to the civ with the monopoly.

**Comment by den9** [comment]
no, if you change to "all" in "select player" it indeed shows that Inca has 120% monopoly.

**Comment by TechpriestEnginseer** [comment]
Mhmm ofc.

**Comment by ryanmusante** [comment]
Aren't the lake Victoria, Gibraltar fixes incorporated into community patch? I think you can remove those from your mods.
