### ISSUE TITLE
Allied maritime city states not granting food properly

### ISSUE THREAD

**Issue by SpankMyMetroid** [LoneGazebo/Community-Patch-DLL#4794]
_1. Mod version (i.e Date - 4/23):_
9/25 (w/hotfixes)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Allied maritime city states don't seem to be granting the intended food to either the capital or other cities. In the capital, 4 food from CS's is given based on the UI (which doesn't seem to relate to anything, I'm allied with 2 maritime, friends with 1). No food is granted at all in other cities based on the city screen. Based on the yields given, 29 food should be given to the capital (11x2 from allies, 1x7 from the friend) There IS 29 "unaccounted" food on the capital city tile (see the screenshot; 24 is granted by statecraft opener) but the math doesn't add up since Athens has other buildings that grant food (water mill, grocer, etc). Regardless, the other city tiles in other cities don't seem to have extra food on them. 

_4. Steps to reproduce (optional):_
Greece, epic, authority->statecraft->imperialism

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[wheres the food.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2454773/wheres.the.food.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20181008011441_1](https://user-images.githubusercontent.com/20096768/46593561-0ce6e400-ca9b-11e8-9e30-1f429980e7c9.jpg)
![20181008011507_1](https://user-images.githubusercontent.com/20096768/46593565-11130180-ca9b-11e8-9a2d-446fbead765f.jpg)
![20181008011544_1](https://user-images.githubusercontent.com/20096768/46593566-14a68880-ca9b-11e8-8cb3-88011c390ed1.jpg)
![20181008011546_1](https://user-images.githubusercontent.com/20096768/46593570-1b350000-ca9b-11e8-8b3f-bb060402c970.jpg)
![20181008013022_1](https://user-images.githubusercontent.com/20096768/46593576-212ae100-ca9b-11e8-98db-0275def0ee14.jpg)

**Comment by TechpriestEnginseer** [comment]
Because the food is added to your capital's, city's tiles???

**Comment by SpankMyMetroid** [comment]
Right, that math does check out, sorry (I counted building food incorrectly). But where does the '4 food from city states' come from in the first screenshot of Athens.

**Comment by TechpriestEnginseer** [comment]
I believe Scrienver's Office does that granting +1 per ally.
