### ISSUE TITLE
Colonia and Town

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4797]
Is the code for extending a Great Merchant's WLTKD turns hardcoded to Colonia and Town or can it detect additional improvements?

And does this apply to all the same GP improvements in applying more production/science from other "types" of manufactories and academies?

**Comment by LoneGazebo** [comment]
Uses the Unit_ScalingFromOwnedImprovements table.

**Comment by LoneGazebo** [comment]
(which accommodates multiple improvements)
