### ISSUE TITLE
Joining a joint war triggers war on the one offering to go to war

### ISSUE THREAD

**Issue by Rafs041** [LoneGazebo/Community-Patch-DLL#4801]
_1. Mod version (i.e Date - 4/23):_
10/10 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
(Just turned the standard mod into a Modpack)

_3. Error description:_ 
The incas offered me to go to war against germany, I said ok lets get this war started as I had a DOF with the incas, and apparently I'm declaring war on the incas instead of germany when pushing the button.

_4. Steps to reproduce (optional):_
Left a save, just need to end the turn, pachacuti will suggest going to war against bismark.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2468696/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Ahmad al-Mansur_0320 BC-0300.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2468690/Ahmad.al-Mansur_0320.BC-0300.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TwoPodRay** [comment]
Did the Inca have a Def pact with Germany?

**Comment by Rafs041** [comment]
No, everyone is still in classical, so no defensive pacts yet (I did check everything at first because it was such a weird issue)

**Comment by NewFellow** [comment]
I got the same problem here. Montezum want us to declare war against Poland, but instead we go to war with eachother!

**Comment by LoneGazebo** [comment]
Was fixed in hotfix

**Comment by NewFellow** [comment]
uhm, strange, I'm using 10-10-1, if that was the hotfix.

**Comment by Questdog** [comment]
I am on 10-10-2 and this just happened to me twice in 10 turns before I realized it.

**Comment by LoneGazebo** [comment]
Ah I see, I misread a prior bug report. Fixed for next version.
