### ISSUE TITLE
Prophet Spawning in Odd Locations

### ISSUE THREAD

**Issue by feariguodala** [LoneGazebo/Community-Patch-DLL#4803]
_1. Mod version (i.e Date - 4/23):_
10-10-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Great prophet spawning in city that isn't the Capital. City it spawned in has no natural wonders giving it faith and no shrine. I have no shrines at all since I'm playing Aztec this game. Happened last game as well playing Rome. In that game it spawned in a city with a shrine but still way behind the Capital in faith generation since it was a newer city. 

_4. Steps to reproduce (optional):_
To get the necessary faith for the prophet to spawn on the next turn capture Rabat. Killing the warrior inside the city gives the necessary faith. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2471071/Logs.zip)

. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
I believe it's because the faith generated are in a nearby city and the GP logic accounts for that.

It's no bug really just historical flavor.

**Comment by feariguodala** [comment]
Unfortunately I don't have my Rome save because the prophet didn't spawn in my 2nd strongest faith generating city. It spawned in the 4th city I built that had only just completed its shrine 2 turns prior to the prophet spawning.

**Comment by LoneGazebo** [comment]
It is randomized and weighted by faith. No bug.
