### ISSUE TITLE
No Gold from Tithe

### ISSUE THREAD

**Issue by Questdog** [LoneGazebo/Community-Patch-DLL#4806]
_1. Mod version (i.e Date - 4/23):_10/10-1

_2. Mod list (if using Vox Populi only, leave blank):_Bunch of UI mods; no gameplay mods

_3. Error description:_ Tithe is not giving me any gold at all in any of my cities.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![nogold2](https://user-images.githubusercontent.com/34197686/46899411-08d31180-ce61-11e8-9a35-17cd8844427c.png)

**Comment by NewFellow** [comment]
Tithe? I'm having that problem when picking the belief "thrift". I then won't be getting any gold at all.

**Comment by Zealot81** [comment]
You mean Thrift, not Tithe? If so, let's close this ticket - I opend one on Thrift.
