### ISSUE TITLE
Fix: Unit SelectionSound (10/10-1)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#4807]
https://github.com/LoneGazebo/Community-Patch-DLL/blob/3e2c015aae2bb8cd5878bd5622559b0a15951b30/Community%20Patch/Core%20Files/Core%20Changes/CoreChanges.sql#L1394-L1408

**FirstSelectionSound** should be **AS2D_BIRTH_******.

Like this

```
UPDATE UnitGameplay2DScripts
SET FirstSelectionSound = 'AS2D_BIRTH_WARRIER', SelectionSound = 'AS2D_SELECT_WARRIER'
WHERE UnitType = 'UNIT_BARBARIAN_WARRIOR';

UPDATE UnitGameplay2DScripts
SET FirstSelectionSound = 'AS2D_BIRTH_CANNON', SelectionSound = 'AS2D_SELECT_CANNON'
WHERE UnitType = 'UNIT_GATLINGGUN';

UPDATE UnitGameplay2DScripts
SET FirstSelectionSound = 'AS2D_BIRTH_FRIGATE', SelectionSound = 'AS2D_SELECT_FRIGATE'
WHERE UnitType = 'UNIT_PRIVATEER';

UPDATE UnitGameplay2DScripts
SET FirstSelectionSound = 'AS2D_BIRTH_MUSKETMAN', SelectionSound = 'AS2D_SELECT_MUSKETMAN'
WHERE UnitType = 'UNIT_SWEDISH_CAROLEAN';
```

Edit

After that, you have to delete these lines.
https://github.com/LoneGazebo/Community-Patch-DLL/blob/3e2c015aae2bb8cd5878bd5622559b0a15951b30/Community%20Balance%20Patch/Balance%20Changes/Leaders/BraveNew/BNWLeaderChanges.sql#L569-L571

**Comment by ryanmusante** [comment]
Is WARRIER a misspelling of WARRIOR?

**Comment by TechpriestEnginseer** [comment]
Since it's Firaxis's creation, we don't edit it since someone else could be using that as a reference and deletion tends to break mods.

**Comment by 8h42** [comment]
WARRIER is an "official" misspelling.
We have to use it.

cf. Sid Meier's Civilization V\Assets\Sounds\XML\AudioDefines.xml
Line: 505-511
```
    <SoundData>
      <SoundID>SND_BIRTH_WARRIER</SoundID>
      <Filename>BirthWarrior</Filename>
      <bDontCache/>
      <bOnlyLoadOneVariationEachTime/>
      <LoadType>DYNAMIC_RES</LoadType>
    </SoundData>
```

**Comment by TechpriestEnginseer** [comment]
Why do we have to delete it? I believed Barbarian Warriors have a AS2D error when you don't do it.

**Comment by 8h42** [comment]
It is duplicated (CP and CBP).

As a side note, it also has a wrong UnitGameplay2DScripts.
`SET FirstSelectionSound = 'AS2D_SELECT_WARRIER', SelectionSound = 'AS2D_BIRTH_WARRIER'`
should be
`SET FirstSelectionSound = 'AS2D_BIRTH_WARRIER', SelectionSound = 'AS2D_SELECT_WARRIER'`

**Comment by TechpriestEnginseer** [comment]
Okay.
