### ISSUE TITLE
Siam's Interesting UA..

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4809]
![image](https://user-images.githubusercontent.com/13937047/46911151-32934380-cf08-11e8-8139-676d918ef776.png)

Was this removed?

**Comment by MoiMagnus** [comment]
Same question for other hidden features? (Like Khan healing air units?)

**Comment by LoneGazebo** [comment]
Hmm?

**Comment by TechpriestEnginseer** [comment]
Does the hidden bonus still apply to them in Vox Populi or was that removed?

(Like Greeks able to trespass onto non-friendly city-states for free)

**Comment by TechpriestEnginseer** [comment]
Does the hidden bonus still apply to them in Vox Populi or was that removed?

(Like Greeks able to trespass onto non-friendly city-states for free)
