### ISSUE TITLE
Indonesia luxuries overwrite strategic resources

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#481]
![8930_2015-07-31_00005](https://cloud.githubusercontent.com/assets/1131228/9011798/20ccbe80-37c9-11e5-86ff-6b54cc1353f7.png)
This spot had uranium in it, but now is replaced with Pepper.

**Comment by LoneGazebo** [comment]
Was the resource there before you founded the city? I'll make sure it can't overwrite.

**Comment by Radost** [comment]
![8930_2015-08-01_00001](https://cloud.githubusercontent.com/assets/1131228/9015610/8461c34a-37e3-11e5-80ae-a553da0a65e6.png)

**Comment by XplosiveLun** [comment]
Did you build the Candi before the resource disappeared? Candi spawn resource after built. Occasionally, the Indonesia resource spawned by Candi will appear under the city (and possibly overlap the current resource under the city?). Maybe this is the case?

**Comment by Radost** [comment]
There is no other way to have 2 luxuries in a city range without building a candi.

**Comment by XplosiveLun** [comment]
I know city don't have 2 luxuries without a Candi.

At turn 577, your city has "a" Uranium resource and you have 6 in stock.
At turn 582, it changed to Pepper and +1 gold yield. You still have 6 Uranium. Do you still remember during that period, have you built a uranium mine?

I hope that could lead to further discussion and help Lord G identifying the problem.

**Comment by Radost** [comment]
I got additional sources of uranium from city-states in-between this period. And Aracaju isn't shown as one providing it anymore.
