### ISSUE TITLE
No gold from Thrift (follower belief)

### ISSUE THREAD

**Issue by Zealot81** [LoneGazebo/Community-Patch-DLL#4810]
_1. Mod version (i.e Date - 4/23):_10-10-1

_2. Mod list (if using Vox Populi only, leave blank):_UI only

_3. Error description:_ No gold from Thrift (follower belief). Please Hotfix, I need it in my game ;). And thanks for everything.

_4. Steps to reproduce (optional):_I guess this has something to do with the latest Thrift changes (cup at 15 followers, not 10).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by NewFellow** [comment]
Same here. I reloaded and picked something else. :)
