### ISSUE TITLE
[UI Feature Request] Add a Notification for When Reformation is Possible

### ISSUE THREAD

**Issue by chicorbeef** [LoneGazebo/Community-Patch-DLL#4812]
1. Mod version: 10/10

3. Feature Request: I just wanted to know whether it is possible to add a notification for when you reach sufficient religious followers to reform (perhaps with an added description instructing players to build the Religious Wonder). Thanks!

**Comment by TechpriestEnginseer** [comment]
Not sure what is Gazebo's response to this, but I'll make a quick UI modmod.
