### ISSUE TITLE
UI questions

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4813]
back in town!

so i tried the 10/10 version, noticed some changes ...

1. this is a bomber attacking an ironclad. what does "status effect change 100%" mean?

![image](https://user-images.githubusercontent.com/1358966/46969448-5a280e80-d0b6-11e8-94a5-314eedec15bb.png)

2. how am i supposed to read this new happiness indicator? what does 83 / 203 mean?

![image](https://user-images.githubusercontent.com/1358966/46969788-78423e80-d0b7-11e8-8e18-2745f788feae.png)

also, the 760 pop for the next luxury level seem very much out of reach - i know that was discussed before, but what needs to be done to allow fractional values here? for example, how about luxuries simply give you max(1,n*pop/50) happiness? (n is the number of unique luxuries)

**Comment by LoneGazebo** [comment]
Hey! 

1.) The chance that the ironclad's 'boarding party' promotion will inflict a promotion on the bomber. In that case it actually shouldn't happen (though I like the idea of a boarding party from a ship engaging in melee with an airplane). It's just a UI quirk.

2.) 83 unhappy citizens, 203 happy citizens. Some players asked for this on the top bar.

3.) Others have discussed this as well - the existing function (IIRC) is exponential, may make sense to move to a more smoothed curve.

**Comment by TechpriestEnginseer** [comment]
Don't you mean 83 unhappy citizens out of 203 citizens?

**Comment by LoneGazebo** [comment]
Sorry yes 83/203 total citizens.

**Comment by TechpriestEnginseer** [comment]
soo the icon should be changed to [icon_citizen]

**Comment by LoneGazebo** [comment]
probably yeah - would probably suffice to remove the first [icon_citizen] and just show the two values

**Comment by ilteroi** [comment]
it seems to me that CvPlayer::GetBonusHappinessFromLuxuries() should be very easy to adapt to a new model. The only question is balance - which percentage of your population should a single luxury make happy? And is this a constant or does it very with player traits, policies etc?

**Comment by LoneGazebo** [comment]
Regarding luxuries, it’d probably be worth tossing a question into the forums. See what they think. The problem is that +1 happiness per luxury can make a big jump!

**Comment by ilteroi** [comment]
no worries about jumps - look at the graph - rounding happens only after multiplication.

but: if i make this change, i will break your UI. hope that's ok for you ... in the first step i'll leave the old lua methods in but replace them with stubs.

**Comment by LoneGazebo** [comment]
Just let me know what you’ve done so I can explain it via a tooltip.

**Comment by ilteroi** [comment]
ok, it's done. i fixed the lua myself ...

![image](https://user-images.githubusercontent.com/1358966/47181138-88118b00-d322-11e8-9988-953b82a056a1.png)

but why does brazil get one extra happiness per luxury?

**Comment by LoneGazebo** [comment]
@ilteroi is that from Industry finisher?

**Comment by ilteroi** [comment]
maybe ... i need to check

**Comment by ilteroi** [comment]
you're right, it's the industry finisher. i hadn't thought of that.

anyway as it works right now, this is an ineffective policy because because the bonus happiness only applies when it exceeds the base happiness from resources.

so any increase in "base resource happiness" is compensated by a decrease in "luxury bonus happiness" at the moment. no net change, assuming you cities are large enough (which the should be by the point you finish industry).

if course i could change this, but it needs balancing. well it needs some balancing in any case i guess. right now you can get 100 bonus happiness in the late game easily. is that too much?

should it be linear in the number of luxuries or is there maybe some saturation (ie the n-th luxury is less effective than the 1 first)?

**Comment by LoneGazebo** [comment]
That policy should just give you an extra happiness over the base value of a luxury (1). Is it not doing that?

**Comment by ilteroi** [comment]
misunderstanding. the industry finisher is working. it's just that the way i calculated the bonus happiness would counteract it. but that's history, i just pushed another small update.

![image](https://user-images.githubusercontent.com/1358966/47236875-b0aa8b00-d3dd-11e8-9e0b-0e005dde8415.png)

overall happiness seems to be pretty much balanced.

**Comment by LoneGazebo** [comment]
Looks nice. The change I made to static values for medians for cities helped quite a bit. That and the new lux scaler should solve the problem for good.

**Comment by ilteroi** [comment]
done
