### ISSUE TITLE
Mission gold yield bug

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#4816]
_1. Mod version (i.e Date - 4/23):_
25/9

_2. Mod list (if using Vox Populi only, leave blank):_
Suppose it is either tooltip issue, or bug. I get really weird yields upon citizen birth from mission. It is neither 1x, nor 3x. it is close to be 2x but not precisely.  Note, that i have progress tree filled.

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![toledo1](https://user-images.githubusercontent.com/21192402/47033343-d719bd80-d174-11e8-8f2e-c64f7c5aaa19.jpg)
![toledo2](https://user-images.githubusercontent.com/21192402/47033345-d719bd80-d174-11e8-98bd-3130ad240d71.jpg)

**Comment by LoneGazebo** [comment]
The value is a factor of production not a flat value.

**Comment by matlajs** [comment]
ok, thank you
