### ISSUE TITLE
Range land units cannot share tiles with other civs non combat units (melee can)

### ISSUE THREAD

**Issue by johanbest69** [LoneGazebo/Community-Patch-DLL#4817]
_1. Mod version (i.e Date - 4/23):_
10/10-2

_2. Mod list (if using Vox Populi only, leave blank):_
vp icons

_3. Error description:_ 
As in the title.  

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
the default action for ranged units is attacking. so if you just drag the unit there you will get a "declare war" popup. but if you activate movement mode first (press M key) it works fine.

**Comment by LoneGazebo** [comment]
@ilteroi we disabled the drag to move for DOW didn’t we?

**Comment by ilteroi** [comment]
i didn't ...

**Comment by LoneGazebo** [comment]
hmm

**Comment by LoneGazebo** [comment]
Someone else was reporting that moving a unit on top of an enemy unit no longer has the DOW popup, and I thought that was because we removed it? Am I crazy?

**Comment by johanbest69** [comment]
Yep,  tested it will not DOW with melee but will with range, so that's why i couldn't walk over the civ unit.  Have to use the manual M move as ilteroi suggests.

Is nice to be able to just drag the units over their civilian units.
