### ISSUE TITLE
Authority "Honor" will spawn only 1 unit for city that already has 20 units

### ISSUE THREAD

**Issue by johanbest69** [LoneGazebo/Community-Patch-DLL#4819]
_1. Mod version (i.e Date - 4/23):_
10/10-2

_2. Mod list (if using Vox Populi only, leave blank):_
vpicons

_3. Error description:_ 
As in title. Was tested with city with exactly 20units , not sure if applies for 20+. If I keep the city on 19 till I get honor I can then get the 2nd unit once hitting 20.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
This is correct, the bonus isn't retroactive multiple times only a single time.

**Comment by johanbest69** [comment]
Ok fair enough.  Or are you now reviewing this?

**Comment by TechpriestEnginseer** [comment]
No, I misclicked it. I assumed that conscript would go above supply cap, but it wouldn't matter since conscripted units don't count to supply cap.
