### ISSUE TITLE
City-States and Defensive Pacts

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#482]
https://www.youtube.com/watch?v=V8EaXPJEqno
At the https://www.youtube.com/watch?v=V8EaXPJEqno&t=1m54s Boudicca doesn't like that I declared a war on the CS under her protection. However, https://www.youtube.com/watch?v=V8EaXPJEqno&t=2m49s shows Cahokia, in fact, declared a war on me due to it being the ally of Korea.
Another variation of this bug is when CS declares a war on someone, and thus declares a war on everyone in the same defensive pact. AI civ will still whine about me declaring a war on their CS and these wars can be ended with peace on the same turn. Take note in this situation I wasn't at war with their ally, so those war declarations basically pop up out of nowhere.

**Comment by LoneGazebo** [comment]
I'll look at the function to make sure that the AI is looking at aggressor values when considering this. Seems like a fair change (and will reduce AI diplo spam during war, which is nice).

**Comment by LoneGazebo** [comment]
I've set the function so that the value of 'attacking a protected CS' can only be triggered if the CS has no ally or the player is the ally of the CS and the player is not at war with you.
