### ISSUE TITLE
Enemy units happily take dmg to easily pillaged citadel

### ISSUE THREAD

**Issue by johanbest69** [LoneGazebo/Community-Patch-DLL#4822]
_1. Mod version (i.e Date - 4/23):_
10/10-2

_2. Mod list (if using Vox Populi only, leave blank):_
vpicon

_3. Error description:_ 
While sieging city enemy units just stand around taking dmg without pillaging the citadel (going on for 10+ turns).  In issue #513 (2015) you said that the units will not pillage if they wish to capture the city (rather than just dmg), but this seems just wrong and took away from some of the immersion of this (amazing) mod.   (they had no chance of taking the city anytime soon either)

![20181017075812_1](https://user-images.githubusercontent.com/43484857/47049618-95772a00-d1e9-11e8-82ca-2361399e0d06.jpg)

![20181017080800_1](https://user-images.githubusercontent.com/43484857/47049622-990ab100-d1e9-11e8-9ef9-1be26e81606c.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
i'll take a look ...

**Comment by johanbest69** [comment]
Cheer!

**Comment by ilteroi** [comment]
i don't have a real test case, but i did some changes to the pillaging logic ... keep an eye out for this behavior in the next version and tell me if it got better

**Comment by johanbest69** [comment]
Ok sure thanks
