### ISSUE TITLE
New Random Seed not working

### ISSUE THREAD

**Issue by johanbest69** [LoneGazebo/Community-Patch-DLL#4825]
_1. Mod version (i.e Date - 4/23):_
10/10-2

_2. Mod list (if using Vox Populi only, leave blank):_

Have been testing for combat discrepancies so needed this to work.

Works perfectly as expected when I run a vanilla BNW game.  Load game, get totally random combat results.

With this mod , I started a new game found a barb and tried for diff combat results.  One new game it actually had 2 different results from reloading (but only ever those exact same 2 results). The other game I was only getting the one result over and over again.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Known. The primary RNG seed system for vanilla breaks in mod packs for MP. So we removed it.

**Comment by LoneGazebo** [comment]
Nay.
