### ISSUE TITLE
Project Decentralization of the AI

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4826]
```
-- OPTIONS --
-- If you have not read the instructions above, please do so now!

/* CSD Difficulty and AI Competitiveness for City-States. Higher values than '2' make the AI more interested in City-States, and more sensitive to your actions with City-States.
1 = Less Competitive (Easy)
2 = Standard (Default)
3 = More Competitive (Hard)
4 = Extremely Competitive (Very Hard)
*/
INSERT INTO CSD (Type, Value)
VALUES ('CSD_DIFFICULTY', 2);
```
I've enjoyed this particular snippet of code. It reminds us of what the Community was in its main framework in which it tried to allow users to pick and mix some of the options they didn't like (from community options), oh but we faded away from that many years ago....

However, we can still keep some of its original pick and mix options in the AI weights and flavoring as the default standard, but I think we can assign flavor values to the player's picking of a (more peaceful AI or a more warlike AI) in the game.

**Comment by LoneGazebo** [comment]
Haha. Ohh. All this does, now, is affect AI diplomatic unit desire.

**Comment by TechpriestEnginseer** [comment]
Yeah, but I'm saying we should expand beyond just unit ai diplomatic desires.

**Comment by supermerill** [comment]
Maybe we could create a set of "flavor" for each civ? for diplomatic, military, science ... 
/s
