### ISSUE TITLE
Tradition - Yields to buildingclass added via free building instead of by policy directly

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4828]
_1. Mod version: 10-10

_3. Error description: Tradition uses Building_BuildingClassYieldChanges instead of Policy_BuildingClassYieldChanges to give +2 culture to monuments/baths/gardens, and +1 science to councils and herbalists.  This causes an issue if a civ has the ability to capture buildings (Rome), because they can receive the full, global benefit of the landed elite and legalism policies. I  propose tying the buildingclass yields to the policy, rather than the building, so Rome can still get the bonus specialists and yields in city, but can't capture the full power of the policy.  

INSERT INTO Building_BuildingClassYieldChanges
	(BuildingType, BuildingClassType, YieldType, YieldChange)
VALUES
	('BUILDING_PALACE_GARDEN', 'BUILDINGCLASS_GARDEN', 'YIELD_CULTURE', 2),
	('BUILDING_PALACE_GARDEN', 'BUILDINGCLASS_BATH', 'YIELD_CULTURE', 2),
	('BUILDING_PALACE_GARDEN', 'BUILDINGCLASS_MONUMENT', 'YIELD_CULTURE', 2),
	('BUILDING_PALACE_ASTROLOGER', 'BUILDINGCLASS_GROVE', 'YIELD_SCIENCE', 1),
	('BUILDING_PALACE_ASTROLOGER', 'BUILDINGCLASS_HERBALIST', 'YIELD_SCIENCE', 1);

New version:

INSERT INTO Policy_BuildingClassYieldChanges
	(PolicyType, BuildingClassType, YieldType, YieldChange)
VALUES
	('POLICY_LANDED_ELITE', 'BUILDINGCLASS_GARDEN', 'YIELD_CULTURE', 2),
	('POLICY_LANDED_ELITE', 'BUILDINGCLASS_BATH', 'YIELD_CULTURE', 2),
	('POLICY_LANDED_ELITE', 'BUILDINGCLASS_MONUMENT', 'YIELD_CULTURE', 2),
	('POLICY_LEGALISM', 'BUILDINGCLASS_GROVE', 'YIELD_SCIENCE', 1),
	('POLICY_LEGALISM', 'BUILDINGCLASS_HERBALIST', 'YIELD_SCIENCE', 1);

**Comment by LoneGazebo** [comment]
I don’t think Rome can capture those anyways.

**Comment by TechpriestEnginseer** [comment]
They can't.

**Comment by pineappledan** [comment]
Okay. Guess it really is 6 of one, half a dozen of the other then. I made a pull request for the change in question. I think it's cleaner if it's tied to policy, rather than the buildings, but it really makes no difference, unless it might result in slightly less computation.
