### ISSUE TITLE
Tooltip shows wrong numbers

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4830]
_1. Mod version (i.e Date - 4/23):_10-10-2

_2. Mod list (if using Vox Populi only, leave blank):_Promotion Flags EUI

_3. Error description:_  Before a Great Merchant gets unpacked into a Town the tooltip shows wrong numbers. In my case it promises "Construct a Town. +4 Gold" on a 5Food tile (pic.1) which should make a 5Food 4Gold tile. The result however is 8Food 6Gold (pic.2). The same inconsistency is observed with other GP improvements.

Pic.1
![20181019135244_1](https://user-images.githubusercontent.com/16341598/47214962-462b2800-d3a8-11e8-945a-609374fd981e.jpg)

Pic.2
![20181019135306_1](https://user-images.githubusercontent.com/16341598/47214965-475c5500-d3a8-11e8-8f4a-b3f3dfd8458a.jpg)

**Comment by TechpriestEnginseer** [comment]
I'm not sure why it would do that...

**Comment by LoneGazebo** [comment]
The EUI tooltip doesn’t take into account all possible bonuses. It can’t.

**Comment by saamohod** [comment]
Also what about those numbers when I hover over the built farm? +10Food +1Production. From a farm? Is it real or some sort of a bug?

![20181019175154_1](https://user-images.githubusercontent.com/16341598/47226011-12f89100-d3c8-11e8-899c-e6fcb8e14f88.jpg)

**Comment by LoneGazebo** [comment]
Sounds like a mod conflict of some kind I haven’t seen anyone report this before.

**Comment by saamohod** [comment]
I suspect the Promotion Flags mod is to blame. As soon as I turned it off and launched a new game the problem disappeared.
By the way when I was playing a similar mod called Thal's FlagPromotions I also encountered some weird stuff that could not be explained by anybody of the mod devs. The two mods seem to be the same at its core.
