### ISSUE TITLE
authority and expansion

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4831]
in one of my testgames i found that nearly all AI players went for authority (7/8) - even korea. that seems a bit much. what's worse, 3 out of those 7 haven't produced a single settler yet (in turn 110). rome was even using the food process for a while.

![image](https://user-images.githubusercontent.com/1358966/47215119-91d9d380-d3a0-11e8-818b-962cb15fd9cb.png)

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2495576/logs.zip)

**Comment by LoneGazebo** [comment]
I’ll look. Generally that means the AI couldn’t find a good settling spot. 

What difficulty? The randomness may be responsible for the authority spam.

**Comment by ilteroi** [comment]
ok in a huge immortal game only 6 out of 12 players went authority ..
