### ISSUE TITLE
Free flanking bonus

### ISSUE THREAD

**Issue by johanbest69** [LoneGazebo/Community-Patch-DLL#4832]
_1. Mod version (i.e Date - 4/23):_
1010-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Units giving flanking bonus while solitary.  I found it was specifically the flanking bonus through logging.

The problem line is 

`int iNumAdjacentFriends = pOtherUnit->GetNumEnemyUnitsAdjacent() - pOtherUnit->GetNumFriendlyUnitsAdjacent();`

![20181020124003_1](https://user-images.githubusercontent.com/43484857/47249951-d9766300-d465-11e8-92bb-60bbd4fe36e2.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
i don't get it, can you explain some more?

**Comment by johanbest69** [comment]
So both units in that screenshot are given the +15% flanking bonus. 
My pathfinder has the -10%  barb bonus + 15% flank to go from 5 -> 5.25.
The barb has just the 15% flank bonus to go from 7 + 8.05.

That code I reference in CvUnit for some reason subtracts the number of friendlies adjacent from number of enemies adj.
So in this example each of the units has the calculation of  1 - 0 = 1.  Which gives them the flanking bonus.

The original code only checks for number of friendly adj.

I confirmed it was the flanking bonus and that bit of code from my own logging.

**Comment by ilteroi** [comment]
fixed. apparently the change was made by a person called "Gazebo" for the 9/25 version? don't know what it was supposed to achieve :)

**Comment by LoneGazebo** [comment]
@ilteroi bleh, a test slipped through. I was tinkering with making flanking a factor of friendly v. unfriendly adjacent (instead of just raw unfriendly adjacency), but forgot to remove it.

**Comment by johanbest69** [comment]
Cheers
