### ISSUE TITLE
CTD in the late game

### ISSUE THREAD

**Issue by ramsayspizza** [LoneGazebo/Community-Patch-DLL#4833]
_1. Mod version:_ [10/10 (October beta w/hotfix)](https://mega.nz/#F!iMNVEISb!gW3aPq-MQ-kibL0lFxrw-w)

_2. Mod list:_
- Vox Populi Full Version (with EUI); everything enabled
- [TacTurns BNW](https://steamcommunity.com/sharedfiles/filedetails/?id=211510253); used TacTurns Epic (original) game-speed
- [In Game Editor](https://forums.civfanatics.com/threads/ingame-editor.436912/)

_3. Error description:_ 
The game will usually crash in the later stages of the game to the desktop with no warnings, often randomly. In this case I crash on turn 683 upon clicking "Next Turn". I run the game with DX11.

_4. Steps to reproduce:_
Load the autosave for turn 683 then click "Next Turn".

---------------------------
All supporting files are included [**here**](https://github.com/LoneGazebo/Community-Patch-DLL/files/2497802/Files.zip). List of things included:
- The entire "Logs" folder
- The "MODS" folder with only the two non-VP mods I was using
- The "ModdedSaves" folder with the AutoSave for turn 683
- The ".ini" settings files
- The "CvMiniDump.dmp" file

**Comment by ryanmusante** [comment]
TacTurns might be problematic because it has tunings not in sync with VP?

**Comment by ramsayspizza** [comment]
I'm wondering whether an XML mod editing gamespeed parameters could be problematic. I don't have the knowledge to make an assumption; however, I'm currently testing an identical game without TacTurns! I'll report when it's done.

**Comment by ramsayspizza** [comment]
OK so I tested a game without TacTurns (only the full EUI VP mod and IGE) and I got no CTD towards the Atomic Era. However, instead, my game would freeze randomly on barbarian turn while autosaving (my game autosaves every turn). I checked my saves and the latest one would be 20 GB in size or so, and the longer I leave the game freeze the bigger the save file size would get. It seems I can't get to late game without CiV breaking

**Comment by LoneGazebo** [comment]
@ilteroi possibly a tactical AI overflow??

**Comment by ramsayspizza** [comment]
hey @LoneGazebo , I love your work , especially on the beta. there's this other thing that's happened in every game, but may be unrelated. So whenever a city revolts and declares itself a free City-State and I have at least 1 CS ally, I get a notification saying "Your allied City-States have declared war on Crom:". The notification list in-game shows that that the DoW notif happens BEFORE the CS is met, and the CS is met BEFORE it declares itself a free CS.

**Comment by LoneGazebo** [comment]
That’s normal, the UI stack resolves after the diplomatic things happen. Brand new AIs have to DOW every valid target on birth.

**Comment by ramsayspizza** [comment]
@LoneGazebo OK. I don't have to worry about that then! One more question: can using a different than normal Game-speed crash the game? I'm wondering why the crashes only happen in late-game (too many units, cities? too high yields? etc.). Also: I didn't seem to have problems starting in the Information Era for 200 turns, but I need to test that more. Again, thank you for your amazing work !

**Comment by ramsayspizza** [comment]
@TechpriestEnginseer thank you for the explanation! I personally don't go crazy with cities and armies, too much headache. The AI however.....wants every piece of land for himself, psh ! time to raze rinse repeat
