### ISSUE TITLE
[Suggestion] Open Borders after a peace deal

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4836]
Am I the only one who gets annoyed when my units get locked out of my territory after a peace deal is brokered between me and my enemy? The units stationed inside enemy's land get pushed away behind enemy's borders and often get stuck in place from where there is no route to my lands. Asking for an Open Borders Agreement is usually hopeless because the relations between two of us are irreparable. 

How hard it would be to implement a small amount (let's say five) turns of Open Borders agreement between the reconciled parties in order to give them a chance to bring their troops back home?

Inspired by Stellaris.

**Comment by ramsayspizza** [comment]
I like this idea. I often gift/delete units getting pushed in weird places. I only get slightly annoyed if I have high xp units getting trapped, and then I have to decide if the civ thinks my military is "threatening" or just delete the unit (I like to play diplo than warmonger >_> )

**Comment by matlajs** [comment]
Much more better would be, if it can just kick out our units some number of tiles towards our nearest city.

**Comment by matlajs** [comment]
bubbles, bubbles ale culprit. always see a lonely blitz/stalwart tank on independant hill.

**Comment by ilteroi** [comment]
it would probably be easier to make sure the units are teleported to a good location.

**Comment by bryan317** [comment]
I also find it important that the AI have the teleportation ability as well.  You guys have made a fantastic day I hear, but they still need all the help they can get 😉

**Comment by ilteroi** [comment]
ok, should be better now

**Comment by supermerill** [comment]
@saamohod 

see https://github.com/LoneGazebo/Community-Patch-DLL/issues/3413
