### ISSUE TITLE
Missing citadel bonus

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4839]
_1. Mod version (i.e Date - 4/23):_10-10-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I can't see the 100% defense bonus provided by the citadel. Whenever I mouse over an enemy unit stationed inside a citadel (in my case a Hunnic Horse Archer) there is no indication of the bonus. See the screenshots.

![20181022003217_1](https://user-images.githubusercontent.com/16341598/47272747-c0b79b80-d592-11e8-8f32-bf4610edd4f2.jpg)
![20181022003451_1](https://user-images.githubusercontent.com/16341598/47272748-c1503200-d592-11e8-9560-b69b3f26c3e9.jpg)

Also what does the -10% Defense Bonus mean? 

![20181022003451_1](https://user-images.githubusercontent.com/16341598/47272817-8e5a6e00-d593-11e8-9131-b73994f3320e.jpg)

[citadel.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2505871/citadel.zip)

**Comment by ilteroi** [comment]
well this sent me down the rabbit hole ... combat bonus calculation is a mess.

@g: you modified the enemyunitpanel recently right? any chance you broke this? meaning, is this maybe a UI issue only?

**Comment by MoiMagnus** [comment]
Not sure, but I think mounted units can't benefit from defensive bonus from terrain (including citadels). It should be one of the "red triangle promotions".

It does not explain the -10%, but explain the absence of +100%.

**Comment by saamohod** [comment]
@MoiMagnus
>Not sure, but I think mounted units can't benefit from defensive bonus from terrain (including citadels). It should be one of the "red triangle promotions".
 The citadel should provide the bonus to any type of unit according to its Civilopedia description. Same as a fort which provides +50% to units, the citadel should provide +100%. It seems the bonus is absent in the current version (even without looking at the bonuses breakdown in combat window it feels like the units in the citadel don't get "tankier", unlike it used to be before).

**Comment by LoneGazebo** [comment]
@ilteroi shouldn’t be, no, I just added a new entry. Didn’t modify that.

**Comment by johanbest69** [comment]
Units such as mounted units with the no defensive terrain attribute have never been able to get bonuses from citadels and forts.

I have currently been looking into combat mech after noticing a few strange things.  One other thing was that it seemed my infantry units were not getting protection by fort/citadel against canons.  Turns out this is the way it is coded for this mod. I don't think intended? Will open new issue.

**Comment by johanbest69** [comment]
In your screenshot you are attacking with Cannon,  so you probably notice you easily blew up even an infantry unit while stationed in a citadel.

**Comment by johanbest69** [comment]
Only other combat issue I have come across so far is the Spearman etc receiving defensive 50% bonus vs ranged mounted units (which it shouldn't). Have opened issue about this already.

**Comment by ilteroi** [comment]
ok, turns out the cannon has "ignoreBuildingDefense" set, so forts and citadels don't help against them. don't know if that is appropriate but it's no bug.

**Comment by johanbest69** [comment]
That attribute was never used in the original civ v or exp. 

It's a pretty massive deal if it is going to be kept and would need to be specified as a special promotion attribute for these units.

If it was to be added as a special attribute then surely it couldn't ignore the entire defensive bonuses of these structures.

**Comment by saamohod** [comment]
Please note that it's not only the cannon that seemingly negates the citadel's bonus. Click on any nearby unit  (Crossbowman, Tercio, Knight in the savegame I provided) and aim at the Horse Archer stationed in the citadel. None of those will have an indication of +100% defense bonus (and all will have the inexplainable -10% malus). So it's not only the case of cannon.

**Comment by johanbest69** [comment]
The horse archer cannot get any defensive bonus from fort/citadel.

The -10% is because of the medic promo.

**Comment by johanbest69** [comment]
Yes, I agree all units should get the defensive bonus of a fort/citadel.

In terms of the cannon.  I think all types of siege/artillery (inc catapults,trebuchets) should have an advantage against fortifications (as they do against cities).  So maybe a 30-50% bonus against fort/citadel.  Just needs to be added as another promo/attribute.

**Comment by ilteroi** [comment]
well for simplicity i would redefine the ignoreBuildingDefense to mean half defensive bonus

**Comment by LoneGazebo** [comment]
@ilteroi that's not 'ignore' though - really building defense should only apply to cities. the bonus for those units is part of their RCS and promotions

**Comment by johanbest69** [comment]
Searching through the code I'm sure that attribute does nothing for those units atm , except the added feature of ignoring fort/citadel. Doesn't factor into city attacks in vanilla or cbp.

The vanilla code for defenseModifier of plot even removes it's only real reference.

`int CvPlot::defenseModifier(TeamTypes eDefender, bool, bool bHelp) const`   <- referring to it as just "bool"

Having it instead ignore half of the defensive bonus of defensive features would be a good adaptation I think.

**Comment by ilteroi** [comment]
ok horses now get a defense bonus from forts and citadels.

ignoreBuildingDefense now applies when attacking cities (not when attacking fortifications) ... beware the mighty cannon!

**Comment by saamohod** [comment]
>ok horses now get a defense bonus from forts and citadels.

Does it mean that only horses were missing the mentioned bonus?

**Comment by ilteroi** [comment]
na, horses was just shorthand for "any unit with the noDefensiveBonus flag". anyway, all good now.
