### ISSUE TITLE
Request: merge "City States No Allied Skirmishes" mod into the CBP

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#484]
http://www.picknmixmods.com/mods/15cd975d-7d94-4845-be4a-4e34bcd3fa1b/mod.html
As of right now CSes spend way too much time warring each other, the change in calculation of city  strength in CBP doesn't make it easier.
Also it would be nice if it will be possible to liberate city-states under allied CS control without declaring a war.

**Comment by LoneGazebo** [comment]
I think I've got the code already included in the CP dll, but I'll look.

Not sure what you mean by the latter - conquering and liberating a CS if it is owned by an allied CS?

**Comment by Radost** [comment]
> conquering and liberating a CS if it is owned by an allied CS?

Yes, exactly that.
