### ISSUE TITLE
No protection in fort/citadels from Canon and above

### ISSUE THREAD

**Issue by johanbest69** [LoneGazebo/Community-Patch-DLL#4841]
_1. Mod version (i.e Date - 4/23):_
10/10-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Units do not get the fort/citadel defensive bonus when defending vs Canon and higher (Trebuchet and below do not have it).
This is because of the **IgnoreBuildingDefense** property in these units and the change to the code in CvPlot::defenseModifier.    

Is this intended?  If it should be added as a clear attribute in the units.

_4. Steps to reproduce (optional):_
I noticed it when my Tercio took impossible dmg from Cannon while stationed in a fort. Code confirms it.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
aha, @ilteroi I think that's the clue to the other defense issue we saw, no?

G

**Comment by ilteroi** [comment]
talk about bad timing, i spent half an hour tracing these combat bonuses to arrive at the same conclusion.

anyway #4839 claims the missing defense bonus is actually because a horseman has the noDefensiveBonuses attribute. should it apply to citadels? not sure.

secondly, ignoreBuildingDefense was allegedly not used in vanilla. but then who added it?

**Comment by LoneGazebo** [comment]
‘‘Twas not I.

**Comment by johanbest69** [comment]
Checking out the db turns out most/all of the post industrial units have this property...

**Comment by ilteroi** [comment]
duplicate to #4839
