### ISSUE TITLE
Rhiannon and GPTIs

### ISSUE THREAD

**Issue by legenciv** [LoneGazebo/Community-Patch-DLL#4842]
_1. Mod version (i.e Date - 4/23):_
10-10-2

_2. Mod list (if using Vox Populi only, leave blank):_
Promotion Flags EUI (1.1)

_3. Error description:_ 
The Rhiannon celtic pantheon doesn't provide the extra gold and production on Manufactories. It may be ignoring other GPTIs as well.

**Comment by LoneGazebo** [comment]
I'll update the text- it technically is only supposed to apply to 'real' improvements (mines etc.), not GP improvements.
