### ISSUE TITLE
Another flanking issue, flanking promo bonus not added

### ISSUE THREAD

**Issue by johanbest69** [LoneGazebo/Community-Patch-DLL#4843]
_1. Mod version (i.e Date - 4/23):_
10/10

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

The extra flanking bonus from "shock" promotions etc is not actually used. The code only uses INT when it needed to use double.

`iModifier += iTempModifier * ((100 + GetFlankAttackModifier()) / 100);`

((100 + GetFlankAttackModifier()) / 100) resolves to 1.

I can create pulls for some of these issues if you prefer.  

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
depends on the value of iTempModifier? maybe it's enough to add some parentheses.

anyway pull requests would be appreciated. i assume - g would be handling them :)

**Comment by johanbest69** [comment]
Wouldn't work for me unless I worked with doubles or multiplied by factor of 10 (which is probably the way to go)

Will do!
