### ISSUE TITLE
AI declares war to my vassal

### ISSUE THREAD

**Issue by marcoatk85** [LoneGazebo/Community-Patch-DLL#4845]
_1. Mod version (i.e Date - 4/23):_
9-19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
AI declares war to my vassal, attack then sign peace same turn. Next turn same things happen. 

The sava game is attached. Denmark and its vassal Spain declares war to my vassal Indonesia.
[etiopya.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2509250/etiopya.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): [etiopya.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2509250/etiopya.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Logs included?

**Comment by marcoatk85** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2516113/Logs.zip)
I dunno if this logs will help you. I enabled it following your message and then played couple of turns. Hopefully it will help to you.

**Comment by bentakacs** [comment]
Just encountered this issue (although technically it was not my vassal). I will provide logs too, maybe it will help.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2521915/Logs.zip)

Screenshot:

![vassalattack](https://user-images.githubusercontent.com/22188835/47605747-cab22200-da0a-11e8-8f9e-753ac159b928.png)

**Comment by ramsayspizza** [comment]
This happens to my vassals and to the AI vassals for me.
ALSO in one of my games an AI acquired a vassal, and whenever I DoW on the vassal, I can damage their units and stuff during my turn, but the moment my turn ends the game forces me to make peace (pushes all my units out etc.). Seems like the same thing I think!
