### ISSUE TITLE
Text on tooltip over Event option isn't clear

### ISSUE THREAD

**Issue by squidgeny** [LoneGazebo/Community-Patch-DLL#4846]
_1. Mod version (i.e Date - 4/23):_

5-20

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I got an event relating to the World Congress, with four options. The tooltip text on the "science" option, aside from referring to "16.6" in text (which was very odd), doesn't make it clear what happens. It ends with "Repeating, of course" - but does this mean I get 268 science every turn plus a 16.6% chance of a free tech every turn? (apparently not - i didn't get any). See screenshot.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![20181019213408_1](https://user-images.githubusercontent.com/44243830/47451550-fe4d3c00-d7bf-11e8-8f97-5cc2f88dfb1e.jpg)

**Comment by LoneGazebo** [comment]
This is a mod mod event, not a core event. Talk to @techpriestenginseer

**Comment by TechpriestEnginseer** [comment]
It means you get a one-shot science bonus with ~17% chance of receiving a free tech. I will change, ty.

**Comment by TechpriestEnginseer** [comment]
wait a second this isnt a modmod event it's a core event.
