### ISSUE TITLE
No supply bonus from citadel

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4847]
so i just build this citadel and got the notifications alright but my unit supply didn't increase ...

![image](https://user-images.githubusercontent.com/1358966/47453194-6f92ec00-d7cc-11e8-8668-30e77e1d9108.png)

also, questions: 

* since when do we have war weariness before industrial era?
* do i get supply increases from captured citadels as well? what happens when one is plundered?

**Comment by ilteroi** [comment]
and, unrelated: does conquering a holy city reset your faith counter? is that by design?

**Comment by LoneGazebo** [comment]
@ilteroi supply from citadels is actually supply from expending the GG. It isn’t related to the citade itself.

**Comment by LoneGazebo** [comment]
WW before industrial has been around for a few months now. And lastly when your majority’official religion changes all stored faith is lost.

**Comment by ilteroi** [comment]
hmm. seems like i missed a bunch of stuff :)

re: supply - i'm positive it did not change when i used the gg. and it's not listed in the tooltip either way.

**Comment by LoneGazebo** [comment]
@ilteroi it is possible that the bonus supply was immediately consumed by the WW or by tech/pop modifiers

**Comment by ilteroi** [comment]
so i tried to debug this - it seems to be more of a UI update problem - but i have questions.

- why is the gg effect hooked into CvUnit::kill() and not into CvPlayer::DoGreatPersonExpended() ?
- why is the bSupply argument for kill() true by default?
- why is the supply increase tied to the capital? seems unfair if you lose it?

**Comment by ilteroi** [comment]
whatever - i fixed the update problem but untying it from the capital is too much work right now

**Comment by LoneGazebo** [comment]
Hey, sorry I missed you, I've been out. @ilteroi the connection to the capital was done to avoid another memory element, but I'll fix that. Thanks!
