### ISSUE TITLE
France UA bug/typo

### ISSUE THREAD

**Issue by matlajs** [LoneGazebo/Community-Patch-DLL#4849]
_1. Mod version (i.e Date - 4/23):_
25/9

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Culture boost doesn't boost city yields, just an overall culture outcome. Production boost doesn't display while city has nothing in queue.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
a.) Accurate, it boosts culture. Not a bug.
b.) It is a production modifier for things, not a general production element. It can't give a bonus until it knows what it is giving a bonus towards.

**Comment by matlajs** [comment]
Oki. But UA description sounds, like a culture boost should be going directly into city output.

**Comment by TechpriestEnginseer** [comment]
No, if we follow how the other UA are set up, they'll say the abilities grants culture or provides. Boosting usually means a multiplicative and thus not an additive bonus.

**Comment by matlajs** [comment]
i just wouldn't mention  a ,,city'' word in a description. It is not such friendly to low-english speaking people, and people not on the philosophical english level.
