### ISSUE TITLE
Venice puppeted capital

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#485]
![8930_2015-07-29_00008](https://cloud.githubusercontent.com/assets/1131228/9024663/f597b152-38f4-11e5-93b0-7d5045e30387.png)
This is the only city Venice have.

**Comment by LoneGazebo** [comment]
I'm going to fix this so that if a puppeted city ever becomes a capital it is un-puppeted. Seems logical.
