### ISSUE TITLE
Randomness not random enough

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#4850]
Version: 10-10 ?

See: https://forums.civfanatics.com/threads/arabia-ua-proc-observation.637694/

Basically, when multiple RNG come from the same source during the same turn, they seems to give the same result. The thread is about Arabia UA, but I guess it may explain all the old reports of "authority only give one kind of unit instead of random".

**Comment by Vektic** [comment]
Playing Arabia on 10-10. Attached is a save of my game, as I finish hubble for 2 GS, as well as one faithbought GS for 4 procs in total. All procs yield GPP for XXX. As a screenshot is not sufficient to see that, I have attached a savefile from that turn, as well as a screenshot of the mods I use. Hope that helps.

Vektic

![20181025160957_1](https://user-images.githubusercontent.com/44470844/47507030-aff87580-d871-11e8-8620-c03b47f90a4b.jpg)

[Harun al-Rashid_0453 AD-1863.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2515815/Harun.al-Rashid_0453.AD-1863.zip)

**Comment by Grabbl** [comment]
Another RNG-related bug (seems to me): When several cities request a new WLTKD-resource at the same time (usually because they end their previous WLTKD at the same time), they all request the same resource.

**Comment by SpankMyMetroid** [comment]
> Another RNG-related bug (seems to me): When several cities request a new WLTKD-resource at the same time (usually because they end their previous WLTKD at the same time), they all request the same resource.

I'm getting the same result here too. And it's not because that's the only resource I have left not connected; I made sure to not import extra luxes until my WLTKD ended.

**Comment by Questdog** [comment]
One other Random thing that seems messed up, but not probably by the same thing as the above, is the Spy names for England.  I almost always play them and lately my first spy is always Merlin.  It would seem that a new seed is guaranteed for a new game, but it is still always Merlin.  Would not be so bad if it was James, but Merlin?

**Comment by ryanmusante** [comment]
@Vektic Why do you have two copies of Calypso's Colored Relgious Icons?

**Comment by azum4roll** [comment]
Still happening to City State Quests in the 12-18 version. I got 3 pairs of City States going to war with each other on the same turn, 4 City States asking to build shrines on another, and 5 City States wanting to discover a Natural Wonder on yet another.
