### ISSUE TITLE
Pantheon selection provides only one Pantheon belief

### ISSUE THREAD

**Issue by Leondegrance** [LoneGazebo/Community-Patch-DLL#4852]
_1. Mod version (i.e Date - 4/23):

5/20

_2. Mod list (if using Vox Populi only, leave blank):

QuickTurns, Tectonic Mapscript, EUI (which comes with VP - 43 Civ version)

_3. Error description:

I noticed a few times in the very early games, when I accumulate enough faith to select a Pantheon belief, the game offers only one single to choose from. I thought okay maybe I was too late and the other Civs exhausted them all. You know, like with the religions. So I disregarded it.

And now it hapenned again. But this time I noticed that a few turns later one of the Civs founded a new Pantheon belief. Wait a minute, how is that possible ?

_4. Steps to reproduce (optional):

Does not happen always but when it does it is always the same conditions - I am playing Morocco and the only Pantheon available is Desert Folklore.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Ahmad al-Mansur.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2517248/Ahmad.al-Mansur.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):2 screenshots representing visually the glitch. first one shows me being offered only 1 Pantheon. And the second pic shows that on the very next turn another Civ chooses a new Pantheon (which was not offered to me the previous turn).
![pantheon1](https://user-images.githubusercontent.com/44485090/47538638-7720c680-d89a-11e8-810f-7c1400820aa1.jpg)
![pantheon2](https://user-images.githubusercontent.com/44485090/47538640-78ea8a00-d89a-11e8-8da3-698690940b25.jpg)

**Comment by LoneGazebo** [comment]
Please enable logging and replicate this.

**Comment by Leondegrance** [comment]
Enabled logging, then loaded the save I provided before and the glitch repeated. But this time the only Pantheon available was not Desert Folklore but another one. Yet on the next turn a Civ founded a new Pantheon. Basically the bug was replicated.

I am sure it will replicate on your PC too. Just bear in mind it is a 43-Civ game so you need the 43 version of VP activated you know.

Here is the logs.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2517520/Logs.zip)
