### ISSUE TITLE
Can't construct anything

### ISSUE THREAD

**Issue by IcyKeswick** [LoneGazebo/Community-Patch-DLL#4855]
Date:

10/15 CBP
10/12 CBO
9/6 CSD
4/21 C4DF
9/15 More Luxuries
10/12 CBO Compatibility File

Error description:

Whenever I start up a new game in Vox Populi, it all works except for the fact that I cannot start constructing anything in my capital. The tab in the bottom-left corner of the city screen doesn't work either.

**Comment by LoneGazebo** [comment]
Sounds like EUI did not end up in the correct place. Please follow the installation instructions included in the VP file.

G
