### ISSUE TITLE
Barbarian Hordes Not Appearing

### ISSUE THREAD

**Issue by Questdog** [LoneGazebo/Community-Patch-DLL#4858]
_1. Mod version (i.e Date - 4/23):_10-10-2

_2. Mod list (if using Vox Populi only, leave blank):_Only UI and graphical mods

_3. Error description:_ Three times in the last two games I have played I have had a City State near me get the Assaulted By Barbarian Hordes event and three times I have sent units to help out but no Barbs ever appeared.   I am thinking that maybe for some reason these Barbs cannot spawn anymore in places where the player has vision. But that is just a guess.
 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
strange. there's a function called CvMinorCivAI::IsHordeActive(), but i can't find where the barbarians are supposed to spawn?

**Comment by ilteroi** [comment]
there are some suspicious rng calls in CvCity::DoBarbIncursion() though. 100 is definitely not a small number ...

**Comment by LoneGazebo** [comment]
@ilteroi incursion doesn’t apply to the CS event. 

The CS event uses a timer. The ‘set active’ code is used for lua IIRC.

**Comment by Questdog** [comment]
Just had the same situation happen in another game, but this time some Barbs showed up.  So I guess the guess about vision being an issue is not correct.  Maybe it was just one of those things.
