### ISSUE TITLE
Interrupted debugging

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#4859]
_1. Mod version (i.e Date - 4/23):_
10-10-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm trying to see the log "EconomicMonitorLog.csv" for a full game, but every time I reload the saved game (since I'm not able to finish a game in one session), values previous to the saved game are not stored, i.e., when loading a game from turn 90, all values in the log before turn 90 are removed from the file.

Is there a way to keep storing the values from the same game in the same file? Alternatively, is there a way to retrieve those historic values? They must be stored in a table or something, isn't it?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
nope. file is recreated every time you restart the game. only way is to copy it somewhere else and append to it manually

**Comment by TwoPodRay** [comment]
Most of my experience is with MATLAB, but is there not a function or condition that can check for previously created files and if so, append to them vs clearing and restarting?

**Comment by ilteroi** [comment]
if you were to write a new logging system, sure, you can do it any way you want. but the one by firaxis deletes the files.

**Comment by ryanmusante** [comment]
@tu-79 what about just using a script that copies the selected files into a separate directory on a timer? Than you can append manually after exiting the game at any time later.

**Comment by tu-79** [comment]
> 
> 
> @tu-79 what about just using a script external _to civ 5_ ? It copies the selected files into a separate directory on a timer _5, 10, 15 min_ ? Append manually or use a second script post-game that merges the interval timed log files. Export to csv.

Wonderful. How do I do this?

**Comment by ryanmusante** [comment]
The easiest method in windows is to use copy method for source and destination file.

https://windows.tips.net/T013219_Specifying_a_Copy_Schedule_in_Robocopy.html
C:\> ROBOCOPY C:\Temp1 C:\Temp3 /MON:1

**Comment by tu-79** [comment]
Thanks, I'll try.
