### ISSUE TITLE
combat bonuses

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4860]
you would think more people notice that, but flanking currently is a mess with about 4 or 5 bugs thrown in. most of them i fixed but some are more conceptual issues ...

1. apparently the flanking bonus applies both to the attacker AND the defender. does that make sense?

2. additionally, there's a flank attack modifier but it's applied in both cases (in c++, not in lua). that definitely seems wrong.

another point

3. with the terrifying effectiveness of cannon against cities since the ignoreBuildingDefense change, some knock-on changes might be required. definitely remove the +100% against cities. possibly reduce the RCS and remove the -33% against units too.

**Comment by ilteroi** [comment]
finally, i can't seem to get the citadel bonus to display for horsemen. on the dll side everything is fine, but the lua doesn't do what it's supposed to and i don't know how to debug it. if somebody else can take a look that would be great (latest shiny branch)

**Comment by LoneGazebo** [comment]
Re: 1 that’s by design. I do think that the flank bonus should be cumulative, ie you shouldn’t get the bonus if each side has 2 ‘flanking’ units adjacent to the target. It should only apply in real flanking situations.

**Comment by ilteroi** [comment]
ok with only a little more effort we can do a "delta" flanking bonus for the player who has more units adjacent to the opposing unit ...

**Comment by ilteroi** [comment]
help! i've implemented a new function CvPlot::GetEffectiveFlankingBonus(...) and the corresponding CvLuaPlot wrapper. but it doesn't work - the EnemyUnitPanel is not even displayed any more when i try to call it from lua.

Can somebody with mad lua skillz please take a look? So far I've only updated the EUI version of EnemyUnitPanel, but the change is commented out.

**Comment by LoneGazebo** [comment]
@ilteroi open the firetuner before you start debugging, the lua error should show up there.

**Comment by LoneGazebo** [comment]
also in the lua.log

**Comment by TechpriestEnginseer** [comment]
Also wouldn't know where to debug with my mad lua skillz :(

**Comment by ilteroi** [comment]
good tip with the log ... it seems i forgot the method declaration

	Method(GetEffectiveFlankingBonus);

what can i say, i'm a lua noob :)

as for the horseman, it turns out an aztec unit in a hunnic fortess indeed doesn't get a bonus.

so it seems everything is working. now i just need to update the other three versions of EnemyUnitPanel we have flying around

**Comment by LoneGazebo** [comment]
Thankfully @ilteroi they’re all identical.

**Comment by LoneGazebo** [comment]
I bypassed EUIs version a long time ago.

**Comment by ilteroi** [comment]
nice. so why not have one copy in a central place?

**Comment by LoneGazebo** [comment]
Because it wasn’t always that way but I didn’t want to merge it into the CP.

**Comment by TwoPodRay** [comment]
Thoughts on additive vs multiplicative flanking bonuses? Adding other combat bonuses are additive. Flanking is the only one I can think of that is multiplicative

**Comment by ilteroi** [comment]
i don't understand. can you give an example?

**Comment by TechpriestEnginseer** [comment]
Zulu promotions increase the flanking bonus, but only multiplicatively.

So when a promotion says +25% Flanking Bonus it usually means +12.5% flanking bonus and not +35% flanking bonus.

**Comment by ilteroi** [comment]
ah. i don't have strong feelings on this one. easy change. we would need to adjust the value of the flanking bonus promotion. what is the proposal there?

**Comment by ilteroi** [comment]
also, come to think of it, i would rather reduce the flanking bonuses a bit across the board because the AI is just not good at it.

**Comment by TwoPodRay** [comment]
I would think 5% would be fine, since it would scale with both levels (shock) and number of units flanking. if you can get 3 total units around another that’s +15% CS (when using additive) at shock 1 and 45% at shock 3, or a full surround gets you +30% (shock 1), +90% (shock 3), which is strong, but probably should be for a full surround. 

Going shock line into overrun could be +5% for shock 1-3 and overrun could be something like +15%? A full surround at max flank rank would be 180% (!!) CS using those numbers.

**Comment by ilteroi** [comment]
i went ahead and made the flanking bonus additive. but i didn't change the actual value to something sensible yet, because i don't know how. help!

**Comment by LoneGazebo** [comment]
@ilteroi the base flanking value is 10, i.e. '10% x # num of friendlies - num enemies' in how you've set it up now. I think 5% will work as a base. I'll fix the promotions.

G
