### ISSUE TITLE
New games using Community Patch: No luxuries or bonus resources spawning

### ISSUE THREAD

**Issue by GruntGG** [LoneGazebo/Community-Patch-DLL#4862]
_1. Mod version (i.e Date - 4/23):_
Vox populi 5-20-3; 31.10.2018

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Maps of games set up using Community Patch have no luxuries or bonus resources spawning (not a single one). If the Community Patch mod is deactivated and a new game is started, map spawns normally. I have tried using the "Ingame Editor" mod to reveal map at turn 1 and try starting up to 10 new games. All showed the same issue.
![screenshot 163](https://user-images.githubusercontent.com/44650134/47807921-ee94a100-dd45-11e8-8ffe-987a2af13bd8.png)
![screenshot 161](https://user-images.githubusercontent.com/44650134/47807933-f8b69f80-dd45-11e8-8788-6364866e86f2.png)
![screenshot 162](https://user-images.githubusercontent.com/44650134/47807942-fbb19000-dd45-11e8-9d17-277b9149331e.png)

Help would be appreciated. Contact me if you need further information.
_4. Steps to reproduce (optional):_
Enable Community Patch mod, set up new game in Pangea, Small map, default parameters.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Do you own all DLCs?

**Comment by GruntGG** [comment]
> Do you own all DLCs?

Yes

**Comment by MoiMagnus** [comment]
Unsubscribe from steam version of More Luxuries. There is a know bug (from the mod manager) when you have both Vox Populi and the steam version of Vox Populi installed (even if disabled)

**Comment by GruntGG** [comment]
> Unsubscribe from steam version of More Luxuries. There is a know bug (from the mod manager) when you have both Vox Populi and the steam version of More Luxuries installed (even if disabled)

Also not the case. Only mods I have installed are the Community Patch, the Ingame Editor and the nQ mod v13 (nQ mod was disabled when trying the Community Patch but it did not make any difference if I would activate it). When starting a new game with only nQ mod enabled the map looks normal.

Any other thoughts? I had a similar problem (no luxuries or bonus resources spawning) once when I installed an improved version of Pangea and other maps (can't remember the name now), after that I uninstalled it.

**Comment by bryan317** [comment]
I hate to say it, but sometimes I'm riddled with bugs that can only be gotten rid of by completely uninstalling the game and reinstalling.  I'm sure that there's SOMETHING I'm missing with I'm trying to "clear my caches" if you will.  But the complete uninstall/fixes me when Im glitched out. I always seemed to run into this after updating a few times.

**Comment by GruntGG** [comment]
> I hate to say it, but sometimes I'm riddled with bugs that can only be gotten rid of by completely uninstalling the game and reinstalling. I'm sure that there's SOMETHING I'm missing with I'm trying to "clear my caches" if you will. But the complete uninstall/reinstall fixes me when Im glitched out. I always seemed to run into this after updating a few times.

It is worth a shot. The main reason I wanted to install the Community Patch was for the AI improvement. I am tired of playing against the dumb vanilla AI. I have also tried installing "Smart AI" but my UI gets bugged and I cannot even select something to produce after building a city, which means I cannot play.

I will try re-installing the game and let you know how it went. Meanwhile, in case it would not work, would there be any way to just have the AI improvement from the Community Patch without having anything else? Perhaps this would make it work.

Thank you all!

**Comment by GruntGG** [comment]
Re-installing the game did not fix the problem. Any other ideas?

**Comment by LoneGazebo** [comment]
Generally the issue you're seeing is caused by an older version of civ, missing DLC, or a bad install. It is also possible that you aren't fully loading the mod- you have to enable the mods _and then_ start single player through the mods menu.

The fact that Smart AI was also making an issue for you makes me thing you've got an install issue with civ.

**Comment by bryan317** [comment]
Always ONLY load VP mods IMO. They make the game Civ5 2.  And superior to civ 6.  I don't know what you gurus are doing for a living but you should be working for firaxis

**Comment by GruntGG** [comment]
I will keep trying. So far no luck. I appreciate all the comments though.

**Comment by ryanmusante** [comment]
What DLC folders are in your Assets Directory? What mod folders are in  your MODS directory? Did you test integrity of files through Steam?

**Comment by Vyyt02** [comment]
What is your Civ5 version? You should see it under the main menu when you launch the game. It should be ending with .279. What you are seeing is typically happening when you are on an older version.

**Comment by bryan317** [comment]
Ok I'll say it... I'd like to see this Thread labeled as Slain like the Hydra.  Anyone that took the time to make a GitHub account must like true gaming and we must help this poor lad.

**Comment by GruntGG** [comment]
Thank you all for your effort and time. My apologies, somehow the game had not updated properly and I was playing on an outdated version which was giving me the problems. After trying it with the updated game version the problem was gone. Let's call it slain! Thank you again!
