### ISSUE TITLE
no production bonus from "organization" policy

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4863]
what the title says ... the 25% bonus seems to work but not the extra hammers.

![image](https://user-images.githubusercontent.com/1358966/47878364-66ce9580-de1e-11e8-8977-27632a2fedd5.png)

**Comment by LoneGazebo** [comment]
the extra hammers come from terrain IIRC.

**Comment by LoneGazebo** [comment]
technically the yields are under the city.

**Comment by ilteroi** [comment]
oh. my bad :)

**Comment by LoneGazebo** [comment]
The yields are _in_ the computer
