### ISSUE TITLE
afraid for no (objective) reason

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4864]
i have a situation here where siam is the leader, and i am india. they have twice my total score and 50% higher military score. they lead in tech and in policies.

nevertheless they are afraid of me?

![image](https://user-images.githubusercontent.com/1358966/47944305-df0a8900-defa-11e8-9e6a-cfd7e03b2dac.png)

i'm assuming this is not intended. should i post a savegame or a log? which one?

**Comment by DoItTomorrow** [comment]
Isn't there an AI modifier where the AI multiplies your army strength based on difficulty? If I recall the modifier for diety is 2, which is the highest.

**Comment by ilteroi** [comment]
well this is prince ... anyway, i found the relevant logs:

499, Siam, India, AFRAID, ---, OPN N, W_THT MINR, 325/29, M_THT mnr, TGT Favorable, WGL None, MAGG None, PRX Neighbors, LND Weak, VCT N, VBlock Weak, WND **FIERCE**, MCF **FIERCE**, ---, War, -19, Hostile, -64, Deceptive, -12, Guarded, -60, Afraid, 52, Friendly, 38, Neutral, -39

499, Siam, India, Opinion: 6, War, Value: -19, Scratch: -19, Delta: +0, Hostile, Value: -64, Scratch: -65, Delta: +1, Deceptive, Value: -12, Scratch: -12, Delta: +0, Guarded, Value: -60, Scratch: -60, Delta: +0, Afraid, Value: 52, Scratch: 52, Delta: +0, Friendly, Value: 38, Scratch: 37, Delta: +1, Neutral, Value: -39, Scratch: -45, Delta: +6

guarded is at -60 while afraid is at +52. definitely something wrong here

**Comment by ilteroi** [comment]
apparently there's a function called GetRandomPersonalityWeight() which is called at the very beginning of the game ... and it doesn't do a good job? the results are mostly zero ...

![image](https://user-images.githubusercontent.com/1358966/47952663-23d20680-df73-11e8-8bd4-02816cbecc26.png)

**Comment by ilteroi** [comment]
further down the rabbit hole.

* warscore is calculated using the "peacetime" method, and it assumes 
** india has an "immense" economic advantage over siam
** india has a "strong" army compared to siam
** both are incorrect (DoUpdateOnePlayerEconomicStrength is a mess)

* warmonger score i won't even get into but obviously it could use some modifications

**Comment by ilteroi** [comment]
ok i fixed the most glaring issues. didn't touch the warscore though.

**Comment by LoneGazebo** [comment]
i'll look at warscore stuff.
