### ISSUE TITLE
City UI Double Counting Event Bonuses

### ISSUE THREAD

**Issue by DoItTomorrow** [LoneGazebo/Community-Patch-DLL#4865]
_1. Mod version (i.e Date - 4/23):_
10-10-2 with EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
UI is double counting Event bonuses.
For instance, getting +1 faith to Shrine should give +3 faith total, but it shows as 4 on the right window in city view. Total city yields seem correct, as are the pop-up windows.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![screenshot 49](https://user-images.githubusercontent.com/43004683/48045448-5b3af000-e1cb-11e8-86a3-fdea9c6c9665.png)
![screenshot 50](https://user-images.githubusercontent.com/43004683/48045450-5b3af000-e1cb-11e8-9773-dbee9c8d2a4d.png)
![screenshot 51](https://user-images.githubusercontent.com/43004683/48045451-5bd38680-e1cb-11e8-99c4-a021099b2e4f.png)

**Comment by TechpriestEnginseer** [comment]
Hi can you extract and replace this file onto your (6a)/Lua/CityView.lua? It should be compatible with any save games and old version.

[CityView.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2569478/CityView.zip)

**Comment by DoItTomorrow** [comment]
> Hi can you extract and replace this file onto your (6a)/Lua/CityView.lua? It should be compatible with any save games and old version.
> 
> [CityView.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2569478/CityView.zip)

Seems to be working. Thanks.

**Comment by TechpriestEnginseer** [comment]
Great! I'll pull this right on.
