### ISSUE TITLE
Unit Supply Cap and Trade route decrease

### ISSUE THREAD

**Issue by asorel1942** [LoneGazebo/Community-Patch-DLL#4867]
_1. Mod version (i.e Date - 4/23): v.88 3-11-1

_2. Mod list (if using Vox Populi only, leave blank): 
Community Patch
Community Balance Overhaul
City-state Diplomacy
C4DF
43 Civs
Community Events
Wonders Expanded
Free Recon Units
Observatory Mod
Confederate States of America
Confederate States of America CBO Compatibility
Antiquity Site Icons Filter
Christian Denominations (Historical Religions)
CIV-linked Great Generals
Community Patch Mod Compatibility
Culturally Linked Start Locations
Donald J Trump
Enhanced Naval Warfare for VP
Friendly Waters
Great Prophet Historical Names
Industrial building Pack
InfoAddict
Ingame Editor
JFD's Confederation of Switzerland
JFD's The Kingdom of Prussia for Vox Populi
JFD's The Papal States (Pius IX) for Vox Populi
Leadership Reformation
Mechanized Infantry with Soldiers
Medieval and Renaissance Building Pack
More Luxuries
Nuclear Fission Reactor Plant
Promotions -- Ancient Ruins Choice
Provincial Palace
Quick Turns
Really Advanced Setup
Reforestation
Resource: Mint Include Copper
Strategic Buildings Pack
Sukritact's Civ VI style city names
Tactical Nuclear Missile
Terrain -- Motte-and-bailey fort
Terrain -- Pontoon Bridge
Terrain -- Terrace Farm Extension
Unique City-states
VP Promo Icons
Wonder Race
World Congress Reformation

_3. Error description:_ 
When advancing to a new era, the total military supply will be reduced by two. From one turn to the next, the total supply may change by a value of one, but will not exceed the original value unless more supply buildings are built.

When advancing to the Renaissance era in a recent game, the total number of available trade routes decreased by three. Savegame is attached.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[AutoSave_0165 AD-1050.Civ5Save.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/2558849/AutoSave_0165.AD-1050.Civ5Save.txt)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by asorel1942** [comment]
The trade route thing no, but I've noticed the supply cap issue even when VP was the only mod I was using.

Best Regards,
Anri Sorel

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ilteroi** [comment]
unit supply depends on tech level - a decrease is to be expected after discovering a new tech

**Comment by LoneGazebo** [comment]
Too many other mods to debug, but supply drop is normal.
