### ISSUE TITLE
CTD in CvUnit

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#4868]
@ilteroi, 
I'm getting a constant CTD here:

![image](https://user-images.githubusercontent.com/7849458/48244204-90556700-e3b2-11e8-907a-789060637207.png)

The map is size zero, but the function is crashing. pPlot isn't null, nor is the unit null. So I don't think it is a null exception there. m_terrainImpassableCount is size zero, but it also appears that some 'auto' elements are NULL.

I hate stuff like this.

G

**Comment by LoneGazebo** [comment]
It is happening when a unit conquers a city, but only in specific circumstances.

**Comment by ilteroi** [comment]
hard to tell without inspecting the variables ... right now i don't see what's going on.

anyway i've never seen this ShouldLoadOnMove() function. i guess it's only needed for rebasing aircraft onto carriers? so why is the terrain check even in there? at the very least only call it if pNewCity==NULL.

not the most satisfying resolution, but maybe it helps.

**Comment by LoneGazebo** [comment]
It is s vanilla function. I’ll add a check.

**Comment by LoneGazebo** [comment]
What do you think about this?

```
//	--------------------------------------------------------------------------------
bool CvUnit::shouldLoadOnMove(const CvPlot* pPlot) const
{
	VALIDATE_OBJECT
	if(isCargo())
	{
		return false;
	}

	if (pPlot == NULL)
		return false;

	switch(getDomainType())
	{
	case DOMAIN_LAND:
		if(pPlot->isWater())
		{
			return true;
		}
		if (pPlot->isCity())
			return false;
		break;
	case DOMAIN_AIR:
		if(!pPlot->isFriendlyCity(*this, true))
		{
			return true;
		}
		break;
	default:
		break;
	}

	if(isTerrainImpassable(pPlot->getTerrainType()))
	{
		bool bCanPass = false;
		bCanPass = m_Promotions.GetAllowTerrainPassable(pPlot->getTerrainType());

		if(!bCanPass)
		{
			return true;
		}
	}

	return false;
}
```

Note that the crash in question is in the m_map vector, which...doesn't make sense?

G

**Comment by ilteroi** [comment]
better but ... not radical enough. i don't know why it crashed so i have a bad feeling about just shuffling stuff around.

anyway:
* the terrainImpassable check seems useless, if the plot is impassable, we shouldn't be moving there in the first place. this function is not about movement rules!
* determining a unit should load is stupid if there's no check whether it actually succeeded

**Comment by LoneGazebo** [comment]
I'm wary of breaking any mods that add cargo capacity and/or carrier loading. I'm also curious as to why there isn't an initialization of the m_map object target 'm_terrainImpassableCount'

**Comment by LoneGazebo** [comment]
Yep, it's a boat that's causing the issue.

**Comment by LoneGazebo** [comment]
Boats can never load onto other things, so I'm just going to add a DOMAIN_SEA false check.

**Comment by LoneGazebo** [comment]
Yep that fixed it. Closing.
