### ISSUE TITLE
Tech tree messed up

### ISSUE THREAD

**Issue by Amecareth002** [LoneGazebo/Community-Patch-DLL#4869]
_1. Mod version (i.e Date - 4/23):_9-11BETA

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ I tought I'd check out the happiness changes by starting a game as Poland. As I went into the tech-tree and it looked like the screenshot I provided.

That picture was taken after a reinstall of the mod. I deleted the content of the ModUserData, ModdedSaves and the 6 "mods" from the Project. I did try to Validate my game files***** (twice) and it didn't fix my problem.

The tech tree looks perfectly fine if I launch a game without the CBP activated.

*****: Every time I've validated my game files, it downloaded 9.2 MB worth of files. It may be known and it's probably unrelated to the topic

_4. Steps to reproduce (optional):_Start a game, I had options set to:

no barbarians, no bad events, no tech brokering, 12 players/24 CS size map (huge I believe), conquest and diplo victories only and 7 civs total (including me).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2567959/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[AutoSave_Initial_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2567958/AutoSave_Initial_0000.BC-4000.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![techtree](https://user-images.githubusercontent.com/20826050/48295592-5db37900-e45b-11e8-81d8-4b9cb6736ad4.png)

**Comment by LoneGazebo** [comment]
Looks like you are missing DLC and/or updated Civ. .279 is the latest version.

Also you don't have logging enabled.

G

**Comment by Amecareth002** [comment]
Greetings G, sorry for the late reply, I was mostly trying to fix it alongside working with a cold. I did ended up "fixing" my issue. The cause/solution was that I wasn't using the enhanced UI. I'm not 100% sure why it happened, but my tech tree looks perfect now. Still got to get used to that UI though.

P.S: to make sure I was indeed running 9-11, I checked the Huns bonuses.
