### ISSUE TITLE
Flanking bonuses not working as intended

### ISSUE THREAD

**Issue by chicorbeef** [LoneGazebo/Community-Patch-DLL#4870]
1. Mod version (i.e Date - 4/23): 11/9

2. Mod list (if using Vox Populi only, leave blank):

3. Error description: I go from 10% to 16.48% flanking boost after picking Shock I, which doesn't seem intended. 

---------------------------
Supporting information:
4. Screenshots: ![20181109183707_1](https://user-images.githubusercontent.com/37256499/48296243-833b8500-e451-11e8-9f37-39be06f3bb21.jpg)
![20181109183758_1](https://user-images.githubusercontent.com/37256499/48296245-8898cf80-e451-11e8-8d33-10f9a066b2eb.jpg)

**Comment by LoneGazebo** [comment]
```
int CvPlot::GetEffectiveFlankingBonus(const CvUnit* pUnit, const CvUnit* pOtherUnit, const CvPlot* pOtherUnitPlot) const
{
	if (!pUnit || !pOtherUnit)
		return 0;

	const CvPlot* pOtherPlot = pOtherUnitPlot ? pOtherUnitPlot : pOtherUnit->plot();

	//our units are the enemy's enemies ...
	int iNumUnitsAdjacentToOther = pOtherPlot->GetNumEnemyUnitsAdjacent( pOtherUnit->getTeam(), pOtherUnit->getDomainType(), pUnit);
	int iNumUnitsAdjacentToHere = GetNumEnemyUnitsAdjacent( pUnit->getTeam(), pUnit->getDomainType(), pOtherUnit);

	if(iNumUnitsAdjacentToOther > iNumUnitsAdjacentToHere)
		return /*15*/ (GC.getBONUS_PER_ADJACENT_FRIEND() + pUnit->GetFlankAttackModifier()) * (iNumUnitsAdjacentToOther - iNumUnitsAdjacentToHere);

	return 0;
}
```

**Comment by LoneGazebo** [comment]
So in your case, 5 (the base value, ignore that 15_ + 3 = 8;

8 * 2 = 16

I don't know why there is a .48, but it is ultimately innocuous, as the real function rounds down. @ilteroi can correct me if I'm wrong.

**Comment by ilteroi** [comment]
just a small error in the lua code for displaying the value
