### ISSUE TITLE
City Ranged Damage way higher than expected

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#4873]
VP 11-9 only

![cityrcs](https://user-images.githubusercontent.com/24731508/48302265-d87fa100-e4fa-11e8-8192-5660c41f2281.png)

That's like 3x as much damage than in previous version

**Comment by Enrico-Swagolo** [comment]
Confirming, my Knight just got wrecked by a city with a wall. 36 damage each barrage.

**Comment by ilteroi** [comment]
there have been some changes but the RCS of a city should not have been affected. 

anyway 37 damage from an attack with 12 vs 8.4 seems reasonable?

@Enrico-Swagolo : what RCS did the city have? remember, RCS is (total defense minus building defense) * 1.5

**Comment by Enrico-Swagolo** [comment]
The city had 15 CS. Maybe 18 if the Horseman inside was still alive. So, it'd be15 - 10 (The Wall) = 5 

5 x 1.5 x 1.5 (second 1.5 from tradition) so... 11.25? That shouldn't be able to three shot a Knight with 3 promos (2x shock, 1x drill), GG aura, honour and morale. It should be barely doing anything if my calculations are correct.

**Comment by johanbest69** [comment]
It was mistakenly(?) changed.

Before range attacks from city are reduced 

`iModifier -= /*40*/ GC.getCITY_RANGED_ATTACK_STRENGTH_MULTIPLIER();`

Now it is added instead 

`int iModifier = /*40*/ GC.getCITY_RANGED_ATTACK_STRENGTH_MULTIPLIER();`

**Comment by LoneGazebo** [comment]
Wasn’t me!

**Comment by ricanuck** [comment]
hotfixable?

**Comment by ilteroi** [comment]
seems best to fix this in the db.

**Comment by ricanuck** [comment]
you mean putting this variable to negative?

CITY_RANGED_ATTACK_STRENGTH_MULTIPLIER
