### ISSUE TITLE
Mongolian Heavy Tribute description

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4874]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Annex City State option under Tribute in CS options still mentions Golden Age points no matter if you highlight it when it's available or not. It's incorrect.

**Comment by TechpriestEnginseer** [comment]
Can I have a pic of this tooltip. I cannot locate.

**Comment by TechpriestEnginseer** [comment]
Cool.
