### ISSUE TITLE
remove promotions from siege units

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4875]
the default promotions on siege units are crazy.

![image](https://user-images.githubusercontent.com/1358966/48305820-f74d5a00-e531-11e8-91d6-3585014178e8.png)

* +25% defensive bonus against ranged
* -33% attack against land units
* -20% attack against naval units
* +100% attack against cities 

cannon and later definitiely don't need the +100% promotions against cities any more because of the "ignoreBuildingDefense" flag.

how about a slightly decreased RCS and all the promotions above can be dropped? maybe keep the defense against ranged, but the others can all go.

**Comment by ilteroi** [comment]
good point, i kind of assumed ignoreBuildingDefense only applies to the later siege units ... if it's for all gunpowder units, that changes things. 

but ignoring it completely seems dull ... any ideas?

**Comment by johanbest69** [comment]
It makes sense that siege units would have an advantage against forts/citadels just like they currently do vs cities. 
It doesn't make sense that they would do the same amount of damage to units who are in a fort or outside of it. Also doesn't make sense that earlier siege units do not benefit.

In my local solution I have all siege units having this property (and no other units), the property reduces the defensive modifier of forts/citadels by 50%. Seems to work well.

**Comment by saamohod** [comment]
>It doesn't make sense that they would do the same amount of damage to units who are in a fort or outside of it. 

Agreed.

**Comment by supermerill** [comment]
It's a relic of civ4.

At this time, walls & castle obsolete at gunpowder. You can't build them after that but they remain in the cities. So this promotion allow all gunpowder (and later) unit to ignore these "obsolete" buildings.

**Comment by ilteroi** [comment]
ok my bad. i'll remove the ignoreBuildingDefense() check and the promotions stay as they are

**Comment by LoneGazebo** [comment]
Let’s mark the entire memory variable for deletion. Goodness knows we need the memory!

**Comment by ilteroi** [comment]
those 400 bytes won't save us ...

**Comment by ilteroi** [comment]
that's the point. most memory is used for graphics. we have little leverage there.

**Comment by Stalker012345** [comment]
Is it possible to replace certain high memory graphics with less consuming ones?

**Comment by LoneGazebo** [comment]
@Stalker012345 we've been doing that somewhat in the CP, but we're kinda at the 'end of the line' on many remaining elements.

**Comment by Stalker012345** [comment]
> probably. but i wouldn't know where to start ...

Is it possible to get a list of the graphics and the size they take up? There may be some choice graphics that we could substitute a lower quality version to free up space.
