### ISSUE TITLE
Great General Bug

### ISSUE THREAD

**Issue by Phantom1tr** [LoneGazebo/Community-Patch-DLL#4876]
_1. Mod version (i.e Date - 4/23):_
Latest (Downloaded on 11/2018 from civfanatics)

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi + JFD's civ mods

_3. Error description:_ 
Great Generals galore. On my first game both The Huns and Arabia whic are original civs in the game got them (around 25 great generals each civ), when it got ridiculous because of the citadels they builtI started a 2nd game where now it seems I'm getting them, which I think has something to do with "Tradition" social tree because I think it started after me completing that tree.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/sho

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Mehmed II_0183 AD-0145.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2568820/Mehmed.II_0183.AD-0145.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![mods1](https://user-images.githubusercontent.com/44932373/48306626-0b528500-e54d-11e8-86b1-518864cd0dd2.jpg)
![mods2](https://user-images.githubusercontent.com/44932373/48306627-0beb1b80-e54d-11e8-94b0-c44b090a02cb.jpg)
![great general](https://user-images.githubusercontent.com/44932373/48306628-0beb1b80-e54d-11e8-82ae-fd719b0937da.jpg)

**Comment by TechpriestEnginseer** [comment]
There is just too much to be able to diagnose the issue.

**Comment by TechpriestEnginseer** [comment]
It has to be the overload of civ mods.
