### ISSUE TITLE
Mongolia heavy tribute annex cooldown gone

### ISSUE THREAD

**Issue by BiteInTheMark** [LoneGazebo/Community-Patch-DLL#4877]
_1. Mod version (i.e Date - 4/23):_
11-9

_2. Mod list (if using Vox Populi only, leave blank):_
none

_3. Error description:_ 
Mongolia is again able to rapidly annex city states without the cooldown.  In my last game mongolia had annexed 3 city states at turn 70. 

_4. Steps to reproduce (optional):_
Play mongolia

**Comment by TechpriestEnginseer** [comment]
Intentional.
