### ISSUE TITLE
Stuck  archaeologist 

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4878]
_1. Mod version (i.e Date - 4/23):_ 11-9

_2. Mod list (if using Vox Populi only, leave blank):_ see screenshot

_3. Error description:_  

An AI archaeologist is stuck in the middle of the ocean for quite some time now.

![20181111114530_1](https://user-images.githubusercontent.com/16341598/48311417-31f1d980-e5a8-11e8-9342-741de0f5a8ec.jpg)
![20181111114600_1](https://user-images.githubusercontent.com/16341598/48311421-35856080-e5a8-11e8-83fa-7fbac1c889ee.jpg)

Savegame

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2569219/QuickSave.zip)

**Comment by ilteroi** [comment]
cannot load this as usual, nothing i can do here

**Comment by LoneGazebo** [comment]
Logs would be ideal, probably too hard to get.

**Comment by saamohod** [comment]
Sadly I didn't keep the logs. I'll make sure I provide them next time I encounter the bug.
