### ISSUE TITLE
"The city of"

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4880]
_1. Mod version (i.e Date - 4/23):_ 11-9

_2. Mod list (if using Vox Populi only, leave blank):_ see screenshot

_3. Error description:_ 

It appears that the "city wants luxury" icon has wrong wording. See screenshot..

![20181111155050_1](https://user-images.githubusercontent.com/16341598/48313797-11d31200-e5ca-11e8-92ee-bf3edfeeb15f.jpg)
![20181111114600_1](https://user-images.githubusercontent.com/16341598/48313802-20b9c480-e5ca-11e8-923f-349a4f2428f1.jpg)

Savegame
[QuickSave (2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2569416/QuickSave.2.zip)

**Comment by TechpriestEnginseer** [comment]
Logging would have been nice and easier to solve. :(

You have too much mods to diagnose.
