### ISSUE TITLE
Duplicate reward for construction

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4881]
_1. Mod version (i.e Date - 4/23):_ 11-9

_2. Mod list (if using Vox Populi only, leave blank):_ see screenshot

_3. Error description:_ 

It seems I got double reward for an office of a foreign corporation that has spread in my capital. 

![20181111163145_1](https://user-images.githubusercontent.com/16341598/48314284-08e53f00-e5d0-11e8-93c8-6bc1400ce9ec.jpg)
![20181111114600_1](https://user-images.githubusercontent.com/16341598/48314287-0b479900-e5d0-11e8-9096-e5559ddb044c.jpg)

Savegame

[QuickSave (3).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2569470/QuickSave.3.zip)

**Comment by TechpriestEnginseer** [comment]
No no it's more like you built something at the same turn a franchise was constructed.

**Comment by saamohod** [comment]
why does it say I constructed Centaurus Extractors in my capital twice?

**Comment by TechpriestEnginseer** [comment]
It count the last building that came into existence.
