### ISSUE TITLE
Weird CS flipping

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4883]
_1. Mod version (i.e Date - 4/23):_ 11-9

_2. Mod list (if using Vox Populi only, leave blank):_ see screenshot

_3. Error description:_ 

Some weird stuff happening, let me explain.

1. I'm at war with Austria, CS Wellington is my ally.
2. At the start of another turn I get message that Wellington is now my enemy.
3. I have a look at it, it is indeed my enemy now, but it's allied to France (France is neutral to me).
4. I open CS diplomacy window and press "Make Peace".
5. Peace is made, now they are my allies again BUT my influence with them is at minus 50ish.
6. Next turn the cycle repeats (they are hostile, allied to neutral France, I make peace, they are back to allies with negative influence).
7. And the third turn the same again. After I've made peace I send a diplomat to them, conduct a diplo-mission and now they are no longer my allies with -50 influence but just friends with influence +44.

![20181111210858_1](https://user-images.githubusercontent.com/16341598/48317354-5a55f400-e5f9-11e8-9894-a9288105bed2.jpg)
![20181111210901_1](https://user-images.githubusercontent.com/16341598/48317355-5b872100-e5f9-11e8-8dd5-64be9dde2c37.jpg)
![20181111210910_1](https://user-images.githubusercontent.com/16341598/48317356-5d50e480-e5f9-11e8-92da-d6aade00c6b1.jpg)
![20181111212411_1](https://user-images.githubusercontent.com/16341598/48317357-5f1aa800-e5f9-11e8-8f47-6b138f96f7c2.jpg)

my cosmetic mods
![20181021132740_1](https://user-images.githubusercontent.com/16341598/48317359-6e99f100-e5f9-11e8-8629-b7df6f25d7b8.jpg)

Savegame
[Weird.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2569753/Weird.zip)

**Comment by TechpriestEnginseer** [comment]
If you don't enable logging, we cannot help you.

**Comment by saamohod** [comment]
**This**   https://forums.civfanatics.com/threads/how-to-enable-logging.487482/   **?**

**Comment by TechpriestEnginseer** [comment]
Yes except you have to replicate the same bug with logging enabled.

**Comment by saamohod** [comment]
I replicated it. Which files do you need?

**Comment by TechpriestEnginseer** [comment]
The logging files.

**Comment by saamohod** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2571059/Logs.zip)

I guess this is what you mean.

**Comment by TechpriestEnginseer** [comment]
Hmmm, there does not seem to be any indication of a major bug despite for a single missing DLC...

And I loaded the save game in the mod order you presented to me and I cannot seem to have replicated the bug at all.
