### ISSUE TITLE
Fragile cities

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4884]
_1. Mod version (i.e Date - 4/23):_ 11-9

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

It seems cities have become much weaker defense-wise in recent patch. 

An average siege unit needs too few shots to strip a city (an average city of about the same age as attacker) of its defenses. It usually takes 2-4 shots. Other missile non-siege units are also way too effective. Often it seems more reasonable to bring a city's defense down with a horse missile unit than bothering with cumbersome siege units.

**Comment by ryanmusante** [comment]
_Horse missile unit_? You mean it's easier to use ranged mounted vs. melee and/or siege?

**Comment by saamohod** [comment]
It's easier not because horse missile units deal more damage to the cities than siege, but because they are mobile and have more HP. 
Can't tell the statistics, I've started a new game. But yesterday when I was harassing enemy territory with my Cavalry I noticed that the damage they did to the cities is considerable. The enemy was slightly ahead on techs and different cities did have different HP, but in general I found it was much more useful to utilize ~3 Cavalry units for the purpose of bombarding the cities before assault.

**Comment by johanbest69** [comment]
There is a known issue that all Gunpowder+ range units are ignoring building defenses in cities.

**Comment by 8h42** [comment]
`UPDATE Units SET IgnoreBuildingDefense = '0';`

Add this code into a file that is loaded **after** CBO files.
e.g. 
(3) CSD for CBP\Options.sql

![test](https://user-images.githubusercontent.com/11933188/48404229-27d00680-e773-11e8-906c-82fceb89f7a9.jpg)

**Comment by ilteroi** [comment]
see #4875
