### ISSUE TITLE
No Tribute culture from Authority

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4885]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_
 I made a regular tribute demand, got some Gold, but I didn't get the sweet Culture reward. I'm Mongolia if it's important.

**Comment by Enrico-Swagolo** [comment]
Checked as several other civs, really no Culture from tribute.

**Comment by vide0gamer** [comment]
Can confirm.  Playing as Aztecs, save has city state available to demand tribute from.  I am using the really advanced setup mod, if it matters.
[AutoSave_0060 BC-1600.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2590442/AutoSave_0060.BC-1600.zip)
Here are the log files:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2590459/Logs.zip)

**Comment by Enrico-Swagolo** [comment]
Im' not using the really advanced setup by the way - but that one is probably not related to how Authority works. No culture on demands both on vanilla VP and 4UC.

Weirdly enough, the "Honor.sql" in Honor folder has the mention demands from minors give Culture, so it must be something else that broke.
