### ISSUE TITLE
Weird message

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4887]
_1. Mod version (i.e Date - 4/23):_ 11-9 EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  A message I can't decipher. I've no idea who Crom is, I'm not at war with anyone and haven't been for a while.

![20181112172746_1](https://user-images.githubusercontent.com/16341598/48357467-554c7f80-e6a1-11e8-9626-8837125743f4.jpg)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2572498/Logs.zip)

**Comment by ilteroi** [comment]
crom is the name for the barbarian leader. go watch conan :)

**Comment by TechpriestEnginseer** [comment]
It's also when these city-states get liberated or get "made" out of nowhere that they declare war on the Barbarians as part of the DLL.
