### ISSUE TITLE
All tile yields display as food (apples)

### ISSUE THREAD

**Issue by TimmyMojo** [LoneGazebo/Community-Patch-DLL#4890]
_1. Mod version (i.e Date - 4/23):_
11/9

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch v.88 (No other Vox Populi mods), installed using automatic installer
EUI v1.29beta26

_3. Error description:_ 
All tile yields display as food (apples). I tried doing a clean install (with fully deleting Documents\My Games\Civ 5 folder) and the issue persists. Happens with every new game.
![civ5screen0000](https://user-images.githubusercontent.com/44988620/48386039-53d98200-e6b6-11e8-84a0-c0aa1f3f0a5f.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
It's a UI bug. You seem to have a duplicated CP UI and EUI UI file.

**Comment by TimmyMojo** [comment]
Are there some special steps that need to be taken for the barebones Community Patch mod when using it with EUI, since there's no accompanying compatibility mod?

**Comment by TechpriestEnginseer** [comment]
I wouldnt know.

**Comment by phantommaxwell** [comment]
I remember this issue from ages ago.  It was most common when we had to manually install VP; it was caused by having extra an compatibility Folder in the (1) Community Patch Folder.

**Comment by TechpriestEnginseer** [comment]
Correct!

**Comment by TechpriestEnginseer** [comment]
However, I don't think CP supports the latest version of EUI at all. Sorry. :s
