### ISSUE TITLE
dreadnought promotion messes up health bar

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4891]
![image](https://user-images.githubusercontent.com/1358966/48437935-06771680-e783-11e8-98ee-4bf219da71ad.png)

it's a bit dangerous to change max HP, there are many instances of sloppy code which assume a unit has 100 hp ... the most visible being the health bar.

**Comment by TechpriestEnginseer** [comment]
I think it's because the UI hardcoded it to 100 instead of the whoward's max hp define. However we can fix it if we find where they are.

**Comment by LoneGazebo** [comment]
Yeah. I’ve been fixing it as I find it. You can search for the Define MAX_UNIT_HP or whatever and go from there.

**Comment by TechpriestEnginseer** [comment]
But it is  UnitFlagManager mod that iliteroi is using, soo... it's not our bug.
