### ISSUE TITLE
wrong tooltip

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4892]
![image](https://user-images.githubusercontent.com/1358966/48438861-36bfb480-e785-11e8-8ec1-8a660f7c6d05.png)

the mine gives +4p at this point in the game ... this is EUI btw, don't know if it makes a difference

**Comment by TechpriestEnginseer** [comment]
From what does the mine receive an additional 3 production? I know they don't pick up on events and city local bonuses for performance's sake.

**Comment by LoneGazebo** [comment]
I hate EUI.

**Comment by LoneGazebo** [comment]
It's something to do with this 

	local function insertImprovementYieldChanges( tips, improvement, bullet )

EUI, PlotHelpManager.lua, line 418, but I don't see where the bug is. Any takers?

**Comment by TwoPodRay** [comment]
The mine should be getting more production from Tech, so whatever function adds yields to the mine after placement due to tech should look similar to or be mirrored by the function that previews the yields prior to placement.

**Comment by LoneGazebo** [comment]
@TwoPodRay that's easy to say, but the EUI code is such spaghetti.

**Comment by TwoPodRay** [comment]
What decompiler do you guys use? I haven’t played with any code not in a LUA or sql file (ie plaintext).

**Comment by LoneGazebo** [comment]
Visual Studio. But lua is plaintext.

**Comment by Infixo** [comment]
This bug affects all types of improvements, e.g. farms, etc. Anyway, I think I solved it at least for Techs.
![obraz](https://user-images.githubusercontent.com/25866684/49011631-36f18400-f177-11e8-8161-d4950f6070af.png)
![obraz](https://user-images.githubusercontent.com/25866684/49011655-48d32700-f177-11e8-934d-9b9acfe11546.png)

**Comment by ilteroi** [comment]
it seems we now have the opposite problem?

![image](https://user-images.githubusercontent.com/1358966/49699784-bbabbb80-fbd5-11e8-8366-f32d8b491e98.png)

this is around 0AD ... the eki plot gives 2f2p1c in total, but the tooltip is showing a lot more

**Comment by TechpriestEnginseer** [comment]
Isn't that intentional? I thought it was showing the maximum amount you could've gotten.
