### ISSUE TITLE
crazy AI city growth

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4893]
how is this possible?

```
Civ Name,Turn,City Name,Population,food,production,city gold,science,culture,faith,tourism,goldenage,food / pop,production / pop,gold / pop,science / pop,culture / pop,faith / pop,tourism / pop,goldenage / pop,food specialist,production specialist,gold specialist,science specialist,culture specialist,faith specialist,tourism specialist,goldenage specialist,food specialist / food,production specialist / production,gold specialist / gold,science specialist / science,culture specialist / culture,faith specialist / faith,tourism specialist / tourism,goldenage specialist / tourism,Tiles,Worked (non-city) tiles,Improved tiles,improved / worked,
Morocco,216,Oujda,3,24,17,10,11,4,2,0,0,8.00,5.67,3.33,3.67,1.33,0.67,0.00,0.00,0,0,0,2,0,0,0,0,0.00,0.00,0.00,0.18,0.00,0.00,0.00,0.00,9,9,0,0.00,
Morocco,217,Oujda,4,24,17,15,13,4,2,0,0,6.00,4.25,3.75,3.25,1.00,0.50,0.00,0.00,0,0,2,4,0,0,0,0,0.00,0.00,0.13,0.31,0.00,0.00,0.00,0.00,10,10,0,0.00,
Morocco,218,Oujda,5,22,28,18,14,5,2,2,0,4.40,5.60,3.60,2.80,1.00,0.40,0.40,0.00,0,1,2,5,0,0,0,0,0.00,0.04,0.11,0.36,0.00,0.00,0.00,0.00,11,11,1,0.09,
Morocco,219,Oujda,6,37,24,15,5,5,2,2,0,6.17,4.00,2.50,0.83,0.83,0.33,0.33,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11,11,1,0.09,
Morocco,220,Oujda,7,40,22,17,8,5,2,2,0,5.71,3.14,2.43,1.14,0.71,0.29,0.29,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11,11,2,0.18,
Morocco,221,Oujda,8,45,22,17,8,5,2,2,0,5.63,2.75,2.13,1.00,0.63,0.25,0.25,0.00,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11,11,2,0.18,
Morocco,222,Oujda,9,42,27,22,17,5,2,2,0,4.67,3.00,2.44,1.89,0.56,0.22,0.22,0.00,0,1,2,5,0,0,0,0,0.00,0.04,0.09,0.29,0.00,0.00,0.00,0.00,12,12,2,0.17,
Morocco,223,Oujda,10,45,27,25,18,5,2,2,0,4.50,2.70,2.50,1.80,0.50,0.20,0.20,0.00,0,1,2,5,0,0,0,0,0.00,0.04,0.08,0.28,0.00,0.00,0.00,0.00,13,13,2,0.15,
Morocco,224,Oujda,11,47,27,25,18,5,2,2,0,4.27,2.45,2.27,1.64,0.45,0.18,0.18,0.00,0,1,2,5,0,0,0,0,0.00,0.04,0.08,0.28,0.00,0.00,0.00,0.00,14,14,2,0.14,
```

prince difficulty. morocco founded a city and it has been growing *every turn*! how is that possible?

![image](https://user-images.githubusercontent.com/1358966/48440191-881d7300-e788-11e8-8447-ee6ac6e7fa57.png)

**Comment by TechpriestEnginseer** [comment]
A cool religion, internal trade routes, event bonuses?

**Comment by ilteroi** [comment]
well the tooltip doesn't show any internal trade routes.

no religious bonuses. and events are turned off.

**Comment by LoneGazebo** [comment]
When you look at the 'AI handicap log' (forget the actual name), what is the instant yield bonus value on the turn it is founded? Because it can sometimes be a substantial amount.

**Comment by ilteroi** [comment]
hmm. it claims they founded the city in turn 215 ... then in 216 there was a "historic event" ... what is that about? events are turned off.

Morocco, 215, CBP AI DIFFICULTY BONUS FROM CITY FOUNDING: Received Handicap Bonus (52 in Yields).
Morocco, 216, CBP AI DIFFICULTY BONUS FROM HISTORIC EVENT 0: Received Handicap Bonus (156 in Yields).

anyway even if the historic event affected oujda, and it's all food - that wouldn't be enough to explain the pop boom

**Comment by LoneGazebo** [comment]
Historic Event = handicap (they're handled using the instant yield system). 

Best way to check would be to put a debug stop in the city growth function with an ID check for the city's ID.

**Comment by ilteroi** [comment]
wow, if they found a new city they get a boost in _every_ city? i wasn't aware of that. anyway event 0 is the dawn of a new era. so they got 200 food bonus in every city. impressive, especially for prince.

**Comment by LoneGazebo** [comment]
Yep, that's the offset for giving the AI a bunch of passive handicaps and free stuff at start.

**Comment by LoneGazebo** [comment]
That's most likely why it happened.

**Comment by ilteroi** [comment]
well it's not relevant for this case but i would definitely only give a bonus to the newly founded city after founding.

also, i did some calculations:

![image](https://user-images.githubusercontent.com/1358966/48585803-1c750a80-e92e-11e8-9f86-7dfc1c83d5e8.png)

they need 1422 food to grow to size 12. now the city started at 3 because it's a pioneer. subtracting that (43 food) and the bonuses they got (286) it means they somehow generated a surplus of 1094 food in 10 turns. that sounds implausible ... even if you consider a granary.

**Comment by ilteroi** [comment]
added some tracing. it was tricky because we still have a reproducability problem - they wouldn't even found the city in the same place without some help ...

```
Pre Growth food 150, kept 00, change 24; Post Growth food 144, new pop 4, new threshold 50
Pre Growth food 420, kept 05, change 11; Post Growth food 392, new pop 5, new threshold 63
Pre Growth food 392, kept 07, change 06; Post Growth food 344, new pop 6, new threshold 83
Pre Growth food 344, kept 09, change 07; Post Growth food 280, new pop 7, new threshold 106
Pre Growth food 280, kept 12, change 11; Post Growth food 200, new pop 8, new threshold 132
Pre Growth food 200, kept 15, change 08; Post Growth food 096, new pop 9, new threshold 161
Pre Growth food 096, kept 19, change 09
```

these are the bonuses they got

```
Morocco, 215, CBP AI DIFFICULTY BONUS FROM CITY FOUNDING: Received Handicap Bonus (52 in Yields).
Morocco, 216, CBP AI DIFFICULTY BONUS FROM HISTORIC EVENT 0: Received Handicap Bonus (156 in Yields).
Morocco, 217, CBP AI DIFFICULTY BONUS FROM HISTORIC EVENT 2: Received Handicap Bonus (26 in Yields).
Morocco, 221, CBP AI DIFFICULTY BONUS FROM HISTORIC EVENT 2: Received Handicap Bonus (26 in Yields).
Morocco, 222, CBP AI DIFFICULTY BONUS FROM HISTORIC EVENT 8: Received Handicap Bonus (0 in Yields).
Morocco, 222, CBP AI DIFFICULTY BONUS FROM HISTORIC EVENT 2: Received Handicap Bonus (26 in Yields).
```

so the city starts with 150 food (although the bonus is 52), has 24 surplus food with 3 pop, and then gets another 420-144=276 from somewhere although the difficulty bonus is "only" 156. seems a bit fishy.

**Comment by TechpriestEnginseer** [comment]
Don't Pioneer give out free buildings like the Aqueduct making it much easier to grow?

**Comment by ilteroi** [comment]
only a granary. that's why "kept food" is > 0

**Comment by LoneGazebo** [comment]
I'm back in town, and will look at this some today.

G
