### ISSUE TITLE
API_LUA_EXTENSIONS error - Unit:GetTradeRouteIndex() causes CTD

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4894]
1. Mod version: 11/9

2. Mod list (if using Vox Populi only, leave blank): building custom Canada civ for VP.

3. Error description: 
I am trying to implement a UA for a custom civ which is VP compatible. I want internal land trade route to claim tiles. 

CTD occurs with this code. If I comment out the line with "pPlayer:GetTradeRoutes(pUnit:GetTradeRouteIndex()).ToID == iPlayer" then the code works as intended, but I want to disable the code for international TRs. 

function YorkFactoryExpress(iPlayer, iUnit, iX, iY)
	local pPlayer = Players[iPlayer]
	if pPlayer:GetCivilizationType() ~= iCanada then return end
	local pUnit = pPlayer:GetUnitByID(iUnit)
	if (pUnit == nil or pUnit:IsDelayedDeath()) then return end
	if pUnit:GetUnitType() == GameInfoTypes.UNIT_CARAVAN then 
		local pPlot = pUnit:GetPlot()
		**if pPlayer:GetTradeRoutes(pUnit:GetTradeRouteIndex()).ToID == iPlayer then**
			if pPlot:GetOwner() == -1 then
				pPlot:SetOwner(pPlayer, pPlayer:GetCapitalCity():GetCityID(), 1, 1)
			end
		end
	end
end
GameEvents.UnitSetXY.Add(YorkFactoryExpress)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Is this still an issue??

**Comment by pineappledan** [comment]
oops, forgot about this.
No it's not. Any use of GetRouteIndex() needs to have a return check for if == nil then return end, because feeding -1 into GetTradeRoute() will cause a CTD.
