### ISSUE TITLE
Luxury trade disparity

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4895]
_1. Mod version (i.e Date - 4/23):_ 11-9

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:

It's my second game with the current patch and there is one diplomacy issue I've seemingly discovered.
AI civilizations are not willing to trade their luxuries for mine on equal terms. Even if a civilization has friendly attitude towards me (I mean really friendly after signing Declaration of Friendship) they still value their extra luxuries vs mine at rate ~3/1 (like 350 to 111 something).
It is wrong, isn't it?

Some screenshots . 

![20181114212045_1](https://user-images.githubusercontent.com/16341598/48506925-40afe900-e853-11e8-87bf-1765537ce3e5.jpg)
![20181114212047_1](https://user-images.githubusercontent.com/16341598/48506929-41e11600-e853-11e8-96d2-ab2b7bedcde8.jpg)
![20181114212050_1](https://user-images.githubusercontent.com/16341598/48506931-4279ac80-e853-11e8-9fee-657b8d7ad417.jpg)

IIRC it hasn't been the case in previous iterations of the mod.

**Comment by SpankMyMetroid** [comment]
It depends on how much they value the luxury at the moment. If they are swimming in happiness they're not going to pay much for it (same as a human would). I think they will also take into account what luxes their cities are demanding and any luxes needed for city state quests.

**Comment by TechpriestEnginseer** [comment]
Indeed.
