### ISSUE TITLE
Bugged interaction when warring with married city states

### ISSUE THREAD

**Issue by SpankMyMetroid** [LoneGazebo/Community-Patch-DLL#4896]
_1. Mod version (i.e Date - 4/23):_
11/9

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
City states married by Austria will flip to "friendly" the turn after they declare war on you due to being allied to someone else. This is the case even if they change hands; when I was at war with two people, the CS had peace blocked, then was friendly next turn. When the other person allied the CS, I had peace blocked the first turn and friendly the next. 

You still can't interact with them with diplo units and they won't talk to you (see screenshot) but based on the screen they are still giving you friend-tier yields. I'm not sure how to test if this is actually the case.

Honestly, if this is unintended this is a pretty interesting mechanic, basically guaranteeing some amount of CS yields based on marriages. Flavorwise it makes sense too, your suitor basically has a coalition within the state that can "help" you, but off the books since they're supposed to be at war. I don't know how Austria is right now in the power rankings, but this could be a unique buff.  

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20181113202717_1](https://user-images.githubusercontent.com/20096768/48510249-455ba980-e821-11e8-8ce7-b8faa667f5bf.jpg)

**Comment by TechpriestEnginseer** [comment]
Wonder if https://github.com/LoneGazebo/Community-Patch-DLL/issues/4883 is related...
