### ISSUE TITLE
Tactical AI suggestion

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#4898]
_1. Mod version (i.e Date - 4/23):_
2018-11-09

_2. Mod list (if using Vox Populi only, leave blank):_

Tactical AI is very competent, and it looks hard to improve it without a heavy computational cost, but I'd like to discuss how this approach would perform. If I were to make an algorithm for my tactical playing, I'd do this:

While (CheckforDangerPoints) is true
{
  #Chooses the highest threat among danger points that is not already dealt with
  CurrentPoint =  PickMostDangerousPoint 
  AssignNearbyUnitstoCurrentPoint
  #ScoutMission is a subroutine that sends a scout, reevaluates threats and reassign units
  If (FriendlyMightInArea > 2 * EnemyMightInArea) { ScoutMission }
  #chooses best objective in this point
  CurrentPointTactic (returns Defense | Crippling | Killing | City)
  #Thinks best movements and hit order to achieve objective
  PlanCurrentPointTactic()
  If ((CurrentPointTactic <> Defense) AND (ExecuteCurrentPointTactic() = Success))
    { UnassignUnitsfromCurrentPoint }
  # ExecuteCurrentPointTactic() ends when there are no more units available (failure) or when objective is achieved (success), then adds current danger point to a list of danger points that are dealt with
}
EscortAndRetreat() #Use remaining movement points for moving to safety or escort civils

In other words, make the algorithm work on the highest threat first, scout, reevaluate, think the combat just for this point, and execute combat. If the goals of the threat are achieved, then release the units involved in this combat point for being used in next nearby threats, unless the units are commited to defense. Check again for the biggest threat that is not been dealt with already and repeat.

Good things of this algorithm
It thinks movements locally and sequentially, with fewer combinations, potentially faster.
It adapts within the turn to new recon data, and might change priorities.
It allows units that still have movement points left to be used in nearby actions.

Bad things
First movements don't take into account what units in nearby danger points might do.
Evaluating threats again after the previous threat has been dealt with may increase CPU work.
It's a lot of work :(

Thoughts?
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by tu-79** [comment]
Sorry about the bad formatting!

**Comment by ilteroi** [comment]
well this is actually quite similar to what's happening already ... but the devil is in the details

* how do you define most dangerous point
* the "FriendlyMightInArea > 2 * EnemyMightInArea" is a bit too simplistic, we need to consider many other factors here
* right now the "scouting" missions are very limited, it's just to make sure the target plot is actually visible (typically a city)
* the greedy approach of working through a list of targets and grabbing all the units around it (up to which distance?) is not optimal. ideally we would try to find the best target for each unit.
* there is little planning beyond the current move. a unit doesn't remember what it did last turn, so there's no need to "unassign" it from a target
* the real improvement would be to estimate the locations of invisible enemy units. AI is not cheating, right now it only considers visible enemy units in it's planning. note that units "discovered" during the turn are also considered for the moves coming after the discovery.

**Comment by tu-79** [comment]
Thanks for answering!

Most of this stuff you are already doing it. :)
As for scouting missions, the simplistic approach is just that, if I'm facing very few units compared to my own, I sure can spare a few to scout the side of the threat. Actually, units that are better at scouting should be prioritized. And other factors could be accouted for, but I didn't want to overextend.
Working through a list of targets is what would allow to use units for more than one purpose. I get that it's not that simple as 'the nearest ones', but you have already an algorithm for sorting this out, haven't you?
I was told that currently units are assigned to danger points, and they can only work on that point during the whole turn. Say, can a horsemen move next to a target just to provide flanking, attack that unit if it is not already killed by the others, and move again to provide flanking at another target in the same turn?

So, tactical AI watches for new discovered units as it procedes, and redo the plans each time it discovers a new unit? Good. Time consuming, but good.

That would be an improvement to be able to estimate attacks, yes, even for my own play :D. That's why you send scouts when you have more units in sight than the enemy.
