### ISSUE TITLE
Austria UA and UB

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#490]
1) There is a text mismatch between UA description and the marriage option
![8930_2015-08-05_00006](https://cloud.githubusercontent.com/assets/1131228/9091784/8ed038a8-3bbb-11e5-9882-24d751dca599.png)
![8930_2015-08-05_00007](https://cloud.githubusercontent.com/assets/1131228/9091792/92f8ac94-3bbb-11e5-9dd4-24612b71443d.png)
2) There is a text mismatch between the effect and description of Coffee House 
![8930_2015-08-05_00002](https://cloud.githubusercontent.com/assets/1131228/9091819/bc3bdab8-3bbb-11e5-9af3-ab913c41414a.png)

**Comment by LoneGazebo** [comment]
Danke, will fix.
