### ISSUE TITLE
Longhouse description & camps

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#4904]
Mod version 10-10

Hiawatha's Longhouses state they require a Nearby Forest to be built, but this was removed from the Herbalist prereq.
Further, they don't buff Camps at all, unlike the Herbalist they replace. I assume this is also unintentional?

**Comment by TechpriestEnginseer** [comment]
https://forums.civfanatics.com/threads/the-iroquois.550965/page-6#post-15079282

**Comment by Hokath** [comment]
Expertly foreseen.
