### ISSUE TITLE
Forbidden Palace civipedia

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4908]
_1. Mod version (i.e Date - 4/23):_11-9 EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

First it says that the wonder decreases the cost of gold purchasing by 15%, but later it show a figure of 5%.

![inked20181120184919_1_li](https://user-images.githubusercontent.com/16341598/48789425-a8ec4800-ecf5-11e8-8dca-217dda2c9435.jpg)

**Comment by Infixo** [comment]
This is unrelated. Extended Information presents only additional fields from Buildings table. -15% goes into a different table - Building_HurryModifiers.

**Comment by TechpriestEnginseer** [comment]
No HurryCostModifier is different from Building_HurryModifiers which the Civilopedia UI cannot unfortunately pick up on.

HurryCostModifier is how much the building increase(cuz negative) in gold investments.
