### ISSUE TITLE
CTD on turn 284

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#491]
The save: http://www.mediafire.com/download/e067kwa6scplu6w/Austria_CBP.Civ5Save
Mods:
CBP EUI
More Luxuries
Quick Turns http://steamcommunity.com/sharedfiles/filedetails/?id=220250184
InfoAddict http://steamcommunity.com/sharedfiles/filedetails/?id=79000477

**Comment by LoneGazebo** [comment]
Thanks, I’ll give it a look.

**Comment by LoneGazebo** [comment]
Took a look - it loaded and ran fine for about four turns. Any dump file in your civ 5 install?

**Comment by Radost** [comment]
No dump file but I think I know the reason: recent AMD driver updates.
The game proceeds just fine in windowed mode and crashes in fullscreen.

**Comment by LoneGazebo** [comment]
Makes sense. On windows 10?

**Comment by Radost** [comment]
Windows 7 x64
It's pretty common for AMD to have issues out of blue on driver updates.

**Comment by Radost** [comment]
I get a CTD further in the game. Except now it crashes regardless of fullscreen/windowed.
http://www.mediafire.com/download/e067kwa6scplu6w/Austria_CBP.Civ5Save
