### ISSUE TITLE
Boarding Party description incosistency

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4911]
_1. Mod version (i.e Date - 4/23):_11-9 EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Mouse-over tip for Boarding Party promotion says it increases units **combat strength** by 15%, but the crosshair sign actually stands for **ranged combat strength**.

![20181121185243_1](https://user-images.githubusercontent.com/16341598/48856539-55dec780-edbf-11e8-8d35-381a537e78b6.jpg)
![20181121185243_1](https://user-images.githubusercontent.com/16341598/48856596-7dce2b00-edbf-11e8-99c4-ff7c3273392c.jpg)

**Comment by TechpriestEnginseer** [comment]
Cool
