### ISSUE TITLE
Game crashes on AI turn

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#4915]
_1. Mod version (i.e Date - 4/23):_ 11-9 EUI, 11-21 EUI

_2. Mod list (if using Vox Populi only, leave blank):_ UI Promotion tree, Faster Aircraft Animation

_3. Error description:_  Game crashes at AI turn around turn 351

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2606091/Logs.zip)

**Comment by ilteroi** [comment]
is it possible that someone is conquering and liberating a city state in that turn?

**Comment by saamohod** [comment]
I can't tell. It's hard to notice this during AI turn.
