### ISSUE TITLE
Flanking not added when attacking into flank

### ISSUE THREAD

**Issue by johanbest69** [LoneGazebo/Community-Patch-DLL#4916]
_1. Mod version (i.e Date - 4/23):_
11-9

Combat window says 5% flank is added for defenders but it is not (CS unaffected). I assume unintentional

![issue4](https://user-images.githubusercontent.com/43484857/48874543-f24cac80-ee47-11e8-9247-971ae7e08770.png)

**Comment by ilteroi** [comment]
there shouldn't be any bonus in a 1 on 1 like that. so just a visual problem

**Comment by TwoPodRay** [comment]
@ilteroi there are two units there on defense, the pathfinder is behind the label for the Mongolian Spearman

**Comment by ilteroi** [comment]
funny. missed that. so is the third unit friend or foe?

**Comment by johanbest69** [comment]
Foe,  I traced the issue through the code first, and then confirmed in game.

As you can see in the code it is now only called through CvUnit::GetMaxAttackStrength and will only will give you a positive modifier value.     (previously was called in def and attack through GetGenericMaxStrengthModifier)

**Comment by ilteroi** [comment]
i don't understand. what is it?

if you're referring to GetEffectiveFlankingBonus(), that is called for the defender as well.

anyway, good find, the parameters from lua were passed incorrectly in lGetMaxDefenseStrength()

**Comment by johanbest69** [comment]
You're right!  I don't know how I missed that...
