### ISSUE TITLE
Automatic installer not installing EUI

### ISSUE THREAD

**Issue by Fir3Li0n** [LoneGazebo/Community-Patch-DLL#4917]
_1. Mod version (i.e Date - 4/23):_
11-9

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Interface errors on game creation make the game unplayable when installing using the VP w/ EUI option

_4. Steps to reproduce (optional):_
Download clean install of civ 5,-then use automatic installer to install with option VP w/ EUI. Create game and interface errors popup repeatedly.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Fir3Li0n** [comment]
I don't have internet access right now, but my logs are in the post "ui errors"

**Comment by TechpriestEnginseer** [comment]
Like I said you don't have EUI installed properly.

**Comment by Fir3Li0n** [comment]
Hello, does this mean the 11-9 auto installer is broken? I haven't installed a single other mod or ever used an older installer.

**Comment by Fir3Li0n** [comment]
Do I need to download an external EUI mod that's more up to date?

**Comment by Fir3Li0n** [comment]
Was able to reproduce this bug on a separate computer with the new 11-21 patch. It appears the auto installer is NOT installing EUI properly. I don't even have the ui_bc1 folder after installation.

**Comment by Fir3Li0n** [comment]
Done. No change. ui_bc1 still fails to create anywhere on the computer.

**Comment by TechpriestEnginseer** [comment]
[UI_bc1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2609361/UI_bc1.zip)
In that case just download this and put it in your DLC folder manually.

**Comment by Fir3Li0n** [comment]
That did it, cheers. Not sure why installer is failing!

**Comment by Fir3Li0n** [comment]
Yes, I'm brand new. This was my first install ever.

**Comment by ryanmusante** [comment]
Welcome.
