### ISSUE TITLE
upgrade costs are around *2 from previous version  11/21/18 verson

### ISSUE THREAD

**Issue by kawyua** [LoneGazebo/Community-Patch-DLL#4919]
_1. Mod version (i.e Date - 4/23):_
11/21

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
unit upgrade costs are really high now. Is it intentional? If so, tool tip needs an update.
Some multiplier is being done when it shouldn't be

is there some issue with the latest commit to coredefine.sql?
![image](https://user-images.githubusercontent.com/12496046/48900325-109eb200-ee20-11e8-98d5-0ce0f3bd7042.png)

_4. Steps to reproduce (optional):_
try to upgrade

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
forgot to turn on logs
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[AutoSave_0063 BC-1480.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2607719/AutoSave_0063.BC-1480.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![image](https://user-images.githubusercontent.com/12496046/48899081-8a34a100-ee1c-11e8-91b5-c86fc764e872.png)

**Comment by LoneGazebo** [comment]
I removed some bad legacy code, it was artificially deflating values by mistake.

**Comment by saamohod** [comment]
@LoneGazebo 

I.e. the new values are what it should be?

**Comment by LoneGazebo** [comment]
They’re the values based on the actual defines. Cost values can be discussed in the thread.

**Comment by kawyua** [comment]
modifying 
UPDATE Defines SET Value = '2' WHERE Name = 'UNIT_UPGRADE_COST_PER_PRODUCTION';
to a 
UPDATE Defines SET Value = '1' WHERE Name = 'UNIT_UPGRADE_COST_PER_PRODUCTION';
would be close to the costs it was before, but this variable is connected with the tool tip, so the original cost on the tooltip is halved, too. maybe the legacy code should stay or the tool tip number needs the correct multiplier.

**Comment by saamohod** [comment]
>Cost values can be discussed in the thread.

In previous version the cost of upgrade was relatively high imho. It was ok with me because it made me think whether I should upgrade a valuable unit or disband/gift/sacrifice in war an ordinary unit. 
Now that the cost is twice as high it makes even less sense to upgrade even highly promoted units (unless the player swims in cash).
Just my 5 cents.
