### ISSUE TITLE
Golden Age culture modifier text mismatch

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#492]
As it can be seen, on the top panel it says 20%, but in the city view - 15%. Production is fine in that sense.
![culture1](https://cloud.githubusercontent.com/assets/12978597/9100556/01634954-3be5-11e5-8807-e8a711808e9b.jpg)
![culture2](https://cloud.githubusercontent.com/assets/12978597/9100558/0494820a-3be5-11e5-87b4-24f7f0229d16.jpg)

**Comment by LoneGazebo** [comment]
Using any mods that affect this? I don't edit that text or that value anywhere in the CP or the CBP.

**Comment by Edaka** [comment]
Might be the case, actually, as there are plenty of mods. However, I am pretty sure that none of them are supposed to change these values.

My mod list (at the moment of taking the screenshot): 
Community Patch (7-24v3);
Community Balance Patch (7-24v3);
Community Balance Patch - Compatibility Files (EUI) (7-24);
Civ IV Diplomatic Features (6-19);
CSD for CBP (6-19);
EUI (CBP Version) (7-21);
Thal's FlagPromotions - CPP version;
Reseed! (v11);
Randomize City Names (v2);
R.E.D. Modpack (v27);
Quick Turns (v10);
Music Changer (v2);
Barathor's More Luxuries (v155);
More Great Works (v3);
InfoAddict (v22);
Improved Air Recon (v1);
Historical Religions Edit (BNW or GK) (v44);
Great Prophet Historical Names (BNW or GK) (v31);
Civ Names by Policies (v8);
Global - Religious Settlers (v1);
Global - Local Generals (v2);
Global - Enable Magellan (v8);
Global - CS Unit Upgrades (v2);
Global - City State Airbases (v3);
Global - Air Routes (v1).

I'm guessing Civ Names by Policies might have something to do with this - there is an overlap between this mod and the CBP as they both have EspionageOverview.lua. The ingame espionage overview is fine, though. Also I'm guessing some of these "global" Whoward's mods are already incorporated into CBP, but I'm not sure.
