### ISSUE TITLE
UnitPanel with Border Growth Points.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4920]
```UnitPanel.lua:1801: bad argument #1 to 'L' (string expected, got nil)```

I swear.. this seems so familiar.

Whenever I try to build an improvement with Border Growth Point bonuses, it backfires.. I just can't explain why..

edit: wait now i remember https://github.com/LoneGazebo/Community-Patch-DLL/issues/2849

**Comment by TechpriestEnginseer** [comment]
nvm no it didnt work

**Comment by LoneGazebo** [comment]
I've registered the enum. Should work in the upcoming beta balance.

G
