### ISSUE TITLE
FreeUnitsTechAppropriate

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4923]
The code doesn't check for if the unit the event spawns has a unique unit. So Spain will randomly get knights instead of conquistadors and likewise for other unique units.

**Comment by TechpriestEnginseer** [comment]
https://forums.civfanatics.com/threads/community-patch-events-development.569321/page-16#post-15286371

**Comment by LoneGazebo** [comment]
Well you didn't specify _that_ :)

That's an entirely new set of function parameters, I'd need to look.
