### ISSUE TITLE
Leader UI not working properly

### ISSUE THREAD

**Issue by SobusJan** [LoneGazebo/Community-Patch-DLL#4928]
_1. Mod version (i.e Date - 4/23):_
Manually removed 10-10 (no problems there) and installed 21-11-1 43 CIV EUI

_2. Mod list (if using Vox Populi only, leave blank):_
All other mods disabled (same thing happening with and without them - 3UC,InfoAddict,Flag promotions for EUI)

_3. Error description:_ 
Upon encountering the civ, screen is blank with no buttons, hovering over portrait doesn't show usual info, cannot easily start war, some part of the top panel is missing.

_4. Steps to reproduce (optional):_
Visible from the beginning of the game and when meeting someone. Screens, Save and logs attached.\:

![zrzut ekranu 2018-11-26 21 32 40](https://user-images.githubusercontent.com/43049242/49013844-caec3b80-f1c9-11e8-9944-19ca1802126e.png)
![zrzut ekranu 2018-11-26 21 32 45](https://user-images.githubusercontent.com/43049242/49013845-cb84d200-f1c9-11e8-88d0-210eeb0e1b95.png)
![zrzut ekranu 2018-11-26 22 08 44](https://user-images.githubusercontent.com/43049242/49013846-cb84d200-f1c9-11e8-99d7-baf8ee3c01e7.png)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2615464/Logs.zip)
[Askia_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2615467/Askia_0000.BC-4000.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ryanmusante** [comment]
Best thing to do is disable leaderheads.

**Comment by Infixo** [comment]
Syntax Error: C:\Users\Jan Sobus\Documents\My Games\Sid Meier's Civilization 5\MODS\(6c) 43 Civs CP\EUI\EUI_tooltip_library.lua:457: ')' expected (to close '(' at line 454) near 'return'
This is one of the core files included by many others, so that error breaks many features in EUI.
Try to make a new, clean installation however. This file looks ok in the repository.

**Comment by MJWedding** [comment]
Reinstalled both VP (manually cleaning steamapps/EUI and MODS folders) and, when it didn't work, the whole game (again cleaning all remaining folders manually). The problem is still the same ...

**Comment by LoneGazebo** [comment]
@MJWedding is correct, the file is missing a )

the line (457) should be: 

tips:insertIf( obsoleteTech and L"TXT_KEY_PEDIA_OBSOLETE_TECH_LABEL" .. " " .. TechColor( L(obsoleteTech.Description) ) )

it is missing the last ).

Sorry for the trouble! I'll fix in the next incremental.

**Comment by Infixo** [comment]
How come you have a different line than in repository? 457 is:
tips:insertIf( item and L"TXT_KEY_PEDIA_PREREQ_POLICY_LABEL" .. " " .. PolicyColor( L(item.Description) ) )
The one you listed is 487 and it also has 3 ")"
Some desync in installation package?

**Comment by MJWedding** [comment]
Thanks Guys, added the third ')' and it works. It seems that a smaller UI issue is still there, the global happiness tooltip at the top screen is not working after the fix (When hovered over for the first time, shows just "brief description". When hovered over checking other item, it just shows the other item (gold income breakdown for example)
![zrzut ekranu 2018-11-28 07 45 58](https://user-images.githubusercontent.com/43049242/49115961-e64d6880-f2e7-11e8-98fc-2207d2c0eb49.png)
 :
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2622067/Logs.zip)

**Comment by LoneGazebo** [comment]
[TopPanel.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2623058/TopPanel.zip)

Replace the TopPanel.lua in C:\Users\~\Documents\My Games\Sid Meier's Civilization 5\MODS\(6c) 43 Civs CP\EUI with the file above.

**Comment by MJWedding** [comment]
Smooth as butter, thanks!
