### ISSUE TITLE
Confusing top panel tooltip culture values

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#493]
There are at least 3 different happiness modifiers for culture, as is shown on the screenshot. The phrasing gets confusing as it doesn't specify how and why exactly happiness influences culture yields in each of the three situations.
![culture3](https://cloud.githubusercontent.com/assets/12978597/9100642/09bacd92-3be6-11e5-95c7-74023e64439d.jpg)
For example, the "35 excess happiness" is there due to one of the aesthetics policies. The "150 from happiness and/or golden age" is there just because of the golden age and happiness doesn't modify this one directly. However, the "80 due to happiness" is, in fact, there due to the 10% happiness modifier, if I'm correct.
Sorry if I'm being picky, but I believe this issue can cause some misunderstanding for someone who isn't familiar with the mod.

**Comment by Radost** [comment]
It is confusing by design.

**Comment by LoneGazebo** [comment]
Your top bar tooltip is missing a lot of information. The CBP's tooltip is much more clear than that normally.

**Comment by Edaka** [comment]
Weird, I'm using the EUI (CBP Version) (7/21) aside from the other mods mentioned in #492

**Comment by LoneGazebo** [comment]
I think one of those mods is overriding your toppanel.lua
G

**Comment by Edaka** [comment]
It must be so, then. In the end, it is probably near impossible to track down the mod that's guilty and it's none of your competence. Thanks, anyway. This and the #492 can be closed (assuming they're not actual CBP or CP issues).

**Comment by Edaka** [comment]
Wait, before you do close the issues, let me double check with just the CBP package. Just to make sure it's actually my mods (:

**Comment by Radost** [comment]
> Your top bar tooltip is missing a lot of information. The CBP's tooltip is much more clear than that normally. What are you using that makes it default?

Mine is like this too. 
![8930_2015-08-06_00001](https://cloud.githubusercontent.com/assets/1131228/9119796/15751672-3c92-11e5-9bab-04d50ddf3cbc.png)

**Comment by LoneGazebo** [comment]
Sounds good. I'll let you close.

Radost, your culture tooltip looks fine.

**Comment by Edaka** [comment]
Tried checking with these mods enabled: 
![mods](https://cloud.githubusercontent.com/assets/12978597/9142592/5178911e-3d49-11e5-9b4e-dde9f5c7160a.jpg)
Cleared cache and moduserdata folders - the top panel still looks like in the OP for me. Don't know what is causing the trouble, but, apparently, it only affects my game. If I figure it out, I'll let you know.
