### ISSUE TITLE
Crashes late game, usually in the Modern Era.

### ISSUE THREAD

**Issue by EJFores** [LoneGazebo/Community-Patch-DLL#4936]
_1. Mod version (i.e Date - 4/23):_ 11-9 (NoEUI)

_2. Mod list (if using Vox Populi only, leave blank):_
![image](https://user-images.githubusercontent.com/32749043/49248471-63a7d480-f3df-11e8-8cd5-6d8ddd0d6580.png)

_3. Error description:_ I was told to report this crash from reddit. From some reason around the modern age my game crashes for seemingly no reason. This has happened plenty of times. However this time i was able to save the game a couple turns before the crash. It is repeatable and will occur within 1 to two turns no matter what i do.

_4. Steps to reproduce (optional):_
Doesnt matter, make some choices and move some troops. Within ending 1 or two turns the game will crash. 

Log files, Save game, CvMiniDump.dmp, and ModList:
[Shaka_Saves_Then_Crashes.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2630729/Shaka_Saves_Then_Crashes.zip)

**Comment by EJFores** [comment]
Not at the time of crashing no. I had already updated one of the units and it was idle doing nothin. Although it could have been one of the AI attempting to do either of those.

**Comment by TechpriestEnginseer** [comment]
I'm suspecting a mod conflict in one of those mods... just not sure which one.

**Comment by EJFores** [comment]
I will try it without the added wonder mods then and see what happens. If that doesnt work ill test without the Navy additions.

**Comment by Infixo** [comment]
Guys, both ENW and VPWE are being used for more than a year and have thousands of downloads. There never, literally, was a single report about CTD or Lua errors for that matter, that was caused by them. So, I am pretty sure the problem is somewhere else.

**Comment by ilteroi** [comment]
please retry with the latest hotfix

**Comment by EJFores** [comment]
Just updated to the 11-21-3 version. Still CTD.

**Comment by Infixo** [comment]
Zip the mods that you are using (except VP ofc) and post it here. I will try to debug this situation then.

**Comment by EJFores** [comment]
[MODS.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2637519/MODS.zip)
Sorry for the late response, here you go.

**Comment by ryanmusante** [comment]
Does it matter that the load order of mods isn't consistent? For my configuration, I manually set 4,5,6 to load in order with dependencies.

**Comment by TechpriestEnginseer** [comment]
Actually it does.

**Comment by TechpriestEnginseer** [comment]
Unless wonders expanded crash because it was missing a resource type that didn't exist because More Luxuries didn't load in first.. possibly...

the 6 aren't exactly an issue since those are UI files, they can load whatever order they're in and extremely save-game compatible (as long as they are purely UI files).

**Comment by Infixo** [comment]
The mod load order is indeed a bit off. 
VPWEE has a hard dependency set for More Luxuries id="be2d13ee-d18d-410e-8f04-7cd19cd99a98", so it _cannot_ load before it. I suspect you have an "unofficial" More Luxuries.
Plus I find a bit weird that (1) Community Patch isn't the first to load.
My load order is the following:
![obraz](https://user-images.githubusercontent.com/25866684/49392091-b6f68b80-f72d-11e8-992f-5726bc68cc55.png)

**Comment by Infixo** [comment]
Anyway, the save doesn't load for me at all with VP 11-21-3. It crashes when reading CvGame object, specifically m_AdvisorMessagesViewed (line 11034 in CvGame.cpp).

**Comment by EJFores** [comment]
As far as i know i do not have anything unofficial for Vox. I have really only ever used the automatic installer available from reddit or the civ forums.

Since load order is an issue is there anyway you can  forcefully reorganize a load order? Cause if so then we could see what happens when Vox is lost aded then city limits. 

And that error code says something about an advisor message. Could it be possible that two seperate error msgs are trying to alert me at the same time? More than once Vox seemlingly ignores the previous turns advisor msgs or wonder popups sometimes even after the turn has ended. But i assume thats just my computer giving it flux.

**Comment by Infixo** [comment]
Like I said - with _hard_ dependency it _cannot_ load before. That is how the loader works. If it loads it means that your ML has a different ID than VP version of ML. It happens often when people subscribe to this mod on Steam. The Steam version is different and NOT to be used.

**Comment by EJFores** [comment]
So how would i go about changing the Mod Loader?

**Comment by Infixo** [comment]
1. Start Steam, unsubscribe all mods, close Steam.
2. Remove everything from MODS folder and Cache folder.
3. Start Steam, subscribe only to those 6 mods (vpwe, enw, cl, pp, 2 wonders).
4. Install VP.
5. Run Civ 5, select Mods.
At this point the game should download and install all required mods from Steam. May take a moment.
6. Check your MODS folder - you should have ONLY mods listed on both screenshots.
7. Select all mods and go further.
You can check the load here and see if it is different than previously.
8. Play.

**Comment by MoiMagnus** [comment]
@LoneGazebo Is it normal that (4) C4DF only depends on (2) CBO and not on (3) CSD? It explains why sometimes (3) CSD is loaded after (4) C4DF.

**Comment by ryanmusante** [comment]
Each time I update, I manually add the following to ensure 1-6 load in order and than for all my modmods, I add a dependency to point to 6A.

(4) C4DF - CBP.modinfo
```
  <Dependencies>
	<Mod id="eead0050-1e3f-4178-a91f-26cf1881ac39" minversion="0" maxversion="999" title="CSD" 
```
More Luxuries.modinfo
```
  <Dependencies>
	<Mod id="c7bf7064-d1b1-4708-9e93-7a1560868582" minversion="0" maxversion="999" title="C4DF" />
```
(6a) CBO.modinfo
```
  <Dependencies>
	<Mod id="be2d13ee-d18d-410e-8f04-7cd19cd99a98" minversion="0" maxversion="999" title="More Luxuries" />
```
