### ISSUE TITLE
Crash to desktop on AI's turn

### ISSUE THREAD

**Issue by pettter1996** [LoneGazebo/Community-Patch-DLL#4937]
_1. Mod version (i.e Date - 4/23):_
11/21

_2. Mod list (if using Vox Populi only, leave blank):_
(1) Community Patch
(2) Community Balance Overhaul
(3) CSD for CBP
(4) Civ IV Diplomatic Features
(5) More Luxuries
(6b) Community Balance Overhaul - Compatibility Files (No-EUI)

_3. Error description:_ 
Civ 5 constantly crashes to desktop on the AI's turn (China). Declaring war and using directX 9 does not rectify the issue.

_4. Steps to reproduce (optional):_

Proceed on to the next turn.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2630841/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Augustus Caesar_0186 AD-1260.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2630844/Augustus.Caesar_0186.AD-1260.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2630849/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by ilteroi** [comment]
please retry with the latest hotfix version

**Comment by pettter1996** [comment]
Sorry where can I get that? I thought I am already using the latest version. Thanks

**Comment by pettter1996** [comment]
Thank you it works now 👍
