### ISSUE TITLE
No city states, ruins or strategic resources

### ISSUE THREAD

**Issue by chimun** [LoneGazebo/Community-Patch-DLL#4938]
_1. Mod version (i.e Date - 4/23):_ Autoinstaller Vox Populi ((11-21-1)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Virtually the same as described here https://forums.civfanatics.com/threads/bug-reports-post-here.528142/page-195#post-14072408. No city states, ruins, strategic resources are really sparse (Monopolies says: _Horses "You have 1 out of 2 in the world"_ , and no luxury resource at all. Looking at the log files, I can see the same error as the post. I have all DLC's and _Civ V version is 1.0.3.279_

_4. Steps to reproduce (optional):_  Just start any game. I used the autoinstaller with EUI.
I remember one time, my friend was using my pc, and he got some luxuries (cotton to be precise). According to him, he created a standard game with a __random__ leader and the Comunnitas map.
I also noticed that the location:
C:\Users\XXXX\Documents\My Games\Sid Meier's Civilization 5\MODS\(5) More Luxuries\Lua
only has a folder, and that folder has a Terra.lua file. Reading here and there, I found that the file AssignStartingPlots.lua may be missing, so I copied it onm the Luxuries LUA folder, with no results.

The minor graphical bugs are:
1) In the policy tree, tradition perks are messed up.
2) On city view, some plot do not show their yields.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional): SORRY I LOST THE SCREENSHOTS LOL

5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2631708/Database.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2631709/xml.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2631718/Lua.log)

**Comment by MoiMagnus** [comment]
Unsubscribe to any mod named "More Luxuries" on steam. In general, make sure you don't have two mods in the MODS folder that have approximately the same name (like both the More Luxuries from steam and from the autoinstaller).

Then, reinstall VP with the autoinstaller.

**Comment by ryanmusante** [comment]
@MoiMagnus is it possible to include a check in the installer to alert of conflict for pre-existing mods like more luxuries? It could assist new players.

**Comment by Infixo** [comment]
So, maybe change the ID of the More Luxuries from VP?

**Comment by chimun** [comment]
@MoiMagnus  @Vyyt02 
My game is up-to-date 1.0.3.279.
One of the first things I tried was a complete removal.
Uninstalled the game and manually deleted the Civ5 folders in ...\My Games\Sid Meier's Civilization V\... , so no traces of a previous installation would eventually create a conflict.
After this wipe out, I used the recommended auto-installer.

I think the file __AssignStartingPlots.lua__ has a lot to do with this, as displayed in the log files.
Do you need any additional info I could provide?
Thanks :)

**Comment by MoiMagnus** [comment]
The AssignStartingPlots.lua is not supposed to be in te (5) More Luxuries. It is supposed to be in the (6a) Compatibility Files / LUA.

(Or the (6b), or the (6c), depending on the options you chose in the autoinstaller).

A check:
After selecting the mods and loading them, you should have a screen with "SINGLE PLAYER" at the top, the list of mods at the middle, and "BACK" at the bottom. 
The list of mods should contain exactly 6 mods, numbered from (1) to (5) and then either (6a), (6b) or (6c). If any of the 6 mod is missing, this is your problem. If any mod appear without its number at the beginning of the name, this is your problem.

**Comment by chimun** [comment]
> The AssignStartingPlots.lua is not supposed to be in te (5) More Luxuries. It is supposed to be in the (6a) Compatibility Files / LUA.
> 
> (Or the (6b), or the (6c), depending on the options you chose in the autoinstaller).
> 
> A check:
> After selecting the mods and loading them, you should have a screen with "SINGLE PLAYER" at the top, the list of mods at the middle, and "BACK" at the bottom.
> The list of mods should contain exactly 6 mods, numbered from (1) to (5) and then either (6a), (6b) or (6c). If any of the 6 mod is missing, this is your problem. If any mod appear without its number at the beginning of the name, this is your problem.

Thanks fir the fast reply. I'll check this as soon as I get home today and let you know the results.
Cheers,

**Comment by chimun** [comment]
Sorry for the late reply. Mods from 1 to 5 plus 6a present.
I also learnt how to take and be able to see a screenshot...
Here it goes, let me know what you recommend. I'll pay more attention to my email inbox this time.
![civ5screen0002](https://user-images.githubusercontent.com/10514733/49534252-d57c9400-f89f-11e8-8c0e-ae741847402f.png)

**Comment by chimun** [comment]
I took a SC of a probably unrelated graphical bug, just in case
![civ5screen0000](https://user-images.githubusercontent.com/10514733/49543225-652d3d00-f8b6-11e8-8bb2-6647a8461a78.png)

**Comment by LoneGazebo** [comment]
You've clearly got a bad install.

Wipe everything from your MODS folder.

In your ~\steamapps\common\Sid Meier's Civilization V\Assets\DLC folder, remove anything called MODSPACK or UI_Bc1.

Redownload the latest autoinstaller. Let it autoinstall.

(1) through (6a) should appear in your MODS folder. If they don't, you have a strange install (it assumes c:/)

UI_BC1 should appear in your DLC folder (it too assumes c:/)

If you're doing all that, and loading the game as instructed above, you're good to go.

If you're missing any DLC your game will break.

**Comment by chimun** [comment]
My install might be strange because I install my games on Partition (D:). I may reinstall in C:, on default folder and let you know.

**Comment by LoneGazebo** [comment]
It is likely that this is the problem.

**Comment by chimun** [comment]
Installing all on default folders ATM, fingers crossed.

**Comment by chimun** [comment]
Exact same problems, run out of ideas. I recall beign able to play the game on .144.
I think is worth the shot

**Comment by chimun** [comment]
> 
> 
> Not sure what to tell you, sorry. .279 is required, make sure you're playing the game in English, and that - when you load the mods - you click 'Next' and then start the game from there.

Yep, always in English

**Comment by chimun** [comment]
OK, maybe my last post, in case someone got the same issue.

On my last game, I noticed that the resources that appeared after researching the needed tech, __always__ appeared inside the territory if the city at that moment. And no resources were created or (revealed) in no man's land, just in cities (mine or AI).

I tried to remember when the CBP stopped working:
1. It was before the Authority Nerf, I remember that specially because it surprised my alot that I could get a free unit for any city with multiply of _8_.
2. And I'm almost sure that I played using .144 at least for 10 games, without any noticeable issue. When I came back to the CBP page to update, I saw __.279__ requiered. Then I freaked out because I thought I would've missing lots of awesome features, but the game remained the same and Authority was washed away by the tides of meta.

Thank you all. I'll check from time to time I something new pops out.

**Comment by smalltimepro** [comment]
I have got the exact same problem. Up to date Civ version with latest vox populi install (12-18-1). I have no other MODS installed except for IGE which non conflicting as far as I understand. The file AssignStartingPlots.lua in 6a is definitely the problem as removing/renaming it provides for correct resource placment (even though missing out on the extra luxury types. I also get the UI bug in tradition as in screenshot from @chimun
