### ISSUE TITLE
AI liberating civ's cities they are at war with

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#494]
I've seen this happen a couple of versions ago, so excuse me if this has been fixed. 
Here's the scenario: let's say civ A captures civ's B city. Civ C is at war with both civ A and civ B. Civ C captures the aforementioned city and chooses to liberate it. As a result, civ C ends up capturing the city second time anyway.

**Comment by LoneGazebo** [comment]
Tweaked. Thanks!
