### ISSUE TITLE
(Tooltip) Customs House (and gold buildings in general?)

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4940]
_1. Mod version (i.e Date - 4/23):_
11-21-1

_2. Mod list (if using Vox Populi only, leave blank):_
none

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/34615525/49265762-77742a80-f421-11e8-8d83-3ac881fdeee4.png)
What is the +2 Gold >> and +2 Gold << supposed to work? It seems to mean that both trade routes originating and terminating in the city gain +2 gold; however, the tooltip only mentions the terminating trade routes.
![image](https://user-images.githubusercontent.com/34615525/49265836-c621c480-f421-11e8-965b-a1af2f0fd360.png)
Caravanaseries, on the other hand, explicitly mention originating trade routes, but because it's only for land routes, it can't be made symbolic.

**Comment by TechpriestEnginseer** [comment]
no that's cuz it's eui

**Comment by Infixo** [comment]
How is the wrong tooltip related to EUI then? The „descriptive” part is just what modders put into. The individual lines usually show separate fields from DB. There are 6 different parameters related to TRs: extra gold for inbound/outbound (first picture), land only - range and extra gold (second picture), sea only - range and extra gold (used by Harbor?)

**Comment by LessRekkless** [comment]
So the tooltip should say (because "in" isn't descriptive enough) something like:

"Trade routes originating and terminating in this city gain +2 gold."
Replacing:
"Trade routes to this city gain +2 gold."

Markets should also have this text, and I don't think it has anything at all.

**Comment by TechpriestEnginseer** [comment]
no we're completely off.

That EUI text represents that you get +2 Gold -> if a **FOREIGN** Trade Route and the owner of that trade route receives +2 Gold <-

I've updated the tooltip to reflect this. No promise that modmods will follow up on this.
