### ISSUE TITLE
Duplicate Melee Naval Promotion (Navigator I)

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4941]
_1. Mod version (i.e Date - 4/23):_
11-21-1

_2. Mod list (if using Vox Populi only, leave blank):_
none

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/34615525/49266766-60cfd280-f425-11e8-9a17-73f5170868af.png)
![image](https://user-images.githubusercontent.com/34615525/49266746-5281b680-f425-11e8-9ed4-245e0747d5ab.png)
Navigator I seems to be duplicated, perhaps because it replaced _both_ the +1 sight promotion and the +1 movement promotion?

_4. Steps to reproduce (optional):_
Upgrade a melee unit to Boarding Party I, then get another promotion.

**Comment by TechpriestEnginseer** [comment]
ooh I know the problem
