### ISSUE TITLE
Last version UNHAPPY distress

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4942]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
EVvery single pop in every single city produces Distress. Basically my pop number = Distress number. I did load an old save. Is it possible to remove that, or should I revert to the previous, pre-hotfix version?

**Comment by LoneGazebo** [comment]
Give the cities a chance to reset via pop growth.

**Comment by Enrico-Swagolo** [comment]
I let them grow. Initially it was okay, but now in mid medieval most of my cities are all heavily Distressed (about 50% of the pop). I focus all the Production buildings and Barracks line, but it's only getting worse. It'll get okay soon, but I have to stop growth everywhere. I  play with a reduced unhappiness (changed 675 to 475 per pop in city happiness file), I can't imagine what would be happening had I not done that.

**Comment by LoneGazebo** [comment]
Weird, the AI had barely any issues in my tests.
