### ISSUE TITLE
Feature Request - New Table: Improvement_AdjacentFeatureYieldChanges

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4943]
Currently, there exists tables for improvements to give extra yields for every adjacent Improvement/Resource/Terrain/City/Mountain, but one doesn't exist for features (that aren't mountains). Would it be possible to add such a table? It would be nice to have for adding bonuses for adjacent oases/floodplains/forests, etc.

**Comment by LoneGazebo** [comment]
Plot variables like this are very expensive - at the moment, no, not unless we can reclaim some memory elsewhere in cvplot.

G

**Comment by pineappledan** [comment]
If an Improvement_AdjacentFeatureYieldChanges table were made there would be no need for Improvement_AdjacentMountainYieldChanges... That at least saves a bit of space.

Out of curiosity, what does Improvement_AdjacentPlotYieldChanges do? Does that even do anything?

**Comment by LoneGazebo** [comment]
Well, not exactly. Improvement_AdjacentFeatureYieldChanges  is a jagged multi array, whereas Improvement_AdjacentMountainYieldChanges is a simpler single array. The former is much more expensive (as it is, at base, numFeaturesXnumYieldsXintegerValues.

**Comment by LoneGazebo** [comment]
Re: Improvement_AdjacentPlotYieldChanges, I think it does: 
PLOT_MOUNTAIN,	//use only with terrain type mountain
	PLOT_HILLS,
	PLOT_LAND,
	PLOT_OCEAN,
Which I don't think actually do...anything. Mind asking on the modforum if anyone uses it? Vanilla and VP do not use it.

**Comment by pineappledan** [comment]
Sure, I'll open up a thread on the general forum. 

What I'm specifically hoping to add is an improvement which gets +1 production for every adjacent forest/jungle. Given that is 2 different features, I don't suppose adding an array specific to whose features would actually save on size...

**Comment by LoneGazebo** [comment]
If I did it, I'd want it to be fully functional- I hate 'piecemeal' memory elements.

**Comment by pineappledan** [comment]
Regarding other consolidations, Improvement_YieldAdjacentSameType is used by the Moai. You can accomplish the same thing just by using Improvement_AdjacentImprovementYieldChanges

**Comment by LoneGazebo** [comment]
@pineappledan yeah, but that's a vanilla function, being used by vanilla. I try to avoid messing with those.

**Comment by pineappledan** [comment]
okay... :(

**Comment by LoneGazebo** [comment]
ah gotcha - yeah, I try to avoid this for compatibility purposes.

**Comment by pineappledan** [comment]
So it's been 22 hours and no one has gotten back re: that Improvement_AdjacentPlotYieldChanges.

**Comment by LoneGazebo** [comment]
Lo, it is done.

Test for you: 
[(1) Community Patch (v 88).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2636524/1.Community.Patch.v.88.zip)

Don't forget to delete the LUA folder if you are testing on a full setup.

**Comment by LoneGazebo** [comment]
BTW this was a whoward table, not vanilla, so I doubt anyone will miss it.

**Comment by pineappledan** [comment]
You da best! I'll give this a spin tomorrow

**Comment by pineappledan** [comment]
The new table doesn't appear to do anything:
![image](https://user-images.githubusercontent.com/33136027/49389979-e2a15380-f6e4-11e8-83f9-b49e9ba1b67d.png)
I hoped the table would add +1 production to the Noow for every forest/jungle, but it looks like the table is set up to give +1 to the adjacent feature, rather than give the yield to the improvement. That's fine, and doesn't really make a huge difference for what I was going for. Regardless, neither the Noow nor the adjacent forest is getting any additional yields.

**Comment by LoneGazebo** [comment]
I misunderstood what you wanted, I'll fix.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2642117/CvGameCore_Expansion2.zip)

Drop this in your CP.

**Comment by LoneGazebo** [comment]
NOT savegame compatible with the DLL I posted above. Sorry.

**Comment by pineappledan** [comment]
![image](https://user-images.githubusercontent.com/33136027/49417366-a567b080-f73a-11e8-94ee-c0a4053d3a90.png)
In the picture is 3 improvements (Noow). They have +1 base production are supposed to get +1 production for each adjacent forest and jungle:
INSERT INTO Improvement_AdjacentFeatureYieldChanges
			(ImprovementType,			FeatureType,		YieldType,			Yield)
VALUES		('IMPROVEMENT_CLFB_NOOW',	'FEATURE_JUNGLE',	'YIELD_PRODUCTION',	1),
			('IMPROVEMENT_CLFB_NOOW',	'FEATURE_FOREST',	'YIELD_PRODUCTION',	1);	

One Noow, with no forest next to it has +1 prod (good)
One Noow on a hill is adjacent to 2 jungles and has +4 prod (+1 base, +2 from hill, +1 from jungle)
On Noow on flat grassland is adjacent to 2 jungle and 1 forest and has +2 prod (+1 base, +1 from forest jungle)

So, it seems that the bonus from adjacent feature might be capped at +1?  I'm not sure

**Comment by LoneGazebo** [comment]
Hills are only +1 production, no?

**Comment by LoneGazebo** [comment]
So +1 base, +1 hill, +2 jungle

**Comment by pineappledan** [comment]
No, hills are +2 prod/0 food

**Comment by LoneGazebo** [comment]
oh, I know why -  it check for ownership for the bonus

**Comment by LoneGazebo** [comment]
i.e. the 'adjacent' tile has to be owned by the player.

**Comment by LoneGazebo** [comment]
I should probably remove that because the game won't know to update the bonus for the improvement. Try buying all the tiles first, then plant the improvement.

**Comment by pineappledan** [comment]
That would still be +2 adjacent jungle though. both those jungle tiles are owned in that picture. 

I built those improvements, then purchased the second forest tile on the hill to check that, bu it's possible the value is tied specifically to when the improvement was built, and doesn't check if tiles are claimed later?

**Comment by LoneGazebo** [comment]
Yes, see above.

**Comment by LoneGazebo** [comment]
I can remove the ownership check

**Comment by pineappledan** [comment]
Yeah, that makes sense. If it doesn't update then it was just that forest directly on the coast that was giving the bonus.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2642325/CvGameCore_Expansion2.zip)

Here. This is a debug dll so it is big and slow.

**Comment by pineappledan** [comment]
![image](https://user-images.githubusercontent.com/33136027/49418517-c1218580-f73f-11e8-8829-15548a6dfa50.png)
That seems to work just dandy.

2 Noow on flat grasslands: 
* 1 Noow with 1 unowned forest next to it = 2 prod (1 base + 1 adjacency)
* 1 Noow with 1 owned and 1 unowned forest next to it = 3 prod (1 base + 2 adjacency)

**Comment by LoneGazebo** [comment]
Yay
