### ISSUE TITLE
Statecraft Spy quantity and Spies on current version

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#4947]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I got 3 spies on normal map by picking Statecraft's policy. Then I reached Renaissance and got 2 or 3 more, I can't say that on the top of my head. Is this because of all the hotfix "revolt CS (6-8 came to life I think)", a ninja balance change or is my game just bugged at this point?

**Comment by MoiMagnus** [comment]
Number of spies in based on the number of CS that have ever existed at some point of the game. So new CS from revolution can increase it.
