### ISSUE TITLE
Units die when Open Borders Expires

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4948]
_1. Mod version (i.e Date - 4/23):_
11-21-1-3

_2. Mod list (if using Vox Populi only, leave blank):_
none

_3. Error description:_ 
Where are units supposed to go when an Open Borders agreement expires?
![image](https://user-images.githubusercontent.com/34615525/49333528-7ad8f480-f58e-11e8-86a6-ffd00e82ec7f.png)
In this image, I have three units within Morocco's borders. They are recuperating after helping him fight a war with Japan, his neighbour.  I have no shared borders with Morocco, being across the ocean.

Two turns later, my Open Borders agreement with ends.  These four units inside his borders just die.  There's no notification about it, but if you're quick enough, you can see them take massive damage and disappear.  Consumed Supply drops from 37 to 33.
![image](https://user-images.githubusercontent.com/34615525/49333533-95ab6900-f58e-11e8-8de0-6c0e20fead57.png)
[AutoSave_0255 AD-1725.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2636375/AutoSave_0255.AD-1725.zip)

If I make an Open Borders Agreement with Japan before the one with Morocco expires, then most of my vulnerable units get moved to Japan's border, with only one dying:
![image](https://user-images.githubusercontent.com/34615525/49333745-48c99180-f592-11e8-91cb-cb68d9ecc1ad.png)
I briefly thought that they had to be within one move of an agreeable border, but you can see here that the knight would've been able to move into Japan, but instead died. There's even an empty spot he can move to that's visibly empty (and the knight himself had vision on it). It looks more like the units need to be exactly on the border?

**Comment by LoneGazebo** [comment]
@ilteroi jumptovalid strikes again?

**Comment by ilteroi** [comment]
turns out the IGNORE_RIGHT_OF_PASSAGE flag was broken, don't know for how long ...

**Comment by Th0mas8** [comment]
I have reproduced this issue on 12-18. I use only extra UI mods, so it should be reproducable. Load savegame from attachment, and request capitulation from Rome. Knight next to Rome will dissapear (at least I am losing one knight).

[https://ufile.io/s6u6g](https://ufile.io/s6u6g)

**Comment by BiteInTheMark** [comment]
Version 1-29
My pathfinder disappeared completly after a peace declaration with Greece, while my pathfinder was in their borders. Only one field away from neutral territory, no blocked area. It was a multiplayer game, so I cant give any logs or save.
