### ISSUE TITLE
Feature request - New diplomacy penalty

### ISSUE THREAD

**Issue by Megastrikex** [LoneGazebo/Community-Patch-DLL#4950]
Hey.

I have always wondered, why there isn't a diplo penalty with others if you are close winning a game. Something that gives big negative penalty with everybody. Only the players with closest to the win will get this penalty and as soon as somebody else is closer, it switches to them. Similar how human players would hate somebody who is close to win.

It could be called something like this: "They believe you are close winning the game".

**Comment by TechpriestEnginseer** [comment]
That already exist.
