### ISSUE TITLE
Mongolia keeps forcing Florence to surrender

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4951]
_1. Mod version (i.e Date - 4/23):_
11-21-1-3

_2. Mod list (if using Vox Populi only, leave blank):_
none

_3. Error description:_ 
This has happened a couple times during this game (specifically with Florence), and I can't figure out what's causing it.  Before I met Genghis Khan, he'd either captured or forced Florence to surrender, so it's firmly in his grasp.
![image](https://user-images.githubusercontent.com/34615525/49346479-205c9880-f661-11e8-83a0-63ef5c2dde47.png)

Then, at the beginning of his turn, something happens _very briefly_ with Florence: its borders become city-state borders and it loses all of its defensive buildings (maybe other buildings as well):
![image](https://user-images.githubusercontent.com/34615525/49346518-e2ac3f80-f661-11e8-96ce-d43d7256b4a3.png)
It then immediately goes under Mongolia's control again, with a notification:
![image](https://user-images.githubusercontent.com/34615525/49346553-6c5c0d00-f662-11e8-96f1-5d95ae29fbfb.png)
I think, this happens when his war status changes with another city state (eg. when he declares war on or makes peace with a civ who has several allied city states). In this case, he is making peace with Colombo and Samarkand because their allied status changed to someone he's not at war with (the Huns) .

Logs:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2637629/Logs.zip)
Save:
[Askia_0275 AD-1810.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2637585/Askia_0275.AD-1810.zip)

**Comment by LessRekkless** [comment]
Whoops; I guess Civ can't be accessing them when 7zip wants to.

The logs are probably only for that turn, unfortunately. I'm on a clean install of Civ 5, so I didn't update the config.ini file until that turn.  If it's a serious issue I can go back a couple turns. and auto end my turn.

**Comment by TechpriestEnginseer** [comment]
I mean you did say you have a blank mod list.. so I can't suspect why it would deny Mongolia's his Force Annex...

**Comment by LessRekkless** [comment]
He's had Florence for dozens of turns, it just occasionally resets; maybe he's even getting yields for the new surrender!

**Comment by TechpriestEnginseer** [comment]
You know I'm thinking, what if he's in negative unhappiness and the city is constantly revolting back to its original form?

**Comment by LessRekkless** [comment]
He is at -20 negative happiness, so I could see a revolt happening. Here's an image of what I can see of his available military nearby.
![image](https://user-images.githubusercontent.com/34615525/49348096-691c4d80-f671-11e8-8671-3a8b734ef587.png)
It's probably enough to frighten a brand new city state with no military and 8 city strength.

**Comment by LoneGazebo** [comment]
He can only get the bonus once per CS, so it’s not triggering over and over again.
