### ISSUE TITLE
(Tooltip) Imperialism and Exploration promotions

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4952]
_1. Mod version (i.e Date - 4/23):_
11-21-1-3

_2. Mod list (if using Vox Populi only, leave blank):_
none

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/34615525/49347798-63be0380-f66f-11e8-8238-6c554171b01c.png)
![image](https://user-images.githubusercontent.com/34615525/49347891-0080a100-f670-11e8-9268-e93cb6632916.png)

I believe both of these promotions are granted on the Imperialism Policy branch opener. I understand why they're split up, each bonus is applied to different portions of the military.  However, Exploration's tooltip states that it gives an additional +1 sight on top of Imperialism.

Also, how is the Great Admiral's movement changed? I see the promotion on the Great General: "Faster General: +1 Movement", but the +1 Movement for the Great Admiral seems baked into the "Naval Leadership" promotion, which should be there before taking Imperialism, since it contains information on the combat bonus aura:
![image](https://user-images.githubusercontent.com/34615525/49348039-f7dc9a80-f670-11e8-8c96-5f0bc0c1af96.png)
![image](https://user-images.githubusercontent.com/34615525/49348035-f1e6b980-f670-11e8-931d-c90364ebcd22.png)
![image](https://user-images.githubusercontent.com/34615525/49348053-088d1080-f671-11e8-9ef7-ab6a9f35227f.png)

**Comment by LoneGazebo** [comment]
Great Admirals aren't affected by the opener.
