### ISSUE TITLE
MinorFriendshipChange doesn't do anything

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4954]
1. Mod version : 11/21

2. Other mods: Canada for VP

3. Error description: The MinorFriendshipChange column in the buildings table doesn't do anything. 

On completion, buildings with this value are supposed to give X influence with every city-state

the CERN wonder currently uses this table, and is supposed to give +100 influence with all city states. The Canada for VP mod uses it for its unique building as well. 

4. Steps to reproduce (optional): build CERN in your city

**Comment by TechpriestEnginseer** [comment]
no I'm pretty sure when you expend a GP with it then you gain the influence.

**Comment by pineappledan** [comment]
Well in that case I can confirm that it works!

**Comment by LoneGazebo** [comment]
Good! Now confirm that the improvement_ table I made works so I can release the beta. :)
