### ISSUE TITLE
Civ IV Diplomacy trade bug, NPC accepts vassalage for free

### ISSUE THREAD

**Issue by toxyy** [LoneGazebo/Community-Patch-DLL#4955]
_1. Mod version (i.e Date - 4/23):_
Civ 4 diplo v11, from steam.  That's it.

_2. Mod list (if using Vox Populi only, leave blank):_
![image](https://user-images.githubusercontent.com/29783193/49418353-c25aae80-f74f-11e8-86e6-b395cc800ee4.png)

_3. Error description:_

Trading with civs is a bit bonked.
Especially on the surrender page, when i ask them if they want to capitulate or give me my city back Theyll counter offer or just deny.
Then i hit propose and it goes through usually.
I traded spain with 400-600 more points than me and got them to be my vassal, just my asking it and a defense pack, lol.

_4. Steps to reproduce (optional):_

YnEAMP Large Europe, with the correct city state placement mod it comes with.  Those are listed in the pic above anyways.

Fight with an AI long enough and sometimes when surrendering they offer their vassalage, though you can request it of them.  Every time I ask what they think, even to give me cities, they deny.  But the last two wars I was in, after negotiating, I added one city to the end and hit propose and it was auto accepted.

I experimented with vassalage... every single enemy in the game agreed to be my vassal.  Interestingly enough, there were no other vassals in the entire game except the ones I made (except for city states counting as them).  I don't know why they didn't use it... to make the bug, all I had to do was trade a defensive pact, but on their side but vassal, and hit propose, and it was always accepted.  Very weird.  I had done this with a couple tiny civs and they agreed so I thought I was intimidating... turns out everyone agreed and I'm not a big shot.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2642366/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
I do not have the turn before the error it just kinda happens during those moments.
[saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2642402/saves.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
Actually it did end up crashing after making a deal with venice way later on, but it was likely a ram issue, only 8gb on this laptop right now.

4. Screenshots (optional):

None

**Comment by LoneGazebo** [comment]
Artificial Unintelligence is not compatible with the Community Patch. If you aren't using the Community Patch...use that instead, AUI is no longer updated and is buggy.

**Comment by toxyy** [comment]
Can I use the community patch with everything disabled except civ 4 diplo?

**Comment by LoneGazebo** [comment]
Yes, but use the VP installer to do so. 

https://forums.civfanatics.com/threads/community-patch-how-to-install.528034/
