### ISSUE TITLE
Block Artifical Unintelligence and stuff

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4956]
clearly if they're incompatible, they should be blocked in the (1) mod?

**Comment by LoneGazebo** [comment]
I'd need to collect all of their mod IDs.

**Comment by TechpriestEnginseer** [comment]
```
a4a8d2bb-cffd-4d8e-8893-d773f25b6fe1
```
is for Artificial Unintelligence, but that's basically it. I searched in the past, and that seems to be the only DLL mod that is active left.
