### ISSUE TITLE
Wonders Policy Requirements busted as of 12/3 beta

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#4957]
12/3b, no other mods

I'm able to produce wonders for which I don't meet the policy requirement yet.

![betaciv](https://user-images.githubusercontent.com/24731508/49436390-50b74a80-f7b9-11e8-8283-6f178a9192e8.png)

**Comment by bigcat88** [comment]
Have the same issue.

**Comment by LoneGazebo** [comment]
I'll look.

**Comment by supermerill** [comment]
@bigcat88  Does the hotfix corected the bug? If yes, you can close the issue.

**Comment by LoneGazebo** [comment]
Yeah
