### ISSUE TITLE
Withdraw Before Melee as a bonus to combat

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4959]
_1. Mod version (i.e Date - 4/23):_
11-21-1-3

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/34615525/49484992-183e5d80-f807-11e8-8e21-0e83a8b12b34.png)
This is a picture of an upgraded Nau (with the Withdraw Before Melee promotion):
![image](https://user-images.githubusercontent.com/34615525/49485021-33a96880-f807-11e8-99b3-f4d76ae2e6bd.png)

Is it really getting +80% combat strength from that promotion when it attacks, or is this a combat calculation display bug?

**Comment by LoneGazebo** [comment]
It's just in the list - it isn't a combat bonus. Blame Firaxis for bad UI.
