### ISSUE TITLE
[8-5] No barbarians spawn

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#496]
I have no barbarian what so ever with this version.

I'm using a scenario map. I checked and I have no players assigned to Team 22 (which would normally cause this as barbarians are hard coded as Team 22).

\Skodkim

**Comment by skodkim** [comment]
Should probably note that I'm using CP from 5-8.

**Comment by LoneGazebo** [comment]
Did you clear your cache?
G

**Comment by skodkim** [comment]
Yes. Tried several times and cleared cache before each try.

On 6. aug. 2015 16.55.17 CEST, LoneGazebo <notifications@github.com> wrote:
>Did you clear your cache?
>G
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LoneGazebo/Community-Patch-DLL/issues/496#issuecomment-128403043

-- 
Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by skodkim** [comment]
Just tried one other thing. When I use the same scenario map but do not load scenario barbarians spawn. When I load the scenario they do not.

\Skodkim

**Comment by LoneGazebo** [comment]
Odd. I'll reference Ilteroi to this.

**Comment by skodkim** [comment]
Here  you go. It contains customized civs etc but these have been used since before CPP was started without problems.

![a_jhw_map_v10_06 civ5map](https://cloud.githubusercontent.com/assets/6018459/9149103/23a79b5e-3d99-11e5-9fb1-5b4e6f602ef1.jpg)

\Skodkim

**Comment by skodkim** [comment]
Actually I just created a new scenario just to be sure. Only standard mods+IGE (to reveal map) active this time. The problem persists: When clicking the load scenario button I get no barbs. Using the same map but without loading the scenario it works.

![aaa civ5map](https://cloud.githubusercontent.com/assets/6018459/9149177/0e09a8ec-3d9d-11e5-848f-6f8421927001.jpg)

\Skodkim

![civ5screen0000](https://cloud.githubusercontent.com/assets/6018459/9149175/04796402-3d9d-11e5-9493-e60f128e0f78.jpg)

**Comment by skodkim** [comment]
Any chance of an ETA on this (not trying to rush you, would just like to know if I'm going to be able to start a new game any time soon)?

\Skodkim

**Comment by LoneGazebo** [comment]
I told ilteroi about it, as this is his domain of the DLL.

**Comment by LoneGazebo** [comment]
I've fixed this (ilteroi is MIA). Will be in next version.
G

**Comment by skodkim** [comment]
Great! Looking very much forward to it.

Thanks!

\Skodkim

On 15. aug. 2015 22.17.14 CEST, LoneGazebo <notifications@github.com> wrote:
>I've fixed this (ilteroi is MIA). Will be in next version.
>G
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/LoneGazebo/Community-Patch-DLL/issues/496#issuecomment-131442364

-- 
Sendt fra min Android telefon med K-9 Mail. Undskyld hvis jeg er lidt kortfattet.

**Comment by skodkim** [comment]
Tested with 8-15 and it works :smile: 

\Skodkim
