### ISSUE TITLE
Building_YieldFromUnitProduction don't work gud

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4960]
_1. Mod version (i.e Date - 4/23):_Building_YieldFromUnitProduction doesn't appear to be working. 

I built a mod that uses it to give culture on construction on units, but nothing happens. I'm not sure if it's working for the Ottoman Siege workshop

**Comment by pineappledan** [comment]
Update: I just checked the Siege Foundry on the Ottomans and it works fine there. The table just doesn't work with culture I guess.

**Comment by Infixo** [comment]
Probably courtesy of Jon...

**Comment by LoneGazebo** [comment]
It should work with culture just fine.

```
if (pLoopCity->GetYieldFromUnitProduction(eYield) > 0)
					{
						int iBonus = iPassYield;
						iBonus *= pLoopCity->GetYieldFromUnitProduction(eYield);
						iBonus /= 100;

						iValue += iBonus;
					}
```

To be clear, the value you input is the % of production the unit being created costs. So if you put in too low of a number, the % may be zero.

**Comment by LoneGazebo** [comment]
It also does not work for civilian units, FWIW.

**Comment by pineappledan** [comment]
To clarify, I set the values as culture, and at ‘20’, which is the same proportion as Ottomans use. 

I tested on construction of catapults and horsemen specifically.

**Comment by LoneGazebo** [comment]
Weird. I'll test with culture, see what's up.

**Comment by LoneGazebo** [comment]
![image](https://user-images.githubusercontent.com/7849458/49552439-9eb77580-f8c1-11e8-8a49-21afe7f88f69.png)

Works fine for me.

**Comment by LoneGazebo** [comment]
INSERT INTO Building_YieldFromUnitProduction
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_SIEGE_WORKSHOP', 'YIELD_CULTURE', 20);

**Comment by pineappledan** [comment]
So I scrapped my game where it wasn't working and booted up a new game without changing anything.

aaaaand it worked perfectly.
Wut?
