### ISSUE TITLE
Unhappiness Spiral

### ISSUE THREAD

**Issue by vide0gamer** [LoneGazebo/Community-Patch-DLL#4965]
_1. Mod version (i.e Date - 4/23):_
12-3-1b

_2. Mod list (if using Vox Populi only, leave blank):_
Really Advanced Setup

_3. Error description:_ 
Over the past 20 or so turns, I have gone from about 20 happiness to 21 unhappiness.  Last turn was from 6 to 21.
[Washington Unhappiness Spiral.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2655479/Washington.Unhappiness.Spiral.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2655480/Logs.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
another observation, which may or may not be related:

the mother of all happiness drops ...
![image](https://user-images.githubusercontent.com/1358966/49687416-9dc15680-fb02-11e8-971e-0e24c6f28972.png)

coinciding with economic collapse
![image](https://user-images.githubusercontent.com/1358966/49687483-90589c00-fb03-11e8-9fcd-5734959e2fa3.png)

don't know how that happened. they seem to have all available buildings, but don't run any specialists?
![image](https://user-images.githubusercontent.com/1358966/49687511-3a382880-fb04-11e8-8c23-7f7743560a90.png)

anyway, logs are here
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2659806/logs.zip)

**Comment by LoneGazebo** [comment]
I am going to tell the AI to work specialists even when happy, however.
