### ISSUE TITLE
Question about yields from events displayed in CityView

### ISSUE THREAD

**Issue by Infixo** [LoneGazebo/Community-Patch-DLL#4966]
_1. Mod version (i.e Date - 4/23): 12-3-2b
_2. Mod list (if using Vox Populi only, leave blank): Improved City View
I've been reviewing changes to CityView and found a little difference.
In ICV I have a line that adds event-related yields to buildings (904)

`city:GetEventBuildingClassYield(buildingClassID, yieldID)`

This line is missing in VP's CityView. Since EventChoice_BuildingClassYieldChange is not empty, it means that those yields are used but somebody removed this line from .lua. Question: is it a bug or not?

**Comment by LoneGazebo** [comment]
I think @TechpriestEnginseer did this - care to chime in?

**Comment by TechpriestEnginseer** [comment]
cuz it was getting duplicated twice. Line 923 has the same line.
