### ISSUE TITLE
Tooltip errors : diplomacy action + supply buildings

### ISSUE THREAD

**Issue by Udutont** [LoneGazebo/Community-Patch-DLL#4967]
1. Mod version: 12/3b

_2. Mod list None

_3. Error description:_ two errors:  1) tooltip on build screen states that diplomat action provides 100 influence. The correct amount can be seen next to information on promotion (see screensho 1); 2) tooltips on several building include text such as  "TXT-KEY_EUI_...", see the screenshot 2 - I have noticed the problem only in regard to buildings modfying unit supply.

_4. Steps to reproduce (optional):_

[Tooltip-errors.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2658085/Tooltip-errors.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Infixo** [comment]
Ad. Walls tooltip - bad install.
![obraz](https://user-images.githubusercontent.com/25866684/49686226-c68d2000-faf1-11e8-9b3d-62ba136875be.png)

**Comment by Infixo** [comment]
Ad. Influence (45 vs. 100)
That comes from the fact that Diplomacy units are not native to vanilla game. In vanilla only GM was able to influence CSs via Trade Mission. The tooltip detects if a unit has such capability and displays the value of Trade Mission influence which is stored in game defines MINOR_FRIENDSHIP_FROM_TRADE_MISSION. It is 100 for now, but can be modified by a parameter in CSD.
Envoys, and other diplo units come from CSD and use a different mechanics. The actual influence is stored in promotions (Adept, etc.) and is stored as a negative value which is subtracted from the default.
![obraz](https://user-images.githubusercontent.com/25866684/49686297-c5a8be00-faf2-11e8-8a78-97dce9d240ce.png)
It this case 100-55=45. And 45 is simply put into the description of the unit. But in fact, this value is not stored in the unit data, and you can't simply display it.

**Comment by Udutont** [comment]
Thx for thorough explanation! As regards the first problem: how do I reinstall to get rid of the error? Sry, for asking such a basic question but I tried to clear cache (deleted the cache folder, deleted mods folder, checked for integrity, ).  No avail, I did it again but also deleted local files and reinstalled from backup. Still no change. I must be doing smth wrong or not doing enough...

**Comment by Infixo** [comment]
Check DLC folder in the main game. Remove any old EUI from there, too. People often forget about that.

**Comment by Udutont** [comment]
I successfully reinstalled the game, no tooltip error, thank you for the help!
