### ISSUE TITLE
CityView Yields from UnitPromotions_GarrisonYield

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#4969]
They'll be added to the Yield Total, but there's no indication on how they're added. (I'm referring to the Yield part where you hover over the yields and it says From Buildings, From Policies, there should be a From Promotions).

**Comment by Infixo** [comment]
This tooltip is generated by DLL. I did some cleanup to make sure that all info is from there thus to avoid desyncs with (E)UI in #3828.

**Comment by TechpriestEnginseer** [comment]
Yes, but how do we grab the Yield so that it can be displayed whenever you got +10 Gold from Promotions or +5 Gold from Promotions.

**Comment by LoneGazebo** [comment]
It goes onto the tile under the city. Don't ask me why, I didn't write the code. But there it is.

**Comment by TechpriestEnginseer** [comment]
Fair enough
