### ISSUE TITLE
Combat Health Bars for units with naval Dreadnought promotions

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4970]
_1. Mod version (i.e Date - 4/23):_
11-21-1-3

_3. Error description:_ 
I don't know if it can be fixed because ...Firaxis Combat UI..., but I thought I'd log it anyway.

The display bar on combat assumes that max HP will only ever be 100, and it looks like the health bar displays:
 `(solid)100-[(empty) current damage taken]-[(flashing) estimated damage dealt]`
![image](https://user-images.githubusercontent.com/34615525/49681458-f562b200-fa6f-11e8-9ec0-f64471d73dd6.png)
So the player can't visually determine what the final HP of a Dreadnought ship will be.

**Comment by LoneGazebo** [comment]
EUI?

**Comment by LessRekkless** [comment]
I have EUI; does it modify the combat UI?

**Comment by TechpriestEnginseer** [comment]
Actually I have an idea.. hold up.

**Comment by ilteroi** [comment]
i thought this was solved? #4891

**Comment by TechpriestEnginseer** [comment]
Different UnitBar.

**Comment by LoneGazebo** [comment]
I think I may have fixed, seems I missed a single MAX_HIT_POINTS in EUI...
