### ISSUE TITLE
Cultural victory counts wiped civilization

### ISSUE THREAD

**Issue by MiroshaLazy** [LoneGazebo/Community-Patch-DLL#4975]
_1. Mod version: 11/21 beta

_2. Mod list: Vox Populi only

_3. Error description:_ 
Culture victory not triggering because it counts civilization (Byzantine), that already is totally concured by another one (Siam). And my influence over Byzantine is constant 87,1% and only can be seen at victory conditions screen.

_4. Steps to reproduce (optional):_
Load the save

---------------------------
Supporting information:

1. Log files
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2660374/Logs.zip)

2. Save game:
[AutoSave_0550 AD-1950-January.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2660373/AutoSave_0550.AD-1950-January.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
I've already installed 12/03 version, so couldn't open that save(

**Comment by MoiMagnus** [comment]
So, if I understand correctly:

1) You influenced everyone else

2) You have an ideology

3) Your citizens are content with it

4) You have 2 level 3 tenets

5) But you are not able to build the Citizen Earth Project

**Comment by MiroshaLazy** [comment]
1,2,3 Yes
4 No.
I had no idea about that, sorry. And about the Citizen Earth Project.
Also I was confused seen Byzantine in cultural victory progress.
