### ISSUE TITLE
GG doesn't create Citadel on artifact

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#4976]
_1. Mod version (i.e Date - 4/23):_
12-3-1b

Subj. Land was acclaimed successfully, artifact digged. but no citadel were created. GE/GM works fine, manufacture and town was created in the same situation.

![20181208234217_1](https://user-images.githubusercontent.com/13381981/49697193-0c62ea80-fbbd-11e8-8a3b-02ef799c431f.jpg)

**Comment by TechpriestEnginseer** [comment]
wait you were able to dig an artifact using a great person?

**Comment by bigcat88** [comment]
Ofc. This feature was introduced a few month ago.
