### ISSUE TITLE
Peace treaty - units in territory get destroyed

### ISSUE THREAD

**Issue by BorussiaVox** [LoneGazebo/Community-Patch-DLL#4977]
_1. Mod version (i.e Date - 4/23):_
11-21-3

_2. Mod list (if using Vox Populi only, leave blank):_
reallyadvancedsetup
infoaddict

_3. Error description:_ 
when my units are in enemy territory and I make peace with them, my units get destroyed.
The same happens when open border agreement runs out.

The bug with open borders agreement is listed as fixed in next version in
https://github.com/LoneGazebo/Community-Patch-DLL/issues/4948

I open this issue just to make sure that this bugfix also works on peace treaties.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
well the fix was included in the 12/3 version iirc ... so just update

**Comment by briantjack** [comment]
Where do I go to download the 12/3 version?
