### ISSUE TITLE
Unwilling to trade world map

### ISSUE THREAD

**Issue by BorussiaVox** [LoneGazebo/Community-Patch-DLL#4978]
_1. Mod version (i.e Date - 4/23):_
11-21-3

_2. Mod list (if using Vox Populi only, leave blank):_
infoaddict
reallyadvancedsetup

_3. Error description:_ 
In my game no civ under any condition was ever willing to trade maps with me. Not even after I explored the whole map myself with 5 plots left. 
Even civs on the other side of the map I have DoF, research agreements and so on with.
And not even my enemy who has a warscore of -50 and about to lose - he would rather die than trade maps -> trade maps is always shown as impossible.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by briantjack** [comment]
It's annoying that I can't trade away my world map either.

**Comment by ryanmusante** [comment]
I'll Give You My World Map

When You Pry It From My Cold, Dead Hands!
![when-you-pry-it-from-my-cold-dead-hands-ote-5575795](https://user-images.githubusercontent.com/26808646/50372496-86aa5a80-0612-11e9-9c7b-909701d0a208.png)

**Comment by LoneGazebo** [comment]
Updated to latest? The AI trades quite a bit for this now.

**Comment by briantjack** [comment]
Good to know

**Comment by ilteroi** [comment]
you can only buy a map if you have the military science tech. note that this is asymmetric, ie it's perfectly possible to sell a map if you don't have that tech. the tooltip in the diplo screen maybe isn't too clear on that.

in fact, i think it would make sense to make the requirement at least symmetric, ie both must have the tech?

**Comment by ilteroi** [comment]
and the valuation seems to be a bit off too 

![image](https://user-images.githubusercontent.com/1358966/50382399-8192ed00-069e-11e9-80f0-ad1852a13262.png)

this is standard size map with aztecs on a different continent. so the map is quite valuable ... but the only way to pay for this would be with my own map ... and even then they want 6k+ gold.

**Comment by LoneGazebo** [comment]
Must be a good-ass map.

**Comment by ilteroi** [comment]
see #5016 for the minimap

**Comment by LoneGazebo** [comment]
We should probably just cap the value

**Comment by briantjack** [comment]
> you can only buy a map if you have the military science tech. note that this is asymmetric, ie it's perfectly possible to sell a map if you don't have that tech. the tooltip in the diplo screen maybe isn't too clear on that.
> 
> in fact, i think it would make sense to make the requirement at least symmetric, ie both must have the tech?

How about just making map trading the same as open borders? That way, if either side has the necessary tech, either side can buy the other's.
