### ISSUE TITLE
Requires extra strategic resource to upgrade

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#4979]
_1. Mod version (i.e Date - 4/23):_
11-21-1-3

_3. Error description:_ 
Is there any way we can remove the requirement of an unused strategic resource to upgrade a unit that's already using that resource? (or is that already the case and my game is messed up?)
![image](https://user-images.githubusercontent.com/34615525/49704962-8314dd80-fbe7-11e8-84c1-e3eefa8bf5ce.png)

(In this example, I have civilizing mission so I can upgrade in Sydney's waters.)

**Comment by bigcat88** [comment]
Frigate doesn't use iron. Or I misunderstood a question.

**Comment by LessRekkless** [comment]
Frigates use iron.

**Comment by LessRekkless** [comment]
Oh.... that explains so much. Did Frigates **ever** cost iron?

This can be closed.
