### ISSUE TITLE
Local unhappines caused by burning lands persists after lands are repaired

### ISSUE THREAD

**Issue by s-fleuren** [LoneGazebo/Community-Patch-DLL#4980]
_1. Mod version (i.e Date - 4/23):_
Community patch v.88
Community balance overhaul v.13

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Barbarians pillaged some improvements near Carthage earlier. I've repaired the improvements some time ago but the unhappiness penalty still persists. I've tried to reload the game but that didn't solve the issue.

_4. Steps to reproduce (optional):_
Have lands pillaged, repair lands.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![afbeelding](https://user-images.githubusercontent.com/24414432/49751221-2d0a6d80-fcad-11e8-8548-5bffbc7dbb11.png)

**Comment by TechpriestEnginseer** [comment]
They take a while to register.
