### ISSUE TITLE
Wrong Goody Hut Upgrades?

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#4982]
VP: 11-21-1
I just noticed this in db:
![bez tytulu](https://user-images.githubusercontent.com/33016300/49760903-e37a4c80-fcc5-11e8-85d1-0fde5cfad8a9.png)
These are spearman class units. First is base one, next are: hoplite, immortal. barbarian, pictish warrior.
If unique units obsolete at 2 tech range, then why goody hut upgrades force them to upgrade in 1 tech range? This upgrade also is shown in unit panel. If let's say hoplite is still better than pikeman then there's no point in upgrading to pikeman, and game forces us to do so.

@Infixo We talked about it during latest VPEE stuff. I was right about ObsoleteTechs, but GoodyHutUpgrades were correct in your mod.

What do you think about it?

**Comment by LoneGazebo** [comment]
Because if you let them upgrade to the tier _after_ that, it'd be absurdly powerful.

Intended.

**Comment by adaneslavo** [comment]
So maybe leaving GoodyHuts as they are, but make upgrading units possible only when the obsolote tech arrives (ommitting one upgrade)? It won't be powerful because you have access to that tech.

**Comment by LoneGazebo** [comment]
I think it's such a small and rare issue that it isn't worth fiddling with the backend mechanics for it.

**Comment by adaneslavo** [comment]
And what about AI? How it performs with that? Does it know it should pass one upgrade fro some time or just try to upgrade whenever possible?

**Comment by TechpriestEnginseer** [comment]
It's rare because you have to put the unique unit inside the ancient ruins that grant him a goody rune.
