### ISSUE TITLE
Unique resource description

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#4983]
I noticed that Brazilian UR has additional info in help description and Indonesian ones do not have such. I noticed that when custom civ added its own resources and there were inconsistency. I think this info in help is irrelevant and can be dropped.
![obraz](https://user-images.githubusercontent.com/33016300/49763881-26d8b900-fcce-11e8-84ba-b1250bea0d6f.png)
![obraz](https://user-images.githubusercontent.com/33016300/49763893-32c47b00-fcce-11e8-8608-74c7edfdb889.png)
And example from custom mod:
![obraz](https://user-images.githubusercontent.com/33016300/49763911-3e17a680-fcce-11e8-8536-3060e9f9b504.png)

**Comment by Hokath** [comment]
Fair. Am happy to change the mod if that is the policy.

**Comment by LoneGazebo** [comment]
I think it's fine.
