### ISSUE TITLE
Forgotten Units still a problem?

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#4985]
_1. **Mod version** (i.e Date - 4/23):_
11-30-18, 2-30-18

_2. **Mod list** (if using Vox Populi only, leave blank):_
I've observed this twice with different versions now, with different mods.

When I played earlier this year (version 2-30-18):
VP (EUI)
Flag Promotions (v7)
Improved City View (v9)
Unit Path Viewer (v10)

The game I'm playing now is more heavily modified (11-30-18):
VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

_3. **Error description**:_ 
I know it's a long modlist but I have observed this error with different versions and mostly VP in common.

The issue is the AI leaving wounded units in an area without need instead of sending them home to heal. This usually happens after a war and I have only observed this with naval units and embarked units. The AI units will usually be really close to their own borders and are not threatened by anyone (and there is no war going on with anyone else either) so they should send those units home to heal but instead they leave them there.
I have found issue #3090 which seems to describe a similar problem.

_4. **Steps to reproduce** (optional):_
I have used the modified file referenced in issue #3090 by Ilteroi and modified my games with it and reloaded some saves that I still had (I also still have the old MODS folder from back then). I posted the results in this gallery: https://imgur.com/a/NeiT4Wm
Since I found the tool for debugging via tool tip after I took most of the screenshots I couldn't provide them for all cases but I think the gallery makes the issue clear enough.

Let me know if I should provide my MODS folders and savegames...the MODS folder is quite large but I'll try to get it uploaded somewhere.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
good bug report! i'll check.

**Comment by ilteroi** [comment]
ok. i don't have a good testcase but i found a spot that could cause this. should be better now.
