### ISSUE TITLE
should the roman pilum ability affect enemy units in cities/citadels etc?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#4986]
see the title

**Comment by LoneGazebo** [comment]
Why not?

**Comment by ilteroi** [comment]
cause it seems strange?

**Comment by LoneGazebo** [comment]
I dunno. Spears being thrown over the walls? Feels like a balance concern, toss it into the Roma thread?

**Comment by ilteroi** [comment]
not keen on discussions. also, creating yet another exception from the rules is tedious. i won't touch it.
