### ISSUE TITLE
East India Company not granting new monopoly

### ISSUE THREAD

**Issue by Vuffster** [LoneGazebo/Community-Patch-DLL#4987]
_1. Mod version (i.e Date - 4/23):_
11-21-1

_2. Mod list (if using Vox Populi only, leave blank):_
VP Promo Icons v1.9

_3. Error description:_ 
The East India Company appears to be granting the additional resources it should, but I'm not getting the monopoly bonuses. I had 2 of the 7 gold in the world, so I built EIC in the city with those two gold. While the monopolies summary screen is showing me at 4 of 7 (57%), I'm not getting the GAP on gold tiles, nor the lengthened golden age. The attached save is a few turns after I built the EIC, and a golden age begins this turn.

[EIC Monopoly Issue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2669711/EIC.Monopoly.Issue.zip)

Hope this is enough info; I'm new to GitHub and bug reporting.

**Comment by LoneGazebo** [comment]
Most likely, someone else has more of that resource than you do.

**Comment by Vuffster** [comment]
Ah. Yes, England does. For some reason I thought multiple civs could have the same monopoly bonus... which doesn't make any sense. Thanks!

**Comment by LoneGazebo** [comment]
No worries!
