### ISSUE TITLE
wonders/corporations unit production modifiers (feature request?)

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#4992]
There are 3 wonders which give unit production modifiers locally: Great Altar, Temple of Artemis, Hexxon Refinery Corporation. Until now, I had been under the impression that these production modifiers were global, but they only apply to the city in which they are built. 

This makes the buildings significantly weaker than I thought they were, and the help text only says "+XX% production of XX units", but does not clarify if that means in this city or globally. 

I think it would make sense for a Building_UnitCombatProductionModifiersGlobal table to be added, especially for Hexxon and Great Altar. At a minimum, the help text for these wonders should be changed to explicitly say that the unit production is only local, since it is usually assumed that wonders provide global effects unless otherwise stated.

Note: there are also non-wonder buildings which give local unit production modifiers (seaport, stable, military academy, military base). It is easilly understood that these are local yield modifiers in these cases, because they are non-wonder buildings.

**Comment by LessRekkless** [comment]
Hexxon Refineries' bonus is at the office level, isn't it? As in, each city with an office gets the bonus.

**Comment by LessRekkless** [comment]
![image](https://user-images.githubusercontent.com/34615525/50051397-4a8d6c00-00df-11e9-856f-2494e4f31a68.png)
+20% in this city or all cities?

**Comment by TechpriestEnginseer** [comment]
I believe this was fixed so...
