### ISSUE TITLE
Follower Belief "Cooperation" doesn't scale with the game speed

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#500]

**Comment by LoneGazebo** [comment]
You sure? It does so in the code:

int iYield = pReligion->m_Beliefs.GetYieldPerBirth(YIELD_FAITH) * iEra;
iYield *= GC.getGame().getGameSpeedInfo().getTrainPercent();
iYield /= 100;
GET_PLAYER(getOwner()).ChangeFaith(iYield);

**Comment by LoneGazebo** [comment]
I mean, the code can be wrong (we've proved that 100x over), so if you see a problem, let me know.
