### ISSUE TITLE
(EUI) Diplomatic units state they provide 100 influence rather than their actual amounts

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#5004]
_1. Mod version (i.e Date - 4/23):_
11-21-1-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Infixo said he wanted to take a look at this EUI tooltip error (essentially the same information as #4685, but with the proper issue).
![image](https://user-images.githubusercontent.com/34615525/50059439-d392ba80-0154-11e9-9050-83b1b0972e09.png)
I think the issue is that the diplomatic units' influence is provided by promotions, which overrides the default Diplomatic Mission, while EUI references the base ability.

**Comment by LessRekkless** [comment]
Agreed; it just seems to be a source of confusion for new players, so I thought I'd list it for Infixo.

**Comment by LoneGazebo** [comment]
It's been on my todolist for a bit, I'll see if I can't whip something up.
