### ISSUE TITLE
(Tooltip?) Strategic Monopoly bonuses don't seem to apply properly

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#5005]
_1. Mod version (i.e Date - 4/23):_
11-21-1-3

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/34615525/50060655-9b937380-0164-11e9-8d8e-0ab1c4ae80c9.png)
![image](https://user-images.githubusercontent.com/34615525/50060583-a4377a00-0163-11e9-9265-0e283b5478bc.png)
![image](https://user-images.githubusercontent.com/34615525/50060584-aa2d5b00-0163-11e9-9829-dd5d29c415ec.png)
Are Horses supposed to apply their strategic monopoly on naval units?  If not, then this is just a tooltip error. What about Iron and Uranium? The only one that calls a unit type out specifically is Coal (Naval). Are the others supposed to be Land units only?

Oil doesn't seem to be providing its full bonus XP:
![image](https://user-images.githubusercontent.com/34615525/50060653-9504fc00-0164-11e9-880c-c25364939efc.png)
![image](https://user-images.githubusercontent.com/34615525/50060707-49068700-0165-11e9-9e35-80000bc6cc73.png)
![image](https://user-images.githubusercontent.com/34615525/50060668-c1b91380-0164-11e9-990c-bf423a6d6f0c.png)
![image](https://user-images.githubusercontent.com/34615525/50060686-12307100-0165-11e9-86a0-e9f85f5a0a33.png)
After this combat, I should get 5 XP from the melee attack, plus another 5 from Oil. I do not have Elite Forces, so it looks like I'm only getting 2 XP from Oil. You can see that this also applies to navy: these ranged navy attacks are getting 4 XP per shot instead of 2.
![image](https://user-images.githubusercontent.com/34615525/50060741-b1edff00-0165-11e9-9210-8ade4ebc374b.png)
![image](https://user-images.githubusercontent.com/34615525/50060746-c500cf00-0165-11e9-8315-2867fb145904.png)

Aluminum seems to work fine for both land and navy. I don't have a Uranium monopoly to test which units it applies to.

**Comment by LoneGazebo** [comment]
First part is just a missing LUA element in the UI. Second part is a bad tooltip (should be 2XP).

G
