### ISSUE TITLE
Naval Combat Strength changes with available attacks, and isn't correct anyway

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#5006]
_1. Mod version (i.e Date - 4/23):_
11-21-1-3

_3. Error description:_ 
Combat UI again.

Depending on whether or not a unit has attacks left, its (displayed) combat strength changes:
![image](https://user-images.githubusercontent.com/34615525/50060920-97695500-0168-11e9-9351-f9dbab25afd7.png)
![image](https://user-images.githubusercontent.com/34615525/50060923-9e906300-0168-11e9-805a-c4a2baa16f6f.png)
Both are supposedly showing ranged combat strength, but the second image shows a strength exactly half of the first.  The second isn't displaying regular combat strength, either.  That would be at 34.

Regardless, a Cruiser with those combat modifiers should be at **60** combat strength, not **65**, unless I'm calculating it incorrectly:
`50 * ( 1 + 0.1 + 0.15 - 0.3 + 0.25) = 60`

**Comment by LoneGazebo** [comment]
I think @ilteroi fixed this, there was some leftover code weakening second shots for units.

**Comment by ilteroi** [comment]
the piece of code i removed halved the strength of the _third_ attack. that was very strange ... i'll check this.

**Comment by ilteroi** [comment]
ok, can't reproduce it. seems to be alright after all.

**Comment by LessRekkless** [comment]
Note the combat strength is reduced *after the second attack*, which means it's fairly benign.  The main problem is that the combat strength isn't being calculated correctly.
