### ISSUE TITLE
Nobility Food for Castles and Armories wrong

### ISSUE THREAD

**Issue by BiteInTheMark** [LoneGazebo/Community-Patch-DLL#5009]
_1. Mod version (i.e Date - 4/23):_
12-18/19

_2. Mod list (if using Vox Populi only, leave blank):_
_

_3. Error description:_ 
Policy description of Nobility from fealty say +3 food +1 faith for armories and castles, but it give only +2 food
Additionally, information about the monastery are still wrong. In policy screen and civilopedia it says monastery give +1 faith, but in construction menue it says +2 faith.

**Comment by TechpriestEnginseer** [comment]
Already hotfixed or something like that.
https://forums.civfanatics.com/threads/new-version-december-18th-12-18.639855/page-5#post-15311244
