### ISSUE TITLE
Free Buildings from Tradition lost forever with Capital

### ISSUE THREAD

**Issue by Zarrk** [LoneGazebo/Community-Patch-DLL#5010]
_1. Mod version (i.e Date - 4/23):_
12-18

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I always assumed those where either transferred with the Palace or they stayed in the old Capital waiting to be reclaimed, but in fact they just disappear. Someone has reported the problem two years ago (issue #2777) but it was closed with a 'cannot reproduce' tag and the answer was implying the buildings shouldn't have been lost.

Is there any chance to reopen the case ?

[LogsSaveLostCapital.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2700494/LogsSaveLostCapital.zip)
A test save prior to the imminent loss of a Capital with all Tradition buildings and the log concerning the loss and reconquest turn.

**Comment by TechpriestEnginseer** [comment]
We may have tinkered something 2 years ago. I will reproduce and see.

**Comment by ilteroi** [comment]
there are other things which are irretrievably lost as well, eg extra supply from expended generals. 

so i guess the lesson is, don't ever let your capital be conquered?

**Comment by TechpriestEnginseer** [comment]
WAIT there is a possible dirty fix using xml. @lonegazebo you didn't make a fix for this yet right?

**Comment by LoneGazebo** [comment]
No

**Comment by TechpriestEnginseer** [comment]
an easy fix then
