### ISSUE TITLE
EUI Issue: Can't see popups for Happiness, Science, Gold, etc. in City screen

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#5013]
_1. Mod version (i.e Date - 4/23):_
12/3

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch Mod Compatibility

_3. Error description:_ 
Within the City Screen, there are tooltips that popup for Food production, Gold production, Happiness, etc. However, if you shift from one City Screen to the next using the arrow keys, these tooltips don't popup. 

_4. Steps to reproduce (optional):_
First, open City Screen for City A. Hover the cursor over the Food production to see a summary of the sources for food. You can do the same for the other production summaries, like Gold and Science.
Then, hit right arrow key (on keyboard) to advance to the City Screen for City B. Hover the cursor over the Food production and notice that no tooltip pops up.
On exiting the City Screen for City B, I can reenter the City Screen and see the tooltips for any of the productions. However, the popups won't show after I advance to the next city.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
This is a known flaw in EUI.

**Comment by TechpriestEnginseer** [comment]
which is fixed in the EUI's newest version now if only that guy who would do EUI compatibility would update it for VP now...
