### ISSUE TITLE
integrate instant yield average into per-turn yields?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5014]
we now have the star icon to track instant yields, but the AI still mostly only looks at yields-per-turn for decisions (eg typical checks like CalculateBaseNetGold() > 0).

why not simply make the calls to GetTotalJONSCulturePerTurn, GetTotalFaithPerTurn, GetScience include the averaged per-turn contributions from instant yields?

**Comment by MoiMagnus** [comment]
Raw instand yield are still relevant for happiness, so unless happiness is changed to take instand yield in account, it may still be a usefull information.

**Comment by LoneGazebo** [comment]
If we do that it should be with a Boolean check on the base code so we can easily toggle it on and off on a function to function basis.

**Comment by LoneGazebo** [comment]
Huh? It already is.
