### ISSUE TITLE
-7 aluminium without using any

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#5015]
_1. Mod version (i.e Date - 4/23):_
12/3 (1b) with EUI

_2. Mod list (if using Vox Populi only, leave blank):_
Many mods, also shuffling some techs in the modern era

_3. Error description:_ 
I discovered aluminum and improved 2 tiles with them in my territory. Each has a quantity of 3. I also have the Hexxon corporation which should be providing the quantity of 1. Yet, the top panel is showing '0'. When I allied a city-state with provided the quantity of 8, the top panel started displaying 8. Then I lost the alliance and it went back to '0'.

I am 100% sure that I am not using any aluminum. When I hover over the top panel, it confirms that I am not accidentally exporting any. Yet my own aluminum seems to be ignored. I hope it is just a UI bug because I can trade my aluminum - the trade screen says I can trade 8 (the numbers do not add up though: 6 improved resources + 1 form Hexxon should be 7, not 8)

Sorry, I am using too many mods and also mod-modding VP, so posting a save would be pointless, but the mods I am using should not be influencing the top panel /  resources.

**Comment by psparky** [comment]
I had a very similar bug in my game just yesterday. This is on an old version 2-27.

On the turn I discovered alum I had only one source (8 alum) and it was on a hill that already had a mine. The number in the top panel was zero, but the breakdown showed 8 in the city and no uses or trades. In the trade screens it showed I had 8 available to trade.

A few turns later I got the tech for subs (which I desperately needed) and I was unable to build any as I lacked the resource - I should have still had 8 at this stage as I hadn't used or traded any (trade screen still said 8 available to trade).

I tried various workarounds using IGE. I removed the resource and the top panel then said I had -8 and I tried increasing the number of resources to 16, but it still said 0 total and can't build subs. In the end I deleted that resource and added 16 on a different hill. This gives me the correct number of 8 in the top panel and I can build subs. I just have to remember not to trade the 8 extras that show up in the trade screen.

**Comment by Padre19** [comment]
Same with coal. I discovered coal I had only one source (3)  on a hill that already had a mine. The number in the top panel - zero.

**Comment by psparky** [comment]
Padre19, do you have a useful save that demonstrates the problem as neither Vyyt or myself have one.

In my case, it eventually corrected itself, but it was more than 20 turns later. Just to be clear (in my case at least) it's not just a UI problem - the aluminum was not available to use, although it was available to trade.

**Comment by TechpriestEnginseer** [comment]
Not posting a mod list...

Vague inquiries can only provide vague answers.

**Comment by TechpriestEnginseer** [comment]
I still want to see a mod list.

**Comment by Vyyt02** [comment]
Yeah, I know I am not very helpful because you cannot debug my save. I was rather hoping that other people playing vanilla VP will notice the same problem and post their saves.

My mod list is here:
http://www.spisek.cz/temp/modlist.gif

I also change a lot of things in the tech tree (including the position of aluminum) and unit stats. The map script is Tectonic (huge, 19 civs).

I did not patch VP mid-game.

**Comment by LoneGazebo** [comment]
Tested this today, cannot replicate.
