### ISSUE TITLE
No room for new unit and subsequent disbanding

### ISSUE THREAD

**Issue by ryanmusante** [LoneGazebo/Community-Patch-DLL#5017]
_1. Mod version (i.e Date - 4/23):_
12-18-1

_2. Mod list (if using Vox Populi only, leave blank):_
AI - No CS Annexers,
Diplomacy - Auto-Denounce,
Global - Commander Influence Borders,
Global - Local Generals,
Global - No Ocean Plundering,
Global - Pro-rata Buildings Purchase,
Global - Religious Settlers,
Units - No Mechs,
Units - Subs Immune Under Ice,
Units - Visible Trade Units,
Tectonic Map Script
And many UI Mods

_3. Error description:_ 
Unit is instantly disbanded after completion of build because there is "no room for new unit". Could instead the unit be placed into embarked status next to city? It is a waste of production/gold and time to create a unit and than lose it.

_4. Steps to reproduce (optional):_
Build unit in single tile city with garrison

---------------------------

4. Screenshots (optional):
![noroomfornewunit](https://user-images.githubusercontent.com/26808646/50377730-de25e600-0665-11e9-815e-eadbc3cecac4.png)

**Comment by ilteroi** [comment]
well, why do you build the unit in that city then? if you really want to, you could remove the garrison ...

AI tends to have problems with embarked units, the check is mainly there for their sake.

**Comment by ryanmusante** [comment]
I assumed it would have placed the new unit on the marble tile to the east since it's still on city's proximity.

**Comment by ilteroi** [comment]
well, in vanilla the unit is always placed in the city tile. we relaxed that rule to reduce micromanagment and allowed adjacent native-domain tiles. now you want to relax it further. possible but i would call this an edge case.

**Comment by ryanmusante** [comment]
I think for island cities in war time, it could be a helpful addition. Moving the garrison out makes the city vulnerable to attacks.

**Comment by ilteroi** [comment]
turns out the unit should have been placed in the city plot in this case (like in vanilla). but another check prevented it. should be fixed.
