### ISSUE TITLE
Rhiannon, Celtish pantheon, doesn't provide food & production in cities

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#502]
Tested with IGE. The fisrt screenshot was taken before founding the pantheon, the second - after. Gold and faith income changed appropriately (can be seen on the top panel), however, food and production in my cities seemed to stay the same.
![sruk1](https://cloud.githubusercontent.com/assets/12978597/9142342/be000fa8-3d47-11e5-97ef-095281e57d2f.jpg)
![sruk2](https://cloud.githubusercontent.com/assets/12978597/9142347/c1d4d1f4-3d47-11e5-80d8-dbbfd2756e2d.jpg)

**Comment by LoneGazebo** [comment]
I'll double check. Thanks for reporting. The code may be filtering out local yields because of how it is processed. I'm fairly certain that the code is in the city file, but not sure why it isn't running.

**Comment by LoneGazebo** [comment]
Ah, yeah. The way that function is setup it cannot actually give those yields (food and production). I've changed to science and GAP.

G
