### ISSUE TITLE
Missing settling button

### ISSUE THREAD

**Issue by Minh12345** [LoneGazebo/Community-Patch-DLL#5021]
_1. Mod version (12-18):_

_2. Mod list (if using Vox Populi only, leave blank):_
VP only

_3. Error description:_ 
Missing settling button on settler.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
![settler bug](https://user-images.githubusercontent.com/46088724/50385107-c0a65a00-0701-11e9-9886-23fc744892a9.jpg)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Isabella_0122 BC-0950.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2706075/Isabella_0122.BC-0950.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![settler bug](https://user-images.githubusercontent.com/46088724/50385129-0b27d680-0702-11e9-84f7-ca7135007c38.jpg)

**Comment by ryanmusante** [comment]
Maybe a button grayed out with a tool tip that says the person is below -10 might be helpful in that situation.
