### ISSUE TITLE
Crime - Happiness Bug

### ISSUE THREAD

**Issue by jwoo02** [LoneGazebo/Community-Patch-DLL#5022]
_1. Mod version (i.e Date - 4/23):_
(12-18-1)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
City crime/defense requirement causing large amounts of unhappiness for little deficit:
    (example) 5.6 total crime deficit in 10 pop city causing 10 points of unhappiness
    occurs in capital and other cities

_4. Steps to reproduce (optional):_
Brazil - small map - 5 (king) difficulty - standard time - 7 ai civs, 14 city states

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

[Pedro II_0102 BC-0325.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2708078/Pedro.II_0102.BC-0325.zip)

**Comment by TechpriestEnginseer** [comment]
It's not a bug because the new happiness is an experimental feature right now.

![image](https://user-images.githubusercontent.com/13937047/50455524-5bba5200-0903-11e9-80d5-4bfea9aef28f.png)
