### ISSUE TITLE
Request removal of diplomacy messages

### ISSUE THREAD

**Issue by ryanmusante** [LoneGazebo/Community-Patch-DLL#5023]
1. Mod version (i.e Date - 4/23):
12-18-1

2. Mod list (if using Vox Populi only, leave blank):
AI - No CS Annexers,
Diplomacy - Auto-Denounce,
Global - Commander Influence Borders,
Global - Local Generals,
Global - No Ocean Plundering,
Global - Pro-rata Buildings Purchase,
Global - Religious Settlers,
Units - No Mechs,
Units - Subs Immune Under Ice,
Units - Visible Trade Units,
Tectonic Map Script
And many UI Mods

3. Error description:
There are several inter-turn messages that interrupt the normal flow of a game. 

According to whoward69 in mods :

_Diplomacy - No Expansion Dialogs
Diplomacy - No Pointless Dialogs_ 

```
	<!-- All of these are "fluff" messages - it doesn't matter how you answer, as the AI ignores your response -->
	<!-- See DiscussionDialog.lua - all of these generate DIPLO_UI_STATE_BLANK_DISCUSSION, DIPLO_UI_STATE_BLANK_DISCUSSION_MEAN_HUMAN or DIPLO_UI_STATE_BLANK_DISCUSSION_MEAN_AI states -->
```

Regardless of your choice it does not change gameplay, only slows down turns and is an annoyance. 
```
		<Row ResponseType="RESPONSE_DISAPPOINTED"                              StfuType="STFU_IGNORE"/>

		<!-- Denouncement -->
		<Row ResponseType="RESPONSE_WORK_AGAINST_SOMEONE"                      StfuType="STFU_IGNORE"/>
		
		<!-- Pointless comments to massage the player's ego -->
		<Row ResponseType="RESPONSE_BOOT_KISSING"                              StfuType="STFU_IGNORE"/>
		<Row ResponseType="RESPONSE_COMPLIMENT"                                StfuType="STFU_IGNORE"/>
		<Row ResponseType="RESPONSE_WARMONGER"                                 StfuType="STFU_IGNORE"/>
```

**Comment by LoneGazebo** [comment]
I found that removing some of these caused issues in syncing for MP.
