### ISSUE TITLE
After loading MP game, turn order is messed up

### ISSUE THREAD

**Issue by Voker57** [LoneGazebo/Community-Patch-DLL#5024]
_1. Mod version (i.e Date - 4/23):_
12.18.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When loading save with two players at war, they are placed into wrong (non-existant?) turn slice, so neither of them can move units.

_4. Steps to reproduce (optional):_
Load save [http://dump.bitcheese.net/files/pidysak/auto.Civ5Save] (or reproduce condition with two (non-host?) players fighting), host is Ethiopia or Russia, fighters are Sweden and Celts.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

http://dump.bitcheese.net/files/tepimyj/logs.zip

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

http://dump.bitcheese.net/files/pidysak/auto.Civ5Save

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
http://dump.bitcheese.net/files/jykypor/plcm.png

**Comment by Voker57** [comment]
Another game exhibited same behavior.

**Comment by TechpriestEnginseer** [comment]
The AutoSave in MoiMagnus's issue seems to have fixed the issue(or I am unable to reproduce it now).

**Comment by Voker57** [comment]
@TechpriestEnginseer is the fix supposed to be retroactive? I loaded the save with autosave fix mod and game is still broken.

**Comment by TechpriestEnginseer** [comment]
no.

**Comment by Voker57** [comment]
Issue still present with autosave fix (in VP 12.18.1 at least)

**Comment by Voker57** [comment]
Issue still present in 2.17, even with autofix.

**Comment by Voker57** [comment]
Bug is not present in 5.20.3.

**Comment by Voker57** [comment]
Steps to reproduce: 

1. create MP game with 3 players and hybrid turns
2. one non-host declare war to other non-host
3. on the next turn turns are broken and will never pass.

**Comment by Voker57** [comment]
@LoneGazebo why closed? Checked, problem is still present in 3.14 beta

**Comment by supermerill** [comment]
when  a new version is coming out, all inactive issue are closed.

**Comment by LoneGazebo** [comment]
The double save method is the only known solution - this was a vanilla issue as well.

**Comment by Voker57** [comment]
Not tested with 3.14 but on previous version, double save didn't work either. It only works against double AI turn (which is now fixed with autosaves anyway)

**Comment by Voker57** [comment]
Also, as I said earlier, 5.20.3 does not have this problem.

**Comment by LoneGazebo** [comment]
I've looked at older versions and I don't see anything that would explain what you're seeing.

**Comment by LoneGazebo** [comment]
@ilteroi any possibility the small change to slice timing in CvGame could cause this? It's the only thing I see that's changed.

**Comment by Voker57** [comment]
Tried double-saving, doesn't help.

Also tried reverting this https://github.com/LoneGazebo/Community-Patch-DLL/commit/0737e57c7231cbb42ddd9ea43dcb4f5cd99ef6ae#diff-ea1347045d6dcad1bfd5c1b741a4e489L8107 not sure if I did it properly but no dice

**Comment by Voker57** [comment]
Testing have determined that bug was introduced at some point between 9.6.2 and 9.18.

P.S. Maybe this bug should be reopened?

**Comment by ilteroi** [comment]
hmm. looking at the history, i did some experiments between those two versions, but didn't officially revert them ...

**Comment by Voker57** [comment]
@ilteroi with your current "shiny" branch, UI appears to be broken, anything else that should be done except dropping DLL into current 3.28?

**Comment by Voker57** [comment]
@ilteroi Your fix works, thank you!
