### ISSUE TITLE
Fourth Great Prophet not spawning

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5025]
1. **Mod version** (i.e Date - 4/23):
11-30-18

2. **Mod list** (if using Vox Populi only, leave blank):
I've observed this twice with different versions now, though I can't remember what version the time before this time was but I definitely had no extra mods beside VP active back then.

The game I'm playing now has the following mods, including VP (11-30-18):
VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

3. **Error description**:
I know it's a long modlist but I have observed this error with different versions and mostly VP in common.

The issue is that my GP won't spawn. It spawned fine the first (for founding), second (for enhancing) and third (for planting a Holy Site) time, but now it just won't do it. I am in the Enlightenment Era right now, so I can't buy Prohpets from the city menu yet, but have to set the faith order buy mechanism to "Save for Great Prophet", which worked flawlessly before but seizes to work now for the fourth GP. I was thinking that maybe it had to do with me accumulating more Faith than is needed for a GP without setting that option for the first time this game, though I did set it later and it didn't buy a GP and I even tried buying some Inquisitors and Missionaries to get below the GP threshold again and set the option to save for GP but it just went over the threshold and still didn't get a GP.

I have found issue #3904 which seems to describe a similar problem and I remember that with an earlier version of VP (from last year, I think) this happened as well.

4. **Steps to reproduce** (optional):
If you need saves and my MODS folder let me know, though it's quite a lot to upload (about 410 MB so I'll probably have to split it into archives and upload them separately somewhere).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
Enlightenment Era is what I assume you should be buying them or something...
@Infixo

**Comment by Padre19** [comment]
-- for spawning Great Prophets in Enlightenment Era
--Copy&Paste in EEVP_Eras.sql

UPDATE PostDefines
SET Key = 'ERA_ENLIGHTENMENT'
WHERE Name = 'RELIGION_LAST_FOUND_ERA';
