### ISSUE TITLE
Hanse lies about what it does

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#5027]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
It sez it gives 5% to the city it's from, but it's 3% to all Hanse cities.

**Comment by TechpriestEnginseer** [comment]
a screenshot would help me find it easier than having to scroll through 5000 info text. :)

**Comment by UndeadDevel** [comment]
The incorrect part of the description is "+5% [production icon] Production for each Trade Route from this City to a City-State.", which should actually read "+3% [production icon] Production in this City for each Trade Route with a City-State empire-wide."

**Comment by Enrico-Swagolo** [comment]
UndeadDevel is right
