### ISSUE TITLE
Ceilidh hall doesn't provide happiness

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#503]
Not quite sure this is intended as the circus change is a recent one.

**Comment by LoneGazebo** [comment]
I left if off on purpose, but I can add it if we feel it is necessary.

**Comment by Edaka** [comment]
Ah, okay then. Thought you'd overlooked that, sorry. Haven't gotten to trying it out to share my thoughts about the necessity, anyway.
