### ISSUE TITLE
Strategic Resource count inaccurate

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5030]
_1. **Mod version** (i.e Date - 4/23):_
11-30-18

_2. **Mod list** (if using Vox Populi only, leave blank):_

VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

_3. **Error description**:_
This bug may be related to issue #5015 

The issue concerns the amount of strategic resources that are available to me; basically upon discovery of the tech for Coal I got 8 Coal "for free" for no reason, which can actually be traded.

This doesn't seem to have happened to the AI and it also doesn't seem to affect Horses, Iron or Paper in my current game.

_4. **Steps to reproduce** (optional):_

![civ5screen0076](https://user-images.githubusercontent.com/30495439/50525861-14d08600-0ad6-11e9-9421-7f1daf7daf95.jpg)
![civ5screen0077](https://user-images.githubusercontent.com/30495439/50525865-1d28c100-0ad6-11e9-8680-4f922597f61a.jpg)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
are you sure your city-states dont have them or providing a bonus?

**Comment by UndeadDevel** [comment]
Yes I'm sure. I just double checked, but City State resources would show up in the drop down panel anyway (they do for my horses, which I get from CS, for example) and as you can see in the screenshot that isn't the case.

I also don't get any bonuses that would give me coal.

**Comment by UndeadDevel** [comment]
Just gonna leave this here, for the record: After unlocking Oil through research, I received my 1 Oil from Statecraft, but also 2 extra Oil that I shouldn't have gotten (see screenshot). It is displayed as being imported despite me not making any such deal or having an appropriate CS ally with improved Oil and it would normally have to show _who_ I'm importing it from, anyway, which it doesn't.
This is still with the same version and the extra Coal is also still there...who knows, maybe someone else encounters this at some point as well with less mods or it really is a mod conflict (though I have no idea how).

![strategic_resource_take_2](https://user-images.githubusercontent.com/30495439/51225986-296da480-1945-11e9-876f-df69d53cb17f.jpg)
