### ISSUE TITLE
Great Prophet and Veneration

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#5033]
_1. Mod version (i.e Date - 4/23):_

current
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Spawning a Great Prophet before Industrial era won't proc the 25% faith to culture conversion. After Industrial era, purchasing them does proc it. If it's intentional, this is really weird.

**Comment by TechpriestEnginseer** [comment]
Purchasing Great People never procs them.
