### ISSUE TITLE
Low Upgrade Costs

### ISSUE THREAD

**Issue by chicorbeef** [LoneGazebo/Community-Patch-DLL#5036]
1. Mod version: 12/18

3. Error description: Upgrade costs seem weirdly low. It only costed 40 Gold for me to upgrade a Warrior into a Hoplite.

**Comment by TechpriestEnginseer** [comment]
Yes to encourage you to spam Warriors and upgrade them... (also 40 Production to train a Warrior = 40 Gold to upgrade one).
