### ISSUE TITLE
Defender of the faith mismatch

### ISSUE THREAD

**Issue by IVastatorI** [LoneGazebo/Community-Patch-DLL#5037]
_1. Mod version (i.e Date - 4/23):_

12/18
_2. Mod list (if using Vox Populi only, leave blank):_
3rd/4th unique components
ui mods

_3. Error description:_ 
Defender of faith description says + 2 faith, but it shows only +1 faith on city screen (see pic)

4. Screenshots (optional):
![civvdefaith](https://user-images.githubusercontent.com/46298555/50573898-f53ea380-0ddc-11e9-9bd5-956d4e883e76.jpg)

**Comment by TechpriestEnginseer** [comment]
good eye, a 4 months bug.
