### ISSUE TITLE
Martial Spirit doesn't scale with gamespeed

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#5039]
_1. Mod version (i.e Date - 4/23):_
currenbt

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
basically title. It's 50 turns, which is much weaker on marathon or epic than normal.

**Comment by TechpriestEnginseer** [comment]
something u shuld bring up to the community and have ppl agree with u on this
