### ISSUE TITLE
Unable to Purchase Tiles in Cities

### ISSUE THREAD

**Issue by macfadden510** [LoneGazebo/Community-Patch-DLL#504]
I am unable to purchase tiles, even as the United States or Russia.
- Running CP, CBP, CBP-EUI, CivIV Diplomacy, CSD, & More Luxuries
- Running Civ Name by Policies, Complete Historical Religions

**Comment by LoneGazebo** [comment]
This sounds like a lua bug. Did you delete the lua files as per instructions?

G

**Comment by macfadden510** [comment]
I have already deleted the LUA folders from CP and CBP.
CP still has the communitas.lua file that's in the mapscripts file.
CBP still has a couple lua files that were not in the LUA folder (TradeRouteOverview, TradeRouteHelpers, ChooseTradeUnitNewHome, etc.)

**Comment by macfadden510** [comment]
I also have UI-TradeRouteEnhancements by Whoward.

**Comment by macfadden510** [comment]
Solved the Issue (I think...)! I got deleted the UI-TRE and started a new game. Saw the spinning gold coin in the upper left of the city screen and was able to start purchasing tiles. 

Guess it's time to play as Russia now.

**Comment by LoneGazebo** [comment]
Yeah that mod is included, you don't need it. It'll cause issues.
