### ISSUE TITLE
City needs iron when I've got a surplus

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#5041]
_1. Mod version (i.e Date - 4/23):_
11-21-1-3

_3. Error description:_ 
I've got 52 iron, why does Otrar want more? It has a Mine Field when I gained it in a peace deal.
![image](https://user-images.githubusercontent.com/34615525/50720253-6dc09100-1077-11e9-80ff-68c0b68adffc.png)

[Askia_0362 AD-1942.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2729145/Askia_0362.AD-1942.zip)

I don't know it the 2% increased cost means anything because the pop-up occurred the turn after I gained Otrar.

**Comment by LessRekkless** [comment]
The message went away when I pushed Morocco's army back.

**Comment by LoneGazebo** [comment]
It's likely that it was just a UI refresh quirk.
