### ISSUE TITLE
Exposing ContentManager.GetAllPackageIDs()

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#5045]
Is it feasible to use this Lua to list out fake DLC like EUI and Modpacks since it only lists out real DLC(which I am unsure if it's hardcoded to do so or it really can't find fake DLCs)

This may prove to be rather beneficial in the near future.....

**Comment by LoneGazebo** [comment]
This entity isn't in the DLL, so I don't see a way to do it.
