### ISSUE TITLE
CTD during AI turn

### ISSUE THREAD

**Issue by aht820** [LoneGazebo/Community-Patch-DLL#505]
Hello. I'm using the 8-6 version. I get a CTD during the AI turn just after rejecting or accepting an offer from William. My list of mods is below and my save and dump file can be found at this link. Please let me know if you need anything else. Thank you for your help

https://www.dropbox.com/sh/zccgmsz0jthbfjs/AADn0mt8JxLS-PQ4LzfWt1iOa?dl=0

![mods list](https://cloud.githubusercontent.com/assets/13701528/9148357/c551afd6-3d3e-11e5-8146-ff9af4b0d6f6.jpg)

**Comment by LoneGazebo** [comment]
Thanks for the report. I think I've got a fix. I'll upload a new version shortly, which you can try out (it'll be savegame compatible).

G

**Comment by aht820** [comment]
I still got a crash with the new version

**Comment by LoneGazebo** [comment]
Upload your mini dump.

**Comment by LoneGazebo** [comment]
My fix was quick, but it may be a deeper issue.

**Comment by aht820** [comment]
https://www.dropbox.com/s/gzw5pbuclz738ys/newCvMiniDump.dmp?dl=0

**Comment by LoneGazebo** [comment]
Alright, rewrote the faulty chunk of code entirely. I'm linking you a new version of the 6-7 to see if it works. You'll be my guinea pig, ok? :) Look for link shortly.

**Comment by LoneGazebo** [comment]
Make sure to clear cache. Here's link: https://www.dropbox.com/s/e0g0y5xet7sf4i1/Community%20Patch%20%288-7v2%29.zip?dl=0

**Comment by aht820** [comment]
That's working

**Comment by LoneGazebo** [comment]
Sweet.

**Comment by aht820** [comment]
Thank you!

**Comment by aht820** [comment]
I'm getting another crash during the AI turn. Same mods different game. Its the same link that I used yesterday. Fold is called 2nd crash
https://www.dropbox.com/sh/zccgmsz0jthbfjs/AADn0mt8JxLS-PQ4LzfWt1iOa?dl=0
