### ISSUE TITLE
community patch v89 Bug with Gold focus and Wonders

### ISSUE THREAD

**Issue by Dreifels** [LoneGazebo/Community-Patch-DLL#5050]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Dreifels** [comment]
community patch v89
I notice massive bug with Gold focus and showing wonders after finished reasearch of Guild.
when I finish research of Guilds which should give producing option focus Gold, it does not give it, also I cannot see the new wonders listed as available.
This is replicateable. When I use Ingame Editor and set this research back, then all works fine, as soon as I have this research done, it is back. no Gold focus, no new wonders. 
So I'm forced to run endless production of something and delete it then .
Game makes no sense by that.

**Comment by Dreifels** [comment]
logging needed? Howto do? 
I can build a complete pack of the files (as 7z it's 400 MB complete \Documents\My Games\4-Sid Meier's Civilization 5.7z\) just before and just after it happens along with screenshots.

**Comment by TechpriestEnginseer** [comment]
![image](https://user-images.githubusercontent.com/13937047/51078990-18d2db00-1674-11e9-9ee6-56e4eee7bef1.png)

**Comment by Dreifels** [comment]
ok, here it is.
I checked it again and probably I found the concrete issue/bug (the gold problem is a result only):
With guild the city screen buttom for production not working correctly and the windows for selection overlapp each other, so scrolling to the bottom of the list where Wonders and Gold is, is not possible.
I made some screenshots (there are in the screenshots folder).
I made a complete package with logs, cache, installed mods, two sav files related and screenshots with explanations, so that it it ieasy to replicate, as "TEST-Sid Meier's Civilization 5.7z", which you may download here https://workupload.com/file/K4YWHCae

**Comment by TechpriestEnginseer** [comment]
![image](https://user-images.githubusercontent.com/13937047/51078990-18d2db00-1674-11e9-9ee6-56e4eee7bef1.png)
You did not enable logging.

**Comment by Dreifels** [comment]
simply forgot it, but logging in this case will give no new answer, as I have the current save only and can't go back (or I have to step back by ingame editor so, that it is just before the research finish and then do a (logged) turn. But as it is a interface mismatch issue, what will logging of one turn give additional information, in that case? You have full package and the two sav in case, same as I have.
Your request is confusing me.

**Comment by Dreifels** [comment]
additional remark: it it replicateable by using ingame editor disable/enable the research guild.
In same turn, no logging will happen as no next turn processed. Means, the existence of guld research already is causing that. Nothing that gets proceded by after end of turn procesing, and so nothing logged for this change as it is no turn.

**Comment by Dreifels** [comment]
ok, don't want to discuss, made it again as you want it,  just with logging enabled.
made no new screenshots, pls see the screenshots and  their comments in former package.
https://workupload.com/file/DPCex3uA

**Comment by TechpriestEnginseer** [comment]
The logging immediately tells me what's the issue if it's caused by Lua or a modding conflict.

**Comment by TechpriestEnginseer** [comment]
![image](https://user-images.githubusercontent.com/13937047/51092292-6ae63000-174a-11e9-8d4b-546a4b7e347e.png)
DLL Production Popup is a custom DLL mod and DLL Mods are incompatible with the CP.
