### ISSUE TITLE
using ICON_RES_MANPOWER instead of ICON_WAR

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#5052]
![image](https://user-images.githubusercontent.com/13937047/51015505-5d9a2d00-1521-11e9-963d-a84e2ddc22de.png)
I feel the [ICON_WAR] is overused and the War Supply could use a resource that is already in the game, but left unused.

**Comment by LoneGazebo** [comment]
Meant to respond - I don’t love the manpower icon because it’s not very clear to see at its size.

**Comment by TechpriestEnginseer** [comment]
that's fine
