### ISSUE TITLE
Stable can't be built despite having improved horses

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5059]
_**1. Mod version** (i.e Date - 4/23):_
11-30-18

_**2. Mod list** (if using Vox Populi only, leave blank):_

VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

_**3. Error description**:_
Can't build a stable in my city despite having improved horses that are being worked by the city.

In other cities this issue did not come up; maybe it happened here because the horses actually used to belong to a different city first, which had them improved. I razed that city and put my own city up but by then the horses had been grabbed by another one of my cities that already had a stable. Finally, I used the city UI of the new city to switch the horses to the now bugged city, which was many turns ago, and as you can see in the screenshot it still won't allow me to build the Stable despite the city actually working the improved horse tile.

_**4. Steps to reproduce** (optional):_
(Raze city with access to improved horses)
Found new city without having horses or sheep or cattle
(Work the horse tile from another city)
Acquire the improved horse tile for the newly founded city by using the switch mechanic
Observe that a Stable can't be built in that city despite the city working improved horses

I'd rather not upload my MODS folder since it's really quite large (about 400 MB) but if necessary I can probably manage it.

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![stable_issue](https://user-images.githubusercontent.com/30495439/51137318-76168a00-1836-11e9-9360-c40bfc805e87.jpg)

**Comment by UndeadDevel** [comment]
Doesn't work for me, unfortunately. The other city doesn't even have the switch icon on that tile for some reason. I can work the tile from the other city, which will make the switch icon reappear in the bugged city, but if I then use it in that city the Stable still can't be built (the other city will stop working the tile, however).

So maybe this is actually a bug with the tile switching system: once I switch the tile to the bugged city, the other city will stop working it but doesn't get the switch icon; if I then click the citizen slot on that tile in the non-bugged city, it will work the tile normally (instead of getting the manual lock like it should and does for every other tile with a regular slot); so it seems that the switch mechanism is only half-active if you know what I mean.
That may be what's causing the bug with the Stable.

**Comment by psparky** [comment]
I think it's only the city that originally acquired the tile that can ever gain the ability to build stables. Which city currently works the tile is irrelevant.

**Comment by TechpriestEnginseer** [comment]
Closed because cannot reproduce anymore in current version(unless future issues arises again).
