### ISSUE TITLE
Minor bug: Archeologist UI issue

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5061]
_**1. Mod version** (i.e Date - 4/23):_
11-30-18

_**2. Mod list** (if using Vox Populi only, leave blank):_

VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

_**3. Error description**:_
When giving an Archeologist the order to dig up a site, the UI responds differently than it does with workers; specifically, the button does not switch to disabled status, the number-of-turns-display does not decrement by 1 and the Archeologist can still be given different orders for the turn. The Archeologist will carry out the dig, however, at the end of the turn, after the player presses "Next Turn".

This is not a big deal, obviously, and the only possible functional impact is that if the player wanted to do something with the Artifact/Landmark in this turn, he would be annoyed by having to handle all other actions in the game first so that he can press Next Turn and thus finally get the Archeologist to complete his action so the player can add the Artifact to the desired collection or whatever else the player planned to do. It does feel awkward, though, and is inconsistent with the way Workers are handled in the UI.

In the screenshot you can see the status quo after I pressed the button. Notice how the Archeologists are standing still (they had been doing their working animations before I pressed the button) and the button is still enabled (it doesn't give me any feedback that I pressed it).

_**4. Steps to reproduce** (optional):_
Send an Archeologist to a dig site and push the button ("Construct an Archeological Dig")

I'd rather not upload my MODS folder since it's really quite large (about 400 MB) but if necessary I can probably manage it.

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![archeologist_issue](https://user-images.githubusercontent.com/30495439/51139493-fbe90400-183b-11e9-9d5d-f94cdeb1d3ed.jpg)

**Comment by LoneGazebo** [comment]
This is a vanilla thing - because the archaeologist is 'expending' himself after the dig and has a popup associated with it, the UI doesn't treat it as a build order.
