### ISSUE TITLE
Possible issue: Cities grabbing tiles they wrongly think are useful to them

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5062]
_**1. Mod version** (i.e Date - 4/23):_
11-30-18

_**2. Mod list** (if using Vox Populi only, leave blank):_

VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

_**3. Error description**:_
In the screenshot below you can see a city having expanded its borders well outside its working range to grab a Fish resource, which the AI then even sent a Work Boat to, as well as an even further removed Atoll. There are no friendly cities close-by, which could work those tiles and the city itself obviously can't, either, so it is questionable whether the city should have expanded there instead of grabbing ocean tiles it could theoretically work, since there are no bonuses, to my knowledge, from having an Atoll that isn't worked or even inside the working radius to begin with.

I realize that this can be viewed as working as intended, I suppose, and it's not a big deal, but since I'm on a reporting spree...(this is the last report, no worries ;) )

_**4. Steps to reproduce** (optional):_

I'd rather not upload my MODS folder since it's really quite large (about 400 MB) but if necessary I can probably manage it.

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![resource_grab](https://user-images.githubusercontent.com/30495439/51139721-8df10c80-183c-11e9-93d4-18dd3c63196f.jpg)

**Comment by LoneGazebo** [comment]
It's possible he bought the tile for chokepoint purposes.

**Comment by UndeadDevel** [comment]
I don't think you can buy that far out though, can you?

**Comment by LoneGazebo** [comment]
Looking at the city, though, it's the only 'good' tile in range. That's why it went for it (the city AI).

G

**Comment by UndeadDevel** [comment]
Reasonable argument. 
However, that still leaves the Fish that is also out of range and was improved by Kamehameha for no reason with a Work Boat...it is now a free health for my or my allies' armies and doesn't give him any benefit.

**Comment by LoneGazebo** [comment]
Eh, it's fine.
