### ISSUE TITLE
"Unable to load texture" errors on loading screen, no control over units

### ISSUE THREAD

**Issue by red525** [LoneGazebo/Community-Patch-DLL#5063]
_1. Mod version (i.e Date - 4/23):_
18th December 2018

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
"Unable to load texture" Error on the following:
DC45_DiplomacyOverview.dds
DC45_AdvisorCounsel.dds
DC45_Greatworks.dds
DC45_Culture.dds
DC45_EspionageOverview
TopPanelGoldenAge.dds
MenuButton.dds
HelpButton.dds
Screenshot; no options are shown for units when I attempt to select them, thus the settler can't found a city, thus I basically have no game. The advanced UI bullshit just doesnt seem to be working.
[bullshit.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2757368/bullshit.zip)
![20190114224041_1](https://user-images.githubusercontent.com/46693741/51146572-255f5b00-184f-11e9-8164-9ffbdf1729ee.jpg)

_4. Steps to reproduce (optional):_
Just trying to play the game at all

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
We are sorry to hear that. Perhaps this mod should fix your problem. Just drag it onto your Mod Folder and activate it. It may fix your problem. If not, return back with new logging files (which should be new after activating this mod).
[Temporary Bugfix (v 1).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2757610/Temporary.Bugfix.v.1.zip)

**Comment by red525** [comment]
Didn't work.
One thing I've noticed: I've seen UI_bc1 get mentioned and that it should be in my main directory's DLC folder (i.e. one of the FAQs I saw mentioned to delete that folder from the DLC directory in order to completely uninstall VP) but it's not there, do you think that might be the cause of the issue?
[bullshit 2 electric boogaloo.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2757776/bullshit.2.electric.boogaloo.zip)

**Comment by TechpriestEnginseer** [comment]
probably

**Comment by red525** [comment]
Downloaded UI_bc1 from the manual install mega folder, dropped it into DLC and now it works. I thought the installer would have done that on its own seeing as the "how to install" pages don't mention UI_bc1 at all. Anyways, thanks for the help.
