### ISSUE TITLE
1-15, CP-only, UI broken, no EUI

### ISSUE THREAD

**Issue by ShelleyProm** [LoneGazebo/Community-Patch-DLL#5065]
_1. Mod version (i.e Date - 4/23):_
1-15

_2. Mod list (if using Vox Populi only, leave blank):_
CP-only
HellBlazers Map script v.5

_3. Error description:_ 
Top line of my User Interface is broken (see below in the screenshot). I am not using EUI, never used it. I tried it with other mods (including CP-only) and just CP-only, always the same. I tried to reinstall civ 5, delete game chache, verify data files, still the same issue. Without CP-only it works fine.
EDIT: When I press top right corner "Menu" or "Help" nothing happen.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2760466/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![screenshot 166](https://user-images.githubusercontent.com/46424881/51194023-7e300180-18ea-11e9-8eae-c8e9ca0de431.png)

**Comment by ShelleyProm** [comment]
EDIT SOLUTION:
Before i just installed the CP-only through the installer.
Now I installed the whole vox populi(no EUI) through the installer but only activate the CP-only and it seems to work now.

**Comment by JFDaly** [comment]
There seems to be a minor syntax error at line 163 of the TopPanel.lua file in (1) Community Patch\LUA; a missing bracket. A quick fix is to add a ) right before the ; for those that encounter this issue before a solution can be pushed out.

**Comment by LoneGazebo** [comment]
I’ll fix thanks!
