### ISSUE TITLE
Custom Tutorial

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#5066]
Here is everything you need for the Custom Tutorial hooks. 

Examples and details are included in the project. You can incorporate the files into CP/VP if that's easier, just make sure to follow how it's setup - the Advisor.xml, Advisor.lua, and OptionsMenu.lua should be imported to VFS to override the vanilla, the CustomTutorial_Functions.lua should be added as an InGameUIAddin, and the Tutorials_Master.sql should be added to the database. 

Let me know if you, or whoever ends up coding in the Tutorials, needs any help.

https://drive.google.com/file/d/1mxNJ_zV9aBhlrdh3Bv8aJ7xJ2NL1MZej/view?usp=sharing

**Comment by JFDaly** [comment]
> Here is everything you need for the Custom Tutorial hooks. Examples and details are included in the project. You can incorporate the files into CP/VP if that's easier, just make sure to follow how it's setup - the Advisor.xml, Advisor.lua, and OptionsMenu.lua should be imported to VFS to override the vanilla, the CustomTutorial_Functions.lua should be added as an InGameUIAddin, and the Tutorials_Master.sql should be added to the database. Let me know if you, or whoever ends up coding in the Tutorials, needs any help.
> 
> https://drive.google.com/file/d/1mxNJ_zV9aBhlrdh3Bv8aJ7xJ2NL1MZej/view?usp=sharing

**Comment by LoneGazebo** [comment]
Very cool. @TechpriestEnginseer you want to work on this with me, see if we can make a few tutorial elements for VP?

**Comment by TechpriestEnginseer** [comment]
Sounds good, what is needed to be done?

**Comment by LoneGazebo** [comment]
I guess we need to decide what elements deserve a tutorial popup, and when/where to trigger them?

**Comment by TechpriestEnginseer** [comment]
I feel like we should remove all the old tutorials and make new ones.

**Comment by TechpriestEnginseer** [comment]
My initial thought is that we disable Firaxis-made tutorials by default and then create a new game option from the game set-up called Tutorials and then start from there.

**Comment by JFDaly** [comment]
There is a new game option "New to Vox Populi" included, which means no default tutorials should ever popup anyway.

**Comment by TechpriestEnginseer** [comment]
ooh even better.

**Comment by TechpriestEnginseer** [comment]
Guess I'll take that as a yes.

**Comment by LoneGazebo** [comment]
Oops for some reason I didn’t get an alert for this.

**Comment by LoneGazebo** [comment]
I think that’s a great idea.
