### ISSUE TITLE
Market ITR Bonus - Either Description of Notification Issue

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5069]
_1. Mod version (i.e Date - 4/23):_
1-15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Currently the market says you get a food bonus when a ITR going TO or FROM your city completes. I had a scenario where both my cities had the market, but only the city that the ITR was from showed a bonus in notifications.

So one or the other is incorrect.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
That’s just a bad description- it is supposed to only trigger in the origin city.
