### ISSUE TITLE
Germany CS ally/friend bonus not scaling with era

### ISSUE THREAD

**Issue by airbse** [LoneGazebo/Community-Patch-DLL#5077]
_1. Mod version (i.e Date - 4/23):_
1-15

_2. Mod list (if using Vox Populi only, leave blank):_
UI - Filters in Trade Route Overview (Vox Populi) (v 1)

_3. Error description:_ 
Germany does not get era scaling bonus for CS allies. Savegame attached. Currently in Classical Era and Berlin gets same culture/science as in Ancient Era (2 per ally).

_4. Steps to reproduce (optional):_
Just load the save and check culture and science in Berlin. 2 CS allies currently.
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2774611/QuickSave.zip)

**Comment by LoneGazebo** [comment]
Ancient and Classical have the same scaling bonus (Ancient is '0', Classical is '1'). All scaling works this way.

**Comment by airbse** [comment]
confirmed. Thanks for clearing that up for me.
