### ISSUE TITLE
City-States and Defensive Pacts 2: Electric Boogaloo

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#508]
https://www.youtube.com/watch?v=KTk1NhyhCwc
As you can see, I only declared a war on 3 civs, while my allied city-states - to the whole world.

**Comment by LoneGazebo** [comment]
Oh lord. Huh. Okay, so looking at the video the text makes it out to be a situation where the major civs DOW the CSs. That may not be indicative of how the actual DOW process is going on. 

Were there nested defensive pacts (i.e. Ethiopia with Polynesia, Polynesia with Netherlands, Netherlands with someone else, etc.) that weren't shown, or was that 3-civ DP the only one?

I'll look at this - I've been trying to work within the confines of the existing function for DPs, but I may have to rewrite it from scratch if this becomes an increasingly-complex issue.

**Comment by Radost** [comment]
I suspect CS dows are treated differently from civs ones. I.e. they declare a war to each DP faction separately thus triggering another DPs from this faction. And as you can see on the 4th second, there are a lot of defensive pacts.

**Comment by LoneGazebo** [comment]
Well, all DOWs funnel through the same function in the Diplomacy AI, minor and major. There are boolean values that feed into it, such as bDefensivePact or bMinor. I need to make sure that these are firing correctly.

**Comment by LoneGazebo** [comment]
You have a copy of this save to test on? I'm going to upload a version that - I think - has fixed this. Mind testing it for me?

**Comment by LoneGazebo** [comment]
https://www.dropbox.com/s/mumyoi445w1j6xk/Test%20Package.zip?dl=0

**Comment by LoneGazebo** [comment]
Should fix CS influence issue and the DP issue of the CS. Let me know.

**Comment by Radost** [comment]
Nope, still the same.

**Comment by LoneGazebo** [comment]
Which is still the same? Also, you cleared your cache after install?

**Comment by Radost** [comment]
The same war declaration to everyone.
Yes, cleared cache and moduserdata.

**Comment by LoneGazebo** [comment]
Nother day, nother version: https://www.dropbox.com/s/gvj35yrik4w0g30/Community%20Patch%20%28v%2066%29.zip?dl=0

**Comment by Radost** [comment]
Nailed it.
![8930_2015-08-12_00012](https://cloud.githubusercontent.com/assets/1131228/9228626/d052c436-4132-11e5-8173-24674104e1ae.png)
![8930_2015-08-12_00013](https://cloud.githubusercontent.com/assets/1131228/9228642/dd5fcd22-4132-11e5-8f8d-4aa02f49880c.png)

**Comment by LoneGazebo** [comment]
yay!
