### ISSUE TITLE
City state "They want you to defeat invading barbarians..." icon should have 1 space between it and text

### ISSUE THREAD

**Issue by TheRealAyCe** [LoneGazebo/Community-Patch-DLL#5088]
_1. Mod version (i.e Date - 4/23):_
1-15 with EUI from installer (Vox Populi (1-15).exe)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
It seems a space is missing between the text and the icon.

_4. Steps to reproduce (optional):_

![csbarbtooltip](https://user-images.githubusercontent.com/11407231/51427617-4aaaeb00-1bfa-11e9-88e5-91e956a68778.jpg)

**Comment by LoneGazebo** [comment]
All of the diplo quest lineups do this to prevent doubling on the end of the line.
