### ISSUE TITLE
No option to get a great prophet

### ISSUE THREAD

**Issue by Rockinroger52** [LoneGazebo/Community-Patch-DLL#509]
![screenshot_1](https://cloud.githubusercontent.com/assets/9918690/9155205/ad7a2f04-3e75-11e5-90eb-39371ed0b8ec.png) Currently playing version 8.8. I started a new game and earned enough to make a great prophet but cant option to it.
 
I have logging enabled how do i upload them?

https://www.dropbox.com/s/mv8rrx81q32edun/Logs.zip?dl=0

**Comment by Rockinroger52** [comment]
Mods enabled

Aggressive and Expansive AI (v,1)
AI-Warmonger Agjusments (v,1)
Buildins Goldsmith v-3
Buildings Guilds Great Work Display v-2
Buildings Lighthouse near sea v-2
buildings mill changes v-5
buildings Textile mill v-3
Buildings Upgrade system v-12
Buildings Garden and monument overhaul v-12
City limits v-7
CSD for CBP 6-19 v27
Civ Iv Diplomatic Featues 6-19 v 10
Classical building pack v-4
CBP Compatability files EUI v-1 (8.8)
CBP more luxuries Compability v-1 (3-6)
CBP v-13 (8-8)
Community Patch v-66 (8.8)
Event and Decsions CBP edition 3/30
Fortress Borders v-2
Global Barbarian XP level 6 v-2
Global City Bombarb range v-2
Global City Forest Bonus v-3
Global City working distanve v-7
Global Counter Religion v-2
Global Expionage Rave v-3
Global Expionage Reports v-2
Global Grateful Settlers v-2
Global National Wondes eXclude Razing v-1
Global Pro rata buildings purchase v-2
global seperate great admiral v-1
Global truluy free great people v-1
Improved air recon v-1
Improvement Airbases v-12
Improvement Tunnel v-4
Improvements in Water tiles v-2
Industrial building pack v-2
Infoaddict v-22
JFDs civ pack 1
JFDs civ pack 2
JFDs Cultural diversity core v-2
JFDs Exploration Continued Expanded ver 6
Landmines for bnw v-3
maps improved small landmasses v-14
Medieval and Renaissance building pack v-1
More Luxuries v 155
National Wonder collection v-3
Natrural Wonders fix v-1
Palace Additions v-6
Promotions Ancient ruins choice v-2
Promotions Heli Airrecon v-6
Promotions jet long range recon v-3
Quick turns v-10
Reforestation v-8
Religions Bonus beliefs v-1
Religion Natural wonder epiphany v-4
Strategic buildings pack v-2
Terrain Brazilwood camp extension v-3
Terrain chateau ext. v-3
Terrain Polder ext v-3
Terrain Poor tiles Tweak v-2
Terrain Terrace Farm ext v-3
Trade Marble shipments v-1
Trading posts grow into towns v-5
Ui great work manager v-13
UI overlay luxuries v-3
UI Relions Spread v-13
UI Trade opportunities v-28
UI Trade route enhancements v-6

**Comment by Radost** [comment]
Did you get a religion?

**Comment by Rockinroger52** [comment]
No i ended up reloading everything and it seems fine now.

**Comment by Rockinroger52** [comment]
So we should close this i think.
