### ISSUE TITLE
Crash on processing barbarian turn.

### ISSUE THREAD

**Issue by themagicalyang** [LoneGazebo/Community-Patch-DLL#5090]
_1. Mod version (i.e Date - 4/23):_ November stable release.  (89 - Beta)

_2. Mod list (if using Vox Populi only, leave blank):_ 
  - Archaelogy Aesthetic Adjustments (https://steamcommunity.com/sharedfiles/filedetails/?id=758243269)
  - Barbarians Unlimited Exp (https://steamcommunity.com/sharedfiles/filedetails/?id=82186217) 
  - Civ Linked Great Generals (https://steamcommunity.com/sharedfiles/filedetails/?id=288364518)
  - RED Modpack.

_3. Error description:_ Crashes on turn 245 of attached savegame after clicking next turn. It crashes while processing barbarian's turn.

_4. Steps to reproduce (optional):_ Load savegame, click next turn.

---------------------------
Supporting information:
1. Log files : [Logs crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2775653/Logs.crash.zip)
2. Save game: 
  - [AutoSave_0243 AD-0980.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2775659/AutoSave_0243.AD-0980.zip)
  - Just click next turn save [aaKamehameha_0245 AD-1000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2775660/aaKamehameha_0245.AD-1000.zip)

3. CvMiniDump.dmp file: 
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2775665/CvMiniDump.zip)

4. Screenshots (optional): none

Edit:
- I removed EUI and uncheck eui compatibility mod and it still crashes.
- Crashes without loading Barbarian Exp mod too.
- I am not sure if this is related, but this was the first time I saw a city of Korea gained independence calling itself colombo city state, and later barbarians captured colombo. I haven't 'met' colombo yet though, since i didn't go near korea after i have explored all that. Barbarian city colombo looks like a puppeted city.
- Again not sure if relevant, but I revealed all with IGE, and kept focus on colombo. After I click next turn, flickering starts on the city, the gold crown encircling it keeps flickering.
![20190119212533_1](https://user-images.githubusercontent.com/9327601/51429079-fe2ed200-1c30-11e9-88fc-edb3997288ac.jpg)

**Comment by TechpriestEnginseer** [comment]
If you're using IGE, how about deleting the barbarian units nearby there.

**Comment by ilteroi** [comment]
well, november version ... may be fixed already?

**Comment by themagicalyang** [comment]
Jan version, not savegame compatible. Actually trying on jan version on the save crashes before even loading the save. So, not sure if the jan version fixes it.

**Comment by ilteroi** [comment]
savegames are not compatible between versions, so the crash on load is expected, not related to the issue at hand.

**Comment by Vyyt02** [comment]
It also would not have hurt had you have tried deactivating RED.

**Comment by themagicalyang** [comment]
> but it says november at the very top?

Yes. Issue is with november version.

> anyway savegames are not compatible between versions, so the crash on load is expected, not related to the issue at hand.

Yes savegames are not compatible, i just mentioned it because you mentioned 'it may be fixed already'.

> It also would not have hurt had you tried deactivating RED.

I can try that. I also have a copy of the previous MODS folder. So just replacing it should work.
