### ISSUE TITLE
[Feature request] New Communitas mapscript 

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#5091]
_1. Mod version (i.e Date - 4/23):_

January 2019
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
JMA2286 has recently updated Communitas mapscript. It fixes fish spawn, improves harsh terrain distribution and increases water/land ratio. It would be nice to deliver this last version of the mapscript.

https://forums.civfanatics.com/threads/guide-map-scripts.637015/page-4#post-15337297

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
So many issues, so little time...

**Comment by ryanmusante** [comment]
https://forums.civfanatics.com/threads/on-communitas-map.648143/

**Comment by tu-79** [comment]
I would wait a little bit. I'm still not happy about horse distribution, and I'd like to know the Community opinion, to make further changes so it suits more tastes.
Let us play the map a couple of weeks at least.
