### ISSUE TITLE
TXT_KEY_EUI_BUILT_IN_X_CITIES On many Building Tooltips

### ISSUE THREAD

**Issue by fampat** [LoneGazebo/Community-Patch-DLL#5092]
**Mod version:_**
1/15

**Error description:_** 
TXT_KEY_EUI_BUILT_IN_X_CITIES on many building tooltips, found out that it get fixed by copying over _C:\Users\NAME\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\EUI\EUI_text_en_us.xml_ to _C:\Users\fampa\Documents\My Games\Sid Meier's Civilization 5\Text_

Since ive used the autoinstaller i suggest this is happening automatically, or at least get documented in the forums (first search result whel looking for this issue) or on the installer itself.

My game ist installed at c:\Steam so no access issues for the installer.

**Comment by LoneGazebo** [comment]
This means that you aren't actually loading (6a).

**Comment by fampat** [comment]
Hi, i was under the impression it works, how can i tell exactly, since ingame it does look to me like it is working, see screens.

![2019-01-20 09_05_16-window](https://user-images.githubusercontent.com/3962513/51436726-df612780-1c92-11e9-8461-959e4627b023.png)
![2019-01-20 09_06_43-window](https://user-images.githubusercontent.com/3962513/51436727-e1c38180-1c92-11e9-9cef-98cef1bc3467.png)

**Comment by fampat** [comment]
i found the issue, had to start a new game after from the mod-menu, then i wonder how this workd from multiplayer... is it maybe bugged in MP?

**Comment by fampat** [comment]
Ok found out all, created an mp modpack, works like a charm, thanks!
