### ISSUE TITLE
Unable to liberate Cities, game breaks after auto-annex

### ISSUE THREAD

**Issue by vand3537** [LoneGazebo/Community-Patch-DLL#5100]
_1. Mod version (i.e Date - 4/23):_
12/2018 & 01/2019

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch EUI

_3. Error description:_ 
Cannot Liberate Cities, they are automatically annexed, and thereafter, the build options are missing from all cities, breaking the game.  Enemy's original cities do not have this issue when being captured.
also, over the course of a war, options become greyed out for peace negations, and Cities disappears from the list entirely, not sure if this is part of the problem or a feature of the Patch

_4. Steps to reproduce (optional):_
Here is the first game, with the December Vox Populi, the save game should load to a unit that can capture a city.  the logs are just from loading up this save game, capturing the city, and shutting down.
[can not liberate.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2783968/can.not.liberate.zip)

After this, I uninstalled and deleted everything, reinstalled Civ V and Installed January Vox Populi and started a new game, the same thing happened.  I'd have to load up the game again to make a proper save, but here is logs from the original play-through, I did not advance the game any turns after the capture of the puppet city
[Logs 2nd game Jan Vox.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2784074/Logs.2nd.game.Jan.Vox.zip)

**Comment by LoneGazebo** [comment]
Lots of

[979.281] Runtime Error: Assets\DLC\UI_bc1\CityBanners\CityBannerManager.lua:272: Instance does not exist.

Is it possible that you had another version of EUI installed before VP, but it wasn't installed before you installed VP?

**Comment by vand3537** [comment]
I installed VP once before, maybe a year ago, pretty sure I used VP installer.  
but if this were the problem, how would I fix it?  I've already uninstalled/deleted everything multiple times.

**Comment by LoneGazebo** [comment]
Not sure, make sure you're running the correct version of EUI and loading (6a)
