### ISSUE TITLE
Increasing Unhappiness from Population

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#5101]
I'm trying to add a bit of extra Unhappiness from Population under certain circumstances (if the city is starving, for instance). I've been trying to use the pre-existing SetYieldFromHealth that you created, which allows adding and subtracting Local Happiness, but this creates some problems in the total happiness calculation. So I was just wondering if a **city:SetExtraUnhappinessFromPopulation()** or something of the kind might be possible. 

Of course, Happiness and Unhappiness in particular are notorious on the Lua and Database sides for being finicky and inflexible to mod, so I completely understand if such a thing is the same on the DLL-side or even if it would be just too complicated. I thought I'd ask nonetheless.  Thank.

**Comment by LoneGazebo** [comment]
Happiness from starvation is already a thing in VP, I could see if it's possible to 'unlock' that functionality so you could use just that part of the VP happiness overhaul.

**Comment by JFDaly** [comment]
Hm, its not the sole thing - I was intending to increase it based on if the city is Plagued, in Resistance, and being Razed as well.

**Comment by LoneGazebo** [comment]
Hmm...you'd run into a performance bottleneck if editing/checking it constantly via a LUA function, as happiness checks occur very frequently.

**Comment by LoneGazebo** [comment]
Possible to use the events system, maybe? I know I added the ability to alter happiness that way.

**Comment by JFDaly** [comment]
Events alter Happiness yeah. But it nets the same awkwardness with the UI - events, as well as the SetYieldFromHealth function, adds or subtracts Happiness, rather than adds Unhappiness, which means the UI ends up a bit finicky if I try to manipulate it to seem like its coming from Unhappiness. No matter, I can figure a way to work with the Local Happiness subtraction instead. Thanks anyway.

**Comment by LoneGazebo** [comment]
I could add an event criterion that adds unhappiness (instead of adding/removing happiness) if that'd help.

**Comment by JFDaly** [comment]
It wouldn't, no. I still need the flexibility of Lua, since the Unhappiness is based on Population (times .25). So I'd need a direct method of increasing Unhappiness (or Unhappiness from Pop.) for things to run smoothly - but if that's too much for the game to process, I'll use what's on hand instead.

**Comment by LoneGazebo** [comment]
Gotcha - yeah, it'd get taxing.

**Comment by TechpriestEnginseer** [comment]
Don't Happiness Dummy buildings just stack?

**Comment by JFDaly** [comment]
Buildings don't yield Unhappiness, so dummy buildings aren't useable in this case. 

@LoneGazebo Back to your earlier offer, Unhappiness from Starving Population would be great, if that can be made accessible to the CP. Not sure if I can switch on the 'MOD_BALANCE_CORE_HAPPINESS' option without inadvertantly overhauling Happiness :p

**Comment by LoneGazebo** [comment]
Unhappy per pop isn’t a float. I’d have to float it. It’d be easier to simply add a secondary float to it, probably. Could also put a lua hook there for you to artificially add unhappiness to pop.

**Comment by JFDaly** [comment]
Ah, gotcha. Well, the dummy policy works fine, so no worries about that. But a lua hook would be useful - would that be easier than trying to make the other three defines accessible?

**Comment by LoneGazebo** [comment]
I'd need to look at the code. WIll report back.

**Comment by JFDaly** [comment]
Awesome, thanks. Ofc, no rush.

**Comment by LoneGazebo** [comment]
Okay, sorry about the delay on this, I think I've got something for you.

**Comment by JFDaly** [comment]
Cool, looking forward to it.

**Comment by LoneGazebo** [comment]
Alright, this is a debug CP, so bear with the speed.

There's now a UNHAPPINESS_PER_POPULATION_FLOAT, which is added to the existing UNHAPPINESS_PER_POPULATION in all instances in the DLL where it appears (it defaults to zero). UNHAPPINESS_PER_POPULATION_FLOAT is also used in the UI in some places, so you'll need to update that wherever you encounter it for your purposes.

There's also a player:GetUnhappinessFromCityJFDSpecial(), which gets 4 sources of unhappiness:
- Starving
- Pillaged
- Connection
- Specialists

You can use the CBO lua UI functions and defines for these.

Should be all you need.

[(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2826693/1.Community.Patch.zip)

**Comment by JFDaly** [comment]
Great, thanks. I will test it out and get back to you.

**Comment by LoneGazebo** [comment]
Awesome. A rare swing and a hit for me with custom, untested code. :)

**Comment by JFDaly** [comment]
Oh, well scratch that - I forgot to test the GetUnhappinessFromCityJFDSpecial() method, which doesn't seem to be working (nil method error, so maybe just wasn't pushed to lua?).

I also discovered that the different methods aren't additive - if I have a city that has no city connection, it correctly has (for e.g.) 1 Unhappiness. But then if that city starts starving, it no longer produces unhappiness from a lack of city connection - only from starvation. The same is true of pillaged tiles as well, but not of Specialists which applies normally.

**Comment by LoneGazebo** [comment]
sorry, the function is: GetUnhappinessFromJFDSpecial()

Right now the model is set up as additive, so that you can't have more unhappiness from a source than the number of city citizens. I can change that if you'd like.

**Comment by JFDaly** [comment]
Oh, right. Yeah, additive would be better, since its a bit confusing to communicate to the player otherwise.

**Comment by LoneGazebo** [comment]
Change it such that there can be more than one source from each citizen? Specialists are treated separately as it's treated as an 'unhappiness tax.' What order of priority do you want?

```
int iLimit = getPopulation();
	int iContribution;
	iContribution = getUnhappinessFromStarvingRaw(iLimit);
	iLimit -= iContribution;
	iContribution = getUnhappinessFromPillagedRaw(iLimit);
	iLimit -= iContribution;
	iContribution = getUnhappinessFromConnectionRaw(iLimit);

	return iContribution;
```

**Comment by LoneGazebo** [comment]
That's the current order

**Comment by JFDaly** [comment]
Is it possible to make it additive? So that a city gets unhappiness from Starving, from Pillaged Tiles, and from no City Connection if all those connections are met? Otherwise that order makes the most sense.

**Comment by LoneGazebo** [comment]
i.e. remove the 'limit' above? Sure, I can just remove the 'iLimit -= iContribution;' line, and let you control the values yourself.

**Comment by JFDaly** [comment]
Yeah, that'd be a great help.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2833921/CvGameCore_Expansion2.zip)

**Comment by LoneGazebo** [comment]
order up!

**Comment by JFDaly** [comment]
Hm, still have the same issue.

**Comment by LoneGazebo** [comment]
Weird, the check was removed, default is INT_MAX. Just how big are these cities? :)

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2834012/CvGameCore_Expansion2.zip)

Same file, reuploading to make sure it updated.

**Comment by JFDaly** [comment]
Hm, weird indeed. Seen below, still the same issue - both Pillaged Tile and City Connection unhappiness only show when the city has 2 Population.

![Alt Text](https://i.imgur.com/YRnJai4.jpg)

![Alt Text](https://i.imgur.com/axcMgnv.jpg)

**Comment by LoneGazebo** [comment]
ahhh, i know the issue, the UI functions for those (for the CBO) default to city pop. Silly me.

**Comment by LoneGazebo** [comment]
I had assumed you'd lump them all in using the 'special' function that I'd made- of course you'd want access to the CBO UI functions as well, duh. Fixed, maybe: 
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2834070/CvGameCore_Expansion2.zip)

**Comment by JFDaly** [comment]
That does it, thanks for the quick help

**Comment by LoneGazebo** [comment]
There we go! 💃
