### ISSUE TITLE
Trade Route Issue (cannot form any routes)

### ISSUE THREAD

**Issue by Frite200** [LoneGazebo/Community-Patch-DLL#5103]
_1. Mod version (i.e Date - 4/23):_
1/23/19 up to date. 4.1.15.2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Cannot form trade routes. looking under the available traderoutes tab I see something quite strange. refer to screenshots

_4. Steps to reproduce (optional):_
It seems that all trade routes will not work, simply build a caravan and try to trade.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

won't accept file type.

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

also won't accept file type.

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![screenshot 1](https://user-images.githubusercontent.com/46980109/51644631-02f3ce80-1f2e-11e9-85be-1c1ca638b136.png)
![screenshot 2](https://user-images.githubusercontent.com/46980109/51644632-02f3ce80-1f2e-11e9-85ec-18511bf0bf7f.png)

**Comment by MoiMagnus** [comment]
> also won't accept file type.

You need to put your files in a .zip

**Comment by wildmercury** [comment]
I've got the same issue, and I've tried verifying local files etc - issue remains. 
There was no crash, so no dmp file, but attached a savegame and some logs for you.
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2791801/logs.zip)
[Theodora_0251 BC-0990.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2791805/Theodora_0251.BC-0990.zip)

**Comment by wildmercury** [comment]
Ok, this issue seems to arise if the users \My Games\Sid Meier's Civilization 5\MODS folder has not been cleared before upgrading.
user workaround: delete everything in that folder and reinstall mods

**Comment by Vyyt02** [comment]
Actually, this may not be enough. The important thing is to make sure that you are not subscribed to a Steam version of any VP components such as More Luxuries or Community Patch.

So first unsubscribe from any VP relate mod, then delete the mods from the MODs folder (or just delete everything if you want to make sure) and then run the autoinstaller again.
