### ISSUE TITLE
MP issue: AI turn skipped when loading

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#5104]
_1. Mod version (i.e Date - 4/23):_
2019/01/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Reverse bug from #2576, and #4166 (both have been fixed). Possibly linked to #5024. The humans get to play twice when loading a MP game. Reported here: https://forums.civfanatics.com/threads/dlc-modpack-and-43-civ-version-repository.609278/page-33#post-15342890

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
You have to save the game twice. It’s the only solution I know of.

**Comment by azum4roll** [comment]
Doesn't that corrupt the save?

**Comment by TechpriestEnginseer** [comment]
[AutoSaveFix_v1.0.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2794487/AutoSaveFix_v1.0.zip)
Try this mod.

**Comment by MoiMagnus** [comment]
So, after some test with the last version:

+ Double save does not change anything. It used to solve "the player's turn is skipped", but do not solve "the AI turn is skipped".
+The saves generated by Enginseer's mod are GOOD, and works correctly. (Though it does not fixes the manual saves, they are still broken even, you have to use the saves automatically generated)

Note that I tested this in a "one player multiplayer game", so it isn't 100% sure that it works for more people, but it look promising.

**Comment by TechpriestEnginseer** [comment]
Awesome, the save works then.
