### ISSUE TITLE
(E)UI issues with movement "estimation" ep. 1 Forts and Tanks

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5106]
_**1. Mod version** (i.e Date - 4/23):_
11-30-18

_**2. Mod list** (if using Vox Populi only, leave blank):_

VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

_**3. Error description**:_
I've collected some UI quirks which may or may not be connected to EUI and may or may not be connected to each other. This is the first one:

In the screenshots below you'll see how I attempt to move a tank from one continent to another. The UI shows me that I can use the intact enemy Fort to embark without spending all movement points and thus disembark onto the other, adjacent continent in the same turn.
Once I execute this action, however, my unit stops moving after embarking and has no more movement points left. I assume that this is because enemy Forts don't actually allow my units to embark with only one movement point but apparently the (E)UI didn't get that memo.

_**4. Steps to reproduce** (optional):_
1. Go to war with a civ that has forts on the coast and move mounted units onto that continent
2. Attempt to embark from that fort and notice how the UI will act as if embarking from the enemy fort only costs 1 movement point, while in reality it consumes all movement points.

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![tank_embarked_mov_before](https://user-images.githubusercontent.com/30495439/51750164-1d9e8280-20a9-11e9-9c7b-f57b17930a76.jpg)
![tank_embarked_mov_after](https://user-images.githubusercontent.com/30495439/51750182-268f5400-20a9-11e9-99dc-b561eadac471.jpg)

**Comment by UndeadDevel** [comment]
The fort isn't adjacent to any enemy units, though, so that shouldn't slow the movement; the only move relevant to ZoC would be the very last one in the first screenshot (planned moves), which would have landed the tank on land; the unit didn't carry out that move, though, even though it should have had movement points left.

So I think it's the Fort that did this since Forts usually allow embarkation without depleting all movement points but I guess enemy forts don't and the pathfinder doesn't know about that.

**Comment by ilteroi** [comment]
i'll check

**Comment by UndeadDevel** [comment]
more evidence (I hope the "spoiler-formatting" works):

<details> 
  <summary>another similar case</summary>
   <p>tank moving from water to enemy fort and back down again, but has UI mismatch with embarkation again</p> 
![tank1](https://user-images.githubusercontent.com/30495439/51760564-9bbb5300-20c2-11e9-8d68-ce715afe85c0.jpg)
![tank2](https://user-images.githubusercontent.com/30495439/51760581-a83fab80-20c2-11e9-8922-52acd470335b.jpg)
</details>

<details> 
  <summary>showcasing a slightly different case</summary>
   <p>tank moving from water to enemy fort and back down again, but has UI mismatch with embarkation again; this time not near city and no further disembarkation planned</p> 
![tank3](https://user-images.githubusercontent.com/30495439/51760595-b097e680-20c2-11e9-9882-e156cc234ead.jpg)
![tank4](https://user-images.githubusercontent.com/30495439/51760611-b7bef480-20c2-11e9-8a26-632dc530e18c.jpg)
</details>

<details> 
  <summary>additional info</summary>
   <p>tank has just disembarked to enemy Fort and has 5 movement points left; embarking from pillaged Citadel correctly shows that all movement points would be expended</p> 
![tank6](https://user-images.githubusercontent.com/30495439/51760642-c60d1080-20c2-11e9-9dca-a259a78039f5.jpg)
</details>

**Comment by ilteroi** [comment]
fixed, but there are side effects. ships now cannot enter enemy forts anymore. but i guess it's better that way.
