### ISSUE TITLE
(E)UI issues ep. 3 Bombers and Destroyers

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5108]
_**1. Mod version** (i.e Date - 4/23):_
11-30-18

_**2. Mod list** (if using Vox Populi only, leave blank):_

VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

_**3. Error description**:_
I've collected some UI quirks which may or may not be connected to EUI and may or may not be connected to each other. This is the third one and is substantially different from the other two:

It concerns Bombers that are stationed in one of my cities and actually fail to attack unit they should be able to attack. In the first screenshot you'll see a Bomber in my city (has the Range promotion) that can and will attack the enemy landship; in the same screenshot you'll see an enemy Destroyer to the north west, which has very low health and is seemingly within attack range of the Bomber as well. However, the Bomber for some reason cannot attack the Destroyer, only the Landship; when mousing over the Destroyer in Strike mode there is no arrow show (see second screenshot). In the third screenshot you'll see a similar situation where another Destroyer and another Landship are in range, but this time the Landship is at max distance and the Destroyer is closer; the Bomber still can't attack the Destroyer, only the Landship.

I have not been able to test this with Triplanes yet, though Triplanes have certainly successfully attacked embarked units in my game and I'm pretty sure I've been able to attack naval units with Bombers as well, but I'll update this post once I confirm that; hopefully I'll be able to discern some sort of pattern.

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![bomber_can_attack_landship](https://user-images.githubusercontent.com/30495439/51751507-f053d380-20ac-11e9-89da-b93a67579c7a.jpg)
![bomber_cant_attack_destroyer](https://user-images.githubusercontent.com/30495439/51751556-05306700-20ad-11e9-9b8a-b872f996847c.jpg)
![bomber_cant_attack_naval](https://user-images.githubusercontent.com/30495439/51751600-22653580-20ad-11e9-9a77-4b4b1a06abd2.jpg)

**Comment by Vyyt02** [comment]
Wasn't there a bug about air units unable to finish off the ships low on health if they had the promotion increasing their HP? Could this be related?

**Comment by UndeadDevel** [comment]
Right. On. The. Money. :moneybag: :smile: 
<details> 
  <summary>Check it out</summary>
   <p>Bomber can attack the full HP destroyer with the Boarding Party promo line but not the low HP destroyer with the Dreadnought promo line.</p> 
<img src="https://user-images.githubusercontent.com/30495439/51768469-543fc180-20d8-11e9-9809-c104758cba66.jpg">
<img src="https://user-images.githubusercontent.com/30495439/51768479-5b66cf80-20d8-11e9-9e4c-4a060150ebad.jpg">
</details>
It was brought up before in issue #4789 and marked as "Cannot reproduce".

**Comment by LoneGazebo** [comment]
That would only be an issue if there were situations in the DLL where GC.getMAX_HIT_POINTS() was being used instead of unit:GetMaxHitPoints()... @ilteroi ?

**Comment by ilteroi** [comment]
well there are 73 instances of getMAX_HIT_POINTS in the code, and about 70 of them are not strictly correct ...

anyway i still can't reproduce this one.

**Comment by MJWedding** [comment]
I just want to add that it occurs with other types of units with >100 maxHP as well.  In my current game I play with Magnus Mutatio Modpack including Unique City States. One of the buffs offered there is +25HP for siege units. I cannot target enemy field guns that are 25/125 or lower with my triplanes/bombers, no problems when targeting with artillery or city bombardment.

**Comment by UndeadDevel** [comment]
Another piece of the puzzle: this happens with missiles as well (firing missiles at >100 maxHP units that have taken >100 damage isn't possible).
