### ISSUE TITLE
City-State influence doesn't increase after a marriage

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#511]
![8930_2015-08-11_00005](https://cloud.githubusercontent.com/assets/1131228/9192377/056f81c8-4024-11e5-9e40-b52890a33c82.png)

**Comment by LoneGazebo** [comment]
Doesn't recover from negative, you mean? I guess that makes sense given how I coded it, but yeah, that's not how it is supposed to work. I'll fixed.

**Comment by Radost** [comment]
Not from negative, but it doesn't increase to the resting point.

**Comment by LoneGazebo** [comment]
Yeah, that's what I meant. We're on the same page. Was simply an oversight on my part.
