### ISSUE TITLE
detect bad mod config?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5111]
considering the amount of problems people have with incorrectly installed mods (cp from steam, wrong eui version, etc), do you think it would be possible to detect this when starting a game and show a hint to the user? that would really cut down on the complaints ...

**Comment by LoneGazebo** [comment]
haha, yeah - I did add the 'not compatible with Smart AI et. al.' check last version...

**Comment by JFDaly** [comment]
This would be possible with incompatibilities that are more subtle - that is, ones that don't throw you back to the main menu but let you get into the game as normal. It would just be a UI popup at game start warning the player that they've enabled an incompatible mod, and would list them, recommending they disable them. I could code this up, if it'd help?

**Comment by TechpriestEnginseer** [comment]
detecting an incorrect eui version tho...

and we could close the community patch from steam until further notice(since it's not getting an update)

**Comment by ilteroi** [comment]
@JFDaly : i think that would help a lot for the typical "my UI is broken" issues

**Comment by LoneGazebo** [comment]
@jfdaly, that’s a solid idea. If it isn’t too much work it might make all of our lives easier. :)

**Comment by JFDaly** [comment]
Cool, I'll get on that today.

**Comment by LoneGazebo** [comment]
This is rad. You're a LUA wizard.

**Comment by MoiMagnus** [comment]
Does it detect the infamous mod manager bug? 

E.g:
When peoples subscribe to "More Luxuries" on steam, they end up with 2 copies of more luxuries in their mod folder, but the mod manager only show one of them, and they can successfully enable the mods of VP, but at the end, their install is broken (for example: no luxuries generated).

(Similar problem if they subscribed to the community patch on steam.)

**Comment by MoiMagnus** [comment]
Could a different version number also work?

**Comment by JFDaly** [comment]
Would, but I'm not sure you can change the version number of you don't have access to the project files. But the system I've setup here will allow you to specify a version - so just make it greater than whatever the last public version Barathor's is at.
