### ISSUE TITLE
No indication of fortify command, unit flag/sound no change

### ISSUE THREAD

**Issue by Mandritti** [LoneGazebo/Community-Patch-DLL#5114]
_1. Mod version (i.e Date - 4/23):_
January-15

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP no EUI (from automatic installer)
Enlightenment Era for VP (by Infixo)

_3. Error description:_ 
Clicking a unit to Fortify, Fortify until Heal, or Alert, does not visually adopt the fortified icon, nor make the unit grunt.  However, as the turn ends, the unit will fortify correctly.

_4. Steps to reproduce (optional):_
Take save for turn 13 and locate Warrior unit 2-left of Istanbul.  Tell it to Fortify until Heal.  End the turn.
(Tell unit to move 1-right into territory on turn 12)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[bugsaves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2799550/bugsaves.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
This is intended - the decision does not fire until you’ve ended your turn.
