### ISSUE TITLE
CITY_EVENT_MIN_DURATION_BETWEEN

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#5115]
```	
<Defines>
		<!-- Minimum amount of time between any two events for Players/Cities. Scales with Gamespeed. Does not affect counters (i.e. cooldowns will still reduce),
			but prevents events from firing during this time. If you set IgnoresGlobalCooldown true for an event, it will ignore this. -->
		<Row Name="EVENT_MIN_DURATION_BETWEEN">
			<Value>10</Value>
		</Row>
	</Defines>
```
The Event Development Team believes this is the root of all evil and request a CITY_EVENT_MIN_DURATION_BETWEEN defaulting at 25. City Events will fire less, while player events still fire between normally.

**Comment by LoneGazebo** [comment]
Done. But I have a request in return. WTH am I doing wrong with this LUA? Got the EUI corporation tab setup for buildings no sweat, but for some reason no-EUI is giving me grief...


[LUA.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2799834/LUA.zip)

Drop these in a No-EUI (6b) and see what I mean - every building ends up in the Corporations tab in the city view screen.

@JFDaly also calling on you for this. Maybe I'm just sleepy...

**Comment by TechpriestEnginseer** [comment]
Preliminary checks, but
````
		  <Button Anchor="L,C" Size="254,27" Offset="2,0" Texture="CivilopediaButtons272x27.dds" ID="CorporationsHeader">
				<Label Anchor="L,C" Offset="12,-2" Font="TwCenMT18" ColorSet="Beige_Black_Alpha" FontStyle="Shadow" ID="CorporationsHeaderLabel"/>
		  </Button>
          <Button Anchor="L,C" Size="254,27" Offset="2,0" Texture="CivilopediaButtons272x27.dds" ID="BuildingsHeader">
            <Label Anchor="L,C" Offset="12,-2" Font="TwCenMT18" ColorSet="Beige_Black_Alpha" FontStyle="Shadow" ID="BuildingsHeaderLabel"/>
          </Button>
````
CorporationsHeaderLabel and BuildingsHeaderLabel looks the same...

Further elaborations... will be edited in.

**Comment by JFDaly** [comment]
XML values should return as booleans in Lua when declared as booleans in the XML. The IsCorporation column isn't being registered as a boolean because the declaration is case sensitive and instead its being passed as an integer. Enginseer's fix works because of this, but not because this is inherently normal. Instead, you should change this in CoreTableEntries:

ALTER TABLE Buildings ADD COLUMN 'IsCorporation' BOOLEAN DEFAULT 0;

to

ALTER TABLE Buildings ADD COLUMN 'IsCorporation' boolean DEFAULT 0;

**Comment by LoneGazebo** [comment]
Bizarre. I swear I tried the ==1 thing (as that’s what I did for EUI) and it wasn’t working. That’s what I get for working at 2am...

Thanks you two!

**Comment by TechpriestEnginseer** [comment]
````
<Defines>
		<!-- Minimum amount of time between any two events for Players/Cities. Scales with Gamespeed. Does not affect counters (i.e. cooldowns will still reduce),
			but prevents events from firing during this time. If you set IgnoresGlobalCooldown true for an event, it will ignore this. -->
		<Row Name="EVENT_MIN_DURATION_BETWEEN">
			<Value>25</Value>
		</Row>
	</Defines>
````
I believe the proposal was misinterpreted.

**Comment by LoneGazebo** [comment]
Uh oh
