### ISSUE TITLE
Apostolic Palace

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#512]
I have a game with 20 CSes. I have the Apostolic Palace and The Forbidden Palace world wonders and 23 cities are following my religion. But I get only +4 votes from world wonders.

I think that there is something wrong with this +1 vote / 6 cities following your religion in Apostolic Palace.

**Comment by Radost** [comment]
Founder NW bonuses are shown as "religious authority".

**Comment by Finarvi** [comment]
I don't see such thing. Maybe something overlaps with another bonus? I have plenty of +1 vote per X CS in game, X civ following my religion, X cities following my religion and so on (going for diplo victory).

**Comment by LoneGazebo** [comment]
It works, just tested it.
G

**Comment by Finarvi** [comment]
And how is it named in WC screen?

**Comment by Edaka** [comment]
Can confirm on having the same issue. I've had it once playing as the pre-patch Celts, but shook it off then. Just tested with the IGE:
The first screenshot depicts additional delegates from the Great Altar (I hope that's what it's called):
![congress1](https://cloud.githubusercontent.com/assets/12978597/9264931/f06d86c2-4234-11e5-840b-374b6c46a6d5.jpg)
The second one depicts no delegates from the Apostolic Palace. I had about 20 cities converted to my religion:
![congress2](https://cloud.githubusercontent.com/assets/12978597/9264932/f27c0948-4234-11e5-831d-dd045fb4d9af.jpg)

**Comment by LoneGazebo** [comment]
Ah, I see what you are saying now – the Apostolic Palace is specifically malfunctioning, not the underlying code. Gotcha. I'll look, is probably just an XML/SQL error.

**Comment by LoneGazebo** [comment]
Yep, Apostolic Palace was simply left out. Fixed!
