### ISSUE TITLE
CTD if I try to start with more than 37 civs - Vox Populi 43Civ

### ISSUE THREAD

**Issue by Dreifels** [LoneGazebo/Community-Patch-DLL#5122]
Vox Populi v89 complete Non-EUI-Version + Language pack 12-18-1 + Ingame Editor

New game, new installation.  I start extended setup, choose somethingbetween 43 and 37 Civs (all random, except my own), set to 18 minor civs
(as I got told "as long as below 43 civs and 20 minors it should work")
click start, configuration running for ~ 30-40 sec, then I get CTD

Tested with 43, 42, 41, 40, 39, 38 civs. It's always same.
When I set to 37 civs, it works  

[00000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2802895/00000.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2802901/CvMiniDump.zip)

**Comment by LoneGazebo** [comment]
Probably an out of memory issue.
