### ISSUE TITLE
Broken Top Right Panel

### ISSUE THREAD

**Issue by MRS-OBAMA** [LoneGazebo/Community-Patch-DLL#5125]
_1. Mod version (i.e Date - 4/23):_
Community Patch (v 89) 29/01/19 DD/MM/YY 

_2. Mod list (if using Vox Populi only, leave blank):_
CP (v 89)
EUI (CP version) 
Really Advanced Setup
Enlightenment Era
Doom Guy (not sure if unit mods like this might have a say in it, doubt so)
Disable Obsoletion
Civ Advanced
Quick turns
Promotions - Expansion pack
Ingame editor (v39, tried without with no change on new savegame) 
Global - City State Airbases
Improvement - Airbases (Infixo version, or the one which is compatible with CP)
Promotion Flags EUI (tried without, didnt see change)
Infoaddict which i found to crash extremely often when used in conjunction with EUI, even with the compatibility patch, although i have tried without and  i still can't use the top right panel 
Global - City Works 5 Tiles
New Buildings
Religion - beliefs Expansion Pack
Quick Turns
Units - Tough Nuts (i changed this one a bit to integrate partly in Promotions - Expansion Pack)
Custom Game Speed i made for myself (no UI or Lua) 
Wonder Race 
(anyone know how to copy your modlist? i had to write by hand each mod) 
All mods should be latest version, most are from workshop.
_3. Error description:_ 
Top right panel not working, shows only diplomacy button, which doesnt work. I have tried removing mods but they crash my savegame if i remove any. I've googled on civfanatics and searched on here but the only issue like mine shown mentioned additional Civilizations or JFD Mods, which i haven't installed, only Enlightenment Era.  

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 

[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2809604/Lua.log)
this is a new world, i created it and spammed the diplomacy button, with no result, i wouldn't even mind if i had to access the menus with f4 but i need to check infoaddict and wonder race too
4. Screenshots (optional):
how it looks in game:
![screenshot_147](https://user-images.githubusercontent.com/47156346/51939308-70f93380-240f-11e9-9e56-db7c488a07c5.png)

**Comment by LoneGazebo** [comment]
That's a lot of other mods, but my best bet would be for you to delete the LUA folder in the (1) Community Patch.

**Comment by MRS-OBAMA** [comment]
> 
> 
> That's a lot of other mods, but my best bet would be for you to delete the LUA folder in the (1) Community Patch.

Fixed, thanks for the quick reply
