### ISSUE TITLE
1-29 Acropolis granting wide yields to all owned cities

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#5126]
I only own 1 acropolis. Upon killing an enemy unit every city I own gets the border growth bonus, even if there's no acropolis there. Probably worth check the new Colosseum as well.

**Comment by LoneGazebo** [comment]
Weird. I wonder if it was my last optimization that caused it. Hmm...

**Comment by RandomNub** [comment]
The culture on kill works fine. Upon building a second acropolis though, the border growth bonus is doubled for all cities. Btw, nice touch with the new blurple icon.
