### ISSUE TITLE
CTD when creating a game with multiple of the same civ

### ISSUE THREAD

**Issue by HalfEmptyMug** [LoneGazebo/Community-Patch-DLL#5127]
_Mod version (i.e Date - 4/23):_
1-29 w/EUI (also present with 1-15)

_Error description:_ 
When starting a game with multiple of the same civ (such as 20 Enrico Dandolos or Moroccos), the game consistently CTDs before loading the map with around 10 or more of the same civ. Amount of active city states doesn't seem to change this.

The lua log breaks when loading "DiploTrade: This is the modded TradeLogic from CBP- C4DF" so it could be a trade logic issue?

This isn't exactly a normal use case, but I figured it's worth bringing up.

_Steps to reproduce:_
When starting a new game, assign all civ slots to the same civ. The game will consistently crash with 22 civs, but it was hit or miss for me around 10 or so.

---------------------------
Logs and minidump: 
[VoxCloneBug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2810241/VoxCloneBug.zip)

**Comment by LoneGazebo** [comment]
I see a crash, but it crashes outside of the DLL, so I can't fix it. Weird bug, probably vanilla.
