### ISSUE TITLE
AI doesn't pillage hostile citadels

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#513]
![8930_2015-08-12_00006](https://cloud.githubusercontent.com/assets/1131228/9224231/52ffd662-411a-11e5-9cdd-97b0068a7ad1.png)

**Comment by LoneGazebo** [comment]
The AI will only pillage when it wants to damage a city rather than capture it.

**Comment by Radost** [comment]
It won't capture a city if it doesn't pillage a citadel.
It can repair after the capture anyway, because units >>>>> improvements.

**Comment by LoneGazebo** [comment]
I understand that, but the AI's war-stance has set stages it operates through. Force-coding pillage calls is risky.
