### ISSUE TITLE
Large Vassal malus for protection of lands without any conquest or major damage

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5132]
_**1. Mod version** (i.e Date - 4/23):_
11-30-18

_**2. Mod list** (if using Vox Populi only, leave blank):_

VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

_**3. Error description**:_
As you can see in the screenshots below, my new vassal Russia is complaining that I'm not protecting her lands well enough, and is giving me a -33 modifier despite only being my vassal for 3 turns. In the meantime there has been a bugged DOW from Denmark on Russia, which peaced out on the same turn (this has been reported already...hopefully fixed in the newest version), but Denmark did not conquer anything of Russia's in that one turn, of course. I am still razing one of Russia's cities, however, that I took and started razing during the preceding war, which ended with her Capitulation (in case that matters).

So without any major damage or conquest of her cities during her (hitherto) short vassalage, her lands protection modifier is -33...gotta be a bug. For comparison: Portugal has been my vassal for almost 200 turns and has a -50 lands protection modifier with me, which I earned by letting Denmark capture 5 of her cities (some of them I recaptured several times...it was a crazy war).

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![vassal_problems](https://user-images.githubusercontent.com/30495439/52029366-d2ea9380-250a-11e9-9bd8-edad17b739e7.jpg)

**Comment by TechpriestEnginseer** [comment]
If her cities are damaged, she'll think it's also you failed to protect her lands.

**Comment by UndeadDevel** [comment]
Those of her cities I didn't take were barely damaged, though; shouldn't there be a mechanism that checks what the damage level of her cities is when she enters the vassalage, such that only new damage after entering the vassalage increases the Protection malus?

**Comment by LoneGazebo** [comment]
@undeadlevel no easy way to do that, no.
