### ISSUE TITLE
AI not building Ideology-specific World Wonder

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5133]
_**1. Mod version** (i.e Date - 4/23):_
11-30-18

_**2. Mod list** (if using Vox Populi only, leave blank):_

VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

_**3. Error description**:_
In my current game the AI is, for some reason, not prioritizing ideology-specific World Wonders at all. They have been very competitive regarding the other types of World Wonders, including ones specific to Social Policy Trees. I got Statue of Liberty for my Freedom despite not being the first to reach the Tech with the Ideology but I thought I was just really lucky in that case. Now, however, Denmark, the only Order civ, is refusing to build Motherland Calls, despite having the tech for many many turns (> 30 turns) and even having built a later wonder (Pentagon) in the meantime. 
Motherland Calls is a great wonder so there should be no reason to delay building it (Denmark wasn't the only Order civ, either; up until about 10 turns ago there was Polynesia, who also took Order, but converted to Freedom once I vassalized them.

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![ideology1](https://user-images.githubusercontent.com/30495439/52029729-70929280-250c-11e9-8926-42430986fa41.jpg)
![ideology2](https://user-images.githubusercontent.com/30495439/52029734-78eacd80-250c-11e9-92e5-f11cd32c9d62.jpg)

**Comment by LoneGazebo** [comment]
I'd need logs.

**Comment by UndeadDevel** [comment]
Hmm I turned on logging in that game at some point but I seem to have turned it off again before this period in the game. I'll try to keep logs running for my next game.

**Comment by ryanmusante** [comment]
Is the overhead for logging negligible? I disable for games sometimes for performance boost. Is it placebo effect?
