### ISSUE TITLE
2for1: AI paying me to win; vassals offering to vote for me despite having to

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5134]
_**1. Mod version** (i.e Date - 4/23):_
11-30-18

_**2. Mod list** (if using Vox Populi only, leave blank):_

VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

_**3. Error description**:_
See screenshots. AI (non-vassal) paying me to vote for myself for the Diplomatic win and a vassal of mine offering to vote for me despite him having to anyway; the latter case only works when I offer to vote for myself (otherwise it will say "Impossible").

While there may be a rare scenario where me voting for myself could be beneficial for the AI, this is definitely not the case when I have enough Delegates to actually win the game.

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![hegenmony_weirdness](https://user-images.githubusercontent.com/30495439/52037322-96c52c00-2526-11e9-9dd4-1b16fbf9654a.jpg)
![hegenmony_weirdness2](https://user-images.githubusercontent.com/30495439/52037329-9b89e000-2526-11e9-928d-7f69284f41a2.jpg)

**Comment by LoneGazebo** [comment]
Maybe they really like you?

**Comment by LoneGazebo** [comment]
There’s actually a hard check against selling or buying votes for world leader. Any mod conflicts?

**Comment by UndeadDevel** [comment]
Can you tell me in what file? I could check against that; otherwise none of the non-VP mods are _supposed_ to interfere with diplomacy or non-TR trade.

**Comment by LoneGazebo** [comment]
Well it’s a DLL element. Probably not a conflict but I can’t imagine how the AI is getting around the hard check. I’ll look.

**Comment by LoneGazebo** [comment]
Checked the code, there's definitely a hard check against what happened above. Not sure.

**Comment by UndeadDevel** [comment]
Hmm...well I guess I'll let you know if it happens again then.
