### ISSUE TITLE
Air bombard battle preview window missing

### ISSUE THREAD

**Issue by yyEdge** [LoneGazebo/Community-Patch-DLL#5135]
_1. Mod version (i.e Date - 4/23):_
29 Jan 2019 with hotfix

_2. Mod list (if using Vox Populi only, leave blank):_
Screenshot game uses a ton of other mods, but result is the same when tested with clean VP (1+6) + IGE

_3. Error description:_ 
No battle preview window for air bombardment, the unit still attacks fine tho
Tested with an earlier version of VP (jan 15/16) the window is still there.

_4. Steps to reproduce (optional):_
Any air bombardment will do
![unknown](https://user-images.githubusercontent.com/43651250/52046777-8478db80-2582-11e9-9fa6-3a7946b1dcc3.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi I’ll leabe this to you. :)

**Comment by ilteroi** [comment]
turns out air units are not considered as combat units ... fixed

**Comment by LoneGazebo** [comment]
well that's funny.
