### ISSUE TITLE
Getting Barbs and Revolt Warnings - Even though Happy

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5136]
_1. Mod version (i.e Date - 4/23):_
1-29

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I just got 2 barbs in my area, and the "your in danger of a revolt warning". But as you can see in the screenshot, I am currently happy. I have also looked at the happy tooltip, and inside the math matches the 13 happy I have.

So either the UI is wrong, or unhappy issues are occurring when I'm happy.

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/52102435-09c1b780-25a6-11e9-901c-93e315c85e8d.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
I believe it's a delay, the unhappiness spike hits when your population grows but then your city governor immediately adopts and put them to use and your happiness goes up again.
