### ISSUE TITLE
Quarry can not be built on Amber (possibly also Jade and Lapis)

### ISSUE THREAD

**Issue by dylansan** [LoneGazebo/Community-Patch-DLL#5137]
_1. Mod version (i.e Date - 4/23):_
1/15/2019

_2. Mod list (if using Vox Populi only, leave blank):_
VP with EUI
RCI 2.0 (DLC mod)
Promotion Flags (EUI) (v1.1)

_3. Error description:_ 
There is an amber resource two tiles from my city, within my borders. I have unlocked the tech to build quarries (Construction), but when I send a worker to build one, it is not an option. I have the techs to clear marshes and chop forests and jungles, though none of those are present on the tile. No other units are present on the tile.

When hovering over the tile, the tooltip does not show quarry as a potential improvement, as it might on resources when a technology is required. The Civilopedia shows that quarries will improve the expected resources: Uranium, Stone, Marble, and luxuries like Amber, Jade, and Lapis. However, when in the tech tree, hovering over quarries in the Construction tech, the tooltip says it improves those resources, but only says it can be built on Uranium, Stone, and Marble.

_4. Steps to reproduce (optional):_

- Found a city within working range of Amber
- Unlock contruction tech (and any others required to clear marsh, jungle, or forest if necessary)
- Move worker to Amber and attempt to build quarry

No option to build a quarry is available

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2823833/Logs.zip)

2. Save game:
[034_VP_Pedro II_0186.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2823831/034_VP_Pedro.II_0186.zip)

3. CvMiniDump.dmp file:
No crash

4. Screenshots (optional):
![20190201193454_1](https://user-images.githubusercontent.com/22200358/52157070-4c44cc00-265a-11e9-8da5-2f4e0e2f0f07.jpg)
![20190201194405_1](https://user-images.githubusercontent.com/22200358/52157071-4c44cc00-265a-11e9-9cd9-ffc978f13173.jpg)
![20190201194537_1](https://user-images.githubusercontent.com/22200358/52157072-4c44cc00-265a-11e9-9f74-e3d247494425.jpg)

**Comment by Vyyt02** [comment]
I already commented on CivFanatics, so I will just copy-paste it here: I really think it is a bad install. Are you using any other mods? Also, are you sure you are using More Luxuries bundled with VP? Make sure you are not subscribed to the Steam version - if you are, unsubscribe and delete it from your MODs filder. Then reinstall VP.

**Comment by dylansan** [comment]
> I already commented on CivFanatics, so I will just copy-paste it here: I really think it is a bad install. Are you using any other mods? Also, are you sure you are using More Luxuries bundled with VP? Make sure you are not subscribed to the Steam version - if you are, unsubscribe and delete it from your MODs filder. Then reinstall VP.

I mentioned it on CivFanatics as well, but I unsubscribed from all mods, cleared my mods folder, and did a fresh install, with no effect. I've updated the issue with some screenshots, the save, and the logs.

**Comment by ryanmusante** [comment]
Do you have any DLC mods installed?

**Comment by ryanmusante** [comment]
![](https://i.imgur.com/1r8QqJv.png)

**Comment by dylansan** [comment]
I did some digging (and probably got in over my head), but I discovered something that might explain the issue. Hopefully it leads to a general solution.
https://forums.civfanatics.com/threads/mods-compatible-with-community-balance-patch-cbp.542679/page-42#post-15355146

**Comment by TechpriestEnginseer** [comment]
big if true

**Comment by TechpriestEnginseer** [comment]
having trouble reproducing at all tho

![image](https://user-images.githubusercontent.com/13937047/52524171-15207d00-2c4f-11e9-8462-b674528708fc.png)
