### ISSUE TITLE
Can't build a citadel on the friendly forest

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#514]
![8930_2015-08-12_00009](https://cloud.githubusercontent.com/assets/1131228/9224251/72300b38-411a-11e5-8839-eacf0f5fef93.png)
![8930_2015-08-12_00011](https://cloud.githubusercontent.com/assets/1131228/9224257/776af54a-411a-11e5-943f-c4bfe6a36ad0.png)

**Comment by LoneGazebo** [comment]
Is this a one-time bug, or have you replicated?

**Comment by LoneGazebo** [comment]
Any update on this?

**Comment by Radost** [comment]
I am waiting for the new version to start a new game. This isn't a total killer issue so it can linger for a bit.
I do remember being confused as to why I couldn't build a citadel on CS ally territory before, but thought it just isn't possible to build there.

**Comment by Radost** [comment]
![8930_2015-08-17_00002](https://cloud.githubusercontent.com/assets/1131228/9295378/8775c6ea-4485-11e5-9a3c-a78a60f30f07.png)
![8930_2015-08-17_00003](https://cloud.githubusercontent.com/assets/1131228/9295380/89ea3528-4485-11e5-826c-e5e1aae6f678.png)

**Comment by LoneGazebo** [comment]
You can only build citadels adjacent to your own borders.

**Comment by Radost** [comment]
Wow, I feel stupid.
![8930_2015-08-21_00006](https://cloud.githubusercontent.com/assets/1131228/9395423/d8692356-47a7-11e5-9ed3-7122f2578a5a.png)
![8930_2015-08-21_00007](https://cloud.githubusercontent.com/assets/1131228/9395427/dd315a70-47a7-11e5-941d-de33d485d0b6.png)

**Comment by LoneGazebo** [comment]
Interesting. To your knowledge, do any of the other GP improvements break if trying to build them on a forest? I can check the XML again as well.

**Comment by Radost** [comment]
You can build other GP improvements in friendly territory?
But there are no problems with building them on owned forest tiles. The forest just gets removed and the production from it gets moved to the nearest city.

**Comment by LoneGazebo** [comment]
By friendly I meant owned, sorry. And yeah, you can only build GGs in owned territory or unowned territory adjacent to your own, IIRC.

**Comment by Radost** [comment]
![8930_2015-08-24_00012](https://cloud.githubusercontent.com/assets/1131228/9459378/3d279eca-4b14-11e5-97fd-63e88f44b9ea.png)
It works just fine on owned forests.

**Comment by LoneGazebo** [comment]
Sounds good.
