### ISSUE TITLE
Researching Future Tech does not seem to increase Happiness

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5140]
_**1. Mod version** (i.e Date - 4/23):_
11-30-18

_**2. Mod list** (if using Vox Populi only, leave blank):_

VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

_**3. Error description**:_
See title and screenshots.

These issues report similar things: #3924 reports lots of other stuff, too, so it isn't clear whether this here issue was fixed; #4513 closed without doing anything as the explanation seemed to be found (not possible to generate more happiness in a city than its citizens, which isn't the case for me: see screenshot 3) and #4371 actually reports Future Tech giving far more happiness than just 10, which also isn't the case for me since I just seem to not gain or lose anything.

What happiness type is it supposed to show up under in the happiness tool tip anyway?

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![happiness_before](https://user-images.githubusercontent.com/30495439/52156459-3b0eb600-2680-11e9-9c12-5c07226693e3.jpg)
![happiness_after](https://user-images.githubusercontent.com/30495439/52156463-41049700-2680-11e9-9792-222466d82a3c.jpg)
![happiness_after2](https://user-images.githubusercontent.com/30495439/52156636-4adaca00-2681-11e9-83ca-b984cb85910f.jpg)

**Comment by LoneGazebo** [comment]
So it works, but it doesn't update right away. I'll force an update.

**Comment by UndeadDevel** [comment]
Is it supposed to show in the "Global Building Happiness"?

That part of the tool tip increased by 20 the turn after I researched Future Tech for the second time.

**Comment by LoneGazebo** [comment]
Yes
