### ISSUE TITLE
barbarian leaves camp

### ISSUE THREAD

**Issue by Enrico-Swagolo** [LoneGazebo/Community-Patch-DLL#5141]
_1. Mod version (i.e Date - 4/23):_
current

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
If you put a weak pathfinder even full hp with no promotions or little of them in sight of a camped barbie, he will rush to attack him whereas in the previous version such a Brute only attacked if he was adjacent (or if pathfinder was so low on HP, the result would be a kill). The camp might end up unmanned for a few turns as the barbie sometimes seemingly decides not to come back.

**Comment by LoneGazebo** [comment]
@ilteroi, duty calls.

**Comment by ilteroi** [comment]
yeah yeah back in town. 

what's the problem here, the fact that they leave the camp or that they do not return immediately in the next turn?

**Comment by Enrico-Swagolo** [comment]
That they do not return, I think. It doesn't happen always, but I've seen a barbie leave the camp to attack some weakling, leaving the camp vulnerable to being taken out. I think they GENERALLY return after some time, but not always. I've seen some barbies lose the track near CS lands.
It's not a huge issue, but they're probably too aggressive for an unit that should be guarding the camp.

I've also seen ranged units in barbie camps (crossbows now) on a 2 tile island leave the camp, move to the other tile just so they can shoot my corvette. It's weird. Not a huge issue, but weird for sure.

**Comment by ilteroi** [comment]
barbarians are more careful about leaving camp now and more eager to return to it
