### ISSUE TITLE
Non-capital captured city cannot be razed

### ISSUE THREAD

**Issue by ghettospud** [LoneGazebo/Community-Patch-DLL#5142]
_1. Mod version (i.e Date - 4/23):_
1-29-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
After capturing the last 3 cities from China, I successfully raze the final two, and annex Xian in order to also raze it.
Upon annexing Xian, the button for Raze does not appear.
Xian was captured after Beijing, and was temporarily China's capital city.
I brokered peace directly after capturing Beijing, so Xian was temporarily a capital during peacetime.

Both Nanjing and the third Chinese city south of Nanjing (not pictured) were successfully razed despite both being temporary capitals. Nanjing was also annexed before being razed, like Xian.

_4. Logs
Logs: [logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2824358/logs.zip)

_5. Screenshots:
![20190202052119_1](https://user-images.githubusercontent.com/39657155/52163723-d8331400-26ab-11e9-9e3d-0325edb7c10a.jpg)
![20190202052123_1](https://user-images.githubusercontent.com/39657155/52163721-d79a7d80-26ab-11e9-9adc-98d15b7243e4.jpg)
![20190202052127_1](https://user-images.githubusercontent.com/39657155/52163722-d8331400-26ab-11e9-9bd4-186f7b1d0b0b.jpg)

**Comment by ilteroi** [comment]
maybe a holy city?

**Comment by ghettospud** [comment]
China did not found a religion this game:

![20190202145046_1](https://user-images.githubusercontent.com/39657155/52169180-063f4500-26fa-11e9-8394-3b79c1d15b2a.jpg)

The complete absence of the button is strange because it is present for Beijing:

![20190202145039_1](https://user-images.githubusercontent.com/39657155/52169208-4a324a00-26fa-11e9-84ad-b481d4a06067.jpg)

Additionally, the tooltip on Beijing's raze button implies that any city which was previously a capital cannot be razed. 
I thought this would be related before I captured the two other temp-capital cities and razed them. Perhaps this tooltip should also be reworded to state that this only applies to original capital cities?

**Comment by Vyyt02** [comment]
Could be related to @Padre19 's issue mentioned in report #5149?
