### ISSUE TITLE
Frigate moving into ice tile

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5146]
_**1. Mod version** (i.e Date - 4/23):_
11-30-18

_**2. Mod list** (if using Vox Populi only, leave blank):_

VP (EUI)
City-States Leader for VP (v8)
List Enhancements for VP (v4.2)
Trade Opportunities for VP (v8.1)
Reforestation (v8) (slightly modified by me)
Civ-linked GG/GA (v11)
Enhanced Naval Warfare for VP (v1.6)
Enlightenment Era (VP) (v1.2)
Faster Aircraft Animations (v3)
Capture Great People (I neutered this one because of compatibility issues)
Espionage Mapping (v7) (modified by me)
Religious Settlers (v1)
Improved Air Recon (v1)
Missiles No Supply (v1)
More Unique Components for VP (v38)
Promotions Flags EUI (v1.1) (slightly modified by me)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
Destination (v4)
Filters in Trade Route Overview (VP) (v1.3) (slightly modified by me)
Improved City View (VP EUI) (v11.0)
Promotion Tree (v17)
Upgrade Tree (v9)
VP Promo Icons (v1.9)

_**3. Error description**:_
I've seen a frigate move into an ice tile (see screenshot); my ships can't do that (except submarines) and the frigate shouldn't be able to, either. I am using the "Subs Immune Under Ice" mod, which works, in case it's relevant. I've only seen this once, so it's not really a big deal I guess. My Modern Destroyer generates the combat simulation for the Frigate (in the screenshot) but can't actually attack, in case you were wondering.

Let me know if you want additional info; I could try and generate some logs or maybe upload my MODS folder and a save, though it's really big (about 400 MB).

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![frigate_on_ice](https://user-images.githubusercontent.com/30495439/52166398-8e2a4c80-2704-11e9-8f96-855a624d53c8.jpg)

**Comment by ilteroi** [comment]
it's possible to move into _owned_ ice tiles. but since this comes up from time to time, i might make it so that the owner can pass through but cannot stay there.

**Comment by UndeadDevel** [comment]
Ah I didn't even know that; yeah that change makes sense.

**Comment by UndeadDevel** [comment]
Yeah but why would that work? If the owner ships have cleared paths to move around in there then why not their enemies?
Way too gamey as it currently works IMO, and weird, too, which is why people keep coming here to post it as a bug ^^
