### ISSUE TITLE
Building_YieldFromFaithPurchase doesn't work

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#5148]
_1. Mod version: 01/29

_2. Mod list (if using Vox Populi only, leave blank):_
4UC mod, which includes a new building which uses the new table

_3. Error description: Purchased a missionary in a city with a building which is supposed to give 15% of faith purchase as science in the city. Nothing happens when a purchase is made:
![image](https://user-images.githubusercontent.com/33136027/52169317-4818bd00-26f3-11e9-9852-618d44a1557a.png)
Note in the before/after pictures, that scientific progress has not changed since the missionary was purchased

**Comment by LoneGazebo** [comment]
What was the faith cost? It can bottom out if the % is less than zero.

**Comment by pineappledan** [comment]
200 faith cost at 15% conversion, so it should give 30 science

Here's the code as it currently exists
INSERT INTO Building_YieldFromFaithPurchase
			(BuildingType,					YieldType,			Yield)
VALUES		('BUILDING_ARABIA_MADRASAH',	'YIELD_SCIENCE',	15);

**Comment by LoneGazebo** [comment]
Hmm....

**Comment by LoneGazebo** [comment]
Dammit, I see why. mea culpa. Here's a debug DLL for your trouble...
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2824989/CvGameCore_Expansion2.zip)

**Comment by pineappledan** [comment]
Out running errands, but I’ll confirm when I get home. Thanks!

**Comment by pineappledan** [comment]
The fix works!

**Comment by LoneGazebo** [comment]
Cool!
