### ISSUE TITLE
Occupied Cities Not Applying Unhappiness

### ISSUE THREAD

**Issue by jbuckmccready** [LoneGazebo/Community-Patch-DLL#5149]
_1. Mod version (i.e Date - 4/23):_ 1-29-1 Vox Populi EUI (everything enabled)

_2. Mod list (if using Vox Populi only, leave blank):_ Really Advanced Setup, Quick Turns, Promotion Flags EUI (Quick Turns and Promotion Flags do not affect save games and Really Advanced Setup was just used to remove Venice from random civ pool). Save games load with only Vox Populi EUI and Really Advanced Setup enabled.

_3. Error description:_ Occupied cities unhappiness is not affecting my global happiness level. It shows the unhappiness on each of the occupied cities but when I look at my global happiness/unhappiness values the occupied cities are not included.

Here is the save file and logs: [OccupiedCityHappinessBug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2825110/OccupiedCityHappinessBug.zip)

EDIT: Updated to clarify that [Really Advanced Setup](https://forums.civfanatics.com/threads/really-advanced-setup.486324/) is required to load the save.

**Comment by jbuckmccready** [comment]
I loaded the save with the latest hot fix (1-29-2), the occupied city unhappiness is still not applied. I also loaded a save earlier when there is only one occupied city and it is not applied then either.

**Comment by jbuckmccready** [comment]
Hmm I wonder if it is a new mod conflict with the latest 1-29 release? I created a new game with 1-29-2 and Really Advanced Setup not enabled on settler difficulty and quickly conquered a city and the occupied unhappiness modifier seemed to be applied (showed -0.4 when I moused over the happiness at the top, unlike in save game I posted).

Are we the only ones reporting this problem? It affects the game play dramatically since occupied cities essentially act as having 0 unhappiness regardless of needs.

**Comment by jbuckmccready** [comment]
@Padre19 I am able to raze the cities, what game difficulty were you playing on?

**Comment by LoneGazebo** [comment]
I see the occupied issue.

**Comment by Vyyt02** [comment]
@Padre19 , your issue could be related to #5142.
