### ISSUE TITLE
Road and Railroad City Connection

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#515]
![8930_2015-08-12_00010](https://cloud.githubusercontent.com/assets/1131228/9224319/e25c601e-411a-11e5-92a5-95f066c82a17.png)
IMO in situations like this railroad should take a precedence.

**Comment by LoneGazebo** [comment]
It's always shortest route because of how the pathfinder optimization works. Otherwise it'd be extremely slow.
