### ISSUE TITLE
Mongol Khan doesn't benefit from Imperialism boost to Great Generals

### ISSUE THREAD

**Issue by Omen-of-Peace** [LoneGazebo/Community-Patch-DLL#5150]
_1. Mod version (i.e Date - 4/23):_ 01/15/2019

_2. Mod list (if using Vox Populi only, leave blank):_ a bunch of UI mods (from Moi_Magnus "Improved Interface" modpack)

_3. Error description:_ After unlocking the 2nd Imperialism on the right branch (which gives +10% bonus and +1 range to Great Generals), the boost does not apply to a Mongol Khan (Great General unique replacement).

**Comment by LoneGazebo** [comment]
Good catch.

**Comment by Omen-of-Peace** [comment]
There's also an Autocracy Tier 2 tenet that changes Great Generals (+3 move or some such). You may want to check that part as well - it didn't apply either.
(I'm not sure whether fixing the 1st issue fixes the 2nd one automatically - it would depend on the code -, hence this post.)
