### ISSUE TITLE
Unit Range Highlight broken with EUI 

### ISSUE THREAD

**Issue by MRS-OBAMA** [LoneGazebo/Community-Patch-DLL#5151]
_1. Mod version (i.e Date - 4/23):_
see below, jan 29

_2. Mod list (if using Vox Populi only, leave blank):_
(ALL DLC)
        AI no free tech	Version	1
	Buildings - Upgrade System	Version	12
	Civ Advanced .1	Version	8
        Disable Obsoletion	Version	3
	Doom Guy	Version	1
	Enlightenment Era	Version	7
	Faster Building - Marathon	Version	1
[	Global - City State Airbases	Version	4
[	Global - City Works 5 Tiles	Version	1
4	Improvement - Airbases	Version	14
	InfoAddict	Version	22
	Ingame Editor	Version	39
	Itsukushima Shrine Wonder	Version	2
	New Buildings	Version	24
        Promotion Flags EUI	Version	1
        Promotions - Expansion Pack	Version	9
	Quick Turns	Version	10
	Really Advanced Setup	Version	15
	Religion - Beliefs Expansion Pack	Version	26
	Rockefeller Center Wonder	Version	2
	Teotihuacan Wonder	Version	4
Units - Airship and Land Ironclad	Version	3
	Units - Railroad Artillery	Version	4
	Units - Throwing Axeman	Version	4
	Units - Tough Nuts	Version	2
	Upgraded Artillery	Version	1
	War - Less Damaged Captured Cities	Version	3
	Wonder Race	Version	7
	Yet Another Industrial Ranged Unit Rebalance	Version	2
	St. Peter's Basilica	Version	2
      (1) Community Patch	Version	89

_3. Error description:_ 
Sorry to bother again, but this is grinding my gears,
the unit range highlight glitches with EUI, version provided in community patch mega manual install folder. I don't like to bother people so i tried to fix it on my own, i had this bug already because bombardment.lua of EUI was clashing with Global - City Bombard Range, after removing the mod (ik its implemented in CP) it was fixed, but now if i try using CP with EUI the unit range highlight is broken, unless the unit has indirect fire, it highlights either the hex the unit is on or hexes on the right, It fixes itself by removing EUI, but it's kind of a bummer. I searched in my mods folder for every bombardment.lua, unitpanel.lua rangedstrikehighlight function (as that was the problem with city bombard range) but nothing. Did i install wrong EUI? i used the manual install link in the forum thread.

_4. Steps to reproduce (optional):_
Install CP, Install EUI, remove LUA folder from CP. (keeping CoreLUA)
---------------------------
Supporting information:

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 

[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2826161/Lua.log)

**Comment by LoneGazebo** [comment]
[(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2826186/1.Community.Patch.zip)

Try this and report back.

**Comment by MRS-OBAMA** [comment]
Yeah That fixes it, is it a problem on my end due to my modlist?

**Comment by LoneGazebo** [comment]
No it’s just an issue with how the bombardment lua was being loaded.
