### ISSUE TITLE
CTD When clicking own leaderhead to view advisors

### ISSUE THREAD

**Issue by RhysDeAnno** [LoneGazebo/Community-Patch-DLL#5152]
_1. Mod version (i.e Date - 4/23):_
Happens in both 1-29-1 and 1-29-2 (tried 1 after 2 crashed). The game was originally created in 2.

_2. Mod list (if using Vox Populi only, leave blank):_
Slightly altered Communitas mapscript (https://forums.civfanatics.com/threads/guide-map-scripts.637015/page-4#post-15338786)

_3. Error description:_ 
When I click my own leaderhead I CTD. There are also some invisible mountains in this game near Seville that I indicated in the screenshot, not sure if that could have something to do with this.

_4. Steps to reproduce (optional):_
Seems to happen reproducibly, but doesn't happen with a save from the start of the game. I've included both a save from the start where I can settle and it doesn't CTD when I view advisors, and a save from later where clicking makes a CTD.

[Crash Data.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2828052/Crash.Data.zip)

**Comment by RhysDeAnno** [comment]
Update: I've been doing some experimenting with other games, and I think the crash is caused by having more than 1 city. I'm attaching a save (1-29-2 version) right before settling a city. You can click leaderhead and view advisors in it fine. Then, you settle, and go to next turn to refresh advisors. After that, clicking the leaderhead will cause the CTD.

I then tried instead using Vox Populi with no EUI, same version. Going to the advisors still causes the CTD in the same way (settle a second city, then wait a turn, then advisors will CTD)

I then tried instead using (1-15-2), which I did not remember this issue from. Loaded an older game from that version with multiple cities, no CTD. Tried to load the new dangerous save out of curiosity, CTD on load, which was what I half expected anyway, but unfortunately doesn't let us learn anything new.

**Comment by Voker57** [comment]
I am experiencing a crash on left-click every time I create a game in multiplayer (with one AI) and build a city.

**Comment by Voker57** [comment]
Save example (load, build a city, left-click your portrait): https://dump.bitcheese.net/files/cehowab/crash.Civ5Save
