### ISSUE TITLE
Automated workers do not build atop citrus

### ISSUE THREAD

**Issue by ryanmusante** [LoneGazebo/Community-Patch-DLL#5153]
1. Mod version (i.e Date - 4/23):
1-29-2

2. Mod list (if using Vox Populi only, leave blank):
```
  AI - No CS Annexers,
  Diplomacy - Auto-Denounce,
  Diplomacy - No Expansion Dialogs,
  Diplomacy - No Pointless Dialogs,
  Global - Commander Influence Borders,
  Global - Local Generals,
  Global - No Ocean Plundering,
  Global - Pro-rata Buildings Purchase,
  Global - Religious Settlers,
  Remove Ban Luxury,
  Scouts ignore Borders,
  Units - No Mechs,
  Units - Subs Ignore Borders,
  Units - Subs Immune Under Ice,
  Units - Visible Trade Units
  Calypso's Archaeology Aesthetic
  Calypso's Colored Religion Icons
  VP Happiness notifications 
AND several UI mods!
```

3. Error description:
I have always used automated workers to reduce micromanagement. Also, I tend to monitor the AI to see what they're usually doing with their workers. In this game, citrus remains untouched despite me having researched calendar and I'm certain the AI next to me also has researched. As you can see in the picture, it **can** be built on, just they're skipping. Is it because of error or just priority? Are my settings also what would be the same conditions as AI?
```
[X] Automated Workers Don't Replace Improvements
[X] Automated Workers Don't Remove Features
```
4. Steps to reproduce (optional)
```
[X] Research Calendar
[X] Research Bronze Working
[X] Watch workers skip over citrus
```
5. Screenshots
![citrus](https://user-images.githubusercontent.com/26808646/52215200-e1ec8f80-28d6-11e9-9e1e-c9debc0f6db1.png)

**Comment by Enrico-Swagolo** [comment]
Those Citrus are on top of forest tiles, you need Bronze Working (Spearman/Statue of Zeus/Iron reveal tech) to remove the forest on top of Calendar to put a plantation on it. Calendar alone would be enough if the tile was a Jungle Citrus, as Calendar also allows one to remove Jungles.

**Comment by ryanmusante** [comment]
I have bronze working. I tested to manually to build the plantation and it works.

**Comment by TechpriestEnginseer** [comment]
The AI neighbor doesn't have automated workers don't remove features.

**Comment by ryanmusante** [comment]
I updated the mod list in the first post to reflect what I'm currently using. I am thinking there might be a possible conflict.
