### ISSUE TITLE
Conquered and doubly converted city losing holy status

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#5154]
29-1

I conquered an enemy holy city while not being a founder. I correctly become the new head of such religion.
I then proceed to annex an enemy city following a different religion, and buy an inquisitor of such enemy faith.
I use that inquisitor on my holy city and convert it to build the heretic faith buildings, then I use an inquisitor and a missionary of my original faith to convert the holy city back.

Result: my holy city is no holy anymore, and I lose the founder benefits.

I understand my citizens are a bit confused at this point :)

**Comment by RandomNub** [comment]
![holycow](https://user-images.githubusercontent.com/24731508/52265228-dda28f80-2933-11e9-84fc-92a85ea1a4c7.png)

Notice I'm still considered the head of such religion and my ex-holy city keeps the reformation wonder (great altar from hero worship in this case): I correctly receive bonus delegates due to religious authority and my reformation belief/boost to holy sites work, but I no longer get the founder benefit (just conquered an enemy city and no bonus GAP/Faith)

**Comment by bigcat88** [comment]
Intended. Holy City lost its status after inquisitor. Try to convert your Holy City with missionaries - it is the only way.

**Comment by TechpriestEnginseer** [comment]
Yes, that's correct. Inquisitor will remove the Holy City Status since anything with 0 pressure no longer has a religious presence. No religion presence = no religion = no holy status
