### ISSUE TITLE
I can't start game with classical era and above.

### ISSUE THREAD

**Issue by bingo12345** [LoneGazebo/Community-Patch-DLL#5156]
_1. Mod version (i.e Date - 4/23):_
1-29-2, 1-29-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I can start game with ancient era with recent patch. but if i set up the game with classical era and above, i get instant CTD with no error message. 

before 1-29, it was fine. i can start game with every era in 1-15-2 version.

_4. Steps to reproduce (optional):_

start game with classical era and above

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by whatanatta** [comment]
I can confirm this problem. Keep all settings at default and attempt to launch a multi-player game with anything but default era.

**Comment by adaneslavo** [comment]
Me too. I thought it were mods fault, but clean VP crashes too. VP 1-29-2.

**Comment by ilteroi** [comment]
can't confirm with 1-15, must be recently introduced bug
