### ISSUE TITLE
[Feature Request] Automated cities

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#5158]
This feature request isn't urgent at all, but if that's not too complex to implement, it would be a great plus.
A recent thread about late game micromanagement nightmare brought back an old idea I had.

In short, I would like the possibility to use the puppet AI for non-puppet cities. With a toggle like "give the production queue of this city to the governor".

This option does not need to be "optimal". It just need to be at least as good as "always randomly choosing  one of the buildings advised".

**Comment by Cat-du-Fromage** [comment]
Agree!!!! It would be wonderful! I often quit 
late  because of the nightmare of micro management, the idea of "peppet" your own city was one of my Dream too :-)

**Comment by TechpriestEnginseer** [comment]
It has existed code-wise, but no one has made a mod for it(or just probably got buried in Steam Workshop).
