### ISSUE TITLE
Floating Gardens

### ISSUE THREAD

**Issue by PaintedSteel** [LoneGazebo/Community-Patch-DLL#516]
I am unable to build the Floating Gardens, despite completing production. 

![2015-08-12_00001](https://cloud.githubusercontent.com/assets/13775844/9242580/b736d7c0-4151-11e5-87b2-b0a3e535357a.jpg)

![2015-08-12_00002](https://cloud.githubusercontent.com/assets/13775844/9242585/bec40f62-4151-11e5-8990-1c6b185e72fd.jpg)

**Comment by LoneGazebo** [comment]
Is this a one-time bug, or have you replicated?

**Comment by PaintedSteel** [comment]
I had replicated it several times, however I just tried replicating after turning off all other mods I was using (mostly civilizations) and got it to work. So it appears it may have been a complication with one of the civilization mods I am using.

**Comment by LoneGazebo** [comment]
Any idea which civilization?

**Comment by PaintedSteel** [comment]
I finally figured out that it is a bug from the Greater Europe Mercia mod. As it occurs when the mod is the only one active.
