### ISSUE TITLE
Multiplayer crash

### ISSUE THREAD

**Issue by whatanatta** [LoneGazebo/Community-Patch-DLL#5162]
_1. Mod version (i.e Date - 4/23):_ 2019-01-15_

_2. Mod list (if using Vox Populi only, leave blank):_ Using VP only... EUI version

_3. Error description:_ I'm playing multiplayer with my buddies. 3 humans. The game works fine till we get to war. Once we go to war, the game either locks up or crashes to desktop. Is there something preventing 3 people playing in multiplayer? Is there a known bug?

The first game we played on World with huge map. All AI slots occupied. 3v3v3v3 or something very close to that. The 2nd time was Europe map still on standard, but only 3v3 and low city states. Both times, as soon as we go to war, it crashes. We have attempted going back a few turns to try getting past that point, but to no avail. 

I do think I need to mention one thing though after thinking about it. We got the mod from this site: https://forums.civfanatics.com/threads/vp-modpack-magnus-mutatio.639974/. I understand it's not the executable that is originally provided, but it's the same mod none the less. 
Direct link to the mega site: https://mega.nz/#F!kWZmDIIQ!NJMw3Kr2NrdeHLaohWjHMQ
 
[Logs and Save game.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2846593/Logs.and.Save.game.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Cat-du-Fromage** [comment]
I can confirm, but in 1-29-2, it's worse with 3 human players and 7 AI, we can't pass one turn without someone crash, with 6 human players and 4 AI, everyone crash trying pass turn ONE.  I will try to do some test to figure out if the AI new improvement is the problem.
