### ISSUE TITLE
Free the yields! (pPlot:ChangeYield())

### ISSUE THREAD

**Issue by tarmont** [LoneGazebo/Community-Patch-DLL#5163]
Sorry for the cheeky title. Stayed awake all night long to learn just how to compile the vanilla dll, download ancient IDEs and check the feasibility of this before asking; still need to try and get this version of the dll to compile as well.

I'd like to tamper with the result of CvPlot::calculateYield by use of a pPlot:ChangeYield() lua hook. Whether it's a permanent change or one that resets the next turn doesn't matter to me (whichever one flows the better with the system already in place)

Hope this wouldn't be too troublesome, thanks.

**Comment by LoneGazebo** [comment]
A lua hook on they would be way to performance intensive unfortunately. You’ll need to try a different method of affecting tiles. I recommend the event system.

**Comment by tarmont** [comment]
So I cobbled something together (but I don't know how arrays and serialization works in the dll). Also, this is still on the unmodded BNW dll.

I added a new field in **CvPlot.h**
`short* tar_ChangedYields`

In **CvPlot::uninit()**, I have 
`SAFE_DELETE_ARRAY(tar_ChangedYields);`

In **CvPlot::reset**,
```tar_ChangedYields = FNEW(short[NUM_YIELD_TYPES], c_eCiv5GameplayDLL, 0);
ZeroMemory(tar_ChangedYields, sizeof(short) * NUM_YIELD_TYPES);


...

	for(int iI = 0; iI < NUM_YIELD_TYPES; ++iI)
	{
	    tar_ChangedYields[iI] = 0;
	}

```

and finally, in **CvPlot::calculateYield**
```
if (tar_ChangedYields[eYield])
{
    iYield += (int)tar_ChangedYields[eYield]; // don't know if the conversion is necessary
}
```

Is this a good idea? I already tested it by assigning the index as its value, and it seems to be working alright ingame (hooray!). I could then allow the user to change this table with an exposed lua method. What are the implications of doing this?

**Comment by LoneGazebo** [comment]
The fact that lua gets called _a lot_ by functions and that calculate yield is a very expensive function makes me wary about adding such a hook. You can performance test if desired to see how it fares.

**Comment by tarmont** [comment]
I ran some tests on a duel map, then again on two normal games to compare. I've used ActivePlayerTurnEnd and ActivePlayerTurnStart to get the time between turns (which unfortunately still counts time spent on dialog with AI), then I took the mean of that.

Playing for 100 turns on the duel map, I've got an average...
1.05s **without** any dll alterations (baseline)
1.75s by making every plot yield huge amounts of everything _(the nearly doubled time is due to the AI having thousands of missionaries and stuff to do, not actually the dll alterations. Particularly, you can't skip missionary animations)._
**0.99s with all of the dll alterations in place**, but zeroed out just before they're actually applied to the plot (meant to counter the experiment above).
1.03s by adding +1 Food to farms improvements through the BuildFinished lua hook.
```
Farm = GameInfoTypes.IMPROVEMENT_FARM
Food = GameInfoTypes.YIELD_FOOD
GameEvents.BuildFinished.Add(function (_, x, y, Improvement)
    if Improvement == Farm then
        Map.GetPlot(x, y):ChangeYield(GameInfoTypes.YIELD_FOOD, 1)
    end
end)
```
1.14s when picking a random plot at random each turn of the human player and giving it +1 Faith. (This one was fun, I actually played a game with it)
```
Events.ActivePlayerTurnEnd.Add(function()
	local w, h = Map.GetGridSize()
	local x = math.random(0, w)
	local y = math.random(0, h)
	Map.GetPlot(x, y):ChangeYield(GameInfoTypes.YIELD_FAITH, 1)
end)
```

Then, I played two standard, actual games on a larger map. Again, random plots are picked and have their faith yield increased.
5.26s with the dll active.
5.19s with the dll disabled.

I think all the figures are falling on the same ballpark. After all, from the perspective of CvPlot::calculateYield, all that's changed is now it needs to access, load and increment a value from an C array before calculating the final yield; something rather harmless, and no lua is directly involved in that. Rather, lua is used to _alter_ the values inside that array at other points in time, like by calling plot:ChangeYield() from within a function hooked to PlayerDoTurn.

**Comment by LoneGazebo** [comment]
Sounds good to me! Solid sleuthing. If you make a merge request I can add this in next version.

**Comment by tarmont** [comment]
Still trying to get the community patch to compile, so I can apply the edits to it rather than the default dll. Stackwalker can't get to "CvGameCoreDLLPCH.h". Bruteforce that by changing it to "../CvGameCoreDLLPCH.h" and I get further problems down the line; 3 unresolved externals, with CvCity.obj, CvPlayer.obj and CvDllNetMessageHandler.obj. All due to "error LNK2001":
```
unresolved external symbol "void __cdecl NetMessageExt::Send::DoCityEventChoice(enum PlayerTypes,int,enum CityEventChoiceTypes,enum CityEventTypes)" 
unresolved external symbol "void __cdecl NetMessageExt::Send::DoEventChoice(enum PlayerTypes,enum EventChoiceTypes,enum EventTypes)" 
unresolved external symbol "bool __cdecl NetMessageExt::Process::FromDiplomacyFromUI(enum PlayerTypes,enum PlayerTypes,enum FromUIDiploEventTypes,int,int)"
```
What version of Visual Code do you use? I started with 2008 since it was recommended, but moved to 2010 as it seemingly has no compatible .vcxproj file here. 

Despite loving the language I'm not familiar at all with c++ tooling though, so I have nowhere to run here.

**Comment by supermerill** [comment]
2013. You have to install 2008, 2010 ( for the compatibility thing) and then 2013.

**Comment by tarmont** [comment]
Thank you! That did the trick, I think.

**Comment by tarmont** [comment]
An unaltered-but-recompiled CP dll crashes the game, though :(

It seems to be twice as large as the release version too.
