### ISSUE TITLE
Crash when trying to launch a new game with more than a couple Civs

### ISSUE THREAD

**Issue by alphakappa88** [LoneGazebo/Community-Patch-DLL#5164]
_1. Mod version (i.e Date - 4/23):
**2019-01-29**

_2. Mod list (if using Vox Populi only, leave blank):
**Vox Populi only**

_3. Error description:_ 
Trying to create a new online game with this VP 1-29 modpack (no EUI) and it keeps crashing immediately. I'm sure I installed correctly.
It seems as though I can make a single-player game or a 2-player online game just fine.
It's after I try adding more players that the game crashes immediately before the first turn.

I've been using a 2018-11-21 modpack without this issue. Even reverted back to it and booted up a 12-player online game, no problem.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Vyyt02** [comment]
I think you should mention that you are talking about mp in the title.
