### ISSUE TITLE
AI does not build plantations on sugar resources - Really Advanced Setup suspected culprit.

### ISSUE THREAD

**Issue by Bloodrocution** [LoneGazebo/Community-Patch-DLL#5165]
_1. Mod version (i.e Date - 4/23):_

1-29-2

_2. Mod list (if using Vox Populi only, leave blank):_
-  (1) Community Patch	Version	89
- (2) Community Balance Overhaul	Version	13
- (3) City-State Diplomacy Mod for CBP	Version	27
- (4) C4DF - CBP	Version	11
- (5) More Luxuries - CBO Edition (5-14b)	Version	155
- (6a) Community Balance Overhaul - Compatibility Files (EUI)	Version	1
- (ui) Trade Opportunities for VP	Version	8
- CIV-Linked Great Generals	Version	11
- Enhanced Naval Warfare for Vox Populi	Version	1
- Enlightenment Era (Vox Populi)	Version	1
- Faster Aircraft Animations	Version	3
- Ingame Editor	Version	39
- Promotion Flags EUI	Version	1
- Really Advanced Setup	Version	15
- Reseed!	Version	11
- Tectonic Map Script	Version	4
- UI - Filters in Trade Route Overview (Vox Populi)	Version	1
- VP Promo Icons	Version	1
- Wonder Race	Version	7
- Unique City-States	Version	4

_3. Error description:_ 

Russia does not want to build plantations to improve any of the sugar resources in its region; 144 turns in up to Medieval era. 

(As a side note, interestingly they are doing surprisingly well despite this, even being first by score for a long time because of the amount of Wonders they built. I only noticed there was an issue by looking at the resource monopolies screen and seeing that sugar had 0% control with 0 out of 10 in the world.)

**Reference similar issues #4345 , #4347,  #4316.**

Discussion seems to point towards the Tectonic Map Script being the culprit. However, even though I do indeed have the Tectonic Script mod installed, I did not use it for the map generation in this instance. The map is the vanilla Pangaea script that comes with Civ. 

I did, however, use Really Advanced Setup to force Ivory to be on the map, and as this is the first time I have used that mod for this purpose, as well as the first time I have witnessed this bug, I am inclined to think that this was the culprit.

_4. Steps to reproduce (optional):_

Use Really Advanced Setup mod's resource parameters to script a resource into the map's generation. My best guess.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2853821/Logs.zip)

Full log folder, sorry. I don't know which, if any would be of use so I included them all. If someone knows the names of only the pertinent logs, I can send a zip of just those.

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[NoSugar.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2853819/NoSugar.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![sugar unimproved](http://puu.sh/CKRIN/9e52f7e08e.jpg)

**Comment by ryanmusante** [comment]
I use Tectnonic map script slightly modified and was wondering if it was causing similar issue with plantations.

https://github.com/LoneGazebo/-Patch-DLL/issues/5153

**Comment by NewFellow** [comment]
Yes I have noticed that this old bug is back some how. But it has been about cocoa in my case.

**Comment by ryanmusante** [comment]
@NewFellow Cocoa is also a plantation resource. Do you notice with the others in relation?
