### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by besset** [LoneGazebo/Community-Patch-DLL#5166]
_1. Mod version (i.e Date - 4/23):_

1-29

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Crash at around turn 100 when right clicking my own potrait on right side of screen (to get to in game wiki)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2855882/Logs.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2855890/CvMiniDump.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Wu Zetian_0096 BC-0475.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2855899/Wu.Zetian_0096.BC-0475.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by l29ah** [comment]
Can confirm it, clicking own portrait sometimes causes a crash.

**Comment by Voker57** [comment]
Not present in 2.17 anymore
