### ISSUE TITLE
Visual bug, maybe RAM related?

### ISSUE THREAD

**Issue by Gartelzwerg** [LoneGazebo/Community-Patch-DLL#5167]
_1. Mod version (i.e Date - 4/23):_
2/13/2019

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch (v.89)
(6c) 43 Civs CP
Faster Aircraft Animation
R.E.D. Modpack
MoreMusic(v2)
Krajzen's Great Musician Pack(v1)
Krajzen's Great Artists Pack(v1)
Krajzen's Great Writers Pack(v1)
Hamm's Great Writer Collection(v4)
Buildings - Upgrade System(v12)
More Great Works (v3)
More Active Religions (v2)
Religion - Belief Expansion pack(v26)
Religion - Improved Customization(v15)
Hormigas Enhanced Map Pack (43 Civs)(v1)
Ingame Editor (v39)
Info Addict (v22)

_3. Error description:_ 
Several images/icons/symbols aren't loading in game. For example, the resource icon for stone isn't showing on the map ,the barbarians symbol while it is there turn (just a black area instead), or in the city menu the borders between tiles look weird. When looking at the entire map with ingame editor, a larger part of the images fail to load. Which specific images actually don't load changes each time I open an interface.
I haven't noticed any images consistantly not loading. 
When starting a normal game with 8 civs and hormigas map pack disabled, this problem doesn't occur, however on a huge map with 43 civs and hormigas map pack disabled, it does!
I have also run the same setup, except without community patch and the 43 Civs CP, but with YnAEMP DLL 43 Civs and YnAEMP Leader fix instead, where I never encountered this problem.
I suspect it to be some kind of memory(ram?) problem, but I have no idea how to solve it.
Any help is appreciated!

Edit:
My computer has 16 GB of RAM, and non of the other hardware should be an issue.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files

[modding.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2862066/modding.log)
[net_message_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2862067/net_message_debug.log)
[stopwatch.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2862068/stopwatch.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2862069/xml.log)
[xml-perf.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2862070/xml-perf.log)
[APP.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2862071/APP.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2862072/Database.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2862073/Lua.log)

**Comment by Vyyt02** [comment]
Yes, this is a known issue. You actually described exactly what the problem is. It is huge map + 43 civs + R.E.D. Civ5 is a 32-bit app, so 16 GB RAM won't help you. Playing without R.E.D. is the safest way or you can try lowering your graphic details or the size of the map, but you will probably run into the same problems in a later stage of the game. In the past on an older computer and a different mod (Communitas), what helped me quite a bit was lowering one particular graphic setting, unfortunately, I cannot remember which one (maybe the shadows?).

**Comment by l29ah** [comment]
Have you tried both DX9 and DX11 versions?

**Comment by Gartelzwerg** [comment]
> Yes, this is a known issue. You actually described exactly what the problem is. It is huge map + 43 civs + R.E.D. Civ5 is a 32-bit app, so 16 GB RAM won't help you. Playing without R.E.D. is the safest way or you can try lowering your graphic details or the size of the map, but you will probably run into the same problems in a later stage of the game. In the past on an older computer and a different mod (Communitas), what helped me quite a bit was lowering one particular graphic setting, unfortunately, I cannot remember which one (maybe the shadows?).

Thanks alot! Disabling RED has resolved all issues, at least for the first few moves. 
I didn't think of doing that since I didn't have any of those issues on huge 43-civ maps with RED before using the Community Patch.
RED is not important to me, so I'll just stop using it and thats that (hopefully) :)
