### ISSUE TITLE
Policy_CapitalYieldPerPopChangeEmpire with GAP and GGP Bug.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#5168]
Well the Policy_CapitaYieldPerPopChangeEmpire seems to work as the yield icon shows up, but no yield is added to the pool!
````
INSERT INTO Policy_CapitalYieldPerPopChangeEmpire (PolicyType, YieldType, Yield)
SELECT 'POLICY_CIVIC_CASTE_SYSTEM', 'YIELD_GREAT_GENERAL_POINTS', 10 UNION ALL
SELECT 'POLICY_CIVIC_CASTE_SYSTEM', 'YIELD_GREAT_ADMIRAL_POINTS', 10;
````

![image](https://user-images.githubusercontent.com/13937047/52757616-29031080-2fba-11e9-952f-3f44137b6a41.png)
![image](https://user-images.githubusercontent.com/13937047/52757621-302a1e80-2fba-11e9-92a0-5b3280a9bf09.png)
![image](https://user-images.githubusercontent.com/13937047/52757630-391af000-2fba-11e9-9c4a-238bf1f17db4.png)
Not sure what is happening here.

**Comment by LoneGazebo** [comment]
It's because I'd turned off all yield types above YIELD_GOLDEN_AGE_POINTS for performance reasons. I can re-enable. It'll be a minimal performance hit.

**Comment by TechpriestEnginseer** [comment]
I would like that.

**Comment by LoneGazebo** [comment]
LO IT IS DONE
