### ISSUE TITLE
Social Policy Notification Bug

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#517]
As LeeS has pointed out here: http://forums.civfanatics.com/showpost.php?p=13923295&postcount=9
the Social Policy notification system appears to break after a certain number of 'dummy' Social Policies (ones which do not effect Social Policy costs) are obtained by a player. I've tested this, and, indeed, after so many SPs, the "Adopt Policy" notification no longer appears, which means it is very easy to miss when you have enough Culture.

I could work around this if need be, but I was hoping that there would be somewhere/somehow/something in the DLL that would help resolve this issue. Failing this vague request, perhaps it would be possible to push out into Lua whatever function is used to prevent the human player from progressing turns, which I could then use (alongside a custom, but identical, notification) to imitate the 'Adopt Policy' notification event. In which case, I'd need an associated check for if the player can progress turns, so perhaps a GameEvent.ActivePlayerCanEndTurn() and a Player:CanEndTurn() or something.

Thanks for any help looking into this issue anyway.

**Comment by LoneGazebo** [comment]
I'll give it a look see. Do you have any idea as to how many dummy policies trigger it?
G

**Comment by JFDaly** [comment]
According to LeeS, 23 is the limit. I can make a note to test myself to confirm the number.

LeeS discovered that sending the 'Adopt Policy' nofitication through the AddNotification() method works to block the player turn, so it wouldn't be entirely necessarily to add a custom method to do this anymore. However, it'd still probably be better to find the cause and fix it (if easy), as we aren't certain whether this issue has any adverse effects upon the AI.

**Comment by LoneGazebo** [comment]
Looking at the DLL, I see no hardcoded limit, which means this is probably a glitch in the UI engine of the game. Unfortunately, we can't modify that.

G

**Comment by JFDaly** [comment]
Ah, no matter. Thanks for taking a look.
