### ISSUE TITLE
Helicopter Gunship on ocean tiles is embarked instead of hovering.

### ISSUE THREAD

**Issue by liutasx** [LoneGazebo/Community-Patch-DLL#5178]
_1. Mod version (i.e Date - 4/23):_
2-17

_2. Mod list (if using Vox Populi only, leave blank):_
(over) More unique Components for VP (v41)

_3. Error description:_ 
Helicopter Gunship on ocean tiles become embarked instead of hovering and also can't attack from ocean tiles. Everything is okay, then helicopter gunship is on coastal tiles.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ryanmusante** [comment]
Helicopters Can Fly Over Water Mod
https://steamcommunity.com/sharedfiles/filedetails/?id=290755783

**Comment by supermerill** [comment]
seems logical. I can't see an helicopter flying indefinitely alone over the ocean irl.

**Comment by Voker57** [comment]
@supermerill but flying indefinitely over coast and hostile land areas is ok?

**Comment by supermerill** [comment]
They may be able to land near a gaz station and steal some gasoline. For the coast, I see it as anti-submarine patrol.
