### ISSUE TITLE
Workers no longer aware of danger

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#5181]
_1. Mod version (i.e Date - 4/23):_

2-17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Workers do not stop working end of turn when they are within range of a enemy unit.
Seems to affect AI also, workers are easy to capture and a lot can be found in barb camps.

_4. Steps to reproduce (optional):_

**Comment by ilteroi** [comment]
i know - it's fixed already
