### ISSUE TITLE
Peace Treaty Length

### ISSUE THREAD

**Issue by psparky** [LoneGazebo/Community-Patch-DLL#5184]
_1. Mod version (i.e Date - 4/23):_12/18

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

CoreDefines.sql has the following:
UPDATE Defines SET Value = '20' WHERE Name = 'PEACE_TREATY_LENGTH';

In game, my treaties are only 10 turns, like in vanilla.

Curiously, I was thinking of changing the length to 20, but found the define already said that!

_4. Steps to reproduce (optional):_

**Comment by TechpriestEnginseer** [comment]
perhaps you play on quick?

**Comment by psparky** [comment]
No, it's standard. Do you get 20 turn peace treaties on standard? If so, then it must be a problem with my set up.

**Comment by psparky** [comment]
Further investigation shows that PEACE_TREATY_LENGTH is _not_ used to determine the length of peace deals that the player makes. That is determined by PeaceDealDuration which depends on game speed. 

However, PEACE_TREATY_LENGTH _is_ used in a number of files and it may be worth a look at those uses to see if it would be more appropriate to use PeaceDealDuration. For example, if I understand what is going on (which is doubtful!), peace deals between AI's might be 20 turns long irrespective of game speed (CvDealAI.cpp).
