### ISSUE TITLE
happiness crash

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5187]
latest version 2/17-3

![image](https://user-images.githubusercontent.com/1358966/53288261-a54dde80-3786-11e9-8d92-66695ab6d554.png)

don't know what happened to persia but i don't think that's intended?

logs here:

[PlayerHappinessStats.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2896935/PlayerHappinessStats.zip)

if you need more, just tell me

**Comment by LoneGazebo** [comment]
Did they get sanctioned or something?

**Comment by ilteroi** [comment]
maybe ... it was autoplay

**Comment by TechpriestEnginseer** [comment]
Although the more likely idea is that their Golden Age ended.

**Comment by ilteroi** [comment]
well a drop of almost 200 just shouldn't happen no matter what. right?

**Comment by LoneGazebo** [comment]
I dunno.

**Comment by ilteroi** [comment]
ok turns out persia declared war on the zulus (and indirectly also on the aztecs apparently) in turn 439.

then this happened:

```
438	 Persia	 TotalHappiness	1	 	GoldU	59	 DefenseU	100	 ScienceU	35	 CultureU	39	 War Weariness	30	 Supply	239	 Use	84
439	 Persia	 TotalHappiness	-193	GoldU	122	 DefenseU	129	 ScienceU	39	 CultureU	130	 War Weariness	27	 Supply	243	 Use	83
```

**Comment by LoneGazebo** [comment]
Holy moly.
