### ISSUE TITLE
Request: Column in promotion table to allow moving over water

### ISSUE THREAD

**Issue by theazuresoul** [LoneGazebo/Community-Patch-DLL#5191]
For a modmod, I've been trying to give a promotion that allows moving over coasts without embarking like a zeppelin, without all the other perks (moving over mountains, ignoring terrain costs) that come with hovering. I tried a combination of EmbarkAllWater and HoveringUnit, and that does allow moving over water, but it also causes the unit to ignore terrain costs, which I do not want. Is there any existing way in the current code to isolate the water-walking functionality of HoveringUnit? If not, would it be difficult to add in a future release?

**Comment by ilteroi** [comment]
i'm afraid there's currently no way to do this. and the unit movement logic is complex and bug-ridden enough as it is so i'm wary of changes.
