### ISSUE TITLE
Pathfinding Request. Missionaries ending turn in unauthorized territory.

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#5193]
_1. Mod version (i.e Date - 4/23):_
2019 February.

_2. Mod list (if using Vox Populi only, leave blank):_
Any

_3. Error description:_ 
Whenever I send missionaries to a far away city, they have the bad habit of passing through the territory of a county which has not given me open borders, just because that's the shorter path.

Would it be possible, just for religious units, to discourage the pathfinding engine ending turns in closed territory? I don't mind them passing by some tiles, it's just ending the turn inside that country what kills them. And I mean discouraging, not forbidding, because sometimes the only available path is through unsafe territory.

This is just worse when I try to automatize them. They love martyrdom.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
this shouldn't be happening. i'll take a look.

**Comment by bryan317** [comment]
Thanks for checking into this.  I've actually noticed this for years and just accepted it as normal behavior.  It would be nice to streamline this, I would always manually control my missionaries through pagan lands

**Comment by ilteroi** [comment]
they way it is implemented right now, missionaries should take detours of up to three plots to avoid ending the turn in foreign territory. maybe that is simply too low? can you confirm that they at least take small detours? or none at all?

**Comment by tu-79** [comment]
Will try next time, but currently I have open borders agreements with most my neighbours :D
