### ISSUE TITLE
AI penalty for voting against proposal he decided he didn't want either

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#5195]
_1. Mod version (i.e Date - 4/23):_
2-17-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/34615525/53460920-d93a3580-3a0c-11e9-8682-73e64cec8cf7.png)
![image](https://user-images.githubusercontent.com/34615525/53460996-130b3c00-3a0d-11e9-9e94-804f09fc95cb.png)
![image](https://user-images.githubusercontent.com/34615525/53461004-1999b380-3a0d-11e9-8e3a-167ad4d16ba7.png)
Why is he angry at me? He voted against the proposal himself D:

**Comment by LessRekkless** [comment]
I mean, I understand why it's there in the first place, but this is a special circumstance, isn't it?

**Comment by bklick** [comment]
To be clear, did Siam pay you to vote Nay?

**Comment by LessRekkless** [comment]
Siam did not. He made the proposal, then likely changed his mind after the global situation changed, and voted down his own proposal.

**Comment by LoneGazebo** [comment]
Unfortunately vote data is lost after the die is cast, there's no way for the AI to remember that it didn't vote on a proposal it proposed. :)

**Comment by LessRekkless** [comment]
It remembers that I voted for/against a proposal it proposed, but not itself?

**Comment by LoneGazebo** [comment]
Well it simply checks to see if it passed or failed, and people's 'side' commitment is what is remembered.

**Comment by LessRekkless** [comment]
So it could technically add another check to see if its own 'side' commitment matches everyone else's 'side' commitment?
