### ISSUE TITLE
This isnt an issue but a solution to the air unit unable to attack melee ships problem

### ISSUE THREAD

**Issue by yyEdge** [LoneGazebo/Community-Patch-DLL#5196]
Like the title said, this isnt a problem but a solution for air units unable to attack melee ships with dreadnought promotion and on low hp problem found a while ago. I just don't know where to post it so I figured I'll just throw it up here. I recalled seeing an issue opened here a while ago and it was closed due to non-repeatability.
Apparently units that are still alive after more than 100 damage dealt to them are registered as negative hp, (according to IGE anyway), and there is this on planes if I'm not wrong.       
< RangedCombatLimit>100< /RangedCombatLimit> (remove the space)
So apparently all it takes is just change the number from 100 to something bigger, I did 
< RangedCombatLimit>160< /RangedCombatLimit>  (remove the space) because dreadnought gives +50 hp at max if I'm not wrong? So I figured just to be safe I used 160.
After that planes are able to attack and sink ships with more than 100 hp no problem.

**Comment by LoneGazebo** [comment]
@ilteroi this makes sense? I see combatlimit being used just in one place, plot::getbestdefender - perhaps that function is returning null for air units in this case, thus the air units aren't 'seeing' a target?

**Comment by yyEdge** [comment]
I excluded combatlimit line in the .xml file on one of my modded fighters and it wasnt able to bombard at all so, that kind of gave me the idea.

**Comment by ilteroi** [comment]
yeah seems somebody added a half-assed feature to stop air units from killing units.

**Comment by LoneGazebo** [comment]
Wasn’t me! :)

**Comment by ilteroi** [comment]
if we're going to keep this i would rename it (and invert it) to "AirAttackHitPointLimit" or so to make clear what's happening. but might as well remove it.

**Comment by LoneGazebo** [comment]
I really don't know what it is supposed to do...

**Comment by TechpriestEnginseer** [comment]
OR WE DONT TOUCH IT

**Comment by yyEdge** [comment]
this is literally what I added into the AirUnits.sql lol, and its only an sql edit so its compatible with whatever.

	UPDATE Units
	SET RangedCombatLimit = '160'
	WHERE Type = 'UNIT_FIGHTER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

	UPDATE Units
	SET RangedCombatLimit = '160'
	WHERE Type = 'UNIT_BOMBER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

	UPDATE Units
	SET RangedCombatLimit = '160'
	WHERE Type = 'UNIT_JET_FIGHTER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

	UPDATE Units
	SET RangedCombatLimit = '160'
	WHERE Type = 'UNIT_STEALTH_BOMBER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

	UPDATE Units
	SET RangedCombatLimit = '160'
	WHERE Type = 'UNIT_JAPANESE_ZERO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

	UPDATE Units
	SET RangedCombatLimit = '160'
	WHERE Type = 'UNIT_AMERICAN_B17' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

	UPDATE Units
	SET RangedCombatLimit = '160'
	WHERE Type = 'UNIT_GUIDED_MISSILE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

**Comment by ilteroi** [comment]
why the screaming? are you telling me any badly coded mod that may or may not exist is now more important than PROGESS (tm)? just kidding.

anyway by removing i meant the check in getBestDefender. db and lua can stay. but the whole thing is crazy because air attacks are not ranged attacks.

**Comment by supermerill** [comment]
Maybe a leftover form civ4, when a combat have to kill one of the contender (most of the time)?

**Comment by TechpriestEnginseer** [comment]
Oh
