### ISSUE TITLE
Missing PuppetCityPopup.lua? 

### ISSUE THREAD

**Issue by MRS-OBAMA** [LoneGazebo/Community-Patch-DLL#5199]
_1. Mod version (i.e Date - 4/23):_
2-17 (CP+EUI only)

_2. Mod list (if using Vox Populi only, leave blank):_
Doesn't seem like it is involved, possible offenders could be me having the UI - City Production option in the CustomModOptions.xml to 1, but i haven't been able to quite replicate

_3. Error description:_ 
Sometimes, when conquering a city of another civ that conquered the city from a 3rd ai, the game will show no pop up to choose, and apply no unhappiness from the citizens, but still gain the local happiness

_4. Steps to reproduce (optional):_
I've tried to reproduce this once but i wasn't able to. Seems to be happening mostly on cities that can be liberated.

Supporting information:

1. Log files 
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/2921100/Lua.log)
 As you can see there's:
`Runtime Error: Assets\ui\InGame\PopupsGeneric\PuppetCityPopup.lua:61: Instance does not exist`.
And (Not sure if this is the one that is being loaded in game) but in the PuppetCityPopup.lua of the Expansion2 Folder line 61 is this:
`strToolTip = strToolTip .. activePlayer:GetLiberationPreviewString(iLiberatedPlayer);`

I haven't found a PuppetCityPopup in the EUI folder nor the CP folder, so i will try to add the PuppetCityPopup.lua from LUA  folder of eui-less CP and report back.
Cheers

**Comment by ryanmusante** [comment]
For a full install, it's located under 6A for EUI/VP. Also, I have the actual UI - City Production mod installed to get the UI option (highly recommend).
```
My Games/Sid Meier's Civilization 5/MODS/(6a) Community Balance Overhaul - Compatibility Files (EUI)/LUA/PuppetCityPopup.lua
```
