### ISSUE TITLE
Happiness from Landmarks

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#5203]
_1. Mod version (i.e Date - 4/23):_

2-17

_2. Mod list (if using Vox Populi only, leave blank):_

-

_3. Error description:_ 

You are supposed to get 2 happiness when you create a landmark, but it doesnt happen.

_4. Steps to reproduce (optional):_

**Comment by LessRekkless** [comment]
See this save game for the turn before two dig sites finish:
[Harald Bluetooth_0314 AD-1888.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2948048/Harald.Bluetooth_0314.AD-1888.zip)
Log:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2948049/Logs.zip)

**Comment by LoneGazebo** [comment]
Yeah, just a small database merge error on my end.
