### ISSUE TITLE
Workers on holidays

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#5205]
_1. Mod version (i.e Date - 4/23):_
2019-Feb-17-hotfix3

_2. Mod list (if using Vox Populi only, leave blank):_
UI enhancements

_3. Error description:_ 
After finishing all possible improvements in the continent, all my workers but two went on holidays. They travelled 10 turns to my island cities, where there's nothing to improve and stayed there even when I discovered railroads and work was needed again in the continent.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
it's not a bug, it's a feature :)

**Comment by tu-79** [comment]
Nice!
Could this feature distribute workers upon owned 'land' territory?

**Comment by ilteroi** [comment]
for performance reasons, workers only look for work on plots which are reachable within 5 turns or so. if there's nothing to do, they spread out and wait for work there. i didn't anticipate them to get stuck on islands ... anyway this should be easy to fix

**Comment by tu-79** [comment]
Actually, this is a nice feature, but currently most workers went to the islands and only a couple stayed in the continent. I don't mind a worker stationed in an island city if it has at least one improvable tile.

Could cities demand workers? It would be a check on border expansion. If upon a border growth city has no improvable tiles, mark this city with a non-workable tag, that prevents workers to be sent to the city. If there are improvable tiles, mark it as workable. If those tiles are not improved yet, mark it as demanding workers, not demanding workers otherwise.
Then, when a worker is left with no work, he would try to go first to a city that is demanding workers. If he can reach the city, change the city tag to workable, not demanding workers, so only one worker answers the call. If there is no city demanding workers, he will go to the closest city with fewer idle workers, and wait there until there is work to do.

Sounds feasible?
