### ISSUE TITLE
AI military flavor is on steroids

### ISSUE THREAD

**Issue by MRS-OBAMA** [LoneGazebo/Community-Patch-DLL#5206]
_1. Mod version (i.e Date - 4/23):_
2-17 (CP+EUI the usual)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm playing on Immortal, i disabled Military Tweaks, City Strategy Tweaks, Diplomacy and Deals tweaks, but isabella has 200.000 soldiers, like, what???? warring feels like the most boring thing ever, you can't even blitzkrieg, the turn you declare war you have no joke 25 units on the border. i have double her population and all cities producing military but it's not enough, i passed standing army tax, and crippled her gold for a bit but then she went back to normal and kept producing more. How the hell do i disable all military tweaks? I just want vanilla ai and unified yields =)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

It appears that there's a lot of war and military stuff in corechanges.sql attached to settler tweaks? why is that? Can i just delete military flavors from there?

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
‘Disabling’ tweaks will break the game.

**Comment by MRS-OBAMA** [comment]
But it's breaking my game, turns take 30-45 seconds per AI on a i7 7700k from the sheer amount of units =(

**Comment by MoiMagnus** [comment]
Disabling tweak possibly break the game even more than keeping them, since the AI will not have any "sanity" to stop building units when it has enough of them. The CP AI doesn't spam like units more than in Vanilla, it is just much cleverer, so has far more efficient cities than in vanilla (so more production to spam units), and is able to not stupidly lose its unit in fight (so more units remaining after war)

For turn duration, have you tried using the quick turn mod? 

And in general, have you tried stepping down the difficulty to a difficulty where the AI doesn't have "35% discount everywhere" like it is the case in immortal in Vanilla civ 5. I mean, the CP AI is usually considered to be worth ~2 difficulty levels.

**Comment by MRS-OBAMA** [comment]
ye i have quick turns, i played on emperor but i outteched ai starting from turn 100, without building all the scientific buildings, like it annoys me because there's the AI with 1/3rd my score, 1 era behind that keeps declaring war on me,  i guess ill revert to whoward's VMC until i figure out how to calm the ai down

**Comment by LoneGazebo** [comment]
Sounds like you're just too good for the CP AI. I think stepping back to the VMC is definitely the right move for you.

G

**Comment by MRS-OBAMA** [comment]
@LoneGazebo just one thing, since i really like all the changes you've got here except the ai, could i rebuild the dll with the vanilla AI files or are they referenced / use references from other files?

**Comment by LoneGazebo** [comment]
Sure, you'll just need to go through the DLL line by line and remove all AI changes, but other than that, you can do whatever you want with the code.

**Comment by MRS-OBAMA** [comment]
![excellent](https://user-images.githubusercontent.com/47156346/53838580-bc19df80-3f95-11e9-9408-f58f07ea2b36.gif)
