### ISSUE TITLE
Trade Routes Unpillagable

### ISSUE THREAD

**Issue by amateurgamer88** [LoneGazebo/Community-Patch-DLL#5208]
_1. Mod version (i.e Date - 4/23):_2/17

_2. Mod list (if using Vox Populi only, leave blank):_Enlightenment Era and 3rd/4th UC

_3. Error description:_ My Trade Routes cannot be pillaged by the AI at all. They move through enemy units as though there was no war going on. AIs have pillaged each other's TR that were sent to me but not mine. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): Unfortunately, logging wasn't enabled so I cannot provide any. However, the error is ongoing throughout the game so I don't know when enabling the logging is ideal. 

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 

[Suleiman_0363 AD-1943.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2929040/Suleiman_0363.AD-1943.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

The first screenshot shows how overwhelmed I am in terms of my war with Arabia. 
![20190304183541_1](https://user-images.githubusercontent.com/48229872/53776885-63224c80-3eac-11e9-9d22-9b3974dacd63.jpg)

The second screenshot shows my active TR which shouldn't be possible given how my capital is more or less surrounded. 
![20190304183546_1](https://user-images.githubusercontent.com/48229872/53776883-63224c80-3eac-11e9-9e2e-ea61e544219d.jpg)

**Comment by LoneGazebo** [comment]
Corporation choice?

**Comment by amateurgamer88** [comment]
The Corporation I went for was Firaxite.  I also went Freedom and grabbed Transnationalism.

**Comment by TechpriestEnginseer** [comment]
![image](https://user-images.githubusercontent.com/13937047/53812516-8383f280-3f10-11e9-8ae6-8cb1b06cb186.png)
