### ISSUE TITLE
Crash during AI Germany's turn - Deity - Marathon

### ISSUE THREAD

**Issue by Jietoh** [LoneGazebo/Community-Patch-DLL#5209]
_1. Mod version (i.e Date - 4/23):_
2-17-3

_2. Mod list (if using Vox Populi only, leave blank):_
Global - City Works 5 Tiles - https://www.picknmixmods.com/mods/CivV/Global/City%20Works%205%20Tiles.html

AI No Free Tech - https://steamcommunity.com/sharedfiles/filedetails/?id=177544192

_3. Error description:_ 
Clicking Next Turn goes into Germany's turn and at some point during his turn, the game crashes.

_4. Steps to reproduce (optional):_
Click Next Turn

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2937819/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Gandhi_0774 AD-1755.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2937822/Gandhi_0774.AD-1755.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[civilizationv_dx11_403694_crash_2019_3_6T17_25_12C0.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2937824/civilizationv_dx11_403694_crash_2019_3_6T17_25_12C0.zip)

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/12678748/53905507-b7e1d680-4016-11e9-9f36-1611cca07fec.png)
![image](https://user-images.githubusercontent.com/12678748/53905521-c203d500-4016-11e9-94a9-985c0a9579e8.png)

**Comment by LoneGazebo** [comment]
I'm guessing it is an out-of-memory crash, 5 tile + marathon = huge ram usage.

**Comment by Jietoh** [comment]
I've tried to limit the amount of RAM used and got rid of the 5-tile mod and still crashes at the same point.

**Comment by LoneGazebo** [comment]
You can't remove a mod like that mid-game.

G
