### ISSUE TITLE
Puppets build Hotels

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#521]
While this structure is very situational.

**Comment by LoneGazebo** [comment]
Okay? So...they shouldn't built it? But then what if you want them to?

**Comment by Radost** [comment]
Supercities/capital are the main source of tourism in the endgame. I doubt 7 tourism (in the very best case) will make much difference in the grand scheme. I think they should check for UI/sites nearby before building it. And even then it should a very low priority, because right now puppets build hotels before arsenals and the likes.

**Comment by LoneGazebo** [comment]
Well, it is based on flavors, particularly economic flavors for the empire. The system, as it stands, prioritizes buildings that the current economic priority demands.

**Comment by Radost** [comment]
Then the flavours are flawed. I can't think of any situations hotels can be more useful than any other building.

**Comment by LoneGazebo** [comment]
I don't feel it is the purview of a puppet to be asked to decide whether or not a city needs a building or not - I think some, like unit training buildings, should be avoided, as they're impossible to use (can't make units). Hotels are more of a strategic question, and are, therefore, a different issue.

**Comment by Radost** [comment]
But "unit training" buildings also reduce crime.

**Comment by LoneGazebo** [comment]
I'd make a post on the forum to see if this is of interest to the community. It feels more like a balance issue, tbh.
