### ISSUE TITLE
2-17 Tradition AI

### ISSUE THREAD

**Issue by RandomNub** [LoneGazebo/Community-Patch-DLL#5210]
![civtradned](https://user-images.githubusercontent.com/24731508/53958921-88989b80-40e2-11e9-9fec-07c0b079d33c.png)

I question AI governor priorities, when they are so blatantly ignoring specialist slots in a full tradition/statecraft capital (half food needed, bonus science, TtGoG reformation) while building basic stuff. WLTK+GA might be what makes AI prefer basic tiles such as no-fresh water farms, but it's unoptimal imho.

Also, t156 rax? :P

**Comment by supermerill** [comment]
May be linked to #5172 (Governors overvalue specialists)
