### ISSUE TITLE
War Weariness Supply Cap Reduction Tooltip

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#5212]
_1. Mod version (i.e Date - 4/23):_
2-17-2? (-3?)

_2. Mod list (if using Vox Populi only, leave blank):_
Improved City View
Filters in Trade Route
Religion Spread

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/34615525/54078784-65195080-429c-11e9-91c7-7a4abeeab72d.png)
The tooltip says that I have a supply cap reduction of 10 due to war weariness. It also says I have a supply cap reduction of 5 ... also due to war weariness.  Which one is correct? Do we need both?

**Comment by bigcat88** [comment]
10% is cost.(to produce or purchase units). 
Supply decreased by 5.

**Comment by LessRekkless** [comment]
You're looking at the wrong "10". I'm talking about the value in red.

![image](https://user-images.githubusercontent.com/34615525/54088245-685f1b80-4332-11e9-971c-c2d18cecbdc8.png)
These don't match up.

Not only that, but 39 + 196 + 8 - 180 - (12 or 18) = 53 or 47 ~= 57. Some supply is not being shown.

As a sidenote, supply from Great Generals and Great Admirals is being added to the "from owned Cities" heading, which isn't great for helping the player remember where all his bonuses from.

**Comment by LoneGazebo** [comment]
Since supply rounds down on decimals, it can create some missed values. The red text issue is just a misplaced {bracket} number. It should mirror the -12.

G

**Comment by LessRekkless** [comment]
I don't understand; where is the rounding occurring such that the displayed values don't sync up? Is it just rounding down in the tooltip and not being rounded in the background?

**Comment by LessRekkless** [comment]
Whoops, somehow I can't do arithmetic. Round down doesn't mean truncation, in this case? 
War Weariness = (39+196+8) * -0.18 = -11.34 = -12?
Military Supply Base Values - Military Supply Reduction = **51**. That's **6** below the supply listed at the top. How can we be 6 supply off when only rounding 5 numbers? Handicap is exact and therefore doesn't get rounded and I believe Owned Cities is as well.

If we round all of the supply from population from my six cities individually before the calculation, then that would show in the **Current Military Supply** number (causing it to be lower than it should be which isn't the case here).

War Weariness being a percentage off of truncated numbers would cause it to be lower than it should be (and the summed values higher than it should, which again isn't the case here).
