### ISSUE TITLE
lost capital notification leaks info

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5214]
it says eg "unmet player lost their capital, oda nobunaga now controls the most capitals" ... but i haven't met japan either.

**Comment by LoneGazebo** [comment]
I think it's something to do with observer mode, as observer mode seems to trigger some weird 'hasmet' criteria for player 0.

**Comment by ilteroi** [comment]
na, played myself for a change :)

**Comment by psparky** [comment]
I've also seen this recently, albeit with an older version.

I think this is actually a vanilla bug that didn't get fixed. Yet :)
