### ISSUE TITLE
AI doesn't dig Antiquity Sites

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#522]
Or does it VERY slowly.
There are still not touched sites in the Atomic Era civilization territory.

**Comment by LoneGazebo** [comment]
It does, but yeah, the AI does not heavily prioritize archaeology.

**Comment by Radost** [comment]
I recall AI being quite aggressive on them in the previous versions.
In one of my games I spent too much time building my capital as Venice to the point AI civs started to dig my sites. And it wasn't very late in game either.

**Comment by LoneGazebo** [comment]
It may simply be contextual – neither Ilteroi nor I have touched that part of the code in the past few months.

**Comment by Radost** [comment]
I am pretty sure it's not contextual. As of right now I have 5 civs in the game with Aesthetics and yet the number of hidden antiquity sites haven't changed in the past 100 turns.

**Comment by LoneGazebo** [comment]
The code remains untouched from previous versions, but I'll give it a look for you.
