### ISSUE TITLE
Feature Request: Changing number of Civs / City States in Online Multiplayer

### ISSUE THREAD

**Issue by bklick** [LoneGazebo/Community-Patch-DLL#5220]
Currently, when you make an online multiplayer game, you're not allowed to add more or subtract fewer civs or minor civs to/from the game. It would be nice if we could change these like in single player.

**Comment by LoneGazebo** [comment]
I think it's because the lobby data is set once you open the lobby itself.

**Comment by bklick** [comment]
You can't change the number of players on a map before the lobby either, though. I found I'd missed a slider for minor civs. Am I missing something for players?

**Comment by Voker57** [comment]
You can set amount of city states using the slider on top of "options" tab.

You can substract AIs by not adding them to slots, you can't add more than default cause it's map limit.
