### ISSUE TITLE
Trade screen almost always blank/messed up mid-game.

### ISSUE THREAD

**Issue by pitprowler** [LoneGazebo/Community-Patch-DLL#5221]
_1. Mod version (i.e Date - 4/23):_
2/17/2019

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi
InfoAddict
In Game Editor
Really Advanced Setup

_3. Error description:_ 
This only just happened since I got the latest version of the mod pack a few days ago.

On the diplomacy screen, when trading with most other leaders, the items to be traded do not appear on the screen, it's just blank (See screenshot). I do see the value of the trade at the top, however I don't get the "What will make this deal work?" button. When it's in this state, I'm also able to add an unlimited amount of resources from them or me to trade and the deal value will keep changing accordingly. The resource count does not decrease.

I can get around it and make the items appear, and this may be a clue to the problem, by adding one or more technologies to the trade. Sometimes adding one tech on my side will fix the problem, for one leader I needed to add 3 to fix it, for another leader I didn't have the problem at all. After I do get the trade items to show up, I'mm able to manually adjust anything else in the trade, then I remove the tech and it all goes blank again, but clicking the Propose button completes the trade.

To me it looks like it may have started when I got to the point where I was able to trade technologies.

The leader that I did not have the problem with, I had a diplomat in his city meaning he had additional world congress items available to trade. It might possibly have something to do with the amount of different items available to trade on each side.

_4. Steps to reproduce (optional):_
Initiate a trade with almost any leader and try to add resources.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2959063/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2959013/Save.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5-screen](https://user-images.githubusercontent.com/42410304/54240875-58d80200-44ed-11e9-8928-1e7b418e2019.png)

**Comment by pitprowler** [comment]
This seems to have somehow fixed itself a bit later into this game.

**Comment by LoneGazebo** [comment]
>[2295280.930] Runtime Error: e:\Users\Ste\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files\Core Values\TechHelpInclude.lua:917: attempt to index field '?' (a nil value)

A ton of times in your lua log. Mod conflict? I don't see this in other lua logs.
