### ISSUE TITLE
City Panel doesn't account for border growth

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#5222]
So if you're wanting to know when is a city going to acquire a tile. The game doesn't account for BGP/turn. Is this for performance's sake or oversight reason?

**Comment by TechpriestEnginseer** [comment]
![image](https://user-images.githubusercontent.com/13937047/54328927-f5bd9c80-45cc-11e9-822d-041cffbde200.png)

**Comment by ilteroi** [comment]
what is bgp?

**Comment by MoiMagnus** [comment]
The culture that only count for border growth, but not for happiness and social policies.
That's a kind of yield different from culture.

**Comment by LoneGazebo** [comment]
The function is managed at the lua level so you can just add a check for it.

**Comment by ilteroi** [comment]
that would be YIELD_CULTURE_LOCAL then? you learn something new every day ...

**Comment by LoneGazebo** [comment]
It's line 1787 in no-EUI CityView.lua...

G

**Comment by TechpriestEnginseer** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/5222

**Comment by LoneGazebo** [comment]
I don’t do modmod edits.
