### ISSUE TITLE
Merchant of Venice does not receive Influence for Mission

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#5225]
?

**Comment by LoneGazebo** [comment]
In VP? It never did, only $$$

**Comment by TechpriestEnginseer** [comment]
![image](https://user-images.githubusercontent.com/13937047/54458947-78a43b80-4722-11e9-9010-89b904b28502.png)
I am certain the Merchant of Venice did provide Influence, but this was removed when CSD Units now provides base influence from the Unit table instead of from the UnitPromotion table. Merchant of Venice was unaffected and lost their influence bonus.

**Comment by LoneGazebo** [comment]
I think that's just a holdover from BNW, they're not supposed to give influence.

**Comment by TechpriestEnginseer** [comment]
oh.
