### ISSUE TITLE
Run Time Error / No Production box

### ISSUE THREAD

**Issue by myles1718** [LoneGazebo/Community-Patch-DLL#5227]
_1. Mod version (i.e Date - 4/23):_

3.14.1b
_2. Mod list (if using Vox Populi only, leave blank):_
List attached in zip

_3. Error description:_ 

Run time error in Improved City View
No Production Box  Unable for city to produce anything
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2974351/Lua.zip)
[xml.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2974352/xml.zip)
[ModInstaller.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2974353/ModInstaller.zip)

_4. Steps to reproduce (optional):_

I disabled Inproved City View Reloaded game and now works perfect
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Did you use the new version I posted?

**Comment by myles1718** [comment]
VP 3-14-1b  Is the version I am using

**Comment by LoneGazebo** [comment]
"Inproved City View" which version of this? I posted a fix for that modmod for users. That's not a standard install.
