### ISSUE TITLE
Prora

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#5228]
_1. Mod version (i.e Date - 4/23):_

2/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I noticed that Prora needs to be in a coastal city. This requirement was removed from the Statue of Liberty, so I think it should be removed from Prora as well, to make things even between the Ideologies.

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
It's literally a coastal resort, tho.

**Comment by Der-Zorn-Gottes** [comment]
I know, but if the SoL can be inland, why could it not be any type of resort?

Mountains are better for holidays anyway.

**Comment by LoneGazebo** [comment]
Ask Hitler.

**Comment by TechpriestEnginseer** [comment]
It's not like the Prora is in need of a buff in its current condition anyway.

**Comment by ilteroi** [comment]
how about "coastal OR mountain"

**Comment by pineappledan** [comment]
If it's such a big deal I would just revert SoL back to coastal only. No leg to stand on then.

**Comment by Der-Zorn-Gottes** [comment]
Well comrade, if we can't have it at least they can'thave it either!
