### ISSUE TITLE
Civilized Jewelers Inc. and office civilopedia effect mismatch

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#523]
![8930_2015-08-17_00011](https://cloud.githubusercontent.com/assets/1131228/9315551/3d1a6a0a-4549-11e5-845d-05f94de8b73d.png)
It says +2g2c to caravansaries and +3g on monopoly resources.
![8930_2015-08-17_00010](https://cloud.githubusercontent.com/assets/1131228/9316289/91d9912a-454d-11e5-943d-3de873a54e92.png)
While actually it is +1g to market/bank/mint/stock exchange without any bonus on monopoly resources.

The similar case with offices, civilopedia says it's gold on resources +5% GP rate per franchise, while actually it's 5% GP rate +5% GP rate per franchise.

**Comment by AnastaseAlex** [comment]
It is the same for twokeyfoods, the offices say +3 food but give +2. It is also unclear how many franchises you have at a given moment, and how much each building is producing in total.

**Comment by Radost** [comment]
The number of franchises is shown in the economic overview.
