### ISSUE TITLE
Future Tech awarding +20 happiness

### ISSUE THREAD

**Issue by ghettospud** [LoneGazebo/Community-Patch-DLL#5230]
_1. Mod version (i.e Date - 4/23):_
2019-3-14 beta

_2. Mod list (if using Vox Populi only, leave blank):_
Unique City States

_3. Error description:_ 
Tooltip for future tech states that it provides +10 happiness to capital
Researching future tech creates two popups on right side
+20 happiness is applied to capital city

Additonally:
Should future tech be adapted to apply empire-wide happiness (and thus spread across cities) like happiness from natural wonders?
Previously, adding future tech happiness to the capital also had the side-effect of countering empire-wide unhappiness. It no longer affects happiness outside the capital, which arguably invalidates the main point of the bonus.

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/2975945/logs.zip)

![20190317170048_1](https://user-images.githubusercontent.com/39657155/54501972-56631700-48f6-11e9-8b3b-092af2976a5b.jpg)
![20190317170151_1](https://user-images.githubusercontent.com/39657155/54501973-56631700-48f6-11e9-833d-7a6ed5e9871c.jpg)
![20190317170159_1](https://user-images.githubusercontent.com/39657155/54501974-56631700-48f6-11e9-99aa-ede6dac6d8bf.jpg)

**Comment by TechpriestEnginseer** [comment]
is fixed
