### ISSUE TITLE
Bug Strange big jump yield in city

### ISSUE THREAD

**Issue by Cat-du-Fromage** [LoneGazebo/Community-Patch-DLL#5231]
_1. Mod version (i.e Date - 4/23):_
March 14th (3-14)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_
Making a AI battle a remark a city with a strange yield behavior (see image below)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/46396184/54518409-792c1480-4964-11e9-86e3-4e1a21973de5.png)

**Comment by Cat-du-Fromage** [comment]
EDIT: by deleting the cash, it seems it's not the table Building_YieldModifiers the problem

**Comment by MoiMagnus** [comment]
Someone on reddit reported a "all the AI gain absurd amount of tech in few turns", so it may be linked.

**Comment by Cat-du-Fromage** [comment]
mmmmmhhh perhaps! i will try to reproduce it, strange about that is that only 1 city have that and even by destroying all building, the bonus is still there.
and there was 0 wonder in the city concerned

**Comment by LoneGazebo** [comment]
I didn’t touch any battle related code. What’s the extra mod?

**Comment by LoneGazebo** [comment]
Any policies or religions?

**Comment by Cat-du-Fromage** [comment]
i used a mod(homemade) for more belief but he didn't take those i added.

mod used:
more unique component
prussia
World wonder expend
Austria-hungary
pontoon for VP

he used the "holy law" recently modified maybe there is a relation but first i will try to reproduce it, and post if it appears again before jumping into conclusion

**Comment by Cat-du-Fromage** [comment]
sooooo... after 10 runs i wasn't able to reproduce it, so maybe some very specific conditions must be reunit

**Comment by TechpriestEnginseer** [comment]
happens when you use save-game compatible updates.
