### ISSUE TITLE
Some oddities with Venice?

### ISSUE THREAD

**Issue by crdvis16** [LoneGazebo/Community-Patch-DLL#5232]
_1. Mod version (i.e Date - 4/23):_
3-14(b?)

_2. Mod list (if using Vox Populi only, leave blank):_
Just VP+EUI!

_3. Error description:_ 
2 things that seem odd to me about Venice (my apologies if either of these are intentional):

1)  When I purchase a CS with MoV it seems that many of its buildings are lost.  I expected that my peaceful purchasing would not result in buildings being lost (I can't remember now if population also gets lost, I'll check that the next time I get a chance to play).  I didn't notice buildings being lost with my initial CS purchases but now that I'm buying CSs in the Renaissance era I notice that after being purchased their city CS drops to ~10 and they immediately start buildings Walls as their first building.  In the city screen for the newly bought puppet I can see things like monument, etc being available to be built so it seems they are losing those ancient era buildings when bought.

2)  I haven't been give the option for a luxury to create WLTKD yet in Venice.  I'm not sure if this is a Venice specific bug or something that can happen to any civ.  All of my puppets show luxuries that can create WLTKD but not Venice all the way through the Renaissance.  I'll keep tracking this to see if it ever fixes itself.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
the first point should be fixed now
