### ISSUE TITLE
Bug demographic stat: Approval

### ISSUE THREAD

**Issue by Cat-du-Fromage** [LoneGazebo/Community-Patch-DLL#5234]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Everyone is at 100% approval when they are not

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/46396184/54722292-78fa6780-4b64-11e9-8ebd-95bc21776037.png)
![image](https://user-images.githubusercontent.com/46396184/54722306-80217580-4b64-11e9-8ed2-ae9d175910c1.png)

**Comment by ricanuck** [comment]
Seconded.
