### ISSUE TITLE
civs keeps declaring war on my vassal then peacing out immediatly

### ISSUE THREAD

**Issue by kilmarta** [LoneGazebo/Community-Patch-DLL#5235]
_1. Mod version (i.e Date - 4/23):_

2-17-3

_2. Mod list (if using Vox Populi only, leave blank):_
Infoaddict 

Wonder race ver 7

_3. Error description:_ 
The Zulu's, that are friendly with me, declare war on the Ottomans (my vassal). This lasts 1 turn, after which they peace out.  Happened multi times

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

video of it happening

https://youtu.be/_SNcmHSR5os?t=288

**Comment by Cat-du-Fromage** [comment]
4th times it is reported, the thing is, a player cannot declare war to the vassal of someone without declare war to the master. BUT since declaring war to a vassal do not trigger the war with the "master" , peace is forced.

**Comment by Padre19** [comment]
In my game someone has declared war on my vassal without I automatically entering the war.....

**Comment by phantommaxwell** [comment]
And I've had times were these same AI want me to go to War with my Vassal.
