### ISSUE TITLE
weird production choice

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5238]
medieval start ...

![image](https://user-images.githubusercontent.com/1358966/54871160-6b392200-4db0-11e9-929d-d02ffb9e01c4.png)

why can they even build a palace? build turns are also very weird ...

**Comment by ilteroi** [comment]
and i see them building publics works *a lot* - is that intended? even when they are under heavy pressure and should be building units instead

**Comment by LoneGazebo** [comment]
public works is pretty heavily penalized, it should only happen if there's not much else to build and the civ is positive GPT. 

G
