### ISSUE TITLE
Technology

### ISSUE THREAD

**Issue by Keshiq** [LoneGazebo/Community-Patch-DLL#5239]
_1. Mod version (i.e Date - 4/23):_
17.02

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi (no EUI), RED mopack, Barbarians Evolved, Hormigas Enhanced Map Pack, YnAEMP DLL 43 civs

_3. Error description:_ 
When I try to research mechanics technology or anythiong that require it, the game crash immediately.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3000255/Logs.zip)

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3000257/CvMiniDump.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Keshiq** [comment]
Oh and infoaddict

**Comment by Vyyt02** [comment]
Mechanics??? There is no such tech in VP. Are you sure you are not using any other mods?

**Comment by Omen-of-Peace** [comment]
Machinery, perhaps?

**Comment by Keshiq** [comment]
First of all I would want to apologize for inactivity but I didn't have time to play and check anything during this few days. Second thing, I have changed my language to english and it is working now perfectly. But it crash on spanish, italian and polish. Yeah machinery, my bad :D I thought that mechanics is how it is called in english. And no, no other mods.
