### ISSUE TITLE
Railroad City Connection and Open Borders

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#524]
![8930_2015-08-18_00002](https://cloud.githubusercontent.com/assets/1131228/9316350/f476a35e-454d-11e5-8c4b-2a8b0c8efd09.png)
![8930_2015-08-18_00003](https://cloud.githubusercontent.com/assets/1131228/9316355/f7828a2c-454d-11e5-861c-6fbce48b3e6c.png)
The territory of foreign civ with Open Borders denies my city from railroad production bonus.

**Comment by LoneGazebo** [comment]
I'll take a look.
G

**Comment by ilteroi** [comment]
don't see an obvious problem in the code. can you provide a savegame?

**Comment by LoneGazebo** [comment]
Radost can answer that for you. The issue seems to be that tiles not owned by the player are breaking city connections even if you have open borders. In the pathfinder check, is it accounting for open borders, or is it only looking at unowned/self-owned tiles?

**Comment by ilteroi** [comment]
it is checking open borders -> see the IsFriendlyTerritory() call in RouteValid()

**Comment by LoneGazebo** [comment]
It isn't breaking the city connection per se, just the railroad bonus. Perhaps the 'industrialrouteconnected' function is the one breaking?

**Comment by ilteroi** [comment]
that's just caching the result from GC.getRouteFinder().GeneratePath() which in turn calls RouteValid()

**Comment by Radost** [comment]
Strangely enough, the railroad bonus appeared when I checked before the end of the game.
https://d.maxfile.ro/hqgquxaseq.Civ5Save - near the end, railroad bonus in place. Btw check #529 if you might.
https://d.maxfile.ro/jdmotqpqej.Civ5Save - turn 492, no railroad bonus.
Mods:
Compatibility EUI + more luxuries
Quick Turns - http://steamcommunity.com/sharedfiles/filedetails/?id=220250184
InfoAddict - http://steamcommunity.com/sharedfiles/filedetails/?id=220250184

**Comment by ilteroi** [comment]
hmm. can't load it because apparently i'm missing some DLC

**Comment by ilteroi** [comment]
it seems railroads are not extended by harbors. so cities on other continents will never get the 25% bonus (which btw is quite high imho). is this by design?

**Comment by LoneGazebo** [comment]
No, it is not. Railroad bonuses should extend to harbors (I see it more as a 'steam power' bonus anyways).

**Comment by Radost** [comment]
> it seems railroads are not extended by harbors.

But they are.
![8930_2015-08-23_00010](https://cloud.githubusercontent.com/assets/1131228/9428598/35b4f9c8-49cd-11e5-8828-c5b43164c7ce.png)

**Comment by ilteroi** [comment]
this is getting curiouser and curiouser

**Comment by LoneGazebo** [comment]
Yellow is correct, IIRC.
