### ISSUE TITLE
Too Much Data in Top Bar - Non-EUI

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#5240]
_1. Mod version (i.e Date - 4/23):_

March 2018

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Non-EUI version - the list of items on the top bar (gold, science, strategic resources, etc...) is too long and wanders past the limited edge of the screen.

_4. Steps to reproduce (optional):_

See attachment.

Thoughts on fixing:  Perhaps the display used in the EUI JUST for the top bar could be transferred to the non-EUI display while everything else is left alone?
![Too Much Data](https://user-images.githubusercontent.com/16022773/54880512-9ad14400-4e1b-11e9-9f0b-3b413a2f8ed8.PNG)

![Too Much Data](https://user-images.githubusercontent.com/16022773/54880499-812ffc80-4e1b-11e9-953e-8f404cb30347.PNG)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Not possible re: EUI, too much is used.

What's your resolution?

**Comment by TechpriestEnginseer** [comment]
and there is too much data in EUI as well.

We could... perhaps take out some of these values, forcing you to hover over the icon to see the yields/turn and yields... but we'll have to take a community poll at that.

**Comment by LoneGazebo** [comment]
Yeah.

**Comment by Gidoza** [comment]
Well I have some thoughts, some of which agree with what you're saying.

-The happiness percentage can be displayed only (and unhappiness/citizens displayed as a hover if you put cursor there)
-The + sign can be removed from science - the font simply turns red if negative and remains blue if positive
-The + sign can be removed from Tourism (Is it even possible to have negative Tourism?)
-The space between Paper and Military Control can be squashed some
-GOLDEN AGE! can be simplified to GA!

**Comment by ilteroi** [comment]
you are not radical enough! the interface needs to be de-cluttered.

* remove the trade route info. it's implicit: if you're at the limit, you can't build any more trade units.
* remove resource info. tradeable resources are in the diplo screen. deficits in strategic resources result in a notification anyway.

**Comment by ricanuck** [comment]
too radical, I... trade route info is useful ESPECIALLY if you are not at limit, plus tooltip is invaluable. Same with resource info.

With that said, I have never had any issue running at 1080p, which seems to be the standard nowadays according to Steam.

**Comment by Omen-of-Peace** [comment]
Perhaps the X/Y for Trade routes can be displayed ONLY when you're not at the limit? When you are, only the Trade route symbol remains.

**Comment by TechpriestEnginseer** [comment]
Actually if we want to be consistent, War Supply is inconsistent.

It should be 0/10 [ICON_WAR] rather than [ICON_WAR] (0/10).

We get to remove two character by doing so.
