### ISSUE TITLE
Minor Tooltip Issue - Archaeological Dig Construction

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5246]
_1. Mod version (i.e Date - 4/23): 3/14 Beta

_2. Mod list (if using Vox Populi only, leave blank): IGE

_3. Error description: If you're trying to construct an Archaeological Dig outside of your territory but do not have the requisite tech to clear a forest/jungle/marsh, the red error tooltip includes the message "A Archaeological Dig cannot be constructed outside of your territory."

It should also be "An" Archaeological Dig, not "A" Archaeological Dig. :P

This error tooltip vanishes once you have the requisite tech to clear the forest/jungle/marsh.

(Yes, I had an Open Borders treaty with Austria)

This wouldn't happen in any ordinary situation (I used IGE as part of trying to show another issue which I'll post soon), but it is still a minor bug - would be useful to fix for certain scenarios, perhaps?

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

**Before Researching Calendar (With Open Borders Treaty)**
![Screenshot (10007)](https://user-images.githubusercontent.com/38794241/55106530-9a4bde00-50a5-11e9-8d82-db63a083e805.png)

**After Researching Calendar (Still With Open Borders Treaty)**
![Screenshot (10009)](https://user-images.githubusercontent.com/38794241/55106557-a9329080-50a5-11e9-82ae-2714b123054f.png)

**Comment by LoneGazebo** [comment]
Can't adjust the article on that because of how it's coded. Other examples allow it, but not the hardcoded stuff.
