### ISSUE TITLE
Feature Request: Allow typing for WC delegate assigning

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5248]
_1. Mod version (i.e Date - 4/23): 3/14 Beta

_2. Mod list (if using Vox Populi only, leave blank): IGE

_3. Error description: Not an error per se, but when you have a large number of delegates, assigning them by clicking repeatedly is irritating and tiring for one's index finger. Is it possible to edit this so that you can simply type in the number of delegates you want to assign?

![Screenshot (10019)](https://user-images.githubusercontent.com/38794241/55112707-8d35eb80-50b3-11e9-8e50-71e73ad048fd.png)

**Comment by LoneGazebo** [comment]
Use shift+click

**Comment by HeathcliffWarriors** [comment]
Oh xD
