### ISSUE TITLE
Communitas map oceans

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#525]
![map](https://cloud.githubusercontent.com/assets/1131228/9317479/4fac3ee4-4555-11e5-90e1-e739b60f5374.png)
I had 2 oceans set with low seal level and narrow ocean rifts. But there is no 2nd ocean.
Even on lowest water settings with 2 oceans there are should be 2 non-crossing lines of 2-3-tile wide ocean tiles going from the north up to the south. Just to be sure no one would be able to get across the globe before being able to cross ocean tiles.

**Comment by LoneGazebo** [comment]
I don't doubt that the communitas map needs some love, but I'm not a map-script writer. You should make a call for help post on the forum.

**Comment by Vyyt02** [comment]
TeenInKay has been playing with the Communitas settings - maybe you can approach him at CivFanatics? I have had the same problem with the map recently, but in my last game, the script generated 2 oceans, so it seems kind of random to me.
