### ISSUE TITLE
Additional Bug in CvDiplomacyAI

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5250]
_1. Mod version (i.e Date - 4/23): 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description:_ 

Line 3742, the first case check for VictoryBlockLevel, has DISPUTE_LEVEL_NONE as the case check, followed by BLOCK_LEVEL_WEAK, BLOCK_LEVEL_STRONG, and BLOCK_LEVEL_FIERCE.

A quick CTRL+F shows that BLOCK_LEVEL_NONE exists elsewhere in the code, and I assume this is a copy-paste bug that makes the AI a little less friendly. :)

**Comment by LoneGazebo** [comment]
It doesn't matter, those are enums which are, in essence, just integers. I can fix it, but you could use integers and it would have the same effect.

G

**Comment by HeathcliffWarriors** [comment]
Also, just to make sure you see it: line 4300 (dogpiling bonus value) is still using the player target value rather than the war projection. Intentional?
