### ISSUE TITLE
"We made a Declarations of Friendship and then declared war on them!"

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5251]
_1. Mod version (i.e Date - 4/23): 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank): Quick Turns, IGE

_3. Error description: Typo

![Screenshot (10045)](https://user-images.githubusercontent.com/38794241/55256433-76b69e00-5233-11e9-885d-8eb8297a9940.png)

**Comment by HeathcliffWarriors** [comment]
Also "Request Help" should probably be changed back to "Demand" when a DoF is ended in this way.

**Comment by LoneGazebo** [comment]
Request Help can't change until after the event is processed.
