### ISSUE TITLE
Files Overriding

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#5252]
Why exactly is each update overriding the changes made in GitHub?

**Comment by LoneGazebo** [comment]
I did a manual merge and then did a force override.

**Comment by TechpriestEnginseer** [comment]
so.

**Comment by LoneGazebo** [comment]
What’s the issue? Did I miss something?

**Comment by TechpriestEnginseer** [comment]
You override a lot of changes that were supposed to be in the game months ago, but now I just can't remember from the tip of my head because the overwriting a file eliminate its history. :thinking:

**Comment by LoneGazebo** [comment]
Let me check and see. I downloaded master and merged it, may have missed something.

**Comment by ryanmusante** [comment]
How many updates in the past were affected?

**Comment by TechpriestEnginseer** [comment]
a lot when one bug has already popped up already
https://github.com/LoneGazebo/Community-Patch-DLL/issues/5269

**Comment by LoneGazebo** [comment]
I think I found it, it was only the CP and CSD stuff missing.

**Comment by ryanmusante** [comment]
@LoneGazebo Thank you, daddy.

**Comment by TechpriestEnginseer** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/blob/master/(3)%20CSD%20for%20CBP/Improvements/Build.xml

looks unchanged?
