### ISSUE TITLE
Bug America's Unique Ability Scaling

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5253]
_1. Mod version (i.e Date - 4/23): 2/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: America's unique ability "Tile purchases grant +20 Production, scaling with era. " doesn't work as intended or the description is wrong, how it actualy works is like this:
Ancient (1 * 20p) -> Classical (1 * 20p) -> Medival (2 * 20p) -> Renaissance (3 * 20p) -> Industrial (4 * 20p) -> Modern (5 * 20p) -> Atomic (6 * 20p)  -> Information (7 * 20p)

As you can see the scaling starts from Classical Era instead of Ancient Era.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
That is how all era scaling works in the game. Not a bug.
