### ISSUE TITLE
Feature Request Double Feature LocalBuildingGoldMaintenanceMod & Trait_NonSpecialistFoodConsume

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#5254]
I was hoping two things might be added as features into the CPP:

1. A local version of the existing GlobalBuildingGoldMaintenanceMod, that only affects the maintenance of the buildings in the same city
_~2. A civ Trait that halves the food consumption of non-specialist citizens~_ **Edit:** Hungry has coded this one already. Yay!

**Comment by LoneGazebo** [comment]
Because of how building maintenance is handled, I can't do 1a.
