### ISSUE TITLE
Suggestion: Allow workers to remove improvements

### ISSUE THREAD

**Issue by ghettospud** [LoneGazebo/Community-Patch-DLL#5255]
Presently, when working on non-freshwater open Tundra or Desert, it is possible to build oneself into a situation where it is impossible to remove a fort or village. On other terrain, it is possible to build other improvements like farms or mines to remove the fort or village, but in situations like the one below, it is impossible to remove either the fort or adjacent village without expending a great person.

Would it be possible to allow workers to simply remove an improvement much like one can choose to remove an existing road?

![20190330162237_1](https://user-images.githubusercontent.com/39657155/55282207-9f12cb00-530d-11e9-9919-b602ab6787fc.jpg)

**Comment by TechpriestEnginseer** [comment]
but if you can't replace it with anything.. why remove it?

**Comment by ghettospud** [comment]
The AI workers placed the town and left fort before I captured the city, and afterwards, I wanted to move the village right one hex onto the railroad hill. I am unable to do so, however, because that tile is adjacent to the existing village, and I am unable to remove that village.

**Comment by LoneGazebo** [comment]
Not feasible for performance reasons.
