### ISSUE TITLE
genghis khan ability

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5256]
don't you think it's a bit too easy to annex city states for him? i'm fine with it if there's a big army on the doorstep of a city state, but it seems to work even when there is no significant military presence around the victim ...

**Comment by LoneGazebo** [comment]
He was debuffed recently, in that there is now a bully penalty for each owned minor CS. So it is harder for him to get each one.

**Comment by ilteroi** [comment]
doesn't seem to work

**Comment by LoneGazebo** [comment]
Depends on how weak the CS is as well.

**Comment by pineappledan** [comment]
@ilteroi, we're discussing this on CFC as well right now. It's not a super fun time seeing Mongolia hoover up CSs and profit massively from it anyways. Even if it were balanced, which I have my doubts about, it could do with a second look.

**Comment by LoneGazebo** [comment]
Yeah don’t try to end around me. :) I see all.
