### ISSUE TITLE
Detect when Public Works is completed.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#5258]
Is there Lua somewhere to detect when a Public Works is completed?

**Comment by ilteroi** [comment]
would it be possible to show the expected effect in the tooltip? ie how many unhappy faces it would remove?

**Comment by LoneGazebo** [comment]
New lua hook added: GAMEEVENT_CityProjectComplete(playerID, cityID, projectID). Fires when a project is completed in a city.

**Comment by pineappledan** [comment]
Did this actually get added? I don't see it in the custom mod options
