### ISSUE TITLE
Inappropriate Warmongering Penalty / Suggestions to Buff City Liberation Slightly

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5261]
_1. Mod version (i.e Date - 4/23): 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank): IGE, Quick Turns

_3. Error description: I created a game, had the Celts declare war on and capture Polynesia's capital, removing it from the game.

Then, I spawned in a Giant Death Robot using IGE, declared war on the Celts, and liberated Polynesia's capital. I did not capture any other Celtic cities, and Polynesia was supposedly out of the game, yet for declaring war and liberating their capital I got a -11 warmongering penalty to Opinion (along with the +200 bonus for resurrecting them).

You'd think they'd be overjoyed if I declared war and resurrected their civilization after they were killed. The war was fought entirely to liberate them and with no other purpose.

I think it's rather silly/unfun for the AI to hate you even slightly for waging war with the sole purpose of liberating their civilization.

Suggested fix:
1. Have dead players not accumulate warmongering penalties when players declare war on their killer.

AND/OR

2. Have players who have lost cities to the player DoW'ed on not accumulate warmongering penalties against the person who declared war (but still for capturing cities).

AND/OR

3. When a player declares war, store a value for that specific war until the player makes peace. If the player who declared war:

- Liberates at least one city without capturing any of that player's cities; reduce all AIs' warmongering penalties by an amount equal to a war declaration.

- Captures a city; if the penalty was previously removed by liberating a city, reinstate the war declaration penalty AND add the captured city penalty for all AIs.

- Does not liberate any cities; no change to the war declaration penalty.

- End storage of the value once the player makes peace (so as to differentiate different wars).

With option 3, wars of pure liberation would not add any opinion penalty for warmongering once you've liberated at least one city. This buffs liberation slightly (and sensibly) from a diplomacy standpoint, and could be especially valuable if the Global Peace Accords resolution is in play.

It's not really warmongering if you declare war simply to liberate cities, and to have any penalty at all for this doesn't make sense to me; especially if, like in this situation, the liberation bonus isn't even enough to offset the penalty for declaring war.

(With India, even after liberating I still had a -18 opinion penalty)

Yes, it's minor, but I think it would be valuable.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

Save and Logs:
[Save and Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3040443/Save.and.Logs.zip)

4. Screenshots (optional):
![Screenshot (10085)](https://user-images.githubusercontent.com/38794241/55508382-c9bf9500-5627-11e9-8bf0-ceb0a67441d4.png)
![Screenshot (10086)](https://user-images.githubusercontent.com/38794241/55508383-c9bf9500-5627-11e9-8683-b7c4eb97ffeb.png)
![Screenshot (10087)](https://user-images.githubusercontent.com/38794241/55508384-c9bf9500-5627-11e9-865f-9fbefd7d7bca.png)

**Comment by HeathcliffWarriors** [comment]
Also worth noting the impact this has in terms of combat penalties, so it's not just opinion that's being affected...

**Comment by LoneGazebo** [comment]
The -11 most likely came from the DOW itself, not much I can do about that. I can null warmonger upon liberation, though.

G
