### ISSUE TITLE
Assorted Typos (Core Text)

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5263]
_1. Mod version (i.e Date - 4/23): 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank): None (found by looking through the repository code)

_3. Error description:

**Community-Patch-DLL/Community Patch/Core Files/Text/CoreText_en_US.xml**

TXT_KEY_DIPLO_NO_CLEAR_WINNER_TT
Cannot add to non-surrendering party in Peace Deal

_Typo:_ Missing period. A period is present in TXT_KEY_DIPLO_NOT_BANK_TT_ONE_LINE, so I assumed this was an oversight rather than a deliberate choice.

TXT_KEY_VOTE_COMMITMENT_REQUEST_2
The upcoming World Congress session is very important to me. I would like to see this resolution passed, and I need your help. Does this offer seem suitable?

_Issue:_ This actually isn't a typo, but the text assumes that the AI wants you to pass a resolution. What if it's asking for a Nay vote?

TXT_KEY_GENERIC_BLOCK_ANNOUNCE_CULTURE_1
Your culture washes over the earth light a carless child, tossing aside anything that does not suit your fancy. Your influence will wane soon enough.

_Typos:_ 
light -> like
carless -> careless

TXT_KEY_GENERIC_ATTACKED_WEAK_WARMONGER_1
We may lack your military strength, however I would rather die a noble death than be a bloody tyrant like you.

_Typo:_ Should be a semicolon before "however" and a comma after it, since it's being used to form a compound sentence. I'm such a nerd. :b 

TXT_KEY_BULLIED_PROTECTED_CITY_STATE_3
Your war against {@1_MinorCivName} is unacceptable. They are under my protection, and I will not tolerate such defiance.

_Issue:_ Text key seems to be for bullying, yet the text is for an attack. Possible error?

TXT_KEY_GENERIC_RESPONSE_SHARE_INTRIGUE_ARMY_SNEAK_ATTACK_KNOWN_CITY_2
I recently learned that {1_PlayerName} has an army headed towards your city of {2_CityName}. Consider this warning a favor, one that I hope you one day return.

_Typo:_ Not exactly a typo...but a "will" between "you" and "one day" would make this flow more smoothly.

TXT_KEY_GENERIC_SWITCHED_TO_AUTOCRACY_2
The new world order of Autocracy is force that cannot be denied. Your decision to join our cause was inevitable, and will lead to a great and triumphant future.

_Typo:_ Should be "a" between "is" and "force".

TXT_KEY_LEADER_RAMESSES_GREETING_POLITE_HELLO_2
The Lord the Nile speaks with you. What do you say in return?

_Typo:_ Should be an "of" between "Lord" and "the Nile".

TXT_KEY_LEADER_HARUN_GREETING_NEUTRAL_HELLO_2
Welcome to Arabia, I do hope the sands were not too harsh for you.

_Typo:_ Comma should be a semicolon, since it's two independent clauses. Nitpicking, but still...

TXT_KEY_LEADER_BISMARCK_GREETING_NEUTRAL_HELLO_2
As Chancellor, I am formally and legally required to welcome you to Germany. So welcome.

_Typo:_ Should be a comma between "So" and "welcome". Nitpicking, but still...(x2)

TXT_KEY_LEADER_ALEXANDER_GREETING_HOSTILE_HELLO_2
Tremble before the might armies of Greece, fiend.

_Typo:_ might -> mighty

TXT_KEY_WASHINGTON_EXPANSION_SERIOUS_WARNING_2
I will not warn you again: you are settling in lands claimed by the United State of America.

_Typo:_ State -> States

TXT_KEY_GENERIC_INSULT_CULTURE_3
You are barbaric and crude. Shall I send one my artists over to show you what real culture looks like?

_Typo:_ Should be an "of" between "one" and "my artists".

TXT_KEY_RESPONSE_DENOUNCE_HUMAN_BELIEVES_ORDER_1
I know that you are trying to cause a worker's revolution in my lands. For my nation's stability and yours, cease this envangelizing of Order at once.

_Typo:_ envangelizing -> evangelizing

TXT_KEY_LEADER_ATTILA_TRADE_CANT_MATCH
I would offer more, but I've spent to much time talking and not enough time pillaging. Is this acceptable?

_Typo:_ to -> too

TXT_KEY_GENERIC_TRADE_CANT_MATCH_NEGATIVE_3
What makes you think we would match you offer, even if we could? This is what we will offer you.

_Typo:_ you -> your

TXT_KEY_GENERIC_TRADE_CANT_MATCH_NEGATIVE_4
An impossible offer that we cannot hope to match. You are simply embarassing yourself, especially if you accept this trade.

_Typo:_ embarassing -> embarrassing

-----
Hope these findings are of use.

**Comment by LoneGazebo** [comment]
Thx. Someone else a long time ago wrote most of these, never checked over them.
