### ISSUE TITLE
Gold handicap value incorrectly reduced

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5264]
_1. Mod version (i.e Date - 4/23): 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank): IGE, Quick Turns

_3. Error description: This bug is also present in Vanilla; the amount of Gold given from the <Gold> value in Civ5HandicapInfos.xml or DifficultyMod.xml is reduced by 33% without explanation.

It's a minor bug, but adding Gold can be useful for people making custom challenges, scenarios and the like - fixing couldn't hurt and probably isn't difficult? Just pointing it out, since no one seems to have done so before.

_4. Steps to reproduce (optional):
![Screenshot (10103)](https://user-images.githubusercontent.com/38794241/55527941-17102680-5669-11e9-875e-c2d93c6e36ac.png)
![Screenshot (10105)](https://user-images.githubusercontent.com/38794241/55527942-17102680-5669-11e9-8aaf-7be168ba6523.png)
![Screenshot (10106)](https://user-images.githubusercontent.com/38794241/55527943-17102680-5669-11e9-8b6c-aa86385798bd.png)

**Comment by LoneGazebo** [comment]
It is modified by gamespeed. Intentional.
