### ISSUE TITLE
Border Growth Points don't show up in border growth calculation

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#5266]
_1. Mod version - 03/28

_2. Mod list (if using Vox Populi only, leave blank):
Inuit civ for Vox Populi

_3. Error description:_ Local culture from tiles/buildings isn't factored into the "borders will expand in X turns" calculation in the city view and city pop-up. This doesn't affect base VP because local culture is only ever used as an instant yield there, but any building or tile which gives constant border growth points won't be used in the calculation.

The border growth points work properly, so it's largely ignorable, but it is a small pain.

**Comment by MoiMagnus** [comment]
See issue #5222
