### ISSUE TITLE
(Musician's) Guilds do not benefit from building production modifiers

### ISSUE THREAD

**Issue by fmgrafikdesign** [LoneGazebo/Community-Patch-DLL#5267]
_1. Mod version (i.e Date - 4/23): 12/18

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description: Musician's guilds do not benefit from building production modifiers like windmill or the expertise policy, despite being listed under buildings.

_4. Steps to reproduce (optional): Queue a musician's guild and a normal building while having the expertise policy unlocked. Compare the production per turn and listed production modifiers for each building.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): -

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): -

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): -

4. Screenshots (optional):
![20190405153722_1](https://user-images.githubusercontent.com/24509324/55631766-1686a580-57b9-11e9-9e08-b98d3f9b130e.jpg)
![20190405153727_1](https://user-images.githubusercontent.com/24509324/55631772-18e8ff80-57b9-11e9-8c7a-0a75f2837d8a.jpg)

**Comment by LoneGazebo** [comment]
That's because they're technically national wonders.

**Comment by fmgrafikdesign** [comment]
Then I'd suggest placing them under that construction category?

**Comment by LoneGazebo** [comment]
I don't have control over those rules, they're managed by EUI. As a rule, any building with a limited # of construction options is treated as a NW by the code, but not necessarily by the UI.

**Comment by fmgrafikdesign** [comment]
Ooh I see, thanks for the info!
