### ISSUE TITLE
Hagia Sofia

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#5268]
_1. Mod version (i.e Date - 4/23):_

3-28

_2. Mod list (if using Vox Populi only, leave blank):_

-

_3. Error description:_ 

After conquering Marrakech, I was astonished that there was already a Church present, since it has forever been on different religion.
Investigating, it claimed that the Church was provided by the Hagia Sofia. However, the Hagia Sofia was build in my capital, Delhi, several hunderd turns ago.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20190406185416_1](https://user-images.githubusercontent.com/16065630/55673349-5b890580-58a7-11e9-8ea8-b2355ce6dbb1.jpg)
![20190406185447_1](https://user-images.githubusercontent.com/16065630/55673350-5fb52300-58a7-11e9-839c-7e133da31dc1.jpg)
[Hagia Sofia.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3050774/Hagia.Sofia.zip)

**Comment by LoneGazebo** [comment]
Probably an event of some type.
