### ISSUE TITLE
City population attribution to lots/specialists algorithm

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#527]
For some reason I cannot connect to the forums since the migrations, so I will talk about this here:

When building a new city with a colonist or a pilgrim, I the population gets sent to specialists slots, hampering the growth of the city.

In general, the way that population is allocated to different specialist slots disregarding high food sources seems a bit strange and forces a lot of micromanagement.

Could we make the algorithm focus on a kind of target population for each era, say 4 or 5 *era and prefer food as long as the city is bellow that threshold, not generating over a certain amount of unhappyness per era (1 per era?) and/or the empire is not unhappy?

**Comment by Radost** [comment]
The needs penalty for the number of cities will be removed in the next version, so it will probably solve the problem of freshly found cities contributing a lot of unhappiness.

**Comment by LoneGazebo** [comment]
Setting 'hard points' like that (i.e. hard values per era) is not a good idea. Allowing the AI to more naturally make choices is far more effective, and scaleable.
G

**Comment by AnastaseAlex** [comment]
however right now, even though my empire sits at 80 happyness in industrial era, the new city works almost all specialists and one person on coal... which will never make it grow unless I manually desactivate specialists and lock growth tiles.

**Comment by LoneGazebo** [comment]
Did you set the city to growth? If not, it won't prioritize growth (naturally).
G

**Comment by AnastaseAlex** [comment]
When I did it did not really select the most obviously food related tiles:
it prefered to get some tiles that had food and other bonuses rather than some of the 4 food 1 hammer lakes.

**Comment by Radost** [comment]
What's your mod list? I don't recall having anything like that.

**Comment by AnastaseAlex** [comment]
I was with infoaddict, more luxuries, cp, cbp, eui_compatibility, csd, civ IV diplo features. However this is with 8/8 version.

**Comment by LoneGazebo** [comment]
I'd upgrade. These kind of issues really haven't been a problem lately.
