### ISSUE TITLE
Happiness not displayed properly

### ISSUE THREAD

**Issue by Handamoose** [LoneGazebo/Community-Patch-DLL#5270]
_1. Mod version (i.e Date - 4/23):_
Vox Populi V3.28

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
 Happiness not displayed properly

_4. Steps to reproduce (optional):_
 Installed VP(EUI) with the 3-28 auto-installer
This issue appears persistent across multiple machines, after verifying cache, reinstalling VP and reinstalling Civilization V and EUI

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Enrico Dandolo_0398 AD-2118.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3051278/Enrico.Dandolo_0398.AD-2118.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20190404212002_1](https://user-images.githubusercontent.com/49128626/55679906-fb16ba00-58e0-11e9-8d93-3264deffdef2.jpg)
![20190404153623_1](https://user-images.githubusercontent.com/49128626/55679912-0669e580-58e1-11e9-8718-e2ea50f1cb87.jpg)
![20190404054756_1](https://user-images.githubusercontent.com/49128626/55679913-0a960300-58e1-11e9-940f-189c7bbe726a.jpg)
![20190404050048_1](https://user-images.githubusercontent.com/49128626/55679916-197cb580-58e1-11e9-9928-49c7ed3d6ec2.jpg)

**Comment by LoneGazebo** [comment]
What’s the issue?

**Comment by Handamoose** [comment]
The numbers displayed are incorrect

**Comment by LoneGazebo** [comment]
No it’s fine. You can’t have more actual happiness than the number of pop in a city. The top tooltip shows you totals unmodified for pop, so you can see growth potential.
