### ISSUE TITLE
War Weariness slow decrease after killing a rival civ

### ISSUE THREAD

**Issue by Omen-of-Peace** [LoneGazebo/Community-Patch-DLL#5272]
_1. Mod version (i.e Date - 4/23):_ March 28

_2. Mod list (if using Vox Populi only, leave blank):_ Unique City-States, Reforestation, Pontoon Bridge + UI mods

_3. Error description:_ Usually War Weariness decreases quite a bit the first turn after making peace.
When I end a war by killing a rival civ, it seems that WW stays at the same level for several turns and only then begins to decrease.

**Comment by TechpriestEnginseer** [comment]
When you kill a civilization, you're not exactly making peace with them...

**Comment by Omen-of-Peace** [comment]
OK, so intended?
If confirmed, I'll close the Issue.

**Comment by LoneGazebo** [comment]
Intended.
