### ISSUE TITLE
No Yields When Clearing Barb Camps Via City Founding

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5273]
_1. Mod version (i.e Date - 4/23): 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank): IGE, Quick Turns

_3. Error description: Adopting Authority is stated to grant Culture when you clear Barbarian camps; in addition a Gold bonus is given for clearing barb camps.

However, if you clear the camp by founding a city next to it, the bonus does not trigger. 

_4. Steps to reproduce (optional):
1. Found a city where the Settler is currently located. Only the bonus from Imperium is added.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

Save and Logs: 
[Save and Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3052035/Save.and.Logs.zip)

Screenshots (optional):
[Screenshots.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3052037/Screenshots.zip)

**Comment by ilteroi** [comment]
true but not a bug - it has always been like that

**Comment by LoneGazebo** [comment]
Word

**Comment by HeathcliffWarriors** [comment]
Alrighty, was worth confirming
