### ISSUE TITLE
Free policy workaround causing issues

### ISSUE THREAD

**Issue by ProtoNoob** [LoneGazebo/Community-Patch-DLL#5274]
**_1. Mod version**
11/21/1

**_2. Mod list (if using Vox Populi only, leave blank):_**
Atlantis III (A civ mod I have made myself, which is part of the problem)
Multi-Mod - (a mod I made myself that has never had any problems)
Convenient start (v. 2) - been using for a long time with no problem

**_3. Error description:_** 
In my civ mod, I add a dummy policy (BE_FRUITFUL_AND_MULTIPLY) to my civ to allow it to reduce the production cost of settlers and start cities with a population of 2.  I am aiming for a agro expansionist civ.  I am able to apply the dummy and it works just fine, but after its application if I go to the policy screen it tells me that I have 999 turns before I can purchase any more (the counter at the top of the main screen seems to be calculating it correctly though.  So, I proceeded to see if it would let me buy one when the main screen counter ran down, and it did... no problem yet.  Then, after I selected my 2nd policy (3rd if you include the dummy one), it told me I effectively had infinite culture and allowed me to buy EVERY policy.

Now, I get that this isn't TECHNICALLY a problem with VP by itself, and I am sure you do not want to put forth the necessary work to allow every kind of mod that works with standard civ5 to work here, but the dummy policy workaround method seems to be used quite often when an effect cannot be applied some other way.  Any chance we can create more robust VP policy code to account for these workarounds? 

Also, if there is another method to achieve this modding goal within VP I am all ears.

Personal Thoughts: seem like some kind of integer overflow or maybe calculations are being done assuming certain values that should not be assumed.

**_4. Steps to reproduce (optional):_**

See Error description.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

[Atlantis Mods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3052213/Atlantis.Mods.zip)

1. Log files: I don't believe I have log files for this.

2. Save game: The save is at turn 0 so you can see the issues that arise right from the start

3. CvMiniDump.dmp file: No Crash

4. Screenshots (optional):  The screenshot I took is few turns in, but show the issue with effectively infinite culture.

Anyways, thanks for your attention.

**Comment by TechpriestEnginseer** [comment]
https://forums.civfanatics.com/threads/dll-various-mod-components.479600/page-77#post-14210926
