### ISSUE TITLE
Opinion Tooltip Bug With Capitulation Treaties

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5278]
_1. Mod version (i.e Date - 4/23): 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank): Quick Turns, Calypso's Colored Religious Icons, Faster Aircraft Animations

_3. Error description: Immediately after accepting a peace treaty including an AI's capitulation, the opinion tooltip for "They are content with your treatment of them as their master." is shown as bright green (I believe this means an Opinion modifier > 10).

This is set back to 0 and white once the AI has their next turn. This bug occurred to me when Persia AND Austria capitulated to me.

Could perhaps be due to shared religion interests (which applies a modifier of either +15 or +20 to opinion, IIRC) but then why is it set back to 0 on the next turn? And Austria didn't have that majority.

Minor bug for sure, but worth pointing out.

![Screenshot (10332)](https://user-images.githubusercontent.com/38794241/55938324-26fbad80-5c09-11e9-9d0b-d3807736cc11.png)
![Screenshot (10333)](https://user-images.githubusercontent.com/38794241/55938325-27944400-5c09-11e9-9d82-3e8a8c3a89d6.png)
![Screenshot (10334)](https://user-images.githubusercontent.com/38794241/55938326-27944400-5c09-11e9-9dae-8113d9bfbac2.png)
![Screenshot (10335)](https://user-images.githubusercontent.com/38794241/55938327-27944400-5c09-11e9-93a7-38dc020eb858.png)
![Screenshot (10476)](https://user-images.githubusercontent.com/38794241/55938329-27944400-5c09-11e9-928e-69d7190e5783.png)
![Screenshot (10477)](https://user-images.githubusercontent.com/38794241/55938330-27944400-5c09-11e9-93a2-d459be1146f2.png)

**Comment by LoneGazebo** [comment]
None of the vassal code runs until the AI has their next diplo turn. Unavoidable.
