### ISSUE TITLE
Double "You Killed My Spy" Interaction Issues

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5279]
_1. Mod version (i.e Date - 4/23): 3/28 Beta, but this is a vanilla bug as well I believe

_2. Mod list (if using Vox Populi only, leave blank): Quick Turns, Faster Aircraft Animations, Calypso's Colored Religious Icons

_3. Error description: When you get the notification that a leader spied on you, you can click on it to have four options: declare war, denounce (if you haven't already), ask them not to spy (if you haven't already), or forgive them.

**Issue No. 1**
However, even if you interact with them and pick one of these options, the leader will still send you a message about the incident giving you a "I forgive you" or a "I don't forgive you" choice, so you end up dealing with a similar popup twice.

**Issue No. 2**
The "I don't forgive you" option seems to be a useless response - which as I recall from an old changelog, VP was trying to avoid. Forgiving them for spying (several times in a row) gives a small Opinion boost IIRC, but "I cannot forgive this" doesn't seem to do anything at all.

So either...forgive them and get advancement towards a slight opinion boost, or...don't forgive them and nothing changes?

Perhaps it's hardcoded, but I'm pretty sure there was a bunch of code about sending diplomatic messages in CvDiplomacyAI, so perhaps something can be done...

**Issue No. 3**
Part of the problem with Issue No. 1: the progression from screenshot 2 to screenshots 3/4 feels very artificial and buggy. Imagine an actual civilization acting like this! :)

![Screenshot (10553)](https://user-images.githubusercontent.com/38794241/55939666-552ebc80-5c0c-11e9-8891-6c1e02db6652.png)
![Screenshot (10554)](https://user-images.githubusercontent.com/38794241/55939667-552ebc80-5c0c-11e9-873b-c662d54b176a.png)
![Screenshot (10556)](https://user-images.githubusercontent.com/38794241/55939668-552ebc80-5c0c-11e9-8f90-b4b3ff2edd49.png)
![Screenshot (10557)](https://user-images.githubusercontent.com/38794241/55939669-552ebc80-5c0c-11e9-8803-4163b7b7a0bd.png)

**Comment by LoneGazebo** [comment]
Option 1 does matter - you don't get a temporary diplo bonus if you choose that, so it can be useful for keeping another civ mad at you for war purposes.
