### ISSUE TITLE
Bletchley Park and National Intelligence Agency do not provide the bonus to the city they were built at

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#528]
![8930_2015-08-18_00012](https://cloud.githubusercontent.com/assets/1131228/9326840/39e56638-45b6-11e5-80fe-0e630ae2ef2e.png)
![8930_2015-08-18_00013](https://cloud.githubusercontent.com/assets/1131228/9326842/3c989ef4-45b6-11e5-9fd5-af20285253f2.png)
![8930_2015-08-18_00014](https://cloud.githubusercontent.com/assets/1131228/9326845/3f1113aa-45b6-11e5-9d49-c95d85230b01.png)

**Comment by LoneGazebo** [comment]
Odd. I'll take a look.
G
