### ISSUE TITLE
"You asked them to not spy on you."

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5280]
_1. Mod version (i.e Date - 4/23): 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank): Quick Turns, Faster Aircraft Animations, Calypso's Colored Religious Icons

_3. Error description: Not _quite_ an error, but "You asked them to not spy" _feels_ unprofessional, just reading it out loud. Every time I read it, I think it should be written "You asked them _not to spy_ on you."

"Not spy" just seems awkwardly/clumsily worded. I feel like there's some kind of grammar rule against it, but I can't come up with anything. Damn it, Firaxis!

This is ultimately just me being OCD, so feel free to ignore me, but nevertheless, do you get where I'm coming from? :b 

![Screenshot (10554)](https://user-images.githubusercontent.com/38794241/55940282-c9b62b00-5c0d-11e9-9b82-006ddc92b6ac.png)

**Comment by LoneGazebo** [comment]
Yes, but not changing it. :)
