### ISSUE TITLE
Archaeologist Typo

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5284]
_1. Mod version (i.e Date - 4/23): 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank): Quick Turns, Calypso's Colored Religious Icons, Faster Aircraft Animations

_3. Error description: Typo

"Requires the Public School in this City."
should be
"Requires a Public School in this City."

![Screenshot (10564)](https://user-images.githubusercontent.com/38794241/55997651-3d494e00-5c89-11e9-9e8a-678e80683c27.png)

**Comment by LoneGazebo** [comment]
ehh
