### ISSUE TITLE
CvDiplomacyAI - Betrayal Checks Don't Include DoW

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5288]
_1. Mod version (i.e Date - 4/23): 3/28 Beta

Early on in GetBestApproachTowardsMajorCiv, there's the following check, which eliminates weight for a current DoF or Research Agreement and adds WAR, HOSTILE and GUARDED bias if this was previously a friend who denounced the AI.

```
// We were friends and they betrayed us!
	if (IsFriendDenouncedUs(ePlayer))
	{
		viApproachWeights[MAJOR_CIV_APPROACH_WAR] += viApproachWeightsPersonality[MAJOR_CIV_APPROACH_WAR];
		viApproachWeights[MAJOR_CIV_APPROACH_HOSTILE] += viApproachWeightsPersonality[MAJOR_CIV_APPROACH_HOSTILE];
		viApproachWeights[MAJOR_CIV_APPROACH_GUARDED] += viApproachWeightsPersonality[MAJOR_CIV_APPROACH_GUARDED];
		viApproachWeights[MAJOR_CIV_APPROACH_FRIENDLY] = 0;
	}
```

I have a simple suggestion: why not factor in IsFriendDeclaredWarOnUs as well? It's objectively a worse form of betrayal and the AI shouldn't forgive it so easily.

Additionally, in my most recent game, America made a DoF with Arabia despite having been backstabbed via a DoW.

I looked through the code section you mentioned when you made that DoF formula post and noticed something:

```

			// We were friends and they betrayed us!
			if (IsFriendDenouncedUs(ePlayer))
			{
				iEnemyWeight += 25;
				iDPWeight += -25;
				iDoFWeight += -25;
			}
```

There's no check for a DoW, only denouncing. Wouldn't it be good to factor in a DoW here as well, for the same reason?

-----

As an additional suggestion, checking for IsUntrustworthyFriend might be a good idea in both of these functions; don't want to be too friendly with people who have denounced multiple friends or DoWed on any friend.

```
/// Has this guy had problems with too many of his friends? If so, then his word isn't worth much
bool CvDiplomacyAI::IsUntrustworthyFriend()
{
	// If you've DoWed any friends, you're a bad person
	if(GetWeDeclaredWarOnFriendCount() > 0)
		return true;

	// If you've denounced at least 2 of your friends, you're the problem
	if(GetWeDenouncedFriendCount() >= 2)
		return true;
```

I think these small changes would help the AI slightly in decision-making.

**Comment by LoneGazebo** [comment]
This is probably because I used to have auto-denounce enabled by default on DOW. At some point I removed that.

G
