### ISSUE TITLE
"Other civs that we like more than you have denounced you!"

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5289]
_1. Mod version (i.e Date - 4/23): 3/28

![Screenshot (10663)](https://user-images.githubusercontent.com/38794241/56085581-b83e7000-5e13-11e9-913a-cbb354c627df.png)

I've seen this modifier only rarely, and I was confused as to why this triggered in some cases and not others. Now that I understand the code a bit more, I went looking.

From what I can tell in my experiment, I believe it's caused by this function.

```
int CvDiplomacyAI::GetFriendDenouncementScore(PlayerTypes ePlayer)
{
	int iTraitorOpinion = 0;
	// How many of their (trustworthy) friends have denounced them?
	PlayerTypes eLoopPlayer;
#if defined(MOD_BALANCE_CORE)
	int iNumPlayers = 0;
#endif
	for(int iPlayerLoop = 0; iPlayerLoop < MAX_MAJOR_CIVS; iPlayerLoop++)
	{
		eLoopPlayer = (PlayerTypes) iPlayerLoop;
		if(eLoopPlayer != GetPlayer()->GetID() && GET_PLAYER(ePlayer).GetDiplomacyAI()->IsFriendDenouncedUs(eLoopPlayer))
		{
			// If this guy is untrustworthy, he doesn't count
			if(!GET_PLAYER(eLoopPlayer).GetDiplomacyAI()->IsUntrustworthyFriend())
			{
				// Do we like this player who denounced them more than the player we're evaluating?
				if(GetMajorCivOpinion(eLoopPlayer) > GetMajorCivOpinion(ePlayer))
				{
					iTraitorOpinion += /*20*/ GC.getOPINION_WEIGHT_DENOUNCED_BY_FRIEND_EACH();
				}

				// We actually more friendly with the player we're evaluating than denouncer
				else if(GetMajorCivOpinion(eLoopPlayer) < GetMajorCivOpinion(ePlayer))
				{
					iTraitorOpinion += /*-10*/ GC.getOPINION_WEIGHT_DENOUNCED_BY_FRIEND_DONT_LIKE();
				}
#if defined(MOD_BALANCE_CORE)
				iNumPlayers++;
#endif
			}
		}
	}
#if defined(MOD_BALANCE_CORE)
	if(iTraitorOpinion > 0 && iNumPlayers > 0)
	{
		iTraitorOpinion = (iTraitorOpinion / iNumPlayers);
	}
#endif

	return iTraitorOpinion;
}
```

While I think the code itself has no issues (that I know of; my knowledge of C++ is limited haha), the modifier has one:

It doesn't explain that it's triggered only by your (trustworthy) friends denouncing you, if they like the friend more than they like you. A player may not understand why they received this modifier sometimes and not other times.

Note: The original tooltip for this in the base game was "Your friends found reason to Denounce you!" - I don't understand why Firaxis in BNW changed it to "Other civs we like more than you have denounced you!" because that's less descriptive of why it actually triggers.

**Comment by LoneGazebo** [comment]
I think it's okay as-is.
