### ISSUE TITLE
Replay doesn't work at the end of the game

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#529]

**Comment by LoneGazebo** [comment]
No idea.

**Comment by LoneGazebo** [comment]
Are you getting any kind of lua errors at this point?

**Comment by Radost** [comment]
In the logs? I'll check them out when I end the current game.

**Comment by LoneGazebo** [comment]
Sounds good.

**Comment by Radost** [comment]
Strangely enough, the replay worked just fine in my latest game.

**Comment by LoneGazebo** [comment]
Good. Perhaps it was simply a quirk.
