### ISSUE TITLE
Sacred Sites + Stupa - Tooltip Issue

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5297]
_1. Mod version (i.e Date - 4/23):_ 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank):_ Calypso's Colored Religious Icons, Faster Aircraft Animations, Quick Turns

_3. Error description:_ The Sacred Sites reformation belief adds an extra +3 Tourism line of text to the Stupa, rather than raising the +5 to +8. As this is not usually the case (e.g. Goddess of Beauty will change the Stonehenge tooltip to make it +4 Faith instead of +2), this seemed like a bug.

![Screenshot (10839)](https://user-images.githubusercontent.com/38794241/56348577-bf0f0f00-6194-11e9-9da7-dbf2767c001e.png)

**Comment by LoneGazebo** [comment]
It's fine, the values are simply managed differently.
