### ISSUE TITLE
Marble + Stone - Tooltip Issue

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5298]
_1. Mod version (i.e Date - 4/23):_ 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank):_ Calypso's Colored Religious Icons, Faster Aircraft Animations, Quick Turns

_3. Error description:_ When you have both Marble and Stone and are building an Ancient or Classical Era Wonder in a city, the entry "Wonder Modifier for Wonder Name" appears twice, rather than combining the modifiers together.

![Screenshot (10694)](https://user-images.githubusercontent.com/38794241/56351309-d3560a80-619a-11e9-814a-4979b7c9539b.png)

**Comment by LoneGazebo** [comment]
Yep, has to be, resources are processed twice.
