### ISSUE TITLE
Can't build an embassy

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#530]
![8930_2015-08-18_00015](https://cloud.githubusercontent.com/assets/1131228/9340335/94e3e210-4608-11e5-9c6e-25e3d3cb7e81.png)
I checked and this is the only city under this CS control. I have a slight suspicion it was located on Oil Well tile before the oil was revealed but then workers replaced it.
On a side note, it would be nice if there was a clear indication of embassies somewhere on CS window. Because it gets hella confusing when city states annexed other cities.

**Comment by LoneGazebo** [comment]
It's definitely not easy, but there's not an easy way to indicate that (as the lua management of banners, tiles, and the map are all done separately, and they don't cross-reference).

As far as why it is doing that, my bet is that the embassy three tiles over is somehow making the CS think it already has one. If you have firetuner, delete that other embassy and see if it lets you make one. If so, I just need to tighten the test a little.

**Comment by Radost** [comment]
Then do something like that archaeologist mod, but outline city-states eligible for embassy? 

Yep, you are right.
![8930_2015-08-19_00003](https://cloud.githubusercontent.com/assets/1131228/9341456/61268322-460f-11e5-9c31-4d827b4ea289.png)

**Comment by LoneGazebo** [comment]
I hate LUA. Is a pain. I'll fix the DLL bug, though I'm not going to worry about the UI issue.
