### ISSUE TITLE
"Demand" button shown in place of "Request Help"

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5301]
_1. Mod version (i.e Date - 4/23):_ 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank):_ Faster Aircraft Animations, Quick Turns, IGE, Calypso's Colored Religious Icons

_3. Error description:_ When requesting help from a friend the "request" button in the trade menu is still labelled "DEMAND".

![Screenshot (10860)](https://user-images.githubusercontent.com/38794241/56353338-292cb180-619f-11e9-8370-cbc37a6f8c53.png)
![Screenshot (10861)](https://user-images.githubusercontent.com/38794241/56353340-29c54800-619f-11e9-8eaf-1abe9cf2b78b.png)

**Comment by LoneGazebo** [comment]
it's fine. it is technically a 'demand.' :) It would require pre-caching a value and I'd rather leave it.
