### ISSUE TITLE
Babylon Trade Dialogue Typo

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5302]
_1. Mod version (i.e Date - 4/23):_ 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank):_ Calypso's Colored Religious Icons, Faster Aircraft Animations, Quick Turns

![Screenshot (10866)](https://user-images.githubusercontent.com/38794241/56353614-c25bc800-619f-11e9-8366-cd78e48f9b4d.png)

our -> out

**Comment by LoneGazebo** [comment]
vanilla
