### ISSUE TITLE
Vassal overview uses default religion name, not custom name

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5304]
_1. Mod version (i.e Date - 4/23):_ 3/28 Beta

_2. Mod list (if using Vox Populi only, leave blank):_ Calypso's Colored Religious Icons, Faster Aircraft Animations, IGE, Quick Turns

_3. Error description:_ The vassal overview screen always displays the default name for the vassal's majority religion, rather than the customized name.

![Screenshot (10868)](https://user-images.githubusercontent.com/38794241/56355106-7e6ac200-61a3-11e9-9a53-93697f354c45.png)
![Screenshot (10870)](https://user-images.githubusercontent.com/38794241/56355107-7f035880-61a3-11e9-92ea-125d9ef9cb88.png)

**Comment by TechpriestEnginseer** [comment]
![image](https://user-images.githubusercontent.com/13937047/56844021-922abe00-685e-11e9-91ce-a7c886833944.png)
