### ISSUE TITLE
Suggestions to improve diplomacy AI re: Vassals

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5308]
_1. Mod version (i.e Date - 4/23):_ 3/28 Beta

I think there may be an issue with the following check.

```
			//we like our vassal.
			if (GET_TEAM(GET_PLAYER(ePlayer).getTeam()).GetMaster() == GetPlayer()->GetID())
			{
				viApproachWeights[MAJOR_CIV_APPROACH_HOSTILE] = 0;
				viApproachWeights[MAJOR_CIV_APPROACH_WAR] = 0;
			}
```

This effectively means that the AI does not factor any of the following in when it comes to declaring war on their vassal:
- Wanted war last turn bias
- Wanted demand last turn bias
- Conquest bias
- War bias for city-state quests to capture, liberate or DoW
- Master denounced vassal
- Vassal was a friend and denounced master
- Vassal denounced master
- Military threat level (severe or critical)
- Warmonger threat level (severe or critical)
- Victory block level (fierce)
- Wonder dispute level (fierce)
- Victory dispute level (fierce)
- Land dispute level (fierce)
- Master is close to domination victory
- Vassal has multiple capitals
- Vassal is close to spaceship, diplomatic or cultural victory
- Master has the lowest influence on them and a stronger military, and is close to cultural victory
- Spaceship, cultural and diplomatic victories being disabled
- Master being cramped
- Nukes

They do factor in the following:
- The player having previously declared their independence by force
- War projection
- Target value
- Military aggressive posture
- Reckless expansion of the target
- Dogpiling
- Duel
- Distance multiplier
- Unique unit / unique unit tech
- The target being the biggest competitor
- Opinion multiplier

I think that not factoring in so many of those factors could result in the AI not declaring war when they have good reason to. This is particularly the case if the vassal still has their original capital, or owns other original capitals, and the master is going for world conquest, and also particularly the case if the vassal is close to victory despite their vassalage.

My suggestion is that if any of the following conditions are true:
- Victory Dispute Level >= STRONG
- Victory Block Level >= STRONG
- The vassal is close to spaceship, diplomatic or cultural victory
- The master is close to domination victory OR is going for world conquest, and the vassal has at least one original capital
- The master is close to cultural victory, has the lowest influence on them and has a stronger military

And the following condition is true:
- If the vassal is removed from the master, the master would have a stronger military than them

Then reduce the war/hostile weight by half instead of removing it entirely for all of those conditions.

(Maybe divide by 3 in the case of being close to cultural victory, or don't factor that one in; there is a +33% tourism modifier against vassals and permanent open borders after all...)

**Comment by HeathcliffWarriors** [comment]
Also, in regards to the dogpiling check, should that value be added to an AI's own vassal? If the other player is at war with the vassal, that means they're also at war with the master.

If the master declares war on their own vassal to dogpile, they could potentially be putting themselves in a situation where they'll lose a large amount of military support _and_ still have the other war to contend with.

**Comment by HeathcliffWarriors** [comment]
Edit to first post: should factor in military strength

**Comment by LoneGazebo** [comment]
I don't want to overcomplicate the logic for the AI with vassals, it'll make them erratic. Easiest is to have the zero weighting only apply if the vassal no longer owns their original capital.

**Comment by HeathcliffWarriors** [comment]
I can see how adding in all of those conditions could overcomplicate things, but what about factoring in if they're close to spaceship, diplomatic, or cultural victory? If a vassal has gotten that far ahead despite their vassalage, they could pose a victory threat.

**Comment by LoneGazebo** [comment]
Fine, but that's extraordinarily rare, if not impossible.

**Comment by HeathcliffWarriors** [comment]
If it's extraordinarily rare, it wouldn't cause erratic behavior, then? :)

**Comment by LoneGazebo** [comment]
It's just wasteful code.

**Comment by HeathcliffWarriors** [comment]
Fair enough, I guess, but if it's a human vassal - take diplomatic victory for example, if you have enough embassies, the right policies, perhaps you built the Palace of Westminster, and you use your spies well, it's possible to build up a decent chance at winning a diplo victory for yourself despite your vassalage, especially on a lower difficulty.

**Comment by HeathcliffWarriors** [comment]
Plus, while you're a vassal you won't be targeted by other AIs, which increases your odds of succeeding at a peaceful victory.

```
	{
		// If we're already at war with this player don't cancel out the weight for them!
		if(!GET_TEAM(GetTeam()).isAtWar(GET_PLAYER(ePlayer).getTeam()))
		{
			if (MOD_DIPLOMACY_CIV4_FEATURES)
			{
				//If a vassal reduce but do not remove the value.
				if (GET_TEAM(GET_PLAYER(ePlayer).getTeam()).IsVassalOfSomeone())
				{
					viApproachWeights[MAJOR_CIV_APPROACH_WAR] = 0;
				}
				else
				{
					viApproachWeights[MAJOR_CIV_APPROACH_WAR] = 0;
				}
			}
			else
			{
				viApproachWeights[MAJOR_CIV_APPROACH_WAR] = 0;
			}
		}
		else
		{
			viApproachWeights[MAJOR_CIV_APPROACH_WAR] += viApproachWeightsPersonality[MAJOR_CIV_APPROACH_WAR];
		}
	}
```

**Comment by HeathcliffWarriors** [comment]
Consider the following scenario:

1. Player A captures Player B's capital.
2. Player C defeats Player A and captures their original capital, then vassalizes them.
3. Player C is going for Domination Victory, yet their approach for WAR and HOSTILE is set very low, they can't be bribed to declare war on their vassal, and they are therefore seriously hindered in their victory plans by the diplomacy AI.

Rather than checking if they no longer have their original capital, would it not be smarter to use iNumCaps from earlier in the function and check if they have more than 0 capitals?

Aside from that, I think the change solves the issue nicely.

**Comment by LoneGazebo** [comment]
You don’t have to own all capitals to win a domination victory, though. Or am I crazy?

**Comment by HeathcliffWarriors** [comment]
BNW changed it to requiring every original capital, about 99% sure that's still the case in VP :P

**Comment by HeathcliffWarriors** [comment]
Tested it just now and it is indeed the case.

![a42343164d01f845e044ce6cebe8eaf2](https://user-images.githubusercontent.com/38794241/57162339-ef24f780-6dbb-11e9-99fd-c2e1f8acfd73.png)

(victory has not been achieved yet)
