### ISSUE TITLE
Morale promotion applies to naval units

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#531]
While Order description specifies "land-only" and Heroic Epic, despite saying "all units", doesn't work on naval units in vanilla game.

**Comment by LoneGazebo** [comment]
Wait, so it does apply to naval units, or you think it should?

**Comment by Radost** [comment]
I worded it wrongly.
Order says "land-only" but still applies the promotion to ships.
Heroic Epic, while saying "all units", doesn't apply it to aircrafts, for example. But applies to ships.
In vanilla game, Heroic Epic says "all units" too, but doesn't apply it to ships.

To be honest, it's better for it to work on land units only, otherwise it forces a military center to be a coastal city for non-Order civs, giving an additional load on it.

**Comment by LoneGazebo** [comment]
Gotcha. Fixed.

**Comment by Radost** [comment]
Actually, I was wrong regarding vanilla Heroic Epic giving the promotion to ships. It does give it.
Still the point of a coastal military center being a must-have still stands.

**Comment by LoneGazebo** [comment]
Yeah, I saw that it gave it in the vanilla game, but it was an irrelevant point to make as I agree, and I've changed it appropriately. Is now land only.
G

**Comment by Radost** [comment]
Btw Heroic Epic description says it's 10% bonus while actually it's 15% and Order doesn't specify "land-only" units.

**Comment by LoneGazebo** [comment]
I'll give it a look. Danke.

**Comment by Radost** [comment]
![10 percent](https://cloud.githubusercontent.com/assets/1131228/9395818/3e310ee0-47aa-11e5-95f5-941f1efb08c0.png)

But that doesn't matter because it is completely broken now. As you can see it isn't shown on the combat preview.
