### ISSUE TITLE
Venice is founding cities.

### ISSUE THREAD

**Issue by Handamoose** [LoneGazebo/Community-Patch-DLL#5311]
_1. Mod version (i.e Date - 4/23):_
 Beta 3-28b

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi(EUI-22 Civs)
3/4UC for VP
Events and Decisions for VP
Civic and Reform
(7) Community Events
Ingame-Editor

_3. Error description:_ 
 It seems the AI Venice is able to obtain settlers to found non-puppeted cities.

_4. Steps to reproduce (optional):_
 Have an AI Venice in-game. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
Did not have logging on.

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Boudicca_0313 AD-2033.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3096576/Boudicca_0313.AD-2033.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20190414160017_1](https://user-images.githubusercontent.com/49128626/56398615-5cab2280-6217-11e9-9955-9cbe5bb10477.jpg)

**Comment by HeathcliffWarriors** [comment]
Was going to report this myself, Venice obtains additional Settlers if they start later than the Ancient Era. Not sure if intentional.

**Comment by LoneGazebo** [comment]
Already fixed.
