### ISSUE TITLE
Major Bug with City Growth

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5313]
_1. Mod version (i.e Date - 4/23):_ 4/20 Beta

_2. Mod list (if using Vox Populi only, leave blank):_ IGE, Quick Turns, Faster Aircraft Animations, Calypso's Colored Religious Icons

_3. Error description:_ I'm gonna just *assume* this isn't intended behavior.

[Save and Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3099807/Save.and.Logs.zip)

![Screenshot (10945)](https://user-images.githubusercontent.com/38794241/56453448-cce99f00-6310-11e9-9033-09af611e5e3b.png)
![Screenshot (10947)](https://user-images.githubusercontent.com/38794241/56453553-053dad00-6312-11e9-99ea-bf860e839266.png)
![Screenshot (10948)](https://user-images.githubusercontent.com/38794241/56453554-053dad00-6312-11e9-9f85-d1bd7d5cfdee.png)

**Comment by HeathcliffWarriors** [comment]
The bug triggered when I got an instant yield of Food from meeting a City-State (when I hit Reveal All).

**Comment by ryanmusante** [comment]
Seeing this on turn 1 first city starvation, standing at -1 growth.
![starving](https://user-images.githubusercontent.com/26808646/56454602-496e9300-638e-11e9-90fb-7597f75fd9ce.png)

**Comment by LoneGazebo** [comment]
That’s weird, can’t reproduce.

**Comment by HeathcliffWarriors** [comment]
I started up another game and couldn't reproduce it either, so I don't think it's an installation issue - perhaps has to do with that non-specialist food modifier?

**Comment by LoneGazebo** [comment]
Maybe. But like I said I can’t reproduce.

**Comment by Stalker012345** [comment]
Not sure if its the same problem, but I'm fighting England right now. Now England has been at the bottom of the totem pole, and I know no why. There capital population....is 1!

England has been beat up a bit by war but I can't see a pop of 1 for the capital by turn 130.

**Comment by nOxrax** [comment]
I see the exact same problem as it is described above. 

I play with 4-20-1 with a new game started on the hotfix. I play Community Patch Only. No mods that could interfer (Tectonic map, advanced setup)


[Wu Zetian_0194 AD-0310.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3115449/Wu.Zetian_0194.AD-0310.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3115450/Logs.zip)

**Comment by Der-Zorn-Gottes** [comment]
I just had the same problem.
In the game before, there were also several AIs who did not found their second city during the whole game. It might be connected with this error (though their capitals somehow got to around 10 pop)

**Comment by HeathcliffWarriors** [comment]
Seems resolved in recent versions, haven't encountered anything at all.
