### ISSUE TITLE
Inuit pull request not correctly merged

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#5315]
The changes to .cpp files from this pull request is not present in your latest version. Error when merging?

https://github.com/LoneGazebo/Community-Patch-DLL/pull/5291/files

**Comment by pineappledan** [comment]
Yeah. Inuit’s broken with the newest merge :(

**Comment by pineappledan** [comment]
Downloaded the newest merge. Trait_NonSpecialistFoodReduction is still not operational

**Comment by LoneGazebo** [comment]
It doesn't exist like that anymore- it's just a 'NonSpecialistFoodReduction' table entry in the base <Traits> table.

**Comment by pineappledan** [comment]
Found it and pushed a new version with the fix. It is working correctly
