### ISSUE TITLE
India Growth Bug

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#5319]
_1. Mod version (i.e Date - 4/23):_
4/20
_2. Mod list (if using Vox Populi only, leave blank):_

4/20 VP + enhanced city view
_3. Error description:_ 

![20190421141221_1](https://user-images.githubusercontent.com/13261433/56474639-0d950580-6442-11e9-80bc-2593c7ae509b.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[AutoSave_0041 BC-2360.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3101528/AutoSave_0041.BC-2360.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TechpriestEnginseer** [comment]
related to this.
https://github.com/LoneGazebo/Community-Patch-DLL/issues/5319
