### ISSUE TITLE
City state heavy tribute yields decrease over time

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#532]
At some point yields even become negative in the city state diplomacy screen:
![8930_screenshots_2015-08-09_00001](https://cloud.githubusercontent.com/assets/12978597/9345637/b31892c2-461b-11e5-9938-ae309ad16e4a.jpg)
However, exctracting such a tribute neither adds nor subtracts any yields.

Mods: CP, CBP, Civ IV Diplomacy, CSD, EUI Compatibility, LUAJIT, IGE (all latest versions).

**Comment by LoneGazebo** [comment]
I don't see this bug. Hmm...

**Comment by LoneGazebo** [comment]
Can't replicate. I added a check to the function to make sure it is positive, though.
