### ISSUE TITLE
No happiness from Colonialism monopolies.

### ISSUE THREAD

**Issue by anders4** [LoneGazebo/Community-Patch-DLL#5320]
_1. Mod version (i.e Date - 4/23):_ 4-20 and 4-20-1 (2019)

_2. Mod list (if using Vox Populi only, leave blank):_Really advanced setup 1.5

_3. Error description:_ Policy Colonialism (Imperialsm tree) does not provide any happiness from monopolies, (not sure on the yields).

_4. Steps to reproduce (optional):_ Play until you have 14 policys while grabbing a lot of land and monopolies.

Logfiles + save from after I won the game hope thats ok.

[Colonialsm.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3109070/Colonialsm.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Works fine for me.

**Comment by anders4** [comment]
Weird, Ive tried in several games and get zero instead of expected 20+ happiness so I guess just my game is broken then.
