### ISSUE TITLE
Black Squares

### ISSUE THREAD

**Issue by ceaviking** [LoneGazebo/Community-Patch-DLL#5322]
_1. Mod version (i.e Date - 4/23):_
4/20

_2. Mod list (if using Vox Populi only, leave blank):_
Additional Ancient Ruins Rewards
Coast and Rivers Yield Gold Again
Custom Advanced Setup Screen
Enhanced Improvements
Enlightment Era
Gibraltar, Reef and Krakatoa Fixes
Ingame Editor
Solar Plant Fix
Speedy Starting Settler
Starting Worker
Terrain - Poor Tiles Tweak
UI - Filter in Trade Route Overview (Vox Populi)
UI - Improved City View (Vox Populi EUI)
Units - No Futuristic Units
Units - Start Scout

_3. Error description:_ 
Black squares randomly appearing

_4. Steps to reproduce (optional):_
Not sure

I saw that this was an issue before but I already have done those steps. My graphics are already lowered all the way. EUI is properly installed. I trimmed my modlist of any incompatible ones and uncessary ones. I do not know what else to do. I included a zip file with screen shot, a bunch of logs (was not sure which one you would need), and a save. Where the yellow square is there should be a two notifications. I am sorry if this is a duplicate, I searched the closed ones. This just started randomly.
[BlackSquares.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3117318/BlackSquares.zip)
![black squares](https://user-images.githubusercontent.com/49987741/56742831-7aaae280-6743-11e9-93a6-23080d2e2928.jpg)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I can't debug unless you are using VP only.

**Comment by ceaviking** [comment]
Fine I'll fix it myself, used to that.
