### ISSUE TITLE
war weariness

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5323]
latest version.

i have two wars going and 20 war weariness. so i make peace with both, but my happiness doesn't change. in fact, the next turn i have 21 war weariness. is that supposed to happen?

**Comment by LoneGazebo** [comment]
IIRC the unhappiness penalty does not cap at the same value as the war weariness cap, so it's possible that, while war weariness goes down, the unhappiness value can stay the same or increase until the war weariness value goes below the unhappiness population cap.

**Comment by ilteroi** [comment]
huh? i know the words but i don't understand ... i want an immediate effect when making peace. can we enforce that in a transparent way?

**Comment by LoneGazebo** [comment]
Look at CvPlayer::GetUnhappinessFromWarWeariness(). It caps war weariness at your pop, but the value created by CultureClasses doesn't care about this, so your 'max real value' can be higher than your cap. This means that the unhappiness value won't change until the max real value comes down below your cap.

**Comment by ilteroi** [comment]
ok, i see,

cleaned up the code a bit and fixed some smallish bugs
