### ISSUE TITLE
No penalties for lacking a strategic resource

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#533]
When you start lacking a strategic resource (say, iron), a popup appears telling that associated units (swordsmen) won't be able to heal. However, they indeed are able to heal.

On a related note, I often find myself mass bying horses from AIs at the time when stockyards come into play and when I'm finished building them, I usually don't renew the deals. As a result, my horse numbers drop into negative values, but it has no impact on the stockyards I've just built, so I just keep ignoring it (which gets harder when there's a popup to remind you about the deficiency every turn). Same applies to coal and seaports/factories/coal plants.

**Comment by LoneGazebo** [comment]
I thought about this (the latter issue) the other day. I added a check which looks for cities over the resource cap. If this happens, building maintenance in your empire will be increased for every building that uses this resource.
