### ISSUE TITLE
Typo: Council of Elders (4/20-2 Beta)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#5332]
_1. Mod version (i.e Date - 4/23):_
4/20-2 Beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Yield mismatch 
gain **30** Science and Production?
gain **60** Science and Production?

https://github.com/LoneGazebo/Community-Patch-DLL/blob/0c2e2e56c6a4ba05ea6cd08385a3b25930ee14a3/Community%20Balance%20Patch/Balance%20Changes/Beliefs/Founder.sql#L134-L138

https://github.com/LoneGazebo/Community-Patch-DLL/blob/0c2e2e56c6a4ba05ea6cd08385a3b25930ee14a3/Community%20Balance%20Patch/Balance%20Changes/Text/en_US/ReligionText.sql#L519-L522

**Comment by HeathcliffWarriors** [comment]
![Screenshot (11451)](https://user-images.githubusercontent.com/38794241/56980114-833b5880-6b49-11e9-8925-31f3eb544741.png)
![Screenshot (11452)](https://user-images.githubusercontent.com/38794241/56980115-83d3ef00-6b49-11e9-8ea1-2413ecaceeec.png)
![Screenshot (11453)](https://user-images.githubusercontent.com/38794241/56980116-83d3ef00-6b49-11e9-9e4f-e3f21859412c.png)

It's always given me 60.

**Comment by TechpriestEnginseer** [comment]
I'm assuming the # of city by default is 1 and adds by +1 including the Capital.

**Comment by HeathcliffWarriors** [comment]
It starts at 60 and for each subsequent city it adds a bonus.
