### ISSUE TITLE
why is happiness capped at 100%

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5333]
right now, happiness cannot exceed 100% ... why is that? allowing values >100 would give the player a sense of the "buffer" they have, even if there aren't any bonuses attached to it.

**Comment by LoneGazebo** [comment]
Because happiness % in the new system = ‘approval’ and > 100% approval feels like a banana republic :)

**Comment by ricanuck** [comment]
Hey! I was born in a hyperbanana dictatorship, and not even there was approval > 100%, even if the dictator dreamed of it (the dead had voting rights, anyways).

**Comment by ilteroi** [comment]
that is a strange thing to say about a game where archers can shoot across the english channel ...

**Comment by LoneGazebo** [comment]
It's an abstraction of public opinion. I don't see how it would be possible to have > 100% approval. :)

G

**Comment by ilteroi** [comment]
well i don't want to blow this out of proportion, but mathematically the number is simply the ratio between happy and unhappy citizens. there is no necessity to give it any additional meaning or institute arbitrary caps which hide information from the user.

**Comment by LoneGazebo** [comment]
I understand the math behind it, but flavor-wise and flavor-text-wise the natural cap of 100% fits the model of unhappiness stemming from dips in approval rating. I'm not strongly attached to it, but I also think it's a clean way of managing the interface (while also keeping players from wondering if there are any bonuses to going above 100%, etc.).

G

**Comment by ricanuck** [comment]
It's not really the ratio between happy and unhappy (that was my first understanding too), but what proportion of the unhappy citizens is "covered" by happiness-inducing elements.

**Comment by TechpriestEnginseer** [comment]
My better question is why is happiness capped at the Capital, it's probably one of the #1 sources of happiness. It should be uncapped and any overflow of happiness from the Capital then gets added to the Empire Total divided by # of Cities.
