### ISSUE TITLE
Auto-Production Should Be Integrated or Distributed

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#5334]
https://forums.civfanatics.com/resources/auto-production-cities.27467/

This mod has been a noticeable QOL to everybody and is not as performance-demanding compared to the other UI mods.

I propose we integrate one of these mods into the VP or make one for ourselves.

**Comment by ryanmusante** [comment]
What does the governor focus on for builds?

**Comment by TechpriestEnginseer** [comment]
Whatever the AI thinks is useful according to the advisor's recommendations, It'll train units or process if it has to.

There's no focus-oriented, but it will make your life easier at late game.

**Comment by ryanmusante** [comment]
This should be integrated along with the condensed top bar as QOL.
