### ISSUE TITLE
Russia kills themself

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#5335]
_1. Mod version (i.e Date - 4/23):_

4/20
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

It's late Rennaisance/early Industrial, and Russa has starver most of its cities down to size 1, or very little. Other civs seem to do fine.
Could be related with issue 5313?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20190501122955_1](https://user-images.githubusercontent.com/16065630/57029331-b52fe600-6c41-11e9-937b-ca66197e03f5.jpg)
[Russia.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3135218/Russia.zip)

**Comment by LoneGazebo** [comment]
on the hotfix?

**Comment by Der-Zorn-Gottes** [comment]
...no.

**Comment by LoneGazebo** [comment]
RIP
