### ISSUE TITLE
AI doesn't value strategic resource quantity when trading

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#534]
Let's say I want to buy open border treaty from an AI. I have some horses and some iron. The AI will sell me his open borders for 1 horse and 1 iron. However, it will not agree to sell them for any quantities of iron without horses and vice versa, not even for 10 of any resource alone. This makes strategic resources non-flexible in trade.

Besides, it's almost impossible to sell strategic resources to an AI, at least in the early game. I couldn't get a friend to buy horses from me even for 1 gold (not gpt, mind you). AI seems to value them very low.

**Comment by LoneGazebo** [comment]
Yeah, there was a bug. I fixed.
