### ISSUE TITLE
Request to clean up the Corporations tech button

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#5342]
I have a QOL request to make. Would it be possible to:
1) Remove icons and tooltips of individual corporations from the Corporations tech. 
![image](https://user-images.githubusercontent.com/12978597/57235917-a45de680-702c-11e9-92a0-e6b2fb8bef3a.png)
![image](https://user-images.githubusercontent.com/12978597/57236123-0585ba00-702d-11e9-8a44-a525430ce719.png)

2) Make it so that right clicking the 'Enables Corporations to be founded' button takes you to this pedia page:
![image](https://user-images.githubusercontent.com/12978597/57236172-1afae400-702d-11e9-9157-5f4b42bae004.png)

I can personally manage to do 1), but 2) is beyond my know-how, so that's part of why I'm asking here. Another one is that, AFAIK, overwriting lua files is a nightmare for compatibility between mods, so a personal modmod is not really an option.

My real reasoning is that all the corporations don't fit there anyway, so it looks incomplete with just the ones that do. Now I realize that by itself it's not a huge issue, and what I'm going to next is purely selfish, so please excuse me. The thing is that my modmod that shifts things around to make the tech tree look cleaner (Tidy Tech Tree) becomes limited - previously I used to place 4 tile improvement yield changes on the Corporations tech, so it would look like this:
![image](https://user-images.githubusercontent.com/12978597/57236637-3b776e00-702e-11e9-957d-72d3aa020054.png)
However, in some version of VP these individual corporations reappeared there and squeezed everything out. 

I realize my proposition ain't pretty, but at least by linking the 'Enables Corporations to be founded' button to the pedia, players would still have practically the same accessibility to corp info as now. ATM right clicking any of the corporations on the tech tree also takes you to the same part of the pedia. Besides, there's a whole separate menu for all the corporations beside the pedia, so that's why I believe removing them from the tech tree wouldn't be such a big detriment.

By the way, this is related to the ticket 'Corporation tech tree items' (#2106). I can't link it properly here for some reason, but it's searchable. From the discussion there, it seems to me that Putmalk's original decision to implement the 'Enables Corporations to be founded' button had similar reasons to mine, which is reduce the tech button clutter be not displaying individual corporations.

P.S. As always, kudos to the team for excellent and relentless work on the project.

**Comment by LoneGazebo** [comment]
I feel like this is a personal preference issue - for all other aspects of the tech tree, all unlocked items are listed. Corps should follow that rule.

**Comment by Edaka** [comment]
Yeah, what I asked in point 1) is mostly a matter of personal preference, as you said, and it's also pretty intrusive. That's why I initially hesitated to ask and I won't press that on that particular issue any further.

However, I think my request in point 2) wouldn't be nearly as intrusive, and it would even add consistency, if anything. (At this point in time right clicking that icon takes you to an irrelevant pedia page). If it was possible, I'd be able to add 1) into my modmod myself with little issue. I just couldn't figure out how to do 2) in lua (I'm a lua n00b). If @Gazebo is still hesitant to add 2) into VP, I plea for help to the lua wizards to show me the way.

**Comment by LoneGazebo** [comment]
@Edaka I don't think you can hook into individual pages of the civilopedia like that without some kind of database hookup to tell the UI where to go, which we don't have in this instance.

**Comment by Edaka** [comment]
Oh, too bad. I mean, it's not that big of a deal. If only someone like @Enginseer could just swoop in and effortlessly do such a thing like it's nothing... but unless that's possible, this ticket can be closed.
