### ISSUE TITLE
Ranged combat does not benefit from Defender of the Faith / Anti-Warmonger Fervor

### ISSUE THREAD

**Issue by gaming-belisarius** [LoneGazebo/Community-Patch-DLL#5346]
_1. Mod version (i.e Date - 4/23):_
 2-17 (2019)

_2. Mod list (if using Vox Populi only, leave blank):_
VP components 1-7b with EUI
(rest of the mods should have no influence on the issue?)
Civ names by policies
R.E.D.
Global relations
Meaningful city state colors
Faster Aircraft Animations

_3. Error description:_ 
While planning to attack with a **ranged unit** (inside friendly territory for Defender of the Faith):
Combat preview shows the bonuses for 
* Defender of the Faith
* Anti-Warmonger Fervor

as appropriate but they are not calculated to the combat strength in the preview. Actual damage is low too so the issue is not only visual.

The bonuses are calculated and shown for melee units however. I am playing as the Inca.

_4. Steps to reproduce (optional):_
Check the combat preview UI with the above conditions.

---------------------------
![combat-normal](https://user-images.githubusercontent.com/50377236/57328302-bff2eb00-7119-11e9-93b6-7fcc3c77732f.jpg)
![combat-fervor](https://user-images.githubusercontent.com/50377236/57328311-c41f0880-7119-11e9-83da-f0a255b546d7.jpg)
![combat-defenderAndFervor](https://user-images.githubusercontent.com/50377236/57328318-c719f900-7119-11e9-8660-311b44dbc253.jpg)

[edit: better markup]

**Comment by LoneGazebo** [comment]
Those values apply based on the target tile, not the occupied tile. So if you shoot someone outside of your land, you don't get the bonus, etc.

**Comment by Edaka** [comment]
I think OP is saying that when the values should apply, they are indeed shown correctly in the combat preview, but they don't affect the actual damage calculations.  If you look at all three screenshots, the 'YOUR STRENGTH' value is the same in all three despite different modifiers.

**Comment by LoneGazebo** [comment]
@ilteroi recently added caching to the check function for unit strength - I don't imagine it is the cause, but he's most familiar with that section of the code. The LUA looks correct, however.

**Comment by ilteroi** [comment]
i have a hard time interpreting those screenshots ... who is attacking whom from where?

anyway, this seems to be the relevant piece of code
```
		// Bonus for fighting in one's lands
		if (pMyPlot->IsFriendlyTerritory(getOwner()))
		{
			iTempModifier = getFriendlyLandsModifier();
			iModifier += iTempModifier;

			// Founder Belief bonus
			CvCity* pPlotCity = pTargetPlot->getOwningCity();
			if (pPlotCity)
			{
				ReligionTypes eReligion = pPlotCity->GetCityReligions()->GetReligiousMajority();
				if (eReligion != NO_RELIGION && eReligion == eFoundedReligion)
				{
					const CvReligion* pCityReligion = pReligions->GetReligion(eReligion, pPlotCity->getOwner());
					if (pCityReligion)
					{
						CvCity* pHolyCity = NULL;
						CvPlot* pHolyCityPlot = GC.getMap().plot(pCityReligion->m_iHolyCityX, pCityReligion->m_iHolyCityY);
						if (pHolyCityPlot)
						{
							pHolyCity = pHolyCityPlot->getPlotCity();
						}
						iTempModifier = pCityReligion->m_Beliefs.GetCombatModifierFriendlyCities(getOwner(), pHolyCity);
						iModifier += iTempModifier;
					}
				}
			}
		}
```

so the bonus depends on the attacker's plot, not the defender's plot, but i don't see how this can go wrong? 

unrelated question: i don't remember ever having seen this holy city check. is this a recent addition? anyway it's pretty heavy for combat simulation, do we really need this?

**Comment by Edaka** [comment]
@ilteroi OP seems to have the same unit (heavy skirmisher) selected in all 3 screenshots. So, on the 1st one he's attacking a Japanese spearman - here we have just some regular modifiers, "YOUR STRENGTH" is shown to be 27.3. On the 2nd one he's attacking a Hunnic unit outside OP's borders - in addition to the previous modifiers, the anti-warmonger modifier shows up in the UI, but "YOUR STRENGTH" is still the same for some reason. Finally, on the 3rd screenshot he's attacking a Hunnic unit inside his borders, so the defender of faith modifier also shows up in the UI, but the strength remains the same. 

Judging by these, it could it be that both the defender of faith and the anti-warmonger modifiers weren't hooked up? 

Sorry for the necro, hope you've already squashed the bug in its entirety.
