### ISSUE TITLE
Combat preview ranged defence numbers wrong when attacking from a city (and in general)

### ISSUE THREAD

**Issue by gaming-belisarius** [LoneGazebo/Community-Patch-DLL#5347]
_1. Mod version (i.e Date - 4/23):_
 2-17 (2019)

_2. Mod list (if using Vox Populi only, leave blank):_
VP components 1-7b with EUI
(rest of the mods should have no influence on the issue?)
Civ names by policies
R.E.D.
Global relations
Meaningful city state colors
Faster Aircraft Animations

_3. Error description:_ 
(vs. ranged attack) Combat preview defender combat strength is very much off when an attacking ranged unit is inside a city. However, this has no effect on the combat preview expected damage calculation. In addition, city bombardment preview results into yet another defense strength. What part of this is intentional, which numbers are correct? Plus lots of invisible bonuses causing added confusion.

I am aware that ranged defense uses the ranged strength value (instead of combat strength). This is assumed below.

Composite bowman (Conscription & Accuracy I) in plains, defense value:
vs. city: 14.3 (= 13 x 1.1, as expected by shown bonus of 10%)
vs. ranged unit outside: 16.9 (= 13 x 1.3, 20% invisible bonuses from promotion Accuracy I ?)
vs. ranged unit garrisoned: 29.9 (!) (= 13 x 2.3 as above plus invisible 100% bonus ?)

Another composite bowman with Bombardment I&II & Morale in plains: 
vs. city: 15.6 (= 13 x 1.2 as expected by shown bonus of 20%)
vs. ranged unit outside: 18.2 (= 13 x 1.4, shows 20% bonus, 20% invisible)
vs. ranged unit garrisoned: 29.9 (= 13 x 2.3, ?? how is it the same as above?)

Applies to composite bowman defender but not a horse archer defender:
Horse archer defense (accuracy I&II):
vs. city: 15.4 (= 14 x 1.1)
vs. outside unit: 21 (= 14 x 1.5, 40% total invisible bonuses - accuracy I&II = 40? + 10% from where?)
vs. garrisoned unit: 21 as well

_4. Steps to reproduce (optional):_
Compare combat preview numbers while the attacking unit is inside/outside a city.

---------------------------
![combat-city](https://user-images.githubusercontent.com/50377236/57329623-d8b0d000-711c-11e9-965f-d41afabd3ac9.jpg)
![combat-outside](https://user-images.githubusercontent.com/50377236/57329634-db132a00-711c-11e9-9c42-0ebc2ed10a80.jpg)
![combat-bombardment](https://user-images.githubusercontent.com/50377236/57330829-d1d78c80-711f-11e9-93e4-db062ebfecb0.jpg)

**Comment by ilteroi** [comment]
should be fixed
