### ISSUE TITLE
Stacked Ships - Can't move it, can't delete it

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5349]
_1. Mod version (i.e Date - 4/23):_
4/20

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In my current game I am now completely stuck because of a stack unit issue. I have a cruiser and ironclad in the same city (the cruiser just finished producing). Because of an enemy ship I cannot move either ship, and there is not option to delete either ship. So the game is now completely frozen, as it won't let me move forward without moving one of the stacked units.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/57428736-51805c80-71ef-11e9-94ee-e6a6de5428d1.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi should we have a check to prevent this somehow?

**Comment by ilteroi** [comment]
i think this is because you can't delete units in danger anymore - should be easy to allow it in cities anyway
