### ISSUE TITLE
Multiplayer hard desync due to AI war and information Delay

### ISSUE THREAD

**Issue by Cat-du-Fromage** [LoneGazebo/Community-Patch-DLL#5350]
Since the last version of VP we had lot a desync due to AI (Major/barbarians), we saw strange behavior when the informations seen by players where different from each player(for exemple, one saw the declaration of war and the others don't or the tile attacked by an AI is different from a player to an other) but after the desync everyone have the same information.

But we sure saw that there is a problem when information goes to every players.
i Tried different Modpack (one with VP only) but the problem remain.

One thing is certain, The Combat involving an AI is the key problem.
_4. Steps to reproduce (optional):_
make an multipalyer game with 4-6 players and make minimum 100 turns

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Sorry, but there's no effective way for us to debug these sorts of issues, as we have no access to the civ netcode.

G
