### ISSUE TITLE
REQUEST - return the exact yield deficits in city unhappiness ui

### ISSUE THREAD

**Issue by kawyua** [LoneGazebo/Community-Patch-DLL#5351]
_1. Mod version (i.e Date - 4/23):_
4/20 BLAZE it 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Requesting to get exact numbers on the yield deficits i need to stop a city from being unhappy. Like it was before. Why was this ui changed to obscure how much i need to get a city to be happy? I can see that there is that additional information of happiness deficits and stuff, but why did the yield deficit have to go because of it? This ui was my only reliable feedback on the effects on how constructing buildings and researching techs are affecting the happiness of my cities. I don't know how to translate happiness deficits to their associated yield deficit. I'm having difficulty understanding the new happiness system, and feeling lost without those numbers
---what the ui looks like now for city unhappiness----
![cityunhappy](https://user-images.githubusercontent.com/12496046/57512052-a8159580-72d8-11e9-8280-a49caa7f66c0.PNG)

_4. Steps to reproduce (optional):_
just a returning player feeling lost

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
You don't need that information anymore, for two reasons:

% modifiers are now a peripheral target, as most buildings just reduce unhappiness by a flat amount.
You can easily get that number, the deficit value is per citizen, so 2x4 = 8

G

**Comment by MoiMagnus** [comment]
The fact the the deficit is "one yield per citizen per unhappiness" should probably be written somewhere in the tooltip.

**Comment by kawyua** [comment]
thanks that makes a lot of sense. being written on a tooltip is a good idea, too

**Comment by LoneGazebo** [comment]
not enough room. This is what it is.
