### ISSUE TITLE
AI not upgrading units in circumstances where they REALLY should

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5352]
_1. Mod version (i.e Date - 4/23):_ 4/20-2 Beta

_2. Mod list (if using Vox Populi only, leave blank):_ IGE + UI mods

I set up a game with some ridiculous difficulty settings just for fun. AI had no maintenance costs, 999 happiness, 1% of normal production and growth costs, 1% of normal research costs, etc.

As part of these settings I set unit upgrade costs to 0% of normal, so unit upgrades cost no Gold whatsoever.

Yet, despite the fact that upgrades were completely free, both players had Gold stockpiles in the tens of thousands and that they had technologies far beyond the unlocked units, it took a long time for Montezuma to upgrade a catapult and spearman...and later on he had an unupgraded archer while both players had nukes.

This is hardly an ordinary circumstance but I think it highlights an issue with AI unit upgrading, haha.

![Screenshot (12039)](https://user-images.githubusercontent.com/38794241/57559406-a20ecb80-734f-11e9-9ebb-fb18237988b3.png)
![Screenshot (12046)](https://user-images.githubusercontent.com/38794241/57559407-a20ecb80-734f-11e9-8841-cfa4facd4c8a.png)

**Comment by TechpriestEnginseer** [comment]
when something is 0, it can mess up the ai calculation.

You should probably set the cost to 1 or something.

**Comment by HeathcliffWarriors** [comment]
I figured it might have been some kind of issue with a division by zero or something of that nature, but note all the other upgraded units surrounding them.

**Comment by TechpriestEnginseer** [comment]
Are you sure they were upgraded and not trained?

**Comment by HeathcliffWarriors** [comment]
Here's the same Archer earlier in the game, next to an upgraded Jaguar (it has the Heals 25 Damage If It Kills a Unit and Combat Bonus in Forest/Jungle promotions).

![Screenshot (12052)](https://user-images.githubusercontent.com/38794241/57560718-c2418900-7355-11e9-9bc0-4bbf767fbf24.png)

**Comment by HeathcliffWarriors** [comment]
In my latest game (no stupid settings, I did a fresh reinstall), the Celts (Renaissance Era) are fending off my assault of Cuirassiers, Cannons, Musketmen and Tercios with...Pictish Warriors. Who died quite easily, I might add.

I mean I get it's their UU but STILL, it can't be that worthwhile to keep around. :S

**Comment by ilteroi** [comment]
check the logs ... should be in homeland ai.

from looking at the code, they will upgrade a number of units (depending on flavors) per turn. as long as they have money.

**Comment by LoneGazebo** [comment]
I worked on this. Should be better. Removed the dumb flavor blocker.
