### ISSUE TITLE
Corvettes crash the game.

### ISSUE THREAD

**Issue by RinderaGraem** [LoneGazebo/Community-Patch-DLL#5355]
_1. Mod version (i.e Date - 4/23):_
Mods_VP_2019-02-17_no-EUI (I'm using a modpack)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The game crashes when an undamaged corvette attacks any other damaged ship. I'm experiencing the error in the multiplayer mode (even if I'm alone) and can't test in the single player mode.
Damaged Corvette vs. Damaged Ship — OK
Damaged Corvette vs. Damaged Ship — OK
Undamaged Corvette vs. Undamaged Ship — OK
Undamaged Corvette vs. Damaged Ship — CTD

_4. Steps to reproduce (optional):_
- load the attached save file in the multiplayer mode;
- kick the team 2 player (The Huns);
- swap to the Attila;
- load into the game and attack a caravel near the Klapeida city with an undamaged corvette.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3169400/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Atilla_0669 AD-1548.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3169399/Atilla_0669.AD-1548.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
The game doesn't create a dmp file for some reason.

4. Screenshots (optional):
DLC folder https://live.staticflickr.com/65535/33949762018_8445e5c346_o.png

**Comment by ilteroi** [comment]
maybe there were some special promotions involved?

**Comment by RinderaGraem** [comment]
Maybe you're right. I cannot reproduce it either in the single player with low level corvettes. But in the attached save file it 100% reproducible.
Promotions: Navigator II, Statue of Zeus, Himeji Castle, Dreadnought II, Dreadnought I. 
https://live.staticflickr.com/65535/40926192553_7e4f29c010_o.png
