### ISSUE TITLE
Issue with over -100% growth modifiers

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#5358]
On 4/20 I'm getting an interesting interaction with negative growth modifiers. First of all, to establish ground rules: if I understand correctly, a -100% modifier means all growth is stopped and going over -100% means starvation in all cases.

Now, in the screenshots below I have -105% (2 sources: unhappiness and going over supply cap).  Naturally, I want the city to starve as little as possible, so I try to work the most food heavy tiles and unassign all specialists. Turns out doing that makes the city starve even more.

Screenshot #1. 
Food base:  72. Food consumption: 13 pop, 4 of those are specialists, so that's 9x2 + 4x4 = 34 food consumed. Apply the modifiers, ???, -2.26 total. 
![20190512192737_1](https://user-images.githubusercontent.com/12978597/57585291-00be7b80-74ef-11e9-8613-a1d0c440c190.jpg)

Screenshot #2:
Same city, same turn. Food base: 89. Food consumption: 13 pop, no specialists, so that's 13x2 = 26 food consumed. **-3.59 total?!**
![20190512192728_1](https://user-images.githubusercontent.com/12978597/57585297-087e2000-74ef-11e9-86b8-e944447bd018.jpg)

Basically, it seems that with over -100% food modifiers the more food you produce, the more you starve. That's a little counterintuitive, because to avoid starvation as much as possible, I had to do this:
Screenshot #3:
![20190512194737_1](https://user-images.githubusercontent.com/12978597/57585299-0caa3d80-74ef-11e9-831e-cb3dca1f906f.jpg)

I don't know the best way to do it, but since it looks that negative modifiers modify base food values, perhaps they should affect food consumption values instead? For example, -105%  would nullify all base food (-100%) and then subtract 5% of food consumption on top? 

Ideally, I'd like it if producing more and consuming less food (working food tiles and unemploying specialists, respectively) meant the least starvation, but my proposed change would only address consuming less. As it works now, though, the most optimal strategy is matching production and consumption exactly (as in screenshot #3), so there's almost no point in working significant amount of food tiles.

**Comment by ridjack** [comment]
Was this fix included in the the 6/12 version? Issue's still open, but G added the "fixed" tag on 5/14.

I think I ran into it in my last game: https://i.imgur.com/uMtuHq3.jpg
