### ISSUE TITLE
Owned hand-axes retreat before melee

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#536]
Hand-axes you can get when playing as the Huns retreat before melee when attacked. However, they have no promotion that indicates them having that ability and barbarian hand-axes never do that, either.

**Comment by LoneGazebo** [comment]
I'unno. Sure it isn't a mod?

**Comment by LoneGazebo** [comment]
I can't replicate this, so I assume it is a mod-conflict issue.
