### ISSUE TITLE
Incorrect Penalty Tourism from Cities

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5361]
_1. Mod version (i.e Date - 4/23): February 17th (2-17)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

The tourism penalty is not calculated correctly, shouldn't be something like this:
(capital (no penalty) + puppet cities (no penalty) + annexed cities (7)) * 7% = 49%

But in every cities the penalty displayed is 56%, I don't know if just the displayed number is wrong, the calculation or something else

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Kamehameha_0345 AD-1925_bug2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3172790/Kamehameha_0345.AD-1925_bug2.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0005](https://user-images.githubusercontent.com/49090452/57620797-82b3b080-7592-11e9-967b-3233713df3c1.png)
![Civ5Screen0006](https://user-images.githubusercontent.com/49090452/57620803-85aea100-7592-11e9-98a0-0e8ea140b88f.png)

**Comment by LoneGazebo** [comment]
Capital counts.

**Comment by Aqinu** [comment]
I loaded an older savefile and the capital city doesn't count towards tourism penalty, something triggered the wrong calculation

![Civ5Screen0007](https://user-images.githubusercontent.com/49090452/57633161-c535b700-75ab-11e9-9a73-67c46507eddf.png)
![Civ5Screen0008](https://user-images.githubusercontent.com/49090452/57633164-c6ff7a80-75ab-11e9-9803-370634977db3.png)
