### ISSUE TITLE
Siam UA Overrides CS Meeting Bonuses

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5363]
_1. Mod version (i.e Date - 4/23):_ 4/20-2 Beta

_2. Mod list (if using Vox Populi only, leave blank):_ Quick Turns, Archaeology Aesthetic Adjustments, Calypso's Colored Religious Icons, Faster Aircraft Animations

_3. Error description:_ Siam does not receive +influence meeting bonuses from City-States, its UA overrides it and sets it to 40. This is a rather significant bug for Siam, because the extra turns of being friends can mean an important amount of early yields (faith, culture, food, etc.)

_4. Steps to reproduce (optional):_ Have Siam meet a City-State that gives them influence as an early meeting bonus.

![Screenshot (12164)](https://user-images.githubusercontent.com/38794241/57627969-09529880-7567-11e9-95ab-922f1b513c4c.png)

**Comment by LoneGazebo** [comment]
Not a bug.

**Comment by HeathcliffWarriors** [comment]
Okey doke.
