### ISSUE TITLE
Incorrect Penalty Tourism from Cities UPDATE!

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5364]
_1. Mod version (i.e Date - 4/23): February 17th (2-17)

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description:_

**UPDATE! The last two screenshots proves that the capital doesn't count towards the tourism penalty, somethings triggered the wrong calculation!**

> The tourism penalty is not calculated correctly, shouldn't be something like this:
> (capital (no penalty) + puppet cities (no penalty) + annexed cities (7)) * 7% = 49%
> 
> But in every cities the penalty displayed is 56%, I don't know if just the displayed number is wrong, the calculation or something else

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Kamehameha_0345 AD-1925_bug2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3173624/Kamehameha_0345.AD-1925_bug2.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0005](https://user-images.githubusercontent.com/49090452/57633772-bac7ed00-75ac-11e9-95a2-b88383158a9d.png)
![Civ5Screen0006](https://user-images.githubusercontent.com/49090452/57633776-bc91b080-75ac-11e9-932f-bfa294917cb8.png)
![Civ5Screen0007](https://user-images.githubusercontent.com/49090452/57633784-c0253780-75ac-11e9-85a9-71daa16a6589.png)
![Civ5Screen0008](https://user-images.githubusercontent.com/49090452/57633782-be5b7400-75ac-11e9-99fe-ac75c1774bf0.png)

**Comment by TechpriestEnginseer** [comment]
It's been an old bug that your 1st puppet will count toward the %-modifier.

**Comment by LoneGazebo** [comment]
If you annex and raze a city, it bumps your total cities count up, even after the city burns.

**Comment by Aqinu** [comment]
> 
> 
> It's been an unfixable old bug/feature (who knows what firaxis developers thought about this) that your 1st puppet will count toward the %-modifier.
> 
> If you have 7 cities annexed(not including Capital), it will assume you are attempting to annex your 8th city(which you are just puppeting).
> 
> However, it will stay at 56% after your 1st puppet until you decided to annex them.

You are right, this bug happened right before the first city puppet after that didn't go any higher, shame that can't be fixed.
