### ISSUE TITLE
Barbarians Requiring Strategic Resources

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#5366]
I noticed that barbarian horseman and swordsman now require their respective horse and iron, but I think they didn't require horse and iron because they were trying to make sure Germany didn't have these units fighting with a huge combat penalty.

**Comment by LoneGazebo** [comment]
Germany doesn't have that ability any more...nor the huns.

**Comment by TechpriestEnginseer** [comment]
Then the barbarians don't really stand out, do they? Do these barbarian units get to heal?

**Comment by LoneGazebo** [comment]
Pretty sure they ignore strategic resource stuff.

**Comment by TechpriestEnginseer** [comment]
understandable.
