### ISSUE TITLE
Incorrect Descriptions and Icons Used for Promotions

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5367]
_1. Mod version (i.e Date - 4/23): 4/20

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: There are many incorrect description and icons used for promotions which must be revisited (Civilopedia, Promotion Tree and Units). Here are some examples (see screenshots):

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

Here is used combat strenght icon instead of range (and should be described completely something as "10% (icon_range) combat strength" just as like the first ability)
![Civ5Screen0009](https://user-images.githubusercontent.com/49090452/57687157-9703b600-7643-11e9-9f47-c44f54d56d14.png)

For the next three screenshots the same, should be range icons used instead of combat in the second abilities
![Civ5Screen0010](https://user-images.githubusercontent.com/49090452/57686916-1fce2200-7643-11e9-9966-5aebb118dbe8.png)

![Civ5Screen0011](https://user-images.githubusercontent.com/49090452/57686970-3e341d80-7643-11e9-8a99-2e6e460bbd8a.png)

![Civ5Screen0012](https://user-images.githubusercontent.com/49090452/57686993-4ab87600-7643-11e9-9f26-2994ed9daa46.png)

And here is done correctly which means is possible to fix this problem
![Civ5Screen0015](https://user-images.githubusercontent.com/49090452/57687094-7dfb0500-7643-11e9-9d0a-8788dd4fe733.png)

**Comment by LoneGazebo** [comment]
Hmm? All promotions are handled correctly by the Expanded Promotions mod mod.

**Comment by Aqinu** [comment]
Where can i get this Expanded Promotions mod mod? All I have installed is vox populi

**Comment by LoneGazebo** [comment]
It is part of VP.

**Comment by Aqinu** [comment]
But many promotions are incorrect displayed (i.e. intead of **range combat icon** is used **defence combat icon** in many places which adds to confusion), I don't understand what you don't understand... (please explain what means "promotions are handled correctly", I didn't say anything about that at all, I just said that many promotions **descriptions / representation of icons** are incorrect presented

**Comment by Aqinu** [comment]
I'm talking about these icons which are sometimes incorrectly used (the second icon "melee icon" should be the same as the first "range icon" in these instances:
![57686993-4ab87600-7643-11e9-9f26-2994ed9daa46](https://user-images.githubusercontent.com/49090452/57762890-fd9ed780-7708-11e9-8183-e7e048e4cbc2.png)
![57687157-9703b600-7643-11e9-9f47-c44f54d56d14](https://user-images.githubusercontent.com/49090452/57763188-903f7680-7709-11e9-9b8d-9f4c4c7a87e6.png)

**Comment by LoneGazebo** [comment]
Not exactly, because the former is offense only, whereas the latter is offense/defense. When both, the shield is used.

**Comment by Aqinu** [comment]
And how people are suppose to know this? (I understand now but the description is confusing).

If it is this way, why not write for Siege Promotion for instance something like this:
10% "range icon" Combat Strength
10% "melee icon" Combat Strength VS Cities
10% "range icon" Combat Strength VS Cities

This way is much clearer to understand (maybe it cannot be done because of max. length of letters? than write it something more compact like: 10% "melee icon" and "range icon" Combat Strength VS Cities)

And another question, why is written in two different formats some abilities? (my guess only for aesthetics?):

10% "melee icon" Combat Strength VS Units at or below 50 HP
10% "melee icon" VS Cities (instead of: 10% "melee icon" Combat Strength VS Cities)

**Comment by Aqinu** [comment]
And after I did some testing (using ingame editor) I found out that 

>  Not exactly, because the former is offense only, whereas the latter is offense/defense. When both, the shield is used

is wrong. For drill promotion for example should be written something like this:
10% "melee icon" Combat Strength for attacking **and** defending, 25% Combat Strength for **only** attacking VS Cities

The combat VS Cities doesnt decrease the damage input for units, more strength less damage ...
(I tested with two warrior: first - all 3 drill promotions and second - all 3 shock promotions and there is not difference in damange from the City)

This should be fixed for all promotions because this is very confusing...
![Civ5Screen0016](https://user-images.githubusercontent.com/49090452/57838145-d14c8f00-77cc-11e9-85df-e69a6f1d219f.png)

**Comment by Aqinu** [comment]
I tested further more for Field Promotions, and the same thing, the description is wrong (the "melee icon" is not for defence and offence in this case; is only for offence which means that should be a "range icon")

I used again ingame editor and I gave a catapult all 3 Field Promotions and let it be attacked by a enemy warrior (which was previsusly damaged by my catapult to be a "wounded unit") and the damage that I took was the same for a catapult with no promotion, hence the description is wrong

The description should be somethings like this:
5% "range icon" Combat Strength, 10% "range icon" Combat Strength VS Wounded Units

And there are many more promotions which are incorrect... (hope will be fixed because is very confusing)
![57687157-9703b600-7643-11e9-9f47-c44f54d56d14](https://user-images.githubusercontent.com/49090452/57908183-1aade480-7888-11e9-9b56-eca305f5e65f.png)

**Comment by LoneGazebo** [comment]
This is a non issue, not going to fix because, primarily, the elements as described as ‘wrong’ are shared promotion attributes that affect both ranged and melee combat profiles. At base, this is used throughout the promotion database with the shield icon, as that is the default. Only items which exclusively affect ranged strength are marked with the range icon.

**Comment by Aqinu** [comment]
Ok, I understand now, but do you agree that my tests are correct  (even though shows "melee icon" for range units its in fact **just** "range icon" (offence bonus) strength (there is not strength bonus increase for defence "melee icon" when the unit is attacked by the enemy)

Now if this is the way promotions are meant to work, and you cannot change the icons with the **correct one**, just to eliminate the confusion (which I think you agree that for anyone this can be a problem) why not add a **simple text** for only range units and remove the icon (to not add further confusion with text telling **Range** and the icon used is **Melee**) like this:

For Field Promotion, 2nd ability, **10% Range Combat Strength VS Wounded Units**

And If this cannot be done separately for range units (the whole string with the icon are extracted from the database or other reason) I think atleast this is possible to put this information in Civilopedia for the respective promotions

**Comment by LoneGazebo** [comment]
I just don’t think it is necessary. The content of the promotions is self explanatory.

**Comment by Aqinu** [comment]
I literally don't understand how can you say that, its like you didn't understand /  read what I said earlier, how should anyone understand that for example for **drill promotions** 2nd ability where it says that offeres you **25% "melee icon" combat strength VS Cities** is just when you attack the city **and not** when the city attacks you?

This is my last comment on this issues, I am not gonna bother you anymore about this problem but my opinion is that what others gamers think about this is also important and I'm curios how many understand the promotions correctly and think that 
> the content of the promotions is self explanatory

**Comment by LoneGazebo** [comment]
Agree to disagree. No one else has ever had issue with it. The promotion language has been the same since 2012.

**Comment by Edaka** [comment]
I can say for myself that I've personally never tried to really determine when those bonuses apply and when they don't. I've always taken the fact that they work for granted. I guess if I was as prudent as the OP and tried to get to the bottom of it, it would confuse me too. 

I see how this could be a point of confusion, especially for new players, and that's not a good thing. The fact that nobody has spoken up so far doesn't necessarily mean that nobody has had an issue with it. Just my two cents.

P.S. @Gazebo what do you say if someone was to make all the appropriate clarifications in the promotion text files and make a pull request here, doing all the tedious work, would you be okay with that?

**Comment by LoneGazebo** [comment]
No, because it breaks compatibility with modmods that use or borrow the original language.

**Comment by TechpriestEnginseer** [comment]
I don't think it matters with modmods since modmods are terribly inconsistent with language anyhow.

**Comment by Edaka** [comment]
I mean, this right here could also be a realised as a modmod, heh. But I doubt that newer players, who'll probably benefit the most from it, install modmods much. Therefore I don't really see a significant demand for it.
