### ISSUE TITLE
Wrong Tooltip for GPT in Trade Screen

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5369]
4-20-2 Beta

![Screenshot (12450)](https://user-images.githubusercontent.com/38794241/57748512-46727400-76a8-11e9-9146-9972f865aa28.png)

**Comment by LoneGazebo** [comment]
usually indicative of lua error- you had one?

**Comment by HeathcliffWarriors** [comment]
Not sure if I did or not, how do I check that?

I'm still new to the whole code process :)
