### ISSUE TITLE
Deal AI: Hide True Feelings issue

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5370]
_1. Mod version (i.e Date - 4/23):_ 4/20-2 Beta

In the DealAI.cpp file, there are four instances where approach towards a specific player is used as a factor in deciding the value of a trade item, and there are checks for the DECEPTIVE and/or WAR approaches, but /*bHideTrueFeelings*/ is set to True, meaning it will never return DECEPTIVE or WAR - this strikes me as a bug.

These cases occur after the checks on lines 2776, 3477, 3496 and 3596.

**Comment by MoiMagnus** [comment]
I'm not sure it is a bug. 

Deal values are public, so a clever player could easily see trough deception if they see deal values are lower than expected.

However, as most players don't know what to expect from deal values, and as a player might see trough deception even without this trick, I agree it is probably a bug.

**Comment by HeathcliffWarriors** [comment]
I think it's a bug since the checks exist despite it never returning those values.

It could be just intentionally changed old code or something, though.

**Comment by LoneGazebo** [comment]
It's all stuff Putmalk added when he did c4df.
