### ISSUE TITLE
IsCloseToDiploVictory Issue

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5374]
```
/// Is this player close to a diplomatic victory?
bool CvDiplomacyAI::IsCloseToDiploVictory()
{
	CvLeague* pLeague = GC.getGame().GetGameLeagues()->GetActiveLeague();
	if (pLeague != NULL)
	{
		int iVotes = GC.getGame().GetGameLeagues()->GetActiveLeague()->CalculateStartingVotesForMember(GetPlayer()->GetID());
		int iVotesNeededToWin = GC.getGame().GetVotesNeededForDiploVictory();
		if(iVotes >= iVotesNeededToWin)
		{
			return true;
		}
	}
	return false;
}
#endif
```

Stalker0 pointed out that if the AI is only reacting when they have enough votes to win, it's probably already too late, and I had the same thought.

Perhaps it should be 75% of the votes needed to win instead, like with Domination Victory requiring 75% of original capitals?

**Comment by Omen-of-Peace** [comment]
In favour!
I argued (in my head) about setting the threshold higher than 75%, but actually Diplo can snowball much like Domination, via the Sphere of Influence resolution, so 75% sounds fine.

**Comment by HeathcliffWarriors** [comment]
Is now the case in latest version
