### ISSUE TITLE
Spies Treat Public Works Construction As Intrigue

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5375]
_1. Mod version (i.e Date - 4/23):_ 4-20-2 Beta

I received the following message while playing earlier:
"Agent X in City discovered that Y is building Public Works."

_2. Mod list (if using Vox Populi only, leave blank):_ UI mods + Quick Turns

**Comment by LoneGazebo** [comment]
So?

**Comment by HeathcliffWarriors** [comment]
*shrug*

Seemed like unintended behavior, but all right.

**Comment by TechpriestEnginseer** [comment]
The spy's intrigue is that you want to know what they are building in a wonder or a project. The Public Works is a project by code.

**Comment by HeathcliffWarriors** [comment]
I realize that, but my reasoning was that it's useful to know when a player is building a Wonder, the Manhattan Project, or the Apollo Program, but it's much less _intriguing_ to learn they are just building Public Works.

**Comment by TechpriestEnginseer** [comment]
still a project.

**Comment by Voker57** [comment]
Reason is to avoid notification spam.
Also, doesn't this allow to share this intriguing discovery with an AI for relation boost?..

**Comment by HeathcliffWarriors** [comment]
No, but obtaining intrigue does allow you to level up your spies. PW isn't interesting enough to warrant that, IMO.
