### ISSUE TITLE
Automated workers sit in one tile city far away from main lands

### ISSUE THREAD

**Issue by Trambambaj** [LoneGazebo/Community-Patch-DLL#5377]
Automated workers travel  to one tile island city to just sit there
1. Mod version (i.e Date - 4/23):
Vox populi beta 4-20-1

2. Mod list (if using Vox Populi only, leave blank):
Ancient techs rebalanced(v. 1)
(over)more unique components for VP(v. 43)
Barbarians - unlimited exp(v. 2)
Improvement - Tunnel (v. 5)( this one is from there including listed dll http://www.picknmixmods.com/mods/CivV/Improvement/Tunnel.html)
Ingame editor (v. 39)
Neolithic Wonders (v. 1)
Promotions -Expansion Pack (v. 9)
Yet not another eartch map pack (v. 24)

[bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3192134/bug.zip)

**Comment by ilteroi** [comment]
yeah yeah should be better now
