### ISSUE TITLE
EUI: Ostrog production bonus on tiles isn't shown in the Tool Tip level 2

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#538]
![8930_2015-08-21_00004](https://cloud.githubusercontent.com/assets/1131228/9396014/4ee8b61a-47ab-11e5-999f-d386b21ac463.png)

**Comment by LoneGazebo** [comment]
That's because of how it's XML is handled - there isn't a location for the XML bonus in EUI's tooltip.
G
