### ISSUE TITLE
Weird Movement Bugs with Missionaries

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5381]
_1. Mod version (i.e Date - 4/23):_ 4/20-2 Beta

_2. Mod list (if using Vox Populi only, leave blank):_ Quick Turns, Calypso's Colored Religious Icons, Faster Aircraft Animations, Archaeology Aesthetic Adjustments

_3. Error description:_ When moving Missionaries (and only Missionaries), I often get weird bugs with the pathfinder; I click on one destination tile and the Missionary moves to another one.

I encountered this bug in the previous version as well IIRC.

The orange circles indicate where I was pointing the cursor, and you can see in the second and fourth screenshots where those Missionaries ended up going.

![Screenshot (12354)](https://user-images.githubusercontent.com/38794241/57989999-2f4cd100-7a70-11e9-9351-24aba75c79af.png)
![Screenshot (12355)](https://user-images.githubusercontent.com/38794241/57990000-2f4cd100-7a70-11e9-9589-b107cf16f558.png)
![Screenshot (12356)](https://user-images.githubusercontent.com/38794241/57990001-2f4cd100-7a70-11e9-8f55-73187f2b6858.png)
![Screenshot (12357)](https://user-images.githubusercontent.com/38794241/57990002-2f4cd100-7a70-11e9-977d-9c13601e47d8.png)

**Comment by ilteroi** [comment]
might be related to the "avoid attrition" feature ... i'll check
