### ISSUE TITLE
Transparent Diplomacy Mismatch

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5382]
_1. Mod version (i.e Date - 4/23):_ 4/20-2 Beta

_2. Mod list (if using Vox Populi only, leave blank):_ Quick Turns, Calypso's Colored Religious Icons, Faster Aircraft Animations, Archaeology Aesthetic Adjustments

![Screenshot (12626)](https://user-images.githubusercontent.com/38794241/57990268-ed715a00-7a72-11e9-8155-c17b72373c15.png)

In the code, the opinion weight is supposed to be -10 for having the same Ideology and +10 for having different Ideologies. (-5/+5 in vanilla but the global is updated)

You stated that DiploEmphasisLatePolicies (or in the current version, "Diplp"EmphasisLatePolicies :S), which it appears to be multiplied by, is a vanilla value that doesn't affect anything.

However, in my case Transparent Diplomacy is showing a +90 opinion modifier for having different ideologies.

Is this a bug? Attempting to figure this one out for my opinion modifier table :)

**Comment by LoneGazebo** [comment]
Not a bug, no - DiplpEmphasisLatePolicies isn't benign, used to be though.

**Comment by HeathcliffWarriors** [comment]
Ah, I see.

If it's just a multiplier based on era should be easy to figure out. Thanks!
