### ISSUE TITLE
Folder Deletion

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5387]
5/19 version

Did you mean to delete the entire CBP folder?

Struck me as potentially being a crazy merge error or something with files being overwritten. 126,000 deletions didn't look normal.

**Comment by LoneGazebo** [comment]
Probably a merge conflict. I’ll look.

**Comment by LoneGazebo** [comment]
This is what happens when 5+ people merge onto master. :)

**Comment by HungryForFood** [comment]
Github can be a cruel mistress. :(

**Comment by HeathcliffWarriors** [comment]
Speaking of merge issues,

`&& !GET_PLAYER(ePlayer).GetNumCapitalCities() > 0` in CvDiplomacyAI (my capital check fix) was somehow changed into

`&& GET_PLAYER(ePlayer).GetNumCapitalCities() > 0`

i.e. The weight will not be zeroed out if they _don't_ have other players' capital cities, which would greatly increase aggression by masters towards vassals.

Would just need to re-add the ! :)

**Comment by LoneGazebo** [comment]
Because that’s illegal syntax.

**Comment by HeathcliffWarriors** [comment]
Ah, makes sense

< 1 then
