### ISSUE TITLE
A promise to stop buying land near them

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#539]
![8930_2015-08-21_00005](https://cloud.githubusercontent.com/assets/1131228/9396198/9bfbb820-47ac-11e5-897b-aa52003269b4.png)
I don't remember to promise him that.

**Comment by LoneGazebo** [comment]
You did say you were 'on something' earlier. :)

**Comment by Radost** [comment]
Nah, I didn't use GG. Also GG-related penalty is different.
It's not the first time I encounter this bug either.

**Comment by Edaka** [comment]
He mentioned smoking something, to be exact (: 
I've had a situation when I actually promised two neighbouring AIs not to buy land near them. Later both of them simultaneously accused me of breaking the promise, which I didn't break. What's even weirder is that eventually I got a message saying I'd kept my border expansion promise, but the diplomatic penalties with the AIs were still there.
Thought this might be related and maybe helpful, excuse me if it's neither.

**Comment by Radost** [comment]
> Later both of them simultaneously accused me of breaking the promise, which I didn't break.

"Near them" is a very vague term. It can range from 1 tile away from their borders to 40 tiles away.
In my case though I didn't give a promise, that accusation was out of blue.

**Comment by LoneGazebo** [comment]
The problem is one of nearness, yeah - 'near' is based on the AI's boldness.

Regarding both, I'll take a look.

**Comment by Edaka** [comment]
Unfortunately, I had the described experience long ago enough so I can't give my word for it, but I think I never bought any tiles after the promise whatsoever. Still got the contradictory message for keeping it after all the accusations, though.
Thanks for looking into it.

**Comment by LoneGazebo** [comment]
Code all checks out just fine. Chalking this up to LUA.

**Comment by Radost** [comment]
And again
![8930_2015-08-24_00013](https://cloud.githubusercontent.com/assets/1131228/9447997/95383496-4ab3-11e5-91ad-a500bd83880b.png)
This time I didn't buy the tiles for a long time and the only thing I did border-related is founding a city. And still I didn't promise anything.
