### ISSUE TITLE
F*kin' Belief_ImprovementYieldChanges, How do they work?

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#5390]
_1. Mod version: 5/19

_2. Mod list (if using Vox Populi only, leave blank): 3/4th Unique Components

_3. Error description: 
I'm unsure how Belief_ImprovementYieldChanges works, and how to use it properly. 
Most beliefs have their yields limited to improvements on resources only (ie. rhiannon, Earth Mother, etc.)
The exception is Knowledge through devotion, which gives all GPTIs 4faith/sci, even if they aren't on resources.
How does the game know to make that exception? Does it check CreatedByGreatPerson?
I want to make an improvement that gains 1 yield for every belief in the nearby city, but I don't want to lock it to resources only. Is there any way that I can do this, or is that a feature request?

4. Screenshots: 4 unique improvements, Ethiopian Monolithic Church, 
     1) 2 on hills with no yields from beliefs
     2) 2 on stone with belief yields.
![image](https://user-images.githubusercontent.com/33136027/58143086-cd729f80-7c06-11e9-8930-5df39f5737fb.png)

**Comment by LoneGazebo** [comment]
The magic:

```
int CvPlot::calculateReligionImprovementYield(ImprovementTypes eImprovement, YieldTypes eYield, PlayerTypes ePlayer, const CvCity* pOwningCity, const CvReligion* pMajorityReligion, const CvBeliefEntry* pSecondaryPantheon) const
{
	if (!pOwningCity || !pMajorityReligion || ePlayer == NO_PLAYER)
		return 0;

	if (eImprovement == NO_IMPROVEMENT || IsImprovementPillaged())
		return 0;

	CvImprovementEntry* pImprovement = GC.getImprovementInfo(eImprovement);
	if (!pImprovement)
		return 0;

	CvPlayer& kPlayer = GET_PLAYER(ePlayer);

	int iReligionChange = 0;
	bool bRequiresResource = pMajorityReligion->m_Beliefs.RequiresResource(pOwningCity->getOwner());
	if (pImprovement->IsCreatedByGreatPerson() || pImprovement->IsAdjacentCity() || pImprovement->IsIgnoreOwnership())
	{
		bRequiresResource = false;
	}
	if (MOD_BALANCE_CORE_BELIEFS_RESOURCE && bRequiresResource)
	{
		if (bRequiresResource && (getResourceType(kPlayer.getTeam()) != NO_RESOURCE) && pImprovement->IsImprovementResourceMakesValid(getResourceType(kPlayer.getTeam())))
		{
			iReligionChange += pMajorityReligion->m_Beliefs.GetImprovementYieldChange(eImprovement, eYield, pOwningCity->getOwner(), pOwningCity);
		}
	}
	else
	{
		iReligionChange += pMajorityReligion->m_Beliefs.GetImprovementYieldChange(eImprovement, eYield, pOwningCity->getOwner(), pOwningCity);
	}
	
	if (!pSecondaryPantheon)
		return iReligionChange;

	bRequiresResource = pSecondaryPantheon->RequiresResource();
	if (pImprovement->IsCreatedByGreatPerson() || pImprovement->IsAdjacentCity())
	{
		bRequiresResource = false;
	}
	if (MOD_BALANCE_CORE_BELIEFS_RESOURCE && bRequiresResource)
	{
		if (bRequiresResource && (getResourceType(kPlayer.getTeam()) != NO_RESOURCE && pImprovement->IsImprovementResourceMakesValid(getResourceType(kPlayer.getTeam()))))
		{
			iReligionChange += pSecondaryPantheon->GetImprovementYieldChange(eImprovement, eYield);
		}
	}
	else
	{
		iReligionChange += pSecondaryPantheon->GetImprovementYieldChange(eImprovement, eYield);
	}

	return iReligionChange;
}
```

**Comment by pineappledan** [comment]
The ~magic~*Miracles*:

So, if 
1. the improvement has a ResourceMakesValid == null, then the yields will be added
2. the improvement has IsCreatedByGreatPerson == true, then the yields will be added
3. the improvement has a ResourceMakesValid == RESOURCE_XXX, and is constructed on that resource, then the yields will be added. 
Otherwise, no yields for you. Is that correct?

**Comment by LoneGazebo** [comment]
Essentially. Note the 'RequiresResource' belief table attribute - if that's false, the tile will get the yields and skip all of the resource stuff.

**Comment by pineappledan** [comment]
Cool, so if I want the improvement to work exactly as it does now (can build on hills with no resource or stone), then I will have to make 2 versions of the UI: 
1. make a version that can be built on hills with no resource
2. make a version that can be built on stone

**Comment by pineappledan** [comment]
Doesn't seem to be working that way. I'm still in the process of checking everything, but I have split the two improvements into distinct ImprovementTypes, according to the separate build requirements (hills vs. stone), and the stone improvement gets the Belief_ImprovementYieldChanges while the hills improvement does not
