### ISSUE TITLE
Diplomatic Units Wrong Descriptions

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5391]
_1. Mod version (i.e Date - 4/23): 2/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: All Diplomatic Units (Envoy, Diplomat, Ambassador, Great Diplomat)  have wrong descriptions  for influence values in **Civilopedia** and **Production Queue**

See Screenshots for examples!

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0021](https://user-images.githubusercontent.com/49090452/58273224-eb700980-7d98-11e9-8c1d-5e7122902c0e.png)
![Civ5Screen0025](https://user-images.githubusercontent.com/49090452/58273233-f165ea80-7d98-11e9-9543-ebfd6fdb8a69.png)
![Civ5Screen0022](https://user-images.githubusercontent.com/49090452/58273269-03e02400-7d99-11e9-8541-447e0b5ba674.png)
![Civ5Screen0023](https://user-images.githubusercontent.com/49090452/58273270-05115100-7d99-11e9-9004-4193aa3a0040.png)
![Civ5Screen0024](https://user-images.githubusercontent.com/49090452/58273273-06db1480-7d99-11e9-9428-ddc5d9e86add.png)
![Civ5Screen0026](https://user-images.githubusercontent.com/49090452/58273364-40138480-7d99-11e9-9275-8c053f1d737e.png)
![Civ5Screen0029](https://user-images.githubusercontent.com/49090452/58273372-443fa200-7d99-11e9-8fee-72c15f071687.png)
![Civ5Screen0030](https://user-images.githubusercontent.com/49090452/58273376-46a1fc00-7d99-11e9-9d5c-c58489a8111d.png)
![Civ5Screen0031](https://user-images.githubusercontent.com/49090452/58273377-486bbf80-7d99-11e9-92b0-238ffe4d51ed.png)

**Comment by UndeadDevel** [comment]
@Aqinu I'm curious as to why you closed this, as the issue seems to still be there...I was going to open a new one exactly like this just now.

**Comment by Aqinu** [comment]
I will leave it open till it's fixed...
