### ISSUE TITLE
Installer - Start Menu Shortcuts

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5393]
_1. Mod version (i.e Date - 4/23):_ 5/19 Beta

![cfbe5c31ddda1e28ffdcd7d856542ee4](https://user-images.githubusercontent.com/38794241/58279440-6838be80-7d6c-11e9-8c22-6a91960c633d.png)

This prompt doesn't seem necessary, and it's rather annoying to always click "Don't create a Start Menu folder". Why would we need a Start Menu folder if you can only activate the mod through playing the game?

I suspect that either the installer doesn't have a configuration option to remove that screen, or there's some unknown functionality involving Start Menu folders, but in case there's not, since no one seems to have opened an issue about it before, might as well bring it up.

I use Windows 10.

**Comment by LoneGazebo** [comment]
Can't remove it.
