### ISSUE TITLE
Peace treaty - units in territory get destroyed, version 2

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#5396]
_1. Mod version (i.e Date - 4/23):_
5/19/2019

_2. Mod list (if using Vox Populi only, leave blank):_
(only VP)

_3. Error description:_ 
I'm at war with the Mongols, and war weariness is high. Mongols sue for peace, and I accept. However, units right before my eyes disappear, reminding me of having seen this issue once before with an earlier version.

_4. Steps to reproduce (optional):_
Get into war, put units in enemy territory, make peace, and then watch unit loss in enemy territory.

**Comment by briantjack** [comment]
I reloaded the game, before the peace treaty, and kept a unit in enemy territory -- just to confirm this problem happens consistently. It did not; the lone unit inside the Mongols' border was moved outside -- just as it should. I can't tell you what was different this time.

**Comment by bentakacs** [comment]
It just happened to me as well right now: Cuirassier with Great General didn't move outside of enemy border, but instead disappeared :( 

Logs:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3234034/Logs.zip)
