### ISSUE TITLE
War weariness all of a sudden

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#5397]
_1. Mod version (i.e Date - 4/23):_
5/19/2019

_2. Mod list (if using Vox Populi only, leave blank):_
(only VP)

_3. Error description:_ 
I was at war with the Mongols (he declared, but I repelled the invasion), and it had been running for several turns. War weariness was reportedly at zero, but on the next turn, it jumped to 21, reducing my happiness from 85% to 58%. (I had adopted the Honor social policy, which should reduce WW by 25%.) 

In older games (with prior versions of VP), WW had been a gradual problem -- starting small and growing larger as the war raged on. The sudden shift from 0 to 21 is what surprised me here. Is this the new norm?

_4. Steps to reproduce (optional):_
Get into drawn out war (with Mongols?)

**Comment by HeathcliffWarriors** [comment]
Also experiencing this - huge jumps in war weariness; 0 one turn, 21 the next turn.

**Comment by LoneGazebo** [comment]
@ilteroi any ideas?

**Comment by ilteroi** [comment]
yeah, that was surprisingly easy to find ... a MAX where it should say MIN
