### ISSUE TITLE
Game freezes during AI's turn

### ISSUE THREAD

**Issue by JLazeZ** [LoneGazebo/Community-Patch-DLL#5398]
_1. Mod version (i.e Date - 4/23):_
May 19th (4.5.19)​

_2. Mod list (if using Vox Populi only, leave blank):_
- Calypso's Colored Religious icons (Extensions also)
- Quick Turns
Additional Civs
- JFD's Prussia for VP
- Colonialist Legacies - Vietnam + CBO compatibility mod for it
- Colonialist Legacies' Canadian Dominion for VP
- MC's Greece/Macedon Split for VP

_3. Error description:_ 
The game freezes during AI Player 4's turn

_4. Steps to reproduce (optional):_
End turn and wait for the AI Player 4's resolve

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3224566/Logs.zip)

2. Save game
[Back Up.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3224569/Back.Up.zip)

3. CvMiniDump.dmp file 
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3224573/CvMiniDump.zip)

**Comment by JLazeZ** [comment]
Using In-Game Editor, I learned I was freezing during the Aztec's turn.

**Comment by Vyyt02** [comment]
Have you tried deleting the Aztecs with IGE? Did the game proceed? Sometimes things are not what they appear, it does not have to do anything with the Aztecs. I would rather suspect the Prussia civ.
