### ISSUE TITLE
Can't improve the resource on CS territory

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#540]
![8930_2015-08-22_00003](https://cloud.githubusercontent.com/assets/1131228/9417496/4c42a73e-4866-11e5-9bdb-4126e60fc267.png)
![8930_2015-08-22_00004](https://cloud.githubusercontent.com/assets/1131228/9417498/51a7aefe-4866-11e5-8c70-e9b7930db7e4.png)

**Comment by LoneGazebo** [comment]
Which? The Coal?

**Comment by Radost** [comment]
Yep.

**Comment by LoneGazebo** [comment]
Probably because the lumbermill. I'll take a look.
G

**Comment by LoneGazebo** [comment]
Code for this looks fine. I don't see any issues, so it must be an EUI/LUA bug.

**Comment by Radost** [comment]
Now I've tried again and it worked.
In the screenshot I tried to improve on the same turn the city was liberated, if it helps.

**Comment by LoneGazebo** [comment]
Probably hadn't refreshed tile ownership.
