### ISSUE TITLE
fix for teleported units being killed

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5402]
new dll, drop in replacement for the one from the 5-19 release (also fixes excessive war weariness)
[CvGameCore_Expansion2-20190519-fixed.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3236208/CvGameCore_Expansion2-20190519-fixed.zip)

**Comment by bentakacs** [comment]
Thank you very much! :)

**Comment by vijaysingh888** [comment]
Can you please upload the 43 civ DLL with this fix???
