### ISSUE TITLE
Bonus vs Mounted Unit Calculation?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#5405]
https://www.reddit.com/r/civvoxpopuli/comments/bvnw1v/question_about_combat_bonus_calculation/

**Comment by TechpriestEnginseer** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/4823
Could be a reference why

**Comment by indrek-k** [comment]
OP here, thanks for reporting this already!

Should I also attach a save file here?

**Comment by ilteroi** [comment]
i didn't understand the linked issue, but i can reproduce this. 

but it's weird, "PROMOTION_ANTI_MOUNTED_I" does not seem to register a UnitClassAttackModifier. maybe a database problem? it's not even mentioned in the table UnitPromotions_UnitClasses.

secondly, there's the fact that a skirmisher is UNITCLASS_ARCHER, not UNITCLASS_MOUNTED.

**Comment by ilteroi** [comment]
pushed some cleanups which should improve performance, but i don't know how to fix the database (assuming that is the problem)

**Comment by LoneGazebo** [comment]
@ilteroi 

In the database, I see:

"PROMOTION_ANTI_MOUNTED_I"	"UNITCOMBAT_MOUNTED"	"50"

For UnitPromotions_UnitCombatMods. Seems fine to me.

**Comment by LoneGazebo** [comment]
Combat class = UNITCLASS_WARRIOR; Combat Type = UNITCOMBAT_MELEE

**Comment by indrek-k** [comment]
Thanks for solving this!

However, someone on Reddit pointed out that the Pikeman on this screenshot also has the Morale bonus which is not displayed in the calculations. 

Should I open a separate issue for this?
