### ISSUE TITLE
Venice AI and merchants

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#541]
![8930_2015-08-22_00001](https://cloud.githubusercontent.com/assets/1131228/9417578/e7aa7ad0-4866-11e5-89be-1584cc182993.png)
This merchant stays for god knows how long without being used.

**Comment by LoneGazebo** [comment]
You have your OperationalAI.log and HomelandAI.logs? Link them if you can. I think I know why this is happening.

**Comment by Radost** [comment]
I don't have them. I followed instructions on "how to install" page.
What exactly do I have to do to enable all possible logging?

**Comment by LoneGazebo** [comment]
In your config.ini file in your my games/civ 5 folder, search for the word 'logging' and enable all logging options except for the one that separates logging files by player. 'AI Logging' is the most important.

**Comment by Radost** [comment]
http://rghost.net/7fpsR9Fps

**Comment by LoneGazebo** [comment]
Does the unit move around at all, or does it just stay still?

**Comment by Radost** [comment]
Just stays still.

**Comment by LoneGazebo** [comment]
I think it's just getting locked in place because it is where it wants to be, but it doesn't want to trade (for some reason). I'll make a check.
