### ISSUE TITLE
bug: declare war on my friend if I ask him to start a war together against another civ

### ISSUE THREAD

**Issue by BorussiaVox** [LoneGazebo/Community-Patch-DLL#5410]
_1. Mod version (i.e Date - 4/23):_
6-2

_2. Mod list (if using Vox Populi only, leave blank):_
Subs ignore borders
Reforestation
Faster aircrafts
Infoaddict
Reallyadvancedsetup

_3. Error description:_ 

If I ask my friend to start a war with another civ in the Discuss menu I automatically declare war on him if he accepts.
He then tells me: "My soldiers are excited at the prospect of war. To arms, ally!"
What happens is: he declares war on the other civ and I declare war on him but not the other civ.

If I ask someone else and they decline my request, nothing happens. They just refuse.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Whoopsy.
