### ISSUE TITLE
5/19 - Incorrect Combat Strength

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5416]
_1. Mod version (i.e Date - 4/23):_

5/19
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
As noted in the screenshot, the final combat strength of the unit doesn't match the bonuses applied. The bonuses equal near 100%, so you would expect a strength of ~60, not 49.

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/58999622-32fc8980-87cc-11e9-8c6b-e4710a554eca.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
this is already fixed in the june version
