### ISSUE TITLE
Renewing deals

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#542]
Civs are way too willing to give away they luxuries and GPT upon deal renews.
![8930_2015-08-22_00014](https://cloud.githubusercontent.com/assets/1131228/9419687/437ab360-4877-11e5-86e1-ba9870eb3bde.png)
![8930_2015-08-22_00015](https://cloud.githubusercontent.com/assets/1131228/9419689/46568348-4877-11e5-9249-913b4f4bc413.png)
This deal is started as Cloves for Coffee but grown up into this.
![8930_2015-08-22_00018](https://cloud.githubusercontent.com/assets/1131228/9419721/9d0850c2-4877-11e5-8f0f-901d0da52277.png)
![8930_2015-08-22_00019](https://cloud.githubusercontent.com/assets/1131228/9419722/a0aa6c1a-4877-11e5-9b78-d498bf1842d5.png)
This is even worse, he traded his last copy for what exactly?

**Comment by LoneGazebo** [comment]
Huh. There's nothing specific to renewals that would make them more or less likely to offer like that.
G
