### ISSUE TITLE
Plunder Trade Route Text Key

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5421]
![Screenshot (13668)](https://user-images.githubusercontent.com/38794241/59141234-033db500-8977-11e9-8ee3-720a85b0fd10.png)

"You must be able to declare war against the trade route owner." is misleading...

I'd go with "You must be at war with the trade route owner."

**Comment by LoneGazebo** [comment]
Why? That excludes Morocco's UA.

**Comment by HeathcliffWarriors** [comment]
The red tooltip doesn't show up for Morocco's UA unless it's to an owned city and they're not at war - in which case they'd need to declare war, so it'd still be accurate in that scenario.

Morocco's UA is already explained in the white text - and they wouldn't see the red tooltip in other scenarios since the option to plunder would be available, not blocked.
