### ISSUE TITLE
AI does not put items they're willing to accept on the deal table

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5422]
_1. Mod version (i.e Date - 4/23):_ 6/2

_2. Mod list (if using Vox Populi only, leave blank):_ Archaeology Aesthetic Adjustments, Calypso's Colored Religious Icons, Faster Aircraft Animations, Quick Turns

_3. Error description:_ Oftentimes when I ask "What do you want for this?" from the AI, they simply refuse as if it's impossible, despite there being items I could put on the table. As an example, William is willing to trade 3 Horses for 70 Gold, but when I asked what he wanted for 70 Gold, he simply said no. I had to offer them myself, which rather defeats the purpose of the button.

![Screenshot (13671)](https://user-images.githubusercontent.com/38794241/59141288-fa011800-8977-11e9-9434-a02c59b67429.png)
![Screenshot (13672)](https://user-images.githubusercontent.com/38794241/59141289-fa011800-8977-11e9-9821-df9160cb9684.png)

**Comment by LoneGazebo** [comment]
Yeah that's because there's a threshold of 'askability' that the AI has to hit, and an order of operations. It's a flaw in Firaxis's deal code that's not really solvable.

**Comment by HeathcliffWarriors** [comment]
Ah. Unfortunate.
