### ISSUE TITLE
Human/AI Diplo Inequalities for Coop War Requests

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5423]
_1. Mod version (i.e Date - 4/23):_ 6/2

DoSendStatementToPlayer function, when a coop war request is rejected:
```
#if defined(MOD_BALANCE_CORE)
				{
					if(eAgainstPlayer != NO_PLAYER && ePlayer != NO_PLAYER)
					{
						if(GetLoyalty() >= 5 && GetMajorCivOpinion(eAgainstPlayer) > MAJOR_CIV_OPINION_FAVORABLE)
						{
							GET_PLAYER(eAgainstPlayer).GetDiplomacyAI()->ChangeRecentAssistValue(ePlayer, -200);
							GET_PLAYER(eAgainstPlayer).GetDiplomacyAI()->ChangeNumTimesIntrigueSharedBy(ePlayer, 1);
							GET_PLAYER(eAgainstPlayer).GetDiplomacyAI()->SetApproachTowardsUsGuess(GetPlayer()->GetID(), MAJOR_CIV_APPROACH_WAR);
							GET_PLAYER(eAgainstPlayer).GetDiplomacyAI()->SetApproachTowardsUsGuessCounter(GetPlayer()->GetID(), 0);
						}
						else if(GetDiploBalance() > 5 && GetMajorCivOpinion(eAgainstPlayer) > MAJOR_CIV_OPINION_NEUTRAL)
						{
							GET_PLAYER(eAgainstPlayer).GetDiplomacyAI()->ChangeRecentAssistValue(ePlayer, -200);
							GET_PLAYER(eAgainstPlayer).GetDiplomacyAI()->ChangeNumTimesIntrigueSharedBy(ePlayer, 1);
							GET_PLAYER(eAgainstPlayer).GetDiplomacyAI()->SetApproachTowardsUsGuess(GetPlayer()->GetID(), MAJOR_CIV_APPROACH_WAR);
							GET_PLAYER(eAgainstPlayer).GetDiplomacyAI()->SetApproachTowardsUsGuessCounter(GetPlayer()->GetID(), 0);
						}
					}
					SetCoopWarAcceptedState(ePlayer, eAgainstPlayer, eAcceptedState);
				}
```
**Problem 1.** The AI does not change the # of times a coop war was denied for its approach calculation. To be equal with the human it'd need to be +1 for denying it and +2 for reporting it to the other AI.

**Problem 2.** There does not appear to be any change in the recent assist value with the asking AI for denying a coop war, as is the case for a human.

**Comment by LoneGazebo** [comment]
That's because the AI's choice is largely RNG, which is not really fair.

**Comment by HeathcliffWarriors** [comment]
Is the problem that the AI isn't choosing the method of denial intelligently or that it isn't choosing whether to agree to a coop war intelligently?

**Comment by HeathcliffWarriors** [comment]
After looking at the code some more, coop war desire seems to be properly evaluated but choosing whether to deny or report it to the other AI seems to be determined largely randomly.

Sounds like an opportunity for improvement, I'll see if I can come up with something to make things more fair. :)
