### ISSUE TITLE
Barbarian does more dmg than it should

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#5425]
_1. Mod version (i.e Date - 4/23):_
6-2

_2. Mod list (if using Vox Populi only, leave blank):_
Improved city view
Filters in traderoutes
Calypso's colored religion
city-states leaders v.10

_3. Error description:_ 
Barbarian kills my newly fortified pathfinder stationed on a hill - crossing a river! The pathfinder initially has 32 health, and gains 10 more by fortification. The dmg numbers presented doesn't represent the actual dmg done either - it's like there are "two barbs" attacking even though no other is in sight.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/59156660-53b03200-8a9f-11e9-8c8e-ee4226da1198.png)
![image](https://user-images.githubusercontent.com/20144751/59156682-9bcf5480-8a9f-11e9-8395-5f31ed8c0d86.png)
[BARBARIAN KILLING PATHFINDER.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3269352/BARBARIAN.KILLING.PATHFINDER.zip)

**Comment by ilteroi** [comment]
well, are you sure there is only one barbarian? they get movement promotions so another one might be hiding in the fog

**Comment by NewFellow** [comment]
So a barb warrior with movement promotions could be able to move more than 2 tiles?

**Comment by LoneGazebo** [comment]
desert walker promotion.

**Comment by NewFellow** [comment]
Still don't get it. All barbarians move around 2 tiles with this promotion, and suddenly one barbarian make a leap of 3 tiles? Or are they able to move 3 tiles all the time?

**Comment by TechpriestEnginseer** [comment]
I believe they ignore terrain cost and get double movement on desert.
