### ISSUE TITLE
43-civ no-eui city banner UI glitch

### ISSUE THREAD

**Issue by Tekamthi** [LoneGazebo/Community-Patch-DLL#5427]
_1. Mod version (i.e Date - 4/23):_
6/2 & 6/12 & 7/17 (possibly earlier releases as well)

_2. Mod list (if using Vox Populi only, leave blank):_
43-civ no-EUI cbp

_3. Error description:_ 
City banner UI is bugged.. shows range attack and espionage/diplomat icons at all times, as well as others.. worker icon? doesn't show production or defense values etc.

_4. Steps to reproduce (optional):_
load 43-civ cbp no-eui, start a game and build a city (as iroquois; did not test others though i assume same.  Tried multiple cache wipes and mod re-loads w/ same result as in screenshot below)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3418304/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/29668026/59275332-204dde80-8c2a-11e9-8fb8-bea5af839772.png)

**Comment by Vyyt02** [comment]
Just wondering, have you tried with the usual 22-civ version of VP? Do you get the same results?

**Comment by Tekamthi** [comment]
i have not,  admittedly... i did full check through steam though... if its just me then i have no idea what could be wrong... in the past 43-civ version has seen little glitches missed in main branch, i'm guessing this is one of those?  i'll report back here if i get a chance to test further.. i think there was at least one like on my forum post though so i expect its not just on my end

**Comment by LoneGazebo** [comment]
No logs, can't help without lua log at least.

**Comment by Vyyt02** [comment]
Please try the usual 22-civ version first. I have seen something similar in the past with the 22-civ version, it was a bad manual install.

**Comment by Tekamthi** [comment]
My steps to reproduce are accurate.  Funny bug report handling here... i love the project, but if you're not interested in maintaining the 43-civ version, or validating reported "steps to reproduce", I can't help further, and I'd suggest just taking the 43-civ out... Not fun to sink a handful of rare recreation hours on ignored bug hunts.   

If its truly just me then i guess don't bother tracking it down.. but problem persists in 6/12 43-civ.  6/12 normal is fine.  just sunk another half hour doing the various wipes, file checks, and resinstalls, confirming my OP was correct, at least on my rather vanilla win 10 system.

I suspect the fragment that plays 43-civ just don't post to git, and roll back to previous working version when these issues are encountered.  in the ~3 years i've been tagging along here, i've been the only one to report a 43-civ only issue at least a half dozen times.  Its not like it happens all the time, but these hiccups in 43-civ are not uncommon.

**Comment by Tekamthi** [comment]
problem persists in 7-17 version.  uploaded new (hopefully better) logs

**Comment by Tekamthi** [comment]
seems to be fixed

**Comment by NoxViginti** [comment]
I'm still having this issue, and it's driving me insane. How did you fix it? Who tf closes a ticket w/o saying how?

**Comment by Tekamthi** [comment]
works on my end in recent versions, open a new ticket and link to this one if you need, I can no longer reproduce it
