### ISSUE TITLE
spy action times

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5429]
it takes a long time to trigger a spy action in the 6/2 version:

<pre>
m_pCityEspionage
0x8d85edc8 {m_pCity=0x8d1ee040 {m_bChooseProductionDirty=false m_iCachePlayerClosenessTurn=-1 m_iCachePlayerClosenessDistance=...} ...}
    m_pCity: 0x8d1ee040 {m_bChooseProductionDirty=false m_iCachePlayerClosenessTurn=-1 m_iCachePlayerClosenessDistance=...}
    m_aiSpyAssignment: {m_akItems=0x8d85edcc {0, 1, -1, -1, -1, 0, 1, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...} }
    m_aiAmount: {m_akItems=0x8d85ee24 {174800, 54168, -1, -1, -1, 52900, 84150, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...} }
    m_aiRate: {m_akItems=0x8d85ee7c {2300, 9028, -1, -1, -1, 2300, 2550, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...} }
    m_aiGoal: {m_akItems=0x8d85eed4 {410186, 591663, -1, -1, -1, 209672, 755607, 2, -1, -1, -1, -1, -1, -1, -1, -1, ...} }
    m_aiLastProgress: {m_akItems=0x8d85ef2c {2300, 9028, -1, -1, -1, 2300, 2550, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...} }
    m_aiLastPotential: {m_akItems=0x8d85ef84 {2300, 9028, -1, -1, -1, 2300, 2550, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...} }
    m_aiLastBasePotential: {m_akItems=0x8d85efdc {2300, 6688, -1, -1, -1, 2300, 2550, 3811, -1, -1, -1, -1, -1, -1, -1, -1, -1, ...} }
    m_aiResult: {m_akItems=0x8d85f034 {1, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} }
    m_aiNumTimesCityRobbed: {m_akItems=0x8d85f08c {0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0} }
</pre>

check m_aiGoal and m_aiRate. either the former is too high or the latter too low.

ps: whoever wrote those Cv*Espionage classes should be whipped

**Comment by LoneGazebo** [comment]
Can tinker with ESPIONAGE_GATHERING_INTEL_COST_PERCENT, currently 350.

**Comment by ilteroi** [comment]
ok turns out it's my fault. i was trying to improve the global city spy potential ranking a while back and removed gold yield from calcPerTurn() for intelligence gathering. it's weird that gold should play a role there but i guess i'll simply revert that change.

**Comment by LoneGazebo** [comment]
🔔  shame! 🔔
