### ISSUE TITLE
Default governors almost ignore merchants

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#543]
Out of 20 cities only like 4 of them have at least 1 merchant. And I have -200 GPT.

**Comment by LoneGazebo** [comment]
Are you running gold strategies in those cities?

**Comment by Radost** [comment]
You meant priorities?
No.

**Comment by LoneGazebo** [comment]
I'd try that - since gold can be situational for the AI, it is not a prioritized specialist.

**Comment by Radost** [comment]
The problem with gold priority is it will almost ignore other specialists, which I don't want to happen.

**Comment by LoneGazebo** [comment]
I understand that, but the AI isn't great with Gold, and Gold isn't a critical resource for the AI (as, let's face it, most AI handicap bonuses are centered around gold costs), so the city AI compensates for that.
