### ISSUE TITLE
Can't Spread Religion to Vassal

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5433]
_1. Mod version (i.e Date - 4/23): 6/2

_2. Mod list (if using Vox Populi only, leave blank): 

_3. Error description: After I conquered and made Assyria my vassal and also in process took his capital (which was Head of Religion but I had my own) it seems that i am not able to spread my religion to the remaining of his cities (either with missionaries or prophets, i tried) and I don't know if this is intended to work this way (which I doubt).

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0002](https://user-images.githubusercontent.com/49090452/59419372-78741480-8dd3-11e9-833b-143106663de4.png)

**Comment by MoiMagnus** [comment]
Inquisitors prevent active religion spreading in the city.
As long as they keep their inquisitor around, you will need to rely on passive pressure.

**Comment by Aqinu** [comment]
Yeah, I apparently you are right but it seems that the area of its effect its bigger because it doesn't need to be placed inside the city for the effect to work accordingly to the Civilopedia description (which should be updated!)
![Civ5Screen0004](https://user-images.githubusercontent.com/49090452/59439910-c0f4f780-8dfe-11e9-8bd7-ecd255f46a70.png)

**Comment by Vyyt02** [comment]
Yeah, it is inside or next to a city, but it has been this way since vanilla. No change in VP.

**Comment by HeathcliffWarriors** [comment]
Of course, they can't use their Inquisitor to protect their city...if you capture it by force. :)
