### ISSUE TITLE
strange settling pattern

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5434]
![image](https://user-images.githubusercontent.com/1358966/59463455-4d66e080-8e26-11e9-8aaa-1736d77feca8.png)

this is with the latest 6/12 release ... anybody else seeing these disconnected empires?

**Comment by ilteroi** [comment]
uh, turns out SETTLER_DISTANCE_DROPOFF_MODIFIER is 67 now? corrupted database ...

**Comment by LoneGazebo** [comment]
Huh? Is that a CP issue?

**Comment by ilteroi** [comment]
damn, deleting the cache didn't help ....

database says:
SETTLER_EVALUATION_DISTANCE,24
SETTLER_DISTANCE_DROPOFF_MODIFIER,67

mod says:

-- Start of settle plot devaluation (prefer close settling)
UPDATE Defines
SET Value = '4'
WHERE Name = 'SETTLER_DISTANCE_DROPOFF_MODIFIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

-- Max range for settling (time offset will be added)
UPDATE Defines
SET Value = '8'
WHERE Name = 'SETTLER_EVALUATION_DISTANCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

wtf?

**Comment by LoneGazebo** [comment]
hmm...

**Comment by LoneGazebo** [comment]
For me:

"SETTLER_DISTANCE_DROPOFF_MODIFIER"	"4"
"SETTLER_EVALUATION_DISTANCE"	"8"

**Comment by ilteroi** [comment]
uh. maybe those are the default values? syntax error somewhere?

anyway i re-installed the mod, now it works ...
