### ISSUE TITLE
Location of Diplo "Mood" Tooltip Code?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5435]
I can't seem to find the current version of the code that decides which opinion modifier text keys are shown to the player when you mouse over the visible approach on the leaderhead screen, messages like e.g. "You have no contested borders.", "You are at war!", etc.

I tried searching the repository but I can only find old versions.

Mind pointing me to the right file? :)

**Comment by LoneGazebo** [comment]
All of that code (GetMoodInfo) is in LuaPlayer

**Comment by HeathcliffWarriors** [comment]
Found it in the lGetOpinionTable! At last!

Thanks G :)
