### ISSUE TITLE
Maritime City-States don't give you the bonuses

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5437]
_1. Mod version (i.e Date - 4/23): 6/2

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description: The bonuses from maritim city-state doesn't appear and apply from how the calculations are shown. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0007](https://user-images.githubusercontent.com/49090452/59518081-9756d180-8ecd-11e9-9833-ccc8b2e4a0bd.png)
![Civ5Screen0008](https://user-images.githubusercontent.com/49090452/59518086-99209500-8ecd-11e9-889a-5c1f9fcc820d.png)
![Civ5Screen0009](https://user-images.githubusercontent.com/49090452/59518090-99b92b80-8ecd-11e9-8f76-8ecc0c13100b.png)

**Comment by TechpriestEnginseer** [comment]
this bonus is a vanilla bonus and thus the Food bonus goes under your capital/city's tile.
