### ISSUE TITLE
DoWs started from Defensive Pacts do not increase War Weariness counter

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#544]

**Comment by LoneGazebo** [comment]
They do – there's no distinguishing between war types. It sounds like you're simply lucky (as the chance of increase is a random dice roll).

**Comment by Radost** [comment]
I am at war with Zulus for like 50 turns already and it haven't gone up even by 1 point.

**Comment by LoneGazebo** [comment]
That can happen. Like I said, the function does not discriminate between war types.

**Comment by Radost** [comment]
So what exactly does Clausewitz's Legacy do then?

**Comment by LoneGazebo** [comment]
Eh? It reduces the war weariness roll by 25% every time it is rolled.

G

**Comment by Radost** [comment]
So it's another obscure modifier then? Because it says something about 50% which isn't even a real percentage.

**Comment by LoneGazebo** [comment]
Sorry, 50%. Whatever the value is (not at my PC at the moment). 50% is a real percentage, unless I'm mistaken.

G
