### ISSUE TITLE
Cannot assign specialists

### ISSUE THREAD

**Issue by TheRealAyCe** [LoneGazebo/Community-Patch-DLL#5443]
_1. Mod version (i.e Date - 4/23):_
Vox Populi (6-12).exe

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Cannot assign specialists. Clicking does nothing.

_4. Steps to reproduce (optional):_
![cannotassignspecialist](https://user-images.githubusercontent.com/11407231/59563713-f6d3ef00-903d-11e9-80c2-7dc219c00895.jpg)

Save:
[save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3294072/save.zip)

**Comment by HeathcliffWarriors** [comment]
As of the most recent versions, you can only work as many specialists as you have positive happiness in a city. Certain buildings, Wonders and the Palace will give you "free" specialists that do not generate Unhappiness, however.

**Comment by TheRealAyCe** [comment]
That's probably it, people were a bit unhappy...

**Comment by HeathcliffWarriors** [comment]
Positive/net happiness = local happiness - local unhappiness, to be clear.

If you have 0 or negative net happiness and no free specialists left, you can't work specialist slots.

**Comment by TheRealAyCe** [comment]
In that case you should maybe gray out the specialist buttons? It's not clear why nothing is happening when the buttons look clickable.

**Comment by ilteroi** [comment]
yeah, even aside from the missing UI feedback, this new rule is pretty annoying. right i have a laborer because there are not enough tiles to work - i'm assuming he would be happier as a specialist!
