### ISSUE TITLE
Conscripted unit shown as unmoved even though it starts with 0 moves

### ISSUE THREAD

**Issue by TheRealAyCe** [LoneGazebo/Community-Patch-DLL#5449]
_1. Mod version (i.e Date - 4/23):_
Vox Populi (6-12)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The unit circle should probably display transparent, because a conscripted unit starts without moves?

![not_unmoved](https://user-images.githubusercontent.com/11407231/59902862-a4a91a00-93ff-11e9-9943-e6b91c86e93f.jpg)

**Comment by TechpriestEnginseer** [comment]
It's an old UI bug since the release of civ 5 that would just cost useless memory elements to fix. The UI gets refreshed at the end and beginning of the turn but never during the turn for sake of performance.

**Comment by ilteroi** [comment]
uh, maybe there's a fix after all? anyway not a big issue
