### ISSUE TITLE
City-States and Defensive Pacts 3

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#545]
![8930_2015-08-22_00029](https://cloud.githubusercontent.com/assets/1131228/9424636/6f4faffa-490c-11e5-82e7-1a612c5b27cd.png)
![8930_2015-08-22_00030](https://cloud.githubusercontent.com/assets/1131228/9424637/72a15168-490c-11e5-9042-c7cfff812549.png)
I am only at war with Zulus. The DPs he has now were signed after he declared a war on me.
![8930_2015-08-22_00031](https://cloud.githubusercontent.com/assets/1131228/9424645/96302fb4-490c-11e5-8560-648fbfd67f9b.png)
![8930_2015-08-22_00032](https://cloud.githubusercontent.com/assets/1131228/9424646/99158080-490c-11e5-833d-9456f3eb8aab.png)

**Comment by LoneGazebo** [comment]
Okay, so to make sure I understand...

1.) You are at war with Zulus, but not allied to these two CSs
2.) Zulus make some Defensive Pacts
3.) You ally Sydney and Cahokia, at which point they go to war with Zulus and Zulu DPs.

Sound right?

**Comment by Radost** [comment]
Looks like it's Zulu DPs of DPs.
![8930_2015-08-22_00036](https://cloud.githubusercontent.com/assets/1131228/9425000/27f116d6-491a-11e5-92ac-7edae238455f.png)

**Comment by LoneGazebo** [comment]
Here's a test version with a fix. Let me know if this works: https://www.dropbox.com/s/oop3110c11n420v/Community%20Patch%20%288-22b%29.zip?dl=0

**Comment by Radost** [comment]
It worked.
Before:
![8930_2015-08-22_00038](https://cloud.githubusercontent.com/assets/1131228/9425181/80980eba-4920-11e5-9098-a13d177dab69.png)
Old:
![8930_2015-08-22_00039](https://cloud.githubusercontent.com/assets/1131228/9425182/83cbdff8-4920-11e5-8dc8-e75984243bb3.png)
Test:
![8930_2015-08-22_00040](https://cloud.githubusercontent.com/assets/1131228/9425185/94f7e434-4920-11e5-9407-fffbe83ae948.png)

**Comment by LoneGazebo** [comment]
Excellent. I just reversed the CS war so that the major civ DoWs the CS and not the other way around. Prevents DP cascades that way.
