### ISSUE TITLE
Tutorial Integration!

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#5455]
Now tutorials can be integrated! The file I am attaching should be integrated into My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Modules\Tutorials (New Folder Name)

Tutorials_Master should update the database as an SQL File.

Advisors.lua and Advisors.xml can be integrated into the VFS as a file safely since EUI does not touch this file.

However OptionsMenu.lua is a different subject, but varying on the 6a and 6b it should be really easy to integrated into the VFS!

[Tutorial_Core.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3317262/Tutorial_Core.zip)

**Comment by TechpriestEnginseer** [comment]
Once I get an understanding of new recent mechanics, I will be able to establish a game tutorial within 3 days or so.

**Comment by ryanmusante** [comment]
Excellent work, Comrade!

**Comment by TechpriestEnginseer** [comment]
I am still waiting and confused why the tutorial system hasn't been implemented yet.

**Comment by LoneGazebo** [comment]
@TechpriestEnginseer necro as I'm going through old issues, I think I misunderstood this, and saw it as a feature request instead of a feature _offer_ Are you still interested in integrating this system?

**Comment by RecursiveVision** [comment]
Not to speak for them, but Enginseer did say a couple days ago they have no further interest in Civ 5 modding.

**Comment by LoneGazebo** [comment]
I see. No worries!

**Comment by TechpriestEnginseer** [comment]
It's still doable, but the game needs to stop its sudden balance changes so the tutorial doesn't outdate itself on a version.

**Comment by RecursiveVision** [comment]
@LoneGazebo
