### ISSUE TITLE
Allied City State Negative Influence

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5456]
_1. Mod version (i.e Date - 4/23): 6/12

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

I don't know if this is intended to be this way but for me is weird to see a city state which I am allied with to have negative influence. 

This happened because I had negative influence with this city state and I won the city-state Sphere of Influence in Word Congress and wouldn't make more sense that the influence to be set down at zero at least?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0002](https://user-images.githubusercontent.com/49090452/59962097-7dc71280-94e9-11e9-85a0-d0158c95eb28.png)

**Comment by TechpriestEnginseer** [comment]
dw is normal, it will recover over time. No need to add unnecessary memory elements. Sphere of Influences are usually colonies in real life and most of the time they don't like being colonized.
