### ISSUE TITLE
Coastal City Train Station Bug

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5457]
_1. Mod version (i.e Date - 4/23): 6/12

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

As you can see in the screenshots all coastal cities can build train station if they are only connected through normal road or/and lighthouse with the capital and have just one tile with railroad, which I think this shouldn't happened. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/59962161-689eb380-94ea-11e9-84c7-59d34abaae1c.png)

**Here just one tile with railroad already can build Train Station and its connected with roads and lighthouse to the capital (the capital also has just one railroad tile around city which isn't important)**
![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/59962235-4b1e1980-94eb-11e9-99fa-91ef8deaea94.png)

**And here I tried with another coastal city but I removed all road/railroad connection with the capital to see if just a lighthouse and one single railroad tile is enough and the result is that it is**
![Civ5Screen0004](https://user-images.githubusercontent.com/49090452/59962236-4d807380-94eb-11e9-8667-993525ff835a.png)

**Comment by ilteroi** [comment]
the code explicitly allows train stations if there is at least one plot with rail adjacent to the city - a complete connection is not required apparently. contradicting the 'pedia and just plain weird - why is that?

**Comment by TechpriestEnginseer** [comment]
I must assume it's for performance's sake since attempting to track one city if connected by a railroad completely might be costly...

**Comment by ilteroi** [comment]
it's actually very easy to check because there is a dedicated flag "industrial route to capital connected".

so, what's is gonna be? fix the pedia or fix the code?

**Comment by Aqinu** [comment]
I say that the code **needs fixing** because:

a) It doesn't make any sense in an island type map to have between islands train stations (for this reason there are Sea Ports), accomplishing this by just building one adjacent city tile railroad

b) I've checked if inland cities work correctly and they do, the city will get Train Station available only if there is a continuous railroad directly to the capital or by passing though other cities which are also connected continuously to the capital with railroads

**Comment by ilteroi** [comment]
i don't understand point b tbh, there is no distinction between coastal/inland.

islands are tricky btw, what if there are two cities there, connected by rail?

**Comment by Aqinu** [comment]
In testing I've tried with 2 cities and capital like this (all cities had previously road connections with capital):

City A is connected with City B and City B is connected to the capital (this is with roads first)

I connected City A with City B with railroads (still no Train Station Available to City A or B)

I connect City B afterwards with the capital with railroads, next turn City A and B have access to Train Station

Conclusion, a city gets access to Train Station if starting from the city, you can arrive in the capital through railroads (doesn't matter through what cities passes, maybe the city is connected with two cities one has railroads all the way to the capital the other city doesn't it will still get access because exist at list one node which is connected to the capital with railroads)


And to answer you question from what I can think there are two solutions:

a) City needs connection only through railroads to the capital (as in description, no exceptions, not through coastal cities), if it has, Train Station access if not it hasn't.
If there are two cities on other island than capital, none get Train Station available (doesn't matter if one is coastal city with connection to the capital and the other city has railroad connection the the coastal one)

Conclusion in this instance inland cities on other continents/islands than capital are weaker but the coastal cities still can build Sea Port

b) From the example above, if you have two cities on another island than capital, one coastal connected to the capital and another one connected to the coastal one with railroad then both cities have available Train Station (the way it is currently but only the that **the access to Train Stations of coastal and inland city to be at the same time when the railroad is finished**, not when you build one tile near coastal city, the city instantly gets access and after completing the connection with the inland city this one gets it)

**Comment by Aqinu** [comment]
To simplify the second solution it would be like this:

A. Coastal City on the same continent as the Capital
The coastal city gets access to Train Station when a **complete railroad route is made** (not only an adjacent tile) to the Capital. This means that you can go from the coastal city to the capital on railroad

B. Coastal City other continent than Capital
The coastal city gets access to Train Station when has connection to the Capital (through lighthouse directly or indirectly through other cities) and has **at least one completed railroad** to another city

**Comment by ilteroi** [comment]
ok i think the issue is that the "railroad to capital connected" flag is actually called "industrial route to capital connected" and it's also set for mixed water / rail connections once railroad is available - meaning a coastal city without any rail could indeed get a train station.

so from now on the requirement is a rail plot next to the city in addition to the connection to the capital.

**Comment by Aqinu** [comment]
> so from now on the requirement is a rail plot next to the city in addition to the connection to the capital.

,but this was the issue that I posted, I don't understand what you fixed?

**Comment by ilteroi** [comment]
well it was possible to have a train station on an island without any rail. not anymore.

also the rail plot needs to be part of a city connection, i forgot to mention. so no dead end railroad.
