### ISSUE TITLE
Tourism diplomat bonus but I don't have a diplomat?

### ISSUE THREAD

**Issue by TheRealAyCe** [LoneGazebo/Community-Patch-DLL#5459]
_1. Mod version (i.e Date - 4/23):_
Vox Populi (6-12).exe

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I had no diplomat-spies, yet the game claimed otherwise.

![diplomatbonus](https://user-images.githubusercontent.com/11407231/59983236-8c164b00-961d-11e9-862b-9b66d7e759d3.jpg)

**Comment by HeathcliffWarriors** [comment]
You get a free Diplomat because they're your vassal.

**Comment by TheRealAyCe** [comment]
Okay, thanks!
