### ISSUE TITLE
Golden age in progress shows negative turns to next golden age

### ISSUE THREAD

**Issue by TheRealAyCe** [LoneGazebo/Community-Patch-DLL#5460]
_1. Mod version (i.e Date - 4/23):_
Vox Populi (6-12).exe

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Is it supposed to display like this? Or should the next golden age immediately start and add turns to the current golden age?

![minusgoldenage](https://user-images.githubusercontent.com/11407231/59983266-d5669a80-961d-11e9-906e-2c28441b6afe.jpg)

**Comment by HeathcliffWarriors** [comment]
Intentional, part of EUI.

**Comment by ilteroi** [comment]
yes, this means you exceeded the threshold for the next golden age by two turns' worth of golden age points. probably instant yields from somewhere.
