### ISSUE TITLE
Fixed Some Typos

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5468]
_1. Mod version (i.e Date - 4/23): 6/12

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description: 

After I've managed to make all the changes, I saw that everything was fixed correctly (I've checked every change) but I've noticed some bugs that are shown in the **screenshots below** and I am not sure why, the integrity of the files is ok (I didn't change anything else and I've checked them by comparing the originals with changed files) so everything should be fine... 

Here is what I've fixed (just typo fixes, please open **README** files):

[Issue #5433 - Can't Spread Religion to Vassal.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3344089/Issue.5433.-.Can.t.Spread.Religion.to.Vassal.zip)
[Issue #5444 - Annex Puppet Raze Popup Description Needs Update.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3344090/Issue.5444.-.Annex.Puppet.Raze.Popup.Description.Needs.Update.zip)
[Issue #5445 - Unrest Notification Needs Update.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3344091/Issue.5445.-.Unrest.Notification.Needs.Update.zip)
[Issue #5448 - Some Typos.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3344092/Issue.5448.-.Some.Typos.zip)
[Issue #5467 - World Congress Resolutions Need Description Updates.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3344093/Issue.5467.-.World.Congress.Resolutions.Need.Description.Updates.zip)
[Issue #5380 - Leader Dialogue Typo.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3344094/Issue.5380.-.Leader.Dialogue.Typo.zip)
[Issue #5392 - Wrong Description UU Dutch Civ.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3344095/Issue.5392.-.Wrong.Description.UU.Dutch.Civ.zip)
[Issue #5432 - Workshop Description Update.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3344096/Issue.5432.-.Workshop.Description.Update.zip)

_4. Steps to reproduce (optional):

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![bug_1](https://user-images.githubusercontent.com/49090452/60413459-af249a00-9bdd-11e9-925d-5d97d778fc6f.png)
![bug_2](https://user-images.githubusercontent.com/49090452/60413462-b055c700-9bdd-11e9-8f1e-3618c9d361ac.png)
![bug_3](https://user-images.githubusercontent.com/49090452/60413463-b186f400-9bdd-11e9-8732-a03f999b17d6.png)

**Comment by LoneGazebo** [comment]
If you've gotten that far, why not just issue a content push? Half a dozen zip files are a pain. Also, the error you're getting means you have a database error from a bad update.

**Comment by Aqinu** [comment]
I've managed to do a pull request. I do have more fixes but this files don't exist in the mod  and I don't know where to add them...

...\Sid Meier's Civilization 5\Assets\DLC\DLC_01\Gameplay\XML\Text\en_US\LeaderDialog\Civ5_Dialog_GenghisKhan.xml
...\Sid Meier's Civilization 5\Assets\DLC\Expansion\Gameplay\XML\Text\en_US\LeaderDialog\Civ5_Dialog_Boudicca.xml

...\Assets\DLC\Expansion\Gameplay\XML\Text\en_US\CIV5GameTextInfos2_Expansion.xml
...\Assets\DLC\Expansion2\Gameplay\XML\Text\en_US\CIV5GameTextInfos2_Inherited_Expansion2.xml

...\Sid Meier's Civilization 5\Assets\DLC\Expansion\Gameplay\XML\Text\en_US\CIV5GameTextInfos2_Expansion.xml
...\Sid Meier's Civilization 5\Assets\DLC\Expansion2\Gameplay\XML\Text\en_US\CIV5GameTextInfos2_Inherited_Expansion2.xml

...\Sid Meier's Civilization 5\Assets\Gameplay\XML\NewText\EN_US\LeaderDialog\Civ5_Dialog_Catherine.xml

**Comment by HeathcliffWarriors** [comment]
@Aqinu There are SQL files which replace the text keys themselves. Leader Dialog is handled in the Core Text file in the Community Patch folder, if I'm not mistaken.

**Comment by Aqinu** [comment]
Thanks, solved now...
