### ISSUE TITLE
Sainthood and inquisitors

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#547]
My religion is Eastern Orthodoxy. I am spreading it on one of my captured cities:
![8930_2015-08-23_00007](https://cloud.githubusercontent.com/assets/1131228/9426298/d338ce5e-4950-11e5-89e9-67bdce60ea57.png)
First I use an inquisitor. Presumably the orthodox one, shame the game doesn't tell of which religion they are, but he was spawned from the city with Eastern Orthodoxy being a majority religion.
But I get this:
![8930_2015-08-23_00008](https://cloud.githubusercontent.com/assets/1131228/9426307/5d769df8-4951-11e5-945e-37b96106f45d.png)
After I use a missionary after an inquisitor, I get this result:
![8930_2015-08-23_00009](https://cloud.githubusercontent.com/assets/1131228/9426314/b689bd4e-4951-11e5-9b35-4fad16e8a6e8.png)

So what gives?

**Comment by LoneGazebo** [comment]
I think it is an issue of majority religion. Inquisitors remove the religion that is the majority in the city (unless it is your founded religion, IIRC).

G
