### ISSUE TITLE
Possible Trade Bug

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5475]
_1. Mod version (i.e Date - 4/23): 6/12

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

When I offer a Luxury to the AI and I press "What will make this deal work" the AI offers open borders instead of gold. Wouldn't be normal to priorities the gold instead, the AI is willing to offer a good deal in gold (but have to do it manually)?

Savegame:
[Gustavus Adolphu_trade_bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3348491/Gustavus.Adolphu_trade_bug.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/60485809-dd21e100-9ca6-11e9-90b0-7287ef169c24.png)
![Civ5Screen0002](https://user-images.githubusercontent.com/49090452/60485811-ddba7780-9ca6-11e9-8dc6-c471b85d9f34.png)

**Comment by TechpriestEnginseer** [comment]
afaik they gain a tourism bonus on you when they open their borders to you (compared to bnw where you gain a tourism bonus on them)

**Comment by Aqinu** [comment]
And how that would benefit me exactly? Most of the time I want gpt and flat gold.

**Comment by TechpriestEnginseer** [comment]
"What will make this deal work" is an option that the AI thinks is the best for them. Not for you.

**Comment by Aqinu** [comment]
I didn't know that, I though that this command just gives you (the player) the best trade possible with the current AI, based on what you trade with and their opinion (the AI) of you, so that the final deal is beneficial for the both parties (as far it can be). 

But this deal still doesn't make sense, the AI gets **one Luxury** and **Tourism Modifiers** on me and what I get in return apart from **nothing** (and the function that calculated this deal in this scenario is pointless, of course is a bad deal and I will never take it in any scenario)

Wouldn't make more sense so that command (as I initially thought) just helps you (the player) get the most out of the deal without the bother of doing it manually, if is not this case what is the purpose of this command if advantages the AI and most of the time you (the player) will change/refuse the deal?

**Comment by TechpriestEnginseer** [comment]
Because you click the button to make this deal work for the AI and the AI thinks that. You have a deal value UI for a reason for you to use to change it.
