### ISSUE TITLE
CTD when trying to buy a tile in a city on the same turn it was captured and annexed

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#548]
I have Iron Curtain tenet.

**Comment by LoneGazebo** [comment]
Investigated, but cannot reproduce.

**Comment by Radost** [comment]
The save then: http://www.mediafire.com/download/mn2v8upq3omutp2/Russia_CBP_CTD.Civ5Save
Newest version of compatibility files, EUI and community patch, quick turns+InfoAddict.
Capture Ergili, immediately annex and try to buy the fish tile.
