### ISSUE TITLE
CP only: Can't buy Spaceship Parts with gold Space Procurements

### ISSUE THREAD

**Issue by calvh** [LoneGazebo/Community-Patch-DLL#5480]
_1. Mod version (i.e Date - 4/23):_
6-12
Latest Civ 5 version (Steam) on Win 10

_2. Mod list (if using Vox Populi only, leave blank):_
CP only (no CBP)
All standard DLC

_3. Error description:_ 
The option to buy Spaceship Parts with gold is not available even though the Level 3 Freedom tenet Space Procurements is taken.

_4. Steps to reproduce (optional):_
In the save game attached, go to social policies, select Space Procurements. Go to city purchase screen to verify.
[info.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3365261/info.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Did you have a Spaceship Factory in the City?
