### ISSUE TITLE
Netherlands Mountain City Bug

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5482]
_1. Mod version (i.e Date - 4/23): 6/12

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description: 

As you can see in the screenshots, The Netherlands were able to settle on a mountain (to mention that not too long ago I've razed Inca's City in that exact spot), I don't see why they are able to do this, all that I've found which may be able to let them to do this (I didn't check) is in the Ballistics Tech, but they aren't even in Modern Era yet (so this isn't the case, even if the tech ability offers this option).

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![Civ5Screen0022](https://user-images.githubusercontent.com/49090452/60766418-311b3400-a0b2-11e9-97e6-01bf5b08e20f.png)
![Civ5Screen0023](https://user-images.githubusercontent.com/49090452/60766419-324c6100-a0b2-11e9-93f5-a9da7c4a71e5.png)
![Civ5Screen0024](https://user-images.githubusercontent.com/49090452/60766421-32e4f780-a0b2-11e9-9f7a-b2dde5c9e0c3.png)

**Here proof that 11 turn earlier the mountain was an razed Inca City (by me) and the current Netherlands City isn't a captured city from the Inca, instead is a founded city**

![Civ5Screen0026](https://user-images.githubusercontent.com/49090452/60766882-76dafb00-a0b8-11e9-9362-36e5ac657143.png)

**Comment by ilteroi** [comment]
i guess the razed incan city left a road, which enables others to enter the plot and found a city. let's call it an unplanned feature ...
