### ISSUE TITLE
Can't Pillage City State Embassy

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5487]
_1. Mod version (i.e Date - 4/23): 6/12

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description: 

I don't know if this is an exception from pillaging but I can't pillage on the city state embassy improvement. If it is not intended to work this way then after pillaging, the number of votes should be recalculated (of the AI/player)  in the world congress before and after repairing the tile.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![Civ5Screen0032](https://user-images.githubusercontent.com/49090452/60875129-ec260780-a241-11e9-8db2-2ca7ba8c6db8.png)

**Comment by Vyyt02** [comment]
You cannot pillage embassies. You can only invalidate them by absorbing them with a citadel.

**Comment by ryanmusante** [comment]
Is that the same with all improvements? Great people improvements can invalidate in each case?

**Comment by Aqinu** [comment]
Yes, it does make sense to not be able to pillage embassy because you can abuse this to decrease the votes of AI right before the voting in the world congress
