### ISSUE TITLE
Combat Preview Panel Bonuses Overflow Fix

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5488]
_1. Mod version (i.e Date - 4/23): 6/12

_2. Mod list (if using Vox Populi only, leave blank): 

_3. Error description: 

I've noticed that when you have above a certain amount of combat bonuses in the preview panel they begin to show over the dedicated area and you can barely see them.

To fix this problem, I don't know if it is possible, from what I've noticed the panel can hold up to 6 rows of bonuses (5 if the description of a bonus takes two rows) without overflowing, and to fix this it needs to be made to work something like this:
- if there are 5 bonuses then to be displayed as usual
- if there are more than 5 bonuses (even the panel can hold 6 rows I've accounted for a possible bonus with two rows which occupies), than all the bonuses to be added together and displayed into a single bonus (i.e. if you have 6 bonuses than the 5th and 6th are added together and displayed under a single bonus)
- and, of course, if in the event that the bonuses that were added together happens to give a negative bonus then to be colored accordingly in red

See the **screenshots** to see how I would like to look.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Here how is currently, which doesn't help me too much cause I barely see them**
![Civ5Screen0034](https://user-images.githubusercontent.com/49090452/60897355-9fa5f080-a270-11e9-9a31-f898b3c659ea.png)

**Here is with the fix and at least, in this instance I can see how much the bonuses help me (I added the last three bonuses and displayed them under a single name**)
![Untitled](https://user-images.githubusercontent.com/49090452/60897127-332af180-a270-11e9-83f0-0c5dffcf0346.png)

**Comment by ilteroi** [comment]
nice idea but hard to implement. 

in fact i think it would be easier to increase the size of the box (maybe depending on window size) but even that i don't know how to do

**Comment by Aqinu** [comment]
Can you elaborate better why is hard to implement, is because is impossible or you don't know how to change it to make it work this way or why is you reasoning behind this?

Theoretically you only have to put some conditions and add some numbers...

**Comment by TechpriestEnginseer** [comment]
`Theoretically you only have to put some conditions and add some numbers...` you make it sound so easy that you could do it yourself.

**Comment by Aqinu** [comment]
Then how the VP mod was made in the first place? You have the original developers' code and you changed it, that you understand how to do it but with this you don't, what's the difference? (other language, it's impossible to change, don't have access to the code, takes long time understanding how it works, too much of a hassle, too risky, or what is it?)

This entire mode is based on someone's else codes, that arguments doesn't make any sense... (and of course you have to understand someone's code so that you can start  to make changes I don't know why you bring that up)

**Comment by ilteroi** [comment]
well the combat preview is implemented in lua, which is different from the c++ gamecore. checking the bonuses one-by-one is much easier than keeping count and grouping them dynamically.

but you can take a look yourself. the relevant part is in enemyunitpanel.lua ...
.

**Comment by Aqinu** [comment]
I've tried to understand the code, I am not 100% sure that something like this would work but please if you can have a look: [PossibleFix.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3379134/PossibleFix.zip)

**Comment by ilteroi** [comment]
unfortunately i'm not the lua expert, so i couldn't tell. but if you tested it and it works you might create a pull request.
