### ISSUE TITLE
Feature Requests Re: AI Approach & Opinion Estimates

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5489]
I see you liked my AI Approach guess code enough to add it! :)

I have a few requests relating to this. I've noticed that the AI lacks a sensible mechanism for guessing what other players' Opinions and Approaches are towards each other and applying this to decision-making - obviously visible approach isn't the only factor. I aim to do some work on this part of the code as I think I could come up with something that works fairly easily, and it could be of use in other parts of the code.

In order to implement this, I have a few requests - I'm still new to C++ coding and don't want to screw something up. In particular, I don't understand how the code for memory values works.

1. Rename the GetApproachTowardsUsGuess function to GetVisibleApproach (as that's what it does), and rename the GetTrueApproachTowardsUsGuess function that I added to GetApproachTowardsUsGuess (not necessary, but would be nice to avoid confusion). This would require replacing all instances of the first function, however.

2. Edit the memory value for approach guesses so that there is a value stored for all other major civs, much like DoEstimateOtherPlayerOpinions, and edit the function Get(True)ApproachTowardsUsGuess so that it returns the memory value for a specific player.

3. Add functions which set and get the estimate of one player's *approach* towards another, like GetMajorCivOtherPlayerOpinion and SetMajorCivOtherPlayerOpinion.

4. Do 2-3 for the GetApproachTowardsUsGuess_Counter_ memory value as well.

If this isn't too arduous or problematic memory-wise, I would really appreciate it whenever there was time. :) - and I intend to write code so that the AI has intelligent Approach and Opinion estimates for all major civs towards all other civs. This would bring it one step closer to smarter psychology/decision-making and could be of use in other parts of the code (particularly in the diplomacy AI itself), or for modders.

If you're too busy or it can't be done, I understand, I'll try to figure it out on my own, but I thought I might as well ask; it seemed like the path least likely to screw something up.

Thanks for considering it!

**Comment by LoneGazebo** [comment]
To make you feel better the diplo AI memory management functionality is absurdly overdone. It's like they decided to mix the worst parts of two memory management systems. Anyways.

1. I don't see any need to rename mainline functions, as they have knock-on effects in some instances. It doesn't hurt it as-is.

For the memory elements, you don't need them TBH. Unless you are going to crunch some major numbers each pass, you can just do a direct call for the data each time via the function itself.

**Comment by LoneGazebo** [comment]
If you do intend to do some major crunching, we can cross that bridge later.

**Comment by HeathcliffWarriors** [comment]
Thanks for the feedback.

1. It isn't necessary, I just think it's confusing to others to have SetApproachTowardsUsGuess affect a different value than GetApproachTowardsUsGuess.

2. I _did_ have some concerns about performance - but after further thought and your feedback, I've come up with a way that might work without using the new memory elements.

I'll spend some time working on this and submit a pull request when I have something ready - or I'll reopen this if I think there will be a performance issue.

Thanks G! :)
