### ISSUE TITLE
missing text

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5494]
_1. Mod version (i.e Date - 4/23): latest

_2. Mod list (if using Vox Populi only, leave blank):_

see the bottom of the screenshot
![20190713061906_1](https://user-images.githubusercontent.com/16341598/61166465-7ddd8f80-a536-11e9-91a9-37401780c2d5.jpg)

**Comment by HeathcliffWarriors** [comment]
That's usually caused by a bad installation/LUA error. Try reinstalling.
