### ISSUE TITLE
how are these yields possible?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5497]
![image](https://user-images.githubusercontent.com/1358966/61181186-f588e880-a622-11e9-9f74-2a19ea49bec4.png)

they chose authority and fealty - not artistry - so they get food and production bonus. not GAP and science.

note that the other aztec cities apparently don't get this bonus!

**Comment by Aqinu** [comment]
Maybe from Religion?

**Comment by ilteroi** [comment]
hmm. did some debugging. apparently the "revealed owner" is not set for the city plot, so the UI defaults to the active player which does have artistry. no idea how that came about.

**Comment by ilteroi** [comment]
maybe fixed. but in any case only a graphical glitch
