### ISSUE TITLE
AI constantly trades maps

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#550]
It gets annoying after a while. And they are quite useless after the whole map has been revealed.

**Comment by LoneGazebo** [comment]
I'll increase the base value needed for it to be worthwhile.

**Comment by Radost** [comment]
Does it mean they will use them in trades less often?

**Comment by LoneGazebo** [comment]
Yep. They'll only trade if it is worthwhile, and that metric has been sharpened a bit so it takes a better map for it to be so.

**Comment by Radost** [comment]
Looks like the trade deal optimizations led to AI shoving maps into every deal again.
