### ISSUE TITLE
Missing Promotion Displayed for Civilian Units from Askia's UA 

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5500]
_1. Mod version (i.e Date - 4/23): 6/12

_2. Mod list (if using Vox Populi only, leave blank): 

_3. Error description:

All Civilizan Units (Settler, Worker, Religious Units...) don't have displayed the promotions from the Askia's UA . 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![Civ5Screen0174](https://user-images.githubusercontent.com/49090452/61366477-52d6a100-a892-11e9-84d0-06bc15954cb0.png)
![Civ5Screen0173](https://user-images.githubusercontent.com/49090452/61366179-bf9d6b80-a891-11e9-9dba-5ccc660c093b.png)
![Civ5Screen0050](https://user-images.githubusercontent.com/49090452/61366177-bdd3a800-a891-11e9-892d-f7c70275a951.png)

**Comment by HeathcliffWarriors** [comment]
Those promotions are for military units only.

**Comment by Aqinu** [comment]
Apparently you are indeed right, my bad, I thought that the extra movement from the civilian units when moving alongside rivers is from the Amphibious Promotion, but in fact is from the river connection (previously I thought that that the river connection only gives you income from gold without the expense from the roads but in fact this promotion acts exactly as an invisible maintenance free road formed by the river)
