### ISSUE TITLE
Wierd Calculation Askia's UA

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5501]
_1. Mod version (i.e Date - 4/23): 6/12

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: After I  settled the second city I've noticed that the gold income is with negative which shouldn't happen, and after some turns it fixed itself... 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![Civ5Screen0175](https://user-images.githubusercontent.com/49090452/61366708-c9739e80-a892-11e9-80db-b79f38121eaf.png)
![Civ5Screen0053](https://user-images.githubusercontent.com/49090452/61366866-15264800-a893-11e9-9731-b828fe031046.png)
![Civ5Screen0054](https://user-images.githubusercontent.com/49090452/61366868-16577500-a893-11e9-9194-e6d4bd20bc50.png)
![Civ5Screen0057](https://user-images.githubusercontent.com/49090452/61366874-18213880-a893-11e9-89c1-ddb58bffee13.png)
![Civ5Screen0058](https://user-images.githubusercontent.com/49090452/61366876-19526580-a893-11e9-97ce-c831507e1d0d.png)

**Comment by ilteroi** [comment]
that's a feature. city connections have a negative bias and only turn a profit for larger cities
