### ISSUE TITLE
Typo still occurring despite fix in core text file

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5509]
_1. Mod version (i.e Date - 4/23):_ 7/17-1

This fix has been here for a while, so I wonder why it isn't working.

![Screenshot (15775)](https://user-images.githubusercontent.com/38794241/61469116-a86f8400-a94c-11e9-8424-7524d261343b.png)
![4f326754ce580e4f9aef9e5903f428d7](https://user-images.githubusercontent.com/38794241/61469170-b91ffa00-a94c-11e9-89a1-caa1fb0fc75c.png)
![c6a589b063fed7d2dac0376e94bec77d](https://user-images.githubusercontent.com/38794241/61469254-db197c80-a94c-11e9-9ab3-da20f6bfa20e.png)

**Comment by HeathcliffWarriors** [comment]
Still occurring in 7-17-3.

**Comment by LoneGazebo** [comment]
Pull request?

**Comment by HeathcliffWarriors** [comment]
No, I'm saying the fix is already in the file (the period is added), but it's not being applied ingame despite this.

**Comment by HeathcliffWarriors** [comment]
Found the problem, will fix in next pull request :)
