### ISSUE TITLE
LandSea Extractors bonus tooltip bug

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#551]
It shows the bonus twice and it's not even +100p increase.
![8930_2015-08-23_00016](https://cloud.githubusercontent.com/assets/1131228/9429263/b226c3cc-49e3-11e5-9590-013587171ee8.png)
![8930_2015-08-23_00017](https://cloud.githubusercontent.com/assets/1131228/9429264/b5d13ad4-49e3-11e5-8874-b08fd47c1b2b.png)

**Comment by LoneGazebo** [comment]
I think this is just a lua quirk, but I'll look at the code.

**Comment by LoneGazebo** [comment]
I rewrote this last night, hopefully it is fixed. We'll see.
