### ISSUE TITLE
Venice puppet cities don't produce buildings

### ISSUE THREAD

**Issue by Necamijat** [LoneGazebo/Community-Patch-DLL#5510]
Version 17-7-2019 (with day 1 hotfix)

Standard VP installation with EUI (auto-installed)

Venice's Colonias (Settled Puppets) don't produce buildings normally, can only produce invested buildings. Will idle if no buildings are invested into.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3407302/Logs.zip)

**Comment by Amecareth002** [comment]
I can confirm this bug, it's happening to me as well, but only to those brand new cities you found and not on those you buy. That means you can still use the Merchant of Venice tu buy city-states as normal.

**Comment by LoneGazebo** [comment]
I know why, easy fix (I left a debug value in).
