### ISSUE TITLE
Decalared war on AI who asked me to go to war with someone else glitch

### ISSUE THREAD

**Issue by NT3NS3** [LoneGazebo/Community-Patch-DLL#5511]
_1. Mod version (i.e Date - 4/23):_7-17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ I've made friends with Darius in attached save game. On the next turn Darius asks me to go to war with Nebuchadnezzar.  If I accept and click "Yes, let's get this war started" Darius replies "Perfect" but then I am at war with him, instead of teaming up with him against Nebuchadnezzar.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Washington7.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3409372/Washington7.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![CivilizationV_DX11_2019_07_19_13_48_39_819](https://user-images.githubusercontent.com/53070320/61508311-a0871100-aa2c-11e9-9f27-616979b02e13.jpg)
![CivilizationV_DX11_2019_07_19_13_49_02_200](https://user-images.githubusercontent.com/53070320/61508322-ab41a600-aa2c-11e9-8c7f-94c0235f0ece.jpg)
![CivilizationV_DX11_2019_07_19_13_49_27_503](https://user-images.githubusercontent.com/53070320/61508622-058f3680-aa2e-11e9-97f9-c90e255ea2d6.jpg)

**Comment by LoneGazebo** [comment]
@heathcliffwarriors what did you do :)

**Comment by NT3NS3** [comment]
I tried choosing "Give us 10 turns to prepare" and he doesn't follow up on my promise 15 turns later. Something is messed up.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo That wasn't my doing, the bug was present last patch too (#5410), and I didn't alter that part of the code.

**Comment by HeathcliffWarriors** [comment]
Someone else has tinkered with the coop war code however, including the soon/accepted and war declaration stuff - those aren't my changes.

**Comment by NT3NS3** [comment]
Any chance for a fix? I needed this, Nebuchadnezzar is out of control like he always is lol hate playing against him.

**Comment by LoneGazebo** [comment]
I’ll take a look.
