### ISSUE TITLE
7-17, Strategic Resource Units available before S. Resource Tech

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5516]
_1. Mod version (i.e Date - 4/23):_
7-17
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I was able to start building train stations/sea ports before I had unlocked coal, and now I can build planes before I have unlocked oil (see screenshot). The unit do seem to consume strategic resources properly, so I think the issue is that the resources are not "hidden" like they are supposed to be.

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/61586737-c56ca880-ab40-11e9-9b35-f5d77c3f7ac9.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Followup, when I tried to build a unit, suddenly its showing that I have oil from Manilla (CS). As you can see, I still have not researched combustion.

![image](https://user-images.githubusercontent.com/20593976/61586757-1b415080-ab41-11e9-88d5-553b5ddf49bd.png)

**Comment by HeathcliffWarriors** [comment]
Is the oil coming from a tile with an embassy on it? #5348

**Comment by MoiMagnus** [comment]
Are you Statecraft? Foreign Service give you strategic resource of every kind, maybe that's the source?

Moreover, if enough civs have unlocked the tech, the city states unlock the tech automatically, so they can have resources before you do. So that's another possible source.
