### ISSUE TITLE
A foreign corporation spread wrong text

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#552]
![8930_2015-08-23_00015](https://cloud.githubusercontent.com/assets/1131228/9429299/ce9fc052-49e4-11e5-8b13-db88ee21b82d.png)
It says Hexxon Refineries was spread to Honolulu, while in fact it was other way around.

**Comment by LoneGazebo** [comment]
Fixed - text key values flipped.
