### ISSUE TITLE
venice settling strategy

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5528]
![image](https://user-images.githubusercontent.com/1358966/62237566-7b51b580-b3d1-11e9-8697-e9ff24b41fe5.png)

here venice chose to buy out geneva for their first puppet - but they can always do that later. wouldn't it be better to found a new city as long as there is space?

**Comment by LoneGazebo** [comment]
@ilteroi the code looks for the best settle spot versus the nearest available CS - if the nearest CS is 2/3 closer than best settle, it goes for the puppet.

**Comment by ilteroi** [comment]
i know - but is that the optimal strategy?

also, did you do something about settling distance? i see a lot of far-flung cities recently ...

**Comment by LoneGazebo** [comment]
@ilteroi nope, didn't touch settling. 
Re: optimal, not sure - I'm open to ideas.

**Comment by ilteroi** [comment]
ok, should be better now
