### ISSUE TITLE
Trade Confederacy doesn't increase City State influence

### ISSUE THREAD

**Issue by Adonis-VII** [LoneGazebo/Community-Patch-DLL#5548]
_1. Mod version (i.e Date - 4/23):_
August 5th

_2. Mod list (if using Vox Populi only, leave blank):_
Modpack

_3. Error description:_ 
As Venice, I have trade routes with 5 different city states. The influence doesn't move with any of them.

_4. Steps to reproduce (optional):_
Select Trade Confederacy policy, send trade route to nearby city state. Watch influence over a number of turns.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
As far as I know Trade Confederacy Policy role is to stagnate the influence with City-States, because normally the City-State Influence decays every turn (decays faster if hostile).

**Comment by bentakacs** [comment]
Exactly as Aqinu said, it doesn't let your City-State influence decay (which is pretty good), it shouldn't increase it.

Practically, if the City-State has Hostile trait it can decay very slow (like -0.25 / Turn) and if it has Friendly it can increase a miniscule (since it's +1 / Turn). I think ...(confirmation needed :D)

**Comment by TechpriestEnginseer** [comment]
Correct.
