### ISSUE TITLE
AI flavors

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5549]
can anyone explain to me what's the difference between these two methods and what's the expected range of values?

```
	// External routines to retrieve flavor values
	int GetIndividualFlavor(FlavorTypes eType);

	// External routines to retrieve Default Personality flavor values
	int GetPersonalityIndividualFlavor(FlavorTypes eType);
```

for example for FLAVOR_OFFENSE i'm seeing GetIndividualFlavor(0)==303 and GetPersonalityIndividualFlavor(0) == 8. a difference of two orders of magnitude seems suspicious ...

**Comment by LoneGazebo** [comment]
The second is just a pure database lookup. The first is after it has been affected by flavor weights from GS, Economy AI, etc.

**Comment by ilteroi** [comment]
so is the base contribution just 8 and basically irrelevant or is that scaled up somehow?

**Comment by ilteroi** [comment]
so you're telling me that the base value doesn't make a difference in the end because all other contributions are much larger?
