### ISSUE TITLE
Tourism Yield Tooltip fix?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#555]
Building_YieldChangesPerPop allows tourism to be yielded basing on population. However, it does not show in the CityView tooltip in how this tourism is added to the total tourism, but rather shows only that the Great Works are producing Tourism and such. The CityView I am referring which is similar to below.

![image](https://cloud.githubusercontent.com/assets/13937047/9431965/819c2f9e-49cf-11e5-8538-6876c4ecd869.png)

I believe this fix will help opening modding better.

**Comment by LoneGazebo** [comment]
I'm not sure what you are asking.

**Comment by TechpriestEnginseer** [comment]
![2015-08-23_00001](https://cloud.githubusercontent.com/assets/13937047/9433378/b7ffd7fe-49e6-11e5-978d-26a27e0c8744.jpg)
![2015-08-23_00002](https://cloud.githubusercontent.com/assets/13937047/9433379/b8007966-49e6-11e5-8b8f-8bdc9301d251.jpg)
The process is yielding +1 tourism (doubled from The Internet) yielding +2 in total, but does not show what is causing the tourism to appear.

**Comment by LoneGazebo** [comment]
Gotcha. Added a tooltip that'll generically be called 'Tourism from Buildings' - will pull all yields gained in the city for tourism (base yield gains not covered by other tooltips).

G
