### ISSUE TITLE
Where does the CS heavy tribute go?

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#556]
![8930_2015-08-24_00015](https://cloud.githubusercontent.com/assets/1131228/9443687/d8f17624-4a9b-11e5-9846-7bddaec30a20.png)
![8930_2015-08-24_00016](https://cloud.githubusercontent.com/assets/1131228/9443689/db601c76-4a9b-11e5-9863-0b7d033c6781.png)
![8930_2015-08-24_00017](https://cloud.githubusercontent.com/assets/1131228/9443690/ddb205d4-4a9b-11e5-922e-c4d1c90bb3eb.png)

**Comment by LoneGazebo** [comment]
Your capital. It may not refresh until the next turn. Did it?

**Comment by LoneGazebo** [comment]
Looks like there's a bug - the production value is negative! Odd!
