### ISSUE TITLE
Fix for Unit:IsInCombat() and related methods

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#5561]
Seems this is an old issue wherein the methods **unit:IsInCombat()**, **unit:IsAttacking()**, **unit:IsDefending()**, and **unit:IsFighting()** were broken by some patch around Gods and Kings. You can find some discussion on it [here](https://forums.civfanatics.com/threads/gods-and-kings-api-documentation-changes.465247/page-3#post-11776520). Would it be possible to get a fix, or to look into why they no longer work?

**Comment by ilteroi** [comment]
well, shouldn't be too hard to fix but what is the desired behavior? when exactly should these four functions return true or false? i need a formal specification, then i can check.

**Comment by JFDaly** [comment]
Well, based on what they're called, I had assumed they're meant to return true or false depending on whether the unit is fighting another unit (presumably, IsInCombat and IsFighting are interchangeable), and whether that unit is defending against the other unit (IsDefending) or is attacking instead (IsAttacking).

**Comment by ilteroi** [comment]
believe me i'm not trying to make this complicated ... can you answer the following questions?

* is this related to the combat animation? 
* if not, how would you define the duration of combat? 
* what is the difference between IsInCombat() and IsFighting()?

**Comment by JFDaly** [comment]
All I know is they're vanilla methods that I can only assume operate as far they're described. They're in the DLL, but were broken by Gods and Kings. I don't know the answer to any of those questions, so forget I made this request then; I merely thought it being an existing set of methods from the base game it was something easy enough to look into.

**Comment by ilteroi** [comment]
from looking at the code i can tell you that

* calling CvUnit::SetAttackPlot(...) with a non-null argument should cause CvUnit::IsAttacking() to become true
* calling CvUnit::SetCombatUnit(...) or CvUnit::SetCombatCity(...) with a non-null argument should cause CvUnit::IsFighting() to become true

* IsInCombat() means IsFighting() OR IsAttacking()
* IsDefending() means IsFighting() AND NOT IsAttacking()

looks like a mess to me, but without a spec it's hard to tell what is correct
