### ISSUE TITLE
Pacal's UA, Can't Close "Choose Great Person" Window

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5562]
_1. Mod version (i.e Date - 4/23): 7/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

When it gives you the choice to  choose your Great Person you can't come back to the map when you hit **ESC** key. This doesn't happen with **Leaning Tower of Pisa** Wonder. Would be nice if you have the same functionality also implemented here.

![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/63228327-d5d47980-c1f9-11e9-92c3-8d9d74cca344.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Can't control netcode UI options.
