### ISSUE TITLE
unexpected missionary result

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#557]
i tried to spread my religion (sikhism) to a foreign city (pop 12) without a majority religion (split between four contenders). afterwards, protestantism was the majority!

confucianism 0
buddhism 0
sikhism 3
protestantism 7

don't have the numbers from before, but something seems to be broken here.

**Comment by LoneGazebo** [comment]
huh. I'll look.

**Comment by LoneGazebo** [comment]
Well, only change I see to that formula/area is a section on the relgionclasses that was, I believe, edited by you. :)

#if defined(MOD_BALANCE_CORE)
ReligionTypes CvCityReligions::GetReligiousMajority()
{
	return m_majorityReligion;
}

bool CvCityReligions::ComputeReligiousMajority()
{
#else
/// Is there a religion that at least half of the population follows?
ReligionTypes CvCityReligions::GetReligiousMajority()
{
#endif

**Comment by LoneGazebo** [comment]
I removed all code associated with that change (I doubt it made much of a performance impact anyways)- we'll see if that fixed it.

**Comment by LoneGazebo** [comment]
Radost, try out Inquisitors with this version, see if my fix for this fixed that as well.
G
