### ISSUE TITLE
Skirmishers wrong movement cost ui

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#5572]
8-21 VP only

The preview still assumes they deplete  all movement points upon moving over rough terrain. 

![civgajabug1](https://user-images.githubusercontent.com/53142313/63666528-5550e280-c7d0-11e9-9e6b-be8191812715.png)

**Comment by ilteroi** [comment]
need to update to the latest version first :)

**Comment by ilteroi** [comment]
ok the promotion is a bit weird: floodplains are considered bad but desert is ok?

also it's hard to mix multiplicative effects with additive effects

**Comment by LoneGazebo** [comment]
Danke!
