### ISSUE TITLE
Warmonger AIs bankrupting themselves.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#5575]
8/21, but I've noticed for at least two versions or so now. Emperor difficulty, communitu_79 map, Huge size, 12 major and 24 minor, no events, no ruins.

In several games, I've noticed AIs taking Authority in particular managing to completely destroy their economy, presumably through unit costs. Here's an example:

![image](https://user-images.githubusercontent.com/22875626/63774949-5b1bf600-c8ac-11e9-94de-d25afea31203.png)

He has as much negative GPT as I have positive, and I watched him get down to -81 earlier. He's dead last in techs as a result, and based on experience he's unlikely to recover from it. 

I've even watched Shaka manage to do this, which is particularly impressive with his 25% discount on melee troop maintenance. It seems like Authority AIs are building units with no regard for their maintenance, and it's really been hurting them every time I've seen it happen.

**Comment by ilteroi** [comment]
i can confirm that
