### ISSUE TITLE
Local Happiness bug

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#5578]
Using the latest beta from August 21, seem to be getting an issue wherein Local Happiness always increases with Unhappiness from Population, despite having no sources of Local Happiness. No other mods running, besides In-Game Editor to test.

You can see in this first screen that I have 7 Local Happiness to meet the 7 Population in the capital, and in the second, see that there is nothing in the city to grant that Local Happiness. This Local Happiness increases/decreases with the Unhappiness from the Population count, as well.

![Image of Yaktocat](https://i.imgur.com/D5MChw4.jpg)

![Image of Yaktocat](https://i.imgur.com/amXbs9p.jpg)

Any idea what's going on?

**Comment by LoneGazebo** [comment]
@JFDaly did this resolve? Or is it still an issue? Meant to report back, I wasn't able to replicate any issues.

**Comment by JFDaly** [comment]
Could there be some kind of setting that's been accidentally left active (I haven't touched anything myself) meant for the CBO's happiness overall?

**Comment by LoneGazebo** [comment]
Hmm, let me check. Any other mods aside from CP and IGE?

**Comment by JFDaly** [comment]
None

**Comment by Lelsn1** [comment]
Had the same issue, so I started looking for an older version without this problem. 
Every non-beta release since 5-19 has this issue, with 2-17 being the latest version where the mechanic works properly. I haven't tried the betas between 2-17 and 5-19, but I assume something caused that along the way.
Hope it helps!
