### ISSUE TITLE
AI won't capture at sea

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#5579]
@ilteroi tests with naval AI show that, even when it can, the AI is very reluctant to capture with melee ships. Possible bug?

	Line 113399: 261, Siam, Zone -2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 505, expected damage 87
	Line 119224: 269, Siam, Zone 2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 505, expected damage 135
	Line 119969: 270, Siam, Zone 2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 488, expected damage 134
	Line 120715: 271, Siam, Zone 2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 427, expected damage 112
	Line 121512: 272, Siam, Zone -2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 447, expected damage 107
	Line 122256: 273, Siam, Zone -2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 467, expected damage 96
	Line 122939: 274, Siam, Zone -2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 471, expected damage 165
	Line 123749: 275, Siam, Zone 2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 424, expected damage 222
	Line 124498: 276, Siam, Zone 2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 362, expected damage 248
	Line 125291: 277, Siam, Zone 2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 323, expected damage 245
	Line 125944: 278, Siam, Zone 2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 298, expected damage 220
	Line 126717: 279, Siam, Zone 2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 146, expected damage 252
	Line 127456: 280, Siam, Zone 2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 25, expected damage 293
	Line 128134: 281, Siam, Zone 2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 21, expected damage 291
	Line 128145: 281, Siam, Zone 2604, attempting capture of TXT_KEY_CITY_NAME_KAESONG, required damage 1, expected damage 74

**Comment by ilteroi** [comment]
well the log is ok if somewhat misleading. they slowly reduce the hitpoints to zero. but "expected damage" should be "max possible damage" - usually not all units can attack the city in one turn.

the real question is the four turn delay between 281 and 285. need to repro

**Comment by ilteroi** [comment]
i can confirm there seems to be a problem, will check

**Comment by ilteroi** [comment]
it might be the problem is that they have too many units with too many possible moves, leading to an aborted search ...
