### ISSUE TITLE
Game crashes on the same player's turn every time

### ISSUE THREAD

**Issue by cburns33** [LoneGazebo/Community-Patch-DLL#5581]
_1. Mod version (i.e Date - 4/23):_
8/12/2019

_2. Mod list (if using Vox Populi only, leave blank):_
1. Community Patch (v. 89)
2. Community Balance Overhaul (v. 13)
3. City-State Diplomacy Mod for CBP (v. 27)
4. C4DF - CBP (v. 11)
5. More Luxuries - CBO Edition (5-14b) (v. 155)
6a. Community Balance Overhaul - Compatibility Files (EUI) (v.1)
7a. Promotion Icons for VP (v. 1)
7b. UI - Promotion Tree for VP (v. 22)
- InfoAddict (v. 22)
- Ingame Editor (v. 39)

_3. Error description:_

Playing as England in a single-player, 8 civ game on the Fractal Islands map. Right as the game is transitioning from turn 500 to 501, the game crashes to desktop with no error messages as Polynesia (CPU) is taking its turn.

Polynesia and I have been in a war with Songhai for a while, and we are both contesting the capture of its final city. At first, I thought the crash was being caused by something happening when Polynesia takes control of the city on its turn, as I've read about leader screen transitions causing crashes before. However, I used the Ingame Editor to allow myself to take the last Songhai city THEN hit next turn, and the game still crashes on Polynesia's turn. 

Polynesia is also at war with The Netherlands and was going to capture two small cities on that same turn, so I also tried using the Ingame Editor to force control to be given to Polynesia. Still crashed. I've been playing this particular game for a number of hours and haven't had any issues with crashes, so this has been frustrating. Appreciate any help I can get!

_4. Steps to reproduce (optional):_

Use the quicksave file provided and proceed to the next turn as you normally would. Should crash right at Polynesia's turn.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3553081/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[quicksave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3553090/quicksave.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3553097/CvMiniDump.zip)

4. Screenshots (optional):

N/A

**Comment by Edaka** [comment]
Old, closing for now.
