### ISSUE TITLE
Crashing on opening the tech screen in late game

### ISSUE THREAD

**Issue by Jack3552** [LoneGazebo/Community-Patch-DLL#5585]
_1. Mod version (i.e Date - 4/23):_ 7/29

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ The game instantly closes upon opening the tech screen, but only in the late game and not 100% of the time. I'm playing on windows 10.

_4. Steps to reproduce (optional):_ It doesn't happen every single time, but maybe every other turn or so when I go to open tech screen. Reliably happens within 10-15 minutes of gameplay. 

I've included the save, logs folder and .dmp. If there's anything else I can provide please let me know.

[lategamecrash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3562073/lategamecrash.zip)

Additional info here: https://www.reddit.com/r/civvoxpopuli/comments/ctiwcc/im_having_major_issues_with_crashing_in_late_game/

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
Size of the map? Are you using any texture enhancing pack (2K texture terrain, or RED,...)?

This might be a memory overflow, in which case, there are no fix (playing the late game in strategic view do solve the issue, but strategic view is kind of ugly...)

**Comment by Jack3552** [comment]
Standard size map, and not using any texture packs. Is there anything I could look out for or test to ascertain if overflow is the cause? I've had task manager open on the other monitor while playing, and I'm seeing Civ steady at about 1700MB RAM, and it doesn't appear to spike before the crash.

**Comment by Edaka** [comment]
Old, closing for now.
