### ISSUE TITLE
CTD on 08/31

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#5588]
_1. Mod version : 08/31

_2. Mod list: 4UC and custom civs

_3. Error description: CTD in early game. Haven't changed any of my mod setup since switching to 08/31. 
CTD happens within 100 turns, no commonanilities for why it occurs

**Comment by Padre19** [comment]
CTD in 3 games ( first 100 turns) when AI capture another AI city. With my mods setup i don't had problems in previous VP versions.

**Comment by ryanmusante** [comment]
@pineappledan I encounter this recently as well, typically each session will last near to 100 turns. Have you tested with base VP only minus mods?

**Comment by Padre19** [comment]
What custom civilizations do you use ?

**Comment by ryanmusante** [comment]
@Padre19 I'm not using custom civs in this case. But, what I do know is my crashes are occuring at the point of selecting (automate) on scouts and pathfinder units. --early game

**Comment by LoneGazebo** [comment]
I would need a zipped MODS folder from you to try and reproduce this. No promises.

**Comment by ryanmusante** [comment]
My situation is possibly due to a regression in wine or a switch in the build that I compiled. I am only seeing crashes with wine-staging. Disregard my previous reply.
https://github.com/Tk-Glitch/PKGBUILDS/tree/master/wine-tkg-git
