### ISSUE TITLE
Mangled combat preview (EUI)

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5589]
_1. Mod version (i.e Date - 4/23):_
8/31

_2. Mod list (if using Vox Populi only, leave blank):_
List Enhancements for VP (v5)
Trade Opportunities for VP (v8.1)
Filters in Trade Route Overview (VP - v1.3)
Promotion Flags EUI (v1.1)
Capture Great People for VP (v1)

_3. Error description:_ 
See screenshot; the cause seems to be a missing string (see the TXT_KEY... text) as it only pushes the numbers into the health bar when that text key is displayed (when selecting the other Pathfinder it has that text key on the other side as well and pushes those numbers into the health bars as well). I haven't played in a while so I'm not sure what modifier this is supposed to be but the extra mods shouldn't be doing this.
**Edit**: I checked the files, it's the string that designates the wounded damage bonus that seems to be missing. It's the [commit](https://github.com/LoneGazebo/Community-Patch-DLL/commit/c021ef38ed527b5ff4341466b1c24d30f59dd410) from the current version that did it...the string key was added but it seems the actual string was forgotten.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Combat_preview](https://user-images.githubusercontent.com/30495439/64133326-e02f6f80-cdc4-11e9-9d0b-55ba9bfb3f95.jpg)

**Comment by Aqinu** [comment]
I've made a pull request for this (this is modifier for damaged units introduce in this patch to be shown in the panel)

**Comment by UndeadDevel** [comment]
Yes, I see it now, thanks! It's not in my CBO files, though, of version 31-8...maybe a merge error?
I included it manually now and it fixes the problem.
