### ISSUE TITLE
CTD on 8/31

### ISSUE THREAD

**Issue by myles1718** [LoneGazebo/Community-Patch-DLL#5590]
[ModInstaller.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3567115/ModInstaller.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3567116/Lua.zip)
[CustomMods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3567117/CustomMods.zip)

_1. Mod version (i.e Date - 4/23):_
8/31

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
after setting up game CTD on starting Turn 1
Am using same set up and mods as used in previous version
Have verified game and deleted Cache and MDU

[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3567113/Database.zip)

 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Hard for me to debug extensive mod lists. Try testing without any other mods first.

**Comment by gpongrac** [comment]
I was getting a CTD on game start as well.   Deleting the MODS directory and re-installing VP fixed the issue.
