### ISSUE TITLE
Minor issue: typo in unit descriptions

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5591]
_1. Mod version (i.e Date - 4/23):_
8/31

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
"Supply" misspelled as "Suppyly" in the descriptions of the B17 and Zero (line 22 and 699 of [this file](https://github.com/LoneGazebo/Community-Patch-DLL/blob/f45f896507032aedafa48acea32dbb7f5304a315/Community%20Balance%20Patch/Balance%20Changes/Text/en_US/CivText.sql)).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@Aqinu you've failed me. :D

**Comment by Aqinu** [comment]
I wouldn't have to fail you if you knew how to spell. :)

**Comment by ryanmusante** [comment]
![ohsnap](https://user-images.githubusercontent.com/26808646/64287170-fe01fd80-cf99-11e9-9024-c7cf0de7f7d8.jpg)

**Comment by LoneGazebo** [comment]
@Aqinu haha

**Comment by LoneGazebo** [comment]
@Aqinu that's it, you're not invited to my birthday party anymore.

**Comment by LoneGazebo** [comment]
@UndeadDevel just checked my local files, I don't see this issue (nor in-game). Let me do a forced push, this is likely a merge error.

**Comment by UndeadDevel** [comment]
Seems like merge errors are happening quite often...is this from git or are you using some other VCS in parallel somehow? The [relevant file](https://github.com/LoneGazebo/Community-Patch-DLL/blob/f45f896507032aedafa48acea32dbb7f5304a315/Community%20Balance%20Patch/Balance%20Changes/Text/en_US/CivText.sql) still has the errors btw.

**Comment by LoneGazebo** [comment]
Because people often push to master on their own, I often have to do manual merges of my files with master. As such, some latent errors can persist unless I check through every directory, which can take some time.
