### ISSUE TITLE
8/31 Morocco's TR Pillage not working

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5593]
_1. Mod version (i.e Date - 4/23):_
8/31

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Unless I misunderstand the mechanic, when my ships go on to of Trade Ships I am not able to pillage them as Morocco.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/64367256-560e2380-cfdd-11e9-9ab9-a7f2cd877030.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
Is it a trade route to your cities? If it is, I don't think that you can pillage in this instance.

**Comment by Stalker012345** [comment]
> Is it a trade route to your cities? If it is, I don't think that you can pillage in this instance.

They are, so if that's a criteria than it would explain the behavior.

**Comment by LoneGazebo** [comment]
It is. WAD.
