### ISSUE TITLE
8/31 Tourism Quest not consistently showing the Leader

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5594]
_1. Mod version (i.e Date - 4/23):_
8/31

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
There are two tourism quests currently active. The first one says that I am the leader. The second says a different person is leading.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/64385774-ead44980-cffc-11e9-8cf5-71bfce05cd97.png)

![image](https://user-images.githubusercontent.com/20593976/64385800-00e20a00-cffd-11e9-98e9-df5c6c72c852.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
Maybe CS on first screen didn't met true tourism leader.

**Comment by LoneGazebo** [comment]
bigcat is correct.
