### ISSUE TITLE
Obnoxious City placement by AI

### ISSUE THREAD

**Issue by bentakacs** [LoneGazebo/Community-Patch-DLL#5595]
_1. Mod version (i.e Date - 4/23):_
8.31 beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Not really an error, just something that would maybe worth a checking. This is not the first time I see the AI does something like this, although placing a City literally in the middle of my empire is kinda rare and... interesting. That place has no luxury, no SR (well... so far), can't be connected to the rest of the cities, and ultimately I can literally take it anytime I want (after I finish my business with Genghis and his betrayal).

With the recent settler changes (which encourages more reasonable city placement) this seems like a waste of a city. Even if Ramkham doesn't like his wonderful tundras, the AI can't be this desperate, right? Right?!

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![grrrr](https://user-images.githubusercontent.com/22188835/64461324-2b1af100-d0fd-11e9-9ae5-106fd37b0897.png)

**Comment by LoneGazebo** [comment]
@ilteroi would this qualify for the AI ignoring a sanity check on defensible locations?

**Comment by ilteroi** [comment]
hard to define what a defensible location looks like ...

**Comment by bentakacs** [comment]
Yeah I suspected much, just thought I will share just in case something could be done, but no big deal. Thank you for your continous work! :)
Closing this.
