### ISSUE TITLE
Minor issue: Byzantium second prophet purchasing UI weirdness

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5596]
_1. Mod version (i.e Date - 4/23):_
8/31

_2. Mod list (if using Vox Populi only, leave blank):_
List Enhancements for VP (v5)
Trade Opportunities for VP (v8.1)
Filters in Trade Route Overview (VP - v1.3)
Promotion Flags EUI (v1.1)
Capture Great People for VP (v1)

_3. Error description:_ 
When gathering faith for a Great Prophet to enhance the religion, there seems to be a conflict between the normal "Save for Great Prophet" mechanic and Byzantium's UA, which allows Great People to be bought starting from Classical. In screenshot 1 below you'll see the top faith UI showing 4 turns needed until GP spawn, while the city UI allows me to buy one right then and there. In screenshot 2 you'll see the result if I don't buy and press "Next Turn": the game sends me a notification that I need to change my automatic faith purchase choice but it didn't actually buy the GP. In screenshot 3 you'll see that I can buy the GP without issue manually in the city.
Not a big deal, just a minor issue.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Byzantium_Prophet_1](https://user-images.githubusercontent.com/30495439/64463534-e9397d00-d0f3-11e9-9da2-708de916ee68.jpg)
![Byzantium_Prophet_2](https://user-images.githubusercontent.com/30495439/64463546-f3f41200-d0f3-11e9-80e9-9663bd409304.jpg)
![Byzantium_Prophet_3](https://user-images.githubusercontent.com/30495439/64463564-fc4c4d00-d0f3-11e9-8f98-6a64098d851a.jpg)

**Comment by LoneGazebo** [comment]
Unfortunately some of this is buried in code we can't mess with.
