### ISSUE TITLE
Paralyzed CS AI

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5601]
_1. Mod version (i.e Date - 4/23):_latest

 After a city-state was pillaged by barbarian invasion it never bothered to build workers and repair the pillaged tiles, even after centuries have passed.

 Logging enabled. Let me know what kind of logs you need.

![20190907131503_1](https://user-images.githubusercontent.com/16341598/64473633-fa28d380-d171-11e9-8945-31571ed8b2c9.jpg)

**Comment by LoneGazebo** [comment]
Post all of those logs if you have them.

**Comment by saamohod** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3587988/Logs.zip)
