### ISSUE TITLE
8/31 Repetable crash at Songhai turn

### ISSUE THREAD

**Issue by Jarrke** [LoneGazebo/Community-Patch-DLL#5604]
_1. 8/31

_2. no other mod

_3. game crashes at Songhai turn. This is second game I started playing with Vox Populi and second that crash at AI turn...

_4. load attached savegame and wait until Songhai turn

---------------------------
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3586748/CvMiniDump.zip)
[Kazimierz_error.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3586749/Kazimierz_error.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3586750/Logs.zip)

**Comment by Edaka** [comment]
Old, closing.
