### ISSUE TITLE
Negative science on foreign trade route

### ISSUE THREAD

**Issue by legenciv** [LoneGazebo/Community-Patch-DLL#5605]
_1. Mod version (i.e Date - 4/23):_

8/31

_2. Mod list (if using Vox Populi only, leave blank):_

34UC

_3. Error description:_ 

The science bonus on trade routes for the other civ having a tech that you haven't researched can be negative. See screenshot, under the "YOUR SCIENCE GAIN" part for an example. What should be a +7 science from the trade route becomes 1 due to a -3 science modifier from Venice having one tech I don't have.

![20190908062459_1](https://user-images.githubusercontent.com/19234279/64486391-fa24e400-d202-11e9-8d37-fb0fac91d0e4.jpg)

**Comment by LoneGazebo** [comment]
Weird, all the checks are for positive integers in the function.

**Comment by legenciv** [comment]
Maybe Trade Confederacy was doing something here? Both me and Venice went Statecraft, maybe this policy affected it somehow.
