### ISSUE TITLE
Many .dds files missing after fresh install of Civ 5 and Vox Populi

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#5608]
_1. Mod version (i.e Date - 4/23):_
Vox_Populi Beta 8/5b, 8/16, 8/21, 8/31. 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

many .dds files missing after fresh install of Civ 5 and Vox Populi

_4. Steps to reproduce (optional):_

Install Civ 5 to non default directory ie D:\SteamLibrary\

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Log Files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3588090/Log.Files.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![mods](https://user-images.githubusercontent.com/10148511/64494788-36862d80-d25f-11e9-9591-e41f5d29df65.PNG)
![diplomacy](https://user-images.githubusercontent.com/10148511/64494789-3b4ae180-d25f-11e9-80b0-e3f047f922f2.PNG)
![Counsel](https://user-images.githubusercontent.com/10148511/64494790-3d14a500-d25f-11e9-93da-4bbd4cb417a5.PNG)
![Greatworks](https://user-images.githubusercontent.com/10148511/64494793-3ede6880-d25f-11e9-9337-27cabf34ef16.PNG)
![Culture](https://user-images.githubusercontent.com/10148511/64494795-4140c280-d25f-11e9-947e-0515ef25659e.PNG)
![Espionage](https://user-images.githubusercontent.com/10148511/64494796-4271ef80-d25f-11e9-818e-304f8dffd882.PNG)
![GoldenAge](https://user-images.githubusercontent.com/10148511/64494799-46057680-d25f-11e9-9597-d8698a55f7f5.PNG)
![Menubutton](https://user-images.githubusercontent.com/10148511/64494801-47cf3a00-d25f-11e9-98a9-07a8a2d929b9.PNG)
![Helpbutton](https://user-images.githubusercontent.com/10148511/64494804-4998fd80-d25f-11e9-80e5-ce8614768c7c.PNG)
![fullscreen](https://user-images.githubusercontent.com/10148511/64494810-646b7200-d25f-11e9-9db9-29d301c59e52.png)

**Comment by LoneGazebo** [comment]
That typically means EUI did not end up in your Civ 5 DLC folder. Move EUI out of the c:/ directory for that and put it in your alt directory.

**Comment by R3P0FFXI** [comment]
@LoneGazebo thank you you were correct EUI was in the default not the alt directory. Issue has been resolved.
