### ISSUE TITLE
crazy food

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5609]
![image](https://user-images.githubusercontent.com/1358966/64507674-a508d100-d2db-11e9-90d8-1aa68ed6f9d7.png)

![image](https://user-images.githubusercontent.com/1358966/64507770-e600e580-d2db-11e9-8cd7-f0cca76d3d5a.png)

all indonesian cities have very high food output on the city plot ...

edit: they have progress/fealty maxed out. this is the 8/31 dll on the 8/21 db. so admittedly a non standard setup but does anyone else see this?

**Comment by HeathcliffWarriors** [comment]
Are they allied with maritime CS?

**Comment by ilteroi** [comment]
hmm. good point. don't know. it would explain why it's even more food in the capital. but it was a standard size map ... unlikely they had so many allies.

**Comment by LoneGazebo** [comment]
@ilteroi many policies and things apply the yield to the city tile for whatever reason.
