### ISSUE TITLE
Bran, the Celtic pantheon, doesn't increase ranged city attacks as advertised

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#5611]
The belief just doesn't have CityRangeStrikeModifier set to anything right now. Is it acrually supposed to give +100% city ranged attack strength or is it just an outdated tooltip?

**Comment by LoneGazebo** [comment]
Missing SQL. Will fix.

**Comment by UndeadDevel** [comment]
Can we also please change the description to make it more clear?

Currently it says "+50% increase to Ranged Combat Strength [...]", which suggests that ranged units may be buffed, too (I actually thought that at first but then suspected it might be city strike instead as +50% RCS for units is too high). Changing it to "+50% increase to City Ranged Strike" should suffice.
