### ISSUE TITLE
Harbors create city connection

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5612]
_1. Mod version (i.e Date - 4/23):_ latest

 A civipedia entry "Roads and Trade Routes" says "Harbors can also create city connections between coastal cities".
 I believe Lighthouses are meant.

**Comment by LoneGazebo** [comment]
@HeathcliffWarriors mind finding this string for me?

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Just saw this now, sorry. Fixed!
