### ISSUE TITLE
CTD on Start

### ISSUE THREAD

**Issue by myles1718** [LoneGazebo/Community-Patch-DLL#5614]
_1. Mod version (i.e Date - 4/23):_
VP 9-9

_2. Mod list (if using Vox Populi only, leave blank):_
VO Mods 1 - 4 6a 7 9 More luxs
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3597559/Database.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3597563/Database.zip)
[xml.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3597564/xml.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3597574/CvMiniDump.zip)

_3. Error description:_ 
CTD on pressing start game

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
You've got a ton of errors in your database log not related to VP content - JFD mods, etc.
