### ISSUE TITLE
Warmongering Penalties

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#5616]
_1. Mod version (i.e Date - 4/23):_

8/31 Beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Not sure really how warmongering works in CPP however I had a weird case where the  Polynesian Empire asked me to go to war against Egypt with them. I had never been to war and when I agreed to join 8 of 14 empires gave me a warmongering penalty including the Polynesian Empire which asked me to go to war with them. I was Carthage.

How in the name of sanity can someone ask you to go to war then penalize you for it lol

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
Not the first recent issue with warmongering penalties, I'll look into this and see if I can find the problem.

When you declared war on Egypt, did it trigger a Defensive Pact, or did Egypt have vassals by any chance?

Also, _how_ did you declare war? Did you do so immediately, did you ask them to go to war, did you agree to war in 10 turns and declare early, or did you wait for the "The time for war against Ramesses II has come" message?

**Comment by R3P0FFXI** [comment]
I was asked to goto war by  Polynesian empire, There were no vassals or defensive pacts.

Its not just this thats an issue look at Warmongering penalties for like Rome as well in my current game which ill post the save here Rome is always at war, but everyone is now viewing me as a warmonger when Rome is taking over like 3/4 of the map extremely aggressively.

Here are 2 save files

1 from the earlier game I mentioned 9/22 and another from my current game 9/29


[Civ 5 Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3612827/Civ.5.Saves.zip)

**Comment by Edaka** [comment]
I think this has been worked on.
