### ISSUE TITLE
CTD on 9-9 version, seems to be reproducible

### ISSUE THREAD

**Issue by crdvis16** [LoneGazebo/Community-Patch-DLL#5617]
_1. Mod version (i.e Date - 4/23):_
9-9

_2. Mod list (if using Vox Populi only, leave blank):_
VP+EUI

_3. Error description:_ 
I get a CTD after hitting next turn

_4. Steps to reproduce (optional):_
hit 'next turn' or see minidump

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[dump_and_save.zip.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3608103/dump_and_save.zip.zip)
[dump_and_save.zip.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3608105/dump_and_save.zip.zip)

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Yep, got it. Will patch.
