### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#562]
I had an issue with AI that kept provoking me and me answering "Get over it" about hundred times in a row. I really wanted war with them :) But they kept saying over and over. In any other case I got answer (war usually) in 3rd try. Feels little strange.

Maybe you could make it so after second answer AI always makes decission? I don't like to sorry AI even if it's only game :D

**Comment by Radost** [comment]
So you want AI to declare a war on you, but also aggro it on all your defensive pact buddies?

**Comment by Finarvi** [comment]
I mean: AI should stop insulting at some point, endless insulting<->"get over it" looks ridiculous and buggy.

**Comment by TechpriestEnginseer** [comment]
I can confirm this happens to me as well. This loop basically builds up anger in the AI and forces them to declare war on you.
