### ISSUE TITLE
Cultural victory not happening after being dominant + getting ideology

### ISSUE THREAD

**Issue by sasogwa** [LoneGazebo/Community-Patch-DLL#5622]
_1. Mod version (i.e Date - 4/23):_
8/31

_2. Mod list (if using Vox Populi only, leave blank):_
I use the modspack and UI_bc1 that I found in the forums

_3. Error description:_ 
So, to have fun I played a Marathon game with polynesia where I stomped the game in tourism and was influential with everyone around 500 AD, before realizing it wasn't enough and I needed an ideology on top of that. Fast forward, I get the ideology, nothing happens. couple of next turns, still nothing happens (I don't win). I check the victory condition it tells me cultural victory is possible and I'm dominant towards everyone. Why don't I win then?

_4. Steps to reproduce (optional):_
get influential with everyone before getting an ideology?
[populisongoku.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3613247/populisongoku.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Gotta build the CEP

**Comment by sasogwa** [comment]
Ok thank you

**Comment by LoneGazebo** [comment]
@Edaka you are a saint for closing all these obsolete issues. Danke!
