### ISSUE TITLE
CTD on Turn 1

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5628]
_1. Mod version (i.e Date - 4/23):_ 9-15 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
IGE
Archaeology Aesthetic Adjustments
Calypso's Colored Religious Icons
Faster Aircraft Animations
Quick Turns

_3. Error description:_ CTD on the first turn, logs, save & dump file included

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3614856/Logs.zip)

**Comment by HeathcliffWarriors** [comment]
Another crash, this time with the 9-15-2 hotfix. Exact same scenario.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3618281/Logs.zip)

**Comment by HeathcliffWarriors** [comment]
Another CTD, this time with the 9-18 hotfix. Occurred on Turn 2 this time but nevertheless...

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3629722/Logs.zip)

**Comment by HeathcliffWarriors** [comment]
These crashes have prevented me from doing any testing and I'm a little irritated. :)

They seem to be always occurring on an AI's turn.

**Comment by ilteroi** [comment]
are you able to do a debug build and run it in the debugger? then it should be easy to see where it's crashing

**Comment by LoneGazebo** [comment]
@HeathcliffWarriors post your nonVP mods zipped as a folder as well please.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Here you are:
[NonVP Mods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3633547/NonVP.Mods.zip)

@ilteroi I'm not sure how to go about doing that.

**Comment by ilteroi** [comment]
i added a section to the readme explaining how to go about it

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3636979/CvGameCore_Expansion2.zip)

**Comment by LoneGazebo** [comment]
Try this report back.

**Comment by HeathcliffWarriors** [comment]
Can't test this at the moment as I'm away from home, but I'll do so as soon as I can, cheers.

**Comment by HeathcliffWarriors** [comment]
Tried using the latest hotfix, crashed during England's turn.

It seems to occur consistently after I use IGE to "Reveal All".

Relevant files are attached.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3641860/Logs.zip)

**Comment by LoneGazebo** [comment]
No crash for me.

**Comment by HeathcliffWarriors** [comment]
There've been several CTD fixes recently, so I'll close this and open another issue if I encounter more of them.
