### ISSUE TITLE
Some general feedback.

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#563]
These Notes were for the 8/24 version... I do not know how pertinent they still are...

Since I cannot use the civfanatics forums since the move I am comenting here.

I find the game a mot more interesting at the moment than how it was some iterations ago.
However the AI has gone to the opposite end of the spectrum as far as settling goes: it tends to build cities EVERYWHERE. While I like this because the map is less empty, it should be toned down a bit.

Some of these will clearly not get enough production, gold and raw yields to make the viable.

They also forward settle to a crazy degree (right next to a luxury I am about to clame), then protest when I build a city 20+ spaces away from them on a different landmass. The diplomacy has gone a bit crazy in general.

There has been also a great increase in the culture cost of acquiring tiles at some point, making cities unable to expand to luxury and resource tiles on the third ring until they have museum at least. Another building that reduces the cost of expanding around medieval/renaissance would be welcome.

The Zulu are crazy strong opponents! They promotions they have make them be a very strong power even when they are behind technologically. This is frustrating, but good.

Generally most civs are interesting. I would like to move the "does not get penalties from isolation" to Polynesia to make them search for those natural wonders and settle them more easily, and add "cities that are unconnected to your capital have +1 faith and +1 culture (or 2 or scaling)" to Indonesia.

I do not know if it is a bug, but in the last version, when I conquered the city that had the HQ of the civilized jewelers, the wonder dissappeared. On the economic overview it still mentioned franchises belonging to Austria, but the world wonder had disappeared.

It would be interesting to give the USA the ability to have more than one Corporation as a UA.

As always, amazing work.

**Comment by LoneGazebo** [comment]
Corporations are limited to one per player as a DLL implementation restriction - limits performance impact in-game. Still, glad you are enjoying the game! 

I did address the corporation issue you mentioned re: the HQ.
