### ISSUE TITLE
crazy science from quest

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5632]
so this is at turn 80.

![image](https://user-images.githubusercontent.com/1358966/64984944-1b04cd80-d8c4-11e9-834c-6d0d0cde274e.png)

my "normal" yield is 14 science per turn. i just earned 3 techs and don't even know why and how.

**Comment by ilteroi** [comment]
still crazy

![image](https://user-images.githubusercontent.com/1358966/66274337-df837080-e87d-11e9-9325-eebedb9aaad9.png)

next to the overly large reward, i had the same quest from 5 different minors ... maybe an rng issue?

**Comment by LoneGazebo** [comment]
@ilteroi could be - did you get the quest on the same turn?

**Comment by ilteroi** [comment]
i made it so that you cannot get another quest of the same type when you already have one active
