### ISSUE TITLE
Realpolitik seems to be bugged.

### ISSUE THREAD

**Issue by TakagiHiro** [LoneGazebo/Community-Patch-DLL#5636]
1. Mod version:
9/15

2. Mod list:

3. Error description:
Germany's ability doesn't work properly; unlike the description claiming it grants science with city-state friends, it only grants culture when allies.

4. Steps to reproduce:
Pick Germany, make a city-state friend, check your capital's science, and there'll be no bonus science in sight. Make a city-state ally, check your capital's culture, and you will find the bonus culture.

**Comment by LoneGazebo** [comment]
You get one or the other, not both.

**Comment by TakagiHiro** [comment]
Oh, I'm fully aware. But even when just friends, science is still not granted.

**Comment by LoneGazebo** [comment]
ah gotcha i see why

**Comment by phantommaxwell** [comment]
10/23 Version, I am getting the Golden Age Points from CS Friend, but not the Science.  Where are the Yields supposed to be sent to, the Global pool or the Capital?

**Comment by LoneGazebo** [comment]
GAP goes to global pool b/c it's not calc'd locally, I'll take a look.

**Comment by LoneGazebo** [comment]
I looked, I'm not seeing the issue. Mind adding more details? Science should go to capital, yes.

**Comment by phantommaxwell** [comment]
The Culture from CS Allies does work.
