### ISSUE TITLE
Units pushed upon city raze

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#5638]
9-15

Unit garrisoned into a burning city is pushed 6 tiles away upon city raze, instead of being moved to the nearest unoccupied tile as in previous versions, or even better stay on the city ruins tile (that'd be the preferred outcome).

Unrelated request, it'd be nice if a city built on flood plains and then razed wouldn't leave a plain desert tile behind, but again some (usually unremoveable) flood plains.

![civbugpush](https://user-images.githubusercontent.com/53142313/65044858-0412b980-d95e-11e9-8c87-80e599b2b29d.png)

**Comment by Padre19** [comment]
JumpToNearestValidPlot is broken, again.

**Comment by TooManyCords** [comment]
Is this the reason my Ironclads used to get tossed into mountain lakes at the conclusion of wars?

**Comment by ilteroi** [comment]
don't worry it's fixed already
