### ISSUE TITLE
Civilized Jewelers, Inc

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#564]
Civilized Jewelers, Inc. lost Resource Bonus, right?

Row Tag="TXT_KEY_CORP_HELPER_CIVILIZED_JEWELERS"
Resource Bonus: Gold, Silver, Gems, and Pearls gain additional Gold.
 ->
Resource Bonus: Nothing.

Related files
- Community Balance Patch (8-28)\Modular Elements\Corporations\CivilizedJewelers.xml
- Community Balance Patch - Compatibility Files (EUI) (8-28)\Corporations\Corporations.sql
- Community Balance Patch - Compatibility Files (No-EUI) (8-28)\Corporations\Corporations.sql

**Comment by LoneGazebo** [comment]
Fixed!
