### ISSUE TITLE
Oracle research overflow

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5641]
_1. Mod version (i.e Date - 4/23):_latest

It may be intended although it doesn't make sense when compared to similar game principles.

After the completion of Oracle (which gives bonus research) and in case of completing current technology by this, there is no overflow in case no next tech has been selected; any excess research is wasted. Research only overflows if a next tech had been selected beforehand thus boosting the said tech.
I think it should overflow even if no next tech had been chosen, the same way production overflow works IIRC.

**Comment by LoneGazebo** [comment]
It applies the overflow once you have a tech selected, you don't lose the overflow.

**Comment by saamohod** [comment]
It doesn't, that's the point.
Once I pick a tech after the Oracle has been created, nothing overflows to that tech.

**Comment by LoneGazebo** [comment]
It does, but on the next turn. I just tested.
