### ISSUE TITLE
Advanced Start - Settler Units Not Upgraded

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5642]
_1. Mod version (i.e Date - 4/23):_ 9-15-3 Beta (aka 9-18)

_2. Mod list (if using Vox Populi only, leave blank):_ IGE, Calypso's Colored Religious Icons, Archaeology Aesthetic Adjustments, Faster Aircraft Animations, Quick Turns

_3. Error description:_ When you start in later eras, your cities start with certain buildings pre-built in them - but the units are Settlers, not Pioneers or Colonists, and you're given the option to upgrade them.

I also have a suspicion (which I've been unable to test because of game crashes) that if the Settlers were upgraded, they'd lose some of the pre-built buildings etc., so if that's the case, that'd be a definite bug.

Side Note: "Cannot found Cities if the Empire is very unhappy." at the bottom of the description is in the same color as "Your unit must be in friendly territory in order to upgrade." immediately below it and this could confuse a player.

![Screenshot (18887)](https://user-images.githubusercontent.com/38794241/65219485-a62dc100-da86-11e9-852c-9ab1975f4397.png)

**Comment by Aqinu** [comment]
How can add confusion, what isn't clear? I am the one who added this description to have "RED" color because is a warning text (to be consistent with other descriptions) which previously wasn't present.

**Comment by HeathcliffWarriors** [comment]
Oh, I'm not blaming you - with the way the UI is, at first glance I thought it was telling me I couldn't upgrade my Settler because of the "cannot found Cities" tooltip as well as the "must be in friendly territory" tooltip. Then I saw the dividing line.

I think I'm probably just nitpicking though, don't worry about it :)

**Comment by HeathcliffWarriors** [comment]
Apparently the Settlers (despite starting with extra buildings) are actually _worse_ than their upgraded versions, so upgrading them to Pioneers or Colonists sounds like a good idea.
