### ISSUE TITLE
A Fort for a Terrace Farm

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5644]
_1. Mod version (i.e Date - 4/23):_ latest

It may be a minor issue, it may be not. I presume this reflects AI's decision making in general.

The suggestion recommends that a Fort should be constructed on the hill thereby destroying the Terrace Farm. I fail to see any benefits of a Fort over a Terrace Farm.

![20190919173006_1](https://user-images.githubusercontent.com/16341598/65253386-390c4100-db03-11e9-9eea-625716f4f5ae.jpg)

**Comment by LoneGazebo** [comment]
The game will always look for a recommendation in spots, but it can't recommend what's already there.

**Comment by saamohod** [comment]
I mean, in case control of my tile with the Terrace Farm is transferred to an AI civ, would its worker destroy the Farm and build an obviously useless Fort?

**Comment by ilteroi** [comment]
the recommendations cover only the plots immediately around the worker. the AI looks at all the plots it controls, so there's a chance the worker would go somewhere else first. but if not, i expect they would build a fort.

**Comment by bentakacs** [comment]
It's close to another civ's border, maybe that's the reason? Placing a fort there would be military-wise quite advantageous.  Can /Does AI worker check for stuff like that?

**Comment by LoneGazebo** [comment]
That’s why the AI would build there, if it decided to. Especially if it did not like the neighbor.
