### ISSUE TITLE
Greyed-out World Map Trade

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5646]
_1. Mod version (i.e Date - 4/23):_
latest

The diplomacy window doesn't provide red text explaining why the Map Trade is not available. I do have the necessary tech for the Map Trading.

![20190919200549_1](https://user-images.githubusercontent.com/16341598/65265255-2866c580-db19-11e9-8e27-82fadb2556ac.jpg)

**Comment by ilteroi** [comment]
both need to have the tech, iirc

**Comment by saamohod** [comment]
Must be the case. Would it be possible to insert red text notification?

**Comment by HeathcliffWarriors** [comment]
See #4539 for possible cause.

**Comment by ilteroi** [comment]
well, this is weird. looking at tradelogic.lua, the tooltip should include a hint about the missing tech requirements. seems this isn't working.
