### ISSUE TITLE
Founder Beliefs (v8-28)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#565]
Would you recheck Founder Beliefs and Religious National Wonders?

- Ceremonial Burial (Mausoleum)
Text: +4 Faith
Effect: +5 Faith

- Hero Worship (Great Altar)
Text: +4 Faith
Effect: +5 Faith

- Theocratic Rule (Grand Ossuary)
Text: +5 Faith
Effect: +6 Faith

- Way of the Pilgrim (Reliquary)
Text: +4 Faith
Effect: +4 Faith and +2 Culture

- Way of Transcendence (Sacred Garden)
Text: +4 Faith
Effect: +3 Faith

**Comment by LoneGazebo** [comment]
Fixed, thanks!
