### ISSUE TITLE
Visibility issues for Quinqueremes

### ISSUE THREAD

**Issue by kcherepyn** [LoneGazebo/Community-Patch-DLL#5652]
_1. Mod version (i.e Date - 4/23):_

(09.15) (3) 
_2. Mod list (if using Vox Populi only, leave blank):_
1. Unique components for VP
2.  Expanded Wonders
3. Unique city states
4.  Wonders from Nefarian222

_4. Steps to reproduce (optional):_
 _3. Error description:_ 
Reconnaissance promotions apply only to sea titles, not to land titles with open terrain (plain, grassland). So there is additional visibility for sea titles and additional movement  points, but there is visibility for land titles regardless of terrain
There was no such problem in VP version 09.09.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
I believe this is intentional as of the latest version.

**Comment by ilteroi** [comment]
yes. you're not supposed to see/bombard inland tiles with ships.

**Comment by kcherepyn** [comment]
Thank you for responses. It actually seriously weakens Carthage, due to the fact that Quinqueremes receive XP from exploration and Reconnaissance  promotion makes a lot less sense now.
