### ISSUE TITLE
AI not improving silk

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#5653]
_1. Mod version (i.e Date - 4/23):_
7-29-1 with EUI

_2. Mod list (if using Vox Populi only, leave blank):_
UI mods only

_3. Error description:_ 
AI sometimes never improves silk. The Shoshones in the screenshot have built encampments everywhere and improved iron, horses, olives (their monopoly) and some other bonus resources, but haven't touched the silk lying just beside their city. You can also see they have improved nearly everything near Timbisha, founded at around the same time.

It happened in the (2019) 1-15 patch too with other civs, but I didn't have logs at the time.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs and save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3639956/Logs.and.save.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![](https://i.imgur.com/yAoUGku.png)

**Comment by Edaka** [comment]
Saw this on 12/1 once or twice.
