### ISSUE TITLE
Misaligned Bullet in Unit Supply Overview

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5655]
_1. Mod version (i.e Date - 4/23):_ 9-18 Hotfix

(The +12 from handicap is due to my tinkering with the settings.)
![Screenshot (18910)](https://user-images.githubusercontent.com/38794241/65432193-c7751100-dde8-11e9-8b40-714b681790be.png)

**Comment by LoneGazebo** [comment]
🍑
