### ISSUE TITLE
Unusable Options in Teammate Trade Table

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5656]
_1. Mod version (i.e Date - 4/23):_ 9-18 Hotfix

![Screenshot (18903)](https://user-images.githubusercontent.com/38794241/65432443-2aff3e80-dde9-11e9-9811-da970b6caa16.png)
![Screenshot (18905)](https://user-images.githubusercontent.com/38794241/65432444-2aff3e80-dde9-11e9-8a7e-093d7f7a3fb1.png)

It is impossible to exchange embassies with teammates, so it is impossible to make use of the "Make Peace With/Declare War On" options - which I'm not sure are meant to be tradeable between teammates anyway.

**Comment by LoneGazebo** [comment]
This is not a bug. Intended.

**Comment by HeathcliffWarriors** [comment]
My point is they're still selectable - they should be greyed out if they can't be used, right?

**Comment by LoneGazebo** [comment]
I think it shows the second screen if you have any options, even if not available - otherwise it wouldn't be explicitly clear why you can't.
