### ISSUE TITLE
Integrate "Diplomacy Extended" Modmod?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5657]
https://forums.civfanatics.com/threads/diplomacy-extended.647933/

This small mod contains a number of additional text keys intended to add more variety to leader dialogue. Some of the lines are in need of proofreading, but aside from that it seems like it could be easily integrated into VP.

The mod description does include the following disclaimer which may be relevant for e.g. copyright and make this idea inadmissible, I'm not sure:
"I'm not very good at writing authentic-sounding dialogue, so the vast majority compiled into this mod are stripped from custom Civilization mods on the Steam Workshop. I do not take credit for them in any way. The mods used are listed in the "credits.txt" file in the mod folder."

Any thoughts on this idea? If it's a good one and the mod author gives permission, I wouldn't mind handling the merge and proofreading work. I was thinking of doing this kind of thing myself, but as it turns out, someone already has.

**Comment by LoneGazebo** [comment]
I'd rather not rip other people's content, that can get messy. I think having it remain a modmod is fine.

**Comment by HeathcliffWarriors** [comment]
I suspected that, just thought I'd suggest it.

I might come up with my own dialogue lines later, I can agree with the author that more variety could be beneficial.
