### ISSUE TITLE
Siam UA Overriding Influence Boosts - Clarify Text Key

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5658]
_1. Mod version (i.e Date - 4/23):_ 9-18 Hotfix

Siam's UA overrides any +influence boost upon meeting a City-State (so, if meeting a City-State would give you 6 Influence, you would get Siam's usual 40 only, not 46). This was previously confirmed as intentional.

However, if it's Siam and there's no gift of Gold or other yield, why not simply use the already existing TXT_KEY_MINOR_CIV_CONTACT_BONUS_NOTHING in these situations?
"Unfortunately they have nothing to offer you."

Situations like these are misleading:
![57627969-09529880-7567-11e9-95ab-922f1b513c4c](https://user-images.githubusercontent.com/38794241/65440166-4e7cb600-ddf6-11e9-9d3f-5c90520309b9.png)

**Comment by LoneGazebo** [comment]
I think it's fine as is, the code is really clunky and managed in lua.
