### ISSUE TITLE
March + repair combo

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#566]
I managed to get both march and repair promotion on my landships (upgraded from berber cavalry). I suppose that it's not intended.
I forgot to figure out if these bonusses stack but I think not. So one of them is wasted level-up.

**Comment by Vyyt02** [comment]
They do not stack. The later one is redundant. Thanks for posting this, I wanted to report it long time ago, but I always forgot :-)

I suggest to merge them into March (accessible to mechanical units as well) and get rid of the Repair promo altogether.

**Comment by Radost** [comment]
In #239 Gazebo said they stack.

**Comment by LoneGazebo** [comment]
I'm fairly certain they stack, but if not, I'll remove Repair and just add March to mechanized units..

**Comment by LoneGazebo** [comment]
Ah, they stack, but the bonus is boolean not integral. Removed repair, added march.
