### ISSUE TITLE
Iron Curtain policy doesn't grant Courthouse

### ISSUE THREAD

**Issue by TooManyCords** [LoneGazebo/Community-Patch-DLL#5663]
_1. Mod version (i.e Date - 4/23):_ 9/9 I think. Realize this isn't the latest, but haven't seen anything related to Iron Curtain in the changelogs.

_2. Mod list (if using Vox Populi only, leave blank):_
VP + 3rd, 4th UC, Wonders Expanded

_3. Error description:_ 
I capture a city and puppet it, the courthouse isn't built. If I annex it, the courthouse seems to be built. If I puppet then later annex, it isn't. Am I misunderstanding the policy?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
You have to annex when you conquer to get it.

**Comment by TooManyCords** [comment]
> 
> 
> You have to annex when you conquer to get it.

Why? Frankly that makes the policy quite a bit less valuable.

Perhaps make the policy reduce the science and culture scaler per city. Otherwise it seems like the policy forces you into bloated empires.

Though I suppose you could argue large Order civilizations do suffer from cultural stagnation.

**Comment by LoneGazebo** [comment]
Because a Courthouse is otherwise not valid as a building unless the city has been annexed.
