### ISSUE TITLE
 No Puppet Cities

### ISSUE THREAD

**Issue by shader301202** [LoneGazebo/Community-Patch-DLL#567]
When I conquer a city, I can only annex or raze this city.

**Comment by AnastaseAlex** [comment]
Was it a capital of another nation? If so it is intentional.

**Comment by shader301202** [comment]
No

**Comment by shader301202** [comment]
I can only create a puppet, If I conquer  a city via InGameEditor :(

**Comment by TechpriestEnginseer** [comment]
Screenshots would be nice.

**Comment by shader301202** [comment]
I don't know why, but now I can create puppets :)
