### ISSUE TITLE
Movement points issue (Cataphract moving into Marsh)

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5670]
_1. Mod version (i.e Date - 4/23):_
8/31

_2. Mod list (if using Vox Populi only, leave blank):_
List Enhancements for VP (v5)
Trade Opportunities for VP (v8.1)
Filters in Trade Route Overview (VP - v1.3)
Promotion Flags EUI (v1.1)
Capture Great People for VP (v1)

_3. Error description:_ 
See screenshots. Moving from a desert hill into marsh drains all 3 movement points, which isn't supposed to happen (I think), as marsh counts as rough terrain and therefore should only consume 2 movement points. There is no river or ZOC issue to explain this.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's 
Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Movement_issue](https://user-images.githubusercontent.com/30495439/65840586-67133180-e30a-11e9-8b86-704f8e3c79b5.jpg)
![Movement_issue2](https://user-images.githubusercontent.com/30495439/65840605-93c74900-e30a-11e9-961e-11d4fb7abc47.jpg)

**Comment by LoneGazebo** [comment]
@ilteroi may have an answer?

**Comment by bigcat88** [comment]
marsh consumes 3 points.

**Comment by UndeadDevel** [comment]
Yep, he's right. It even says that it consumes 3 MP in the civilopedia; I guess I should play civ more often 😄
