### ISSUE TITLE
Pledge of Protection 15% bonus not active

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5671]
_1. Mod version (i.e Date - 4/23):_
8/31

_2. Mod list (if using Vox Populi only, leave blank):_
List Enhancements for VP (v5)
Trade Opportunities for VP (v8.1)
Filters in Trade Route Overview (VP - v1.3)
Promotion Flags EUI (v1.1)
Capture Great People for VP (v1)

_3. Error description:_ 
The PoP description states that "During protection [...] you will earn 15% Influence from quests completed for this City State. [...]", but I haven't been able to actually see that (I assume it means that upon pledging protection I will get 15% more Influence from completing this CS's quests). When I check the Influence that a quest will give me and then recheck after pledging it stays the same (both in the pop up and with respect to what I'll actually get). I have also tested diplomatic missions, but those stay the same as well. The only things that I didn't test for is that either it may take effect later, after some number of rounds pass since my PoP but if that's the case it should say so in the description, or it may refer to new quests that will be given while I am holding the PoP already, but I feel like it should state this as well in that case, because I assumed in my game that pledging would give me the bonus Influence for fulfilling existing quests for that CS, as well.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
It applies to quests received after a PtP begins, not existing quests.

**Comment by UndeadDevel** [comment]
I see; could this be reflected in the description? Something like "you will earn **+**15% Influence from **new** quests completed for this City State" (changes to the current text are bold).

**Comment by LoneGazebo** [comment]
Fixed.
