### ISSUE TITLE
No city attack

### ISSUE THREAD

**Issue by Diphyllin** [LoneGazebo/Community-Patch-DLL#5673]
Just downloaded the community patch this past weekend and have enjoyed relearning this great game. I've tried searching for a similar bug, but I couldn't find anything similar. I've turned off ALL other mods and even deleted the folders and unsubscribed from them to ensure that the issue is from the community mod.
Bug:
Despite being prompted at the beginning of my turn that an enemy is within bombardment range AND the target icon appearing under my city name, I am unable to attack any units. When I click on the icon nothing happens.

**Comment by ilteroi** [comment]
do you get a red border like this?

![image](https://user-images.githubusercontent.com/1358966/65906444-e49a7880-e3c2-11e9-9e90-c6363cad8620.png)

**Comment by Diphyllin** [comment]
No. The target icon will turn red when I hover over it, but when I click on it there is no in game response.

**Comment by ilteroi** [comment]
weird. do you have any DLC mods installed?

**Comment by Diphyllin** [comment]
Solved. The issue was the EUI that was installed with VP was out of date. When I used the UI_bc1 from the manual installation page instead, everything worked fine.
To anyone who reads this in the future: Don't forget to move the .xml text files to the appropriate folder.
