### ISSUE TITLE
not enough melee units

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5674]
![image](https://user-images.githubusercontent.com/1358966/65905956-dd269f80-e3c1-11e9-9b65-eacf29a0da9a.png)

i've seen a bunch of instances like this, where the AI has only ranged units and is thus unable to capture a city. note that they are building yet another galeass in seoul. they really love galeasses ...

**Comment by LoneGazebo** [comment]
May be because they want turtle ships, which fits their flavor. Some civs build more melee than ranged because of naval flavor.

**Comment by ilteroi** [comment]
well in my experience it's not only korea and not only naval units

**Comment by bigcat88** [comment]
They build a caravel. Or unit icons was changed?

**Comment by Stalker012345** [comment]
I will pipe in to say, in my recent games I've seen plenty of melee units, especially by Tercio. Now Galleases, I agree, and I think that's to the AI determent. Until frigates, navy shouldn't be massed that heavily, there just isn't enough to do with Galleases in that number.
