### ISSUE TITLE
(Re-)allying with a CS makes it DOW a civ with whom neither I nor them have ever been at war

### ISSUE THREAD

**Issue by Maxxim69** [LoneGazebo/Community-Patch-DLL#5677]
_1. Mod version (i.e Date - 4/23):_
9-15-4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Description in topic title. 
When I saw it happen once, I thought it was a new mechanic I hadn't been aware of, but now when I've seen it happen three times under different circumstances, I'm inclined to believe it's a bug.

_4. Steps to reproduce (optional):_
OK, I'm Russia, and I'm at war with the US and China (no surprises here, huh). I send my diplomat to re-ally with a CS who was allied with the Netherlands, and the CS declares war on the US, China... and Brazil.

Then I liberate a CS conquered by China which makes the CS declare war on China, the US... and Brazil again!

Then I complete quest for a far-away CS which makes me its ally, and the CS promptly declares war on my enemies... and its neighbor Brazil. Bye-bye, CS. :(

**Comment by Maxxim69** [comment]
I'm mildly surprised my report received no comment in 10 days.
Do you guys need more info or is it not a bug at all?

**Comment by LoneGazebo** [comment]
This is not a paid support service. We look at bug reports when we get a chance. Thanks for your patience

**Comment by Maxxim69** [comment]
No problem G, take your time.
Also, I wasn't requesting support, I was hoping to give something back to the community. :)
