### ISSUE TITLE
Mayans not upgrading

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#568]
I noticed that the Mayans had at least half a dozen alarmists in the late renaissance. Thought I'd mention it in case it is a bug.  Could just be they had no cash I guess :)

**Comment by TechpriestEnginseer** [comment]
It is maybe because the AIs know how good Atlantists are? ;)

**Comment by LoneGazebo** [comment]
Probably just a money issue.
