### ISSUE TITLE
Wrong Strength Calculation

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5682]
_1. Mod version (i.e Date - 4/23): 9/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

As you can see in the screenshots when the city attacks a range unit the strength value is calculated correct with the bonuses, but when land range attacks other land range unit the strength value doesn't apply the bonuses to it. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

Correct strength calculation, including the bonus 
![s1](https://user-images.githubusercontent.com/49090452/66266441-cd79e180-e82d-11e9-91eb-48b299ced570.png)

Incorrect strength calculation, doesn't include the bonus (should be the same as above)
![s2](https://user-images.githubusercontent.com/49090452/66266442-cf43a500-e82d-11e9-9f0d-6ff1f1b73412.png)

Again, here in the strength calculations isn't included the bonus
![q1](https://user-images.githubusercontent.com/49090452/66266391-301ead80-e82d-11e9-8e80-3d91aa1ae7ac.png)

**Comment by LoneGazebo** [comment]
@ilteroi tweak to combat calc issue?

**Comment by ilteroi** [comment]
i think this was observed with the 9/15 version so it predates my recent changes. in any case needs to be retested

**Comment by LoneGazebo** [comment]
@ilteroi it is something to do with the temp cache in units for speeding up turns, I've reproduced this. I don't think the cache is thoroughly checking all ends to make sure it is pulling the right value.

**Comment by LoneGazebo** [comment]
I think I've fixed, we'll see...

**Comment by ilteroi** [comment]
yeah i checked it, GetMaxRangedCombatStrength() is called with a wrong parameter from lua (bAttacking should be false for the defender)

**Comment by ilteroi** [comment]
did you fix this?

**Comment by LoneGazebo** [comment]
Yes I did

**Comment by LoneGazebo** [comment]
I simply added an additional parameter to the function for bRangedStrike

**Comment by ilteroi** [comment]
why do we need another parameter?

**Comment by LoneGazebo** [comment]
For the ranged attack check for damage unit penalties - that's why it was added.

**Comment by Aqinu** [comment]
VP 10/23:
1. Why in the bottom combat panel of enemy aren't displayed all promotions like in the mouse tooltip?
2. From where does 35% bonus comes from? I think that it shouldn't be applied, regardless even it is intended is also gives a wrong value (should be 10.6):
![Civ5Screen0005](https://user-images.githubusercontent.com/49090452/68083003-491a7e80-fe2c-11e9-99f4-b68edd3d5c4f.png)

**Comment by LoneGazebo** [comment]
Runs out of room.
