### ISSUE TITLE
Diplo AI - Pledge to Protect Statements

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5683]
On the forums, LifeOfBrian brought up an interesting point which made me think.

Currently, declaring war on a City-State before anyone pledges to protect it prevents you from getting any diplomatic penalties with any other civ - which can be used to, among other things, grind XP without any diplo penalties, up to a certain limit.

If an AI pledges to protect the City-State after you've declared war on it, the AI doesn't respond with any diplo statement, despite the fact that damage to the City-State's capital triples their Influence decay.

If this were the real world, if a major power took an interest in the protection of a minor power, they wouldn't disregard existing conflicts - they'd send a message to the attacker to back off and get upset if they didn't do so, right?

Looking at, for instance, TXT_KEY_ATTACKED_PROTECTED_CITY_STATE_2:
"Your war against {@1_MinorCivName} will not be tolerated any longer. They are under our protection, and we mean to enforce that promise."

I see no reason why they couldn't send the message as soon as they Pledge to Protect the CS, rather than only if they pledged beforehand. I think this should be implemented.

Obviously, this should exclude situations where the City-State is peace blocked.

Any thoughts?

**Comment by LoneGazebo** [comment]
Sure. We'd need to be careful about compounding pain, though, as if we have the AI check every time it enables a PtP it could rapidly increase diplomatic tension.
