### ISSUE TITLE
crazy default promotions

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5687]
so this is a cannon with zero xp. who is supposed to understand this? what does the base CS even mean on such a unit?

![image](https://user-images.githubusercontent.com/1358966/66349894-32caf100-e95a-11e9-9e47-bee344608f62.png)

it has
* no melee attack (ok)
* no defensive bonuses (ok)
* must set up for attack (ok, but wrong text)
* limited visibility (ok)
* bonus against ranged attacks (25% but typically cancelled out by the last two)
* bonus against cities (100%)
* penalty against naval (20%)
* penalty against land units (33%)

can't that be cleaned up?

**Comment by Stalker012345** [comment]
Could the last four be converted into a "siege weapon bonus", similar to how covering fire takes care of a lot of adjustments at once?

**Comment by ilteroi** [comment]
well that's one option but i was hoping we can adjust cs/rcs and then drop some of these promotions completely.

eg cs 12 rcs 20, plus 200% attacking cities full stop

**Comment by LoneGazebo** [comment]
@ilteroi problem is we want the siege unit to have the same stats, but be less effective versus units, etc.

**Comment by ilteroi** [comment]
i know but what i'm saying is there is an easier way to achieve approximately the same result.
