### ISSUE TITLE
Late game crashes

### ISSUE THREAD

**Issue by besset** [LoneGazebo/Community-Patch-DLL#5688]
_1. Mod version (i.e Date - 4/23):_
9-15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  The game crashes every 10-15 turns in the late game, always by pressing menus/the tech tree etc.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3699837/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Bismarck_0342 AD-1922.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3699846/Bismarck_0342.AD-1922.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3699854/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by Edaka** [comment]
Thanks for reporting. I assume this has been looked into, though late game crashes can be difficult to pinpoint. This is was on an old version, so I'm closing for now.
