### ISSUE TITLE
Conscription and Capturing Cities

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#569]
http://images.akamai.steamusercontent.com/ugc/618471345342855876/EFA886CE66ED1F3580D28BC41CDE46478D562D5C/

http://images.akamai.steamusercontent.com/ugc/618471345342856304/196A5696D43C6276ED50A9133F67CC73974CF743/

When you capture a City with a Multiple of 6 Pop, it triggers the Policy.

**Comment by LoneGazebo** [comment]
Ha, excellent. I'll fix.
