### ISSUE TITLE
Cannot ask a Civ to peace a CS

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5690]
_1. Mod version (i.e Date - 4/23):_
9/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Maybe this is similar to a brokered deal where you can't get peace for X turns, but I've never seen it before myself. Currently Askia is at war with Quebec, and yet I cannot even try to ask for peace (Quebec isn't even on the list). This may have to do with the fact that I just liberated the civ.

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/66443398-885bd800-ea04-11e9-9ad6-3a2e1fc29d1d.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
Is Askia at war with the CS's ally?

**Comment by Stalker012345** [comment]
At the time no. I was Quebec's ally and we were not at war.
