### ISSUE TITLE
Poland's UA (free social Policy) not working properly

### ISSUE THREAD

**Issue by HeroOfTheSword** [LoneGazebo/Community-Patch-DLL#5691]
_1. Mod version:_
7-29-1 No-EUI

_2. Mod list:_ 
(over) More Unique Components for VP (v. 51)
Calypso's Colored Religious Icons (Basic) (v. 4)
Calypso's Colored Religious Icons (Extended) (v. 5)
Global - Capture Great People (v. 1)
Global Relations (v. 7)
Maps - Improved River Systems (v. 1)
Reforestation (v. 9)

_3. Error description:_ 
Hi, so when I enter the medieval era, the free social Policy doesn't work. I got the free social policy in the classical era so I'm at a loss as to why it wouldn't reoccur. I did fresh install to the latest Vox version and played another game and the same thing happened again. Maybe I need to do a fresh install of the base game? Any advice at all would be great thanks.

Drew

---------------------------
Supporting information:

1. Log files 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3707756/Logs.zip)

2. Save game
[Casimir III_0383 AD-0330.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3707757/Casimir.III_0383.AD-0330.zip)

3. CvMiniDump.dmp file 
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3707762/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Every other era. Not every era.

**Comment by bentakacs** [comment]
Hmmm, I'm not a native English-speaker, but the text "Gain a free Social Policy in the Classical Era, and every other Era after." strongly suggests that you'll get a free Social Policy in the Classical, Medieval, Renaissance and so on.

So you get one in Classical, Renaissance, Modern and Information only? If that's the case, the text is a bit ambiguous in my humble opinion (although I have no better proposal either so far).

**Comment by LoneGazebo** [comment]
Correct, and you also get two extra tenets.

**Comment by HeroOfTheSword** [comment]
Thanks guys for the replies! 

It actually makes sense now that it would be every second era because you don't get one in the ancient era. So the skip is in line with that. It would probably be a bit too easy if you got one every era!

Apologies for my misinterpretation anyways. I hope I didn't waste your time on this too much. I'm a bit of a newbie! At least there's nothing wrong with my game files though :)

**Comment by LoneGazebo** [comment]
No worries! Now go have fun. :)
