### ISSUE TITLE
10/8 - Can't settle a city in this 4 tile away spot

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5693]
_1. Mod version (i.e Date - 4/23):_
10/8

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Unless my eyes have gotten really bad, this spot seems 4 tiles away from every current city, so I'm not sure why I can't build here.

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/66506356-d0294080-ea92-11e9-89db-5d46dd9c1b56.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
You can't settle a city near anyone's border (except maybe on  different land mass, not sure)

**Comment by Stalker012345** [comment]
Learn something new every day!
