### ISSUE TITLE
compile warnings

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5696]
in the function

void CvCityReligions::CityConvertsPantheon(ReligionTypes eMajority, ReligionTypes eOldMajority, PlayerTypes eResponsibleParty)

none of the parameters are being referenced. whose code is this? is this by design?

**Comment by LoneGazebo** [comment]
I removed those, they're not in master - are you sync'd?

**Comment by LoneGazebo** [comment]
It's someone's modmod, I cleaned that code up last week.
