### ISSUE TITLE
AI gets Production discount on Wonders

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5698]
_1. Mod version (i.e Date - 4/23):_ Latest
```
if(!isHuman() && !IsAITeammateOfHuman() && !isBarbarian())
	{
		if(isWorldWonderClass(pkBuildingInfo->GetBuildingClassInfo()))
		{
			iProductionModifier += GC.getGame().getHandicapInfo().getAIWorldConstructPercent() - 100;
		}
		else
		{
			iProductionModifier += GC.getGame().getHandicapInfo().getAIConstructPercent() - 100;
		}

		iProductionModifier += std::max(0, ((GC.getGame().getHandicapInfo().getAIPerEraModifier() * GetCurrentEra()) + 100)) - 100;
	}
```
I wasn't aware the AIPerEraModifier applied to World Wonders; on Deity that would mean a very large Production discount on late game Wonders, with the -10 per era modifier, but even on Emperor the modifier is -8.

Edit: This also applies to World Congress projects, apparently.

Is it really necessary to discount Wonders with all the other bonuses the AI gets? Especially seeing as it's only the per era modifier with no base Production discount.

**Comment by LoneGazebo** [comment]
It's a base game choice.

**Comment by ilteroi** [comment]
that doesn't mean it makes sense :)

**Comment by LoneGazebo** [comment]
True, just noting that it's not our original choice.

**Comment by HeathcliffWarriors** [comment]
Wasn't an accusation. :)

But with the A/B/C periodic Gold, GAP, Food & Production bonuses to all cities, the production discounts on units and buildings (including the per era modifier) and more Gold to invest with lower maintenance costs, not to mention other sources of instant yields like City-State quests - is the per era bonus to World Wonders and WC projects really useful enough to the AI to warrant it staying there?
