### ISSUE TITLE
Nuada, the Silver-Handed King reduces yields.

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#570]
![8930_2015-08-31_00002](https://cloud.githubusercontent.com/assets/1131228/9569903/d07d7a36-4f93-11e5-824e-f4b1f16978ca.png)
![8930_2015-08-31_00003](https://cloud.githubusercontent.com/assets/1131228/9569904/d233213c-4f93-11e5-9013-c2d797e159b1.png)

**Comment by LoneGazebo** [comment]
Odd, I'll look.

**Comment by LoneGazebo** [comment]
Is it doing the same for culture?

**Comment by LoneGazebo** [comment]
Ha, go it - hadn't accounted for negative GPT pulling the value down.

G
