### ISSUE TITLE
MAJOR_CIV_APPROACH_DEFENSIVE_WAR

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5700]
right now it doesn't make a difference for the AI how a war got started - they will look for attack targets even if they didn't want the war. this makes it easy for the player to lure their units into traps and grind them down.

what would it take to change this?

MAJOR_CIV_APPROACH doesn't seem to cover this, although there is one instance of MAJOR_CIV_APPROACH_DEFENSIVE_WAR which is commented out.

nevertheless it should be easy to suppress creation of attack operations in CvMilitaryAI::UpdateOperations() under some conditions. 

question for the diplo experts out there: what's the best way to check for a defensive war?

**Comment by HeathcliffWarriors** [comment]
There is no MAJOR_CIV_APPROACH_DEFENSIVE_WAR in the enums, but I'd say factors you could check when deciding if the AI should play a war defensively would be:

- Current approach, to see what the AI thinks of the player they're at war with
- GetWarState, for how the war is going
- GetWarProjection, to gauge how powerful the opponent is
- GetPlayerTargetValue, for the same reason
- Who declared the war
- Whether it was a coop war
- How many turns it's gone on for
- War weariness
- Victory competitiveness

If the AI can distinguish between offensive and defensive war it would surely be smarter. Maybe some kind of function that adds or subtracts points for various conditions?

You did ask for the best way, not the quickest way. This is just my two cents. :)

**Comment by LoneGazebo** [comment]
I think we can use target value @ilteroi to define this most easily. Target value and relative target strength. If a target is not prime, and/or it is substantially stronger, an AI should default to defensive wars.

**Comment by ilteroi** [comment]
uh, target value is an enum ... anyway i added a basic check, give it a try and see if it isn't too restrictive. may also need to adjust the target value calculation, that's a beast of a function ... is it reliable?

**Comment by HeathcliffWarriors** [comment]
I meant in the approach enums; DEFENSIVE_WAR is a remnant of ancient code. :)

**Comment by ilteroi** [comment]
no worries, i just misread g's comment
