### ISSUE TITLE
Iconography Bonus Incorrectly Applied

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5701]
_1. Mod version (i.e Date - 4/23):_ Latest

_2. Mod list (if using Vox Populi only, leave blank):_ Quick Turns, IGE

_3. Error description:_ The +15% GP generation bonus applies all the time, not just during Golden Ages like the description claims.

![Screenshot (19252)](https://user-images.githubusercontent.com/38794241/66690047-9eafa100-ec5b-11e9-93e8-d649db1b2a2c.png)
![Screenshot (19253)](https://user-images.githubusercontent.com/38794241/66690048-9eafa100-ec5b-11e9-9572-3935182450a6.png)
![Screenshot (19254)](https://user-images.githubusercontent.com/38794241/66690049-9eafa100-ec5b-11e9-8801-968e50136347.png)

**Comment by LoneGazebo** [comment]
it's just a UI quirk.
