### ISSUE TITLE
Alhambra still grants Drill I

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#5702]
beta 10-8

simple as that

**Comment by LoneGazebo** [comment]
Not for me.

**Comment by randomnublet** [comment]
From the CIV5Buildings_Inherited_Expansion2 xml file Alhambra grants:

		<TrainedFreePromotion>PROMOTION_DRILL_1</TrainedFreePromotion>

and I don't see VP removing that. In an authority game my shock I-III troops suddendly gained a rank of drill, no save anymore though.
