### ISSUE TITLE
City Manager unexpected, suboptimal behavior

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5703]
_1. Mod version (i.e Date - 4/23):_
8/31

_2. Mod list (if using Vox Populi only, leave blank):_
List Enhancements for VP (v5)
Trade Opportunities for VP (v8.1)
Filters in Trade Route Overview (VP - v1.3)
Promotion Flags EUI (v1.1)
Capture Great People for VP (v1)

_3. Error description:_ 
See screenshots:
First screenshot shows the city in **Default** focus, gaining **420.07 hammers**
Second screenshot shows the city in **Production** focus, gaining **404.32 hammers**
Third shows it in **manual assignment**, where I've tried to maximize hammers, gaining **422.32 hammers** (I actually made a mistake by not seeing that one merchant specialist was still employed above the engineers, so the city would have had even more Production if I assigned him to e.g. an Ocean tile).
So the most Production in this case can be gained through manual assignment and, compared to the CM Default setting, Production focus actually makes it significantly worse (about 5% less Production).

Pretty minor, I guess, but it does sometimes make a difference between finishing something the next turn or not and it's just better if I can be sure that Production focus actually maximizes Production.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![City_Manager1](https://user-images.githubusercontent.com/30495439/66704140-07088c00-ed09-11e9-9701-c652a25dc5e5.jpg)
![City_Manager2](https://user-images.githubusercontent.com/30495439/66704151-18519880-ed09-11e9-91c4-21ea5c9452cb.jpg)
![City_Manager3](https://user-images.githubusercontent.com/30495439/66704158-230c2d80-ed09-11e9-838e-14229b87ff2c.jpg)

**Comment by HeathcliffWarriors** [comment]
As far as I know, focus =/= maximization

**Comment by UndeadDevel** [comment]
Could you elaborate? What does focus mean if Production focus gives me less Production than the Default focus?

**Comment by HeathcliffWarriors** [comment]
Ah, I misread that. If the Production focus grants less hammers than the Default focus, that's definitely suboptimal behavior.

I interpreted from the title that you were looking for the highest possible Hammer count at the exclusion of everything else, my bad. :)

**Comment by LoneGazebo** [comment]
Production focus = specialist focus for production, meaning it will run as many engineers as possible. It will compensate with other yields as needed to make sure your city isn't super unhappy or low growth as a result.

**Comment by UndeadDevel** [comment]
I see; if you look at the third screenshot, though, where I've manually set things, the city has less Unhappiness (1 vs. 4) and more Growth than on Production focus (as well as more Production)...the main problem here is that for some reason the City Manager decided to fill my artsy guilds with specialists, which slightly increases Faith and strongly increases Culture, as well as accelerating GA/GW/GM spawning. This is what I'd expect from Culture focus or GP focus, certainly not from Production focus.

To be fair, however, switching from Default to Production focus usually does increase Production as expected, so I can appreciate that this may represent a somewhat unique case...might be worth a look, though.
