### ISSUE TITLE
Suggestion: Add a Happiness Focus For Citizen Management

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5708]
This would particularly help players who have trouble with happiness management; if checked, the city would prioritize minimizing Local Unhappiness and maximizing Local Happiness (at least enough to try to cancel out Global Unhappiness for that city).

I imagine this is a substantial amount of work, but I think it'd be a big improvement to the mod, especially for newcomers to VP who are having trouble.

I also imagine it'd be a change many VP players would like to see.

**Comment by LoneGazebo** [comment]
Generic already does this.

**Comment by HeathcliffWarriors** [comment]
Ah.
