### ISSUE TITLE
National Wonders require 1+ buildings in the empire.

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#571]

**Comment by LoneGazebo** [comment]
Clarify? That's by design, if you mean to say that you have to have the 'base' building (i.e. library) in the city to build the national college.

**Comment by Radost** [comment]
You have to have library in at least 2 cities to build the national college.

**Comment by LoneGazebo** [comment]
Ah, that's because of world-size. There's a calculation in the 'prereqs needed' that bumps it up from 1 to 2+ based on world size (this is unchanged from vanilla DLL). So it is working as designed, but the function isn't needed anyways. So yes, a 'bug,' but not a DLL bug, just an XML one. :)
