### ISSUE TITLE
Minor issue: Covering Fire (I & II) descriptions

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5715]
_1. Mod version (i.e Date - 4/23):_
8/31

_2. Mod list (if using Vox Populi only, leave blank):_
List Enhancements for VP (v5)
Trade Opportunities for VP (v8.1)
Filters in Trade Route Overview (VP - v1.3)
Promotion Flags EUI (v1.1)
Capture Great People for VP (v1)

_3. Error description:_ 
The promotion description for Covering Fire (late game infantry ranged units) states "Enemy units within 2 tiles suffer -15% Combat Strength.", while testing seems to show that this only applies to land units, so it would be nice to update the description of this promotion and its successor (Covering Fire II) to reflect that ("Enemy land units" should suffice).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
That parentheses isn't superfluous tho...
( (  ) )

**Comment by UndeadDevel** [comment]
Whoops, you're right, didn't see that for some reason...

**Comment by UndeadDevel** [comment]
This is fixed already.
