### ISSUE TITLE
Diplo AI Trade Value Check Doesn't Factor In Deals, Science & Culture Output

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5717]
_1. Mod version (i.e Date - 4/23):_ latest

In **GetBestApproachTowardsMajorCiv:**

```
	////////////////////////////////////
	// Are we getting money from trade with them?
	////////////////////////////////////
	int iCurrentTradeValueIn = GetPlayer()->GetTrade()->GetAllTradeValueFromPlayerTimes100(YIELD_GOLD, ePlayer) + 
				GetPlayer()->GetTrade()->GetAllTradeValueFromPlayerTimes100(YIELD_CULTURE, ePlayer) + 
				GetPlayer()->GetTrade()->GetAllTradeValueFromPlayerTimes100(YIELD_SCIENCE, ePlayer);
	int iCurrentTradeValueOut = GET_PLAYER(ePlayer).GetTrade()->GetAllTradeValueFromPlayerTimes100(YIELD_GOLD, GetPlayer()->GetID()) + 
				GET_PLAYER(ePlayer).GetTrade()->GetAllTradeValueFromPlayerTimes100(YIELD_CULTURE, GetPlayer()->GetID()) + 
				GET_PLAYER(ePlayer).GetTrade()->GetAllTradeValueFromPlayerTimes100(YIELD_SCIENCE, GetPlayer()->GetID());

	// Scale factor is hard to guess ...
	int iGdpEstimate = GetPlayer()->GetTreasury()->GetGoldFromCitiesTimes100();
	int iTradeDelta = (5 * (iCurrentTradeValueIn - iCurrentTradeValueOut)) / max(iGdpEstimate,1);

	if(iTradeDelta > 0)
	{
		viApproachWeights[MAJOR_CIV_APPROACH_FRIENDLY] += iTradeDelta;
	}
```
**Problem 1**
This check seems to only be factoring in trade value from Trade Routes. While this is fine for Culture and Science, it means that, for instance, if:

Babylon was receiving 200 net GPT per turn from China in trade deals and their total GPT was +50, meaning that their economy would become -150 in the event of war, then;

They wouldn't be dissuaded at all about declaring war. It's an extreme example, but that would be complete stupidity.

**Problem 2**
Furthermore, the GDP Estimate variable means that Science and Culture yields from Trade Routes are being compared to the GPT yield from cities - I get that it's an estimate, but when there is a GetScienceFromCitiesTimes100 function, it seems a bit lazy to not compare them yield-for-yield.

In general but particularly early game, 1 Culture or Science per turn is worth more than 1 Gold per turn.

**Problem 3**
For the Netherlands, there is also no consideration of the Gold and Culture they get from their unique trait that would be lost when trade deals are cancelled, which you would think would be a big deal considering the Dutch's legendary trading history.

**Proposed Solution**
Change variables as follows (all values are times 100):

iCurrentGoldIn = Gold to us from TRs + Gold to us from deals + (Dutch only: Gold from imports/exports)

iCurrentGoldOut = Gold to them from TRs + Gold to them from deals

iCurrentScienceIn = Science to us from TRs

iCurrentScienceOut = Science to them from TRs

iCurrentCultureIn = Culture to us from TRs + (Dutch only: Culture from imports/exports)

iCurrentCultureOut = Culture to them from TRs

Then rather than have one trade delta value, compare Gold with Gold from cities, Science with Science from cities, and Culture with Culture from cities, combine them all together, and the result (with appropriate scaling) can affect the FRIENDLY approach.

That seems to me like a better way of doing things.

**Comment by LoneGazebo** [comment]
I'm fine with those changes, yep.

**Comment by HeathcliffWarriors** [comment]
Only factoring in the yields from trade routes seems to be a Firaxis decision, which is not to say that it makes sense, as I've described above. :)

Is there a function which gets the total amount of GPT from trade deals with another player? I can see one for trade routes, but not deals...

**Comment by LoneGazebo** [comment]
No. But I can make one. You’d have to iterate through all deals IIRC.

**Comment by HeathcliffWarriors** [comment]
That sounds great - I separated the yield evaluations for you. :)

**Comment by HeathcliffWarriors** [comment]
Is adding in the Gold/Culture being earned from importing/exporting resources for the Netherlands too complicated to be feasible/worthwhile? I could drop that.

**Comment by HeathcliffWarriors** [comment]
Scaling it by personality seems like it'll do the trick :)
