### ISSUE TITLE
turn 1 crash

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#5718]
beta 8-10

No matter what I do on my turn, upon processing the turn of 7th AI the game crashes to desktop.

[Catherine_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3744424/Catherine_0000.BC-4000.zip)

**Comment by Edaka** [comment]
This is old, so I assume it's fine now.
