### ISSUE TITLE
Enemy city doesn't shoot at certain targets

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5719]
_1. Mod version (i.e Date - 4/23):_latest

 Enemy city Nimrud never attacks my Trebuchet or Legion who have been sitting there for ages. 
 It does attack any unit that steps into the forest between the two units of mine. Also it does attack any embarked or naval unit. If no other enemy units are in range, the city just skips turn without shooting at the Treb or Legion.

![20191018200150_1](https://user-images.githubusercontent.com/16341598/67113684-c9ad6e00-f1e2-11e9-9911-c09a81960c2d.jpg)

Mods:

![20191018200312_1](https://user-images.githubusercontent.com/16341598/67113700-d16d1280-f1e2-11e9-9d72-20ed3dcf03d4.jpg)

**Comment by ilteroi** [comment]
i think i know why. should be fixed
