### ISSUE TITLE
DoF messages

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#572]
![8930_2015-08-31_00005](https://cloud.githubusercontent.com/assets/1131228/9571811/4e0629f2-4fbd-11e5-816d-314cd6554954.png)
![8930_2015-08-31_00008](https://cloud.githubusercontent.com/assets/1131228/9571815/5c238b9c-4fbd-11e5-9129-edf1ca92b9bf.png)
![8930_2015-08-31_00009](https://cloud.githubusercontent.com/assets/1131228/9571817/62bd7436-4fbd-11e5-84d8-7caba25f0345.png)
![8930_2015-08-31_00011](https://cloud.githubusercontent.com/assets/1131228/9571820/680a28e4-4fbd-11e5-9fb6-b84ff72c6ca7.png)

**Comment by LoneGazebo** [comment]
Is this with the v2?

**Comment by LoneGazebo** [comment]
Ah, I see the problem - duplication of char value. Fixed.
