### ISSUE TITLE
CTD after some turns

### ISSUE THREAD

**Issue by Tarzan737** [LoneGazebo/Community-Patch-DLL#5725]
_1. Mod version (i.e Date - 4/23):_   = 10-8-1

_2. Mod list (if using Vox Populi only, leave blank):_  world trade center wonder, advanced air units, 2 units per fort, improvement airbases, quick turns, RAS v15, Map pins, No mechs, Subs ignore borders, world congress reformation
                                                                

_3. Error description:_  CTD

_4. Steps to reproduce (optional):_

---------------------------
Supporting information: I have played this version some days ago almost a full game (same other mods) then Civ5 suddenly reinstalled itself by steam and now i get CTD just after few turns.
i did clear cache,logs, mod user data and those tings..

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3747670/Logs.zip)

**Comment by Edaka** [comment]
Old version, report back if it happens again. Also, since it happened after a game reinstall, you could try wiling your MODS folder clean and reinstalling mods as well.
