### ISSUE TITLE
Feature Request: Two simple UI improvements for quality of life

### ISSUE THREAD

**Issue by Jack3552** [LoneGazebo/Community-Patch-DLL#5726]
Sorry if I am doing this in the wrong format. I was recommended to make an issue for my suggestions as people on the [forum post](https://forums.civfanatics.com/threads/feature-request-two-simple-ui-improvements-for-quality-of-life.650915/) liked them. I will paste the suggestion below:

**1)** When you mouse over an AI's luxury resource in the trade screen, a tooltip appears (similar to mousing over terrain) to inform you of which of your cities will get WLTK day for acquiring this resource.

E.g. mouse over Indonesia's Pepper, and see:

We Love The King day in:

- Teotihuacan
- Texcoco

This would let me know whether it's worth trading my luxury for one of theirs, vs just for gold. Especially useful when it's a trade deal offered by the AI during their turn, when you can't go back to the map to look at your cities straight away.

**2)** When you mouse over the purchase button to make a gold investment in a building or wonder, a tooltip appears with 'After investment, completed in 'x' turns. This lets me know if it will then be finished on the next turn or not, which helps with minimising the risk of losing your gold investment for wonders, or just generally weighing up whether a building investment is worth the gold.

Thank you coders for your consideration and making this wonderful mod :)

**Comment by LoneGazebo** [comment]
The first is doable, the second, however, would be computationally expensive.
