### ISSUE TITLE
Battleships Issues (No Iron Requirement and Useless Indirect Fire Promotion)

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#5729]
_1. Mod version (i.e Date - 4/23): 10/23

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

1. Cruisers have **iron requirement** but then Battleships don't. 
2. The promotion **Indirect Fire** with the new mechanic is **now useless**.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by UndeadDevel** [comment]
Can I ask what the status on this is? I was just about to post a new issue concerning the Battleship description, which states that it gains the "Range" promotion, which isn't true (I'm still on 10/23).

**Comment by Aqinu** [comment]
For the next release, Helicopter description: "Indirect Fire" instead of "Range".
