### ISSUE TITLE
Unable to remove roads

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#573]
That's a minor issue but sometimes I'm unable to remove railroads (and save some gpt). See the pic.

![2015-08-30_00003](https://cloud.githubusercontent.com/assets/10740997/9573572/3734d4e8-4fbe-11e5-9605-a60e69737c81.jpg)

I was also unable to remove this upper scrap of railroad untill I deleted one of adjacent parts of railroad. Maybe adjacency is somewhat important here.

**Comment by LoneGazebo** [comment]
No idea.

**Comment by LoneGazebo** [comment]
Looked at the code: If you didn't build the route, and you don't own it, you can't remove it. Those are the restrictions.

**Comment by LoneGazebo** [comment]
I've added an additional line that should allow for outside-of-city-limits road deletion.
