### ISSUE TITLE
i wonder how that happened

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5731]
![image](https://user-images.githubusercontent.com/1358966/67517715-7ab07e80-f6a3-11e9-96a5-a763b1a6dd17.png)

**Comment by LoneGazebo** [comment]
Weird. Seems like collusion.

**Comment by HeathcliffWarriors** [comment]
THERE WAS NO COLLUSION-oh wait, wrong investigation.

**Comment by saamohod** [comment]
Same here

![20191027031330_1](https://user-images.githubusercontent.com/16341598/67628039-e2172b80-f867-11e9-81dd-b51f0f2c9217.jpg)
