### ISSUE TITLE
feitoria has wrong description

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5732]
![image](https://user-images.githubusercontent.com/1358966/67519324-e6481b00-f6a6-11e9-8113-578c54d9d151.png)

**Comment by LoneGazebo** [comment]
Yep, that's normal.

**Comment by ilteroi** [comment]
tooltip says in "construct a feitoria in this city state's lands"

**Comment by LoneGazebo** [comment]
typo
