### ISSUE TITLE
Code for latest version?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5733]
Hey G,

Not to rush you or anything, but any chance you could upload the code for the latest beta version to Github soon? I have a number of contributions planned shortly (I plan on demystifying the diplo AI opinion modifiers and posting a lot of diplo-related stuff on the wiki, and am considering moving on to the deal AI next), and it's always useful to have the most current code when engaged in such tasks, especially since it was updated last time.

**Comment by LoneGazebo** [comment]
I had to quickly go out of town for work, will be back tonight.

**Comment by HeathcliffWarriors** [comment]
No worries, thank you :)

**Comment by LoneGazebo** [comment]
should be online now.

**Comment by HeathcliffWarriors** [comment]
Appreciated! I'll get to work :)
