### ISSUE TITLE
Leader Dialogue Issue

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5734]
_1. Mod version (i.e Date - 4/23):_ Latest

_2. Mod list (if using Vox Populi only, leave blank):_ IGE/Quick Turns

_3. Error description:_ First of all, my game isn't crashing anymore - hoping it's not too soon to celebrate that. :)

Vanilla issue: Certain leader dialogue relating to the World Congress does not update when the United Nations is constructed, to read "United Nations". I managed to update the opinion modifier text keys, as you can see, but I'm unsure as to how to go about updating the dialogue.

![Screenshot (19785)](https://user-images.githubusercontent.com/38794241/67544225-9e36f180-f6c2-11e9-9a87-d5dbfcd81547.png)
![Screenshot (19790)](https://user-images.githubusercontent.com/38794241/67544226-9e36f180-f6c2-11e9-8ca1-37c08a5f2236.png)

Strangely, it does work for the "relocated the UN to our lands" message:
![Screenshot (19781)](https://user-images.githubusercontent.com/38794241/67544256-c6beeb80-f6c2-11e9-98f0-356c9c043003.png)

**Comment by LoneGazebo** [comment]
You'd have to create explicitly new versions and tie them to new dialogue response trees...not worth it IMO.

**Comment by HeathcliffWarriors** [comment]
The OCD is real haha...I intend on making some changes to dialogue in the future, so I'll tackle that then.
