### ISSUE TITLE
City Production Bug (Later Era Start)

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5735]
_1. Mod version (i.e Date - 4/23):_ Latest

_2. Mod list (if using Vox Populi only, leave blank):_ IGE/Quick Turns

_3. Error description:_ 
I started a game in the Industrial Era (Quick speed, I think) and the City Production menu looks odd. I can invest in buildings by putting 0 Gold into them, the cost of a lot of stuff is "FREE", and for some reason I can build the Roman Forum (once I get enough policies), but not any other Ancient Era wonders.

![Screenshot (19792)](https://user-images.githubusercontent.com/38794241/67544712-88c2c700-f6c4-11e9-9cd2-14ec29e659c8.png)
![Screenshot (19793)](https://user-images.githubusercontent.com/38794241/67544713-88c2c700-f6c4-11e9-92d9-51261f706dd6.png)
![Screenshot (19794)](https://user-images.githubusercontent.com/38794241/67544714-88c2c700-f6c4-11e9-8963-4a916121e5ad.png)

**Comment by LoneGazebo** [comment]
Yeah advanced starts are totally borked. Another problem for another day...

**Comment by HeathcliffWarriors** [comment]
Mkay, I'll keep this in mind for the future :)
