### ISSUE TITLE
weird yields from CS trade route

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5736]
![image](https://user-images.githubusercontent.com/1358966/67547613-df99c200-f6ff-11e9-9fc2-3a20614cb401.png)

**Comment by LoneGazebo** [comment]
What’s weird about it?

**Comment by ilteroi** [comment]
food and hammers?

**Comment by LoneGazebo** [comment]
that's from a feitoria.

**Comment by ilteroi** [comment]
what can i say, i've never played portugal before :)
