### ISSUE TITLE
(Request - NonIssue) Add Logging to Track cumulative yields for each building

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5737]
This is not an issue, but a request (I wasn't sure where to put it exactly).

A feature that would help us in the forums get some real metrics on balance for buildings (especially late game ones), is it possible to log a specific building in the game (or all buildings) and track how many yields I am gaining due to that building?

For example, the Council provides +1 science, and 5 science (era scaling) each time I grow. Is it possible to log all of the science generated by the council for each city, so that when the game ends I can see a report that shows me the total science that each council generated, and the number of turns that building has been active? Something like:
Barcelona - Council: 500 science, 350 turns
Madrid - Council: 400 science, 300 turns

The base yields would be good as a start, in the perfect scenario the logging would also factor in any percentage bonuses. So a +10 science in a city with a +10% science bonus would actual generate 11 science while that bonus is active.

Thank you for taking a look at this and considering it.

**Comment by MoiMagnus** [comment]
Just to be clear, are you talking about "yields of a specific Council" or "cumulative yields of all the Council build during the game?"

**Comment by Stalker012345** [comment]
> Just to be clear, are you talking about "yields of a specific Council" or "cumulative yields of all the Council build during the game?"

I updated the original post to clarify a bit. I would want yields for a city's council. So a list of each city and that building, and then the yields. An example was placed in the original post.

**Comment by LoneGazebo** [comment]
Unfortunately that data isn’t stored for cumulative control, and to do so would be quite the investment in memory (number of cities * number of buildings * number of yields * number of turns). Talk about a huge table!

**Comment by Stalker012345** [comment]
> Unfortunately that data isn’t stored for cumulative control, and to do so would be quite the investment in memory (number of cities * number of buildings * number of yields * number of turns). Talk about a huge table!

What if you could do capitals only? Do you think that would cull it down enough?

**Comment by HeathcliffWarriors** [comment]
In theory, could it be stored in a logfile and retrieved from there at the end of the game (or when requested) rather than kept in memory?

**Comment by LoneGazebo** [comment]
But where would the logfile draw the cumulative data from? That data has to be stored.

**Comment by Stalker012345** [comment]
> But where would the logfile draw the cumulative data from? That data has to be stored.

If the log file just had a turn by turn dump of the yields each building generated, I could do some work to sum it all together at the end. That in theory would be memory light...I think.
