### ISSUE TITLE
AI requests free Open Borders

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5738]
_1. Mod version (i.e Date - 4/23):_ Latest

_2. Mod list (if using Vox Populi only, leave blank):_ IGE, Quick Turns

_3. Error description:_ 

Tempting, Bismarck.

This is not because he has nothing to offer me (he could offer GPT) but rather that he values my OB at 0 Gold (or close to it), and yet still asks for them.

![Screenshot (19772)](https://user-images.githubusercontent.com/38794241/67588829-0e765f00-f725-11e9-9726-7ae416b510cd.png)

**Comment by LoneGazebo** [comment]
Yes?

**Comment by HeathcliffWarriors** [comment]
If the AI considers requests of the "something for nothing" type to be not only unacceptable but insulting (according to the deal AI), I'd question why they're making such offers.

Not many players, human or AI, are likely to agree. :)

**Comment by LoneGazebo** [comment]
Well he values it at essentially 1-2 GPT, but for the AI that's close enough to zero (but still positive) that they'll send it this way. I bet you can add 1GPT to it and he'll agree.

**Comment by HeathcliffWarriors** [comment]
I see...but would it be feasible to add a check to prevent them from sending offers with nothing on their end?

**Comment by LoneGazebo** [comment]
There's a check for zero offer deals, but this technically isn't a zero offer.

**Comment by HeathcliffWarriors** [comment]
Zero offer on their end, then?

Something like: if Deal Value On My End = 0, don't send?

**Comment by LoneGazebo** [comment]
Likely the latter - remember that the 'acceptable' tag applies to deals within a range of value of 1-2GPT, so technically he just asked you for OB for 1 GPT or so.

**Comment by HeathcliffWarriors** [comment]
Looking at the deal AI, it looks like they consider you to consider OB valuable for Tourism reasons, so I suspect that's driving it. But hard to make an explicit check for that possibility. Ah well, minor enough to ignore.
