### ISSUE TITLE
10/23 - Possible Combat Damage Bug

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5739]
_1. Mod version (i.e Date - 4/23):_
10/23

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I may just be misreading city combat here, but considering the two combat strengths, I don't think my swordsman should be taking near this much damage.

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/67604662-ca458780-f741-11e9-96c7-9aa846950cf2.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
yeah it's weird, there are arbitrary modifiers for melee city attack/defense in the database

ATTACKING_CITY_MELEE_DAMAGE_MOD == 100
CITY_ATTACKING_DAMAGE_MOD == 100

this has the effect of amplifying the result of the battle - ie either you take a lot of damage or you do a lot of damage.

this only became visible after a recent code change, don't know what's the intended behavior.
