### ISSUE TITLE
CityView (8-29v2)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#574]
Cycling through cities doesn't work properly.
I can see only 2 CityViews.

Active mods: 
Community Patch (8-29v2)
Ingame Editor
![cityview](https://cloud.githubusercontent.com/assets/11933188/9576887/08ee27de-5017-11e5-9089-f34973abddd2.jpg)

**Comment by Radost** [comment]
You can't view puppets through these buttons.

**Comment by 8h42** [comment]
I have no puppet city.
Three of them are my own cities.

**Comment by phantommaxwell** [comment]
Can confirm this issue

**Comment by LoneGazebo** [comment]
I'll look, but keep in mind that the Community Patch does not touch the UI.

**Comment by LoneGazebo** [comment]
I can verify this exists as a problem - not sure why, though, as the code is untouched.

**Comment by 8h42** [comment]
I checked older versions.
CP(8-28) has the same problem.
CP(8-24) works fine.

**Comment by LoneGazebo** [comment]
Yep - ilteroi's ID changes caused the DLL backend to mess up. Fixed in upcoming version.
