### ISSUE TITLE
AICreatePercent Question

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5740]
_1. Mod version (i.e Date - 4/23):_ Latest

Given that you removed the per era modifier for both World Congress projects _and_ regular projects (like Manhattan), it's worth noting that AICreatePercent is still granting a Production discount of up to 30% on regular projects.

I was wondering if your intent was to remove all discounts on these projects - which might be worth considering for fairness, given that the first to complete MH gets a bonus and that the Apollo program is required for the Science victory.

I daresay a 30% (on Deity) discount on two(?) specific projects is not really meaningful enough to be worth keeping.

**Comment by HeathcliffWarriors** [comment]
I'll just remove it in my next pull request and you can discard that file if you disagree :)

**Comment by LoneGazebo** [comment]
Works for me.
