### ISSUE TITLE
IsWantsToConquer Flag

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5744]
_1. Mod version (i.e Date - 4/23):_ Latest

With the current IsWantsToConquer flag, AIs that start a coop war or trade war where they're backed up by another player are discouraged from launching attack operations unless the target value is favorable or they're bold.

I have edited this slightly in my current pull request to make AIs who choose to start a coop/trade war more willing to launch attacks, since they're backed up by another player. 

There's a VP-added check in GetCoopWarScore which makes the AI disregard target value if they're fiercely competitive when starting a coop war, so I added a check like this as well. 

I also changed it so that the AI always wants to conquer players if the Always War or No Changing War or Peace game options are enabled, since that flag is used in scenarios where the main objective is to conquer the enemy.

I think this'll make the AI a bit more willing to follow through on its commitments, without detracting from the function's use as a "defensive war flag". :)

**Comment by ilteroi** [comment]
sounds good!
