### ISSUE TITLE
CS mission completion triggers prematurely 

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5746]
_1. Mod version (i.e Date - 4/23):_10-23

CS wants me to discover lands of France. On a certain turn I get notification that the CS is happy for my discovery and gives me the reward. However I cannot see the land of France. See screenshot.

![20191027030428_1](https://user-images.githubusercontent.com/16341598/67627651-ceb89000-f868-11e9-97f4-d3207c0508a3.jpg)

Next turn I move further down South and notice France. Now I see it.

![20191027030638_1](https://user-images.githubusercontent.com/16341598/67627658-f9a2e400-f868-11e9-9450-dfe9e4f43af4.jpg)

I thought I may have not noticed the lake tile the previous turn (which is the closest to me), but it was not visible then. Here's the strategic view of the **previous turn** with the lake hex marked by blue circle down at the bottom.

![201](https://user-images.githubusercontent.com/16341598/67627728-4a670c80-f86a-11e9-96fc-74c4811764d2.jpg)

**Comment by LoneGazebo** [comment]
Adjacency to borders counts.
