### ISSUE TITLE
AI naval unit desregards healing

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5747]
_1. Mod version (i.e Date - 4/23):_10-23

This dromon has been sitting wounded in the open ocean for ages instead of moving one tile to his native territory to heal.

![20191027181953_1](https://user-images.githubusercontent.com/16341598/67637805-db7bc900-f8e6-11e9-88c6-4523c3a67015.jpg)

Mods:
![20191027182253_1](https://user-images.githubusercontent.com/16341598/67637815-e9c9e500-f8e6-11e9-94e0-a465f61ed7b9.jpg)

![20191027182257_1](https://user-images.githubusercontent.com/16341598/67637817-efbfc600-f8e6-11e9-8397-4196981a87ce.jpg)

EDIT: generally I presume that AI not only forgot to heal the unit, but it has forgotten about him completely. Denmark has been in a couple of wars since I first noticed the dromon, but the ship has been motionless for dozens of turns.

**Comment by UndeadDevel** [comment]
Seen this as well in 31/8...I had reported this (or a very similar issue) last year already (#4985) but maybe the fix didn't work?

**Comment by LoneGazebo** [comment]
@ilteroi any ideas?

**Comment by ilteroi** [comment]
hmhmhm. i suspect it's the stupid homeland AI controlling this unit, since there is no enemy around. i've been meaning to rewrite that part for a while ...

**Comment by LoneGazebo** [comment]
stupid homelander

**Comment by ilteroi** [comment]
should be better now
