### ISSUE TITLE
military strength stats

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5748]
i'm in a war with the zulu right now which i won, they have hardly any units left. still infoaddict says we are almost equal in military power? so i finally took a closer look and it's confusing.

* raw military unit count is 23 vs 13 (most of them useless naval units ...)
* raw military score is 545 vs 332 (no scaling with number of cities anymore!)
* world factbook has "active duty military" 45k vs 36k
* diplomacy overview has "soldiers" 116k vs 91k

so what is correct? the first two roughly agree, and the latter two roughly agree. but how do you go from 545 to 45k to 116k?

**Comment by LoneGazebo** [comment]
@ilteroi possible that the world 'factbook' uses some pseudomath within the lua?

G

**Comment by ilteroi** [comment]
well the factbook apparently uses math.sqrt( p:GetMilitaryMight() ) * 2000; however the value in the graph should be using the plain GetMilitaryMight() ... i don't understand it

**Comment by LoneGazebo** [comment]
Yeah for some reason firaxis loved to use fake math in their LUA for the UI...
