### ISSUE TITLE
Corporation typos

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#575]
- Trader Sid's, Inc.
Text: All Caravansaries produce +2 Gold and **+2  Culture**.
Effect: All Caravansaries produce +2 Gold and **+2 Food**.

- TwoKay Foods, Inc.
Text: **+3** Food on all Monopoly Resources associated with TwoKay Foods.
Effect: **+2** Food on all Monopoly Resources associated with TwoKay Foods.
 
Related files:
- Community Balance Patch (8-29)\Modular Elements\Corporations\TraderSid.xml
- Community Balance Patch (8-29)\Modular Elements\Corporations\TwoKayFoods.xml
- Community Balance Patch - Compatibility Files (EUI) (8-29)\Corporations\Corporations.sql
- Community Balance Patch - Compatibility Files (No-EUI) (8-29)\Corporations\Corporations.sql

**Comment by LoneGazebo** [comment]
fixed, thanks!
