### ISSUE TITLE
Logging camp / Lumbermill: Description in techtree is other than function

### ISSUE THREAD

**Issue by 4CV** [LoneGazebo/Community-Patch-DLL#5755]
_1. Mod version (i.e Date - 4/23):_ October 23rd (10-23)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  
Techtree: Machinery unlocks logging camps. Metallurgy unlocks lumbermills.
But I can construct both already, without Metallurgy researched

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/25335477/67791733-47da0200-fa78-11e9-80ba-bbb3d5c53539.png)

![image](https://user-images.githubusercontent.com/25335477/67800386-74494a80-fa87-11e9-9be5-de73e5516ad0.png)

**Comment by 4CV** [comment]
At first I thought it was only a description error, because i had already constructed some lumbermills and didn't even think of constructing logging camps so early. 

![image](https://user-images.githubusercontent.com/25335477/67801291-2af9fa80-fa89-11e9-87c0-47443cbedd8e.png)

**Comment by UndeadDevel** [comment]
Check the tech tree again, 'cause I'm pretty sure "Metal Casting" is supposed to unlock Lumber Mills and "Machinery" Logging Camps; "Metallurgy" simply gives more production for one or both of those.

**Comment by 4CV** [comment]
Right you are, how stupid one man alone can be...
