### ISSUE TITLE
AI doesn't disband settlers

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5759]
_1. Mod version (i.e Date - 4/23):_10-23
 
It seems AI doesn't know how to disband settlers (colonists etc) in the late game.

![20191030075107_1](https://user-images.githubusercontent.com/16341598/67832483-7690c080-faea-11e9-890d-8b930bc059c7.jpg)
![20191030075115_1](https://user-images.githubusercontent.com/16341598/67832490-78f31a80-faea-11e9-8736-0ce26a8c86b7.jpg)

**Comment by HeathcliffWarriors** [comment]
Relevant code:
```
void CvEconomicAI::DisbandUselessSettlers()
{
	//If we want settlers, don't disband.
	EconomicAIStrategyTypes eNoMoreSettlers = (EconomicAIStrategyTypes) GC.getInfoTypeForString("ECONOMICAISTRATEGY_ENOUGH_EXPANSION");
	int iNumSettlers = m_pPlayer->GetNumUnitsWithUnitAI(UNITAI_SETTLE, true);
	int iNumCities = m_pPlayer->GetNumCitiesFounded();

	bool bNoMoreSettlers = m_pPlayer->GetEconomicAI()->IsUsingStrategy(eNoMoreSettlers);
	if(!bNoMoreSettlers)
	{
		return;
	}

	//two settlers are ok
	if (iNumSettlers <= 2)
	{
		return;
	}

	CvCity* pCapital = m_pPlayer->getCapitalCity();
	if(!pCapital)
	{
		return;
	}

	//Don't disband during the early game.
	if(iNumCities <= 4 && (GC.getGame().getGameTurn() <= 150))
	{
		return;
	}
	if (m_pPlayer->HaveGoodSettlePlot(-1) )
	{
		return;
	}

	CvUnit* pUnit = FindSettlerToScrap(false);
	if(!pUnit)
	{
		return;
	}

	pUnit->scrap();
	LogScrapUnit(pUnit, iNumSettlers, iNumCities, -1, 0);
}
```

**Comment by saamohod** [comment]
>It has 3+ Settlers;

Does it mean that if it has 3 or less settlers it'll be keeping them till the end?

**Comment by HeathcliffWarriors** [comment]
If they have 1-2, yes. 3+ will be reduced to 2 if the other conditions are met.

**Comment by saamohod** [comment]
In a late game like my example probable the only opportunity to settle is when a city is razed somewhere due to a war. I'm not sure if it's worth the drain of gold for settler maintenance for a very slim chance of settling a city.
