### ISSUE TITLE
Tourism influence and trade routes

### ISSUE THREAD

**Issue by Finarvi** [LoneGazebo/Community-Patch-DLL#576]
I can see that with each level of tourism influence I get more science from TRs, faster espionage, less pop loss. But also less gold from TRs. Shouldn't it be that the more influential you are, the more gold you take? Maybe that's just a tooltip bug but it's confusing.

**Comment by LoneGazebo** [comment]
Nope, that's working as designed. You get more gold for exotic, but less science. It then flips. Think about it: exotic goods are worth more than common (popular) goods.

**Comment by Finarvi** [comment]
OK, thank you. Yeah, that makes sense.

2015-08-31 22:35 GMT+02:00 LoneGazebo <notifications@github.com>:
