### ISSUE TITLE
AI doesn't want its cities back

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5760]
_1. Mod version (i.e Date - 4/23):_10-23

![20191030082548_1](https://user-images.githubusercontent.com/16341598/67834076-12243000-faef-11e9-8d35-0be0c976b979.jpg)
![20191030082538_1](https://user-images.githubusercontent.com/16341598/67834077-13edf380-faef-11e9-9f88-005d529c8bc1.jpg)

I captured a city from Ethiopia. A while later I want to sell or give him his city back, but the diplomacy window says "We don't have any tradeable cities".

**Comment by HeathcliffWarriors** [comment]
Not a bug - you can't trade with a sanctioned AI (except peace treaties and masters with their own vassals). Cities included.
