### ISSUE TITLE
Two small installer issues

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5761]
_1. Mod version (i.e Date - 4/23):_
10/23

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Normally I download and copy the files manually but since the manual download hasn't been provided for the newest beta yet I used the installer this time and noticed two small issues:
-  I removed EUI from my DLC folder for testing purposes and, sure enough, despite choosing the VP EUI option in the installer it did not install EUI (the DLC wasn't copied, the 6a mod component, on the other hand, was copied normally)
- When the installer tells the user what is going to be installed it fails to mention the 7a and 7b components (very small issue but it may confuse those users that are new and wonder why there are these non-mentioned components in their MODS folder after the install).

My Steam folder is in a non-standard location in case that's relevant, but the game is properly installed within the steamapps folder.

_4. Steps to reproduce (optional):_
use latest installer on clean civ 5 install

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by MoiMagnus** [comment]
The installer always install EUI without problems, so that one is probably linked to your Steam folder being on a non standard location.

However, I see this problem (the EUI folder not being installed properly) being reported quite frequently. So it's not a "only on one machine" problem.

**Comment by LoneGazebo** [comment]
Those features cost money.

**Comment by UndeadDevel** [comment]
Ah, because of licensing or getting a new certificate or something?

Well in that case I'd say it isn't worth it for such small issues...
