### ISSUE TITLE
City-State War Declarations Trigger DPs

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5762]
_1. Mod version (i.e Date - 4/23):_ Latest

https://forums.civfanatics.com/threads/quick-questions-quick-answers.573489/page-282#post-15581609

When you declare war on a civ while having a DP, your DP will not go to war. However, if that civ has a CS ally and the ally declares war on you, it will trigger your DP and the City-State will be at war with them - despite not being Peace Blocked.

Should City-State declarations be triggering DPs? Moi Magnus raises the point that it's unwarranted as they're largely defensive in nature, and if your civilization is at serious risk of being defeated by a City-State, you're clearly behind the curve defense-wise. :)

Strikes me as unintended behavior.

**Comment by Omen-of-Peace** [comment]
Having had allied CS conquered because of that (by the civ they declared war on because of the DP) I'm partial to changing this!

It forces the player to monitor these interactions carefully, and potentially pay the other civ to make peace with the CS again, which is not fun.
