### ISSUE TITLE
interesting statistics for unit production

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5763]
with some regex and pivot magic i created the following diagram

![unit-productions-stats](https://user-images.githubusercontent.com/1358966/67896901-944b3d80-fb5d-11e9-8404-9a61f29bd7c1.png)

this is the number of units built per type from about 0 AD to 2015 AD, standard size map, 8 players. 

confounding factors:
* bought units 
* losses in combat
* unit upgrades
* time constraints, unit unlock and obsolescence
* resource constraints
* build cost
* build interruptions

still it's obvious that the AI likes some unit types more than others ...

edit: aircraft are missing due to a script error

**Comment by ilteroi** [comment]
i'll take a look at buildings next, i feel there's a lot of data mining potential in the logfiles ...

**Comment by LoneGazebo** [comment]
Neat - I wonder why paratroopers blow everything else away...

**Comment by MoiMagnus** [comment]
This graph shows that the AI love "ressource-free melee units" (where low range units like Gatling guns are considered melee)

I think the conclusion of this graph is that Infantry must be pretty bad, and even after having unlocked them, the AI still prefer building paratroopers. 

(Though conclusion from few games are always very approximative, as units from era where everybody is at war will obviously be build in higher numbers)

**Comment by azum4roll** [comment]
There's an alarming lack of utilization of Jaguars.

**Comment by ilteroi** [comment]
here's another picture, same civs, different map (oval instead of pangea). turn 0 to 440. paratroopers not so dominant this time.

![unit-productions-stats2](https://user-images.githubusercontent.com/1358966/68008330-dae48900-fc7e-11e9-9040-870ad735cc32.png)
