### ISSUE TITLE
Proposed AI Sanity Check

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5765]
_1. Mod version (i.e Date - 4/23):_ Latest

While comparing the BNW diplo AI with the VP diplo AI, I noticed that the AI's "sanity check" to avoid going into negative GPT from war had been removed.

I don't blame you, it was woefully inadequate (as is the remnant in GetCoopWarScore). I have written a better function in my current pull request.

However, there are still circumstances where it would be strategically advantageous for the AI to avoid going to war, and where the current bonus to FRIENDLY from positive trade deals might not be sufficient.

For instance, if AI's GPT is 50, and it would lose 100 GPT from going to war, it should probably think twice.

I see two problems with a straightforward sanity check like the BNW one, however:
1 - There's no consideration of the AI's Gold reserves. If the AI has 0 Gold, -5 GPT is much more impactful than if they had 10,000 Gold.

2 - The AI might be able to change their city focus or make deals with other players to compensate for the lost GPT.

Any thoughts on this?

**Comment by ilteroi** [comment]
well you could implement a check for "turns until bankrupt < 30" or so

**Comment by HeathcliffWarriors** [comment]
Hmm, good thinking on point 1. Continuing with that, perhaps point 2 could be addressed by weighting the sanity check modifier in terms of how long it would take for bankruptcy.

So if it was -1 value per GPT in the negative, and it would take 15 turns to reach 0, reduce the total value by 15%, or something like that.

**Comment by azum4roll** [comment]
Should perhaps take instant yields into account too. I'd start a war losing 100GPT if I know I can get more than that back from city captures/unit kills.

**Comment by HeathcliffWarriors** [comment]
@azum4roll Good point; it isn't hard to take the average of the past 10 turns' instant yields into account.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo 
What would you think about this as a sanity check?

1) Calculate the amount of GPT that would be lost by declaring war on another player.

2) Calculate the average of instant Gold yields over the past 10 turns.

3) "Adjusted GPT" = (current GPT + recent average GPT from instant yields) - lost GPT

4) If the adjusted GPT rate is negative, proceed to step 5, otherwise end here.

5) Calculate the amount of turns it would take to reach bankruptcy at the adjusted GPT rate. If 30 or less, then proceed to step 6, otherwise end here.

6) iValue = 1 per GPT in the negative at the adjusted rate

7) Reduce iValue by 2% for each turn it would take to reach bankruptcy. So if already bankrupt, the full decrease is applied; if it would take 30 turns, reduce by 60%. If iValue was -20, it would be reduced to -8.

8) Subtract iValue from the War approach weight, and also the weight in GetCoopWarScore.
