### ISSUE TITLE
stats for buildings

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5767]
standard map, 8 players (plus minors), from the beginning up to 2020. this one is actually rather boring, no big unexpected outliers:

![buildings-stats](https://user-images.githubusercontent.com/1358966/68008272-a40e7300-fc7e-11e9-85d2-de55afa2ed08.png)

but those are only the unique builds, meaning we only count once if the build was interrupted. this happens a lot, there are 2652 unique builds vs 4089 overall.

btw one weird thing showed up in the log:
```
107, TheAztecs, Lyon, SEED: 5076662547903419532, CHOSEN: Building, Walls, Rushifpossible, TURNS: 39
107, TheAztecs, Lyon, SEED: 5076662547903419532, CHOSEN: Unknown, , Donotrush, TURNS: 0
```

**Comment by Stalker012345** [comment]
The interesting notes for me:

So Judging by the stats, there were about 24 cities total in the game (average 3 per civ, which seems low but its in the ballpark).

Amphitheaters are a bit low considering how early they come into play. I would also think the AI is severely undervaluing Chanceries and Wire Services. Even if the AI doesn't get a lot of alliances and just gets friends, that is an incredible amount of yields to be giving up.

**Comment by azum4roll** [comment]
Seeing Aztecs, France, Zulu, Mongolia, Sweden, Songhai all exist, it can be assumed that city states are mostly gone from the map.

**Comment by ilteroi** [comment]
oops, you know that 50% of all statistics are false .... there was an error in the uniqueness check, i've updated the picture

**Comment by HeathcliffWarriors** [comment]
I thought 61.3% of statistics were made up on the spot? :)

**Comment by LoneGazebo** [comment]
62.5%
