### ISSUE TITLE
Minor issue: bonus vs Barbarians higher than should be

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5770]
_1. Mod version (i.e Date - 4/23):_
10/23

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) List Enhancements for VP (v 5)
(ui) Trade Opportunities for VP (v 8.1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations
Global - City State Airbases (v 4)
Improved Air Recon (v 1)
Promotion Flags EUI (v 1.2)
Subs Ignore Borders
Subs Immune Under Ice
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Religion Spread (Vox Populi) (v 1.0)

_3. Error description:_ 
As you can see in the screenshot my level 1 Warrior is getting a 53% bonus against the barbarian even though I went Tradition and the Brute Force promo is only supposed to give 33%. This is on Emperor difficulty and Epic speed, in case that matters.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![Anti-Barbarian-Bonus](https://user-images.githubusercontent.com/30495439/67997911-29c5fa80-fc4e-11e9-9738-c546e54b831c.jpg)

**Comment by HeathcliffWarriors** [comment]
Emperor difficulty = +20% bonus VS Barbarians

**Comment by UndeadDevel** [comment]
Ah yes I forgot about that...the "BarbarianBonus" in the DifficultyMod; makes sense, thanks!
