### ISSUE TITLE
Improvement_YieldPerEra only triggers on Ancient Era improvements

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#5775]
_1. Mod version : 10/23

_2. Mod list (if using Vox Populi only, leave blank): Nubia for VP

_3. Error description: Nubia is a custom civ by LITE and MC. Its royal pyramid UI is supposed to give +1 faith and +1 culture for each era between when it was built and the current era (the landmark's yield per era mechanic)

INSERT INTO Improvement_YieldPerEra (ImprovementType, YieldType, Yield)
SELECT 'IMPROVEMENT_MC_LITE_NUBIAN_ROYAL_PYRAMID', 'YIELD_CULTURE', 1 UNION ALL
SELECT 'IMPROVEMENT_MC_LITE_NUBIAN_ROYAL_PYRAMID', 'YIELD_FAITH', 1;

Currently, only pyramids built in the Ancient Era gain yields per era. All UIs built in subsequent eras do not gain any yields. 

4. Steps to reproduce (optional): Add Improvement_YieldPerEra to any non-landmark improvement.

---------------------------
Supporting information:
![image](https://user-images.githubusercontent.com/33136027/68073249-a989bd00-fd53-11e9-95a9-1e264fe64809.png)

**Comment by pineappledan** [comment]
Found the issue. You have to place a ruin below the tile in order to activate the Improvement_YieldPerEra. Maybe something could be done to unhook the yieldPerEra from the ancient ruins system, but it's not necessary in this use case

**Comment by LoneGazebo** [comment]
The only time in which the 'era' component of a thing is saved is if it is a ruin. Improvements don't record their era.

**Comment by pineappledan** [comment]
Fair nuff
