### ISSUE TITLE
route to cancelled

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5776]
_1. Mod version (i.e Date - 4/23):_10-23

Every now and then this thing happens which I presume is a bug. 
A worker is ordered to build a road to a neutral tile that has no road, then a message pops up:

![20191102201603_1](https://user-images.githubusercontent.com/16341598/68075249-f7cbaa00-fdad-11e9-9355-56a23a3b2c5e.jpg)

The tile where I want to build a road is marked on the screenshot:

![Inked20191102200606_1_LI](https://user-images.githubusercontent.com/16341598/68075288-52fd9c80-fdae-11e9-9e8e-fc4b1d93b014.jpg)

**Comment by ilteroi** [comment]
i assume that"s because the plot is potentially in danger
