### ISSUE TITLE
Austrian Hussar promotion

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5779]
_1. Mod version (i.e Date - 4/23):_10-23

Hussar possesses the promotion Lightning Warfare which gives +15% combat strength when attacking. 

![20191103034455_1](https://user-images.githubusercontent.com/16341598/68079097-a1ca2700-fdec-11e9-92fb-8dd8deb65eab.jpg)

The problem is, Hussar is a ranged unit, it attacks with ranged combat strength.

**Comment by Aqinu** [comment]
This is not a bug, a lot of promotions are shared between melee and ranged units, and when melee combat strength is showed for any range unit it means that modifies the range attack/defence (because it is impossible for a range unit to attack with melee strength, exception only when defending against melee attack)

**Comment by saamohod** [comment]
@Aqinu 
Would it be better if it read "+15 % attack strength" or something like that? Without mentioning combat or ranged.

**Comment by Aqinu** [comment]
Personally I would make the change to read just "Combat Strength" instead of "Icon Ranged Combat Strength" and "Icon Combat Strength" (it would be easier to replace all the promotions this way) but I don't know if @LoneGazebo finds any issues with this.

**Comment by LoneGazebo** [comment]
Firaxis design means that +% combat strength and +% ranged combat strength mean the same thing for ranged units.

**Comment by Aqinu** [comment]
So, If I understand correctly you are **against** the suggestion of changing all "**[Range_Icon] Ranged Combat Strength**" and "**[Melee_Icon] Combat Strength**" to say just "**Combat Strength**" without melee or range icon?

My opinion is that those **icons** can cause some confusions of understanding for the new players and it will be better without them...

**Comment by saamohod** [comment]
I too think that the **icon** is misleading.

**Comment by Aqinu** [comment]
Or other suggestion, in case that we don't want to get rid off icons, just replace them with "[ICON_WAR] Combat Strength", like in this screenshot:
![Civ5Screen0002](https://user-images.githubusercontent.com/49090452/68106716-2ef3a580-feeb-11e9-9e0d-0fc04edb1aa8.png)
