### ISSUE TITLE
English spy + Patronage opening

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#578]
I got the patronage opening (getting a spy before rennaisance era) and then when I entered rennaisance as ENgland I did not get my spy and an extra one. (playing on a small map)

**Comment by LoneGazebo** [comment]
Will look at code. I hope to hell that Firaxis didn't hard-code that spy logic for England.

**Comment by LoneGazebo** [comment]
It was hardcoded. Fixed.
