### ISSUE TITLE
UI doesn't show opener policy choices

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#5780]
_1. Mod version (i.e Date - 4/23):_ Latest

_2. Mod list (if using Vox Populi only, leave blank):_
Archaeology Aesthetic Adjustments
Quick Turns
Calypso's Colored Religious Icons
Faster Aircraft Animations

_3. Error description:_ Finally not crashing anymore! Happy about that.

This issue has bugged me for a while. The UI will show me that the AI has unlocked a policy tree in the form of the "We have similar/divergent Social Policies" modifier, but won't show me _what_ policy tree they've adopted until they unlock more policies. The opener doesn't seem to count.

The AI gets this information, so why shouldn't the player?

![Screenshot (20017)](https://user-images.githubusercontent.com/38794241/68080345-ff9c4600-fdcf-11e9-80d6-555bbfbf23fb.png)

**Comment by LoneGazebo** [comment]
Blame Firaxis. Openers don't count as policies for UI anywhere, and I don't see a way to make that so because of how the tables are managed at a root level.

**Comment by HeathcliffWarriors** [comment]
What about IsPolicyBranchUnlocked? The diplo AI uses that in GetPolicyScore.
