### ISSUE TITLE
Incorrect Embassy Description

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5782]
_1. Mod version (i.e Date - 4/23):_ Latest

![Screenshot (20021)](https://user-images.githubusercontent.com/38794241/68080389-c7e1ce00-fdd0-11e9-9d30-eb462d1918e6.png)

Incorrect on two counts: it _can_ be built on top of resources now, but it does _not_ connect the resources it's built on to the empire's trade network (since it's on City-State territory).

**Comment by LoneGazebo** [comment]
Latter code is generated separately and added to the TT, so it's immutable.

**Comment by HeathcliffWarriors** [comment]
Possible to hard code an exception for it? The Embassy is the only GP improvement built in someone else's territory.
