### ISSUE TITLE
Great General does not count towards City CS

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5783]
I thought Great Generals were supposed to buff the City's CS? I've had several situations this game where they've done nothing to it at all; probably has to do with the new calculation.

**Comment by UndeadDevel** [comment]
Can confirm for 10/23.

Also, naval units now boost city strength more than land units unless a land unit is already in the city as well (in which case the city gets the lower land unit boost and ignores the naval unit boost)...I thought it was supposed to be changed the other way around?

**Comment by LoneGazebo** [comment]
@ilteroi can comment

**Comment by ilteroi** [comment]
the garrison strength issue with land/naval units is fixed, afaik generals never gave extra strength?

**Comment by UndeadDevel** [comment]
Generals and Admirals both gave the city extra strength as long as it had a garrison (it didn't matter if it was a land garrison with admiral or naval garrison with general)...this was still the case in the 8/31 version; I'm guessing it broke when the garrison/city strength change was introduced.

**Comment by ilteroi** [comment]
maybe it's just me but i never knew. anyway this seems to me like yet another AI unfriendly micromanagement feature, do we really need it?

**Comment by UndeadDevel** [comment]
For my part I liked it a lot, even though the defensive boost was never that substantial (usually like 3-6 points) but I think right now people are assuming it's a bug that it went away since removing this was never discussed. If you think it's better without this feature the forum should probably be made aware of it so others can have their say as well.

**Comment by UndeadDevel** [comment]
I created a [forum thread](https://forums.civfanatics.com/threads/great-general-admiral-buffing-city-strength.652500/) for discussing this and allowing people to vote on this issue. So far the people seem to be strongly in favor of keeping the defense boost.
