### ISSUE TITLE
Extra Space

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5785]
_1. Mod version (i.e Date - 4/23):_ Latest

"The  City of Jerusalem" has an extra space between The and City.

![Screenshot (20039)](https://user-images.githubusercontent.com/38794241/68080454-222f5e80-fdd2-11e9-8143-5f87257fe2a5.png)

**Comment by UndeadDevel** [comment]
Can confirm for 10/23, this seems to be true for all City States but not Major Civ cities.

**Comment by LoneGazebo** [comment]
I haven't touched this.

**Comment by HeathcliffWarriors** [comment]
I don't think it's a recent bug, I've noticed it's been the case for a while - any chance of fixing?
