### ISSUE TITLE
Can Annexation Show Projected Unhappiness Increases?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5786]
_1. Mod version (i.e Date - 4/23):_ Latest

![Screenshot (20050)](https://user-images.githubusercontent.com/38794241/68080475-76d2d980-fdd2-11e9-9c00-904f60a53740.png)

It would be nice if you could see how much annexing a city will raise your Unhappiness; the tooltip here is not particularly helpful.

**Comment by UndeadDevel** [comment]
Well, you can see the Population number in the upper left corner, which, as the tool tip says, will be your Unhappiness until you build the Courthouse. IMO it's fine but I'm not entrenched if someone wants to add that to the tool tip directly...

**Comment by HeathcliffWarriors** [comment]
Oh, true. Brain fart there. But I thought Unhappiness wasn't capped at the city's population anymore? I'm confused. :)
