### ISSUE TITLE
Holy Site yields not showing on tooltip

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5787]
_1. Mod version (i.e Date - 4/23):_ Latest

_2. Mod list (if using Vox Populi only, leave blank):_
Archaeology Aesthetic Adjustments
Quick Turns
Calypso's Colored Religious Icons
Faster Aircraft Animations

_3. Error description:_  The yields for construction are missing.

![Screenshot (20044)](https://user-images.githubusercontent.com/38794241/68080509-4475ac00-fdd3-11e9-9d3b-a9a593cf07d7.png)

**Comment by LoneGazebo** [comment]
It's a weird vanilla issue with the pillaged attribute being tied to the plot, not the improvement. Can't really change that.

**Comment by HeathcliffWarriors** [comment]
Huh. Weird.
