### ISSUE TITLE
Great Wall Works on Missionaries

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5788]
_1. Mod version (i.e Date - 4/23):_ Latest

_2. Mod list (if using Vox Populi only, leave blank):_
Archaeology Aesthetic Adjustments
Quick Turns
Calypso's Colored Religious Icons
Faster Aircraft Animations

_3. Error description:_ The Great Wall makes Missionaries expend all movement when entering (at least when you don't have an Open Borders treaty). Intentional? I mean, it's kind of cool, and powerful against Missionaries, but I wonder if it's a bug, as it's only supposed to apply to enemy units and Missionaries are usually neutral.

**Comment by UndeadDevel** [comment]
I vote keep it as is...if I don't give someone OB I don't want their units slogging through my lands, especially units that can mess with me (which Missionaries definitely can)...makes a nice additional perk for a Wonder that will soon lose a bonus IIRC (GG).

**Comment by LoneGazebo** [comment]
Intentional.
