### ISSUE TITLE
More empty deal offers

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5789]
_1. Mod version (i.e Date - 4/23):_ Latest

_2. Mod list (if using Vox Populi only, leave blank):_
Archaeology Aesthetic Adjustments
Quick Turns
Calypso's Colored Religious Icons
Faster Aircraft Animations

_3. Error description:_ Received two more empty deal offers, not too far apart from each other, and these ones have no pretense of possible benefits for me.

Furthermore, Austria wouldn't even volunteer 1 GPT in exchange for making peace.

I really think the AI should not be asking for stuff if they have nothing they're willing to part with in exchange.

![Screenshot (20055)](https://user-images.githubusercontent.com/38794241/68080772-6de50680-fdd8-11e9-9a01-949af26f3f28.png)
![Screenshot (20056)](https://user-images.githubusercontent.com/38794241/68080773-6e7d9d00-fdd8-11e9-85a9-cbc8e598426c.png)

**Comment by LoneGazebo** [comment]
I don't see the issue - humans offer the AI 'open' deals all the time- this is a chance for the human to decide terms. Not a problem IMO.

**Comment by HeathcliffWarriors** [comment]
Well, if you observe the second deal, Austria wasn't willing to give me anything at all, so not much I could decide there...

**Comment by LoneGazebo** [comment]
But you could bargain

**Comment by HeathcliffWarriors** [comment]
They value my liberating the City-State at 5 Gold.

1 GPT in exchange is too negative and they refused. The only other thing they could trade was their Horses, which they valued at about 9,000 Gold or so, so that wasn't happening. :)
