### ISSUE TITLE
Upgrading units resets tile visibility

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5794]
_1. Mod version (i.e Date - 4/23):_
10/23

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
As confirmed by Bite in the Mark in the forums, upgrading a unit will reset the visibility status of all tiles.

_4. Steps to reproduce (optional):_
- use a unit to uncover some tiles, such that by the end of its movement it's visibility range doesn't cover all previously seen tiles anymore
- upgrade a unit
- see those tiles outside visibility range, that were visible until end of turn, become invisible again

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi fairly certain this is because revealed tiles are not stored from turn to turn, thus the upgrade creates a new unit with no known data right?

**Comment by ilteroi** [comment]
well the root cause is that an upgrade actually kills the original unit. normally after a kill a visibility update is triggered because that happens on somebody else's turn and you're not supposed to keep the vision until it's your turn again.

**Comment by LoneGazebo** [comment]
Dead units tell no tales.
