### ISSUE TITLE
Move Troops Requests Not Working Properly

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5795]
_1. Mod version (i.e Date - 4/23):_ Latest

ridjack has reported that the option to ask the AI to move their troops from your borders is not showing up consistently for him.

From DiscussionDialog.lua:
```
				-----------------
				-- MOVE TROOPS --
				-----------------
				-- Hostile!
				print("Hello");
				print(tostring(activePlayer:GetMilitaryAggressivePosture(g_iAIPlayer)));
				print(AggressivePostureTypes.AGGRESSIVE_POSTURE_MEDIUM);
				
				if(not pAIPlayer:MoveRequestTooSoon(iActivePlayer)) then
					if(activePlayer:GetMilitaryAggressivePosture(g_iAIPlayer) >= AggressivePostureTypes.AGGRESSIVE_POSTURE_MEDIUM) then
						if(pAIPlayer:GetMajorCivApproach(iActivePlayer) == MAJOR_CIV_APPROACH_HOSTILE) then
							strButton9Text = Locale.ConvertTextKey( "TXT_KEY_DIPLO_DISCUSS_MESSAGE_MOVE_TROOPS_HOSTILE" );
						else
							strButton9Text = Locale.ConvertTextKey( "TXT_KEY_DIPLO_DISCUSS_MESSAGE_MOVE_TROOPS" );
						end
						
						strButton9Tooltip = Locale.ConvertTextKey("TXT_KEY_DIPLO_DISCUSS_MESSAGE_MOVE_TROOPS_TT", strLeaderName);
					end
				end
```
It seems that the requisite is a military aggressive posture on their part of at least MEDIUM (3 units).

He's shown screenshots where there were more than the requisite 3 non-scouting troops on his borders (with troops in their own lands counting as half) and yet the option to request they move their troops didn't show up. https://forums.civfanatics.com/threads/improvement-ideas-move-troops-from-borders-request.651002/page-2#post-15586585

He has not given them Open Borders and they don't have a DoF, both of which cancel the option to make the request.

Any ideas?

**Comment by supermerill** [comment]
from cpp code:

// At war with someone?  Because if this Unit is in the vicinity of another player he's already at war with, don't count this Unit as aggressive

// If the Unit is in the other player's territory, halve its "aggression value," since he may just be defending himself

So if the units are on his border side and not in neutral territory, it needs at least 6 units, and only if it's not at war already with someone else.

**Comment by HeathcliffWarriors** [comment]
Yeah, but in ridjack's screenshot, China is not at war with anyone, they have 3 units near his borders (enough for MEDIUM) plus another five within their own borders but still nearby, which should total 70, just short of AGGRESSIVE_POSTURE_INCREDIBLE.

**Comment by supermerill** [comment]
It only count unit that are no more than 3 plots from a city. So in this picture, 1 in neutral territory in the south (10 points) and one in the east inn  china territory (5 points). As you need 30 points to be aggressive, it's not triggering.

IMO, you can recode
```
bool CvPlot::IsHomeFrontForPlayer(PlayerTypes ePlayer) const
{
	int iRange = GC.getAI_DIPLO_PLOT_RANGE_FROM_CITY_HOME_FRONT();
	int iDistance = GET_PLAYER(ePlayer).GetCityDistanceInEstimatedTurns(this);
	return (iDistance < iRange);
}
```
to also check if the plot is bordering the player territory.

**Comment by HeathcliffWarriors** [comment]
GetCityDistanceInEstimatedTurns doesn't use the plot distance, though? It seems to be checking if they can reach the city within 4 turns, assuming 2 movement. In which case they would all qualify.

**Comment by supermerill** [comment]
GetCityDistanceInEstimatedTurns is a method from a cache that uses:
```
int iDistance = plotDistance(pCityPlot->getX(), pCityPlot->getY(), pPlot->getX(), pPlot->getY());
bool bUpdate = (iDistance < m_vDistance[iPlotIndex]);
```
and plotDistance count the number of hex.

**Comment by HeathcliffWarriors** [comment]
I _see_. Well, that explains it.
