### ISSUE TITLE
Tactical AI lacking aggression

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5796]
https://forums.civfanatics.com/threads/horrible-war-related-ai.651400/#post-15587256

Paging Dr. @ilteroi :)

I suspect it's the IsWantsToConquer flag being too restrictive. Although I do see that you made some changes to both its application in the tactical AI and the strength estimates of other players, so maybe that'll improve things?

**Comment by ilteroi** [comment]
yeah, should be better now

**Comment by ilteroi** [comment]
oops turns out there was another bug. here's a replacement dll for the 8-11 release which fixes it

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3827760/CvGameCore_Expansion2.zip)

**Comment by ilteroi** [comment]
here's the latest build, drop-in replacement for the dll in the 8-11 release

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3854670/CvGameCore_Expansion2.zip)

**Comment by ilteroi** [comment]
okay, another new build. this time installation is a bit more complex, next to the dll there are some database changes. unpack the content of "CoreFiles.zip" into the VP/CommunityPatch folder, overwriting any existing files.

[Core Files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3882263/Core.Files.zip)
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3882264/CvGameCore_Expansion2.zip)
