### ISSUE TITLE
Automatically buys Great Prophets with faith

### ISSUE THREAD

**Issue by random-hero** [LoneGazebo/Community-Patch-DLL#580]
Had an issue today that the automation always buys Great Prophets with faith when "Remind me later" is selected. (Happened twice)

Modlist: CBP Coremods (Germanized) + more lux, Thals unit promotions, RED Modpack

**Comment by LoneGazebo** [comment]
Hmm – sounds like the AI is being naughty again.

**Comment by Radost** [comment]
It always works like this pre-Industrial era.

**Comment by LoneGazebo** [comment]
Ah, yes, if we're talking pre-Industrial, then yeah, 'remind me later' and 'save for prophet' are essentially the same thing.
