### ISSUE TITLE
War icon tool tip blank

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5801]
_1. Mod version (i.e Date - 4/23):_
10/23

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) List Enhancements for VP (v 5)
(ui) Trade Opportunities for VP (v 8.1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v3)
Global - City State Airbases (v 4)
Improved Air Recon (v 1)
Promotion Flags EUI (v 1.2)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Religion Spread (Vox Populi) (v 1.0)

_3. Error description:_ 
For some reason this can't be captured in screen shots, but when mousing over the little war icon in the left lower corner of the leader flag on the right side EUI panel (see screenshot below) there is no working tool tip appearing, but only an empty, small, black box. I think I remember this tool tip showing the war status that is otherwise visible when opening the Leader Screen (peace offer, economy, military, war weariness statuses) in previous versions so it looks like something broke that.

Edit: lol I just noticed that the little black box is actually visible in the screenshot after all, I just didn't notice it there because it's so little 😆 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![war_icon_tool_tip](https://user-images.githubusercontent.com/30495439/68244214-3eb6db00-000c-11ea-86f7-567f4712545e.jpg)

**Comment by HeathcliffWarriors** [comment]
Can confirm this has been the case for a while.

**Comment by azum4roll** [comment]
It just means the war is not neither brokered nor negotiated, or has passed the 15-turn Peace Blocked period.

**Comment by UndeadDevel** [comment]
@azum4roll I don't understand your comment, to be honest. 1) Regardless of what should be shown in that tool tip, displaying an empty tool tip like that is a bug. 2) There is useful information that can be shown independent of wars being brokered, like the war status info (economy, military, war weariness, peace willingness) so that the player doesn't have to enter the leader screen every turn to check those things there.
