### ISSUE TITLE
Desired Luxury tool tip in Trade Screen incorrectly shown

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5803]
_1. Mod version (i.e Date - 4/23):_
10/23

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) List Enhancements for VP (v 5)
(ui) Trade Opportunities for VP (v 8.1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v3)
Global - City State Airbases (v 4)
Improved Air Recon (v 1)
Promotion Flags EUI (v 1.2)
Subs Ignore Borders (v3)
Subs Immune Under Ice (v2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Religion Spread (Vox Populi) (v 1.0)

_3. Error description:_ 
The recently added Luxury sought TT in the Trade Screen (very nice feature btw.) is incorrectly shown if some other event caused the desire to disappear (such as building a Circus, which gives WLTKD for some turns, but maybe also other buildings like Churches or even popping Great Merchants?).

_4. Steps to reproduce (optional):_
- wait for desire to occur
- build Circus in City and see desire disappear
- enter Trade Screen with civ that has Luxury from previous desire and observe tool tip saying that desire is still present

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Unavoidable, the 'resource demanded' is still, well, demanded, even in a WLTKD. It is only when the event ends that a new resource will be expected. I can simply have it check against the city being in WLTKD already.

**Comment by UndeadDevel** [comment]
Yes that would probably be best to avoid confusion and prevent the player from making unnecessary Luxury purchases.
