### ISSUE TITLE
Interface problems

### ISSUE THREAD

**Issue by Lelsn1** [LoneGazebo/Community-Patch-DLL#5805]
_1. Mod version (i.e Date - 4/23):_
 Current version (05/19)

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch only
EUI (compatible version from the folder)

_3. Error description:_ 

Whenever I play a game with the mod enabled, the EUI interface does not work properly.
The civs/city states never appear on the right, and the overview buttons on the top right are missing: 
![20191105111629_1](https://user-images.githubusercontent.com/57405836/68220735-06d97480-ffc7-11e9-840f-51006382b8af.jpg)

When I play without the mod, it works as intended:
![20191105114553_1](https://user-images.githubusercontent.com/57405836/68220785-1bb60800-ffc7-11e9-9bb2-7ac9931c164d.jpg)

Some features of EUI are working normally, like tile improvements when hovering. It's hard to tell how much of the Community Patch is working properly, but I can definitely notice a difference from vanilla when doing trade deals at least.

I've removed and manually reinstalled both the mod and EUI (the compatible version) a couple of times and the issues persisted. First time I forgot to include the files from the EUI compatibilty folder, but even after doing that, nothing has changed. Issue not save related, tried over multiple games

**Comment by MoiMagnus** [comment]
For "Community Patch only" to work with EUI, you need to delete the LUA folder from the Community Patch folder.

For me, just using CP - LUA folder + EUI (the version found on the manual installation repository) works fine. Or at least used to work fine last time I've tried.

**Comment by Lelsn1** [comment]
I was pretty sure I had tried that already, but apparently I didn't. Just did that and it worked perfectly.
Thanks for the help!
