### ISSUE TITLE
Inca's Skirmishers using two movement points on Hills.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#5806]
10/23 version

Mounted ranged units are using an extra movement point on Hills as the Inca. Per @LoneGazebo and @HeathcliffWarriors [here](https://forums.civfanatics.com/threads/new-beta-version-october-23rd-10-23.651049/page-12#post-15589520), this should not be happening.

![image](https://user-images.githubusercontent.com/22875626/68437423-e5c38000-018e-11ea-8d3f-ded1aa128156.png)
![image](https://user-images.githubusercontent.com/22875626/68437428-f07e1500-018e-11ea-83a8-569692ac9e12.png)

**Comment by HeathcliffWarriors** [comment]
That's my assumption, anyway, based on the UA. Also applies for the Iroquois.

**Comment by phantommaxwell** [comment]
I recall someone mentioning that Flood Plains also slow them down.

**Comment by ilteroi** [comment]
you guys crack me up, first inventing new promotions while not considering the interactions between them, then pushing buggy code, now discovering unexpected interactions while simultaneously debating whether to roll back the whole thing.

forgive me if i won't touch this for now.

**Comment by LoneGazebo** [comment]
I didn't say it should or should not happen, I said it's worth looking into. I think it makes sense to have a more granular movement penalty than the vanilla boolean rough penalty.

**Comment by ridjack** [comment]
Apologies, in that case. That was how I read the replies.

Re: "Granular movement penalty," would have to hard disagree, if the Inca and Iroquois' current state are what you mean by that. If the game gave you some immediate feedback as to how many points you were going to use to make a move, I could see an argument for it. But as things are currently, the game only tells me "<1 move;" I get to guess whether I'll be able to attack and move, or be stuck, unless I happen to know the exact interactions on every piece of terrain between me and the target tile.

That sounds torturous.
