### ISSUE TITLE
Resource icon tooltip doesn't preview monopoly boni

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#581]
![res](https://cloud.githubusercontent.com/assets/12978597/9613879/cd4ef362-50f6-11e5-957a-b3991b307a7f.jpg)
Hovering over luxury and strategic resource icons on the map used to show what bonus is associated with getting a monopoly on a that resource until a couple of versions ago (sorry, don't know exactly).
Mods: 
![ress](https://cloud.githubusercontent.com/assets/12978597/9613969/61500d8a-50f7-11e5-8256-e4c12c37b0ec.jpg)

**Comment by LoneGazebo** [comment]
I think that tooltip only occurs with EUI. Using EUI?

**Comment by Edaka** [comment]
Yes. It stopped working before the implementation of the new EUI version, though.

**Comment by LoneGazebo** [comment]
I didn't change that element of EUI (info tooltips for plots), so it is probably a change on EUI's end. You might ask around there.

**Comment by Edaka** [comment]
Oh the UI issues, they always get me! So I might ask, then. Thankfully, it's not a game breaking issue. Thanks for the help anyway!

**Comment by LoneGazebo** [comment]
Yep!
