### ISSUE TITLE
Terracota Army still providing old bonus

### ISSUE THREAD

**Issue by Guynemer** [LoneGazebo/Community-Patch-DLL#5818]
_1. Mod version (i.e Date - 4/23):_Nov 8

_2. Mod list (if using Vox Populi only, leave blank):_3/4 UC, Dan's various civs for 3/4 UC, Dan's building changes and China/Spain rebalance

_3. Error description:_ TCA is still providing the extra copies of units, in addition to culture when winning a battle 

---

**Comment by ASCII-Guy** [comment]
I have put a pull request #5819 to fix this issue.
