### ISSUE TITLE
Great Diplomats have 6 movement points by default

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#582]
I might be making a noob out of myself in case I'm not informed that it's intended, though, but I took the liberty of assuming that it isn't.

**Comment by LoneGazebo** [comment]
That's be design. Movement forever!

**Comment by Edaka** [comment]
Ah, sorry then. I was a little surprised when I first noticed it, because Great Merchants have to travel to city-states, too (although not necessarily), but they only have 2 movement points.
Anyway, here's probably not the place to discuss balance, so this case should be a closed case (at least for now).

**Comment by LoneGazebo** [comment]
It is because GD have to travel to CSs, whereas Merchants can choose to.

**Comment by Edaka** [comment]
Yeah, I figured that would make sense (:
