### ISSUE TITLE
Barbarians only spawn Zeppelins

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5824]
_1. Mod version (i.e Date - 4/23):_11-8

At certain point barb camps start spawning exclusively Zeppelins. There has been three consecutive camps that spawned outside my borders and all of them spawned nothing else than Zeppelins.

![20191111162759_1](https://user-images.githubusercontent.com/16341598/68603733-909aad80-04b1-11ea-969f-1019c2306904.jpg)

**Comment by ilteroi** [comment]
turns out there is no randomness involved here, they simply choose the "best" unit type according to some arbitrary scoring function ...

**Comment by ilteroi** [comment]
now we randomly choose from the top 3 options
