### ISSUE TITLE
10/29 - Stealth Bombers can't dock on carrier...except by upgrades

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5825]
_1. Mod version (i.e Date - 4/23):_
10/29

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Stealth bombers cannot be reposition onto aircraft carriers. If that is intended (and if it is the tooltip needs to be updated), than there is a hack. If you send a carrier with bombers into a city, and upgrade them to stealth bombers, and then leave the city, the stealth bombers will go with the carrier.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ryanmusante** [comment]
But than after they leave the carrier upgraded, they cannot reposition onto the same carrier?

**Comment by bigcat88** [comment]
Cant. It is always was like this, but I always ask to let stealth bombers be stationed on carriers official.

**Comment by ryanmusante** [comment]
That or make it where heavy bombers don't go obsolete.

**Comment by Stalker012345** [comment]
Personally I would let Stealth bombers talk on carriers, or hugely increase their range (modern stealth bombers can hit most places in the world). I know its a little bit against flavor but otherwise what's the point, as in many continents maps you have to bring your carrier force to the enemy anyway, so late game you will be using crappy bombers against an enemy that does have stealth bombers.

I can also say in that same game I got to try out Stealth Bombers against a destroyer heavy (not even missile cruiser) fleet for the first time, and I was surprised how well the destroyers did. The stealth bombers took a lot of damage, and quickly had to retreat. I don't think it would be OP to allow.
