### ISSUE TITLE
City Strength of liberated City-States is too low in later eras

### ISSUE THREAD

**Issue by Omen-of-Peace** [LoneGazebo/Community-Patch-DLL#5826]
_1. Mod version (i.e Date - 4/23):_ 10/23

_2. Mod list (if using Vox Populi only, leave blank):_ only UI mods

_3. Error description:_ even in later eras, a liberated City-State has a very low City Strength (12) in a case I observed in the last October beta, which makes it extremely vulnerable to pretty much any late-game unit.
The City-State should either get a bonus to City Strength scaling with era, or be automatically granted one unit upon liberation.

Note: I thought about gifting a unit to the CS right away, but even if it's on its territory it won't get it to the city before each player has had at least 1 turn to play.

**Comment by Stalker012345** [comment]
+1 on the instant unit idea. I too have the problem of getting into old tug of war with the AI, where we just take the city back and forth, back and forth.

**Comment by ilteroi** [comment]
it's done
