### ISSUE TITLE
Cities without airport can accomodate more than 2 aircraft

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5827]
_1. Mod version (i.e Date - 4/23):_11-8 and earlier versions

 A presume this is a bug and not my misunderstanding of current game mechanics.

A city without airport doesn't allow building aircraft if the amount of stationed aircraft in this city is already two (as supposed to be). But you can rebase as many as eight (maybe more) aircraft to this city from other places.

![20191112043833_1](https://user-images.githubusercontent.com/16341598/68637317-ea799280-0506-11ea-978e-6b1bfa435e62.jpg)

It should be noted that rebasing the aircraft in this case is only possible by simple right-clicking on the destination city, but it doesn't work by pressing the Rebase button.

**Comment by LoneGazebo** [comment]
@ilteroi this seems like a weird quirk with unit missions, no?
