### ISSUE TITLE
DoW triggered by atomic bomb

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5828]
_1. Mod version (i.e Date - 4/23):_latest

Not sure if intended, but I will report just in case. Doesn't seem to make sense anyway.

I'm at war with Denmark (they declared). They are in Defensive Pact with America and Polynesia (or signed it later during the war, I didn't notice. The point is that I'm not at war with America and Polynesia). 
At some point I decide to drop an Atomic Bomb on a Denmark's city. The bombing triggers declaration of war from America and Polynesia at the same moment. 
There were no units of America or Polynesia in the blast radius, hence collateral damage is not the case.

Intended or bug?

EDIT: 
Apparently caused by an empty Austrian water tile getting caught by the blast radius, which causes a war with Austria and her allies. See further postings.

**Comment by HeathcliffWarriors** [comment]
My assumption is that the game auto-DoWs any enemies in the blast range, even if already at war, and this triggers the DP, so likely a bug.

**Comment by ilteroi** [comment]
![8f7ae07e-bc9d-419d-9ef8-162834473ed9](https://user-images.githubusercontent.com/1358966/68683268-67842680-055e-11ea-85b0-447bcc584751.jpg)

**Comment by bigcat88** [comment]
Maybe there was a caravan?

**Comment by saamohod** [comment]
> 
> 
> Maybe there was a caravan?

I checked for any units. There were only Danish ones. 



> 
> 
> ![8f7ae07e-bc9d-419d-9ef8-162834473ed9](https://user-images.githubusercontent.com/1358966/68683268-67842680-055e-11ea-85b0-447bcc584751.jpg)

What's more is that when I tried to nuke him ~5 turns later it didn't trigger the war with his friends.

**Comment by saamohod** [comment]
Here is the strike that would trigger the war. No units except the Danish ones are seen in the blast radius.

The only suspect is the empty water tile belonging to Austria to the North-West of Klagenfurt. Since Austria is in DP with America it's the most likely cause.

![20191113060148_1](https://user-images.githubusercontent.com/16341598/68732412-f420fa00-05db-11ea-9c59-de1a62f9e4fd.jpg)

![20191113060156_1](https://user-images.githubusercontent.com/16341598/68732401-ecf9ec00-05db-11ea-8eee-15d95567f532.jpg)

**Comment by LoneGazebo** [comment]
I’m betting that we don’t check for ‘if already at war, then declare war.’

**Comment by saamohod** [comment]
I've done some more testing. It happens because of that water tile belonging to Austria which gets caught in the blast radius. This is what causes her defensive allies America ans Polynesia to declare on me.

**Comment by LoneGazebo** [comment]
@saamohod that's the correct reason. Not a bug.
