### ISSUE TITLE
Stupa description/effect mismatch

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#583]
![resss](https://cloud.githubusercontent.com/assets/12978597/9615087/c0584804-50fe-11e5-85b3-6a3418b62f76.jpg)
The description mentions 2 tourism, while the effect is 3 tourism (the EUI tooltip also mentions 3 tourism, as it can be seen).

Praying this is actually a real issue this time.

**Comment by LoneGazebo** [comment]
It is! +1 Bug Hunter Points to you!
G

**Comment by Edaka** [comment]
Hooray!
