### ISSUE TITLE
Local Unhappiness Not Displaying in City Screen

### ISSUE THREAD

**Issue by usadefcon1** [LoneGazebo/Community-Patch-DLL#5836]
_1. Mod version: 11/8

_2. Mod list: 
UI - Improved City View (Vox Populi EUI)

_3. Error description:
Mouse-over in City Screen does not show reasons for unhappiness except if the unhappiness level is at 0.

![Screenshot (1)](https://user-images.githubusercontent.com/57153924/68915380-d06ec880-072f-11ea-99a6-63f79756c7b1.jpg)

![Screenshot (2)](https://user-images.githubusercontent.com/57153924/68915383-d49ae600-072f-11ea-9c19-a39719ad9428.jpg)

![Screenshot (3)](https://user-images.githubusercontent.com/57153924/68915385-d795d680-072f-11ea-9fe5-56aeffcb38b3.jpg)

**Comment by LoneGazebo** [comment]
There's a hotfix for that UI mod you're using somewhere... might ask on the forum. In any case that UI mod is to blame.

**Comment by Aqinu** [comment]
I have this version without any issues (provided by @LoneGazebo):
[UI - Improved City View (Vox Populi EUI) (v 11.0).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3854050/UI.-.Improved.City.View.Vox.Populi.EUI.v.11.0.zip)
