### ISSUE TITLE
How to install Visual Studio?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5837]
So I realize this is going to be painstaking to figure out how to do, but better start somewhere :)

I'm attempting to install Visual Studio in order to be able to contribute more and debug my own changes.

I was able to successfully download the trial version of VS 2019; when I attempted to download VS 2008 C++ Express from Microsoft, there was no download link available. Attempting to open any of the repository files results in an error message, since I don't have the VS 2008 tools.

Furthermore, it seems to only offer a trial version, not any free tool I can use.

How do I get around this or install the correct toolset?

The IDE may be my friend, but it's a very uncooperative friend.

**Comment by ilteroi** [comment]
https://go.microsoft.com/fwlink/?LinkId=104679 should work for vs2008

also you don't need the full version of 2019, community will do fine

**Comment by HeathcliffWarriors** [comment]
```C:\Users\Admin\source\repos\Community-Patch-DLL\CvGameCoreDLL_Expansion2\VoxPopuli.vcxproj : warning  : The build tools for Visual Studio 2008 (v90) cannot be found. To build using the Visual Studio 2019 (v142) build tools, either click the Project menu or right-click the solution, and then select "Retarget Solution". Install Visual Studio 2008 (v90) to build using the Visual Studio 2008 (v90) build tools.```

Okay, so I installed VS 2008 Express using the download link you provided. 

The error message above is from trying to open the sln file from VS 2019 - trying "retarget project/retarget solution" does not display the VS 2008 build tools as an option - and I can't find a link to actually run VS 2008.

How do I proceed?

**Comment by ilteroi** [comment]
order is important ... did you install 2008 first?

**Comment by HeathcliffWarriors** [comment]
@ilteroi VS 2019 was installed first, since I couldn't figure out how to install VS 2008. Should I uninstall both of them and reinstall 2008?

**Comment by ASCII-Guy** [comment]
I'm also installing the IDE.  I want to help out the project more.

**Comment by ASCII-Guy** [comment]
@HeathcliffWarriors This forum post may help you. https://forums.civfanatics.com/threads/building-a-dll-based-mod-in-2019.645887/

**Comment by ASCII-Guy** [comment]
I've been doing this myself and it's a pain in the ass. Even these steps didn't work properly. VS Studio 2008 had to have SP1 as well to work properly. Even then I'm not confident.

**Comment by ilteroi** [comment]
@HeathcliffWarriors : yes you should start from scratch
@ASCII-Guy : what exactly doesn't work for you? i don't remember the setup being so complicated ...

**Comment by ASCII-Guy** [comment]
@ilteroi I am having no issues after the recent pull requests were merged. Had a successful DLL build.
