### ISSUE TITLE
Cavalry doesn't get obsolete at Combustion

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#584]

**Comment by LoneGazebo** [comment]
It isn't supposed to (that way if you can't build tanks you can still build a mobile unit.

**Comment by Radost** [comment]
It's a moot point, as Tanks require a different resource too, but obsolete landships just fine.

**Comment by LoneGazebo** [comment]
It's an issue of pace - cavalry comes very quickly before landships.
