### ISSUE TITLE
Air interception seems bugged

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#5841]
_1. Mod version (i.e Date - 4/23):_11-8

It looks like something is wrong with air combat, namely interception. 

I keep seeing animation when my bombers are getting intercepted by enemy fighters, but no interception message pops up on top of the screen nor does it seem that any additional damage to my bombers is done (the damage level they end up with is consistent with pre-battle odds prediction).

The same thing is observed when a guided missile gets intercepted by a destroyer. The animation shows the interception, but no message (and probably no damage to the missile).

**Comment by ilteroi** [comment]
damage calculation is correct as far as i can tell but there is a problem with the database, eg TXT_KEY_MISC_YOU_ATTACK_BY_AIR_INTERCEPTED is not found ...
