### ISSUE TITLE
please push all your changes

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5842]
hey all,

i'm back ... apparently there's a demand for a new build? i could do it but i don't see substantial changes. 

especially @HeathcliffWarriors : please push what you have

**Comment by HeathcliffWarriors** [comment]
@ilteroi I'm not a collaborator, so I can't merge changes directly, but all my changes are in my pull request. The only thing needing replacement at the moment is the DLL.

There were complaints about the diplo AI being too passive and unwilling to initiate wars, so I changed it to be (hopefully) substantially more aggressive/opportunistic, and made some other improvements - I and some others on the forums would be eager to test out the changes and see if AI aggression is at a desirable level with those changes, or if it needs further tweaking.

Code should be already debugged for things like syntax errors etc, and once I figure out VS I'll eventually be able to do that on my own. :)

Thanks for your help!

**Comment by ilteroi** [comment]
ah, got it, didn't see the PR

**Comment by HeathcliffWarriors** [comment]
No problem, thanks a lot :)

Will you post the new DLL here or on the forums?
