### ISSUE TITLE
Barbarians spawn Great Merchants

### ISSUE THREAD

**Issue by ChickenFighter** [LoneGazebo/Community-Patch-DLL#5845]
_1. Mod version (i.e Date - 4/23):_
11-8 (with [this](https://forums.civfanatics.com/threads/new-beta-version-november-8th.651590/page-10#post-15596646) .dll)

_2. Mod list (if using Vox Populi only, leave blank):_
(over) More Unique Components for VP (v 53)
(text) Promotion Overhaul for VP (v 15)
(ui) List Enhancements for VP (v 5)
(ui) Trade Opportunities for VP (v 8.1)
Enhanced Naval Warfare for Vox Populi (v 1.6.08)
pdansBuildingTweaks(V2)
Promotion Flags EUI (v 1)
Provincial Palace (v 3)
UI - City Production (v 15)
UI - Destination (v 4)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 1.0)
UI - Small Resource Icons (v 4)

_3. Error description:_ 
Barb camps started to spawn Great Merchants. They idle in their camps until it gets destroyed.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional): 

![8930_screenshots_20191117094616_1](https://user-images.githubusercontent.com/1348405/69005385-cb716b00-0921-11ea-815c-470a2e4fb1f3.jpg)

**Comment by HeathcliffWarriors** [comment]
The fact that the GM is spawning non-embarked in the water just raises _further_ questions!

**Comment by ilteroi** [comment]
it's fixed, this happened when the barbarians are not yet allowed to have boats

**Comment by ASCII-Guy** [comment]
To get the fix, update your DLL.

**Comment by randomnublet** [comment]
![civbug4](https://user-images.githubusercontent.com/53142313/69033554-7eec6500-09df-11ea-91ab-483a1230f68a.png)

Another issue with barbarians after you fixed the GM spawning, happened twice in the early game already: barbarian camps spawn empty, and I'm sure nobody cleared them (I'm the only player around, no cs, the area where the camp is was patroled by one of my units 2 turns before so it spawned right now...)
