### ISSUE TITLE
Text Bug : 'Gold per turn' tooltip

### ISSUE THREAD

**Issue by Farcear** [LoneGazebo/Community-Patch-DLL#5847]
_1. Mod version (i.e Date - 4/23):_
11/8 (with updated DLL from 11/16)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In the diplomacy screen, when I mouse over the "gold per turn" box, it looks like it is giving the tooltip for the "gold" box. The AI obviously does have gold per turn to trade (and the trade worked fine) so this is just a text issue.

_4. Steps to reproduce (optional):_
[Civ V - Turn 100 - GPT Text Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3855846/Civ.V.-.Turn.100.-.GPT.Text.Bug.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
See answer #5705
