### ISSUE TITLE
Great General Combat Bonus 

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#585]
It would seem that the Great General Combat Bonus has somewhere broken for Barbarians. I discovered that units do not receive any bonus when near to (or next to, or on top of) a Great General and a Barbarian, but it works fine when near to a regular enemy. 

I was using quite an old version (15th August), but updated to the current (1st Sept.), and I disabled all other mods to be certain. Perhaps it's a feature of CBP that seeped into the CP unintentionally?

**Comment by LoneGazebo** [comment]
The bonus isn't applying versus barbs? That just sounds like a plain ol' bug. I know ilteroi made some caching changes to that function to reduce performance impact. I'll forward this to him.

**Comment by ilteroi** [comment]
cannot confirm this - for me it works.

also: what is your expectation, i don't quite understand the "seeping into CP" part ...

**Comment by JFDaly** [comment]
I merely ask whether it was a feature of the CBP which was accidentally on for the CP. It wasn't an expectation, merely a possibility I found plausable.

A screenshot of the issue: http://imgur.com/a/46FQg

**Comment by LoneGazebo** [comment]
What turn was the unit spawned? Also, was it spawned with IGE/Firetuner, or naturally? The way the caching works, it needs a turn to 'cache' the value before it works (unless it is spawned naturally, at which point the cache is updated).

**Comment by JFDaly** [comment]
It was spawned turn 0, and via the Honor policy (which I gained through culture, not IGE). However, on trying to spawn a GG on turn 1 (via regular combat, via policy, or by IGE), the issue seems to be gone. It would be perhaps impossible to test via regular combat on turn 1, so I suppose this is an anomaly of little import.

**Comment by LoneGazebo** [comment]
I think it's that, then - the cache simply isn't 'alive' yet at turn 0.

G

**Comment by JFDaly** [comment]
Seems so. Thanks for taking a look anyway.
