### ISSUE TITLE
Barbarian camps spawning empty

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#5852]
![civbug4](https://user-images.githubusercontent.com/53142313/69033554-7eec6500-09df-11ea-91ab-483a1230f68a.png)

Another issue with barbarians after you fixed the GM spawning, happened twice in the early game already: barbarian camps spawn empty, and I'm sure nobody cleared them (I'm the only player around, no cs, the area where the camp is was patroled by one of my units 2 turns before so it spawned right now...)

_Originally posted by @randomnublet in https://github.com/LoneGazebo/Community-Patch-DLL/issues/5845#issuecomment-554893752_

**Comment by randomnublet** [comment]
I should have posted this as standalone instead of replying to an ''already fixed'' bug report

**Comment by ChickenFighter** [comment]
Can confirm, I have the same issue. All freshly spawned camps spawn empty.

![8930_screenshots_20191119154436_1](https://user-images.githubusercontent.com/1348405/69156557-e1c72480-0ae3-11ea-85e7-714ae09ba6c3.jpg)

**Comment by ilteroi** [comment]
can't reproduce. any other active mods?

![image](https://user-images.githubusercontent.com/1358966/69176067-49419c00-0b05-11ea-9002-ec4fbe8ef2a4.png)

**Comment by ChickenFighter** [comment]
I'm using these:
(over) More Unique Components for VP (v 53)
(text) Promotion Overhaul for VP (v 15)
(ui) List Enhancements for VP (v 5)
(ui) Trade Opportunities for VP (v 8.1)
Enhanced Naval Warfare for Vox Populi (v 1.6.08)
pdansBuildingTweaks(V2)
Promotion Flags EUI (v 1)
Provincial Palace (v 3)
UI - City Production (v 15)
UI - Destination (v 4)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 1.0)
UI - Small Resource Icons (v 4)

Mostly UI changes, none of them touch barbs in any way. Didn't experience this with the "original" 11-8 .dll, just the updated one. When I start a game the first few barb camps spawn just fine, but as the game continues more and more barb camps spawn empty. Haven't really found a reliable way to reproduce this properly though.
