### ISSUE TITLE
Issues with #5853

### ISSUE THREAD

**Issue by ASCII-Guy** [LoneGazebo/Community-Patch-DLL#5854]
@HeathcliffWarriors

There are minor errors in #5853.

1. Line 16888 of CvDiplomacyAI.cpp:
"eLoopPlayer" identifier is undefined. I assume you meant to use "ePlayer" instead.

2. Line 4734 of CvDiplomacyAI.cpp:
"isPlayerDPwithAnyFriend" identifier not found. You forgot to capitalize "with" in the Boolean.

Thanks for all your hard work!

**Comment by ASCII-Guy** [comment]
I have fixed the bugs myself.

**Comment by HeathcliffWarriors** [comment]
@ASCII-Guy Already noticed the first one before seeing this, will fix the second. Thank you :)

**Comment by LoneGazebo** [comment]
Beware the IDEs of March.
