### ISSUE TITLE
Exceptionally long trade routes in the early game

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#5857]
_1. Mod version (i.e Date - 4/23):_
November 8th

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I've been noticing lately that some trade routes as early as in the ancient era seem to be able to go too far. I've particularly noticed that rough terrain doesn't make a difference.

Here's a screenshot where I apparently can send a caravan from Casablanca to Tharros. Notice how it's a distance of about 14 tiles with some jungle and a river on the way. The trade route overview shows the maximum range of 10 tiles and indicates that the range of this particular trade route is 4 tiles. It just doesn't add up, but that may be because there was already a road between the cities.

![Inked20191118123407_1_LI](https://user-images.githubusercontent.com/12978597/69145586-a6722900-0ad6-11ea-9c74-5b517e0874dc.jpg)

![Inked20191118125919_1_LI](https://user-images.githubusercontent.com/12978597/69145591-a96d1980-0ad6-11ea-85ce-a5708d176e51.jpg)

Here's another from later on in the game. I'm able to send caravans to both Ur and Zurich from both Tetouan and Casablanca (offscreen, it's in the lower left corner). These just seem too long for such a rough terrain. Also, no roads here.

![InkedInked20191118125929_1_LI](https://user-images.githubusercontent.com/12978597/69145664-d4f00400-0ad6-11ea-9c51-78a9cda784a7.jpg)

![InkedInked20191118125919_1_LIs](https://user-images.githubusercontent.com/12978597/69145671-da4d4e80-0ad6-11ea-8e04-a7c7d9a77e2b.jpg)

Another example. Fired up the game with pure VP and UI mods. Notice how it shows 10 range from assur to belgrade, while the caravan itself is about to go on a route that's actually 12 tiles, many of which are rough terrain. 
![20191119143858_1](https://user-images.githubusercontent.com/12978597/69147466-affd9000-0ada-11ea-8e61-2c7276d6a940.jpg)

And here we see range 8, which is technically correct, but there's also a lot of rough terrain inbetween that doesn't seem to be calculated in.
![20191119143911_1](https://user-images.githubusercontent.com/12978597/69147510-c9064100-0ada-11ea-8033-29137b33e800.jpg)

Has anybody else been experiencing this?

**Comment by LoneGazebo** [comment]
@ilteroi is the path-finder

**Comment by ilteroi** [comment]
i don't think there's a pathfinder issue here ... if you think the routes are too long, reduce the maximum range.

note that moving along a river is cheaper than normal even if the tiles themselves are rough terrain.

**Comment by Edaka** [comment]
Oh, cool, didn't know that about rivers. Has it always been like that? In that case, I can see how rivers + roads can combine to create super cheap movement.

Still, the trade routes in my screenshots seem excessively long to me, at least for the ancient era. Bear in mind that there isn't even a caravansary in the city. Kind of makes those bonuses to trade route range feel less consequential. Or perhaps it's just a map quirk, then?

**Comment by Edaka** [comment]
![20191124220951_1](https://user-images.githubusercontent.com/12978597/69500855-b1c6b980-0f07-11ea-9220-e588303a53b0.jpg)

The Sukhotai - Vientiane route is apparently a distance 4 one, while the actual tile count is about 15. The Sukhotai - Taphan Hin route is a distance 5 one, the tile count is about 20. It seems that both roads and rivers in combination make for some ridiculous movement discounts. Shouldn't rivers be ignored if roads are already in place? I mean, how exactly are caravans using both at the same time? It looks weird when the game considers that the suggested route is actually faster than this:

![Inked20191124220951_1_LI](https://user-images.githubusercontent.com/12978597/69500963-d1121680-0f08-11ea-983b-3814ad1873de.jpg)

For comparison, the Sukhotai - Loci route is a distance 6 one. This seems more reasonable, but notice that there's no road. 

![20191124220954_1](https://user-images.githubusercontent.com/12978597/69500856-b2f7e680-0f07-11ea-97b9-91f1061f5908.jpg)

**Comment by ilteroi** [comment]
moving along a road costs 1/4, along a river costs 1/2, rough plots cost 3/2

the math works, what exactly would you like to change?

**Comment by Edaka** [comment]
Ah, so ist's just the roads, then. Sorry, I didn't know how much of an impact roads made, so I assumed something was wrong. Thanks for clarifying.

**Comment by ilteroi** [comment]
i've made an adjustment, roads is now 1/3 and railroad 1/4
