### ISSUE TITLE
Goddy Hut Upgrades

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#586]
According to Leftover Units.xml in CBP, Sipahi and Hakkapelitta would upgrade to Anti Tank Guns if they pick up the upgrade.

**Comment by LoneGazebo** [comment]
I think this is fixed in the SQL after it, is it not?

**Comment by LoneGazebo** [comment]
If not, I'll check (references to the anti-tank gun would break the database.xml, IIRC).
