### ISSUE TITLE
Build Errors #5861

### ISSUE THREAD

**Issue by ASCII-Guy** [LoneGazebo/Community-Patch-DLL#5863]
![Errors](https://user-images.githubusercontent.com/14044545/69298517-f9290f00-0bc2-11ea-83ce-a06fff0649e1.PNG)

@HeathcliffWarriors if you need any help with the IDE I installed it on Saturday.

**Comment by HeathcliffWarriors** [comment]
@ASCII-Guy Heh, thanks :)

My intention is to set up the IDE before my next pull request to prevent such issues in the future, now that all the major diplo changes are made.

**Comment by LoneGazebo** [comment]
I just fixed those locally as well. The IDE is your friend! :)

**Comment by LoneGazebo** [comment]
Honestly I'm impressed you haven't had more build errors, I can't fathom trying to write code without an IDE.

**Comment by LoneGazebo** [comment]
You might even say I have no IDEa how you do it...

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Grrrr, I will get you for that 😝
