### ISSUE TITLE
useless navy

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5864]
![image](https://user-images.githubusercontent.com/1358966/69315144-24991180-0c36-11ea-9927-3bba2b067597.png)

AI shouldn't be building more than 1 naval unit per 6 water plots (AI_CONFIG_MILITARY_TILES_PER_SHIP) ... how can this happen?

**Comment by HeathcliffWarriors** [comment]
The French are at last giving the English a run for their money!

**Comment by supermerill** [comment]
Can't they use the almaty fort?

**Comment by HeathcliffWarriors** [comment]
There's also one of their ships stationed in the Manila fort, so it seems they're using the canal.

**Comment by ilteroi** [comment]
oh i missed that. so maybe they just moved into that area
