### ISSUE TITLE
Pioneer cost calculation

### ISSUE THREAD

**Issue by 4CV** [LoneGazebo/Community-Patch-DLL#5869]
_1. Mod version (i.e Date - 4/23):_latest beta Nov 8th

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Calculation for pioneer and colonist seems to be mixed up. (Pioneers cost more than colonists two eras later?)
![pioneer](https://user-images.githubusercontent.com/25335477/69386264-6374a900-0cc2-11ea-8ed9-32e61436edf1.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by corona88** [comment]
Capital city is problem.
settlers/pioneer/colonist cost is 106 (standard speed), after i build capital cost for settler and colonist is 114 (which should be ok), but cost for pioneer is 228.

Maybe should have different scaling for different map size, is not same have 20 city on standard maps and on huge

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo This seems to have gone unaddressed in the latest versions.
