### ISSUE TITLE
no influence from returning worker to city state

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#587]
i captured a worker from the barbarians but got no influence for returning it

**Comment by AnastaseAlex** [comment]
Were you at war with the city-state?
Was the worker initially owned by that city-state?
Could it be owned by a civ you are at war or a civ or city-state you have not yet met?

**Comment by LoneGazebo** [comment]
Not sure - can you provide specifics?

**Comment by ilteroi** [comment]
so nobody did any changes around that function recently?

i'll try to reproduce ... i had met the citystate before, the worker was apparently theirs originally (else why would the game ask me to return it to them) and we were not at war.

**Comment by LoneGazebo** [comment]
No, I haven't. You can find the function in docivilianreturnedlogic()
