### ISSUE TITLE
capturing a settler

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5872]
the aztecs just captured a barbarian (ex-inca) settler and got a settler (not a worker)

![image](https://user-images.githubusercontent.com/1358966/69460308-18b36980-0d74-11ea-966c-9b3872f1560b.png)

is that supposed to happen? also the prisoner of war promotion seems strange ...

**Comment by HeathcliffWarriors** [comment]
Pretty sure that's not intended behavior.

**Comment by supermerill** [comment]
seems like it's GLOBAL_GRATEFUL_SETTLERS
This switch isn't used anywhere, but all other that depends on it are, so i seems like someone may have removed it (i don't know when) unintentionally.
