### ISSUE TITLE
Is it possible for units gifted to City-States to keep their promotions?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5875]
I've always found it annoying that you have to physically march units into City-State territory to have them keep their promotions.

Clearly the game is able to keep track of what unit type you sent, so is it a huge challenge to keep track of the promotions too, or is it a design choice?

Logically speaking, it doesn't make a lot of sense for units professionally trained in a major civ's territory to mysteriously lose all of their combat experience during their offscreen journey to the City-State's lands, but keep it if they were directly marched there by the player.

If it's for balance reasons, I'd argue the delay for several turns and the ability to only send one at a time is sufficient to prevent it from becoming overpowered, especially when you consider #5876

**Comment by 4CV** [comment]
If they could at least keep such like 'Himeji Castle' or 'Morale' should help a lot

**Comment by LoneGazebo** [comment]
No, because they're new units and the promotions are tied to player attributes and values, not CS ones.
