### ISSUE TITLE
City-States not defending themselves

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5876]
_1. Mod version (i.e Date - 4/23):_ Latest

According to people in the thread for the latest beta, City-States at war with a player will tend to send their units over there to invade them, and neglect their own defense, rendering them easily capturable.

My understanding is that this is because they now use the normal tactical AI, but City-States aren't exactly meant to be powerhouses, plus there's a cooldown on gifting units and a cap on how many units City-States can have, so it will be difficult for players to protect their City-State allies.

**Comment by ilteroi** [comment]
yeah, maybe that wasn't the best idea, i've disabled operations for minors again

**Comment by HeathcliffWarriors** [comment]
I don't think it's entirely a bad idea - I recall an earlier changelog for VP that said "City-States now have an independent function to search for and deliver appropriate attack targets near them" or something to that effect.

But they should be defending themselves. :)
