### ISSUE TITLE
Negative Tech Costs

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#5878]
As reported in the forums (https://forums.civfanatics.com/threads/negative-science-requirements-in-atomic-era.599403/ ), tech costs can go to the negatives.

I think the int data type can store from -2,147,483,648 to 2,147,483,647.

Inside the dll, research progress and cost for each tech seems to be stored in the hundreds, then percent modifiers are applied to this number as an integer (eg 25 for 25%, rather than 0.25 if you're doing math by hand), then the resulting number divided by 100.

So, that means our actual maximum tech cost will be 2,147,483,647 / 10,000 = 214,748, which is consistent with the ~210,000 max cost reported in the thread.

I am able to force an issue by modding a tech cost of some tech (Pottery in my case) to a very high number, eg 300,000. The tech cost displays correctly, however when using the ChangeResearchProgress lua method, you can obtain the tech even when you don't expect it.

For example, tech cost is shown to be 600,000. I add 100,000 research to that tech, and the game then grants me the tech. (not sure why this bug is happening somewhere below 100,000 and not ~210,000)

I think I can fix this by using the long long data type. However, I am unsure of the impact to memory usage. Worth considering replacing arrays with map containers?

I'll be posting a pull request shortly, then you can inspect to see if this is a fix we want to use.

**Comment by ilteroi** [comment]
i'm not so sure this solves the issue, the lua interface is still only 32bit wide. and so we now get a bunch of "cast losing data" warnings.

also i think that 32 bit should be plenty, we just need to be a bit smarter when applying modifiers.

**Comment by HungryForFood** [comment]
Modifiers to tech cost are applied within the DLL, lua only fetches the final result. Without having to apply modifiers, that's 2 more digits which can be used.

I think lua does not keep track of tech costs and research progress in times 100, so that's another 2 more digits possibly.

The only modifiers which increase the tech cost are game speed and number of cities, those have fairly large balance impacts.

Is the cast losing data error happening now? I can make the lua hook itself return an int rather than a long long, which should stop the error from showing.

**Comment by ilteroi** [comment]
it's relatively easy to apply modifiers without multiplying by 100, so that is the easiest solution imho. check out how it's done in ole branch
