### ISSUE TITLE
Inability to Raze Cities or Disband Units

### ISSUE THREAD

**Issue by theunholypotato** [LoneGazebo/Community-Patch-DLL#588]
I believe that someone has already reported an error of this type. However, I wanted to provide my own 2 cents. I am currently playing America (again, as they seem good at provoking bugs), and I've found that I can neither raze cities nor delete units (most notably captured missionaries).

I'm running with the full CBP+Diplo+EUI+E&D package, plus reforestation and RED graphics. I can provide a saved game or specific log types if either would help provide insight.

**Comment by LoneGazebo** [comment]
lua.log would be useful.

**Comment by theunholypotato** [comment]
Gazebo, I provided an example lua.log on p. 144 of the bugfix thread.

**Comment by LoneGazebo** [comment]
I can't reproduce the bug, sorry.
