### ISSUE TITLE
Question re: creating new text keys for leader dialogue

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5884]
So when it comes to leader dialogue, if I wanted to add more variety to the leader dialogue, my current understanding is that this is what I'd have to do:

Existing dialogue:
```
		<Row Tag="TXT_KEY_GENERIC_GREETING_POLITE_HELLO_5">
			<Text>Hail, friend. What can I do for you?</Text>
		</Row>
		<Row Tag="TXT_KEY_GENERIC_GREETING_POLITE_HELLO_6">
			<Text>Speak, friend, and enter...my throne room.</Text>
		</Row>
		<Row Tag="TXT_KEY_GENERIC_GREETING_POLITE_HELLO_7">
			<Text>Greetings and salutations, fellow ruler!</Text>
		</Row>
		<Row Tag="TXT_KEY_GENERIC_GREETING_POLITE_HELLO_8">
			<Text>Welcome, friend. Shall I prepare a feast to mark this occasion?</Text>
		</Row>
```
New dialogue (number +1):
```
		<Row Tag="TXT_KEY_GENERIC_GREETING_POLITE_HELLO_9">
			<Text>Lorem ipsum docet!</Text>
		</Row>
```

Do I simply follow this process for every type of text key, and does doing so have any negative impact on memory or performance?

e.g. If I were to add 500 new dialogue messages, would it change anything?

**Comment by Aqinu** [comment]
Take a look at this mod:
https://forums.civfanatics.com/threads/diplomacy-extended.647933/

**Comment by HeathcliffWarriors** [comment]
I've seen it, that's why I'm asking this question to confirm all the details. :)

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Any thoughts on this? It wasn't answered.

**Comment by LoneGazebo** [comment]
Yes that is what you do, and yes additional text is loaded into memory. So if you do it, it would need to be a modmod.

**Comment by HeathcliffWarriors** [comment]
How substantial is the impact on memory?

**Comment by HeathcliffWarriors** [comment]
So if it was, say, 500 extra entries, would that be substantial enough to cause issues, if I was only using VP?

I'm not sure how much memory text uses :)

**Comment by LoneGazebo** [comment]
Length, diacritics, etc. all add to cost. 43 civ VP is where the issues would crop up.

**Comment by HeathcliffWarriors** [comment]
Ah, makes sense. Thanks for the help!

If only it was possible to make a 64 bit exe, then we wouldn't have all these memory issues...

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo
 I've thought of a new idea. Text consumes memory, but the actual text key format (i.e. TXT_KEY_GENERIC_GREETING_POLITE_HELLO_X) obviously has a much smaller consumption.

While the cost may be high in terms of memory, the cost of text storage in a text file is pretty low, and even with hundreds of lines would be measured in a few MB, at most, in a mod which 

So, theoretically speaking, while no such functionality exists at the moment, Civ is able to generate logfiles, so it's not much of a stretch to assume it could read them.

If I were to add one or more files with extra text (ideally laid out in an efficient way to prevent redundant searches) and a pointer in the code to search through the file(s) when deciding what random response to generate, would that work without consuming memory?

For instance, there could be a folder labelled "Text Database" and a bunch of files with each text key name. The game could open the folder, open the file with the correct filename (to avoid searching through every other text key) and pick a random number to decide which text key to use.

(If the file doesn't exist, then the game would default to the handful of normal responses stored in memory)

I'm not sure if this is possible or too costly performance-wise, but if it is, I think it's an idea with potential.

**Comment by HeathcliffWarriors** [comment]
For example, suppose I had "TXT_KEY_GENERIC_GREETING_HELLO.txt". The game needs to generate a response for TXT_KEY_GENERIC_GREETING_HELLO, so it follows this process:

1) Count the number of responses stored in memory.
2) Open TXT_KEY_GENERIC_GREETING_HELLO.txt, if it exists.
3) At the start of the file will be a number indicating how many responses the file has.
4) Add these two values together, then generate a random number between 1 and the # of responses.
5) Each text entry is written like so:
```
1, Hello.
2, Hi.
3, Howdy.
```
6) The game reads the first few characters of the entry to see if it matches the target number. When it finds the correct entry, it grabs it and outputs it.

7) If the target number exceeds the number of entries or there's otherwise a problem (like the file not existing), the game can just default to the handful of normal responses stored in memory.

**Comment by HeathcliffWarriors** [comment]
(I'm well aware this is probably way more work than it's probably worth, but nevertheless, it interests me enough that I'd probably do it at some point, were it possible to do)

**Comment by LoneGazebo** [comment]
@HeathcliffWarriors the rub is that reading from files at runtime is very expensive. Text loaded into memory and stored as separate strings is far more performance friendly.

Now, if you wanted to create dynamic strings, look at how I setup the instant yield text. You could create opener/middle/closer strings and run them together that way within the DLL, but you definitely do not want to read from text files during runtime,

**Comment by HeathcliffWarriors** [comment]
Curses. Back to the drawing board! :)
