### ISSUE TITLE
AI operation result stats

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5885]
some more pivot magic.

one test game, standard pangea, 400 turns in. zulus and assyria eliminated.

this is the military statistic. doesn't look too bad at first glance but i don't have a good reference to compare to. note that "too dangerous" means that the muster point was overrun by enemies.

observations:
* there are a lot of RapidResponse ops which time out ... this shouldn't happen, maybe we should modify the formation to use fewer units?
* there are no successful RapidResponse or NavalSuperiority ops?

![ai-op-result-military](https://user-images.githubusercontent.com/1358966/69493495-a0ea5980-0eaf-11ea-8057-f563727bbf75.png)

and this is the civilian result

![ai-op-result-civilian](https://user-images.githubusercontent.com/1358966/69493544-1a824780-0eb0-11ea-9647-0a0fee048f81.png)

don't know what's up with all those failed diplomat missions. also no concert tours at all, but maybe that's a fluke.

**Comment by HeathcliffWarriors** [comment]
I suspect the diplomat missions are failing due to a change I made to GetBestApproachTowardsMinorCiv - latest pull request should fix.

**Comment by ilteroi** [comment]
next game. standard fractal, 430 turns.

![ai-ops-results-military](https://user-images.githubusercontent.com/1358966/69501688-aecbc900-0f07-11ea-9c7c-414b417f5962.png)

similar picture. "NoUnits" for NavalSuperiority is actually a not-bad result, means they were killed in action.
