### ISSUE TITLE
Game freezes when trying to scroll between cities 

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#589]
It seems to be happening only when I try to press the right arrow button while viewing one specific city. Technically, it's not a CTD - the image freezes, but music and ambient sounds keep going. The game is then shown as not responding in the task manager and has to be closed forcefully.

**Comment by LoneGazebo** [comment]
I think ilteroi fixed this, and the fix will be in the next version.
G

**Comment by Edaka** [comment]
Ah, great. Looking forward to it then.
