### ISSUE TITLE
Spy was able to steal 3 techs in a row (in 3 turns)

### ISSUE THREAD

**Issue by RockettSJ** [LoneGazebo/Community-Patch-DLL#5897]
25-11(1) hotfix version

Only using full VP without EUI.

Check the turn count in the screenshots. Would happily upload saves if necessary but I don't know how

![spy1](https://user-images.githubusercontent.com/8049731/69636610-e5f8c200-104e-11ea-9f30-87120b62e588.png)
![spy2](https://user-images.githubusercontent.com/8049731/69636618-e8f3b280-104e-11ea-9ad2-192a46397011.png)
![spy3](https://user-images.githubusercontent.com/8049731/69636623-eb560c80-104e-11ea-8503-aeb318608ecd.png)

**Comment by HeathcliffWarriors** [comment]
@ilteroi

**Comment by ilteroi** [comment]
damn i should never have touched that tech cost thing. anyway i know where to look.

**Comment by ilteroi** [comment]
unfortunately i don't know what code actually went into that hotfix ... it may have been fixed already?

also it seems we always steal the tech with lowest ID, is that intended?

TechTypes eStolenTech = pEspionage->m_aaPlayerStealableTechList[uiDefendingPlayer][0];

**Comment by LoneGazebo** [comment]
Whatever you posted yesterday for espionageclasses.cpp I fixed.

**Comment by ilteroi** [comment]
yeah found the issue, forgot a factor 100 because nothing in the variable or function name indicates it ... whoever wrote this espionage code deserves to be flogged.
