### ISSUE TITLE
espionage randomness

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5901]
looking through espionageclasses.cpp (which is a horrible mess, i hope this is my first and only time) i found a bunch of instances like this:

int iOurSpyPower = iRandomRollSpyAction;

but iRandomRollSpyAction is not actually a random value, it's always 300. is this intended? correct usage would be something like

iSpyResult = GC.getGame().getSmallFakeRandNum(iRandomRollSpyAction, pCity->plot()->GetPlotIndex() + m_pPlayer->GetTreasury()->GetLifetimeGrossGold());

**Comment by LoneGazebo** [comment]
@ilteroi I just cribbed the existing nightmare system firaxis put in place...but yes, we can redefine that variable however we want.

**Comment by LoneGazebo** [comment]
You could easily write a new class function that creates that random value for you

**Comment by ilteroi** [comment]
that's not the problem ... the problem is that right now there is zero actual randomness in iOurSpyPower (and four additional instances)

**Comment by LoneGazebo** [comment]
Are you sure about that? Looking at code the only places where iRandomRollSpyAction is used w/o being modified is for the UI.

**Comment by LoneGazebo** [comment]
Modified or being ran against another number that is randomized.*

**Comment by ilteroi** [comment]
that's why i'm asking if the lack of randomness is intended?

looking at the overall code quality, it could just as well be a case of stupid naming syndrome.

**Comment by LoneGazebo** [comment]
Ah - I see question - yes lack of randomness for that value is intended. It is used against/with randomized values elsewhere.

I've long held that the espionage code was written by one-armed chimps. I put my band-aids on it and haven't looked back.
