### ISSUE TITLE
11/28 Melee Units doing equal city damage to ranged units...but with much higher strength

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5902]
_1. Mod version (i.e Date - 4/23):_
11/28

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Note that for this city attack. Even though the Swordsman has a much higher CS than the Cbowmen, they are doing the damage damage to the city.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/69676925-62979a80-1067-11ea-9bb1-4735dddd7ddb.png)

![image](https://user-images.githubusercontent.com/20593976/69676939-6d522f80-1067-11ea-9f91-f0358fef513d.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
first of all the bowman CS seems weird, 12 base+25% should be 15, not 16.8 but that might just be another lua issue

but anyway it seems for melee attacks the result is minus the damage the garrison will absorb whereas in the ranged attack it's the full damage. fixed
