### ISSUE TITLE
[Feature Request] Border expansion take in account yields from pantheons

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#5903]
As being currently discussed in the November 25th threads (https://forums.civfanatics.com/threads/new-beta-version-november-25th-11-25.652102/page-4#post-15604440), the automated border growth fail to take in account that some resources are high priority because of the chosen pantheon.

I guess an ad hoc code could be added to check if the tiles are boosted by the pantheon or not, but there is probably a better solution.

Quickly looking at the code, it seems that the core reason is that tiles are evaluated for the yield they currently have, and not the yield they could have if they were inside the city border. However, I don't think there is any function currently coded that predict "how much yield would a tile produce if it were part of the city", so it seems non-trivial to change.

Though? Ideas?

**Comment by LoneGazebo** [comment]
It’s a very expensive calculation.

**Comment by ilteroi** [comment]
hmm, i would rather not touch this, it becomes complicated quickly ... next request will be to consider possible unique improvements as well
