### ISSUE TITLE
Visibility update issue with trade routes

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5907]
_1. Mod version (i.e Date - 4/23):_ Latest

_2. Mod list (if using Vox Populi only, leave blank):_ IGE & some UI stuff

So Morocco has an undocumented component to their UA wherein if they plunder a trade route while not at war and when out of sight, they don't get diplo penalties for it and the notification shows up saying it was done by Barbarians.

It's a useful ability for Morocco because their kit includes plundering trade routes that aren't connected to their cities while not at war.

I fixed this so it applies also to the destination civilization, not just the origin civilization. I also restored the diplo penalties for plundering trade routes.

The trouble is, when a trade route is plundered, the visibility doesn't change (at least, not for the AI).

I plundered a Mongolian Caravan on the plot where my Spearman is standing and received a diplo penalty for it. 

Using IGE confirmed that it was because Mongolia had visibility of the plot, despite having no units there.

![Screenshot (20678)](https://user-images.githubusercontent.com/38794241/69833720-afb07380-1203-11ea-8a96-8d2c352ef5ca.png)

@ilteroi Would it be possible to tinker with the code so it runs in the following order, when a trade route is plundered?

1 - Kill the Caravan/Cargo Ship
2 - Update the trade route owner's plot visibility for the plot the Caravan/Cargo Ship was on
3 - Call the PlunderTradeRoute function in CvTradeClasses.cpp (which handles, among other things, the diplo stuff)

**Comment by ilteroi** [comment]
i'll be away for a while ... caravans are regular units, but with a sight range of zero, meaning they see their current plot but no neighbors. so i don't know how a player would ever have one of his own caravans out of sight?

**Comment by HeathcliffWarriors** [comment]
Problem 1: the caravan is still providing visibility of the plot it's on after being killed, which I think isn't supposed to happen for any units, but IGE indicates it does for caravans.

Problem 2: this prevents the Moroccan UA where they receive no diplo penalties for plundering on plots the trade route owner can't otherwise see from working.

**Comment by HeathcliffWarriors** [comment]
@ilteroi Just a reminder for this, since you were away. Hope you went somewhere nice, by the way!

**Comment by ilteroi** [comment]
should be better now ...
