### ISSUE TITLE
Mongolia UA affected by low population + penalty not working

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5909]
_1. Mod version (i.e Date - 4/23):_ Latest

_2. Mod list (if using Vox Populi only, leave blank):_ IGE & some UI stuff

Mongolia's UA is affected by the City-State having a low population. This makes sense for enslaving a Worker (vanilla heavy tribute) or providing large yield bonuses, but...you'd think having a low population would, if anything, make the City-State _more_ vulnerable to being conquered.

![Screenshot (20672)](https://user-images.githubusercontent.com/38794241/69835953-4c2e4200-1213-11ea-952e-481e61a14509.png)

Also, I annexed another City-State this turn, yet it doesn't seem to be adding a penalty to my annexation (I believe it's supposed to be -20)?

The penalty wasn't applied the next turn, either.

**Comment by HeathcliffWarriors** [comment]
It's entirely possible for a player to go to war with a City-State and plunder/blockade all their tiles to starve them, preventing Mongolia from annexing it - which would be a counterintuitive mechanic. :)

**Comment by LoneGazebo** [comment]
I don't think this is an issue TBH.
