### ISSUE TITLE
AI not defending Forts, Citadels, and Great Generals

### ISSUE THREAD

**Issue by usadefcon1** [LoneGazebo/Community-Patch-DLL#5916]
_1. Mod version (i.e Date - 4/23):_
11-25-2

_2. Mod list (if using Vox Populi only, leave blank):_
See Screenshot

_3. Error description:_ 
The AI appears to be leaving its Forts, Citadels, and Great Generals undefended.

![Screenshot (4)](https://user-images.githubusercontent.com/57153924/69908931-b6381a00-13c0-11ea-8cdc-1be767dd09ca.png)
![Screenshot (5)](https://user-images.githubusercontent.com/57153924/69908932-b6381a00-13c0-11ea-8fcc-a4805123c984.png)
![Screenshot (6)](https://user-images.githubusercontent.com/57153924/69908933-b6d0b080-13c0-11ea-83c7-aa9581c0f02b.png)
![Screenshot (7)](https://user-images.githubusercontent.com/57153924/69908934-b6d0b080-13c0-11ea-890e-255c14c1e0f7.png)
![Screenshot (8)](https://user-images.githubusercontent.com/57153924/69908935-b6d0b080-13c0-11ea-89dd-3136cc1c7068.png)
![Screenshot (11)](https://user-images.githubusercontent.com/57153924/69908936-b6d0b080-13c0-11ea-89ad-0e5b1f906ac8.png)

**Comment by ryanmusante** [comment]
Can you point me to the link for "Units Wake When Ungradeable"?

**Comment by usadefcon1** [comment]
> Can you point me to the link for "Units Wake When Ungradeable"?

"Units Wake When Upgradeable" by calcul8or on Steam.
