### ISSUE TITLE
Feature request - withdraw before range attack

### ISSUE THREAD

**Issue by Tekamthi** [LoneGazebo/Community-Patch-DLL#5917]
_1. Mod version (i.e Date - 4/23):_
N/a

_2. Mod list (if using Vox Populi only, leave blank):_
N/a

_3. Error description:_ 
Not an error, just a request... There used to be a withdrawBeforeMelee option in the SQL promo tables (I'm sure it's still there, I just haven't looked in a while), but no equivalent withdrawBeforeRanged.. can we have one added that works the same way, but triggers off ranged attacks instead of melee?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Since direction is harder to predict with ranged this is not feasible without a  lot of work.

**Comment by Tekamthi** [comment]
> Since direction is harder to predict with ranged this is not feasible without a lot of work.

isn't this already built-in to 'withering fire' promo, where range attack forces withdrawal after attack?

**Comment by LoneGazebo** [comment]
I misunderstood the request. Yes this is already built in.
