### ISSUE TITLE
Feature request - generic version of special cargo

### ISSUE THREAD

**Issue by Tekamthi** [LoneGazebo/Community-Patch-DLL#5918]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Another feature request as I return to modding.. would it be possible to have a generic version of the special cargo ability on the nau? Ie one that doesn't create fetoria? In past modding I used the special cargo flag in promos then had any ineligible fetorias removed via Lua, but this is inelegant.

If added, I'd be happy with it mostly the same otherwise, though ideally I'd want to be able to set the value of the trade return (existing special cargo is rather high for my purposes).  Extra points if it can be made 'reloadable' in some ai-accessible way (ie trigger it in own borders to +1 cargo, in foreign borders to -1 cargo)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I think it works that way already...civ has to be owner of the special improvement to do the Feitoria thing now.
