### ISSUE TITLE
City can't adopt a religion via passive spread with Piety opener

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#592]
During my Piety playthrough my cities have been having difficulties adopting my religion. It went like this: at the beginning of a turn a notification popped up: 
![rel](https://cloud.githubusercontent.com/assets/12978597/9688788/31be14e6-533a-11e5-8ef0-8e03eabb9da5.jpg)
But, in fact, the city remained without a majority religion, as can be seen.
![rel1](https://cloud.githubusercontent.com/assets/12978597/9688850/8786092e-533a-11e5-97d3-66f9f0859edb.jpg)
So, despite my religion (Islam) having had such high pressure in the city, it couldn't become their majority one. Eventually, it did after few turns (though the notification would pop up every turn inbetween).

After that, the city would swing back and forth between having a majority religion (mine) and not having a majority religion. This was happening to a handful of cities that had the highest neighbour's religion's (Protestantism) pressure.

I guess it might have to do something with recalculating (cutting in half) my religion's pressure after a city has adopted it as a majority one between my turns?

**Comment by LoneGazebo** [comment]
Looks like an odd quirk caused by the piety opener. It isn't a 'bug,' per se, but rather a result of the pressure fluctuation.

**Comment by Edaka** [comment]
Well, one's city can remain with a stagnant amount of followers for quite some time even with ridiculous pressure values as a result of this. I had this city with only 5 out of 6 citizens following a religion for a good amount of turns, all the while triggering the 'your city has adopted a religion' pop up. 

Eventually, it converted, but for some reason it then reverted back after a while, even though my religion's pressure was higher that my neighbour's after Piety opener wore off (talking about a different city).
