### ISSUE TITLE
Civilopedia Technology Cost Mismatch & Promotion Category Issue

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#5923]
_1. Mod version (i.e Date - 4/23):_ 11-25 Beta, probably still present in current beta

Tech cost under **Cost** doesn't match the value under **Game Info**. Some examples provided below.

![Screenshot (20720)](https://user-images.githubusercontent.com/38794241/69931584-d1c12480-1495-11ea-98b0-5d03bc452887.png)
![Screenshot (20721)](https://user-images.githubusercontent.com/38794241/69931586-d1c12480-1495-11ea-8f22-2e0c9d1a3555.png)
![Screenshot (20722)](https://user-images.githubusercontent.com/38794241/69931587-d1c12480-1495-11ea-9fe7-a4e6467e90b6.png)
![Screenshot (20723)](https://user-images.githubusercontent.com/38794241/69931588-d1c12480-1495-11ea-912a-8c0fdbc437ba.png)

Also, why are these two promotions listed as Civilian promotions? They're military only.

![Screenshot (20724)](https://user-images.githubusercontent.com/38794241/69931589-d1c12480-1495-11ea-8eca-13fd0c16d475.png)
![Screenshot (20725)](https://user-images.githubusercontent.com/38794241/69931590-d1c12480-1495-11ea-96a4-7ad23cd931ae.png)

**Comment by RecursiveVision** [comment]
@LoneGazebo Since you're in a bugfixing frenzy - pretty sure this bug is still present.

**Comment by LoneGazebo** [comment]
'cost' values are set in database, whereas TT is generated on the fly.

**Comment by LoneGazebo** [comment]
GG promotions are in civilian because...they're civilans? dunno

**Comment by RecursiveVision** [comment]
@LoneGazebo Great Generals I/II are the "combat is more likely to create Great Generals" promotions...civilian units can't obtain them.

Is there any way to change the source of the cost number so that it uses the runtime info instead of the database? The examples I used here were at game start with no cost reductions or modifiers IIRC, so it's getting wrong information somewhere along the line.

**Comment by LoneGazebo** [comment]
@RecursiveVision those values are pulled directly out of the database columns - they're loaded prior to a game starting (you can view the civilopedia in the menu) so you can't edit them using 'game' parameters.
