### ISSUE TITLE
11/25 - Battleship requires both Iron and Oil

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5925]
_1. Mod version (i.e Date - 4/23):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Unless this is an undocumented change, battleships are supposed to require Iron. According to this it requires both iron and oil.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/69940341-aa735300-14a7-11ea-8a86-b818f5c6da69.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
This is actually 11/25 not 12/1

**Comment by ridjack** [comment]
It's also true on 12/1.

**Comment by Edaka** [comment]
Hotfixed, as far as I know.
