### ISSUE TITLE
11/25 - Strange Misc Bonus on defending units

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5927]
_1. Mod version (i.e Date - 4/23):_
11/25

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So I've noticed in the past that the Anti-warmonger bonus seems to roll into a misc bonus periodically. However, in this case even that wouldn't explain it. What is granted this ship such an incredibly high misc bonus?

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/69987267-bc371380-1504-11ea-8f0a-36049b965395.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
Look at the enemy promotions, and add them together, should give you approx. (because of anti-warmonger) the same value (all promotions, usually when exceeding four of them the remaining ones get added to the misc. bonus for preventing overflowing)
