### ISSUE TITLE
11/25 - City Attacks Remain Weak

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5928]
_1. Mod version (i.e Date - 4/23):_
11/25

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This city has all of the defense buildings and yet can barely scratch a bazooka.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/69987813-fd7bf300-1505-11ea-868c-254b0d31ed17.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
you said it yourself, those building are defensive. they don't contribute to attacks. that's by design. which doesn't imply that the design is good ...

**Comment by Stalker012345** [comment]
> you said it yourself, those building are defensive. they don't contribute to attacks. that's by design. which doesn't imply that the design is good ...

My point is that cities used to do a bit more damage than they are doing now.

**Comment by MoiMagnus** [comment]
I've open a thread here: https://forums.civfanatics.com/threads/city-attack-strenght.652417/

**Comment by ilteroi** [comment]
honestly i would disable ranged attacks from cities completely, they aren't essential for anything. radical but simple solution. has a few knock-on effects though ...
