### ISSUE TITLE
Cannot attack enemy cities if there is a non-hostile unit there.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#593]
![2015-09-04_00002](https://cloud.githubusercontent.com/assets/13937047/9693171/1fa015a2-5303-11e5-932e-bf8adc973406.jpg)
![2015-09-04_00003](https://cloud.githubusercontent.com/assets/13937047/9693172/1fb68ae4-5303-11e5-82cd-9fc97c30a1ae.jpg)

This is not intentional because I am able to use a melee unit to attack the city, but I am not able to use a ranged unit to attack the city if there is a non-hostile unit vacating the city.

**Comment by Edaka** [comment]
I believe manually clicking the 'ranged attack' and then left-clicking the city works in these situations.

**Comment by TechpriestEnginseer** [comment]
Huh, thanks for the advice. Will do it in the future. I was just IGEing the workers out of the city.

**Comment by LoneGazebo** [comment]
I'll fix this in the next version. NMCTJ was not a terribly well fleshed-out mod.
