### ISSUE TITLE
[Code typo] About the City Strength and other subjects

### ISSUE THREAD

**Issue by MoiMagnus** [LoneGazebo/Community-Patch-DLL#5930]
In CvCity::updateStrengthValue, we have the following lines:

`int iBuildingDefense = m_pCityBuildings->GetBuildingDefense();`
`...`
`iBuildingDefense *= (100 + m_pCityBuildings->GetBuildingDefenseMod() + iAdjUnitDefense);`
`iBuildingDefense /= 100;`
`iStrengthValue += iBuildingDefense;`

The first issue is that iAdjUnitDefense might be undefined, as it is only defined if MOD_BALANCE_CORE is defined.

The second issue is that latter, in the code of CvCity::getStrengthValue, we have:

`int iValue = m_iStrengthValue - m_pCityBuildings->GetBuildingDefense();`

So we forgot to apply the modifier "GetBuildingDefenseMod" and "iAdjUnitDefense" to "GetBuldingDefense" before substracting it.

**Comment by MoiMagnus** [comment]
Oh, and we should also apply "GET_PLAYER(getOwner()).GetCityStrengthMod()" before subtracting it.

**Comment by MoiMagnus** [comment]
I've found another weird thing, in the vassalage code of CvDiplomacyAI.cpp, function CvDiplomacyAI::IsCapitulationAcceptable:

	`int iWarScore = GetWarScore(ePlayer);`
	`// Check war score`
	`if (GetWarScore(ePlayer) > -80) return false;`
	`if(iWarScore < -80) iWantVassalageScore = 75;	else iWantVassalageScore = 100;`

This code is weird because it call GetWarScore twice instead of once, but that's irrelevant.
The important part is that, a warscore of -80 is somehow better than a warscore of -81. That doesn't make any sense to me that iWantVassalageScore start at 75, except when the warscore is precisely -80 where it starts at 100.

**Comment by LoneGazebo** [comment]
@MoiMagnus it'd make more sense to do it as an inverse function, so iWantVassalageScore = 100 - WarScore (etc.)
