### ISSUE TITLE
12/1 - Combat Screen not showing anti-mounted bonus against Heavy Skirmisher

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5931]
_1. Mod version (i.e Date - 4/23):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Tercio in these examples has the same CS for both units, suggesting that the +50% vs mounted is being applied to both knight and heavy skirmisher. But the combat screen does not show that bonus against the skirmisher.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/70203026-37552100-16e1-11ea-934d-dd3223380c8d.png)

![image](https://user-images.githubusercontent.com/20593976/70203047-4936c400-16e1-11ea-8858-16f4524461c5.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
No idea how to fix this...

**Comment by LoneGazebo** [comment]
Look at line 1602 of EnemyUnitPanel. It should be working...

**Comment by Aqinu** [comment]
I looked at those lines, that's why I said that I don't know whats wrong, so that maybe someone does...

**Comment by Aqinu** [comment]
Just to point out similar issue opened also at #5931.
