### ISSUE TITLE
Frigates lose all movement after attacking

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#5935]
_1. Mod version (i.e Date - 4/23):_
12/1-1

_2. Mod list (if using Vox Populi only, leave blank):_
![Capture](https://user-images.githubusercontent.com/19291347/70280998-c9b00000-1787-11ea-9eae-e4b291ca7b32.PNG)

_3. Error description:_ 
Frigates turn end after shooting.  Haven't checked other ships except Galleass which seem to work fine.

**Comment by Aqinu** [comment]
This is intended, they don't have "move after shooting" promotion...

**Comment by phantommaxwell** [comment]
They even lose all their Movement after spending their 2 attacks with Logistics for not having the "move after attacking" promotion.

**Comment by azum4roll** [comment]
Logistics doesn't imply move after attacking after all...
