### ISSUE TITLE
12/1 Event bug - "special session"

### ISSUE THREAD

**Issue by BorussiaVox** [LoneGazebo/Community-Patch-DLL#5939]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
infoaddict
reforestation (modified)
really advanced setup
faster aircraft animations
submarines ignore borders

_3. Error description:_ 
In the event I chose the option to receive 3600 gold and that banks increase gold output by 5%.
I did not receive the 5% gold increase of banks.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20191207034701_1](https://user-images.githubusercontent.com/31174386/70368089-09213e00-18a7-11ea-9dad-7337db0d4c93.jpg)

**Comment by LoneGazebo** [comment]
that's not a VP quest.

**Comment by BorussiaVox** [comment]
I really only use full VP and those small mods I mentioned that should not have anything to do with this event.

**Comment by bigcat88** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/3970
