### ISSUE TITLE
Fix to Resolution: UnitMaintenanceGoldPercent

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#594]
For my upcoming Mercenaries mod, I have one resolution to ban Mercs. In the hopes that I could tempt the AI to vote for it, I decided to give it the secondary bonus of reducing the maintenance cost of military units, inverse to the Standing Army tax. One civ did vote in favour, so I'm guessing that this idea is good enough to make the resolution more than dead weight. However, I discovered that the actual effect is another one of those things in which the inverse value isn't accepted. When the resolution was passed, it actually increased the cost, though I'd specified it to reduce maintenance by -25%. So it'd be great if this can be fixed. Thanks.

**Comment by LoneGazebo** [comment]
If you are using the CP, you have access to CSD's resolution functions as well. As such, you can use the 'reduce maintenance cost' element of CSD to do this. Look in CSD's DLL folder for the function.

There's a couple of other CSD-created resolution functions that might also work for you. Take a look and let me know.

G

**Comment by JFDaly** [comment]
I see that you just use the standard tag, so I assume CP DLL already allows for a reduction. But there are definitely some interesting things included. Thanks.
