### ISSUE TITLE
Units are keeping Statue of Zeus promotion after civ loses the wonder.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#5941]
12/1 version, I just took the SoZ off Monty and vassalized him about five turns ago and I'm still seeing the promotion on his units.

![CivilizationV_DX11_asmBQGDWBO](https://user-images.githubusercontent.com/22875626/70378686-5aeeb600-18f1-11ea-8a6e-3e5aa75d5b6e.jpg)

![CivilizationV_DX11_sYGWyFnVpL](https://user-images.githubusercontent.com/22875626/70378700-75289400-18f1-11ea-8084-7c1e2aec419c.jpg)

**Comment by bigcat88** [comment]
New units created by Monti grants this promo? If yes - then it is a bug. 
Old units must not loose promo.

**Comment by Edaka** [comment]
@ridjack Could you confirm whether new units that shouldn't be getting the promotion are still getting it? If it's just the old ones keeping it, then it's working as intended

**Comment by ridjack** [comment]
No idea. That game is long gone now.

Seems counter-intuitive; as far as I know, other wonders (natural or world) that give promotions to all units do not work like this; you only get the promotion as long as you have the wonder.

**Comment by bigcat88** [comment]
A year ago I am 100% sure that Kilimanjaro was like current Zeus. Capture city with it, all units receive promo and then you can burn\trade that city. 
And I don't remember in change-log that this was changed.
So it is intended and works like it should, imho.
