### ISSUE TITLE
AI making landmarks outside of any workable borders.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#5943]
12/1; after taking some cities from Montezuma, I discovered he (or someone, but most likely him) had multiple landmarks built outside of any workable borders.

![CivilizationV_DX11_eDRXNgXQ2r](https://user-images.githubusercontent.com/22875626/70379826-246c6780-1900-11ea-93fe-c590da472ec7.jpg)
![CivilizationV_DX11_mZO6c7YXrV](https://user-images.githubusercontent.com/22875626/70379827-2504fe00-1900-11ea-94cf-13ea711846cd.jpg)

**Comment by LoneGazebo** [comment]
No slots I bet.
