### ISSUE TITLE
Pentagon JetFighters start without exp.

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#5949]
_1. Mod version (i.e Date - 4/23):_
12-1-1

Subj. Got two JetFigthers with 0 exp.

**Comment by UndeadDevel** [comment]
If this gets fixed can we please do the same for Treasure Fleet (giving the free Frigate one can win some XP)...I'm thinking 35 XP should do it for the Frigate and maybe 60 XP for the Jet Fighters (scaled with game speed, of course); this would be the equivalent of Barracks + Armory XP for the Frigate and Ba. + Ar. + Military Academy for the fighters.

**Comment by bigcat88** [comment]
Treasure Fleet already doing well. It was fixed in this year.

**Comment by UndeadDevel** [comment]
Really? I remember playing an October version where the Frigate definitely didn't get XP...are you sure?
