### ISSUE TITLE
Function to convert integer to string?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5950]
I'm writing a logging function to assist in my debugging; however, I'm unsure on how to convert an integer into a string to put into the logfile.

There is information on this available online, but I'm not sure how much of it applies to VP, since it's written using older code.

So as is my usual way of problem solving, I'm scouring the repository for a solution. I see a potential solution in LuaPlayer:
```
#if defined(MOD_API_LUA_EXTENSIONS) && defined(MOD_DIPLOMACY_CIV4_FEATURES)
		if(MOD_DIPLOMACY_CIV4_FEATURES && GC.getGame().isOption(GAMEOPTION_ADVANCED_DIPLOMACY))
		{
			CvString strTemp;
			// Reverse the value of the opinion so as to not confuse players
			strTemp.Format(" (%d)", -(aOpinions[ui].m_iValue));

			strOutput += strTemp;
		}
#endif
```
This seems to indicate that I can write "%d" and the integer after the comma will replace "%d". Is this correct?

**Comment by MoiMagnus** [comment]
Yes, the Format method takes a string containing some  %d and then one integer argument per %d in the string, and replace those %d by the value of this integer.

So strTemp.Format("The first value is %d, the second is %d, and the third is %d", 1,2,3); would put in strTemp the string "The first value is 1, the second is 2, and the third is 3.

Something quite useful is %+d, which is is the same as %d for negative numbers, but add a + in front of positive numbers.

If you ever need to put in a string something else than signed decimal integers, you can see here (http://www.cplusplus.com/reference/cstdio/printf/) a list of what letter to put after the %. For example, for an unsigned integer, it is %u, for a long int it is %ld, for a long long int it is %lld, for a char it is %c, for a string it is %s, for a float it is %f, ... And there is also a ton of option to automatise padding with zeros or spaces, or precision for floats.
