### ISSUE TITLE
No Cap Per Turn For Purchasing Mercenaries

### ISSUE THREAD

**Issue by durkki** [LoneGazebo/Community-Patch-DLL#5951]
Mod version: 11-9

Error description: 
When you purchase the unit "Mercenary," you are able to buy them for as long as you have gold (and free tiles), as you can move them the same turn you buy them. This way you are able to buy hundreds of units in 1 turn, if you have the coin.

**Comment by HeathcliffWarriors** [comment]
I think that's intended. It also applies to purchases made with Faith, minus the moving after purchase.
