### ISSUE TITLE
Why do City-States prioritize Shrines?

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#5952]
Ran a test game to get an understanding of how AI Autoplay works.

Am playing on Deity on a crowded map; I noticed that almost all, if not all City-States are building a Shrine before anything else.

Why? I get that on Deity they start with 3 Warriors, but a Monument or Worker is much more useful to a City-State than a Shrine is; City-States can't found pantheons.

I mean, I can understand it for Hong Kong, goodness knows they could use extra faith right now with how terrible things are, but for the rest of the City-States in my game, it makes no sense.

Logs are attached.
[Production Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3949252/Production.Logs.zip)

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Since you're adjusting city production AI, may want to look at this.
