### ISSUE TITLE
Issue with Observer/Autoplay mode (can't pause)

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5953]
I've just started using the Firaxis LiveTuner to autoplay games.

For a while I couldn't figure out how to stop autoplay once it was started, but I realized that the issue was that I had it set to "return as OBSERVER".

It seems that, unless I'm mistaken, the tuner supports autoplay, but will not allow you to pause the autoplay process mid-turn or at the end of a turn, and still remain as an Observer (which allows you to spectate city production & other useful values). It forces you to leave spectator mode and take over one of the AI players' slots.

Does anyone know a way around this?

**Comment by ilteroi** [comment]
yes indeed. i built a little python script to do exactly that. can share it as soon as i get home ...

**Comment by HeathcliffWarriors** [comment]
@ilteroi I'd appreciate that a lot, thank you!

**Comment by ilteroi** [comment]
here you are. obviously you need to install python ... run the script in parallel to the game. after clicking "acquire mutex" the game is paused at the beginning of the next turn slice. after clicking "release mutex" the game continues.

[TurnByTurn.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3961752/TurnByTurn.zip)

**Comment by HeathcliffWarriors** [comment]
Thank you very much!
