### ISSUE TITLE
Minor issue: superfluous space in diplomatic message

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5957]
_1. Mod version (i.e Date - 4/23):_
12/1-1

_3. Error description:_ 
See screenshot. This was after asking him to join a war with me again (it indicates repeated refusal).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![diplo_message_bug](https://user-images.githubusercontent.com/30495439/70838469-41bd9c00-1e00-11ea-93b5-5e468feabea5.jpg)

**Comment by HeathcliffWarriors** [comment]
Vanilla typo, thanks for pointing out.
