### ISSUE TITLE
William of Orange too enthusiastic about extra luxuries

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#5959]
_1. Mod version (i.e Date - 4/23):_
12/1

William of the Netherlands is willing to buy as many copies of the same luxury as I can sell. For example, if I have 4 spare cocoa, he will be up to purchase all of them. As far as I know, only one copy will really benefit him, though.

**Comment by UndeadDevel** [comment]
Well he can gain monopolies through trade, though that would require buying a lot of them usually, of course; he also gets yields from exporting resources...maybe he can export the extra copies he has first imported?

**Comment by Edaka** [comment]
Hmmm, I don't think he resell them like that. Good point about monopolies, though, but it's hard to execute due to the 1 copy per trade deal restriction. But yeah, I completely forgot about the ability to get a monopoly from imports, so I think then it's working as intended.

**Comment by HeathcliffWarriors** [comment]
@Edaka William will be willing to buy luxuries until he has monopoly bonuses. If he already has a global monopoly, he'll only pay 5 Gold per extra copy beyond that.
