### ISSUE TITLE
National wonder population requirement not reduced for Venice as documented

### ISSUE THREAD

**Issue by Mallek3** [LoneGazebo/Community-Patch-DLL#596]
There appears to be an issue with the national wonder population requirements for Venice.  The mod documentation states that the population requirements for national wonders should be 1/3 of the normal requirements for OCC and Venice.  Looking at the code (line 9935 in CvPlayer.cpp) the modifier only applies to OCC.

**Comment by Radost** [comment]
#288

**Comment by Mallek3** [comment]
Appreciate the link.  It appears this has been brought up before and it's working as intended.
