### ISSUE TITLE
Unsuccessful coup in a CS allied to your war adversary make you peace out with the CS

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#5960]
_1. Mod version (i.e Date - 4/23):_
12/1

Say I'm at war with player A. Player A is allied to city-state B, hence I'm automatically at war with city-state B as well. If I attempt a coup in city-state B and fail, the war with the city state will automatically abort, even while the war with player A will still continue, logically. 

One time when this happened I also noticed that this immediately lowered player's A influence over the city-state, to the point that they stopped being allies. Mind you, it was a failed coup by me.

**Comment by jimmymcperson** [comment]
This happens to me too on 12/1/1
