### ISSUE TITLE
Aqueduct not applying production boost

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5965]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2)
UI - Religion Spread (Vox Populi) (v 1.1)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
The Aqueduct description states that "[...] and +25% of the Production of the City is added to the City's current Production. [...]"; however, this does not seem to happen. See the two screenshots below where all buildings of the City are shown (I have Authority 6, which explains the Production on the City tile itself and have researched Steel, which is what boosts my Mines; I also have the War Fervor Event active, where I chose +3 Production to all Cities for 45 turns).
Notice that summing all the Production from the tiles, buildings (including the population scaler from Waterwheel) as well as the specialist and event will already sum to the total Production before the 10% Wonder modifier (I have Stone and Colossus is a Classical Era WW) is applied. Notice also in the second screenshot, 1 turn later, that exactly this amount was added and not a single hammer more.

So the question is: where is the +25% from the Aqueduct?

Edit: I checked some older screenshots from previous versions: I'm pretty sure this 25% is supposed to appear as a "City Modifier" that is applied to the base Production...this seems to be broken currently, which is actually pretty annoying as it does reduce overall Production pretty significantly starting in early mid-game.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Aqueduct1](https://user-images.githubusercontent.com/30495439/70855956-15228680-1ecb-11ea-87fc-a46879bd1dcd.jpg)
![Aqueduct2](https://user-images.githubusercontent.com/30495439/70855958-1eabee80-1ecb-11ea-83da-fdac1c8d0bfa.jpg)

**Comment by UndeadDevel** [comment]
Tested with 12-1-1 VP only (and IGE to create the conditions): the bug's still there, unfortunately, so it's not one of my modmods causing it.

**Comment by LoneGazebo** [comment]
I think you're misreading the bonus - when the city grows, you get 25% of the city's current total production output as an instant yield.

G

**Comment by UndeadDevel** [comment]
Looks like you're right!
