### ISSUE TITLE
Unclear Perfume Monopoly description

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5966]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2)
UI - Religion Spread (Vox Populi) (v 1.1)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
I have 6/9 Perfume and therefore a global Monopoly...after acquiring it, however, I noticed that the "+3 Gold from Resource tiles" only applies to Perfume tiles, not Cocoa or other Resources. So I'm thinking either the description should change or the Monopoly should actually count for Resources other than Perfume.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
"+X yield from Resource Tiles" always refers to the resource in question. Of course, that might be unclear.

**Comment by UndeadDevel** [comment]
Ah...well it would be clearer if it said "from this Resource type" or "from Perfume Tiles" or something like that.

**Comment by ASCII-Guy** [comment]
This applies to all resources. It's a generic phrase.

**Comment by UndeadDevel** [comment]
Can it be changed to "Resource type" then? I know it's a nitpick but technically the description is inaccurate since it clearly does not boost "Resource tiles" but only tiles of that specific Resource type.

**Comment by LoneGazebo** [comment]
It's fine, Monopoly bonuses always apply solely to the resource itself.
