### ISSUE TITLE
Puppets tool tip issues and Faith/Culture output calculation

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5967]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2)
UI - Religion Spread (Vox Populi) (v 1.1)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
Other yields seem to work fine and the tool tip for those yields shows the -80% Puppet modifier, but for Culture and Unhappiness it doesn't do anything and the Puppet modifier isn't part of the tool tip; thus my Puppet has no Unhappiness at all and no Culture output at all, including no border growth, despite having a Culture building; see screenshots.

Edit (update after more testing):
There are 3 problems:
1. what led to the confusion about Unhappiness is an incorrect tool tip:
![Puppet3](https://user-images.githubusercontent.com/30495439/70863799-c06f2200-1f43-11ea-8a30-2b01031237e9.jpg)
So if 1 Unhappiness per 5 Citizens for Puppets is working as intended, the tool tip needs to be changed to reflect that.

2. superfluous bullet point in Faith tool tip (only happens in Puppets):
![Puppet4](https://user-images.githubusercontent.com/30495439/70863820-f90efb80-1f43-11ea-8423-33a9449c53ba.jpg)

3. Calculation of Faith and Culture output for Puppets: there seems to be some sort of Math.floor() function running here, which does not occur with the other yields...therefore, there will be no Faith or Culture generation with Puppets until they reach at least 5 Culture or 5 Faith (because of the -80% Puppet yield modifier; if that modifier is reduced, e.g. by choosing Martial Law from the Imperialism tree, the yields required to get border growth or Faith are reduced).
**Is this working as intended?**

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Puppet_issues1](https://user-images.githubusercontent.com/30495439/70856586-5f116980-1ed7-11ea-877b-3a96eb42e2ee.jpg)
![Puppet_issues2](https://user-images.githubusercontent.com/30495439/70856590-6cc6ef00-1ed7-11ea-9ddb-c81799514f72.jpg)

**Comment by HeathcliffWarriors** [comment]
Puppets don't generate happiness or unhappiness IIRC.

**Comment by UndeadDevel** [comment]
Unless I missed some recent change, Puppets are supposed to generate 1 Unhappiness for every 3 or 4 Citizens. And they're also supposed to output Culture (with the Puppet malus applied, of course).

**Comment by UndeadDevel** [comment]
Tested with VP 12-1-1 only (and IGE to create the conditions: the bug's still there, so it's not any of the modmods I'm using)...no matter how many Culture buildings I put into the Puppet, it won't actually produce any and therefore never grow borders on its own.

**Comment by UndeadDevel** [comment]
Okay I did some more testing with this in VP only (+IE): there are 3 separate issues with Puppets (I'll update the OP in a bit):

1. what led to the confusion about Unhappiness is an incorrect tool tip:
![Puppet3](https://user-images.githubusercontent.com/30495439/70863799-c06f2200-1f43-11ea-8a30-2b01031237e9.jpg)
So if 1 Unhappiness per 5 Citizens for Puppets is working as intended, the tool tip needs to be changed to reflect that.

2. superfluous bullet point in Faith tool tip:
![Puppet4](https://user-images.githubusercontent.com/30495439/70863820-f90efb80-1f43-11ea-8423-33a9449c53ba.jpg)

3. Calculation of Faith and Culture output for Puppets: there seems to be some sort of Math.floor() function running here, which does not occur with the other yields...therefore, there will be no Faith or Culture generation with Puppets until they reach at least 5 Culture or 5 Faith (because of the -80% Puppet yield modifier; if that modifier is reduced, e.g. by choosing Martial Law from the Imperialism tree, the yields required to get border growth or Faith are reduced).
Is this working as intended?

**Comment by LoneGazebo** [comment]
TT is correct - there's no 'floor' math here, culture and faith aren't calc'd in 100s like other yields.

**Comment by LoneGazebo** [comment]
I'll fix 1 per 3 to 1 per 5
