### ISSUE TITLE
12/1 - Not gaining 2 votes per CS ally after Modern Era

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5969]
_1. Mod version (i.e Date - 4/23):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When the modern era hits, your CS allies are now supposed to give 2 votes instead of one. However, I am still only getting 1 each.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/70859896-eb278f00-1edf-11ea-92d8-4ac550313efd.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by UndeadDevel** [comment]
I believe the two votes per CS Ally start with the UN, so you need to build the UN first by proposing that resolution and getting it passed and built.

**Comment by Stalker012345** [comment]
If that's the case than the issue is a text one. One you get to the Modern Era WC screen, it says you get 2 votes per ally.
