### ISSUE TITLE
NewText.xml in Community Patch

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#597]
<Row Tag="TXT_KEY_GENERIC_COMPETITION_ANNOUNCE_WORLD_CONGRES_1">
			<Text>You will soon bend your knee to my silver-tongued diplomats. Global hegemony shall be mine!</Text>
		</Row>
		<Row Tag="TXT_KEY_GENERIC_COMPETITION_ANNOUNCE_WORLD_CONGRES_2">
			<Text>You'll be happy to know that I've just finished revising my acceptance speech for the position of 'Supreme Leader of Earth.' I do hope you'll attend the reception.</Text>
		</Row>
		<Row Tag="TXT_KEY_GENERIC_BLOCK_ANNOUNCE_WORLD_CONGRES_1">
			<Text>Your machinations in the World Congress are pathetic. A true hero fights his battles with swords, not coins and silver tongues.</Text>
		</Row>

I hope you will see a mistake in the tags.. of world_congres.

**Comment by LoneGazebo** [comment]
These were done by someone else, but I'll fix the typo. Thanks!
G
