### ISSUE TITLE
[FEATURE REQUEST] Cities only demand Luxuries that they know about

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5971]
An annoyance I've had for a long time is that the early-game WLTKDs are extremely luck-dependent. This is because a City will demand a random Luxury that could come from anywhere on the entire map, including any other, unexplored, continents; this is especially problematic if one builds the Mausoleum of Halicarnassus (increases multiple yield types when WLTKD is active; yes, it does give WLTKD but only for a short time).
Artificially inducing WLTKD only becomes possible in the Medieval Era with Circus, and Great Merchants typically also don't spawn before late Classical at the earliest. Because of this I've often had the situation where I couldn't fulfill a City's demand for 100+ turns (on Epic, at least), which means I lose a huge amount of yields just because I got unlucky.
It should also be mentioned that it isn't exactly logical for citizens to demand something they never could have heard of (if the Luxury only exists on an unexplored continent, for example)...after all, they will only demand things that are part of the map and not other Luxuries; before the map is explored, however, it's like Luxuries from other continents don't exist yet, either, from the viewpoint of those people, so they shouldn't be demanded, either.

So it would be nice to change the mechanics such that only Luxuries, which are possessed by Civs or City States that player has met or are on a tile that has been explored by the player, can be demanded.

**Comment by HeathcliffWarriors** [comment]
Makes sense to me.

**Comment by Edaka** [comment]
If I could just piggy back on this: I know work has been done recently to make cities not demand luxuries that have been banned by the world congress (thanks @HeathcliffWarriors !) but unfortunately it only seems to work retrospectively and not prospectively. That means that if my cities had already demanded a certain resource and then it was banned, they won't reset, which can be a major annoyance requiring a great merchant to be solved. Is it possible and not too performance taxing to run a check for all cities if a luxury ban has just been passed and reset the demanded resource for those demanding the now banned one that is practically impossible to get?
