### ISSUE TITLE
12/1 - Can't determine where this misc combat bonus is coming from.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5974]
_1. Mod version (i.e Date - 4/23):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I know I've asked about these bonuses a lot lately, I'm just still struggling to see where all the bonuses are coming from.

In this example, the foreign legion has a +90% misc bonus. I count:

1) +40% promotions
2) +10% morale (I don't actually see a morale promotion but I'll go with it)
3) +10% from honor tree.
4) +20% in foreign lands

There is an extra +10% I can't account for. Anyone know what bonus that would be?

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/70867922-923c1300-1f40-11ea-8f6c-b5444d5b8004.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by UndeadDevel** [comment]
Morale and the Honor policy bonus would be shown in his panel, so it's actually 30% you're missing here...maybe he gets anti-warmonger fervor, too?

**Comment by Aqinu** [comment]
Find the file **EnemyUnitPanel.lua** in the VP Mod Folder, open it and find and replace all instances **local maxBonusDisplay = 4** with **local maxBonusDisplay = 100**, save the file then reload the game and look at the promotions. (if doesn't work delete **cache** folder also)
