### ISSUE TITLE
How to get better log files?

### ISSUE THREAD

**Issue by ASCII-Guy** [LoneGazebo/Community-Patch-DLL#5975]
I've seen other bug reports with more log files than my own.
I ran an AI test for a good amount of turns, here is the result: 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3965499/Logs.zip)

Here is my config.ini file:
[config.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3965500/config.zip)

**Comment by HeathcliffWarriors** [comment]
https://forums.civfanatics.com/threads/new-beta-version-november-8th.651590/page-16#post-15599213

**Comment by ASCII-Guy** [comment]
Thanks.
