### ISSUE TITLE
Nuclear Missle and War Weariness

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#5976]
_1. Mod version (i.e Date - 4/23):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Nuclear Missiles and Atomic Bombs don't have their cost increased as you accumulate War Weariness.  While my Military Units have a +40% increase to their Costs, Nuclear Missiles stayed at 7000 (standard speed.).

**Comment by LoneGazebo** [comment]
Yep, because they don't consume supply.
