### ISSUE TITLE
The AI builds questionable disjointed cities in really bold locations

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#5978]
_1. Mod version (i.e Date - 4/23):_
12/1

Lately I've been observing city placements like these:

![Inked20191216192824_1_LI](https://user-images.githubusercontent.com/12978597/70929169-2094bf80-203b-11ea-9205-70108ca49e50.jpg)
![Inked20191216192830_1_LI](https://user-images.githubusercontent.com/12978597/70929170-2094bf80-203b-11ea-9ff7-96c2928ba93d.jpg)

As you can see, those cities are completely cut off from the AI's empire which could work for island cities, but not like this. These are extremely vulnerable to invasion, are very hard to connect and probably generate border dispute levels that I can only imagine.

**Comment by ilteroi** [comment]
where do you get those city names?

anyway, there haven't been any changes lately, so i would chalk it up to randomness but i agree there's potential for improvement.

**Comment by HeathcliffWarriors** [comment]
Don't the Huns borrow city names from other ingame civs?

**Comment by bigcat88** [comment]
I like those cities placement, btw.

**Comment by Stalker012345** [comment]
I see this type of placement in a lot of my games as well. I guess the question is, is the AI finding those of value? If they put it in the right stop it can be incredibly difficult to take, so if they are getting good yields maybe its worth it.

**Comment by Edaka** [comment]
Re: city names: I'm using the Hunnic City Names mod, as well as Randomise City names, which randomises their order.

By the way, note the Polish city on the second screenshot as well. It blended so well with Austria that even I myself didn't notice that Ruda Slaska there.

Re: yields: Sultantepe and Egerseg have neither bonus, nor luxury resources. Ruda Slaska has just stone. Only Egerseg is coastal, others are landlocked, which diminishes their value. 

I agree that if a city is easily defensible, there's sone value in it, but first of all, these particular citues aren't exactly fortresses (Attile ended up chopping all the rainforest). Secondly, with the amount of tiles those cities even have there's no way they're generating a good amount of yields.

I had better examples from a previous game. Unfortunately, I didn't take screenshots, but the gist is that Harald Bluetooth had a peninsula to himself, but then he decided to skip over his neighbour and settle between him and another AI, sandwiching himself inbetween. When he rventually got declared war on, those sandwiched cities crumbled very quickly.

**Comment by ilteroi** [comment]
AI should be more careful now
