### ISSUE TITLE
12/1 - Can't settle in a legal spot

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#5979]
_1. Mod version (i.e Date - 4/23):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
As far as I can tell, this settler is 4 tiles away from every other city. Also, I have confirmed that there are other spots it can settle on, so its not the case that I can't settle at all. Is there other criteria that prevents the settler from founding?

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/70949261-f6cf9e80-2022-11ea-8983-0a9a1fbb5b0f.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Can't settle directly on borders.

**Comment by Stalker012345** [comment]
ah! I forgot that also applies to CS, I thought it was only other AIs.
