### ISSUE TITLE
Extremely annoying Barbarian Hand-Axe animation bug

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5980]
So I've been meaning to report this for a while but I keep forgetting...this bug frustrates me to the point where I always enable Quick Combat for Barbarians :)

There's a bug when Barbarian Hand-Axes are attacking a city; rather than animating bolts of fire and striking the city, they continuously swing in place as if trying to do that animation (repeating the sound effect with every attempt), and repeat this process for about 15-20 seconds before the game eventually kills the animation and moves on.

I can't remember, but I think this might also apply to Hand-Axe attacks on normal units. The bug doesn't _always_ happen, but when it does, it's a PITA.

Any way to fix this?

**Comment by LoneGazebo** [comment]
Can't, nope.
