### ISSUE TITLE
Debugging help (CTD)

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#5984]
So I'm attempting to debug the mod to figure out the cause of a CTD upon loading a saved game (Iamblichos thinks I made a typo somewhere when adding new memory values to the diplomacy AI, although there are no build errors). I can confirm the CTD does happen, though I'm not sure why.

I'm following the instructions under "How do I debug this". Upon loading the mod, attaching to process, and starting the game, I encountered this error (there was a popup as well, but I didn't get a screenshot of it). Not sure how to proceed.

I'm using VS 2008 Express (SP 1) + VS 2010 (SP 1) + VS 2019, installed in that order.

![Screenshot (21036)](https://user-images.githubusercontent.com/38794241/71138256-dcd7bc80-21d8-11ea-932c-62bd9941d5e4.png)

**Comment by Iamblichos** [comment]
I know it's definitely in CvDimplomacyAI as I isolated it to that by using 12-1 releases version for that .cpp alone (and revertingthe code to wherever else the new functions were called) all the other new code is the same with the current repository.

I've been trying to figure out which kstream variable that you added is causing the game to crash, but so far no dice.

**Comment by HeathcliffWarriors** [comment]
Okay, so I tried again (HungryForFood advised that I should try without copying over the generated PDB file, but only using the debug DLL) and got this error upon trying to load a savegame:

![b5a02722235117a115264450824dc31d](https://user-images.githubusercontent.com/38794241/71141036-f54bd500-21e0-11ea-8997-a629c1f63fce.png)

**Comment by Iamblichos** [comment]
right click, Open with Visual Studio whichever version you are using. Point your symbol path to the folder that you are using in your current build.

**Comment by HeathcliffWarriors** [comment]
I opened it in VS 2019, clicked on "Set symbol paths", set it to the MODS > (1) Community Patch folder. Not sure how to proceed.

**Comment by HeathcliffWarriors** [comment]
Clicking on "Debug with native only" shows an error in this function.

![f2b44f920810cbd11a5bc6c6c902b613](https://user-images.githubusercontent.com/38794241/71142038-224db700-21e4-11ea-9996-8cd61d7722ff.png)

**Comment by Iamblichos** [comment]
No, it needs to point to the .pdb file that was created when you built the DLL. For example for a Release version, mine is in Documents\Visual Studio 2017\Projects\CivReloaded\BuildOutput\Release

Once you do that hit the Debug with Native Only Action link, and then you'll be able to view the content.

**Comment by HeathcliffWarriors** [comment]
Ahhhh, okay.

**Comment by Iamblichos** [comment]
Check your call stack, you'll see that there is a kstream issue in CvPlayerAI, nobody has done changes there is recent, but it'll call the diplomacy stuff during turns.

**Comment by HeathcliffWarriors** [comment]
![a6d901eb9ea3a85d0af776623e47f2e0](https://user-images.githubusercontent.com/38794241/71142185-a1db8600-21e4-11ea-8840-f18838952d7f.png)

Hmm, I see now. Very unhelpful.

**Comment by HeathcliffWarriors** [comment]
The most likely suspect are the OtherPlayerMajorCivApproach and OtherPlayerMajorCivApproachCounter variables, as being a 2D array they were the most complicated.

**Comment by HeathcliffWarriors** [comment]
Nope, doesn't seem to be those, I tried deleting them and recompiling.

**Comment by HeathcliffWarriors** [comment]
I guess I'll remove them one by one to see if I can find the problem. What a pain!

**Comment by HeathcliffWarriors** [comment]
OpinionTowardsUsGuess
NumWarsDeclaredOnUs
NumCitiesCaptured
OtherPlayerMajorCivApproach
OtherPlayerMajorCivApproachCounter
DemandAcceptedWhenVassal
BrokenVassalAgreementTurn
WantsDoFWithPlayer
EverBackstabbedBy
DoFBrokenTurn
FriendDenouncedUsTurn
FriendDeclaredWarOnUsTurn

These were the added variables.

**Comment by ilteroi** [comment]
do a binary search, don't need to test them one by one.

otherwise yea, serialization is a pain.

there also seem to be some undefined differences between release build saves and debug build saves that can cause crashes if you eg load a release save with a debug dll. i never got to the bottom of that

**Comment by HeathcliffWarriors** [comment]
@ilteroi How does one do a binary search?

**Comment by ilteroi** [comment]
ah, nothing fancy. just divide the set into two halves. omit one half. test. then you know which half causes the error. repeat.

**Comment by HeathcliffWarriors** [comment]
Ah. Logical.

**Comment by HeathcliffWarriors** [comment]
Found the CTD bug! :)

The problematic variable was NumCitiesCaptured; it was writing MAX_MAJOR_CIVS instead of MAX_CIV_PLAYERS by mistake.

Fixed and tested, no more CTDs upon loading a savegame.

Thanks @Iamblichos and @ilteroi for helping me find the problem.

**Comment by LoneGazebo** [comment]
And I helped (I did not help)

**Comment by Iamblichos** [comment]
@HeathcliffWarriors good job!
