### ISSUE TITLE
Celts receiving foreign religious pressure in capital

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#5987]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2)
UI - Religion Spread (Vox Populi) (v 1.1)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
I'm playing as the Celts, who aren't supposed to give or receive religious pressure (except internally from the Celtic Religion), but as you can see in the screenshots I am receiving such pressure (and quite a large amount) in my Holy City / capital.
This can't be from TRs (see screenshot 2) as the only City I'm trading with that has Catholicism is Honululu and they are trading with Truro only. There are some Catholic followers in my Cities but they don't generate pressure in any of my other Cities, only in the capital...even when my other Cities flip to some foreign Religion they still don't generate pressure for that Religion (as expected), so the problem is only with the capital.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Celts_Religious_pressure](https://user-images.githubusercontent.com/30495439/71159975-9c128e80-223e-11ea-9303-3c68340cfdff.jpg)
![Celts_Religious_pressure2](https://user-images.githubusercontent.com/30495439/71160048-c1070180-223e-11ea-808a-d50c79d0a723.jpg)

**Comment by UndeadDevel** [comment]
Some turns later, when I purposefully converted Dublin to another Religion (to buy their religious building, a Church, to fix the WLTKD bug I reported in the other issue), the religious pressure in my capital seized, but now it exists in Dublin...some of my other Cities have followers of foreign religions, as well, but without any pressure, so it seems it's always just one City that can exhibit this phenomenon:
![Celts_Religious_pressure3](https://user-images.githubusercontent.com/30495439/71246513-b4ea7500-230e-11ea-8cf0-26d1fdc2f8d7.jpg)

**Comment by LoneGazebo** [comment]
I tried to replicate but could not do so. 

G

**Comment by UndeadDevel** [comment]
Want a save and my MODS folder?
