### ISSUE TITLE
Freshly met City-States start as friends with maxed Patronage

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#599]
![8930_2015-09-06_00005](https://cloud.githubusercontent.com/assets/1131228/9704121/5fb67282-54b4-11e5-82fc-e05ac8db7bf8.png)
![8930_2015-09-06_00006](https://cloud.githubusercontent.com/assets/1131228/9704122/6427bfc4-54b4-11e5-85b2-26b1e076a8b8.png)

**Comment by Radost** [comment]
Moreover, city-states have a resting point of 45
![8930_2015-09-06_00008](https://cloud.githubusercontent.com/assets/1131228/9704476/dee92470-54c1-11e5-98b7-53b6c13cc400.png)

**Comment by Hokath** [comment]
This has always been the case, I believe.

**Comment by LoneGazebo** [comment]
Depends on what sets of policies/beliefs you take, yep.
G

**Comment by Radost** [comment]
Beliefs on a non-religious city?

**Comment by LoneGazebo** [comment]
the / indicates either or. As in either/or.
G

**Comment by Radost** [comment]
As I've said, I only maxed Patronage (which gives 20 points) and nothing else related to resting points.

**Comment by LoneGazebo** [comment]
Fixed the XML bugs, and I've changed the DLL so that influence will stay at zero if you haven't met the CS (what was happening is that, every turn, unmet CS base values were rising. This was a vanilla feature, but it is somewhat silly).
