### ISSUE TITLE
Trade logic

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#5991]
Current unreleased trade code:
@HeathcliffWarriors et al.

Something wrong with trade logic for getting a competitors Embassy. This is early game where there shouldn't be any diplomatic hits.

![image](https://user-images.githubusercontent.com/14372214/71195327-4e545100-2253-11ea-82c6-0e6f1284f7e4.png)

**Comment by LoneGazebo** [comment]
If he doesn't trust you, he won't show you his capital.

**Comment by Iamblichos** [comment]
Yeah? But I couldn't get one Embassy...not even one. All of 'em were like this. I do war early. So does that set everyone into the negative?

**Comment by HeathcliffWarriors** [comment]
@Iamblichos Could you post a savegame?

**Comment by Iamblichos** [comment]
Nah, this is all the base stuff man, no squirrely situation. Just start a game in the classical era and try to get an embassy from the first person you meet. Easy to reproduce.

**Comment by HeathcliffWarriors** [comment]
I'll add a new logfile to my build and try that, then.

**Comment by HeathcliffWarriors** [comment]
Seems there's a problem with the approach guess function. I'll investigate and post a fix.

**Comment by Iamblichos** [comment]
Thanks.

To me this looks backwards:

`for (iPlayerLoop = 0; iPlayerLoop < MAX_MAJOR_CIVS; iPlayerLoop++)
		{
			eLoopPlayer = (PlayerTypes) iPlayerLoop;
			
			if (GET_PLAYER(eLoopPlayer).getTeam() == GET_PLAYER(eOtherPlayer).getTeam())
			{
				if (GetPlayer()->GetDiplomacyAI()->IsUntrustworthyFriend(eLoopPlayer) || GetPlayer()->GetDiplomacyAI()->GetTrueApproachTowardsUsGuess(eLoopPlayer) <= MAJOR_CIV_APPROACH_HOSTILE)
				{
					return INT_MAX;
				}
				
				for (iTeammateLoop = 0; iTeammateLoop < MAX_MAJOR_CIVS; iTeammateLoop++)
				{
					eTeammate = (PlayerTypes) iTeammateLoop;
					
					if (GET_PLAYER(eTeammate).GetDiplomacyAI()->IsUntrustworthyFriend(eLoopPlayer) || GET_PLAYER(eTeammate).GetDiplomacyAI()->GetTrueApproachTowardsUsGuess(eLoopPlayer) <= MAJOR_CIV_APPROACH_HOSTILE)
					{
						return INT_MAX;
					}
				}
			}
		}`

**Comment by Iamblichos** [comment]
if a player is less than or equal to hostile return INT_MAX

**Comment by HeathcliffWarriors** [comment]
The function seems to be returning no value, hence it will always be less than or equal to HOSTILE.

**Comment by HeathcliffWarriors** [comment]
Adding logging shows this result for all civs:
![cabad95cdc68f59e3cb5db76d0966ff2](https://user-images.githubusercontent.com/38794241/71203413-e827f800-226b-11ea-8bb0-aad81d05b55f.png)

**Comment by LoneGazebo** [comment]
if (GET_PLAYER(eLoopPlayer).getTeam() == GET_PLAYER(eOtherPlayer).getTeam())
	
shouldn't that be !=
??

**Comment by Iamblichos** [comment]
It's definitely just that part of the function above as this was the new addition to CvDealAI. Might be an issue of how you are looping through teams.

**Comment by LoneGazebo** [comment]
in fact that whole code seems sketch - the TEAM loop should always be on the outside of the player loop, as it is a 'higher' function. So it should be a team loop, and then inside of that you check players to see if they're on that team.

**Comment by LoneGazebo** [comment]
In some you do a loop to check all other players regardless of team affiliation, so other players are affecting the approach/diplo attitude of each player. Not good.

**Comment by Iamblichos** [comment]
definitely the way the loop is constructed because if you just check it to the player without looping:

```
if (GetPlayer()->GetDiplomacyAI()->GetTrueApproachTowardsUsGuess(eOtherPlayer) == MAJOR_CIV_APPROACH_HOSTILE)
		{
			return INT_MAX;
		}
```

everything is fine.

**Comment by HeathcliffWarriors** [comment]
Oops, looks like I goofed up there. :)

I'm having some clientside issues preventing me from debugging it, so I'll just remove that code for now.

**Comment by Iamblichos** [comment]
You could use your function if you just want to check it to that player (as I suggested above). That works for now. And do the rest TBD later.

**Comment by LoneGazebo** [comment]
Yeah. And TBH you really don't need team checks there because you're not passing a team. Don't worry about teams unless a team was passed into the function explicitly.

**Comment by HeathcliffWarriors** [comment]
I'll just comment out/remove buggy functionality for now, and debug next version - my database is broken which is making testing difficult.

**Comment by LoneGazebo** [comment]
re: database, check your database.log

**Comment by HeathcliffWarriors** [comment]
#5992, this should fix this and other potential bugs. Figures there'd be a problem _somewhere_, but at least it's relatively minor. I'll fix next version.

**Comment by HeathcliffWarriors** [comment]
Heh, I can see where you were coming from when you said you didn't want to go down the rabbithole of fixing teammate logic :)

**Comment by HeathcliffWarriors** [comment]
I think I'll just add a new function for a trustworthiness check rather than copying and pasting; seems less prone to problems.

Note to self: Avoid rushing with new code...
