### ISSUE TITLE
cannot make peace despite warscore 100

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#5995]
i conquered assyria's capital, i have warscore 100, but i haven't been able to make peace for at least 10 turns. what's up? is this a known bug?

**Comment by UndeadDevel** [comment]
If you made great gains in a short time in your conquest, especially when conquering the Holy City or Capital as part of those gains, the AI is supposed to be reluctant to make peace at first, but more than 10 turns does sound like more than I usually see.

**Comment by ilteroi** [comment]
that's why i mentioned that part.

but just now i noticed they apparently are a voluntary vassal of rome.

shouldn't this somehow be apparent from the dialogue text?

**Comment by HeathcliffWarriors** [comment]
Vassals are never willing to make peace if their master is at war, but while several things can block peace, the AI's dialogue doesn't make it clear.

**Comment by ilteroi** [comment]
can we simply disable the button?

**Comment by HeathcliffWarriors** [comment]
I don't see why not.
