### ISSUE TITLE
City religion lost upon reloading

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#600]
This is what it looks like on the same turn the game was loaded:
![8930_2015-09-06_00011](https://cloud.githubusercontent.com/assets/1131228/9704525/e3014c2a-54c3-11e5-803c-2e9f4f833a29.png)
Then on the next turn: 
![8930_2015-09-06_00012](https://cloud.githubusercontent.com/assets/1131228/9704526/f8facb78-54c3-11e5-8534-85316fa0a2a7.png)

**Comment by Vastator** [comment]
I have the same problem. Maybe it's only a ui bug.
