### ISSUE TITLE
Purchasing spaceship parts with gold (freedom tenet) does nothing.

### ISSUE THREAD

**Issue by Rand0miz3d** [LoneGazebo/Community-Patch-DLL#6000]
When I purchase a spaceship part I lose the gold, I get an instant yield for purchasing, but no spaceship part appears and it doesn't halve the time to build it either.

**Comment by LoneGazebo** [comment]
On VP? It invests in the SS part.

G

**Comment by Rand0miz3d** [comment]
It does not appear to be investing either (the turns to build doesn't change), unless I'm severely missing something.

I am on VP (EUI version) with no other mods. I also did a reinstall and played a whole new game I still have the same issue. 

I made a gif of the problem: https://imgur.com/a/8ZspkB4.

**Comment by Aqinu** [comment]
I've tried with VP 12-20-3 and it works correctly, try to install this one and see if its fixed.

**Comment by Rand0miz3d** [comment]
Cool, I'll try it in a few days, currently away for Christmas.

**Comment by Rand0miz3d** [comment]
Yes it does indeed appear to be fixed in 12-20-3.
