### ISSUE TITLE
Many build/merge errors

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6002]
The latest build in the repository is filled with merge errors. Most of them are of the
```
<<<<<<<<<< HEAD
(code)
==============
(different code)
>>>>>>>>>>> (commit number)
```
variety, but others feature duplication of code where the same lines are entered twice.

This also happened last time.

There's many of them scattered throughout the repository files that were changed during the update - please fix? @LoneGazebo

**Comment by LoneGazebo** [comment]
Weird. I’ll look.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Well, your latest hotfix fixed the build errors, but it also eliminated a number of my diplo changes (database ones in particular) from the repository and the version on the forums, which I presume was not the intention. :)

I'll use WinMerge to fix the missing changes and send a pull request within a couple hours; would you mind merging and posting another hotfix?

**Comment by ASCII-Guy** [comment]
Those are called conflict markers. Git creates them when it can't automatically merge.

**Comment by LoneGazebo** [comment]
Hmm. Merge should be the same. Don’t know why it dropped your content. 12-2 is savegame compatible.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Ah, I figured out the issue. So your merge error fix seems to have worked correctly for most of the DLL code but it dropped SQL file changes. I'll send a pull request for those now.

**Comment by LoneGazebo** [comment]
Aha I see the issue, you didn't add the SQL updates to the OnModActivated queue for CP so they weren't being picked up by my merge tool. Fixed.

**Comment by HeathcliffWarriors** [comment]
Ah, okay. I've also noticed just now that the opinion weight changes don't seem to be applied correctly ingame; would that be why?

**Comment by HeathcliffWarriors** [comment]
If there's a file that needs to be changed so that the three diplo files I added are included in the database, would you mind doing that, or pointing me in the right direction? :)

**Comment by HeathcliffWarriors** [comment]
...and another hotfix would be appreciated, if possible.

**Comment by LoneGazebo** [comment]
I'll do it. For the future if you add a file to the CP/CBO you have to register it in the modinfo file.

**Comment by HeathcliffWarriors** [comment]
I'll remember that. Thank you!
