### ISSUE TITLE
Defensive Pact text errors

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6003]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2)
UI - Religion Spread (Vox Populi) (v 1.1)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
This was supposed to have been fixed already last year with #4998, but maybe the incorrect info was only removed in the civilopedia, not in the trade window.
There seem to be two issues:
1. The trade window tool tip incorrectly states "NOTE: If either player declares war the agreement is cancelled."; that part should simply be removed.
2. In the civilopedia entry there may be an error regarding the duration of a DP: it says "A Defensive Pact lasts for 30 turns (on standard speed)."; I'm playing on Epic and it is 70 turns there...I know that it would be shorter on standard but I have a feeling that it may be more than 30 turns (not sure, though).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
If either player declares war on each other, the agreement is cancelled, I think that's what is meant.

**Comment by UndeadDevel** [comment]
I don't think this text was changed since the mechanics were changed so DPs don't get cancelled on DoW, though, so it clearly used to mean something else and now it is very ambiguous...the meaning that a new player would be most likely to derive from it would be that the DP gets cancelled if he or the other player declare war (that's literally what it says, after all). For Open Borders and Embassies there is no such note, either, despite those getting cancelled when declaring on the other....so I really think it would improve things to remove that part.

**Comment by HeathcliffWarriors** [comment]
Fair point.

**Comment by HeathcliffWarriors** [comment]
Fixed.
