### ISSUE TITLE
Upload code latest version

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6008]
_1. Mod version (i.e Date - 4/23): 12/20

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: When you can, upload the latest version changes... 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
@Aqinu This was already done.

**Comment by Aqinu** [comment]
Maybe you are right, but no the files that I want to make small fixes, which are clearly from previous versions...

**Comment by Aqinu** [comment]
This one I have trouble with which is not updated **(3) CSD for CBP/World Congress/Projects.xml**

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo
