### ISSUE TITLE
In strategic view the health of cities appears near 0 when it is actually at ~40%

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#601]
Just noticed this playing on my clunky old laptop. Don't know if this is a default problem, but thought I would mention it.

**Comment by TechpriestEnginseer** [comment]
It's a vanilla problem when the health of cities exceed the graphical amount of which the city displays the health. I've encountered this without CP.

**Comment by LoneGazebo** [comment]
can't fix. Is a UI engine bug.
