### ISSUE TITLE
Crash When Portugal's Turn Is Processed

### ISSUE THREAD

**Issue by ASCII-Guy** [LoneGazebo/Community-Patch-DLL#6011]
_1. Mod version (i.e Date - 4/23):_
**10-23**

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This crash caused Martin Fencka's India let's play to be cut short. It occurs consistently on turn 490 when Portugal's turn is processed. Here's the timestamp on the video: https://youtu.be/-SKndz19Jhc?t=2237

_4. Steps to reproduce (optional):_
Process AI on turn 490.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):  I asked for them. Will update this report if I receive them.

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3995983/Saves.zip)
These saves were provided by Martin when I asked for them.

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): I asked for it. Will update this report if I receive it.

4. Screenshots (optional):
![Screenshot](https://user-images.githubusercontent.com/14044545/71376363-00528c80-2576-11ea-8b13-77574b902b0a.png)

**Comment by ASCII-Guy** [comment]
I'm going to go ahead and run the save file myself to grab some log files as well as the CvMiniDump.dmp

**Comment by ASCII-Guy** [comment]
Alright, here's Martin's logs folder and his CvMiniDump.dmp. I'll make my own log files as well as it doesn't include AI logs, ect.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3996133/Logs.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3996134/CvMiniDump.zip)

**Comment by ASCII-Guy** [comment]
Here's the 10/23 installer:
https://forums.civfanatics.com/threads/new-beta-version-october-23rd-10-23.651049/page-15#post-15625198

**Comment by HeathcliffWarriors** [comment]
If you're debugging old versions, be mindful that the CTD may have already been fixed.

**Comment by ASCII-Guy** [comment]
Yeah, I thinking it may have been but it is a real shame.
