### ISSUE TITLE
Sacred Sites does not give tourism on Hermitage or Hotels

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#6012]
_1. Mod version (i.e Date - 4/23):_
12/20-3

_2. Mod list (if using Vox Populi only, leave blank):_
![Capture2](https://user-images.githubusercontent.com/19291347/71388416-40416000-25c6-11ea-9d88-3527dcf1decc.PNG)

_3. Error description:_ 
Sacred Sites reformation belief does not give tourism on Hermitage or Hotels.

**Comment by LoneGazebo** [comment]
You certain the religion was the majority in all cities?

**Comment by jimmymcperson** [comment]
Yep, was playing Spain.

**Comment by LoneGazebo** [comment]
evidence it wasn't working?

**Comment by jimmymcperson** [comment]
![Capture](https://user-images.githubusercontent.com/19291347/71790815-66242700-3000-11ea-8e15-0b0c2939056f.PNG)

Here you can see faith buildings giving tourism, but not Hermitage.

**Comment by jimmymcperson** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4024450/Logs.zip)
