### ISSUE TITLE
Late Game CTD

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#6013]
_1. Mod version (i.e Date - 4/23):_
12/20-3

_2. Mod list (if using Vox Populi only, leave blank):_
![Capture2](https://user-images.githubusercontent.com/19291347/71397354-544b8880-25eb-11ea-82a3-b9b7db940ef2.PNG)

Also changed some DiploAIOptions:

DIPLO_AI_SHOW_TRUE_APPROACHES to 1
DIPLO_AI_NO_VICTORY_COMPETITION to 1

_3. Error description:_ 
CTD when mousing over Brazil to see diplo mods.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3997379/Logs.zip)

**Comment by HeathcliffWarriors** [comment]
@jimmymcperson Did you succeed in seeing the AI's true approaches with SHOW_TRUE_APPROACHES enabled, by the way?

**Comment by jimmymcperson** [comment]
SHOW_TRUE_APPROACHES worked just fine (changed it mid-game).

When togged back off the crash still happens.

The CvMiniDump file isn't where it's supposed to be.  I have a batch file that usually zips everything for me so I never noticed when it disappeared.  Any way I can get it back?

**Comment by bigcat88** [comment]
CvMiniDump generates after crash. Default near civ5.exe (so it is not in documents folder)

**Comment by jimmymcperson** [comment]
Mid-game crash this time in a different game, same symptoms.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4004258/Logs.zip)

This time it's Indonesia.  CvMiniDmp still isn't generating, not sure why.

**Comment by jimmymcperson** [comment]
The second game's crash was using 12/24 build.

**Comment by jimmymcperson** [comment]
The hotfix fixes both crashes, nice job!
