### ISSUE TITLE
GDR promotion is named 'Titanic'

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6014]
Rather than Titan. Struck me as a possible typo. Intentional?

**Comment by UndeadDevel** [comment]
Let's hope no GDR ever sinks or we'll never hear the end of it 🤣

**Comment by LoneGazebo** [comment]
Intended. ‘Titanic’ is the adjectival form of titan

**Comment by HeathcliffWarriors** [comment]
Ah, ok. Changelog said Titan so I thought to confirm.
