### ISSUE TITLE
Nitpick: make the Boarded Combat Info only take up one line and fit the conventional notation

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6018]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2)
UI - Religion Spread (Vox Populi) (v 1.1)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
The Boarded Combat Info needlessly takes up two lines...it looks to me that there's plenty of space to fit this on one line...it would also be nice if this followed the notation that the other combat info lines use, namely having the three components (info text, colon, number) arranged in a specific order depending on which side of the Combat Info window they're at (for the left side the order described and for the right side reversed)...see screenshots.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Boarded_nitpick1](https://user-images.githubusercontent.com/30495439/71415845-b5a84180-2655-11ea-95c2-97ed5c190c3c.jpg)
![Boarded_nitpick2](https://user-images.githubusercontent.com/30495439/71415848-bb9e2280-2655-11ea-8fdb-9fb115e64bd0.jpg)

**Comment by LoneGazebo** [comment]
Dialog won’t fit on one line as is.

**Comment by UndeadDevel** [comment]
Are you sure? In the screenshots it looks like it would fit with room to spare...or is the issue that it's impossible to put the "chance" number where the other percent modifiers are shown for the combat modifiers?

**Comment by Aqinu** [comment]
There are two types of these bonuses in combat panel:
1. with modifier numbers (with +- percent numbers)
2. info messages (boarded, ignore zoc, intercepting..., ), which are fully displayed in text column, and with nothing in numbers column...

Possible solution: change that string with **Boarded(II) Chance: 100%**, so that fits in one row, which will let one more bonus to be displayed, thing which I can do if @LoneGazebo gives the approval...

**Comment by UndeadDevel** [comment]
Thanks, @Aqinu, it is as I thought, then; I was hoping that it's possible to add some sort of exception to that code so that for boarded status messages the "100%" can be displayed in the numbers column but maybe that's impossible or too much work for such a small polishing action. Anyway, just thought I'd ask about it with this issue; gonna close it now.
