### ISSUE TITLE
Culture on buildings from certain policies isn't shown

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#602]
Culture from Military Tradition and New World Order on affected buildings (barracks, armories, military acadedmies and constabularies), when the policy or the tenet is not taken, are previewed by EUI: 
![culture4](https://cloud.githubusercontent.com/assets/12978597/9706845/a7468734-54fc-11e5-8d0e-a8b25ab82540.jpg)
However, upon adopting the policy and/or the tenet, the culture bonus is no longer shown:
![culture1](https://cloud.githubusercontent.com/assets/12978597/9706853/e6a6789e-54fc-11e5-99c0-c575c32aac96.jpg)
![culture2](https://cloud.githubusercontent.com/assets/12978597/9706854/e7ae969a-54fc-11e5-9c66-bc4e91c94568.jpg)

Also, somewhat related: additional hammers on barracks, forge and armory from colloseum aren't shown. These, however, aren't previewed by the EUI, either.

**Comment by LoneGazebo** [comment]
Intentional, as that data is only loaded once the building is constructed (because of how the policy is handled at the DLL level, it requires the 'city' element to work).

G
