### ISSUE TITLE
Diplomatic Malus for "We helped relocate the World Congress to their lands"

### ISSUE THREAD

**Issue by TranceBlossom** [LoneGazebo/Community-Patch-DLL#6020]
_1. Mod version (i.e Date - 4/23):_
12/20

_2. Mod list (if using Vox Populi only, leave blank):_
ui: city state leaders
ui: meaningful colours
ui: filters in trade route overview
ui: religion spread
My Spanish Inquisition spain rework
Autoproduction CIties

_3. Error description:_ 
I have a negative 20 diplo modifier with Austria for voting for them to lead the world congress

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3998684/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/3998686/QuickSave.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20191224230254_1](https://user-images.githubusercontent.com/47022053/71419304-1bc2b200-26b2-11ea-8394-425672b765b1.jpg)

**Comment by HeathcliffWarriors** [comment]
Whoops, forgot to put a negative sign. :)
