### ISSUE TITLE
Celtic Pantheon (Nuada, the Silver-Handed King) Not Giving Correct Yields

### ISSUE THREAD

**Issue by amateurgamer88** [LoneGazebo/Community-Patch-DLL#6023]
_1. Mod version (i.e Date - 4/23):_

12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_

4UC, a few custom civs

_3. Error description:_ 

The yields I'm getting aren't as advertised by the Pantheon. As seen in the screenshot below, my city is generating 90+ gold so I expect 9 Culture generation from religion. Since I also went for Mendicancy, I should be getting 11 Culture from religion. However, that isn't the case. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![20191221223702_1](https://user-images.githubusercontent.com/48229872/71437793-ff217c80-26a7-11ea-8a57-3bb581be69b1.jpg)

**Comment by LoneGazebo** [comment]
Ah, that's because it's capped at half followers. Will fix tooltip.
