### ISSUE TITLE
Consistent Late Game CTD (12/29 Update: Crash reproduced with no modmods)

### ISSUE THREAD

**Issue by TranceBlossom** [LoneGazebo/Community-Patch-DLL#6025]
_1. Mod version (i.e Date - 4/23):_
 12-24-3 w/ HeathCliffWarriors's DLL

_2. Mod list (if using Vox Populi only, leave blank):_
ui: city state leaders
ui: meaningful colours
ui: filters in trade route overview
ui: religion spread
My Spanish Inquisition spain rework
Autoproduction Cities

_3. Error description:_ 
Game crashes on the same turn every time

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4001243/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4001239/QuickSave.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4001236/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by TranceBlossom** [comment]
I'm fairly certain the crashdump is from a tech screen crash, because that's when it last updated. However, I'm experiencing a consistent crash at the very end of the barbarians move on turn 386, right before it should become my turn. I looked at the logs but didn't see anything out of place for them, but even if I restart from several moves before, it consistently happens that turn.

**Comment by CyberPhy** [comment]
I am having almost the same problem but every-time I start to load the game from a save it crashes, with no mini dump.
I can load a auto save from the previous turn and it works until i hit next turn

**Comment by TranceBlossom** [comment]
I tried removing HCW's DLL, I went back to my oldest autosave (16 turns before) and let the AI autoplay, and even with that it still crashed on the exact same turn.

**Comment by CyberPhy** [comment]
> I tried removing HCW's DLL, I went back to my oldest autosave (13 turns before) and let the AI autoplay, and even with that it still crashed on the exact same turn.

lol yep I did that same thing.
I will probably go back to the last version as this one seems to just keep crashing

**Comment by TranceBlossom** [comment]
I played an AI-only game with just the CBP mods and sure enough am getting another repeatable late-game CTD on turn 389.

1. Mod version (i.e Date - 4/23):
12-24-3

2. Mod list (if using Vox Populi only, leave blank):

3. Error description:
Game crashes on the same turn every time

4. Steps to reproduce (optional):

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4007724/Logs.zip)


Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4007725/QuickSave.zip)


CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4007723/CvMiniDump.zip)
^ The crash does NOT seem to be updating the mini dump file, this file was last modified yesterday according to Windows.

Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
Well, it's not the 12-24 build I posted that's responsible, then.

I have no idea what _is_ causing it, though.

**Comment by TranceBlossom** [comment]
Fixed with 12-30 DLL
