### ISSUE TITLE
Wat description is missing crime reduction value

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#603]
The description states that the building reduces crime, but no percentual value is shown.
![watpreview](https://cloud.githubusercontent.com/assets/12978597/9706870/b8e6dbb4-54fd-11e5-89b2-f8f2c3aefcc7.jpg)

**Comment by LoneGazebo** [comment]
Do any of the other reducers have it? May just be an EUI leaderscreen quirk.
G

**Comment by LoneGazebo** [comment]
Can't be avoided in EUI. Sorry.
G
