### ISSUE TITLE
Strategic Monopoly not being achieved despite having more than a quarter of the resource

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6030]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2)
UI - Religion Spread (Vox Populi) (v 1.1)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
See screenshots; I have one more than a quarter (32 of 124) Iron but getting no Iron Strategic Monopoly...at a later turn I even had 33 of 124 (at this point the Monopoly screen showed 26% for me) but also still no Strategic Monopoly. Do note that I'm getting part of my Iron from Zealotry...does this not count for Monopolies? Also, the two Iron from Ironworks are not marked in green color...maybe that's what's not being counted?

**[See solution at the bottom](https://github.com/LoneGazebo/Community-Patch-DLL/issues/6030#issuecomment-573360897)**

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![SRMonopoly1](https://user-images.githubusercontent.com/30495439/71516963-c4843380-28a3-11ea-97c5-c3160fa7bd4b.jpg)
![SRMonopoly2](https://user-images.githubusercontent.com/30495439/71516969-d2d24f80-28a3-11ea-91ca-30906f1ffab0.jpg)

**Comment by UndeadDevel** [comment]
At 34 Iron I finally received the SM...so it looks like it might be the Ironworks (+2 Iron) that don't count for Monopolies? 34 is two Iron more than I would need to have more than 25% of the Iron on the map, according to the Monopolies screen.

If so, is this intended?

**Comment by corona88** [comment]
Need 26% and 51% for monopolies
32/124=25,8% yes is over 25%, but numbers are rounded. Game counts that as 25% not 26%

-- Monopoly Defines for CBP
INSERT INTO Defines (Name, Value)
SELECT 'GLOBAL_RESOURCE_MONOPOLY_THRESHOLD', '51';

INSERT INTO Defines (Name, Value)
SELECT 'STRATEGIC_RESOURCE_MONOPOLY_THRESHOLD', '26';

**Comment by UndeadDevel** [comment]
Except I had 33/124=26.6% some turns later without receiving the Monopoly, either:
![Mono1](https://user-images.githubusercontent.com/30495439/71560567-cbf23b00-2a63-11ea-92c9-564ad714812c.jpg)
![Mono2](https://user-images.githubusercontent.com/30495439/71560572-d4e30c80-2a63-11ea-8503-949aa0ba062d.jpg)

**Comment by UndeadDevel** [comment]
This could very well be connected to the issue I just referenced above; it may be that solving that issue would solve this one.

**Comment by UndeadDevel** [comment]
I've figured this one out, too:
The error lies in the defines...the Monopoly thresholds are supposed to be defined as 25 and 50, not 26 and 27, because the game wants the floored percentage to be over the threshold ( '>', not '>='), so it needs the player to achieve >= 27% for the Strategic Monopoly currently.

So change the Monopoly defines in the SQL to 25 and 50, which would mean the player needs >= 26 % and >= 51 % for Strategic and Global Monopoly, respectively, which I assume is the intended effect.
