### ISSUE TITLE
Civilized Mission working bugged

### ISSUE THREAD

**Issue by BiteInTheMark** [LoneGazebo/Community-Patch-DLL#6032]
_1. Mod version (i.e Date - 4/23):_
12/20

_2. Mod list (if using Vox Populi only, leave blank):_
-

_3. Error description:_ 
Civilized mission policy from Imperialism branch gives production modifier to buildings, even the courthouse is not build.

_4. Steps to reproduce (optional):_
Get a puppet in game and annex it while having Imperialism branch

**Comment by HeathcliffWarriors** [comment]
Corporate Offices are also considered to be Ancient Era buildings for the purposes of Civilizing Mission.
