### ISSUE TITLE
Crash - Late Game - 5 turns before Cultural Victory :]

### ISSUE THREAD

**Issue by kdm2k6** [LoneGazebo/Community-Patch-DLL#6033]
_1. Mod version (i.e Date - 4/23):_

Latest (December 20 - 3)

_2. Mod list (if using Vox Populi only, leave blank):_

Self made modpack with :
Vox Populi with EUI
Quick Turns
UI - Improved City View (Vox Populi version)

_3. Error description:_ 

The game crashes at the end of the turn (when the Barbarian symbol displays).

_4. Steps to reproduce (optional):_

Simply go to the next turn and the game crashes (tried it several times and it is reproducible on my computer).

Additionally :

1) The MiniDump doesn't seem to be recent so it is likely not from this crash (not sure if something is wrong regarding my setup).
2) I was about 5 turns away from my first attempt at a cultural victory so if there is any way to fix the save (even via deleting civs) I will do it - just let me know :] Thanks

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4007730/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[CRASH Gandhi_0359 AD-1939.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4007731/CRASH.Gandhi_0359.AD-1939.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4007732/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by JohannesGaessler** [comment]
I'm having the same issue as described in the OP.

1.Version:
12-20-3

2. Other Mods:
* Faster Aircraft Animations
* Wonder Race

3. Error Description:
CTD when Barbarian symbol is displayed.
However, the game still creates an autosave for the next turn that can be loaded.
Upon loading the autosave the game crashes after clicking "Continue your journey".
**As with OP no CvMiniDump.dmp file is created upon the game crashing.**

4. Steps to reproduce:
Load the regular save file and click next turn
or
load the autosave file.

[debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4007964/debug.zip)

**Comment by jimmymcperson** [comment]
My first crash #6013 was also exactly 5 turns before culture victory.  Though it was caused by mousing over AI rather than Barbarian's turn.

**Comment by JohannesGaessler** [comment]
The 12-30 fix worked for me.
