### ISSUE TITLE
endless recursion

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6034]
i might have found the reason for the crashes people are reporting.

```
/// Sets if this player declared war on us while we had a DoF
void CvDiplomacyAI::SetFriendDeclaredWarOnUs(PlayerTypes ePlayer, bool bValue)
{
	if (GetPlayer()->isHuman() && GET_PLAYER(ePlayer).isHuman())
		return;

	if (bValue != IsFriendDeclaredWarOnUs(ePlayer))
	{
		m_pabFriendDeclaredWarOnUs[ePlayer] = bValue;
	}
```

unfortunately IsFriendDeclaredWarOnUs() is calling SetFriendDeclaredWarOnUs() again.

this seems to be a recent change by @HeathcliffWarriors from Dec 13th.

i don't understand why you even need to do an expensive check before a cheap write to a boolean value so i'm keeping my fingers off that one.

**Comment by HeathcliffWarriors** [comment]
Oof. I meant to have it compare to the existing memory value...luckily fixing this should be savegame compatible.

**Comment by HeathcliffWarriors** [comment]
@ilteroi My current pull request should fix the issue. Also posted a savegame compatible hotfixed DLL (without the other changes in my pull request) on the forums.

**Comment by HeathcliffWarriors** [comment]
It appears the fix works. Thanks for finding the problem!

**Comment by kdm2k6** [comment]
Thanks to both of you. I was able to finish up my last 5 turns :]

**Comment by ilteroi** [comment]
that's good but still i'm not sure if the whole design is sound ... really IsFriendDeclaredWarOnUs() should be a const-function and should not call SetFriendDeclaredWarOnUs() either.

**Comment by HeathcliffWarriors** [comment]
If it's an issue, I can move the check to DoCounters or something.

**Comment by HeathcliffWarriors** [comment]
I've moved the backstabbing penalty forgiveness checks to DoCounters. Only issue with that, is if a player is killed and resurrected, it'll take a turn to forgive any past maluses...but I can add something to CvPlayer to handle that, I guess.

**Comment by ilteroi** [comment]
just hit the same issue again in IsFriendDenouncedUs / SetFriendDenouncedUs ... did you fix that one as well?
