### ISSUE TITLE
Text key mismatch in game settings

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6035]
_1. Mod version (i.e Date - 4/23):_ Latest

Text key when hovering over the different difficulties doesn't match the one for when you actually click on that difficulty. The one for Settler in this screenshot should be:

```
UPDATE Language_en_US
SET Text = 'Easy. The AI is at a slight disadvantage.'
WHERE Tag = 'TXT_KEY_HANDICAP_SETTLER_HELP';
```
![Screenshot (21285)](https://user-images.githubusercontent.com/38794241/71602780-d0802780-2b27-11ea-92c3-b9462cc3807c.png)

**Comment by LoneGazebo** [comment]
Yep, TTs are cached at launch.
