### ISSUE TITLE
Unhappiness problem

### ISSUE THREAD

**Issue by Tarzan737** [LoneGazebo/Community-Patch-DLL#6037]
_1. Mod version (i.e Date - 4/23):_ 12-20-3

_2. Mod list (if using Vox Populi only, leave blank):_
![Skärmbild (5)](https://user-images.githubusercontent.com/20152388/71620320-a2532400-2bc9-11ea-922c-2282b2e52c3c.png)

_3. Error description:_  Happiness jumps from -40 to +50 difficulty level chieftain
no current war for a while

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![Skärmbild (4)](https://user-images.githubusercontent.com/20152388/71620374-f0682780-2bc9-11ea-84e6-cbfa6585a2cf.png)
[AutoSave_0314 AD-2034.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4012575/AutoSave_0314.AD-2034.zip)

**Comment by Vyyt02** [comment]
Aren't you missing some VP components? I can see only 5 in your modlist (I don't remember the setup for non-EUI though).

Also, as I pointed out on CivFanatics, the unhappiness breakdown seems to be messed up - I cannot see any distress, illiteracy, etc. Looks like your install is broken.
