### ISSUE TITLE
Joint war increases warmonger score

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#6038]
_1. Mod version (i.e Date - 4/23):_
12/30 hotfix

_2. Mod list (if using Vox Populi only, leave blank):_
![Capture2](https://user-images.githubusercontent.com/19291347/71638760-73bf6280-2c36-11ea-809f-8afe3e9fa8bd.PNG)

_3. Error description:_ 
I was asked by Spain for a joint war against Aztecs.  I agreed and she gained the "They have some early concerns about your warmongering. (They hate warmongers!)" diplo mod.  I thought this was changed recently so I'm reporting it.

**Comment by HeathcliffWarriors** [comment]
Still needs to be fixed, but I can put in a temporary fix for humans by having the AI declare war first.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Another thing you may want to address here; I think that Civ 6 has one thing right in that it nullifies all warmongering penalties with coop war partners.
