### ISSUE TITLE
Great Writer can't create Great Work?

### ISSUE THREAD

**Issue by jimmymcperson** [LoneGazebo/Community-Patch-DLL#6039]
_1. Mod version (i.e Date - 4/23):_
12/30 hotfix

_2. Mod list (if using Vox Populi only, leave blank):_
![Capture2](https://user-images.githubusercontent.com/19291347/71646462-03a4f100-2cb7-11ea-937b-ff130ab859c5.PNG)

_3. Error description:_ 
Naturally born Great Writer can't create Great Work even though there are slots available in the city.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4015301/Logs.zip)

**Comment by bigcat88** [comment]
How many civs in game(Japan is present i think) and what era is it going on?

**Comment by jimmymcperson** [comment]
It was mid-game and Japan was not present.

**Comment by bigcat88** [comment]
Try this:
https://steamcommunity.com/sharedfiles/filedetails/?id=181362854
