### ISSUE TITLE
After city trade cant process turn

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#6040]
_1. Mod version (i.e Date - 4/23):_
12-30

Situation was simple:
I conquered from Japan an original China city , annex it, do what I need and sold to China.
I sold it when it asks me to choose what to build.
As a result: 
After successful sold, Civ 5 want to me choose what to build in city that I doeas not own. Was fixed by loaded an autosave, choosed what to build and then sold. :) 

P.S.: Related to this:
CS gives me quest to build a road. I sold city that was on CS continent. Quest can't be completed. CS is allied so I cant demand tribute to reset that quest.

**Comment by HeathcliffWarriors** [comment]
Vanilla bug.

**Comment by bigcat88** [comment]
Ok, that's not a big trouble when autosaves are enabled.
But can bug with CS quest be fixed?

**Comment by HeathcliffWarriors** [comment]
I didn't say it was unfixable, just noting that it's also a vanilla bug.

**Comment by LoneGazebo** [comment]
fixed and fixed
