### ISSUE TITLE
Civilizing Mission(Imperialism branch)

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#6041]
_1. Mod version (i.e Date - 4/23):_
12-30
_3. Error description:_ 
See screen. Maybe description is wrong. City annexed without courthouse.
4. Screenshots (optional):
![Untitled](https://user-images.githubusercontent.com/13381981/71670720-7a0a2780-2d79-11ea-9877-c21153d48c46.png)

**Comment by UndeadDevel** [comment]
Duplicate of #6032
