### ISSUE TITLE
Free Jet Fighters from Pentagon don't receive any XP

### ISSUE THREAD

**Issue by 1andUnly** [LoneGazebo/Community-Patch-DLL#6045]
1. Mod version:12/20 with all hotfixes

2. Mod list (if using Vox Populi only, leave blank): 3/4MUCfVP

3. Error description: They start with 0 XP even with a Military Academy present. 

4. Steps to reproduce (optional): I also had Brandenburg in the city, maybe that messed something up when these 2 units spawned. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by UndeadDevel** [comment]
This was supposed to have been fixed with #5949 for the 12/20 version...I guess the fix didn't work or maybe 3/4UC is messing things up?

**Comment by bigcat88** [comment]
No, I still has the same issue and I didn't use 3/4UC.
