### ISSUE TITLE
True strategic resource monopolies don't work

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#605]
I've only got to test with horses and iron, but anyway - after I got over 50% of global amount of these resources (checked in resources&happiness tab), no popup showed up and these resource tiles didn't get additional yields (+3 science to horses, +3 hammers to iron). The 25% monopoly for these works just fine, though. Perhaps it's of any importance that I had Third Alternative, which doubles all owned strategic resources.

**Comment by LoneGazebo** [comment]
Can't replicate bug, sorry.

**Comment by LoneGazebo** [comment]
Wait! I did! It simply wasn't refreshing the Third Alternative value. Fixed.
