### ISSUE TITLE
Trade Route duration shown as 1 longer than actual

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6050]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2)
UI - Religion Spread (Vox Populi) (v 1.1)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
Trade Routes are shown in the UI as having one more turn to complete than is actually the case, which messed up timing for offices in my game...I checked the code of the Filters in TRO mod and the problem does not lie there, but in the actual data that it fetches. This may be connected to however the fix for #2738 was implemented (the author of the issue also mentions that a "-1" is missing, which seems like it would fix the issue), though it's probably been messed with in #3956 as well. See screenshots for confirmation (compare turn numbers: the two TRs that were supposed to complete 2 turns later actually complete the next turn).

_4. Steps to reproduce (optional):_
Establish a TR ingame and compare the given TR duration with the actual one as the game goes on.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![TR_turns1](https://user-images.githubusercontent.com/30495439/71748226-cb91df80-2e69-11ea-99a7-51c90240d12d.jpg)
![TR_turns2](https://user-images.githubusercontent.com/30495439/71748229-ce8cd000-2e69-11ea-97d5-74782ec2124b.jpg)

**Comment by LoneGazebo** [comment]
I'll add a -1 to the LUA connector, see if fixes
