### ISSUE TITLE
AI putting Great Generals in danger

### ISSUE THREAD

**Issue by Omen-of-Peace** [LoneGazebo/Community-Patch-DLL#6051]
_1. Mod version (i.e Date - 4/23):_ 12/20

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ AI brings not one but two Generals right next to a Citadel. And that's with a city right next door (though it's admittedly a bruised city, it's less likely to fall this turn than for the injured Lancer to die).

Suggestions:
- never stack up two GG near the front line.
- when defending, put GG in a city when there's one nearby and it shouldn't fall right away.

Let me know if you need any log.

Screenshot:
![image](https://user-images.githubusercontent.com/13177248/71752279-c25f3d80-2e7e-11ea-9177-f1ef51dacfc5.png)

@ilteroi

**Comment by ilteroi** [comment]
hard to do anything without a testcase
