### ISSUE TITLE
12/30 (DLL Update) - Cannot create Great Work with GM

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6055]
_1. Mod version (i.e Date - 4/23):_
12/30 (12/20 with DLL update)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I cannot found a great work in Berlin, even though I have confirmed the Opera house has an open slot. I have made some Great Works before, so its not a scenario where I cannot make them at all.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/71758937-6e972900-2e6b-11ea-925d-94535721a5ac.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
Large map with lots of players? There's been reports about the limit on Great Works being reached.

**Comment by Stalker012345** [comment]
Standard Size standard number of civs.

**Comment by bigcat88** [comment]
Screen is from Information Era. On standard map with 8 players great writers are usual ending creating all GW in Modern. 
Try as temporal solution this(you can enable it anytime): 
https://steamcommunity.com/sharedfiles/filedetails/?id=181362854

**Comment by Rand0miz3d** [comment]
I too have had this happen a lot. Always in late game. I play on standard map, 8 civs.
