### ISSUE TITLE
Boarding Party III and Boarded II description mismatch

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6056]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2.1)
UI - Religion Spread (Vox Populi) (v 1.2)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
The Boarding Party III description, which applies Boarded II, states about its effects on enemies that it's "reducing their Movement by 4 for 1 Turn.", while Boarded II actually reduces the movement by 3 and correctly states that in its description.

There are two issues:
1. The description mismatch; I'd like to add, however, that I feel a reduction by 4 movement points would be better, as 3 movement points aren't much for naval units in late game.
2. The movement point reduction actually lasts for 2 Turns, not 1. Technically the Movement points are reduced for 1 Turn only, but because of the way they get replenished, which happens before the promotion is removed, on the second Turn after Boarded was applied the unit will still only have the reduced movement points available...I think it would make sense to reflect that in the description (i.e. "lasts for 2 Turns").

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Boarded1](https://user-images.githubusercontent.com/30495439/71770407-14a66a00-2f24-11ea-9b13-3d49ffba1525.jpg)
![Boarded2](https://user-images.githubusercontent.com/30495439/71770412-1b34e180-2f24-11ea-98ed-a4354c10a091.jpg)

**Comment by ryanmusante** [comment]
Is Airfield Improvement-Unit (v 1) deprecated? I cannot locate it.

**Comment by UndeadDevel** [comment]
You can get it from the MODS folder I posted [here](https://github.com/LoneGazebo/Community-Patch-DLL/issues/6054)...I'm currently testing this mod to see how the AI behaves with it.

**Comment by pineappledan** [comment]
Also, Boarded levels stack, so a unit can get hit by boarded 1,2, and 3. I am guessing this is not the intention.

**Comment by LoneGazebo** [comment]
I haven't seen it stack before...

**Comment by UndeadDevel** [comment]
I haven't seen it be applied in the same turn before, either, but in my current game I have an Ironclad with normally 7 movement points get Boarded I (reduced to 5) and then the next turn Boarded II; because of the way Boarded works, however, my Ironclad only had 2 movement points when it was my turn again (it showed 2/4 at the beginning of my turn), so it effectively did stack the penalty.

This is why I noted in my OP that the description should probably change to state that movement points get reduced for 2 turns...the Boarded promo only lasts for one but the replenishment of movement points happens at the end of one's turn, so the reduced movement points last for 2 turns.

The issue I described with my Ironclad (stacking Boarded) is because applying Boarded apparently not only lowers the maximum but also "drains" the MP directly...is it maybe possible to have it only lower the max or maybe check how many MP the unit actually has before draining and not drain more than the max after lowering the max?

**Comment by pineappledan** [comment]
It has to be from 2 different ships. They don't stack from the same ship.

**Comment by bigcat88** [comment]
even when ship hit,   end turn - get level,  and hit?

**Comment by azum4roll** [comment]
What about changing it back to one turn only? (change the timing of debuff removal)

**Comment by UndeadDevel** [comment]
Don't know if that's possible with how it currently works...maybe if the debuff were to be given a duration of 0 turns?
