### ISSUE TITLE
12/30 (DLL Update) - Suicidal Knight Charge

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6057]
_1. Mod version (i.e Date - 4/23):_
12/30 (12/20 with DLL update)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This was an example of a very suicidal and weird knight charge by the AI. This knight did absolutely nothing and was already very hurt. It bashed against my fortified swordsman, and now its going to get quickly sniped. 

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/71774900-77a3fb00-2f3c-11ea-9134-18181d8845b0.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
hmm. weird. unfortunately hard to diagnose without a savegame, and those have their own set of problems. i did recently implement some changes in any case, so keep an eye on it in the next release ...

**Comment by Stalker012345** [comment]
Add to this in my recent game, a lancer just suicided into my musketeer. And not in a "well I killed the unit"....it just killed itself, doing a little bit of damage.
