### ISSUE TITLE
Tile acquisition culture overflow

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#6058]
_1. Mod version (i.e Date - 4/23):_
12-20-3 with 12-30 DLL

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Tile acquisition culture cost can overflow after completing 4 rings and working on the 5th, making the city unable to acquire another tile naturally.

Normally this isn't noticeable since cities aren't getting that huge and there are usually overlaps between different cities.

_4. Steps to reproduce (optional):_
Start any game, found capital and use IGE to continually grow the border. After a while it stops growing and the city view shows a negative culture cost to acquire the next tile.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
not a big problem but should be an easy fix
