### ISSUE TITLE
12/30 (Updated DLL) - Tercio not showing mounted bonus in summary screen.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6059]
_1. Mod version (i.e Date - 4/23):_
12/30 (12/20 with updated DLL)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In the combat summary screen, the Tercio is receiving its anti-mounted bonus (the overall CS is right), but its not showing the bonus in the summary breakdown.

On this note, I think it would be worth a good look at the code for the combat summary area...as I feel like I am reporting these kinds of problems continuously in every new version of the mod.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/71784385-afe91f00-2fb8-11ea-8792-709877a5b00c.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
Apparently this was how is supposed to be from vanilla (classified as an archer unit), [here ](https://forums.civfanatics.com/threads/chariot-archer-is-not-a-mounted-unit.523494/) discussion, but I don't know if was intentional to make "chariot archers" as mounted (cause of strength increase from the bonus) which, in this case, somewhere isn't modified to be classified in this way , hence the missing modifier text...

**Comment by HeathcliffWarriors** [comment]
I think this was fixed earlier, maybe the fix only applied on offense, not defense. @ilteroi may know

**Comment by Stalker012345** [comment]
Just confirmed with G that the Tercio should be getting its anti-mounted bonus on both offense and defense against skirmishers, so that's the desired intent.

**Comment by azum4roll** [comment]
And they're actually getting the bonus on defense against the skirmisher class during combat.
