### ISSUE TITLE
Incorrect unhappiness preview upon city capture 

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#606]
A 2 pop city certainly won't result in -156 unhappiness.
![capunhap](https://cloud.githubusercontent.com/assets/12978597/9718552/88529c30-5585-11e5-9eab-51930fbfa8be.jpg)

**Comment by LoneGazebo** [comment]
Huh. I'll look, but the value just simply pulls the city population.
