### ISSUE TITLE
Feature request: Distinct intrigue types for "plotting against" vs "planning war"

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6060]
_1. Mod version (i.e Date - 4/23):_ Latest

Currently there are several types of intrigue; however, the intrigue notifications for when an AI has the DECEPTIVE approach towards another AI vs. the WAR approach are merged into a single "plotting against" message.

I think it would be more useful and fun if "plotting against" was reserved for deception and "planning war against" was added as a new intrigue type for when the AI has the WAR approach.

Then it's clear which is which, and gives the player a more effective tool in distinguishing friend from foe. It would also make the diplo messages from other AIs sharing intrigue to the human more useful.

**Comment by ASCII-Guy** [comment]
I like the uncertainty. Gives me the Cold War paranoia vibe. That's just my two cents.

**Comment by Hokath** [comment]
This would be nice, before you pointed it out in the wiki I had no idea that there were two separate things. I assumed the AI just changed its mind about war sometimes (often :D)

**Comment by HeathcliffWarriors** [comment]
I'll try to figure this one out myself.
