### ISSUE TITLE
Do AIs need a starting Warrior?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6064]
_1. Mod version (i.e Date - 4/23):_ Latest

Do AIs need a starting Warrior? As in, are they capable enough to avoid having their turn 0 Settler captured by Barbarians, and build a Warrior fast enough to defend their capital? If not, I'd argue it could be removed, at least on the lower difficulties (below Prince). Otherwise it gives the AI a slight edge in the culture and religion races that it doesn't really need; early game turns are the most important.

**Comment by HeathcliffWarriors** [comment]
If the issue is that the human shouldn't make Pledges of Protection at the start of the game, perhaps PTPs could be disabled before turn 20 or so?

**Comment by HungryForFood** [comment]
Or do it the other way, give everyone a starting Warrior?

**Comment by azum4roll** [comment]
I already remove all starting units in my own modpack. They never lose their initial settler or have their capital demolished by barbarians at start. The only problem is human early rush, as always.

Even if the human can make PTPs at start, AI's military score will soon surpass the human anyway, before any quests are available.

**Comment by HeathcliffWarriors** [comment]
@HungryForFood I kind of like the early decision to choose between building a Warrior for defense or building a Shrine/Monument; if all players got a free Warrior my start-of-game build order would always be the same.
