### ISSUE TITLE
performance regression in CvCity::getBaseYieldRate()

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6066]
```
#if defined(MOD_BALANCE_CORE)
	//Update Yields from yields (this is tricky, avoid recursion, pooh!)
	for (int iI = 0; iI < NUM_YIELD_TYPES; iI++)
	{
		YieldTypes eIndex2 = (YieldTypes)iI;
		if (eIndex2 == NO_YIELD)
			continue;
		if (eIndex == eIndex2)
			continue;

		CvCity* pCity = this->plot()->getPlotCity();
		if (pCity)
		{
			pCity->UpdateCityYieldFromYield(eIndex, eIndex2, iValue);
		}

		//NOTE! We flip it here, because we want the OUT yield
		iValue += GetRealYieldFromYield(eIndex2, eIndex);
	}

	iValue += GetYieldFromHappiness(eIndex);
	iValue += GetYieldFromHealth(eIndex);
	if (eIndex != YIELD_JFD_CRIME)
	{
		iValue += GetYieldFromCrime(eIndex);
		iValue += GetYieldFromDevelopment(eIndex);
	}
#endif
```

notice the following line: CvCity* pCity = this->plot()->getPlotCity();

this is why i found this piece of code in the first place ... because it calls getPlotCity 17 times per plot. but it's even worse! it doesn't avoid possible recursion but instead circumvents the const-ness of the function. this is more than ugly! is there any other way to do whatever this code is supposed to be doing?

**Comment by LoneGazebo** [comment]
Well this is a very tricky beast, I ran into some major issues getting it to work. It allows for yield conversion between yields (i.e. every 10 gold counts as 1 culture per turn, etc.). And yeah, dealing with the const was the issue...I know it is ugly but it isn't that performance heavy.

**Comment by ilteroi** [comment]
well it's called a gazillion times when re-allocating citizens. i solved the performance issue but it's still ugly.

**Comment by LoneGazebo** [comment]
It is ugly, yes. But it's the best I can do given the spaghetti of the yield system as-is.
