### ISSUE TITLE
GetPlayerTraits()->IsCapitalOnly()

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6067]
how exactly is that supposed to work?

when initializing the traits, the following happens:

			if (trait->IsCapitalOnly())
			{
				m_bIsCapitalOnly = true;
			}

but afterwards it's unclear which trait is supposed to be affected!

**Comment by LoneGazebo** [comment]
I think only certain traits even call on that, but I'm not sure...
