### ISSUE TITLE
AI way too reluctant to trade Great Works

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6071]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2.1)
UI - Religion Spread (Vox Populi) (v 1.2)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
The world in my game is in Modern now and the AI has only traded something with me once despite me having something on offer constantly. I thought that maybe they trade amongst themselves and it's just me they leave out, but now I've seen several of their capitals and almost none of them have foreign art, which at this point is to their own detriment, since they all have Hermitage now and it needs foreign Art for the theming bonus. Venice even filled up its own Hermitage with 3 pieces of its own Art, which indicates that it doesn't have any better use for it. Why wouldn't it trade for one of mine? It has nothing to lose in that trade.

That's why I'm posting this as a bug report...the GW swapping reluctance of the AI is hurting its own development...at the very least they should be trading amongst themselves.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![trading_reluctance_AI](https://user-images.githubusercontent.com/30495439/71955191-8cec8400-31df-11ea-9617-af79c437401b.jpg)

**Comment by azum4roll** [comment]
Is it possible to put Great Works in the trade screen? It's a big change and probably involves lots of new code but it would solve the problem completely.

**Comment by bigcat88** [comment]
Was the same for me(no trade till late industrial) - but after that in modern I finish trading and themed all buildings I have. Total trade 7 or 8 works(all atomic are we trade)
I think in earlier eras AI doesn’t need much works for theme.

**Comment by UndeadDevel** [comment]
Well if you look at the screenshot I posted you'll see that Venice sure does have a reason: they have a Hermitage full of their own Art, which doesn't give any theming bonus, so they should actually be offering those up for trade right now, but they're not.

**Comment by HeathcliffWarriors** [comment]
@azum4roll It's possible to do AFAIK, but it would indeed require a lot of new code.
