### ISSUE TITLE
Nitpick: total GPT income shown less than components

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6072]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2.1)
UI - Religion Spread (Vox Populi) (v 1.2)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
See screenshot; my total GPT income shown is less than the individual components add up to; I've observed this over several turns. The expenses part matches perfectly, however.
The actual combined income should be approximately 2966, which is higher than is shown; however, the total matches and seems to be added each turn correctly, so it's just the listed sum of the income components that is incorrect.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![GPT_mismatch](https://user-images.githubusercontent.com/30495439/71955874-70514b80-31e1-11ea-9508-ae6a658e9830.jpg)

**Comment by LoneGazebo** [comment]
If you can figure out which value is wrong that would be helpful. Without that info I can’t do anything.

**Comment by UndeadDevel** [comment]
Like I said: it's the sum of the income that's wrong. The individual income components seem to be correct and the "grand total" (GPT) at the very top (below the "500 total Gold available to spend") is also correct. 
What's incorrect is the "2660.58 in total income", which is too low, but doesn't seem to matter aside from the display, because the "grand total" is still correct and those correct amounts are added each turn to my treasury.

**Comment by LoneGazebo** [comment]
Yes. but I wonder if the sum alone is the issue or if there's an individual GPT value that's not transposing to LUA correctly.

**Comment by UndeadDevel** [comment]
Well adding all the individual income elements together and subtracting the total expenses from that yields the "grand total" (golden number), so the individual components must therefore be correct.
It's the sum of the income alone that is incorrectly shown.

**Comment by LoneGazebo** [comment]
Can you confirm for me the amount of money you're sending to other civs via trade deals?

I think the issue may be that the 'net' trade value is being calc'd for that TT, so you're only seeing the net income from other civs, not the raw income.

**Comment by UndeadDevel** [comment]
Okay I'll give you the numbers from my current turn (see screenshot below):
Individual components: 1,829.5 + 158.3 + 440.82 + 303 + 442 + 39 = **3,212.62**
Total income shown: **2,874.04**
Total expenses: **2,129**
Grand Total (shown): **1,084.32**
The Grand Total is pretty much correct (technically 0.7 too much, but that's probably a rounding issue with the expenses shown); the total income is, again, wrong; it is off by 338.58.
I am sending 3 + 3 + 9 + 16 = 31 GPT to other Civs (see screenshot), so that doesn't seem to be it.

![GPT](https://user-images.githubusercontent.com/30495439/72008965-d0310c00-324c-11ea-8ff0-cce776917e0a.jpg)

**Comment by UndeadDevel** [comment]
This issue persists after my Golden Age ended, so that doesn't seem to be the cause, either.

**Comment by LoneGazebo** [comment]
I looked at the UI and the code looks fine, so something is missing from the tooltip. Any gold-related policies, beliefs, ideologies?

**Comment by UndeadDevel** [comment]
Policies (all taken fully) / Ideology:
1. Authority: insta-Gold on border expansion and reduced maintenance for Routes and Units
2. Fealty: Gold from Castles, Armories, Pastures
3. Imperialism: Puppet yield modifier reduced (=more Gold from Puppets, of which I have several but their income is not high enough to add up to the missing value alone), +3 to Yields from Monopolies (I have Perfume Monopoly, which gives Gold on resource tiles)
4. Autocracy: only Iron Fist could increase Gold Yields here (+25% from CSs and Vassals, though I don't know if Vassal Taxes get boosted by that as well...I do have 3 Vassals)

Beliefs:
several Beliefs that give insta-Gold, including Cathedrals, which give flat Gold and boost Gold from certain Improvements.


I've taken a look at the code myself now, however, and it's kind of a mess, to be honest. I've compared the way the correct GPT at the top is calculated (at least "correct" in the sense that this is what is actually being added to my treasury every turn) with the way the sum of incomes is calculated. The sum of incomes comes from a variable called `totalIncome`, which itself comes from a variable called `explicitIncome`, which allows this comparison. There are four discrepancies:
1. `goldPerTurnFromCities` and `tradeRouteGold` are calculated in a different way (in the cpp they are combined and simplified). There could be a discrepancy buried in the `GetGoldFromCitiesMinusTradeRoutesTimes100` function but my brain is not fit enough anymore today to go down that rabbit hole.
2. `iGoldFromVassalTax` has been divided by 100, which is a bug. See below.
3. `iInternalRouteGold` isn't being multiplied by 100, which is a bug. See below.
4.  `iGoldFromMinors` isn't being multiplied by 100, which is a bug. See below.

The third point is a bug that should be fixed but it's not relevant to my specific problem, because I'm not getting any of that kind of yield.

`totalIncome` will be divided by 100 to display the value in the tool tip, so all components of `explicitIncome` should have been multiplied by 100 at some point beforehand; what definitely dramatically reduces the sum of incomes is 
1. the fact that `iGoldFromVassalTax` is being divided by 100 beforehand (unlike in the cpp, where it is correctly taken from a function that gives the 100x value and then simply added without division); so in effect this value, which originally is a multiple of 100, is divided by 100 twice (so by 10000) before it's displayed.
2. the fact that `iGoldFromMinors` is not being multiplied by 100 when calculating `explicitIncome`; it comes from a non-multiplied source so it needs to be multiplied (as is done in the cpp).

For reference: 
- here is the (presumably) [correct function in the cpp](https://github.com/LoneGazebo/Community-Patch-DLL/blob/1a769066eca1640d9f915176021a867d5e438349/CvGameCoreDLL_Expansion2/CvTreasury.cpp#L445)
- here is the [problematic calculation in the LUA](https://github.com/LoneGazebo/Community-Patch-DLL/blob/master/EUI%20Compatibility%20Files/EUI%20Compatibility%20Files/LUA/TopPanel.lua#L996)

The remaining problem is that recalculating the observed values the correct way still doesn't explain the discrepancy (now the sum of income would be too high), which likely means there is some problem with `GetGoldFromCitiesMinusTradeRoutesTimes100` as well, but I need a break for now.

**Comment by UndeadDevel** [comment]
Actually, fixing the 100 multipliers would probably do it...I had a little brain fart when doing the "corrected" calculations...fixing those two problems brings the remaining error within less than 0.1, which can be explained by rounding, so this is probably it!

I almost want to say "Halleluja" and also that I never want to deal with yield calculation again 😃 

Do you get what needs to be done or should I make a pull request (that you should really review, though, as it's still a lot of spaghetti)?

**Comment by LoneGazebo** [comment]
You're officially the expert on those lines of code, so a pull would be great :)

**Comment by UndeadDevel** [comment]
Alright I'll get on it...it seems to only be affecting the EUI versions, so VP (EUI) and 43 Civs (EUI).

Question: is `civ5_mode` ever not `true` in VP (EUI) or 43 Civs (EUI)?
