### ISSUE TITLE
Feature request: "Stop Sending Quests" button for City-States

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6078]
There've been a fair number of complaints about City-State Influence competition and the resulting diplo tension rising incidentally from constructing buildings and the like.

There's already an option to request that militaristic City-States stop sending units, and this would be the same principle.

Would it be possible to simply add a button like this for quests? Pressing it would cancel all current quests and prevent any further quests from being sent (except perhaps invasion by Barbarians and gifting units). 

Pressing it a second time would re-enable quests, assuming they're not blocked by something else.

If possible, I think this would make everyone happy.

**Comment by UndeadDevel** [comment]
I like it.

The annoying part of the implementation would be to sift through CvMinorCivAI.cpp (about 18,000 lines) and make the required "backend" changes there and make sure it doesn't break anything.
If someone were willing to take care of that I'd be willing to look at implementing the "frontend" stuff (UI).
