### ISSUE TITLE
Warmonger Aggrieved Percent

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6080]
@LoneGazebo Since you're modifying the warmonger penalty calculations, if you haven't noticed this already:
```
				if (!bLiberation && GET_TEAM(kConqueringPlayer.getTeam()).isAggressor(kConqueredPlayer.getTeam()))
				{
					iWarmongerAggrievedModifier = GC.getWARMONGER_THREAT_AGGRIEVED_PERCENT();
				}
```
This seems to be reducing warmongering weight for the aggressor, not the victim? Seems to be the opposite of what is intended in the AIWarmongerAdjustments.xml file.

**Comment by LoneGazebo** [comment]
Yep, saw that

**Comment by HeathcliffWarriors** [comment]
Well, that works.
