### ISSUE TITLE
WLTK trigger and reset

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6088]
12/20 with 12/30 updated dll

A novelty of this version is that cities wltk resource demand happens the turn after founding, while in past we had to wait 20ish turns, or about 3-4 population, not sure tbh. This might be intended or not.

Anyway, turn 44 I didn't connect the required resource for my capital yet, but the wltk reset and now the city asks for a different resource.

**Comment by LoneGazebo** [comment]
I added some resets in the system to keep it all flowing. intended...
