### ISSUE TITLE
YIELD_POP should not scale on gamespeed or era

### ISSUE THREAD

**Issue by stevenkxu** [LoneGazebo/Community-Patch-DLL#6093]
_1. Mod version (i.e Date - 4/23):_ 12/20

_2. Mod list (if using Vox Populi only, leave blank):_ 3/4 UC, World Congress Reformation, Civic and Reform, Unique City States, Enhanced Naval Warfare, Community Events

_3. Error description:_ Got an event where one of the options was -3 Pop in a city, playing on Epic speed. Lost 5 pop upon choosing it.  Was playing on epic gamespeed and in ~Medieval era

_4. Steps to reproduce (optional):_ If the issue is what I'm reporting, set up event that gives you +1 Pop on city found, play on marathon, see how many pop you get.

**Comment by LoneGazebo** [comment]
Does not scale - probably a TT typo, ask @TechpriestEnginseer

**Comment by TechpriestEnginseer** [comment]
I will see and fix.
