### ISSUE TITLE
AI loves building hotels

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6096]
this is hadrumetum. it barely has any tourism, and the benefit from a hotel is 0.

even minors are building hotels!

i see two options:
* implement a check for the actual benefit of the building
* give the hotel some innate tourism

![image](https://user-images.githubusercontent.com/1358966/72223462-3e3c4280-356f-11ea-82f7-c6214b90d4fd.png)

232, Carthage, Hadrumetum, PRE: Building, Bank, 4910, 4
232, Carthage, Hadrumetum, PRE: Unit, Fusilier, 4770, 6
232, Carthage, Hadrumetum, PRE: Building, Hotel, 4750, 7
232, Carthage, Hadrumetum, PRE: Unit, Musketman, 4059, 3
232, Carthage, Hadrumetum, PRE: Building, Opera House, 3335, 4
232, Carthage, Hadrumetum, PRE: Unit, Field Gun, 3249, 9
232, Carthage, Hadrumetum, PRE: Building, Workshop, 3095, 2
232, Carthage, Hadrumetum, PRE: Building, Stable, 2511, 2
232, Carthage, Hadrumetum, PRE: Unit, Ironclad, 2500, 8
232, Carthage, Hadrumetum, PRE: Unit, Frigate, 2200, 4
232, Carthage, Hadrumetum, PRE: Building, Aqueduct, 2180, 2
232, Carthage, Hadrumetum, PRE: Building, Herbalist, 2180, 1
232, Carthage, Hadrumetum, PRE: Building, Armory, 1320, 2
232, Carthage, Hadrumetum, PRE: Building, Circus, 966, 2
232, Carthage, Hadrumetum, PRE: Process, Wealth, 930, 1
232, Carthage, Hadrumetum, PRE: Unit, Pioneer, 825, 20
232, Carthage, Hadrumetum, PRE: Process, Arts, 475, 1
232, Carthage, Hadrumetum, PRE: Process, Research, 424, 1
232, Carthage, Hadrumetum, PRE: Project, Public Works, 300, 17
232, Carthage, Hadrumetum, PRE: Process, Farming, 140, 1
232, Carthage, Hadrumetum, PRE: Unit, Zeppelin, 135, 6
232, Carthage, Hadrumetum, PRE: Building, Constabulary, 125, 4
232, Carthage, Hadrumetum, PRE: Process, Defense, 100, 1
232, Carthage, Hadrumetum, SKIPPED: Fusilier, Val: -1, TURNS: 6
232, Carthage, Hadrumetum, SKIPPED: Musketman, Val: -1, TURNS: 3
232, Carthage, Hadrumetum, SKIPPED: Field Gun, Val: -1, TURNS: 9
232, Carthage, Hadrumetum, SKIPPED: Ironclad, Val: 0, TURNS: 8
232, Carthage, Hadrumetum, SKIPPED: Frigate, Val: 0, TURNS: 4
232, Carthage, Hadrumetum, SKIPPED: Pioneer, Val: 0, TURNS: 20
232, Carthage, Hadrumetum, SKIPPED: Zeppelin, Val: -1, TURNS: 6
232, Carthage, Hadrumetum, SKIPPED: Defense, Val: 0, TURNS: 1
232, Carthage, Hadrumetum, POST: Building, Hotel, 4231, 7
232, Carthage, Hadrumetum, POST: Building, Workshop, 2115, 2
232, Carthage, Hadrumetum, POST: Building, Armory, 1091, 2
232, Carthage, Hadrumetum, POST: Building, Constabulary, 1023, 4
232, Carthage, Hadrumetum, POST: Building, Stable, 871, 2
232, Carthage, Hadrumetum, POST: Building, Opera House, 856, 4
232, Carthage, Hadrumetum, POST: Building, Aqueduct, 639, 2
232, Carthage, Hadrumetum, POST: Building, Herbalist, 605, 1
232, Carthage, Hadrumetum, POST: Building, Circus, 573, 2
232, Carthage, Hadrumetum, POST: Building, Bank, 556, 4
232, Carthage, Hadrumetum, POST: Process, Arts, 238, 1
232, Carthage, Hadrumetum, POST: Process, Wealth, 103, 1
232, Carthage, Hadrumetum, POST: Process, Farming, 102, 1
232, Carthage, Hadrumetum, POST: Process, Research, 82, 1
232, Carthage, Hadrumetum, POST: Project, Public Works, 35, 17
232, Carthage, Hadrumetum, SEED: 14862701830179580984, CHOSEN: Building, Hotel, NoRush, ERA: 4, TURNS: 7

**Comment by HeathcliffWarriors** [comment]
Related issue reported on the forums:
https://forums.civfanatics.com/threads/new-beta-version-december-20th-12-20.652983/page-12#post-15640499

**Comment by LoneGazebo** [comment]
weird, hotels are part of an implicit check - i'll look
