### ISSUE TITLE
Tributing reluctance decay small correction

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6097]
_1. Mod version (i.e Date - 4/23):_
1-11

_2. Mod list (if using Vox Populi only, leave blank):_
only IGE for testing

_3. Error description:_ 
I unfortunately made a small error in my suggestion for the fix, which seems to have been implemented as I suggested. The "17"s in line 15798 and 15800 need to be changed to "15" and "16", respectively, otherwise there will be a reluctance of -225 for two turns in a row as it changes from fast reluctance decay to slow reluctance decay as well as a useless statement of zero reluctance on the last turn of the effect. So this is what it should look like in the code (or see my pull request):
```
if(iLastBullyTurn >= 0)
{
	if (iLastBullyTurn == GC.getGame().getGameTurn())
	{
		iScore += iFailScore * 2;
		if (sTooltipSink)
		{
			Localization::String strNegativeFactor = Localization::Lookup("TXT_KEY_POP_CSTATE_BULLY_FACTOR_NEGATIVE");
			strNegativeFactor << iFailScore;
			strNegativeFactor << "TXT_KEY_POP_CSTATE_BULLY_FACTOR_BULLIED_VERY_RECENTLY";
			sFactors += strNegativeFactor.toUTF8();
		}
	}
	else if(iLastBullyTurn + 7 >= GC.getGame().getGameTurn())
	{
		int iBulliedVeryRecentlyScore = (((iLastBullyTurn + 10) - (GC.getGame().getGameTurn())) * -75);
		iScore += iBulliedVeryRecentlyScore;
		if (sTooltipSink)
		{
			Localization::String strNegativeFactor = Localization::Lookup("TXT_KEY_POP_CSTATE_BULLY_FACTOR_NEGATIVE");
			strNegativeFactor << iBulliedVeryRecentlyScore;
			strNegativeFactor << "TXT_KEY_POP_CSTATE_BULLY_FACTOR_BULLIED_VERY_RECENTLY";
			sFactors += strNegativeFactor.toUTF8();
		}
	}
	else if (iLastBullyTurn + 15 >= GC.getGame().getGameTurn())
	{
		int iBulliedRecentlyScore = (((iLastBullyTurn + 16) - (GC.getGame().getGameTurn())) * -25);
		iScore += iBulliedRecentlyScore;
		if (sTooltipSink)
		{
			Localization::String strNegativeFactor = Localization::Lookup("TXT_KEY_POP_CSTATE_BULLY_FACTOR_NEGATIVE");
			strNegativeFactor << iBulliedRecentlyScore;
			strNegativeFactor << "TXT_KEY_POP_CSTATE_BULLY_FACTOR_BULLIED_RECENTLY";
			sFactors += strNegativeFactor.toUTF8();
		}
	}
}
```

Thanks.

_4. Steps to reproduce (optional):_
Tribute a CS and click next turn while checking the numbers every turn to see the development.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
@UndeadDevel It was updated.
![be402b0b5b93874b9120f16631747326](https://user-images.githubusercontent.com/38794241/72224908-7894e800-354d-11ea-9b24-5dd24c0c509c.png)

**Comment by UndeadDevel** [comment]
Hmm...now that you show it I've checked and I do see the commit...it seems when it was updated my link got changed to a historical version of the file...my bad; I'm still newbish on GitHub.

I'll make the pull request then.

**Comment by HeathcliffWarriors** [comment]
No worries! :)
