### ISSUE TITLE
City Strength still bugged

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6098]
_1. Mod version (i.e Date - 4/23):_
1-11

_2. Mod list (if using Vox Populi only, leave blank):_
only IGE for testing

_3. Error description:_ 
I already posted this in the other issue thread but it's being ignored (perhaps because notifications aren't being sent out)....retested this with the newest version and it's still broken:
1. Land melee units moving into a City with a naval garrison still lower the City's Combat Strength in certain circumstances (specifically, when the unit has greater CS than the City but lower CS than the naval unit's CS / RCS, the former in the case of melee naval, the latter in the case of ranged naval, which is another bug).
2. Ranged naval garrisons still use RCS instead of CS for to determine City Combat Strength, though  that may be intended (earlier ilteroi said that it wasn't intended, however).
3. Naval unit garrison's contributions to City Strength aren't halved (ilteroi has said before that their CS is supposed to be halved when determining how much they boost City Strength by)

See screenshots below.

_4. Steps to reproduce (optional):_
Just plant a new coastal City on flat land, put a Spearman, Dromon and Trireme next to it and then try out the possible combinations of garrisoning those units in the City and observe the City Strength value.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![_CS1](https://user-images.githubusercontent.com/30495439/71916294-8de8cb80-3175-11ea-89e4-3b9d5871fd61.jpg)
![_CS2](https://user-images.githubusercontent.com/30495439/71916312-93461600-3175-11ea-883f-e36a904c24f5.jpg)
![_CS3](https://user-images.githubusercontent.com/30495439/71916318-96410680-3175-11ea-8833-c50f2e5cdc71.jpg)
![_CS4](https://user-images.githubusercontent.com/30495439/71916326-9a6d2400-3175-11ea-8e66-00677d012fb4.jpg)
![_CS5](https://user-images.githubusercontent.com/30495439/71916333-9d681480-3175-11ea-82d8-042eb0d184da.jpg)

**Comment by LoneGazebo** [comment]
@ilteroi I leave this to you, as you messed with garrison code recently :)

**Comment by UndeadDevel** [comment]
This is also affecting Imperialism, which states that aircraft is supposed to boost City Defense by 3, which doesn't always happen.
