### ISSUE TITLE
Barbarians rarely heal

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#610]
I've noticed this since the previous version. Barbarian healing in general seems very inconsistent - they will often stand in one place for several turns, injured, but not healing. It's most noticeable with units fortified in barbarian camps - they will even have fortification bonus applied, but their health won't replenish at all.

**Comment by Edaka** [comment]
I will add that ranged barbarian units (archers, at least) can shoot from an encampent and then heal during the same turn.Perhaps logic for ranged and melee units is different?

**Comment by ilteroi** [comment]
fixed, barbarians reliably heal in camps now.

never seen them resting outside of camps, and i think they are annoying enough as is :)

**Comment by Edaka** [comment]
Does that mean that they won't ever heal outside of camps? I'm asking because there is this option (probably outdated, I assume) in C:\My Documents\My Games\Sid Meier's Civilization 5\MODS\Community Balance Patch\CommunityOptions.sql :
Barbarians Heal!
0 = No Healing
1 = 6HP out of camps, 12 in camps. (Default)
2 = 10HP out of camps, 20 in camps. (Hard)

**Comment by LoneGazebo** [comment]
Latter is errata from Communitas days. I'll fix.
