### ISSUE TITLE
Open Borders Broken

### ISSUE THREAD

**Issue by zozer** [LoneGazebo/Community-Patch-DLL#6102]
_1. Mod version:_
1/11

_2. Mod list:_
More Unique Components

_3. Error description:_ 
Open borders arnt letting my units through. As seen I have open borders with the Shoshone, yet my unit can not enter their tiles. Open borders is working in some regard where missionaries dont suffer the unwelcomed penalty.
![image](https://user-images.githubusercontent.com/10717704/72228036-12ba5780-3571-11ea-9101-48e548a9e807.png)

**Comment by 1andUnly** [comment]
I'm having the same issue
