### ISSUE TITLE
AI still building scores of diplo units

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6104]
and not using them ...

![image](https://user-images.githubusercontent.com/1358966/72236795-893e7000-35d8-11ea-8f8d-5b67a21d8f54.png)

**Comment by LoneGazebo** [comment]
You have weird unit issues that I don't, which concerns me.

**Comment by ilteroi** [comment]
made some changes to ScoreCityForMessenger() to allow more targets ...
