### ISSUE TITLE
1/11 - Connected Marble not being recognized

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6106]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Even though Agra has connected Marble, its not showing up as an available luxury, and Mumbai still shows it as a needed resource for WLTKD. Only note is that Agra was conquered and retaken at one point.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/72281876-0ed61600-3601-11ea-94cc-c9db6fa04884.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
embargoed?

**Comment by Stalker012345** [comment]
Double checked, no its not banned.

**Comment by LoneGazebo** [comment]
I dunno. That's weird.

**Comment by azum4roll** [comment]
Not sure if related, but in my 7-29-1 game (very old version I know), the UI keeps telling me I have 2 (untraded) copies of Olives despite only having 1. There's also only 1 copy in the trade screen.
