### ISSUE TITLE
1/11 - High Negative Warscore, even without a single battle

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6109]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Shoshone has not pillaged a single TR, and we have never actually engaged in battle. Yet my warscore is -33

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/72288076-e0ab0300-360d-11ea-80e2-6bd9923d65a9.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
Unusual. Could you post a savegame?

**Comment by HeathcliffWarriors** [comment]
Possibly caused by being previously at war recently; war damage decays over time.
