### ISSUE TITLE
performance issue in GetTourismMultiplier()

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6110]
this is the last finding from my profiler runs ...

each player's diplo AI calls GetTurnsToInfluential(ePlayer) for each other player which finally calls GetTourismMultiplier(ePlayer), which loops over all cities of both players and calls getUnhappinessFromCulture() for each, which is not cheap.
```
		int iBoredom = kPlayer.getUnhappinessFromCityCulture();
		int iDelta = iBoredom - kCityPlayer.getUnhappinessFromCityCulture();
```

this does not scale well with the number of cities and the number of players.

is there a better way? because of the deep callstack, it's unfortunately not easy to pass any precomputed values ...

**Comment by HeathcliffWarriors** [comment]
Calls are probably going through IsCloseToCultureVictory.

One option could be to cache the IsCloseToXVictory values, but it would still be performance intensive. Maybe the GetTurnsToInfluential value could be stored somewhere?

**Comment by HeathcliffWarriors** [comment]
Another option is to cache the IsCloseToXVictory values; while this wouldn't be optimal intelligence-wise, it's not that critical to update it more than once a turn.

**Comment by ilteroi** [comment]
well there's precomputing (difficult as mentioned) and caching (also complex - because of the UI calls) and finally re-arranging the algorithm. the most extreme option would be to remove the boredom delta ... i don't know how big the impact is. so no clear favorite ...

**Comment by LoneGazebo** [comment]
Boredom plays a big role...why not just cache 'last turn values' at start of each turn for the tourism check, we can include that in boredom TT in tourism overview.

**Comment by LoneGazebo** [comment]
edit: done.

**Comment by ilteroi** [comment]
nice
