### ISSUE TITLE
Hey CP ppl! Just wondering what was changed in the DLL to allow the oberserver player to meet other players

### ISSUE THREAD

**Issue by iskaandismet** [LoneGazebo/Community-Patch-DLL#6112]
Not quite an issue but iirc last time I asked a technical question on CFC I was told to ask it here instead:

What was changed in the DLL to allow
1) having observer players meet all Civs and
2) loading improvement graphics on tiles when in observer mode?

**Comment by ilteroi** [comment]
that was ages ago .... a short search in the history says:

53722a63ab046037f555f09491dc20577f4d0ad8 and 302b46cbbda3efd44b7dc6d36d13775d1b03d293

check the changes in CvGame

**Comment by iskaandismet** [comment]
Thanks!
