### ISSUE TITLE
Bonus Building_TerrainYieldChanges does not work on hill

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6116]
1. Mod version: 12-20-3
2. Mod list: VP + MoreWonders for VP v0.3.14 (in developement) + IGE
3. Error description:
I used code in sql:
```
INSERT INTO Building_TerrainYieldChanges 
(BuildingType,		TerrainType,		YieldType,		Yield) 
VALUES		
('BUILDING_NAZCA',	'TERRAIN_PLAINS',	'YIELD_FOOD',	2),
('BUILDING_NAZCA',	'TERRAIN_PLAINS',	'YIELD_FAITH',	1),
('BUILDING_NAZCA',	'TERRAIN_HILL',		'YIELD_FOOD',	1),
('BUILDING_NAZCA',	'TERRAIN_HILL',		'YIELD_FAITH',	2);
```

and received correct info in wonder tooltip, but if you find hills on map, then they do not receive bonus.
![hillfaith](https://user-images.githubusercontent.com/33016300/72372003-d3713f80-3705-11ea-938d-2d83d5193bd7.png)

**Comment by ilteroi** [comment]
well that's probably because hills is not a only a terrain but also a plot type: PLOT_HILLS. don't ask me why but there's probably historic code from 1991 in there.

some map scripts produce inconsistent results ...

**Comment by adaneslavo** [comment]
So is there any way to make this work?

**Comment by adaneslavo** [comment]
Building_PlotYieldChanges seems to be working, but UI doesn't display correct buffs like Building_TerrainYieldChanges.
