### ISSUE TITLE
Trade Confederacy gives +0.01 influence for each trade route after the first one instead of +1

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#6117]
_1. Mod version (i.e Date - 4/23):_
Latest

Title, pretty much.

**Comment by ilteroi** [comment]
i don't really understand the problem but probably fixed indirectly, because the number of trade routes to minors was mis-counted.

but there is some weird code here:
```
		//Influence decay increases the higher your influence over 100;
		if (MOD_DIPLOMACY_CITYSTATES_QUESTS &&  iBaseFriendship > 100)
		{
			float iInfluenceTotal = GetBaseFriendshipWithMajorTimes100(ePlayer) * .001f;

			if (iInfluenceTotal != 0)
				iChangeThisTurn += (int)iInfluenceTotal*-1;
		}
```

why not just make the influence decay a fraction of the current influence instead of introducing arbitrary thresholds?

**Comment by ilteroi** [comment]
also there is this part:

```
				if (iShift != 0 && MOD_BALANCE_CORE_DIPLOMACY_ADVANCED)
				{
					iShift += kPlayer.GetTrade()->GetNumberOfCityStateTradeRoutes()-1;
				}
```

that's calculated in 1/100th, so each trade route gives 0.01 influence point per turn. is that effect really intended to be so small?

**Comment by Edaka** [comment]
Yeah, I think my issue is the one you described in your last post. There's a policy that's supposed to give +1 infuence per turn for each active trade route to a city state. As from the change log: 

> Trade Confederacy - [...] Tweaked influence per turn to generate +x influence to city states, where x is the total number of city-state trade routes you have at that time (so 5 routes = +5 influence on each CS TR route)

It currently correctly gives +1 influence per turn if x=1, but for x>1 it only gives +0.01 influence per turn for each route (i.e., 2 routes=+1.01 instead of +2, 3 routes=+1.02 instead of +3, etc).

**Comment by LoneGazebo** [comment]
I’m aware.
