### ISSUE TITLE
War icon tool tip outdated info

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6118]
_1. Mod version (i.e Date - 4/23):_
1-11-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I recently added functionality to have the war icon display the war info stuff that one can see in the Leader Head screen. What I didn't realize is that the functions fetching that info don't make sure that it's updated, so that in effect the tool tip right now only shows current information at the start of the turn or if there was no relevant action taken since the last time the Leader Head screen of that AI was opened.

I identified what would need to be called to update the info:
- **DoUpdateWarDamageLevel** in CvDiplomacyAI.cpp
- **DoUpdatePeaceTreatyWillingness** in CvDiplomacyAI.cpp
These are called when the player enters the Leader Head screen (**DoBeginDiploWithHuman**) but not when fetching the info they update.

Since I think that the war icon tool tip is a very convenient tool, I'd like to keep it and make it work; I think I know what needs to be done but I thought I'd post here first before I just make the relevant pull request. Basically I intend to add two LUA hooks to CvLuaPlayer.cpp (and the relevant references in CvLuaPlayer.h) that simply call the two methods listed above; for this I would simply follow the pattern that DoBeginDiploWithHuman uses, which is easy enough. Additionally there will be an update to NotificationPanel.lua, of course.

I checked the relevant sections of CvDiplomacyAI.cpp and CvLuaPlayer.cpp and this seems to be unproblematic as long as I make sure not to call it outside the player turn, which I'll ensure by introducing a check in the LUA portion of my pull request.

Any objections?

_4. Steps to reproduce (optional):_
Wage war and keep checking the tool tip and then compare that info with the tool tip in the Leader Head screen and also see how entering the Leader Head screen updates the tool tip outside of it.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
DoUpdatePeaceTreatyWillingness calls IsWantsPeaceWithPlayer (directly for AIs, indirectly for humans), and if logging is enabled this would spam the peace willingness logs.

**Comment by UndeadDevel** [comment]
Well DoUpdatePeaceTreatyWillingness is called in DoBeginDiploWithHuman, which is called every time the Leader Head screen is opened (it will call the former if the AI is at war with the human)...this was the whole point of the feature, after all, to get the info about the war that is accessible in the tool tip of the Leader Head screen without having to go to the Leader Head screen...it's just a UI simplification (one mouse over instead of one mouse over and two clicks and having to trigger the whole Leader Head stuff visually, which can be a bit annoying if I want to check the info often).

So it doesn't seem like logging is an issue that is pertinent to the changes I want to make...if there is a logging problem with these functions then it already exists even before my changes; do you agree?

**Comment by HeathcliffWarriors** [comment]
Yeah, that makes sense, just pointing it out as a potential issue.

**Comment by UndeadDevel** [comment]
Okay well just as a heads up then:
this already happens even without the war icon tool tip functionality: the tool tip in the Leader Head screen calls IsWantsPeaceWithPlayer; this is after DoUpdatePeaceTreatyWillingness is called by opening the Leader Head screen if it's a human at war with the AI, so it would output the logging from the IsWantsPeaceWithPlayer twice, at least...I don't really deal with those logs though and I don't want to start changing stuff there, but if it's a problem it would need to be tackled separately there.

**Comment by UndeadDevel** [comment]
Okay I just tested it: opening the Leader Head screen with the AI when at war will output 1 line into the peace log for every vassal and a total of 4 lines, all containing the same info, about peace willingness with the human...this is without the war icon tool tip or anything else I did. I wouldn't say it makes the peace logs unusable or anything but again, if this is considered to be a problem then it's unrelated to my proposed changes.

**Comment by UndeadDevel** [comment]
I'm just thinking to myself as I'm looking through this again: isn't it a bug that DoUpdatePeaceTreatyWillingness is called before DoUpdateWarDamageLevel in DoBeginDiploWithHuman inside CvDiplomacyAI.cpp?

If I understand the code correctly, a human triggering the function DoBeginDiploWithHuman by clicking on the civ's portrait button in the EUI NotificationPanel, for example, means that DoUpdatePeaceTreatyWillingness will call IsWillingToMakePeaceWithHuman, which will call IsWantsPeaceWithPlayer, which will eventually call GetWarScore, which will simply retrieve a value that could very well be outdated at that point, right?
In the DoTurn routine it also calls it the other way around...I mean unless it somehow updates when the AI's units are killed, for example, since units are one part of what it looks at, the AI will actually have the wrong idea about what it lost when considering the kind of peace deal it's willing to make; I could theoretically destroy their entire army and take half their Cities in one turn and they could think that everything is fine...in fact, I often had the feeling that the AI is weirdly inconsistent about peace willingness sometimes; this could explain some of those cases.

@HeathcliffWarriors should I make a separate bug report? (In case my comment is too confusing: I think that the two calls in CvDiplomacyAI.cpp, on lines 29252 and 29253, should be switched).

**Comment by HeathcliffWarriors** [comment]
@UndeadDevel All good. :)

**Comment by UndeadDevel** [comment]
No problem, welcome back!

**Comment by HeathcliffWarriors** [comment]
@UndeadDevel Not quite back yet, personal issues are proving challenging. My current projection is that I should be at the start of February or thereabouts.

**Comment by UndeadDevel** [comment]
Oh okay, well good luck and take your time!
