### ISSUE TITLE
Crash on turn 316

### ISSUE THREAD

**Issue by TOLYANJIGAN** [LoneGazebo/Community-Patch-DLL#6120]
_1. Mod version (i.e Date - 4/23):_
(12-20-3)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Game crushes right after new turn begin after autosave

_4. Steps to reproduce (optional):_
Skip the turn
[civ.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4063881/civ.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
@TOLYANJIGAN Are you using the 12-30 DLL fix I posted?

**Comment by HeathcliffWarriors** [comment]
https://forums.civfanatics.com/threads/new-beta-version-december-20th-12-20.652983/page-7#post-15628785

**Comment by TOLYANJIGAN** [comment]
No, i didn't. Will install and check today.

**Comment by TOLYANJIGAN** [comment]
It fixed, thank you.
