### ISSUE TITLE
New Natural Wonders

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6121]
I found such mod, but it used some changes to dll structure. Do you know if it was incorporated into VP?
https://forums.civfanatics.com/threads/wondrous-nature.573645/

**Comment by LoneGazebo** [comment]
Not sure!

**Comment by LoneGazebo** [comment]
Worst you can do is try it out. :)

**Comment by adaneslavo** [comment]
Ok. I will do it someday. If I knew something more I will call you or other modder :)

**Comment by adaneslavo** [comment]
Ok, I dig something in the code of that mod. There were uploaded changes to dll file needed to make natural wonders work.
[0001-Added-PseudoNaturalWonder-feature-type.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4552538/0001-Added-PseudoNaturalWonder-feature-type.zip)

This code should to something like this:
- check for NaturalWonder tag in Features table to know if feature is a natural wonder;
- check for PseudoNaturalWonder tag in Features table to know what model it has (it uses sort of improvement method for applying model, because without that it uses default model for Fuji).

DLL changes from that mod were ported to CP (Vox Populi) by @Iamblichos. I copied all sqls, added models etc, but still got Fuji model regardless of what model I have in my mod folder.

Can someone help me verify if those changes are correctly ported from dll to vp? This is the only things that stands between my plan to add more natural wonders to the game. I even started to learn 3D modeling for that :P. @HungryForFood, @LoneGazebo, @ilteroi?

**Comment by adaneslavo** [comment]
I don;t want to be rude, but will anyone help me with that issue? @RecursiveStar @HungryForFood? It's not probably a big thing for you, the DLL veterans, to check this out and give me some advice or solutions or fixes :) , but for me is an important milestone which make be break through the impassable obstacle.

**Comment by Iamblichos** [comment]
The mod works fine for me. Let me check and see if you have to do database update for Custom mod options.

**Comment by Iamblichos** [comment]
@adaneslavo, show me how you setup your mod for the pseudonatural wonders.

**Comment by adaneslavo** [comment]
Look here:
https://github.com/adaneslavo/More-Wonders-for-VP/blob/master/2.NaturalWonders/XML/NaturalWondersParameters.xml
and here:
https://github.com/adaneslavo/More-Wonders-for-VP/tree/master/2.NaturalWonders/Art

**Comment by Iamblichos** [comment]
Is that all the database updates/insertions you are doing? you need more than that. Can you give me your whole SQL or XML file?

**Comment by Iamblichos** [comment]
AssignStartingPlots needs to be able to generate for PseudoNaturalWonder. 

In function: AssignStartingPlots:GenerateNaturalWondersCandidatePlotLists() it needs this code:

```
self.wonder_list = table.fill(-1, self.iNumNW);
	local next_wonder_number = 1;
	for row in GameInfo.Features() do
		if (row.NaturalWonder == true or row.PseudoNaturalWonder == 1) then
			self.wonder_list[next_wonder_number] = row.Type;
			next_wonder_number = next_wonder_number + 1;
		end
	end
```

**Comment by adaneslavo** [comment]
I added those changes in AssignStartingPlots. I missed that. I will tell you if it helped.

**Comment by adaneslavo** [comment]
Here on github you have all the most up to date files:
https://github.com/adaneslavo/More-Wonders-for-VP
All relevant additions are in NaturalWondersParameters.xml;
Spawning conditions are in NaturalWondersLocations.xml;

As I said I added that change in AssignStartingPlots.lua, but it didn't help

**Comment by adaneslavo** [comment]
> 
> 
> Is that all the database updates/insertions you are doing? you need more than that. Can you give me your whole SQL or XML file?

Heh, no, there are more of them. All texts, placing, values, abilities are ok. Only model is missing.

**Comment by Iamblichos** [comment]
Where is your code for Natural_Wonder_Placement? Like this:

INSERT INTO Natural_Wonder_Placement
			(NaturalWonderType,			OccurrenceFrequency,	AvoidFreshWater,	LandBased,	CoreTileCanBeAnyTerrainType,	CoreTileCanBeShallowWater,	AdjacentTilesCareAboutPlotTypes,	AdjacentTilesAvoidOcean,	MaximumAllowedAdjacentOcean)
VALUES		('FEATURE_GIANTS_CAUSEWAY',	10,						1,					0,			0,								1,							1,									1,							5);

**Comment by Iamblichos** [comment]
You don't need to define the new ones as a NaturalWonder and PseudoNaturalWonder. Do it like this:

```
INSERT INTO Features
			(Type,						Description,						Civilopedia,									ArtDefineTag,						OccurrenceFrequency,	Movement,	SeeThrough,	TurnDamage,	Defense,	Impassable,	InfluenceCost,	InBorderHappiness,	PseudoNaturalWonder,	AddsFreshWater,	NoImprovement,	Rough,	YieldNotAdditive,	PassableTechFeature,	PortraitIndex,	IconAtlas)
VALUES		('FEATURE_SALAR_DE_UYUNI',	'TXT_KEY_FEATURE_SALAR_DE_UYUNI',	'TXT_KEY_CIV5_FEATURES_SALAR_DE_UYUNI_TEXT',	'ART_DEF_FEATURE_SALAR_DE_UYUNI',	10,						1,			0,			0,			10,			0,			-3,				0,					1,						1,				1,				0,		1,					NULL,					7,				'CIVREL_ATLAS_6'),
			('FEATURE_GIANTS_CAUSEWAY',	'TXT_KEY_FEATURE_GIANTS_CAUSEWAY',	'TXT_KEY_CIV5_FEATURES_GIANTS_CAUSEWAY_TEXT',	'ART_DEF_FEATURE_GIANTS_CAUSEWAY',	10,						1,			0,			0,			25,			0,			-3,				0,					1,						0,				1,				1,		1,					NULL,					8,				'CIVREL_ATLAS_6'),
			('FEATURE_EVEREST',			'TXT_KEY_FEATURE_EVEREST',			'TXT_KEY_CIV5_FEATURES_EVEREST_TEXT',			'ART_DEF_FEATURE_EVEREST',			10,						1,			3,			50,			100,		1,			-3,				3,					1,						0,				1,				1,		1,					'TECH_CHIVALRY',		9,				'CIVREL_ATLAS_6');
```

**Comment by Iamblichos** [comment]
Never mind I found your code for Natural_Wonder_Placement:

**Comment by Iamblichos** [comment]
Which file are you doing: ArtDefine_Landmarks

**Comment by adaneslavo** [comment]
NaturalWondersParameters.xml
```
<ArtDefine_Landmarks>
		<Row>
			<Era>Any</Era>
			<State>Any</State>
			<Scale>1</Scale>
			<ImprovementType>ART_DEF_IMPROVEMENT_NONE</ImprovementType>
			<LayoutHandler>SNAPSHOT</LayoutHandler>
			<ResourceType>ART_DEF_FEATURE_SALAR</ResourceType>
			<Model>feature_Salar.fxsxml</Model>
			<TerrainContour>1</TerrainContour>
		</Row>
		<Row>
			<Era>Any</Era>
			<State>Any</State>
			<Scale>1</Scale>
			<ImprovementType>ART_DEF_IMPROVEMENT_NONE</ImprovementType>
			<LayoutHandler>SNAPSHOT</LayoutHandler>
			<ResourceType>ART_DEF_FEATURE_CAUSEWAY</ResourceType>
			<Model>feature_Causeway.fxsxml</Model>
			<TerrainContour>1</TerrainContour>
		</Row>
		<Row>
			<Era>Any</Era>
			<State>Any</State>
			<Scale>1</Scale>
			<ImprovementType>ART_DEF_IMPROVEMENT_NONE</ImprovementType>
			<LayoutHandler>SNAPSHOT</LayoutHandler>
			<ResourceType>ART_DEF_FEATURE_MT_EVEREST</ResourceType>
			<Model>feature_Everest.fxsxml</Model>
			<TerrainContour>1</TerrainContour>
		</Row>
	</ArtDefine_Landmarks>
```

**Comment by Iamblichos** [comment]
I'm not seeing anything here that should be problematic.

**Comment by adaneslavo** [comment]
Crap... In AssignStartingPlots, those mentioned were the only changes you've made for this mod?

**Comment by adaneslavo** [comment]
Here's how Mt. Everest looks like:
![20200811175553_1](https://user-images.githubusercontent.com/33016300/89919826-0af08d80-dbfc-11ea-9f7e-03c3e7296b41.jpg)
This red marker is strange...

**Comment by Iamblichos** [comment]
Yeah mine look right on the map so I know for fact it works. This is quite odd. But I also use a modpack. I wonder if there is an issue using this as a straight up mod. What if you made a modpack of all this and try it?

**Comment by Iamblichos** [comment]
Seems like an artdefine tag problem or a problem with the art files themselves.

**Comment by adaneslavo** [comment]
Once I tried to make a modpack, but with no success. If you know how to do it, please do if you have some spare time, but honestly I don;t think it will change the thing.

When I deleted column NaturalWonder from Features table like you posted earlier, NW spawned, but no additional feature model was applied (Everest became just regular Mountain f.e.).

**Comment by adaneslavo** [comment]
Do you use it with VP or with your own file?

**Comment by adaneslavo** [comment]
You were right!

I copied again files, but didn't change their names (I did it before, because I like to have everything in order :)). And everest shown up! But scaling is awful...
![20200811183717_1](https://user-images.githubusercontent.com/33016300/89924084-cec02b80-dc01-11ea-867b-307832858424.jpg)

**Comment by Iamblichos** [comment]
![image](https://user-images.githubusercontent.com/14372214/89924403-94399d00-dbc7-11ea-9c6a-af529872fc63.png)

**Comment by Iamblichos** [comment]
Good job! Glad you got it cleared up! Now you can just tweak the scaling.

**Comment by adaneslavo** [comment]
Thanks for your help.

**Comment by adaneslavo** [comment]
@Iamblichos I did the same for rest of the stuff, but...
For Mt everest and Giant's Causeway is much better because model shown up. As you can see on the picture below, graphics for changed terrain didn't update (for Giants causeway it should be Coast, but is still green Hill/Mountain). Same for Salar. Sv view can see changed types of terrain, but models didn't change. Any idea?
![20200811185844_1](https://user-images.githubusercontent.com/33016300/89928424-1ba70080-dc08-11ea-97c3-6ac1d60c58b0.jpg)
![20200811191818_1](https://user-images.githubusercontent.com/33016300/89928426-1cd82d80-dc08-11ea-9278-da646394198b.jpg)
![20200811191821_1](https://user-images.githubusercontent.com/33016300/89928431-1e095a80-dc08-11ea-872e-09cd58aef4eb.jpg)

**Comment by Iamblichos** [comment]
I don't do any lua stuff at all, mine looks correct.

**Comment by adaneslavo** [comment]
Fixed. Once again thanks for help :)
