### ISSUE TITLE
City ID changing after each conquer

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6122]
VP 12-20-3: I used function added to CityCaptureComplete with attributes:
(iOldOwner, bIsCapital, iX, iY, iNewOwner, iPop, bConquest)
On game load I checked for cityID containing wonder and saved it: 1070.
Then I made AI conquer my city and using iX and iY values I found current city ID: 1082.
Further, I conquered this city again. Its ID: 1090.
I made again AI to reconquer the same city. ID: 1093.
Reloaded the game. ID: 1093.

Why it is changing? I cannot compare these values because code treats them as totally different cities. Any ideas?

**Comment by adaneslavo** [comment]
I made this code work other way, but issue still concerns me...

**Comment by LoneGazebo** [comment]
It changes because city code is controlled player by player.

**Comment by ilteroi** [comment]
yeah it's stupid, capturing a city destroys the old one and creates a new one in its place. same for captured units btw.
