### ISSUE TITLE
1/11 - Anti-warmonger bonus higher than cap

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6123]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Possible that with the new system, it was intended that the cap is higher, but the cap is now higher than the previous 49% on Immortal max.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/72484376-a5553380-37c9-11ea-8936-9ab230eefa52.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Cap is controlled by an XML constant in the difficulty table.

**Comment by HeathcliffWarriors** [comment]
Cap is 65% on Immortal (see DifficultyMod.xml).
