### ISSUE TITLE
Naval Ships passing through Cities

### ISSUE THREAD

**Issue by Murderologist** [LoneGazebo/Community-Patch-DLL#6127]
_1. Mod version (i.e Date - 4/23):_
1-11

_2. Mod list (if using Vox Populi only, leave blank):_
Just Vox Populi 

_3. Error description:_ 
Everything functions fine. I however can not move my naval ships through key allied city state cities. In the past I was able too.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
hmm. i don't know what the intended behavior is here. moving military through other players' cities sound like an unintended feature to me ...

**Comment by Murderologist** [comment]
Quite the contrary if the city is Istanbul and is the only port city with access to the Black Sea it becomes very very key in getting naval units  in there or passage Panama City state instead of going all the way around. Again you don’t get to go through the city if you aren’t friendly or allied with the state. It was there before and now it’s not accessible

**Comment by azum4roll** [comment]
It's a thing in BNW. Not sure when this was changed in VP.

**Comment by Murderologist** [comment]
I thought I had it before in vox populi I could be mistaking but it’s a feature I wish would be added back as it really highlights the benefits of forming alliances with key city states.

**Comment by Vyyt02** [comment]
This was definitely possible a few versions back. I clearly remember commencing a surprising naval assault through an allied city state.

**Comment by Murderologist** [comment]
I’d like to see this come back

**Comment by ilteroi** [comment]
well there is this piece of code:

```
		if (!IsCivilianUnit() && plot.isCity() && plot.getOwner() != getOwner())
		{
			return false;
		}
```

so this doesn't seem like a bug, but intentional. i didn't put it there so i won't touch it.

**Comment by Murderologist** [comment]
Ok where is it and how do we change it for people who want it reverted?

**Comment by azum4roll** [comment]
It has never been possible in VP since I started playing with the mod (in 2018). Only civilian units can pass through allied CS city tile.

**Comment by ryanmusante** [comment]
Pass through the center city tile or tiles within the city proximity?

**Comment by Murderologist** [comment]
How or what do I need to alter to allow naval units to pass

**Comment by UndeadDevel** [comment]
@Murderologist  You'd need to change appropriate code in the DLL source and recompile the DLL, so it's not an easy fix (if you knew how to do that you wouldn't be asking what to do, no offense).

It would be better to try to convince people on the forum that this should be officially changed for everyone.

**Comment by Murderologist** [comment]
Well considering it was in the base game and was removed from this intentionally I don’t see why they shouldn’t put it back. It wasn’t ground breaking at all. It was more strategic. Now it’s completely removed from the game for what? I don’t see the imbalance here with earning positioning or access to bodies of water if you develop the friendship with these city states.

**Comment by UndeadDevel** [comment]
I agree, but this is not the place to discuss that.

**Comment by Murderologist** [comment]
Ok well I was told to post it here so I did

**Comment by ilteroi** [comment]
yeah, if it's a bug this is the right place, but since it's a judgement call you should try and get a consensus about the intended behavior on the forum
