### ISSUE TITLE
12/1-1 Wrong HP tooltip for units with max HP > 100

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#6128]
_1. Mod version (i.e Date - 4/23): 12/1-1

_2. Mod list (if using Vox Populi only, leave blank): Many mods

_3. Error description: The tooltip for hit points of a unit with max hitpoints greater than 100 is showing a wrong number in the combat preview. See the attached screenshot - the rifleman has 14 HP left (out of max 115 = boosted over 100 by the Field Works promo), but the tooltip is showing it has -1 HP left (= ignoring the Field Works extra +15 HP)
![civ-hp](https://user-images.githubusercontent.com/11929356/72566806-c2b2fc00-38b4-11ea-804d-e9e4e0a2a483.jpg)

4. Screenshots (optional):

**Comment by UndeadDevel** [comment]
Are you sure you are using the latest PFEUI4VP? Because I'm pretty sure you're not.

The latest version is [here](https://forums.civfanatics.com/resources/promotion-flags-eui-for-vp.27909/).

**Comment by Vyyt02** [comment]
Ohhh, ok, thanks, I'll try it over the weekend and report back.

**Comment by UndeadDevel** [comment]
No I mean the Promotion Flags EUI mod that you are using...did you get the special version of it that I made and posted in the Community Patch Forum (Mods Repository) or are you using the old one that is posted in the general Civ 5 modding forum? Only my version has the updates that fix Health Bars in VP.

**Comment by UndeadDevel** [comment]
Yeah I just tested it with the latest PFEUI4VP and it is not bugged there, so the problem lies with your (old) version of it or some other mod that you're using that is overwriting UnitPanel.lua...

**Comment by Vyyt02** [comment]
That was it, thanks! I will update the Compatible mods list accordingly.
