### ISSUE TITLE
How Can I disable just the CP AI?

### ISSUE THREAD

**Issue by iskaandismet** [LoneGazebo/Community-Patch-DLL#6134]
Hey CP ppl! 

Just wondering how I can disable the new AI, but leave the APi extensions intact. Is I set to 0
COMMUNITY_CORE_BALANCE
COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS
in CommunityOptions.sql, this doesn't seem to change their behaviour. Thanks!

**Comment by LoneGazebo** [comment]
Not gonna happen.
