### ISSUE TITLE
Pathfinder not choosing optimal paths

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6135]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2)
UI - Religion Spread (Vox Populi) (v 1.1)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
See screenshots: in the first and third screenshot the path chosen is (almost) optimal but in the second and fourth a path to a tile adjacent to the tile of the previous screenshot is definitely not optimal and would take far longer than necessary to complete. This happens especially often when the unit has the option of embarking / disembarking on their way to the destination.
In the second screenshot the unit would waste only one turn (still not good, though), but in the fourth screenshot it would waste more than three turns and therefore make the travel take more than twice as long as necessary! The optimal path here would be to embark to the West of Rome and stay embarked until reaching the Coastal tile adjacent to the target, which would only take three turns, including the final disembarking action and is thus less than half the number of turns the chosen path would take. Note how this means that the path in the third screenshot is also sub-optimal, though in a less severe way (only wastes some movement points it could have had left over in that last turn of movement).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0000-Civ5Screen0008](https://user-images.githubusercontent.com/30495439/72659380-92538680-39b6-11ea-9e05-8984c9fe8e4f.jpg)
![Civ5Screen0000-Civ5Screen0009](https://user-images.githubusercontent.com/30495439/72659382-94b5e080-39b6-11ea-8548-bc7b377e7ed4.jpg)
![Civ5Screen0000-Civ5Screen0010](https://user-images.githubusercontent.com/30495439/72659383-95e70d80-39b6-11ea-8bd9-bf0227db9037.jpg)
![Civ5Screen0000-Civ5Screen0011](https://user-images.githubusercontent.com/30495439/72659384-997a9480-39b6-11ea-8973-1c37b10dfb8a.jpg)

**Comment by ilteroi** [comment]
yeah, embarkation is annoying. i agree that case 4 is not great ... i'll keep an eye on it and see if i can reproduce it

**Comment by bigcat88** [comment]
@ilteroi look at Denmark. Pathfinding there are broken much greater.(i can generate images with description like this)
offtop question: is this normal that with one pathfinder in 50% of cases i can take barbarian camps without fight? looks like barbarians don't know that pathfinder can get Ignore ZOC and attack it as usual unit.(this happens in my every game so if you need save or pic i can post it)

**Comment by ilteroi** [comment]
seems this was cause by the different movement speed in water vs land. should be better now ...
