### ISSUE TITLE
No explanation for "Accept Embassy" unavailability.

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6136]
_1. Mod version (i.e Date - 4/23):_latest

No red-colored text explaining why "Accept Embassy" diplomatic option isn't possible.

![20200118120440_1](https://user-images.githubusercontent.com/16341598/72662096-4f5fd600-39eb-11ea-8fc3-0ca12ab00c54.jpg)

**Comment by RecursiveVision** [comment]
Will fix soon.

**Comment by RecursiveVision** [comment]
By soon, I meant "a year and a month later". :)

In my defense, this code was hell to clean up, rewrite and debug!
