### ISSUE TITLE
Military supply too low when starting a game in later eras

### ISSUE THREAD

**Issue by mt-empty** [LoneGazebo/Community-Patch-DLL#6143]
1. Mod version (i.e Date - 4/23):
Vox Populi (1-11-2)

2. Mod list (if using Vox Populi only, leave blank):

3. Error description:
Military supply too low when starting a game in later eras(deity).

4. Steps to reproduce (optional):
start a game in atomic era, military supply will be 5/1 unit.
![1](https://user-images.githubusercontent.com/59728838/72681159-bdbe9a00-3ab8-11ea-9431-0aed72902df6.jpg)

**Comment by UndeadDevel** [comment]
AFAIK VP isn't really compatible with starts in later Eras.

**Comment by HeathcliffWarriors** [comment]
Advanced starts are, as Gazebo described it, "totally borked. Another problem for another day..."

**Comment by HeathcliffWarriors** [comment]
Could add +1 or +2 flat supply per game era as a quick fix?
