### ISSUE TITLE
Train station cannot be built in one city challange 

### ISSUE THREAD

**Issue by mt-empty** [LoneGazebo/Community-Patch-DLL#6144]
_1. Mod version (i.e Date - 4/23):_
Vox Populi (1-11-2)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Train station cannot be built in one city challenge, I think it is due to lack of a connected owned city via railroad.

_4. Steps to reproduce (optional):_

**Comment by UndeadDevel** [comment]
You can probably fix this by building a Railroad improvement a tile adjacent to the City, but maybe there should be an exception for the case of One-City-Challenge being enabled...

**Comment by mt-empty** [comment]
@UndeadDevel, I tried it doesn't work, 
I even tried connecting it to a city state or AI cities.
