### ISSUE TITLE
France's unique ability is powerful, might need adjustment

### ISSUE THREAD

**Issue by mt-empty** [LoneGazebo/Community-Patch-DLL#6146]
_1. Mod version (i.e Date - 4/23):_
Vox Populi (1-11-2)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
France's unique ability is very powerful, 40% production for 15 turns and 40% culture for 22 turns(epic speed) for capturing a city of 30 pop. 

On deity, by the industrial era major cities can easily grow around 20, capital even higher. One can easily get 50 turns of production and 75 of culture boost by capturing 5 cities.

The culture is even higher than that of the word's fair.

Maybe have it scaled down with eras.

_4. Steps to reproduce (optional):_

**Comment by UndeadDevel** [comment]
This isn't really a bug but more a balance concern so you should post it in the appropriate Leader thread in the "Leader Balance" subforum...I'll just give you the [link](https://forums.civfanatics.com/threads/france.546883/) to it.

**Comment by mt-empty** [comment]
@UndeadDevel yea you are right, feel free to make a thread if you want.
