### ISSUE TITLE
City HP upon capture very inconsistent

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6147]
_1. Mod version (i.e Date - 4/23):_
1-11-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This has been mentioned multiple times now on the forums and I've observed it myself: the HP a freshly captured City has is very inconsistent...there does not seem to be much of a pattern associated with it.
Furthermore, sometimes the City will have 0 HP upon capture, which means it will be really easy to retake the next turn even if a strong unit is garrisoned there, which in those cases pretty much eliminates the benefit of the garrison-gives-minimum-strength-system that was implemented.

Therefore the City should never have 0 HP after being captured (probably a minimum of 100 HP would be a good value) and captured Cities should either always have the same HP or at least the HP amount should be predictable to some degree (maybe dependent on siege length or damage dealt to it the last few turns or whether it was blockaded or not or something else that is known).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by mt-empty** [comment]
felt the inconsistencies as well in my last game
