### ISSUE TITLE
City expanding into unreachable non-strategic resource

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6148]
_1. Mod version (i.e Date - 4/23):_latest

![20200119213807_1](https://user-images.githubusercontent.com/16341598/72687190-339c2300-3b04-11ea-8402-e1abfa5a267b.jpg)

Would it be possible to code so that a city doesn't prioritize expanding borders into unreachable non-strategic/non-luxury resource?

**Comment by ilteroi** [comment]
really moving into corner cases here, but easily fixed.

at least i think so, i don't have a testcase at hand

**Comment by mt-empty** [comment]
Hijacking this issue. 
The Huns can expand beyond the 5 tile city limit with their UA, I'm guessing that is a feature not a bug.

**Comment by HeathcliffWarriors** [comment]
@mt-empty Yeah, that's intentional.
