### ISSUE TITLE
Wrongfully accused of plundering trade

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6149]
_1. Mod version (i.e Date - 4/23):_latest

It seems there is a bug in Morocco's attitude. One of his negative attitude modifiers says "You plundered their trade routes". The point is I never was at war with him and therefore was never able to do it. **But he did plunder** my routes using his special ability.

![20200119224048_1](https://user-images.githubusercontent.com/16341598/72688159-42d39e80-3b0d-11ea-90ab-49dac4f7552f.jpg)

**Comment by HeathcliffWarriors** [comment]
@saamohod Plundering another player's trade routes leading to their cities also counts.
