### ISSUE TITLE
Open Borders not allowing unit passage

### ISSUE THREAD

**Issue by kd5crs** [LoneGazebo/Community-Patch-DLL#6150]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_
Faster Aircraft animations, Quick Turns, RED units

_3. Error description:_ 
When Open Borders are in effect, it doesn't actually allow units to enter the Open Borders Civ. In the India game you can see it with Siam, and in the Portugal game you can see it with the Dutch and Danes (who are capitulated vassals). There's just the red circle for invalid move.

_4. Steps to reproduce (optional):_
It seems to happen every game, and all kinds of Open Borders.

(Loving Vox Populi, thanks for making it!)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.
[Gandhi_0219 AD-1545.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4083686/Gandhi_0219.AD-1545.zip)
[Maria I_0361 AD-1941.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4083687/Maria.I_0361.AD-1941.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4083690/Logs.zip)

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
@kd5crs Using the latest hotfix?

**Comment by kd5crs** [comment]
Newest hotfix did the trick. Thanks!
