### ISSUE TITLE
Automated Ambassador not working

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6154]
_1. Mod version (i.e Date - 4/23):_1-11-2

![20200120172353_1](https://user-images.githubusercontent.com/16341598/72738228-ccd14500-3ba9-11ea-8789-bef16163cbb3.jpg)

Automation button says there aren't valid diplomacy targets at this time, but it isn't true. There are plenty of City States who aren't friends or allies with me. Even if all the CS's were my allies they'd still be valid targets.

**Comment by ilteroi** [comment]
are they far away? there was a fix for that recently, i think it was to late for the release ...

**Comment by saamohod** [comment]
Well, there were CS close and far. Some allies, some friends, some neutrals. I don't understand how ambassador's auto-logic works, but for me it seems that it never does any harm to keep pumping even allies with influence. A hundred or two turns later I had a look at the auto-mission button and it was back on.
