### ISSUE TITLE
Cities without airport can accommodate more than 2 aircraft 

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6155]
_1. Mod version (i.e Date - 4/23):_1-11-2

Not sure how I should treat this issue. I reported it 2 months ago and the issue was later closed, but apparently not fixed (https://github.com/LoneGazebo/Community-Patch-DLL/issues/5827)
Should I presume it cannot be fixed?

TL;DR:
 It's possible to accommodate more than 2 aircraft units in a city without an airport by simply right clicking the unit to rebase to that city.

**Comment by LoneGazebo** [comment]
@ilteroi missing a check?

**Comment by ilteroi** [comment]
funny. the rebase mission doesn't work but right-click does ... there is no call to canRebaseAt(), just a direct move mission. 

i could put in a hack but this should really be fixed in lua ... any takers?

**Comment by LoneGazebo** [comment]
Taker took

**Comment by ilteroi** [comment]
do you differentiate between attacking (move mission) and rebasing (rebase mission) in lua?
