### ISSUE TITLE
Hovering Units not taking damage over Mountains

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6156]
_1. Mod version (i.e Date - 4/23):_
1-11-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
According to the help text of PROMOTION_HOVERING_UNIT those units are supposed to take damage when ending their turn on a Mountain tile...they're not; if that's intentional the description would need to be changed.

_4. Steps to reproduce (optional):_
place / move Helicopter or Zeppelin on Mountain tile and press next turn.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by UndeadDevel** [comment]
Alright the fix has been merged, thanks! Closing...

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo The text is fixed, but is this intentional?

**Comment by UndeadDevel** [comment]
Well I assume so, since he merged it...the text change signifies that taking damage is not the intention.
