### ISSUE TITLE
Strategic Defense System and New Random Seed

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6158]
_1. Mod version (i.e Date - 4/23):_1-11-2

I rarely run my games until all out nuclear warfare. What happened in my current game is probably a bug, or my lack of understanding of some game mechanics.

 I try to drop an atomic bomb on an enemy city (and within 2 hexes, too) but it gets destroyed and zero damage is dealt. I guess this is SDS at work. The problem is it gets destroyed each time I reroll the savegame. I reloaded 10 times. New Random Seed is on in my current game. SDS's chance of destroying the nuke is 50% according to description, and this is not how 50% chance should be working 10 times in a row I guess.

Something doesn't add up. It's either the SDS success chance is way higher than 50% or New Random Seed option doesn't work. Or I don't quite understand something.

**Comment by LoneGazebo** [comment]
That option doesn’t do anything. Hasn’t for years.

**Comment by saamohod** [comment]
Good to know. Wish I'd known before.
Closing.
