### ISSUE TITLE
Workers Not Constructing Improvements

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6159]
_1. Mod version (i.e Date - 4/23):_ 1-11 (with hotfix)

According to multiple players in the 1-11 beta version thread, AI Workers are not doing a good job of constructing improvements, and take forever to connect resources.

Apparently they're idling in cities a lot as well.

@ilteroi

**Comment by HeathcliffWarriors** [comment]
I initially mentioned similar behavior in #5856 (first post) but don't know if any action was taken - I suspect this bug has been around for a few versions now.

**Comment by ilteroi** [comment]
works fine for me ... i'll watch it

**Comment by adaneslavo** [comment]
I don't know if it is connected, but I noticed that when I automate my pathfinder he just stops in weird places even if there're many places to discover. Especially on archipelago map when he must cross water. I can see land behind water, but he stops. Clicking automate gives no result. Only manual move order works.
