### ISSUE TITLE
Bugs from forums

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#616]
Check pantheons not firing after religion - done
Check CP for lua errors
Bump WLTKD from GM (static + scaling) - done
Fix WLTKD not firing on unhappiness - done
Check AI diplomacy values out of peace - done
Check duration promise value tick value - done
Check settling bug when capturing a city - looked at
AI giving up on peace treaties - worked on
Razing and conscription working together - fixed

**Comment by ilteroi** [comment]
fyi, i had two crashes but no idea how to fix them

- one without debugger, callstack log was empty (why?)
- one with debugger, callstack not very helpful, see screenshot. the null pointers in the building infos at the bottom are especially alarming

![image](https://cloud.githubusercontent.com/assets/1358966/9825154/d18f5c36-58d1-11e5-8e30-4c6cd13642e2.png)

**Comment by LoneGazebo** [comment]
Was the DLL optimized or not when it crashed? Null values can sometimes pass into the debugger, even though they aren't actually null in reality.

Might be a notification message bugging out - especially since it was called in gameturn, and also calls for a civadjective key (or at least it seems to, given your watch 1 area).
