### ISSUE TITLE
1/11 - Ranged Combat Defense not calculating properly

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6160]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In this example, the defense value of the crossbow is much too low. It looks like it is only getting a +60%, assuming its using CS for defense (and correct me if I'm wrong but ranged units are supposed to use their RCS for defense against ranged attacks). 

I confirmed that the expected damage is what the unit did, so its not just a visual error, but an actual combat calculation.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/72923747-476aa380-3d15-11ea-8a74-a19560556bd0.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
several points ...

1. it seems the "anti-warmonger fervor" is called ResistancePower in the DLL ... it's only applied for melee combat. probably an oversight.

2. RCS is used when ranged units defend against ranged attacks:
iDefenderStrength = pDefender->GetMaxRangedCombatStrength(...)

3. "ranged attack modifier" on the defender seems weird

4. we need a bonus of 20% but the remaining bonuses still add up to 40%

**Comment by Aqinu** [comment]
>     3. "ranged attack modifier" on the defender seems weird
It's from +5% rcs from each barrage bonus which works for offense and defence...

**Comment by LoneGazebo** [comment]
I think this is the right time to finally decide that anything not explicitly 'ranged' shouldn't be included in melee defense, and vice-versa...

**Comment by BlittzzXander** [comment]
This crossbow should have had 43 combat strength if we sum and multiply all bonuses. There are +115% of bonuses, so 20 RCS x 2.15 = 43 RCS, but it shows 24.
