### ISSUE TITLE
Typo (?): National Intelligence Agency

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6162]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2)
UI - Religion Spread (Vox Populi) (v 1.1)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
According to the description of the National Intelligence Agency it provides 1 additional spy; however, in my current game I received 3, so either the description is wrong or it's not working as intended. The number may be based on a fraction of the amount of City States in the game or it may be a flat 3, I don't know.

Don't forget to update the description / functionality of the White Tower as well, depending on what the problem is.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
I tested it, and it's fine (gives only 1 spy), maybe you got the other ones from different source...

**Comment by UndeadDevel** [comment]
Don't you think I would have checked for other sources?

Anyway, I just tested it with only VP (1-11-2) and IGE on Large, Epic and it gives 3 Spies. So I repeat: either this is intended and the description needs to change (I assume it's the Map Size / City States number or Game Speed that scales the number of spies) or the mechanics need to conform to the description.

**Comment by Aqinu** [comment]
You are right, my mistake, it's based on number of city-state (<20 CS you have as in description, >=20 you have +2, >=30 you have +3). Fixed this issue in other places...

**Comment by UndeadDevel** [comment]
Alright the fix has been merged, thanks! Closing...
