### ISSUE TITLE
Not possible to demand to stop proselytising 

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6163]
_1. Mod version (i.e Date - 4/23):_1-11-2

Pachacuti sends missionaries to my cities spreading his religion and displacing mine, but there is no dialogue option to ask him to stop doing that.

![20200125011743_1](https://user-images.githubusercontent.com/16341598/73110909-d5f74480-3f10-11ea-96e9-03e48db5b916.jpg)
![20200125011753_1](https://user-images.githubusercontent.com/16341598/73110910-d7c10800-3f10-11ea-9603-05fdd6869b9a.jpg)

**Comment by HeathcliffWarriors** [comment]
He needs to actually convert a city before the option becomes available. Firaxis rule choice.

**Comment by HeathcliffWarriors** [comment]
Could change it, but it'd require adding a new memory value.

**Comment by saamohod** [comment]
> 
> 
> Could change it, but it'd require adding a new memory value.

I'm almost certain I saw a case when my neighbor's missionary changed religion is one of my cities. I immediately went to diplomacy window and the option to stop sending missionaries wasn't there. The next turn it wasn't there either.

I'll try to pinpoint it when it happens next time.

**Comment by Vyyt02** [comment]
Same here, in my current game (12/1), an AI civ converted my 2 cities with Great prophets and the option in the diplomacy / discuss dialog is missing.

**Comment by HeathcliffWarriors** [comment]
That's odd. Will investigate.
