### ISSUE TITLE
Stone Works Typo

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6164]
_1. Mod version (i.e Date - 4/23): 1/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:
At the top of the description it's missing the 'Requires improved **Jade**...'(also **Uranium**), and I don't have any jade near the city so it should be mentioned because it is mentioned in Local Resources Required.
Also tested it in normal condition and it is shown, don't know what's the issue in my case (Second Screenshot)...

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![Civ5Screen0003](https://user-images.githubusercontent.com/49090452/73127157-f4b71300-3fc4-11ea-8eb1-481eb2fe6080.png)
![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/73127383-1c5baa80-3fc8-11ea-8472-9a6321e0c0f0.png)

**Comment by HeathcliffWarriors** [comment]
@Aqinu Second screenshot: you have Lapis Lazuli but it isn't improved.

**Comment by HeathcliffWarriors** [comment]
Now I'm tempted to make a modmod to add Redstone as a luxury resource 😄

**Comment by Aqinu** [comment]
@HeathcliffWarriors I know that, that's why I said that in the second screenshot everything is ok, but in the game somehow doesn't work correctly (not showing jade and uranium which are not present/improved in the 1st one)
