### ISSUE TITLE
Feature in Buildings: IsNoCoast

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6167]
Recently I met a problem which I solved using lua, but it could be added to sql.

Currently we have **Water** (Lake or Coast), **River**, **FreshWater** (Lake or River), **AnyWater** (Lake, Coast or River).
On the other side we have **IsNoWater** (no Lake nor River), **IsNoRiver**, but nothing that would forbid Coast. With **_IsNoCoast_** we could combine something like **_IsNoAnyWater_** (**_IsNoCoast_** + **IsNoWater**).

**AnyWater** description in CP on github is misleading and suggest that it works like **_IsNoAnyWater_**, but I checked that in game and it requires any water if set on true.

Also **IsNoWater** is not so obvious without looking inside code. Should be **_IsNoFreshWater_** to be consistent.

**Comment by LoneGazebo** [comment]
@ilteroi fixed this...

**Comment by adaneslavo** [comment]
May I ask, what was added or changed? Will it be implemented in upcoming beta?

**Comment by LoneGazebo** [comment]
>Also IsNoWater is not so obvious without looking inside code. Should be IsNoFreshWater to be consistent.

This

**Comment by LoneGazebo** [comment]
the others are feature requests

**Comment by HungryForFood** [comment]
Part of #7334, IsNoCoast will be in next version if merged.

**Comment by adaneslavo** [comment]
Awesome!
