### ISSUE TITLE
Can't pillage road under embassy when at war

### ISSUE THREAD

**Issue by mt-empty** [LoneGazebo/Community-Patch-DLL#6168]
_1. Mod version (i.e Date - 4/23):_
Vox Populi (1-11-2)

_2. Mod list (if using Vox Populi only, leave blank):_
reforestation
ingame editor
quickturn
Faster Aircraft Animations 
Really Advanced Setup

_3. Error description:_ 
Can't pillage road under embassy when at war
4. Screenshots (optional):
![1 (1)](https://user-images.githubusercontent.com/59728838/73149797-e21f0580-40ba-11ea-8801-7ec27a4e14a3.jpg)

**Comment by LoneGazebo** [comment]
Correct, on 'the stack' you can't pillage anything on a permanent tile.
