### ISSUE TITLE
Settler into pioneer upgrade costs -1 gold

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#617]
Haven't tested pioneer - colonist upgrade, but I assume it might be affected, too, since the recent introduction of upgrade cost cap.
![pioneer](https://cloud.githubusercontent.com/assets/12978597/9819901/4f95fc16-58b9-11e5-861c-991f0e3cf86d.jpg)

**Comment by LoneGazebo** [comment]
This is not, technically, a bug, but rather a small oversight on my part on how the max gold cost is handled.
