### ISSUE TITLE
Units in enemy tiles disappearing after making peace

### ISSUE THREAD

**Issue by mt-empty** [LoneGazebo/Community-Patch-DLL#6170]
1. Mod version (i.e Date - 4/23):
Vox Populi (1-11-2) 
Also in the previous beta 

2. Mod list (if using Vox Populi only, leave blank):
reforestation
ingame editor
quickturn
Faster Aircraft Animations
Really Advanced Setup

3. Error description:
Units disappearing after making peace. Only happens to units stationed in enemy tiles, can be noticed as "current military supply" goes by 1 or 2.
This bug was present in the previous beta as well. 

4. Steps to reproduce (optional):
**This bug cannot be easily reproduced**
1- Declare war with a civ.
2- Have some units stationed in enemy tiles.
3- Make peace with this civ.

4. Screenshots (optional):
At war  with rome
![1 (1)](https://user-images.githubusercontent.com/59728838/73151329-a720d000-40c2-11ea-88bc-30ebc527f0bc.jpg)
forced peace with ingame editor.
![1 (2)](https://user-images.githubusercontent.com/59728838/73151331-a7b96680-40c2-11ea-8eac-c47b7e5d32bf.jpg)

Save game:
[Ashurbanipal_0528 AD-1938.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4132548/Ashurbanipal_0528.AD-1938.zip)

The rocket artillery- the one inside Rome's territory next to landmark - will disappear after making peace(use IGE to force peace).

**Comment by saamohod** [comment]
Off-topic:

What map script did you use and what size? I love those massive continents, but also lots of water.

**Comment by mt-empty** [comment]
@saamohod ,
*  map : communitas
*  ocean rifts: None
*  everything else: default

**Comment by ilteroi** [comment]
can't reproduce ...

**Comment by mt-empty** [comment]
I have attached the save game.
The rocket artillery inside Rome's territory(next to landmark) will disappear after declaring peace(use IGE to force peace).
