### ISSUE TITLE
Futurism not giving culture to great works

### ISSUE THREAD

**Issue by crdvis16** [LoneGazebo/Community-Patch-DLL#6171]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_
VP+EUI only

_3. Error description:_ 
1)  futurism from Autocracy did not seem to give culture from great works as the tool tip indicates. 

2)  when playing Japan and producing tons of generals/admirals I seem to have hit a limit on creating music and writing works.  My musicians and writers only had the option to bulb (creating the great work was NOT greyed out, it was just gone).  I had available slots to place them as well.  Oddly, I could still make great works of art.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
1. Cannot reproduce
2. You ran out of great people

**Comment by UndeadDevel** [comment]
I think I've seen the Futurism issue, too, but IIRC the Culture did get added after a turn or two or after reloading or something like that...so it seems there might be an issue there but in my case it resolved itself pretty quickly.

Does it resolve itself for you after some turns / reload, @crdvis16 ?

**Comment by crdvis16** [comment]
I'm not sure- it was a game from a bit ago and I only checked my culture
before and after picking Futurism on a whim to see how much culture it
added.

As for the running out of great people thing- would it be possible to allow
generic "Great Writer/Musician/Artist" (similar to how you sometimes get
"Great General" instead of a historically named one?) as well as generic
Literature/Music/Art?  Though I don't think this situation happens
frequently so maybe it's just not a huge deal...

**Comment by crdvis16** [comment]
I'm in a game as Brazil now and at T333 I've again hit the limit on being able to create works of music.  I myself only have 7 works of music but perhaps other civs have created too many and the pool is shared?  I'm the only Tradition civ though...
