### ISSUE TITLE
Interceptor promotion for ironclads

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6172]
_1. Mod version (i.e Date - 4/23):_1-11-2

Interceptor promotion line for ironclads is shown but cannot be chosen and no explanation is given why.

![20200127154457_1](https://user-images.githubusercontent.com/16341598/73179519-3e664180-411c-11ea-8517-0f270f570030.jpg)

**Comment by UndeadDevel** [comment]
It says in the tool tip in your screenshot that it can only be chosen for "late game units with AirInterceptRange ability".

The Ironclad does not have that ability, therefore it can't choose the Interceptor promos (check the Civilopedia entry of units to see what abilities they have).

**Comment by saamohod** [comment]
Got it.
