### ISSUE TITLE
Interception

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6175]
_1. Mod version (i.e Date - 4/23):_1-11-2

An enemy bomber attacks my unit and gets intercepted by my fighter (according to the animation), but the bomber manages to hurt my ground unit and there is not mention of the successful interception in the log. It seem the animation  shows an interception when none takes place in reality.

**Comment by UndeadDevel** [comment]
Did the fighter perhaps not have Interceptor IV?
I've noticed in my games that Destroyers will make the "intercepting"-sound every time, but only apply the damage sometimes (when the 25% chance triggers)...maybe it's the same for air planes?

Also, the fact that air unit actions often don't get logged makes it very confusing to figure out what's going on / what happened.

**Comment by UndeadDevel** [comment]
Okay I've been testing air units a bit and the animations and text notifications are REALLY buggy...they very often don't correspond to what's actually going on, which is quite confusing, like no animation and no text message despite Interception happening (I know it happened due to changes in HP).

**Comment by LoneGazebo** [comment]
hmm
