### ISSUE TITLE
Liberated CS goes to vassal

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6177]
_1. Mod version (i.e Date - 4/23):_1-11-2

After I capture Bratislava (my former ally CS) from the Netherlands (my current enemy) and press Liberate option, Bratislava becomes a city of my vassal Aztecs instead of becoming a CS again.

![20200128031330_1](https://user-images.githubusercontent.com/16341598/73227607-b2d0cd00-417c-11ea-8d08-28f0e12d6b61.jpg)

**Comment by azum4roll** [comment]
Was Bratislava formed by revolution of an Aztecs city?

**Comment by saamohod** [comment]
> 
> 
> Was Bratislava formed by revolution of an Aztecs city?

Can't tell. I can only comment on what has happened. I ally Bratislava via diplomats, immediately declare war on their neighbor Netherlands. Netherlands eventually capture Bratislava. I recapture it after several turns, but liberation grants the city to my vassal Aztecs somehow.

**Comment by LoneGazebo** [comment]
It was probably a revolt CS.

**Comment by saamohod** [comment]
> 
> 
> It was probably a revolt CS.

Not sure if we understand each other correctly. 

Bratislava is a standard CS, it began as one. It wasn't an original Aztec city obviously therefore it didn't revolt from them.
https://civilization.fandom.com/wiki/Bratislava_(Civ5)

**Comment by LoneGazebo** [comment]
If a city revolts it can become a CS and rename itself

**Comment by HeathcliffWarriors** [comment]
If this is the case, can it be set so that the original owner of the revolt CS is flagged correctly? i.e. the city banner would say "this city originally belonged to X"
