### ISSUE TITLE
1/11 - Repealed World Religion cannot be Selected

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6178]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I have had Judaism as the world religion for several WC votes. It finally was repealed, and on the next vote, I was unable to select it, because the system says its "already in effect"

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/73235929-08de4a00-4156-11ea-9c2e-e87b0b7fc70d.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Pretty sure there's a one-session 'cool down' for the same resolution.

**Comment by Stalker012345** [comment]
I know there is a cool down for proposing the same resolution, but is there one for asking for a resolution that was just repealed?

**Comment by LoneGazebo** [comment]
Yes

**Comment by HeathcliffWarriors** [comment]
Text should indicate that, then.

**Comment by LoneGazebo** [comment]
It's just a wrong TT.
