### ISSUE TITLE
Vassal doesn't want his original capital

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6179]
_1. Mod version (i.e Date - 4/23):_1-11-2

May be intended, idk.

My vassal's original capital Ulundi isn't on the list of cities in diplomacy widow. I wanted to give it back to him but no chance.

![20200128202043_1](https://user-images.githubusercontent.com/16341598/73293481-a5fbba00-420c-11ea-99fb-33365bab4dfa.jpg)
![20200128202051_1](https://user-images.githubusercontent.com/16341598/73293486-a72ce700-420c-11ea-8cf6-edb7b7e77fe6.jpg)
![20200128202057_1](https://user-images.githubusercontent.com/16341598/73293492-a85e1400-420c-11ea-95ff-1346b9cecbc7.jpg)
![20200128202059_1](https://user-images.githubusercontent.com/16341598/73293497-aac06e00-420c-11ea-835c-fac70e98bcdf.jpg)

**Comment by HeathcliffWarriors** [comment]
@saamohod Can't trade a damaged city.
