### ISSUE TITLE
marsh on grassland gives 3 food

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#618]
see screenshot:

![image](https://cloud.githubusercontent.com/assets/1358966/9826431/8c06f102-58da-11e5-9bdb-2f3a97b94811.png)

is this by design?

**Comment by TechpriestEnginseer** [comment]
I'm pretty sure it's by design since features' yield will replace the regular tile's yield.

**Comment by LoneGazebo** [comment]
intended
