### ISSUE TITLE
Enemy caravel teleports under my ship and kills great admiral

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#6182]
_1. Mod version (i.e Date - 4/23):_

1/11 

So, this happened the other day. Looks like the City State caravel just executed a move command right on my corvette, which was guarding my great admiral. As a result, the GA got killed and my corvette got stacked with the enemy caravel. No damage was taken on either sides except for the GA.

![20200126230149_1](https://user-images.githubusercontent.com/12978597/73353532-346b4c80-429c-11ea-97d7-f0edee89ea96.jpg)

**Comment by LoneGazebo** [comment]
nani?

**Comment by ilteroi** [comment]
i'm confused. are you saying this was a normal move or a teleport? where did the caraval come from?

**Comment by Edaka** [comment]
Normal move. I could see the carsvel nearby the turn before. The next turn it ghosted through my ship, somehow ending its turn stacked with it. Notice on the screenshot there's an enemy caravel stacked with my corvette .

**Comment by ilteroi** [comment]
did the mongolian border expand? or did the city state have an alliance with mongolia which lapsed?

**Comment by Edaka** [comment]
It was on a mongolian plot earlier, yeah, although it wasn't on an adjacent one. It was at least a couple of tiles away.
