### ISSUE TITLE
Borobudur grants additional religion spreading to Great Prophets

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#6183]
_1. Mod version (i.e Date - 4/23):_
1/11

AFAIK, only missionaries should receive additional spreading. Also, after you use that additional spread on a Great Prophet, it can still build a holy site, which seems like an oversight.

Notice 5 charges on the Great Prophet.
![20200126010056_1](https://user-images.githubusercontent.com/12978597/73353775-c8d5af00-429c-11ea-8803-6616b9b01292.jpg)

**Comment by saamohod** [comment]
Can confirm. Built Borobudur, now my Prophets have 5 charges.

**Comment by Stalker012345** [comment]
damn, I thought this was intentional :(
