### ISSUE TITLE
AI builds landmark well outside city range

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#6184]
_1. Mod version (i.e Date - 4/23):_
1/11

Notice how that landmark is in the city's 5th ring. While it may still be beneficial to build it just for happiness, the actual bonus is pretty small without the actual yields, so the choice seems rather questionable.
![20200123224251_1](https://user-images.githubusercontent.com/12978597/73353840-fae71100-429c-11ea-8f5f-043516b4a64a.jpg)

**Comment by LoneGazebo** [comment]
It happens if they don't have free slots.

**Comment by Edaka** [comment]
Ah, makes sense.
