### ISSUE TITLE
Stop City Razing button doesn't work and isn't greyed out

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#6185]
_1. Mod version (i.e Date - 4/23):_
1/11

After having started to raze Iztapam, I tried to stop it but the button just didn't work. You could press it, it wasn't greyed out or anything, even the sound effect of pressing the button played. However, the city continued burning to the ground.

**Comment by LoneGazebo** [comment]
I'd need logs or something, likely lua log.

G

**Comment by mt-empty** [comment]
Same here with the latest version.

**Comment by Edaka** [comment]
Sorry for the late reply. I'll provide logs as soon as I can, which will be at least a couple of days.

**Comment by johanbest69** [comment]
Yep same issue ;  2-9
