### ISSUE TITLE
Policy count inconsistency

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6186]
![20200129190120_1](https://user-images.githubusercontent.com/16341598/73378854-eff6a580-42c9-11ea-8bb3-52cd5258b854.jpg)

 Not a bug but rather an inconsistency. 

When only an opener of a policy tree is unlocked it is not shown in the tooltip. E.g. on the screenshot there is no mention of the Statecraft opener which I unlocked. But as soon as I unlock one more tenet of it it'll start showing it as "2 Statecraft" skipping the "1 Statecraft" phase.

**Comment by LoneGazebo** [comment]
Can't fix because of how the opener is counted in the policy system. Vanilla thing.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo I suggested a fix for this in #5780 but I think it might have been missed.

> What about IsPolicyBranchUnlocked? The diplo AI uses that in GetPolicyScore.
> 
> i.e. If IsPolicyBranchUnlocked(eTradition) and policy count for Tradition = 0 then display "1 Tradition"
