### ISSUE TITLE
Questionable AI tactical decisions

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6187]
_1. Mod version (i.e Date - 4/23):_1-11-2

May seem as a minor thing but imo it exposes some flaws in AI battlefield decision-making. See the screenshot. Enemy catapult moved one tile forward and made a non-fatal shot at the crossbowman who could've been reached without moving. It's plain suicidal and I fail to see any reasoning for having done that. They could perfectly see all my units standing within and next to their borders.

![sfgsg](https://user-images.githubusercontent.com/16341598/73382085-95604800-42cf-11ea-833f-1ed7c1228b40.jpg)

So I crush his treb with my tercio expecting some kind of trap and there is no trap:

![20200129194701_1](https://user-images.githubusercontent.com/16341598/73382851-f6d4e680-42d0-11ea-86b8-4224486f9ee5.jpg)

The tercio survived till the next turn.

**Comment by ilteroi** [comment]
ok weird, that shouldn't be happening. i'll see if i can reproduce it ...

any other oddities? skirmisher use? what about naval combat? does the fish-in-a-barrel behavior still occur?

**Comment by saamohod** [comment]
>ok weird, that shouldn't be happening. i'll see if i can reproduce it ...

I could provide the savegame, but I use mods so it may be some headache for you to launch it (not the mods that affect AI obviously)

>any other oddities?

one more oddity of similar nature happened in the previous game. I don't use quick turns therefore I observe AI movements. Enemy AI moved an injured artillery unit into a tile adjacent to my citadel and was destroyed immediately by the citadel "aura". 

Also I observe some back and forth movement of units, although not as much as in previous versions.

**Comment by Stalker012345** [comment]
Ah, now that you mention this, I saw the same thing with a cannon that went right up to my citadel. Didn't think of it at the time, but now looking back, it was quite the stupid move.

**Comment by ilteroi** [comment]
ok i think i know what's up. should be better now ...
