### ISSUE TITLE
Feature: no info about some local and global bonuses in UI

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6189]
For now there's no info in UI tooltip about bonuses:
- **Building_ImprovementYieldChanges**
- **Building_ImprovementYieldChangesGlobal**
- **Building_FeatureYieldChanges**
- **Building_PlotYieldChanges**

and they are used quite often. Could be added.

**Comment by LoneGazebo** [comment]
I don't mess with that part of EUI anymore,it's too buggy and performance hogging.

**Comment by adaneslavo** [comment]
I know, but maybe one of your co-coders do.

**Comment by ryanmusante** [comment]
@adaneslavo That would be this https://github.com/LoneGazebo/Community-Patch-DLL/issues/4369

**Comment by adaneslavo** [comment]
I guess after reading this conversation, that there are some rifts. I don't know if those features were implemented in bc_1's version.
