### ISSUE TITLE
Bug Fix Request: Fix overclocking crashes to desktop

### ISSUE THREAD

**Issue by B-Knight49** [LoneGazebo/Community-Patch-DLL#6190]
**_1. Mod version:_**
Not applicable

**_2. Mod list:_**
With and without mods

**_3. Error description:_** 
Crash to Desktop in vanilla game

**_4. Steps to reproduce (optional):_**
I'm on a 9900K and am overclocked to 5.00Ghz 100% stable.
Play the game with or without mods and every 40-100 turns your game will CTD. No pattern, it can happen mid-turn or during the AI turn, it can happen on all types of video settings, any DirectX version and on any map or with any civ. 
The crash will see the game become unresponsive for ~1-2 seconds, audio will freeze, the game will recover along with the audio and then it'll crash straight to desktop about half a second to a second later. 

**_Additional information:_**
Since getting my new CPU and overclocking it, civ 5 has repeatedly crashed to desktop randomly. I originally put it down to mods and ruled them out almost 1-by-1. Eventually I played a vanilla game and experienced the exact same type of crash. 
From here, I verified the cache of the game, reinstalled and even removed all mods and any settings or left-over documents after the reinstall. I repaired or reinstalled the runtime executables in the VCRedist folder and other dependencies and did just about every other possible thing recommended by anyone. I even tried playing with this (and exclusively this) very community patch to see if it might address the bug and fix my game - it did not. 

I'd like to reiterate, my overclock is 100% stable. Nothing else has suffered with any issues, I've stress-tested my system to ensure stability and my temperatures are perfect. I also never use to encounter this issue on my older CPU (4790K). By a process of elimination and with the [discovery of other users having the same problem](https://steamcommunity.com/app/8930/discussions/0/1696043806564600685/#c1631916887497821218), I've ruled it down to Civ5 just generally being buggy.

My request is to see if you guys might be able to implement any fix into the community patch to address this issue. I imagine it's not going to be easy and could even be impossible but I'm willing to test and provide logs wherever possible to aid in that process. This bug makes the game almost unplayable for extended periods of time unless I constantly restart it every hour or two.

Detailed system info \ only changes to my system since the 4790K:

- Intel Core i9-9900K @ 5.00Ghz OC
- 16GB DDR4 TridentZ 3600Mhz CL15 RAM (XMPP)
- ASUS Maximus Hero XI Z390 

---------------------------

[crash_mdmp.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4136155/crash_mdmp.zip)
These include the civilization_dx11_403694_crash_[date].mdmp. Not sure if readable or useful but provided regardless.

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4136157/CvMiniDump.zip)

Save-game not applicable. No particular save, the crash happens on every single game I create or play. It's just a matter of time. Restarting the game from a crash, reloading the same save from a turn before and proceeding from there will be fine. EDIT: Fine until it crashes again. One crash does not solve the issue for a save-game, it'll repeatedly happen and I'll repeatedly need to restart. 

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4136163/Logs.zip)
Note: logs may be from my most recent, modded game but the same crash happens. Let me know if vanilla logs are required.

Let me know if you need anything else at all.

**Comment by bigcat88** [comment]
** or without mods **
How do you think developers must fix this?  
Try down clock CPU to 4.8(9) GHz and say to us about results.( did you really think that there is difference in speed for civ5 between 4.8 GHz and 5 GHz? :))))   )
It is not a software developer problem(maybe it is a problem in Firaxis graphic code)
If game crashes **without mods** - what modders can do? =)

**Comment by ilteroi** [comment]
the report is exemplary but yes, i think there is little we can do.

**Comment by B-Knight49** [comment]
I understand. 

All I ask is perhaps you could investigate to see if there's any chance at all that something could be done or improved. 

Obviously a low-priority too. I wouldn't want to take development time away from more pressing issues.

**Comment by LoneGazebo** [comment]
If not overclocked, does it still crash?

**Comment by B-Knight49** [comment]
No it doesn't crash when not overclocked.

**Comment by LoneGazebo** [comment]
Have you run Prime95 to check OC stability?

**Comment by B-Knight49** [comment]
Yes, please read the post man.

**Comment by LoneGazebo** [comment]
I did read the post, you didn't mention Prime95. It's my goto when checking for OC stability, I find it will trigger OC instability better than anything.

**Comment by B-Knight49** [comment]
I used it. It's definitely not the stability of my OC.

**Comment by LoneGazebo** [comment]
Ultimately it's not 100% stable if it crashes with OC in civ5. It's 99.9% stable. :)

**Comment by LoneGazebo** [comment]
May be - likely an issue with civ being single core and not x64, so it is bandwidth strapped.

**Comment by B-Knight49** [comment]
Technically you're right lol. Though it's a CTD and the temporary recovery leads me to believe it's CIV hitting a wall rather than my hardware. 

As for the x64 and single-core - how come that'd cause crashing on my CPU? With that in mind, wouldn't that render CIV 5 completely unplayable in the near future when processors get much more powerful?

**Comment by LoneGazebo** [comment]
There’s a lot of legacy games that require downclocked emulation to function.
