### ISSUE TITLE
1/11 - Disappearing Ship

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6191]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So I had an ironclad trapped in this hex the last turn. And yet this turn.... David Copperfield would be proud.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/73495486-402e4000-437c-11ea-8ee8-3bc63b0d17b5.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
i don't get it, why would it be trapped?

**Comment by Stalker012345** [comment]
It was pinched between my two ironclads (it was an enemy ironclad between the two ships shown in the screenshot), and shouldn't be able to move through ice, so how do it leave?

**Comment by ilteroi** [comment]
ok so it was an enemy ship between your two ironclads. well, maybe it was disbanded?

**Comment by Stalker012345** [comment]
Normally you can't disband a ship outside of your borders can you?

**Comment by ilteroi** [comment]
you can disband everywhere unless it's in danger. you get some gold if it's in your territory.

but i think a unit can still be force-scrapped because of deficit, even if it's in danger.

**Comment by Stalker012345** [comment]
I figured it out. Melee ships can cross ice if they can see the other side (similar to how they can cross ocean). Not sure if that is intended, but I've been able to do it with my own ships.

**Comment by ilteroi** [comment]
what? i can't reproduce and in any case it would be weird if that only works for melee ships ...

**Comment by Stalker012345** [comment]
I just did it again with one of my ships. It might have something to do with the fact that the ice is right next to my city.

**Comment by ilteroi** [comment]
well that is a feature. owned ice is passable. so it shouldn't apply in this case. i'll go with the "forced scrap" theory ...
