### ISSUE TITLE
1/11 - Losing a TR to war removes other TRs as well.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6192]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_
I made 4 TRs on the same turn, one to a CS. This CS has been a seesaw, going back and forth between me and an enemy. Each time it happens, I lose the CS TR and have to remake the connection to a new city (as expected). However, at the same time, I must also remake the other TRs made on the same turn.

_3. Error description:_ 

![image](https://user-images.githubusercontent.com/20593976/73517092-21519d00-43c0-11ea-8f47-b3eb7d0c689f.png)

_4. Steps to reproduce (optional):_
It is happening like clockwork everytime the CS is taken. It is not affecting all TRs.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
So digging into this more, its not just in the same city where the TR to the CS was done. I moved the 4 other trade routes to a different city, but the same thing happened. When the CS was taken, 4 of my TRs reset.

**Comment by LoneGazebo** [comment]
@ilteroi you recently did some cache rewrites in this area- did you touch any of this?

**Comment by LoneGazebo** [comment]
are the CSs on the same team? Did you change that functionality in game setup?

**Comment by LoneGazebo** [comment]
@ilteroi this is the function where we do this...but it looks fine to me.
void CvGameTrade::DoAutoWarPlundering
Check it out?
