### ISSUE TITLE
Feature Request - "Their Finest Hour" replaces heavy bomber with B17

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6193]
_1. Mod version (i.e Date - 4/23):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This is a feature request. Currently when you pick "their finest hour", you get both the heavy bomber and B17. The thing is, the B17 is superior in all ways, yet you can build both, and your old bombers will upgrade to the worst version.

I would like it to work like a UU, where the B17 replaces the heavy bomber as your unit for building and upgrades.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by saamohod** [comment]
IIRC Zero is also better in any regard than Fighter and it doesn't make much sense having both in the roster either.

**Comment by LoneGazebo** [comment]
unfortunately you can't edit UU's 'on the fly.' I'm not really sure how you'd address this, it'd be a hell of  a rewrite.

**Comment by TechpriestEnginseer** [comment]
And also what do you do for ideological revolutions? It'll be an awkward way to "lock" something away.
