### ISSUE TITLE
1/11 - Air Sweep promotions don't reduce damage against Mobile Sam

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6194]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Whether I used Interceptor 3 or Air Sweep 3, an air sweeping Jet Fighter still took 45 damage from a mobile Sam.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi mind taking a quick peek?

**Comment by LoneGazebo** [comment]
>Interceptor 3 or Air Sweep 3
Neither of those reduce air damage...

**Comment by Stalker012345** [comment]
The point of Air Sweep 3 is to increase your CS against the opposing force when you do an air sweep.

If that bonus is not helping my fighter take less damage when doing the air sweep against anti-air...than what's the point of having it?

**Comment by LoneGazebo** [comment]
Air Sweep 3? What promotion is that anyways?

**Comment by Stalker012345** [comment]
Dogfighting I-III

**Comment by UndeadDevel** [comment]
I'm actually not sure that it should increase CS against AA-units...certainly against other Fighters when Sweeping, but giving it a bonus against AA-units as well would make the Dogfighting promos be worth much more than the Ace Pilot promos.
