### ISSUE TITLE
1/11 - Rocket Artillery doing greater air defense damage than expected.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6195]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Not below, the Rocket Artillery did 70 damage to my stealth bomber. It has no air defense promotions, and normal air defense is 35 for the unit.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/73530191-9e3f3f80-43dd-11ea-8de2-a28f692f19dc.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi another combat damage query for you...
