### ISSUE TITLE
Connected coal not usable

### ISSUE THREAD

**Issue by crdvis16** [LoneGazebo/Community-Patch-DLL#6196]
![Coal](https://user-images.githubusercontent.com/17805009/73545941-54b91980-440a-11ea-8cbb-c996929d15eb.png)
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_
VP+EUI only

_3. Error description:_ 
I've connected my 3 coal southeast of Sao Paulo via manufactory but for some reason it doesn't actually give me access (when attempting to build a train station it says I need coal).  I tried exiting to windows and restarting.  I haven't tried building a mine instead of a manufactory yet.  If a game save ends up being required let me know.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by crdvis16** [comment]
Note: building a mine instead of the manufactory did not fix the issue.  Also odd is that my 3 coal is tradable to other civs as if I have it.

**Comment by LoneGazebo** [comment]
No idea, never seen this before.

**Comment by crdvis16** [comment]
See attached for a save game.  It's more complicated now because I have things generating and using coal in this save but you can still see that I'm at -4 when I should be at -1 (the source from Sao Paulo isn't being added to the total).

[Pedro II_0351 AD-1931.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4142968/Pedro.II_0351.AD-1931.zip)

**Comment by Vyyt02** [comment]
My resource count is off from time to time for me. It's been like this for years. Reported to GitHub, but could not have been replicated though some other people reported the same. Could be a mod conflict in my case though.

**Comment by mt-empty** [comment]
I have experienced the same with an oil tile.
