### ISSUE TITLE
1/11 - Melee Ship city damage seems off

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6199]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Check me on this, but I believe city CS is supposed to act the same as a unit's. If that's the case, than because my unit has greater CS, it should be doing more damage than it takes, but that is not the case based on this screenshot.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/73587058-2411c800-447c-11ea-91ed-f46d33878730.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
If that city has a garrison, I think it is related to my issue #6166.
