### ISSUE TITLE
captured settler

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6201]
portugal captured a barbarian settler (originally swedish)

![image](https://user-images.githubusercontent.com/1358966/73615339-556acf00-4607-11ea-8c4c-18b12b3f21c9.png)

shouldn't they get a worker only?

**Comment by bigcat88** [comment]
or portugals capture from settler from barbs?

**Comment by ilteroi** [comment]
ha. i totally forgot about that other one. so it is intentional? what effwct does the prisoner of war promotion have?

**Comment by HeathcliffWarriors** [comment]
I'm wondering if that's a modmod honestly.

**Comment by ryanmusante** [comment]
If these are enabled it gives percent chance of returning a settler.
```
	<CustomModOptions>
		<Update>
			<Where Name="GLOBAL_GRATEFUL_SETTLERS"/>
			<Set Value="1"/>
		</Update>
		<Update>
			<Where Name="GLOBAL_GRATEFUL_SETTLERS_PERCENT"/>
			<Set Value="20"/>
		</Update>
	</CustomModOptions>
```
