### ISSUE TITLE
memory usage stats

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6202]
check this. memory usage does have an upward trend, but it seems we have some headroom until the 2gb limit. this is VP without any extra mods of course.

![image](https://user-images.githubusercontent.com/1358966/73721109-c901fe80-4723-11ea-9ea7-1eb667e806ba.png)

**Comment by supermerill** [comment]
What tool did you use?

**Comment by Stalker012345** [comment]
Personally I've noticed in this latest version that my missing icon problems are significantly less than normal. So I had assumed you all did some memory management updates.

**Comment by ilteroi** [comment]
that's a powershell script running in parallel to the game ...

but no, there were no large-scale optimizations recently, so i'm assuming the crashes that people complain about are due to extra mods

**Comment by ilteroi** [comment]
this is the script if anyone is interested. runs for two hours, adjust as necessary

```
$i = 0
while($i -lt 720)
{
	Get-Process -Name 'CivilizationV_DX11' | Select @{n="PrivateBytes_MB";e={$_.PrivateMemorySize64/1MB}}, @{n='WorkingSet_MB';e={$_.WorkingSet64/1MB}} | Add-Content civ-memory.log 
    Start-Sleep -Seconds 10
	$i++
}
```

i've also added the PrivateBytes metric here but it's kind of boring, always around 2524
