### ISSUE TITLE
Diplomacy Overview Incorrect Turns Remained

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6204]
_1. Mod version (i.e Date - 4/23): 1-11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

In the EUI the turns are displayed correctly but in the diplomacy screen are displayed with negative numbers, the code should be updated there also (this happens on epic speed and I think on marathon is the same issue). Should be fixed for the others modifiers that can cause this issue.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![a](https://user-images.githubusercontent.com/49090452/73870646-1f228f00-4855-11ea-97af-be7192f6a36f.png)

![b](https://user-images.githubusercontent.com/49090452/73870657-234eac80-4855-11ea-962b-0d3614207d9a.png)

**Comment by HeathcliffWarriors** [comment]
The UI for the diplomacy overview must not be using the same code...

**Comment by Aqinu** [comment]
**For denouncing is the same issue, it's shown incorrectly (I'm playing as Byzantium)**
![a](https://user-images.githubusercontent.com/49090452/74144735-f0663900-4c05-11ea-86de-ba84d5af4510.png)

![n](https://user-images.githubusercontent.com/49090452/74144750-f9efa100-4c05-11ea-904c-8c00de7901ab.png)

**Comment by LoneGazebo** [comment]
I fixed this in latest already.
