### ISSUE TITLE
Paratrooper interception bugs

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6210]
_1. Mod version (i.e Date - 4/23):_
12-1-1

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) Trade Opportunities for VP (v 8.2)
Airfield Improvement-Unit (v 1)
Capture Great People for VP (v 2)
CIV-Linked Great Generals (v 12)
Faster Aircraft Animations (v 3)
Global - Religious Settlers (v 1)
Improved Air Recon (v 1)
Promotion Flags EUI for VP (v 2)
Subs Ignore Borders (v 3)
Subs Immune Under Ice (v 2)
UI - Destination (v 4)
UI - Filters in Trade Route Overview (Vox Populi) (v 2)
UI - Religion Spread (Vox Populi) (v 1.1)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.2)

_3. Error description:_ 
See screenshot; the text isn't properly shown, only the text key, and the Special Forces unit didn't actually take any damage even though one of the AA-units, which aren't visible in the screenshot but they're to the "South", did get "used" (at least that's what the combat preview UI for my Fighters tells me, which stated before this jump that there are two Interceptors and after it only one).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![paradrop_bug](https://user-images.githubusercontent.com/30495439/74074410-cba37300-4a05-11ea-9c89-9660c6c7d2c9.jpg)

**Comment by ilteroi** [comment]
fixed the part where the damage isn't applied to the paradropping unit, but i have no clue what's wrong with the text localization
