### ISSUE TITLE
Many bugs with air units

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6211]
_1. Mod version (i.e Date - 4/23):_
1-11-2

_2. Mod list (if using Vox Populi only, leave blank):_
IGE for testing

_3. Error description:_ 
I won't provide screenshots or save games as this can be seen within a few minutes of testing...there are many issues, including:
- Interceptions happening without notifications or animations
- Air Units that did Sweeps in their turn still doing interceptions during the enemy's turn
- Animations being buggy (only flying a tiny bit instead of meeting the attacking aircraft)
- AI promoting their Fighters to Interceptor IV but then not using them for interception (either that or interception is broken in some cases)

_4. Steps to reproduce (optional):_
Just test it...load up a game, put a City near another Major Civ, give yourself some Fighters and the other some air units, too, and place a Knight or something in between and then declare war and watch what happens over the next few turns.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
yeah, air combat is a mess ... in particular, AI unit selection is greedy, meaning they always use the first available unit which can do a certain mission without checking whether there might be a better unit somewhere else.

**Comment by UndeadDevel** [comment]
Hmm that sounds bad...the human would always take such consideration; if it's too costly from a performance standpoint, maybe the "check for best unit"-logic should only be active for air units, or even only for fighter units?
I think air units, particularly fighter units, because of their rather extreme specialization compared to other unit domains and their late game status (several promotions will be present), are very sensitive to things like choosing the correct unit for a particular job; if that is not done then efficacy drops by a huge amount.

**Comment by ilteroi** [comment]
yeah ... the AI used to be stupid like that everywhere ... for regular combat it has all been rewritten by now, but air combat uses different code.

@all: we probably also should create new text for air sweeps, right now their notifications use the regular strings, creating confusion

**Comment by LoneGazebo** [comment]
@ilteroi I've made some of these fixes – I haven't de-dumbed the tactical AI but the other things I've fixed.

**Comment by LoneGazebo** [comment]
Only one we can't fix is animations, that's not something we can control.

**Comment by UndeadDevel** [comment]
Alright, sounds better already!

Yes, with the new Sweep "strafing" feature there should be a new notification added that happens then and ideally a sort of attack animation triggering, even if there is no interception, if this is possible.

**Comment by LoneGazebo** [comment]
@UndeadDevel sweeps don't have interception animations, but there's a txt popup and also damage text on the map.

**Comment by LoneGazebo** [comment]
@ilteroi I just pushed my repo, let's not replicate work on the same stuff. Also look at what I did for the homeland AI interception code, with the sorting based on aux data for interception chance - we should do that for the tactical AI too, should't be too hard.

**Comment by UndeadDevel** [comment]
Hmm I could swear that in vanilla an Air Sweep would show a sort of dogfight if it was intercepted by an enemy fighter (but not when intercepted by naval or land units).
But what I meant was that if the Sweep will damage enemy air units (new "strafing" mechanic) can there be an attack animation triggered as if it was an attack on that tile? Would be pretty nice...

**Comment by LoneGazebo** [comment]
@UndeadDevel no animation for that
