### ISSUE TITLE
AI has Information Era Air Units in early Atomic

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6212]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The AI is currently 2 techs ahead of me, and I am 5 techs from Radar. So even just having Fighters would be impressive (meaning he did a super ultra beeline to get there).

But no....he has JET FIGHTERS!!!

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/74078623-5f6b4400-49f2-11ea-9d0f-445ae6691a82.png)

![image](https://user-images.githubusercontent.com/20593976/74078636-7ad64f00-49f2-11ea-9915-59ff3625f802.png)

![image](https://user-images.githubusercontent.com/20593976/74078642-8e81b580-49f2-11ea-8fc4-11324d7f66c0.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Dunno. AI doesn't cheat.

**Comment by Stalker012345** [comment]
I've been watching the combat logs, and I have never seen the AI actually fight with the units, so maybe they aren't real. I have noticed some memory bugs, like a unit that is "there" but the unit portrait is missing, that kind of thing.

**Comment by LoneGazebo** [comment]
hm

**Comment by bigcat88** [comment]
Pentagon

**Comment by UndeadDevel** [comment]
Yup the Pentagon gives two Jet Fighters for free upon completion.

**Comment by Stalker012345** [comment]
well....time to turn in my man card....my encyclopedic knowledge of all VP updates has failed me:(
