### ISSUE TITLE
1/11 - (Tactical) AI throwing bombers into the CS seesaw

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6214]
_1. Mod version (i.e Date - 4/23):_
1/11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
One thing I'm seeing the AI consistently do is, it takes the CS...and then immediately brings in 2 bombers. However, the city is very tentative, and I just take it right back, knocking out 2 bombers each time.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/74084532-a62e5d80-4a35-11ea-8eb1-7411afa9af80.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
might already be fixed ... unless the fix already made it into the previous release, in that case it didn't work as intended
