### ISSUE TITLE
12/30 - Disappearing GWs?

### ISSUE THREAD

**Issue by bentakacs** [LoneGazebo/Community-Patch-DLL#6217]
_1. Mod version (i.e Date - 4/23):_
12-30-3

_2. Mod list (if using Vox Populi only, leave blank):_
(over) More Unique Components for VP (v 55)
A Few More Terrain-Specific Buildings (v 1)
Convenient start (v 2)
Even More Terrain-Specific Buildings (v 1)
Forest On Snow Tiles (v 1)
Improved Air Recon (v 1)
Lake Victoria Fix (v 2)
Music Changer (v 2)
Reforestation (v 9)
UI - Map Pins (v 17)
UI - Small Resource Icons (v 4)
Useful City Ruins (v 3)
TreeGrowth (VP) (v 2)

(for me only Infoaddict)

_3. Error description:_ 
I have noticed this myself, and now someone else also reported that GW-s are just disappearing sometimes from a city without any (known) spy activity or notification. 

Both of us experienced it on version 12-30, so maybe it got fixed since, but I felt it worths at least a check or a confirmation from you.

Here is a save file from Delvemor on the very same turn it happens. Also according to him if you move the GW-s they do not necessarily disappear (I personally haven't tried it).

Could you please take a look at it? Thank you!

[weird bug with great worksinAkad.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4175597/weird.bug.with.great.worksinAkad.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
Does this happen in base VP? I've seen a number of bug reports about things disappearing unexpectedly and it often turns out to be a mod conflict.
