### ISSUE TITLE
(Request) LocationUnitFreePromotion for Improvements

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#622]
I'd like to make a request for the functions of LocationUnitFreePromotion to be extended to the Improvements table. In a bid to expand upon my Tribes system in ExCE, I aim to have each Tribe possess their own borders. Because I'm not DLL-savvy, and doing this through Lua can be CPU-intensive, I've opted to simply place 'dummy improvements' in order to mark these borders. This works well, as I hoped that Tribes would afford unique bonuses to these tiles. However, some of these bonuses I wanted to affect Units walking through their borders, and this is where LocationUnitFreePromotion will come in handy. I'd appreciate it immensely if this could be added for the next update, or just whenever you're able. Thanks.

**Comment by LoneGazebo** [comment]
Done. It'll only be for units on the plot - does it need to be for adjacent plots as well, or is that good enough?
G

**Comment by LoneGazebo** [comment]
It'll also use the same rules as the other methods, so it will be taken away when you leave (if you want), and can negated (as with the scurvy promotion).

**Comment by JFDaly** [comment]
Thanks! Just on the plot itself is enough for what I need.

**Comment by LoneGazebo** [comment]
Done. Look for it in the new version of the CP.
