### ISSUE TITLE
Building to Policy Tag Requests

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#6224]
A few requests for functionality thats already handled by Buildings to be made accessible to Policies. Any or all that are possible would be greatly appreciated and help reduce reliance on dummy buildings. 

**ExtraMissionaryStrength**
**ExtraMissionarySpreads**
**Policy_YieldChangesPerReligion** (which is to say in all cities at once)

Churs for any help.

**Comment by HungryForFood** [comment]
@LoneGazebo if you're busy I can do this?

**Comment by LoneGazebo** [comment]
If you want to take point on this that would be great! :)

**Comment by HungryForFood** [comment]
@JFDaly Done. You can test this it if you want, I've attached the DLL.

New columns are the same name as in your post.

Policy_YieldChangesPerReligion is exactly like Building_YieldChangesPerReligion, ie the yield column is a percent.

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4209629/CvGameCore_Expansion2.zip)

**Comment by HungryForFood** [comment]
#6251

**Comment by JFDaly** [comment]
Awesome, thank you :3
