### ISSUE TITLE
two embassies for on CS?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6225]
![image](https://user-images.githubusercontent.com/1358966/74129165-2cd26e80-4bdf-11ea-8836-d53fba42a7c2.png)

also both are french, fwiw

**Comment by LoneGazebo** [comment]
hmm

**Comment by 1andUnly** [comment]
I experienced the same bug

**Comment by TechpriestEnginseer** [comment]
Embassies are allowed to be placed on Luxury/Strategic Resources, years ago.

**Comment by ryanmusante** [comment]
```Embassies can only be built in City-State territory by Great Diplomats. The first player (and only the first!) to construct an Embassy in a City-State's land earns an extra vote in the World Congress. No player will receive additional votes for Embassies beyond the first one placed in a City-State's territory.```

**Comment by LoneGazebo** [comment]
Was the CS conquered or something?
