### ISSUE TITLE
Ranged ships deal x1.5 more damage to ranged land units

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#623]
The cause of that is the 'difficult target' promotion on ranged land units. While they deal less damage to navy, they also receive way more damage than they should. I realise this is not actually a bug, but I doubt it is supposed to work both ways.
![naval](https://cloud.githubusercontent.com/assets/12978597/9834145/553b95c8-59b7-11e5-860e-9eee685b5e7f.jpg)

**Comment by LoneGazebo** [comment]
Not sure about that, actually - there's no intrinsic code that makes it work this way. Sure there isn't a promotion in there for the galleass that's helping it?

**Comment by LoneGazebo** [comment]
Is a side-effect, but I don't want to edit the LUA/DLL (as it'd be a hard-code), so I'm going to reduce the penalty/bonus to -25/+25%. Feels fair.

**Comment by Edaka** [comment]
An easy compromise - sounds good.
