### ISSUE TITLE
Barbarian pillaging their own camps to heal

### ISSUE THREAD

**Issue by UndeadDevel** [LoneGazebo/Community-Patch-DLL#6236]
_1. Mod version (i.e Date - 2/9):_
2-9-3

_2. Mod list (if using Vox Populi only, leave blank):_
IGE for testing

_3. Error description:_ 
see screenshot; before that screenshot there was a Barbarian Brute just outside the camp, which I attacked with my Archer; on his turn he moved into his camp and pillaged it, which gave him 25 HP heal....then I killed him.

Barbarians are probably not supposed to be able to pillage their own camps for healing.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![barb_pillaged_his_own_camp](https://user-images.githubusercontent.com/30495439/74280372-5b9e3100-4d14-11ea-9cd9-eacfefbd4867.jpg)

**Comment by ilteroi** [comment]
that's a funny one. let's leave it in

**Comment by UndeadDevel** [comment]
Haha yeah that's what I initially thought, as well...I mean they are Barbarians, after all, so you wouldn't expect them not to pillage their own camp, right?

But I still reported it as it does seem kinda weird and probably has some non-sensical effects (E.g. I don't think Barb spawning or healing are turned off after the pillage, right? They kinda should be if this is to be sensical, though).

**Comment by LoneGazebo** [comment]
I’ve already patched it out in my test build.
