### ISSUE TITLE
New Beta - Lighthouse supply added to BUILDING_HARBOR

### ISSUE THREAD

**Issue by Vayan44** [LoneGazebo/Community-Patch-DLL#6237]
_1. Mod version (i.e Date - 2/9):_3b (2-9-3b)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  In new beta: (2 CBO)/Buildings/BuildingChanges.sql under Lighthouse (line 363) +1supply(CitySupplyFlat=1) is added to BUILDING_HARBOR not BUILDING_LIGHTHOUSE.

There is already +2 supply added to BUILDING_HARBOR at line 384. Patchnotes state +1 to **lighthouse** and +2 to **harbor**.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Padre19** [comment]
Patchnotes state Harbor - +2 supply (removed +10% from pop) but at line 378-380

 UPDATE Buildings
SET CitySupplyModifier = '10'
WHERE Type = 'BUILDING_HARBOR'

**Comment by 8h42** [comment]
Does Runestone need +1 supply too?
It replaces the Lighthouse.
