### ISSUE TITLE
Civilian and military units ignoring the roads, prefering direct routes even if it takes more turns

### ISSUE THREAD

**Issue by SuperNoobCamper** [LoneGazebo/Community-Patch-DLL#6239]
_1. Mod version (i.e Date - 2/9):_
2/9

_2. Mod list (if using Vox Populi only, leave blank):_

1. (1) Community Patch
2.(2) Community Balance Overhaul
3.(3) CSD for CBP
4.(4) Civ IV Diplomatic Features
5.(5) More Luxuries
6.(6a) Community Balance Overhaul - Compatibility Files (EUI)
7.(7) Community Events (v 4)
8.(7a) Promotion Icons for VP
9.(7b) UI - Promotion Tree for VP
10.(over) More Unique Components for VP v56
11.Faster Aircraft Animations (v 3)
12.FlagPromotions (v 7)
13.InfoAddict (v 22)
14.Really Advanced Setup (v 15)

_3. Error description:_ 
The pathing issue seems to be units both civilians, military and GG ignoring the presence of the roads and preferring the more direct route even if it takes more turns, i had to manually move every unit tile by tile, sometimes this is not even feasible if you have to transfer a unit from a non-road tile to a road tile occupied with a unit with no moves left. 
Screenshots showing the issue in the attached file.

[pathing issue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4195408/pathing.issue.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi will be on this, but he’s gone currently.

**Comment by ilteroi** [comment]
fixed - recent embarked movement changes reduced costs per plot, making the heuristic function inadmissible
