### ISSUE TITLE
bug "two embassies for on CS" reloaded

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#6243]
_1. Mod version (i.e Date - 2/9):_ Version  2-9-4b

_2. Mod list (if using Vox Populi only, leave blank):_
VP and personal mod......

_3. Error description:_ 
 The bug "two embassies for on CS" is still there. When improve srategic resource ( iron ) in CS via diplomatic mission result is lost resources and build holy site......
Also i have error on lua logs
(2) Community Balance Overhaul\LUA\DiploList.lua:39: attempt to index field 'OuterGrid' (a nil value).
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Padre19** [comment]
https://forums.civfanatics.com/attachments/1581637063_1037_14022020_1920x1080-png.546072/

**Comment by ryanmusante** [comment]
DiploList.lua

https://forums.civfanatics.com/threads/trade-opportunities-for-vp.636230/page-4#post-15670924
```
found these two lines:
[29739.656] Runtime Error: C:\Users\Home\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Community Balance Overhaul\LUA\DiploList.lua:39: attempt to index field 'OuterGrid' (a nil value)
[29739.656] Runtime Error: Error loading C:\Users\Home\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Community Balance Overhaul\LUA\DiploList.lua.

Edit: VP and TOVP only.
```
