### ISSUE TITLE
Diplomacy button does not work

### ISSUE THREAD

**Issue by arievillo** [LoneGazebo/Community-Patch-DLL#6244]
Vox Populi 2-9-4b

Error description: Button is locked. The diplomacy screen does not open.

Steps to reproduce: Just clic it.

[Logs and Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4202427/Logs.and.Save.zip)

**Comment by adaneslavo** [comment]
Confirmed on my installation. Early error in lua during loading CityList.lua and DiploList.lua.

**Comment by ryanmusante** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/6243 similiar

**Comment by arievillo** [comment]
So..3 days and no aswer. I know you guys have a lot of work to do and obviously a list of priorities. But this button, without working, prevents any possibility of starting a save. Unless only me and the 2 other people who wrote here are the lucky ones. What i have to do to enter the please, have a look at my question" club? Thanks

**Comment by adaneslavo** [comment]
Why is it closed? It has not been solved yet, right?

**Comment by ryanmusante** [comment]
@arievillo Reopen and just wait, it will get got.

**Comment by arievillo** [comment]
I will reopen for you and the community. I just don't care anymore. Not for this bug or for this version of Civilization. I migrated to IV, for numerous reasons. Good luck take care.
