### ISSUE TITLE
MODS\(1) Community Patch\Core Files\CoreLua\InGame.lua:941: bad argument #1 to 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#6247]
Running a game, getting this notification 2-3 times a turn.

MODS\(1) Community Patch\Core Files\CoreLua\InGame.lua:941: bad argument #1 to 'ipairs' (table expected, got nil)

**Comment by LoneGazebo** [comment]
That isn’t an error in the lua, rather an error in the lua input from the database

**Comment by pineappledan** [comment]
It’s just a in pairs(players) do. Is there unassigned variables or something?

**Comment by LoneGazebo** [comment]
Possibly?
