### ISSUE TITLE
Revisions to diplo AI approach selection

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6255]
So, I currently have a few problems with the approach functions:

1) There are a few circumstances (Always War/No Changing War or Peace/teammates/human shadow AI), where calculating all the approach weights is completely unnecessary, yet the AI goes through the full calculation. Skipping these checks is an opportunity to improve performance. I added this for the human shadow AI but the other three cases still need to be fixed.

2) The approach value logs provide little information on the actual factors behind the calculation (I'm working on improving this by adding better logging).

3) The AI updates approaches from worst to best Opinion rating (not weight). If there are two or more civs at the same Opinion rating, it does an initial pass of GetBestApproachTowardsMajorCiv, retrieves the highest number weight for any approach (without considering what approach it's from) and updates higher weights before lower weights.

This is kind of arbitrary, and I want to implement a more strategic system that better prioritizes the AI's approaches.

My planned new system for DoUpdateMajorCivApproaches is as follows:

1) For civs that fall under problem 1 above, simply update their approaches immediately rather than going through the entire function.

2) For all other valid civs (met, not dead, etc.), do an initial pass of GetBestApproachTowardsMajorCiv and store their approach weights for all seven approaches - without considering approaches already adopted towards other players. Don't log or update.

3) For each of the seven approaches except NEUTRAL (the default approach), rank the approach weights from the players in order from highest to lowest.

4) Do a second pass of GetBestApproachTowardsMajorCiv - this time, at some point in the function, the AI looks at the civ's ranking for all non-neutral approaches.

5) For each approach except NEUTRAL, remove weight for that approach based on the civ's ranking compared to other valid civs.

So for example, suppose we had a ranking for WAR like this:
Songhai - 87
Egypt - 76
Persia - 62
India - 55

Songhai would have no alteration to the WAR weight. Egypt would get -1x WAR bias, Persia would get -2x WAR bias, India would get -3x WAR bias.

This would help to reduce the AI's propensity towards adopting a single approach towards many civs (as can happen sometimes like in the reports from last version, where all the AIs were ganging up on the human but being friendly towards each other) while also applying this reduction in a strategic way.

It's also a lot more intelligent than the current system, and would not need to be changed frequently (if at all) once implemented.

The current system of adding some weight for NEUTRAL/FRIENDLY if specific approaches were adopted towards other civs is not functioning all that well, because:
- The AI's prioritization order is not very strategic.
- The effect does not scale based on the civ's ranking.
- It boosts NEUTRAL/FRIENDLY specifically rather than just reducing the weight for the stronger approach. +1x NEUTRAL bias boosts NEUTRAL specifically, whereas -1x WAR bias boosts all other approaches.
- A civ might have a very high bias for the WAR approach, but a low NEUTRAL/FRIENDLY bias, so the effect is not equal. This alternative change is proportional to the civ's desire for that approach.

This may cost a bit more performance-wise but I think the strategic benefits would be worth it.

--------
My problem is that I'm not experienced with using vectors/arrays, and I would appreciate any help or suggestions on how to code this new system in without screwing it up.

**Comment by HeathcliffWarriors** [comment]
Well, on second thought, no need to store the NEUTRAL approach weight if it isn't going to be used for ranking, but the rest of the system still applies. :)

**Comment by ilteroi** [comment]
i don't think you need to worry about performance or memory impact here ... also, you know the first rule? premature optimization is the root of all evil.

anyway, i don't know the code that well but it seems to me that a vector maybe isn't the best approach, just put all "phase 1" results into a nested map structure like std::map<PlayerTypes,std::map<MajorCivApproachTypes,int>> ... then you can access them later like cache[player][approach]

**Comment by HeathcliffWarriors** [comment]
I wasn't really set on vectors, just needed some kind of array structure I could edit. :)

I'm not experienced in using maps, either, but it does sound a lot simpler. I might ask for help in setting it up once I finish rewriting the approach function, if you don't mind.

**Comment by HeathcliffWarriors** [comment]
Draft code for new DoUpdateMajorCivApproaches function.
```
void CvDiplomacyAI::DoUpdateMajorCivApproaches()
{
	std::vector<PlayerTypes> PlayersToUpdate;
	bool bPermaWar = (GC.getGame().isOption(GAMEOPTION_ALWAYS_WAR) || GC.getGame().isOption(GAMEOPTION_NO_CHANGING_WAR_PEACE));

	for (int iPlayerLoop = 0; iPlayerLoop < MAX_MAJOR_CIVS; iPlayerLoop++)
	{
		PlayerTypes eLoopPlayer = (PlayerTypes) iPlayerLoop;
		
		if (IsPlayerValid(eLoopPlayer, true) && eLoopPlayer != GetPlayer()->GetID() && GET_PLAYER(eLoopPlayer).isMajorCiv())
		{
			// Under certain circumstances, set the approach immediately
			if (IsTeammate(eLoopPlayer))
			{
				DoUpdateApproachTowardsTeammate(eLoopPlayer);
				continue;
			}
			else if (bPermaWar && IsAtWar(eLoopPlayer))
			{
				DoUpdatePermaWarApproach(eLoopPlayer);
				continue;
			}
			else if (GetPlayer()->isHuman())
			{
				DoUpdateHumanApproachTowardsMajorCiv(eLoopPlayer);
				continue;
			}
			else if (GetPlayer()->getCapitalCity() == NULL)
			{
				DoUpdateApproachWithNoCities(eLoopPlayer);
				continue;
			}
			else if (GET_PLAYER(eLoopPlayer).getCapitalCity() == NULL)
			{
				DoUpdateApproachTowardsMajorCivWithNoCities(eLoopPlayer);
				continue;
			}
			
			// Otherwise, add this player to the list of civs to update approaches towards this turn
			PlayersToUpdate.push_back(eLoopPlayer);
		}
	}
	
	// Human shadow AI and AI players with no cities end the function here.
	if (GetPlayer()->isHuman() || GetPlayer()->getCapitalCity() == NULL)
	{
		return;
	}

	if (!PlayersToUpdate.empty())
	{
		// Do a first pass of GetBestApproachTowardsMajorCiv for each player and record (but do not update) the approach weights in a map; they will be used in the second pass.
		for (std::vector<PlayerTypes>::iterator it = PlayersToUpdate.begin(); it != PlayersToUpdate.end(); ++it)
		{
			GetBestApproachTowardsMajorCiv(*it, /*bFirstPass*/ true, /*bUpdate*/ false);
		}
		
		// Do a second pass of GetBestApproachTowardsMajorCiv for each player and update/log the (possibly new) approach and weights.
		for (std::vector<PlayerTypes>::iterator it2 = PlayersToUpdate.begin(); it2 != PlayersToUpdate.end(); ++it2)
		{
			MajorCivApproachTypes eApproach = GetBestApproachTowardsMajorCiv(*it2, /*bFirstPass*/ false, /*bUpdate*/ true);
			SetMajorCivApproach(*it2, eApproach);
		}
	}
	return;
}

/*
bFirstPass = if set to true, updates the approach weights map at the end of the function, and skips the approach weights map check within the function.
bUpdate = if set to true, updates the approach weights and war face and logs the update.
*/
```

**Comment by HeathcliffWarriors** [comment]
@ilteroi So, now that I've resolved the embarrassing error with the deleted function...:)

I need help with adding a std::map container to the diplo AI to store the approach values from the first pass. It doesn't necessarily need to be serialized, as GetBestApproachTowardsMajorCiv is only called through DoUpdateMajorCivApproaches, which calls it twice.

The first pass of the function doesn't store the return value, it's meant to collect each evaluated player's approach weights for each of the seven approaches and in the check at line 7831, add them to the map.

The second pass of the function will feature a check on line 7099 which will collect all players' approach weights for every approach except NEUTRAL, rank them in order from highest to lowest, and subtract weight based on how low the current player's ranking is compared to the others.

I'm just not sure how to add that...could you help me with that?

The container needs to be structured like such:

Container > Player A > FRIENDLY > # weight
                   Player A > HOSTILE > # weight
                                   (so on for each approach)
                   Player B > FRIENDLY > # weight
                   (so on for each player)

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo In case ilteroi's busy, do you have any advice for this?

**Comment by LoneGazebo** [comment]
We do a sortable vector map here: CvWeightedVector<PlayerTypes, MAX_MINOR_CIVS, true> vePlayerApproachWeights;

Just copy the relevant code and you're good to go. Replace MINOR with MAJOR

**Comment by LoneGazebo** [comment]
Are you wanting to map an array? You might want to think about a custom class that stores the data as the second part of the map.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo The issue I see with a CvWeightedVector is that GetBestApproachTowardsMajorCiv is called twice for each player; the first time, I'm going to store each player's weights for each approach, and in the second call, I'll use that data.

But since GetBestApproachTowardsMajorCiv's return value is simply the approach, how can I keep the data in the CvWeightedVector from being deleted between the first and second calls? 

A local variable won't work since I need the results from all players' first pass through the function, before I do _any_ player's second pass through the function.

Not 100% sure what you mean re: an array, but I think so...? It would be helpful to only have a map of the players whose approaches are actually being sorted (the PlayersToUpdate vector in the new  DoUpdateMajorCivApproaches).

**Comment by LoneGazebo** [comment]
Hmm...to my rudimentary brain I think a custom struct could be helpful, but I'm also not 100% sure what you're trying to do. If you're doing all of this in the same function, just do this.

Call GetBestApproachTowardsMajorCiv() and have the CvWeightedVector be passed out as a &variable from the function.

Store that value off in the function as a different name so it isn't modified by another function.

Second call, pass the value back in in the same location, with a check in GetBestApproachTowardsMajorCiv that looks if it is empty. If it isn't empty, you can store the data off again within the function.

**Comment by HeathcliffWarriors** [comment]
I'll describe what I'm trying to do more exactly:

1) DoUpdateMajorCivApproaches loops through all players. For certain players (teammates, permanent war, players with no cities, or if the current player is a human shadow AI or an AI with no capital) it simply sets an approach immediately as a performance improvement. 

For players that don't have an approach set immediately (most of them), it adds them to a vector.

2) DoUpdateMajorCivApproaches then iterates through this vector once, and runs GetBestApproachTowardsMajorCiv for each player. 

In GetBestApproachTowardsMajorCiv, bool bFirstPass is set to true, so it records each player's approach weights (for all approaches) at the end of the function.

So if Persia's diplomacy AI is running DoUpdateMajorCivApproaches, on the first pass it runs GetBestApproachTowardsMajorCiv for China and records the following:

China's player ID
Neutral - 40
Friendly - 28
Afraid - 15
Guarded - 33
Hostile - 30
War - 38

It then stores this data for all of the players in the vector in some array-like structure for later retrieval.

3) DoUpdateMajorCivApproaches then iterates through the "players to update" vector and calls GetBestApproachTowardsMajorCiv a second time, this time with bool bFirstPass set to false.

At a certain point in GetBestApproachTowardsMajorCiv, Persia's diplomacy AI would loop through each non-Neutral approach, and collect the approach weights for all players from the first pass.

So for instance, for the Guarded approach it might have values of:
Aztecs - 72
Babylon - 55
China - 33
America - 27

As China is ranked #3 for Guarded, it would get a reduction of -2x Persia's Guarded bias (the #1 civ gets no reduction and the others get -1x, -2x, -3x, etc).

Persia repeats this process for all approaches except Neutral, as the default. The result of this is that it doesn't matter in what order the players' approaches are updated, compared to the existing arbitrary order which makes it more likely for players updated last to not be DoW'ed.

4) GetBestApproachTowardsMajorCiv then finishes, updates the average value for the next turn, logs the update, updates the war face if needed, and returns the selected approach to DoUpdateMajorCivApproaches, which sets the approach.

5) End of DoUpdateMajorCivApproaches.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo I'll describe what I'm trying to do more exactly:

-------------
**Step 1**
DoUpdateMajorCivApproaches loops through all players. For certain players (teammates, permanent war, players with no cities, or if the current player is a human shadow AI or an AI with no capital) it simply sets an approach immediately as a performance improvement. For players that don't have an approach set immediately (most of them), it adds them to a vector.

-------------
**Step 2**
DoUpdateMajorCivApproaches then iterates through this vector once, and runs GetBestApproachTowardsMajorCiv for each player. 

In GetBestApproachTowardsMajorCiv, bool bFirstPass is set to true, so it records each player's approach weights (for all approaches) at the end of the function.

So if Persia's diplomacy AI is running DoUpdateMajorCivApproaches, on the first pass it runs GetBestApproachTowardsMajorCiv for China and records the following:

China's player ID
Neutral - 40
Friendly - 28
Afraid - 15
Guarded - 33
Hostile - 30
War - 38

It then stores this data for all of the players in the vector in some array-like structure for later retrieval.

-------------
**Step 3**
DoUpdateMajorCivApproaches then iterates through the "players to update" vector and calls GetBestApproachTowardsMajorCiv a second time, this time with bool bFirstPass set to false.

At a certain point in GetBestApproachTowardsMajorCiv, Persia's diplomacy AI would loop through each non-Neutral approach, and collect the approach weights for all players from the first pass.

So for instance, for the Guarded approach it might have values of:
Aztecs - 72
Babylon - 55
China - 33
America - 27

As China is ranked #3 for Guarded, it would get a reduction of -2x Persia's Guarded bias (the #1 civ gets no reduction and the others get -1x, -2x, -3x, etc).

Persia repeats this process for all approaches except Neutral, as the default. The result of this is that it doesn't matter in what order the players' approaches are updated, compared to the existing arbitrary order which makes it more likely for players updated last to not be DoW'ed.

-------------
**Step 4**
GetBestApproachTowardsMajorCiv then finishes, updates the average value for the next turn, logs the update, updates the war face if needed, and returns the selected approach to DoUpdateMajorCivApproaches, which sets the approach.

-------------
**Step 5**
End of DoUpdateMajorCivApproaches.

**Comment by LoneGazebo** [comment]
With that, your best bet is just another serialized variable. You could probably just use the same variable for both, since the data is only updated once per turn, and in sequence. So...

bFirstPass -> Get raw approach values -> set in SetPlayerApproachValue(ePlayer, eApproach, iValue)
!bFirstPass -> GetPlayerApproachValue(ePlayer, eApproach) -> refine -> SetPlayerApproachValue(ePlayer, eApproach, iValue)

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Hmm, in that case would I serialize a value for each approach and each player?

i.e. m_iWarApproachValue, m_iHostileApproachValue, etc.?

Or would it be a multidimensional array? I don't know how to serialize that, which is why I'm asking for help. :)

**Comment by LoneGazebo** [comment]
Multidimension - look at how m_ppaaeOtherPlayerMilitaryThreat does it

**Comment by HeathcliffWarriors** [comment]
Alright, thanks for the pointers!

**Comment by LoneGazebo** [comment]
And you don't have to serialize it, just init it and reset it - if the data doesn't need to be persistent across turns don't worry about the kstream stuff

**Comment by HeathcliffWarriors** [comment]
Alright, thanks for the pointers!

**Comment by LoneGazebo** [comment]
Yeah so your array will end up being m_ppaaeApproachValues[ePlayer][eApproachType] = iValue

**Comment by LoneGazebo** [comment]
Yep!

**Comment by HeathcliffWarriors** [comment]
```	
m_ppaaeOtherPlayerMilitaryThreat = &m_pDiploData->m_apaeOtherPlayerMilitaryThreat[0];
	for(iI = 0; iI < MAX_CIV_PLAYERS; iI++)
	{
		m_ppaaeOtherPlayerMilitaryThreat[iI] = &m_pDiploData->m_aaeOtherPlayerMilitaryThreat[REALLY_MAX_PLAYERS*iI];
	}
```

Unlike OtherPlayerMilitaryThreat, though, I don't think I need to be multiplying by REALLY_MAX_PLAYERS; should I be multiplying by NUM_MAJOR_CIV_APPROACHES? @LoneGazebo

**Comment by HeathcliffWarriors** [comment]
Like so?
```
	m_ppaaeApproachValues = &m_pDiploData->m_paeApproachValues[0];
	for(iI = 0; iI < MAX_MAJOR_CIVS; iI++)
	{
		m_ppaaeApproachValues[iI] = &m_pDiploData->m_aaeApproachValues[NUM_MAJOR_CIV_APPROACHES*iI];
	}
```

**Comment by HeathcliffWarriors** [comment]
And for resetting to default state:
```
	for (iI = 0; iI < MAX_MAJOR_CIVS; iI++)
	{
		for (iJ = 0; iJ < NUM_MAJOR_CIV_APPROACHES; iJ++)
		{
			m_ppaaeApproachValues[iI][iJ] = 0;
		}
	}
```

**Comment by LoneGazebo** [comment]
Yes, that looks right.

**Comment by LoneGazebo** [comment]
Of course you won't know 100% until you see Picard's face if you did it right or not :)

**Comment by HeathcliffWarriors** [comment]
lol...can you review the pull request once I send it? Just wanna make sure I didn't screw it up.

**Comment by LoneGazebo** [comment]
Just run a test or two, save and load, if it saves/loads and doesn't crash you're 95% of the way there.

**Comment by HeathcliffWarriors** [comment]
Alright, that's done. Thanks for the help!

Now I need to work that into GetBestApproachTowardsMajorCiv...

**Comment by HeathcliffWarriors** [comment]
I think the CvWeightedVector will come in handy for the ranking/sorting part.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo How do I pass a vector into a function? I want to pass the vePlayersToUpdate vector into GetBestApproachTowardsMajorCiv, so that it only grabs the approach values from the players who are actually being evaluated (players with no cities and teammates shouldn't be counted in this, for example).

**Comment by LoneGazebo** [comment]
Pass it like any other variable - just define a ‘blank’ vector in the variable set for the function

**Comment by LoneGazebo** [comment]
https://www.google.com/amp/s/www.geeksforgeeks.org/passing-vector-function-cpp/amp/

**Comment by HeathcliffWarriors** [comment]
Think I've got it! :)
