### ISSUE TITLE
Feitoria can be created on a mountain by nau

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#626]
This can happen when the Portuguese UU 'sells exotic cargo':
![feitoria](https://cloud.githubusercontent.com/assets/12978597/9839022/d1a1317c-5a75-11e5-8014-99d44a1cdaa9.jpg)

**Comment by TechpriestEnginseer** [comment]
Well, I hope it's intentionally. It doesn't hurt the gameplay that much...

**Comment by LoneGazebo** [comment]
It's fine. Is intentional, and (aside from a lil glitch) helps Nau on small island CSs.
