### ISSUE TITLE
Consistent CTDs with latest beta

### ISSUE THREAD

**Issue by lbrett3** [LoneGazebo/Community-Patch-DLL#6265]
[crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4226831/crash.zip)

_1. Mod version: latest beta, 2/18

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: Around turn 60 or so in every game I've played on this version (5 or 6 times so far), the game will close for no apparent reason. It's not hanging and stopping responding so much as alt-f4ing itself suddenly. I've tried different settings and such and disabled all mods besides the VP ones but it keeps happening. Nothing like this has happened before for me and I've played a couple of games on each of the most recent betas, including the previous one.

Edit: Forgot to mention, I cleared the cache and did a clean install of the mod but those didn't help

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi I caught one endless loop in your latest and patched it out - is there another endless loop in your homeland/tactical code? It was a busted 'while' loop.

**Comment by LoneGazebo** [comment]
just ran this save, no crash here...

**Comment by ilteroi** [comment]
hmm, i just tried CP only and indeed there was a crash on turn 0.

GC.getPromotionInfo(eNextPromotion) returned a nullpointer.

seems to be something wrong with the promotion tree? anyway i put in a failsafe.

now at turn 130, no other issues.
