### ISSUE TITLE
2/18 - Bad Tactical Move

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6266]
_1. Mod version (i.e Date - 2/9):_
2/18

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Here is an example of a bad tactical error by the AI. The enemy archer was standing on the plains space to the right of the city. It was a spot I was able to attack from my hill archer, so it made since for that unit to move. However, its moved right next to my 2 archers, allowing for quick destruction.

This might have made sense if the warrior had moved with it to pressure, but otherwise this is just a suicidal attack.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/74868845-83952200-531c-11ea-8a5b-f3b734f3512c.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
indeed that is bad. do you have a savegame?

**Comment by Stalker012345** [comment]
No, sorry:(
