### ISSUE TITLE
2/18 - Garrison affecting RCS for Cities

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6267]
_1. Mod version (i.e Date - 2/9):_
2/18

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
G, you asked me to show you this if I could repeat the error, and I have an example for you. In the example below, the city has an RCS of 5. Once the warrior is upgraded to a spearmen in the next turn, the RCS increases.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/74869518-b5f34f00-531d-11ea-94fb-24ee2874eb86.png)

![image](https://user-images.githubusercontent.com/20593976/74869437-90fedc00-531d-11ea-95e2-60a4f6f97753.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
hmmmmmmmmm is it only on the turn that you upgrade?

**Comment by LoneGazebo** [comment]
if you move in/out does it reset?

**Comment by Stalker012345** [comment]
When I move a unit in the RCS goes up. When I move it out, the RCS goes
down.

**Comment by LoneGazebo** [comment]
any unit? or just that dude?

**Comment by Stalker012345** [comment]
Any unit. Both for the AI and for me.

**Comment by LoneGazebo** [comment]
I still can't replicate this. Next time you see it, I need a savegame. But wait until the next version.

**Comment by Stalker012345** [comment]
Here you go. Save game is also attached, just move the GDR into Nippur to see the RCS go up.

![image](https://user-images.githubusercontent.com/20593976/76017625-85e2a900-5ee4-11ea-87eb-9b82d106109c.png)

![image](https://user-images.githubusercontent.com/20593976/76017664-94c95b80-5ee4-11ea-84ab-e32da5fd55c0.png)

[City RCS Issue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4294777/City.RCS.Issue.zip)

**Comment by Stalker012345** [comment]
As of 3/15, issue is still occuring.
