### ISSUE TITLE
unit:IsAdjacentTo...()

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#627]
I'm preparing to update a few of my civs, and so I'm looking to improve stability by reducing the amount of LUA needed for things already somewhat covered by the CP DLL (so forgive me if my requests become more frequent as of late). One thing that would be useful is if the unit:IsAdjacentTo() series of methods could be expanded to allow checks for Unit Promotion, Unit Class, and Unit Combat (sort of like the request for this with IsWithinDistance for while back - I thought of using this first, but evidently a unit of the same type considers itself to be within its own distance).

So, I'd be looking for something like the following:

unit:IsAdjacentToCombatType(iCombatType, bIsFriendly, bIsEnemy)
unit:IsAdjacentToUnitClass(iPromotionClass, bIsFriendly, bIsEnemy)
unit:IsAdjacentToUnitPromotion(iPromotionType, bIsFriendly, bIsEnemy)

Hopefully something like this would be easy enough to implement. Thanks as ever for your help.

P.S. How do you label posts so that it's clearer to identify this as a request?

**Comment by LoneGazebo** [comment]
I added a label for you.

I'll look at this - may be a little while, as I've just pushed out a new version with your previous request, and mod turnaround is a little slower (critical bugs fewer and fewer).

**Comment by LoneGazebo** [comment]
Done.

I also edited the 'within distance' ones to not look at the plot the unit is on (as that negates the whole point of those functions). So these four do a similar function as if you set the distance to 1 in those, but they'll be a little bit snappier (and also easier for you to write/use).  Here's the code:

IsAdjacentToUnit, iUnitType, bool, bool
IsAdjacentToUnitClass, iUnitClassType, bool, bool
IsAdjacentToUnitCombatType, iUnitCombatType, bool, bool
IsAdjacentToUnitPromotion, iPromotionType, bool, bool

**Comment by JFDaly** [comment]
Thanks much :) I plan to use these aplenty in my next releases.
