### ISSUE TITLE
CTD around T100-130

### ISSUE THREAD

**Issue by anders4** [LoneGazebo/Community-Patch-DLL#6270]
_1. Mod version (i.e Date - 2/9):_
2.18.b

_2. Mod list (if using Vox Populi only, leave blank):_
really advanced setup

_3. Error description:_ 
Crash to desktop at around T100-130 every game I've tried.

_4. Steps to reproduce (optional):_
Press next turn in attached save.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4228296/Logs.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4228297/CvMiniDump.zip)
[Elizabeth_0123 BC-0925.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4228298/Elizabeth_0123.BC-0925.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by anders4** [comment]
I reverted to 2.9,4b to make sure that nothing is wrong/changed on my side and that version still plays as it should.

**Comment by ASCII-Guy** [comment]
I'm going to test your save file tonight using the debugger.
