### ISSUE TITLE
GameEvent Request: Anarchy

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#6273]
Would it be possible to get a GameEvent that registers when Anarchy begins and ends? I imagine something that fires off of SetAnarchyNumTurns. 

**GameEvents.PlayerAnarchy.Add(function(iPlayer, bStart, iTurns) end)**

Would be much appreciated. Surprised I never asked for it before tbh. Thank.

**Comment by LoneGazebo** [comment]
Will be in next version.
