### ISSUE TITLE
AI Archers not attacking

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6275]
2-18b

![civarcher](https://user-images.githubusercontent.com/53142313/75028698-0ba43480-54a1-11ea-8716-437663c0a698.png)

I ended my turn in range of a 100% health enemy archer garrison who could have fired a cheap shot at my unit but decided not to. This is not the first time I witness archers standing still, sometime they're also on some hill 2 tiles away and ignore my unit, maybe because the damage they'd do would be negligible?

**Comment by ilteroi** [comment]
cannot reproduce but there have been a number of changes in the meantime ...
