### ISSUE TITLE
2/18 - (Tactical AI) Unit not pushing in on easy city kill

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6276]
_1. Mod version (i.e Date - 2/9):_
2/18

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Ghandi caught me with my pants down. My city here is very vulnerable, and yet the horseman has been sitting there for 3 turns not attacking. I'm pretty sure it could take it down by itself, but if nothing else could seriously wound it.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/75047419-58c9db80-548c-11ea-87c6-030f73e65f72.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Here's a saved game (note I'm using the experimental DLL). 
[Uploading Tactical AI Error.zip…]()

**Comment by ilteroi** [comment]
yeah, AI was too careful in some situations, if it couldn't kill a target in one turn it wouldn't attack. also in some situations they would not attack a city until they had significantly superior forces in place. should be better now.

**Comment by LoneGazebo** [comment]
Any luck in tracking down the elusive CTD?

**Comment by ilteroi** [comment]
nope
