### ISSUE TITLE
Feature Request: SetMinorUniqueUnit() and SetMinorPersonality()

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#6277]
Currently, when assigning a city to an available minor civ player, thereby creating a new city-state, the new city-state does not have a [MinorCivPersonalityType ](http://modiki.civfanatics.com/index.php?title=MinorCivPersonalityType_(Civ5_Type))set. Also, if the new city-state is militaristic, it does not have a unique unit. 

I am still working on the phoenicia mod and I don't care if the personalities/uniques are pre-assigned at the game start, or if it is easier to expose them to lua so I can assign them on creation.

**Comment by HeathcliffWarriors** [comment]
How is this handled for city revolts?

**Comment by pineappledan** [comment]
They get personalities and unique units. There's no way to force a city to revolt like this, so I have been using AcquireCity(). It works well enough except no personality or UU is assigned.
![image](https://user-images.githubusercontent.com/33136027/75094641-6d6ca900-554a-11ea-85a9-d12c6c2e7b27.png)

**Comment by pineappledan** [comment]
So maybe it would be less work if there was some sort of ForceRevolt(cityID, Captured, Traded)? I don't know what would be easier

**Comment by LoneGazebo** [comment]
Damn, meant to tell you, this already exists for Game

Game.DoSpawnFreeCity(pCity);

It picks the minor civ stuff automatically.

**Comment by pineappledan** [comment]
Will anything happen if there are no more player slots to add new players?

**Comment by pineappledan** [comment]
this DoSpawnFreeCity() method does not resolve the biggest problem with city states: Only the city-state player is "grabbable". There is absolutely no method where you can select or manipulate a city state city. So, if I set that city into revolt using Game:DoSpawnFreeCity() then I have no way to define the new player, because pCity:GetOwner() doesn't do anything. With my old code, which used player:AcquireCity(), the player was already defined, so i could give them a dummy policy which marked them as a Phoenician city-state. I can't do that with this new method.

**Comment by LoneGazebo** [comment]
Good to know.

**Comment by pineappledan** [comment]
So yeah. I guess I would still like a way to set description, shortdescription, adjective, personality, and unique unit for minor civs...  

I actually think that function would give me an opportunity to tie the phoenician CSs back to phoenicia by forcing them to give one of phoenicia's UUs as a unique military unit.

**Comment by pineappledan** [comment]
continued to tinker with it a little. 

Game.DoSpawnFreeCity(pCity) works fine. i can trigger multiple revolts and it's no longer CTD'ing
The CTD was because I was grabbing the settled city's name, then converting it to a city-state, then trying to rename it back to its original name. This caused a problem with the civ city-names list, I think, and wasn't doing anything because, once again, I can't manipulate a CS city.

I made a workaround where I just selected the city plot and got the player using plot:getOwner() - I don't know why I didn't think of this before, so I can spawn new cities with personalities and UUs, but :
1. I can't change their names to phoenician ones
2. I can't change their adjectives or descriptions
3. Since Bratislava is the first city state in the player list, they are settled first 9/10 times. Functionally, this makes Phoenicia's city list irrelevant, and it really hurts their flavor. The only indication that they are settled cities by phoenicia is that the symbol in the name.

**Comment by LoneGazebo** [comment]
and city:setName doesn't work?

**Comment by pineappledan** [comment]
It worked on the first city, but it was the source of the crash on the second city. I commented out the city:SetName() and it worked as intended

**Comment by LoneGazebo** [comment]
hmm...and you're sure the city pointer in the second instance was valid?

**Comment by pineappledan** [comment]
Here's the full code, not too complicated. you can see the GetName() and SetName() line commented out before and after I revolt the city
```function OnFoundMetropolis(iPlayer, iX, iY)

	local pPlayer = Players[iPlayer]
	if not (pPlayer and pPlayer:GetCivilizationType() == eCivilizationPhoenicia) then return end
	
	local pPlot = Map.GetPlot(iX, iY)
	local pCity = pPlot:GetPlotCity()
	if not pCity:IsOriginalCapital() then 
		
--		local pMinorName = pCity:GetName()
		Game.DoSpawnFreeCity(pCity)
--		pCity:SetName(pMinorName)
		local pNewCityOwner = Players[pPlot:GetOwner()]
		pNewCityOwner:GrantPolicy(GameInfoTypes.POLICY_PHOENICIAN_METROPOLIS, true)
		pNewCityOwner:ChangeMinorCivFriendshipWithMajor(pPlayer:GetID(), 35 + math.max(1, pPlayer:GetCurrentEra())*30)
	end
end```
Maybe this could be put out to the general VP community, but why not make automatically edit the adjective and description of a revolting city-state to the parent civ?

Right now, if my Danish city of Viborg revolts, suddenly they are the Prague city of Prague.

**Comment by LoneGazebo** [comment]
aha! when you spawn the city, the 'old' city is deleted, so you need to get the city again

**Comment by LoneGazebo** [comment]
so you need a second pCity = pPlot:GetPlotCity()

**Comment by pineappledan** [comment]
ooooh

**Comment by LoneGazebo** [comment]
Isn't that what all CSs look like, though?

**Comment by LoneGazebo** [comment]
Are you saying it should stay 'Danish City of Prague?'

**Comment by LoneGazebo** [comment]
another easy method would be to grab the pCity by calling for the capital.

**Comment by pineappledan** [comment]
I'm grabbing off the plot for now. It's loading up.

I'm saying that in the current VP build, if a city revolts, the only marker that it used to belong to a major civ is that civ's icon in the banner. I had a game where Austria's city of Linz revolted. It got turned into Bratislava. Austria then founded another city named Linz later in the game. The current implementation just strikes me as really weird, like the city really is deleted and its culture is replaced wholesale by something that popped out of the ether.

I'm just suggesting that if there was a way to store the original city's adjective and city name, that maybe the revolting city-state should keep those when it revolts. I think it would help immersion.

**Comment by LoneGazebo** [comment]
gotcha. I'd need to look at the code, 'save off' that value if I can. Is your code working for now?

**Comment by LoneGazebo** [comment]
almost wonder if it should just be 'Free City of X' instead of the civ adj.

**Comment by pineappledan** [comment]
Had to restart. I settled by second city before anyone else had settled their first. If your city is given away and there are no other players on the map you automatically win the game, so I couldn't properly test it. oops😆

**Comment by LoneGazebo** [comment]
haha

**Comment by pineappledan** [comment]
free city of X would work too. culture is less malleable than that generally, so my own preference would just be to keep their parent adjective. The American colonists still largely considered themselves english/etc. for a while after independence, for example.

**Comment by pineappledan** [comment]
That did it. Thanks for helping with that; probably wouldn't have figured out that I needed to call a second city on my own.
![image](https://user-images.githubusercontent.com/33136027/75115890-294bd800-5620-11ea-8d43-5822939e3efb.png)

**Comment by LoneGazebo** [comment]
nice!

**Comment by LoneGazebo** [comment]
well the primary reason to do 'free city' is that you'd need to set the civ's name and adj to be the parent civ's, which could get confusing in the sidebar, etc.

**Comment by LoneGazebo** [comment]
otherwise it'd be 'Danish City of Prague' but still Prague in the sidebar. So the Danish would kinda be out of left field.

**Comment by pineappledan** [comment]
So more to identify revolted cities as a game entity unto themselves, rather than for any verisimilitude reasons. Fair enough. Though I don't think this would be worth doing unless you couldn't also have the city retain its original name after it revolted. Having Tokyo wink out of existence and then having Samarkand appear in its place - with all the cultural baggage that is signified by Samarkand - is weird.

**Comment by LoneGazebo** [comment]
I can have it keep the original name, sure.

**Comment by pineappledan** [comment]
Third option. since the city-states do this already, maybe just make the city name the adjective and the civ description?

So it's just the Tokyo of Tokyo, whose capital is Tokyo

**Comment by LoneGazebo** [comment]
Free City would inform players that did not witness the event just exactly what happened, though.

**Comment by pineappledan** [comment]
I do prefer free city as the adjective. Just wanted to make sure we covered bases.

**Comment by pineappledan** [comment]
Time to stress test this baby. I want to see what happens when the game runs out of player slots

**Comment by LoneGazebo** [comment]
It will return false if there are no more player slots.

**Comment by LoneGazebo** [comment]
ah, so, you can't 'change' the adjective, it pulls directly from the database for minor civs. So I'd need to set a 'free city' flag and have that grab a TXT_KEY for free City. Not a big deal, but I don't want to add a memory value right now so I'll hold on this until next version.

**Comment by pineappledan** [comment]
Forgot to mention this, but it [came up in another thread.](https://forums.civfanatics.com/threads/ithobaal-is-phoenician-civilization.655685/#post-15704606) 

The rebellion mechanic always spawns the same city-states in the same order (ie. it will always place Bratislava if it does not already exist in-game). So, an added benefit of changing the names/descriptions/adjectives is it would obfuscate the predictability of this mechanic

**Comment by pineappledan** [comment]
Necro time!

Wondering if there was any update on your exploration of the adjective, 'free city flag', and if you had an opportunity to implement this? It would be a big improvement on the current rebellion system.

**Comment by LoneGazebo** [comment]
The problem is that the code for changing stuff like this is actually not very real-time friendly because a lot of the data is cached at load.

**Comment by pineappledan** [comment]
In that case, couldn't you cache any minor player who isn't assigned a starting plot/units as 'free city' at load?

If those players are ever going to become visible over the course of the game it is because they were added via rebellion later on, thus, they are free cities, no matter if that adjective was assigned during play or at the start.

**Comment by pineappledan** [comment]
The only remaining issue would be the player name. You wouldn't be able to assign them a player name at the beginning of the game, because you wouldn't know what civ/city rebelled when starting the game. 

Maybe there is a name, like, free city, that could describe all rebellion players, or they could be assigned a value like {Player:GetCapitalCity:GetName}, so the player's name is cached as a variable that depends on the city name?

**Comment by LoneGazebo** [comment]
Minors aren’t cached that way. The spots are reserved but not all slots. It’s very complicated to add or remove players on the fly. I’ve messed with it a lot, and it is unstable and unreliable.
