### ISSUE TITLE
CP only oddities

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6279]
turn 215, a single worker in the whole hunnic empire

![image](https://user-images.githubusercontent.com/1358966/75097447-2b278400-55ab-11ea-8e14-e27b2662a8fa.png)

guzana has 0 improvements ... and what is the inquistor doing? they don't have their own religion, therefore won't build missionaries, but apparently inquisitors, even if there is zero pressure from other religions.

**Comment by LoneGazebo** [comment]
Odd. The unitproduction AI isn’t exclusive to the CBO, no idea why it’s not making units. 

No idea on inquisitor.

**Comment by LoneGazebo** [comment]
Side note: did you see comments on missionaries not spreading in current version? Something to keep eye on.
