### ISSUE TITLE
CTD 2.18.3b

### ISSUE THREAD

**Issue by anders4** [LoneGazebo/Community-Patch-DLL#6280]
1. Mod version (i.e Date - 2/9):
2.18.3b

2. Mod list (if using Vox Populi only, leave blank):
really advanced setup

3. Error description:
Crash to desktop at end turn T105,
(adding save for T104 also if any use)

4. Steps to reproduce (optional):
Press next turn in attached save.
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4240521/CvMiniDump.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4240522/Logs.zip)
[AutoSave_0105 BC-1375.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4240523/AutoSave_0105.BC-1375.zip)
[AutoSave_0104 BC-1400.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4240524/AutoSave_0104.BC-1400.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4240539/CvGameCore_Expansion2.zip)

Do me a favor - drop this in your CP, make it crash, then post the save and logs again.

**Comment by LoneGazebo** [comment]
And the minidump file. Thanks! I can't get yours to crash either, and the minidump file isn't being polled by my debugger. I need a new minidump on this DLL.

**Comment by anders4** [comment]
I used the same autosave, did the same move and same result on end turn,
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4241010/CvMiniDump.zip)
[AutoSave_0105 BC-1375.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4241011/AutoSave_0105.BC-1375.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4241012/Logs.zip)

**Comment by LoneGazebo** [comment]
Alright, success, I see the crash. @ilteroi 

![image](https://user-images.githubusercontent.com/7849458/75115097-5947ab00-5621-11ea-866a-ccba957202a9.png)

**Comment by LoneGazebo** [comment]
This is a pretty standard function, I don't see why it would crash, but that's where it is crashing.

**Comment by LoneGazebo** [comment]
@anders4 try this, may not work but worth a go: 

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4241593/CvGameCore_Expansion2.zip)

**Comment by ilteroi** [comment]
hmm i cannot see a fault in the piece or code. what did you change?

**Comment by LoneGazebo** [comment]
I added an 'empty' check for the currentturnunits and added a check for your debug code to work like your tactical debug code does (gHomelandDebugOutput > 0)

**Comment by LoneGazebo** [comment]
I thought maybe it was a bad pointer being called that we can't see because of the debug code. Dunno.

**Comment by LoneGazebo** [comment]
The common complaint is that it is happening on CS turns, so possible that a bad m_pPlayer is sliding in? I just don't know what else it could be.

**Comment by lbrett3** [comment]
Not the guy you directed it at but I tried a game with the file you posted but still got a crash (in half the number of turns as usual this time, not that that necessarily means anything)

[crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4241717/crash.zip)

**Comment by ilteroi** [comment]
smells like memory corruption. nasty. also seems to occur only in release builds?

**Comment by LoneGazebo** [comment]
from what I can tell. Weird that neither you and I can reproduce it and, more importantly, reloading doesn't seem to fix it. I removed the LUAJit stuff just to make sure that wasn't making us immune, didn't help. Also tried full screen etc.

**Comment by lbrett3** [comment]
This is a complete shot in the dark, but could the fact that I'm still on Windows 7 have any bearing on this at all?

**Comment by ASCII-Guy** [comment]
I think the issue might be line 2290 in HomelandAI. Specifically `&& !pUnit->TurnProcessed()` that was added with the 2/18 release.

**Comment by JamesNinelives** [comment]
I rushed through a game with no minor civs on it to see what would happen and still got a crash, in case that's relevant. This patch, with the dll G shared above. In this case, the game crashed while Player 10's turn symbol was visible rather than one of the minor civs (the game has 12 players).

No crash report generated. Crash on Turn 120, I have attached a Turn 119 save and logs.

[J9CrashinformationA.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4243334/J9CrashinformationA.zip)

**Comment by ilteroi** [comment]
no minidump? that's weird.

also, fwiw, i'm at turn 230 in an autoplay game, release build, no crash either.

**Comment by LoneGazebo** [comment]
I still haven't had a crash, and there's apparently a number of other people who have also not crashed. So it isn't 100%

**Comment by anders4** [comment]
> 
> 
> @anders4 try this, may not work but worth a go:
> 
> [CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4241593/CvGameCore_Expansion2.zip)

Same result CTD (sry for slow respons).
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4252160/CvMiniDump.zip)

**Comment by anders4** [comment]
Additionally.
Win7, I got forced a visual C runtime upgrade and had to upgrade graphics drivers for other game.
But it shouldn't matter? since the previous versions work just fine.

**Comment by JamesNinelives** [comment]
Yeah it is strange that it's happening for some and not others. I'm on Win7, but as noted has no issues with the previous patches. Also interesting to me that there are people commenting who have never had CTDs before but get it on this patch.

**Comment by RyesDailee** [comment]
Not sure if it matters, but will echo others: I am also using Windows 7. The CTD I posted occurs while processing an AI player turn. Tried with the updated file and crash still occurs.

**Comment by anders4** [comment]
I've also tested with reverting to my old graphics driver to be sure that it was not the issue.
And same result and crash.

**Comment by JamesNinelives** [comment]
Here's some more files in case they help (before moving on to the next patch).

No minidump, as per last time. I searched /C/ for a file by that name to see if it was being created somewhere else by accident but no luck. Crash occured on Turn 124, on Epic game speed (beginning of classical era/end of ancient era).

Something else odd happened too. I reinstalled 2/18/3b in case in messing around with the dll I had messed something up. Then I decided to check my local files were OK, so I went to Steam and validated them, and it told me this: (3 files failed to validate and will be reacuired).

![Files](https://user-images.githubusercontent.com/61379041/75653152-e5984480-5c97-11ea-8b1b-e366fbc23811.PNG)

That was before the crash. After the crash, did the same thing on Steam and got the same result...

![Capture2](https://user-images.githubusercontent.com/61379041/75653267-37d96580-5c98-11ea-8621-16dd12525d52.PNG)

I made sure to watch the download to makes sure it happened properly. Seemed fine. I'm going to try the new patch now, but I'm wondering if I should delete my local files and reinstall Civ V completely at this point.

Mods:
Community Events (v. 5)
Civ Names by Policies (v. 8)
Global Relations (v. 7)
Historical Religions (BNW or GK) (v. 55)
Krazjen's Great Musicians Pack (v. 1)
Quick Turns
Really Advanced Setup
Unique Cultural Influence

[ReportC.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273843/ReportC.zip)

**Comment by ilteroi** [comment]
is there maybe any relation to game settings here? detail level? dx9 vs dx11? movement animations on/off?

**Comment by JamesNinelives** [comment]
I have DirectX11, movement animations on. Here's my graphical settings: 
![20200304011629_1](https://user-images.githubusercontent.com/61379041/75801691-841ac780-5db6-11ea-969f-9e6e17f7dd92.jpg)

**Comment by LoneGazebo** [comment]
Try the updated DLL I posted in the 3-1 CTD Issue
