### ISSUE TITLE
CTD 2.18.3b

### ISSUE THREAD

**Issue by RyesDailee** [LoneGazebo/Community-Patch-DLL#6281]
_1. Mod version (i.e Date - 2/9):_
2,18,3b

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
CTD on Turn 73

_4. Steps to reproduce (optional):_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4240552/Logs.zip)
[Huns_3.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4240553/Huns_3.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4240554/CvMiniDump.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by JamesNinelives** [comment]
1. Information on crash/bug

Turn 113, Turn 123. No information recieved. Crash straight to desktop at the beginning of my turn (or possibly at the very end of the AIs turn). The last thing I see is the city-state turn processing. The screen does not show anything happening though, so it seems to me that the AI has finished their turn at this point.

Edit: Actually, on further reflection it occurs to me that I have yet to see the red barbarian symbol before the game crashes.

2. Modlist (if using mods outside of the Community Patch Project set)
Community Events (v. 5)
Civ Names by Policies (v. 8)
Global Relations (v. 7)
Historical Religions (BNW or GK) (v. 55)
Krazjen's Great Musicians Pack (v. 1)
Quick Turns
Really Advanced Setup
Unique Cultural Influence

3. Supporting information

[Civ Autosaves Ninelives.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4241489/Civ.Autosaves.Ninelives.zip)

Screenshots of turn the crash occured before pressing 'End Turn'

![20200223215033_1](https://user-images.githubusercontent.com/61379041/75114951-62725f80-5695-11ea-98cf-bfbf1f47f92b.jpg)

![20200223232508_1](https://user-images.githubusercontent.com/61379041/75114933-3ce55600-5695-11ea-816e-38917093d7d4.jpg)
