### ISSUE TITLE
AI prioritization of Settlers

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6282]
Feedback on the forums, in general, seems to indicate that humans are handling the slower pace of expansion a lot better than the AI is. Maybe AI needs to produce Settlers more often/earlier?

**Comment by LoneGazebo** [comment]
>handling the slower pace of expansion a lot better than the AI
What do you mean? Elaborate?

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo CrazyG made a post last version which, among other things, described all of the AIs expanding much more slowly than he was.

In the current version, the posts made in the 2-18 thread describe the AI expanding much more quickly when the difficulty handicaps (particularly the capital founding bonus) were higher, but continuing to expand slowly when they were lower.

This leads me to believe there might be an issue with AI prioritization of Settlers compared to humans, since requiring higher difficulty handicaps may mean they are building other things when they should be building Settlers.

Worth noting, though, that CrazyG in his post did not construct a lot of military - the AI does tend to build more military early on, from what I've seen.
