### ISSUE TITLE
CTD on City State turn

### ISSUE THREAD

**Issue by JohannesGaessler** [LoneGazebo/Community-Patch-DLL#6283]
_1. Mod version (i.e Date - 2/9):_
2-18-3b

_2. Mod list (if using Vox Populi only, leave blank):_

- Really Advanced Setup
- Wonder Race
- I am playing on Linux through WINE

_3. Error description:_ 
Reproducible CTD on City State turn.

Files:
[debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4241710/debug.zip)

**Comment by HungryForFood** [comment]
I found a crash during city state turn when testing the Phoenicia civ. Fixed for that case, but maybe this is related as well?

See the first commit in #6291.
