### ISSUE TITLE
Wonder policy req and techs needed

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6285]
I recently asked why if Forum required 1 tech less. Now I got to renaissance and found more mess. And further is even worse. My analysis:
![obraz](https://user-images.githubusercontent.com/33016300/75122580-8175ef00-569f-11ea-8c26-447b060eba7e.png)
I suppose it has left from base game somehow, but after tech tree rework it broke.

**Comment by Stalker012345** [comment]
The one wonder for me that always feel out of sorts is Brandenburg. I frequently get to that tech and need like 2-3 more policies to snag it.

I'm often capped on Porcelain and Taj but I always assumed that was designed as a culture heavy benefit, and its normally only 1 policy that caps me.

**Comment by adaneslavo** [comment]
Any thoughts @LoneGazebo?

**Comment by LoneGazebo** [comment]
I looked them over, didn't see any issues.

**Comment by adaneslavo** [comment]
What was concernig me in this table, was fact that f.e. you need 6 tech more gor some industrial era wonders, were they require 1 policy less in the same time. This means that some wonders are long time available, but stay untouched because of policy requirement.

**Comment by adaneslavo** [comment]
Did you aplly some corrections or it was left as it is?
