### ISSUE TITLE
IsWithinDistanceOfCity no longer working

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#6287]
The **unit:IsWithinDistanceOfCity()** method seems to have broken somewhere along the line, with the game returning 'nil method' when trying to call it. All the neighbouring methods - IsWithinDistanceOfUnit/UnitCombat/UnitPromotion, etc - are all working fine, so it's just this one. This is on the latest beta from Feb. 18, but I'm not sure for how long it's been like this.

**Comment by HungryForFood** [comment]
This is a CP lua method right? Weird, seems to have been deleted somehow. I'll add it back in.

**Comment by JFDaly** [comment]
Yeah. Thanks.

**Comment by HungryForFood** [comment]
Try if this works.
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4253361/CvGameCore_Expansion2.zip)

**Comment by JFDaly** [comment]
Yeap, that's fixed it. Thanks.
