### ISSUE TITLE
2/18 - Joining a joint war has the person declared on me

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6289]
_1. Mod version (i.e Date - 2/9):_
12/8

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Brazil asked me to join him in a war against Korea, and I said give me 10 turns. 10 turns later he asked me to commit. I declare war, which actually declares against both Korea and Brazil.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Ah, I see the reason. Brazil actually has a defensive pact with Korea now! So he's asking me to join him in a war against defensive pact partner. And while he does declare on me, he also declares on Korea.

**Comment by LoneGazebo** [comment]
Weird that such a check never made it through, I can fix that no problem.

**Comment by HeathcliffWarriors** [comment]
That IS really strange.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Have you fixed this on your end already?

**Comment by LoneGazebo** [comment]
yes

**Comment by HeathcliffWarriors** [comment]
great

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Looks like the fix didn't make it into the latest version.

**Comment by HeathcliffWarriors** [comment]
I'll just fix and send a pull request. :)
