### ISSUE TITLE
EUI Pledge of Protection counter disrespancy

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#629]
![8930_2015-09-16_00002](https://cloud.githubusercontent.com/assets/1131228/9888752/35f3ae7a-5c10-11e5-9e2e-af876f4f232a.png)
![8930_2015-09-16_00003](https://cloud.githubusercontent.com/assets/1131228/9888754/38a31692-5c10-11e5-929a-40ce46906f4b.png)

**Comment by LoneGazebo** [comment]
I guess EUI hardcoded the value, instead of, you know, using the stupid define. Sigh...I really feel like bc1's work is in steep decline lately, but maybe that's just me.
