### ISSUE TITLE
production choice

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6292]
hamburg under siege (that's a hunnic tank), builds a stadium

![image](https://user-images.githubusercontent.com/1358966/75322537-3d3b4800-5873-11ea-9fec-fcfbe1f0d4f8.png)

417, Germany, Hamburg, PRE: Building, Research Lab, 6825, 5
417, Germany, Hamburg, PRE: Building, TwoKay Foods Office, 5600, 2
417, Germany, Hamburg, PRE: Building, Strategic Defense System, 5425, 6
417, Germany, Hamburg, PRE: Unit, Panzer, 5149, 7
417, Germany, Hamburg, PRE: Building, Mine Field, 4750, 4
417, Germany, Hamburg, PRE: Unit, Infantry, 4560, 5
417, Germany, Hamburg, PRE: Unit, Battleship, 4545, 6
417, Germany, Hamburg, PRE: Unit, Destroyer, 4040, 5
417, Germany, Hamburg, PRE: Building, Broadcast Tower, 3300, 3
417, Germany, Hamburg, PRE: Unit, Cargo Ship, 3220, 3
417, Germany, Hamburg, PRE: Unit, Paratrooper, 2997, 4
417, Germany, Hamburg, PRE: Building, East India Company, 2900, 1
417, Germany, Hamburg, PRE: Building, Castle, 2375, 1
417, Germany, Hamburg, PRE: Unit, Machine Gun, 2258, 4
417, Germany, Hamburg, PRE: Building, Stable, 2257, 1
417, Germany, Hamburg, PRE: Unit, Caravan, 2160, 3
417, Germany, Hamburg, PRE: Unit, Submarine, 2020, 5
417, Germany, Hamburg, PRE: Building, Refinery, 1830, 5
417, Germany, Hamburg, PRE: Unit, Artillery, 1824, 5
417, Germany, Hamburg, PRE: Unit, Light Tank, 1440, 4
417, Germany, Hamburg, PRE: Building, Stadium, 1332, 4
417, Germany, Hamburg, PRE: Building, Barracks, 980, 1
417, Germany, Hamburg, PRE: Building, Monument, 660, 1
417, Germany, Hamburg, PRE: Process, Farming, 560, 1
417, Germany, Hamburg, PRE: Project, Public Works, 550, 6
417, Germany, Hamburg, PRE: Process, Research, 544, 1
417, Germany, Hamburg, PRE: Process, Wealth, 530, 1
417, Germany, Hamburg, PRE: Process, Arts, 330, 1
417, Germany, Hamburg, PRE: Building, Constabulary, 125, 2
417, Germany, Hamburg, PRE: Process, Defense, 100, 1
417, Germany, Hamburg, PRE: Unit, Worker, 60, 1
417, Germany, Hamburg, SKIPPED: Research Lab, Val: -1088, TURNS: 5
417, Germany, Hamburg, SKIPPED: Cargo Ship, Val: 0, TURNS: 3
417, Germany, Hamburg, SKIPPED: East India Company, Val: 0, TURNS: 1
417, Germany, Hamburg, SKIPPED: Stable, Val: -793, TURNS: 1
417, Germany, Hamburg, SKIPPED: Caravan, Val: 0, TURNS: 3
417, Germany, Hamburg, SKIPPED: Refinery, Val: 0, TURNS: 5
417, Germany, Hamburg, SKIPPED: Barracks, Val: -536, TURNS: 1
417, Germany, Hamburg, SKIPPED: Public Works, Val: 0, TURNS: 6
417, Germany, Hamburg, SKIPPED: Constabulary, Val: -497, TURNS: 2
417, Germany, Hamburg, SKIPPED: Worker, Val: 0, TURNS: 1
417, Germany, Hamburg, POST: Building, Castle, 8604, 1
417, Germany, Hamburg, POST: Building, Stadium, 7932, 4
417, Germany, Hamburg, POST: Unit, Submarine, 2593, 5
417, Germany, Hamburg, POST: Building, Monument, 2376, 1
417, Germany, Hamburg, POST: Unit, Battleship, 2351, 6
417, Germany, Hamburg, POST: Unit, Destroyer, 2239, 5
417, Germany, Hamburg, POST: Unit, Light Tank, 2041, 4
417, Germany, Hamburg, POST: Unit, Paratrooper, 1935, 4
417, Germany, Hamburg, POST: Unit, Artillery, 1907, 5
417, Germany, Hamburg, POST: Unit, Panzer, 1856, 7
417, Germany, Hamburg, POST: Unit, Machine Gun, 1848, 4
417, Germany, Hamburg, POST: Building, Strategic Defense System, 1801, 6
417, Germany, Hamburg, POST: Unit, Infantry, 1733, 5
417, Germany, Hamburg, POST: Building, Broadcast Tower, 1444, 3
417, Germany, Hamburg, POST: Process, Defense, 586, 1
417, Germany, Hamburg, POST: Building, Mine Field, 538, 4
417, Germany, Hamburg, POST: Building, TwoKay Foods Office, 472, 2
417, Germany, Hamburg, POST: Process, Farming, 293, 1
417, Germany, Hamburg, POST: Process, Wealth, 144, 1
417, Germany, Hamburg, POST: Process, Research, 129, 1
417, Germany, Hamburg, POST: Process, Arts, 123, 1
417, Germany, Hamburg, SEED: 3687753091468301551, CHOSEN: Building, Stadium, NoRush, ERA: 6, TURNS: 4

**Comment by LoneGazebo** [comment]
Football is important okay.?
