### ISSUE TITLE
Embarked civilian units don't stack

### ISSUE THREAD

**Issue by JamesNinelives** [LoneGazebo/Community-Patch-DLL#6295]
_1. Mod version:_
2/9/3b, 2/9/4b, 2/18b, 2/18/3b, possibly earlier.

_2. Mod list:_
Really Advanced Setup.

_3. Error description:_ 
Embarked civilian units cannot move to occupy the same water tile. Have noticed this missionaries, inquisitors, and workers.

Oddly they can be embarked to occupy the same tile however. And they can stack once their movement points have been used up!

It's only if one embarked civilian unit tried to move into the space of another which also has movement left, they switch space.

I tried it on each of the 4 betas mentioned above and got the same results. It is not the case on the next most recent beta version that I have, which is 11/8.

_4. Steps to Reproduce:_

Research Fishing (or play as Polynesia), build 2 workers, embark them adjacent to one another. Then try to move one into the other's space.

**Comment by ilteroi** [comment]
seems to be an unintended swap ...
