### ISSUE TITLE
Feature Request: Trait Column IgnoresMinPopulation

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#6299]
It would be really great to have a Boolean trait for OCC civs that allows them to ignore the minimum population requirements for national wonders.

**Comment by LoneGazebo** [comment]
I can just have the code ignore that min requirement if the player only has one city. Seems logical. One less memory value.

**Comment by pineappledan** [comment]
I would like this code for Phoenicia, and it is technically possible for the civ to have >1 city (Phoenicia gets to keep conquered capitals). 

Maybe a national population modifier? ie setting it to -100 would mean the civ ignores minimum pop requirements, but setting it at -50 means it still requires half the normal amount? That could be useful for semi-OCC civs like Venice.

**Comment by LoneGazebo** [comment]
Right now the OCC trigger cuts cost to 1/3 of normal value.  What's the UA element for Phonecia? I can just add that to the check.

**Comment by pineappledan** [comment]
Just the UA Trait?
it's 'TRAIT_PHOENICIAN_METROPOLIS'

**Comment by LoneGazebo** [comment]
No, the trait column value. i.e. <SettlersAsCS>true</SettlersAsCS>

**Comment by pineappledan** [comment]
I haven't made one because the trait runs entirely off lua right now.
Maybe I just add one, maybe called <ReducedNWRequirement>?

**Comment by LoneGazebo** [comment]
Well the trait has to be seeded in the DLL, otherwise I won't know what it is. You don't have any custom variables in the 'traits' column(s)?

**Comment by pineappledan** [comment]
None. The UA works off a lua that checks if the civ is in the game and applies a dummy policy.

**Comment by LoneGazebo** [comment]
ah, ok, so what's the dummy policy? :)

**Comment by LoneGazebo** [comment]
does it have a unique column value I can borrow?

**Comment by LoneGazebo** [comment]
I just need something that is already rooted in the DLL to grab onto

**Comment by pineappledan** [comment]
The dummy policy only has CSResourcesCountForMonopolies = 1 and IsDummy = 1.
It basically confers the Statecraft trade Confederacy monopoly bonus at the beginning of the game. I don't think that's what you're looking for though.
I haven't created any unique columns because there hasn't been any need for them up until now. the lua mostly just uses GetCivilizationtype()

**Comment by LoneGazebo** [comment]
hmmm

**Comment by LoneGazebo** [comment]
sounds like a trait value is necessary, then.

**Comment by pineappledan** [comment]
Sounds like the easiest thing to do is add a column that confers the OCC NW reduction to a civ if set to 'true'

**Comment by LoneGazebo** [comment]
i'll just do it as an integer for flexibility.

**Comment by pineappledan** [comment]
So -100 equals ignore, and -67 is OCC levels, default is 0?
Or would it be 0 is ignore and 33 is OCC, default is 100?

**Comment by LoneGazebo** [comment]
0 = ignore, 25 = 25% of real, 50= 50% of real, etc.

**Comment by LoneGazebo** [comment]
so 0 and 100 would be the same thing.

**Comment by LoneGazebo** [comment]
it'll default to zero

**Comment by pineappledan** [comment]
Sounds good. So you could still set 200 if you wanted to give a civ a malus for extra pop requirement that way.

**Comment by LoneGazebo** [comment]
yeah

**Comment by HungryForFood** [comment]
How about a lua method/hook ForceCanBuild or similar? Currently the hook lua CanBuild allows you to block something which otherwise can be built. Being able to ignore the game's CanBuild check would work for this, be useful for other scenarios, and not take a memory value.

**Comment by LoneGazebo** [comment]
@pineappledan  It's actually going to be negative:

```
int iScaler = (getNumCities() * pkBuildingInfo->GetNumCityCostMod());
				iScaler += GetPlayerTraits()->GetNationalPopReqModifier();
				iNationalPop *= (100 + iScaler);
				iNationalPop /= 100;
```

So if you want a 66% reduction, you'll need to make it -66.

**Comment by LoneGazebo** [comment]
Trait column is 'NationalPopReqModifier'

**Comment by Omen-of-Peace** [comment]
Not sure I understand: reducing by x% should be a multiplication by (1-x/100), or (100-x) here since we deal with integers only.
Here when iModifier < 100 we're increasing iNationalPop.

Another possibility is division by 100+iModifier since I believe Civ 5 uses this (odd) definition of "reduce by" in quite a few places?
