### ISSUE TITLE
Barbarians stealing food can delevel a city

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#630]
Furthermore, the city's food then can go into negative values:
![8930_screenshots_2015-09-16_00005](https://cloud.githubusercontent.com/assets/12978597/9914373/4ee35fde-5cba-11e5-9983-e892cf43452e.jpg)
It sure isn't intentional, is it? Those barbarians deleveled my capital three times in the span of less than 20 turns (playing with raging barbarians).

**Comment by LoneGazebo** [comment]
It's intentional, in that I didn't code against it - they're stealing food so that you are starving to death. This seems valid, no?

**Comment by Radost** [comment]
I think you shouldn't.
He plays with raging barbarians on and has only one warrior and scout? He deserves the population loss.

**Comment by Edaka** [comment]
Well, out of all the other barbarian stealing actions this one seems unreasonably harsh. With culture, gold, science and production (although I rarely see this one) at most you will lose 2-3 turns worth of these yields. Deleveling a city, though, is much more crippling. 

Firstly, it doesn't even matter how much population it has and the city's food drops down to zero. It can be downgrade from 2 to 1 population, or from 6 to 5. The latter is way over 2-3 turns worh of growth, obviously.

Secondly, the amount of stolen food is considerably higher than for other yields since, I assume, the formula uses food, not growth. Because of this, you can lose 40 food while sitting on 6 growth (again, the ratio is much higher than for any other yield). 

Thirldly, If you're on bad terms with RNG and barbarians repeatedly steal food from one city, you can lose 2/3/etc. population in just the same amount of turns. Once again I'll say that 1 population is significantly more valuable than something like 12 culture. I don't think that anything that is defined solely by dumb luck should have such an impact on the gameplay.

I mean, I know I should've been punished. Yes, I deserved n turns of tech/policy/production delay or an empty treasury, but losing 4 population in my capital by turn 50 (yes, RNG hates me)?

**Comment by LoneGazebo** [comment]
I think it's fair to have it drop to zero, instead of going negative.

**Comment by Edaka** [comment]
At least in case of production loss you don't loose buildings that you've already built. That would be extreme, wouldn't it?
