### ISSUE TITLE
Building_ResourcePlotsToPlace broken

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6303]
2-18-3b:
I used Building_ResourcePlotsToPlace function but resources added cannot be connected via improvements: 
![obraz](https://user-images.githubusercontent.com/33016300/75610761-5d3d6680-5b14-11ea-8ec2-8672eac49cec.png)

Checked with More Wonders for VP mod and bunch of UI ones.

**Comment by LoneGazebo** [comment]
It can, but EUI won't register it because those files are created at runtime based on map generation.

**Comment by adaneslavo** [comment]
But people also mentioned that other nations suggested them resources they should have (in this example salt).

```On the other hand, I noticed one thing, I built Wieliczka, obtained the two salts on the ground and built mines. But I don't seem to have the resource, my cities ask for a WLTKD and another civilization offers it to me in exchange (excuse me but the economic overview bug in the non EUI version and I cannot see if the resource is part of those in my possession).```

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo ^

**Comment by gwennog** [comment]
Hello, sorry it's my first post in Github.

Play with VP2.18 **without EUI** and More wonders for VP.

I confirm the bug reported by Adan_eslavo.
The resources appear well but are not available (neither exchange, nor WLTKD).
I can't check the presence or not in other ways because I also have a bug in the economic overview.

**Comment by HungryForFood** [comment]
Is this an EUI issue? Adding resources to tiles via Lua works correctly, so I'm inclined to say no.

I can investigate when I have time.

**Comment by adaneslavo** [comment]
@gwennog plays without EUI and has that issue. Resource placement works well. I also check that ingame more deeply.

**Comment by adaneslavo** [comment]
Checked by myself and confirmed bug:
Before Salt:
![obraz](https://user-images.githubusercontent.com/33016300/75878752-5d8e7800-5e1a-11ea-859f-ad91cc7cc106.png)
After Salt:
![obraz](https://user-images.githubusercontent.com/33016300/75878814-79921980-5e1a-11ea-94c7-8c74ddfc3655.png)
After improving both:
![obraz](https://user-images.githubusercontent.com/33016300/75878851-91699d80-5e1a-11ea-8d71-5ed66e6c6827.png)
![obraz](https://user-images.githubusercontent.com/33016300/75878868-9cbcc900-5e1a-11ea-971c-d413833b6f69.png)
![obraz](https://user-images.githubusercontent.com/33016300/75878894-a5150400-5e1a-11ea-921f-56db554e4b5d.png)
![obraz](https://user-images.githubusercontent.com/33016300/75878910-acd4a880-5e1a-11ea-8a59-962e73192807.png)
![obraz](https://user-images.githubusercontent.com/33016300/75878935-b5c57a00-5e1a-11ea-8545-1e313313ce56.png)

Doesn't connected with my network.

**Comment by HungryForFood** [comment]
From CoreTableAdditions.xml, where Building_ResourcePlotsToPlace is defined:

```
	<!-- BUILDING: Grants a free Resource in your territory and will try to place it on X number of plots. Entry 'ResourceQuantityToPlace' in Buildings must be set to a value of the quantity you desire that will be placed on X plot -->
	<Table name="Building_ResourcePlotsToPlace">
		<Column name="BuildingType" type="text" reference="Buildings(Type)"/>
		<Column name="ResourceType" type="text" reference="Resources(Type)"/>
		<Column name="NumPlots" type="integer" default="0"/>
	</Table>
```

You need to set 1 in the ResourceQuantityToPlace column in Buildings. I checked the code, and this should work.

To be fair, this is a confusing way to implement this table. Perhaps I should move the ResourceQuantityToPlace column to Building_ResourcePlotsToPlace instead, which additionally allows more customisation potential.

**Comment by adaneslavo** [comment]
Ahh, that is quite tricky. So should I wait for your changes or temporarily adapt this table value?

**Comment by HungryForFood** [comment]
I think use the ResourceQuantityToPlace column in Buildings for now. If I do remove it from the DLL, I'll still leave it inside the database for mod compatibility.

And if I do move ResourceQuantityToPlace to Building_ResourcePlotsToPlace, I'll make it default to 1, so you won't need edit your code.

**Comment by adaneslavo** [comment]
Good. Thanks.
