### ISSUE TITLE
2/18 Visual Issues Air Sweep Action

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6306]
_1. Mod version (i.e Date - 2/9): 2/18

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**For air sweep shouldn't be displayed combat panel**
![2](https://user-images.githubusercontent.com/49090452/75622596-dab3b600-5baa-11ea-9da8-0b30e29fd03e.png)

**Most of the time (sometimes works correctly) when I do Air Sweep the red arch remains there, disappears when I click on any air unit otherwise the arch stays there**
![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/75622602-ec955900-5baa-11ea-825e-00c7c239a13e.png)

**Comment by LoneGazebo** [comment]
yeah it's a consequence of adding the range indicator for the air sweep. Can't fix unfortunately.

**Comment by Aqinu** [comment]
@LoneGazebo 

I understand but I saw that it is possible to have the border limit for air sweep range (which it is useful) but without the red arch (nice, but not that necessary), and in this way there's not any visual issue, what do you think, remains the way it is with this issue or you remove it (just the arch, keep the range limit). Something like this was made before but it's not fully compatible but works the way I described it in vanilla, without the need for the red arch.

 [https://steamcommunity.com/sharedfiles/filedetails/?id=288579237](here)

**Comment by LoneGazebo** [comment]
I find the red arch useful, tbh.
