### ISSUE TITLE
more statistics

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6308]
some numbers on what the AI units are doing all the time. a unit can have either a tactical move (T_) or a barbarian move (B_) or a homeland move (H_).

obviously some are almost never used and candidates for removal.

Name | Count@T465
-- | --
T_UNASSIGNED | 1139
T_GUARD | 20669
T_GARRISON | 1875
T_OPERATION | 19105
T_PILLAGE | 296
T_PLUNDER | 5
T_GOODY | 378
T_HEAL | 3718
T_SAFETY | 971
T_REPOSITION | 4382
T_ESCORT | 33
T_AIRSWEEP | 56
T_AIRPATROL | 156
T_HEDGEHOG | 472
T_COUNTERATTACK | 1884
T_WITHDRAW | 465
T_CLOSE_ON_TARGET | 3244
T_ATTRITION | 311
T_SURGICAL_STRIKE | 41
T_STEAMROLL | 2302
T_FLANKATTACK | 699
T_AIRLIFT | 1
T_BLOCKADE | 384
T_CAPTURE | 2
B_CAMP_DEFENSE | 1959
B_CIVILIAN_ATTACK | 0
B_AGGRESSIVE_MOVE | 913
B_PASSIVE_MOVE | 3
B_HUNT | 252
H_MOVE_UNASSIGNED | 16894
H_MOVE_EXPLORE | 2098
H_MOVE_EXPLORE_SEA | 2824
H_MOVE_SETTLE | 4
H_MOVE_GARRISON | 18025
H_MOVE_HEAL | 511
H_MOVE_TO_SAFETY | 610
H_MOVE_MOBILE_RESERVE | 0
H_MOVE_SENTRY | 2237
H_MOVE_SENTRY_NAVAL | 19311
H_MOVE_WORKER | 16033
H_MOVE_WORKER_SEA | 224
H_MOVE_PATROL | 14445
H_MOVE_UPGRADE | 1309
H_MOVE_ANCIENT_RUINS | 0
H_MOVE_WRITER | 5
H_MOVE_ARTIST_GOLDEN_AGE | 4
H_MOVE_MUSICIAN | 492
H_MOVE_SCIENTIST_FREE_TECH | 50
H_MOVE_MERCHANT_TRADE | 47
H_MOVE_ENGINEER_HURRY | 149
H_MOVE_GENERAL | 1136
H_MOVE_ADMIRAL | 516
H_MOVE_SPACESHIP_PART | 0
H_MOVE_AIRCRAFT_REBASE | 4774
H_MOVE_TREASURE | 0
H_MOVE_PROPHET_RELIGION | 168
H_MOVE_MISSIONARY | 249
H_MOVE_INQUISITOR | 558
H_MOVE_TRADE_UNIT | 0
H_MOVE_ARCHAEOLOGIST | 1259
H_MOVE_ADD_SPACESHIP_PART | 0
H_MOVE_AIRLIFT | 0
H_MOVE_DIPLOMAT_EMBASSY | 172
H_MOVE_MESSENGER | 1035
H_MOVE_SECONDARY_SETTLER | 0
H_MOVE_SECONDARY_WORKER | 0

**Comment by LoneGazebo** [comment]
huh. spaceship part never used?

**Comment by ilteroi** [comment]
well, it was 2020 but they weren't so advanced

**Comment by ilteroi** [comment]
another game. 
* again too early for spaceship?
* plundering traderoutes never seems to happen on purpose
* capturing civilians never seems to happen on purpose
* air sweeps and air patrols are done during combat, show up as steamroll/counterattack etc
* writers and artists probably never show up because they are instantly popped, before the statistics are updated
* treasure and secondary worker/settler are not used because no matching units, but mods might have them?

move | count@T415
-- | --
T_UNASSIGNED | 284
T_GUARD | 20846
T_GARRISON | 1578
T_OPERATION | 13735
T_PILLAGE | 93
T_PLUNDER | 0
T_GOODY | 139
T_HEAL | 2039
T_SAFETY | 547
T_REPOSITION | 2874
T_ESCORT | 39
T_AIRSWEEP | 0
T_AIRPATROL | 0
T_HEDGEHOG | 148
T_COUNTERATTACK | 1038
T_WITHDRAW | 264
T_CLOSE_ON_TARGET | 2135
T_ATTRITION | 175
T_SURGICAL_STRIKE | 85
T_STEAMROLL | 873
T_FLANKATTACK | 511
T_AIRLIFT | 0
T_BLOCKADE | 171
T_CAPTURE | 0
B_CAMP_DEFENSE | 1589
B_CIVILIAN_ATTACK | 0
B_AGGRESSIVE_MOVE | 924
B_PASSIVE_MOVE | 5
B_HUNT | 177
H_MOVE_UNASSIGNED | 22570
H_MOVE_EXPLORE | 4330
H_MOVE_EXPLORE_SEA | 3291
H_MOVE_SETTLE | 2
H_MOVE_GARRISON | 20415
H_MOVE_HEAL | 267
H_MOVE_TO_SAFETY | 220
H_MOVE_SENTRY | 992
H_MOVE_SENTRY_NAVAL | 33010
H_MOVE_WORKER | 13689
H_MOVE_WORKER_SEA | 146
H_MOVE_PATROL | 10987
H_MOVE_UPGRADE | 1287
H_MOVE_ANCIENT_RUINS | 7
H_MOVE_WRITER | 0
H_MOVE_ARTIST_GOLDEN_AGE | 0
H_MOVE_MUSICIAN | 16
H_MOVE_SCIENTIST_FREE_TECH | 50
H_MOVE_MERCHANT_TRADE | 43
H_MOVE_ENGINEER_HURRY | 106
H_MOVE_GENERAL | 1809
H_MOVE_ADMIRAL | 682
H_MOVE_SPACESHIP_PART | 0
H_MOVE_AIRCRAFT_REBASE | 241
H_MOVE_TREASURE | 0
H_MOVE_PROPHET_RELIGION | 106
H_MOVE_MISSIONARY | 415
H_MOVE_INQUISITOR | 1156
H_MOVE_TRADE_UNIT | 495
H_MOVE_ARCHAEOLOGIST | 885
H_MOVE_ADD_SPACESHIP_PART | 0
H_MOVE_DIPLOMAT_EMBASSY | 151
H_MOVE_MESSENGER | 1331
H_MOVE_SECONDARY_SETTLER | 0
H_MOVE_SECONDARY_WORKER | 0

**Comment by JamesNinelives** [comment]
> * plundering traderoutes never seems to happen on purpose
> 
> * capturing civilians never seems to happen on purpose

Something I noticed is that plundering trade routes seem to incur a 'you have captured or killed cilivian units' penalty. So these may both have the same cause (wanting to avoid the diplo penalty)?

**Comment by HeathcliffWarriors** [comment]
@JamesNinelives Not the case; I added that. Seemed unfitting that you would be penalized for killing a civ's workers but not their merchants.

@ilteroi "Treasure" might refer to the treasure units from the "new world" scenario, which need to be escorted back to the capital like spaceship parts.
