### ISSUE TITLE
Unit gets teleported back to City when AI border expands

### ISSUE THREAD

**Issue by JohannesGaessler** [LoneGazebo/Community-Patch-DLL#6309]
_1. Mod version (i.e Date - 2/9):_
2020/03/01

_2. Mod list (if using Vox Populi only, leave blank):_
- Wonder Race
- Really Advanced Setup
- I'm playing on Linux via WINE
- I installed two mods that modify production for Epic/Marathon game speeds (_Marathon (Standard Production)_, _Faster Building - Epic_,  I was playing with Standard game speed though).

_3. Error description:_ 
My own Unit is stationed on the AI border at the end of my turn.
On the AI turn their border expands and my own Unit gets teleported back to my own City (~20 Tiles away) instead of being displaced by just one Tile.
I'm assuming this is a bug.

Files:
[debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4272616/debug.zip)

**Comment by JohannesGaessler** [comment]
My Units also get teleported when I make peace with an AI while they are still in enemy territory.

Files:
[debug2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4274402/debug2.zip)

**Comment by JohannesGaessler** [comment]
Just to be sure, I confirmed that this presumed bug also occurs on Windows 10.

**Comment by ilteroi** [comment]
i know what's up
