### ISSUE TITLE
Game hangs forever at turn 40-70 [linux/wine]

### ISSUE THREAD

**Issue by rahenry** [LoneGazebo/Community-Patch-DLL#6311]
I'm playing on wine/linux so this might be difficult to fix or reproduce, but I figure I should still report it.

_1. Mod version (i.e Date - 2/9):_
3-1, similar issue with previous version

_2. Mod list (if using Vox Populi only, leave blank):_
Really Advanced Setup

_3. Error description:_ 
Game hangs forever during the enemy turn. Usually occurs around turn 40-60. Background/cursor are still animated and the camera can be moved. Happened the last three games I've tried. Continues to occur if game is reloaded (i.e. no way to continue)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[achievements_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273219/achievements_debug.log)
[APP.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273220/APP.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273221/Database.log)
[init_host.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273222/init_host.log)
[Localization.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273223/Localization.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273224/Lua.log)
[modding.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273225/modding.log)
[net_message_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273226/net_message_debug.log)
[stopwatch.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273227/stopwatch.log)
[system_init.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273228/system_init.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273229/xml.log)
[xml-perf.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4273230/xml-perf.log)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by JohannesGaessler** [comment]
Check if a _CvMiniDump.dmp_ file was generated.
In my experience a situation that crashes the game on Windows results in the game freezing on Linux with a _CvMiniDump.dmp_ file still being generated.

**Comment by rahenry** [comment]
Hey, yes it did generate one.
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4274834/CvMiniDump.zip)

**Comment by LoneGazebo** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/6313

**Comment by LoneGazebo** [comment]
Try the CP I posted here

**Comment by rahenry** [comment]
Thanks Gazebo I will try it out today.
