### ISSUE TITLE
CTD ~T100 V3-1 2020

### ISSUE THREAD

**Issue by anders4** [LoneGazebo/Community-Patch-DLL#6313]
_1. Mod version (i.e Date - 2/9):_
3.1 2020

_2. Mod list (if using Vox Populi only, leave blank):_
Really advanced setup.
(I have 3rd-4th component and change vp options but they havent been activated in this or other games for quite some time)

_3. Error description:_ 
Crash on end turn.

_4. Steps to reproduce (optional):_
Load save, end turn.

---------------------------
Supporting information:

I have tried dx9 and strategic view to no avail.
All files in the same zip.
I could try to clean up and reinstall civ5 but why then does 2.9.4b work like a charm?

[darius.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4275466/darius.zip)

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by JamesNinelives** [comment]
Thanks for opening an issue anders4!

1. Mod version (i.e Date - 2/9):
3/1b 

I ran a bunch of games, couldn't even get to turn 0 on the first two. Crash to desktop similar to what I experienced on 2/18/3b. I've collected some of the saves and logs. Still no minidump files from any of them unfortunately.

[Report D.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4275604/Report.D.zip)

Modlist:
Community Events (v. 5)
Civ Names by Policies (v. 8)
Global Relations (v. 7)
Historical Religions (BNW or GK) (v. 55)
Krazjen's Great Musicians Pack (v. 1)
Quick Turns
Really Advanced Setup
Unique Cultural Influence

**Comment by lbrett3** [comment]
Got a crash on the new beta as well, same sort of thing as others have been reporting; seemed to be the exact same thing as was happening with the previous version. 

[crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4277260/crash.zip)

(I also had Global Relations (v. 7) and Historical Religions (BNW or GK) (v. 55) running this time in addition to the VP mods)

**Comment by lbrett3** [comment]
I just changed CORE_DISABLE_LUA_HOOKS to 1 as suggested elsewhere and tried reloading that save, still crashed.

**Comment by ilteroi** [comment]
my civfanatics account doesn't work anymore, but can somebody create a survey?

- how many people experience crashes (never, randomly, reproducable)
- additional mods in use?
- game settings (graphic detail, dx9/11, detail level, movement animations on/off)
- etc

i fear otherwise we'll have a hard time isolating the root cause here.

@g: can you maybe make a release with the latest gamecore but the "old" (pre-crash) lua?

**Comment by anders4** [comment]
Looks like the game gets to player 6 before it crashes.
Tried with opt out of beta (to remove commersial) but same error.

**Comment by anders4** [comment]
Have removed all mods, cleared cache and added VP+ras again, same crash on player6.

**Comment by anders4** [comment]
Full uninstall of civ 5 (including the steam apps folder) and reinstall+mods, same crash player6.

**Comment by LoneGazebo** [comment]
[(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4278473/1.Community.Patch.zip)

Try this CP. It is not savegame compatible, but I'll be curious to see how far you can get on it before it crashes, if at all.

**Comment by anders4** [comment]
> 
> 
> [(1) Community Patch.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4278473/1.Community.Patch.zip)
> 
> Try this CP. It is not savegame compatible, but I'll be curious to see how far you can get on it before it crashes, if at all.

No crash turn 170. seems fine.
Whats changed?

**Comment by ilteroi** [comment]
reverted most of the changes since 2-9 ... but still no idea about the root cause of the crash. might need some additional iterations with different builds to narrow it down

**Comment by LoneGazebo** [comment]
@ilteroi why not do one with just homelandAI, and one with just tacticalAI? 50/50 split.

**Comment by ilteroi** [comment]
ok next round.

here are two builds with other parts reverted. try the release build first, if that crashes please try the debug build. note that release saves typically cannot be used in a debug build (different issue).

[CvGameCore_Expansion2-debug-old-homeland.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4283781/CvGameCore_Expansion2-debug-old-homeland.zip)
[CvGameCore_Expansion2-release-old-homeland.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4283782/CvGameCore_Expansion2-release-old-homeland.zip)

crashes gone? crashes still present? waiting for feedback ...

**Comment by JamesNinelives** [comment]
The release version works! Played up to turn 187, no issues excepting some odd trade valuations for strategics.

**Comment by ilteroi** [comment]
ok that sounds great, finally making some progress. i may have one or two other builds to test soon but this one should be quite playable already.

**Comment by ilteroi** [comment]
here's the next build for testing ... only about changed 300 lines between this one and the crashing version.

[CvGameCore_Expansion2-release-8ca2af0e.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4289874/CvGameCore_Expansion2-release-8ca2af0e.zip)

does it work?

**Comment by Udutont** [comment]
I am the guy who reported: CTD, turn 50 #6317. Tried it for 100 turns. No crash so far.

**Comment by anders4** [comment]
> 
> 
> here's the next build for testing ... only about changed 300 lines between this one and the crashing version.
> 
> [CvGameCore_Expansion2-release-8ca2af0e.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4289874/CvGameCore_Expansion2-release-8ca2af0e.zip)
> 
> does it work?

No crash 220 turns, seems fine.

**Comment by ilteroi** [comment]
excellent. how about this one then?

[CvGameCore_Expansion2-release-e50f0eb8.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4291613/CvGameCore_Expansion2-release-e50f0eb8.zip)

@g: functionally, this has everything ... only the unit selection and management is different. current head of ole branch.

**Comment by Udutont** [comment]
Tried the new version for 40 turns then found a way to crash it. It crashes to the desktop if you click on the icon of your own nation in the upper right corner of the screen (this is supposed to bring up the  screen with you advisors). The previous dll version did not have the issue. Note that the game appears to  be stable otherwise. I will keep playing when able and report again later. 

P.S. Attached zip with the savegame. Note that I am playing with the following mods: Commander Influence borders v1, Remove ghost routes v2, really adavanced setup v15

[MayaCrash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4292489/MayaCrash.zip)

**Comment by Udutont** [comment]
LOL, I should have played on:, CTD at the end of the same turn (turn 40). It may or may not have relevance that  I finished Henge on the turn and established belief.

**Comment by ilteroi** [comment]
please test without any extra mods ...

**Comment by anders4** [comment]
> 
> 
> excellent. how about this one then?
> 
> [CvGameCore_Expansion2-release-e50f0eb8.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4291613/CvGameCore_Expansion2-release-e50f0eb8.zip)
> 
> @g: functionally, this has everything ... only the unit selection and management is different. current head of ole branch.

190 turns no crash, feels solid.

**Comment by Udutont** [comment]
Ok.  Just FYI: I have used the mods since forever and they have never resulted in CTDs with Vox Populi before. Also, I reloaded an earlier save (prior turn 40) out of curiosity and I was able to somehow avoid the CTD.  However, the game still CTD if I try to bring up the advisors screen. Finally, I noticed that AI does not value horses  at all in deals (meaning they offer zero gold for horses). Perhaps this is a feature: it has been a while since I played Vox Populi (horses used to be good early trade items in previous iterations)

**Comment by LoneGazebo** [comment]
@ilteroi what's the diagnosis on the ultimate caused of the CTDs? Any ideas?

**Comment by LoneGazebo** [comment]
@ilteroi latest is working fine for me,  but AI is quite passive - operations firing correctly?

**Comment by Udutont** [comment]
140 turns, seems to work fine.

**Comment by BiteInTheMark** [comment]
> 
> 
> here's the next build for testing ... only about changed 300 lines between this one and the crashing version.
> 
> [CvGameCore_Expansion2-release-8ca2af0e.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4289874/CvGameCore_Expansion2-release-8ca2af0e.zip)
> 
> does it work?

This version looks fine. No crash.

**Comment by ilteroi** [comment]
no idea what the root cause was. little desire to investigate further.

**Comment by rikonen** [comment]
@ilteroi not sure if this was the same crash but I encountered the following:

```
void CvHomelandAI::ReviewUnassignedUnits()
...
	for(list<int>::iterator it = m_CurrentTurnUnits.begin(); it != m_CurrentTurnUnits.end(); ++it)
	{
		CvUnit* pUnit = m_pPlayer->getUnit(*it);
```
^ crash, read of address 8. iterator ptr is NULL. I reckon calling `UnitProcessed` from that loop invalidates the iterator. Changing that to

```
	list<int> currentTurnUnits(m_CurrentTurnUnits);
	for(list<int>::iterator it = currentTurnUnits.begin(); it != currentTurnUnits.end(); ++it)
	{
		CvUnit* pUnit = m_pPlayer->getUnit(*it);
```

fixed the crash for me. Call stack and variable states below in case those are still relevant.

```
>	CvGameCore_Expansion2.dll!CvHomelandAI::ReviewUnassignedUnits()  Line 2245 + 0x8 bytes	C++
 	CvGameCore_Expansion2.dll!CvHomelandAI::AssignHomelandMoves()  Line 584	C++
 	CvGameCore_Expansion2.dll!CvHomelandAI::Update()  Line 207	C++
 	CvGameCore_Expansion2.dll!CvPlayerAI::AI_unitUpdate()  Line 307	C++
 	CvGameCore_Expansion2.dll!CvGame::updateMoves()  Line 9165	C++
 	CvGameCore_Expansion2.dll!CvGame::update()  Line 1708	C++
 	CvGameCore_Expansion2.dll!CvDllGame::Update()  Line 486	C++
```

```
-		it	{...}	std::list<int,std::allocator<int> >::_Iterator<0>
-		std::list<int,std::allocator<int> >::_Const_iterator<0>	{_Ptr=0x00000000 }	std::list<int,std::allocator<int> >::_Const_iterator<0>
+		std::_Bidit<int,int,int const *,int const &>	{...}	std::_Bidit<int,int,int const *,int const &>
-		_Ptr	0x00000000 {_Next=??? _Prev=??? _Myval=??? }	std::_List_nod<int,std::allocator<int> >::_Node *
		_Next	CXX0030: Error: expression cannot be evaluated	
		_Prev	CXX0030: Error: expression cannot be evaluated	
		_Myval	CXX0030: Error: expression cannot be evaluated	
-		m_CurrentTurnUnits	[15](3146,2825,3039,2672,2735,2711,2673,2675,2677,2719,2688,2638,2143,2167,1821)	std::list<int,std::allocator<int> >
		[0]	3146	int
		[1]	2825	int
		[2]	3039	int
		[3]	2672	int
		[4]	2735	int
		[5]	2711	int
		[6]	2673	int
		[7]	2675	int
		[8]	2677	int
		[9]	2719	int
		[10]	2688	int
		[11]	2638	int
		[12]	2143	int
		[13]	2167	int
		[14]	1821	int
-		m_pPlayer	0x3ca7a3e4	CvPlayer *
```

**Comment by ASCII-Guy** [comment]
@LoneGazebo

**Comment by ilteroi** [comment]
you are right, that is dangerous code ...

**Comment by rikonen** [comment]
> although for a std::list<> it should not be critical

I'm pretty sure it's critical because a) it crashed for me there with 100% reproducibility and b) the following simple app shows the same behavior (using GNU STL because I'm not at Windows now):

```
#include <iostream>
#include <list>

int main()
{
  int ints[]= {1, 2, 3, 4};
  std::list<int> mylist(ints, ints + 4);

  for (std::list<int>::iterator it = mylist.begin(); it != mylist.end(); ++it)
  {
    std::cout << *it << '\n';
    mylist.remove(*it);
  }
  std::cout << '\n';

  return 0;
}
```

```
rikonen:~/git/scratch$ g++ test.cpp 
rikonen:~/git/scratch$ ./a.out 
1
Segmentation fault (core dumped)
```

**Comment by ilteroi** [comment]
obviously you're right, but still i wonder why it only crashes for some people.

**Comment by Udutont** [comment]
FYI: I played the game I reported previously to the conclusion (300+ turns), no issues. However, I fired up a few other games and got a CTD on end turn in one of them. This happened on the very first turn. I could not reproduce the crash after reloading the initial autosave despite trying to follow exactly the same moves as best as I could remember.  Plase let me know if you need the save game and dump file anyway.
