### ISSUE TITLE
3/1 (Tactical AI) - Units not garrisoning a defending city

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6316]
_1. Mod version (i.e Date - 2/9):_
3/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The AI has spearmen just sitting behind the city. As a garrison they would at least give me strong opposition (and the +25% ranged boost from Tradition). But as of now this is easy pickings. Screenshot and saved game below.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/75803384-f1414500-5d43-11ea-93a9-94b4d59019f0.png)

---------------------------
[AI not garrisoning.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4282769/AI.not.garrisoning.zip)

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I know why.

**Comment by ilteroi** [comment]
enlighten us :)

**Comment by LoneGazebo** [comment]
@ilteroi look in the PlotGarrisonMoves function in the tactical AI there are two pTarget reassignments in the function so every other city is being skipped.

**Comment by LoneGazebo** [comment]
line 2060 if looking for it, @ilteroi - we define pTarget = GetNextZoneTarget();, then do it again at the bottom, effectively skipping a pTarget every loop.

**Comment by ilteroi** [comment]
yeah yeah it's fixed

**Comment by LoneGazebo** [comment]
it's my fault, I added that code.
