### ISSUE TITLE
CTD, turn 50

### ISSUE THREAD

**Issue by Udutont** [LoneGazebo/Community-Patch-DLL#6317]
_1. 3-1b

_2. Commander Influence borders v1, Remove ghost routes v2, really adavanced setup v15 

_3. CTD on turn 50

[SiamCrash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4282971/SiamCrash.zip)

**Comment by Udutont** [comment]
the second mod is "Remove ghost routes"

**Comment by Udutont** [comment]
The crash occured in my first 3-1b game. After the crash I launched another game (same mods) and it also CTDs (around turn 100).

**Comment by LoneGazebo** [comment]
Try the CP I posted here https://github.com/LoneGazebo/Community-Patch-DLL/issues/6313

**Comment by LoneGazebo** [comment]
Not save game compatible unfortunately.

**Comment by Udutont** [comment]
Ok, thx for quick response! Seems to work fine: 200 turns, no CTD.
