### ISSUE TITLE
God of Commerce not counting Active Trade Routes

### ISSUE THREAD

**Issue by Adonis-VII** [LoneGazebo/Community-Patch-DLL#6318]
_1. Mod version (i.e Date - 2/9): 3-1 (Main Page)

_2. Mod list (if using Vox Populi only, leave blank): MP Modpack, Historical Religions Edit (adds more Icons)

_3. Error description: The Patch notes and ingame description state:
            God of Commerce - +2 faith/gold in connected cities; Capital/Holy city gains +2 great merchant points, +2 gold/faith per active trade route

In game active trade routes do not give a bonus. Settling the first city (without a road or trade route connection) does give the City Connection bonus in the Capital.

_4. Steps to reproduce (optional): Found a pantheon with God of Commerce and create 2+ trade routes.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by randomnublet** [comment]
In my Venice game, I got the +2GMP and +2faith/gold in capital thanks to city connection (actually there was no road, but I founded a second city already and after that the capital counts as connected, old glitch) but not even the first trade route (I tried sending to AI/CS) gave any faith/gold reward.

**Comment by Adonis-VII** [comment]
Random is correct. I settled with the Great Merchant around the time I sent my first caravan. I went back to an earlier save and it was only settling that gave me +2G/+2F. The first trade route didn't give me any bonuses.

**Comment by Adonis-VII** [comment]
@HeathcliffWarriors  Trade routes still give no bonus on 3-15. I still only get a total of 2F 2G even with 2 trade routes.
