### ISSUE TITLE
3/1 - City Attack Damage Inaccurate

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6319]
_1. Mod version (i.e Date - 2/9):_
3/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The swordsman has a higher CS value when attacking the city, and yet is ultimately taking more damage.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/75894413-cadde100-5df9-11ea-8895-c40de5f6212b.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
Same issue #6166 

Short answer: The damage shown is for city only (23), but the damage that the attacking unit is inflicted is split between city(23) and the garrison(another value).
