### ISSUE TITLE
3/1 - Late Game Visual Glitches

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6322]
_1. Mod version (i.e Date - 2/9):_
3/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Into the late game I'm starting to get various visual glitches, such as this bombard arrow that doesn't go away until I've completed other moves. I've also noticed the disappearing yield issue has been much more prominent in this version. Ultimately nothing that is stopping gameplay, just an annoyance.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/75993561-43f33c00-5ebf-11ea-8c60-89dd220b1cf4.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
Same issue  #6306
