### ISSUE TITLE
CTD on Hovering Over Warring City State City Banner

### ISSUE THREAD

**Issue by CommieDog** [LoneGazebo/Community-Patch-DLL#6325]
_1. Mod version (i.e Date - 2/9):_
3/1

_2. Mod list (if using Vox Populi only, leave blank):_
(Community Patch only)

_3. Error description:_ 
The game crashes without fail whenever the mouse cursor crosses over or touches the city banner of a city state that I am at war with. Declaring war on a city state and then immediately making peace works just fine, so I suspect it's a UI issue.

_4. Steps to reproduce (optional):_
Declare war on a city state, then close the city state popup and move the mouse over the city state's city banner.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4299828/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4299831/QuickSave.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4299836/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by ishwaw** [comment]
Has this been fixed in April 7th 2020 patch?

**Comment by CommieDog** [comment]
I just checked, and it has indeed been fixed! I'm not sure what changed, but it's working now.
