### ISSUE TITLE
AI buying useless strategics

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6328]
https://forums.civfanatics.com/threads/new-beta-version-march-1st-3-1.655679/page-10#post-15696648

(The Iroquois bought Iron despite not needing it at all until significantly later; their UU makes it unnecessary.)

**Comment by HeathcliffWarriors** [comment]
It'd be handy if the AI would weigh individual strategic resources by how useful they are, looking at their own needs and resources.
