### ISSUE TITLE
Installer misplacing EUI

### ISSUE THREAD

**Issue by ricanuck** [LoneGazebo/Community-Patch-DLL#6329]
_1. Mod version (i.e Date - 2/9):_

5.3.1b
_2. Mod list (if using Vox Populi only, leave blank):_
GR

_3. Error description:_ 
Installer places EUI in standard location instead of where it should go (Registry shows correct location for Civ 5 folder)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ricanuck** [comment]
I found some old reports about this, but it never happened to me before. OTOH, it's been a long time since I tried VP, but now I returned and found this little error. What changed in the meanwhile is that I migrated from Win7 to Win10 x64, if that is relevant. Any idea?

**Comment by Vyyt02** [comment]
With the current autoinstaller, the only option is to move the EUI from the default location to the correct one manually, I am afraid.
