### ISSUE TITLE
Landsknecht doesn't count towards the purchase limit

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#633]

**Comment by LoneGazebo** [comment]
By design.

**Comment by Radost** [comment]
By design only the "move after purchasing" part should be applied.
Otherwise they can be spammed for easy city-state influence.

**Comment by LoneGazebo** [comment]
That's a nerf to that policy, though, one which I don't think it warrants. If you want to spend your gold on those units to get a minor amount of influence, why not?

**Comment by LoneGazebo** [comment]
Eh, I'll make the change, see how it works for now.

**Comment by Radost** [comment]
It's not only about influence, turns out it's possible to buy foreign legions and airlift them on the same turn. I doubt AI is that smart to abuse it this way.

**Comment by LoneGazebo** [comment]
I'll change it, see if anyone but you and I notice :)
