### ISSUE TITLE
Chop yields upon city settle

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6331]
3-1b

Settling a new city on top of a forest, after having discovered Iron Working (40 production when a worker chops a forest) only net me 20 hammers (same as Bronze Working)

**Comment by randomnublet** [comment]
Update: Settling a new city on top of a forest having discovered Bronze Working only gives me 10 hammers, that's half of the production I get from chopping a forest in the city first ring (I would expect the same production at least, given closer distance)

**Comment by LoneGazebo** [comment]
Settling is always a 'fixed' half of the max because there's no 'work' involved in getting it. It has been that way for a long time.
