### ISSUE TITLE
inquisitor not working at all against Prophecy belief

### ISSUE THREAD

**Issue by kienerj** [LoneGazebo/Community-Patch-DLL#6336]
1. Mod version

2/18

2. Error description

I conquered several cities of a different religion and since missionaries and prophets seem underpowered I wanted to at least remove the current religion with inquisitors.

The current religion had the "belief" (Prophecy) containing the effect 

    If this is the Majority Religion, Follower reduction from Inquisitors and Prophets is halved.

However in these cities inquisitors had 0 effect. No followers of the other religion were removed at all.

**Comment by Mileslewis** [comment]
I did some testing on this, seems like if I kept on using inquisitors then there was some change eventually, but it did seem like the reduction was way more than half.

If, for example, Hindu religion had Prophecy enhancer then this reduction applied to all Hindu followers even if Hindu was not the majority religion of the city but does not apply to any followers of other religions.

Also does not require Hindu to be majority religion in your civ but does require that you own the holy city for Hinduism. Am unsure whether it requires Hindu to be primary religion or not (in my case it was).

**Comment by ilteroi** [comment]
cannot reproduce

**Comment by SuperNoobCamper** [comment]
I sent 5 inquisitors to the Incan holy city after conquering it in the modern era and it neither changed the majority religion -in fact i did not gain a single follower-, nor lost the holy city status.
I had to spam missionaries from my religion with Borobudur and Symbolism to change the holy city majority religion but i cannot remove the holy city status yet.

**Comment by JamesNinelives** [comment]
I have encountering similar issue with inquisitors, but I don't think it has anything to do with the Prophecy Enhanced. Neither of the religions I was trying to remove had that - one had Mendicancy and the other wasn't even enhanced.

**Comment by ilteroi** [comment]
#6337

**Comment by anders4** [comment]
Want to add that this been since feb version and includes usage of great Prophet doing zero.
A couple of regular missionaries does the job.

**Comment by bigcat88** [comment]
Currently I has the same issue with 4-7 version.

**Comment by anders4** [comment]
As mentioned in #6337, it works when you have a majority religion, with no majority it doesnt matter if its prophecy enhancer or not, inquisitors just doesn't work.
