### ISSUE TITLE
Inquisitors not having any effect on cities with no majority religion

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6337]
_1. Mod version (3-1b) or (v.94)

_2. 

_3. Inquisitors had no effect on cities without a majority religion (followers stayed exactly the same), didn't matter which religion the inquisitors were from or which religions were present in the city. Didn't matter if my civ had majority religion or not or whether i had a primary religion.

Inquisitors were working as normal in cities with any majority religion.

Also inquisitors do seem to still work on pantheon followers as normal just not followers from any religions in cities without a majority religion.

Perhaps this is intended but seems quite strange and I don't remember seeing it mentioned in the patch notes. Also I'm pretty certain inquisitors were working on non-majority cities a few patches ago.

_4. Steps to reproduce (optional): 
Use an inquisitor in a city which does not have a majority religion. There will be no change except from pantheon followers.

---------------------------
Supporting information:

[Inquisitor issue zip.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4314889/Inquisitor.issue.zip.zip)

In zip folder is photos of before and after using a Buddhist inquisitor in a city without and then with a majority religion. 
A save file of just before using inquisitors.
A copy of the logs file of me using a Buddhist and then Tengri inquisitor on Neapolis while it had no majority religion (no effect). Then I used two missionaries to convert Neapolis to majority Buddhism and then used a Buddhist inquisitor which then worked.

**Comment by ilteroi** [comment]
well that seems to be by design. there is an explicit check if the city has a majority religion before the inquisitor does anything.

so, two options:

* remove that check
* move the check into canRemoveHeresy() so that the action is greyed out

**Comment by LoneGazebo** [comment]
I know why, I'll fix.

**Comment by ilteroi** [comment]
also, different discussion but shouldn't an inquisitor also have a downside? right now they are so much more powerful than missionaries. how about losing some population? after all, people are burning at the stake!

**Comment by ilteroi** [comment]
ha. synchronous update ... reopen

**Comment by LoneGazebo** [comment]
@ilteroi probably, but that's a balance concern. You don't 'gain' followers from them, only other religions lose them.

**Comment by ilteroi** [comment]
well, technically, the other religions lose their built-up pressure. this causes the inquisitor's religion to gain followers. otherwise the majority would never change after using an inquisitor.

**Comment by LoneGazebo** [comment]
I thought other religions just lost followers, not pressure?

**Comment by ilteroi** [comment]
followers are just the result of distributing the population according to pressure

**Comment by HeathcliffWarriors** [comment]
Religious pressure can get pretty high if many civs spam Missionaries on some targets, City-States are notorious for this but it can happen to major civs too. Without some way to reset high pressure levels the religion game would be unbalanced...I'm not totally opposed to the idea of lost population though, that sounds thematically satisfying haha

**Comment by bigcat88** [comment]
Guys did you change that for AI?
Currently see on github in
https://github.com/LoneGazebo/Community-Patch-DLL/blob/master/CvGameCoreDLL_Expansion2/CvUnit.cpp#L11386
no changes for that.
`if(GetReligionData()->GetReligion() == NO_RELIGION)
	{
		return false;
	}`
