### ISSUE TITLE
Denouncements and embassies

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#634]
Every time I get denounced by other civ, on the next turn it asks for the "embassy-embassy" trade deal.

**Comment by TechpriestEnginseer** [comment]
I believe it's intentional. You can still trade with denounced Civilizations and if they somehow still like you get a good deal from it.

**Comment by LoneGazebo** [comment]
I'll just make it so that if you are denounced by them, or they denounced by you, they won't want to do this.
