### ISSUE TITLE
3/1 - Minor Text Error with Cult of Personality

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6340]
_1. Mod version (i.e Date - 2/9):_
3/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The cult of personality bonus text is written twice.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
hmm having some problems with screenshots. Its in the tourism dropdown, it say "+50% from fighting against a common enemy" twice

**Comment by LoneGazebo** [comment]
technically not a bug, but it is unclear- you get the bonus for each common foe you share, which is why it is adding one per foe. I'll merge the bonuses into a single line.

**Comment by Stalker012345** [comment]
Oh, so you mean if I share two common enemies with a person, I get a +100% bonus?

**Comment by LoneGazebo** [comment]
yes
