### ISSUE TITLE
Fallout after nuclear detonation

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#6341]
_1. Mod version (i.e Date - 2/9):_
3/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
AI workers never remove fallout after nuclear detonation.

_4. Steps to reproduce (optional):_
IGE - nuclear detonation

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Possibly related to your worker changes?

**Comment by bigcat88** [comment]
After Nanotechnology they must clear it.
Before that worker almost die and got sended back to heal, then again was trying to remove and go heal again...

**Comment by ilteroi** [comment]
i just took a look and it seems the "fallout" feature has TurnDamage==15 and ExtraTurnDamage==-10. what's that supposed to mean?

also the worker is weird, it has an "ignoreFeatureDamage" promotion and an "extraFeatureDamage" promotion, resulting in nonsensical danger value of -10 ... ie healing.

what is the expected behavior here?

**Comment by LoneGazebo** [comment]
I think the two tiers are related to the promotion? Not sure. I haven’t messed with that in forever.
