### ISSUE TITLE
humans and minor territory

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6342]
AI combat units are not allowed to end their turn in minor players' territory (unless allied etc).

Human units are allowed, but the consequence are some negative influence points.

Should the human "advantage" be removed? It has side effects like the AI units being teleported away when a city state is liberated, while human units may stay, greater pathfinding freedom for humans etc.

Unfortunately the other solution (allowing AI units into minor territory permanently) will lead to extreme influence loss because the AI is still a little bit stupid. So that would only work with a lot of extra checks in the code or if the influence penalty is removed.

My CivFanatics account is still broken, therefore posting here ...

**Comment by bigcat88** [comment]
That will broke many naval paths...

**Comment by HeathcliffWarriors** [comment]
IMO, teaching the AI to be smarter is superior to denying the human movement rights - plus entering CS borders may be more or less required for exploration, preparing for war against a neighbor to the CS, etc.. It's very useful and I think players would be upset about the change. You're the one who actually does the AI work, though.

**Comment by ilteroi** [comment]
well it used to be the case that AI could not even pass through CS territory (with the known exceptions ...). now they can pass through but may not stay.

so AI restrictions already were loosened, making human rules the same would be meeting in the middle.

**Comment by bigcat88** [comment]
Better decrease penalty(or replace it with something) and allow AI pass CS like humans.

**Comment by HeathcliffWarriors** [comment]
I agree with bigcat - not allowing human players in may be meeting in the middle, but it'd be frustrating for players and not optimal; while I recognize I'm not the one doing the work, I'd support more AI checks/intelligence as the solution.

**Comment by ilteroi** [comment]
easy for you to say ... try my suggestions first, it's implemented but as an option

**Comment by HeathcliffWarriors** [comment]
Is there an exception for civilian units? Diplomats need to enter a CS's territory somehow after all. :)

Also, I've proposed this before - why not have an exception of one scouting unit per player per City-State to the Influence penalty / in this case, entrance rule? That way exploration isn't hindered but you can't just put a bunch of scouts in their lands and blockade their tiles without being at war.

**Comment by bigcat88** [comment]
Idea:
CS influnce penalty for crossing borders applies only if unit end turn in CS terrotiry for more then 1 turn.
Idea2:
Make this as a part of lua, not letting to stay at CS territory for more then 1 turn. Removed penalty for crossing tottaly from game.
Will this help AI or not?

**Comment by ilteroi** [comment]
all these ideas require a lot of bookkeeping ... not terribly attractive.

has anyone tried the current version?

**Comment by HeathcliffWarriors** [comment]
Which build should I use to test out the current version? Ole or master?

**Comment by ilteroi** [comment]
head of ole

**Comment by HeathcliffWarriors** [comment]
@ilteroi Pretty busy ATM, but I'll test it out if I'm able to.

Regarding https://github.com/LoneGazebo/Community-Patch-DLL/commit/d8a7fdf41af05e68b495d88e039e7aef05440a0a, shouldn't the Horde/Rebellion quests (if active for that player) grant access to major civs as well?

**Comment by azum4roll** [comment]
See also #6356

**Comment by ilteroi** [comment]
forget this, AI is now close to human rules so no need for further change
