### ISSUE TITLE
open borders with vassal?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6345]
indonesia is a vassal of the celts, nevertheless the celts have open borders with them:

![image](https://user-images.githubusercontent.com/1358966/76686377-1b83e400-661b-11ea-86e0-1601958ff441.png)

is that intended?

**Comment by ilteroi** [comment]
also, i checked that the open borders flag is set in the debugger, but the UI doesn't show it. on the other hand, that might be a problem of observer mode.

![image](https://user-images.githubusercontent.com/1358966/76686483-078cb200-661c-11ea-8814-fc53bc20b45b.png)

**Comment by HeathcliffWarriors** [comment]
Are you sure they didn't just trade for OB?

**Comment by ilteroi** [comment]
yeah i assume they traded but why would the master want to?

**Comment by HeathcliffWarriors** [comment]
Ah, fair enough
