### ISSUE TITLE
crash in diplo AI

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6348]
offending line:

iAverageOpinionScore /= aOurTeam.size();

for some reason aOurTeam is empty ...

the whole thing is weird anyway, why not use CvTeam::getPlayers()?

**Comment by HeathcliffWarriors** [comment]
@ilteroi Oh, I see what happened. Hold on a minute.

**Comment by HeathcliffWarriors** [comment]
Yeah, I'm scratching my head at why Putmalk wrote it that way. Maybe CvTeam::getPlayers wasn't a thing at the time? I'm not too good with vectors, so I'll just fix the bug so as to avoid causing crashes/etc, but it could definitely be optimized.

**Comment by ilteroi** [comment]
there are more of these ...

iAverageMeanness /= m_MasterTeam.size();

did you fix them as well?

**Comment by HeathcliffWarriors** [comment]
@ilteroi Yes.
