### ISSUE TITLE
IsLostOnMove and Improvements.UnitFreePromotion

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#635]
Unfortunately, whilst Improvements.UnitFreePromotion appears to work perfectly on its own, the functionality of IsLostOnMove appears not to. When this is set to true on a promotion, the promotion simply does not show up.

**Comment by LoneGazebo** [comment]
Code works for me, just tested it. Are you testing it with units that can use/gain the promotion in a valid way? Your promotion should allow the unit combat class to use it (i.e. Scouts can't get Drill I from this, but Warriors could, etc.).

**Comment by JFDaly** [comment]
Yes. It is a promotion where IsLostOnMove is true and it is hooked up via Promotion_UnitCombatTypes to only apply for Mounted Units. 

As you can see in the album below, with IsLostOnMove set to false, everything works as expected (the promotion next to the sun icon is added when the Horseman enters the Tipi improvement). 
http://imgur.com/a/5EQES

But with IsLostOnMove set to true, the promotion is not added whatsoever, as seen here: http://i.imgur.com/07nW3lz.jpg. 

I did try clear my cache, and tested with no other mods running, so I'm at a loss.

**Comment by LoneGazebo** [comment]
Man, I'm at a loss. I've got it working just fine:

moving onto it:
http://imgur.com/oBWBlmG

and off of it:
http://gazebo.imgur.com/all/

**Comment by LoneGazebo** [comment]
What does your improvement/promotion XML look like?

**Comment by JFDaly** [comment]
It's in SQL, so it'll appear a bit messy, but just like this: http://pastebin.com/3gBjqKTq. You can toggle text wrapping at the top, next to the clipboard icon.

**Comment by LoneGazebo** [comment]
I'll give it a go and see what I can figure out. Only thing I can think of is flipping the location of the promotion and the improvement, so that the latter isn't grabbing an invalid XML call. Not sure it matters with SQL creation, though.

Are you seeing any lua or database.xml errors?

**Comment by JFDaly** [comment]
Nope, no database errors and switching the order around didn't change a thing. However, I switched in the March promotion as a test and this worked. So it's something to do with the promotion setup specifically, however, I'm sure sure what, as it is almost functionally identical to promotions that work with IsLostOnMove and Terrain, Feature, etc. Moreoever, it's clear that the promotion is valid for the unit, as it works fine with IsLostOnMove set to false.

**Comment by LoneGazebo** [comment]
Okay, so it worked with March, but not that promotion? Hmm...

Could it be JFD_TribeType causing the issue? When you look at the SQL when loaded in-game does it look right?

**Comment by LoneGazebo** [comment]
You also lack OrderPriority...could that be it?

**Comment by JFDaly** [comment]
JFD_TribeType only concerns the improvement. Hooking the promotion up to the Plantation, for instance, had no effect. Setting OrderPriority to a higher value similarly did nothing. In any case, the issue appears to be on my end, though I'm honestly baffled. I tried making this promotion as one given by terrain/feature, but it still didn't work. Yet, I also tried giving out one of my attrition promotions via improvement, which assuredly work via Feature/Terrain, and that didn't work. So for now I guess there's nothing to be done.

**Comment by LoneGazebo** [comment]
That's really, really odd. It's as if your promotions aren't registering as promotions for some reason.

Try adding the promotions as XML, perhaps? See if there's something going on with the SQL on-generation?

**Comment by LoneGazebo** [comment]
To ease your sanity, the improvement code is identical to the terrain and feature code in terms of design, so if one works on one, it should work on the other.

One thing to consider- are you using the same promotion with 'islostonmove' in two different ways? I wonder if that's causing it, perhaps?

**Comment by LoneGazebo** [comment]
Any updates on this working for you? I'm genuinely curious.

**Comment by JFDaly** [comment]
Well, after much confusion over why it appeared to concern the tag that I was using, it was indeed the use of IsLostOnMove in two different instances - one for the improvement, and one for the feature (which was leftover from earlier tests for the concept). Thanks for the patience. At least the mystery is solved.

**Comment by LoneGazebo** [comment]
Hooray!
