### ISSUE TITLE
3/1 - Symbolism enhancer belief does not let missionaries erode existing pressure

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6352]
_1. Mod version: 3/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  The symbolism enhancer belief bonus does not seem to let missionaries erode 25% of existing pressure when spreading religion. The religious pressure of foreign religions is unchanged after spreading religion. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
By "pressure" do you mean the (+x pressure) number or the follower count?

**Comment by silentreply** [comment]
Ok my mistake then. I didn't have any cities following another religion to confirm if the missionaries were able to remove more followers. I'll assume it's working. Is there any way to see the "built up" pressure in a city?
