### ISSUE TITLE
Barbarians don't attack/take weak cities

### ISSUE THREAD

**Issue by Cat-du-Fromage** [LoneGazebo/Community-Patch-DLL#6358]
_1. Mod version (i.e Date - 2/9):_
Last Version

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Barbarians attack a few time cities but never took it (even when the city has 0 hp) and then suddently stop attacking it
It seems the AI is to careful about the city defense, terrain modifier etc and act like if there was an army ready to strike them if they take to much damage.
it also seems they don't take in consideration there is no garrison in a city.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/46396184/76735613-86d9cd00-6765-11ea-8049-3e5c4b459483.png)
![image](https://user-images.githubusercontent.com/46396184/76750279-42a6f680-677e-11ea-9ee0-440a4e64806a.png)

**Comment by ilteroi** [comment]
barbarians don't capture cities, only plunder. that is by design
