### ISSUE TITLE
WLTKD and population increase notifications don't queue in EUI.

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#636]

**Comment by Edaka** [comment]
You might also add city border growth and building maintenance cost increase (the penalty for an insufficient strategic resource) notifications, but I'm not sure if such UI tweaks are Gazebo's job.

**Comment by LoneGazebo** [comment]
Not really my thing.

**Comment by Radost** [comment]
But monopoly notifications queue just fine, which aren't the part of vanilla game in any way.

**Comment by LoneGazebo** [comment]
It is because of the notification method they use in the DLL. The other elements that you speak of would have to be rewritten within EUI. You should speak to bc1 about this, not me.
