### ISSUE TITLE
Unique Units bug

### ISSUE THREAD

**Issue by favoriety** [LoneGazebo/Community-Patch-DLL#6361]
_1. Mod version (i.e Date - 2/9):_ 3/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
All vanilla Unique units are avalible for each civilization, even scouts are replaced by pathfinder.
_4. Steps to reproduce (optional):_

---------------------------
4. Screenshots (optional):
![JohF59JwpL](https://user-images.githubusercontent.com/42432879/76883181-01950c00-687c-11ea-9f65-5f2e09f15cca.png)
![mWLoJAHwp6](https://user-images.githubusercontent.com/42432879/76883190-05289300-687c-11ea-977f-d393d6f78283.png)

**Comment by Vyyt02** [comment]
What do you mean? The recon unit using the old Shoshone pathfinder graphics is the default starting unit for everyone (it then upgrades to a scout later on). And the ranged horse in the tech screenshot is the Skirmisher unit available to everyone. Are you sure that "all UUs are available to everyone"? The 2 examples you presented are default VP units, not UUs.

**Comment by HeathcliffWarriors** [comment]
VP has players start with a Pathfinder that upgrades to a Scout later. Not a bug.
