### ISSUE TITLE
3/15 Pathfinding Issues

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6362]
_1. Mod version (i.e Date - 2/9) 3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: **See screenshots.**

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Here I don't have open borders with England but the path is made as I do, and I can't move unless I do it manually**
![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/76889989-33639e00-688f-11ea-9abe-fc9554b0329d.png)

**Going in CS territory triggers war unless i select a tile outside and after the CS territory (west to the CS's sheep in this instance)**
![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/76890167-86d5ec00-688f-11ea-8561-ba5bec56e2d3.png)

**Very offen I have to do two commands to move my units in one turn, first I select in this instance a two distance away (2) tile after that the unit moves only one tile (1) and then I have to do it again to move when I wanted(2)**
![Untitled](https://user-images.githubusercontent.com/49090452/76890318-d2889580-688f-11ea-8e0b-8c2b06c4a5a5.png)

**Comment by ilteroi** [comment]
yeah i know. side effect of restoring the "declare war" popups. it's gone already.
