### ISSUE TITLE
3/15 - Trade Issue

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6363]
_1. Mod version (i.e Date - 2/9): 3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

I know that his ability may have an impact over the price but in this instance I still think that is too much **(epic speed)**. First time I made the deal.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![Civ5Screen0002](https://user-images.githubusercontent.com/49090452/76890690-7a9e5e80-6890-11ea-928b-e073d8d62b45.png)

**Here another example early game (epic speed)**
![z](https://user-images.githubusercontent.com/49090452/76891446-ae2db880-6891-11ea-8d72-203de9dc4091.png)

**Comment by HeathcliffWarriors** [comment]
GPT being valued less likely has an impact on this.
