### ISSUE TITLE
3/1 - Cult of Personality Highest Warscore bonus never goes away

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6365]
_1. Mod version (i.e Date - 2/9):_
3/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Could be my misunderstanding with how this policy works. If its meant to give a permanent tourism bonus based on your highest warscore since getting the belief, than no issue. If its supposed to go down after the war ends than there's a bug, as the bonus is staying even once I peaced out.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
The policy gets your overall highest warscore in any war, not just the war with the target civ. So if you're punching a civ at 80 warscore, you get that as a tourism bonus with all civs.

**Comment by Stalker012345** [comment]
Its not that, but what I reported either isn't actually true either, as I have noticed the numbers going down sometimes. I'm going to have to watch this one, the numbers don't look right but I'm not exactly sure what's up.

**Comment by HeathcliffWarriors** [comment]
Maybe it's using the war score while at peace?

**Comment by HeathcliffWarriors** [comment]
It *is*. Well, that's easily resolved.

**Comment by LoneGazebo** [comment]
@HeathcliffWarriors no, it's not using the peacetime calc.

**Comment by HeathcliffWarriors** [comment]
No, but it's doing this, which is why it's gradually decaying as Stalker0 describes.

```
if (bUsePeacetimeCalculation)
 // power estimates code
else
{
	int iTheirWarScore = GetWarDamageValue(ePlayer);
	int iWarScore =GET_PLAYER(ePlayer).GetDiplomacyAI()->GetWarDamageValue(GetPlayer()->GetID());
```
War damage value decays over 10 turns, I think.

**Comment by LoneGazebo** [comment]
Yes but it is still getting the highest war score, period.

**Comment by HeathcliffWarriors** [comment]
Is that intended? Most players don't know that there's a warscore even when not at war, since it's not displayed in the UI, hence the confusion here.

**Comment by HeathcliffWarriors** [comment]
And GetHighestWarscore is only called for the purposes of Cult of Personality.

**Comment by HeathcliffWarriors** [comment]
So IMO, changing it to this wouldn't cause any problems (IsAtWar check added):
```
int CvDiplomacyAI::GetHighestWarscore()
{
	int iHighestWarscore = 0;
	for (int iPlayerLoop = 0; iPlayerLoop < MAX_MAJOR_CIVS; iPlayerLoop++)
	{
		PlayerTypes eLoopPlayer = (PlayerTypes) iPlayerLoop;

		if (IsPlayerValid(eLoopPlayer) && IsAtWar(eLoopPlayer))
		{
			int iWarscore = GetWarScore(eLoopPlayer);
			if (iWarscore > iHighestWarscore)
			{
				iHighestWarscore = iWarscore;
			}
		}
	}

	iHighestWarscore *= GetPlayer()->GetPositiveWarScoreTourismMod();
	iHighestWarscore /= 100;

	return iHighestWarscore;
}
```

**Comment by HeathcliffWarriors** [comment]
I'll just send a PR and you can decide.
