### ISSUE TITLE
City placement and desert river

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6366]
3-15-2b

I know I'm nitpicking but I can't help thinking the AI did a poor job at placing this city

![civchichen](https://user-images.githubusercontent.com/53142313/76933231-f5956280-68ec-11ea-92b8-77c6252f8781.png)

I think it's considering the amber (already worked by the capital) as a good tile to have in range, better than those fish. By placing itself on the floodplains instead of the SE hill, it gave up a possible river/wheat triangle farm.

Anyway, what irks me (knowing I'm going to conquer and raze it :) ) is that once you build a town over floodplains, the feature goes away and once razed it becomes a standard desert tile. I wonder if this could be changed and floodplains don't get removed, afterall the river is still there providing fresh water to the tile.

**Comment by bigcat88** [comment]
But here are one pro:
 - Only one coast tile. Hard to take such city with naval invasion. Good defence position.

**Comment by ilteroi** [comment]
so many factors go into choosing a city site, it's hard to tell what made the difference
