### ISSUE TITLE
AI gpt deals

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6367]
3-15-2b

When asking an AI any deal for gpt ("What will you give me for this?"), they still value 1 gpt = 50 points. 

Examples:

![civgpt1](https://user-images.githubusercontent.com/53142313/76936068-8b7fbc00-68f2-11ea-9726-f65a948b13d6.png)

![civgpt2](https://user-images.githubusercontent.com/53142313/76936077-8fabd980-68f2-11ea-88b4-1da42270e641.png)

Here Washington thinks 4 gpt ~= 200 while for Pacal 3 gpt ~=150 is a fair deal.

I can manually adjust this and they gladly accept the new values

![civgpt3](https://user-images.githubusercontent.com/53142313/76936534-60e23300-68f3-11ea-935e-15a7b0d2e08a.png)

This is not the usual rounding down the short bidding AI always made in regard with trades that already caused players to manually adjust values 1 gpt higher (and that I'd love for you to address as well, it's pretty tedious), the values differ too much.

**Comment by LoneGazebo** [comment]
the difference in value is based on the individual civ's GPT - civs with more money pay more for resources.

**Comment by randomnublet** [comment]
That's not the issue I'm referring to. 

Before the patch, let say an AI valued my luxury 200 points: 1 gpt = 50 points, hence he was going to offer me 4 gpt for the luxury. Now 1 gpt = 38 points, but looks like he didn't receive the meme so he's still offering me 4 gpt, and I have to arrange manually to 6 gpt so that the offer matches the new values. That might be easier to notice with higher value trades but I already see a pattern here.
