### ISSUE TITLE
More about CS territory

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6368]
15-3-2b

If I want to move on that tile to capture the Egyptian missionary I am forced to declare war on Ur. There're no military units on the tile. 

![civcswar](https://user-images.githubusercontent.com/53142313/76950230-0ef8d780-690a-11ea-91d6-41b522ba5d81.png)

**Comment by LoneGazebo** [comment]
@ilteroi, the joy continues...

**Comment by ilteroi** [comment]
that's an old one, isn't it?

**Comment by LoneGazebo** [comment]
Don't think so, no.

**Comment by ilteroi** [comment]
after checking GetDeclareWarMove() i'm pretty sure it is ... also i have no idea how to fix it. there are just too many possible combinations.

**Comment by JamesNinelives** [comment]
I think I remember this happening with embarked units from one civ occupying the same tile as a ship from a different civ (that I'm at war with). Fairly minor from my perspective though, as doesn't happen very often.
