### ISSUE TITLE
3/1 (Tactical AI) - Suicidal Ship Movement

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6369]
_1. Mod version (i.e Date - 2/9):_
3/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm seeing this continuously through my game. The AI will sometimes just send one or two ships near my fleet, they don't do much damage, and I can easily scoop them up.

I've seen it time and time again. Below is one example of an ironclad just moving right next to my fleet for no purpose.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/76978895-444ef680-6905-11ea-928d-b451929fe0bf.png)

[Bad Ship Tactics.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4349869/Bad.Ship.Tactics.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
hmm. old version, i need to watch this and see if i can reproduce it

**Comment by Stalker012345** [comment]
Also seeing it on 3/15. AI continues to send in a 1-2 ships near my cities...which I just clean up with ease. Its not all the time, I am seeing strong fleets as well, but I periodically I just see this idiot ship that wants to die.

**Comment by Stalker012345** [comment]
One more example. Celts sent in 1 ship a few turns ago. Now 2 ships right up to my fleet.

![image](https://user-images.githubusercontent.com/20593976/77217843-9a818c80-6af3-11ea-96ef-30ba22b576b6.png)

**Comment by Stalker012345** [comment]
And a few turns after that.

![image](https://user-images.githubusercontent.com/20593976/77218036-2fd15080-6af5-11ea-8871-452f9dc391df.png)

**Comment by ilteroi** [comment]
might be the usual visibility issue ... they simply don't see/remember all those ships of yours.

**Comment by Stalker012345** [comment]
So this one can't be a visual issue as he would have definately seen this fleet farther out. This John McClane of frigates came in to this fleet by himself, got right up next to my ships, and proceeding to fire. What a brave soul.

![image](https://user-images.githubusercontent.com/20593976/77495850-9d43f080-6e17-11ea-896c-1108b118765d.png)

**Comment by Stalker012345** [comment]
Ignore that one ship in the middle from me, I just moved him.

**Comment by ilteroi** [comment]
hmm still not convinced. the question is where did he start the turn?

unfortunately AI isn't good at changing tack in the middle of the turn ... pun fully intended ... but they do try opportunity attacks if they have moves left at the end of the turn.
