### ISSUE TITLE
suboptimal citizen allocation

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6370]
![image](https://user-images.githubusercontent.com/1358966/76998471-70926380-6955-11ea-99c6-90fbb6d7d185.png)

building a settler, but still ... food focus works the plantations, default focus works the hills.

**Comment by HeathcliffWarriors** [comment]
Doesn't excess Food give a Production bonus for Settlers? In which case the two plantations would be superior to the forest and stone tiles.

**Comment by silentreply** [comment]
I have noticed unusual tile selection and was going to make a post on this soon. I'm pretty sure 2f=1p when building settlers - so two plantations should indeed be superior to two 2f/1p tiles. 
![governor tile selection](https://user-images.githubusercontent.com/59859911/77006022-218a0580-6938-11ea-984c-de4816f3ac50.png)

**Comment by silentreply** [comment]
Here's another example. In the cases I've posted could it be related to god of the sky pantheon? If I lock down the forest plains silk, the city wants to work the 1f/1p plains tile over the wheat, even though there is a feature on the silk tile. Is there code that modifies the governor tile selection based on god of the sky pantheon?
![image](https://user-images.githubusercontent.com/59859911/77109910-22d03680-69fb-11ea-943a-4cbc91bda9f6.png)

**Comment by silentreply** [comment]
That would also explain the first example I posted - where the city wants to work two jungle (plains) tiles even though there is a feature on them.

**Comment by LoneGazebo** [comment]
yes, the governor AI tries to maximize pantheon bonuses

**Comment by silentreply** [comment]
Could the governor AI be coded to recognize when features on tiles will not result in a bonus from god of the sky pantheon?

Here is another example that doesn't involve such pantheon. The citizen allocation is the same on default or production focus.
![image](https://user-images.githubusercontent.com/59859911/77505914-dcd00400-6e3a-11ea-86cf-4aa969df3677.png)
![image](https://user-images.githubusercontent.com/59859911/77505937-e9545c80-6e3a-11ea-8e12-32d9b8ecfd5c.png)

**Comment by LoneGazebo** [comment]
In this situation the AI tries to achieve a minimum level of productivity, even with a food focus.

**Comment by silentreply** [comment]
I was just clarifying that the citizen allocation is identical in the first image on default or prod focus. My point was that the tile selection is not optimal - working the 3f tile yields 1 extra production over the 1f/1p tile. 

Although the math doesn't add up...there should be 2 excess food in the first image, 4 excess in the second. The production should be the same if I'm not mistaken.
