### ISSUE TITLE
Function to calculate the median from a vector's values?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6371]
To make the "wonder spammer" modifier (building way more Wonders than average) more balanced, I'm thinking of using the median value among major civs as the comparison point rather than the mean, which should be less susceptible to various weirdness.

Probably the easiest way to do this would be to use a vector, push back every civ's value, and find the median - is there some kind of easy function for finding the median set up already?

Could perhaps use this for the reckless expander modifier too.

**Comment by ilteroi** [comment]
search for nth_element

**Comment by HeathcliffWarriors** [comment]
So that's vector.GetElement(n) after using vector.SortItems()?

**Comment by LoneGazebo** [comment]
@HeathcliffWarriors look at how we set the global averages in CvGame.

**Comment by LoneGazebo** [comment]
void CvGame::updateGlobalAverage()

**Comment by ilteroi** [comment]
there is no median without sorting. std::nth_element() is optimized because it doesn't sort the complete vector. but for a small vector the difference is negligible.

**Comment by HeathcliffWarriors** [comment]
Ah, so std::nth_element finds the correct median value without needing to sort the entire vector?
