### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6372]
![image](https://user-images.githubusercontent.com/1358966/77003732-282b7380-695e-11ea-95b9-9eefc705ead0.png)

**Comment by JamesNinelives** [comment]
So I noticed that sometimes a size 1 city will prefer to work a production tile rather than a food tile and needs to be redirected manually. Maybe what is going on here?

I assume it is the city size you are talking about, in spite of having several tile improvements.

**Comment by azum4roll** [comment]
Someone has reported it on the forums too. It seems to be the result of resettling a razed city.

**Comment by ilteroi** [comment]
definitely a connection with razing but doesn't have to be the same plot

**Comment by LoneGazebo** [comment]
fixed. bad booool.
