### ISSUE TITLE
Better memory management for diplo AI

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6375]
@LoneGazebo A while back (https://github.com/LoneGazebo/Community-Patch-DLL/issues/5489#issuecomment-509841750), you said this...

> To make you feel better the diplo AI memory management functionality is absurdly overdone. It's like they decided to mix the worst parts of two memory management systems.

Although I'm able to add new values now, I still find it complicated to work with myself. If it's indeed mixed this badly and absurdly, is there a way to simplify it to make it easier to work with?

**Comment by ilteroi** [comment]
well i don't know which two parts he was referring to, but i don't see an easy & risk-free way to simplify anything.

you need to remember a lot of stuff about each player in the game one way or another.

my personal preference would have been to have a "PlayerDiploData" struct and then ONE array of those, not a million independent arrays. but changing that now is very invasive.

**Comment by LoneGazebo** [comment]
The struct already exists - DiplomacyAIData - but for some reason I can't comprehend they have this struct, and then identical structs, that they pass data to and from. Perhaps the struct was performance-intensive in Civ4, and they simply ported the code over? From what I can tell they store data in the struct for save/load, and then push it into a series of arrays (like CvUnit etc.) at runtime.

**Comment by LoneGazebo** [comment]
@ilteroi look at line 1707 of CvDiplomacyAI.h

**Comment by ilteroi** [comment]
indeed i had missed that part, that is messed up.

**Comment by LoneGazebo** [comment]
I really wonder if we could just scrap the data outside of the struct and just reference the struct directly.

**Comment by HeathcliffWarriors** [comment]
A number of the values aren't really used for anything useful - I got rid of the unused "working against player" code (I think that was only used in the earliest stages of the base Civ V game, if at all), but there's a lot of "other player estimate" functions that only record data for logging.

**Comment by ilteroi** [comment]
well in absolute terms the memory consumption for diplo AI is not so big, say 1k per player times 22? so you should not expect significant savings in that respect.

but if your goal is to make it easier to understand and maintain, go ahead ...

**Comment by HeathcliffWarriors** [comment]
As you say, it isn't really a memory problem, more that it's overcomplicated and unwieldy to work with. So if there's a way to improve that, I'd be happy.

**Comment by HeathcliffWarriors** [comment]
I'm just not sure how to go about doing that, due to the aforementioned overcomplication. :)

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo So, any chance you could help me by simplifying the memory system? I'm not experienced with memory, and don't want to screw anything up. :)

**Comment by LoneGazebo** [comment]
I think, at this advanced point, we just roll with it as is.

**Comment by HeathcliffWarriors** [comment]
_shrug_ Alright, I guess. Would've been nice, though. :)

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo If there's work involved in simplifying it that's tedious but not particularly complicated (like removing unnecessary memory elements), I wouldn't mind doing that part.
