### ISSUE TITLE
3/15 - (Tactical AI) No Aggression...then high Aggression on rerun

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6377]
_1. Mod version (i.e Date - 2/9):_
3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I found this one odd. I declared war on Mongolia and started hitting his city in the east. Mongolia remains extremely passive, and didn't see any units for about 4 turns. Ultimately I didn't like my positioning so I did a save scum to do it again.

This time on the same turn, Mongolia declares on me, and sends a nice solid force to attack me. What seems strange is, why didn't Mongolia do that the first time I attacked him, considering its the exact same circumstances?

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/77111296-18ab3980-69f5-11ea-9a21-fa58ce65fbeb.png)

-----------
[Tactical War AI.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4356738/Tactical.War.AI.zip)
----------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeathcliffWarriors** [comment]
War declaration aborting the AI operation?

**Comment by ilteroi** [comment]
you may be on to something here, i believe there is a problem with savegames, something is not saved or restored correctly.

when you load a savegame multiple times it's always the same behavior but it's different from the "original". unfortunately i haven't been able to pin down the root cause ...

**Comment by HeathcliffWarriors** [comment]
The way I read the OP, the AI declared war because Stalker didn't, later on the same turn. Seems like the AI was ready to attack the first time around but didn't because they were declared on first.

It _could_ be due to a savegame issue, but it could be something else too.

**Comment by Padre19** [comment]
I noticed that when you are in a long war with AI, after load a savegame he demands immediate peace.

**Comment by ilteroi** [comment]
@HeathcliffWarriors : can you take a look at this peace offer issue?

in the meantime i have determined that on reload the AI tends to buy plots it doesn't buy in the original "history".

first run:
037, Mongolia, Checking plot (54:9) for scout Warrior 1006 - base score 160, extra 25, bonus 120
037, Mongolia, Warrior Explored to nearby target, To X: 54, Y: 9, From X: 53, Y: 7
037, Mongolia, Checking plot (40:30) for scout Pathfinder 1007 - base score 160, extra 0, bonus 120
037, Mongolia, Checking plot (39:32) for scout Pathfinder 1007 - base score 165, extra 0, bonus 120
037, Mongolia, Pathfinder Explored to nearby target, To X: 39, Y: 32, From X: 38, Y: 30
037, Mongolia, Pathfinder Explored to nearby target, To X: 30, Y: 22, From X: 32, Y: 20
037, Mongolia, Warrior healing at, X: 36, Y: 18
037, The_Inca, Best settle plot (no embarkation) is 53,17 - value 67322

second run (reload save from t37):
037, Mongolia, Buying plot, X: 36, Y: 16, Cost: 45, Balance (before buy): 106, Priority: 177 <--------------
037, Mongolia, Checking plot (54:9) for scout Warrior 1006 - base score 160, extra 25, bonus 120
037, Mongolia, Warrior Explored to nearby target, To X: 54, Y: 9, From X: 53, Y: 7
037, Mongolia, Checking plot (40:30) for scout Pathfinder 1007 - base score 160, extra 0, bonus 120
037, Mongolia, Checking plot (39:32) for scout Pathfinder 1007 - base score 165, extra 0, bonus 120
037, Mongolia, Pathfinder Explored to nearby target, To X: 39, Y: 32, From X: 38, Y: 30
037, Mongolia, Pathfinder Explored to nearby target, To X: 30, Y: 22, From X: 32, Y: 20
037, Mongolia, Warrior healing at, X: 36, Y: 18
037, The_Inca, Best settle plot (no embarkation) is 53,17 - value 67322

so maybe if they spend their money there, they have less for buying units ...

**Comment by HeathcliffWarriors** [comment]
Sure, I'll take a look at the peace logic.

**Comment by HeathcliffWarriors** [comment]
I don't have a test case for the peace offer issue, but I've asked people on the forum to post on Github with a save/logs so I can look more into it.

**Comment by ilteroi** [comment]
i'm not sure the city yield issue completely fixes the whole wider reproducability problem, but it's a start

**Comment by HeathcliffWarriors** [comment]
Oh, I misinterpreted what you meant by "this one is fixed", then :)
