### ISSUE TITLE
3/15 - Religious pressure bugged?

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6378]
_1. Mod version (i.e Date - 2/9):_ 3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Observing strange values for religious pressure. Rabat has 3 cities in range following Islam, +3 pressure. Sale has 1 city in range, +9 pressure, no trade routes. Pressure from trade routes appears in the available trade routes tab, but not in the active routes tab, but does seem to be applied to cities. Lodz has two cities in range, one trade route, +16 pressure. 

Would help to know what the default pressure values are for the AI and human player - can not find this information. Does the number of followers in a city increase pressure? Description of pressure mechanics is still very lacking in the wiki/civilopedia/forum. 

![image](https://user-images.githubusercontent.com/59859911/77119549-0fc66200-6a0d-11ea-8be9-96991c7cfa36.png)
![image](https://user-images.githubusercontent.com/59859911/77119708-5fa52900-6a0d-11ea-80b4-dbd039757ad2.png)
![image](https://user-images.githubusercontent.com/59859911/77119668-4d2aef80-6a0d-11ea-82e4-352c1540f005.png)

Update: Reloading save had no impact. Still seeing strange values. Rabat still at +3. See Agadir with 5 cities in range, +30 pressure - what I would expect to see based on vanilla civ +6 pressure per city. Logs and save posted. 

![image](https://user-images.githubusercontent.com/59859911/77124209-a0566f80-6a18-11ea-9fcc-e33250fbcb12.png)
![normal value](https://user-images.githubusercontent.com/59859911/77124772-2cb56200-6a1a-11ea-9ee6-63698bae8c60.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4357341/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[bersAhmad al-Mansur_0137 AD-0540.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4357342/bersAhmad.al-Mansur_0137.AD-0540.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
base pressure is 6.5 per city on a std map but that is then modified by distance (unless there is a trade route), buildings, beliefs, etc

maximum distance is your trade route range. religious pressure takes the same route a caravan/ship would take.

so you can check the available trade routes from a city and that is where your pressure is coming from.
