### ISSUE TITLE
Can improve GBR

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#638]
![8930_2015-09-19_00024](https://cloud.githubusercontent.com/assets/1131228/9977111/f81819c0-5f15-11e5-9c14-c703332012da.png)

**Comment by LoneGazebo** [comment]
If fish spawn there, yep.

**Comment by Radost** [comment]
Fish can't spawn on top GBR.

**Comment by LoneGazebo** [comment]
Fish can spawn there, I've seen it (the map generator is odd). This is an artifact of the map generation model, not the DLL. I could force limit no improvements on natural wonders, but that feels a bit heavy-handed.

**Comment by LoneGazebo** [comment]
I'll add the forced limit in the DLL, if anyone complains I can make it more flexible later
