### ISSUE TITLE
3/15 - Trade Issue Quantity

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6380]
_1. Mod version (i.e Date - 2/9): 3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

Can't trade my strategic resource, I can only sell 1 horse, if I choose to trade 3 automatically reverts back to one, and it's not like they don't want more horses cause I can sell them 1 horse multiple times. (tried with all civs and the same behavior)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**I have 3 horses**
![a](https://user-images.githubusercontent.com/49090452/77158438-ff18f900-6aab-11ea-98af-23b323438356.png)

**But here I can't change it to 3 or 2 cause it reverse back to 1**
![b](https://user-images.githubusercontent.com/49090452/77158444-00e2bc80-6aac-11ea-8776-5502989c6421.png)

**Here again I have 6 iron but can't give him more than 3 at a time (reverts back)**
![a](https://user-images.githubusercontent.com/49090452/77186584-c8f36d80-6adb-11ea-8f69-06be3bf6387b.png)
![b](https://user-images.githubusercontent.com/49090452/77186590-cabd3100-6adb-11ea-85bb-720ab3c2d78d.png)

**Comment by HeathcliffWarriors** [comment]
Possibly related to the resource quantity issues.
