### ISSUE TITLE
wonder city choice

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6381]
it's 1960 and yangshou is constructing the empire state building although it's a very small city in comparison and has basically no chance against a mature city:

![image](https://user-images.githubusercontent.com/1358966/77161372-cb3cd400-6aa9-11ea-82b0-50df0f1019bb.png)

![image](https://user-images.githubusercontent.com/1358966/77162037-579bc680-6aab-11ea-9c09-6aca5ec38644.png)

are there any empire-level sanity checks here? why is it filtered out in beijing?

325, China, Beijing, PRE: Building, Empire State Building, 4730, 12
325, China, Beijing, PRE: Unit, Archaeologist, 3240, 1
325, China, Beijing, PRE: Unit, Colonist, 3175, 5
325, China, Beijing, PRE: Process, Research, 951, 1
325, China, Beijing, PRE: Project, Public Works, 750, 2
325, China, Beijing, PRE: Building, Refinery, 480, 3
325, China, Beijing, PRE: Process, Wealth, 305, 1
325, China, Beijing, PRE: Process, Arts, 235, 1
325, China, Beijing, PRE: Unit, Fusilier, 200, 1
325, China, Beijing, PRE: Unit, Musketman, 140, 1
325, China, Beijing, PRE: Process, Defense, 100, 1
325, China, Beijing, PRE: Unit, Chu-Ko-Nu, 98, 1
325, China, Beijing, SKIPPED: Empire State Building, Val: 0, TURNS: 12
325, China, Beijing, SKIPPED: Colonist, Val: 0, TURNS: 5
325, China, Beijing, SKIPPED: Defense, Val: 0, TURNS: 1
325, China, Beijing, POST: Unit, Chu-Ko-Nu, 823, 1
325, China, Beijing, POST: Unit, Fusilier, 769, 1
325, China, Beijing, POST: Unit, Musketman, 757, 1
325, China, Beijing, POST: Building, Refinery, 577, 3
325, China, Beijing, POST: Process, Research, 179, 1
325, China, Beijing, POST: Process, Wealth, 140, 1
325, China, Beijing, POST: Process, Arts, 140, 1
325, China, Beijing, POST: Unit, Archaeologist, 100, 1
325, China, Beijing, POST: Project, Public Works, 20, 2
325, China, Beijing, SEED: 14530450033885803781, CHOSEN: Military, Fusilier, NoRush, ERA: 4, TURNS: 1

325, China, Yangzhou, PRE: Building, Customs House, 10980, 2
325, China, Yangzhou, PRE: Building, University, 7860, 1
325, China, Yangzhou, PRE: Building, Aqueduct, 4080, 1
325, China, Yangzhou, PRE: Building, Workshop, 3911, 2
325, China, Yangzhou, PRE: Building, Empire State Building, 3430, 36
325, China, Yangzhou, PRE: Building, Windmill, 3386, 3
325, China, Yangzhou, PRE: Building, Herbalist, 3100, 1
325, China, Yangzhou, PRE: Building, Refinery, 2730, 13
325, China, Yangzhou, PRE: Building, Bank, 2691, 3
325, China, Yangzhou, PRE: Unit, Colonist, 2425, 23
325, China, Yangzhou, PRE: Building, Stone Works, 2070, 1
325, China, Yangzhou, PRE: Unit, Fusilier, 1980, 4
325, China, Yangzhou, PRE: Building, Lighthouse, 1960, 1
325, China, Yangzhou, PRE: Building, Arena, 1927, 1
325, China, Yangzhou, PRE: Unit, Musketman, 1386, 2
325, China, Yangzhou, PRE: Building, Armory, 1340, 1
325, China, Yangzhou, PRE: Unit, Chu-Ko-Nu, 990, 1
325, China, Yangzhou, PRE: Building, Opera House, 786, 1
325, China, Yangzhou, PRE: Project, Public Works, 625, 10
325, China, Yangzhou, PRE: Process, Research, 608, 1
325, China, Yangzhou, PRE: Process, Wealth, 505, 1
325, China, Yangzhou, PRE: Process, Farming, 320, 1
325, China, Yangzhou, PRE: Building, Constabulary, 150, 3
325, China, Yangzhou, PRE: Process, Arts, 110, 1
325, China, Yangzhou, PRE: Building, Walls, 100, 1
325, China, Yangzhou, PRE: Process, Defense, 100, 1
325, China, Yangzhou, SKIPPED: Refinery, Val: 0, TURNS: 13
325, China, Yangzhou, SKIPPED: Colonist, Val: 0, TURNS: 23
325, China, Yangzhou, SKIPPED: Defense, Val: 0, TURNS: 1
325, China, Yangzhou, POST: Building, Empire State Building, 38892, 36
325, China, Yangzhou, POST: Building, Walls, 8176, 1
325, China, Yangzhou, POST: Building, Opera House, 4887, 1
325, China, Yangzhou, POST: Building, Arena, 2527, 1
325, China, Yangzhou, POST: Building, University, 2305, 1
325, China, Yangzhou, POST: Building, Workshop, 1973, 2
325, China, Yangzhou, POST: Building, Customs House, 1710, 2
325, China, Yangzhou, POST: Building, Armory, 1443, 1
325, China, Yangzhou, POST: Building, Windmill, 1174, 3
325, China, Yangzhou, POST: Building, Constabulary, 1159, 3
325, China, Yangzhou, POST: Building, Aqueduct, 841, 1
325, China, Yangzhou, POST: Building, Lighthouse, 825, 1
325, China, Yangzhou, POST: Building, Stone Works, 821, 1
325, China, Yangzhou, POST: Building, Bank, 787, 3
325, China, Yangzhou, POST: Building, Herbalist, 737, 1
325, China, Yangzhou, POST: Unit, Chu-Ko-Nu, 556, 1
325, China, Yangzhou, POST: Unit, Musketman, 435, 2
325, China, Yangzhou, POST: Unit, Fusilier, 376, 4
325, China, Yangzhou, POST: Process, Research, 239, 1
325, China, Yangzhou, POST: Process, Farming, 109, 1
325, China, Yangzhou, POST: Process, Wealth, 101, 1
325, China, Yangzhou, POST: Process, Arts, 89, 1
325, China, Yangzhou, POST: Project, Public Works, 24, 10
325, China, Yangzhou, SEED: 7325575516212182973, CHOSEN: Wonder, Empire State Building, Rush, ERA: 5, TURNS: 36

**Comment by LoneGazebo** [comment]
AI should only build wonders in the ‘approved’ city.
