### ISSUE TITLE
3/15 - Can build Stone Works without resource requirements

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6383]
_1. Mod version (i.e Date - 2/9):_
3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Unless its a new feature (can build stone works in the capital), my cap here should not be able to build a stone works, as there is no resource it controls that's pertinent.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/77229082-a011bd80-6b59-11ea-96a1-95eeb6a0e493.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by randomnublet** [comment]
Did you move your initial settler? Only thing I can think is you moved over a stone tile and is now hiding under your city, in that case the resource icon goes away.
