### ISSUE TITLE
Old repository branches?

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6386]
There's a number of "stale" repository branches which haven't seen updates in a really long time.

master, ole and diplomacy are the only active ones. So...is there any reason for keeping the old ones, or should they be deleted?

**Comment by LoneGazebo** [comment]
they don't hurt anything.

**Comment by HeathcliffWarriors** [comment]
They don't, just wondering. :)
