### ISSUE TITLE
3/15 - Low Religious Pressure

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6388]
_1. Mod version (i.e Date - 2/9):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:

I never saw so little pressure when the capital is in 10 tiles range and another city also within 10 tiles range (capital has two religious buildings with total 50 extra pressure and the other city has one with another 25 extra pressure)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![a](https://user-images.githubusercontent.com/49090452/77352480-ecbaeb80-6d47-11ea-9373-8ece33a3278f.png)

**Comment by silentreply** [comment]
This is partly due to reduced spread over water. Terrain features also slow "movement" of pressure, and roads can accelerate it. These mechanics are not mentioned in the wiki/civilopedia, but might be somewhere in old patch notes. Heathcliff mentioned he would look in the code.

It does seem to be overtuned in my opinion however. Lighthouses do not seem to have an effect either. And I do believe that some aspects are actually bugged. I posted a report where a city has low pressure (+3), and the holy city is indeed across water, however that city also has other cities in range over land that should be applying full pressure.

**Comment by ilteroi** [comment]
well, i think i found something suspicious:

		int iNumFollowersOtherReligions = pFromCity->GetCityReligions()->GetNumFollowers(eReligion);

should probably be

		int iNumFollowersOtherReligions = pFromCity->GetCityReligions()->GetFollowersOtherReligions(eReligion);

**Comment by ilteroi** [comment]
also it seems you can have pressure from non-majority religions? is this new?

**Comment by LoneGazebo** [comment]
Non-majority religions produce pressure, yes.

**Comment by LoneGazebo** [comment]
The only changes to pressure that I can think of are related to ye olde pathfinder.

**Comment by silentreply** [comment]
@ilteroi It may not be intended to but it certainly appears to be occurring in game. The post below might be relevant.

![image](https://user-images.githubusercontent.com/59859911/77706920-15d2ba80-6f9a-11ea-875f-0d61e18f334d.png)

There really isn't a clear description of how the mod has changed pressure mechanics. I would like to be of more help but I'm unable to calculate what the actual pressure values should be.

**Comment by ilteroi** [comment]
i think the code is a better reference than a forum post ...

**Comment by silentreply** [comment]
What I was getting at is that the pathfinder for pressure may not be using water tiles properly.

**Comment by ilteroi** [comment]
send a cargo ship. it's the same pathfinder
