### ISSUE TITLE
Fresh water and Buildings

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#639]
Not a Bug Report

The Water Mill can only be constructed in a city located next to a **river**.
The Well can only be constructed in a city without access to **fresh water**.

Fresh water means a **river, lake or oasis**.
Neither the Water Mill nor the Well can be constructed in a city located next to a **lake or oasis**.
How about changing the terrain requirements of these buildings?

By the way, Gardens and Baths don't have such an issue.
The Garden can only be constructed in a city **with** access to fresh water.
The Bath can only be constructed in a city **without** access to fresh water.

**Comment by LoneGazebo** [comment]
Bath and Well use same function to determine location. Is this an issue of wording in the tooltips, or a functional issue?

**Comment by 8h42** [comment]
I think this is a functional issue.
It would be great if we could build either a Water Mill or a Well in every city.

One of the simplest ways to solve this issue is to make a Water Mill a "fresh water building" like a garden.
But, does it seem strange to construct a Water Mill near a lake or oasis?

**Comment by LoneGazebo** [comment]
I'll just make a 'noriver' function and tie it to that.
G

**Comment by 8h42** [comment]
That sounds like a perfect.
Are you going to apply the "noriver" rule to Wind Plants too?

**Comment by LoneGazebo** [comment]
Yep.

**Comment by 8h42** [comment]
Wonderful.
