### ISSUE TITLE
Map missing City info such as growth, what's under production, and population size

### ISSUE THREAD

**Issue by RJArtistry** [LoneGazebo/Community-Patch-DLL#6391]
_1. Mod version (i.e Date - 2/9): 
July 17th (4.7.17)

_2. Mod list (if using Vox Populi only, leave blank):_
Vox 43 Civ - No EUI
Info Addict
Conquest for Unique Unit
In Game Editor (IGE)

_3. Error description:_ 
Originally I installed Vox with the EUI. I ended up really disliking the interface and tried to remove it. I deleted the DLC folder but even afterwards I was still seeing some of the UI changes (like the Interface option changes in the settings menu). So I deleted the mod completely, reinstalled Civ, and then reinstalled Vox with the 43 civ fix and no EUI. 

Now when I load up the games, the map isnt' showing information properly for cities. It's missing the growth rate, production tyle, and there the icons for espionage below the city name. The cities prompt me to bombard, but that goes away after one turn.

_4. Steps to reproduce (optional):_
I did some searching and the only bug report that seems similar to this issue is this thread here:
https://github.com/LoneGazebo/Community-Patch-DLL/issues/4422
However I was unable to find the line item mentioned for the fix

Issue persisted after disabling IGE. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

[Civ Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4372021/Civ.Bug.zip)

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Screenshot 2020-03-23 16 49 02](https://user-images.githubusercontent.com/33042997/77365819-229ea680-6d2d-11ea-841f-e42a55a75cdc.png)

**Comment by Vyyt02** [comment]
How did you remove EUI? Did you manually delete the UI_bc1 folder from DLCs? I'd also delete cache and all Vox Populi components from the MODS folder manually to be sure. Then I'd reinstall Vox Populi via autoinstaller. Maybe to be on the safe side, I'd pick the standard (not 43 civs) non-EUI version first. I am not familiar with the Conquest for Unique Unit mod - are you sure it's compatible? It could be causing some mod conflict.
