### ISSUE TITLE
AI makes peace although they don't want to

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6393]
i have a save game here where carthage is about to capture the zulu capital. the zulus obviously want peace, and carthage accepts although they shouldn't.

the debugger tells me:
* IsWantsPeaceWithPlayer(zulu) is false for carthage! 
* GetTreatyWillingToAccept(zulu) is CAPITULATION for carthage
* next turn GetTreatyWillingToAccept(zulu) is NO_PEACE for carthage

so there is definitely an inconsistency here.

@HeathcliffWarriors : care to take a look?

**Comment by HeathcliffWarriors** [comment]
Will investigate. Mind posting the save game?

**Comment by HeathcliffWarriors** [comment]
Added some new checks - values should no longer conflict, and peace treaties can't be traded with the AI if IsWantsPeaceWithPlayer is false.

**Comment by ilteroi** [comment]
well extra checks shouldn't be necessary, there already is a check in DoUpdatePeaceTreatyWillingness():
```
					//don't give up if we're about to score!
					if (!IsWantsPeaceWithPlayer(eLoopPlayer))
					{
						SetTreatyWillingToOffer(eLoopPlayer, NO_PEACE_TREATY_TYPE);
						SetTreatyWillingToAccept(eLoopPlayer, NO_PEACE_TREATY_TYPE);

						continue;
					}
```

but apparently it doesn't work as intended.

or worse, there is another problem with serialization/deserialization.

**Comment by HeathcliffWarriors** [comment]
If there is a problem with serialization, this fixes it - albeit somewhat clumsily, since all calls to get the peace treaty type will check IsWantsPeaceWithPlayer.

This is more of a temporary patch, I'll investigate the underlying issue this weekend when I have more time to play Civ. :)

**Comment by RecursiveVision** [comment]
@ilteroi by the way, this is fixed now - diplo AI was having serialization bugs
