### ISSUE TITLE
India still building Stonehenge

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6394]
you might argue it's only bad luck with the RNG, stonehenge was actually second choice, but the interesting thing is that the PRE weights seem more sensible than the POST weights

029, India, Delhi, PRE: Unit, Settler, 10750, 11
029, India, Delhi, PRE: Building, Granary, 4796, 7
029, India, Delhi, PRE: Building, Council, 4110, 7
029, India, Delhi, PRE: Building, Stonehenge, 1020, 19
029, India, Delhi, PRE: Unit, Archer, 546, 6
029, India, Delhi, PRE: Process, Farming, 410, 1
029, India, Delhi, PRE: Unit, Worker, 300, 10
029, India, Delhi, PRE: Unit, Warrior, 219, 5
029, India, Delhi, PRE: Unit, Pathfinder, 49, 5
029, India, Delhi, SKIPPED: Worker, Val: 0, TURNS: 10
029, India, Delhi, POST: Unit, Settler, 7094, 11
029, India, Delhi, POST: Building, Stonehenge, 4571, 19
029, India, Delhi, POST: Building, Council, 293, 7
029, India, Delhi, POST: Unit, Archer, 262, 6
029, India, Delhi, POST: Building, Granary, 137, 7
029, India, Delhi, POST: Unit, Pathfinder, 123, 5
029, India, Delhi, POST: Unit, Warrior, 121, 5
029, India, Delhi, POST: Process, Farming, 96, 1
029, India, Delhi, SEED: 1786177054798549254, CHOSEN: Wonder, Stonehenge, Rush, ERA: 0, TURNS: 19

**Comment by LoneGazebo** [comment]
India building it is fine - it still gets the faith yields and the free council.

**Comment by LoneGazebo** [comment]
Puts it one step closer to an early religion.

**Comment by ilteroi** [comment]
a small step while he's losing tempo. but anyway, in that game he's the leader, so it cannot be that bad a blunder :)
