### ISSUE TITLE
AI workers building kasbahs next to foreign cities

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6395]
![image](https://user-images.githubusercontent.com/1358966/77479953-13992080-6e21-11ea-8a9f-6d1acba4f35a.png)

**Comment by LoneGazebo** [comment]
Yup!

**Comment by ilteroi** [comment]
forgot to mention, it's way out of range of their own city ...

**Comment by azum4roll** [comment]
I thought this was intended?

**Comment by silentreply** [comment]
I've known this is possible, but if I remember correctly, the description in game says they can only built adjacent to "owned" cities...
