### ISSUE TITLE
Puppets giving specialist unhappiness?

### ISSUE THREAD

**Issue by crdvis16** [LoneGazebo/Community-Patch-DLL#6396]
_1. Mod version (i.e Date - 2/9):_
3-15

_2. Mod list (if using Vox Populi only, leave blank):_
VP+EUI

_3. Error description:_ 
Puppet cities are generating 1/4 pop unhappiness from being a puppet but also generating unhappiness from specialists they are self assigning.

_4. Steps to reproduce (optional):_
Presumably just puppet some cities and you'll eventually see it.  If save games are needed I can provide them but I assume it should be easy to replicate.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by crdvis16** [comment]
Screen shot if it's useful

![puppet unhappiness](https://user-images.githubusercontent.com/17805009/77480797-c0ab7300-6df8-11ea-964d-84b9763d5356.png)

**Comment by LoneGazebo** [comment]
Intended
