### ISSUE TITLE
3/15 - Possible Religious Conversion Bug

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6398]
_1. Mod version (i.e Date - 3/15):_
3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm just putting this on the watch list for now. This city in question was decidedly Jewish last turn (I literally just poured 20,500 pressure into last turn, and it flipped on about 10,000).

I guess its possible that Aztec also poured an equal absurd amount of missionaries into the city in one turn, hence its watch list only to see if I can replicate it.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/77561435-af13ab00-6e8c-11ea-9fdd-4521639555b1.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
inquisitor?

**Comment by Stalker012345** [comment]
On a CS?

**Comment by ilteroi** [comment]
uh. i just read the name, totally missed the fact that it has revolted.
