### ISSUE TITLE
Liberty finisher procs upon city capture

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#640]

**Comment by Radost** [comment]
That's not needed to be "fixed", because I forgot I had Imperialism maxed.
Liberty does proc on a city founding though, because I saw the gold number showing up several times after the founding.

**Comment by LoneGazebo** [comment]
Is it from city growth, i.e. the change of a city's pop via a colonist/pioneer/order policy?

**Comment by Radost** [comment]
From the city founding, the colonist/pioneer/order just multiply this number.
https://d.maxfile.ro/xhlzuuonmh.webm
Notice how the gold went up even though I didn't do anything beside settling.
