### ISSUE TITLE
Revolting cities don't update the city title

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6404]
_1. Mod version (i.e Date - 3/15):_ Latest

Reported in this post:
https://forums.civfanatics.com/threads/new-beta-version-march-15th-3-15.656118/page-8#post-15712792

"Although, there's probably a bug with city flipping, as I've noticed a few times it's happened where the new CS states it has flipped to "X", but it keeps the same name of the original city, e.g., Chicago is now Bratislava except it still says Chicago on the map until you actually click on the CS, where it will then list it as Bratislava in the CS screen. Just wondering if anyone else has viewed this; for all I know, it's unavoidable and is just a side-effect of the way it's implemented, but I figured I'd point it out considering it does bring some confusion."

**Comment by LoneGazebo** [comment]
intended - as bratislava is the 'culture' whereas the city name remains the same.

**Comment by LoneGazebo** [comment]
Also calling them revolting is mean. Ugly, maybe, but revolting?
