### ISSUE TITLE
Suggestion for Worker AI

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6405]
If the AI's Workers are completely out of things to do, the Worker AI should build Roads/Railroads in nearby allied CS borders. They're free, and it increases mobility for the AI's units.

**Comment by ilteroi** [comment]
you means the roads are free because the city state will pay the maintenance on them? not sure if it works that way ...

anyway there is a quest to connect minors, you could just increase its frequency, then the AI will connect city states

**Comment by HeathcliffWarriors** [comment]
I actually don't know if the CS pays road maintenance - they might be outright free.

And unlike the road quest, if I have extra Workers I just spam roads on every single tile within CS borders - why not?

**Comment by ilteroi** [comment]
because it's ugly?

**Comment by HeathcliffWarriors** [comment]
Perhaps, but it's practical. And if it works, the AI should do the same ... or it should be nerfed, but I honestly like it the way it is, since it makes the "connect with a road" quest more feasible to complete.

**Comment by HungryForFood** [comment]
Please don't, there are some players who are slightly OCD, like me...

**Comment by Omen-of-Peace** [comment]
It does make sense to me, though I haven't done it. One of the remaining advantages for humans is perhaps that we spam roads around contested areas (in owned, neutral or CS territory), which is essential to rotate units and keep them alive.
