### ISSUE TITLE
3/15 - AI Settler not move out to settle

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6406]
_1. Mod version (i.e Date - 3/15):_
3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I've grown accustomed to the AI founding 1 or even 2 cities before I do on Emperor, so I found it strange that my neighbor only had one. It looks like the settler is just hanging out in this base.

![image](https://user-images.githubusercontent.com/20593976/77622207-d8bfe700-6f0b-11ea-925b-1b5acec49371.png)

[Settler Issue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4385717/Settler.Issue.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Update: He finally settled on Turn 65

**Comment by HeathcliffWarriors** [comment]
Possibly there were Barbarians nearby? I see an encampment up there.

**Comment by Stalker012345** [comment]
> Possibly there were Barbarians nearby? I see an encampment up there.

AIs are usually good about escorting their settlers. Honestly if barbs were the normal problem I don't think I'd ever see them expanding early, barbs are pretty common now that CS don't take camps.
