### ISSUE TITLE
idea for trade & religion

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6408]
i know, going for gold and so on ... but still.

how about religious pressure only happens over trade routes. and once a player has researched civil service, you need open borders to send trade routes to him.

result: gives more control over religion spread & makes open borders more useful.

think about it!

**Comment by Stalker012345** [comment]
Hehe I just made a note on the forum how if I had my way, pressure would be removed entirely from the game in favor of missionary only:)

I do think its too aggressive for the core mod....and a worthwhile experiment as a mod mod.

**Comment by LoneGazebo** [comment]
@ilteroi that's largely how it works in civ4...and you know how I like civ4.

**Comment by ilteroi** [comment]
actually i don't even remember civ 4 ...

i just see that the current system is a mess that nobody understands.

but anyway, since you made c4df at one point, i assume you're in favor?

**Comment by LoneGazebo** [comment]
c4df wasn't me! But I have shamelessly cribbed ideas from Civ4 before, such as corporations.

Only issue is that we have a few players and abilities that rely on the pressure system to function. Such a change kills India, for example. So we'd need to think about it.

**Comment by LoneGazebo** [comment]
One option would be to make pressure a defensive mechanic, so that 'pressure' is simply a city's resistance to conversion. Doing so means, again, we'd need to think about civs that use pressure as a UA mechanic. I'm not 100% sure it is worth the effort, at this stage. Perhaps we can simply modify the underlying pressure mechanic to operate on the old 'terrainless' pathfinder map, instead of using actual routes?

**Comment by ilteroi** [comment]
well india does have trade routes and a head start on religion, so that sounds feasible? maybe give them some resistance to conversion.

yes numbers will need adjustment but it will be so much better.

**Comment by HeathcliffWarriors** [comment]
I think it's a good idea as well. Would make religion a far more strategic endeavor.

**Comment by silentreply** [comment]
I agree that going back to the "terrainless" pathfinder would be a simple way to address this in the short term.

**Comment by ilteroi** [comment]
i refuse to consider that option. the pathfinder is just a scapegoat. 

you can see it at work for all trade units and there is nothing wrong with it.

a terrainless pathfinder is just tile distance and stupid.

**Comment by Stalker012345** [comment]
Well hot damn, this actually got some consideration. Well ok then!

So if you want to go for a simplier system, that still uses trade routes:

1) We change pressure to "Religion Points" (call them whatever you would like, still call it pressure if you want). These are simply 1,2,3, 4....easy to use numbers. I am going to scale it up about 4 times higher than my base, to account for your 25% stronger missionaries and the like.

2) A pantheon city has 3 points in pantheon. A Holy City starts has 20 religion points in its religion. 

3) This system assumes no additional points based on growth, proximity or time...which simplifies everything greatly. Missionaries and Trade Routes is what we are focusing on.

4) A missionary bam adds 4 points. If this city has no religion currently, it gets an extra 2 points in that religion (this part may be unnecessary, just want to ensure cities convert well enough in the beginning). Unwelcome evangelist subtracts 1 point until it dies.

5) Buildings subtract 1 point from a missionary hit (there resistance power). +25% missionary strength = +1 religion point on bam. -25% erosion = -1 religion point to other religions.

6) When a TR finishes in a city, it generates 4 points (this one I'm less sure of the right number to start off with, but a TR = 1 missionary bam felt right as a base).

7) If you still want inquisitors to work like now, have them remove all foreign religion points.

8) All follower % are the ratios of the various points.

And done. You can put that in a simple helpfile and explain it very easily to a person.

**Comment by silentreply** [comment]
The pathfinder itself works great. What I am concerned about is the pressure being applied using the pathfinder - particularly over water but possibly in other situations. While it is a more realistic system, it has complicated pressure to a degree that few seem to understand exactly how pressure works. 

I do like the idea you posted, but as G said it could be more complicated to implement.

**Comment by HeathcliffWarriors** [comment]
@Stalker012345 I actually like this idea a lot.

**Comment by ilteroi** [comment]
there is also spy pressure per turn ... what about that? is getting rid of per turn pressure really important or is it just a UI problem because the accumulated values are not shown right now?

anyway i prepared a simple change for a start where cities only exert per turn pressure if there is a trade route between them (any direction).

numbers for base pressure, holy city pressure, missionary strength etc are the same as before, but you can modify them in the database.

todo: add AI logic to consider religion when trading open borders, choosing trade unit targets

[CvGameCore_Expansion2-new-religion.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4397965/CvGameCore_Expansion2-new-religion.zip)

**Comment by silentreply** [comment]
@ilteroi I'm not opposed to passive pressure per turn. There appear to be bugs with the current system - most apparent being pressure applied over water. Cities seem to apply only +1 pressure over water regardless of distance/modifiers. I was under the impression that reduced pressure over water may be intended to some degree - but your comment on the bug report suggested it was not.

If the UI were more clear about pressure sources and the modifiers applied it would certainly be helpful - not just for players but also for validation purposes.

**Comment by Stalker012345** [comment]
> there is also spy pressure per turn ... what about that? is getting rid of per turn pressure really important or is it just a UI problem because the accumulated values are not shown right now?

Ultimately the biggest complexity is the calculation of all the pressure values at the moment, so you are right that removing that would be the biggest improvement in understanding the system (a UI update to use accumulated pressure would also be wonderful).

That said, if we are down to TR pressure and spy pressure (which exists on one belief....and is not all that amazing at the moment to be honest)…. I always go back to the quote "A designer knows he has achieved perfection, not when he has anything left to add...but when he has nothing to take away"

If we are down to so few sources of per turn pressure, is it worth keeping? Make TR pressure something obvious and special (like a missionary spread), and remove spy pressure (which isn't doing much already).

So that's my push there, but if we went with your current concept I do think it would remove most of the issue.

**Comment by ilteroi** [comment]
i'm fine with removing per turn pressure, it's just more work than disabling only city pressure w/o trade route.

anyway there is a lua method GetAccumulatedPressure() now, should be easy hook up in the UI.

could you try and get a picture of the opinion in the forum? my account is still out of order ...

**Comment by LoneGazebo** [comment]
Would it be possible to make the pressure calculations show you converts per x turns, instead of the random value (i.e. +30 pressure could show the estimate of (1 conversion every 5 turns). ?

**Comment by Stalker012345** [comment]
Going to give Iterois dll a shot in my next game.

**Comment by Stalker012345** [comment]
First result with Iterois update. Turn 145, so far so good. I'm not noticing anything really different about spreading to my initial cities, I can clearly see the pressure when my TRs are activated.

India is in my game (farther away), and he is obviously struggling, but that was expected with his current setup.

I am starting more aggressive spread and we will see how that goes.

**Comment by ilteroi** [comment]
@g: i don't think it works that way ... followers are only recomputed on certain events, eg growth

**Comment by LoneGazebo** [comment]
Well, okay, so if we’re really considering dropping passive pressure, can we make that India’s UA? And also can we make it such that the existing enhancer gives it as well? It’d be a reduced value of course but let’s not scrap the system, just make it default to zero for anyone that doesn’t have a special bonus. 

Also how is this going to affect belief buildings?

**Comment by Stalker012345** [comment]
Turn 205. So what I am noticing now is as TRs are becoming more external (and more CS focused with the various statecraft civs), followers numbers are not keeping up with growth. Unless they receive a missionary "top off" every so often, the follower number start to decline compared to overall population.

Also, it looks like the unwelcome evangelist penalty isn't working.

**Comment by LoneGazebo** [comment]
I wonder if city connections via roads should count as a TR for connection purposes?

**Comment by LoneGazebo** [comment]
That would resolve the internal pressure issue. So in essence the only major 'change' we'd see would be pressure between non-connected cities disappearing. India's UA could remain the same (pressure to all cities instead of just connected cities), and the enhancer belief could allow the same as well. Both would need to have reduced value, of course, but they could still exist.

**Comment by Stalker012345** [comment]
If I'm not mistaken, with the road as TR change...effectively you are just removing any of the modifiers to pressure we have today (like distance, percentage of followers, etc).

**Comment by LoneGazebo** [comment]
@Stalker012345 correct.

base pressure 6.5 on std map **between road-connected cities only**
trait modifiers **between road-connected cities only**
belief modifiers **all cities in range**
city state friendship modifier (removed)
tech modifier (printing press) (added to base pressure 6.5 above)
policy modifier (added to TR/Road connected cities only)
congress modifier (world religion) (added to TR/Road connected cities only)
vassal modifier (removed)
building modifier (added to TR/Road connected cities only)
population modifier (india) **all cities in range**
quest modifier (removed)
scale by fraction of followers in origin city, unless spread religion is majority (removed)
relative faith output modifier (if no traderoute) (removed)
distance modifier relative to max spread distance (if no traderoute) (only affects belief modifiers and india)

**Comment by ilteroi** [comment]
@LoneGazebo : the code for passive pressure is still there, no worries. i thought about the "pressure via city connection" and it could work as well, but it needs new AI logic for when to connect their road network to another player's network (or disconnect for that matter). also what about naval connections? what is the influence of open borders?

@Stalker012345: "followers numbers are not keeping up with growth" this is because each newborn citizen is an atheist at first, can be changed with RELIGION_ATHEISM_PRESSURE_PER_POP

**Comment by Stalker012345** [comment]
The other question, the pressure all of your cities would receive would be from your capital correct? In that case, someone would have a severe drawback if their holy city was in a secondary city...the overall pressure for their cities would be much lower.

**Comment by Stalker012345** [comment]
So one interesting note, since TRs only carry pressure from the majority religion, it makes flipping a city a bigger pressure switch than just gradually adding followers. Once you flip a city, its TR pressure will lose all of the opposing religious pressure it was generating and now generate pressure for you.

**Comment by Stalker012345** [comment]
@ilteroi here are the poll results so far (34 votes weighed in).

Model 1 

6 vote(s) 
17.6% 

Model 2 

3 vote(s) 
8.8% 

Both Model 1 and 2 

2 vote(s) 
5.9% 

Neither model, but I would like to see some conversion updates. 

12 vote(s) 
35.3% 

I don't want to see religious conversion changed. 

11 vote(s) 
32.4%
