### ISSUE TITLE
Railroads do not provide the movement bonus

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#641]
At least not more than roads.

**Comment by ilteroi** [comment]
will check

**Comment by ilteroi** [comment]
can't reproduce in my current version - but then again i have cleaned up a bunch of old code, maybe that was an accidental stealth fix

**Comment by Radost** [comment]
Is 15/9 version too old already?
https://d.maxfile.ro/snuvxhdqnx.webm
