### ISSUE TITLE
3/15 - Prophecy Holy Site not producing full tourism

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6412]
_1. Mod version (i.e Date - 3/15):_
3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The holy site icon says it produces 6 tourism. But based on the change in yield (see before and after screenshot), it looks like its only producing 3. I have prophecy, though I don't know if that is really a part of the issue.

_4. Steps to reproduce (optional):_
With holy site.
![image](https://user-images.githubusercontent.com/20593976/77793389-f38f7a00-7037-11ea-9d29-a05acbf64a4f.png)

One holy site turned off (3 drop in tourism).

![image](https://user-images.githubusercontent.com/20593976/77793414-01dd9600-7038-11ea-9deb-3e0767e9f571.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
any tourism penalties?

**Comment by Stalker012345** [comment]
9 cities (so 45% penalty I believe, which would do it).

I always forget that because tourism yields work differently than everything else. I wish the base yields were static like science and culture...and then the culture thresholds needed for each level was increased by the modifier.

**Comment by LoneGazebo** [comment]
that's the bogey.
