### ISSUE TITLE
3/15 - Weird unhappiness values

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6413]
_1. Mod version (i.e Date - 3/15):_ 3/15

_2. Mod list (if using Vox Populi only, leave blank):_
Improved city view v11

_3. Error description:_ 
I'm observing strange things involving unhappiness values in cities. For instance in the below screenshots - the unhappiness of the city remains the same whether working a laborer or a town. Working the town lowers the unhappiness from distress and poverty but raises unhappiness from illiteracy and culture boredom. The needs factors and modifiers are unchanged. Where is this unhappiness coming from? Intended?

Note that the "actual unhappiness" from culture is 3, and reduced by 0, yet the observed unhappiness is either 0 or 1. I am observing this in many other cities, where there is high "actual unhappiness" particularly for illiteracy or culture, zero reduction, and yet the observed unhappiness is lower or zero. 

![laborer](https://user-images.githubusercontent.com/59859911/77805213-bfc44c80-7057-11ea-85dc-0b5738367c88.png)
![town](https://user-images.githubusercontent.com/59859911/77805221-c2bf3d00-7057-11ea-9ef0-a437492a4da7.png)

After growth and library:
![image](https://user-images.githubusercontent.com/59859911/77805927-9d333300-7059-11ea-846e-a1654f0fd197.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
Everything is intended, look over the explanations in my issue  #5545.

**Comment by silentreply** [comment]
@Aqinu Thanks for the info!
