### ISSUE TITLE
God of Commerce not giving faith on trade routes

### ISSUE THREAD

**Issue by legenciv** [LoneGazebo/Community-Patch-DLL#6415]
_1. Mod version (i.e Date - 3/15):_
3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_
34UC

_3. Error description:_ 
Sending trade routes is not granting 2 faith, neither on the city, nor on the capital.

**Comment by crdvis16** [comment]
It's also not working for trade routes sent to your city from another civ (though I'm not 100% sure it's supposed to give faith in that instance).
