### ISSUE TITLE
Killing using city bombard grants instant yield to all cities

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#6417]
_1. Mod version (i.e Date - 3/15):_
3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When city bombard kills a unit, the instant yield kill bonus from Authority is granted to every city. Expected: should only be granted to the city which killed the unit.

_4. Steps to reproduce (optional):_
Go Authority, kill unit with city bombard.

**Comment by HungryForFood** [comment]
![Before bombard](https://i.imgur.com/tN10QqU.png)
![After bombard](https://i.imgur.com/HzHYeoZ.png)

**Comment by LoneGazebo** [comment]
Terracotta Army?

**Comment by HungryForFood** [comment]
I have a Terracotta, but the yields given to all cities is from Authority.

**Comment by Mileslewis** [comment]
Seems like this happens only when you use city bombard to kill units OUTSIDE your territory. Have seen the same thing with the acropolis culture bonus for killing units applying to all cities.
