### ISSUE TITLE
England Ship of the line(range naval) receive Breacher Promotion(melee promotion)

### ISSUE THREAD

**Issue by Cat-du-Fromage** [LoneGazebo/Community-Patch-DLL#6418]
_1. Mod version (i.e Date - 3/15):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
England Ship of the line receive Breacher Promotion, which is useless for a rangenaval type

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/46396184/77846766-9a9b1f80-71b8-11ea-8e82-5fef8506500b.png)

**Comment by azum4roll** [comment]
It's intended.

**Comment by Stalker012345** [comment]
Even though its normally a melee promotion, its benefit do work on the SOL.

**Comment by Cat-du-Fromage** [comment]
from my last game, destroying an enemy ship with a ship of the line didn't apply damage to boats around my boat
