### ISSUE TITLE
3/15 (Tactical AI) - Carriers get way too close to enemy forces

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6421]
_1. Mod version (i.e Date - 3/15):_
3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
While the AI carrier use has improved markedly, it still has a bad tendency to bring its carriers far too close...making them easy targets. In this example, fleet aside, a carrier should never get within a city's firing range....that just should just be a hard run.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/77977523-8729aa80-72c5-11ea-9d29-cc388aba6e25.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
yeah i know. it's on the list
