### ISSUE TITLE
AI putting crazy production into World Projects

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6423]
_1. Mod version (3-1) most recently happened on this but happened to me on version before this also.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Twice now In games where I have had the highest production an AI Civ has managed to put triple my production into a world project (World's Fair/Global Wargames) in one turn. When I had a look around on In Game Editor I couldn't see any way they managed this as they didn't even have great engineers. Both games were on Deity.

_4. Steps to reproduce (optional):_
Not really sure as most of the time the numbers seem completely normal and then sometimes they are just way above. I would guess it has something to do with Deity. Also I had suspicions that it is related to doing processes (Science/Wealth/Farming) in a city and then switching to the project but I could not recreate this myself and have seen Civs do this but still have normal numbers.

---------------------------
Supporting information:
Zip File contains one save file from (3-1) version and one from (12-20) where this happened.
Also screenshots of the results. (Bear in min I was top production in both these games and put my production into the projects.)

[Worlds Project Issue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4415569/Worlds.Project.Issue.zip)

Also video of both these happening are on youtube
https://www.youtube.com/watch?v=IRsSUkKDQto (38:50)
https://www.youtube.com/watch?v=t7CQ-_pKXY0 (19:50)

**Comment by silentreply** [comment]
This happens frequently and usually involves temporary AI bonuses such as from entering a new era. However I find it unusual that at least one AI manages to do this every WC project. I don't know if the AI is actually "aware" it will receive such bonus and times it accordingly. 

In the 3-1 example, Morocco had just entered Atomic era and received a large production bonus. However I am surprised it is so large - around 20,000 hammers. Seems unusually high. Multiple players have observed that Morocco AI tends to runaway more frequently than other AI civs, perhaps there is a connection... 

In the 12-20 example, I saw that Poland founded their corporation the previous turn which I believe grants a bonus - albeit smaller than the era bonus.

**Comment by Mileslewis** [comment]
Well in the Poland one they built the Corporation after the Worlds Fair in the same turn due to the (potential) bug I mentioned in the next issue so technically the corporation came after.

Also these are AI only bonuses right? Is there a place to see what bonuses AI are getting? I honestly have no idea but if they really are getting 4 or 5 times the production of their whole empire as bonuses they seem pretty excessive.

Does this issue only happen on deity or all difficulties?

Potential solution could be to not allow bonus yields to go into World Projects (or cap the contribution to the cities production).

**Comment by Omen-of-Peace** [comment]
I agree it's annoying, but it's not a bug. If there was some way to store this production instant bonus and not apply it to projects (only afterwards), it'd be nice.

Info about AI bonuses is on:
https://civ-5-cbp.fandom.com/wiki/AI_and_Difficulty

It happens on all difficulties but the bonuses increase sharply with difficulty level.

**Comment by Mileslewis** [comment]
Yea thanks, must've been the new era bonuses and bad luck on the timing. Ngl though I really don't see the reason for these A/B/C bonuses (especially to production) instead of just giving AI comparable percentage bonus to yields. I guess that's probs a discussion for the forum rather than here.
