### ISSUE TITLE
Another slight Issue with World Projects

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6424]
_1. Mod version (3-1) But has been like this for a while

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ If you put a World Project at the top of a queue and put another thing below it. On the turn where the project is finished you will put production into the world project but then also get it on the other thing in the queue. It's possible this could be intended though.

_4. Steps to reproduce (optional):_

**Comment by LoneGazebo** [comment]
It's an overflow catch, is fine.
