### ISSUE TITLE
3/15 (Iteroi Religion DLL) - Can't make TRs with most CS

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6425]
_1. Mod version (i.e Date - 3/15):_
3/15 (using Iterois no pressure DLL)….but I believe I have this on regular 3/15 as well.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Sometimes in the game I just cannot make TR with legal CS, even when I am very close. I've ruled out the usual suspects (city state sanctions, I already have TR with them).

Otherwise I can make TR fine with other civs or myself, its just CS.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
ah, i think i might know the reason ... are you friends or allied with the ones where it works and not with the others?

**Comment by Stalker012345** [comment]
No, allied with ones where it works and ones where it doesn't.

**Comment by ilteroi** [comment]
hmm. screenshot?
