### ISSUE TITLE
Request for Help: Per City + Instant Yield logging for Balance Test

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6426]
Special Request:

I want to do a test to determine the effectiveness of midgame expansion. This will test the balance of the pioneer as well as midgame expansions in general (aka do they truly pay for themselves all said and done). Effectively I am going to log the various yields that my empire is getting compared to the new city, and confirming if the city is overall a net benefit or drain to the overall empire...as well as what turn that switch from bane to boon occurs.

I am happy to run the test and analysis, but I could use some help collecting the metrics. Would any of you wonderful people be able to whip me up something that could log each cities yields per turn, as well as the instant yields per turn? It only has to be for the human player, but if its easier to do it for all players I can probably work with that.

The main yields I am looking at are:

1) Culture
2) Science
3) Gold
4) Production
5) Happiness (the happy number and the unhappy number)

I'll take any others if its easier, but those are the only yields I need.
If someone is willing to do that for me I would greatly appreciate it.
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Cat-du-Fromage** [comment]
i unfortunately don't have the numbers with me, from our multiplayer game, we used to conclude that if you don't have at least 2 caravan/cargo ship to help your pioneer's city your empire would sink. pioneer's city comes with so few buildings it causes a massive unhappiness (poverty,illitracy,etc..) and make fealty's social policy (+33% interne caravan stronger) a must have.

I buff them now with a personnal modmod to give them all buildings from ancient to classical era, this way one caravan is needed.

with this modmod my logs will not be revelant for your data but if you desire i can post the log from our current game?

**Comment by Stalker012345** [comment]
> i unfortunately don't have the numbers with me, from our multiplayer game, we used to conclude that if you don't have at least 2 caravan/cargo ship to help your pioneer's city your empire would sink. pioneer's city comes with so few buildings it causes a massive unhappiness (poverty,illitracy,etc..) and make fealty's social policy (+33% interne caravan stronger) a must have.
> I buff them now with a personnal modmod to give them all buildings from ancient to classical era, this way one caravan is needed.
> with this modmod my logs will not be revelant for your data but if you desire i can post the log from our current game?

That's kind of you, but my goal is to do a clean test run. Thank you for the offer though:)
