### ISSUE TITLE
Game Freezes on start up

### ISSUE THREAD

**Issue by myles1718** [LoneGazebo/Community-Patch-DLL#6428]
_1. Mod version (i.e Date - 3/15):_
VP 3 -15-2

_2. Mod list (if using Vox Populi only, leave blank):_
vp 1 - 9

_3. Error description:_ 
game freezes after loading on turn 1

_4. Steps to reproduce (optional):_
Reinstalled civ 5 and verified

[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4420946/Database.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4420948/Lua.zip)
[xml.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4420949/xml.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4420950/CvMiniDump.zip)

Reinstalled VP
deleted cache and mod data

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
have you tried the latest version?

**Comment by Reefpix** [comment]
Have what sounds to be the same problem.

Was running 7-29-1 fine, then had a crash, and upon restart, any new Vox game freezes at turn 1 before any actions.

Tried uninstalling Vox, verifying Steam files, reinstalled 3-15-2 and still get the same problem.

I have tried:

[1] Starting a vanilla game, no problem here.
[2] Starting a Vox game with different parameters including one that worked before, still freeze on load.

I'll try reinstalling with 7-29-1 and see if it helps but it did present the same error originally. And I'll try to get some log files.

**Comment by Reefpix** [comment]
Update:

[1] Same error with 7-29-1
[2] Forgot to say before that I am have no other mods installed.
[3] Log files:
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4431379/xml.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4431380/Database.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4431381/Lua.log)

**Comment by AllofHumans** [comment]
I was having this problem as well, where the game freezes as soon as I click the "Begin your journey" button.
 
I tried reinstalling VP, clearing cache, and deleting other mods. I also reinstalled civ and tried with the legacy version of the game I noticed that, **at least for me, this is a problem with all civ 5 mods**, not just VP.

I am using the version with eui, including parts 1-7  (7-29-1) , as installed by the automatic installer.

From a quick glance at the log files, mine seem similar to other users', but here they are:
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4433054/Database.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4433055/Lua.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4433056/xml.log)

Dump:
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4433064/CvMiniDump.zip)

**Comment by AllofHumans** [comment]
Update: I reinstalled civ 5 (again) and deleted the entire civ 5 folder in /documents/my games. This seems to have fixed the problem - It seems like some of the game files were corrupted there, causing all mods to fail.
