### ISSUE TITLE
3/15 - Naval units sharing tile with embarked unit from different civ?

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6429]
_1. Mod version (i.e Date - 3/15):_ 3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Can not attack this naval unit because there is an embarked unit from another civ I am not at war with on that tile. Should they even be able to share this tile in the first place?
![image](https://user-images.githubusercontent.com/59859911/78340544-48655000-7564-11ea-90aa-f6a3cbf165eb.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Isn't this always been possible?
