### ISSUE TITLE
3/15 - Combat RCS calculation error

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6431]
_1. Mod version (i.e Date - 3/15):_
3/15 (Iteroi Religion DLL)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Considering the combat bonuses of my light tank, it should have well over 100 RCS in this attack.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/78457590-f4945d00-7670-11ea-950d-6948440a701b.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Some of the bonuses on the right side for the defender actually factor into the left side calculation in the DLL.

**Comment by Stalker012345** [comment]
So the UI is in error then and the bonuses should be shifted?
