### ISSUE TITLE
Unused values in DifficultyMod.xml

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6432]
There are a number of unused values for each handicap entry in DifficultyMod.xml:
```
			<StartingLocPercent>0</StartingLocPercent>
			<AdvancedStartPointsMod>0</AdvancedStartPointsMod>
			<AIAdvancedStartPercent>0</AIAdvancedStartPercent>
			<NumCitiesUnhappinessMod>100</NumCitiesUnhappinessMod>
			<TechTradeKnownModifier>0</TechTradeKnownModifier>
			<NoTechTradeModifier>0</NoTechTradeModifier>
			<AIWorldTrainPercent>100</AIWorldTrainPercent>
```
And a further two that are commented out:
```
			<!--<InflationPercent>100</InflationPercent>-->
			<!--<AIInflationPercent>100</AIInflationPercent>-->
```

Is it necessary to have an entry for these in each DifficultyMod.xml handicap? They all have default values in the table, don't they? DifficultyMod.xml doesn't change them, since they're unused.

**Comment by LoneGazebo** [comment]
They don’t do anything yes, but their memory impact is negligee.

**Comment by LoneGazebo** [comment]
Negligible. Whatever sexy phone.

**Comment by HeathcliffWarriors** [comment]
@LoneGazebo Right, but since they have a default value anyway, is an entry for each of them needed in DifficultyMod.xml? Why not just remove them from the file?

**Comment by HeathcliffWarriors** [comment]
The reason I'm asking is that when I asked this in 2017, you said it was fine to rearrange the order of the rows as long as none of them were missing. :)

**Comment by HeathcliffWarriors** [comment]
i.e. 
![286a81b1731070b1ce004b7d58b40ac2](https://user-images.githubusercontent.com/38794241/78462889-b87aef80-76a4-11ea-8812-975437770a9c.png)

**Comment by HeathcliffWarriors** [comment]
New file is used in the 4-7 version, no issues.
