### ISSUE TITLE
Victory Progress screen doesn't include VP-added score elements

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6435]
![upload_2020-4-3_23-48-49](https://user-images.githubusercontent.com/38794241/78469607-da01c880-76f0-11ea-9d45-f058d16c7937.png)

**Comment by nobubblegums** [comment]
@RecursiveVision which elements are needed to be included in here, I may give it a try

**Comment by RecursiveVision** [comment]
@nobubblegums Mouse over the score for any player to get the breakdown, compare with the list for score victory to see what's missing
