### ISSUE TITLE
AI seems to avoid building cities on tundra (loosing his monopoly ressources)

### ISSUE THREAD

**Issue by Cat-du-Fromage** [LoneGazebo/Community-Patch-DLL#6439]
_1. Mod version (i.e Date - 3/15):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Every time an AI got a tundra start they avoid tundra as much as they can, in some instance they even limit their number of cities if there is too much tundra

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/46396184/78548196-aada7c80-7800-11ea-81e8-f45f14c070bc.png)

**Comment by ilteroi** [comment]
well indeed monopoly & belief bonuses etc are not considered. but then it's still early in the game

**Comment by LoneGazebo** [comment]
I think monopoly resources are considered, but not the bonuses, just the presence of resources that would lead to a monopoly.

**Comment by Cat-du-Fromage** [comment]
this place will never be settle, the AI did have the ressources when cities began taking the 4th tile around. but they really don't want to settle on tundra.

**Comment by ilteroi** [comment]
i agree there is space for at least 2 cities there.

the AI will also ignore spots which are "bad" compared to a certain threshold which is computed once after map generation. maybe that is to blame ...
