### ISSUE TITLE
Patch release with latest fixes for 3/15

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6440]
with gazebo ooo, i though it would be a good idea to do an intermediate patch release.

so here is a new build which goes on top of the 3/15 release (commit id a5addaf8).

[patch-vp-20200315-to-20200407.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4443663/patch-vp-20200315-to-20200407.zip)

this includes some fixes from me and a lot of diplomatic improvements from hcw, but no changes to religion spread mechanics.

can somebody please create a thread for this in the forum?

**Comment by HeathcliffWarriors** [comment]
@ilteroi Done.

https://forums.civfanatics.com/threads/new-beta-patch-april-7th-4-7.656818/

**Comment by bigcat88** [comment]
That issue that someone report with embarked pathfinding with sight one - is a problem

**Comment by ilteroi** [comment]
new build is here ... commit 7cbd11ae

[patch-vp-20200315-to-20200409.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4458411/patch-vp-20200315-to-20200409.zip)

**Comment by HeathcliffWarriors** [comment]
@ilteroi Can't find commit 7cbd11ae in any of the branches; not sure what's included. Mind linking it?

**Comment by ilteroi** [comment]
yeah i forgot to push apparently. also i just updated the dll for simplicity

**Comment by HeathcliffWarriors** [comment]
But your patch folder already contains replacement database files...I don't see the simplicity :)

**Comment by HeathcliffWarriors** [comment]
Anyway, if it has the new DLL I can post that on the forums.

**Comment by HeathcliffWarriors** [comment]
@ilteroi Posted...could you push your code? Would like to run a few tests on AI approach, I saw too much passive behavior in a test game.

**Comment by ilteroi** [comment]
it's done ...

also, here's the result of my test game, don't know if it's related to your changes, but augustus was absolutely ruthless:
![image](https://user-images.githubusercontent.com/1358966/78999142-527de480-7b4a-11ea-8e74-70d758f29631.png)

**Comment by HeathcliffWarriors** [comment]
Interesting - feedback on the forums and my own experience was indicating there was too little AI aggression in the earlier part of the game, but clearly performance in the late game is alright, at least for leaders with a high WAR bias. Anyhow, I've made some adjustments to make AI aggression more strategic, and I'll play a game myself to test it out.

**Comment by ilteroi** [comment]
another day, another patch!

[patch-vp-20200315-to-20200412.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4466090/patch-vp-20200315-to-20200412.zip)

this includes the program database (PDB) so hopefully we can get stacktraces for crashes. everybody who experiences a crash, please check callstack.log and create a ticket here.

**Comment by bigcat88** [comment]
looks like it is not savegame compataible...

**Comment by HeathcliffWarriors** [comment]
It isn't, I stored IsEasyTarget in memory.

**Comment by bigcat88** [comment]
Idea:
_Next time reserve for future use 10,20,30 variables and in new version just use them_

**Comment by LoneGazebo** [comment]
It's fine, I'm hoping to return to service this week, will put out a new version then.
