### ISSUE TITLE
Golden Age Difficulty Bonus grants Golden Age Points?

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6442]
Considering it grants every other yield, I think we could lose the GAP on it - it's superfluous and contributes to a feedback loop. I know it's minor and "if it ain't broke, don't fix it", but it just bugs me. :)

**Comment by bentakacs** [comment]
Wait, it does? I thought GA "only" increase culture and prod by 20%, and it adds +1 Gold to every gold tiles. It does more than these?

**Comment by HeathcliffWarriors** [comment]
Not the GA itself - the AI handicap bonus from entering a Golden Age.
