### ISSUE TITLE
3/15 - Guerilla warfare tenet does not provide XP bonus

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6443]
_1. Mod version (i.e Date - 3/15):_ 3/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
XP bonus for units in friendly territory from guerilla warfare tenet (Order tier 1) does not seem to be working. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by phantommaxwell** [comment]
If I recall correctly, for a Melee Unit to be in "Friendly Territory", the Unit they are attacking must also be in Friendly Territory.  For Ranged Units, it doesn't matter where the Enemy is as long as the Ranged Unit is in Friendly Territory for the XP bonus.

**Comment by silentreply** [comment]
I believe that is correct, but it's currently not giving bonus XP under any circumstance.
