### ISSUE TITLE
4-17 - Boarded status effect occasionally not being applied to naval units 

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6445]
_1. Mod version (i.e Date - 3/15):_ 4-17-2, 3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm occasionally observing the boarded status effect not being applied to enemy naval units. It seems to only occur situationally. The blue text shows up indicating the effect has been applied but the movement does not seem to be decreased. The red status effect icon does not appear.
![image](https://user-images.githubusercontent.com/59859911/78788478-dd5bb500-7979-11ea-9787-4257b4cdaca8.png)
![boarded bug](https://user-images.githubusercontent.com/59859911/78788489-e3ea2c80-7979-11ea-8b3c-dac1be2f23a1.png)

Edit: At first seemed to occur only with units with blitz promotion, but now I am seeing it more widespread, even when I am the one attacking an enemy unit that should be giving my unit boarded effect.

![boarded bug2](https://user-images.githubusercontent.com/59859911/78899724-cbdedf80-7a43-11ea-8aa6-d3124e07e58b.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Do they have the 'Indomitable' promotion? 
+25% [ICON_STRENGTH] Combat Strength when defending.[NEWLINE]Immune to the [COLOR_POSITIVE_TEXT]Boarded[ENDCOLOR] effect from Naval Melee units.

**Comment by silentreply** [comment]
In all of the cases above, it is strictly melee vs melee, so they do not have indomitable. I do remember instances where boarded effect did not appear to be applied to ranged ships (without indomitable) however.

**Comment by silentreply** [comment]
This bug is still active in 4-17-2. Both of these corvettes attacked an enemy caravel, one received boarded effect, the other did not. Neither have promotions granting immunity to boarded. 
![image](https://user-images.githubusercontent.com/59859911/80289131-b5ef4100-870a-11ea-9288-10aa84745b0e.png)
