### ISSUE TITLE
Netherlands doesn't receive monopoly bonuses from imports

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6446]
_1. Mod version (i.e Date - 3/15):_ 4-7 Patch

_2. Mod list (if using Vox Populi only, leave blank):_ Quick Turns / Religious Icons

_3. Error description:_ I'm importing all of Germany's Copper, which should give me a global monopoly, but I'm not receiving the +10% Production bonus in all cities, nor did I get the monopoly notification.

![Screenshot (507)](https://user-images.githubusercontent.com/38794241/78806604-e4da8880-7990-11ea-9c27-d242adb6c02a.png)
![Screenshot (508)](https://user-images.githubusercontent.com/38794241/78806605-e5731f00-7990-11ea-9a15-0b1423af49a8.png)

**Comment by silentreply** [comment]
Bummer :( I was planning on playing Netherlands for my next game. Sea Beggars are insane right now.

**Comment by bigcat88** [comment]
Intended if someone has more % then you.

**Comment by HeathcliffWarriors** [comment]
Oh, that makes sense. Thanks. :)
