### ISSUE TITLE
Governor starves city when Production focus enabled

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6447]
_1. Mod version (i.e Date - 3/15):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ With Production focus enabled and nothing locked, the governor starves my city of Utrecht, even though there are abundant Food tiles available.

![Screenshot (525)](https://user-images.githubusercontent.com/38794241/78807014-79dd8180-7991-11ea-814d-954da0a82ea3.png)

**Comment by Stalker012345** [comment]
Yep I've seen it to.

**Comment by AmusingThrone** [comment]
I face this problem as well.

**Comment by AmusingThrone** [comment]
@LoneGazebo Sorry to bump this, but I think this is still an issue. What version was this fixed on?

**Comment by LoneGazebo** [comment]
this upcoming version
