### ISSUE TITLE
(4-7) Embarked units strange movement

### ISSUE THREAD

**Issue by XplosiveLun** [LoneGazebo/Community-Patch-DLL#6448]
_1. Mod version: (4-7)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Embarked units cannot move into hex outside vision range (should be player-only). They either consider the destination hex as obstacles (like moving a unit into mountain) or detour to disembark and then embark again.

![image](https://user-images.githubusercontent.com/12179253/78853933-b1603280-7a52-11ea-9bf2-3f567d9b15b3.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by randomnublet** [comment]
Related to this: embarked unit can't disembark and attack with the last movement point on this tile (possibly because I had no visibility at the turn start?)

![civdisembarkattack](https://user-images.githubusercontent.com/53142313/78876543-c8e9ec00-7a4f-11ea-91d3-59806f17ea89.png)

**Comment by ilteroi** [comment]
both fixed ...
