### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6450]
3-15

Game crashing during AI (Gandhi) turn.

[Alexander_0058 BC-1680 ctd.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4454740/Alexander_0058.BC-1680.ctd.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4454742/Logs.zip)

**Comment by randomnublet** [comment]
I tried to replay some turns and it always strikes on the same India turn (t58, maybe related to founding religion)

**Comment by randomnublet** [comment]
Ops sorry it's actually the 4-7 version

**Comment by ilteroi** [comment]
sorry, can't load the save ...

**Comment by randomnublet** [comment]
Damn, are you trying it under the 4-7 build?

I only run VP

![civmodlist](https://user-images.githubusercontent.com/53142313/78911249-5a745080-7a86-11ea-9280-ea75c40de775.png)

**Comment by ilteroi** [comment]
how should i say, it's surprising that savesgames work at all sometimes, the code is just so insane. not your fault but annoying and unfortunately unfixable

**Comment by adaneslavo** [comment]
I also experience various CTDs, but didn't have time to test if the cause is IGE or some modmods I playtest. The religion can be the reason, because I gave enough faith to 2 nations and next turn got crash.

**Comment by ilteroi** [comment]
i just meant to say that serialization is broken, but people can at least load their own saves, so it's playable

**Comment by HeathcliffWarriors** [comment]
@ilteroi What causes the broken-ness? Is it truly unfixable or just not feasible to change at this point?

**Comment by ilteroi** [comment]
we don't have the complete source code ... and it would be a gigantic effort

**Comment by adaneslavo** [comment]
What I can suggest (and this is really serious) is going back to **1-11** and starting over again. I played dozens of playtests, with bunch of mods, and I was doing lots of IGE mambo-jumbo and had NO crash at all. Even when there were bugged versions in February and March, I was still using **1-11**. If you cannot find the source of the mess (I know lots of people add their stuff that can break the mod) this can be really good solution. Then try to clean issues and then add some new stuff. At least you will be sure that VP is working...

**Comment by adaneslavo** [comment]
Got crash with bunch of mods. What logs/dumps do you need? Where do I find minidump?

**Comment by ilteroi** [comment]
sorry the minidump doesn't match my build ... weird. also mine was 4-9 not 4-10, so maybe hcw made that one?

anyway, @all: it would be great if we could ship the PDB file as well in the future, then the Callstack.log file wouldn't be empty when we get a crash report. much easier to handle than a minidump.

**Comment by adaneslavo** [comment]
I used this build:
https://forums.civfanatics.com/threads/new-beta-patch-april-7th-4-7.656818/page-3#post-15728029

**Comment by adaneslavo** [comment]
PDB file? Never heard of... Where can I find it?

**Comment by ilteroi** [comment]
no worries, you only get it when you build the dll yourself.

**Comment by adaneslavo** [comment]
I loaded today the same save, but unfortunately about 10 turns before crash, because I had autosave configured that way. Now I change it one save each 2 turns. And I cannot reproduce that! I played about 100 turns past this moment and nothing.

**Comment by HeathcliffWarriors** [comment]
@ilteroi I posted the DLL on the forums from your patch folder - I just called it 4/10 because the current date was 4/10. It's your build, not mine.

**Comment by ilteroi** [comment]
then i don't understand why i cannot load the minidump but anyway let's try a different way.

https://github.com/LoneGazebo/Community-Patch-DLL/issues/6440#issuecomment-612585906
