### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6454]
4-10 dll

[AutoSave_0047 BC-2120.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4462019/AutoSave_0047.BC-2120.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4462023/Logs.zip)

**Comment by ilteroi** [comment]
do you have a minidump?

**Comment by randomnublet** [comment]
what's that? :D

**Comment by ilteroi** [comment]
in the folder where civ5.exe is located you should have a file called CvMinidump.dmp which some information about what was happening when it crashed. Please reproduce the crash and post it here.

**Comment by randomnublet** [comment]
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4464542/CvMiniDump.zip)

**Comment by bigcat88** [comment]
**offtop**
@ilteroi what branch I need to build to get your dll?

**Comment by ilteroi** [comment]
all my stuff is in the "ole" branch ...

anyway, these minidumps are unfortunately hard to handle ... let's try a different way.

https://github.com/LoneGazebo/Community-Patch-DLL/issues/6440#issuecomment-612585906
