### ISSUE TITLE
3/15 - Low instant yield from great engineer?

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6455]
_1. Mod version (i.e Date - 3/15):_ 3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Not sure if this is actually a bug, but there seems to be very low yield for hurry production from great engineer. I'm getting 855 production here, which is not even enough to build an arsenal (980 production). The city is already producing 528 per turn.  

![image](https://user-images.githubusercontent.com/59859911/79018613-3f671680-7b42-11ea-8179-40d32a151acd.png)

I see that the ability text says "every owned manufactory **_you've created_** increases the amount of production gained by 20%. I take it this means only manufactories that you built, and not conquered, apply bonus production? I have built 4 (own 11), and have the industry policy that gives an additional +25%. From my understanding I should be getting +105% yield. That would make the base yield around 400 hammers, or 40% of an arsenal. This seems very insignificant. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by silentreply** [comment]
Scientist yield also seems pretty low. I have created 6 academies, so +60% yield for total of 7505 science. Thats only 5 turns of science in this situtation, less than half the cost of a modern era tech.


![scientist yield](https://user-images.githubusercontent.com/59859911/79024444-f074ad80-7b50-11ea-8da4-a4acc66bc3a7.png)

**Comment by psparky** [comment]
For production, I believe the calculation is ((Pop*20 + 100) *1.8) *1.25

1.8 for 4 manufactories at .2 each, 1.25 for policy. Unusually, the policy bonus is applied to the whole total in this case - most are additive.

14*20 = 280+100 = 380*1.8 = 684*1.25 = 855

Would be higher in a city with more pop....

For science, I believe it's based on the science from cities in the last 5 turns (so trade routes and some other bonuses don't count). Looks a little low, but probably OK, especially if your science recently increased.

**Comment by silentreply** [comment]
@psparky Thanks for the formula!

However I'm still seeing very low yield much later in the game, this time it's 800 regardless of the city, even the capital with 40 pop.

![engineer yield](https://user-images.githubusercontent.com/59859911/79176214-9e8c8b80-7dcd-11ea-97b1-4207a3f20033.png)

**Comment by psparky** [comment]
Perhaps the amount is now fixed on birth, although I don't recall that changing if so. Would that make sense in your example?

**Comment by Stalker012345** [comment]
I also notice my late game GS give about 5 turns of tech on a bulb....but honestly I think that's WOI. GS bulbing was recently weakened because it was crazy....I was blitzing through techs because late game you get a lot of GS.
