### ISSUE TITLE
3/15 - Artistry policy grants GA points for building refineries 

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6456]
_1. Mod version (i.e Date - 3/15):_ 3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Artistry policy "Heritage" (golden age points for constructing world or national wonders) grants GA points for building refineries. I'm guessing that refineries are classified under "national wonders" as a workaround to limit you to building 5 of them.

![image](https://user-images.githubusercontent.com/59859911/79802960-06435900-832f-11ea-8537-1eee9e45ca75.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by silentreply** [comment]
Just an update on this issue; I believe it is related to the Artistry policy "Heritage" which grants golden age points for constructing world or national wonders. I'm guessing that refineries are classified under "national wonders" as a workaround to limit you to building 5 of them.

**Comment by LoneGazebo** [comment]
Intended, as limited buildings are technically national wonders.
