### ISSUE TITLE
CS Quest "Road between our Capitals"

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6457]
I'm glad this quest takes in consideration sea connection through lighthouses, but its implementation has one quirk: it doesn't work if you're not allied already, or there's something else weird happening.

In my current game, my inland capital is connected with a road to a secondary city that has a lighthouse. CS itself built a lighthouse (sea tile yields changed accordingly and I can see the little building on the map). There's a clean path of revealed sea tiles between the two cities, still the quest isn't fullfilled. I even stationed a 'Scouting 2' Scout next the CS to have visibility of its territory just to try one more thing.

As soon as I become its ally through a different quest, the road quest triggers as well.

**Comment by LoneGazebo** [comment]
I think it is because of how open borders work...

**Comment by LoneGazebo** [comment]
@ilteroi can we check OB code for minors with regards to pathfinding?
