### ISSUE TITLE
Make Event Choice - event does not pop up, cannot make choice, cannot advance game

### ISSUE THREAD

**Issue by choraltrickster** [LoneGazebo/Community-Patch-DLL#6458]
_1. Mod version (i.e Date - 3/15):_
Laast night I installed the VP as Modpack installation (pictured). During installation I had some filenames that were too long and had to skip. I enabled long file names in my Win10 registry, and reinstalled, but the problem persisted (due to x86 maybe?) If there's a fix for this can you please share a link? Thanks!

_2. Mod list (if using Vox Populi only, leave blank):_
no mods chosen, but VP modpack is installed:
- Mods_CP_2020-02-09
- Mods_CP_2020-02-09_EUI
- Mods_VP_2020-02-09_EUI
- Mods_VP_2020-02-09_Improved-Interface
- Mods_VP_2020-02-09_Magnus-Mutatio

_3. Error description:_ 
Make Event Choice - event does not pop up, cannot make choice, cannot advance game, cannot force turn end; stuck

_4. Steps to reproduce (optional):_
tried reloading previous turns--does not provide a different outcome

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4464981/xml.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4464982/Lua.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4464983/Database.log)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
https://drive.google.com/open?id=1LKtkFfLwrTif1Y8s7UtnpHzNOycWUBEK

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![2020-04-11 12_39_31-Sid Meier's Civilization V (DX9)](https://user-images.githubusercontent.com/61171515/79049674-08047280-7bf3-11ea-8ecc-ad9258bd4bb6.png)
![2020-04-11 12_40_20-Sid Meier's Civilization V (DX9)](https://user-images.githubusercontent.com/61171515/79049675-09ce3600-7bf3-11ea-8d93-e468f298fcd0.png)
![2020-04-11 12_41_06-Window](https://user-images.githubusercontent.com/61171515/79049676-0aff6300-7bf3-11ea-9868-0eff3c332d2c.png)
![2020-04-11 12_45_10-Sid Meier's Civilization V (DX9)](https://user-images.githubusercontent.com/61171515/79049677-0b97f980-7bf3-11ea-9b87-66355f207f42.png)

**Comment by ElliotS-1** [comment]
Same issue, using a modpack but no long filenames or mods other than base VP. Too bad, game was going well too. Tried saving/loading from previous turn and same turn. Tried restarting. Nothing.
![20200527115132_1](https://user-images.githubusercontent.com/24664752/83049396-b84a0100-a010-11ea-9ba0-5da9f3da6d8f.jpg)

**Comment by Lesdebian** [comment]
11th July 2020 - I'm still getting this issue. I have Vox Populi 5.6.19 EUI with Strange Religions, Historical Religions (MP_MODSPACK), Redesigned Colours and Icons 3.0 (RCI, distributed as it's own modpack). Turn 54 as the Huns and I've got the exact same problem. I made the modpack myself.

**Comment by LoneGazebo** [comment]
I see a few LUA errors in your log - unfortunately I can't debug modpacks.
