### ISSUE TITLE
TIL - analysing minidumps with windbg

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6459]
since visual studio is a bit picky with minidumps i googled a bit and it seems there is a way to get useful information out of a minidump even if the vs debugger refuses to load it, so here's a PSA:

* open the minidump in windbg (using ctrl+d) and enter the following commands
* .sympath \path\to\VP\BuildOutput\Release (or wherever the most closely matching pdb is located)
* !sym noisy (optional but shows whether the next command succeeds)
* .reload /i (the /i is the important thing!)
* .ecxr
* k (no period this time)

you should now see the callstack and the line in the source where the exception happened!

using the call stack window you can also walk up and down the stack. i'm sure windbg can do even more awesome things but that's enough for a start ...

**Comment by ilteroi** [comment]
some example results:

a7a5f450 9a8ad2b1 CvGameCore_Expansion2!CvTacticalAI::GetNextZoneTarget+0x4f [d:\sources\civ-vp\cvgamecoredll_expansion2\cvtacticalai.cpp @ 3560]
a7a5f530 9a8ae964 CvGameCore_Expansion2!CvTacticalAI::IdentifyPriorityTargets+0x461 [d:\sources\civ-vp\cvgamecoredll_expansion2\cvtacticalai.cpp @ 3207]
a7a5f58c 9a8b95a8 CvGameCore_Expansion2!CvTacticalAI::FindTacticalTargets+0xa34 [d:\sources\civ-vp\cvgamecoredll_expansion2\cvtacticalai.cpp @ 929]

unfortunately not clear what the problem is here?
	while(m_iCurrentTargetIndex < (int)m_ZoneTargets.size())
	{
		if (m_ZoneTargets[m_iCurrentTargetIndex].GetLastAggLvl() <= eMaxLvl)

//-----------

7911f70c 64b28588 CvGameCore_Expansion2!std::vector<int,std::allocator<int> >::_Xran+0x5b [c:\program files (x86)\microsoft visual studio 9.0\vc\include\vector @ 1265]
7911f750 64b28876 CvGameCore_Expansion2!CvDiplomacyAI::CalculateMedianNumWondersConstructed+0x128 [d:\sources\civ-vp\cvgamecoredll_expansion2\cvdiplomacyai.cpp @ 15663]
7911f77c 64b2a0f6 CvGameCore_Expansion2!CvDiplomacyAI::IsPlayerWonderSpammer+0xa6 [d:\sources\civ-vp\cvgamecoredll_expansion2\cvdiplomacyai.cpp @ 15804]
7911f79c 64b2acac CvGameCore_Expansion2!CvDiplomacyAI::GetWonderSpammerScore+0x16 [d:\sources\civ-vp\cvgamecoredll_expansion2\cvdiplomacyai.cpp @ 42541]
7911f7d8 64b2fe0e CvGameCore_Expansion2!CvDiplomacyAI::GetMajorCivOpinionWeight+0x69c [d:\sources\civ-vp\cvgamecoredll_expansion2\cvdiplomacyai.cpp @ 3642]
7911f7f0 64b43c1b CvGameCore_Expansion2!CvDiplomacyAI::DoUpdateOnePlayerOpinion+0x8e [d:\sources\civ-vp\cvgamecoredll_expansion2\cvdiplomacyai.cpp @ 3414]

offending line seems to be 
	fMedianNumWonders = ((viWonderCounts.at(iElement) + viWonderCounts.at(iElement+1)) / 2);

@hwc you're playing fast and loose with data types and indices here ...

//-----------

0682e840 2a214489 CvGameCore_Expansion2!CvPlayer::DoDistanceGift+0x36 [d:\sources\civ-vp\cvgamecoredll_expansion2\cvplayer.cpp @ 37420]
0682e860 2a313bf7 CvGameCore_Expansion2!CvPlayerTrade::GetPlotMouseoverToolTips+0x389 [d:\sources\civ-vp\cvgamecoredll_expansion2\cvtradeclasses.cpp @ 6111]
0682e88c 2a315af1 CvGameCore_Expansion2!CvLuaPlayer::lGetTotalValueToMeNormal+0xe7 [d:\sources\civ-vp\cvgamecoredll_expansion2\lua\cvluaplayer.cpp @ 14202]
0682e89c 0fe8266d CvGameCore_Expansion2!CvLuaPlayer::lIsMyDiplomatVisitingThem+0x61 [d:\sources\civ-vp\cvgamecoredll_expansion2\lua\cvluaplayer.cpp @ 14876]

seems to be a bad unit pointer passed from lua, unclear how to fix ...

**Comment by ASCII-Guy** [comment]
@HeathcliffWarriors

**Comment by HeathcliffWarriors** [comment]
> you're playing fast and loose with data types and indices here ...

Could you clarify? I lack experience with vectors, but I haven't gotten any crashes.

**Comment by ilteroi** [comment]
well i haven't had any crash either but if viWonderCounts is empty, it will crash.

also i'm not sure if the median really needs to be a float ... we can define it any way we want ... and the peculiarities of math in C cause your result to be truncated to int first anyway.

so my version would be:

```
int CvDiplomacyAI::CalculateMedianNumWondersConstructed()
{
	vector<int> v;
	for (int iPlayerLoop = 0; iPlayerLoop < MAX_MAJOR_CIVS; iPlayerLoop++)
	{
		PlayerTypes eLoopPlayer = (PlayerTypes) iPlayerLoop;
		const CvPlayer& kPlayer = GET_PLAYER(eLoopPlayer);

		if (kPlayer.isMajorCiv() && kPlayer.isAlive() && kPlayer.GetWondersConstructed() > 0)
			v.push_back(kPlayer.GetWondersConstructed());
	}

	if (v.empty())
		return 0;

	std::sort(v.begin(), v.end());

	return v[v.size()/2];
}
```

what's more, this should be a CvGame method, since it's not player specific.

**Comment by HeathcliffWarriors** [comment]
Ah, I hadn't considered that it could be empty, but I guess it's possible under some circumstances. Thanks for the help.

One note, though; I specifically did not check for the player being alive because it's based on Wonders constructed, not Wonders owned, and the penalty's meant to affect players who construct way more Wonders than average. Other players being killed doesn't make any one player more of a constructor.

**Comment by ilteroi** [comment]
fine by me, but after looking at the code i have to say it's all a bit weird ... 
* first call CalculateMedianNumWondersConstructed() and then calculate the average? 
* CalculateMedianNumPlots() should be NumPlotsPerCity?
* I don't know how often these are called but it might make sense to store all these medians in CvGame and update them once per turn

**Comment by HeathcliffWarriors** [comment]
1 - The global average check is to ensure that a player isn't punished for being above the global median if they're not actually building too many Wonders compared to the global average (like if a few civs hoard most of the Wonders). For instance, a player with 6 Wonders with a median of 3 if other players had built 30 amongst themselves.

2 - It's based on total plot count compared to other players' total plot count.

3 - Called every time opinion is updated (once per turn as well as if certain events happen, like signing a DoF), or any time a player mouses over an AI's approach to get their opinion table. It could be updated once per turn in CvGame at the cost of giving the player instant feedback on whether they're angering other AIs.

**Comment by HeathcliffWarriors** [comment]
@ilteroi Fixed: https://github.com/LoneGazebo/Community-Patch-DLL/pull/6451/commits/21a9b4ed7a207180e69de47c81a7d749cf00be77

**Comment by ilteroi** [comment]
1 - just saying that median + avg + WONDER_SPAMMER_THRESHOLD fudge factor seems like overkill

2 - but plot count and city count are highly correlated ... so it makes little sense to check both conditions as they are defined right now. better to look at plots per city instead, and maybe ignore the 19 plots in the first two rings.

3 - you can do even better and update the three medians with one pass over all players. but i don't know if the performance impact is significant.

**Comment by HeathcliffWarriors** [comment]
1 - Got a lot of complaints about AI overreactions, so I wanted to make certain the AI applied it when it made sense, and proportionally so. Overkill, maybe, but not a huge problem.

2 - A fair point. Is there an existing function which does this without iterating over all plots in the city?

3 - The Wonder median I think could be cached and updated every time a Wonder is built, since that's an infrequent occurrence. Plots and cities could be updated once a turn with no real issue, I think - the AI doesn't update border disputes, etc instantly either.

**Comment by ilteroi** [comment]
also, weird thing i forgot, why does the wonder spammer code ignore players with zero wonders?

**Comment by HeathcliffWarriors** [comment]
There's a tendency for a few civs to build most of the Wonders, and zeros drag down the median...so in short, to avoid excessive penalties by ignoring civs who aren't interested in wonder building.

Furthermore, while part of the penalty's point is to encourage the AI to attack players who build a lot of juicy Wonders that the AI could conquer, it's also to encourage players to either beef up their empire so they can do what they want with impunity, or let some other civs build some of the Wonders. The "other civs" being civs who are actually interested in Wonder building.

That was my logic, anyway.

**Comment by ilteroi** [comment]
maybe the median just isn't the right tool here ... why not use the 90% percentile for example?

also, transparency to the player is a virtue.

**Comment by RecursiveStar** [comment]
Problem with idea 1: a percentile threshold isn't necessarily indicative of excessive wonder building (if one player has 1 wonder and everyone else has 0, they're at the highest percentile, but that's not really excessive).

Problem with idea 2: building more wonders than half would only allow for one player to get the penalty - as mentioned, oftentimes a few civs hoard most of the wonders between them.

I don't like the overcomplication either, but I have yet to think of something better that works in practice.
