### ISSUE TITLE
Tourism get lost upon hovering a city banner

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#646]
https://d.maxfile.ro/mnwlviwiej.webm
https://d.maxfile.ro/xabqqsbhbr.webm
a/v desync because at this stage my game freezes for 5+ seconds every time I hover over an owned city banner.

**Comment by LoneGazebo** [comment]
Weird. Are you getting any errors in your lua.log?

**Comment by Radost** [comment]
http://pastebin.com/FevUfuyP
No errors.

**Comment by Edaka** [comment]
Have you been moving any great works? Whenever I stack them for theming bonuses, the tourism counter doesn't refresh until I hover over the banners of cities from and to where I've moved them. For example: I reassign a great work from city A to city B - the tourism counter doens't change at first. Hovering over city A's banner makes the counter go down, while hovering over city B's banner makes it go back up.

**Comment by Radost** [comment]
Except it goes down even when I hover over my capital, even when I haven't changed great works there.
