### ISSUE TITLE
"Impossible!" Trade Accepted

### ISSUE THREAD

**Issue by MIS-g** [LoneGazebo/Community-Patch-DLL#6460]
_1. Mod version (i.e Date - 3/15): 4-7_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ "Impossible!" Trade Accepted

_4. Steps to reproduce (optional):_Attaching (a) autosave before it happened.  Offer Copper to Genghis at 7gpt. (b) Save after.
[kAskia_0071 BC-1160.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4466489/kAskia_0071.BC-1160.zip)
[AutoSave_0070 BC-1200.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4466491/AutoSave_0070.BC-1200.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by silentreply** [comment]
I have also been observing AI offering peace treaties that are "impossible." Also at the leader screen they will say "now is the time for peace" but then the deal screen says "impossible." I'm still on 3-15-2 though.

**Comment by HeathcliffWarriors** [comment]
Don't think this is my doing.

**Comment by silentreply** [comment]
Still active in 4-17, at least with regards to "impossible" peace treaty offers.

![image](https://user-images.githubusercontent.com/59859911/80766925-95f9bc00-8b14-11ea-9096-f44e81c6e75d.png)
