### ISSUE TITLE
3/15 - Spies can not defend against advanced actions?

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6462]
_1. Mod version (i.e Date - 3/15):_ 3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I suspect that spies are unable to defend against advanced actions, and can only kill spies that attempt to steal technology. 

My strategy in this game has been to send spies out to rig election and get a level up, then bring them back to defend in my core cities. Strangely, I have only had one spy kill the entire game (an attempted tech steal), despite constant identifying spies performing advanced actions in multiple cities. In Washington, the chance to kill spies performing advanced actions is 74%, chance to identify 10%, chance to detect 16%. Chances are similar for attempts to steal technology, and the same other cities with lvl 2 spies defending. 

![image](https://user-images.githubusercontent.com/59859911/79075090-8843da00-7cbe-11ea-9afc-920151ef9086.png)

Espionage log: 
[EspionageLog.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4466748/EspionageLog.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I'd need more information to debug this, from other players.

**Comment by LoneGazebo** [comment]
it's just a UI issue

**Comment by silentreply** [comment]
Yes it seems spies are not supposed to be able to defend against advanced actions. 

I do think it's worth keeping an eye on however. I've nearly finished that game and still not had a single tech stolen - it may be that the AI is moving spies once they are "detected" performing an advanced action instead of staying in place for tech steal. Not a bad strategy given tech steal times are extremely long in the late game.
