### ISSUE TITLE
Bad AI movement choices at war

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#6466]
AI India made some suicidal moves during a war: a GG that was sitting on city borders (on the ??? hex, I thought it was going to place a citadel, and the AI should actually use more defensive citadels when besieged imo) moved unescorted right next a unit of mine he could see the whole time. It also created a fresh trade unit after I pillaged a trade route going from Delhi to Vijayanagara two turns before and sent it to Stockholm, following pretty much the same path, again free gold for me.

![civgg2](https://user-images.githubusercontent.com/53142313/79112345-a2dd8800-7d7e-11ea-9539-acf0ff469e9f.png)

**Comment by ilteroi** [comment]
hmm. AI should know not to recreate a trade route that was plundered recently ...

the issue with the general is also weird, do you have the tactical AI logfiles?

**Comment by randomnublet** [comment]
To be fair the AI didn't recreate the same route, but it lost Delhi -> Vija route, then created Delhi -> Stockholm. Both going through warzone. You probably don't want to send routes around when you're at war and there're enemies let say 3 tiles from the sending/receiving city or whatever. Trade units are at best badly invested hammers in a war.

Where're the tactical AI logfiles located?

**Comment by ilteroi** [comment]
ok that explains it ... they avoid trade routes through enemy territory but not individual units, that would make pathfinding to expensive and too jittery.

the tactical log is in the logs folder (name should be PlayerTacticalAI), but you have to activate AI logging in config.ini first. if you don't have it no worries, i guess i'll need to reproduce it anyway eventually

**Comment by ilteroi** [comment]
general moves have been improved ... the trade route thing needs watching, closing anyway
