### ISSUE TITLE
Multiplayer compatibility?

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6468]
@LoneGazebo I remember you stating at some point (in 2019? 2018?) that you wouldn't be able to debug multiplayer "until at least this summer" due to a lack of equipment. I realize we do not have access to the full source code, but is debugging multiplayer still planned at some point? And do you have the equipment you'd need, or if not, what is that equipment? It'd be really fun to play multiplayer with friends of mine, since VP is one of the only strategy games out there with intelligent AI, and the game balance is overall very well done. :)

Obviously I don't mean right now or on any kind of strict timeline, I recognize you're very busy IRL, but I'm wondering if it's something to expect going forward.

**Comment by LoneGazebo** [comment]
so much of the code from the networking side is unavailable to us, unfortunately. we can engage in some light bugfixing here and there, and maybe resolve some desyncs, but major overhauls dedicated to MP are not feasible.

**Comment by HeathcliffWarriors** [comment]
I suppose there isn't a way to reverse engineer or otherwise obtain the source code? Probably against the license agreement or something.

**Comment by LoneGazebo** [comment]
Nope. It's proprietary to firaxis.

**Comment by HeathcliffWarriors** [comment]
Curses. Maybe they'll release it one day, not that I'll count on it.

**Comment by Serpens66** [comment]
Hi, I also try to debug multiplayer.
Isnt it possible to at least find some lua/dll sources of desyncs? I see CP added fake-random numbers to lower the number of desyncs, although I'm not sure if this was necessary? Was it proven that the original random numbers could cause desync? I'm just added a customlog to the getJonRandNum function to be able to see if there is something different (in my non CP dll).

Anyway, we could enable intensive logging of all major values and also logging for all randomly generated numbers (unless we assume fake-random numbers is totally save). I guess there are more than enough players willing to play CP as kind of beta in mutliplayer, thus enabling logging and keep an eye on the results (this this version with extensive logging will be marked as such)

**Comment by RecursiveStar** [comment]
Maybe? @LoneGazebo would know more.
