### ISSUE TITLE
Question re: game performance/memory

### ISSUE THREAD

**Issue by HeathcliffWarriors** [LoneGazebo/Community-Patch-DLL#6470]
Do functions written into the CPP/H files that aren't called have any adverse effect on memory or performance, or do they just increase file size? I removed a couple ancient unused functions from the diplo AI, and I'm planning on more cleanup over time.

Likely will be adding more functions as well, which is why I ask.

**Comment by ilteroi** [comment]
no impact

**Comment by HungryForFood** [comment]
If removing Firaxis code, remember to use [preprocessor directives](http://www.cplusplus.com/doc/tutorial/preprocessor/l) to mark them out rather than outright deleting.

**Comment by HeathcliffWarriors** [comment]
@HungryForFood I inquired about that earlier, actually: https://github.com/LoneGazebo/Community-Patch-DLL/issues/5724#issuecomment-544327012

**Comment by HeathcliffWarriors** [comment]
@ilteroi Thanks!
