### ISSUE TITLE
[Question] about new Tables and failsafe checks in dll

### ISSUE THREAD

**Issue by Serpens66** [LoneGazebo/Community-Patch-DLL#6471]
Hi, I'm new to modding the dll (I know lua and a bit xml/sql and made mods for Civ5 already).

I'm currently trying my first steps by trying to implement some of CP features to whowards v94 dll. I may switch to the opposite (using CP as base and implementing missing features from whoward), but currently I know most bugs/crashes of whowards dll, while I'm unexperienced with CP dll..

Anyway:
I implemented "MOD_RESOURCES_PRODUCTION_COST_MODIFIERS" into whowards dll and got a crash when loading dll, because I missed defining the new tables from CoreTableAdditions.xml into the mod folder.

I'm by far no professional programer, but shouldnt there be a failsafe check for things like this?
And why are those tables defined in the Core? Wouldnt it be better to let mods, that would like to use this feature, define the table themself (with a check if it already exist, if not create). And then execute the code in CvInfos.cpp only, if a such a mod is active.
In general, there is really much new code, that is always executed, even if no mod is using it (MOD_RESOURCES_PRODUCTION_COST_MODIFIERS being false).

So is there any good reason why we dont take all these safety measures? Or are my thoughts wrong? I just would like to eleminate as much crash reasons as possible :D

**Comment by ilteroi** [comment]
in theory you are right but unfortunately many people have added code over the years and not all of them shared your careful approach.

als
