### ISSUE TITLE
Game crashing on loaded saves II. 

### ISSUE THREAD

**Issue by doominator10** [LoneGazebo/Community-Patch-DLL#6472]
_1. Mod version (i.e Date - 3/15):_
4/14  (not sure what version it is, I just used the installer)

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch
CBP OverHaul
CSD for CBP
CIV Diplomatic Features
More Luxuries
CBP Compatibility files EUI
Promotion Icons VP
UI - Promotion Tree VP
Communitas Map
Faster Aircraft Animations
Infoaddict
Less Warmonger Hate

_3. Error description:_ 
Game exits to desktop when I try to load the modded save I just spent 12 hours on last night.

_4. Steps to reproduce (optional):_
I go through Mods->Load Game 
Loading my save directly crashes the game
Making a new modded save with the same mods works. I save it, try to load my old save from the new game, game crashes back to desktop.
I try to load turn 0 of my save from the autosave list. Game still crashes to desktop. 
I try to load ANY of the autosaves from the list. Game still crashes.

I've reinstalled civ V, vox populi, and removed everything from the MODS folder. 
Game still crashes. The previous thread https://github.com/LoneGazebo/Community-Patch-DLL/issues/1814 isn't working for me.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4473360/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[0ldAutoSave_0270 AD-1250.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4473368/0ldAutoSave_0270.AD-1250.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4473371/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by ilteroi** [comment]
savegames break easily unfortunately. don't update if you don't need to ...

**Comment by doominator10** [comment]
It wasn't an update though. I downloaded VP on this laptop first time last night, played the game through the night, went to bed, then couldn't get back to it.

**Comment by ilteroi** [comment]
now i see. well that should not be happening then. but unfortunately not sleeping might be easier than fixing this. can you try without all the extra mods?

**Comment by doominator10** [comment]
I can try with just the VP mods, tho I don't know how long until I get back to here with that.
Unless by extra mods you're referring to all of them.

**Comment by HeathcliffWarriors** [comment]
@ilteroi Perhaps analyzing the minidump with windbg might yield something useful?

**Comment by ilteroi** [comment]
already did that, just got the usual deserialization error in a misaligned read() call

**Comment by Vyyt02** [comment]
Maybe a silly question, but could you have accidentally deactivated some mod when going through the mods screen? When the mod composition changes, the saves often stop working.

**Comment by doominator10** [comment]
I've double checked them, I'm certain I haven't missed any of the mods when I went through them.
On a separate note, I've started a new save with just the vp mods, and so far I've been able to go back to it. We'll see if that will continue as I stop / start playing it.
