### ISSUE TITLE
AI not prioritizing defending own citadels

### ISSUE THREAD

**Issue by MontyJava** [LoneGazebo/Community-Patch-DLL#6473]
_1. Mod version:_3/15beta + 4-10DLL

_2. Mod list:_InfoAddict

_3. Error description:_ N/A

AI seems to just ignore its own citadels (though it seems to avoid player citadels as part of plot danger still). Typically they are undefended at start of war, and even after DoW+1T they remain vacant.

**Comment by silentreply** [comment]
I have noticed this to some degree. Here's an example in game:

![image](https://user-images.githubusercontent.com/59859911/79279744-b53deb80-7e7c-11ea-8196-a859fa77a9b0.png)
