### ISSUE TITLE
3/15 Some Typos and clarification requests.

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#6475]
_1. Mod version (i.e Date - 3/15):_
3/15

_2. Mod list (if using Vox Populi only, leave blank):_
More Unique Components
Enhanced Naval Warfare
Even More Resources

_3. Error description:_ 
Vanguard Promotion description says it gives 100%, it actually gives 125% vs Cities.
GDR's are missing Armor Plating I, even though they upgrade from Modern Armor, although you can get to them without even Combustion.  

_4. Steps to reproduce
Text clarification Requests (optional):_
Radio, Computers, and The Internet's Civilopedia stats that it "Greatly increases empire wide Tourism output."  I would like it such a description listed it's value.  

Foreign Service and Treaty Orgnization state that they scale base on the # of City States.  Would you have it list per how many City States?  Cover Action and Double Agents as well.

Police State lets you Courthouses in half the usual time.  Worker's Facilitates Factories in half the usual time.  Space Procurements, Spaceship Factories.  Isn't it more appropriate to have them state that they give +100% Production towards them as with New World Order?  

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by silentreply** [comment]
> 3. Error description:
Vanguard Promotion description says it gives 100%, it actually gives 125% vs Cities.
GDR's are missing Armor Plating I, even though they upgrade from Modern Armor, although you can get to them without even Combustion.

Did you take into account the preceding Dreadnought promotions, which give an additional 30% CS? Vanguard is gives 100% bonus in my game.

As far as I know, GDR's are not intended to receive AP I, if you want them to have that promotion you have to go the upgrade route from Modern Armor. Same applies to other units, such as receiving Cover or Formation on Rifleman. 

As for the text clarifications, I agree it would be nice if you could find that info easily in game. I believe you can probably find that info through a search on the forums however.

**Comment by phantommaxwell** [comment]
No, it the Bonus vs Cities in the Combat Preview is 158%.  I did not factor them in together, the game did.

**Comment by Aqinu** [comment]
> Foreign Service and Treaty Orgnization state that they scale base on the # of City States. Would you have it list per how many City States? Cover Action and Double Agents as well.

+2 Spies >= 20 (total: base + 2)
+3 Spies >= 30 (total: base + 3)
+4 Spies >= 40 (total: base + 4)
