### ISSUE TITLE
AI Logistics units don't know how to move after shoot

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#6476]
_1. Mod version (i.e Date - 3/15):_
3-1b

_2. Mod list (if using Vox Populi only, leave blank):_
Skirmisher Doctrine replaced with Logistics, Cover II and -50% exp gains. Lowered RCS of most skirmisher units.

_3. Error description:_ 
AI Skirmisher units with logistics never move after shooting twice, thus dying easily to counter-fire. Normal skirmishers, however, know how to utilize road networks to harass invaders.

_4. Steps to reproduce (optional):_
Since apparently AIs never pick Logistics, you'll probably need IGE to give it to them. Maybe England's SotL has the same issue, but I haven't fought England ever since the ranged ship change.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
cannot reproduce ... you sure they did not simply run out of movement points?
