### ISSUE TITLE
Ancient Ruin Typo

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6477]
_1. Mod version (i.e Date - 3/15): 4/10

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

Appears the txt_key text, only on production bonus from the ancient ruins, I don't know how to fix it.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/79326263-3cda3780-7f1b-11ea-984a-f6402b0a9ab0.png)

**Comment by HeathcliffWarriors** [comment]
TXT_KEY blank lines are usually indicative of an installation error - sure it's not that?

**Comment by LoneGazebo** [comment]
could also be a broken { } bracket for numbers from the DLL...which TXT_KEY_ exactly?

**Comment by Aqinu** [comment]
TXT_KEY_GOODY_PRODUCTION, you can see it in the screenshot

**Comment by AmusingThrone** [comment]
I face the exact same error in my installation as well.

**Comment by azum4roll** [comment]
Same in my 3-1b version.
