### ISSUE TITLE
Puppet Cities Unhappiness

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6478]
_1. Mod version (i.e Date - 3/15): 4/10

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

The descriptions states that for every 5 citizens you get 1 unhappiness but I have it at 4 citizens. Don't know if typo or not intended.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/79326584-c0942400-7f1b-11ea-8e5d-77b60b80ad88.png)

![Civ5Screen0002](https://user-images.githubusercontent.com/49090452/79326734-05b85600-7f1c-11ea-9f8b-ced9a290c650.png)

**Comment by LoneGazebo** [comment]
Should be 1 per 4.
