### ISSUE TITLE
Game Crash on Specific Turn End

### ISSUE THREAD

**Issue by ausberg** [LoneGazebo/Community-Patch-DLL#6479]
_1. Mod version (i.e Date - 4/10):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Game crashes specifically at the end of turn 98. Loading to a previous turn and playing back to turn 98 doesn't resolve the issue.

_4. Steps to reproduce (optional):_
End turn 98. Technically I always promote and move my scout, lock new growth tiles, then end the turn--if that matters. Worth noting that I experienced this on my last play-though as well but the issue resolved itself when I reloaded the auto-save of the turn before.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4482321/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Ahmad al-Mansur_0098 BC-1550.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4482322/Ahmad.al-Mansur_0098.BC-1550.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4482324/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by ilteroi** [comment]
which version?

**Comment by ausberg** [comment]
> which version?

I included the version in my post. 4-10 pasted over 3-15-2 tho.

**Comment by ilteroi** [comment]
which post? anyway, known problem, already fixed

**Comment by ausberg** [comment]
![Capture](https://user-images.githubusercontent.com/59094203/79436012-583a5680-7f9e-11ea-836c-3168dd276b4a.PNG)

In the comment template. Glad it is fixed though. Is it fixed in version 4-12 or will it be a later patch?

**Comment by ilteroi** [comment]
oh you changed the template. sneaky ...
anyway there will be a new official release tonight. not save game compatible unfortunately.

**Comment by ausberg** [comment]
> oh you changed the template. sneaky ...
> anyway there will be a new official release tonight. not save game compatible unfortunately.

Yea sorry I realize I did it weird... lol. Thanks for the info!
