### ISSUE TITLE
Military units stacking

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#648]
https://d.maxfile.ro/ynsqhtglju.webm
Explorer had 3 movements points, while the rifleman - only 2.

**Comment by LoneGazebo** [comment]
Really odd. I've paged ilteroi, just to see if we can figure it out. If you try to reverse it from the start (swap explorer with rifleman), does it work?

**Comment by Radost** [comment]
That the video from older version and I don't have the save anymore. It wasn't the first time I encountered this bug either.

**Comment by LoneGazebo** [comment]
If it happens again, do a couple of tests to see if you can reverse it. What it looks like is that the unit could have made it had it not been for the ZOC from that Ethiopian artillery piece. Since the explorer used a different path, it didn't encounter the ZOC.

**Comment by ilteroi** [comment]
interesting indeed.

it seems CvUnit::CanSwapWithUnitHere() uses the ignore unit pathfinder, which gives a valid path for the infantry along the road.

the actual movement then uses the regular pathfinder, so the unit runs out of moves on the way. and apparently there's no stacking check there.

i guess i'll change to the regular pathfinder for CanSwapWithUnitHere() and we'll see what happens ...
