### ISSUE TITLE
Possible coding error evaluating relative military strength

### ISSUE THREAD

**Issue by psparky** [LoneGazebo/Community-Patch-DLL#6482]
I have found a strange piece of code in file CvDiplomacyAI.Cpp, routine DoUpdateOnePlayerMilitaryStrength. This is used to evaluate the relative military strength of two civs. The code is:
            if(iDPThem > 0)
            {
                iOtherPlayerMilitary *= (int)((iDPThem * .1f) + 100);
                iOtherPlayerMilitary /= 100;
            }
            if(iDPUs > 0)
            {
                iMilitaryStrength *= (int)((iDPUs * .1f) + 100);
                iMilitaryStrength /= 100;
            }
This code multiplies a civ’s military score by a tenth of the sum of the military score of the civs that they have a defensive pact with, and adds that to the civ’s own score.

I’m guessing that what is intended is to add 10% of the military score of the civs that they have a defensive pact with:
            if(iDPThem > 0)
            {
                iOtherPlayerMilitary += iDPThem / 10;
            }
            if(iDPUs > 0)
            {
                iMilitaryStrength += iDPUs / 10;
            }
If this is indeed a bug, then it could have a big impact on the AI’s view of its strength relative to other civs, and a significant impact on their diplomatic actions.

See also https://forums.civfanatics.com/threads/diplomacy-ai-development.655040/page-11#post-15732830 for an example of the calculation.

**Comment by RecursiveStar** [comment]
Nice catch, thanks a lot!
