### ISSUE TITLE
How do you build the Vox Populi repository into a .civ5proj?

### ISSUE THREAD

**Issue by iskaandismet** [LoneGazebo/Community-Patch-DLL#6486]
Hey guys! I'm trying to put together a custom version of VP with changes made for compatibility with my own mods. I'm trying to build the repository into a premade pack with my own additions / compatibility changes, and want to be able to make my own changes within modbuddy. 

I know that there isn't one version of VP, the installer installs different sets of files depending on your preferences regarding EUI and 43civs, but I'm just trying to set a up a super-basic No-EUI/22civs/CBP VP without (5) - More Luxuries or (2) \Modular Elements\Corporations.

To do this, I've been trying to make a .5civproj by:
 - downloading the repo
 - making a new modbuddy project, then combining the contents of the .civ5projs in the downloaded Repo's (1) CP and (2) CBP folders into my new modbuddy project's blank .5civproj, and adding the files from (1) and (2) to my modbuddy project
 - adding in the necessary files for (3) CSD and (4) C4DF into my modbuddy project, then adding the data via some ctl+c ctrl+v ctrl+h from the .modinfo files from the folders of (3) and (4) into my modbuddy project's .civproj, because unfortunately they didn't come with their own .civ5projs
 - deleting the contents of (1) CP\LUA and (2) - CBP\LUA from my modbuddy project. because I assume they're replaced by (6b) - Compatibility Files, which I copy into my modbuddy project

That leaves me with something that looks like this:
![Untitled](https://user-images.githubusercontent.com/40811773/79412247-fe706700-7f72-11ea-9079-ad54bcb9ee3a.png)

This all seems to work fine, and I was patting myself on the back, but I'm encountering a strange bug. The AI will not settle Cities; the only exception being that very rarely will only one Civ in any game of any world size / number of Civs settle one City, but that's the only pattern I've seen. Civs will send their Settlers around the world, then bring them home, then send them out, them bring them home.

Anyway, this makes me think I took a wrong turn somewhere, and was wondering if someone could tell me if I did anything obviously wrong, or if my problem is probably somewhere else.

Thanks in advance! Love you guys!

**Comment by LoneGazebo** [comment]
getting any weird database log errors?

**Comment by iskaandismet** [comment]
This can be closed, I took the slow way and compiled a .cciv5proj from an installer-installed VP. Works fine.
