### ISSUE TITLE
Large number of unresolved issues

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6487]
Not counting this one, there are currently 218 open issues (effectively 211 because five are "Fixed for upcoming version" and two are "Not going to fix"), which is more than I've ever seen before at once. Not saying this to blame anyone, everyone's been busy, but that's a lot of potential problems that haven't been addressed.

@LoneGazebo Is there anything I can do to help out? Categorize them or something?

**Comment by LoneGazebo** [comment]
I was actually just looking at this. Bulk of them are already resolved. Let me clean up.
