### ISSUE TITLE
Military Units Stacking

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6488]
_1. Mod version (i.e Date - 3/15): 4/10

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![a](https://user-images.githubusercontent.com/49090452/79487387-d8a19b80-8020-11ea-9ded-41f525795664.png)
![b](https://user-images.githubusercontent.com/49090452/79487397-d9d2c880-8020-11ea-9ce3-aee2920bb820.png)

**Comment by Aqinu** [comment]
So this is now how it is suppose to work, i didn't see this happen before...

![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/79497581-95e7bf80-8030-11ea-9881-03bfc4281c5a.png)

**Comment by ilteroi** [comment]
well, the feature actually should only abort the move if a new enemy unit becomes visible during the move. to give you an opportunity to react to that new info. but apparently there was a false positive here? anyway, it's benign.

**Comment by Stalker012345** [comment]
The only instance of unit stacking that I find a real problem, are scenarios like this:

1) I have a ship in my city.
2) City is under assault by enemy ship.
3) I finish a new ship.
4) New Ship has absolutely no where it can go. I have to scrap it right out of the gate.

**Comment by RecursiveStar** [comment]
@ilteroi Couldn't you have the feature check if one of your units is already on the plot or something?

**Comment by ilteroi** [comment]
well, units have different vision range so that's dangerous. i'd rather fix the false positive if i ever encounter it.

re: new ship ... you probably should not finish it in that situation. in fact, i think there should already be a check that makes it impossible to build a unit if there's nowhere to put it? but maybe it didn't trigger. or maybe i'm wrong.

**Comment by Stalker012345** [comment]
If there is supposed to be a protection, I can confirm it does not work. I've had the ship thing happen several times.

In a perfect world, yes your right I should just not build it, but of course sometimes you get lazy in a game or just don't think about it when the enemy's death navy is at your door. All your thinking is "moar troops!"

**Comment by azum4roll** [comment]
My units sometimes get stacked on AI ones when I try to move them through fog, instead of the move being cancelled.
