### ISSUE TITLE
0 turns until city growth

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6490]
![Screenshot (899)](https://user-images.githubusercontent.com/38794241/79500789-07a51680-7ffb-11ea-8c61-dc48f2929c8c.png)
![Screenshot (900)](https://user-images.githubusercontent.com/38794241/79500790-083dad00-7ffb-11ea-9d9c-82f507281e87.png)

**Comment by RecursiveStar** [comment]
Probably a missing (if == 0 then = 1) check.

**Comment by ilteroi** [comment]
nope. 0 means the city is over the growth threshold.

**Comment by RecursiveStar** [comment]
I get that, but it's not going to grow in 0 turns, it's going to grow in 1 turn.

**Comment by ilteroi** [comment]
real men start counting at zero :)

**Comment by Stalker012345** [comment]
I like the added 0 turn myself

**Comment by RecursiveStar** [comment]
_shrugs_ Vox Populi, I guess :)
