### ISSUE TITLE
MP modpack creation from SP exe does not include Monopoly overview, ...

### ISSUE THREAD

**Issue by Kierkegaard89** [LoneGazebo/Community-Patch-DLL#6494]
_1. Mod version (i.e Date - 3/15):_
3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Monopoly icon overview (among others) are not found in MP modpacks. Others have said they have the same issue:
https://forums.civfanatics.com/threads/where-to-find-monopolies-overview.657110/

_4. Steps to reproduce (optional):_
Tried to make the MP pack several times, assuring I did it correctly, issue still persists.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I don't do modpacks, but IIRC there is an InGame.lua you have to delete from the CP/CoreLUA to fix it.

**Comment by Kierkegaard89** [comment]
Thank you! That's indeed the solution.
I don't remember having to do that a year ago.

I'll post it on my thread on the civfanatics forums. Thanks!
