### ISSUE TITLE
Tech Tree Broken: Gunpowder Missing

### ISSUE THREAD

**Issue by choraltrickster** [LoneGazebo/Community-Patch-DLL#6495]
_1. Mod version (i.e Date - 3/15):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4491069/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Bug Tech Tree Gunpowder](https://user-images.githubusercontent.com/61171515/79535464-92156680-804b-11ea-990c-13cf74d8dea7.jpg)

![Gunpowder Bug--Mods List](https://user-images.githubusercontent.com/61171515/79535398-58dcf680-804b-11ea-801a-4a03c1f5e8e8.jpg)

**Comment by RecursiveStar** [comment]
Try clearing your cache and ModUserData folders and reinstalling.

**Comment by choraltrickster** [comment]
That worked. Thanks so much!
