### ISSUE TITLE
Wrong Units Total Strength Calculation

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6498]
_1. Mod version (i.e Date - 3/15): 4/10

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

Here should be 30.1 (14 + 14 * 115%) for the hoplite, but it's 25.9 (14 + 14 +85%)
![b](https://user-images.githubusercontent.com/49090452/79558831-793d9d00-80ad-11ea-828f-66610aeece15.png)

Here should be 34.7 (14 + 14  * 148%) for the hoplite, but it's 30.5 (14 + 14 * 118%) here it's also +40% combat bonus as above but it's under the hoplite panel)
![a](https://user-images.githubusercontent.com/49090452/79558802-6fb43500-80ad-11ea-97a5-8ac2e175fc2c.png)

The bonuses do add up correctly

**Comment by LoneGazebo** [comment]
It's because some penalties show up on the friendly side, and some bonuses show up on the enemy side. It's a firaxis choice, for whatever reason, but the actual calculation is not happening based on the UI.

**Comment by Aqinu** [comment]
So how the actual calculation is done if not from promotions gained and showed in panel, what's the point of the ui combat panel if it's not accurate and what's the point of promotions if some of those are not applied? 

On the friendly side is calculated correctly (both screenshots) on the enemy side it's the problem, still I don't understand how those bonuses are gained are not applied (-30% bonus for hoplite in each case)

**Comment by LoneGazebo** [comment]
It's not a matter of the bonus being applied, it's that the enemy side UI elements are sometimes applied to the friendly values.

**Comment by Aqinu** [comment]
But how are applied to friendly values if the 'friendly bonuses' add up correctly (those are not bigger than are shown), where are applied?

**Comment by Aqinu** [comment]
> but the actual calculation is not happening based on the UI.

The UI Shows the promotions for enemy unit (are shown correctly in enemy panel), it means that those promotions are not in fact gained/applied, then those are misleading...

**Comment by Stalker012345** [comment]
So the million dollar questions...

1) Is it fixable?
2) If not, is it possible to change the bonus to a different "type" that does show up correctly?
3) If neither, can we get a list of bonuses that do that so we aren't putting up false alarms?

**Comment by LoneGazebo** [comment]
We'd need to dissect the enemy unit panel lua...which is very complex, redundant, and awful.

**Comment by ilteroi** [comment]
should i ever lie in a hospital bed with two broken legs, i might implement a sane system where all the bonuses are reported directly from the gamecore. until then, we'll have to live with the occasional inconsistency.

**Comment by Aqinu** [comment]
After some testing I found out the following:

**Adjacent friendly unit bonus doesn't work/apply for both player and enemy:**
Stage1a: with adjacent bonus 9 total damage from chariot
![a1](https://user-images.githubusercontent.com/49090452/79633677-45c34700-816f-11ea-957a-6d6a82af1317.png)

Stage1b: WITHOUT adjacent bonus still 9 total damage from chariot
![a2](https://user-images.githubusercontent.com/49090452/79633724-6390ac00-816f-11ea-9bd0-0938b4a8f4d1.png)

Stage2a: Hoplite WITH adjacent bonus 17.5
![c1](https://user-images.githubusercontent.com/49090452/79633891-fc272c00-816f-11ea-9fe2-b98c75a2d7ec.png)

Stage2b: Hoplite WITHOUT adjacent bonus 17.5
![c2](https://user-images.githubusercontent.com/49090452/79633893-ff221c80-816f-11ea-9359-2a5fe3a46d60.png)


**General bonus DOESN'T WORK ONLY for the enemy units**
Stage2a: WITHOUT GENERAL 22.1 damage from hoplite
![b1](https://user-images.githubusercontent.com/49090452/79633761-786d3f80-816f-11ea-8851-4145592527ac.png)

State2b: WITH GENERAL STILL 22.1 damage from hoplite
![b2](https://user-images.githubusercontent.com/49090452/79633810-96d33b00-816f-11ea-9f1c-11737256f3f8.png)

**Comment by RecursiveVision** [comment]
I'll consider working on this when I get back.

**Comment by RecursiveVision** [comment]
Going to do some work on this :)

**Comment by Stalker012345** [comment]
Was this fixed?

**Comment by RecursiveVision** [comment]
No, but there was two issues open for this. Will fix soon.
