### ISSUE TITLE
[CSD] [UI] Great Diplomat and Great Persons panel

### ISSUE THREAD

**Issue by CunningGabe** [LoneGazebo/Community-Patch-DLL#65]
The Great Persons panel doesn't have a separate category for Great Diplomats. The bar for Great Diplomats appears under the heading of Great Engineers. It seems that sometimes, this is there in addition to the actual Great Engineers counter (so that your capital appears twice under Great Engineers), and sometimes, the Great Diplomats bar is there instead of the Great Engineers bar.

**Comment by LoneGazebo** [comment]
Looks normal - not quite sure what is wrong at this point.
