### ISSUE TITLE
3/15 - City processes and yield modifiers

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6503]
_1. Mod version (i.e Date - 3/15):_ 3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When a city works a process, the yield is displayed as though it should be affected by modifiers to that yield - in the top section above the "base" sum, as opposed to the bottom section which includes trade routes, modifiers, other yields not affected by modifiers. 

However, only culture process adds the culture produced to the "base" yield, and is thus affected by modifiers. For all other processes, the process yield is not added to the "base" yield.

I don't know which is intended, but the position they are displayed in the UI suggests they should be affected by modifiers. I also prefer this, because it makes processes more relevant and offers potential for specialization - some cities may have higher modifiers for certain yields. 

![culture process base](https://user-images.githubusercontent.com/59859911/79605785-86af5300-80be-11ea-9f76-6cf1d43795a8.png)
![research process base](https://user-images.githubusercontent.com/59859911/79605791-88791680-80be-11ea-9984-3a50f912c530.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Because of the order of operations, some things can't be adjusted here.
