### ISSUE TITLE
3/15 - Supply cap UI inaccurate

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6505]
_1. Mod version (i.e Date - 3/15):_ 3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Supply cap (and/or UI) does not appear to working properly. Adding the displayed values typically does not sum to the supply cap. Bonus supply from Brandenburg doesn't appear to be displayed, but does seem to be accounted for in peacetime. 

The UI suggests that the supply cap is reduced by 75%, however it seems to always state that there is just a flat -75 unit supply reduction. The bottom part about unit prod/gold cost being increased by 75% seems to always be active, even when there is no war weariness, and does not even seem to modify unit prod/gold cost regardless. Instead, cities suffer a production penalty when building units above the supply cap. 

265+433+6-470-75=**159**   
159 + 10 (brandenburg) = **169**
Actual supply = **121**
![supply t361](https://user-images.githubusercontent.com/59859911/79615264-5ec8eb00-80d0-11ea-8442-27fc3bf4c42d.png)

Will update with info from more turns, but wanted to try to get this up in case you could take a look before the next version goes out.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveStar** [comment]
@LoneGazebo Seems like this may warrant your attention prior to the next release, since the difference between the expected and actual unit supply is almost 50 units.
