### ISSUE TITLE
CTD upon selecting Maya free great prophet

### ISSUE THREAD

**Issue by ghettospud** [LoneGazebo/Community-Patch-DLL#6507]
_1. Mod version (i.e Date - 2/9):_
4-17

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) City-States Leaders for VP (v. 8)
(ui) List Enhancements for VP (v. 5)
InfoAddict (v. 22)
Promotion Overhaul for VP (v. 11)
Unit Path Viewer (v. 10)

_3. Error description:_ 
Selecting the free great prophet spawned from the maya UA instantly crashes my game.
I successfully founded a religion many turns prior before spawning the free prophet.
Loading a savefile from a few turns earlier and replaying the turns does not remedy the issue.

---------------------------
Supporting information:
[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4496240/logs.zip)

**Comment by ilteroi** [comment]
good news ... the lua callstack logging seems to work:

=[C] (-1): GetConversionStrength
Sid Meier's Civilization 5\MODS\Promotion Flags EUI (v 1)\UI\UnitPanel.lua (1382): UpdateUnitStats
Sid Meier's Civilization 5\MODS\Promotion Flags EUI (v 1)\UI\UnitPanel.lua (2012): ?

**Comment by JamesNinelives** [comment]
Thanks ilteroi! :)
