### ISSUE TITLE
4-17: hard crash when missionary gets selected

### ISSUE THREAD

**Issue by Kierkegaard89** [LoneGazebo/Community-Patch-DLL#6508]
_1. Mod version (i.e Date - 2/9):_
4-17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Whenever a missionary gets selected either by auto cycle or clicking on it, a hard crash to desktop occurs. Saved a game when I could buy a missionary. Load the save game file and buy missionary and click on it, then the hard crash happens.

[missionary test.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4496261/missionary.test.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4496281/Logs.zip)

_4. Steps to reproduce (optional):_
First noticed in MP modpack. Recreated in MP modpack.
Deleted Modpack and started SP game with SP mods (Vox Populi only). Crash still occurs

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
duplicate #6507
