### ISSUE TITLE
3-15 CTD on City-state or barbarian turn

### ISSUE THREAD

**Issue by modzster** [LoneGazebo/Community-Patch-DLL#6509]
_1. Mod version (i.e Date - 2/9):_
3-15

_2. Mod list (if using Vox Populi only, leave blank):_
(BNW) Leugi's Barbarian Inmersion Enhancements (v 1)
(Z) Change VP Options (v 3)
Buildings - Upgrade System (v 12)
Community Patch Mod Compatibility (v 17)
Calypso's Colored Religious Icons (Basic) (v 4)
Calypso's Colored Religious Icons (Extended) (v 5)
Calypso's Colored Religious Icons (BNW Extended) (v 3)
City Limits (v 7)
Civ Names by Policies (v 8)
Enhanced Naval Warfare for Vox Populi (v 1.6.12.1)
Ethnic Diversity Unit Pack (v 29)
Faster Aircraft Animations (v 3)
Ingame Editor (v 39)
JFDLC (07) - JFD's Cultural Diversity (Core) (v 17)
Krajzen's Great Artists Pack (v 1)
Krajzen's Great Musicians Pack (v 1)
Krajzen's Great Writers Pack (v 1)
More Great Works (v 3)
Quick Turns (v 10)
Throne Room (v 3)
UI_RCI
Unique City-States (v 6)
Units - No Futuristic Units (v 1)

_3. Error description:_ 
43 civ version of mod. Playing with 40 civ and 20 city states. Communitas map. Crashes on turn 391 epic game mode during Industrial Era. Turn indicator shows city-state before it crashes. I used IGE to kill barbarians to see if that would work, but it still crashed. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
old version, a million other mods and no logs ... sorry

**Comment by modzster** [comment]
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4496448/CvMiniDump.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4496452/Logs.zip)
[Sweden 042.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4496454/Sweden.042.zip)

Thought it took rar files. I uploaded the zip files.
