### ISSUE TITLE
4/17 Promotions Issues

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6510]
_1. Mod version (i.e Date - 2/9): 4/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Infiltrators bonus doesn't give -15 adjacent bonus, gives +15 adjacent bonus which doesn't work either:**
![a1](https://user-images.githubusercontent.com/49090452/79634034-c767a480-8170-11ea-9315-cdf5dd26385d.png)

Here WITHOUT adjacent bonus (chariot strength 9)
![z1](https://user-images.githubusercontent.com/49090452/79634102-25948780-8171-11ea-9958-6b7fe3a9fd9c.png)

Here WITH adjacent bonus (STILL chariot strength 9)
![z2](https://user-images.githubusercontent.com/49090452/79634111-32b17680-8171-11ea-998b-de67f8d35fec.png)

**Field i ii iii, still have bonus against wounded, should be open terrain**
![b](https://user-images.githubusercontent.com/49090452/79634138-55438f80-8171-11ea-9600-c11867b0a43c.png)

**Ace pilot 2 has +1 operational range, it is described as only from ace pilot 3 has +1 operational range**
![c](https://user-images.githubusercontent.com/49090452/79634161-815f1080-8171-11ea-8145-6641e4840789.png)

**Air penetration i ii/evasion still has 25% bonus TYPO in description**
![d](https://user-images.githubusercontent.com/49090452/79634179-976cd100-8171-11ea-993d-de1c6840b68c.png)

**Comment by LoneGazebo** [comment]
Fixed. Merge error. Thanks!

**Comment by adaneslavo** [comment]
Ace Pilot II still has description error (+1 range missing).

**Comment by adaneslavo** [comment]
Field also has 5% + Wonded instead of 10% + Open terrain.
