### ISSUE TITLE
Feature Request: GameEvents.CityDestroyed()

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#6512]
I would really like a lua hook for when a city is destroyed. Ideally, the hook would take place before the city is actually removed, so some info could be taken from the city, like its ID, tile location, what buildings were in it, etc.

There is already a Events.SerialEventCityDestroyed(Vector2, PlayerID, cityID, PlayerID2), but to my knowledge this only fires if the city is visible to a human player

**Comment by iskaandismet** [comment]
MFW I went to the trouble of making this for you

![Untitled](https://user-images.githubusercontent.com/40811773/79816939-5384f200-8352-11ea-8031-68d56fe9b05f.png)

And then it was already in the CP

![Untitled](https://user-images.githubusercontent.com/40811773/79816969-64cdfe80-8352-11ea-9225-4ed0f615d229.png)

Welp, there goes a half hour

**Comment by pineappledan** [comment]
Cool... So what does the lua hook look like? 

Sorry, I can't really read that; I don't know what's going on in the photos you posted

**Comment by LoneGazebo** [comment]
The event is CityRazed(eOwner, CityIX, CityIY). 
So you need to have a lua event hook looking for the owner and the city plot's x/y coordinate.

**Comment by pineappledan** [comment]
perfect timing, I tried putting this together and got a nil value for pCity. Here's the code:
```function CapitalBonusOnDestroy(iPlayer, iX, iY)
    local pPlayer = Players[iPlayer]
    
    if pPlayer:GetCivilizationType() == TimuridsID then
        local pCity = Map.GetPlot(iX, iY):GetPlotCity()
        local pCapital = pPlayer:GetCapitalCity()
        local iRazeBonus = (math.ceil(pCity:GetNumRealBuilding(GameInfoTypes.BUILDING_UNIQUE_RAZE_DUMMY) / 2))
        pCapital:SetNumRealBuilding(bTimDummy, (pCapital:GetNumRealBuilding(bTimDummy) + iRazeBonus))
    end
end

if Game.IsCivEverActive(TimuridsID) then
    GameEvents.CityRazed.Add(CapitalBonusOnDestroy)
end```

**Comment by LoneGazebo** [comment]
Hmm...just checked, values aren't reversed, as the 'kill' is happening before the hook. So you can't call the city for the function as it is. I can move the hook above if you'd like.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4511773/CvGameCore_Expansion2.zip)

**Comment by LoneGazebo** [comment]
Try that

**Comment by pineappledan** [comment]
I would like that very much. It's a much more useful hook if you can pull some information about the destroyed city ahead of time. eg, how many plots it has, what buildings/wonders are in it, etc.

**Comment by LoneGazebo** [comment]
look at what I sent you above

**Comment by pineappledan** [comment]
That works. Yay!
