### ISSUE TITLE
3/15 - Way of the pilgrim reformation belief tourism bonus

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6514]
_1. Mod version (i.e Date - 2/9):_ 3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Way of the pilgrim reformation belief does not provide tourism when spreading religion to city states. Are city states not counted as "foreign cities?"

![image](https://user-images.githubusercontent.com/59859911/79677442-8fd41900-81bf-11ea-83b2-2c6d14bfb55d.png)

Spread to city of a major civ:
![image](https://user-images.githubusercontent.com/59859911/79677461-cf9b0080-81bf-11ea-98ba-a1053e8effae.png)

Spread to a friendly city state:
![image](https://user-images.githubusercontent.com/59859911/79677473-ed686580-81bf-11ea-9f05-efa71fe2daa6.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveStar** [comment]
Maybe it's Tourism towards the civ you spread religion to? You can't influence City-States.

**Comment by silentreply** [comment]
You're right - it only provides tourism to the civ you spread to. Could we change the description to "Receive 15 culture and _tourism towards the city owner_ when you spread..." or similar?
