### ISSUE TITLE
Where is the best place to ask questions about debugging via Visual Studio?

### ISSUE THREAD

**Issue by iskaandismet** [LoneGazebo/Community-Patch-DLL#6516]
Hello VP people,

I recently got around to publishing a beta of my latest mod:https://steamcommunity.com/sharedfiles/filedetails/?id=2059129972

It's quite large, and is prone to the occasional ctd without anything particularly informative in the logs or in any of my print statements. I thought before I went to something more extreme like adding a print function to the beginning and end of all of pieces of code,  I'd finally get around to figuring out how to debug the game via visual studio. I think I've managed to hook VS up to the civ application correctly, because eventually I managed to get crash reports that look like this:

![2](https://user-images.githubusercontent.com/40811773/79678051-3cfd6000-81c5-11ea-82b9-de62c5237a42.png)

I just want to make sure I'm reading this right; the crash was called because IsMinorCiv() was called with an "expression cannot be evaluated", which I assume is nil? 

Anyway, I'm just dipping my toes into the DLL for the first time after having becoming really proficient in lua, and am considering rewriting several underlying fuctions of my mods from lua into the the DLL. I'm going to continue doing debugging with VS and am wondering where the best place to ask questions is; is there a Discord or Forum or should I just open issues when I have questions?

**Comment by ilteroi** [comment]
well there are a million tutorials on the web and then there is stackoverflow for specific questions ... but you're almost there! you typically have look one level down in the callstack, the root cause would be in GetGenericMaxStrength modifier where isMinorCiv() is called on an invalid CvPlayer pointer.

**Comment by iskaandismet** [comment]
Thanks ilteroi! So if I'm reading this one right, the crash happened because IsHasTech() was called? (or because updateTechShare was called with an invalid TeamTechs?)

![2](https://user-images.githubusercontent.com/40811773/79692336-8a63e680-8232-11ea-920a-5fc9157f88d3.png)

IsHasTech() is only called three times in my mod, 1. in InfoTooltipInclude, 2. in TopPanel, and 3., in this chunk of my own code:

`function GrantFreeNationalismForRadio(iPlayerID)
	local pPlayer = Players[iPlayerID]
	if pPlayer:IsMinorCiv() or iPlayerID == 63 or not pPlayer:IsAlive() then return false end
	if pPlayer:HasPolicy(GameInfoTypes["CIVIC_NATIONALISM"]) then return end
	local iTeamID = pPlayer:GetTeam()
	local iTeam = Teams[iTeamID]
	local iTeamTechs = iTeam:GetTeamTechs()
	if iTeamTechs:HasTech(GameInfoTypes["TECH_RADIO"]) then
		pPlayer:SetHasPolicy(GameInfoTypes["CIVIC_NATIONALISM"], true)
	end
end
GameEvents.PlayerDoTurn.Add(GrantFreeNationalismForRadio)`

Assuming it isn't InfoTooltipInclude or TopPanel, it must be this chunk of code, right? So all I have to do is add a `if iTeamTechs == nil then return end` ?

**Comment by iskaandismet** [comment]
Going back a bit here, I don't call GetGenericMaxStrength anywhere in my code, so the problem has to be that somewhere I'm calling IsMinorCiv() with a nil right? But wouldn't that cause a lua error of the cannot index nil variety?

**Comment by ilteroi** [comment]
now i'm confused. in the first screenshot, the callstack starts with CvGame::update() ... there is no lua involved here, just the regular turn processing.

in the second screenshot i can't be sure but the problem seems to be that a CvTeamTechs method was invoked on an invalid object, check UpdateTechShare().

the interaction between lua and the gamecore is as follows:
* the gamecore calls a lua hook during turn updates to support lua mods
* the lua ui needs data and calls one of the interface methods of the gamecore, eg in CvLuaUnit

the ui and the gamecore are two different threads with and a mutex (the gamecore lock) to synchronize.

**Comment by iskaandismet** [comment]
Alright, looks like I'm going to have to start understanding how threading works...

If you could please answer one more question ilteroi:

here it seems to say "the symbols have been loaded" which I assume means the pdb (which I have to include it with the dll in the mod folder?)

![1](https://user-images.githubusercontent.com/40811773/79696878-50eca480-824d-11ea-9a85-c993eb81070c.png)

But here, it says that there are "no symbols loaded", and doesn't give any helpful info about the crash. Why is this?

**Comment by ilteroi** [comment]
well lua has its own callstack because it's a vm. there's a method to print it ... if you have the lastest version you should see it in callstack.log

**Comment by iskaandismet** [comment]
>  callstack.log

Where do I find this? It doesn't seem to be with the rest of the logs in the logs civ 5\logs folder.

Also, please clarify for me: do I have to keep the .pdb with the .dll in my mods folder in order for Visual Studio to give me detailed crash reports, or does that not matter?

Also, I began separating my mod into different components to see if I could isolate my ctds. I got this error today:

![2](https://user-images.githubusercontent.com/40811773/79706328-d3458a80-8286-11ea-880f-e190d2c0d63d.png)

and I'm not quite sure how any of m code could have affected something so (seemingly) deep in the DLL. Any idea how that happened?

**Comment by ilteroi** [comment]
callstack log: should be next to the other logs if you have the latest vp version. search for CreateMinidump in the source and see if it mentions lua.

secondly, the callstack is not always reliable, it can be corrupted. but in your screenshot the problem is simply in the lua interpreter which is "invisible" to the vs debugger. so it shows you the only thing it knows, which is useless here.

third, put the pdb next to the dll. it has the references to the sources which the debugger needs. you can also put the pdb somewhere else but then you need to tell the debugger where to find it.

**Comment by iskaandismet** [comment]
Thanks for the answers ilteroi! So if I get this error:

![2](https://user-images.githubusercontent.com/40811773/79766109-864ccd00-82f5-11ea-9b10-f3ac7389ef4c.png)

then the error is completely to do with lua, and can't really be debugged thru VS?

**Comment by ilteroi** [comment]
well there is no callstack in that picture but yes, it's totally possible that it crashed without gamecore involvement, eg in the 3d engine. the sdk only contains the source code for the gamecore, but there are many other parts which are not public

**Comment by iskaandismet** [comment]
Slightly different question:

There seems to be kind of a belief held among members of the community that it doesn't depend how stable any collection of mods is, once you start adding more and more mods to the game is just becomes unstable.

I feel like this can't be right: the game was shipped by professional developers as more or less stable, and bar the occasional crash, is more or less dependably stable. Any instability must be a result of some sort of memory leak or bug/error/glitch in any modded code.

However, every once and a while, somebody in the know seems to indicate something about RAM limitations and x64 versions and developer incompetence. 

Anyway I'm trying to debug my mod, and getting frustrated by the fact that even though all the components seem to be stable by themselves, they don't seem to be stable all together. Visual Studio is being less helpful than I thought it would be, and I'm considering the possibility that my mod will never be stable, which would be quite unfortunate.

VP is the largest, most complex mod still being actively maintained, and you guys have a reputation for trying to make the game even more stable than it was when launched. So I have to ask you, is my mod crashing simply because it's too large, or is it a problem with my code somewhere, and it absolutely can be fixed?

**Comment by ilteroi** [comment]
well it's certainly possible that mods interact negatively , overwrite each others' settings for example.

there is also a memory limits but VP itself is stable even with large maps.

in your case it should be possible to isolate the root cause, the component which introduces the problems.
