### ISSUE TITLE
4/17 - CTD

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6519]
_1. Mod version (i.e Date - 2/9):_
4/17

_2. Mod list (if using Vox Populi only, leave blank):_
Quickturns v10
UI - Trade Filter

_3. Error description:_ 
I've seen several non-sticky CTDs on this version (very rare for me), but this is the first permanent CTD on saved game load. Logs and saved game attached.

_4. Steps to reproduce (optional):_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4499481/Logs.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
is this with the hotfix or without?

**Comment by LoneGazebo** [comment]
Does every save crash on load?

**Comment by Stalker012345** [comment]
Ah not with the hotfix, good point. Crashes on every load.
