### ISSUE TITLE
Liberated CSes leader screen

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#652]
![8930_2015-09-19_00026](https://cloud.githubusercontent.com/assets/1131228/10012999/dd2a47c4-6126-11e5-8458-3d088a9fcefa.png)
Long story short: Genghis Khan annexed a bunch of city-states before I even came in contact with him. So when I DoW'ed him and liberated them afterwards, I've gotten the screen above.

The second instance is related to #380 
![8930_2015-09-22_00001](https://cloud.githubusercontent.com/assets/1131228/10013232/efe4a920-6128-11e5-9b70-b4a3116a1450.png)
I got the same screen as in the first screenshot, except the liberating ship was pulled god knows where and turns out I hadn't even met that city-state, even though I was the one liberating it.

**Comment by LoneGazebo** [comment]
Odd. I'll take a look.
