### ISSUE TITLE
[4-17] Odd trade suggestions

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6521]
Few things with relly odd trade proposals:
- **strategic** resources are very undervalued; they wanted all my 4 horses for less than 2GPT;
- **luxuries** resources are overpriced; I got 7-8 GPT for one copy of luxury at the game beginning; then I saw most of AIs bankrupted;
- initial values of trade proposal from AI were around hundreds, where the biggest had 900! In previous version I got maximum 50?
- why they offer me embassy for 1 GPT instead embassy for embassy if this is possible?

![20200419210818_1](https://user-images.githubusercontent.com/33016300/79698453-4c45e180-8289-11ea-8e1d-5cbaed998e11.jpg)
![20200419211732_1](https://user-images.githubusercontent.com/33016300/79698456-4d770e80-8289-11ea-9303-b42fe6b5c21d.jpg)
![20200419212340_1](https://user-images.githubusercontent.com/33016300/79698458-5071ff00-8289-11ea-9aea-e8ae99d26bcf.jpg)

This is nearly unplayable...
It would be nice if major Trade rework would be next Diplo feature :)

**Comment by RecursiveStar** [comment]
Major trade rework's gonna take a while. But I'm sure something can be done in the meantime.

**Comment by RecursiveStar** [comment]
@LoneGazebo You modified resource valuation recently, I think?

**Comment by LoneGazebo** [comment]
Nope.

**Comment by adaneslavo** [comment]
![20200420010949_1](https://user-images.githubusercontent.com/33016300/79703683-9214a100-82ad-11ea-9195-524e1af82f67.jpg)

**Comment by adaneslavo** [comment]
Can this error be related to this?
```
[21627.978] Runtime Error: C:\Users\Adam\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\TradeLogic.lua:519: attempt to index field '?' (a nil value)
stack traceback:
	C:\Users\Adam\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\TradeLogic.lua:519: in function 'OnShowHide'
	Assets\DLC\UI_bc1\Improvements\DiploTrade.lua:35: in function <Assets\DLC\UI_bc1\Improvements\DiploTrade.lua:34>
```
