### ISSUE TITLE
Units requiring action before next turn don't show up in 'requires command' queue

### ISSUE THREAD

**Issue by crdvis16** [LoneGazebo/Community-Patch-DLL#6523]
_1. Mod version (i.e Date - 2/9):_
4-17-2

_2. Mod list (if using Vox Populi only, leave blank):_
VP+EUI

_3. Error description:_ 
The 'next turn' button is visible but doesn't actually progress you to the next turn.  Instead, you have to hunt through your units to find one that requires a command before 'next turn' will actually work but the unit doesn't get cycled to normally via the normal 'unit requires command' button that normally shows prior to 'next turn'.

This seems to particularly affect units that were upgraded the previous turn and/or units that performed an action while garrisoned in a city the previous turn.  It is as if being a garrison and attacking or being upgraded in the previous turn makes that unit get forgotten by the list that keeps track of units that require commands.

_4. Steps to reproduce (optional):_
Upgrade a unit that is garrisoned in a city and then do NOT put it to sleep.  The next turn it will likely not show up in the 'requires command' cycle but will nevertheless block 'next turn' from working. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by crdvis16** [comment]
FYI- I believe this has been occurring as of the last few betas.

**Comment by RecursiveStar** [comment]
Relatively sure this has been a bug since vanilla.

**Comment by Aqinu** [comment]
>  you have to hunt through your units to find one that requires a command before 'next turn'

Normally when it shows you 'end turn' but if there are units which still needs to be given commands when you click 'end turn' it actually appears 'unit needs order' and automatically goes to the unit/units in question, if doesn't work like the way I understand what you say, this is most likely is a bug.

> Relatively sure this has been a bug since vanilla. I remember hitting next turn, and then suddenly more "A Unit Needs Orders" missions queue up.

I agree.

**Comment by crdvis16** [comment]
Yep- I've seen times where 'Next Turn' appears and when you hit it the game
then finds a few more units that require attention.  In that case the 'Next
Turn' button is replaced with something like 'Requires Orders' and when you
click it you are automatically taken to the units that require attention.
That's not what I'm describing in this case.  In this case, when you hit
the 'Next Turn' button it stays 'Next Turn' but will NOT actually progress
to the next turn.  You then have to manually hunt for the unit that still
needs orders and until you find that unit and give it an order you can not
progress the turn.

**Comment by ilteroi** [comment]
cannot reproduce ... there must be some other condition

**Comment by crdvis16** [comment]
I can try to get a save file

**Comment by crdvis16** [comment]
See attached.

At least for me, the 'Next Turn' button is visible but does nothing when pressed.  The turn will not progress until the gatling gun in Madrid is given an order.  Normally the gatling gun should show up when the "unit needs an order" button is clickable but for some reason it does not.  Pressing 'W' DOES select the gatling gun so whatever logic used there is correctly identifying the gatling gun as the impediment.

I have only VP+EUI installed from the 4-17-2 version.

[Isabella_0282 AD-1824.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4506683/Isabella_0282.AD-1824.zip)

**Comment by Cat-du-Fromage** [comment]
from my observations it happens when: naval unit is created, city-state give you a unit, after a unit upgrade, after a unit attack.

i also enable saving promotion, maybe it is related?

**Comment by crdvis16** [comment]
I don't have promotion saving enabled.

**Comment by ilteroi** [comment]
same old problem, cannot load the save.

anyway both the unit cycler and the end turn check use the same code to check for "ready" units. so it's unclear how they would behave differently.

**Comment by crdvis16** [comment]
That's weird.  Maybe it's just something weird with my install.  I'm glad
'W' finds the unit, though- it makes it a harmless quirk rather than a
tedious bug.
