### ISSUE TITLE
3/15 - Air combat, fighters

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6526]
_1. Mod version (i.e Date - 2/9):_ 3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

There seems to be no difference when using fighters for air sweep or ranged strike if it results in interception. The dogfighting promotions (+ combat strength when conducting air sweeps) do not seem to be working. Fighters do not receive XP when conducting either.

Air strike:
![air strike](https://user-images.githubusercontent.com/59859911/79804506-2c1e2d00-8332-11ea-860f-5fd8a9aca4ff.png)

Air sweep (preview is the exact same), dogfighting promotions have no impact:
![air sweep](https://user-images.githubusercontent.com/59859911/79804512-2e808700-8332-11ea-8e48-c1c0861d2146.png)

The end result is the same in both cases, and not in line with the combat preview:
![image](https://user-images.githubusercontent.com/59859911/79804588-540d9080-8332-11ea-8880-a89138374190.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
what is the expectation here? the mission is aborted after a successful interception

**Comment by silentreply** [comment]
Well I was under the impression that if you use air sweep with dogfighting promotions, the fighter will have higher CS and take less damage from interception. 

Many have commented that there is little incentive to build fighters and that is becoming more apparent to me. They are ineffective at clearing out interceptors and don't get XP for doing so. I don't think air sweep gives XP even without interception. 

I guess they're ok for passive interception - but the AI doesn't respond well, they seem to just not use air units if you put an interceptor in range.

I was going to test out some other things but I just downloaded the new beta. I'll keep an eye on this in the current version.

**Comment by LoneGazebo** [comment]
@ilteroi the TT makes it seem as if the 'sweep' was actually an attack - any chance a right click is performing an attack with air units regardless of whether or not you have air sweep selected?
