### ISSUE TITLE
3/15 - Vassal tribute favors obsolete unique units

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6529]
_1. Mod version (i.e Date - 2/9):_ 3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Vassal tribute seems heavily weighted towards unique units even when they are obsolete. In the below screenshot I entered information era, and all my vassals are in modern or atomic era. Minuteman are from at least two eras before any other gifted unit.

![vassal tribute units information era](https://user-images.githubusercontent.com/59859911/79821625-43bedb00-835d-11ea-8417-6f95d0b40261.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by JamesNinelives** [comment]
Hmm. I kinda like it this way in many cases, but it does seem reasonable to (as Recursive) mentions only do this for units that have promotions which persist on upgrades.
