### ISSUE TITLE
3/15 - Queued air units are not replaced by upgrade unit upon tech discovery

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6530]
_1. Mod version (i.e Date - 2/9):_ 3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
If you have a queued air unit and discover the tech for the upgrade unit, it doesn't seem to be replaced in the queue. From my understanding, for all other units, they will be updated in the queue and the production added to the upgrading unit. 

For instance, below I moved a bomber with one turn left up in the queue, after having discovered tech for heavy bomber. The city just builds the bomber even though it is now obsolete.
![queued bomber upgrade](https://user-images.githubusercontent.com/59859911/79821946-03ac2800-835e-11ea-9a14-ac1341012f7c.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
The check for obsolescence happens the turn 'after' you get a tech, so your 1 turn overflow took place before the obsolescence check.

**Comment by silentreply** [comment]
I'm fairly certain I discovered the tech on T368, then moved a bomber with one turn left up in the queue. On T369, the bomber was completed. I'll check this again in the new version or reload the save to confirm.

**Comment by silentreply** [comment]
Working fine in 4-17.
