### ISSUE TITLE
3/15 - AI cities fail to use city ranged strike 

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6531]
_1. Mod version (i.e Date - 2/9):_ 3-15-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I've noticed that the AI will often fail to use a city ranged strike on units 3 tiles away, particularly if it requires indirect strike and/or the AI has visibility through territory and not a unit.

In the case below, both cities have arsenals but do not use ranged strike on my units.
![ranged strike](https://user-images.githubusercontent.com/59859911/79822280-c4320b80-835e-11ea-8bfe-6555c2a65caa.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
should be fixed already in 4-17
