### ISSUE TITLE
Vassal Description TXT_KEY

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6532]
_1. Mod version (i.e Date - 2/9): 4/10

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0004](https://user-images.githubusercontent.com/49090452/79852729-b8326200-83cf-11ea-853f-a7b32ec1a333.png)

**Comment by Maxxim69** [comment]
I was just going to report the same. :)

![TXT_KEY_DIPLO_MASTER_OF](https://user-images.githubusercontent.com/24704375/79855786-622ce100-8406-11ea-9f9d-211fa14f2745.jpg)
