### ISSUE TITLE
The Vassal of My Vassal is My... Bug?

### ISSUE THREAD

**Issue by Maxxim69** [LoneGazebo/Community-Patch-DLL#6533]
_1. Mod version (i.e Date - 2/9):_
3-15-2 hotfix + 4-7 patch + 4-10 DLL

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) List Enhancements for VP (v 5.2)
(ui) Trade Opportunities for VP
Quick Turns (v 10)
Single Unit Graphics (v 10)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 
In an unexpected turn of events, my vassal Askia (*that magnificent bastard!*) has resurrected our old arch-nemesis Attila, whom I had finally vanquished just a turn ago.
While bastardly behavior by vassals is probably not a sufficient cause for bug reports, the fact that vassals can't have vassals (despite what the message below says) probably is.

4. Screenshots (optional):
![Vassal of my vassal](https://user-images.githubusercontent.com/24704375/79856585-7d4c2080-8407-11ea-8f0a-43373ebb88ab.jpg)

**Comment by RecursiveStar** [comment]
Probably an unexpected consequence of making resurrected civs vassals of their liberators.

**Comment by RecursiveStar** [comment]
I actually find this really funny.

**Comment by LoneGazebo** [comment]
My favorite kind of bugs.

**Comment by RecursiveStar** [comment]
Oh, I see, it's a text issue. Weird. I'll fix.

**Comment by RecursiveStar** [comment]
Okay, should be fixed now.
