### ISSUE TITLE
NOBODY expects the Inquisition... to do nothing at all

### ISSUE THREAD

**Issue by Maxxim69** [LoneGazebo/Community-Patch-DLL#6534]
_1. Mod version (i.e Date - 2/9):_
3-15-2 hotfix + 4-7 patch + 4-10 DLL

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) List Enhancements for VP (v 5.2)
(ui) Trade Opportunities for VP
Quick Turns (v 10)
Single Unit Graphics (v 10)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 
Inquisitor's "Remove Heresy" action does nothing at all (the Inquisitor is nevertheless expended) if numbers of followers of your religion vs. others are tied (the city doesn't have a religion icon). Expected behavior is as per "Remove Heresy" action description, "remove the presence of other religions".

_4. Steps to reproduce (optional):_
1) Load the attached save file;
2) Press F3 to invoke the Unit List and locate the Inquisitor;
3) Attempt to use the "Remove Heresy" action to remove the presence of other religions from Attila's Court;
4) Notice that the action did nothing and the Inquisitor is expended.

4. Screenshots (optional):
![Nobody expects the Inquisition to do nothing at all ](https://user-images.githubusercontent.com/24704375/79858234-0ebc9200-840a-11ea-8eb1-833be5a5b571.jpg)

[AutoSave_0267 AD-1785.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4509495/AutoSave_0267.AD-1785.zip)

**Comment by bigcat88** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/6337

**Comment by ilteroi** [comment]
inquisitor only works on the majority religion ... strange but true. could either change that or disable the inquisition if there is none.

**Comment by LoneGazebo** [comment]
@ilteroi should probably disable that....I'll take point.

G

**Comment by Edaka** [comment]
While we're on the topic, is it WAD that the inquisition belief only gives instant gold per removed foreign follower if by doing so you flip the majority religion from a foreign one to yours? For example, if you use an inquisitor on a city with your majority religion and successfully remove 5 foreign religion followers, you get zero gold for that, probably because there was no 'flip'.
