### ISSUE TITLE
[Question] How does "gCustomMods.is...()" work?

### ISSUE THREAD

**Issue by Serpens66** [LoneGazebo/Community-Patch-DLL#6535]
Is there anywhere a thread, eg in civfanataics where I can ask questions about dll modding that are actually answered? (I wrote several in whowards threads and some dll guides, but no one answers)

I would like to make dll code enabled/disabled by micro mods.
So lets try to undertand it with an easy eample:

```
#define MOD_ANY_PANTHEON						gCustomMods.isANY_PANTHEON()
MOD_OPT_DECL(ANY_PANTHEON);
```
is defined in CustomMods.h and 
`MOD_OPT_CACHE(ANY_PANTHEON);`
in CustomMods.cpp
and the relevant code starts with:
```
#if defined(MOD_ANY_PANTHEON)
	if (MOD_ANY_PANTHEON)
```
where "if defined" is always true as long as we defined it in CustomMods.h, regardless of the value. And "if (MOD_ANY_PANTHEON)" should be the value that was assigned by our mod in xml CustomModOptions.
```
        <CustomModOptions>
		<Update>
			<Where Name="ANY_PANTHEON"/>
			<Set Value="1"/>
		</Update>
	</CustomModOptions>
```

Is this everything? Or is there something I forgot? Eg. I tried to port this feature MOD_ANY_PANTHEON to whowards dll and also added few things on my own, but this "toggle" to enable/disable mods does not work. For some reason "if (MOD_ANY_PANTHEON)" and others are always false, so I think I missed something.. so how does "gCustomMods.is...()" work? Or what did I miss? Everything works when I do `#define MOD_ANY_PANTHEON						(true)` instead.

edit:
**Does this xml Update command also add a new entry? Maybe I have to adjust the CustomModOptions table to include this new entry?**

**Comment by ilteroi** [comment]
i think you need to 'insert' instead of 'update' the new flag
