### ISSUE TITLE
Incorrect Possible Yield Tooltips (Road/Railroad on Village)

### ISSUE THREAD

**Issue by Maxxim69** [LoneGazebo/Community-Patch-DLL#6536]
_1. Mod version (i.e Date - 2/9):_
3-15-2 hotfix + 4-7 patch + 4-10 DLL

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) List Enhancements for VP (v 5.2)
(ui) Trade Opportunities for VP
Quick Turns (v 10)
Single Unit Graphics (v 10)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 
Incorrect possible yield tooltips displayed for worker actions such as constructing/removing [rail]roads (see screenshot). Expected behavior is +1p +1c on constructing a railroad on a Village hex.

4. Screenshots (optional):
![Misleading Road Tooltip](https://user-images.githubusercontent.com/24704375/79869981-3537f880-841d-11ea-8093-407af7087ed8.jpg)

**Comment by LoneGazebo** [comment]
Yes, those EUI elements are virtually worthless, can ignore. Should probably remove them entirely.
