### ISSUE TITLE
GoldenAgePoints Hook not properly merged

### ISSUE THREAD

**Issue by iskaandismet** [LoneGazebo/Community-Patch-DLL#6538]
This pull: https://github.com/LoneGazebo/Community-Patch-DLL/pull/6493 was merged, but I can't find the code for the hook while searching through the repo.

**Comment by iskaandismet** [comment]
Is this really going to be ignored? :| Did I made a mistake and miss it while looking in the repo? Should I do another pull request?

**Comment by LoneGazebo** [comment]
Hm? My PC is inaccessible right now. Haven’t done any pull requests.
