### ISSUE TITLE
4/17 - Improved resources from formerly razed cities are not connected

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6542]
_1. Mod version (i.e Date - 2/9):_ 4-17-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
A silk plantation formerly belonged to a Japan city that has been razed. It's now in range and being worked by a Huns city but the silk is not connected. 

It would seem only way to connect it at this point is to put a GP improvement on it. 

![image](https://user-images.githubusercontent.com/59859911/80044722-6541d300-84d3-11ea-8621-d63069b03a04.png)
![image](https://user-images.githubusercontent.com/59859911/80044731-696df080-84d3-11ea-833f-4788cbe75018.png)

Originally posted on forums - https://forums.civfanatics.com/threads/yet-another-bug-in-vox-populi-version-4-17.657290/#post-15739337

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Best guess is that this is a vanilla bug, since the tile is likely not having its working city' connection tested. You could probably remove and readd the plantation via firetuner to test.

**Comment by bigcat88** [comment]
I cant reproduce.
AI settle a city, I improve resource with IGE. Pillage, raze, wait till my city border expands - resource fine.
When I pillage and then conquer-raze and then repair - it works fine too.

**Comment by LoneGazebo** [comment]
hmm
