### ISSUE TITLE
4/17 - Player as Vassal Still Causing Text Spam.

### ISSUE THREAD

**Issue by AnemoneMeer** [LoneGazebo/Community-Patch-DLL#6543]
_1. Mod version (i.e Date - 2/9):_ 4/17

_2. Mod list (if using Vox Populi only, leave blank):_
Tested with only Vox Populi. Tested again with Ingame Editor.

_3. Error description:_ 
Every turn that passes when player is vassalized, causes a text popup for tax change.

_4. Steps to reproduce (optional):_
Become player vassal.

Decided to test this again just to make sure it's fixed. Tried a clean install of VP as well, didn't fix it. Not sure at this point if it's my computer or just a bug with player vassal still. Going back to earlier versions removes the bug though.

**Comment by RecursiveStar** [comment]
No idea...

**Comment by RecursiveStar** [comment]
Think I've found the issue! Will fix :)
