### ISSUE TITLE
4/17 - Zoc Possible Issue

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6545]
_1. Mod version (i.e Date - 2/9): 4-17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:

I don't know if this is intended or not (but I don't remember being this way), but if you have two units adjacent to each other and with a city (with a garrison) you can't switch them (even though you have MP).

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

WITH garrison you can't switch units
![a](https://user-images.githubusercontent.com/49090452/80074738-4fbfbe00-8552-11ea-85b3-e92e7c2decca.png)
![b](https://user-images.githubusercontent.com/49090452/80074743-50f0eb00-8552-11ea-90c0-49d4ba92f9ad.png)

WITHOUT a garrison you CAN  switch
![c](https://user-images.githubusercontent.com/49090452/80074748-52baae80-8552-11ea-894f-d2884a14396c.png)

**Comment by RecursiveStar** [comment]
Are you sure one of the units isn't asleep or fortified in your first example?

**Comment by Aqinu** [comment]
Yes, I am sure, you can also test it with IGE...

**Comment by Aqinu** [comment]
Apparently the issue is with the units, you can't switch them now if adjacent to enemy unit...
![a](https://user-images.githubusercontent.com/49090452/80186349-86f7a300-8616-11ea-9d3a-4bb578daea29.png)

**Comment by ilteroi** [comment]
yeah that's an rule to prevent AI stupidity ... easy to disable the check for human players

**Comment by silentreply** [comment]
From what I've seen only one of the units needs to be adjacent to an enemy unit:
![image](https://user-images.githubusercontent.com/59859911/80291942-f9a07580-871f-11ea-82e6-6dbbff2c1f85.png)

**Comment by azum4roll** [comment]
Is the "AI stupidity" check disabled as well for AI units that ignore ZOC?
