### ISSUE TITLE
4/17 - Units gaining extra XP from combat

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6546]
_1. Mod version (i.e Date - 2/9):_ 4-17-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Units are frequently receiving extra XP from combat. I am observing 6 XP from ranged attacks (and defense) very frequently. Occasionally I have seen melee units receive 15 XP from melee attacks.

Related issue - in the 3-17-2 beta I also noticed that bombers were receiving 4 XP when attacking city-states with garrisons, and the usual XP cap was not in effect - allowing you to farm XP for bombers. I haven't reached the tech yet in my game to confirm if this is also the case in the current beta. 

There are no XP bonuses (i.e. strategic monopoly) in effect in such cases I am aware of.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/blob/36abcf712ed44835750b89d9976272eb33d7e76d/CvGameCoreDLL_Expansion2/CvUnit.cpp#L21410

Issue is here, I think, as it is the only thing changed this version WRT XP.

**Comment by LoneGazebo** [comment]
this section. If someone wants to test for me, that'd be great @ilteroi @RecursiveStar :)

**Comment by RecursiveStar** [comment]
Sorry, not available today - too busy with work. :(

**Comment by ilteroi** [comment]
i can confirm it's the problem but i don't know how to fix it :)

**Comment by bigcat88** [comment]
I can see invalid behaviour only with Order policy. 17 xp instead of 7.
If someone can say what mod(MOD_UNITS_XP_TIMES_100) do - that will helps.

`iCombatExperienceMod += (getDomainType() == DOMAIN_LAND ? kPlayer.getDomesticGreatGeneralRateModifier() : 0) + kPlayer.getExpInBorderModifier();`

After attacking with melee unit I got:
iCombatExperienceMod  = 250. I suggest that it is a percent rate of exp.
If by default we have 5 exp from attack, then 5 + 250% = 17,5

getDomesticGreatGeneralRateModifier return 100.

**Comment by bigcat88** [comment]
Also a stupid question maybe. 
What is **getDomesticGreatGeneralRateModifier** ? Rate at which GG points are created? If yes - what does it do in calculating exp?

**Comment by kawyua** [comment]
https://forums.civfanatics.com/threads/my-fastest-domination-victory-ever-turn-206-immortal-mongolia.658716/

in this thread someone mentioned that hit cities with units in them gives this extra xp?
[QUOTE="Antix, post: 15786086, member: 312515"]It seems like you get 6XP if you attack cities with ranged attacks and not when you attack units, my bad.
With Logistics you are able to get 12EXP per Turn and potentially even a bit more, if you tank 1 shot of city bombardment (i did not do that, too risky)[/QUOTE]

**Comment by adaneslavo** [comment]
I mentioned it here but maybe it is related: Can XP arise over time? I set dummies giving global XP. Reset them with lua, set them again. Number is 0 or f.e. 3 at some moments. But turn by turn number of XP given is rising. Checked number of dummies with IGE.

https://github.com/LoneGazebo/Community-Patch-DLL/issues/6595
