### ISSUE TITLE
4/17 - Tradition +2 happiness in capital

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6548]
_1. Mod version (i.e Date - 2/9):_ 4-17-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Adopting tradition grants +2 happiness in the capital. In AI capitals under espionage screen, this happiness seems to appear as "+2 for being the capital." However this happiness source is not visible in the player capital.

This may be just be a UI thing and the happiness is counted elsewhere (on palace?), but from my attempts to add up all the happiness from buildings in both capitals, it seems it is not counted. 

Player capital:
![image](https://user-images.githubusercontent.com/59859911/80102059-44fc2d80-8540-11ea-8e16-c741c70545c1.png)

AI capital:
![image](https://user-images.githubusercontent.com/59859911/80102867-64e02100-8541-11ea-9592-35135cba9cc2.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveStar** [comment]
2 for "being the capital" is a local happiness bonus to the capital from difficulty level. Not a result of adopting Tradition.
