### ISSUE TITLE
4-17-2 City States killing all the Barbs

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#6551]
_1. Mod version: 4/17-2

_2. Mod list (if using Vox Populi only, leave blank):
4UC
New Beliefs
Some custom civs (Timurids, Israel, Khmer)

_3. Error description:
Discussion from the CFC Forum post:

- The City-States are damned axe murderers right now. This has been the case for many versions now, but I only had 2 in proximity to my start and I think they cleared more barb camps than I did. They threw my entire early game into jeopardy because they thinned the flow of barbs too effectively, and they nearly cost me a religion (god of war). I shudder to think if I had a third CS neighbor. I wonder if they could let just... not clear barb camps? Like ancient ruins, what if the CS just weren’t able to move onto those tiles, or otherwise ignored camp tiles, and needed a major civ to disperse them?
 
This has been noted in several versions now. I'm wondering if the city-states' active barb hunting is intentional? If so, it's a huge balance concern for the God of War/Morrigan beliefs and Authority policy tree.

**Comment by ilteroi** [comment]
minors should only target camps adjacent to their borders ...

**Comment by bigcat88** [comment]
In my last game on 4-17-2 I have a CS behaviour like ilteroi says...

**Comment by LoneGazebo** [comment]
@ilteroi let's have CSs not target barb camps at all.

**Comment by ilteroi** [comment]
well, after thinking about it some more, maybe they don't target the camp specifically but the enemy unit inside. there is no distance check there ...

so what should be the rule for attacking enemy units?

**Comment by RecursiveStar** [comment]
You could have them ignore units in or adjacent to encampments unless in or adjacent to their borders?

**Comment by RecursiveStar** [comment]
In an old changelog, one of the listed features of VP was that City-States would actively attack players they're at war with, and I thought that was cool, made them less useless militarily as allies.

The problem with Barbarians is that it interferes with authority and quest completion, so they could be excluded specifically.

**Comment by RecursiveStar** [comment]
Maybe you could exclude Barbarian units that are inside their ally's borders, too...so they'd defend their ally.

**Comment by adaneslavo** [comment]
But their agressiveness towards civilizations at war is still not so big.

**Comment by RecursiveStar** [comment]
Well, my suggested check for City-States is:
```
Ignore Barbarian encampments unless adjacent to our borders

Ignore Barbarian units unless:
- In or adjacent to our borders
- In our ally's borders

For enemy cities, or non-Barbarian enemy units:
- Attack them if we can without putting ourselves at risk
```

**Comment by pineappledan** [comment]
Personally, I would just make it so city-states either don't clear barb camps if they walk over them, or they can't enter tiles with barb camps. Whichever one is easier to do.

I don't have a problem with city-states roaming from their borders and hunting barbarians, but I really don't like that they can clear camps. It causes 2 problems:

1. They can "stem the tide" of barb generation without a major civ's help, and can sometimes "solve" a barbarian problem entirely if there are 2+ city states packed together. It feels like a dead zone in the early game map where there is nothing going on as a result.
2. They will often revoke their own barbarian quests by clearing camps they have offered quests for. This is especially frustrating if you have moved units to kill those barbs, but the CS snipes the camp, or clears it while you are still moving your units. It's a waste of turns and can be very frustrating to have the CS divert your troops for a boondoggle.

**Comment by adaneslavo** [comment]
And weakens Authority.

**Comment by ilteroi** [comment]
ok minors cannot enter barbarian camps anymore
