### ISSUE TITLE
4/17 - Capitulate option doesn't work, neither liberate

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6552]
_1. Mod version (i.e Date - 3/15): 4/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

I try to capitulate Greece (100 war score with both of them; his vassal) but I think because he has a vassal I can't do it, neither to liberate the enemy's vassal (I don't know how this option is suppose to work, even if it works, never used it).

Also there are not explanations in the tooltip if there is a reason why the option doesn't work in case is not a bug.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![a](https://user-images.githubusercontent.com/49090452/80278123-63a72380-86fc-11ea-94da-41a2605f92c3.png)

![d](https://user-images.githubusercontent.com/49090452/80278268-85ed7100-86fd-11ea-9733-806478681e65.png)

![b](https://user-images.githubusercontent.com/49090452/80278127-6570e700-86fc-11ea-831a-0ec602da457e.png)

![c](https://user-images.githubusercontent.com/49090452/80278129-66a21400-86fc-11ea-8abd-d8dcb271bad0.png)

**Comment by bigcat88** [comment]
It's always was like this.
Only player without vassals can be vassalized.

**Comment by RecursiveStar** [comment]
Intended, I think.
