### ISSUE TITLE
Freedom of navigation through waters

### ISSUE THREAD

**Issue by ryanmusante** [LoneGazebo/Community-Patch-DLL#6555]
Mod version (i.e Date - 3/15):_
4/17

Error description:_ 
In reference to ocean tiles claimed by cities, shouldn't it be possible for civs to always navigate through waters uninhibited?

---------------------------
Supporting information:

![mDsu4oU](https://user-images.githubusercontent.com/26808646/80303926-02b53500-8768-11ea-872c-9c5ea25bc6b1.jpg)

![q1CKm2k](https://user-images.githubusercontent.com/26808646/80303927-03e66200-8768-11ea-9270-42fccb95a868.jpg)

Civ expanding far beyond the city seems counterintuitive to design. Shouldn't waters be neutral territory?

**Comment by ilteroi** [comment]
hmm. interesting idea. we could limit the border spread on deep water to the city's working range. why don't you make a poll on the forum?
