### ISSUE TITLE
Merge error

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6557]
@LoneGazebo There seems to have been an error while merging Aqinu's fork; changes were made to CPP files.

**Comment by Aqinu** [comment]
@LoneGazebo I think I did something wrong, should I make a request with 'revert pull request'?

**Comment by RecursiveStar** [comment]
@Aqinu Fixed it, no worries. :)

**Comment by Aqinu** [comment]
@LoneGazebo You have to worry cause I didn't fix anything upstream...
