### ISSUE TITLE
4/17 - Orthodoxy enhancer belief too strong?

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6559]
_1. Mod version (i.e Date - 3/15):_ 4-17-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Orthodoxy enhancer belief increases religious pressure strength and distance, and doubles pressure to cities connected by trade routes. I'm not sure this is working correctly.

Notice I am not receiving any pressure from Islam despite being in trade route range. If I attempt to  send a trade route to a Ottoman city with Islam, the pressure from those trade routes is 5X or greater (42+) than routes to cities of other religions, or to city-states following Islam (4-9). 

I don't see an explanation for: 
1. Why is Islam not already applying pressure given it is in trade route distance, and has increased pressure distance?
2. If they are not applying passive pressure, how would "doubling" that pressure by connecting a trade route explain these massive pressure values from trade routes (42+)?

![image](https://user-images.githubusercontent.com/59859911/80350950-7aa25e80-883f-11ea-92d3-41a6ab447ee8.png)
![image](https://user-images.githubusercontent.com/59859911/80351006-9d347780-883f-11ea-9948-d99777b2dd88.png)
![image](https://user-images.githubusercontent.com/59859911/80350875-5ba3cc80-883f-11ea-8f6c-d80030955068.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by pineappledan** [comment]
My new beliefs mod splits the TR pressure off from the passive distance/power multipliers, and I think it has helped balance this belief considerably. The TR pressure power is quite considerable on its own, and I wonder if the 20% passive multiplier is stacking with the TR multiplier to give a real bonus of 2.4x TR pressure?
