### ISSUE TITLE
Bonus resources not shown in yields

### ISSUE THREAD

**Issue by CunningGabe** [LoneGazebo/Community-Patch-DLL#656]
Playing the 9/24 version with EUI. I have the yield icons shown on the map. Tiles with bonus resources that are not in my territory are not showing the correct yields. For example, a coastal tile with fish shows 2 food when not in my territory and 3 food when in my territory, even though I have no buildings in the city that affect that.

**Comment by CunningGabe** [comment]
Looking at it a bit more, it seems to only affect fish maybe. Also, there is one fish coastal tile I can see that is showing the correct yields (and isn't in my territory), which puzzles me even more.

**Comment by CunningGabe** [comment]
Over time, some of the bonus tiles are changing to show correct yields, but it is unpredictable which. I guess this is just some sort of refresh issue.

**Comment by LoneGazebo** [comment]
Outside your territory? Sounds like a cached value performance element.

**Comment by Iamblichos** [comment]
Yep. Horse on grass popup as two food in your territory and then 2 food + 1 prod when your territory acquires the tile.

**Comment by LoneGazebo** [comment]
That's fine. It's a caching issue. Why do we need extra values for things outside your territory? Big maps slow to a crawl because of that excess computation.

**Comment by CunningGabe** [comment]
Well, it's nice when you are trying to decide where to expand. I don't know the yields well enough to always catch when it is showing me something incorrect.

**Comment by Iamblichos** [comment]
Not a big deal. I usually turn off yields most of the time anyways.
