### ISSUE TITLE
CTD after year 2050

### ISSUE THREAD

**Issue by MilkyP** [LoneGazebo/Community-Patch-DLL#6561]
[Gandhi_0500 AD-2050-January.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4540386/Gandhi_0500.AD-2050-January.zip)
_1. Mod version (i.e Date - 3/15):_
New Beta Version - April 17th - (4-17) with Hotfix

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
CTD during year 2050. Happens generally in July of that year. All victory conditions enabled apart from time limit. 
Events enabled.
Using mapscript Communtias_79a version 1.16,1 
Note that this has happened in two separate games with same setup but different leaders.
I've also noticed that the size of the save file changes??

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Gandhi_0500 AD-2050-January.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4540398/Gandhi_0500.AD-2050-January.zip)
[Gandhi_0501 AD-2050-July.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4540399/Gandhi_0501.AD-2050-July.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4540418/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by bigcat88** [comment]
Looks like **not enough memory** problem.
1.9Gb used by civ.
After setting all video settings to minimal and in strategic view I can pass further..(also after setting settings to minimal many textures dissapears)


[Gandhi_0503 AD-2051-July.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4541723/Gandhi_0503.AD-2051-July.zip)
![image](https://user-images.githubusercontent.com/13381981/80413888-d4a33280-88d8-11ea-9217-8b975c7e0244.png)

**Comment by MilkyP** [comment]
Ok thanks. I’ll try changing the settings and see if that helps. Just seems strange that the CTD happens in 2050 in two separate games.

**Comment by MilkyP** [comment]
I’ve lowered the graphics settings and managed to complete the game. Thanks for your help 👍

**Comment by azum4roll** [comment]
As soon as the game reaches turn 500, weird stuff happens.

![image](https://user-images.githubusercontent.com/14953746/84596420-3a02b100-ae90-11ea-9c43-473cc978c910.png)

The Huns is actually getting lots of yields in a short time (around 10k culture per turn, quickly dropping Venice's influence, as well as 1 tech per turn). I wonder if something has overflown.
