### ISSUE TITLE
City default tile selection leads to starvation

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#6563]
_1. Mod version: 4-17-2

_2. Mod list:

_3. Error description: City default tile selection seems to not take into account starvation although tiles with more food are available.

---------------------------
Supporting information:
4. Screenshot:
![image](https://user-images.githubusercontent.com/64471766/80480062-4c607400-8950-11ea-9bb3-86b18ede786d.png)

**Comment by Zuizgond** [comment]
Another case :
![image](https://user-images.githubusercontent.com/64471766/81926979-2ccd7a80-95e3-11ea-91a4-7ef5a02234f3.png)
Seems like it chooses tiles with the most yield (2p2g) but then chooses to starve the city as it cannot find 4f to compensate.

**Comment by JamesNinelives** [comment]
Here's a case of it happening in my game. Not really sure why tbh.

![20200525005912_1](https://user-images.githubusercontent.com/61379041/83229690-fedb5f00-a1ba-11ea-8c1a-5f8b834aace1.jpg)
