### ISSUE TITLE
4/17 - Shadow networks (statecraft) policy bugged?

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6564]
_1. Mod version (i.e Date - 4/17):_ 4-17-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:
Shadow networks (statecraft) policy provides 33% of science generated by allied city states. Observed science is much lower than expected. On turn 217 I'm receiving 0.47 science from Panama City. I believe the total science received from this policy appears in the UI under "scholasticism" (old policy name - can we update?). I have 8 allied city states giving a total of 9.73 science. 

![image](https://user-images.githubusercontent.com/59859911/80625372-1d630480-8a1b-11ea-9c38-e31422ee355c.png)
![image](https://user-images.githubusercontent.com/59859911/80625802-b6921b00-8a1b-11ea-9f66-a13748aad1db.png)
![image](https://user-images.githubusercontent.com/59859911/80625464-3cfa2d00-8a1b-11ea-81d8-ccaf4d9e05a3.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by silentreply** [comment]
Yields from this policy are clearly decreasing with time and/or number of allied CS

T180, 4 allied CS, 28.57 sci:
![image](https://user-images.githubusercontent.com/59859911/80875102-adf24c80-8c88-11ea-8472-40db7c93c43d.png)

T334, 12 ish allied CS, 4.37 sci:
![image](https://user-images.githubusercontent.com/59859911/80873963-5a7ffe80-8c88-11ea-9179-49009f61079b.png)

**Comment by LoneGazebo** [comment]
It is based on the science of the minor civ, which can fluctuate over time.

**Comment by silentreply** [comment]
@LoneGazebo Yes it may fluctuate, but doesn't this seem too extreme to be just fluctuation? The low values are consistent from turn to turn. Each CS would have to be making around 1-2 SPT total to explain the scenario on turn 334, yet each makes 3 SPT from the embassy tile alone.

**Comment by LoneGazebo** [comment]
That's assuming the AI is working that tile.

**Comment by LoneGazebo** [comment]
Also the function gets 33% of _each_ CS's science and adds them all together.

**Comment by silentreply** [comment]
Ok, I'll keep an eye on it in my next game.
