### ISSUE TITLE
4/17 - Gold purchase of diplomatic units puts cooldown on civilian units

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6567]
_1. Mod version (i.e Date - 4/17):_ 4-17-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Gold purchase of diplomatic units puts cooldown on purchase of civilian units. Intended?
![image](https://user-images.githubusercontent.com/59859911/80720561-1693ca80-8acb-11ea-96ce-600f4cead184.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Yes, all civilian units are on the cooldown system for civilians.

**Comment by silentreply** [comment]
@LoneGazebo Only diplomatic units are triggering this extended cool down period. It seems the cooldown gets longer throughout the game, but by late game it is 5 turns on the purchase of all units. 

Whereas if you buy a civilian or military unit, you can purchase one again in the same city the next turn. Also if you buy a military unit, you can still purchase a worker, work boat, or diplomatic unit the same turn in the same city, but not vice versa.
