### ISSUE TITLE
4/17 - Can't starve cities in resistance

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6568]
_1. Mod version (i.e Date - 4/17):_ 4-17-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Cities won't starve during resistance. Was something put in place this version to stop cities starving during resistance (#6467)? It seems the -100% growth modifier (unhappiness from unrest) during resistance is gone.

This city has been at 21 pop since capture. 
![image](https://user-images.githubusercontent.com/59859911/80735649-01289b80-8adf-11ea-8ff8-ec46523dc153.png)

-100% growth modifier is gone:
![image](https://user-images.githubusercontent.com/59859911/80736016-8dd35980-8adf-11ea-8de1-00b34e59b4bb.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
seems to be intentional ...

```
	// No growth or starvation if being razed
	if(IsRazing())
	{
		return;
	}
	//No growth or starvation if in resistance
	if(IsResistance())
	{
		return;
	}
```

**Comment by RecursiveStar** [comment]
Pretty sure it's been that way for a loooong time, possibly since vanilla.

**Comment by silentreply** [comment]
@RecursiveStar From memory I think it has been possible to starve cities in resistance, but I haven't had a chance to check a save from last version. The code above may have been added to address the bug report I linked from last version. 

I'm sure there's a faster way to just compare the code but I'm not savvy in that regard.
