### ISSUE TITLE
4/17 - Enemy units recieve full warmonger fervor in vassal and allied CS territory

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6569]
_1. Mod version (i.e Date - 4/17):_ 4-17-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Enemy units recieve full warmonger fervor in territory of vassals and allied city-states. Previously reported for 3-15 version #6513.

Allied CS:
![image](https://user-images.githubusercontent.com/59859911/80747036-c62f6380-8af0-11ea-9a4c-5b0f33a067ca.png)

Vassal (45%):
![image](https://user-images.githubusercontent.com/59859911/80747640-c1b77a80-8af1-11ea-8728-71f2cbe5e1f3.png)

Neutral territory (22%):
![image](https://user-images.githubusercontent.com/59859911/80748255-a00ac300-8af2-11ea-8cec-338c75aae40b.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveStar** [comment]
Now that I think about it, Greece's UA, as written, should allow for it to have no anti-warmonger fervor in City-State territory unless at war with the CS, since their units are treated as being in friendly territory.
