### ISSUE TITLE
4/17 - Air supremacy (T3 autocracy) tenet does not provide production boost to missiles

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6570]
_1. Mod version (i.e Date - 4/17):_ 4/-17-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Air supremacy (T3 autocracy) tenet does not provide production boost to missiles or nukes. Text states "+25% production when building air units." The production modifier is listed as "empire modifier for unit combat class."

The military base uses similar text "+25% production of air units," and does indeed apply to missiles. Modifier is listed as "modifier for unit domain." 

![image](https://user-images.githubusercontent.com/59859911/80764442-b9ba0380-8b0e-11ea-809f-13e15ba14ec1.png)
![image](https://user-images.githubusercontent.com/59859911/80764477-c8a0b600-8b0e-11ea-986b-fed7e1a00609.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
They technically don't have a combat class, so this is intended.

**Comment by silentreply** [comment]
@LoneGazebo Should the military base not provide the production boost then? I always liked that it did, since it makes cities with military base more optimal for building missiles/bombs. 

The air supremacy tenet text could just be changed to "+25% to production of planes."

**Comment by LoneGazebo** [comment]
I can change the tenet.
