### ISSUE TITLE
4/17 - Unusual lux distribution to city-states

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6575]
_1. Mod version (i.e Date - 4/17):_ 4-17-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In my recent game there were 14 ivory distributed to city states. Map size was standard. I have never observed more than 8 copies of a lux on standard size map. Indeed there were no other lux with more than 8 on the map. 

Map: Communitu_79a v1.16
Size: Standard
Settings: all standard, except +2 city-states (18 vs 16)

tu_79 said the map script does not touch anything involving lux distribution. 

![image](https://user-images.githubusercontent.com/59859911/80892345-45f73280-8c97-11ea-8200-6795234cc1e3.png)

Interestingly, during the early game the monopoly page indicated there were only 8 ivory:
![image](https://user-images.githubusercontent.com/59859911/80892309-0b8d9580-8c97-11ea-93bb-4f78f09acb14.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Vyyt02** [comment]
I've never thought much about this, but I think that I see 1 kind of lux distributed among the majority of CSes quite often (I play mostly huge and crowded Tectonic btw)

**Comment by JamesNinelives** [comment]
I see the same as you Vyyt. It's never occured to me to count them though. I guess I will check next game to see if the number is consistent with other luxes.
