### ISSUE TITLE
Running out of Great Writers/Musicians/Artists

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6577]
_1. Mod version (i.e Date - 4/17):_ Latest

There have been numerous reports across several versions about this problem: eventually Great Works of Writing, Art and Music become impossible to obtain because all of them have been "used up".

I think that in such an event, a generic GP and GW should be created rather than not allowing any more Works to be created.

This problem occurs more often on larger maps.

**Comment by ilteroi** [comment]
there are mods to fix that, add more names to the pool

**Comment by RecursiveStar** [comment]
In that case, I think we should integrate a fix into VP? @LoneGazebo

**Comment by RecursiveStar** [comment]
I still think that, in the event that the names in the pool run out, rather than blocking Great Works from being created, a generic one should be created.

**Comment by LoneGazebo** [comment]
That's tricky to do - there's no supported functionality for a default value for those at this time. The solution is easy, just install the more GPs mod.

G

**Comment by RecursiveStar** [comment]
Could more GPs be integrated into VP, then? The idea that people need to install another mod to fix a bug in base VP kinda irks me. :)

**Comment by LoneGazebo** [comment]
it only happens if you're running a supermassive map and civs.

**Comment by azum4roll** [comment]
It starts happening recently because every civ is given a free Great Writer from Heroic Epic. With a few cultural civs it's easy to run out of Great Writings in Classical.

**Comment by pineappledan** [comment]
Sounds like at least 8 new GWriters are needed just to keep the same real number of GWriters in the game...

**Comment by Stalker012345** [comment]
> it only happens if you're running a supermassive map and civs.

I'll disagree with this G, it happens every time I play Tradition civs nowadays. The issue is common.

Ultimately I agree with you all that there's no reason for you devs to spend effort on something when there are perfectly good modmods to accomplish it, but the project has included others modmods before, and if the modmod designer is agreeable I say we just add it in to the list.

**Comment by JamesNinelives** [comment]
I agree with Stalker and the others. It's not a big deal but it does happen more often since the AI are better are producing great works now :).
