### ISSUE TITLE
Probable coding error affecting diplomacy

### ISSUE THREAD

**Issue by psparky** [LoneGazebo/Community-Patch-DLL#6578]
Found in my old version but still appears present in 4-17

In file CvMinorCivAI.cpp, routine DoSetBonus, this line of code:
`if (bPassedBySomeone && eNewAlly != NO_PLAYER)
					
   GET_PLAYER(eOldAlly).GetDiplomacyAI()->ChangeNumTimesTheyLoweredOurInfluence(eNewAlly, 1);`
				
is executed in a loop for each civ, related to notifications. This means that NumTimesTheyLoweredOurInfluence gets greatly inflated, often causing the Minor Civ Dispute level to be too high, typically Fierce. I think this code should be before the loop so that the count is only increased once for each occurrence of a new ally.

**Comment by RecursiveStar** [comment]
Recursioooooooon!

I'll fix, thanks for finding.

**Comment by psparky** [comment]
I have a supplementary question related to this. I've been logging the values of NumTimesTheyLoweredOurInfluence and found some negative values! Nothing in the normal code would explain this - it starts at zero and gets incremented by 1 in various places.

I'm wondering if it might be related to the save/load mechanism. I found this code:

	ArrayWrapper<char> wrapm_paiTheyLoweredOurInfluence(MAX_MAJOR_CIVS, m_paiTheyLoweredOurInfluence);
	kStream >> wrapm_paiTheyLoweredOurInfluence;

Does the <char> here mean the values are converted to signed bytes, and then sign-extended back to integers on load? If so, then it makes sense and all is well (as after the fix the numbers should be less than 128). If not, there is a mystery here.

**Comment by RecursiveStar** [comment]
@psparky I'm honestly not sure. The diplo memory management system is a source of endless hindrance and confusion to me, as I mentioned in #6375. I'm working on getting a better understanding of it.

**Comment by RecursiveStar** [comment]
There definitely should not be any negative values for NumTimesTheyLoweredOurInfluence, though.

**Comment by psparky** [comment]
Thanks for the reply - I'll monitor it to see if there are any new occurrences now that the main bug is fixed and raise a new issue if so.

**Comment by psparky** [comment]
OK, did some more testing and it's nothing to do with the save/load cycle. These numbers ARE signed bytes at all times. If the value goes beyond 127 it will become negative. As the bug was causing an increase of 21 rather than 1 for each occurrence, it would overflow pretty easily. This meant that if you transgressed enough, then suddenly all was forgiven :)

**Comment by RecursiveStar** [comment]
Ah, integer overflow. Classic. I'll change the variable type.

**Comment by ilteroi** [comment]
well, we tried to minimize the memory footprint at one point because it seemed that multiplayer desyncs are more frequent the more data has to be transferred. so maybe it's better to put in a simple check and only increment if <127

**Comment by psparky** [comment]
Now the main bug is fixed, it's pretty unlikely to exceed 127, and even if it did, the result would still be Fierce dispute level. Adding a cap, just in case, as ilteroi suggests, seems like a good solution.

**Comment by LoneGazebo** [comment]
@ilteroi at some point let’s do another series of MP tests

**Comment by RecursiveStar** [comment]
@ilteroi Sure, but I still maintain that fixing the diplo AI's memory system (#6375) would be a better initial approach to this problem. :)

**Comment by ilteroi** [comment]
i'm saying this seems like a step in the wrong direction, especially since a less invasive fix is possible.

**Comment by LoneGazebo** [comment]
@RecursiveStar biggest issue is that we don't know if there's another, different reason that Firaxis did it that way which we can't control.

**Comment by LoneGazebo** [comment]
besides I'd wager 99.9% of the desyncs are movement and combat related.

**Comment by RecursiveStar** [comment]
well I capped NumTimesTheyLoweredOurInfluence and NumTimesTheyPlottedAgainstUs at 0 and 127 in my latest pull request (which will be submitted shortly).

@LoneGazebo Personally, I still think it's worth testing, at least...I'd be willing to do any work necessary to test a fixed system, I just don't know how to code it :)

**Comment by RecursiveStar** [comment]
@ilteroi Just to note, there are a lot of <short> values in the diplo AI memory, for counters and the like, and that doesn't seem to cause any problems.

**Comment by RecursiveStar** [comment]
According to Google, char = 1 byte, short = 2 bytes, int = 4 bytes.

Even if it was made into an int value and multiplied by REALLY_MAX_PLAYERS (80), that's still only 320 bytes, or 0.32 KB, which is negligible, since a single MB could accomodate 3125 integer memory values for every player, and Civ's memory usage is in GB.

I'm by no means an expert about data processing rates in Civ, but it doesn't seem like a big deal to me?

**Comment by ilteroi** [comment]
this discussion is much too long already for a very minor issue that is already solved.
