### ISSUE TITLE
new patch for 4-17

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6579]
hey all, here's a new patch release with all the latest bugfixes from hcw and me. goes on top of 4-17. should be savegame-compatible even.

[CvGameCore_Expansion2_6baa43f4e2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4571138/CvGameCore_Expansion2_6baa43f4e2.zip)

**Comment by JamesNinelives** [comment]
Wonderful, thank you! Hope you are well ilteroi :).

**Comment by bigcat88** [comment]
will be there any new betas/patches soon?

**Comment by RecursiveStar** [comment]
I posted the current master branch build (which has both of our fixes) on the forums as the 5-15 DLL: https://forums.civfanatics.com/threads/new-beta-version-april-17th-4-17.657164/page-21#post-15762699
