### ISSUE TITLE
Lack of Resource Notifications piling up

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#658]
If your supply of strategic resource like iron or horse is not enough to support your units, you get a notification. So far so good, but they keep coming every turn. And you cannot dismiss them!

Ideal behavior would be 
a) they go away after right-click like all others 
b) you never have more than one notification of the same type - ie delete the stale ones at the end of the turn

I suspect it's a LUA issue ...

**Comment by LoneGazebo** [comment]
I've changed the notification type in the latest version, I think it uses the EUI stacking code (so it should go away). We'll see.

G
