### ISSUE TITLE
city production automation

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6580]
there is a mod which allows to automate production for non-puppet cities ([reference](https://forums.civfanatics.com/resources/auto-production-cities.27467/))

it simply sets the "ProductionAutomated" flag for the city in question on a button click in the city screen.

could we do this in VP as well? it's a nice comfort feature and also it allows easier testing of the production AI ...

**Comment by RecursiveStar** [comment]
I second this.

**Comment by pineappledan** [comment]
I wonder if this feature would address a bug i'm having with my Phoenicia custom civ...

**Comment by ilteroi** [comment]
i've made a first attempt to add that feature but it does not work ... can somebody with more lua experience take a look? it's in the "automate" branch.
