### ISSUE TITLE
Coding questions re: player loop

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6581]
Coding questions for player loops:

So as I understand it, if you do
`for (int iPlayerLoop = 0; iPlayerLoop < MAX_CIV_PLAYERS; iPlayerLoop++)`

Player -1 is NO_PLAYER
Player 0 to the slot just before MAX_MAJOR_CIVS (21?) are major civ slots
Player MAX_MAJOR_CIVS to just before MAX_CIV_PLAYERS (62?) are minor civ slots

**Question 1:** Where is the Barbarian player? At the MAX_CIV_PLAYERS position?

 **Question 2:** If a slot is empty, does changing anything in that slot do anything?
For example:
```
for (int iPlayerLoop = 0; iPlayerLoop < MAX_MAJOR_CIVS; iPlayerLoop++)
{
  PlayerTypes eLoopPlayer = (PlayerTypes) iPlayerLoop;
  SetValueForPlayer(eLoopPlayer, true);
}
```
Now suppose a new City-State comes into existence via revolution and occupies one of the Minor Civ slots. Would the new value apply to that player even though they didn't exist at the time it was set?

**Question 3:** Does the Observer player occupy a slot, and if so, which one?

**Question 4:** Do dead players continue to occupy their slot?

**Comment by ilteroi** [comment]
1 - yes. that's why there's a MAX_PLAYERS also
2 - should be fine, player is not alive
3 - there's a difference between a slot and a player. observer slot is the first non-alive player.
4 - yes, might be resurrected after all

good timing, good night

**Comment by RecursiveStar** [comment]
Thanks!
