### ISSUE TITLE
Problems with SetPlayerNoSettlingRequestAccepted

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6583]
```
/// Marks plots as blocked or not blocked for this AI's settlers depending on if they agreed not to settle near ePlayer
void CvDiplomacyAI::SetPlayerNoSettleRequestAccepted(PlayerTypes ePlayer, bool bValue)
{
	CvAssertMsg(ePlayer >= 0, "DIPLOMACY_AI: Invalid Player Index.  Please send Jon this with your last 5 autosaves and what changelist # you're playing.");
	CvAssertMsg(ePlayer < MAX_MAJOR_CIVS, "DIPLOMACY_AI: Invalid Player Index.  Please send Jon this with your last 5 autosaves and what changelist # you're playing.");

	if(bValue != IsPlayerNoSettleRequestAccepted(ePlayer))
	{
		m_pabPlayerNoSettleRequestAccepted[ePlayer] = bValue;

		int iPlotLoop;

		// Add blocker to plots nearby ePlayer
		if(bValue)
		{
			int iLoopX, iLoopY;
			CvPlot* pNearbyPlot;
			int iRange = 6;

			// Loop through all of this player's Cities and create a barrier around them
			CvCity* pLoopCity;
			int iCityLoop;
			for(pLoopCity = GET_PLAYER(ePlayer).firstCity(&iCityLoop); pLoopCity != NULL; pLoopCity = GET_PLAYER(ePlayer).nextCity(&iCityLoop))
			{
				for(iLoopX = -(iRange); iLoopX <= iRange; iLoopX++)
				{
					for(iLoopY = -(iRange); iLoopY <= iRange; iLoopY++)
					{
						pNearbyPlot = plotXY(pLoopCity->getX(), pLoopCity->getY(), iLoopX, iLoopY);

						if(pNearbyPlot != NULL)
						{
							if(plotDistance(pNearbyPlot->getX(), pNearbyPlot->getY(), pLoopCity->getX(), pLoopCity->getY()) <= iRange)
							{
								GetPlayer()->SetNoSettling( pNearbyPlot->GetPlotIndex() );
							}
						}
					}
				}
			}
		}
		// Remove blocker from all plots
		else
		{
			int iNumPlots = GC.getMap().numPlots();
			for(iPlotLoop = 0; iPlotLoop < iNumPlots; iPlotLoop++)
			{
				GetPlayer()->ClearNoSettling();
			}
		}
	}
}
```
There are a number of problems with this function.

1) Isn't there already a function to calculate plot distance from a city? Why not just use that?

2) I don't understand exactly how SetNoSettling is storing the data for which plots are blocked from settling, but it seems to be a std::map. ClearNoSettling just wipes all the data from the map. So, if that's the case, I don't understand the purpose of having it loop once for every plot on the map.

3) Neither SetNoSettling nor ClearNoSettling seem to discriminate by player. Whenever any player declares war on an AI or whenever 50 turns have passed since a request was accepted, SetPlayerNoSettlingRequestAccepted for that player is called, thus clearing all "no settling" data for all players, whether or not they were involved. This means that the AI will often not respect its promise not to settle because of another player's actions. For this to work, there needs to be a separate array for each player in order for this to work, or some kind of multidimensional array that stores each "no settle" plot and the player **or players** they promised not to settle near.

4. This system isn't accounting for changes in city placement. Agreeing not to settle near a player only applies to plots near that player's cities at the time the request is accepted.

But I don't think ANY of this is even necessary. Why not get rid of the entire stored array and simply add the following check to settling logic?
```
if we are a major civ, loop through all other valid major civs

if settling plot is within X range of a player's city and we promised not to settle near that player, exclude this plot as a settling location

(range of 6 is currently used)
```

**Comment by RecursiveStar** [comment]
@ilteroi Can you add this? It would be infinitely simpler as a method of handling it.

**Comment by psparky** [comment]
Pretty scary that this looks like another subsystem that doesn't work anything like intended :(

However, I do feel that a promise should only apply to cities that exist at the time of the promise, not to cities settled (or captured) later. You agree to not settle certain lands, not to avoid any future cities.

**Comment by ilteroi** [comment]
yeah this seems to be broken ... you see that a lot with vanilla code. i'll see what i can do

**Comment by RecursiveStar** [comment]
@psparky The AI are pretty self-centered, they'll get mad if you settle near their new cities too, so it should apply the other way around. :)

**Comment by ilteroi** [comment]
it's done. and pushed. 2892402291a6a2d4d3538e1c230823f2bfad0a5e.

**Comment by RecursiveStar** [comment]
Thanks a lot! @ilteroi
