### ISSUE TITLE
Unfinished feature with move troops request

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6584]
```		
case FROM_UI_DIPLO_EVENT_HUMAN_MOVE_TROOPS_RESPONSE:
		{
			int iResponse;

			// 0 = Accept, 1 = Neutral, 2 = Refuse
			iResponse = IsMoveTroopsRequestAcceptable(eFromPlayer, /*bJustChecking*/ false);

			if (iResponse == 2 && !GET_TEAM(GetTeam()).canDeclareWar(GET_PLAYER(eFromPlayer).getTeam(), GetPlayer()->GetID()))
				iResponse = 1;

			// AI says yes, they will move their troops, and even better, they will leave the human alone
			if(iResponse == 0)
			{
				// AI accepts move troops request
				// Make sure all players on this team get this check, so that teammates don't screw each other over.
				TeamTypes eLoopTeam;
				for(int iI=0; iI < MAX_MAJOR_CIVS; iI++)
				{
					eLoopTeam = GET_PLAYER((PlayerTypes)iI).getTeam();
					if(eLoopTeam == GetPlayer()->getTeam())
					{
						GET_PLAYER((PlayerTypes)iI).GetDiplomacyAI()->SetPlayerMoveTroopsRequestAccepted(eFromPlayer, true);
						GET_PLAYER((PlayerTypes)iI).GetDiplomacyAI()->SetPlayerMoveTroopsRequestCounter(eFromPlayer, 0);

						GET_PLAYER(eFromPlayer).GetDiplomacyAI()->SetPlayerMadeMilitaryPromise((PlayerTypes)iI, true);
						GET_PLAYER(eFromPlayer).GetDiplomacyAI()->SetPlayerMilitaryPromiseCounter((PlayerTypes)iI, 0);
					}
				}

				if(bActivePlayer)
				{
					strText = GetDiploStringForMessage(DIPLO_MESSAGE_MOVE_TROOPS_ACCEPT);
					gDLL->GameplayDiplomacyAILeaderMessage(eMyPlayer, DIPLO_UI_STATE_BLANK_DISCUSSION, strText, LEADERHEAD_ANIM_YES);
				}

				// lower weight for crossing tiles around this player's cities
				int iLoop;
				CvCity* pLoopCity;
				for(pLoopCity = GET_PLAYER(eFromPlayer).firstCity(&iLoop); pLoopCity != NULL; pLoopCity = GET_PLAYER(eFromPlayer).nextCity(&iLoop))
				{
					//todo: mark cities for pathfinder
					//open question: when to unmark?? 
				}
			}
```

So IsMoveTroopsRequestAcceptable in the diplo AI is supposed to return 0 for ACCEPT (the AI agrees to move their troops from the human's borders), 1 for NEUTRAL (the AI promises it's not about to declare war, but does not remove their troops), or 2 for REFUSE (the AI declares war).

However, there is no distinction between ACCEPT and NEUTRAL aside from the dialogue. The AI is not any more reluctant to traverse near the human's borders.

This section here indicates Putmalk had the intention of making the AI more reluctant to move near the human's borders, but never implemented the feature.
```
					//todo: mark cities for pathfinder
					//open question: when to unmark?? 
```
So, @ilteroi, I'm sure there's an existing method of increasing reluctance to use specific plots; would you mind implementing that when **IsPlayerMoveTroopsRequestAccepted** for a player is **true** (meaning the response was ACCEPT, not just NEUTRAL)? I intend to make the AI able to make these requests to each other as well, so it'd be more relevant than just for the human-only dialogue option.

I don't think denying entrance completely is the way to go, since the human isn't expected to move their troops at all, just not to declare war. Maybe just treat it as a less desirable plot to move through or remain on, similar to embarkation on lakes?

As for when to unmark it, that can be handled in the diplo AI via the counter (or better yet, a variable that stores the turn the request was accepted; I don't understand why Firaxis used counters for a bunch of things - if you're going to store a value in memory, you may as well be precise with it and account for things like the player dying and being resurrected, since DoTurn doesn't function if a player is dead. I'll be replacing most or all of the counters with simply storing the turn number.)

**Comment by ilteroi** [comment]
well the first thing would be to create an enum for the response ... 

but yeah, missionaries already have code to avoid ending the turn on plot which cause attrition - that could be adapted. but i fear the effect will be less impressive than you imagine, because this extra cost only applies to multi-turn move missions. for missionaries it's ok because the destination typically is far away. but for military units the AI typically moves them to close-range destinations, so there are no intermediate stops. we would need to add checks in each place a destination is chosen ...

**Comment by RecursiveStar** [comment]
@ilteroi I added an enum to the response in my PR to the ole branch: #6586

Hmm, I see. Would adding checks in each destination be problematic?

**Comment by ilteroi** [comment]
well there are about 30 places or so that would need to be modified, a lot of effort for a minor feature

**Comment by RecursiveStar** [comment]
@ilteroi Would it be performance/memory intensive or is the only issue the effort required to add the feature?

**Comment by RecursiveStar** [comment]
@ilteroi I see...I would offer to do the work myself, but I'm not nearly as familiar with the unit movement code as you are and wouldn't want to screw anything up. I guess I'll shelve this on my "implementation wishlist" for now (or until I become more experienced).

**Comment by RecursiveStar** [comment]
Is there any easy way to distinguish where all these places are? A function call they all have in common, for instance?
