### ISSUE TITLE
[4-17] Building_ClassesNeededInCity cannot see uniques

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6585]
I use following code for numerous wonders:
```
INSERT INTO Building_ClassesNeededInCity (BuildingType, BuildingClassType) 
VALUES ('BUILDING_SISTINE_CHAPEL',	'BUILDINGCLASS_ARTISTS_GUILD');
```
When I check for unique building of the same class this functions seems to not work. 
I checked that on two examples: Artists Guild/Ukiyoe (from MUCfVP) and Stone Works/Tabya. With first building constructed (base building) it works. When I place unique building, it isn't.

**Comment by LoneGazebo** [comment]
code looks fine to me - keep in mind that the building has to actually be in the civ's unique building list for it to work - it can't just be a UB in a city.

**Comment by adaneslavo** [comment]
Those buildings are civ's unique, and are shown in tha loading screen. Tabya is base one and ukiyoe is from mucfvp. I'm sure problem is present with the rest.

**Comment by adaneslavo** [comment]
Eyyy, why did you close this? It's major bug making improtant table function useless for unique buildings... Tabya for example which **is** on the unique component list for its civ.
