### ISSUE TITLE
getSmallFakeRandNum Question

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6587]
So if I understand this correctly:

getSmallFakeRandNum returns a random # between 0 and the number specified, inclusive. An integer is provided as a seed for the randomizer.

(Not sure if it supports negative numbers...)

If the seed is X, the return value will always be Y (using whatever method it uses for fake randomness).

Is this correct?

**Comment by ilteroi** [comment]
i think it's zero to max exclusive.

but more importantly, the provided seed is added to a generic seed value which depends on turn slice etc. using the same extra seed in successive turns yields different results.

**Comment by RecursiveStar** [comment]
I think it's inclusive, considering how GetRandomPersonalityWeight in the diplo AI uses it - it obtains a random number from 0 to 5, then subtracts 2, allowing for a randomization range of +/- 2.

Ah, I see the turn slice factor now.

Thanks!
