### ISSUE TITLE
Guerilla barbarians

### ISSUE THREAD

**Issue by Verheather** [LoneGazebo/Community-Patch-DLL#6589]
_1. Mod version (i.e Date - 4/17):_
4/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Guerillas spawn around my capital when the enemy conquers a city at the edge of my empire (instead of the conquered city).

**Comment by ilteroi** [comment]
are you talking about partisans? those are spawned around a city being razed ... 

then there are rebellions - spy actions that can happen in the capital. maybe just a coincidence?

or do have events enabled?

**Comment by Verheather** [comment]
Partisans I guess? What I'm saying is that when a city was taken from me, barbarians would spawn next to my capital. Happened twice in a row. The city in question wasn't even close to my capital.
Events are off.

**Comment by Vyyt02** [comment]
Are you very unhappy? This can cause barbs spawning near your capital.
