### ISSUE TITLE
Units cannot switch places

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#659]
I cannot swap 2 neighboring units. When I click one and drag mouse over the other one, the cursor becomes red - same as if the units where out of move points, but this is not the case. It is repeatable, it happens every time. I tried both with NMCJT flag turned on and off.

(version CP+CBP 9-24, bunch of other mods active, but they should not be interferring)

**Comment by LoneGazebo** [comment]
Thanks for reporting, ilteroi has fixed. Waiting for his code to finish it up and push out a hotfix.
G

**Comment by Vyyt02** [comment]
Man, you guys are quick :-) Thanks!
