### ISSUE TITLE
HoveringUnit value doesn't allow to move over mountains.

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6590]
I wanted to allow movement via mountains to units with new created promotion. I added HoveringUnit values, but I still cannot move there until I set CanMoveImpassable (or something similar; cannot check now). The downside of such solution is that unit now can cross Ice too, and I don't want that. Bug? Or maybe there's another solution?

**Comment by ilteroi** [comment]
hovering is broken and should have been deleted a long time ago.

i can't look at the code now but you should probably create a promotion that makes mountains passable.

**Comment by adaneslavo** [comment]
Is there any other table value that allows that? Let me know when you can, please.
Do you plan to fix hovering?

**Comment by adaneslavo** [comment]
@ilteroi Can you help with that or the topic is lost?
