### ISSUE TITLE
Flat resources given by dummy cannot be traded

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6593]
Here is the code I used for cresting dummy. Dummy is placed using lua.
https://forums.civfanatics.com/threads/quick-questions-quick-answers.573489/page-317#post-15756417
Resources are visible, counted towards monopoly, but unfortunately I cannot trade any of copies given such way.

**Comment by LoneGazebo** [comment]
It's because they don't 'exist' for the trading class as physical copies on the map.

**Comment by adaneslavo** [comment]
Is there any way to fix this? Giving 3 copies with dummies seems irrelevant if you cannot trade them.
