### ISSUE TITLE
How to build 43 Civ DLL?

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6596]
Is it simply a matter of changing
#define MAX_MAJOR_CIVS to 43 and then building normally, or are there more steps involved?

**Comment by ilteroi** [comment]
never done it. but please do me a favor: do not add the resulting binaried to the repo. that only serves to blow up the history.

**Comment by RecursiveStar** [comment]
I don't add GameCoreDLL files to the repo in any case; G does that. :)

**Comment by LoneGazebo** [comment]
Yes that’s all you need to do

**Comment by LoneGazebo** [comment]
Just switch that define and built away :)

**Comment by RecursiveStar** [comment]
Thanks!
