### ISSUE TITLE
Adding new text keys WITHOUT consuming memory or excessive performance

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6600]
@LoneGazebo I had a potential "lightbulb moment" as to how I could add more leader dialogue textkeys without consuming memory or tanking performance (which you said were problems with my previous ideas).

Strings can be written to logfiles from within the GameCoreDLL, right? It would require modification of the code, but would it be possible to simply store the additional dialogue textkeys within the GameCoreDLL?

i.e. Pick a random number between 1 and the maximum number of textkeys, then a very long if/switch statement, for instance:
```
CvString* strOutput;
switch (iIndex)
{
case 1:
  strOutput = ("Blah blah blah");
case 2:
  strOutput = ("Blah blah blah blah");
case 3:
  strOutput = ("Blah blah blah blah blah");
}

return strOutput;
```
It would increase the file size a little bit, yes, but it wouldn't consume memory to the point of causing issues (ilteroi stated earlier that functions that aren't called don't consume memory), and I don't think a switch statement would be very performance-consuming either, since it's only finding a number and adding a string.

I could add a custom define to turn additional dialogue on/off, to turn it off for translated versions of the game.

Do you see any problems with this idea?

**Comment by LoneGazebo** [comment]
It still has to be compiled, so it still takes up memory. Also, you can’t localize it, and there are some weird issues that can happen if you don’t use the text key parser on text.

**Comment by LoneGazebo** [comment]
As long as you aren’t adding a thousand lines, a few hundred more Txt_key lines won’t kill performance.

**Comment by RecursiveStar** [comment]
D'oh! Back to the drawing board. :)

**Comment by RecursiveStar** [comment]
Wait, how much memory is consumed by compilation? Is it equal to the file size for the GameCoreDLL? Because if so, that still allows for way more lines of text to be added.

**Comment by ilteroi** [comment]
i said a function that is never called will be optimized away. but your function would be called, otherwise it's pointless. 

anyway while we shouldn't be wasting memory a few kilobytes don't matter much considering the total footprint is gigabytes. most of that is graphics of course ...

**Comment by RecursiveStar** [comment]
Hmm, think I misunderstood that as "code that isn't run doesn't impact performance in any way".

So if I create a switch statement as above, would the code in all other sections besides the one matching the switch statement consume memory/performance?

**Comment by LoneGazebo** [comment]
If any part of a function runs, the entire function has to be compiled, because the DLL doesn't know what will or will not be called _within_ a function.

**Comment by LoneGazebo** [comment]
It only knows if a function is not explicitly called within a function. i.e., 

If you have three functions (A,B, C):

If A calls B, A & B will be compiled
If neither A nor B calls C, and C does not call A or B, then C will be ignored
If A has 1,000 switch calls in it, but is only called once by B, all of A will be compiled, because the DLL doesn't know which switch functions will be called upon.

**Comment by RecursiveStar** [comment]
Ah okay, I understand the memory aspect now - but as far as performance, would the code in the other switch calls (aside from the correct one) have any impact?

**Comment by LoneGazebo** [comment]
A switch statement is more performance friendly than an if/else if chain, but memory wise its irrelevant if you intend to add a few hundred lines of dialog.

**Comment by RecursiveStar** [comment]
So is there a difference in compiling it within the GameCoreDLL versus using the text key parser?

I'm trying to understand the upper limit of what can be done within the limitations of Civ V's 32-bitness, so I have a better idea of how much wiggle room there is.

I'm trying to understand if adding one thousand text keys will be harmful memory-wise but a few hundred are okay - maybe I'm underestimating how much space text takes up.

**Comment by ilteroi** [comment]
i don't have actual numbers but text is typically 2 bytes per character. of course there is a certain overhead for the data structures around it but it should be ok.

member variables in classes that are instantiated often (plot, unit, player, team etc) are more critical, especially if they scale quadratically, eg a plot stores something about every other plot.

lua is hard to quantify, but it all pales in comparison to graphics ... and probably there are some memory leaks as well.

**Comment by RecursiveStar** [comment]
So if your numbers are correct (2 bytes per character), let's say I added a bunch of lines that were on average 100 characters long. I'm not sure if 1 KB = 1000 or 1024 bytes but anyway assuming 1000, each KB would support 500 characters, or 5 lines.

With the final footprint being measured in GB (which contain a thousand MB), that would mean that each MB could support 5 * 1000 = 5000 lines of text.

So while the space isn't limitless, is this really a big deal at all? Even if I did add a thousand lines, it would take up about one MB, assuming your numbers are correct.

**Comment by Voker57** [comment]
Just passing by and curious, what is the problem with text keys consuming memory? Could you point me at thread/issue?

**Comment by RecursiveStar** [comment]
@Voker57 #5884

**Comment by ilteroi** [comment]
people are still getting crashes in the late game, and saving a few kb might give them one additional turn but it's all for nothing if they use too many additional mods ... so relax and just do it

**Comment by RecursiveStar** [comment]
Alright then.
