### ISSUE TITLE
New Barbarian tactical AI behavior questions

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6603]
@ilteroi I have three questions about the new Barbarian tactical AI behavior you've pushed.

So m_iLandBarbarianRange is based on the game handicap's difficulty level (+1 per level).
`Settler = 5, Chieftain = 6, Warlord = 7, Prince = 8, King = 9, Emperor = 10, Immortal = 11, Deity = 12`

And m_iSeaBarbarianRange is also based on the game handicap's difficulty level (+2 per level).
`Settler = 14, Chieftain = 16, Warlord = 18, Prince = 20, King = 22, Emperor = 24, Immortal = 26, Deity = 28`

These values used to only apply to Barbarians who were searching for trade routes to plunder. However with the new code they seem to apply for general use as well.

So question 1: rather than "Range of barbarian pathfinder (for visible caravan/cargo ship trade routes)" what new description should I give to the value on the wiki's difficulty page?

Question 2: The sea range seems to be divided by three now (not sure if it was the case previously), so I wonder - why not just divide all the difficulty values by 3 - or just make them equal to the land values?

Question 3: Are these values using estimated turns rather than plot distance now? Is that why the division occurred?

**Comment by ilteroi** [comment]
yes, the ranges are specified in plots, but the pathfinder needs approximate turns, so i simply divided them because i am lazy.

if you want to clean it up, go ahead.

for the description, i would suggest "maximum range for barbarian target search"

**Comment by RecursiveStar** [comment]
Pulled - will push new pull requests shortly so as not to conflict with your changes.
