### ISSUE TITLE
Suggestion: Include PDB file as part of the installer?

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6608]
If the PDB file generated as part of the build is useful in debugging issues, perhaps we should have it be placed in the Community Patch folder along with the CvGameCore_Expansion2.dll file?

Only downside I can think of is that new interim builds would need to update the database file as well.

**Comment by bigcat88** [comment]
For me is not hard to copy-paste file with hands.
