### ISSUE TITLE
Air sweeps causing friendly fire

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6609]
_1. Mod version (i.e Date - 4/17):_ Latest

@ilteroi Reported on the forums: https://forums.civfanatics.com/threads/new-beta-version-april-17th-4-17.657164/page-23#post-15773926

**Comment by Phosphoraptor97** [comment]
Some more details: [https://forums.civfanatics.com/threads/new-beta-version-april-17th-4-17.657164/page-23#post-15773926](url)

**Comment by RecursiveStar** [comment]
@Phosphoraptor97 Could you upload a savegame?
