### ISSUE TITLE
Cannot choose production or change production

### ISSUE THREAD

**Issue by Leyvatein** [LoneGazebo/Community-Patch-DLL#6610]
_1. Mod version (i.e Date - 4/17):_
4/17/2020

_2. Mod list (if using Vox Populi only, leave blank):_
community patch
balance overhaul
info addict
wonder race

_3. Error description:_ 
If I click "choose production" button above the map, the camera will center on the city but the production menu won't come up, if I click on the city and click "choose production" nothing happens either. I also can't change production

_4. Steps to reproduce (optional):_
Load save #1, go to the next turn and you can't change production anymore. Go next turn when cities have finished building and "choose production" doesn't work

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4668938/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[2 saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4668939/2.saves.zip)
in save #1 I can change production, in save #2 (next turn) I cant change production 

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Leyvatein** [comment]
I read the lua log file and found the CBO InfoTooltipInclude.lua file had a problem so I went to that file around line 669 and commented out the if else so that there only is 
`local iCost = 0;`
`iCost = pActivePlayer:GetProjectProductionNeeded(iProjectID);`

Now I can choose production but I'm sure something else eventually will break because of this

**Comment by Vyyt02** [comment]
This looks like a bad install, InfoAddict and Wonder Race should work fine with VP. You mention Community Patch and Balance Overhaul, but what about the other VP components such as More Luxuries, Civ4 Diplo and the compatibility components? I don't think you can play without them (could be wrong).

**Comment by Leyvatein** [comment]
They are optional and I don't use EUI either
