### ISSUE TITLE
Do non-major civs have a diplomacy AI?

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6613]
I've noticed a number of cases where the code will just call a diplomacy AI function in the form of: `GET_PLAYER(ePlayer).GetDiplomacyAI()->Function()` without checking if ePlayer is a major civ.

So what happens if a minor civ or the Barbarian player is passed to GET_PLAYER? Does it just do nothing, or do minor civs and Barbs also have a diplomacy AI?

How does that affect memory storage, also? Do the Minor Civs and Barbs have all the values major civs have? Seems wasteful if so.

I'm wondering if I ought to add `if (!GetPlayer()->isMajorCiv()) return;` checks to the memory-related functions in the diplo AI for that reason. But maybe there's a better way of handling it than that.

**Comment by RecursiveStar** [comment]
Unless I'm mistaken, all civs including minors and Barbs have a diplomacy and deal AI, according to CvPlayer.cpp. Furthermore all civs have a minor civ AI.

Seems very wasteful of your limited memory, Firaxis.

**Comment by ilteroi** [comment]
interesting observation. you could try and modify GetDiplomacyAI() to return NULL for minors and GetMinorCivAI() to return NULL for majors to see how many crashes that results in.

**Comment by RecursiveStar** [comment]
That'd be interesting; I suspect a lot. I think it might be that Firaxis didn't want to bother adding "if isMajorCiv() then GetDiplomacyAI" type checks. 

I rewrote some of those checks when I saw them but there's probably a fair number left.
