### ISSUE TITLE
Is there a cached value for # of units owned by a player?

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6614]
Asking since IsPlayerValid in the diplomacy AI considers a player invalid if they have no cities, but it's possible to still be alive with units and no cities (Complete Kills, or at game start), and I might want to modify this for some situations.

**Comment by RecursiveStar** [comment]
@ilteroi Any thoughts? What I want is an easy, performance-friendly way to test if a player has > 0 units, combat or non-combat.

**Comment by RecursiveStar** [comment]
My current thought is to add a function to CvPlayer:
```
//	--------------------------------------------------------------------------------
/// Does this player have any units, period?
bool CvPlayer::HasAnyUnits()
{
	int iLoop;
	for (CvUnit* pLoopUnit = firstUnit(&iLoop); pLoopUnit != NULL; pLoopUnit = nextUnit(&iLoop))
	{
		if (pLoopUnit != NULL && !pLoopUnit->isDelayedDeath())
			return true;
	}
	
	return false;
}
```

**Comment by ilteroi** [comment]
what's wrong with CvPlayer::getNumUnits() ?

**Comment by RecursiveStar** [comment]
Nothing at all, I just didn't see it haha...thanks
