### ISSUE TITLE
fix for unprotected AI settlers

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6617]
@LoneGazebo: i forgot to push a fix, can you add a danger check at line 2698 in tactical ai?

replacing the 'else' by
```
else if (pCivilian->GetDanger(pOperation->GetMusterPlot())<INT_MAX)
```
should do it.

**Comment by RecursiveStar** [comment]
@ilteroi It's been my experience that the AI does a poor job of protecting their early Workers, in that I can often declare war, zoom in with a unit, leave and wait for white peace.

I feel the AI, at least in the early part of the game where Workers are highly valuable, should constantly have a unit stacked with their Worker. I mean, they start the game with two Warriors, so they have defense available from turn 0.

**Comment by ilteroi** [comment]
good idea, but they need to build more units in the first place

**Comment by RecursiveStar** [comment]
@ilteroi I added your fix to my pull request...I think Gazebo's busy.
