### ISSUE TITLE
AI Work Boats can pass through ice

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#6618]
_1. Mod version (i.e Date - 4/17):_
3-1b

_2. Mod list (if using Vox Populi only, leave blank):_
Logistics Skirmishers
Selected 4-17 changes (non-DLL)
Various UI mods

_3. Error description:_ 
AI work boat had no way to reach the destination fish, but did so anyway in 1 turn. No forts as seen in the screenshot below.

_4. Screenshot:_
![image](https://user-images.githubusercontent.com/14953746/82746136-f354f600-9dbe-11ea-8326-44ed572bd961.png)

**Comment by azum4roll** [comment]
And tradition Siam isn't supposed to settle there at all, but that's another issue...

**Comment by bigcat88** [comment]
Intended

**Comment by azum4roll** [comment]
Even if they can pass through ice they still don't have 4 moves, do they?

Oh wait they do, they have the Sri Pada.
