### ISSUE TITLE
Trade Screen: Strategic Resources Quantity Issue

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6619]
_1. Mod version (i.e Date - 4/17): 4/17 + DLL

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

This issue (#6380) hasn't been solved.

I think that you can now sell only half of the strategic resources in one trade (can sell multiple times in one turn but different trades), maybe that could help found the problem.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ridjack** [comment]
Copying from my now-closed post and pasting it here to decrease clutter: 

_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_
A fair few. I'll append later if needed; at the moment the mod list is inaccessible to me.

_3. Error description:_ 

Hard to describe, so I'll do a play-by-play.

- Civ comes to me wanting to buy 4 horses for 8 GPT and 62 flat.
- I click in the horses edit box, or unclick horses from my side.
- Even though I have 5 horses to sell, nothing I do will allow me to put it above 2 horses. I can adjust it to 2 without issue; adjusting it to 3 or higher sets it back to 1 or 2 depending on what was previously in the edit box.

I tried clearing out my side and asking him what will make this deal work, hoping he would put the 4 horses back. Nada.

I am not selling any horses to anyone else. This is early in this game, and these are the first horses I've even connected. 

I'm fairly sure I've seen this with other resources as well, but I can't say that 100% right now. I'll edit this as more becomes apparent to me.

A gif:

https://i.imgur.com/kALGAuQ.gifv

(Please note that even though the civ in question is a modded civ, I've had this happen with plenty of vanilla civs as well.)

EDIT: Edited title to more accurately reflect the situation; I just tried going back to Nubia once my turn came up, and I still cannot increase the horses above two.
EDIT2: Went back one turn and waited for the deal to appear again. If I don't make any changes, the deal is accepted without apparent issue.

**Comment by LoneGazebo** [comment]
I believe the issue here is that the game 'holds' the resources the AI would like in the original offered deal - that deal is not deleted until the AI's offer is accepted or declined. In game terms, that means that you actually have fewer resources available than are being offered in the deal because a few of them are tied up.
