### ISSUE TITLE
Negative values for Policy_BuildingClassYieldModifiers

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#662]
Hopefully a small request, but could you adjust Policy_BuildingClassYieldModifiers so that it allows for negative values (so, negative modifiers). Policy_BuildingClassYieldChanges already does this, so I'm guessing this is another of those unnecessary > 0 checks on Firaxis' part. Definitely no rush, and thanks!

**Comment by LoneGazebo** [comment]
Yep, that was the case. I'll edit for next version.

**Comment by JFDaly** [comment]
Excellent, thank you.
