### ISSUE TITLE
repo size

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6620]
the repo is currently at 1.3 gb including the history.

this seems to be quite high, and the history is not really something to be proud of anyway.

so how about a fresh start with the next release version?

**Comment by RecursiveStar** [comment]
I've sometimes found it useful to go back and see when a specific change was made, and this is often useful for diagnosing problems.

That said, there are years of history here and I doubt many people are looking back to see what commits changed what in 2016.

Not everything is a source of pride (my commits prior to learning the IDE aren't for me, and my coding practices have certainly improved over time as I learn better ways of doing things), but the progression is still interesting.

If a new repository were created, probably without the dead unused branches and years of old issues and commits, I wouldn't have any objections, but I think the old one should be kept around for historical interest.
