### ISSUE TITLE
AI wasting Great Generals

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6622]
_1. Mod version (i.e Date - 4/17):_ latest

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

This issue has been around for quite a while. 
AI disregards enemy units in the vicinity and sends unprotected Great Generals close to the enemy to be destroyed.

EDIT: Probably has something to do with AI's inability to preserve embarked units.

![Inked20200526172347_1_LI](https://user-images.githubusercontent.com/16341598/82913067-83896b80-9f76-11ea-80de-698218a7f37d.jpg)

**Comment by ilteroi** [comment]
should be better now, but keep an eye out
