### ISSUE TITLE
Corporation Issues

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6623]
_1. Mod version (i.e Date - 4/17):

4/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

A few mechanics around corporations are not the same as stated in tooltips.

_4. Steps to reproduce (optional):_

---------------------------

When A Civ gets sanctioned by World Congress:

Tooltip: No trade routes, franchises with other civs (excluding vassals). Franchises removed from foreign cities.

Result in Game: Franchises removed from all foreign cities including vassals, you can then still establish trade routes and establish franchises with vassals but seems strange to remove the franchises in vassals if they are allowed anyways. 
Also can have trade routes but no franchises with City States which I assume is as intended.

Nationalization Policy (Order Ideology):

Tooltip: Each office counts as a franchise, corporate trade route bonuses to cities with a franchise doubled. No foreign franchises.

Result in Game: No foreign franchises and each office counts as franchise. However trade route bonus to owned cities with an office (and now a franchise) only give the normal trade route bonus (not doubled as stated).

One minor extra thing is couldn't Nationalization also allow franchises with your vassals? Seems like Order is supposed to have some synergy with having vassals already.

**Comment by RecursiveStar** [comment]
Fixed the sanction issue. https://github.com/LoneGazebo/Community-Patch-DLL/pull/6624

**Comment by LoneGazebo** [comment]
Fixed secondary issues.
