### ISSUE TITLE
Late Game crash - every single time

### ISSUE THREAD

**Issue by Peper1410** [LoneGazebo/Community-Patch-DLL#6625]
_1. Mod version (i.e Date - 4/17):_
Latest, v89 (29.07.2019)

_2. Mod list (if using Vox Populi only, leave blank):_
![2020-05-27_185635](https://user-images.githubusercontent.com/66028575/83049811-ded95d80-a04b-11ea-9b3e-84907adc8c96.png)
Could be in this format, or should i write them manually?

_3. Error description:_ 
During late game, normally between mid-industrial to early atomic era game suddenly crash during AI turn. I have this problem from first installation of voxpopuli around 2 years ago. It happens literary every time i play (since i started playing using Vox Populi, i never completed a single game). Loading previous save don't work - sometimes, if i load earlier save (for example 5 or 7 turns) everything works - but, eventually (rather sooner than later), it will CTD. I even to tracked down on which civ turn game crashes, and manually (using IGE) delete that civ -  but then game still crashes, but maybe like 10-15 turns later.

---------------------------
Supporting information:
Logs + auto and manual save +minidump:

[civ5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4690308/civ5.zip)

**Comment by ilteroi** [comment]
well, that version is almost one year old ... try again with the next release?

**Comment by Peper1410** [comment]
> well, that version is almost one year old ... try again with the next release? and without the extra mods at first.

I downloaded last version 18.05.2020 from here: https://forums.civfanatics.com/threads/community-patch-how-to-install.528034/  (vox populi automatic installer), so i assume **this is** current build. I really have to play 20-30h play only to see if it crash? I used this set of mods without vox populi and it was fine.

**Comment by ilteroi** [comment]
yes that is the latest release but a new one should be coming soon.

anyway, i was hoping you like playing :)

**Comment by RecursiveStar** [comment]
@Peper1410 A lot of issues that cause crashes are fixed within a year's time, and diagnosing crashes takes time so we focus on issues that are still present. Maintaining support for every old version would require a ton of time and effort.

**Comment by Peper1410** [comment]
> 
> 
> yes that is the latest release but a new one should be coming soon.
> 
> anyway, i was hoping you like playing :)

Ok, so i will just wait till new realise and then try it without any other mods. May by it will work this time. I like playing, but i'm unable to finish any game from very long time, late game is my favorite part, and as i previously described, it crashes on the very beginning of late game.

**Comment by Vyyt02** [comment]
> > yes that is the latest release but a new one should be coming soon.
> > anyway, i was hoping you like playing :)
> 
> Ok, so i will just wait till new realise and then try it without any other mods. May by it will work this time. I like playing, but i'm unable to finish any game from very long time, late game is my favorite part, and as i previously described, it crashes on the very beginning of late game.

I think you do not need to wait for the new release, the latest beta (4-17) is very stable (if you do not mind a bug which sometimes gives a bit of extra XP from combat, but the bug triggers for both humans and AIs and is not getting out of hand, so I believe it does not cause any big imbalance).
