### ISSUE TITLE
Can't move stacked unit or end turn

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6627]
_1. Mod version (i.e Date - 4/17):_ Latest

Reported on the forums: https://forums.civfanatics.com/threads/new-beta-version-april-17th-4-17.657164/page-27#post-15781600

![20200527221249_1](https://user-images.githubusercontent.com/38794241/83136021-c4879a00-a0b4-11ea-9783-99818f0d6901.jpg)

@ilteroi 

Stacking occurred unintentionally ("I moved an ironclad into an area of fog of war that turned out to contain the Incan navy. My unit was on top of one of their units but unable to move into any of the adjacent spaces.") and was resolved by gifting the unit to the City-State.

**Comment by ilteroi** [comment]
haha, that's a funny one

**Comment by JamesNinelives** [comment]
Thanks very much for reporting Recursive, and for fixing Ilteroi! Hope you are both well <3.
