### ISSUE TITLE
Policy_GoldenAgeYieldMod not working

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#663]
It appears that Policy_GoldenAgeYieldMod doesn't work. Building_GoldenAgeYieldMod, on the other hand, works perfectly, so I'm fairly sure that this time I'm not mistaken on this being an actual bug. I tested with a variety of yields for both, and whilst they worked for the latter, none did for the former. Thanks for taking a look when you get the chance.

**Comment by LoneGazebo** [comment]
I'll take a look now. Odd, as this code hasn't been touched in some time.

**Comment by LoneGazebo** [comment]
![2015-09-29_00001](https://cloud.githubusercontent.com/assets/7849458/10165006/da4d0ee2-668a-11e5-9c81-0fb0582ecdbf.jpg)
![2015-09-29_00002](https://cloud.githubusercontent.com/assets/7849458/10165005/da4c4f84-668a-11e5-9b1c-a2c3bb4223bb.jpg)

**Comment by LoneGazebo** [comment]
Just tested, seem to work for me. Your code looks like this?

<Policy_GoldenAgeYieldMod>
		<Row>
			<PolicyType>POLICY_HUMANISM</PolicyType>
			<YieldType>YIELD_SCIENCE</YieldType>
			<Yield>10</Yield>
		</Row>
		<Row>
			<PolicyType>POLICY_HUMANISM</PolicyType>
			<YieldType>YIELD_FOOD</YieldType>
			<Yield>10</Yield>
		</Row>
	</Policy_GoldenAgeYieldMod>

**Comment by JFDaly** [comment]
My code (set to tradition to test):

INSERT INTO Policy_GoldenAgeYieldMod
		(PolicyType, 				YieldType, 			Yield)
VALUES	('POLICY_TRADITION', 		'YIELD_CULTURE',	20),
		('POLICY_TRADITION', 		'YIELD_FAITH',		20),
		('POLICY_TRADITION', 		'YIELD_FOOD',		20),
		('POLICY_TRADITION', 		'YIELD_PRODUCTION',	20);

Yet nothing: http://i.imgur.com/WlxPL5B.jpg

But if it works for you, it must be another problem on my end.

**Comment by LoneGazebo** [comment]
And the code is showing up in your SQL table when the mod(s) are loaded? You might try putting the 20s in 'quotes' to see if that helps. SQL can be finicky sometimes.

**Comment by JFDaly** [comment]
Yup, the table was directly above a test for Building_GoldenAgeYieldMod. Also appeared in the database. Quotes around the numbers didn't change anything.

**Comment by LoneGazebo** [comment]
Hmm...and you took the policy during your test? I'm just trying to sort this out. Have you enabled or disabled any of the mod values in the custommodoptions.xml file, or are you just using the straight CP?

**Comment by LoneGazebo** [comment]
Ahh nevermind I see what it is. I closed off the playerlevel function with a bracketed look for an option disabled in the CP but open in the CP. I'll remove that bracket for the next version. Sorry!!

**Comment by JFDaly** [comment]
Glad you found out the cause. Thanks for taking a look
