### ISSUE TITLE
AI settler decision making

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#6630]
_1. Mod version (i.e Date - 4/17):_
5-15 DLL

_2. Mod list (if using Vox Populi only, leave blank):_
Various UI mods
Logistics Skirmishers

_3. Error description:_ 
Songhai settler (and escort) keeps moving back and forth between the plots circled in red. The debug log reveals that the AI keeps switching its target settle location between (42:20) and (51:21) (plots circled in blue), and I suspect it'll keep happening until Austria/Babylon/Morocco settle one of those spots and Songhai will be stuck with 2 cities.

![image](https://user-images.githubusercontent.com/14953746/83350296-d5af0000-a36d-11ea-8d72-dfdd40b5daaf.png)

[OperationalAILog_Songhai.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/4707523/OperationalAILog_Songhai.txt)

**Comment by azum4roll** [comment]
Log snippet:
`064, Songhai, AI_OPERATION_FOUND_CITY, 3, Started, Army: 1402, Units Recruited: 0, Max Formation Size: 2, Not initialized
064, Songhai, AI_OPERATION_FOUND_CITY, 3, setting new target (51:21)
064, Songhai, AI_OPERATION_FOUND_CITY, 3, Added Settler 1256 to slot 0 in army 1402. ETA at (45:25) is 0 
064, Songhai, AI_OPERATION_FOUND_CITY, 3, Initial stage is recruiting
064, Songhai, AI_OPERATION_FOUND_CITY, 3, Found 7 potential units to recruit for operation 3 at x=45 y=25, target of x=51 y=21
064, Songhai, AI_OPERATION_FOUND_CITY, 3, Added Warrior 1099 to slot 1 in army 1402. ETA at (45:25) is 0 
064, Songhai, AI_OPERATION_FOUND_CITY, 3, Transition to gathering stage
064, Songhai, AI_OPERATION_FOUND_CITY, 3, Started, Army: 1402, Units Recruited: 2, Max Formation Size: 2, Gathering Forces
064, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Gathering Forces, Army: 1402, Gather (45:25), variance (2.25:1.00), Settler 1256 at (43:22),Warrior 1099 at (46:24),
064, Songhai, AI_OPERATION_FOUND_CITY, 3, Transition to movement stage
064, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (43:22), To (51:21), Settler 1256 at (44:25), Warrior 1099 at (46:24), 
065, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (43:22), To (51:21), Settler 1256 at (44:25), Warrior 1099 at (46:24), 
065, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (44:25), To (51:21), Settler 1256 at (43:23), Warrior 1099 at (43:23), 
066, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (44:25), To (51:21), Settler 1256 at (43:23), Warrior 1099 at (43:23), 
066, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (43:23), To (51:21), Settler 1256 at (42:21), Warrior 1099 at (42:21), 
067, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (43:23), To (51:21), Settler 1256 at (42:21), Warrior 1099 at (42:21), 
067, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (42:21), To (51:21), Settler 1256 at (42:19), Warrior 1099 at (42:19), 
068, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (42:21), To (51:21), Settler 1256 at (42:19), Warrior 1099 at (42:19), 
068, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (42:19), To (51:21), Settler 1256 at (43:18), Warrior 1099 at (43:18), 
069, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (42:19), To (51:21), Settler 1256 at (43:18), Warrior 1099 at (43:18), 
069, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (43:18), To (51:21), Settler 1256 at (44:16), Warrior 1099 at (44:16), 
070, Songhai, AI_OPERATION_FOUND_CITY, 3, setting new target (42:20)
070, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (43:18), To (42:20), Settler 1256 at (44:16), Warrior 1099 at (44:16), 
070, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (44:16), To (42:20), Settler 1256 at (43:18), Warrior 1099 at (43:18), 
071, Songhai, AI_OPERATION_FOUND_CITY, 3, setting new target (51:21)
071, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (44:16), To (51:21), Settler 1256 at (43:18), Warrior 1099 at (43:18), 
071, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (43:18), To (51:21), Settler 1256 at (44:16), Warrior 1099 at (44:16), 
072, Songhai, AI_OPERATION_FOUND_CITY, 3, setting new target (42:20)
072, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (43:18), To (42:20), Settler 1256 at (44:16), Warrior 1099 at (44:16), 
072, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (44:16), To (42:20), Settler 1256 at (43:18), Warrior 1099 at (43:18), 
073, Songhai, AI_OPERATION_FOUND_CITY, 3, setting new target (51:21)
073, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (44:16), To (51:21), Settler 1256 at (43:18), Warrior 1099 at (43:18), 
073, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (43:18), To (51:21), Settler 1256 at (44:16), Warrior 1099 at (44:16), 
074, Songhai, AI_OPERATION_FOUND_CITY, 3, setting new target (42:20)
074, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (43:18), To (42:20), Settler 1256 at (44:16), Warrior 1099 at (44:16), 
074, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (44:16), To (42:20), Settler 1256 at (43:18), Warrior 1099 at (43:18), 
075, Songhai, AI_OPERATION_FOUND_CITY, 3, setting new target (51:21)
075, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (44:16), To (51:21), Settler 1256 at (43:18), Warrior 1099 at (43:18), 
075, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (43:18), To (51:21), Settler 1256 at (44:16), Warrior 1099 at (44:16), 
076, Songhai, AI_OPERATION_FOUND_CITY, 3, setting new target (42:20)
076, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (43:18), To (42:20), Settler 1256 at (44:16), Warrior 1099 at (44:16), 
076, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (44:16), To (42:20), Settler 1256 at (43:18), Warrior 1099 at (43:18), 
077, Songhai, AI_OPERATION_FOUND_CITY, 3, setting new target (51:21)
077, Songhai, AI_OPERATION_FOUND_CITY, 3, PRE Moving To Target, Army: 1402, At (44:16), To (51:21), Settler 1256 at (43:18), Warrior 1099 at (43:18), 
077, Songhai, AI_OPERATION_FOUND_CITY, 3, POST Moving To Target, Army: 1402, At (43:18), To (51:21), Settler 1256 at (44:16), Warrior 1099 at (44:16), `

**Comment by azum4roll** [comment]
Update:
Songhai gave up the settling operation on turn 85 (Ended: TimedOut)
Songhai started going for (51:21) again on turn 88
Austria settled the spot below (42:20) on turn 91

**Comment by ilteroi** [comment]
weird, let's keep an eye on it in the next version
