### ISSUE TITLE
Cant save game at all

### ISSUE THREAD

**Issue by musikBear** [LoneGazebo/Community-Patch-DLL#6634]
_1. Mod version (i.e Date - 4/17):_ Basegame : **Sid Meier's Civilization Vl**

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Nothing can be saved. Not manually through the menu, and not auto-saves either. That makes the game unusable!
Provider : EpicGame (Free for week 3 in may 2020
Checked and tested:
Save location 
* has full rights
* is not ReadOnly
* No change if game is started with option *'as  Administrator'*

_4. Steps to reproduce (optional):_
I think i know the reason. I have moved Documents away from my C:-drive, simply because it is a SSD, and i do not want to fill it up with games oa game-data. Therefore i believe that the issue can be reproduced on **win10**, by moving the *Documents* -folder from C: to a different HD, *before* the game is installed. Since the new location (D:) is totally in user control (full read/write), that should not matter, but it does.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.
I do not have any. However i find it very unsatisfactory, that the game has a *hardcoded* save location! That is simply not ok! User MUST be able to select locations for both installation and save-location! 

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
**Folder** does NOT exists! -Eg *not created* during installation

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 
Impossible!

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveStar** [comment]
@musikBear This is a Github repository for the Civ **V** game mod, Vox Populi AKA the Community Patch Project. We have nothing to do with Civ VI, and can't help you with it. 

You'd have to contact Firaxis Games for support.

**Comment by musikBear** [comment]
l..o..l.. :|

**Comment by ryanmusante** [comment]
Or join the community and enjoy.

**Comment by musikBear** [comment]
> Or join the community and enjoy.

I do not *have* civ5 :)
