### ISSUE TITLE
Strategic resource count resets to 1 when renewing a deal on AI turn

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#664]
Say, I traded 6 horses for some gpt with an AI. After the time for the deal runs out, the AI asks to renew it. If I alter something and ask what he wants in return or straight up press the 'propose' button, those 6 horses will reset to just 1 horse. It doesn't persist when I trade on my turn - I can set whatever SR count I want.

**Comment by LoneGazebo** [comment]
That's intentional to get the AI to refresh its desire. I did that so that the AI would have to reevaluate, otherwise it can make an offer, and then turn it down (because those values weren't recached.

G

**Comment by Edaka** [comment]
Ah, I see. But then wouldn't it be better if the AI didn't offer those renewals of deals involving SRs in the first place, or is that too much of a pain to code?

**Comment by LoneGazebo** [comment]
That gets painful to hardcode.

**Comment by Edaka** [comment]
Too bad. Well, anything for the AI (: .

**Comment by LoneGazebo** [comment]
Yep. The AI is actually the one doing the editing there- in order to make them 'offer,' they have to mess with your stuff. It's real dumb, but that's the way it is.

**Comment by LoneGazebo** [comment]
I'll take another look, but I fear this is the AI being troublesome.
