### ISSUE TITLE
resource accounting

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6640]
what is the difference between

int CvPlayer::getResourceFromCSAlliances(ResourceTypes eIndex) const

and 

int CvPlayer::getResourceFromMinors(ResourceTypes eIndex) const

and

int CvPlayer::getResourceSiphoned(ResourceTypes eIndex) const

?

sometimes a few comments would really be helpful :)

**Comment by ilteroi** [comment]
why fixed?

**Comment by RecursiveStar** [comment]
I saw your commit here: https://github.com/LoneGazebo/Community-Patch-DLL/commit/a28d343d743d39fc703597ebb57a27c2099af994

**Comment by RecursiveStar** [comment]
@ilteroi Also you may want to look at this: https://github.com/LoneGazebo/Community-Patch-DLL/issues/6619

**Comment by ilteroi** [comment]
well i made change more or less blindly, based on my hunches ... still would like to have official confirmation.
