### ISSUE TITLE
Statecraft too popular

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6641]
_1. Mod version (i.e Date - 4/17):_4-17

 It seems AI is overwhelmingly biased towards choosing the Statecraft policy tree.
 Roughly 50-70% of AIs had Statecraft as their second policy in each of those games.
 Can anyone confirm?

**Comment by RecursiveStar** [comment]
Can confirm a lot of people have voiced this complaint on the forums. Probably an imbalance with the tree.

**Comment by azum4roll** [comment]
Tradition and Rationalism too, but not as extreme.
