### ISSUE TITLE
How to search for a value within a vector?

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6643]
DoUpdateMajorCivApproaches currently does the following:
```
	if (vPlayersToUpdate.size() > 1)
	{
		// Do a first pass of GetBestApproachTowardsMajorCiv for each player and record (but do not update) the approach weights in a map; they will be used in the second pass.
		for (std::vector<PlayerTypes>::iterator it = vPlayersToUpdate.begin(); it != vPlayersToUpdate.end(); ++it)
		{
			GetBestApproachTowardsMajorCiv(*it, /*bFirstPass*/ true, /*bUpdate*/ false, vPlayersToUpdate, oldApproaches, bIgnoreApproachCurve);
		}

		// Do a second pass of GetBestApproachTowardsMajorCiv for each player and update/log the (possibly new) approach and weights.
		for (std::vector<PlayerTypes>::iterator it2 = vPlayersToUpdate.begin(); it2 != vPlayersToUpdate.end(); ++it2)
		{
			MajorCivApproachTypes eApproach = GetBestApproachTowardsMajorCiv(*it2, /*bFirstPass*/ false, /*bUpdate*/ true, vPlayersToUpdate, oldApproaches, bIgnoreApproachCurve);
			SetMajorCivApproach(*it2, eApproach);
		}
	}
	else if (vPlayersToUpdate.size() == 1)
	{
		// There's only one player to update, so we only need one pass of the function
		MajorCivApproachTypes eApproach = GetBestApproachTowardsMajorCiv(vPlayersToUpdate.front(), /*bFirstPass*/ true, /*bUpdate*/ true, vPlayersToUpdate, oldApproaches, bIgnoreApproachCurve);
		SetMajorCivApproach(vPlayersToUpdate.front(), eApproach);
	}
```

Approach is updated on a curve, so the values for each approach change gradually from turn to turn. I added bIgnoreApproachCurve so that when a player is resurrected, they perform an approach update without using this curve, since they've been dead. :)

What I'd like to do now is add the ability for the AI to "re-evaluate" a specific player or player(s) when a specific event happens; for instance, when a player is denounced, they set bIgnoreApproachCurve to true for the player who denounced them and that player's teammates, but use the default (false) for all other players. This allows for more dynamic reactions from the AI when the situation calls for it.

My desired approach is to add a vector to DoUpdateMajorCivApproaches with a list of players to reevaluate for the update; however, this would require searching through the vector to see if a player exists within it. I know how to iterate through all elements of a vector, but I'm not sure how to do a "if exists within" type search.

Alternatively, I could add another boolean memory value (m_pabReevaluatePlayer or something), but I'd rather minimize memory impact where possible.

**Comment by ilteroi** [comment]
i don't really understand the problem you are trying to solve, so take this with a grain of salt. here's the code review ...

1. it's a bit weird that during the first pass you ignore the return value from GetBestApproachTowardsMajorCiv() ... instead you seem to rely on a side effect. it's bad style and unintuitive for a getter to have side effects, normally they should be const.

2. is the second pass even necessary? from looking at the snippet you could do all that in one loop? but then maybe not because of side effects, see point 1.

3. in general you are over-optimizing ... the if/else clause is unnecessary, the performance impact is negligible and it makes the code more complex than it needs to be.

4. there are multiple ways to search in a vector. if it's unsorted, use std::find or find_if (both do a brute-force test of all elements, just like a hand-coded loop). if the vector is sorted use binary_search, which is more elegant. however for the relatively small vectors we have it doesn't make a lot of difference.

5. adding a single boolean won't kill anybody, and if it makes the code easier to understand i would go that way.

**Comment by RecursiveStar** [comment]
@ilteroi 
1 - First pass calculates the value and calls SetPlayerApproachValue.

Second pass calculates the value, if vPlayersToUpdate.size() > 1 then it uses data from GetPlayerApproachValue and modifies the final result, calls several functions if bUpdate is set to true, and then returns the approach.

I agree it's unintuitive - that's because I'm using the Firaxis function name and formatting. 

I also set it up this way so that it's possible to call GetBestApproachTowardsMajorCiv for a single civ ignoring the first/second pass stuff without calling DoUpdateMajorCivApproaches for all civs. After further reflection, however, that extra feature could be removed; you're probably right about it being over-optimization.

2 - Two passes are needed because it updates a (currently non-serialized) memory value for every player on the first pass, and then uses every player's value in the second pass.

3 - I thought removing the second pass (which is only necessary if vPlayersToUpdate.size() > 1) was worth the small addition in complexity. It's not hard to read.

4 - Thanks!

5 - Any value added to the diplo AI is multiplied by MAX_CIV_PLAYERS*MAX_MAJOR_CIVS in terms of memory impact from what I can see, so a boolean could end up taking over a KB. It's horribly ineffective.

In addition to the structure problems with the diplo AI that I've already mentioned, it appears in CvPlayer.cpp that all players, not just major civs, are given a diplo AI abd a deal AI. And also all major civs are given a minor civ AI. No idea why.

**Comment by ilteroi** [comment]
just one addition: there is a differnce between a const value and a const function. but i guess you're on the right track.

**Comment by RecursiveStar** [comment]
Yeah, that's what I meant.

**Comment by RecursiveStar** [comment]
@ilteroi 
Okay, so this is my new syntax:
```
		// Do a first pass of SelectBestApproachTowardsMajorCiv for each player and record (but do not update) the approach weights in a map; they will be used in the second pass.
		for (std::vector<PlayerTypes>::iterator it = vPlayersToUpdate.begin(); it != vPlayersToUpdate.end(); it++)
		{
			// Do we need to re-evaluate our approach towards this player? If so, ignore the approach curve.
			if (bIgnoreApproachCurve || (std::find(vPlayersToReevaluate.begin(), vPlayersToReevaluate.end(), *it) != vPlayersToReevaluate.end()))
			{
				SelectBestApproachTowardsMajorCiv(*it, /*bFirstPass*/ true, vPlayersToUpdate, oldApproaches, /*bIgnoreApproachCurve*/ true);
			}
			else
			{
				SelectBestApproachTowardsMajorCiv(*it, /*bFirstPass*/ true, vPlayersToUpdate, oldApproaches, /*bIgnoreApproachCurve*/ false);
			}
		}

		// Do a second pass of SelectBestApproachTowardsMajorCiv for each player and update/log the (possibly new) approach and weights.
		for (std::vector<PlayerTypes>::iterator it2 = vPlayersToUpdate.begin(); it2 != vPlayersToUpdate.end(); it2++)
		{
			// Do we need to re-evaluate our approach towards this player? If so, ignore the approach curve.
			if (bIgnoreApproachCurve || (std::find(vPlayersToReevaluate.begin(), vPlayersToReevaluate.end(), *it2) != vPlayersToReevaluate.end()))
			{
				SelectBestApproachTowardsMajorCiv(*it2, /*bFirstPass*/ true, vPlayersToUpdate, oldApproaches, /*bIgnoreApproachCurve*/ true);
			}
			else
			{
				SelectBestApproachTowardsMajorCiv(*it2, /*bFirstPass*/ true, vPlayersToUpdate, oldApproaches, /*bIgnoreApproachCurve*/ false);
			}
		}
```

Is this correct? No build errors in the compiler.

An annoying side effect of this is that I had to add a blank vector in every place where DoUpdateMajorCivApproaches is called, since it doesn't seem possible to pass it as an optional parameter. However, I intend to rework the code in the future so that this will flow more naturally, so it's just a temporary annoyance.

**Comment by RecursiveStar** [comment]
Okay, IMPROVED syntax:
```
		// Do a first pass of SelectBestApproachTowardsMajorCiv for each player and record (but do not update) the approach weights in a map; they will be used in the second pass.
		for (std::vector<PlayerTypes>::iterator it = vPlayersToUpdate.begin(); it != vPlayersToUpdate.end(); it++)
		{
			// Do we need to re-evaluate our approach towards this player? If so, ignore the approach curve.
			if (std::find(vPlayersToReevaluate.begin(), vPlayersToReevaluate.end(), *it) != vPlayersToReevaluate.end())
			{
				SelectBestApproachTowardsMajorCiv(*it, /*bFirstPass*/ true, vPlayersToUpdate, oldApproaches, /*bIgnoreApproachCurve*/ true);
			}
			else
			{
				SelectBestApproachTowardsMajorCiv(*it, /*bFirstPass*/ true, vPlayersToUpdate, oldApproaches, /*bIgnoreApproachCurve*/ false);
			}
		}

		// Do a second pass of SelectBestApproachTowardsMajorCiv for each player and update/log the (possibly new) approach and weights.
		for (std::vector<PlayerTypes>::iterator it2 = vPlayersToUpdate.begin(); it2 != vPlayersToUpdate.end(); it2++)
		{
			// Do we need to re-evaluate our approach towards this player? If so, ignore the approach curve.
			if (std::find(vPlayersToReevaluate.begin(), vPlayersToReevaluate.end(), *it2) != vPlayersToReevaluate.end())
			{
				SelectBestApproachTowardsMajorCiv(*it2, /*bFirstPass*/ true, vPlayersToUpdate, oldApproaches, /*bIgnoreApproachCurve*/ true);
			}
			else
			{
				SelectBestApproachTowardsMajorCiv(*it2, /*bFirstPass*/ true, vPlayersToUpdate, oldApproaches, /*bIgnoreApproachCurve*/ false);
			}
		}
```

**Comment by RecursiveStar** [comment]
On further reflection, I probably don't need to rename the second iterator it2, since it's cleared after the loop.

**Comment by RecursiveStar** [comment]
Pushed!
