### ISSUE TITLE
PSA: the LUA trap

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6644]
i just found an issue that might be responsible for a lot of UI problems.

there are two ways to create a lua wrapper for a c++ method.

one is the manual approach, eg here:
```
int CvLuaCity::lGetCityUnhappinessBreakdown(lua_State* L)
{
	CvCity* pkCity = GetInstance(L);
	const bool bIncludeMedian = luaL_optbool(L, 2, false);
	const bool bFlavor = luaL_optbool(L, 3, false);
	lua_pushstring(L, pkCity->GetCityUnhappinessBreakdown(bIncludeMedian, bFlavor));
	return 1;
}
```

or the templated approach:
```
int CvLuaPlayer::lIsCanHurry(lua_State* L)
{
	return BasicLuaMethod(L, &CvPlayerAI::IsCanHurry);
}
```

now the problem is when the lua / c++ method has optional parameters.

in the first case, you can use optbool or optint to check if the parameter exists and have a defined default value for the c++ call.

in the second case, assuming the method has two optional parameters, the two-parameter template will be used. unfortunately it seems that the template blindly takes two values from the lua stack and uses them to overwrite the defaults on c++ side! these values could be anything ...

that is obviously very dangerous, and what's worse it can happen inadvertently when you add a new parameter to a c++ method that is already exposed to lua. that can mean code that used to work reliably is silently broken!

so we have to be very careful with those templates. it's not feasible to re-implement all those calls now but if you ever have a problem, it's probably worth checking whether the template is to blame.

**Comment by RecursiveStar** [comment]
Good to know, thank you!

**Comment by LoneGazebo** [comment]
hmm, are there are any we need to sort out at present?

**Comment by ilteroi** [comment]
well i noticed because the resource overview was inconsistent. that's fixed now, don't know about anything else ...
