### ISSUE TITLE
Splash damage does not apply when targeting units in cities

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#6645]
_1. Mod version (i.e Date - 4/17): 4/17

_2. Mod list (if using Vox Populi only, leave blank): many mods, but none affecting promotions

_3. Error description:_ 

When my artillery units possessing the splash promotion target cities (with units in them), the enemy units surrounding the city do not receive any damage. Is it intended? (the tooltip mentions only targeting units, not cities, so it probably is ... ?)

**Comment by LoneGazebo** [comment]
Correct, only works when targeting units specifically, and cities trump units in targeting order.
