### ISSUE TITLE
Terrace farms don't get adjacency bonuses

### ISSUE THREAD

**Issue by Leyvatein** [LoneGazebo/Community-Patch-DLL#6648]
_1. Mod version (i.e Date - 4/17):_
4-17

_2. Mod list (if using Vox Populi only, leave blank):_
CBP, CBO, info addict, wonder race

_3. Error description:_ 
In the civilopedia it is said that terrace farms receive +1 food for adjacent farms, actually terrace farms don't get any bonus food, not when being adjacent to farms nor when they are adjacent to other terrace farms

_4. Steps to reproduce (optional):_
build a terrace farm and a farm next to each other

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/60935129/83965045-244e2400-a8b1-11ea-8f2f-56f6f358d849.png)

**Comment by LoneGazebo** [comment]
Not a bug, intended.

**Comment by RecursiveStar** [comment]
Text says they give adjacency bonuses to nearby Farms but don't receive them, which seems to be working as intended.
