### ISSUE TITLE
Suboptimal city governor

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6649]
_1. Mod version (i.e Date - 4/17):_4/17

Default AI city governor doesn't seem to be making right choices when it comes to producing a Settler.

Picture 1: Default governor chooses working only food-rich lake tiles, gets the Settle finished in 7 turns, but no food is accumulated (due to production of Settler).

Picture 2: Production focused governor does the right choice by using the hill tile to speed up the settler. 

I guess, default governor should be behaving like production governor during the building of a Settler since choosing food tiles provides no benefits .

![20200607152742_1](https://user-images.githubusercontent.com/16341598/83968771-22498c80-a8d4-11ea-9998-cf94a354b9ad.jpg)
![20200607152755_1](https://user-images.githubusercontent.com/16341598/83968772-237ab980-a8d4-11ea-87a4-b874dbc6df34.jpg)

**Comment by RecursiveStar** [comment]
When building a Settler food tiles do provide a Production benefit. You can mouse over the Production yield to observe this.

**Comment by saamohod** [comment]
>When building a Settler food tiles do provide a Production benefit. 

I know. But it's not worse it in my particular case as you may see.

**Comment by ilteroi** [comment]
check this:

![image](https://user-images.githubusercontent.com/1358966/84136255-54c9c580-aa4b-11ea-8f0e-d4e4f651a4a5.png)

this is with all governors except production, which correctly works the plot to the northwest.

**Comment by LoneGazebo** [comment]
Growth is important yo.

**Comment by RecursiveStar** [comment]
> 
> 
> Growth is important yo.

Speaking of that, shouldn't the Food focus governor be working the northeastern most tile with 3 Food?

**Comment by ilteroi** [comment]
ok maybe i was a bit too terse ...

the governor is working a 2f1p plot when it could be working a 2f2p1g plot. that is decidedly suboptimal.

**Comment by LoneGazebo** [comment]
Jungle pantheon?

**Comment by ilteroi** [comment]
yes indeed! my bad, didn't think of that.

so it's working as intended ... there's only one way to put it:

![image](https://user-images.githubusercontent.com/1358966/84191074-3d64f980-aa98-11ea-9655-aa416c622485.png)

**Comment by ilteroi** [comment]
so here's another one, what's going on here?

![image](https://user-images.githubusercontent.com/1358966/84418106-f2252500-ac16-11ea-8c08-5523c83ba8d4.png)

this is an occupied city ... the governor prefers laborers over the desert plots. also, the city has a lot of food, but excess is zero?

**Comment by LoneGazebo** [comment]
-100% from unhappiness.

**Comment by LoneGazebo** [comment]
What are laborers making?

**Comment by ilteroi** [comment]
so if food has no effect, that's another reason to work production tiles.

the laborers are 1p1g

**Comment by ilteroi** [comment]
another case, the laborer is 1p1g ... why isn't he working one of the free jungle plots?

![image](https://user-images.githubusercontent.com/1358966/85073339-e3acaf80-b1ba-11ea-958b-193dfd94239b.png)

also, +8 unhappiness on city growth? can this be true?

![image](https://user-images.githubusercontent.com/1358966/85073607-646bab80-b1bb-11ea-97b6-f670d6368752.png)

oh damn it is true. then again, why does the next citizen only give 1 extra unhappiness? why is this so non-linear? why did the city have a gold deficit of 51 with 18 pop, and now 97 with 19 pop? questions over questions.

**Comment by LoneGazebo** [comment]
City yield needs are static and locked until growth. So growth can often result in a big bump of unhappiness if you are really slow to grow. 

For the laborer issue, what does the IDE say when you check specialist value?

**Comment by ilteroi** [comment]
you always have a good explanation ... it's just that the UI is hell ... how about we change it to "Local Unhappiness X (Set Y Turns Ago)"?

also i have a hard time believing that the median (!!!) is 10 gold per pop per turn. the log says:
Turn: 241, Food/Production: 421, Gold: 472, Science: 244, Culture: 305. 

so there is a hidden factor of two. where does that come from and where is it logged?

coming back to the laborer, this is what the debugger says:

specialistValueCache
	[0]	(1, 20)
	[1]	(4, 89)	
	[2]	(5, 71)	
	[3]	(6, 112)

**Comment by LoneGazebo** [comment]
the UI shows you the unhappiness modifiers if you hover over the unhappy face in the cityview tooltip.

**Comment by saamohod** [comment]
The bug is still present in 6-19 version, in addition to the locked citizen bug.
This is automated governor's choice (forest tile instead of fish tile):

![20200620184052_1](https://user-images.githubusercontent.com/16341598/85205731-d8c25e00-b325-11ea-8364-984ea57baa84.jpg)
