### ISSUE TITLE
Hidden antiquity sites are revealed without archaeology

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#665]
Sorry if this has been discussed or it's intentional. Hidden antiquity sites become visible as soon as you max the aesthetics tree, which can happen very long before researching archaeology to see even basic antiquity sites.

**Comment by LoneGazebo** [comment]
This is by design, yep. Gives you time to plan ahead.

**Comment by Edaka** [comment]
Oh, okay, got it. It just seemed a little too weird, but not a big deal.

**Comment by Radost** [comment]
What to plan exactly? You can't "pre-build" archaeologists before Archaeology anyway.
