### ISSUE TITLE
consolidate bonus notifications

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6656]
is there a way to get a combined notification for all yield bonuses received in the last turn?

right now it's crazy, and i have only 8 cities ...

![image](https://user-images.githubusercontent.com/1358966/84036194-2db4ba80-a99d-11ea-9a36-54e5ca254683.png)

**Comment by LoneGazebo** [comment]
They are 'merged,' but they can't be double-merged without losing information.

**Comment by ilteroi** [comment]
well, how bad can it be? it's not like anyone is reading those right now ... so you could say information is being lost all the time :)

**Comment by LoneGazebo** [comment]
the notifications are merged by yield, but since the notifications for each 'type' trigger independently the merge would have to happen in the EUI lua. I tried it once and the notification text boxes were being cut off. Data was lost.

**Comment by ilteroi** [comment]
how about a single "bonuses on turn change" notification? would that work? not sure how to handle the battle and GP bonuses, but at least all the quests, border expansion, pop growth, etc can be consolidated.

or maybe just drop the worst offenders?

or even better, stack all notifications of the same type? would need some lua skill though.

many ideas for a small issue :)

**Comment by RecursiveStar** [comment]
From my own experience the huge barrage of notifications in later turns is an annoyance, and I end up just dismissing them all without reading them (especially as instant yield notifications are not the most useful). I imagine I'm not alone in this.

**Comment by azum4roll** [comment]
If this is doable, please also make it optional.

**Comment by ilteroi** [comment]
ok, stacking is easy, just add a B to NotificationPanel.lua
```
	NOTIFICATION_INSTANT_YIELD			InstantYieldItem	B
```

the lost information can be integrated in the top panel tooltip. it claims to show the instant yields from the last turn anyway but currently it doesn't.
