### ISSUE TITLE
better differentiation between tercio and musketman

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6657]
i don't if i'm the only one but i constantly confuse tercios and musketmen.

which is which? would it be possible to use more distinct icons?

![image](https://user-images.githubusercontent.com/1358966/84036621-b9c6e200-a99d-11ea-8254-b99f2e14b5e8.png)

**Comment by LoneGazebo** [comment]
I don't have the art, but someone might make it for us. They're both vanilla assets.

**Comment by ASCII-Guy** [comment]
@LoneGazebo here you go. I extracted the original from Expansion1UITextures.fpk

DDS download: https://drive.google.com/file/d/1bWUnzPw_3wqwX3-2gcRK-IScfOL58FDk/view?usp=sharing

![sv_tercio](https://user-images.githubusercontent.com/14044545/84089338-8dae5f80-a9a3-11ea-879a-52615332d940.png)

**Comment by azum4roll** [comment]
I confuse between Spearman and Tercio more.

**Comment by ilteroi** [comment]
spearman and tercio are different eras ...

**Comment by pineappledan** [comment]
making the halberd heard slightly bigger would resolve the issue, no?

**Comment by pineappledan** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/pull/7648
