### ISSUE TITLE
Inconsistent allowed fort and citadel placement

### ISSUE THREAD

**Issue by Phosphoraptor97** [LoneGazebo/Community-Patch-DLL#6658]
_1. Mod version (i.e Date - 4/17):_4-17 beta with latest hotfixes

_2. Mod list (if using Vox Populi only, leave blank):_
Historical Religions Edit, Krajzen's GWAM Pack, Recurring Religion Purchases, InfoAddict, Promotion Flags for EUI, Really Advanced Setup

_3. Error description:_ 
Cannot build fort on tile where citadel can be built (no adjacent forts or citadels). Tile is specifically a tundra hill with sheep and pasture

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4747245/Lua.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4747247/xml.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/4747248/Database.log)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Fort Bug Report Saves 060920.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4747262/Fort.Bug.Report.Saves.060920.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20200609001117_1](https://user-images.githubusercontent.com/65775637/84056189-79408600-a9e8-11ea-88da-51cb37c5d80a.jpg)
![20200609001113_1](https://user-images.githubusercontent.com/65775637/84056194-7b0a4980-a9e8-11ea-9ea9-e3fa9070103c.jpg)

**Comment by ilteroi** [comment]
forts cannot be on top of resources because they don't connect resources unlike great people improvements. guess it's logical from a certain perspective ...
