### ISSUE TITLE
AI text word sequence

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#666]
Sorry to be nitpicking, but it seems that 'who do you will think benefit...' should instead be 'who do you think will benefit...', unless I'm actually illiterate (:.
![word sequence](https://cloud.githubusercontent.com/assets/12978597/10203643/f2565a8a-67bf-11e5-92eb-731827aeba7f.jpg)

**Comment by LoneGazebo** [comment]
I'll fix, thanks.
