### ISSUE TITLE
cannot ask to stop conversions

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6660]
isabella is swarming me with her missionaries, yet i cannot ask her to stop. is that by design?

**Comment by RecursiveStar** [comment]
Has she converted a city yet?

**Comment by RecursiveStar** [comment]
I could add another memory value so that whenever a missionary is used on a city, an option pops up for the other player - without needing to actually convert the city.

**Comment by LoneGazebo** [comment]
Easier would be to just allow the request if you've founded a religion, period. So either you've been converted once, OR you've founded.

**Comment by RecursiveStar** [comment]
Not a bad idea. Know any "IsFoundedReligion" LUA functions? I'll do a search...

**Comment by RecursiveStar** [comment]
HasCreatedReligion seemed promising, but it ends up pointing to CvGameReligions::GetReligionCreatedByPlayer, which has this check:
```
/// Get the religion this player created
ReligionTypes CvGameReligions::GetReligionCreatedByPlayer(PlayerTypes ePlayer) const
{
#if defined(MOD_BALANCE_CORE)
	if(ePlayer != NO_PLAYER)
	{
		return GET_PLAYER(ePlayer).GetReligions()->GetCurrentReligion();
	}
	else
	{
		return NO_RELIGION;
	}
#else
	ReligionTypes eRtnValue = NO_RELIGION;

	ReligionList::const_iterator it;
	for(it = m_CurrentReligions.begin(); it != m_CurrentReligions.end(); it++)
	{
		if(it->m_eFounder == ePlayer)
		{
			if(!it->m_bPantheon)
			{
				eRtnValue = it->m_eReligion;
			}
		}
	}
	return eRtnValue;
#endif
}
```
Seems like a non-indicative name.

**Comment by LoneGazebo** [comment]
GetCurrentReligion() is I believe a founder check. It’s what I use in the ReligionOverview.lua

**Comment by RecursiveStar** [comment]
Eh, why not give it a try I guess? I'll fix.

**Comment by RecursiveStar** [comment]
Not a whiz at LUA by any means but I think this should work. https://github.com/LoneGazebo/Community-Patch-DLL/pull/6661/commits/cd8e515cc01fccbda3805c02aacf7ca24ce635d6

**Comment by ilteroi** [comment]
still cannot ask her to stop, even after she converted one of my cities now ...

![image](https://user-images.githubusercontent.com/1358966/84386615-ef640900-abf1-11ea-8f1a-cc5bae5b0300.png)

this is with the very latest build, of course.

**Comment by LoneGazebo** [comment]
Did you make the necessary lua change?

**Comment by ilteroi** [comment]
oh, i didn't realize it is a lua change ...
