### ISSUE TITLE
Automissions

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6663]
Does anyone know what automissions are for? Can that code be removed?

**Comment by RecursiveStar** [comment]
Isn't there code to automatically spread religion, CS Influence and extract artifacts? I don't recall using it (maybe the button wasn't there, maybe I didn't notice it), but that's my best guess as to what it could be.

**Comment by LoneGazebo** [comment]
why remove?

**Comment by ilteroi** [comment]
there was a bug where units executed stale missions and just deleting the automission stuff would have been the easiest solution. but i found another way.
