### ISSUE TITLE
I got one of each great person around turn 50

### ISSUE THREAD

**Issue by 4gkenzy** [LoneGazebo/Community-Patch-DLL#6665]
_1. Mod version (i.e Date - 2/9):_
April 17 beta patch

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Title, no idea what happened. 

_4. Steps to reproduce (optional):_
If no one else has reported this bug, let me know and I can upload a save file. Using no other mods. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
More info please.

**Comment by RecursiveStar** [comment]
First I've ever heard of this bug. Please do upload a save file. :)

**Comment by Mileslewis** [comment]
Maybe you got the city-state quest somehow?
