### ISSUE TITLE
Question regarding removing a global

### ISSUE THREAD

**Issue by RecursiveStar** [LoneGazebo/Community-Patch-DLL#6667]
Suppose I were to remove a vanilla global from the database...

Example: APPROACH_NEUTRAL_DEFAULT, a vanilla value which is used in vanilla but that use was removed in VP. It is extremely unlikely to ever see use in VP. Its value is 4 and it is in the table "Defines" which has a Name and Value column.

Could I remove the vanilla global from the database by doing the following?
1) Removing all DLL references to the global.
2) Adding the following line to an SQL file in the Community Patch folder:
```
DELETE FROM Defines WHERE Name = 'APPROACH_NEUTRAL_DEFAULT';
```

**Comment by ilteroi** [comment]
you could do that but it's extremely tedious. so i would say leave the database alone, it's a mess but it can easily be ignored :)

**Comment by RecursiveStar** [comment]
Yeah, I get that - but my question is simply, would it work if I did? :)
