### ISSUE TITLE
Temple with Organized Religion tooltip

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#667]
First off, EUI preview dublicates the +1 faith from Organized Religion (shows +1f, +1f, +1c). Secondly, when the policy is adopted it shows additional +2 culture instead of +1. The issue is just the tooltip - the actual yields are correct.
![temple1](https://cloud.githubusercontent.com/assets/12978597/10208528/93bf0df6-67dc-11e5-895a-b201f2634c4f.jpg)
![temple2](https://cloud.githubusercontent.com/assets/12978597/10208529/94c2583e-67dc-11e5-9a7e-6116c73031c5.jpg)

**Comment by LoneGazebo** [comment]
Fixed, I think. We'll see.
