### ISSUE TITLE
Captured city unhappiness + oversupply of military units = negative food

### ISSUE THREAD

**Issue by Leyvatein** [LoneGazebo/Community-Patch-DLL#6670]
_1. Mod version (i.e Date - 4/17):_
4-17

_2. Mod list (if using Vox Populi only, leave blank):_
cbp, cbo, wonder race, infoaddict

_3. Error description:_ 
Captured cities are unhappy from occupation, if you have more units than your supply then you have NEGATIVE food, instead of being at 0 (stagnation)

_4. Steps to reproduce (optional):_
Annex a city while being over your military supply

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

4. Screenshots (optional):
With over supply:
![image](https://user-images.githubusercontent.com/60935129/84309106-ecb8d380-ab5f-11ea-8a85-299b2a90da3d.png)

After deleting units so I dont exceed my supply:
![image](https://user-images.githubusercontent.com/60935129/84309133-fcd0b300-ab5f-11ea-94ce-165840548eb9.png)

**Comment by silentreply** [comment]
@Leyvatein Are you sure you have the 4-17 version? This looks like an earlier version. The -100% growth modifier during resistance was removed in this version, see #6568.

**Comment by Leyvatein** [comment]
I am 100% sure it's the 4-17 version, it says so in both of the .modinfo files

**Comment by silentreply** [comment]
Ok I noticed a key difference is that your city is not under resistance. It seems the -100% modifier was removed only for the resistance period.
