### ISSUE TITLE
did i mention i hate spain?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6671]
![image](https://user-images.githubusercontent.com/1358966/84386847-5681bd80-abf2-11ea-999d-5ac982ba880c.png)

i cannot spread to the city state, in spite of the active quest. i know it's because spain is their ally but something has to give ...

**Comment by supermerill** [comment]
spain, the new england?

**Comment by LoneGazebo** [comment]
haha
