### ISSUE TITLE
unhappiness not capped by population?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6673]
take a look here:

![image](https://user-images.githubusercontent.com/1358966/84436738-3a067500-ac34-11ea-9604-dd4cd876c4db.png)

the city has 11 citizens but 13 unhappiness ... i though that was not supposed to be possible?

**Comment by bentakacs** [comment]
Urbanization comes top on needs, hence it can make a city to have more Unhappiness than Population.

**Comment by RecursiveStar** [comment]
Yeah Urbanization is a flat 1 Unhappiness per specialist, uncapped.

I think it should probably be displayed at the top of the list to avoid confusion.

**Comment by ilteroi** [comment]
it should be in it's own category with a hint
