### ISSUE TITLE
city state protection

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6674]
how does the AI decide which minor to protect?

one the one hand i see this, polynesia doesn't seem to care about their ally

![image](https://user-images.githubusercontent.com/1358966/84487853-a9657e80-ac9f-11ea-8a18-62ebabb1969f.png)

on the other hand this, everybody seems to love samarkand.

![image](https://user-images.githubusercontent.com/1358966/84487934-c601b680-ac9f-11ea-92a0-e44d1965a04c.png)

both are far from polynesian cities btw.

**Comment by RecursiveStar** [comment]
If AI's minor civ approach is protective and they can protect (meet the required conditions) they will protect.

**Comment by RecursiveStar** [comment]
I've made improvements to GetBestApproachTowardsMinorCiv but haven't given it the thorough revision that SelectBestApproachTowardsMajorCiv has yet - feel free to improve it if you see problems.
