### ISSUE TITLE
AI not not protecting civilian units well/not keeping military near capital

### ISSUE THREAD

**Issue by JamesNinelives** [LoneGazebo/Community-Patch-DLL#6679]
_1. Mod version (i.e Date - 4/17):_
4/17/2 with bufixes

_2. Mod list (if using Vox Populi only, leave blank):_
Community Events
Quick Turns
Really Advanced Setup
Historical Religions
Krazjen's Art, Music, and Writing packs

_3. Error description:_ 
AI seems to be building settlers to expand early (which is good) but not have many military units near their capital such that their settler either gets captured or is stuck in/near the capital until the barbarians nearby are taken care of. Sometimes workers will get captured as well. Results in a significant delay to the civ's expansion and development.

It's possible the AI is unable to judge that their units are in danger due to the Barbarians' 'Walker' promotions (e.g. Forest Walker). Regardless, it's bizarre that they have military units elsewhere on the map who seem to be scouting but don't know to keep such units near the capital to protect it and their civilians. Granted they may have had military units that got killed by barbarians, but it still seems strange e.g. using a spearman as a recon unit when it would do much better at killing or defending against barbs.

---------------------------
Screenshots:

England lost a settler, which I returned to them. It took some time after that to settle their second city though. I can't see any military units of their nearby. They had a relatively slow start in this game, despite getting a settler out early with the help of Tutelary Gods. 

![20200612211708_1](https://user-images.githubusercontent.com/61379041/84625472-e6d34180-af15-11ea-8d70-5de4c12fc59b.jpg)
![20200612211923_1](https://user-images.githubusercontent.com/61379041/84625478-e9ce3200-af15-11ea-9b60-fd5f1d2fdf55.jpg)
![20200612212103_1](https://user-images.githubusercontent.com/61379041/84625480-eb97f580-af15-11ea-955c-fc48acadf36e.jpg)

Here the Shoshone have a settler and a worker being menaced by barbarians.  They have a spearman up near my capital which shows no interest in heading back home to help. They did expand eventually and do pretty well in this case though.

![20200614211618_1](https://user-images.githubusercontent.com/61379041/84625603-2ef26400-af16-11ea-8c3f-75ff2fa06b10.jpg)
![20200614212012_1](https://user-images.githubusercontent.com/61379041/84625605-30bc2780-af16-11ea-9ac9-1674b0690b73.jpg)
![20200614212016_1](https://user-images.githubusercontent.com/61379041/84625607-31ed5480-af16-11ea-863b-dc4065502a4e.jpg)

Here Washinton lost a worker to barbarians and has one camped outside his capital. I returned the worker, and he does have one warrior near the capital but with both a settler and a worker at risk I feel he really should have better protection for them. Washington had a slow start in this game similar to England previously, which I have to attribute in part to his trouble with barbarians.

![20200614213732_1](https://user-images.githubusercontent.com/61379041/84625739-74169600-af16-11ea-96af-b77273eeea93.jpg)

**Comment by RecursiveStar** [comment]
@JamesNinelives Might already be fixed. Which bugfixed DLL are you using?
