### ISSUE TITLE
CPP problem

### ISSUE THREAD

**Issue by djmumsy** [LoneGazebo/Community-Patch-DLL#668]
Hi, i don't know why but when i install CPP a lot of things changed in my game, but for example social policies did not (still have honor etc.) couldn't find the solution, i can post screenshots of sth if needed.

THANKS

**Comment by Mitchsp** [comment]
This place is mainly to notify specific bugs, probably your best shot is here Community Patch - How To Install http://forums.civfanatics.com/showthread.php?t=528034 and Community Patch - Bug Reports http://forums.civfanatics.com/showthread.php?t=528142

**Comment by LoneGazebo** [comment]
Sounds like you didn't delete your cache.
