### ISSUE TITLE
AI don't seem to know to heal their recon units

### ISSUE THREAD

**Issue by JamesNinelives** [LoneGazebo/Community-Patch-DLL#6680]
_1. Mod version (i.e Date - 4/17):_
4/17/2 with bufixes

_2. Mod list (if using Vox Populi only, leave blank):_
Community Events
Quick Turns
Really Advanced Setup
Historical Religions
Krazjen's Art, Music, and Writing packs

_3. Error description:_ 
The AI has recon units running around in relatively safe territory at as little as 5 or 10 hp. I've seen this multiple times and while I can rationalise a risk-reward situation for low level recon units during the crucial early turns of the game it really is poor decision-making when you have a high-level promoted unit doing the same. Particularly units which have the extra healing promotions could heal to full in as little or 2 or three turns and yet I often see them travelling around barely alive as if nothing was wrong.

---------------------------
4. Screenshots (optional):

Here's a highly promoted Scout belonging to the Shoshone in the ancient era (a very valuable unit) at 5hp.

![20200614211503_1](https://user-images.githubusercontent.com/61379041/84626301-6e6d8000-af17-11ea-8b6f-b44f7f10adb2.jpg)
![20200614211618_1](https://user-images.githubusercontent.com/61379041/84626292-69a8cc00-af17-11ea-912d-e2e442e932c4.jpg)

Here's the same unit a number of turns later. It has gained 5 hp to a total of 10hp, probably from being promoted again. It spend some time near my capital where I know there was nothing threatening it because I was patrolling with my own units. The Shoshone aren't at war with anyone either, so there was zero risk of healing up there.

![20200614212208_1](https://user-images.githubusercontent.com/61379041/84626346-804f2300-af17-11ea-9351-55d4ebdfe196.jpg)

**Comment by ilteroi** [comment]
too late for the big release but fixed

**Comment by JamesNinelives** [comment]
Awesome, thanks :).
