### ISSUE TITLE
What does 'Popular' mean?

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6684]
_1. Mod version - 4/17
Talking about the Syndicalism policy which is tier 2 Autocracy policy.

From wiki:
Syndicalism - Corporate Franchises count double in the cities of civilizations you are at least Popular with. Does not count against Global Franchise maximum.

What does 'Popular' mean exactly here? Would be useful for me to know but also seems like it could be explained better in the policy.

**Comment by RecursiveStar** [comment]
Your Tourism is at least Popular over the other civ's Culture.

**Comment by Mileslewis** [comment]
So all Civs that are in the lowest category count for this?

**Comment by RecursiveStar** [comment]
Influence levels are, from lowest to highest, Unknown > Exotic > Popular > Influential > Dominant.
