### ISSUE TITLE
Missing File: WonderPopup.xml

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6689]
@LoneGazebo Aqinu added the file "WonderPopup.xml" to the repository and the .civ5proj file references it - but it isn't added in the 6/19 release commit and isn't currently present in the repository.

It was added in this pull request: https://github.com/LoneGazebo/Community-Patch-DLL/pull/6606

**Comment by Aqinu** [comment]
It does work (glad that it does), but I don't know why it disappeared from this repository and also

> This branch is 429 commits ahead of LoneGazebo:master.

**Comment by LoneGazebo** [comment]
That’s my bad- I just forgot to physically cart it over.
