### ISSUE TITLE
Tradition opener gives 5% growth instead new 10%

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#669]

**Comment by LoneGazebo** [comment]
That's a typo mismatch - does it say that in the description? If so, it should say 5%.

**Comment by Mitchsp** [comment]
Yes, both description in game and in your patch notes says 10%.

**Comment by LoneGazebo** [comment]
Ah, that's just an oversight, should be 5% (10 was over-performing a bit). Thanks for the report.

G
