### ISSUE TITLE
Blank instant yields notification

### ISSUE THREAD

**Issue by dape6509** [LoneGazebo/Community-Patch-DLL#6691]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_
Info Addict
Strange Religions

_3. Error description:_ 
![blank_yield](https://user-images.githubusercontent.com/19981950/85193157-44072400-b283-11ea-9e52-e8bb86858da3.png)
This is the yield notification for completing Stonehenge, the faith was received properly.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4807401/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[AutoSave_0021 BC-3160.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4807398/AutoSave_0021.BC-3160.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
they are not really blank but stcked. you only get one per turn now. unfortunately this cuts off the text.

if you want to see the yields, you can hover the mouse over the star icon in the top bar.

**Comment by dape6509** [comment]
Thanks for clarifying! I can understand why people don't want multiple messages but I will probably revert this for my games as I actually like the long list of notifications, though even with that system some would get cut off or buried. Hopefully we can reach an ideal solution!

**Comment by Hokath** [comment]
I also thought this might be a bug.
Perhaps the tooltip could show the aggregate number, as is parsed in the star icon?
Maybe that's not feasible, idk

**Comment by phantommaxwell** [comment]
I noticed this too.  At first I wondered if it meant the Gift of the Pharaoh wasn't working.  A compromise would be to have 2 Stars, one for the last 10 turns, as usual.  Another Star for all on the current Turn.

**Comment by phantommaxwell** [comment]
Oh, nevermind, there already is a "This Turn" on the instant Yields Star.
