### ISSUE TITLE
Way Too Many Strategic Resources?

### ISSUE THREAD

**Issue by WhatsTheBadNews** [LoneGazebo/Community-Patch-DLL#6695]
_1. Mod version (i.e Date - 4/17):_ 6-19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ I am not 100% sure this is a bug, but I have way more Strategic Resources (iron, horses, paper) than I am used to. All of them say I am getting 30+ imported, but I only have one ally. I've attached my save game so someone more knowledgeable than me can confirm if there is an issue.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Ramesses II_0255 AD-1725.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4808758/Ramesses.II_0255.AD-1725.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20200620193708_1](https://user-images.githubusercontent.com/29821149/85214257-2b077d00-b32e-11ea-8156-849bd5a910ef.jpg)

**Comment by Hokath** [comment]
I'm observing similar but for me I'm sure its because of the Autocracy policy "Third Alternative"
INSERT INTO Policy_ResourcefromCSAlly
	(PolicyType, ResourceType, Number)
VALUES
	('POLICY_NATIONALISM', 'RESOURCE_OIL', 100),
	('POLICY_NATIONALISM', 'RESOURCE_COAL', 100);
-- Third Alternative
Bucharest is giving me 103 coal as opposed to just 3 :)

Perhaps this sort of table is used elsewhere and is causing your high levels of strategics also?

**Comment by InkAxis** [comment]
Same thing happening to me, but for an AI. And it's happening in the renaissance. I think it's likely from the Statecraft policy as that is the policy the Inca took. They have 34 of every single strategic, even ones they haven't discovered yet, like coal, oil and uranium.
![upload_2020-6-21_14-11-0](https://user-images.githubusercontent.com/40811935/85235736-43c67000-b3cc-11ea-993e-dd2f93ed706d.png)

**Comment by LoneGazebo** [comment]
I see why, someone added that value directly to stuff in the DLL.

**Comment by RecursiveVision** [comment]
Fixed in the hotfix.
