### ISSUE TITLE
Military unit stacking bug potentially linked to pop-up notification (natural wonder discovery)

### ISSUE THREAD

**Issue by dape6509** [LoneGazebo/Community-Patch-DLL#6696]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_
Info Addict
Strange Religions

_3. Error description:_ 
Moving scout unit through neutral CS warriors into clear territory, the scout stops on an occupied tile when the second Great Barrier Reef tile is revealed. Scout is able to move off this tile into adjacent tiles and cannot reoccupy the same tile afterwards. The game does force the player to move before being able to end the turn, so that is working correctly.

_4. Steps to reproduce (optional):_
Load attached save and move the scout to the jungle tile to the east as in the screenshots below.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4809034/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[AutoSave_0035 BC-2600.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4809035/AutoSave_0035.BC-2600.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20200621010422_1](https://user-images.githubusercontent.com/19981950/85219010-3e7e0c80-b35d-11ea-9386-d61c8502ff41.jpg)
![20200621010435_1](https://user-images.githubusercontent.com/19981950/85219016-4473ed80-b35d-11ea-8c5b-d69c0bd7d3de.jpg)
![20200621010444_1](https://user-images.githubusercontent.com/19981950/85219019-4fc71900-b35d-11ea-9225-8f260613ba49.jpg)
![20200621010511_1](https://user-images.githubusercontent.com/19981950/85219021-5786bd80-b35d-11ea-8fc5-668a1b7b6e96.jpg)
![20200621010523_1](https://user-images.githubusercontent.com/19981950/85219023-5f466200-b35d-11ea-97cd-29bff22d77c2.jpg)
![20200621010534_1](https://user-images.githubusercontent.com/19981950/85219035-813fe480-b35d-11ea-9757-6b302ca92281.jpg)
![20200621010537_1](https://user-images.githubusercontent.com/19981950/85219038-89981f80-b35d-11ea-96ef-5238d07397aa.jpg)

**Comment by Aqinu** [comment]
So what's the bug? Now units do stop if they discover an unit (if you want to change your direction), in this case is with a wonder...

**Comment by dape6509** [comment]
That's fair, it may be intended behavior but since the only other time I've seen stacked units is when there isn't an available tile to occupy when a unit is teleported or spawned.

**Comment by ilteroi** [comment]
only a bug if you end up stacked without a way out
