### ISSUE TITLE
6/19 Aircraft cap

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#6697]
Airports say they increase the Air Unit Capacity from 2 to 6.
The Civopedia says 6 to 10.
In any case, before airports I can only base 1 aircraft.

What is correct?

Also---and I might just be crazy---I swear some of my planes are just disappearing, without having engaged in any combat.

**Comment by Vyyt02** [comment]
I haven't noticed disappearing planes myself, but it is worth mentioning that now when air sweeps are not intercepted, they cause damage to the based airplanes (I think it starts with 5 HP and increases with promotions). Could this be happening? We're your planes damaged and did AI have enough fighters to sweep your airfields? I don't know if the "unit killed" with the super-sad taaaa-ta-daaa sound pops up when this happens.

**Comment by Hokath** [comment]
No, they didn't have any planes yet.

**Comment by Sphener** [comment]
@Hokath You aren't going craze, they are actually disappearing. I spent ten or so turns in my current game questioning my sanity when, despite me constantly building bombers, my power rating wasn't increasing at all. I then found out that bombers were randomly disappearing from my cities, despite me not being at war with anyone. I'll post a save with the bug soon.

**Comment by LoneGazebo** [comment]
@ilteroi is this a jumptovalid deletion issue?

**Comment by ilteroi** [comment]
don't think so.

also aircraft are not subject to deficit scrapping ...

**Comment by LoneGazebo** [comment]
hmm, so what's causing them to delete? That seems like something that the game is cleaning up on its own.

**Comment by Sphener** [comment]
To reproduce: just click end turn in the attached save file, the number of bombers I have should go down to 2 from 6 despite me not being at war with anyone. I've also attached the logs folder in case that's useful.

[Logs and save file.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4820841/Logs.and.save.file.zip)

**Comment by Mzimoxs** [comment]
Glad to see someone else with disappearing aircraft. I want to add: It only seems to happen with aircraft that did something the turn before (so rebasing or attacking). If I produce/buy a unit and let it idle it will stay.

**Comment by soeb80** [comment]
I can confirm the same problem with disappearing airplanes! All my air units disappears after a turn; after being rebased to a city with 1 air unit already stationed.

**Comment by ilteroi** [comment]
the disappearing part should be fixed ... #6725
