### ISSUE TITLE
Summary: Bugs with City Management

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6698]
Just to summarize the current reported bugs with city management:

**Confirmed for this version**
Bug No. 1: Unable to lock tiles properly. (#6692)

According to ilteroi, the offending line is 3147: SetForcedWorkingPlot(pPlot, false) in CvCityCitizens.cpp, which should be set to true.

Bug No. 2: City governor making suboptimal decisions that starve citizens. This bug has been reported multiple times in recent versions: #6649, #6563, #6447.

Combined with the city tile locking bug and that you cannot micromanage puppet cities (resulting in them starving unless annexed), it's a definite problem.

**Unconfirmed for this version**
Bug No. 3: Greater than -100% Growth modifiers are possible. (#6670)

There needs to be a check to make sure that the max growth penalty is never more than 100%.

Bug No. 4: Insane tile yields after turn 500. (#6677)

See that issue for explanation.

**Comment by ilteroi** [comment]
also there is the issue where the governor prefers not to work a tile at all and creates a laborer instead.

**Comment by LoneGazebo** [comment]
Worked on this last night. We’ll see how it does.

**Comment by Zuizgond** [comment]
Just started a game with the hotfixed version but got this:
![image](https://user-images.githubusercontent.com/64471766/85411973-588c3a80-b569-11ea-89c3-ca1796cfeb42.png)

I don't know if the latest version was supposed to fix bug No. 3 though

**Comment by Zuizgond** [comment]
Some turns later, despite having two 5-food tiles, default selection still prioritizes a 3-prod tile:
![image](https://user-images.githubusercontent.com/64471766/85420973-2df3af00-b574-11ea-8ebb-a58ee1665cbe.png)

**Comment by LoneGazebo** [comment]
Hmm. I've tried innumerable starts to see if I can get it to do that, to no avail. What's your pantheon?

**Comment by Zuizgond** [comment]
No pantheon yet.

**Comment by Aqinu** [comment]
Same issue with starving Puppet Cities (6-19-2)

![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/85595883-ea6f7280-b651-11ea-96f6-ab010ac925e0.png)

**Comment by HouyiTheArcher** [comment]
I confirm the issue, it also happens in my games quite often. I did a clear installation of mod, removing all leftovers from previous installations. 
It looks like there is no restriction for food output to be more or equal than "0". Sometimes cities starve on default focus, sometimes it's OK on default focus but on production, it also starts to starve.
This problem is especially annoying in early game. 
Attaching screenshots from my recent early game. All game setting are on default/standard.

![20200624180017_1](https://user-images.githubusercontent.com/13876697/85626444-bc9c2500-b675-11ea-98c5-14ada5b7323b.jpg)
![20200624180237_1](https://user-images.githubusercontent.com/13876697/85626480-c9b91400-b675-11ea-86e1-f709a81bc7bd.jpg)
![20200624180432_1](https://user-images.githubusercontent.com/13876697/85626487-ccb40480-b675-11ea-977a-0ffd6e0662c9.jpg)

**Comment by azum4roll** [comment]
City still starving in 6-19-2 version

![image](https://user-images.githubusercontent.com/14953746/85951832-588ca000-b998-11ea-8e75-9294dfd4ad7a.png)

There was also a city state that went back and forth between 1 and 2 pop until it grew to a 3 food tile.

**Comment by azum4roll** [comment]
Here's another

![image](https://user-images.githubusercontent.com/14953746/85952009-24fe4580-b999-11ea-89fc-ec1f0ee0784e.png)

**Comment by asche77** [comment]
Automatic starving bug confirmed from my end, too -- the governor just likes the obsidian hills too much and ignores food.

**Comment by azum4roll** [comment]
Cities with no 3+ food tiles and good <2 food tiles are still starving at 2-3 pop. While it could be beneficial for bringing up infrastructure faster, it's hurting capitals and delaying the first settler by a lot (until workers can build farms).

I suggest a different tile-selecting strategy for capitals that favours food tiles until they reach 4 pop, and never starving them below 4. (6 for tradition capitals)

**Comment by RecursiveVision** [comment]
@LoneGazebo This starvation bug just will not go away! I think it needs to be slain like the hydra.

**Comment by RecursiveVision** [comment]
@LoneGazebo Another report of the starvation bug on the forums: https://forums.civfanatics.com/threads/quick-questions-quick-answers.573489/page-333#post-15856292

**Comment by azum4roll** [comment]
There are lots of these in my AI match photojournal thread.

**Comment by Zuizgond** [comment]
Does AI select tiles based on default governor selection? If that's the case it may be stuck in a starvation loop.

**Comment by RecursiveVision** [comment]
@LoneGazebo Is the city starvation bug finally fixed?

**Comment by LoneGazebo** [comment]
I hope so. :)
