### ISSUE TITLE
Construction and Masonry

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#670]
Is it me, or did these two tooltips swap over in the tech tree?

**Comment by LoneGazebo** [comment]
I swapped the names and locations of the techs - part of the 'ui adjustments' I made. Same stuff is in each spot, but the techs are simply in different locations. Why? Seemed odd to me that the art icon of two guys building the pyramid came after the one of a polished brick!

**Comment by Hokath** [comment]
Ah ok! makes sense. The help text is the wrong way round in this case.

**Comment by Radost** [comment]
![8930_2015-10-03_00004](https://cloud.githubusercontent.com/assets/1131228/10262619/654c1f22-69e9-11e5-9756-a94895d0897c.png)
![8930_2015-10-03_00005](https://cloud.githubusercontent.com/assets/1131228/10262620/67b8f51e-69e9-11e5-85fe-6c8bdb8b4e45.png)
Doesn't look very intentional.

**Comment by LoneGazebo** [comment]
I'll fix the tooltip - most of the changes were intentional. :)
