### ISSUE TITLE
Rocket artillery has anti-tank free promo - intended?

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#6705]
_1. Mod version (i.e Date - 6/19): 4/17

_3. Error description: The Rocket Artillery has the 50% anti-tank promotion, is it intended? Aren't they supposed to be vulnerable to tanks?

**Comment by phantommaxwell** [comment]
Real life Rocket Artillery is effective vs Tanks.  Tanks should still be able to destroy if they can reach them.

**Comment by Vyyt02** [comment]
Yeah, I get the attacking part, but I am not so sure about the defending part. I must play a bit more, but it seems to me that they defend a bit too well against tanks.
