### ISSUE TITLE
Missing Files in Hotfix

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6706]
@LoneGazebo The hotfix doesn't seem to include my changes to LUA files or WonderPopup.xml.

**Comment by RecursiveVision** [comment]
Ah okay, they seem to be in the hotfix .exe, they're just not uploaded to Github yet.

**Comment by LoneGazebo** [comment]
I dunno why, I pushed my repo. I'll push again.
