### ISSUE TITLE
CTD on turn five or six

### ISSUE THREAD

**Issue by Cokolwiek-Unni** [LoneGazebo/Community-Patch-DLL#6708]
_1. Mod version (i.e Date - 4/17):_
6/19-2 hotfix

_2. Mod list (if using Vox Populi only, leave blank):_
Historical Religions Edit

_3. Error description:_ 
CTD on turn five or six, in several different games

_4. Steps to reproduce (optional):_
Hit the next turn

[AutoSave_0004 BC-3900.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4817995/AutoSave_0004.BC-3900.zip)

**Comment by Cokolwiek-Unni** [comment]
Also without any mods, bare VP, same thing, turn six

[AutoSave_0004 BC-3900.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4818243/AutoSave_0004.BC-3900.zip)

**Comment by bigcat88** [comment]
> 
> 
> Also without any mods, bare VP, same thing, turn six
> 
> [AutoSave_0004 BC-3900.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4818243/AutoSave_0004.BC-3900.zip)

Can't reproduce here. I haven'r ctd :(

**Comment by JamesNinelives** [comment]
I'm experiencing the same thing, occuring either in the early turns (<6) or in some cases on loading a saved game. I've tried with and without other mods, same outcome.

Supporting Information

Save on T5 for CTD at the end of T5 or start of T6 (unsure), crash report, and logs.

I renamed three of the logs because my PC tells me that the Assyrian city name Sam'al includes a character that cannot be in compressed files. I removed that character in the log names. In hindsight those logs may not be relevant, but I'm not sure which ones are so I included everything.
[Report2aZipped.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4818740/Report2aZipped.zip)

**Comment by JamesNinelives** [comment]
I just loaded Cokolwiek's save and got a crash at the same T5/T6.
Here's the crash report for it.
[Report2bzipped.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4818815/Report2bzipped.zip)

**Comment by LoneGazebo** [comment]
I'll look at it.

**Comment by Jarrke** [comment]
Similar situation here. First crash at turn 4, after loading autosave from turn2 crash immediatly after hitting end turn. 
Version 6-19-2 Vox Populi + EUI
other mods Quick Turns
[crash_report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4833797/crash_report.zip)

**Comment by JohannesGaessler** [comment]
I have this same issue with 6-19-2 or the new DLL by Ilteroi.
When playing with 6-19 I do **not** experience this issue.

**Comment by ilteroi** [comment]
this is why i included the PDB file. please post your callstack.log file!

**Comment by JohannesGaessler** [comment]
Here you go:

[debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4943533/debug.zip)

Mod list:

* Faster Building - Epic
* Really Advanced Setup
* Wonder Race

**Comment by ilteroi** [comment]
there are no logs ....

**Comment by JohannesGaessler** [comment]
I was playing on Linux via WINE when I experienced the CTD; I don't know if that influences the generation of logs.
I booted into Windows 10 to see if it makes a difference but on Windows I didn't experience a CTD at all.

**Comment by RecursiveVision** [comment]
We can't really fix bugs if you're not using Windows...

**Comment by JohannesGaessler** [comment]
>We can't really fix bugs if you're not using Windows...

While the bug in question does seem to be platform-dependent it is obviously not exclusive to WINE because otherwise I would be the only one reporting it.
My current policy is to report bugs and disclaim that I am playing on Linux if that could potentially be relevant for the bug.
If you decide that you don't want such bug reports please note this somewhere.

**Comment by RecursiveVision** [comment]
I may be wrong on VP only being Windows compatible, but I'm not sure the game config allows for creating logs normally if the OS isn't Windows, as it searches for a location using the Windows filesystem...

**Comment by JohannesGaessler** [comment]
I just realized that there has been a misunderstanding.
When I inspected the Callstack.Log file it only contained:

    Gamecore Callstack
    
    Lua Callstack

I was assuming that this is what Ilteroi meant when he said that there are no logs; meaning that there should be a stack trace in the Callstack.log file.
However, it seems that I accidentally zipped up an empty folder for the logs.
Here is a zip with the Logs actually attached:

[debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4944195/debug.zip)

**Comment by ilteroi** [comment]
well unfortunately the logs are not much use then ... either it crashed outside of the gamecore or the callstack generation somehow failed.

cannot load your save either, but that is unfortunately normal. so nothing to be learned here.

**Comment by cdanger341** [comment]
I can confirm this CTD as well. Occurs on turns 4-5 consistently, regardless of map script, game speed, choice of Civ, or use/not use of mods. I've been trying every possible permutation of mods and settings to see if I can get the game to run past turn 5 using the 6-19-2 version since it came out with no luck. Iterio's updates did not fix the problem. And it's frustrating because clearly other people are able to get it to run without crashing.

I am running Windows 7 with relatively modern hardware (aka more than enough RAM and GPU strength for the game engine) with up to date Nvidia drivers. I run the game in fullscreen with GPU texture decode turned OFF. I've tried running the game with otherwise maxed graphical settings and min settings, but it makes no difference. Crash on turn 4 or 5 every. Single. Time.

**Comment by ilteroi** [comment]
callstack.log?

**Comment by cdanger341** [comment]
This is the logs from my Logs folder from directly after the most recent crash. I don't see the callstack.log but I might not have proper logging enabled. If you could point me in the direction of how to make sure I have full logging enabled I can run some tests this evening and capture the crash logs.

[Logs Crash 200720 2225.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4955190/Logs.Crash.200720.2225.zip)

**Comment by RecursiveVision** [comment]
@cdanger341 https://forums.civfanatics.com/threads/can-we-get-a-tutorial-for-submitting-ctd-bug-reports-to-github.655371/#post-15681894

**Comment by ilteroi** [comment]
you should not even need to enable logging. callstack is dumped always. but it may be empty.

your zip file is also corrupted. seems like a conspiracy.

**Comment by cdanger341** [comment]
Weird. Let's try that again, this time with the CvMiniDump included.

[Logs Crash Take 2 200720 2225.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4955300/Logs.Crash.Take.2.200720.2225.zip)

**Comment by RecursiveVision** [comment]
Isn't corrupted for me, I can open the files normally.

_(Quick, everyone, hide the logs from ilteroi!)_

**Comment by ilteroi** [comment]
ok it works on the desktop. but there is no callstack log. that should not be possible, it's created together with the minidump.

but, suspecting that the root cause is the same is in #6829, the log is no use anyway.

**Comment by LoneGazebo** [comment]
I do find that if the crash is solely within the LUA, it won't produce the proper logs/dump.

**Comment by cdanger341** [comment]
Per Ilteroi's request, copied from the other ticket:

"It's not the graphics settings. I already tried adjusting every possible graphics settings from max to min and still saw consistent crashes on turns 4-5. It's also not non-VP mods as I've tried playing with just base VP 6-19-2 and the crashes are still consistent. These crashes did not occur in the initial 6-19 release, only post-hotfix. So it was something that was changed between 6-19 and 6-19-2."

**Comment by LoneGazebo** [comment]
@ilteroi getting a consistent crash here:

![image](https://user-images.githubusercontent.com/7849458/88226854-597cbe80-cc32-11ea-9448-43686e6df145.png)

**Comment by cdanger341** [comment]
I expanded my crash logs and did another run. Crashed upon hitting End Turn on turn 4 or 5 every time.

[Logs Crash 200722 1545.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4962508/Logs.Crash.200722.1545.zip)

**Comment by ilteroi** [comment]
@cdanger341 : unfortunately the callstack log is empty, so it seems your crash is somewhere else. do you have the PDB file in place?

@LoneGazebo 
* i've added the lua callstack to the callstack log a while a ago so it can be useful for lua issues as well
* anyway it's good you can reproduce the issue (hoping it's the same root cause)
* unfortunately your screenshot is two frames too far down in the callstack. can you show me the line and the local variables in CvPathFinder::GetPlotsInReach? 
* which revision is that anyway?

**Comment by azum4roll** [comment]
I got a "not responding" screen instead of a CTD once in my AI games. The logs are completely normal. Loading the autosave of the same turn progresses the game as usual.

**Comment by cdanger341** [comment]
@ilteroi Yes, I have the PDB file in place. Should I have included that as well with the crash log?

**Comment by ilteroi** [comment]
no but if it were missing that would explain the empty callstack log. 

can you try and install the debug helpers and see if that changes things?

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools#small-classic-windbg-preview-logo-debugging-tools-for-windows-10-windbg (don't need the full sdk!)

**Comment by cdanger341** [comment]
@ilteroi I see that the debugging tools are for Windows 10, but I'm still running Windows 7 (I'm old, and I like what I like!). I am more than happy to get a debug tool and assist further, but I want to make sure I get the correct one for my OS.

**Comment by ilteroi** [comment]
wait for the next crash and see if the callstack is logged

**Comment by cdanger341** [comment]
@ilteroi I checked and the call stack is still empty upon crash after installing the suggested debug tools. 

Something I discovered through some trial and error: If I adjust the starting Era and start a new game, it doesn't crash on turn 4 or 5 anymore. It DOES eventually crash again, but not until closer to turn 20-25, so there is something happening consistently during the AI's 4th or 5th turn during a normal Ancient era start that doesn't happen nearly as soon when starting in, say, the Industrial Era. From the AI logs, what is the AI doing consistently on their 4th or 5th turn?

**Comment by woortoo** [comment]
I have the same problem. As was mentioned in another ctd issue the game runs fine under original 6/19 version without hotfix. I hope this bug won't be carry over into the next version

**Comment by PhiLe20** [comment]
Woortoo what do you mean by "original 6.19 version". It's the latest version of the mod, the one I have installed, and the one that keeps crashing. Or is there another version of the 6.19 update? And is it maybe due to the automatic installer?

**Comment by woortoo** [comment]
> Woortoo what do you mean by "original 6.19 version". It's the latest version of the mod, the one I have installed, and the one that keeps crashing. Or is there another version of the 6.19 update? And is it maybe due to the automatic installer?

There are 6-19 and 6-19-2 versions. These CTDs occur with 6-19-2 only.

**Comment by cdanger341** [comment]
@ilteroi Okay, I think I got Windbg to run while attached to the Civ 5 executable and used the 'g' command to step through every exception until I got to a never-ending loop of exceptions that crashed the game (on turn 6 this time). Below is the usual Civ 5 logs, but I also included a copy of the entire console output of my Windbg session from beginning to crash.

[Crash Logs 200731 1420.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5008730/Crash.Logs.200731.1420.zip)

I don't think I used the .pdb library correctly as I got a lot of errors about not being able to find the correct symbols. After attaching the debugger to Civ 5, I entered the following commands:
'.sympath C:\..........'  (where ......... is the path to the .pdb file)
'.reload'
'g'

And then I reentered 'g' manually at each exception until I got to the loop of exceptions on turn 6. I should note that there were a number of handled exceptions nearly every turn during the AI processing, but it didn't get into the crash loop til turn 6. If you can suggest how to get the symbol library integrated properly, I would be happy to run the same save again with the debugger running.

**Comment by ilteroi** [comment]
civ5 depends on many external libraries, it's fine not to have the symbols for all of them.

also maybe you should enter the symbol path in quotes as is contains spaces? 

but there is an interesting hint in there: CvHomelandAI::PlotExplorerMoves(), this could be the culprit.
