### ISSUE TITLE
Morocco - Kasbahs problem

### ISSUE THREAD

**Issue by soeb80** [LoneGazebo/Community-Patch-DLL#6709]
_1. Mod version (i.e Date - 4/17):_
Latest to date; 6-19

_2. Mod list (if using Vox Populi only, leave blank):_
CP 6-19 installer (1,2,3,4,5,6a,7a,7b)
+Infoaddict

_3. Error description:_ 
Playing Morocco. Workers not able to build Kasbahs adjacent to my cities. Weird thing is; the workers can build the Kasbahs everywhere else, except adjacent to a city!

**Comment by Stalker012345** [comment]
Can confirm the behavior.

![image](https://user-images.githubusercontent.com/20593976/85421150-b43ecf80-b539-11ea-8233-06565cd2f5a9.png)

**Comment by ilteroi** [comment]
d'oh. my bad. forgot a negation ...
