### ISSUE TITLE
Arabia's UA increased yields from TR not working now in desert

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#671]

**Comment by LoneGazebo** [comment]
Only works for featureless desert - is it floodplains or hills?
G

**Comment by Mitchsp** [comment]
Yes, it's floodplains, so working right then.

**Comment by LoneGazebo** [comment]
Yeah, UA says 'featureless desert and plains,' so no flood plains/hills/oases, or forests/jungles/hills for plains.

G

**Comment by Mitchsp** [comment]
Thanks, didn't noticed the change.
