### ISSUE TITLE
AI doesn't move its units away from enemy ranged units

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6710]
_1. Mod version (i.e Date - 4/17):_6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

- Subs ignore borders http://www.picknmixmods.com/mods/CivV/Units/Subs Ignore Borders.html
- UI - religion spread (Vox Populi) https://forums.civfanatics.com/threads/ui-religion-spread-vox-populi.627375/
- UI - notify exit resistance http://www.picknmixmods.com/mods/CivV/UI/Notify Exit Resistance.html
- Quick Turns https://steamcommunity.com/sharedfiles/filedetails/?id=220250184
- Promotion flags EUI (for VP) version 3
- UI - wonder planner http://www.picknmixmods.com/mods/CivV/UI/Wonder Planner.html

_3. Error description:_ 

An embarked spearman has been sitting in one spot for 3 turns getting shot by my archers without an attempt to move away from the line of fire

![20200623160406_1](https://user-images.githubusercontent.com/16341598/85408340-0e0cbd00-b56d-11ea-8ec7-acdb30b1c644.jpg)

![20200623160520_1](https://user-images.githubusercontent.com/16341598/85407793-55df1480-b56c-11ea-8795-f3bd999e9c17.jpg)

Also a spearman standing on the hill never moved away from my archer's fire:

![20200623162412_1](https://user-images.githubusercontent.com/16341598/85409229-3cd76300-b56e-11ea-84a3-9055b741aed8.jpg)

![20200623162512_1](https://user-images.githubusercontent.com/16341598/85409234-3e089000-b56e-11ea-89e5-3fd197dc2807.jpg)

Logs included:
_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4819593/Logs.zip)

**Comment by ilteroi** [comment]
bad. but i played a bit and couldn't reproduce. so it's not so bad.

in fact, the AI wiped me out in a 3 on 1 war. that is humiliating.

**Comment by RecursiveVision** [comment]
Humiliated by your own creation? Great Scott! :)

**Comment by ilteroi** [comment]
well, the 3 on 1 part is your doing i guess!
