### ISSUE TITLE
Enhancer "Inquisition" doesn't provide the promised gold

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6711]
_1. Mod version (i.e Date - 4/17):_ 6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

- Subs ignore borders http://www.picknmixmods.com/mods/CivV/Units/Subs Ignore Borders.html
- UI - religion spread (Vox Populi) https://forums.civfanatics.com/threads/ui-religion-spread-vox-populi.627375/
- UI - notify exit resistance http://www.picknmixmods.com/mods/CivV/UI/Notify Exit Resistance.html
- Quick Turns https://steamcommunity.com/sharedfiles/filedetails/?id=220250184
- Promotion flags EUI (for VP) version 3
- UI - wonder planner http://www.picknmixmods.com/mods/CivV/UI/Wonder Planner.html

_3. Error description:_ 

Enhancer "Inquisition" doesn't earn any gold when converting heretics.

![20200623165642_1](https://user-images.githubusercontent.com/16341598/85412954-d739a580-b572-11ea-86d7-4c7847ab26f6.jpg)

![20200623165654_1](https://user-images.githubusercontent.com/16341598/85412958-d9036900-b572-11ea-87d1-da919cb69b06.jpg)

Logs:
[Logs (2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4819862/Logs.2.zip)

**Comment by saamohod** [comment]
Update: 
As I kept playing I noticed that the Enhancer did work in some cases in some cities. But mostly it didn't. 

I couldn't pinpoint a pattern.

**Comment by Aqinu** [comment]
I remember that the notification appears in the next turn maybe the gold is updated next turn?

**Comment by saamohod** [comment]
> 
> 
> I remember that the notification appears in the next turn maybe the gold is updated next turn?

It _could_ be. But then why in some cases I get the gold in the same turn, and in other cases in the next turn?

**Comment by Hokath** [comment]
I had it also. I did notice gold appearing above the holy city, and it was quite erratic. 
Perhaps the explanation is in the "converted" bit, that it is not the citizens whose religion is lost but only those who religion fully swaps?

**Comment by LoneGazebo** [comment]
Gold is earned from swaps, not just conversions.
