### ISSUE TITLE
Messed up unit's Upgrade button

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6712]
_1. Mod version (i.e Date - 4/17):_ 6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

    - Subs ignore borders http://www.picknmixmods.com/mods/CivV/Units/Subs Ignore Borders.html
    - UI - religion spread (Vox Populi) https://forums.civfanatics.com/threads/ui-religion-spread-vox-populi.627375/
    - UI - notify exit resistance http://www.picknmixmods.com/mods/CivV/UI/Notify Exit Resistance.html
    - Quick Turns https://steamcommunity.com/sharedfiles/filedetails/?id=220250184
    - Promotion flags EUI (for VP) version 3
    - UI - wonder planner http://www.picknmixmods.com/mods/CivV/UI/Wonder Planner.html

_3. Error description:_ 

Upgrade button description messed up for upgrade sometimes. Moving unit to other tile seems to help on the next turn.

![20200623222908_1](https://user-images.githubusercontent.com/16341598/85450666-a9b82080-b5a1-11ea-8b19-d4762458cd4c.jpg)

![20200623222918_1](https://user-images.githubusercontent.com/16341598/85450922-fb60ab00-b5a1-11ea-9b62-13dc8ca384b4.jpg)

![20200623225205_1](https://user-images.githubusercontent.com/16341598/85453171-41b70980-b5a4-11ea-90e2-f7c3177ba8a1.jpg)

**Comment by ilteroi** [comment]
can confirm, if upgrade is impossible you get the wrong tooltip

**Comment by saamohod** [comment]
Yes, seems to be the case only if I have insufficient gold for the upgrade.

**Comment by LoneGazebo** [comment]
what does lua.log say? Sounds like a busted variable.
