### ISSUE TITLE
Unit Promoted Missing Visual Attack Positions

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6715]
_1. Mod version (i.e Date - 4/17): 6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**No red circle under units if you have to choose a promotion**
![a](https://user-images.githubusercontent.com/49090452/85531269-48cb2f80-b617-11ea-841a-6ee67919a4a0.png)

**Red circle under units appears after you choose the promotion**
![b](https://user-images.githubusercontent.com/49090452/85531270-49fc5c80-b617-11ea-840c-19042542cb83.png)

**Comment by RecursiveVision** [comment]
This is intentional, ilteroi made it so that the combat preview wouldn't pop up if the promotion choice window is open.
