### ISSUE TITLE
Embarked Military Units not defending vs Naval Units

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#6716]
_1. Mod version (i.e Date - 4/17):_
6/19, no hotfix

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi package
ENW
3/4 UC

_3. Error description:_ 
Naval Units can just eliminate Embarked Military Units as if they were Civilians, by moving over them.   Both Melee and Ranged.  

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

Battle Preview 
![20200623143609_1](https://user-images.githubusercontent.com/11430209/85640118-ebf06900-b658-11ea-8ce8-7d1ceab62ab0.jpg)

Aftermath
![20200623143612_1](https://user-images.githubusercontent.com/11430209/85640119-ec88ff80-b658-11ea-9faf-402ed836db77.jpg)

**Comment by ilteroi** [comment]
hmm. seems to be a side effect from fixing some pathfinding issues, embarked units behave like civilians now.

honestly i'm loath to revert that, also for me this is more a feature than a bug.

opinions?

**Comment by saamohod** [comment]
I'd support this feature only if AI could guard their embarked units properly, and I'm not sure this is the case at the moment. Actually, I think it's the opposite now when AI "forgets" its embarked units: https://github.com/LoneGazebo/Community-Patch-DLL/issues/6710

**Comment by RecursiveVision** [comment]
Seems unfun to have units get killed off instantly when crossing between islands, across the sea, etc. It shuts down amphibious options unless you have a strong navy, and even then it weakens it.

They already have a large penalty when attacking. Also, the Amphibious promotion and Denmark's UA rely on amphibious assault mechanics. To me, it's more of a bug than a feature, and I think that part should be reverted.

**Comment by LoneGazebo** [comment]
Makes them super squishy @ilteroi

**Comment by ilteroi** [comment]
well the AI is much better with embarked units but maybe not perfect yet.

i'll see what i can do to fix it.

**Comment by Stalker012345** [comment]
I am in both camps. I agree with ilteroi that ultimately I see this as a feature not a bug.

However, while the AI has gotten better at embarkation protection, I don't think its good enough to leave the "feature" in. One day maybe!

**Comment by ilteroi** [comment]
well it's now back to the old behavior, i'm hoping that doesn't have other side effects now :)

**Comment by ilteroi** [comment]
well it's actually a compromise now:
* civilian stay civilians even when embarked, so you move into their plot to destroy them
* military units stay military units when embarked, so you can attack them and they defend against melee

**Comment by RecursiveVision** [comment]
I think that system works fine. No reason embarked civilians should be any more powerful than civilians on land.
