### ISSUE TITLE
CTD loading save with 6-19-2

### ISSUE THREAD

**Issue by Nigel--C** [LoneGazebo/Community-Patch-DLL#6718]
1. Mod version (i.e Date - 4/17): 6-19-2 no EUI
2. Mod list (if using Vox Populi only, leave blank): City Limits (v. 7), UI - Summary Clock (v 11)
3. Error description: CTD on load of previous save 
4. Steps to reproduce (optional):

---------------------------
Supporting information:
Game was started using version 6-19 no EUI. Installed 6-19-2 hotfix, now get CTD when loading previous save. Went back to 6-19 and save loads fine.

zip file attached with logs, save file and crash dump.
[ctd.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4829034/ctd.zip)

**Comment by kawyua** [comment]
https://forums.civfanatics.com/threads/new-official-version-june-19th-6-19.659579/page-6#post-15810600
yeah its savegame incompatible.
