### ISSUE TITLE
SetForcePeace and a never ending Peace Treaty

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#672]
Seems Team:SetForcePeace(), which was added at my request a while back, creates a permanent peace treaty; at least, war was blocked by a "current peace treaty" for some 50 turns (on standard). Is this something that can be fixed easily? It's not a major problem if not. Thanks.

**Comment by LoneGazebo** [comment]
Force Peace is, in the DLL, technically permanent peace. I'll look at it to see if it can work more like a standard treaty.

**Comment by LoneGazebo** [comment]
New setforcepeace function:

	SetForcePeace(eOriginatingPlayer, bPacifier, eTeam, bBumpUnits, bSuppressNotification)

Look good?

**Comment by JFDaly** [comment]
Looks good to me. Thanks.

**Comment by LoneGazebo** [comment]
Well, looking at it, there's already a makepeace function in the LUA which does what the above change does. Were you wanting something different? In other words, did you want a 'forced peace treaty' in which two civs can't attack each other? Because that's something different.

**Comment by LoneGazebo** [comment]
(and not necessarily simple to execute, as the code doesn't exist in the DLL).

**Comment by JFDaly** [comment]
That's what I intended - but if it's too difficult to implement then I wouldn't worry about it.

**Comment by LoneGazebo** [comment]
Ah, well there's no specific way to set a duration of 'no war' - the values are all boolean, not integral. Sorry. :/

**Comment by JFDaly** [comment]
No worries. I'm just grateful that you took the time to look anyway.

**Comment by LoneGazebo** [comment]
If it's any consolation, the 'forcepeace' function is actually used by the deal element, and therefore the deal lua. You could create a spoof deal in LUA and add it (adding a peace treaty gives you this 'forcepeace' element) that would then expire naturally. The problem with directly adding 'forcepeace' is that it never expires, as the deal is technically never created.
