### ISSUE TITLE
6/15 - CS allied with Enemy Civ still shows as friend

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6721]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This CS is an ally of a person I am at war with, and yet still shows me as a friend. I believe this is due to a weird interaction with Adobe of Peace which is my current belief.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/85785922-610e7d80-b6ef-11ea-8211-81e7db6159d1.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by JamesNinelives** [comment]
I've observed this as well! I never considered it might be due to Abode of Peace, but I have been taking that recently so seems plausible.
