### ISSUE TITLE
Inquisition does not work in cities without majority religion

### ISSUE THREAD

**Issue by Mzimoxs** [LoneGazebo/Community-Patch-DLL#6722]
June 19, Vox Populi only

Inquisitors have no effect when used in cities that do not have a majority religion. They only apply a turn of resistance. Prophets work fine.

**Comment by kawyua** [comment]
I'd like to add that even if this is intentional, the ai constantly tries to inquisitor their own cities even while there is no majority, making their own city in resistance every now and then, which is kind of abusable.

**Comment by ilteroi** [comment]
well i don't know if it's intentional but it is definitely not new.

the AI behavior is a problem though, even if i don't see how that could come about ... will check

**Comment by RecursiveVision** [comment]
@ilteroi It's also been reported on the forums that Byzantium AI seems reluctant to spread religion beyond its Holy City. Might be something to look at.

**Comment by ilteroi** [comment]
just checked, can confirm neither.

byzantium spreads just fine.

inquisitors can be used on cities without a majority.

AI will no longer use inquisitors if the harm is larger than the benefit.

**Comment by Mzimoxs** [comment]
Guess I'll have to upload a savegame then: Use the one inquisitor, it won't do anything. 
If you move him to my northest city with a different religion (will take a few turns, though) he would work just fine.

[Inq bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4840951/Inq.bug.zip)

**Comment by ilteroi** [comment]
so you're saying you can perform the inquisition (inquest?) but it has no effect?

**Comment by JamesNinelives** [comment]
Yes, I think that is the case. I haven't tried it on the current patch, but I've observed it on previous ones. I've gotten used to using missionaries on those cities instead as a workaround.

**Comment by ilteroi** [comment]
duplicate #6534
