### ISSUE TITLE
Disappearing air units

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6725]
_1. Mod version (i.e Date - 4/17):_ 6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

- Subs ignore borders http://www.picknmixmods.com/mods/CivV/Units/Subs Ignore Borders.html
- UI - religion spread (Vox Populi) https://forums.civfanatics.com/threads/ui-religion-spread-vox-populi.627375/
- UI - notify exit resistance http://www.picknmixmods.com/mods/CivV/UI/Notify Exit Resistance.html
- Quick Turns https://steamcommunity.com/sharedfiles/filedetails/?id=220250184
- Promotion flags EUI (for VP) version 3
- UI - wonder planner http://www.picknmixmods.com/mods/CivV/UI/Wonder Planner.html

_3. Error description:_ 

Two bombers disappeared from my city after AI turn. 

After performing strike on enemy unit and returning back to the base city almost uninjured, a bomber disappeared after I pressed skip turn. 

I built a second one, moved him to the frontlines and performed airstrike (I'm ahead of the AI and they don't have air units yet). The plane returned to the city barely scratched but it disappeared from my units list the next turn as well. 

Both times the city where the aircraft had been wasn't in any way attacked by the enemy. My gold income is in positives therefore I dismiss possible disbandment due to lack of money.

Logs attached:

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4836740/Logs.zip)

**Comment by LoneGazebo** [comment]
Second of these @ilteroi – really think there's an issue with the jump command.

**Comment by ilteroi** [comment]
why would they need to teleport?

**Comment by LoneGazebo** [comment]
If there’s a bug with stacking it might try to jump them somewhere

**Comment by ilteroi** [comment]
so there's a bug with stacking that triggers sometimes and a bug with teleporting air units?

**Comment by LoneGazebo** [comment]
I can't read logs at the moment, are 'failures to jump to a valid plot' logged?

G

**Comment by ilteroi** [comment]
yes it should say something like "Can't find a valid plot for ..." in the homeland log.

anyway i added jump code specifially for aircraft, let's see.

**Comment by paramenides** [comment]
My planes are not teleporting. They are actually just disappearing.
