### ISSUE TITLE
AI doesn't move its aircraft from cities that are about to be lost

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#6726]
_1. Mod version (i.e Date - 4/17):_6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

- Subs ignore borders http://www.picknmixmods.com/mods/CivV/Units/Subs Ignore Borders.html
- UI - religion spread (Vox Populi) https://forums.civfanatics.com/threads/ui-religion-spread-vox-populi.627375/
- UI - notify exit resistance http://www.picknmixmods.com/mods/CivV/UI/Notify Exit Resistance.html
- Quick Turns https://steamcommunity.com/sharedfiles/filedetails/?id=220250184
- Promotion flags EUI (for VP) version 3
- UI - wonder planner http://www.picknmixmods.com/mods/CivV/UI/Wonder Planner.html

_3. Error description:_ 

Not sure how difficult would it be to implement, just wanna point out that AI doesn't know how to preserve its aircraft stationed in a city that's definitely gonna be lost the next turn. 

![20200626165923_1](https://user-images.githubusercontent.com/16341598/85866532-37795300-b7d0-11ea-9d54-d2d35eaf4553.jpg)
![20200626170832_1](https://user-images.githubusercontent.com/16341598/85866537-38aa8000-b7d0-11ea-9ddb-736b9def4f2e.jpg)

The bomber in the screenshot didn't even attack in that turn, may be it was healing. The enemy has quite a few cities that have space for rebase.

![20200626171612_1](https://user-images.githubusercontent.com/16341598/85867061-09484300-b7d1-11ea-9093-945a06982f2c.jpg)

**Comment by ilteroi** [comment]
there is definitely code to move them out, but there was an off-by-one error with rebasing.

but they should have been able to go to novgorod at least, it seems to have zero air units.

let's keep an eye on it.
