### ISSUE TITLE
CalculateNetHappiness() performance drag

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6729]
citizen re-allocation is one of the major performance sinks right now, mainly because CalculateNetHappiness() is called lots of times when assigning specialists. is there a way to optimize this?

**Comment by LoneGazebo** [comment]
Not super easily because of needing to re-check needs values etc. with each analysis.

**Comment by ilteroi** [comment]
should be better now because of optimizations in GetBaseYieldRateFromReligion()
