### ISSUE TITLE
Local Building Maintenance/Unhappiness Mods

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#673]
I'm not sure if this request would be possible, but could a LocalUnhappinessModifier and/or a LocalBuildingProductionModifier be possible to add to the Buildings table? Naturally, this would work to reduce unhappiness/maintenance from only the city with the building. Thanks for taking a look regardless.

**Comment by LoneGazebo** [comment]
There's a localhappiness modifier already, is there not? I'll see about it. Also, the windmill does what you want with the latter, no?

**Comment by JFDaly** [comment]
No, there's only an 'UnhappinessModifier' which increases/decreases global unhappiness. And there is no maintenance modifier (global or otherwise); the Windmill increases building production.

**Comment by LoneGazebo** [comment]
Ah gotcha. I misread the request for the building maintenance element. I'll take a look.

**Comment by JFDaly** [comment]
Thank you. And please consider adding a global 'BuildingMaintenanceModifier' if the local one is possible. I didn't actually realize that a global didn't exist for the buildings table until you prompted me (though it exists for the policies table ('BuildingGoldMaintenanceMod'), so the logic is probably similar).

**Comment by LoneGazebo** [comment]
Alright, so the first one (happiness I can work with) - the second one, maintenance, is a bit trickier, as maintenance is not maintained city-by-city, but rather for all buildings as a whole. So no matter what, a modifier to building maintenance will always be global. Is that okay?

**Comment by JFDaly** [comment]
Yup, I understand. Thanks for taking a look. Happiness mod. will do just fine.

**Comment by LoneGazebo** [comment]
I've added the localhappiness mod and the globalbuildingmaintenancemod for buildings. I've also fixed the LUA issue for forcepeace. Should be in next version, though they'll need some testing to guarantee functionality.

**Comment by JFDaly** [comment]
Thanks. I'll test out the two new tags once the update is out.
