### ISSUE TITLE
Useless Options?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6731]
I've decided to do a bit of cleanup (#6632).

To start with, Community Patch > CommunityOptions.sql has options which appear to be obsolete, namely:

COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS
COMMUNITY_CORE_BALANCE_POLICY_TWEAKS
COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS
COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS
COMMUNITY_CORE_BALANCE_SETTLER_MOVE_START

These are all basically AI improvements. At this stage of the mod I don't think anyone is enabling or disabling specific AI intelligence upgrades, and it's certain they don't cover all the changes. These can probably all be removed, unless anyone has a reason for keeping them?

My only real question is regarding the "AI can move their Settlers on Turn 0" change. Is this actually used by anyone for testing, or can it be removed as well? I doubt many (if any) players are setting it so the AI can't move on Turn 0.

The only two options in this file that could be worth keeping IMO are COMMUNITY_CORE_BALANCE_ENGINEER_INSTANT_BUILD, which allows Engineers to instantly build Wonders (sure, why not have an option to use the default behavior) and COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS (ditto).

**Comment by ilteroi** [comment]
i've yet to see an option that is actually exercised. most of them probably break the build when enabled. 

one exception is 43 civs but that is also broken btw because there are 32 bit wide bitfields being used to store flags per player.
