### ISSUE TITLE
6/19 - Ideological Pressure occuring when criteria haven't been met.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6732]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
According to the screenshot, two things have to happen to start feeling Ideological Pressure:

1) A civ has to be popular to you.
2) A civ has to have more influence than you.

In this case, neither is true. No one is popular to me, and I have be and large the most influence. This occured after World Ideology (Autocracy) was obtained (I'm Freedom), so perhaps that has something to do with it.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/85931181-12e0b200-b888-11ea-809c-5f5d86f95b0a.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
World Ideology always inflicts two pressure on you. It's been that way for a long time, and a main reason why AIs going for CV never win.

**Comment by saamohod** [comment]
What doesn't seem fair at the first glance is that you are the civ with the highest tourism output, but the only one who suffers the public opinion penalty, despite all the other civs also have non-Autocracy ideologies and should be having some dissent, too.

**Comment by azum4roll** [comment]
All other Freedom civs are influenced by Egypt to prefer Freedom more. Not sure about Polynesia.

**Comment by Stalker012345** [comment]
So it seems this is just a tooltip problem then, we need to update it to note that World Ideology can also be a factor in generating pressure.

**Comment by Stalker012345** [comment]
@LoneGazebo what was the solution here? Did you all update the tooltip, are consider some changes to the ideology pressure criteria?

**Comment by LoneGazebo** [comment]
I fixed the TT.
