### ISSUE TITLE
Combat Panel Missing Unit Health Modifier for Range Units

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6735]
_1. Mod version (i.e Date - 4/17): 6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Unit A, doesn't display unit health modifier**

![h1](https://user-images.githubusercontent.com/49090452/85946126-ce6a1a80-b94a-11ea-9845-7be55d953244.png)
![h2](https://user-images.githubusercontent.com/49090452/85946128-cf9b4780-b94a-11ea-8c2f-b080feade46f.png)

**Same promotions as Unit A but deals more damage (because of full health)**

![h3](https://user-images.githubusercontent.com/49090452/85946129-d1650b00-b94a-11ea-9553-557dd54dd0b7.png)
![h4](https://user-images.githubusercontent.com/49090452/85946130-d2963800-b94a-11ea-85e1-07d3fe78ae77.png)

**Comment by LoneGazebo** [comment]
Custom EUI or anything?

**Comment by Aqinu** [comment]
Nothing that would change the Combat Panel or EnemyUnitPanel.lua (removed most of the mods and tested it this way and it the same, just to be sure...)
