### ISSUE TITLE
Invisible Caravan

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6737]
_1. Mod version (i.e Date - 4/17): 6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![a](https://user-images.githubusercontent.com/49090452/85946013-31a77d00-b94a-11ea-9be3-5ca01b05ad3e.png)
![b](https://user-images.githubusercontent.com/49090452/85946014-32d8aa00-b94a-11ea-8718-bd7bf7dda485.png)

**Comment by Aqinu** [comment]
**I've just noticed again the invisible caravan**

![a](https://user-images.githubusercontent.com/49090452/85984287-a681c200-b9f1-11ea-8a05-79d440d7aa4c.png)

**Comment by randomnublet** [comment]
Bump as of 10-7-2 version, this is happening often with trade units the AI sends to my cities: often one turn I spot the caravan on its way to my territory from the fog of war, then during the next AI turn it disappears from minimap (but the trade route is still running, giving the correct yields)
