### ISSUE TITLE
Air units randomly can't attack or other actions like sleep

### ISSUE THREAD

**Issue by CppMaster** [LoneGazebo/Community-Patch-DLL#6742]
_1. Mod version (i.e Date - 4/17):_
June 19th (6-19)

_2. Mod list (if using Vox Populi only, leave blank):_

- Promotions Icons for VP
- UI - Promotion Tree for VP
- UI - Filters in Trade Route Overview
- UI - Improved City View
- UI - Religion Spread
- UI -Show XP in Military Overview

_3. Error description:_ 
Air units randomly can't attack or other actions like sleep

_4. Steps to reproduce (optional):_
Try to attack with the Bomber

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4842251/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[AutoSave_0329 AD-1909.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4842254/AutoSave_0329.AD-1909.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![bommer cant attack](https://user-images.githubusercontent.com/8946274/85947698-9bc12180-b94c-11ea-8f79-1632e5a72978.png)

**Comment by ilteroi** [comment]
the was a problem with the air unit capacity, is fixed

**Comment by ilteroi** [comment]
#6725
