### ISSUE TITLE
Cannot increase number of a strategic resource I'm trying to sell above two. 

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#6743]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_
A fair few. I'll append later if needed; at the moment the mod list is inaccessible to me.

_3. Error description:_ 

Hard to describe, so I'll do a play-by-play.

- Civ comes to me wanting to buy 4 horses for 8 GPT and 62 flat.
- I click in the horses edit box, or unclick horses from my side.
- Even though I have 5 horses to sell, nothing I do will allow me to put it above 2 horses. I can adjust it to 2 without issue; adjusting it to 3 or higher sets it back to 1 or 2 depending on what was previously in the edit box.

I tried clearing out my side and asking him what will make this deal work, hoping he would put the 4 horses back. Nada.

I am not selling any horses to anyone else. This is early in this game, and these are the first horses I've even connected. 

I'm fairly sure I've seen this with other resources as well, but I can't say that 100% right now. I'll edit this as more becomes apparent to me.

A gif:

https://i.imgur.com/kALGAuQ.gifv

(Please note that even though the civ in question is a modded civ, I've had this happen with plenty of vanilla civs as well.)

EDIT: Edited title to more accurately reflect the situation; I just tried going back to Nubia once my turn came up, and I still cannot increase the horses above two.
EDIT2: Went back one turn and waited for the deal to appear again. If I don't make any changes, the deal is accepted without apparent issue.

**Comment by Aqinu** [comment]
Same issue as #6619

**Comment by ridjack** [comment]
I'll copy my content and add it to your post; could you please make your title a little more clear?
