### ISSUE TITLE
6/19 - AI refused to go SV even when they had a clear win path

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6744]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4842818/Logs.zip)
[AutoSave_0384 AD-1964.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4842820/AutoSave_0384.AD-1964.zip)

_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This is going to be one of those "fuzzy" strategic issues that I'm providing an example of just to put it on the radar.

So in my latest game, Polynesia was extremely competitive with me. They were top score all game, they always had the most techs and almost always the most policies.

At first it looked like they were going for a CV with large tourism and culture. However, by industrial I had taken the lead in that area. CV was a stalemate, we both had too much culture to overtake the other.

However, the AI had all the tools it needed to go SV. It had aluminum, Order for big production, it had the tech lead, even got to Apollo faster than anyone else. And yet, I don't believe it built a single SS part. I ultimately won by SV, and I truly believe I shouldn't have, the AI had me....and it just gave up and didn't pursue the victory path.

This isn't the first time I've "felt" this, but this was the first time it was so blatant.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/85955472-687a9480-b944-11ea-8e78-d4eab875d458.png)

Attached the save game of the last turn and logs.
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Any logs?

**Comment by Stalker012345** [comment]
They are attached

**Comment by azum4roll** [comment]
Same in last version when Venice was sitting at 82 techs for 50+ turns and refused to build any spaceship parts because he was going for an impossible CV (Dissident due to World Ideology).
