### ISSUE TITLE
Feature Request: More Notifications for Players and Observers

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#6746]
Is it possible to make the following notification popups on the right side (like DoFs) for all players including observers (some are already available to players but not observers):

1. War and Peace Declarations
2. Any city changing hands (captures, rebellions, etc.)
3. Forming Defensive Pacts
4. World Wonder completion
5. Congress results
6. Congress project completion
7. Nuke usage - both user and victim(s) (if all the AIs know someone nuked someone else, it's strange the human doesn't)
8. Vassalage and Liberation

Would be nice if the "Just one more turn" button is made available for observers as well, for screenshot purposes.

**Comment by saamohod** [comment]
I'd love to see 3. and 7. as a player.

**Comment by RecursiveVision** [comment]
I've enabled 1, 2, 4, and 8 for observers for next version.
