### ISSUE TITLE
Missing Open Borders Antiquity Site Info

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6748]
_1. Mod version (i.e Date - 4/17): 6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

Apparently you can only dig in foreign borders only if there is mutual open border, should be specified in Open Borders in Trade Screen.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Here write something like, "Mutual open borders is required to be able to dig Archeology Sites in foreign borders"**
![a](https://user-images.githubusercontent.com/49090452/86029961-84f9f800-ba3c-11ea-8a3a-79aa2ed33cbb.png)

**Comment by LoneGazebo** [comment]
What's weird is that I don't see anywhere in the code that makes it so that you have to have mutual OB to dig. Can anyone else find this code? @ilteroi @RecursiveVision ?

**Comment by RecursiveVision** [comment]
On vacation till mid August - no computer.

**Comment by LoneGazebo** [comment]
@RecursiveVision  @ilteroi do either of you know where the check for mutual OB is located in the DLL? I've scoured it and see no evidence that it should be required, yet it is...

**Comment by RecursiveVision** [comment]
@LoneGazebo Think it might be in UnitPanel.lua and not in the DLL at all...

**Comment by LoneGazebo** [comment]
just checked, don't see it.
