### ISSUE TITLE
AI units not healing?

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#675]
Not sure how common this issue is yet, but it seems that injured AI units are sitting on the same tile for ages, but not healing - this includes even units in cities. Playing v9-27.1 by the way.

See the Russian Scout and Spearman marked by the red arrows in the screenshot. They were sitting there like this for several turns and the health bar was not changing at all.

![no-heal](https://cloud.githubusercontent.com/assets/11929356/10263054/0b101792-69e0-11e5-9a89-b7dfee11f65f.jpg)

**Comment by LoneGazebo** [comment]
Some of this was fixed in the latest version. If it persists, reopen this issue.
