### ISSUE TITLE
City-States disbanding their starting Warriors

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6750]
I noticed this strange behavior recently while testing: It's turn 8, and not a single City-State still has their starting Warrior.

I spawned a ton of Giant Death Robots and advanced myself to a later era using IGE (was testing something with vassalage), not sure if that impacted the disbandment decision in any way (maybe it flagged the units as obsolete?).

But either way, City-States should never disband their starting units if they have nothing else to defend themselves with. I'd argue they shouldn't disband military units at all if possible.

![Screenshot (4470)](https://user-images.githubusercontent.com/66801010/86073793-81716b80-ba52-11ea-8913-6b0427a1c6ad.png)

**Comment by ilteroi** [comment]
cannot confirm.

![image](https://user-images.githubusercontent.com/1358966/86120982-83c8d980-bad5-11ea-9025-fe55c2deebfc.png)

**Comment by RecursiveVision** [comment]
I'll see if I can reproduce.
