### ISSUE TITLE
First turn warriors don't garrison the capital

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6751]
On the first turn, the AI consistently settles their capital and leaves their starting Warriors fortified adjacent to the capital...rather than putting one of them inside the capital. Not a huge issue by any means, but odd.

![Screenshot (4466)](https://user-images.githubusercontent.com/66801010/86073861-ac5bbf80-ba52-11ea-9b47-4964fe9d39e3.png)
![Screenshot (4467)](https://user-images.githubusercontent.com/66801010/86073863-acf45600-ba52-11ea-990e-852b200a3ee4.png)
![Screenshot (4468)](https://user-images.githubusercontent.com/66801010/86073865-ad8cec80-ba52-11ea-9c0f-86a1880911bb.png)

**Comment by ilteroi** [comment]
just an ordering problem since the city does not exist yet at the start of the turn.
