### ISSUE TITLE
Problem with Archeologists and digging sites.

### ISSUE THREAD

**Issue by soeb80** [LoneGazebo/Community-Patch-DLL#6752]
1. Mod version (i.e Date - 4/17):
Latest to date; 6-19
2. Mod list (if using Vox Populi only, leave blank):
CP 6-19 installer (1,2,3,4,5,6a,7a,7b)
+Infoaddict
3. Error description:
Problem with Archeologists and digging sites.
(Playing Morocco). 
1) I noticed several times that when I sent a archeologists to start a excavation. Even though I already started the digging; when a archeologists from another civ shows up on the same tile, it just take over. I have no other choice to leave.

2) I usually try to ‘protect’ or hinder foreign civs from sending there archeologists to dig-sites in my territory, by placing a military unit on that tile. But now it doesn’t matter if I have a archeologists or a military unit occupying the tile; the other civs archeologists just starts digging there anyway.

3) I was in a war with a civ. I sent in a archeologists to a dig-site in his territory; I started the digging. When I then tried to proceeded with the next turn; I ended up needing to give the archeologists orders. I had this problem in my one territory also; it doesn’t matter how many times I give him the order to dig, every time I click next turn his orders are canceled.

**Comment by ilteroi** [comment]
orders are cancelled when the unit is in danger ... as for the rest i don't know what's up. similar issue #6739
