### ISSUE TITLE
Problem with disappearing airplanes / air units

### ISSUE THREAD

**Issue by soeb80** [LoneGazebo/Community-Patch-DLL#6753]
1. Mod version (i.e Date - 4/17):
Latest to date; 6-19

2. Mod list (if using Vox Populi only, leave blank):
CP 6-19 installer (1,2,3,4,5,6a,7a,7b)
+Infoaddict

3. Error description:
Problem with disappearing airplanes (early game air units; bombers and triplanes)! All my air units disappears after a turn; after being rebased to a city with 1 air unit already stationed.

Have seen others with similar problem. I just think this is a major problem an want to highlight it.

**Comment by ilteroi** [comment]
duplicate #6725
