### ISSUE TITLE
AI Archer not always attack units around city (Doesn't assist city it's stationed in)

### ISSUE THREAD

**Issue by Senteliks** [LoneGazebo/Community-Patch-DLL#676]
This is something I noticed in my current game. Apparently, for some reason AI had stationed Archer all the time in city and it had LOS to shoot all my melee units (3 of them ) stationed around city in alert mod. I had Archer, which I had to move out of danger, since both city and enemy archer was bombarding that unit.

 Once, I moved archer I continue with assault. Only city was bombarding my units while Archer was idle to the very end.

Here is another scenario: Archer is attacking all my units but after I heavily damaged city with Archers who had + 1 range promotion and my melee units  Archer stopped assisting city and stood idle until I conquered city.

Look at SS for visual explanation
http://postimg.org/image/wzhoul1jh/

Edit: I had to post direct link because SS in  bmp format which isn't supported by Git and I don't have patients to convert it to jpeg.

**Comment by LoneGazebo** [comment]
I'll page ilteroi, this is his domain.

**Comment by ilteroi** [comment]
will check

**Comment by ilteroi** [comment]
should be better now
