### ISSUE TITLE
Community Patch Run Time Error

### ISSUE THREAD

**Issue by myles1718** [LoneGazebo/Community-Patch-DLL#6760]
_1. Mod version (i.e Date - 4/17):_
6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_
VP 1-7a AG Late Game Mod, IGE, Real Advance Set Up

_3. Error description:_ 
When using all above mods am getting run time error in lua
IGE is not showing up or avilable in game
NOT using AG Late Game Mod. There is no Run Time Error and IGE IS avilable in game

_4. Steps to reproduce (optional):_
Have reinstalled game, cleared cache and mod data user but no change to problem

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.
[Lua1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4856461/Lua1.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4856464/Lua.zip)
[Database1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4856465/Database1.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4856467/Database.zip)

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by myles1718** [comment]
Any one going to answer this problem PLEASE

**Comment by myles1718** [comment]
PLEASE

**Comment by RecursiveVision** [comment]
@myles1718 We don't usually debug other people's mods, sorry.
