### ISSUE TITLE
AI never (re-)capture barbarian settlers

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#6761]
6-19-2 mod.

![image](https://user-images.githubusercontent.com/14953746/86249115-68e38b80-bbe1-11ea-92d1-db637d8a7cee.png)

The settler has been there for ~20 turns now. It seems AIs are prohibited from going into that tile or something.

**Comment by ilteroi** [comment]
cannot reproduce. must be some special condition or i fixed it in the meantime ...
