### ISSUE TITLE
Terrible promotion selection AI?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6762]
Feedback on the forums is that the AI is terrible at selecting and using unit promotions like Range, Logistics, City Assault etc.

What manages this AI? Is it unmodifiable because it's outside of the GameCoreDLL or something? Otherwise, I'm surprised it isn't fixed by now.

**Comment by LoneGazebo** [comment]
the ai_promote function is what you're looking for. It's...a mess, always has been. I've tried wrangling it in, but it is largely built around the flavors system.

**Comment by RecursiveVision** [comment]
I see, that is indeed pretty terrible.

My first thought on how to improve it would be to have the AI assign all of its units a "promotion strategy plan" or something like that (consider flavors here), and choose promotions accordingly based on value (don't consider flavors here).

For instance, if the AI needs city siege melee units, good promotion choices include Drill, Cover and City Assault.

**Comment by Mileslewis** [comment]
Was there any attempt to change this?

**Comment by Mileslewis** [comment]
Tbh I think I could do an okay job of at least improving it without overhauling it (though I may need some questions answered along the way).

However I also think Recursive's idea would be much easier and would probably give better results and be easier to modify later.

The main problem I could see would be conflicts with any modmods which add extra promotions to the available selections which would now be ignored.

**Comment by RecursiveVision** [comment]
Well it wouldn't be searching for "PROMOTION_DRILL", it'd be searching for "combat bonus VS cities".

**Comment by Mileslewis** [comment]
Okay, so you're saying give each AI unit a promotion plan such as siege melee and then make it value the promotions which give that very highly for the rest of the game?

I wouldn't know how to set that up so that the plan was accessible each time you were on that unit. But I could definitely do the the choosing of a plan and choosing of promotions within a plan. 

Also there are calls to AI_getUnitAIType() lower down in the AI_promotionValue function. Are these unit types perhaps similar to what you are mentioning where the AI has given a role to each unit? I can't find how these unit types are determined.

**Comment by RecursiveVision** [comment]
@Mileslewis That's my idea. I'm not saying it has to be done that way, but I think it's a good mixture of solutions.

It allows for flavors to be considered in a more meaningful way (right now it feels like a random lottery more than anything, but it makes sense for AIs that have a higher flavor for mounted units to build more mounted units, and to assign roles accordingly).

But in terms of the turn-by-turn promotion decisions, it would guarantee that the AI is making choices that are actually valuable to it. A promotion plan could outline the boundaries of what promotions are acceptable choices, and the decision could also consider, e.g. the unit's danger level, current position and surrounding terrain as circumstances to modify the weights. That's my ideal solution.

In terms of setting it up, it would require an enum for each promotion plan, and storing a memory value for each unit corresponding to that enum.

**Comment by RecursiveVision** [comment]
```
//	--------------------------------------------------------------------------------
UnitAITypes CvUnit::AI_getUnitAIType() const
{
	VALIDATE_OBJECT
	return m_eUnitAIType;
}

//	--------------------------------------------------------------------------------
void CvUnit::AI_setUnitAIType(UnitAITypes eNewValue)
{
	VALIDATE_OBJECT
	CvAssertMsg(eNewValue != NO_UNITAI, "NewValue is not assigned a valid value");

	if(AI_getUnitAIType() != eNewValue)
	{
		m_eUnitAIType = eNewValue;
	}
}
```

So it's a memory value stored at the unit level. To understand how it works, you'd have to look at the calls to AI_getUnitAIType and AI_setUnitAIType.

**Comment by RecursiveVision** [comment]
```
enum UnitAITypes			
{
	NO_UNITAI = -1,

	UNITAI_UNKNOWN,					// we don't know what to do with these units
	UNITAI_SETTLE,					// these are Settlers
	UNITAI_WORKER,					// these are Builders
	UNITAI_ATTACK,					// use these to attack other units
	UNITAI_CITY_BOMBARD,			// use these to attack cities
	UNITAI_FAST_ATTACK,				// use these to pillage enemy improvements and attack barbarians
	UNITAI_DEFENSE,					// these are units that are mainly in the floating defense force
	UNITAI_COUNTER,					// these are counter-units to specific other units - these will likely need more logic in building and using
	UNITAI_RANGED,					// units with ranged attacks
	UNITAI_CITY_SPECIAL,			// siege support
	UNITAI_EXPLORE,					// scouts, etc.
	UNITAI_ARTIST,					// great person
	UNITAI_SCIENTIST,				// great person
	UNITAI_GENERAL,					// great person
	UNITAI_MERCHANT,				// great person
	UNITAI_ENGINEER,				// great person
	UNITAI_ICBM,					// nuke
	UNITAI_WORKER_SEA,				// work boats
	UNITAI_ATTACK_SEA,				// naval melee units
	UNITAI_RESERVE_SEA,				// naval units used defensively
	UNITAI_ESCORT_SEA,				// naval units tasked to defend embarked units
	UNITAI_EXPLORE_SEA,				// naval units used for scouting
	UNITAI_ASSAULT_SEA,				// naval ranged units
	UNITAI_SETTLER_SEA,				// UNUSED in Civ 5
	UNITAI_CARRIER_SEA,				// aircraft carrier
	UNITAI_MISSILE_CARRIER_SEA,		// missile carrier - UNUSED
	UNITAI_PIRATE_SEA,				// avast, ye - UNUSED
	UNITAI_ATTACK_AIR,				// bombers
	UNITAI_DEFENSE_AIR,				// fighters
	UNITAI_CARRIER_AIR,				// planes on boats - UNUSED
	UNITAI_MISSILE_AIR,				// cruise missiles
	UNITAI_PARADROP,				// paratrooper
	UNITAI_SPACESHIP_PART,			// spaceship part that needs to be taken to capital
	UNITAI_TREASURE,				// treasure to return to your capital
	UNITAI_PROPHET,					// great person
	UNITAI_MISSIONARY,				// missionary
	UNITAI_INQUISITOR,				// inquisitor
	UNITAI_ADMIRAL,					// admiral
	UNITAI_TRADE_UNIT,				// international trade unit
	UNITAI_ARCHAEOLOGIST,			// archaeologist
	UNITAI_WRITER,					// great person
	UNITAI_MUSICIAN,				// great person
#if defined(MOD_DIPLOMACY_CITYSTATES)
	UNITAI_DIPLOMAT,
	UNITAI_MESSENGER,
#endif

	NUM_UNITAI_TYPES
};
```

Ah, here we go, from CvEnums.h ^

**Comment by RecursiveVision** [comment]
Each unit has a default Unit AI Type in SQL/XML. From what I can tell the default type is used unless there's a reason to switch it to something else. For instance UNITAI_EXPLORE can be switched to UNITAI_DEFENSE if there's a critical military threat.

**Comment by RecursiveVision** [comment]
Perhaps UnitAITypes could be modified rather than adding an entirely new value, although they're probably used a lot in military and tactical AI.

**Comment by Mileslewis** [comment]
Well it would be good to have the promotion path synced up with how the AI would use a unit. I think it depends on how the UnitAITypes are assigned. Like can two knights be assigned different roles when created and how often would units be switched.

**Comment by Mileslewis** [comment]
`for (int iJ = 0; iJ < GC.getNumPromotionInfos(); iJ++)
			{
				const PromotionTypes eNextPromotion(static_cast<PromotionTypes>(iJ));
				CvPromotionEntry* pkNextPromotionEntry = GC.getPromotionInfo(eNextPromotion);
				if (!pkNextPromotionEntry)
					continue;

				//for some basic forward planning, look at promotions this promotion unlocks and add those to the value.
				if (   pkNextPromotionEntry->GetPrereqOrPromotion1() == ePromotion
					|| pkNextPromotionEntry->GetPrereqOrPromotion2() == ePromotion
					|| pkNextPromotionEntry->GetPrereqOrPromotion3() == ePromotion
					|| pkNextPromotionEntry->GetPrereqOrPromotion4() == ePromotion
					|| pkNextPromotionEntry->GetPrereqOrPromotion5() == ePromotion
					|| pkNextPromotionEntry->GetPrereqOrPromotion6() == ePromotion
					|| pkNextPromotionEntry->GetPrereqOrPromotion7() == ePromotion
					|| pkNextPromotionEntry->GetPrereqOrPromotion8() == ePromotion
					|| pkNextPromotionEntry->GetPrereqOrPromotion9() == ePromotion)
				{
					iValue += AI_promotionValue(eNextPromotion) / 2;
				}

			}`

I also think this could be quite promising for getting promotions to go down a path without even needing a set plan. If we assigned higher values to things like logistics maybe AIs would just get towards them more often anyways. 

This code does seem quite dubious though like is there no function which could just directly get us which promotions are unlocked by ePromotion? That would allow us to go more promotions deep if necessary as well.

**Comment by LoneGazebo** [comment]
That code above exists because Firaxis hardcoded prereqs within the main table instead of making a secondary prereq table (like they did for everything else). It's madness. In any case, there are hundreds of promotions, you're looking at tons of redundancy if you try to create 'paths' for the AI - your best bet is to take what we have, and add modifiers to the existing modifiers/value metrics to try and steer the AI towards specific promotion types. I tried to 'reinvent' this wheel awhile back, and it is extremely difficult because of the knock on considerations and sheer quantity of variables.

**Comment by Mileslewis** [comment]
Okay yea I was leaning towards just doing that also. Do you know if what I pasted in works for finding promotions which lead on from others 100% of the time? Also would putting in a second 'layer' with eNextPromotion replacing ePromotion and eNextNextPromotion replacing eNextPromotion work?

**Comment by LoneGazebo** [comment]
It gets expensive and slow if you go beyond the first 'step' of recursive checks, since it gets the value of each and every one of these promotions. If you really want to steer an AI towards specific capstones, you could add a new, non-serialized column to the promotiontable called 'CapstonePromotion' or something so that, for example, Drill I would have a capstone of Drill IV or Barrage I would have a capstone of Logistics.  So that the AI would know what the 'top tier' promotions are for each tree. Does that make sense?

G

**Comment by Mileslewis** [comment]
Makes sense but I think I will try without that first. Do you think this UnitAIType() would be suitable for use in calculating the value of more promotions or not really?

**Comment by Mileslewis** [comment]
Okay here is what I have done so far:
[AI promotions edited.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/4905964/AI.promotions.edited.txt)

**Comment by Mileslewis** [comment]
I commented in which unit types can choose a promotion which has each benefit to make it easier to see what you are affecting when you change values.

Then I went through and changed some of the values that were being added from each benefit. Here is one example:

	iTemp = pkPromotionInfo->GetOpenAttackPercent();
	// mM: +10 Charge 1,2;
	if(iTemp != 0)
	{
		iExtra = getExtraOpenAttackPercent();
		iValue += (iTemp + iExtra) * (iFlavorOffense + iFlavorDefense + iFlavorMobile);
		iValue /= 4
		if(noDefensiveBonus())
		{
			iValue *= 2;
		}
	}

The usual formula I used was:
iTemp is the percentage increase from the benefit.
iExtra is current percentage bonus the unit has from synergistic promotions (sometimes from having some of the same benefit already.
iTemp + iExtra * 3 Flavors which I thought were most appropriate (Sometimes the same flavor 3 times)
Then multiply or divide (usually divide) to get the relative strength of the promotion benefit. So for example open attack bonus I divided by 4 as it only affects attacks on roughly half the terrain.
Then multiply by added benefits/negatives like open attack is multiplied by 2 for mounted/armor units and some benefits are multiplied by number of attacks a unit has.

**Comment by Mileslewis** [comment]
Also I added in CITY_DEFENSE and NAVAL_RECON Flavors.

And changed this formula:

			if (pkPromotionEntry->GetPrereqOrPromotion1() == NO_PROMOTION)
			{
				if (iLevel >= 3)
				{
					iValue = iValue * (iLevel - 2);
					iValue /= iLevel;
					// At level 3 has 1/3 chance of picking base promotion again, chance increases back towards 1 as leveled further.
				}
			}

Which should mean it's very unlikely to ever pick a base promotion again until later on when a unit has many promotions already.

Okay I really need to go back and add in semi colons lol but do you guys think this seems on the right track?

**Comment by ilteroi** [comment]
can you create a pull request? this is github, no need for text files ...

**Comment by Mileslewis** [comment]
Okay, does it need to be finished before I do that? Because there are some things I am unsure about.

**Comment by ilteroi** [comment]
no worries, you can always update your branch if anything is wrong

**Comment by Mileslewis** [comment]
Okay #6815

**Comment by Mileslewis** [comment]
Alright I'm mega noob at using GitHub but I think it's done #6816

**Comment by JamesNinelives** [comment]
Thanks for the work everyone, I think the community will really appreciate this :).
