### ISSUE TITLE
warmonger penalty after joint war

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6764]
so assyria asked me for a joint war on austria. i obliged. now i'm about to conquer an austrian city and i see that assyria will be upset with me if i conquer it. intended?

**Comment by RecursiveVision** [comment]
Not intended. I'll fix soon, I'm doing a full revision of many diplo AI things.

**Comment by LoneGazebo** [comment]
Not entirely true @RecursiveVision, it is intended that the AI is upset if a player conquers something, even if they're in a joint war. There is a sizable reduction in the penalty, however.

G

**Comment by RecursiveVision** [comment]
The code checking that is commented out.

**Comment by LoneGazebo** [comment]
Weird

**Comment by RecursiveVision** [comment]
Working on fixing.
