### ISSUE TITLE
Austrian Coffee House Problems

### ISSUE THREAD

**Issue by lifeordeath2077** [LoneGazebo/Community-Patch-DLL#6767]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Austrian Coffee House increases the yields of bananas, tobacco, tea, and coffee like the grocer used to do, however that feature was moved from the grocer to the customs house.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Alpakinator** [comment]
It's partially true. Coffee House improves only bananas by +2 gold. Tobacco ,coffee and tea are unaffected. However it still has old description saying that it improves all of them. Hope they'll remove those extra bananas yields and fix the description.
