### ISSUE TITLE
Indian Naga-Malla Problems

### ISSUE THREAD

**Issue by lifeordeath2077** [LoneGazebo/Community-Patch-DLL#6768]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Indian Naga-Malla Obsoletes at Combustion. Following how other uniques obsolete, it should obsolete at Ballistics as it is a Curaissier replacement

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@lifeordeath2077 You can just open one issue if they're all on the same topic. :)

**Comment by RecursiveVision** [comment]
While trying to figure this one out:
```
CIV5_ANTIQUITY_INDIANWARELEPHANT
INDIAN_WAR_ELEPHANT
INDIAN_WARELEPHANT_
```

Thanks for being consistent, Firaxis. 🙄
