### ISSUE TITLE
Consitent CTD on AI Turn

### ISSUE THREAD

**Issue by Soranya** [LoneGazebo/Community-Patch-DLL#677]
I am getting a consitent CTD on this savefile. I recieve a warning about a Plot against me, the AI processing continues for a few seconds and then crash.

Only Mods i am using are hte ones from the Community Patch with the EUI. (Latest version)

The attched files are zip files (had to change extension to upload them here) with the logs and the save file

![autosave_post_0247 ad-1020](https://cloud.githubusercontent.com/assets/14956353/10264505/bc13870e-6a0d-11e5-8373-f6f959107014.jpg)
![logs](https://cloud.githubusercontent.com/assets/14956353/10264509/d7749b78-6a0d-11e5-83e2-55d2d3cd72c1.jpg)

**Comment by Ordinaryperson2** [comment]
I'm also getting a consistent crash that matches this. Just click next turn on this save file, deny the offer to buy Shanghai and crash.
Here's a zip with the minidump, save file and logs.
I'm using the Multiplayer Compatible CPProject Full EUI 10/2 provided by Lynnes with no other mods and no changed mod settings. (It is a singleplayer game though).
(like Soranya, I renamed it to jpg to upload. If you need I can upload it on mega or etc. as a normal zip.)
![combal crash](https://cloud.githubusercontent.com/assets/14125694/10278023/b0a5efa2-6ba1-11e5-8917-598ff69bd1e0.jpg)

**Comment by LoneGazebo** [comment]
Your zipped files aren't showing up. Really, what is needed is your minidump file, in your base civ install (where the .exe is located).

**Comment by Ordinaryperson2** [comment]
Here's the same .zip
https://mega.nz/#!PkBAQaTT!4GZ84hYyRd8stsVeld8VrJTKexsWn0rC061hMfPfVj8

**Comment by Soranya** [comment]
I allready posted my minidumb file on the forums in the Bugreport Thread.

**Comment by Iamblichos** [comment]
I posted a mini dump file for the same issue in the forum.
