### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by paramenides** [LoneGazebo/Community-Patch-DLL#6771]
_1. Mod version (i.e Date - 4/17):_

6-19-2
_2. Mod list (if using Vox Populi only, leave blank):_

faster airplanes v2
_3. Error description:_ 

Crash to desktop
_4. Steps to reproduce (optional):_

Just run the save file
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4866125/Logs.zip)
[AutoSave_0220 AD-0700.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4866128/AutoSave_0220.AD-0700.zip)
This is I think two turns before crash at AD 0730
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4866144/CvMiniDump.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by adaneslavo** [comment]
I also have repeatable crash on 6-19-2 with bunch of standard mods used earlier:
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4886765/CvMiniDump.zip)
