### ISSUE TITLE
Odd barbarian camp behavior

### ISSUE THREAD

**Issue by crdvis16** [LoneGazebo/Community-Patch-DLL#6772]
_1. Mod version (i.e Date - 4/17):_
June 2020 version

_2. Mod list (if using Vox Populi only, leave blank):_
just VP

_3. Error description:_ 
I'm seeing odd behavior from the AI military units near barbarian camps.  I got a quest from a CS to take out a camp so moved 2 archers to it.  By the time I got there Arabia already had 2 warriors adjacent to the camp so I figured my two archers were out of luck.  However, the 2 warriors just sat there.  After a turn I decided to at least attack the camp.  After I began attacking it the 2 warriors also attacked and got it low.  I shot again with my archers and cleared the barbarian from it (figured I would at least get the EXP) and assumed the warriors would then enter the camp for the clear (and quest!).  Instead, they left the area and let me clear it instead.

It seemed weird that they weren't attacking the camp initially and it was especially weird that they didn't enter the camp to clear it once it was empty.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Might be related to #6761 ?

**Comment by crdvis16** [comment]
See attached save. Kill the barbarian in the camp near Arabia with the 2
archers.  Arabia's warrior will retreat away rather than clear the now
empty camp.

**Comment by ilteroi** [comment]
should be fixed
