### ISSUE TITLE
Bug with food supply on a conquered capital

### ISSUE THREAD

**Issue by LGS34** [LoneGazebo/Community-Patch-DLL#6774]
_1. Mod version (i.e Date - 4/17):_
7-29-1 (from 2019)

_2. Mod list (if using Vox Populi only, leave blank):_
Calypso's Colored Religious Icons (basic & extended)
National Wonder Collection
Sukritact's Events & Decisions

_3. Error description:_ 
The food supply on a conquered capital is badly calculated, so that it is starving even though there is plenty of food after resistence. This is quite weird since it sometimes happens and sometimes not (that bug also happened in another save that I cannot have anymore, but didn't in yet another save).
I don't know if such a bug has already been reported and/or corrected (I tried to search, but didn't find anything, and the save just doesn't work with more recent versions), so sorry if so.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Indonesia PS MOD bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4872926/Indonesia.PS.MOD.bug.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20200704114400_1](https://user-images.githubusercontent.com/67824303/86513624-07ebcb80-be0c-11ea-9fcf-6bde4a9a29d1.jpg)

**Comment by RecursiveVision** [comment]
Debugging old versions from a year ago would be too much work for us, sorry, especially when the issue was likely fixed in the meantime.

**Comment by LGS34** [comment]
Yeah I understand, no problem. I still wanted to let you know in the case it might have not been fixed. Anyway I started other games with a more recent version, I'll let you know if I still find this problem. Thank you anyway for the work you've been doing ;)
