### ISSUE TITLE
performance question

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6775]
there are two functions which are called very frequently during citizens reassignment and seem to be inefficient.

- CvCity::getBaseYieldRateModifier() calls pCityPlot->getUnitByIndex(iUnitLoop)->GetYieldModifier(eIndex);
- CvCity::getBaseYieldRate() calls pCityPlot->getUnitByIndex(iUnitLoop)->GetYieldChange(eIndex);

the unit lookup is relatively expensive, and the result is always zero afaik.

so is it safe to remove that check? if necessary we can make it a compile time option on the off chance that somebody makes a mod which uses those yield modifiers.

**Comment by LoneGazebo** [comment]
I think that’s fair yeah.
