### ISSUE TITLE
pantheon choice

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6777]
this is persia, with 7 sea resources:

![image](https://user-images.githubusercontent.com/1358966/86540876-77df7c00-bf08-11ea-84d0-cbb2c3e92a95.png)

and this is their pantheon choice:

037, -2520, Persia, Belief, Tutelary Gods, 669
037, -2520, Persia, Belief, God of the Sea, 412
037, -2520, Persia, Belief, God of Commerce, 294
037, -2520, Persia, Belief, Goddess of Protection, 264
037, -2520, Persia, Belief, God of Craftsmen, 174
037, -2520, Persia, Belief, God of War, 149
037, -2520, Persia, Belief, Goddess of Festivals, 144
037, -2520, Persia, Belief, God of the Sun, 120
037, -2520, Persia, Belief, Goddess of Wisdom, 114
037, -2520, Persia, Belief, Goddess of Beauty, 108
037, -2520, Persia, Belief, Earth Mother, 96
037, -2520, Persia, Belief, God of All Creation, 88
037, -2520, Persia, Belief, Goddess of Nature, 72
037, -2520, Persia, Belief, Goddess of Springtime, 72
037, -2520, Persia, Belief, God-King, 24
037, -2520, Persia, Belief, Goddess of the Hunt, 0
037, -2520, Persia, Belief, Goddess of Purity, 0
037, -2520, Persia, Belief, Spirit of the Desert, 0
037, -2520, Persia, Belief, God of the Stars and Sky, 0
037, -2520, Persia, CHOSEN, God of Commerce

so god of the sea actually was the runner-up ... but tutelary gods seems to be overrated?

**Comment by RecursiveVision** [comment]
Should belief choice even be randomized? Unlike Social Policies they're a one-shot deal, so I think the AI should always take the "optimal" belief.

**Comment by azum4roll** [comment]
I have a feeling the AIs might never pick the terrain-based pantheons if they always pick the highest score one.

**Comment by RecursiveVision** [comment]
@azum4roll If that's the case then the pantheon scoring logic would be in need of improvement. Note also that pantheons are first come first serve, so even if that's the case the AI would end up choosing the terrain dependent ones sometimes, based on the scoring here.

**Comment by LoneGazebo** [comment]
It’s not randomizes in selection, but a random amount (n= 1->belief value) is added to score to help with diversity

**Comment by JamesNinelives** [comment]
I do see the AI picking terrain-dependant pantheons in my games (12 civs) although the AI does seem to like Expanse, Home, and Ancestor Worship more than the others, generally speaking.

Tutelary Gods gets picked more often that I would expect, being a low-faith pantheon but then the AI doesn't have as much trouble founding so maybe that makes sense for them.

I'm not complaining though, as those as I like the terrain-related pantheons myself.

**Comment by LoneGazebo** [comment]
I'll bump valuation for terrain dependent pantheons.
