### ISSUE TITLE
How to retrieve a player's base XML flavor value?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6778]
I'm looking at the flavor manager code but it's just confusing me.

What I'm trying to do is add the following function:
```
int CvDiplomacyAI::GetEstimateOtherPlayerFlavorValue(PlayerTypes eOtherPlayer, FlavorTypes eFlavor) const
{
	if ((int)eOtherPlayer < 0 || (int)eOtherPlayer >= MAX_MAJOR_CIVS) return 0;
	if ((int)eFlavor < 0 || (int)eFlavor >= GC.getNumFlavorTypes()) return 0;

	// Human or Random Personalities? Assume the default flavor value.
	if (GET_PLAYER(eOtherPlayer).isHuman() || GC.getGame().isOption(GAMEOPTION_RANDOM_PERSONALITIES))
	{
		return /*5*/ GetDefaultFlavorValue();
	}

	// AI? Use the other player's base XML value.
	int iRtnValue = 0;

	??? What goes here ???

	return iRtnValue;
}
```

Any tips on how to retrieve the base (non-adjusted) XML value?

Also for some reason the diplomacy flavor values are separate from other XML values, so it seems I'll need to write a new function for each of those.

**Comment by LoneGazebo** [comment]
Pretty sure you're looking for: 

m_pPlayer->GetFlavorManager()->GetPersonalityIndividualFlavor(eFlavor)

**Comment by RecursiveVision** [comment]
So GetIndividualFlavor returns the adjusted value and GetPersonalityIndividualFlavor returns the base value?

**Comment by RecursiveVision** [comment]
/// Make a random adjustment to each flavor value for this leader so they don't play exactly the same
void CvFlavorManager::RandomizeWeights()
{
	int iMin = /*0*/ GC.getPERSONALITY_FLAVOR_MIN_VALUE();
	int iMax = /*20*/ GC.getPERSONALITY_FLAVOR_MAX_VALUE();
	int iPlusMinus = /*2*/ GC.getFLAVOR_RANDOMIZATION_RANGE();

	for(int iI = 0; iI < GC.getNumFlavorTypes(); iI++)
	{
		// Don't modify it if it's zero-ed out in the XML
		if(m_piPersonalityFlavor[iI] != 0)
		{
			m_piPersonalityFlavor[iI] = GetAdjustedValue(m_piPersonalityFlavor[iI], iPlusMinus, iMin, iMax);
		}
	}
}

It seems that the randomization happens to PersonalityIndividualFlavor.

**Comment by RecursiveVision** [comment]
Okay, I think I've found it:
```
			// Copy over leaderhead defaults unless human
			if(!pPlayer->isHuman())
			{
				LeaderHeadTypes type = pPlayer->getPersonalityType();
				if(type != NO_LEADER)
				{
					CvLeaderHeadInfo* pkLeaderHeadInfo = GC.getLeaderHeadInfo(type);
					if(pkLeaderHeadInfo)
					{
						int iDefaultFlavorValue = GC.getDEFAULT_FLAVOR_VALUE();
						int iNumFlavorTypes = GC.getNumFlavorTypes();

						for(int iI = 0; iI < iNumFlavorTypes; iI++)
						{
							// Majors use Leader XML Flavors
							if(!pPlayer->isMinorCiv())
							{
								m_piPersonalityFlavor[iI] = pkLeaderHeadInfo->getFlavorValue(iI);
							}
```

**Comment by RecursiveVision** [comment]
So final function will be:
```
int CvDiplomacyAI::GetEstimateOtherPlayerFlavorValue(PlayerTypes eOtherPlayer, FlavorTypes eFlavor) const
{
	if ((int)eOtherPlayer < 0 || (int)eOtherPlayer >= MAX_MAJOR_CIVS) return 0;
	if ((int)eFlavor < 0 || (int)eFlavor >= GC.getNumFlavorTypes()) return 0;

	// Human or Random Personalities? Assume the default flavor value.
	if (GET_PLAYER(eOtherPlayer).isHuman() || GC.getGame().isOption(GAMEOPTION_RANDOM_PERSONALITIES))
	{
		return /*5*/ GC.getGame().GetDefaultFlavorValue();
	}

	// AI? Use the other player's base XML value.
	int iRtnValue = /*5*/ GC.getGame().GetDefaultFlavorValue();

	LeaderHeadTypes leader = pPlayer->getPersonalityType();
	if (leader != NO_LEADER)
	{
		CvLeaderHeadInfo* pkLeaderHeadInfo = GC.getLeaderHeadInfo(leader);
		if (pkLeaderHeadInfo)
		{
			iRtnValue = pkLeaderHeadInfo->getFlavorValue(eFlavor);
		}
	}

	return iRtnValue;
}
```

@LoneGazebo Would this function?

**Comment by RecursiveVision** [comment]
Yeah, it's copied and pasted, I'll test it but it should work.
