### ISSUE TITLE
No combat classes for some units.

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6779]
I wanted to make promotion which is applied to all land units. Unfortunately some of them like Great People, Archaeologists, Assyrian Siege Tower (why it is not UNITCOMBAT_SIEGE?) or Space Ship Parts have no such value, which means I cannot add them into UnitPromotions_UnitCombats table.

Can you add such values to make it possible?

**Comment by Tekamthi** [comment]
i suspect some features are mutually exclusive from others, like unitcombats and special cargo units maybe?

my guesswork aside, some clever SQL selecting for the unit's domain and placing in freepromotions should accomplish what you're after, assuming you want these promos applied automatically?  UnitPromotions_UnitCombats just makes the corresponding units eligible for the promotion, and doesn't "apply" it to all units immediately.  If you're trying to apply it via some building or other gated trigger, like GL wonder does for naval, then you'll probably have to use lua i think.

**Comment by adaneslavo** [comment]
Promotion is planned to be given by the wonder, so unit combat class is enough. There are only few units missing in that column, so it is probably a moment for VP guys to fill the gap.

For now I just gave it to those units which have such value.

**Comment by LoneGazebo** [comment]
Combat classes can't just be assigned to units that aren't technically combat units.

**Comment by adaneslavo** [comment]
You're not right.
![obraz](https://user-images.githubusercontent.com/33016300/89736528-5410d800-da6a-11ea-9812-89bb28e5d1f7.png)
Missionaries, diplomatic units, settlers, cargo, workboats are not combat units and have their corresponding unitcombattypes...

**Comment by LoneGazebo** [comment]
Apologies I got my wires crossed, I was thinking about combat animation subgroups. Mea Culpa.

**Comment by adaneslavo** [comment]
I made temporary lua solution:
```
--============================================--
-- VP FIXES
--============================================--
-- additional combat classes for pormotions
INSERT INTO Language_en_US 
			(Tag,										Text) 
VALUES		('TXT_KEY_UNITCOMBAT_SPECIAL_PEOPLE',		'Great People'),
			('TXT_KEY_UNITCOMBAT_SPACESHIP_PARTS',		'Space Parts'),
			('TXT_KEY_UNITCOMBAT_MISSILE',				'Missiles'),
			('TXT_KEY_UNITCOMBAT_ARCHAEOLOGIST',		'Archaeologists');

INSERT INTO UnitCombatInfos 
			(Type,							Description) 
VALUES		('UNITCOMBAT_SPECIAL_PEOPLE',	'TXT_KEY_UNITCOMBAT_SPECIAL_PEOPLE'),
			('UNITCOMBAT_SPACESHIP_PARTS',	'TXT_KEY_UNITCOMBAT_SPACESHIP_PARTS'),
			('UNITCOMBAT_MISSILE',			'TXT_KEY_UNITCOMBAT_MISSILE'),
			('UNITCOMBAT_ARCHAEOLOGIST',	'TXT_KEY_UNITCOMBAT_ARCHAEOLOGIST');

UPDATE Units SET CombatClass = 'UNITCOMBAT_ARCHAEOLOGIST'	WHERE Type ='UNIT_ARCHAEOLOGIST';
UPDATE Units SET CombatClass = 'UNITCOMBAT_SIEGE'			WHERE Type ='UNIT_ASSYRIAN_SIEGE_TOWER';
UPDATE Units SET CombatClass = 'UNITCOMBAT_SPECIAL_PEOPLE'	WHERE Special ='SPECIALUNIT_PEOPLE';
UPDATE Units SET CombatClass = 'UNITCOMBAT_MISSILE'			WHERE Special ='SPECIALUNIT_MISSILE';
UPDATE Units SET CombatClass = 'UNITCOMBAT_MISSILE'			WHERE Type ='UNIT_ATOMIC_BOMB';
UPDATE Units SET CombatClass = 'UNITCOMBAT_SPACESHIP_PARTS' WHERE DefaultUnitAI ='UNITAI_SPACESHIP_PART';
```

**Comment by adaneslavo** [comment]
It was still not added to the VP, as I can see. Have you abandoded this topic for good?

**Comment by RecursiveVision** [comment]
@LoneGazebo

**Comment by LoneGazebo** [comment]
>I made temporary lua solution:
I assumed this was your fix.

**Comment by adaneslavo** [comment]
In one of my mods :P I didn't add anything to VP.
