### ISSUE TITLE
Where is the Settler?

### ISSUE THREAD

**Issue by minipuerto** [LoneGazebo/Community-Patch-DLL#678]
Hi!

Playing as Rome, I chose liberty and then the free settler, but I didn't became any,...
Any Idea? The rest works fine...

Regards!

**Comment by Radost** [comment]
There is no settler, nor liberty anymore.

**Comment by minipuerto** [comment]
ok,....I cleared cache and followed the instructions....is this why I today became a settler when going honor? I dont understand,... :S

**Comment by Radost** [comment]
There is no honor either.

**Comment by Edaka** [comment]
All is right - liberty doesn't have  a free settler now and honor does. 

Do you play in a different language than English? If so, you may not be seeing the changes made in the mod. In that case I suggest to check out this thread:
http://forums.civfanatics.com/showthread.php?t=539883

There you'll find the information on how to play with CBP in whatever language you please. If this seems too complicated, you can change the game language to English, although that will require a reinstall.

**Comment by minipuerto** [comment]
ouch, it may be that then,....
Thank you for your quick support!! :)
