### ISSUE TITLE
06-19-2 Quick Speed CTD on Turn 10, Turn 5

### ISSUE THREAD

**Issue by ghost** [LoneGazebo/Community-Patch-DLL#6780]
_1. Mod version (i.e Date - 4/17):_
6-19-2
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Medium map, quick speed, CTD on turn 10. I have tried other civs & and map scripts on quick speed and they all seem to crash between turns 2 and 10 on AI turn. Maybe this is related to recent game speed related modifier change since on epic speed this does not seem to be a problem?
[Quick Speed CTD bug report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4880974/Quick.Speed.CTD.bug.report.zip)

_4. Steps to reproduce (optional):_
Load the turn 10 save file, press Next Turn button

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by jayeye2011** [comment]
I did not have logging enabled for initial bug report files, so I enabled logging and loaded initial turn 00 autosave and this time got a crash on turn 5. data attached.
[6-19-2 Quick Speed CTD turn 5+logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4881076/6-19-2.Quick.Speed.CTD.turn.5%2Blogs.zip)

**Comment by ilteroi** [comment]
@LoneGazebo : can you check this? only you have the PDB for 6-19-2 ... take the minidump, follow the steps in #6459 and this should be easy
