### ISSUE TITLE
archaeologists, when startled, refuse to keep working

### ISSUE THREAD

**Issue by paramenides** [LoneGazebo/Community-Patch-DLL#6782]
_1. Mod version (i.e Date - 4/17):_
6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

faster airplanes
_3. Error description:_ 

When an players archaeologist is working on a dig site, and an enemy comes within sight, the archaeologist will refuse to get  back to work.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
I think it is intended, see #6739

**Comment by azum4roll** [comment]
I don't think it worked that way before... You could continue digging after he stopped working (enemy nearby) if you insisted. Same for workers.

**Comment by Aqinu** [comment]
I would also preferred it the same way (to work like workers, notify me by stopping the action than give me the option to do what I want).

**Comment by LoneGazebo** [comment]
@ilteroi may need to adjust safety check

**Comment by ilteroi** [comment]
cannot reproduce. dig is interrupted by the archeologist gets back to work when i tell it to.
