### ISSUE TITLE
Can't faith buy Great Persons when Running Out of names

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6783]
_1. Mod version (i.e Date - 4/17): 6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:

I've finished tradition, statecraft and rationalism branches and, at some point in only one of my cities that i had (total 5) I could faith purchase the GPs, then after some time I couln'd do it anywhere (running out of them, I guess, all of them?) but they still could be born by GPP accumulations and for instance for scientist it was given a generic name (great scientist).

So, I think that normally you should be able to faith buy them in all cities and all the time (provided you have faith) but use only the second ability if they run out of names (culture bomb, golden age points, concert...)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Here is the only city where you can faith buy at this moment and the remaining 4 where you can't buy**
![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/86735768-b32e9780-c03b-11ea-80cf-4060d0706f39.png)
![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/86735773-b45fc480-c03b-11ea-94c5-dbb4dd2c021c.png)
![Civ5Screen0002](https://user-images.githubusercontent.com/49090452/86735781-b4f85b00-c03b-11ea-82f5-838312b5886d.png)
![Civ5Screen0003](https://user-images.githubusercontent.com/49090452/86735785-b6298800-c03b-11ea-8c25-abdeb542b4e5.png)
![Civ5Screen0004](https://user-images.githubusercontent.com/49090452/86735792-b75ab500-c03b-11ea-9bd3-2c8c74ed40c5.png)

**And then, at this turn you can no longer buy them from anywhere**
![Civ5Screen0006](https://user-images.githubusercontent.com/49090452/86735888-cb9eb200-c03b-11ea-8b71-d03c5f1ac4b9.png)

**But here you still gain a great person through GPP with generic name (should be the same for faith buy)**
![Civ5Screen0008](https://user-images.githubusercontent.com/49090452/86736046-e53ff980-c03b-11ea-87f7-3e774a8d2261.png)

**Comment by LoneGazebo** [comment]
May be time to incorporate the extra GP mod...only issue is that we'd need to mod it to add the era-specific code. Anyone want to help with that? It's the 'EraType' column in Unit_UniqueNames

**Comment by RecursiveVision** [comment]
@LoneGazebo I could try to help - which mod are you referring to exactly?

**Comment by LoneGazebo** [comment]
Krazjen? Krajzen? Someone like that name has a 'more GPs' mod.

**Comment by RecursiveVision** [comment]
@LoneGazebo I can do the integration work when I get back, presuming the mod author gives permission.

**Comment by GLop4** [comment]
[Krajzen's Great Musicians](https://steamcommunity.com/sharedfiles/filedetails/?id=231104510&searchtext=) Pack is buged.
I made a "more GM" for myself without sound track.

I you want a "more GM" (with sound track) for VP, just ask...

**Comment by GLop4** [comment]
Here is a model with 3x new GM:
[new_musicians.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5038489/new_musicians.zip)

Want more ?
