### ISSUE TITLE
Production cost of pioneers still increasing with number of cities

### ISSUE THREAD

**Issue by Phosphoraptor97** [LoneGazebo/Community-Patch-DLL#6784]
_1. Mod version (i.e Date - 4/17):_
6-19

_2. Mod list (if using Vox Populi only, leave blank):_
Historical Religions Edit v.45
InfoAddict v.22
Krajzen's GWAM Packs
Promo Flags EUI v.1.1
Really Advanced Setup v.15
Religion- Recurring Purchase Notify v.1

_3. Error description:_ 
Production cost of pioneers increases as i gain cities.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[single.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4884895/single.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Intended, same as settlers.
