### ISSUE TITLE
Lebensraum + tribute policy inconsistency

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6788]
_1. Mod version 4/17

_3. Error description:_ 

Tribute policy gives yields when borders expand. Usually this does not apply to expansions from using a great general but with Lebensraum (autocracy) policy you do get the yields from tribute (in your capital) when using a great general to expand your borders.

Not sure which way around is intended but you do get some crazy yields from this combo in lategame.

**Comment by RecursiveVision** [comment]
Okay, so the issue is that Lebensraum awards Culture and GAP from border expansion, and so calls an instant yield:
```
#if defined(MOD_BALANCE_CORE_POLICIES)
			if(GET_PLAYER(getOwner()).IsCultureBombBoost())
			{
				CvCity* pCapitalCity = GET_PLAYER(getOwner()).getCapitalCity();
				if(pCapitalCity != NULL)
				{
					GET_PLAYER(getOwner()).doInstantYield(INSTANT_YIELD_TYPE_BORDERS, false, NO_GREATPERSON, NO_BUILDING, 0, true, NO_PLAYER, NULL, true, pCapitalCity);
				}
			}
#endif
```
This triggers Authority's Tribute Policy, however. @LoneGazebo Is this intended?

**Comment by LoneGazebo** [comment]
@RecursiveVision yeah it is intended.

**Comment by LoneGazebo** [comment]
I'll edit so that all bombs get the boost.
