### ISSUE TITLE
Attacking from Enemy Citadel 

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#6789]
_1. Mod version (i.e Date - 4/17):_
6/19
Enhanced Naval Warfare
3/4 Unique Components 
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When a Unit attacks from an enemy Citadel (unPillaged) they will not move out of it as if it were your own Citadel.

_4. Steps to reproduce (optional):_
Move a high movement Unit (Tank) into a Citadel and have it defeat a weakened Unit from the enemy Citadel.  

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
The Tank defeated a Paratrooper that was on the hidden Antiquity Site.
![20200707152904_1](https://user-images.githubusercontent.com/11430209/86843151-2b18b400-c074-11ea-9824-be516f5f49da.jpg)

**Comment by LoneGazebo** [comment]
@ilteroi do we need to do an ownership check?

**Comment by ilteroi** [comment]
should be an easy fix
