### ISSUE TITLE
Various UU's obsolete Techs

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#6790]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_
Enhanced Naval Warfare
3/4 UC's

_3. Error description:_ 
Indian Naga Malla obsoletes at Combustion, instead of Ballistics.
Austrian Hussar obsoletes at Mobile Tactics, instead of Ballistics.  And they have 1 RCS than standard.
Sipahi (CS UU) goes obsolete at Military Science, giving a very short lifespan. 
Korean H'Wacha goes obsolete at Dynamite instead of Rifling.
Mayan Atlatlist goes obsolete at Rifling instead of Metallurgy.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Okay, I fixed everything except the -1 RCS, I suspect that's intentional since they ignore ZOC and have more CS.
