### ISSUE TITLE
Calculating Unhappiness?

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6791]
I have some suspicions that there is some strangeness going on when calculating unhappiness in cities. It's quite hard to tell though because I don't know what the calculation is supposed to be. Could someone point me to the relevant code so I could take a look please?

Relevant codes:
- Where Global Average is calculated.
- Where Unhappiness of each type in a city is calculated.

**Comment by RecursiveVision** [comment]
@ilteroi modified this recently.

a) I think you're looking for HappinessInfo.lua, not sure though
b) CvCity::GetLocalHappiness / CvCity::GetCityUnhappinessBreakdown

**Comment by Mileslewis** [comment]
Okay thanks man
