### ISSUE TITLE
Demanding Tribute Display Error Or Bug?

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#6792]
_1. Mod version (i.e Date - 4/17):_

June 19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

See picture - self-explanatory.  The display of my military strength indicates that I ought to be trouncing the City-State when demanding tribute, but my reward is only 10%.  This happens often
![20200707193604_1](https://user-images.githubusercontent.com/16022773/86856210-da13ba80-c089-11ea-8d8a-48baecffac23.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Gidoza** [comment]
Sorry and I forgot to mention that the reward as displayed (40ish food) is exactly what my capital received when I hit the button.

**Comment by RecursiveVision** [comment]
@ilteroi Didn't you change something about this recently?

**Comment by ilteroi** [comment]
1. the tooltip is wrong. or at least misleading. the modifier from local military is capped at 100%.
2. i'm not sure how many other negative modifiers there are
3. so in total the 10% might just be right
4. but thinking about it the 100% limit is a bit artifical, so i replaced it
