### ISSUE TITLE
Cannot create new GW of Music

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#6797]
_1. Mod version (i.e Date - 4/17):_

June 19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I have plenty of remaining slots for GW of music, but my Great Musicians are only allowed to do concert tours for some reason.

_4. Steps to reproduce (optional):_

I'm not sure what is causing this.  Maybe there's just a feature I'm not aware of that needs to have a tooltip somewhere so I can understand it.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Known issue - happens once all Great Works for a category have been used up by other civs.

**Comment by Gidoza** [comment]
Oh ok cool.  :)
