### ISSUE TITLE
pathfinding w/ EVENTS_CAN_MOVE_INTO

### ISSUE THREAD

**Issue by Tekamthi** [LoneGazebo/Community-Patch-DLL#6799]
_1. Mod version (i.e Date - 4/17):_
4-17 and previous.. 6-19 has introduced further issues

_2. Mod list (if using Vox Populi only, leave blank):_
any mod that enables EVENTS_CAN_MOVE_INTO 

_3. Error description:_ 

when the customModOptions EVENTS_CAN_MOVE_INTO is enabled and implemented, this feature works as expected for restricting movement, but creates issues with pathfinding:

a unit with this mod flag properly enabled will pathfind appropriately through all visible tiles, but will treat non-visible tiles as though EVENTS_CAN_MOVE_INTO is not enabled.  This happens to all human units, though it is unclear whether AI is affected as well, as typically a unit will eventually gain sight on the barricade tiles to his pathfinding and find a new path.

it appears as though VP's pathfinding code has partially implemented this mod feature (eg it works already in visible tiles), and that this function was either removed or never fully implemented in a portion of the .dll code concerned with non-visible tiles

SPECULATIVE FIX: ensure that, when EVENTS_CAN_MOVE_INTO is enabled, the pathfinding function calls the relevant EVENTS_CAN_MOVE_INTO check for non-visible as well as visible plots... ie add a 2-condition (if mod option enabled, and if unit is flagged for it), 1-line (call the modded plot check function) if statement somewhere in the non-visible pathfinding function, where the plot passability is checked

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Tekamthi** [comment]
issue persists in 12-1... was this one deemed not doable?

**Comment by RecursiveVision** [comment]
@ilteroi

**Comment by ilteroi** [comment]
i don't understand. are you talking about non-visible or non-revealed plots? do you have a picture?

anyway this is again a case where a fringe usecase will have negative performance impact for everybody ...

**Comment by Tekamthi** [comment]
i'll add some screens within a day or two to illustrate the concern

agreed, its possibly not gonna see wide use, this feature, however EVENTS_CAN_MOVE_INTO is nonetheless intact and included in VP, if disabled by default... and it mostly works, just with this odd pathing concern through non-visible, but revealed plots.

the speculative fix i suggested should result in one additional if statement database evaluation (ie mod option won't be enabled for most players and if statement will fail) per plot checked... this strikes me as a small hit on resources, and one that is already occurring in visible plots anyway.  Maybe I have a misconception of how this part of the dll functions though -- maybe time I get into the dll myself finally (*cringe*) :P

anyway will try to elaborate here shortly, thanks for taking a look

**Comment by ilteroi** [comment]
the first place to check is PathValid(...) i assume. but as this is the most frequently called non-trivial function, you have to be careful with it. maybe it's also possible to call the hook from UpdateNodeCacheData(...) which is called less frequently.
