### ISSUE TITLE
6/19 - Trade Route Science from Tourism tooltip is backwards

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6801]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In the tooltip that tells me the amount of science I'm getting from a TR, I believe the amount for number of techs and for tourism are backwards. In this example, I am supposed to get +4 science from TR based on my familiar influence level, and I have a lot more techs than venice. So I think its simply backwards in the tooltip.

Also while you are looking, could you put a line break before "your science gain", as its crammed against the previous paragraph.

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/87204785-534e2000-c2cb-11ea-94e4-226d78d48f0a.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I think the issue is an errant /100 modifier I added. Fixed.
