### ISSUE TITLE
AI offers terms for end of a war, but finds those terms too onerous.

### ISSUE THREAD

**Issue by paramenides** [LoneGazebo/Community-Patch-DLL#6802]
_1. Mod version (i.e Date - 4/17):_

6-19-2
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

To end a war, an AI will offer terms, often involving giving up one or more of their disconnected or smaller cities. The player cannot accept the offered terms, because the AI will claim they are impossible. Probably only happens when player has a very high war score.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Recurring bug. Not sure why it happens.
