### ISSUE TITLE
6/19 - Triplane Interception is not showing up on Combat Screen

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6803]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
There is an intercepting triplane in the city I am attacking (it has made interception hits multiple times in the last few rounds). However, there is no warning of interceptors in the combat screen. This plane is in my full view, so I should get a warning.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/87218374-a64dc480-c317-11ea-93bf-318bbaaf3b29.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
The interception 'warning' is only for AA land units- the yellow warning you see there is what you get for air units (supposed to be a mystery if the air units are on intercept patrol or not).
