### ISSUE TITLE
6/19 - (AI) Archers not firing 2 tiles away from unwalled cities

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6805]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This seems to be an AI bug, as I can fire just fine. In unwalled cities, AI archers are not firing at enemies 2 tiles away. I've seen this behavior repeatedly.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/87231411-ad5aee00-c37c-11ea-8ede-8f0d64efa510.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
weird. according to history this has been in since january 2019 ... fixed.
