### ISSUE TITLE
CSD tooltip

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#681]
ICON_BULLET]
For "Conduct Diplomatic Mission". Missing the first bracket

**Comment by Hokath** [comment]
Cheeky suggestion:
Do you think the CSD ideology wonders could give Civil Servant slots? (instead of paper, perhaps)
Love me some Civil Servants

**Comment by LoneGazebo** [comment]
I'll fix.

Which wonders? The Hall of Heroes, etc.?

**Comment by Radost** [comment]
Hall of Honor, International Finance Center and Palace of Culture and Science.
+2 paper is like nothing at this stage.

**Comment by Hokath** [comment]
what radost said

**Comment by LoneGazebo** [comment]
Gotcha. Yeah, I think we can do that. Should probably also put one on the scriv office and foreign office.

**Comment by Hokath** [comment]
Good idea. 
Scrivener maybe a bit early given when the +yields come?

**Comment by LoneGazebo** [comment]
+yields? From techs, you mean?

**Comment by Hokath** [comment]
Yes
