### ISSUE TITLE
6/19 - AI still loves to get point blank with Carriers

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6811]
_1. Mod version (i.e Date - 4/17):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
First, I just want to note that this is finest carrier fleet I have ever seen the AI put together, so kudos.

And now if they didn't place them right next to cities to be killed that would be even better:) Do you think their ranged attack is the reason they keep getting in close? Would it be better to remove the ranged attack?

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/87502891-7c064a80-c628-11ea-9767-9ff84b9c7553.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Wow, ok...so this turned into the most laughable AI attack I've seen in a long time.

1) AI had 2 atomic bombs....never dropped them (even though they were literally in range of my capital).
2) Carriers stayed within 2 of the city and coast, got slaughtered by cities and machine guns.
3) AI had over 13 aircraft (more than I have ever seen in a single engagement). It proceeds to slam them against 4 mobile Sams + 1 full ace pilot fighter again and again. I believe they lost all of them.


So yeah a bit of work on the tactical AI for this one.

**Comment by ilteroi** [comment]
ok major fail but not much i can do about it without a savegame from a debug build

**Comment by Stalker012345** [comment]
"Save from a debug build".... so not the build I am using currently?

**Comment by ilteroi** [comment]
right. for some reason the save game format is different in release builds and that basically makes savegames from other people useless for me.

**Comment by RecursiveVision** [comment]
@ilteroi Is there a reason why you can't build the release config, or...?

**Comment by ilteroi** [comment]
well the debug build is better for debugging

**Comment by Stalker012345** [comment]
Is there anything I can provide you as I see these things that would help you?
