### ISSUE TITLE
GetNumPoliciesInBranchForDisplay a nil value

### ISSUE THREAD

**Issue by RhysDeAnno** [LoneGazebo/Community-Patch-DLL#6813]
_1. Mod version (i.e Date - 4/17):_
6/19-2 With the July 16 ilteroi DLL installed

_2. Mod list (if using Vox Populi only, leave blank):_
Just Really Advanced Setup to get rid of buggy Morocco

_3. Error description:_ 
When I mouseover a leaderhead to see data EUI throws an error but does not crash the game

_4. Steps to reproduce (optional):_
Mouse over leaderhead, or talk to a leader and mouse them over there

[Nil Value.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4936118/Nil.Value.zip)

<img width="837" alt="NilValue" src="https://user-images.githubusercontent.com/47321731/87756206-777f9480-c7d6-11ea-826a-3dcdf0522c33.png">

**Comment by RecursiveVision** [comment]
Probably caused by the merge error with master. Ole branch fixes this already.

**Comment by RecursiveVision** [comment]
Actually, it seems that I'm mistaken. It is caused by the merge error, but isn't fixed yet.

**Comment by RecursiveVision** [comment]
Merge errors fixed, pushed to ole branch...and renamed to GetNumPoliciesPurchasedInBranch for good measure.
