### ISSUE TITLE
range two citadel is overpowered

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#682]
after some further improvements to AI general handling, watch this:

![image](https://cloud.githubusercontent.com/assets/1358966/10279328/1a82dc38-6b65-11e5-879a-854556c09738.png)

the greeks stole all the land from 'merica. and i guess a human would do the same.

ideas: range one only? disallow building in foreign territory?

**Comment by Radost** [comment]
What is the problem exactly? If america can't retake Seattle, then it probably deserves being wrecked by autocratic Greece.

**Comment by Iamblichos** [comment]
I totally agree with your thinking ilteroi. Even in peace time, the ability to acquire that much land means a city is toast once it comes to war. Every tile could then be outfitted with infantry and tanks to take Washington in a turn or two.

**Comment by Radost** [comment]
Peace time when going Autocracy? Take note citadel-based land acquisitions become null once the city, from which you stole the land, gets flipped.

**Comment by Iamblichos** [comment]
Sure. Peace time. Do you plan to be at war at every given point at the moment you adopt Autocracy with every civ in the game? Generals acquired could be used to take land from a different front and then occupy the new region acquired. That's way too easy.

**Comment by Hokath** [comment]
Not to mention that lebensraum is in the first tier iirc, meaning you can start this naughtiness in the industrial era.
Citadel acquisition doesn't currently proc the other effect, nor tribute, etc. at the moment (?)
perhaps this policy could allow that, instead?

**Comment by LoneGazebo** [comment]
So if it's too strong, should we move it up to tier 2?

**Comment by ilteroi** [comment]
and i would make it so that you can build in your own territory and in adjacent *unowned* tiles only?

**Comment by Radost** [comment]
Then it will make non-autocracy citadels useless.

**Comment by ilteroi** [comment]
not really. you can still steal up to 5 tiles. on average maybe 3 or 4. not too bad.

**Comment by Radost** [comment]
More like 3 at best. In exchange for a great person.

**Comment by ilteroi** [comment]
so i went ahead and implemented the change - closing the issue

**Comment by Radost** [comment]
You should've brought up this issue on the forums first, because 3 participants isn't very reliable sample size for the gameplay balance changes.

**Comment by LoneGazebo** [comment]
Which change? I'm fine with trying it, but we need to document it for the change log.
