### ISSUE TITLE
Cant declare war on other players

### ISSUE THREAD

**Issue by Synchrololled69** [LoneGazebo/Community-Patch-DLL#6820]
_1. Mod version (i.e Date - 6/19):_
10-08-19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
We're a group of 4 trying to play the game but we are unable to declare war on eachother, we've tried multiple versions as well as differend modpacks and basegame, the issue seems to only occur when using VP modpack.

**edit** obviously we are not in the same team either

Reinstalling the game and/or mod didn't seem to solve it eitherm we've also tried multiple setting changes.

_4. Steps to reproduce (optional):_
for us it is litterly skirmish map, duel size, and find each other to attempt to declare war to find out we cant, neither by attacking a unit, attemping to go in their border or anything. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Synchrololled69** [comment]
We've found a workaround for not being able to declare war which is that we use CTRL and click on the portrait of said player to declare war but the normal way of putting a unit in their border or attacking their units still doesn't work.

**Comment by ilteroi** [comment]
yeah the automatic war declaration was buggy and annoying. have to do it manually.

**Comment by Synchrololled69** [comment]
Makes me wonder thought why there were moments where it was possible there were games where we could normally declare war without having to CTRL click on the civ portrait.

Any way for us to make it possible again to just declare the normal way? cause we prefer that over having to use this method.

**Comment by RecursiveVision** [comment]
Does clicking on their portrait/city banner and hitting "DECLARE WAR" not work? I thought that's what you meant wasn't working.

**Comment by Synchrololled69** [comment]
We have no way to declare war when we go to eachothers portrait we just have options like declare friendship the only way for us to declare war is to use the cheesy EUI method by pressing CTRL and then clicking their portrait which forces a declare war / peace treaty window

**Comment by RecursiveVision** [comment]
Well, that seems like a bug to me, @ilteroi - there should be a window popping up with options to trade or declare war in multiplayer...

**Comment by Synchrololled69** [comment]
Trading is possible @RecursiveVision the only thing we cant do is declare war on eachother. we can trade stuff like cities, friendship, research agreement and so on but declaring war is impossible

**Comment by ilteroi** [comment]
ok maybe i misunderstood but i was referring to the war declaration popup when moving units. diplo screen is a different thing

**Comment by azum4roll** [comment]
Clicking on another (human) player's portrait brings up the trade screen with the Denounce button but no Declare War button.

**Comment by LoneGazebo** [comment]
I believe a ctrl+click on portrait declares war?

**Comment by Synchrololled69** [comment]
Yes correct thats the workaround we ended up finding, but this seems a bit weird, we never knew of this and we previously did declare war on each other by just using units

**Comment by RecursiveVision** [comment]
I think it should be more intuitive to the player than Ctrl+Click...

**Comment by LoneGazebo** [comment]
Closing for now, as I recall that implementing a human->human DOW button caused desyncs in the past.

**Comment by RecursiveVision** [comment]
@LoneGazebo Isn't there one in vanilla already?

**Comment by LoneGazebo** [comment]
Nope. Not in MP.
