### ISSUE TITLE
Statecraft's foreign service gives 34 strategic resources imported

### ISSUE THREAD

**Issue by SolicShooter** [LoneGazebo/Community-Patch-DLL#6821]
_1. Mod version (i.e Date - 6/19):_
6/19-2 with new Recursive dll. 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Picking Statecraft's foreign service gives you 34 of all strategic resources imported including ones like uranium/paper.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Before_broken.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4949752/Before_broken.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I fixed this, sounds like someone undid my fix. It's the use of the minorstrategic value in cvPlayer - that's a nono, and I commented out the offenders for 6-19.

G

**Comment by RecursiveVision** [comment]
I think not everything from master was merged into ole/drk originally, that fix must've slipped through the cracks.

**Comment by RecursiveVision** [comment]
@LoneGazebo After investigation it looks like that specific fix slipped through the cracks but everything else was merged in correctly. I'll recomment them out in my next pull request. :)
