### ISSUE TITLE
CTD after declaring war and return to world (dlc modpack)

### ISSUE THREAD

**Issue by apolo49** [LoneGazebo/Community-Patch-DLL#6822]
_1. Mod version (i.e Date - 6/19):_
6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_
- (1) Community Patch (v 94)
- (2) Community Balance Overhaul (v 13)
- (3) City-State Diplomacy Mod for CBP (v 28)
- (4) C4DF - CBP (v 11)
- (5) More Luxuries - CBO Edition (5-14b) (v 155)
- (7a) Promotion Icons for VP (v 3)
- (7b) UI - Promotion Tree for VP (v 22)
- Additional Ancient Ruin Rewards (v 1)
- Ayyubid Civilization (v 2)
- Benin (Brave New World) (v 61)
- Buildings - Goldsmith (v 4)
- Buildings - Storage Yard and Stockpile (v 2)
- Caral - Norte Chico (Brave New World) (v 37)
- Caravans Build Roads (v 1)
- Champa (Brave New World) (v 43)
- Diplomacy - Tech Bonuses (v 1)
- DMS' Civilizations (with CL) - Madagascar (Ranavalona I) (v 4)
- Enlightenment Era (Vox Populi) (v 1)
- Fortress Borders (v 2)
- Global - Air Routes (v 2)
- Global - Passable Forts (v 3)
- Harappa - Indus Valley (Brave New World) (v 55)
- Hex Conquer and Release (v 3)
- Historical Religions Complete (BNW or GK) (v 45)
- InfoAddict (v 22)
- JFD's Civilizations - Aquitaine (Eleanor) (v 1)
- JFD's Civilizations - Armenia (Tiridates III) (v 4)
- JFD's Civilizations - Belgium (Leopold II) (v 1)
- JFD's Civilizations - Brittany (Nominoe) (v 1)
- JFD's Civilizations - Canada (Mackenzie King) (v 1)
- JFD's Civilizations - Central Africa (Bokassa I) (v 1)
- JFD's Civilizations - Germany (Adolf Hitler) (v 11)
- JFD's Civilizations - Great Jin (Shizong) (v 1)
- JFD's Civilizations - Great Liao (Shengzong) (v 1)
- JFD's Civilizations - Great Ming (Yongle) (v 1)
- JFD's Civilizations - Great Qing (Cixi) (v 4)
- JFD's Civilizations - Hungary (Stephen I) (v 10)
- JFD's Civilizations - Indo-Greeks (Menander I) (v 1)
- JFD's Civilizations - Kongo (Afonso I) (v 1)
- JFD's Civilizations - Laos (Fa Ngum) (v 1)
- JFD's Civilizations - Lithuania (Gediminas) (v 5)
- JFD's Civilizations - New Zealand (Keith Holyoake) (v 1)
- JFD's Civilizations - Norway (Haakon IV) (v 9)
- JFD's Civilizations - Punjab (Ranjit Singh) (v 1)
- JFD's Civilizations - Siam (Rama V) (v 1)
- JFD's Civilizations - Soviet Union (Joseph Stalin) (v 15)
- JFD's Civilizations - Switzerland (Henri Dufour) (v 6)
- JFD's Civilizations - Yugoslavia (Peter II) (v 1)
- JFD's The Commonwealth of Iceland (v 2)
- JFD's The County of Flanders (v 1)
- JFD's The Duchy of Burgundy (v 1)
- JFD's The Republic of Carthage (v 4)
- Kievan Rus' (Brave New World) (v 74)
- Light in the East - Akkad (v 1)
- Light in the East - Sri Lanka (v 2)
- Light in the East - The Ainu (v 1)
- Light In The East - The Safavid Empire (v 1)
- Mali (Brave New World) (v 52)
- MC and LITE's Moorish Civilisation (v 4)
- MC and LITE's Nubia (v 3)
- MC's Greek Civilisation Split (v 2)
- MC's Tuareg (v 1)
- More Trade Routes (v 1)
- No Road Maintenance (v 2)
- Promotions - Extra Cargo (v 5)
- Religion - Beliefs Expansion Pack (v 26)
- Religion - Bonus Beliefs (v 1)
- Religion - Early Piety (v 1)
- Religion - Recurring Purchase Notify (v 1)
- Shang (Brave New World) (v 22)
- Sukritact's Burmese Civilization (v 2)
- Sukritact's Khmer Civilization (v 1)
- Sukritact's Phoenician Civilization (v 2)
- Sumer (BNW or GK) (v 70)
- Tech - Satellites Reveal Cities (v 10)
- The Bruneian Empire (v 2)
- The Garamantes (Brave New World) (v 73)
- The Hittites (Brave New World) (v 76)
- The Olmec (Brave New World) (v 33)
- The Sioux (Brave New World) (v 32)
- The Timurids (Brave New World) (v 71)
- UI - Destination (v 4)
- UI - Diary (v 21)
- UI - Enhanced Demographics (v 6)
- UI - Religion Spread (v 13)
- UI - Upgrade Tree (v 9)
- Unique Improvement - Tipi (v 2)
- Unique Unit - Longboat (v 6)
- Units - Brigantine (v 1)
- Units - Cheap Workboats (v 2)
- Units - Dwarf Broad Axeman (v 1)
- Units - Equine Need Stables (v 4)
- Units - Herdsmen (v 12)
- Units - Mech Infantry (v 9)
- Units - Mounted Units (v 11)
- Units - Multiple Upgrades (v 2)
- Units - Paratroop Enhancements (v 4)
- Units - Population (v 10)
- Units - Prospectors (v 8)
- Units - Super Carrier (v 11)
- Xia - Erlitou (Brave New World) (v 67)
- [BNW] Colonialist Legacies (and Senshi) - Australia (Bob Hawke) (v 1)
- [BNW] Colonialist Legacies (and Senshi) - Samoa (v 1)
- [BNW] Colonialist Legacies - Afghanistan (v 4)
- [BNW] Colonialist Legacies - Australia (John Curtin) (v 1)
- [BNW] Colonialist Legacies - Australian Commonwealth (v 4)
- [BNW] Colonialist Legacies - Canadian Dominion (v 2)
- [BNW] Colonialist Legacies - Cuba (v 1)
- [BNW] Colonialist Legacies - Greenland (v 1)
- [BNW] Colonialist Legacies - Kimberley Aboriginals (v 2)
- [BNW] Colonialist Legacies - Kulin (v 1)
- [BNW] Colonialist Legacies - Nigeria (v 3)
- [BNW] Colonialist Legacies - South Africa (v 1)
- [BNW] Colonialist Legacies - The Beothuk (v 1)
- [BNW] Colonialist Legacies - The Blackfoot Confederacy (v 2)
- [BNW] Colonialist Legacies - The Chimu (v 1)
- [BNW] Colonialist Legacies - The Cree (v 4)
- [BNW] Colonialist Legacies - The Dene (v 4)
- [BNW] Colonialist Legacies - The Murri (v 1)
- [BNW] Colonialist Legacies - The Tlingit (v 2)
- [BNW] Colonialist Legacies - The Wabanaki (v 1)
- [BNW] Colonialist Legacies - Vietnam ft. Trung Sisters (v 1)
- [BNW] Colonialist Legacies - Zapotecs (v 1)
- [BNW] Colonialist Legacies The Coast Salish (v 1)
- [BNW] Colonialist Legacies' Anishinaabe (v 1)
No EUI.

_3. Error description:_ 
Crash to desktop after declaring war on any civ, Human or AI

_4. Steps to reproduce (optional):_
Declare war on civ, return to overworld.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): http://www.mediafire.com/file/bf3u579bm1hep36/Logs.zip/file

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 
[AutoSave_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4949857/AutoSave_0000.BC-4000.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): http://www.mediafire.com/file/fdq29b772oc8i8i/CvMiniDump.dmp/file

4. Screenshots (optional):

**Comment by apolo49** [comment]
If Modpack is wanted will upload

**Comment by RecursiveVision** [comment]
@apolo49 That's a _lot_ of mods. Doubtful we'll be able to do much.
