### ISSUE TITLE
AI running out of things to build

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6823]
king level, standard speed, 1700 AD. attila went progress/statecraft.

they have nothing left to build ... the turn before all cities were using the food process btw.

![image](https://user-images.githubusercontent.com/1358966/88028326-cb70dd00-cb38-11ea-982c-4a74f5d2d629.png)

is that intended? seems like the AI bonuses are a bit high?

**Comment by RecursiveVision** [comment]
There are frequent complaints that the AI production bonuses are excessive and should be scaled back, especially since they can occasionally instantly build a World Congress project or Wonder because of them.

**Comment by azum4roll** [comment]
That land is just too perfect for the Huns.

Btw I noticed they can sometimes get their city names from civs not in the game. Is that intended?

**Comment by RecursiveVision** [comment]
@azum4roll Yes. It's part of their UA in BNW.

**Comment by azum4roll** [comment]
@RecursiveVision They should only get city names from the civs in game.
