### ISSUE TITLE
EUI_text_en_us.xml doesn't get installed by installer

### ISSUE THREAD

**Issue by ZebraFromPluto** [LoneGazebo/Community-Patch-DLL#6824]
_1. Mod version (i.e Date - 6/19):_
6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The installer doesn't install the file from EUI named EUI_text_en_us.xml into \Documents\My Games\Sid Meier's Civilization 5\Text. As a result many places in the game will show XML tags such as TXT_KEY_EUI_BUILT_IN_X_CITIES in city building info instead of replacing it with the relevant text.
See error reported in forums here: https://forums.civfanatics.com/threads/community-patch-how-to-install.528034/page-164#post-15840098

_4. Steps to reproduce (optional):_
If you have EUI_text_en_us.xml in your Text folder (presumably from installing EUI separately at some point) then temporarily rename it, run the game, then hover your cursor over a Monument in any city and you will see TXT_KEY_EUI_BUILT_IN_X_CITIES in the info.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Zanteogo** [comment]
Are you installing to a not default location? I notice that if you attempt to do so that some of the files get put into the default location anyways.

**Comment by ZebraFromPluto** [comment]
@Zanteogo That's a known issue with the UI_bc1 folder from EUI. The EUI_text_en_us.xml file isn't getting installed at all, anywhere. It's not in the manual install files either.

**Comment by LoneGazebo** [comment]
Doesn't need to be, it is integrated elsewhere.

**Comment by ZebraFromPluto** [comment]
I'm not sure what you think "is integrated elsewhere", but the file EUI_text_en_us.xml isn't, and without it you will see XML tags in several places. If you install Vox Populi on a clean install of Civ 5 you will see the XML tags. Check this more carefully please; I assure you it's a real problem. I've see other posts from users seeing the XML tags as well.
