### ISSUE TITLE
Random Nuke Rolls

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6825]
So AI nukes based on two random rolls (they have to pass both) and their USE NUKE flavor, or if nukes have been used already. This is a Firaxis design choice. I improved it a little to make them more likely to use nukes, but this still feels kind of...clunky and artificial.

Should we keep the random roll? I'm leaning towards no: AI doesn't seem to have a problem targeting opponents, and it'd make the late game more intense and fun if the AI doesn't toss nukes on carriers only not to use them.

**Comment by RecursiveVision** [comment]
Alternatively we could reduce it to one random roll, so the USE NUKE flavor isn't totally useless (it's only used for the random rolls and a bump to conquest desire in the policy AI).

**Comment by ilteroi** [comment]
well i guess it was a hack to stop them from using too many nukes. 

a replacement mechanism should take into account diplomatic repercussions. or is that already in place?

**Comment by Stalker012345** [comment]
Its actually an interesting debate in terms of how much nuking we want the AI to do. In theory, nukes are the ultimate AI power play, high production disposable units that basically ignore how strong (or promoted) the enemy units are. I can see a scenario where the AI could effectively reset the human board....killing all of the high promoted units with nukes, forcing the human to start over.

My guess is that human players would hate that with the passion of 1000 suns (although the deity players can finally have their ultimate warfare challenge ;)

I certainly would at least like to see a bit more nuking, especially the key capital nuke blitz to try and stay in the game.

**Comment by Mileslewis** [comment]
It wouldn't be the end of the world as units can be built with a decent amount of levels late game.

I think it would mainly be annoying if AIs just got to the tech much before you and then came and nuked you for no real reason. Like would be better if it was use defensively/in retaliation, and yea have a big diplo effect.

The amount of spare production the AIs have lategame may be another problem if they build and use so many.

One other thing is that when I use nukes myself they did like 50-60% damage to units but when I got nuked my units got insta-killed. Is that intended?

**Comment by azum4roll** [comment]
If AIs use more nukes I think the SDS should be changed to have the following effects instead:

0. No random chance of making nukes disappear
1. Reduce population loss on cities by 75%
2. Pillage and nuclear fallout only have 25% chance to happen on each affected tile inside the city territory
3. 50% damage reduction on units inside the city territory

Alternatively, somehow make nukes and missiles interceptable and teach the AI that.

**Comment by Zanteogo** [comment]
> Alternatively, somehow make nukes and missiles interceptable and teach the AI that.

There already exists a city building that does this. (50% chance)

If you guys want to make the AI more nuke happy may I suggest you link it into difficulty level?

**Comment by bigcat88** [comment]
Tradition players will hate AI that nukes them. 
Lets imagine that a year past and AI are a brilliant commandor.
So tradition human player(or AI) must have an opportunity to avoid most nukes. Like extra class bombshell - to evacuate citiziens and some army. 
Or an extra class of some Iron Sky Shield project(https://www.raytheonmissilesanddefense.com/capabilities/products/irondome)
It can cost a huge number of hammers, resources or gold - but it must be. Imho.

**Comment by Stalker012345** [comment]
It still feels like there is more debate to do here, not sure why the issue is closed.

**Comment by RecursiveVision** [comment]
I'll bring it up on the forums.

**Comment by LoneGazebo** [comment]
Sorry, I added the tag 'Community Polling' but it didn't take.
