### ISSUE TITLE
City-States Friend/Not-Friend color is the same

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#6827]
_1. Mod version (i.e Date - 6/19):_
6/19-2

_2. Mod list (if using Vox Populi only, leave blank):_
all the VP
Pontoon Bridges for VP
XCOM for VP
Community Patch Mod Compatibility

_3. Error description:_ 
City States color indicator for Friends/Not-Friends appears the same. It used to be that Not-Friends would show no color, and Friends would show as lime-green. Now, they're all lime-green. So, at a glance, it's not easy to tell whose territory you can travel through without a diplomatic penalty.

_4. Steps to reproduce (optional):_
Play the game, visit a city-state, hover mouse over right side of city-state name bar which will inform you of the influence you have over the city-state. the field behind the city-state icon (e.g., culture, faith, mercantile) is a lime-green color, regardless of your relationship status.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by briantjack** [comment]
On further play, I have realized that CS are now colored by their moods (Allies, Fear, Anger, etc.). Still, it would be nice to have an additional indicator differentiating friends from non-friends.

**Comment by RecursiveVision** [comment]
I think this is fixed for next version.
