### ISSUE TITLE
6/19 - Musician Bomb Tooltip shows incorrect tourism numbers

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6828]
_1. Mod version (i.e Date - 6/19):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This is is actually an old bug, its been around a long time, but I finally took some time to actually showcase it. The number shown in the tooltip...I have no idea where it comes from but its not accurate. Its not the base, and its not the tourism bomb factoring in Tourism modifiers. In this example, the actual tourism gotten from the bomb (taken directly from the CV UI) was 17074

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/88148922-f0ab2d00-cbc4-11ea-812a-2c2f477da11e.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
I will note that sometimes the tooltip shows the same number as the base GM shows, and sometimes you get what I noted above, so it appears inconsistent

**Comment by Stalker012345** [comment]
@LoneGazebo did this get fixed? I didn't see the fixed tag for it.

**Comment by LoneGazebo** [comment]
Yeah.
