### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by PhiLe20** [LoneGazebo/Community-Patch-DLL#6829]
_1. Mod version (i.e Date - 6/19):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Game crashes between turn 3-5, most of the time turn 5. Installed using the automatic installer. 
Settling a city or not makes no difference, it always crashes on turn 3-5
The game Crashes when hitting next turn and the first 4-5 AI Civs get their turn calculated
Additionally, upon crash, I could see a small glimpse of the civ5 launch cinematic for 1-2 seconds, afterwards black screen and shutdown of Civ5 (this happened only twice in 8 test)
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4959496/Logs.zip) 

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 
[AutoSave_0002 - 3920 v. Chr..zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4959481/AutoSave_0002.-.3920.v.Chr.zip) 

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[civilizationv_403694_crash_2020_7_20T12_10_14C0.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4959490/civilizationv_403694_crash_2020_7_20T12_10_14C0.zip) 

4. Screenshots (optional):

**Comment by ilteroi** [comment]
callstack log is empty. seems the crash is happening outside of the dll. that is bad.

**Comment by PhiLe20** [comment]
Is my Laptop to blame? Maybe performance or stuff like that? I can run Civ 5just fine tho.

**Comment by ilteroi** [comment]
well some other people see this too. maybe experiment with your graphics settings?

**Comment by PhiLe20** [comment]
Unluckily no chances did 4 test with different graphic settings. All Crashes within 3-5 Turn.

**Comment by cdanger341** [comment]
It's not the graphics settings. I already tried adjusting every possible graphics settings from max to min and still saw consistent crashes on turns 4-5. It's also not non-VP mods as I've tried playing with just base VP 6-19-2 and the crashes are still consistent. These crashes did not occur in the initial 6-19 release, only post-hotfix. So it was something that was changed between 6-19 and 6-19-2.

**Comment by PhiLe20** [comment]
OK very cool. To lower confusion and streamline a bit the thought process, i believe it to be beneficial if everybody would go the "original" report at #6708 
If anyone finds stuff or got any idea later, pls go there has it is probably easier to find a solution on one singular thread than a lot of different ones.

**Comment by LoneGazebo** [comment]
So I think I may have found the CTD - apparently the AI will look for 'turnssincestatementsent' in the diplo AI when evaluating war with a player, but if the target was a minor civ it would cause them to violate the memory allocation for the variable (as the variable was only expanded to the size of the major civ pool). Going to test to see if my simple fix works.
