### ISSUE TITLE
6/19 - Border Growth AI showing unequal tiles as equal choice for growth

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6830]
_1. Mod version (i.e Date - 6/19):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In this example, the deer is clearly the best choice, yet there are 3 options the border may expand to. I could potentially understand number 2, as based on buy cost it looks slightly cheaper, but why is number 3 at the bottom even an option?

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/88211099-cedc9500-cc1a-11ea-948b-29a5342cf269.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
two rules

* at most 3 plots are highlighted
* all plots are highlighted which have at least half the score of the best plot

**Comment by Stalker012345** [comment]
well damn, learn something new every day!
