### ISSUE TITLE
Universities don’t produce +1 science from Jungle tiles!

### ISSUE THREAD

**Issue by soeb80** [LoneGazebo/Community-Patch-DLL#6831]
1. Mod version (i.e Date - 4/17):
Latest to date; 6-19 (including the 7/19 additional update)
2. Mod list (if using Vox Populi only, leave blank):
CP 6-19 installer (1,2,3,4,5,6a,7a,7b)
+Infoaddict
3. Error description:
Universities and Jungle tile don’t produce the extra science!

I have a lot of Jungle: no city with a university earn any extra science from worked Jungle tiles! 

![3AFFEE24-D812-4C56-9428-A0002A1D84CB](https://user-images.githubusercontent.com/67321050/88318076-81475180-cd1a-11ea-98d4-88ad7fbddeb3.jpeg)

**Comment by DelJon** [comment]
I am having that same issue, running the files from July 17, manual install, Calypso's and extra great works mods.
When I build a University the science to jungle tiles is there but once I load a game, the cities that already have Universities don't get the yields in Jungles anymore.
Besides science from Universities, the same thing is happening with the zoos, their culture and science are missing after loading a game in both jungles and forests while this DOES NOT happen with Workshop's +1 production to forests or Lighthouse yields (or any other that I saw), I can see both records in the database table for changing to yields of features, but they just don't work when I load games. I ran another game in Information era to confirm it's not just that savegame and test with zoos.

![jpg](https://user-images.githubusercontent.com/23047762/88442536-850fcc80-ce1d-11ea-9429-aa4744fdd479.jpg)

**Comment by ilteroi** [comment]
i have a suspicion, will check

**Comment by soeb80** [comment]
> i have a suspicion, will check

👍🏻 It would be super if you could post a patch file, just like last time here on githhub, as soon you found the problem. The deficiencies of culture and science makes the game unplayable for the moment. 🙏🏻🥰

**Comment by ilteroi** [comment]
cannot reproduce ...

![image](https://user-images.githubusercontent.com/1358966/88515252-b3db9d80-cfeb-11ea-82e8-29701238cb77.png)

**Comment by ilteroi** [comment]
serialization for CvCity was broken, is fixed

**Comment by soeb80** [comment]
> serialization for CvCity was broken, is fixed. however this breaks savegames, is unavoidable

@ilteroi; what does that mean?

As mentioned I started a new game after installing the new 7/19 patch. I decided to continue playing without the science bonus after initially realizing the deficiency... I built Zoos, and revived the bonuses. As @DelJon mentioned; the day after when I loaded the game from the day before, there was no longer bonuses from Jungle tiles (+1 science, +2 culture and +2 tourists).

**Comment by DelJon** [comment]
> serialization for CvCity was broken, is fixed. however this breaks savegames, is unavoidable

Is there a fixed version available so that we can start some more stable games? Or do we have to wait for the next release? This patch has been rough, big respect for your work either way though.

**Comment by ilteroi** [comment]
serialization broken means i forgot to save/restore the extra yield per terrain and per feature ... now i added that but that means you cannot load your old savegames anymore.

anyway check #6812 for a build

**Comment by soeb80** [comment]
@ilteroi; Thanks a bunch! ❤️
The question still is: is there a patch file we can download?
