### ISSUE TITLE
Naval melee and ranged units instakill embarked military land units without engaging in combat as if they were civilian units

### ISSUE THREAD

**Issue by SuperNoobCamper** [LoneGazebo/Community-Patch-DLL#6832]
_1. Mod version (i.e Date - 6/19):_

16-9-2

_2. Mod list (if using Vox Populi only, leave blank):_

- VP with EUI
-Unique CS
-3rd & 4th UC
-Infoaddict
-Really advanced setup

_3. Error description:_ 
naval units -both melee and ranged- are insta-killing embarked land units as if they are civilian units, happened twice to two of my explorers *enemy units were a triremme not taking any damage and a galleass* and i could do it too with my galleass without ranged attack, it just passes over it and kill it as if it's a worker or any civilian unit.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

[Nope.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4969400/Nope.zip)

**Comment by RecursiveVision** [comment]
@SuperNoobCamper Using ilteroi's patch?

**Comment by SuperNoobCamper** [comment]
No, just the 19-6-2 installer.

**Comment by RecursiveVision** [comment]
Then it's already fixed.
