### ISSUE TITLE
Crashing around the turn 200 during city state turn

### ISSUE THREAD

**Issue by hawkseye17** [LoneGazebo/Community-Patch-DLL#6834]
**GO TO BOTTOM OF THIS ISSUE FOR EXPLANATION ON NEW REVELATION**

_1. Mod version (i.e Date - 6/19):_

6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

![Screenshot (69)](https://user-images.githubusercontent.com/67494452/88448147-75d25400-ce08-11ea-8eae-476f0cd4f694.png)
![Screenshot (70)](https://user-images.githubusercontent.com/67494452/88448148-766aea80-ce08-11ea-9151-bd3ff51a0385.png)

I am also using the Ethnic Diversity mod: https://forums.civfanatics.com/threads/ethnic-diversity-r-e-d-unofficial.449070/

Note: In my current game, only the Papal States, Tunis, and Wallachia are in the game

_3. Error description:_ 

Consistent crash occurring around turn 200 at the start of my turn; it happens before it even shows the leader's name (ex: Enrico Dandolo the Great) . I had this issue countless times before and I've tried with different mod setups, leaders, and custom civs and I still keep crashing at the start of my turn around 200 turns into the game. My last report of it was #6728 but I had way more mods installed. I'm starting to think it might not be a mod problem and might be something that comes with the events or anything that occurs at the very beginning of my turn. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

[Game Crash Info.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4974874/Game.Crash.Info.zip)

I tried again with less players, lower graphics, and less mods and I still crashed around the same turn mark. I'm also using @ilteroi 's new patch. I'm really desperate for a solution here. 

[Crash Information 2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4985424/Crash.Information.2.zip)

The crash was not at the start of my turn after all. It seems to be a problem from something going on during the city-state turn. I don't know which city-state but after killing them all using IGE, the issue was gone. Clearly this is not a good workaround so I'm hoping someone can help me properly fix this 

[Crash Info 3.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4986112/Crash.Info.3.zip)

**Comment by hawkseye17** [comment]
Ok so during random troubleshooting, I decided to kill all city states with IGE and the crash did not occur at the start of my turn. I don't know which city state is at fault for this but this does seem to narrow down the issue more. Probably because I used quick turns, the issue appeared to be at the start of my turn but it was during the city state turn. I still have no idea what is causing this crash though, I just now know when it happens specifically

**Comment by hawkseye17** [comment]
Another update, I found that the causative city-state was Ormus. Specifically the city as after I added one city with IGE to Ormus, then deleted the original city, the game did not crash. I have no idea what is causing the crash but now I know who is causing it

**Comment by ilteroi** [comment]
@LoneGazebo : can you check this? only you have the PDB for 6-19-2 ... take the minidump, follow the steps in #6459 and this should be easy
