### ISSUE TITLE
6/19 (Tactical AI) - AI didn't pillage key strategic resource

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6835]
_1. Mod version (i.e Date - 6/19):_
6/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
iteroi, here's another one for the list. In this example, the AI had a unit on that iron next to my city for 2 full turns, and didn't pillage it. It was a critical resource, would have knocked out 2 swords in prod, and would have left my other 2 unable to heal.

Logical wise, in ancient or classical, I would say the AI should be willing to pillage the resource even at the cost of its life, that early in the game can completely shift a war.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/88516670-43b12580-cfb3-11ea-8137-5beace4c00f6.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
right now they only specifically target citadels, but i extended it to strategic resources.

so should be better now, check the new build at #6812
