### ISSUE TITLE
1Million Archaeologist Points In Ancient Era

### ISSUE THREAD

**Issue by GoodGoy777** [LoneGazebo/Community-Patch-DLL#6838]
_1. Mod version (i.e Date - 6/19):_

6/19
_2. Mod list (if using Vox Populi only, leave blank):_
![Screenshot (31)](https://user-images.githubusercontent.com/68883948/88612733-7ad61400-d051-11ea-8b7c-b7476148e9d3.png)

_3. Error description:_ 
Archaeologist spawning as great people only in capital in ancient era. Each birth increase gp points. May or may not be tied to Kuk wonder from overhaul more wonders for VP

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4985644/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[AutoSave_0020 BC-2800.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4985635/AutoSave_0020.BC-2800.zip)
Not sure how many turn before issue

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Screenshot (30)](https://user-images.githubusercontent.com/68883948/88612843-b5d84780-d051-11ea-8516-82d1a61c4d12.png)
![Screenshot (29)](https://user-images.githubusercontent.com/68883948/88612846-b83aa180-d051-11ea-80d3-c6d346d15187.png)

More wonders for vp mod i version8.3 which is only in github had to compile myself.

Uncompiled Version
https://drive.google.com/drive/folders/1pWjsp06P6utZs8aUM701zvI4wOHdwr8o?usp=sharing

Compiled Version
https://drive.google.com/drive/folders/1Vumyv8RunE0LfqxP9dfQ2T9e_nuTZ0nL?usp=sharing

**Comment by RecursiveVision** [comment]
Report the issue on the mod's forum thread, not here.

**Comment by GoodGoy777** [comment]
I havent narrowed down the problem to any of the other mods though dont see how the others in my list could cause this, positive its VP
