### ISSUE TITLE
ilteroi patch, incorrect number of city states

### ISSUE THREAD

**Issue by mt-empty** [LoneGazebo/Community-Patch-DLL#6839]
_1. Mod version (i.e Date - 6/19):_
ilteroi patch only

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The game doesn't spawn the correct number of city states.
For example:
If I choose 5, it spawns none.
if I choose 35, it spawns 14.
if I choose 41 it spawns 20.

_4. Steps to reproduce (optional):_
start a game on at large map.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
![wpid-unpossible-2014-01-23-20-43](https://user-images.githubusercontent.com/1358966/88678594-f043f200-d0ee-11ea-859c-20e5218beb0b.jpg)

**Comment by mt-empty** [comment]
It's fixed with the new patch #6844
