### ISSUE TITLE
crash in luajit dll

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#684]
any lua experts around here?

i have a fairly reproducable crash (~50%) when exiting the game (to main menu or completely). has been like that forever, but now i'm running out of patience :)

![image](https://cloud.githubusercontent.com/assets/1358966/10291310/7959b0ee-6ba9-11e5-8d45-aa9d232bbda2.png)

this is the place. i'm using a debug build of luajit to see this. how can i go on from here? how do i find out the file and line of the lua script thats making this call?

**Comment by LoneGazebo** [comment]
This is why I stopped using luajit. You've looked here? http://luajit.org/faq.html

**Comment by Iamblichos** [comment]
This is the same crash that we all experience regardless if we use luajit or not, correct?

**Comment by ilteroi** [comment]
don't see anything relevant in the faq, what do you mean? anyway, i'll check if the regular lua is any better. 

but since the crash is not 100% reproducable, luajit can't be so bad, more likely it's a timing issue during deallocation

**Comment by Iamblichos** [comment]
It happens to me no matter which one I use, I wonder if Firaxis would be any help here.

**Comment by ilteroi** [comment]
maybe it's really better with normal lua? couldn't reproduce the crash in five or six attempts now. i'll watch it for a while and then close this issue if it doesn't reoccur.

**Comment by Iamblichos** [comment]
Hmm...yeah seems to only crash if you do a restart on turn 1 to reroll.

**Comment by ilteroi** [comment]
yep. still there. same function even:

![image](https://cloud.githubusercontent.com/assets/1358966/10331079/97b4146a-6cd2-11e5-99e1-7f3b91617508.png)

**Comment by ilteroi** [comment]
ok - turns out it's not a script being executed but a direct call from Civ5.exe with an invalid lua stack.

don't have a clue what's happening there, but I put in a dirty hack (IsBadReadPtr) and that seems to fix it. don't know what to do now though ... @LoneGazebo : would you like to include it in the installer?

**Comment by LoneGazebo** [comment]
Did you check the netmessagedebug log to see if it's a DLL call that's bypassing everything?

What's the 'dirty hack' entail?

**Comment by ilteroi** [comment]
well, i've seen the callstack, no DLL function in there.

The hack part is about IsBadReadPtr() - that's a windows function, but one really shouldn't use it because it hides bugs and is not 100% accurate. but in this case it's the only option.

**Comment by LoneGazebo** [comment]
How common is this CTD? Worth the install for normal users?

**Comment by Iamblichos** [comment]
I think it happens about 20% of the time going to main menu. And about 90% time (or more) when you want to 'Restart Game'. If it corrects the latter where you can actually reroll a restart without backing out, I'd include it if there is foreseeable issue.

**Comment by LoneGazebo** [comment]
Cool. If it fixes the issue, it is worth including, then. Luajit is nice (and feels snappier, even if it actually isn't).

**Comment by ilteroi** [comment]
ok, here's the new lua dll. normal lua and luajit version - pick your poison :)

in both cases, initialization/deinitialization may be a bit slower, but ingame there's no difference to the unpatched version. https://dl.dropboxusercontent.com/u/16988401/civ/lua-fixed.zip

**Comment by LoneGazebo** [comment]
I haven't included the file yet, but I'll make a link for interested users.
