### ISSUE TITLE
Not a bug report but a request for air interception related files.

### ISSUE THREAD

**Issue by yyEdge** [LoneGazebo/Community-Patch-DLL#6840]
I was directed here by Recursive from civfanatics forum.

My original message from the forum is:

Hi, can someone point me towards the files related to air interceptions? I think I figured out the cause for plane interception animations to not play (or just do this weird circle around the city)

So ever since the Jan version interception has been changed to the attacker (bomber or fighter) not dealing damage to the target when intercepted (though for the Jan version it's infinite damage instead lol), so I think to the game it counts as the battle not happening, so the animation does not play.

So I think the solution to that might be to have the attacker (bomber/fighter) to do a reduced amount of damage instead of doing 0, it might solve the glitchy plane animation as before January 2020 (and in vanilla civ 5) the animations played fine, so I think it has something to do with the change.

I understand fixing issues related to animations isnt a priority here, I'm just asking to be directed to the files related to the mechanics of air interception so I can work on it myself, as the new weird half animation is really weirding me out, thanks in advance.

**Comment by RecursiveVision** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/issues/6812

Try using ilteroi's fix first - just noticed he had posted this myself.

**Comment by yyEdge** [comment]
ok thanks, will test it out

**Comment by yyEdge** [comment]
> 
> 
> #6812
> 
> Try using ilteroi's July 27 fix first - just noticed he had posted this myself.

It seems fixed, thanks!
