### ISSUE TITLE
patch release july 29

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6844]
so, here's another patch which includes almost all fixes and improvements. goes on top of the 6/19 release, not savegame compatible.

[Release_8ceccef620.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/4997407/Release_8ceccef620.zip)

unfortunately there is still no fix for the crashes that some people experience. the debugging symbols (PDB) are included in the zip, so i'm still hoping to get a usable callstack log. but ideally one of you guys can try and run the game in windbg or the visual studio debugger?

**Comment by paramenides** [comment]
Ilteroi any chance you can put this in the installer?

**Comment by cdanger341** [comment]
@ilteroi I got the debugging tools installed but I'm going to need a little more assistance and description to understand how to utilize them to get the call stack log to populate properly. I have the PDB file in the same location as the .dll. What do I need to do to get the debugging tools and Civ 5 to interact and utilize the PDB file?

**Comment by ilteroi** [comment]
well the basic workflow would be:

* start a new game
* before ending the first turn, start windbg and attach to the civ5 process
* probably you have to to set the symbol path manually [as described here](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-sympath--set-symbol-path-)
* wait for the crash, you should end up in the debugger
* type "!analyze -v" and post the result

**Comment by Zanteogo** [comment]
> Ilteroi any chance you can put this in the installer?

If not, could it be indicated as to exactly where someone would put these files? The whole Vox package is like 8 main folders and a bunch of sub folders. This update contains two files, one a .dll and a .pdb file without any indication as what or where to put them. 

Probably obvious, really obvious to you veteran moder's, But for us simple end users..

**Comment by ilteroi** [comment]
well the dll goes replaces the dll of the same name in the community patch folder. and the pdb goes next to it.

**Comment by ilteroi** [comment]
uh, i'm on the road right now. you might need to use the 'g' command

**Comment by LoneGazebo** [comment]
@cdanger341 if civ is locking up when you start the debugger, that typically means you have a breakpoint set in the debugger and that breakpoint is triggering - there should be an arrow appearing on screen next to a red dot, which shows you where the DLL is currently 'at' in its process. You can advance the DLL with the play button at the top, or remove the red circle to stop breaking at that point.

**Comment by cdanger341** [comment]
I think when I attach the debugger to the Civ5 process it is automatically triggering a breakpoint. I'll play around with it more later and see if I can capture a crash.

**Comment by LoneGazebo** [comment]
You can view all active breakpoints in the bottom of the debugger in the 'Breakpoints' tab - delete any breakpoints you see there and see if that helps.

**Comment by bigcat88** [comment]
Type g in command window. It is standard break after attaching

**Comment by cdanger341** [comment]
Thank you, @bigcat88. I am using Windbg because I don't have Visual Studio.

**Comment by LoneGazebo** [comment]
Ah I didn't realize you weren't in VS - you should really try VS

**Comment by cdanger341** [comment]
@LoneGazebo I probably should, but my modding/coding days are long past. I'm trying to play catch-up now because, selfishly, I really want to be able to play VP Civ 5 again and this consistent crash has kept me from being able to enjoy the latest version of the mod. You have been doing such an amazing job at all this, and I cannot thank you enough for the sweat and hours that have gone into this.

**Comment by LoneGazebo** [comment]
well if it is any consolation we're doing our best to root out the crash. 

VS installation isn't too tough, it's worth the effort.  Worst part is the 8 million VS redistributables that'll appear in your programs list :)
