### ISSUE TITLE
CTD 

### ISSUE THREAD

**Issue by yyEdge** [LoneGazebo/Community-Patch-DLL#6845]
_1. Mod version (i.e Date - 6/19):_ 6/19 with July 29 patch

_2. Mod list (if using Vox Populi only, leave blank):_ 
Base VP
(over) More Unique Components for VP (v 59)
Advanced Air Units Non-Modded DLL (v 8)
AI - Warmonger Adjustments (v 4)
Enhanced Air Warfare 4VP (V. alpha_3.5)
Enhanced Naval Warfare for Vox Populi (v 1.6)
Wild Weasel Jet Fighter (v 1)
Improved Air Recon (v 1)
Improvement - Pontoon Bridge (v 3)
Ingame Editor (v 39)
JFD's Civilizations - Japan (Tojo) for Vox Populi (v 9)
JFD's Civilizations - Prussia (Frederick) for Vox Populi (v 9)
JFD's Civilizations - United States of America (Roosevelt) for VP (v 7)
Promotion Flags EUI (v 1.1)
Promotions - Extra Cargo (v 5)
Promotions - Heli AirRecon (v 6)
Promotions - Jet Long Range Recon (v 3)
QMMOD (v 1)
Tech - Satellites Reveal Cities (v 10)
Units - No Mechs (v 6)
Units - No Nukes (v 6)
Units - Subs Ignore Borders (v 3)
Yet (not) Another Earth Maps Pack (v 22)

(okay I know this is a long list but it runs fine with VP even with the previous 6/19 Recursive patch so...)

_3. Error description:_ Babylon starts turn and immediately CTD, removed babylon with IGE and no CTD, pretty sure it has something to do with Babylon, not sure if its something new or what though.

_4. Steps to reproduce (optional):_ 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5000801/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[IGE3.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5000804/IGE3.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5000782/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by ilteroi** [comment]
ok, good old division by zero.

unfortunately related to religion, so it doesn't explain the early crashes.

**Comment by yyEdge** [comment]
So is there anything I can do with IGE rn to keep babylon in the game?

**Comment by ilteroi** [comment]
delete their great prophet. but that is mean :)

**Comment by yyEdge** [comment]
I mean... it's either that or thanos snapped, so deleting the prophet would be better xD

**Comment by azum4roll** [comment]
Maybe give them 800 faith to spawn another next turn?

**Comment by Vyyt02** [comment]
Advanced Air Units Non-Modded DLL (v 8)

... I don't know this mod, but the title suggests it has its own DLL??? You cannot have 2 DLL mods active at the same time.

**Comment by yyEdge** [comment]
> 
> 
> Advanced Air Units Non-Modded DLL (v 8)
> 
> ... I don't know this mod, but the title suggests it has its own DLL??? You cannot have 2 DLL mods active at the same time.

Oh it's a non-modded DLL version of a mod that mods a DLL, it worked since 2018 for VP, dont worry haha

**Comment by yyEdge** [comment]
also plus the only thing i actually use from that mod is _one_ fighter and a building, I've cleaned up the rest of the files
