### ISSUE TITLE
6/29 (Iteroi's patch, Tactical AI) - AI not pursuing very vulnerable cities

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6846]
_1. Mod version (i.e Date - 6/19):_
6/29 - DLL from iteroi

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
iteroi, similar to an issue I brought up a while back, here is a new example.

The AI has just declared war, and had an Immortal in not just but two spots 2 spaces away from cities with no walls and no garrisons. When I saw it I panicked, and I'm scrambling for troops...it was the perfect time to sneak attack me.

And both immortals just walked away...

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/88960506-3b821000-d269-11ea-840a-8640636848ca.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
well, that's a tricky situation. they probably didn't feel strong enough to attack ... hard to make the right call in every situation.

**Comment by Stalker012345** [comment]
I agree its tricky, which I why I always try to post specific examples. The "human thinking" here, I have a completely exposed city that I can take in a couple of rounds of fighting....minimal return damage. Even if I can't hold the city, taking it and razing it is a big win.

Even if the city had just walls or a garrison, I could understand the caution... but this city is WIDE open.... to me anytime an AI sees a strength 5 city at pretty much any point in the game with no units around it, it should take a shot at it.

Alright I do have an autosave from a turn or two back so I'll see if I can find the setting.

**Comment by Stalker012345** [comment]
So I tried values of 30 and 10, and loaded the game one turn before war was declared. Neither value worked, the AI activated the same as before. Also for more insult to the injury, both immortals were Drill II...so that city is paper to them right now.

**Comment by Stalker012345** [comment]
Continuing the experiment with a value of 1. This ship failed to take out either the missionary or the TR, which was right in its grasp.

Hehe as you can tell I'm playing pretty darn lean here, I am clearly not ready for a fight, but I'm not getting punished for it.

![image](https://user-images.githubusercontent.com/20593976/89068703-6a66b780-d337-11ea-8046-35b3483f943c.png)

**Comment by Vyyt02** [comment]
@ilteroi , when you give suggestions about which values to fiddle with (I love it btw and I think it is a great way for having things tested by the community), would you also include some basic guidelines about the min, max and how the numbers scale? It is easier to test/pick the right numbers, when we know if increasing or decreasing the number makes AI bolder or if, for example, the number is multiplied by 100, so that we choose a smaller or bigger step/offset. Or what happens if the number goes negative. Thanks!

**Comment by ilteroi** [comment]
well it was just a guess ... maybe this is the wrong lever.

anyway the way it works it, AI compares friendly and enemy power in the area around each city.

if the ratio is greater than 100+DOMINANCE_PERCENTAGE they consider the zone as friendly dominated.
if the ratio is lower than 100-DOMINANCE_PERCENTAGE they consider the zone as enemy dominated.
if the ratio is in between, the zone is contested.

then they will adapt their strategy based on that, ie attack or withdraw.

**Comment by Stalker012345** [comment]
I'll just note that I left that value at 1 for all of my last game, and I really haven't noticed ANY difference in how the AI behaviors, I wonder if that value is actually working.
