### ISSUE TITLE
AI needlessly exposing settler to be taken during war

### ISSUE THREAD

**Issue by RhysDeAnno** [LoneGazebo/Community-Patch-DLL#6847]
_1. Mod version (i.e Date - 6/19):_
6/19-2 with the 7/29 DLL patch

_2. Mod list (if using Vox Populi only, leave blank):_
Really Advanced Setup, only to ban Morocco + Siam

_3. Error description:_ 
I am doing an ancient war to pressure the AI on Deity difficulty. I currently have its settler's options constrained and its warrior under mild threat. The AI's response to my question is less than fantastic, exposing its settler to immediately be taken, in spite of having clear vision on the capturing warrior beforehand.

_4. Steps to reproduce (optional):_
Load the attached save, end the turn

![Settler1](https://user-images.githubusercontent.com/47321731/89013930-c2270380-d2e2-11ea-9a8d-ffbfca962ee2.jpg)

![Settler2](https://user-images.githubusercontent.com/47321731/89013951-c94e1180-d2e2-11ea-89e5-e7299a1d3c47.jpg)

[Settlers Exposed.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5005829/Settlers.Exposed.zip)

**Comment by ilteroi** [comment]
yeah, that is a known stupidity, the settler moves first, thinks the plot is safe because of the warrior, but then the warrior moves away.

**Comment by ilteroi** [comment]
fixed & pushed

not too well tested though. will be out for a few days

**Comment by Stalker012345** [comment]
So I think my issue is a result of this fix.

With one pathfinder I have completely pinned in this settler, even though it could just escort it out with a warrior.

![image](https://user-images.githubusercontent.com/20593976/89073127-82dad000-d33f-11ea-9409-3fd2314347e8.png)

**Comment by Stalker012345** [comment]
Hehe well and then after penning it for like 8 turns it got brave after get a few more units. And by brave I mean stupid... yoink!

![image](https://user-images.githubusercontent.com/20593976/89073385-00064500-d340-11ea-908f-7e013f43dad7.png)
