### ISSUE TITLE
What causes an Access Violation in CvDllGame::CvDllGame?

### ISSUE THREAD

**Issue by iskaandismet** [LoneGazebo/Community-Patch-DLL#6848]
Hello fellow Civ 5 DLL modders, I'd like to ask a Visual Studio related question:

what causes this crash? Or is it undiagnosable?

![Untitled](https://user-images.githubusercontent.com/40811773/89063631-7e5de980-d336-11ea-9f8c-3c3ebe5dee23.png)
![Untitled2](https://user-images.githubusercontent.com/40811773/89063639-8158da00-d336-11ea-83a1-5a793880b38f.png)

**Comment by bigcat88** [comment]
can you post a savegame? Maybe it is reproducible...

**Comment by LoneGazebo** [comment]
without the PDB, typically a crash in gamelock is a LUA crash... @ilteroi ?

**Comment by iskaandismet** [comment]
Woops, for context, this is my own mod, own DLL, own PDB. So this would probably be a lua crash then?

**Comment by iskaandismet** [comment]
[Crashdump and DLL and PDB.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5008510/Crashdump.and.DLL.and.PDB.zip)

**Comment by LoneGazebo** [comment]
Likely lua yeah

**Comment by iskaandismet** [comment]
So is there any way to further diagnose it, or just turn things off one by one and hope for the best?
