### ISSUE TITLE
6/29 (Feature Request) - Update Combat Tooltip to explicitly note "Mounted Archery"

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6849]
_1. Mod version (i.e Date - 6/19):_
6/29

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The spearmen promotion is a 33% bonus against mounted units. However, against skirmishers it notes it as "+33% vs archery units".... which isn't fully correct (no bonus vs archers).

Just to make it crystal clear, can we update the tip to either say "+33% vs mounted archery" or "+33% vs mounted"

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/89068509-f5937d80-d336-11ea-8568-f773fb956376.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
the text is auto-generated based on the combat class of the unit, which is technically Archery...

**Comment by Stalker012345** [comment]
Its also "technically" mounted :)

If it can't be changed I understand, not all features can be done!

**Comment by RecursiveVision** [comment]
It would be nice if all this was handled in the DLL instead of in LUA. Maybe I can work on that when I get back.

**Comment by Mileslewis** [comment]
UPDATE Units SET IsMounted = '1' WHERE CombatClass = 'UNITCOMBAT_ARCHER' AND Moves >= 3 AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );

Is what sets them to mounted, perhaps this could do with a check that range=1 as well so that any 3 move archers are not counted?

**Comment by azum4roll** [comment]
That's weird. The promotions check their range instead of moves.
