### ISSUE TITLE
Wrong label for city-state revolution

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#685]
I got a notification saying that citizens of ***The Ottomans*** are revolting against Ottomans. When I clicked on the notification, it took me to the city state of Mombase which was allied to Ottomans.

(playing version 9/27 - sorry if this has been already fixed) (no-EUI)

**Comment by LoneGazebo** [comment]
Fixed. Was a 2 instead of a 3.
G
