### ISSUE TITLE
6/29 - Combat Tooltip Error

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6850]
_1. Mod version (i.e Date - 4/17):_
6/29 (Iteroi DLL)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So this skirmisher I am attacking (not to be confused with the skirmisher I am attacking with) should be getting a -20% penalty for the hill that its on, but its showing the +40%. If the CS is accurate, than that means the unit is actually receivng a +50% bonus. The only way I can see that is it had another -20% bonus laid on top. I am wondering then if the skirmisher is receiving both its +40% bonus and -20% penalty at the same time.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/89069416-b5cd9580-d338-11ea-9826-2b3a0b7442bf.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
>should be getting a -20% penalty for the hill that its on

why?

**Comment by sgwicks** [comment]
> why?

Aren't the skirmisher line supposed to get -20% CS from Rough Terrain, and +40% on Open Terrain? I'm seeing the same issue on jungle tiles as well, though I didn't do any calculation to see if it was actually affecting strength or just a visual bug.

**Comment by Stalker012345** [comment]
As sgwicks said, skirmishers are supposed to get -20% CS in rough terrain.

**Comment by LoneGazebo** [comment]
ah yes, I recall. I'll see if there's a dupe in the code.
