### ISSUE TITLE
6/29 - Combat Tooltip Error (Embarked Units)

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6851]
_1. Mod version (i.e Date - 4/17):_
6/29

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This one looks straightforward. The embarked unit in this case is not adjusted its CS for its promotion (which is intended). However, the tooltip suggests that it should be.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/89069749-5e7bf500-d339-11ea-8af2-9a60f9456850.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi may need to resolve his unit changes with CS changes.
