### ISSUE TITLE
Missing Changes

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6852]
@LoneGazebo Your merge only functioned for (most of) the files that I changed and no one else did. Changes are missing from all of these files (from what I can tell so far):

AddDefines.sql (City-State Diplomacy)
Gameplay.sql (City-State Diplomacy)
Pineappledan's changes to his Israel civ
CustomMods.cpp
CvCity.cpp
CvCity.h
CvDealAI.cpp
CvDiplomacyAI.cpp
CvDiplomacyAI.h
CvEspionageClasses.cpp
CvFlavorManager.cpp
CvFlavorManager.h
CvGlobals.cpp
CvGlobals.h
CvGrandStrategyAI.cpp
CvHomelandAI.cpp
CvMilitaryAI.cpp
CvMinorCivAI.cpp
CvPlayer.cpp
CvPlayer.h
CvPlayerAI.cpp
CvPolicyClasses.cpp
CvPolicyClasses.h
CvTeam.cpp
CvTeam.h
CvTradeClasses.cpp
CvUnit.cpp
CvVotingClasses.cpp
CvLuaPlayer.cpp
CvLuaPlayer.h

Did you keep a copy of the pre-merge master repository? I can't fix the merge errors myself on my phone so I can only assist in getting the correct versions of the files.

To clarify, ilteroi did not merge my changes into drk because they contained database changes (and it's more difficult to get a patch released if it contains database changes...)

**Comment by RecursiveVision** [comment]
If you didn't keep a copy of the repository, there are recent backups in the ole and diplomacy branches (although ole was not fully up to date, and diplomacy also contains additional untested changes that could cause crashes).

That said, I can give instructions on how to re-merge all of my changes. I would do a pull request but that isn't really an option without a computer.

**Comment by LoneGazebo** [comment]
I merged master directly into my changes - are you looking at both of my 7-31 pushes? I had changes from those files in there.

**Comment by LoneGazebo** [comment]
I'll do another cross-compare against diplomacy and drk/ole, make sure I'm looking at clean code.

**Comment by LoneGazebo** [comment]
(for what it is worth, I've run two test games on this DLL with no hitches so far)

**Comment by RecursiveVision** [comment]
@LoneGazebo I looked at both pushes: according to Github, the second one just fixes the missing WonderPopup.xml files.

The first one is missing all of the changes from certain files, such as:
- CvEspionageClasses.cpp
- CvGlobals.cpp/h
- CustomMods.cpp

And for others (most of the files listed above) the problem is that you or ilteroi also made changes, which overwrote mine.

**Comment by RecursiveVision** [comment]
@LoneGazebo This point in the repository's history contains all of my changes (except the untested memory rework), and all of ilteroi's changes up to and including "performance improvement for tactsim" in the drk branch, but not any of his changes after that.

**Comment by RecursiveVision** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/tree/f5b07c3d927f00bd4fb75edfa44edf9a7a442ddb

**Comment by RecursiveVision** [comment]
So from the point I just linked, the following drk commits would need to be merged:

Commits on Jul 31, 2020
fix a crash …

Commits on Jul 30, 2020
fix deep water embarkation

Commits on Jul 29, 2020
use latest stackwalker

fix resource accounting …

Commits on Jul 28, 2020
embarked unit defense is base combat strength …

Commits on Jul 27, 2020
more aggressive pillaging of strategic resources …

fix cvcity serialization

Commits on Jul 23, 2020
fix AI envoys and merchants stuck on a stolen plot next to a city

Commits on Jul 22, 2020
fix trade path cache update …

Commits on Jul 21, 2020
work on military approach estimation

The changes from this commit can be ignored:
Merge remote-tracking branch 'remotes/recursive/merge-fix' into drk

**Comment by RecursiveVision** [comment]
...and then your own changes would need to be merged.

**Comment by RecursiveVision** [comment]
@LoneGazebo My review of the redux redux commit (a lot better, but still a few things missing):

**Problem 1**
Changes to the following files are still missing:
- AddDefines.sql (City-State Diplomacy folder)
- Gameplay.sql (City-State Diplomacy folder)
- Pineappledan changed 2 of his Israel civ files

For these 4 missing files, you can grab the version from the ole branch. The Various Fixes & Improvements commit in the ole branch history indicates the file paths for all of them.

**Problem 2**
The change to CvCityCitizens.cpp in the redux redux commit may not be intended - I didn't change this file, so make sure it's working as intended.

**Problem 3**
My changes to CvHomelandAI.cpp are still missing - I removed the obsolete SETTLER_MOVE_ON_START option. The removal from every other file was successful. I suggest either a cross-compare between CvHomelandAI.cpp in the ole and drk branches, or simply removing the SETTLER_MOVE_ON_START checks manually.

**Problem 4**
In CvUnit.cpp, changes I made to culture bomb logic (using the new STOLEN_TILE_BASE_WAR_VALUE global) are missing. These changes are supposed to be between lines 12739 and 12832. My other changes appear to have been merged successfully.

**Problem 5**
Also in CvUnit.cpp, verify that the changes in line 15884 onwards are intended and not the result of a merge error - they're not mine.

**Problem 6**
Line 12780 of CvVotingClasses.cpp, involving a valuation change based on # of City-State allies, was reverted between your first redux commit and this one. Verify that this is intended and not the result of a merge error.

**Problem 7**
In CvDiplomacyAI.cpp, a few lines were accidentally reverted to an earlier version at some point.

Line 6684 should read: 

```
viApproachWeights[MAJOR_CIV_APPROACH_WAR] += bWantsOpportunityAttack ? (viApproachWeightsPersonality[MAJOR_CIV_APPROACH_WAR] * 2) : viApproachWeightsPersonality[MAJOR_CIV_APPROACH_WAR];
```

Line 6711 should read the same as line 6684.

Line 7657 should read:
```
if (GetStateAllWars() != STATE_ALL_WARS_LOSING && !GetPlayer()->IsEmpireUnhappy() && !bWeLostCapital && GetPlayer()->GetCulture()->GetWarWeariness() < 10 && eLoopWarState != WAR_STATE_DEFENSIVE && eLoopWarState != WAR_STATE_NEARLY_DEFEATED)
```

**Problem 8**
@ilteroi's most recent commit (fix a crash) changed EnemyUnitPanel.lua in EUI Compatibility files but that change does not appear to be reflected in the master branch (I think you overwrote the drk version with the master version) - so I'd make sure you merged that correctly.

Also, as an LUA file, other EnemyUnitPanel.lua files may need to have an identical change performed - the 43 Civs version, for instance?

Everything else appears to be in order.

**Comment by RecursiveVision** [comment]
Also I noticed you made a few changes to diplomacy AI in your first merge commit - I also made over 8000 changes to the file according to Github. Although I didn't see yours removed when I looked through the file, you might want to verify that they're there.

**Comment by LoneGazebo** [comment]
Thanks for the write up.  Yes my Diplo changes were minor. I’ll take a look at the missing merge content this weekend. Cheers!

**Comment by RecursiveVision** [comment]
Np - I shall return to my vacation now, see you in a while. :)

**Comment by RecursiveVision** [comment]
Okay, NOW I've caught them all (probably).

**Comment by LoneGazebo** [comment]
Alright, all merged up now. I think!

**Comment by LoneGazebo** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/commit/21235346ccac5d1d4ed947bd64535acdcdeeaa61
