### ISSUE TITLE
Promise not to spy not working

### ISSUE THREAD

**Issue by Zanteogo** [LoneGazebo/Community-Patch-DLL#6853]
_1. Mod version (i.e Date - 4/17): 6/29

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:  If you promise the AI you will not spy anymore, the promise is not being tracked. You can keep spying and it will act like it the promise was never made. 

_4. Steps to reproduce (optional):_

**Comment by RecursiveVision** [comment]
I must have broken something when I fixed a different bug in caught spy discussion logic. At least this one's minor - just a small opinion hit isn't being applied. Someone else will have to fix this one.

**Comment by RecursiveVision** [comment]
@Zanteogo If war is declared, spy promises are cancelled - if that's what happened, it's intentional.

**Comment by Zanteogo** [comment]
I'm 90% sure this was before war, though we have been at war in past. Will update if comes up again.

**Comment by RecursiveVision** [comment]
Well let me know if it recurs.
