### ISSUE TITLE
Cannot trade cities back to owner

### ISSUE THREAD

**Issue by Zanteogo** [LoneGazebo/Community-Patch-DLL#6854]
Using current plus newest patch.

Seem I am again unable to trade fully healed cities back to their original owner, even for free.

https://i.ibb.co/Jxk586d/impossible.jpg

**Comment by LoneGazebo** [comment]
The AI will not always want a city back.

**Comment by Zanteogo** [comment]
Why would a civ not want it's fully healed capital back? Is it a random thing or is it weighed against something?
Seems like a capital should have large worth?

**Comment by RecursiveVision** [comment]
I think this is fixed now?
