### ISSUE TITLE
Cannot Stop Razing City

### ISSUE THREAD

**Issue by Zanteogo** [LoneGazebo/Community-Patch-DLL#6855]
_1. Mod version (i.e Date - 4/17): _
6/19 plus current patch

_2. Mod list (if using Vox Populi only, leave blank):_
R.E.D. - Smaller Landmarks (v.5)
R.E.D. Modpack (v.27)

_3. Error description:_ 
Razing city, want to stop, click on "stop razing", game asks "halt razing process are you sure?" Click yes. But still keeps razing. 

_4. Steps to reproduce (optional):_
See above. 

---------------------------

Game Save:
https://gofile.io/d/NIu5aU

**Comment by RecursiveVision** [comment]
Ever since that ability was added this keeps happening...

**Comment by ASCII-Guy** [comment]
Whoops... glad it's been taken care of now.
