### ISSUE TITLE
Conquistador can't found a new city

### ISSUE THREAD

**Issue by CheesyFeetUK** [LoneGazebo/Community-Patch-DLL#6856]
_1. Mod version 6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Conquistador should have a special ability to found a new city on a continent that does not contain the Spanish capitol.  However there is no found city button to do this and the shortcut B does not work either. Also all the steps shown on the thread here have been tried - https://forums.civfanatics.com/threads/conquistadors-spy-spawning.661296/

_4. Steps to reproduce (optional):_ Load up attached save and check out the Conquistador unit.

[Conquistador Isabella T320.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5012039/Conquistador.Isabella.T320.zip)
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Vyyt02** [comment]
Don't know if it helps, but as stated on CivFanatics, I tested it on the April version and still worked.

**Comment by ilteroi** [comment]
old bug
