### ISSUE TITLE
Ranged naval units lose all movement after firing

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#6858]
_1. Mod version (i.e Date - 4/17):_
5.6.19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Ranged naval units move in, fire shot(s), lose all movement points.

One of the prior versions gave ranged naval units the capability of "move in for a shot, fire the shot, and then move away". But this current version zeroes out the remaining movement points after the shot is fired. Any possibility of going back to the prior capability?

A notable problem with the current arrangement is that ranged naval units have a lower defense rating than their melee counterparts. (For instance, Battleships [60] are easier to kill than Destroyers [75].) If you insist on keeping the current arrangement, would you please consider improving the defenses for ranged naval units?

_4. Steps to reproduce (optional):_
Ranged naval units move in, fire shot(s), lose all movement points.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
What unit are you using? Move on attack only exists until the Frigate. From Frigate on, you stop when you shoot, unless you have logistics.

So if its frigate or higher, this is intended behavior.

**Comment by Vyyt02** [comment]
It's intended, you should protect your ranged with melee in the front. If you want to revert back to shoot-n-scoot from last year, copy paste the sql adding the MOVE_AFTER_ATTACK promotion from a Galleas or Droning and add it to each ranged ship you want to apply it to (if you don't know how, I will write it for you when I get to my computer, I'd probably screw up if I wrote it from memory).

**Comment by briantjack** [comment]
> What unit are you using? Move on attack only exists until the Frigate. From Frigate on, you stop when you shoot, unless you have logistics.
> 
> So if its frigate or higher, this is intended behavior.

Even units with the Logistics promotion stop after the second shot is fired.

**Comment by RecursiveVision** [comment]
@briantjack Intended

**Comment by briantjack** [comment]
> It's intended, you should protect your ranged with melee in the front. If you want to revert back to shoot-n-scoot from last year, copy paste the sql adding the MOVE_AFTER_ATTACK promotion from a Galleas or Dromon and add it to each ranged ship you want to apply it to (if you don't know how, I will write it for you when I get to my computer, I'd probably screw up if I wrote it from memory).

I appreciate the work-around. I'll see about implementing it.

**Comment by briantjack** [comment]
> @briantjack Intended

Were WW2 battleships easier to kill than WW2 destroyers?

**Comment by RecursiveVision** [comment]
Balance usually trumps realism.
