### ISSUE TITLE
Air units don't work in city at unit cap

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#6859]
_1. Mod version (i.e Date - 4/17):_
June 19th (5.6.19)

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi
Community Patch Mod Compatibility
XCOM for VP
Pontoon Bridges for VP

_3. Error description:_ 
Cities without Airports have an air unit capacity of 2. When I station two air units in such a city, I can use neither air unit for combat; instead, I have to move one of the air units to a different city before I can use the other for attacking. I should be able to use them both in combat, right?

I haven't tried this yet for a city with an Airport (which raises the city's air unit capacity to 6).

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
old bug
