### ISSUE TITLE
InGame.lua

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#6860]
_1. Mod version: 06-19-02

_2. Mod list (if using Vox Populi only, leave blank): 4UC and custom civs

_3. Error description:_ 
Lua log gives this error every turn:
Runtime Error: E:\...\Sid Meier's Civilization 5\MODS\MODS\(1) Community Patch\Core Files\CoreLua\InGame.lua:941: bad argument #1 to 'ipairs' (table expected, got nil)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/5017231/Lua.log)

**Comment by pineappledan** [comment]
I believe this is the cause of an error I am having with a notification for a custom civ that concatenates text onto the notification if certain criteria are met.
sText = 'Hello'
if X == 1 then
  sText = sText .. ' World'
end
The "Hello" only appears ingame; but no "World", if the appropriate condition is met.

**Comment by azum4roll** [comment]
Is InGame.lua here to stay? It didn't exist until a few versions ago, and it messes up modpacks. (Most people don't know how to fix it)
