### ISSUE TITLE
Merge and Go

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#6861]
@ilteroi,

Master is now merged up with your and @RecursiveVision's changes. Please update to this DLL set.

I'm getting a weird endless loop issue on reloading saves. Anyone else on this one?

G

**Comment by ilteroi** [comment]
sorry but this is very suspicious ... four commits to merge but no actual merge commit? 34k lines changes in diplo AI? what is going on?

**Comment by RecursiveVision** [comment]
I didn't make 34000 lines of changes for this version - did you merge the diplomacy branch? I'll investigate.

**Comment by RecursiveVision** [comment]
Yeah, the latest changes in diplomacy are not ready for release yet @LoneGazebo. As I said in #6833 that has a ton of changes to memory and I haven't tested it yet - so crashes or serialization errors to be expected.

If you want to test and debug that, be my guest, but you'll be at it a while. :)

Only CvDiplomacyAI.cpp & CvDiplomacyAI.h are changed, though - so you can fix by reverting to the files in the point I mentioned in #6852 and then re-adding:

1) Your changes to IsCloseToSSVictory
2) The missing line changes I mentioned in #6852 

I'll look at the rest of the commit to make sure nothing else is missing...

**Comment by RecursiveVision** [comment]
The point in time I'm referring to is the one I linked in the Missing Changes issue thread - grab the CvDiplomacyAI files from there, follow steps one and two, and should be good to go: https://github.com/LoneGazebo/Community-Patch-DLL/tree/f5b07c3d927f00bd4fb75edfa44edf9a7a442ddb

**Comment by RecursiveVision** [comment]
Rest of your merge commit seems to be good, except:

- The changes to the EUI Compatibility Files version of the EnemyUnitPanel.lua file should be ported over to No EUI Compatibility Files and 43 Civs Versions - you only merged ilteroi's most recent changes to the EUI Compatibility Files version - the others actually had a fix reverted in this commit.

- Can you check if iUnitBonusXPTimes100 in CvUnit (in changeExperience, I think) is multiplying by getExperiencePercent, not adding? I think that bugfix might've been reverted, but I'm not sure.

**Comment by LoneGazebo** [comment]
I misunderstood your post re: diplo branch. I’ll revert those diplo changes and add in my fix.

**Comment by RecursiveVision** [comment]
@LoneGazebo Also, all 12 of my issues seem to be addressed except for this one - could you add this code to CvGame.cpp at line 6723?

Muchas gracias. 🙂 
```

if (IsAIAggressiveMode())
{
   return true;
}

```

**Comment by LoneGazebo** [comment]
>Can you check if iUnitBonusXPTimes100 in CvUnit.cpp (in changeExperience, I think) is multiplying by getExperiencePercent, not adding? I think that bugfix might've been reverted, but I'm not sure.

Supposed to be adding, right? I'm confused.

**Comment by RecursiveVision** [comment]
@LoneGazebo Should be XP + Bonus XP

Bonus XP = XP * experiencePercent / 100

**Comment by ilteroi** [comment]
well, now we have a fifth commit with another 30k lines of changes.

i do not trust this at all ... there must be a better way?

**Comment by LoneGazebo** [comment]
@ilteroi I merged @RecursiveVision's test build of DiploAI, instead of the stable stuff. It's all good now. :)

**Comment by LoneGazebo** [comment]
@ilteroi unfortunately my absence meant no one was merging into master, so a manual forced merge was necessary. Also @RecursiveVision's IDE likes to shift around brackets, so I think a lot of the changes are just brackets being indended/unindented.

**Comment by RecursiveVision** [comment]
+34k, -30k? There seems to be a large difference in line changes between the merge and the reversion.

I can't see the full changelist because the diff is too large, so I can't confirm that all is as it should be...maybe you could squash the commits? I think that'd be more reassuring to ilteroi...and myself :) @LoneGazebo 

Also, I think you misinterpreted the CvUnit.cpp and CvGame.cpp issues:

CvUnit: Looks like it wasn't reverted earlier, but you reverted it manually. :) My bad for not being clear - the + should be changed back to a *.

CvGame: The added check goes below the IsAIPassiveTowardsHumans() check, not above it (that's why I specified the line number)...however a check later on will prevent that from mattering, so no biggie.

The other EnemyUnitPanel.lua files are still unchanged - are you only updating the EUI version?

**Comment by LoneGazebo** [comment]
@RecursiveVision I merged against @ilteroi's latest and my versions are identical to his changes now.

See image below, this is what the difference between your experimental and your stable DiploAI look like.

Fixed the two merge issues.

![image](https://user-images.githubusercontent.com/7849458/89318958-216b7780-d645-11ea-8989-8d1713e20c20.png)

**Comment by RecursiveVision** [comment]
So are my changes EXCEPT the experimental ones merged?

**Comment by LoneGazebo** [comment]
Yes, 100%

**Comment by RecursiveVision** [comment]
Alright then :)

Still think squashing the commits may help, though - otherwise the diff won't be visible in the history.

**Comment by LoneGazebo** [comment]
I fear and loathe squashing commits, I've lost many a change to squashes over the years :)

Look on my epic commits, ye mighty, and despair.

**Comment by RecursiveVision** [comment]
Ha, fair enough. This merge has been complicated as it is...

Then, just to be absolutely clear:
1) DiplomacyAI files were reverted back to the pre-experimental point I linked;
2) Your fixes were added;
3) My line changes listed here were added

![Screenshot_20200804-123155_Adblock Browser](https://user-images.githubusercontent.com/66801010/89320015-eec67c80-d64e-11ea-8589-5ef5225f48d5.jpg)

Is that correct?

**Comment by RecursiveVision** [comment]
The line numbers at the 50000 point may be different if you added in your own fix before those changes...

**Comment by LoneGazebo** [comment]
I'll double check the lines above.

**Comment by RecursiveVision** [comment]
If all is well, then it looks like all of my changes are correctly merged.

**Comment by ilteroi** [comment]
guys i'm afraid you're do

**Comment by ilteroi** [comment]
please take a step back and reconsider.

it's just not possible for a merge to have so many conflicts when one side hardly changed. i've heard enough now about strange merge errors and manual merging and lost changes to suspect that there is a problem in the workflow which makes everything harder than it needs to be.

i don't know exactly what you are trying to do, but it seems you are in vicious cycle ... your "manual merges" hide the origin of changes and create spurious reformatting changes. when you later try to merge again, git does not know about the manual changes and sees them as conflicts, making automatic merging harder.

i think it would be best to reset the master branch to  f31c9311e0c56a48182f5c5319a261974ea0cca0 and try again.

**Comment by LoneGazebo** [comment]
@ilteroi the issue isn't conflicts, it's just quantity of edits to that file - see the view of the manual merge above, DiploAI just has a bunch of revisions in-between @RecursiveVision's stable and unstable versions. The workflow problem we've encountered here is because you and he have two separate branches, but those branches were not synced with each other - in some ways your was ahead of his, and in other ways his was ahead of yours. You had some shared fixes, but I had to go to an earlier version of his commits to get his stable content, and then port yours on top of it to make sure I hadn't missed anything.

I don't enjoy manual merges, but sometimes it is the only way to safely guarantee that changes are not being missed or overwritten.

**Comment by LoneGazebo** [comment]
We could rebase master if we want to 'clean' the repo, but that's something we need to think on.

**Comment by RecursiveVision** [comment]
@LoneGazebo Two of the revised lines were messed up, but everything else seems okay.

Replacing lines 6685 and 6712 with:
```
viApproachWeights[MAJOR_CIV_APPROACH_DECEPTIVE] += bWantsOpportunityAttack ? (viApproachWeightsPersonality[MAJOR_CIV_APPROACH_DECEPTIVE] * 2) : viApproachWeightsPersonality[MAJOR_CIV_APPROACH_DECEPTIVE];
```

Will resolve the error...

Is there a reason you removed the #if defined(MOD_DIPLOMACY_CIV4_FEATURES) checks in  the IsVassal()/IsMaster() functions? Were they causing issues?

**Comment by RecursiveVision** [comment]
ilteroi proposed starting with a new repository to clear the very extensive history and reduce repo size in #6620.

I think this could do some good, there's a lot of clutter, and it takes me a long time to download the repo. Naturally I think the current repository should be preserved as an archive if that's done.

**Comment by LoneGazebo** [comment]
The if/defined checks create unreachable code so I removed them. 

I’ll look at those two lines. 

And sure, we can create a new repo at some point soon.

**Comment by RecursiveVision** [comment]
That's odd - the compiler reported no errors for me, and I thought CIV4_FEATURES was always defined in the build. Strange.

Also, on another but related topic, there are close to 200 open issues again, some users have complained that issues on Github don't get seen or get a response, and it does seem like some things are getting overlooked.

Furthermore, to avoid tedious merges like this one (albeit ilteroi and I being away complicates things) I feel like there might be a better way for us to coordinate in general. Any ideas?

A comprehensive, stickied tutorial on the forum on how to submit bug reports would be a good start - a lot of people don't know how to fully enable logs, for instance.

**Comment by RecursiveVision** [comment]
Maybe us "core devs" could use some kind of centralized chat to communicate, since we make the vast majority of changes? Github is great for code and bug reports, but things seem to slip between the cracks, branches don't get synced up, etc. We could be better coordinated.

Just an idea. :)

**Comment by azum4roll** [comment]
Maybe it's time for an "official" VP discord server? ;)

**Comment by RecursiveVision** [comment]
@LoneGazebo Well I see you're addressing the unresolved issues problem 👍 

That said, I still think we could benefit from more communication overall.

**Comment by LoneGazebo** [comment]
@RecursiveVision  I agree I'm hoping to be more active now that life is returning to normal.....

**Comment by RecursiveVision** [comment]
@LoneGazebo I'm happy to hear that! Hope things are well with you and your family now. 😃 

What are your thoughts on some kind of centralized chat we could use to communicate? A Discord server isn't a bad idea if you guys are interested in that...

**Comment by LoneGazebo** [comment]
Discord would be fine with me.

**Comment by RecursiveVision** [comment]
@ilteroi Would using a Discord server to communicate work for you?

I have some experience in running servers - I could set one up when I return if you guys want.

**Comment by RecursiveVision** [comment]
@LoneGazebo When you merge @ilteroi's CTD fix, it modifies peace log format in CvDiplomacyAI.cpp, but I also modified some of that formatting so it won't be directly compatible.

It just adds colons and spaces to make the logs more readable, so not a big deal or anything. :)

**Comment by ilteroi** [comment]
i don't care too much for real time communication, it's too difficult to organize with different timezones

**Comment by RecursiveVision** [comment]
@ilteroi Discord can be used in realtime but doesn't have to be - you'll get notifications when someone sends you a message or mentions you, much like Github, the message is stored serverside, you can respond to it when you get online, and the other person will see it when they get online. So real-time communication and delayed communication like on Github are both viable options - and most people on Discord don't expect an immediate response. It also has email notifications for missed messages, but you can turn those off if you don't like them.

The channel/privacy/notification settings also make it really easy to control how and where people can contact each other to keep things organized.

Part of the reason I like the idea of a VP Discord server is that Discord is the leading communication method for gaming in general, there's already a lot of members on a fan server for VP, and in addition to the forums and Github, I think it would help foster community engagement.

You don't have to join a Discord server if you don't want to, but I think it'd be a good tool both for increased communication amongst each other and amongst the community. I assume it'd make it easier to get feedback when you make changes as well.

**Comment by ilteroi** [comment]
let's try it then

**Comment by RecursiveVision** [comment]
Cool, I'll set up a server when I return...should be in about a week.

**Comment by RecursiveVision** [comment]
@LoneGazebo ilteroi has merged changes and made a few more fixes of his own, so looks like once your changes and his are synced up we're good to go.

**Comment by RecursiveVision** [comment]
@ilteroi Also just to confirm, I looked through your merge changes and you did get the correct version of the file. 👍
