### ISSUE TITLE
Hovercrafts good for nothing

### ISSUE THREAD

**Issue by tu-79** [LoneGazebo/Community-Patch-DLL#6862]
_1. Mod version (i.e Date - 4/17):_
July 29th ilteroi patch

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The hovercraft is not moving properly. It embarks and disembarks losing all the movements, which makes no sense. Also, it cannot shoot while at sea, as if it were an embarked unit. Supposedly, it's a flying unit, and a very slow one at that. The ability to fight on the sea made up for this lack of speed, but it is no longer the case.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@ilteroi I think you modified this?

**Comment by ilteroi** [comment]
as noted, deep water embarkation is broken in the july 29 build. but fixed already.
