### ISSUE TITLE
AI suiciding their siege units

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#6863]
1. Mod version (i.e Date - 4/17): 4/17-2

2. Mod list (if using Vox Populi only, leave blank): Thousands and thousands of mods!!! (sorry, not helpful, useless to post a save, I know)

3. Error description: In my current game as Babylonians I set up a kill zone of a wide arc of defensive units supported by 2 citadels to thin out a huge Mongol army first and then I started slowly advancing on their capital. The Mongols were harassing my flanks with skirmishers and knights nicely, but they kept sending canons to the frontline right in front of my melee. They arrived right next to my melee, shot and my melee took them out the very next turn effortlessly. I think they were trying to damage my own ranged/siege units behind my melee instead of shooting my melee from the safety behind their own line of melee.

Please refer to the attached image - this is at the beginning of my turn after their army thinned out a bit and when I started closing in on Karakorum. You can see the poor canon right next to my tercio. After I kill it, next turn, they will send another canon and park it right next to my tercio again. In the past (even on the same April version), I thought it was an occasional fluke or AI's misjudgment, but this game, it was happening every single turn (sometimes even with 2 canons) during the siege of Karakorum, which took like 10 turns.

![civ5-canon](https://user-images.githubusercontent.com/11929356/89340132-894eac00-d69f-11ea-894b-8ae80dce890a.jpg)

**Comment by RecursiveVision** [comment]
Thousands and thousands of mods? 😬

**Comment by Mileslewis** [comment]
Are you sure they were moving them in and not buying them so they aren't allowed to move them? If they have less/no promotions than their other units it means they bought them.

**Comment by RecursiveVision** [comment]
Old version, though...ilteroi fixes tactical AI issues regularly.

**Comment by ilteroi** [comment]
yeah retry with latest

**Comment by Vyyt02** [comment]
@Mileslewis yes, absolutely sure they moved them in, not buying them.

@RecursiveVision , ok, not thousands, more like 15-ish, mostly QOL and I alter the later eras quite a bit, but you cannot load my saves either way.

Ok, I will will watch this when I update to a newer version. Given my limited time to play and the nature of my epic games, I always fall behind a couple of versions.
