### ISSUE TITLE
Incorrect #if defineds in CvUnit

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6864]
You merged my changes to promotion logic in CvUnit but I had messed up one of the #if defined things.

Inside the CvUnit::AI_promotionValue function there are checks to see if a promotion gives each benefit such as:
	iTemp = pkPromotionInfo->GetCombatPercent();

I moved a lot of these checks around so now the ones inside 
#if defined(MOD_BALANCE_CORE_MILITARY_PROMOTION_ADVANCED)
are not the same as they were before.

Do the benefits checked inside this #if defined need to be the same ones as are listed within the
#if defined(MOD_BALANCE_CORE)
at the top of CvUnit?

**Comment by LoneGazebo** [comment]
Well anything inside an #if defined set will populate as long as the value is defined (which it is) - they only fail to trigger if the populated value is 0 (i.e. if(MOD_BALANCE_CORE))

**Comment by Mileslewis** [comment]
But aren't there some scenarios where #if defined(MOD_BALANCE_CORE_MILITARY_PROMOTION_ADVANCED) is set to 0?

**Comment by Mileslewis** [comment]
I guess I don't really know the reason that certain things were inside 
#if defined(MOD_BALANCE_CORE_MILITARY_PROMOTION_ADVANCED) in the first place?

I only know that I changed which things were in and outside of it.

**Comment by LoneGazebo** [comment]
#if defined will never be set to zero, as it's simply noting the _existence_ of the variable.

if(MOD_BALANCE_CORE_MILITARY_PROMOTION_ADVANCED) can however be zero, as it's a variable that can be set to 0 or 1.

G

**Comment by Mileslewis** [comment]
Okay, sorry btw I changed my question before you answered it.

If I'm understanding correctly then:
#if defined(MOD_BALANCE_CORE_MILITARY_PROMOTION_ADVANCED)
is **always** the case so anything inside it will **always** be done so it doesn't matter what comes before the #endif and what comes after.

is #if defined(MOD_BALANCE_CORE) always the case as well?

**Comment by LoneGazebo** [comment]
Yes. That's correct.

**Comment by Mileslewis** [comment]
Okay, I had it in my head that they were to distinguish VP to non-VP.

If it doesn't matter what's inside and out there is no issue.
