### ISSUE TITLE
6/29 - Cannot remove Feitoria when coal appears underneath

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6865]
_1. Mod version (i.e Date - 4/17):_
6/29

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Feitorias cannot be removed, even if a coal appears underneath them and I want to change it to a mine.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/89453410-d45ed280-d724-11ea-8e87-081e2ac263b6.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@LoneGazebo Easiest solution would be to just have them connect resources.

**Comment by LoneGazebo** [comment]
I've fixed the rule for feitorias in owned land - it was an oversight in the boolean logic.
