### ISSUE TITLE
Boarded II

### ISSUE THREAD

**Issue by GLop4** [LoneGazebo/Community-Patch-DLL#6867]
_1. Mod version (i.e Date - 4/17): 6-19)+patch july29

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 
Boarded (I) > -2 moves
Boarded (II) > -4 moves !
Boarded (III) > -4 moves

Intented?
Boarded (III) dropped ? 
____________________________
**(GLop4 is Asterix Rage)**

_4. Steps to reproduce (optional): In Civilopedia

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![boardii](https://user-images.githubusercontent.com/8753808/89517473-054d0f00-d7da-11ea-91f0-3e0179142374.png)

**Comment by azum4roll** [comment]
Is there even a Boarded (III)? Boardside I inflicts Boarded (I) and Boardside III inflicts Boarded (II).

**Comment by GLop4** [comment]
Ok just checked
Boarding Party I inflicts Boarded I (-2moves)
Boarding Party III inflicts Boarded II (-4moves)

PROMOTION_BOARDED_III is unused anymore.

Here is
**promoIcons_Update_Main.sql (rev4)**
to replace **promoIcons_Update_Main.sql (rev3)**
in **MODS\(7a) Promotion Icons for VP\sql**

It fixes the wrong Promo Icon given to Boarded II (-4 instead of -3)

[promoIcons_Update_Main_rev4.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5034401/promoIcons_Update_Main_rev4.zip)
in MODS\(7a) Promotion Icons for VP\sql
