### ISSUE TITLE
Naval stacking

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#6868]
@ilteroi,

What's the possibility of re-enabling embarked unit stacking at sea? The AI is not doing a great job of keeping the seas clear of embarked units, and I'm seeing quite a few failed naval operations due to crowded muster spots. I think let's make it so that naval embarked units can stack at sea again.

**Comment by Vyyt02** [comment]
Pretty pureeezu!!!

**Comment by LoneGazebo** [comment]
As far as I can tell it is as simple as adding a small section to CvUnit::CountStackingUnitsAtPlot:

```
//special rule for land units at sea
				else if (pPlot->isWater())
				{
					//we can embark under naval units, but not other land units!
					if (getDomainType() == pLoopUnit->getDomainType())
						iNumUnitsOfSameType++;
				}
```

**Comment by ilteroi** [comment]
this would change the pathfinder behavior but not the combat simulation. also some logic for operations is affected. the only clean way is to revert all my changes post 6-19.

**Comment by RecursiveVision** [comment]
Even more merge commits? 😬

**Comment by LoneGazebo** [comment]
@ilteroi is the combat simulation making its own checks outside of the pathfinder?

**Comment by LoneGazebo** [comment]
The other change I've made (temporarily, just testing) is to allow embarked units to swap spots. I'm running tests on this now, I'll let you know if this results in wonky behavior. I don't think we'll have to touch the Tactical AI, as the AI should be more capable of getting units moving around this way. The only thing we may need to add back in is logic for escorting at sea.

**Comment by ilteroi** [comment]
yes. cannot use the "official" plot state because it's dealing in hypotheticals.

on a side note, i haven't really seen any feedback related to AI performance on the forum, so i don't have confirmation whether the changes were a step forward.

but for me it seems the mustering could be fixed be simply choosing a different muster plot, which is way easier than going back.

**Comment by LoneGazebo** [comment]
Well, if the only change here is allowing embarked stacks, that should affect a pretty small portion of the tactical AI simulation, right?

**Comment by ilteroi** [comment]
no because it's the difference between one unit per plot or not.

**Comment by LoneGazebo** [comment]
Well, I think the general consensus is that embarked units need to be able to stack, or it simply crowds melee boats too much. I agree, and I think it is worth adjusting.

**Comment by Stalker012345** [comment]
> Well, I think the general consensus is that embarked units need to be able to stack, or it simply crowds melee boats too much. I agree, and I think it is worth adjusting.

I would adjust this statement a bit. I think the general consensus is "people saw no reason to make the change in the first place".

But in terms of "the community has tried iteroi's version and it has reinforced their opinion that stacking should return" ... I think that would be a false statement. I think a sparse section of the community has any real experience with the change to say yeah or nay (I've run several games on it as Portugal, and I've only gotten into one instance where I definitively got to test out how the difference "feels"). I would also bet a lot of the community is holding until they see a new "official version" (aka one with an installer).

So my thought is.... if I had my way, we would not have ever made the change. But we have, and the code is in place. Might as well put it through its paces.

**Comment by LoneGazebo** [comment]
I'd agree if I wasn't already seeing issues with it in AI-v-AI games.

**Comment by ilteroi** [comment]
so what issues are those? i just checked the logs for two games, there is not a single instance of an AI operation timing out because they failed to gather their units. what should i be looking for?

**Comment by LoneGazebo** [comment]
If I can get a better example I’ll save the logs and share it with you.

**Comment by RecursiveVision** [comment]
@ilteroi It's possible that you're encountering no failures because of a lack of AI aggression, and G is encountering them because he's using my diplo changes which should be greatly increasing it.

Also see my most recent comments in the #6861 thread, in particular my question to you.

**Comment by ilteroi** [comment]
ok it seems there is something wrong with army moves. but it affects land operations as well, is not related to naval stacking

**Comment by LoneGazebo** [comment]
Oh good I’m not crazy, just wrong! ;)

**Comment by LoneGazebo** [comment]
@ilteroi https://github.com/LoneGazebo/Community-Patch-DLL/commit/21e1ab112e954e3fdd903969036b09effdfb27c7
This version has the fix to naval stacking I created. All it needs is the tactical tweaks for you for naval embarked units.

**Comment by ilteroi** [comment]
sorry but that is quite a lot of effort and i don't have time for that

**Comment by LoneGazebo** [comment]
@ilteroi don’t have time for that right now, or don’t have time for that period? Former is fine, but latter - I apologize if this reversion is controversial for you, I’m not trying to be.

**Comment by RecursiveVision** [comment]
Judging by how he disappeared, my suspicion is the former - he probably got busy.
