### ISSUE TITLE
Martial Law and Route maintenance (v10-8)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#687]
It seems to me that Martial Law has the wrong value.

Community Balance Patch\Balance Changes\Policies\Honor\Honor.sql
Line: 103
SET RouteGoldMaintenanceMod = '**50**'

**50** should be **-50**

cf. The value of Wagon Trains (Vanilla policy)
< RouteGoldMaintenanceMod>**-50**< /RouteGoldMaintenanceMod>

**Comment by LoneGazebo** [comment]
Ha, yep. That's why it's a test version! :)
