### ISSUE TITLE
7-29 Ilteroi dll patch CTD Quick Speed Turn 8

### ISSUE THREAD

**Issue by jayeye2011** [LoneGazebo/Community-Patch-DLL#6870]
_1. Mod version (i.e Date - 4/17):_

6-19-2 using Release_8ceccef620 7-29 Ilteroi dll patch
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
CTD on next turn during AI processing CvHomelandAI::PlotExplorerMoves() infinite loop
Win 7, Civ 5 [legacy] version, quick speed, tiny pangea, 2 player

_4. Steps to reproduce (optional):_
load turn 8 save file, press next turn will crash unless windbg attached then it will do infinite loop on CvHomelandAI::PlotExplorerMoves.
[Ilteroi  Release_8ceccef620 CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5035925/Ilteroi.Release_8ceccef620.CTD.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
finally fixed

**Comment by jayeye2011** [comment]
Yay!

**Comment by jayeye2011** [comment]
> finally fixed

@ilteroi any chance of you posting a dll that has this fix? I would like to use it in place of the official 6-19-2 release version.

**Comment by ilteroi** [comment]
i think gazebo as about to release a new version anyway

**Comment by jayeye2011** [comment]
@ilteroi Can you tell me if there reason I am seeing CTDs is because I am still using Windows 7. I tried playing on epic speed, standard pangea, 8 players, no ruins, no events, quick movement/combat, transparent diplomacy (my usual settings other than game speed) and I still got a CTD on turn 5 with windbg showing the same infinite loop issue. I know that others including Youtubers Fencka and Milae are able to play 6-19-2 on epic and standard speed respectively without issue and I believe they are using Windows 10. But according to the steam page, Civ 5 is only spec'd to run on Windows Vista & 7, not Windows 8 or 10. Are you and Gazebo are compiling for Windows 10 and testing only under Windows 10 and so maybe that is why you don't get the CTDs in your testing?

**Comment by ilteroi** [comment]
in fact i think the windows version is a factor, yes. although what steam says is irrelevant here.

the crash is due to an invalid iterator. it becomes invalid because an element is removed from the underlying container. apparently in win7 the removal causes a reallocation of the container whereas in win10 it does not. different memory management.
