### ISSUE TITLE
AI spending too much on strategics (too early?)

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6872]
Patch: 6-19-2

I have seen other people talk about this but I can't find any mention of it being changed.

There is almost always at least 1 AI willing to pay 7 or even more gpt for a single strategic right from the start. A large resource tile can get you 30-40 gpt in ancient era which is quite balance breaking imo.

**Comment by RecursiveVision** [comment]
Resource value was adjusted for next version.
