### ISSUE TITLE
Suggestion: Make barrage equal again

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6873]
Accuracy: 
+10% ranged combat strength
+10% ranged combat strength attacking units above 50hp

Barrage:
+5% ranged combat strength
+10% ranged combat strength attacking units at or below 50hp

Generally in combat you want to weaken enemy troops with ranged units and then finish them with melee units as melee units do more and take less damage against low hp units. This means on ranged units accuracy's above 50hp modifier is generally more useful than barrage's below 50hp modifier. This is not a problem as it's still good to have some mix but right now barrage also gives 5% less flat ranged combat strength making it overall considerably weaker than accuracy.

Had to cheat a bit in the promotion logic to get AIs to consider barrage somewhat equal to accuracy because of this.

**Comment by RecursiveVision** [comment]
For some reason, after reading your post, I feel an intense emotional desire to defeat someone in an upcoming election...I believe it is an anger-filled desire! How curious.

You have a point, especially considering units do not apply the unit health penalty to ranged defense anymore. It could be bumped up to 10% IMO.

**Comment by Mileslewis** [comment]
Good luck brother!

**Comment by LoneGazebo** [comment]
I agree.

**Comment by RecursiveVision** [comment]
@Mileslewis Does a bump to 10% necessitate a change to the promotion logic? Since you had to "cheat" to get the AI to value the promotion properly.
