### ISSUE TITLE
Suggestion: Slight buffs to Snow Tiles

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6874]
Snow could be included in god of starts and sky so it would be +1F,+C and +1G from tundra or snow tiles with resources.

Snow could be included in the +Science from Scientific Revolution (Rationalism Policy).

Snow could be included in +Science from Universities or given extra +Science from Research Labs.

Obviously snow would still be bad but I think it would makes sense if snow gave +Science later on in the game as that's what cold places are used for IRL.

**Comment by RecursiveVision** [comment]
I like the idea.

**Comment by pineappledan** [comment]
It's not really a feature request, is it? this is totally doable with current code.

**Comment by RecursiveVision** [comment]
Well, it isn't a bug, an AI issue or an optimization. By process of elimination it's a feature request. :) 

But yes, it is.

**Comment by pineappledan** [comment]
![image](https://user-images.githubusercontent.com/33136027/91213778-53fe1280-e6cf-11ea-8c28-4858c99fb2e8.png)

Just wanted to put this out there, because not getting a yield bonus on all of this broke my heart. 
I didnt even bother taking the tundra pantheon, because I knew it wasn't going to cut it without the snow tiles

**Comment by pineappledan** [comment]
I have been using the Communitu map in my tests lately.

The way that map style mixes snow and tundra tiles, and likes to make large stretches of continent into tundra/snow mixtures on the default settings makes this proposed change not only feel desirable, but necessary.

I'll make a pull request for the changes to the pantheon and university this afternoon. merge or discard at your leisure

**Comment by pineappledan** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/pull/7649
