### ISSUE TITLE
Request: building forts in unworkable vassal territory 

### ISSUE THREAD

**Issue by Skidizzle** [LoneGazebo/Community-Patch-DLL#6875]
_1. Mod version (i.e Date - 4/17):_
the initial 6-19 VP

outside the workable city radius if at all possible
And I guess by extension chopping as well

![20200808111049_1](https://user-images.githubusercontent.com/20171478/89713848-70c4e700-d968-11ea-8b1b-06f9705d032d.jpg)

**Comment by RecursiveVision** [comment]
Disagree. It's still the vassal's land.
