### ISSUE TITLE
CvTacticalAI.cpp

### ISSUE THREAD

**Issue by iqddd** [LoneGazebo/Community-Patch-DLL#6876]
1. Mod version (i.e Date - 4/17): 6-19-2

2. Mod list (if using Vox Populi only, leave blank): only Community Patch

3. Error description:_ 
https://github.com/LoneGazebo/Community-Patch-DLL/blob/ba29fc18da4b6f3a60e9a5a88ce932cd4038fc64/CvGameCoreDLL_Expansion2/CvTacticalAI.cpp#L3136
The game just crashes due to an incorrect iterator.

**Comment by ilteroi** [comment]
weird. don't really know what's wrong there and it's very old code. but the mismatch between "unit target" and "zone target" is suspicious ...

**Comment by iqddd** [comment]
When calling GetNextZoneTarget without calling GetFirstZoneTarget, the m_iCurrentTargetIndex variable has no initialized value.
Strange, of course. In the dll version v89, this did not cause a crash.
