### ISSUE TITLE
Turns of some AIs take sometimes way too long

### ISSUE THREAD

**Issue by Vyyt02** [LoneGazebo/Community-Patch-DLL#688]
This is a crosspost from the bugs thread on CivFanatics - I do not want to flood it with multiple reports on the same topic, so I am moving here. While processing turns of the most of the AI civs takes 2-5 seconds mid-game, sometimes 1-2 AI civs suddenly start to take about a minute. Sometimes the problem goes away after several turns by itself (back to seconds). It is somehow related to units, because if I mass-kill the said civ's units with IGE, the turn times go back to just a few seconds. It does not seem to be (strictly) related to the size of the civ or size of their army/navy. I have seen it happening to a civ with all these below average.

How can I help? I suppose you need the OperationalAI log (or whatever it is called)? If yes, please tell me how to turn the advanced logging on, I am only getting the basic ones such as database.log or lua.log and I cannot find anything relevant by Google.

Or do you want me to pin-point which unit(s) is/are causing this by killing single units or their groups by IGE? This will be tedious, but if it helps, I can try it - I have done this before.

Version 9/27, no-EUI ; before I played 9/9 and had not experienced this problem.

**Comment by LoneGazebo** [comment]
Thanks for helping with this. Try deleting great generals / admirals if they have any. If that doesn't help, then it is likely operational. I did make some changes to this in the latest test version, so if deleting GGs doesn't help your best bet is the new version (for testing).

**Comment by Vyyt02** [comment]
Ok, cool, I will test it tonight or tomorrow. If deleting GGs does not help, I will try deleting groups of units. Then I will move on the new version.

**Comment by Vyyt02** [comment]
I tried deleting GGs, but it did not help at all. Then I tried to delete all diplomacy units and workers - the difference was negligible. I also tried deleting all ships and embarked units (I probably missed a few) - this reduced the turn times from 35 secs to about 25 secs, which is probably natural. I have not found anything strange in the AI unit formations.

**Comment by ilteroi** [comment]
This is the result of a profiler run on my current development version (turn 500, islands map):

![image](https://cloud.githubusercontent.com/assets/1358966/10406633/dd4ca756-6ee1-11e5-8156-9e69e70d943b.png)

nothing out of the ordinary, i'm afraid ...

@LoneGazebo : what did you change?

**Comment by LoneGazebo** [comment]
The FillWithUnitsFromTheReserves function (running every turn, for every army) was dragging heavily. I've moved the concept to unit creation (thus there's no loop for units, just for armies). I've also changed the FindClosestUnit in CvAIOperation to not pathfind for naval units - it now checks to see if they're in the same area (as water is water) and then grabs distance from the ksearchlist function (saves on a hell of a lot of long-distance pathfinding for naval units across the world).

**Comment by Vyyt02** [comment]
What is this profiler thing? Can I do the same thing as you did with it, ilteroi?

If you do not need me to try any more tests with deleting units with IGE, I will abandon my current game and upgrade to the experimental version 10/8 tomorrow, ok?

**Comment by LoneGazebo** [comment]
http://www.codersnotes.com/sleepy

Grab this, Use x64 version and have it grab the civilization5.exe. It'll profile for a bit, and then you can stop it to get a breakdown of what all is being called by the exe.

Inclusive is the one I watch most, as you can see what functions are specifically dragging that way.

**Comment by ilteroi** [comment]
you also need
- the source code
- a version of the dll compiled with debug symbols
- if compiler optimization is on, the results may be a bit difficult to interpret

**Comment by Vyyt02** [comment]
Uh oh, this sounds way too complicated. I installed the Very Sleepy profiler thing, but ...

- **the source code:** I can grab it from Github I suppose, I thought I had Visual Studio, because I installed Civ SDK in the past, but when I try to run VS as a stand-alone, it tells me there is a problem with license(?!?). I will re-install it - is it ok to install the newest version? (or will it break the Civ5 SDK?) And I need the compiler for C++, nothing else, correct? After that I should be theoretically able to compile the project although I have never done anything like it before. The problem is that I need source code of version 9/27 to open my current lagging save. Can I get it somewhere?

- **a version of the dll compiled with debug symbols**: I have no idea what this means.

- **if compiler optimization is on, the results may be a bit difficult to interpret**: I suppose this is something I can turn off/on in the Visual Studio???

Before we all start wasting time on this (me setting up everything and you explaining everything to a noob like me) ... wouldn't it be easier if I abandon my current game and start a new one with the 10/8beta, and if I experience these delays again, I will just send you a save? You have the Profiler and advanced logging already setup. I will not use any extra mods, and i will not edit any sql/xml so that you can use my save right away.

Moreover Gazebo's recent changes may have eliminated the problem, if I read his comment above correctly.

What do you think? I have some time this weekend, so I am all yours if you want me to test stuff :-)

**Comment by LoneGazebo** [comment]
Very sleepy works for me with or without optimizations on, ilteroi. Or maybe it doesn't, and I'm too dumb to tell the difference. :dancer:

**Comment by LoneGazebo** [comment]
I think we're addressing this in the patch coming up.

**Comment by Vyyt02** [comment]
Great news! If there is any noobish / brute-force (such as deleting units one-by-one with IGE, haha!) way, how I can help, let me know.

**Comment by RDeluxe** [comment]
That's indeed good news, could not stand it after a few turns :D
