### ISSUE TITLE
city starvation

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#6881]
again with 8/4.

![image](https://user-images.githubusercontent.com/1358966/89742153-a87e7c80-da97-11ea-85d1-fd3f5286e2bd.png)

tenochtitlan has been stuck at pop 2 forever, they only managed to found a second city because of the pyramids.

**Comment by RecursiveVision** [comment]
This bug needs a "SLAIN LIKE THE HYDRA" label when it's finally fixed.

**Comment by LoneGazebo** [comment]
So weird, I never see starvation in my tests.

**Comment by azum4roll** [comment]
It needs to be low population with workable high production tiles.

**Comment by RecursiveVision** [comment]
@LoneGazebo I hope it's for real this time! :)
