### ISSUE TITLE
AI building many pathfinders

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6885]
Mod Version: 6-19-2

Was just doing some Deity AI watching and seems like there are quite a few AIs who love building many pathfinders. All Civs go for monument and shrine first but then some will start building workers/settlers while others will start building pathfinders. The Civs who do this tend to keep on building more pathfinders throughout the early game instead of available buildings or units. Didn't seem like they were losing their original ones or anything.

Seemed to mostly be more military orientated civs who were doing this like Greece, Zulus etc however there were some others like Babylon and Morocco who did this as well. 

Also seemed to have quite an effect on their game as the ones who did this ended up some way behind civs like Poland and Brazil who just got on with building all the buildings they could.

**Comment by RhysDeAnno** [comment]
Anecdotally I also frequently see pairs of pathfinders owned by the same AI adventuring together. I don't have an example of it to hand but it always strikes me as wasteful.

**Comment by RecursiveVision** [comment]
Building too many Pathfinders should be fixed in the next version - leaving this open due to the reported AI issue.
