### ISSUE TITLE
Petra not giving Culture from Archeology

### ISSUE THREAD

**Issue by DelJon** [LoneGazebo/Community-Patch-DLL#6887]
_1. Mod version (i.e Date - 4/17):_
newest

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Petra doesn't seem to be giving +6 after Archeology? Might just not be showing? It's quite hard for me to count the culture or test this in some other manner
![20200812123616_1](https://user-images.githubusercontent.com/23047762/90001995-bea85a80-dc9a-11ea-8f29-ff5fa309b1ae.jpg)

**Comment by DelJon** [comment]
Bump, Petra is still not giving culture after Archeology, I think

**Comment by RecursiveVision** [comment]
It's being applied to "Culture from buildings".
