### ISSUE TITLE
More Great People

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#6889]
Calling all modders! 

I've grabbed data for more great people, but it is formatted oddly and I could use manpower to get it up to speed. Here are the files (attached).

[NewGPs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5065279/NewGPs.zip)

Any help would be appreciated. Namely, we need to make uniquename TXT_KEY entries for most of them (for some reason original authory Krajzen didn't do this), and we need to check eratype for correct era.

@RecursiveVision @Aqinu @Glop4 you all want to hop on this?

**Comment by RecursiveVision** [comment]
Still don't have a computer for another 4-5 days - if you want it done by next version I probably can't help.

Vacation's going great, though. :)

**Comment by adaneslavo** [comment]
If you plan such an expansion consider adding this mod too: [CIV-Linked Great Generals (v 11)](https://steamcommunity.com/sharedfiles/filedetails/?id=288364518)

**Comment by GLop4** [comment]
newGM.sql (rev.1) corrected. 
eratype as the  release date of the work.

`INSERT INTO Unit_UniqueNames
	(UnitType, UniqueName, GreatWorkType, EraType)
VALUES
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_MANUEL_DE_SUMAYA',                'GREAT_WORK_HIEREMIAE_PROPHETAE_LAMENTATIONES',   'ERA_RENAISSANCE'), -- 1717
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_AGBANI_NGURU_IKORODO_GROUP',      'GREAT_WORK_IJE_NWAYO',                           'ERA_INDUSTRIAL'), -- 1800+
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_HAMMAMIZADE_ISMAIL_DEDE_EFENDI',  'GREAT_WORK_EY_BUT_I_NEV_EDA_OLMUSUM_MUPTELA',    'ERA_INDUSTRIAL'), -- 1810+
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_ROBERT_HERRICK',                  'GREAT_WORK_CHERRY_RIPE',                         'ERA_INDUSTRIAL'), -- 1825.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_GAETANO_DONIZETTI',               'GREAT_WORK_LUCIA_DI_LAMMERMOOR',                 'ERA_INDUSTRIAL'), -- 1839.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_GEORGE_LINLEY',                   'GREAT_WORK_I_VE_LEFT_THE_SNOW_CLAD_HILLS',       'ERA_INDUSTRIAL'), -- 1847.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_STEPHEN_FOSTER',                  'GREAT_WORK_GWINE_TO_RUN_ALL_NIGHT',              'ERA_INDUSTRIAL'), -- 1852.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_WILLIAM_VINCENT_WALLACE',         'GREAT_WORK_LURLINE',                             'ERA_INDUSTRIAL'), -- 1860.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_GABRIEL_FAURE',                   'GREAT_WORK_REQUIEM',                             'ERA_INDUSTRIAL'), -- 1888.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_JOSEPHINE_BAKER',                 'GREAT_WORK_BLUE_SKIES',                          'ERA_MODERN'), -- 1927.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_MOHAMED_EL_QASABGI',              'GREAT_WORK_ZIBRAYATI',                           'ERA_MODERN'), -- 1930
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_CARL_ORFF',                       'GREAT_WORK_CARMINA_BURANA',                      'ERA_MODERN'), -- 1936.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_DJANGO_REINHARDT',                'GREAT_WORK_MY_SERENADE',                         'ERA_MODERN'), -- 1937.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_MAHMOUD_ZOLFONOUN',               'GREAT_WORK_ROOH_AFZA',                           'ERA_MODERN'), -- 1940+
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_EDITH_PIAF',                      'GREAT_WORK_LA_VIE_EN_ROSE',                      'ERA_MODERN'), -- 1941.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_LUIS_ALBERTI',                    'GREAT_WORK_DAME_EL_SI',                          'ERA_POSTMODERN'), -- 1950+
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_GLENN_MILLER',                    'GREAT_WORK_IN_THE_MOOD',                         'ERA_POSTMODERN'), -- 1953.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_THELONIOUS_MONK',                 'GREAT_WORK_MISTERIOSO',                          'ERA_POSTMODERN'), -- 1958.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_RAY_BARRETTO',                    'GREAT_WORK_GUAJIRA_Y_TAMBO',                     'ERA_POSTMODERN'), -- 1962.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_THE_BEATTLES',                    'GREAT_WORK_HELP',                                'ERA_POSTMODERN'), -- 1965.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_DR_M_BALAMURALIKRISHNA',          'GREAT_WORK_ENDARO_MAHANUBHAVULU',                'ERA_POSTMODERN'), -- 1966.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_JANIS_JOPLIN',                    'GREAT_WORK_SUMMERTIME',                          'ERA_POSTMODERN'), -- 1968.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_THE_TEMPTATIONS',                 'GREAT_WORK_PAPA_WAS_A_ROLLING_STONE',            'ERA_POSTMODERN'), -- 1972.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_FELA_ANIKULAPO_KUTI',             'GREAT_WORK_WATER_NO_GET_ENEMY',                  'ERA_POSTMODERN'), -- 1975.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_FRANCO_DU_CONGO',                 'GREAT_WORK_LIBERTE',                             'ERA_POSTMODERN'), -- 1976.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_RAM_JAM',                         'GREAT_WORK_BLACK_BETTY',                         'ERA_POSTMODERN'), -- 1977.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_RICKY_LEE_JONES',                 'GREAT_WORK_CHUCK_ES_IN_LOVE',                    'ERA_POSTMODERN'), -- 1979.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_HORACE_ANDY',                     'GREAT_WORK_IT_S_GONNA_BE_DREAD',                 'ERA_POSTMODERN'), -- 1980
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_WOMACK_AND_WOMACK',               'GREAT_WORK_TEARDROPS',                           'ERA_POSTMODERN'), -- 1988.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_ERNST_REIJSEGER',                 'GREAT_WORK_SHADOW',                              'ERA_FUTURE'), -- 1990+
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_SINEAD_O_CONNOR',                 'GREAT_WORK_DONT_CRY_FOR_ME_ARGENTINA',           'ERA_FUTURE'), -- 1992
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_THE_SUGAR_HILL_GANG',             'GREAT_WORK_RAPPERS_DELIGHT',                     'ERA_FUTURE'), -- 1993.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_KARL_JENKINS',                    'GREAT_WORK_PALLADIO',                            'ERA_FUTURE'), -- 1995.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_RUBEN_GONZALEZ',                  'GREAT_WORK_ALMENDRA',                            'ERA_FUTURE'), -- 1997
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_UFO',                             'GREAT_WORK_LOUD_MINORITY',                       'ERA_FUTURE'), -- 1997.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_AJIM_KRAJKA',                     'GREAT_WORK_FANTAZI',                             'ERA_FUTURE'), -- 1960+
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_DAVID_BOWIE',                     'GREAT_WORK_LIFE_ON_MARS',                        'ERA_FUTURE'), -- 1971.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_SHIGERU_UMEBAYASHI',              'GREAT_WORK_IN_THE_MOOD_FOR_LOVE',                'ERA_FUTURE'), -- 2000.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_DEGUNG_SUNDA',                    'GREAT_WORK_MENYEJUKKAN_HATI',                    'ERA_FUTURE'), -- 2000+
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_SAWAI_HIKARU',                    'GREAT_WORK_ESORAGOTO',                           'ERA_FUTURE'), -- 2000+
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_PEACHES_AND_IGGY_POP',            'GREAT_WORK_KICK_IT',                             'ERA_FUTURE'), -- 2003
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_ROBERTO_FONSECA',                 'GREAT_WORK_DRUME_NEGRITA',                       'ERA_FUTURE'), -- 2009.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_NILS_FRAHM',                      'GREAT_WORK_ME',                                  'ERA_FUTURE'), -- 2012
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_CHAD_LAWSON',                     'GREAT_WORK_NOCTURNE_IN_F_MINOR',                 'ERA_FUTURE'), -- 2014.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_BALTI',                           'GREAT_WORK_YA_LILI',                             'ERA_FUTURE'), -- 2017.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_LUIS_FONSI',                      'GREAT_WORK_DESPACITO',                           'ERA_FUTURE'), -- 2017.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_MANNAT_NOOR',                     'GREAT_WORK_LAUNG_LAACHI',                        'ERA_FUTURE'), -- 2018.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_CHILLY_GONZALES',                 'GREAT_WORK_NIMBUS',                              'ERA_FUTURE'), -- 2018.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_THE_WEEKND',                      'GREAT_WORK_BLINDING_LIGHTS',                     'ERA_FUTURE'), -- 2019.
	('UNIT_MUSICIAN', 'TXT_KEY_GREAT_PERSON_GABRIEL_GARZON_MONTANO',          'GREAT_WORK_BLOOM',                               'ERA_FUTURE'); -- 2020.
`
[newGM_rev1_.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5065735/newGM_rev1_.zip)

**Comment by GLop4** [comment]
newGM.sql corrected. (rev.2)

[newGM_rev2_.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5066396/newGM_rev2_.zip)

**Comment by GLop4** [comment]
Here are the Extra_GA_Arts (.dds) I plan to use to add 40 GAs:
[Extra_GA_Arts_rev0.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5068781/Extra_GA_Arts_rev0.zip)
@LoneGazebo 
Much better quality than the Art folder you suggest.

Please tell me if newGM_rev2_.zip meets you expectations?
I plan to use it as a model for the rest of GPs.
The tabulated sql format help me a lot to see the all thing.

It will take long to complete GMs/GAs/GWs/GPs
I can deal with that and provide at the end 1 .sql and 1 Arts folder (all in one). Is it ok with you?

For now, I believe ExtraGMs (The most wanted) can go in the next VP. (The most wanted)

**Comment by GLop4** [comment]
@LoneGazebo 
50 GM + 40 GA (All in one)
[Extra_GP (rev 3).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5077067/Extra_GP.rev.3.zip)

**Comment by GLop4** [comment]
@LoneGazebo 

Here is **MoreGP (ver 2)**
With in it:
-- 50 Great Musicians
-- 66 Great Artists
-- 34 Great Writers
-- 91 Great Generals
-- 61 Great Admirals
-- 61 Great Merchants
-- 61 Great Engineers
-- 83 Great Scientists

Replaces entirely the existing folder   \MODS\(1) Community Patch\Modules\MoreGP   in VP(10-7-2)

Merge the 5 .zip below to get the new MoreGP module.

[MoreGP (v 2) 1-5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5490845/MoreGP.v.2.1-5.zip)
[MoreGP (v 2) 2-5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5490852/MoreGP.v.2.2-5.zip)
[MoreGP (v 2) 3-5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5490857/MoreGP.v.2.3-5.zip)
[MoreGP (v 2) 4-5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5490860/MoreGP.v.2.4-5.zip)
[MoreGP (v 2) 5-5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5490864/MoreGP.v.2.5-5.zip)

More GWs will be added in the future.

**Comment by GLop4** [comment]
@LoneGazebo 

VP (12-1)
\Modules\MoreGP\Extra_GPs_items folder is not updated (Old items)
