### ISSUE TITLE
Improvements to war selection logic

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6892]
So I've been thinking about how to make the AI smarter in terms of who it DoW's.

I haven't fully reviewed the logic for war declarations, but from what I remember it goes something like this:

**Normal War Declarations**

- Each turn, AI checks which majors it already has the WAR approach against (or the HOSTILE approach if it's going for Domination Victory - or, added by me - the DECEPTIVE approach if the other player is close to winning). If any of these are true, bWantToAttack is set to true.

- If AI has a Declaration of Friendship or can't declare war, bWantToAttack is set to false.

- If AI is already at war with a major civ, and (added by me) this new guy isn't an "easy target", bWantToAttack is set to false.

- If bWantToAttack is set to true, then SetWantsSneakAttack(ePlayer, true) is called.

- The military AI checks if the diplo AI wants a sneak attack, and decides (not sure how) who to launch a sneak attack operation against.

- When the sneak attack operation is complete, the military AI calls SetArmyInPlaceForAttack(ePlayer, true) in the diplo AI.

- Each turn, the AI goes through its war targets and (I'm not sure exactly how it prioritizes, but proximity is a major factor) declares war if IsArmyInPlaceForAttack is true or the sneak attack operation is sufficiently (85%?) complete.

**Other War Declarations**
- When it agrees to a coop war, paid war, or in any other circumstance, the AI sends a request for a "basic attack" (sometimes but not always along with a "pure naval attack") to the military AI, which decides whether or not to attack.

- This means that when the AI declares war through any means other than a normal war declaration, it is significantly less prepared.

- You can force the AI to declare war early by asking it to move its troops (not sure what effect this has on war preparedness).

- AIs randomly decide whether to declare war on the human if the insulting dialogue option is selected (although they don't declare war on friends).

I can think of a number of flaws with this system:
- The AI keeps the WAR approach adopted towards players it won't attack because it's already at war, which affects trade prices, discussion responses, etc. The AI might be shooting itself in the foot by being unnecessarily hostile to players it's not currently at war with, while at war (poor strategy, to an extent).

- The AI could potentially have multiple sneak attack operations dividing its forces, rather than sending one large army to get the guy it's actually going to attack.

- The AI doesn't prepare for coop wars, doesn't actually wait 10 turns even if it requests it, and is generally far less prepared. I guess it's unavoidable for trade wars, but coop wars could be more well-prepared.

- The AI's strategic prioritization of targets based on proximity is not necessarily a smart choice.

- "Phony wars" (distant adversaries with no nearby threatening presence) can impede an AI's ability to effectively attack its opponents.

- It is possible to bribe an AI to declare war on someone else while they are moving on you.

- Declaring war on the AI before they declare war on you can mess up their military preparedness.

- The AI can declare war out of pure hostility, without the military capability to back up its threats, and not with a specific intention to, say, block someone's trade routes. This is particularly bad if it declares war on a hugely powerful neighbor based on an insult or something, and then refuses to make peace for a while.

I'm looking at ways of reworking this to make it more intelligent, something which I think will make a major impact on humans' enjoyment of diplomacy as well as AI intelligence.

Does anyone have any thoughts or suggestions on how to improve this? The logic is pretty messy and I plan on improving it when I return from my vacation.

@LoneGazebo @ilteroi

**Comment by RecursiveVision** [comment]
One of my initial thoughts is to reserve the WAR approach for when the AI is actually planning war.

After selecting approaches for the turn, the AI could select the targets it wants to WAR against, change the WAR approach to the next-highest approach weight, or something like that.

**Comment by Mileslewis** [comment]
I guess make sure that the AI isn't switching targets too much, so once it starts preparing an attack it is unlikely to change it's mind mid way and stop.

Seems like coop wars might be worth somewhat hard coding that an AI will then prepare that sneak attack and not others for 10 turns.

Not sure how much you can do about this but when it isn't a normal war they planned or are in danger from AIs really do very little. Sometime they don't even bother killing trade routes that are close to them. Maybe that's okay though if they aren't really interested so they don't want to do negative diplo actions.

**Comment by RecursiveVision** [comment]
*REVISED LOGIC (WORK IN PROGRESS)*

Fix 1: Phony War
A phony war is one in which:
- The other player(s) are not currently attacking the AI;
- The AI has no attack operations against them, and;
- Warscore is not too high on either side, and;
- IsWantsToConquer is false.

Modify IsWantsToConquer so that wars started by the AI that are not unfavorable targets, wars not started by the AI that are favorable targets, and wars against players who stole cities from the AI return true - all others return false.

AIs in a phony war are willing to make peace, provided all other requirements (such as the minimum turn counter, and a city isn't about to be captured) are met.

Fix 2: Target Selection
After each update of major civ approaches, the AI goes through all players and decides which ones it wants to sneak attack for a normal war declaration, overriding its selected approach as needed.

1) The AI loops through all players it is currently at war with, and eliminates them from consideration but increments the "at war" counters. For a phony war the at war counter is not incremented.

2) If the AI has agreed to a coop war against any players, it sets its approach towards those players to WAR and increments the "at war" counter.

**Comment by RecursiveVision** [comment]
Fix 3: Potential Wars
As mentioned above, the AI might be willing to join a coop war or be bribed into declaring war.

AI tolerates only so many ongoing wars. Its tolerance is measured in points, and depends on boldness:
1-2 Boldness: 0 points
3-5 Boldness: 2 points
6-8 Boldness: 4 points
9-10 Boldness: 6 points
Add 2 points if player has a UA which grants bonuses towards war.

Phony wars are worth 1 point.
Wars against easy targets are worth 1 point.
Wars against bad targets or players with stronger militaries (that aren't easy targets) are worth 4 points.
Other wars are worth 2 points.

If AI is doing terribly (see Fix 2 above) or is currently at a STALEMATE or worse in any war, it will refuse to start additional wars.

If AI is not doing terribly, it will be willing to accept bribes to go to war up to its war tolerance if the target is a "potential war target". It will also accept wars above its war tolerance provided all other conditions are met, but the price is multiplied by 5 * the number of points above its tolerance, making it extremely expensive. AI factors in DPs/teammates/vassals/masters when doing this calculation.

AI is willing to start coop wars up to its tolerance, and not above that (unless the asker is a teammate, in which case it must automatically accept as usual).

**Comment by RecursiveVision** [comment]
Fix 4: Insults
Rather than determine whether to go to war randomly, AI can run the usual sanity checks and respond to the player's taunt with a variety of responses:
- Declare war
- Change approach to HOSTILE, GUARDED, AFRAID or NEUTRAL

**Comment by RecursiveVision** [comment]
Fix 5: Stick to your Wars, Damn It!
When an AI decides to wage war, it will set a value called "WantsSneakAttack" which tells the military AI to create a sneak attack operation against the other player.

When "WantsSneakAttack" is set, the AI gains a significant WAR approach bias and cannot reevaluate its war desire unless another approach overrides it, to prevent the AI constantly switching between wars.

WantsSneakAttack is set to false when another condition besides approach that made the war OK to start is suddenly false, however.

IsWantsToConquer (an existing function mentioned in Fix 1) will be used to track whether the AI cares about the war and affects AI willingness to attack cities.

**Comment by RecursiveVision** [comment]
This is my current idea so far. Any thoughts, anyone?

**Comment by ilteroi** [comment]
what really needs to happen is a rewrite of the military AI.

* iterate all players/cities
* evaluate surrounding terrain, distance, city quality (economic or settle plot) etc
- code is already there
* keep only the top N targets in the world (scale with era etc)
- build units according to top target types (land/naval)
* create matching AI operations (land/naval) if requested to attack a certain enemy
- or maybe even before and keep the army on standby
- right now we request a certain op type and look for suitable targets which is stupid and inefficient
* choose diplomatic approach according to availability of targets
- become friends if we have no attack target for a certain player

or something along those lines.

**Comment by RecursiveVision** [comment]
@ilteroi Good points, particularly the last one. I have some ideas for this which I'm gonna start working on. I'll call upon your military expertise soon :)

**Comment by Caspiff** [comment]
@RecursiveVision , I'm pretty new here, but I saw your post when checking what was going on with this fantastic mod... and I thought it would be great to say something about this topic. A good job here could really change the game experience!

I believe the war declaration is very random in this game. There are lots of flaws and I think you named a lot of them. Since a war is most likely strengthening or weakening a civ, it would be important to help the AI to make the right choice.

Historically, wars have been constantly happening among neighbors for the sake of expansion and resource control. Historically, only very large empires have had resources to declare war to countries far from their borders (and many times those wars didn't go well). I don't think it should be different in this game. I don't get when a distant civ is declaring war against me, even if we have good trade possibilities that benefit us both.

Based on this, the priority for war declaration should be proximity + resources + difference in military strength. And really penalize wars against distant civs, unless force majeure. Really focus AI military resources on the closest and weakest targets.

This way, civilizations would become larger and more powerful over time, versus staying small and weak, as it is usually happening today.

There are many other variables that could happen in the real life for a war declaration, but the higher the complexity for the AI, the higher chances it will take wrong choices and start useless wars around.
