### ISSUE TITLE
Tech costs issues

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6894]
So after the base tech cost in a given game is calculated there are some modifiers applied to each to get each player's individual tech cost.

calculateResearchModifier() is a function in CvPlayer which calculates the cost modifier for a given tech based on percent of known civs who have the tech and then extra bonus if scholars in residence is active.

Seems like there has been some change in use of this and that it was designed to be used as a positive modifier for your tech production, but is now used as a negative modifier for your tech cost.

in CvTechClasses it is used in: 
int CvPlayerTechs::GetResearchCost()                  which seems to give the cost displayed for a player.

however it is also used in:
void CvTeamTechs::SetResearchProgressTimes100()          which seems to give the **actual** tech cost, so how much overflow will be left after a tech is completed. It is applied in two different ways though (neither of them are optimal but this one is better. EDIT- actually the way it is used here is fine) so there are sometimes differences between what is displayed that you need and what is actually need for a tech.

Also lastly for some reason calculateResearchModifier() is also then used as a positive modifier on overflow amounts which I'm guessing is a relic from when it was used as a positive modifier on tech production in the past. There are multiple locations where this seems to be implemented and tbh I got quite confused trying to figure out which one was actually the culprit. Can't see any reason why it should be like this if we can avoid it though.

**Comment by psparky** [comment]
I think it's always been used as a modifier to tech costs going back to vanilla (certainly in BNW). You have always been able to tell how many of the known civs have discovered a tech by examining the individual tech costs.

**Comment by Mileslewis** [comment]
Fair enough, well I really don't understand why it is being used as a positive modifier on overflow amounts then.

**Comment by psparky** [comment]
Revisiting this while investigating another tech overflow issue...

I was pointing out that the current arrangements with the research modifier predate VP, but I should add that I agree it is probably a relic from either a pre-BNW Civ 5 or even an earlier Civ game. With the current mechanism where the modifier affects tech costs, I can see no reason why overflow should ever be adjusted by the modifier, and I support the suggestion that it should be removed.
