### ISSUE TITLE
Some simpler stuff about tech.

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6895]
Currently the tech cost modifier for percent of civs who know a given tech includes yourself.
This means you can never actually get the full (10%) bonus even if all other civs know a tech and for example if you are playing with only one other civ you can only get half the bonus.

Also the tech and policy cost increase per city on a given map size starts with your first city. Could perhaps be changed to start on the second one?

**Comment by RecursiveVision** [comment]
I'd see no issue with that, Tourism excludes the capital.

**Comment by LoneGazebo** [comment]
Fine by me.

**Comment by Mileslewis** [comment]
Fine as it is or fine with changing it?

**Comment by LoneGazebo** [comment]
fine with changing

**Comment by psparky** [comment]
I think that these changes make sense, but I'm concerned about the resultant quickening of the tech rate.

The first point, number of known civs with the tech, would typically give a 1% increase, so maybe 3-5 turns over a typical standard speed game of 400 turns.

The second though, not counting the capital for penalties, will have a much bigger impact; close to 7% (that's still the figure for a standard game, right>) at the start and around 4.5% with 8 cities. Say 5% on average, that's 20 turns.

If anything, I would prefer to slow the tech rate down slightly.

Social Policies would also come quicker of course.

**Comment by Mileslewis** [comment]
Tbh I'm inclined to agree that tech is probably a little too fast right now, and changing these would speed it up slightly. I just mentioned these because they weren't how I expected them to be.

The mapsize scaling is a little strange as well really. On a huge map there is a 30% increase to all tech cost, even though, for example at the start, it makes no difference to the player how big the map is.

Also policy cost doesn't have this 30% increase on huge map.

**Comment by RecursiveVision** [comment]
If tech speed is too fast, a better solution is to increase the base cost.
