### ISSUE TITLE
New City States show old city name despite having new city owner

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#6898]
_1. Mod version (i.e Date - 4/17):_
June 19th (5.6.19)

_2. Mod list (if using Vox Populi only, leave blank):_
VP
Community Patch Mod Compatibility
Enhanced Naval Warfare for VP
Pontoon Bridges for VP
XCOM for VP

_3. Error description:_ 
When an opposing empire plumbs the depths of unhappiness, one of their cities breaks away and declares itself an independent city-state. I'll get an appropriate notification of the event. For example, "Calcutta has declared itself an independent city-state! It's new name is Cahokia." (paraphrased, of course) However, the name on the map still shows "Calcutta", while the name in the city-state diplomacy screen says "Cahokia".

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
I haven't seen this happen for ages I thought this feature had been removed?

**Comment by RecursiveVision** [comment]
Nope.
