### ISSUE TITLE
Feature Request - New Beliefs DLL Integration

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#6899]
I have released and tested a modmod that adds new beliefs to VP. It is pretty fun, but very unstable. The lua implementation simply stops working after a while for non-pantheon beliefs (pantheons seem stable). DLL integration would make it far better to use and more enjoyable.

DLL features I am wanting to have added:
Column: Free Promotion - Units trained in city with this majority religion get a promotion
Table: Belief_YieldFromTechUnlock - Identical to the existing Belief_YieldFromPolicyUnlock (scaling per follower), but yields every time a tech is researched.
Table: Belief_YieldFromTileImprovement - instant yields whenever a unit completes a non-road tile improvement. Does not scale with era.
Table: Belief_YieldFromPillage - instant yield whenever a tile is pillaged. Does not Scale with Era.

**Comment by Tekamthi** [comment]
i have very inconsistently been able to add more than the built-in number of max religions... i have tried a database update to relevant xml table but no luck, must be missing some static variable in lua or dll.  Would be nice to get around 10 religions or so with 43 civ dll

**Comment by HungryForFood** [comment]
#7334
