### ISSUE TITLE
City States not building workers

### ISSUE THREAD

**Issue by espence1** [LoneGazebo/Community-Patch-DLL#690]
Originally posted on Civfanatics bug forum before I read the first post properly. One other person confirmed the bug, so here it is...

Using just the CP, City States don't seem to build workers at all, at least not before turn 100 (normal speed). I've tried 2 games up to turn 100 and haven't witnessed a single worker for a City State, leaving all their land unimproved.

More subjectively, enemy civs seem late to build workers, and seem to prioritize roads over other improvements.

I've tried with the full CBP and these problems do not occur.

**Comment by TechpriestEnginseer** [comment]
Because with just the CP, the AIs aren't flavored properly to build workers. With the CBP, flavor lines are installed under workers.

**Comment by LoneGazebo** [comment]
It depends on a few factors, honestly. I'll add a tile improvement buff to flavors for CSs, see if it helps.
G

**Comment by LoneGazebo** [comment]
Can't replicate the issue, sorry.
G
