### ISSUE TITLE
Vassals and Domination Victory

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6900]
I suggest that we alter the rules for Domination Victory so that capitals owned by vassal states or allied City-States count towards Domination Victory.

This prevents situations where a player has to declare war on their own vassal or allied City-State in order to win a Domination Victory.

Not only would players probably appreciate this (Domination Victory is the hardest to achieve, and it's not fun to have to declare an easy war on an ally in order to win like this) but it'd be a lot more AI friendly.

As it is the special logic I wrote to handle the special case where the AI should attack their own vassals is ineffective, probably because of that check ilteroi mentioned preventing attack operations on vassals.

**Comment by LoneGazebo** [comment]
Fixed. Vassal-owned capitals now count towards Dom victory.
