### ISSUE TITLE
8/16 - pathfinder doesn't account for terrain cost 

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6902]
_1. Mod version (i.e Date - 4/17):_ 8/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Pathfinder doesn't appear to calculate turns for movement correctly. Does not account for terrain cost.
![image](https://user-images.githubusercontent.com/59859911/90345961-19bbb380-dff3-11ea-96bc-4c79941993ce.png)
![image](https://user-images.githubusercontent.com/59859911/90345968-2d671a00-dff3-11ea-8ddb-4499fb8cbdfa.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by cdanger341** [comment]
This isn't just for Pathfinders. All units are not accounting for terrain movement speed adjustments which is throwing off the multi-turn movement path previews and causing features like Path-To road building to fail when the worker has to move over hills, forests, or rivers. Confirmed using 8-16-2 hotfix build.

**Comment by LoneGazebo** [comment]
I’ve already fixed for next version.
