### ISSUE TITLE
8/16 - low scores from military power

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6907]
_1. Mod version (i.e Date - 4/17):_ 8/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Score contribution from military power seems very low. Highest among AI at this point in the game is 5. In demographics I am sixth in "soldiers" and tied for lowest military power, yet Theodora is "terrified" of my military. 

![image](https://user-images.githubusercontent.com/59859911/90360588-1d1e6180-e02a-11ea-8b80-0f96928f5de1.png)
![image](https://user-images.githubusercontent.com/59859911/90360617-31625e80-e02a-11ea-8f5c-e45b78c930b0.png)

![image](https://user-images.githubusercontent.com/59859911/90360603-25769c80-e02a-11ea-963c-7456f6840508.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Yeah, GetPlayerMilitaryStrengthComparedToUs/DoUpdatePlayerMilitaryStrengths in the Diplomacy AI uses a different calculation. Not sure what's wrong with the score calculation.

**Comment by RecursiveVision** [comment]
The code is:
```
int CvPlayer::GetScoreFromMilitarySize() const
{
	return (GetMilitaryMight() / (20 + getNumCities()));
}
```

Obviously the issue is the huge divisor... @LoneGazebo I can confirm military scores are absurdly low in the list - you'll want to tweak this.

**Comment by silentreply** [comment]
@RecursiveStar If the diplomacy AI uses a different calculation, would that calculation also determine "afraid" status and war evaluation? I'm concerned that the low military scores may be impacting AI diplomacy and opportunistic aggression. 

Here is another example, where we both have 1 score from military power:
![image](https://user-images.githubusercontent.com/59859911/90702000-2260f380-e258-11ea-91c5-1cd2c5d50d39.png)

**Comment by RecursiveVision** [comment]
@silentreply G updated it to be 10 + number of cities as the divisor in the hotfix.

Diplo AI calculation is used for AFRAID status and war evaluation but is unrelated to the score in the scoreboard.
