### ISSUE TITLE
8/16 - Can't build stone works in city with marble

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6908]
_1. Mod version (i.e Date - 4/17):_ 8/16
 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I can't build stone works in my capital despite owning and working a marble tile. That tile was first acquired by a city to the north, but in the past I am pretty sure you've been able to build stone works (and other buildings with resource requirements) by swapping the tiles over. 

![image](https://user-images.githubusercontent.com/59859911/90362181-00842880-e02e-11ea-8d2a-a037613abe29.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by silentreply** [comment]
I was able to build it after swapping the marble tile back and forth. Not ideal, but I guess not high priority - however this does seem to be part of a persistent issue where cities/yields do not "update." For example, building a workshop will sometimes not give production to forests until the tiles are swapped or reset.

**Comment by azum4roll** [comment]
That would be a problem for the AI...
