### ISSUE TITLE
Random map script generates non-existant worlds

### ISSUE THREAD

**Issue by sgwicks** [LoneGazebo/Community-Patch-DLL#6909]
_1. Mod version (i.e Date - 4/17):_

8/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Choosing "random map" during game setup generates no world (and instant game loss)

_4. Steps to reproduce (optional):_

Start a game with "random map"

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5082563/Logs.zip)

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Random map huh? I forgot that existed. I'll take a look some time.
