### ISSUE TITLE
map generator / starting locations / direction_types

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#691]
so the big change in the DLL was that NO_DIRECTION used to be -1, now it's 7. makes it easier and faster to do a neighbor lookup for a plot. the rest is still as before.

this is the export of the DirectionTypes enum from C to Lua:

	// DirectionTypes
	EnumStart(L, "DirectionTypes");
	RegisterEnum(NO_DIRECTION);
	RegisterEnum(DIRECTION_NORTHEAST);
	RegisterEnum(DIRECTION_EAST);
	RegisterEnum(DIRECTION_SOUTHEAST);
	RegisterEnum(DIRECTION_SOUTHWEST);
	RegisterEnum(DIRECTION_WEST);
	RegisterEnum(DIRECTION_NORTHWEST);
	RegisterEnum(NUM_DIRECTION_TYPES);
	EnumEnd(L);

Note that the actual order of the values here is (7,0,1,2,3,4,5,6) but (0,1,2,3,4,5,6,7) should work just as well.

This is how it's used most of the time:

	local directions = {
		DirectionTypes.DIRECTION_NORTHEAST,
		DirectionTypes.DIRECTION_EAST,
		DirectionTypes.DIRECTION_SOUTHEAST,
		DirectionTypes.DIRECTION_SOUTHWEST,
		DirectionTypes.DIRECTION_WEST,
		DirectionTypes.DIRECTION_NORTHWEST
	};

		for loop, current_direction in ipairs(directions) do
			local testPlot = Map.PlotDirection(x, y, current_direction);

this is fine.

in some places you also see this, where ints are used instead of the enum:

		local numDirections = DirectionTypes.NUM_DIRECTION_TYPES;
		for direction = 0, numDirections - 1, 1 do
			adjacentPlot = Map.PlotDirection(pPlot:GetX(), pPlot:GetY(), direction);

which should also work. 

so, (unfortunately) i don't really see a problem here ... also, the earth map which has a problem with the startinglocations apparently is not a generated map but handcrafted. don't know how that figures in here.

**Comment by ilteroi** [comment]
i suspect the issue is somewhere in void CvGame::assignStartingPlots()

**Comment by LoneGazebo** [comment]
Hooray! I like issues where the problem and solution are found before I even get a chance to look! :+1:
