### ISSUE TITLE
Promotion Open Terrain Modifier Doesn't Work as intended

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6911]
_1. Mod version (i.e Date - 4/17): 8/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:

**Issue 1**: Doesn't work at all for catapults.
**Issue 2**: For melee only hills are considered to be NOT open terrain everything else IS consider as open (jungle, forest, hills with forest/jungle, marshes...)

I think is related to #6730.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Issue 1. ex1.**
![Civ5Screen0006](https://user-images.githubusercontent.com/49090452/90381241-c21a5800-e085-11ea-8d81-6acfb981b4b2.jpg)

**With field 3, if you calculate the strength you will see that open terrain bonus isn't used on any type of terrain.**
![Civ5Screen0007](https://user-images.githubusercontent.com/49090452/90381243-c34b8500-e085-11ea-8f81-0f4a5bb8d352.jpg)

**Issue 1. ex2.**
![Civ5Screen0009](https://user-images.githubusercontent.com/49090452/90381479-1de4e100-e086-11ea-89ac-3263c2e269f7.jpg)
**Ranged attack modifier from field 3 disappears here (because -30 from logistics) and you can see that it doesn't apply open terrain modifier**
![Civ5Screen0008](https://user-images.githubusercontent.com/49090452/90381483-1f160e00-e086-11ea-802e-56315ec6dcec.jpg)

**Issue 2. For Melee Mounted the Charge Promotion considered everything OPEN TERRAIN except for hills without features (you can see from total strength).**
![Civ5Screen0010](https://user-images.githubusercontent.com/49090452/90381743-7c11c400-e086-11ea-9e1e-9ecea066e028.jpg)
**HERE OPEN TERRAIN**
![Civ5Screen0011](https://user-images.githubusercontent.com/49090452/90381744-7caa5a80-e086-11ea-9364-1c52f0a41401.jpg)
**HERE OPEN TERRAIN (HERE CORRECT)**
![Civ5Screen0012](https://user-images.githubusercontent.com/49090452/90381747-7ddb8780-e086-11ea-8bd0-0bbf8aaf77e3.jpg)
**HERE OPEN TERRAIN**
![Civ5Screen0013](https://user-images.githubusercontent.com/49090452/90381749-7e741e00-e086-11ea-9a19-72524305382a.jpg)
**ONLY HERE ROUGH TERRAIN AND THE BONUS SHOULDN'T EVEN APPEAR HERE**
![Civ5Screen0014](https://user-images.githubusercontent.com/49090452/90381752-7fa54b00-e086-11ea-9197-6cf9c8c9cf88.jpg)

**Comment by RecursiveVision** [comment]
ilteroi changed what's considered open terrain in the DLL, I think.
