### ISSUE TITLE
Mooom, the Governor is starving my citizens again! [8/16]

### ISSUE THREAD

**Issue by Maxxim69** [LoneGazebo/Community-Patch-DLL#6917]
_1. Mod version (i.e Date - 4/17):_
8/16

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) List Enhancements for VP (v 5.2)
Quick Turns (v 10)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 
City Governor causes a 2-population city to starve as early as Turn 15.

Save file attached.
[Catherine_0015 BC-3400.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5086107/Catherine_0015.BC-3400.zip)

**Comment by LoneGazebo** [comment]
Already fixed in hotfix version - was a missing bit of code I'd made.
