### ISSUE TITLE
No sacrifice at all [8/16]

### ISSUE THREAD

**Issue by Maxxim69** [LoneGazebo/Community-Patch-DLL#6919]
_1. Mod version (i.e Date - 4/17):_
8/16

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) List Enhancements for VP (v 5.2)
Quick Turns (v 10)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 

*It's a human sign
When things go wrong...*

![No_Sacrifice_at_All](https://user-images.githubusercontent.com/24704375/90443037-40a5e280-e0e4-11ea-84ad-ce59c47a6c2e.jpg)

It looks like I have 26.7 food in my capital, but the sacrifice of 25 food cannot be made, and no reason for that is given.
Savefile attached.

[AutoSave_0075 BC-1000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5086748/AutoSave_0075.BC-1000.zip)

**Comment by Maxxim69** [comment]
Sadly, the issue persists in version 10-7-2.

The option that is unavailable due to this bug is (quoting from memory) "Requires your Religion to be a Pantheon". However, when my Religion is indeed a Pantheon, the option is not made active.

**Comment by Maxxim69** [comment]
Sadly, the bug still persists in version 10-7-2.
This time I have more than 115 food in my capital.

![No_Sacrifice_II](https://user-images.githubusercontent.com/24704375/96321553-86b4ef00-101e-11eb-8527-6c4b764bfe79.jpg)

**Comment by RecursiveVision** [comment]
Took hours to narrow this one down, but it's finally fixed!

**Comment by Maxxim69** [comment]
You are breathtaking, @RecursiveVision! 😊👍
