### ISSUE TITLE
8-16-2 "NO MESSAGE" diplo string

### ISSUE THREAD

**Issue by Pathologic72** [LoneGazebo/Community-Patch-DLL#6920]
Just leaving this here for whoever "Jon" is.

**Most recent autosaves here:** [AutoSaves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5087265/AutoSaves.zip)

_1. Mod version (i.e Date - 4/17):_
8-16-2

_2. Mod list (if using Vox Populi only, leave blank):_
<img width="269" alt="Mods Used" src="https://user-images.githubusercontent.com/35882706/90453506-cd3daa00-e0be-11ea-9234-ce9fc85e11e5.png">

_3. Error description:_ 
Got a "NO MESSAGE" string when receiving a message from an AI.

_4. Steps to reproduce (optional):_
Unknown

![CivilizationV_DX11_KolOKj7vtK](https://user-images.githubusercontent.com/35882706/90453467-b13a0880-e0be-11ea-8c03-25a73765fa9e.jpg)

**Comment by RecursiveVision** [comment]
Either this is caused by my diplo AI options or by your new diplo statement.

**Comment by RecursiveVision** [comment]
@Pathologic72 Did you change any of the diplomacy options in DiploAIOptions.sql?

**Comment by Pathologic72** [comment]
> @Pathologic72 Did you change any of the diplomacy options in DiploAIOptions.sql?

I haven't made any changes to the VP mod files.

**Comment by RecursiveVision** [comment]
Strong chance it's your new diplo statement, G. Both times the bug was reported the AI was visibly FRIENDLY.

**Comment by Pathologic72** [comment]
I think I remember making a DoF with France before seeing that, so that may be the cause. I've used VP and mostly the same mods for years and have **never** seen this message before now.

**Comment by LoneGazebo** [comment]
I'd need the DiploAIMessage log to diagnose.

**Comment by Pathologic72** [comment]
@LoneGazebo 

This file, right?
[DiplomacyAI_Messages_Log.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5088121/DiplomacyAI_Messages_Log.zip)

I went back and was able to replicate the "NO MESSAGE" from France with logging enabled. It looks like the ***BECOME YOUR VASSAL*** bit is the culprit.

**Comment by LoneGazebo** [comment]
Oh I know why. I forgot to do the enum parser... 🤦

**Comment by LoneGazebo** [comment]
It's been awhile since I've done a new diplo message.
