### ISSUE TITLE
(Temporary) Icon for PROMOTION_IKLWA

### ISSUE THREAD

**Issue by GLop4** [LoneGazebo/Community-Patch-DLL#6922]
_1. Mod version 8-16-2

_3. Error description: New Iklwa promotion. No promo Icon yet:
![00](https://user-images.githubusercontent.com/8753808/90529290-d9d00a00-e173-11ea-8281-713ab71f285c.png)

'tempVPPI_Atlas' is here to provide a temporary solution:
![11](https://user-images.githubusercontent.com/8753808/90529766-5ebb2380-e174-11ea-9a47-77c807b022e1.png)

**\MODS\(7a) Promotion Icons for VP\sql\promoIcons_Update_Main.sql**
Line 21
`*/
UPDATE UnitPromotions SET IconAtlas = 'tempVPPI_Atlas' WHERE Type = 'PROMOTION_IKLWA'; -- Yellow Triangle like a inclined star
UPDATE UnitPromotions SET PortraitIndex = '7' WHERE Type = 'PROMOTION_IKLWA';
/*
`

![temp_show](https://user-images.githubusercontent.com/8753808/90530158-dab56b80-e174-11ea-8564-d51e73e362bb.png)

**Comment by LoneGazebo** [comment]
Done! Thanks.
