### ISSUE TITLE
Spearman Showing Tourism Amount

### ISSUE THREAD

**Issue by usadefcon1** [LoneGazebo/Community-Patch-DLL#6925]
_1. Mod version
 8-16-2

_2. Mod list (if using Vox Populi only, leave blank):_

![Mods](https://user-images.githubusercontent.com/57153924/90591412-0f471880-e1b1-11ea-8d37-21ae778885bd.jpg)

_3. Error description:_ 

Spearman Showing Concert Tour Strength instead of Combat Strength.

![Spear](https://user-images.githubusercontent.com/57153924/90591467-31409b00-e1b1-11ea-9427-91d477f72c45.jpg)

**Comment by usadefcon1** [comment]
Note: This only happens when the Spearmen are embarked.

**Comment by ryanmusante** [comment]
Can you provide a link to production menu cheatsheet?

**Comment by silentreply** [comment]
I've seen this on pathfinders also.

**Comment by LoneGazebo** [comment]
Probably a lua error - can you give me your logs?

**Comment by usadefcon1** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5097822/Logs.zip)

**Comment by usadefcon1** [comment]
> Can you provide a link to production menu cheatsheet?

It's my own mod which adds an icon before the unit name, ie swords in front of swordsmen, shield in front of spearman, culture icon before amphitheater, production in front of forge, etc. It's pretty close to being done so I might just release it as a beta soon.
