### ISSUE TITLE
Air Units despawning

### ISSUE THREAD

**Issue by Murderologist** [LoneGazebo/Community-Patch-DLL#6926]
_1. Mod version (i.e Date - 4/17):_
8/16 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
Various Pick n Mix Mods , Air, Naval, Land Mega Mod

_3. Error description:_ 
Fighter, Bomber, Atomic Bomb, Nuclear Missiles Disappearing

_4. Steps to reproduce (optional):_
I was able to reproduce the units vanishing on a turn where I expended a great scientist resulting in a tech and new city state ally’s. On said turn each time I expended  the great person the most recently moved air units were deleted. Then it began to work fine for about 20 turns. Then I mad peace with over 7 CiVs and had one Capitulate and then Four of my bombers disappeared. It appears that when dramatic things happen in between turns for the player some units vanish. On a positive note. On this 8-16 version and the 6-19 version No missile, fighter or bomber has ever gone missing while on a carrier or being held as cargo on a ship. Units have only ever disappeared from cities and airbase tiles (pick n mix mod).

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Murderologist** [comment]
I've managed to get a save where on the same turn (279)  8 Bombers will disappear if you capitulate with Canada on the turn. Immediately after he accepted 8 Bomber units will disappear. 6 in St. Louis, 2 in New Orleans. If you advance to turn 280 without accepting his offer and then go ahead and offer him whatever and to capitulate (on turn 280) you will retain the units. The 8 units in question did perform an action on turn 279 so did many other air units and for some reason those 8 on that turn are targeted. 
 
I'm not able to put my MODS folder on the file size is to much but I have the save file and mods file if you'd like to see it first hand.

**Comment by LoneGazebo** [comment]
I would need your MODS folder to reproduce.

**Comment by Murderologist** [comment]
The file was to large to put it here any suggestions?

**Comment by yyEdge** [comment]
Can confirm it happens to me as well, after a great person spawns in modern era while at war, some of the planes disappeared, for me it was 6 zeros and 8 medium bombers (enhanced air for vp)

**Comment by Murderologist** [comment]
I’m not sure what other info I can provide. These are the observations I’ve seen. It has since started occurring randomly between turns. Sometimes I can go 10+ turns without air units disappearing but I cannot accurately reproduce it except for the one save file I have. The mod folder is to large to put on here. But this seems to be an issue restricted to cities and airbase tiles. Everything at sea is safe.

**Comment by JohannesGaessler** [comment]
I also experienced this issue with only Wonder Race and Really Advanced Setup (while playing on Linux via WINE).
Unfortunately I was not able to reproduce the issue and thus cannot provide files for debugging.

**Comment by Murderologist** [comment]
Still occuring in the lastest hotfix. Like I said before this is occuring when the player has a major event happen and the map is much more populated with WC going on plenty of wars everywhere and units everywhere. This time I produced it by purchasing one bomber and then declaring war on indonesia. As soon as i leave the leader screen the bomber i just purchased is gone.  Did it 5x in a row now.  Again unit only disappearing from cities still, nothing naval.

**Comment by ilteroi** [comment]
i have a lead ...

**Comment by LoneGazebo** [comment]
I think I’ve already got it in my version I pushed earlier

**Comment by LoneGazebo** [comment]
@ilteroi look at my changes to the checkvalidplot loops

**Comment by ilteroi** [comment]
i'm using your latest

**Comment by Murderologist** [comment]
OMG you've got a potential suspect!?  I did some more testing for you guys not sure how it helpful it is. I thought maybe because every civ was entangled in a war I thought I'd force peace between them all with IGE and me and indonesia be the sole civs in conflict. Still no joy. Purchase unit - declare war - units gone. I'll see if i can get a scenario where they don't vanish.

**Comment by LoneGazebo** [comment]
@ilteroi on my latest i've not seen a single airplane despawn

**Comment by ilteroi** [comment]
hate to break it to you, but the log says:

Triplane 1836 killed by -1
d:\sources\civ-vp\cvgamecoredll_expansion2\stackwalker\stackwalker.cpp (1072): StackWalker::ShowCallstack
d:\sources\civ-vp\cvgamecoredll_expansion2\cvunit.cpp (2328): CvUnit::kill
d:\sources\civ-vp\cvgamecoredll_expansion2\cvgame.cpp (9801): CvGame::updateMoves
d:\sources\civ-vp\cvgamecoredll_expansion2\cvgame.cpp (1725): CvGame::update
d:\sources\civ-vp\cvgamecoredll_expansion2\cvdllgame.cpp (486): CvDllGame::Update

only one instance though so far.

**Comment by Murderologist** [comment]
😭

**Comment by LoneGazebo** [comment]
@ilteroi possible that it died for 'correct' reasons, though (i.e. in a city that was taken by enemy)

**Comment by LoneGazebo** [comment]
The 'end turn' despawns I was seeing and replicating from user saves were happening in the jumptovalidplot code.

**Comment by JohannesGaessler** [comment]
I have obtained a save that reproduces the bug.
Version: 8-16-2
Mod List: Really Advanced setup, Wonder Race
To reproduce: buy WORLD MAP from Suleiman. When I do this one of my Bombers despawns.
Zip file with Logs, the save file, and the MODS folder: https://mega.nz/file/FAEQWSha#i6sIwvy_-hASaSfAzxSnQc-w44eJ1vYqSImSMix9yrw

When I originally encountered the bug, four of my Bombers despawned (I wasn't able to perfectly replicate the situation though).
Could this bug be related to memory issues?

**Comment by ilteroi** [comment]
> @ilteroi possible that it died for 'correct' reasons, though (i.e. in a city that was taken by enemy)

take a look at the callstack i posted before making such statements

**Comment by LoneGazebo** [comment]
@JohannesGaessler you are not on my 8-25 hotfix version, please try to reproduce on the hotfix.

**Comment by LoneGazebo** [comment]
@ilteroi I can't glean much from that callstack, what's your theory?

**Comment by JohannesGaessler** [comment]
@LoneGazebo Thanks for the pointer, using the 8-23-3 hotfix found in the CivFanatics thread seems to have fixed the issue for me.
I will finish my current game with the hotfix and monitor if any more planes go missing.

**Comment by LoneGazebo** [comment]
@JohannesGaessler that's good!

**Comment by ilteroi** [comment]
come on ... take a look at CvGame::updateMoves around line 9801.

1. apparently canEndTurnAtPlot fails for the plane, not sure why
2. then we call jumpToNearestValidPlotWithinRange(1) which must fail for an air unit

**Comment by LoneGazebo** [comment]
@ilteroi can't glean much because I'm not at my desktop this afternoon. :)

I think canEndTurnAtPlot fails because the unit is running out of moves. That's what I ran into for verifyvalidplot.

CvUnit::canRebase checks for getMoves() <= 0 - if it is the end of a turn, the unit has had its moves zeroed out, so it can't go anywhere. That's why I added the 'forced' check. I think if you follow the canRebase back, just add the bForced = true variable in the stack so that the unit ignores the getMoves() check.

**Comment by LoneGazebo** [comment]
Does that make sense?

**Comment by LoneGazebo** [comment]
CvUnit::canMoveInto needs a bForced pass through, as does canEndTurnAtPlot. That would allow you to set line 9785 as canEndTurnAtPlot(pLoopUnit->plot(), true).

**Comment by LoneGazebo** [comment]
sorry doing this without the IDE in front of me is a bit tricky.

**Comment by JohannesGaessler** [comment]
I've finished my current game with the hotfix.
I didn't notice any of my planes going missing (I periodically checked if the total number of planes I have is consistent with the number of planes built/lost in combat).
I didn't monitor if AI planes despawn but I was heavily attacked with bombers so I would assume that at most a small percentage of AI planes has despawned.
