### ISSUE TITLE
8/16 - AI not escorting units properly

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6927]
_1. Mod version (i.e Date - 4/17):_ 8/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
AI does not appear to be protecting its civilian units (most importantly, settlers). Several others have noted this on the forums. 

![image](https://user-images.githubusercontent.com/59859911/90605011-c05aac80-e1cb-11ea-80df-ec3e28786319.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by cdanger341** [comment]
Can confirm on 8-16-2 hotfix, but I feel like it's due to the AI pathfinding issues mentioned in other tickets.

**Comment by silentreply** [comment]
In the case I first posted, yes it is true the settler did not have far to go (I think they actually settled on the spot my unit was on the next turn), but I have been seeing this quite frequently and that example just happened to be the one I posted.

Here is another example from 8-23-3, where the warrior was actually escorting it previously, but then for some reason didnt expend full movement to cross the river with the settler. I also suspect the pathfinder movement cost issues may be affecting this as noted by cdanger above.

![image](https://user-images.githubusercontent.com/59859911/91471409-0e268300-e864-11ea-82e5-bc23c2d523de.png)

**Comment by silentreply** [comment]
@ilteroi Ok, so here is a very clear cut example. I've already been at war with this AI and want to block him from settling this area. The turn after I move my scout on the hill, he leaves the settler unprotected. But this is ok since if I were to capture he would easily recapture with 3 attacks. Thus I fortify on the hill, but the next move, he moves the settler unprotected, and the supporting units run off elsewhere..

I've already captured 2 of his settlers, this will be number 3. 

![image](https://user-images.githubusercontent.com/59859911/91778723-5fff3e00-ebc1-11ea-8c6f-345351dee5ba.png)
![image](https://user-images.githubusercontent.com/59859911/91778935-0c412480-ebc2-11ea-9b34-530ca026a3c0.png)

**Comment by ilteroi** [comment]
cannot reproduce with 9/2 ...
