### ISSUE TITLE
[8-16] Embarkation movement penalty

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6930]
I created promotion which changed (-3) movement of all units (of course all which are in UnitCombatInfos table until you fill it :)), but it doesn't work on Embarked units. They still have 3/3 moves regardless of having or not the promotion. Is there any other table column than MovesChange which applies to Embarked units as well? Is it a bug?

**Comment by Mileslewis** [comment]
<ExtraNavalMovement> is what you want.

**Comment by adaneslavo** [comment]
Works, thanks.

**Comment by adaneslavo** [comment]
Unfortunately there is crash:
Feature gives this promotion if unit enters its tile (LocationUnitFreePromotion). Promotion gives -3 MP. I Worker emkars on that tile and in the same tile gets the promotion game crashes. IF same think is done with Swordsman, it is not. I don;t have time to do more testing, if needed I will do them in few hours.

**Comment by Tekamthi** [comment]
i think the feature gives promotion stuff has never been correctly implemented.  Use lua instead to grant promo if possible

**Comment by adaneslavo** [comment]
Maybe it is time to fix it? Earlier [was Buildings_ClassNeededInCity not fixed](https://github.com/LoneGazebo/Community-Patch-DLL/issues/6585), so maybe at least this :P

**Comment by LoneGazebo** [comment]
It works fine.

**Comment by adaneslavo** [comment]
What may be the reason Worker crashes the game repeatedly, while combat unit don't? Same situation, same turn. His movement points go to 0, game hangs and CTD (it has 2 as Worker, and 3 as embarked worker).

**Comment by adaneslavo** [comment]
I did some experiment. Lowered malus to -1 and -2 MP and there was no crash. Additonally I checked other units (missionary, diplo, settler). CTD is only with -3 when you click on worker after embarking. Before clicking him game still works. He has 0/0MP on click.

**Comment by adaneslavo** [comment]
I did further test: changed LocalUnitFreePromotion to AdjacentUnitFreePromotion, and what is really interesting, I placed Worker on **land** tile; so it still used his 2/2MP. Even though game CTD; it means that lowering value of sea movement to 0 on worker is crashing the game.

**Comment by adaneslavo** [comment]
CTD file from last crash.
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5103433/CvMiniDump.zip)

**Comment by LoneGazebo** [comment]
Dropping movement to zero is not allowable in the DLL - too many checks rely on base movement being greater than 0.

**Comment by adaneslavo** [comment]
I noticed that when I set -2MP (MovesChange) it was set to minum of 1.
Strange is that other civilian units had set value to 0 and nothing happend.

**Comment by LoneGazebo** [comment]
Embarked units are handled as a special case.

**Comment by adaneslavo** [comment]
I did one more check.
Malus is -3 for WaterMovement.
Galley was dimnished from 3 to 1 (not 0)
Settler was set from 3 to 0 (no CTD)
Worker was set from 3 to 0 (CTD)

Can you just make this minimum to be set to 1 for civilians? I don't care if it will be 0 or 1 at the end, but I want to set the malus as I want to not cause CTD.

![obraz](https://user-images.githubusercontent.com/33016300/90782742-82f73b80-e2ff-11ea-9a51-5185a431c105.png)
![obraz](https://user-images.githubusercontent.com/33016300/90782797-91455780-e2ff-11ea-8fec-c8c86ce7df15.png)

**Comment by LoneGazebo** [comment]
Embarked units are  a special case. I'll see if there's a spot I can add a minumum value to prevent divide by zero errors.

**Comment by azum4roll** [comment]
Speaking of movement penalty, does the Boarded status still last 2 turns?
