### ISSUE TITLE
Feature Request - link Worlds table variables to AssignStartingPlots.lua

### ISSUE THREAD

**Issue by Tekamthi** [LoneGazebo/Community-Patch-DLL#6933]
_1. Mod version (i.e Date - 4/17):_

any recent version

_2. Mod list (if using Vox Populi only, leave blank):_

VP only

_3. Error description:_ 

The Worlds table contains variables for tweaking number of natural wonders and map sizes etc -- some of these have a direct effect as expected, while some must be changed in conjunction with static variables inserted into assignstartingplots.lua and possibly other files.

Requested feature: instead of static variables, the assignstartingplots and others should reference the Worlds table variables for easier customization.

_4. Steps to reproduce (optional):_

try the following sql mod:

UPDATE Worlds
SET DefaultPlayers = 43, DefaultMinorCivs = 20, FogTilesPerBarbarianCamp = 10, NumNaturalWonders = 17, GridWidth = 180, GridHeight = 94, MaxActiveReligions = 11
WHERE Type = 'WORLDSIZE_HUGE';

Most of these seem pretty self-explanatory, and some are, but some aren't.  For example, NumNaturalWonders requires that assignstartingplots has the following array variable tweaked manually as well:
	local worldsizes = {
		[GameInfo.Worlds.WORLDSIZE_DUEL.ID] = 2,
		[GameInfo.Worlds.WORLDSIZE_TINY.ID] = 3,
		[GameInfo.Worlds.WORLDSIZE_SMALL.ID] = 4,
		[GameInfo.Worlds.WORLDSIZE_STANDARD.ID] = 5,
		[GameInfo.Worlds.WORLDSIZE_LARGE.ID] = 6,
		[GameInfo.Worlds.WORLDSIZE_HUGE.ID] = 17
		}

(around lines 6170+)

this lua, and others that control number of religions etc, should reference the Worlds table values rather than these static values

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Very easily doable, but we'll need inputs what should be the correct value for each world size.

**Comment by Tekamthi** [comment]
in my experience, even with making all of the changes i listed in that sql (ie an even bigger "huge" map, usually on continents+ or fractal), the number of NWs never hits 17 (I chose this number cuz there are 17 NWs already in VP iirc).  On pangaea presumably it would be higher, but I've never tried.

The lua still searches for valid regions for NWs and doesn't find enough to use up all 17 available NWs... with the settings above, it usually places 13-14 NWs, and with the default 'huge' map maybe 12-13.   I'd thus suggest 12 is a better default for huge than 7.  That said, you could just put 17 for all of these and the game would still limit placements based on the other conditional checks for NW placement... in this sense these values are somewhat redundant.  Maybe there should be no max NWs, and just let the lua determine how many to place based on map conditions

**Comment by azum4roll** [comment]
It could potentially make happiness too easy for Polynesia.

There still needs to be a cap, but maybe we can make it looser.
