### ISSUE TITLE
Strategic Resources Unavailable After Deal Expiration

### ISSUE THREAD

**Issue by mtmuehl** [LoneGazebo/Community-Patch-DLL#6934]
_1. Mod version (i.e Date - 4/17):_
8/16 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
3/4 UC

_3. Error description:_ 
I have 8 Horses listed as being exported, even though I have no active deals. It's not just visual because I can't build units or buildings that would require more Horses

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Please provide the save

**Comment by mtmuehl** [comment]
[Sejong_0270 AD-1800.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5100048/Sejong_0270.AD-1800.zip)

**Comment by LoneGazebo** [comment]
Please share custom civ

**Comment by mtmuehl** [comment]
https://forums.civfanatics.com/resources/colonialist-legacies-tlingit-for-vp.27167/

**Comment by mtmuehl** [comment]
https://forums.civfanatics.com/resources/colonialist-legacies-tlingit-for-vp.27167/

**Comment by mtmuehl** [comment]
https://forums.civfanatics.com/resources/colonialist-legacies-tlingit-for-vp.27167/

**Comment by mtmuehl** [comment]
https://forums.civfanatics.com/resources/colonialist-legacies-tlingit-for-vp.27167/

**Comment by LoneGazebo** [comment]
thanks

**Comment by LoneGazebo** [comment]
![image](https://user-images.githubusercontent.com/7849458/90777601-4278cd00-e2c1-11ea-9aeb-5d2e30b4672f.png)

**Comment by LoneGazebo** [comment]
There are quite a few mods here - please zip and share the non-VP mods from your MODS folder.

**Comment by mtmuehl** [comment]
Sorry, I thought since only Tlingit were in the game that would be the only one required. The zipped mods are too large to upload to github, so I'll try a game with custom civs and see if it comes up again

**Comment by LoneGazebo** [comment]
You can upload to somewhere like Mega and share it that way.

**Comment by mtmuehl** [comment]
https://gofile.io/d/lKON4N

**Comment by LoneGazebo** [comment]
I need the save that occurs the turn the resources go missing without a proper renewal.

**Comment by mtmuehl** [comment]
Here is two turns before the deal runs out, and the turn the deal runs out.

[saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5106543/saves.zip)

**Comment by LoneGazebo** [comment]
@mtmuehl did you test this for me?

**Comment by mtmuehl** [comment]
Been traveling so haven't had a chance to yet, I'll be able to try it tomorrow evening
