### ISSUE TITLE
Can't Spread Religion to City States

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#6935]
_1. Mod version (i.e Date - 4/17): 8/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:

It doesn't give me the option to spread my religion, but only for some city states.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/90749753-82997900-e2dc-11ea-936e-b9e05f3618f9.jpg)
![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/90749757-83caa600-e2dc-11ea-89b9-1ebccac27937.jpg)
![Civ5Screen0002](https://user-images.githubusercontent.com/49090452/90749760-84633c80-e2dc-11ea-8e9e-0a7e11929028.jpg)
![Civ5Screen0003](https://user-images.githubusercontent.com/49090452/90749766-84fbd300-e2dc-11ea-893a-9a96b585136a.jpg)
![Civ5Screen0006](https://user-images.githubusercontent.com/49090452/90749767-85946980-e2dc-11ea-9f74-676a51e5792b.jpg)
![Civ5Screen0007](https://user-images.githubusercontent.com/49090452/90749769-862d0000-e2dc-11ea-82fd-ef940bcb72ca.jpg)

**Comment by bsesar** [comment]
@Aqinu , perhaps your missionary is too far from the city? I think it has to be within one hex of the city.

**Comment by Aqinu** [comment]
@bsesar Thank you, you are right, I always forget that only for diplomatic units works within their borders and for religious units only from adjacent, don't know why is not applied the same logic for both though...
