### ISSUE TITLE
8/16 - City on top of marble can not build stone works

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#6936]
_1. Mod version (i.e Date - 4/17):_ 8-16-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
May be related to recently closed issue #6908
![image](https://user-images.githubusercontent.com/59859911/90845227-a50ab100-e333-11ea-8eb9-f6ca0b9bddae.png)
![image](https://user-images.githubusercontent.com/59859911/90845175-8f958700-e333-11ea-95a9-19d80fa735b6.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Worth noting that Amber and Uranium affect whether Stone Works can be built but aren't mentioned in the description.

**Comment by RecursiveVision** [comment]
Yeah, you're right - that's it. @bsesar
