### ISSUE TITLE
8/16 Eventwindow won't open when Mod is used as DLC (Multiplayer workaround)

### ISSUE THREAD

**Issue by Lamandus** [LoneGazebo/Community-Patch-DLL#6937]
This is the first time reporting here, so bear with me.
I am not sure if this is the first version with the problem, but I had a hiatus of nearly a year, so I can't exactly pinpoint the time when it broke.

When using the Mod as a DLC (Multiplayer workaround, CreateMP(); in Firetuner, that jazz), when reaching the point of you needing to choose something because of an event, you aren't able to open the window. The Events work when using the Mod as a Mod, so that works.
I am not sure if you are keen on fixing that issue in any way, because that problem is "not your fault" per se. The DLC version works fine and without softlocks when Events are completly swtiched off.

**Comment by LoneGazebo** [comment]
events are not entirely MP safe because of desync potentials.

**Comment by Dromin** [comment]
Problem cause & fix: https://github.com/LoneGazebo/Community-Patch-DLL/issues/6241#issuecomment-593061394

**Comment by Lamandus** [comment]
@Dromin thank you for the link! I never would have seen that!

**Comment by Dromin** [comment]
@Lamandus You're welcome :)
