### ISSUE TITLE
God of Open Sky

### ISSUE THREAD

**Issue by Tascani** [LoneGazebo/Community-Patch-DLL#694]
On October 02 2015 version - automatic installer:

"God of the Open Sky: +2 Faith from Pastures, +1 Culture for every 3 Plains tiles worked by the city."

In game tooltip and result is different.
Seems to give a lot more.
A new city  with 1 pop gave me +8 in culture.

**Comment by LoneGazebo** [comment]
Can't replicate, sorry.

**Comment by Tascani** [comment]
So its on my end I guess:
I can replicate it though.

reinstall:
- cleaned cache
- deleted mods in UserData
- removed EUI
- downloaded CPP version october 12
- installed CPP with automatic installer

issue:
- God of open Sky  gives massive Culture:
+1 Culture from every 2 Plains tiles near a city

Check screenshot:
http://imgur.com/lhItqOu

**Comment by LoneGazebo** [comment]
'near a city' = 2 tiles away. So if you have 12 adjacent plains, you get 6 culture.

G

**Comment by Tascani** [comment]
Oh. That's what the naming means. Thank you for this.
At any rate - there is an oversight/error:

The manual / unified changelog lists the pantheon with a different effect than what is in game:

manual:
God of the Open Sky: +2 Faith from Pastures, +1 Culture for every 3 Plains tiles worked by the city.

in-game:
God of the Open Sky: +2 Faith from Pastures, +1 Culture from every 2 Plains tiles near a city, 

I am too new to this game to speak about balance but one version needs to be corrected.
Same applies to "Sacred Path" pantheon.

Thank you for your work on the CPP. :)

**Comment by LoneGazebo** [comment]
Ah, the 'manual' is a bit outdated.
