### ISSUE TITLE
CSBullyValueModifier vs CSBullyMilitaryStrengthModifier

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#6948]
_1. Mod version: 08/16

_3. Error description:_ [DLCChanges.sql](https://github.com/LoneGazebo/Community-Patch-DLL/blob/master/Community%20Balance%20Patch/Balance%20Changes/Leaders/DLC/DLCChanges.sql) gives Zulu +100% tribute value at lines 30-32, which is supposed to be the Mongols (the Trait is wrong). So Zulu is getting both, +50% CS bully strength AND +100% CS bully Value.

I don't know what the math between these two values is in the current tribute system, but the end result is that they both directly increase the amount of tribute you get. Because the threshold for CS bullying is trivially low now, and tribute value is a direct function of your bully strength, the only difference between these two values is their wording in the UA. 

IMO, we should only move forward using one of these trait columns. Mongolia could keep the ability to ignore defense bonuses while Zulu just gets the straightforward bully modifier

**Comment by LoneGazebo** [comment]
Zulu bonus is for military power, Mongol is raw value towards entire test.
