### ISSUE TITLE
UnitPromotions_YieldChanges and UnitPromotions_YieldModifiers don't work

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#6949]
_1. Mod version (i.e Date - 4/17):_

_2. Mod list (if using Vox Populi only, leave blank):_ Nubia for VP
Other mods that use these tables: 
- MUC4VP, 
- JFD's Papal States for VP, 
- CL's Canada for VP

_3. Error description:_ UnitPromotions_YieldChanges and UnitPromotions_YieldModifiers don't work.
These tables are supposed to give flat and % yields when garrisoned in a city, but neither of them do anything. 
See picture of example of unit with the correct promotion in a 1 population city, but no bonus production
---------------------------
4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/33136027/90981359-c29b6e80-e51d-11ea-91db-cba4c90fd0c7.png)

**Comment by LoneGazebo** [comment]
It was deactivated for performance reasons, I'll re-enable behind a YIELD_MODIFIER_FROM_UNITS define.
