### ISSUE TITLE
ExCE and CTDs

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#695]
I've been running a few AI-only games through Firetuner, just to test the stability of my mods, and so far I can get through 100+ turns no sweat on a few of them (8~ civs, plus Mercenaries (which has a lot of Lua) and Claims & Colonies (which has less, but still which fires more often than ExCE)). However, on ExCE, I keep getting a persistent crash around the turn 80-90 mark. I can't trace anything of note in the logs, and the Lua in the mod is comparatively light to the Lua in those which have been stable. I'm also unable to ascertain any specific actions of the AI, as each time I re-load the save I can get a few turns further before it crashes. So I was wondering if there was something you could tell me by looking at the crash dump (if you don't mind) - this is the mod with attrition, and so naturally makes a lot of calls to the DLL, so I'm wondering if it's something in there. Would really appreciate any help.

Crash Dump: https://www.dropbox.com/s/007rcyut1f7hvqw/CvMiniDump.dmp?dl=0
Crash Dump 2: https://www.dropbox.com/s/akxe1ip5mqfjh8l/CvMiniDumpv12.dmp?dl=0
Crash Dump 3: https://www.dropbox.com/s/lhfrdj420dch4ld/CvMiniDump3.dmp?dl=0

I was using the CP version from the 8th, so I'll update and edit my findings from that. But I'd still appreciate a look, as its definitely isolated to with ExCE.
EDIT: Indeed, it still crashed at turn 95~, so I've included the mini dump from that, too.
And just to be scientific about it, I've added a third where it crashed at turn 65~ (worse, I know).

Please let me know if there's anymore info you need.

**Comment by LoneGazebo** [comment]
I'll take a look, yep. Are you using the very latest version(10-12)? If not, I won't be able to trace the stack very easily.

G

**Comment by JFDaly** [comment]
The last two crash dumps were from the latest version, whilst the first was from the previous. So you can ignore the first without impairing the search, I'd say, as I had the same result on both.

**Comment by LoneGazebo** [comment]
I checked  both dumps - each of them stacked out to lua, so there wasn't a proper trace. Can you link me your debug copy of ExCE so I can test a version with that? Perhaps if I'm hooked into the DLL while the game is running it'll give me a proper crash.

G

**Comment by JFDaly** [comment]
Sure, below is the latest version as of when it crashed (each time):

https://www.dropbox.com/s/j4qfwxgycs89nd0/JFD%27s%20Exploration%20Continued%20Expanded%20%28v%208%29.civ5mod?dl=0

**Comment by LoneGazebo** [comment]
Great, thanks. You were testing just with the CP, yes?

Also, if you ever need any additional AI functionality with your mods (i.e. to avoid some of the pitfalls of E&D), feel free to ask.
G

**Comment by JFDaly** [comment]
Yup, just the CP.

Thanks. I'll probably have to take you up on this for Piety, but I'll take some time to articulate what I'd need. ExCE and Claims&Colonies are no problem for the AI, as far as I can tell.

**Comment by JFDaly** [comment]
So, since you ascertained that the crashes were Lua related, I made some further tests. I had originally suspected the issue was coming from the Attrition component (which is what led me to ask for help), but I've actually narrowed it down to the Exploration component. I'll edit this posts if I come up with anything else, but I don't think that it's anything to do with the DLL after all (as the Attrition component ran with no crashes with Exploration disabled, but not vice versa).

**Comment by LoneGazebo** [comment]
Interesting. I know some users have had crashes related to your resources in the diplomacy screen. How many do you add, and - with More Luxuries - what's the grand total? I wonder if we're hitting a memory cap somewhere?

**Comment by JFDaly** [comment]
Ah, I undid my edit, as I may have been mistaken. I've been running games back-to-back and the latest one got to turn 200 without crashing, with the resources enabled. So now I'm not sure, but it's almost certainly not the core part of Exploration (i.e. the stuff that handles the Great Recon units).

Regardless, I add 12, whilst Barathor adds 10 in MLs.

I'm going through the list of sub-components to Exploration, disabling each by each to see if it crashes before the turn 200 mark. It definitely does with all active, and it definitely doesn't with only the core part active (or with only Attrition active). I'll report back if I can narrow it down consistently.

**Comment by LoneGazebo** [comment]
Sounds good. Also, why were feathers breaking the TP?

G

**Comment by JFDaly** [comment]
Tbh, I can't remember. It was just reported a while back that the two didn't play nice together. But I'll take a look - as perhaps that's no longer true.

Meanwhile, no real luck on the CTD front. But if there's nothing more the crash dumps can tell you, you may as well close this post, as it certainly seems an entirely Lua issue.

**Comment by Hokath** [comment]
Feathers broke because they spawned a) in jungle, b) next to each other. 
CBP trading post likes neither of these things

Happy to see you're tracking this one down. It needs to be sent back to lua hell.

**Comment by JFDaly** [comment]
Hm, I ran an AI-only game with only the latest beta of the CP that you've given me, Gazebo, and it crashed around the turn 285 mark. I'll run a few more games to see if this was an anomaly, but here's the [mini dump](https://www.dropbox.com/s/007rcyut1f7hvqw/CvMiniDump.dmp?dl=0) in case it's of any use.

**Comment by LoneGazebo** [comment]
I've caught a few CTDs, yep. Maybe pushing a few more ExCE elements (the terrain stuff I'm working on) will help with stability as well.

G

**Comment by JFDaly** [comment]
Yea, maybe. But the Lua in ExCE really is light. I mean, I've tested my Mercenaries mod, which caches a lot of data and evaluates it each turn, and no CTDs whatsoever. Ditto my Claims & Colonies mod, and my 8 most recent Civilization updates. These are the only functions I have that I could see pushed into the DLL:

* When a Great Recon Unit (Great Scout/Explorer/Adventurer) founds a city, it generates Golden Age Points. Is called via GameEvents.UnitCityFounded(). So maybe that could become a Unit_YieldOnCityFounded table or something (or better a UnitPromotion_YieldOnCityFounded). Of course, the benefit of doing this in Lua is that I can have the amount change depending on game speed.
* When a Scout/Explorer/Adventurer is promoted to level 5, it becomes a Great Scout/Explorer/Adventurer. Perhaps a Unit_AutomaticClassUpgrades table or something, with a column to specify the level.

So I'm anticipating some kind of database issue (yesterday, all tests pointed to the resources), and any other crashes (which are sparse, compared to the persistent ones with the ExCE resources active) are probably unrelated.

**Comment by LoneGazebo** [comment]
I'll keep hunting for CTDs on my end. The lua you mention seems light enough, so I'm not too worried about that.

G

**Comment by StangleKhan** [comment]
I'm not sure how much help this is but I can confirm that any game I play with ExCE seems to CTD between 250-350 turns. It happens during the AI's turn and on every map I've tried. If I go back and reload a save from a few turns back it sometimes fixes it. Most of the time it CTDs during the exact same AI's turn though.

**Comment by LoneGazebo** [comment]
I'd be interested to see if this is, perhaps, deal related. Do any ExCE resources come online around that time? Also, if you have logging enabled, does the AI initiate a deal around that time? (You can see AI deals in DiplomacyMessages log)

G

**Comment by StangleKhan** [comment]
I'm usually playing on marathon so I wouldn't be surprised if something like cedar or oak was revealed at that time. I don't have logging enabled but I'll enable it. I'm not familiar with coding beyond some basic concepts so I'm helpless when it comes to lua or DLL. Could the AI be attempting to trade a bonus resource? Or maybe that AI player has built some improvement on the spot where the resource spawns?

**Comment by LoneGazebo** [comment]
Latter shouldn't CTD, but the other issue (improper trade) might.

G

**Comment by JFDaly** [comment]
I did consider that the AI might be trying to trade bonus resources, as the other day I thought I'd narrowed it down to bonuses. I'll run a few more tests with just luxuries enabled to see. I'll also keep an eye on the DiplomacyMessages log.

And yes, Sulphur (Gunpowder) and Rubber (Industrialization) become available around the late game, and they're both bonus resources. I'll disable these specifically after some tests.

**Comment by JFDaly** [comment]
This is the [Mini Dump](https://www.dropbox.com/s/007rcyut1f7hvqw/CvMiniDump.dmp?dl=0) from a CP+ExCE only game in which it crashed at turn 300~, and in which it crashes everytime I try to load the last autosave at this turn (also crashes on the two auto-saves previous, at turn 295 and turn 290). Maybe it tells you something?

**Comment by LoneGazebo** [comment]
I loaded it up and the stack traced out to the disassembly (which generally indicates that the crash occurred outside of the DLL). Send me the mod files you are working with and I'll load them for a test.

G

**Comment by JFDaly** [comment]
[Here you go](https://www.dropbox.com/s/3u7s6jhdnu0u7o2/Mods.rar?dl=0)  I unfortunately don't have the save, but the settings were Duel map, Quick speed. Only the resources were active at the time - no Lua whatsoever (the Lua files aren't active).

**Comment by LoneGazebo** [comment]
Just ran a quick/duel through to the end of a time victory with no crash. Any settings in the ExCE I need to do?

**Comment by JFDaly** [comment]
That sounds about right. The biggest frustration with this crash is that it doesn't always happen. You can try switching on all the Exploration components (MODS\JFD's Exploration Continued Expanded (v 8)\JFD_ExCE_UserSettings.sql) and see what happens. Just set everything to 1.

**Comment by LoneGazebo** [comment]
I should note that no resources are spawning. I manually placed a bunch on the map in the 2nd game I'm running now.

**Comment by JFDaly** [comment]
Yea, I disabled the script that places the resources, just to make sure it's not that.

**Comment by JFDaly** [comment]
Crashed after 240, and getting a persistent crash on load. This time I have the [save](https://www.dropbox.com/s/c97r74o41s9mkm9/AutoSave_0240%20AD-1650.Civ5Save?dl=0). You'll need [IGE](https://www.dropbox.com/s/12bk2hmqnsa5jnt/Ingame%20Editor%20%28v%2039%29.rar?dl=0) to run it, as I had that enabled this time. Nothing else though, and just the resources enabled. Do you think this crash-on-load could be because the autosave was made on auto-run?

**Comment by LoneGazebo** [comment]
Okay. Game two went fine as well, game 3 will have all settings. I'll keep running it (duels are nice for me to test AI behavior as well).

**Comment by LoneGazebo** [comment]
Loaded your save and it crashed for me! Running stacks now...

**Comment by LoneGazebo** [comment]
And it still goes to disassembly. Wtf.

**Comment by JFDaly** [comment]
I wonder if somehow the mod project for ExCE has become corrupt. Perhaps I should move everything into a new project.

**Comment by LoneGazebo** [comment]
I'm not sure. Generally speaking if there's a deep problem in sql/xml/lua it'll show up in a log or something. It may be something else in the DLL that's crashing oddly. I'd hold off before that big of an effort.

**Comment by LoneGazebo** [comment]
Alright, another 3 debug runs with various settings enabled/disabled and no crash. I'm uploading a new version of the CP for you, perhaps I've somehow fixed the bug that was CTDing for you.

Also, a new table:

''
	<Table name="Belief_SpecificFaithUnitPurchase">
		<Column name="BeliefType" type="text" reference="Beliefs(Type)"/>
		<Column name="UnitType" type="text" reference="Units(Type)"/>
	</Table>''

**Comment by LoneGazebo** [comment]
And here's the link: https://mega.nz/#!eU1zTLSR!QixP7kwRn4tfwD4zM_uO9L8-KMRGdNkYgjlW6i8IOB0

**Comment by JFDaly** [comment]
Awesome, hopefully so. I'll run some ExCE games myself and report with my findings. I'll also make use of the table (which is for C&C) and report back on that, too.

**Comment by JFDaly** [comment]
Hm, regular faith purchasing of units with Holy Warriors/Religious Fervour appears to have broken. And Belief_EraFaithUnitPurchase works only when Belief_EraFaithUnitPurchase is filled with the eras which unlock the units specified in the former table.

**Comment by JFDaly** [comment]
And [crash] (https://www.dropbox.com/s/007rcyut1f7hvqw/CvMiniDump.dmp?dl=0) at turn 345~, with the same issue of trying to load the [autosave](https://www.dropbox.com/s/fem6786od0p66mj/AutoSave_0345%20AD-1925.Civ5Save?dl=0) crashes it, too. At a real loss...

**Comment by LoneGazebo** [comment]
Dang and dang. I'll work on it today.

**Comment by LoneGazebo** [comment]
The save loaded, and then crashed when I hit next turn...we'll see where this goes.

G

**Comment by LoneGazebo** [comment]
Okay, okay, I think I finally figured it out. The impassable terrain data had a char value instead of a bool in one spot, and I think that was corrupting the map's data, causing a crash on load/save/use.

**Comment by Hokath** [comment]
so like an explorer walking onto ice or something? Hence why seems to occur mostly in early renaissance?

**Comment by LoneGazebo** [comment]
Oh, this issue is only related to the beta I'm working on with JFD. It's tough to explain, but every map tile now has two boolean values for impassability (global and team), and the latter was assigned an incorrect value type (char instead of bool) during map gen. It'd work as long as you didn't quit, but qutting/reloading = CTD.

**Comment by JFDaly** [comment]
At least that's hopefully one mystery CTD solved.
