### ISSUE TITLE
Adopting Industry is not awarding gold for constructed buildings

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#6950]
_1. Mod version (i.e Date - 4/17):_
June 19th (5.6.19)​

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
After adopting Industry policy branch, I am supposed to be awarded gold for constructing a building. No such award is being provided in the 20 turns since I took this policy.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by pineappledan** [comment]
The Industry opener does not give gold on construction; it gives +100% production to seaports and train stations

The yields on construction was changed to science, and moved back to Mercatilism

**Comment by briantjack** [comment]
> The Industry opener does not give gold on construction; it gives +100% production to seaports and train stations
> 
> The yields on construction was changed to science, and moved back to Mercatilism

Was somebody planning to update the "adopt Industry" tooltip to reflect this?

**Comment by briantjack** [comment]
While we're on the subject, are there any other policy tooltips that display wrong information?

**Comment by LoneGazebo** [comment]
The industry opener says:

Industry provides bonuses to empires focused on  Gold and Production. Adopting Industry grants: +100% Production speed of Train Stations and Seaports.[NEWLINE][ICON_BULLET] -5% [ICON_GOLD] Gold needed for purchases.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Each Industry policy unlocked grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] -5% [ICON_GOLD] Gold needed for purchases.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting all Policies in Industry grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building [COLOR_POSITIVE_TEXT]Broadway[ENDCOLOR]. [NEWLINE][ICON_BULLET] Doubles the Empire-Wide [ICON_HAPPINESS_1] Happiness value for owned Luxuries. [NEWLINE][ICON_BULLET] Specialists gain +2 [ICON_PRODUCTION] Production and [ICON_GOLD] Gold.[NEWLINE][ICON_BULLET] Allows for the purchase of [ICON_GREAT_MERCHANT] Great Merchants with [ICON_PEACE] Faith starting in the Industrial Era.

Says nothing about. gold for building construction.

**Comment by briantjack** [comment]
The industry opener says:

 

SET Text = '[COLOR_POSITIVE_TEXT]Industry[ENDCOLOR] provides bonuses to empires focused on [ICON_GOLD] Gold and [ICON_PRODUCTION] Production.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting Industry grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] 10 [ICON_GOLD] Gold every time you construct a building. Scales with Era. [NEWLINE][ICON_BULLET] -5% [ICON_GOLD] Gold needed for purchases.[NEWLINE][ICON_BULLET] Unlocks the [COLOR_CYAN]Depots[ENDCOLOR][NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Each Industry policy unlocked grants:[ENDCOLOR] [NEWLINE][ICON_BULLET] -5% [ICON_GOLD] Gold needed for purchases.[NEWLINE][NEWLINE][COLOR_POSITIVE_TEXT]Adopting all Policies in Industry grants:[ENDCOLOR][NEWLINE][ICON_BULLET] Unlocks building [COLOR_CYAN]Broadway[ENDCOLOR]. [NEWLINE][ICON_BULLET] +1 [ICON_HAPPINESS_1] Happiness for every owned Luxury. [NEWLINE][ICON_BULLET] Specialists gain +1 [ICON_PRODUCTION] Production and [ICON_GOLD] Gold.[NEWLINE][ICON_BULLET] Allows for the purchase of [ICON_GREAT_MERCHANT] Great Merchants with [ICON_PEACE] Faith starting in the Industrial Era.'

 

This is where gold is mentioned for building construction.

 

But this is my error – not yours. This text is not within the VP mod but rather within the Community Patch Mod Compatibility mod, managed by Techpriest Enginseer. I’m sorry for the trouble.

**Comment by RecursiveVision** [comment]
@briantjack Email replies can reveal your email address jsyk. In case you didn't intend on publicly displaying it, I removed it from your comment, along with the extra data (to/from stuff) not part of your reply.
