### ISSUE TITLE
Incorrect espionage possible outcomes % (35% being killed chance is actually like 95%-100%), Inconsistent spy rank modifiers of Special Agents (70% and 105% for two different Special Agents)

### ISSUE THREAD

**Issue by EtOpIST** [LoneGazebo/Community-Patch-DLL#6952]
_1. Mod version (i.e Date - 4/17):_
6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Chance for my spies to be killed while stealing technology is shown 35% while actually it is much much higher. I've attached 2 saves: China killed my spy like 29 times from 30 in the first save so I was able to steal the technology only once and Portugal killed my spy every single time like 50 times from 50 in the second save. So it seems like either it's an UI error displaying wrong % for possible espionage outcomes or those outcomes are not calculated as intended.

Also Irina and Mikhail are both Special Agents but their spy rank modifiers are different: 70% for Irina and 105% for Mikhail.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5117449/saves.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Irina](https://user-images.githubusercontent.com/11495270/91040280-fe6a2d00-e61e-11ea-9bde-6fe5c8d428c5.png)
![Mikhail](https://user-images.githubusercontent.com/11495270/91040288-032ee100-e61f-11ea-8898-28c1ea76ef50.png)

**Comment by LoneGazebo** [comment]
The percentages are correct, however the 'random seed' that is rolled for each test does not change on reloading a save, so the outcome will always be the same on a reload of a save.

**Comment by RecursiveVision** [comment]
@LoneGazebo OP said that he made repeat attempts and they continuously failed.

**Comment by EtOpIST** [comment]
> The percentages are correct, however the 'random seed' that is rolled for each test does not change on reloading a save, so the outcome will always be the same on a reload of a save.

Thanks for the reply. I chose "New random seed" option for this game. Why isn't it working? Moreover I tried like 20 times to move some units before ending the turn after loading the save putting those units in different locations each time for variety - the same result, my spy getting killed each time by Portugal. And how was possible that I managed to eventually steal technology from China if the random seed was always the same?

**Comment by LoneGazebo** [comment]
New random seed does not function, it is a 'dead' option. It was buggy to begin with.

**Comment by LoneGazebo** [comment]
Possible that one of the parameters that feeds into the RNG seed altered slightly - we use different variable inputs to simulate randomness, there's a small chance something changed in someone's empire and that changed the RNG seed slightly.

**Comment by EtOpIST** [comment]
And there is still an issue with 70% and 105% spy rank modifiers for different spies with the same rank Special Agent which I showed on the attached screens.

**Comment by EtOpIST** [comment]
> Possible that one of the parameters that feeds into the RNG seed altered slightly - we use different variable inputs to simulate randomness, there's a small chance something changed in someone's empire and that changed the RNG seed slightly.

Hm, interesting... Is it known what parameters random seed depends on? And is it possible for a human player to make some actions before ending the turn to change the random seed? Seems like moving units did not affect the random seed in my game.

**Comment by EtOpIST** [comment]
For example, if I make some deal with one of the AIs before ending the turn can it be "the slight change" to one of the RNG parameters?
