### ISSUE TITLE
UI/Pather considers civilians to have more movement than they have

### ISSUE THREAD

**Issue by Necamijat** [LoneGazebo/Community-Patch-DLL#6953]
_1. Mod version (i.e Date - 4/17):_ 8/23 (hotfix)

_2. Mod list (if using Vox Populi only, leave blank):_ UI - Improved City View

_3. Error description:_ UI and pathing considers civilians to have 1 more movement speed than they do. It seems to happen after getting a 2nd policy (in any tree)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:

1. Log files :
[Logs zip.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5118154/Logs.zip.zip)

2. Save game:
[Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5118160/Save.zip)

4. Screenshots:
![20200824135734_1](https://user-images.githubusercontent.com/53052880/91051443-6f5e1480-e620-11ea-9fb6-e9778cafcb75.jpg)

**Comment by RecursiveVision** [comment]
Use the most recent hotfix.

**Comment by bsesar** [comment]
@RecursiveVision According to the description of this particular issue, the mod version used is 8/23, which I believe is the latest hotfix. If that is the case, perhaps the issue should be reopened?

**Comment by bsesar** [comment]
@Necamijat Would you please confirm that you have used the latest hotfix when encountering this issue?

**Comment by RecursiveVision** [comment]
Yeah, already realized the error - see #6954
