### ISSUE TITLE
Warriors receive wrong Barbarian bonus

### ISSUE THREAD

**Issue by Necamijat** [LoneGazebo/Community-Patch-DLL#6955]
_1. Mod version:_ 8/23 hotfix

_2. Mod list (if using Vox Populi only, leave blank):_ UI Improved City View

_3. Error description:_ Warriors seem to get +53% strength against Barbarians, instead of +33%

---------------------------
Supporting information:

1. Log files:
[Logs zip.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5118200/Logs.zip.zip)

2. Save game (Unfortunately, the only save I have is from far ahead into the game):
[Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5118201/Save.zip)

4. Screenshots:
![20200824135225_1](https://user-images.githubusercontent.com/53052880/91051819-ed222000-e620-11ea-8519-1b32cf4030b1.jpg)

**Comment by RecursiveVision** [comment]
Playing on King or Emperor difficulty? There's an additional 20% bonus.
