### ISSUE TITLE
CvDealAI::GetTradeAgreementValue

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6957]
What is a "trade agreement"? It doesn't seem to be a valid deal item - so I'm thinking delete all code related to it, unless it has a use I'm not aware of.

**Comment by RecursiveVision** [comment]
Likewise for TRADE_ITEM_UNIT and TRADE_ITEM_PERMANENT_ALLIANCE.

**Comment by LoneGazebo** [comment]
They are not used.

**Comment by RecursiveVision** [comment]
Cleanup time! 👍 

Time to SWEEP, SWEEP, SWEEP!
