### ISSUE TITLE
MountainPass

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6958]
I tried to make new promotion allowing passing mountain in many ways, but still cannot find the solution.
First, I tried to use HoveringUnit value in UnitPromotions:
![obraz](https://user-images.githubusercontent.com/33016300/91084515-68e59200-e64c-11ea-9e40-b7c0004f42a9.png)
Unfortunately there are bunch of problems: HoveringUnit cannot be used without CanMoveImpassable; CanMoveImpassable allows to move on Ice, which I don't want; HoveringUnit makes units ignore Roads and Railroad and other terrains (it is flying probably).

Later I tried to use UnitPromotions_Terrains, but it didn't work too:
![obraz](https://user-images.githubusercontent.com/33016300/91084697-b235e180-e64c-11ea-800d-879fa3beef6f.png)

Do you know other way to implement this feature with current build?
Can you make it possible? Like with Incan Trait?
![obraz](https://user-images.githubusercontent.com/33016300/91084777-ce398300-e64c-11ea-9817-97b7473b5541.png)

**Comment by pineappledan** [comment]
Promotion Column 'CanCrossMountains' has got you

**Comment by adaneslavo** [comment]
Nope it is not working.
![obraz](https://user-images.githubusercontent.com/33016300/91172115-f2907080-e6db-11ea-9dd2-b88c1ed902c1.png)
 ![obraz](https://user-images.githubusercontent.com/33016300/91172171-04721380-e6dc-11ea-8b53-804383d9b0c9.png)

**Comment by gwennog** [comment]
In his mod, Promotions - Terrain Crossing, WHoward change value in CustomModOptions to 1 for Promotions_cross_mountains

![image](https://user-images.githubusercontent.com/61754910/91212024-f5a55400-e70f-11ea-8a89-bda1bb808647.png)

In VP value is at 0

![image](https://user-images.githubusercontent.com/61754910/91211937-d4dcfe80-e70f-11ea-95ab-8b1b28e35bd6.png)

Perhaps is the solution ?

**Comment by adaneslavo** [comment]
Ok, now it is good! Thanks for help. One problem out.
