### ISSUE TITLE
CTD when spreading faith with missionary

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#696]
Playing with the lattest version. It has happened twice, but the logs do not provide any explanation...

I reloaded the game, tried to spread the faith, it worked. The on the second missionary I use I get a CTD.

**Comment by LoneGazebo** [comment]
What civ? To whom? Any special mods being used?

**Comment by AnastaseAlex** [comment]
Otomans, only CBP mods +EUI installed with the CPP.exe No other mods.
I spread my religion to my own cities with missionaries. I had tithes, venreation, inspiration and founder the one that gives gold science and faith.
The log files are empty, and it is turn 140, standard speed.

While I am here: love the changes to tourism, and would really like to see the patronage tree get a boost to the tourism you get for completing city-state quests somewhere.

**Comment by LoneGazebo** [comment]
Autocracy got a policy boost for the tourism element, but I might consider a boost to patronage. Perhaps make a post on civfanatics, see if others have interest in expanding those values? Might be prudent to make policy modifiers for all of them, to be honest.

G

**Comment by LoneGazebo** [comment]
I can't reproduce this, sorry.

G

**Comment by AnastaseAlex** [comment]
It has not happened anymore in my newer games. Perhaps it was another problem and it coincided with the spreading of faith. Wil keep an eye out.
