### ISSUE TITLE
Unable to trade/give captured cities back to vassal

### ISSUE THREAD

**Issue by Lillebo** [LoneGazebo/Community-Patch-DLL#6961]
_1. Mod version (i.e Date - 4/17):_
June 19th (5.6.19)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Captured city from neighbor civ to force them to become my vassal. After their capitulation, and after the city has healed back 100% and no longer in resistance, I still cannot sell/give the vassal his city back. They refuse to accept it, and the trade value just says "Impossible".

Many others seem to have the same problem. See this thread: https://www.reddit.com/r/civvoxpopuli/comments/hg45dl/how_to_give_back_cities_to_new_vassal//how_to_give_back_cities_to_new_vassal/

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@Lillebo Use the most recent hotfixed beta version.

**Comment by Lillebo** [comment]
Ah, great! 👍 Is it the 8-23 version found [here](https://mega.nz/folder/iMNVEISb#gW3aPq-MQ-kibL0lFxrw-w/folder/nBFmXSJR)? Also, is it save game compatible?

**Comment by RecursiveVision** [comment]
@Lillebo Yes, it is the 8-23 version. No, it is not savegame compatible with 6-19 (it is savegame compatible with 8-16, though).

**Comment by Lillebo** [comment]
Playing on 8-23. This does not seem to be fixed?

![CivilizationV_DX11_8kaZQq57wj](https://user-images.githubusercontent.com/74510/92401004-21233800-f12d-11ea-9500-c1bfa3d038f1.png)

**Comment by RecursiveVision** [comment]
@Lillebo Try 9-2.

**Comment by Lillebo** [comment]
Please tell me they are save game compatible? 🙏

**Comment by RecursiveVision** [comment]
Should be.

**Comment by Lillebo** [comment]
Can confirm that this has been fixed in 9-2 - and that 9-2 is save game compatible with 8-23. Many thanks 👍
