### ISSUE TITLE
Various unit panel issues

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#6966]
_1. Mod version (i.e Date - 4/17):_
8/23

_2. Mod list (if using Vox Populi only, leave blank):_

Started with no extra mods.

Added several UI mods at various points in the game.
(ui) Trade Opportunities for VP
InfoAddict (v 22)
Promotion Flags EUI for VP (v 3)
UI - Filters in Trade Route Overview (Vox Populi) (v 2.1)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 1.2)
UI - Show XP in Military Overview (v 2.3)

"(ui) Trade Opportunities for VP" has the "AffectsSavedGames" flag set to 1.
The creator of this mod just leaves this flag on by default, as he mentions here:
https://forums.civfanatics.com/threads/list-enhancements-for-vp.638546/page-3#post-15313358
That thread is for a different mod by the same person.
The thread for the trade opportunities mod does not mention anything about this.
 I set that option to 0 and kept playing my save with the mod.

InfoAddict similarly has that flag set to 1. I've been setting it to 0 manually for years and never had issues.

_3. Error description:_ 

With or without extra mods none of my units have a "wake unit" button.
Without any extra mods, a pioneer shows to give 100 tourism.
With the extra mods, the upgrade button on a settler shows different incorrect tooltips. Hovering over it once, then moving mouse around randomly for one second, then hovering over it again shows different things.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:

4. Screenshots (optional):

![bbb](https://user-images.githubusercontent.com/4227288/91238369-dce66f80-e70a-11ea-8735-6e6db7eb7985.jpg)
![ccc](https://user-images.githubusercontent.com/4227288/91238404-f4255d00-e70a-11ea-835e-b6b7b6f567d2.jpg)
![ddd](https://user-images.githubusercontent.com/4227288/91238407-f687b700-e70a-11ea-8025-c22e6c79af7e.jpg)

**Comment by gamask** [comment]
8-23-3 fixed the settler upgrade button issue (still using the extra mods).
But he was still showing tourism when upgraded.

**Comment by ryanmusante** [comment]
Does the "AffectsSavedGames" only affect saved games or also newly created maps?

**Comment by gamask** [comment]
Not entirely sure what you're asking. Also I'm not an expert on this.
If you start a game with a mod with that flag set to 1, you can't continue that game without that mod. And if you start without that mod, you can't add it later.
If you set the flag to 0 at any point, you can add a mod you weren't using before. I haven't tried the opposite (stop using a mod you were using from the start).
This rests on the assumption that the mod doesn't actually affect saved games. Simple UI mods generally don't.
InfoAddict saves data for its graphs somewhere, and I don't know where it does that, so it could actually be a problem, but never was for me.

**Comment by LoneGazebo** [comment]
Fixed tourism. Other issues cannot be reproduced.
