### ISSUE TITLE
Zeppelin on Ice

### ISSUE THREAD

**Issue by GLop4** [LoneGazebo/Community-Patch-DLL#6967]
_1. Mod version: (8-16-2)
_2. Mod list : A lot but nothing related with Recon Units or Path
_3. Error description: On Ice, **Zeppelin** is very often **forced to make a long detour**.
_4. Steps to reproduce: IE

Screenshots:
![02](https://user-images.githubusercontent.com/8753808/91283806-5de54b80-e78b-11ea-998f-5be2870bdd6c.png)
![03](https://user-images.githubusercontent.com/8753808/91283830-663d8680-e78b-11ea-822f-ecaf7f9be83f.png)

Btw, is it intended to have Zeppelin almost blind when on sea?
![01](https://user-images.githubusercontent.com/8753808/91283982-9dac3300-e78b-11ea-9e12-0b1e1e4d73e7.png)

**Comment by ilteroi** [comment]
funny how the fog looks on your machine ... anyway zeppelin embarks in deep water, that reduces vision range.

the pathfinding problem only affects ice on deep water. fixed.
