### ISSUE TITLE
[8-16] Dummy building demanded by CS

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6968]
[Here one user mentioned](https://forums.civfanatics.com/threads/more-wonders-for-vp.653498/page-31#post-15887694) that dummy building made using standard pattern (used also in few other mods) is demanded by CSs. It has Production = -1 and [few other things set like dummy](https://github.com/adaneslavo/More-Wonders-for-VP/blob/master/2.NaturalWonders/SQL/UniqueNaturalWondersAbilities.sql), so it shouldn't be taken into account. Any ideas?

**Comment by LoneGazebo** [comment]
IsDummy must be true.

**Comment by adaneslavo** [comment]
Ok. Thanks.
Does this parameter do anything else beside that?

**Comment by LoneGazebo** [comment]
It prevents dummy buildings from doing things dummy buildings shouldn't be doing.

**Comment by adaneslavo** [comment]
Fine. Thanks.
