### ISSUE TITLE
A promise is shown as a negative modifier

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#697]
![8930_2015-10-13_00002](https://cloud.githubusercontent.com/assets/1131228/10462828/2ea63d18-71fa-11e5-8194-db17d3f7564a.png)

**Comment by LoneGazebo** [comment]
That's weird. I wonder if it's a problem with how the transparent diplomacy function works, as that value (-75) isn't being passed into the diplo score at all in the DLL.

G

**Comment by LoneGazebo** [comment]
Any confirmation on turning off transparent diplomacy with this? Unfortunately I can't edit that functionality (as it's an issue with how lua is pulled for the diplo opinion tooltip). Can confirm that it has no bearing on your relations, though.

G
