### ISSUE TITLE
Resource not spawning (PlotsToPlace)

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6970]
I used following code:
```
	INSERT INTO Building_ResourcePlotsToPlace
				(BuildingType,			ResourceType,		NumPlots) 
	VALUES		('BUILDING_WIELICZKA',	'RESOURCE_SALT',	2);
```
In my city I have possible spot checked with lua function:
```
if pSpecificPlot:CanHaveResource(eCheckedResource, false) and pSpecificPlot:GetNumResource() == 0 then
```
and this is it:
![obraz](https://user-images.githubusercontent.com/33016300/91357540-b2bbad00-e7f1-11ea-94fc-b9db348209c2.png)
but it is not spawned... why?

**Comment by adaneslavo** [comment]
In other city it was spawned for example, so it is not always bugged.

**Comment by olmer711** [comment]
Same issue here.
1 turn before complete:
![изображение](https://user-images.githubusercontent.com/69159425/95681989-9500a680-0beb-11eb-86d5-7ffb480c03de.png)
![изображение](https://user-images.githubusercontent.com/69159425/95682028-c4171800-0beb-11eb-9733-70e86913b244.png)

after complete:
![изображение](https://user-images.githubusercontent.com/69159425/95682003-b497cf00-0beb-11eb-8b2e-56e3237996de.png)
![изображение](https://user-images.githubusercontent.com/69159425/95682029-ca0cf900-0beb-11eb-9063-cd94235f32f0.png)

**Comment by adaneslavo** [comment]
This base sql function is not fixed and it still doesn't work (confirmed by few users). I can only declare it in my mod, so the problem lies in VP. Can you look at it? Why did you close it without any comment?

**Comment by RecursiveVision** [comment]
Couple issues were mistakenly closed prematurely, sorry about that.

**Comment by adaneslavo** [comment]
No problem. This one is rather hot because it breaks some stuff I've added to the mod.

**Comment by HungryForFood** [comment]
#7334
