### ISSUE TITLE
Even his horse is laughing at this deal [8/23]

### ISSUE THREAD

**Issue by Maxxim69** [LoneGazebo/Community-Patch-DLL#6971]
_1. Mod version (i.e Date - 4/17):_
8/23

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) List Enhancements for VP (v 5.2)
Quick Turns (v 10)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 
Two turns after having met me, Alexander pops up with this offer:

![2020-08-27_013542](https://user-images.githubusercontent.com/24704375/91364461-71ce9300-e807-11ea-90d1-165ab4470445.gif)

Save file attached.
[AutoSave_0205 AD-1450.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5133066/AutoSave_0205.AD-1450.zip)

**Comment by LoneGazebo** [comment]
Your on the hot fix posted last night?

**Comment by Maxxim69** [comment]
Nope, was too busy playing to visit the forum.
I know it's savegame compatible, but I think I'll start (yet) again using the same initial autosave to see whether I'll spot any differences. Third time's the charm, huh? :))

**Comment by yyEdge** [comment]
Even the latest fix (8-23?) has this problem, I've just experienced it
