### ISSUE TITLE
Worker does not know that removing a forest will lose workshop/zoo yields

### ISSUE THREAD

**Issue by DelJon** [LoneGazebo/Community-Patch-DLL#6972]
_1. Mod version (i.e Date - 4/17):_
8-23

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When removing features, Worker does not account for lost yields from Buildings that improve features. For example, when looking to cut a forest to create a farm, the worker will correctly calculate that 1 production will be lost as a result, but if there is a Workshop or a Zoo, it doesn't seem to realise that an additional 1 production and gold (workshop) or 1 culture and tourism (zoo) will be lost. Same with Marshes and Windmill. It's possible that the AI does not consider these either.

_4. Steps to reproduce (optional):_
Create a city near Forest or Marsh. Build Workshop or Windmill. Move worker to the feature tile. Examine the tooltips for removing the feature or building an impovement that removes it.

**Comment by RecursiveVision** [comment]
@LoneGazebo Does your fix consider resources? Connecting a resource (particularly strategics for a war or luxuries to get a monopoly) often outweighs any side benefits from features.
