### ISSUE TITLE
Ceremonial Burial era scaling

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6973]
Patch: 8/16/2

Tooltip says: using gp gives faith and culture per city (nothing about scaling with era)

Reality: Faith scales with era, culture does not.

**Comment by LoneGazebo** [comment]
This does not scale, you're probably getting the scaling bonus from on faith from another belief or ability.

**Comment by Mileslewis** [comment]
For me I am getting exactly twice as much faith as culture for using GPs in Medieval and then 3 times as much faith as culture in Renaissance. Don't see what else could be giving this. Perhaps it is fixed in new version though.
