### ISSUE TITLE
Goddess of the Home/ God King

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6974]
_1. Mod version 8-16-2

When you have founded a religion, if a new building is built in a city with Goddess of the Home Pantheon but not your religion you will not get the bonus food and faith instant yield.

Similarly Cities with your pantheon but not your full religion do not count for god king bonus in capital. It's possible this is intended though.

**Comment by LoneGazebo** [comment]
This is intended, as once you have founded your 'religion' is the new religion - the pantheon is obsolete.
