### ISSUE TITLE
8-23-3 Suboptimal governor tile selection

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#6976]
_1. Mod version (i.e Date - 4/17): 8-23-3

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description:_ 

City is building a settler. Choosing the improved copper tile would be a net increase in production while providing +1 gold. So it would be a better choice (no pantheon yet)

![20200827112921_1](https://user-images.githubusercontent.com/64471766/91423526-f4337300-e858-11ea-8578-42ba5af78ada.jpg)

**Comment by Stalker012345** [comment]
Here's one from me. This is the Production governor, and notice that he is not using Feitoria tiles compared to Coastal tiles. Regardless of the science, gold, and culture benefits, the Feitoria also provides more hammers. When I switch to general governor it does use them, and my production increases by 50.

![image](https://user-images.githubusercontent.com/20593976/91472455-1202d700-e85d-11ea-9720-45aec6b8367b.png)

**Comment by LoneGazebo** [comment]
what does food output look like on general v. production focus?

**Comment by Stalker012345** [comment]
It goes down a bit but its still net positive.

**Comment by LoneGazebo** [comment]
Can I get a save with that setup?

**Comment by Stalker012345** [comment]
[Governor Issues.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5143013/Governor.Issues.zip)

Yep here you go. This is later than my screenshot but shows the same behavior, go to Lisbon and switch between general and production governor. The only thing I can think of is the Prod governor is highly overvaluing the speed up of my next Great Merchant...but otherwise the general governors layout is better in pretty much every single way.

**Comment by Stalker012345** [comment]
Here is another one that I wouldn't say is a full out "issue", but I think it does highlight how the AI overvalues certain things (at least to how I value yields). Look at Wroclaw. He is working a 2F coastal over the 8p mine. If I lock the 8p mine and then refresh (aka switch the governor to something else and then back to general), it will pull a worker off the 12p 2F natural wonder to work the 2f.

If I was near starving I would understand, but it seem that the growth bonus of going from 8f to 10f is so strong that the AI is willing to give up a LOT of hammers to do it. As a player I would always work the hammers myself.

![image](https://user-images.githubusercontent.com/20593976/91602369-dafdf580-e930-11ea-956b-1bec4a434a27.png)
[Governor Issues 2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5143583/Governor.Issues.2.zip)

**Comment by ilteroi** [comment]
another one: you would expect the production governor to work the cinnamon to the north here, not the coffee to the south?

![image](https://user-images.githubusercontent.com/1358966/91631377-6b901080-e9d9-11ea-80de-72811a8c9653.png)

**Comment by LoneGazebo** [comment]
It would be stagnant if it worked the cinnamon.

**Comment by ilteroi** [comment]
nope. population is 1. not obvious from the picture, sorry. also stagnant is maybe even acceptable for production governor.

**Comment by LoneGazebo** [comment]
I'd agree, but at size 1 the governor wants to grow ASAP.

**Comment by silentreply** [comment]
Here's a very obvious one, working a 3 food tile over 3 prod tile when on prod focus.

![image](https://user-images.githubusercontent.com/59859911/91677325-5b2e8180-eb10-11ea-9ba5-d3d867a419d2.png)

**Comment by Zuizgond** [comment]
Another example with settler production.

With default governor : 8 gold, 14 production, 5 culture, 3 unhappiness
![20200901152017_1](https://user-images.githubusercontent.com/64471766/91859934-4e727080-ec6b-11ea-8df0-00b1e6a73fad.jpg)

With production governor : exactly the same as default
![20200901152025_1](https://user-images.githubusercontent.com/64471766/91861964-add18000-ec6d-11ea-8866-715b84faa2d2.jpg)

With manual tile allocation : 17 gold, 19.5 production, 7 culture, 1 unhappiness
![20200901152201_1](https://user-images.githubusercontent.com/64471766/91862056-c80b5e00-ec6d-11ea-8365-c34c1cb868b8.jpg)

So the difference between default governor and manual allocation is +9 gold, +5.5 prod, +2 culture, -2 unhappiness.

**Comment by Stalker012345** [comment]
Does the governor look at all possibilities or does it have a capped amount of time it will stay options before it picks one? (aka chess computer style).

If its the former than the example above would suggest that the AI is not just weighting yields "badly", but there is a fundamental flaw in how it looks the available terrain. If its the later...well thems the breaks for keeping the game speedy I guess.

**Comment by a3kov** [comment]
Some obvious bugs I noticed:
governor preferring 3f jungle over 3p mine with production focus
governor preferring 4f unimproved fish over 4f 1p 1f lake (purity pantheon) with production focus

**Comment by Stalker012345** [comment]
One thing is the governor does not seem to understand how settlers work, I find it never optimally places tiles when I'm building one.

**Comment by Zuizgond** [comment]
Exactly my point. It doesn't seem to understand that the city does not grow and it usually prefers a 3f tile over a 3p tile.

**Comment by RecursiveVision** [comment]
It has special logic for this case, though.

**Comment by a3kov** [comment]
![Screenshot_20200904_152129](https://user-images.githubusercontent.com/813860/92211110-832c3500-eec2-11ea-84af-db4bfe1dc3f0.png)
Governor prefers working the bison instead of the cacao tile.

**Comment by Zuizgond** [comment]
Does the logic in case of settler production thinks 1f = 1p ?

**Comment by Zuizgond** [comment]
Yes but conversion is not 1:1

And I think the conversion is decreasing the more food you have. In the screen below, Funchal has 47.3 excess food that translate into 13.75 production (conversion rate = 0.29)
![20200904182801_1](https://user-images.githubusercontent.com/64471766/92263405-e4610200-eedc-11ea-8986-cb405e119070.jpg)
![20200904182807_1](https://user-images.githubusercontent.com/64471766/92263418-e7f48900-eedc-11ea-90d4-0ddda97dc0c2.jpg)

Now in this city 22.2 excess food translate into 8.25 (conversion rate = 0.37)
![20200904182836_1](https://user-images.githubusercontent.com/64471766/92263572-21c58f80-eedd-11ea-8148-3e8825d64241.jpg)
![20200904182839_1](https://user-images.githubusercontent.com/64471766/92263648-3f92f480-eedd-11ea-8f56-085547864fa1.jpg)

**Comment by a3kov** [comment]
> @a3kov That's because food = production when making a settler.
> 
> G

By locking the cacao tile I was able to shave off 1 turn. Also my gpt was 0, and working cacao could help with that.

**Comment by a3kov** [comment]
The city just grown and the governor wants to starve it.
![Screenshot_20200912_024010](https://user-images.githubusercontent.com/813860/92961235-836b9800-f4a1-11ea-9bda-e61dadcc89be.png)

**Comment by Zuizgond** [comment]
![20200824153133_1](https://user-images.githubusercontent.com/64471766/93647393-a3064180-fa08-11ea-9a01-8485b7176a2a.jpg)
 If AI uses the same tile selection when building settlers, I understand why they have a slow start.

**Comment by asche77** [comment]
Ciy governor causing starvation is still an issue in 8 September 2020 version:

**Comment by LoneGazebo** [comment]
You're building stonehenge, it's trying to get you that wonder ASAP.

**Comment by Zuizgond** [comment]
Why choosing to work the forest instead of horses.

![20201019171936_1](https://user-images.githubusercontent.com/64471766/96471270-7031b200-122f-11eb-8358-28500a8237a6.jpg)

Does anyone know in which file is the code for tile selection?

**Comment by ilteroi** [comment]
i still can get the governor to starve a city in 10/7

need to have production focus and avoid growth active though :)

**Comment by LoneGazebo** [comment]
blegh

**Comment by ilteroi** [comment]
![image](https://user-images.githubusercontent.com/1358966/98425812-dffcc500-2096-11eb-8c08-8a092f3c43a7.png)

autoplay, AI governor
