### ISSUE TITLE
[8-23-2] Lua fix for Buildings_ClassesNeededInCity bug

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#6978]
Regarding [this closed topic](https://github.com/LoneGazebo/Community-Patch-DLL/issues/6585), I made temporary lua fix in my mod. Maybe you will try to look at current dll code to check why this table is still not working? Lua is not so efficient, so I would like to cut it as soon as possible.
```
local tValidIsHasUniqueBuildingClassReq = {} -- fix for VP bug
```

```
-- temporary FIX for unique buildingclass requirement (ALL)
function IsHasUniqueBuildingClassReq(ePlayer, eCity, eBuilding)
	if not tValidIsHasUniqueBuildingClassReq[eBuilding] then return true end
	if bReachedMaxEra then return false end

	local pPlayer = Players[ePlayer]
	
	if not pPlayer:IsAlive() then return false end
	
	local iBuildingClass1 = tValidIsHasUniqueBuildingClassReq[eBuilding].iBuildingClass1
	local iBuildingClass2 = tValidIsHasUniqueBuildingClassReq[eBuilding].iBuildingClass2
	local pCity = pPlayer:GetCityByID(eCity)
	
	for building in GameInfo.Buildings{BuildingClass=iBuildingClass1} do
		if pCity:IsHasBuilding(building.ID) then
			if iBuildingClass2 == nil then
				return true
			else
				for building in GameInfo.Buildings{BuildingClass=iBuildingClass2} do
					if pCity:IsHasBuilding(building.ID) then
						return true
					end
				end
			end
		end
	end
	
	return false
end
GameEvents.CityCanConstruct.Add(IsHasUniqueBuildingClassReq)
```

```
-- IsHasUniqueBuildingClassReq
	tValidIsHasUniqueBuildingClassReq[GameInfo.Buildings.BUILDING_MALWIYA.ID] = {
		iBuildingClass1 = "BUILDINGCLASS_STONE_WORKS"
	}
	tValidIsHasUniqueBuildingClassReq[GameInfo.Buildings.BUILDING_CHAND_BAORI.ID] = {
		iBuildingClass1 = "BUILDINGCLASS_WELL"
	}
	tValidIsHasUniqueBuildingClassReq[GameInfo.Buildings.BUILDING_MOSQUE_OF_DJENNE.ID] = {
		iBuildingClass1 = "BUILDINGCLASS_LIBRARY"
	}
	tValidIsHasUniqueBuildingClassReq[GameInfo.Buildings.BUILDING_WARTBURG.ID] = {
		iBuildingClass1 = "BUILDINGCLASS_WRITERS_GUILD"
	}
	tValidIsHasUniqueBuildingClassReq[GameInfo.Buildings.BUILDING_FORBIDDEN_PALACE.ID] = {
		iBuildingClass1 = "BUILDINGCLASS_WALLS"
	}
	tValidIsHasUniqueBuildingClassReq[GameInfo.Buildings.BUILDING_GLOBE_THEATER.ID] = {
		iBuildingClass1 = "BUILDINGCLASS_BATH",
		iBuildingClass2 = "BUILDINGCLASS_AMPHITHEATER"
	}
etc.
```

The code that should work earlier was:
```
INSERT INTO Building_ClassesNeededInCity 
	        (BuildingType,			BuildingClassType) 
VALUES		('BUILDING_MALWIYA',	'BUILDINGCLASS_STONE_WORKS');
```

**Comment by adaneslavo** [comment]
I understand it is not planned to fix the sql function, so I could go back to it and delete my lua code?

**Comment by HungryForFood** [comment]
I tested it, it works properly with the Songhai case. Malwiya Minaret will show up correctly for Songhai Tabyas when playing Songhai. I looked into the code, and it is as Gazebo states.

I'm guessing the reason it is done this way in the code is for performance reasons. To check for all buildings in a class would require looping through all buildings in a city, as opposed to checking if the particular civ has a UB, which is just a single request.

It is fine for 99% of cases, only mods like 4UC which replace Japan's non-UB buildings via Lua would be affected.

**Comment by adaneslavo** [comment]
Strange, because when I tested Tabya, it was not triggering the wonder properly... I wonder why? Which version of MWfVP did you use?

**Comment by HungryForFood** [comment]
Not sure which version I'm on, maybe at most 2 versions outdated.

Either way it shouldn't affect how the table behaves.

I think you can go back to using the database table. As far as I'm aware, none of the wonders which use building requirements in your Lua have mods which replace them via Lua.

**Comment by adaneslavo** [comment]
I just rechecked the old code. It's ok for Stone Works, but Tabya doesn't trigger the wonder. The problem is not only for MWfVP, but also for some VP buildings, unless no building is requiring unique one in base game.

**Comment by HungryForFood** [comment]
There is an exception in the code for Rome, so really only mod civs with Lua that replaces buildings.

**Comment by pineappledan** [comment]
The Polish have a unique Armory that has all the bonuses of a castle, so they have a unique armory, and then they are disabled from building castles. In other words, the have 2 BuildingClassOverrides: 'BUILDING_POLAND_BARBICAN' and null.

When a barbican is built in a city, a dummy building is added to the city as well that does nothing, but has BUILDINGCLASS_CASTLE, so if you have any bonuses to castles from policies/wonders/etc, you don't miss out (but they are invisible).

Israel does the same thing, where it has a unique Grand Temple, and then has normal temples disabled, but it doesn't have a temple dummy

**Comment by HungryForFood** [comment]
This is the code that checks for prerequisite buildings in the DLL.
```
	// Does this city have prereq buildings?
	for(iI = 0; iI < iNumBuildingClassInfos; iI++)
	{
		CvBuildingClassInfo* pkBuildingClassInfo = GC.getBuildingClassInfo((BuildingClassTypes)iI);
		if(!pkBuildingClassInfo)
		{
			continue;
		}

		if(pkBuildingInfo->IsBuildingClassNeededInCity(iI))
		{
			ePrereqBuilding = ((BuildingTypes)(thisCivInfo.getCivilizationBuildings(iI)));

#if defined(MOD_BALANCE_CORE)
			//Exception for new Rome UA, because civ type doesn't help you here.
			if(GET_PLAYER(getOwner()).GetPlayerTraits()->IsKeepConqueredBuildings())
			{
				if(0 == m_pCityBuildings->GetNumBuildingClass((BuildingClassTypes)iI))
				{
					return false;
				}
			}
			else
#endif

			if(ePrereqBuilding != NO_BUILDING)
			{
				if(0 == m_pCityBuildings->GetNumBuilding(ePrereqBuilding) /* && (bContinue || (getFirstBuildingOrder(ePrereqBuilding) == -1))*/)
				{
					return false;
				}
			}
		}
	}
```

Seems that because the Armory's replacement for Poland is null, anything that requires Armories just never checks for them for Poland, due to the `if(ePrereqBuilding != NO_BUILDING)` check. I checked in-game, and this is correct, Poland can build Military Academies without Armory.

Putting a dummy as the unique building would show up in the UI though, and also wouldn't work for Japan's case.

So options are: 
- Check for every building in class for every case, not just for Rome.
- New database table so that mod civs can define additional buildings as valid for the class.

I think I'll go with option 2, seems like it would use less CPU processing at a small cost of memory.

**Comment by adaneslavo** [comment]
So, if I understood correctly, old code would stay and the only thing that should be changed in any modmod, would be MUCfVP adding new stuff in new table for Japan and Poland.

This way I could use standard sql table requirements in my mod and get rid of that lua once and for all, right?

**Comment by HungryForFood** [comment]
Yea, database tables will be enough.

Also, a change. I'll make it into a CustomModOption, BUILDINGS_PREREQ_CHECK_ALL_IN_CLASS. Set Value = 1 to make the game do a more thorough check.

**Comment by pineappledan** [comment]
> Putting a dummy as the unique building would show up in the UI though, and also wouldn't work for Japan's case.

except you can silence that by setting the ShowInPedia column in Buildings to 0, so I think, at least for Poland, I can rig this to work without a change in existing code. That doesn't fix anything for Japan though

**Comment by adaneslavo** [comment]
Does the latest 1-9 patch contin fix for this problem?

**Comment by RecursiveVision** [comment]
Yes

**Comment by adaneslavo** [comment]
Awesome!
