### ISSUE TITLE
Crash on exit with the newest fixed LUAJIT.

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#698]
I didn't experience them much prior this version.

**Comment by ilteroi** [comment]
well, that's disappointing. personally i haven't seen a single crash with the new version, don't know what's going on here.

**Comment by Vyyt02** [comment]
Crosspost from CivFanatics:

Everything seemed to be workign fine for a couple fo hours - I exited to main menu a couple of times and reloaded without any problems.

I needed to reload again a while ago, so I exited to main menu without problem, but after I selected the save to load, I got a CTD. I restarted the game, loaded the same save, without prob.

There are 2 runtime errors at the very bottom of the lua.log. Sorry, GitHub says I do not have permission to upload the log even if I change the extension to txt - you can find my lua.log at CivFanatics:

http://forums.civfanatics.com/showthread.php?t=554175

**Comment by Vyyt02** [comment]
Hmm, now it became consistent. Happens every time I quit to main menu and click a save a want to load (or a 1-2 secs right after the click)

**Comment by Vyyt02** [comment]
JFYI, switched to the very original dll by Firaxis and I am getting no crashes when I try to reload the game.
