### ISSUE TITLE
City RCS with ranged ship garrison still wrong

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#6980]
_1. Mod version (i.e Date - 4/17):_
8-23-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
City RCS is still wrong when the garrison is a ranged ship. Newly found capital should have 8 RCS regardless of garrison.
![image](https://user-images.githubusercontent.com/14953746/91465958-0e08a080-e8c1-11ea-808e-90307066312f.png)

_4. Steps to reproduce (optional):_
Start new game, open IGE and place a lategame ranged ship to see the effect.

**Comment by LoneGazebo** [comment]
Why 8?

**Comment by azum4roll** [comment]
5 base plus 3 from the palace? Garrisons shouldn't contribute to RCS.
