### ISSUE TITLE
8/23 - 3 - Missile Cruiser stacking protection from pathfinder failed

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6981]
_1. Mod version (i.e Date - 4/17):_
8/23 - 3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Pathfinding allowed this moving Missile Cruiser to go right on top of an allied fleet. No the stacking limits are forcing me to destroy it.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/91473208-2b585300-e85e-11ea-9e88-795f81bea89a.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
gimme dat save yo

**Comment by Stalker012345** [comment]
Sorry I don't have it for that one :(

**Comment by LoneGazebo** [comment]
@ilteroi I assume this is my fault.

**Comment by ilteroi** [comment]
probably not in fact ... was the spanish armada hidden in fog before you moved?

because we don't check stacking for fog plots so we don't leak information.

but when executing the moves, the unit should stop once it becomes clear the path is impossible. apparently those checks failed though.
