### ISSUE TITLE
Venice founding puppet cities

### ISSUE THREAD

**Issue by uileschuil** [LoneGazebo/Community-Patch-DLL#6982]
_1. Mod version (i.e Date - 4/17):_
6-19-2

_2. Mod list (if using Vox Populi only, leave blank):_
None

_3. Error description:_ 
Seems that Venice is founding puppet cities. 

_4. Steps to reproduce (optional):_
![Civ5 screenshot](https://user-images.githubusercontent.com/70340066/91477136-3df27c80-e89e-11ea-836a-6e472182bf3d.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Intended
