### ISSUE TITLE
Bad Math for Strategic Resources

### ISSUE THREAD

**Issue by RhysDeAnno** [LoneGazebo/Community-Patch-DLL#6983]
_1. Mod version (i.e Date - 4/17):_
8-23-3

_2. Mod list (if using Vox Populi only, leave blank):_
No other mods

_3. Error description:_ 
The evaluation of strategic resources seems broken. Despite exporting 4 horses to China it only sees that as exporting 2. The problem seemed to originate when earlier deals ended and never resolved. Also, despite having 2 paper sources it thinks I have 3 total paper (and when I had completed Roman Forum and Scrivener still under construction and no embassy I had 2). I've attached a couple past saves with similar weird behavior as well.

_4. Steps to reproduce (optional):_
Load saves, should still be weird.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5138191/Logs.zip)

[single.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5138211/single.zip)

<img width="244" alt="Resource Oddity" src="https://user-images.githubusercontent.com/47321731/91482813-a9275900-e874-11ea-8d5b-57637b6b9536.png">

**Comment by RecursiveVision** [comment]
I HEAR MATH THAT BAD

**Comment by LoneGazebo** [comment]
Did you run the whole game on the same hotfix? I think I resolved a potential for missing resources after deals in an earlier hotfix.

**Comment by RhysDeAnno** [comment]
I started this game with the new hotfix. I think the problem with the horses started after 2 deals for 2 horses each resolved on the same turn, I renewed neither, and I went from 0 available horses to 6.

**Comment by LoneGazebo** [comment]
Ideally if you could share that save (prior to the deals resolving) that would help.

**Comment by RhysDeAnno** [comment]
Unfortunately the best I can do now is this save from turn 60, it's 26 turns before the deals resolve.

[Gandhi_0060 BC-1600.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5138724/Gandhi_0060.BC-1600.zip)

**Comment by LoneGazebo** [comment]
Thanks, that may help!

**Comment by LoneGazebo** [comment]
![image](https://user-images.githubusercontent.com/7849458/91612857-e9a1d800-e943-11ea-8fb6-ad3d44138f1d.png)

**Comment by LoneGazebo** [comment]
Fixed. When prepping a deal for a human, I forgot to have the game skip over already cancelled deals if the human refused the prepared offer. All good now.
