### ISSUE TITLE
Inconsistent lake tile yields with goddess of purity

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#6984]
_1. Mod version (i.e Date - 4/17):_

8-16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

See screenshot.
It did not correct itself later.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:

![asd](https://user-images.githubusercontent.com/4227288/91502328-c91b4480-e895-11ea-8efd-673ca3ac68e8.jpg)

**Comment by bsesar** [comment]
@gamask Do the yields shown on the map change if you work the other lake? Due to the proximity of the lake closest to your city, I assume the city is working that tile. Maybe the Goddess of purity is giving extra yields only on worked tiles, even though that is not noted in the pantheon description.

In short, the behavior may be as intended, but the description of the pantheon may need to be improved to specify extra yields only on worked tiles.

**Comment by Mileslewis** [comment]
Also sometimes the map will show unchanged yields but when you actually work the tile you will get the correct yields.

**Comment by gamask** [comment]
This is clearly not my city so I can't control what it works.
I don't think there are any bonuses that show up only if you work the tile, so this is clearly not intended.

**Comment by LoneGazebo** [comment]
If it is not your city the tile yields will only update when you 'view' the tiles with a unit.

**Comment by gamask** [comment]
But that's still not consistent with other things that boost tile yields.
I frequently use yields to determine if an AI civ has some tech.
For example if they have economics for +2 food on towns I can see that even through the fog.

**Comment by bsesar** [comment]
@LoneGazebo Why even allow players to see yields of other players? The only usage I see would be to gain information about the opponents tech (as @gamask noted) and perhaps buildings they have in their city (if the observed yields also include bonuses from buildings). If that's the intended usage then fine, but to me it sounds like a cheat :-)

Instead, would it make sense to show yields as they would be if *you* controlled the territory? Such logic may be even easier to put in code.

**Comment by LoneGazebo** [comment]
Definitely not easier to code- far more expensive.
