### ISSUE TITLE
Archaeologists not digging through features

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#6987]
Mod version: 8-16-2

My archaeologists were refusing to do digs where there was forest/jungle underneath. The icon was there but just wouldn't do anything when clicked. Once I removed the forest/jungle they would dig.

**Comment by LoneGazebo** [comment]
It technically works, but there's no 'chop' animation so the game doesn't start the animation until you click end turn. I've
