### ISSUE TITLE
Sometimes AI values strategics non-linearly when buying

### ISSUE THREAD

**Issue by a3kov** [LoneGazebo/Community-Patch-DLL#6988]
_1. Mod version (i.e Date - 4/17):_
8-23-3

_2. Mod list (if using Vox Populi only, leave blank):_
Promotion icons for VP
Reseed

_3. Error description:_ 
I noticed sometimes AI values strategics non-linearly, depending on number of resources he is buying. For example:
For 1 horse Japan is offering 400
For 6 - 3120
For 7 - 4270
For 8 - 7040 !!!

_4. Steps to reproduce (optional):_
Wait for Japan to contact you, then remove his deal from the screen and try to offer him different number of horses

[Pacal_JapanHorses.Civ5Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5139955/Pacal_JapanHorses.Civ5Save.zip)

**Comment by Stalker012345** [comment]
I am noticing this as well. It does seem that the more strategics you add to the deal, the more the AI values each strategic.

If anything you would expect it to be the opposite, its harder to put more strategics to work, so you would always expect a bulk discount in that case.
