### ISSUE TITLE
8/23 - 3 - Danish Fusiliers have higher base CS than normal

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#6989]
_1. Mod version (i.e Date - 4/17):_
8/23 - 3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
As far as I know, there is nothing in the Danish kit that should allow their Fusiliers to have a straight up higher base CS than normal.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/91604761-dd624e80-e934-11ea-8883-4e010f884346.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
Pillaged tile

**Comment by Stalker012345** [comment]
Just to be clear, it is intended that the Viking Pillage Tile bonus actually boosts the base unit CS instead of adding a multiplier. This means this is the greatest multiplier in the game, because it boosts every other multiplier along with it.

**Comment by LoneGazebo** [comment]
Yes it is intended
