### ISSUE TITLE
On Piety

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#699]
I've given your offer some thought, and tbh, I don't think I need anything AI-wise for Piety, or at least I think it would be too complicated. This is what I'd like ideally for the AI's decision to adopt/change a State Religion:
* they have researched tech X (Priesthood in my mod, but I'd use a tech tag to mark it, as I remove Priesthood in CBP)
* the religion is the majority in their empire and they have met the founder
* they have not founded their own religion
* they have not changed their State Religion within the past X turns (this last part is something I can't really simulate in Lua). 
* If all these are true, the chance to adopt would be based on the leader's religious intolerance flavour (a custom one that I've made: 'FLAVOR_JFD_RELIGIOUS_INTOLERANCE'), and increased by if they desire friendly relations with the founder of that religion (again, something I can't simulate in Lua).

However, most of this can be simulated in Lua, and probably works good enough (only missing the once in every X turns and favouring friendly relations). But what would be useful is a **player:GetMajorityReligion()** function to return the religion which has the most cities to its name in the given player's empire. This would at least streamline the above assessment in Lua, so that it wouldn't need to loop every city and calculate from that.

I'd also like to ask - not having done so before because I assume it's a bit too much, so feel free to reject it - if some of the Piety related functions could be pushed into the DLL. At the moment, I rely upon Pazyryk's TableSaverLoaded in order to cache the player's state religion ID and their piety value, but I feel as though pushing it into the DLL would be much more stable. Basically, I'd be looking for some if not all of the following functions, grouped by what I feel is least of an ask to most:

* **player:SetStateReligion(religionID)**
* **player:GetStateReligion()**
* **player:GetNumCitiesWithStateReligion(religionID)** - would return the number of cities where the state religion is the majority

I would need a **GameEvents.StateReligionChanged(playerID, religionID)** and a **GameEvents.StateReligionAdopted(playerID)** in order to catch these in Lua, however, so that I could still pass all the notifications and sound effects. The difference between the two would be that StateReligionAdopted only fires if the AI has never had a State Religion before (i.e. GetStateReligion() is at -1).

There are actually a few methods in the DLL/CvGameCoreDLL/CvPlayer.h already that relate to StateReligion ("GetNumCitiesWithStateReligion", "SetHasAdoptedStateReligion", "IsHasAdoptedStateReligion"), which I presume to be dormant from CivIV, but perhaps could be hijacked for my needs above.

* **player:SetPiety(value)**
* **player:ChangePiety(value)**
* **player:GetPiety()**
I would need a **GameEvents.PietyChanged(playerID, value)** in order to catch when a piety level changes (which sends a notification, amongst other things).

* **player:GetPietyRate(value)**
----To make this work, I'd need something like **GameEvents.GetPietyRate(playerID)** or something, so that I can tell the DLL what the actual piety rate is, which is why it's last on this list.
----And with this, perhaps it could fire each turn from within the DLL to ChangePiety() based on the GetPietyRate() value, if GetStateReligion() > -1, so that I didn't have to handle it in Lua.

But like I said, I don't wish to ask for more than you'd like to work on (especially when I can be little help coding-wise), and you've already done so much to help this mod, so I have absolutely no expectations and am already awed by your generosity. In addition, I would certainly wait as long as needed for (if) anything you decided to do.

Incidentally, does the AI already take into consideration policies, buildings, etc. which have a negative value? Or, at least, would it take into account if something had a negative flavour? This could be useful in helping the AI understand my Sovereignty reform system (the bulk of which consist of 'dummy policies' that have a positive effect in one area in exchange for a negative in another).

**Comment by LoneGazebo** [comment]
These changes are less intense than you might imagine. I can add lua hooks for the existing player functions (like religious majority) fairly easily. I can also add a boolean lua call for the friendly relations, if that'd help. The 'per x turns' could be addressed with a memory element that lets you set the last turn it was changed, and compare that to the current game turn. 

The ones with memory bits aren't bad, as they don't hook into any existing functions. They'd just be independent elements that you can change.

Might be easiest to handle the piety rate as a yield - how is it currently calculated/implemented? I could add a new yield (YIELD_PIETY) if that'd help.

**Comment by JFDaly** [comment]
The DLL is black magic to me, so I'm probably overthinking the work involved.

A check for friendly relations would be excellent, thank you. And the 'per x turns' arrangement could work, although come to think of it I could handle that in TableSaverLoader if need be.

I do have a yield ('YIELD_JFD_PIETY'), though it's mostly unused (so changing it to just YIELD_PIETY can work if its to be more formally implemented). 

Piety is calculated per turn. Basically, I assess a range of variables which make up the piety yield rate (for instance, each city not following your State Religion costs 1 Piety Per Turn), which I then hook into a custom JFD_ChangePiety() function, which changes the cached piety value for the player. Piety isn't generated passively (except in one instance), but it is lost passively in most cases. So unfortunately it wouldn't be as simple as hooking up the yield itself and having things generate it as if it were Faith or any other yield.

**Comment by LoneGazebo** [comment]
Yeah, I don't think the YIELD_PIETY would be a good fit, as it seems circumstantially used as a yield. The other things, though, aren't too bad. In fact, I've already added them :)

Here's the functions,  I think you can figure out how they work:

Player:GetMajorCivOpinion(ePlayer);

returns an enum for opinion. Here's the list of enums (in order)

MajorCivOpinionTypes
NO_MAJOR_CIV_OPINION_TYPE);
MAJOR_CIV_OPINION_UNFORGIVABLE);
MAJOR_CIV_OPINION_ENEMY);
MAJOR_CIV_OPINION_COMPETITOR);
MAJOR_CIV_OPINION_NEUTRAL);
MAJOR_CIV_OPINION_FAVORABLE);
MAJOR_CIV_OPINION_FRIEND);
MAJOR_CIV_OPINION_ALLY);

So you could have it pass with a value of 5 or better.

Player:GetMajorityReligion();
   returns a ReligionTypes value

Player:GetStateReligion();
   returns a ReligionTypes value

int Player:GetNumCitiesWithStateReligion(eReligion)
   With this one, you can either enter eReligion, or you can use NO_RELIGION to return the GetStateReligion() value above, or you can ask for a specific religion using a ReligionType value.

Player:SetStateReligion(eReligion)
int Player:GetPiety()
Player:SetPiety(iValue)
Player:ChangePiety(iValue)
int Player:GetPietyRate()
Player:SetPietyRate(int)
Player:ChangePietyRate(int)
int Player:GetTurnsSinceConversion()
   gets turns since last conversion (set in function below) - subtract from gameturn to get a proper value.  
Player;SetTurnsSinceConversion(iValue)

The Game event for Piety Changing is:



There's a value in the CustomModOptions.xml file you'll need to flip to 1 to enable the 'dopiety' function in the DLL:

BALANCE_CORE_JFD

I'm uploading the Community Patch shortly. Test everything and let me know how it works.

**Comment by LoneGazebo** [comment]
and here's the link

https://mega.nz/#F!jVNzQSBT!AfGZtgAez86yDuuhWO0NjA

**Comment by JFDaly** [comment]
Wow, this is amazing. I'll test these out shortly and report back. Thank you so much! Did you also add a Game Event to detect when a State Religion is adopted/changed? I'll need this to notify the player when a State Religion is adopted by another player.

**Comment by LoneGazebo** [comment]
I didn't add the state religion one, but I will. Missed that request. 

Link works for me. Refresh page?

**Comment by JFDaly** [comment]
Awesome, thanks much :)

Yup, refreshing page did the trick.

**Comment by JFDaly** [comment]
Ok, everything works perfectly, including the PietyChange game event and the Get/SetTurnsSinceConversion function. So could I ask for just a few more functions, which would just make some regular checks a bit more direct:
* **Player:HasStateReligion()** -- this wouldn't care for the specific religion, and would just return true or false, depending on whether the player has any State Religion at all.
* **Player:HasSecularized()** -- this would just be a true/false flag.
* **Player:SetHasSecularized(boolean)** -- and this would call the value from the above.
* **Player:IsPagan()** -- this would be a (Player:HasCreatedPantheon() and (not Player:HasStateReligion()) and (not Player:hasSecularized())) check (don't know how it's written in C++, but that's the logic in Lua. It basically checks that the player has created a pantheon, but that the player doesn't have a State Religion and that the player hasn't also secularized).

These plus the afore-discussed GameEvent.PlayerAdoptsStateReligion and GameEvents.PlayerChangesStateReligion would tie up everything nicely, and would cover all the major functions I use in Piety.

**Comment by LoneGazebo** [comment]
I assume the oldReligionID in playersecularizes function is the state religion ID, yes?

**Comment by LoneGazebo** [comment]
Done, though I can change the element above if need be.

New functions:

**bool Player:HasStateReligion()
bool Player:HasSecularized()
Player:SetHasSecularized(bool bValue)
bool Player:IsPagan()**

**	*8
**	
				**
**	**
			   **

**Comment by LoneGazebo** [comment]
And here's the link: https://mega.nz/#!zIsg1JRY!-BvOQqWDacFDcw6IFy333vfh4vXKAIMmz6KtlKjVz5A

**Comment by JFDaly** [comment]
Yup, oldReligionID was the state religion before secularization. Thanks again. I'll report back on whether the new functions work later.

**Comment by JFDaly** [comment]
Confirming that everything works perfectly :)

**Comment by LoneGazebo** [comment]
Awesome!

**Comment by JFDaly** [comment]
I notice that many of the Belief_X tables don't support every yield. Would it therefore be safe to assume that it would be too much work/not possible to indeed add a Piety yield and to hook it up to these? If so, I can certainly achieve what I intend with Lua, but I thought I'd ask anyway.

**Comment by LoneGazebo** [comment]
Any particular table?

**Comment by JFDaly** [comment]
Ah, perhaps a few. But if it needs to be handled specifically, then don't worry about it, as that means there's room for change on my part in the future.

**Comment by JFDaly** [comment]
Encountered a bit of an oversight on my part. In Piety, there is a max threshold of piety that you can accumulate. You can also not go below 0. I hadn't thought about this until now. I thought I could remedy this by catching it at the PietyChanged game event, but of course this fires just before the piety is actually changed (which is immensely helpful otherwise). So could I please get a Player:Set/GetMaxPiety() and a Player:Set/GetMinPiety(). Sorry for overlooking it earlier.

**Comment by LoneGazebo** [comment]
I'll just create two defines, a max and a min, that the DLL will push against if it tries to make the value above/below them. You can then set the define however you want.

**Comment by JFDaly** [comment]
Do you mean a database define? Because the max piety varies according to game speed, so that probably wouldn't be enough. You could add a Max/MinPiety to the GameSpeeds table though.

**Comment by LoneGazebo** [comment]
Does it vary specific to gamespeed? Because, if so, I can just % +/- it based on a gamespeed value (such as training speed).

G

**Comment by LoneGazebo** [comment]
I added the gamespeed columns: **PietyMin** and **PietyMax**

**Comment by JFDaly** [comment]
The max piety is specific to the game speed (min piety is always 0, but just in case I change it. Max piety is 100/200/300/400 on Quick/Standard/Epic/Marathon).

Thanks. That'll work perfectly.

**Comment by LoneGazebo** [comment]
New version inbound with this change, and the CTD mapload fix. We'll see if that addresses all the bugs (for now) :8ball: 

G

**Comment by LoneGazebo** [comment]
And here's the link: https://mega.nz/#!rN00RDTJ!7GbqpXmsSFzsgOkNW2cusmih0Iv-iTlP5nvZCPgtZic

**Comment by JFDaly** [comment]
Ran just this version of the CP; still crashes on trying to load. I ran a quick 100 turn game and then made a manual save to be certain. Here's the [mini dump](https://www.dropbox.com/s/007rcyut1f7hvqw/CvMiniDump.dmp?dl=0) and the [save file](https://www.dropbox.com/s/l5set79do7b91tm/Oda%20Nobunaga_0100%20BC-0375.Civ5Save?dl=0). Fully exited out of the game before loading, too, and deleted the cache before this test. I also tried a 1 turn save, and the same issue [mini dump](https://www.dropbox.com/s/z1l4mq4uqecs2hm/CvMiniDump1.dmp?dl=0) [save] (https://www.dropbox.com/s/yyomejrjyyrpkz7/Alexander_0000%20BC-4000.Civ5Save?dl=0).

On a more positive note, PietyMin/Max work perfectly :)

**Comment by LoneGazebo** [comment]
Did you try to load an old save? That'll break it. I loaded and saved and loaded a few times and it worked for me...

Send me your ExCE again just to be sure.

**Comment by JFDaly** [comment]
It was a completely new save, from just now. It wasn't using ExCE (just the CP), but [here's] (https://www.dropbox.com/s/u6rvvqejx38bxmb/JFD%27s%20Exploration%20Continued%20Expanded%20%28v%208%29.rar?dl=0) the mod anyway. I'll try verifying the game's files.

**Comment by LoneGazebo** [comment]
Huh. I'll keep tinkering.

**Comment by JFDaly** [comment]
Since the very latest version (23rd), loading save games appears to be fine.

There is one thing I forgot about for Piety, if you'd be able to oblige. A Game.GetFoundYear(religionID) and (if there's no way to register this already) a Game.SetFoundYear(religionID). This is a fairly minor thing, so it can wait until you get the chance.

I'll have a few requests in the near future for Sovereignty along the same lines as Piety, if that's ok with you. I'll have to think about how you might be able to help with the Reforms system a bit more - as it's something I'm not sure how to get the AI to make use of (if it would even be possible).

**Comment by LoneGazebo** [comment]
Sure, always happy to help. I'll add those functions (pretty simple).

G

**Comment by LoneGazebo** [comment]
All added. The founding year of a religion is set automatically when it is created, but the value was not accessible via lua. I've added the functions, though you should only need the 'set' function if you wish to force-change the founding value.

**Comment by JFDaly** [comment]
Excellent, thank you. I had a suspicion that the found year was already recorded in the DLL.
