### ISSUE TITLE
Settler not moving for a long time early game

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#6991]
_1. Mod version (i.e Date - 4/17):_
8-23-3

_2. Mod list (if using Vox Populi only, leave blank):_
No change related to settlers

_3. Error description:_ 
England built her first settler, but didn't move it for 10+ turns because of "no escort". There was an archer garrisoned in city, a warrior off fighting a barb camp, and a scout and pathfinder exploring elsewhere, and there was no intent to bring back any of those. Meanwhile, nearly everyone else has 2-3 cities.
![image](https://user-images.githubusercontent.com/14953746/91633257-62269880-ea19-11ea-97e8-3539d26945d8.png)
[OperationalAILog_England.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/5144987/OperationalAILog_England.txt)

Zulus in the same game had a settler from Pyramids that stayed for 10+ turns as well, though there WAS an escort.
![image](https://user-images.githubusercontent.com/14953746/91633309-c6e1f300-ea19-11ea-863f-8265462925aa.png)
[OperationalAILog_The_Zulus.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/5144988/OperationalAILog_The_Zulus.txt)

_4. Steps to reproduce (optional):_
Load the below autoplay save.
[AutoSave_0040 BC-2400.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5144990/AutoSave_0040.BC-2400.zip)

**Comment by azum4roll** [comment]
https://mega.nz/folder/bK4F0SBS#4gnB_isvbPaqC5X1_tQLzA Modpack here

**Comment by silentreply** [comment]
On a similar note, I observed below where the AI wants to settle on a barb camp but simply didn't have the strength to clear the camp. It has been sitting here for 10 turns when it could have just moved a few turns north and settled a still decent location.

Most of the time I feel like the AI usually recognizes this and cuts their losses and moves to a different location. But in this case it really seems stuck on this location. 
![image](https://user-images.githubusercontent.com/59859911/91638402-6b920f80-e9dd-11ea-947a-2d40a65b9638.png)

**Comment by RecursiveVision** [comment]
Merge error, fixed.
