### ISSUE TITLE
Liberating a dead civ doesn't make them your vassal

### ISSUE THREAD

**Issue by a3kov** [LoneGazebo/Community-Patch-DLL#6992]
_1. Mod version (i.e Date - 4/17):_
8-23-3

_2. Mod list (if using Vox Populi only, leave blank):_
Promotion icons for VP
Reseed

_3. Error description:_ 
Liberating a dead civ was supposed to vassalize them peacefully, however it doesn't happen.

_4. Steps to reproduce (optional):_
Liberate Delhi to reproduce

[Pacal_IndiaLiberatio.Civ5Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5145141/Pacal_IndiaLiberatio.Civ5Save.zip)

**Comment by Lillebo** [comment]
Does 9-2 include this fix? 🙏

**Comment by RecursiveVision** [comment]
Yes

**Comment by Lillebo** [comment]
Sorry to say, 9-2 does ***not*** appear to include this fix 😕

Perhaps 9-8 does? And is 9-8 save game compatible with 9-2? 🙏

**Comment by Lillebo** [comment]
Looks like this problem still exist in 9-8 as well. But 9-2 and 9-8 does seem to be save game compatible at least...

**Comment by Lillebo** [comment]
Here's hoping the next release/beta will include this fix 😬🙏

**Comment by RecursiveVision** [comment]
I found the problem, working on a fix.

**Comment by RecursiveVision** [comment]
Fixed!
