### ISSUE TITLE
Bring back postturn autosaves

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#6994]
_1. Mod version (i.e Date - 4/17):_

8-23-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Currently postturn autosaves happen in CvPlayer.cpp:34062, but only in debug builds.
I didn't investigate the entire history of changes; looks like things were moved around a lot.
But originally (and in the base game) this feature was toggleable simply via the config file, and didn't require a debug build.
Is there a reason that was changed?
I personally find it very useful for a multitude of reasons.

**Comment by gamask** [comment]
I compiled my own dll in debug mode, and loaded a save produced by the code mentioned above.
It loads fine but a second or so after loading the turn ends on its own.

So I commented that code out.
In fc05ce6e431a9767019c7cfcc4ca4fa800c83385 some code was removed from doControl function.
I've included some extra code below for context. There's a comment above the lines that I added back.

```c++
	case CONTROL_ENDTURN_ALT:
		if(GC.GetEngineUserInterface()->canEndTurn() && gDLL->allAICivsProcessedThisTurn() && allUnitAIProcessed())
		{
			CvPlayerAI& kActivePlayer = GET_PLAYER(getActivePlayer());

			// code below was removed from here in fc05ce6e431a9767019c7cfcc4ca4fa800c83385
			if (!isNetworkMultiPlayer() && kActivePlayer.isHuman() && GC.GetPostTurnAutosaves()) {
				gDLL->AutoSave(false, true);
			}

#if defined(MOD_EVENTS_RED_TURN)
			if (MOD_EVENTS_RED_TURN)
			// RED <<<<<
			{
				ICvEngineScriptSystem1* pkScriptSystem = gDLL->GetScriptSystem();
				if(pkScriptSystem)
				{	
					CvLuaArgsHandle args;

					args->Push(getActivePlayer());

					bool bResult;
					LuaSupport::CallHook(pkScriptSystem, "TurnComplete", args.get(), bResult);
				}
			}
			// RED >>>>>
#endif
```

Now I have functioning post-turn autosaves. There were more changes in that commit that I left alone.
I'm not familiar enough with the codebase to say that what I did is sufficient and won't break something, like multiplayer games or AI autoplay games. For my purposes it seems to be functional.

There were a ton of other changes related to autosaves both before and after that commit.
I don't care to figure out the intent behind all of them. This is where informative commit messages would be useful.
I'm just leaving this here because it could be useful to you in case you decide to bring this feature back properly.

My understanding is that it was repurposed to facilitate AI testing?
If so, that's not cool at all.

**Comment by RecursiveVision** [comment]
@ilteroi maybe you wanna look at this?

**Comment by ilteroi** [comment]
we're not good with atomic commits or useful commit messages, i'll grant you that ... and in fact i would prefer post-turn saves only and always. but there was some pushback. don't remember why.
