### ISSUE TITLE
AI City Connections and Isolation Unhappiness issues

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#6996]
_1. Mod version (i.e Date - 4/17):_
8-23-3

_2. Mod list (if using Vox Populi only, leave blank):_
Nothing that affects roads or worker logic, I'm sure

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/14953746/91660233-b60fab00-eb07-11ea-9227-877424075598.png)
There seems to be a problem with both isolation unhappiness and the AI's willingness to build roads. In the screenshot, Goshute, Pohokwi and Te-Moak is not connected but isn't hit by isolation, while Agaidika and Byblos have isolation unhappiness.

They're currently sending a worker to build roads to the capital, but shouldn't that be the highest priority instead of connecting other cities with each other? They're currently VERY unhappy. I won't be surprised if one of their cities break free in a few turns.

_4. Steps to reproduce (optional):_
Dunno, it randomly happens.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
https://forums.civfanatics.com/threads/new-beta-version-august-16th-8-16.661882/page-18#post-15887099 Someone mentioned it here too.

**Comment by ilteroi** [comment]
trade routes prevent isolation. but road building is not prioritized by unhappiness i think.

**Comment by LoneGazebo** [comment]
>but road building is not prioritized by unhappiness

There is some bonus priority for unhappiness, but it does not outweigh resource connections.

**Comment by azum4roll** [comment]
> 
> 
> > but road building is not prioritized by unhappiness
> 
> There is some bonus priority for unhappiness, but it does not outweigh resource connections.

Even when happiness is below 30%, like it is here?

**Comment by LoneGazebo** [comment]
even yes
