### ISSUE TITLE
Cannot have Gold Per Turn and Gold in same trade

### ISSUE THREAD

**Issue by GLop4** [LoneGazebo/Community-Patch-DLL#6997]
1. Mod version:_(8-23-3)
2. Mod list: A lot but nothing linked with Trade or Diplo
3. Error description: I'm not offering Gold or other to Nebu. but He's consedering I'm offering Gold per turn!
4. Steps to reproduce (optional):_
---------------------------
Supporting information:
4. Screenshots (optional):
![Civ5Screen0091](https://user-images.githubusercontent.com/8753808/91660993-8f3a8000-ead9-11ea-89e9-313f82073edb.png)

**Comment by psparky** [comment]
Whilst not allowing gold and GPT on opposite sides of a trade deal is intended, I think the problem being reported here is that the tooltip is inappropriate in this situation, where gold has not been added to the other side.

In the specific case here, the message should be something like "No Gold Per Turn available to trade".

Also, the message is slightly confusing when seen for the first time as it suggests that Gold and GPT also can't be on the same side a deal. Perhaps "Cannot trade Gold for Gold Per Turn" would be clearer.
