### ISSUE TITLE
Puppets produce Urbanization

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#6999]
Puppets cannot produce GPP but still produce Urbanization, and the player can't control this unhappiness at all.

I suggest one of the following changes:
- Puppets are unable to work GP slots
- Puppets do not produce Urbanization

I'd prefer the second, considering the yields from GP slots are still reduced by 80% anyway...

**Comment by LoneGazebo** [comment]
I disagree!

**Comment by Mileslewis** [comment]
This felt like an issue to me also as you can't do anything about it.

Seems like the Puppeted city citizen selection could be better in general. Most of the time they will focus food over anything else and then sometimes work loads of specialists for little reason that creates a lot of unhappiness.

**Comment by azum4roll** [comment]
It's balanced if every puppet behaves the same. We can adjust puppet unhappiness when the annex/puppet balance goes wrong.

**Comment by ilteroi** [comment]
disallowing specialists in puppets seems like an elegant way out to me but does venice get an exception?

**Comment by Stalker012345** [comment]
If the puppet runs out of land, does it just create laborers then, or would it get specialists (maybe engineers) at that point?

**Comment by Mileslewis** [comment]
> disallowing specialists in puppets seems like an elegant way out to me but does venice get an exception?

Puppets can make Great People atm which can be kind of nice, perhaps no more specialists over the city's urbanisation cap?

**Comment by Mileslewis** [comment]
Just had an idea for this.
What if puppet cities get local unhappiness in the normal way but then it's all *0.25 when added to global happiness?

 Puppet cities would generally be at the unhappiness cap which is their population so in practise this would just mean that war weariness/urbanisation/famine would be *0.25 as well as the usual 0.25*pop unhappiness.

Would also allow puppet city's happiness to follow the same rules as other cities so there is some possible control over it.

**Comment by azum4roll** [comment]
That would drag down the global median for gold/culture/science.

**Comment by Mileslewis** [comment]
Btw this is quite a problem on this patch because the governor loves assigning many specialists even in small cities. I just raze or annex all cities atm.
