### ISSUE TITLE
Still Have Missing Greeting Text from CS's

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#700]
![2015-10-15_00001](https://cloud.githubusercontent.com/assets/14372214/10520387/6543a4e2-732f-11e5-8f5d-e576b9a6b542.jpg)

**Comment by LoneGazebo** [comment]
I don't think you installed it all correctly, then.
G

**Comment by Iamblichos** [comment]
Got it.
