### ISSUE TITLE
Difficulty Bonus applying to Puppets

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7000]
So I realize it's intentional for the AI to gain extra Food/Production in all cities.

But unlike the other bonuses (which are meant to simulate human skill level) the bonus to Puppets is simply an AI cheat, and a relatively powerful one considering Puppet cities only produce 20% of normal yields.

I'd be in favor of dividing the bonus Food/Production yields between non-puppet cities only. That way if the AI captures your city and turns it into a Puppet, the puppet wouldn't inexplicably gain a large amount of Food to grow with and Production to build defensive buildings with in a way a human never could.

Not a huge deal, but thought I'd bring it up.

**Comment by LoneGazebo** [comment]
The bonus is divided amongst all cities, though, so the bonus is diluted anyways. I don't think this is an issue.

**Comment by RecursiveStar** [comment]
Fair enough, I guess.
