### ISSUE TITLE
8/23 - 3 - CS Resource Request asking for Resource I already have.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7002]
_1. Mod version (i.e Date - 4/17):_
8/23 - 3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
A CS is asking for Incense, which I already have in my empire, and have for quite some time.

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/91672523-c9fde180-eaf4-11ea-8fb6-c5de8292775c.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Possible that you had traded all copies away?

**Comment by Stalker012345** [comment]
I think your right, even looking at my screenshot it looks like I had traded away all of the copies at that time, so looks like its working as intended.
