### ISSUE TITLE
8/23 - Unit upgrade button graphical bug

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7003]
_1. Mod version (i.e Date - 4/17):_ 8-23-3

_2. Mod list (if using Vox Populi only, leave blank):_
Promotion flags v3
Improved city view v11

_3. Error description:_ 
When there is not sufficient gold to upgrade a unit (or outside friendly territory), the upgrade button displays an incorrect tooltip - whichever was moused over most recently. This is annoying because you can not quickly see the needed amount of gold for upgrade.
![image](https://user-images.githubusercontent.com/59859911/91673928-6c719100-eb04-11ea-80c5-024ee233d623.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I would need your lua logs to debug.
