### ISSUE TITLE
8/23 - 3 - AI not taking advantage of the "Air God"

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7005]
_1. Mod version (i.e Date - 4/17):_
8/23 - HF 3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
America through ruins has gotten himself an Airship very early in the game. This thing is a beast, capable of tanking my best shots and asking for me. But he is just scouting around the map with it, when he could be doing some real pillage damage to my backyard.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/91752914-ad14ed00-eb8c-11ea-8f14-ccec08b7aaff.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
unfortunately AI explorer logic is completely separate from everything else ... but this is really a corner case.
