### ISSUE TITLE
8/23 - 3 - Skirmishers not receiving Terrain CS Bonus

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7006]
_1. Mod version (i.e Date - 4/17):_
8/23

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
My heavy skirmishers here are recieving no combat bonus to the open ground.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/91755442-b902ae00-eb90-11ea-8912-ab6c20f50ef6.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by silentreply** [comment]
I thought this was supposed to be fixed in 8-23? See closed issue #6911

**Comment by LoneGazebo** [comment]
Yep, I caught a merge bug. Already fixed.
