### ISSUE TITLE
8/23 - Brazil's "carnival" unique WLTKD not described in civilopedia

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7008]
_1. Mod version (i.e Date - 4/17):_ 8-23-3 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Brazil's "carnival" appears to replace WLTKD. Intended? UA description only mentions that Brazil gets 10 turns of carnival when starting a golden age. 

From looking at the forums it seems it's always been like this. I can't find any civilopedia entry for "carnival" or "carnaval" or from the brazil page. I'm glad I finally gave this civ a shot, I now realize it's much more powerful than I expected. 

Could an entry page be added for "carnival", or at least reflect this in the UA entry? I've been playing for months and had no idea of this. 

![image](https://user-images.githubusercontent.com/59859911/91903202-db6bf880-ec70-11ea-9bdb-4c2377160f00.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by pineappledan** [comment]
Clarified text in UA:
https://github.com/LoneGazebo/Community-Patch-DLL/commit/cb0aab7602966089571dc3d8e399d578a3074ae9
