### ISSUE TITLE
Enable Open Borders a lot earlier than Civil Service

### ISSUE THREAD

**Issue by Lillebo** [LoneGazebo/Community-Patch-DLL#7010]
This is a feature/change request.

I would love to have the possibility of Open Border agreements a lot earlier in the game. Having Open Borders as late as Civil Service puts a pretty big constraint on any early military engagements - where you're limited to pretty much your immediate neighbors only.

I suggest moving it all the way to Trade or Military Theory (they would make some sense "story wise", no?).

**Comment by DelJon** [comment]
I think this is more suited for the forum. As it's a balance change, and a radical one at that. It affects exploration, tourism, diplomacy and settling. I think a lot of people would object to it, you could try editing a file to test it at your game of course, I can't find which file assigns open borders to civil service though... might be a feature from vanilla?

**Comment by RecursiveVision** [comment]
Yeah, this is something that belongs on the forum, it's a major balance change.
