### ISSUE TITLE
Non-coastal city next to a lake cannot build ships?

### ISSUE THREAD

**Issue by Lillebo** [LoneGazebo/Community-Patch-DLL#7011]
_1. Mod version (i.e Date - 4/17):_
8-23

_2. Mod list (if using Vox Populi only, leave blank):_
N/A

_3. Error description:_ 
This city cannot build any ships except cargo ships? My plan was to put forts on the sides of this large lake to open it up for ships to pass into the ocean. But not being able to build ships in Venice would be a huge bummer. Also weird how I'm still allowed to build cargo ships? Please tell me this can be fixed in a save game compatible way 🙏 
![CivilizationV_DX11_qVA9slfCSt](https://user-images.githubusercontent.com/74510/92011875-fc554c00-ed4b-11ea-8584-2659b9940405.jpg)
![CivilizationV_DX11_tC1hWneuXU](https://user-images.githubusercontent.com/74510/92012008-2a3a9080-ed4c-11ea-93ff-5fc79218594b.png)

_4. Steps to reproduce (optional):_

-------------------------

--
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
Intended as I know. Like in vanilla.

**Comment by ilteroi** [comment]
but necessarily logical

**Comment by DelJon** [comment]
How unfortunate for a Venice playthrough... you can still buy ships from your puppets though?
Either way, this is how this mechanic worked.
Big lakes do spawn occasionally and it feels weird to not be able to build ships in them, as opposed to a slightly bigger inland sea. I am afraid that changing it could lead to the AI stupidly building ships in one-two tiles lakes, and it would also affect the defensiveness of these cities.

**Comment by Lillebo** [comment]
Isn't it possible to limit the ability to build ships in lakes to only human players? The AI would never build forts/citadels for canal purposes anyways - so there's no point in allowing them to build ships on lakes?

**Comment by ilteroi** [comment]
the deeper reason seems to be that trade units are in fact DOMAIN_IMMOBILE, whereas regular ships are DOMAIN_SEA, so different checks apply to them.

it might still be possible to allow building naval units if naval trade routes are possible. the trade route cache uses the pathfinder and so will make use of passable improvements.

**Comment by Lillebo** [comment]
Has it been fixed to allow all ship building - or to also prevent cargo ship building? 🤔

**Comment by RecursiveVision** [comment]
Allow ship building.

**Comment by azum4roll** [comment]
I wonder if we'll start seeing ships in one-tile lakes...

**Comment by ilteroi** [comment]
good point about the harbor. maybe disabling cargo ships is actually the better choice.

**Comment by Lillebo** [comment]
As long as map generation allows for lakes bigger than 1 tile I'd think most players would expect the ability to build ships on them. Implementation difficulties aside. There are lots of historical parallels here after all.

https://en.wikipedia.org/wiki/Battle_of_Lake_Erie
https://en.wikipedia.org/wiki/Great_Lakes_Patrol
https://en.wikipedia.org/wiki/Caspian_Flotilla

**Comment by ilteroi** [comment]
it's an easy change to allow harbors on lakes but it's not so easy to teach the AI when to skip them.

**Comment by azum4roll** [comment]
Would lighthouse establish city connections across lakes? That's a balance change if it does.
