### ISSUE TITLE
8/23 - Possible combat modifier bug

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7012]
_1. Mod version (i.e Date - 4/17):_ 8-23-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm thinking something is bugged here in this combat preview. The horse archer should have a net negative combat modifier yet it appears to have a net positive defense bonus (defending with 16.5 str vs 13 base).
![image](https://user-images.githubusercontent.com/59859911/92036941-ff960b00-ed3e-11ea-8f37-c4b3cfe11315.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Duplicate, and already fixed.

**Comment by silentreply** [comment]
@LoneGazebo @RecursiveVision  I wasn't sure that this was related to the previous issues, which mostly involved the open terrain bonus. I suppose the flip side shown here (rough terrain penalty) is similarly bugged then. Also, shouldn't these issues be labeled "fixed for upcoming version" until the next hotfix is ready?

**Comment by LoneGazebo** [comment]
I marked it that way because I’m already on the new version. Sorry. Hoping to release tonight.

**Comment by RecursiveVision** [comment]
@LoneGazebo If you push your code I can recreate my pull request to avoid merge errors (I changed a lot of files).

**Comment by LoneGazebo** [comment]
I’m not pulling rsi yet, as it’s hotel save game compatible. ;)

**Comment by RecursiveVision** [comment]
Ah, I see.

**Comment by RecursiveVision** [comment]
Gotcha. I'll stay tuned then. :)
