### ISSUE TITLE
How to delay war declaration until a certain trigger

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7013]
@ilteroi So in the rsi branch I have a number of fixes relating to AI war logic, with the changelog listed in the pull request. One of these causes the AI to prepare sneak attack operations for coop wars that are due to take place "soon".

Problem 1) The AI will currently declare war as soon as the operation is finished and (due to the new rules) drag their ally into the war early, possibly more often than not. There needs to be a delay where they stay in position but don't attack, but I have no idea how to accomplish this.

Problem 2) The AI will probably trigger a move troops request by moving their units so close rather than hiding them out of sight until it's time, causing them to be forced to declare war early and having the same effect as problem 1.

Any ideas on how to address these?

**Comment by ilteroi** [comment]
difficult. right now there is a muster plot and a target plot. it seems you want a "staging" plot in between. would need a lot of new code.

**Comment by LoneGazebo** [comment]
@ilteroi conversely, would it be possible to set a 'turn we should arrive at target plot' and have the army only leave muster when the turn to arrive is the same as the number of turns it takes to get to the target?

**Comment by ilteroi** [comment]
unfortunately it's very hard to tell how long it will take to get to the target. army movement is different from single unit movement.

**Comment by RecursiveVision** [comment]
@ilteroi I see. Well the AI actually preparing for coop wars is still an improvement, even if there isn't an easy way to make them delay their attack.

How about making them delay at the target plot before declaring war if a coop war is pending, is that achievable?

**Comment by RecursiveVision** [comment]
Then you could set the target plot to be just outside the boundaries where the AI can send a move troops request if a coop war is pending, and otherwise just use the normal logic. That's an easier way of achieving it than a separate staging plot, I think.

**Comment by ilteroi** [comment]
after thinking some more it might be possible to simply delay further movement when we get too close to the target too early, with introducing another waypoint ... need to check
