### ISSUE TITLE
Promotion Open Terrain Modifier Doesn't Work as Intended Again

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#7015]
_1. Mod version (i.e Date - 4/17): 9/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Field 3**
![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/92092663-0e320000-eddb-11ea-89cf-2b360110aa49.jpg)

**Here works ok**
![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/92092670-10945a00-eddb-11ea-89c1-b1afeca6d943.jpg)

**Here total strength value should be bigger than previous screenshot, but the damage inflicted is ok (open terrain modifier is working)**
![Civ5Screen0002](https://user-images.githubusercontent.com/49090452/92092676-11c58700-eddb-11ea-968d-dc4a4bd5c4bc.jpg)

**Here is still rough terrain but has different damage and the same strength compared with 2nd screenshot (hill + forest)**
![Civ5Screen0003](https://user-images.githubusercontent.com/49090452/92092681-138f4a80-eddb-11ea-9d9e-027c330e406d.jpg)

**Here again, same strength value, different damage compared with 2nd screenshot**
![Civ5Screen0004](https://user-images.githubusercontent.com/49090452/92092690-14c07780-eddb-11ea-8a61-5c89529c842d.jpg)

**Here again, same strength value, different damage compared with 2nd screenshot (marsh)**
![Civ5Screen0005](https://user-images.githubusercontent.com/49090452/92092693-15f1a480-eddb-11ea-83f8-0e0aeb974d33.jpg)

**Comment by silentreply** [comment]
I am seeing similar behavior as reported previously. Below, the skirmisher is defending with a net 40% bonus, but should have a net 30% penalty. 
![image](https://user-images.githubusercontent.com/59859911/93039746-4674e200-f616-11ea-9097-40671b32ff15.png)
