### ISSUE TITLE
Installer Wizard

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7018]
@LoneGazebo Any chance you could share the software you use to create the executable launchers for new versions?

I don't intend to supplant you as project lead or anything, however I can think of several potential uses:
- If you ever become inactive again for an extended period of time due to real life obligations or problems, ilteroi or I could fill in for you with interim patches. I often make database changes and as a result some of ilteroi's interim builds didn't include my changes to reduce complication to the end user.

- It can be somewhat challenging to debug or test when a lot of changes to LUA files have been made, and since you already have a program that installs everything in the correct location, I could delete my MODS folder and use the special version I created to make sure all the changes get in correctly.

- It's useful to have auto-installer software if I want to send a friend a modified version of the game, or make a modmod, or get beta test feedback for a specific feature, etc.

Thoughts on this? I'm not sure whether the software you use costs money, but you seem to be able to post new versions relatively quickly once the code is straightened out.

**Comment by LoneGazebo** [comment]
No worries! Here's what I use:

https://www.kymoto.org/products/inno-script-studio/

The .iss file is already on github, it is called CPPSetupData.

Note that there's a specific structure you need to follow for the folders. They have to look like this:

![image](https://user-images.githubusercontent.com/7849458/92254724-edc77b80-ee96-11ea-9ce4-a5a19d0d7013.png)

Note that the CP LUA and CBO LUA folders have to be moved out of the CP and the CBO into those external folders. If you do that, it should compile out of the box. :)

**Comment by RecursiveVision** [comment]
Thanks! :)

**Comment by bukowa** [comment]
@LoneGazebo Looks like there are some files missing in the github repository:
````
LicenseFile=C:\Users\Jeff\Documents\Community Patch Project Installer Files\License.rtf
InfoBeforeFile=C:\Users\Jeff\Documents\Community Patch Project Installer Files\Opener.rtf
SetupIconFile=C:\Users\Jeff\Documents\Community Patch Project Installer Files\installer.ico
````
Can you provide them?

**Comment by bukowa** [comment]
@LoneGazebo There's also folder named "UI_bc1" that is not included. Is this a specific version? Is there anything else i am missing that is not included?

**Comment by LoneGazebo** [comment]
Easier and safer to just download the inno files locally, compile, and then reload. In any case I've uploaded the requested files (except for the .modinfo files, as those come from compiled mods).

**Comment by bukowa** [comment]
Thanks for the files. I don't have any idea about compiling this stuff, is there easy way to do that using command line interface? Can you explain that in some simple steps?

**Comment by LoneGazebo** [comment]
Compilation takes place through the CIV 5 SDK, namely modbuddy.

**Comment by bukowa** [comment]
Oh ok 😆 that complicates some stuff i will take a look.

**Comment by bukowa** [comment]
I found this topic https://forums.civfanatics.com/threads/build-mods-from-command-line.520729/
From what i understand you need CIV 5 files to compile the mods?
