### ISSUE TITLE
Consolidation of LUA files

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7019]
@LoneGazebo Recently you deleted the various versions of EnemyUnitPanel.lua and replaced them with a single file, which is a much-welcomed change, at least on my part. :)

I get the feeling there isn't much difference between 43 Civ and normal LUA files, although there are clear differences between EUI and non-EUI.

To me it seems that many of these files could be consolidated into fewer copies...

**Comment by LoneGazebo** [comment]
Possibly, but the files are maintained as such because of how the installer manages them. Keep in mind that if you're using (6c) you don't need (6a) or (6b).

**Comment by RecursiveVision** [comment]
I'm aware of that, it's just annoying to change so many files every time I need to make an LUA change.
