### ISSUE TITLE
Railroads do not provide the movement bonus

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#702]
I am in the industrial era and units expend less movement on roads than on railroads.

**Comment by LoneGazebo** [comment]
Initial railroads start out with barely any movement bonuses - have you teched ahead to see if the later tech bonuses change this?

G

**Comment by Radost** [comment]
What the point of them providing less bonus than roads the moment they get available?

**Comment by LoneGazebo** [comment]
+25% production in all cites connected via rails.

**Comment by Radost** [comment]
So what was the fix?

**Comment by LoneGazebo** [comment]
Ilteroi said that he fixed this, so I'm going to assume so until told otherwise. If not, re-open and we'll move forward from there.
