### ISSUE TITLE
Defense production option is a big problem for Venice

### ISSUE THREAD

**Issue by Lillebo** [LoneGazebo/Community-Patch-DLL#7020]
_1. Mod version (i.e Date - 4/17):_
8-23

_2. Mod list (if using Vox Populi only, leave blank):_
N/A

_3. Error description:_ 
The ability to turn production into defense is a huge problem for Venice. This city is needlessly producing defense even though I'm not at war with anyone - and there's still other buildings or units this city could be producing instead. I'm losing a lot of production to puppets preferring to build defense :(

![CivilizationV_DX11_r1rCYjgq8B](https://user-images.githubusercontent.com/74510/92288864-cc09db00-ef0e-11ea-945b-982204239d07.png)

![CivilizationV_DX11_19sqoOb2EO](https://user-images.githubusercontent.com/74510/92288898-e774e600-ef0e-11ea-81ad-c04565e1a5ba.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
Lol I am having the opposite problem where I wish my puppet cities would produce defense while I am defending at war.

**Comment by Lillebo** [comment]
A little curious why this issue was closed?

**Comment by RecursiveVision** [comment]
I closed most old issues. Gazebo changes city production logic quite often. If it's still an issue in the latest version just open another issue. :)
