### ISSUE TITLE
Cannot capture civilian units

### ISSUE THREAD

**Issue by JohannesGaessler** [LoneGazebo/Community-Patch-DLL#7027]
_1. Mod version (i.e Date - 4/17):_
9-2

_2. Mod list (if using Vox Populi only, leave blank):_

* Ingame Editor
* Really Advanced Setup
* Standard Production - Epic
* Wonder Race
* I'm playing on Linux via Wine

_3. Error description:_ 
I cannot capture civilian units during war.
If I select a regular units and click on the civilian unit nothing happens as if I was trying to move into a mountain.

[debug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5177986/debug.zip)

**Comment by Zanteogo** [comment]
To add to this, you can take civilian units if they are sharing a space with a military unit. So if you attack a unit being guarded you can move into the space after killing the unit. You cannot move into the space without however.

**Comment by ilteroi** [comment]
side effect from fixing #6981

**Comment by anders4** [comment]
While upcoming patch have fixed it.
I noticed that it seems to be medival era units, Tercio can capture but not knight, crossbow etc.
