### ISSUE TITLE
9/2 - Low religious pressure and other observations

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7029]
_1. Mod version (i.e Date - 4/17):_ 9-2 hotfix

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
There was definitely something strange going on with pressure in 8-23 version, so I was glad to see there was a fix in 9-2. However, pressure seems very low across the board in the 9-2 hotfix. Conversion possibly seems quicker though. 

My holy city has a mosque and mandir (+50% pressure) yet either has no religious pressure with nearby cities or very low. It also appears that there is no pressure for internal trade routes anymore, even when the cities are not receiving pressure to begin with (such as Salvador below). 

![image](https://user-images.githubusercontent.com/59859911/92313218-4aaa5b00-ef97-11ea-8dec-d5206bdabc5f.png)

![image](https://user-images.githubusercontent.com/59859911/92313215-41b98980-ef97-11ea-8caa-294e212f25f0.png)

![image](https://user-images.githubusercontent.com/59859911/92313248-a96fd480-ef97-11ea-8f2b-72393bec53f4.png)

P.S. Are cities supposed to change the requested WLTKD resource if not acquired after some time? This seems to be happening quite often in this game, especially when I move an emissary to the CS border with the desired resource...

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by silentreply** [comment]
Below you can see there is now very high pressure (+55) from Islam, yet no cities following Islam in proximity, no trade routes. The only cities I have revealed following Islam are the two Songhai cities far to the northeast. This is similar to what I was seeing earlier with 8-16 and 8-23 versions where some religions would have inexplicably high amounts of pressure. ![image](https://user-images.githubusercontent.com/59859911/92342813-ff27a800-f08f-11ea-8a21-a0c54e3265a6.png)

**Comment by ilteroi** [comment]
i would guess the islamic cities are across the sea.

**Comment by silentreply** [comment]
There may be some pressure coming from the sea to the east, but I think most of it is coming over land. It seems as though the spread distance is not capped. Is it possible the Songhai UA (land units ignore terrain costs next to river) might be effecting the pressure pathfinder?

About 25 turns later and nearly every city on the continent has fell to Islam and its absurd pressure amounts. The Iroqois religion only has the holy city left, which will be converted soon. Some of his cities are receiving nearly 200 pressure. 
![image](https://user-images.githubusercontent.com/59859911/92415592-a7d51680-f127-11ea-855e-f1110379a613.png)

**Comment by RecursiveVision** [comment]
> About 25 turns later and nearly every city on the continent has fell to Islam and its absurd pressure amounts.
You could make a religion out of this.

**Comment by ilteroi** [comment]
well sea trade routes have quite a long range, so you get a lot of pressure in coastal cities.

add in building and belief modifiers and you easily end up with 12 or 15 pressure per city.

**Comment by silentreply** [comment]
On turn 183, I started to try to fight back against the spread - mainly to try to unlock my reformation belief, and buy a couple buildings I am missing. I popped inquisitors in my 3 expansions and used a GP to convert the nearby city states. 

Here is something strange.. the GP used on Brussels converted 8 citizens and removed followers of all other religions. On the same turn, I used inquisitor on Brasilia, which gave me 13 followers of Sikhism (my religion) and removed all others. Only four turns later, Brussels has 177 pressure for Islam, and Brasilia has 152. However, only 3 citizens converted to Islam in Brussels where my religion is still holding on, while 5 have converted in Brasilia and already lost majority. 
![image](https://user-images.githubusercontent.com/59859911/92419245-42d6ec00-f13a-11ea-90ad-96b510a00b44.png)

**Comment by silentreply** [comment]
Was the pressure falloff from distance removed from naval routes? Islam does not have any buildings or belief modifiers. The naval routes are probably the major factor at this point in the game, but in the first images I posted I don't believe they were in range. I tried removing the fort next to my capital and it had no impact on the pressure received. 

As for the trade route pressure, it seems the pressure just isn't being displayed in the active routes page. It is being applied to cities. 

![image](https://user-images.githubusercontent.com/59859911/92421835-87698400-f148-11ea-8824-750cf01ff510.png)
![image](https://user-images.githubusercontent.com/59859911/92421861-b8e24f80-f148-11ea-886a-fff3e740fe3d.png)

**Comment by silentreply** [comment]
Surely a city such as this one, in the heart of Islam and in closer proximity to all the coastal cities, should be receiving higher pressure than my city.
![image](https://user-images.githubusercontent.com/59859911/92422145-0f03c280-f14a-11ea-9916-3026999affdb.png)
![image](https://user-images.githubusercontent.com/59859911/92422182-45d9d880-f14a-11ea-89a5-f307eda877ae.png)

**Comment by silentreply** [comment]
At one point I was able to convert all of my cities, the surrounding city states, and nearby Iroqois cities to my religion. It barely made a dent in the pressure of Islam. Even with my inland city completely surrounded by my religion, had less than half the pressure of Islam. I am fairly certain if you counted up all the possible trade connections to that city, even assuming that all the Islam connections had max pressure (they shouldn't), it would not explain the observed pressure. Keep in mind that Islam has no pressure beliefs or buildings, yet my cities in close proximity include the holy city, mosques, mandir, etc. 

![image](https://user-images.githubusercontent.com/59859911/92435260-e1317480-f16f-11ea-834a-efdc081d2bfb.png)


I also observed that city-states took far longer to convert back to Islam, despite having higher pressure in some instances, something is not right there. 

My biggest frustration with the current system is that it is nigh impossible to calculate what the appropriate pressure values should be. It's extremely difficult to determine what is or isn't working. The mechanics are heavily based on guesswork and feel, and from my observations I don't feel everything is working correctly. I remember there was some discussion a while back about removing passive pressure, perhaps we could revisit that.

**Comment by ilteroi** [comment]
oh yes i would be very much in favor of removing passive spread, or more precisely limit it to cities connected by trade. but that has a lot of knock-on effects, don't know if you can organize a majority for that.

anyway the UI is hell, starting with the fact that it shows only pressure per turn but not where it's coming from nor the accumulated sum. but so far in all the cases i have checked the pressure turned out to be correct - it's just that the source cities may be invisible to you.

**Comment by Stalker012345** [comment]
So it wouldn't explain all of it, but is Islam running with Fealty? That could be a +50% boost right there because of Organized Religion, which would start to explain the pressure.

Also, check the trade routes and find out how many routes are coming from Islam cities. If its a large amount it might also explain it, and that should be easy to look at and check.

**Comment by azum4roll** [comment]
How much is the current sea pressure compared to land pressure? It really needs to be lower since you travel further by sea.

**Comment by silentreply** [comment]
@Stalker012345 That's a good point, Songhai/Islam does have full Fealty. I never thought that policy was very strong based on the description, but after you brought that up I did some searching on the forums, and it seems it doesn't work exactly how I would have thought. There is one trade route going to my city, from one of Mongolia's cities - which based on what I read would have a +50% bonus because he also has Fealty. Still, I don't think it would explain all of the pressure difference, or some of the other quirks I have been noticing. 

@azum4roll I'm curious if something was changed recently with the pressure falloff for naval routes. I know in the past it was an issue because you often wouldn't transfer any (or very low) pressure to your cities by sea. But in game it appears to me the falloff from sea pressure has been greatly reduced or eliminated. 

Now here's another interesting one. Eastern orthodoxy has 1 city where it is majority, yet is giving off 71 pressure to this city.
![image](https://user-images.githubusercontent.com/59859911/92550640-fb2f8d80-f229-11ea-9dd1-66147ecb2d7e.png)
![image](https://user-images.githubusercontent.com/59859911/92550608-e2bf7300-f229-11ea-81bc-fa3161a68230.png)

**Comment by azum4roll** [comment]
Note that all cities with any amount of followers would emit pressure of their religion (boosted by the respective religion building), not necessarily the majority.

**Comment by ilteroi** [comment]
found the bug

**Comment by silentreply** [comment]
@ilteroi Thank you! I didn't think I had gone crazy...yet. I will look forward to trying out those options as well.

**Comment by ilteroi** [comment]
in fact i think RELIGION_PASSIVE_SPREAD_WITH_MAJORITY_ONLY should be active by default

**Comment by RecursiveVision** [comment]
I agree, @ilteroi, it isn't intuitive otherwise.

**Comment by Stalker012345** [comment]
> in fact i think RELIGION_PASSIVE_SPREAD_WITH_MAJORITY_ONLY should be active by default

So are you saying that a city would only generate passive religious pressure for its majority religion? I would be good with that personally, as that's how I actually thought it worked for a long time. Let me throw a poll on the forum and see people's reaction.

**Comment by azum4roll** [comment]
Change back Inquisitors first. That really needs to be done.

**Comment by silentreply** [comment]
@Stalker012345 I'm not sure that is how the organized religion policy works. See the discussion on this page: https://forums.civfanatics.com/threads/quick-questions-quick-answers.573489/page-302#post-15692981

From this I gathered that it is actually a bonus to (all?) religious pressure _emanating_ from your cities (and supposedly any other city where the owner has the same policy, even when following your religion). And if that is the case, I think the description in-game needs an update.

**Comment by a3kov** [comment]
In my current game, the capital is not producing any passive pressure to satellite cities at all. All satellites have 1-2 followers from India that is far away (no Orthodoxy or traderoutes with me) and some pressure from them as well. Has it been fixed ? This is version 9-2
![Screenshot_20200919_132709](https://user-images.githubusercontent.com/813860/93659962-016d0780-fa7d-11ea-81ef-d1c2b83ed7aa.png)

**Comment by a3kov** [comment]
In the same game, if I send a caravan to a neighbor's city, the caravan adds just +1 pressure - way too low.

**Comment by skodkim** [comment]
OMG am I glad to see a fixed bug on this one. Low religious pressure really killed my current game, where my religion (Orthodoxy) just doesn't seem to spread passively while a far away religion (Catholicism does). I do seem to have pressure (~+30) in my holy city does none or next to none in the neighboring cities (again exept from Catholicism) and I had no idea what was going wrong. Right now I'm at the point where I actually lost my religion in my holy city... See screen shots.

I'm running a modded game so I didn't really feel it was right to make a new bug report, but I'm confident that the only mod affecting religion is calypsos colored religions + some minor tweaks of my own (e.g. upped pressure a bit to to to counter this...).

Am I wrong or this a fairly new "feature"? :-) Didn't see it before the newest hot fix.

![Civ5Screen0003](https://user-images.githubusercontent.com/6018459/93731812-f9bd7800-fbce-11ea-8280-22e78cbf4c53.jpg)

![Civ5Screen0002](https://user-images.githubusercontent.com/6018459/93731825-1063cf00-fbcf-11ea-929f-73fed12c4609.jpg)

**Comment by skodkim** [comment]
@ilteroi Oh, one question though: Does this mean we can fix it by tweaking CustomModOptions or is there something in the code as well? (didn't really understand your answer at that point).

\Skodkim

**Comment by asche77** [comment]
Gentlemen, I'll chip in with another observation on strange religious pressure, i.e. religious buildings:

My understanding from the in-game descriptions was that building religious buildings would add pressure of my (majority) religion both in that city(?) and towards other nearby cities, and reduce other religions' pressure towards that city.

However, what I see happening from in-game "hover over" is that actually pressure on that city **drops** -- both pressure of my(!) religion as well as pressure of foreign religions on that city. (I can follow up with screenshots later).

Further, to chime in with the consensus of this thread, religious pressure of the player seems to be difficult to be built up and not on par with pressure exerted by AI (assuming roads, shrines, temples built). Therefore looking forward to the new version!
