### ISSUE TITLE
Barbarian unit is stuck

### ISSUE THREAD

**Issue by Senteliks** [LoneGazebo/Community-Patch-DLL#703]
What happened is that Barbarian axeman  embarked on lake, which is close to my capital and stood idle for 7-8 turns, frankly doing nothing. I bet he would remain there much longer, have I not killed it.

http://s13.postimg.org/exggmxa6f/Civilization_V_DX11_2015_10_16_11_14_55_28.png

Some other points:
-It didn't move to capture worker, even though I put worker in front of him
-It didn't engage my or other civ units, even though I gave him enough space to disembark.

I was concern with whatever to post this report or not, because at glance it's "minor" inconvenience and I don't recall, encountering this before , however this problem might affect more things than this one, especially if it's related to AI Naval patch finding /logic.

Edit: I did a little test just now (I reloaded save before I killed it) , Instead of killing it, I stopped at wounding him while he was embarked.As soon as next turn started it disembarked.

**Comment by LoneGazebo** [comment]
It's a quirk, sure, but it is technically harmless. The AI gets sketchy when trying to think about disembarking into hostile territory.

G

**Comment by Senteliks** [comment]
Here is one more similar problem 
http://postimg.org/image/q4j4qy3gj/24da7227/

This is technically harmless but annoying. So what you see on that SS is Danish swordsman,that's embark and disembark in loop for the past 25 turns.For example, one turn he embarks and next disembark and that's all it does.

I wasn't in war with Denmark, AI explored with that swordman and ran into barbarian camp (I think at least).

**Comment by ilteroi** [comment]
oh no, not again :)

i'll keep an eye on it, haven't seen this in a while
