### ISSUE TITLE
broken city tooltip

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7031]
![image](https://user-images.githubusercontent.com/1358966/92332970-c1bc1e00-f081-11ea-9c1d-4de6d0ea6ef7.png)

this is with the latest e13ecec7748def07bc040911f5d2fdd4a0dc51c1

**Comment by RecursiveVision** [comment]
@ilteroi Did you update your LUA files as well as the build? I changed a lot of LUA files.

**Comment by RecursiveVision** [comment]
I deleted all of the code that related to trade agreements, as they were an unused vanilla deal item.

**Comment by ilteroi** [comment]
well ok then

**Comment by RecursiveVision** [comment]
Nearly 2.5k less lines of useless code :)
