### ISSUE TITLE
6-19: Crash to desktop on turn 406

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#7032]
_1. Mod version (i.e Date - 4/17):_
June 19th (5.6.19)

_2. Mod list (if using Vox Populi only, leave blank):_
VP (all of it)
Enhanced Naval Warfare for Vox Populi

_3. Error description:_ 
Crash to desktop around turn 406. I've run four games, with assorted mods; all of them CTD during AI steps (between player turns) in turns of early 400s. Seems to crash after processing a turn for an AI who is at war with me. (With each subsequent game, I removed a mod and started over, hoping to eliminate a possible incompatibility/conflict with the latest VP version. I'm writing now because I don't think ENWfVP has such a conflict.) 

_4. Steps to reproduce (optional):_
Start as Sejong (Korea), play on Huge Communitas map.
Play 400+ turns.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
CTD issues were fixed in the latest beta
