### ISSUE TITLE
SetToolTipString to blank string / disable?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7036]
How do I set a button's tooltip string to a blank string (i.e. disable the tooltip from popping up) in LUA?

Specifically I'd like to make it so that the Demand button tooltip (added in https://github.com/LoneGazebo/Community-Patch-DLL/pull/7035/commits/e4e0b19c1bfaf04f9b497cd55980b79cf8d00d6a) does not show up if you mouse over the Demand button while at war with a civ.

**Comment by RecursiveVision** [comment]
@LoneGazebo Any tips?

**Comment by LoneGazebo** [comment]
@RecursiveVision sorry I missed this - the only way to prevent it would be to rewrite the TT function in the LUA/XML - if the TT is generated in the XML file for the UI, you'll have to remove it from there, set it in the LUA instead, and simply have a if/else check for whether or not it should exist.

**Comment by RecursiveVision** [comment]
Oboy, messing with text files :)

I'll have to test this next version. Thanks!
