### ISSUE TITLE
plot yields are inconsistent

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7038]
check for the string "houston, we have a problem!" and put a breakpoint there.

it will trigger fairly regularly in the latest version, don't know what was changed ...

**Comment by LoneGazebo** [comment]
It’s been doing that for a long time, I’ve started ignoring it. I can’t figure out what’s causing it.

**Comment by azum4roll** [comment]
So... what IS the problem?

**Comment by silentreply** [comment]
This bug is the real hydra. I've been ignoring it as well, but it would be great if someone can figure it out.
