### ISSUE TITLE
9/2 - AI not purchasing natural wonder tile

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7039]
_1. Mod version (i.e Date - 4/17):_ 9-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This city has been there for a very long time yet never purchased out to Solomon's mines. 
![image](https://user-images.githubusercontent.com/59859911/92433284-9d883c00-f16a-11ea-80c3-dfa575481a05.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Do AIs have decision making for tile buying different from natural growth? Could be the same reason why Incas don't purchase mountains?

**Comment by ilteroi** [comment]
they only purchase tiles adjacent to their border - no long term strategizing here - and unfortunately the intermediate tiles are worthless.

**Comment by silentreply** [comment]
Nine turns after acquiring the plains tile, the city has acquired (naturally, I presume) the wonder tile. Surely they take the presence of the NW into account when choosing the settle location, and I would say the AI chose the objective best tile for this settle location. Unfortunately the city likely missed out on 100+ turns of working the NW, and were it in a more contested area, could easily have lost it to another civ. 

Is it possible to code an exception into the AI purchase logic? Something along the lines of: if NW within 3 tiles, prioritize purchase of tiles leading to it? 

![image](https://user-images.githubusercontent.com/59859911/92825602-baf11c00-f39d-11ea-8d22-72dbe05535af.png)

**Comment by ilteroi** [comment]
the question is how often does this case occur and how much is the overhead for the added checks

**Comment by LoneGazebo** [comment]
I think this is a 'if we get bored later after all bugs and optimizations are fixed' thing.

**Comment by azum4roll** [comment]
Pretty often, since tiles around a natural wonder are trash most of the time.
