### ISSUE TITLE
Question about SPECIALUNIT_PEOPLE

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#704]
In testing, I found that Policy_FaithPurchaseUnitClasses doesn't allow for faith purchasing of civilian units like Settlers and Workers. I expect this is linked to the 'SPECIALUNIT_PEOPLE' tag. I'm guessing there's no easy way to make this more modular, so I have a hacky workaround, but I'd need to know if there would be any unintended side-effects to making a non-Great Person unit a 'SPECIALUNIT_PEOPLE.' 

One such side-effect would be the 'Glory to God' Reform Belief, which unlocks faith purchasing of all GP, but I can work around that with a dummy policy. Another is the various 'Choose Free Item' popups, but I can replace those. Are there any others that you might know from your experience with the DLL?

**Comment by LoneGazebo** [comment]
It does come into play with any policy or building (like halicarnassus) that procs a yield when a GP is created/used. It'd probably be better for me to just add in the ability to buy non-GPs that way.

You can add policytypes to specific units to make them only unlock with certain policies. You could do that with a new settler/worker and then make them faith-purchase only.

**Comment by JFDaly** [comment]
Yeah, I tried using Policy_FaithPurchaseUnitClasses, but that only works if I set a FaithCost and a PrereqTech to the units, which means they also become available with the Holy Warriors belief. If it's easy, then it'd be useful, but it's no big deal. Thanks for the info.

**Comment by LoneGazebo** [comment]
Did you try specifically using the <PolicyType> row for <Units> ? For example if you create a new settler, and give it that tag (with your policy), and then give it a faith cost (but no gold cost), that should make it work, no?

**Comment by JFDaly** [comment]
Tried that. If you give a unit a faith cost without setting RequiresFaithPurchaseEnabled, it'll become available as soon as you get a religion. If you set RequiresFaithPurchaseEnabled, it'll become available with the Belief_EraFaithUnitPurchase table (i.e. the Holy Warriors belief).

**Comment by LoneGazebo** [comment]
Alright, I've made you a fancy new table that'll allow you to set specific units that are unlocked by specific beliefs. I'll upload a test version for you in a bit.

**Comment by LoneGazebo** [comment]
Just saw your edit - oh well! I'm sure an extra table will come in handy. :)

**Comment by JFDaly** [comment]
Well, a new table is most definitely better, as it means I don't have to create copies of the Settler, Worker, and Colonist, which then runs into trouble if anyone has any unique versions of these.

**Comment by JFDaly** [comment]
I reported an issue with Belief_SpecificFaithUnitPurchase interfering with the regular unit faith purchasing, but as I did so in the "ExCE and CTD" thread, I'm guessing it got lost, so I'll repeat it here (and close the CTD thread, as I don't think there's much more that can be done at this point).

Hm, regular faith purchasing of units with Holy Warriors/Religious Fervour appears to have broken. And Belief_SpecificFaithUnitPurchase works only when Belief_EraFaithUnitPurchase is filled with the eras which unlock the units specified in the former table.

**Comment by LoneGazebo** [comment]
Yeah, I fixed that first issue. Second issue is a little confusing. Are you setting 'requiresfaithpurchase' to true? Because you don't need to if you are using the 'specificfaith' unit table, as it returns true regardless of the 'requiresfaithpurchase' element (if you have the faith to buy it, it'll show up).

In the even that it still acts up, I've added another column for you to the Units table: 'BeliefRequired'.
This column needs a Belief type (so BELIEF_SACRED_PATH, etc.) to work. If you put one in, and the city does not have this belief in it, it'll return false even if you have 'faithpurchaseenabled' on the unit.. So you can use this to make things a bit more granular.

**Comment by JFDaly** [comment]
I have RequiresFaithPurchaseEnabled indeed. I did test it without that, but if you give the unit a FaithCost, this allows it to be purchased just with a religion. If you don't give it a FaithCost, it doesn't show up whatsoever. But I think BeliefType would fix this entirely anyway.

**Comment by LoneGazebo** [comment]
Yep. Should work as you want it to, hopefully.

**Comment by LoneGazebo** [comment]
New stuff should be in latest version for you. Let me know if works/doesn't work.
G

**Comment by JFDaly** [comment]
The new functions appear to work, but what is the second parameter in GetFoundYear()? The first is the religion ID, and the second (an integer) doesn't appear to affect anything, so I was just wondering. The functions actually return the turn that it was founded, but with SetFoundYear I can translate that into the game year.

BeliefRequired works perfectly. Thanks again.

**Comment by LoneGazebo** [comment]
Second variable was eFounder, but the value isn't actually needed. I'll remove for the sake of sanity.

Glad it all works! 

G
