### ISSUE TITLE
9/2 - poor AI inquisitor logic

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7040]
_1. Mod version (i.e Date - 4/17):_ 9-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Iroqois control Eastern Orthodoxy (with the inquisition enhancer), yet is attempting to convert all his cities using missionaries. All the cities with no majority religion are cities I used a GP on and he followed with missionaries. 
![image](https://user-images.githubusercontent.com/59859911/92436484-cb717e80-f172-11ea-9c4c-915a363d28e6.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Inquisitors don't work on cities without a majority religion. (which is stupid imo)

**Comment by JamesNinelives** [comment]
I don't have strong feelings about it, but the AI should at least be taught how to use them.

**Comment by silentreply** [comment]
I agree on that, however the cities _had_ a majority religion (mine), then removed the majority with missionaries.

**Comment by Stalker012345** [comment]
I will also note I never see inquisitors anymore when I am trying to convert someone else. I could understand not initially, but if I'm starting a conversion, adn the AI doesn't want that, faith buying an inquisitor or 2 would seem to make good sense.

**Comment by azum4roll** [comment]
Maybe they find it's not worth the faith cost with only 50% conversion resistance, and the yield loss from using them to remove heresy?

**Comment by silentreply** [comment]
@azum4roll His religion has the inquisition enhancer, it would be much more efficient to use the inquisitors imo.

**Comment by ilteroi** [comment]
AI is using inquisitors alright, in my testgame i had 109 missionaries and 43 inquisitors in 284 turns.

**Comment by silentreply** [comment]
That is good to hear! I can also report that Iroqois eventually did make use of the inquisitors in their cities, as shown below. 
![image](https://user-images.githubusercontent.com/59859911/92827007-58991b00-f39f-11ea-98d0-6fff47e82138.png)
