### ISSUE TITLE
Militaristic City-States consistently having the same Unique Units

### ISSUE THREAD

**Issue by JamesNinelives** [LoneGazebo/Community-Patch-DLL#7042]
_1. Mod version (i.e Date - 4/17):_
9/2, possibly earlier

_2. Mod list (if using Vox Populi only, leave blank):_
None

_3. Error description:_ 
Militaristic City-states should offer a random unique unit, but currently certain units are turning up much more often than others.

I ran 20 test games with 16 city-states each and got the following results:
Janissary: 16 times
Minutemen: 15 times
Mohawk Warrior: 5 times
Narasaun's Elephant: 5 times
Legion: 2 times
Maori Warrior: 1 time
Panzer: 1 time

Notably, the units other than Janissary and Minutemen were only present on maps with more than 2 militaristic city-states. The units Legion and Maori Warrior were only offered by CSs when there were at least 4 militaristic city-states (including those offering the more 'common' UUs).

It should be noted that on 2 games none of the city-states were militaristic, and in at least 2 games either America or The Ottomans were playing (and therefore those units could not be offered by city-states). Hence why no unit appears 20 times.

The other settings I used for the 20 tests were: Small, Fast, 2 civs only, player civ: Shoshone. Map: lakes. However, I trialed various settings before settling on one and the trend was noticeable across settings. One change that occured was that when starting in the Classical rather than Ancient Era, the Mohawk Warrior was not available and the Panzer was more common instead. Anecdotal evidence has also been provided by others in the Civfanatics forums and I had seen this in my own Epic speed, Huge Continents map. I wanted to make sure I had something a bit more solid though.

---------------------------
Example game
![20200908183841_1](https://user-images.githubusercontent.com/61379041/92515448-363fba00-f246-11ea-8ddf-7f1a86b6385e.jpg)
![20200908172246_1](https://user-images.githubusercontent.com/61379041/92515451-3770e700-f246-11ea-8971-9860805f63a2.jpg)

**Comment by Stalker012345** [comment]
completely speculative follow up but I have noticed a lot of janissaries in my games.

**Comment by silentreply** [comment]
I always thought this was more than speculation. Thanks for taking the time to get some numbers on this.

**Comment by Mileslewis** [comment]
I had a look at this at some point and it seemed like total gold produced was being used to randomise it. But aren't they chosen at the start so this always gives the same?

Ngl I didn't fully understand they system though.
