### ISSUE TITLE
diplo AI performance drag

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7044]
i did a profiling run and found some major issues, should be much better now in lategame.

but one thing remains:

![image](https://user-images.githubusercontent.com/1358966/92518841-4b522400-f219-11ea-855c-c365e4ddb7ab.png)

the tactical AI makes frequent calls to diplo AI which in the end iterate over all players.

is there a way to improve this?

**Comment by LoneGazebo** [comment]
which of those iterates? The playervalid one?

**Comment by RecursiveVision** [comment]
IsPlayerValid doesn't iterate IIRC. Seems like an issue on your end.

**Comment by RecursiveVision** [comment]
```
/// Is this a valid player to be looking at for diplomacy purposes? (e.g. are they alive, do we know them, etc.)
bool CvDiplomacyAI::IsPlayerValid(PlayerTypes eOtherPlayer, bool bMyTeamIsValid /* = false = */ ) const
{
	if ((int)eOtherPlayer < 0 || (int)eOtherPlayer >= MAX_CIV_PLAYERS) return false;

	// Alive?
	if (!GET_PLAYER(eOtherPlayer).isAlive())
	{
		return false;
	}

	// REALLY Alive? (For some reason a player can be "alive" but have no Cities, Units, etc... grrrr)
	if (GET_PLAYER(eOtherPlayer).getNumCities() == 0)
	{
		return false;
	}

	// A player we've met?
	if (!GET_TEAM(GetPlayer()->getTeam()).isHasMet(GET_PLAYER(eOtherPlayer).getTeam()))
	{
		return false;
	}

	// On our team?
	if (!bMyTeamIsValid)
	{
		if (GET_PLAYER(eOtherPlayer).getTeam() == GetPlayer()->getTeam())
		{
			return false;
		}
	}

	return true;
}
```

**Comment by RecursiveVision** [comment]
@ilteroi Actually I think I found the issue, this should help: https://github.com/LoneGazebo/Community-Patch-DLL/pull/7035/commits/f402e34db226bc020383976de193625892252cdc
