### ISSUE TITLE
9/2 - Train station construction requires seaport

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7045]
_1. Mod version (i.e Date - 4/17):_ 9-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/59859911/92544002-d384f900-f21a-11ea-9043-6d8ad8604717.png)
![image](https://user-images.githubusercontent.com/59859911/92544025-e1d31500-f21a-11ea-90ea-0c4e23c048e5.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by silentreply** [comment]
I was concerned when I saw this and was unable to build a train station in a city where I just finished my railroad connection. However I was able to build it the next turn. So it's really just a minor quirk where it lists the seaport as a prerequisite.

**Comment by Mileslewis** [comment]
Think the red writing is meant to mean you can't have a seaport.
