### ISSUE TITLE
AI selling their owned cities

### ISSUE THREAD

**Issue by knml15** [LoneGazebo/Community-Patch-DLL#7046]
_1. Mod version (i.e Date - 4/17):_

9-2

_2. Mod list (if using Vox Populi only, leave blank):_

More Unique Components for VP (v60)
Additional Great People (v 1)
Calypso's Colored Religious Icons (Basic) (v 4)
Calypso's Colored Religious Icons (BNW Extended) (v 3)
Calypso's Colored Religious Icons (Extended) (v 5)
Ingame Editor (v 39)
More Great Works (v 3)
Polar Station 4VP (v 1.0)
Promotion Flags EUI for VP (v 3)
Quick Turns (v 10)
Reforestation (v 9)
TopPanel Replace (EUI Only) (v 4.4)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Show XP in Military Overview (v 2.3)
Unique City-States (v 6)
Unit Path Viewer (v 10)

_3. Error description:_ 

This is the turn before both Brazil and Siam sell their cities to Indonesia, they are not at war either.

![image](https://user-images.githubusercontent.com/67277925/92552176-9a886b00-f292-11ea-9e6f-8d998614d406.png)

Turn after sellling their cities.

![image](https://user-images.githubusercontent.com/67277925/92552009-2f3e9900-f292-11ea-80d4-71cca8ff72b0.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5192569/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): [QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5192535/QuickSave.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by knml15** [comment]
Still occurs after 9-8 hotfix.

**Comment by LoneGazebo** [comment]
Not  a bug.
