### ISSUE TITLE
9/2 - Can't create great work of writing

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7047]
_1. Mod version (i.e Date - 4/17):_ 9-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I don't have the option to create a great work with this writer. I tried moving to a different city. I don't think it's possible that they are all taken at this point..I was able to make one from a hidden antiquity site after earning this writer. 
![image](https://user-images.githubusercontent.com/59859911/92554400-45693c80-f233-11ea-99ec-abf069e823de.png)
![image](https://user-images.githubusercontent.com/59859911/92554423-5023d180-f233-11ea-9124-6684ba02bb95.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by GLop4** [comment]
More Great Writers (Great Work of Writing) are coming in few weeks. A team is on it recording quotes. It will solve the problem definitly.

**Comment by LoneGazebo** [comment]
If the writer has generic name, you're out.

**Comment by RecursiveVision** [comment]
@GLop4 Hey, if you've got a team recording quotes, you might want to also consider the quotes for the VP-added World Wonders. Just a thought...that would be pretty cool compared to the silence :)
