### ISSUE TITLE
CTD's late game

### ISSUE THREAD

**Issue by paramenides** [LoneGazebo/Community-Patch-DLL#7048]
_1. Mod version (i.e Date - 4/17):_
8/16 with hotfix

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

CTD in late game
_4. Steps to reproduce (optional):_

Here is the thing. They are NOT reproducible. If i load from an autosave, I can often continue for a few turns with no issue. Not sure if loading all the supporting files are really going to be helpful in this situation, so i won't unless requested.
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
probably out of memory. what mapsize are you playing at? maybe try reducing graphics settings.

**Comment by paramenides** [comment]
I will try and reduce graphic settings. Large map.

**Comment by azum4roll** [comment]
If it still fails after a while you'll have to stick to strategic view.
