### ISSUE TITLE
9/2 - AI hoarding prophets

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7049]
_1. Mod version (i.e Date - 4/17):_ 9-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
There may be some scenarios where a "prophet parade" is useful, but in this case Songhai has very strong passive pressure and converted nearly every city on his continent. Also at least two have been sitting in the capital for 30+ turns. Perhaps the AI needs a push in their decision making to plant them for holy sites?
![image](https://user-images.githubusercontent.com/59859911/92555681-359f2780-f236-11ea-960f-047970f423bf.png)
![image](https://user-images.githubusercontent.com/59859911/92555756-60897b80-f236-11ea-9fa4-b2ed824233cb.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
eh, sometimes I will hoard 2 prophets if my goal is to do a full conversion of a civ on another continent or something, so its not completely out of line.

**Comment by ilteroi** [comment]
this weird, how can you even get 5 prophets

**Comment by Stalker012345** [comment]
> this is weird, how can you even get 5 prophets ... post the homeland AI log, it should contain hints

Completely doable by this point in the game with very high faith output for a free GP somewhere.

**Comment by DelJon** [comment]
I had the AI continuously sent prophets to my lands in the latest version to convert my cities. Moderately disruptive.
