### ISSUE TITLE
Researching Future Tech does not add 1 happiness to capital

### ISSUE THREAD

**Issue by whatsdown44** [LoneGazebo/Community-Patch-DLL#7050]
_1. Mod version (i.e Date - 4/17):_

August 16th (8/16)

_2. Mod list (if using Vox Populi only, leave blank):_

with improved city view

_3. Error description:_ 

researching future tech does not add 1 happiness to the capital
researched it over 10 times and my happiness did not increase above 49
playing china

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
Happiness is capped at a city's population, is that what happened here?

**Comment by whatsdown44** [comment]
oh yeh that is it! I did not know this! Sorry!!
