### ISSUE TITLE
Restrictions on demanding from major civs

### ISSUE THREAD

**Issue by Skidizzle** [LoneGazebo/Community-Patch-DLL#7053]
9-8 beta Vox 43civ EUI

Error description:

I'm unable to demand gold without a declaration of friendship. I'm also unable to demand open borders without an embassy even though they have the relevant tech. Also, and this may be intentional, I cannot demand anything from a sanctioned civ. 

Should threatening demands have these restrictions?

**Comment by RecursiveVision** [comment]
Problem is demands use the same code as deals, just with one side of the deal table. Rewriting this would be a lot of work.

**Comment by Skidizzle** [comment]
I'm continuing this same game and just got sanctioned myself. I didn't realize that you couldn't demand under those circumstances either.

So much for a hypothetical North Korea playthrough :P

I'm guessing coding demands while under sanction to be one way falls under "too much work for the effort" as well?

**Comment by RecursiveVision** [comment]
You guess correctly. Plus, the community voted against it when I proposed it a while back.
