### ISSUE TITLE
Spy Leveling Missing Information Still Not Fixed

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#7054]
_1. Mod version (i.e Date - 4/17): 9/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:

 Issue #6736 is not fixed, either update the tooltip to state the fact that you can level up the spies by having them as diplomats in capital cities or remove their xp gain.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by silentreply** [comment]
I think there may be some other issues still going on with the espionage UI as reported in #6566 

On a side note, are you seeing your diplomats level up from intrigue in game? In my only game on 9-2 I started with my spy as a diplomat for about 30 turns and never got any intrigue. I gave up and moved him to steal tech.
