### ISSUE TITLE
9/2 - Trade route turns to complete not displayed

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7056]
_1. Mod version (i.e Date - 4/17):_ 9-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Is this not supposed to be visible to the player?
![image](https://user-images.githubusercontent.com/59859911/92828634-43bd8700-f3a1-11ea-9489-f2188523776d.png)

Also applies to the "available trade routes" page, which should definitely be visible. 
![image](https://user-images.githubusercontent.com/59859911/92846563-36f75e00-f3b6-11ea-8e86-4c5363ac3a33.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Works for me?
