### ISSUE TITLE
9/2 - Mystery corporate franchise established

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7058]
_1. Mod version (i.e Date - 4/17):_ 9-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Somehow my first franchise was established in Berlin, where I have no active trade routes to/from. This is an inland city and I am on a separate continent, so I can not trade with Berlin in the first place. I am sending a trade route to to coastal city of Cologne. I believe the franchise happened to be established on the same turn my diplomat "arrived," if that is significant. 

![image](https://user-images.githubusercontent.com/59859911/92836016-eda11180-f3a9-11ea-9b40-d650cf512e1e.png)
![image](https://user-images.githubusercontent.com/59859911/92836044-f5f94c80-f3a9-11ea-93c3-2f8fd80f57b8.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by silentreply** [comment]
Now another franchise was just established in Songhais capital, where I just moved a diplomat recently.
As a side note, this is nice buff to diplomats considering they don't appear to be uncovering intrigue at the moment! I'm not certain of that yet, but I will update if that changes. 

![image](https://user-images.githubusercontent.com/59859911/92837298-694f8e00-f3ab-11ea-90e5-1db1d19b196a.png)

**Comment by RecursiveVision** [comment]
Do you have the ideology tenet which gives a random chance of causing a franchise to appear?

**Comment by silentreply** [comment]
I don't have that policy. I think you're referring to transnationalism below?

![image](https://user-images.githubusercontent.com/59859911/92839299-c8160700-f3ad-11ea-9214-f2b5415308f3.png)

Just for clarification, is that a random chance to appear in any city, or to appear in cities with a trade route connection? I didn't think that franchises can appear at random, perhaps that is what's going on here.

**Comment by RecursiveVision** [comment]
Random chance to appear in any city - and yes, looks like that's what's going on.

**Comment by silentreply** [comment]
Ok thanks, just FYI I don't think it is mentioned that franchises have a chance to appear randomly in the civilopedia. I suppose it is only indirectly mentioned under the transnationalism policy.
