### ISSUE TITLE
9/2 - Mystery coal imported

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7059]
_1. Mod version (i.e Date - 4/17):_ 9-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I appear to have a mystery source of coal. I only have two in my territory which is correctly displayed. I am also receiving 7 from Kyzyl, however it shows that there is 56 "imported resources." The amount of coal I have also seems to be increasing, I think whenever Kyzyl flips allegiance back to me. I did originally give them gold to improve the resource which may be the source of the potential bug. 
![image](https://user-images.githubusercontent.com/59859911/92839685-42df2200-f3ae-11ea-829f-5e3b520fd9a6.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
It’s just a lua issue because of use of the wrong player variable for minor civ resources. I believe it is already fixed?

**Comment by silentreply** [comment]
Well I do appear to be receiving some of the incorrectly displayed 56. I am using 10 but should only have 9 (2 local + 7 from Kyzyl). When Kyzyl switches allegiance I do not lose that coal either.
