### ISSUE TITLE
Council of Elders not working as intended

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#7060]
_1. Mod version (i.e Date - 4/17): 9/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:

The description says that its scaling with the number of city following your religion but I meet the max 15 cities (above by a lot)  so I should get **450sp** (20 bonus yield * 15 cities * 1.5 epic game speed) but instead I get **127sp**.

I don't know why is like this, typo or bug but this is a very underwhelming bonus (playing standard, at this point even if i convert all the cities on the map i should get only 40 cities remaining including city-states * 127sp = **5000sp** and that's it with this belief for this game, doesn't even make for a full tech (modern era).

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/92944696-fdc5f900-f45c-11ea-9398-4922a35ff8c7.jpg)
![Civ5Screen0002](https://user-images.githubusercontent.com/49090452/92944706-00285300-f45d-11ea-8441-820438565432.jpg)
![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/92944704-fef72600-f45c-11ea-9126-68d955f764b5.jpg)

**Comment by RecursiveVision** [comment]
```
				case INSTANT_YIELD_TYPE_CONVERSION:
				{
					int iBaseValue = pReligion->m_Beliefs.GetYieldFromConversion(eYield, GetID(), pLoopCity, true);
					if (iBaseValue != 0)
					{
						int iTempValue = iBaseValue;
						iTempValue *= (100 + pReligion->m_Beliefs.GetCityScalerLimiter(iNumFollowerCities) * pReligion->m_Beliefs.GetCityScalerLimiter(iNumFollowerCities));
						iTempValue /= 100;

						iBaseValue += iTempValue;
					}

					iValue += iBaseValue;
					break;
				}
```

@Aqinu 

The code does this:

The base bonus is 20.

Multiply the base bonus by (100 + 15^2) = 325. 

20 * 325 = 6500.

Divide by 100 to get 65.

Add the base bonus (20) to 65 to get 85.

Multiply 85 by InstantYieldPercent for the current game speed to get 12,750.

Divide by 100 to get 127.

It's working as intended. Whether or not this is too weak is up for debate.

**Comment by Stalker012345** [comment]
I plugged the formula into excel, and this is what I got (assuming 100 is right for standard speed). The numbers are off in that the first city is supposed to 20, but its starting at 40...unless standard speed's Instant Yield Percent = 50?


0 | 40
1 | 40
2 | 40
3 | 41
4 | 43
5 | 45
6 | 47
7 | 49
8 | 52
9 | 56
10 | 60
11 | 64
12 | 68
13 | 73
14 | 79
15 | 85

**Comment by RecursiveVision** [comment]
@Stalker012345 You're right, I hadn't considered that. So THAT's why it was giving double the base bonus so long ago.

@LoneGazebo The code doubles the base bonus so you may want to adjust.
