### ISSUE TITLE
crash in deal AI

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7061]
```
		// Sort the vector based on value to get the best possible item to trade.
		viTradeValues.SortItems();
		if (viTradeValues.size() > 0)
		{
			for (int iRanking = 0; iRanking < viTradeValues.size(); iRanking++)
			{
				int iWeight = viTradeValues.GetWeight(iRanking);
				if (iWeight != 0)
				{
					eResource = (ResourceTypes)viTradeValues.GetElement(iRanking);
					if (eResource == NO_RESOURCE)
						continue;

					const CvResourceInfo* pkResourceInfo = GC.getResourceInfo(eResource);
					if (pkResourceInfo == NULL || pkResourceInfo->getResourceUsage() == RESOURCEUSAGE_LUXURY)
						continue;

					iResourceQuantity = viTradeQuantities.GetWeight(eResource);
```

the last line is the problem, viTradeQuantities is a vector, needs to be accessed by index. there are two instances of this error.

but honestly i'm suprised that it doesn't crash all the time because this should be called a lot? maybe something is wrong with the logic?

**Comment by LoneGazebo** [comment]
hmm, I've not seen that crash - since we're looking for the weight there, why would we need to get the indexed value?

**Comment by LoneGazebo** [comment]
keep in mind viTradeQuantities and viTradeValues are different arrays.

**Comment by ilteroi** [comment]
well they are updated in sync so the same index should work
```
				viTradeValues.push_back(eResource, iItemValue);
				viTradeQuantities.push_back(eResource, iResourceQuantity);
```

**Comment by LoneGazebo** [comment]
trade values is sorted, though

**Comment by ilteroi** [comment]
true, i missed that.

now after giving it a closer look i rewrote it completely because that's faster than talking.

seems firaxis had a pet monkey ...

**Comment by LoneGazebo** [comment]
@RecursiveVision broke a database item:

```
`ent:		6
------------------------------
[6807.453] columns Language, Tag are not unique
[6807.453] While executing - 'insert into Language_en_US('Tag', 'Text') values (?, ?);'
[6807.453] In XMLSerializer while inserting row into table insert into Language_en_US('Tag', 'Text') with  values (TXT_KEY_DIPLO_REQUEST_HELP_BUTTON, Request Help, ).
[6807.453] In XMLSerializer while updating table Language_en_US from file XML/Text/en_US/en_US_Text_UIC4DF.xml.
[6807.453] columns Language, Tag are not unique
[6809.484] Validating Foreign Key Constraints...
[6812.375] Invalid Reference on Resolutions.Help - "TXT_KEY_RESOLUTION_PLAYER_VASSAL_TAX_HELP" does not exist in Language_en_US
[6812.421] Invalid Reference on Resolutions.Description - "TXT_KEY_RESOLUTION_PLAYER_VASSAL_TAX" does not exist in Language_en_US
[6813.671] Failed Validation.
[6815.171] 
-- SQLite Memory Statistics --`
```

**Comment by LoneGazebo** [comment]
also don't insult that poor monkey, it's hard to find jobs these days.

**Comment by ilteroi** [comment]
is there an easy fix?

**Comment by RecursiveVision** [comment]
Huh? I made sure to remove the text key from en_US_Text_UIC4DF.xml when I put it in CoreText_en_US.xml. Are you sure your local files are updated?

_Of course it's THAT change that screws everything up. Just my luck._

Maybe it's because I didn't transfer the translations? I removed it so that my changes to the LUA files wouldn't be dependent on having the C4DF stuff installed, because I hate LUA and it simplified the code.

**Comment by RecursiveVision** [comment]
#7071

**Comment by ilteroi** [comment]
still broken in 9/8 with your fix on top

**Comment by RecursiveVision** [comment]
Really weird, this change worked for me when I tried it.

Okay, I'll look at this as soon as I can.

**Comment by RecursiveVision** [comment]
@ilteroi @LoneGazebo Make sure your (4) Civ IV Diplomatic Features local files are updated.

I built the DLL and copied all of the database files from master branch. Trade screen works fine.
![Screenshot (1102)](https://user-images.githubusercontent.com/66801010/93312737-8e8e3300-f7d5-11ea-97fe-1fa327aa7b15.png)

**Comment by RecursiveVision** [comment]
I did notice another bug, though, and I'll be fixing that.
