### ISSUE TITLE
Wierd Diplo modifier

### ISSUE THREAD

**Issue by Sekisetsu** [LoneGazebo/Community-Patch-DLL#7062]
_1. Mod version (i.e Date - 4/17):_  9/8

_2. Mod list (if using Vox Populi only, leave blank):_ VP + quick turns + Really Advanced Setup

_3. Error description:_  Some unusual high diplo modfier and why don't I get a negative one for different ideologies?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[William.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5212637/William.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![diplo modifier](https://user-images.githubusercontent.com/20355596/92995004-c65c5880-f4ff-11ea-9642-0685b4374170.jpg)

**Comment by RecursiveVision** [comment]
@Sekisetsu Sometimes the AI chooses to overlook ideological differences.

Hope I've got the coup modifier fixed...
