### ISSUE TITLE
cannot purchase great people

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7063]
this is lategame, assyria has 37k faith and apparently no way to spend it ...

![image](https://user-images.githubusercontent.com/1358966/92995469-4a184400-f504-11ea-9c07-18a8baf11eaf.png)

(don't know what happened to portugal, austria was eliminated)

![image](https://user-images.githubusercontent.com/1358966/92995451-1a693c00-f504-11ea-9821-9054431b5afe.png)

they have completed progress, fealty and rationalism ... so there should be plenty of options

**Comment by LoneGazebo** [comment]
Do they have a majority faith in any city?

**Comment by ilteroi** [comment]
no they don't. is that a comdition? doesn't say so in the description ...

**Comment by Stalker012345** [comment]
It is required yes. No religion = no ability to buy GP

**Comment by LoneGazebo** [comment]
@ilteroi yep, that's required. Always been that way.

**Comment by ilteroi** [comment]
but why oh why

**Comment by azum4roll** [comment]
I think it's more the problem of AIs not maintaining their religion. It's hard with the inquisitor nerf.

**Comment by Stalker012345** [comment]
Its not because inquisitors also reduce passive pressure I believe now too, I just find the AI doesn't build them.

**Comment by azum4roll** [comment]
Can you still use inquisitors on cities without a majority religion? If yes, maybe AIs are using them with no effect.

**Comment by ilteroi** [comment]
they did not found. so what is their religion?

we neee a late game faith sink. i don't see the point of this arbitrary restriction which isn't even mentioned anywhere.

**Comment by azum4roll** [comment]
It worked before when all AIs actively maintained their majority religion (via inquisitors of their existing majority if they did not found). So we just need to fix that.

**Comment by silentreply** [comment]
The city has to have a majority religion to be able to faith purchase, the player does not need a majority religion across the majority of their cities. I don't think the inquisitor change is having much impact on whether the AI uses them or not.

I don't see any reason why cities without majority shouldn't be able to faith purchase. A non-founder AI may often find themselves in this predicament if there are multiple religions pressuring but unable to establish a majority.

**Comment by LoneGazebo** [comment]
@ilteroi I agree re:restriction
