### ISSUE TITLE
No units can be upgraded to Fusilier?

### ISSUE THREAD

**Issue by Lillebo** [LoneGazebo/Community-Patch-DLL#7064]
_1. Mod version (i.e Date - 4/17):_
9-2

_2. Mod list (if using Vox Populi only, leave blank):_
N/A

_3. Error description:_ 
After researching Rifling I cannot upgrade any units to the new Fusilier? It seems neither Pikemen nor Longswordsmen can be upgraded any further? Is this by design? Do I really need to start deleting units and producing/buying new modern ones now? I though one should be able to continually upgrade old units to newer ones - and keep their promotions?

**Comment by RecursiveVision** [comment]
They upgrade to Tercios. Fusiliers are ranged units.

**Comment by Lillebo** [comment]
I cannot upgrade Minutemen to Fusiliers either 😕 And I see no Tercios in the tech tree? Which tech is supposed to give Tercios?

**Comment by RecursiveVision** [comment]
@Lillebo Do you have all DLC for Civ 5?

**Comment by Lillebo** [comment]
Crap, was actually missing several DLCs 🤦‍♂️ Thanks 👍
