### ISSUE TITLE
9/2 - Strange city CS/RCS behavior

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7065]
_1. Mod version (i.e Date - 4/17):_ 9/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When some units are garrisoned, they lower city CS/RCS. Alternatively, garrisoned naval units are incorrectly raising it.
![image](https://user-images.githubusercontent.com/59859911/93009344-cc792600-f54d-11ea-9ca7-c5e36f440e25.png)
![image](https://user-images.githubusercontent.com/59859911/93009349-dd299c00-f54d-11ea-803c-87f9104cb6dd.png)
![image](https://user-images.githubusercontent.com/59859911/93009371-401b3300-f54e-11ea-83c5-c6c80dfc0721.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Already reported. It's the ships. See #6980
