### ISSUE TITLE
9/2 - Can't establish trade route shown in available routes tab

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7066]
_1. Mod version (i.e Date - 4/17):_ 9/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I want to send a trade route to Dublin but am not able to establish this route. Also tried from another city where it was "available" but could not make the route. We are friends and there is no enemy territory in between. 
![image](https://user-images.githubusercontent.com/59859911/93042864-36f99700-f61e-11ea-8d54-cb7409853b9e.png)
![image](https://user-images.githubusercontent.com/59859911/93042884-4082ff00-f61e-11ea-96af-f36e37bf9eeb.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Do you have another city that has a current trade route with Dublin?

**Comment by silentreply** [comment]
Yes I did. Forgot about that rule!
