### ISSUE TITLE
9/2 - Boarded status effect (occasionally) not being applied to naval units

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7067]
_1. Mod version (i.e Date - 4/17):_ 9/2

_2. Mod list (if using Vox Populi only, leave blank):_
Promotion flags v3
Enhanced city view v11

_3. Error description:_ 
I'm seeing this come up again as reported in #6445. I don't see why it would be specific to my install. Can anyone reproduce? Logs and save attached below.

The unit received the text indication for boarded, but not the status icon. It had full movement the next turn as well. 
![image](https://user-images.githubusercontent.com/59859911/93075893-77740780-f654-11ea-8e5c-7ff5047d6985.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5217921/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[AutoSave_0147 AD-0740.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5217923/AutoSave_0147.AD-0740.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
remember that units can become immune to it

**Comment by silentreply** [comment]
@LoneGazebo In this example it is my unit (Songhai, not immune) that should have received the boarded effect after attacking the French trireme. I've seen it happen both ways in prior versions.

**Comment by LoneGazebo** [comment]
Not sure - the chance is 100%, I'd need a save with the event to see it.

**Comment by silentreply** [comment]
@LoneGazebo It's attached at the bottom under the "supporting information"
