### ISSUE TITLE
9/2 - "Accept embassy" tradeable in deal screen when already established

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7069]
_1. Mod version (i.e Date - 4/17):_ 9/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I've been seeing this very frequently. 
![image](https://user-images.githubusercontent.com/59859911/93091728-7d75e280-f66c-11ea-94b9-fc38099cf4e5.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by JamesNinelives** [comment]
I'm seeing the same thing. I assume it's related to recurring deals where you included the Embassy in the original and then they try to trade it to you again when the deal expires.

**Comment by LoneGazebo** [comment]
Did they approach you with the embassy offer?

**Comment by silentreply** [comment]
@LoneGazebo No they did not approach with it. I just forget that I have it sometimes and keep trading for it again :)

**Comment by LoneGazebo** [comment]
lol
