### ISSUE TITLE
aesthetics finisher

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#707]
says that it doubles theming bonuses but doesn't appear to
also the "+8 museum of mayan art" tooltip on the culture screen is likewise deprecated

**Comment by Edaka** [comment]
Just curious, have you checked if the French double theming in capital works? That might be causing a trouble, too.

**Comment by LoneGazebo** [comment]
To be clear the only bonuses that double are the tourism ones.
