### ISSUE TITLE
Captured Units don't keep Promotions/Experience

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7075]
When you capture a unit (Huns UU, Sea Beggars etc) or gain another unit for example from buying a city state as Venice they lose all their promotions/experience.

Could be intentional that it's like this but I think it would be pretty cool if you keep the promotions since it is still technically the same unit.

**Comment by RecursiveVision** [comment]
Could be way too powerful otherwise.

**Comment by azum4roll** [comment]
I think Venice units should have the base experience from the CS buildings. And the bought CS should retain all its buildings and population as well, if it doesn't already work that way.

**Comment by Mileslewis** [comment]
> Could be way too powerful otherwise.

Don't necessarily agree, right now captured units just end up being used as meatshields for your proper troops.

**Comment by RecursiveVision** [comment]
Hmm, perhaps. But it's intentional nonetheless. I'll let G speak about any balance-related reasons.

Personally I'm not opposed to letting Venice CS units keep promotions/experience - and I'd be in favor of having units gifted to City-States keep them as well.

**Comment by azum4roll** [comment]
Units gifted to CS do keep the promotions if they travel there manually.
