### ISSUE TITLE
LUA Runtime Error Breaks Discuss Menu

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7077]
I'm having difficulty diagnosing an LUA error:
```
[191267.953] Runtime Error: C:\Users\[User]\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Community Balance Overhaul - Compatibility Files (EUI)\LUA\DiscussionDialog.lua:1493: attempt to call method 'CanRequestCoopWar' (a nil value)
```

So here's the call:
```
----------------------------------------------------------------
----------------------------------------------------------------
function IsWarAgainstThirdPartyPlayerValid(iThirdPartyPlayer)
	
	if (not IsThirdPartyPlayerValid(iThirdPartyPlayer)) then
		return false;
	end
	
	local pActivePlayer = Players[Game.GetActivePlayer()];

	if (not pActivePlayer:CanRequestCoopWar(g_iAIPlayer, iThirdPartyPlayer)) then
		return false;
	end
	
	return true;
end
```

And here's the equivalent in CvLuaPlayer.cpp:
```
//------------------------------------------------------------------------------
int CvLuaPlayer::lCanRequestCoopWar(lua_State* L)
{
	CvPlayerAI* pkPlayer = GetInstance(L);
	PlayerTypes eAllyPlayer = (PlayerTypes) lua_tointeger(L, 2);
	PlayerTypes eTargetPlayer = (PlayerTypes) lua_tointeger(L, 3);

	const bool bValue = pkPlayer->GetDiplomacyAI()->CanRequestCoopWar(eAllyPlayer, eTargetPlayer);

	lua_pushinteger(L, bValue);
	return 1;
}
```

And I also added this line in CvLuaPlayer.h:
```
	static int lCanRequestCoopWar(lua_State* L);
```

This runtime error is preventing any of the Discuss buttons from appearing.

Any ideas what I'm doing wrong here? I copied GetCoopWarAcceptedState exactly when creating this and I can't find the problem.

**Comment by RecursiveVision** [comment]
![Screenshot (1104)](https://user-images.githubusercontent.com/66801010/93327755-ca7ec380-f7e8-11ea-8131-a9fedbedb148.png)

**Comment by RecursiveVision** [comment]
@ilteroi @LoneGazebo

**Comment by RecursiveVision** [comment]
Okay, I cleared my cache and ModUserData files. Now I'm still getting the runtime error, but the button is simply blacked out, instead of blocking all Discuss buttons or generating the insanity above.

**Comment by RecursiveVision** [comment]
Tried adding isMajorCiv and IsPlayerValid checks in case invalid players were sneaking in...no dice.

Been at this all morning with no luck. Grrrr.

**Comment by LoneGazebo** [comment]
Did you add the CanRequestCoopWar new lua statement twice in the luaplayer.cpp file?

**Comment by LoneGazebo** [comment]
There's a second spot in that lua file that requires it - find the nearest 'good' lua call and model yours on that with regards to location.

**Comment by RecursiveVision** [comment]
Ah, that's probably it! Will check.

**Comment by RecursiveVision** [comment]
Fixed! Thank you!

**Comment by LoneGazebo** [comment]
isn't it maddening when one tiny thing is causing such a headache?

**Comment by RecursiveVision** [comment]
It was driving me nuts all morning, trying to figure out why it wasn't working. Wanted to tear my hair out.

It's still not working the way I want it to, but at least now I have an idea of how to fix the other issues. SMH

**Comment by RecursiveVision** [comment]
I'd better learn how to use the debugger, cause I'm going to need it for this...

**Comment by LoneGazebo** [comment]
keep in mind that LUA reloads on a savegame, so you can save hours of debugging (if you're editing lua) just overwriting the lua file in the MODS folder with your changes and then reloading a save.

**Comment by LoneGazebo** [comment]
can't with the DLL of course, but you can with lua.

**Comment by RecursiveVision** [comment]
Good to know, thanks!

There's issues with my new coop war code on the DLL side, however...but at least it isn't crashing or breaking menus. :)

**Comment by LoneGazebo** [comment]
yeah you'll need the debugger for that - it's not too tricky, just attach the debugger to the civ 5.exe process while running, make a breakpoint in your new function, and you're good to go!

**Comment by RecursiveVision** [comment]
Well, I know what I'll be doing later today then :) 

Gonna take a break first, though, this has given me a headache. Some ice cream may help!
