### ISSUE TITLE
Alhambra gives drill I again

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#7078]
_1. Mod version (i.e Date - 4/17): 9-02 hotfix

_3. Error description:_ with the switch to global jinete, the edit that removes the old drill I promotion from vanilla is no longer overwriting it. So, Alhambra gives Jinete globally and drill locally.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by pineappledan** [comment]
This fix has somehow broken everything downstream of Alhambra in the sql. Check out where everything’s tech placements went:
![image](https://user-images.githubusercontent.com/33136027/94441870-8385bc00-0160-11eb-8909-b193bb85bab4.png)
I don’t think you can just NULL that column. Maybe you can try DELETE FROM, or maybe just set the free promotion as PROMOTION_ALHAMBRA, so it is the same as the global promotion

**Comment by RecursiveVision** [comment]
The default for that column *is* NULL.

**Comment by LoneGazebo** [comment]
you can, NULL is fine just don't put it in quotes. I use it elsewhere in the SQL.

**Comment by LoneGazebo** [comment]
The issue is 'WHERE BuildingType = 'BUILDING_ALHAMBRA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1 );

Needs to be Type, not BuildingType

**Comment by LoneGazebo** [comment]
BuildingType is only used for the ancillary mod columns

**Comment by RecursiveVision** [comment]
Oops, will keep in mind for the future. :)
