### ISSUE TITLE
Problem with Steam library not in C:

### ISSUE THREAD

**Issue by tukkek** [LoneGazebo/Community-Patch-DLL#7079]
Hello I have run into problems with the latest automatic installer (missing textures/could not load...). The installer had put the `DLC/assets` folder on my C: drive, where I have no games installed. Moving that folder to the proper install location inside my Steam library seemed to resolve the issue.

I have not yet been able to actually play the game but at least I can launch and start a new game successfully. If anything else comes up I will report it.

Thank you for keeping Civ V alive well into 2020 and beyond! I have just bought the remaining DLC in expectation of enjoying the Vox Populi experience. Big thanks to everyone involved!

**Comment by LoneGazebo** [comment]
This happens if the registry is not aligned with your civ install location.

**Comment by tukkek** [comment]
OK but I haven't changed my registry at all, it's a fresh install all-around (including Windows itself, which I seldom use). Shouldn't the installer maybe prompt for the install location rather than fail by definition just because it's a non-default install path?

**Comment by Vyyt02** [comment]
I am a bit confused. I often advise people on this issue in the install thread on CivFanatics. I used to think the problem ALWAYS occured when your Steam installation was not on C: Then someone corrected me that it was happening when registry was not aligned with the Civ install location - as you say now @Gazebo.

How can this happen if you have fresh install though? Like @tukkek , I never reinstalled / moved Civ5 on my old computer and yet it was happening.

Either way, what are our options to make it easier for new players? Not everyone is brave enough to ask for help. If a prompt to specify the Steam location in the autoinstaller is not possible, can we at least display some text warning? Or, in the worst case, add the into to the install page on CF? I can write the text if you want (you may have to proofread it, haha).

**Comment by tukkek** [comment]
> add the into to the install page on CF?

I would recommend also the wiki, as that was the first place I looked at for troubleshooting info.

**Comment by tukkek** [comment]
Was this issue fixed?

**Comment by LoneGazebo** [comment]
Not fixable with our current installer method
