### ISSUE TITLE
AI use of trade routes

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#708]
I rarely ever see the AI sending me trade routes
Are they just having a party without me or are they using internal trade routes extensively?

**Comment by LoneGazebo** [comment]
probably both?

**Comment by Hokath** [comment]
nobody loves me :(
The reason I ask is because quite a while after corporations were founded (i was last), they haven't spread a great deal. See picture, information era:
![2015-10-18_00001](https://cloud.githubusercontent.com/assets/11889219/10563455/8f969f74-7582-11e5-9c5d-9577a23071c6.jpg)

 I notice when AI does send me trade routes it tends to be to my 'worst' cities, like ones I have just captured. Do they care a lot about the delta?

**Comment by LoneGazebo** [comment]
They care much about delta yes.

**Comment by Radost** [comment]
So, it defeats the point of all "+ gold for incoming trade routes" on a city.
The trading hub will never trade.

**Comment by LoneGazebo** [comment]
Sometimes. The AI cares a lot less about delta values it if likes you.

G

**Comment by Radost** [comment]
Looks like it's other way around. In my hugbox games I end up with next to zero incoming trade routes, while in my current 100% warmonger I get this:
![8930_2015-10-19_00005](https://cloud.githubusercontent.com/assets/1131228/10571232/a0d8e498-7656-11e5-8c17-801710b852c7.png)
Notice how Korea has a TR right into my capital, even though it hates my guts.

**Comment by LoneGazebo** [comment]
There are a lot of elements in the scoring aside from friendship. Here's the code:

#if defined(MOD_BALANCE_CORE_DEALS_ADVANCED)
	//If we are friends with the player, let's not care about how much gold they make.
	if(m_pPlayer->GetDiplomacyAI()->GetMajorCivApproach(kTradeConnection.m_eDestOwner, false) == MAJOR_CIV_APPROACH_FRIENDLY)
	{
		iTechDifferenceP2fromP1 /= 2;
	}
	else if(m_pPlayer->GetDiplomacyAI()->GetMajorCivOpinion(kTradeConnection.m_eDestOwner) >= MAJOR_CIV_OPINION_FAVORABLE)
	{
		iTechDifferenceP2fromP1 /= 2;
	}
#endif

G

**Comment by Hokath** [comment]
this function seems personally reasonable.
I think from my screenshot of the franchises we can see that the issue (if there is one - and I think there is if the AI is not using corporations, which are very strong) is internal vs external

**Comment by LoneGazebo** [comment]
The AI understands franchises and corporations quite well, but they prioritize other things too. Internal productivity is really important to the AI.

G
