### ISSUE TITLE
9-2: Great Lighthouse benefit not seen after reload

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#7080]
_1. Mod version (i.e Date - 4/17):_
9-2

_2. Mod list (if using Vox Populi only, leave blank):_
VP (all of it)
Pontoon Bridges for VP
Enhanced Naval Warfare for VP

_3. Error description:_ 
I noticed a few things on a recent play-through. I'll address each one separately.
- I have the Great Lighthouse wonder, so each of my naval units are supposed to get +1 movement. Yet, when I load a game from a save file, my naval units do not get the stated benefit for a few turns. Is there a trick to getting this benefit consistently?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by briantjack** [comment]
On reload of an earlier save -- from which I recalled having +1 movement for my naval units -- I realized I had not yet acquired the Great Lighthouse (through city capture). What other source or effect provides this benefit? (By the way, I never acquired the opener for Imperialism.)

**Comment by briantjack** [comment]
I identified the other source: having a strategic monopoly of Coal grants naval units with +1 movement. After reloading the game and then advancing to the next turn (on researching another issue), I noticed that my naval units still have their standard movement speed -- despite controlling 90% of the world's coal supply. Is there a way to trick the game into turning this switch on?

**Comment by LoneGazebo** [comment]
@ilteroi any idea why the kStream for m_pabHasGlobalMonopoly and m_pabHasStrategicMonopoly wouldn't persist on gameload?

**Comment by briantjack** [comment]
While investigating another issue, I also did not see the strategic monopoly benefit for oil on loading a new game. Even advancing to the next turn did not gain me the "+2 XP after combat" benefit for any unit. (So, the problem is not specific to coal.)

**Comment by ilteroi** [comment]
it seems this piece of code here is to blame
```
		if (MOD_BALANCE_CORE_RESOURCE_MONOPOLIES && m_pabHasGlobalMonopoly[iResourceLoop])
		{
			SetHasGlobalMonopoly((ResourceTypes)iResourceLoop, true);
		}
		if (MOD_BALANCE_CORE_RESOURCE_MONOPOLIES_STRATEGIC && m_pabHasStrategicMonopoly[iResourceLoop])
		{
			SetHasStrategicMonopoly((ResourceTypes)iResourceLoop, true);
		}
```

you should deserialize to a temporary vector, then call SetHasMonopoly. otherwise it's a no-op.

**Comment by RecursiveVision** [comment]
@LoneGazebo

**Comment by LoneGazebo** [comment]
Really we don't even need to serialize those values, as we can just generate that data on load.

**Comment by ilteroi** [comment]
which values?

anyway i'm concerned there might be other instances of this bug elsewhere.

**Comment by RecursiveVision** [comment]
I reiterate that I'd be greatly in favor of simplifying and improving memory management across the entire project. :)

**Comment by LoneGazebo** [comment]
@ilteroi since we know resource totals for players already, we can just run the 'checkformonopoly' code for all resources for each player on load. That would correctly set the m_aResourceMonopoly and m_aStrategic values.

**Comment by Skidizzle** [comment]
version 9-8 

Can confirm the strategic monopoly on coal for naval movement is also lost on reload
