### ISSUE TITLE
9-2: Strategic monopoly of oil benefit not seen consistently

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#7081]
_1. Mod version (i.e Date - 4/17):_
9-2

_2. Mod list (if using Vox Populi only, leave blank):_
VP (all of it)
Pontoon Bridges for VP
ENW for VP

_3. Error description:_ 
- My units are not consistently seeing the benefit of the strategic monopoly benefit for oil -- i.e., +2 XP after combat. For example, when working properly, melee attacks normally award +5 XP, but with the benefit the unit should see +7 XP; when defending against a ranged attack, the unit normally sees an award of +2 XP, but with the benefit the unit should see +4 XP. On the last turn, units were not benefitting on attacks but were benefitting while on defense. Was this change intentional?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
same as #7080 i assume
