### ISSUE TITLE
9-2: When do fishing boats get 3 movement instead of 2 movement?

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#7082]
_1. Mod version (i.e Date - 4/17):_
9-2

_2. Mod list (if using Vox Populi only, leave blank):_
VP (all of it)
Pontoon Bridge for VP
ENW for VP

_3. Error description:_ 
- In the mid- to late-game, some fishing boats have 2 movement while others have 3 movement. Why the difference?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by briantjack** [comment]
After reloading earlier saves, I went through each of my cities and either bought a Fishing Boat or inserted it at the top of the construction queue. Out of three attempts, two such reloads produced no difference, as all boats started the subsequent turn with 2/2 movement; the second attempt saw bought Fishing Boats starting the subsequent turn with 2/3 movement while constructed boats starting with 3/3 movement. On continuing with the second attempt, I mixed it up again only to see all boats starting the subsequent turn with 3/3 movement. It was as though the reload didn't flip the appropriate "switch", only for the cycling to the next turn to, on a chance, flip the switch "on" for the extra movement.

**Comment by LoneGazebo** [comment]
only possibility would be a missing memory value for the extra movement from naval - @RecursiveVision if you get a chance today could you take a look?

**Comment by RecursiveVision** [comment]
@LoneGazebo 
```
//	---------------------------------------------------------------------------
// Get the base movement points for the unit.
int CvUnit::baseMoves(bool bPretendEmbarked) const
{
	VALIDATE_OBJECT
	CvTeam& thisTeam = GET_TEAM(getTeam());
	CvPlayer& thisPlayer = GET_PLAYER(getOwner());
	CvPlayerTraits* pTraits = thisPlayer.GetPlayerTraits();
	DomainTypes eDomain = getDomainType();

	//hover units don't embark but movement speed may change!
	if(bPretendEmbarked)
	{
		CvPlayerPolicies* pPolicies = thisPlayer.GetPlayerPolicies();
		return max(1, GC.getEMBARKED_UNIT_MOVEMENT() + getExtraNavalMoves() + thisTeam.getEmbarkedExtraMoves() + thisTeam.getExtraMoves(eDomain) + pTraits->GetExtraEmbarkMoves() + pPolicies->GetNumericModifier(POLICYMOD_EMBARKED_EXTRA_MOVES));
	}

	int m_iExtraNavalMoves = 0;
	if(eDomain == DOMAIN_SEA)
	{
		m_iExtraNavalMoves += getExtraNavalMoves();
#if defined(MOD_BALANCE_CORE_RESOURCE_MONOPOLIES)
		if(MOD_BALANCE_CORE_RESOURCE_MONOPOLIES)
		{
			const std::vector<ResourceTypes>& vStrategicMonopolies = GET_PLAYER(getOwner()).GetStrategicMonopolies();
			for (size_t iResourceLoop = 0; iResourceLoop < vStrategicMonopolies.size(); iResourceLoop++)
			{
				ResourceTypes eResourceLoop = vStrategicMonopolies[iResourceLoop];
				CvResourceInfo* pInfo = GC.getResourceInfo(eResourceLoop);
				if (pInfo && pInfo->getMonopolyMovementBonus() > 0)
				{
					m_iExtraNavalMoves += pInfo->getMonopolyMovementBonus();
				}
			}
		}
#endif
		// Work boats also get extra moves, and they don't have a combat class to receive a promotion from
		if(m_iBaseCombat == 0)
		{
			m_iExtraNavalMoves += pTraits->GetExtraEmbarkMoves();
		}
	}

	int iExtraGoldenAgeMoves = 0;
	if(thisPlayer.isGoldenAge())
	{
		iExtraGoldenAgeMoves = pTraits->GetGoldenAgeMoveChange();
	}

#if defined(MOD_BALANCE_CORE_POLICIES)
	if(!IsCombatUnit() && !IsGreatGeneral() && !IsGreatAdmiral())
	{
		iExtraGoldenAgeMoves += GET_PLAYER(getOwner()).GetExtraMoves();
	}
#endif

	int iExtraUnitCombatTypeMoves = pTraits->GetMovesChangeUnitCombat((UnitCombatTypes)(m_pUnitInfo->GetUnitCombatType()));

#if defined(MOD_BALANCE_CORE)
	iExtraUnitCombatTypeMoves += pTraits->GetMovesChangeUnitClass((UnitClassTypes)(m_pUnitInfo->GetUnitClassType()));
#endif

	return max(1, (m_pUnitInfo->GetMoves() + getExtraMoves() + thisTeam.getExtraMoves(eDomain) + m_iExtraNavalMoves + iExtraGoldenAgeMoves + iExtraUnitCombatTypeMoves));
}
```

Fishing boats get the monopoly movement bonus and "extra embark moves". My guess is that it has to do with the monopoly bonus not serializing properly. Either that or it's not receiving a bonus that normal naval units are in the code above.

**Comment by RecursiveVision** [comment]
@briantjack Did you experience this issue in the same game as the monopoly issue?

**Comment by briantjack** [comment]
> @briantjack Did you experience this issue in the same game as the monopoly issue?

All of the "9-2:" posts (from 2 days ago) were experienced within the same game.

**Comment by RecursiveVision** [comment]
@LoneGazebo I suspect that if you solve the monopoly issue, you'll solve this issue as well.

**Comment by pineappledan** [comment]
Can you confirm this is not related to the +1 movement from the Progress policy? 

Does Briantjack even have the correct monopoly, or the correct policy branch?

**Comment by briantjack** [comment]
> Can you confirm this is not related to the +1 movement from the Progress policy?
> 
> Does Briantjack even have the correct monopoly, or the correct policy branch?

I did not have any policies within the Progress branch selected. No descriptions for policies I did have hinted at +1 movement for boats. Yet, I think I did have a global monopoly on Coal.

**Comment by RecursiveVision** [comment]
@pineappledan OP mentioned having a global monopoly on coal in the same game in another issue, and there's an already established issue about that not loading properly, so I suspect they're related - but good point, glad to have that ruled out.
