### ISSUE TITLE
9-2: 

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#7083]
_1. Mod version (i.e Date - 4/17):_
9-2

_2. Mod list (if using Vox Populi only, leave blank):_
VP (all of it)
Pontoon Bridges for VP
ENW for VP

_3. Error description:_ 
- I have the ISS wonder in my capital, and I then discover a new technology, I appear to receive the "+200 production per era" benefit twice. Is this intentional?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Probably from another wonder or policy.
