### ISSUE TITLE
Deal AI observations

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7085]
in TooMuchAdded() is says:

```
	//still not good enough, but trending in the right direction? Carry on.
	return bFromUs ? (iTotalValue <= 0) : (iTotalValue >= 0);
```

shouldn't this be

```
	return bFromUs ? (iItemValue<= 0) : (iItemValue>= 0);
```

?

**Comment by ilteroi** [comment]
also, i'm seeing interesting deal offers where the AI offers their sole instance of a given luxury but values it very highly:

![image](https://user-images.githubusercontent.com/1358966/93568409-6ac31c80-f990-11ea-92eb-d8041e33db92.png)

(i removed the 13 horse they wanted from me in return)

**Comment by ilteroi** [comment]
and another one, i got one offer (luxury+gold+gpt) against (strategics+gpt), which could be equalized in a simpler way as luxury against gpt).

**Comment by LoneGazebo** [comment]
Might be knock on effects of your changes to the resource code. I’ll check!

**Comment by ilteroi** [comment]
pacal just tried to sell me two if his iron ... but i already have 24.

it seems that CvDealAI::GetResourceRatio() is broken.

**Comment by LoneGazebo** [comment]
Was the price off? The AI will try to sell strategics even if you don't need them...pads the deal value.

**Comment by ilteroi** [comment]
they value their iron higher the more i already have

**Comment by ilteroi** [comment]
also offered me this deal but wouldn't accept it

![image](https://user-images.githubusercontent.com/1358966/94060857-e4ba3200-fde4-11ea-9bcb-c46f867ccc2a.png)
