### ISSUE TITLE
Weak Carrier Defence Agains Range Units

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#7087]
_1. Mod version (i.e Date - 4/17): 9-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

It seems that Carrier strength is calculated differently for range units, for all other units if they have the same strength value (ex. melee vs melee) the both do to one another 30 damage, but for Carrier is different when attacking with range units (land or sea). 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**This is the normal damage if both of them have the same strength (for melee units works correctly, 30 damage)**
![Civ5Screen0009~1](https://user-images.githubusercontent.com/49090452/93613377-771f9780-f9d9-11ea-92b0-b05f375b649a.jpg)

**Here when attacking with range unit (should be 30 damage not 50, for range units is not working correctly)**
![A2](https://user-images.githubusercontent.com/49090452/93613355-6f5ff300-f9d9-11ea-9797-b40c701ad4fc.jpg)

**For land range units, the same, is wrong as in the second screenshot (the damage should be much lower, between 20-25)**
![Civ5Screen0010](https://user-images.githubusercontent.com/49090452/93613503-a0402800-f9d9-11ea-857c-f0ab1ca85fe1.jpg)

**Comment by LoneGazebo** [comment]
Intended, ranged damage always resolves against ranged damage if the unit is ranged. Carriers are weak to ranged.

**Comment by Aqinu** [comment]
Then it should show the correct strength for range not for melee.

**Comment by Stalker012345** [comment]
Yeah it looks like the damage is right, but the strength shown in the Combat Screen is incorrect.

**Comment by Stalker012345** [comment]
Actually there is another issue shown in that third screenshot. The rocket artillery strength is too low. Its getting a +15% CS bonus, but its effective CS is actually lower than its base.

**Comment by Aqinu** [comment]
Yeah, that's why #7088 exists...
