### ISSUE TITLE
Specialist getting stuck in a destroyed building after flooding

### ISSUE THREAD

**Issue by a3kov** [LoneGazebo/Community-Patch-DLL#7090]
_1. Mod version (i.e Date - 4/17):_
9-2

_2. Mod list (if using Vox Populi only, leave blank):_
Promotion icons for VP

_3. Error description:_ 
I got a flood event, and the city library got destroyed. It was working it's specialist, and it seems the specialist is now stuck in the destroyed building: the city is producing urbanization with 0 specialists, and number of available citizens for working tiles is 1 less than it should be.

![Screenshot_20200919_183635](https://user-images.githubusercontent.com/813860/93665180-11014600-faa7-11ea-8b98-051f88b80ea7.png)

**Comment by phantommaxwell** [comment]
What happens when you rebuild the Library?
