### ISSUE TITLE
(Feature Request) MAXIMUM_ACQUIRE_PLOT_DISTANCE not being used?

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7091]
In base game this variable determined the maximum distance a city's borders could grow which is 5 tiles by default. Seems like this is no longer being used in VP code as when I tried to change it with VP on in game the max range stayed at 5. Would be nice to have the option of changing this.

The reason I was even bothering with this is that it's quite sad that once you have run out of tiles for a city to grow to you stop getting the bonus yields from border growth which can actually happen quite early in the game so I wanted to prolong it at least. 

Allowing the bonus yields to still be received each time you hit the border growth threshhold even once there are no more tiles would also solve this but I'm guessing not everyone would want this.

**Comment by HungryForFood** [comment]
Seems that changing the following in line 7198 of CvGlobals.h:

`	inline int getMAXIMUM_ACQUIRE_PLOT_DISTANCE()
	{
		return std::min(m_iMAXIMUM_ACQUIRE_PLOT_DISTANCE, MAX_CITY_RADIUS);
	}`

To this:

`	inline int getMAXIMUM_ACQUIRE_PLOT_DISTANCE()
	{
		return m_iMAXIMUM_ACQUIRE_PLOT_DISTANCE;
	}`

Would allow higher MAXIMUM_ACQUIRE_PLOT_DISTANCE values. However, this chunk of code seems to be written by whoward quite early on as part of his DLL, so I'm not sure if it is a good idea to change it.

**Comment by Mileslewis** [comment]
Ahh thanks, well maybe ill try it and see if my comp explodes
