### ISSUE TITLE
AI very reluctant on pillaging enemy citadels

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#7094]
_1. Mod version (i.e Date - 4/17):_
8-23, one of the many hotfixes

_2. Mod list (if using Vox Populi only, leave blank):_
Nothing that changes the AI or citadels, I'm sure

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/14953746/93713487-e5598b00-fb8e-11ea-8ac1-a35748a7bb94.png)
The Zulu knight just stayed on the citadel tile the whole time without pillaging or moving off it, until it died the turn after this.

![image](https://user-images.githubusercontent.com/14953746/93713748-86951100-fb90-11ea-84ad-856c4ab905b2.png)
Earlier when invading America on the mainland the Zulu army ignored the citadel as well, for more than 20 turns.

_4. Steps to reproduce (optional):_
Observe the AI wars. It happens pretty commonly.

**Comment by azum4roll** [comment]
Maybe they're thinking they can benefit from the defense bonus from the citadel?

**Comment by ilteroi** [comment]
i think i know why

**Comment by Stalker012345** [comment]
just noting I have seen this behavior several times myself.
