### ISSUE TITLE
Guerrilla Warfare incorrect Experience for Ranged Units 

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7097]
Guerrilla Warfare: +15% attack bonus and +50% Experience for Military Units in friendly territory. Can build Guerrilla Fighters.

Seems like ranged units get bonus experience when attacking OUTSIDE friendly territory instead of inside. Everything else seems to work fine.

**Comment by RecursiveVision** [comment]
@Mileslewis Does the target being in friendly or non-friendly territory make a difference?

**Comment by Mileslewis** [comment]
You mean vassal/city state?

**Comment by Mileslewis** [comment]
Just wondering would it be possible to make it give the bonus if your unit is standing in friendly territory rather than attacking into friendly territory? Would make it much less awkward to try and get the bonus for ranged units.
