### ISSUE TITLE
Incorrect triggering of "plotting against them" diplo penalty

### ISSUE THREAD

**Issue by subhchatu** [LoneGazebo/Community-Patch-DLL#7099]
_1. Mod version (i.e Date - 4/17):_

9-8 latest hotfix
_2. Mod list (if using Vox Populi only, leave blank):_

  Civ names by policy
  Diplomacy responses extended
  Enhanced air Warfare 4VP
  Enlightenment era(vp)
  Info Addict
  Quick Turns
  RED Modpack
  Toppanel replace
  Unique Citystates
  Vox Populi's Bare Necessities 

_3. Error description:_ 

 [(https://forums.civfanatics.com/threads/diplomacy-ai-development.655040/page-35#post-15914244) ]
Screengrab^
after liberating Siam, suddenly he broke our DoF and now there is a diplo penalty saying "I was caught plotting against them". But i didnt do anything of the nature.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Think this is already fixed. Let me know if it recurs in the next version.

**Comment by subhchatu** [comment]
k cool
