### ISSUE TITLE
Ranged barbarians in camps bombard and heal on the same turn

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#710]
This one is back again. So far I've seen barbarian archers and hand-axes reliably heal after attacking, all on the same turn.

**Comment by TechpriestEnginseer** [comment]
Can confirm.

**Comment by ilteroi** [comment]
i'll keep an eye on it ... but it's quite impossible, the code says:

if( ( !pUnit->hasMoved() && pUnit->IsHurt() ) && (pLoopPlot->getImprovementType() == eCamp) )
[...]

so unless there's another place where barbarians heal, i don't know how this could happen. no heal if the unit has lost movement points (ie moved or attacked)

**Comment by Mitchsp** [comment]
Still happening with 10/23 version.

**Comment by LoneGazebo** [comment]
You sure they aren't getting promotions or something?

**Comment by Mitchsp** [comment]
Isn't the case for me at least. Observing this, can state that happens always a unit end the turn in a camp, being a unit stationed even if attacks, or moving from away to the camp.

**Comment by Edaka** [comment]
I thought barbarians couldn't receive promotions, isn't it right? I haven't had a chance to playtest lately, so can't provide any useful input at the moment, unfortunately.
