### ISSUE TITLE
when declare war the game crash

### ISSUE THREAD

**Issue by Alexanzero** [LoneGazebo/Community-Patch-DLL#7100]
_1. Mod version (i.e Date - 4/17):_ 6/19

_2. Mod list (if using Vox Populi only, leave blank):_ i only use vox populi Community Patch(not Community Balance Overhaul)

_3. Error description:_ when declare war the game crash

_4. Steps to reproduce (optional):_ declare war any leader

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencin
[Bug_declare_war.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5261631/Bug_declare_war.zip)
g a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
[Bug_declare_war.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5261634/Bug_declare_war.zip)

**Comment by bsesar** [comment]
@Alexanzero I had crashes like that due to animations of leaders. Have you tried setting leader animations to minimal in graphic settings?

**Comment by Alexanzero** [comment]
I tried and didn't work.

**Comment by Alexanzero** [comment]
> @Alexanzero I had crashes like that due to animations of leaders. Have you tried setting leader animations to minimal in graphic settings?

I tried and didn't work.

**Comment by Alexanzero** [comment]
I tried vox populi version 7 - 29 - 1( community patch v 89) and i havent this problem. Then i will play with this version.
