### ISSUE TITLE
just for fun

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7103]
the roman navy sure is experienced!

![image](https://user-images.githubusercontent.com/1358966/94237804-b5541400-ff0f-11ea-9dfc-4667ad2f7046.png)

**Comment by SuperNoobCamper** [comment]
Winged hussars: I identify as a modern era 1500 ton destroyer armed with 6 20mm AA guns.

**Comment by DelJon** [comment]
that's a lot of fish, what a sick city it must be
