### ISSUE TITLE
Weird city trades

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#7107]
_1. Mod version (i.e Date - 4/17):_
One of the many hotfixes of 8/23

_2. Mod list (if using Vox Populi only, leave blank):_
None that affects AI

_3. Error description:_ 
Mongolia and Japan trade the same city back and forth on the same turn, for vastly different values.

Log excerpt:
337, Japan, Mongolia, , , ***** City Trade: ID Tokyo *****, (value 3841 - raw)
337, Mongolia, Japan, , , ***** Resource Trade: ID TXT_KEY_RESOURCE_TOBACCO *****, (value 207 - raw)
337, Mongolia, Japan, , , ***** Resource Trade: ID TXT_KEY_RESOURCE_WINE *****, (value 623 - raw)
337, Mongolia, Japan, , , ***** GPT Trade: 61 *****, (value 3050 - raw)
DEAL COMPLETE: Deal Net Value: -39, From Player Value: -3880, To Player Value: 3841

337, Mongolia, Japan, , , ***** City Trade: ID Tokyo *****, (value 17811 - raw)
337, Japan, Mongolia, , , ***** City Trade: ID Hong Kong *****, (value 10249 - raw)
337, Japan, Mongolia, , , ***** GPT Trade: 152 *****, (value 7600 - raw)
DEAL COMPLETE: Deal Net Value: -38, From Player Value: -17849, To Player Value: 17811

At the end Japan traded Hong Kong and 91GPT for Tobacco and Wine, as well as losing lots of buildings in Tokyo.

Earlier on Mongolia already scammed a city with 3 wonders from the Inca. Their biggest city. For 31GPT.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Ok this just happened.

![image](https://user-images.githubusercontent.com/14953746/94370006-b9ef1700-011f-11eb-8118-bf8a58c8d2fd.png)

367, Japan, Mongolia, , , ***** City Trade: ID Osaka *****, (value 5749 - raw)
367, Mongolia, Japan, , , ***** City Trade: ID Montreal *****, (value 5578 - raw)
367, Mongolia, Japan, , , ***** GPT Trade: 4 *****, (value 200 - raw)
DEAL COMPLETE: Deal Net Value: -29, From Player Value: -5778, To Player Value: 5749

The city has 5 wonders.

**Comment by DelJon** [comment]
Genghis legendary negotiation skills!
On-topic I've seen more City trading this patch, mostly from weak AIs to warmongers. Not like this though.
