### ISSUE TITLE
Autocracy happiness policies are bugged

### ISSUE THREAD

**Issue by paramenides** [LoneGazebo/Community-Patch-DLL#7108]
_1. Mod version (i.e Date - 4/17):_

9/8
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

After selecting two of the policies in Autorcracy, the one that is supposed to reduce distress unhappiness by 20% in every city and the one that is supposed to provide +3 happiness for courthouses (among other effects which should also affect unhappiness), absolutely nothing changed. Generally this is not the case with Order policies...I usually see an immediate effect.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
Happiness sometimes needs to update before it shows. Did it work after you ended the turn?

**Comment by paramenides** [comment]
No. 
Unless it takes several turns, and then the answer is " I am not sure, but probably not."
It would be weird if it worked like (delaying several turns) this for autocracy policies and not other policies, though, right?

**Comment by Mileslewis** [comment]
I'm just meaning happiness changes will sometimes not apply until you end the turn. It wouldn't take longer than that though.
