### ISSUE TITLE
Strategic aluminum monopoly does not provide healing to naval units

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#7113]
_1. Mod version

9-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Tooltip says "Units gain +5 HP when healing". Nothing about land vs naval.
With this monopoly my land units heal 20 HP/turn, but naval only 15 HP/turn.

**Comment by gamask** [comment]
It fixed itself when I loaded a save.
The issue occured only in the same game session as when the monopoly was obtained.
It persisted for the entire session. Definitely didn't fix itself the turn after the monopoly was obtained.

**Comment by gamask** [comment]
Loaded a save again, and now it's broken again (back to 15 HP/turn).
Broken or correct behaviour persists for the entire session.
Absolutely nothing changed with my aluminum situation the entire time.

**Comment by azum4roll** [comment]
See #7080
