### ISSUE TITLE
Industry finisher doesn't double luxury happiness

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#7115]
_1. Mod version: 9/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Base happiness per lux is 3. Industry finisher raises it to 4, not to 6.

**Comment by RecursiveVision** [comment]
```
UPDATE Policies
SET ExtraHappinessPerLuxury = '1'
WHERE Type = 'POLICY_COMMERCE_FINISHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );
```

SQL just adds a flat +1 per luxury, but the text says it doubles the value. @LoneGazebo
