### ISSUE TITLE
Combat preview is completely nuts

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#7116]
_1. Mod version: 9/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

![a00](https://user-images.githubusercontent.com/4227288/94884880-b66bd080-043c-11eb-9a70-865c5c01ed08.jpg)
![a01](https://user-images.githubusercontent.com/4227288/94884891-b8ce2a80-043c-11eb-9263-efca7fd47cb6.jpg)

In the first screenshot cav's strength is 47.5.
That's 144% of base of 33.
Listed bonuses add up to 59%. **That's issue # 1**
For the rifleman everything is correct.
15 + 10 + 33 + 40 = 98%
50 * 1.98 = 99
So the green percentages from the cavalry side don't affect the rifleman in this screenshot.

In the second screenshot the rifleman has all the same bonuses.
But now his strength is 91.5
That's 183% compared to 198% in previous screenshot. He somehow lost 15% despite having the same bonuses on his side.
There is no -15% anywhere.
**That's issue # 2.**

Now look at the cavalry in the second screenshot.
The differences compared to the 1st cavalry are:
+10% flanking (makes sense).
no -10% defense (makes sense; 1st cavalry has medic)
+20% miscellaneous
-20% terrain modier

What are these last two?
Skirmisher doctrine is -20% in rough terrain. Both cavalries are in rough terrain. **Issue # 3**
And what is the +20%? **Issue # 4**

Finally, the cavalry's modified strength is 74.2. That's roughly 225% of base.
Yet the bonuses add up to +80%, not +125%.
**Issue # 5**

**Comment by gamask** [comment]
Save:
[aTheodora_0297 AD-1854.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5320703/aTheodora_0297.AD-1854.zip)

**Comment by Mileslewis** [comment]
There are defo quite a few issues with the combat preview generally. Seems like the THEIR STRENGTH/YOUR STRENGTH numbers are correct from what I've seen however the individual modifiers are rarely correct.

When you try and do a preview for a combat where you are moving first it is always way off though so a lot of the differences here could be from that.

**Comment by Stalker012345** [comment]
I would say once things in the mod settle, I would love a strong pass at the combat preview code. It does seem like we find some UI issue in nearly every version, so my guess is there is something more fundamental in the code that needs review.

**Comment by ilteroi** [comment]
it's fundamentally broken, that is well known. somebody tried to recreate the overly complex c++ combat modifier logic in lua and the two implementations are simply out of sync.
