### ISSUE TITLE
Auto-workers possibly causing lategame performance drop

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7117]
_1. Mod version  8/16/2

Was playing a game with many workers and set them all to automatic. Was working fine until they started running out of tiles to build improvements on at which point the game started lagging massively at the beginning of every turn which was definitely because of the workers moving around.
From what I could see they were going into cities to wait there but instead of just waiting in the city they would all swap around at the beginning of each turn.
Saw some people mentioning lag lategame on the forums and this could easily be the cause if AIs use the same logic for workers as the auto-workers for players.

Another minor issue was that the workers didn't seem to know they could build forts on non-freshwater flat tundra or desert tiles as they were just leaving them unimproved.

**Comment by LoneGazebo** [comment]
@ilteroi something to look at?

**Comment by ilteroi** [comment]
eventually ...

**Comment by LoneGazebo** [comment]
@ilteroi I think I fixed it. A little too much stacking in the for plot loops in homeland AI for workers.

**Comment by ilteroi** [comment]
i don't think your change will change anything. do you have a testcase?

**Comment by LoneGazebo** [comment]
I ran verysleepy afterwards on a large map lategame and the function was very low on the % use side.

**Comment by Mileslewis** [comment]
Just to clarify it only became a problem for me once there wasn't anything left for the workers to improve.
