### ISSUE TITLE
WC proposal cooldown reset when loading saves

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#7119]
_1. Mod version: 9/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

End turn.
Open door Ur will fail.
Next turn you can't propose it.
Save game and reload.
Now you can.

[AutoSave_Post_0306 AD-1872.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5320875/AutoSave_Post_0306.AD-1872.zip)

**Comment by nhkun** [comment]
Can confirm on 10-7. AI proposed sanctions on me twice in a row with reload.
