### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#712]
I've created a mod where I can transport land units on melee ships. Unfortunately, under the latest community patch, if the melee ship is killed with a land unit that is cargo, it crashes the game. If this is any help to you, you can take a look at my minidump.

![cvminidump](https://cloud.githubusercontent.com/assets/14372214/10585982/b04ef198-765f-11e5-9afe-b8fbd0e6e889.jpg)

Rename the file from *.jpg to *.zip

**Comment by LoneGazebo** [comment]
Minidump won't open, though I'll tell you that adding such functionality directly contradicts a chunk of the core unit code. I doubt it'll ever work unless you write a lua hook to kill all the units on the tile before the cargo vessel is destroyed.

G

**Comment by Iamblichos** [comment]
Strange. Well it used to work just fine so I'm not sure if you changed up any core unit functionality.

I'm not really sure what it's doing because I went into IGE and deleted the land unit that was cargoed, and that made it crash too.

File opened fine for me in visual studio. If you are interested in taking a look at the dump, I can send it some other way to you.

**Comment by LoneGazebo** [comment]
"Used to work" meaning when? The file opens in VS, but it stacks out to the disassembly, which is virtually useless.

G

**Comment by Iamblichos** [comment]
With 10-2 iirc

**Comment by Iamblichos** [comment]
Yep, just tried with 10-2. Attacked a City state with a Trireme with a Spearman as cargo until the boat was killed. No crash. I bet it was a change done from 10-2 to 10-8.

**Comment by LoneGazebo** [comment]
Ilteroi fiddled around in that code recently, I think, but I'm not sure. In any case, I'm almost at RC for the next version, so it may have to wait. Send me your mod, please.

G

**Comment by Iamblichos** [comment]
Very strange findings. I played a 40 turn game earlier which prompted the request. Attacked a city state and lost the trireme that had a cargo. First time I noticed the crash. Replayed the crash turn with IGE editor and even deleted the land unit that was cargo on the trireme. Just by deleting the cargo unit made the game crash.

I then tried  10-8, 10-9, 10-13, large islands, classical era start. Created my units with IGE, performed the same routine, and none of them crashed. So I was stumped. Went back to the other game that was 40 turns in and let a few turns go by and lost that trireme again and it didn't crash. So something else is going on here. Must've been coincidental. If it's okay with you, I'll close this out as it appears there is something else going on here.

**Comment by Iamblichos** [comment]
Yeah sure I'll send it over.

**Comment by LoneGazebo** [comment]
Send it to TheLoneGazebo@gmail.com

**Comment by LoneGazebo** [comment]
Is this still breaking?

**Comment by LoneGazebo** [comment]
Going to assume that this is working now, as no reply.
