### ISSUE TITLE
Possible to Tribute every turn

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7124]
If you wipe out all units of a city state it isn't too hard to get your 'local military strength' modifier above the 'recently tributed' modifier so if you have some ranged units and wipe out the garrison every time they make it you can get 100% tribute every turn. Not a bug but was definitely quite ridiculous on last patch with high tribute values.

Aside from this tribute values are now going to start at 50 and go up to like 400 lategame which is pretty underwhelming (unless you are getting it every turn).

**Comment by azum4roll** [comment]
Lategame tributes aren't supposed to be that effective after all.
