### ISSUE TITLE
Missing changes

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7125]
My changes are missing from your squashed commit @LoneGazebo.

**Comment by LoneGazebo** [comment]
I merged and added everything you sent me.

**Comment by LoneGazebo** [comment]
Also I didn’t mess with memory values, so I worry that the save/load issues are stemming from the diploAI memory changes. Give them a once-over?

**Comment by RecursiveVision** [comment]
If you read through the list of commits in master branch, the changes are not listed, but they do seem to have made it into the release. Maybe the Github repo is out of sync?

I'll look over the memory changes - I think @ilteroi might have changed something as well?

**Comment by LoneGazebo** [comment]
That’s weird. I merged up 100%. I’ll do a clean check.

**Comment by Padre19** [comment]
There is no change in the cost of technologies. Some commits in master branch,not have made it into the release.

**Comment by RecursiveVision** [comment]
Did a once-over of the memory changes, I can't spot anything obvious. I didn't experience issues during my earlier save/load testing. It's possible something I changed got lost in a merge snafu somewhere, or that a change elsewhere is responsible.
