### ISSUE TITLE
CTD on new game (probably due to Mapscript)

### ISSUE THREAD

**Issue by usadefcon1** [LoneGazebo/Community-Patch-DLL#7127]
_1. Mod version: Oct 7th (10-7)

_2. Mod list (if using Vox Populi only, leave blank):_

![Screenshot (55)2](https://user-images.githubusercontent.com/57153924/95406260-fc66df80-08e7-11eb-8bf7-9c7e033ec0f4.jpg)

_3. Error description:_ 
CTD starting a new game with Venice. This is the last line in the Lua Log:

[93721.296] Runtime Error: C:\Users\nospa\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Mapscripts/Communitas.lua:8864: attempt to call method 'AttemptToPlaceStoneAtGrassPlot' (a nil value)
stack traceback:
	C:\Users\nospa\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Mapscripts/Communitas.lua:8864: in function 'NormalizeStartLocation'
	C:\Users\nospa\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Mapscripts/Communitas.lua:8909: in function 'BalanceAndAssign'
	C:\Users\nospa\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Mapscripts/Communitas.lua:960: in function 'StartPlotSystem'
	Assets\DLC\Expansion2\Gameplay\Lua\MapGenerator.lua:815: in function <Assets\DLC\Expansion2\Gameplay\Lua\MapGenerator.lua:779>
	=[C]: ?

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5344948/Logs.zip)

**Comment by azum4roll** [comment]
Use Communitu_79a aka Communitas for VP.

I'll still fix this though, for any potential mapscripts overriding NormalizeStartLocation.

**Comment by Mileslewis** [comment]
#7140
