### ISSUE TITLE
CTD after turn 98 and on loading saves

### ISSUE THREAD

**Issue by Spaghetti657** [LoneGazebo/Community-Patch-DLL#7128]
_1. Mod version: 10-7 (most recent)

_2. Mod list: Vox Populi (including EUI) plus a few non-DLL mods: Barbarians - Unlimited Exp, Quick Turns, Faster Aircraft Animations, RED Modpack

_3. Error description: Game crashed on founding a new city. Afterward all attempts to load recent auto saves (tried all the way back to turn 86) result in a crash to desktop.

_4. Steps to reproduce: start game > load mods from menu > load save > crash

[bugreport.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5345313/bugreport.zip)

**Comment by usadefcon1** [comment]
When I try to load turn 34 I get a CTD, but if I load turn 1 and then turn 34 it works. 
However, no matter what I do I cannot load turn 39.

**Comment by silentreply** [comment]
@usadefcon1 Your fix worked for me, for now at least. I was having some graphical issues (flickering when tech tree open) so I tried to reload but got a CTD. After that, I could no longer load the save, nor any recent autosave. I tried validating game files and reinstalling, neither worked. But strangely... I load the turn 1 autosave up fine, and then was able to load the most recent autosave.
