### ISSUE TITLE
10/7 - AI offers to trade 0 horses

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7129]
_1. Mod version (i.e Date - 4/17):_ 10-7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Doesn't appear to be affecting the trade value (although that is a pretty lucrative offer below..too good?), but AI offers to trade zero horses in deals. It might also affect other strategics but I haven't seen it yet. 
![image](https://user-images.githubusercontent.com/59859911/95418122-c5eb8d80-0904-11eb-9e28-b32f55858954.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by JamesNinelives** [comment]
I'm getting the same thing. No mods.

![20201008124857_1](https://user-images.githubusercontent.com/61379041/95421995-10a2ef00-0971-11eb-82eb-3f9186ddb2ab.jpg)
![20201008124936_1](https://user-images.githubusercontent.com/61379041/95421998-126cb280-0971-11eb-925f-24e94bb58dce.jpg)

**Comment by LoneGazebo** [comment]
Weird, zero deals shouldn’t be allowed. I’ll look.
