### ISSUE TITLE
ai trading cities a bit too easily?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#713]
check this:

![image](https://cloud.githubusercontent.com/assets/1358966/10599586/a8f6127e-7703-11e5-9556-3dd6ca04ad0e.png)

that wasn't even a peace deal. the huns just gave their biggest city away. hunnic military strength was twice as much as the celts!

**Comment by LoneGazebo** [comment]
What version are you looking at? In the previous version I made it so that the AI cannot sell (they can only buy or exchange) their cities through trade deals.

G

**Comment by ilteroi** [comment]
that's with the 10/16 version

**Comment by LoneGazebo** [comment]
huh, weird. I'll keep an eye on it, but I haven't seen that in a while.


G

**Comment by ilteroi** [comment]
just saw it again. arabia (scoreboard leader!) gives damascus to germany. 
no war, simply traded away. germany has the weaker military. no unhappiness problem for arabia either.

**Comment by LoneGazebo** [comment]
That's weird. I haven't seen that yet, maybe I fixed something recently that hasn't been uploaded. :)

Prepping a new version for release now. What was the fix I needed to put in for turnstoreachtarget? Seems to be working the way I had it, but the pathfinder can be tricky.

G

**Comment by ilteroi** [comment]
i'll re-check your fix for turnstoreach

**Comment by ilteroi** [comment]
turnstoreach is fine

but this is with the 10/23 version:

![image](https://cloud.githubusercontent.com/assets/1358966/10812674/ef3f8320-7e18-11e5-92cd-00e0d1970c59.png)

something seems to be wrong in the city valuation, they can't be serious

**Comment by LoneGazebo** [comment]
Huh. I mean, the AI can lowball, but woah. I'll check.

G
