### ISSUE TITLE
Crash on turn 135

### ISSUE THREAD

**Issue by JamesNinelives** [LoneGazebo/Community-Patch-DLL#7130]
_1. Mod version (i.e Date - 4/17):_
8/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
CTD at the start of my turn. I was able to see the map before the crash occured. I thought it was the result of founding my 4th city. After the crash, I am unable to load the autosaves from the previous 10 turns (crash before the screen is visible). The inital autosave works fine though.

Civ is The Celts, epic speed, huge map. I took a mix of Tradition and Progress in case that's relevant.

Edit: I was able to load the pre-crash saves again by loading turn 1 first as others have suggested. It seems the city founding is the trigger - the game crashes occurs if I try to settle on an earlier turn, or if I continue the game and settle on a later turn instead instead. I played another 30 turns to see if anything would change (before I tried settling again), but no luck.

---------------------------
Supporting information:
1. Log files. 

The log folder for this game seems quite large, so I didn't upload them all.
[Logs1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5345824/Logs1.zip)
[Logs2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5345825/Logs2.zip)

2. Save game:

[Autosave 134, 135.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5345835/Autosave.134.135.zip)
[Autosave159.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5346435/Autosave159.zip)

3. CvMiniDump.dmp file
No minidump file.

4. Screenshots
![20201008155105_1](https://user-images.githubusercontent.com/61379041/95430398-4dc1ae00-097e-11eb-8f00-61579776d138.jpg)

**Comment by Vyyt02** [comment]
I haven't tried the newest version yet myself. But I remember we had a similar problem like 2-ish years ago. Loading the save from turn 1 first and then loading the latest save fixed it too back then. @Gazebo, maybe the cause is the same as before? Do you guys remember?

**Comment by Zanteogo** [comment]
I have tried a few game and notice the CTD always occurs when placing your 5th city. 

This is on epic speed in a large map. 

Doing the loading turn zero and reloading does not fix it.

**Comment by JamesNinelives** [comment]
I just played another game on the same settings (Huge map, Epic speed), but with Authority (in case it was related to social policy) but got the same thing: crash on settling 4th city, consistently.
