### ISSUE TITLE
Traded to go to war, Negotiate Peace timer not decreasing

### ISSUE THREAD

**Issue by TranceBlossom** [LoneGazebo/Community-Patch-DLL#7131]
_1. Mod version (i.e Date - 4/17):_
10/7

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi & several UI mods, no gameplay altering mods

_3. Error description:_ 
I got another AI to pay me to go to war, but even after 30+ turns have passed I still can't negotiate peace because it says I have to wait 15 more turns.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5348844/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
See above zip

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20201009000307_1](https://user-images.githubusercontent.com/47022053/95477727-9cde0200-09c3-11eb-8245-5d23ea3cedac.jpg)
![20201009000204_1](https://user-images.githubusercontent.com/47022053/95477732-9e0f2f00-09c3-11eb-96ab-95742f98f050.jpg)

**Comment by RecursiveVision** [comment]
I'll take a look at what's up later today.
