### ISSUE TITLE
10/7 - City state falls (automatically?) to barbarians upon end of "horde" quest

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7134]
_1. Mod version (i.e Date - 4/17):_ 10-7
Improved city view v11
Promotion flags v3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
T88:
![image](https://user-images.githubusercontent.com/59859911/95507835-089e7b80-0980-11eb-8200-696eea369005.png)

T89:
![image](https://user-images.githubusercontent.com/59859911/95507976-44d1dc00-0980-11eb-86d6-6513d37770d1.png)

Logs and save (same folder):
[logs and autosave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5351092/logs.and.autosave.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Yes?

**Comment by RecursiveVision** [comment]
I thought the idea was that if you fought off the Barbarians, it wouldn't turn into a Barbarian city?

**Comment by silentreply** [comment]
@LoneGazebo The city is at full health with no barbarian units next to it. I thought in the past you could simply "protect" them by killing off any units. It used to be pretty much free influence as you mop up the barbs while the CS was typically not in any real danger. 

In this case it seems the city is falling regardless at the end of the quest.

**Comment by LoneGazebo** [comment]
Hmm. Not sure. It fails if the ‘kill barbarians’ subquest is active.

**Comment by silentreply** [comment]
So if any barbarian is in the CS territory (thus "kill barbarians" active), on the turn the "protect them from horde" quest expires, the CS converts? 

I'm thinking in the above example a barb spawned the same turn the horde quest was ending, but the CS did not kill it immediately (and player/AI have already taken their turns). Although I forget if CS move after barbarians, if the barbarians go last then the CS also has no chance to kill it. 

If that is the case, why should barbs spawn on the final turn of the quest? I think it would be better to disable them for the last few turns, say 3 turns.

**Comment by RecursiveVision** [comment]
The Horseman must have spawned on the final turn and caused the quest to fail, that's my thought. A while back I set it so that a garrison would spawn whenever Barbs take a city, meaning the garrison could not have been there previously.

**Comment by azum4roll** [comment]
Btw, is it intended that barbarian cities cannot work land tiles?

**Comment by RecursiveVision** [comment]
I don't know if Barbarian cities actually work or produce anything. They're set to spawn units periodically much like camps.

**Comment by azum4roll** [comment]
They can work water tiles and not starve that way, otherwise they just keep starving.
