### ISSUE TITLE
[10-7-2] Borobudur does not give extra religion spread actions retroactively

### ISSUE THREAD

**Issue by Maxxim69** [LoneGazebo/Community-Patch-DLL#7139]
_1. Mod version (i.e Date - 4/17):_
10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
As per wonder description, Borobudur is supposed to give "all new and existing Missionaries and Prophets 1 Additional Religious Spread action". What actually happens in VP 10-7-2 is Borobudur gives this extra religion spread only to Missionaries purchased after it's constructed.  Existing Missionaries, including the two provided by the wonder itself, are left with 2 religion spread actions.

_4. Steps to reproduce (optional):_

**Comment by aleph-hax** [comment]
Same thing here.

4. Steps to reproduce (optional):
build Borobudur (sorry)

**Comment by briantjack** [comment]
Same thing happened to me.

**Comment by LoneGazebo** [comment]
@ilteroi you changed some stuff here, right?

**Comment by Maxxim69** [comment]
Still not fixed as of version 12-1-3.

**Comment by ilteroi** [comment]
relax everyone, it's not the end of the world

**Comment by Maxxim69** [comment]
Hey, it's just a bug report, not the end of the world report. :D
Would be nice to see it fixed eventually though.

**Comment by RecursiveVision** [comment]
Well it will be for next version :)
