### ISSUE TITLE
CTD when I try to open Advisor Council menu 

### ISSUE THREAD

**Issue by hawkseye17** [LoneGazebo/Community-Patch-DLL#7142]
_1. Mod version (i.e Date - 4/17):_

 10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_

![Screenshot (116)](https://user-images.githubusercontent.com/67494452/95685507-4c82c200-0bc6-11eb-9069-49b33b0a338f.png)
![Screenshot (115)](https://user-images.githubusercontent.com/67494452/95685509-4d1b5880-0bc6-11eb-9f42-5ddbd9764951.png)

**Note, Only the following mods are new since I've started seeing this crash, all others have never caused it**:
Vox Populi Version 10-7-2 (non-EUI installation)
Events and Decisions 
Neolithic Wonders
Reseed
Vox Populi's Bare Necessities 
Wonders Expanded

_3. Error description:_ 

Whenever I try to open the advisor council, the game crashes.

_4. Steps to reproduce (optional):_

Open the advisor council 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

[Crash Files 1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5361543/Crash.Files.1.zip)

**Comment by LoneGazebo** [comment]
Can’t diagnose that many extra mods unfortunately.

**Comment by azum4roll** [comment]
Doesn't advisor randomly crash the game since always?

**Comment by hawkseye17** [comment]
@LoneGazebo only the 5 mods under the note are new since I've started seeing this crash. I know for sure the others are not causing it. 

@azum4roll advisor menu only started crashing for me recently

**Comment by ASCII-Guy** [comment]
I've crashed on the advisor menu before. I really need to compile a debug dll and get it to crash to see if we can finally get this fixed.
