### ISSUE TITLE
10/7 - Local unhappiness UI incorrect?

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7143]
_1. Mod version (i.e Date - 4/17):_ 10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In the city below, switching a citizen from the forest to the deer camp tile should lower the unhappiness in the city according to the UI. Food is increased by 3 (~2 after unhappiness penalty) which should eliminate the food/production distress (1.7 deficit). The UI also states that increasing culture by 0.95 culture will lower unhappiness from boredom - but note the deficit is 3.45. 

However, when the tile is swapped, the unhappiness remains the same and is not lowered for either yield. It remains the same on the next turn. On my end it seems there is around a 50% penalty to food/production yields when it comes to eliminating the displayed deficit.

![image](https://user-images.githubusercontent.com/59859911/95704965-900a1a00-0c20-11eb-90aa-51ac24c2a090.png)
![image](https://user-images.githubusercontent.com/59859911/95704985-9b5d4580-0c20-11eb-8dd1-6b82d6b95b4c.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by silentreply** [comment]
@LoneGazebo Just didn't want this one to get lost among the other reports. If food/production is incorrectly being penalized by 1/2 with regard to distress deficit, this may explain a lot of the happiness struggles early game. Especially with wide it often seems impossible to meet food/production distress even when the city is working great tiles and has good infrastructure.

**Comment by bsesar** [comment]
@LoneGazebo , would you please comment on the above issue? I think I may be seeing the same problem.
