### ISSUE TITLE
10/7 - City-state building project quest requirements much lower

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7145]
_1. Mod version (i.e Date - 4/17):_ 10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When city-states give a building project quest, the required number of buildings is very low. For example, below I have 8 cities (0 walls) but only need to build 1 wall. 

In previous versions, you would typically need to build multiple, and often one in _every_ city. This quest was often too difficult (for wide) in its previous states, but too easy currently. Can we try to find a middle ground here? Something like 50% of cities without the building, rounded up, but with a hard cap (~8) so that it doesn't get out of hand for wide. 

![image](https://user-images.githubusercontent.com/59859911/95720869-cc993e00-0c3f-11eb-89e6-13a5992d42cd.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by JanSobus** [comment]
In the previous version it was ok'ish up to late medieval but endgame requirements were terrible (got asked to build 55 hotels once)
