### ISSUE TITLE
(10-7-2).exe being quarantined for containing "Trojan:Win32/Fuery.C!cl" by Windows 10

### ISSUE THREAD

**Issue by Lillebo** [LoneGazebo/Community-Patch-DLL#7146]
![ApplicationFrameHost_zzxXaFfZlC](https://user-images.githubusercontent.com/74510/95790843-74fedf00-0ce0-11eb-81c7-0d481ca6aa84.png)

**Comment by SuperNoobCamper** [comment]
I double checked & updated windoes defender but it's not infected on my machine.
This is pretty strange, even after turning on reputation based protection it's free .... Some people are reporting similar resuts as yours on the forum.

**Comment by LoneGazebo** [comment]
My guess is that your connection to Mega is being intercepted - I've doubled-checked my exe files and I see no virus or malware.

**Comment by ricanuck** [comment]
Defender was doing the same to my DL yesterday, but after today's update, at least MS Defender is not flagging the file anymore... it's still being flagged by two engines from Virustotal though...

No, connections are not being intercepted. Either the Inno installer has some iffy code that is calling a few engine's heuristics analyzers, or... well, you are not the only developer anymore, G, or are you?

I mean, dirty code can come from any machine working in compiling, not only yours...

**Comment by RecursiveVision** [comment]
@ricanuck G compiles all the code personally.

**Comment by ricanuck** [comment]
@RecursiveVision good to know, that fact points to a FP even stronger... but something is iffy with the Inno setup installer builder, at least...

**Comment by ricanuck** [comment]
Talked too fast... LOL

Just out of curiosity, I updated MS Defender once again, and now it flags the file again, and with the same Fuery crap as the OP. Yesterday it flagged it with something different...

And No, my connection is not being intercepted.

I suspect the Inno builder...

**Comment by bsesar** [comment]
After the update, my Windows Defender is reporting the same malware on the VP file. Of course, it did not report any installed malware after a full system scan (I installed VP a few days ago). I will submit a false positive report to Microsoft.

https://www.microsoft.com/en-us/wdsi/filesubmission

In the case of this developer, using the Inno Builder *solved* his problem with false positives (another application builder was initially causing alerts)

https://weblog.west-wind.com/posts/2016/oct/05/dealing-with-antivirus-false-positives

I think the only things we can do here are:

1. Submit false positive reports
2. Sign the executable using a certificate

https://stackoverflow.com/questions/252226/signing-a-windows-exe-file

The later may not help with AV false positives, but at least people may feel more comfortable installing the file.

**Comment by bsesar** [comment]
I just checked again after updating my Windows, and Microsoft Defender is no longer making a false-positive detection (i.e., no malware detected in VP installer). This is so dumb.

**Comment by LoneGazebo** [comment]
Self-signing a certificate is pointless, and certificates cost on average $200/ year. That’s a bit out side of my price range.

**Comment by ricanuck** [comment]
Yeap, just updated and it's not flagging the file anymore... for now. The same pattern emerged yesterday, the morning update flagged it, the afternoon update cleared it.

OTOH, downloading manually was a PITA slow, for a moment I thought I was back in the Third World... perhaps zipping the whole pack before posting to Mega would make it faster? As an alternative to the Installer...

**Comment by LoneGazebo** [comment]
And then people have to manually move/delete the files. That's why I made the installer in the first place.

**Comment by ricanuck** [comment]
I know, but beats people disregarding the installer because their main AV (Win 10 Defender) blocks the file... doesn't it?

**Comment by ryanmusante** [comment]
For preparation of gold, setup donation box for signed installer?

**Comment by ricanuck** [comment]
@ryanmusante having both the installer and a zipped file of the entire package is cheaper, isn't it? At least that gives people the alternative... read @bsesar 's second link, that article is very interesting and suggests a pattern that, if true in this case, will make this problem potentially reappear without cause or explanation.

**Comment by ricanuck** [comment]
Looks like Defender at least got its act together, two days in a row without flagging the file anymore...
