### ISSUE TITLE
blockades

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#715]
so it seems to be possible to blockade city even if it has a "redundant" road connection to the capital. intended or not?

![image](https://cloud.githubusercontent.com/assets/1358966/10658365/6fa27d66-7896-11e5-9b77-5b9a6ddafe76.png)

while checking the code, i found an oddity in UpdateRouteInfo()

					if(bBestRouteFound)
					{
						pRouteInfo->m_cRouteState |= HAS_BEST_ROUTE | HAS_ANY_ROUTE;
					}
					else if(bAnyRouteFound)

--> no clause after the else!

**Comment by LoneGazebo** [comment]
Yeah, the blockade thing is by design (boats blockading the port).

Not sure about the updaterouteinfo() issue.

**Comment by ilteroi** [comment]
boats blockading the port sure is by design ... but should they be able to block the road as well?

**Comment by LoneGazebo** [comment]
Well the disconnection bonus is for both disconnection from the capital and/or being blockaded (see the toppanel tooltip).
G
