### ISSUE TITLE
10-7 v2 Lake Victoria not treated as a normal lake by city

### ISSUE THREAD

**Issue by Skidizzle** [LoneGazebo/Community-Patch-DLL#7150]
10/7 v2 43civ Vox EUI

I built a city next to Lake Victoria and then built forts to connect a string of lakes to the ocean. All other cities along the string of lakes are able to build ships and lighthouses that provide city connections to the capitol. All but the one adjacent to Lake Victoria :(

**Comment by ilteroi** [comment]
unfortunately natural wonders are not normal tiles, so it's not a real lake.

**Comment by Skidizzle** [comment]
Should there be some sort of warning about this in the tile's tooltip for new players? I've had months sunk into VP and wasn't aware of this. Just a QoL request
