### ISSUE TITLE
10/7 - CS influence not decaying

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7151]
_1. Mod version (i.e Date - 4/17):_ 10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Something has stopped my influence from decaying with CS.  I don't have any beliefs/policies that should enable this such as statecraft trade routes. 

![image](https://user-images.githubusercontent.com/59859911/96021784-e42e1d80-0e1d-11eb-94a8-f0b66cbe2efb.png)
![image](https://user-images.githubusercontent.com/59859911/96021814-f0b27600-0e1d-11eb-9e3e-7679fac4518b.png)

Seems to apply only to allied CS, friendly are still decaying at usual rate:
![image](https://user-images.githubusercontent.com/59859911/96022607-19873b00-0e1f-11eb-9996-e188b9b745f0.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Cold War?

**Comment by silentreply** [comment]
@LoneGazebo Negative, world congress has not even met yet.

**Comment by randomnublet** [comment]
I noticed for this to happen you only have to be allied and share religion. Also, sharing religion is enough for the influence to raise by 4 every turn if you angered the CS in past and its opinion is below 0.

**Comment by silentreply** [comment]
@randomnublet That is indeed what's happening. I think the influence recovering faster when religion is shared was an intended change several versions ago, but I don't recall anything about freezing influence. The latter is probably too OP.

**Comment by JanSobus** [comment]
Can confirm, noticed it in my game too

**Comment by ricanuck** [comment]
Confirmed: any CS sharing religion stops decaying influence, be it as Friend or Ally.

WAD or BUG?

**Comment by LoneGazebo** [comment]
Should only do so with the religious enhancer?

**Comment by randomnublet** [comment]
I never selected that particular belief in my whole VP career :P

**Comment by ricanuck** [comment]
Me neither. At first, I thought it was a change to empower religion gameplay, but then saw others reporting and joined the fray.

**Comment by Mileslewis** [comment]
Okay so the issue is from MINOR_FRIENDSHIP_RATE_MOD_SHARED_RELIGION which is an xml value in CoreDefines file in:
(2) Community Balance Overhaul\Balance Changes 

Currently it's set at 300. It is halved before it is applied but still gives -150 so decaymod in GetFriendshipChangePerTurnTimes100( in CvMinorCivAI goes below 0 so is then set as 0. This is also the reason having a shared religion with a minor means your influence will recover super fast.
