### ISSUE TITLE
10/7 - AI not swapping academy tile to workable city

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7152]
_1. Mod version (i.e Date - 4/17):_ 10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Maybe this is just a UI thing but it appears that Celts are not working this academy tile. It is "owned" by Edinburgh but can only be worked from Dublin.
![image](https://user-images.githubusercontent.com/59859911/96021991-366f3e80-0e1e-11eb-9511-645fbfdae7d9.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Pretty sure that yellow outline is just showing the tiles that the city gained. If you press Ctrl+Z in debug mode (save your game first!), you can see which tiles they're working in green.

**Comment by silentreply** [comment]
Ok I guess the AI has a different set of rules then for what tiles you get on city capture. I'm pretty sure the human player is able to swap over any tiles if they are about to lose a city and the AI doesn't get them on capture.
