### ISSUE TITLE
10/7 - Inquisitors of other religions

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7153]
_1. Mod version (i.e Date - 4/17):_ 10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

If you use an inquisitor of a different religion, is it supposed to convert the city to your majority religion or the faith of the inquisitor? I thought in the past it converted the city to the inquisitors faith. 

I wanted to flip this city to Buddhism below, but the inquisitor just strengthened my own religion (Hinduism). I thought you could do this with inquisitors but maybe you need a prophet to do it?
![image](https://user-images.githubusercontent.com/59859911/96067281-5e36c480-0e67-11eb-9fe2-90d62b08c2a2.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
It's possible if Hinduism has Prophecy enhancer that a Buddhist Inquisitor could make the city flip to Hindu. Is that what happened here?

**Comment by silentreply** [comment]
@Mileslewis Yes, Hinduism has the prophecy enhancer. But that enhancer says it should reduce the followers lost by half - so I would think that instead of going from 16 Hindu followers to 0, it should just go to 8. Maybe you would need two inquisitors to actually convert, but the description is not really clear on how many followers you should gain with inquisitors. Actually, based on the description only using an inquisitor should not gain any followers, only remove followers of other religions..

I tried to buy a prophet from a Buddhist city but turns out the prophet gets your majority faith and not the religion of the city. I don't think it worked like that before?
![image](https://user-images.githubusercontent.com/59859911/96211585-bd1d3c00-0f42-11eb-850d-e9eb673356b9.png)

**Comment by Mileslewis** [comment]
Inquisitors reduce the total pressure which doesn't translate directly into followers. Also it seems to me like inquisitor reduction from prophecy enhancer might be more than 50% so the followers go down by even less than half.

And I was pretty sure you can't get prophets of other religions but I'm surprised it let you buy one in that city.

Missionaries should be enough once you have used an inquisitor or two though.

**Comment by silentreply** [comment]
Inquisitors just don't seem to work all that well in this version. I am also doubtful that they are providing any conversion resistance when stationed. I remember in the past version I was eliminating all followers of other religions while converting a majority to my religion. Look what happens when I use an inquisitor for Shinto (my religion) in the city below. It eliminates all Catholicism but somehow increases the followers of Buddhism, becoming the majority. 
![image](https://user-images.githubusercontent.com/59859911/97093023-ce3b0c80-1616-11eb-8519-17b23bde39ba.png)

![image](https://user-images.githubusercontent.com/59859911/97093031-d430ed80-1616-11eb-9fcf-8d1915d2193f.png)

**Comment by silentreply** [comment]
Here Aztec use a GP (Catholicism) on this city adding 5 followers for Buddhism as well. Something is up here. 

![image](https://user-images.githubusercontent.com/59859911/97108542-aa260c80-16a4-11eb-874c-fac83cd2184a.png)
![image](https://user-images.githubusercontent.com/59859911/97108556-c629ae00-16a4-11eb-8020-f010afa46e09.png)

**Comment by briantjack** [comment]
@silentreply 
Opening with a disclaimer, I am not a programmer, but I think the game appears to function properly -- as I understand the way faith conversion is executed in the game. (I can't speak to the programming intent behind purchasing units with faith.) I think there's a running tally (that's hidden to the player) for the influence strength of each religion; any modifier that occurs during play (e.g., +106 Pressure, +1000 Faith, etc.) is applied to that running tally. The number of followers for each religion is a reflection of the apparent fraction that religion has of the city's total faith.

The Prophecy enhancer actually frustrates this running tally -- not the number of followers. So, in your first example, suppose the running tally looks as follows.
- Shinto: 5000 (10 followers)
- Hinduism: 4000 (8 followers)
- Buddhism: 1000 (2 followers)
Then you use the Buddhist inquisitor to zero out other religions -- but Hinduism has the Prophecy enhancer. The new tally will look like this.
- Shinto: 0
- Hinduism: 2000 (13 followers)
- Buddhism: 1000 (7 followers)
Hinduism would become the majority religion for this city.

I think the results shown in your last two examples can be similarly explained.

LoneGazebo is looking at it, though, so I'll defer to his expertise.

**Comment by silentreply** [comment]
@briantjack Thanks for the explanation! However in the Korea examples, the reduction from prophecy enhancer is only supposed to apply when it is the majority faith in the city. Buddhism does have prophecy in those examples, so perhaps it is being applied even when it is not the majority.

**Comment by Mileslewis** [comment]
Yea it definitely is still applied when the religion is not majority. A few patches ago I felt like it was being applied twice on majority cities because the follower reduction when using inquisitors was so low. So once for followers in any city and then again if the city is majority of that religion and you own the holy city which are the normal requirements for enhancers.

Not sure if this was fixed or if I was just wrong about that though.
