### ISSUE TITLE
10-07-2 New natural wonders crash modpacks on map start

### ISSUE THREAD

**Issue by JanSobus** [LoneGazebo/Community-Patch-DLL#7159]
_1. Mod version (i.e Date - 4/17):_
10-07-2

_2. Mod list (if using Vox Populi only, leave blank):_
VP + More wonders for VP

_3. Error description:_ 
So this is a more descriptive continuation of #7141. When using More Wonders for VP, standard modded games work properly but modpacks crash to desktop on map start/generation. It is happening for MW for VP versions 9 or 10.3, previous ones (8.3 or older) didn't have new natural wonder models and seem to work fine. The only difference in logs between bare VP or VP + MW 8.3 and VP + MW 10.3 is in lines 196-197 of CustomMods.log -> PROMOTION_CROSS_MOUNTAINS = 0 in the former and 1 in the latter. Adan says that new natural wonders use some VP dll features that are disabled by default and that might root of the issue: https://forums.civfanatics.com/threads/more-wonders-for-vp.653498/page-35#post-15936455

If anyone of you wizards could fix the problem, that would be great.
I created VP +MW 10.3 modpack (the one that is crashing) that you can download here: https://www.dropbox.com/s/r8yxganyoo8cs2h/MP_MODSPACK.7z

Thanks for all your work! 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by adaneslavo** [comment]
I am curious too and would like to know where the problem lies. I'm not using modpacks now, but if the problem is not on VP side I will try to fix it. Standard version works well and have no such problems like CTDs or something. Issue seems to be only with multiplayer modpack.

**Comment by adaneslavo** [comment]
Any ideas why it is crashing multiplayer, when it is working fine single player? Can you check if it is because of using some of VP built-in features?

**Comment by RecursiveVision** [comment]
G has said he doesn't debug modpacks.
