### ISSUE TITLE
IGE crash

### ISSUE THREAD

**Issue by shader301202** [LoneGazebo/Community-Patch-DLL#716]
When I open the InGameEditor, my game crashes. I use the 10/23 version, before this version my game doesn't crashed.

**Comment by LoneGazebo** [comment]
I'll give it a look.

**Comment by Vyyt02** [comment]
If it helps (to either of you :-) ), it seems that you can open IGE at the beginning (first turn?) of the game, then it starts crashing.

**Comment by LoneGazebo** [comment]
I've fixed it. It'll be fixed in upcoming version. Was a divide by zero from IGE spoofing a player to run.

**Comment by shader301202** [comment]
Ok, thanks for the answer :)
