### ISSUE TITLE
Religious pressure not shown when establishing TR

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#7160]
_1. Mod version 10-7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: In the latest version the religious pressure is not displayed in the list of cities to trade with (see screenshot), Yet when the trade route is established I can see the increase in the religious pressure.
![20201021092254_1](https://user-images.githubusercontent.com/64471766/96687131-c0b82500-137f-11eb-8845-cb8e6dfcdbf5.jpg)

**Comment by LoneGazebo** [comment]
@ilteroi you made some changes here in the DLL that might affect the UI, yes?

**Comment by ilteroi** [comment]
fixed
