### ISSUE TITLE
Constabularies not preventing Building disruption?

### ISSUE THREAD

**Issue by DelJon** [LoneGazebo/Community-Patch-DLL#7163]
_1. Mod version (i.e Date - 4/17):_
latest

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I've got a Constabulary in my Capital but the Aztecs still manage to sabotage my wonder.

_4. Steps to reproduce (optional):_
Build Constabulary, wait for enemy spies? Might be tricky to recreate
![20201024140852_1](https://user-images.githubusercontent.com/23047762/97080275-d2f5c580-1602-11eb-8773-bad3ffaaa75a.jpg)
![20201024140842_1](https://user-images.githubusercontent.com/23047762/97080277-d4bf8900-1602-11eb-8fe3-9665ca7f1b84.jpg)

**Comment by azum4roll** [comment]
Maybe only "buildings" count, not units and wonders?

**Comment by DelJon** [comment]
Units of course, but wonders would be considered buildings, no?
Not having my wonder construction sabotaged was big part of the reason I decided to pick up the constabulary early.

**Comment by LoneGazebo** [comment]
buildings != wonders - they're two different categories.
