### ISSUE TITLE
10/7 - Warmonger ferver maxing out too fast

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7164]
_1. Mod version (i.e Date - 4/17):_ 10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I've been at war with China for 4 turns and have not captured any cities, yet he already has maximum warmonger fervor (+75%). China had already been at war with Aztecs for probably 15 turns or so, and lost their capital, but I don't see why that would affect the bonus they get vs me. 

![image](https://user-images.githubusercontent.com/59859911/97092614-5d462580-1613-11eb-9a33-782c26d63c0c.png)

I've been at war with France for the same number of turns, who appropriately has no warmonger fervor bonus. 

![image](https://user-images.githubusercontent.com/59859911/97092654-b0b87380-1613-11eb-855b-79df7092e645.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bigcat88** [comment]
It is always work like this.

**Comment by silentreply** [comment]
@bigcat88 Always worked like how? The AI gets automatic maximum fervor against all players if they lose their capital? I've never seen any mention of the sort. 

It's not like I've been warmongering the whole game and have a huge warmonger score, if so, France would already get some fervor vs me.

**Comment by LoneGazebo** [comment]
no, but if your warmonger goes above the cap threshold, you still have to wait for the value to come back down below the threshold before it'll reduce the warmonger CS bonus.
