### ISSUE TITLE
10/7 - AI production choices in wartime

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7168]
_1. Mod version (i.e Date - 4/17):_ 10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The AI tends to make poor production choices during wartime, especially when cities are on the verge of capture. Rather than building units or defense process, they will build random things. One thing they are especially susceptible too is plundering of trade routes. When a trade route gets plundered, the AI prioritizes replacing it, but often just resends it on the same route to be plundered again, giving more gold to the enemy.

Just prioritizing the building of units or defense process when a city is under siege would be a major improvement. 

On a similar note, the AI seems very reluctant to use great generals for defensive purposes. 

Just an example below, the AI is choosing to build public works in a happy city, and their empire is happy as well. Earlier they were building trade units and other useless items while their city is under attack. 
![image](https://user-images.githubusercontent.com/59859911/97109761-74d0ed00-16ab-11eb-894b-8add5c8dac35.png)
![image](https://user-images.githubusercontent.com/59859911/97109771-80241880-16ab-11eb-8c56-2a9a8a3887f2.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
They also won't move away those great people until it's too late (1 turn before capture).
