### ISSUE TITLE
10/7 - Naval units medic promotion penalty not shown, do not receive "dazed" effect from slinger UU

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7172]
_1. Mod version (i.e Date - 4/17):_ 10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/59859911/97213547-1f263e80-1798-11eb-8694-1841f83d749b.png)

Looks like the medic penalty is counted but not displayed. 16.8 / 14 = 1.2 so a net 20% bonus. 30% from coastal raider - 10 % from medic promotion, I assume. Their displayed combat bonus is 30%, but only 20% is applied, thus the medic penalty is hidden. 

Based on the wording of the slinger UU "concussive hits" promotion, the dazed debuff should apply to all units, including naval. It's my first time playing Inca so I'm not sure how it worked in the past. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
dazed is land only

**Comment by silentreply** [comment]
@LoneGazebo Thanks for letting me know. But shouldn't the combat preview for the trireme still read +20% (30% - 10%), or display the medic penalty?
