### ISSUE TITLE
No Iron in Workable Range of Capital with Strategic Balance turned on

### ISSUE THREAD

**Issue by jayeye2011** [LoneGazebo/Community-Patch-DLL#7175]
_1. Mod version (i.e Date - 4/17):_
10-7-2 with Milae revised AssignStartingPlots.lua downloaded from the master branch repo after pull request update
https://github.com/LoneGazebo/Community-Patch-DLL/pull/7140

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Pangea map, standard size with strategic balance did not generate iron within workable range of capital
![noiron](https://user-images.githubusercontent.com/69315126/97598841-99d3a180-19c4-11eb-9b3e-091354c506bd.png)
[noiron data.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5459703/noiron.data.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by jayeye2011** [comment]
Note. I had to use the updated AssignStartingPlots.lua because the one that came with 10-7-2 caused CTD with strategic balance enabled using the regular Pangea map.

**Comment by azum4roll** [comment]
There's an iron 4 tiles from your capital, so it's working as intended (4-6 tiles).

**Comment by jayeye2011** [comment]
@azum4roll Sorry, didn't read the the AssignStartingPlots thread in detail and must of missed this. I preferred the old version before you and tu_79 starting making the changes you made to Communitas_tu79 apply to all map scripts including vanilla map scripts. Will the pre-change AssignStartingPlots.lua file from one of the older Vox Populi versions still work without issue or did you guys make changes to other lua and cpp files that depend on your new version of AssignStartingPlots.lua?

**Comment by azum4roll** [comment]
I think you can use the old version. It just won't be compatible with Communitu_79a and has some problems like NWs being claimed by CS, and has some weird strategic resource-terrain combo like aluminum in jungles.

Nothing was changed regarding start locations, so I don't know about your one tile island start. Must be some obscure glitch in PlanetSimulator map.

The CTD should be fixed with the updated lua, but if you still encounter it please post your Lua.log.

**Comment by jayeye2011** [comment]
> I think you can use the old version. It just won't be compatible with Communitu_79a and has some problems like NWs being claimed by CS, and has some weird strategic resource-terrain combo like aluminum in jungles.
> 
> Nothing was changed regarding start locations, so I don't know about your one tile island start. Must be some obscure glitch in PlanetSimulator map.
> 
> The CTD should be fixed with the updated lua, but if you still encounter it please post your Lua.log.
