### ISSUE TITLE
indian religion is weak

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7178]
there was a time when india was unstoppable, but now india is almost always overwhelmed quickly. typical situation:

![image](https://user-images.githubusercontent.com/1358966/97791292-28b50980-1bd1-11eb-8500-63de05cadb4e.png)

maybe their starting faith should be increased, to allow them to found earlier?

**Comment by azum4roll** [comment]
Back then AI civs spread to their own cities first to allow India pressure to spread. Now they're much more aggressive.

**Comment by JamesNinelives** [comment]
Yeah. I don't know exactly why, but India's religion does seem in a sad state recently :(.

**Comment by DelJon** [comment]
This happens in my games as well. But when I played India myself recently, I had absolutely no problem maintaining my religion and exerting very strong pressure on my neighbors, even converting some of their cities.

**Comment by ilteroi** [comment]
well the good news is, with the latest (unreleased) changes they are able to make a limited comeback once they have inquisitors. but they have no chance abroad
