### ISSUE TITLE
unhappiness breakdown not working any more

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#718]
![image](https://cloud.githubusercontent.com/assets/1358966/10725211/963e11e2-7bca-11e5-9317-2035c237e481.png)

obviously, there is some unhappiness in my cities but the breakdown says zero. no mouse-over tooltip either

**Comment by LoneGazebo** [comment]
I took the lua out for it while making the new panel and forgot to put it back in. I'll fix.
G
