### ISSUE TITLE
endgame slowdown

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7180]
i did a profiler run and it's not pretty.

the main reason being area effect promotions, in particular:

- GetGiveDefenseModToUnit
- GetGiveOutsideFriendlyLandsModifierToUnit
- IsHiddenByNearbyUnit

do we really need those? i'm half of a mind to delete them or at the very least put them behind an ifdef. they wreck performance for no benefit for at least 99.9% percent of players.

**Comment by LoneGazebo** [comment]
I agree.

**Comment by Mileslewis** [comment]
Do great generals not have a similar effect or are we just allowing that since it's a well established mechanic?

**Comment by ilteroi** [comment]
generals use different code paths, well optimized. and they are relatively rare.

**Comment by Mileslewis** [comment]
I'm just thinking that those promotions could be being used in modmods and they do sound like interesting mechanics. I guess the only way to save them would be to convert them over to use similar system as Great Generals if that's possible?

**Comment by supermerill** [comment]
Or maybe they can be switch out via a setting, a bit like DIPLOAI_ENABLE_NUCLEAR_GANDHI
somethign like ENABLE_AREA_PROMOTION, or an enable per promotion.
and if it's switch out, the codepath can be deactivated behind a if.

**Comment by ilteroi** [comment]
ok it turns out there may be a relatively easy solution. there are 13 promotions sharing the same container:

- isGiveInvisibility()
- getGiveDefenseMod()
- getGiveCombatMod()
- getGiveExperiencePercent()
- GetGGGAXPPercent()
- getGiveOutsideFriendlyLandsModifier()
- getGiveExtraAttacks()
- getGiveHPIfEnemyKilled()
- getNearbyCityCombatMod()
- getNearbyHealFriendlyTerritory()
- getNearbyHealNeutralTerritory()
- getNearbyHealEnemyTerritory()
- getAdjacentTileHeal()

but only the last one (medic) is really in use. the idea is to give a separate container to medic units, making the checks for the others fast. let's see ...
