### ISSUE TITLE
City-states act as if you attacked them if you cannot keep your pledge to protect them

### ISSUE THREAD

**Issue by JamesNinelives** [LoneGazebo/Community-Patch-DLL#7181]
_1. Mod version (i.e Date - 4/17):_
10/7

_2. Mod list (if using Vox Populi only, leave blank):_
Community Events (v. 5)
Civ names by policies (v. 8)
Historical Religions (v. 55)
Krazjen's Great Writers (v. 1)
Quick Turns (v. 10)
Really Advanced Setup (v. 15)
Unique Cultural Influence (v. 4)

_3. Error description:_ 
If you say you will protect a city-state but your military drop below the required threshold, you loose your pledge to protect and a small amount of influence. This is reasonable, and there are warnings so that you have opportunity to build more units.

However, when this happens the city-state _also_ treats you as if you have agressively attacked them. IMO this is too extreme, because it means they will not grant you any quests for some time - 75 turns on epic speed, which is a very meaningful chunk of the game. It's particularly annoying because the threshold is the same for all city-states so this can happen to every CS you pledged to protect at the same time.

The workaround for this is that it goes away if you become friends with them, which is fine. And if you already have lots of influence with them this will happen after 1 turn. It's less of an issue late-game when CS influence levels tend to be very high. But early and mid-game sending an envoy to make friends costs a fair amount of your resources. I think loosing some influence (as is already the case) is reasonable, but the CS acting as if you attacked them does not seem fair. 

---------------------------
Supporting information:

Screenshots

![betrayal](https://user-images.githubusercontent.com/61379041/97975453-1d95ef80-1e04-11eb-875b-4ec0d9d05940.jpg)

**Comment by JamesNinelives** [comment]
I noticed just now that the same thing happens if a CS you have declared to protect is allies with a civ who declared war on you. E.g. the Ottomans declare war on me, and so does their allied city-state 

![20201107021727_1](https://user-images.githubusercontent.com/61379041/98437702-63fa8f80-211f-11eb-9bf3-f29d734262f3.jpg)

I can understand if the initial issue was intended (if you are not strong enough to protect them). But a CS saying that you 'agressively attacked them' when they literally attacked you is a bit silly haha.

**Comment by RecursiveVision** [comment]
I simply removed this mechanic. Reducing Influence is a better way to deal with this.
