### ISSUE TITLE
10-7-2 lighthouse on lakes

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#7183]
Not sure if bug or feature, but being able to build lighthouses, or even the great lighthouse next to a 1 tile lake looks silly.

**Comment by ilteroi** [comment]
#7011

**Comment by bsesar** [comment]
I think this is intended and sometimes useful. For example, build a cargo ship then transfer it to a different city (I built one in my capital that was next to a lake), build warships on the lake as a static defense, etc. However, a capital on the lake with a lighthouse *does not* connect to cities with a lighthouse (I verified this), which is good design in my opinion.

**Comment by bigcat88** [comment]
I imagine how people build a cargo in lake and then transfer it to coast... fantastic!
Or a lighthouse in 1-tile lake. How useful it is for people there...
