### ISSUE TITLE
The AI offers or asks for multiple copies of world maps

### ISSUE THREAD

**Issue by JamesNinelives** [LoneGazebo/Community-Patch-DLL#7185]
_1. Mod version (i.e Date - 4/17):_
10/7

_2. Mod list (if using Vox Populi only, leave blank):_
Community Events (v. 5)
Civ names by policies (v. 8)
Historical Religions (v. 55)
Krazjen's Great Writers (v. 1)
Quick Turns (v. 10)
Really Advanced Setup (v. 15)
Unique Cultural Influence (v. 4)

_3. Error description:_ 
From Military Science onwards (when you are able to trade world maps), the AI regularly offers some strange trade deals. This happens either during their turn or sometimes if you put something on your side and ask 'what do you want for this?'. Specifically they will ask for or offer (sometimes both) multiple copies of your world map or theirs. It appears as one item, but if you click to remove the item from the deal, you will find it remains but the deal value changes (implying the offers are stacked on top of each other somehow).

_4. Steps to reproduce (optional):_
Load save, press 'next turn'. You should get an offer from The Ottomans involving multiple map trades.

---------------------------
Supporting information:

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[James Ninelives_0331 AD-1555.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5505862/James.Ninelives_0331.AD-1555.zip)

4. Screenshots (optional):
![20201107181522_1](https://user-images.githubusercontent.com/61379041/98457381-a4aae500-21c1-11eb-80c9-308dd5191d95.jpg)
![20201107181526_1](https://user-images.githubusercontent.com/61379041/98457382-a8d70280-21c1-11eb-8fc1-16a95103b2fe.jpg)
![20201107181529_1](https://user-images.githubusercontent.com/61379041/98457383-aaa0c600-21c1-11eb-9a36-0ef6593eb860.jpg)
![20201107181532_1](https://user-images.githubusercontent.com/61379041/98457384-ab395c80-21c1-11eb-8391-35304e9b7507.jpg)

**Comment by JamesNinelives** [comment]
Here's a save from an unmodded game. Same thing, click End Turn and you should get a trade offer from Portugal where they ask for two copies of your world map.

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5506328/QuickSave.zip)

**Comment by bukowa** [comment]
There's a bug where you can trade the world map all over again.

1. Trade world map.
2. Don't exit "trade" screen"
3. Trade world map.
4. The value is the same.
5. Exit "trade" screen.
6. Trade world map.
7. The value is lowered but there's a value.

**Comment by Amecareth002** [comment]
It happened to me. I was trading for a city with Venice and by removing a luxury resource from the deal then asking again, Venice would repeatedly add another "instance" of world map to the deal AND reduce the amount of gold they ask. I effectively removed all the gold they asked, which was about 9k

**Comment by ilteroi** [comment]
funny one. fixed.
