### ISSUE TITLE
EUI previews the old city distance

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#719]

**Comment by LoneGazebo** [comment]
What do you mean?

**Comment by Radost** [comment]
![8930_2015-10-29_00013](https://cloud.githubusercontent.com/assets/1131228/10816441/a8672e6c-7e54-11e5-997d-ccaf368f523c.png)
Also, with the new distance value there is a high possibility of non-workable tiles.

**Comment by LoneGazebo** [comment]
The orange lines indicate city working radius, not city distance, though, correct?

**Comment by Radost** [comment]
It indicates both.
