### ISSUE TITLE
10-7-2 Borobudur not upgrading missionaries anymore

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#7190]
Upon completition of the wonder, existing missionaries (with 1 charge left) don't gain the promised additional spread action. In previous version they used to correctly upgrade from 1 out of 2 charges to 2 out of 3 charges left.

The two free missionaries coming with Borobudur also spawn with 2/2 charges only.

Newly bought missionaries correctly show as 3/3.

**Comment by legenciv** [comment]
Prophets are also not getting the extra conversion from the Wonder.

**Comment by oalzubbi** [comment]
I am seeing the missionary issue in the 12-1-3 version as well.

**Comment by RecursiveVision** [comment]
@ilteroi

**Comment by Maxxim69** [comment]
Confirm issue not fixed as of version 12-1-3.
See also #7139

**Comment by ilteroi** [comment]
duplicate
