### ISSUE TITLE
10-7-2i - Nau can sell exotic cargo to any civ

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7192]
_1. Mod version (i.e Date - 4/17):_
10-7-2 - iteroi dll

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Normally Naus can only sell their cargo to a CS, but now they can sell it to any foreign civ. This sell does not create a feitoria as far as I can tell.

_4. Steps to reproduce (optional):_

![image](https://user-images.githubusercontent.com/20593976/99155152-07e1bf00-267b-11eb-89dc-bd1252cda76b.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I believe it has always been this way?
