### ISSUE TITLE
10-7-2i - Governor doesn't factor in unhappiness when considering food

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7193]
_1. Mod version (i.e Date - 4/17):_
10-7-2i

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
See the before and after screenshots. I have my city on production gov, but several mines are unworked in favor of water tiles. The reason is, the governor thinks I need this food. However, this is a trick of the massive unhappiness penalties I'm currently getting, in reality I don't need food at all. When I manually reassign, my city is perfectly good, but with a significant production boost.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/99157402-15ed0b00-268e-11eb-8851-de495f5f2eac.png)

![image](https://user-images.githubusercontent.com/20593976/99157404-2a310800-268e-11eb-835a-ffaa8bd38643.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
This happens more commonly in puppets, which is a huge problem.
