### ISSUE TITLE
10-7-2i - Ambassadors are requiring 3 paper instead of 2

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7194]
_1. Mod version (i.e Date - 4/17):_
10-7-2i (iterois dll)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Looking at this, it looks like ambassadors are consuming 3 papers instead of 2.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/99161535-e4d60000-26b8-11eb-9bfb-7ac860d95df4.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
Pretty sure you have 2 more ambassadors queued up to be built in your cities. That's why it says 4 (+2) ambassadors. That makes 6 so explains why 12 paper is used.

**Comment by Stalker012345** [comment]
I think your right, alright one less thing to worry about. I'll close it up.
