### ISSUE TITLE
10-7-2 - Swapping naval units also swaps out the garrison

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7195]
_1. Mod version (i.e Date - 4/17):_
10-7-2 (both regular and iteroi dll)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
If you have a naval unit in water, and swap it with a naval unit in a city, if there is a garrison in the city, the garrison will also embark to perform the swap. Normally the system is smart enough only to swap the naval unit.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
fixed
