### ISSUE TITLE
10-7-2i - Destroyers still do not have the See Submarine Promotion

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7196]
_1. Mod version (i.e Date - 4/17):_
10-7-2 (iteroi dll)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Destroyers still can't gain the ability to see subs. Looking at this, I think the promotion is linked to the 75% sub bonus promotion, but destroyers get the 33% one...which may be the issue.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/99161712-945fa200-26ba-11eb-9ceb-6bfb2d498319.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@Stalker012345 What is the intended behavior?
