### ISSUE TITLE
question for recursive

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7197]
human players get a warning when they have too many unit near an AI players' border, but does this apply between AI players as well?

because at the moment unit positioning doesn't take into account possible diplomatic repercussions.

**Comment by RecursiveVision** [comment]
I believe so; there's code for it. And it doesn't take this into account; I've mentioned this before but you said it would be a lot of work to implement checks for it.

**Comment by ilteroi** [comment]
yeah that is true, i don't have a good solution here except removing the diplo penalty for AI vs AI.

**Comment by Mileslewis** [comment]
Humans can also ask AIs to remove troops from their borders.

**Comment by azum4roll** [comment]
> 
> 
> Humans can also ask AIs to remove troops from their borders.

But do AIs suffer a global penalty if they declare war on the human after making the promise?

**Comment by RecursiveVision** [comment]
> > Humans can also ask AIs to remove troops from their borders.
> 
> But do AIs suffer a global penalty if they declare war on the human after making the promise?

Yes.
