### ISSUE TITLE
Some religious buildings are not available for purchase after chosen as a belief

### ISSUE THREAD

**Issue by Salvador2930** [LoneGazebo/Community-Patch-DLL#7199]
_1. Mod version (i.e Date - 4/17):_
10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Some added religious buildings, specifically Jinjas and Auls, are not selectable. Other religious buildings are. 

_4. Steps to reproduce (optional):_
Was playing as Rome, selected Auls with first prophet, but Auls were not purchasable. Orders were selectable.

Played as Rome again, selected Jinjas and Auls, neither was selectable. 

Played as Rome again, Jinjas were not selectable.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5543570/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): 
[Augustus Caesar_0099 BC-0400.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5543569/Augustus.Caesar_0099.BC-0400.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): 

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
You are using a mod?
