### ISSUE TITLE
10-7-2i Coop War

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#7200]
I agreed with Japan to declare war on Russia in 10 turns. Once the timer is over, at the start of my turn, I get a notification that Oda declared (missing the opportunity to do that on his turn) and I'm automatically dragged into the war, without the old window where it was possible to go back on my given word.

Bug or feature? I actually like it, you don't get the same opportunity to double cross your ally on defensive pacts afterall, but can't remember a patch note about it.

While we're at it, some sort of diplomatic reminder about my dow pact situation with other AIs would be welcome (something along the lines of "you agreed to go to war together in 10 turns" over my friend portrait)

**Comment by RecursiveVision** [comment]
Feature. Glad it's working correctly in your case!
