### ISSUE TITLE
10-7-2i - Combat Viewer Strength Incorrect

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7202]
_1. Mod version (i.e Date - 4/17):_
10-7-2i

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The combat strength that is calculated looks wrong on both sides. I expect higher numbers for each unit.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/99603612-48b63c80-29c9-11eb-82de-051d38c2cc0b.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I hate the combat viewer.

**Comment by Stalker012345** [comment]
> I hate the combat viewer.

Preach it brother! But at least for the skirmishers, I don't think its just the viewer, the strength calculation looks off. Another example:

![image](https://user-images.githubusercontent.com/20593976/99840755-c184d800-2b32-11eb-92ae-19da1113a3dd.png)

The strength of the unit looks to be pulling from the CS instead of the RCS for a ranged attack.

**Comment by LoneGazebo** [comment]
second one i'm not sure - looks like a missing tooltip for another modifier...

**Comment by LoneGazebo** [comment]
ran a quick test and the code is working correctly, so all i can imagine is that there are some modifiers that aren't being reported in the TTs.

**Comment by LoneGazebo** [comment]
i'd need to dig through your save

**Comment by Stalker012345** [comment]
Ok here is another example and this time I gave you the saved game. It looks like the defense bonus for skirmishers is a bit screwy.

![image](https://user-images.githubusercontent.com/20593976/99865661-f0ba3a00-2b70-11eb-92b9-b77376bf9266.png)

[Combat Viewer Issue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5576895/Combat.Viewer.Issue.zip)

**Comment by Stalker012345** [comment]
Ok something is seriously screwy. Not only was this Infantry's strength through the roof, but when my plane was intercepted, the infantry actually healed damage.

![image](https://user-images.githubusercontent.com/20593976/99869435-9af58a00-2b90-11eb-8ceb-dabde8bc1be6.png)

**Comment by Stalker012345** [comment]
In this one, the defender strength properly reflects the percentages given. But the attacker's strength is much too low, I am only getting 26% of the 71% in total bonuses

**Comment by LoneGazebo** [comment]
for the second one, makes me think that the 'near great admiral' bonus was refreshing in the UI but not in the code.

**Comment by LoneGazebo** [comment]
Alright...I think I've solved part of it. There were some caching issues tied to the UI, and some inconsistencies based on assumed 'attack plot' for the UI versus the actual calculations.

**Comment by LoneGazebo** [comment]
not sure about the infantry one, i'd need to look at that more specifically.

**Comment by Stalker012345** [comment]
> for the second one, makes me think that the 'near great admiral' bonus was refreshing in the UI but not in the code.

Just confirming that I was able to replicate this with another battle. Moving the GA into and out of the battle updates the percentage UI but not the actual strength.

**Comment by Stalker012345** [comment]
> second one i'm not sure - looks like a missing tooltip for another modifier...

Looks more closely I now agree with it, it looks like the defense malus from medic is not being factored in to the UI on that screenshot.
