### ISSUE TITLE
10-7-2i - Production Unhappiness Penalty does not match Happy UI when at 50%

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7203]
_1. Mod version (i.e Date - 4/17):_
10-7-2i

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
My guess is this is due to a fractional rounding error. So the UI says that I am happy, no penalty. However, the city's production is still receiving a very large (-75%) penalty.

Is the penalty normally that large for global unhappiness by itself?

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/99607825-40163400-29d2-11eb-8ead-f0db9452d7b7.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
War Weariness?

**Comment by Stalker012345** [comment]
Hmm... possible, does WW normally show up as a unhappy penalty to production? If so than that is the likely culprit.

**Comment by LoneGazebo** [comment]
Was the city unhappy, then you adjusted things this turn to make it even?

**Comment by LoneGazebo** [comment]
Looking at the code that's the only thing I can see - I cache the happiness delta for speed every turn.

**Comment by Stalker012345** [comment]
I don't believe so but hard to remember at this point. I'll keep an eye out for it.

**Comment by Mileslewis** [comment]
Well I often see it not updating the production penalty until the end of the turn. Pretty sure the penalty is adjusted before the production actually triggers though.

You must have made a big adjustment this turn for this to be the case though.
