### ISSUE TITLE
10-7-2i - (promotions) - AA Guns not going full interception

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7204]
_1. Mod version (i.e Date - 4/17):_
10-7-2i

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Looks like AI AA guns are choosing base promotions over the interception ones....which I would consider a mistake. Its not just 1, I've seen it pretty consistently.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/99621220-f1c25e80-29ec-11eb-965f-e9acb97b3653.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
Careful to not put this too high unless you want destroyers/missile cruisers to always go interception as well. iExtra*=0.3 or 0.4 should be plenty.
