### ISSUE TITLE
10-7-2i - Skirmisher Doctrine treating Desert as "Rough Terrain" for penalties.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7207]
_1. Mod version (i.e Date - 4/17):_
10-7-2i

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Sorry I didn't get a proper screenshot for this one, it wasn't until later I realized it was a bug. I am seeing chariot archers on desert get -20% for rough terrain, instead of the +40% for open. Its not a UI bug, the damage is definately lower.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Is it flood plains? It's been treated as rough terrain for skirmisher doctrine since it was introduced.

**Comment by Stalker012345** [comment]
Nope, flat boring desert.

**Comment by LoneGazebo** [comment]
desert has a move penalty. that makes it 'rough.'

**Comment by Mileslewis** [comment]
Don't Chariot Archers also get increased movement cost in 'rough' terrain? Pretty sure this doesn't include desert. Personally I think flat desert is 'open'.

**Comment by RecursiveVision** [comment]
@LoneGazebo I thought "rough terrain" meant hills, forest or jungle?

**Comment by LoneGazebo** [comment]
@Stalker012345 how's the unit panel stuff on the latest?
