### ISSUE TITLE
10/7 - Strange work boat movement issue

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7208]
_1. Mod version (i.e Date - 4/17):_ 10-7-2 + ilteroi patch

_2. Mod list (if using Vox Populi only, leave blank):_
Improved lakes

_3. Error description:_ 
This work boat uses all movement to move one tile. Possibly related to the odd river setup around the capital?
![image](https://user-images.githubusercontent.com/59859911/99742819-4b389500-2aa2-11eb-8364-e6fa408aa661.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
That's surely a weird forest tile southeast of Berlin...

**Comment by ilteroi** [comment]
maybe a river crossing along the coast. map issue

**Comment by silentreply** [comment]
@azum4roll Could this be specific to communitas? I've never seen this in particular happen but I have occasionally seen some weird looking coastal river tiles like above. This is with v2.1 (I think), whatever the latest one is.

**Comment by azum4roll** [comment]
I guess that could happen, when the ConnectPolarSeasToOceans function converts a river tile into ocean.
