### ISSUE TITLE
Minutemen Tech Changed

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#721]
http://forums.civfanatics.com/showthread.php?t=539387&page=4
Bottom Posts

 Originally Posted by ecgopher 
I'm assuming this is a bug/accident but minutemen got moved to replaceable parts?!

Strgivir:  Yep, and obsolete at Rifling.

**Comment by LoneGazebo** [comment]
I already fixed. Was an oversight when doing an SQL update.
G
