### ISSUE TITLE
wild AI deals

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7214]
so i just took a look at the deal history panel for the very first time and it's astonishing what the AI players will do among each other. i stopped them from importing and exporting the same resource simultaneously, but there are many other weird deals:

![image](https://user-images.githubusercontent.com/1358966/99907363-b5d51500-2cdc-11eb-9f73-ad9d2bf72795.png)

![image](https://user-images.githubusercontent.com/1358966/99908947-d2297f80-2ce5-11eb-8f54-11d1443292d8.png)

![image](https://user-images.githubusercontent.com/1358966/99909101-ce4a2d00-2ce6-11eb-8f66-a7667caa2599.png)

![image](https://user-images.githubusercontent.com/1358966/99909119-eae66500-2ce6-11eb-81c0-478fc4697059.png)

a gift?

![image](https://user-images.githubusercontent.com/1358966/99909060-7d3a3900-2ce6-11eb-960d-16f1625f614f.png)

![image](https://user-images.githubusercontent.com/1358966/99909076-a1961580-2ce6-11eb-855f-0324f3ba15df.png)

should buying a tech with GPT even be allowed?

![image](https://user-images.githubusercontent.com/1358966/99909144-1e28f400-2ce7-11eb-970b-9f787da97933.png)

bismarck had already lost some wars against the much stronger aztecs ... so yes he hated them but this was suicide.

**Comment by RecursiveVision** [comment]
@ilteroi For the last one I think you've misinterpreted it - Bismarck was paying Ramesses to declare war, not the other way around. :)

AIs can gift a tech as part of C4DF gifts, this was intended by Putmalk.
