### ISSUE TITLE
Strategic Monopolies don't work after reloading the game

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7215]
Patch: 10-07-02

Strategic Monopolies aren't doing anything when you reload a game. Seems like you need to either gain or lose a monopoly (of any kind) in order for it to update so that you start getting the benefits you should have.

**Comment by Mileslewis** [comment]
Also this is still quite a major issue: #7120 
And I've just realised it only happens when you have Colonialism (Imperialism Policy).

**Comment by bukowa** [comment]
I also cannot see strategic monopolies. 
![mspaint_L1e9oq5Sa5](https://user-images.githubusercontent.com/38087302/101238603-93ca9200-36e1-11eb-956a-bb316a779ec2.png)

![mspaint_ieVg3KXX02](https://user-images.githubusercontent.com/38087302/101238606-962cec00-36e1-11eb-931a-4ab59006fd7c.png)

![mspaint_mw6xgu8za7](https://user-images.githubusercontent.com/38087302/101238608-9927dc80-36e1-11eb-8c1f-cfae8e7dba9e.png)


**Save game:**
[AutoSave_0274 AD-1808.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5646774/AutoSave_0274.AD-1808.zip)

**Comment by RecursiveVision** [comment]
@bukowa You need at least 25% to have a strategic monopoly...

**Comment by bukowa** [comment]
Yes but it's not the case in my post. You can see the coal and horses
visible in the first screen but after switching to strategic monopolies
there are only horses. Also all the other resources like iron etc are not
visible at all.

sob., 5 gru 2020, 16:10 użytkownik RecursiveVision <notifications@github.com>
napisał:

**Comment by RecursiveVision** [comment]
Looks like it only shows up under Strategic Monopolies if a player actually has a monopoly.

**Comment by bukowa** [comment]
Yes is this a big or a feature? Also other resources are not shown at all.

sob., 5 gru 2020, 18:32 użytkownik RecursiveVision <notifications@github.com>
napisał:

**Comment by bukowa** [comment]
Oh sorry they are indeed visible my bad. Should i create different issue
about the 25% visibility?

sob., 5 gru 2020, 18:41 użytkownik ama bamo <pythoncontrol@gmail.com>
napisał:
