### ISSUE TITLE
10-7-2i (Tactical AI) - AI Warriors not grabbing obvious Ruins

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7216]
_1. Mod version (i.e Date - 4/17):_
10-7-2i

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The previous turn as I came upon this scene, the northern Warrior was present on the Lapis hill, which is in full view of the ancient ruin. However, the AI did not immediately go for the ruin, which allowed me to snag it.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/99934829-bdb8a780-2d24-11eb-858f-e817aaad8aec.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
hmm. depends on whether the warrior was a scout. if not it can be recruited for other tasks with higher prio.

**Comment by Stalker012345** [comment]
I can't think of much that would be a higher priority than a ruin. I would
rather grab a ruin and lose a barb camp with a quest on it than the other
way around. The only priority I could see as higher is if a city of yours
is literally in the process of falling.

**Comment by Tekamthi** [comment]
looks to me like it should go for that ruin too... alternatively war dec you once he sees you're gonna get it first?

**Comment by RecursiveVision** [comment]
Doesn't make sense to declare war over something you can just snag yourself.

**Comment by Tekamthi** [comment]
true, though if i mis-clicked into those moves or something and was playing a no-save-scum game (ie standard hotseat ruleset over here) i'd at least consider it

**Comment by RecursiveVision** [comment]
Sure, but the AI should aim to make the optimal decision, not to misclick. :)

**Comment by ilteroi** [comment]
i made it so that the AIs won't spend ALL their gold on plot purchases

**Comment by RecursiveVision** [comment]
@ilteroi I gotta agree with the others that nearby ancient ruins should be a very high priority, especially in the early game.

**Comment by ilteroi** [comment]
you guys have no idea of the disproportionate effort involved here

**Comment by RecursiveVision** [comment]
I guess I'll label this as "not going to fix" for now then.

**Comment by RecursiveVision** [comment]
Seems was fixed. Thanks, ilteroi. :)
