### ISSUE TITLE
Some Corporations missing

### ISSUE THREAD

**Issue by Gargamelli** [LoneGazebo/Community-Patch-DLL#7217]
_1. Mod version (i.e Date - 4/17):_
10-7-2

_2. Mod list (if using Vox Populi only, leave blank):_
CP v.94
CP Balance Overhaul v.13
CS Diplo Mod for CBP v.28
C4DF - CBP v.11
More Luxuries CBO 5-14b v.155
CP Balance Overhaul Comp. Files v.1
Community Events v.5
Promotion Icons for VP v.3
UI Promotionn Tree v.22
Less Ice On Maps v.101
Really Advanced Setup  v.15
Subkritact's Events & decisions v.3

_3. Error description:_ 
For some reason, I can't build Centaurus, Fireaxis, and Armeier corporation headquarter.
Btw building the Great Wall wonder wasn't possible either.
Played nation: The Shoshones.
![Civ5_Corp](https://user-images.githubusercontent.com/74968138/100096013-ae884580-2e5b-11eb-8641-ad976d55a260.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Gargamelli** [comment]
Obviously there is much more going wrong here:
![Civ5_StrangeHappiness](https://user-images.githubusercontent.com/74968138/100108732-63762e80-2e6b-11eb-8a51-dfaf2def9182.jpg)
371 happy against 317 unhappy people results in 58% happiness.
Bad; the mods I've used seemingly don't work with this CP version anymore (worked w/o problems gefore).

**Comment by Mileslewis** [comment]
You need certain resource monopolies to build each Corporation.

For happiness if you have equal happiness to unhappiness it will be at 50% so 58% there is correct.

**Comment by Gargamelli** [comment]
_You need certain resource monopolies to build each Corporation._
I missed that, thanks!
_For happiness if you have equal happiness to unhappiness it will be at 50% so 58% there is correct._
IIRC in the CP version I've got before, unhappiness was calculated in a different way.
(In may example  it would have been 117% happiness (371/317)) 
Let's see how I can handle this. Distress wasn't such an issue before I think.
Thanks again
