### ISSUE TITLE
10-7-2i (Strategic AI) - AI not settling high resource tundra area

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7219]
_1. Mod version (i.e Date - 4/17):_
10-7-2i

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Something I have now seen 4 games in a row. Communitas_79 maps like to generate these pockets of tundra that have very nice resources. This is a good city spot that the AI ignores pretty much all game. I have noticed its generally next to authority type civs, so my guess is they stop natural expansion after X point.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/100132979-cce64500-2e4b-11eb-9d19-4bf7bf810553.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Padre19** [comment]
And AI not settling in desert.

**Comment by gamask** [comment]
I wouldn't settle there either. Not enough food.

**Comment by Stalker012345** [comment]
> I wouldn't settle there either. Not enough food.

There is a spot there that gives you 3 sheep and 2 deer, plenty of food to make a solid city, especially with all the hammers it has access to.

**Comment by ilteroi** [comment]
well there are two hard conditions for the AI to settle a plot:

* the score must be better than 2/3 of the average settle score of all plots at the beginning of the game
* there must be at least 4 food and 3 hammer plots within the second ring

it's probably the first one that applies here. you can play with the relative weight of yields in CoreChanges.sql (around line 300). changes will only affect new games though.

**Comment by Stalker012345** [comment]
> * there must be at least 4 food and 3 hammer plots within the second ring

Does this mean literally 4 food and 3 hammers within the second ring, or if not what defines a "food plot" and a "hammer plot"

**Comment by ilteroi** [comment]
plots that provide at least one production or food. a plot can be in both categories.

**Comment by Stalker012345** [comment]
Ok last (hopefully) question. Does the settle score look at:

1) Terraforming: Okay what a plot will be after its improvement is applied.

2) Tech/Policy benefits: Aka the natural yields resources get from techs and policies.

Another way to ask this, does the settling score for things change over time, or is it set at the beginning of the game?

**Comment by ilteroi** [comment]
it looks at the natural yields and makes some assumptions: +1 food from lighthouse,

**Comment by Stalker012345** [comment]
> it looks at the natural yields and makes some weak assumptions: +1 food from lighthouse, +1 hammer from mines, +1 food from farms. that's all, iirc

Ok, that definately helps explain it. It means the AI undervalues things like deer or sheep whose base yields are okay but do get some good value adds through terrain and buildings.

**Comment by ilteroi** [comment]
ok i checked, they do consider possible improvements on resources.

but there was a bug in the threshold calculation, so watch this in the next version.
