### ISSUE TITLE
tooltip stuff

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#722]
not on the hotfix so don't know if you caught this stuff but:
Hexxon Refineries Inc does not describe its effect on Factories in the tooltip
Hexxon Refineries Office is missing a space between 'every' and 'three' in the tooltip

**Comment by LoneGazebo** [comment]
I'll take a look.

**Comment by LoneGazebo** [comment]
Ah, that's a leftover bit from an early build - I'll remove (shouldn't have that bonus, as it gets resources instead).
