### ISSUE TITLE
CS influence

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#7220]
Patch: 10-07-02

As a founder of religion, if you are allied with a city-state that has the same religion as you, your influence does not decay.

**Comment by RecursiveVision** [comment]
Can happen if playing Greece or Friendly personality.

**Comment by Padre19** [comment]
It always happens. It doesn't matter the civilization or the personality of the CS.

**Comment by Stalker012345** [comment]
I believe this was introduced several patches ago to provide a little more benefit to spreading religion. I don't think it was a not decay thing, but a minimum influence value. Could be wrong but I very much remember the discussion at least.

**Comment by SuperNoobCamper** [comment]
I had this in my current game too, CS following my religion (Playing Inuit) influence decays by 0 and rests at 0 so i don't lose any influence with time with CS following my religion no matter what personality they are and what policies i use (i went Authority, fealty and Imperialsim).

**Comment by RecursiveVision** [comment]
Duplicate issue
