### ISSUE TITLE
CTD playing Denmark in early game.

### ISSUE THREAD

**Issue by dostillevi** [LoneGazebo/Community-Patch-DLL#7221]
_1. Mod version (i.e Date - 4/17):
10-7-2 with Ilteroi's latest .dll

_2. Mod list (if using Vox Populi only, leave blank):_
All of Vox Populi and:
(7z) Promotion Icons (Patch for VP(7-29))(v. 1)
Archaeology Aesthetic Adjustments (v. 1)
Civ Names by Policies (v. 8)
InfoAddict (v. 22)
Quick Turns (v. 10)
UI - Filters in Trade Route Overview (Vox Populi) (v. 1)

_3. Error description:_ 
Crash to windows immediately on resolution of spearman combat across river with barbarian near my capital. Frustratingly, this happened several turns after my last save, and the AI made different decisions after loading that save so the crash is not reproducible. The barbarian was approaching my capital maybe 4 or 5 turns after this save, and I fought it back with the spearman my capital is producing over the river just north of the capital. The game crashed immediately after the combat resolved.

_4. Steps to reproduce (optional):_
If possible, keep attacking Moscow. The AI moved up from south of moscow to threaten my archer, and after moving my archer to the east, the AI moved their warrior out of moscow to attack. This left me able to capture moscow at the expense of the archer. This isn't related to the barbarian, but when I reloaded the attached save, the ai unit from the south moved to a different tile instead of threatening my archer, and it took several turns longer to capture moscow. Nothing else played out the same either - the barbarian never approached my capital from the north. So, unfortunately, this may not be a reproducible crash.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5594213/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[AutoSave_0070 BC-2250.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5594214/AutoSave_0070.BC-2250.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5594217/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by ilteroi** [comment]
callstack says the problem is at:

CvGameCore_Expansion2!CvLuaGame::lGetAdvisorCounsel+0x27 [d:\sources\civ-vp\cvgamecoredll_expansion2\lua\cvluagame.cpp @ 2111]

seems to be some lua issue. maybe with one of your extra mods, but i don't play with advisors, so it could be in base VP as well.

**Comment by RecursiveVision** [comment]
@ilteroi There's been a recurring issue for a long time where attempting to open the advisor panel sometimes causes a CTD. From what I remember it tends to happen more often when you're at war with other civs.

**Comment by dostillevi** [comment]
@ilteroi , is there a way to disable advisors? I never look at them.

**Comment by dostillevi** [comment]
@RecursiveVision Interesting. I was at war with Russia at the time. Maybe it was related to an advisor changing their recommendation following the barbarian combat? Also the barbarian didn't die in the combat immediately prior to the crash, just took damage.
