### ISSUE TITLE
(Question Only) Question about Happiness AI

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7222]
I realized more of the experts are going to look here, so I thought I should post this here.

I could use your all's advice to understand how complex a problem I would be dealing with for a modmod.

I don't want to get too technical at the moment, just looking for a general understanding.

Lets say for the sake of argument, a modmod turned all iliteracy, boredom, distress, religious unrest, and poverty calculations for each city to 0. Isolation, Urbanization and Pillage unhappiness values remain the same. Then each city was given an amount of unhappiness based on its set population + some static number. Public Works would still provide +1 happy, and would also reduce unhappiness by 2. Other buildings and policies that provide happiness work as normal. All of the bonuses and penalties of local and global happiness are still intact.

At a baseline, how would the AI react to such a change? Would the AI know that iliteracy is 0 and therefore not prioritize libraries because of "phantom happiness flavors".... or is the AI more hardcoded to reduce iliteracy and that would have to be adjusted?

If a city was greatly unhappy, would the AI understand innately to build the Public Works building....or would I need to add some "flavor" to the building to make the AI understand to use it?

A lot of what I'm getting at is this simply a matter of shifting existing values and flavor options with the AI or do I need to create an entire new logic set to make it understand this kind of system.

Thank you for any insight you can provide.

**Comment by LoneGazebo** [comment]
The function for the AI checks for actual numbers of unhappiness to prioritize buildings. So if that priority went away, illiteracy for example, they would not artificially focus on buildings to fix that issue. So it should be plug-and-play. That's how I designed it anyways.

**Comment by Stalker012345** [comment]
> The function for the AI checks for actual numbers of unhappiness to prioritize buildings. So if that priority went away, illiteracy for example, they would not artificially focus on buildings to fix that issue. So it should be plug-and-play. That's how I designed it anyways.

So the AI would automatically know to still build things like grocers, circuses, and public works? (aka things that still provide a happiness benefit).

If I were to change a building to now either provide happiness or to remove unhappiness straight up, I assume I would need to add a happiness_flavor to the building for that to work, would I need to do anything else for the AI to recognize that building is good to relieve unhappiness?
