### ISSUE TITLE
10-7-2i - Combat Viewer consistently undervalues GDR strength

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7223]
_1. Mod version (i.e Date - 4/17):_
10-7-2i

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Could be due to the collossal trait, but the GDR combat screen is never right. I will consistently kill units the viewer thinks I'll only do 60 ish damage to

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
It's the free ranged attack. No idea how much damage it's supposed to do though which would be good to know.
