### ISSUE TITLE
New version soon?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7224]
I was going to start making some changes again, but I held off because @LoneGazebo you said there was a new version coming soon...

Meanwhile I see ilteroi has continued to make changes. Is a new version upcoming or is it all right to begin making more edits? I don't want to be delaying a new version considering it's been nearly two months since the last release.

**Comment by RecursiveVision** [comment]
I suppose I can simply make changes but you can wait till next version to merge them, if there's an issue. :)

**Comment by ilteroi** [comment]
you can always make changes, just make it clear whether they should be merged :)
