### ISSUE TITLE
Barb City Attack Hesitance?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7226]
@ilteroi, check out line 460 of CvTacticalAI.cpp:

```
					//barbarians don't care about cities much compared to normal players
					newTarget.SetAuxIntData( m_pPlayer->isBarbarian() ? 20 : 100);
```

Perhaps consider changing this? According to APLion in the forums, Barbarians were aggressive again after this - and it seems like Barbs focus on cities AFTER units anyway in the new order of priority, so there may not be much point in changing the "amount of caring" values.

Or perhaps change the check to `(MOD_BALANCE_CORE_BARBARIAN_THEFT && m_pPlayer->isBarbarian())` so that Barbs only have this increased hesitance if yield theft is enabled, as they want to stay alive to do that.

**Comment by ilteroi** [comment]
doesn't make a difference
