### ISSUE TITLE
AI plot buying behavior

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7229]
001, Russia, Buying plot, X: 25, Y: 50, Cost: 45, Balance (before buy): 55, Priority: 311
001, Morocco, Buying plot, X: 87, Y: 39, Cost: 45, Balance (before buy): 55, Priority: 355
001, The_Ottomans, Buying plot, X: 59, Y: 33, Cost: 45, Balance (before buy): 55, Priority: 377
001, England, Buying plot, X: 30, Y: 12, Cost: 45, Balance (before buy): 55, Priority: 377
001, Assyria, Buying plot, X: 51, Y: 52, Cost: 50, Balance (before buy): 55, Priority: 320
001, The_Inca, Buying plot, X: 23, Y: 25, Cost: 50, Balance (before buy): 55, Priority: 320
001, Songhai, Buying plot, X: 78, Y: 49, Cost: 50, Balance (before buy): 55, Priority: 320
001, Korea, Buying plot, X: 80, Y: 17, Cost: 50, Balance (before buy): 55, Priority: 320
001, Siam, Buying plot, X: 60, Y: 20, Cost: 45, Balance (before buy): 55, Priority: 355
002, Germany, Buying plot, X: 15, Y: 34, Cost: 45, Balance (before buy): 55, Priority: 355
002, Greece, Buying plot, X: 83, Y: 34, Cost: 45, Balance (before buy): 55, Priority: 355
002, Poland, Buying plot, X: 34, Y: 36, Cost: 50, Balance (before buy): 55, Priority: 320

this is the homeland log. notice all AIs immediately buying a plot around their capital. is this a good strategy?

in the first 100 turns they buy 66 plots in total, so ~5.5 per player.

**Comment by ASCII-Guy** [comment]
It's only a good strategy if there's no good tiles in the initial city ring, but the capital should be settled in a way that there's multiple good tiles in the initial city ring. It's way better to spend the gold on military units or workers.

**Comment by RecursiveVision** [comment]
If I have extra gold at the start, it almost always goes towards a building, Worker, or I save up for a unit/Wonder. Never spend it on plots that early, although I'd consider it for a Natural Wonder.

**Comment by JamesNinelives** [comment]
I find buying plots useful in cases where for example I'm in the jungle and there is a citrus tile within working distance. Generally my rule is that if I can gain 2 yields (e.g. 1 production, 1 gold) by purchasing a tile I do it.

That said, in this specific case I'd always invest in either a monument or shrine first. More useful.

**Comment by ilteroi** [comment]
they start with 50 and +5 gpt (on king at least)

they seem to buy mostly (only?) resource plots so i guess it's not too bad but i could block the plot buying while they are still in the "early expansion" phase.

**Comment by azum4roll** [comment]
America does want to buy plots though, I think.

**Comment by Mileslewis** [comment]
Nah, I would only ever buy an amazing tile like an atoll or a natural wonder. Maybe a lake if all my tiles were only 2 yields.
