### ISSUE TITLE
Right-Clicking Leader Select Screen Opens Bugged Civlopedia

### ISSUE THREAD

**Issue by straightflushin** [LoneGazebo/Community-Patch-DLL#723]
When I right-click a leader while setting up a game to open their Civlopedia page, an empty page opens that can't be closed out of. The only way to exit appears to be Alt+F4.

Using Full version + EUI

**Comment by Radost** [comment]
#432

**Comment by LoneGazebo** [comment]
Don't do this. It is a flaw in the way EUI handles mod files.
G
