### ISSUE TITLE
Deals and Demands screens do not function.

### ISSUE THREAD

**Issue by davidcyuan** [LoneGazebo/Community-Patch-DLL#7237]
_1. Mod version (i.e Date - 4/17):_
10-7-2 installer, CP v.94

_2. Mod list (if using Vox Populi only, leave blank):_
CP only

_3. Error description:_ 
In the deals or demands screens, clicking any resources or proposition commands does nothing. Dialogue box only says "Message are for AI."
![CivDealBug1](https://user-images.githubusercontent.com/38829845/100659073-b17cad80-3315-11eb-948c-4536cd976c44.png)

Hovering over AI in map screen displays a nil value error. "Assets\DLC\UI_bc1\Core\EUI_tooltip_library.lua2457: attempt to call method 'IsHasTradeAgreement' (a nil value)"
![CivDealBug2](https://user-images.githubusercontent.com/38829845/100659380-2cde5f00-3316-11eb-94b9-0c79413bf337.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by davidcyuan** [comment]
Save: [Greece Quick Mod.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5618522/Greece.Quick.Mod.zip)

Logs: [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5618509/Logs.zip)

Upon game testing, I believe the trade interactions work, but the UI is not displaying anything during the trade/demand screens.

**Comment by RecursiveVision** [comment]
That's odd. Will examine, when I removed all of the trade agreement code it worked fine, but I didn't test CP only.

**Comment by RecursiveVision** [comment]
@davidcyuan Did you have any installation issues? I downloaded the 10-7-2 autoinstaller and selected CP only, then searched the files. 'IsHasTradeAgreement' returns 0 hits - it's not supposed to be in the files at all, which makes me think you had some issues with your installation. 

![83ebd67f4f5d5cc24b9ae47355cae911](https://user-images.githubusercontent.com/66801010/100691511-e4936100-3356-11eb-8795-96abdb536741.png)

Try deleting the CP from your MODS folder, emptying your ModUserData folder and deleting the files from your cache folder, then reinstalling again.

**Comment by RecursiveVision** [comment]
Maybe it's an issue with EUI...

**Comment by RecursiveVision** [comment]
Okay on closer inspection it seems that you have an EUI_tooltip_library.lua file which is generating the error. The autoinstaller isn't adding a EUI_tooltip_library.lua file, so I'm guessing you're using the EUI version from CivFanatics?

**Comment by RecursiveVision** [comment]
I'm not sure of EUI's compatibility to begin with without the compatibility files, and I hadn't considered that the standard EUI mod would make that function call, so that explains the problem.

**Comment by RecursiveVision** [comment]
I can attempt a fix in the meantime.

**Comment by davidcyuan** [comment]
When I ran the AutoInstaller, I chose to install all the Vox Populi Mods under the assumption that I could choose CP only within the game. Was my assumption wrong, and is this the cause of the problem?

**Comment by davidcyuan** [comment]
After reading your responses and other information from the forums, I would like to ask some questions to make sure my understanding is now correct.

1) Is EUI a separate mod from CP?
2) Is EUI not installed as a mod, but as an piece within the core game files?
3) And as a result, when I chose upon installation to install all VP mods, did the installer install EUI into the core game files under the assumption that it would have access to all VP mods? So when I chose to create games using only the CP, the EUI was by default activated, and attempted to call methods and variables in VP, but not in CP?

**Comment by davidcyuan** [comment]
Here's a how I created games. Is this the cause of the problems?
![CivModScreen](https://user-images.githubusercontent.com/38829845/100696192-9c753e00-3358-11eb-85dd-b10497e7b377.png)

**Comment by RecursiveVision** [comment]
Delete the "UI_bc1" folder in Program Files (x86)\Steam\steamapps\common\Sid Meier's Civilization V\Assets\DLC and your game should work normally (don't enable the 6a mod however).

1 - EUI is a separate mod, however VP installs its own modified version of EUI.
2 - Yes.
3 - It's attempting to call functions that I deleted, thus returning a nil value. When the compatibility files are enabled, the UI_bc1 folder files are overwritten by the 6a) files, so this problem doesn't occur. However since you're running only the CP and not the compatibility files, it's running the base files in the UI_bc1 folder, which have not been modified to account for my deletion of the functions.

**Comment by RecursiveVision** [comment]
What I'd like to do is add an EUI compatibility files mod for the CP only version, thus overwriting the files and avoiding this issue.

**Comment by davidcyuan** [comment]
Upon rereading the installation instructions, here is my hypothesis of what is going on. If you could check my reasoning, it would be helpful.

1) I ran the installer, and chose to install all VP mods, under the (wrong) assumption that I can, in game, choose CP only.
2) The installer assumes I will run all VP mods, and therefore deletes the LUA of CP and CBO.
3) (This one I need help understanding). Somehow EUI is automatically enabled when I told the installer to install all VP mods. I don't know why this is how it works.
4) I setup the game with CP only, but for some reason EUI is enabled by default upon VP installation, and the EUI needs VP resources which are not in the game.
5) To fix this, I need to delete VP from the mods folder, delete the EUI folder within the core game files, and reinstall CP only. Deleting just the EUI folder doesn't work, since the installer deleted the LUA folder from my CP folder.

**Comment by RecursiveVision** [comment]
@LoneGazebo Wouldn't it be easier to just modify the UI_bc1 folder files instead of overwriting them like this?

**Comment by davidcyuan** [comment]
I'm curious why deleting the EUI files from the game assets fixes this issue. I was under the assumption the installer deleted the LUA files from the CP folder when I chose to install VP? So wouldn't I be now missing the LUA from CP?

**Comment by RecursiveVision** [comment]
Oh, right...it overwrites the LUA. I forgot about that 😓 

Okay, well delete the VP folders in your MODS folder AND the UI_bc1 folder, run the installer again and choose "Community Patch Only" this time - or play with the full mod. Up to you. :)

**Comment by davidcyuan** [comment]
Thanks so much, I'll do that. I'm kind of curious though, if the compatibility files removes function calls from EUI, what were those EUI function calls used for in the first place?

**Comment by RecursiveVision** [comment]
Unused deal items that were leftovers in the code.
