### ISSUE TITLE
CP/EUI install version

### ISSUE THREAD

**Issue by arievillo** [LoneGazebo/Community-Patch-DLL#7238]
No bugs just a question here.

Is it possible at some point we have a CP/EUI version (the one already included in the VP) playable?
Because in the installer there is only a CP/Non EUI installation option.

Thanks.

**Comment by RecursiveVision** [comment]
@LoneGazebo I think it'd be more or less OOTB compatible, given that all the DLL hooks are in the CP mod and not CBP/C4DF/CSD. This would also fix #7237.

**Comment by RecursiveVision** [comment]
We may have to move some text keys/etc. around, however...

**Comment by arievillo** [comment]
@RecursiveVision Thank you in advance for the response and effort to discuss a solution. Many players would be happy with this compatibility.

**Comment by LoneGazebo** [comment]
If you delete the LUA folder out of CP, that should give you EUI's interface exclusively, which is IIRC compatible?

**Comment by RecursiveVision** [comment]
@LoneGazebo I haven't tested it; however, EUI Compatility Files only work with the full mod, not just the Community Patch. Perhaps only the dependencies need to be adjusted?

Using only EUI is not currently compatible as I've modified the mod's version in the compatibility files and deleted some unused function calls.

**Comment by arievillo** [comment]
Using last CP from 12-1-3 install and legacy EUI whit the LUA trick i got this. For now.

![Sem título](https://user-images.githubusercontent.com/61036004/101208854-8e256b80-3651-11eb-9d92-0c1ecfe19b45.png)

**Comment by arievillo** [comment]
@LoneGazebo @RecursiveVision  Its possible to adjust only the VP EUI version to always work whit the latest CP? Isn't worth it?

**Comment by RecursiveVision** [comment]
Going to work on this soon.

**Comment by HellsingDarge** [comment]
Considering it was closed without explanation or follow up, I'd like to confirm the status of this request *here* (going from more recent comments in issues): it isn't planned and/or is abandoned?

**Comment by RecursiveVision** [comment]
May happen at an indefinite future time.
