### ISSUE TITLE
Reproducible CTD while clicking player civilization icon. (advisor)

### ISSUE THREAD

**Issue by bukowa** [LoneGazebo/Community-Patch-DLL#7239]
**_1. Mod version (i.e Date - 4/17):_**
10-7-2.exe auto installer - Vox Populi (including EUI)

**_2. Mod list (if using Vox Populi only, leave blank):_**

**_3. Error description:_** 
After clicking on this icon game crashes to desktop. I had this problem before and reinstalled the game. It still happens. No other mods installed. All mods that Vox Populi auto installer provided are enabled.
Clicking other Civilization that mine does not cause the crash. I also played before with Isabella and the same crash occured after some number of turns.

_4. Steps to reproduce (optional):_
1. Load save number 0-18 - you can click the icon everything works.
2. Load save number 19-20 - you can click the icon and game crashes.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

**1. Log files:**
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5622741/Logs.zip)

**2. Save game:**
[saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5622746/saves.zip)

**3. CvMiniDump.dmp file:**
Backed up, i don't know what inside that file and won't be uploading it publicly because of that. I can provide if requested.

**4. Screenshots (optional):**
Heres the icon to click to cause the crash:
![mspaint_RlScEFkbIb](https://user-images.githubusercontent.com/38087302/100746418-f4578780-33e0-11eb-9eb4-e1dae6b7e550.png)

I don't know if this is related but after i start the game launcher (not even the game) this happens:
![steam_9jvEEpjpZJ](https://user-images.githubusercontent.com/38087302/100745516-af7f2100-33df-11eb-8cd6-69093f30bcc1.png)

**Comment by RecursiveVision** [comment]
This has been a known issue for a while, happens upon clicking the advisor button.

**Comment by bukowa** [comment]
@RecursiveVision thanks for reply, should there be "known issues" somewhere?
