### ISSUE TITLE
Herbalist description

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#724]
As taken from Civilopedia: "City must have a nearby, workable Forest or Jungle tile in its borders".
Perhaps it's just me, but the wording seems to be a little too excessive with an unnecessary comma.  "City must have  workable Forest or Jungle tile in its borders" sounds a lot better to me.

Sorry to be nitpicking.

**Comment by Hokath** [comment]
"nearby" in ciV means within two tiles. Not sure if this is what G is going for as I haven't played enough games with it. Workable implies within your borders.

**Comment by LoneGazebo** [comment]
What's confusing about it? Nearby implies near the city you are trying to build it in, which is the restriction.

**Comment by Edaka** [comment]
As I see it, the terms "workable" and "in its borders" combined make "nearby" redundant. If it's workable, then it's not farther than 3 tiles away (is nearby).
