### ISSUE TITLE
Error loading savegames

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7244]
Seems something messed up savegames. I suspect I made an error somewhere, looking through my changes now.

**Comment by LoneGazebo** [comment]
Ilteroi nor I touched save memory. Probably a mismatched MAX_PLAYERS variable?

**Comment by LoneGazebo** [comment]
if you debug a crash it'll show you where in the loading process it crashes.

**Comment by RecursiveVision** [comment]
Think I found it. Missing a `kStream >>` line. Testing now.

**Comment by RecursiveVision** [comment]
Yep, works again! Sorry about that, could've sworn I wrote that correctly.

**Comment by LoneGazebo** [comment]
No worries. Penance will be helping me close the 200 some-odd issues we have on here. Vast majority are fixed or obsolete now. :)

**Comment by RecursiveVision** [comment]
Heh, alright. :)
