### ISSUE TITLE
Spain still gains Faith/Gold for founding cities

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7245]
Intended?

**Comment by LoneGazebo** [comment]
I believe so yes.

**Comment by LoneGazebo** [comment]
@pineappledan created the merge.

**Comment by pineappledan** [comment]
Spain gains yields on all tile acquisitions of any kind. This includes tiles gained through settling

**Comment by RecursiveVision** [comment]
Okay, just got confused because the notification that popped up was for "founding a city" not gaining tiles.
