### ISSUE TITLE
Possible to have more than -100% growth modifier.

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7248]
With a lot of unhappiness and penalty from being over supply cap, total growth modifier can go to over -100% growth. This is quite strange because in this state the more net food you produce the more negative food you will end up producing after the growth penalty. 

Capping overall growth penalty at -100% should fix this.

**Comment by RecursiveVision** [comment]
This bug just keeps returning...
