### ISSUE TITLE
Game crashes when selecting any ranged unit and mousing over a hostile city.

### ISSUE THREAD

**Issue by Fusha** [LoneGazebo/Community-Patch-DLL#7249]
_1. Mod version (i.e Date - 12/1):_ 12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Game crashes when selecting any ranged unit and mousing over a hostile city.

_4. Steps to reproduce (optional):_ In the provided save, selecting either the catapult or the composite bowman by Vatican City, and then mousing over Vatican City, will always make the game crash.

---------------------------
Supporting information:

1. Log files [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5630003/Logs.zip)

2. Save game: [auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5630019/auto.zip)

3. CvMiniDump.dmp file: [CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5630032/CvMiniDump.zip)

**Comment by ASCII-Guy** [comment]
003cf940 293b70e1 CvGameCore_Expansion2!CvFlavorManager::~CvFlavorManager+0x4 [c:\users\alex\documents\github\community-patch-dll\cvgamecoredll_expansion2\cvflavormanager.cpp @ 135] 
003cf958 541ea984 CvGameCore_Expansion2!CvModEventCityChoiceInfo::getEventResourceChange+0x31 [c:\users\alex\documents\github\community-patch-dll\cvgamecoredll_expansion2\cvinfos.cpp @ 10695]

**Comment by ilteroi** [comment]
not what i'm seeing ... but i've got it

**Comment by CyberPhy** [comment]
I am also getting this problem 

[Callstack.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/5632792/Callstack.log)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5632776/CvMiniDump.zip)

**Comment by kawyua** [comment]
The issue of crashing on hovering enemy cities is consistent and I can't play the game any further. hope the change will be save game compatible
like the logfile from cyberphy 

```
=[C] (-1): GetMaxRangedCombatStrength
C:\Users\Personal\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files\CoreLua\EnemyUnitPanel.lua (324): UpdateCombatOddsUnitVsCity
C:\Users\Personal\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files\CoreLua\EnemyUnitPanel.lua (3557): ?
=[C] (-1): ?
=[C] (-1): ?
```

i guess something went wrong here

[AutoSave_0073 BC-1080.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5636581/AutoSave_0073.BC-1080.zip)

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5636572/CvMiniDump.zip)

**Comment by LoneGazebo** [comment]
@ilteroi does your latest have the fix?

**Comment by ilteroi** [comment]
yes

**Comment by RecursiveVision** [comment]
@LoneGazebo You seem to have overwritten my latest fix. :)

**Comment by LoneGazebo** [comment]
huh. I did a merge.

**Comment by RecursiveVision** [comment]
oh, never mind, I see it further down in the commits list. My bad.
