### ISSUE TITLE
Non-EUI UI issues

### ISSUE THREAD

**Issue by Mzimoxs** [LoneGazebo/Community-Patch-DLL#7250]
My issue #6723 was closed without comment while none of the points I raised were adressed.

As of version 1/12/20 I can add another point: Spain displays the Inquisitor as a second UU, while the Hacienda doesn't show up.

**Comment by RecursiveVision** [comment]
Sorry, it was almost 6 months old and Gazebo had his label on it so I assumed it was obsolete. New issues will get more visibility, anyhow.
