### ISSUE TITLE
(12-1-1) CTD when UNIT_FIGHTER is attaking

### ISSUE THREAD

**Issue by GLop4** [LoneGazebo/Community-Patch-DLL#7251]
_1. Mod version (12-1-1)
_2. Mod list : Ingame Editor (v 39) only

_3. Error description: CTD when a UNIT_FIGHTER is attaking a warrior.

_4. Steps to reproduce (optional): Select the UNIT_FIGHTER. Attack the nearest warrior.

---------------------------

Attached:
- logs
- savegame (Edited)

The exact same scenario with (10-7-2) does not cause CTD

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5635930/Logs.zip)
[Napoleon_0001 BC-3960.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5635934/Napoleon_0001.BC-3960.zip)

**Comment by RecursiveVision** [comment]
@ilteroi Same issue?

**Comment by GLop4** [comment]
Fixed with (12-1-3)
