### ISSUE TITLE
AI over paying for strategics 12-1-1 / 12-1-3

### ISSUE THREAD

**Issue by CyberPhy** [LoneGazebo/Community-Patch-DLL#7254]
Version: 12-1-1
It looks like the AI is over paying for strategics again (4gpt 2 luxury's and 1 iron for two Horses)
![Capture](https://user-images.githubusercontent.com/21373332/101086969-98773500-357f-11eb-8f7e-ca256550c428.PNG)
)

**Comment by ilteroi** [comment]
they really want those horses ... can you remove all the stuff from the left side to see the deal value for the right side?

**Comment by CyberPhy** [comment]
@ilteroi Ok I removed the stuff from the left side and got a deal value of 1,134
![Capture](https://user-images.githubusercontent.com/21373332/101099964-b484d180-3593-11eb-8ebf-0d7dcd42b579.PNG)

**Comment by CyberPhy** [comment]
Here is a screenshot of the same problem from the latest hotfix 
![Capture](https://user-images.githubusercontent.com/21373332/101377048-5ac82400-387f-11eb-87e7-816d77be7e3c.PNG)

**Comment by CyberPhy** [comment]
![Capture](https://user-images.githubusercontent.com/21373332/101379539-62d59300-3882-11eb-8d1f-61511b60199f.PNG)
