### ISSUE TITLE
CTD Turn 231, unknown trigger

### ISSUE THREAD

**Issue by physicalmetallurgy** [LoneGazebo/Community-Patch-DLL#7258]
_1. Mod version (i.e Date - 12/1):_
12-1-1 (v94)

[CTD turn 231 12-4-2020.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5644928/CTD.turn.231.12-4-2020.zip)
 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Game is reliably CTD on this turn or just after; have tried 4 times, unable to reproduce cause exactly.  Crash has occurred while moving crossbowman, while panning across the map, or just at rest while considering what to do.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by physicalmetallurgy** [comment]
After posting this, I tried the stability improvement fix ilteroi posted today (12-4) in the forums, setting CORE_DISABLE_LUA_HOOKS to 1 in the CustomModOptions xml.  This did not fix the issue; I still experienced a CTD within a turn after loading that save again.

**Comment by ilteroi** [comment]
tried the latest hotfix? minidump?

**Comment by physicalmetallurgy** [comment]
Using the latest (12-1-3) fix seems to have solved the issue, no longer crashing.  Thanks
