### ISSUE TITLE
Unreasonable AI Aggression

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7260]
I've seen two reports so far of the AI being nonsensically aggressive, declaring war left and right. This would be a good time for the rework of diplomacy-related war logic I've been pondering.

If anyone has more reports to add on a pattern of unreasonable, self-defeating AI aggression, please add them to this issue. 

Logs and a savegame (preferably with no other mods required to play) would be appreciated.

**Comment by bukowa** [comment]
I think it's important to make a difference between what is an agression. Do you mean just declaring a war or military agression?
For example i experienced wars declared on me after trading world maps for big amount of gold per turn (50-100) + sometimes all their luxury resources. It looks logicial to me that they declared the wars after few turns. Their lands were far away and there was never any military agression from their side but the trade agreements were broken while they kept the world map 👍

**Comment by ilteroi** [comment]
bool HaveValidAttackTarget(PlayerTypes eEnemy) is ready for use

**Comment by RecursiveVision** [comment]
@ilteroi I'm pretty sure that's already in use everywhere, don't think that's the culprit.

**Comment by usadefcon1** [comment]
Arabia just declared on me with nothing to gain. Most likely a bribe from Songhai.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5686361/Logs.zip)

**Comment by RecursiveVision** [comment]
I think I've identified some of the problems, working on some adjustments. Watch this in the next version.
