### ISSUE TITLE
[10-7-2][UI] City state influence number can be confusing with "Open Door" resolution.

### ISSUE THREAD

**Issue by bukowa** [LoneGazebo/Community-Patch-DLL#7261]
Marking the issue to fill later.

1. My influence with city state is the same as other civilization.
2. Increase influence.
3. Other civilization influence is increased by the same value (on the city state screen).

<details>
  <summary>Template not filled yet</summary>
_1. Mod version (i.e Date - 12/1):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
</details>

![mspaint_W3fECA1F3c](https://user-images.githubusercontent.com/38087302/101238712-4dc1fe00-36e2-11eb-962b-cd558e791373.png)

**Save game:**
[AutoSave_0274 AD-1808.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5646776/AutoSave_0274.AD-1808.zip)

**Comment by bigcat88** [comment]
Open borders?

**Comment by bukowa** [comment]
Could you tell more?

sob., 5 gru 2020, 10:45 użytkownik bigcat88 <notifications@github.com>
napisał:

**Comment by azum4roll** [comment]
You're the contender.

**Comment by Mileslewis** [comment]
open door resolution from world congress means noone can ally that city state.

**Comment by RecursiveVision** [comment]
Looks like an Open Door resolution to me. It should just say 0 under "Contender" though...

**Comment by Mileslewis** [comment]
I think it's fine because its good to know who would ally them if it was repealed

**Comment by bukowa** [comment]
Ok, sorry for confusion and thanks for explaining. It can be confusing, but it's clearly not a bug.

**Comment by azum4roll** [comment]
Contender just means second place, which you're at. If you hover above the CS icon it should show how much influence you need to gain to surpass the current ally.

**Comment by RecursiveVision** [comment]
Under "contender" it shows the highest Influence total among all players, not counting the current ally. Since there's no ally because of the Open Door resolution, you show up there. 

You need to repeal the Open Door resolution to become the City-State's ally.
