### ISSUE TITLE
[10-7-2][UI] "Corporations & Monopolies" - monopolies tab is confusing.

### ISSUE THREAD

**Issue by bukowa** [LoneGazebo/Community-Patch-DLL#7262]
When switching to "strategic" or "global" view only active monopolies are visible but while in "All" everything is visible. I think it's confusing and it should be possible to sort "strategic" vs "global" and see them in the same way as they are in the "all".

![mspaint_L1e9oq5Sa5](https://user-images.githubusercontent.com/38087302/101238603-93ca9200-36e1-11eb-956a-bb316a779ec2.png)

![mspaint_ieVg3KXX02](https://user-images.githubusercontent.com/38087302/101238606-962cec00-36e1-11eb-931a-4ab59006fd7c.png)

![mspaint_mw6xgu8za7](https://user-images.githubusercontent.com/38087302/101238608-9927dc80-36e1-11eb-8c1f-cfae8e7dba9e.png)

**Save game:**
[AutoSave_0274 AD-1808.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5646774/AutoSave_0274.AD-1808.zip)

**Comment by LoneGazebo** [comment]
Strategic monopolies only apply above 25%.

**Comment by bukowa** [comment]
Turns out "Global" monoplies above 25% are not visible too. It's just confusing and not a bug, because "All" shows everything and when switching to "Global" or "Strategic" only active monopolies are visible. It's just confusing and not a bug.
