### ISSUE TITLE
Haciendas inconsistent with luxury bonuses

### ISSUE THREAD

**Issue by SpankMyMetroid** [LoneGazebo/Community-Patch-DLL#7263]
_1. Mod version (i.e Date - 12/1):_Most recent 12/5-3?

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I am very surprised this wasn't reported already considering people are probably itching to play spain.
On unlock, Haciendas give +2G per adjacent luxury, with base 1G and 1BG. In screenshot one, despite being next to an improved tea, no extra gold. In 2, bizarrely the improved lapis lazuli is counted as a bonus resource, granting food instead of gold. 3 is an example of the haciendas working correctly. 4, again, a hacienda next to perfume without the gold bonus.  

_4. Steps to reproduce (optional):_
Play de spain. Communitas. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20201205211302_1](https://user-images.githubusercontent.com/20096768/101270847-39feb200-374b-11eb-9768-e4ffc3fe76cf.jpg)
![20201205211419_1](https://user-images.githubusercontent.com/20096768/101270848-3a974880-374b-11eb-99c0-f9c60e56c830.jpg)
![20201205211437_1](https://user-images.githubusercontent.com/20096768/101270850-3b2fdf00-374b-11eb-935f-ae964f3326b0.jpg)
![20201205211444_1](https://user-images.githubusercontent.com/20096768/101270851-3b2fdf00-374b-11eb-83fa-b68cab1ea623.jpg)

**Comment by RecursiveVision** [comment]
@pineappledan

**Comment by pineappledan** [comment]
Maybe it is a load order issue? The improvement gives 2 gold for all luxury resources, but then the (5) extra luxuries mod is loaded after hacienda is, so they aren't loaded into the database?

This is the current code:
```
INSERT INTO Improvement_AdjacentResourceYieldChanges    
            (ImprovementType,                ResourceType,    YieldType,        Yield)
SELECT        'IMPROVEMENT_SPAIN_HACIENDA',    Type,            'YIELD_GOLD',    2
FROM Resources WHERE ResourceClassType = 'RESOURCECLASS_LUXURY';
```
maybe it could work if I just looped through all possible luxuries individually?

**Comment by pineappledan** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/pull/7264
