### ISSUE TITLE
CTD when archer targets Barbarian City

### ISSUE THREAD

**Issue by DeAnnoCiv** [LoneGazebo/Community-Patch-DLL#7267]
_1. Mod version (i.e Date - 12/1):_
12-1-1 (newest)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When selecting the nearby Archer, then selecting the attack action, then mousing over the barbarian city in preparation to attack it, the game CTDs.

_4. Steps to reproduce (optional):_
Just load the save and then try to use the Archer against the city. Note that you don't even get a chance to try to attack; the mouseover causes the CTD.

---------------------------

[BarbCityCTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5652195/BarbCityCTD.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5652202/Logs.zip)

**Comment by ilteroi** [comment]
fixed in latest version
