### ISSUE TITLE
Incorrect intrigue sent to the wrong civilization

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#7268]
_1. Mod version (i.e Date - 12/1): 12-1-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: Theodora shares an incorrect intrigue with the wrong civilization. She says that Askia is marching to attack your city of Gao (see screenshot). The first problem is, I am not the owner of Gao. The second problem is, Askia is the owner of Gao (see screenshot) and he is not going to attack his own city :-D

_4. Steps to reproduce (optional): Load the save and hit "Next turn". On her turn, Theodora will share the intrigue.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[before_share_intrigue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5652898/before_share_intrigue.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Theodora_intrigue](https://user-images.githubusercontent.com/620131/101356035-c4ecc300-3897-11eb-81d5-a98625d3c5a8.png)
![Gao_is_owned_by_Askia](https://user-images.githubusercontent.com/620131/101356122-e8177280-3897-11eb-9876-dc1ff3e73f2c.png)

**Comment by RecursiveVision** [comment]
@ilteroi pretty sure you made changes to this.
