### ISSUE TITLE
Wrong combat preview when land ranged unit targets ranged ships

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#7269]
Latest version, see below image
![image](https://user-images.githubusercontent.com/14953746/101363271-2a62a300-38dc-11eb-97da-fb4cf9de58f4.png)

As a ranged attack, the dromon should defend with its ranged strength against the trebuchet, but the combat preview uses the melee strength. It seems to be correctly calculating the estimated damage though.

**Comment by ilteroi** [comment]
well, that seems to be by design:
```
				if (iTheirStrength == 0 or pTheirUnit:GetDomainType() == DomainTypes.DOMAIN_SEA or pTheirUnit:IsRangedSupportFire()) then
					iTheirStrength = pTheirUnit:GetMaxDefenseStrength(pToPlot, pMyUnit, pFromPlot, true);
				end
```

no idea who put it there but easy to remove

**Comment by ricanuck** [comment]
Well, how can it defend with its ranged ATTACK? Seems to work as intended, and is logical.

**Comment by ilteroi** [comment]
nope. 

ranged units use ranged strength against ranged attacks.

in any case the distinction between naval units and land units is highly questionable.
