### ISSUE TITLE
Spies can steal 0 gold 

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#727]
![spies](https://cloud.githubusercontent.com/assets/12978597/10868929/d31ca1d8-80a6-11e5-8d20-d14fa6da2b50.jpg)

**Comment by TechpriestEnginseer** [comment]
What if Cusco had 0 gold in the first place and the best they could do was to steal 0 gold?

**Comment by Edaka** [comment]
In that case, the advanced spy action is used up for no reason. Perhaps there could be a check so that if there is no gold in the treasury, a different advanced action occurs. Might as well be an aborted mission, but I certainly wouldn't call what's seen on the screenshot a robbery. Unless that spy wasn't the brightest of minds, "Oh hey, look at that sweet 0 gold I robbed! Better report to my king - he will be most delighted!"

**Comment by LoneGazebo** [comment]
Odd that it fired at zero - requires a positive value to fire. I'll take a look.
