### ISSUE TITLE
Missing Worker Recommendations

### ISSUE THREAD

**Issue by Dovaj** [LoneGazebo/Community-Patch-DLL#7270]
_1. Mod version (i.e Date - 12/1):  12-1-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ I am only getting a very rare flash of Worker Recommendations. ** If I go to/from City View from a selected worker, I see a recommendation. If I select anything else and go back to that, or any other worker, nothing. I get Leader(Citadel) and Settler(City) recommendations though. This works 100% of the time, so it seems like it has something to do with the screen refreshing on clicking another unit as opposed to leaving city view?

I re-instaIled, cleaned up my MODS folders (Cache & ModUserData) and loaded no mods beyond the VP ones and see the same behavior. I have toggled the Worker Recommendations on/off/on and checked it in Options. This has happened to me before, but I do not see many folks reporting it. Do others not use the Worker Recommendations? Not have this issue. Or, just not notice?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by CyberPhy** [comment]
I'm not seeing this problem on my end, have you tried validating Civilization V in Steam?

**Comment by Dovaj** [comment]
I had done that earlier, and just did again.  The verify stated that 8 files were to be reaquired.  No change in the behavior.  If I recall, the last time this happened to me, about a year ago, the next VP update 'fixed' the issue for me.  Since I seem to have found a workaround, if no one else is seeing this behavior, we can close this ticket.  I'll keep an eye on it and try to refrain from doing anything systemic until the next update.  Thanks for checking.
