### ISSUE TITLE
Don't merge RSI yet

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7272]
@ilteroi @LoneGazebo I'm working on a long list of fairly substantial/complex changes ATM (including changes to memory) which aren't quite ready to be merged yet, and I may undo or redo changes - it would be unwise to merge partial changes as it'll cause merge errors later. I'll make a pull request when I'm ready. :)

Just letting you guys know since I notice you sometimes do merges from my changes before I actually make pull requests. (Which is usually fine, just not this time!)

**Comment by ilteroi** [comment]
you don't have to push your intermediate state. in fact it's better if you don't because you can rewrite the history while it's private

**Comment by RecursiveVision** [comment]
Easier for me to work from the cloud at the moment.

While looking at my earlier code sometimes makes me roll my eyes, I'm not too ashamed of my recent work. :)
