### ISSUE TITLE
Nationalization and Vassals

### ISSUE THREAD

**Issue by Oscar-IronTower** [LoneGazebo/Community-Patch-DLL#7273]
_1. Mod version (i.e Date - 12/1):_ 12/1 with hotfix.

_2. Mod list (if using Vox Populi only, leave blank):_

Gedemon's YnAEMP
InfoAddict
Quick Turns
Really Advanced Setup
UI - Improved City View (Vox Populi EUI)
UI - Trade Opportunities for VP
Minor tweaks to VP like allowing farms on freshwater hills, allowing both train station and seaports in a city, and modified the values of resource deposits.
Playing on Dale's Earth map from YnAEMP.

_3. Error description:_ 

With Nationalization, should I be able to build franchises on vassals or not? Because it seems to imply I can, but it says it can't when selecting a trade route.

_4. Steps to reproduce (optional):_

In the savegame there's a trade route ready so you can check if it will create a franchise or not.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Nationalization Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5663314/Nationalization.Bug.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![image](https://user-images.githubusercontent.com/4163757/101569431-3ec59f00-39b3-11eb-9c95-f86cc72495f7.png)

**Comment by RecursiveVision** [comment]
@LoneGazebo Which one is intended?

**Comment by LoneGazebo** [comment]
'except vassals' is intended.

**Comment by RecursiveVision** [comment]
Fixed. Bad syntax.
