### ISSUE TITLE
«Give me 10 turns to prepare» AI co-op wars not being triggered with early aggression.

### ISSUE THREAD

**Issue by Fusha** [LoneGazebo/Community-Patch-DLL#7274]
_1. Mod version (i.e Date - 12/1):_ 12-1-3

_2. Mod list (if using Vox Populi only, leave blank):_ UI - Destination (v. 4)

_3. Error description:_ At the end of turn 281, Morocco offers a co-operative war against Austria. After the player chooses «Give me 10 turns to prepare», Morocco succumbs to their everlasting impatience and declares war on Austria on their own on turn 284. Presumably because of this, nothing happens at the end of turn 291, and you can even get Morocco to pay you a very large amount of money to agree to declare war on Austria again. :^)

_4. Steps to reproduce (optional):_ In the «Test turn 281» save, press «next turn» without issuing any commands. (I deleted any great people that appeared, accepted all trade agreements, chose Metallurgy for the next research, adopted the «Divine Right» policy and chose to steal Guilds and Astronomy).

---------------------------
Supporting information:

1. Log files: [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5663431/Logs.zip)

2. Save game: [single.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5663441/single.zip)

**Comment by RecursiveVision** [comment]
Thanks for this! I'll see what's up.

**Comment by RecursiveVision** [comment]
![99789c25c015c61fed38b4b0e2f2bb07](https://user-images.githubusercontent.com/66801010/101950616-8fabe200-3bc3-11eb-9827-658d76f0dddf.png)
![f28a08d58de54f53c82c5eab3e4c8f09](https://user-images.githubusercontent.com/66801010/101950619-920e3c00-3bc3-11eb-985b-e7989d090cf3.png)

**Comment by RecursiveVision** [comment]
So looks like Morocco DoW'ed Assyria and triggered a Defensive Pact with Austria, which for some reason reset the coop war flag against Austria with Rome. Problem is likely in CvTeam::declarewar...interesting that it happens even before the embassy with Assyria is closed.

**Comment by RecursiveVision** [comment]
OKAY YEAH there's definitely something weird going on with coop wars :)

I'm looking into it!
