### ISSUE TITLE
CTD when second player chooses Pantheon

### ISSUE THREAD

**Issue by dejagore** [LoneGazebo/Community-Patch-DLL#7275]
_1. Mod version (i.e Date - 12/1):_
Vox Populi (12-1-3)

_2. Mod list (if using Vox Populi only, leave blank):_
"12-1-3 VP
EUI
Improved City View
and has the fix to fix the missing info tabs"
It's from MODPACK from civfanatics forum (https://forums.civfanatics.com/threads/multiplayer-mod-pack-12-1-hottest-fix-3-updated.663567/)

_3. Error description:_ 
When second Human player (Catherine) chooses Pantheon - immediately CTD
Multiplayer game
Disabled barbarians, goody huts, events for stability
Enabled full logging. Logs in the attachment.

_4. Steps to reproduce (optional):_
1. Open save game 
2. Two players join as Spain and Russia
3. As Russia pick a Pantheon --> CTD

---------------------------

[AutoSave_0114 BC-0025.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5669385/AutoSave_0114.BC-0025.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5669393/CvMiniDump.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5669382/Logs.zip)

**Comment by ilteroi** [comment]
points to
```
GAMEEVENTINVOKE_HOOK(GAMEEVENT_PantheonFounded, ePlayer, GET_PLAYER(ePlayer).getCapitalCity()->GetID(), RELIGION_PANTHEON, eBelief);
```

so that means ePlayer is invalid or the player has no capital or it's something wrong with lua.

can you retry with lua hooks disabled?

**Comment by dejagore** [comment]
@ilteroi Sure- just please tell me how to disable them :)

**Comment by RecursiveVision** [comment]
@dejagore https://forums.civfanatics.com/threads/stability-improvement.665199/

**Comment by dejagore** [comment]
@RecursiveVision thanks

Tested on two different autosaves
1. Both players changed `Name="CORE_DISABLE_LUA_HOOKS"` to `Value="1"`
2. Both cleared cache folder `Documents\My Games\Sid Meier's Civilization 5\cache`

CTD exactly in the same turn - when Catherine is picking the Pantheon :(

**Comment by dejagore** [comment]
@ilteroi @RecursiveVision - do you need any additional debugging from my side ?
