### ISSUE TITLE
(12-1-3) Wrong message on the inactive upgrade button

### ISSUE THREAD

**Issue by GLop4** [LoneGazebo/Community-Patch-DLL#7277]
_1. Mod version: 12-1-3
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Wrong message on the inactive upgrade button (insufficient funds)
![Civ5Screen0125](https://user-images.githubusercontent.com/8753808/101713651-588ce200-3a98-11eb-98ab-d6d38adf2148.png)

**Comment by RecursiveVision** [comment]
@GLop4 LUA log is needed.
