### ISSUE TITLE
Teaching the AI to build canals

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7278]
Take a look at this situation.
![Untitled](https://user-images.githubusercontent.com/66801010/101823741-3c6d5d00-3af9-11eb-89df-1470fd4808c9.png)

As you can see, the Netherlands has several naval units lying around. They also have a UU naval melee unit, and the nearby city of Samoa is obviously one they want to capture.

In this situation, it would make perfect sense IMO for the AI to build a fort on the jungle tile where their crossbowman is located. This would allow for naval units from both Rotterdam and Groningen to pass through and attack Samoa from behind.

Amsterdam and Utretcht could also send in units, and a fort on the farm tile next to Rotterdam or the adjacent village tile could allow for even faster naval movement between those cities.

When the AI is in this kind of situation when a fort or citadel on a single tile could allow for mass naval troop movement between its cities and/or to an opponent's cities, they should build one there if possible.

Multi tile canals can also be built by connecting a fort to an adjacent citadel next to a water tile, but even teaching the AI to take advantage of these one tile opportunities would be a big improvement.

IIRC they're already able to use existing canals.

**Comment by Tekamthi** [comment]
/agree

on some maps with critical canal spots that bisect large continents etc, i'll stop at nothing to get these setup: forward settling,  attacking CS, starting major wars even.  Capture, canal with my own GG, and sometimes regift the city to a friendly ally in better position to defend it.  That said, sometimes its better to leave a location 'uncanaled' if there are larger hostile naval powers nearby and the city is otherwise highly defensible on land.  Ideally AI that knows how to make canals as suggested in OP might balance its naval abilities vs nearby rivals and possibly other factors before setting them up

**Comment by ilteroi** [comment]
not an easy problem, because you need the pathfinder to tell how much of a shortcut it is. kills performance. also would need to track how many canals they already have linking the two sides ... i'll think about it

**Comment by ilteroi** [comment]
![image](https://user-images.githubusercontent.com/1358966/104124287-50062080-5350-11eb-8ba8-6ab8a5f19aec.png)

**Comment by RecursiveVision** [comment]
A step in the right direction, though!

**Comment by ilteroi** [comment]
should canals be allowed on resource plots?

alternatively, should forts connect resources?

**Comment by RecursiveVision** [comment]
I'd think no for the former...doesn't make any sense why resource plots would enable ships to pass through them.

I think the latter is a good idea, though - tradeoff of using a fort is that you wouldn't get the yields from the regular improvement. It doesn't make sense why you're unable to build forts on resource tiles, anyway.

**Comment by RecursiveVision** [comment]
However from a balance perspective it should probably cost more to build a fort on a resource tile...forts can be built faster than other tile improvements IIRC?

**Comment by ilteroi** [comment]
![image](https://user-images.githubusercontent.com/1358966/104129893-83f03e80-536e-11eb-9814-b7498060360a.png)

just right!
