### ISSUE TITLE
diplo ai performance

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7279]
i'm on a performance optimization spree right now and it seems that in a release build, about 10% of the time are spent in SelectBestApproachTowardsMajorCiv(). distribution as follows:

![image](https://user-images.githubusercontent.com/1358966/101900636-18208780-3bb0-11eb-96c4-9d2f8bbc2cce.png)

it's not major, but if you see an easy way to optimize that could have an impact.

**Comment by RecursiveVision** [comment]
@ilteroi I'll see what I can do, was going to revise this function anyway. :)
