### ISSUE TITLE
TwoKay Foods description/effect discrepancy

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#728]
Abstract from Civilopedia on TwoKay Foods HQ:
![corp3](https://cloud.githubusercontent.com/assets/12978597/10868942/3e3831f8-80a7-11e5-91f8-e7298836e5c7.jpg)

However, the in-game tooltip mentions +3 (instead of +2) food from coffee, tea, and olives. Other resources are apparently fine.
![corp1](https://cloud.githubusercontent.com/assets/12978597/10868947/6bfedd08-80a7-11e5-9061-43b1edae9230.jpg)

Moreover, the office descriptions says "+2 food on all Monopoly resources", but this time coffee, tea and olives are omitted completely from the tooltip.
![corp2](https://cloud.githubusercontent.com/assets/12978597/10868953/a07c2716-80a7-11e5-8ea1-a37b38f0cbf3.jpg)

The actual effects seem to reflect the tooltips, not the descriptions.

**Comment by LoneGazebo** [comment]
Seems like a More Luxuries goof on my end.
