### ISSUE TITLE
ctd when ranged attacking city

### ISSUE THREAD

**Issue by Artafrates** [LoneGazebo/Community-Patch-DLL#7280]
_1. Mod version (i.e Date - 12/1):_12/1
December 1st (5.12.1)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When I choose to attack city with ranged attack when I move cursor toward city i got ctd

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization [5/ModdedSaves):]

3. CvMiniDump.dm
[nowe.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5683948/nowe.zip)

p file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Fixed in 12-1-3 hotfix.
