### ISSUE TITLE
Help running the debugger

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7282]
So I'm trying to learn how to run the debugger so I can fix the problems in my latest build as well as with coop wars.

I followed the instructions as listed under "How do I debug this":
1. Built the debug configuration of the project.
2. Copied the DLL and PDB from BuildOutput and replaced the DLL from the installer.
3. Started Civ 5 (legacy launcher).
4. Loaded the mod (also IGE and Quick Turns, not sure if that prevents it from working).
5. Opened the mod's .sln file in Visual Studio 2019.
6. Clicked attach to process:
![Screenshot 1](https://user-images.githubusercontent.com/66801010/102000403-ffe66080-3cb4-11eb-8f09-00db312adad7.png)
7. Chose my settings and hit launch game.

The debugger threw this exception and froze the game. When the debugger was unattached, the game continued normally.
![Screenshot 2](https://user-images.githubusercontent.com/66801010/102000423-39b76700-3cb5-11eb-8208-15f30edae8be.png)

Any idea what I'm doing wrong?

I'm running Windows 10 Home Edition.

__FYI, when I installed Visual Studio my install order was:__
VS Express 2008 with Service Pack 1 (no optional/online products) [VS2008ExpressWithSP1ENUX1504728.iso]
VS Express 2010 (no optional/online products) [VS2010Express1.iso]
VS 2008 Isolated Shell (no optional/online products) [VSIsoShell.exe]
VS 2008 Hotfix for Precompiler Header Error [VS90SP1-KB976656-x86.exe]
VS 2019 Community Edition (Desktop development with C++, default options)

My install order works fine for building the DLL so I doubt it's that but I listed it just in case.

**Comment by RecursiveVision** [comment]
@LoneGazebo @ilteroi

**Comment by ilteroi** [comment]
you only want to catch unhandled exceptions.

see the checkmark "break when this exception type is thrown"? remove it. might have to do that several times until all the benign exceptions are filtered.

**Comment by RecursiveVision** [comment]
Thanks! That explains it. Will let you know if I encounter further difficulties.

**Comment by RecursiveVision** [comment]
@ilteroi Okay, so it stopped throwing exceptions, but now I'm not seeing anything at all in the display (besides "process memory").

![Screenshot](https://user-images.githubusercontent.com/66801010/102028170-b9f1d100-3d76-11eb-93ae-5b03f222ef06.png)

**Comment by ilteroi** [comment]
good. now you can set (conditional) breakpoints in interesting places to inspect variables and execute the code step by step.

**Comment by RecursiveVision** [comment]
I think I get it now. For some reason much of the diplo AI memory is unreadable, though.
