### ISSUE TITLE
Problems past turn 500

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7283]
There have been a number of reports about significant problems past turn 500, with the game essentially breaking.

I have no idea what's responsible but perhaps someone wants to look into it or post a savegame of these problems?

**Comment by azum4roll** [comment]
Just run an autoplay game for 500 turns with base VP, and have yield icons enabled so it's clear which civ is breaking. My version is quite a bit modded.

**Comment by bigcat88** [comment]
Played a game. Till turn 750(Epic Speed, Standard, Communits)
No crashes and games is fast.
Turn 750(2050 AD) i press next and get a crash...

I can post an autosave(Enhanced Air Warfare 4VP and Enhanced Naval Warfare mods are present)

**Comment by RecursiveVision** [comment]
Yeah, the issue is that some memory variables assume max turns is 500, scaling with gamespeed.

**Comment by azum4roll** [comment]
At least it doesn't always become unresponsive (instead of CTD) and start putting corrupt data into the autosave non-stop until you force kill the game...

**Comment by bigcat88** [comment]
Is it hard to increase max turn limit from 500 to 750(or 1000) turns on Standard speed?
