### ISSUE TITLE
Releasing installer automatically using github actions.

### ISSUE THREAD

**Issue by bukowa** [LoneGazebo/Community-Patch-DLL#7284]
It's possible to execute a script using [github actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) based on git actions (push/commit/release). For example [this action](https://github.com/actions/create-release) could be used to automatically create installer and make a release on [release page](https://github.com/LoneGazebo/Community-Patch-DLL/releases) of the project. Github hosted / self hosted runners [can run on windows server 2019](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#github-hosted-runners).

I don't know the process of building and creating installer for this project - with some help i could make a commit for this.

**Comment by RecursiveVision** [comment]
@bukowa https://github.com/LoneGazebo/Community-Patch-DLL/issues/7018

**Comment by bukowa** [comment]
Great it looks like there's a CLI https://www.kymoto.org/documentation/scriptstudio/index.html?CommandLine.html
