### ISSUE TITLE
Hacienda Missing Texture

### ISSUE THREAD

**Issue by Phosphoraptor97** [LoneGazebo/Community-Patch-DLL#7285]
_1. Mod version (i.e Date - 12/1):_
12-1 w/ latest hotfix

_2. Mod list (if using Vox Populi only, leave blank):_
Historical Religions Edit (BNW or GK) (v 45)
InfoAddict (v 22)
Promotion Flags EUI (v 1.1)
Really Advanced Setup (v 15)

_3. Error description:_ 
Hacienda surface and icon has error texture/graphics

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/5684636/Lua.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/5684637/xml.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/5684638/Database.log)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Shaka Prince AD-1640.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5684639/Shaka.Prince.AD-1640.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by GLop4** [comment]
Probably not responsible for the Hacienda missing texture but Promotion Flags EUI for VP v3 must be used instead of 1.1

**Comment by Phosphoraptor97** [comment]
Tried it, issue persists

**Comment by pineappledan** [comment]
There was a known issue with the Strategic view icon which I just resolved. Perhaps this is related?

**Comment by Phosphoraptor97** [comment]
where can i find the fix?
