### ISSUE TITLE
Castle and it GW didnt displayed in 'Culture Overview'

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#7286]
_1. Mod version (i.e Date - 12/1):_
12-1-3 

_2. Mod list (if using Vox Populi only, leave blank):_
(9a) Enhanced Air Warfare 4VP (v 1.0)
Enhanced Naval Warfare for Vox Populi (v 1.6.16)
Really Advanced Setup (v 15)

_3. Error description:_ 
Cant see castle on screen.
Noticed it when create a GW a was unable to find it.
On city screen Castle is displayed with GW.

4. Screenshots (optional):

![image](https://user-images.githubusercontent.com/13381981/102021407-4bb60a00-3d88-11eb-8e4a-84866384b9ed.png)

**Comment by Zarrk** [comment]
I confirm the problem. Looking at the lua.log it seems the function doesn't return the Castle for integration in the window: my guess is that now there are two buildings in the same buildingclass both being 'generic' (not an UB) and when searching the Database only the last one is kept.
Removing the Great Work slot from the Mission makes the Castle reappear.
