### ISSUE TITLE
Crashing on end turn in early game

### ISSUE THREAD

**Issue by Leozahn** [LoneGazebo/Community-Patch-DLL#7287]
_1. Mod version (i.e Date - 12/1):_12/4

_2. Mod list (if using Vox Populi only, leave blank):_Vox Populi 1-7 + VP Community Events.  No other mods

_3. Error description:_ Game crashes to desktop after hitting End Turn button.  No error popup- the game simply closes automatically.  No dump file appears to be created.

_4. Steps to reproduce (optional):_ Hit End Turn, this doesn't happen always, but it does happen every few turns or so especialy by Classical Era.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5685815/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[AutoSave_0120 AD-0125.Civ5Save.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/5685819/AutoSave_0120.AD-0125.Civ5Save.txt)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): N/A

**Comment by RecursiveVision** [comment]
Probably the crash has something to do with LUA, those don't generate a minidump.
