### ISSUE TITLE
Popup notifications related to mercantile and military city-states.

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#729]
The popups only mention just the old bonuses (happiness and unit gifts), but don't mention gold and science. The mouse over tooltip is fine, however.
![cs1](https://cloud.githubusercontent.com/assets/12978597/10868989/82879a8c-80a8-11e5-9c3d-f5e2a71774af.jpg)
![cs2](https://cloud.githubusercontent.com/assets/12978597/10868990/834776ea-80a8-11e5-9234-cf7486758e5a.jpg)

**Comment by LoneGazebo** [comment]
I'll take a look.
G
