### ISSUE TITLE
city governor still being weird

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7290]
with a manual tile assignment the settler takes 3 turns:

![image](https://user-images.githubusercontent.com/1358966/102133765-e892a900-3e55-11eb-8dcd-2a58c4ed0ffe.png)

the governor selects these tiles here, taking 4 turns and foregoing gold/faith/culture.

![image](https://user-images.githubusercontent.com/1358966/102133845-052ee100-3e56-11eb-9d49-6a95a53673a2.png)

**Comment by ilteroi** [comment]
this is even weirder. default assignment, city is far from starving

![image](https://user-images.githubusercontent.com/1358966/102137116-9b650600-3e5a-11eb-9c29-249fb7943a48.png)

**Comment by LoneGazebo** [comment]
Settler product choices are weird because the food/production conversion is hard to compute cheaply.

**Comment by ilteroi** [comment]
well the second one did not even involve a settler

**Comment by Mileslewis** [comment]
Seems like the governor generally way over values food compared to the other yields. After pop 4 or 5 cities should prioritise culture, science, production, faith, food then gold in that order imo.

**Comment by sgtslick** [comment]
Even if you made it consider all yields equally but just count their number, in the second example the default is selecting tiles with 2 yields over tiles with 7. Seems retarded

**Comment by ilteroi** [comment]
i simplified the plot valuation code a bit, seems to be more predictable now. and i have yet to see a starving city, so that seems fine as well.
