### ISSUE TITLE
Clearing a forest provides production for city that is far away.

### ISSUE THREAD

**Issue by bukowa** [LoneGazebo/Community-Patch-DLL#7291]
Is it a known bug or a feature? 

1. Capitol is building pyramids, worker near capitol is clearing forest.
2. I found new city far away on island.
3. It says 60 production from clearing forest was alocated to newly founded city.

**Comment by bukowa** [comment]
Looks like when i found a city on forest/jungle it's cleared and production goes towards the newly founded city

**Comment by bsesar** [comment]
@bukowa , that sounds like normal behavior to me. So it's no longer an issue?

**Comment by bukowa** [comment]
It's not an issue - i didn't know it works that way and the forest clearing at the same time made it confusing sorry.
