### ISSUE TITLE
Colonialism policy gives all Great Person Points (GPPs) in all cities? Not sure if bug

### ISSUE THREAD

**Issue by CokolwiekUnni** [LoneGazebo/Community-Patch-DLL#7293]
Why does Colonialism (monopolies policy in Imperialism) does that? I've been looking for this in here and CivFanatics. Searched for Colonialism bug and other keywords, but I found nothing. Is this a recurring bug or intended effect? If intended is it additional and not mentioned in the policy info or is it due to some effect? If it is intended I think it should be completely removed.
I don't work any specialist, I still have flat 3 GPPs towards any great person in all of my cities as soon as I open this policy.

I rarely play Imperialism so don't remember exactly? But I've done a search on Milae's videos as I found it (Spain and Netherlands playthrough) and it provided the same bonus to him, so this bug (?) must be present since at least some versions.

And just to clarify Colonialism other bonuses works the way that flat counts multiple (so +9 happiness from three +6 happiness monopolies) but only once for percentage ones (so only 10% percent for having both sugar and salt monopolies, not 20%)?

My save is on 10-07-2 with Ilteroi hotfix, along with Historical Religions Edit (BNW or GK) (v 45)

[AutoSave_0193 AD-1330.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5693539/AutoSave_0193.AD-1330.zip)

**Comment by Mileslewis** [comment]
Yea, I think you also get a +10% modifier to GP generation from the policy which says monopoly bonus even though I don't think there is a monopoly which gives that.

**Comment by CokolwiekUnni** [comment]
Alright guys, I made a tiny modmod to fix the issue for now

I didn't want to be locked into other policies by this bug so I simply edited out both flat and percentage modifiers for monopolies from Colonialism policy to get rid of both GPP bug and combat bonus bug. The tree is still strong if you know what you're doing and if you happen to possess mostly flat yield monopolies the nerf is negligible. You can easily throw some other thing into it like copying the line from Progress' Expertise that gives you +10% production if you miss original effect so much. Progress is in the Liberty folder. Changes are savegame compatible so you can add desired effect manually after gaining a particular monopoly, with text, if you so desire. Tested with Ingame Editor, everything works perfectly. I also added text for logging camps bonus from Industry's Entrepreneurship policy because it was missing the info previously, while providing the effect.
Just replace the files in (2) Community Balance Overhaul. All are in Balance Changes folder, one Policies, the other Text folders. Don't have CivFanatics account so can't post it there.

Note for the devs: After throwing only percentage modifier, the GPP bug still persists but vanishes after deleting flat effect. So the game is clearly taking +3 modifier to apply to GPPs also as it is always +3 GPPs in all cities.

[Imperialism Pseudo Fix.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5721288/Imperialism.Pseudo.Fix.zip)

![Untitled](https://user-images.githubusercontent.com/75467145/102720941-ad7df300-42f7-11eb-820f-6da36fccdecc.png)
