### ISSUE TITLE
world congress oddities

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7297]
i proposed my religion as world religion and got a diplo message from arabia supporting me, although they are the founder of a different religion.

**Comment by SolicShooter** [comment]
I believe every civ supports world religion proposals at the moment. If you hover over the proposal before proposing it, it'll say it will benefit your relationship with every other civ. So probably bugged yes.

**Comment by ilteroi** [comment]
even better, now i proposed a resolution and they offered me a deal where they would vote *against* my proposal (their vote valued at 150 gold)

**Comment by ilteroi** [comment]
and another one. i proposed to sanction brazil ... seems like a real good way to make money!

![image](https://user-images.githubusercontent.com/1358966/102400591-70a5b980-3fe2-11eb-8eae-83c13f3f3dc4.png)

**Comment by ilteroi** [comment]
and then this

![image](https://user-images.githubusercontent.com/1358966/102410601-0f391700-3ff1-11eb-8708-be03e110336f.png)

russia has no chance in hell, yet england votes for them instead of themselves. otherwise they would have won.

**Comment by ilteroi** [comment]
ok now my best friend austria proposed to sanction me ... after they wanted to become my voluntary vassal several times.

![image](https://user-images.githubusercontent.com/1358966/102724502-33a63380-4310-11eb-86d2-069255bd187f.png)

also, fun fact, arabia hates me for being a warmonger after the russian declared war on me - i captured one city from them and liberated another one. seems excessive ...

**Comment by RecursiveVision** [comment]
@ilteroi last one should be slightly better with my changes, diplo AI was set to ignore religious differences but league AI wasn't.

**Comment by ilteroi** [comment]
one more ... the aztecs / the maya / the ottomans would be angry if i propose peace accords. but they also would be angry if i propose casus belli. make up your minds, guys!

**Comment by RecursiveVision** [comment]
Probably they'd hate you either way because of a bad alignment in EvaluateAlignment...
