### ISSUE TITLE
Make city resource needs for WLTK visible during diplo/trade

### ISSUE THREAD

**Issue by Dovaj** [LoneGazebo/Community-Patch-DLL#7301]
(Feature request only)
Is it possible to have my city icons in the top left of the EUI show during Trade/Diplo negotiations?  I can see the list of other Civs in the top right, but not what resources my cities desire during dealmaking.

**Comment by bsesar** [comment]
@Dovaj , I think if you hover the pointer over a luxury in the diplo trade window, you can see which (if any) cities need that luxury. Does that suffice?

**Comment by Dovaj** [comment]
That is funny. 400+ hrs played and I didn't remember that at all!  It does the trick and I do recall seeing it now that you reminded me.  Thanks.  Closing.
