### ISSUE TITLE
Automated workboats dont create Offshore Platform

### ISSUE THREAD

**Issue by bigcat88** [LoneGazebo/Community-Patch-DLL#7302]
_1. Mod version (i.e Date - 12/1):_
1 December

_4. Steps to reproduce (optional):
In my current game workboat when I press 'A'(automate): do nothing with oil resource on sea.
Not a problem at all, just for note.

**Comment by Vyyt02** [comment]
Maybe it will be a problem for AI though?

**Comment by ilteroi** [comment]
are you sure you have the required tech for the oil rig? because that comes much later than the oil itself ...
