### ISSUE TITLE
CTD NO ISSUES SEEN

### ISSUE THREAD

**Issue by myles1718** [LoneGazebo/Community-Patch-DLL#7303]
_1. Mod version (i.e Date - 12/1):_
12/1/3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Pressing  NEXT TURN after my turn on turn 210 crashes straight to desktop

_4. Steps to reproduce (optional):_
Loaded game twice and played from saved games but still had CTD on same turn
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5711914/Lua.zip)
[xml.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5711916/xml.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5711921/CvMiniDump.zip)
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5711923/Database.zip)
[Elizabeth_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5711924/Elizabeth_0000.BC-4000.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
can't do anything with the crashdump, no idea what's up. but then only gazebo has the proper debug symbols.

**Comment by R3P0FFXI** [comment]
I also have had issues randomly for no reason where the game is just crashing to the desktop . It can happen after 1 turn on a straight game or 500 turns into a game.
