### ISSUE TITLE
Ai Settlers just roaming

### ISSUE THREAD

**Issue by Jkwain** [LoneGazebo/Community-Patch-DLL#7305]
_1. Mod version (i.e Date - 12/1):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Ai settler with this mod keep roaming which ruins the whole purpose of the mod. anyone kindly fix this 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@Jkwain Version number? Screenshot? Details? More information is needed to diagnose this. :)
