### ISSUE TITLE
I have a bug, Faith bug

### ISSUE THREAD

**Issue by ulok7450** [LoneGazebo/Community-Patch-DLL#7307]
_1. Mod version (i.e Date - 12/1):_
CP(94)

_2. Mod list (if using Vox Populi only, leave blank):_
CP(94) , IGE only

_3. Error description:_ 
[Sid Meier's Civilization 5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5724216/Sid.Meier.s.Civilization.5.zip)
Only CP mode is used. (1) After checking CP mode, after the game starts, the faith is between 20 and 50 and there are great Great Engineer and great merchant in the capital city, and the great list score is 166666060. I don't know what the problem is. help me :(

_4. Steps to reproduce (optional):_
just turn end

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482): yes file here

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves): yes file here

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): yes file here

4. Screenshots (optional): https://imgur.com/a/0TkNUDk

**Comment by RecursiveVision** [comment]
@ulok7450 Did you select "only Community Patch" when you installed the mod, or did you install everything? There's currently some issues when you enable only the CP.

Also try clearing your cache and ModUserData folders in My Games > Sid Meier's Civilization V.

**Comment by RecursiveVision** [comment]
I see on the forums that you fixed the issue. No problem, then.
