### ISSUE TITLE
No faith from ruins

### ISSUE THREAD

**Issue by Dromin** [LoneGazebo/Community-Patch-DLL#7309]
_1. Mod version (i.e Date - 12/1):_
12-1

_2. Mod list (if using Vox Populi only, leave blank):_
* (1) Community Patch
* (2) Community Balance Overhaul
* (3) CSD for CBP
* (4) Civ IV Diplomatic Features
* (5) More Luxuries
* (6a) Community Balance Overhaul - Compatibility Files (EUI)
* (7) Community Events (v 5)
* (7a) Promotion Icons for VP
* (7b) UI - Promotion Tree for VP
* Convenient start (v 2)
* Even More Resources for Vox Populi (v 5)
* Global - Civilians Move After Purchase (v 2)
* Global - Enable Magellan (v 10)
* Global - Grateful Settlers (v 4)
* Improvement - Pontoon Bridge (v 3)
* Raze Capitals and City States (v 1)

_3. Error description:_ 
Ancient ruins appear to no longer give faith (either pantheon or prophet) early-game. I haven't seen a single instance of patheon / first great prophet faith from ruins ever since I updated to 12-1 version. However, I have received faith from ruins late-game after I already had a fully enhanced religion, which is something that used to be impossible. 

_4. Steps to reproduce (optional):_
/

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
/
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
/
3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
/
4. Screenshots (optional):
/

**Comment by RecursiveVision** [comment]
Maybe I made a typo somewhere...will look.

**Comment by RecursiveVision** [comment]
I did! My bad. :)
