### ISSUE TITLE
Separate <ExtraLeagueVote>

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#731]
I would like a separate XML tag that grants votes not based on amount of city-states. (I was strangely alerted when someone had 11 votes at only the renaissance era to only realize they had the Forbidden Palace.

And if it's possible a separate XML tag that grant votes based on a city's population as well.

**Comment by LoneGazebo** [comment]
Is this a feature request? For what purpose?

**Comment by TechpriestEnginseer** [comment]
Well, the second feature request can be ignored until later on...

BUT the first request of having an XML tag granting votes not based on amount of city-states is related to users using external mods outside of CBP. Having the <ExtraLeagueVote> on a separate mod and the CBP enabled will cause the buildings to have given more votes(if the users has created more city-states) than what the external mod owner has intended for.

An example would be a mod which adds a national wonder: "Congress Delegation" which grants one extra vote in the World Congress. Users would find that it is compatible with CBP except that they would find their Congress Delegation to be producing more than one vote if they had enabled more city-states in the game settings. This would create confusion for users and imbalance if the author of the mod did not intend for the building to grant more than one vote.

**Comment by Radost** [comment]
1 vote from a wonder is literally nothing.

**Comment by LoneGazebo** [comment]
I can add this, sure - in the future make sure to mark it as a feature request (or indicate as such), otherwise it gets filed away as a bug report on my end.

**Comment by TechpriestEnginseer** [comment]
Would be good if I knew how.

**Comment by LoneGazebo** [comment]
No need to get sassy. :)

Right side there is a gear icon next to labels - click it and select the 'feature request' label.

**Comment by Radost** [comment]
Except only the project owner can label issues.

**Comment by LoneGazebo** [comment]
Blegh, didn't realize that. I'll deal with it.
