### ISSUE TITLE
Issues with units waking up when they shouldn't / not waking up when they should

### ISSUE THREAD

**Issue by Dromin** [LoneGazebo/Community-Patch-DLL#7310]
_1. Mod version (i.e Date - 12/1):_
12-1

_2. Mod list (if using Vox Populi only, leave blank):_
* (1) Community Patch
* (2) Community Balance Overhaul
* (3) CSD for CBP
* (4) Civ IV Diplomatic Features
* (5) More Luxuries
* (6a) Community Balance Overhaul - Compatibility Files (EUI)
* (7) Community Events (v 5)
* (7a) Promotion Icons for VP
* (7b) UI - Promotion Tree for VP
* Convenient start (v 2)
* Even More Resources for Vox Populi (v 5)
* Global - Civilians Move After Purchase (v 2)
* Global - Enable Magellan (v 10)
* Global - Grateful Settlers (v 4)
* Improvement - Pontoon Bridge (v 3)
* Raze Capitals and City States (v 1)

_3. Error description:_ 
(Note: all of this has been happening for several versions; I just thought I'd report it while I'm opening issues anyway.)
* After clicking "next", civilian units that saw an enemy unit in the current turn drop their tasks and ask for new instructions. This is useful to prevent them from being captured; however, they still do this even if the enemy unit was killed the same turn it appeared and is no longer a threat at that point. Even more annoying: they do this two turns in a row for no apparent reason. So the sequence of events is: a barbarian appears near my city; I kill it with units stationd around my city; I click "next"; workers drop their tasks and need to be manually given the same tasks they were already doing (even though the threat is gone by this point); I click "next" again; the game moves to the next turn; I finish the turn; I click "next"; workers drop their tasks and need manual re-instruction *again* even though the barbarian was killed the previous turn. I've started jokingly referring to it as worker PTSD because they are appearantly so traumatised at the sight of a barbarian they forget what they were doing multiple turns in a row.
* Units that get attacked while healing don't wake up. This is an issue because on multiple occasions I instructed a unit to heal in (what I thought was) a safe spot, only to get a notification a few turns later that this unit was killed by barbarians. If the unit had woken up after the first attack, I might have been able to get it out of there in time.
* Ships that see an embarked enemy unit don't wake up. So many times I've ended up with barbarian units sailing right inside my borders that could have been stopped by the ships I instructed to lie alert in strategic locations for this very reason, only I didn't notice the barbarian invision in time because my ships didn't wake up when they passed by.

_4. Steps to reproduce (optional):_
/

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
/
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
/
3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
/
4. Screenshots (optional):
/

**Comment by CokolwiekUnni** [comment]
I can confirm waking up civilian units, they stop their tasks and wait for reassignment as if the enemy was nearby but with no enemy in many tiles from them.

**Comment by ilteroi** [comment]
* i have fixed the civilian wakeup after the enemy has been killed. but i don't know how that would carry across turns.
* units would wake up if they were attacked or in danger. but not if an enemy unit was simply visible. also fixed.
