### ISSUE TITLE
How to make function trigger on Game Load?

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7311]
Trying to fix this bug here #7215 

Pretty sure it just needs CvPlayer::UpdateMonopolyCache() to trigger for all players on reloading the game. Or maybe at least at the start of their turn. What is the best way to do this?

Btw I have #7120 and #7293 fixed. Will do a pull request soon.

**Comment by RecursiveVision** [comment]
@Mileslewis In the various files, the reset function is used to reset all variables to their default state, and the read function loads saved data. If you call a function after reading save data it should update properly.

**Comment by ilteroi** [comment]
check CvPlayerManager::Refresh()

**Comment by Mileslewis** [comment]
Seems like it worked in CvPlayerManager::Refresh(). Thanks!

**Comment by RecursiveVision** [comment]
Awesome! Looking forward to your pull request.
