### ISSUE TITLE
question for ilteroi

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7314]
@ilteroi A while back we redid land/sea barbarian target range
The current code is:
```
	m_iLandBarbarianRange = std::max(1, GC.getGame().getHandicapInfo().getBarbarianLandTargetRange());
	m_iSeaBarbarianRange = std::max(1, GC.getGame().getHandicapInfo().getBarbarianSeaTargetRange());
	if (MOD_BALANCE_CORE_DIFFICULTY)
		m_iSeaBarbarianRange /= 2;
```

My intention was (and now that I've gotten better at C++ I would write it like this):
```
	m_iLandBarbarianRange = std::max(1, GC.getGame().getHandicapInfo().getBarbarianLandTargetRange());
	m_iSeaBarbarianRange = MOD_BALANCE_CORE_DIFFICULTY ? std::max(1, GC.getGame().getHandicapInfo().getBarbarianSeaTargetRange()) : std::max(1, (GC.getGame().getHandicapInfo().getBarbarianSeaTargetRange()/2));
```

But I remember what I wrote having this same effect...so did you reduce the sea target range intentionally for performance reasons or was it a typo/merge error a while back?

**Comment by RecursiveVision** [comment]
Current XML values are:
Land - ranges from 3 on Settler to 7 on Deity.
Sea - ranges from 6 on Settler to 10 on Deity.

**Comment by ilteroi** [comment]
there is no performance difference, it is just about readabilty.

the compiler is your friend. performance optimization only after profiling.

**Comment by RecursiveVision** [comment]
@ilteroi I meant did you reduce the sea barbarian turns from 10 to 5 intentionally :)

**Comment by ilteroi** [comment]
ah. well the original value was in plots but now i calculate in turns.

so gameplay wise it is similar. and yessmaller search range is faster

**Comment by RecursiveVision** [comment]
@ilteroi Yeah, the original range was a max of 12 for land and 28 for sea, but it was in plots rather than in turns.

I adjusted those values. 10 is close to 1/3 of 28 and 7 is about half of 12.

So is a 10-turn range too performance intensive for the Barbarians, and did you further reduce it to 5 intentionally...or was it a typo/merge snafu. That's my question :)

**Comment by ilteroi** [comment]
i don't have numbers. set what you think is best

**Comment by RecursiveVision** [comment]
Okay. Feel free to revert if issues arise, I don't question your expertise with tactical AI. :)
