### ISSUE TITLE
City state settlers can spawn on top of mountains

### ISSUE THREAD

**Issue by Dromin** [LoneGazebo/Community-Patch-DLL#7315]
_1. Mod version (i.e Date - 12/1):_
12-1

_2. Mod list (if using Vox Populi only, leave blank):_
* (1) Community Patch
* (2) Community Balance Overhaul
* (3) CSD for CBP
* (4) Civ IV Diplomatic Features
* (5) More Luxuries
* (6a) Community Balance Overhaul - Compatibility Files (EUI)
* (7) Community Events (v 5)
* (7a) Promotion Icons for VP
* (7b) UI - Promotion Tree for VP
* Convenient start (v 2)
* Even More Resources for Vox Populi (v 5)
* Global - Civilians Move After Purchase (v 2)
* Global - Enable Magellan (v 10)
* Global - Grateful Settlers (v 4)
* Improvement - Pontoon Bridge (v 3)
* Raze Capitals and City States (v 1)

_3. Error description:_ 
Okay, so I like to play on the highlands map and I've seen this happen many times before (thanks to the Convenient Start mod giving my initial settler extra vision), but this time it was a particularly egregious case 😆 See screenshots below. Appearantly there is no check that prevents city state settlers from spawning on top of mountains. This results in various types of weirdness. 

In this particular case, the city state settler spawned on a mountain close to the spot where I decided to settle my capital. Obviously it couldn't settle there, so the next turn it teleported to the other side of my capital. (Side note: that was actually the first time I've seen them do anything like teleporting themselves. Previously they would either walk around on the mountains until they found a way out, or just... sit there in the same spot for the rest of the game and never actually settle a city.) 
They couldn't settle there either because they were touching my borders, so they moved 1 tile down and planted their city pretty much right on top of my capital. (Side note 2: appearantly the restriction that you have to settle at least 3 tiles away from an existing city does not apply to city states; not sure if this is intentional?) I went back a few autosaves at that point, declared war and captured their settler before they could settle. However, this does not remove the city state from the game, as would happen if I had conquered their city. So the city state is still displayed in the list on the right side of the screen, can still give quests etc. and their warrior is still standing in the same spot next to my border, even though the chances of it settling an actual city are zero now because their settler turned into a worker when I captured it.

In fact, I'd say that I find city states in this situation in most of the highlands games I play. Sometimes, like now, there is only a warrior left with no indication of what happened to the settler (... well, except this time I know exactly where it went, lol). I image it was taken by barbarians before it could find a suitable spot to settle. Sometimes the settler is still sitting on top of the mountain and never settles a city. There was also that one case in which the Bratislava settler was still hanging out in a corner of the map until the industrial era, not even on top of a mountain (although I assume it originally spawned on top of one) but embarked in a small sea. It kept moving back and forth as if it was trying to find a spot to settle, but Ur was in the way. Then it was chased to the other side by barbarians and finally founded a city really late-game. And on several occasions I have freed a city state settler from a barbarian encampment; they usually settle a city on the spot right after being freed.

_4. Steps to reproduce (optional):_
Play highlands map for a ridiculous number of hours because you have no life.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
/
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
/
3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
/
4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/9011748/102840526-63823380-4403-11eb-9987-55bc0080f382.png)
![image](https://user-images.githubusercontent.com/9011748/102840870-16eb2800-4404-11eb-8020-ed224926f112.png)
![image](https://user-images.githubusercontent.com/9011748/102840939-3d10c800-4404-11eb-94bf-f5f0820bf13c.png)

**Comment by RecursiveVision** [comment]
This is a funny bug. Don't think I've ever seen anything like this before. :D

**Comment by Dromin** [comment]
lol, I aim to please 😛

**Comment by ilteroi** [comment]
as far as i understand this, it would be a problem of the map script. couldn't reproduce in any case.

**Comment by RecursiveVision** [comment]
@Dromin Does the Highlands map come with VP? If not, it's a mod conflict. I'm not familiar with all the maps, but it's not listed as an additional mod in your list.

**Comment by ilteroi** [comment]
ok, now i see it ... but no idea what to do about it. if it's only this one mapscript, no big deal?

![image](https://user-images.githubusercontent.com/1358966/102920463-1c3f8580-448b-11eb-9298-11e6147b7fa6.png)

**Comment by RecursiveVision** [comment]
Maybe someone like @azum4roll would have a better idea of how to handle this?

**Comment by Dromin** [comment]
@RecursiveVision I think the Highlands map came with the vanilla game. My bad, I didn't realize that it would be the map script that determines city state starting location 😅 
Settler teleportation however is most likely being caused by VP (given that this was the first time I saw them do that, and I'm definitely seeing a big increase in "missing" city state settlers since updating to 12-1).

**Comment by RecursiveVision** [comment]
@ilteroi The thing about Barbarian civilians is probably a bug?

**Comment by ilteroi** [comment]
cannot confirm that

**Comment by Dromin** [comment]
I'll make a report as soon as I can get a good screenshot.

**Comment by Dromin** [comment]
Issue report: https://github.com/LoneGazebo/Community-Patch-DLL/issues/7327

**Comment by azum4roll** [comment]
`	local plotType = plot:GetPlotType()
	if plotType == PlotTypes.PLOT_OCEAN or plotType == PlotTypes.PLOT_MOUNTAINS then
		return false
	end`

Mountain check does exist in Highlands, so I don't know why that happens.

**Comment by RecursiveVision** [comment]
@LoneGazebo Does the CP modify any vanilla mapscripts?

**Comment by RecursiveVision** [comment]
Fixed this at last.
