### ISSUE TITLE
"City-States grow wary" fires twice

### ISSUE THREAD

**Issue by Dromin** [LoneGazebo/Community-Patch-DLL#7316]
_1. Mod version (i.e Date - 12/1):_
12-1

_2. Mod list (if using Vox Populi only, leave blank):_
* (1) Community Patch
* (2) Community Balance Overhaul
* (3) CSD for CBP
* (4) Civ IV Diplomatic Features
* (5) More Luxuries
* (6a) Community Balance Overhaul - Compatibility Files (EUI)
* (7) Community Events (v 5)
* (7a) Promotion Icons for VP
* (7b) UI - Promotion Tree for VP
* Convenient start (v 2)
* Even More Resources for Vox Populi (v 5)
* Global - Civilians Move After Purchase (v 2)
* Global - Enable Magellan (v 10)
* Global - Grateful Settlers (v 4)
* Improvement - Pontoon Bridge (v 3)
* Raze Capitals and City States (v 1)

_3. Error description:_ 
When declaring war on a city state, the "City-States grow wary" notification is fired twice, resulting in double the number of wary city states. See screenshot below.

_4. Steps to reproduce (optional):_
Declare war on a city state.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
/
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
/
3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
/
4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/9011748/102841280-ec4d9f00-4404-11eb-9477-f889ca55ae8d.png)

**Comment by RecursiveVision** [comment]
This is a mistake in CvTeam::DoDeclareWar causing the function to be called multiple times. I fixed this already. :)
