### ISSUE TITLE
City States getting "stuck" on multiplayer

### ISSUE THREAD

**Issue by Dromin** [LoneGazebo/Community-Patch-DLL#7317]
_1. Mod version (i.e Date - 12/1):_
12-1

_2. Mod list (if using Vox Populi only, leave blank):_
* (1) Community Patch
* (2) Community Balance Overhaul
* (3) CSD for CBP
* (4) Civ IV Diplomatic Features
* (5) More Luxuries
* (6a) Community Balance Overhaul - Compatibility Files (EUI)
* (7) Community Events (v 5)
* (7a) Promotion Icons for VP
* (7b) UI - Promotion Tree for VP
* Convenient start (v 2)
* Even More Resources for Vox Populi (v 5)
* Global - Civilians Move After Purchase (v 2)
* Global - Enable Magellan (v 10)
* Global - Grateful Settlers (v 4)
* Improvement - Pontoon Bridge (v 3)
* Raze Capitals and City States (v 1)

_3. Error description:_ 
Sometimes when the city states are executing their turn, the game gets "stuck" (we can still move the camera around the map, but the game does not progress to the next turn) on one city state for several minutes, for no apparent reason. It's possible to tell which city state is the cause because it is highlighted in black the entire time in the list of city states on the right side of the screen. Usually when this happens, it happens several turns in a row (caused by the same city state), then goes away for a few turns, then comes back, and so forth. This only happens in multiplayer and is new behavior since the last one or two versions (we skipped one, so I don't know if it started with 12-1 or the previous version).  

_4. Steps to reproduce (optional):_
/

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
/
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
/
3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
/
4. Screenshots (optional):
/

**Comment by Dromin** [comment]
@ilteroi What kind of information do you need? Would a savegame (+ modpack) help?

**Comment by ilteroi** [comment]
multiplayer is always hard. frankly it would be best if you run it in the debugger yourself, if you have the setup to do so. otherwise not much i can do

**Comment by Dromin** [comment]
@ilteroi Do you have (a link to) some instructions on how to do that? I would love to help debug multiplayer, only I'm not sure how and where to get started.

**Comment by ReanKW** [comment]
I've had a very similar issue playing MP with a modpack with base VP + 3/4th UC. From what I could tell it was an issue with boats getting stuck unable to find a mission or something, it was running some unit update fuction until it got timed out. No idea where you could fix that though.

**Comment by ilteroi** [comment]
well the readme contains some pointers ... if you have worked with visual studio before it should be easy. otherwise there might be a learning curve :)

**Comment by RecursiveVision** [comment]
@Dromin Message me on CivFanatics, I can walk you through the installation and setup process.

**Comment by Dromin** [comment]
> well the readme contains some pointers ...

Ah, oops, sorry! 😅 I was looking at the wiki and didn't find any instructions and now I feel like an idiot, lol. I'll see how far I can get with that and I'll message you if I get stuck @RecursiveVision
