### ISSUE TITLE
Tech scaling on 2 player teams on Quick Speed

### ISSUE THREAD

**Issue by Phosphoraptor97** [LoneGazebo/Community-Patch-DLL#7318]
I played a multiplayer game with a friend and we were in a team. Found that we were teching so fast that we could not keep up with infrastructure and units.

Did some testing, apparently Quick speed scales everything by ~2/3, so no problems here. But Quick and 2 player team does not scale tech costs by 2x but by 1.5x, causing players to research faster than they can build. Can we get this fixed? 

Costs of 1st tier of techs: 42 on 1 player teams, 63 instead of 84 on 2 player teams.

Further testing shows this applied to all game speeds, and 3 player teams scaled tech costs by 2x instead of 3x.

**Comment by Mileslewis** [comment]
I actually noticed this in the code. I can fix if you want?

**Comment by Mileslewis** [comment]
Also are there any other bugs with team tech costs? For example do you both always have the same tech cost even when you have different number of cities? It's supposed to go up by 5% per city.

**Comment by RecursiveVision** [comment]
@Mileslewis Sure! :)
