### ISSUE TITLE
Better CustomCivs Compatibility: HappinessMod Component

### ISSUE THREAD

**Issue by Jamforce** [LoneGazebo/Community-Patch-DLL#732]
Ugly because of the limits of sqlite, but it still does its job.

CREATE TRIGGER HappinessMod_Buildings
AFTER INSERT ON Civilization_BuildingClassOverrides
WHEN EXISTS (SELECT BuildingType FROM Civilization_BuildingClassOverrides WHERE BuildingType = NEW.BuildingType) AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_BUILDINGS' AND Value= 1)
BEGIN

	UPDATE Buildings
	SET Happiness = (SELECT Happiness FROM Buildings WHERE Type IN (SELECT DefaultBuilding FROM BuildingClasses WHERE Type = NEW.BuildingClassType)),
	
	PovertyHappinessChange = (SELECT PovertyHappinessChange FROM Buildings WHERE Type IN (SELECT DefaultBuilding FROM BuildingClasses WHERE Type = NEW.BuildingClassType)),
	DefenseHappinessChange = (SELECT DefenseHappinessChange FROM Buildings WHERE Type IN (SELECT DefaultBuilding FROM BuildingClasses WHERE Type = NEW.BuildingClassType)),
	IlliteracyHappinessChange = (SELECT IlliteracyHappinessChange FROM Buildings WHERE Type IN (SELECT DefaultBuilding FROM BuildingClasses WHERE Type = NEW.BuildingClassType)),
	UnculturedHappinessChange = (SELECT UnculturedHappinessChange FROM Buildings WHERE Type IN (SELECT DefaultBuilding FROM BuildingClasses WHERE Type = NEW.BuildingClassType)),
	MinorityHappinessChange = (SELECT MinorityHappinessChange FROM Buildings WHERE Type IN (SELECT DefaultBuilding FROM BuildingClasses WHERE Type = NEW.BuildingClassType)),
		
	PovertyHappinessChangeGlobal=(SELECT PovertyHappinessChangeGlobal FROM Buildings WHERE Type IN (SELECT DefaultBuilding FROM BuildingClasses WHERE Type=NEW.BuildingClassType)),
	DefenseHappinessChangeGlobal=(SELECT DefenseHappinessChangeGlobal FROM Buildings WHERE Type IN (SELECT DefaultBuilding FROM BuildingClasses WHERE Type=NEW.BuildingClassType)),
	IlliteracyHappinessChangeGlobal=(SELECT IlliteracyHappinessChangeGlobal FROM Buildings WHERE Type IN (SELECT DefaultBuilding FROM BuildingClasses WHERE Type=NEW.BuildingClassType)),
	UnculturedHappinessChangeGlobal=(SELECT UnculturedHappinessChangeGlobal FROM Buildings WHERE Type IN (SELECT DefaultBuilding FROM BuildingClasses WHERE Type=NEW.BuildingClassType)),
	MinorityHappinessChangeGlobal=(SELECT MinorityHappinessChangeGlobal FROM Buildings WHERE Type IN (SELECT DefaultBuilding FROM BuildingClasses WHERE Type=NEW.BuildingClassType))
	WHERE Type = New.BuildingType;
	
END;

**Comment by LoneGazebo** [comment]
This looks a bit odd on my end - mind sending as a .txt. file?

**Comment by Jamforce** [comment]
http://s000.tinyupload.com/?file_id=40458137614806139477

**Comment by LoneGazebo** [comment]
Danke!

**Comment by Jamforce** [comment]
Now that i think about it, after the tourism's recent changes, another trigger would be mandatory for the custom civs with an own version of the buildings with tourism attributes (EventTourism, FinishLandTRTourism, FinishSeaTRTourism).

 http://s000.tinyupload.com/?file_id=96104925245792217440

**Comment by LoneGazebo** [comment]
Thanks, I'll add as well.

**Comment by TechpriestEnginseer** [comment]
How would this affect the modded civilization buildings that already have CBP compatibility and also significantly increases the numbers a bit?

**Comment by Jamforce** [comment]
Generally the mods' authors are used to group the necessary compatibility stuff in a dedicated file, which will update the database after that the core stuff has been added. Note that you are not forced to follow such schema, in fact what really matters is that the compatibility changes are applied after that the trigger has fired (in this case it fires AFTER INSERT ON Civilization_BuildingClassOverrides).
