### ISSUE TITLE
(Request) Player.GetNumUnitType and Player.GetNumUnitPromotion

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#7322]
If you're still taking requests for new methods, a **player:GetNumUnitType(unitID)** would prove really useful in improving performance of modded civs (and their unique units). This would return the number of the specified unit type that the player has - current methods only allow this to be narrowed down by class.

Similarly, a **player:GetNumUnitPromotion(promotionID)** would be really helpful but that one might not be as reasonable as the first. Returning the number of instances where this promotion is active on a player units (i.e. a quick way of iterating over all units and counting that promo).

Churs for any help, and merry chrisymas!

**Comment by HungryForFood** [comment]
#7334

Is there documentation somewhere for CPDLL Lua methods? Feels like unless you know how to look inside the DLL, there is no way to know what new options there are. Would need some updating.
