### ISSUE TITLE
Inconsistent behaviour of Improvement_Adjacent.....YieldChanges tables

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#7326]
I'm referring to the following six tables. AdjacentCity and AdjacentMountain are Firaxis tables, the rest are modded.

![image](https://user-images.githubusercontent.com/22621937/103125215-5eeca200-46c5-11eb-9665-96f701e8b862.png)

For all except Improvement_AdjacentImprovementYieldChanges and Improvement_AdjacentTerrainYieldChanges, the primary improvement defined in the first ImprovementType column is the one that gets the bonus.

![image](https://user-images.githubusercontent.com/22621937/103125319-a7a45b00-46c5-11eb-9c46-798353862a1d.png)

For instance, the Terrace Farm gets bonus 1 Gold when next to a mountain.

However, for Improvement_AdjacentImprovementYieldChanges, the second column, 'OtherImprovementType', is the one that gets the bonus.

![image](https://user-images.githubusercontent.com/22621937/103125870-79277f80-46c7-11eb-8bb3-c95435dbc674.png)

In VP, this affects Polders, Feitorias, Kasbahs, and Terrace Farms. For example, Polders grants adjacent Villages and Towns 1 Gold.

For Improvement_AdjacentTerrainYieldChanges, the Terrain gets the bonus rather than the Improvement.

![image](https://user-images.githubusercontent.com/22621937/103125903-9e1bf280-46c7-11eb-8266-fee2b52b8c7e.png)

Feitorias and Kasbahs grant the adjacent Coast tile 1 Gold and Culture respectively.

I do believe the intended behaviour should be the first one (ImprovementType gets the bonus), as the two Firaxis tables follow this convention.

Worth fixing it? Since I'm looking at this part of the code right now.

For Feitorias and Kasbahs, a new table, 'Plot_AdjacentImprovementYieldChanges' may be required if we want to keep the same in-game behaviour.

**Comment by SuperNoobCamper** [comment]
If i remember correctly some custom civs (the Inuit UI adds production to tundra tiles regardless of the improvement) rely on Improvement_AdjacentTerrainYieldChanges and as you mentioned Kasbahs are supposed to grant adjacent water tiles culture regardless of the presence of an improved maritime resource.

**Comment by HungryForFood** [comment]
Yes, hence the possible new table required.

For modders, most that use the DLL are in the Discord. Outside of VP, I'm only aware of JFD who uses it.

**Comment by LessRekkless** [comment]
The entire point of Improvement_AdjacentImprovementYieldChanges is that ImprovementType gives OtherImprovementType the bonus.

For example, in the description for IMPROVEMENT_TERRACE_FARM, we write that the Terrace Farm gives Food to adjacent Farms.  We do not write in the description of IMPROVEMENT_FARM that Farms receive Food from adjacent Terrace Farms.
