### ISSUE TITLE
Barbarian civilians no longer move towards the nearest encampment

### ISSUE THREAD

**Issue by Dromin** [LoneGazebo/Community-Patch-DLL#7327]
_1. Mod version (i.e Date - 12/1):_
12-1

_2. Mod list (if using Vox Populi only, leave blank):_
* (1) Community Patch
* (2) Community Balance Overhaul
* (3) CSD for CBP
* (4) Civ IV Diplomatic Features
* (5) More Luxuries
* (6a) Community Balance Overhaul - Compatibility Files (EUI)
* (7) Community Events (v 5)
* (7a) Promotion Icons for VP
* (7b) UI - Promotion Tree for VP
* Convenient start (v 2)
* Even More Resources for Vox Populi (v 5)
* Global - Civilians Move After Purchase (v 2)
* Global - Enable Magellan (v 10)
* Global - Grateful Settlers (v 4)
* Improvement - Pontoon Bridge (v 3)
* Raze Capitals and City States (v 1)

_3. Error description:_ 
Civilians that were captured by barbarians used to move towards the nearest encampment as quickly as possible. Now, however, they tend to just stand around at the same spot where they were captured, making it very easy to re-capture them. 

Related problem (not sure if the cause is the same): the AI (major as well as minor civs) do not attempt to re-capture their captured civilians, even if they have a unit literally standing right next to them and the civilians don't attempt to run away. See screenshots below for examples.

_4. Steps to reproduce (optional):_
/

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
/
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
/
3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
/
4. Screenshots (optional):

    Example 1:

    ![image](https://user-images.githubusercontent.com/9011748/103130363-b3c7f280-469c-11eb-85bb-e10e52b360aa.png)
    ![image](https://user-images.githubusercontent.com/9011748/103130434-fee20580-469c-11eb-80d0-d3c8b0c75880.png)
    ![image](https://user-images.githubusercontent.com/9011748/103130500-38b30c00-469d-11eb-81fd-fa0788feee5b.png)

    Example 2:

    ![image](https://user-images.githubusercontent.com/9011748/103130027-3d76c080-469b-11eb-8bf1-4b89f9190497.png)
    ![image](https://user-images.githubusercontent.com/9011748/103130179-df96a880-469b-11eb-8047-328088bb7d10.png)
    ![image](https://user-images.githubusercontent.com/9011748/103130188-ee7d5b00-469b-11eb-81f4-a65330db20e1.png)

**Comment by ilteroi** [comment]
well that seems to have been the case for quite a while ... anyway should be better now
