### ISSUE TITLE
Epona's yields on tile claim don't scale

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#7329]
_1. Mod version : 12/1

_3. Error description:_ Epona Celtic Pantheon's yields from tile claim don't scale with era even though they say they do.
The yields used to scale, but were changed incidentally, because Epona uses the same yield table as God of the Expanse. God of the Expanse was changed so that it did not scale with era, because it was too strong in the mid/late game. This change affected Epona, even though the remifications to the Celts and Epona were never discussed when the change was made.

Since Epona is a Celtic UA pantheon, it is more similar to Russia's science on tile claim, so I think it **should** scale. Maybe a boolean ScalesWithEra column can be added to Belief_YieldPerBorderGrowth?

**Comment by HungryForFood** [comment]
#7398
