### ISSUE TITLE
On Sovereignty

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#733]
As mentioned, here are my Sovereignty requests. There are a few here, so please take your time. However, most do the same, generic thing in caching a specified value in the DLL and retrieving it, so hopefully nothing here is too much of a request. I may request more specific functions in the future, but for now these are all the generic functions I make use of in Sovereignty, which otherwise rely upon third party caching. I really appreciate your help on this, so of course let me know if there's any way I can return the favour.

**Player:SetGovernment(value)** 
**Player:GetGovernment()** -- returning the above value
**Player:HasGovernment()** - returning true or false on whether the above value is greater than -1/nil
**GameEvent.PlayerAdoptsGovernment(playerID, value)**
The value here would correspond to the value set in SetGovernment, naturally. These will be generic integers to the DLL, but they'll correspond to a custom set of IDs in my mod.

**Player:SetSovereignty(value)**
**Player:ChangeSovereignty(value)**
**Player:GetSovereignty()**

**Player:SetReformCooldown(value)**
**Player:ChangeReformCooldown(value)**
**Player:GetReformCooldown()**
**GameEvent.ReformCooldownChanges(playerID, currentCooldown, cooldownChange)**

**Player:ChangeGovernmentCooldown(value)** 
**Player:SetGovernmentCooldown(value)** 
**Player:GetGovernmentCooldown()**
**GameEvent.GovernmentCooldownChanges(playerID, currentCooldown, cooldownChange)**

**Player:SetPoliticLeader(ID, text)**
**Player:GetPoliticLeader(ID)**
**Player:SetPoliticPercent(ID, value)**
**Player:GetPoliticPercent(ID)**
Here, the first parameter: 'ID' would just be a generic integer that I would use to correspond to a custom ID in the database. When GetPoliticX is called, the ID specified in that function should pull the text/value of that ID established in the SetPoliticX function.

**GameEvent.GreatWorkCreated(playerID, unitID, greatWorkID)**

**Comment by LoneGazebo** [comment]
I'll work on these this week, shouldn't be too bad. The 'ID' in the last 4 is just an int value? Do you need an enum for that?

When you are ready for AI stuff, I need you to make me some flow charts (or at least logic charts) regarding how you want the AI to behave. This will be a bit more complex, so my plan here is to write (and annotate) the base code and upload it to you for 'proofing' (to see if it makes sense) before I try to deploy/test it.

G

**Comment by JFDaly** [comment]
Thanks. Yup, the last four just need a integer value. It corresponds to a specific Political Party ID as defined in a custom table. At the risk of exposing my lack of technical expertise, would I need an enum for that?

**Comment by LoneGazebo** [comment]
Nah, as long as you know the numbers and they don't change (and the DLL doesn't specifically need to know them), you shouldn't need an enum. You (essentially) have a pseudo-enum with that table.

G

**Comment by JFDaly** [comment]
The IDs don't change and I pull them from the table, so a simple integer will do.

**Comment by LoneGazebo** [comment]
Cool.

**Comment by LoneGazebo** [comment]
are there any max or min values you need for sovereignty? Much like piety?

**Comment by JFDaly** [comment]
Nope. Sovereignty doesn't accumulate - it's a global calculation of various factors. So there is no Sovereignty rate to worry about, nor a min/max.

**Comment by LoneGazebo** [comment]
Sounds good.

**Comment by LoneGazebo** [comment]
Also, with politicleader, what kind of text? A CvString? strKey?

**Comment by JFDaly** [comment]
A strKey. Something like 'TXT_KEY_JFD_POLITIC_LEADER_1' would be used.

**Comment by LoneGazebo** [comment]
Also, with regards to the politic leader/politic ID stuff, I need bounds for the size of the table.

**Comment by LoneGazebo** [comment]
Excellent, strkey is easy enough.

**Comment by LoneGazebo** [comment]
Ah, well, not exactly - I forgot that you can't use non-integers in a vector like that. Hmm...

**Comment by JFDaly** [comment]
How about a Player:SetPolitic(ID, value1, value2)? Then I could just correspond value2 to a leader string with that number and value1 to the percent I would've otherwise set in Player:SetPoliticPercent(), and all three values can just be simple integers in a single function.

**Comment by LoneGazebo** [comment]
It'll be easier, honestly, to just have the strkey be a separate set function - that way you have more control over the values in the event the integer values on your strkey table change.

**Comment by LoneGazebo** [comment]
So you'll have  SetPoliticLeader(int iID) and  SetPoliticLeaderKey(strKey).

**Comment by JFDaly** [comment]
Sounds good.

**Comment by LoneGazebo** [comment]
Alright, done. I'll test some things, make sure everything is initializing properly, then I'll link you a copy for debug.

G

**Comment by LoneGazebo** [comment]
And here's your debug copy. All events and lua functions are named as you indicated above, and I did add two functions for the politicleader stuff:

player::GetPoliticLeader() returns int
player::SetPoliticLeader(int iValue) requites an int
player::GetPoliticLeaderKey returns a cvstring
player::SetPoliticLeaderKey needs a cvstring (const* char, technically)

https://drive.google.com/file/d/0BwqQJAI2m04UcF9wZllfbmJTYnc/view?usp=sharing

**Comment by JFDaly** [comment]
A few issues:

All three Game Events appear to return a boolean as its second parameter, instead of the integer relating to the cooldowns triggered by ChangeReform/GovernmentCooldown/SetGovernment(). The first two also don't trigger on SetReformCooldown/SetGovernmentCooldown, only on the equivalent Change functions.

**GetGovernment()** doesn't appear to have been implemented. When trying to call, I get a "attempt to call method 'GetGovernment' (a nil value).

**GetPoliticPercent** appears to only store the first integer. e.g. I set Player:SetPoliticPercent(1,10) and Player:GetPoliticPercent(1) returns 1, instead of 10. I set Player:SetPoliticPercent(5,50) and GetPoliticPercent(2) returns 5, instead of 50.

Everything else works perfectly, however.

**Comment by LoneGazebo** [comment]
I'll check those out later tonight and send you a fresh version when setup. GetGovernment may be a typo on my end, or perhaps the lua flibbed.

I misunderstood politic percent – I see it now (I set it up as a simple int, and you needed a vector).

G

**Comment by JFDaly** [comment]
Also, I forgot to mention, could I request the following functions relating to the cooldowns:

**Player:GetReformCooldownRate()**
**Player:ChangeReformCooldownRate(value)**
**Player:SetReformCooldownRate()**
**Player:GetGovernmentCooldownRate()**
**Player:ChangeGovernmentCooldownRate()**
**Player:SetGovernmentCooldownRate()**

And then like with Piety have these rates subtract from the cooldowns each turn (going no lower than 0). They slipped my mind before.

**Comment by LoneGazebo** [comment]
I assume the cooldown rates will be positive integers, as I'll have them subtracted (i.e. made negative) in the rate functions.

**Comment by JFDaly** [comment]
Yeah, the rates will always be subtracting from the Cooldown value.

**Comment by LoneGazebo** [comment]
Figured so. Alright, new version inbound. Should all be in (and fixed), but we'll see. Took the liberty of adding event hooks for you in the new functions, figured they might be useful.

**Comment by LoneGazebo** [comment]
These are the names of the event hooks:

#define GAMEEVENT_PlayerAdoptsGovernment    "PlayerAdoptsGovernment"
#define GAMEEVENT_ReformCooldownChanges     "ReformCooldownChanges"
#define GAMEEVENT_GovernmentCooldownChanges "GovernmentCooldownChanges"
#define GAMEEVENT_ReformCooldownRateChanges     "ReformCooldownRateChanges"
#define GAMEEVENT_GovernmentCooldownRateChanges "GovernmentCooldownRateChanges"
#define GAMEEVENT_GreatWorkCreated          "GreatWorkCreated"

They are setup as you indicated above.

**Comment by LoneGazebo** [comment]
And here we go: https://drive.google.com/file/d/0BwqQJAI2m04URjJOdWozaUx0TjA/view?usp=sharing

**Comment by JFDaly** [comment]
Hm, GetPoliticPercent still only returns the first integer in SetPoliticPercent. And none of the CooldownRate() functions work (so haven't been able to test the new events, save GreatWorkCreated, which works). Everything is functional, though.

**Comment by LoneGazebo** [comment]
Ah, there was a typo in the lua for setpoliticpercent and the methods were missing. Blech. I'll fix tomorrow. Too sleepy to work on it now! :)

G

**Comment by LoneGazebo** [comment]
And here we go: https://drive.google.com/file/d/0BwqQJAI2m04UUVZ3N1RyZVdzVVU/view?usp=sharing

**Comment by JFDaly** [comment]
Excellent, that fixes the PoliticPercent thing. The only thing left is the ReformCooldown and GovernmentCooldown don't naturally change with the Rates set in ReformCooldownRate/GovernmentCooldownRate. But the game events covering those rate changes work perfectly.

**Comment by LoneGazebo** [comment]
Hm, they should - did you enable the 'BALANCE_CORE_JFD' value in the custommodoptions.xml?

**Comment by JFDaly** [comment]
Ah, of course. I was using the incorrect version of Piety to test. No problem then. So, everything works perfectly.

**Comment by LoneGazebo** [comment]
With that value enabled, it works? Good to hear.

G

**Comment by JFDaly** [comment]
Yup.

**Comment by LoneGazebo** [comment]
Awesome. As always, glad to help.

**Comment by JFDaly** [comment]
Starting work on Sovereignty, so fair warning that I may come across new functions that I could use. I say this mostly because there was one that I forgot about:

**Player:SetLegislatureName(cvstring)**
**Player:GetLegislatureName()**

This would save a key similar to PoliticLeader, but this time it should be easier to implement.

This is the last of the pre-existing functions that were using TableSaverLoader - the third party caching utility - that i think you can help with. The other two I think are too complex for the DLL, as they store tables.

**Comment by LoneGazebo** [comment]
"too complex for the DLL" - is that a challenge? :)

Sounds good, I'll add these functions to the version of the CP I'll be pushing out today. 

The DLL can definitely handle tables, by the way - we'd just need to make you a custom table in the DLL. If it doesn't affect performance, though, there's little reason to do it.

G

**Comment by JFDaly** [comment]
Excellent, thank you.

Actually, it looks like I probably won't even need those table functions, now that I have Player:SetPoliticPercent. Between that and the database table which holds all the politics (the different political parties), I should be able to replace the tables I was saving entirely.

**Comment by JFDaly** [comment]
Here's an oddity: when using SetGovernment() it increases the value of GetGovernment(). For instance, SetGovernment(1) and then SetGovernment(2) results in GetGovernment() ==  3, instead of 2.

**Comment by LoneGazebo** [comment]
Fixed - a rogue plus had breached my code. I put it down, with prejudice.

G

**Comment by LoneGazebo** [comment]
Everything good to go?

**Comment by JFDaly** [comment]
Yup, everything's working.

**Comment by JFDaly** [comment]
Ah, one thing (Piety related) is that the GreatWorkCreated event seems to increase the playerID each time a great work is created. So, I'll expend a Great Prophet for a great work, and it'll at first pass 0 as the ID (correctly), but then the next GP will pass 1, then 2, and so forth.

**Comment by LoneGazebo** [comment]
I'll look at that event - right now it returns the unit's id, not the player, so I'll change that. The ID is an int, and looks right on the DLL-end of things.

**Comment by JFDaly** [comment]
Oh gotcha. I could probably pull the player's ID directly from the unit, but having the event pass it would makes things easier. Explains why greatWorkID always return nil, too. Thanks.

**Comment by LoneGazebo** [comment]
Cool. Will fix.
