### ISSUE TITLE
Faith ruins after founding a religion

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#7330]
Latest version. Got a huge chunk of faith on standard speed turn 241, waaaaaay after everyone's got and enhanced their religion.

![image](https://user-images.githubusercontent.com/14953746/103174424-fbb56800-489c-11eb-9443-ea5c0ea746c9.png)

**Comment by RecursiveVision** [comment]
I already fixed this.

**Comment by azum4roll** [comment]
Wow that was quick.
