### ISSUE TITLE
Possible bug with CvGame::getSmallFakeRandNum(int iNum, int iExtraSeed)

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7336]
Bit of a weird one but city state unique units were not always being activated at the start and then the only thing I changed was adding a larger iNum for when getSmallFakeRandNum( was called and that seemed to completely fix it.

I found that adding a large int to the result of getSmallFakeRandNum( also worked, however multiplying the result of getSmallFakeRandNum( didn't help.

Is it possible that it returns negative numbers sometimes if iExtraSeed is much larger than iNum?

int CvGame::getSmallFakeRandNum(int iNum, int iExtraSeed)
{
	unsigned long iState = getGameTurn() + abs(iExtraSeed);

	/*
	//safety check
	if (iState == giLastState)
		OutputDebugString("warning rng seed repeated\n");
	giLastState = iState;
	*/

	int iResult = 0;
	if (iNum > 0)
		iResult = hash32(iState) % iNum;
	else if (iNum < 0)
		iResult = -int(hash32(iState) % (-iNum));

	/*
	FILogFile* pLog = LOGFILEMGR.GetLog("FakeRandCalls2.csv", FILogFile::kDontTimeStamp);
	if (pLog)
	{
		char szOut[1024] = { 0 };
		sprintf_s(szOut, "turn %d, max %d, res %d, seed %d\n", getGameTurn(), iNum, iResult, iExtraSeed);
		pLog->Msg(szOut);
	}
	*/

	return iResult;
}

**Comment by ilteroi** [comment]
what? i don't understand.

**Comment by Mileslewis** [comment]
i'm asking if it's possible that it sometimes returns negative values if iExtraSeed is much higher than iNum. Because increasing iNum got rid of a bug I was having.

**Comment by ilteroi** [comment]
not really. the return value of hash32 is an unsigned long.

if the results are not random enough, it's typically because the seed is not varying enough.

**Comment by RecursiveVision** [comment]
Interesting, I guess I'll increase the randomization for flavors...

**Comment by Mileslewis** [comment]
If it's not that then there must be something weird with the PseudoRandomChoiceByWeight( function in CvGameCoreUtils.h which is where these random values were being sent:

PseudoRandomChoiceByWeight(vector<OptionWithScore<T>>& candidates, const T& defaultChoice, int maxCandidatesToConsider, int randomSeed)
{
	if (candidates.empty())
		return defaultChoice;

	if (candidates.size() == 1 || maxCandidatesToConsider == 1)
		return candidates[0].option;

	size_t maxCandidates = min(candidates.size(), (size_t)maxCandidatesToConsider);
	sort(candidates.begin(), candidates.end());
	reverse(candidates.begin(), candidates.end());

	int totalWeight = 0;
	for (size_t i = 0; i < maxCandidates; i++)
		totalWeight += candidates[i].score;

	int index = GC.getGame().getSmallFakeRandNum(10, randomSeed);
	int selectedWeight = (totalWeight*index) / 10;

	int weight = 0;
	for (size_t i = 0; i < maxCandidates; i++)
	{
		weight += candidates[i].score;
		if (weight > selectedWeight)
			return candidates[i].option;
	}

	return defaultChoice;
}

Though I can't figure out why it would arbitrarily want higher values. And like I said multiplying the value from getSmallFakeRandNum( probably made it worse while adding an int after also sorted the issue.

**Comment by RecursiveVision** [comment]
@Mileslewis If you run the debugger you can track the value of variables line by line, so you can see where the problem is.

**Comment by ilteroi** [comment]
it's called fake random number for a reason .. all it does is, it takes a seed and maps it to a pseudorandom number in the desired interval. changing the input seed has hard-to-predict effects on the output. but that's it. if you call this function multiple times in succession with the same seed you will get the same result.

**Comment by RecursiveVision** [comment]
(However, ilteroi did alter this for next version so that it changes on each player's turn rather than each game turn...)

**Comment by Mileslewis** [comment]
Just want to say I found out what the issue is and it wasn't this function.
