### ISSUE TITLE
Sometimes can't lock worked tiles

### ISSUE THREAD

**Issue by sgtslick** [LoneGazebo/Community-Patch-DLL#7337]
Dec 2020 Version
Sometimes I can't lock tiles in my cities. 

![cant lock tile](https://user-images.githubusercontent.com/9771207/103433968-2f521280-4c4e-11eb-8014-9d4b928c1d44.png)

**Comment by RecursiveVision** [comment]
Hard to diagnose the issue with only that to go on...are you sure double clicking doesn't fix it?

**Comment by Mileslewis** [comment]
happens why you have already locked a tile which another city 'steals' from this city. So in this case you probably had one of those tiles on the right locked but now they are worked by the other city. You can get rid of it by locking those tiles again and then unlocking them.

Unfortunately it can also happen when you get great general'd and then you are stuck with it like this.

**Comment by psparky** [comment]
Resetting the tiles also works, but you then have to lock them all again.

You can mostly avoid this situation by unlocking a tile in one city before switching it to a different city.

**Comment by ilteroi** [comment]
should be fixed
