### ISSUE TITLE
Lategame Great Artist can have enormous strength

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7339]
i just had a great artist with a strength of over 400k.

is that intended? it seems to hinge on the fact that it scaled with the tourism/gap output of the last ten turns ... how about we use the average over the last turns instead?

also, it seems like if you gain a second artist shortly after spending the first it will be even stronger? intended?

**Comment by RecursiveVision** [comment]
I venture to guess that it is not intended. Should also examine if the instant tourism yields from historic events are based on the average of the last ten turns (as the description says) or the total (like Great Artists apparently are).
