### ISSUE TITLE
Piety CTD

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#734]
I had one CTD whilst running an AI-only game with Piety. It could be an anomaly, and the game resumed upon reloading (and continued to run as normal until victory occured), so it might be something to ignore. But I was hoping you could take a look and see if there's anything of note in the [mini dump](https://www.dropbox.com/s/007rcyut1f7hvqw/CvMiniDump.dmp?dl=0). Thanks.

P.S. Is there anyway that I can actually read these for myself?

**Comment by LoneGazebo** [comment]
Yeah, you just need to get visual studio 2010 express and set up the DLL files. If you then load the minidump as a project and 'run' the debug, it'll point to your CTD spot.

G

**Comment by JFDaly** [comment]
I followed the instructions [here](http://forums.civfanatics.com/showthread.php?t=528319), however, all I got when I tried to compile the CvGameCoreDLL.vs2010 project were a bunch of "X.pdb" was not found. Piety crashed a second time, so it'd be good to get to the bottom of it.

**Comment by LoneGazebo** [comment]
If you have the civ SDK installed, copy the gamecore source folder (with the DLL files in it) into your Visual Studio 2010 folder, then overwrite it with the project files from github. After that, it should (theoretically) work.

**Comment by JFDaly** [comment]
Honestly, I've no idea what I'm doing. I'll just have to try and find it in the Lua.

**Comment by JFDaly** [comment]
Fortunately, I think I found the issue, and there might be a way you can help. 

I have a custom mission for the Great Prophet which allows them to be expended for Piety (AI does this automatically under certain conditions). When this is done, it also creates a Great Work of Art (a relic of sorts). However, the process of getting that relic into a Great Work slot is very complicated, and I think herein lies the issue (at least, I was able to run several games with no CTDs with this completely disabled, otherwise not). 

So would it be possible for you to create a **GameEvents.UnitCreatesGreatWork(playerID, unitID, greatWorkID)** game event? It would bascially be the GreatPersonExpended event, but specifically for when the unit is expended for a Great Work. Then I can just reverse my mission - Piety is awarded when the Prophet is expended for the Great Work - and I wouldn't have to jump through hoops to find a slot.

**Comment by LoneGazebo** [comment]
I'll take a look at the dump file myself. I think it might be worth it to see if you can get the DLL to compile: http://forums.civfanatics.com/showthread.php?t=528319

**Comment by JFDaly** [comment]
Thanks, I thought I'd tracked down the crash, but I was mistaken.

I did try to compile the DLL, but it threw "this.pdb was not found" a hundred times. I'll try re-compiling, though.

**Comment by JFDaly** [comment]
Ugh, now it's doing the time I hate most and not crashing after three games, with nothing changed. But I do have one request to make things a bit more efficient, a **GameEvents.GreatWorkCreated(playerID, unitID, greatWorkID)** event that basically acts like the GreatPersonExpended event, but specific to when a Great Work is created. Would something like this be possible?

**Comment by LoneGazebo** [comment]
How many of those errors are you getting? If they're just warnings, they are benign (there are 31 warnings that always happen when you compile the DLL).

I'll look at event - mind adding it to your list in the sovereignty request list? It'll help me keep them organized.

G

**Comment by JFDaly** [comment]
I dunno how many, perhaps 31. But at least trying to compile CvGameCoreDLL_Expansion2 results in a failure with the following errors:

1>FLuaFStringSupport.h(25): error C2027: use of undefined type 'FStringA'
1> FDataStream.h(25) : see declaration of 'FStringA'
1>FLuaFStringSupport.h(25): error C2027: use of undefined type 'FStringA'
1>FDataStream.h(25) : see declaration of 'FStringA'
1>FLuaFStringSupport.h(26): error C2027: use of undefined type 'FStringA'
1>FDataStream.h(25) : see declaration of 'FStringA'
1>FLuaFStringSupport.h(26): error C2228: left of '.c_str' must have class/struct/union
1>FLuaFStringSupport.h(36): error C2079: 'sConverted' uses undefined class 'FStringA'
1>FLuaFStringSupport.h(37): error C2027: use of undefined type 'FStringW'
1> FDataStream.h(26) : see declaration of 'FStringW'
1>FLuaFStringSupport.h(37): error C3861: 'CopyToUTF8': identifier not found
1>FLuaFStringSupport.h(38): error C2228: left of '.c_str' must have class/struct/union
1>type is 'int'
1>FLuaFStringSupport.h(51): error C2027: use of undefined type 'FStringW'
1> FDataStream.h(26) : see declaration of 'FStringW'
1>Include/FLuaFStringSupport.h(51): error C2027: use of undefined type 'FStringW'
1> FDataStream.h(26) : see declaration of 'FStringW'
1>FLuaFStringSupport.h(48): error C2079: 'sConvert' uses undefined class 'FStringW'
1>FLuaFStringSupport.h(49): error C2228: left of '.CopyUTF8' must have class/struct/union
1>type is 'int'
1>FLuaFStringSupport.h(55): error C2027: use of undefined type 'FStringW'
1>FDataStream.h(26) : see declaration of 'FStringW'
1>FLuaFStringSupport.h(55): error C2228: left of '.c_str' must have class/struct/union

**Comment by LoneGazebo** [comment]
Odd. Ilteroi's working on a few changes, and I am as well – let me get these changes on github tomorrow or so and we'll try again then. Until then, lemme see if I can reproduce a crash with Piety on.

G

**Comment by JFDaly** [comment]
Here's the latest [build](https://www.dropbox.com/s/hk6fy4rbk3hb9mr/JFD%27s%20Piety%20and%20Sovereignty%20%28Piety%29%20%28v%207%29.civ5mod?dl=0).

**Comment by LoneGazebo** [comment]
I'll see what it does. Thanks! Any special settings I need to enable or anything?

**Comment by JFDaly** [comment]
Nope, all settings are already setup.
