### ISSUE TITLE
New Barb Camp destroy underlying luxury resource

### ISSUE THREAD

**Issue by MIS-g** [LoneGazebo/Community-Patch-DLL#7340]
_1. Mod version (i.e Date - 12/1):_ 12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  New Barb Camp was formed between T83 and T84.  It destroyed the luxury resource that was there.

_4. Steps to reproduce (optional):_ Start with T83 game.  Press "next turn".  Look at T84.
[Askia_0084 BC-0775 and 0083.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5759449/Askia_0084.BC-0775.and.0083.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by CokolwiekUnni** [comment]
Have you played until you destroyed that camp? I am nearly 100% sure it would come back, I had this with them spawning on pastures, bananas etc. It is just hiddden until the camp will be cleared and not visible in any tooltip.
