### ISSUE TITLE
OCC Strategy Change

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7341]
@ilteroi You changed line 3502 of CvEconomicAI.cpp to:
```
if (pPlayer->isHuman() || GC.getGame().isOption(GAMEOPTION_ONE_CITY_CHALLENGE))
```
changing it from logical AND to logical OR...but the One City Challenge clearly states that "HUMAN players are only allowed to ever control one city". It doesn't apply to the AI.

**Comment by RecursiveVision** [comment]
And likewise with line 3534...

**Comment by ilteroi** [comment]
oh. my bad. i was confused because the whole check does not make sense ... the function is never called for human players. will fix
