### ISSUE TITLE
CTD No Reason any Civ Vox EUI 12/1

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#7342]
_1. Mod version (i.e Date - 12/1):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_
Really Advanced Setup

_3. Error description:_ 
CTD completely random

_4. Steps to reproduce (optional):_
Ever since the 10/8 version of Vox I have been having random CTD issues. I can restart from last autosave and not have the issue, I can have CTD on turn 1 or turn 2000. Sometimes the game will play for 8 hours no issues other times I can get 3 crashes in 10 minutes. 

I've had it CTD on Click for Next turn, I've had it CTD when in city screen choosing my next item to build, I've had CTD happen when upgrading units.

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5759567/CvMiniDump.zip)

[Logs Files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5759571/Logs.Files.zip)

@LoneGazebo
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
that sounds like a memory issue to me. Try strategic mode, see how far you can get?
