### ISSUE TITLE
Way of transcendence +1500 production stuck/lost if changed

### ISSUE THREAD

**Issue by sgtslick** [LoneGazebo/Community-Patch-DLL#7343]
Not sure if this is intended and whether you need to anticipate changing eras so you can plan your production accordingly but it happened to me before too I recall and I think it needs to be changed. The issue is when you get into a new era and research a new technology quite often you are able to then build a new wonder only after researching that new tech. So in order to be able to build that new wonder with the bonus production yields from way of transcendence (founder belief) you have to have an empty production queue or already be building a different wonder to avoid having the production lost when changing as shown in the example here:
![overflow part 1](https://user-images.githubusercontent.com/9771207/103449274-fd968580-4cf9-11eb-8686-c6a60b87a661.png)
![overflow part 2](https://user-images.githubusercontent.com/9771207/103449279-071fed80-4cfa-11eb-9bba-d4500ab01c9c.png)

If I simply cancel the caravel here the 1500 production will be lost. The overflow from the caravel does not get applied to the wonder, I think its do to with production types not sure though, so like military units only overflow into other military units etc, that's what it's like in alpha centauri anyway :) 

So in terms of gameplay, I guess I have to load, start producing public works, and then change. Ill test that now and see..
**Simply changing doesn't work but constructing the public works allows the production to overflow at least.

**Comment by Mileslewis** [comment]
Overflow caps at the production cost of what you just built, or your production per turn depending on what's higher. So you can overflow from the caravel but only up to it's cost, Public works costs more so that's why you were able to get more production from it the overflow from that.

**Comment by sgtslick** [comment]
I see thanks. So is not being able to change production once you receive the free production a bug or is that just how instant yields work? If that's how all instant yields work then it's not really a bug just a balancing issue with way of transcendance - buyer beware kinda thing which I'm cool with tbh.

**Comment by azum4roll** [comment]
There's no way the AI can learn to do this...

**Comment by CokolwiekUnni** [comment]
> There's no way the AI can learn to do this...

If that's true for insta production yields boths from things like way of transcendence/goody huts and ABCs, then the Milae's case for rebalancing difficulty has gained a lot of strength, tough a still support substantial ABC in early game along with it and use them in my testing.

If the AI can't use production intelligently from the belief, should it be changed? My answer is yes, even when AI is very rarely taking it, if ever.

**Comment by bentakacs** [comment]
You don't lose the production. Yes, if you switch the queue immediately it seems like that, maybe it's related to a buffer where overflow is kept or simply how instant yields are being applied in a single Turn (I haven't looked at the code yet so just guessing). I'm sure however if you finish the Caravel, the next Turn the remaining cost of the wonder will be much lower.

I just did a quick testing where a worker is first in queue followed by the Mausoleum of Halicarnassus with 18 Turns. CS quest with lot of production is procced, worker 1 Turn, wonder 18 Turns, even if I switch their order. However, next Turn worker is finished and the wonder has 12 remaining Turns.

I'm 99% sure that you don't lose production. Should it be applied "immediately", regardless of queue order is a good question tho. I'm personally fine how it is right now.

**Comment by sgtslick** [comment]
as mileslewis said above, the overflow is capped at production cost of first item, so in your example you can only overflow up to the cost of the settler into mausoleum. My caravel cost 160 with overflow of 1472. So i would lose like 1300 minerals.
