### ISSUE TITLE
Question for ilteroi

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7345]
I see you've rewritten a bunch of CvGlobals.cpp...

Suppose I delete globals that are never referenced in the DLL from the CvGlobals files (but _not_ from the SQL database, Gazebo already noted that would break SQL files in modmods), would that cause any problems? There are a bunch of unused defines there getting in the way of the actually used ones...

**Comment by RecursiveVision** [comment]
My intuition says "no" because CvGlobals searches the database but it doesn't seem like that happens the other way around...but thought I'd check.

**Comment by ilteroi** [comment]
no problem here

**Comment by RecursiveVision** [comment]
heh :)

Is that a reference?

**Comment by ilteroi** [comment]
nothing to see here, move along

**Comment by RecursiveVision** [comment]
lol

**Comment by RecursiveVision** [comment]
@ilteroi Ok, I deleted all the unused global defines from the DLL. And it only took me all night! :)

_AND THEY CALLED ME MAD..._
