### ISSUE TITLE
Cant bully with units inside your territory

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7347]
Feel like this was changed in the last few patches but seems like now your units have to be inside the city-state's or neutral territory for them to count towards local power bully score.

Seems like unnecessary complication to me and also I imagine it makes tributing quite hard for AIs.

Also tributing range is now 4 which is much smaller than it used to be. Not necessarily against that, though it can be tricky to actually get enough units within that range.

**Comment by ilteroi** [comment]
looking at the code, max pathlength is 5, and right of passage is explicitly ignored.

**Comment by Mileslewis** [comment]
Yea but that's how it's working in the game. Maybe the 5 includes the start and end tile. Not sure about the territory stuff.
