### ISSUE TITLE
City-State keeps selecting Defense with no threat in sight

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7348]
Genoa keeps selecting the Defense process (which it weights equally with Farming, at 50). King difficulty, despite there being no dangers in sight. It sometimes swaps to Farming but then back to Defense next turn.

Seems to be a random selection, but Defense should be weighted at 0 if there's no threats.
![1](https://user-images.githubusercontent.com/66801010/103519992-73a70380-4e44-11eb-9b95-06daef68aab1.png)
![2](https://user-images.githubusercontent.com/66801010/103520000-7570c700-4e44-11eb-888c-f19088c0ad21.png)
![3](https://user-images.githubusercontent.com/66801010/103520001-76095d80-4e44-11eb-8ccf-50fbbb842cc4.png)

**Comment by RecursiveVision** [comment]
Log attached - see entries from Turn 70 onwards
[CityStrategyAIProductionLog_Genoa_Genoa.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5763956/CityStrategyAIProductionLog_Genoa_Genoa.zip)

**Comment by LoneGazebo** [comment]
look at you, finally using the IDE! :)

**Comment by RecursiveVision** [comment]
I've been using it for a while now, but learning to use the debugger recently was a great asset :)
