### ISSUE TITLE
DoF fix

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7349]
in your latest commit you have

	int iMapSizeScaler = (int)(vValidPlayers.size() / 8);
	iFriendLimit *= max(1,iMapSizeScaler);

this seems weird? because the multiplier will always be 1 until you have 16 valid players, at which point it jumps to 2.

if you want a smooth scaling, it's probably better to do something like:

	iFriendLimit = max(1, (vValidPlayers.size() * iFriendLimit) / 8);

i didn't look at the rest of the code but integer truncation is annoying. so it's a good idea in general to do fixed-point math, basically multiply everything by eg 100 at the beginning and then do a final division to get it back to the intended range at the end.

anyway the gamecore seems to deliberately avoid floating point math because rounding errors could theoretically give different results in multiplayer depending on the machine you are playing on. in case you were wondering.

**Comment by RecursiveVision** [comment]
@ilteroi Yeah I noticed the weirdness, I already fixed 👍
