### ISSUE TITLE
Great Prophet Spawning

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#735]
This is an inquiry mostly on behalf of the Enlightenment Era mod. Great Prophet spawning stops at the Enlightenmnet Era, which takes the ID of the Industrial Era. I'm assuming, therefore, that Great Prophet spawning is hardcoded to end at the beginning of the Industrial Era. Is there a way you could confirm or deny this, and, if indeed this is the case, to push this out to a PostDefines value so that it can be modified?

**Comment by LoneGazebo** [comment]
That already exists in the CP courtesy Whoward - look in the CP's GameInXML.xml file in the Core Files/PNM Mods DB/CONFIG folder.

G

**Comment by JFDaly** [comment]
Ah, it didn't occur to me that that was what 'RELIGION_LAST_FOUND_ERA' was for. Thanks.

**Comment by LoneGazebo** [comment]
Should be the case - if it doesn't work as needed, let me know.
