### ISSUE TITLE
Reformation with inadequate number of followers

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#7350]
Latest version. Mongolia lost their holy city to me, captured Greece's holy city, and then immediately reformed next turn.

![image](https://user-images.githubusercontent.com/14953746/103547447-5d01ba80-4edf-11eb-8bf6-5f4d10bae126.png)
![image](https://user-images.githubusercontent.com/14953746/103547580-8fabb300-4edf-11eb-91c3-f8e0b33539d0.png)

**Comment by ilteroi** [comment]
did the mongolians have a reformation for tengrilism before?

**Comment by azum4roll** [comment]
Yes

**Comment by ilteroi** [comment]
corner case but fixed
