### ISSUE TITLE
Pledging to Protect decreasing experience rewards for city capture quest

### ISSUE THREAD

**Issue by ReanKW** [LoneGazebo/Community-Patch-DLL#7351]
_1. Mod version (i.e Date - 12/1):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_
3/4th component

_3. Error description:_ 

Pledging to protect a city state increased the influence reward but somehow decreased the XP gained for it.

_4. Steps to reproduce (optional):_

Pledge to Protect Budapest in the savegame, the experience rewards drops from 25 to 18.

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[Ashurbanipal_0229 AD-1595.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5767423/Ashurbanipal_0229.AD-1595.zip)

4. Screenshots (optional):
![Before](https://user-images.githubusercontent.com/21000723/103593635-a7426600-4ef6-11eb-964a-a1a6cf7ce4da.jpg)
![After](https://user-images.githubusercontent.com/21000723/103593645-ab6e8380-4ef6-11eb-8112-5e7d0f9dfd13.jpg)

**Comment by RecursiveVision** [comment]
The code recalculates quest rewards when a PTP is made, and there's a random element during each recalculation.

@LoneGazebo Is this functioning as intended?

**Comment by LoneGazebo** [comment]
all the code is refreshed, and there IS an RNG for the XP. All rewards are recalculated, but I should probably make it so that it can't go below when doing the recalc.
