### ISSUE TITLE
Multiplayer crash

### ISSUE THREAD

**Issue by Phosphoraptor97** [LoneGazebo/Community-Patch-DLL#7356]
_1. Mod version (i.e Date - 12/1):_
12/1 w/ latest hotfixes

_2. Mod list (if using Vox Populi only, leave blank):_
Modpack VP + EUI version from this thread:
https://forums.civfanatics.com/threads/multiplayer-mod-pack-12-1-hotfix-3-desync-lag-stability-fixes.663567/

_3. Error description:_ 

Games hard crashes at end of turn 146 regardless of actions

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482

):
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5770558/Lua.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[AutoSave_0145 AD-1550.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5770550/AutoSave_0145.AD-1550.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5770566/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
probably fixed
