### ISSUE TITLE
12-1 (Strategic AI) - Too many Catapults

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7358]
_1. Mod version (i.e Date - 12/1):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
AI is producing a LOT of catapults. At first it seems incredibly scary but ultimately it doesn't have stamina. Once I got my forces in the right place the catapult line starts to weaken. Further, there is a great lack of melee units (that one immortal just appeared and there was were 0 melee units around for 6 turns. That city could have been easily taken with just a few more melee.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/103690270-10a79080-4f5a-11eb-8621-2b4dbd7805dc.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by CokolwiekUnni** [comment]
![Civ5Screen0000](https://user-images.githubusercontent.com/75467145/103900517-2ce13400-50f8-11eb-9420-82344410b99e.jpg)

**Comment by LoneGazebo** [comment]
Likely an issue with flavoring for siege, but I don't know why. I'd need to see your unitproductionAI logs.

**Comment by Stalker012345** [comment]
Finally got one for you.

![image](https://user-images.githubusercontent.com/20593976/106403706-9d2c5e00-63f5-11eb-8a10-9fe1081886ac.png)
[Maria I_0122 AD-0175.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5901279/Maria.I_0122.AD-0175.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5901278/Logs.zip)
