### ISSUE TITLE
NumFreeLux

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#736]
Could you tell me what mod option enables the functionality of 'NumFreeLux,' which, in CBP, is what handles the Great Admiral's free luxuries mission. For the life of me I can't find it - I enabled every option and yet it still wouldn't work without the CBP.

**Comment by LoneGazebo** [comment]
It should just be the base option, though you need the UnitMission info (located here): Community Balance Patch/Balance Changes/Units/UnitChanges.xml

**Comment by JFDaly** [comment]
Ah, that was it. Thanks.
