### ISSUE TITLE
endless loop

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7361]
so i thought i'd give rsi another try, but i hit an endless loop (diplo ai line 14876)
```
			for (CvCity* pLoopCity = GET_PLAYER(ePlayer).firstCity(&iCityLoop); pLoopCity != NULL; GET_PLAYER(ePlayer).nextCity(&iCityLoop))
```

spot the error ... took me a while :)

```
			for (CvCity* pLoopCity = GET_PLAYER(ePlayer).firstCity(&iCityLoop); pLoopCity != NULL; pLoopCity 
 = GET_PLAYER(ePlayer).nextCity(&iCityLoop))
```

**Comment by RecursiveVision** [comment]
Oops!

I didn't encounter that in my testing, and I ran several test games for stability...really strange. But will fix, thank you.

**Comment by RecursiveVision** [comment]
Ahhhh, I see why. I forgot to enable vassalage. :)
