### ISSUE TITLE
12/1 - (Old Issue, New Version) AI not settling nice tundra spots

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7362]
_1. Mod version (i.e Date - 12/1):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I reported this in the last version, just showing that its still occuring. The AI has a gorgeous tundra space full of sheep, would make a very nice city that its ignoring. I tend to notice this most with aggressive civs.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/103802829-5ecd9a00-5015-11eb-9f5c-62cb16e80103.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
I actually wouldn't settle on most of the space except the coast (which is occupied by Sydney). Even with all the sheep you'd struggle to grow past 10 pop.

**Comment by CokolwiekUnni** [comment]
If the AIs are not settling there, even with their food/production bonuses, they are smart. Human would be able to make this location theoretically viable with prioritizing stable, food trade route, and having tundra pantheon or/and being Inca, but the city would probable never (or after like four eras) pay itself off in terms of invested gold/production/culture & science penalty and would be too disconnected from your other cities with all that this entails. In other words, even with those resources this would be a garbage city. By this turn and era progress AIs should need better location, tradition AIs shouldn't be interested in new cities, and authority AIs should be conquering, not founding their cities. Everything works as intended.

**Comment by azum4roll** [comment]
Better make sure Progress Inca does settle there though, if they're nearby.
