### ISSUE TITLE
Happiness bugged

### ISSUE THREAD

**Issue by ando310** [LoneGazebo/Community-Patch-DLL#7364]
_1. Mod version - CP 2019-07-17, no EUI

_2. Mod list - no other mods

_3. Error description: I'm encountering an issue where local happiness from new citizens is higher than unhappiness given and it is almost impossible for your empire to be unhappy as a result, happiness buildings/policies become completely irrelevant and you can settle new cities without luxuries forever. I've seen this reported several times on the steam forums, too.

_4. Steps to reproduce (optional): Happens every game

**Comment by RecursiveVision** [comment]
Very old version, probably fixed by now. Same goes for the Steam Workshop version.

Feel free to reopen if you encounter this in a recent version.
