### ISSUE TITLE
12/1 - AA Gun intercepts even while embarked

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7365]
_1. Mod version (i.e Date - 12/1):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I assume this is unintended. Even while embarked, the AA gun can intercept. This means a crafty player hiding their AA guns under a naval ship has unbeatable interception.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/103843643-cd364a80-505d-11eb-9ffb-25a17d64ed07.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Does it actually intercept or is it just an UI problem?

**Comment by ilteroi** [comment]
i have a theory ...
