### ISSUE TITLE
(Feature Request) Bombers should upgrade to B17 if "Their Finest Hour" is on

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7367]
_1. Mod version (i.e Date - 12/1):_
Feature request. Currently you cannot upgrade to B17, just build them. This severely limits their usefulness.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Vyyt02** [comment]
And Zeroes, and the Guerilla fighters of Order. I already asked for this on CivFanatics in the past, but overall most people said it would be nice, but did not care that much. And someone well versed with modding said it would not be easy to implement.

I tried tweaking WHoward's multiple upgrade paths minimod, but did notale it work for ideology restricted units.

If this can be solved, I'd be very happy - I thought I was the only one bothered by this. And I'd immediately add more ideology-specific units :-)

**Comment by phantommaxwell** [comment]
This would be very nice for Guerillas, as those units can be upgraded from, say a Samurai.

**Comment by HungryForFood** [comment]
I can add the necessary tables and logics, but is this something we agree should be in the game?

**Comment by RecursiveVision** [comment]
@HungryForFood I think it'd be pretty cool. You can always add an option to disable it. :)

**Comment by Vyyt02** [comment]
@HungryForFood , I understand some people don't care about this, but I cannot imagine someone would actually be against it.

While you are at it, would it be possible to add an option (for mod-modders) to have ideology-specific units? (Now we have only policy/tenet-specific units, the opening ideology cannot be assigned to a unit, correct?)

**Comment by HungryForFood** [comment]
Have you tried assigning a FreePolicy to the ideology in PolicyBranchTypes, and have that policy unlock the unit?

**Comment by Vyyt02** [comment]
@HungryForFood No, I have not, is this something I can learn from VP code? I don't think this is done anywhere...

**Comment by HungryForFood** [comment]
![image](https://user-images.githubusercontent.com/22621937/104808359-a081f000-5820-11eb-8c30-3a01e4a94aaf.png)

It is how the starter policies are granted.

**Comment by Vyyt02** [comment]
@HungryForFood Ooohh, this looks interesting. Thanks!
