### ISSUE TITLE
premature war declaration

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7368]
this is with the latest rsi:

i founded edirne close to orleans ... it seems napoleon did not appreciate that, because he immediately declared war. no complaints about expansion, just a straight war declaration.

![image](https://user-images.githubusercontent.com/1358966/103813620-b04f4680-5060-11eb-94ba-fc9dd325ea86.png)

however it took a few turns until his army (quite impressive for the early timing) arrived, giving me time to prepare.

it would probably have been better to do a sneak attack?

**Comment by RecursiveVision** [comment]
I rewrote "wants sneak attack" code but the "declare war" code should function the same, just a little cleaned up.

Perhaps he was bribed into war?

**Comment by RecursiveVision** [comment]
If you want to see if the AIs are planning war enable Debug Mode in the DiploAIOptions.sql file, it's finally working as intended :)

Also has several other useful functions, like activating Transparent Diplomacy, showing World Congress desire info, and forcing Share Opinion requests to succeed...may be useful to you

**Comment by RecursiveVision** [comment]
I also made some changes to observers, they should get more notifs and auto-succeed on share opinion requests too

**Comment by ilteroi** [comment]
i'm not sure i understand what you're saying but i got the third declaration of war from france now in turn 109.

luckily in the two previous wars he offered peace after ten turns or so, although he was close to capturing a city each time.

anyway, you really got to be on your toes ... is everybody as crazy aggressive as napoleon now?

**Comment by RecursiveVision** [comment]
@ilteroi They weren't in my test games, although I fixed a bug that was making them too peaceful so that may have changed...

If you find the AI too aggressive try commenting out the check in IsEarlyGameCompetitor() that calls GetNumSamePolicies(), that may have a strong effect. AI should also be making friends and DPs with each other now and respecting those limits.

To enable the diplo debug mode, go to Community Patch > Core Files > Core Changes > DiploAIOptions.sql, scroll down to the bottom and set to 1 or 2.

**Comment by ilteroi** [comment]
well, i'm asking for a friend ...

seriously, i didn't test it much but i think this is a critical point. and it's fine if a few leaders are hyperaggressive ... but maybe not gandhi :)

**Comment by RecursiveVision** [comment]
Yeah, point taken :)

I'll adjust aggression again, should be a simple fix

**Comment by RecursiveVision** [comment]
Made some adjustments...should be better now

**Comment by RecursiveVision** [comment]
@ilteroi Fixed some bugs and adjusted the logic...AI should no longer peace out so easily when about to take a city :)
