### ISSUE TITLE
GreatPersonExpended Question

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#737]
I wanted to ask what the conditions were that triggered GreatPersonExpanded. I had thought it were tied the Mission, to the EntityEventType as 'ENTITY_EVENT_GREAT_EVENT,' but this doesn't seem to be the case. Is there some other condition that I'm missing? The units which fire these missions are 'SPECIALUNIT_PERSON,' as well.

**Comment by LoneGazebo** [comment]
Yeah, any unit that is 'killed' by the DLL is checked for great person status. Function is independent of missions, but missions call for a kill function, so that's the link. What's the context of the question?

**Comment by JFDaly** [comment]
My Great Magistrate and Great Dignitary units don't seem to pass through the GreatPersonExpended function, except where the Great Dignitary is being expended for the Great Merchant's Trade Mission.

**Comment by LoneGazebo** [comment]
Okay, yeah, I was wrong. Functions called next to, but not by the kill function. What do you need? I could push GreatPersonExpended to lua.

G

**Comment by JFDaly** [comment]
Oh, no, don't worry about it. I don't need it for anything specifically - it was just for compatibilities sake for anyone using GreatPersonExpended for a generic 'on any Great Person expended, do this' function, so that my Great Dignitary and Great Magistrate would count (I have one such function in a custom civ of mine, but skipping these two is no big deal). I honestly thought I was missing something, so if there's actually work required, it's really no matter.

**Comment by LoneGazebo** [comment]
Ok - if it becomes an issue, exposing that function to lua is not a big deal.

G

**Comment by JFDaly** [comment]
As it turns out, I could use a fix to this issue, so that my Great Magistrate and Great Dignitary can indeed be passed through the function. Will exposing it to Lua help? (I don't know what's involved in that, any more than it is already exposed anyway). Thanks.
