### ISSUE TITLE
12/1 - Inquisitors are not reducing Passive Pressure

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7371]
_1. Mod version (i.e Date - 12/1):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I believe several versions ago, Inquisitors were supposed to adjust both active and passive foreign pressure. I have checked and confirmed that producing an inquisitor has no impact on passive pressure.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
is that so?

there is no code for this effect. it would be easy to add, but i'm not sure it's a good idea ... in the end there will be an inquisitor in every city. boring and equivalent to reducing passive pressure across the board.

now what could make it interesting is to limit the maximum number of inquisitors you can have, but that is another discussion.

alternatively, take a look at the RELIGION_PASSIVE_SPREAD_WITH_TRADE_ONLY option if you think passive spread is too dominant.

**Comment by Vyyt02** [comment]
@ilteroi , I'd swear Inqs were listed as reducing the passive spread in one of the recent patch notes.

**Comment by Stalker012345** [comment]
I found in the April 17 update that the 50% active spread reduction was added (which is not working currently btw). But I did not find anything on passive spread in the versions since March.

Perhaps it was in a preview or discussion post but never was made official.
