### ISSUE TITLE
Is Gold and Production from creating a Citadel intentional?

### ISSUE THREAD

**Issue by CokolwiekUnni** [LoneGazebo/Community-Patch-DLL#7372]
Expending a Great General for a Citadel provides Gold and Production in the Capital for each tile claimed.
Yields are ridiculous, I had created two citadels to start two sieges simultaneously on the same turn in Renaissance and I received IIRC 150 Gold and Production for each tile, standard size and speed. Started Himeji Castle, went from 17 turns to 2 turns.
Is it intentional? Authority is already very good at getting wonders through high production, usually developed capital, prioritizing bottom of the tech tree which wonders are less coveted by tradition AIs, and general AI neglect for certain wonders (Oracle, Angkor Wat, Terracotta Army, Colossus, Leaning Tower of Pisa).

**Comment by RecursiveVision** [comment]
@LoneGazebo

**Comment by LoneGazebo** [comment]
Yes, it is intended, this change was made some time ago.

**Comment by RecursiveVision** [comment]
Does seem pretty powerful though
