### ISSUE TITLE
swedish Trebuchet one-shot killed city based Comp Bowman

### ISSUE THREAD

**Issue by rhaidinger** [LoneGazebo/Community-Patch-DLL#7376]
[Swe_Tre.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5791573/Swe_Tre.zip)
_1. Mod version (i.e Date - 12/1):_12/1 + 1/9 Beta

_2. Mod list (if using Vox Populi only, leave blank):_Krajzen's Great Artists + Writers

_3. Error description:_ Not sure if its WAD: a swedish Trebuchet just one shot killed my city based Comp. Bowmen (no walls, no damage to city, unit before). 101 Damage. Haven't seen this before, but also my first game on Immortal (Large, Epic) Enclosed 2 screenshots before/after (this time I sent the units back an it only nearly killed the comp. bowman.) Seems Sweden is slightly overpowered. Didn't considered this.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by phantommaxwell** [comment]
What was the City's Strength?  If it was a Cannon attacking a City w/o Walls, I could believe it.  Once a unit has high enough Strength attacking a weak City, the City can easily take 2-300 dmg and the garrison will get 1 shot.

**Comment by rhaidinger** [comment]
It was 10 and a Great General (Swedish was around). I don't know why I can't upload the screenshots. I'll check

**Comment by ReanKW** [comment]
That damage seems about right tbh, doesn't look bugged

**Comment by RecursiveVision** [comment]
@ilteroi Does this look bugged to you? I didn't see garrisons getting oneshot in my testing, but I'm not sure...

**Comment by RecursiveVision** [comment]
With all those bonuses, plus the -33% penalty not applying, plus its bonus against cities, plus Sweden's attack bonus, it could have very high strength...

**Comment by azum4roll** [comment]
It looks right. A city on flat land without walls is like wet tissue.

**Comment by RecursiveVision** [comment]
Gonna flag this as intentional for now, the AI does have a lot of bonuses for that attack...
