### ISSUE TITLE
(Tactical AI) 1/9 Beta - AI is terrified of 1 scout

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7377]
_1. Mod version (i.e Date - 12/1):_
1/9 Beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
With just a single scout, the AI is now terrified to leave their base. They won't use the warrior to escort the settler to a spot, or to guard a worker so it can work.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/104107364-229e7180-5281-11eb-8e80-a6602627fa27.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Update: So what I am seeing now is that Ghandi has 5 warriors, but still remains passive. He keeps moving the worker back to the horse spot, but then immediately moves it back to the city even though he has a warrior on the spot guarding it.

**Comment by ilteroi** [comment]
how come you see all his plots?

**Comment by Stalker012345** [comment]
> how come you see all his plots?

My scout has vision promotions and there is a hill on the north side in that forest. I keep sweeping my scout that way which gives me vision
