### ISSUE TITLE
1/9 Beta - Crossbowmen not obsolete when Janissary is out

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7378]
_1. Mod version (i.e Date - 12/1):_
1/9 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
EAW (Asterix's advanced aircraft mod)

_3. Error description:_ 
I'm not sure if this is because of Ottomans UU or the issue is with muskets in general, but when I get access to the Janissary the crossbowmen has not obsoleted.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/104110225-3525a480-529b-11eb-90ec-7bf4dcd6d031.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
It's available earlier, but you can't upgrade until the Crossbowman is obsolete...
