### ISSUE TITLE
1/9 Beta - Can't trade anything for flat gold

### ISSUE THREAD

**Issue by ReanKW** [LoneGazebo/Community-Patch-DLL#7379]
_1. Mod version (i.e Date - 12/1):_
12/1 + 1/9 beta

_2. Mod list (if using Vox Populi only, leave blank):_
3rd/4th mod

_3. Error description:_ 
Got DoF with Genghis (right after we warred when I'm his only real target for conquest, seems questionable), but if I try to trade anything for flat gold, it won't let me offer anything for it. Can trade GPT just fine. Putting in f.e. copper and hovering over flat gold it says you can't have gpt and gold in the same deal.

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

[Elizabeth_0086 BC-0725.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5792035/Elizabeth_0086.BC-0725.zip)

**Comment by RecursiveVision** [comment]
Can't trade resources for lump sum Gold.

**Comment by RecursiveVision** [comment]
Tooltip will need to be updated, though...
