### ISSUE TITLE
Building_YieldChanges and Building_YieldModifiers

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#738]
Could you please check if Building_YieldChanges and Building_YieldModifiers have an unneeded >0 check? It seems that they do and won't allow negative yield values. If so, I would appreciate a fix to this when you get a chance. Thanks.

**Comment by LoneGazebo** [comment]
Building_YieldChanges had one for culture, but nothing else.

**Comment by JFDaly** [comment]
Sorry! I was actually a bit suspicious about this after some thought, and as it turns out, I was very much mistaken. I had thought it wasn't working because I hadn't noticed a change in the city yields (mostly because I'd not noticed any +-X in the ToolTip), but indeed they all work (even Culture).

**Comment by LoneGazebo** [comment]
Good to hear.
