### ISSUE TITLE
1/9 Beta CTD

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#7380]
_1. Mod version (i.e Date - 12/1):_
1/9 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
Really Advanced Setup
More Luxury Resources for VP

_3. Error description:_ 

_4. Steps to reproduce (optional):_
CTD during game

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Civ5 Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5792078/Civ5.Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5792079/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by HungryForFood** [comment]
@R3P0FFXI do you have a save file? Since you're running very few mods, I can try to load it.

**Comment by R3P0FFXI** [comment]
@HungryForFood No I do not have a save file I am just running off Autosaves, however the crashes still exist in 1/15 Beta
