### ISSUE TITLE
GetBlastTourism() stopped working

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#7381]
_1. Mod version - 1/9

_2. Mod list (if using Vox Populi only, leave blank): More Unique Components for VP

_3. Error description:_ I have a component that gives Japan a fraction of the Tourism blast yields from a Great Musician as an instant faith yields when it is born. This worked in previous versions, but doesn't work with the latest version. All other code works downstream from the bug, so it appears to just be returning 0 instead of causing an error, because the code completes and fires notifications and functions further down in the code. 

I tested GetGAPAmount() and GetGivePoliciesCulture() and they are both working. It's just GetBlastTourism().

_4. Steps to reproduce (optional):_
```
function JapGuildsExpendBonus(iPlayer, iUnit, iUnitType, iX, iY)
	local pPlayer = Players[iPlayer]

	if not (pPlayer and pPlayer:GetCivilizationType() == eCivilizationJapan) then return end

	local pUnit = pPlayer:GetUnitByID(iUnit)
	local pPlot = Map.GetPlot(iX, iY)

	if pUnit:GetUnitType() == GameInfoTypes.UNIT_MUSICIAN and (pPlayer:CountNumBuildings(eBuildingGagaku) > 0) then 
		local iMusicianBonus = math.floor(pUnit:GetBlastTourism()*0.03*pPlayer:CountNumBuildings(eBuildingGagaku))
		pPlayer:ChangeFaith(iMusicianBonus)

		if pPlayer:IsHuman() and pPlayer:IsTurnActive() then
			local vUnitPosition = PositionCalculator(iX, iY)

			Events.AddPopupTextEvent(vUnitPosition, "[COLOR_WHITE]+"..iMusicianBonus.."[ICON_PEACE][ENDCOLOR]", 1)

			pPlayer:AddNotification(NotificationTypes.NOTIFICATION_GENERIC,
				'A Great Musician has emerged. +'..iMusicianBonus..' [ICON_PEACE] Science from Gagaku guilds.',
				'Yields from Gagaku Guilds',
				iX, iY)
		end
	end
end

function PositionCalculator(i1, i2)
	return HexToWorld(ToHexFromGrid(Vector2(i1, i2)))
end

GameEvents.UnitCreated.Add(JapGuildsExpendBonus)
```
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
there is quite a bit of weird code in int CvLuaUnit::lGetBlastTourism() ... did you check that?

also canBlastTourism() must be true. and looking at how the strength is computed makes me feel ill so i'll go for a walk now.

**Comment by pineappledan** [comment]
I have no C++ experience, so I haven't dug into GetBlastTourism(), no

The code above already checks if the unit is a GMusician, so that should effectively do the same thing as checking CanBlastTourism().

**Comment by HungryForFood** [comment]
Checking around git blame, all the GetBlastTourism() stuff is old code, and MOD_BALANCE_CORE_NEW_GP_ATTRIBUTES has been activated since 2015.

Not sure what changed recently, I'll take a dive.

**Comment by HungryForFood** [comment]
You sure your lua is good? I see there's a multiply by 0.03 somewhere there, what if you turn that into an integer, like 1 for example?

From http://lua-users.org/wiki/MathLibraryTutorial:

```
math.ceil , math.floor
Return the integer no greater than or no less than the given value (even for negatives).

    > = math.floor(0.5)
    0
    > = math.ceil(0.5)
    1
    > = math.floor(-0.5)
    -1
    > = math.ceil(-0.5)
    -0
```

**Comment by HungryForFood** [comment]
So I'm looking at your Kabuki.lua now, you're saying the sections for Artists and Writers works right?

**Comment by HungryForFood** [comment]
Scratch whatever I said.

After I did a quick check, seems that there is a unit:GetTourismBlastStrength() and a unit:GetBlastTourism()

GetTourismBlastStrength() is the base strength which the Musician has, which in VP is set when it is created.

![image](https://user-images.githubusercontent.com/22621937/104441134-41c53800-55ce-11eb-9040-3a21e30110a1.png)

Then there is GetBlastTourism(), which attempts to calculate the actual amount of tourism you get with a civilization if you were to perform a concert tour. The civilization it uses to calculate is the one whose plot the Musician is standing on.

![image](https://user-images.githubusercontent.com/22621937/104441401-98cb0d00-55ce-11eb-80e5-069514629cdc.png)

Really confusing names unfortunately. And I say attempt, because the code for GetBlastTourism() is really messed up. For reference:

```
//int GetBlastTourism()
int CvLuaUnit::lGetBlastTourism(lua_State* L)
{
	CvUnit* pkUnit = GetInstance(L);
#if defined(MOD_BALANCE_CORE)
	if(MOD_BALANCE_CORE_NEW_GP_ATTRIBUTES && pkUnit && pkUnit->getBlastTourism() > 0)
	{
		CvPlayer &kUnitOwner = GET_PLAYER(pkUnit->getOwner());
		PlayerTypes eOwner = pkUnit->plot()->getOwner();

		if (eOwner != NO_PLAYER)
		{
			InfluenceLevelTypes eLevel = kUnitOwner.GetCulture()->GetInfluenceLevel(eOwner);
			if(eLevel <= INFLUENCE_LEVEL_EXOTIC)
			{
				int iTourismNeededForFamiliar = GC.getCULTURE_LEVEL_FAMILIAR() + 2;
				int iInfluenceOn = kUnitOwner.GetCulture()->GetInfluenceOn(eOwner);
				int iLifetimeCulture = GET_PLAYER(eOwner).GetJONSCultureEverGenerated();
				int iTourismDifference = 0;

				//Get % needed for Familiarity
				if (iTourismNeededForFamiliar > 0)
				{
					iTourismDifference = (iLifetimeCulture * iTourismNeededForFamiliar) / 100;
				}
				//Subtract existing %
				iTourismDifference -= iInfluenceOn;
				lua_pushinteger(L, iTourismDifference);
				return 1;
			}
		}
	}
#endif

	const int iResult = pkUnit->getBlastTourism();
	lua_pushinteger(L, iResult);
	return 1;
}
```

For example, this part: `if(eLevel <= INFLUENCE_LEVEL_EXOTIC)` makes no sense, as it only includes INFLUENCE_LEVEL_EXOTIC, INFLUENCE_LEVEL_UNKNOWN, and NO_INFLUENCE_LEVEL.

Then, this `int iTourismNeededForFamiliar = GC.getCULTURE_LEVEL_FAMILIAR() + 2;` makes no sense because `GC.getCULTURE_LEVEL_FAMILIAR()` is just 5 in Defines.

I'll refactor CvLuaUnit::lGetBlastTourism(). On the other hand, @pineappledan you should use unit:GetTourismBlastStrength() as it should match what you're going for better.

**Comment by pineappledan** [comment]
Yes, I tried just changing the multiplier amount from 0.03 to 3, but 0*1 and 0*100 are both still 0 

Okay, yeah looks like I was using the wrong one in that case, because the GMusician will always be standing in one of your own cities

**Comment by HungryForFood** [comment]
It was broken just enough that it gave you a seemingly good result. In actual fact the method did not give a useful number at all.

#7398
