### ISSUE TITLE
diplo weirdness

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7383]
1. it seems there is a typo in DoMakeWarOnPlayer(). what is meant here?

```
			bWantToAttack = (GetCSWarTargetPlayer() == eTargetPlayer);
			bWantToAttack = (GetCSBullyTargetPlayer() == eTargetPlayer);
```

the reason why there are no bully operations anymore is that plain attacks are launched instead because bWantToAttack is set to true for bully targets.

2. what is the difference between GetCSBullyTargetPlayer() and MINOR_CIV_APPROACH_BULLY anyway?

**Comment by RecursiveVision** [comment]
@ilteroi A while back G made it so the AI wouldn't bully or war more than one City-State at the same time.

I didn't change the logic here, someone else did...all I did here in my most recent changes was clean up some of the messily written stuff. I'm not familiar with the military operations code, feel free to change it to work properly. :)

**Comment by RecursiveVision** [comment]
I see this later on in the function...
```
GetPlayer()->GetMilitaryAI()->RequestBullyingOperation(eTargetPlayer);
```

Will calling this be sufficient? Is there a "cancel operations" switch if the AI no longer wants to bully?

**Comment by RecursiveVision** [comment]
TBH DoMakeWarOnPlayer seems like it could use improvement in general...I didn't touch it because I don't know enough about the military operations code.

**Comment by RecursiveVision** [comment]
@ilteroi So something I've just noticed is that DoMakeWarOnPlayer() was changed to use getFirstOffensiveAIOperation, and if bWantToAttack is set to false, it'll cancel the operation, so even if GetCSBullyTargetPlayer() was removed, they still wouldn't be functioning...probably an unintended side effect of your change a while back.

**Comment by ilteroi** [comment]
information overload ... but i'll make it work
