### ISSUE TITLE
1/9 Beta - Meeting new Civ generates multiple Civ meetings

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#7385]
_1. Mod version (i.e Date - 12/1):_
1/9 Beta - has happened in many revisions previous

_2. Mod list (if using Vox Populi only, leave blank):_
Even More Luxury Resources for VP v7
Really Advanced Setup

_3. Error description:_ 
When meeting a new civ multiple diplo windows occur
this is entirely game dependent but if I meet China and they have met Germany I meet both on the same turn even though I have only actually met China

When this happens both civs manage to get embassies if traded on initial meeting.

_4. Steps to reproduce (optional):_
Start game, meet new Civ

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Are they on the same team? Was the World Congress just founded?

**Comment by R3P0FFXI** [comment]
> Are they on the same team? Was the World Congress just founded?

No this was ancient era start of the game before anyone even founded the congress or had moved to a new era

**Comment by RecursiveVision** [comment]
Never heard of this issue...does it occur without the other mods?

**Comment by R3P0FFXI** [comment]
> Never heard of this issue...does it occur without the other mods?

Yes, it happens without the other mods, and I have been having it since previous versions of VP, I wont lie with the  CTD issues I have + some weird bugs I am debating wiping out Civ 5 and reinstalling.

**Comment by RecursiveVision** [comment]
Try verifying the integrity of the game files...Steam should have an option for that under Properties.

**Comment by RecursiveVision** [comment]
Tech tree issues are often caused by a bad installation.

**Comment by R3P0FFXI** [comment]
> Try verifying the integrity of the game files...Steam should have an option for that under Properties.

Validation is running now

**Comment by RecursiveVision** [comment]
See if it fixes your issues...otherwise I have no idea what's up here, this shouldn't be possible in the code

**Comment by R3P0FFXI** [comment]
> See if it fixes your issues...otherwise I have no idea what's up here, this shouldn't be possible in the code

It did not I am still able to discover multiple civs as well as just had another CTD

**Comment by R3P0FFXI** [comment]
@RecursiveVision last game I played fast did not have a replication of this issue, post reinstall. Unfortunately the CTD issue & research still occurred
