### ISSUE TITLE
1/9 Beta - Natural Wonders not providing resources at first

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#7386]
_1. Mod version (i.e Date - 12/1):_
1/9 beta 

_2. Mod list (if using Vox Populi only, leave blank):_
Really Advanced Setup
Even More Luxury Resources for VP v7

_3. Error description:_ 
Was gifted land from Ancient Ruins and when my city expanded that land included 2 Natural wonders, both of these natural wonders had faith bonuses to them. 

The Natural Wonder Bonuses did not apply even tho the Natural wonders were inside of my city limits.

The Natural Wonders were Sri Panda and Ularu

The bonuses eventually did show up but it may have been 50-60 turns later.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
You need a citizen to be working the tile with the NW...
