### ISSUE TITLE
1/9 Beta Research Issues (Sailing)

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#7387]
_1. Mod version (i.e Date - 12/1):_
1/9 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
Really Advanced Setup
Even More Luxury Resources for VP v7

_3. Error description:_ 
I unlocked Pottery and Archery, which should give me the option to unlock sailing. Sailing now does not unlock until the entire tree is completed. Animal Husbandry, Mining, The Wheel

Not sure if this change was intentional or a bug.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by R3P0FFXI** [comment]
@RecursiveVision This is post reinstall of all Mods and the game

![VP Research](https://user-images.githubusercontent.com/10148511/104131609-5511a280-5345-11eb-99ab-c29fc323ab6d.jpg)

**Comment by RecursiveVision** [comment]
Probably a mod conflict...try without the extra mods

**Comment by Vyyt02** [comment]
Also, you can mouse over Sailing and it will show you prerequisite techs in the tooltip.

I have noticed that in some cases the arrows between the ancient techs sometimes overlap or create a wrong impression about the prerequisites.

I was meaning to dig in to it and suggest a minor reshuffle (just visual) within the tree, but have not had the time to do so yet.

**Comment by HungryForFood** [comment]
Even More Luxury Resources for VP is my mod, it doesn't adjust tech.

Does Really Advanced Setup change tech?

I know Enlightenment Era messes with tech requirements, you have that?

**Comment by RecursiveVision** [comment]
Either way, I'm unable to reproduce the issue...

**Comment by R3P0FFXI** [comment]
> Even More Luxury Resources for VP is my mod, it doesn't adjust tech.
> 
> Does Really Advanced Setup change tech?
> 
> I know Enlightenment Era messes with tech requirements, you have that?

I think I do have Enlightenment Era

**Comment by R3P0FFXI** [comment]
@HungryForFood You are correct I was looking at my Mods wrong I had Enlightenment Era selected and now EMLR I swapped and it is fixed now. Would be great if someone could fix Enlightenment Era as its a great MOD adds a ton to the game.
