### ISSUE TITLE
1/9 Beta Hotfixes 2 and 3 - AI rejects peace despite 100% warscore

### ISSUE THREAD

**Issue by cpm4001** [LoneGazebo/Community-Patch-DLL#7390]
_1. Mod version:_

1/9 Beta; game started on hotfix 2 and then continued on save-compatible hotfix 3.

_2. Mod list (if using Vox Populi only, leave blank):_

**Functionality-Affecting Mods**

Community Patch
Community Balance Overhaul
City-State Diplomacy Mod for CBP
C4DF - CBP
More Luxuries - CBO Edition
43 Civs CP
Promotion Icons
UI - Promotion Tree
Civ Names By Policy
Enlightenment Era for VP
Historical Religions Complete
Music Changer
Quick Turns
R.E.D. Modpack
Sukritact's Events and Decisions

**Additional Civilizations Actually in this Game**

Hoop Thrower's Tehuelche for VP
JFD's Great Britain (Victoria) for VP
JFD's Japan (Meiji) for VP
JFD's Sweden-Norway (Oscar II)
Leugi's Musica Civilization
More Civilization's Kilwa [Note: did not have the VP compatibility patch enabled, which is my mistake]
More Civilization's Polynesian Civilization Split [Rapa Nui was in the game]
Sukritact's Phoenicia

**Additional Civilization Mods Enabled but not Actually in the Game**

Colonialist Legacies Vietnam + CBO Compatibility Patch
Colonialist Legacies Tlingit for VP
Colonialist Legacies Canadian Dominion for VP
Colonialist Legacies Inuit for VP
JFD's Armenia (Tiridates III)
JFD's Belgium (Leopold II)
JFD's Great Ming (Yongle)
JFD's Great Qing (Cixi)
JFD's Indo-Greeks (Menander I)
JFD's Khazaria (Bulan)
JFD's Lithuania (Gediminas)
JFD's Mexico (Maximilian I)
JFD's Punjab (Ranjit Singh)
JFD's Swedes (Erik)
JFD's Takuts (Tygyn Darkhan)
JFD's Poland-Lithuania (Sigismund II)
JFD's Egypt (Hatshepshut)
JFD's Italy (Victor Emmanuel III)
JFD's United States (Teddy Roosevelt)
LastSword's Tibet for VP
LastSword's Zimbabwe for VP
More Civilization's Ashanti
More Civilization's Buccaneers
More Civilization's Nazca
Sukritact's Burma
Tomatekh's Sumer for VP

_3. Error description:_ 

AI won't make peace despite me having 100% warscore on them, having seized two of their three cities, and having essentially wiped their army out multiple times. Copy-pasted from the beta thread on CivFanatics: 

Just as I was entering the Industrial Era the AI went nuts and nearly everyone (including long-time friends Kilwa and Sweden-Norway) Denounced and then Dowed me. Beat most of the attackers off but was only able to peace out three non-neighboring civs (Sweden-Norway, Tehuelche, Spain), and even then only after upgrading to Hotfix 3. Shoshone (my closest neighbor) won't peace out despite getting decimated, losing 2 of his cities and being at -100 warscore against me. Updated to hotfix three and still no peace. Note that I am a turn or two from taking his capital and that he has a negligible army.

_4. Steps to reproduce (optional):_

Boot up save file, go to Shoshone's leaderscreen, click Negotiate Peace.

---------------------------
Supporting information:

[Arabia 4.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5798385/Arabia.4.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5798387/Logs.zip)
![20210111014600_1](https://user-images.githubusercontent.com/19790048/104239370-6a133200-5428-11eb-87ab-e845d40f8c58.jpg)

**Comment by RecursiveVision** [comment]
Can't boot up the save with all those other mods...was the war declaration on you a coop war?

![6891b4c7075d749e944b3e34e021a843](https://user-images.githubusercontent.com/66801010/104240607-57016180-542a-11eb-9dba-bd397e84139a.png)

**Comment by RecursiveVision** [comment]
Aha, found the problem
