### ISSUE TITLE
Barbarian Encampments giving Culture upon clearing without Authority

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7391]
Latest beta version - reported on the forums.

**Comment by ReanKW** [comment]
Yeah, it's giving you 20 culture for clearing the camp aswell as the 20 gold you normally would get. The 20 culture shows on the camp as a floating yield (like the one in your capital for completing citystate quests) if that helps.

**Comment by RecursiveVision** [comment]
Side effect of a code simplification I made. Fixed.
