### ISSUE TITLE
1/9 Aircraft Issue

### ISSUE THREAD

**Issue by myeong1129** [LoneGazebo/Community-Patch-DLL#7394]
_1. Mod version (i.e Date - 12/1):_
1/9 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
Quick turns
R.E.D. ModPack

_3. Error description:_ 
Aircrafts stationed in the city appear differently from the 12/1 patch. Nuclear missile properly appears as a number, but the aircrafts appear as if it is normal units. I believe it is not intended since it is very uncomfortable to understand how many aircrafts are stationed in the city. I post the screenshot for better the understanding.

+Better delete Spanish Mission building if it is not going to be used, or at least delete its art or artifact slot. Due to its slot, the castle's art slot is missing from the culture overview. Since castle is one of the early art slot building, arts often directly go into it and disappear from the overview. I just manually deleted Mission's code and now the bug is gone, but quite annoying it was.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
<img width="714" alt="2021-01-13 012333" src="https://user-images.githubusercontent.com/77344272/104343341-2b23d000-553f-11eb-9b0b-14dbfda452d0.png">

<img width="711" alt="2021-01-13 013721" src="https://user-images.githubusercontent.com/77344272/104344450-80acac80-5540-11eb-9817-959696db2889.png">

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5803451/Logs.zip)

**Comment by ilteroi** [comment]
aircraft unit flags are fixed. culture overview is tracked in other issues
