### ISSUE TITLE
Feature Request: Improvement_ResourceQuantityRequirements 

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#7395]
Would it be possible to add the ability to add resource requirements to improvements? That way, you could have improvements that require unique or existing strategic resources to build, which opens up a lot more options for improvements besides tile requirements.

**Comment by HungryForFood** [comment]
I didn't know this, but apparently this is already in the game. It's a Firaxis table even.

![image](https://user-images.githubusercontent.com/22621937/104465514-130b8980-55ef-11eb-8720-6731e9fc59d0.png)

So if you don't want the functionality of ResourceMakesValid and ResourceTrade, I think just making it 0 will do.

Keep in mind that like Building_ResourceQuantityRequirements and Unit_ResourceQuantityRequirements, this will decrease your resource count when the improvement is built.

**Comment by RecursiveVision** [comment]
Neat

**Comment by pineappledan** [comment]
Hot dog, I was just looking in the wrong tables I guess
Thanks for pointing that out!
