### ISSUE TITLE
CTD  Possible CV GAMECORE EXPANSION 2 ! D11 GETGAMECONTEXT

### ISSUE THREAD

**Issue by myles1718** [LoneGazebo/Community-Patch-DLL#7396]
_1. Mod version (i.e Date - 12/1):_
1/9 WITH ALL HOT FIXES

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
CTD  NO ISSUES SEEN IN LUA
[IGE1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5809184/IGE1.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5809185/CvMiniDump.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5809187/Lua.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HungryForFood** [comment]
![image](https://user-images.githubusercontent.com/22621937/104467575-6ed71200-55f1-11eb-8b3f-3e250ff991cf.png)

Not much useful information from the dump unfortunately.

And too many mods, I can't load the save.

**Comment by CyberPhy** [comment]
Try removing IGE (Ive had problems with that mad before)
It's odd that the Lua log is empty (Did the game crash before you loaded into the game?)

I looked at the dump and found this
`EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 7aea0a80 (CvGameCore_Expansion2+0x00220a80)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 000001b8
Attempt to read from address 000001b8
`
I don't know if this was helpful or not
