### ISSUE TITLE
Military AI questions

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7397]
@ilteroi While I feel there's been some big improvements to war logic with our latest changes, I'm still unsatisfied. :)

So, question 1: how capable is the AI of handling multiple military conflicts at the same time? Obviously it's always a weakness to be fighting wars on two fronts. But if an AI is sufficiently powerful (e.g. a warmonger that's swallowed up a couple other civs) it may be possible to fight and win multiple wars. You know the military AI far better than I do, so I'm interested to know how feasible it would be for the AI to wage, for instance, one war against an adversary and a secondary war against an easy nearby target.

Question 2: If not multiple wars, then would it be possible to have the AI use their main army for war and have a secondary army for bullying tribute out of City-States / making demands of other players? It may be very helpful, especially for warmongers, to bully resources out of others if they're waging war...

However in CvMilitaryAI::RequestBullyingOperation() we have this code which renders that impossible:
```
	// Let's only allow us to be bullying one opponent at a time, so abort if already have one of these operations active against any opponent
	if (m_pPlayer->getFirstAIOperationOfType(opType))
		return false;
```

Because bullying operations use the same opType as city attacks...

**NOTE:** Also CvMilitaryAI::RequestBullyingOperation had a line of code that prevented bullying operations against non-minor civs thus blocking all demands, but I fixed that bug in the latest RSI.

Question 3: You'll notice the section in DoMakeWarOnPlayer() that I marked...
```
		//see if we can start a sneak attack
		if (bWantToAttack)
		{
			SetWarGoal(eTargetPlayer, WAR_GOAL_PREPARE);

			// Attack on minor
			if (GET_PLAYER(eTargetPlayer).isMinorCiv())
			{
				GetPlayer()->GetMilitaryAI()->RequestCityAttack(eTargetPlayer,1);
			}
			// Attack on major
			else
			{
				GetPlayer()->GetMilitaryAI()->RequestCityAttack(eTargetPlayer,3); //consider: if we want to declare war but this call fails because we don't have a preferred target, declare war now?
				SetWantsSneakAttack(eTargetPlayer, true);
			}
		}
```

I already have code limiting the amount of civs the AI is allowed to adopt the WAR approach towards; see the DoUpdateWarTargets() function I added for how the AI does this (it's messy, but it seems to work, and I couldn't think of a smarter way to accomplish it with how much the AI needs to consider to appropriately select the WAR approach).

So I'm thinking perhaps the AI should declare war on major civs if they request a city attack after selecting the WAR approach but it's denied because there are no good attack targets. It can still be useful for limiting cultural influence/religious spread, plundering trade routes, cancelling trade agreements, etc. Alternatively they could maybe change it to a demand instead.

The problem I have with the current code is that without a preferred attack target, the AI is left just sitting there with the WAR approach rather than declaring war or anything else. 

Any thoughts on how this could be addressed/any good alternatives? Could just have it call DeclareWar, but I'm not sure how easily a target can change from being "possible" to "preferred"...perhaps the AI should bide their time instead...

**Comment by ilteroi** [comment]
hard to say.

on the one hand the AI is perfectly capable of waging a two front war, if it has enough units. there is nothing to prevent it if the other players declare war.

what we are currently doing is preventing "active" two front wars, where the AI declares. and i think that's fine, concentrate on one enemy at a time.

to answer your questions, there is currently no code to check whether a player is in shape to fight multiple enemies or how many armies a player could field. but you can go by trial and error and call RequestCityAttack() with maxMissingUnits==0. if it fails, you know there are not enough spare units or no good targets.

**Comment by RecursiveVision** [comment]
@ilteroi Thanks for the answers! I made some adjustments to this in the latest RSI commits, to try to teach the AI how to handle this properly...and fixed some bugs...hopefully it performs well. :)
