### ISSUE TITLE
Very limited City-State Generation (43-Civ DLL)

### ISSUE THREAD

**Issue by cpm4001** [LoneGazebo/Community-Patch-DLL#7400]
_1. Mod version:_

12/1 beta, hotfixes 4 and 5

_2. Mod list (if using Vox Populi only, leave blank):_

Occurs with 43-civ (no EUI) DLL both with several other mods enabled and with VP only

_3. Error description:_ 

Map only generates 2-3 city states.

_4. Steps to reproduce (optional):_

Start new game on any map script (first noticed issue on Huge Communitas v.79 maps with 4 extra major civs, so 16 full civs and 24 theoretical city states, but later confirmed with 'normal' Large and Huge on Communitas and Continents maps). Play one turn, then either Resign and check the message log to note "[city] was founded" messages or use IGE to reveal the full map. No more than 3 CSes will have spawned and settled.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5811717/Logs.zip)

**Comment by cpm4001** [comment]
An addendum: I uninstalled Vox Populi again and reinstalled just the 'regular' version with hotfix 5. That map (Huge Communitas v.79, 16 major civs) had regular City-State generation.

**Comment by HungryForFood** [comment]
What mods do you have?

**Comment by HungryForFood** [comment]
@RecursiveVision I think the way you are compiling the 43 Civ DLL is incorrect. When I installed 12-1-3, and only replaced the AssignStartingPlots.lua, everything was fine.

Unfortunately I have no idea what is the correct way to compile the 43 Civ DLL.

**Comment by RecursiveVision** [comment]
@HungryForFood I just switch #define MAX_MAJOR_CIVS  from 22 to 43, which according to Gazebo is the correct way to compile it

**Comment by HungryForFood** [comment]
I tested with 12-1-3 only, everything was fine. Then I swapped in your hotfix 5, except for AssignStartingPlots.lua, and it stopped working.

AssignStartingPlots.lua fetches the number of major and minor civs using the function GetPlayerAndTeamInfo(). In line 1613:

```
	self.iNumCivs, self.iNumCityStates, self.player_ID_list, self.bTeamGame, self.teams_with_major_civs, self.number_civs_per_team = GetPlayerAndTeamInfo()
```

With print statements, I confirmed that right at this line, the number of minor civs was already bugged. So something went wrong before AssignStartingPlots.lua was called.

GetPlayerAndTeamInfo() is from MapmakerUtilities.lua, which VP does not change.

```
function GetPlayerAndTeamInfo()
	-- This function obtains Civ count, CS count, correct player IDs, and basic Team information.
	local iNumCivs, iNumCityStates, player_ID_list = 0, 0, {};
	for i = 0, GameDefines.MAX_MAJOR_CIVS - 1 do
		local player = Players[i];
		if player:IsEverAlive() then
			iNumCivs = iNumCivs + 1;
			table.insert(player_ID_list, i);
		end
	end
	for i = GameDefines.MAX_MAJOR_CIVS, GameDefines.MAX_CIV_PLAYERS - 1 do
		local player = Players[i];
		if player:IsEverAlive() then
			iNumCityStates = iNumCityStates + 1;
		end
	end

	local bTeamGame = false;
	local iNumTeams = Game.CountCivTeamsEverAlive()
	local iNumTeamsOfCivs = iNumTeams - iNumCityStates;
	if iNumTeamsOfCivs < iNumCivs then
		bTeamGame = true;
	end

	local teams_with_major_civs = {};
	local number_civs_per_team = table.fill(0, GameDefines.MAX_CIV_PLAYERS)
	number_civs_per_team[0] = 0;
	for i = 0, GameDefines.MAX_MAJOR_CIVS - 1 do
		local player = Players[i];
		if player:IsEverAlive() then
			local teamID = player:GetTeam()
			number_civs_per_team[teamID] = number_civs_per_team[teamID] + 1;
			local bCheckTeamList = TestMembership(teams_with_major_civs, teamID)
			if bCheckTeamList == false then
				table.insert(teams_with_major_civs, teamID)
			end
		end
	end
	
	return iNumCivs, iNumCityStates, player_ID_list, bTeamGame, teams_with_major_civs, number_civs_per_team
end
```

Relevant section being this:

```
	for i = GameDefines.MAX_MAJOR_CIVS, GameDefines.MAX_CIV_PLAYERS - 1 do
		local player = Players[i];
		if player:IsEverAlive() then
			iNumCityStates = iNumCityStates + 1;
		end
	end
```

I checked SQLiteSpy, MAX_MAJOR_CIVS and MAX_CIV_PLAYERS seems good, which means the minor civ player slots are failing the IsEverAlive() check for some reason.

Have you changed anything to do with game start or turn order?

**Comment by RecursiveVision** [comment]
@HungryForFood There were some changes to CvPlayer::DoTurn() but nothing that should prevent City-States from spawning. Hmm.

**Comment by HungryForFood** [comment]
Maybe one of the init player functions? I never inspected the pre-game start stuff before, so I don't really have an idea.

**Comment by azum4roll** [comment]
Do we have an AssignStartingPlots.lua compatible with Communitu_79a?

**Comment by HungryForFood** [comment]
Yes. I tested with Continents as well to be sure.

**Comment by RecursiveVision** [comment]
@Mileslewis made some adjustments to City-State initialization, now that I think of it (to fix the unique unit issues), perhaps it's related? I can't think of anything I've done that would impact it.

**Comment by RecursiveVision** [comment]
@HungryForFood I don't have the time right now, but if you run the VS debugger and set a breakpoint during initialization, then go step by step you should be able to identify the problem (if it isn't an LUA issue).

**Comment by HungryForFood** [comment]
Not familiar with the functions for initialisation. I assume it is CvGame::InitPlayers()?

**Comment by HungryForFood** [comment]
Relevant for loop for initialisating players, from CvGame::InitPlayers():

```
	// Players
	for(iI = 0; iI < MAX_PLAYERS; iI++)
	{
		// init Barbarian slot
		if(iI == BARBARIAN_PLAYER)
		{
			CvPreGame::setTeamType(BARBARIAN_PLAYER, BARBARIAN_TEAM);
			CvPreGame::setSlotStatus(BARBARIAN_PLAYER, SS_COMPUTER);
			CvPreGame::setNetID(BARBARIAN_PLAYER, -1);
			CvPreGame::setHandicap(BARBARIAN_PLAYER, (HandicapTypes)GC.getBARBARIAN_HANDICAP());
			CvPreGame::setCivilization(BARBARIAN_PLAYER, eBarbCiv);
			CvPreGame::setLeaderHead(BARBARIAN_PLAYER, (LeaderHeadTypes)GC.getBARBARIAN_LEADER());
			CvPreGame::setPlayerColor(BARBARIAN_PLAYER, ((PlayerColorTypes)barbarianPlayerColor));
			CvPreGame::setMinorCiv(BARBARIAN_PLAYER, false);
		}
		// Major Civs
		else if(iI < MAX_MAJOR_CIVS)
		{
			CvPreGame::setPlayerColor((PlayerTypes)iI, aePlayerColors[iI]);
			// Make sure the AI has the proper handicap.
			if(CvPreGame::slotStatus((PlayerTypes)iI) == SS_COMPUTER)
			{
				CvPreGame::setHandicap((PlayerTypes)iI, (HandicapTypes)GC.getAI_HANDICAP());
			}
		}
		// Minor civs
		else if(iI < MAX_CIV_PLAYERS)
		{
			eMinorPlayer = (PlayerTypes) iI;

			if(iI < MAX_MAJOR_CIVS + iNumMinors)
			{
#if defined(MOD_GLOBAL_MAX_MAJOR_CIVS)
				CvMinorCivInfo* pMinorCivInfo = GC.getMinorCivInfo(CvPreGame::minorCivType((PlayerTypes)(eMinorPlayer + (MAX_PREGAME_MAJOR_CIVS - MAX_MAJOR_CIVS))));
#else
				CvMinorCivInfo* pMinorCivInfo = GC.getMinorCivInfo(CvPreGame::minorCivType(eMinorPlayer));
#endif
				if(pMinorCivInfo)
				{
					CvPreGame::setSlotStatus(eMinorPlayer, SS_COMPUTER);
					CvPreGame::setNetID(eMinorPlayer, -1);
					CvPreGame::setHandicap(eMinorPlayer, (HandicapTypes)GC.getMINOR_CIV_HANDICAP());
					CvPreGame::setCivilization(eMinorPlayer, eMinorCiv);
					CvPreGame::setLeaderHead(eMinorPlayer, (LeaderHeadTypes)GC.getBARBARIAN_LEADER());
					CvPreGame::setPlayerColor(eMinorPlayer, (PlayerColorTypes)pMinorCivInfo->getDefaultPlayerColor());
					CvPreGame::setMinorCiv(eMinorPlayer, true);
					CvPreGame::setMinorCivType(eMinorPlayer, (MinorCivTypes)pMinorCivInfo->GetID());
				}
			}
			else
			{
#if defined(MOD_GLOBAL_MAX_MAJOR_CIVS)
				int testingMinor = GetAvailableMinorCivType() + (eMinorPlayer + (MAX_PREGAME_MAJOR_CIVS - MAX_MAJOR_CIVS));
				CvMinorCivInfo* pMinorCivInfo = GC.getMinorCivInfo((MinorCivTypes)testingMinor);
#else
				MinorCivTypes eAvailableMinor = GetAvailableMinorCivType();
				GAMEEVENTINVOKE_HOOK(GAMEEVENT_FreeCitySelector, eMinorPlayer, eAvailableMinor);
				CvMinorCivInfo* pMinorCivInfo = GC.getMinorCivInfo(eAvailableMinor);
#endif
				if (pMinorCivInfo)
				{
					CvPreGame::setSlotStatus(eMinorPlayer, SS_CLOSED);
					CvPreGame::setNetID(eMinorPlayer, -1);
					CvPreGame::setHandicap(eMinorPlayer, (HandicapTypes)GC.getMINOR_CIV_HANDICAP());
					CvPreGame::setCivilization(eMinorPlayer, eMinorCiv);
					CvPreGame::setLeaderHead(eMinorPlayer, (LeaderHeadTypes)GC.getBARBARIAN_LEADER());
					CvPreGame::setPlayerColor(eMinorPlayer, (PlayerColorTypes)pMinorCivInfo->getDefaultPlayerColor());
					CvPreGame::setMinorCiv(eMinorPlayer, true);
					CvPreGame::setMinorCivType(eMinorPlayer, (MinorCivTypes)pMinorCivInfo->GetID());
				}
			}
		}
	}
```

For the minor civ part, there is a pre-processor directive MOD_GLOBAL_MAX_MAJOR_CIVS which is not defined anywhere. Did you delete this? Not sure if it is meant to be activated or not, or what value it should have. Don't see anything related to this in your pull request.

**Comment by HungryForFood** [comment]
The reason city states don't spawn is because `CvMinorCivInfo* pMinorCivInfo = GC.getMinorCivInfo(CvPreGame::minorCivType(eMinorPlayer));` returns a null.

**Comment by RecursiveVision** [comment]
@LoneGazebo Do you have any idea what the problem is here? :)

**Comment by RecursiveVision** [comment]
@HungryForFood 

```Community-Patch-DLL\CvGameCoreDLLUtil\include\CustomModsGlobal.h```

Could you try un-commenting out this line and seeing if it works properly?
```
// #define MOD_GLOBAL_MAX_MAJOR_CIVS (43)
```

**Comment by HungryForFood** [comment]
Yep it works now. Looks like that is the correct way to compile the 43 Civ DLL.

**Comment by RecursiveVision** [comment]
Seems like it. Well, that's easy to solve then.
