### ISSUE TITLE
Is this code working as intended?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7404]
@ilteroi In CvMilitaryAI::RequestBullyingOperation...
```
		SPathFinderUserData data(m_pPlayer->GetID(), PT_ARMY_MIXED, -1, MINOR_POWER_COMPARISON_RADIUS);
		ReachablePlots relevantPlots = GC.GetStepFinder().GetPlotsInReach(pTargetCity->plot(), data);

		//taken from CalculateBullyScore
		pair<int, int> localPower = TacticalAIHelpers::EstimateLocalUnitPower(relevantPlots, GET_PLAYER(eEnemy).getTeam(), m_pPlayer->getTeam(), false);
		int iLocalPowerRatio = int((localPower.second * 100.f) / (localPower.first + pTargetCity->GetPower()));

		//check if we have a chance ...
		int iCurrentBullyMetric = GET_PLAYER(eEnemy).GetMinorCivAI()->CalculateBullyScore(m_pPlayer->GetID(), true);
		if (iLocalPowerRatio > 100 || iCurrentBullyMetric < -200)
			return false;
```

Used to determine whether bullying has a chance...but the syntax seems weird. Seems to me that iLocalPowerRatio is checking is checking if TeamB (the bullying team)'s power * 100 /  TeamA's power (the City-State's) is above 100...wouldn't a higher ratio be beneficial to bullying, not detrimental? I might be misreading it.

**Comment by ilteroi** [comment]
actually i'm not sure. i wanted to test it, found it was never called and then fell down a different rabbit hole

**Comment by RecursiveVision** [comment]
@ilteroi Hmm...well, I'm posting a new beta patch (latest RSI). Hopefully this helps in testing it.

**Comment by RecursiveVision** [comment]
@ilteroi Posted

**Comment by ilteroi** [comment]
i just removed that piece of code because it was indeed weird.

however question: what happens to the approach after a successful bully attempt? is it reset?

secondly, there is this bit CalculateBullyScore:

```
	// **************************
	// Current influence of major
	//
	// -999 ~ -0
	// **************************
	if (!GET_PLAYER(eBullyPlayer).IsCanBullyFriendlyCS())
	{
		int iFriendshipLimit = GC.getFRIENDSHIP_THRESHOLD_CAN_BULLY();
		if (GetEffectiveFriendshipWithMajor(eBullyPlayer) > iFriendshipLimit)
		{
			iScore -= GetEffectiveFriendshipWithMajor(eBullyPlayer);
		}
	}
```

this seems designed to prevent AI players from bullying their friends? but isn't there a better way to do that? maybe a hard exclusion if they are friends? or rather if they want to be friends?

**Comment by RecursiveVision** [comment]
@ilteroi I'm pretty sure the intended behavior is a reduction in bully % for each Influence point up until Friendship, and then a hard exclusion (unless GetPlayer()->IsCanBullyFriendlyCS() is true; Autocracy tenet).

I think if you try to bully a City-State you're friends with a huge negative modifier pops up; so this may be duplicate code.

Also, I checked and there actually isn't any code forbidding the AI from selecting the bully approach repeatedly towards the same target even though it won't work...will fix.

**Comment by RecursiveVision** [comment]
@ilteroi 
```
 		
		//if we're not being careless, just use whatever units we have and do not wait for new ones
		
		if (m_pPlayer->addAIOperation(opType, bCareful ? iNumUnitsWillingToBuild : 0, eTargetPlayer, pTargetPlot->getPlotCity(), pMusterPlot->getPlotCity()) != NULL)
		
			return true;
```

Your comment and your code are producing inverted results...think it should be !bCareful

**Comment by ilteroi** [comment]
nah. "careful" is the default where we wait for extra units. in the opposite case we just take what we have.

**Comment by RecursiveVision** [comment]
Should say "if we're being careless" then...
