### ISSUE TITLE
Random seed still in use?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7405]
It seems that the random seed (the one changed by GAMEOPTION_NEW_RANDOM_SEED) is still in use to randomize some AI decisions: city production, policies, techs, beliefs, World Congress voting, event decisions, and City-State elections. 

Could this be causing multiplayer desyncs?

**Comment by ilteroi** [comment]
never played multiplayer ... are there reports of desync? more frequent than before?

**Comment by RecursiveVision** [comment]
From what I remember, there are reports of desyncs, but none recently.

**Comment by RecursiveVision** [comment]
@ilteroi Is there an alternative pseudorandom seed that would work comparably well?

**Comment by ilteroi** [comment]
well we never really understood where those desyncs are coming from. so it's unclear how to improve the situation.

theoretically it should be possible to replace all the jonRand calls with fake RNG calls (except the pregame stuff of course). i do not have "quality data" for the fake RNG, but it should not matter much.

on the other hand i don't like shotgun debugging ...

**Comment by ReanKW** [comment]
Last time I tried MP desyncs still happened, was kinda random how often but would usually get very frequent as the game went on, like once every two to three turns. Would having logs of the desyncs help? Could probably go get some.
