### ISSUE TITLE
AI too lenient when it comes to "no contested borders"

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7406]
@ilteroi See this forum post:
https://forums.civfanatics.com/threads/new-beta-patch-1-9.666251/page-6#post-16001246

You were last to change this logic...any thoughts? I think perhaps it should check for the plot distance to the closest city or something...AI only seems to consider current contested tiles, and not where they'd like to settle next, which is making the AI overly friendly.

**Comment by ilteroi** [comment]
well there are two unowned plots between ... how would you define border.

if porto is juicy target, that should be enough to attack, no?

**Comment by RecursiveVision** [comment]
@ilteroi Perhaps if the plot is within 4 tiles of the AI's city and the other player's city? Unowned plots could count for less...

I'll think about this, seems like modifying GetContestedPlotScore should do.

"No contested borders" simply means no territorial disputes, I don't think it literally has to be bordering for the AI to get mad about it. 

Being too close still blocks the AI's expansion possibilities and would anger a human player.

Yeah, approach doesn't only factor in land disputes, but it's still a big factor in AI aggression, particularly in the early game.

**Comment by ilteroi** [comment]
well maybe the "you stole my settle plot" idea has merit. but that is currently not tracked.

**Comment by ilteroi** [comment]
done. it's called GetPlayerWhoStoleMyFavoriteCitySite() now. not sure if the design is ideal though. only the first call in each turn can yield a result.

**Comment by RecursiveVision** [comment]
@ilteroi Thanks! :)
