### ISSUE TITLE
Joint War in 10 Rounds is not triggering

### ISSUE THREAD

**Issue by rhaidinger** [LoneGazebo/Community-Patch-DLL#7407]
_1. Mod version (i.e Date - 12/1):_ 12/1 & 9/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Sweden invites me to a war. I answer "Ready in 10 rounds". In 10 rounds Sweden declares war and no invite for me. We have a your recent diplomatic action disappoints them malus. (But I don't know if its caused by this)
Edit: Confusingly the war started now but I got no information about it...

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@rhaidinger I'd need more information to debug...

Are you still friends with Sweden? What happened when the war finally started?

**Comment by rhaidinger** [comment]
> @rhaidinger I'd need more information to debug...
> 
> Are you still friends with Sweden? What happened when the war finally started?
> 
> Logs/savegame are also very helpful.

Hi, it seems just the screen with the decision "join war" or "don't join the war" is missing.

**Comment by ReanKW** [comment]
Maybe unrelated but I've noticed that the AI will sometimes declare war before the 10 turns and then you don't automatically declare aswell anymore, it cancels the agreement or something.

**Comment by rhaidinger** [comment]
> Maybe unrelated but I've noticed that the AI will sometimes declare war before the 10 turns and then you don't automatically declare aswell anymore, it cancels the agreement or something.

Seen this too, thats probably why I thought I missed the invite the first time.
![mt1](https://user-images.githubusercontent.com/76167984/104780954-e8056f00-5781-11eb-87eb-a6f7261971b0.jpg)
![mt2](https://user-images.githubusercontent.com/76167984/104780960-e9cf3280-5781-11eb-96ea-734798bff9ec.jpg)



But to the topic before 2 screenshots. One with the deal and 10 rounds later. Dido declares and I'm automatically in the war.

**Comment by RecursiveVision** [comment]
Oh, that isn't a bug. I removed the option to cancel.

**Comment by RecursiveVision** [comment]
@ReanKW Have you experienced this in the 1/9 or 1/15 patches? I fixed a lot of memory-related bugs.

**Comment by RecursiveVision** [comment]
Well, if you have, feel free to open another issue :)
