### ISSUE TITLE
1/15 - Land Based Medic not Healing adjacent Naval Units

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7409]
_1. Mod version (i.e Date - 12/1):_
1/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This land based medic is not applying its healing bonus to the adjacent ships.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/104796792-061da000-577f-11eb-9078-d0d8447fe8f0.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
has always been like that?

**Comment by RecursiveVision** [comment]
Yeah, this is intentional

**Comment by Stalker012345** [comment]
I know for a fact that it hasn't always been this way, I use land healing for naval units frequently. When was it changed?

**Comment by RecursiveVision** [comment]
Think ilteroi changed it recently when he changed area of effects for medics...?
