### ISSUE TITLE
AI opinion permanently stuck at hostile 

### ISSUE THREAD

**Issue by lollerskatez** [LoneGazebo/Community-Patch-DLL#7410]
1. Mod version: 1/9 with hotfix 5

2. Mod list (if using Vox Populi only, leave blank): 
(over) More Unique Components for VP (v 62)
[BNW] Colonialist Legacies - Vietnam ft. Trung Sisters (v 1)
[BNW] Colonialist Legacies Vietnam CBO Compatibility (v 1)
Civ Names by Policies (v 8)
Enhanced Naval Warfare for Vox Populi (v 1)
Global Warming (v 7)
Global Warming Congress (v 2)
Improved Air Recon (v 1)
MC and LITE's Nubia (v 3)
MC and LITE's Nubia CBO Compatibility (v 1)
MC's Tunis (v 1)
MC's Tunis Compatibility (v 1)
Kilwa Sultanate (v 4)
More Civs' Kilwa Sultanate VP Compatibility (v 4)
Pontoon Bridges for VP (v 1)
R.E.D. Modpack (v 27)
Reforestation (v 9)
Resource - Granary Includes Bison (v 3)
Resource - Mint Include Copper (v 2)
Sukritact's Chinookan Civilization (v 2)
Sukritact's Chinookan Civilization VP Compatibility (v 1)
Terrain - Poor Tiles Tweak (v 2)
TreeGrowth (VP) (v 2)
Unique City-States (v 6)

3. Error description: AI's opinion is permanently stuck at hostile despite net positive modifiers. Seems to happen after doing certain actions (converting them, allying with city-states). 

4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5823960/Logs.zip)
 

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):
[SaveFile.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5823925/SaveFile.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional): 
![20210115184058_1](https://user-images.githubusercontent.com/77524489/104798545-4c79fb80-578d-11eb-96d0-c31172ccd353.jpg)
![20210115184133_1](https://user-images.githubusercontent.com/77524489/104798546-4c79fb80-578d-11eb-82f3-58aa21363a6e.jpg)
![20210115184142_1](https://user-images.githubusercontent.com/77524489/104798547-4d129200-578d-11eb-9eb9-b029ba12d515.jpg)
![20210115184212_1](https://user-images.githubusercontent.com/77524489/104798548-4d129200-578d-11eb-89b6-b67bbbd9ecc1.jpg)
![20210115184235_1](https://user-images.githubusercontent.com/77524489/104798550-4d129200-578d-11eb-974d-c905a9feeef2.jpg)

**Comment by RecursiveVision** [comment]
@lollerskatez Can't explain Chinook or Byzantium, but the other cases should be fixed in my upcoming hotfix.

You don't have logging enabled so your logs are useless; check here for how to enable them: https://forums.civfanatics.com/threads/can-we-get-a-tutorial-for-submitting-ctd-bug-reports-to-github.655371/#post-15681894
