### ISSUE TITLE
Joint war cancelled

### ISSUE THREAD

**Issue by rhaidinger** [LoneGazebo/Community-Patch-DLL#7412]
_1. Mod version (i.e Date - 12/1):_ 12/1 & 15/1

_2. Mod list (if using Vox Populi only, leave blank):_3rd & 4th component

_3. Error description:_ Indonesia and me made a Joint War in 10  rounds agreement vs the aztecs in round 186. The next round he wanted to bribe into him declaring war on the the aztecs. And in 189 he declared war (Probably bribed by the russians who also were at war with the aztec). Afterwards i never got into the war and in 200 the war is over again. DOF still running. I signed a DP with Russia inbetween but that shouldn't change the Joint War with Indonesia vs. Aztecs. 
![aztec1](https://user-images.githubusercontent.com/76167984/104846107-324d3400-58d9-11eb-9034-0431d483c5f1.jpg)
![aztec2](https://user-images.githubusercontent.com/76167984/104846113-35e0bb00-58d9-11eb-8f41-795d7ea15b79.jpg)

Edit: I hoped to get you more screenshots with a russian Joint War but  because of a bribe they declared war vs Indonesia which had an DP with me and therefore instead fighting the Aztecs together with Russia, Russia fought against Aztecs (because of an Joint war with Indonesia) and Indonesia and me because of an bribed war. 
Anyway the prepared Screenshots....
![Rus1](https://user-images.githubusercontent.com/76167984/104848965-a68ed400-58e7-11eb-87db-1d768c8fabbb.jpg)
![Rus2](https://user-images.githubusercontent.com/76167984/104848968-a8f12e00-58e7-11eb-826d-35e5dfdce319.jpg)
![Rus3](https://user-images.githubusercontent.com/76167984/104848970-aabaf180-58e7-11eb-9e5c-0d7ec154ee45.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@rhaidinger I'd need a savegame from before you made the coop war agreement, and a savegame before it stops working.

**Comment by rhaidinger** [comment]
@RecursiveVision I do now play with the hotfix. I'll provide you with the save games as soon as I have this situation again.

**Comment by RecursiveVision** [comment]
I've added code to log every time a coop war is cancelled for any reason, hopefully we can find this soon.
