### ISSUE TITLE
Settler Marathon cost x9

### ISSUE THREAD

**Issue by ziadb** [LoneGazebo/Community-Patch-DLL#7415]
_1. Mod version (i.e Date - 12/1):_
Beta 1/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Settler base cost is multiplied by 9 on Marathon, 3x expected value.

_4. Steps to reproduce (optional):_
Load a game on Marathon.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by R3P0FFXI** [comment]
LOL I was enjoying the cost of settlers on Marathon it was a great way to slow the game down. I vote this not be changed and kept as is.

**Comment by ziadb** [comment]
> LOL I was enjoying the cost of settlers on Marathon it was a great way to slow the game down. I vote this not be changed and kept as is.

lmao it was a little much though no?

**Comment by R3P0FFXI** [comment]
> > LOL I was enjoying the cost of settlers on Marathon it was a great way to slow the game down. I vote this not be changed and kept as is.
> 
> lmao it was a little much though no? Like 3x cost of pyramids almost.

Not really think about it in that time to recruit families to uproot with low populations it should take time for this to happen. Anything in the very early ages should take a very long time to complete especially recruiting and uprooting families to go start a new settlement.

**Comment by RecursiveVision** [comment]
@Mileslewis I think this is your doing :)

**Comment by Mileslewis** [comment]
Yep, thought I'd tested that my bad.

I'll fix it today, hopefully without reverting the change.
