### ISSUE TITLE
Nearby City combat bonus not working

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7418]
Chu-Ko-Nu are supposed to get 25% combat bonus from being in or adjacent to a city but they don't seem to get this bonus at all in any situation. Same for other units with nearby stuff promotions.

There seems to be a function for it but it's greyed out behind an:
#if defined(MOD_BALANCE_CORE_AREA_EFFECT_PROMOTIONS)

@ilteroi I remember you made some changes to increase performance so I'm guessing this got caught in that.

**Comment by bsesar** [comment]
Possibly related to #7357 ?

**Comment by Mileslewis** [comment]
Yea tbh I wasn't sure how it was meant to work since 'siege volleys' implies it should give extra damage when attacking at or near enemy cities but then the wording of the bonus implies it's when the unit is next to or in a city so that's more likely defensive purposes.

Either way though it doesn't do either of these and it doesn't work for defense either.

**Comment by ilteroi** [comment]
this is because MOD_BALANCE_CORE_AREA_EFFECT_PROMOTIONS is disabled ... the performance impact was too big.

but maybe this one promotion can be restored, cities are stationary, so optimizations are possible.

**Comment by Mileslewis** [comment]
Fixed just for nearby city?

Pretty sure a lot of the promotions used in Unique Components use area of effect stuff

**Comment by RecursiveVision** [comment]
@ilteroi

**Comment by ilteroi** [comment]
only fixed the chokunu. the rest has to be stay disabled because they kill performance for the 99%

if you really want you can replace the compile switch with a runtime option. but still those promotions are AI unfriendly.
