### ISSUE TITLE
(Feature Request) - Allow for Airsweeps to do damage to AA Guns

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7419]
I wanted to confirm with the modders, is it already set up that Airsweeps do technically do damage to AA Guns (and its just set to 0), or that functionality actually missing and would need to be added in?

The fact that Fighters cannot damage AA guns is a major reasons AA guns are so impressive at the moment, which greatly hinders the niche of the fighter. Giving the fighter a tool to fight back and use the air sweep promotions they have would go a long way towards helping that.

**Comment by azum4roll** [comment]
I'd just lower their intercept range to 2 and give them a promotion that lowers their CS from all non-air attacks.

**Comment by Stalker012345** [comment]
> I'd just lower their intercept range to 2 and give them a promotion that lowers their CS from all non-air attacks.

That's only a part of the problem. I do think the AA guns are too strong in general, but there is also no good counter. Normally, the whole point of Air Sweeps is to remove interception and damage intercepting units. But because AA guns are immune from that, they are significantly better than fighters at providing interception.

**Comment by azum4roll** [comment]
On the downside, they occupy a hex and one unit of supply, and are easily sniped by anything ranged if you lower their CS. If Dogfighting Fighters are too easily killed (I don't really know how), maybe just lower the percentage of Air Supremacy promotions.

**Comment by Stalker012345** [comment]
> On the downside, they occupy a hex and one unit of supply, and are easily sniped by anything ranged if you lower their CS. If Dogfighting Fighters are too easily killed (I don't really know how), maybe just lower the percentage of Air Supremacy promotions.

In my experience, those downsides rarely come up in play. I generally have more supply than I have city slots (especially before airports are common), their 3 range makes it easy to find a place to put them, and they are quite durable.

But again it comes down to counterability. Fighters are designed to deal with intercepting units, that is their niche, so we should let them deal it. Now my preference would be that fighters can actually weaken AA guns, but I would also be okay if fighters took trivial damage from an AA gun (aka its a fair play, the action costs little hp and just consumes an interception). Right now AA guns are killing fighters that sweep them (and especially mobile sams).... that should not be happening.

**Comment by Stalker012345** [comment]
Would it be possible to make Air Supremacy also apply to AA guns and Mobile Sams? The issue right now is that an AA gun gets its bonus against fighters but not the other way around. So the AA gun with Supremacy II has a 135 CS (before even adding in other bonuses). Meanwhile the fighter actually has penalties vs land units, so no wonder they are getting one shotted.

**Comment by ilteroi** [comment]
right now there is no code to damage the ground units, but there is a setting called AIR_SWEEP_INTERCEPTION_DAMAGE_MOD which you can use to scale down the damage to the sweeping unit. use a negative percentage.

however it would be better to adjust the AA units' stats/promotions because that is more transparent to the player.

**Comment by Stalker012345** [comment]
> right now there is no code to damage the ground units, but there is a setting called AIR_SWEEP_INTERCEPTION_DAMAGE_MOD which you can use to scale down the damage to the sweeping unit. use a negative percentage.
> 
> however it would be better to adjust the AA units' stats/promotions because that is more transparent to the player.

I assume this would also impact the damage an interception plane would take from an airsweeping plane correct? Aka airsweeping would become stronger against other planes as well.

That might still be a good thing, but just noting that for completeness.

**Comment by ilteroi** [comment]
nah, it's only used for ground based interceptions
