### ISSUE TITLE
Missing Corporation office yields from tier 2 tenets

### ISSUE THREAD

**Issue by legenciv** [LoneGazebo/Community-Patch-DLL#7421]
_1. Mod version (i.e Date - 12/1):_
1/15 Patch EUI with Hotfix

_2. Mod list (if using Vox Populi only, leave blank):_
34UC v62 , JFD's The Empire of Japan (Meiji) for Vox Populi (v 3)

_3. Error description:_ 
The tier 2 tenet Transnationalism was not giving +2 Culture to offices when I played as Meiji. It may be a bug specific to that modded civ (UB being a unique corporation), but I'm leaving this bug report in case the bug is from the base VP build.

I have not tested with Order's Nationalization +2 Science, so it is possible that it may be bugged as well.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HungryForFood** [comment]
I have to fix it in my mod, I did Meiji before those policies worked like that.
