### ISSUE TITLE
crash in diplo AI

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7425]
callstack

![image](https://user-images.githubusercontent.com/1358966/105248647-0cdd5600-5b77-11eb-8b23-f2ffd553c3bd.png)

an out of bounds read because you look up espionage data for a minor player but CvPlayerEspionage only stores data for majors.

**Comment by RecursiveVision** [comment]
@ilteroi Good catch, thanks! Must have been a war bribe against a City-State, but DoReevaluatePlayers was only intended to trigger for majors...will fix.
