### ISSUE TITLE
Great Work goes into Castle, but GW Display only has Missions

### ISSUE THREAD

**Issue by DeAnnoCiv** [LoneGazebo/Community-Patch-DLL#7426]
_1. Mod version (i.e Date - 12/1):_
1/15 Hotfix 3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I used my first great artist to create a GW, and it was automatically put in a castle in my capital. Unfortunately, when I go to the GW manipulation screen, it doesn't show up because I have Missions as a category instead of castles.

_4. Steps to reproduce (optional):_
Just go to the save and look at the screen, Missions are there instead of castles. Screenshot included, where you can see the work in the castle in the background but the mission is blank on the screen.

---------------------------
<img width="838" alt="GaoMission" src="https://user-images.githubusercontent.com/47321731/105421900-d94f0a00-5c10-11eb-8424-966ba1377ef9.png">

[GaoMission.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5852535/GaoMission.zip)

**Comment by bentakacs** [comment]
Yup, same as #7370 

[https://github.com/LoneGazebo/Community-Patch-DLL/issues/7370](url)

There was also another ticket about the same thing, opened not long ago but couldn't find it.
