### ISSUE TITLE
1/15 - Cities getting renamed to strange single character names

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7427]
_1. Mod version (i.e Date - 12/1):_
1/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In the late game, I am noticing certain cities that are getting renamed to single garbage looking characters.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/105461057-4cc53b80-5c52-11eb-89e2-1bb02336b0ac.png)

![image](https://user-images.githubusercontent.com/20593976/105461117-6070a200-5c52-11eb-9b39-3ef3414c1747.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
uh. guess you're lucky it didn't crash :)

**Comment by Stalker012345** [comment]
> uh. guess you're lucky it didn't crash :)

I had periodic CTDs, but that's been normal the last few versions, none of the CTDs are sticking so its been a minor annoyance.
