### ISSUE TITLE
Lua API Documentation

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#7429]
The whoward/CP DLL adds many new Lua methods and hooks, but modders cannot use them if they do not know they exist. There exists a [thread](https://forums.civfanatics.com/threads/dll-lua-api-requests.527958/) at CFC by whoward for his stuff, but it is not easy to search for it.

I propose that we make a wiki right here at GitHub, containing all the new Lua stuff, including whoward's.

I'll get to work, firstly by copying whoward's thread, then by looking through my pull requests since I've added a few.

In the meantime, if anyone remembers adding anything Lua related, please comment here. Best if you tell me what you added.

In the future, I hope we can just keep adding to the wiki as we add new Lua stuff.

Maybe we can have one for database tables as well, but since it is easy to check what's available with SQLiteSpy, I'd say that's a low priority.

**Comment by RecursiveVision** [comment]
CanRequestCoopWar
IsWarBlockedByPeaceTreaty
IsDenounceMessageTooSoon

I haven't really added many LUA functions, these are the three I can remember.

**Comment by ilteroi** [comment]
do a regex search through the code. all the lua methods look like CvLuaX::lY where x and y are placeholders obviously

**Comment by HungryForFood** [comment]
Done.
