### ISSUE TITLE
diplo overreaction?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7430]
multiple times now the AI has asked me to remove my troops from their border ... but it's only a lonely scout.

![image](https://user-images.githubusercontent.com/1358966/105577642-2fd85780-5d7b-11eb-8d31-d63516128ffc.png)

why are they so sensitive?

**Comment by RecursiveVision** [comment]
Relevant functions are DoAggressiveMilitaryWarningStatement and DoUpdateMilitaryAggressivePostures...I adjusted the latter in the latest RSI but it shouldn't have resulted in this.

Scouting units are supposed to be excluded from the aggressive posture to begin with so I'm not sure why that's happening...I haven't encountered this myself yet.

**Comment by RecursiveVision** [comment]
@ilteroi Ah, let me guess...you didn't merge my changes to CoreDefines.sql :)

**Comment by ilteroi** [comment]
but what will happen if i scout with a warrior? maybe just ignore single units?

**Comment by RecursiveVision** [comment]
I think a single Giant Death Robot would still be worth getting alarmed over :P 

It should be ok if you merge CoreDefines.sql...
