### ISSUE TITLE
1/15 Beta Random events not always random

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#7432]
_1. Mod version (i.e Date - 12/1):_
1/15 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
Advanced Setup
Even More Luxury Resources 1.0

_3. Error description:_ 

_4. Steps to reproduce (optional):_
Start new game first series of events are always the same not random. 

Comet Sighting
Meteor Found
Solar Eclipse
Old Man and Harbor (which will fail always if you have 1000 gold)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
RNG issues were fixed, open another issue if it reoccurs
