### ISSUE TITLE
1/15 Beta Stuck on Next Turn

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#7433]
_1. Mod version (i.e Date - 12/1):_
1/15 Beta

_2. Mod list (if using Vox Populi only, leave blank):_
Really Advanced Setup
Even More Luxuries 1.0

_3. Error description:_ 
Stuck on Next Turn

_4. Steps to reproduce (optional):_
Load Saved game
[Stuck on Next Turn.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5862551/Stuck.on.Next.Turn.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):
[Stuck on Next Turn.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5862552/Stuck.on.Next.Turn.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by CyberPhy** [comment]
I've had this problem before, it happens with automatic explore/route to,  just move the unit that failed to move and the next turn button should work

**Comment by RecursiveVision** [comment]
@ilteroi There seems to be an issue where you can't hit Next Turn because a unit still needs orders...

(But it doesn't say "A Unit Needs Orders", you have to find the problem unit on your own)
