### ISSUE TITLE
too many medics

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7434]
![image](https://user-images.githubusercontent.com/1358966/105835573-43c6c800-5fcc-11eb-8483-6f17c49d1f25.png)

there are 5 bowmen here, four of them are medic level 2 and one is medic level 1.

seems a bit excessive?

**Comment by RecursiveVision** [comment]
@Mileslewis

**Comment by azum4roll** [comment]
What's that star promotion?

**Comment by ilteroi** [comment]
morale. irrelevant here.

**Comment by Mileslewis** [comment]
Yea I'm gonna go through all the promotions in the next few days

**Comment by Mileslewis** [comment]
@ilteroi To what extent does the AI know how to use medics?

**Comment by ilteroi** [comment]
not at all

**Comment by Mileslewis** [comment]
klkl, I'll make these promotions pretty unlikely then

**Comment by azum4roll** [comment]
> 
> 
> not at all

Welp, does that mean they don't know how to use Khans as well?

**Comment by ilteroi** [comment]
well a khan is also a great general. there is some special handling for those.
