### ISSUE TITLE
Hacienda yield tooltip spoiling hidden resource locations

### ISSUE THREAD

**Issue by esk38265** [LoneGazebo/Community-Patch-DLL#7435]
_1. Mod version (i.e Date - 12/1):_ 1/15 with EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The UI prediction of a Hacienda's yields reveals the locations of hidden resources.

_4. Steps to reproduce (optional):_
1. Start a game with Spain and check the predicted yields for building a Hacienda on a tile. Some tiles may have more food and/or production than normal for the improvement.
2. Research techs until resources are revealed to confirm their presence adjacent to a yield-mismatched tile.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
https://i.imgur.com/Ameafuj.png
https://i.imgur.com/jx538q9.png

**Comment by RecursiveVision** [comment]
@pineappledan @HungryForFood

**Comment by pineappledan** [comment]
A known issue for a long time. The adjacency bonus doesn’t care if the resource in question is invisible/unlocked. I hadn’t realized you could check tile yields before hacienda is even unlocked though. Ideally improvement_adjacentResourceYieldChange would check if the resource is visible, but that’s way beyond my ability to fix
