### ISSUE TITLE
Garrisoned units abandon cities when they shouldn't

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#7437]
_1. Mod version (i.e Date - 12/1):_
15/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The riflemen of Kyzyl has fleed _thus giving away the city for free_ - even though I have my navy around and can help protecting it. It will die with the city in any case, so why flee the battle?

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20144751/106034035-ad30fe80-60d2-11eb-821e-da8b2e494961.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. Make sure you have enabled logging before experiencing an error! Go here to find out how: http://forums.civfanatics.com/showthread.php?t=487482):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
well, self preservation is good ... but not if they're supposed to make a last stand.

also good point about allied forces, they are ignored at the moment.
