### ISSUE TITLE
1/15 - (Combat Viewer) Medic Defense Penalty not appearing

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7438]
_1. Mod version (i.e Date - 12/1):_
1/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The final number is right, but the defense penalty for medic is not showing up.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/106069783-c46aee80-60c8-11eb-884a-b3748720f77e.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
I think the slightly worrying thing here is that usually the YOUR STRENGTH/THEIR STRENGTH are actually correct even when the modifiers aren't but it looks like THEIR STRENGTH is also wrong here.

**Comment by Stalker012345** [comment]
> I think the slightly worrying thing here is that usually the YOUR STRENGTH/THEIR STRENGTH are actually correct even when the modifiers aren't but it looks like THEIR STRENGTH is also wrong here.

So a medic II has a -20% defense penalty, which completely cancels out their bonus. So having a RCS of 13 against this attack (which they use to defend against a ranged attack) is correct. Unless there is another bonus you see that they should have, I think the math is right, just the UI is wrong.

**Comment by Mileslewis** [comment]
normally you use normal combat strength for ranged defense though
