### ISSUE TITLE
CultureOverview.xml

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#744]
I think it would be better to left-justify AntiquitySites and HiddenSites.
The current value looks just a little bit odd in my language.

Current value
Label Anchor="**C**,T" Offset="**300**,480" Font="TwCenMT18" ID="AntiquitySites"
Label Anchor="**C**,T" Offset="**329**,510" Font="TwCenMT18" ID="HiddenSites"

![1](https://cloud.githubusercontent.com/assets/11933188/10966526/71565102-83f7-11e5-8958-c9fc1280c66d.png)

Tentative value
Label Anchor="**L**,T" Offset="**700**,480" Font="TwCenMT18" ID="AntiquitySites"
Label Anchor="**L**,T" Offset="**700**,510" Font="TwCenMT18" ID="HiddenSites"

![2](https://cloud.githubusercontent.com/assets/11933188/10966530/73a928bc-83f7-11e5-82ec-2c20a5c0e707.png)

Related files
- Community Balance Patch\LUA\CultureOverview.xml
- Community Balance Patch - Compatibility Files (EUI)\LUA\CultureOverview.xml
- Community Balance Patch - Compatibility Files (No-EUI)\LUA\CultureOverview.xml

**Comment by LoneGazebo** [comment]
Works for me. I hate interface stuff, so any improvements are grand

G
