### ISSUE TITLE
MinAreaSize in the Buildings table does nothing

### ISSUE THREAD

**Issue by HungryForFood** [LoneGazebo/Community-Patch-DLL#7440]
In the unmodded Civ 5, MinAreaSize is used in conjunction with the Water column to make buildings require the water body the city is adjacent to to be of certain size.  Without MinAreaSize, Water enables the building to be built even if the city is built on 1 tile lakes.

This behaviour was changed in this [commit](https://github.com/LoneGazebo/Community-Patch-DLL/commit/8405f2d3d6ccc772e3a57861327f4019064cbc4e). The change is in the function CvCity::isValidBuildingLocation.

Specifically, before:
```
	// Requires coast
	if(pkBuildingInfo->IsWater())
	{
		if(!isCoastal(pkBuildingInfo->GetMinAreaSize()))
			return false;
	}
```

After:
```
	// Requires coast
	if(pkBuildingInfo->IsWater())
	{
		//-1 is ocean (fast check), 1 is any lake (not cached, slower)
		if(!isCoastal(-1) && !isCoastal(1))
			return false;
	}
```

Should be the following instead if we want to do the optimisation route:
```
	// Requires coast
	if(pkBuildingInfo->IsWater())
	{
		//-1 is ocean (fast check), 1 is any lake (not cached, slower)
		if(!isCoastal(-1) && !isCoastal(pkBuildingInfo->GetMinAreaSize()))
			return false;
	}
```

If we look at CvCity::isCoastal though:

```
bool CvCity::isCoastal(int iMinWaterSize) const
{
	if (iMinWaterSize==-1)
		iMinWaterSize = GC.getMIN_WATER_SIZE_FOR_OCEAN();

	VALIDATE_OBJECT
	return plot()->isCoastalLand(iMinWaterSize);
}
```

We see that if the argument is -1, it gets changed to 10 via GC.getMIN_WATER_SIZE_FOR_OCEAN() anyway, so there's no optimisation in the end.

There is a CPU save at CvPlot::isCoastalLand if we put min water size as -1 though, so maybe we can get rid of the check for -1 in CvCity::isCoastal. Not sure how it would affect other functions that call it though.

```
bool CvCity::isCoastal(int iMinWaterSize) const
{
	VALIDATE_OBJECT
	return plot()->isCoastalLand(iMinWaterSize);
}
```

I would fix this myself, but it seems that one of us changed this, and CvCity::isCoastal is used by many other functions, so I rather discuss it first.

At the same time, there is a gameplay implication, as fixing this would prevent Lighthouses, Harbours, and Seaports from being built at lake cities again, as before. If we decide to allow these buildings at lake cities, we will need to change their MinAreaSize to -1.

Related to #7183, #7011.

**Comment by RecursiveVision** [comment]
@ilteroi

**Comment by Mileslewis** [comment]
I think it's good to allow people to build lighthouses etc next to lakes if they want to.

Only negative I can think of is that AIs will probably waste time building them unnecessarily.

**Comment by ilteroi** [comment]
i have a love/hate relationship with git blame, haha.

anyway what i did is a hack on top of a lot of other hacks ... your proposed fix seems good though.
