### ISSUE TITLE
AI deal equalization bargaining

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7443]
@LoneGazebo I think that when proposing deals to or equalizing deals with humans, the AI should offer the maximum value they're willing to accept. There have been several complaints about consistently needing to adjust the deal upward by a few GPT - and this requires extra clicking. :P

Humans are capable of choosing whether they want to give a favorable deal by accepting less to gain diplo bonuses or for whatever other reason, so while this mechanic may be realistic, I don't think it's fun for most players.

**Comment by Stalker012345** [comment]
Completely agree. It seems like a neat idea initially, but very quickly becomes tedious.

**Comment by ilteroi** [comment]
the real question is type of items used for equalization. which items should be preferred? i would say only same type and gold for instant deals / gpt for long term deals.

**Comment by NewFellow** [comment]
It would be such a relief if the AI would start offering their maximum prize.

**Comment by LoneGazebo** [comment]
The reason is because there’s wiggle room in the offers to make it easier for the AI to make seas. What you see is the wiggle room.
