### ISSUE TITLE
1/15 - Teaching the AI how to build the spaceship "properly"

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7444]
So having won several games on deity where the AI just fell asleep at the wheel building SS parts, I thought I would post some thoughts on Github to help improve it.

This is the technique I generally use when building parts. There are deviations of course, but this method is tried and true and generally lets me build parts very quickly.

1) Designate my 4 highest production cities as my SS part producer. I ensure they all get: Factory, Trainstation/Seaport, Power Plant, SS Factory.

2) Once I get the first part tech, it goes into the worst production city of the 4.

3) Next parts go into the next worse production city. If its the booster, then my capital and the other 2 cities get them.

4) The last parts are set so that ultimately my capital is building 2 parts, my 2nd highest production city is building 2, and my other two cities build 1 each.

5) As TRs finish, new ITRs are set up in the capital and 2nd production city. At this point, my goal is to shave off turns on which ever city is going to be slowest with its final part. I will also use gold and/or engineers if my policies allow for the same purpose.

6) If I'm doing it right, the capital and 2nd city will finish their parts within a turn or two of each other. All parts are collected, and the spaceship goes to work!

7) With this method I can generally finish the spaceship 7-10 turns after the last SS part tech, depending on my final production numbers.

**Comment by ilteroi** [comment]
this is unfortunately way too complex ... coordination between multiple cities and subsystems is sorely lacking. but maybe g can do something about production choices at least.

**Comment by Stalker012345** [comment]
> this is unfortunately way too complex ... coordination between multiple cities and subsystems is sorely lacking. but maybe g can do something about production choices at least.

Yeah all the TR coordination and stuff is honestly the icing on the cake. If the AI simply understands to spread out its parts and build them simultaneously it will shave off a large number of turns.
