### ISSUE TITLE
1/15 - Exporting an Item immediately after gaining it does not give you the benefit for CS quests

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7445]
_1. Mod version (i.e Date - 12/1):_
1/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This seems to be a slight error in the priority of what happens first. If you get a CS quest that says "gain horse as a resource". If you acquire horses, often teh AI will immediately make an offer for them. If you accept it, and it takes your last horse...then you don't get the CS quest. Meanwhile if you decline, you'll get the quest, and then can speak with the AI and then make the same deal they offered before.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/106338211-d8455a80-6258-11eb-988d-acb53765b824.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by psparky** [comment]
You need to have the resource on the CS's turn, which comes after the AI that might buy it.

It is a bit quirky, but I think it's working as expected. But let's see what the experts say...

**Comment by ilteroi** [comment]
indeed. quests are processed on the quest giver's turn.
