### ISSUE TITLE
merge hell

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7449]
i'm not sure what's going on but we have two wildly different branches now, it seems rsi is different from what it was before.

the only halfway possible method to reconcile the two was to rebase "rsi" onto "mil". i'm 99% sure it went well. the result is called "mrg". please let's use that one from now on.

**Comment by RecursiveVision** [comment]
@ilteroi I copied all the folders from Community-Patch-DLL that were changed, deleted RSI, created a new RSI branch based on master, then pasted all the folders back in.

Then Gazebo merged that, and then I rebased it off of master again.

**Comment by RecursiveVision** [comment]
And I don't see a mrg branch?

**Comment by ilteroi** [comment]
d'oh. forgot to push. now it's there.

please keep in mind the first rule of git ... do not rewrite public history.

**Comment by RecursiveVision** [comment]
Ok. Well I'm done making changes for an indefinite amount of time so no worries.

**Comment by RecursiveVision** [comment]
...or maybe not...I was in a terrible mood when I wrote that. :)

anyway i'll use mrg

**Comment by RecursiveVision** [comment]
@ilteroi see #7458
