### ISSUE TITLE
Franchises & Transnationalism

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#745]
I'll group these two issues together even though one of them isn't a bug and the other is questionable, too. However, I sense something fishy, so I hope you don't mind.

First of all, I'm currently playing on a standard-sized map, sitting at 10 trade routes in the early information era. At this point my total possible franchise count is capped at 4. I think it is too low - it means the cap can't possibly get incresed by Transnationalism, since it requires at least a cap of 5. Mind you this is early information era, whereas corporations become available (and so theoretically does Transnationalism) in the early modern era, when the amount of trade routes one can posess is lower.

However, if one half of Transnationalism is underperforming the other one has been clearly overperforming in my experience. The random franchise spread triggers way too often - It got procced twice in about 5 turns or so and then about 10-15 turns later it got procced the third time (I'm very sorry I don't have the exact numbers). Basically, only 1 of the 4 franchises spread naturally by a trade route. This can probably be a lucky RNG roll, but it is aggravated by the low franchise count cap.

**Comment by LoneGazebo** [comment]
Yep, already fixed for upcoming version.
G

**Comment by Edaka** [comment]
Transnationalism still procs way too frequently for me. Something around once every 3-4 turns on standard speed.

**Comment by LoneGazebo** [comment]
I'll take a look.

**Comment by Edaka** [comment]
Also, false notifications for newly spread franchises continue appearing after the cap's been reached.
