### ISSUE TITLE
1/15 Byzantium found second religion

### ISSUE THREAD

**Issue by pikasnoop** [LoneGazebo/Community-Patch-DLL#7450]
_1. Mod version (i.e Date - 12/1):_
1/15 first hotfix

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
After I conquered Byzaniums capital and holy city I used an inquisitor on it. A few turns later Byzanium found its second religion. Which probably should not be possible. Also the AI immediately decided it did not want this new religion and used an old inquisitor on their new holy city. (I did not directly see this happen, but the holy city had only original religion followers and had a turn of anarchy)

_4. Steps to reproduce (optional):_
Speculation here:
1) Let Byzantium found
2) Conquer holy city
3) not sure if needed - Use inquisitor on holy city
4) Wait for Byzantium to generate a new profet and let them found a religion

I can provide screenshots and/or my save tomorrow if necessary.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Founding a second religion is intended; inquisiting it right after founding probably isn't.

@ilteroi

**Comment by Mileslewis** [comment]
I think maybe once a civ has founded a religion they never accept that they are another religion later on.

For example Japan founded a religion (Shinto) in my game. I conquered their holy city and then converted all their remaining cities over to my religion (Taoism). But they were still trying to use shinto missionaries/inquisitors as if Shinto was still their religion. Also I never got the positive diplo modifier for shared religion.

**Comment by RecursiveVision** [comment]
Diplo bonus not applying is intended.

**Comment by ilteroi** [comment]
i did not invent this religion business
