### ISSUE TITLE
Spies as diplomats get no XP

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#7451]
_1. Mod version (i.e Date - 12/1):_
1/15-3

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP + some UI

_3. Error description:_ 
Spies as diplomats get no XP. Their status shows as idle even when they are established as diplomats.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20210128191116_1](https://user-images.githubusercontent.com/13261433/106371135-8f5bd780-6326-11eb-8ade-8c49a56318db.jpg)

**Comment by R3P0FFXI** [comment]
My spies all rank up as diplomats, I usually toss them into civs who truly hate me for faster rank up before dropping them in my main cities. What we really should be talking about it when I recruit my spies I always seem to get 2 instead of 1.

**Comment by Mileslewis** [comment]
They do get exp when they get intrigue which is in the other tab on espionage overview, rank 3 is maximum though and diplomats don't do missions like normal spies.

Getting 2 instead of 1 is based on mapsize.

**Comment by oalzubbi** [comment]
Hmm, the tooltip says "Special Agent is sitting at the hideout doing no good"
