### ISSUE TITLE
CTD 2/4 Beta Hotfix 2 - Please make these unknown CTD a priority!

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#7452]
_1. Mod version (i.e Date - 12/1):_
1/15 beta

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Another Random CTD

_4. Steps to reproduce (optional):_
Please stop adding new features until all the CTD are fixed I've had 6 crashes this AM for no reason. The system was not even calculating anything it was a CTD when I was inside one of my cities selecting something.

Make that 7 now this one was when I was upgrading to Cannons via gold

8th CTD just happened when I used a great scientist and started upgrading to cannons again 

9th CTD today inside city screen was not even selecting anything

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bsesar** [comment]
@R3P0FFXI , if you are using the latest hotfix and no other mods, I can check if I am getting the same CTDs. If you upload a savegame to this page, I can check them out.

**Comment by R3P0FFXI** [comment]
> @R3P0FFXI , if you are using the latest hotfix and no other mods, I can check if I am getting the same CTDs. If you upload a savegame to this page, I can check them out.

@bsesar the issue is it does not always CTD at the same spot. Even with a saved game it really does not matter at the point. The only MODS I use are Really advanced setup and extra resources V1. Neither of these should have any affect on VP 800 turns into the game.

If you look at the last 2 crashes they happened when I was not doing anything IE clicking on a city and going into it. Or clicking on a unit to upgrade.

**Comment by azum4roll** [comment]
Do you get CTDs a short time after you load the game, or is it after long time of playing?

**Comment by R3P0FFXI** [comment]
> Do you get CTDs a short time after you load the game, or is it after long time of playing?

Can happen anytime, Turn 1 or Turn 5000

**Comment by bsesar** [comment]
@R3P0FFXI , I'm not an expert, but to me it seems that the issue is outside Vox Populi. Maybe your computer's memory, main board, or graphics card are starting to have problems. Have you tried to play with lower graphics settings? Or maybe the drivers need to be updated? Do CTDs happen with older versions of VP?

In any case, debugging is hard and without having savegames to reproduce CTDs, close to impossible.

**Comment by R3P0FFXI** [comment]
> @R3P0FFXI , I'm not an expert, but to me it seems that the issue is outside Vox Populi. Maybe your computer's memory, main board, or graphics card are starting to have problems. Have you tried to play with lower graphics settings? Or maybe the drivers need to be updated? Do CTDs happen with older versions of VP?
> 
> In any case, debugging is hard and without having savegames to reproduce CTDs, close to impossible.

@bsesar it is not my PC only Vox crashes these crashes started with the 10-1 version of VP. I have even done a complete reinstall. It is not a driver issue either this is 100% an issue with Civ 5 and VP

**Comment by RecursiveVision** [comment]
@R3P0FFXI You need to attach the CvMiniDump.dmp file, see the new issue instructions.

If you are constantly experiencing random crashes and no one else is the problem is likely on your end...

**Comment by Vyyt02** [comment]
Also, you can try downloading an older version of VP and see if it is also CTDing for you.

**Comment by R3P0FFXI** [comment]
@RecursiveVision I have unloaded all MODS except 2/4 Beta Hotfix 2 and will see if the issue still occurs. Please note I am not the only one experiencing CTD. The problem is these are random they do not occur on the same turn from the same saved game. 

I have had them when going into city screens, when selecting new research, when upgrading units with gold as well as when the game is processing turns. This is not some simple 1 off I suspect this is due to a memory leak in VP but I have no way of proving that.

I have also tested my ram and verified, I do not get crashes in ANY of the other games I play with MODS, Xcom, Xcom 2, or FFXI.

Normally I only use the extra extra resources which is supposed to be compatible with VP as well as Really Advanced Setup which is not longer updated. Once the game builds I do not see how Really Advanced Setup could cause the issue. 

I am starting anew fresh game today with VP 2-4 Hotfix 2 and will let you know how it goes.

@Vyyt02 I have had this issue with VP since 10/1, I have uninstalled and physically deleted all the old mods. I redownloaded VP and installed the beta patches fresh on 1/10. I have updated and verified all my drivers manually form the manufacturer websites. T

**Comment by R3P0FFXI** [comment]
@RecursiveVision Please see the attached mini dump as expected I had another CTD the only MOD I had was the extra resources MOD which adds rubber sulfur etc to the game. This crash happened as I was cycling through units during a WAR with Ghandi

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5937820/CvMiniDump.zip)

**Comment by R3P0FFXI** [comment]
@RecursiveVision Maybe you can figure out what caused the crash here. I seem to actually have a save that every time I load it will continue crashing.

[AutoSave_0170 BC-1800.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5937923/AutoSave_0170.BC-1800.zip)

Please see the attached screenshot  of the MODS I have loaded currently. 
![MODS](https://user-images.githubusercontent.com/10148511/107133163-44f0d280-68b3-11eb-86a4-1b542f63c51e.jpg)

And the current Minidump

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5937929/CvMiniDump.zip)

**Comment by Tarzan737** [comment]
I have this issue to, just using VP mods ,quick turns and no futuristic units

i get CTD late game around industrial area, randomly CTD and then can´t load the latest autosave
