### ISSUE TITLE
FLAVOR_RECON goes mega high in early game?

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7454]
Had an issue in promotion logic which must have been caused by very high FLAVOR_RECON outweighing all the other factors.

Seemed to suddenly happen to quite a few civs on around turn 5/6, not sure how long it lasts for.

Not sure but is this possibly what causes some to build many scouts as well?

**Comment by ilteroi** [comment]
hard to tell but the number of scouts is limited by the number of 'frontier' plots.

as for flavors, yes they are broken.
