### ISSUE TITLE
CTD on new research selection

### ISSUE THREAD

**Issue by physicalmetallurgy** [LoneGazebo/Community-Patch-DLL#7455]
_1. Mod version (i.e Date - 12/1):_
12-3 w/ 1/15 patch

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

CTD turn 279.  Last queued technology (Railroad) finishes researching.  Opening the research panel /tech tree (either from the upper left menu OR clicking the beaker icon which appears in the lower right notification stream) causes immediate CTD.  I loaded an autosave from turn 277 to attempt to queue up more technologies and avoid the crash after Railroad, but even there opening the research panel causes immediate CTD (i.e. before Railroad has completed researching).  Communitu_79 map, standard speed, Poland, warlord, no other mods / modmods.

Logs, turn 277 autosave, and CvMiniDump file attached in zip.

_4. Steps to reproduce (optional):_

Open research menu / tech tree per error description
[CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5900638/CTD.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
I couldn't load it, which version of VP are you using?
