### ISSUE TITLE
Cannot Stop Razing Cities

### ISSUE THREAD

**Issue by aakashjain28** [LoneGazebo/Community-Patch-DLL#7456]
_1. Mod version (i.e Date - 12/1):_
12/1

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi only

_3. Error description:_ 
After capturing and deciding to raze an enemy city, the razing process cannot be stopped. When pressing the 'Stop City Razing' button, nothing happens and the razing process proceeds as usual.

_4. Steps to reproduce (optional):_
Capture an enemy city and raze it. Click the 'Stop City Razing' button

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
cannot reproduce.

maybe it happens in special circumstances but not always. details needed.
