### ISSUE TITLE
2/4 - Specialist do not generate GP points

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7460]
_1. Mod version (i.e Date - 12/1):_
2/4

_2. Mod list (if using Vox Populi only, leave blank):_
Enhanced Naval Warfare, Logistic Skirmishers, Late Game Warfare

_3. Error description:_ 
None of my specialists in any cities are generating GP points.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@ilteroi as far as I recall you were the only one to change citizen logic...

**Comment by ilteroi** [comment]
i changed citizen assignment, not yields. also i cannot reproduce it on my branch

**Comment by randomnublet** [comment]
![civnogp](https://user-images.githubusercontent.com/53142313/107017619-a9227200-679f-11eb-8677-21c628312a69.png)


it is happening indeed

No other mods, clean cache

**Comment by Sphener** [comment]
Yes, the title of the issue is somewhat misleading I think. Specialists are contributing GPPs (as can be seen when mousing over any specialist), but the points are not incrementing the GP counter. @ilteroi perhaps you can try reproducing with Goddess of Beauty?

**Comment by RecursiveVision** [comment]
I'll run it through the debugger...

**Comment by RecursiveVision** [comment]
Problem seems to be that CvCityCitizens::ChangeSpecialistGreatPersonProgressTimes100() is not being called.

**Comment by RecursiveVision** [comment]
Can confirm that no sources of GPP are being added, though.

**Comment by RecursiveVision** [comment]
@ilteroi 
Line 306 of CvCityCitizens.cpp :)
```
	//nothing else to do ...
	if (thisPlayer.isHuman())
		return;
```

This is called before DoSpecialists() which updates GPP progress.

Thanks to @Mileslewis for finding this.

**Comment by ilteroi** [comment]
ah ok so it only seemed to work in the UI ...

**Comment by Stalker012345** [comment]
Note that while the HF did fix the issue for specialist, the points from wonders and things are still not working.

**Comment by RecursiveVision** [comment]
It works if you start a new game.
