### ISSUE TITLE
Ships cannot pass through citadels on resource tiles

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7462]
@ilteroi (They are supposed to be able to)

**Comment by Stalker012345** [comment]
Could also be related to #7463

**Comment by ilteroi** [comment]
i'm not aware of any recent changes here ... but i'll check

**Comment by RecursiveVision** [comment]
hm.

**Comment by RecursiveVision** [comment]
maybe fixed in the latest?

**Comment by RecursiveVision** [comment]
I tried it and can't reproduce it either, yet it's been reported several times. Weird.

**Comment by bsesar** [comment]
Have you tried reproducing the bug after creating the citadel with a GG *outside* of your borders, @RecursiveVision ?

**Comment by ilteroi** [comment]
duplicate
