### ISSUE TITLE
1/15 - Citadel + Fort no longer creates an effective Canal

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7463]
_1. Mod version (i.e Date - 12/1):_
1/15

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In previous versions you could make a 2 tile canal with fort + citadel or even a 3 tile one with Fort + Citadel + Fort. Those are no longer possible.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/107077170-1a6b2080-67b2-11eb-8e83-366854ce4db9.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Yes, I agree, 5e has a lot of broken mechanics. Wish + Simulacrum chains are amazing. Oh, right...this is about a canal. :)

**Comment by Stalker012345** [comment]
Recursive you tagged as cannot reproduce. So are canals working normally for you?

**Comment by RecursiveVision** [comment]
ilteroi's canal worked. But I have an idea of what the problem might be...hold on.

**Comment by RecursiveVision** [comment]
Yeah, no dice. I can't reproduce the bug either.

**Comment by Mileslewis** [comment]
I think the canals don't work if at the moment you build it it's out of your borders

So here you Great Generalled from outside the border so it hasn't worked.

**Comment by RecursiveVision** [comment]
@ilteroi

**Comment by RecursiveVision** [comment]
Cause identified!

![Screenshot (8918)](https://user-images.githubusercontent.com/66801010/107107188-8030ca00-67fd-11eb-9c11-d34379b850a6.png)
![Screenshot (8919)](https://user-images.githubusercontent.com/66801010/107107190-8161f700-67fd-11eb-9276-534045395c4c.png)
![Screenshot (8920)](https://user-images.githubusercontent.com/66801010/107107192-82932400-67fd-11eb-94ce-acd5c2ef0dfb.png)
