### ISSUE TITLE
2/4 HF1 - Mt Fuji does not count as a mountain for Nature Pantheon

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7464]
_1. Mod version (i.e Date - 12/1):_
2/4 HF1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Probably just the way natural wonders work, but though it quacks like a duck ("Mt" Fuji), and looks like a duck (impassible terrain), it is not a duck for purposes of the nature pantheon.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/107086541-c8c99280-67bf-11eb-9ac5-ab7b3d695958.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Would need to add an "IsMountain" column or something...

**Comment by RecursiveVision** [comment]
actually want to test this some more

**Comment by ilteroi** [comment]
natural wonders are weird, lake victoria is not a lake either.

it's because they are treated as features which are added on top of the underlying plot type / terrain type.

would need to change all map scripts to fix?
