### ISSUE TITLE
2/4 HF1 CS quests aren't triggering

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#7465]
I witnessed both the barbarian encampment quest (the quest disappeared one turn after I cleared the encampment with a spearman) and the resource connection (CS asked for copper, I traded for copper, quest is still there) not triggering.

![civnocs](https://user-images.githubusercontent.com/53142313/107098815-6fd61a80-6810-11eb-80da-f49efaea69d5.png)

**Comment by RecursiveVision** [comment]
@ilteroi you're the only one who changed CS quests

**Comment by Mileslewis** [comment]
Quests are fine for me using 2-4 hotfix 1 VP EUI.

**Comment by ilteroi** [comment]
seems to be a deserialization issue, so occurs only after reloading. fixed.

**Comment by randomnublet** [comment]
> 
> 
> seems to be a deserialization issue, so occurs only after reloading. fixed.

Is this a subtle way to enforce a no reloads, one session only civ game? :D can I fix it somehow for a game in progress?
