### ISSUE TITLE
Beta patch 2/4 - Persia Peace Deal "Impossible" despite them wanting it

### ISSUE THREAD

**Issue by sgwicks** [LoneGazebo/Community-Patch-DLL#7466]
_1. Mod version (i.e Date - 12/1):_

Beta patch 2/4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Persia wants a peace deal, but the deal is set to "Impossible" and they won't accept it

Darius comes to me every few turns to offer peace, but won't accept even if I say "yes" right away. If I ask what he's willing to give me, he'll offer some gold, but won't accept if I do. Even if I offer a blanket white peace, it's still impossible.

I haven't had troubles making peace with any other civilization, though those have always been wars where no cities changed hands. Every war this game has been prompted by the Ottomans or Portugal.

This is the only war I asked for "10 turns to prepare" instead of waging war immediately. I declared at the same time as the Ottomans, though they peaced out quite a while ago without any cities exchanging hands.

_4. Steps to reproduce (optional):_

Just ask Persia for a peace deal.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5936594/Logs.zip)

[Persia Wont Peace.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5936597/Persia.Wont.Peace.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![20210206090612_1](https://user-images.githubusercontent.com/60254658/107114862-f87ca700-6860-11eb-8129-720cc8c1fd4e.jpg)

**Comment by airbse** [comment]
+1

**Comment by RecursiveVision** [comment]
@airbse @sgwicks I'm trying to figure this one out: https://forums.civfanatics.com/threads/new-beta-patch-2-4.667153/page-4#post-16022224
