### ISSUE TITLE
Bordergrowth 2/4

### ISSUE THREAD

**Issue by Sekisetsu** [LoneGazebo/Community-Patch-DLL#7467]
So I started a new game on newest patch and have some issues with my city getting always the wrong tile.

![city tile](https://user-images.githubusercontent.com/20355596/107116685-397eb680-6875-11eb-9848-0a4da7130eca.jpg)

I just want to have the salt, but it isn't even considered to get?
I think that is wierd.

**Comment by ilteroi** [comment]
it's on the far side of the river in rough terrain
