### ISSUE TITLE
Unit Promotions that give bonuses to nearby units not working

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#7468]
_1. Mod version (i.e Date - 12/1):_

_2. Mod list (if using Vox Populi only, leave blank): Mor unique Components for VP

_3. Error description:_ 
I have been getting a lot of bug reports that a few features have stopped working in my mods as of a few months ago. They all use the IsNearbyPromotion dll feature.
The promotion bonuses that give certain abilities to nearby units of specific domains and at specific ranges have stopped working in the latest versions. I tested these tables when I implemented them over a year ago, so I am wondering if they were inadvertently deactivated, or if they were removed for optimization?

Specifically, I have a unit that gives +50% XP to adjacent land units via the UnitPromotions table, using the following columns:
GiveExperiencePercent, 	
GiveCombatMod,
IsNearbyPromotion, 
NearbyRange
GiveDomain,		

Maybe the IsNearbyPromotion bonuses could be locked behind an option if they are too intensive?

**Comment by RecursiveVision** [comment]
@ilteroi

**Comment by ilteroi** [comment]
they are disabled on purpose. because the bookkeeping was a significant performance drag in the lategame.

can't you just build your own version?

**Comment by pineappledan** [comment]
We originally did have our own versions, but these tables worked better. 

Couldn't they just be gated behind a CustomModOption?

**Comment by ilteroi** [comment]
yeah yeah it's done. set CORE_AREA_EFFECT_PROMOTIONS to 1 to enable them.
