### ISSUE TITLE
FeatureRequest: Improvement_ResourceQuantityRequirements

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#7469]
Could a table be added that allows modders to add improvements that consume strategic resources, identical to the Strategic resource requirements for some buildings and units? 

That would open up new options for modders to add different unique requirements for improvements besides tile placement limitations.

**Comment by Padre19** [comment]
UPDATE CustomModOptions SET Value = 1 WHERE Name='IMPROVEMENTS_EXTENSIONS';


CustomMods.cpp[267]: CustomMods::getOption - Cache: IMPROVEMENTS_EXTENSIONS has missing database updates!
CustomMods.cpp[272]: CustomMods::getOption - Cache: IMPROVEMENTS_EXTENSIONS = 0

**Comment by Padre19** [comment]
- Improvement does not consume resources.
- You can create improvement even if you do not have enough resources.

**Comment by RecursiveVision** [comment]
@HungryForFood
