### ISSUE TITLE
AI overvalues strategics when sold/bought in bulk

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#747]
Works both ways.

Atilla will happily sell me 1 coal for 9gpt four times in a row.
But he wants nothing less than 132 gpt for 4 coal.

Observed with every AI and every resource.

**Comment by TechpriestEnginseer** [comment]
Could it be that the scaling strategic resources are on a logarithm scale rather than a multiplicative scale?

**Comment by LoneGazebo** [comment]
It's an issue with the point where the quantity is considered. I'm rewriting the resource deal code anyways, so I'll fix this.
