### ISSUE TITLE
CTD with 2-4 hotfix 2 on reload of new hotfix 2 savegame

### ISSUE THREAD

**Issue by CliveJarman** [LoneGazebo/Community-Patch-DLL#7470]
_1. Mod version (i.e Date - 12/1):_
2-4 Hotfix 2

_2. Mod list (if using Vox Populi only, leave blank):_
3rd and 4th components for vox populi ver 62

_3. Error description:_ 
CTD when I reload a save game

_4. Steps to reproduce (optional):_
Reload savegame
[AutoSave_0055 BC-2625.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5937563/AutoSave_0055.BC-2625.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
As I noted, it's not savegame compatible

**Comment by CliveJarman** [comment]
It was saved with the latest hotfix 2!

**Comment by CliveJarman** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5937566/Logs.zip)

here are the logs

**Comment by CliveJarman** [comment]
@RecursiveVision  please unclose this!

**Comment by RecursiveVision** [comment]
Sorry, I misunderstood :)

Will investigate promptly

**Comment by CliveJarman** [comment]
Thanks! Your the best!

**Comment by CliveJarman** [comment]
@RecursiveVision I just went back in my autosaves and found when this started happening. The first save in this list opens OK. The next turn autosave has the CTD. Hope this helps!
[Saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5937674/Saves.zip)

**Comment by ilteroi** [comment]
my bad. fixed

**Comment by RecursiveVision** [comment]
fixed in hotfix 3
