### ISSUE TITLE
Gandhi denounces and declares war on turn 28 (epic, huge)

### ISSUE THREAD

**Issue by dostillevi** [LoneGazebo/Community-Patch-DLL#7471]
_1. Mod version (i.e Date - 12/1):_
12-1-3 with the 2/4 beta

_2. Mod list (if using Vox Populi only, leave blank):_
![image](https://user-images.githubusercontent.com/39426657/107106950-27ecce80-67e3-11eb-85e6-f91e89dac0a2.png)

_3. Error description:_ 
Gandhi declared war on me almost immediately after first contact, likely due to feeling threatened to me scouting with my warrior.

_4. Steps to reproduce (optional):_
Start a game near Gandhi, then scout near him with a warrior.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/39426657/107128581-adb85a80-6873-11eb-8157-d1806d16607f.png)
![image](https://user-images.githubusercontent.com/39426657/107128585-b1e47800-6873-11eb-80c0-6484e385f07f.png)

**Comment by RecursiveVision** [comment]
Logs and save file, please?

**Comment by dostillevi** [comment]
Unfortunately I have neither. This happened several games ago and the autosave has been overwritten.

**Comment by dostillevi** [comment]
Here are my current logs in case they have anything going back that far. The issue occurred Thursday around 10:45 PM.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5937570/Logs.zip)

**Comment by RecursiveVision** [comment]
I think I know what's the problem.

**Comment by RecursiveVision** [comment]
Too much aggression re: tech/policy competition. Should be better in the next version.
