### ISSUE TITLE
[2/4 Hotfix 3] Random CTD (but almost always during AI turn) 

### ISSUE THREAD

**Issue by 0x192** [LoneGazebo/Community-Patch-DLL#7475]
_1. Mod version (i.e Date - 12/1):_  **2/4 Hotfix 3**

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Those CTD issues were introduced in 2021 patches. I tested on **12-1-3** and everything is fine.

I ran multiples games trying to isolate a bit the problem. In 90% of my games I can't pass the first turn. The game CTD during the AI turn. I can however reload the save and keep playing for 20 to 100 turn without any issue until it crash again for no reason. I can always reload the save and continue the game.

It is pretty rare but sometimes the game also crash during my turn.

I think all the recent CTD issues are related (#7452, #7380 ...). This reminds me this CTD issue #6829 that only some people experienced. It would not surprise me if it's another segmentation fault.

PS: Thanks **a lot** for your devotion on this mod. You guys are awesome. Really! :)

---------------------------
Supporting information:
- [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5939771/Logs.zip)

I don't know if the dump is overwritten each time so I uploaded 2 of them (crash on turn 1 and crash on turn ~115)
- [CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5939767/CvMiniDump.zip)

**Comment by ilteroi** [comment]
well the first minidump points to a place where a crash could conceivably happen, but the second one is unfortunately useless ...
