### ISSUE TITLE
2/4 HF3 UI display bug

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#7476]
Hovering over the culture on top panel I can't get the details (total culture needed for next poilicy)

![civcultureui](https://user-images.githubusercontent.com/53142313/107161925-30d6cf00-69a0-11eb-836f-0dd5442a2731.png)

Moving my mouse over the other informations (faith, happiness, supply cap) displays the correct info, then going back checking the culture shows me the details of such last information I checked (just imagine I am always checking culture, the yellow arrow being my mouse cursor)

![civuiculture](https://user-images.githubusercontent.com/53142313/107161960-64195e00-69a0-11eb-9500-441419d2a676.png)

**Comment by RecursiveVision** [comment]
Fixed in HF4
