### ISSUE TITLE
Question for ilteroi

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7478]
```
							if (pLoopUnit->isDelayedDeath() || pLoopUnit->plot() == NULL)
								continue;

							bool bMoveMe  = false;
							IDInfo* pUnitNodeInner = pLoopUnit->plot()->headUnitNode();
							while(pUnitNodeInner != NULL && !bMoveMe)
							{
								CvUnit* pLoopUnitInner = ::GetPlayerUnit(*pUnitNodeInner);
								if(pLoopUnitInner && pLoopUnit != pLoopUnitInner)
								{
									if(pLoopUnit->getOwner() == pLoopUnitInner->getOwner())	// Could be a dying Unit from another player here
									{
										if (!pLoopUnit->canEndTurnAtPlot(pLoopUnit->plot()))
										{
											if(pLoopUnitInner->IsFortified() && !pLoopUnit->IsFortified())
											{
												bMoveMe = true;
											}
										}
									}
								}
								pUnitNodeInner = pLoopUnit->plot()->nextUnitNode(pUnitNodeInner);
							}

							if(bMoveMe)
							{
								if (!pLoopUnit->jumpToNearestValidPlotWithinRange(1))
									pLoopUnit->kill(false);
								break;
							}

							pLoopUnit->doDelayedDeath();
```

So you added a fix here, but I notice that at the end of this loop where "isdelayeddeath" causes a continue, the function "doDelayedDeath" is called which kills the unit if it's set to be "delayed death"...whatever that means exactly, I'm assuming it refers to when a unit is still visible on screen and hasn't completely died yet.

Is the delayed death stuff handled elsewhere or was this an oversight?

If it isn't an oversight, the doDelayedDeath call is useless...

**Comment by ilteroi** [comment]
hmm, well that change was an act of desperation to fix that mystery crash ...

anyway i think the pLoopUnit->doDelayedDeath() line is redundant. delayed death is handled in other places.

**Comment by RecursiveVision** [comment]
ok I'll just remove it in #new-beta if it's redundant then :)
