### ISSUE TITLE
2/4 HF3 - Occasionally, attack on enemy unit will cause it to fully heal

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7480]
_1. Mod version (i.e Date - 12/1):_
2/4 HF3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I've seen this occur twice now. When I am attacking a unit (it was with a c bowmen both times), the unit will go from very hurt to completely full. This isn't even a promotion thing, as the unit doesn't even have time to receive a promotion, this is literally right after the attack I make.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
Not attacking Sweden?

**Comment by RecursiveVision** [comment]
Sounds like Sweden's UA to me too

**Comment by Stalker012345** [comment]
Oh, you guys are right. I had forgotten that the GG is made right as the attacks are occurring, so it performs a heal.
