### ISSUE TITLE
China lost their first settler to barbarians

### ISSUE THREAD

**Issue by dostillevi** [LoneGazebo/Community-Patch-DLL#7481]
_1. Mod version (i.e Date - 12/1):_
12-1-3 with the first version of the 2-4 beta (no hotfixes)

_2. Mod list (if using Vox Populi only, leave blank):_
![image](https://user-images.githubusercontent.com/39426657/107306387-a478ea80-6a39-11eb-8d08-124608491ca9.png)

_3. Error description:_ 
China lost their initial settler to barbarians.

_4. Steps to reproduce (optional):_
Probably difficult to reproduce.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5948305/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5948301/auto.zip)

The initial autosave and the latest prior to me noticing the issue. China is south and a bit west of my starting location, their settler held in a barb camp.

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/39426657/107306824-721bbd00-6a3a-11eb-9d11-fdff27b22a23.png)

**Comment by ilteroi** [comment]
well that must have been a lot of bad luck. but should not happen anymore
