### ISSUE TITLE
2/4 HF4 specialists bug

### ISSUE THREAD

**Issue by rhaidinger** [LoneGazebo/Community-Patch-DLL#7483]
_1. Mod version (i.e Date - 12/1):_2/4 HF4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ The values from specialists only updates after a tile from the city changes to laborer, a specialist changes to a tile or the tiles get automativally redistributed. It is not (or not everything is) updating if a laborer or tile changes to specialist. Unhappiness is updated correct. It took a while to figure out whats causing the wrong numbers.

_4. Steps to reproduce (optional):_ see the screenshots
![VP_Korea_specialists_1](https://user-images.githubusercontent.com/76167984/107425968-f300b480-6b1f-11eb-8c0e-0b193ffb5e78.jpg)
![VP_Korea_specialists_2](https://user-images.githubusercontent.com/76167984/107425978-f6943b80-6b1f-11eb-9033-4ad1ee4b38fb.jpg)
![VP_Korea_specialists_3](https://user-images.githubusercontent.com/76167984/107425990-f85dff00-6b1f-11eb-8633-efd000c9e393.jpg)

1 Put all citizens to work on tiles. 
2 Fill your specialists slots (only do that) No change in the specialists numbers
3 Redistribute your remaining citizens automatically

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@ilteroi

**Comment by rhaidinger** [comment]
I played again and the royal astrologer is the first specialist building with this problem. The Guardhouse and the court chapel work fine at this point. I added the saves from these two games.
[sejong.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5954931/sejong.zip)

**Comment by ilteroi** [comment]
fixed but not proud at all ... my god that code is ugly
