### ISSUE TITLE
Joint-war malfunction

### ISSUE THREAD

**Issue by 1andUnly** [LoneGazebo/Community-Patch-DLL#7484]
_1. Mod version (i.e Date - 12/1):_2-4 hotfix 4. I also play with edited difficulty xml, to give King AI the best choices, if that matters for loading the save. 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5954180/Logs.zip)

_2. Mod list (if using Vox Populi only, leave blank):_3/4 UC version 63 from Jan 16th (I'd include it in the zip, but it makes the file too large) + these 
[Saves and Mods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5954177/Saves.and.Mods.zip)
 

_3. Error description:_I asked for 10 turns to prepare once America proposed to war against the Aztecs. A couple turns later Washington declares on the Aztecs prematurely, but I'm not triggered into the war.

_4. Steps to reproduce (optional):_Load save 186 and hit next turn. I've also provided the save from the turn after.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Natural war declaration

Problem check:
```
							CoopWarStates eCoopWarState = pDiplo->GetCoopWarState(eThirdParty, eLoopDefender);
							if (eCoopWarState == COOP_WAR_STATE_PREPARING)
							{
								if (pDiplo->CanStartCoopWar(eThirdParty, eLoopDefender) || (pDiplo->IsAtWar(eLoopDefender) && GET_PLAYER(eThirdParty).IsAtWarWith(eLoopDefender)))
								{
									pDiplo->SetCoopWarState(eThirdParty, eLoopDefender, COOP_WAR_STATE_READY);
									GET_PLAYER(eThirdParty).GetDiplomacyAI()->SetCoopWarState(eLoopPlayer, eLoopDefender, COOP_WAR_STATE_READY);
									pDiplo->DoStartCoopWar(eThirdParty, eLoopDefender);
								}
								else
								{
									CUSTOMLOG("Cancelling TRIGGERED coop war for Player %s with Player %s against Player %s: unable to start coop war!", GET_PLAYER(eLoopPlayer).getName(), GET_PLAYER(eThirdParty).getName(), GET_PLAYER(eLoopDefender).getName());
									pDiplo->SetCoopWarState(eThirdParty, eLoopDefender, NO_COOP_WAR_STATE);
									GET_PLAYER(eThirdParty).GetDiplomacyAI()->SetCoopWarState(eLoopPlayer, eLoopDefender, NO_COOP_WAR_STATE);
								}
							}
```

**Comment by RecursiveVision** [comment]
FINALLY FIXED IT

**Comment by RecursiveVision** [comment]
Arrrrrgh. I stared at the code for like an hour and I didn't see it. I feel stupid!

CvDiplomacyAI::CanStartCoopWar()
```
	// Can't be already at war with the target
	if (IsAtWar(eTargetPlayer))
		return false;
```
