### ISSUE TITLE
2/4 HF4 AI doesn't pick up goody huts very well

### ISSUE THREAD

**Issue by rhaidinger** [LoneGazebo/Community-Patch-DLL#7485]
_1. Mod version (i.e Date - 12/1):_ 2/4 HF4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ As mentioned in the title. They should have found and picked this goody hut. 
![goody hut](https://user-images.githubusercontent.com/76167984/107444331-ae364700-6b3a-11eb-82fe-23186fae776e.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
where is the goody and where are their units?

**Comment by rhaidinger** [comment]
North-West of Honolulu, next to the Bison. The warrior was guarding Honolulu. I have seen their pathfinder but have no idea where he was in Round 37 (epic). Still I think I have seen this behaviour quite a few times, that AI doesn't pick up goody huts next to their capital and I'm not sure why.

**Comment by RecursiveVision** [comment]
They might just not have seen it?

**Comment by rhaidinger** [comment]
In my opinion the AI seems to miss a lot of easy, close to their capital or close to their units, goody huts. It don't recall when I first thought "hmm, the AI was already better in picking up the goody huts" but I think something got worse the last year.
Anyway its not very clear so maybe somebody else has additional information or I have been just lucky and its not game breaking in any way. thx
