### ISSUE TITLE
UITradeRoutesEnhancements.xml

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#749]
I like the new UI.
How about adding a **Customs House** as one of the Local Trade Building Classes?

**Comment by LoneGazebo** [comment]
I added only buildings that affect what your trade routes can do (no market/bank/custom house), but if there's demand we can expand it.
G

**Comment by 8h42** [comment]
Ah, that makes sense.
Let's leave the setting as it is for the time being.

**Comment by Edaka** [comment]
Seeing this is an appropriate moment: the UI recognises the workshop instead of stone works as a condition for sending internal production trade routes.

**Comment by LoneGazebo** [comment]
Well, workshops are the universal equivalent, stone works are not. I'll add stone works to list, though.

**Comment by Edaka** [comment]
Oh, I didn't realise workshops still gave the ability to send production thinking it was moved entirely to stone works. 

Sounds good (:

**Comment by LoneGazebo** [comment]
Yep.
