### ISSUE TITLE
Why use #if defined (MOD_NAME) rather than if (MOD_NAME)?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7491]
I notice a lot of the code is written something like this:

```
#if defined(MOD_BLAH)
    if (MOD_BLAH)
    {
       code;
    }
#else
   code;
#endif
```

But is there a reason why it shouldn't simply be...
```
#define MOD_BLAH (isMOD_BLAH_ENABLED())

if (MOD_BLAH)
{
  code;
}
else
{
  code;
}
```

This seems easier to manage, and especially easier to read. Maybe it has a performance impact?

**Comment by ilteroi** [comment]
it's just an additional precaution to make the code to compile even without the custom mod options header.

but imho it's unncessary and makes the code ugly to read.

no performance impact in any case.
