### ISSUE TITLE
Joint-war trigger failure #2

### ISSUE THREAD

**Issue by 1andUnly** [LoneGazebo/Community-Patch-DLL#7492]
_1. Mod version (i.e Date - 12/1):_2/4 with hotfix 5. 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5969116/Logs.zip)

_2. Mod list (if using Vox Populi only, leave blank):_same as before except I updated 3/4 UC to version 64.
[Saves and Mods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5969114/Saves.and.Mods.zip)

_3. Error description:_The war against the Aztecs triggered properly after hotfixing, and during the conquest America proposed another against Japan. I again told him to wait 10 turns as we were in the process of eliminating Monty. A few turns go by with America eliminating the last Aztec city, and then he prematurely denounces + declares on Japan a couple turns later, except now I'm not pulled into that war as well. 

_4. Steps to reproduce (optional):_I've included the save on the turn he declared + a quicksave from a few turns prior.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Found one bug...trying to locate a second one.

**Comment by RecursiveVision** [comment]
Can't figure out the problem, perhaps the turn 196 save is after the coop war was cancelled.

**Comment by 1andUnly** [comment]
If you'd like, tomorrow I can try to upload an earlier save for you (from when he initially asks me to war Japan). Either way, it wasn't game-breaking or anything, so it's all good. I'm glad it helped you resolve an issue anyhow.

**Comment by RecursiveVision** [comment]
That'd be appreciated. :)

**Comment by RecursiveVision** [comment]
Seems the issue happened on turn 194.

https://gyazo.com/0f3375546a3bc29bfdd00dbcfe83b88f

**Comment by 1andUnly** [comment]
Yeah, this coincides with me taking the Aztec Capital, so I'd assumed the problem stemmed from the sequence of events around this time. Here are the saves from 193 and 194, all you have to do is take the capital and then his other city the following turn. America will then finish him right after.
[Saves and Mods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5972571/Saves.and.Mods.zip)

**Comment by RecursiveVision** [comment]
Tested it and it works now with the issue I fixed earlier.
