### ISSUE TITLE
City governor tile selection

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#7493]
Mod version : Patch 2/4

Error description: New case of strange default governor tile selection :
![20210212130914_1](https://user-images.githubusercontent.com/64471766/107766653-0f753a80-6d34-11eb-9d46-3974239de853.jpg)

Why working the 2f tile while there are better choices?

**Comment by ilteroi** [comment]
aaah. i should never have touched it, now i guess i'm responsible

**Comment by RecursiveVision** [comment]
If it helps, I've thought the same about diplomacy sometimes :)

**Comment by Zuizgond** [comment]
Hmm wait, I think I know why. I have God of the Open Sky so maybe it chooses this tile for the extra culture instead of the extra +1f+1g from the coast tile.

**Comment by ilteroi** [comment]
it's not a bug, it's a feature!

**Comment by Mileslewis** [comment]
Well I think governor seems much better this patch tbh. But yea still some weirdness.
