### ISSUE TITLE
12/1 CTD at end of AI turn, beginning of player turn

### ISSUE THREAD

**Issue by mparusk** [LoneGazebo/Community-Patch-DLL#7494]
_1. Mod version: 12/1

_2. Mod list (if using Vox Populi only, leave blank)

_3. Error description:
The game crashes somewhere at the end of the AI turn and in the beginning of the player turn. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5974089/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[AutoSave_0102_BC-0325.Civ5Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5974097/AutoSave_0102_BC-0325.Civ5Save.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.dmp.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5974094/CvMiniDump.dmp.zip)

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Old version
