### ISSUE TITLE
CTD 2/4 Beta Patch 4

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#7496]
_1. Mod version (i.e Date - 12/1):_
CTD 2/4 Beta Patch  4

_2. Mod list (if using Vox Populi only, leave blank):_

![MODS](https://user-images.githubusercontent.com/10148511/107860597-12445e00-6e0e-11eb-8f8b-24844033935f.jpg)

_3. Error description:_ 

CTD when processing other players next turn

_4. Steps to reproduce (optional):_
Hit next turn on player 10 save file will CTD during the processing other players.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5976455/Database.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5976451/QuickSave.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5976458/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Can't load the save.

**Comment by R3P0FFXI** [comment]
> Can't load the save. It doesn't display in my ModdedSaves folder.
> 
> Also if you're using additional mods it'd be appreciated if you attached those in a zip file, hunting them down on the forums is a pain...

Sorry to be a pain wasn't intentional. The modded save is a quicksave file I believe. I will zip and upload the mods for you shortly.

**Comment by R3P0FFXI** [comment]
Mods Attached

[pdansUnitTweaks(V4).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5978259/pdansUnitTweaks.V4.zip)

[National Parks (v 1).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5978260/National.Parks.v.1.zip)

[Even More Resources for Vox Populi (v 8).zip](https://github.com/LoneGazebo/Community-Patch-

DLL/files/5978261/Even.More.Resources.for.Vox.Populi.v.8.zip)

https://forums.civfanatics.com/resources/more-unique-components-for-vox-populi.26966/download?version=29850

[Really Advanced Setup (v 15).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5978274/Really.Advanced.Setup.v.15.zip)

**Comment by RecursiveVision** [comment]
ah. I've actually never used quick saves before. So THAT'S what it does...

**Comment by RecursiveVision** [comment]
Doesn't crash for me.

**Comment by R3P0FFXI** [comment]
> ah. I've actually never used quick saves before. So THAT'S what that folder does...
> 
> And no worries, it wasn't indicated as required on the issue template or anything, I just don't currently play with a lot of modmods :)

No problem some of these are just setup mods so would be really good to just drop them right in VP especially Really Advanced Setup

**Comment by amateurgamer88** [comment]
I have a similar situation as this issue. Should I post my save here to see if it's repeatable?

**Comment by ilteroi** [comment]
@amateurgamer88 : minidump please.

original minidump does not contain useful info, looks like a crash outside of the gamecore

**Comment by amateurgamer88** [comment]
Here's mine. Thanks! 

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5982197/CvMiniDump.zip)

**Comment by ilteroi** [comment]
nothing useful in there unfortunately
