### ISSUE TITLE
pPlayer:CalculateUnitSupply() doesn't work

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#7498]
_1. Mod version (i.e Date - 12/1): 02/04

_2. Mod list (if using Vox Populi only, leave blank):_ Goths for VP

_3. Error description:_ The command CalculateUnitSupply() doesn't work. It only returns 0

_4. Steps to reproduce (optional):_
I used the following code:
```
function GothSupplyToCulture(iPlayer)
	local pPlayer = Players[iPlayer]

	if not (pPlayer and (pPlayer:GetCivilizationType() == GothsID or pPlayer:GetCivilizationType() == eCivilizationRome)) then return end

	if (pPlayer:CountNumBuildings(eBuildingGulthsmitha) > 0) then
		local pCapital = pPlayer:GetCapitalCity()
		print("Goth Supply Yields")
		local pUnitSupply = pPlayer:CalculateUnitSupply()
		print(pUnitSupply)
		pCapital:SetNumRealBuilding(GameInfoTypes.BUILDING_DF_GULTHSMITHA_SUPPLY, (math.floor(pUnitSupply/10)))
	end
end
GameEvents.PlayerDoTurn.Add(GothSupplyToCulture)
```

**Comment by pineappledan** [comment]
Maybe I need to use player:GetNumUnitsSupplied() ?

**Comment by pineappledan** [comment]
yup! player:GetNumUnitsSupplied() does what I needed. Goodness knows what CalculateUnitSupply() is supposed to do

**Comment by Padre19** [comment]
Yes.
player:GetNumUnitsSupplied() - return total supply available (Top Panel.lua)
