### ISSUE TITLE
Minor request: No Followup From Cities and kasbahs

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#750]
Could kasbahs be made affected by NFFC so that units wouldn't move out of them if they defeat an enemy unit? Basically, the same way NFFC affects forts since kasbahs essentially are forts.

**Comment by TechpriestEnginseer** [comment]
Then it would have to affect chateau as well, since chateau essentially are forts.

**Comment by LoneGazebo** [comment]
That becomes a bit gamey for humans, as the AI isn't going to use that to their advantage.

**Comment by Edaka** [comment]
Ah, I didn't realise it was intentional. I imagine kasbahs don't need a buff either. It's weirder if chateaus don't have the no followup feature, but it's not a big deal.
