### ISSUE TITLE
Game hanging on processing turn 2/4 HF5

### ISSUE THREAD

**Issue by CyberPhy** [LoneGazebo/Community-Patch-DLL#7500]
2/4 HF5

The Game showed me the meet dialog for Dido without actually meeting her, during the processing turns it hung on Dido's turn

Steps to reproduce):I'm not sure this does not always happen

No Mini dump as the game did not crash 
the only log that had anything of worth was the net_message_debug.log
No save game because it was a new game I had just started 
[net_message_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/5979373/net_message_debug.log)

**Comment by CyberPhy** [comment]
@RecursiveVision  what information do you need?

**Comment by RecursiveVision** [comment]
Would need to be able to reproduce the bug; a savegame or something.

@ilteroi might be able to find the cause of the 7000 log entries for Dido's unit moves starting at line 3039 in the file you uploaded. Looks like an endless loop to me.

**Comment by ilteroi** [comment]
log is not really helpful, it points to CvGame::updateMoves() but i'm extremly wary of shotgun debugging in that area.

**Comment by CyberPhy** [comment]
unfortunate I don't have a save game as it was a new game, and my auto save settings was to long.

**Comment by CyberPhy** [comment]
Well I can't get this problem to happen now =_=
I guess I will close this problem and if it happens again I will reopen.
I don't know if this was just an isolated problem or if it only happens under certain conditions.
