### ISSUE TITLE
Venice's trade routes count double (2/4)

### ISSUE THREAD

**Issue by Omen-of-Peace** [LoneGazebo/Community-Patch-DLL#7501]
_1. Mod version (i.e Date - 12/1):_ 2/4 beta

_2. Mod list (if using Vox Populi only, leave blank):_ VP + UI mods

_3. Error description:_ when Venice gets Trade, they get 2 trade routes.
However, as soon as a caravan is built, the UI displays 2/2: the caravan seems to count for 2 TR.

**Comment by RecursiveVision** [comment]
![Screenshot](https://user-images.githubusercontent.com/66801010/109405060-7735a300-793a-11eb-9aee-591a8c78c903.png)

Keep in mind that caravans in city production queues count against your limit...

**Comment by Omen-of-Peace** [comment]
Yes, I know! I double-checked (it's not that hard with only 1 production queue).

Between this and the other issue with blocked peace, perhaps my install is borked. I'll try reinstalling in the coming days - restarting from the previous installer.
