### ISSUE TITLE
Crash at end turn/during AI turn

### ISSUE THREAD

**Issue by WardBenjamin** [LoneGazebo/Community-Patch-DLL#7502]
_1. Mod version (i.e Date - 12/1):_ 12/1, as a multiplayer modpack (DLC)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Crash at end of turn or during AI turn

_4. Steps to reproduce (optional):_
Open save. Do any action. Click end turn, and the game will crash to desktop.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs_Inca-MP.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5984494/Logs_Inca-MP.zip)

2. Save game: 
[Save_Inca-MP.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5984495/Save_Inca-MP.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[Dump_Inca-MP.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5984496/Dump_Inca-MP.zip)

4. Screenshots (optional):

**Comment by ilteroi** [comment]
is fixed already in latest beta, triggered by a city being liberated

**Comment by WardBenjamin** [comment]
Awesome, thank you!
