### ISSUE TITLE
Crash when moving galleas into position (and others)

### ISSUE THREAD

**Issue by WardBenjamin** [LoneGazebo/Community-Patch-DLL#7503]
_1. Mod version (i.e Date - 12/1):_ 12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Crash to desktop (but Steam still thinks the game is open?)

_4. Steps to reproduce (optional):_

I've replicated this crash three times with one save after enabling logs. It doesn't seem to be triggered by anything in particular that I'm doing, since I've also made it to the end of the turn once (but crashed on end turn, like in #7502).

1: Moving a galleass next to a city state
2: Alt-tabbing to take a screenshot
3: Pressing M to move the same galleass

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

[Logs_Polynesia.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5984541/Logs_Polynesia.zip)
[Logs_Polynesia2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5984539/Logs_Polynesia2.zip)
[Logs_Polynesia3.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5984540/Logs_Polynesia3.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[Save_Polynesia.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5984543/Save_Polynesia.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[Dump_Polynesia.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5984544/Dump_Polynesia.zip)
[Dump_Polynesia2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5984545/Dump_Polynesia2.zip)
[Dump_Polynesia3.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5984546/Dump_Polynesia3.zip)

4. Screenshots (optional):

![image](https://user-images.githubusercontent.com/4739008/108000764-b538db80-6fb8-11eb-91fd-d5e7f149f040.png)

**Comment by WardBenjamin** [comment]
I had this problem come up with another game today, moving a dromon next to a Danish city that I was at war with.

**Comment by ilteroi** [comment]
three times the same thing ... crashdump seems to point to lua, but hard to tell what's going on

**Comment by azum4roll** [comment]
Didn't we have this before? Game crashed when hovering on a target with a ranged unit active.

**Comment by ilteroi** [comment]
yeah right. so it might be fixed

**Comment by RecursiveVision** [comment]
old version...
