### ISSUE TITLE
Several problems: Ancient ruins not granting rewards, frequent desyncs, and lost Pathfinder

### ISSUE THREAD

**Issue by WardBenjamin** [LoneGazebo/Community-Patch-DLL#7504]
A bunch of issues all in one save here. I'm playing Venice along with a human player playing Austria. We've been experiencing frequent desyncs (one every 2-4 turns, or so), and a few other odd issues. Popping a goody hut with a unit doesn't seem to actually grant the reward. Also, an Austrian pathfinder somehow made it inside the fog of war while auto-exploring, and it wasn't revealing tiles.

_1. Mod version (i.e Date - 12/1):_ 2/4 beta hotfix 5 (multiplayer modpack)

_2. Mod list (if using Vox Populi only, leave blank):_ 

_3. Error description:_ Moving a unit into a goody hut shows a reward message (free tech, advanced weapons, citizen, etc) but the event doesn't actually occur.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

Modpack: https://mega.nz/file/SkxiTaSJ#N8R7po-uVfiscea99ZtrHcFZ2NxbZvsGSYBLK2wAkXU (file too big to upload to Github)

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

[Logs_Venice-MP.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5992733/Logs_Venice-MP.zip)

I'm not sure these logs correspond exactly to the savegame below; they may be from a few turns later.

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[Save_Venice-MP.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5992770/Save_Venice-MP.zip)

In this file, the Austrian pathfinder is lost in the fog of war and the Venetian warrior is one tile away from an ancient ruin

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
yeah, multiplayer is not tested well and a pain to debug

**Comment by WardBenjamin** [comment]
If I can help out with the actual debugging, please let me know. I don't have experience with Civ/VP in particular but I know my way around an IDE.

**Comment by Mileslewis** [comment]
Yea I think a lot of people would appreciate if VP worked better in online. Do we have any idea what sort of things could cause desyncs so we could try to change them where possible?
