### ISSUE TITLE
Autoexplore doesn't account for Polynesia ability prior to discovering Fishing

### ISSUE THREAD

**Issue by dostillevi** [LoneGazebo/Community-Patch-DLL#7505]
_1. Mod version (i.e Date - 12/1):_
12-1-3 with the version of the 2-4 beta (hotfix 5)

_2. Mod list (if using Vox Populi only, leave blank):_
![image](https://user-images.githubusercontent.com/39426657/108152050-031f1380-708d-11eb-9743-705866d10576.png)

_3. Error description:_ 
I started as Polynesia on a relatively small landmass connected to other land by coast. I set my explorer to automate before the initial landmass was discovered, and it proceeded to (correctly) start exploring along the coastline, even though I hadn't discovered embarkment yet. However, after I stopped automatic exploration, I was unable to restart, I think because the automation function was looking at the tiles my civilization would normally be able to reach without embarkment and not finding any remaining to be explored.

I suspect a similar issue will occur if all land reachable by embarkment has been explored, even if automation should be able to send a unit to explore across oceans prior to researching astronomy.

Also, the description on Fishing seems incorrect. Currently, when Fishing is researched, all units regardless of where they are become able to embark. They no longer need to return to owned territory to gain this ability.

_4. Steps to reproduce (optional):_
Start as Polynesia on a smaller landmass connected to other landmasses by coast. Explore the landmass, but don't research fishing. Attempt to automate any unit and note it cannot be automated. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5993030/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[AutoSave_0040 BC-3000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5993035/AutoSave_0040.BC-3000.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![image](https://user-images.githubusercontent.com/39426657/108152135-3cf01a00-708d-11eb-8985-c5265591f70f.png)

![image](https://user-images.githubusercontent.com/39426657/108152770-a1f83f80-708e-11eb-8961-f3670c8c7df2.png)

**Comment by RecursiveVision** [comment]
I fixed the text issue.

**Comment by dostillevi** [comment]
Updating confirming I was able to automate again the turn after I researched Fishing.

**Comment by ilteroi** [comment]
i see the issue ... and the code is disgusting. might need a larger cleanup to do it right.
