### ISSUE TITLE
World Congress votes not tradeable

### ISSUE THREAD

**Issue by WardBenjamin** [LoneGazebo/Community-Patch-DLL#7507]
_1. Mod version (i.e Date - 12/1):_ 2/4 beta hotfix 5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ I am not able to trade World Congress votes with either of the two civilizations where I have diplomats in their capitals (in this case, Babylon and The Netherlands)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

My log files are ~35MB so Github won't let me upload - options?

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[Save_Venice_WorldCongress.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/5999789/Save_Venice_WorldCongress.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![image](https://user-images.githubusercontent.com/4739008/108295459-b9562c00-7165-11eb-89f5-02233bb7a1cd.png)
![image](https://user-images.githubusercontent.com/4739008/108295468-bf4c0d00-7165-11eb-933c-9df1cad7f454.png)
![image](https://user-images.githubusercontent.com/4739008/108295492-c83cde80-7165-11eb-8dde-8c126d8c5ed4.png)

**Comment by Mileslewis** [comment]
Mouse over 'world congress' on the trade screen. I'm guessing it will say they have already traded votes for this session.
Same thing happened to me recently :)

**Comment by WardBenjamin** [comment]
![image](https://user-images.githubusercontent.com/4739008/108396814-47252c00-71e5-11eb-8aa8-540e02e27c2c.png)

Same issue on the World Congress screen.

**Comment by Mileslewis** [comment]
did you try what I said as well?

**Comment by R3P0FFXI** [comment]
The only thing that seems to work for World Congress trading right now if if a civ is a vassal of you

**Comment by Mileslewis** [comment]
Okay I have this issue in my game as well. Also I'm not getting the tourism bonus you are supposed to get from having a diplomat so I think Diplomats just aren't registering properly.

**Comment by RecursiveVision** [comment]
Can't load the save in debug mode...CTD

**Comment by RecursiveVision** [comment]
seems to be fixed
