### ISSUE TITLE
Crash to desktop / save game corruption (latest beta)

### ISSUE THREAD

**Issue by PerfectDark99** [LoneGazebo/Community-Patch-DLL#7508]
1. Mod version: 
2/4

2. Mod list (if using Vox Populi only, leave blank):
More Luxuries, Faster Aircraft Animations, Quick Turns, Really Advanced Setup, Tectonic Map Script, Submarines Ignore Borders
(played with this setup for years, no issues before)

3. Error description: 
Tried loading a saved game from yesterday but upon loading the game crashes. A 5 turn old auto-save I was able to load but after playing couple turns at some point I get an in-game crash. The crash happened when clicking on a Spy notification when my spy has been promoted. I actually saved the game manually before the crash and that save is also corrupted.

4. Steps to reproduce (optional): 

Load the turn 254 save and see that it crashes, then try with turn 250 save, play a couple turns till the spy gets promoted, click on the notification and see what happens (or not click and see if one can recover).

[SaveGames.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6003864/SaveGames.zip)

No dump file is created.

**Comment by Mlac99** [comment]
I have sam issue, too.
[AutoSave_0240 AD-1940.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6005047/AutoSave_0240.AD-1940.zip)

**Comment by RedHotTomato2** [comment]
I am also having crashes for Beta 2/4 Hotfix 5. Cannot reload save as it crashes and closed the program. Around turn 500

[AutoSave_0495 AD-1905.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6008675/AutoSave_0495.AD-1905.zip)

**Comment by RecursiveVision** [comment]
@RedHotTomato2 The game breaks around turn 500 due to a problem with memory.

**Comment by RedHotTomato2** [comment]
> @RedHotTomato2 The game breaks around turn 500 due to a problem with memory. Different issue.

Is there any way to overcome that memory problem?

**Comment by psparky** [comment]
@RecursiveVision: Are you referring to the problem that occurs if you continue a (standard speed) game beyond t500?

If so, I don't think that applies to @RedHotTomato2 crash as the save game date is 1905, so probably an epic speed game. I believe they generally work beyond t500 (and may have a problem beyond t750).

**Comment by RedHotTomato2** [comment]
Yea my game that crashed near t500 is on Epic speed, sorry for not mentioning about it.

**Comment by RecursiveVision** [comment]
@RedHotTomato2 Yes, but I don't know how to do it personally.

Clarification acknowledged, I misunderstood.

**Comment by ilteroi** [comment]
can't load that save (mlac99)

**Comment by Mlac99** [comment]
> 
> 
> can't load that save (mlac99)

Yes that is example of corrupted save game. Can it be useful for debugging?

**Comment by Mlac99** [comment]
This autosave works:
[AutoSave_0316 AD-2036.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6045195/AutoSave_0316.AD-2036.zip)
And I'm didn't change anything except deleting cache.
