### ISSUE TITLE
Phantom civs

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#751]
Rome lost all of its cities and still remained in the game.
![phantom1](https://cloud.githubusercontent.com/assets/12978597/11015724/e4005574-8571-11e5-8c73-d1e82b8246f6.jpg)
![phantom2](https://cloud.githubusercontent.com/assets/12978597/11015725/e5cdf0f0-8571-11e5-821d-6d8933c40bc7.jpg)

InfoAddict here shows that apparently August has some troops left over. However, I didn't enable "Complete kills". He can still interact diplomatically, vote at the WC etc.

**Comment by LoneGazebo** [comment]
Hmm. This was a problem once before, but it hasn't been around. I'll page ilteroi, he worked on this originally.

**Comment by ilteroi** [comment]
oh no, not again!

**Comment by LoneGazebo** [comment]
I can't replicate this, but it may have been an issue with partisans. I think it is fixed now.
