### ISSUE TITLE
2/4 HF5 - City on Lake is Coastal....but not Coastal

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7511]
_1. Mod version (i.e Date - 12/1):_
2/4 HF5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
My capital on the lake is treated as costal for certain things (such as building naval ships). However, it can not build work boats or the Colossus.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/108558636-d141c300-72bf-11eb-9bd7-c814da64e346.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Should be able to build ships and Work Boats, but not the Colossus.

**Comment by Stalker012345** [comment]
I feel pretty confident I have been able to build colossus on a lake city before.

**Comment by RecursiveVision** [comment]
Well, I think the intended behavior is that "coastal" things should not be buildable on lakes but "naval" things should be.

**Comment by ilteroi** [comment]
minwatersize was fixed recently?

**Comment by HungryForFood** [comment]
Yes, then I made coastal buildings buildable at lakes, but coastal wonders unable to do so. Not much reasoning behind it, just the setting I used since there's no agreed correct one.

Forgot about units though, simple enough to set its MinWaterSize to 1.

**Comment by Stalker012345** [comment]
I do think if your going to count lakes part way as "coastal", then you should go all the way with wonders as well.
