### ISSUE TITLE
Proxy peace treaty bug - peace for 10 turn instead of 15 turn as it says, and deducts GPT/resources twice on 10/50th turn.

### ISSUE THREAD

**Issue by racraky** [LoneGazebo/Community-Patch-DLL#7512]
_1. Mod version (i.e Date - 12/1):_ 
Feb.4 beta Hotfix5

_2. Mod list (if using Vox Populi only, leave blank):_
VP + various UI mods in modpack + my local language translation 

_3. Error description:_ 

![20210221102015_1](https://user-images.githubusercontent.com/79009479/108613379-c8bec900-7434-11eb-9fe4-0818302341c9.jpg)
- Brazil requests proxy peace treaty in war between me and Germany and Brazil gives gold, gpt, luxury resources for that peace.
- and that treaty starts on turn 101. It says peace lasts 15 Turns.

![20210221104103_1](https://user-images.githubusercontent.com/79009479/108613447-8a75d980-7435-11eb-9f4b-4284e35c025a.jpg)
- It suddenly cancelled and peace treaty got over on Turn 112 (which is around 10 Turn after that treaty, If it's a normal peace that lasts 10 turn, it is okay. but it doesn't follow the proxy peace treaty I made with Brazil.)

![20210221104115_1](https://user-images.githubusercontent.com/79009479/108613469-b2653d00-7435-11eb-9a4d-608bc3b92df2.jpg)
- and GPT, luxury resources from Brazil got removed.

![20210221111623_1](https://user-images.githubusercontent.com/79009479/108613549-62d34100-7436-11eb-8f48-c9d991a0566b.jpg)
- and after Turn 151, which turn peace treaty ends, things become strange.
- I have to pay him 36 GPT.  other agreement gives me 7 GPT, and It becomes I have to give him 29 GPT, (36-7=29) which seems permanent.

- It seems the bug caused by 'proxy peace' thing doesn't applied properly. It doesn't give peace for 15 Turn, and Ended GPT/resources for 50 Turn on peace treaty ends(which is 10 turn), and It re-applied things on deal end so It makes I have to give him 36 GPT starting on end of deal.

so It seems It ends the treaty twice (on 10th turn for peace ends, and 50th turn for agreement ends) and it deduct the trade things twice.

_4. Steps to reproduce (optional):_
go war and get GPT/resources from another faction by proxy peace for war target.
and see the GPT ends on 10th turn(not 15th turn as it says)
and also checks reverting GPT into them after 50th turn, when agreement ends.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6017088/Logs.zip)
I used my localization, not en_us. so there could be non-English words.
and I loaded on Turn 110, and 151 to check the peace treaty end / and treaty end.

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

My modpack (includes localization mod which disabled on en_us setting, various ui mods) : https://drive.google.com/file/d/1LNLASJsPzRQsPa_AEfG0XNX4IN_-07_a/view?usp=sharing

savefile
Turn 112 (which peace ends on next turn)
[Attila_0112 BC-0075.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6017102/Attila_0112.BC-0075.zip)

Turn 152 (which agreement ends on next turn)
[Attila_0152 AD-0840.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6017107/Attila_0152.AD-0840.zip)

**Comment by RecursiveVision** [comment]
Your UI is bugged.

**Comment by racraky** [comment]
yes, it is caused by 'Trade Opportunities for VP' (https://forums.civfanatics.com/threads/trade-opportunities-for-vp.636230/) mod. but it is purely UI mod, so doesn't break in-game thing like this bug.

**Comment by ryanmusante** [comment]
@racraky can you post that in the trade opportunities forum?

**Comment by racraky** [comment]
@ryanmusante found the github for that mod, so I posted a issue there.
