### ISSUE TITLE
incorrect notification

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7513]
![image](https://user-images.githubusercontent.com/1358966/108623548-de85bb80-743f-11eb-95e2-b02cbe6d667d.png)

there are two issues here:

* "war changes hands", what's that supposed to mean?
* harald obviously did not liberate the city

**Comment by HungryForFood** [comment]
I thought this text is from a mod that lets you liberate city states when conquering them? World Congress Reformation if I'm not mistaken.

**Comment by ilteroi** [comment]
now that you mention it i did get an event popup when i conquered the city even though events are disabled. and i might have that mod active inadvertently. but what is the connection to the world congress? weird.

**Comment by HungryForFood** [comment]
Probably because the mod gives you an option to set a sphere of influence when liberating city states.

The notification is supposed to be one of the options, where you just liberate normally.
