### ISSUE TITLE
Modder Feedback - Is this "fast city heal with no enemies around" check a large performance impact?

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7515]
An idea we had debated on the main forum, and the question came up on how much performance impact it would have. So before we debate it further, I wanted to get your alls thoughts on it.

The idea is this. Currently we believe there is some check the system already uses to confirm if an enemy unit is within firing range of each city, and likely this is some loop that goes city to city.

So could we piggy back on that loop, and put in code that (if the arsenal has been built) and there are no enemies units within firing range (aka 3) to increase the city's healing rate by X amount for the turn.

Is that something that would take a minimum of processing time (since the loop happens anyway), or would that add a new performance bottleneck?

**Comment by RecursiveVision** [comment]
@ilteroi

**Comment by ilteroi** [comment]
should be possible w/o too much impact. i'll check

**Comment by azum4roll** [comment]
> if the owner is at peace the heal rate is tripled

Yeah this seems not to be working well with city states, seeing as they're almost always at war with someone.

**Comment by pineappledan** [comment]
If it was attached to a building, and therefore had to perform that check, Would it be a lot more work to make it an integer value for additional healing per turn, rather than a boolean value for triple healing?

**Comment by ilteroi** [comment]
not sure i understand, but the heal rate is computed once per turn per city, so little impact.
