### ISSUE TITLE
2/4 HF5 - All coup chances are 0%

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7516]
_1. Mod version (i.e Date - 12/1):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Regardless of my current influence, it is always showing me 0% for coup chances.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/108638191-953f6700-7453-11eb-8ff2-6332957ee045.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
side effect from a failsafe i put in to fix a crash ...

@RecursiveVision : did you fix that out-of-bounds issue with espionage for minors?

**Comment by RecursiveVision** [comment]
@ilteroi I believe so, I added a check so only majors had that called for them.
