### ISSUE TITLE
gandhi is a warmonger now?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7517]
![image](https://user-images.githubusercontent.com/1358966/108736454-ed4c9b00-7531-11eb-868a-445490fa53ab.png)

```
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Casus Belli,,478
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,International Monetary Fund,,314
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,The Cultural Revolution,,314
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Mombasa,292
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Treasure Fleet,,251
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Almaty,232
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Zanzibar,232
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Ormus,232
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,World Science Initiative,,190
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,Byzantium,167
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,City-State Sanctions,,122
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,Arabia,79
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,The Aztecs,79
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Natural Heritage Sites,,67
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Choose Host,,0
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,France,-11
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Melbourne,-37
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Hong Kong,-39
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Endowment for the Arts,,-123
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,World Religion,[ICON_RELIGION_ISLAM] Islam,-163
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,World Religion,[ICON_RELIGION_CHRISTIANITY] Catholicism,-200
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,World Religion,[ICON_RELIGION_ORTHODOX] Eastern Orthodoxy,-200
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,World Religion,[ICON_RELIGION_BUDDHISM] Buddhism,-200
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Scholars In Residence,,-224
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,Rome,-230
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Prague,-302
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Sanction,Denmark,-324
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Sofia,-439
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Kiev,-647
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Samarkand,-1082
248, 1690,India,- - -,Evaluating for Proposal, ENACT, POST SORT,Open Door,Buenos Aires,-1325
248, 1690,India,- - -,Evaluating for Proposal, REPEAL, POST SORT,Sphere of Influence,,-4939
```

then they did not care all that much and instead like everybody else put all their votes into preventing a sanction, which was proposed by byzantium (but they did not vote on it at all).

![image](https://user-images.githubusercontent.com/1358966/108737921-5b459200-7533-11eb-8e24-2628ef40afa1.png)

but i'm not sure how that matches their preferences ... also funny that denmark is *against* the casus belli!

261, 1755,Persia,- - -,Evaluating for Delegates,ENACT: Cultural Heritage Sites,Nay,221
261, 1755,Persia,- - -,Evaluating for Delegates,ENACT: Sanction: Persia,Nay,1012
261, 1755,Persia,- - -,Evaluating for Delegates,ENACT: Casus Belli,Yea,348
261, 1755,Persia,- - -,Committing Delegates,ENACT: Sanction: Persia,Nay,6
261, 1755,Rome,- - -,Evaluating for Delegates,ENACT: Cultural Heritage Sites,Nay,140
261, 1755,Rome,- - -,Evaluating for Delegates,ENACT: Sanction: Persia,Nay,560
261, 1755,Rome,- - -,Evaluating for Delegates,ENACT: Casus Belli,Yea,406
261, 1755,Rome,- - -,Committing Delegates,ENACT: Sanction: Persia,Nay,2
261, 1755,Rome,- - -,Committing Delegates,ENACT: Casus Belli,Yea,1
261, 1755,The Aztecs,- - -,Evaluating for Delegates,ENACT: Cultural Heritage Sites,Nay,104
261, 1755,The Aztecs,- - -,Evaluating for Delegates,ENACT: Sanction: Persia,Nay,268
261, 1755,The Aztecs,- - -,Evaluating for Delegates,ENACT: Casus Belli,Yea,82
261, 1755,The Aztecs,- - -,Committing Delegates,ENACT: Sanction: Persia,Nay,5
261, 1755,The Aztecs,- - -,Committing Delegates,ENACT: Cultural Heritage Sites,Nay,1
261, 1755,Byzantium,- - -,Evaluating for Delegates,ENACT: Cultural Heritage Sites,Nay,99
261, 1755,Byzantium,- - -,Evaluating for Delegates,ENACT: Sanction: Persia,Yea,1082
261, 1755,Byzantium,- - -,Evaluating for Delegates,ENACT: Casus Belli,Nay,362
261, 1755,Byzantium,- - -,Committing Delegates,ENACT: Casus Belli,Nay,4
261, 1755,Byzantium,- - -,Committing Delegates,ENACT: Cultural Heritage Sites,Nay,1
261, 1755,India,- - -,Evaluating for Delegates,ENACT: Cultural Heritage Sites,Nay,206
261, 1755,India,- - -,Evaluating for Delegates,ENACT: Sanction: Persia,Nay,653
261, 1755,India,- - -,Evaluating for Delegates,ENACT: Casus Belli,Yea,334
261, 1755,India,- - -,Committing Delegates,ENACT: Sanction: Persia,Nay,19
261, 1755,Denmark,- - -,Evaluating for Delegates,ENACT: Cultural Heritage Sites,Nay,97
261, 1755,Denmark,- - -,Evaluating for Delegates,ENACT: Sanction: Persia,Nay,661
261, 1755,Denmark,- - -,Evaluating for Delegates,ENACT: Casus Belli,Nay,232
261, 1755,Denmark,- - -,Committing Delegates,ENACT: Sanction: Persia,Nay,4
261, 1755,France,- - -,Evaluating for Delegates,ENACT: Cultural Heritage Sites,Nay,162
261, 1755,France,- - -,Evaluating for Delegates,ENACT: Sanction: Persia,Nay,116
261, 1755,France,- - -,Evaluating for Delegates,ENACT: Casus Belli,Nay,202
261, 1755,France,- - -,Committing Delegates,ENACT: Sanction: Persia,Nay,1
261, 1755,Congress,- - -,Proposal Passed,ENACT: Cultural Heritage Sites,Yea,Won by 2
261, 1755,Congress,- - -,Proposal Failed,ENACT: Sanction: Persia,Nay,Won by 37
261, 1755,Congress,- - -,Proposal Failed,ENACT: Casus Belli,Nay,Won by 7

**Comment by RecursiveVision** [comment]
@ilteroi 
![b3c](https://user-images.githubusercontent.com/66801010/108809987-0f690c00-7578-11eb-9637-0cca06e42659.jpg)

**Comment by RecursiveVision** [comment]
yeah i'll look at it...may be due to the diplo flavors rework, but the logic seems wonky in general if Denmark is against it

**Comment by Stalker012345** [comment]
I'll pile on on this one. Ghandi is going to war, and asking me to join him in war, very often.

**Comment by ilteroi** [comment]
more oddities ... this is after i proposed montezuma as host of the world congress:

![image](https://user-images.githubusercontent.com/1358966/108911685-dee0ab00-7627-11eb-967b-ea4566fc9f0c.png)

on the other hand byzantium congratulated me for my choice ... but the log says the opposite.

284, 1828,The Aztecs,- - -,Evaluating for Delegates,ENACT: Choose Host,The Aztecs,50
284, 1828,The Aztecs,- - -,Committing Delegates,ENACT: Choose Host,The Aztecs,7
284, 1828,Byzantium,- - -,Evaluating for Delegates,ENACT: Choose Host,Arabia,50
284, 1828,Byzantium,- - -,Committing Delegates,ENACT: Choose Host,Arabia,2

**Comment by RecursiveVision** [comment]
@ilteroi The Choose Host resolution is a modmod, it's not integrated into the DLL when used like that.

**Comment by RecursiveVision** [comment]
Lowered Gandhi's war fervor, upped some friendliness values, changed the logic. Should be better.
