### ISSUE TITLE
traderoute over ice?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#752]
see here:

![image](https://cloud.githubusercontent.com/assets/1358966/11017399/07626cc4-859e-11e5-8d58-24ae0f13daa8.png)

1. kukia was founded solely for the iron (nice move!)
2. it is connected to the trade network, even though it is ice-bound. is this intended?
3. the iron it provides doesn't seem to count, why?

**Comment by Radost** [comment]
3. I don't see the mine on it, if you are talking about the deposit on the east.

**Comment by ilteroi** [comment]
oops. good point. the tile was producing 3 hammers, so i just assumed the mine is there.

**Comment by LoneGazebo** [comment]
Looks fine to me, I guess. I'unno.

**Comment by ilteroi** [comment]
so it's a failure to build a mine ... songhai seems to have a lack of workers in general.
