### ISSUE TITLE
Crash past turn 500 issues

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7524]
@LoneGazebo So based on what you said and looking at an ancient commit, it looks like the value that's breaking the game is...

```
		m_ppiInstantYieldHistoryValues.clear();
		m_ppiInstantYieldHistoryValues.resize(GC.getGame().getEstimateEndTurn());
		for (unsigned int i = 0; i < m_ppiInstantYieldHistoryValues.size(); ++i)
		{
			m_ppiInstantYieldHistoryValues[i] = yield;
		}
```

Just raising the size should fix it, looking at the code. But is there really a need to store 500 turns * every yield in memory for every player?

**Comment by MilkyP** [comment]
Are there any updates on what is causing this issue or how near we are to a fix? Occurs now on every game I play once I reach turn 500.

**Comment by ilteroi** [comment]
thanks for the reminder ... i guess :)
