### ISSUE TITLE
AI trades cities too easily

### ISSUE THREAD

**Issue by Circine** [LoneGazebo/Community-Patch-DLL#7526]
_1. Mod version (i.e Date - 12/1):_ 2-4 Hotfix 5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Friendly and neutral AIs will trade almost all their cities away for pocket change. I was able to get Boudicca here to give up all but her second city(which she refused to sell at all) for half my GPT. Rinse and repeat for every AI that didn't already hate me.
I also noticed they seem to value territory close to yours more highly in trade deals. I'm guessing that's because you ought to value it more too, but it leads to them being more willing to grant you cities in their heartlands than on your frontier, which is unrealistic and only weakens that AI in the long run.

---------------------------
Supporting information:
4. Screenshots (optional):
![20210226182857_1](https://user-images.githubusercontent.com/39605664/109373494-f5734600-7863-11eb-979f-e18631156240.jpg)

**Comment by RecursiveVision** [comment]
ilteroi tried to fix this by making it so they'd only trade a city for a city, but it looks like that didn't work. It's been an issue for a while.

**Comment by RecursiveVision** [comment]
In particular outside of a peace deal, AI shouldn't be willing to trade away more than one of their cities...

**Comment by ilteroi** [comment]
indeed something is broken, will check

**Comment by RecursiveVision** [comment]
There have also been reports on the forums of insane prices for third party war deals.
![upload_2021-1-19_12-11-29](https://user-images.githubusercontent.com/66801010/109383100-33975680-78b2-11eb-94f5-813f9bb85b53.png)
![upload_2021-1-30_23-57-7](https://user-images.githubusercontent.com/66801010/109383102-37c37400-78b2-11eb-8c34-9259693544a8.png)

**Comment by ilteroi** [comment]
never touched that but let me correct my earlier statement: just about everything in the deal AI is broken

**Comment by RecursiveVision** [comment]
G cleaned it up a lot from what it was, but it's...eh. It'd require a complete rewrite to fix the root problems with it.

**Comment by LoneGazebo** [comment]
It's probably just an extra multiplier somewhere in that third party code.

**Comment by Circine** [comment]
AI doesn't consider defensive pacts when trading third party war either. Gandhi and Theo had one, but I could double dip and get twice as much by including both in the same deal.

**Comment by ilteroi** [comment]
should be better now. AI won't buy or sell non-border cities. third party war mostly rewritten, but no idea how solve the double dipping issue without much more extensive changes.

**Comment by RecursiveVision** [comment]
@ilteroi Check out CvDiplomacyAI::GetLinkedWarPlayers(), I likewise got annoyed at this kind of issue cropping up a lot.

**Comment by RecursiveVision** [comment]
Think I found a temporary fix, will just add a check to IsPossibleToTradeItem...

**Comment by RecursiveVision** [comment]
ugh, never mind, this code is disgusting...will have to wait

**Comment by ilteroi** [comment]
@LoneGazebo : nope, probably that was math done to an INT_MAX value
@RecursiveVision : can you check the third party war code again? (latest commit) it's using some values from diplo AI and i'm not quite clear on whether they are valid for human players, eg IsPotentialWarTarget() seems to be false, but on the other hand i'm not even sure it's needed since we also check HavePreferredAttackTarget()

**Comment by RecursiveVision** [comment]
@ilteroi Sure, I'll look at the code and fix anything that doesn't look right.

IsPotentialWarTarget() is an AI flag to determine whether the AI might be bribed into war against this player (or might enter war for a few other reasons). Whenever a new war is declared this flag is reset globally so they have a turn to reassess the world situation before being bribed into anything.

IsWarSane() returns if the AI considers the war "sane" from a diplomatic and financial perspective (not counting military strength, but checks things like if it would backstab, or if it would bankrupt the AI).

And you know what HavePreferredAttackTarget() does, obviously :)

**Comment by RecursiveVision** [comment]
@ilteroi done :)

https://github.com/LoneGazebo/Community-Patch-DLL/pull/7531/commits/2bc1ce97e91f3deca5d2c96410adbd84bd2267ac
