### ISSUE TITLE
2/4 HF5 Venice can found more than 3 colonia

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#7527]
Title says it all, I can found the colonia of Candia as my 4th self founded puppet, when I should be restricted to a max of 3

**Comment by ilteroi** [comment]
says who?

**Comment by RecursiveVision** [comment]
@ilteroi That was the original limit when this feature was introduced.

**Comment by randomnublet** [comment]
Has it been removed in a patch note I missed?

**Comment by RecursiveVision** [comment]
Not to my knowledge.

**Comment by RecursiveVision** [comment]
Can confirm they can build more than 3, though.

**Comment by ilteroi** [comment]
let me put it another way. it has been like this for quite a while and where is the problem?

**Comment by RecursiveVision** [comment]
I don't have a problem with it, but it was G's idea.

**Comment by randomnublet** [comment]
Not a balance issue either if you ask me, but if you keep it this way the MoV description has to be changed:

![max3civ](https://user-images.githubusercontent.com/53142313/109414726-ad176d80-79b4-11eb-9246-f4dabb3c4578.png)

**Comment by LoneGazebo** [comment]
Since this is a balance discussion, we need to bring it up with the Vox Populi first.

**Comment by pineappledan** [comment]
I like that the limit was dropped. I think the text should just be changed to fit

**Comment by pineappledan** [comment]
Until a final decision is made, the text is wrong. I have removed mention of the 3 colonia for now. 
https://github.com/LoneGazebo/Community-Patch-DLL/commit/cb0aab7602966089571dc3d8e399d578a3074ae9

**Comment by ilteroi** [comment]
yeah. arbitrary limit with little impact on gameplay, who has so many merchants anyway

**Comment by RecursiveVision** [comment]
I have to agree this could probably be dropped with little consequence.
