### ISSUE TITLE
AI offers Peace Deal yet it is marked Impossible

### ISSUE THREAD

**Issue by Omen-of-Peace** [LoneGazebo/Community-Patch-DLL#7528]
_1. Mod version (i.e Date - 12/1):_ 2/4

_2. Mod list (if using Vox Populi only, leave blank):_ only VP and UI mods

_3. Error description:_ The Zulu offer a peace deal (including two of their cities) voluntarily on their turn (or it can be seen on the player's turn in the trade screen, by clicking 'what would make this deal work?'), but it is marked as "Impossible!"

_4. Steps to reproduce (optional):_ see attached save
[Maria Theresa_0258 AD-1976.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6055084/Maria.Theresa_0258.AD-1976.zip)

Let me know if a log could be useful.

**Comment by RecursiveVision** [comment]
@Omen-of-Peace Are you using the latest hotfix? I fixed a bug relating to this.

**Comment by Omen-of-Peace** [comment]
I'm on hotfix 5 (assuming I didn't mess it up :)), which does appear to be the latest.

It's the first time I run into it in several games.

**Comment by RecursiveVision** [comment]
I'll see what's up. :)

**Comment by RecursiveVision** [comment]
@Omen-of-Peace Can't load the save...

**Comment by DeagaDH** [comment]
I've gotten the same bug on my game, also running the lastest beta. I'm also running the Promotion Flags for VP and  More Unique Components for VP mods.

In my case, this does not affect all peace deal offers from the AI, as I've gone to war and back to peace multiple times within the same game. However, the Shoshone are now attempting to give me a city in the Peace Deal, which flags it as Impossible!" and thus make it, well, impossible to accept. It's impossible to take the deal even if I propose it on my turn asking for just peace and nothing else, as the deal is valued as "Impossible!" by the AI regardless of what's offered.

I've also attached my save file, hope this one helps.
[Bugged_NoPeaceDeal.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6070158/Bugged_NoPeaceDeal.zip)

**Comment by RecursiveVision** [comment]
Might be fixed by ilteroi's changes...

**Comment by ilteroi** [comment]
![image](https://user-images.githubusercontent.com/1358966/109719932-abfb6180-7ba9-11eb-85c0-fe095cd6cb0d.png)

**Comment by RecursiveVision** [comment]
@ilteroi I fixed that in one of the hotfixes...

**Comment by RecursiveVision** [comment]
Anyway there's a new version so you might as well merge from master so there's no more divergent changes :)

**Comment by ilteroi** [comment]
bad timing, i've just fixed a few annoying little bugs. but i guess there will be hotfix :)

**Comment by RecursiveVision** [comment]
@ilteroi ok I merged your changes manually into rsi. If you rebase/create a new branch based on rsi all your stuff and all the other new version stuff should be there, with no divergent changes.

**Comment by ilteroi** [comment]
yeah yeah yeah, just one more commit and then i give up my test game :)

**Comment by RecursiveVision** [comment]
@ilteroi ok, merged :)
