### ISSUE TITLE
I had a ctd in classical era, just after the CS turns, before i saw the barbarian turn popup 

### ISSUE THREAD

**Issue by teeinkay** [LoneGazebo/Community-Patch-DLL#753]
first ctd ive had in a long time, since i upgraded to 4bgram i think

So I read to include the civvminidmp file, idk what logs.. and the dmp file isnt supported to drag and drop.. im gonna just make a rar of my logs folder and that minidmp file and hold it.. plx let me know what i need to do to be helpful

**Comment by LoneGazebo** [comment]
If you can upload it and link me to it, that'd be great.

**Comment by teeinkay** [comment]
https://www.dropbox.com/s/837y9firecp1w12/Logs%20crash%20330pm%20askia%20mods%20game.rar?dl=0  

Here you go, for some reason my autosves interval and max autosaves was set to 0, idk y i did that and do not remember having done so. I included the whole logs folder, the civvminidump, a pic of my modsfolder list.. but i think thats in the logs

**Comment by teeinkay** [comment]
Thx i did reply to u at githuiub with the dropbox link
 


     On Sunday, November 8, 2015 6:33 PM, LoneGazebo <notifications@github.com> wrote:
   

 If you can upload it and link me to it, that'd be great.—

**Comment by teeinkay** [comment]
I did not know how it works, sorry for double and now triple reply, next time ill know better

**Comment by LoneGazebo** [comment]
In the future, turn of builder logging, it'll eat up tons of space (gigs and gigs of space).

G

**Comment by teeinkay** [comment]
; Enable Builder AI logging
BuilderAILog = 1  

to ; Enable Builder AI logging
BuilderAILog = 0 

?
 


     On Sunday, November 8, 2015 8:30 PM, LoneGazebo <notifications@github.com> wrote:
   

 In the future, turn of builder logging, it'll eat up tons of space (gigs and gigs of space).G—

**Comment by LoneGazebo** [comment]
Yes, otherwise it will output way too much useless data.

Your CTD minidump traced out to the disassembly, which is hard to catch. I'll keep an eye on the issue.
G

**Comment by teeinkay** [comment]
Gool, thanks LordG, I changed my logging options. If i have further problems I will be sure to communicate them with you, now that i know how
 


     On Sunday, November 8, 2015 11:28 PM, LoneGazebo <notifications@github.com> wrote:
   

 Yes, otherwise it will output way too much useless data.Your CTD minidump traced out to the disassembly, which is hard to catch. I'll keep an eye on the issue.
G—

**Comment by LoneGazebo** [comment]
Will continue to try to reproduce. Closing until I can find an answer.

**Comment by teeinkay** [comment]
so, different game, medieval era and again a ctd from nowhere.. idk why.. after end turn before my next turn..

**Comment by teeinkay** [comment]
am i doing somethign wrong?  clear my cache any time i have a change in files

https://www.dropbox.com/s/2igjexpnkd46b3i/Logs%20anddmp%20from%20crash%20at847%2011112015.rar?dl=0

**Comment by teeinkay** [comment]
i dont see other complaing of ctd every single game so i feel like i must be screwing up

**Comment by LoneGazebo** [comment]
I checked your database log, and you've got broken files. Your MODS folder only has the CP/CBP/CSD/C4DF and EUI compatibiltiy files in it, correct?

G

**Comment by teeinkay** [comment]
I have some of enginseers file,I'll reinstall the cpp/cbp file and try to run them alone this afternoon. I like eggy's work but if it is breaking the game for me ill skip it, cbp is what i really am trying to use. thanks for help and support LordG
 


     On Wednesday, November 11, 2015 10:21 PM, LoneGazebo <notifications@github.com> wrote:
   

 I checked your database log, and you've got broken files. Your MODS folder only has the CP/CBP/CSD/C4DF and EUI compatibiltiy files in it, correct?G—
