### ISSUE TITLE
MOD_GLOBAL_TRULY_FREE_GP

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7532]
Going to continue with my gradual cleanup of unnecessary defines/settings...

@LoneGazebo For this one, would it be fair to count this as a bugfix? There are 225 places in the code where it's used, and it seems unnecessary to me, so a potential cleanup opportunity. But I hesitated to remove it earlier as it does affect balance, bugfix though it may be, and is only enabled in the CBP.

If not, maybe there's a way of optimizing the function calls...

**Comment by RecursiveVision** [comment]
EDIT: Same thing for GLOBAL_SEPARATE_GP_COUNTERS...

**Comment by RecursiveVision** [comment]
@LoneGazebo Think you missed the notification? :)

**Comment by LoneGazebo** [comment]
Yeah, I did. Since this is a balance issue, I think we leave it as-is for CP/CBO flexibility.

**Comment by RecursiveVision** [comment]
Alright.
