### ISSUE TITLE
Tech Tree Broken

### ISSUE THREAD

**Issue by BenYeshu** [LoneGazebo/Community-Patch-DLL#7533]
_1. Mod version (i.e Date - 12/1):12/1/3_

_2. Mod list (if using Vox Populi only, leave blank): 
MC's Gallic Civilization (v.1)
FIFA World Cup Host Resolution (v.1)
JFD's Rise to Power - (3) (Gameplay) Epithets (v.3)
JFD's The Anglo-Saxons (v.1)
Resolution - Cultural Exchange Program (v.1)
Ingame Editor (v.39)
Cultural Diffusion (v.18)
Global Warming Congress (v.2)
Economics (v.4)
Submarines Ignore Borders (v.3)
 (BNW) Leugi's Israel Civilization (v.7)
Gedemon's YnAEMP (v.25)
JFD's Civilizations - Punjab (Ranjit Singh) (v.1)
Smaller Units Graphics (v.1)
DMS' Civilizations - Dacians (Burebista) (v.6)
JFD's Rise to Power - (3) (Gameplay) Ideological Values (v.2)
Tactical Nuclear Missile (v.2)
Reforestation (v.9)
Provincial Palace (v.3)
Fallout Damage (v.1)
Contextual Unit Names (v.3)
Resolution - Intelligence Networking (v.1)
Historical Religions Complete (BNW or GK) (v.45)
The Kazakhs (BNW) (v.2)
(6c) 43 Civs CP (v.1)
Resolution - Secure Industry Initiative (v.1)
Emigration (v.6)
Kongo (Brave New World) (v.48)
Special Forces Mod (v.4)
JFD's Rise to Power - (3) (Gameplay) Dark Ages (v.1)
The Hittites (Brave New World) (v.76)
JFD's Civilizations - Great Jin (Shizong) (v.2)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6072971/Lua.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6072975/xml.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6072978/Database.log)
JFD's Rise to Power - (3) (Gameplay) Spirit Ideology (v.2)
JFD's Rise to Power - (4) (Content) Neutrality Ideology (v.1)
(6b) Community Balance Overhaul - Compatibility Files (No-EUI) (v.1)
(2) Community Balance Overhaul (v.13)
Bridges and Canals (v.2)
R.E.D. Modpack (v.27)
UN Security Council Resolution (v.2)
JFD's Rise to Power - (2) (UI) Social Policy Screen (v.4)
Slave Trade (v.3)
(JEM) Nuclear Missle Range Extension (v.2)
Uighur_Caesar's Kaweskar (v.1)
JFD's Rise to Power - (1) (Core) Utilities (v.6)
Medieval Espionage (v.1)
Custom Advanced Setup Screen (v.5)
JFD's Rise to Power - (2) (UI) Info Panel (v.1)
Resolution - Aeronautical Engineering Cooperation (v.1)
JFD's Civilizations - Yakuts (Tygyn Darkhan) (v.1)
Kilwa Sultanate (v.4)
Move Capital (v.10)
Civ Names by Policies (v.8)
JFD's Civilizations - Rome (Caracalla) (v.1)
Resolution - Geneva Convention (v.1)
JFD's Civilizations - Norway (Haakon IV) (v.9)
(4) C4DF - CBP (v.11)
TarcisioCM - The Iberians (v.2)
Revolutions (v.9)
Helicopters Can Fly Over Water (v.3)
(1) Community Patch (v.94)
Faster Plot Expansion (v.1)
Resolution - Global Labor Standards (v.1)
JFD's Rise to Power - (3) (Gameplay) Sovereignty (v.9)
 Global Warming (v.7)
Resolution - Interfaith Exchange (v.1)
The Vainakhs (v.1)
JFD's The Merchant Republic of Novgorod (v.2)
Nuclear Superiority (v.3)
Resolution - Naval Games (v.1)
Resolution - International Monetary Fund (v.1)
The Kuikuro (Brave New World) (v.26)
 Health & Plague for BNW (v.19)
Less Warmonger Hate (v.10)
JFD's The Germans (v.2)
JFD's Rise to Power - (3) (Gameplay) Cycles of Power (v.3)
Scouts ignore Borders (v.2)

_3. Error description: Tech tree is broken and I'm unable to slide to the right

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
I don't think I've ever seen a larger mod list. Think you might be on your own here.

**Comment by RecursiveVision** [comment]
oh, it's an old version too. Welp.

**Comment by RecursiveVision** [comment]
The following lines may be of interest for debugging it, though:
```
[783642.875] Runtime Error: C:\Users\RIzza\OneDrive\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files\CoreLua\InGame.lua:1262: attempt to index local 'addinFile' (a nil value)
[783642.875] Runtime Error: Error loading C:\Users\RIzza\OneDrive\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files\CoreLua\InGame.lua.
[787494.171] Runtime Error: C:\Users\RIzza\OneDrive\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files\Core Values\TechHelpInclude.lua:480: attempt to index field '?' (a nil value)
```

**Comment by LoneGazebo** [comment]
I bet that issue is related to a tech database error. What’s the database.log look like?

**Comment by RecursiveVision** [comment]
Full of errors...highly probable mod conflict

**Comment by LoneGazebo** [comment]
Yeah, if there's a bad tech error then it'll break the tech tree. My advice @BenYeshu is to go through your list, remove all but CP, start up. If it looks good, add in a few mods at a time until figure out which are incompatible with the others. It's a pain, but that's what it takes.

**Comment by BenYeshu** [comment]
@LoneGazebo @RecursiveVision Yeah, I figured I used too many mods. Like you said I'll through and figure it out one by one. Thanks guys for taking a look at this for me
