### ISSUE TITLE
Bad World Congress Voting AI

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7535]
Currently most World Congress votes are very random and also AIs will change their mind about their preferences each time you open up the congress menu or the deal screen to trade votes.

Had some look through the code for voting logic and tbh I would like to just go through the CvLeagueAI::ScoreVoteChoiceYesNo function and give it some love by:

- Removing the large random aspect at the end of it
- Removing/editing some of the places inside and outside the function where scores get messed with unnecessarily
- Updating the scores for each proposal to better reflect their actual worth to a civ
- Then finally including more consideration of a civ's diplomacy now that recursive has updated that

@LoneGazebo Let me know if you're happy with these changes and I can make them in next few weeks.

**Comment by LoneGazebo** [comment]
I'm good with that, yep. The whole thing is cobbled together with bandaids.
