### ISSUE TITLE
3/2 - Vassal Negotiation gives benefit to defensive pact

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7536]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I am in a vassal negotiation with Arabia. Putting forward a defensive pact offer gives me diplomatic points....even though they will automatically get the defensive pact as a part of the vassal agreement.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/109999898-55d90c00-7cd8-11eb-9e2f-d28b6c02c21f.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by anders4** [comment]
I noticed the issues with instant peace vassal at chivalry went away when disabling defensive pacts.
