### ISSUE TITLE
too many melee units

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7539]
it seems the AI players tend to build too many melee units?

not sure if there was a change or if they simply don't lose as many fighting but for my taste at least there are not enough ranged units in the mix.

![image](https://user-images.githubusercontent.com/1358966/110161159-47c8df80-7ded-11eb-9114-c93e456214cc.png)

![image](https://user-images.githubusercontent.com/1358966/110161124-37186980-7ded-11eb-8994-a863ca726eb5.png)

![image](https://user-images.githubusercontent.com/1358966/110161415-9aa29700-7ded-11eb-8679-253474fda780.png)

not cherrypicking here, all same game, same turn

**Comment by LoneGazebo** [comment]
looks to be related to fusilier - is that unit way over-valued in the unitproductionAI?

**Comment by ilteroi** [comment]
some log analysis. indeed seems to vary by era?

unit | count
-- | --
Camel Archer | 86
Caravel | 102
Crossbowman | 80
Explorer | 6
Galleass | 107
Heavy Skirmisher | 73
Knight | 97
Longswordsman | 58
Pikeman | 71
Trebuchet | 24

unit | count
-- | --
Cannon | 61
Carolean | 79
Corvette | 82
Cuirassier | 32
Frigate | 73
Hussar | 45
Lancer | 283
Musketeer | 146
Musketman | 40
Sea Beggar | 36
Ship of the Line | 16
Tercio | 138

unit | count
-- | --
Berber Cavalry | 11
Cavalry | 3
Cruiser | 22
Field Gun | 30
Fusilier | 186
Gatling Gun | 24
Ironclad | 92
Mehal Sefari | 11


lancer and fusilier are way overrepresented

**Comment by LoneGazebo** [comment]
Hmm, I wonder why.  What does the actual production value in the log look like?

**Comment by Stalker012345** [comment]
I'll note that I am seeing similar behavior.

I think its especially notable once g guns come out. Fusiliers are a great unit when they first come out, but once g guns are on the field, its much better to mass a lot of them with the occasional fusiliers to push lines and plug key chokepoints.

**Comment by ilteroi** [comment]
did some more analysis in another game, overall 62% of all military unit's built were melee units. while that doesn't sound too lopsided overall, AI really loves fusiliers, lancers, ironclads.

**Comment by Stalker012345** [comment]
Something else I am seeing in game that may show up in those metrics. The AI is building very very few AA guns, like 1-2 at most. This may be due to the CS nerf, but they don't have triplanes either, so my airforce is running ramshot through them.

**Comment by Stalker012345** [comment]
> did some more analysis in another game, overall 62% of all military unit's built were melee units. while that doesn't sound too lopsided overall, AI really loves fusiliers, lancers, ironclads.

The ironclads could make sense as a simple lack of iron. The AI builds huge navies but is still iron limited on cruisers, hence the skew.

In my last game I also am seeing a LOT of paratroopers. At first I thought it was just Brazil (aka Banderitas upgraded), but then I took on the Mayan who had a lot of them as well.
