### ISSUE TITLE
3/2 - AI overly sensitive to late game settlements

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7542]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I settled this city in a very remote area. While I can respect Persia being upset, every other civ except Arabia gave me a warning about settling too close. This looks to be too sensitive.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/110184682-1d1f5c80-7dd6-11eb-87f0-1f4c3a53546b.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@ilteroi You changed this last

**Comment by ilteroi** [comment]
well if there is only one spot left, which is targeted by everybody, then this could happen.

but only if all the other players are running the "expansion" strategy. which is unexpected in the lategame.

conditions are iFlavorGrowth<iFlavorExpansion or naval map or offshore expansion map. the last two are map generator flags, no idea how they are used.

anyway i added a distance check based on player boldness.

**Comment by azum4roll** [comment]
Communitu_79a is an offshore expansion map if Terra mode and naval if not.

**Comment by ilteroi** [comment]
well i don't even know if we still need those hints but should be ok now anyway
