### ISSUE TITLE
3/2 - Not receiving units from military city-states

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7544]
_1. Mod version (i.e Date - 12/1):_ 3/2

_2. Mod list (if using Vox Populi only, leave blank):_ 
Better lakes v2.2
Improved city view v11
Promotion flags v3

_3. Error description:_ 
I have been allied with a military CS for at least 50 turns, and friends/allies with another one during that time, but have not received any gifted units. 

Is there a log that has the info on unit gifts?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6095888/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu): 

[William_0177 AD-1170.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6095887/William_0177.AD-1170.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@silentreply Need a save file

**Comment by silentreply** [comment]
@RecursiveVision Save and logs are now attached!

**Comment by RecursiveVision** [comment]
I'll see if I can figure this out then. :)

**Comment by RecursiveVision** [comment]
Found one bug...multiple initialization of the same variable by mistake. Let's see if that fixes it...

**Comment by RecursiveVision** [comment]
yeah, looks like it's fixed
