### ISSUE TITLE
Suboptimal city governor

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7545]
_1. Mod version (i.e Date - 12/1):_3-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I've been away from Civ5 for a while, but it seems this issue persists.

![20210306110909_1](https://user-images.githubusercontent.com/16341598/110201637-cc0e7780-7e6c-11eb-9f12-9c57440707ef.jpg)

Auto focus governor favors a tile with 1 food 1 production over the cow or horse tiles with 2 food 1 production.

Savegame:

[Alexander_0047 BC-2120.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6095091/Alexander_0047.BC-2120.zip)

EDIT: May be caused by unhappiness in case of pop growth, not sure.

**Comment by Stalker012345** [comment]
The governor has been bad for a few versions, but I do think its even worse on this version. I am seeing absolute wrong decisions, I had a city working a regular sea tile compared to a netted fish tile (with harbor).

**Comment by ilteroi** [comment]
well actually i thought it got better. 

without better logs we'll never solve this, so i tried to improve this.

in the future, change the focus type and check CityTileScorer.csv afterwards

**Comment by Stalker012345** [comment]
Here's a good example. I did try switching focus back and forth and it fixed it.

![image](https://user-images.githubusercontent.com/20593976/110373266-edaa6300-8014-11eb-993e-9a5ea6624f09.png)

**Comment by saamohod** [comment]
Another example.

Auto governor chooses to work meagre jungle tiles to produce settler in 8 turns instead of working two rich silver tiles that would produce a settler in 7 turns.

![20210310162758_1](https://user-images.githubusercontent.com/16341598/110644655-fe4a0d00-81bd-11eb-9e31-78bda058a105.jpg)
![20210310162806_1](https://user-images.githubusercontent.com/16341598/110644674-01dd9400-81be-11eb-9751-413b602d54b7.jpg)

[Wu Zetian_0076 BC-0975.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6116559/Wu.Zetian_0076.BC-0975.zip)

**Comment by ilteroi** [comment]
everybody relax, i made some improvements, wait for the next release
