### ISSUE TITLE
request: IsPlotConnectedToPlot() ignoring borders; or adding SetHasOpenBorders()

### ISSUE THREAD

**Issue by inkyant** [LoneGazebo/Community-Patch-DLL#7550]
The function
`player:IsPlotConnectedToPlot(Plot pFromPlot, Plot pToPlot)`
requires there to be open borders to the destination. 

Would it be possible to adjust it so that it ignores open borders (maybe with an optional parameter)?

Or, maybe some function like SetHasOpenBorders() could be added?

**Comment by ilteroi** [comment]
what is it you want to achieve?

**Comment by inkyant** [comment]
I have a UA for a modded civ that essentially wants you to build roads to other player's capitals to connect them.

But currently it only works if I have open borders, so I wanted a function to set open borders or an adjustment of IsPlotConnectedToPlot().

**Comment by ilteroi** [comment]
player:IsConnectedTo(player) is meant for city state quests. so you don't need open borders there ...

**Comment by inkyant** [comment]
thank you!

**Comment by RecursiveVision** [comment]
@inkyant See also CvLuaTeam::SetOpenBorders() :)

**Comment by inkyant** [comment]
@ilteroi sorry, but I unfortunately was not able to get it to work. After building the DLL running this:
`pPlayer:IsPlotConnectedToPlot(pCity:Plot(), pCap:Plot(), GameInfoTypes.ROUTE_ANY, true, true) `
only outputted true if I was connected and had open borders.

If it helps, I've attached a save file with a test mod that just prints to the logs when IsPlotConnectedToPlot() is true/false. The save file already has the two cities connected and you can get open borders any turn.
[Connection Test.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6132244/Connection.Test.zip)

I was able to run the debug DLL too and make sure that it was actually running the function and it had the boolean as true, but from there I wasn't sure what to do. iFlags had the correct value and everything, but pPathOut still had everything as -1.
At this point I'm beyond my expertise, I would appreciate if it was fixed.

**Comment by ilteroi** [comment]
hmm which version did you test exactly? there was an omission in the first commit ... maybe it's fixed already in latest oleole

**Comment by inkyant** [comment]
Oh my god, you're right. Thanks, it works perfectly now.
