### ISSUE TITLE
3/2 - Open terrain combat bonus not applied

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7551]
_1. Mod version (i.e Date - 12/1):_ 3/2

_2. Mod list (if using Vox Populi only, leave blank):_
Better lakes v2.2
Improved city view v11
Promotion flags v3

_3. Error description:_ 
Without field promotion STR=28.1
![no field](https://user-images.githubusercontent.com/59859911/110228174-09a2ed00-7ecd-11eb-9be2-6d55917f2524.png)

With field promotion STR=28.1
![with field](https://user-images.githubusercontent.com/59859911/110228175-0ad41a00-7ecd-11eb-8134-1e7c7523df34.png)

Damage was in line with the combat preview if shot with either cannon.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
openRangedAttackModifier() returns zero, even with field level 3.
