### ISSUE TITLE
3/2 - Defender of the faith question

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7552]
_1. Mod version (i.e Date - 12/1):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

![image](https://user-images.githubusercontent.com/59859911/110232043-3b29b180-7ee9-11eb-9aba-c8fc612d3504.png)

Is the combat bonus against land units of a player following another religion only supposed to apply in friendly territory? Crusader Spirit uses the same language and I thought in the past it applied anywhere fighting land units of another religion (not contingent on being in enemy territory).

For example below I do not receive the "other religion" combat bonus against Germany:

![image](https://user-images.githubusercontent.com/59859911/110231755-a3779380-7ee7-11eb-94c9-cb77f00448c8.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Pretty sure it does, yeah

**Comment by silentreply** [comment]
Ok thanks, maybe I am mistaken about the bonus on crusader spirit.
