### ISSUE TITLE
4 Horses still being exported 23 turns after deals ended

### ISSUE THREAD

**Issue by hamorphis** [LoneGazebo/Community-Patch-DLL#7553]
1. Mod version: v.94
2. Mod list:
3. 4 Horses still being exported 23 turns after deals ended
4. Open the save file

[HorsesExportedAfterDealEnded.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6096985/HorsesExportedAfterDealEnded.zip)
[screenshots.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6096987/screenshots.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6096991/Logs.zip)

**Comment by randomnublet** [comment]
beta 3-2

There's still something buggy going on with trading resources. I had 3 spare horses, traded them away correctly with two deals to the same AI, Indonesia, the first was just 2 horses for gpt, the other was 1 copy for some gpt. After the first deal expired I found myself with only 2 horses total, with only one of two copies from the first deal being 'refunded'.

![civhorses2](https://user-images.githubusercontent.com/53142313/112054716-322a1880-8b56-11eb-9ce8-ea2ee2122589.png)


You can see I am now trading one resource to Greece but it counts as 2, leaving me with 1 spare only. Using Poland but didn't unlock the ducal stables yet, just saying, I also noticed some resource loss in previous games.

![civhorses](https://user-images.githubusercontent.com/53142313/112053917-3ace1f00-8b55-11eb-81f1-23af3a09387d.png)
