### ISSUE TITLE
3/2 - Units on occasion get weirdly high Air Defense bonuses

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7555]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_
ENW

_3. Error description:_ 
I saw this in 2/4 as well but didn't report since we had gotten the new version by the time I saw it. I have noticed that periodically a unit will have a much higher air defense than it should. There is no remaining interception in the area (I've bombarded several times with no interception counters), and no air defense on this unit. But it has a 40 defense when it should have 5.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/110254414-aa88bb00-7f54-11eb-8fc5-1032ac0b1f09.png)
[William_0369 AD-1949.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6097943/William_0369.AD-1949.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
why should it have defense 5? i see 52 base plus 116% ... should be even more than 83.

in other news the combat preview does not show the bonus from the forest
![image](https://user-images.githubusercontent.com/1358966/110295801-d443ef80-7ff1-11eb-85ed-bfa5546dbb99.png)

this is so broken.

**Comment by Stalker012345** [comment]
> why should it have defense 5? i see 52 base plus 116% ... should be even more than 83.
> 
> in other news the combat preview does not show the bonus from the forest
> ![image](https://user-images.githubusercontent.com/1358966/110295801-d443ef80-7ff1-11eb-85ed-bfa5546dbb99.png)
> 
> this is so broken.


Sorry if I wasn't clear, I am referring it its Air Defense value (aka how much damage is dealt to the plane after the plane's attack), not the unit defense for the purpose of how much damage it takes. Light Tanks have a default Air Defense of 5, and the unit in question had no air defense promotions, but currently its Air Defense was 40 (aka my plane would take 40 damage when attacking it).
