### ISSUE TITLE
3/2 - Infiltrator Penalty is off versus Cities

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7556]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_
ENW

_3. Error description:_ 
if you compare the two screenshots, in which I am targetting the city, and then a city....look at the monsterous difference in misc bonus. Its a 130% swing. I should be getting an extra +25% for attacking a wounded target, but that's it. Is that the Anti-warmonger penalty somehow?

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/110262186-7cb56d80-7f78-11eb-8ccb-9f3225542b0f.png)

![image](https://user-images.githubusercontent.com/20593976/110262204-88a12f80-7f78-11eb-9b72-e6d8fbd6cab2.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Machine Guns are bad against cities, but I'm not sure if it's that much a penalty...

**Comment by RecursiveVision** [comment]
more issues with EnemyUnitPanel...
