### ISSUE TITLE
Combined MajorCiv and MinorCivApproachTypes

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7558]
Per @ilteroi's suggestion that I be more radical (I hope you're happy because it took me 15 hours to do this!!!), I have combined the MajorCiv and MinorCivApproachTypes enums into a single CivApproachTypes enum:

CIV_APPROACH_WAR,
CIV_APPROACH_HOSTILE (= bully for City-States),
CIV_APPROACH_DECEPTIVE (majors only),
CIV_APPROACH_GUARDED (majors only),
CIV_APPROACH_AFRAID (majors only),
CIV_APPROACH_NEUTRAL,
CIV_APPROACH_FRIENDLY

I eliminated MINOR_CIV_APPROACH_PROTECTIVE and simply made a single approach for being friendly and protective to City-States; it was a pointless Firaxis distinction that barely made any difference.

Results can be seen in the experimental branch (not tested yet). Also did another pass of SelectBestApproachTowardsMinorCivs() to reduce CS conquest fervor a bit.

I did not alter the XML tables for leaders, rather I altered the way in which the data was retrieved from those tables in CvInfos.cpp, so custom civs and most mods should still be compatible. For the CIV_APPROACH_FRIENDLY bias in the case of City-States, it takes the higher value of MINOR_CIV_APPROACH_FRIENDLY and MINOR_CIV_APPROACH_PROTECTIVE (from XML).

Unfortunately because the LUA enum MajorCivApproachTypes was changed to CivApproachTypes, this breaks compatibility with any modmod that uses this. Probably not a big deal as I doubt many VP mods (if any?) do anything which affects diplomacy, but worth noting.

@LoneGazebo, any comments? This is not in my pull request yet as it's untested.

**Comment by RecursiveVision** [comment]
Note that if you're testing experimental you need to update your LUA folders as well!

**Comment by ilteroi** [comment]
uh, i didn't mean to pressure you into anything ... but i'll test it

**Comment by RecursiveVision** [comment]
@ilteroi No worries, I did it of my own volition, not because I felt pressured. It will be nice to have it united like this for me as well. Just annoying how much work it was haha :)

**Comment by RecursiveVision** [comment]
Sorry if it came off as aggressive, I thought the exclamation mark spam would communicate the humorous intent!

**Comment by LoneGazebo** [comment]
It should be fine. Is it not possible to retain those other enum types and simply have a lua level filter that manages it? That's my recommendation.

**Comment by RecursiveVision** [comment]
@LoneGazebo Okay, I rewrote it so that GetMajorCivOpinion() still works in LUA by retaining the MajorCivApproachTypes enum (MinorCivApproachTypes had no LUA equivalent).

@ilteroi Okay so now it's simplified a bit as follows.

Enums:
CivApproachTypes - A civ's approach towards another player, i.e. how they act towards them
CivOpinionTypes - A civ's opinion of another player, i.e. what they think of them

You can now call:
GetCivOpinion()
GetCivApproach()
GetSurfaceApproach() - the surface-level approach adopted towards another player (not always the same as the true approach)
GetVisibleApproachTowardsUs() - the other guy's surface-level approach towards the viewing player

This now works for majors, City-States and Barbarians alike.

(For non-majors I just used simple logic but it should work effectively if you want to use it for determining whether a nearby player is an enemy or for whatever else)

**Comment by RecursiveVision** [comment]
Tested and it's not crashing, things seem as stable as ever. Merged into rsi.

**Comment by RecursiveVision** [comment]
@ilteroi WarDamageLevelTypes is now no more as well...
