### ISSUE TITLE
EnemyUnitPanel.lua Rewrite?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7559]
So I'm getting tired of the EnemyUnitPanel being broken, and I'm not the only one. :)

GetOpinionTable() in CvLuaPlayer proves that we can associate text strings with numbers and push them into LUA.

Why not just calculate all the modifiers in the DLL, cache the top X modifier values plus the Misc. value (however many will fit in the box) and also cache the textkeys for those modifier values, then retrieve them using LUA methods?

So LUA call -> DLL calculation -> DLL cache -> LUA retrieval, in that order.

Or maybe you could skip the caching and just have the call retrieve the data from the DLL directly in the same vein as GetOpinionTable()?

The calculation is already being performed by the game so it would require:
1) Adding new cached memory values
2) Copying the prioritization of which modifier is displayed first / which are summed up in Misc. to the DLL calculation
3) Replacing the LUA calculation with the calculation and retrieval calls

Although this would be some work, it doesn't sound insurmountable to me - assuming that this would actually work.

@LoneGazebo @ilteroi @HungryForFood Any thoughts?

**Comment by ilteroi** [comment]
it's sure possible but it's a lot of work.

**Comment by LoneGazebo** [comment]
I wonder if you could integrate tooltipsink method (like how they do it for tooltips for city yields)?

**Comment by LoneGazebo** [comment]
That would let you simply inject the tooltips into the existing function. 

The real problem though is presentation - enemy unit panel is only so large.

**Comment by RecursiveVision** [comment]
Gonna do some work on this and see what I can do, but the code is awful.

**Comment by Stalker012345** [comment]
+1000 desire on this one ;)
