### ISSUE TITLE
Crash on restart button + settling a city

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#756]
Ilterioi,

I've pinpointed the crash on restart/settle or settle/restart to here (see gallery for callstack below), but I can't quite get it to not crash. I've fiddled some, but not much. In any case, you can reproduce by starting a game, using restart button, settling, and then using restart button again (any combination should probably cause it.

![untitled5](https://cloud.githubusercontent.com/assets/7849458/11024049/369fffca-8656-11e5-923d-c9b6ec3d08b1.png)
![untitled6](https://cloud.githubusercontent.com/assets/7849458/11024050/36a0cfe0-8656-11e5-8fb8-2f4bb97d73f0.png)
![untitled7](https://cloud.githubusercontent.com/assets/7849458/11024052/36a30116-8656-11e5-9c5e-bf8ad805252d.png)
![untitled8](https://cloud.githubusercontent.com/assets/7849458/11024051/36a171e8-8656-11e5-94b9-f62d52dd8b53.png)
![untitled9](https://cloud.githubusercontent.com/assets/7849458/11024053/36a4906c-8656-11e5-83c8-bfdf492dc715.png)
![untitled10](https://cloud.githubusercontent.com/assets/7849458/11024054/36a48176-8656-11e5-9a2e-8f31b080f9e2.png)
![untitled](https://cloud.githubusercontent.com/assets/7849458/11024055/36a7573e-8656-11e5-8e97-3e78c2bc4861.png)
![untitled2](https://cloud.githubusercontent.com/assets/7849458/11024056/36aa061e-8656-11e5-9c06-c988685701c9.png)
![untitled3](https://cloud.githubusercontent.com/assets/7849458/11024058/36ad487e-8656-11e5-998c-c27fdb5f969d.png)
![untitled4](https://cloud.githubusercontent.com/assets/7849458/11024057/36ac59fa-8656-11e5-90b7-3a0e4f210ee6.png)

**Comment by LoneGazebo** [comment]
Seems a key variable is not being refreshed properly on restart. Fixing this might also fix multiplayer issues with desyncs on save/load (as the logic seems to be the same).

G

**Comment by ilteroi** [comment]
wow, a picture story!

i got one of my own too:

![image](https://cloud.githubusercontent.com/assets/1358966/11043687/439c2802-871e-11e5-8bc1-0ec7f1018daf.png)

seriously, i'll try to reproduce ...

**Comment by LoneGazebo** [comment]
Yay, those are fun. Is that due to something you've done recently, or is it a problem already in the DLL?

G

**Comment by ilteroi** [comment]
didn't touch it. i think i have a fix, but it's hard to verify, was a strange configuration with multiple masters and vassals.

reproduced your issue and it seems gGlobals.m_map is not initialized. the hunt is on

**Comment by LoneGazebo** [comment]
Ah, I didn't look at that element when trying to debug. Admittedly my glance was cursory (I've been a wee bit busy as of late). Sorry for tossing it on you!

**Comment by ilteroi** [comment]
i do enjoy a good puzzle now and then :)

unfortunately, it seems there's little to be done about it (on dll side at least). CvGame::InitMap() is just never called in the bad case. The correct entry point would be CvDllGame::Init2()

**Comment by LoneGazebo** [comment]
Hmm...so the initialization isn't being called in our DLL? If that's the case, then why does our DLL (but not other custom DLLs) crash on restart? Any way we can force initmap into our initialization?
G

**Comment by LoneGazebo** [comment]
I'm going to spelunk a bit as well.

**Comment by ilteroi** [comment]
after sleeping over it, i may have been looking in the wrong place.

initPlayers() leads to the crash and it's called before initMap().

need to investigate some more

**Comment by ilteroi** [comment]
ok, i think i got it. flavor manager was re-initialized before the old cities have been cleared

**Comment by LoneGazebo** [comment]
Odd! Was that a CP change, or standard?
