### ISSUE TITLE
(3-2) Game crash on AI turn 

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7561]
_1. Mod version (i.e Date - 12/1):_3-2

_2. Mod list (if using Vox Populi only, leave blank):_ None

_3. Error description:_  

Game consistently crashes on AI's turn

Savegame:

[Crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6101265/Crash.zip)

Minidump:

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6101305/CvMiniDump.zip)
 
Logs:

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6101858/Logs.zip)

**Comment by ilteroi** [comment]
maybe my bad, had a typo. try this one 
[CvGameCore_Expansion2_8bffa11b.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6104794/CvGameCore_Expansion2_8bffa11b.zip)

**Comment by saamohod** [comment]
> maybe my bad, had a typo. try this one
> [CvGameCore_Expansion2_8bffa11b.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6104794/CvGameCore_Expansion2_8bffa11b.zip)

Is it supposed to go to "(1)Community Patch" folder? I put it there and it doesn't work. The game still CTDs at the same spot.

**Comment by ilteroi** [comment]
callstack is
```
7444fa5c 65d2aba7 CvGameCore_Expansion2!std::_Tree<std::_Tset_traits<FAutoVariableBase *,std::less<FAutoVariableBase *>,std::allocator<FAutoVariableBase *>,0> >::insert+0xf [c:\program files (x86)\microsoft visual studio 9.0\vc\include\xtree @ 634]
7444fa7c 65b3151a CvGameCore_Expansion2!CvUnit::SetTurnProcessed+0x37 [d:\sources\civ-vp\cvgamecoredll_expansion2\cvunit.cpp @ 7193]
7444fb30 65b3d29a CvGameCore_Expansion2!CvHomelandAI::ReviewUnassignedUnits+0x1ba [d:\sources\civ-vp\cvgamecoredll_expansion2\cvhomelandai.cpp @ 2016]
7444fb40 65c1f484 CvGameCore_Expansion2!CvHomelandAI::Update+0x8a [d:\sources\civ-vp\cvgamecoredll_expansion2\cvhomelandai.cpp @ 205]
7444fb68 65afb5c4 CvGameCore_Expansion2!CvPlayerAI::AI_unitUpdate+0xf4 [d:\sources\civ-vp\cvgamecoredll_expansion2\cvplayerai.cpp @ 298]
```

seems to be an invalid CvUnit pointer. no idea how and why this happens.

**Comment by randomnublet** [comment]
CTD during city state turn, I tried this dll as well no luck. 3-2, no other mods


[AutoSave_0095 BC-0500.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6136473/AutoSave_0095.BC-0500.zip)

**Comment by ilteroi** [comment]
there is a good chance this is fixed
