### ISSUE TITLE
3/2 - AI is no longer building proper Air Defenses

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7563]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
A version ago I couldn't throw a rock without hitting an AA gun. Now the AI is building very few AA guns and almost no fighters. I've seen it in two games now where I have a big air force that is demolishing the enemy without any real attempt at interception forces mounted.

I am noticing an increase in Air Defense promotions used by the AI....so perhaps it thinks that is "fulfilling its air defense need"? 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
this is not tactical ai, will change the title accordingly
