### ISSUE TITLE
3/2 - Vassal screen not showing all conditions for independence.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7565]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_
ENW

_3. Error description:_ 
I believe there is like 3-4 conditions for independence, but currently the screen in only showing the first (and easiest) one.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/110394223-aed6d600-8031-11eb-8dff-a589b66a61ff.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Voluntary vassal.

**Comment by Stalker012345** [comment]
Oh, your saying that voluntary vassals can leave their masters anytime after 10 turns? I had no idea!

**Comment by RecursiveVision** [comment]
Yes :)
