### ISSUE TITLE
3/2 - Missing Left Panel for Trade Screen

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7566]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_
ENW, UI - Trade Routes, UI - Improved City View

_3. Error description:_ 
Got a nasty one for you. For most of the game, trade was fine no issues. Now...the left side of the trade screen is completely gone, I cannot make trades.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/110405383-231b7480-8046-11eb-9a0b-7e64401d049c.png)
[Bad Trade.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6105215/Bad.Trade.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Upon full reload the issue seems to be gone, so maybe a memory issue?

**Comment by RecursiveVision** [comment]
If you encounter it again, upload your lua.log file.
