### ISSUE TITLE
3/2 - Infinite save loading with a revealed map

### ISSUE THREAD

**Issue by dubhit** [LoneGazebo/Community-Patch-DLL#7567]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_
Ingame Editor (IGE) or built-in debug mode

_3. Error description:_
Infinite save loading with a revealed map after exiting the game

_4. Steps to reproduce (optional):_
1. Start a map with Community Patch enabled
2. Click "Reveal Map" button in IGE or press CTRL+Z if debug mode is on
3. Save the game
4. Click "Exit to windows" (if you choose "Exit to main menu" instead, the save will be loaded successfully)
5. Run the game again and try to load the save

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by CyberPhy** [comment]
I've had this problem on the last update, my game took about 30 minutes to load
I did not use IGE but FireTuner to do it
