### ISSUE TITLE
Divide by zero in CvDiplomacyAI.cpp 

### ISSUE THREAD

**Issue by Heinous-Hat** [LoneGazebo/Community-Patch-DLL#757]
In the previous version (10-29), I was seeing a rare CTD from iMyMilitaryStrength=0, despite the check that's supposed to prevent that. I notice CvDiplomacyAI.cpp is updated... was this a known or addressed bug?

Version 11-5 is not save compatible, so I ask because I've lost my reference point ;)

**Comment by LoneGazebo** [comment]
Don't think so - there's a discrete check to prevent that from happening. I'll double the check though, to be sure.

**Comment by ilteroi** [comment]
i think i hit the same issue, it's fixed in my branch

**Comment by Heinous-Hat** [comment]
Ah, good... wasn't sure when/how it was hitting 0 or why it was escaping the check. 

Thanks
