### ISSUE TITLE
3/2 - Received unit for meeting militaristic CS

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#7570]
_1. Mod version (i.e Date - 12/1):_ 3/2

_2. Mod list (if using Vox Populi only, leave blank):_
Better lakes v2.2
Improved city view v11
Promotion flags v3

_3. Error description:_ 
I was gifted a pathfinder upon meeting Budapest. Could be related to the fix for unit gifts? 
![image](https://user-images.githubusercontent.com/59859911/110718335-c4d2cb00-81d8-11eb-8265-b46842619305.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[AutoSave_0001 BC-3960.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6119648/AutoSave_0001.BC-3960.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
It's the unique reward for being the first to meet a militaristic CS.

**Comment by silentreply** [comment]
@RecursiveVision I guess this is the first time I've been the first to meet a militaristic CS! A free pathfinder seems way stronger than the other meeting bonuses. These days I am playing with ruins off, but still.
