### ISSUE TITLE
Disabled movement animation right after a peace deal

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7573]
_1. Mod version (i.e Date - 12/1):_3-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  This oddity has been around for years, but I cannot remember anyone bringing it up. Does it only happen to me or is there any legitimate reason for this behaviour? 

Right after signing a peace deal my units lose their movement animation and start moving instantaneously as if I disabled movement animation (I guess many people play with quick moves and therefore never notice the change). Things go back to normal next turn.
It's a very minor issue and can be slightly annoying for those who play with movement animation on. But since it's been around as long as I remember myself playing VP, I start getting curious.

**Comment by RecursiveVision** [comment]
I've had this issue too, I suspected it was a bug with Quick Turns.

**Comment by Padre19** [comment]
Quick Turns

click once on the icon ''Quick Turns'' on the top right.

**Comment by saamohod** [comment]
> I've had this issue too, I suspected it was a bug with Quick Turns. Are you using Quick Turns?

Yes. So it must be it. Case closed I guess.
