### ISSUE TITLE
GameEvents.CityCaptureComplete.Add + GameEvents.CityPuppeted.Add

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#7574]
For AI the CityPuppeted event comes before CityCaptureComplete and for the human player it is the other way around: first CityCaptureComplete then CityPuppeted.

Because of this
World Congress Reformation by Enginseer is no longer working properly.

**Comment by LoneGazebo** [comment]
Unfortunately I don't see a way to avoid this, as the human popups are handled differently. Might need to take this to @TechpriestEnginseer

**Comment by Padre19** [comment]
Should be CityCaptureComplete then CityPuppeted for all.

**Comment by TechpriestEnginseer** [comment]
> Should be CityCaptureComplete then CityPuppeted for all.

Interesting...

**Comment by Padre19** [comment]
your mode needs an update if you are still interested ....
