### ISSUE TITLE
Game crash on guided missile launch

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7579]
_1. Mod version (i.e Date - 12/1):_3-2, updated .dll from this post (https://forums.civfanatics.com/threads/new-beta-version-march-2nd-3-2.668024/page-7#post-16044317)

_2. Mod list (if using Vox Populi only, leave blank):_Quick Turns

_3. Error description:_  When launching a guided missile from a freshly captured city Fortaleza aimed at an enemy ironclad nearby, the game crashes.

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6132624/QuickSave.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6132625/Logs.zip)

[CvMiniDump (2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6132631/CvMiniDump.2.zip)

**Comment by ilteroi** [comment]
can reproduce it if i turn off quickturns, ie enable animations.

unfortunately it happens outside the gamecore, no chance to analyze further, let alone fix.

![image](https://user-images.githubusercontent.com/1358966/110998274-dce44f00-837e-11eb-959f-e53f39de6192.png)

this seems bad. no idea why what's going on.

**Comment by ilteroi** [comment]
found the offending change with a bit of bisection ...
