### ISSUE TITLE
a few saves which ctd on loading them

### ISSUE THREAD

**Issue by a1nosweat** [LoneGazebo/Community-Patch-DLL#758]
I am using modpack 29/10, with no other mods installed.  I suspect that its map related - as even the autosave.initial files fail to load.  Some CTD when the map is loaded, others before (during the loading screen.

I cannot post the saves here, but here's the database and lua log files from a game as Ethiopia(ctd during load screen)

[Lua.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/31342/Lua.txt)
[Database.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/31347/Database.txt)

And here's me playing Lizzie vs the celts
[Lua.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/31353/Lua.txt)

[Database.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/31352/Database.txt)

Last entry in both cases is for database.log is "columns StrategicViewType, TileType are not unique"

Is this significant?

Could I be choosing the wrong map type?  I think I probably choose random.  This would also explain why my games fail more often than my brother's.

**Comment by LoneGazebo** [comment]
Nah, those are innocuous errors, however looks like you are missing some Leader DLC, like Spain and Denmark.

**Comment by a1nosweat** [comment]
That shouldn't be the the case.

![image](https://cloud.githubusercontent.com/assets/15791659/11078853/3ea0226c-8800-11e5-9fe1-4a74bd4d416d.png)
![image](https://cloud.githubusercontent.com/assets/15791659/11078872/61315e72-8800-11e5-9364-ebab71f1d776.png)

**Comment by a1nosweat** [comment]
reread the thread, here's cvminidmp.dmp - renamed to txt file.

[CvMiniDump.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/31366/CvMiniDump.txt)

**Comment by LoneGazebo** [comment]
Interesting - when you load the mod, are you checking them and then clicking 'next?' Also, running any other mods that might conflict?

**Comment by LoneGazebo** [comment]
What's your mod list?

**Comment by a1nosweat** [comment]
I'm using the last modpack, no other mods installed.  All DLC stay checked (as far as  I know, I never uncheck them.)

Some games work other's don't.  On some You can revert  to an autosave, on the ones above (certainly ethiopia, not sure about england) all autosaves, including the first ones fail to load.

Luckily hotseat games seem to function just fine.

**Comment by LoneGazebo** [comment]
Very odd. I'll keep an eye out.

G

**Comment by a1nosweat** [comment]
cheers - shall I continue to post new examples here?  Will update to next version after next game finished.

**Comment by LoneGazebo** [comment]
I'm about to do a merge and some testing, so hold off on new posts until after new version.
G

**Comment by a1nosweat** [comment]
Just tried to get my hotseat game completed before I update.

Seems I've got a problem with aircraft now.  CTDs when asking them to bomb targets.  logs attached.
[Database (2).txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/33517/Database.2.txt)
[Lua.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/33518/Lua.txt)

**Comment by LoneGazebo** [comment]
What version? This problem was fixed a few versions back.
G

**Comment by a1nosweat** [comment]
still 29/10 - hooked on the hotseat game I'm playing, and only play it a few hours a night.  will update asap.....and keep quiet till then :)

Many thanks...
