### ISSUE TITLE
Ironclad sails across a desert hill

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7580]
_1. Mod version (i.e Date - 12/1):_3-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  An enemy ironclad is spotted sitting on a desert hill. Tooltip says there isn't any improvement there.

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6134523/QuickSave.zip)

![20210313121137_1](https://user-images.githubusercontent.com/16341598/111026907-a695e680-83f5-11eb-8e25-bc9d22a79ae6.jpg)

**Comment by ilteroi** [comment]
must be the new 'aguirre' promotion!

https://en.m.wikipedia.org/wiki/Aguirre,_the_Wrath_of_God

**Comment by azum4roll** [comment]
Maybe they started building something on the plot and replaced the fort.

**Comment by saamohod** [comment]
> Maybe they started building something on the plot and replaced the fort.

Maybe, but it's still something abnormal. When my paratrooper landed on that tile there wasn't any worker there, and he was sitting on that tile as a spotter for the whole duration of war with Brazil, which was at least 20 turns. Obviously no worker was doing any improvements there in that time.

**Comment by SuperNoobCamper** [comment]
A pillaged fort behaves like this...
I wanted to report this bug in addition to another one related to pillaged forts.
Not only ships can pass through it, embarked units can disembark onto it with only 1 MP but also sometimes units ignore terrain cost when moving into that tile.

**Comment by ilteroi** [comment]
re: pillaging, i see no issue

![image](https://user-images.githubusercontent.com/1358966/111917045-2ff48b00-8a7e-11eb-9cfb-7b283facba31.png)

**Comment by saamohod** [comment]
I one of my games (maybe the one mentioned in this thread) I pillaged a fort and it just disappeared, at least visually. I thought it was intended, haven't played VP for quite a while.

**Comment by SuperNoobCamper** [comment]
> I one of my games (maybe the one mentioned in this thread) I pillaged a fort and it just disappeared, at least visually. I thought it was intended, haven't played VP for quite a while.

Forts disappear every single time I pillage them.

This report has the same issue in addition to the ability of ships to pass through it
https://github.com/LoneGazebo/Community-Patch-DLL/issues/7588

**Comment by ilteroi** [comment]
duplicate
