### ISSUE TITLE
Boredom decrease as pop grows

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7581]
_1. Mod version (i.e Date - 12/1):_3-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Not sure if it's a bug or my lack of understanding of the game mechanics.
Tooltip says that the boredom in Nanjing will **decrease** when the city grows a pop. Can't find any reason for this and it's the first time I see a green number in that slot, therefore I raise the alarm.

![20210313143143_1](https://user-images.githubusercontent.com/16341598/111030126-5759b100-8409-11eb-94b6-082729d5f1eb.jpg)

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6134766/QuickSave.zip)

**Comment by ilteroi** [comment]
might be possible, because of hierarchy of needs
