### ISSUE TITLE
Lighthouse for a lake city

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7582]
_1. Mod version (i.e Date - 12/1):_3-2 hotfixed

_2. Mod list (if using Vox Populi only, leave blank):_pineappledan's Power Plants

_3. Error description:_ 

I'm able to build a lighthouse in a lake city, although the description says it should only be coastal city. Are lakes considered coastal for lighthouse?

![20210313200509_1](https://user-images.githubusercontent.com/16341598/111039620-a61e3f80-8437-11eb-8909-2eb52f01878c.jpg)

**Comment by silentreply** [comment]
Cities on lakes can build coastal buildings now, but I think a recent change disallowed them from building coastal wonders. 

I think this is a good middle ground that offers a lot of utility for lake cities, especially when they can be connected to ocean by fort/canal.
