### ISSUE TITLE
Abandoned AI units

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7583]
_1. Mod version (i.e Date - 12/1):_3/2 hotfixed

_2. Mod list (if using Vox Populi only, leave blank):_pineappledan's Power Plants

_3. Error description:_ 

Probably related to https://github.com/LoneGazebo/Community-Patch-DLL/issues/7576

Apparently Zulu sent a party to a distant island to clear a barb encampment and they were eventually forgotten. Those units have been sitting there for a long time without purpose quite far from Zulu lands.

![20210313232312_1](https://user-images.githubusercontent.com/16341598/111044857-bc39f900-8453-11eb-8498-808d758d951b.jpg)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6135608/Logs.zip)

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6135609/QuickSave.zip)

**Comment by silentreply** [comment]
Are they not stuck there? Do you have open borders? And looks like the camp was only cleared recently.

**Comment by ilteroi** [comment]
yeah i assume they simply cannot find a way home

**Comment by saamohod** [comment]
They've been sitting there for a very long while motionlessly. I founded my three cities there much later, before that they had literally dozens of turns to return back home. The path was there the whole time

![Inked20210314101052_1_LI](https://user-images.githubusercontent.com/16341598/111061888-3bf4b180-84ae-11eb-96a4-35d91ffb455c.jpg)

Worth mentioning that city-state Nobamba used to be Zulu city but it rebelled and became independent when those troubled units were out on the islands. Could it be that the reason they weren't able to pass through Nobamba territory was their war status? If so, then war definitely lasted way longer than should be.

**Comment by RecursiveVision** [comment]
Pretty sure pathfinder AI won't route through cities they are at war with, so yes, probably they have no path.

**Comment by ilteroi** [comment]
i added a flag which allows paths through unrevealed plots, should help in cases like this
