### ISSUE TITLE
Warrior still buildable after Celts research Mining

### ISSUE THREAD

**Issue by dostillevi** [LoneGazebo/Community-Patch-DLL#7584]
_1. Mod version (i.e Date - 12/1):_
3-2 beta

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi with EUI
(7c)Leugi's Israel for VP (v. 16)
(7z) Promotion Icons (Patch for VP(7-29)) (v. 1)
(over) More Unique Components for VP (v. 65)
(ui) Wonder Planner for VP (V. 8)
Colonialist Legacies' Tlingit for VP (v. 17)
Archaeology Aesthetic Adjustments (V. 1)
Civ Names by Policies (v. 8)
Colonialist Legacies' - Phillipine Republic for Vox Populi (v. 9)
Colonialist Legacies' Canadian Dominion for VP (v. 19)
Colonialist Legacies' Inuit for VP (v. 16)
Goths for Vox Populi (v. 2)
Historical Religions Complete (BNW or GK) (v. 45)
InfoAddict (v. 22)
MC and LITE's Nubia for VP (v. 15)
MC's Greece/Macedon Split for Vox Populi (v. 13)
Monopoly Buildings for Vox Populi (v. 3)
New Beliefs Mod (v. 8)
Pineappledan's Phoenician Civilization (v. 3)
Quick Turns (v. 10)
Sukritact's Khmer Civilization for VP (v. 10)
Tomatekh's Timurids for VP - 4UC Compatible (v. 12)
Tomatekh's Sumer for VP (v. 21)
UI - Filters in Trade Route Overview (Vox Populi) (v. 1)
Unique City-States (v. 6)
Wonder Race (v. 7)

_3. Error description:_ 
The Celts are able to build the Pictish Warrior, a Spearman replacement, after researching Mining (as intended) instead of the usual Bronze Working. Once Mining is researched, the Celts may continue building Warriors alongside Pictish Warriors. Once Bronze Working is researched, the Celts can only build Pictish Warriors. I believe only Pictish Warriors should be buildable once Mining is researched, otherwise it's much faster to build warriors and promote them than to build Pictish Warriors directly. Either way, it doesn't make sense that researching Bronze Working, a tech unrelated to the Pictish Warrior, should affect whether or not the Celts can build Warriors.

_4. Steps to reproduce (optional):_
Start a game as the Celts, and research Mining but not Bronze Working. Note that Warriors and Pictish Warriors may both be built. Research bronze working. Now only Pictish Warriors may be built.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6136002/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[AutoSave_0039 BC-3025.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6136003/AutoSave_0039.BC-3025.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):|

![image](https://user-images.githubusercontent.com/39426657/111055928-97338f00-842f-11eb-8391-e482bdaf3485.png)

**Comment by RecursiveVision** [comment]
The Warrior obsoletes at Bronze Working and not Mining, that's why. This is not changed on a civilization-specific basis.

**Comment by RecursiveVision** [comment]
Could be fixed by adding a condition to the "canbuild" check - if unit's upgrade's prereq technology is unlocked, don't allow building.

**Comment by dostillevi** [comment]
Based on that, there are probably other examples of this occurring with other Civs, but those situations may be less odd than this one. 

There's also the reverse, for example when it's highly desirable to be able to continue making a civ's unique unit and then immediately promoting it to the next tier, until the tech that retires the unique unit is eventually researched. I wouldn't want to change that.
