### ISSUE TITLE
[Feature Request] Baths should be made available to all cities, but not on equal terms

### ISSUE THREAD

**Issue by Phosphoraptor97** [LoneGazebo/Community-Patch-DLL#7586]
My main gripe with the terrain requirement for Baths is that tradition civs will be locked out of a 4 culture building(Baths gives +2, Splendor gives +2), a lot of culture for that stage of the game (almost as much as opera house when it usually becomes available). The bonus to the Baths is only a small part of Traditions' kit, but being "cheated" out of 4+ culture in the early game because you didnt start next to a lot of rivers does not feel good.

Cities with fresh water should always be a step up from those without to model how the earliest civilisations sprung up near rivers, but I also feel that as the game goes on and civs develop,  they should be able to provide amenities to any citizen under them. With this in mind, I would suggest enabling cities without fresh water to be able to build baths, but locked behind more strenuous requirements: logistics on the level of the Roman Empire is not easy! These can range from:
- An Aqueduct (Same era, thematically appropriate, may be too close in tech tree)
- Tradition finisher (Addresses the gripe i mentioned, but still sucks for everyone who picked something else)
- A Garden (Good distance from Baths tech, synergy encourages player to build a usually specialised building)
- Machinery Tech (Might be too far ahead of Baths tech to be meaningful, but also makes thematic sense)

**Comment by Stalker012345** [comment]
I am generally a fan of saying "The aqueduct connects the city to fresh water", and then allow the building of baths. That seems appropriately thematic and addresses the balance concern nicely.

**Comment by RecursiveVision** [comment]
@Phosphoraptor97 As a balance issue, this should be discussed on the forums.
