### ISSUE TITLE
[Feature Request] Religious Quests/Wars

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#7587]
One thing that has always been lacking in all Civs with regards to Religions has been the ability to spread them using quests. Yes we can do this somewhat with City States when they request our religions, however Civ itself is sorely lacking on any type of religious expansions through quests or military. 

The best example of this is of course the 9 catholic crusades between AD 1096 and 1271. This helped not only increase wealth but also had side effects for other religions such as Islam with the Mamaluks rising to power and actually being able to expand Islam.  

If done properly this could really expand VP as well as the game itself as the obvious choices would be the main religions fighting one another aside from just using missionaries and inquisitors. You could also technically have protestants expanding off of Catholicism. 

Some examples of ideal scenarios would be 

30 Years War
Tudor conquest of Ireland
Catholic Crusades
Mamluk Expansion
Hessian War
80 Years War
8 Wars of Religion
Ottoman Threat 

etc. etc. 

Just a thought.

**Comment by ilteroi** [comment]
sounds good, go ahead!

**Comment by R3P0FFXI** [comment]
> sounds good, go ahead!

LOL im a project manager not a programmer, I can help you map it out but as far as writing code you might want to get someone that wont break everything. The extent of my knowledge for programming is if then else.

**Comment by RecursiveVision** [comment]
I think this is outside the scope of VP. You could try asking in the Mods Repository subforum :)
