### ISSUE TITLE
Boats forced to move end up in weird places

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7588]
Version: 3-2
After capturing a city with a boat and then liberating it, my boat got put in a pretty silly place as shown:
![boat issue](https://user-images.githubusercontent.com/55395192/111102952-2e3e3b00-8545-11eb-8ea7-784c76418517.jpg)

Also when I tried it again and blocked the tile it went to here it went to one of my forts like 10 tiles away so definitely strange stuff.

When this happens to land units they get put on a tile next to the city.

**Comment by ilteroi** [comment]
duplicate
