### ISSUE TITLE
Worker as a religious unit

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7590]
_1. Mod version (i.e Date - 12/1):_3-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Can't remember seeing it in vanilla or in previous VP versions. Religious strength is shown for a worker unit. He isn't even a religious unit.

![20210315201246_1](https://user-images.githubusercontent.com/16341598/111201385-5ff9e500-85cb-11eb-9540-cff012cc82e8.jpg)

**Comment by ilteroi** [comment]
doesn't happen for me

**Comment by saamohod** [comment]
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6144395/QuickSave.zip)

It seems all civilian units in my game have some religious reference.

![20210315225220_1](https://user-images.githubusercontent.com/16341598/111220211-8fb3e780-85e1-11eb-9df9-404b49a26bc5.jpg)

![20210315225128_1](https://user-images.githubusercontent.com/16341598/111220231-96daf580-85e1-11eb-8dcd-c4ffa523da99.jpg)

**Comment by LoneGazebo** [comment]
likely a mod conflict, then, unfortunately.

**Comment by randomnublet** [comment]
> 
> 
> likely a mod conflict, then, unfortunately.

I have a different installation than the OP, in fact the only mod over vp 3-2 I use is Alternative Difficulty Mod that is not in his list, and I do have the same issue. It also happens with zealotry-bought military units (bought/built military units don't have this issue, civilians do)

![civuibug](https://user-images.githubusercontent.com/53142313/112902559-96188800-90e6-11eb-9f70-923902c7f90c.png)


This ONLY happens after I built Borobudur though, that's likely the culprit.

**Comment by ilteroi** [comment]
duplicate #7644
