### ISSUE TITLE
Game crashes during AI turn back to destop

### ISSUE THREAD

**Issue by knut1988** [LoneGazebo/Community-Patch-DLL#7591]
_1. Mod version (i.e Date - 12/1):_
New Beta Version - March 2nd (3-2)

_2. Mod list (if using Vox Populi only, leave blank):_
None

_3. Error description:_ 
Game crashes at end of turn back to desktop

_4. Steps to reproduce (optional):_
Please hit end of turn. Wait for AI to perform their turns. Game crashes to desktop prior player can do the next turn.

--------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6144617/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Maria Theresa_0305 AD-1425.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6144625/Maria.Theresa_0305.AD-1425.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6144626/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
probably fixed
