### ISSUE TITLE
CvFlavorManager::ChangeFlavors

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7595]
i just found out that GetIndividualFlavor(CULTURE) is -12 for Oda Nobunaga, which was a surprise

0. the database says flavor should be 8
1. seems weird that japan would have such a low flavor?
2. in general the active flavors are all over the place, what is the intended range here?

  | Name | Value | Type
-- | -- | -- | --
◢ | this->m_piActiveFlavor,20||
  | [0] | 182 | int
  | [1] | 218 | int
  | [2] | 6 | int
  | [3] | 20 | int
  | [4] | 40 | int
  | [5] | 192 | int
  | [6] | 104 | int
  | [7] | 68 | int
  | [8] | 48 | int
  | [9] | 9 | int
  | [10] | 5 | int
  | [11] | 69 | int
  | [12] | 3 | int
  | [13] | 6 | int
  | [14] | -4 | int
  | [15] | 3 | int
  | [16] | 8 | int
  | [17] | 7 | int
  | [18] | 5 | int
  | [19] | -12 | int

**Comment by RecursiveVision** [comment]
@ilteroi Yeah I have no idea what's up with that code at all...

**Comment by ilteroi** [comment]
surprise!

		int iFlavorMinValue = /*-1000*/ GC.getFLAVOR_MIN_VALUE();
		int iFlavorMaxValue = /*1000*/ GC.getFLAVOR_MAX_VALUE();

this seems quite stupid. much too finegrained and negative values cause havoc all over the place.

**Comment by RecursiveVision** [comment]
Hence why I said that. The "strategy" system in general seems convoluted and stupid.

**Comment by ilteroi** [comment]
i cleaned it up a bit ...
