### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#7597]
(1) Community Patch/Core Files/Core Changes/UnitFixes.sql

INSERT INTO Unit_FreePromotions (UnitType, PromotionType) SELECT 'UNIT_HELICOPTER_GUNSHIP' , 'PROMOTION_EMBARKATION';
INSERT INTO Unit_FreePromotions (UnitType, PromotionType) SELECT 'UNIT_HELICOPTER_GUNSHIP' , 'PROMOTION_DEFENSIVE_EMBARKATION';
INSERT INTO Unit_FreePromotions (UnitType, PromotionType) SELECT 'UNIT_HELICOPTER_GUNSHIP' , 'PROMOTION_ALLWATER_EMBARKATION';

(2) Community Balance Overhaul/Balance Changes/Units/MountedUnits.sql

	DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_HELICOPTER_GUNSHIP' AND PromotionType = 'PROMOTION_EMBARKATION';
	DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_HELICOPTER_GUNSHIP' AND PromotionType = 'PROMOTION_DEFENSIVE_EMBARKATION';
	DELETE FROM Unit_FreePromotions WHERE UnitType = 'UNIT_HELICOPTER_GUNSHIP' AND PromotionType = 'PROMOTION_ALLWATER_EMBARKATION';

**Comment by Padre19** [comment]
Should the helicopter have these promotions or not?

Also 
(2) Community Balance Overhaul/Balance Changes/Units/NewUnits.sql at line 299 description for  UNITCLASS_ZEPPELIN should be TXT_KEY_UNIT_ZEPPELIN_CBP

**Comment by azum4roll** [comment]
They have the promotions in CP only, but not with full VP?

**Comment by LoneGazebo** [comment]
Those are fixes for base game, but helicopters behave differently in VP.
