### ISSUE TITLE
GreatPersonExpended

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#760]
As it turns out, I could use a fix to the issue I described a while back, wherein the GreatPersonExpended event doesn't register my new Great Magistrate and Great Dignitary (not sure if it registers any new Great People - have you had trouble with the Great Diplomat?). You offered then to expose this function to Lua, so I'm hoping you can indeed do this, when the chance arises. Thanks.

**Comment by LoneGazebo** [comment]
I'll take a look.

**Comment by LoneGazebo** [comment]
Alright, so I've created a workaround for you that exposes the function to lua - it is simply a unit-level lua function called 'greatperson'. If you do that (i.e. eUnit:greatperson()), it'll kill the unit and do the expended function in the player level. Sound good?

**Comment by JFDaly** [comment]
Sounds good. Thanks.
