### ISSUE TITLE
interesting crash in diplo AI

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7600]
there are only 20 different resolutions in the database, but somehow resolutions of type 23 are on the table?

when diplo AI tries to make a vote buying offer, it crashes.

  | Name | Value | Type
-- | -- | -- | --
◢ | vEnactProposals | { size=3 } | std::vector<CvEnactProposal,std::allocator<CvEnactProposal> >
  | [capacity] | 3 | int
  | ◢ [0] | {...} | CvEnactProposal
  | ◢ CvProposal | {m_eProposalPlayer=1 } | CvProposal
  | ▶ CvResolution | {m_iID=10 m_eType=23 m_eLeague=0 ...} | CvResolution
  | m_eProposalPlayer | 1 | PlayerTypes
  | ◢ [1] | {...} | CvEnactProposal
  | ◢ CvProposal | {m_eProposalPlayer=3 } | CvProposal
  | ▶ CvResolution | {m_iID=11 m_eType=23 m_eLeague=0 ...} | CvResolution
  | m_eProposalPlayer | 3 | PlayerTypes
  | ◢ [2] | {...} | CvEnactProposal
  | ◢ CvProposal | {m_eProposalPlayer=8 } | CvProposal
  | ▶ CvResolution | {m_iID=12 m_eType=3 m_eLeague=0 ...} | CvResolution
  | m_eProposalPlayer | 8 | PlayerTypes

obviously i can put a safeguard around the crash location, but how can this even happen? where is the root cause?

**Comment by RecursiveVision** [comment]
I have no idea, the World Congress code in general is overcomplicated as hell...

**Comment by ilteroi** [comment]
weird. seems my database was shot.
