### ISSUE TITLE
3/2 - Auto Explore for Ships cutting out early

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7601]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I've had these caravels on Auto Explore, and though you can see there is still a fair amount of fog of war to explore, the caravels have just stopped. Attempts to move them slightly and kick back auto explore are not working.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/111886079-8b991880-8999-11eb-92d9-fb765ed58fa2.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
yeah, found some small bugs, should be better now
