### ISSUE TITLE
Tourism output bug?

### ISSUE THREAD

**Issue by bringmecoffeeortea** [LoneGazebo/Community-Patch-DLL#7603]
_1. Mod version (i.e Date - 12/1):_

12-1-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Shaka's tourism output skyrocketed in late game around turn 500 or so and I think it's a bug

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6176561/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[Elizabeth_0503 AD-2051-July.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6176565/Elizabeth_0503.AD-2051-July.zip)
[Elizabeth_0487 AD-2043-July.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6176566/Elizabeth_0487.AD-2043-July.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![2021-03-20 (11)](https://user-images.githubusercontent.com/45615147/111888403-944a1880-89b2-11eb-97a2-903d89c4550e.png)
![2021-03-20 (16)](https://user-images.githubusercontent.com/45615147/111888404-944a1880-89b2-11eb-83c9-4ed6ec5fbdf7.png)
![2021-03-20 (17)](https://user-images.githubusercontent.com/45615147/111888405-94e2af00-89b2-11eb-82f0-aaa5410a0a3d.png)

**Comment by ilteroi** [comment]
oh yes i think you are right

**Comment by bringmecoffeeortea** [comment]
Shaka was under sanction for the second half of the game, not sure if that has something to do to the bug.

**Comment by azum4roll** [comment]
Game always break past 2050AD.

**Comment by RecursiveVision** [comment]
think this is fixed
