### ISSUE TITLE
Ships passing through ice tiles

### ISSUE THREAD

**Issue by SuperNoobCamper** [LoneGazebo/Community-Patch-DLL#7604]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_

![image](https://user-images.githubusercontent.com/20557080/111917645-e01bc100-8a89-11eb-9468-fe75ee617542.png)

_3. Error description:_ 
Ships can pass through some ice tiles gaining access to passages they should not be able to access.
It's not always reproducible but it happened enough times in multiple matches that I think it's worth reporting.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[Repor-Ships.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6178136/Repor-Ships.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![CivilizationV_DX11 2021-03-20 16-37-14-641](https://user-images.githubusercontent.com/20557080/111917737-443e8500-8a8a-11eb-8d4f-f916a4da8958.jpg)

**Comment by psparky** [comment]
I believe they can pass through ice within your borders.
