### ISSUE TITLE
3/2 (Tactical AI) - AI abandoning Citadels much too easily

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7606]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Something I have seen several times now, AIs are just abandoning their citadels, even though the units within them are holding decently well.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/111922704-37f60000-8a69-11eb-82f3-6c5cad7a33fb.png)
[Tactical AI.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6178488/Tactical.AI.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
well, the rifleman would die in the citadel. so they retreat. now you can argue that this weakens their overall position but this is exactly the type of reasoning the AI is bad at. but i'll see what i can do.

**Comment by Stalker012345** [comment]
> well, the rifleman would die in the citadel. so they retreat. now you can argue that this weakens their overall position but this is exactly the type of reasoning the AI is bad at. but i'll see what i can do.

Honestly I don't even think the rifle would die, a fortified infantry in a citadel can take a lot of shots.

**Comment by ilteroi** [comment]
made some changes, keep an eye out
