### ISSUE TITLE
[Bug] Losing food every turn on city tile

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#7607]
Mod version 2/4
Error description: Due to unknown reason, all my cities are losing 4 food per turn on the city tile (savegame below).

[Suleiman_0528 AD-1938.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6185064/Suleiman_0528.AD-1938.zip)

**Comment by Zuizgond** [comment]
Looks like it started at turn 523 (epic). Here is the food consumption at turn 522 :
![20210323104206_1](https://user-images.githubusercontent.com/64471766/112126880-2a558d00-8bc5-11eb-9880-1d7861ac4d01.jpg)

Food consumption is affected by empire modifier 25% (I didn't even know such thing exists), local happiness modifier and WLTKD modifier.

Then next turn (I just entered information era), all those modifiers suddenly disappeared in all my cities :
![20210323103532_1](https://user-images.githubusercontent.com/64471766/112127228-80c2cb80-8bc5-11eb-8db6-84a036679705.jpg)

Is it intended?

And then food on city tile started to decrease every turn.

**Comment by azum4roll** [comment]
Looks normal to me.

1. When entering a new era, all specialists consume more food, and your city enters starvation.
2. Positive modifiers don't apply during starvation, since they'll make you starve more.

Switching focus or hovering on the city banner in the overworld should make the city re-evaluate the tiles to work.

**Comment by Zuizgond** [comment]
Ok thanks that makes sense. But what about the food on city tile disappearing? If you look at the screenshot below you can see there is no more food on each city tile.

![20210324092212_1](https://user-images.githubusercontent.com/64471766/112277874-80d4d100-8c82-11eb-8aad-a84169e8ed77.jpg)

**Comment by ilteroi** [comment]
probably a graphical issue only?

**Comment by Zuizgond** [comment]
That was my first thought but city tiles are really losing food each turn at a rate of -4f/turn in the capital and -2f/turn in other cities. So in 4 turns, all city tiles except capital have run dry of food. My capital city tile still has food in the attached savegame (first post) but is losing 4 food each turn and will soon be dry as well.

**Comment by LoneGazebo** [comment]
Event that causes food loss?

**Comment by Zuizgond** [comment]
Events are disabled.
