### ISSUE TITLE
India can build missionaries

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#7608]
_1. Mod version (i.e Date - 12/1):_
3/2/2021

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
India seems to be able to build missionaries.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Just confirming, these were true built missionaries and not the free ones from Borobadur?

**Comment by LukaSlovenia29** [comment]
Good question, Stalker, it's possible that its from Borobodur, but I can't verify that because they're on the other side of the map. I'll fire up a game as India and see if I can build normal missionaries.

**Comment by RecursiveVision** [comment]
Balance Changes
- India now gets 2 free Great Prophets from Borobudur instead of Missionaries
