### ISSUE TITLE
Deals automatically continue after expiring, sometimes invisibly

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#7609]
_1. Mod version (i.e Date - 12/1):_
March 2nd 2021

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Sometimes deal will automatically continue after expiring, sometimes visibly, sometimes invisibly. For example if I sell 5 iron to Mongolia for 50gpt, after the deal expires, there will be no visible deal, but my screen will show I'm exporting 5 iron and my GPT will actually be increased by 50. The only way to get out of the deal is for war to be declared by either side.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Make sure you give the AI a turn or two to renew.
