### ISSUE TITLE
great prophet won't spawn

### ISSUE THREAD

**Issue by texashunk18** [LoneGazebo/Community-Patch-DLL#761]
In several games I've had more than enough faith to spawn a great prophet, often twice as much, but they will not spawn. I notice at the same time that the AI cannot or does not found religions. 

I'm using no other mods than those included in the community balance patch project.

**Comment by LoneGazebo** [comment]
Hmm...interesting. Did you clear your cache after installation? Any other problems or obvious errors?

If you have logging enabled, post your database.log. If not, enable logging, start up a modded game, and then post your database.log.

G

**Comment by texashunk18** [comment]
I did clear my cache, also did a full reinstall of the whole game and community mods. The cache we are talking about is in the mygames/civ v right?

When I get enough time to play again I'll try the logging.

**Comment by texashunk18** [comment]
OK, I duplicated the great prophet problem and concurrently I noticed that I cannot improve tea resources even though the AI can make plantations. It won't let me load the log file so I copied and pasted it into word, hope that doesn't destroy the integrity of the file. 
![image](https://cloud.githubusercontent.com/assets/15802292/11100215/86a52060-8875-11e5-8079-a3c70e71c87d.png)
![image](https://cloud.githubusercontent.com/assets/15802292/11100217/8e4fffd8-8875-11e5-8c95-94d9d624434f.png)
[Database.docx](https://github.com/LoneGazebo/Community-Patch-DLL/files/32192/Database.docx)

**Comment by LoneGazebo** [comment]
You have a bunch of broken data files. Missing DLC? On latest version?
