### ISSUE TITLE
Wrong tooltip over upgrade button

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7610]
_1. Mod version (i.e Date - 12/1):_ 3-2

_2. Mod list (if using Vox Populi only, leave blank):_ pdans Powerplants

_3. Error description:_ 

I remember reporting this issue a while ago. It seems the issue is still there. Whenever I miss money for a unit upgrade, the tooltip shows some wrong text.

![20210323152208_1](https://user-images.githubusercontent.com/16341598/112153555-0d808000-8bec-11eb-83ba-25ca6f675832.jpg)

**Comment by LoneGazebo** [comment]
lua log?
