### ISSUE TITLE
[Feature] Ranged units can pillage tiles

### ISSUE THREAD

**Issue by Tonas1997** [LoneGazebo/Community-Patch-DLL#7612]
WHoward [created a modmod](http://www.picknmixmods.com/mods/CivV/Units/Ranged%20Pillage.html#) that allows for late-game ranged units to pillage tile improvement without yields, and I wonder if it could be integrated into VP. The necessary DLL functions have already been included in [this commit](https://github.com/LoneGazebo/Community-Patch-DLL/commit/6702f26274858f6f6eebdea69009a2347b271825).

### Why?

The capability for certain ranged units to pillage tile improvements would add more depth to the combat system, as it would be possible for improvements such as mines, manufactories and oil wells to be the target of airstrikes and artillery - such strategic strikes, aimed at crippling the opponent's war effort (production, strategic resources, forts...), have been a staple of warfare for decades.

### AI

The original mod lacks AI handling, so that would have to be added. Evidently, different improvements would have different priorities based on their usefulness to the war effort, distance, etc. A few ideas:

- Mines are important, specially the ones sitting on top of strategic resources (e.g. uranium mines are more important than iron).
- Citadels and forts should also be a priority, particulary if they are close to the front.
- Farms would be targeted if the goal is to... well, starve their enemy!
- Great tile improvements (Academy, Customs House) could be targeted depending on other factors (e.g. Academy if Science Victory is enabled, Holy Sites for Religious Victory...)

### Rules

- Empty tile improvements can be targeted by late-game ranged units - such as artillery and battleships - and aircraft. Doing so will result in the improvement getting pillaged, but without any yields for the attacking player (similar to the Civ 6 system)
- If there's a unit on said improvement, said unit absorbs the attack damage, just as with the current system.

**Comment by RecursiveVision** [comment]
@Tonas1997 As this affects balance, it should be discussed on the forums. (Sorry for the very late response)
