### ISSUE TITLE
3/2 - AI can override my Archeologists, but I cannot do the same.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7613]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So I have seen the AI in many games "trump" my archeologist. Meaning I start work on a dig in their land, they come in with their own archeologist and boot me out.

I was always fine with that, I figured it was fair play it being their land and all. However, I've finally had the chance to do it to the AI, and it turns out I can't. Once they start the dig I can't start on it myself.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/112228040-97d1df80-8bfe-11eb-926d-6c03d0862e52.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
They can, however, start digging your artifact while yours is working in your own land.

**Comment by Stalker012345** [comment]
What more info do you need?

**Comment by Stalker012345** [comment]
So was this actually fixed?

**Comment by LoneGazebo** [comment]
Working as intended, OB should not need to be mutual.

**Comment by Stalker012345** [comment]
This issue had nothing to do with Open Borders. Its the fact that an AI archeologist can literally come over to an artifact I am 1 turn away from finishing, start work....and completely kick me off the artifact!

And I cannot do the same. If I come over with my archeologist and try to boot them off, the dig button is greyout it. Its a complete double standard.

**Comment by LoneGazebo** [comment]
Well I've told the AI to ignore tiles where another archaeologist is already working, so let's _watch this in the next release_

**Comment by azum4roll** [comment]
Can you tell them to ignore tiles where a worker is already working on too? This is double standard too - human archeologists can't override AI workers doing improvements/chopping trees, but AI archeologists can override workers.
