### ISSUE TITLE
3/2 - Solar Power Confusing Description

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#7614]
_1. Mod version (i.e Date - 12/1): 3/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

When you build the Solar Power and use any process, besides giving you 20% more yield depending of what process you choose (for that yield) also it gives +20% more yields to food,gold,science,faith and culture (doesn't give the chosen process the bonus twice).

So the description should be more like:
"When using any of the processes you convert 20% of production to food,gold,science,faith and culture"

Is this intended or not?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Wealth process gives +20% science also to the other ones mentioned above**
![Civ5Screen0007](https://user-images.githubusercontent.com/49090452/112311738-b4c5eb80-8cae-11eb-9643-41d0f0363074.png)

**Comment by azum4roll** [comment]
Then it's actually really strong...

**Comment by LoneGazebo** [comment]
Unintended, and already fixed. :)
