### ISSUE TITLE
Glitched "automated action" buttons appearing on all units

### ISSUE THREAD

**Issue by Tonas1997** [LoneGazebo/Community-Patch-DLL#7617]
_1. Mod version: 12/1/3:_

_2. Error description:_ 

Every unit's pane displays repeated, non-functional "automated" buttons for diplomacy and archeology actions (?!?!), which might even end up stacking the action buttons on two rows. Unknown cause; if I remember correctly, this started happening mid-playthrough. 

Disabling all my mods apart from the Vox Populi suite confirmed the issue is being caused by it. Vanilla + VP-installed EUI also works fine.

Screenshot and logs:

![20210324215705_1](https://user-images.githubusercontent.com/43859708/112390707-9ed81b00-8cee-11eb-962e-f4e7a11d28d5.jpg)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6200774/Logs.zip)

**Comment by LoneGazebo** [comment]
>Disabling all my mods apart from the Vox Populi suite confirmed the issue is being caused by it. Vanilla + VP-installed EUI also works fine.

what other mods? Are you saying it works fine if just VP+EUI?

**Comment by Tonas1997** [comment]
I meant that the issue was being caused by VP/EUI, as turning off the rest of my mods didn't fix the glitch.

Reinstalling VP _did_ work, though. Feel free to close or keep the issue open!

**Comment by RecursiveVision** [comment]
Probably a bad install.
