### ISSUE TITLE
Building_GreatWorkYieldChanges and SecondReligionPantheon

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#762]
This has been a request I've delayed for how minor it is. However, because the next update to Piety will hopefully complete it, and because I've already a few requests (GreatPersonExpended, GreatWorkCreated) lined up for the next CP update, I thought now better than ever.

So, would it be possible to add a Building_GreatWorkYieldChanges, akin to the Policy_GreatWorkYieldChanges? This would be a global change to Great Work yields. This is an effect for the Hagia Sophia in Piety. Previously, I'd been using Policy_GreatWorkYieldChanges and a dummy policy, but this isn't ideal, as when the Hagia Sophia is captured, the effect doesn't transfer to the new owner (which I suppose historically makes sense, but still...)

Similarly, the Pantheon wonder in Piety affords the SecondReligionPantheon effect from the vanilla Religious Tolerance policy (the whole 'get the pantheon belief of the second largest religion') via dummy policy. Same issue. However, in this case, I'm not as fussed, as this wonder is primarily a throw-away keepsake for the effect and so is rarely constructed. So if you had to choose which of these two to do, the GreatWorkYieldChanges would be most useful. I ask only if it's easy enough to add in (which might not be the case), to wrap up some loose ends in Piety.

Thanks!

**Comment by LoneGazebo** [comment]
I'll give these a look, yep.
G

**Comment by LoneGazebo** [comment]
Alright, done. They're both player-level changes. That correct?

**Comment by JFDaly** [comment]
Yes, both player-level. Thank you.

**Comment by LoneGazebo** [comment]
All requests are in latest CP. Test and let me know if they work.
G

**Comment by JFDaly** [comment]
Yup, these work, as well as unit:greatperson(). Thanks again!
