### ISSUE TITLE
Bought units appearing adjacent to city, even if un-garrisoned

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#7620]
_1. Mod version (i.e Date - 12/1):_
March 2nd 2021

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
If I buy a unit in a un-garrisoned city, sometimes the unit will appear adjacent to the city instead of in the city, leaving the city vulnerable to attacks on that turn. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
cannot reproduce. the report says sometimes but it seems to be very rare.

**Comment by LukaSlovenia29** [comment]
Thanks for the reply.
