### ISSUE TITLE
Pillaged forts completely disappearing instead of looking pillaged in addition to allowing ships passage

### ISSUE THREAD

**Issue by SuperNoobCamper** [LoneGazebo/Community-Patch-DLL#7621]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_
 
![image](https://user-images.githubusercontent.com/20557080/112521917-b6bea600-8da5-11eb-962c-ec9d6a61a914.png)

_3. Error description:_ 
Pillaged forts disappear instead of pillaged yet allow ships passage.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Ships.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6206936/Ships.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![CivilizationV_DX11 2021-03-25 12-34-32-836](https://user-images.githubusercontent.com/20557080/112522092-e7064480-8da5-11eb-8570-cb41d8410ba6.jpg)

**Comment by azum4roll** [comment]
Pillaged forts always disappear. They shouldn't allow passage though.

**Comment by ilteroi** [comment]
#7580

**Comment by SuperNoobCamper** [comment]
> Pillaged forts always disappear. They shouldn't allow passage though.

It does not disappear on ilteroi's end; it's pillaged like a normal improvement

**Comment by ilteroi** [comment]
ok, turns out pillaging with the firetuner is not the same a pillaging with a unit

anyway, fixed. a flag was not reset when the fort improvement was replaced.

the disappearance when pillaged seems to be by design, there is a property for that: IsDestroyedWhenPillaged. on the other hand that apparently was meant for roads (judging from the code) but it's not used for roads. weird.

**Comment by SuperNoobCamper** [comment]
> ok, turns out pillaging with the firetuner is not the same a pillaging with a unit
> 
> anyway, fixed. a flag was not reset when the fort improvement was replaced.
> 
> the disappearance of the fort when pillaged seems to be by design, there is a property for that: IsDestroyedWhenPillaged. on the other hand that apparently was meant for roads (judging from the code) but it's not used for roads. weird.

so a pillaged fort is not repairable and instead it has to rebuilt?

**Comment by ilteroi** [comment]
yeah. although i'm totally open to changing this. make a poll on the forum if you want.
