### ISSUE TITLE
Iroquois ability functions incorrectly when playing without balance patch

### ISSUE THREAD

**Issue by TheBuggg** [LoneGazebo/Community-Patch-DLL#7625]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch **without** Community Balance Patch

_3. Error description:_ 
Play a game as the Iroquois. Leader ability: "Units move through Forest and Jungle in friendly territory as if they were Roads..."
What is expected: Units can move through forests in friendly territory as if they are roads.
What is observed: Units can move through forests in all territory as if they are roads.

**Comment by ilteroi** [comment]
doesn't have anything to do with balance patch? mismatch between description and code, i chose to fix the code :)
