### ISSUE TITLE
[Suggestion] Make Great Admiral be able to traverse ice

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7626]
In rare cases like this every Great Admiral that is born "naturally" in my capital will be cut out from my fleet until I research airlift tech. Would it be nice to let GA's travel through ice then?

![20210327045826_1](https://user-images.githubusercontent.com/16341598/112708254-a1d33700-8eb9-11eb-8fd8-5a9a80fe4dba.jpg)

**Comment by ilteroi** [comment]
i would rather try and make sure the spawn plot is sane
