### ISSUE TITLE
3/2 - Happiness UI not showing when I will get happiness for Growth

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7627]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The happiness UI shows an estimate of how my unhappiness and happiness will change when I grow. It used to tell me that my happiness will increase by 1 on growth (assuming it would of course). I am no longer seeing that in the UI, it never tells me I will gain a happiness even when I will.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/112735045-8eef4f80-8f17-11eb-8dde-e05772ee7d07.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I don't think it ever said that, did it?

**Comment by LoneGazebo** [comment]
Or rather, if it does, perhaps just in the happiness TT?

**Comment by Stalker012345** [comment]
Here is what the screen is supposed to look like. Now this is a much lower difficulty, and it seems to be working fine. Both on immortal, even when I'm growing and I am certain I will get a +1 happy, the UI is not telling me I will, so I'm not sure what the issue is.

![image](https://user-images.githubusercontent.com/20593976/112926504-25b73a00-90d9-11eb-9cbf-c23911be2a97.png)
