### ISSUE TITLE
Add a warning for randomized victory

### ISSUE THREAD

**Issue by EGA-SUPREMO** [LoneGazebo/Community-Patch-DLL#7629]
_1. Mod version (i.e Date - 12/1):_ 12/1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ If you disable some victory types like SV and activate randomized victory, when you reach atomic era, you could still get SV, but since SV is already disabled, nobody can't win(I think, I didn't try to finish the game)

some time ago I read that it's impossible to fix this bug, so I propose to add a warning for randomized victory and the victory types buttons, warning the user about this behavior.

_4. Steps to reproduce (optional):_ 
1. Disable CV, SV and DV
2. Enable Randomized Victory
3. Select atomic era as starting era
4. ???
5. profit

**Comment by RecursiveVision** [comment]
Do you mean that if Randomized Victories is on it can still select a manually disabled victory?

**Comment by EGA-SUPREMO** [comment]
Yes

**Comment by EGA-SUPREMO** [comment]
and from a game I played some years ago, SV was chosen, but I couldn't launch Spaceship parts because SV was manually disabled.

Not sure, if that still happens in this version thou
