### ISSUE TITLE
Peace trades- AI not taking into consideration all factors

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#763]
here's the scenario: AI is winning the war and i'm in the negative warscore. I have 192 gold in my treasury, and i'm making +4GPT. 3 turns after DOW she's ready to make peace, but she wants 50 gold from me because shes ahead. So, i close the trade dialogue, spent all my money on purchasing a Warrior, now i have 2 gold- i go back to make peace and let her make me an offer. Her proposal for peace this time was for me to include (0) gold pieces to her

she seems to be ignoring that i have something to give, my positive GPT cash flow. this is one example, but ive repeatedly noticed during peace deals the AI settles for far too little, im guessing because theyre only taking into consideration my current amount of raw cash?

**Comment by LoneGazebo** [comment]
Has the AI taken a city or two? If the AI is winning, it doesn't necessarily care about more stuff through the treaty.

G

**Comment by deadstarre** [comment]
no this was very early in the game, we were only in a war because I stole her worker. the AI was placing her ahead in warscore because her spearmen was in my territory. we both had 2 cities at that point, no city had been conquered anywhere in the game yet-  essentially we had just begun and were on as equal footing as possible for Deity.

**Comment by LoneGazebo** [comment]
I worked on this a bit for the latest version. Report back and let me know.
