### ISSUE TITLE
I can't choose any unit, or click menu

### ISSUE THREAD

**Issue by ohsuen** [LoneGazebo/Community-Patch-DLL#7630]
_1. Mod version (i.e Date - 12/1):_
3-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
( English is not my major language. so, my description couldn't be clear, and also it would be hard to read.  But, i need your help. )

I installed VP mod version 3-2 Eui included. and also i installed eui ( first, i installed only vp mod, but there was something glitch appeared. after i installed eui, some of problem was solved. ). I thought i followed its guidance, but there's something problem. i can't choose my own unit, and also i can't click menu button Which is on the top of the left side ( clicking esc work properly. ). without mod, in singleplay with vanila civ 5, eui work properly without any problem. is this the problem because i installed vp wrong? i just installed it with auto installer.

_4. Steps to reproduce (optional):_
![123123123123](https://user-images.githubusercontent.com/81545748/112785508-17dcc700-908f-11eb-88cf-8639cad2bcaa.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Padre19** [comment]
Delete VP Mods. Delete EUI dlc. Install just Vp eui.

**Comment by ohsuen** [comment]
> Delete VP Mods. Delete EUI dlc. Install just Vp eui.

oh... i cleared mods folder, and deleted txt and ui_bc folder. i deleted all of them, and i tried i again. unfortunately it didn't work...

**Comment by ohsuen** [comment]
> Delete VP Mods. Delete EUI dlc. Install just Vp eui.

oh my. i solved it. what a stupid. thanks.
