### ISSUE TITLE
Stonehenge doesn't guarantee a Pantheon on Marathon gamespeed

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7631]
InstantYieldPercent is 200 and FaithPercent is 300; that's why.

I received a complaint about this, and I do think the intent of the Wonder was to give an instant pantheon, so @LoneGazebo - balance is your purview :)

**Comment by RecursiveVision** [comment]
It was noted that if the Faith yield was increased by 10 to 60 then it would let you instantly found on all game speeds.

**Comment by LoneGazebo** [comment]
IIRC stonehenge text states a flat amount of faith, so I think it is fine.

**Comment by RecursiveVision** [comment]
That greatly reduces the utility of Stonehenge on lower difficulties, since costs do scale. The text could be changed :)

**Comment by LukaSlovenia29** [comment]
I agree with Recursive, I wish Stonehenge gave as much faith as need for a pantheon on that particular gamespeed.
