### ISSUE TITLE
3/2 - Side Notification does not show Progress Instant Culture for faith buying Buildings

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7632]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I just built a cathedral and synogogue in Sanchu using Faith. Though I got 60 culture from Progress (and I checked the culture numbers to make sure), the notification on the right only shows the instant yield for the granary, not the progress yields.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/112882729-f382e980-9092-11eb-9615-624ca5c6bc97.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
I see multiple yield icons on right...

**Comment by Stalker012345** [comment]
> I see multiple yield icons on right...

I checked them all. Believe me I just did an exercise where I meticulously tracked every single instant yield from this city for over 100 turns (yes its as arduous as it sounds). The progress (and industry it turns out) bonus yields are not being shown in the notifications, but are being generated.
