### ISSUE TITLE
GetCompetitiveSpawnUnitType is broken

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7634]
sometimes it doesn't find any unit type. that seems to happen because CvPlayer::canTrain() is a mess. does anyone understand how it is supposed to work?

**Comment by RecursiveVision** [comment]
I haven't looked at that code in a while, but it's...yeah. I see you did some cleanups already.

@ilteroi Also Github Desktop added a cherrypick feature so I'll be using that from now on instead of manual merges. :)

**Comment by ilteroi** [comment]
well aaaactually cherrypicking is plan B when rebasing fails :)
