### ISSUE TITLE
AI too aggressive at denouncing (former) friends

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#7636]
_1. Mod version (i.e Date - 12/1):_
March 2nd 2021

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm seeing a lot of early backstabbing due to denouncing friends, so perhaps that's something to look at? I can hardly imagine a good reason to not be able to wait 10 turns before denouncing (afaik, you need to wait 10 turns before denouncing if you discontinue the DoF prematurely) worth incurring a backstabbing diplo penalty? 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
A save file one turn before the denouncement is necessary.

**Comment by RecursiveVision** [comment]
@LukaSlovenia29 If you can manage it, a save file from one turn before the DoF was ended early would also be appreciated. I suspect something's wrong with that memory value.

**Comment by R3P0FFXI** [comment]
@RecursiveVision you may want to check the hate list regarding technology competition I've noticed this is incredibly high amongst all games I've played.

**Comment by LukaSlovenia29** [comment]
Recursive, I have the files, but Github says "We don't support that file type". Do you want me to post them on civfanatics and post a link here?

**Comment by RecursiveVision** [comment]
@LukaSlovenia29 just .zip them up

**Comment by RecursiveVision** [comment]
@R3P0FFXI Elaborate?

**Comment by LukaSlovenia29** [comment]
[Terran Prime_0063 BC-1480.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6250325/Terran.Prime_0063.BC-1480.zip)
T63 is the turn before denouncement, T64 is the turn when I was denounced by Babylon. If you need any logs or other save files, let me know.

**Comment by RecursiveVision** [comment]
@LukaSlovenia29 I will check this out 👍

**Comment by R3P0FFXI** [comment]
> @R3P0FFXI Elaborate?

@RecursiveVision 

![Civ Anger1](https://user-images.githubusercontent.com/10148511/113463067-f0209280-93f1-11eb-84f4-4341156e2193.jpg)
![England](https://user-images.githubusercontent.com/10148511/113463079-f3b41980-93f1-11eb-84b2-b5fe6713792a.jpg)
![Demark](https://user-images.githubusercontent.com/10148511/113463118-1b0ae680-93f2-11eb-9d32-4939d3e8de9b.jpg)
![Aztecs](https://user-images.githubusercontent.com/10148511/113463156-4e4d7580-93f2-11eb-9a89-95bf0c735863.jpg)
![Spain](https://user-images.githubusercontent.com/10148511/113463190-78069c80-93f2-11eb-81f1-1f198d700c41.jpg)
![America](https://user-images.githubusercontent.com/10148511/113463223-a7b5a480-93f2-11eb-8eeb-8f154c20bd59.jpg)


![Map](https://user-images.githubusercontent.com/10148511/113463248-ccaa1780-93f2-11eb-97f8-122f193405bc.jpg)

**Comment by RecursiveVision** [comment]
@LukaSlovenia29 Works as intended. Babylon denounced you because his approach had shifted to Hostile, and he seems to have adequate reason for it (early game territory dispute). Denouncing a friend doesn't make you automatically untrustworthy with the new system.

He denounced while still friends, so it's not an issue with the 10 turn timer.

@R3P0FFXI I don't see a problem here. You need to watch global politics and avoid befriending people that everyone hates. Your friendships with Indonesia and Rome appear to be straining relations. You also founded different religions, so there's aggression from that.

**Comment by RecursiveVision** [comment]
I did find a couple issues with the denouncement code on a second pass. Made some adjustments.

**Comment by LukaSlovenia29** [comment]
Thanks, looking forward to seeing how the adjustments will work! In the last few versions or at least in this version I'm not seeing "We can't be friends anymore" messages from the AI, discontinuing the DoF prematurely, something that was fairly common in the past. The AI used to discontinue the DoF when they became unhappy with your, now they seem to go straight for the denouncement. In any case, I hope my report helped.

**Comment by RecursiveVision** [comment]
You don't see that at all? Hrm. That shouldn't happen.

**Comment by R3P0FFXI** [comment]
@RecursiveVision I do tend to avoid befriending people everyone hates. The issue is the AI changes friendships and you seem to get stuck. I have been friends with someone for 400-500 years if not longer then all of a sudden they hate you because of something behind the scenes with the AI. The other issue is I can stop being friends with everyone and the hate decay never seems to happen. Once an enemy hates you they always seem to hate you. I can give Money, Resources, Land etc. Nothing changes they will never be friends with you again.

**Comment by RecursiveVision** [comment]
@R3P0FFXI I made a few adjustments to this, let's see how it performs in the next version.

**Comment by R3P0FFXI** [comment]
Understood @RecursiveVision I am awaiting the next beta release 🥇

**Comment by LukaSlovenia29** [comment]
> 
> 
> You don't see that at all? Hrm. That shouldn't happen.

Nope, I don't think I've seen it in any of my games with the latest version. Perhaps something to ask other people on civfanatics if they've seen it.

**Comment by RecursiveVision** [comment]
I wonder if I could just add a "don't count if the friendship/denouncement has only been for less than 3-5 turns" check.

**Comment by LukaSlovenia29** [comment]
> 
> 
> I wonder if I could just add a "don't count if the friendship/denouncement has only been for less than 3-5 turns" check.

That might work. In any case, I like how it was for a long time: the AI became unhappy with you and either waited for the DoF to expire naturally and then denounce you/DoW you or he'd use the diplomatic option to end the DoF, then wait 10 turns to denounce or attack. Only in very exceptional circumstances did the AI backstab you. Also, while I can see some situations where it's beneficial for the AI to backstab you by DoW-ing you (to actually catch you off guard and take a city or two), I can't imagine a situation where the AI would be in a hurry to denounce you, i.e. where it'd be worse off it waited for 10 turns so it could denounce you without backstabbing.

**Comment by RecursiveVision** [comment]
@LukaSlovenia29 Ah, I see what you're saying now. I misunderstood.

**Comment by RecursiveVision** [comment]
@LukaSlovenia29 I think I found what was causing the AI to get so aggressive; it was indeed a bug (a major one at that). It should be fixed in the new version.

**Comment by LukaSlovenia29** [comment]
That's great to hear, I'm glad you found it! Thanks for letting me know, looking forward to the next version!
