### ISSUE TITLE
(Logging Assistance) Capturing Civ Science/Culture/Instant Science/Instant Culture

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7638]
_1. Mod version (i.e Date - 12/1):_
(Request)

Modders,

I am requesting a very simple log that would save me tremendous effort in doing some game analysis. I could use a log that collects the following numbers.

1) Turn Number
2) Total Civ Science
3) Total Civ Culture
4) Instant Civ Science
5) Instant Civ Culture

So looking at this screenshot, the log should capture the following.

![image](https://user-images.githubusercontent.com/20593976/113191808-9bc7b800-9223-11eb-95ad-11757e501ffa.png)

1) 317
2) 1115
3) 1969
4) 2119
5) 2807

I would greatly appreciate the help.
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by inkyant** [comment]
I made this, it prints to the lua logs those numbers in the order you posted.
One thing is that unfortunately the culture per turn rounds up so it may be off by one. The science is exact. 
[Yield Logs (v 1).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6241362/Yield.Logs.v.1.zip)

**Comment by inkyant** [comment]
This should print those values to the lua.log
The culture is rounded up.
[Yield Logs (v 1).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6244921/Yield.Logs.v.1.zip)

**Comment by Stalker012345** [comment]
Just gave this a go, looks like its working perfectly. Thank you so very much!!!!

**Comment by Stalker012345** [comment]
Damn, I spoke too soon, its actually not tracking the instant culture.

![image](https://user-images.githubusercontent.com/20593976/113457775-4bdd2280-93d6-11eb-8747-af04e4bc1924.png)

**Comment by inkyant** [comment]
In this case I'm pretty sure the "Culture: 20" means you've gotten 20 instant culture in the last ten turns. So just to make sure, the 20 culture never went in the logs? (I'm assuming you only want the instant culture gained that turn, though I could have it be from any time). And it's working for science?

**Comment by Stalker012345** [comment]
I guess your right that the per turn instant culture would be even better, so that would be preferred. So I took another look at the log must later, and it does seem to tracking science. As for culture, the number is close but not the same as the UI.

![image](https://user-images.githubusercontent.com/20593976/113469438-068b1600-9413-11eb-9cf7-3dd6e9086a3c.png)

**Comment by inkyant** [comment]
That's very strange, because it literally just gets the string for that UI that you are using, but only for the past turn. (pPlayer:GetInstantYieldHistoryTooltip(1)). It would be one thing if it didn't detect the yield but the fact that it does detect it, but slightly off, and that science works?

Maybe try running this version and show me the logs? It should print the whole tooltip and then also the section it detects.
Or send me the save.
[Yield Logs (v 1).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6252006/Yield.Logs.v.1.zip)

**Comment by Stalker012345** [comment]
Ok, so with the new log it is working if you parse it out right. With this line:

[ICON_RESEARCH] [COLOR_BLUE]Science[ENDCOLOR]: 183 [NEWLINE]        [ICON_BULLET] This Turn: +75

That +75 value is accurate.

However, there is one other snag. The log is capturing the instant yields at the very beginning of the turn, but instant yields generated during the turn (such as bank science when you purchase something), is not captured.

Is there a way to run the log update when the end turn button is pressed? If all of that is too challenging, I can go back to the 10 turn numbers and use those. Having the exact number every turn is wonderful, but I would rather take the 10 turn average and use that then to flat out leave instant yields on the table.

**Comment by inkyant** [comment]
That's a good point. The function for after a player's turn ends isn't very good but I was able to use it for this case.
Check if maybe now it will be more accurate?
[Yield Logs (v 1).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6255057/Yield.Logs.v.1.zip)

**Comment by Stalker012345** [comment]
So the per turn instant culture number its giving me is 45, instead of 0 (and I did write down the numbers from last turn to check). I'm guessing the instant science is probably off too.

![image](https://user-images.githubusercontent.com/20593976/113525239-5edc2800-9579-11eb-8807-d985c7246195.png)

We could go back to the longer string you gave me before and do it after the turn like you have now, I should be able to parse from it what I need.

**Comment by inkyant** [comment]
Ok, I realized a few issues with the code that made it get the incorrect turn, also I was testing it wrong in some cases :p.
I swear this time it should work.
If it doesn't you can uncomment (delete the "--" from) lines 55, 61, and 68, which will print the longer string
[Yield Logs (v 1).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6256325/Yield.Logs.v.1.zip)

**Comment by Stalker012345** [comment]
Ok so I've taken several readings periodically through my recent game and checked them with the logs. Everything looks spot on now so I think we are good here.

@inkyant , thank you so very much for this, I am already putting it to work and its already saving me time. It is a big help!
