### ISSUE TITLE
CTD during AI turn 11/5 version

### ISSUE THREAD

**Issue by aht820** [LoneGazebo/Community-Patch-DLL#764]
Gazebo,

I'm getting a CTD during the AI turn with the 11/5 version. My log file is linked below. I'm using all the full version with EUI as well as IGE, rotate starting positions, and Whowards' cheap workboats. 

https://www.dropbox.com/sh/wt0qltggdcatlqa/AABOMr-q5HGIFNynKOWq2hpYa?dl=0

**Comment by aht820** [comment]
I had another crash in a new game. This one occurred at the start of a turn after I received a great writer. When i reload the game it crashes after I click begin your journey. Files are separated in the folder that is linked above.

**Comment by LoneGazebo** [comment]
I'll take a look. Did you rotate starting positions?

**Comment by aht820** [comment]
Yes

**Comment by LoneGazebo** [comment]
I looked into this and it pushed into disassembly. If it happens again, let me know.
