### ISSUE TITLE
Invisible Caravan/Cargo Ship

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#7642]
_1. Mod version (i.e Date - 12/1): 3/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

Issue #6737 still not solved. They seem to become invisible as soon as they enter the target city (in your empire).

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Ah, but the Third Hallow is a _true_ cloak of invisibility, Miss Granger! I mean to say, it is not a travelling cloak imbued with a Disillusionment Charm, or carrying a Bedazzling Hex, or else woven from Demiguise hair, which will hide one initially but fade with the years until it turns opaque. We are talking about a cloak that really and truly renders the wearer completely invisible, and endures eternally, giving constant and impenetrable concealment, no matter what spells are cast at it. How many cloaks have you ever seen like _that_, Miss Granger?
