### ISSUE TITLE
3/2 - No diplomatic penalty for stealing land with a citadel

### ISSUE THREAD

**Issue by IskarJarak01** [LoneGazebo/Community-Patch-DLL#7643]
[3_2_Citadel_No_Diplomatic_Penalty.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6244063/3_2_Citadel_No_Diplomatic_Penalty.zip)

_1. Mod version (i.e Date - 12/1): 3/2

_2. Mod list (if using Vox Populi only, leave blank): A custom modpack loaded as DLC. I can provide a Google drive link to this modpack (too large to attach here):
!Clock Tower Building (v 1)
(1) Community Patch (v 94)
(2) Community Balance Overhaul (v 13)
(3) City-State Diplomacy Mod for CBP (v 28)
(4) C4DF - CBP (v 11)
(5) More Luxuries - CBO Edition (5-14b) (v 155)
(6a) Community Balance Overhaul - Compatibility Files (EUI) (v 1)
(7) Community Events (v 5)
(7a) Promotion Icons for VP (v 3)
(7b) UI - Promotion Tree for VP (v 22)
(9) Wonders Expanded (v 2)
(over) More Unique Components for VP (v 65)
(ui) City-States Leaders for VP (v 10)
(ui) Trade Opportunities for VP (v 11)
(ui) Wonder Planner for VP (v 8)
[BNW] Colonialist Legacies' Tlingit for VP (v 17)
Archaeology Aesthetic Adjustments (v 1)
Calypso's Colored Religion Icons (Basic) (v 1)
Casino for VP (v 1)
Cemetery Building 4VP (v 1)
Civ Names by Policies (v 8)
Colonialist Legacies' Canadian Dominion for VP (v 19)
Colonialist Legacies' Inuit for VP (v 16)
Colonialist Legacies' Philippine Republic for VP
Enhanced Naval Warfare for Vox Populi (v 2)
GMO Lab for VP (v 1)
JFD's Civilizations - Great Britain (Victoria) for Vox Populi (v 5)
JFD's Civilizations - Japan (Meiji) for Vox Populi (v 3)
JFD's Civilizations - Japan (Tojo) for Vox Populi (v 9)
JFD's Civilizations - Papal States (Pius IX) for Vox Populi (v 8)
JFD's Civilizations - Prussia (Frederick) for Vox Populi (v 9)
JFD's Civilizations - United States of America (Roosevelt) for VP (v 7)
Krajzen's Great Writers Pack (v 1)
Leadership Reformation (v 4)
MC and LITE's Nubia for VP (v 15)
MC_s Greece and Macedon Split for VP (v13)
Parks for Vox Populi (v 2)
Polar Station for VP (v 1)
Promotion Flags EUI (v 1.1)
Quick Turns (v 10)
Randomize City Names (v 2)
Ski Resort Building for VP (v 2.1)
Sukritact's Khmer Civilization for VP (v 10)
Tomatekh's Sumer for VP (v 21)
Tomatekh's Timurids for VP - 4UC Compatible (v 12)
UI - Improved City View (Vox Populi EUI) (v 11)
UI - Religion Spread (Vox Populi) (v 1)

Some mod-added civs (not present in the bugged savegame) and Quick Turns broke after making the modpack and I didn't bother tracking down the error.

_3. Error description: No diplomatic penalty with an AI for stealing their land with a citadel. The leader dialogue still plays, but no diplomatic penalty with them ever appears.

**Comment by RecursiveVision** [comment]
Too many other mods, sorry.
