### ISSUE TITLE
3/2 - All workers and great people become faith units after building Borobudur

### ISSUE THREAD

**Issue by IskarJarak01** [LoneGazebo/Community-Patch-DLL#7644]
[3_2_Borobudur_Faith_Unit_Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6244058/3_2_Borobudur_Faith_Unit_Bug.zip)
3/2 - All workers and great people become faith units after building Borobudur

_2. A custom modpack loaded as DLC. I can provide a Google drive link to this modpack (too large to attach here):
!Clock Tower Building (v 1)
(1) Community Patch (v 94)
(2) Community Balance Overhaul (v 13)
(3) City-State Diplomacy Mod for CBP (v 28)
(4) C4DF - CBP (v 11)
(5) More Luxuries - CBO Edition (5-14b) (v 155)
(6a) Community Balance Overhaul - Compatibility Files (EUI) (v 1)
(7) Community Events (v 5)
(7a) Promotion Icons for VP (v 3)
(7b) UI - Promotion Tree for VP (v 22)
(9) Wonders Expanded (v 2)
(over) More Unique Components for VP (v 65)
(ui) City-States Leaders for VP (v 10)
(ui) Trade Opportunities for VP (v 11)
(ui) Wonder Planner for VP (v 8)
[BNW] Colonialist Legacies' Tlingit for VP (v 17)
Archaeology Aesthetic Adjustments (v 1)
Calypso's Colored Religion Icons (Basic) (v 1)
Casino for VP (v 1)
Cemetery Building 4VP (v 1)
Civ Names by Policies (v 8)
Colonialist Legacies' Canadian Dominion for VP (v 19)
Colonialist Legacies' Inuit for VP (v 16)
Colonialist Legacies' Philippine Republic for VP
Enhanced Naval Warfare for Vox Populi (v 2)
GMO Lab for VP (v 1)
JFD's Civilizations - Great Britain (Victoria) for Vox Populi (v 5)
JFD's Civilizations - Japan (Meiji) for Vox Populi (v 3)
JFD's Civilizations - Japan (Tojo) for Vox Populi (v 9)
JFD's Civilizations - Papal States (Pius IX) for Vox Populi (v 8)
JFD's Civilizations - Prussia (Frederick) for Vox Populi (v 9)
JFD's Civilizations - United States of America (Roosevelt) for VP (v 7)
Krajzen's Great Writers Pack (v 1)
Leadership Reformation (v 4)
MC and LITE's Nubia for VP (v 15)
MC_s Greece and Macedon Split for VP (v13)
Parks for Vox Populi (v 2)
Polar Station for VP (v 1)
Promotion Flags EUI (v 1.1)
Quick Turns (v 10)
Randomize City Names (v 2)
Ski Resort Building for VP (v 2.1)
Sukritact's Khmer Civilization for VP (v 10)
Tomatekh's Sumer for VP (v 21)
Tomatekh's Timurids for VP - 4UC Compatible (v 12)
UI - Improved City View (Vox Populi EUI) (v 11)
UI - Religion Spread (Vox Populi) (v 1)

Some mod-added civs (not present in the bugged savegame) and Quick Turns broke after making the modpack and I didn't bother tracking down the error.

_3. Error description: Immediately after building Borobudur, all workers and great people were flagged as faith units with a strength of 0. All future workers/ great people also became faith units, however they all still functioned normally.

**Comment by SuperNoobCamper** [comment]
Can confirm, i encountered the same "bug" in my normal installation without any custom civs.
