### ISSUE TITLE
MapTrading Request

### ISSUE THREAD

**Issue by Jamforce** [LoneGazebo/Community-Patch-DLL#765]
Could you make MapTrading available even without using C4DF? I dont think that his original author (Putmalk) would be contrary, considering also that part of the code is already present in the vanilla DLL. This would be a nice feature for people like me who play on huge maps, and it's just a matter of changing a few preprocessor directives. 

Also taking advantage of your kindness, could you add a "MaxDistance" column to the "Building_YieldFromDeath" table? So that would be possible to create local graveyards.

**Comment by LoneGazebo** [comment]
You'd need the lua for it, as well as the defines, all of which are bundled with C4DF. It'd be a lot of dismantling.

You can disable tech trading and vassalage, which pretty much leaves you with just map trading as C4DF features. Why not do this?

I'll look at _YieldFromDeath table, but I try to avoid distance calls as a performance measure. We'll see.

G
