### ISSUE TITLE
Guided Missile CTD

### ISSUE THREAD

**Issue by DeAnnoCiv** [LoneGazebo/Community-Patch-DLL#7650]
_1. Mod version (i.e Date - 12/1):_
3-2 (Most recent hotfix I think?)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Attacking with a Guided Missile seems to produce a CTD. I haven't experimented much but there is a set way of causing a CTD that seems to be reliable.

_4. Steps to reproduce (optional):_
Load the save provided in the zip. The save is an autosave, so let the start of turn happen and just ignore the million alerts that go off. Once they're done spazzing out, go to the southern area of the main continent, on the front with the Iroquois. Select the Guided Missile in Helsinki. Fire it at the Iroquois Rifleman holding the strait, as indicated on the linked picture (both are circled in purple.) The game should immediately crash to desktop.

https://i.imgur.com/43jWfZl.png

---------------------------
[GuidedMissileCrash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6253724/GuidedMissileCrash.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6253727/Logs.zip)

**Comment by ilteroi** [comment]
i think this is fixed already? in the mean time turn off combat animations ...
