### ISSUE TITLE
AI economy fail

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7651]
they are in a hole they cannot get out of.

![image](https://user-images.githubusercontent.com/1358966/113500506-c87b1880-951e-11eb-9720-12d3010760f2.png)

bonus question: is there a rational explanation for the resource consumption? how can they be at -22 iron?

**Comment by Stalker012345** [comment]
Do they have autocracy? If they have double strategics, but the ones in red were pillaged (which 12 pillage would actually equal 24 to this player), that could in theory do the job.

**Comment by ilteroi** [comment]
what could be helpful: maybe puppets should not build anything that costs maintenance if the owner is running a deficit?

**Comment by RecursiveVision** [comment]
@ilteroi you can't trade a city except for a city anymore, though? you changed it :)

**Comment by ilteroi** [comment]
damn! but it would be difficult to.find a buyer with enough money anyway

**Comment by Vyyt02** [comment]
I thought I messed something up in my kiddos, but this is typical in my games.

When I check with IGE, starting roughly in Modern era, most AIs have huge deficits of strategics and run around with obsolete units. No idea what they used the strategics on, does not seem to be units.

**Comment by azum4roll** [comment]
How they are having 66 Rocket Artillery is a bigger problem...
