### ISSUE TITLE
gold tooltip is wrong

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7652]
![image](https://user-images.githubusercontent.com/1358966/113503112-0fbdd500-9530-11eb-8f50-e7f80fe753fe.png)

these numbers don't add up ... probably the process yield should be added after the trade yield, that would be close at least.

**Comment by psparky** [comment]
I think you are correct and the small remaining difference is because the number from the process is shown rounded down, but you actually get the fractions based on your total production.

**Comment by ilteroi** [comment]
changed the lua
