### ISSUE TITLE
3/2 - Culture Overview summary thinks artifacts are artists

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7653]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Minor bug. In the culture overview screen, when you hover over your number of great works, it notes 2 artists in the example, but the city actually has 2 artifacts.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/113517966-c3cb5a00-9548-11eb-83a4-e5d6bc4088a6.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
art/artifacts are interchangeable. That's just a UI text typo thing
