### ISSUE TITLE
Vassal destroying trade routes

### ISSUE THREAD

**Issue by youngsteve11** [LoneGazebo/Community-Patch-DLL#7656]
_1. Mod version (i.e Date - 12/1):_2/3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ My vassal Morocco, who I have had for ages, has been constantly robbing my trade routes. Usually it says barbs have robbed it, even though none have been around for 100's of turns & always near Morocco territory. Last go it names Morooco of robbing trade route, but I cannot do anything about it, & don't know why. Have DOF & open borders with him. Recursive asked to send save previously which I will do from previous turn
[AutoSave_0839 AD-1820.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6255467/AutoSave_0839.AD-1820.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@youngsteve11 Fixed, but please note down if you're using other mods next time :)

**Comment by youngsteve11** [comment]
That was quick. Do you know what caused it as haven’t seen it before. What it to do with Morocoo. 

 

Regarding mods, the only one I use except standard is infoaddict. Never sent one of thee requests before so all new to me.

**Comment by RecursiveVision** [comment]
See part 2 of the issue template. InfoAddict affects savegame format so you can't load a game which has it unless you install and run it too.

The bug was annoyingly simple, there were two different checks which identified potential trade routes to plunder. One of them wasn't checking to see if the trade route owner was a bad target. So I copied the check over.

**Comment by ilteroi** [comment]
really? i cannot load other people's saves because of infoaddict? how long has this been known? i've been despairing over this at times ...

**Comment by RecursiveVision** [comment]
@ilteroi It won't let you load a save that doesn't have all required mods installed. Clicking on the MODS button will then tell you which mods in that savegame affect savegame compatibility.

However, I've still had instances where I had all required mods and upon loading the save the game still crashed.

**Comment by ilteroi** [comment]
i thought UI mods are optional. but what you wrote above about infoaddict affecting savegame format makes sense, in a twisted firaxis kind of way.

**Comment by RecursiveVision** [comment]
@ilteroi UI mods yes, but InfoAddict isn't just a UI mod, it stores data across turns.
