### ISSUE TITLE
AI not interrupting construction of wonders during early war

### ISSUE THREAD

**Issue by corps-of-discovery** [LoneGazebo/Community-Patch-DLL#7657]
_1. Mod version:_
3/2/2021

_2. Mod list (if using Vox Populi only, leave blank):_
- 3/4 UC
- PDan’s new beliefs
- UI - List enhancements
- UI - Trade opportunities
- UI - Filters in trade route overview 
- UI - Improved city view
- UI - Top panel replace
- Better Lakes
- Gibraltar, Reef, Krakatoa fix
- Diplomacy responses extended
- Historical Religions Complete
- Capture great people for VP
- Really advanced setup
- Community Events
- Promotion flags

_3. Error description:_ 
During an ancient era rush war, in three separate games the AI continued building a World Wonder even though I was on the verge of capturing their capital (at the time, their only city). A human player at this point would almost certainly have switch to producing units, defense, or walls.

1st instance: India building Pyramids
2nd instance: Mongolia building Stonehenge
3rd instance: Mongolia (again) building Pyramids

_4. Steps to reproduce (optional):_
Uncertain, but this is likely reproducible by rushing a civ that is building an ancient era wonder. I only remember seeing this problem before the AI founds a second city, so it may be related to that.

**Comment by RecursiveVision** [comment]
@ilteroi I believe you did some work on this just now?

**Comment by ilteroi** [comment]
yes

**Comment by ilteroi** [comment]
should reconsider now if their city is damaged
