### ISSUE TITLE
CTD when opening the tech tree.

### ISSUE THREAD

**Issue by Cyclopia31** [LoneGazebo/Community-Patch-DLL#7659]
_1. Mod version (i.e Date - 12/1):_
Version 3-2

_2. Mod list (if using Vox Populi only, leave blank):_
Only Vox Populi with EUI, but in a modpack (even if it is a solo game). I disabled bribed war and both victories competition. Here my modpack: 

https://www.transfernow.net/dl/20210405CUwono9Y

_3. Error description:_ 
Random CTD but always when I open the research screen (tech tree), start ~ turn 250 (normal speed), then happen again randomly. I have this problem since fews patch now in all my games.

4. Steps to reproduce (optional):_
I tried to open/close the tech tree in a loop, but I couldn't reproduce the crash using this way. I have to play normaly and suddenly, in the middle of nowhere, when I open the tech tree to pick a new research I got an instant CTD. When I load again the save I don't have the CTD again when I open the tech tree to chose a new research.
Sadly I think it is hard to reproduce, but I have also the same problem on my other PC.
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"): 
[logs_CTD_researchtree.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6260004/logs_CTD_researchtree.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Autosave_CTD_researchTree.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6259989/Autosave_CTD_researchTree.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[dmp_CTD_researchtree.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6259995/dmp_CTD_researchtree.zip)

4. Screenshots (optional):
5.Good luck and thank you from France for all your work !

**Comment by RecursiveVision** [comment]
Probably the game is running out of memory, especially if you're using other mods. This can't be fixed, but autosaving frequently (game options) and reloading to the last save seems to help.

**Comment by Cyclopia31** [comment]
I see, sad story.
Thank you for the reply ! 
Who know, maybe, one day, firaxis will release a 64 bits version of Civ 5 ! (I know I dream too much :/)
