### ISSUE TITLE
Embassy not connecting strategic resources- problem later on

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#766]
Built an embassy early game, late game found out it was on top of a Coal resource. I citadel the CS land to get the coal, only to find out embassy wouldn't connect it to my trade network, and also that embassy is not a replaceable improvement

**Comment by LoneGazebo** [comment]
Embassy should connect coal. What version are you on?

**Comment by deadstarre** [comment]
the 11/5 release. Perhaps its connecting for the city states, to give to their allies but if a player annexes the tile with citadel, they don't work for players? i'm not sure, i just know i have 3 coal in the Red and not available for the city that owns that tile

**Comment by LoneGazebo** [comment]
Ah, I see what you are saying now, you own the embassy that you (or someone else) had placed there. That's an interesting scenario. If it isn't fixed in the latest version, let me know and I'll take a look.

**Comment by deadstarre** [comment]
probably the odds of placing it on coal arent going to happen anytime soon again hehe but if it comes up i'll let you know. side note- it was my own embassy that i annexed, and when it came into my lands i lost the associated congress vote it had previously granted me. im guessing that means if i annex an embassy placed by another player, they'd lose their vote too. super obscure cheese

**Comment by LoneGazebo** [comment]
If you see it again, let me know.

G

**Comment by LoneGazebo** [comment]
Closing issue for now, but if it happens again feel free to reopen.

**Comment by Radost** [comment]
Isn't it required to have some sort of elevated privileges, in order to re-open issues closed by the project owner?
I can't reopen my issues, or at least don't know how.

**Comment by LoneGazebo** [comment]
Not sure - JFD opens and closes his, as do others. In any case, I can reopen this if we need to.

**Comment by Radost** [comment]
I checked all his 37 issues and the only case of re-opening was the one when he closed the issue by himself to begin with.
If you close an issue, it cannot be re-opened by the OP.

**Comment by LoneGazebo** [comment]
Makes sense, I guess.
