### ISSUE TITLE
weird vision from pledge of protection?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7660]
![image](https://user-images.githubusercontent.com/1358966/113670399-5c7ee880-96b5-11eb-97cf-cd8d1676a6bd.png)

where does the tile visibility come from here? is that from the pledge of protection? but why only on some tiles?

![image](https://user-images.githubusercontent.com/1358966/113670518-846e4c00-96b5-11eb-948f-34ae25b882f6.png)

![image](https://user-images.githubusercontent.com/1358966/113670735-c7302400-96b5-11eb-9978-b0e0b51f7aaa.png)

**Comment by Padre19** [comment]
from friendly or allied status

**Comment by bentakacs** [comment]
Do you have a Trade Route passing nearby?

**Comment by RecursiveVision** [comment]
Are you playing as Portugal? Feitoria is supposed to give vision...although I don't see one there.

**Comment by ilteroi** [comment]
hmm. might be trade routes but still very strange.

**Comment by LoneGazebo** [comment]
Corporation? One gives vision on TRs.

**Comment by azum4roll** [comment]
Happened to me some versions ago too. I got vision on random tiles.
