### ISSUE TITLE
puppet culture from process?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7661]
![image](https://user-images.githubusercontent.com/1358966/113695849-9e1d8c80-96d1-11eb-9a00-1cc7e2045863.png)

what is the intended behavior here, should the culture output from the arts process count?

it does seem to count for other processes. but is the display wrong or is culture an exception?

**Comment by LoneGazebo** [comment]
It counts here, it is part of the 34 total. 34 x .2 (i.e. -80%) = 6.8, or 6 rounded culture per turn. It's an issue with the TT formatting because of where the LUA and the C++ 'UI' stuff interact.

**Comment by ilteroi** [comment]
well i just changed the tooltip because for all other yields the process output is added after the modifiers.

**Comment by LoneGazebo** [comment]
Hmm. Perhaps culture is messed up in that respect then

**Comment by ilteroi** [comment]
fixed, culture and faith were treated differently from the rest
