### ISSUE TITLE
Not the best tactical AI

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#7663]
_1. Mod version (i.e Date - 12/1):_
March 2nd 2021

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Not an error per se, but suboptimal tactical AI in two instances: in the first one, a Songhai Field Gun remained in range of my city Halab, allowing itself to be destroyed, instead of retreating to safety; in the second one, a Songhai Fusilier attacked my Lancer north of Halab, allowing its health to be reduced enough so it would be destroyed the next turn. Not sure what the tactical AI was "thinking" here, because it never really tried to overwhelm Halab en masse, so it didn't make sense for it to sacrifice its units like this. Also, the AI could have done much better had it brought over a few more Field Guns to attack, using the mountain range against me for protection of the attacking Field Guns, rotating them in and out as necessary. All in all the tactical & strategic AI is really good, but this is an example where perhaps it could be improved a little bit, that's why I'm making this report.

_4. Steps to reproduce (optional):_
[Tactical AI.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6266000/Tactical.AI.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
might be fixed already, after all march 2 was a long time ago :)
