### ISSUE TITLE
3-2 Inquisitors not working

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#7665]
I can convert cities where an inquisitor is parked. In past in the same situation the spread religion button wasn't active. Bug, bad memory or new feature?

![civnoinqui](https://user-images.githubusercontent.com/53142313/113778185-642da400-972c-11eb-99a3-7f4a2d9f3fab.png)

**Comment by ilteroi** [comment]
new feature. inquisitors only weaken the impact of the missionary.

**Comment by randomnublet** [comment]
Oh okay, that works. Do they reduce passive pressure as well?

**Comment by ilteroi** [comment]
no. unclear if that is desirable.
