### ISSUE TITLE
(Question) What is the "Header Row" of the EconomicMonitor Log?

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7666]
EDIT: NVM! I figured it out. The logs only show the header in the very first copy of the log, if you have it broken down by player as I do, only the first play has the header, the other logs just have the values.

So I was able to get what I needed, please close the thread.

**Comment by RecursiveVision** [comment]
@Stalker012345 if you opened the issue you can close it yourself
