### ISSUE TITLE
Can't improve some new resources

### ISSUE THREAD

**Issue by texashunk18** [LoneGazebo/Community-Patch-DLL#767]
Thought I'd put this in as a separate bug. Neither I nor the AI can seem to upgrade olives, perfumes, or tea for some reason. It'll say that we need to research calendar to improve it, but once it is researched there is no option to improve it. 
This happens at the same time as my inability to found a religion or build the pyramids.
[Database.docx](https://github.com/LoneGazebo/Community-Patch-DLL/files/34474/Database.docx)

**Comment by LoneGazebo** [comment]
Looks like you are missing leader DLC like Denmark and Polynesia.

**Comment by texashunk18** [comment]
I have all DLCs downloaded and activated though. I had just done a fresh install too.

**Comment by texashunk18** [comment]
Ok, so I did another full reinstall and it is now working correctly. I don't know why the first time didn't work. But thanks LoneGazebo, these mods are the best!

**Comment by LoneGazebo** [comment]
Glad to hear it.
