### ISSUE TITLE
Wonder Audio Quotes won't play.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#768]
Just did a clean install, cleared the cache and loaded only the CP, CBP, C4DF, CSD, More Luxury, and the Compatibility Files. I am unable to hear audios from any wonder at all. I am sure that it is not my side because loading without any mods gives me and having a wonder gives the the wonder audio.

I've also seen this on the 11/5 download as well.

**Comment by LoneGazebo** [comment]
Odd, I don't think we can even access the audio engine. I wonder if an audio is being overwritten. Any odd logging?

**Comment by TechpriestEnginseer** [comment]
Not from the XML or database as far as I can tell.

**Comment by TechpriestEnginseer** [comment]
Never mind, it was a faulty download, Installer need to have a file integrity check.

**Comment by TechpriestEnginseer** [comment]
Never mind, I was trying out this simple mod in vanilla and it seems to work with the wonder audio, whereas using it with the CP or CBP doesn't work with the wonder audio. I can only predict that any addition of wonder audio in the CBP will crash every other audio file and prevent any from being played.

**Comment by LoneGazebo** [comment]
It might be Motherland Calls. There is a motherland calls audio file in-game, but it might not be processed properly. Remove that XML element and see if it works.

**Comment by TechpriestEnginseer** [comment]
No, avail. As a reference, I used this [url=http://steamcommunity.com/sharedfiles/filedetails/?id=185694843]mod[/url]

**Comment by LoneGazebo** [comment]
Ah, yeah, wonder stuff doesn't work at turn 0. Not sure why.
