### ISSUE TITLE
behold the empire of budapest

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7683]
![image](https://user-images.githubusercontent.com/1358966/114313837-83477f80-9af8-11eb-9c93-009c20333cd6.png)

**Comment by RecursiveVision** [comment]
🤣 

I thought City-States had a unit cap @LoneGazebo ?

**Comment by ilteroi** [comment]
no worries!

![image](https://user-images.githubusercontent.com/1358966/114315878-4d5ac900-9b01-11eb-8fb9-039b436790b6.png)

**Comment by bentakacs** [comment]
Wow! The biggest one I ever managed to help creating was a 5 City CS, if I remember correctly.


> I thought City-States had a unit cap @LoneGazebo ?

Nooooo, please don't have! XD

Btw I really like this, it adds so much to the game in my opinion! <3

**Comment by Stalker012345** [comment]
> Wow! The biggest one I ever managed to help creating was a 5 City CS, if I remember correctly.
> 
> > I thought City-States had a unit cap @LoneGazebo ?
> 
> Nooooo, please don't have! XD
> 
> Btw I really like this, it adds so much to the game in my opinion! <3

Agreed, I wholeheartedly see this as a feature, not a bug.

**Comment by RecursiveVision** [comment]
I'd prefer for there to not be a unit cap as well. :)

**Comment by azum4roll** [comment]
I wonder how they can have Cruisers but none of the other strategic units.
