### ISSUE TITLE
AI Citadel usage

### ISSUE THREAD

**Issue by bentakacs** [LoneGazebo/Community-Patch-DLL#7684]
_1. Mod version (i.e Date - 12/1):_
3-2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

It's not necessarily an error, rather than just an inquiry. 

The AI uses Citadels to steal land from you really, really well, and I like this, but often I feel like it could be better used as a Great General to be honest.

For example, in my current game Songhai used 3 citadels near my border (I retaliated with 1 after the 2nd), and at the end grabbed only 1 lumber mill, 1 Furs (which they already have a monopoly on, and they are sanctioned anyway) and 2 Horses. Do they have that many GGs that it just doesn't matter for them? (Assyria also stole from me, and they are definitely not having that many GGs, they didn't wage too many wars)

I'm playing on Huge map, so the frontiers are quite big and they have a lot of soldiers, and I often don't see an AI GG for quite some time, which in combat is a significant weakness.

Yes, their land grabbing is hurting, but at the end does it actually backfire and hurt them more? Can their "flavor" for this be lowered a bit? (if it even exists to begin with) 

Thoughts?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
well each citadel also gives supply points ...

**Comment by bentakacs** [comment]
> well each citadel also gives supply points ...

Yes, like 2 or 4? Which is nice, but thanks to AI bonus I'm not sure they are desperately needed (I'm at my cap (54), and despite having ~20% more citizens than Assyria (146 vs 123), they have over +40% more units (54 vs 79) in my current game, on Emperor. I'm not saying its a bad usage, I'm asking if it is the best one? (see below)

> i think they keep one general around just in case and use additional ones for citadels

By "one general around" you literally mean 1? Because for a warmonger with almost 30 cities (Huge map), who spends most of the game with war on multiple fronts that's nowhere near enough.

**Comment by RecursiveVision** [comment]
> > well each citadel also gives supply points ...
> 
> Yes, like 2 or 4? Which is nice, but thanks to AI bonus I'm not sure they are desperately needed (I'm at my cap (54), and despite having ~20% more citizens than Assyria (146 vs 123), they have over +40% more units (54 vs 79) in my current game, on Emperor. I'm not saying its a bad usage, I'm asking if it is the best one? (see below)
> 
> > i think they keep one general around just in case and use additional ones for citadels
> 
> By "one general around" you literally mean 1? Because for a warmonger with almost 30 cities (Huge map), who spends most of the game with war on multiple fronts that's nowhere near enough.

Have to agree there.

**Comment by ilteroi** [comment]
just looked it up, it depends also on the number of wars they are in. but anyway i changed it, the limit now also takes into account on the number of land units they have available.

**Comment by bentakacs** [comment]
> just looked it up, it depends also on the number of wars they are in. but anyway i changed it, the limit now also takes into account on the number of land units they have available.

I have the feeling that it'll be a good change and will help the AI overall, but we will see. If it'll curtail their land-grabbing too much we can still change it back. Thank you!
