### ISSUE TITLE
Crash after giving next turn

### ISSUE THREAD

**Issue by hamorphis** [LoneGazebo/Community-Patch-DLL#7686]
_1. Mod version: v.94

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description: Game crashes and exits to windows 

_4. Steps to reproduce (optional): Load the save and click Next Turn

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"): [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6295907/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):  [CRASH SAVE.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6295910/CRASH.SAVE.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): [CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6295917/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
probably fixed
