### ISSUE TITLE
🐛 Constant War CTDs

### ISSUE THREAD

**Issue by Chagrilled** [LoneGazebo/Community-Patch-DLL#7688]
_1. Mod version (i.e Date - 12/1):_
12/1 modpack from Nik [here](https://forums.civfanatics.com/threads/dlc-modpack-repository.609278/page-41#post-15971708)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
There are 3 humans vs 3 AI, just started a war. Most actions we seem to do will crash the game to desktop. 

_4. Steps to reproduce (optional):_
Several varying steps seem to crash the game. As the Russians, we are about to move north and attack Vienna, the coastal city in the fog below Salzburg. Mousing over the city with ranged units (the trebuchets) seem to instantly crash it. My scroll wheel crashed something. Moving a soldier in a boat caused a crash. We also believe moving next to coastal cities (or some interaction thereabouts) causes a crash. Attached is a zip with a bunch of logs from several crashes, minidumps and the save file. The current turn is a minefield of crashes if you try to attack a city, at least for me. 

The knights seem to be able to attack the city. 
[civdump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6299615/civdump.zip)

**Comment by RecursiveVision** [comment]
This version is 5 months old, we don't maintain old versions.

**Comment by Chagrilled** [comment]
Am I missing something? The latest version on Gazebo's thread on the forum is 12/1? Is there somewhere else that has more up to date releases? I only see a few beta threads on the forums.

**Comment by RecursiveVision** [comment]
Oh, right. 

The latest betas are more stable than 12/1 was.
