### ISSUE TITLE
Golden age point generation in the top panel tooltip

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#769]
As posted on Civfanatics:
Bearing in mind that you don't like tinkering with interface, may I ask if one little issue could possibly be fixed? Golden age points is the only yield which income isn't shown correctly on the top panel. The only thing that's included is happiness; however, there are things like buildings (Satrap's court and Apostolic Palace, I believe) and traits (Moroccan and German UA) that also contribute towards regular GAP accumulation. I might have forgotten something else. This leaves the player oblivious to how much GAP he's actually receiving from each turn in some situations. Screenshot attached:
![1](https://cloud.githubusercontent.com/assets/12978597/11193514/bd7bf940-8caf-11e5-9680-24f61c4d0a8f.jpg)
As you can see, I'm playing Morocco and have an international (trust me) trade route that is yielding a defined amount of GAP per turn, which isn't reflected in the top panel tooltip.

It's certainly not a big deal, but rather something that makes my inner perfectionist itch.

**Comment by LoneGazebo** [comment]
Fixed in latest version.
