### ISSUE TITLE
Next Version

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#7691]
@RecursiveVision @ilteroi @Mileslewis 

Please give a brief write-up of your recent changes (since last version) for changelog. Thanks!

**Comment by LoneGazebo** [comment]
Also, if I could get some help with issue cleanup, that'd be great.

Also also, who messed with the Tercio icon? It looks weird in-game.

**Comment by RecursiveVision** [comment]
@pineappledan messed with the Tercio icon. Will write up a changelog shortly :)

**Comment by ilteroi** [comment]
so many changes, but the most important are
* improved city specialization logic for AI
* improved city governor tile selection
* fix city yield calculation
* improved AI explorer handling
* fix lots of crashes
* fix 'cannot end turn' issue
* fix map trading
* owned ice is passable for everybody
* improve instant yield history, can continue playing forever now
* puppets can only build defensive buildings up to the previous era (run processes otherwise)
* improve AI economic decisions, consider instant yields in addition to gold per turn
* tweak AI city production choices, should not go broke so easily
* does not create so many citadels, keeps more generals
* improve some AI tactical combat behavior corner cases

**Comment by LoneGazebo** [comment]
>improve instant yield history, can continue playing forever now
 is this the fix I did, or did you also tweak it?

**Comment by pineappledan** [comment]
- added +1 flat supply to Runestones (same as base lighthouse)
- Text fixes for Venetian Merchant and Brazilian UA
- Altered the flag for the Tercio
- God of the Stars & Sky yields now given to resources on Snow tiles as well
- University/Seowon +1 science on Snow tiles
- Scientific Revolution +2 science on Snow Tiles

**Comment by LoneGazebo** [comment]
@pineappledan the tercio flag looks...wrong. It's not color-coordinating anymore.

**Comment by LoneGazebo** [comment]
![image](https://user-images.githubusercontent.com/7849458/114603783-c111e880-9c5d-11eb-9324-ea36f57c0d26.png)

**Comment by pineappledan** [comment]
Just revert change I guess.

**Comment by ilteroi** [comment]
> Just revert change I guess.

i like that new icon ... but why is it red, that's the question?

**Comment by ilteroi** [comment]
> > improve instant yield history, can continue playing forever now
> 
> is this the fix I did, or did you also tweak it?

no idea what you did ... but now it's storing only the previous thirty turns.

**Comment by LoneGazebo** [comment]
@pineappledan i think maybe the DDS is just busted? Try resubmitting the change. No rush.

**Comment by LoneGazebo** [comment]
> no idea what you did ... but now it's storing only the previous thirty turns.

Redid the storage logic so that it isn't a fixed-size array based on maxgameturns. Now it's a dynamic vector.

**Comment by RecursiveVision** [comment]
My changes:
```
Voluntary Vassalage
- Fixed excessive AI desire for voluntary vassalage
- Masters who accept a voluntary vassal now go to war with anyone the vassal is currently at war with, preventing troops from being kicked out + AI trained to handle this
- Added option to disable voluntary vassalage (DiploAIOptions.sql)
- Fixed being able to have a Defensive Pact and Voluntary Vassalage in the same trade deal

Opinion Score
- Fixed recent trade, common foe, vassal protection opinion bonuses not being applied
- Vassal protection bonus now nullified if you attack your vassal
- Adjusted penalties for competition with the AI
- Reduced "denounced by our friend" penalty, also applies less often
- Reworked common foe bonus to account for power difference between AI and damaged player; now can go up to +100
- The effect of an AI's opinion score on approach selection is now less extreme; increased consideration of leader personality + prioritization if the AI hates or likes a lot of people

Approach
- Improvements to AI approach selection towards both civs and City-States
- Reduced tendency to gravitate towards neutral
- Fixed erratic shifts in approach while AI is planning war
- Fixed a major bug with AI approach prioritization

Bugfixes
- Fixed militaristic City-States not spawning units
- Another major revision of warmongering calculation, fixed excessive penalties and several bugs, dropped flavor elements
- AI less likely to denounce friends
- Fixed some issues with difficulty-related code
- Fixed missing distance check from third party war bribes

Balance
- Penalty for breaking PTP now scales with era
- Fixed excessive anti-warmonger fervor

Other
- Improvements to DP + coop war logic
- Adjustments to AI strength perception of humans
- Diplo Flavors Rework now fully reintegrated + VictoryCompetitiveness now a 1-10 scale
- AI no longer considers Grand Strategy before the medieval era (for domination) and renaissance era (otherwise); prior to this it uses its "diplo personality" which is based on flavors
- Added text to show when a Peace Treaty with a player's DP ally is blocking the ability to declare war
- Tweaked war information display
- Significant code cleanup and enum sanitization (still ongoing)
```

**Comment by RecursiveVision** [comment]
@LoneGazebo My changelog is rather long so I'll post it in the Diplomacy AI Development thread. You can add whatever you feel are the highlights to your changelog and add a note to check that thread if people want to see the full one. :)

**Comment by RecursiveVision** [comment]
@LoneGazebo Here's the commit which added the Tercio flag changes: https://github.com/LoneGazebo/Community-Patch-DLL/commit/5413bb6bdadea6c499c0c39534d47db3fcdf21b5

I'll help close issues.

**Comment by GLop4** [comment]
I suggested this original a while ago :
![ter](https://user-images.githubusercontent.com/8753808/114608429-f8a08500-9c9d-11eb-8738-2402ccfac560.png)

[newTercioFlag.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6306181/newTercioFlag.zip)

**Comment by Stalker012345** [comment]
> @GLop4 that's nearly identical to the conquistador.

I like that one better than the other one though. the other one is really thin and hard to see.

**Comment by RecursiveVision** [comment]
Isn't the Tercio originally a Spanish unit though?

**Comment by Mileslewis** [comment]
Basically all of the World Congress logic is now completely different but I'll try to make some key bullet points.

Proposal Logic:
- No randomness in voting or proposal choices
- Updated estimates of what proposals will help/hurt a Civ in general
- Earlier recognition of Tourism and Diplomatic victory progress and which proposals can help
- Civs will estimate which proposals other Civs like/dislike and then either help/hinder them depending on relationship and victory competitiveness. They may even help you win if they like you enough!
- Vassals use same logic but are likely to help their master if they like them.

Special Sessions (Host and World Leader Votes):
- Voting for another player is dictated by high congress 'alignment'. Alignment is mostly dictated by congress voting history, shared religion/ideology and war history. Vassals/Liberated Civs will have high alignment if they like their master.
- Vote numbers are also important (the more votes you have compared to them the more likely they are to vote for you)
- World Leader votes can no longer be bought.

- Deal valuation for trading votes updated

When the patch goes live I'll make a thread on the forum so people can complain

**Comment by RecursiveVision** [comment]
I closed about 100 issues that appeared to be resolved.

**Comment by RecursiveVision** [comment]
@Stalker012345 For all the enemy unit panel stuff I'll do some work on fixing it after the next release.

**Comment by LoneGazebo** [comment]
@pineappledan I fixed it.

**Comment by GLop4** [comment]
![ter2](https://user-images.githubusercontent.com/8753808/114613482-ad897080-9ca3-11eb-8991-55992e3d0fd4.png)
I use it for months and never made a confusion.

**Comment by Stalker012345** [comment]
> * Receiving extra votes for Diplomatic Victory is less likely than for host
> * Diplomatic Victory votes can no longer be bought.
> 

hehe probably too early for feedback as these are the changes that are going live, but since I see them. I really don't like they are taking away concrete ways to win a victory conditions (getting diplomats and making deals to secure votes) and trading them for fuzzy ways (other civs may....or may not...vote for you, who knows?).

Now I am all for those deals costing you an arm and a leg, if an AI is willing to make a deal where you could win the game, then it should hurt! But....if I can afford it, then let me do it. I think that it is way more sastifying to go "okay I convert my +200 GPT reserve into key DV votes" than "oh....the AI voting for me....wow I won....that's....um, cool".

**Comment by Mileslewis** [comment]
The Civs randomly voting for you is something that could happen before, I just tried to explain the reason why it would now happen so that people have more of an idea.
I do get that it might still feel random though because I'm not sure there is any way of actually seeing your alignment with other civs.

Tbh I agree on the trading votes that I would like to know what people want and do that. I would have to think on how to rework it though and what situations people shouldn't sell their votes. Also I have no idea how much they should be worth.

**Comment by LoneGazebo** [comment]
Diplo votes should be buyable IMO.

**Comment by RecursiveVision** [comment]
> With respect I think they have a right to on this one. This isn't a bug fix or an update in logic, its a fundamental change to how a victory condition is acquired. That's something that should absolutely be debated by the community before implemented.

I think Milae's comment was intended as self-deprecation, not as an attack. :)

> Diplo votes should be buyable IMO.

I agree. But they should be expensive.

**Comment by Mileslewis** [comment]
Well if you all agree I can try to change it before release?

**Comment by LoneGazebo** [comment]
@Mileslewis I think it should be.

**Comment by azum4roll** [comment]
AssignStartingPlots:

- Natural Wonder locations require higher fertility, to properly prevent being put in the middle of nowhere. Side effects might include Krakatoa never being placed, please observe.
- Make sure Natural Wonders can never be 3 tiles around City States (up from 1).

Communitu_79a v2.3.0:

- Tweak shortest path algorithm edge weights so it actually works (no more straight unnatural canals)
- Make sure polar sea connections never dig through land in Terra mode

**Comment by hamorphis** [comment]
When are you planning to release this new version?

**Comment by RecursiveVision** [comment]
> When are you planning to release this new version?

@LoneGazebo I second this, I'm looking forward to playing a game on the new version myself :)

**Comment by LoneGazebo** [comment]
hopefully today.

**Comment by hamorphis** [comment]
Great Work of Programming! Wish I knew C++, but I am only a C# guy :)

**Comment by hamorphis** [comment]
We should have a new special person in the modern era - Great Developer who could write a Great Piece of Software and place it in a Research Lab giving boost to cyber espionage :)

**Comment by azum4roll** [comment]
> 
> 
> We should have a new special person in the modern era - Great Developer who could write a Great Piece of Software and place it in a Research Lab giving boost to cyber espionage :)

And then it gets stolen by a hacker the very next turn
