### ISSUE TITLE
3/2 (Tactical AI) - AI continues to send Field Guns to their death

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7698]
_1. Mod version (i.e Date - 12/1):_
3/2

_2. Mod list (if using Vox Populi only, leave blank):_
ENW

_3. Error description:_ 
Siam continues to send field guns into this position, only to see them obliterated time and time again. I've probably killed at least 20 field guns off of those spots.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/114664060-ce13f380-9cc0-11eb-8d36-00fbee773629.png)
[For Review.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6308636/For.Review.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
hmm difficult. AI remembers almost nothing from the previous turns. and they think it's a safe spot because no adjacent enemies. no idea how to fix.

**Comment by LoneGazebo** [comment]
Would a simple dangerplots ‘unitdiedherelastturn’ interger work?

**Comment by Mileslewis** [comment]
If anything I would say the issue is that the AI should be more aggressive with their melee units. This would mean siege weapons wouldn't be left out in front. Particularly their best melee units seem to often get left as garrisons instead of being used in attacks.
They ain't winning that war either way though.

**Comment by Stalker012345** [comment]
> If anything I would say the issue is that the AI should be more aggressive with their melee units. This would mean siege weapons wouldn't be left out in front. Particularly their best melee units seem to often get left as garrisons instead of being used in attacks.
> They ain't winning that war either way though.

I get the reason to put your ranged units in this position though, I mean the lake blocks melee from moving in, so its reasonable to station ranged units there. The problem is I have set up a kill box in that area and the AI just doesn't respect it.

**Comment by ilteroi** [comment]
> Would a simple dangerplots ‘unitdiedherelastturn’ interger work?

not specific enough

**Comment by RecursiveVision** [comment]
@ilteroi Perhaps store the danger level of the plot?

**Comment by LoneGazebo** [comment]
@RecursiveVision I added checks in the citadel calc model so it'll adapt, yep.

**Comment by inkyant** [comment]
> hmm difficult. AI remembers almost nothing from the previous turns. and they think it's a safe spot because no adjacent enemies. no idea how to fix.
There are no adjacent enemies but surely it should know that there are two ranged units and a city right there? It should consider ranged units/cities.

**Comment by azum4roll** [comment]
I think they can only see one ranged unit (and the city). Field Guns have -1 sight.

**Comment by LukaSlovenia29** [comment]
I'd recommend giving siege units full sight. Humans already know how to work around their siege units having -1 sight, so the current setup is very AI-unfriendly. This small change might help the AI perform a bit better.

**Comment by ilteroi** [comment]
good point. can't even remember why that reduced sight was introduced

**Comment by RecursiveVision** [comment]
If Stalker is playing on Immortal or Deity, they should have +1/+2 extra sight respectively...
