### ISSUE TITLE
AI asks to declare war on civs you have DOF with

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#770]
I'm taking a liberty to post on behalf of Funak who has been so reluctant to post here. Disclaimer: the quote isn't 100% accurate.

"Is it possible to make the AI stop asking me to declare war on my friends (as in DOF)? I mean I can't ask them to declare on their friends so it is really unfair that I should suffer diplopenalties for getting asked to declare war on my friend. "

**Comment by LoneGazebo** [comment]
This was fixed in latest version.
