### ISSUE TITLE
Game crashes upon clicking research on compass or machinery

### ISSUE THREAD

**Issue by worldwarli** [LoneGazebo/Community-Patch-DLL#7701]
_1. 12-1

_2. VP, red Scaling, small scale and extended 

_3. Tech tree appears broken, game crashes upon clicking on Compass or Machinery and the options to research them never appears

_4. Steps to reproduce: Literally just start the game, settle, go to the tech tree and click on compass or machinery.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. [CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6311657/CvMiniDump.zip)

2. [AutoSave_Initial_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6311672/AutoSave_Initial_0000.BC-4000.zip)

3.  [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6311687/Logs.zip)

4.

**Comment by corecontingency** [comment]
Screenshots (and more context) are here:
`https://forums.civfanatics.com/threads/bug-with-certain-techs.669260/`

The tech tree in the screenshots is completely wrong (probably vanilla tech tree). Just checking, but are you opening a VP game by clicking on the MODS menu, enabling all the Vox Populi mods (there are eight in total, 1-7b) in that submenu, then clicking on next and starting a game from there?

The logs you posted:

```
[20198.734] ERR: Cannot create directory.
C:\Users\world\Documents\My Games\Sid Meier's Civilization 5\MODS\Air and Missile Base/Commanders (v 1)\
[20198.734] ERR: The system cannot find the path specified.
[20198.734] ERR: There was an error installing the mod. (C:\Users\world\AppData\Local\Temp\Civ5ModInstaller\Air and Missile BaseCommanders (v 1).modinfo)
[20226.328] ERR: There was an md5 mismatch on one of the included files. (C:\Users\world\AppData\Local\Temp\Civ5ModInstaller\XML/New Text/GameText.xml)
[20226.328] ERR: There was an error installing the mod. (C:\Users\world\AppData\Local\Temp\Civ5ModInstaller\[BNW] Colonialist Legacies - The Boers (v 1).modinfo)
[20253.406] ERR: Cannot create directory.
C:\Users\world\Documents\My Games\Sid Meier's Civilization 5\MODS\Super Power: Clash of Civilizations (v 6)
[20253.406] ERR: The directory name is invalid.
[20253.406] ERR: Cannot copy file. C:\Users\world\AppData\Local\Temp\Civ5ModInstaller\Art/Flags/SPUnitFlags.dds
[20253.406] ERR: The filename, directory name, or volume label syntax is incorrect.
```

show it trying to install some additional mods (Super Power: Clash of Civilizations, and Air and Missile Base/Commanders). Does selecting just base VP in the MODS menu also cause the glitched tech tree?

Also, as mentioned in the CivFanatics forums, have you tried deleting everything in the cache directory (path is below):
`C:\Users\world\Documents\My Games\Sid Meier's Civilization 5\cache\`

**Comment by worldwarli** [comment]
I am loading the game through mods and enabling all VP mods

**Comment by corecontingency** [comment]
Weird, I don't know why the mods Super Power: Clash of Civilizations, and Air and Missile Base/Commanders are being installed if you are not enabling it in the MODS menu. I am guessing that those mods being installed with VP is the cause of the glitches.

Kind of a scorched earth approach, but maybe try unsubscribing to all Civ 5 mods on the steam workshop, delete everything in the cache and MODS folders, open up steam and run a verify integrity of game files for Civ 5 (right click on the game, click properties, then click local files), and then reinstall VP using the installer here:

`https://forums.civfanatics.com/threads/new-beta-version-march-2nd-3-2.668024/`

Paths to the folders I mentioned above:
```
 C:\Users\world\Documents\My Games\Sid Meier's Civilization 5\cache\
 C:\Users\world\Documents\My Games\Sid Meier's Civilization 5\MODS\
```

**Comment by worldwarli** [comment]
Understood! I will try it, thank you kindly!
