### ISSUE TITLE
Dumb way to calculate military strength ranking for City-State protection

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7703]
Surprised this hasn't come up yet, but why can't we just do this? There have been a lot of complaints about people being unable to compete with the AI in terms of military power for protecting City-States.

```
	int iHighestStrength = 1;

	for (int iPlayerLoop = 0; iPlayerLoop < MAX_MAJOR_CIVS; iPlayerLoop++)
	{
		PlayerTypes ePlayer = (PlayerTypes) iPlayerLoop;

		if (GET_PLAYER(ePlayer).isAlive() && GET_PLAYER(ePlayer).isMajorCiv())
		{
			int iStrength = GET_PLAYER(ePlayer).GetMilitaryMight();

			if (iStrength > iHighestStrength)
			{
				iHighestStrength = iStrength;
			}
		}
	}

	double fMilitaryMight = (double)GET_PLAYER(eMajor).GetMilitaryMight();
	int iPercent = (int)(fMilitaryMight / (double)iHighestStrength * 100);

	if (iPercent < (100 * /*0.6*/ GC.getMOD_BALANCE_CORE_MINIMUM_RANKING_PTP()))
	{
           return false;
        }
```

**Comment by RecursiveVision** [comment]
@LoneGazebo If you have no objections I'm going to change it to work this way because it's so much simpler to understand.

**Comment by LoneGazebo** [comment]
Sure

**Comment by ilteroi** [comment]
wrong parentheses on your percent calculation

**Comment by RecursiveVision** [comment]
@ilteroi Where's the problem?

**Comment by RecursiveVision** [comment]
actually, I realized I could just do this and it'll be much simpler haha
`int iPercent = GET_PLAYER(ePlayer).GetMilitaryMight() * 100 / iHighestStrength;`
