### ISSUE TITLE
Can work 3 tiles with 2 citizens

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7706]
Latest beta. I had the marsh locked and the forest worked but unlocked. When I clicked on the pearls to lock it and then clicked it a second time to unlock it, I somehow produced a third citizen.

Save file is in DEBUG config since I'm testing for any crashes or bugs that might occur.

[City Tile Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6315065/City.Tile.Bug.zip)
![Screenshot (9708)](https://user-images.githubusercontent.com/66801010/114811675-8a7ebf80-9d7c-11eb-81ad-7a0e373c55f7.png)
![Screenshot (9709)](https://user-images.githubusercontent.com/66801010/114811676-8b175600-9d7c-11eb-841c-8ad9acb54594.png)

**Comment by RecursiveVision** [comment]
Bug persists when the game is saved and loaded.

**Comment by RecursiveVision** [comment]
@ilteroi Here's an autosave (again, debug config) from before it happened. To reproduce, click on the pearl tile twice.

[AutoSave_0010 BC-3600.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6315076/AutoSave_0010.BC-3600.zip)

**Comment by RecursiveVision** [comment]
Clicking on the city center tile seems to fix the bug.

**Comment by youngsteve11** [comment]
I have just noticed the same thing playing as America. This was on a size three city, but when I pressed city centre it went away like yours did. This can be quite expoitable if in all cities, but more concerning how does it affect the AI civs.

**Comment by Primarch-Alpharius** [comment]
Got the same issue as well playing Babylon. Clicking a locked tile seems to produce both a laborer and an additional citizen working one random tile. Doesn't occur 100% of the time.

**Comment by ilteroi** [comment]
should be fixed. weirdly though, the offending code was from 2018 ...

**Comment by LoneGazebo** [comment]
@ilteroi what's the fix?

**Comment by ilteroi** [comment]
ah, i was mistaken, my fix had side effects ... the real issue was an unexpected citizen reallocation in an intermediate state during removal of the forced work plot.

**Comment by RecursiveVision** [comment]
@ilteroi Your fix doesn't seem to be savegame compatible.
![Screenshot (9732)](https://user-images.githubusercontent.com/66801010/114926466-5ea41e00-9dfe-11eb-9354-e28980aaf5db.png)

**Comment by ilteroi** [comment]
didn't change anything savegame related
