### ISSUE TITLE
Barbarians too passive?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7707]
@ilteroi I've had two Barbarian units in a row show up in front of this jungle here, and then they just stand there and heal, turn after turn, while I take my time to heal as needed and farm them for XP. Shouldn't they be more aggressive?

![Screenshot (9711)](https://user-images.githubusercontent.com/66801010/114812968-1e518b00-9d7f-11eb-9f4c-15bdb0a11ea9.png)

**Comment by grmagne** [comment]
I've noticed that too. They'll just stand in front of my heavily injured Warrior that can easily be killed.

**Comment by ilteroi** [comment]
i think i know what's up

**Comment by RecursiveVision** [comment]
Well, perhaps not any amount of damage, but they're uncivilized Barbarians, not organized military with long-term goals, and on the whole their strategy is to plunder and kill randomly...

Braveheart LOL, very nice :)

**Comment by skodkim** [comment]
Any chance of a hot fix? Rather annoying bug :-)
