### ISSUE TITLE
4/14 - 1st Turn CTD

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7708]
_1. Mod version (i.e Date - 12/1):_
4/14

_2. Mod list (if using Vox Populi only, leave blank):_
(UI) Trade Oppurtunities
Promotion Flags (EUI)
UI - Filters in Trade Route Overview
UI - Improved City View
UI - Religion Spread

_3. Error description:_ 
Getting a CTD right off the bat as I hit turn 1. Logs and saved game provided.
[AutoSave_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6315818/AutoSave_0000.BC-4000.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6315827/Logs.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Update: Tried running a new game with my UI mods off, and still 1 turn CTD. Both games were with Washington, so my guess is that is the problem.

**Comment by RecursiveVision** [comment]
I'll see if I can reproduce.

**Comment by Stalker012345** [comment]
Also to clarify, the CTD is occurring when I hit the next turn button on Turn 1

**Comment by RecursiveVision** [comment]
![df9411fa4a4df05a7760a8c201722a3e](https://user-images.githubusercontent.com/66801010/114832877-fd982e00-9d9c-11eb-9709-dc99748b9662.png)

**Comment by RecursiveVision** [comment]
@Stalker012345 Can't load the save game without that Yield Logs mod you're using.

**Comment by Stalker012345** [comment]
So I remade to go with just the absolute core to give you a save....and of course now its working. I'm starting to dig in. It seems to have something to do with Advanced Setup mod, or perhaps its the Communitas map itself. I'm trying some iterations.

**Comment by azum4roll** [comment]
You should prepare the Logs.zip before restarting the game so it doesn't wipe the logs.

**Comment by RecursiveVision** [comment]
I started a game with Communitas, no crash.

**Comment by Stalker012345** [comment]
Ok so I've narrowed it down to the Really Advanced Start Mod. The game runs fine with everything else. I can't figure out if there is a specific setting in that mod that is triggering it, but it definately involves that mod somehow.

**Comment by RecursiveVision** [comment]
Maybe it's conflicting with Communitas?

**Comment by Stalker012345** [comment]
> Maybe it's conflicting with Communitas? Communitas does have an "override AssignStartingPlots" setting...

I thought the exact same thing, but I tried standard continents, and I tried communtitas turning the override off and on. Both crashed. But running communitas with assign over on (as long as I was using regular advanced settings and not the really advanced ones) worked fine.

**Comment by ilteroi** [comment]
out-of-bounds read in CvEspionageClasses.cpp, lline 4115

```
					TechList tempList = GET_PLAYER(eLoopPlayer).GetEspionage()->m_aaPlayerStealableTechList[m_pPlayer->GetID()];
```

**Comment by LoneGazebo** [comment]
@ilteroi weird that it is only happening with that other mod. Code for that has been in there for some time. I'll add another validity check just to be sure.

**Comment by Dovaj** [comment]
Same CTD here as AI Turn 0/1 processes.  Clean install, VP Mods only, Communitas79 Map, Cache Cleared prior to start.
Logs may have some 'junk' at the beginning  I can not recall if I had deleted them all prior to most recent start.
Using the 43 CIV DLL by the way.

Before doing this 'clean' I had the issue off and on sometimes with Really Advanced Setup and sometimes without.  I tried peeling off mods, but eventually decided to just clean all of them out, delete cache, and try again pure.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6320000/Logs.zip)
[AutoSave_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6320019/AutoSave_0000.BC-4000.zip)
I hope these help.  I can redo the logs from nothing if they are too messy.  I am glad to help testing, etc.

**Comment by LoneGazebo** [comment]
@Stalker012345 try this DLL and report back: 
[Uploading CvGameCore_Expansion2.zip…]()

**Comment by dailyminerals** [comment]
I don't know if this has been said yet or not, but the 43 civ with EUI install gives me that 1st turn crash, but reinstalling with the "normal" vox populi with EUI eliminates the crash

**Comment by Dovaj** [comment]
> I don't know if this has been said yet or not, but the 43 civ with EUI install gives me that 1st turn crash, but reinstalling with the "normal" vox populi with EUI eliminates the crash.

Confirmed for me.  Reinstalling the regular VP w/EUI let games run from turn 0 to turn 1.

**Comment by CyberPhy** [comment]
I am also having this problem 
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6321630/CvMiniDump.zip)
