### ISSUE TITLE
Pioneers'/Colonists' pre-built buildings

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#771]
Posted on Civfanatics by Der_Zorn_gottes:

"The well and herbalist, being very early buildings, should be given to the pioneer and colonist building list."

**Comment by Radost** [comment]
They are dependent on the settled position of the city, so no.

**Comment by LoneGazebo** [comment]
Oh, good point, I hadn't considered that (perhaps that's why I didn't add them in the first place). My addled brain may have forgotten. :)

**Comment by LoneGazebo** [comment]
Since they are terrain-specific, I don't think adding them is worthwhile. Closing.

**Comment by Edaka** [comment]
It is a good point, haven't thought of it myself (:
