### ISSUE TITLE
4/14 - Various Governor Issues

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7711]
_1. Mod version (i.e Date - 12/1):_
4/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'll just keep updating this thread with various city governor issues I find. (UPDATE: Several more additions noted below)

1) Even with no growth on, the city is working a 4 F over a 3F 2G. Further, it is ignoring the natural wonder, which should basically be always prioritized I don't care what focus your on, but especially for the general one.

![image](https://user-images.githubusercontent.com/20593976/114840389-60d59080-9d9c-11eb-96d8-02cfacbaebb2.png)

2) Still working a 4F, even with growth capped.

![image](https://user-images.githubusercontent.com/20593976/114840978-fa04a700-9d9c-11eb-98ec-34d9090a2afc.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Now on 4/16 version. City skipped this National Wonder for its first 3 pop, which I understood, as the 2 silk and the oasis was a good yield foundation for a growing city.

But on Pop 4, the city should really be working that 6 C tile over a meer 2 P.

![image](https://user-images.githubusercontent.com/20593976/115447564-448f8480-a1de-11eb-8c33-8675055e3b44.png)

**Comment by Stalker012345** [comment]
City wants to work a 4F over the 3F 2G 2C Brazilwood tile.

![image](https://user-images.githubusercontent.com/20593976/115758444-bdb8e400-a364-11eb-96c3-014fb8125151.png)

**Comment by Stalker012345** [comment]
![image](https://user-images.githubusercontent.com/20593976/115782092-e18a2300-a380-11eb-8702-b8813a4f26b9.png)

So here we have a worked village over a brazilwood.

So thats 2F 2P 5G 1 C vs 3F 2G 1S 6C.

Or 2P + 3G > 1F + 1S + 5C

This one is at least closer, but I think the governor is still undervaluing culture especially and should be working the brazilwood.

**Comment by Stalker012345** [comment]
Ok even worse than the last one.

![image](https://user-images.githubusercontent.com/20593976/115785581-447db900-a385-11eb-8c92-d3ef5db6cad1.png)

He's working the tile just northwest of the city as opposed to the brazilwood in the southeast. 1F + 1P is definately not worth 6 C and 1 S

**Comment by azum4roll** [comment]
![image](https://user-images.githubusercontent.com/14953746/115993867-49ea3600-a607-11eb-9b84-f70aab25e190.png)
There are 2 tiles strictly better than the 1f3p2g lumber mill.

**Comment by ilteroi** [comment]
seems like i need to play brazil one of these days

**Comment by ilteroi** [comment]
i think i found the problem, with the default focus the weight for science/culture/faith was very low
