### ISSUE TITLE
City borders expand to flood plains instead of oasis, jade hill or cloves flood plains

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#7713]
_1. Mod version (i.e Date - 12/1):_
14/4/2021

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Before expanding, the possible selection tiles marked with purple/pink were two flood plains and an oasis, despite also having flood plains with cloves and a jade hill in the 2-tiles-away-from-city-center-range. The borders expanded to flood plains instead of to the oasis. Enclosed are save files before and after expansion. That seems either buggy or very suboptimal, despite the changelog of the new beta saying the city borders tile growth was improved.

_4. Steps to reproduce (optional):_
[City Borders Expansion.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6319390/City.Borders.Expansion.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
nobody said anything about border growth ... also a screenshot would have been nice? border growth is not only about yields but also about ease of access / natural borders.

**Comment by LukaSlovenia29** [comment]
My mistake, I must have misunderstood the changelog. Please close this, thank you.
