### ISSUE TITLE
False sacking notification returns

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7714]
![Screenshot (9727)](https://user-images.githubusercontent.com/66801010/114913335-17626100-9def-11eb-9e88-ac33761d6147.png)

**Comment by RecursiveVision** [comment]
Trying to find the cause.

**Comment by RecursiveVision** [comment]
Problem seems to be that the City-State "ready for take over" check is set before the Barbarians actually sack the city. 

In this case there was one Barbarian next to the City-State, but the City-State killed it before the Barbarians could have their turn and take over the city.

**Comment by RecursiveVision** [comment]
[Sacking Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6320389/Sacking.Bug.zip)

@ilteroi If you need a save file ^

(Debug config)

**Comment by ilteroi** [comment]
this should be impossible. the takeover is only attempted for units which are adjacent to a city. no unit, no takeover.

**Comment by RecursiveVision** [comment]
The issue seems to be:

Unit is adjacent to city (yes) ->trigger notification -> set "ready for takeover" -> City-State kills Barbarian unit adjacent to city -> No unit is able to take over

**Comment by ilteroi** [comment]
ah, i should have read till the end
