### ISSUE TITLE
github warning

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7716]
remote: warning: File 7cb6ef730d0e7c84ed6ad69488daa48a2821a46e is 54.82 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File fcf594390711bd3437706fbaa03abd3f6c6ed66a is 54.14 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File 381830d848017da0326adfa4a15b28d5b6f85862 is 54.14 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File 8b2f09b447f0d3712ce286371d06104946075553 is 54.82 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB

this seems to be due to "Packages\(1) Community Patch (v 94).civ5mod"

any way to make it smaller?

**Comment by LoneGazebo** [comment]
hmm...
