### ISSUE TITLE
The elusive ExCE CTD

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#772]
I'm almost certain I've finally tracked down the elusive CTD, and it appears that the Great Recon units have been causing the crash all along, hence the irregularity of it (not all AI Scouts grow up to be Great Recon Units). Almost every time I tried to select a Great Recon Unit, it would CTD. Giving the AI a free one using IGE, it would CTD on the next turn. I've ended with the conclusion that it is - somehow - related to **Unit_ClassUpgrades**, as every time that was commented out, no crash, otherwise almost always a crash - and I tested this many, many times.

Problem now is that I'm lost as to why this is. I tried changing the unit and the upgrade unit to not be a Great Person, to see if this was the problem, but it made no difference. I also tried changing the unitclass that it upgraded to a regular unit (rifleman) instead of another Great Recon unit, and this did work, but did not work when I made this regular unit a scout.The only certainly is that commenting out Unit_ClassUpgrades means no crash, always.

So, I'm hoping you might provide some insight. Do you know of anything that might cause the Unit Upgrade check (or however it works in the DLL) to crash the game?

**Comment by LoneGazebo** [comment]
Are you getting a minidump for the crash? If so, mind linking it?

**Comment by oalzubbi** [comment]
ExCE is part of CBP? I thought they were seperate mods.

**Comment by LoneGazebo** [comment]
It oalzubbi - it uses the CP, which I manage for JFD.
G

**Comment by LoneGazebo** [comment]
Looked at minidump, and it is breaking in the lua51_win32.dll file, not the DLL. That makes it hard to trace. Mind linking me the mod files? Also, instructions to reproduce same as above?

**Comment by JFDaly** [comment]
[Here](https://www.dropbox.com/s/3u7s6jhdnu0u7o2/Mods.rar?dl=0) is ExCE v8 and IGE for testing.

The easiest way to reproduce the issue:
1. Add through IGE Belem Tower (can be found in the Wonders list for the Renaissance).
2. When it spawns the Great Explorer, try selecting it. It in almost all cases will crash.
3. If it doesn't the first time, please start a new game and repeat the above, as it always did it within the first three tries for me. If it doesn't, then perhaps it's an issue specific to me.

Does this lua51_win32.dll file relate to the graphics engine, if you know? I says lua, but for Firaxis that could mean anything.

**Comment by LoneGazebo** [comment]
lua51 is, IIRC, the interface engine that links the UI with the DLL.

G

**Comment by LoneGazebo** [comment]
I think I know why it crashes (it crashed for me). It seems that the lack of a prereq tech for the unit you are upgrading into causes an invalid attempt to grab upgrade price, as upgrade price is affected by era.

G

**Comment by JFDaly** [comment]
It appears to be the case indeed. Unfortunately, this was a change I made in development of the latest version (can can be fixed), so this probably wasn't the source of elusive crash after all. Thanks for your help!

**Comment by LoneGazebo** [comment]
Hmm...well, if it comes back, send it my way. If this doesn't fix the problem (setting a prereqtech), let me know.

G

**Comment by JFDaly** [comment]
Will do. Setting the prereq has definitely fixed this crash, though, so that's something.

**Comment by LoneGazebo** [comment]
Good. That's the best of all feelings. 

G
