### ISSUE TITLE
4/14 - Automated Workers not Building Railroads

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7720]
_1. Mod version (i.e Date - 4/14):_
4/14

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Normally once Railroad tech is activated, my auto workers get right on building them. This game after an entire era and no rails.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/115002135-0440a700-9e6a-11eb-98d3-820166611afa.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi did you touch builderAI? I didn't.

**Comment by ilteroi** [comment]
works for AI at least
