### ISSUE TITLE
Iroquois Forest City Connection Not Working

### ISSUE THREAD

**Issue by grmagne** [LoneGazebo/Community-Patch-DLL#7722]
1. Mod Version 4-14 & 4-16.

2. Only Vox Populi Mods.

3. I've tested this repeatedly with both 4-14 and 4-16, with custom mods, without custom mods, etc. and it seems that Iroquois Forest City Connection ability doesn't work at all. I haven't been able to connect cities unless it is with a road.

**Comment by ilteroi** [comment]
hmm. it's weird. the code says you need to own the forest plot. the description says something else. according to the history, i added that ownership check on march 27 to fix some github issue, but it's unclear which. i guess my commit messages can be improved.

**Comment by grmagne** [comment]
That's how it works in Vanilla Civ 5, you need to own the forest. But it was changed in VP like 4-5 years ago because that was considered too weak.

**Comment by RecursiveVision** [comment]
@ilteroi It was this issue: https://github.com/LoneGazebo/Community-Patch-DLL/issues/7625

Probs just need to add a !MOD_BALANCE_CORE check.

**Comment by ilteroi** [comment]
so what is the intended behavior here? is there a difference between CP and CBP?

**Comment by RecursiveVision** [comment]
@ilteroi

Community Patch:
- Units move through Forest and Jungle in friendly territory as if they were Roads.
- Forest and Jungle in friendly territory act as Roads for the purposes of City Connections and Trade Routes

Community Balance Patch:
- Units ignore terrain costs in ALL Forest and Jungle
- All Forests and Jungles act as Roads for the purposes of City Connections and Trade Routes

**Comment by Hokiefan00** [comment]
I know this issue is closed and as I am new to this I don't know if I should open a new issue or just comment here. Sorry if I am doing this incorrectly!

The previous discussion above suggests that with the CBP, friendly territory is not necessary to create city connections. However, in the 5-24 version of the CBP friendly territory is required to create them.

I did a fresh re-install of CivV and the CBP with no modmods installed.

**Comment by grmagne** [comment]
Yes, this issue was never fixed even though it is closed. If you want to start a new thread, I'll confirm that it still does not connect Iroquois cities properly.
