### ISSUE TITLE
Repeatable CTD when in war, already second game.

### ISSUE THREAD

**Issue by Ice5640** [LoneGazebo/Community-Patch-DLL#7723]
_1. Mod version (i.e Date - 4/14):_
version 94 (latest, described as December 1st (5.12.1) on the page)

_2. Mod list (if using Vox Populi only, leave blank):_
![image](https://user-images.githubusercontent.com/68536969/115064313-1283d700-9eed-11eb-894f-c5491337e3f7.png)

_3. Error description:_ 
CTD when moving my units attacking a city. 
This is already the second game when this happens. The first game was also with Russia, but I activated some other mods which auto-downloaded in game when i had VP mod). First it was an occasional CTD here and there (no war) but at some point, when i started war the CTD became persistent, i could not finish the turn. I thought other mods might have been a problem, so i started a second game and this time ONLY activated the numbered mods 1-7b shown on the image above. The issue happened too.

_4. Steps to reproduce (optional):_
Just move military units to the Mongol city or attack nearby enemy. The game should CTD. i tried 3 times.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the reposit
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6327094/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Save_plus_another_1_turn_before.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6327103/Save_plus_another_1_turn_before.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6327106/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Old version, probably already fixed in the latest beta.

**Comment by Ice5640** [comment]
> Old version, probably already fixed in the latest beta.

@RecursiveVision , i just downloaded and installed this version, from here https://forums.civfanatics.com/threads/community-patch-how-to-install.528034/

That should be latest one. Where do i get the latest version?

**Comment by Ice5640** [comment]
ok, i found 4/14 / 4/16 beta. I guess this is the latest one.
would be good to update the links in the "how to install" thread so that people dont get into the same issue as me after 100+ turns.
