### ISSUE TITLE
[Feature Request?] Change rough terrain definition

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#7725]
@LoneGazebo you mentioned [here](https://github.com/LoneGazebo/Community-Patch-DLL/commit/a2a04c46aa86881f20d2e73bdf9d87da944d7731#commitcomment-49187742) that desert can't both cost 2 moves and be open terrain from a performance standpoint. What if we change the definition of rough terrain from

```cpp
bool isRoughGround() const
{
    return m_bHighMoveCost;
}
```
to
```cpp
bool isRoughGround() const
{
    return isHills() || getFeatureType() == FEATURE_FOREST || getFeatureType() == FEATURE_JUNGLE || isMountain();
}
```
? (CvPlots.h) How much will it affect performance?

**Comment by RecursiveVision** [comment]
If the answer is "too much", we could cache the value in memory, and update it only if the feature or terrain changes. One extra bool probably couldn't hurt. Could repurpose m_bHighMoveCost if it has no other uses.

**Comment by azum4roll** [comment]
This has a side effect of treating Natural Wonders as open terrain. The IsNaturalWonder function is slightly costlier. Not sure if they're supposed to be open or rough anyway.

**Comment by LoneGazebo** [comment]
I leave this to @ilteroi

**Comment by RecursiveVision** [comment]
@ilteroi For context, there was a consensus on the forum to keep flat Desert as 2 movement but make it open terrain for promotions (except hills).

**Comment by ilteroi** [comment]
uh. so far rough terrain is defined as everything that costs more than 1 movement point. 

now you want to break this logic. possible, but i can't see all the implications right now.

maybe it's possible to define it via visibility instead.

on the other hand i would prefer to nuke those god-awful "double movement in X" promotions. that makes no sense at all.

**Comment by Stalker012345** [comment]
> uh. so far rough terrain is defined as everything that costs more than 1 movement point.
> 
> now you want to break this logic. possible, but i can't see all the implications right now.
> 
> maybe it's possible to define roughness via visibility instead (each feature has a seeThroughChange property)
> 

Assuming Recursive's logic is the proper way to activate it, I can't see how it would cause gameplay issues. Is rough vs open used in any scenarios other than movement (which it looks like movement is defined first before open/rough, so that shouldn't matter) or promotions (which we have a full list of those on the main forum that we reviewed before agreeing to this change).

Of course performance remains the outstanding question.

**Comment by azum4roll** [comment]
Testing my own build of the DLL, it doesn't seem to perform any differently.

**Comment by ilteroi** [comment]
agree, performance impact should be minor and even zero if we cache the flag like before. 

so now "roughness" is defined as seeThroughLevel > 1, so all plots which hinder sight because of type, terrain or feature.

**Comment by LoneGazebo** [comment]
We need to respect CP as a change. Just make sure we can do both.

**Comment by pineappledan** [comment]
In that case, Marshes should reduce visibility. Currently they are see-through, so I think it makes more sense for them to disrupt visibility than it does for them to be open terrain

**Comment by azum4roll** [comment]
The mountain-like ones should all block visibility if they don't already. Fountain of Youth, Great Barrier Reef, Barringer Crater and Lake Victoria should not. I'm not sure about Solomon's Mines. I'm not sure about the El Dorado.
