### ISSUE TITLE
"There is no scene loaded for this leader"

### ISSUE THREAD

**Issue by TheRealAyCe** [LoneGazebo/Community-Patch-DLL#7726]
_1. Mod version (i.e Date - 4/14):_
4-16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Leader scenes appear blank for leaders I've never met, and Sweden also displays this and greets me as if we are friendly, even though I've killed their soldiers and their starting settler.

_4. Steps to reproduce (optional):_
I just started a "normal" game on a huge map with the VP mapscript with 43 civs at once.

Save: 
[save2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6329341/save2.zip)

_4. Screenshots (optional):
![20210417150454_1](https://user-images.githubusercontent.com/11407231/115114518-63dca680-9f7f-11eb-8ad0-e78d709b83c2.jpg)
![20210417150858_1](https://user-images.githubusercontent.com/11407231/115114520-650dd380-9f7f-11eb-8e4f-98f1a98b1d7e.jpg)
![20210417151639_1](https://user-images.githubusercontent.com/11407231/115114522-65a66a00-9f7f-11eb-95df-fe2dc57bb54c.jpg)
![20210417145935_1](https://user-images.githubusercontent.com/11407231/115114523-66d79700-9f7f-11eb-82e4-268e876f0777.jpg)
![20210417145946_1](https://user-images.githubusercontent.com/11407231/115114525-66d79700-9f7f-11eb-81e5-cd272089e104.jpg)

**Comment by RecursiveVision** [comment]
Diplo AI behavior is wonky if they never found a city.

**Comment by Dovaj** [comment]
Isn't the behavior shown in the screenshots above a known limitation of the 43Civ DLL when you have more than 22 Civs in the game?  I have seen that ever since I first started using the 43Civ DLL.
