### ISSUE TITLE
Oops

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7727]
@ilteroi I was trying to clone the oleole branch to create an RSI branch but accidentally deleted your branch on the remote...my bad!

Thankfully master was all synced up with your changes except for this commit https://github.com/LoneGazebo/Community-Patch-DLL/commit/3eae9c5a368fc5820d6709dfed303213d71f0419 which is still on Github's records, I'm fixing my mistake ASAP

**Comment by RecursiveVision** [comment]
Okay I created a "shiny" branch and restored your commit there, in case you aren't able to restore oleole to Github yourself.

Sorry!

(Also I think you misunderstood the Iroquois thing, it's vanilla Civ 5 that requires plot ownership, not VP)

**Comment by ilteroi** [comment]
no worries, nothing lost. i deleted the remote branch myself because i had rebased my changes on top of master.
