### ISSUE TITLE
Question re: LUA hooks

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7728]
If an LUA hook calls a DLL function, does the LUA script pause until the DLL finishes execution of the code, or does it keep moving on to the next line of LUA code as the DLL function is executing?

**Comment by RecursiveVision** [comment]
For context, I'm thinking of redoing Enemy Unit Panel logic to work like this:

1. Call "GenerateCombatOdds" function.
2. DLL generates all the modifiers and values.
3. Retrieve them using more LUA calls.
4. Display.

**Comment by RecursiveVision** [comment]
Hmm, not sure WHERE I'd cache those in memory, though. Is there convenient clientside only memory for this kind of thing?

Ideally I'd use a table but I don't know how to parse text in LUA.

**Comment by ilteroi** [comment]
game logic and lua seems to be mutually exclusive, enforced by the game core lock.

the combat panel already does lots of calls into the dll to retrieve the individual numbers, so the best course of action seems to be to make just one call which returns two strings, one for the left side, one for the right side?

no caching necessary.

**Comment by RecursiveVision** [comment]
@ilteroi How can you retrieve two strings with one call? There's also health, CS and predicted damage to consider...

**Comment by LoneGazebo** [comment]
> @ilteroi How can you retrieve two strings with one call? There's also health, CS and predicted damage to consider...

Return the strings as an array. See how I do it for instant yield strings...

**Comment by LoneGazebo** [comment]
If you return two strings as an array, m_aiString[0] could be enemy, m_aiString[1] could be friendly

**Comment by LoneGazebo** [comment]
You could also create a custom container struct for the call that holds two strings and all the other values. See how Great Work function.

**Comment by RecursiveVision** [comment]
Thanks for the help!
