### ISSUE TITLE
Minor Civs move at startup

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#7729]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_
A lot, but the same was used previously without problems while VP has been updated

_3. Error description:_ 
According to RecursiveVision minor civilizations should be prevented from moving at startup unless they are unable to found a city in the location they're in. This doesn't work however (they move from good locations).

Rather annoying since "BALANCE_CORE_SETTLER_MOVE" was removed from CustomModOptions meaning you can't control minor civ placement without use of an editor.

_4. Steps to reproduce (optional):_
Start game, observe minor civ placement, hit next turn and see some of them have moved.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@ilteroi Such was the case when I removed that option (only majors cared about optimal settling spots). Did you change this?

**Comment by ilteroi** [comment]
yeah. why should they not move?

**Comment by skodkim** [comment]
It's a way of playing scenario like maps. I always place minor civs at his locating, while spreading around.

I'm fine with them moving if the old option of preventing settlers from moving at startup is reactivated. That was the way i used to control it.

**Comment by LukaSlovenia29** [comment]
[Antananarivo Settler.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6331008/Antananarivo.Settler.zip)
Here's a save game from turn 0 where Antananarivo's settler moves.

**Comment by LukaSlovenia29** [comment]
I'll say that in this version I've seen quite a few cases where one of the 8 copies of my starting luxury came top be within 3 tiles of a city state, so I guess it could be connected to CS settlers moving. Through this major civs can get denied one copy of their starting luxury, which can be a problem.

**Comment by azum4roll** [comment]
They really shouldn't move. In this version they're getting luxuries and natural wonders they shouldn't have got.

**Comment by ilteroi** [comment]
ok ok i'll make sure they don't move

**Comment by skodkim** [comment]
@RecursiveVision will you revert this please?

**Comment by RecursiveVision** [comment]
@skodkim I'll make it an option, yeah.

**Comment by RecursiveVision** [comment]
Done. https://github.com/LoneGazebo/Community-Patch-DLL/pull/7908/commits/0579563832c6ad1a095311205c2cb77e128982d8

**Comment by azum4roll** [comment]
Please make the default value 0 for CS. It seriously breaks them if they move.

**Comment by RecursiveVision** [comment]
yeah ok

**Comment by RecursiveVision** [comment]
changed it
