### ISSUE TITLE
Return of false promises

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#773]
Posted by Funak on Civfanatics:

"I have an AI(Pedro) claiming I demanded he shouldn't settle near me as well as demanding that he stops spying on me. I've not talked to him all game (he isn't even located anywhere near me). I don't really know how to prove this, but anyways that's how it is. "

**Comment by LoneGazebo** [comment]
I'll look, but I need more than one case to consider this a full-on bug.
