### ISSUE TITLE
Too few minor civs at startup

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#7730]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_
A lot but worked prior to updating to 4/16

_3. Error description:_ 
At startup screen I select 22 minor civs and only 20 show up in game. Seen twice in a row now.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by skodkim** [comment]
Verified for the third game (just to make sure since it seems so weird)

**Comment by skodkim** [comment]
Simply capped at 20 it seems  - choosing 24 also results in 20. Playing a "large" map (with custom proportions if it mappers)

**Comment by skodkim** [comment]
Ok, this is driving me mad, so I decided to test with only VP (full package) installed.Same result: 22 minor civs selected, 20 civs spawn

**Comment by azum4roll** [comment]
Please attach Lua.log.

**Comment by skodkim** [comment]
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6331646/Lua.zip)
Here you go. Very easy to reproduce. Just start a game and increase number of players to e.g. 22. This game was with communitas map, 15 civs and 22 (in reality 20) minor civs.

Hope you can nail this - eager to start playing with my setup-

\Skodkim

**Comment by azum4roll** [comment]
Hmm it only planned to add 20 City States. Are you using the 43-civ version? That one can only have 20 CS, IIRC.

**Comment by skodkim** [comment]
I'm not

**Comment by skodkim** [comment]
@azum4roll How do I see if its the 43 civ dll? 

One thing I noticed is that normal civs are assigned player numbers 0-14 (in firetuner) while Minor Civs are assigned numbers 43-62 which implies that there's room for 43 civs. Don't think I've seen hat before when using the Firetuner.

I downloaded the release from Civfanatics again and it the same. Also tried downloading the files directly from Github and even though I take the standard dll it's the same problem. Could it be that the wrong file has been posted??? Don't know if that's possible. Tried comparing the two dll's from the standard and the 43 civ directory and they're exactly the same size and a comparison in Winmerge shows no differences.

**Comment by azum4roll** [comment]
It could actually be. I compiled the DLL myself changing only one line (rough terrain definition) and it reduced the size by 2KB, so there could be something going on.

**Comment by skodkim** [comment]
So can you compile a new dll with the standard version (actually took the day off to play and that sort of...)?

**Comment by azum4roll** [comment]
I don't have it here...

**Comment by skodkim** [comment]
Thats fine - it was a long shot. Thanks for the help so far !! :-)
