### ISSUE TITLE
16/4 lake city with sea access: work boats and sea route issues

### ISSUE THREAD

**Issue by Thibix-Magnus** [LoneGazebo/Community-Patch-DLL#7732]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi, info adict, convenient start

_3. Error description:_ 

Case of a lake city (1-tile lake) with access to sea via fort: issues with cargo ship and work boats

- lake city can't make work boats, and other work boats can't cross forts into lake.

Lake cities can build cargo ship and send trade routes, but:
- no internal sea trade route can be sent to lake city with sea access via fort. AI doesn't seem to send external sea routes to lake city.  
- cargo ships can't be re-located to lake city from other cities: they seem to relocate when asked to, but are teleported to the nearest city once clicking end turn.

_4. Steps to reproduce (optional):_

In sent save: wait 1 or 2 turns, new cargo ships will be available to try.
Otherwise: found city on lake shore and build a fort to access the sea. Found other coastal cities to make work boats and cargo ships.

[Lake_coastal_issue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6331066/Lake_coastal_issue.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
duplicate #7735
