### ISSUE TITLE
Empty gift from AI

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#7734]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Maya sends me nothing as a gift, which forces me to decline and get an opinion penalty. Note that they made another trade (peace with Greece) on the same turn. Might have mattered.
![image](https://user-images.githubusercontent.com/14953746/115151173-510cc380-a09e-11eb-874c-48e05ac65c99.png)

**Comment by RecursiveVision** [comment]
Need a save file to reproduce.

**Comment by azum4roll** [comment]
Unless you're willing to download a whole modpack, I don't think you can open my saves...

**Comment by RecursiveVision** [comment]
Not much I can do, then.
