### ISSUE TITLE
Ships can't enter lake cities

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#7735]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Naval units can't enter lakeside cities, resulting in ships getting stuck when built/gifted when they otherwise could've got out.
![image](https://user-images.githubusercontent.com/14953746/115151414-528abb80-a09f-11eb-865f-d3420a54b1c0.png)

They're also a waste as a conscript unit, as they can't act as garrison for the Authority policy.
![image](https://user-images.githubusercontent.com/14953746/115151344-0fc8e380-a09f-11eb-847a-def770006322.png)

_4. Steps to reproduce (optional):_
Settle a city with multiple lakes, build a ship.

**Comment by ilteroi** [comment]
no 1: yeah, a bug with lakeside cities and coastal cities

no 2: conscript units are only land units now, so not relevant

**Comment by azum4roll** [comment]
> 
> no 2: conscript units are only land units now, so not relevant

But that's a conscripted trireme in the second image...

**Comment by ilteroi** [comment]
maybe gifted? different thing? but gifted units should go to the largest water body in your empire, is that the case here?

**Comment by azum4roll** [comment]
I haven't received any naval gifts. The Trireme has the conscript promotion.
