### ISSUE TITLE
Wrong dll uploaded?

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#7737]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I suspect that the 43-civ dll may have been uploaded as part of the standard VP package in the 4/16 hotfix, see https://github.com/LoneGazebo/Community-Patch-DLL/issues/7730

Don't mean to spam the bug reports, but I didn't know how else to report this apart from a buried conversation in an existing bug report.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
The correct DLL was uploaded, however I'll recompile and place here for you to try again.

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6336778/CvGameCore_Expansion2.zip)

**Comment by LoneGazebo** [comment]
just start with that one
