### ISSUE TITLE
Overblown tribute values

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#774]
Posted by Physiker on Civfanatics:

"Using the the Mod pack with EUI from 29/10. I noticed that the tributes from City states are way to high on slower game speeds.
You get like 65 of a resource on standard, 260 on epic, and 1200 on marathon. As you can demand one every 10 turns .. they should be the same value, should they not? (or maybe a factor of 1.5 became 5 ?) "

**Comment by LoneGazebo** [comment]
I'll fix. Probably a missing /100 divisor.
