### ISSUE TITLE
Korea won't settle at start of game

### ISSUE THREAD

**Issue by glider1001** [LoneGazebo/Community-Patch-DLL#7742]
_1. Mod version 4/16:

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Turn 20 and Korea hasn't settled oscillating between two squares forever unable to make up its mind between two equally good locations

Link:
https://forums.civfanatics.com/threads/new-beta-version-april-14th-4-14.669346/page-6#post-16077400

_4. Steps to reproduce (optional):_
map Communitas 2.3.0

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/42725181/115345118-a9a0a580-a1f1-11eb-8c94-81438b20feef.png)

**Comment by ilteroi** [comment]
very strange - there is a hardcoded limit of three turns for initial settler moves.

**Comment by azum4roll** [comment]
Can you show the whole minimap? I wonder how civs can start in such a small island.

**Comment by glider1001** [comment]
Sorry azum4roll I no longer have the save I should have captured the whole screen. It was tiny communitas map 2.3.0 6 civs + 12cs so probably cramped.

I've never seen this happen again in my testing on same map config so it might be a very unlikely bug.
