### ISSUE TITLE
curious non-aggression

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7743]
![image](https://user-images.githubusercontent.com/1358966/115346340-58bc8d00-a1b0-11eb-8e45-086af2a8a572.png)

this is a huge map in turn 330. a total of 2 major-owned cities have changed hands.

i would have expected some players to be eliminated by now. does anyone else see similar behavior?

**Comment by Stalker012345** [comment]
I my last game Monty was Monty, declaring on me at every opportunity, didn't pay too much attention to the rest of the world.

**Comment by RecursiveVision** [comment]
@ilteroi Maybe you made the AI too competent at defense?

I reduced aggression a tad in some areas, but conquest-driven aggression should actually have increased considerably.

Also worth noting that I programmed diplo AI to hate and gang up on successful conquerors to prevent them from becoming runaways. This was also bumped up, or should have been.

**Comment by RecursiveVision** [comment]
Could be the broken "peace out too early" logic. I still need to fix that.

**Comment by ilteroi** [comment]
seems to have been a fluke ...
