### ISSUE TITLE
Wrong "You killed or captured their civilian" diplo modifier

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#7747]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_
Waaaaay long ;-)

_3. Error description:_ 
Have a weird negative Diplo modifier with another Civ saying "You killed or captured their civilian". Problem is... I didn't! Only just started the game (nearing classical) and we haven't been to war or anything. Maybe just a glitch???
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6344224/Logs.zip)

Other player has reported this as well on Civfanatics and he only uses Infoaddict. Unfortunately we don't have a savegame for you guys. Logs attached if these help :-)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@RecursiveVision

**Comment by RecursiveVision** [comment]
@skodkim No idea what's responsible for this. The logs are useless and with all those mods I couldn't load a savegame.

I'd need a savegame one turn before the modifier appears to make a definitive diagnosis.

**Comment by skodkim** [comment]
Yeah, I'm hoping someone will be able to produce one. Seen this in more than one game and it doesn't seem to be related to mod incompatibility.
