### ISSUE TITLE
Units waking each turn during healing

### ISSUE THREAD

**Issue by vetox20** [LoneGazebo/Community-Patch-DLL#7749]
_1. Mod version (i.e Date - 4/14):_
04/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Tooltip indicates units healing will stay inactive until full health. When next to an enemy, units will wake every turn and you must select heal unit (H) every turn until fully healed.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![HealWarrior](https://user-images.githubusercontent.com/82966157/115595037-7408c480-a2a4-11eb-9065-f9038aa22734.PNG)
[HealingBug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6352813/HealingBug.zip)

**Comment by ilteroi** [comment]
intentional. you don't want your unit to die when you're not looking, do you?

**Comment by vetox20** [comment]
So strange, I have no idea why I thought it was a bug then. I thought it
would only wake if it took damage, not if it was just near a hostile unit.
Apologies.

**Comment by pineappledan** [comment]
Even if intentional, it's very frustrating to have to press H on every unit every turn for 5+ turns. If I want to wake a unit that is fortifying/healing on the front lines then I will issue it new orders. I don't want to have to fuss over every unit I have pulled to the back line to heal. 

I would personally like to have this reverted.

**Comment by Stalker012345** [comment]
I agree with PAD, I find the pain is not worth the gain in this case. I am having to make a LOT more orders for my healing units now, to the point where I just gave up and use fortify instead.

**Comment by ilteroi** [comment]
well it's tricky, i think "fortify until healed" and "heal until in danger" are both valid strategies. but the UI only offers one choice.

**Comment by azum4roll** [comment]
The Alert button works for "heal until in danger".

**Comment by ilteroi** [comment]
well but alert doesn't wake the unit when fully healed. could be changed though. maybe

**Comment by RecursiveVision** [comment]
Didn't you change the Do Nothing button? Could repurpose that.

**Comment by skodkim** [comment]
If I want to heal but wake every turn I just use space.

But a "heal until in danger" would be preferable IMHO.

**Comment by randomnublet** [comment]
Exactly, space worked fine for scouts and other units who you wanted to heal but keep an eye upon in past. 

Please add a toggle to this feature if you don't feel like going back to the perfectly working pre-beta behaviour, it's hard to change micro habits after years of playing with the same shortcuts.
