### ISSUE TITLE
Sun God pantheon 

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#775]
Posted by Kolaris on Civfanatics: 

"Sun God Pantheon says "farms on improved resources", but I was getting faith from farms over Incense. To my understanding that Incense isn't "improved" without a Plantation.

I'm playing with Luxury resources hidden and the Incense was revealed under an existing Farm, if that makes a difference. "

**Comment by LoneGazebo** [comment]
Probably needs a resource link tag. I'll fix.
