### ISSUE TITLE
4/16 - Happiness Growth Penalty improperly applied

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7750]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
While my unhappiness is high, its actually causing my food to drop to 0, resulting in no growth. I think either the penalty is being magnified some where....or the penalty is suddenly being added to food instead of growth.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/115609198-dc5ba400-a2ac-11eb-87a7-73778ff62f5c.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Some more notes here, I am not seeing the problem all the time, so I'm not sure why its triggering at this point, but when it did, it triggered for all of the unhappy cities I had.

**Comment by ilteroi** [comment]
turns out CvCity::getHappinessDelta(bool bStatic) is hell, returned different values for the UI than for internal computation. and the latter can be wrong.
