### ISSUE TITLE
4/16 - Possible Spy Level Bonus Bug

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7751]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Possible bug, not confident in my understanding of the system.

In one circumstance I gain a +50% from my level 3 spy. In another city...+75%

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/115612714-2e062d80-a2b1-11eb-841d-5e947f42a3be.png)

![image](https://user-images.githubusercontent.com/20593976/115612736-33637800-a2b1-11eb-87a6-56dcdf748265.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Open Borders inflates your spy level. Also cultural influence.
