### ISSUE TITLE
Puppets not including Military Bases in their Build Orders

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7752]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I believe puppets are supposed to consider all defensive buildings in their orders, but my puppets are staying on processes after military bases are unlocked.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/115668403-b1a13800-a30c-11eb-872c-158930d0586d.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
They only build defensive buildings up to the _previous_ era.
