### ISSUE TITLE
Suspicious voluntary vassalage

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#7753]
_1. Mod version (i.e Date - 4/14):_
4/16/21

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The save file is on the turn before Poland (#3/4 in score) becomes a voluntary vassal to #2 Ethiopia.

_4. Steps to reproduce (optional):_
Click next turn.
[Turn B4 Poland Vassalage.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6359562/Turn.B4.Poland.Vassalage.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Can't load the save due to the broken savegame system.

**Comment by RecursiveVision** [comment]
I dropped voluntary vassalage willingness a little more but not much else I can do at the moment.
