### ISSUE TITLE
4/16 - Highly Suboptimal AI building

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7755]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Arabia AI is playing its normal Tall game. Yet it did not build a single guild or money building in its capital...not one.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/115802619-dcd76600-a3a4-11eb-8da4-07cee037dcdc.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Production AI logs?

**Comment by ilteroi** [comment]
seems they consider the bazaar invalid, which naturally blocks them from building the later buildings

**Comment by Stalker012345** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6363742/Logs.zip)

Here are the logs

**Comment by LoneGazebo** [comment]
@ilteroi d'oh, my bad

**Comment by ilteroi** [comment]
not your fault, i added that check to prevent them from building unneccesary buildings on lakes. still the question remains why the bazaar should give tourism to sea trade routes?

**Comment by LoneGazebo** [comment]
coastal bazaar?
