### ISSUE TITLE
Global monopoly on iron

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#776]
Posted by Takagi Hiro on Civfanatics:

"Despite having a global monopoly on iron, I am not getting the production bonus on my tiles. Unless this ties in with Russia's UA, which I doubt it does being as the strategic bonus works just fine, something's wrong here. 11/5, No-EUI version.

Edit: I'm actually noticing that I'm getting +10% production in all of my cities due to a resource monopoly... and I don't have one on copper. The iron bonus is simply wrong or written incorrectly. Hope that puts us in the right direction. "

**Comment by LoneGazebo** [comment]
Sounds like an XML bug.
