### ISSUE TITLE
AI says "Impossible" when I want to trade for voting against them being sanctioned

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#7761]
_1. Mod version (i.e Date - 4/14):_
4/16/21

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I wanted to ensure Siam would vote against itself being sanctioned, but it refused to make any deal for that. To me that seems illogical - not getting sanctioned should generally be of the highest priority for the AI.

_4. Steps to reproduce (optional):_
[Siam Sanctions Vote Trade.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6367224/Siam.Sanctions.Vote.Trade.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
They don't trade on votes involving them personally.

**Comment by LukaSlovenia29** [comment]
Hmm. But when it comes to this, the AI imo shouldn't be willing to make trades to give any of their votes for other proposals, because those deals take away some of their votes against the sanctions proposal. In this case, if I managed to make a deal with Siam so that they would vote for/against one of the other two proposals, I'd be weakening their voting power against sanctions.

**Comment by RecursiveVision** [comment]
@Mileslewis
