### ISSUE TITLE
Food discrepancy

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#7762]
_1. Mod version (i.e Date - 4/14):_
4/16/21

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The UI's math for food in Lisbon doesn't add up, there should be a surplus of food in Lisbon, but it's stagnating.

_4. Steps to reproduce (optional):_
[Food Lisbon Discrepancy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6367227/Food.Lisbon.Discrepancy.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by SuperNoobCamper** [comment]
had it a couple of times after recovering from unhappiness or the resistance till the courthouse is built, mostly it's a visual bug and it does refresh and show the correct values next turn.

**Comment by ilteroi** [comment]
probably fixed
