### ISSUE TITLE
Imperialism nerfed after puppets change - rebalance request

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#7764]
_1. Mod version (i.e Date - 4/14):_
4/16/21

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
After the puppets' change (no buildings except defense), two Imperialism policies seem to have been greatly nerfed (Martial Law and Civilizing Mission), with nothing to compensate it, so that's perhaps something to look at for rebalancing purposes if the puppets change is here to stay.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
hmm how about they allow production buildings respectively gold buildings in puppets

**Comment by LukaSlovenia29** [comment]
Yeah, that might work! Maybe we could also brainstorm on the forum which buildings to allow puppets to build? For example workshops technically aren't a gold building per se (like a bank), but it still usually is gold-positive or at least gold-neutral due to gold on forests, not to mention the production benefits.

**Comment by ilteroi** [comment]
it's not so easy to implement though .. just an idea

**Comment by LoneGazebo** [comment]
@ilteroi we need to look at this again -  I think making puppets construct buildings up to one era prior (instead of just defense) makes the most sense.

**Comment by ilteroi** [comment]
i don't have strong feelings either way

**Comment by RecursiveVision** [comment]
@ilteroi @LoneGazebo I merged all changes from oleole and fixed the merge/build errors in RSI, then changed the logic to this:

```
#if defined(MOD_BALANCE_CORE_PUPPETS_LIMITED_BUILDINGS)
		//puppets will build fewer buildings
		if (CityStrategyAIHelpers::IsTestCityStrategy_IsPuppetAndAnnexable(m_pCity))
		{
			//too new? not ok
			if (pkBuildingInfo->GetEra() > kPlayer.GetCurrentEra() - 1)
				continue;

			//option: disallow everything (EXCEPT defense buildings) that costs maintenance if we are running a deficit
			if (pkBuildingInfo->GetDefenseModifier() <= 0)
			{
				static EconomicAIStrategyTypes eStrategyLosingMoney = (EconomicAIStrategyTypes)GC.getInfoTypeForString("ECONOMICAISTRATEGY_LOSING_MONEY", true);
				if (pkBuildingInfo->GetGoldMaintenance() > 0 && GET_PLAYER(m_pCity->getOwner()).GetEconomicAI()->IsUsingStrategy(eStrategyLosingMoney))
					continue;
			}
		}
#endif
```

...which should hopefully address both the balance concerns and ilteroi's concern about the AI building expensive buildings and running deficits in puppets.
