### ISSUE TITLE
Militaristic CS unit gifts

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#777]
Posted by nametaken on Civfanatics:

"One other bug that I think has been in the CP for a while now is that Militaristic City States will quite often gift non-UU's for being allied with them instead of a UU. "

Also, Strigvir's complaint comes in mind about the fact that militaristic CS with early UUs give only (worthless?) generic units for the rest of the game.

**Comment by LoneGazebo** [comment]
I'll take a look.

**Comment by LoneGazebo** [comment]
Looked at CS unit code, and it seems alright. Tweaked it a bit, but otherwise good. I think strigvir's point is a complaint about not getting UUs after they obsolete, which is by design.
