### ISSUE TITLE
[Bug/Feature?] Militaristic CS naval UU gift destination

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#7770]
4/16 version.

![image](https://user-images.githubusercontent.com/14953746/115987843-6d9e8380-a5e9-11eb-9fa0-487962c4847e.png)

Valletta here can give out Sea Beggar, yet they prefer to gift Cannons to Prague because it's the closest city, instead of gifting Sea Beggars to my closest coastal city.

Is it possible to change it so naval UUs are given to nearest coastal city when available?

**Comment by RecursiveVision** [comment]
This is unintended behavior, could you provide a save file? @azum4roll

**Comment by azum4roll** [comment]
Modpack (use your own EUI): https://mega.nz/folder/3P4Q1TpS#jaO3Ac9IQOzOGxJ6gXA-0g
Save (make sure you put it in Saves/single, not ModdedSaves/single): [Askia_0250 AD-1700.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6372212/Askia_0250.AD-1700.zip)

**Comment by RecursiveVision** [comment]
MEGA isn't working for me.

**Comment by pineappledan** [comment]
Users of my mod are reporting they are being gifted zeppelins by every city-state, regardless of what unique they are supposed to gift

**Comment by RecursiveVision** [comment]
That's probably an issue with @ilteroi's changes to GetCompetitiveSpawnUnitType()...not that it was working well beforehand.

**Comment by LoneGazebo** [comment]
@ilteroi take a look at GetCompetitiveSpawnUnitType, see if bugged?
