### ISSUE TITLE
CTD when Opening Advisor Panel

### ISSUE THREAD

**Issue by TranceBlossom** [LoneGazebo/Community-Patch-DLL#7771]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
CTD on clicking my own civ's icon (Portugal) to open the advisor panel

_4. Steps to reproduce (optional):_
Click on my own civ portrait

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6372094/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[AutoSave_0071 BC-1160.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6372095/AutoSave_0071.BC-1160.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6372098/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
This is a LONG running crash.
