### ISSUE TITLE
Multiple embassies in city

### ISSUE THREAD

**Issue by youngsteve11** [LoneGazebo/Community-Patch-DLL#7772]
_1. Mod version (i.e Date - 4/14):_4/16

_2. Mod list (if using Vox Populi only, leave blank):_infoaddict

_3. Error description:_ Not sure if error, but I have had an embassy in Tyre, my neighbour, for along time, & just now Morocco has also planted one. I hadn't realised you could put another down, though info does seems to say you can, but just seems strange & a waste of a GD as neither Tyre or myself are going anywhere, & even if Tyre is conquered any benefits wouldn't go to Morocco.

_4. Steps to reproduce (optional):_
[AutoSave_0271 AD-1802.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6372480/AutoSave_0271.AD-1802.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Bug, intended to be 1 per CS.

**Comment by youngsteve11** [comment]
Are you sure as the civilopedia in game is a bit ambigious suggesting only the first to build embassy will get the delagtes, & seems to suggest you can build another even though you wouldn't gain any additional delegates. Perhaps the civilopedia wording needs to change slightly as well.

**Comment by RecursiveVision** [comment]
@LoneGazebo ?

**Comment by LoneGazebo** [comment]
not allowed.
