### ISSUE TITLE
4-16 : Wrong More GPs version !

### ISSUE THREAD

**Issue by GLop4** [LoneGazebo/Community-Patch-DLL#7773]
_1. Mod version: 4-16

_3. Error description:

4-16 comes with the old (and very buggy) **More GPs​ v2** instead of **MoreGPs v3 rev6**

**Comment by GLop4** [comment]
Also:
\(1) Community Patch\Modules\MoreGP\ExtraGPs.sql
**must be UTF-8 encoded (Currently ANSI)**
To have accents instead of blank writing

**Comment by azum4roll** [comment]
Would explain the blank art I got.

**Comment by LoneGazebo** [comment]
hmm. not sure why. link newest?

**Comment by GLop4** [comment]
Original link still there:
[https://drive.google.com/file/d/1efSEwc7Fix2KKK9ZJiGFmLXArFo11wSZ/view](url)

All the material is perfectly integrated into 3-2
