### ISSUE TITLE
Can't plunder trade routes

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#778]
Posted by Gidoza on Civfanatics:

"A bug I encountered later in the game - after turn 300, but I can't pick out a specific technology (some people had the more modern version of Cargo Ships, others didn't).

Even when at war with a civ, if I moved my vessel onto their cargo ship, the tooltip showed that I had to declare war on that civ to plunder the cargo ship. Earlier in the game, this wasn't happening - it simply started at some point, and stayed that way for the rest of the game. "

**Comment by LoneGazebo** [comment]
A corporation (cannot recall which one) makes your trade units immune to plunder IIRC.

**Comment by Edaka** [comment]
Yeah, I figured that might be the case. By the way, this and the other couple of unique trade unit related features (like sight, double movement speed, increased distance etc.) for some specific corporations are only listed in the Civilopedia, but not in in-game building tooltips. Might be worth adding that info?

**Comment by LoneGazebo** [comment]
It's in the helper text now.
