### ISSUE TITLE
Quest not considered during war or planning war?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7787]
In the rewritten CvEspionageClasses::BuildOffenseCityList(), the logic goes:

If at war or planning war, diplo modifier +15

ELSE, process a bunch of modifiers, including quests (25) and denouncements (33) which are larger than 15.

It's worthwhile for the AI to target cities of players they are at war with more than those of players they've denounced, IMO. Furthermore, if war is being planned, the AI can change their mind, and if they don't end up declaring war after all they lose out on the benefits of considering the other factors. In all cases, the quest should be considered.

I can understand the rationale of wanting to avoid placing spies in cities that will be conquered soon, but isn't there a way to test if a city is likely to fall before the spy mission would end? @ilteroi ?

**Comment by LoneGazebo** [comment]
I don't know if there's a function that reliably guesses turns to fall for a city.

**Comment by RecursiveVision** [comment]
@LoneGazebo How about avoiding current targets and cities that are under siege?

**Comment by LoneGazebo** [comment]
well the new mechanic can sap a city, so i'm not sure that's a good idea.

**Comment by RecursiveVision** [comment]
Hmm, good point. Hard to fix.
