### ISSUE TITLE
Foreign leader screen: no text / options displayed

### ISSUE THREAD

**Issue by TooManyCords** [LoneGazebo/Community-Patch-DLL#7788]
_1. Mod version (i.e Date - 4/14):_4/29

_2. Mod list (if using Vox Populi only, leave blank):_ 3rd and 4th UC, better lakes, Wonder expanded, World Congress Reformation, Modern Navy (or whatever it's called)

_3. Error description:_ When I meet a foreign leader, there isn't anything displayed other than the leader holding their sword (or whatever). No trade, no talk, no anything. When I click on their portrait, it does not bring up the diplomacy screen with them

_4. Steps to reproduce (optional):_ Start a game, meet any leader.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TooManyCords** [comment]
The mod conflict appears to be with 3/4UC (when I disabled it, the leader options displayed again).

Specifically the conflict is between VP 4/29 and 3/4UC v67 (but I haven't tested with older versions of 3/4UC)

**Comment by LoneGazebo** [comment]
I’d need logs. I’m guessing it’s a lua error.

**Comment by TooManyCords** [comment]
How do I get logs without a crash? (sorry, I've only done them that way)

**Comment by LoneGazebo** [comment]
They’re in your docs/civ 5/logs folder. I want the lua log

**Comment by TooManyCords** [comment]
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6402373/Lua.log)

**Comment by LoneGazebo** [comment]
@RecursiveVision 'GetMoodInfo' error in lua

**Comment by RecursiveVision** [comment]
Only with 4UC? Strange. I'll investigate.

**Comment by inkyant** [comment]
Not sure if this helps, but 4UC is glitching because Austria's UB blocks spies. Not sure if the errors are related.
But looking through their logs they don't seem to get the error I do, `no such column: BlockScienceTheft`

**Comment by pineappledan** [comment]
Oh, is it to do with the new espionage stuff? Do I need to delete all the blocksX action bonuses?

**Comment by RecursiveVision** [comment]
@pineappledan That may be a contributor, see if removing that resolves it.

**Comment by LoneGazebo** [comment]
Yes, sorry @pineappledan all that stuff is gone now.

**Comment by LoneGazebo** [comment]
at present, no. It was such a kludgey system. I'd replace with positive/negative espionage modifiers.
