### ISSUE TITLE
4/29 - No puppet option on Conquest

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7791]
_1. Mod version (i.e Date - 4/14):_
4/29

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When I conquered this city, there was no popup window to select what type of city, it was immediately annexed.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/116648294-4d9cf600-a942-11eb-8807-ecb1b88b53f5.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Update: So I think this may be linked to the Spy Icon error (7790). When I cleared the icon with a reload, I was able to puppet normally.

**Comment by Stalker012345** [comment]
Update: Ok its not the Spy icon error, as I had cleared that and took another city which did not give me the puppet window. So I have had 3 cities taken with no window, and one time with the window. The one time I did get the window was a retake of a city if that matters.

**Comment by RecursiveVision** [comment]
Longrunning bug, cause unknown.

**Comment by LoneGazebo** [comment]
![image](https://user-images.githubusercontent.com/7849458/116702267-81057200-a98e-11eb-8bb1-b1cd3dff0906.png)

**Comment by LoneGazebo** [comment]
just tested....works for me?

**Comment by RecursiveVision** [comment]
@LoneGazebo Reloading seems to fix it IIRC

**Comment by Stalker012345** [comment]
> Longrunning bug, cause unknown.

Well I've gone from never seeing that in the last 50 games I've played to "I have now seen it 4 times in the same game". So pretty sure something changed:)
