### ISSUE TITLE
No event

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#7792]
1. Mod version (i.e Date - 4/14):
4/29

2. Mod list (if using Vox Populi only, leave blank):

3. Error description:
I play with events system on but it doesn't seem to work.
No event is triggered.....

**Comment by LoneGazebo** [comment]
?

**Comment by Padre19** [comment]
I mean, I don't get any other events. They seem disabled due to espionage.

**Comment by LoneGazebo** [comment]
How many turns? Events are working on my end.

**Comment by LoneGazebo** [comment]
I see why. Fixed.
