### ISSUE TITLE
txt_key_building errors

### ISSUE THREAD

**Issue by mcymsb** [LoneGazebo/Community-Patch-DLL#7793]
_1. Mod version (i.e Date - 4/14):_

4/29

_2. Mod list (if using Vox Populi only, leave blank):_

Enlightenment era for VP

_3. Error description:_ 

txt_key_building errors with enlighenment era for VP

I tried rolling back 4/16 and it had no problem. When updated to 4/29, buildings text become broken

and i tried removing cache folder, didnt work

<img width="960" alt="ss1" src="https://user-images.githubusercontent.com/62123081/116687675-c9169b80-a972-11eb-89d6-256de37b2d78.png">

_4. Steps to reproduce (optional):_

Enable EE for VP with 4/29 and reproduce
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by mcymsb** [comment]
i been digging into some files and saw that from 'CoreTableEntries.sql', 

-- Increases the cost by this amount every time you build the unit
ALTER TABLE Units ADD 'CostScalerNumRepeats' INTEGER DEFAULT 0;

this recent change made txt_key error. 

Any idea why?

**Comment by LoneGazebo** [comment]
check your database log. Probably a duplicate entry.
