### ISSUE TITLE
4/29 - Skimisher Doctrine is always a penalty

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7795]
_1. Mod version (i.e Date - 4/14):_
4/29

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Skimisher Doctrine is showing a -20% in flood plains instead of the +40%

UPDATE: Not working in plains either, assuming its just not working period.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/116736088-07cd4580-a9b5-11eb-8a76-1986ab923cbe.png)

![image](https://user-images.githubusercontent.com/20593976/116736400-74e0db00-a9b5-11eb-81cc-49d3f72e86cd.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi what did you chance to rough, and did it translate to the promotion area of cvunit?
