### ISSUE TITLE
Notifcations Not Displaying - All Events Not Triggering (no-eui)

### ISSUE THREAD

**Issue by vetox20** [LoneGazebo/Community-Patch-DLL#7798]
_1. Mod version (i.e Date - 4/14):_
4-29-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Notifications (barbarian spawn, AI completed wonder, etc.) do not display, but you can hear the notification sound
Events system is enabled, but no events (non spy) are triggering

_4. Steps to reproduce (optional):_
Play a few steps, you'll hear it and not (see) it :)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6409563/Logs.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Nigel--C** [comment]
I'm getting the same problem.

**Comment by LoneGazebo** [comment]
Are you on the latest?

**Comment by Nigel--C** [comment]
Yes, 4-29-3.
