### ISSUE TITLE
Upgrade button wrong tooltip

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7799]
_1. Mod version (i.e Date - 4/14):_4-29-2

_2. Mod list (if using Vox Populi only, leave blank):_ pinappledan's powerplants, quick turns

_3. Error description:_ 

This old issue is still with us. Hovering over the upgrade button, in case of insufficient funds, the tooltip displays wrong info.
![20210501160726_1](https://user-images.githubusercontent.com/16341598/116783531-da0cfd00-aa97-11eb-96cf-55d27e96af9a.jpg)

[bad tooltip.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6409594/bad.tooltip.zip)

**Comment by LoneGazebo** [comment]
Need lua log from hover

**Comment by saamohod** [comment]
Cannot do at the moment. Feel free to close.
