### ISSUE TITLE
CIV 4 Diplo Mod - War starting after CS declaring war

### ISSUE THREAD

**Issue by RDeluxe** [LoneGazebo/Community-Patch-DLL#78]
What happened : 
- Germany is my vassal. I'm at war with Ethiopa, and so was Germany.
- My turn starts : I make peace with a city state which was previously allied with Ethiopia.
- I end my turn. 
- Germany, during its turn, makes peace with Ethiopia
- Ethiopia regains control of the previously mentionned CS : this CS declares war on me and ...
- Germany and Ethiopia starts being at war again 
- And the CS is at war with me.

So it seems that the CS changing its state toward me (peace/war) triggered a war between Germany and Ethiopia, which in the same turn signed a peace treaty. If I remember correctly, it's impossible to declare war again (during X turns) after a peace treaty (I don't know if the AI must respect this rule though), which leaves only one possibility : an automatic war trigger because of the CS, which does not seem to make sense to me.

From Gazebo : "This is a lingering bug in the civ 4 diplomacy features mod. As I didn't write the mod, I'd have to spend some time with it to figure out how to solve it. It is a fringe case, and an odd one at that, but I'll keep it in mind if I ever get around to fixing that mod."

![image](https://cloud.githubusercontent.com/assets/2767681/5347528/70722ece-7f29-11e4-97cf-a6c45c6054e4.png)

**Comment by LoneGazebo** [comment]
This is an old issue, but I think I've fixed it by virtue of making it impossible for vassals to make peace before their master has done so. I've also added some sanity checks to the CS code for DOWs to prevent this.
