### ISSUE TITLE
tooltip error with "goddess of love" pantheon

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#780]
tooptip said it would give +5 and +3, scaling with era. i'm in the ancient era still and i'm visibly gaining +7 and +4 for every citizen born. im guessing nobody else ever noticed because nobody picks this pantheon =) i don't know if the tooltip is wrong or the ability is giving more than it should.

**Comment by LoneGazebo** [comment]
Ah, you are on a non-standard gamespeed, no? It scales with gamespeed too. I'll update help text to reflect this.

**Comment by deadstarre** [comment]
yes i play on epic- i guess that was it. i forgot about game speed scaling- ill try to keep this in mind next time i see something similiar =( mostly i just take the tooltips at their word without thinking the speed scaling through
