### ISSUE TITLE
Strange popups

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7805]
_1. Mod version (i.e Date - 4/14):_4-29-3

_2. Mod list (if using Vox Populi only, leave blank):_pineappledan's powerplants, quick turns, flag promotions

_3. Error description:_ 

Playing as Egypt I get this seemingly nonsensical message

![20210502151202_1](https://user-images.githubusercontent.com/16341598/116812750-15bbcb80-ab59-11eb-912c-ec9580f3232a.jpg)

[Ramesses II_0225 AD-1575.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6411298/Ramesses.II_0225.AD-1575.zip)

**Comment by vetox20** [comment]
Received same in game as Japan using 4-29-3, and no mods other than VP

**Comment by Cyclopia31** [comment]
Same here, I think these are the notifications relating to the new spy system, but they are bugged.

**Comment by CyberPhy** [comment]
I also have the same problem 
![Bug 1](https://user-images.githubusercontent.com/21373332/116943730-26943c00-ac42-11eb-88ef-b81dc12ba6cf.PNG)
I think its because of the new spy thing with poisonings the water supply as my city went down to one pop right after that happened
