### ISSUE TITLE
Cities get auto-annexed, no puppet option given

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7806]
_1. Mod version (i.e Date - 4/14):_4-29-3

_2. Mod list (if using Vox Populi only, leave blank):_pineappledan's powerplants, quick turns, promotion flags

_3. Error description:_  Playing as Egypt, England declares war on me. Eventually I capture their city, choose to puppet it and sign peace. After a while I declare on them, capture their capital London, it gets annexed automatically, no choice window to puppet pops up. I capture a second city, same again. No selection regarding the city's fate is given.

[AutoSave_0245 AD-1675.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6411545/AutoSave_0245.AD-1675.zip)

In the savegame above capturing Canterbury will expose the bug.

**Comment by Cyclopia31** [comment]
I have the same problem here : 
![image](https://user-images.githubusercontent.com/80354202/116819542-c1bce100-ab70-11eb-88e3-758bd32dce0c.png)

When I capture Wittenberg the city is annexed automatically, I can't puppet it or liberate it.
Here the save (VP 4-29-3+ EUI) : 
[Autosave City annexed.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6411771/Autosave.City.annexed.zip)

**Comment by saamohod** [comment]
Just noticed that restarting the game fixes the problem, at least for the first capture.

**Comment by azum4roll** [comment]
Can you try opening the tech tree via hotkey (F6 I think?) then closing it normally between city captures? That's the vanilla MP menu fix.

**Comment by Stalker012345** [comment]
I'll actually note that I have seen the behavior on the first city capture, not just on subsequent ones.

**Comment by Stalker012345** [comment]
Oh its even worse, the annexed city doesn't auto invest the courthouse!

**Comment by azum4roll** [comment]
Because it's not actually "annexed". It's just in a limbo state, and you could actually get the popup some time later (and choose to puppet/raze).

**Comment by Stalker012345** [comment]
> Just noticed that restarting the game fixes the problem, at least for the first capture.
> EDIT: yeah, the proper behaviour only happens once the first city is captured. Any consecutive city captures get annexed automatically.

Just want to note that reloading saves is NOT working for me. The bug simply occurs with no remediation at the moment.

**Comment by Stalker012345** [comment]
@LoneGazebo what more info do you need? More save games?

This happens to me continuous, I haven't seen a window for annex vs puppet in my last 6 conquests.

**Comment by LoneGazebo** [comment]
it sounds like a lua issue, are you getting errors in your lua log?

**Comment by Stalker012345** [comment]
So I've attached all the logs right as I have taken a city where no popup was given. I see the following errors in lua.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6492500/Logs.zip)


[307706.546] Runtime Error: C:\Users\Travis\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files/CoreLua/CityEventPopup.lua:47: attempt to index local 'city' (a nil value)

[310382.421] Runtime Error: C:\Users\Travis\Documents\My Games\Sid Meier's Civilization 5\MODS\Promotion Flags EUI for VP (v 3)\Promotion Flags EUI for VP (v 3)\UI\UnitPanel.lua:1673: attempt to call method 'getNumFriendlyUnitsOfType' (a nil value)

**Comment by LoneGazebo** [comment]
well the second one is a modmod, but I can add that method's lower case element in the DLL (easier than getting a modmod to work). The first one might be the culprit, as a bad queued popup could bork the whole stack.
