### ISSUE TITLE
No AI's reaction to Luxury Ban proposal

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#7807]
_1. Mod version (i.e Date - 4/14):_4-29-3

_2. Mod list (if using Vox Populi only, leave blank):_pineappledan's powerplants, quick turns, promotion flags

_3. Error description:_ 

No more text about which civs will like or dislike my Luxury Ban proposal.

**Comment by RecursiveVision** [comment]
@Mileslewis

**Comment by Stalker012345** [comment]
Oh yes, this has actually been there for a few versions now, I kept forgetting to mention it

**Comment by azum4roll** [comment]
Same for Passport System. I doubt nobody cares.

**Comment by Mileslewis** [comment]
I'm planning some changes to this system so I'll test it properly when I do that.
