### ISSUE TITLE
4/29 HF2 - Coal not showing up as a resource

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7808]
_1. Mod version (i.e Date - 4/14):_
4/29 HF

_2. Mod list (if using Vox Populi only, leave blank):_
(UI) Trade Oppurtunities +

![image](https://user-images.githubusercontent.com/20593976/116826585-58ca6e80-ab5a-11eb-8fa1-fff9463f9923.png)

_3. Error description:_ 
Going into Industrialization, coal is not even appearing as an option for me on my toolbar, and I'm not seeing any coal on the map.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/116826699-ef972b00-ab5a-11eb-9d17-ed86507d59bd.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Update: I can still utilize coal from refineries and the statecraft finisher, so its not that coal is completely removed, but it just doesn't exist on the map or on my toolbars.

**Comment by LoneGazebo** [comment]
What map script?

**Comment by azum4roll** [comment]
Check if they exist on the monopoly menu?

**Comment by Stalker012345** [comment]
So I had so many weird bugs in my last game, things I have never seen before.... that I just assumed my game had been corrupted or something. So I have done a complete reinstall to see if it clears things up. I have already noticed some of the things I had mentioned before are gone. So I'll close this for now, and if it comes back then I'll report it again.
