### ISSUE TITLE
barbarians attacking and healing on the same turn from camps

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#781]
archers shooting out of barb camp and healing on the same turn. pretty sure i saw this mentioned as a confirmed bug in forums, just not sure if a fix was in the works yet- thought i'd post it here in case it was forgotten

**Comment by LoneGazebo** [comment]
Ilteroi has claimed this is not possible, but a lot of users continue to report it. I've paged him.

G

**Comment by Edaka** [comment]
Still happening, yes. May any kind of logs be of use?

**Comment by deadstarre** [comment]
i literally havnt seen a single barb archer that won't do this lately- for me its not a rare occasion its beginning to feel like a balance change i need to deal with. should be easy to replicate? take an archer to clear a barb camp with an archer stationed in it- see how that plays out

**Comment by ilteroi** [comment]
indeed, i've seen it now ... shouldn't be hard to fix now
