### ISSUE TITLE
6/29 HF2 - Spy Screen, clicking on Show City button is not working

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7810]
_1. Mod version (i.e Date - 4/14):_
6/29 HF2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I presume that little button in the upper left is supposed to show me the city based on the hotfix notes. But clicking on the button does not do anything.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/116848394-29dfe700-abb2-11eb-9414-f37ecdf01e3a.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Button isn’t supposed to look like that. I’m releasing a fix today I think my merge tool didn’t grab all my files.
