### ISSUE TITLE
6/29 HF2 - Seaport and Train Station allowed in same building queue

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7811]
_1. Mod version (i.e Date - 4/14):_
4/29 HF2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I can put the Train Station in the same building queue as a seaport, I can even invest in both.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/116915941-4ca1e800-ac12-11eb-83d1-d6a7fe623d5b.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bsesar** [comment]
Where you able to build both?

**Comment by Stalker012345** [comment]
> Where you able to build both?

No, once the seaport finished the Train Station was stripped from the queue.

**Comment by LoneGazebo** [comment]
hmm, the queue is tricky to monitor. I'd need to spend some time looking at the updater, as it runs frequently and can get expensive.
