### ISSUE TITLE
Changing MinDistanceCities Had No Effect

### ISSUE THREAD

**Issue by grmagne** [LoneGazebo/Community-Patch-DLL#7812]
1. Mod version 4/29

2. Only Vox Populi.

3. Updating the MinDistanceCities variable in the WorldSizes.sql file no longer works. Everyone builds cities at distance 3 even if the variable is changed to 4. This has never occurred before in any previous version. The changes I make are listed below.

4.  -- Standard - 3 Minimum for Major, 2 for Minor

UPDATE Worlds
SET MinDistanceCities = '4'
WHERE Type = 'WORLDSIZE_STANDARD';

UPDATE Worlds
SET MinDistanceCityStates = '4'
WHERE Type = 'WORLDSIZE_STANDARD';

-- Min City Range
UPDATE Defines
SET Value = '4'
WHERE Name = 'MIN_CITY_RANGE';

**Comment by ilteroi** [comment]
how do you define distance? three plots between the cities means distance is four!

**Comment by grmagne** [comment]
The problem seems to have been fixed since I posted this issue. The AI is now forced to build cities 4 plots apart if I set MinDistance to 4.
