### ISSUE TITLE
6/29 HF2 - Kidnap Specialist Boost not decaying with Time

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7813]
_1. Mod version (i.e Date - 4/14):_
6/29 HF

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I haven't made any Kidnap Specialist missions in quite some time, but I don't think my specialist yields are coming back down after the 10 turn duration, they seem to remain high.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/116936906-12464400-ac2e-11eb-91c5-8834dd4d78fb.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Future version confirmed!
