### ISSUE TITLE
4/29 HF2 - Minefield slows movement, but performs no damage.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7815]
_1. Mod version (i.e Date - 4/14):_
4/29 HF

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
After a long naval engagement, I can confirm that not only does the minefield slow work, it is working on every single enemy water tile (so the "worked tile" clause is not present, its just any border water tile). However, there is no damage being done at all, just the slow effect.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
I prefer it working this way, actually. Slowdown effect on all owned tiles.

**Comment by LoneGazebo** [comment]
haha I'm actually about to switch this because the other mechanic can't work (I forgot that naval units blockade adjacent tiles, so adjacent tiles can never inflict damage). 

Now, minefield will work like Great Wall - ends all movement upon entering city limits via water. Additionally, it deals 5 damage to every unit that ends its turn in deep water. So coastal tiles are safe, but vulnerable to land units.

**Comment by azum4roll** [comment]
Does it stop neutral missionaries as well like the current Great Wall? Not sure if that's a bug or a feature.
