### ISSUE TITLE
better tooltip for unhappiness effects

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7817]
it seems prices for buying units vary with the local unhappiness in the city. but the tooltip doesn't include any details. i'm not so sure it's even necessary, what good does it do?

also, unhappiness gives negative growth modifier but it's similarly intransparent. in that case i can at least understand why it's there, but it still seems unpredictable.

**Comment by RecursiveVision** [comment]
I think the unit production penalty is generally unpopular, I've seen several complaints about it, since it makes it much harder to defend yourself against often hostile neighbors.

**Comment by RecursiveVision** [comment]
Not saying it's bad but it doesn't seem to be effective at punishing warmongers, and doesn't war weariness already do this?
