### ISSUE TITLE
How viable is...?

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#782]
I have a rudimentary idea for a Currency mechanic, which I've always hoped to develop. But before I go too far, I wanted your expert advice on how viable some of the things I want to do are, as they will invariably require the CP DLL (including on whether we're pushing the DLL too much).

The idea would be that the relative strength of Currencies would be translated as 'Prosperity,' which determines how much happiness Luxury Resources produced (homogeneously) (among other effects which can be handled using existing methods), similar to how its based on population in the CBP. Would something like that be possible? Basically to allow me to set the happiness value of luxuries in Lua?  

In addition, to that, I'd need to cache one thing: the player's currency choice - so a Player:SetCurrency(currencyID), Player:GetCurrency(), and a corresponding GameEvent.CurrencyAdopted. Prosperity would be a calculation like Sovereignty, so wouldn't need similar functions.

Of course, I'd develop everything with the TableSaveLoader first, and formulate a more robust plan before actually requesting anything. I just wanted to know if the luxury-happiness thing is possible, as this would be fundamental to the system.

Incidentally, would we be pushing the DLL to its limit if we discussed 'On Mercenaries'? This is a mod which requires TSL extensively, and some users have reported erratic behaviour when reloading - so if it's possible to push its values into the DLL, that would be ideal. But I don't want to take up precious memory on something that isn't quite as imperative.

**Comment by LoneGazebo** [comment]
Well, the question is (re: happiness and luxuries), if it is similar enough to the CBP model, why not just use the CBP model? I can make sure that the code is separate from all other happiness changes if you'd like.

I mean, if it involves numbers and crunching them it's theoretically possible in the DLL. Since you'd only be saving a couple of integers per player it wouldn't be memory-heavy, so the key would be figuring out how you want the algorithm to function. We can hash out numbers later, but a defined model of what you want it to look like would be a good first step.

Re: mercenaries, how many table entries are we looking at?

G

**Comment by JFDaly** [comment]
I'd still intend for the happiness value to be based on 'Prosperity,' rather than Population. But come to think of it, I could use the 'ExtraHappinessPerLuxury' policy tag to get what I want - or, if you can create a Player:SetExtraHappinessPerLuxury()/GetExtraHappinessPerLuxury() function, that would accomplish things perfectly without needing a dummy policy. What do you think?

On Mercenaries: that you ask means its probably too intensive. There are at least 100 Contracts in the mod, and although not all can be active at once, each would need to be saved individually, and each of those has a few different values that would need storing (length of contract, a unitID, a resourceID, and a resource count) and retrieving from the specific Contract ID. So I'd wager it should be left with TSL  and I might hit up someone else to take a look at why TSL's failing on occasion.

**Comment by LoneGazebo** [comment]
Hmm...If it's over 100 entries, it'd probably be easiest to store that in a unique table in the DLL. If you can figure out why it is messing up on load using your TSL loader system, do that. If not, we'll pursue the DLL entries.

**Comment by JFDaly** [comment]
Thanks. Good to know it can be a last resort. I'll make a proper thread about it if need be.

**Comment by LoneGazebo** [comment]
Sounds good.
