### ISSUE TITLE
Venice Colonia puppet building Wonder

### ISSUE THREAD

**Issue by youngsteve11** [LoneGazebo/Community-Patch-DLL#7820]
_1. Mod version (i.e Date - 4/14):_4/16

_2. Mod list (if using Vox Populi only, leave blank):_Infoaddict

_3. Error description:_ I asked a question regarding Venice Coronia cities, & Recursive said they can build anything but wonders. In Medieval Age & one builds Petra, which somehow hadn't yet got built. 
[AutoSave_0155 AD-0900.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6428695/AutoSave_0155.AD-0900.zip)

Secondry, I was building a wonder myself & wanted to slow Cattoro down so purchaed a building for it to build, but when doing this building disappeared from queues & wasn't built. Tried the same thing in another city with same result.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6428718/Logs.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
old version

**Comment by youngsteve11** [comment]
Thanks. So these things have been resolved with Venice in latest patch.
