### ISSUE TITLE
policies and city count

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7821]
is there any dependency between AI policy choice and wide/tall play?

i often see players with island starts choosing progress, or even worse, progress players sitting at two cities although there is space.

conversely, tradition players sometimes found a lot of cities ...

![image](https://user-images.githubusercontent.com/1358966/117207616-6c910180-adf4-11eb-9987-1e6a40190279.png)

germany here chose progress (2 cities), japan is traditino (6 cities), rome tradition (6 cities), byzantines tradition (6 cities)

**Comment by R3P0FFXI** [comment]
Makes no sense as Progress has option for city connections +3 science and food per connection, progress should be expansive

**Comment by LoneGazebo** [comment]
Yes, see Firaxis::Array< int, NUM_YIELD_TYPES > CvPolicyAI::WeightPolicyAttributes
