### ISSUE TITLE
txt_key error

### ISSUE THREAD

**Issue by mcymsb** [LoneGazebo/Community-Patch-DLL#7822]
_1. Mod version (i.e Date - 4/14):_
5/5

_2. Mod list (if using Vox Populi only, leave blank):_

EE for VP
_3. Error description:_ 
I posted once and checked the database but i dont know  how to solve it

heres the database.log please tell me how to fix it
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6431987/Database.log)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by mcymsb** [comment]
just noticed 

removing "ALTER TABLE Buildings ADD COLUMN 'BlockScienceTheft' INTEGER DEFAULT 0;"

causes the txt error. why is that?

**Comment by skodkim** [comment]
Mod incompatibility. Delete Localization/IGE_ZH_CN.xml from IGE mod and replace XML/Hokath/ReligiousEvents/CouncilOfElders.xml from the events mod with the file in the attached zip (personal fix I made for myself)
[CouncilOfElders.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6435092/CouncilOfElders.zip)

**Comment by mcymsb** [comment]
> Mod incompatibility. Delete Localization/IGE_ZH_CN.xml from IGE mod and replace XML folder from the events mod with this folder (fixes to mod made for my personal use)
> [XML.ZIP](https://github.com/LoneGazebo/Community-Patch-DLL/files/6435114/XML.ZIP)

sry i dont understand what you mean by that

**Comment by mcymsb** [comment]
its still there... txt key wont go away

**Comment by skodkim** [comment]
That was just one fix - you have other incompatible mods - look in you database.log file and you'll se references to items in the files that are clearly not from this mod
