### ISSUE TITLE
5/5 Getting massive faith bonus risning with each researched tech (apstolic tradition?)

### ISSUE THREAD

**Issue by creamedpickle** [LoneGazebo/Community-Patch-DLL#7824]
_1. Mod version (i.e Date - 4/14):_
5/5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Getting massive faith bonus (and a new great prophet) scaling with each researched tech, earliest save I had it was it is 7300.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6436238/Logs.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
5. ![Massive faith bonus](https://user-images.githubusercontent.com/83774710/117330111-a5cd7e00-ae95-11eb-90ab-41c190621892.jpg)

**Comment by raymond-sutandar** [comment]
I can confirm this is an issue; it's happening to me as well.

**Comment by creamedpickle** [comment]
> 
> 
> I can confirm this is an issue; it's happening to me as well.

With other civs than Austria? Maybe even before the 5/5 release aswell?

**Comment by skodkim** [comment]
If I understand this big correctly it can throw off balance entirely in a game. I was planning to start a new game tomorrow morning (10 hours or so). Should I wait for a fix? Maybe I can just disable the belief?

**Comment by LoneGazebo** [comment]
Hot fix is incoming soon. Today. Hour or less or it’s free.

**Comment by LoneGazebo** [comment]
I just did it as a quick fix, ill get a better fix for the next one :)

**Comment by pineappledan** [comment]
I'd recommend taking a look at the Extra beliefs mod. The Revelation founder belief is what that table was designed for, and I feel it is more congruent with the existing beliefs than the new, double-barreled beliefs.
https://forums.civfanatics.com/threads/pineappledan-hungryforfood%E2%80%99s-new-beliefs-mod.656517/
