### ISSUE TITLE
5/5 - Spy Notification Text Errors and Cleanup

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7826]
_1. Mod version (i.e Date - 4/14):_
5/5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Just some general issues on a couple of text boxes for cleanup.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/117343387-dac3db80-ae69-11eb-8738-74fd66b3fd06.png)

![image](https://user-images.githubusercontent.com/20593976/117343423-e6170700-ae69-11eb-89d3-5bc8ae5b2eee.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Fixed, missing a bool
