### ISSUE TITLE
small peformance issue with CalculateStartingVotesForMember

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7828]
CalculateStartingVotesForMember() shows up in the profiler, it's called a lot from CvDiplomacyAI::IsCloseToDiploVictory().

is there a simple way to optimize this?

**Comment by LoneGazebo** [comment]
you could probably create a cached value that updates once per turn and have CalculateStartingVotesForMember(true) where true == get quick cached value

**Comment by RecursiveVision** [comment]
I tried to reduce the number of calls but the IsCloseToVictory functions end up called fairly often. We cached the culture victory call in the same way.
