### ISSUE TITLE
5/5 HF1 - AI still abandoning Citadels

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7830]
_1. Mod version (i.e Date - 4/14):_
5/5 HF1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Wasn't sure if any work had been done on it, but just noting the AI still pulls out of citadels much too quickly.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/117480102-c560b700-af26-11eb-9a56-8bc95fdb4237.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
duplicate
