### ISSUE TITLE
Belief_YieldFromTechUnlock no longer scales from Followers

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#7833]
_1. Mod version:_ 5/5

_2. Mod list (if using Vox Populi only, leave blank):_ Extra Beliefs mod

_3. Error description:_ The current implementation of Belief_YieldFromTechUnlock breaks its original intent, which was to be a yields on tech unlock that scales with the number of followers of your religion, as a counterpart to Holy Law's Belief_YieldFromPolicyUnlock.

The current implementation breaks any modmod that relied on the previous functionality, and it seems unsuitable and incongruent with the other designs for beliefs in VP. Once again, refer to Holy Law.

**Comment by LoneGazebo** [comment]
Yeah I took it away as it was implemented weirdly. I can take another look later.

**Comment by pineappledan** [comment]
I will close this as I see there is an older, related bug report
