### ISSUE TITLE
5/5 HF1 - Worker Facilities does not build factories if they exist in top cities

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7834]
_1. Mod version (i.e Date - 4/14):_
5/5 HF1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Worker's Facilities' description is a bit of a misnomer. It stays that you receive 5 free factories, which implies you get 5 new buildings. That is not true though if factories already exist in your big cities, they simply replace the buildings with free copies....which means you receive less hammers than if you had not built them in the first place.

Ideally if a factory already exist in a top city, the policy should just go to the next city and add a factory there. Only if there are no cities without factories should it "replace" a building.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Easier solution is to refund the purchase amount to the city as free production. Multiple loops like that run the risk of breaking the correct quantity or endless recursion.
