### ISSUE TITLE
Corporation HQs aren't NukeImmune

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#7836]
_1. Mod version:_ 5/5

_3. Error description:_ 
Corporation HQs function as world wonders, down to having splash screens, but they are not NukeImmune. 
World Wonders and National Wonders are both NukeImmune, but corporations are not. Is this an oversight, or is there some reason that you _SHOULD_ be able to nuke people's corporations that I'm not thinking about?

Supporting information:
https://github.com/LoneGazebo/Community-Patch-DLL/blob/master/Community%20Balance%20Patch/Modular%20Elements/Corporations/Corporations.xml

**Comment by RecursiveVision** [comment]
Can't think of any reason why this should be the case. Fixed.

Also added NukeImmune tags to the Tradition policy buildings, Ideology NWs, and the CSD National Wonders.
