### ISSUE TITLE
5/5 HF1 - AI Offers Peace Deal w/ Peace Treaties Only, but Refuses when I Press Accept

### ISSUE THREAD

**Issue by frootloopers** [LoneGazebo/Community-Patch-DLL#7837]
_1. Mod version (i.e Date - 4/14):_
5-5-2 w/ GUI fix

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch, Tomatekh's Great Spy, some custom mod mods (just editing values via XML).

_3. Error description:_ 
The AI will offer me a peace deal with just the peace treaties from both sides. Nothing else can be offered since the war score is near 0. However, when I try to accept, they will refuse the deal.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[google drive](https://drive.google.com/file/d/1HG92sOOgzdGKw_pJu41rWvUKP_XdZ_Q4/view?usp=sharing)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by CommieDog** [comment]
I've encountered this bug as well. Whether the AI proposes a peace treaty or I do, the AI always balks at it if there is no exchange of gold, goods, or cities.

This seems to be present (at least for me) when using the Community Patch by itself. Using both the Community Patch and the Community Balance Overhaul allows AI players to accept a peace treaty where the war has resulted in a stalemate.

**Comment by RecursiveVision** [comment]
Savegame needed to reproduce.

**Comment by CommieDog** [comment]
I can't speak for @frootloopers on this, but here's a save with the latest (5-5-2) Community Patch mod enabled and nothing else:
[CDQuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6470286/CDQuickSave.zip)

**Comment by RecursiveVision** [comment]
Fixed. Unintended consequence of a difficulty option I added.
