### ISSUE TITLE
communitas map script crashes

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#784]
i haven't used it in a while, is this a known issue?

the game crashes reproducably when trying to make a communitas map. Lua calls getX() on an invalid plot pointer (0xFFFFFFFF).

**Comment by LoneGazebo** [comment]
Not that I know of - I don't use the map much, but  I haven't seen any complaints either.

G

**Comment by LoneGazebo** [comment]
Gonna close, as no one else seems to have this issue.
