### ISSUE TITLE
5/5 HF1 - City not creating laborers when it runs out of space.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7841]
_1. Mod version (i.e Date - 4/14):_
5/5 HF1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Notice that this city looks "at capacity". But its actually got 1 extra person that's just in limbo, not a laborer, not anything. When I start making specialists see how my first one is free. Only by the second specialist do i start removing workers from the land (the fort straight north of the city in this case).

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/117735006-42578f00-b1ba-11eb-91f3-8f3cd471c4b7.png)

![image](https://user-images.githubusercontent.com/20593976/117735028-4c798d80-b1ba-11eb-97ce-c81178a66128.png)

![image](https://user-images.githubusercontent.com/20593976/117735042-526f6e80-b1ba-11eb-99e0-043f8b524bb9.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@ilteroi
