### ISSUE TITLE
5/5 HF1 (Possible Bug/Weird Interaction) - Barbarians from Barb quest still spawn even when quest is revoked

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7848]
_1. Mod version (i.e Date - 4/14):_
5/5 HF1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
so in this example, Jerusalem had the barb spawning quest. Then Jerusalem goes to war with me due to Mongolia's declare, so all quests are removed. But the barbs still spawn. Now that maybe intentional as other players can accomplish the quest, but now the user has no warning that barbs may suddenly occur. Its completely changed my current war with Mongolia, as my c bows may get utterly wrecked by these super barbs.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/118198748-1a189c00-b417-11eb-96aa-4a75d81557cf.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
The quest is not "revoked", it's a global quest that is not visible to you because you're at war.

Maybe there should be an indicator? @LoneGazebo

**Comment by LoneGazebo** [comment]
Probably should just be immune to being revoked.

**Comment by RecursiveVision** [comment]
@LoneGazebo What about receiving the quest in the first place?

**Comment by LoneGazebo** [comment]
yep
