### ISSUE TITLE
Deal renewal fires twice

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#785]
Posted by pandasnail on Civfanatics:

"Civs are offering to renew trades twice, the turn before the deal ends and the turn after. Even when I accept the first time, and even when its something like paying for open borders that can't happen twice functionally. If I accept both, both go through."

I've personally yet to encounter anything like that, but I also haven't been playing much lately. Don't know if it's worth looking into, but copying here just in case.

**Comment by LoneGazebo** [comment]
I think this was fixed by ilteroi in the latest version. Report back if not.
