### ISSUE TITLE
Multiple cities can work same tile

### ISSUE THREAD

**Issue by tojothethief** [LoneGazebo/Community-Patch-DLL#7851]
_1. Mod version (i.e Date - 4/14):_
5-5

_2. Mod list (if using Vox Populi only, leave blank):_
(1)
(2)
(3)
(4)
(5)
(6a) EUI
(7a)
(7b)
More Unique Components
Even More Resources for Vox Populi
Global - Faith Purchases in Puppets
Milae's Hotkeys WASD EUI
UI  - Improved City View (Gazebo's version)

_3. Error description:_ 
Paris and Lyon are both able to work the same Copper tile. It's not a visual bug, both cities are in fact benefiting from the yields.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[bugsave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6480697/bugsave.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20210514214558_1](https://user-images.githubusercontent.com/34595084/118315839-b23d8080-b4fe-11eb-8309-f44905a44820.jpg)
![20210514214557_1](https://user-images.githubusercontent.com/34595084/118315852-b6699e00-b4fe-11eb-933f-6e168e6dbd4c.jpg)

**Comment by LoneGazebo** [comment]
@ilteroi related to citycitizen work?

**Comment by mcymsb** [comment]
im having a same issue

**Comment by tojothethief** [comment]
Just as a further clarification, this problem seems to be universal and not only for the case of Paris and Lyon as shown in the pics. All cities can work same tiles, at least with my mod setup. Didn't tinker with it more than that.

**Comment by ilteroi** [comment]
this code is so f'd up

**Comment by LoneGazebo** [comment]
@ilteroi I added a check on city founding to make sure to clear any citizens working a title inherited by a city when founded. I think the issue is that if a citizen is working a tile that is taken by another city, it wasn’t pushing that citizen out so when the second city took it over it started at zero, and then lost resources  as a result. Does that make sense?

**Comment by ilteroi** [comment]
maybe, but i don't think it's related? 

the issue here is (i think) that the governor does not check for "overridden" plot ownership ... but it's hard to tell because the code for that is so bad.
