### ISSUE TITLE
getting weird deal offers

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7852]
![image](https://user-images.githubusercontent.com/1358966/118322168-fa5ca300-b4fe-11eb-827c-5f065e130ce5.png)

it seems they value strategic resources extremely high?

**Comment by RecursiveVision** [comment]
@LoneGazebo Why me? @ilteroi changed this valuation quite a lot, not me :)

**Comment by RecursiveVision** [comment]
@ilteroi actually on that topic can you push any changes you've made? I think G is planning a new release soon and you've marked several issues as fixed without pushing the changes as of yet.

**Comment by LoneGazebo** [comment]
Oops wrong tag

**Comment by ilteroi** [comment]
it seems they have a high "ResourceShortageValue". whatever that is about

**Comment by Stalker012345** [comment]
If this is medieval game or earlier, I certainly would value 2 horses a good bit higher over 1 iron.
