### ISSUE TITLE
AI doesn't need mutual Open Borders to dig artifacts

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#7854]
_1. Mod version (i.e Date - 4/14):_
4/16

_2. Mod list (if using Vox Populi only, leave blank):_
Logistics Skirmishers
Lategame War Rebalance

_3. Error description:_ 
Egypt is digging up my artifacts while not allowing me to enter their borders.
![image](https://user-images.githubusercontent.com/14953746/118354252-cfc12780-b59c-11eb-92f2-3388d4759e96.png)
![image](https://user-images.githubusercontent.com/14953746/118354369-57a73180-b59d-11eb-97a8-fe9387edbacc.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Oh well that’s good right? Intended behavior yay

**Comment by azum4roll** [comment]
Don't you need mutual open borders for this...?

**Comment by RecursiveVision** [comment]
The intention is one-way OB but G is having trouble finding the code section that prevents humans from doing it too.

**Comment by azum4roll** [comment]
So, can humans do it now? That's a big change missing from patch notes I'd say.
