### ISSUE TITLE
MOD_API_ESPIONAGE, MOD_API_EXTENSIONS, MOD_API_UNIFIED_YIELDS & etc.

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7857]
Is there any reason why someone would want to disable the extra API functionality added in the DLL, or can we delete the defines and #else'd out code?

**Comment by LoneGazebo** [comment]
That’s all from Whoward he was vigilant about refines

**Comment by LoneGazebo** [comment]
Defines* I’m fine with deleting them

**Comment by RecursiveVision** [comment]
Okay :)

Although I won't touch them until you've pushed your code, since it sounds like you have a substantial number of changes and I'd rather avoid merge errors!
