### ISSUE TITLE
DoUpdateWarStates is weird

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7863]
it seems the AI decides the "war state" depending on how many friendly/enemy cities are in danger. but they do not consider war score for that.

so it happens that they are in WAR_STATE_DEFENSIVE while being besieged (correctly) and then after losing a city they switch to WAR_STATE_OFFENSIVE, which seems weird? or maybe it makes sense because they should try and get their city back ... but simultaneously the "war projection" is WAR_PROJECTION_DESTRUCTION.

i don't have a solution, but note that UpdateOperations() currently looks at the war state when deciding what to do ...

**Comment by RecursiveVision** [comment]
@ilteroi I'll look at this, note that I deleted "war projection" as there was nothing it was doing that couldn't be done by GetPlayerMilitaryStrengthComparedToUs() or GetWarScore() or GetWarState()...

**Comment by RecursiveVision** [comment]
Found a solution, will fix for next release.

**Comment by RecursiveVision** [comment]
@ilteroi @LoneGazebo I rewrote peace logic and cleaned up the code, it's a lot less stupid now. Deleted two memory values, nine functions, and WarGoalTypes is no longer a thing.

Does need testing, however. Code is in the RSI branch.

**Comment by LoneGazebo** [comment]
neat!

**Comment by RecursiveVision** [comment]
Added logging and some more improvements...ready for beta testing :)
