### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Atavisti** [LoneGazebo/Community-Patch-DLL#7865]
_1. Mod version: v94

_2. Mod list:

Vox Populi including Enlightenment Era

_3. Error description:

Game crashes during city state AI and I see the following error in my Lua log repeated multiple times:

>[11866.140] Runtime Error: C:\Users\Tommie\Documents\My Games\Sid Meier's Civilization 5\MODS\(1) Community Patch\Core Files\Core Values\TechHelpInclude.lua:480: attempt to index field '?' (a nil value)

---------------------------
Supporting information:

1. Log files: 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6490656/Logs.zip)

2. Save game: https://easyupload.io/052056

3. CvMiniDump.dmp file: https://easyupload.io/supci8

4. Screenshots: I have no relevant screenshots except for a tangential issue regarding missing text on the screen (which I notice with respect to trade and research): 
![20210516182459_1](https://user-images.githubusercontent.com/84298688/118425182-3ffba600-b68e-11eb-97c2-414c58c34f40.jpg)

**Comment by LoneGazebo** [comment]
Likely a mod conflict?

**Comment by Atavisti** [comment]
Almost certainly. My fault for not noticing, lol.
