### ISSUE TITLE
Iroquois City Connections not working again

### ISSUE THREAD

**Issue by DeAnnoCiv** [LoneGazebo/Community-Patch-DLL#7867]
_1. Mod version (i.e Date - 4/14):_
5/5 Hotfix 1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Despite having a route between cities made of roads, forests, and jungles, a city connection is failing to establish. I have helpfully positioned a unit to light up all the tiles and make sure no barbarian is lurking, and on the screenshot I highlighted a possible path made up for roads in red and jungle/forest in blue.

_4. Steps to reproduce (optional):_
Load the save and observe.

---------------------------
<img width="839" alt="CityConnection" src="https://user-images.githubusercontent.com/47321731/118539198-20f82500-b71d-11eb-8d43-4bcf213c692e.png">

[Hiawatha_0055 BC-1800.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6496080/Hiawatha_0055.BC-1800.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6496084/Logs.zip)

**Comment by ilteroi** [comment]
cp only?

**Comment by DeAnnoCiv** [comment]
No I'm pretty sure this was the full mod. I'll doublecheck the save from inside Civ 5... Yeah it was with everything, look:

<img width="461" alt="Proof" src="https://user-images.githubusercontent.com/47321731/118860084-f509aa80-b8a8-11eb-9188-0f2d6db427b0.png">

**Comment by ilteroi** [comment]
well then you have to own the forest plots

**Comment by DeAnnoCiv** [comment]
Oh learn a new thing everyday I guess.
