### ISSUE TITLE
5/5 HF1 - Puppet governors sometimes starving out city

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7869]
_1. Mod version (i.e Date - 4/14):_
5/5 HF1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Hey so finally got 1 puppet to create. Unfortunately the governor decides that the people must starve!

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/118603894-2041ac00-b77a-11eb-8974-03a89f5af66e.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
hmm that is a significant food shortage. will check

**Comment by skodkim** [comment]
How can 13 citizens consume 66 food..? They must be really hungry :stuck_out_tongue_winking_eye:

**Comment by ilteroi** [comment]
the specialists need extra food ... it works out: 66 = 3x2 + 10x6

**Comment by ilteroi** [comment]
i suspect is has to do with the fact that the governor thinks a specialist consumes 4 food when in reality it consumes 6.

no idea why. aaargh.

**Comment by LoneGazebo** [comment]
I thought you fixed it?

**Comment by LoneGazebo** [comment]
The extra food cost- stemming from the era increase?
