### ISSUE TITLE
Crash after a few turns in Multiplayer game

### ISSUE THREAD

**Issue by tanisdlj** [LoneGazebo/Community-Patch-DLL#787]
Me and two friends just installed Community Patch Modpack (Multiplayer compatible) found in:
http://forums.civfanatics.com/showthread.php?t=553187
Started the game, I am the host. After a few turns, the game crashes to the desktop with a black screen and no error message.

Tried to continue the game (loading) ends with one of the players able to play but the other two (me, the host, and other friend) getting stuck - we cannot take any action, the game just ignores us.

We verified the cache of the game and steam downloaded different files.

Tried twice more and get both crashes too.
I am sure the issue is with the Community Patch. 
We played hundreds of hours Civ 5 on MP and never had this error.
We do not have enabled any other mods, nor DLCs (apart from the "official" ones).
We all have Windows 10 and are playing with dx11 mode.

https://dl.dropboxusercontent.com/u/16340249/Logs.7z <---- Here you can find the logs of the complete process. I deleted the previous logs, opened the game, hosted a new game, my friend joined me, we started a new game, played a few games and it crashed.

Also inside you have the minidump of the game. Any questions or test you want me to do, just let me know.

The mod looks great, but we can't play multiplayer at all with it :/
Thanks for your great job!

**Comment by LoneGazebo** [comment]
Once the modpack is updated by lynnes, give it another go. There were some problems with the latest two versions.
