### ISSUE TITLE
5/17 - AI accepting to pay for duplicate luxuries

### ISSUE THREAD

**Issue by DemaciaMaggotPie** [LoneGazebo/Community-Patch-DLL#7871]
_1. Mod version (i.e Date - 4/14):_
5/17 beta, no hotfixes (yet!)

_2. Mod list (if using Vox Populi only, leave blank):_
Improved City View, Milae's Hotkeys

_3. Error description:_ 
My buddy Bismark is regularly asking me to trade away my spare Olives for his gold. Problem is, he's already recieving a copy of my Olives, but he just can't get enough, and will throw money at me for more. 
Perhaps he's having a inner conflict and wishes he was playing Netherlands instead?

_4. Steps to reproduce (optional):_
Aquire at least 2 luxuries, meet an AI that is not Netherlands, check their desire to purchase a duplicate Luxury.

---------------------------
Supporting information:

4. Screenshots (optional):

![image](https://user-images.githubusercontent.com/7167416/118663322-042d2180-b7f1-11eb-95f1-ee05484648eb.png)

**Comment by LoneGazebo** [comment]
I didn't touch this...last person with their hands on resources was @ilteroi  👯

**Comment by ilteroi** [comment]
oh no

**Comment by LoneGazebo** [comment]
Oh yeah
