### ISSUE TITLE
5/17 + 3th & 4th: City population not decreasing upon finishing a settler 

### ISSUE THREAD

**Issue by Mar-viellac** [LoneGazebo/Community-Patch-DLL#7872]
_1. Mod version:_ 5-17

_2. Mod list:_ 3rd and 4th component v68

_3. Error description:_  City population doesn't decrease when finishing settler. The pop number do decrease but I can still work as many tiles/specialists as if I hadn't built a settler. In the screenshot I have build 2 settlers, pop count is 8, but I can still work 10 pops.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Pop bug report](https://user-images.githubusercontent.com/84395842/118669404-0180fb00-b7f6-11eb-8d5f-c401904cfcb1.jpg)

**Comment by LoneGazebo** [comment]
@ilteroi more fun for u

**Comment by Zarrk** [comment]
I have seen the same behavior: if all citizens are locked on tiles when the settler is spawned, none are removed, but if at least one is still left to be managed to the Governor AI he will be deleted as it should. It was early game so I didn't check if specialist slots are also preventing the removal of citizen.

**Comment by DeAnnoCiv** [comment]
I can confirm what Zarrk said, it has happened to me in a game just now as well, all the pop was locked and the settler reduced it from 4->3 but left all four tiles worked.

**Comment by ilteroi** [comment]
i should have become a watchmaker ...
