### ISSUE TITLE
Citizens can't select Natural Wonder to work (Governor issue?)

### ISSUE THREAD

**Issue by DeAnnoCiv** [LoneGazebo/Community-Patch-DLL#7873]
_1. Mod version (i.e Date - 4/14):_
5/17

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In the city tile screen, the natural wonder has no selector circle as if it was an empty desert. Additionally, the desert next to it can be selected and worked for 0 yields. Trying to enlist the governor to select the tile with Faith focus didn't help.

_4. Steps to reproduce (optional):_
Load the save and observe.

---------------------------
<img width="839" alt="NW" src="https://user-images.githubusercontent.com/47321731/118685321-fc5d8500-b7d0-11eb-9284-7170eede2fc2.png">

[Theodora_0031 BC-2760.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6502725/Theodora_0031.BC-2760.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6502729/Logs.zip)

**Comment by ilteroi** [comment]
hmm, probably because the plot is impassable. easy fix.

**Comment by ciqasty** [comment]
Hi, also encountered this problem - any chances to get the file that may fix this, to apply on top of current version so I can continue game without this bug or it is not so simple? :)

**Comment by ilteroi** [comment]
not so easy, i made some other improvements in the meantime which break savegames.

**Comment by skodkim** [comment]
Imho a fix would (always) be preferred anyway. Just state that it's not save game compatible. Sometimes we hold off starting games due to bugs.

\Skodkim

**Comment by ciqasty** [comment]
Thanks for reply. I will finish current game with this bug then and start new one when next version is ready :). Although maybe if I have enough time I will try and compile 5-17 myself with only fix for this bug applied.

**Comment by ciqasty** [comment]
I have managed to compile the dll file with fix for that issue only, with limited testing seems plots are now workable and game managed to proceed at least one turn - can share it on civ forum (saw someone asking for this) or here if you guys don't mind? @ilteroi @LoneGazebo

**Comment by RecursiveVision** [comment]
@ciqasty No one will mind :)

**Comment by ciqasty** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6511527/CvGameCore_Expansion2.zip)
Thanks, attaching the file then :D Note this is my first time I compiled this, so use at your own risk ;)
