### ISSUE TITLE
5/17 CTD (reproducible on turn 99)

### ISSUE THREAD

**Issue by HelpfulCarrot** [LoneGazebo/Community-Patch-DLL#7874]
_1. Mod version (i.e Date - 4/14):_5/17

_2. Mod list (if using Vox Populi only, leave blank):_I created a custom modpack using Multiplayer Mods Workaround (https://steamcommunity.com/sharedfiles/filedetails/?id=361391109) (as I have done literally dozens of times before without issue - I absolutely know how to do it correctly) with the following mods: 
Vox Populi (including EUI) version 5/17
InfoAddict (https://steamcommunity.com/sharedfiles/filedetails/?id=79000477)
Quick Turns (https://steamcommunity.com/sharedfiles/filedetails/?id=220250184)
Faster Non-Aircraft Animations (https://steamcommunity.com/sharedfiles/filedetails/?id=2482550592)

_3. Error description:_ 
The game worked perfectly until turn 99. Then, when I hit end turn (to progress to turn 100), it seems to work perfectly until it gets to the indicator that it's the barbarian turn, at which point it crashes to desktop. 

_4. Steps to reproduce (optional):_
I tried loading an autosave from the beginning of turn 99 (AutoSave_0098 AD-0740.Civ5Save). I play the turn, end the turn, and the problem happens again during the barbarian turn. The same thing happens if I load an autosave from the beginning of turn 98 or 97 - it always crashes during the barbarian turn after I end turn 99. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):[For bug report - log files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6503323/For.bug.report.-.log.files.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):[For bug report - save files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6503318/For.bug.report.-.save.files.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):[For bug report - crash dump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6503322/For.bug.report.-.crash.dump.zip)

4. Screenshots (optional): N/A
Also: 
Please let me know if you need me to upload the custom modpack I created - I'd be happy to do so, I think it's too large for GitHub or something so I'll only upload it if requested! 
Please note that none of the mods other than Vox Populi touch the DLL, and I've used modpacks I've made with this exact same modlist with previous versions of Vox Populi in past games that I've won, so I know they work with Vox Populi!

**Comment by LoneGazebo** [comment]
I'll need the modpack, can't load it otherwise and the minidump isn't helpful.

**Comment by HelpfulCarrot** [comment]
Here's the modpack: 
https://we.tl/t-YzwDPTQUUk

**Comment by LoneGazebo** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6512392/CvGameCore_Expansion2.zip)

**Comment by LoneGazebo** [comment]
This fixes the issue.
