### ISSUE TITLE
Reverted commit?

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7876]
@LoneGazebo You reverted one of @ilteroi's commits? Why?

Asking because I'm wondering how to proceed with my own changes and don't want to create merge errors :)

**Comment by LoneGazebo** [comment]
Savegame compatibility with a save i'm debugging.

**Comment by RecursiveVision** [comment]
Oh ok so it'll be re-reverted.

**Comment by ilteroi** [comment]
i hate to be a smartass but i really think there are some things that can be improved ... i'm not saying i'm perfect and the merging process has gotten better, but:

* branches are free! you don't have to do everything on the main branch. then rebase your fixes onto main later on.
* commit messages like "update CvPlayer.cpp" are pointless, git tells me the affected files
* multiple commits like "rewriting peace logic" are fine to have locally, but you can squash them into one before pushing the change
* commit messages like 5/15 are pointless, git tells me the date. use a proper semantic versioning scheme instead and tag the release. this way also people can finally stop asking whether it's savegame compatible

**Comment by RecursiveVision** [comment]
> i hate to be a smartass but i really think there are some things that can be improved ... i'm not saying i'm perfect and the merging process has gotten better, but:
> 
> * branches are free! you don't have to do everything on the main branch. then rebase your fixes onto main later on.
> * commit messages like "update CvPlayer.cpp" are pointless, git tells me the affected files

Yeah that's just me being lazy, I'll try to stop doing that :P

> * multiple commits like "rewriting peace logic" are fine to have locally, but you can squash them into one before pushing the change

That's on the experimental branch. I combine them into one before actual submission. Pull from my incomplete experimental work at your own risk. :)

> * commit messages like 5/15 are pointless, git tells me the date. use a proper semantic versioning scheme instead and tag the release. this way also people can finally stop asking whether it's savegame compatible

I think this would be a good idea, also helps avoid confusion because there are old versions - e.g. 5/12 this year or 5/12 last year?

**Comment by RecursiveVision** [comment]
Could just go

Version 1.0

Increment the second number by 1 each time a savegame compatible version or hotfix is released (1.1, 1.2, etc.)

Increment the first number by 1 each time a non-compatible fix is released.

**Comment by LoneGazebo** [comment]
No i'm pretty sure that every time we open and close a branch, god kills a kitten.

**Comment by LoneGazebo** [comment]
Technically we're on 6.x.x right now - we could go back to that serial method if we want.

**Comment by RecursiveVision** [comment]
I'm cool with that.
