### ISSUE TITLE
Minimum amount of time before making "peace"

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#788]
i'm in epic speed right now, i declared war on Pedro turn 19 and stole his worker. on my turn 22 he is ready to make peace- 3 turns. In a recent patch note it was mentioned the minimum time before AI considered peace had increased- is it based on era?

**Comment by LoneGazebo** [comment]
I worked on it, but there are a few more variables I haven't looked at yet. I'll keep an eye on it, though- it's definitely a priority.
