### ISSUE TITLE
Should the MOD_COMMUNITY_PATCH sub-macros be considered as always defined?

### ISSUE THREAD

**Issue by IanE9** [LoneGazebo/Community-Patch-DLL#7881]
This line marks the beginning of a series of macro definitions related to the community balance patch: https://github.com/LoneGazebo/Community-Patch-DLL/blob/4833a1acd4cdaaa05e0c3a8aab10b7b4d07327be/CvGameCoreDLL_Expansion2/CustomMods.h#L252

These macros are often conditionally ifdef'd out where they appear as if it is supposed be a optional compilation option, but in some places such as in CvPlayer.cpp's CvPlayer::canReceiveGoody() they are used as if they are expected to always be defined.

Are occurrences of these macros without conditional ifdefs errors? If not should the related ifdefs be removed?

**Comment by ilteroi** [comment]
it's historic ... i tend to delete those obsolete ifdefs if i stumble over them but no hurry

**Comment by RecursiveVision** [comment]
I'm working on it as well.

**Comment by LoneGazebo** [comment]
careful, you're digging up priceless historical artifacts

**Comment by RecursiveVision** [comment]
I promise I'll build a Landmark :D

**Comment by IanE9** [comment]
This is exactly what I wanted to know, thanks folks!
