### ISSUE TITLE
5/19 (Minor Issue) - GPTI cannot built on worker building a road

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7882]
_1. Mod version (i.e Date - 4/14):_
5/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
GPTI are set you can't plant them over workers that are building improvements, which in most cases makes complete sense. However, they also do it to roads as well, which is a bit awkward.

There is another issue. If you do plant the GPTI on a tile that almost has a road finished....the road is removed completely, and you have to rebuild it from scratch.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
only one improvement can be built at a time, too much hassle to change this

**Comment by RecursiveVision** [comment]
That's a shame, I was planning to ask at some point whether the "building a road cancels out all of my progress on the farm I half built" issue would get fixed.

**Comment by LoneGazebo** [comment]
@ilteroi is right, the build status is a singular value per tile, not an array. That'd be expensive.

**Comment by RecursiveVision** [comment]
@LoneGazebo An array would be expensive, but we could have one value for an improvement and a second value for a route without a fullblown array?

**Comment by azum4roll** [comment]
It's fine right now, provides some sort of dilemma whether you build the road or the improvement on the tile first.
