### ISSUE TITLE
warning: cached blockade plots are broken

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7887]
apparently there is a bug with 77dbe80c25af2d9a64f2f9370d0c2cea8a4cbaf7

@LoneGazebo : luckily it seems you reverted that change anyway ... i don't have time to fix it right now, so it's better to live with some late game slowdowns for now.

**Comment by RecursiveVision** [comment]
@ilteroi It was re-reverted

**Comment by ilteroi** [comment]
uh oh

**Comment by LoneGazebo** [comment]
I'm guessing tied to this: #7890

**Comment by LoneGazebo** [comment]
@ilteroi I'm betting the issue is that when a unit dies, there's no cleanup of plots it might have been blockading.

**Comment by ilteroi** [comment]
well that case *should* be covered

**Comment by LoneGazebo** [comment]
I fixed it.
