### ISSUE TITLE
Settler-swallowing Jungles

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#789]
With ExCE, where Jungle has been made impassable by your magic, it would seem that a Settler which can bypass this restriction will simply disppear into the void when trying to found a city - i.e. the animation plays, but then no city is founded. With a unit that can found a city abroad (like the Conquistador), it outright crashes. Everything is normal once Jungle is made passable by tech (i.e. Optics). Could you take a look and see what's up? Thanks.

**Comment by LoneGazebo** [comment]
Huh. I'll check. If you can send me the minidump, It'll be easier.

On the other hand, I mean, vicious, civilian-swallowing jungles are pretty badass. And jungles that can cause CTDs? That really encourages proper teching-up. :)

G

**Comment by JFDaly** [comment]
Here's the [mini dump](https://www.dropbox.com/s/007rcyut1f7hvqw/CvMiniDump.dmp?dl=0), from when a Conquistador trying to found a city abroad in Jungle triggered a CTD.

**Comment by LoneGazebo** [comment]
Forgot to say that the minidump went to lua - mind linking your current working copy of ExCE?

G

**Comment by JFDaly** [comment]
[Here you go](https://www.dropbox.com/s/j4qfwxgycs89nd0/JFD%27s%20Exploration%20Continued%20Expanded%20%28v%208%29.civ5mod?dl=0).

**Comment by LoneGazebo** [comment]
Alright, fixed. There are multiple 'found plot' tests and one of them slipped past me - the one that fires after the unit is expended. Fixes both issues.

G

**Comment by LoneGazebo** [comment]
Here's a debug version for you to test out.

https://mega.nz/#!mJU00JDA!EMJx_KBd5aFQPzWny3V6iHcklVY--ujiJ2nbOABI2WA

**Comment by JFDaly** [comment]
Link doesn't seem to work.

**Comment by LoneGazebo** [comment]
Bah, mega has been messing up again. Let's try this one: https://mega.nz/#!nR020RBI!l5hMtTijbIt2b1vAa3ea3YqdfrDNufzVNoOb5YegjjY

**Comment by JFDaly** [comment]
Issue is resolved. Thanks!

**Comment by LoneGazebo** [comment]
Hey, quick question (this is the easiest way to contact you). You are much more skilled with UI LUA than I - do you know how to make use of firaxis's frames in deal/trade screens? The latest version of the CP adds peace values to the trade screen, but they're in a blank black box. I'd love to add frames around it and/or color it properly, but I'm at a loss, as most frame elements seem to fixed in size.

If you can help, that'd be swell.

**Comment by JFDaly** [comment]
What files are you looking at? Most UI elements are hardcoded, but you can change them, either in Lua or in the files themselves. Is this for when you're brokering a peace deal? There's no quick way to get to that point, so do you have a screenshot of what you mean?

**Comment by LoneGazebo** [comment]
![civ5screen0008](https://cloud.githubusercontent.com/assets/7849458/11618081/4e312424-9c64-11e5-9316-b63bf58ce288.jpg)

The red area is where the new window element is going - I'm looking to add a gold frame around the top to make it look integrated.

**Comment by JFDaly** [comment]
Ah, gotcha. How's this:

![Alt Text](http://i.imgur.com/zcLE4tm.jpg)

Alternatively, this:

![Alt Text](http://i.imgur.com/FkST78W.jpg)

Let me know which you prefer (or if you want me to tweak something - I'll set the transparency back to 155, unless you want to keep it as shown), and I'll pass on the file.

**Comment by JFDaly** [comment]
So, is any of that good for you? I'm happy to make adjustments.

**Comment by LoneGazebo** [comment]
Sorry, for some reason I didn't get an alert for this! I like the last one the best as well – it's clean, and doesn't get lost quite so easily in the rest of the features. Fantastic work!

**Comment by JFDaly** [comment]
Right, [here you go](https://www.dropbox.com/s/uohe10lx4l3zptq/DiploTrade.xml?dl=0)
