### ISSUE TITLE
5/19 - Marble Plot unable to be worked by a worker.

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7890]
_1. Mod version (i.e Date - 4/14):_
5/19

_2. Mod list (if using Vox Populi only, leave blank):_
(placed below)

_3. Error description:_ 
Got a juicy one for you. So the marble plot next to my capital has no worker spot, I cannot work the tile in any way. Including Saved Game, mods, and logs.
[Info Packet.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6518942/Info.Packet.zip)

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/119053577-de884f80-b98b-11eb-8e91-3acb8089cc25.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by DeAnnoCiv** [comment]
I have a similar issue with a Truffle plot. I think it may have started when it was pillaged in a war but I can't be sure. 5/19 no other mods. It may also have happened when it was occupied by an enemy troop who I then killed, a knight died on that spot (after pillaging it) before I noticed the issue.

<img width="839" alt="SadTruffle" src="https://user-images.githubusercontent.com/47321731/119068920-18b91780-b9b3-11eb-8cae-d4d98fe62245.png">

[Nebuchadnezzar II_0139 AD-0580.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6519488/Nebuchadnezzar.II_0139.AD-0580.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6519486/Logs.zip)

**Comment by LoneGazebo** [comment]
Alright, I fixed it. Here's a DLL to test and see if it works for you...

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6523127/CvGameCore_Expansion2.zip)
