### ISSUE TITLE
All civs have as many delegates as delegate leader

### ISSUE THREAD

**Issue by tojothethief** [LoneGazebo/Community-Patch-DLL#7892]
_1. Mod version (i.e Date - 4/14):_
5-19

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP + EUI
Community Events
More Unique Components
Even More Resources
Historical Religions Complete
Milae's Hotkeys
Really Advanced Setup
UI - Improved City View
UI - Religion Spread (Vox Populi)

_3. Error description:_ 
All civs have the same amount of delegates, as many as the civ with the most.

![20210521130040_1](https://user-images.githubusercontent.com/34595084/119120480-fec01900-ba34-11eb-8cac-6bc8ae5d863f.jpg)
![20210521130048_1](https://user-images.githubusercontent.com/34595084/119120492-01bb0980-ba35-11eb-8f5e-4d40e5fc515d.jpg)

**Comment by LoneGazebo** [comment]
@Mileslewis ?

**Comment by RecursiveVision** [comment]
@LoneGazebo Culprit is likely @ilteroi's changes to create a cached number of votes.

**Comment by LoneGazebo** [comment]
ah

**Comment by Mileslewis** [comment]
I think this should be fixed from #7885 there was a random comma in the middle of a line I think it was just messing up the whole file

**Comment by ilteroi** [comment]
so i'm innocent for a change? yay

**Comment by LoneGazebo** [comment]
Comma would not allow compile though

**Comment by Mileslewis** [comment]
iTradeDealValue += 400,GC.getGame().GetGameTrade()->CountNumPlayerConnectionsToPlayer(GetPlayer()->GetID(), eTargetPlayer, true) * 100;

This was the line. I honestly don't know how it was running but when I fixed this the delegates were okay for me.

**Comment by mcymsb** [comment]
> iTradeDealValue += 400,GC.getGame().GetGameTrade()->CountNumPlayerConnectionsToPlayer(GetPlayer()->GetID(), eTargetPlayer, true) * 100;
> 
> This was the line. I honestly don't know how it was running but when I fixed this the delegates were okay for me.

how do i fix that on my end? since moderators seem busy with the update, i wanna fix it myself but CvGameCoreDLL_Expansion2 dll i dont know how to update the lines please tell me how

**Comment by RecursiveVision** [comment]
@mcymsb You would need to build the DLL, which requires special tools. Info and a tutorial is posted on the main repository page: https://github.com/LoneGazebo/Community-Patch-DLL#how-can-i-build-this

**Comment by LoneGazebo** [comment]
I don't think this fixes it... m_startingVotesCached is an 'int' for the CvLeague:: level, but the function it is used in calls on PlayerTypes ePlayer, so you're getting the same int for every player.

**Comment by LoneGazebo** [comment]
I think the int would need to be an array for all players for this to work.

**Comment by LoneGazebo** [comment]
easier fix: move the two int to the Member struct. Solved.
