### ISSUE TITLE
Futurism, Mastery and MoreLuxuries.sql (v11-19)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#790]
1.
How did recent tourism changes affect Futurism?
20% of one's Culture earned over the past 10 turns?

2.
The text of Mastery needs to be updated.
Specialists produce **+1** of their primary yield
   ->
Specialists produce **+3** of their primary yield

Community Balance Patch\Balance Changes\Beliefs\FollowerText.sql (Line: 81)

3.
I think the MoreLuxuries.sql in the **No-EUI** needs to be updated.

Community Balance Patch - Compatibility Files (No-EUI)\MoreLuxuries\MoreLuxuries.sql
cf.
Community Balance Patch - Compatibility Files (EUI)\MoreLuxuries\MoreLuxuries.sql

**Comment by LoneGazebo** [comment]
It becomes 14%, yes, IIRC. Numbers may need adjusting, we'll see.

I'll fix those other two things in the hotfix.

**Comment by LoneGazebo** [comment]
Fixed in 11-20 hotfix. We'll keep an eye on futurism.
