### ISSUE TITLE
5/19 HF1 - City cannot produce units

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7900]
_1. Mod version (i.e Date - 4/14):_
5/19 HF1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
This city can produce buildings just fine, but look what happens when I try to make a unit. Attached full packet with saved game, logs, and mods. I believe I'm at max war weariness, maybe something off with the new calculation therE?

_4. Steps to reproduce (optional):_
[Info Pack.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6527105/Info.Pack.zip)

![image](https://user-images.githubusercontent.com/20593976/119240406-ec1d1100-bb14-11eb-8c42-804f9eb6a077.png)

![image](https://user-images.githubusercontent.com/20593976/119240411-f17a5b80-bb14-11eb-9a94-e0d7e65cd95d.png)

![image](https://user-images.githubusercontent.com/20593976/119240424-0e169380-bb15-11eb-9025-fa747ac4f1c1.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
UPDATE: confirmed its not just about global unhappiness. Increased by global happiness backed to 50%, and no change.

**Comment by Stalker012345** [comment]
Update: I do believe this some kind of war weariness interaction. Once I made peace with the Incan, my unit production was back in action.

**Comment by LoneGazebo** [comment]
missing an upper limit/
