### ISSUE TITLE
Exceptionally long multiplayer turns, about 100ish turns in

### ISSUE THREAD

**Issue by Asher3195** [LoneGazebo/Community-Patch-DLL#7909]
_1. Mod version (i.e Date - 4/14):_
December 1st (5.12.1)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Extremely long turn times in MP, certain AI hang but mainly the barbarians and city states (Crom). About 3 mins or 4 waiting time. This only starts around turn 110ish

_4. Steps to reproduce (optional):_
Play a MP vox populi game with 1 other human player on a large shuffle map.

[Nebuchadnezzar II_0127 AD-0300.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6534409/Nebuchadnezzar.II_0127.AD-0300.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6534412/Logs.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
I don't think anyone is going to be fixing issues from December when the latest beta was on May 17...

**Comment by ilteroi** [comment]
but there's a good chance it's better now anyway
