### ISSUE TITLE
CTD with 11/19 version

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#791]
Very early CTDs that were fixed in the 11/17 version came back again, this time even earlier (managed to crash on turn 2). Two minidumps attached. Tell me if you need anything else.

https://www.dropbox.com/s/w8mz8g4238o1rx2/CvMiniDump1.dmp?dl=0
https://www.dropbox.com/s/l1i1fsn8etx3t3x/CvMiniDump2.dmp?dl=0

**Comment by LoneGazebo** [comment]
Fixed (Was time victory issue).
