### ISSUE TITLE
5/19 - Production Spy Mission "Halve Duration on World Wonder" is not working

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7910]
_1. Mod version (i.e Date - 4/14):_
5/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
My spy was supposed to take 6 turns to complete a production sabotage mission, and then half that with a world wonder. 4 turns in, my spy is still going, and the wonder is still building. All mods, save game, and logs included.
[Info Packet.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6534784/Info.Packet.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
did the wonder start building after the production sabotage was started? Or before?

**Comment by Stalker012345** [comment]
> did the wonder start building after the production sabotage was started? Or before?

The wonder started before, and looked to be active the entire time.
