### ISSUE TITLE
5/19 - Science Mission Notification Science Amounts does not match right side notification

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7913]
_1. Mod version (i.e Date - 4/14):_
5/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When I completed the science spy mission, I got up saying I had recieved 300 science. But the right side notification says I get 2100. The 2100 value was what the missions said it was worth, so it appears to be the mission popup in error.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/119435900-bb89d280-bce0-11eb-8f01-95357da43fa9.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Sounds like it is just missing a modifier.

**Comment by LoneGazebo** [comment]
Can you get me a shot of the popup?

**Comment by Stalker012345** [comment]
![image](https://user-images.githubusercontent.com/20593976/119449568-6ce83280-bcf8-11eb-90bb-b1e46f0eb8fe.png)

**Comment by LoneGazebo** [comment]
gotcha, I think I got it sorted.

Also, fun fact: that popup occurring is 100% an accident, I'm glad you like it. :)

G
