### ISSUE TITLE
5/24 - Apostolic Tradition Giving More Than 500 Faith Per Tech?

### ISSUE THREAD

**Issue by raymond-sutandar** [LoneGazebo/Community-Patch-DLL#7914]
_1. Mod version (i.e Date - 4/14):_
5/24 (2021)

_2. Mod list (if using Vox Populi only, leave blank):_
(1) Community Patch
(2) Community Balance Overhaul
(3) CSD for CBP
(4) Civ IV Diplomatic Features
(5) More Luxuries
(6a) Community Balance Overhaul - Compatibility Files (EUI)
(7a) Promotion Icons for VP
(7b) UI - Promotion Tree for VP
(9a) Enhanced Air Warfare 4VP (v 1.9)
(over) More Unique Components for VP ----> v68
(overhaul) More Wonders for VP            -----> v0.11
(ui) Trade Opportunities for VP
CIV-Linked Great Generals (v 11)
Contextual Unit Names (v 3)
Diplomacy Responses Extended (v1)
Enlightenment Era (Vox Populi) (v 3)
Even More Resources for Vox Populi (v 8)
Hex Conquer (Borders Only)
Historical Religions Complete (BNW or GK) (v 45)
Infixo's Enhanced Naval Warfare for Vox Populi (v 2.1)
JFDLC (07) - JFD's Cultural Diversity (Core) (v 17)
JFDLC (07a) - JFD's Cultural Diversity (Soundtrack)
Map Labels (v 6)
More Great Musicians
More Great Works (v 3)
Music Changer (v 2)
pdansTweaks
PerfectWorld 3 (v 4)
Quick Turns (v 10)
Really Advanced Setup (v 15)

_3. Error description:_ 
Apostolic tradition is giving me 608 faith from researching a tech. However, the belief's description says "When you unlock a new technology, receive 2 faith for every Follower of your Religion (max 250 followers)", which implies the faith gain I should earn maxes at 500.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[AutoSave_0400 AD-0500.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6536461/AutoSave_0400.AD-0500.zip)

(I named my save here; this is turn 401, where I received too much faith from Apostolic Tradition (see screenshot)):
[Drylands of the Lord (VP240521).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6536463/Drylands.of.the.Lord.VP240521.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20210525001239_1](https://user-images.githubusercontent.com/46147898/119439114-b2ecc880-bcef-11eb-96eb-b2d8864564f8.jpg)

**Comment by RecursiveVision** [comment]
Era scaling?

**Comment by raymond-sutandar** [comment]
Ah I wasn't aware that era scaling applied to Apostolic Tradition; I didn't see it in the description, so I thought it was removed.
