### ISSUE TITLE
Achievement/Tutorial Code

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#7917]
Do we need to keep any of this in the DLL? It seems useless, and a comment in CustomMods.h says that achievements don't work in modded games (although that might be a Firaxis comment, not sure).

There's two separate defines for achievements (MOD_API_ACHIEVEMENTS and ACHIEVEMENT_HACKS), too...

**Comment by LoneGazebo** [comment]
CustomMods.h was written by Whoward back in the day so that’s all modded content

**Comment by RecursiveVision** [comment]
@LoneGazebo So is there any use in having this code around or can it be deleted? I don't imagine many people are playing VP to get achievements, if that's even possible to do.

**Comment by azum4roll** [comment]
I'm gaining achievements through modpack...

**Comment by LoneGazebo** [comment]
@RecursiveVision the benefit of removing that code is minimal.

**Comment by RecursiveVision** [comment]
Mmmmmmm, I'll leave it alone for now I guess
