### ISSUE TITLE
5/24 - 4 way DP before Ideologies

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7920]
_1. Mod version (i.e Date - 4/14):_
5/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
AI has formed a 4 way DP with 9 players in the game (8 AI, 1 human). I believe this is not supposed to be possible until ideology.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/119585218-da936d80-bd8f-11eb-92ff-354883e9120f.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@Stalker012345 Without a savegame one turn before the AI actually agrees to make a DP over the limit, I can't fix.

**Comment by LoneGazebo** [comment]
@RecursiveVision there are logs which show some thinking on this.

**Comment by RecursiveVision** [comment]
@LoneGazebo Unlikely; I rewrote all of the DoF/DP logic.

But you make a good point, I should add logging.
