### ISSUE TITLE
Units cannot receive plague debuff twice (boarded, concussive shots etc.)

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7924]
_1. Mod version: 5-24

Once the duration of a plague is over, the debuff goes away, but it seems like the unit is still flagged with that plague which means it cannot get plagued again.
![plague bug](https://user-images.githubusercontent.com/55395192/119690087-4b469280-be41-11eb-8d63-2d10f38e49e5.jpg)

In the photo the barbarian caravel is no longer boarded since the duration ran out, but on the combat menu it says it is still boarded. It would not become boarded again if I attacked. Same thing happens with concussive shots and other plagues in other Mods.

It actually does properly reset the original plague if a unit gets hit with a different plague after.

**Comment by RecursiveVision** [comment]
Well that would explain the inconsistent bugs...

**Comment by LoneGazebo** [comment]
aha, yep, that's the bug. wohoo.

**Comment by skodkim** [comment]
Good Find. That's a bug fix I'm looking forward to 😄
