### ISSUE TITLE
Happiness from Natural Wonders

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#793]
I discovered two NWs: Fountain of Youth and Barringer Crater. I then claimed FOY to be inside my borders. Since the tooltip says it's supposed to give 1 happiness when inside your borders, I should be looking at +3 happiness (2 from discovering BC and FOY and 1 for having FOY in my borders). However, the happiness tooltip said "5 from discovery of Natural Wonders". Is FOY supposed to give 3 happiness when inside your borders?

**Comment by LoneGazebo** [comment]
Not sure exactly. I'll take a look.

**Comment by Edaka** [comment]
I'll let you know if it happens again.
