### ISSUE TITLE
Weird UI glitches in 5/24 no EUI

### ISSUE THREAD

**Issue by Nigel--C** [LoneGazebo/Community-Patch-DLL#7931]
_1. Mod version (i.e Date - 4/14):_
5/24 no EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Location of other cities appear on the map in the FOW before they have discovered (from turn 1)
When selecting production for a city, it does not show what it is producing in its map icon until the turn after.

_4. Steps to reproduce (optional):_
This has happened in both 5/24 games I have started on different computers, using Communitu_79a v2.3.0.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

[logfiles.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6550122/logfiles.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[savefile.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6550127/savefile.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5 screenshot](https://user-images.githubusercontent.com/8080565/119743666-b9d13200-becd-11eb-8527-e4a608df9855.png)

**Comment by sSs1897** [comment]
Same issue with all cities displaying america icon
