### ISSUE TITLE
Happiness modification issue in cities when producing military units

### ISSUE THREAD

**Issue by mcymsb** [LoneGazebo/Community-Patch-DLL#7933]
_1. Mod version (i.e Date - 4/14):_

5/24

_2. Mod list (if using Vox Populi only, leave blank):_
VP 

_3. Error description:_ 

as you can see the city and the global happiness are both above 50% yet when producing military units, i get - 55% ( prolly more later? )  buildings and non-military units dont get affected though
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/62123081/119747647-62d94780-be50-11eb-83af-bc3dd414f19b.png">

**Comment by LoneGazebo** [comment]
It’s just a text typo, should be War Weariness

**Comment by mcymsb** [comment]
> It’s just a text typo, should be War Weariness

I see.
6 war weariness and already 55 % down. That's scary. Anyways I can't end a war that is lasting for almost more than 50 turns. Any change in war mechanism?

**Comment by RecursiveVision** [comment]
@mcymsb I rewrote peace logic. Savega
me would be useful.
