### ISSUE TITLE
5/24 - Iroquois City Connections require friendly territory in CBP

### ISSUE THREAD

**Issue by Hokiefan00** [LoneGazebo/Community-Patch-DLL#7935]
_1. Mod version (i.e Date - 4/14):_ 5/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ The bug reported in [this issue](https://github.com/LoneGazebo/Community-Patch-DLL/issues/7722) is still present. Iroquois cities will not be connected via forest/jungle unless all forests/jungles are in friendly territory when using CBP.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by grmagne** [comment]
I submitted a similar request about a month ago and, although that Issue was closed, the Iroquois City Connections still do not work.

**Comment by LoneGazebo** [comment]
@ilteroi take a look?

**Comment by RecursiveVision** [comment]
> 
> 
> @ilteroi
> 
> Community Patch:
> 
>     * Units move through Forest and Jungle in friendly territory as if they were Roads.
> 
>     * Forest and Jungle in friendly territory act as Roads for the purposes of City Connections and Trade Routes
> 
> 
> Community Balance Patch:
> 
>     * Units ignore terrain costs in ALL Forest and Jungle
> 
>     * All Forest and Jungle act as Roads for the purposes of City Connections and Trade Routes

**Comment by ilteroi** [comment]
oh, i thought it was the other way around
