### ISSUE TITLE
5/24 - Still seeing extreme War Weariness causing inability to produce troops bug

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7938]
_1. Mod version (i.e Date - 4/14):_
5/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Similar to what I reported on 5/19. There is still an issue where war weariness is cutting unit production down to the point where I can no longer produce troops. The weariness toolbar says I'm at 39%, so either the toolbar is wrong and WW can go much higher than I thought, or WW is applying too much,

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/119918621-680cc400-bf2e-11eb-84d7-3e9df44b08a6.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by mcymsb** [comment]
I agree. War weariness rises too quickly I'm having difficulties producing units too

**Comment by LoneGazebo** [comment]
I’d need a save

**Comment by Mileslewis** [comment]
The war weariness production penalty seems to be war weariness * 10 which is pretty extreme. I'm guessing the *10 is the problem.

**Comment by LoneGazebo** [comment]
There’s a min value so it caps at 75% penalty.

**Comment by Mileslewis** [comment]
yea but it gets there too fast, 7.5% war weariness = 75% production penalty?

**Comment by Mileslewis** [comment]
![war weariness](https://user-images.githubusercontent.com/55395192/120024506-39065900-bfe7-11eb-93a2-45bd502f4788.jpg)

Also you can see in this pic that it says the cost increase should be 16% so 2 * 8% instead of *10.

**Comment by Mileslewis** [comment]
Okay so it seems like it's the penalty is actually war weariness * 5. I think if you want to make it very punishing then war weariness * 2 could work but * 5 just feels like way too much.
