### ISSUE TITLE
(Question) - Is it possible to turn off log recreate after program restart or game reload?

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7939]
Modder Question:

One difficulty I am having in using the logs for data collection is that every time I reload the program or reload a game, the logs instantly flush and reset. I can try preserving the logs but that just leads to some other messes and I forget to do it.

Is that any setting that prevents the logs from flushing so it will just add new data to the existing logs after a reload?

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Only if you don't close and reopen the game.

**Comment by Stalker012345** [comment]
> Only if you don't close and reopen the game.

So it wouldn't refresh if I reload the game, but it still would if the program closes and reopens (with whatever changes you can offer me? I can work with that, its not quite as good but its a big help. I can just keep the program open and its somewhat ease to remember to save the log if I get soft CTDs.

**Comment by LoneGazebo** [comment]
correct.

**Comment by inkyant** [comment]
You can also use firetuner, as the logs will still be displayed as long as you don't close it. 

You need to download the SDK on steam for free and set the "EnableTuner" option to 1 in your config.ini file which is located at the root of the Civ5 documents folder.
