### ISSUE TITLE
Mysterious demands from player

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#794]
In my game with the 11/20 hotfix I'm seeing negative diplomatic modifiers with some AIs for demands I never made. It's sort of a reverse of the previously seen situation where AIs accused the player of not keeping promises without contacting him with any demands (as if they were made automatically with no notifications). This time apparently it was me who silently demanded some AIs not to spy on me and not to settle nearby.

Here's how it was in a little more detail: at some point there were 2 AIs with both of whom I'd had DOFs. Suddenly (there didn't seem to be any obvious trigger) they broke DOFs with me one after another - that's when I saw that apparently I'd made the two demands in the diplomatic relations tooltip (when hovering over "friendly" and the like). There was anotherAI that didn't have a DOF with me and I had no diplomatic penalties for false demands with him for a long time, so I assume it happens only with friends. I didn't keep a save, but I definitely will next time it happens.

**Comment by LoneGazebo** [comment]
Only with DOF? Do you have a save from right before when it happens? That code wasn't messed with at all by me, not that I know of. Using any special mods?

**Comment by Edaka** [comment]
Yep, only with DOF. I've dug out two saves for you - both the turn before an AI ends DOF and the diplomatic penalties become visible. I don't know if my "demands" fire before that, but the two saves are like 3-4 turns apart from each other anyway.

Here's a save around turn 135: https://www.dropbox.com/s/taheako42pzdkbm/demands1.Civ5Save?dl=0
Here's another at around turn 140: https://www.dropbox.com/s/rbq2bvl8nn6fqkm/demands%202.Civ5Save?dl=0

Mods I'm using (sorry there's a long list, but most should be cosmetic):
CPP full install with EUI and More Luxuries;
Some Whoward's Pick'n'Mixes: 
http://www.picknmixmods.com/mods/a3944698-d02f-4af2-b0e5-0e4d968c106c/mod.html
http://www.picknmixmods.com/mods/2d00d048-8df2-4ced-8a38-ae4e8d55baa2/mod.html
http://www.picknmixmods.com/mods/e4cc6d22-502f-4c55-bc44-a3da5b4d7021/mod.html
http://www.picknmixmods.com/mods/7d12def5-835d-4de6-a69b-dc8f8504f07b/mod.html
Mod for great prophet names: http://steamcommunity.com/sharedfiles/filedetails/?id=79544687
Mod for additional religion icons and names: http://steamcommunity.com/sharedfiles/filedetails/?id=177650706
Mod for Hunnic city names: https://steamcommunity.com/sharedfiles/filedetails/?id=138222160
Randomize city names: https://steamcommunity.com/sharedfiles/filedetails/?id=98460355
More great works (not my mod, but I've made some edits so that great people are tied to accurate eras): https://www.dropbox.com/s/8fq7sdf0a0ridaj/More%20Great%20Works%20%28v%203%29%20EDIT.zip?dl=0
Krajzen's great people: https://steamcommunity.com/sharedfiles/filedetails/?id=231009607
Promotion flags (I'm using an outdated version, but it's been taken down - hopefully, that isn't a problem as it's purely cosmetic anyway): http://forums.civfanatics.com/showthread.php?t=547864
Info Addict: https://steamcommunity.com/sharedfiles/filedetails/?l=russian&id=79000477
Mod that lets you uncover tiles with air recon ability: https://steamcommunity.com/sharedfiles/filedetails/?id=288579237
A UI mod that highlights the destination of a unit: http://forums.civfanatics.com/downloads.php?do=file&id=23988
Remove XCOM: http://steamcommunity.com/sharedfiles/filedetails/?id=244582957&searchtext=remove+xcom
Quick turns: http://steamcommunity.com/sharedfiles/filedetails/?l=russian&id=220250184

I'm really sorry I have to put you through this. However, as you can see, the vast majority of these mods are just cosmetic changes, so you might probably replicate the problem without having to enable all of them. None of them is supposed to tinker with diplomacy AI, demand mechanic or anything like that.

**Comment by LoneGazebo** [comment]
I'll try to replicate things without the mods (if you get the bug to try and so the same, that'd be great).

**Comment by Edaka** [comment]
I think I'll try to cheat a little with IGE and just the CPP pack to speed things up (artificially creating DOFs and such). I don't suppose IGE will have any impact on that.

**Comment by LoneGazebo** [comment]
Cool. It shouldn't.

**Comment by LoneGazebo** [comment]
Have I mentioned that I hate the way firaxis wrote the DiplomacyAI?

**Comment by Edaka** [comment]
Yeah, I think we can all "appreciate" the way Firaxis has done some things with Civ.

Probably worthy to note: I've declared war on a major (3-rd party) civ at least once as well as declared and captured a city state, which should've generated a handful of warmonger points. It all definitely factored into those AIs breaking DOFs with me. Not sure if the bug can cause breaking of DOF by itself.

Oh, I just remembered transparent diplomacy exists. That'll definitely be useful.

**Comment by LoneGazebo** [comment]
Yeah - even if those things are triggering the DOF breaking, those additional modifiers shouldn't be appearing.

**Comment by Edaka** [comment]
It seems that the issue is specifically connected to capturing city states. I signed DOFs with two leaders nearby, then capped a city state nearby - both neighbours followed to break DOFs and at the same time the diplomatic modifiers for demands appeared. I've attached a save so you can reproduce if needed -  capture the city state (you'll know which one (: ) and Boudicca will demonstrate the effect. For some odd reason, Ramesess doesn't do it right away, so I had to capture another CS to trigger that response from him. The diplomatic modifiers for demands only appear with those civs you have DOF with.
https://www.dropbox.com/s/1ph475dzpf23hl9/demands.Civ5Save?dl=0

**Comment by LoneGazebo** [comment]
Okay, I've rewritten some things, maybe this will fix it.
G
