### ISSUE TITLE
5/24 - Archeologist cannot dig for CS artifact

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7940]
_1. Mod version (i.e Date - 4/14):_
5/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
As far as I can tell, there should be absolutely no reason I can't dig here, but its not allowing me. This is the first dig I have attempted outside my borders (within borders has been fine), so I'll try and see if this is happening all the time or just this one instance.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/119928186-b32fd280-bf40-11eb-8ad3-6091f37241d2.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
Update: Digs in no borders are confirmed working.

**Comment by Stalker012345** [comment]
Update: A dig at another CS site is also not working.

**Comment by LoneGazebo** [comment]
I didn’t touch digging logic.

**Comment by LoneGazebo** [comment]
Again, save needed

**Comment by Stalker012345** [comment]
[Sid Meier's Civilization 5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6561874/Sid.Meier.s.Civilization.5.zip)

A saved game + mods used. I don't have an archeologist super handy in this save unfortunately.

**Comment by Stalker012345** [comment]
Here's a better saved game with an archeologist right on the CS site. Use the mods I provided previously.
[Maria I_0355 AD-1935.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6588750/Maria.I_0355.AD-1935.zip)

**Comment by LoneGazebo** [comment]
Hmm, saves won't load for me. Bummer. I'll watch this in next release.
