### ISSUE TITLE
diplomacy and economy

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7942]
so enrico is rich ... has +100 gpt in classical. this is his very generous offer to me:

![image](https://user-images.githubusercontent.com/1358966/119985981-9ee0e980-bfc3-11eb-8c73-b5752b126083.png)

some time later, he asks me for a gift, a flat 1000 gold, although by this time he's in a war, and has only +12 gpt.

did anyone change the logic here lately? never seen such sums before, and they seem a bit on the high end for the classical era. should they be aligned with era or average gpt or so?

**Comment by RecursiveVision** [comment]
I haven't touched Putmalk's code for this as of yet.

**Comment by azum4roll** [comment]
My two DoFs both gave me exactly 17GPT as a gift too.
