### ISSUE TITLE
Exceptionally poor performance in multiplayer on high core count systems

### ISSUE THREAD

**Issue by IanE9** [LoneGazebo/Community-Patch-DLL#7945]
_1. Mod version (i.e Date - 4/14):_
N/A (engine bug)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Very poor performance in multiplayer on systems with greater than 8 cores.

_4. Steps to reproduce (optional):_
Start a multiplayer lobby on a system with a lot of cores and watch FPS tank.

---------------------------
Supporting information:
Encountered this while testing multiplayer and confirmed it occurs without any mods installed. The only reason I opened an issue is because I found that manually reassigning the process's affinity mask to only use the lower 8 cores appears to eliminate the problem. Maybe this should be done automatically when the DLL loads.

**Comment by RecursiveVision** [comment]
@IanE9 Civ 5 is 32-bit so it can only use one core. Not fixable, unless Firaxis decides to release a 64-bit version for PC.

**Comment by IanE9** [comment]
32-bit processes are capable of using more than 1 core. In fact it appears the only reason this issue occurs is because it's using more than 8. The primary restrictions on 32-bit processes are memory, registers, and instruction availability.

**Comment by RecursiveVision** [comment]
Huh. Still nothing we can do about it, though. The engine code is outside of the GameCoreDLL.
