### ISSUE TITLE
5/24 hotfix city razing bug

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#7948]
![civrazebug](https://user-images.githubusercontent.com/53142313/120080278-6111bd00-c0b8-11eb-8431-20151e23ac3d.png)

There used to be a polish city on that lone patch of terrain that now belongs to me...

**Comment by ilteroi** [comment]
i just rewrote that code ... but it's not yet included in the latest build. so it should be fixed already, but you never know :)

so exciting!
