### ISSUE TITLE
Can't do any Event action with Spy

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#7949]
_1. Mod version 5-28
![spy bug](https://user-images.githubusercontent.com/55395192/120092413-74e60f00-c10a-11eb-8c21-7385792e292b.jpg)

Am not allowed to do any of the spy events. Also not able to end the turn since I can't make the choice.

Spy is level 1 doing it's first ever mission.

**Comment by bentakacs** [comment]
Same thing happens for me on previous version. I get a new spy by entering Renaissance era, then choose the capital of a hostile civ and I get the same window, the Spy can't do anything. 

If I move it to another city however, the options are appearing and seem to be correct. Dunno if it's related, but thought might as well share it.

**Comment by LoneGazebo** [comment]
Hmm. I’d need a save
