### ISSUE TITLE
Battle outcome calculation display

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#795]
It isn't shown whenever you hover over an enemy unit that's not on a neutral territory. E.g. enemy units on an enemy territiry, enemy units on my territory. It works fine when you hover over units on a neutral territory.

Here you can see me hovering over a comp. bowman outside the Aztec borders:
![calc](https://cloud.githubusercontent.com/assets/12978597/11315207/e6dfae18-8ff6-11e5-919d-51d912529afb.jpg)

And here I'm hovering over a pikeman inside the Aztec borders:
![calc2](https://cloud.githubusercontent.com/assets/12978597/11315220/146a4f32-8ff7-11e5-88fc-4cf2dace0aa5.jpg)

**Comment by LoneGazebo** [comment]
Post your Lua log.

**Comment by Edaka** [comment]
https://www.dropbox.com/s/xnvwa5lm4t0nakr/Lua.log?dl=0

It looks like the problem lies in this line: 
[13955.568] Runtime Error: [string "C:\Users\Edaka\Documents\My Games\Sid Meier's..."]:1094: attempt to call method 'GetCombatVersusOtherReligionTheirLands' (a nil value)

**Comment by LoneGazebo** [comment]
Ah, that's just a mistake on my end in the lua. I'll fix for the next release. You did update to the latest EUI-CBP Compatibility mod, correct?

G

**Comment by Edaka** [comment]
Assuming it wasn't updated in the hotfix, yes.Downloaded CP, CBP and EUI compatibility mod on 11/19, then updated CP and CBP only on 11/20.

**Comment by LoneGazebo** [comment]
It wasn't updated in the hoftix, no. Odd, I had it working just fine. I sometimes think that the megasync servers conspire against me.

**Comment by LoneGazebo** [comment]
For now, you can delete the 'enemyunitpanel.lua,' but it won't show values from the CBP. You'll at least get basic info, though.

**Comment by DuckZero** [comment]
Ok savegame. This was played with CPP-NoEUI (probably 19/11), but it loads and triggers bug with 20/11 fine.

http://s000.tinyupload.com/index.php?file_id=08762628556951280853

After it loads, initiate trade with germany offer 1 horse etc.

**Comment by Edaka** [comment]
Okay, it's heartbreaking to admit but I must: it must have been an outdated compatibility mod all along. I redownloaded and reinstalled it and it's working without issues so far. I also want to blame Mega, but I probably messed something up along the way of installing 11/19, reverting back to 11/17, then to 11/20 again. I think it was exactly the fact that the compatibility mod wasn't updated in the hotfix that led to this. Sorry.

**Comment by LoneGazebo** [comment]
Oh, so it works now? Yay.
