### ISSUE TITLE
god of nature pantheon error

### ISSUE THREAD

**Issue by mcymsb** [LoneGazebo/Community-Patch-DLL#7952]
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/62123081/120120960-26626000-c15e-11eb-8ee0-1143048ddbc1.png">
_1. Mod version (i.e Date - 4/14):_

5/28

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
as you can see in the screenshot, only +1 faith, +1 gold +1 food is added from god of nature pantheon although there are numerous mountains in the vicinity

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
“Capping at the city’s population”

**Comment by mcymsb** [comment]
> “Capping at the city’s population”

sorry what does that mean exactly?
