### ISSUE TITLE
CTD when switching to strategic view.

### ISSUE THREAD

**Issue by TadhgEomonn** [LoneGazebo/Community-Patch-DLL#7958]
_1. Mod version (i.e Date - 4/14): 5/28 Playing 

[David_0085 BC-0750.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6571874/David_0085.BC-0750.zip)

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6571883/CvMiniDump.zip)

_2. Mod list (if using Vox Populi only, leave blank):  many--
MODS
(1) Community Patch
(2) Community Balance Overhaul
(3) CSD for CBP
(3UC) - 3rd Unique Component (v 7)
(4) Civ IV Diplomatic Features
(4UC) 4th Unique Component (v 10)
(5) More Luxuries
(6a) Community Balance Overhaul - Compatibility Files (EUI)
(7) Community Events (v 5)
(7a) Promotion Icons for VP
(7b) UI - Promotion Tree for VP
(7c) Leugi's Israel for VP
(9a) Enhanced Air Warfare 4VP (v 1.9)
(graph) Faster Aircraft Animations (v 3)
(over) More Unique Components for VP (v 69)
(overhaul) More Wonders for VP (v 0.11)
(qua) Convenient start (v 2)
(text) Promotion Overhaul for VP (v22)
(ui) Meaningful Colours (v 8)
(ui) Trade Opportunities for VP (v11.1)
(ui) Wonder Planner for VP (v 9)
Archaeology Aesthetic Adjustments (v 1)
Barbarians - Unlimited Exp (v 2)
Better Lakes for Vox Populi (v 2.2)
Buildings - City Automaton Workers (v 1)
Calypso's Colored Religious Icons (Basic) (v 4)
Capture Great People for VP (v 3)
City Limits (v 7)
Enlightenment Era (Vox Populi) (v 3)
Even More Resources for Vox Populi (v 8)
Few More Buildings (v 210104)
Global - Commander Influence Borders (v 2)
Greatest Cities (v 11)
Infixo's Enhanced Naval Warfare for Vox Populi (v 2.1)
InfoAddict (v 22)
Leadership Reformation (v 4)
Monopoly Buildings for Vox Populi (v 3.4)
National Parks (v 1)
New Beliefs Mods (v 8)
pdansPowerPlants(V3)
Perfidious Recon Units (v 1.1)
Promotion Flags EUI for VP (v 3)
Provincial Palace (v 3)
Quick Turns (v 10)
Religion - Permanent Pantheons (v 1)
Subs Ignore Borders for ENW (v 1)
UI - City Production (v 15)
UI - City Religions (v 4)
UI - Destination (v 4)
UI - Diary (v 21)
UI - Enhanced Demographics (v 6)
UI - Filters in Trade Route Overview (Vox Populi) (v 2.1)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 2)
UI - Show XP in Military Overview (v 2.3)
UI - Small Resource Icons (v 4)
Unique City-States (v 6)
Wonder Race (v 7)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.3)

_3. Error description: as per issue title--when switching to strategic view (using mouse or F10 key) the game crashes to desktop. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Check your logs for errors. My guess is missing art.
