### ISSUE TITLE
Compatibility with "Even More Resources for VP" version >5 in multiplayer

### ISSUE THREAD

**Issue by Dromin** [LoneGazebo/Community-Patch-DLL#7959]
_1. Mod version (i.e Date - 4/14):_
5/24

<details>
<summary><i>2. Mod list (if using Vox Populi only, leave blank):</i></summary>

* (1) Community Patch
* (2) Community Balance Overhaul
* (3) CSD for CBP
* (4) Civ IV Diplomatic Features
* (5) More Luxuries
* (6a) Community Balance Overhaul - Compatibility Files (EUI)
* (7) Community Events (v 5)
* (7a) Promotion Icons for VP
* (7b) UI - Promotion Tree for VP
* Convenient start (v 2)
* Even More Resources for Vox Populi (v 8)
* Global - Civilians Move After Purchase (v 2)
* Global - Enable Magellan (v 10)
* Global - Grateful Settlers (v 4)
* Improvement - Pontoon Bridge (v 3)
* Raze Capitals and City States (v 1)

</details>

_3. Error description:_ 
I recently updated from Even More Resources v5 to v8, and as it turns out, any version of this mod highter than v5 does not work correctly when used as part of a modspack. (Now that I think about it, this was probably the reason why I was previously on such an old version in the first place...) The problem: EMR's extra resources exist in the game, get added to the in-game help section, etc., but they never actually appear on any newly generated maps. Everything does work correctly when using the mod from the in-game MODS menu.

I didn't want to revert back to the outdated mod, so I tried digging through the code & commit history and eventually narrowed down the problem to this function in `AssignStartingPlots.lua` returning `false` when it should return `true`:
```lua
-- Check if Even More Resources for Vox Populi is activated
function AssignStartingPlots:IsEvenMoreResourcesActive()
	local evenMoreResourcesModID = "8e54eb87-31e8-4fcd-aafe-ede055b463d0"
	local isUsingEvenMoreResources = false
	
	for _, mod in pairs(Modding.GetActivatedMods()) do
		if (mod.ID == evenMoreResourcesModID) then
			isUsingEvenMoreResources = true
			break
		end
	end

	return isUsingEvenMoreResources
end
```

Appearantly some code that was originally part of EMR was included in VP so that EMR didn't need to override VP's `AssignStartingPlots.lua` file, and this function is used to check if the included EMR code should be executed. And my previous modspack did work correctly because EMR v5 does overwrite the lua file, so this function was never used.

I edited the function to always return `true` as a bandaid solution, and now the extra resources appear on a new map as expected.
I think that when using a modspack, the included mods are technically seen as DLC by the game, and that's why searching for EMR in the list of mods would return `false`. Could this function be updated to use a different kind of flag to test if EMR is active (like testing for the existence of one or more of the extra resources, for example), so that it works properly in multiplayer?

**Comment by inkyant** [comment]
```
for row in DB.Query("SELECT * FROM Resources WHERE Type = 'RESOURCE_BEER'") do
	return true
end
return false
```
