### ISSUE TITLE
Long belief descriptions

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#796]
The new religious building descriptions are long enough to cause overlapping.
![text long](https://cloud.githubusercontent.com/assets/12978597/11315244/581e1c04-8ff7-11e5-9fdd-de8145783b50.jpg)

**Comment by LoneGazebo** [comment]
Blegh, I even expanded the tabs. I hate that screen, it is garbage. I'll expand.

**Comment by Edaka** [comment]
Read #795 first.

I tried to pick beliefs with the longest descriptions and here's how it actually looks:
![relover](https://cloud.githubusercontent.com/assets/12978597/11320641/90a91ce8-90a8-11e5-8c6c-5f30ff002035.jpg)
Pretty fine, imo. Could use a little more spacing, but it's definitely not wirth the hassle. I hope you haven't begun working on it. Sorry.

**Comment by LoneGazebo** [comment]
No worries. I haven't started working on it. It is tight, yep - I tested it and that was what it looked like for me. I might change the font size to help. 

I hate that window.

**Comment by JFDaly** [comment]
For Piety, I've just kept it truncated, but added the full description in a tooltip when hovering. That might be the best solution.

**Comment by LoneGazebo** [comment]
Mind sending me your lua, JFD?

**Comment by JFDaly** [comment]
Sure thing. Here's the default [ReligionOverview.lua](https://www.dropbox.com/s/hqckfybzoqjybny/ReligionOverview.lua?dl=0) with the added tooltips.

**Comment by LoneGazebo** [comment]
Awesome, thanks JFD!
