### ISSUE TITLE
(5-24) Modded civs no longer seem to make peace or do vassal calculations.

### ISSUE THREAD

**Issue by AnemoneMeer** [LoneGazebo/Community-Patch-DLL#7961]
5-24

Mods Used: Vox Populi. Various modded civs included but not limited to creations by TariscoCM, Surkitract, the Neptunia modded civs. Fire Emblem modded civs, Konosuba modded civs (downloaded just for testing). Ran individually and in groups. Ingame editor used for testing extremes, but also tested without.

The AI for civs not native to Civ V no longer calculates peace deals or vassalage. They will simply refuse peace outright all of the time (Tested with a 100 turn war where I spawned mechanized infantry swarms, as well as deliberately botching a war, and deliberately creating an unfightable stalemate war. Curiously, in a few cases, they were able to be bribed out of wars by other AIs, but would NEVER make peace on their own accord. Vassal trades simply read as impossible in both directions at all times.

Debugging attempts concluded modifying the XMLs to force them to have an AI personality did not fix, but did change their behavior.

Reproduction steps: Just use a modded civ.

**Comment by LoneGazebo** [comment]
@RecursiveVision thoughts?

**Comment by RecursiveVision** [comment]
My best guess is that a flavor is being set to 0, even though that should be impossible. Will investigate.

**Comment by RecursiveVision** [comment]
@AnemoneMeer

I just ran @pineappledan's Israel civ and peace logic worked just fine, with the flavors loading as normal (GetMeanness() returned 4).

So it must be a compatibility problem with the custom civs you're using. Could you zip the folders for the civs that you can't make peace with and post them here?

**Comment by RecursiveVision** [comment]
I tried the Fire Emblem civs modpack myself, no issues. You must have a mod conflict somewhere.
