### ISSUE TITLE
funny bug

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#7962]
![image](https://user-images.githubusercontent.com/1358966/120363276-3cae1e80-c30c-11eb-9d4d-4f2bb296a945.png)

no idea how this is possible

**Comment by LoneGazebo** [comment]
https://youtu.be/NvS351QKFV4

**Comment by IanE9** [comment]
Are they actually sharing stats or is this just the UI?

**Comment by ilteroi** [comment]
i think in fact it's the same city, but it's shown twice on the map ...
