### ISSUE TITLE
Use Whole Program Optimization (/GL)

### ISSUE THREAD

**Issue by IanE9** [LoneGazebo/Community-Patch-DLL#7963]
Is there any reason not to enable this in release builds outside of the slightly longer build times? It's useful in that it allows the code generator to optimize code invocation between different translation units. When I built with this option it also reduced the binary size.

**Comment by LoneGazebo** [comment]
I don't know why it would be a bad thing, no.

**Comment by LoneGazebo** [comment]
Also @IanE9 if you want to have fun with serialization, take a look at playertraits. Whoo boy, someone was clearly drunk when they designed that system.

**Comment by IanE9** [comment]
@LoneGazebo The write function is terrifying.

Probably not a great place to discuss this, but since save compatibility with older versions has been broken in the past would it not be safe to just remove most of the versioning tracking? Retaining compatibility with more recent saves makes sense, but these versions are way older than currently compatible afaik.

Also, couldn't we drop the MOD_SERIALIZE_INIT_READ and MOD_SERIALIZE_INIT_WRITE pattern entirely? The saves already store a version number as a header and both those macros just add a second redundant one and a sentinel that isn't being used.

**Comment by LoneGazebo** [comment]
yes, save versioning is dead, has been forever. New memory elements always break savegames.

**Comment by LoneGazebo** [comment]
I'm perfectly fine removing those headers as well.

**Comment by IanE9** [comment]
That certainly makes things easier. I'll just remove them.
