### ISSUE TITLE
5/24 - Cannot Blockade City

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7964]
_1. Mod version (i.e Date - 4/14):_
5/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I got a full surround but unable to get blockade bonuses.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/120556047-9886af00-c3c1-11eb-981b-136571cc8caa.png)

![image](https://user-images.githubusercontent.com/20593976/120556154-bc49f500-c3c1-11eb-8673-366b1b33aed8.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Stalker012345** [comment]
No, never changed.

**Comment by ilteroi** [comment]
![image](https://user-images.githubusercontent.com/1358966/120707841-1aa6ce80-c4bb-11eb-8a76-0adebdd469e1.png)

**Comment by LoneGazebo** [comment]
Perhaps recon units can’t blockade?

**Comment by LoneGazebo** [comment]
Can’t remember if that’s a thing

**Comment by Stalker012345** [comment]
Just tried another surround with all ranged units and this one was successful. So maybe its something about the zeppelin.

**Comment by Stalker012345** [comment]
Ok so there is still a problem here, or at least a change. While I have had another successful surround, it is taking a full turn before it goes into effect.

This is new, before the blockade bonus would kick in the second I put the final unit in place. While the icon would sometimes lag due to lack of refresh, I would get the blockade bonus immediately. That is no longer occuring.

**Comment by ilteroi** [comment]
it doesn't matter, the effects of the blockade are only relevant on the other player's turn. but yes, i restored the immediate feedback.

**Comment by Stalker012345** [comment]
> it doesn't matter, the effects of the blockade are only relevant on the other player's turn.

The fact that I am not getting the +20% CS boost for blockade on my entire army attacking the city for 1 turn is very relevant.
