### ISSUE TITLE
5/24 (Tactical AI) - Ships moving to far out from port to engage enemies

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7966]
_1. Mod version (i.e Date - 4/14):_
5/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So in situations like these when a foreign navy is approaching your shore, I find the AI often engages a little too far outside its shore. By doing so, its denying itself all of the land support. Even just one more hex closer to shore would still give his cities total protection, but increase my weariness due to +1 range g gun and city support.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/120586106-84aa6f80-c3f8-11eb-8a71-9723ea3650aa.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
very hard to improve this

**Comment by Stalker012345** [comment]
> very hard to improve this

Understandable, feel free to throw on the "not going to fix" tag on some of these. I just note areas of improvement, but if they are too difficult to change I completely understand.
