### ISSUE TITLE
Game hangs during Arabian turn on the turn the Arabians lose their capital

### ISSUE THREAD

**Issue by Roban1967** [LoneGazebo/Community-Patch-DLL#7968]
_1. Mod version (i.e Date - 4/14):_

2/12/2020

_2. Mod list (if using Vox Populi only, leave blank):_

(1) Community Patch (v. 94)
(2) Community Balance Overhaul (v. 13)
(3) City-State Diplomacy Mod for CBP (v. 28)
(4) C4DF - CBP (v. 11)
(5) More Luxuries - CBO Edition (5-14b) (v. 155)
(6a) Community Balance Overhaul - Compatibility Files (EUI) (v. 1) 
(7a) Promotion Icons for VP (v. 3)
(7b) UI - Promotion Tree for VP (v. 22)
Krajzen's Great Artists Pack (v. 1)
Krajzen's Great Musicians Pack (v. 1)
Krajzen's Great People Pack (v. 1)
Krajzen's Great Writers Pack (v. 1)
R.E.D Modpack (v. 27)

_3. Error description:_ 

On the turn where the England AI takes Mecca (Arabian AI capital), the game always hangs during the Arabian AI player's turn.  The game doesn't crash, it just hangs permanently.  The error is not turn number specific.  I've restarted from various saves where England takes Mecca on different turn numbers.  The game hang always and only occurs on the turn Mecca is taken.  A .zip file containing a save file right before I end my turn is attached.  The .zip file also contains the LOGS folder.

[ArabiaGameHang.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6589881/ArabiaGameHang.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by pineappledan** [comment]
This probably has nothing to do with it, but I would recommend against using more GP mods, since many more GPs were integrated into base VP a little while ago. There is probably a lot of overlap with Krajzen's mods.
R.E.D. is also known for being a very hungry mod that takes up a lot of memory. It could be contributing to instability.

**Comment by Roban1967** [comment]
Thanks for the reply, pineappledan.
I tried disabling all non-VP mods and saw no change in behavior.
I also tried running the game to the hang point with the Windows Task Manager resources manager window active, just to see the resource usage of the game at the point of the hang/crash.  The screenshot is attached.  Basically, I'm using less than 50% CPU, less than 50% RAM, and around 60% GPU memory at the point of the hang, where usage drops to near zero when the game crashes.
![Civ 5 VP Crash Task Manager Screenshot](https://user-images.githubusercontent.com/85279377/121533634-76e38400-c9ce-11eb-8f5c-2a20779362ff.jpg)

So, should I just call this save dead and move on, or is it possible there something else to examine or diagnose?  Also, this is my first time running a huge map / epic time scale game like this past the medieval era.  Is it likely I'll run into similar problems with this scale of game again in the future?  What is your experience with stability on big map games like this one?

Again, thank  you for your time and attention.

-Rob Mattes

**Comment by LoneGazebo** [comment]
one option would be to use IGE and just delete Mecca? Or perhaps forcibly turn arabia into a vassal?

**Comment by Roban1967** [comment]
Thanks for the suggestion, LoneGazebo.  I may try tinkering with the game in IGE to work around the problem.  I was hoping someone could provide some insight into why the error was occurring, so I don't solve the problem temporarily with IGE tinkering, only to have it hang up again some random number of turns later because I haven't truly solved the problem.

**Comment by Roban1967** [comment]
What is the experience of other VP users regarding map size.  Is the game more likely to have problems with bigger maps?

**Comment by RecursiveVision** [comment]
Very old version
