### ISSUE TITLE
Can pillage other civs' roads

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#797]
I didn't actually try doing it, but the button is active, which means I can probably keep the road pillaged until Caesar's borders claim that tile. Again, haven't actually tried, but I don't think that the button should be working in this situation. 
![road banditism](https://cloud.githubusercontent.com/assets/12978597/11315261/8d0c8fea-8ff7-11e5-9383-1e5ddafbcaab.jpg)

**Comment by LoneGazebo** [comment]
Hmm. Any possibility that that road was made by a now dead civ? If not, I know why it's possible.

**Comment by Radost** [comment]
Technically, any improvement outside of claimed borders belong to no one.
I thought that was a feature.

**Comment by Edaka** [comment]
Nope, no dead civs here. This road was made by Caesar himself between two cities founded by him not long ago.

**Comment by LoneGazebo** [comment]
Ok, I just need to set a 'civ dead?' check there. Radost, they 'belong' to no one, but they are assigned a 'built by' value, so I just want to test against that.
