### ISSUE TITLE
Venice Building Purchasing Bugged

### ISSUE THREAD

**Issue by amateurgamer88** [LoneGazebo/Community-Patch-DLL#7976]
_1. Mod version (i.e Date - 4/14):_
5/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Playing as Venice but, after purchasing a Castle in Cattaro, it vanishes. Doesn't show up anywhere. 

_4. Steps to reproduce (optional):_
For save file, go into Cattaro and you'll see no Castle available to be built and it's not there in the queue or as a built building. 
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6596006/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[Enrico Dandolo_0155 AD-0900.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6596008/Enrico.Dandolo_0155.AD-0900.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
seems the issue is not specific to castles but affects all building.

but what is the expected result? it should go to the build queue right?

**Comment by amateurgamer88** [comment]
Yes, it affects all buildings, including those of the previous era. 

Expected result is regular investment and the building moves into the build queue after what the puppet is currently building. That's the extent of what control Venice has regarding what the puppets will build. Thanks!
