### ISSUE TITLE
Getting war weariness from killing enemy units in my lands despite the AI not wanting peace

### ISSUE THREAD

**Issue by LukaSlovenia29** [LoneGazebo/Community-Patch-DLL#7977]
_1. Mod version (i.e Date - 4/14):_
5/28 (last hotfix)

_2. Mod list (if using Vox Populi only, leave blank):_
5/28 + Milae's difficulty mod v.4

_3. Error description:_ 
I'm getting war weariness from killing enemy units in my lands despite the AI not wanting to make peace (war score fluctuates between -4 and 4), because nothing else is really happening (I'm not losing units, I got a few tiles pillaged, but my WW is already 28). I think there might be a chance that the change in WW (that you don't get WW from killing enemy units in owned lands if the AI is not willing to make peace) didn't go through properly.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
@RecursiveVision

**Comment by RecursiveVision** [comment]
@LoneGazebo I didn't make this change, I thought you did that?

**Comment by LoneGazebo** [comment]
<points finger back>

**Comment by RecursiveVision** [comment]
I only adjusted peace logic, not WW...but ok I can look at it
