### ISSUE TITLE
2 Wonders finish on the same turn for AI- seemingly no penalty

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#798]
I've been in the spot where you have 2 wonders ending on the same turn- as i recall, one finished and the other then needed a few more turns due to the wonder penalty kicking in

i just saw theodora complete the hagia sophia and the st bails on the exact same turn. i suppose its possible one finished, then she used an engineer to hurry the other and get them both in the same turn but i'm guessing its more likely the penalty check isn't in place for this scenario for the AI? just figured it might be worth a look- uncommon scenario, but i only had 2 and 3 turns left on the same wonders respectively hah! woulda been nice to get either one- if her penalty had kicked in i think i would have

**Comment by LoneGazebo** [comment]
The penalty is in effect, but it is likely that the production needed didn't increase enough to offset the production she produced that turn.

**Comment by deadstarre** [comment]
i've never completed a wonder that didn't add at minimum a few more turns onto the others i had currently in progress. unless the penalty works differently for AI if she had THAT much production in a city by theology something would be quite off. it had to be a great engineer then i'd say

**Comment by LoneGazebo** [comment]
There's no AI exclusivity in the function, no. It could be an engineer- you can always check homelandAI logs.

G

**Comment by deadstarre** [comment]
i found a folder called Logs in my install folder but dont see anything thatsays homelandAI... where do i find it?

**Comment by LoneGazebo** [comment]
If you don't have logging enabled for the AI it won't show up.

**Comment by Iamblichos** [comment]
I've seen this happen in a game where Ramesses built two wonders one through natural build and the other with an engineer on the same turn. I actually like that I see this, that the AI is being aggressive with engineers and evaluating what they can grab on that same turn.
