### ISSUE TITLE
Keep getting Crashes

### ISSUE THREAD

**Issue by sgtslick** [LoneGazebo/Community-Patch-DLL#7983]
_1. Mod version (i.e Date - 4/14):_
5/24

_2. Mod list (if using Vox Populi only, leave blank):_
Quick Turns is the only other mod

CTD
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6602136/Logs.zip)

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6602141/CvMiniDump.zip)

**Comment by sgtslick** [comment]
I think this was the Quick Turns mod, hasn't happened again since I turned it off so maybe don't worry about this.

**Comment by ilteroi** [comment]
i play with quick turns all the time, no problem so far

**Comment by briantjack** [comment]
I'm playing a regular game on a huge map. CTD on turn 367 -- twice. Can't seem to progress any further.
