### ISSUE TITLE
5/24 - CS settling very close to each other

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7988]
_1. Mod version (i.e Date - 4/14):_
5/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Don't know if this is an oddity or true bug, pretty sure CS have to follow the 4 hex policy just like everyone else.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/120908904-e1926980-c634-11eb-92b9-9125180b071e.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
Their settlers can move in this version. I don't think they have the settling restrictions since they usually don't move and their distance is guaranteed by the map generator.

**Comment by IanE9** [comment]
If the only issue was that city states were allowed to move their settler (and assuming everything else is working properly), this should be fixed in the next version thanks to ``CS_CAN_MOVE_STARTING_SETTLER`` recently being changed to ``0``
https://github.com/LoneGazebo/Community-Patch-DLL/blob/eb9ee3329c93c9acf0d51e73131e2de9e0c757d4/Community%20Patch/Core%20Files/Core%20Values/CoreDefines.sql#L37

**Comment by psparky** [comment]
CS can settle one tile closer than major civs so this is fine (see WorldSizes.sql)
