### ISSUE TITLE
AI war unit movement- Leaving the garrison

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#799]
I know theres been recent work on the unit movement but i am repeatedly seeing one questionable move in particular from AI concerning the garrisons- they'll have an archer in the garrison, the city is under attack (but far from yet being a lost cause on their end) and then on AI turn instead of using archer to attack any of my units they'll step it out of the garrison. often while it was under influence from a ZOC (definitely no LOS issue for finding a target to hit) and can only get 1 tile out, which most of the time means i can now kill the archer on my next turn. If there is any way to add more weight to the AI decision to stay put in garrison during a city siege it might be worth a look

i hope this doesnt sound like a "make the AI better!" request =)

**Comment by LoneGazebo** [comment]
Nah, it's a specific example with a specific fix, so it is very welcome. :)

**Comment by ilteroi** [comment]
fixed
