### ISSUE TITLE
5/24 - UI Bug - Base Culture UI in cities is inaccurate

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#7991]
_1. Mod version (i.e Date - 4/14):_
5/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The base culture as shown in this screen is completely off. I did a math check, and it look likes the total culture is correct, its just the base culture that is wrong.

![image](https://user-images.githubusercontent.com/20593976/120916360-ca706d80-c66e-11eb-8f4e-4e9c3ee4a202.png)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by psparky** [comment]
So , 332 is double the actual base culture of 166.

**Comment by LoneGazebo** [comment]
Weird.

**Comment by LoneGazebo** [comment]
aha, vestigial lua hack from border growth. Was purely a UI quirk because you're in a GA and have the double border growth UA bonus.
