### ISSUE TITLE
Luxury trades not actually giving luxury but still leaving deal in the system somehow

### ISSUE THREAD

**Issue by DeAnnoCiv** [LoneGazebo/Community-Patch-DLL#7992]
_1. Mod version (i.e Date - 4/14):_
Game was started on 5/24 and changed midway through to 5/28 on turn 95.

_2. Mod list (if using Vox Populi only, leave blank):_
Milae's difficulty mod https://forums.civfanatics.com/threads/alternative-difficulty-mod.668184/ started on 5/24 version and changed contemporaneously to 5/28 version

_3. Error description:_ 
When trading for some luxuries, the deal goes through but the luxury does not appear in your available luxuries, you get no happiness for it, and you can still trade for more of it.

_4. Steps to reproduce (optional):_
After loading the save, buy Amber from the Huns for 7 gpt. Before you buy, you will have 272 gpt and 60 happiness. After, you will have 265 gpt and still 60 happiness and still no amber. He has 4 amber now though, instead of 5! If you buy the amber again, you will get it for real. Note that the same bug will happen if you buy Assyria's Cotton, but not if you buy Russia's Copper. Note that I am not the Netherlands, and this isn't exactly how they should work anyway.

---------------------------
<img width="252" alt="buggg" src="https://user-images.githubusercontent.com/47321731/120917063-23de9980-c67b-11eb-97f8-c418be173122.png">

[Nebuchadnezzar II_0178 AD-1180.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6603819/Nebuchadnezzar.II_0178.AD-1180.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6603820/Logs.zip)

**Comment by DeAnnoCiv** [comment]
I don't have proof yet but I think this has to do with when the AI reproposes a deal and you don't accept. Like for example let's say I traded 6gpt for Amber, and that lasted 50 turns. 50 turns go by, the AI wants more, I say no. Sure, the Amber is gone.

Then 5 turns later I try to trade for Amber, and doing it results in this. It's almost like when the deal got reproposed and then refused, you ended up with -1 Amber instead of 0, not that it knew to display that.

This is all just me guessing.

**Comment by DeAnnoCiv** [comment]
This is a really relevant save for the bug. If you hit next turn the Polynesia AI comes to you in the offturn to say it wants you to make the Silk deal better or cancel it. If you cancel it, and then on the next turn try to trade for Silk again, the bug happens and you don't actually get the silk. If you fix the deal in the first popup right as he complains, you get the silk. It definitely has something to do with that popup negotiation in the offturn and what happens when you say no, I think it gives you a negative silk somehow or something.

(7-1-3 no other mods)

[LearningDido_0109 BC-0150.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6806665/LearningDido_0109.BC-0150.zip)

**Comment by azum4roll** [comment]
![image](https://user-images.githubusercontent.com/14953746/126185600-eca43eab-ad10-4f71-ab74-bb0fc252ce4b.png)

https://mega.nz/folder/nSh1FQZD#nbXZ_MudFndn2ti8fiWPOQ
More example, if you're willing to download a modpack...
[Ashurbanipal_0294 AD-1848.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6842168/Ashurbanipal_0294.AD-1848.zip)
Put the save in Saves\single to load it.

**Comment by azum4roll** [comment]
Is the Netherlands in your game?

**Comment by LoneGazebo** [comment]
@RecursiveVision this is something we need to track down, but damn it is hard to find. In your test games, would you mind sticking a breakpoint in CvDiplomacy::DoRenewExpiredDeal and watch for anomalies?

**Comment by RecursiveVision** [comment]
@LoneGazebo I could, but I'm not familiar with how that code works so I'm not sure what to look for.
