### ISSUE TITLE
5/24 Unit Production and Happiness

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#7997]
5/24 beta, no other mods

I have positive global and local happiness, very little war weariness yet I am taking a huge hit to units production in every city, I can't see where it's coming from. I have a -35% modifier, while the UI displays an expected -7% only.

![civwarwear](https://user-images.githubusercontent.com/53142313/120969952-0be64300-c76b-11eb-9897-1130504ec58b.png)

**Comment by LoneGazebo** [comment]
the Production/Gold Costs is a typo, should be Gold/Faith

**Comment by LoneGazebo** [comment]
On your version it should be 'due to War Weariness', that's also a typo I've fixed. And currently the function is 5xWar Weariness, but is 2x in upcoming.
