### ISSUE TITLE
Celt's Mannanan Pantheon doesn't work completely

### ISSUE THREAD

**Issue by Cyclopia31** [LoneGazebo/Community-Patch-DLL#7998]
_1. Mod version (i.e Date - 4/14):_
VP (28/05) + EUI

_2. Mod list (if using Vox Populi only, leave blank):_
-

_3. Error description:_ 

Mannanan pantheon doesn't give the gold part from every two citizens working sea tiles in my city.

The production part works well. 

_4. Steps to reproduce (optional):_

Play The Celt with Mannanan pantheon, work at least 2 sea tiles with a city.

---------------------------
Supporting information:

1. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu): 
[Boudicca save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6611642/Boudicca.save.zip)

2. Screenshots (optional):

Here the pantheon: 
<img width="157" alt="Pantheon" src="https://user-images.githubusercontent.com/80354202/121080786-2f95a180-c7dc-11eb-9bd5-4bbb4082bf52.png">

Here we can see the expected +5 (3 + 2)  production from the religion: 
<img width="1280" alt="production Celt" src="https://user-images.githubusercontent.com/80354202/121079888-07597300-c7db-11eb-8dca-bb5f59112dcc.png">

Here we can see only the +3 gold part of the pantheon:
<img width="698" alt="gold Celt" src="https://user-images.githubusercontent.com/80354202/121081532-22c57d80-c7dd-11eb-8421-8987b0dc4fd5.png">

**Comment by pineappledan** [comment]
The offending code:
INSERT INTO Belief_CityYieldPerXTerrainTimes100
	(BeliefType, TerrainType, YieldType, Yield)
VALUES
	('BELIEF_MANANNAN', 'TERRAIN_COAST', 'YIELD_PRODUCTION', 50),
	('BELIEF_MANANNAN', 'TERRAIN_OCEAN', 'YIELD_GOLD', 50);

**Comment by pineappledan** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/commit/4ababab3df4797f1369e141aadccebf8f682ff4c

**Comment by IanE9** [comment]
@pineappledan
I believe this is still partially broken. Ocean tiles are still not going to provide additional production due to a typo.
https://github.com/LoneGazebo/Community-Patch-DLL/blob/4ababab3df4797f1369e141aadccebf8f682ff4c/Community%20Balance%20Patch/Balance%20Changes/Leaders/GodsKings/GKLeaderChanges.sql#L466-L469
Changing the terrain type on either line 466 or 467 to ``TERRAIN_OCEAN`` should solve this.
