### ISSUE TITLE
Units not able to swap?

### ISSUE THREAD

**Issue by Boxrof** [LoneGazebo/Community-Patch-DLL#800]
My units aren't able to swap, only in the CBP. Is there any way to fix this?

**Comment by LoneGazebo** [comment]
Shouldn't matter, CBP or not. Is it a valid swap?

**Comment by TechpriestEnginseer** [comment]
If you had a screenshot of you attempting to swap, then it would be possible to diagnose the issue?

**Comment by Boxrof** [comment]
Yeah, I had posted it here

https://www.reddit.com/r/civ/comments/3tq7qk/units_cant_swap_places/

http://i.imgur.com/3jHczGp.jpg

**Comment by Boxrof** [comment]
Yes, it was a valid swap, but I a starting to think it may be an issue of
the outdated version of the CBP I have.

**Comment by LoneGazebo** [comment]
You can't move the other spearman to where it is? There's a ZOC issue at stake, also, I think - ilteroi rewrote some of it, but I think ZOC + rough terrain can make swaps not work, as there's a theoretic risk that the path therein could cause two units to stack.

**Comment by Edaka** [comment]
It indeed  used to be an issue some time ago and it got fixed. I recommend you to try out the newest version, although it's not save game compatible.
