### ISSUE TITLE
5/24 (Tactical AI) - Ironclad being dumb

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#8001]
_1. Mod version (i.e Date - 4/14):_
5/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Ironclad came over here by itself, and in full view of my forces (we are at war), decides to give the CS a little attack bump....which is complete suicide. I mean just bringing the ship in is probably suicide, but this even more so.

_4. Steps to reproduce (optional):_
Save game with mods included. I gave you a few turns back all the way until the current turn.
[Sid Meier's Civilization 5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6612296/Sid.Meier.s.Civilization.5.zip)

![image](https://user-images.githubusercontent.com/20593976/121094587-7cfe1880-c7b4-11eb-9813-35faf72a943d.png)

[Logs - Copy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6612304/Logs.-.Copy.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
yeah, that should not happen:

358, Russia, Zone -1086, water, city of Budapest, posture P_WITHDRAW

but hard to tell what's going on.

**Comment by LoneGazebo** [comment]
CS has no units, perhaps that emboldens it?

**Comment by bsesar** [comment]
@LoneGazebo , I see one CS infantry in the city.

**Comment by LoneGazebo** [comment]
sorry, I meant naval units.
