### ISSUE TITLE
Stupid Manufactory placement

### ISSUE THREAD

**Issue by sgtslick** [LoneGazebo/Community-Patch-DLL#8002]
5/24
![stupid manufactory](https://user-images.githubusercontent.com/9771207/121095968-a3639880-c834-11eb-9716-9747b7cc9709.png)

**Comment by IanE9** [comment]
You should reveal the tile to the east of it to check if wasn't a tile acquired by citadel placement.

**Comment by ilteroi** [comment]
it's outside of working range ... so yeah, seems weird

**Comment by LoneGazebo** [comment]
> it's outside of working range ... so yeah, seems weird

Unless citadel

**Comment by ilteroi** [comment]
huh? plot ownership and working range are different things, no?

**Comment by ilteroi** [comment]
ah now i get it
