### ISSUE TITLE
reproducability

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8003]
it seems we still have a problem with serialization, leading to different outcomes when you load an old save.

for example, i had a testgame recently which i saved at turn X, then let the AI take over and they immediately declared war on their neighbor. when i went back, loaded the save and started autoplay again, they did not declare war.

obviously there are multiple possible reasons for this, but it points in the direction of diplo AI.

@RecursiveVision : can you take a look at this?

**Comment by LoneGazebo** [comment]
Randomization calls aren't seeded, so perhaps that's the culprit?

**Comment by LoneGazebo** [comment]
Also, have you tinkered with @IanE9's new serialization model? Might have a positive effect on reproducibility.

**Comment by IanE9** [comment]
I think you got the crux of the issue right, randomization calls need to be consistent. Unfortunately I don't think any changes I've made will actually help with this.

**Comment by ilteroi** [comment]
what?

the new fake RNG depends only on game state, so it should work fine if everything is serialized.

the pseudo RNG uses a dedicated seed and there is an explicit option to save it. which is active by default iirc.

**Comment by IanE9** [comment]
@ilteroi I took a look and I'm almost certain you're correct. Assuming everything is staying within CvRandom for sources of randomness it should all work if things are serialized back to a correct state. This isn't necessarily always the case at all though.

Here's an instance where instead of actually having AI data saved, it just gets marked to be updated. This could cause differences in behavior if the update depends on previous data that wasn't saved.
https://github.com/LoneGazebo/Community-Patch-DLL/blob/59ef2e8f9acd65c93fba4bf0e49bb3c2212455cc/CvGameCoreDLL_Expansion2/CvDangerPlots.cpp#L561-L583

**Comment by ilteroi** [comment]
yes that is a common pattern where data is regenerated on load. of course that can go wrong as well.

anyway it's good you're looking at serialization, maybe you find a smoking gun.

**Comment by RecursiveVision** [comment]
> 
> 
> it seems we still have a problem with serialization, leading to different outcomes when you load an old save.
> 
> for example, i had a testgame recently which i saved at turn X, then let the AI take over and they immediately declared war on their neighbor. when i went back, loaded the save and started autoplay again, they did not declare war.
> 
> obviously there are multiple possible reasons for this, but it points in the direction of diplo AI.
> 
> @RecursiveVision : can you take a look at this?

I don't know where to look. Would need more information.

**Comment by ilteroi** [comment]
yeah i know it's a bit thin but keep your eyes open in case you accidentally reproduce it

**Comment by LoneGazebo** [comment]
@RecursiveVision a good place to start would be to look for instances of the following functions in the diplo AI code:

        int getJonRandNum(int iNum, const char* pszLog);
	int getJonRandNumVA(int iNum, const char* pszLog, ...);
	int getAsyncRandNum(int iNum, const char* pszLog);
	int getSmallFakeRandNum(int iNum, const CvPlot& input);
	int getSmallFakeRandNum(int iNum, int iExtraSeed);

**Comment by LoneGazebo** [comment]
the functions themselves are fine to use, but if the function's 'seed' won't be consistent after reload, that can be the 'ghost in the machine' that's changing the AI's behavior. Of course, if the seed is a unit's position, but the unit goes a different way, then the rabbit hole goes back into @ilteroi's den...

**Comment by ilteroi** [comment]
no, i don't think that's the root cause. of course the RNGs will eventually diverge but that is only a symptom. i'm expecting some value (eg attitude toward another player) is not written/read correctly, or some intermediate cached data is not restored correctly. something like that.

**Comment by RecursiveVision** [comment]
There were some issues with memory not being reproduced after loading, but when I removed all the overly complex crap in the diplo AI, that issue seemed to disappear.

My best guess is that it's a problem with the leader dialogue system. AI's decision to declare war under certain circumstances (like when a human insults them, but there's also some AI to AI interactions) is randomized.

I plan on redoing leader dialogue next.

@LoneGazebo @ilteroi
