### ISSUE TITLE
Scheme for variable count database types serialization

### ISSUE THREAD

**Issue by IanE9** [LoneGazebo/Community-Patch-DLL#8010]
Since @LoneGazebo wants to start testing the changes I've made on the autovariables branch, I'd like to get some ideas and feedback on this issue now - Should variable count database types have their names hashed when serialized or should we just be serializing their index?

Currently many types that may have new entries introduced (such as units and buildings) are serialized as the hash of their name. This scheme would (hypothetically) ensure that saves are compatible if types are re-ordered or new types are introduced in the database. However this compatibility isn't guaranteed as the addition or re-ordering of these types in the database is likely to be accompanied by some sort of other save compatibility breaking change.

I've more recently tried to avoid explicitly hashing these sorts of types when migrating serialization routines and instead opted to just let the type determine how it feels it should be serialized (see CvGameEnumSerialization.cpp in autovariables). This means that when type declarations are correct or serialization makes clear the type that is meant to be represented (char m_eFeatureType in CvPlot representing a FeatureType for instance), the scheme for serialization of these types can easily be changed across the entire DLL just by changing the type's serialization function.

**Comment by ilteroi** [comment]
i don't really have an opinion here ... you are the expert here!
