### ISSUE TITLE
5/24 - AI does not seem proactively scrub fallout

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#8013]
_1. Mod version (i.e Date - 4/14):_
5/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
So this has been an issue for a long long long time, but I finally putting it into a thread after this note. So notice that Arabia still has this one area of fallout. This war was over 20 turns ago....but what's stranger to me is all of my fallout was scrubbed by automated workers. So the automated worker AI understands to clean fallout, and yet I have watched AIs time and time again struggle with it, they leave it lingering for turn after turn, and have no idea how to handle it during wartime. They just go nuts about it.

_4. Steps to reproduce (optional):_
![image](https://user-images.githubusercontent.com/20593976/121311570-284cc180-c8ca-11eb-850d-021435fd7320.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
>have no idea how to handle it during wartime. They just go nuts about it.

Could you clarify?

**Comment by Stalker012345** [comment]
> > have no idea how to handle it during wartime. They just go nuts about it.
> 
> Could you clarify?

During wartime when you nuke the AI, it gets extremely indecisive with its movement. It will move in and out of the fallout, and gets very disorganized. Further, it won't proactively send workers to clean the fallout as I've noted above. I have found just nuking an area is an extremely effective way to prevent the AI from ever attackign you, as it just doesn't seem to know what to do when it encounters fallout.

**Comment by LoneGazebo** [comment]
@ilteroi perhaps the danger calc gets too sensitive?

**Comment by Stalker012345** [comment]
So what was changed that warrants the "watch this in the next release"?

I ask because this has been a looooong standing issue in the mod, so unless some concrete changes to this area were made, there is no reason to watch....the thread should simply remain open.

**Comment by RecursiveVision** [comment]
@Stalker012345 I believe ilteroi accounted for fallout in worker AI
