### ISSUE TITLE
6/7-2 Investment graphical glitch

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#8014]
Investing in a building puts the same building in queue. Upon completition, the queue disappears so no mechanical consequences, just annoying glitch
![civinvest](https://user-images.githubusercontent.com/53142313/121312758-fc4f3180-c905-11eb-91e1-1094a6eb1ebf.png)

**Comment by ilteroi** [comment]
hmm maybe a side effect of my recent venice fix

**Comment by arievillo** [comment]
yeah i was about to open a ticket about this.
