### ISSUE TITLE
REQUEST: make city/fort/citadel retreat after melee kill an improvement column option

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#8018]
_1. Mod version (i.e Date - 4/14):_
melee units stationed in forts citadels and cities retreat back to the defensive tile if they kill a unit. This ability is hardcoded from the Pick'n'Mix mods:
https://www.picknmixmods.com/mods/CivV/Global/No%20Followup%20From%20Cities.html
```
#if defined(MOD_GLOBAL_NO_FOLLOWUP_FROM_CITIES)
        // If the attacker is in a city, don't advance
        if (MOD_GLOBAL_NO_FOLLOWUP_FROM_CITIES && kAttacker.plot()->isCity()) {
            CUSTOMLOG("Attacker %s is in a city/fort/citadel at (%i, %i) - they will not follow up", kAttacker.getName().GetCString(), kAttacker.getX(), kAttacker.getY());
            bAdvance = false;
        }
#endif
```
This is a useful attribute for if people want to make unique GGenerals with unique citadels, or other unique improvements with major defensive bonuses. It would be nice if this were exposed as a database column

**Comment by inkyant** [comment]
#8050
