### ISSUE TITLE
Improvement_AdjacentResourceYieldChanges gives bonus for hidden resources

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#8019]
_1. Mod version (i.e Date - 4/14):_ 05/24

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Improvement_AdjacentResourceYieldChanges gives yields for resources that the player hasn't revealed yet. This means users can use and improvement with this ability to "minesweep" for invisible resources. 

While not gamebreaking, it's not intended that the improvement can be used like this and gain bonuses from undiscovered resources. Could a check be added that tests if the resource is visible?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Hacienda base yields are 1 prod, 1 food, 1 gold
Hacienda is supposed to get 2 prod for each adjacent strategic resource. 
The preview for the Hacienda shows that it will get +4 prod.
Thus, there must be 2 adjacent strategic resources. 

This spot with the worker has 1 visible Horse resource, and there is an invisible resource in 1 of the other 5 tiles around it.
![image](https://user-images.githubusercontent.com/33136027/121444323-8a4e0b00-c94c-11eb-84c8-66e65fc1d0f1.png)

**Comment by pineappledan** [comment]
It was an aluminum on the southeast tile
![image](https://user-images.githubusercontent.com/33136027/121444625-1c561380-c94d-11eb-9c3d-2d481b04fad1.png)

**Comment by inkyant** [comment]
#8048
