### ISSUE TITLE
"successfully" failed trades

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#802]
this happened multiple times in my last game with multiple civs but basically, me and other civ would agree on a trade- it was "successful" but then neither of us actually traded anything. this happened when alexander tried to give me 2 of his 8 horses, it happened with many luxuries i tried to get. i couldnt make sense of it. I noticed though that sometimes if i re-arranged the trade a little, say i took his spices instead or pearls or vice versa then the deal would actually go through. my best guess at what was happening is that things were being allowed to show in the trade window that were not actually available to trade so though every party wanted it, the game wouldnt let it through

**Comment by deadstarre** [comment]
it became worse as the eras progressed, earlier on in the game i hadnt seen it at all

**Comment by Radost** [comment]
Oh wow, this bug again.

**Comment by LoneGazebo** [comment]
I was worried about this.

**Comment by LoneGazebo** [comment]
Ilteroi changed the deal AI code and may have removed my fix.

**Comment by deadstarre** [comment]
seems like it. It wouldnt hurt to give another look at the "what will make this deal work" function if possible either- the AI would tell me there was no way to make it work, but then i'd make them an offer anyway and they'd accept it (and it went through). only fair things like 1 for 1 luxuries of duplicates- they wouldn't accept trades that were unfair in any circumstance. It's not a big deal as it never hurts to not take their word for it when they say "no way jose" but as a QOL measure, if it could be improved why not.

**Comment by deadstarre** [comment]
also relevant, they now have a pretty damn good sense of whats fair and what isnt- the value of resources seems to be in a good spot

**Comment by LoneGazebo** [comment]
I'm happy with my resource revaluation, glad you are as well. I've paged ilteroi on this, as he was the last to touch the deal code (and thus he has the 'hot potato.') :)

**Comment by deadstarre** [comment]
you seem overly happy to not have to delve back into it lmao. sorry ilteroi =(

last thing that just came to mind- they'll pay 2gpt for an embassy, but always come to you offering 1. was it meant to simulate haggling in that they don't always approach with the best deal? or is this 1 specific trade instance of a bug?

**Comment by LoneGazebo** [comment]
Correct. The AI has wiggle room.
