### ISSUE TITLE
Empty trade menu

### ISSUE THREAD

**Issue by lunarium-user** [LoneGazebo/Community-Patch-DLL#8024]
_1. Mod version (i.e Date - 4/14):_

5/12/2020
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

There are empty spots under every resource category tab in the trade menu. The only readable things are categories names. AI can still send trade offers, but I can't see antyhing, only empty trade window. I used community patch alone with all others mods disabled.

_4. Steps to reproduce (optional):_
Open new game with community patch enabled, proceed to trade anything.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by arievillo** [comment]
Similar to my ticket? #7969

**Comment by lunarium-user** [comment]
> Similar to my ticket? #7969

Yes, exactly like that. It does not only make empty NPC trade offers, it renders whole trade system unusable. Seems like I didn't see your ticket and created duplicate, sorry.
