### ISSUE TITLE
No civ and natural wonder event activate

### ISSUE THREAD

**Issue by mcymsb** [LoneGazebo/Community-Patch-DLL#8026]
_1. Mod version (i.e Date - 4/14):_

6 /7 -3
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Played til 300ish turns yet no civ events no natural events pop-ups

Only minor events show up
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by IanE9** [comment]
Playing on the serialization branch I received the comet event on turn 27. I'll try on master soon.

**Comment by mcymsb** [comment]
> Playing on the serialization branch I received the comet event on turn 27. I'll try on master soon.
> Edit - Played on master, got the comet event on turn 26.
> 
> Both games were played on quick. Can anyone else reproduce?

Yep simple events occur like comers, monuments event but no civ events no natural wonder events

**Comment by skodkim** [comment]
Oh no 😦

**Comment by LoneGazebo** [comment]
>no civ events no natural events pop-ups 
mod mod?

**Comment by IanE9** [comment]
As far as I can tell there are currently no events that are specific to any civilization in the CBO. There is at least one event for a hotel to be established nearby a natural wonder which I do believe I've seen triggered before.

Can someone confirm that there are no civilization specific events without additional mods though?

**Comment by skodkim** [comment]
Now that you say it I can't think of any civ specific events in cp/cbp. There's some in other mods but don't know if they're affected by this (really hope not).

**Comment by mcymsb** [comment]
> > no civ events no natural events pop-ups
> 
> mod mod?

More components , vp and I'm playing as japan

**Comment by azum4roll** [comment]
I think they're only in the Community Events mod?

**Comment by skodkim** [comment]
@mcymsb so it just because you're not using the more events mod?

**Comment by mcymsb** [comment]
> @mcymsb so is it just because you're not using the more events mod?

I did try using community events mod as well still no. You getting various events?

**Comment by skodkim** [comment]
I'm playing a game with community events activated using CPP 6/7-5 and I have both civ-specific and natural wonder events.

\Skodkim

**Comment by mcymsb** [comment]
> I'm playing a game with community events activated using CPP 6/7-5 and I have both civ-specific and natural wonder events.
> 
> \Skodkim

Community event version?

**Comment by skodkim** [comment]
https://forums.civfanatics.com/threads/community-patch-events-development.569321/
but with the fixes I posted here:
https://forums.civfanatics.com/threads/community-patch-events-development.569321/page-20#post-16091912
