### ISSUE TITLE
5/28 (also on 6/7-5) - CP only: Policy screen inaccessible from turn 283 (280) on

### ISSUE THREAD

**Issue by Abros96** [LoneGazebo/Community-Patch-DLL#8031]
_1. Mod version (i.e Date - 4/14):_
5/28 - CP only, 6/7-5 - CP only

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
In my game with 5/28 from turn 283 on, the policy screen is not accessible anymore. In the other game with 6/7-5 it happens on turn 280.

_4. Steps to reproduce (optional):_
Load save file, you can still open the policy screen. Then click "Next turn". Afterwards it isn't possible anymore.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[No Policy Screen 6-7-5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6703881/No.Policy.Screen.6-7-5.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Catherine_0282 AD-1824.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6640251/Catherine_0282.AD-1824.zip)
[Catherine_0279 AD-1818_Policy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6696645/Catherine_0279.AD-1818_Policy.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Did you include your lua.logs from this? I don't see them.

**Comment by Abros96** [comment]
Done. Sorry, it's my first bug report.
