### ISSUE TITLE
[Feature Request] New tables for mountain and snow "start bias"

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#8035]
It's often complained that Incas don't start near any mountains. I've found that it's possible to add new "biases" for mountain (Incas) and snow (Inuits), except they're more like Venice's "forced" coastal start plus extra force to ensure they always have a mountain/snow tile in their starting radius.

For this, two new tables are needed, Civilization_Start_Near_Mountain and Civilization_Start_Near_Snow, each with two columns like the Civilization_Start_Along_River table.

I can implement the Lua part (for mapscript-generated maps), but I have no idea how to add new tables and integrate them to the DLL. CvStartPositioner.cpp (for civ5maps) is preferably changed as well, but most people play on freshly generated maps anyway.

**Comment by HungryForFood** [comment]
Don't think you need to change anything in DLL. There's no reference to Civilization_Start_Along_River, it is all handled in Lua.

CvStartPositioner.cpp does not appear to be used anywhere as well?
