### ISSUE TITLE
(6-7) Heavy tribute gives no yields

### ISSUE THREAD

**Issue by Phosphoraptor97** [LoneGazebo/Community-Patch-DLL#8039]
_1. Mod version (i.e Date - 4/14):_
6/7

_2. Mod list (if using Vox Populi only, leave blank):_
Historical Religions Edit (BNW or GK) (v 45)
InfoAddict (v 22)
Promotion Flags EUI for VP (v 3)
Really Advanced Setup (v 15)

_3. Error description:_ 
No yields from heavy tribute

_4. Steps to reproduce (optional):_
Move the scout and trireme close to Milan and demand heavy tribute on turn 112. No yields are gained.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6643577/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[AutoSave_0111 BC-0100.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6643579/AutoSave_0111.BC-0100.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20210613164614_1](https://user-images.githubusercontent.com/65775637/121801161-7a923780-cc68-11eb-9a5f-10ee7f447a22.jpg)
![20210613164632_1](https://user-images.githubusercontent.com/65775637/121801163-7bc36480-cc68-11eb-8c87-13a6b0b4548e.jpg)

**Comment by azum4roll** [comment]
You clearly gained 5 turns of culture...

**Comment by LoneGazebo** [comment]
The instant tied pop up happens on the next turn I think.

**Comment by Phosphoraptor97** [comment]
I see. Missed it since no notification popped up
