### ISSUE TITLE
Building_BuildingClassLocalYieldChanges Tooltip Possible Error?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#804]
Didn't these buildings update the affected buildings' tooltips like with colosseum and the barracks?

**Comment by LoneGazebo** [comment]
Eh? If I understand you, the code for the updated values can't update until a 'city' is active, which only happens (in the LUA) when the building is built.

**Comment by TechpriestEnginseer** [comment]
![image](https://cloud.githubusercontent.com/assets/13937047/11341567/d4d9f59e-91b7-11e5-858f-e3bb53010259.png)
![image](https://cloud.githubusercontent.com/assets/13937047/11341603/f5bef7b4-91b7-11e5-888d-36e452e280d4.png)

Then what happens here? The pantheon updated the barrack to give +2 science, but the colosseum never updated to add +2 production.

**Comment by LoneGazebo** [comment]
They use different Lua functions. So the building one isn't updating, but the belief one is?

**Comment by TechpriestEnginseer** [comment]
Just tested again with no belief, the building one isn't updating.

**Comment by LoneGazebo** [comment]
Ok, I'll take a look. Thanks for testing!

**Comment by LoneGazebo** [comment]
Fixed.

**Comment by TechpriestEnginseer** [comment]
Golden Age Points aren't added in the Building_BuildingClassLocalYieldChanges and is needed for a "unified yield" cause.

**Comment by LoneGazebo** [comment]
Yes, it is. What's your proof that it isn't?

G
