### ISSUE TITLE
6-7-5 AI Religious City Conversion Overpowered

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#8040]
_1. Mod version (i.e Date - 4/14):_
6-7-5

_2. Mod list (if using Vox Populi only, leave blank):_
Sixth Policy
Even More Luxury Resources
Enhanced Air Warfare
Enlightenment Era
Enhanced Naval Warfare

_3. Error description:_ 
Missionaries can convert cities in 1 turn even if under another religion. Mongolia was able to convert my city population 11, in 1 turn after I had used an inquisitor to remove all foreign religions. Afterwards the AI resent a missionary to the city and on 1 turn reconverted the city to another religion.  This happened to multiple cities even after the missionary lost 250 attrition. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
inquisitors simply nullify accumulated pressure from other religions (or reduce it at least). so your scenario is possible but unlikely. only happens if your own pressure is very weak. no changes required i think.

**Comment by R3P0FFXI** [comment]
@ilteroi It happened multiple times my religious pressure should have been fine as the cities were surrounded by multiple cities in my religion. No one had Bradobure yet nor did anyone have anything past the initial 4-5 starting policies.

**Comment by Stalker012345** [comment]
Did the person have the beliefs that add +25% religious pressure and/or the one that reduces current influence by 15%? Both of those really do help with conversions quite a bit, ESPECIALLY the latter one.

**Comment by R3P0FFXI** [comment]
> Did the person have the beliefs that add +25% religious pressure and/or the one that reduces current influence by 15%? Both of those really do help with conversions quite a bit, ESPECIALLY the latter one.

I will have to check on that and can let you know

**Comment by R3P0FFXI** [comment]
> Did the person have the beliefs that add +25% religious pressure and/or the one that reduces current influence by 15%? Both of those really do help with conversions quite a bit, ESPECIALLY the latter one.

No the Mongols do not have either of these that I can see

**Comment by ilteroi** [comment]
well i added the extra info in the tooltip, that might help already.

it's more a UI issue imho, pressure comes from potential traderoutes, dropping off linearly with distance. but you don't see those routes.

also the dropoff should really be quadratic, otherwise faraway cities are overrepresented. but that makes it even harder to understand.

**Comment by ilteroi** [comment]
ok i went ahead and made the dropoff quadratic anyhow. should give more impact to active religion spread.

does not really fix the missionary strength issue though, i haven't been able to reproduce that yet.

**Comment by R3P0FFXI** [comment]
@ilteroi thank you, once the changes are pushed I will test again. The only other thing I can ask about would be AI spamming you with missionaries. I get some more religious AI may want to be more aggressive at pushing their religious beliefs but I've had some where I've asked them to stop they tell me no, then I don't get the option again to ask them to stop its either deal with them spamming, denounce, or go to war. I feel like we may be missing something diplomatically in dealing with these aggressive AI tactics and Religion.

**Comment by RecursiveVision** [comment]
@R3P0FFXI I'll work on the diplomatic aspect of it when I have time.
