### ISSUE TITLE
Spy/diplomacy bug?

### ISSUE THREAD

**Issue by nayrulol** [LoneGazebo/Community-Patch-DLL#8041]
_1. Mod version (i.e Date - 4/14):_ 5.12.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Idk if this is supposed to be a thing but whenever some ai civ discovers some plans of another ai civ, they tell it the info to me. Example: I'm playing as Austria and I have Assyria, Byzantium and America in my game. Assyria discovers that America is planning a sneak attack on Byzantium but then they tell it me like "America is marching towards Constantinople, you have been warned", even though I'm playing as Austria. 
Sorry for this messy explanation, but it seems kinda weird to me.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bsesar** [comment]
This sounds like #7268 bug that was presumably closed a long time ago. @nayrulol , do you have a savegame before this sharing of intrigue happened?

**Comment by RecursiveVision** [comment]
Old version, fixed already
