### ISSUE TITLE
CS quests cant be cancelled

### ISSUE THREAD

**Issue by mcymsb** [LoneGazebo/Community-Patch-DLL#8042]
_1. Mod version (i.e Date - 4/14):_

6/7 -5
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
There's no way I can undo CS quests.

I tried declaring war but it doesn't work

How do I cancel ones quest?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@mcymsb Which quest(s) are not cancelled?

**Comment by Mileslewis** [comment]
It seems like in this patch quests are not always cancelled when you are at war with a city state, which was usually the case before.

On a related note, I don't think quests from city states who get conquered ever actually get cancelled. This is also a problem because you can only have one of each type of (non-global) quest at once.

**Comment by mcymsb** [comment]
> @mcymsb Which quest(s) are not cancelled?

Going to war with cs isn't cancelling quests. Is this intended?

**Comment by RecursiveVision** [comment]
@mcymsb The quests involving Barbarians remain active, the others should not.
