### ISSUE TITLE
6-7-5 Impossible to choose the fate of a captured City

### ISSUE THREAD

**Issue by DemaciaMaggotPie** [LoneGazebo/Community-Patch-DLL#8044]
_1. Mod version (i.e Date - 4/14):_
6-7 Hotfix 5

_2. Mod list (if using Vox Populi only, leave blank):_
3/4 UC, Milae's Hotkeys

_3. Error description:_ 
Capturing a city simply annexes it, with no option to puppet it. You can still raze it by going into the city view.

_4. Steps to reproduce (optional):_
Capture a city that would be puppetable.

---------------------------
Supporting information:
I can provide a savegame if you wanna, internet is super slow to upload so not doing it by default.

**Comment by DemaciaMaggotPie** [comment]
Addendum: I captured another city and this one "worked" just fine. Interesting...
I'll keep an eye out if the issue happens again.

**Comment by IanE9** [comment]
I've experienced this issue before. It's inconsistent and I'm not sure what causes it. If you have a save where it occurs consistently that would be very helpful.

**Comment by azum4roll** [comment]
Not just that one popup, ALL popups like capturing barbarian camps and getting ruins will be gone when this happens.

**Comment by DemaciaMaggotPie** [comment]
> 
> 
> Not just that one popup, ALL popups like capturing barbarian camps and getting ruins will be gone when this happens.

Isn't Barbarians intended though? I thought the popup was straight up removed when the gold was merged into Instant Yield.
I played with Ruins off in my game so I couldn't tell... I wish Ruins would be okay in my book but I've been revolted by so many cases of them so often.

**Comment by DemaciaMaggotPie** [comment]
https://www.dropbox.com/s/0y9vo7jdyk68kwn/QuickSave.Civ5Save?dl=0

here's a quicksave done right after I annexed a city-state (Bratislava) and was unable to choose. A few previous conquests worked fine.

**Comment by IanE9** [comment]
I don't think I can do much with saves from turns after the bug occurred. What would really be best to have would be a save from before the city is captured where upon the city being captured, the popup bug occurs consistently or at least very frequently.

If anyone knows, it would also be helpful to know if this bug is known to happen _without_ the CBP installed.

**Comment by Mileslewis** [comment]
I don't think it will happen when you open someone else's save file. The bug seems to clear itself when you reopen the game. It persisted through reloading as long as I didn't close the game though.

**Comment by IanE9** [comment]
That's actually very useful to know, thank you!

**Comment by skodkim** [comment]
Isn't this also the bug you can sometimes fix by opening and closing the tech tree (close by using the button, not ESC I believe)?

I believe this can provoke otherwise hidden notifications to pop up.

\Skodkim

**Comment by LoneGazebo** [comment]
If I were to make an educated guess, it would be that something is awry with the queue pop up manager system for pop ups. I wonder if we turned the Annex into an icon-based pop up if it would work better. Shouldn’t be too hard to do, just need to change the pop up trigger code in the DLL and make the notification block end turn

**Comment by IanE9** [comment]
> 
> 
> If I were to make an educated guess, it would be that something is awry with the queue pop up manager system for pop ups. I wonder if we turned the Annex into an icon-based pop up if it would work better. Shouldn’t be too hard to do, just need to change the pop up trigger code in the DLL and make the notification block end turn


That would be far more convenient for the user anyway. I'd still like to know if this is known to happen without CBP if only because this could also be an engine bug.

**Comment by DemaciaMaggotPie** [comment]
>  it would be that something is awry with the queue pop up manager system for pop ups

Possibly a side effect of the new Spy events?

**Comment by LoneGazebo** [comment]
No it has been a sporadic concern for years. Even vanilla.

**Comment by azum4roll** [comment]
Found this thread https://forums.civfanatics.com/threads/captured-cities-immediately-annexed.479391

The vanilla bug is related to popups. Given that there were no reports about this until recently, I think the increased amount of popups with espionage increases the chance of this happening?

**Comment by Stalker012345** [comment]
What's so interesting to me is that I have played hundreds of games of Civ 5 (you all know how frequently I discuss the games I play) and yet until the last version I never saw this bug a single solitary time, not once in my entire gameplay history (vanilla or VP). I have to believe something changed to ramp up its triggering.

**Comment by DemaciaMaggotPie** [comment]
> 
> 
> What's so interesting to me is that I have played hundreds of games of Civ 5 (you all know how frequently I discuss the games I play) and yet until the last version I never saw this bug a single solitary time, not once in my entire gameplay history (vanilla or VP). I have to believe something changed to ramp up its triggering.

As for me this is the first version where I've encountered it at all.
