### ISSUE TITLE
CTD when I capture TE-MOAK with a boat (corvette)

### ISSUE THREAD

**Issue by Cyclopia31** [LoneGazebo/Community-Patch-DLL#8047]
_1. Mod version (i.e Date - 4/14):_
6-7-5 + EUI

_2. Mod list (if using Vox Populi only, leave blank):_
4 U/C (v70)

_3. Error description:_ 
I got a CTD when I try to capture TE-MOAK with my Corvette. I tried to load 2 turns before but I keep get a CTD when I capture the city.

_4. Steps to reproduce (optional):_

Capture the city "TE-MOAK"
I have news,  I only have a CTD when I capture the city with a corvette, I have continued the game until I could capture TE-MOAK with a land unit and I didn't get a CTD, I restart the turn and captured it with a corvette: CTD.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
Only activated since the last turn...

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6650339/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu): 
[Gajah Mada_0253 AD-1715.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6650326/Gajah.Mada_0253.AD-1715.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[MiniDump Capture Te Moak.zip]
[MiniDump Capture Te Moak.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6650335/MiniDump.Capture.Te.Moak.zip)

4. Screenshots (optional):
<img width="1280" alt="TE-MOAK" src="https://user-images.githubusercontent.com/80354202/121935443-b997ba00-cd48-11eb-83db-cec9e2235ae4.png">

**Comment by RecursiveVision** [comment]
@ilteroi Could you push your most recent code? I'm merging everything together to avoid errors.

**Comment by ilteroi** [comment]
done

**Comment by RecursiveVision** [comment]
Merged, thanks!

**Comment by ilteroi** [comment]
uh, found a bug ... merge again pls

**Comment by RecursiveVision** [comment]
Done 👍
