### ISSUE TITLE
Venetian UB (v11-20)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#805]
It seems to me that the UB grants 5% event-tourism and +4 tourism after Guilds.
Would you recheck the xml?

cf.
Community Balance Patch\Balance Changes\Leaders\BraveNew\BNWNewBuildings.xml
Line: 19, 28 and 80

![venetian ub](https://cloud.githubusercontent.com/assets/11933188/11336338/d5ec2914-9227-11e5-93f5-a4f7b105f050.png)

**Comment by LoneGazebo** [comment]
I'll check, yep.

**Comment by Edaka** [comment]
Can't help but notice that "Enter new Era" isn't perfectly alligned with all the rest bullet points. Slightly offtopic and largely nitpicky, sorry (:

**Comment by LoneGazebo** [comment]
Fixed.
