### ISSUE TITLE
Yield-less flat desert tiles don't give Spanish UA bonus 

### ISSUE THREAD

**Issue by esk38265** [LoneGazebo/Community-Patch-DLL#8052]
_1. Mod version (i.e Date - 4/14):_
6-7-5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Gaining flat desert tiles with no yields, at least from settling a city, doesn't give Spain her gold and faith yields.

_4. Steps to reproduce (optional):_
Start a game as Spain, reroll until you get a start with flat desert nearby, and settle with it in the first ring or under the city.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6655582/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Isabella_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6655589/Isabella_0000.BC-4000.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
https://i.imgur.com/KNZancZ.png
https://i.imgur.com/c8wftaV.png

**Comment by pineappledan** [comment]
The offending code:
```
INSERT INTO Trait_YieldFromTileConquest		(TraitType, TerrainType, YieldType, Yield) SELECT 'TRAIT_SEVEN_CITIES', Type, 'YIELD_GOLD', 10 FROM Terrains;
INSERT INTO Trait_YieldFromTileConquest		(TraitType, TerrainType, YieldType, Yield) SELECT 'TRAIT_SEVEN_CITIES', Type, 'YIELD_FAITH', 4 FROM Terrains;

INSERT INTO Trait_YieldFromTileCultureBomb 	(TraitType, TerrainType, YieldType, Yield) SELECT 'TRAIT_SEVEN_CITIES', Type, 'YIELD_GOLD', 10 FROM Terrains;
INSERT INTO Trait_YieldFromTileCultureBomb 	(TraitType, TerrainType, YieldType, Yield) SELECT 'TRAIT_SEVEN_CITIES', Type, 'YIELD_FAITH', 4 FROM Terrains;

INSERT INTO Trait_YieldFromTileSettle 		(TraitType, TerrainType, YieldType, Yield) SELECT 'TRAIT_SEVEN_CITIES', Type, 'YIELD_GOLD', 10 FROM Terrains;
INSERT INTO Trait_YieldFromTileSettle 		(TraitType, TerrainType, YieldType, Yield) SELECT 'TRAIT_SEVEN_CITIES', Type, 'YIELD_FAITH', 4 FROM Terrains;
```
And here they are in the database:
![image](https://user-images.githubusercontent.com/33136027/122404615-9cc3d800-cf3c-11eb-8918-230067fac236.png)
So the SQL is working correctly

**Comment by ilteroi** [comment]
that's because only workable plots were counted, and plots without yield are not workable
