### ISSUE TITLE
[6-7-5] Spy Action Kidnap Specialists' bonus seems to not expire

### ISSUE THREAD

**Issue by DemaciaMaggotPie** [LoneGazebo/Community-Patch-DLL#8053]
_1. Mod version (i.e Date - 4/14):_
6-7 Hotfix 5

_2. Mod list (if using Vox Populi only, leave blank):_
3/4 UC, Milae's Hotkeys

_3. Error description:_ 
Performing a Kidnap Specialist with a Spy grants the Capital +2 base yields to all specialists for 15 turns. This bonus seems to never expire, as my capital Delhi currently has Writers outputting 21 base culture, for instance (and similar yields for all specialists)

_4. Steps to reproduce (optional):_
Kidnaps lotsa specialists!

---------------------------
Supporting information:

Forgot to screenshot it. Can attach a savegame if noone else manages to reproduce.

**Comment by RecursiveVision** [comment]
@LoneGazebo Did you push the fix for this? I didn't see it, but I might've missed it.

**Comment by LoneGazebo** [comment]
yes
