### ISSUE TITLE
[6-7-5] Receiving tech from AI during their turn breaks UI and may corrupt manual save made on following player turn

### ISSUE THREAD

**Issue by ciqasty** [LoneGazebo/Community-Patch-DLL#8055]
_1. Mod version (i.e Date - 4/14):_
(6-7-5)

_2. Mod list (if using Vox Populi only, leave blank):_
Vox populi standard installation with EUI
Really advanced setup
Faster Aircraft Animations

_3. Error description:_ 
When AI gifts player a technology during their turn - accepting offer breaks UI in this matter:
- When hitting accept offer you may hear the sound that tech was researched, AI screen should proceed to some summary sentence from AI and user should be able to leave AI screen - this does not happen, because that last sentence as well as buttons do not appear
- User may leave AI screen by hitting ESC button
- After hitting ESC button user will be on world map, but none of the UI buttons are working
- User may hit ESC second time which will bring to front just received tech window (Same as when tech is researched)
- After closing tech window UI is clickable, but cursor changes to forever spinning planet (busy) and leader/events list on right side is completely missing or is not scrollable at all

Now here comes the interesting part - I have saved the game via ESC -> save game, because UI was broken and easiest fix would be to reload game - done that and received CTD. After checking save folder the save I have made and loaded is just 15kb (other saves are around 2 megabytes). Sadly there was no dump done by game.

I also don't have screenshots of broken UI, as I expected loading game will fix the problem. In addition I am playing with new random seed, so it may be hard to reproduce - I am attaching logs, manual save few turns before, manual save that got corrupted and autosaves from few turns before (this is because I have loaded autosave 2 turns before corrupted save and continued to play, but due to random seed tech was not gifted anymore on this save and it didn't occur to me autosaves will be lost :/).

If I ever reproduce this I will update ticket with both saves and screenshots.

_4. Steps to reproduce (optional):_
AI needs to gift human player technology during their turn and user must accept it.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[ctd_on_loading.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6662873/ctd_on_loading.zip)
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6662906/saves.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
dump was not made by game

4. Screenshots (optional):
no screenshots :(

**Comment by Mcantona** [comment]
Exactly the same happened to me two times now in my playthrough. I had to load an older save game to be able to continue, but then later on it happened again.
[files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6903361/files.zip)

**Comment by LoneGazebo** [comment]
i've disabled tech gifting, as it appears there's a networking issue involved.
