### ISSUE TITLE
Two issues re: Sphere of Influence 

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#806]
Posted by max_gradient on Civfanatics:

"Seeing some weird behaviour related to the new "Sphere of Influence" resolution (which I otherwise really love) on Nov 11th version:

I got the resolution passed, and the banner tooltip of the CS says we are allies, and "you are receiving resources XYZ", however:

1. Said resources never appear in my economy, I never got the coal and oil my empire was longing for
2. During wartime I came to help the CS, however they became angry when I moved my units on their territory, and I started getting influence penalties form "trespassing".

Cheers!"

I assume the problem here might be the fact that he had less than 60/30 influence with the CS, since, ally/friend states aside, it's at these points when they start sharing resources/letting you pass in their territory.

**Comment by LoneGazebo** [comment]
I'll take a look.
