### ISSUE TITLE
Two issues re: militaristic city states' featured gift units

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#807]
Posted by kaspergm on Civfanatics (and confirmed by a couple of folks):

"The first one relates to a problem I've been experiencing for a long time: Militaristic city-states most often - but not always - have a common unit appearing as their "special" unit. For instance, I can meet a militaristic city state with the Composite Bowman or the Anti-Tank Gun listed as the unit I get if I'm their ally. This has been an issue since back in june version. I'm not sure if this is a common bug or caused by conflict perhaps with some of whowards city-state related mods? 

Anyway, today I experienced a new and truly odd twist on this bug. I meet Sofia, and they have the Janissary as their special unit (and I'm in the renaissance - yay!). Now the strange thing is: Ottomans are in the game also and very much alive! I tried to ally the CS to see if I would actually get a Janissary from them, and indeed I did!"

**Comment by LoneGazebo** [comment]
Fun. I'll take a look.

Thanks for adding these reports for me, Edaka. You are a hero.

**Comment by Edaka** [comment]
Nope, just a human trying to stay away from actually playing the game as much as possible so it doesn't interfere with real life too much, and trying to be helpful to this wonderful project along the way (: .
