### ISSUE TITLE
[6-7-5] Great wall wonder ticks away 5 damage per turn like a Minefield

### ISSUE THREAD

**Issue by SolicShooter** [LoneGazebo/Community-Patch-DLL#8079]
Title would do it I think. Guessing they use the same code, because of their similar effects.

**Comment by LoneGazebo** [comment]
Nope, not the same code. My guess is you are on encampments or citadels.

**Comment by SolicShooter** [comment]
Oh my mistake, it was the Moroccan Kasbah. Thanks for the speedy response.

**Comment by LoneGazebo** [comment]
yep!
