### ISSUE TITLE
Cities from AI via peace deals and their distance towards player

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#808]
On behalf of our dear Funak:

"For some reason whenever the AI offers me cities in a peacedeal it is ALWAYS the cities the furthest away from my territory for some reason, I have no idea if this is my bad luck, the AI being an arse, or if it calculated which city would be worst the least for me (distance from capital).

Anyways with peacedeals automatically resetting to the AI suggestion on "what deal will end this conflict" trying to negotiate anything other than their suggested cities is close to if not impossible. I would love to know if there is some way to improve upon this."

**Comment by deadstarre** [comment]
if i dont want their city i just remove it from the trade and accept. they shouldnt be made to substitute in another city that they didn't want to give?

**Comment by Edaka** [comment]
Well, from my experience they are very hard to be made to substitute them with anything else, too. The 'What do you want for this' button is very rigid  and pressing it most of he time will result in either the AI saying it won't accept (which sometimes it does despite that if you press 'Propose') or resetting the deal to the initial AI's proposal. However, I think Gazebo's said that he's thought about and worked on the issue of the 'What do you want' button a lot and it just can't be feasibly improved, and I acknowledge it's a mighty hard task.

**Comment by deadstarre** [comment]
i think im actually in favor of their rigid terms not being substitutable to where i can pick and choose just how much i get to pull down their pants over a peace deal.  if i dont want their city theres probly good for that, i dont think i should be able to take an additional 10gpt in lieu of it for example. theyre pretty generous as is

**Comment by LoneGazebo** [comment]
It's very difficult to work with, but we'll keep looking at it.

**Comment by ilteroi** [comment]
the AI looks at the "bid/ask spread" of a city. so it might be possible that the far-away cities have the best ratio there.

might also be possible that there is still a bug lurking there ...

**Comment by LoneGazebo** [comment]
I've flipped a symbol (- to +) as the function looks at lowest first, so we were weighting it incorrectly.

G

**Comment by ilteroi** [comment]
aaah. hope you did that after merging my stuff? i also fiddled with it, there was a copy/paste error.

BUT: the price ratio is only used for "normal" deals as far as i see, not for peace deals! that blows a hole into the whole theory.

**Comment by LoneGazebo** [comment]
I did, yep. The problem was that distance was being factored into city value negatively, meaning that closer cities were being placed at the wrong end of the list. Flipping that symbol means that the closer cities will be at the correct end.
