### ISSUE TITLE
Repository is totally busted

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#8084]
@LoneGazebo Check that your most recent commit was pushed correctly, there's no way there can be 2.5 million additions. And it looks like you accidentally created a whole host of subfolders (LUA\LUA\LUA\LUA).

Cloning the repository locally failed due to this.

**Comment by RecursiveVision** [comment]
I fixed it...that was seriously wacky

**Comment by LoneGazebo** [comment]
Huh
