### ISSUE TITLE
Commando Pull

### ISSUE THREAD

**Issue by LoneGazebo** [LoneGazebo/Community-Patch-DLL#8089]
@pineappledan:

[175299.234] Invalid Reference on Units.GoodyHutUpgradeUnitClass - "UNITCLASS_ZEPPELIN" does not exist in UnitClasses

Database log error - take a look?

**Comment by pineappledan** [comment]
Found it. New pull request:
https://github.com/LoneGazebo/Community-Patch-DLL/pull/8090
It's just that 1 instance right?

**Comment by LoneGazebo** [comment]
I guess so, though it if it breaks the file it may reappear. I’ll check
