### ISSUE TITLE
Era scaling of culture refunds for failed wonders

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#809]
Brought to you on behalf of dear, but stubbornly githubphobic Funak.

**Comment by deadstarre** [comment]
how much is he paying you =)

**Comment by Edaka** [comment]
Can't tell you that - I don't want to risk losing the job (:

**Comment by LoneGazebo** [comment]
Heh

**Comment by Mitchsp** [comment]
But this is already happening, later Wonders costing more hammers so more culture obtained when losing them. And anyway the 2:1 conversion rate is way better compared to 5:1 from Arts, so don't see the need to this change at all.

**Comment by Radost** [comment]
@Mitchsp No, you don't understand, you should be rewarded for failing a wonder.

**Comment by Edaka** [comment]
I agree that failing a wonder shouldn't have a consolation big enough to completely justify it, that would lead to win-win decisions and going for wonders you know you can't complete. That's most probably a bad strategy. 

However, I don't think it makes enough sense that culture consolations are so high and impactful in the early game but have practically no bearing on the course of the game in the mid-game and on. I think making the mechanic stay relevant for the entirety of the game instead is reasonable, therefore I'd even go as far as to suggest lowering the initial values, but making them scale with era.

**Comment by LoneGazebo** [comment]
Will era-scale, but at a reduced conversion.
