### ISSUE TITLE
Here are some extra random events from my old Civ 4 days

### ISSUE THREAD

**Issue by Skidizzle** [LoneGazebo/Community-Patch-DLL#8096]
I don't know if this would help, but I have a lot of old .xml event files from my Civ4 days.

I really enjoyed refining these back in the day, but I just don't play civ4 anymore now that I found Vox Populi. Now I have a few kids and just don't have the time to play and code.

Please use these for inspiration or conversion. I appreciate what you guys do for the mod.

[Events.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6711164/Events.zip)

**Comment by psparky** [comment]
I'm just an interested user, not one of the developers, but I don't think anyone is working on events at present.

It might be better to post your ideas in https://forums.civfanatics.com/threads/community-patch-events-development.569321/. However, I didn't find the TXT_KEY definitions here, that presumably would describe the events and choices and I think are crucial to understanding the ideas.

**Comment by RecursiveVision** [comment]
@Skidizzle The contribution is appreciated, but I also don't think there's anyone working on events at present.

Maybe reach out to whoever's creating the events modmod? This seems like it'd be modmod territory.
