### ISSUE TITLE
AIs wont attack land units on board

### ISSUE THREAD

**Issue by mcymsb** [LoneGazebo/Community-Patch-DLL#8098]
_1. Mod version (i.e Date - 4/14):_

6/7 -5
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Cities attack land units on board but no enemy land and naval units attack land units if aboard. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
i don't understand. do you have a picture?

**Comment by RecursiveVision** [comment]
He means embarked units, I think. Other embarked units can't attack them.

Ranged units or ships can, though. Are you saying that's not happening? A picture would indeed be helpful.

**Comment by Mileslewis** [comment]
Yea I'm guessing he means boats rarely attack embarked units. I have experienced that also.

**Comment by mcymsb** [comment]
> Yea I'm guessing he means boats rarely attack embarked units. I have experienced that also.

Yep sorry for unclear op. Embarked units are safe from naval attacks. In fact I also found out that land range units do not attack Embarked units

**Comment by ilteroi** [comment]
indeed IsEnemyUnit() returned false for embarked units ... I added that check in the last version because of blockade logic, but it has side effects ... will think of a better solution.

**Comment by LoneGazebo** [comment]
@ilteroi can you give IsEnemyUnit a domain pass and use the calling units current domain for the check?

**Comment by ilteroi** [comment]
what? no matter, everything can be solved by adding another parameter
