### ISSUE TITLE
Question about NUM_YIELD_TYPES

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#810]
Is this a defines stored in the DLL? Or is it accessible to the database? I was wondering how I might go about adding new Yields and having them appear on the map.

**Comment by ilteroi** [comment]
it's an enum ... and it has already been extended before, this is the current definition:

enum YieldTypes
{
    NO_YIELD = -1,

    YIELD_FOOD,
    YIELD_PRODUCTION,
    YIELD_GOLD,
    YIELD_SCIENCE,
    YIELD_CULTURE,
    YIELD_FAITH,
#if defined(MOD_API_UNIFIED_YIELDS_TOURISM)
    YIELD_TOURISM,
#endif
#if defined(MOD_API_UNIFIED_YIELDS_GOLDEN_AGE)
    YIELD_GOLDEN_AGE_POINTS,
#endif
#if defined(MOD_BALANCE_CORE_YIELDS)
	YIELD_GREAT_GENERAL_POINTS,
	YIELD_GREAT_ADMIRAL_POINTS,
	YIELD_POPULATION,
	YIELD_CULTURE_LOCAL,
#endif

    NUM_YIELD_TYPES
};

**Comment by JFDaly** [comment]
I know that it's been extended before. I was just wondering if it could be extended outside of the DLL, but it appears not. Some of the game's UI iterates over NUM_YIELD_TYPES instead of the Yields table. But it'd probably be easier to replace the UI's method, rather than to add two new yields to the above?

**Comment by LoneGazebo** [comment]
Yeah - it honestly depends on what you are trying to do. Adding new yields shouldn't be taken lightly, but it can easily be done by editing that enum table.

**Comment by JFDaly** [comment]
I'm content to handle every calculation myself in Lua (although things like Game.GetBuildingYieldChange seem to process the new yields anyway), it's just that without extending NUM_YIELD_TYPES to include them ('YIELD_JFD_HEALTH', 'YIELD_JFD_DISEASE'), I need to change several UI files to instead iterate over the Yields table and I'm not sure if that would have unwanted consequences, considering it wasn't done in the first place. EUI also iterates the enum table for several of its tooltips. So, would it be viable to simply extend NUM_YIELD_TYPES to include the two aforementioned, but nothing more?

**Comment by LoneGazebo** [comment]
Done. We'll see how it goes, performance-wise.

**Comment by JFDaly** [comment]
Thanks! Would it really cause that much of a performance hit?

**Comment by LoneGazebo** [comment]
Nah, shouldn't really. I'm just thinking absolute worse-case-scenario. Most expensive checks for yields (i.e. plots) skip anything above faith, anyways.
G

**Comment by LoneGazebo** [comment]
Alright, done. The values are in the CoreTableAdditions.xml file. You can edit info (like the name or icon) using SQL.

**Comment by JFDaly** [comment]
All works as expected. Thanks again!
