### ISSUE TITLE
Missing .civ5sln and .civ5proj files for (3) CSD, (4) Civ IV Diplomatic Features, (5) More Luxuries, (7a/7b) Promotion Mods

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#8104]
@LoneGazebo Could you upload these to the repository? Seems there's only the .modinfo files there.

**Comment by LoneGazebo** [comment]
yeah, they're probably being filtered out

**Comment by LoneGazebo** [comment]
checked, I don't have the original files for (4), (5), (7a/7b), only the compiled mods.

**Comment by RecursiveVision** [comment]
@LoneGazebo Unfortunate...I guess we'll have to recreate them?

**Comment by LoneGazebo** [comment]
I never had c4df's original files, nor the others.

**Comment by LoneGazebo** [comment]
recreating would be tough, as we'd lose the EID for the mods, etc. We don't need them to compile for setup, however.

**Comment by RecursiveVision** [comment]
@LoneGazebo Hmm :(

**Comment by LoneGazebo** [comment]
why do you need them?

**Comment by RecursiveVision** [comment]
@LoneGazebo With the CBP I was able to consolidate some files into each other and do some cleanup - and I've thought of merging some of the C4DF stuff (Transparent Diplomacy and other non-vassalage stuff) into the Community Patch, for instance.

Doesn't the lack of the project/solution files make it impossible for you to add/delete files to the mod?

**Comment by LoneGazebo** [comment]
technically you can add them by directly editing the .modinfo file, but it's not easy to do so  because of hashing.

**Comment by RecursiveVision** [comment]
Is there some kind of tutorial on how to recreate the hash values manually?

**Comment by LoneGazebo** [comment]
modbuddy makes them, so you could theoretically create a generic repo, make the file, check the hash in the .modinfo, and then copy that...but no guarantee that it'll match, as I don't know if the hash creation model uses an internal tool to randomize the values.

**Comment by RecursiveVision** [comment]
Worth a shot.
