### ISSUE TITLE
orthodoxy

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8106]
![image](https://user-images.githubusercontent.com/1358966/123865839-ae3db480-d92c-11eb-8cd0-2c96bd8bc512.png)

this description seems to be wrong?

PressureChangeTradeRoute is 200 so you get three times the base pressure with a trade route. modifier for friendly city states is 100 as expected. what is intended?

**Comment by LoneGazebo** [comment]
hmmm

**Comment by Stalker012345** [comment]
well that might explain some of the weird pressure scenarios people have been seeing.
