### ISSUE TITLE
The specialist food consumption

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#811]
This is renaissance era in the city with 12 specialist slots:
![8930_2015-11-24_00001](https://cloud.githubusercontent.com/assets/1131228/11366269/03eb97f4-92ce-11e5-91f4-2133f2bb12f3.png)
![8930_2015-11-24_00002](https://cloud.githubusercontent.com/assets/1131228/11366271/0684f5c8-92ce-11e5-9ed1-548f6658a83f.png)
Judging from consumption, specialists consume only 1 food? I thought their scaling per era is rougher.

**Comment by LoneGazebo** [comment]
I'll take a look. Also that tourism tooltip for growth should be unified.

**Comment by LoneGazebo** [comment]
12 * 3 (Renaissance ID #) = 36 food total (+1 over normal citizen)
36 + 14 (2 * 7) = 50 food total

So specialists are consuming 1 additional food at this point (2 is base, plus 1 from era). 

If you are in Atomic, it is 4 additional food per era:

12 * 6 (Atomic ID) = 72 food
72 + 14 = 86 food total

So specialists consume 6, which is +4 over standard citizen.

G

**Comment by Radost** [comment]
I don't get why are you putting Atomic era in there.
If the base is 2 and +1 plus era, shouldn't they consume 4 food? Classic-Medieval-Renaissance.

**Comment by LoneGazebo** [comment]
0 - Ancient (2 food per specialist)
1 - Classical (2 food per specialist)
2 - Medieval (2 food per specialist)
3- Renaissance (3 food per specialist)
4 - Industrial (4 food per specialist)
5 - Modern (5 food per specialist)
6 - Atomic (6 food per specialist)
7 - Information (6 food per specialist)

Specialist food cost is a minimum of 2, and a max of 6.

**Comment by LoneGazebo** [comment]
Atomic was an example.

**Comment by Radost** [comment]
Probably should put that information in the specialists main page of civilopedia.
