### ISSUE TITLE
Problems with starting coop wars

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#8110]
So there are two reported issues with coop wars.

The first issue is that when humans declare war early, sometimes the AI is released from the promise, while humans are forced to stay in. Not sure what causes this, will investigate.

The second issue is much harder to solve: the AI will often declare war early and drag the other player who said they needed 10 turns to prepare into the coop war.

I've pushed a few commits to the RSI branch that should prevent the AI from doing this on their own initiative, but the underlying issue is with the move troops request: if an AI notices an army built up on their borders that's about to strike, they will demand the other player move their troops.

If the AI promises not to attack, they're betraying their ally, and if they break the promise they made, they incur a global diplo penalty with most other civs.

If the AI declares war immediately, their ally is dragged into the war before they've had adequate time to prepare.

There are two solutions to this:
**(1)** Prevent defending AIs from sending move troops requests to attacking AIs, only to humans. This is definitely the easiest solution, but it comes with two problems:
Problem 1 - The defending AI is at a disadvantage because they're unable to make the same request they would make to a human.
Problem 2 - It gives humans an unfair disadvantage, since other AIs don't have to deal with this.

**(2)** Program the attacking AI to stay out of reach of the move troops request range. AI can send the request if military aggressive posture is HIGH or INCREDIBLE, or if it went from NONE to MEDIUM in one turn. Code for updating the military aggressive posture can be found in CvDiplomacyAI::DoUpdateMilitaryAggressivePostures().

Under certain circumstances they do not need to this:
- If the target civ allows them Open Borders;
- If the target civ is a friend or DP that they're betraying.

For this to work, the attacking AI would need to find a "staging" plot and position their army there instead of right next to the target player's borders, **IF** and **ONLY IF** GetDiplomacyAI()->GetGlobalCoopWarAgainstState(eTargetPlayer) == COOP_WAR_STATE_PREPARING. 

Otherwise they'd simply approach normally.

This is the preferred solution, but I'm sure it's harder to program. What are your thoughts, @ilteroi?

**Comment by ilteroi** [comment]
my feeling is that option 2 is indeed quite hard to to implement, but i'll take a look.

but even in the best case it would simply reduce the frequency of those premature wars. cannot have a hard exclusion zone. or what is your expectation?

**Comment by RecursiveVision** [comment]
@ilteroi I think simply reducing the frequency would be acceptable, especially since my changes should prevent the AI from declaring war early on its own initiative.

Most players probably wouldn't be opposed to an occasional premature war but the reports I'm getting are that people are unhappy that it seems to happen constantly.

**Comment by RecursiveVision** [comment]
@ilteroi
I came up with a much easier solution: AIs won't send military promise requests to other AIs that are preparing for a coop war with a human. This way humans aren't dragged into war early and the AI is still usually able to send the promise requests.
