### ISSUE TITLE
Multiple CTD (5-5).  2 attached.

### ISSUE THREAD

**Issue by voxpopplayer** [LoneGazebo/Community-Patch-DLL#8112]
_1. Mod version (i.e Date - 4/14):_

(5-5)
[CTD files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6750377/CTD.files.zip)

_2. Mod list (if using Vox Populi only, leave blank):_

(1) Community patch (v.94).  (5-5)
City Limits (v.7)
Faster Aircraft Animations (v.3)
InfoAddict (v.22)
(2) Community Balance Overhaul (v.13).  (5-5)
(4) CADF - CBP (v.11).  9-27)
(3) City State Diplomacy Mod for CBP (v.28) . (1-28)
(5) More Luxuries - CBO Edition (5-14b) (v.155)
(6a) Community Balance Overhaul - Compatibility Files EUI (v.1).  (5-5)
(7a) Promotion Icons for VP (v.3)
(7b) UI - Promotion Tree for VP (v.22)
UI - Filters in Trade Route Overview (Vox Populi) (v.1)
UI - Religion Spread (Vox Populi) (v.1)
Quick turns (v.10)

_3. Error description:_ 

Multiple CTD.  Loading previous saves (5-15 turns earlier) does not prevent CTD.

Greece @ turn 271
Zulu @ turn 181

_4. Steps to reproduce (optional):_

Both saves 1 turn before crashing.  Both have crashed multiple times, and have tried going back 15 turns for the Greece game, and 10 (twice) for the Zulu game.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Version is 2 months old, likely fixed in the interim.
