### ISSUE TITLE
Change to GameSetupScreen.lua not merged

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#8114]
@LoneGazebo The change to line 39 of GameSetupScreen.lua in UI_bc1 is not included in the autoinstaller.

(Unfortunately there was no alternative way to resolve this problem, other than removing the check.)

**Comment by LoneGazebo** [comment]
what's the change specifically? I don't see it. remove the isWBMap?

**Comment by RecursiveVision** [comment]
@LoneGazebo Remove bIsModding

**Comment by IanE9** [comment]
The exact details and change needed are here #8037

It's already been said but this really should be reported to bc1 so that it can be included as a standard fix in EUI.

**Comment by RecursiveVision** [comment]
@IanE9 VP uses a very old version of EUI. It may have been fixed in the meantime.
