### ISSUE TITLE
07/01/2021 - Can't Assign Specialists

### ISSUE THREAD

**Issue by raymond-sutandar** [LoneGazebo/Community-Patch-DLL#8115]
_1. Mod version (i.e Date - 4/14):_
07/01/2021

_2. Mod list (if using Vox Populi only, leave blank):_
(1) Community Patch
(2) Community Balance Overhaul
(3) CSD for CBP
(4) Civ IV Diplomatic Features
(5) More Luxuries
(6a) Community Balance Overhaul - Compatibility Files (EUI)
(7a) Promotion Icons for VP
(7b) UI - Promotion Tree for VP
(9a) Enhanced Air Warfare 4VP (v 1.9)
(over) More Unique Components for VP ----> v70
(overhaul) More Wonders for VP -----> v0.11
(ui) Trade Opportunities for VP
CIV-Linked Great Generals (v 11)
Contextual Unit Names (v 3)
Diplomacy Responses Extended (v1)
Enlightenment Era (Vox Populi) (v 3)
Even More Resources for Vox Populi (v 8)
Hex Conquer (Borders Only)
Historical Religions Complete (BNW or GK) (v 45)
Infixo's Enhanced Naval Warfare for Vox Populi (v 2.1)
JFDLC (07) - JFD's Cultural Diversity (Core) (v 17)
JFDLC (07a) - JFD's Cultural Diversity (Soundtrack)
Map Labels (v 6)
More Great Musicians
More Great Works (v 3)
Music Changer (v 2)
pdansTweaks (v. 17)
PerfectWorld 3 (v 4)
Quick Turns (v 10)
Really Advanced Setup (v 15)

_3. Error description:_ 
After clicking the "Manually Assign Specialists" button and clicking on the buttons to assign specialists, I can't assign any specialists.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs_and_Save_File.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6755106/Logs_and_Save_File.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

Save game is in the Logs_and_Save_File.zip above

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by vetox20** [comment]
To add to this I am having same issue. I'm using just the standard EUI VP 7-1 install w/no extra mods
[Logs_Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6756261/Logs_Save.zip)

**Comment by IanE9** [comment]
``CvCityCitizens::DoRemoveWorstCitizen()`` is failing to find a citizen to remove for some reason.

**Comment by ilteroi** [comment]
hmm i've got another fix :)

**Comment by IanE9** [comment]
@ilteroi If yours is cleaner open a pull request and I'll close mine.
