### ISSUE TITLE
Population Does Not Appear In Non-EUI

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#8116]
_1. Mod version (i.e Date - 4/14):_

6-7

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Population and defence do not appear on any cities not owned by me.  Alliance status is not shown on the overview map with City-Stations.

_4. Steps to reproduce (optional):_

Non-EUI.
![No Population](https://user-images.githubusercontent.com/16022773/124310827-c2570100-db3a-11eb-994c-6fda1ba08ba2.jpg)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by IanE9** [comment]
This is unusual. I just tried to reproduce this and found no problem on turn 1.
![foo](https://user-images.githubusercontent.com/7848638/124313082-9bde9900-db2d-11eb-97ad-88f506e8af30.png)

These extra tidbits of info would be helpful:

- Have you made sure there is no ``UI_bc1`` directory in your ``DLC`` directory?
- Did this issue begin occurring mid game?
- Did this issue begin occurring after loading a save?
- Does the issue persist after restarting the game?

**Comment by LoneGazebo** [comment]
He’s on 6-7, known issue there. @Gidoza update to latest.

**Comment by LoneGazebo** [comment]
@IanE9 it was related to your inline change to lua functions.

**Comment by IanE9** [comment]
Ahh I missed the version number whoops. Thank you for the correction.

**Comment by Gidoza** [comment]
Hi there - just found out there was a new version on July 1st and missed that detail.  FYI, the July 1st version seems to have no problems.

Thanks!
