### ISSUE TITLE
Auto Unit Cycle does not work after reload

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#812]
I'm using the EUI version and reload generally works fine, but I find the the "auto unit cycle" option is disabled after reloading and what's worse, if you re-activate it, it won't stay activated.

This is very annoying. Anyone have a clue what could be the problem?

**Comment by LoneGazebo** [comment]
Sounds like a player's unit sequence IDs aren't being reset properly, perhaps?

**Comment by ilteroi** [comment]
always the poor little sequence IDs :)

seriously, the problem is that the checkmark in the options is vanishing on its own. i think that's a lua issue. does that happen for you as well?

**Comment by LoneGazebo** [comment]
That's odd, I haven't seen it happen, no.

**Comment by Iamblichos** [comment]
This happened to me on a couple versions back...back in October (?) IIRC.
