### ISSUE TITLE
City capture choice screen does not close when choosing raze. 

### ISSUE THREAD

**Issue by rongute** [LoneGazebo/Community-Patch-DLL#8126]
_1. Mod version (i.e Date - 4/14):_
2021-7-1 (non hotfix version)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When choosing Raze, city capture choice screen does not close, leaving you unable to proceed or end turn. Reported on forum but not previously reported in Github. 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6758188/Logs.zip)

[Dido_0492 AD-0960.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6758181/Dido_0492.AD-0960.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
-Save game zip attached. Save game is after city capture but is locked into the city capture choice screen. 

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by DeAnnoCiv** [comment]
In my different game, I could choose Annex and then it was already Razing, but after it hit 1 population it spent 10 more turns finishing the raze.

**Comment by rongute** [comment]
Opening file with hotfix version doesn't solve the issue.
