### ISSUE TITLE
World map trading is broken (maps stack when trading)

### ISSUE THREAD

**Issue by Erchufu** [LoneGazebo/Community-Patch-DLL#8129]
_1. Mod version (i.e Date - 4/14):_
Latest official 12-1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
First, I'm not sure if this has been reported yet. You can stack maps when trading with any civ, allowing you to get all their money and resources pretty much for free. 

_4. Steps to reproduce (optional):_
First you need to suggest trading world maps to a civ. Then, you just click on "what will make this deal work?" and the civ ai will add one or more world maps on your and their side of the trade. You just remove their world map(s) and hit the what will make this deal work again and the value of your trade will keep rising and rising, as many times as you want until they dont have anything else to give you.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6765512/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[AutoSave_0251 AD-1962.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6765524/AutoSave_0251.AD-1962.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![valueof1map](https://user-images.githubusercontent.com/86976551/124500036-546f3b80-ddbf-11eb-9a33-fc651edcde09.JPG)
![valueofstackedmaps](https://user-images.githubusercontent.com/86976551/124500042-576a2c00-ddbf-11eb-9f43-f9457cdb1d09.JPG)

**Comment by LoneGazebo** [comment]
@ilteroi any changes here?

**Comment by RecursiveVision** [comment]
Old version; fixed already
