### ISSUE TITLE
(7-1)(Feature request below) UI not working with EUI

### ISSUE THREAD

**Issue by Phosphoraptor97** [LoneGazebo/Community-Patch-DLL#8132]
_1. Mod version (i.e Date - 4/14):_
7-1-2

_2. Mod list (if using Vox Populi only, leave blank):_
Historical Religions Edit (BNW or GK) (v 45)
InfoAddict (v 22)
Promotion Flags EUI for VP (v 3)
UI_bc1 from EUI v1.29h

_3. Error description:_ 
Top bar UI elements not functioning

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6767795/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20210706143039_1](https://user-images.githubusercontent.com/65775637/124553249-19c0de00-de67-11eb-8679-313c25439f2c.jpg)

DLC folder:
![image](https://user-images.githubusercontent.com/65775637/124553458-5a205c00-de67-11eb-86f5-d3bc137ec471.png)

**Comment by azum4roll** [comment]
Is that the VP version of EUI?

**Comment by psparky** [comment]
Standard EUI isn't compatible with Vox Populi - use the version included in the download (which is a customized variant of 1.28).

**Comment by Phosphoraptor97** [comment]
Where do I find it?

**Comment by Phosphoraptor97** [comment]
Reinstalled VP, games works. But I would like to see a separate install for the special EUI on the civfanatics forum.

**Comment by LoneGazebo** [comment]
Check the how to install thread.
