### ISSUE TITLE
7-1 Indonesia Happiness Monopoly bonus disappears upon trade

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#8133]
7-1-2 hotfix, no other mods

The +3 Happiness monopoly bonus is correctly awarded, but when you trade away the last copy of cloves/nutmeg/pepper it disappears. Easy to check with your first luxury, worth 5 avg happiness (vs the usual 2), but you lose all of that upon trading it away.

**Comment by LoneGazebo** [comment]
if you trade away the last copy, you're losing the natural happiness bonus of the resource.

**Comment by DeAnnoCiv** [comment]
I've actually seen this happen with Furs too in a recent game and was confused but this explains it. I traded my last furs and lost both the natural bonus AND the additional +6 happiness, lost a total of 9 happiness or so.

**Comment by RecursiveVision** [comment]
@LoneGazebo Shouldn't it be only the base happiness that's lost? I thought monopoly bonuses were supposed to persist even if traded away?

**Comment by LoneGazebo** [comment]
@RecursiveVision nope, the bonus is a bonus to the happiness _from_ the resource.
