### ISSUE TITLE
Events with multiple choices impossible to interact with, prevents turn from ending.

### ISSUE THREAD

**Issue by ExNilos** [LoneGazebo/Community-Patch-DLL#8134]
_1. Mod version (i.e Date - 4/14):_ Date 6th of July 2021. Not sure what version but it's up to date according to Steam.

_2. Mod list (if using Vox Populi only, leave blank):_ CP, CBP, CSD, C4DF, More Luxuries, CBP compatibility files (No-EUI), Promotion Icons for VP, UI - Promotion Tree for VP, Ingame Editor. 

_3. Error description:_ A notification pops up: "An event with multiple options has occurred, and awaits your decision." It is impossible to dismiss or otherwise remove this notification. The "END TURN" button is replaced with "MAKE EVENT CHOICE" and is unresponsive to left and right clicks. It is impossible to interact with, making the turn impossible to end.

_4. Steps to reproduce (optional):_ So far this has happened twice, once as as India turn 27, next as India turn 8. I've turned off these events so I can play in the mean time.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by BZab** [comment]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0.3.279

_2. Mod list (if using Vox Populi only, leave blank):_

- (9a) Enhance Air Warfare 4VP v1.0
- Civ Names by Policies (v 8)
- Enhanced Naval Warfare for Vox Populi (v 1)
- Global Warming (v 7)
- Global Warming Congress (v 2)
- Hex Conquer and Release (v 3)
- Improved Air Recon (v 1)
- InfoAddict (v 22)
- Reforestation (v 8)

_3. Error description:_ 
Exactly same bug as desribed in [Issue #8134](https://github.com/LoneGazebo/Community-Patch-DLL/issues/8134).
Seems like the choice menu gets unresponsive only in multiplayer games (ie in single player ones it works for me flawlessly).

_4. Logs + save file:_
_It is random event, so it may take few turns after saved one to let it happen again_
[report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7253692/report.zip)
