### ISSUE TITLE
Enlightenment Era building names and descriptions are not pulling from database

### ISSUE THREAD

**Issue by lukethighwalker** [LoneGazebo/Community-Patch-DLL#8138]
_1. Mod version (i.e Date - 4/14):_
beta 6-7-5

_2. Mod list (if using Vox Populi only, leave blank):_
all the VP with CBP and UI
EE for VP
Even more resources for VP

_3. Error description:_ 
Enlightenment Era building names and descriptions are not pulling from database. For Example, the Tavern is showing up as "txt_key_building_EE_Manor_help", etc

_4. Steps to reproduce (optional):_
enter enlightenment era and try to build EE buidings

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
We don't manage EE.
