### ISSUE TITLE
7-1 Do purchased Pillaged Tiles still count for Unhappiness?

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#8139]
_1. Mod version (i.e Date - 4/14):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
City has Unhappiness from pillaged tiles despite none being nearby.  The tiles were pillaged before Washington bought them.  
The Copper and Citrus by the Citadel.  [I should have scouted the area better before placing that Citadel.]
_4. Steps to reproduce (optional):_
Citadel pillaged tiles

---------------------------

4. Screenshots (optional):
Black Circle were tiles I owned, Red X's were tiles that were pillaged before being purchased.  
![20210707233947_1](https://user-images.githubusercontent.com/11430209/124859468-ff2d5880-df7d-11eb-8a92-10b6f039c279.jpg)

**Comment by RecursiveVision** [comment]
@phantommaxwell Yes
