### ISSUE TITLE
CTD when asking Celts AI "What would make this deal work?"

### ISSUE THREAD

**Issue by Makikou** [LoneGazebo/Community-Patch-DLL#814]
Long story short, currently playing as Romans on Chieftain difficulty, one of the enemies are the Celts. The game crashes constantly & consistently if you click the "What would make this deal work" when either AI or player initiates the trade. This happens only when trading w/ Celts.

How do i upload CvMiniDump.dmp here?

**Comment by LoneGazebo** [comment]
You can change the file extension, or you can host it on a site like mega and then post the link.

**Comment by Makikou** [comment]
Here: https://mega.nz/#!0A81FDyQ!b03RYzAM7JYw4KE3lF4SiqEEh3-LQd_C6mvN0lUSZqU

Do you need any .log files?

**Comment by LoneGazebo** [comment]
It crashes to lua, so you've got a mod conflict somewhere.

**Comment by Makikou** [comment]
Interesting. I'm only running the mods that came with the 20/11 [Hotfix] installer.

**Comment by Edaka** [comment]
http://forums.civfanatics.com/showthread.php?t=487482
That should do it. Follow the instructions and try to reproduce the crash.

**Comment by Makikou** [comment]
Here i am again! Managed to reproduce it. Celts offer me a trade with them paying me 1 GPT for Crab resource. I change the GPT value to 2. I ask them what would make this work -> CTD.

https://mega.nz/#F!sNVwBDIC!7DTuqyclIZFP4eBf7oBEkg 
There's the logs in the folder and crash dump again.

Cheers.
