### ISSUE TITLE
Opening tech tree leads to CTD 7-1

### ISSUE THREAD

**Issue by pHerpAndDerp** [LoneGazebo/Community-Patch-DLL#8140]
_1. Mod version (i.e Date - 4/14):_

Vox Populi (7-1).exe-20210702T023912Z-001
_2. Mod list (if using Vox Populi only, leave blank):_
Edit: Vox Populi with EUI

_3. Error description:_ 
Opening the tech screen crashes the game. As far as I see it every time with the provided save. On a general note it seems that the crash starts to appear late game with most of the map revealed, a lot of units, etc. 
_4. Steps to reproduce (optional):_
Load attached save 
Open tech tree
Get CTD
[civ death.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6785803/civ.death.zip)

---------------------------
Supporting information:
I have had a lot of CTD late game with this beta and the previous one. I haven't played Vox Populi in a long time, but when I was playing an year or two ago I did not have these issues. My whole PC setup has changed since then, so it could be the root of the problem
Both of my latest games were ended by this issue where from some point in the game opening the tech screen crashes the game. Most of the other crashes were not consistent, so I could load a save and proceed.

On an unrelated note, thank you for your amazing creation, Vox Populi is amazing, and even if I am getting cut from the late game by issues like this I would still enjoy playing it.

**Comment by RecursiveVision** [comment]
Memory issue. Can't be fixed.

**Comment by RecursiveVision** [comment]
Memory issue. Unfixable, but saving/loading can help.
