### ISSUE TITLE
Open Borders renewal issue

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#8141]
Latest version (7-1-3).

So my mutual Open Borders with America was about to expire, and I needed to renew it this turn so that my units didn't get pushed into Spanish lands to get killed. As you see, 0 turns on both sides.
![image](https://user-images.githubusercontent.com/14953746/125201114-48441c00-e2a0-11eb-8826-4828a8cbb9f6.png)

On the trade screen, I could only choose to buy Open Borders from him, which was ok, that's what I needed.
![image](https://user-images.githubusercontent.com/14953746/125201144-614ccd00-e2a0-11eb-88f5-c718548673d8.png)

The trade went through and I had 51 turns of Open Borders with him, somehow. However, next turn both Open Borders expired as if I never renewed it, my crossbow got killed, and I was paying America 2GPT for no reason.

**Comment by RecursiveVision** [comment]
Really need save files for these kinds of issues...

**Comment by azum4roll** [comment]
Can't you just replicate it with any mutual open borders and wait 50 turns?

**Comment by LoneGazebo** [comment]
nope, since the issue is a corrupted trade cache.
