### ISSUE TITLE
Unable to Click Spy Event

### ISSUE THREAD

**Issue by Teholb** [LoneGazebo/Community-Patch-DLL#8145]
1. Mod version (i.e Date - 4/14): 7-1-3 + EUI as a modpack in SP, no additional modmods

2. Mod list (if using Vox Populi only, leave blank):

3. Error description: Unable to end turn due to "Make Event Choice" button being unclickable.  It is a spy event in my Capital- the first such event.

4. Steps to reproduce (optional): load the attached save

1a. Log files:

[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803910/xml.log)
[xml-perf.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803912/xml-perf.log)
[achievements_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803913/achievements_debug.log)
[APP.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803914/APP.log)
[CustomMods.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803915/CustomMods.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803916/Database.log)
[Gamecore.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803917/Gamecore.log)
[init_host.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803918/init_host.log)
[Localization.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803919/Localization.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803920/Lua.log)
[modding.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803921/modding.log)
[net_message_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803922/net_message_debug.log)
[stopwatch.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803923/stopwatch.log)
[system_init.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803924/system_init.log)

2. Save game:

[Suleiman_0196 AD-1360.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6803948/Suleiman_0196.AD-1360.zip)

3. CvMiniDump.dmp file:

N/A

4. Screenshots (optional):

**Comment by Teholb** [comment]
This is the MP I am using, in case that is helpful.

**Comment by Legoras** [comment]
Already fixed but maybe will help future people / mods here*

Looked at your modpack and found what is wrong - missing, will just copy-paste from forum.

https://forums.civfanatics.com/threads/7-1-new-beta-version.671286/page-7#post-16125506\

@@Need to change guide for modpack.
