### ISSUE TITLE
Broken expansion promise after conquest

### ISSUE THREAD

**Issue by Chase-star** [LoneGazebo/Community-Patch-DLL#8146]
_1. Mod version (i.e Date - 4/14):_ 7/1 Hotfix 3

_2. Mod list (if using Vox Populi only, leave blank):
Vox Populi
Trade Opportunities
mixn'match (Global - City Forest Bonus, Global - City Jungle Bonus, Global - City State Airbases, Global - Local Generals, Global - Passable Forts, Improvements - Airbases)
Promotion Flags EUI for VP
Reforestation
TopPanel Replace (EUI Only)
UI - Destination
UI - Filters in Trade Route Overview
UI - Improved City View (Vox Populi EUI)
UI - Religion Spread (Vox Populi)

These mods are compiled into a modpack though so please tell if the modpack also needs to be uploaded.
_3. Error description:_ 
After conquering the capital of Songhai, Denmark shows up telling me that I am a thief for breaking the promise of NOT expanding. 

_4. Steps to reproduce (optional):_
Capture the city (I only tried using the knight)
Select Annex or Puppet
End turn
Denmark will message you in his turn

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Horde.Civ5Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6809466/Horde.Civ5Save.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![2021-07-13 21_46_50-Greenshot](https://user-images.githubusercontent.com/74890182/125466666-7ff54d15-3f87-408e-8ffa-1de6bf0b3b80.png)
![2021-07-13 21_50_16-Greenshot](https://user-images.githubusercontent.com/74890182/125466681-0a197f28-e3a7-4bd3-8cf3-93c8f3dcaf5e.png)
![2021-07-13 21_52_19-Greenshot](https://user-images.githubusercontent.com/74890182/125466687-bced71c9-c907-45be-9733-04ddd72d37c4.png)
![2021-07-13 21_53_47-Greenshot](https://user-images.githubusercontent.com/74890182/125466691-e0a8e33d-1841-4868-b273-f69caa068cd8.png)
![2021-07-13 21_54_45-Greenshot](https://user-images.githubusercontent.com/74890182/125466695-d0cda404-3370-42ff-a94f-96093a9a437e.png)

**Comment by LoneGazebo** [comment]
that counts as expansion

**Comment by RecursiveVision** [comment]
Intended

**Comment by Neborya** [comment]
Just reported this case, because it seems like a 99% bug, so people are most likely going to report it again and again.
If this is intentional, the promise should should say something about conquering too.

**Comment by RecursiveVision** [comment]
@Neborya I updated the text to make it more clear.

**Comment by Neborya** [comment]
At least it would be clear, thanks!

I'd argue, that gaining city through conquering shouldn't be considered expansion in all cases (at least because you cannot raze the conquered city instantly to keep the promise), but maybe a forum thread would suit better for this discussion.
