### ISSUE TITLE
Council not giving instant science yields on citizen birth

### ISSUE THREAD

**Issue by dape6509** [LoneGazebo/Community-Patch-DLL#8148]
_1. Mod version (i.e Date - 4/14):_
7-1-3

_2. Mod list (if using Vox Populi only, leave blank):_
Info Addict
Strange Religions

_3. Error description:_ 
No science yields received in citizen birth, also no notification and not listed in instant yields tooltip.

_4. Steps to reproduce (optional):_
Load eng37end.Civ5Save
Proceed to next turn

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[councilLogs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6818456/councilLogs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[councilbug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6818453/councilbug.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by dape6509** [comment]
Just to follow up, I did get the yield with the next birth, but not the one that came two turns after the council was built. Was this an intentional change or just a fluke for me? Either way, I haven't seen it before.

**Comment by LoneGazebo** [comment]
Bonus only applies if the city is hitting its new largest size. You likely built a settler which reduced the size, then reached that size again (no bonus), then exceeded it (bonus)
