### ISSUE TITLE
City state influence decay after liberation

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#815]
Bromar1: "Yeah, every time I liberate a CS (from barbs or otherwise) my influence gets set to about 70 but then degrades by like -4 every turn. Is this intended? It doesn't make sense to put the effort in liberating them if your influence is gonna drop to nothing anyway..."

Enginseer: "When you liberate a city, the city will be currently damaged. The tooltip is sort of inaccurate because as long as the city's state hp is not at maximum, then your influence will decay significantly. "

IIRC, the influence decay takes place only if you've pledged to protect a CS, right? That would mean that it's retained after a CS has been conquered and liberated, which probably shouldn't take place.

**Comment by LoneGazebo** [comment]
Yep, will fix PtP resetting issue.
G
