### ISSUE TITLE
Some cities unable to build stable

### ISSUE THREAD

**Issue by Phosphoraptor97** [LoneGazebo/Community-Patch-DLL#8152]
_1. Mod version (i.e Date - 4/14):_
(7-1-3)

_2. Mod list (if using Vox Populi only, leave blank):_
Historical Religions Edit (BNW or GK) (v 45)
InfoAddict (v 22)
Promotion Flags EUI for VP (v 3)

_3. Error description:_ 
City in screenshot has improved horse in range and is working it, but cannot build stable.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6836532/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[AutoSave_0365 AD-1710.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6836535/AutoSave_0365.AD-1710.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20210718233757_1](https://user-images.githubusercontent.com/65775637/126073497-d517ee54-0eb1-4f05-a9cb-9f1173b84e4f.jpg)

**Comment by Mileslewis** [comment]
Not sure if this is the reason but switching which city is working a tile no longer updates which city 'owns' that tile. So whichever city is working it when the pasture is built keeps the horse and there fore ability to build a stable forever.

**Comment by DeAnnoCiv** [comment]
I can confirm the above, and that's the case for Stone Works etc too. I think it actually isn't the case for East India though, that pays attention to what city currently has it.

**Comment by LoneGazebo** [comment]
@Mileslewis is correct.
