### ISSUE TITLE
"Science Theft" spy event gives 1/10th of expected yields

### ISSUE THREAD

**Issue by dape6509** [LoneGazebo/Community-Patch-DLL#8154]
_1. Mod version (i.e Date - 4/14):_
7-1-3

_2. Mod list (if using Vox Populi only, leave blank):_
Info Addict
Strange Religions

_3. Error description:_ 
Dr. Grey's science theft from Addis Adaba is supposed to yield 600 beakers but only yields 60. Hardly seems worth the effort!

_4. Steps to reproduce (optional):_
Load eng47end.Civ5Save
Proceed to next turn

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[spytheftLogs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6839229/spytheftLogs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[spytheftbug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6839208/spytheftbug.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20210719022219_1](https://user-images.githubusercontent.com/19981950/126129499-b68c98a6-0a89-496a-a714-78bbf6f5f3e1.jpg)
![20210719022231_1](https://user-images.githubusercontent.com/19981950/126129528-9057ed06-d821-435b-88bc-10ce4598d2dd.jpg)

**Comment by phantommaxwell** [comment]
Gold as well.
