### ISSUE TITLE
IsNoCoast parameter in Buildings table is broken

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#8155]
VP 7-1-3.
**IsNoCoast** parameter does not allow to build a building/wonder if inland city lays around lake or river. It was added few versions ago.

**Comment by ilteroi** [comment]
river should be fine ... but lake coast is coast

**Comment by adaneslavo** [comment]
So it should have an exception, right?

**Comment by ilteroi** [comment]
no

**Comment by adaneslavo** [comment]
Is there any way to use some another field from database to include Lakes as a correct parameter? @HungryForFood made this function strictly for me, but I had to revert old lua code because this issue.

**Comment by LoneGazebo** [comment]
Don't believe so, no.
