### ISSUE TITLE
Issues with the RoughAttack and RoughRangedAttackMod flags

### ISSUE THREAD

**Issue by monkeystick** [LoneGazebo/Community-Patch-DLL#8157]
_1. Mod version (i.e Date - 4/14):_
7-1-3

_2. Mod list (if using Vox Populi only, leave blank):_
(overhaul) More Wonders for VP v11
Ingame Editor (v 39)

_3. Error description:_ 
The two flags behave strangely and cause disparities between the bonuses stated in the combat preview and the final calculated attack strength of a unit. These bonuses are used by the "Imperial Army" promotion from the More Wonders mod.
		  
a) RoughAttack and RoughRangedAttackMod don't work in the same way because they alter final attack strength under different circumstances. RoughAttack works when the enemy is in rough terrain and RoughRangedAttackMod works when you are in rough terrain. Is this behavior intended? 
b) When they appear in the combat preview, RoughAttack and RoughRangedAttackMod do so simultaneously for both melee and ranged units even though no more than one of them is ever involved in the calculation for final attack strength. 
c) RoughRangedAttackMod appears in the combat preview for ranged units only when the enemy is in rough terrain but actually alters final attack strength only when your unit is in rough terrain.

Is it possible and would it be useful to make RoughAttack affect both melee and ranged units (but for ranged affect RCS instead of regular strength) and discard RoughRangedAttackMod?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6857494/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Gustavus Adolphus_0002 BC-3920.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6857510/Gustavus.Adolphus_0002.BC-3920.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
Issue b)
![issueB1](https://user-images.githubusercontent.com/35145298/126527883-2633de9e-1128-42f0-9054-1c03a0bce163.png)
![issueB2](https://user-images.githubusercontent.com/35145298/126527890-995e0dcc-4bff-4c57-93f0-cce81de71433.png)

Issue c)
![issueC1](https://user-images.githubusercontent.com/35145298/126527905-8410e1f6-60ce-4a0e-a0f6-9d44c432ba68.png)
![issueC2](https://user-images.githubusercontent.com/35145298/126527913-e60d2e70-1aed-493f-a427-4d69f908924b.png)

**Comment by LoneGazebo** [comment]
The ranged rough attack discrepancy sounds like a bug

**Comment by adaneslavo** [comment]
There are also issues with Flanking parameter in the unit combat UI. It shows some odd percentages which after calculation are not taken into account. Sometimes it shows 50% bonus, but uses only part of it etc. I can't tell you if the calculations are correct or the UI. It's easy to reproduce.

**Comment by RecursiveVision** [comment]
EnemyUnitPanel still busted...I'll fix eventually

**Comment by adaneslavo** [comment]
Fixed?

**Comment by LoneGazebo** [comment]
I fixed the DLL issue with ranged being based on your location, not enemy.

**Comment by RecursiveVision** [comment]
@adaneslavo I believe so? Gazebo changed the code for it.

As for the display issue, I still need to fix that. The display code is broken in general, but there's already an issue open for that.
