### ISSUE TITLE
Mother Land Calls Music and Voice

### ISSUE THREAD

**Issue by inkyant** [LoneGazebo/Community-Patch-DLL#8158]
[Motherland Calls has, in the base game files, a quote and music.](https://tcrf.net/Sid_Meier%27s_Civilization_V_(Windows)#Unused_Wonder)
This should be used, currently there is no quote or music for Motherland calls so changing it to this would be very nice.

**Comment by adaneslavo** [comment]
There are lots of other missing quote sounds for World Wonders. We are working on this with @pineappledan in More Wonders mod. Motherland Calls will be available in next update.

**Comment by inkyant** [comment]
For the more Wonders mod? It is a great mod, but this can also be added to base VP I think.
Also, that website I linked has a couple more quotes that could be used. And the corporations tech has no quote. 
Maybe the agriculture quote can be switched with the Fertilizer quote, and then we would have the quote "the nation that destroys it's soil destroys itself". This could be used for military stuff and other things.

**Comment by inkyant** [comment]
#8250
