### ISSUE TITLE
Building production cost

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#8160]
Lately during my works with More Wonders mod and compatiblity with Enlightment Era mod I noticed small chaos in production cost for buildings. Quick table for an overview and rest of coments below:
![obraz](https://user-images.githubusercontent.com/33016300/126724631-03b39eb0-c58e-4c57-884d-8c47b48327d5.png)
Ignore 3 last columns, because they are for EE use only.
- production cost for normal building does not follow any pattern (linear, expotential, anything);
- same for World Wonders; there are multiple holes, some ridiculous values;
- for later eras value for World Wonders is lower (a lot) than for standard building; I'm aware that there are % modificators for WW cost, but even though it seems uneven;
- some buildings like Seaport have very high cost comparing to others;
- in the same tier there can be buildings with values that vary from 1000 to 1500;
- Solar Power Plant has lower value than other Power Plants;
- Atomic era tiers for regular buildings have same values, where other eras have them set rising slowly;
- jump from Renaissance to Industrial for regular buildings is very high;
- jump from 1st tier of Information era to 2nd tier for WWs is very high;

I can modmod and clean values for World Wonders in my modmod, but doing the same for regular buildings is too much for me and I don't know if it was intended.

I noticed similar mess with policy requirements for World Wonders, but topic was closed. Maybe here there's no issue, but for me it looks like no one has treated this part with care for a long time.

**Comment by LoneGazebo** [comment]
these variables are intended, not a mess. Production cost is a balance factor.
