### ISSUE TITLE
Issues with final strength and flanking bonus displayed for long attack commands

### ISSUE THREAD

**Issue by monkeystick** [LoneGazebo/Community-Patch-DLL#8161]
_1. Mod version (i.e Date - 4/14):_
7-1-3

_2. Mod list (if using Vox Populi only, leave blank):_
Ingame Editor (v 39)

_3. Error description:_ 
Issues:
a) the final attack strength is accurate, but the stated flanking bonus is wrong 
b) the flanking bonus is correctly stated, but the final attack strength is wrong 
c) both the final attack strength and flanking bonus are wrong
d) a weird, potentially unrelated problem where both final attack strength and flanking bonus are correct, but there is an "attacking over river" penalty stated unnecessarily.

I found that these issues affect both land and naval units, but since they seem to occur in the same fashion I only included screenshots for land units.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6867038/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Gustavus Adolphus_0001 BC-3960.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6867042/Gustavus.Adolphus_0001.BC-3960.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
issue a)
Flanking bonus should be stated as 40% instead of 50%
![issueA1](https://user-images.githubusercontent.com/35145298/126747709-6a34b092-1f01-44a3-81cb-9c6c2a88dd1c.png)
Flanking bonus should be stated as 40% instead of 30%
![issueA2](https://user-images.githubusercontent.com/35145298/126747859-1fcd2219-6a52-47ad-bc8f-1909e7966547.png)

issue b)
Final strength should be 130
![issueB1](https://user-images.githubusercontent.com/35145298/126748007-8a546d9b-a6da-4846-ad1b-5848718aa74d.png)

issue c)
Flanking bonus should be 20% and final strength should be 140
![issueC1](https://user-images.githubusercontent.com/35145298/126748120-61707e31-1f70-42e0-99f8-1348ea71d9b7.png)
Final strength should be 120 and the enemy should have a 10% flanking bonus
![issueC2](https://user-images.githubusercontent.com/35145298/126748339-8f603d10-b87c-4575-b955-5284fe1b20af.png)

issue d)
There shouldn't be an "attacking over river" penalty
![issueD](https://user-images.githubusercontent.com/35145298/126748719-d077f2c6-6f62-4c49-ae2d-362523562461.png)

**Comment by RecursiveVision** [comment]
EnemyUnitPanel is still busted...will fix eventually. (x2)
