### ISSUE TITLE
Imported resource not being imported

### ISSUE THREAD

**Issue by Neborya** [LoneGazebo/Community-Patch-DLL#8167]
_1. Mod version (i.e Date - 4/14):_
7-1-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Gandhi gifted me some copper, but it did not become imported (not shown in the Resources Imported list, and available for trading from other players).

![изображение](https://user-images.githubusercontent.com/27854329/127405115-f5b7e502-1a8e-4da4-83ed-3c4df827f648.png)

_4. Steps to reproduce (optional):_
Is [savegame](https://github.com/LoneGazebo/Community-Patch-DLL/files/6896840/Pedro.zip) enough? I don't have logs enabled, but can try to get an earlier save 1 turn before Gandhi offers his copper (although i'm not sure accepting it will trigger the bug again).

**Comment by azum4roll** [comment]
I have a feeling it's related to the "trade cache", and thus does not persist through saves. See also #7992

**Comment by DeAnnoCiv** [comment]
And when everyone's the Netherlands... no one will be.

**Comment by HeinzWGuderian** [comment]
I have this issue too and it persists through saves. Also when I trade away a lux and then get it back sometimes it doesnt register as if I have the resource in my trade network, such as completing quests etc.
