### ISSUE TITLE
"Stop City Razing" button doesn't work

### ISSUE THREAD

**Issue by monkeystick** [LoneGazebo/Community-Patch-DLL#8172]
_1. Mod version (i.e Date - 4/14):_
7-1-3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Upon capturing a city and choosing to raze it, the "Stop City Razing" button appears and is clickable, but it doesn't work and the city continues to be razed. This issue persists until the city is fully razed.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6935827/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Attila_0092 BC-0575.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6935830/Attila_0092.BC-0575.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by monkeystick** [comment]
Still present in 8/19. Are you referring to a future version?

**Comment by LoneGazebo** [comment]
I checked and couldn't reproduce the issue.

**Comment by monkeystick** [comment]
Just tried again, this time with naval capture and annexing the city first. Still no luck.
Checked with versions 5-28 and 6-7-5 as well, and for me it seems the issue is present around version 6-7 onwards. 5-28 was fine.

**Comment by LoneGazebo** [comment]
hmm

**Comment by monkeystick** [comment]
Well I just reinstalled 8-19, decided to test again, and for whatever reason didn't encounter the issue this time.

**Comment by LoneGazebo** [comment]
yay
