### ISSUE TITLE
[7-1-3] Game gets super buggy after Indonesia offers me a tech gift

### ISSUE THREAD

**Issue by Sphener** [LoneGazebo/Community-Patch-DLL#8173]
_1. Mod version (i.e Date - 4/14):_ 7-1-3 (with EUI)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ So after I click end turn on turn 267, AI Indonesia (my friend) offers me a tech gift on their turn. However, if I accept this gift, the dialog box disappears and I am stuck on Indonesia's leader screen with no interface. If I click escape here it takes me back to the game, but the interface becomes clunky, the leader icons disappear, and the graphics become glitchy. If I save after this, the save file is corrupted (only 16kb, crashes on trying to load). None of these issues come if I just reject his gift.

_4. Steps to reproduce (optional):_ Open the attached save and click next turn, then accept Gajah Madah's gift.

---------------------------
Supporting information:
Zip contains screenshots and savegame.
[Suleiman_0267 AD-1785.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6938486/Suleiman_0267.AD-1785.zip)

**Comment by Mcantona** [comment]
I think this is the same issue as somebody else and I reported also here: #8055
