### ISSUE TITLE
previously working LUA broken in newest version

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#8179]
_1. Mod version (i.e Date - 4/14):_ 07-01

_2. Mod list (if using Vox Populi only, leave blank):_ CL Inuits for VP mod

_3. Error description:_ Something has changed with the newest version of VP that is breaking lua that grabs the cityID of a city. Using the city ID to assign tile ownership renders the city into a nil value

_4. Steps to reproduce (optional):_ build an inuksuk unique improvement on the outer border of a city you own

---------------------------
Supporting information:
1. Lua log error description:
Runtime Error: [...]\(6a) Community Balance Overhaul - Compatibility Files 
(EUI)\LUA\CityView.lua:1562: attempt to index local 'workingCity' (a nil value)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/6951239/Lua.log)

2. relevant snippets of lua code
```
local eCivilizationInuit = GameInfoTypes.CIVILIZATION_CLINUIT

function GetDemSEALS(iX, iY, iOwner, iOldImprovement, iNewImprovement, bPillaged)
    local pPlayer = Players[iOwner]
    local pPlot = Map.GetPlot(iX, iY)
    if iNewImprovement == GameInfoTypes.IMPROVEMENT_INUKSUK then
        pPlot:SetOwner(iOwner)
        for eDirection2 = 0, DirectionTypes.NUM_DIRECTION_TYPES - 1, 1 do
            local pAdjacentPlot2 = Map.PlotDirection(pPlot:GetX(), pPlot:GetY(), eDirection2)    
            if    pAdjacentPlot2:GetOwner() == -1 then
                local pNearestCity = GetNearestCity(iX, iY)
                pAdjacentPlot2:SetOwner(iOwner, pNearestCity:GetID(), 1, 1)
            end
        end
    end
end
    
function GetNearestCity(iX, iY)
    local iDistance = 10000
    local pNearestCity = nil
    local pPlot = Map.GetPlot(iX, iY)
    local pPlayer = Players[pPlot:GetOwner()]
    for pCity in pPlayer:Cities() do
        local iDistanceToCity = Map.PlotDistance(pCity:GetX(), pCity:GetY(), pPlot:GetX(), pPlot:GetY())
        if(iDistanceToCity < iDistance) then
            iDistance = iDistanceToCity
            pNearestCity = pCity
        end
    end
    return pNearestCity
end

function PositionCalculator(i1, i2)
    return HexToWorld(ToHexFromGrid(Vector2(i1, i2)))
end

if Game.IsCivEverActive(eCivilizationInuit) then
    GameEvents.TileImprovementChanged.Add(GetDemSEALS)
end
```

3. Screenshots (optional):
pictures can be found at this link:
https://forums.civfanatics.com/threads/colonialist-legacies%E2%80%99-inuit-for-vp.644564/page-9#post-16136297

**Comment by pineappledan** [comment]
I should also add I tried testing this with improved city view and an identical error occurs but from that mod instead of EUI.

**Comment by pineappledan** [comment]
Just tested another custom civ that claims tiles and assigns them to the capital. 
No issues with that. So it might be some issue with GameEvents.TileImprovementChanged

**Comment by inkyant** [comment]
```
local workingCity = plot:GetWorkingCity()
-- worked by another one of our Cities
if workingCity:IsWorkingPlot( plot ) then
```
Here's the code with the error.
The issue is that the city exists, yes, but it's because plot:GetWorkingCity() isn't returning anything.
So, the plot doesn't have a working city.
In your code:
`pPlot:SetOwner(iOwner)`
You aren't setting the working city, like you do here:
` pAdjacentPlot2:SetOwner(iOwner, pNearestCity:GetID(), 1, 1)`
(also you technically don't need the ones because by default it's true for the last two params)
Though probably the function should automatically give it to the nearest city if not specified.

**Comment by pineappledan** [comment]
commenting that out worked
