### ISSUE TITLE
Spy mission produced no result.

### ISSUE THREAD

**Issue by alanmary01** [LoneGazebo/Community-Patch-DLL#8180]
_1. latest 7.1.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Playing as England (which has an initiial free spy). I sent the spy to do the easiest possible task on the first AI civ I met. (rob some gold). The mission was reported as successful and the spy was promoted, but no gold was actually received.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by duwy99** [comment]
I have the same problem. None of the spy missions seem to work.

**Comment by ThyraDannebod** [comment]
Happens quite often, actually. Mostly on capitals, for some reason
