### ISSUE TITLE
I open the victory process and the game will flash back

### ISSUE THREAD

**Issue by herobbk** [LoneGazebo/Community-Patch-DLL#8183]
_1. Mod version (i.e Date - 4/14):_
12-1-3

_2. Mod list (if using Vox Populi only, leave blank):_
![FAS$( O`XH%O2GW~H~6U @V](https://user-images.githubusercontent.com/31226544/129313825-4bae1689-c646-4143-881b-5ec90c3e171d.png)

_3. Error description:_ 
Open the victory process in the upper right corner and the game will flash back
![Inked4Y}J6 J71$77@5C9} }DH~S_LI](https://user-images.githubusercontent.com/31226544/129313968-f8e8a344-54cc-4d0a-91de-95a3195aa7fd.jpg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1.[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6980315/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Exolt Thraxus_0000西元前-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6980325/Exolt.Thraxus_0000.-4000.zip)

3. [CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6980333/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
can't deal with that many extra mods
