### ISSUE TITLE
8-12 New Freedom branch bugs

### ISSUE THREAD

**Issue by smalIson** [LoneGazebo/Community-Patch-DLL#8184]
_1. Mod version (i.e Date - 4/14):_
8/12

_2. Mod list (if using Vox Populi only, leave blank):_
Ingame editor

_3. Error description:_ 

Wanted to see new changes to Freedom branch, so went ingame to check and noticed Universal Healthcare tooltip did not say anything about providing hospitals, so i checked it and saw it wasnt working properly. So i started checking all the other tenets. 
Freedom branch is completely broken. I think Order and autocracy are working as intended form my limited testing, although i didn't spend much time on them.
these are my found errors so far (definitely not an exhaustive list i only had time to spend an hour on this):
- Avant Garde only provides +25% GPP instead of listed 33%. Culture needs modifier working.
- Creative Expression appears to provide no bonuses at all.
- Civil Society appears to reduce food cost of specialists by 50% not 2, 7 -> 3.5 in Atomic era, 8 -> 4 in informational era. not applying +4 food to farms, camps, plantations or UI.
- Draft registration purchased units still have half XP, units units spawned when taking tenet have full XP. I wasn't even aware it spawned units, as tooltip says nothing about this.
- Economic Union does not provide +2 trade routes, and +6 gold to freedom civs appears to be only +3.
- Universal Healthcare in not providing free hospitals, instead tooltip says gives +1 happiness for every NW. (this does appear to function).
- Covert Action not providing +1 spies per game size, coup chance doubling appears to work.
- Capitalism, specialist are not providing +1 gold, happiness from specialists not working either, although weirdly i do receive happiness when i take the tenet, but this appears to come from banks, stock exchange and customs houses?
- Their Finest Hour is not providing +1 air capacity. otherwise working as intended.
- New Deal only provides +4 of yields instead of +6 and no tourism.
- Universal Suffrage appears not to work at all.
- Arsenal of Democracy provides military production bonus, but influence from gifting is tripled not +40 like in tooltip. Influence does not increase when expending GP.
- Media Culture tourism bonuses working, but no happiness and culture bonuses.
- Treaty organization is not providing delegates, but +influence per turn appears to work.
- Space Procurements allows investing in rocket parts but nothing else about this tenet works.
- Transnationalism didnt have time to test increase in spawn chance of franchise per turn, but towns counting as franchises and +2 culture bonus and franchise cap increase all seem to work.
- Did not have time to test self determination unfortunately.

Also some buildings maintenance costs appear to be capped at 4 i think? e.g. i sold a military base and gain 4gpt, then built again and lost 4, this was similar with other 10 cost building although i did not test many. i just wanted to make this post about freedom branch mostly. 

save
[8-12 freedom testing.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6980630/8-12.freedom.testing.zip)
logs
[Logs 8 12 freedom testing.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6980631/Logs.8.12.freedom.testing.zip)

**Comment by RecursiveVision** [comment]
`New Deal only provides +4 of yields instead of +6 and no tourism.`

This is a merge error and has been fixed. The rest are @InkAxis's demesne.

**Comment by inkyant** [comment]
#8185 
Seems I missed merging just this line and that broke the SQL.
Hopefully that fixes it
