### ISSUE TITLE
8/12 Crash on turn 425

### ISSUE THREAD

**Issue by duwy99** [LoneGazebo/Community-Patch-DLL#8187]
_1. Mod version (i.e Date - 8/12):_
8/12 beta (hotfix 2 installed midgame, started on hotfix 1)

_2. Mod list (if using Vox Populi only, leave blank):_
Wonders Expanded (v 2)
More Unique Components for VP (v 71)
Unique City-States (v 6)
World Congress Reformation (v 8)

_3. Error description:_ 
Game always crashes on turn 425, when unmet player 3's turn is on.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6986696/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Maria I_0215 BC-1350.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6986698/Maria.I_0215.BC-1350.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/6986699/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Loaded it with no crash.

**Comment by duwy99** [comment]
Thanks for looking into it. I don't have an idea what's wrong on my end then.

**Comment by CyberPhy** [comment]
> Thanks for looking into it. I don't have an idea what's wrong on my end then.

Have you tried clearing the game cache?

**Comment by duwy99** [comment]
> > Thanks for looking into it. I don't have an idea what's wrong on my end then.
> 
> Have you tried clearing the game cache?

Yes, it didn't work unfortunately.
