### ISSUE TITLE
Coups

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#819]
By StrangleKhan:
"Coups really need a timer in between uses. Carthage and I have been flipping Hanoi every single turn for something like 20 turns straight now. "

**Comment by LoneGazebo** [comment]
Fixed. There will be a 20 turn cooldown if a coup is attempted on a CS.

**Comment by Radost** [comment]
Sure it will be fun to remember which CSes have this cooldown on a 41 CS map.

**Comment by LoneGazebo** [comment]
There'll be a tooltip, bro.
