### ISSUE TITLE
8-12 (Hotfix 4) - Laborer with default governor

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#8190]
It seems the governor still create laborers in the 8-12 version :
![20210817174812_1](https://user-images.githubusercontent.com/64471766/129758887-22fbd098-f4ee-4624-8009-35e0c0733674.jpg)

I suspect it has to do with the tile with a bison that I manually transfered to another city. Apparently it does not want to reassign the laborer to another tile.

**Comment by ThyraDannebod** [comment]
With you m8, I play with the newest VP patch (goddamnit stop releasing new hotfixes!!!!), and the governor keeps giving me laborers.
When I capture a city this also happens, and I must press on the labo-slaves in order to free them (make them work land tiles)

**Comment by Zuizgond** [comment]
Nevermind, I just forgot to reset tiles after the transfer...
