### ISSUE TITLE
Vassal AI removes most player built roads.

### ISSUE THREAD

**Issue by Laz0rG** [LoneGazebo/Community-Patch-DLL#8192]
_1. 5/24, 2021

_2. Mod list (if using Vox Populi only, leave blank):_
more unique components (v.71)
infoaddict
IGE
Music Changer
Multiple map scripts
Really Advanced Setup
Level promotions 
unique city states (v.6)
wonder race (v.7)
world congress reformation (v.8)
trade opportunities ui (v.8)

_3. Error description:_ 
Whenever you build any roads on vassal territory they will often send workers to remove them immediately, although they seem to prioritize improvements if there are any to be made. This has been an issue for a long while now so I doubt it is version specific.

_4. Steps to reproduce (optional):_
1. build roads in a vassal's territory that aren't the bare minimum for city connections or citadel/forts
2. observe them sending workers to remove them

**Comment by RecursiveVision** [comment]
@ilteroi I thought you fixed this?
