### ISSUE TITLE
8/12 - 6 AI Settler build Rate is insane

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#8194]
_1. Mod version (i.e Date - 8/12):_
8/12 - 6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
After the 8/5 or 8/12 hotfix the rate at which the AI is building settlers and founding cities is insane. I am not sure how the AI is getting so much production to buildout settlers this fast but I believe this needs to be looked into. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ThyraDannebod** [comment]
If they're getting settlers by turn 30, that's been in there for like 3 months already. The A.I are starting to be more and more competitive now...

**Comment by R3P0FFXI** [comment]
> If they're getting settlers by turn 30, that's been in there for like 3 months already. The A.I are starting to be more and more competitive now...

They are getting 5-6 cities by turn 100 in some cases on level 4.

**Comment by ThyraDannebod** [comment]
> > If they're getting settlers by turn 30, that's been in there for like 3 months already. The A.I are starting to be more and more competitive now...
> 
> They are getting 5-6 cities by turn 100 in some cases on level 4.

By turn 100 on difficulty 5 pretty much every A.I has 4-6 cities, so I think this is intended.

**Comment by NewFellow** [comment]
We've in the past had discussions on 'slow' settling speeds. The AI then was pretty careless and didn't expand it's empire even if there were alot of land available.

> After the 8/5 or 8/12 hotfix the rate at which the AI is building settlers and founding cities is insane. I am not sure how the AI is getting so much production to buildout settlers this fast but I believe this needs to be looked into.
>

I don't want this issue to be 'looked into', as you write. If the AI at last is 'competitive' this is a very good thing!

**Comment by NewFellow** [comment]
I hope nothing radical has been changed here, since in my past 10 games the AI hasn't outperformed me in any way when it comes to settling cities. I 9/10 times get the land I want, and my expansion phase is pretty much unhindered by my neighbours (of course complaining about me expanding into them) Nothing crazy at all has been going on and it just feels perfectly 'in sync' as it is. In my latest game at turn 100 my neighbours have, 3, 4, 5, 5, 5 and I have 4 cities and 2 settlers on the way...

**Comment by R3P0FFXI** [comment]
@NewFellow Noone is suggesting making any changes if it is working as intended. Simply asking @LoneGazebo and crew to verify that this is working as intended is all that was being asked. I do agree a more competitive AI is a good thing. But you should want the AI to be more human like not just building cities to build. I am pretty sure you have an order to build before you make a settler, the AI should as well.
