### ISSUE TITLE
Specialist yield tooltips + Mastery belief

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#820]
Here goes an interface issue.

Originally submitted by Kolaris. Specialist yield tooltip doesn't show the additional yields from Mastery.

**Comment by phantommaxwell** [comment]
In the Civpedia, Mastery still says it gives +1 to Yields
![2015-11-23_00152](https://cloud.githubusercontent.com/assets/11430209/11410717/94f2ec60-9397-11e5-875c-497bae2465e6.jpg)

**Comment by LoneGazebo** [comment]
I assume this (the first issue) is in no-EUI?

G

**Comment by Edaka** [comment]
@phantommaxwell I believe the wikipedia issue has been fixed in the 11/20 hotfix.
@LoneGazebo This is what Kolaris responded with: "No EUI. Science, Production, and Gold seem to be working fine. Only Culture has an issue." 
So yeah, no EUI. Also, apparently my title is inaccurate.

**Comment by phantommaxwell** [comment]
![2015-11-23_00185](https://cloud.githubusercontent.com/assets/11430209/11414859/cf537c4a-93c8-11e5-86a0-5799f312da8d.jpg)

This one remained unchanged in 11-20, note:  Mastery

**Comment by LoneGazebo** [comment]
Yeah, all of that did not refresh for some reason. It's fixed in next version.
