### ISSUE TITLE
Missing Ethiopian Event Text

### ISSUE THREAD

**Issue by jdoug312** [LoneGazebo/Community-Patch-DLL#8202]
_1. Mod version (i.e Date - 8/12):_
9/19

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP
Enhanced Naval Warefare
Enhanced Air Warfare

_3. Error description:_ 
Event "A Featherweight Heart" has 6 chooseable options. Option 3 is missing it's flavor text, but still has its effect

_4. Steps to reproduce (optional):_
Play as Ethiopia in the atomic era

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ThyraDannebod** [comment]
You're using a 2 year old version, that could be the problem

**Comment by jdoug312** [comment]
> You're using a 2 year old version, that could be the problem

Where can I find the updated version?

**Comment by R3P0FFXI** [comment]
> > You're using a 2 year old version, that could be the problem
> 
> Where can I find the updated version? (v. 5) was the version included in the 8/19 patch, and all of the ones as far back as I can remember

clear your cache and reload the mod

**Comment by jdoug312** [comment]
> > > You're using a 2 year old version, that could be the problem
> > 
> > 
> > Where can I find the updated version? (v. 5) was the version included in the 8/19 patch, and all of the ones as far back as I can remember
> 
> clear your cache and reload the mod

I do that with each new version of VP I download though

**Comment by LoneGazebo** [comment]
this is a modmod under discussion.
