### ISSUE TITLE
ExtraMove in UnitPromotions_Terrains

### ISSUE THREAD

**Issue by monkeystick** [LoneGazebo/Community-Patch-DLL#8206]
_1. Mod version (i.e Date - 8/12):_
8-19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Setting ExtraMove to -1 does not grant one additional movement point in the specified terrain type. Is this intended?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
-1 is filtered out in the vanilla DLL. I'm not sure why but likely it results in UI problems?

**Comment by adaneslavo** [comment]
So, maybe is there any way to fasten up the unit on particular Terrain tiles?

**Comment by LoneGazebo** [comment]
I closed it because it's not a solvable issue, the DLL function is vanilla and it appears to have been written as-is for a reason.
G
