### ISSUE TITLE
Capturing a city yields trigger incorrectly

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#8208]
patch: 8-19

Yields which trigger upon city capture (imperium/hero worship etc) trigger every time if you conquer the same city multiple times. It used to be limited to once per city. This seems incorrect as it's quite abusable.

Also you now don't get yields for reconquering a city you originally settled. You used to be able to get a trigger for these once as well. This one is debatable whether you should or shouldn't get the bonus.

**Comment by LoneGazebo** [comment]
The code hasn't changed.

**Comment by RecursiveVision** [comment]
@LoneGazebo I did remove the EverOwned value and instead made it use the GetNumTimesOwned() value - since two memory values accomplishing the same thing was stupid. Might have created an inadvertent error.

**Comment by LoneGazebo** [comment]
aha
