### ISSUE TITLE
War weariness unhappiness 

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#821]
Ilteroi is probably already working on it, but just in case.: some users have reported a sudden appearance of large unhappiness right after selecting an ideology, whereas it should be gradual. The war weariness unhappiness also seems to disappear just as suddenly in one turn.

**Comment by LoneGazebo** [comment]
Yeah, ilteroi has fixed.

**Comment by ilteroi** [comment]
well, part of it. the instant appearance should be gone, but the instant disappearance is still a mystery
