### ISSUE TITLE
Tourism modifier for Empire Size Difference needs attention

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#8210]
_1. Mod version (i.e Date - 8/12):_
version 7-1-3 with 8-12 Beta Patch

_2. Mod list (if using Vox Populi only, leave blank):_
VP 1-7(b)
Enhanced Naval Warfare for VP
Pontoon Bridges for VP

_3. Error description:_ 
As I have the largest civ on the planet, my tourism modifier for Empire Size Difference is negative for every opposing civ. For the smallest competitors, my tourism modifier exceeds -100%. 

![Tourism Modifier](https://user-images.githubusercontent.com/44197707/130557827-6c05363c-ca71-4625-ae11-0cde2b4feb48.jpg)

Something about this just looks very wrong. Is my empire's tourism with Greece, for instance, being penalized by having more Hotels, Zoos, etc.?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
Sounds like the minimum/maximum penalty boundaries aren’t triggering
