### ISSUE TITLE
Future Tech triggers ISS twice?

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#8211]
_1. Mod version (i.e Date - 8/12):_
version 7-1-3 with 8-12 Beta Patch

_2. Mod list (if using Vox Populi only, leave blank):_
VP 1-7(b)
Enhanced Naval Warfare for VP
Pontoon Bridges for VP

_3. Error description:_ 
Having built the ISS, on founding a new Tech, my capital city sees a +1400 hammer benefit. On founding a Future Tech, my capital city sees a +1400 hammer benefit TWICE. Is this an undocumented feature?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
it's a consequence of the future tech triggering the 'end of era' element. I'm just going to halve its value.
