### ISSUE TITLE
AI declaring war with denunciation message.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#8214]
8/19 version.

![image](https://user-images.githubusercontent.com/22875626/131235347-06c66494-4c32-4931-b311-08d83a3b643b.png)

We were not already at war. This is literally the message I got when he declared.

**Comment by RecursiveVision** [comment]
yeah I'm looking into it

**Comment by RecursiveVision** [comment]
The underlying bug causing this is too complicated to fix right now but this will fix it for now
