### ISSUE TITLE
Voluntary vassalage too often for high score Civs

### ISSUE THREAD

**Issue by JingWeiChen2019** [LoneGazebo/Community-Patch-DLL#8220]
_1. Mod version (i.e Date - 8/19):_
8/19

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
High score civs tend to get vassalage without any wars or boarder contact. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
[civvoxissue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7080430/civvoxissue.zip)

**Comment by RecursiveVision** [comment]
I'll need a savegame to debug.

**Comment by JingWeiChen2019** [comment]
> I'll need a savegame to debug.

Added 2 savegame (Enrico Dandolo_0283 AD-1826.Civ5Save & Enrico Dandolo_0212 AD-1510.Civ5Save) in the uploaded .zip file

**Comment by RecursiveVision** [comment]
@JingWeiChen2019 I need a savegame 1 turn before the AI agrees to become a vassal.

**Comment by JingWeiChen2019** [comment]
@RecursiveVision  

1 turn before vassalage
[VoxCivVassalage.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7102621/VoxCivVassalage.zip)


> @JingWeiChen2019 I need a savegame 1 turn before the AI agrees to become a vassal. Saves after it occurred can't be used.

**Comment by RecursiveVision** [comment]
Found the bug! A value was not being multiplied by 100 before dividing, so Portugal thought they had 1% of The Iroquois's techs.
