### ISSUE TITLE
Game stuck in infinite loop within AI civs friendship dialog.

### ISSUE THREAD

**Issue by alanmary01** [LoneGazebo/Community-Patch-DLL#8221]
_1. Mod version (i.e Date - 8/19):_8/19 (latest)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Sometimes when an AI civ offers friendship, it is impossible to exit the dialog. Whether or not the offer is accepted, the game remains stuck asking if you will accept the offer. This bug is not related to the current version, I've seen it in earlier ones. There does not seem to be any particular circumstance which triggers it. The only way out is to use task manager to crash the game and then restore from an autosave. Having done that and then awaiting the same offer (which generally does happen), the bug may or may not reoccur, it seems about 50/50 if it does or it doesn't.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Need logs/savegame.

**Comment by alanmary01** [comment]
I had not so far enabled the logging, but will now do so for possible future issues. However here is the most recent save file before the bug occurred. (I'm playing as Rome and have got into a bit of a mess due to a city having revolted, but I don't think that is relevant to the bug). In the net few turns Arabia should offer friendship, and the bug might occur (Or maybe not).
[AutoSave_0110 BC-0125.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7086676/AutoSave_0110.BC-0125.zip)

**Comment by alanmary01** [comment]
Something I forgot to mention. There are a couple of other mods used in this game, however this bug has occurred previously and on those occasions it was just plain vox pop and nothing else. These mods are from pineapple dan.
1. voxpop modmods.
2. additional buildings and units.

**Comment by RecursiveVision** [comment]
@alanmary01 Could you list the name (and version number, if any) of the mods you're using? I can't load the save otherwise.

**Comment by RecursiveVision** [comment]
Even without logging properly enabled, the lua log is usually written IIRC.

**Comment by alanmary01** [comment]
Fortunately, since I've only started using these recently I still have
those in my download folder. so I've attached them to this email.
In addition, I tried myself resuming the game from the save file I gave
you, and this time the bug did not repeat, Arabia accepted my response.
As you will see, Rome is pretty much a lost cause anyway at this point so I
will not be pursuing that game, but the bug is weird in that it may or may
not occur given exactly the same starting point. In fact I think a reload
from a save usually does fix it, though that's not guaranteed. It's a rare
bug, I've seen it only about 3 times in total over 50 or so games
 (over) More Unique Components for VP (v 72).zip
<https://drive.google.com/file/d/1fFwssLA7aRD3g6bJgXH8LY3Bb9FVjQzT/view?usp=drive_web>


pdansTweaks.zip
(2,786K)
<https://mail.google.com/mail/u/0?ui=2&ik=d9c4e62cf7&attid=0.1&permmsgid=msg-a:r-6778781687813087954&view=att&disp=safe&realattid=f_kt0r05sz0>

**Comment by RecursiveVision** [comment]
Save doesn't work with v24 of pdan's tweaks, and your link for v23 doesn't work.

**Comment by alanmary01** [comment]
Hmm that's odd.
I must have done something wrong when attaching the file for the v23 pdan
tweaks mod, so here is another attempt.
Is the other mod installing OK? (the extra units and stuff).

**Comment by RecursiveVision** [comment]
What other attempt..? You haven't uploaded anything.

**Comment by alanmary01** [comment]
I checked my 'sent' email folder.and it's showing up there as having been
sent as an attachment to the email (2.7Mb Pdans Tweaks.zip).
I'm using just the standard gmail browser based email system.
I have heard though that sometimes people elect to turn off all email
attachments, or they can be turned off by default automatically by some AVs.
Could this be what has happened?
Anyway, now I have uploaded it directly to the Github thread. not as an
email attachment.
Sorry about this, I'm relatively new to how github stuff works.

**Comment by alanmary01** [comment]
[pdansTweaks.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7100946/pdansTweaks.zip)

**Comment by alanmary01** [comment]
I expect I'll have to do the same thing for the other pdan mod as well?

**Comment by RecursiveVision** [comment]
@alanmary01 The other one is fine, I downloaded it from CFC.

**Comment by alanmary01** [comment]
Oh good. As I mentioned earlier this bug did not recur for me when I reloaded from the save.
Perhaps it's not that important since it seems quite rare.
Unless there is something very obvious in the code which might cause this, it might best just to file it under freak events caused by cosmic rays or similar :)

**Comment by RecursiveVision** [comment]
I'll take a look, there's been another report of an endless loop that we're trying to solve.

**Comment by alanmary01** [comment]
That's interesting. Well good luck.
Superficially it seems as something is corrupting a loop exit condition.

**Comment by RecursiveVision** [comment]
No infinite loop, but my game crashed to desktop. I suspect the crash is what's responsible, not the DoF.

**Comment by RecursiveVision** [comment]
Can't reproduce. Open a new issue and be sure to post logs/savegame if it happens again.
