### ISSUE TITLE
Rebel spawning notification

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#823]
I haven't checked that one in a long, long while, but I remember the popup notification used to say something along these lines of: 'Rebels spawned because your unhappiness was below -10', when in fact the treshold is -20. Sorry if that's been fixed and I haven't noticed, but you don't get that notification often. (: Could you check it, please?

**Comment by LoneGazebo** [comment]
Tooltip says -20, but we'll see.

**Comment by Edaka** [comment]
I'll close this then. It was a really long time and it might as well been fixed since then - can't test to confirm it right now. Not a big deal. I'll let you know if it happens again.

**Comment by Edaka** [comment]
Managed to get it. Stayed above -20 unhappiness for a while and rebels didn't make me wait too long.

By the way, there was only two of them, which seemed like a pretty low number to me. Does it scale with era/gamespeed (I was on quick)/unhappiness amount or something?
![rebels](https://cloud.githubusercontent.com/assets/12978597/12079832/28d0ed5c-b250-11e5-969d-66f6db65a60d.jpg)

**Comment by LoneGazebo** [comment]
Fixed.

**Comment by LoneGazebo** [comment]
It uses an RNG dice roll to get the number of rebels.
