### ISSUE TITLE
Duplicate citizens being created

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#8236]
In the latest 1.0 release there is a major bug causing more citizens to work tiles than actually exist. @ilteroi 

See the early posts in this thread: https://forums.civfanatics.com/threads/new-version-1-0-september-3rd-2021.672999/

**Comment by LoneGazebo** [comment]
Definitely caused by latest merge. Look at those commits?

**Comment by LoneGazebo** [comment]
Oleole merge*

**Comment by LoneGazebo** [comment]
working on it now...
