### ISSUE TITLE
GAP generation from happiness suring GA

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#824]
Originally posted by Gidoza (sorry that I'm snatching this one from you, but it's better posted sooner than later):

"I've tested and retested GA points generated from Happiness during a GA, and happiness is definitely not generating any during a GA. "

**Comment by Gidoza** [comment]
You would of course post it 4 minutes before I came to do it.  :P

**Comment by LoneGazebo** [comment]
Looked at it, and I remember why this is so - GAP cannot be generating during a golden age because the value is not reset for overflow. This is by design of firaxis, and would be quite complex to dis-entangle. So we leave it, for now anyways.

**Comment by Gidoza** [comment]
Then how are other things (like Mausoleum of Halicarnassus) generating GAP
during a GA?

**Comment by LoneGazebo** [comment]
They aren't. Like I said, old code had it that way, then I reversed the change because of overflow concerns.

G

**Comment by Gidoza** [comment]
Ahhhhhh okay.  I take it a dummy counter during GA that refills the value
after the GA is over has already been considered, then?  If not that, I'm
out of ideas.  :P
