### ISSUE TITLE
CTD Just Before New Turn

### ISSUE THREAD

**Issue by jdoug312** [LoneGazebo/Community-Patch-DLL#8240]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0.1

_2. Mod list (if using Vox Populi only, leave blank):_
Leuigi's Israel for VP
(9a) Enhanced Air Warfare 4VP (v 1.9)
CIV-Linked Great Generals (v 11)
Colonialist Legacies' - Phillipine Republic for VP (V10)
Dolen2's Ethnic Diversity
Great Prophet Historical Names (BNW or GK) (v 31)
Improvement - Airbases (v 14)
Infixo's Enhanced Naval Warfare for Vox Populi (v 2.1)
Kushan Empire for VP (v 1)
MC and LITE's Nubia  for VP
Quick Turns (v 10)
Sukritact's Civ VI Style City Names (v 1)
The Timurids (VP)

_3. Error description:_ 
Upon clicking new turn, the game CTDs just after the city states' turn

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7110933/logs.zip)

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7110934/CvMiniDump.zip)

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7110936/QuickSave.zip)

**Comment by NewFellow** [comment]
I experienced the exact same CTD just now (crashing after city-state turn) and went here and saw your post.

I'm using the latest patch.

**Mod list (if using Vox Populi only, leave blank):**
(ui) City-States Leaders for VP (v 10)
Calypso's Colored Religion Icons (Basic) (v 1)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Improved City View (Vox Populi EUI) (v 11.0)

[CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7111365/CTD.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7111366/CvMiniDump.zip)

**Comment by NewFellow** [comment]
I reloaded the game from a save a few turns earlier. This worked initially... and gave me another few turns to play until, unfortunately, another CTD happened. This time in the middle of an AI's turn (venice placing a citadel).

**Comment by ilteroi** [comment]
also probably fixed by 19a72e4dda535aa5a88672d03df1e0b3862cbfab

**Comment by RecursiveVision** [comment]
@jdoug312 Try replacing your GameCoreDLL_Expansion2 DLL file in MODS > (1) Community Patch with this one, and see if that fixes it. Savegame compatible.

[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7124423/CvGameCore_Expansion2.zip)

**Comment by RecursiveVision** [comment]
@ilteroi This crash is not fixed by your fix

**Comment by Ledro** [comment]
Was there a solution to this CTD on/after city-states' turn?
I seem to have the same issue: https://github.com/LoneGazebo/Community-Patch-DLL/issues/8258
