### ISSUE TITLE
Reproducible Crash To Desktop

### ISSUE THREAD

**Issue by rongute** [LoneGazebo/Community-Patch-DLL#8241]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0.1 Full Vox Populi

_2. Mod list (if using Vox Populi only, leave blank):_
No other mods used

_3. Error description:_ 
Crash to desktop after I press end turn. 

Apologies if this is duplicating other report. Not sure if same CTD or not. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs5Sept21.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7111728/Logs5Sept21.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Save before CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7111731/Save.before.CTD.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7111737/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by rongute** [comment]
Crash to desktop seemed to be after "Player 3", rather than during City State Turn so likely to be different cause to other reported CTD.

**Comment by NewFellow** [comment]
Yeah I experienced this 'crash' too, after managing to get past the initial CTD (during city-state turn) through reloading an earlier save. This procedure got me but an extra few turns until I experienced what you seem to have experienced: An CTD in the middle of an AI turn.

**Comment by ilteroi** [comment]
might be fixed in 19a72e4dda535aa5a88672d03df1e0b3862cbfab

**Comment by rongute** [comment]
> 
> 
> might be fixed in [19a72e4](https://github.com/LoneGazebo/Community-Patch-DLL/commit/19a72e4dda535aa5a88672d03df1e0b3862cbfab)

Is there a way for me to test?

**Comment by NewFellow** [comment]
> > might be fixed in [19a72e4](https://github.com/LoneGazebo/Community-Patch-DLL/commit/19a72e4dda535aa5a88672d03df1e0b3862cbfab)
> 
> Is there a way for me to test?

Yeah, I would much appreciate that too, since I'd otherwise had to put my playing on halt until next beta (which might take a while).

**Comment by RecursiveVision** [comment]
@rongute @NewFellow Try replacing your GameCoreDLL_Expansion2 DLL file in MODS > (1) Community Patch with this one, and see if that fixes it. Savegame compatible.
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7124422/CvGameCore_Expansion2.zip)

**Comment by NewFellow** [comment]
Thanks alot, that fix worked for me!
