### ISSUE TITLE
Portuguese Naus still inflict Boarded when retreating.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#8242]
New 1.0.1 version

No damage exchanged, attacks and moves still intact, got Boarded anyway. Only mods enabled aside from main suite are QoL/UI mods, plus Pdan's Beliefs Overhaul and Permanent Pantheons.

**Comment by RecursiveVision** [comment]
@ridjack Savegame and mod list needed.

**Comment by ridjack** [comment]
This game is long gone along with the savegames. The mod list was literally the main VP suite, a handful of UI or non-gameplay-affecting mods and the two I mentioned in the original report, Beliefs Overhaul and Permanent pantheon. I was intentionally playing a game with almost no additions.

**Comment by phantommaxwell** [comment]
Just had this happen to me today.  Mod list, before, and after.
![20210917001014_1](https://user-images.githubusercontent.com/11430209/133723060-8f2d0711-17db-48d5-b235-94c5c73b39c0.jpg)
![20210917000951_1](https://user-images.githubusercontent.com/11430209/133723063-85643572-ac7d-407f-a04d-388282c2e975.jpg)
![20210917001005_1](https://user-images.githubusercontent.com/11430209/133723064-18b4d0a4-9af8-402e-875d-3585b698b3c4.jpg)

[nau.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7182567/nau.zip)

Manual save is after auto save.

**Comment by LoneGazebo** [comment]
boarded effects do not require you to damage the ship, merely to attack it.
