### ISSUE TITLE
MoreGreatDiplomats gone!

### ISSUE THREAD

**Issue by GLop4** [LoneGazebo/Community-Patch-DLL#8243]
Mod version 1.0.1

**\(3) CSD for CBP\Units\MoreGreatDiplomats.sql** (part of MoreGP)
is not in **City-State Diplomacy Mod (CSD) for Brave New World (v 27).modinfo** !
and seem to be replaced by a tiny and uncompleted **GreatDiplomats.xml** ??? (With duplicates!)

**Comment by inkyant** [comment]
#8246

**Comment by RecursiveVision** [comment]
@inkyant What about the incomplete GreatDiplomats.xml file with duplicates? Your commit doesn't address that...

**Comment by GLop4** [comment]
@RecursiveVision 
@inkyant 

Double checked, There is no duplicates between **moreGP** and **GreatDiplomats.xml**
but, EraType are missing. Consequently, Henry Kissinger will borne in the game long before it use to do :)

Also, I contest the presence of the following persons as GDiplomates:
Yoshida Shigeru
Kurt Waldheim
Violette Szabo
William Seward
T.E. Lawrence
William Howard
Lawrence Durrell
Madeleine Albright

GreatDiplomats.xml seen to have been added recently by ..?
If it can help, I can make a new **MoreGPs - Extra Great Peoples for VP - Version b3 rev 6** with the pertinent content of **GreatDiplomats.xml**

**Comment by inkyant** [comment]
Yeah, I didn't notice anything wrong with the original GreatDiplomats.xml 
It seems like it was the original file made by CSD, and the other one was just added by MoreGP but wasn't in the modinfo.
I would say because of the amount of GP a lot of the choices are questionable but I would contest them on the MoreGP CFC thread.

**Comment by GLop4** [comment]
**MoreGreatDiplomats.sql** (v3 rev5) with the content of **GreatDiplomats.xml** + **EraType** - _Kurt Waldheim_... = MoreGreatDiplomats.sql (v3 rev6)

I planned to do that with GA/GM/GW but never did it.
NewArtists.xml
NewWriters.xml
There is a GA duplicate, probably others **EraType** missing, and at least one sound quote missing (aready recorded by Hinin)

So, every 'VP GP' could be standardized in MoreGP module
