### ISSUE TITLE
Indonesia monopoly bonus disappears 

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#8244]
_1. Mod version (X.Y.Z, e.g. 1.0.0): 1.0.1

_2. Mod list (if using Vox Populi only, leave blank):_
3/4 UC v73
Promotion Flags v3
Improved City View v11

_3. Error description:_ 
I've noticed in a few games that Indonesia will inevitably lose the monopoly bonus from its new UA. It appears it may be triggered by loading a saved game after a monopoly has been acquired. 

_4. Steps to reproduce (optional):_
Load the save game, get monopoly on nutmeg (check for +15% production bonus), next turn, save, reload, monopoly bonus should now be 10%.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[AutoSave_0046 BC-2160.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7112263/AutoSave_0046.BC-2160.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by inkyant** [comment]
#8246
