### ISSUE TITLE
[1.0.1] Cannot build Stables in Annexed cities

### ISSUE THREAD

**Issue by DemaciaMaggotPie** [LoneGazebo/Community-Patch-DLL#8248]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0.1

_2. Mod list (if using Vox Populi only, leave blank):_
3/4 UC, Milae's Hotkeys, PDan's tweaks

_3. Error description:_ 
Cities that I have captured and annexed cannot build a Stable even when they have the required resources nearby.

_4. Steps to reproduce (optional):_
Annex a city, build a courthouse, research Chivalry.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/7167416/132333699-e490e204-cd73-4dfc-9f02-4d656773883e.png)

**Comment by DemaciaMaggotPie** [comment]
Update: Two out of 5 of the cities I have annexed and have a Stable resource, can now build Stable. Maybe it's because of pillaged tiles? All these cities had a functioning (unpillaged) Pasture, but some had pillaged tiles (some being non-pastures). I'll investigate further.

**Comment by Mileslewis** [comment]
I believe it has to do with the city not originally 'owning' the pasture tile.

You can't switch which city owns a tile just by switching which city works it so ownership is whichever city was owning the tile when the pasture was built.

Repairing a pillaged tile may update ownership, I'm not sure about that.

Also this was brought up before: #8152

**Comment by DemaciaMaggotPie** [comment]
Update: I have not been able to find a clear pattern of how to restore the ability to build Stables. However I have found a decent work-around: Building a Great People Improvement "resets" the tile ownerships and allowed me to build a Stable in the city nearby.
