### ISSUE TITLE
Allied CS steals my city- should it work this way?

### ISSUE THREAD

**Issue by deadstarre** [LoneGazebo/Community-Patch-DLL#825]
not %100 sure this belongs here but here goes-

Inca sneak attacked my island city with 6 corvettes i never saw coming- i mobilize my fleet to get there however he took the city in only a few turns by the skin of his teeth. Then, my allied CS who was right next door gets their fleet into action 1 turn too late, and takes the city back immediately on the next turn from him flipping it- but now it's theirs, they did not liberate it. Inca is decimated and gone. 

so where am i? i lost my city i was about to take right back, except now instead of Inca owning it my allied CS owns it- having intervened only on my behalf (for my sake supposedly, because we're allies) but just ends up opportunistically stealing my city. 

now my only recourse is to attack a city state i am deeply allied with, and which just also happens to be protected by 4 other major civs. can the AI liberate cities and if they can; in this case, should they?

**Comment by LoneGazebo** [comment]
Haha. That's wonderful. I should probably hard code minors to liberate cities of allied players.

**Comment by deadstarre** [comment]
"wonderful" was not the word i would have used at the time =) glad you got a laugh though lol thanks for the reply on this

**Comment by LoneGazebo** [comment]
At least it didn't raze your city?
G
