### ISSUE TITLE
Automatic installer places Asset files on wrong drive

### ISSUE THREAD

**Issue by valrossenOliver** [LoneGazebo/Community-Patch-DLL#8253]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0 Stable

_2. Mod list (if using Vox Populi only, leave blank):_
EUI (that comes with Vox Populi)

_3. Error description:_ 
When using the automatic installer, the Asset folder is placed on the C drive where CIV V is not installed.
I suspect it recognizes the steamapps folder on the C drive and thinks Civilization should be installed there.

**Comment by LoneGazebo** [comment]
it uses your registry. so wherever your registry says civ is located, that's where it goes.
