### ISSUE TITLE
CTD when responding to AI prompt

### ISSUE THREAD

**Issue by jdoug312** [LoneGazebo/Community-Patch-DLL#8254]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0.2

_2. Mod list (if using Vox Populi only, leave blank):_
Really advanced setup
Extra civs optimized for VP
EAW
ENW
Dolen2's Ethnic Diversity

_3. Error description:_ 
I bullied a city state under Austria's protection. When their turn came they demanded I not bully CSs. As soon as I tell them no, the game CTDs. I'll have to submit the logs later as I'm doing this from mobile

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Padre19** [comment]
Same.CTD when I press ''Discuss'' when I try to talk to AI.

**Comment by RecursiveVision** [comment]
Sounds like an LUA crash. Need lua.log.

**Comment by Padre19** [comment]
Here. 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7145298/Logs.zip)

But with many mods installed.

**Comment by Hokiefan00** [comment]
Here's my list of mods to go with the attached save game. Germany will request not settling near them. Clicking on an answer causes a CTD.

- Vox 1.0.2
- Calypso's Colored Religious Icons basic and extended
- Really Advanced Setup
[Catherine_0055 BC-2625.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7145660/Catherine_0055.BC-2625.zip)
