### ISSUE TITLE
CTD zulu ask to be friends 1.0.2

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#8255]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0.2

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) City-States Leaders for VP (v 10)
Calypso's Colored Religion Icons (Basic) (v 1)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 
pressing next turn, getting CTD on zulu asking to be friends.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7145239/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7145222/CTD.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7145230/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@NewFellow Please enable logging, see here for instructions: https://github.com/LoneGazebo/Community-Patch-DLL#to-enable-logging-for-bug-reports

**Comment by NewFellow** [comment]
But i attached logs?

**Comment by RecursiveVision** [comment]
@NewFellow You need to enable _all_ the logging settings in the instructions, reproduce the crash, and _then_ attach the logs.

**Comment by Mcantona** [comment]
Same happened to me. Also happens when opening the zulu screen and clicking the discuss button.
[crash-CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7145338/crash-CTD.zip)

**Comment by NewFellow** [comment]
@RecursiveVision Ok here it is I hope :)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7145363/Logs.zip)
