### ISSUE TITLE
[1.0.1] CTD on city-states' turn

### ISSUE THREAD

**Issue by Ledro** [LoneGazebo/Community-Patch-DLL#8258]
1. Mod version: 1.0.1

2. Mod list (I uploaded all mods I use in this zip folder):

[MODS.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7148184/MODS.zip)

    (7) Community Events (v 5)
    Civ-linked Great Generals (v 11)
    Global - 2 Units Per Fort (v 1)
    Global - 3 Units Per City (v 1)
    Global - Local Generals (v 2)
    Hex Conquer and Release (v 3)
    Improved Air Recon (v 1)
    Reforestation (v 8)
    Trade Opportunities for VP
    Units - No Mechs (v 6)
    Units - Subs Ignore Borders (v 3)
    my own mod (changes desert move cost to 1 and a few other small things)

EDIT: I also got the same issue without any additional mods enabled (see comment below).

3. Error description: CTD after current turn, on city states turn. When reloading several turns earlier it crashed after the same turn (132) as before.

EDIT: I had this problem in **several games since version 7-1**. I always got a **CTD on a fixed turn** and **always during** (or directly after) the **city-states' turn**. In each game it was a different fixed turn that I could't get past, but it always happend in classical or medieval era (between turn 75 and 230, epic game speed).
For those games I used 2 maps I created in WorldBuilder. Maybe this has something to do with it? See my comments below.

4. Steps to reproduce (optional): just end turn

---------------------------

1. Log files:

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7146406/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[K0132 BC-0700.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7146403/K0132.BC-0700.zip)

3. CvMiniDump.dmp file:

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7146405/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by Ledro** [comment]
Same result with Recursive's DLL from september 7 (cache cleared):
https://forums.civfanatics.com/threads/new-version-1-0-september-3rd-2021.672999/page-4#post-16152979

**Comment by Ledro** [comment]
I forgot to mention that I'm also using the community events mod (I thought it was part of VP). It's included now in the mod list above and in the zip file.

**Comment by Ledro** [comment]
Could the cause for this CTD be the fact that it's a custom scenario created with an earlier version of VP (12/1) installed? It's only a map and starting locations assigned to certain civs and city-states, no units/cities etc. On VP 12/1 everything worked fine.

**Comment by Ledro** [comment]
Maybe this has something to to with the SDK WorldBuilder?
Because the same CTD on a fixed turn (during city-states' turn) also happend in a newly created scenario (also just a map with starting locations assigned to certain civs and city-states). When I start a normal game (same mods, map size, speed, difficulty setting) no CTD happens.

**Comment by Ledro** [comment]
Same result without any additional mods, only VP 1.0.3. This time the CTD happend in turn 233. It's the same new map I was talking about in the last post.
Log Files:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7198747/Logs.zip)
Save game:
[Q_0233 AD-0880.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7198757/Q_0233.AD-0880.zip)
MiniDump:
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7198760/CvMiniDump.zip)

**Comment by RecursiveVision** [comment]
Please open a new issue if you encounter crashes in the latest version
