### ISSUE TITLE
"You are their greatest rival in the world congress!" with way less delegates and no votes having taken place.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#8259]
Mod version 1.0.2

![image](https://user-images.githubusercontent.com/22875626/132927834-4a8a7b2c-635a-438f-aa34-9ae9ea05c506.png)
![image](https://user-images.githubusercontent.com/22875626/132927840-ec0c469d-9216-42db-bf73-35669b0b463a.png)

**Comment by RecursiveVision** [comment]
Intended, but I'll work on this logic.

**Comment by RecursiveVision** [comment]
Instead of using league alignment, which creates feedback loops and odd situations like this, I'm going to base the opinion bonus on voting history.
