### ISSUE TITLE
Does Mastery affect GP Improvements?

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#826]
![2015-11-25_00004](https://cloud.githubusercontent.com/assets/11430209/11410659/267d928a-9397-11e5-8490-1d1f0178b0f5.jpg)

I'm getting 10 Sceince from this Academy in the Medieval

**Comment by phantommaxwell** [comment]
![2015-11-25_00005](https://cloud.githubusercontent.com/assets/11430209/11410677/5b8d80ca-9397-11e5-919b-ce42a3b83940.jpg)

 This is my Religion

**Comment by LoneGazebo** [comment]
No, it does not - academies do get yield bumps from techs, though.
G

**Comment by Edaka** [comment]
I think physics is among those techs and, judging by the fact that you're researching machinery, you probably have it researched.

**Comment by phantommaxwell** [comment]
Shouldn't I only be getting 8 Science though, Base 5 and +3 at Physics?

**Comment by Edaka** [comment]
I think it got buffed to 7 base in the last patch.

**Comment by LoneGazebo** [comment]
It did!

**Comment by phantommaxwell** [comment]
ah that's right

**Comment by phantommaxwell** [comment]
well than update it in the Civpedia

**Comment by LoneGazebo** [comment]
It is, but for some reason the civliopedia didn't refresh in the CBP's latest version. It'll be working in the next one.
G
