### ISSUE TITLE
Game crashes to Desktop at Turn 345

### ISSUE THREAD

**Issue by Mizo5119** [LoneGazebo/Community-Patch-DLL#8264]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_ VP V1.00 released in September 3rd 2021.

_2. Mod list (if using Vox Populi only, leave blank):_

![image](https://user-images.githubusercontent.com/44852924/133256567-45a8858a-d304-45e4-be3c-cb7321b69a7c.png)

Keep in mind I am not using the multiplayer mod pack. but the rest of the files are used.

_3. Error description:_ No error pop up. It is just a crash to desktop directly

_4. Steps to reproduce (optional):_

You just need to load the game and it will always crash on desktop. I tried to disable ethnic diversity mod to continue but to no avail. All of my graphics settings are set appropriate to the ethnic diversity skin pack and the game always runs fine at the start. Settings played is Epic on a standard size map.
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7161840/QuickSave.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7161861/CvMiniDump.zip)
"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mizo5119** [comment]
Let me know if you guys need anything else in that regards

**Comment by RecursiveVision** [comment]
Please open a new issue if you encounter crashes in the latest version
