### ISSUE TITLE
2 Faith related bug reports : Grand temple and Sacred calendar

### ISSUE THREAD

**Issue by TU116** [LoneGazebo/Community-Patch-DLL#8265]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0.3

_2. Mod list (if using Vox Populi only, leave blank):_
Enhanced Air Warfare 4VP (v 1.9)
Enhanced Naval Warfare for Vox Populi (v 2.1)
UI - Improved City View (Vox Populi EUI) (v 11.0) (Gazebo edition)
[mods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7164143/mods.zip)

_3. Error description:_ 
-Can build grand temple in a non-holy city capital and without having met the temple in all city requirement.
-The great person bonus from the Sacred calendar belief applies to all cities instead of being holy city only.

_4. Steps to reproduce (optional):_
Just look at my save and screencaps and ask for further info if necessary.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[End turn.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7163321/End.turn.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0014](https://user-images.githubusercontent.com/63357353/133290077-869caf07-e6e8-43a5-9b90-a908b48764e0.jpg)
![Civ5Screen0013](https://user-images.githubusercontent.com/63357353/133290120-8d059e16-62da-4ea8-9981-2e0426d0654e.jpg)
![Civ5Screen0015](https://user-images.githubusercontent.com/63357353/133290160-5c60b098-36ed-4371-8ab2-533a7718e033.jpg)
![Civ5Screen0016](https://user-images.githubusercontent.com/63357353/133290186-6e6efe8b-2689-40ff-bea5-4e8efc9d9f4b.jpg)

**Comment by azum4roll** [comment]
You can build the Grand Temple in any city that has a Temple.

**Comment by TU116** [comment]
Then the tooltip need to be changed (look at my 3rd screenshot).

**Comment by azum4roll** [comment]
Your version looks strange. 

The Grand Temple description is supposed to be:
All Temples gain +2 Faith and +1 Gold. -1 Unhappiness from Religious Unrest, and -10% Unhappiness Needs Modifier for Religious Unrest in all Cities.
The Production Cost and Population Requirements increase based on the number of Cities you own.

**Comment by TU116** [comment]
Nope, just checked, vanilla is different and this is what I get in 1.0.3. Highly doubt this is a mod conflict. Can someone confirm this ?
