### ISSUE TITLE
Cathedral of St. Basil's not giving Reformation

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#827]
I built the Wonder and I got the Social Policy, but not the Belief

![2015-11-25_00007](https://cloud.githubusercontent.com/assets/11430209/11410732/d198a7b8-9397-11e5-9410-7d3def1ec497.jpg)

Was it because I recently took a Holy City?
![2015-11-25_00006](https://cloud.githubusercontent.com/assets/11430209/11410736/d9853b30-9397-11e5-8877-2d337ff07a73.jpg)

**Comment by deadstarre** [comment]
am i understanding correctly- you didn't found a religion for the celts, just conquered greece holy city then built it?

**Comment by LoneGazebo** [comment]
Does the conquered religious holy city have a reformation?

**Comment by phantommaxwell** [comment]
No it was Enhanced though

**Comment by LoneGazebo** [comment]
Did you click next turn after building it? The reformation selection doesn't happen until the next turn.
G

**Comment by phantommaxwell** [comment]
I waited a turn before I quit

**Comment by LoneGazebo** [comment]
Odd. I can't really explain it at present. More knowledge required.

**Comment by phantommaxwell** [comment]
I reloaded the save the turn before and still only got the Policy.

**Comment by phantommaxwell** [comment]
Using 11-19 Version btw

**Comment by LoneGazebo** [comment]
That's really odd. I don't have an answer for you at present. Sorry.

**Comment by phantommaxwell** [comment]
![2015-11-25_00008](https://cloud.githubusercontent.com/assets/11430209/11414842/8b5a0fa4-93c8-11e5-9884-7856f2002948.jpg)
  Here's the Holy City

**Comment by LoneGazebo** [comment]
Ooh, I think I know! Zealtory was accidentally labeled as a reformation belief last version, so that's what caused it. You can't reform after you have a reformed belief.

G

**Comment by LoneGazebo** [comment]
So it'll be fixed next version. Meanwhile, you can do this and see if it works!

UPDATE Beliefs
SET Reformation = '0'
WHERE Type = 'BELIEF_HEATHEN_CONVERSION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

**Comment by LoneGazebo** [comment]
add that to Enhancer.sql in the Religion folder of the CBP, clear your cache, and see if it works. It may not, but it might!

**Comment by phantommaxwell** [comment]
Yes, that fixed it, ty!

**Comment by LoneGazebo** [comment]
Yay!

**Comment by oalzubbi** [comment]
I had a similar quirk with Cathedral of St. Basil. I got the reformation belief and the policy but after building it, I wasn't able to "enhance" my religion. I got a great prophet shortly afterward but the only thing he could do was build the holy site and spread the religion. Is there something I'm missing about religion enhancement?

**Comment by LoneGazebo** [comment]
Did you take Zealotry as your reformation belief? There was a missing element in Zealotry that allowed it to be both, and taking one broke the other.

G

**Comment by oalzubbi** [comment]
No I took the one that gave +20 influence to CS whenever a missionary spread there. "missionary Influence" I believe

**Comment by LoneGazebo** [comment]
Not sure. Reformations and Enhancers don't negate each other, but I'll take a look.
G

**Comment by oalzubbi** [comment]
Just to double check, what are the requirements for enhancing religion?
