### ISSUE TITLE
Right clicking to move a ranged unit onto a civilian unit from another civ asks if you're declaring war.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#8272]
So this has existed literally since the first time I played VP. I never reported it then because I was new to the mod and didn't feel comfortable making reports yet, and since then I've gotten so used to it that it hasn't occurred to me to consider reporting it. I searched the issues as best I could to make sure it wasn't already reported, and I didn't see anything. I'll be a little surprised if y'all don't know already know about this, but I figure it's worth reporting just in case.

For clarification on the actual bug:

- If I use right-click move a melee unit onto a tile occupied by a civilian unit from another major or minor civ that I am not at war with, the move completes normally and nothing else happens.
- If I do the above with a ranged or siege unit, the move does **not** complete, and instead brings up the same dialog that comes up when attempting to move into territory of another civ you don't haven open borders with. (Does this mean WAR?) I'll get a screenshot next time it pops up if needed.
- In order to successfully move a ranged/siege unit onto that tile, I have to explicitly use the 'Move Mode' button or hotkey, at which point everything behaves normally.
- IIRC, all of this is true whether on land or in the sea.

**Comment by ilteroi** [comment]
no idea what to do about this, it's a UI thing; the popup happens before the unit gets the order.
