### ISSUE TITLE
CTD when clicking next turn OR loading the game

### ISSUE THREAD

**Issue by OrbitingOcelot** [LoneGazebo/Community-Patch-DLL#8273]
_1. Mod version (X.Y.Z, e.g. 1.0.0): 1.0.1

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description:

CTD when game loading finishes before you can click continue (attached quicksave)
CTD during AI turn (happens 2-3 turns after the attacked turn 310 save game)

_4. Steps to reproduce (optional):

A1. load the quicksave
*crash when loading completes*
-- or --

B1. load turn 310
B2. play 2-3 turns
*crash during "next turn" phase*

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7178571/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[AutoSave_0310 AD-1880.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7178744/AutoSave_0310.AD-1880.zip)
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7178656/QuickSave.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7178681/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by OrbitingOcelot** [comment]
Oh hey some more info, I have also tried the DLL attached in this post, but it did not help:
https://github.com/LoneGazebo/Community-Patch-DLL/issues/8241#issuecomment-914640139

**Comment by RecursiveVision** [comment]
Please open a new issue if you encounter crashes in the latest version
