### ISSUE TITLE
Unit_BuildingClassRequireds not blocking faith purchases?

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#8275]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_ 1.0.3

_2. Mod list (if using Vox Populi only, leave blank):_ Belief Overhaul mod

_3. Error description:_ I am trying to add a unique faith purchased unit for a belief that you can only buy 25 of. I made a dummy building that is placed in a city that the unit is unlocked by via Unit_BuildingClassRequireds. The idea was that once you have 25 bought 25 of these units, that dummy building is removed via lua.

The prerequisite building is working as intended for the most part. Cities that don't have the building can't purchase the unit until they get the building. But, if I remove the building, the unit can still be purchased. It's like if I add the building to a city, it permanently unlocks the unit.

This is not how it works with Archeologists, who can be also faith purchased. If I add or remove the public school via firetuner or by selling the building, I can't build Archeologists anymore. So what is happening? Is there something about using dummy buildings that prevents this from working as intended?

**Comment by LoneGazebo** [comment]
hmm...this is tricky, as the flag is set as a bool and there's no 'reversal' code for removing said bool in the code.

**Comment by pineappledan** [comment]
Ended up using a dummy policy as a workaround
