### ISSUE TITLE
Identified spy?

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#8278]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_

1.0.3
_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

When an enemy spy succeeds, even though he has not been identified, you will find the spy's name in the notification received

**Comment by Skidizzle** [comment]
I also have this issue on 1.0.3

**Comment by LoneGazebo** [comment]
can I get a picture of the notification?

**Comment by RecursiveVision** [comment]
#8368
