### ISSUE TITLE
Incorrect text  when hovering over "Declare war on.."

### ISSUE THREAD

**Issue by ThyraDannebod** [LoneGazebo/Community-Patch-DLL#8279]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
Newest one, version 1.0

_2. Mod list (if using Vox Populi only, leave blank):_
![image](https://user-images.githubusercontent.com/89103845/134054737-e398560b-18e5-4fc1-9db7-e6d05fdfb0a6.png)
![image](https://user-images.githubusercontent.com/89103845/134054768-ad37b47c-a6fe-4886-8152-562188ab45df.png)

_3. Error description:_ 
Here in this image we can see Mr. Pachacuti say that he's friends with the Chinese, but in reality - he isn't.
![image](https://user-images.githubusercontent.com/89103845/134054858-2fee379b-929a-4fa4-b25b-17b35ad8fbd9.png)
![image](https://user-images.githubusercontent.com/89103845/134054956-656ce989-1e79-4713-924d-9f86f4d4f084.png)

_4. Steps to reproduce (optional):_
Mostly happens erratically, after a while it starts working but this is in the early game. Try to hover over "Declare war on" screen.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by azum4roll** [comment]
You can't bribe wars on your friend.

**Comment by RecursiveVision** [comment]
@ThyraDannebod Yeah, you can't pay someone to DoW a player you have a DoF with.

**Comment by ThyraDannebod** [comment]
Oh, didn't know that. You can close this, then.
