### ISSUE TITLE
Pathing issues

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#828]
The rifleman can clearly make it from the '5' tile in screenshot 1 to the '7' tile in screenshot 2 in one turn. So why is the game suggesting I take the longer route?

![01](https://cloud.githubusercontent.com/assets/4227288/11412088/3035435e-93a6-11e5-839e-b75bd4456c48.jpg)
![02](https://cloud.githubusercontent.com/assets/4227288/11412090/3261823c-93a6-11e5-9ccf-287b88450ea4.jpg)

And only slightly related, once you get the tech that lets you embark/disembark in a city without losing all movement, the pathing once again gets screwy, namely, it thinks you can go farther than you actually can on the segment that involves the embarkation/disembarkation. No pictures of that at the moment.

**Comment by ilteroi** [comment]
good observation. there have been some changes in the latest version (not yet released). maybe it's solved already (also the disembark). let's keep an eye on it
