### ISSUE TITLE
[1.0.3] Crash during turn time (same turn)

### ISSUE THREAD

**Issue by DemaciaMaggotPie** [LoneGazebo/Community-Patch-DLL#8280]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0.3

_2. Mod list (if using Vox Populi only, leave blank):_
3/4 UC ; Milae's Hotkeys ; PDan's Tweaks ; Milae's alternative difficulty ; ReallyAdvancedSetup ;  Improved City View

_3. Error description:_ 
Crash on the same turn whenever I try to load the save and give it another shot. **Seems to be during the Aztec's Turn.**

_4. Steps to reproduce (optional):_
Load save, try to pass turn.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7213617/CvMiniDump.zip)

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7213586/Logs.zip)
[Crashing Nappy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7213594/Crashing.Nappy.zip)

:

**Comment by DemaciaMaggotPie** [comment]
Would it be useful for me to upload another crash-on-same-turn save? This one is much later in the game but I know it's not performance-related.

**Comment by RecursiveVision** [comment]
Please open a new issue if you encounter crashes in the latest version
