### ISSUE TITLE
crazy gift

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8281]
![image](https://user-images.githubusercontent.com/1358966/134471657-629350a1-101a-4e3d-a264-4f19e9332b54.png)

this is a lot of gold for the early game (T130) ... and they are at the other end of the world. we hardly know each other :)

![image](https://user-images.githubusercontent.com/1358966/134471754-88438abd-4951-4454-afd2-e1c22d3bd5f4.png)

**Comment by ilteroi** [comment]
some more AI/AI deals from my latest testgame

![image](https://user-images.githubusercontent.com/1358966/136051254-b4451a0e-2f9a-43d3-b30c-ecab01ef0acf.png)

![image](https://user-images.githubusercontent.com/1358966/136051515-28e9975f-7e6c-4b39-882e-9853c98b3821.png)

**Comment by CyberPhy** [comment]
I've had this problem also (sadly no screenshot :( )
The AI's do the something with Tech gifts also

**Comment by RecursiveVision** [comment]
That's Putmalk's code. I guess someone should fix it.
