### ISSUE TITLE
Governor-assigned specialists sometimes disappear

### ISSUE THREAD

**Issue by tojothethief** [LoneGazebo/Community-Patch-DLL#8282]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0.3

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP
More UCs
Community Events
Even More Resources

_3. Error description:_ 
If a city is left to its governor's choosing regarding specialists, they will sometimes fail to assign pop as specialists, and said pop will simply disappear from the city untill you choose manual specialist allocation.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
duplicate #8283
