### ISSUE TITLE
Worker disappearing when choosing science focus

### ISSUE THREAD

**Issue by dostillevi** [LoneGazebo/Community-Patch-DLL#8283]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0!

_2. Mod list (if using Vox Populi only, leave blank):_
![image](https://user-images.githubusercontent.com/39426657/134756912-c5a43656-0f2f-4b09-979c-b3cc95526e7e.png)
![image](https://user-images.githubusercontent.com/39426657/134756915-d361b7fd-cf15-4cec-b9eb-9682c4088d13.png)
![image](https://user-images.githubusercontent.com/39426657/134756918-65f8df47-314f-455c-bb35-40ae2641fcd8.png)

_3. Error description:_ 
When selecting science focus for my city, a worker seems to vanish. I checked all my city yields and the worker is doing nothing at all.

_4. Steps to reproduce (optional):_
1. Build a city with several citizens.
2. Change the city focus to science (or maybe others? I only could reproduce with science) and count to see if a citizen has disappeared.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7229115/Logs.zip)
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[Pachacuti_0122 BC-0950.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7229116/Pachacuti_0122.BC-0950.zip)
3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
Missing citizen:
![image](https://user-images.githubusercontent.com/39426657/134757068-dc8859d2-d261-44ee-9622-fe33f436d38b.png)
Changed focus to default and the citizen pops out of nowhere to work a tile:
![image](https://user-images.githubusercontent.com/39426657/134757078-1b3009fc-6e4f-4d52-b233-a7795dc1e39a.png)

**Comment by tojothethief** [comment]
This is the same as my issue below

**Comment by LoneGazebo** [comment]
@ilteroi any ideas?
