### ISSUE TITLE
Can't kidnap specialist 

### ISSUE THREAD

**Issue by Skidizzle** [LoneGazebo/Community-Patch-DLL#8285]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_

**1.0.3 43 civ**

_2. Mod list (if using Vox Populi only, leave blank):_
infoaddict v22
enhanced naval warfare v2

_3. Error description:_ 

kidnap specialist spy event not selectable during renaissance and later eras despite having level 3 spies

**Comment by Skidizzle** [comment]
I can now kidnap in the Atomic Era. Is this a tooltip error?

**Comment by Skidizzle** [comment]
Ok, its happened again in the Atomic Era. This time in a city that only has 2 writers. Tooltip says that i need to be in at least the renaissance. Is it a matter of only specific types of specialists?

**Comment by LoneGazebo** [comment]
no, it's likely that someone else was already doing it. Did you see any more info in the tooltip?

**Comment by Skidizzle** [comment]
The tool tip only listed that I was not in Renaissance, despite being well past it.
