### ISSUE TITLE
tactical moves

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#829]
this is the current list of tactical moves, in the order they are executed.

priority seems about right - might need to demote reposition though, it does not have any precondition and thus applies to all units. therefore all moves with a lower priority are effectively skipped.

question is, where is the "interruptibility" defined? this might need to be sorted out in some cases.

	Move 32: TACTICAL_EMERGENCY_PURCHASES - Prio 200 (not interruptible)
	Move 48: TACTICAL_PILLAGE_CITADEL - Prio 200 (not interruptible)
	Move 2: TACTICAL_CAPTURE_CITY - Prio 150 (not interruptible)
	Move 31: TACTICAL_MOVE_OPERATIONS - Prio 150 (not interruptible)
	Move 40: TACTICAL_OFFENSIVE_POSTURE_MOVES - Prio 150 (not interruptible)
	Move 4: TACTICAL_DESTROY_HIGH_UNIT - Prio 140 (not interruptible)
	Move 24: TACTICAL_AIR_SWEEP - Prio 135 (not interruptible)
	Move 25: TACTICAL_AIR_INTERCEPT - Prio 130 (not interruptible)
	Move 33: TACTICAL_ATTACK_VERY_HIGH_PRIORITY_CIVILIAN - Prio 130 (not interruptible)
	Move 5: TACTICAL_DESTROY_MEDIUM_UNIT - Prio 120 (not interruptible)
	Move 6: TACTICAL_DESTROY_LOW_UNIT - Prio 110 
	Move 29: TACTICAL_POSTURE_SHORE_BOMBARDMENT - Prio 100 (not interruptible)
	Move 38: TACTICAL_PLUNDER_TRADE_UNIT - Prio 100 (not interruptible)
	Move 49: TACTICAL_PILLAGE_RESOURCE - Prio 100 (not interruptible)
	Move 27: TACTICAL_POSTURE_WITHDRAW - Prio 95 (not interruptible)
	Move 14: TACTICAL_SAFE_BOMBARDS - Prio 90 (not interruptible)
	Move 34: TACTICAL_ATTACK_HIGH_PRIORITY_CIVILIAN - Prio 90 (not interruptible)
	Move 13: TACTICAL_PILLAGE - Prio 75 (not interruptible)
	Move 30: TACTICAL_CLOSE_ON_TARGET - Prio 75 (not interruptible)
	Move 37: TACTICAL_ESCORT_EMBARKED_UNIT - Prio 75 
	Move 50: TACTICAL_PILLAGE_CITADEL_NEXT_TURN - Prio 75 (not interruptible)
	Move 51: TACTICAL_PILLAGE_RESOURCE_NEXT_TURN - Prio 65 (not interruptible)
	Move 35: TACTICAL_ATTACK_MEDIUM_PRIORITY_CIVILIAN - Prio 60 (not interruptible)
	Move 3: TACTICAL_DAMAGE_CITY - Prio 50 
	Move 8: TACTICAL_ATTRIT_HIGH_UNIT - Prio 50 
	Move 28: TACTICAL_POSTURE_HEDGEHOG - Prio 50 (not interruptible)
	Move 52: TACTICAL_PILLAGE_NEXT_TURN - Prio 50 (not interruptible)
	Move 47: TACTICAL_DEFENSIVE_AIRLIFT - Prio 42 (not interruptible)
	Move 36: TACTICAL_ATTACK_LOW_PRIORITY_CIVILIAN - Prio 40 (not interruptible)
	Move 9: TACTICAL_ATTRIT_MEDIUM_UNIT - Prio 35 
	Move 16: TACTICAL_ANCIENT_RUINS - Prio 25 
	Move 17: TACTICAL_GARRISON_TO_ALLOW_BOMBARD - Prio 20 
	Move 10: TACTICAL_ATTRIT_LOW_UNIT - Prio 12 
	Move 7: TACTICAL_TO_SAFETY - Prio 11 (not interruptible)
	Move 12: TACTICAL_BARBARIAN_CAMP - Prio 10 (not interruptible)
	Move 11: TACTICAL_REPOSITION - Prio 9 
	Move 15: TACTICAL_HEAL - Prio 8 
	Move 39: TACTICAL_PARK_ON_TRADE_ROUTE - Prio 8 (not interruptible)
	Move 18: TACTICAL_BASTION_ALREADY_THERE - Prio 7 
	Move 19: TACTICAL_GARRISON_ALREADY_THERE - Prio 6 
	Move 21: TACTICAL_BASTION_1_TURN - Prio 5 
	Move 22: TACTICAL_GARRISON_1_TURN - Prio 4 
	Move 20: TACTICAL_GUARD_IMPROVEMENT_ALREADY_THERE - Prio 3 
	Move 23: TACTICAL_GUARD_IMPROVEMENT_1_TURN - Prio 2 
	Move 26: TACTICAL_AIR_REBASE - Prio 1 (not interruptible)
	Move 1: TACTICAL_MOVE_NONCOMBATANTS_TO_SAFETY - Prio 0

**Comment by LoneGazebo** [comment]
It is defined in the <TacticalMoves>  XML.

**Comment by LoneGazebo** [comment]
TacticalMoves XML, that is.

**Comment by ilteroi** [comment]
ah. found it in CIV5TacticalMoves.xml

but that is not included in the mod. can we include it? will it be used instead of the orginal then?

**Comment by LoneGazebo** [comment]
Eh? It's a standard civ file, so we can just edit the values. There's already a couple of edits to the tacticalmoves in the CP (CoreChanges.sql, I think), so we can just edit the ones we need to.

**Comment by LoneGazebo** [comment]
What's your plan, here? Is this an issue of ID sequencing? If that's the case, we'll need to nuke the current tacticalmoves table and then rewrite it in the CP.

**Comment by ilteroi** [comment]
kind of lost focus here. anyway, i found the place where you do an SQL update of some of the priorities. should be ok.

**Comment by LoneGazebo** [comment]
Cool.
