### ISSUE TITLE
The Great Firewall

### ISSUE THREAD

**Issue by briantjack** [LoneGazebo/Community-Patch-DLL#8291]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0.3

_2. Mod list (if using Vox Populi only, leave blank):_
Enhanced Naval Warfare for VP
Pontoon Bridges for VP

_3. Error description:_ 
With the new security system in place, how does the Great Firewall affect foreign spy success rates? (In one turn alone, nine spies successfully completed their missions against my cities. My security network caught none of them.)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
slows them down substantially - but that slowing won't affect a spy already on a mission, only newly-started spies.

**Comment by briantjack** [comment]
So, "reduction in enemy spy effectiveness" simply means that enemy spy operations take longer but still have the same rate of success?

**Comment by LoneGazebo** [comment]
yes
