### ISSUE TITLE
Grand Temple doesn't work

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#8295]
_1. Mod version (X.Y.Z, e.g. 1.0.0): 1.0.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:  

Double pressure and +1 vote for every 6 cities with your religion doesn't seem to work. 

Also missing yields in description: Grants Temples +2 faith and +1 gold.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
those features are on the reformation buildings IIRC.

**Comment by Aqinu** [comment]
![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/136072433-3e38dbdd-be97-4182-a922-a23f474d75c4.png)

It's already fixed  #8271.

**Comment by Aqinu** [comment]
Version 1.1 still not fixed

**Comment by Aqinu** [comment]
@LoneGazebo, you made the change for the grand temple with VanillaBuildingChanges.sql file. So do you keep the file or not (cause the changes don't work)?

**Comment by LessRekkless** [comment]
![image](https://user-images.githubusercontent.com/34615525/140851546-f4aabdc8-ca53-422c-a280-60ef133595ab.png)
https://github.com/LoneGazebo/Community-Patch-DLL/blob/d345671cd429de86b37f24507186af890ed1b4ba/Community%20Balance%20Overhaul/Balance%20Changes/Beliefs/ReligiousNW/Changes.sql#L3-L13
https://github.com/LoneGazebo/Community-Patch-DLL/blob/d345671cd429de86b37f24507186af890ed1b4ba/Community%20Balance%20Overhaul/Balance%20Changes/Buildings/NationalWonderChanges.sql#L359-L363
https://github.com/LoneGazebo/Community-Patch-DLL/blob/d345671cd429de86b37f24507186af890ed1b4ba/(3)%20CSD%20for%20VP/Buildings/VanillaBuildingChanges.sql#L3-L6
https://github.com/LoneGazebo/Community-Patch-DLL/blob/d345671cd429de86b37f24507186af890ed1b4ba/EUI%20Compatibility%20Files/CSD/CSDCompatibility.sql#L246-L256

So, as far as we can tell, we now only have a National Wonder that doesn't require Holy City to be built, gives 6 Faith, and boosts Temples a bit. 

Instead, Reformation Wonders require the Holy City, get +25% Pressure, 20% Conversion Resistance (in addition to the Reformation Belief, Boost to Holy Sites, and other bonuses).

I'm not quite sure why the Grand Temple -> Reformation Wonder change happened in the EUI/No EUI CSD files, but there it is.

Is a National Wonder that does so little desirable?
