### ISSUE TITLE
[13/66.9] Terrain defense not logical

### ISSUE THREAD

**Issue by skodkim** [LoneGazebo/Community-Patch-DLL#83]
Unless it's graphical forests give +25% defense and hills 10% defense. That's fine I suppose but why do Forests on hills only give 10% defense?

Using other mods (EUI, E&D, CSD, ...) but I don't think it's related to any of them.

\Skodkim

**Comment by skodkim** [comment]
Have you looked into this yet?

Just did a couple of tests on this using 66.11/13.2.
Test 1: Set HILLS_EXTRA_DEFENSE=100
Test 2:  Set HILLS_EXTRA_DEFENSE=10 and Defense on FEATURE_FOREST=100

Both tests show that forests do not give additional defense on hills visually. 

Furthermore I did some test battles on different terrains combinations *(flat lands, hills, hills with forests) using the same unit combinations and they indicate that there's no extra defense from forests on hills.

\Skodkim

**Comment by LoneGazebo** [comment]
I have, yes. Did you see my post on civfanatics?
