### ISSUE TITLE
tech cost too low?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8303]
the fertilizer tech is 7K science, giving it away for that price seems a bit too generous, no?

![image](https://user-images.githubusercontent.com/1358966/136052964-2f6cd25b-df3f-4071-9dd0-fb95f39adcac.png)

**Comment by LoneGazebo** [comment]
what's the science per turn?

**Comment by ilteroi** [comment]
no idea. but yeah, the price is determined by looking at remaining turns, although with a lot of ad-hoc kludges thrown in ... so i guess i'm questioning the whole logic.
