### ISSUE TITLE
'Barbarian Horde' event's last spawn wave's timing

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#831]
In case you haven't looked at this yet: some users in the 'Barbarian horde' thread on Civfanatics have confirmed seeing the last wave of barbarians during the said event spawn near its very end (e.g. 1 turn before the end).

**Comment by LoneGazebo** [comment]
I'll take a look.
G

**Comment by idontknow12** [comment]
Chiming in to say this still happens in the latest version with game time set to quick (the fastest).
I believe the quest duration is either 13 or 15 turns on that, and the last wave comes exactly at 1 turn left.

**Comment by LoneGazebo** [comment]
Alright fixed for next version.
