### ISSUE TITLE
spy event yield booked for wrong city?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8315]
![image](https://user-images.githubusercontent.com/1358966/136627380-b685dfd5-bd1a-4a6a-8dcd-c2362b0ddb54.png)

so it seems somebody stole gold from me but it was added to my treasure instead of theirs?

**Comment by ilteroi** [comment]
still the text is misleading, i did not gain anything. and is it even a raid if i lost nothing?

**Comment by LoneGazebo** [comment]
Well the bottom text is just telling you what the foreign operatives did - technically 'raid' is probably not the best word choice, but I struggle with better wording here.
