### ISSUE TITLE
Cities look broken and automatically shown (43 civ)

### ISSUE THREAD

**Issue by JakcieChan2** [LoneGazebo/Community-Patch-DLL#8318]
_1. Mod version (X.Y.Z, e.g. 1.0.0): 1.0.3

_2. Mod list (if using Vox Populi only, leave blank): Vox Populi with 43 civ

_3. Error description: Foreign cities are always shown and look broken.

_4. Steps to reproduce (optional): Just start a new game with 43 civ addition and click next turn

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7316620/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Alexander_0002 BC-3920.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7316623/Alexander_0002.BC-3920.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): NONE

4. Screenshots (optional)
![Screenshot (86)](https://user-images.githubusercontent.com/92235858/136677057-d5f64127-00dc-4669-b8fe-75d41cb0210e.png)
:

**Comment by RecursiveVision** [comment]
Non EUI glitch
