### ISSUE TITLE
Venice not assigning tiles in puppet cities in new beta. 

### ISSUE THREAD

**Issue by HeroOfTheSword** [LoneGazebo/Community-Patch-DLL#8319]
_1. Mod version:_ 1.1 (October 13, 2021) no eui. 

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ New beta said Venice could assign tiles in Puppet cites, but this isn't working. I first tried it with all my extra mods, then I deleted cache as always, reinstalled without additional mods but still had the same issue. I even reinstalled it a third time. 

_4. Steps to reproduce (optional):_

Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"): 
[Logs file.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7348532/Logs.file.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Saved Game.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7348534/Saved.Game.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by HeroOfTheSword** [comment]
> maybe the description was unclear, it should have said venice can re-assign puppet tiles to non-puppets.

Thanks for the response. I'm actually still unsure what it means, is it that when you settle a new city overlapping your capital, you can re-assign tiles taken by the puppet? Or is it something else entirely? I'm glad it's not a bug though, that's the main thing!

**Comment by ilteroi** [comment]
well normally if a tile is in reach of multiple cities you can manually choose which city should work it. unless the tile is owned by a puppet. but venetian puppets are special. really quite a minor thing.
