### ISSUE TITLE
Cannot move Greatworks

### ISSUE THREAD

**Issue by myeong1129** [LoneGazebo/Community-Patch-DLL#8320]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_

1.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

I cannot move the Greatworks to the second or latter slots of any building. There's no issue about putting GW to the first slot or the only slot of the building. Fortunately optimize buttons work, so I could use it to get theme bonuses, but it's still kinda disturbing as I can't check for theme bonus myself.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by AndreyK-555** [comment]
You can try first to press desired slot (second or latter slot) of building and then on GW you want to move there. For me also if you want to move GW from second or latter slot you should first move it to building with 1 slot and then to desired slot
