### ISSUE TITLE
Slow AI expansion

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#8321]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.03

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Babylon has 2 cities (turn 100) even though it has beautiful land next to it. Maya has 3. I got more cities (4) even though I play authority Sweden; thus I'm not focusing 'peaceful expansion' (Meaning that I'd expand more aggressively and would have had another city, or one about to settle by now - sometimes even _two_). Babylon should easily have at least one more city than me. 

I don't know why this is so. Babylon can't win the game going about doing this, shooting itself in the foot for no reason at all - when there is unchallanged land next to it.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/137581914-f519b705-57ef-4687-aa0e-2f85bce61e67.png)

**Comment by ilteroi** [comment]
can confirm; since a while AI expands significantly more slowly, especially tradition players. which is good, but probably they should consider the quality of open settle spots as well

**Comment by RecursiveVision** [comment]
@ilteroi Didn't you change the "enough expansion" logic?
