### ISSUE TITLE
More naval mechanics

### ISSUE THREAD

**Issue by lfricken** [LoneGazebo/Community-Patch-DLL#8322]
This is a suggestion to change naval mechanics a bit. I'm a software developer and made a naive implementation for me and my friends in my own branch [here](https://github.com/lfricken/LeonMod/commit/b4e42984424d6d61b6a4e4ba221f431bb658998d) on an older version of VP. I figured I'd drop them here in case VP was interested. Thanks for such an amazing mod!

Why change things? Because naval combat is boring. The ocean behaves as an infinite plane of uniform density upon which boats crash into each other without much "tactical" analysis required. Compare that to land, where mountains, hills, forests, cities, and roads create defensive positions, areas of high movement, areas of low movement, regions of danger, and critically: interesting combinations of those. Consider how boring land combat would be if it was all flat terrain with no roads.

But that's exactly what naval combat is like now, so we did the following:
1. Ocean tiles always cost two movement. Coast is 1.
2. Workboats can create "naval" fortifications.
3. You can build canals across land that cost 2 movement to ships. They cost defensive penalties and cannot be used if there are nearby enemy land units.
4. There are many ways you can balance these (increase base boat movement for balance, ocean costs 1.5, high canal maintenance, canal only in borders, even slower canal movement, etc. Same with fortification)

All of these changes are certainly unrealistic, but [only to some extent](https://improvesailing.com/media/pages/guides/sailing-seasons/3486132774-1558441123/map_prevailing_winds_on_earth.png). There really are areas of higher movement, for sailboats anyway. It's definitely not realistic once you get to self-powered ships. Similarly, big canals and naval forts are on shaky "realism" ground.

[I saw discussions](https://forums.civfanatics.com/threads/is-there-an-official-or-unofficial-consensus-vox-populi-map-script.620305/page-2) about canals being "unrealistic", so I do think I should add this here: Is Civilization V realistic in any domain? In real life workers can fight, and warriors can farm. If, in Civ 5, "warriors" made farms and "workers" fought in battle, the problem isn't that it would be realistic or unrealistic, it would **_primarily_** be that the game would become less interesting and that it would violate common sense uses of the terms warrior and worker. Canals that span a continent, or ships that don't move as fast in deep water are similar. The terms match the behavior close enough. If you feel most people wouldn't enjoy these changes, that's a perfectly valid reason to not implement them, but please don't decide based on "realism".

I can only say from experience playing that these changes made the game more interesting, and the ideas/terms made the mechanics seem perfectly reasonable to people I played with, given the other liberties civ 5 takes with realism. Thanks again for such an amazing mod!

**Comment by RecursiveVision** [comment]
@lfricken This would be better suited to a modmod. Implementing this in the base mod would require polling on the forum.
