### ISSUE TITLE
Unknown Foreign Operatives aren't Unknown

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#8326]
_1. Mod version (X.Y.Z, e.g. 1.0.0):_
1.0.3

_2. Mod list (if using Vox Populi only, leave blank):_
![image](https://user-images.githubusercontent.com/34615525/137640830-8b44f6ca-376e-4b8d-92ee-a4de3cbf7006.png)

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/34615525/137640840-33c0f328-37a4-42a0-9ce8-51f986f074b9.png)
![image](https://user-images.githubusercontent.com/34615525/137640846-2aff9649-412d-401a-a85f-e98dde6d4374.png)
Even though my counterspy was unable to identify what civilization committed a spy action, one of the tooltips does indicate the name of the spy.  Knowing enough about what civilizations employ which spies allows me to determine that Valeriy is from Russia.

In this context, the second notification seems completely superfluous.

**Comment by RecursiveVision** [comment]
#8368
