### ISSUE TITLE
Serious Bug after City Captured

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#8330]
Version: 1.1 and 1.0.3
In two games now I have had a city where the UI for them has basically stopped working. It's not possible to choose buildings or change tiles.

The common factor seems to be the AI capturing one of my cities at which point cities (which shared tiles perhaps) become bugged.

Picture won't really explain so here is the link to vid where I had this bug. https://www.twitch.tv/videos/1180436932?t=60m25s

**Comment by RecursiveVision** [comment]
Thank you for the data.

**Comment by ilteroi** [comment]
hmm. hopefully rare, i don't have time to investigate right now
