### ISSUE TITLE
AI not capturing ridiculously easy to conquer cities

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#8334]
@ilteroi 1.1 version

In an attempt to debug #8330, I DoW'ed Assyria and gave them two Modern Armor units (100 CS) versus my two cities with 5 CS.

They keep moving their units into my territory but don't conquer the city despite the fact that they could do it in a single turn. Not sure what's up here?

[Alexander_0002 BC-3920.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7375696/Alexander_0002.BC-3920.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7375697/Logs.zip)
![Screenshot](https://user-images.githubusercontent.com/66801010/137965513-a84d3092-1417-42f2-a850-00d89f8f06ea.png)

To reproduce: load the save and hit Next Turn repeatedly.

I gave each city control of one tile in the other city, so if you fix you may encounter the #8330 bug next.

**Comment by ilteroi** [comment]
their actions depend on the "tactical posture" ... which might be off in that unusual situation
