### ISSUE TITLE
Double City-State embassies are possible (only one is valid)

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#8335]
Latest version.

If you build a City-State embassy 4-5 tiles away, the AI **can** build an embassy in the City-State's territory, but humans are **not** able to.

However, if the AI plants a second embassy like this, the generated embassy doesn't give them a World Congress delegate (the original one does grant a delegate).

In the screenshots below, I planted an embassy 5 tiles away from the City-State, and then the Mongols planted their embassy next to the City-State several turns later. Only my embassy gave me a delegate.

![Screenshot 1](https://user-images.githubusercontent.com/66801010/138007325-810a27d9-87b6-4ce8-b763-815cad1ae5b1.png)
![Screenshot 2](https://user-images.githubusercontent.com/66801010/138007327-9c0ce708-0763-44fa-9314-38c19eb7a81d.png)
![Screenshot 3](https://user-images.githubusercontent.com/66801010/138007329-c552f503-fa8f-4086-aee7-4d9aed03bae8.png)

**Comment by LoneGazebo** [comment]
pCity->GetNumWorkablePlots() is the culprit
@ilteroi does this function only cover tiles ring 3 and in?
