### ISSUE TITLE
Few War QOL questions

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#834]
I'm unable to see if I will get a MAJOR or MINOR warmonger penalty from conquering a city against certain civs that have a lot of wonders and/or diplomacy modifiers with me. Whenever I hover their city, I see a long list of all the wonders they've built (around12 because they were Egypt) and then all the diplomacy modifiers (around 15 because we were neighbors). The tooltip goes from the top to the bottom of the screen with still more information cut off on the bottom. 
![image](https://cloud.githubusercontent.com/assets/13261433/11445965/cf273c1e-94f6-11e5-9d0f-b0f941e7b805.png)

Also, upon city capture, I still don't know how each option affects my city count. If I annex a city, I understand that it will increase my science and culture costs. But what about puppeting and razing? Some tooltips would be nice too!

**Comment by LoneGazebo** [comment]
The tooltip issue is a problem with EUI, and is not in my purview (my version of EUI is just edited for compatibility). So you should bring these issues up with bc_1 over on the forums.

**Comment by Radost** [comment]
On the subject of EUI, it was updated recently.

**Comment by LoneGazebo** [comment]
Blegh. EUI updates are the worst.

**Comment by oalzubbi** [comment]
Okay, what about city count (from capture, raze, etc)? Can you do anything to clarify that?

**Comment by LoneGazebo** [comment]
I don't know what you mean. Puppets do not raise the % tech/policy cap, but annexed cities do. Razing does, but it overlaps with the next city you gain, so it's a 'ghost.' These are all core game elements.

**Comment by oalzubbi** [comment]
I meant adding that information to the city capture screen. It's not super critical, just a small qol addition. 
Don't know if this is the best place to bring it up, but I don't really like that razing cities increasese your costs. It doesn't really make sense for that penalty when you're not getting anything out of razing the city.

**Comment by Radost** [comment]
The "ghost" mechanic sure is obscured for a core element.

**Comment by LoneGazebo** [comment]
Both are part of how the razing/city count function is built into the iterator. Sorry, can't really change that (not my choice to have it done that way).

The info on puppet/razing elements are in the tooltips for culture and science on the top panel, FYI.

G
