### ISSUE TITLE
Ending up last with negative value building 'Treasure fleet'

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#8347]
_1. Mod version (X.Y.Z, e.g. 1.1.3):_
I'm using version "1.1.1"

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) City-States Leaders for VP (v 10)
Calypso's Colored Religion Icons (Basic) (v 1)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 
I believe I've spent 1 turn, and is about to spend another turn building on this world project 'Treasure fleet'. When pressing next turn I end up last place with a negative value of -83 production!

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Treasurefleet ERROR 1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7404695/Treasurefleet.ERROR.1.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/138596039-da70e5ed-68e4-4632-9ec1-9d81f9f00788.png)

**Comment by LessRekkless** [comment]
Did a spy attack your production?

**Comment by NewFellow** [comment]
@LessRekkless That's a relevant question. Now I don't remember, but can spies disrupt building these projects?

**Comment by LoneGazebo** [comment]
anything that costs production can be interrupted, including by random events.

**Comment by RecursiveVision** [comment]
Yes, but it shouldn't result in negative Production? Shouldn't it be capped at 0?

**Comment by ilteroi** [comment]
with 1.3.4 + x (ole branch tip), events disabled

![image](https://user-images.githubusercontent.com/1358966/151677043-8599738f-a95b-46ce-aa9a-e5d054377934.png)

**Comment by sgtslick** [comment]
I just had this happen to me and despite killing the culprit (the filthy chinese dog), I still got -700 production. This spy function to attack production is kind of ridiculously powerful btw.. Every few turns I am getting this at the moment. I don't have constabulary yet..
