### ISSUE TITLE
Peace Treaty Weirdness

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#8348]
1.1.3

Apologies for the title, couldn't think of a good, succinct way to summarize the problem. 

Here's what happens:

- Click "Negotiate Peace"
- Deal screen opens, but the usual "Peace Treaty" option is not present, and is greyed out on the sides.
- Clicking either the "Accept" or "What will this take?" does nothing except indicate the AI is unwilling to discuss it.
- Backing out to the leader screens shows that the AI is now in "peace not possible" mode. Clicking "Negotiate Peace" returns the typical "the time for diplomacy is long gone" etc etc.

**Comment by ridjack** [comment]
Got a little bit more info on this.

It appears to happen when something happens during the player's turn to cause the relevant AI to re-evaluate their peace willingness. For example, if they willing to make peace but then I take a city from them, the situation above unfolds.

**Comment by RecursiveVision** [comment]
@ridjack Ohhhh I know what caused it. Will fix.
