### ISSUE TITLE
AI not considering other AIs' valuation of deal items

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#8358]
@ilteroi I finally fixed the infamous "AI going over Defensive Pact limit" bug. 

The AI-to-AI deals seem to only be considering the asking AI's own valuation of the deal items, and so the AI would automatically agree to make a Defensive Pact (or Research Agreement) whenever it was offered, provided it could equalize the deal. 

But both sides of the equalization are made using the asking AI's valuation, not the other AI's.

This seems like it might be responsible for a lot of insane AI-to-AI trades and deal offers? You might wanna look at this.

**Comment by Mileslewis** [comment]
Where do you think this is happening? I don't see it.

**Comment by RecursiveVision** [comment]
@Mileslewis GetDefensivePactValue() is called only for the asking AI, then equalized.

**Comment by RecursiveVision** [comment]
Milae is looking at this
