### ISSUE TITLE
Constant CTD when progressing to next turn. Also missing Great Prophets or i am missing something

### ISSUE THREAD

**Issue by Makikou** [LoneGazebo/Community-Patch-DLL#836]
Sorry if this is my fault, but i've hit a new snag in my Rome game.. Actually two i think.

Right now the save game is stuck. Clicking next turn seems to always crash civ5. The Mega.co.nz link below will include logs + savegame + crash dump.

Also there might be an issue with no great prophets spawning at all.. Not sure if i have messed something up but CustomMods.txt is full of:
CvPlayer.cpp[5280] - GetSpecificUnitType for player Augustus Caesar: UNITCLASS_PROPHET is UNKNOWN!!!
CvPlayer.cpp[5280] - GetSpecificUnitType for player Ahmad al-Mansur: UNITCLASS_PROPHET is UNKNOWN!!!
CvPlayer.cpp[5280] - GetSpecificUnitType for player Ahmad al-Mansur: UNITCLASS_PROPHET is UNKNOWN!!!
CvPlayer.cpp[5280] - GetSpecificUnitType for player Suleiman: UNITCLASS_PROPHET is UNKNOWN!!!
CvPlayer.cpp[5280] - GetSpecificUnitType for player Suleiman: UNITCLASS_PROPHET is UNKNOWN!!!

for every civ.

https://mega.nz/#F!lBFFWA6a!dfARaP0wohV9oP-VB_6VeQ

**Comment by LoneGazebo** [comment]
You've got a ton of broken mods in your database.log. A mod list would help.
G

**Comment by Makikou** [comment]
Okay, stupid question before i go gather my mod list BUT: Shouldn't the game only use the mods i select in the Mods screen (as in the 6 CBP mods w/ EUI) ? So the ones that probably are broken as hell aren't even selected but they are still loaded? 

Anyway.. if i just remove all the other ones.. maybe it'll work? :D

**Comment by Edaka** [comment]
The first thing you shall do is make sure you've cleared your cache before starting a game with a different set of mods/different mod version (which means you also have to clear cache every time when you install a new CPP version). So, to answer your question: just deselecting mods in the ingame mod screen will usually still leave some artifacts.

**Comment by Makikou** [comment]
Then you can close this, didn't realize i need to do it between CPP installs also. Damn. 

So sorry for the inconvenience for you guys.

**Comment by LoneGazebo** [comment]
No worries at all! It happens.
