### ISSUE TITLE
Kills via Overrun's secondary damage do not trigger on-kill bonuses.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#8362]
1.1.3

I believe this also applies to other things, like the Dromon's plague damage.

**Comment by pineappledan** [comment]
all AOE damage (splash, overrun, pilum, etc) does not trigger yields on kills. I think this has been kept as is for performance.

**Comment by ilteroi** [comment]
this is weird because DoAdjacentPlotDamage() does call DoYieldsFromKill()

**Comment by LoneGazebo** [comment]
Possibly because the unit isn't being triggered as _being killed_ by the killing unit?
