### ISSUE TITLE
AI goes bananas

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#8365]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_
1.1.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
AI seem to fail improving the resource _banana_ for whatever reason.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/139524608-74f850c7-8085-4b5a-a390-e1b57dcbe861.png)
![image](https://user-images.githubusercontent.com/20144751/139524618-b5b2fd9f-2338-4e80-8367-183b7c52bd7b.png)

**Comment by ilteroi** [comment]
they do it eventually but i can confirm the priority seems to be relatively low

**Comment by NewFellow** [comment]
Eventually you say? I just entered the modern era here... You mean that they might be postponing until information era; being busy doing something else? :))

But it does take alot of time finishing all the tiles around the cities, so I can understand the problem.

**Comment by azum4roll** [comment]
It's actually not worth to improve bananas anymore after universities. It should be given more priority earlier though.
