### ISSUE TITLE
Incan 'mountain walk' ignores rivers

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#8367]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_
1.1.3

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) City-States Leaders for VP (v 10)
Calypso's Colored Religion Icons (Basic) (v 1)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 
Incan 'mountain walk' _ignores rivers_. This can't be intended right (otherwise very OP), since no other promotion nor civilization - like the celts 'hill walk', aztecs and iroquois with their 'forest walk' - has this ability? I mean they have to cross the river _first_ and all movement points should have been spended through such an action.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[INCA LONGSWORDMEN JUMP.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7449812/INCA.LONGSWORDMEN.JUMP.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
Look at that swordsman in first screenshot, then see him having jumped over the river killing my horse and worker standing in the forest.
![image](https://user-images.githubusercontent.com/20144751/139601950-6bc21b4e-5514-401b-83f7-2e817d4be0be.png)
![image](https://user-images.githubusercontent.com/20144751/139601976-c6a05f2b-9ec5-46d2-98e4-cd47e25517f8.png)

**Comment by ilteroi** [comment]
works fine, river crossing ends the turn. except for scouts.

![image](https://user-images.githubusercontent.com/1358966/139601532-59eba5d8-0014-423a-a096-3cf7948221a6.png)

**Comment by NewFellow** [comment]
How about the 'hills'? It was an non amphibious swordmen who jumped over the river to an hill, then killing a unit behind that hill.

**Comment by NewFellow** [comment]
@ilteroi See screenshot how that unpromoted _Longswordmen_ jump the river

**Comment by ilteroi** [comment]
got it, happens only after researching engineering (and bridge building).

**Comment by NewFellow** [comment]
Good job! Thanks.
