### ISSUE TITLE
spy notifications

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8368]
two things here.

1. how does disruption of production work with a process?
![image](https://user-images.githubusercontent.com/1358966/139591599-fde8c4bc-60b0-4021-aef5-0c266b03870f.png)

2. it seems the second notifcation is going to the wrong player, i'm the victim here but it should go to the owner of the spy?
![image](https://user-images.githubusercontent.com/1358966/139591622-24f3190e-834b-452c-8f08-d6c298006b86.png)

**Comment by ilteroi** [comment]
oh and this one is weird as well

![image](https://user-images.githubusercontent.com/1358966/139596536-431e4cde-43e9-4998-92a1-034e9b1dc817.png)

malformatted and wrong attribution

**Comment by RecursiveVision** [comment]
I fixed the notification going to the wrong player, but not the other issues

**Comment by calloatti** [comment]
#8469

**Comment by RecursiveVision** [comment]
oh yeah i fixed this
