### ISSUE TITLE
strange decisions

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#837]
![image](https://cloud.githubusercontent.com/assets/1358966/11451506/c6dbf19e-95c8-11e5-899d-3bd3dec5b8b5.png)

there is only a monument here (tooltip says 1 culture per turn), but the city produces 3 culture.

i checked the code and indeed m_aiBaseYieldRateFromBuildings[YIELD_CULTURE] is 3. it seems that this value is only reset when the city is initialized, normally it's only consecutively updated. so maybe there's a bug somewhere.

on the other hand, isn't there a policy which gives you +2 culture from monuments? maybe it's simply that the tooltip (either for the monument or for the total culture) is misleading.

**Comment by Edaka** [comment]
I'd say it's probably the policy. Culture from policies on buildings isn't displayed properly and Gazebo's said it's unfixable. I mean, when you hovered over the monument on the right it said +1 culture, yes?

**Comment by LoneGazebo** [comment]
I think this was fixed in the latest version. You using latest version?

**Comment by ilteroi** [comment]
ok, same savegame but different outcome, and about 100 turns later

![image](https://cloud.githubusercontent.com/assets/1358966/11453721/355aab0e-9616-11e5-9fc2-ce51c97bcc1a.png)

observations:
- the city has no monument this time?
- but it does have a hotel?
- and a caravansary?

**Comment by LoneGazebo** [comment]
Policies/Tenets/Religion?

G

**Comment by Radost** [comment]
Yeah, puppets (and by extension AI) are that retarded. I don't even know why do they build hotels above all else, as hotel is the last building I want a puppet to build.

**Comment by LoneGazebo** [comment]
Puppets and AI use similar algorithms, but Puppets don't have the ability to call upon AI flavors like AI cities do. AI cities have an advantage in that regard.
