### ISSUE TITLE
Paper UI doesn't show paper gained by Great Diplomats

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#8370]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_
1.0.3

_2. Mod list (if using Vox Populi only, leave blank):_
+Pdans's 3/4 UC and tweaks

_3. Error description:_ 
![unknown](https://user-images.githubusercontent.com/34615525/139598308-20f42109-043d-438c-97a8-6f7550a9f4fc.png)
It took me a while to figure out that the unaccounted paper in this UI came from Great Diplomats being expended. Is there any way a counter can be added to the UI?

**Comment by inkyant** [comment]
the resources code is pretty messed up, I'll have a look
