### ISSUE TITLE
AI offers to vote NAY on my proposal

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8371]
just an example: i proposed an open door for the city state of sidon, and egypt wants to sell me his NAY. does not make sense.

it seems the code just looks at what the AI desires itself (which is fine) but does not take into account that i made the proposal and therefore would like it to succeed. a fix is probably possible somewhere in CvLeagueAI::GetDesiredVoteCommitments() but i don't know how.

**Comment by Mileslewis** [comment]
I'm guessing it was called with bFlippedLogic as 'true'. It doesn't seem to really work when bFlippedLogic is true.

If it was just always called with it false then they would only offer a human 'nay' on sanctioning them and 'yea' on something the human had proposed.

**Comment by Mileslewis** [comment]
I could just get rid of the bFlippedLogic option but I'm confused why it's there in the first place.

**Comment by RecursiveVision** [comment]
@Mileslewis Search to see where it's called from. If it's never set to true then just delete the code, it's probably a fragment of old code.

**Comment by RecursiveVision** [comment]
@Mileslewis Found the code section. 

The intention here is that the AI is trying to estimate what the human would want and offer to vote on things they would like. I don't know why bFlippedLogic is used to do that, so I think a better approach is to remove bFlippedLogic and add a special check - if a player proposed something, assume they would want the AI to vote for it and not vote against it.
