### ISSUE TITLE
Works of art can't be freely moved around between slots

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#8374]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_
1.1.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When clicking on a _great work of art_ in an attempt to move it to another slot, in another city. The action is canceled and the great work is not moved. Sometimes it works if one moves from the first slot into the first slot of the other city, but if one were to move it to the second slot nothing happens. In the screenshot I'm trying to move a great work of art from the artist guild into the Louvre - but it can't be moved.

This bug wasn't here before.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/139748585-92413eca-deb4-4ce3-b1fe-79f9c01b27c8.png)

**Comment by NewFellow** [comment]
Seems like it works if I press the empty slot and then on the great work that I want moved to it.

**Comment by gamask** [comment]
What NewFellow suggested worked for me sometimes, but other times it led to infinite happiness gain each time I did it.
+6 "from events" for every time I did.
Happiness persists into next turn and on reload.
I don't have exact steps to reproduce. Just click around randomly 50 times and it's almost guaranteed to happen.
