### ISSUE TITLE
City can't build Trainstation 

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#8375]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_
1.1.3

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) City-States Leaders for VP (v 10)
Calypso's Colored Religion Icons (Basic) (v 1)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 
This city (screenshot) can only build _Seaport_ (due to one lake tile) even though I have a railroad going to my capital (I've checked several times)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[TRAINSTATION.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7463065/TRAINSTATION.zip)

3. CvMiniDump.dmp file 
(attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/139920720-0822bf1c-08bd-4f65-9d60-34e5518b7b0f.png)

**Comment by azum4roll** [comment]
Is the *shortest* path to the capital all railroads?

**Comment by NewFellow** [comment]
No, it's not. I got a road that is not railwayed and which is shorter - which is intentional since I don't want my caravan to use it.

**Comment by LessRekkless** [comment]
Which road had the city connection? You can check by going into strategic view and then selecting it in the strategic view's map display options (all buttons next to the mini map.

**Comment by RecursiveVision** [comment]
Welp, don't think this is getting fixed.
