### ISSUE TITLE
Capitulation bug: declares war on previous vassal and city states allies

### ISSUE THREAD

**Issue by lalalaprout** [LoneGazebo/Community-Patch-DLL#8376]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_1.1.4

_2. Mod list (if using Vox Populi only, leave blank):_

Civic and Reform v12
Flagpromotion v7
3 units per city
Air Routes
Religious settlers
Improvements - Airbases
Infoaddict
IGE
Really Advanced Setup
Natural wonder epiphany
Unique City states
Wonderrace
World congress reformation

_3. Error description:_ 
I was at war with polynesia, my vassal was assyria and I was allied to several city states. I was able to get Polynesia to offer to make peace and capitulation before capturing their city of Samoa. However, when taking the city of  Samoa, and clicking on Honolulu to talk to them, then I could get them to capitulate (and it didn't say "make peace") but it would put my vassal and allied City states at war with me. If I decline and leave the negociation panel and try to click "negociate peace" again then Polynesia just says that we can't negociate at that time. If instead of clicking on Honolulu I click straight away on their portrait in the civ list, then they straight up don't wont to negociate, which is the expected behaviour. 
SO I guess the bug is: by talking to warring leader through clicking on city, we can get them to negociate capitulation when they otherwise wouldn't want to negociate at all. But the negociation pannel doesn't show "make peace" as a possibility and if you go through with it, it declares war with previous vassals and allied city states. It also doesn't erase CS quests. 
_4. Steps to reproduce (optional):_
unsure. perhaps you have to click on a city (or the capital) to access the diplo pannel and then you can get a buggy capitulation?

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (opti
[bug report.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7470308/bug.report.zip)
onal):

**Comment by RecursiveVision** [comment]
too many additional mods, sorry
