### ISSUE TITLE
Question: What is the formula for citizen conversion made by the inquisitor

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#8379]
_1. Mod version (X.Y.Z, e.g. 1.2.0): 1.1.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:

I knew that all citizens of other religions were converted into yours, but is not longer the case. How is calculated?

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by ilteroi** [comment]
it's a bit different. followers in each city are distributed according to *accumulated* pressure. and the inquisitor by default simply zeros pressure from all other religions. but as always, modifiers may apply.

**Comment by Aqinu** [comment]
I wanted to know how to calculate exactly the final number of citizens before you expand your inquisitor, to see if you get the majority religion or not, cause now the inquisitor gives you fewer citizen converted than before (approx. is something like half the number of citizen with foreign religion + number of citizen of your religion - 2). The enhancer Inquisiton now is much weaker.

**Comment by LessRekkless** [comment]
Inquisitors were changed to only remove half of the other religions' pressure. Also they can't remove atheist pressure, so they will get relatively more followers until pressure builds up again.
