### ISSUE TITLE
Railroads

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#838]
Posted by Aristos:
"Version 11-20: I had to build a railroad inside the city tile to connect the cities to the capital. Same happened for every single city, including the capital." Kaspergm added that CP only causes this, too.

Could this be the cause for the railroad connection issues in the past? I don't think those have been resolved, although they were rare and inconsistent

**Comment by LoneGazebo** [comment]
No, it was something ilteroi accidentally did.

**Comment by ilteroi** [comment]
fixed

**Comment by LoneGazebo** [comment]
Yay! I'll avoid throwing you under the bus...this time. :)
