### ISSUE TITLE
Weird Destroyer Upgrade Path

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#8382]
https://github.com/LoneGazebo/Community-Patch-DLL/blob/d345671cd429de86b37f24507186af890ed1b4ba/Community%20Balance%20Overhaul/Balance%20Changes/Units/NavalUnits.sql#L99
https://github.com/LoneGazebo/Community-Patch-DLL/blob/d345671cd429de86b37f24507186af890ed1b4ba/Community%20Balance%20Overhaul/Balance%20Changes/Units/NavalUnits.sql#L186
https://github.com/LoneGazebo/Community-Patch-DLL/blob/d345671cd429de86b37f24507186af890ed1b4ba/Community%20Balance%20Overhaul/Balance%20Changes/Units/NavalUnits.sql#L13

The I find that the movement rate for the Naval Melee class to be very odd:
```
Trireme         4
Caravel         4
Corvette        4
Ironclad        5
Destroyer       4
Missile Cruiser 6
```
Is there a reason why the Destroyer has lower movement than the Ironclad? Ironclad used to have 3 movement, but double movement in coast but that's long gone.

**Comment by RecursiveVision** [comment]
Looks like an error. Will fix.
