### ISSUE TITLE
Infinite citizens in cities and more...

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#8386]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_
1.1.3

_2. Mod list (if using Vox Populi only, leave blank):_
(ui) City-States Leaders for VP (v 10)
Calypso's Colored Religion Icons (Basic) (v 1)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 
I currently work 27 tiles in a 22 size city + all specialist slots! The trick (cheat:)) is to remove a 'specialist' and have him added to a tile, then lock the citizen to that tile. I then click the specialist again and voilá I work both the tile and the specialist in the city HUAMANGA.

**Not a part of this particular problem (and no save game)**:
In general the city governor acts weird in other ways too. 1) sometimes not assigning laborers to tiles. 2.) I can't click directly on a laborer either to have them automatically assigned to whatever tile (as was possible in the past - when one just clicked the laborer and it was assigned to the most optimal tile). Instead I now need to click the tile to have them removed as laborers. 

City management has been messed up somehow (I feel that I need to have my cities to under constant observation due to this) since these particular problems weren't  in patches in the past. It started when one no longer could 'grab tiles' from _puppets_ (don't know what patch) and assigning them to other cities. After this _change_ (if intentional) the city managment just feels 'off' from time to time and should probably be paid a close look if 'possible' (I don't know coding).

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[INFINITE CITIZENS.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7531173/INFINITE.CITIZENS.zip)

3. CvMiniD
ump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/141600474-ee8085b2-611d-496e-97a7-df69ed1969a4.png)

**Comment by ilteroi** [comment]
cannot reproduce. when all tiles are locked and i create a specialist, a citizen is removed from a tile.

also i can assign laborers to plot with one click on the laborer just fine.

as for the uncalled-for laborers, that may be true (#8378) but hard to reproduce.

**Comment by NewFellow** [comment]
@ilteroi It's very strange, because now I can't reproduce it either, after having saved the game and restarted it. So some kind of special condition has to occur (Perhaps when there were no workable tiles available).

**Comment by Mileslewis** [comment]
I had this occur in a city after I'd reconquered it. Was there some conquering involved here also?

**Comment by NewFellow** [comment]
@Mileslewis No, it happens in my own settled city/cities.

**Comment by NewFellow** [comment]
![image](https://user-images.githubusercontent.com/20144751/141661097-0e85b5cb-206b-4af2-b4b6-eb096522b0ab.png)

Happened right now, can't click that laborer to assign him to a tile. I need to click the tile for him to be assigned.

**Comment by bsesar** [comment]
> Happened right now, can't click that laborer to assign him to a tile. I need to click the tile for him to be assigned.

I see the same behavior in #8378 when using bad_governor save.

**Comment by NewFellow** [comment]
The thing is that this _infinite citizen_ issue, acctually seem to happen every game to my notice.

**Comment by RecursiveVision** [comment]
Possibly related to Improved City View?

**Comment by azum4roll** [comment]
Does that happen only when you've locked every tile you're currently working?

**Comment by Mileslewis** [comment]
> Possibly related to Improved City View?

Happened to me without.
