### ISSUE TITLE
VP UI issues, I believe EUI is not the issue

### ISSUE THREAD

**Issue by JavaBaklava** [LoneGazebo/Community-Patch-DLL#8387]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_
I'm not entirely sure. I was installing different Vox Populi versions to see if anything changed, but the mods screen didn't seem to respond to me deleting and reinstalling earlier VP versions. I believe it's the most current, 1.0.3. The first two screenshots give the versions of the individual components of the mods themselves, I included them in case it helps you determine which version I am running..

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Two issues:

1: There seems to be a major UI issue that I am having where I cannot select units and the EUI does not seem to be responding correctly to the mod The third screenshot shows a base game run without any mods, with the most recent version of EUI. I am also running the most recent version of Civ V. The fourth screenshot shows a game running only the first mod of VP, (1) Community Patch (v. 94). As you can see, the unit icons show up on the main game screen and I can control all of the units actions on the bottom left, but all of the buttons in the top right seem to be broken, showing only one button. The fifth screenshot shows a game running with only the first two mods of VP, (1) Community Patch (v. 94) and (2) Community Balance Overhaul (v. 13). As you can see, the unit icons disappear from the main game screen, and the buttons return to the BNW state without the EUI. I also have no control over the units. I can't right click to move them, and I can't left click to bring up the unit window in the bottom left of the screen. Considering that neither of these mods have EUI or non-EUI versions, I think it's safe to say that this issue is EUI-agnostic.

2. A side issue that I noticed trying to diagnose this problem is occasionally if I run the game with just the first mod (1) Community Patch (v. 94), it would crash. I didn't have any issues running it with the second mod (2) Community Balance Overhaul (v. 13). I don't know if the issue will persist if I run the full suite of VP mods.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
4. 
4. Screenshots (optional):
![20211112225524_1](https://user-images.githubusercontent.com/94213733/141607831-4cfa8979-b4c7-4edd-b0c0-9ad3d608ef3f.jpg)
![20211112225529_1](https://user-images.githubusercontent.com/94213733/141607832-eaac9bb0-b749-459b-b40a-da3427a17785.jpg)
![20211112225547_1](https://user-images.githubusercontent.com/94213733/141607841-ec5f695c-2a3e-420e-82cf-b8346829236e.jpg)
![20211112225755_1](https://user-images.githubusercontent.com/94213733/141607843-cd94d760-a871-495f-9136-c97acf2fd3a9.jpg)
![20211112225908_1](https://user-images.githubusercontent.com/94213733/141607844-65fc21cb-6068-4761-a0df-8b32d51348cc.jpg)

**Comment by RecursiveVision** [comment]
1) The latest version is 1.1.4.

2) VP isn't compatible with the latest EUI. You must install VP with EUI in the installer, which overwrites any existing installation of EUI. You cannot use the non-EUI version with the latest EUI.

You can blame bc1 for this, as they insisted we use a complicated way of installing EUI which made it difficult for us to keep up with updates, and as such we use an old customized version that is several years out of date (yet functional for our purposes). While in theory we could legally ignore bc1's wishes, Gazebo wanted to avoid the conflict.

3) Non-EUI has several UI issues, but no one is both skilled and motivated enough to work on the UI at the moment.

4) This situation is unlikely to change in the near future. Eventually, it would be nice to have the latest EUI, but it's a ton of work and bc1 changed EUI's variables and structure a lot.
