### ISSUE TITLE
Trade screen issues

### ISSUE THREAD

**Issue by radziu93** [LoneGazebo/Community-Patch-DLL#8388]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_
1.0.3(latest downloadable from the forum)

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Everything NPC has to offer cannot be visible in the trade screen. I can click to add things into trade screen, and according to NPC answers, goods and other stuff can be indeed proposed to trade, but main trade window stays empty all the time and 'clicked' object doesn't dissappear from the list. If I'm putting my coins or luxuries, somehow it remain visible. Everything else (like embassy,defensive pacts, open borders) is invisible. Also if I try to put NPCs luxuries or coins, they remain invisble too. If NPC proposes any deal, everything is always invisible. 

Honestly I feel kinda annoyed, as this basically means game is unplayable and I remember seeing similar bugs reported many months ago, and purposelly waited a long time for newer versions to come out and since those issues dissapeared from there, I assumed error was fixed. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7532624/Logs.zip)
2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change 
[error_save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7532618/error_save.zip)
autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Are you using EUI and if so are you using the latest version or the one that comes with VP?

**Comment by radziu93** [comment]
I made full installation when I downloaded VP, but the bug is there even if I run game with community patch only (just checked to be sure)

**Comment by RecursiveVision** [comment]
@radziu93 Please enable logging, reproduce the issue, and then attach your Lua.log file.

https://github.com/LoneGazebo/Community-Patch-DLL#to-enable-logging-for-bug-reports

**Comment by radziu93** [comment]
Oh, sorry, I didn't enable logging earlier. Here is lua log with new save. 
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/7549659/Lua.log)
[ErrorSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7549651/ErrorSave.zip)

amd also rest of logs if needed

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7549647/Logs.zip)

**Comment by RecursiveVision** [comment]
```
[346817.515] DiploTrade: PocketAllowEmbassyHandler
[346817.515] Runtime Error: Assets\DLC\Expansion2\UI\InGame\WorldView\TradeLogic.lua:1359: attempt to call method 'IsTradeAgreementTradingAllowed' (a nil value)
[346818.625] DiploTrade: PocketAllowEmbassyHandler
[346818.625] Runtime Error: Assets\DLC\Expansion2\UI\InGame\WorldView\TradeLogic.lua:1359: attempt to call method 'IsTradeAgreementTradingAllowed' (a nil value)
```

The modded TradeLogic.lua is missing from your installation.

**Comment by radziu93** [comment]
Great, but how do I fix it? As I said, I did full instalallation from the file from the forum. I do have few other smaller mods, but all of them are disabled and yet the error is still there. Reinstalling also doesn't help.
