### ISSUE TITLE
Your civ name for a foreign spy notification

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#8389]
_1. Mod version (X.Y.Z, e.g. 1.2.0): 1.1.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: a Greece spy... 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0000(1)](https://user-images.githubusercontent.com/49090452/141682549-ba5ac85c-c4a2-4533-bcfd-c385b40b0c62.png)

**Comment by RecursiveVision** [comment]
Duplicate
