### ISSUE TITLE
celts building missionaries but not using them

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#839]
![image](https://cloud.githubusercontent.com/assets/1358966/11452819/8a0e3d40-95f4-11e5-8c29-2de96a519fd9.png)

this seems to be because they don't want to spread their fancy beliefs to somebody else. but then they should spend their faith on something else instead?

ps: it doesn't seem the AI knows how to garrison an inquisitor either

**Comment by LoneGazebo** [comment]
Odd. The AI shouldn't be building missionaries as the Celts. I'll take a look. 

Also inquisitor logic is rough, yep.
