### ISSUE TITLE
AI units move much farther than they should be able to

### ISSUE THREAD

**Issue by Thurhame** [LoneGazebo/Community-Patch-DLL#8391]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_
I used the version 1.0.3 installer from https://drive.google.com/drive/folders/1C4EUItogZx-3XpkzyPA52WLaDSWZqxVZ, but for some reason Civ lists it as version 0.94:
![Mod version](https://user-images.githubusercontent.com/94323640/141700456-7beedc81-f7bb-4089-b40d-cb5e8629b028.jpg)

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch ai and bugfix mod only.

_3. Error description:_ 
An AI Knight and Musketman both crossed several forested hills to reach and kill a wounded unit I had retreated.
![Civ5 CP ai movement bug](https://user-images.githubusercontent.com/94323640/141700479-91a71761-086b-4126-a67d-3412a43dc767.png)

_4. Steps to reproduce (optional):_
Load save and click end turn, then watch enemy movements:
[Bug Report Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7534784/Bug.Report.Save.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LessRekkless** [comment]
It looks like the Iroquois, who use forests as roads, used forests as roads to attack your unit.

**Comment by Thurhame** [comment]
> It looks like the Iroquois, who use forests as roads, used forests as roads to attack your unit.

According the Civilopedia, they only use forests _in friendly territory_ as roads. Neither the hexes belonging to Antananarivo (who is my ally and at war with the Iroquois), nor the neutral hex the knight crosses a river to reach, should count as roads based on that description.

**Comment by Thurhame** [comment]
> Show us the promotions of those two units.

How do I do that? I can't select enemies, and even if I target them for a combat preview it disappears when I move the mouse, so I can't hover over the promotion icons to see what they are.

![20211114174238_1](https://user-images.githubusercontent.com/94323640/141701665-7f69cdc0-f518-4bfb-b590-131d5769a94f.jpg)
![20211114174240_1](https://user-images.githubusercontent.com/94323640/141701666-74076141-ac61-4167-9d10-fce44a18c1ae.jpg)

**Comment by RecursiveVision** [comment]
In full VP, the Iroquois treat all forests and jungles as roads, even those outside their territory. I'll correct the text.

**Comment by LessRekkless** [comment]
Recursive, unless there's something specific that I can't find, the main change is that all units gain Woodsman and that's it. That's not the quite same as treating forests as roads.

**Comment by LessRekkless** [comment]
Ah, @RecursiveVision : Thurhame isn't playing with VP, he's only playing with the AI patch. Should the relevant movement code be behind an if statement with regards to Balance changes?

**Comment by Thurhame** [comment]
> In full VP, the Iroquois treat all forests and jungles as roads, even those outside their territory. I'll correct the text.

I'm not using VP, only the basic ai/bugfix patch that supposedly doesn't change any game mechanics.

**Comment by ilteroi** [comment]
i fixed this for city connections but apparently i forgot about unit movement.

**Comment by RecursiveVision** [comment]
@ilteroi fix awaited then :)

also I merged #8373 as you didn't respond but let me know if there's an issue with it

**Comment by RecursiveVision** [comment]
@LessRekkless Road movement + Woodsman is intended, see their trait.

**Comment by RecursiveVision** [comment]
> > In full VP, the Iroquois treat all forests and jungles as roads, even those outside their territory. I'll correct the text.
> 
> I'm not using VP, only the basic ai/bugfix patch that supposedly doesn't change any game mechanics.

@Thurhame There are small game mechanic changes (e.g. No More Civilian Traffic Jams). However some bugs have crept in and there are surely a few unintended balance changes in the code. Since not that many players play CP only we rely on bug reports to fix them.

**Comment by Thurhame** [comment]
Thank you
I really enjoy the interface qol fixes in CP, so I'm glad this issue is resolvable.


> @Thurhame There are small game mechanic changes (e.g. No More Civilian Traffic Jams). However some bugs have crept in and there are surely a few unintended balance changes in the code. Since not that many players play CP only we rely on bug reports to fix them.

Is there a list of the intended changes for reference?

**Comment by LessRekkless** [comment]
@Thurhame my only remaining question is: 
did the musketman in your screenshot moved  _over_ the river and then attack in the same turn? Or did it end its turn there?

**Comment by Thurhame** [comment]
> @Thurhame my only remaining question is: did the musketman in your screenshot moved _over_ the river and then attack in the same turn? Or did it end its turn there?

If you mean the knight, yes it moved over the river and then attacked. I assume Bridge Building applied to the fake road. (The musketman attacked directly over the river, so it doesn't count for your question.)
