### ISSUE TITLE
[1.1.4] There is something wrong with Future Tech and the science counter

### ISSUE THREAD

**Issue by MoreFirepower** [LoneGazebo/Community-Patch-DLL#8397]
Important to reproduce bug: Load save game and **set research to Future Tech first**.

Then when you spend gold for a building, you get two Future Techs. If you spend gold for another building (in another city), you get two more Future Techs. And so on.

[AutoSave_1179 AD-1995-October.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7575515/AutoSave_1179.AD-1995-October.zip)

**Comment by RecursiveVision** [comment]
It overflowed to a negative value :)
