### ISSUE TITLE
kidnap specialists

### ISSUE THREAD

**Issue by AndreyK-555** [LoneGazebo/Community-Patch-DLL#8398]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ kidnap specialists spy event still don't expire

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
[Ramkhamhaeng_0320 AD-1500.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7585863/Ramkhamhaeng_0320.AD-1500.zip)

**Comment by RecursiveVision** [comment]
save file needed

**Comment by AndreyK-555** [comment]
here is
[Ramkhamhaeng_0340 AD-1600.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7585871/Ramkhamhaeng_0340.AD-1600.zip)

**Comment by AndreyK-555** [comment]
This was an issue that I opened before and G said was fixed for September version so I didn't include a list of modmods I use and there are quite a number. I think it doesn't depend on modmods, because I seen a number of people mention it.
My modmods are -RAS, IGE, (overhaul) SMAN's Duchy of Brittany, Leugi's Israel for VP, Sukritact's Khmer, MC's Greece and Macedon Split, Granary includes Bison, Quick turns, Wonder Race, RemoveBanLuxury, TreeGrowth (VP) (v 2), pdansPowerPlants, MUCfVP, EE, More Wonders for VP, EAW, ENW, Monopoly Buildings for VP, Better lakes for VP, Corsica for VP, Sky Resort for VP, Sixth Policy for VP, Cemetery building, Parks for VP, Casino, GMO Laboratory, Polar station, Recruitment office, Clock Tower, Reforestation, Improved City View, Capture Great People
![8930_20211123140341_1](https://user-images.githubusercontent.com/61764413/142974899-10c72759-04db-4b89-92ac-1ef898cb3eac.png)

**Comment by azum4roll** [comment]
Can confirm it's still happening.

**Comment by RecursiveVision** [comment]
Duration wouldn't tick down unless Events were enabled
