### ISSUE TITLE
City States only building melee ships

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#840]
Starting around the industrial era, I've noticed that all the city states are building only melee naval units. No ranged ships and no land units (melee or otherwise). They'll have like 5 or 6 Corvettes but nothing else despite constantly getting invaded by land from major civs.

**Comment by oalzubbi** [comment]
Here's some screenshots. This game is on Huge Map, King (lvl 5 difficulty) with just CPB with EUI and In Game Editor.

![image](https://cloud.githubusercontent.com/assets/13261433/11458828/e3ada64e-968d-11e5-92d3-ce531449d31d.png)

![image](https://cloud.githubusercontent.com/assets/13261433/11458830/f2af63f8-968d-11e5-9a1e-e646b6a681b9.png)

![image](https://cloud.githubusercontent.com/assets/13261433/11458834/fe098be8-968d-11e5-8bcc-5a9623ad2c0e.png)


![image](https://cloud.githubusercontent.com/assets/13261433/11458843/1f4b2816-968e-11e5-89db-bd9b2798cf97.png)

![image](https://cloud.githubusercontent.com/assets/13261433/11458851/33a7a000-968e-11e5-8454-75f3eda7b7c2.png)

**Comment by LoneGazebo** [comment]
ranged ships require strategic resources, which are taken away from CSs when you ally them. In fact, I don't think CSs can use strategic resources at all, and post-medieval ranged ships require SRs.

**Comment by oalzubbi** [comment]
They can't use any strategic resources ever? Not even horses or iron? I could have sworn I've seen City States with swordsmen and horsemen...  
Regardless, the city states are still not building basic land units like machine guns or infantry which require no strategic resources.

**Comment by LoneGazebo** [comment]
So what are they building?

**Comment by Edaka** [comment]
I've just had a game where a cultural city state built its very first military unit, a spearman, on turn 95. Up until that point it had no military. I attacked that city state and destroyed the spearman. It was after that moment when I think I saw a colosseum model appear in the city. A replacement military unit only appeared on turn 112 - it was a trireme against my 3 spearmen and 2 composite bowmen.

**Comment by LoneGazebo** [comment]
Hmm...

**Comment by LoneGazebo** [comment]
addressed CS limited unit issue
