### ISSUE TITLE
New built units must wait a turn until action

### ISSUE THREAD

**Issue by tojothethief** [LoneGazebo/Community-Patch-DLL#8402]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_
1.2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When you finish building a unit, said unit must wait a turn until being able to perform actions, just like gold purchased (few exceptions aside) units.
I assume this is an unintentional side effect of the new code changes?

_4. Steps to reproduce (optional):_
Build a unit

**Comment by ilteroi** [comment]
uh, my bad ... will fix later

**Comment by RecursiveVision** [comment]
ty...also I'd recommend pulling from master :)
