### ISSUE TITLE
Border growth points do not get added in calculation of next border growth for city (only raw culture does)

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8404]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_
1.2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
For example when using the Celts pantheon that gives +3 Border growth points, it does not get added to the culture to calculate the remaining turns of the next border growth. Forts are also affected.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![](https://i.imgur.com/MZBhhU3.png)
Should say 5 turns remaining: (1 culture + 3 BGP -> 20/4 = 5)
![](https://i.imgur.com/JoXmvHg.jpeg)
This is true for both the Pantheon and forts
![](https://i.imgur.com/uOxfFaU.jpeg)

**Comment by Mileslewis** [comment]
It is correct after you end turn though right?

**Comment by maarten99** [comment]
Yes the BGP helps grow the border, just the UI isn't showing the right turns until growth

**Comment by pineappledan** [comment]
This has been a known issue for years. It was less of an issue back then, because BGPs were not as common

Well, the city screen is correct, sort of, in that BGPs are not culture. You'd have to have a separate line item for BGPs. 
Though it would be nice if BGPs were factored into that turn calculation.

**Comment by LoneGazebo** [comment]
Pretty sure the code includes BGP for that UI element, but I'll look.
