### ISSUE TITLE
Authority policy completion bonus "Yields from Tribute policy doubled" does not work/ does not double/change the rewards

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8407]
_1. Mod version (X.Y.Z, e.g. 1.2.0):_
1.2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
From the description it's not clear whether the effect of the border growth yield and the tributing from City State should be doubled, but they BOTH do not get doubled.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
Bonus in question:
![](https://i.imgur.com/yQ9fSMX.png)
![](https://i.imgur.com/NWBHLHF.png)
Before Authority completion:
![](https://i.imgur.com/0WEzWp8.jpeg)
![](https://i.imgur.com/O2wB6G7.png)
After Authority completion (reloaded turn and gave policies with IGE):
![](https://i.imgur.com/GXOk4eY.png)
![](https://i.imgur.com/rziWJz3.jpeg)
![](https://i.imgur.com/kAUkIjU.jpeg)

Bonus from border growth also isn't doubled:
![](https://i.imgur.com/Brmpu32.jpeg)
![full policy tree](https://i.imgur.com/sk0Q5oL.jpeg)

**Comment by RecursiveVision** [comment]
Works for me
