### ISSUE TITLE
expansion warnings

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8409]
i just settled adwa and got an expansion warning from the aztecs (expected) but also from austria (rather unexpected)

is this intended with the new logic in v1.2?

![image](https://user-images.githubusercontent.com/1358966/143093975-d3a4eaa1-4cef-471d-ac38-ef88360ae20f.png)

**Comment by RecursiveVision** [comment]
@ilteroi Yeah, it's a flat 6-8 tile range depending on Boldness and the leader's UA. Adwa is 7 tiles away.

You can see the new logic in CvDiplomacyAI::DoExpansionBickering(), and it's much, much simpler. Open to tweaking it, though. In this case, perhaps a check to see if the new city is closer to your capital than it is to their city.

**Comment by ilteroi** [comment]
haha, it will become complex in no time

**Comment by RecursiveVision** [comment]
lol, let's hope not, I had enough trouble understanding the last version :)

**Comment by RecursiveVision** [comment]
added the check, also reduced "bicker range" by 1 tile across the board, let's see how this works
