### ISSUE TITLE
Method city:GetGarrisonedUnit() no longer working

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#841]
I've tested this with no other mods but the CP (26/11 beta) and the method city:GetGarrisonedUnit() appears to no longer work - it should return the object ID of the military unit stationed in a city, however, it simply returns nil no matter the unit. Disabling CP remedies the issue.

**Comment by LoneGazebo** [comment]
Huh. I'll check. Also, look at the getgreatwork event again, see if it works.
G

**Comment by LoneGazebo** [comment]
Oh, ilteroi changed this. I'll message him.

**Comment by JFDaly** [comment]
Thanks. Planning to, once the downloads for the beta work.

**Comment by ilteroi** [comment]
d'oh. looks like you beat me to the fix. m_hGarrisonOverride not initialized? i wonder if we should remove it, nobody's using it anyways ...

**Comment by LoneGazebo** [comment]
I just rewrote the lua grab to bypass all that, so the two functions are no longer linked. You can do what you want with it. :)
G
