### ISSUE TITLE
Japan's Dojo isn't giving bonus yields when promoting units.

### ISSUE THREAD

**Issue by knml15** [LoneGazebo/Community-Patch-DLL#8412]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_

Vox Populi (1.2.1)

_2. Mod list (if using Vox Populi only, leave blank):_

3rd and 4th UC

_3. Error description:_ 

Japan's Dojo doesn't give culture and science when promoting units created from that city.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by nobubblegums** [comment]
Can confirm, PROMOTION_BUSHIDO probably needs entries under UnitPromotions_InstantYields . I'm not sure if that makes them scale with unit level as the text states though

**Comment by ridjack** [comment]
Also confirming, and adding on that this was working properly in the previous major version.
