### ISSUE TITLE
Possible bug from unit fix in 1.2.1: Buying missionaries allows them to move on the same turn

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8416]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_
1.2.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Previously it was intented that you could not move missionaries the same turn that you buy them.
There was a fix in 1.2.1 for no units being able to move after getting built.
This should be fixed if the intention is to still not allow missionaries to perform actions on the turn they are bought.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bsesar** [comment]
The fix you talk about was used to address issue #8402. @ilteroi?

**Comment by ilteroi** [comment]
hmm, it seems faith purchases use the REASON_TRAIN flag and not REASON_BUY.

no idea why. is this a plain bug or is there a deeper reason here?

**Comment by RecursiveVision** [comment]
I think it's a plain bug.

**Comment by ilteroi** [comment]
ah yes, another unnecessary rule that the AI and 90% of players know nothing about

**Comment by bentakacs** [comment]
> ah yes, another unnecessary rule that the AI and 90% of players know nothing about

I kinda have to agree with ilteroi here. Is the half XP for purchased units really necessary?

**Comment by RecursiveVision** [comment]
Hey, I didn't come up with it. Talk to @LoneGazebo lol

**Comment by RecursiveVision** [comment]
I decided to open a community poll about it: https://forums.civfanatics.com/threads/poll-should-we-keep-gold-purchased-units-start-with-half-xp.674310/

**Comment by RecursiveVision** [comment]
> ah yes, another unnecessary rule that the AI and 90% of players know nothing about

29-1 in favor of keeping, also I should note that the 50% reduction is mentioned in the unit tooltips, so many players are aware of it. Likewise it's currently 2.6x as many people in favor of keeping Faith purchases as is due to Faith's rarity compared to Gold.

I also proposed nerfing Zealotry in the past and the vote was something like 30-0 so I don't think that one would be popular.

I think that disproves both the "unnecessary" and "unknown by 90% of players" points. 

A fair point that the AI may need to be taught, though.

**Comment by RecursiveVision** [comment]
Now uses REASON_FAITH_BUY
