### ISSUE TITLE
Incorrect tooltip shown for the worker (tooltip of the previously selected unit)

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#8420]
1. Mod version (X.Y.Z, e.g. 1.2.1): 1.2.1

2. Mod list (if using Vox Populi only, leave blank):

3. Error description: The tooltip for the worker shows the tooltip of the previously selected unit.

4. Steps to reproduce (optional): Load the attached save, click on the war chariot near Bogota, check out its tooltip (see the screenshot below)

![war_chariot_tooltip](https://user-images.githubusercontent.com/620131/143678661-8f33789e-53dd-4f53-a86a-9a408c6b7dee.jpg)

Then click on the worker near Memphis and check out its tooltip (see the screenshot below). The tooltip shown is for the previously selected unit (i.e., the war chariot).

![worker_tooltip](https://user-images.githubusercontent.com/620131/143678702-3aabe958-7fe1-420a-b85c-f937868e8bf8.jpg)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu): [bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7611619/bug.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LoneGazebo** [comment]
that's a UI error - any errors in your lua.log?

**Comment by bsesar** [comment]
Good to have you back, @LoneGazebo! :-)

Yes, there are lines like this

```[172421.171] Runtime Error: C:\Users\XXX\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Vox Populi - Compatibility Files (EUI)\LUA\UnitPanel.lua:598: bad argument #1 to 'GetNumResourceRequiredForRoute' (number expected, got nil)```

Here are all the logs: [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7953678/Logs.zip)
