### ISSUE TITLE
Venetian puppets circumventing building requirements for unit purchases.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#8426]
1.2.1 

![image](https://user-images.githubusercontent.com/22875626/143787263-1bc3cbab-a479-44da-ab77-13a6ceee8931.png)

This issue does not exist in the capital.

**Comment by nobubblegums** [comment]
I think I've figured this out while going over the investment code, will push after testing a bit.

**Comment by RecursiveVision** [comment]
Looks intentional?
