### ISSUE TITLE
Corporate franchise limit is 3

### ISSUE THREAD

**Issue by james-norcross** [LoneGazebo/Community-Patch-DLL#8427]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_1.21

_2. Mod list (if using Vox Populi only, leave blank):_
Alternative Difficulty for VP (v 10)
Ingame Editor (v 39)
(over) More Unique Components for VP (v 74)
_3. Error description:_ 
Every corporation in the game has only 3 franchises at least 50 turns after founding

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by PerfectDark99** [comment]
Can confirm. Can't make any more franchises.
