### ISSUE TITLE
Settlers can't found a City

### ISSUE THREAD

**Issue by leodominiscki** [LoneGazebo/Community-Patch-DLL#8429]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_

1.0.1 and the same error when I try 1.0.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

If using all the Vox Populi mods, 2 seconds after the game starts, the game over screen appears and finish the game.
If not using the 7 and 5 mods, the game starts, but the button to found city in the settlers is missing, also, the AI cannot found cities  either.

NOTES:

- I am not using STEAM, my downloads were all manual.
- My civ 5 version is 279
- I've already tried clearing cache, reinstall the game, reinstall the vox populi, and tried with and without EUI. The same problem every time.
- I am not using another Mod, just VP

**Comment by RecursiveVision** [comment]
Firstly you'll want to use the latest version (1.2.1)
