### ISSUE TITLE
[v1.2.1] Honor does not spawn units near cities that have already reached 10+ citizens

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#8430]
Title says it all. No units are spawn when choosing the Honor policy (Authority).

Savegame just before selecting Honor
[Ramesses II_0376 AD-1732.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7618610/Ramesses.II_0376.AD-1732.zip)

Additional mods : RAS
.

**Comment by RecursiveVision** [comment]
Works for me
