### ISSUE TITLE
AI values the strategic resources of others too low

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8432]
1.2.1
They value their own strategics at an appropriate value, but heavily undervalue those of other players (including AI it seems, since they don't trade strategics that often).
Examples:
Askia valuing horses at 10 gold, even though he has none:
![](https://i.imgur.com/LlNeIKI.jpeg)

Austria when we both have horses:
![](https://i.imgur.com/QmRP3QP.jpeg)
![](https://i.imgur.com/hItLoZl.jpeg)

When she has a deficit (-1 Horse) (by giving her Horse units with IGE) it is somewhat valued more fairly, but still too low:
![](https://i.imgur.com/DSgKLdw.png)

**Comment by maarten99** [comment]
There seems to be an even bigger difference between Player vs other AI:
Arabia wants 250 gold for horses, the next turn he gives away all his horses (4) for an embassy to another AI.
![](https://i.imgur.com/EY4GokP.png)

IGE take seat as Arabia:
![](https://i.imgur.com/BX1KYVJ.jpeg)

**Comment by PerfectDark99** [comment]
I can confirm this. AI keeps asking for 4 coal for 1 GPT. And not just one of them. all of them.

**Comment by nobubblegums** [comment]
I'm getting this too
