### ISSUE TITLE
CTD with larger than huge map sizes

### ISSUE THREAD

**Issue by dostillevi** [LoneGazebo/Community-Patch-DLL#8433]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_
1.2.1

_2. Mod list (if using Vox Populi only, leave blank):_
Many mods installed, only VP enabled with EUI.

_3. Error description:_ 
Before the most recent patch, I was able to use Communitu_79a maps sized at 200x150 without issue. After installing the latest version, my game crashes as soon as the leader screen appears during game generation. The land percent ratio may be a factor in this, but it's inconclusive in my testing. I found the following:

150x100x.31 = : Loads without issue. No crashes. 15000 tiles, 4650 land tiles.
160x 108x.31: Loads but takes a few minutes (3m avg). No crashes. 17280 tiles, 5356.8 land tiles.
160x108x.54: Crashes most of the time, but occasionally loads. Map creation time varies from 3m to 10m before success or crash. This is the same number of land tiles, roughly, as 200x150x.31 that I used to play on. 17280 tiles, 8812.8 land tiles.
200x150x.31: the map size I used all the time previously. Always crashes, but time to crash varies as above. 30000 tiles, 9300 land tiles. 

I also tested 160x108x.54 with just two AI and still crashed, so I think the issue is more to do with the land tiles than with the number of civs in game.

_4. Steps to reproduce (optional):_
Edit Communitu_79a to change the huge map size to 200x150 and change the land percent to .31. Load a normal huge game using advanced setup, and wait for the game to crash.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7622557/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7622561/CvMiniDump.zip)

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/39426657/143976473-d55e1947-1eaa-4339-b758-9eff338bd2c8.png)

**Comment by dostillevi** [comment]
I’m pretty sure this had something to do with a recursive formula run in land tiles, where larger tile sets could result in land shapes that led to huge memory utilization due to recursion. I think that would account for the variability on a given map size and land tile ratio.

**Comment by IanE9** [comment]
If you're able to determine on what patch and with what version of Communitu this was working I may be able to do something, but I tried running without any mods other than the Communitu map script and it crashed in the same way so this is likely a bug in the engine.
