### ISSUE TITLE
Reformation belief granting yields incorrectly

### ISSUE THREAD

**Issue by 1andUnly** [LoneGazebo/Community-Patch-DLL#8434]
_1. Mod version (X.Y.Z, e.g. 1.2.1): 1.2.1

_2. Mod list (if using Vox Populi only, leave blank):

_3. Error description: Siam spread to me and reformed with Divine Teachings, yet I receive faith after expending a GP. Text states only the holy city is to receive yields. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional)
![Screenshot (902)](https://user-images.githubusercontent.com/59460164/143987685-0fa5efa8-5c54-458a-a925-4089ac8989ff.png)
![Screenshot (901)](https://user-images.githubusercontent.com/59460164/143987702-49dbdcd0-b59b-434a-a8c1-e4cde55bf1ce.png)
:

**Comment by maarten99** [comment]
That is the correct amount if you are in Renaissance era
"scaling with era" means 100% in Ancient/Classical, 200% in Medieval, 300% in Renaissance and so on

**Comment by RecursiveVision** [comment]
Religion code was cleaned up, make a new issue if reproduced in next release
