### ISSUE TITLE
Issues with Shoshone Goody Hut Selection

### ISSUE THREAD

**Issue by JigglySK** [LoneGazebo/Community-Patch-DLL#8437]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_ Version 1.21

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Scouts do not offer all selection options, leaving out Faith option in particular. The faith option seems to randomly be available after a handful of turns in some games and then not at all in others. Also, the option to upgrade a second time from scout to explorer was not showing up, even after multiple goody huts have cycled. I think there is some weird interplay in the goody hut options when multiple scouts are getting goody huts within the same game.  

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"): [Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/7629557/Lua.log)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu): Said it doesn't support file type when I tried to drag

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by dostillevi** [comment]
The prophet is deliberately left out of options until after a pantheon (or maybe) religion is founded. Can't remember which, but it's deliberate to avoid giving the shoshone a super early religious head start.

**Comment by RecursiveVision** [comment]
@JigglySK Can't upgrade a unit more than once from Ruins, can't get Faith ruins until Turn 20 (IIRC).
