### ISSUE TITLE
Cities don't experience unhappiness from not being connected to capital

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#8441]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_
1.2.1

_2. Mod list (if using Vox Populi only, leave blank):_
(over) More Unique Components for VP (v 74)
(ui) City-States Leaders for VP (v 10)
Calypso's Colored Religion Icons (Basic) (v 1)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 
None of my cities has ever experienced any unhappiness from being disconnected from my capital.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[NO UNHAPPINESS.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7651418/NO.UNHAPPINESS.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/144648256-bc187dde-596e-4946-9440-a115ee42b2b6.png)

**Comment by maarten99** [comment]
Your city is at max unhappiness, you don't see all the unhappiness because it is capped at city population + urbanization sources

**Comment by Mileslewis** [comment]
Trade routes to/from that city will also get rid of that unhappiness
