### ISSUE TITLE
Industry policy don't give 100% building windmill etc.

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#8443]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_
1.2.1

_2. Mod list (if using Vox Populi only, leave blank):_
(over) More Unique Components for VP (v 74)
(ui) City-States Leaders for VP (v 10)
Calypso's Colored Religion Icons (Basic) (v 1)
UI - Filters in Trade Route Overview (Vox Populi) (v 1.3)
UI - Improved City View (Vox Populi EUI) (v 11.0)

_3. Error description:_ 
Division of labor don't give 100% when building the affected buildings.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[NO 100.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7653866/NO.100.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by nobubblegums** [comment]
That policy only gives production towards Trainstations and Seaports though. Windmill etc. generate +3% production or gold with it.

**Comment by NewFellow** [comment]
Hahaha, my bad. I didn't read it carefully enough.

**Comment by nobubblegums** [comment]
The text is confusing though, I had a hard time when I first read it too. Maybe it would be better if it's formatted like this : 
"[COLOR_POSITIVE_TEXT]Division of Labor[ENDCOLOR][NEWLINE]+100% [ICON_PRODUCTION] Production speed of Train Stations and Seaports. _+3% [ICON_PRODUCTION] Production and [ICON_GOLD] Gold generated by Forges, Windmills, Workshops, Factories, Train Stations, and Seaports_."

**Comment by RecursiveVision** [comment]
Clarified text for next version
