### ISSUE TITLE
Cannot build naval units in a city connected to the sea via a Fort

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#8445]
1. Mod version (X.Y.Z, e.g. 1.2.1): 1.2.1

2. Mod list (if using Vox Populi only, leave blank):

3. Error description: Thebes is connected to the sea via a Fort built on a Flood Plains, River tile but I still cannot build any naval units. Perhaps related to #8439?

![cannot_build_a_work_boat](https://user-images.githubusercontent.com/620131/144721106-4a432716-04d4-4e68-89af-7ada90661924.jpg)

4. Steps to reproduce (optional): Load the attached save, [no_boat.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7654461/no_boat.zip).
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by maarten99** [comment]
cities need a body of water next to them to build naval units, I don't think this is a bug

**Comment by bsesar** [comment]
I thought that having a connection is good enough, but I guess I was wrong. Closing the issue.

**Comment by RecursiveVision** [comment]
Yep that's right
