### ISSUE TITLE
AI still fails to finish roads

### ISSUE THREAD

**Issue by NewFellow** [LoneGazebo/Community-Patch-DLL#8446]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_
1.2.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm conquering Sweden and I find that the roads are not properly finished (prioritized perhaps) 1000 a.d. and still there is this square between stockholm and helsinki that hasn't been finished. Also one square between Stockholm and Sigtuna.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/20144751/144727262-575070e9-0d0c-43ed-9e04-c771e752981a.png)

**Comment by Plockets** [comment]
I have noticed this also, but it seems only with coastal cities, so perhaps the AI decides the road isn't worth building if there is already a city connection with the Lighthouse?

**Comment by ilteroi** [comment]
does not seem to be a common issue ... i don't see this at all
