### ISSUE TITLE
Starting co-op war in 10 turns with 1 civ then some turns later with another civ causes the second civ to declare on the same turn as the first civ/agreement 

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8447]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_
1.2.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_
1. Co-op war with civ 1 (Russia) choose option "in 10 turns"
2. Wait some turns (less than 10)
3. Start co-op war with 2nd civ (Mongolia) against the same civ (Assyria) and also choose "in 10 turns"
4. 10 turns after the first agreement (with Russia) both Civ 1 (Russia) and Civ 2 (Mongolia) declare war on the same turn

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![](https://i.imgur.com/N9JkdLQ.jpeg)

**Comment by RecursiveVision** [comment]
When one civ in the agreement goes to war, the others do too.
