### ISSUE TITLE
Feature Request: additional info in the "Establish Trade Route" window

### ISSUE THREAD

**Issue by Radost** [LoneGazebo/Community-Patch-DLL#845]
Namely the tags, or whatever the franchise indication is called, for influence and UA-related bonuses (such as Morocco) and filtering by influence.

**Comment by LoneGazebo** [comment]
Which Window? The main trade destination selection one?

**Comment by Radost** [comment]
This one
![clipboard01](https://cloud.githubusercontent.com/assets/1131228/11458328/6f3e8844-96df-11e5-87c9-d0a3594de3d4.png)
