### ISSUE TITLE
pagodas and/or tooltip bug

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#8455]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_

1.2.1

_2. Mod list (if using Vox Populi only, leave blank):_

InfoAddict (v 22)

_3. Error description:_ 

Pagodas give 2 yields per religion, but are supposed to give 1.
Tooltip is also confused by it.

![image](https://user-images.githubusercontent.com/4227288/145132031-69eb392e-06b7-4924-9ff8-3663be3e5f63.png)

**Comment by gamask** [comment]
Actually seems like different yields get different amounts.
Culture: 2 from monument + 1 from pagoda = 3
Science: 1 from pagoda, but total somehow = 2
Commerce: 2 from pagoda
Faith: +2 from pagoda's built-in bonus, +1 from monument, +1 from pagoda's per-religion bonus = 4

Definitely something wonky here.

**Comment by RecursiveVision** [comment]
GetBaseYieldRateFromReligion() is functioning properly.
