### ISSUE TITLE
wacky interactions between workable tiles and enemy units

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#8456]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_

1.2.1

_2. Mod list (if using Vox Populi only, leave blank):_

InfoAddict (v 22)

_3. Error description:_ 

There are all sorts of whacky issues.

Here's one.
When I let the governor select tiles to work, I'm able to work tiles blocked by enemy units.
This screenshot doesn't show anything interesting, it's just for comparison with the next one.
![image](https://user-images.githubusercontent.com/4227288/145135316-bd88f69c-0e5e-4b32-bed3-9766adb82bc7.png)

As soon as I try to lock one of the tiles that's occupied by the enemy, this happens:
![image](https://user-images.githubusercontent.com/4227288/145135342-21f2577d-5ad1-4ac5-bd17-d534a068b56b.png)

I also had this happen:
1. barb blocks tile
2. next turn I kill barb
3. I can NOT immediately assign a citizen to this tile after killing the barb. I have to wait till next turn

There were several other whacky situations for which I don't remember the details.

**Comment by gamask** [comment]
In the screenshot I'm also using these mods:
Promotion Flags EUI for VP (v 3)
InfoAddict (v 22)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 1.2)

I started the game with only infoaddict and added the other mods later.
Weird things were already occuring before I did that.

**Comment by ilteroi** [comment]
hmm. will check
