### ISSUE TITLE
Can't adopt policy

### ISSUE THREAD

**Issue by leodominiscki** [LoneGazebo/Community-Patch-DLL#8458]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_

1.2.1 (with EUI)

_2. Mod list (if using Vox Populi only, leave blank):_

YnAEMP (v.24)

_3. Error description:_ 

I have an issue when I try to play with YnAEMP (v.24). 
I already did the change in the YnaemLoading to make it work. Also did the game setup as it is in the civfanatics forum. 
I don't have any problem with TSL and resources, so I think these changes are correct.
The problem is: when try the game with the "(6a) Vox Populi - Compatibility Files (EUI)", when it's time to Adopt Policies, the window for policies doesn't show, and it's impossible to pass the turn without adopting policy.
When I try the game without the "(6a) Vox Populi - Compatibility Files (EUI)" I don't have this problem, but when I try to trade with another civilization the screen is all bugged and I can't do any trade.
How can I fix this?

I am using:
- (1) Community Patch
- (2) Community Balance Overhaul
- (3) CDS for VP
- (4) CIV IV Diplomatic Features
- (6a) Vox Populi - Compatibility Files (EUI)
- Yet (not) Another Earth Maps Pack (v 24) with the correct YnaemLoading,LUA and Setup

_4. Steps to reproduce (optional):_
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/7721131/Lua.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/7721133/Database.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/7721134/xml.log)

**Comment by leodominiscki** [comment]
Here is what is shown in the lua log:

[57920.156] Runtime Error: C:\Users\Usuario\Documents\My Games\Sid Meier's Civilization 5\MODS\(6a) Vox Populi - Compatibility Files (EUI)\LUA\SocialPolicyPopup.lua:680: attempt to perform arithmetic on local 'iNeed' (a nil value)

**Comment by leodominiscki** [comment]
I just solved the problem after 1 week trying.
I installed the core game all from scratch again, but using another download source.
If someone's having the same problem, try this.
Also, thanks for everyone that made this Patch, it's awesome.

**Comment by RecursiveVision** [comment]
So...no bug? Okay.
