### ISSUE TITLE
Byzantine cataphracts and basilicas

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#846]
According to Funak, '1) Byzantine Cataphracts go obsolete at gunpowder. 
2) Byzantine Basilica still has the great work of art slot (no idea if this is intended)'
I've no idea when cataphracts should go obsolete, however.

**Comment by phantommaxwell** [comment]
Catapracts and Comp Cav unlock @ Trading instead of Military Theory.

**Comment by LoneGazebo** [comment]
Comp Cav?

**Comment by LoneGazebo** [comment]
Companion?

**Comment by phantommaxwell** [comment]
The Greek UU

**Comment by LoneGazebo** [comment]
gotcha. forgot about those.
