### ISSUE TITLE
Misspelling in Parthenon description

### ISSUE THREAD

**Issue by TadhgEomonn** [LoneGazebo/Community-Patch-DLL#8464]
_1. Mod version (X.Y.Z, e.g. 1.2.1): 1.2.1

_2. Mod list (if using Vox Populi only, leave blank):
(1) Community Patch
(2) Community Balance Overhaul
(3) CSD for VP
(4) Civ IV Diplomatic Features
(5) More Luxuries
(6a) Vox Populi - Compatibility Files (EUI)
(7) Community Events (v 5)
(7a) Promotion Icons for VP
(7b) UI - Promotion Tree for VP
(9a) Enhanced Air Warfare 4VP (v 1.9)
(graph) Faster Aircraft Animations (v 3)
(over) More Unique Components for VP (v 74)
(overhaul) More Wonders for VP (v0.14.1)
(text) Promotion Overhaul for VP (v24)
(ui) Meaningful Colours (v 8)
(ui) Trade Opportunities for VP (v11.1)
(ui) Wonder Planner for VP (v 9)
Archaeology Aesthetic Adjustments (v 1)
Barbarians - Unlimited Exp (v 2)
Better Lakes for Vox Populi (v 2.2)
Buildings - City Automaton Workers (v 1)
Calypso's Colored Religious Icons (Basic) (v 4)
Capture Great People for VP (v 3)
City Limits (v 7)
Enlightenment Era (Vox Populi) (v 4)
Even More Resources for Vox Populi (v 8)
Few More Buildings (v 210104)
Global - Commander Influence Borders (v 2)
Greatest Cities (v 11)
Historical Religions Edit (BNW or GK) (v 45)
Infixo's Enhanced Naval Warfare for Vox Populi (v 2.1)
InfoAddict (v 22)
Leadership Reformation (v 4)
Milae's Hotkeys (WASD) (With EUI) (v 4)
Monopoly Buildings for Vox Populi (v 3.4)
National Parks (v 1)
New Beliefs Mods (v9)
pdansPowerPlants(V3)
Perfidious Recon Units (v 1.1)
Promotion Flags EUI for VP (v 3)
Provincial Palace (v 3)
Quick Turns (v 10)
Religion - Permanent Pantheons (v 1)
RemoveBanLuxury (v 1)
Subs Ignore Borders for ENW (v 1)
UI - City Production (v 15)
UI - City Religions (v 4)
UI - Destination (v 4)
UI - Diary (v 21)
UI - Enhanced Demographics (v 6)
UI - Filters in Trade Route Overview (Vox Populi) (v 2.1)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 2)
UI - Show XP in Military Overview (v 2.3)
UI - Small Resource Icons (v 4)
Unique City-States (v 6.2)
Wonder Race (v 7)
zzz_(ui) List Enhancements for VP and PFEUI4VP (v 5.3)

_3. Error description: Misspelling of the word entertaining  (entartaining) in the pop-up box that opens upon completion of the world wonder, Parthenon.

**Comment by RecursiveVision** [comment]
Must be a modmod typo
