### ISSUE TITLE
City food/production focus sets questionable tile preferences

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#847]
Posted by RMcD94:
'If I put it on food focus it goes to a 2 food 0 anything tile instead of a 3 food 0 anything else tile.

If it's on production focus it goes to 2 production 0 anything rather than 1 food 2 production tile.'

I personally haven't noticed that kind of behaviour with the food focus, but I have seen it with the production focus. Basically, a lot of times when you have more citizens working tiles than there are production tiles, setting the production focus will cause tiles that yield only food be switched over to tiles that yield only food, only less. 

Sometimes it doesn't take setting any focus whatsoever - you can see this on the screenshot attached.
![guvnah](https://cloud.githubusercontent.com/assets/12978597/11459269/5b230c58-96db-11e5-9635-3691c744e0c9.jpg)
As you can see, the default city governor prefers a 2p tile over a 1f2p tile, probably because it thinks that food the city's food output is already high as is.

I don't have many screenshots on me, but it is pretty easy to reproduce. Either way, let me know if you need any more screenshots or examples.

**Comment by LoneGazebo** [comment]
I'll take a look. I think I know why, but we'll see.

**Comment by Plockets** [comment]
I have also noted weird behavior in the citizen management focus. It is not consistent though. My feeling is that "Production Focus" (as an example) assigns some small value to nonhammer yields, and this either gets lost somewhere, or gets rounded away to zero in some cases, so that in some cases 3f0h and 2f0h tile are considered equivalent by the governor. But that is just a hunch.

**Comment by LoneGazebo** [comment]
I tweaked it some in the last release. We'll see if it is working better now.
G

**Comment by LoneGazebo** [comment]
No complaints, so I'm going to close for now.
