### ISSUE TITLE
Clarication for Catherine's UA

### ISSUE THREAD

**Issue by nobubblegums** [LoneGazebo/Community-Patch-DLL#8472]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_
1.2.1

Currently Catherine's UA states that "**All** Strategic Resources provide double their normal quantity", while in fact, this doesn't apply to Paper, or any other resources provided by buildings (e.g. Aluminum from Recycling Center). I think the effect itself is fine but the text could use a bit more clarification. Maybe something like "Strategic Resources on the map" could be better.

**Comment by psparky** [comment]
Personally, I never found this confusing, but it can't hurt for it to be clearer. How about "All Strategic Resource deposits...".

**Comment by nobubblegums** [comment]
Well that's perfect!
