### ISSUE TITLE
Generating GAP by clicking on empty great work slots

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#8475]
_1. Mod version (X.Y.Z, e.g. 1.2.1):_
1.2.1

_2. Mod list (if using Vox Populi only, leave blank):_
![20211219203822_1](https://user-images.githubusercontent.com/11430209/147190955-48ef40ef-847c-4c91-a14d-565a9567d5e8.jpg)

_3. Error description:_ 
I am able to create a Golden Age Point trigger by clicking back and forth on empty Great Work Slots.
I made 2400 GAP this turn with this bug. 
_4. Steps to reproduce (optional):_
Click on an empty  GW slot on a building and then click on an empty slot on another building.   This triggers a GAP boost of 200 in the Capital.  I think it's from the National Epic.  

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![20211222235806_1](https://user-images.githubusercontent.com/11430209/147190723-bc70e406-f81f-4147-a12d-e1ff8c92c776.jpg)

![20211219203556_1](https://user-images.githubusercontent.com/11430209/147191239-29940395-60b1-4c95-a7b1-3281f95ecf9e.jpg)

**Comment by bentakacs** [comment]
I'm able to reproduce this. It's a bit more restricted as I can see, for Buildings with a single slot it seems to be ok, however, when I click on an empty slot with 2 slots and the other one is filled, then indeed it generates 300 GAP (I'm playing on Epic, so 200 on standard).

Also, I can't place manually one GW (made by a great writer in this case) to another slot where there is already one in the other slot (so there would be two and a potential theming bonus), and in this case the free GAP is triggered guaranteed.

With the "Optimize" button it works well, and doesn't generate free GAP, it seems to be only with manually trying to move GWs as described above.

To the OP: there is no building called "National Epic". There is National Monument and Heroic Epic, the first generates GAP when you unlock Social Policies, could be maybe somehow the code got messed up and also generates like you and I found?! I don't know, but maybe it worths a check.

There is definitely some weird thing going on here. Could someone please look at this? Thank you!
