### ISSUE TITLE
1.3 Art/Icon/Textures Troubles Mega-Issue

### ISSUE THREAD

**Issue by nobubblegums** [LoneGazebo/Community-Patch-DLL#8478]
I thought it'd be better to collect them under one issue since they are probably caused by the same thing. So far I've got Writer icons not showing up on the tech tree, and missing texture for Sutton Hoo.
I'd appreciate if people can comment with:
The problematic texture
Modlist
Graphic settings (dx9 or 11, resolution, small UI or not)
GPU brand
and anything that could be relevant.

In the meantime you can use this to go back to old files, extract into Mods folder and overwrite all.
https://drive.google.com/file/d/1b9TjQuRFAWUDqqxKZrstgQD49edO8Rsa/view?usp=sharing

edit : This seems to happen on DX11, I'm working for a fix. In the meantime you can use the old files or run the game with dx9

**Comment by Hokiefan00** [comment]
The writer icon on the tech tree missing.

Modlist:
- VP version 1.3 with EUI
- Promotion Flags for VP v3
- More Unique Components for VP v74
- New Belief Mods v10
- Israel for VP v16
- Canada for VP v24
- Inuit for VP v18
- Tlingit for VP v19
- Goths for VP latest version
- Greece and Macedon for VP v14
- Khmer for VP v12
- Sumer (CBP) v23
- The Timurids for 4UC (VP) v14

Graphic Settings: dx11 1920x1080 default UI
Processor: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz
GPU: Nvidia GeForce GTX 1060
Ram: 16GB

**Comment by nobubblegums** [comment]
Thanks Hokiefan, you can find the hotfix on civfanatics release thread. Closing this now, hope there won't be more!
