### ISSUE TITLE
CityView Graphic Issue.

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#848]
![image](https://cloud.githubusercontent.com/assets/13937047/11465136/efe4ce6c-96ea-11e5-8dd8-8b6fa90bc733.png)
So, when you have too much of a number in a certain row, it tends to get bad because the palace's yield is seen below the great work icon. Could be EUI-related as well..

**Comment by LoneGazebo** [comment]
I noted this in the beta changelog -it's an issue with bc_1's EUI, nothing to do with my version. You can badger him if you want, as he hasn't stated if he's going to fix this or not.
