### ISSUE TITLE
India's UA failing to convert secondary cities (creating negative followers instead)

### ISSUE THREAD

**Issue by DemaciaMaggotPie** [LoneGazebo/Community-Patch-DLL#8481]
_1. Mod version (X.Y.Z, e.g. 1.3.2):_
1.3.2

_2. Mod list (if using Vox Populi only, leave blank):_
3/4 UC, Milae's Hotkeys, Simplified Warfare for VP

_3. Error description:_ 
Upon founding, my second city (I don't have a third) converted minus 2 followers rather than 2. It kept its Pantheon. The capital converted appropriately.

_4. Steps to reproduce (optional):_
Found as India with more than one city.

---------------------------

I can upload a savegame if needed.

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/7167416/147395207-67fee74f-06e6-4062-9eaf-44927354f720.png)

**Comment by ilteroi** [comment]
will check when i get home ...

**Comment by LessRekkless** [comment]
#8486
