### ISSUE TITLE
Shoshone have no cities, but have an embassy

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#8482]
1. Mod version (X.Y.Z, e.g. 1.3.2): 1.3.2

2. Mod list (if using Vox Populi only, leave blank):

3. Error description: Now this is a weird one :-) In turn 2 or 3, my scout stumbled upon a lonely Shoshone settler (their first one). I promptly declared war and captured their settler before they could found a city (capture_settler.zip save). After that they were left with 2 warriors and a pathfinder. Eventually, I killed one warrior and a pathfinder, and then on Mongolia's request agreed to a peace with Shoshone. At some point they asked to establish and embassy, which I agreed to (see the screenshot below). I think they have one warrior left which means they are still technically in the game, but that simply makes no sense since they have no cities to build anything. Perhaps their civ should have been declared dead some number of turns after they lost their first (and only) settler?

4. Steps to reproduce (optional): Load one of the attached saves if that helps with the analysis.

EDIT: added a save before capturing the settler and the logs up to that point.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"): [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7776861/Logs.zip) (for the first three turns of the game, just before I capture Shoshone settler)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu): [no_cities.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7776471/no_cities.zip)
[capture_settler.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7776859/capture_settler.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional): ![no_cities_but_have_embassy](https://user-images.githubusercontent.com/620131/147397595-a9531cf9-fcdf-4f4b-b055-e4bdf3b6b482.jpg)

**Comment by RecursiveVision** [comment]
I've been meaning to address this one for a while...done!
