### ISSUE TITLE
Kuna appears both with Construction and Mathematics (The Maya)

### ISSUE THREAD

**Issue by brsoft1981** [LoneGazebo/Community-Patch-DLL#8484]
_1. Mod version (X.Y.Z, e.g. 1.3.2): Vox Populi 1.3.2.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ Kuna appears both with Construction and Mathematics (The Maya civ)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Kuna](https://user-images.githubusercontent.com/96129291/147406065-1736f7ff-0900-4040-bf01-cf9bebe8ed12.jpg)

**Comment by pineappledan** [comment]
The one at math indicates that all Kuna improvements gain more science. It's a tech yield bonus unlock

**Comment by brsoft1981** [comment]
Oh, i'm sorry for the false alarm. Thanks for the great Vox Populi :)

    On Monday, December 27, 2021, 06:27:02 AM GMT+2, pineappledan ***@***.***> wrote:  
 
 


The one at math indicates that all Kuna improvements gain more science. It's a tech yield bonus unlock

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
