### ISSUE TITLE
Communitas Map ignoring "Really advanced Setup" settings

### ISSUE THREAD

**Issue by PerfectDark99** [LoneGazebo/Community-Patch-DLL#8485]
1. Mod version: 

1.3.1

2. Mod list:

- Really Advanced Setup
- others but not relevant (Quick turns, Speedy starting settler, faster aircraft animation,...)

3. Error description:

Communitas Map script ignores/overrides settings from Really advanced setup. I did not try a lot but it ignores for examples setting a specific natural wonder (Lake victoria) within 3 tiles of your start location

4. Steps to reproduce:

- start new game with really advanced setup mod
- choose communitas map as map
- in really advanced setup assign lake victoria to current player

Is there any setting that enforces really advanced setup settings?

**Comment by RecursiveVision** [comment]
@azum4roll

**Comment by azum4roll** [comment]
I'm not sure how RAS works. If it also overrides AssignStartingPlots.lua I'd say it's a mod conflict.

**Comment by PerfectDark99** [comment]
Not sure how it works either. I often play with Tectonic Map script and there it seems to work for most wonders (set as random) except also not for explicitly placing lake victoria. On pangea plus map it works fine always.

I searched the MODS dir for "AssignStartingPlots.lua" and it doesn't find any other copy than that from vox populi. But the Really Advanced Setup mod contains many lua files around map generation:

MapmakerUtilities.lua"
GTAS_WonderTypes .lua"
LoadScreen.lua"
GTAS_TerrainTypes.lua"
GTAS_Utilities.lua"
GTAS_WonderTracker.lua"
GTAS_StartGame.lua"
GTAS_TableSerialization.lua"
GTAS_SlotManager.lua"
GTAS_Sprinkles.lua"
GTAS_StartBias.lua"
GTAS_RouteConnections.lua"
GTAS_ScrollText.lua"
GTAS_SetCivNames.lua"
GTAS_PlotPlacement.lua"
GTAS_ResourceTypes.lua"
GTAS_PlaceResources.lua"
GTAS_PlaceTerrain.lua"
GTAS_PlaceWonders.lua"
GTAS_PlaceFeatures.lua"
GTAS_PlaceNonCityUnits.lua"
GTAS_MapTerrain.lua"
GTAS_MapWonders.lua"
GTAS_PlaceCityItems.lua"
GTAS_MapPanel.lua"
GTAS_MapResources.lua"
GTAS_MapBonusPanel.lua"
GTAS_MapFeatures.lua"
GTAS_MapManager.lua"
GTAS_InitGame.lua"
GTAS_InitMap.lua"
GTAS_InitPlayers.lua"
GTAS_GlobalManager.lua"
GTAS_IDoNotKnowWhatFileNameIsSafe.lua"
GTAS_FeatureTypes.lua"
GTAS_GameManager.lua"
GTAS_GamePanel.lua"
GTAS_CustomNaturalWonders.lua"
GTAS_DataManager.lua"
GTAS_Constants.lua"
GTAS_CivTerrain.lua"
GTAS_CivUnits.lua"
GTAS_CivWonders.lua"
GTAS_CivPanel.lua"
GTAS_CivResources.lua"
GTAS_CivStartBonus.lua"
AdvancedSetup.lua"
GTAS_CivBonusPanel.lua"
GTAS_CivFeatures.lua"

**Comment by PerfectDark99** [comment]
Update: i have now tried twice with 1.3.4 and it worked fine (before I think it was with 1.3 and 1.3.2)
