### ISSUE TITLE
No ruins generated on Communitas map 

### ISSUE THREAD

**Issue by essiemaestudios** [LoneGazebo/Community-Patch-DLL#8488]
_1. Mod version (X.Y.Z, e.g. 1.3.3): 1.3.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: There are no ruins being generated. Worked fine in 1.3.1. Issue started in 1.3.2. Also, just an observation, but luxury and strategic resource generation seems very sparse as well in these versions compared to 1.3.1 (chose abundant in game settings). Have seen the issues in 5 different restarts so should be relatively easy to reproduce.

_4. Steps to reproduce (optional): See attached screenshot of game settings to reproduce.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![civ1](https://user-images.githubusercontent.com/91953991/147449942-6854a1b1-7be7-4882-b7f9-713ad5d8bb6a.jpg)

**Comment by RecursiveVision** [comment]
@azum4roll

**Comment by azum4roll** [comment]
Cannot reproduce with the same settings.
