### ISSUE TITLE
Allocation of Followers

### ISSUE THREAD

**Issue by psparky** [LoneGazebo/Community-Patch-DLL#8489]
_1. Mod version (X.Y.Z, e.g. 1.3.3):_
 
Latest code as of posting date.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

In CvCityReligions::RecomputeFollowers, after the initial allocation of follows based on iPressurePerFollower, there will usually be some population left. This is distributed according to the remainder of accumulated pressure after taking out that used in the initial allocation.

Recently (sometime in 2021) the code that does this has been changed (for clarity or performance or standardization I presume), but in the process the method was, I believe accidentally, changed. If there are x left unallocated, previously one was allocated to each of the x highest remainders. Now, all x are allocated to the religion with the highest remainder.

I'm pretty certain this is wrong as the code could be much simpler if that change was intended.

It used to set the remainder to zero when an extra follower was allocated, but this no longer happens.
Was:
		if (iLargestRemainder > 0)
		{
			itLargestRemainder->m_iFollowers++;
			itLargestRemainder->m_iTemp = 0;
		}
Now:
		if (iLargestRemainder > 0)
			m_ReligionStatus[iNextRecipient].m_iFollowers++;

_4. Steps to reproduce (optional):_

Found by code inspection, no example available.

**Comment by ilteroi** [comment]
you're right, my bad

**Comment by RecursiveVision** [comment]
@ilteroi That's what we have beta testers for ;)
