### ISSUE TITLE
Negotiating Peace Doesn't Work

### ISSUE THREAD

**Issue by usadefcon1** [LoneGazebo/Community-Patch-DLL#8490]
1. Mod version
v1.3.4

2. Mod list 
See attached screenshot for Mod List

3. Error description:
Negotiating peace has worked in the past, but this time when the deal is done we are still at war. 
I can also put items on both sides of the deal.

1. Log files

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7782573/Logs.zip)

2. Save game

[Save Game.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7782574/Save.Game.zip)

4. Screenshots (optional):

![010](https://user-images.githubusercontent.com/57153924/147524468-cad4423c-2043-4957-9a80-8970d2350b6b.jpg)
![020](https://user-images.githubusercontent.com/57153924/147524474-aa0a935d-8253-4a08-a624-46c852c980f2.jpg)
![030](https://user-images.githubusercontent.com/57153924/147524477-1dfcbbbc-8595-4314-be6e-9d617de36423.jpg)
![035](https://user-images.githubusercontent.com/57153924/147524481-af70d3fc-3fbc-48cb-8b0a-e80750a4407e.jpg)
![040](https://user-images.githubusercontent.com/57153924/147524483-9368288b-582f-40a7-9890-811915b19001.jpg)
![050](https://user-images.githubusercontent.com/57153924/147524487-116ba52d-5787-4dba-bf1a-ac5af3f35c8a.jpg)
![060](https://user-images.githubusercontent.com/57153924/147524490-a10cd08c-9312-43f3-8388-d6f50dcbdfbe.jpg)

**Comment by RecursiveVision** [comment]
@Mileslewis

**Comment by Mileslewis** [comment]
Don't think this was anything I did?

**Comment by RecursiveVision** [comment]
@usadefcon1 You're using lots of extra mods. You'll need to a) provide a ZIP file of your MODS folder (as it was when this bug happened) and b) specify which ones were activated. Otherwise I can't reproduce.

**Comment by usadefcon1** [comment]
> @usadefcon1 You're using lots of extra mods. You'll need to a) provide a ZIP file of your MODS folder (as it was when this bug happened) and b) specify which ones were activated. Otherwise I can't reproduce.

Okay here is a zip of the mods I was using, in addition to these I was also using More Unique Components for VP (v 74) but that was too big to include:

[Mods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7826634/Mods.zip)

**Comment by RecursiveVision** [comment]
@usadefcon1 You also had Enhanced Air Warfare...anyway, fixed
