### ISSUE TITLE
UnitAI Inconsistencies

### ISSUE THREAD

**Issue by nobubblegums** [LoneGazebo/Community-Patch-DLL#8491]
I was fixing the DefaultUnitAI for some units but then noticed a lot more inconsistencies under Unit_AITypes, and I'm not sure about how to proceed. Here's what I noticed so far, my questions and changes I'm planning to make. I'm not including the obvious bugs that I fixed to keep it short.

**Units, DefaultUnitAI**

- Battering Ram is a Melee vs City unit, has UNITCOMBAT_MELEE as CombatClass, but UNITAI_CITY_BOMBARD as DefaultUnitAI. **Wouldn't CITY_BOMBARD prevent them from getting adjacent to cities?** Not sure if and how to deal with this. 
- UNITCOMBAT_GUN units mostly have UNITAI_DEFENSE, except Musketeer which has UNITAI_ATTACK and Mercenary/Guerilla which _had_ UNITAI_FAST_ATTACK, but I replaced that with UNITAI_ATTACK. I think this fits with their unique abilities/promotions, so I kept them that way for now. **Should we consider giving UNITAI_ATTACK to some other offensive-oriented Gun Melee units, especially Foreign Legion & Carolean?**
- I gave Free Company ATTACK (had FAST_ATTACK). Other Pike units have UNITAI_COUNTER, but Free Company has two plunder/pillage abilities so ATTACK made more sense to me, but I'm not sure.
- I'm not sure about Landsknetch either, it has Formation 1 & 2, so UNITAI_COUNTER makes sense, yet it replaces Tercio which has UNITAI_ATTACK.
- Pre-Paradrop Recons have EXPLORE, but Commando has FAST_ATTACK, is this right?
- Korean Hwacha currently has UNITAI_RANGED. It replaces Trebuchet, so an argument can be made for it to have UNITAI_CITY_BOMBARD, but it doesn't have the standard siege unit penalty vs. land units, so keeping it with UNITAI_RANGED also makes sense. Which one should it be?

**Unit_AITypes**
Ranged units until Gatling Gun only have UNITAI_RANGED, Gatling and later units have UNITAI_RANGED and UNITAI_DEFENSE. **Is this intended, should I give DEFENSE to earlier units or remove it from later ones?**

Skirmishers all have UNITAI_COUNTER and UNITAI_RANGED, except Keshik which has DEFENSE + FAST_ATTACK, Camel Archer which has FAST_ATTACK in addition to them. Warchariot and Chariot Archer are missing COUNTER. I'm standardizing all to have RANGED & COUNTER only.

Mounted&Armor has FAST_ATTACK, DEFENSE. Some have extra ATTACK, which I'll be removing.

Pre-gun Melee units:
Spearline has ATTACK, DEFENSE, COUNTER and EXPLORE. Swordline has ATTACK, DEFENSE and sometimes EXPLORE. I've given EXPLORE to every Swordline unit for consistency.
**I'm not sure about this, but wouldn't it be better if EXPLORE was removed from Melees and instead given to Mounted or Skirmisher line (maybe very early melee units can keep it)?**
A few Spearline units are missing ATTACK (Spearmen, Barb Spearman, Tercio), I'm also giving them ATTACK for consistency.

Gun units: All have Attack, Defense, Explore.
**Mechanized Infantry has FAST_ATTACK, should that be removed?**

Recon: All have EXPLORE, later units have PARADROP. 
Marine (Special Ops) has extra ATTACK & DEFENSE , which I considered an error and removed. That said there may be an argument to give ATTACK&DEFENSE to all late Recon units as they are somewhat combat capable.

**Comment by nobubblegums** [comment]
I think these lie in the @ilteroi territory, what a nice Christmas gift for them!

**Comment by ilteroi** [comment]
great writeup, but i have no opinion on most of those. also it's pure database stuff, anyone who feels the itch can do it ... so i'll pass on this one

**Comment by nobubblegums** [comment]
Thanks for taking a look! I'll proceed with the safe changes then, leaving this issue open for a while in the case someone has advice.
