### ISSUE TITLE
expansion warning

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8493]
just got an expansion warning from brazil after they settled brazilia ...

![image](https://user-images.githubusercontent.com/1358966/147609353-2107fee9-bea3-4942-8793-71a2615e3aa8.png)

all my cities are older. last one was antiochia about 15 turns back.

edit: aaaand again, 50 turns later

**Comment by RecursiveVision** [comment]
Savegame?

**Comment by ilteroi** [comment]
lost in the mist of time
