### ISSUE TITLE
CS wants me to declare war on its ally

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#8495]
1. Mod version (X.Y.Z, e.g. 1.3.4): 1.3.2

2. Mod list (if using Vox Populi only, leave blank):

3. Error description: Kabul is asking me to declare war on its ally, Denmark (see the screenshot below). My understanding is that such quests should be canceled once the target (Denmark, in this case) becomes the CS's ally.

4. Steps to reproduce (optional): Load the attached save.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"): [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7790922/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu): [war.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7790921/war.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![declare_war_on_ally](https://user-images.githubusercontent.com/620131/147709915-faad8d31-c8bb-4837-a187-006f009cdaf1.jpg)

**Comment by bsesar** [comment]
Followup: I got the reward after making peace with Denmark (after I declared and made them capitulate).

**Comment by RecursiveVision** [comment]
Ugh, messy code. Will work on this.

**Comment by RecursiveVision** [comment]
Fixed this specific issue, the code still needs work though.
