### ISSUE TITLE
Strange Starting City Placement (4 Civs Starting On One Small Island)

### ISSUE THREAD

**Issue by Roban1967** [LoneGazebo/Community-Patch-DLL#8496]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_ 
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_ 
Barbarians - Unlimited Exp (v. 2)
Krajzen's Great Artists Pack (v. 1)
Krajzen's Great Musicians Pack (v. 1)
Krajzen's Great People Pack (v. 1)
Krajzen's Great Writers Pack (v. 1) 
R.E.D. Modpack (v. 27)

_3. Error description:_ 
Bad placement of multiple starting civilizations (4) on a single small island.  See screenshot and save attached.

_4. Steps to reproduce (optional):_

[VP Report Dump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7794380/VP.Report.Dump.zip)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Roban1967** [comment]
Follow up post.  Just started a new game, same version and mods.  Check out this insane start, on a HUGE large islands map...  Something is clearly wrong with the starting placement script.

![VP Crazy Start](https://user-images.githubusercontent.com/85279377/147797937-2d43e247-744c-4b08-b110-16d0d1e34944.jpg)

**Comment by bsesar** [comment]
@Roban1967, what happens if you don't use R.E.D. Modpack? I think this may be a mod conflict issue since some changes were done in v1.3.2 to AssignStartingPlots.lua.

**Comment by azum4roll** [comment]
What's the mapscript?

**Comment by Roban1967** [comment]
@bsesar Removing the R.E,D, Modpack had no effect.  The next "Large Islands" map I generated had four main civilizations all starting on a single island (previously using this map - before installing VP 1.3.4, there was a maximum of one main civ and 1-2 city states on any island).

@azum4roll I don't know anything about the mapscript.  I assume it's the standard one that comes with the Large Islands map.  I haven't edited it (I wouldn't know how).
