### ISSUE TITLE
Cannot work a tile (locked by a puppet city?)

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#8498]
1. Mod version (X.Y.Z, e.g. 1.3.4): 1.3.2

2. Mod list (if using Vox Populi only, leave blank):

3. Error description: I would like to transfer a tile with Marble to Copenhagen, but that is not possible. The tooltip says that the tile belongs to puppet city of Kaupang (see the screenshot), but that tile is too far away for Kaupang to work it. Is this intended behavior?

4. Steps to reproduce (optional): Load the attached save and try to work the tile with Marble near Copenhagen.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"): [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7796486/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu): [cannot_transfer_tile.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7796484/cannot_transfer_tile.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![cannot_transfer_tile](https://user-images.githubusercontent.com/620131/147829942-1a5f387c-e7f9-4bf0-99df-8bbb6c21531e.jpg)

**Comment by ilteroi** [comment]
hmm, i assume you are egypt and conquered both cities? kaupang is the city to the northeast and got the tile through the citadel?

this is a corner case ... but an easy fix.

**Comment by bsesar** [comment]
Yes, I am playing as Egypt and have first puppeted Kaupang, then created a citadel just outside the border to grab two hill tiles from Copenhagen.
