### ISSUE TITLE
HasReligionInMostCities / ComputeMajority

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8499]
there is some weird logic at work here when determining the majority religion in an empire

ComputeMajority:
```
	for (int iI = RELIGION_PANTHEON + 1; iI < GC.GetGameReligions()->GetNumReligions(); iI++)
	{
		ReligionTypes eReligion = (ReligionTypes)iI;
		if (HasReligionInMostCities(eReligion))
```

HasReligionInMostCities:
```
	// Over half? Equal to make OCC/Venice possible.
	return (iNumFollowingCities * 2 >= m_pPlayer->getNumCities());
```

i don't understand that comment anyhow, but the effect is that in case of a tie (eg 2 religions with 3 cities each) the first religion *in the database* will always win. cannot imagine that is desired?

options
* require a true majority
* look at number of followers in case of a tie
* look at founding turn in case of a tie

**Comment by psparky** [comment]
That's not an ideal situation I agree. If starting from scratch, I would probably use the number of followers to break a tie. However, there are quite a few calls of HasReligionInMostCities, so the logic really would need to be in that routine to ensure consistency. The way the code is structured, where HasReligionInMostCities is called for each religion in turn, makes that pretty undesirable.

I would therefore go for the true majority solution - easy to do and to test.
