### ISSUE TITLE
india building missionary

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#850]
![image](https://cloud.githubusercontent.com/assets/1358966/11484422/34934d9a-97ae-11e5-8ec5-30c769397b4c.png)

i thought they cannot do that?

**Comment by Radost** [comment]
Probably it is a captured one.

**Comment by LoneGazebo** [comment]
Did they build borobudur?

**Comment by ilteroi** [comment]
ok, i see there are explanations aplenty. closing the issue :)
