### ISSUE TITLE
(CP only) Religious belief "Church Property" has no effect

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#8502]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch only, no Community Balance Overhaul

_3. Error description:_ 
The religious belief "Church Property" (2 gold per city having the religion) does not work, it doesn't provide any extra money at all. The other gold-related belief "Tithe" (1 gold per 4 followers of the religion) works fine.

**Comment by RecursiveVision** [comment]
Weirdly set so that it only applied to pantheons. Fixed.
