### ISSUE TITLE
"NOTE: You are not at war" when you are at war

### ISSUE THREAD

**Issue by Neborya** [LoneGazebo/Community-Patch-DLL#8509]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Looks like a minor UI bug?
If there might be some logic involved too, and a save file is needed, I'll find it and attach.

![Civ5Screen0000](https://user-images.githubusercontent.com/27854329/147935304-ad82f295-318f-4c9c-af9b-c24597c0312f.jpg)

**Comment by RecursiveVision** [comment]
Forgot to account for this...

**Comment by RecursiveVision** [comment]
This can't be fixed without some major code rework, unfortunately

**Comment by RecursiveVision** [comment]
Nvm, found an easier fix
