### ISSUE TITLE
Triremes in lakes

### ISSUE THREAD

**Issue by Neborya** [LoneGazebo/Community-Patch-DLL#8512]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I thought in one of the earlier versions AI was disallowed to build ships in lakes? On the screenshot Genghis Khan has 5 triremes patrolling 8 water tiles (there is no access to the ocean). Is this a bug? Still I think that dromons would be of some use there...

![Civ5Screen0000](https://user-images.githubusercontent.com/27854329/147990136-4525de4f-9ff0-4aa6-84d2-598bdee9c85b.jpg)

**Comment by ilteroi** [comment]
they do build ships here because there is an enemy city.

**Comment by Neborya** [comment]
1 turn before the screenshot Turfan belonged to Mongolia...

**Comment by ilteroi** [comment]
hmm, indeed. should not have happened then

**Comment by axatin** [comment]
Maybe the same issue: It happens sometimes that a lake next to a city is misinterpreted as an ocean coast, and then triremes and lighthouses can be built.
![Screenshot (40)](https://user-images.githubusercontent.com/95587882/154571593-77363db3-cfad-4b7c-82ea-410b50bb39f9.png)
