### ISSUE TITLE
Reformation belief logic and tooltips

### ISSUE THREAD

**Issue by Neborya** [LoneGazebo/Community-Patch-DLL#8513]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Suddenly I was prompted to choose the reformation belief. The tooltip says "You have adopted the Reformation social policy", but I didn't adopt any policy in the last turns + it looks like there is no policy called Reformation at all.
What happened on this turn (religion-wise) is that Mausoleum was constructed. But the description of Mausoleum doesn't say anything about adding a belief.
So, was it the Mausoleum? :)

![Civ5Screen0000](https://user-images.githubusercontent.com/27854329/148397068-ac4232e3-83ba-4914-9aa7-c4212a506805.jpg)

**Comment by psparky** [comment]
I think it's just a wonky notification - I'm not sure I ever actually read the main notification text before, so it may have been like this for, well, ever.

Building the Mausoleum does give a reformation belief. If it's not mentioned in the building's tooltip it probably should be. I think it is mentioned in the founder belief description that unlocks the building.

**Comment by RecursiveVision** [comment]
Fixed the notification text. There's something wonky about the text for religious NWs in general. Looking at it.
