### ISSUE TITLE
Religious conversion warning

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8514]
![image](https://user-images.githubusercontent.com/1358966/148462397-c3ca0f9b-5e04-4783-a375-99695dfae599.png)

you get this warning when you have sucessfully converted a majority of an AI players' cities ... that seems weird? why not after the first missionary?

also, we now have GetFavoriteForeignReligion, so in case they like my religion they should not complain at all.

**Comment by RecursiveVision** [comment]
Hm, that message is supposed to trigger the first time you convert a founder's city.

**Comment by ilteroi** [comment]
it's reproducable ...
