### ISSUE TITLE
Game crashes always on the same turn (43 civs, Communitas map)

### ISSUE THREAD

**Issue by murilozardo** [LoneGazebo/Community-Patch-DLL#8516]
1. Mod version: 1.3.4

2. Mod list: 43-Civ Vox Populi (EUI) and Ingame Editor (v. 39)

3. Error description: Game crashes to desktop always on turn 761, on the AI Inca's turn (with or without IGE). Using IGE, I deleted the Inca civilization from the game. That worked until turn 770, when another CTD always occurs on AI Korea's turn (which always played immediately before the Inca previously, by the way). This is my very first game with 43 civs and also my very first time using the Communitu_79a v2.3.0-exp map.
[CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7831442/CTD.zip)

**Comment by RecursiveVision** [comment]
@ilteroi pCity is returning NULL and crashes when it tries to call getTeam(). You changed this last and know the code better than I do, so :)

![9c3ff1ddf3190cae9a0709aca8a5b1bd](https://user-images.githubusercontent.com/66801010/148711325-dc6aa7bc-29cd-4056-ab63-b71fe1d0ca94.png)

**Comment by RecursiveVision** [comment]
Well if you build the 43 Civ DLL for the "1.3.4 Release" commit, you should be able to load the save and reproduce said deeper issue for yourself.

**Comment by ilteroi** [comment]
cannot load it, just slap a null pointer check on it an be done

**Comment by RecursiveVision** [comment]
@ilteroi I added a null pointer check but I'm not gonna give up that easily :P 

Loading the save worked for me by running the debugger from this DLL folder (extract to Desktop): https://drive.google.com/file/d/1bZPBXzwOa0eZCQK057STrNTxRVUAoqef/view?usp=sharing

And by using this MODS folder: https://drive.google.com/file/d/1TKdTfXqqASS320zBsd-SRG_rgIOkq2n0/view?usp=sharing

I uploaded both to Google Drive. If it still doesn't work for you then there's an instance of the "loading saves inexplicably doesn't work" bug which I'll bring to IanE9's attention.

**Comment by RecursiveVision** [comment]
@ilteroi So... not planning on fixing this?

**Comment by ilteroi** [comment]
maybe later ... if i succeed in loading it without infoaddict ... but don't delay the new release because of this

**Comment by RecursiveVision** [comment]
@ilteroi This is fixed now. https://github.com/LoneGazebo/Community-Patch-DLL/commit/d69eb3bc4378792a173bd50baa1db53e8c540645

The City ID exceeded the unsigned short size limit. It's now an int.
