### ISSUE TITLE
Graphics resources get corrupted eventually leading to crash

### ISSUE THREAD

**Issue by punger** [LoneGazebo/Community-Patch-DLL#8517]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_
More unique components v. 22
Enhanced naval warfare for VP v.1
R.E.D Modpack v 27

_3. Error description:_ 
After playing for a while -- time can vary from, say, 20 minutes to an hour -- the graphics for any new icons are loaded incorrectly.  Sometimes they are black squares, sometimes just other incorrect icons, sometimes distorted versions of icons, sometimes patterns, sometimes what looks like miniature versions of arrays of other icons.  Sometimes there is also a popup outside the game that says that it cannot load a font texture.  The game is mostly playable even so, however, eventually the symptoms worsen.  The game may no longer respond to clicking on buttons.  Particularly when looking at the tech tree, icons may start disappearing very quickly until they are all gone and then nothing can be done.  Exiting back to the main menu seems to reset it for some time, however the game can crash at that point.  Exiting the game and reloading resets things back to normal until the problem starts anew.  The problem always happens after some amount of playing although it can be highly variable.

_4. Steps to reproduce (optional):_
None specifically necessary other than playing the game.

Note that the save file is not from the turn prior to the problem because in this case it happened on the very first turn.  Clearly the problem had already occurred but there is no earlier save game.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7832163/Logs.zip)
[Gustavus Adolphus_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7832165/Gustavus.Adolphus_0000.BC-4000.zip)

**Comment by nobubblegums** [comment]
There are other reports like this on the forums, all with RED Modpack. Try playing without it and see if that helps.

**Comment by RecursiveVision** [comment]
Mod conflict or Firaxis memory limitation. Can't be fixed by us.

**Comment by punger** [comment]
Setting up a game without RED Modpack seems to have solved the problem.  Thank you.
