### ISSUE TITLE
Spanish Mission's yields (gold&faith) on city growth

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#852]
Posted by Takagi Hiro: 
"I think something isn't working correctly. There have been many times where my city grew and I got something like 7/3."

I think I saw at least one other person report that also reported the same thing a while back. Not sure if you've looked at it, so I'll leave it here.

**Comment by LoneGazebo** [comment]
The yield is not flat, it is a % of your current production rate.

**Comment by Edaka** [comment]
Oh, so that's what it is! No wonder it's confusing when most other yield-on-event effects are either flat or otherwise specified in the tooltip (like the chancery). Perhaps the tooltip could use an update?

**Comment by LoneGazebo** [comment]
Yeah, I should probably update it. :)

G
