### ISSUE TITLE
1.3.4 Weak Inquisitors

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#8522]
Latest version, no other mods

Upon being expended, Inquisitors powered by the Inquisition enhancer only turn a single heretic into a follower of the owner religion.

**Comment by ilteroi** [comment]
need the numbers from the city tooltip before and after

**Comment by randomnublet** [comment]
![civinqui](https://user-images.githubusercontent.com/53142313/148650719-fd8a621b-835d-4c5b-b50a-82ad7ce16060.png)

**Comment by randomnublet** [comment]
So basically the Inquisitor halved foreign religions pressure, but it failed at turning the city to my own (my religion is the one with the zoroastrism icon). I gained one follower, Eastern Orthodoxy lost one, but despite the pressure drop Catholicism still prevails (nobody enhanced with Prophecy fwiw)

Let see what happens if I use a (Hagia Sofia - powered) missionary instead:

![civinqui2](https://user-images.githubusercontent.com/53142313/148650798-da35a0ef-68ce-4b0f-8ae0-64c4154c8008.png)

I gain two followers, converted a filthy Catholic as well and that took one spread only so in the long run missionaries do it better™

**Comment by randomnublet** [comment]
Thanks for these new religion pressure tooltips by the way, they really help figure what's going on.

A request: it would be nice if the inquisitors UI displayed the religion they follow and the remove heresy button also gave a preview on how many heretics are being burned at the stake.

![civinqui3](https://user-images.githubusercontent.com/53142313/148651059-1aea00f5-6794-451f-bc23-5a0ba4485a6f.png)

**Comment by randomnublet** [comment]
Some more testing and ranting:

![civinqui4](https://user-images.githubusercontent.com/53142313/148651439-cfa7a3d0-d5d0-4c06-b3e8-0ddf72be0659.png)

Same city (original pressure in previous screenshots) hit by 2 missionary spreads in one test, and by 2 remove heresy actions in the other. Inquisitors are plain bad at what they used to be good at, if I want to keep my majority religion I'd better use missionary for all pratical purposes (final # of followers is what matters for beliefs here)

**Comment by ilteroi** [comment]
well, it depends ... of course if you deal with pressure values ~1k a missionary will have a larger impact.

but when the accumulated pressure is 10k the picture is different and the inquisitor wins.

so both have their niche, i think it's fine?

**Comment by LessRekkless** [comment]
Even if you used an inquisitor with 100% pressure removal, your opponent could reconvert to their religion with a single missionary use, or maybe ten turns of passive pressure.

The correct play is still to use a missionary so you can establish a pressure base.

**Comment by randomnublet** [comment]
Those values are from a freshly established satellite city in late medieval, few turns after I enhanced. Quite early in the religion game. 
I figured Inquisition could work when being behind in faith generation and having to fight hostile pressure (that's what inquisitors are designed for, right?)
Imho there's something wrong balance wise that you can spot in the first picture, when I remove 963 pressure out of 1927 and the targeted heretic religion doesn't lose a single follower.
Don't forget Inquisitors cost the same as missionaries but only have 1 action vs 2 spreads, also Inqusition gives a pretty meh amount of gold for each conversion, and in the latest beta there're very few conversions even after big pressure drops.

**Comment by LessRekkless** [comment]
The problem is that you only have 300 pressure. That's not enough. I'm not saying that 50% conversion should be set in stone, but I am saying that you should be using missionaries in this specific city, regardless of how powerful the inquisitor is.
