### ISSUE TITLE
Missing text when playing Community Patch only

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#8524]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch only, no Community Balance Overhaul

_3. Error description:_ 
When playing Community Patch only, some lines of text are missing:

TXT_KEY_CHOOSE_INTERNATIONAL_TRADE_ROUTE_ITEM_TT_THEIR_GOLD_EXPLAINED
TXT_KEY_MISC_BONUS
TXT_KEY_LEAGUE_OVERVIEW_INVALID_RESOLUTION_ATTEMPTED_LAST_SESSION
TXT_KEY_MISC_LOST_WONDER_PROD_CONVERTED_S (visible only for a short time on a notification on the side; appearing when a world wonder couldn't be completed)
TXT_KEY_POP_CSTATE_BULLY_FACTOR_FRIENDS

![Screenshot (7)](https://user-images.githubusercontent.com/95587882/148660611-05b146a8-93f7-4fcb-abcc-f5e9636d18cc.png)
![Screenshot (8)](https://user-images.githubusercontent.com/95587882/148660619-31610c03-5e99-4994-b54e-174f81e25bd3.png)
![Screenshot (10)](https://user-images.githubusercontent.com/95587882/148660623-0e0309ad-dd52-4327-9b4f-01345d7e679e.png)
![Screenshot (13)](https://user-images.githubusercontent.com/95587882/148660627-302c1d9c-75e1-464b-aec6-462088be8172.png)

**Comment by axatin** [comment]
and also:

TXT_KEY_CO_PLAYER_TOURISM_TOUR_BONUS_HALF
TXT_KEY_NOTIFICATION_FRIENDLY_PARTISANS_NEAR_RAZING_CITY
TXT_KEY_DIPLO_DEFENSE_PACT_WITH_US
TXT_KEY_EUPANEL_WITHDRAW_CHANCE

![Screenshot (19)](https://user-images.githubusercontent.com/95587882/149922235-096667be-284c-41ab-90d1-c193da1059c2.png)
![Screenshot (21)](https://user-images.githubusercontent.com/95587882/149922252-468e3347-248b-460f-a665-f484b0ff864d.png)
![Screenshot (22)](https://user-images.githubusercontent.com/95587882/149922262-8035eede-759c-4baf-9761-ce8ef826d774.png)
![Screenshot (23)](https://user-images.githubusercontent.com/95587882/149922286-588470ba-bde4-41a2-b909-53ca97001cf9.png)

**Comment by RecursiveVision** [comment]
Some of these were indicators of balance changes mistakenly included in the Community Patch, thanks for pointing them out!
