### ISSUE TITLE
Incorrect AI opinions towards World Ideologies

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#8525]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch only, no Community Balance Overhaul

_3. Error description:_ 
There seems to be an error in determining how the proposal of a World Ideology affects AI civs. AI civilisations react negatively if their own ideology is proposed as a World Ideology:

![Screenshot (11)](https://user-images.githubusercontent.com/95587882/148660933-3e5788c3-6024-4aa2-b242-651a83ae1dbe.png)
![Screenshot (12)](https://user-images.githubusercontent.com/95587882/148660934-79d721d8-6882-4287-b9ba-ce201b376b09.png)

On the other hand, they also don't like it if the World Ideology is repealed, even if they follow a different ideology (Russia in the example below):
![Screenshot (14)](https://user-images.githubusercontent.com/95587882/148660954-6b86f927-03d8-4b34-b2f2-3e8b614ca8eb.png)
![Screenshot (15)](https://user-images.githubusercontent.com/95587882/148660956-fb7860b2-f284-4952-ab7d-8a080f31ada0.png)

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Mileslewis** [comment]
@RecursiveVision should be fixed now
