### ISSUE TITLE
(Community Patch only) Trade deals offered by AI include map trading

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#8526]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch only, no Community Balance Overhaul

_3. Error description:_ 
The AI sometimes offers trade deals that apparently include the trade of the explored world maps. This is not indicated in the description of the trade deal, and it's also not possible to offer those deals to the AI.

Before the trade deal:
![Screenshot (16)](https://user-images.githubusercontent.com/95587882/148662211-578075c5-ea81-4a28-a1a6-864f951621cf.png)

The trade deal itself:
![Screenshot (17)](https://user-images.githubusercontent.com/95587882/148662214-ece717db-eaf6-4c1d-b1e3-e8ba3fef4ccf.png)

After the trade deal:
![Screenshot (18)](https://user-images.githubusercontent.com/95587882/148662216-9b4cf0df-cdd5-4eeb-99be-e7c91c040b7c.png)

Save game (the deal will be offered in the next round):
[Augustus Caesar_0039 BC-1660.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7834123/Augustus.Caesar_0039.BC-1660.zip)

**Comment by RecursiveVision** [comment]
Ohoho, I see the problem. Fixed :)
