### ISSUE TITLE
preview for inquisitor / missionary impact

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#8529]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_3. Error description:_ 
The AI doesn't seem to understand that expending an inquisitor on a city will not necessarily turn it to its religion (or will not convert it to its religion for very long, either due to passive spread or another missionary coming in and replacing

This case happens when the majority pressure is *much* higher than the desired religion and/or pressure overall is very low.

Maybe it's doing this in a function other than CvReligionAI::ScoreCityForInquisitor()

**Comment by ilteroi** [comment]
oh, fat finger problem ... so what is the desired behavior? right now they do maximum damage, that's not bad is it?

**Comment by LessRekkless** [comment]
Maybe we make a SimulateErosion() function -> SimulateFollowers() that tells the player how many followers they gain by expending the inquisitor; then they can compare that to doing a ScoreCityForMissionary().  I *think* ScoreCityForMissionary() checks what the actual pressure levels will be at the end so it can determine how likely it is for the city to quickly flip backwards, and we will want to do this for inquisitors as well.

**Comment by Mileslewis** [comment]
Yea it would be good to have the same UI for Inquisitors as Missionaries, where you get to see beforehand what they will do.

**Comment by axatin** [comment]
Fixed by #10627
