### ISSUE TITLE
Impis

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#853]
Posted by skitter:
'Impis don't throw spears, and the tooltip says they do. Either a bug or a wrong tooltip. '

**Comment by ilteroi** [comment]
not sure i understand. what is the expectation here? impis get an additional ranged attack before their actual melee attack. can't verify right now, but that used to work at least. it's not very obvious though.

**Comment by LoneGazebo** [comment]
Is the combat animation being overwritten somehow?

**Comment by Edaka** [comment]
I have no idea if there's a problem, tbh. I thought the OP meant that the additional attack wasn't being registered. Probably should have checked before lazily copy-pasting this from the forum (:

**Comment by LoneGazebo** [comment]
No worries.

**Comment by ilteroi** [comment]
just checked and impis are as badass as ever. closing this

**Comment by LoneGazebo** [comment]
Yup, can confirm.
