### ISSUE TITLE
Poor AI settling decision

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#8534]
Latest build.
![Screenshot (8069)](https://user-images.githubusercontent.com/66801010/149182943-bb1affc1-2812-443f-9295-83435a763d8d.png)

The two civs are at war. Olsztyn seems like a decidedly poor settling choice, given its low defensibility (flat plains) and that it's two tiles away from an enemy unit.

**Comment by RecursiveVision** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7856261/Logs.zip)

Logs are included but they may be poor quality because 8 of the players are Poland (the other 4 are Shoshone). I'm making sure Rek's animation change doesn't crash the game. :)

**Comment by ilteroi** [comment]
well, defensibility is hard to define and plays little role in settling decisions (except then when in doubt they avoid very exposed coastal plots iirc)

enemy units are ignored if the settler has an escort

**Comment by RecursiveVision** [comment]
FWIW they didn't lose the city, but if it was a human..
