### ISSUE TITLE
1.3.4 conscript ships and lakes

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#8536]
![civconscript](https://user-images.githubusercontent.com/53142313/149301314-9854f74f-9575-43bd-8796-1ef72eb1d523.png)

Please no.

**Comment by bsesar** [comment]
Similar to  #8175?

**Comment by azum4roll** [comment]
Why not? I'd put it in the city as garrison so the Tercio can go elsewhere.

**Comment by ilteroi** [comment]
this is weird because there is an explicit check in getConscriptUnit() - only land units can be conscripted
