### ISSUE TITLE
AI doesn't disband/gift away units when oversupply

### ISSUE THREAD

**Issue by nobubblegums** [LoneGazebo/Community-Patch-DLL#8537]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4 (also present in earlier)

_2. Mod list (if using Vox Populi only, leave blank):_
Full VP

_3. Error description:_ 
I went through bunch of logs and it seems AI often doesn't disband units when it's over the supply limit. The code* allows it to have only 3 or 5 (if going for conquest) excess units but only when at war, yet the logs show AI holding on to their units even at peace and even when well over the limit. There's a check in place to force the AI to either gift away or disband their units when oversupply, but it doesn't seem to work. I'll eventually take a look into this, but until then here are some logs I've gathered from unrelated github issues and my autoplays.

[MilitarySummary_logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7866688/MilitarySummary_logs.zip)
(log 4 comes from a modded game with lower supply cap and no supply for naval units)
*The code can be found under DisbandObsoleteUnits() in CvMilitaryAI.cpp

**Comment by nobubblegums** [comment]
OK now that I've looked at the code again, these are the things that look off to me:

- It seems disbanding is not allowed before turn 100, makes no sense.
- Disbanding is also prevented if the AI isn't winning all the war it's currently fighting. I can see the merit in this, yet it'd be too easy to lock the AI in a losing war to prevent them from disbanding, then slowly increase their war-weariness to reduce their supply, and give them massive oversupply maluses. I'm not sure what'll be the ideal solution, maybe the AI should be able to disband as long as the war status isn't critical.

That said, I'm going through the logs and I'm not seeing AI disbanding stuff at peace (and after 100) either. Rather than disbanding, its supply cap eventually increases (possibly as war-weariness decreases and through the growth of cities) and that's how they stop being oversupply.

**Comment by azum4roll** [comment]
>  It seems disbanding is not allowed before turn 100, which makes little sense to me.
Aztecs used to build a ton of Jaguars and disband them before this change.

**Comment by RecursiveVision** [comment]
STATE_ALL_WARS_LOSING is definitely a better check to see if the AI's military situation is negative enough not to disband.

**Comment by ilteroi** [comment]
> > It seems disbanding is not allowed before turn 100, which makes little sense to me.
> 
> Aztecs used to build a ton of Jaguars and disband them before this change.

this is such a bad hack ... how about not building too many in the first place? or avoiding disbanding unique units?

**Comment by RecursiveVision** [comment]
City production AI needs revision IMO

**Comment by nobubblegums** [comment]
I think I fixed what caused cities to keep building units when oversupply, needs more testing to be sure but it will be an improvement in any case. I can push it tomorrow night

**Comment by nobubblegums** [comment]
Will be fixed or considerably improved in the next version
