### ISSUE TITLE
Red-box/Glitchy Textures for Ordo & Hacienda

### ISSUE THREAD

**Issue by nobubblegums** [LoneGazebo/Community-Patch-DLL#8538]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_
VP

_3. Error description:_ 
Ordo has redboxes (signaling missing/incompatible texture IIRC) below the improvement, and on the improvement for Hacienda. Tested it with VP 1.2, so this shouldn't be related to my compression crusade.

**Comment by RecursiveVision** [comment]
@pin

**Comment by RecursiveVision** [comment]
@pineappledan

**Comment by nobubblegums** [comment]
This is weird, both seem fine in DX11, and very, very rarely I had Ordo work fine in DX9.
