### ISSUE TITLE
Trade Route and River Bonus (v11/30 beta)

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#854]
Either the patch note or the sql is incorrect.

- patch note
Reduced river bonus for International TRs to **15%** (was 33%)

- Community Balance Patch\Balance Changes\CoreDefines.sql (Line: 25)
-- Trade Route Stuff
	UPDATE Defines
	**SET Value = '20'**
	WHERE Name = 'TRADE_ROUTE_RIVER_CITY_MODIFIER';

![trade route](https://cloud.githubusercontent.com/assets/11933188/11500837/022246f2-9873-11e5-9d5b-89751d34e241.png)

**Comment by LoneGazebo** [comment]
Patch notes. I'll fix. I had 15 in testing and bumped back to 20 in last test but forgot to update. 

Patch was a little bit rushed, as I need balance tests on internal routes.

**Comment by 8h42** [comment]
I got it.
Thank you for all your hard work.

**Comment by LoneGazebo** [comment]
Thanks! I'll update the patch notes.
G
