### ISSUE TITLE
Crashing within 2 turns

### ISSUE THREAD

**Issue by Neborya** [LoneGazebo/Community-Patch-DLL#8543]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

The game will either crash during my own turn after I press "Next turn", or during the AI turn. If not, it will crash during my next turn, or during the next AI turn... 

[Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7875527/Save.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7875528/Logs.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7875529/CvMiniDump.zip)

**Comment by ilteroi** [comment]
you can try the dll linked here: #8539

**Comment by Neborya** [comment]
No CTDs so far, but I've lost all faith, as my primary religion has become my primary religion...

**Comment by RecursiveVision** [comment]
No idea what's up here
