### ISSUE TITLE
CvReligionClasses::GetStateReligion() should be used more.

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#8544]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_3. Error description:_ 
The following code sample appears a lot in the code; it asks "are you the founder of the religion; if not, do you have the religion in most of your cities".
```
CvGameReligions* pReligions = GC.getGame().GetGameReligions();
ReligionTypes eFoundedReligion = pReligions->GetFounderBenefitsReligion(GetID());
if (eFoundedReligion == NO_RELIGION)
{
    eFoundedReligion = GetReligions()->GetReligionInMostCities();
}
```
There are a lot of these types of checks, and they could just be replaced with GetStateReligion() now. It's slightly different, because GetStateReligion() also checks for "acquired" religions, and that's based off of majority of domestic followers, not majority of cities, but I think it's worth the change.

**Comment by RecursiveVision** [comment]
It is now.
