### ISSUE TITLE
Incorrect notification for the Great Musician tour

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#8546]
1. Mod version (X.Y.Z, e.g. 1.3.4): 1.3.4

2. Mod list (if using Vox Populi only, leave blank):

3. Error description:  I am playing as Egypt and have bulbed a Great Musician in Rome territory. However, the pop-up notification incorrectly says "Tour of Egyptian lands completed" (see the screenshot below). I don't know if just the notification is wrong or also the bulbing of the GM.

4. Steps to reproduce (optional): Load the attached save and bulb the GM.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7876798/bug.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![musician_tour](https://user-images.githubusercontent.com/620131/149657174-b4ddcabe-0beb-43e5-bca6-62706fb57096.jpg)

**Comment by nobubblegums** [comment]
Yeah I always forget reporting this, this also happens to me. And not just v1.3.4, I had this with earlier versions too
