### ISSUE TITLE
Relations not written in declare war window

### ISSUE THREAD

**Issue by Tarzan737** [LoneGazebo/Community-Patch-DLL#8548]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_ 1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_

Bunch of mods

_3. Error description:_  Can´t see correct diplomatic relations when i shall declare war, i know a civilization have
a defensive pact or vassal but it doesent show that in "declare war window" and in picture i upload it´s written we have defensive pact but its not true.. and i had denounced him.

_4. Steps to reproduce (optional):_ always

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screensho
![Skärmbild (7)](https://user-images.githubusercontent.com/20152388/149677762-cd78e2b3-2ece-47ba-a84b-e7f5bd959106.png)
ts (optional):

**Comment by RecursiveVision** [comment]
Not nearly enough information to be actionable and no one else has reported this so it's probably your installation or mod conflicts.
