### ISSUE TITLE
CTD's, three versions

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#855]
These were posted in forum, but just wanted to be thorough and make sure they have visibility. Thank you.
http://forums.civfanatics.com/showpost.php?p=14075022&postcount=3906

**Comment by LoneGazebo** [comment]
I'll give it a look, thanks. Also, could you post your modlist?
G

**Comment by Iamblichos** [comment]
Mod list: CPP
My Transport mod, which you have. Still wonder if that one causes an issue or not.
XIA-Erlitou (Chinese Civ)
Some other custom LUA code I've written that shouldn't affect it, unless you found it crashes out on LUA operations. Than I'll do some digging into it.

**Comment by LoneGazebo** [comment]
Took a look - all three break in the pathfinder, which ilteroi is currently rewriting. We'll see if his rewrite fixes it.

**Comment by Iamblichos** [comment]
Thanks a bunch for your relentless support!

**Comment by Iamblichos** [comment]
Been running lots of sim games with 12-4 and haven't had any crashes so far. About to run some with 12-6.

**Comment by LoneGazebo** [comment]
Sounds good!

**Comment by Iamblichos** [comment]
Haven't gotten any crashes with 12-6 after several sim games. Shall we call it good?

**Comment by Iamblichos** [comment]
Check that: just got two crashes back to back on Turn 1....strange..

http://forums.civfanatics.com/showpost.php?p=14083751&postcount=3971

**Comment by LoneGazebo** [comment]
Any special conditions?

**Comment by Iamblichos** [comment]
No not really. crashed both on turn 1 after I did my turn. most of my sim games have gone for 350+ turns without a hitch. I did implement your new table though for Improvements enhancing other adjacent improvements on a unique ottoman improvement I made. But that shouldn't matter on turn 1.

**Comment by LoneGazebo** [comment]
Okay, both minidumps crash here, so you've got a lua problem.


//------------------------------------------------------------------------------
bool LuaSupport::CallHook(ICvEngineScriptSystem1* pkScriptSystem, const char* szName, ICvEngineScriptSystemArgs1* args, bool& value)
{
	// Must release our lock so that if the main thread has the Lua lock and is waiting for the Game Core lock, we don't freeze
	bool bHadLock = gDLL->HasGameCoreLock();
	if(bHadLock)
		gDLL->ReleaseGameCoreLock();
	bool bResult = pkScriptSystem->CallHook(szName, args, value);
	if(bHadLock)
		gDLL->GetGameCoreLock();
	return bResult;
}

**Comment by Iamblichos** [comment]
Thanks. I think I can narrow it down of which lua is causing it since it is on turn 1. Let you know when I got it fixed and we'll close this out. I think the pathfinder issue is good though.

**Comment by Iamblichos** [comment]
Got it!

**Comment by LoneGazebo** [comment]
Awesome. I'm relieved that it was lua and not the DLL! :)

G
