### ISSUE TITLE
Number of city-state types could be more balanced

### ISSUE THREAD

**Issue by nobubblegums** [LoneGazebo/Community-Patch-DLL#8551]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The distribution of CS' along types can differ widely, check this game with 3 militaristic, 3 cultured, and 3 maritime city-states, without any religious or mercantile. I think a baseline could be that if CS numbers >= 5 one of each should be present in-game, with TypeWithMaxCS - TypeWithMinCS = 2.

![image](https://user-images.githubusercontent.com/94949778/149878754-731ce608-7815-46a1-8c75-e8a4e8063c96.png)
(one cs got conquered it seems)

**Comment by axatin** [comment]
City-state distribution has been reworked by now. Further suggestions should be discussed in congress.
