### ISSUE TITLE
AI doesn't properly utilize Great Admirals

### ISSUE THREAD

**Issue by nobubblegums** [LoneGazebo/Community-Patch-DLL#8552]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I often see AI sitting their admirals at cities while they could've been boosting a naval group. In this SS you can see Portugal harassing Sao Paolo with ships, while they have 4 admirals idle at cities. Since this is with a test game with custom DLL & mods I can't provide a save, but I've seen this behavior a lot with just VP. AI also often doesn't assign an escort to Admirals when transporting them, leaving them vulnerable. In fact the bandeirantes at the bottom-left just killed an Admiral travelling alone to probably Braga or Sao Paolo
While at it, I often see the AI sending its ships one by one instead of forming groups. 

![20220118085849_1](https://user-images.githubusercontent.com/94949778/149879542-cfee2289-8f12-4c87-9566-2e12b383f31c.jpg)
a

**Comment by nobubblegums** [comment]
[PlayerTacticalAILog.csv](https://github.com/LoneGazebo/Community-Patch-DLL/files/7893801/PlayerTacticalAILog.csv)
[MilitaryAILog.csv](https://github.com/LoneGazebo/Community-Patch-DLL/files/7893802/MilitaryAILog.csv)
[OperationalAILog.csv](https://github.com/LoneGazebo/Community-Patch-DLL/files/7893803/OperationalAILog.csv)

For some reason github doesn'T allow me to upload zips (apparently a known issue), here are the logs I thought would be relevant.

**Comment by ilteroi** [comment]
hmm the NAVAL_SQUADRON and NAVAL_BOMBARDMENT army formations don't have slots for admirals. maybe an optional slot should be added.

**Comment by nobubblegums** [comment]
Yeah it seems BNW has those, so I just went ahead and added them without really testing much, seems safe enough.
