### ISSUE TITLE
General/Admiral Supply Boost gets reduced by tech

### ISSUE THREAD

**Issue by nobubblegums** [LoneGazebo/Community-Patch-DLL#8561]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

This was reported on discord. I briefly looked over the code, it seems GG supply is added to the capital city as a flat bonus, hence it gets modified by tech supply reduction, and maybe more importantly GG supply bonuses are lost if the player loses capital (the new conqueror doesn't get it though). It could be a good idea to store GG supply separately to be added with GetNumUnitsSupplied.

**Comment by pineappledan** [comment]
I strongly support this. The GG and GAdmiral supply is a rare enough occurence in most games that making them an exception to tech reduction shouldn't inflate supply too much overall. More importantly, not actually getting 2 supply when the game says you got +2 supply feels bad.

Also I had no idea that the supply was stored in the capital. That does indeed sound like it needs to be fixed.
