### ISSUE TITLE
database errors

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8562]
custommods.log says for every player:
```
CvPlayer.cpp[10578]: CvPlayer::GetSpecificUnitType - GetSpecificUnitType for player Napoleon: UNITCLASS_GALLEY is UNKNOWN!!!
CvPlayer.cpp[10578]: CvPlayer::GetSpecificUnitType - GetSpecificUnitType for player Napoleon: UNITCLASS_ASSYRIAN_SIEGE_TOWER is UNKNOWN!!!
CvPlayer.cpp[10578]: CvPlayer::GetSpecificUnitType - GetSpecificUnitType for player Napoleon: UNITCLASS_GALLEY is UNKNOWN!!!
CvPlayer.cpp[10578]: CvPlayer::GetSpecificUnitType - GetSpecificUnitType for player Napoleon: UNITCLASS_ASSYRIAN_SIEGE_TOWER is UNKNOWN!!!
```

don't know if this is benign, but still ...

**Comment by nobubblegums** [comment]
Hm I think I have an idea about what's causing this. These units miss a DefaultUnit in UnitClasses, probably to prevent other Civs from building them. Barbs and Assyria get the units (Unit_Type) in Civilization_UnitClassOverrides. I think we could prevent these errors if we set a DefaultUnit in UnitClasses, then give all non-barb/non-assyria civs null overrides in Civilization_UnitClassOverrides (as it's done to prevent barbs from building most units). However, that would probably result in modded civs being able to build Galley and Siege Tower. There's a "create trigger" method in SQL that runs each time a table is altered (even by non-referenced mods), maybe we can use that to give nulls to modded civs, I think @pineappledan knows how to do that.

**Comment by ilteroi** [comment]
i have not opinion on this, do whatever you think is best ...

**Comment by RecursiveVision** [comment]
@nobubblegums Would rather not use dummies. Create Trigger works, you can see an example of it with `CREATE TRIGGER Leaders_Personality` in CoreTableEntries.sql

**Comment by nobubblegums** [comment]
So that "give defaultunit but override with null" thing didn't work, still getting errors. I guess we'll need to edit CvPlayer::GetSpecificUnitType

**Comment by RecursiveVision** [comment]
Well that should be easy
