### ISSUE TITLE
Splendor's tooltip doesn't mention +3 food for Palace Garden

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#857]
![pg](https://cloud.githubusercontent.com/assets/12978597/11520666/22247408-98ae-11e5-86f8-184c5f1e02e4.jpg)
By the way, do you think changing the food to +3 science would be a bad idea? There's already loads of food from the opener and the scaler (13 total if I'm not mistaken), it seems weird to have another 3 food from one of the policies.

**Comment by LoneGazebo** [comment]
Science makes sense to me.
