### ISSUE TITLE
city capture is a performance drag

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8571]
in my current testgame 6.4% of the time was spent in CvPlayer::CheckForMurder().

this is massive, considering city capture does not happen so often.

it goes down to diplo AI which then triggers a recomputation of all tactical maps ... any way to optimize this?

relevant callstack:

![image](https://user-images.githubusercontent.com/1358966/150740869-c22b56f3-6f2f-4f77-9157-5d7a987edfdf.png)

**Comment by RecursiveVision** [comment]
@ilteroi I could remove the call to DoUpdateWarStates(), at the cost of the AI potentially making suboptimal decisions with their lost city not being factored in.

**Comment by ilteroi** [comment]
tactical map update is expensive ... right now the "out of date" check is done based not on turns but on turn slices. so if you iterate all players and access their tactical map, all need to be updated. then when it's the players' own turn, it will update again.

going to turn based updates or an explicit "dirty" flag could also work ... so maybe i can fix this on my side with little impact.

**Comment by ilteroi** [comment]
city capture might also invalidate tactical maps so they need to be regenerated but only for the affected players ...
