### ISSUE TITLE
National Intelligence Agency wrong column

### ISSUE THREAD

**Issue by 1andUnly** [LoneGazebo/Community-Patch-DLL#8572]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: NIA states that it only gives 15% better spy protection in the city -- which it does using the column "EspionageModifier" -- but it's also applying it globally through the column "GlobalEspionageModifier", used by wonders like Bletchley and Great Firewall. You can see in the screenshot that it's listed in the "Extended Information".

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Screenshot (1013)](https://user-images.githubusercontent.com/59460164/150816679-3f761c4e-4528-4433-bde3-29d8a8dcf733.png)

**Comment by psparky** [comment]
Also, Bletchley Park and Great Firewall don't match their descriptions either - BP shouldn't set EspionageModifier and GFW should set it to -75 (to make -100 in total).

Or the descriptions should be updated of course...
