### ISSUE TITLE
[1.3.4] Moving certain Great Works doesn't work and brings +500 Golden Age Points instead (repeatedly)

### ISSUE THREAD

**Issue by Abros96** [LoneGazebo/Community-Patch-DLL#8577]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I want to move the painting "Zhou Maoshu Appreciating Lotuses" from the Parthenon in Moscow to the Museum in Moscow. It doesn't work. Instead I receive +500 Golden Age Points with every try.

I've experienced this bug several times before with different Great Works.

Strangely, it does work if I move the first painting in the Museum to another place, then move "Zhou Maoshu" to the first spot of the Museum and then move the other painting to the second spot (but only if I click the empty spot first and then the painting).

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Great Works bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7938826/Great.Works.bug.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Great Works bug save file.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7938832/Great.Works.bug.save.file.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bsesar** [comment]
This issue was already reported in  #8475.

**Comment by Abros96** [comment]
Ok, sorry. Then I will close it.
