### ISSUE TITLE
Founding identical pantheon with Byzantium, after Byzantium

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#858]
I know that Byzantium should be able to take any pantheon at any time, but I'm not sure if it should work the other way around, too. I was able to found God of the Open Skies after Byzantium took that exact same pantheon a couple of turns before.

**Comment by LoneGazebo** [comment]
Technically that's how Whoward had that particular element coded - it's working as designed, but I don't necessarily like it.

**Comment by LoneGazebo** [comment]
I'll fix.
