### ISSUE TITLE
ai offers peace instead of conquering a city

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8584]
the iroquois were about to re-conquer ulundi from me and kill a whole bunch of units but instead they offered peace ... savegame here
[AutoSave_Post_0292 AD-1844.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7966933/AutoSave_Post_0292.AD-1844.zip) (version bae41841b93542027aba0b07a67dc1406e5f22b2)

**Comment by RecursiveVision** [comment]
@ilteroi 
![4eac728ed80f013d83514daf13ecf814](https://user-images.githubusercontent.com/66801010/152249416-16433e13-bfd8-4176-9494-3feaa76eedfc.png)

InfoAddict affects savegame compatibility...if you're continuously getting savegame errors this might be the culprit?

**Comment by RecursiveVision** [comment]
@ilteroi
So two issues: one was an error in CvPlayer::DoTestEmpireInBadShapeForWar(), which I fixed...the other is that Ulundi was returning false for CvCity::IsInDanger() - and it certainly was in danger, so the calculation would need to be modified to account for the issue. Perhaps consider city HP in this as well?

**Comment by ilteroi** [comment]
> @ilteroi ![4eac728ed80f013d83514daf13ecf814](https://user-images.githubusercontent.com/66801010/152249416-16433e13-bfd8-4176-9494-3feaa76eedfc.png)
> 
> InfoAddict affects savegame compatibility...if you're continuously getting savegame errors this might be the culprit? Trying to load a non-InfoAddict game with InfoAddict enabled?

good point

**Comment by ilteroi** [comment]
fix IsInDanger() also
