### ISSUE TITLE
Units abandon citadels during retreat

### ISSUE THREAD

**Issue by MontyJavasFly** [LoneGazebo/Community-Patch-DLL#8587]
1.3.4, CPP only, tons of other mods that shouldn't affect this

AI often abandon citadels during war, allowing enemy to simply walk in and capture them, while the AI still has multiple units nearby. Citadels within 5 tiles of enemy units (or any unsure border) should be absolute top priority for at least one unit (preferably ranged).

Additional logic suggestion: tiles adjacent to an owned citadel should have a large bonus to placement. Tiles adjacent to a citadel but further from enemy units than the citadel itself should have a very large bonus to placement, as they require enemy to usually come adjacent to the citadel (and take dam) to directly assault their position. See image:

https://imgur.com/a/nxc9onQ

**Comment by ilteroi** [comment]
that additional logic is unfortunately hard to translate into code ... AI is not so smart.

but yeah, i found a bug, they should not give up citadels so easily now.
