### ISSUE TITLE
'git' is not recognized as an internal or external command...

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#8589]
@ilteroi Getting the following error from your batch file when I compile. Not sure if it affects anything, but if another tool is needed to build the DLL, that should be documented so modders can set that up :)

![Error](https://user-images.githubusercontent.com/66801010/151901761-6a362013-fc7f-4a00-af59-096ad3fc0357.png)

**Comment by RecursiveVision** [comment]
For reference, I'm using Github Desktop and Windows 10.

**Comment by ilteroi** [comment]
the regular git command line client must be in your path

**Comment by RecursiveVision** [comment]
To all modders, the Git command line client must now be installed to build the Vox Populi DLL correctly. https://git-scm.com/downloads

When you encounter the installer prompt "Adjusting your PATH environment", select the recommended option:
![515afb524e773bda456caad58feb08d6](https://user-images.githubusercontent.com/66801010/151926733-3cf6e5e1-bab3-415a-836b-d84dceb97b26.png)
