### ISSUE TITLE
God of the Open Skies

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#859]
I think it still counts plains with features (hills, forests). Take a look at these:
![gotos](https://cloud.githubusercontent.com/assets/12978597/11520797/692790e6-98af-11e5-9a8a-9ac87c4978a5.jpg)
![gotos2](https://cloud.githubusercontent.com/assets/12978597/11520800/6ac8d658-98af-11e5-87fc-af288bb24b90.jpg)
![gotos3](https://cloud.githubusercontent.com/assets/12978597/11520802/6c1ac520-98af-11e5-89f0-18af1015ab28.jpg)
There are only 5 truly featureless plain tiles on the first screenshot, 5 on the second, 1 on the third (if we're counting in a two tile radius). I'm getting much more culture than I should be.

**Comment by LoneGazebo** [comment]
Fixed in last beta.
