### ISSUE TITLE
CTD when i'm in war and close of a city enemy

### ISSUE THREAD

**Issue by Minidumpfile** [LoneGazebo/Community-Patch-DLL#8594]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4 (December 27, 2021)​

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi Automatic Installer with EUI

_3. Error description:_ 
Early in the game : turn 47. I'm in a war with China and the game CTD to all my tentatives. I tried to test some diferents moves for knowing what was the "bad thing". The game CTD when i'm close to the city, like two tiles and when i'm in war with the leader of the city concerned. I was trying the game with CPP a year before and that was the same, always CTD when i'm in conflict, haha.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Database.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7982052/Database.zip)
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7982056/Lua.zip)
[xml.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7982058/xml.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Kaya Magan_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7982044/Kaya.Magan_0000.BC-4000.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7982046/CvMiniDump.zip)

**Comment by RecursiveVision** [comment]
@Minidumpfile Do you mean "Community Patch only" or are you playing with all VP components?

**Comment by Minidumpfile** [comment]
Sorry, it was a confuse formulation. Yes, all the VP components, EUI version. I just follow the automatic installer.

**Comment by RecursiveVision** [comment]
Can't load the savegame

**Comment by Minidumpfile** [comment]
Very weird, i really dont use other mods. If I just can play with VP i'm okay. 
I give you the save again, maybe i don't use 7zip correctly with it.


[Kaya Magan_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/7991652/Kaya.Magan_0000.BC-4000.zip)

**Comment by RecursiveVision** [comment]
@Minidumpfile Are you 100% certain you were playing with the 1.3.4 version? You didn't update versions midgame?

**Comment by Minidumpfile** [comment]
Yes, i take the mod from https://forums.civfanatics.com/threads/community-patch-how-to-install.528034/ and juste download the automatic installer.

**Comment by Minidumpfile** [comment]
@RecursiveVision did you try to load again my savegame ?

**Comment by RecursiveVision** [comment]
@Minidumpfile Yes - still couldn't load, unfortunately.
