### ISSUE TITLE
CTD when founding capital

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#8599]
No idea what's up with this, but it was called from this line:
`CUSTOMLOG("No Stat for selected Wonder %s",szWonderType)`
where szWonderType is `BUILDINGCLASS_PALACE`.

Could this be related to your CUSTOMLOG changes, @ilteroi ?

![42ab91cccc614035eb80568f22b848a7](https://user-images.githubusercontent.com/66801010/152268531-ad73e405-1df0-456a-8bb5-954d0bbf62c5.png)

**Comment by RecursiveVision** [comment]
Yeah it seems to be, you changed that line!

**Comment by ilteroi** [comment]
ouch. yes disable it for now
