### ISSUE TITLE
Duplicated peace treaty expiration messages

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#860]
![peacenotif](https://cloud.githubusercontent.com/assets/12978597/11520896/22df88b8-98b0-11e5-9b4a-c9d30491b12c.jpg)
The other one in the queue is exactly the same.

**Comment by LoneGazebo** [comment]
<shrugs> I'unno. Seems like an EUI quirk (as it uses the 1/2 element). Report to bc1?

G

**Comment by Edaka** [comment]
Yeah, forgot to specify that's with EUI. Not a big deal anyway (:
