### ISSUE TITLE
AI Civs Bipolar Friendship Disorder

### ISSUE THREAD

**Issue by calloatti** [LoneGazebo/Community-Patch-DLL#8600]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_

1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Afraid Vassal Civ accepts Declaration of Friendship, only to end it and go back to be Afraid the next turn. If asked for friendship again, it will accept and the cycle can go on forever.

STEP 1: VASSAL CIV AFRAID OF US:

![image](https://user-images.githubusercontent.com/12817862/152279103-7526092f-73ea-4420-b925-72eb95577bbe.png)

STEP 2: ASK FOR FRIENDSHIP:

![image](https://user-images.githubusercontent.com/12817862/152279146-1d048984-cdad-4e73-96de-651a832ca4b1.png)

STEP 3: CIV ACCEPTS! WE ARE FRIENDS NOW!

![image](https://user-images.githubusercontent.com/12817862/152279201-39b5c2c8-1ffe-4ce6-966e-48d2fcf3ad2a.png)

STEP 4: NEXT TURN, BACK TO SQUARE ONE:

![image](https://user-images.githubusercontent.com/12817862/152279263-6121306b-2390-4f79-9bd7-1ebdbb96ffee.png)

GOTO STEP 1.

**Comment by RecursiveVision** [comment]
lol...
