### ISSUE TITLE
Not possible to buy spaceship parts with gold

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#8602]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch only

_3. Error description:_ 
The Social Policy in the Freedom ideology that allows you to buy spaceship parts with gold seems not to work. When clicking on "Buy" in a city screen, no spaceship parts appear in the list.

**Comment by CommieDog** [comment]
I can confirm that this issue exists in 1.4.4 as well.

**Comment by axatin** [comment]
The reason for the problem is the following: In CvCity::GetPurchaseCost(UnitTypes eUnit), a negative value (indicating no purchase possible) is returned if the entry "HurryCostModifier" for the unit is -1 in the database. And this is the case for all spaceship parts.
![Screenshot (44)](https://user-images.githubusercontent.com/95587882/154809295-d90d56d7-e7bf-4d17-b8e4-8ca67dc8b28d.png)
![Screenshot (45)](https://user-images.githubusercontent.com/95587882/154809297-9a092e20-3b4e-4b98-8af7-90a1499c09b8.png)
