### ISSUE TITLE
Submarines can attack cities

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#8603]
_1. Mod version (X.Y.Z, e.g. 1.3.4):_
1.3.4

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch only

_3. Error description:_ 
I don't know if this is intentional, but in the Community Patch, submarines are able to attack cities. In the vanilla game they had a special promotion that prevented this. Giving them the ability to attack cities makes them really overpowered in my opinion...

**Comment by RecursiveVision** [comment]
@LessRekkless This is Community Patch only.
