### ISSUE TITLE
Communitu_79a v2.3.1 generating rivers next to ocean coasts

### ISSUE THREAD

**Issue by Hokiefan00** [LoneGazebo/Community-Patch-DLL#8608]
_1. Mod version 1.4.1

_2. Mod list 
Really Advanced Setup v15
Promotion Icons for VP v3

_3. Error description:_ 
Two maps in a row have included rivers showing up right next to ocean coasts.

_4. Steps to reproduce (optional):_
My settings for the map are:
Standard size
2 Pacific oceans
Circumnavigation on
All others = default

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/84920557/152664818-084e66d9-450b-4bd7-85cb-1306a186c5ea.png)

**Comment by RecursiveVision** [comment]
@azum4roll
