### ISSUE TITLE
Happiness from National Wonders and Tradition

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#861]
Most NWs and the palace provide 2 happiness with the new Tradition policy now; however, there are exceptions that still provide 1 happiness. These include the Scrivener's Office, the three Ideology NWs and the Foreign Bureau.

**Comment by LoneGazebo** [comment]
mm, I'll fix.

**Comment by Edaka** [comment]
By the way, all these buildings are located in the 'Buildings' Civilopedia section instead of the 'Wonders' one, where all other NWs are.

**Comment by LoneGazebo** [comment]
I have no idea why it is doing that (the civilopedia thing), as the civilopedia sorting data is untouched.

G

**Comment by LoneGazebo** [comment]
If anyone can help figure out the LUA issue with the civilopedia, that'd be great. No idea why it suddenly changed.
