### ISSUE TITLE
Goddess of Protection is not increasing healing

### ISSUE THREAD

**Issue by legenciv** [LoneGazebo/Community-Patch-DLL#8612]
_1. Mod version (X.Y.Z, e.g. 1.4.1):_
1.4.1.

_2. Mod list (if using Vox Populi only, leave blank):_
34UC (v75)
Milae's alternative difficulty for VP (v10)
Promotion Flags EUI for VP (v3)

_3. Error description:_ 
Units healing in owned territory aren't healing under the Goddess of Protection pantheon.

**Comment by Padre19** [comment]
Also BELIEF_GOD_WAR does not grant faith from kills.

**Comment by pineappledan** [comment]
@RecursiveVision @LessRekkless

**Comment by pineappledan** [comment]
I had a report that Trickster God isn't working either
