### ISSUE TITLE
Should the Americans be able to buy citadels?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8614]
seems a bit cheesy

**Comment by nobubblegums** [comment]
Yeah, that should be off limit

**Comment by pineappledan** [comment]
We've had this conversation before. It's fine and good
https://forums.civfanatics.com/threads/america.539387/page-17#post-15869825

**Comment by ilteroi** [comment]
ha. one comment does not equal a discussion. nice to provide the link but i don't think it proves what you want it to prove.

**Comment by pineappledan** [comment]
Look again, it’s three comments saying no, and 1 outright mocking the sentiment, and then a handful more users liking those comments that say leave it alone

**Comment by ilteroi** [comment]
well i don't really care ... human players can manage. the trigger was i observed other AI players having their citadels turned against them. if you could fix that, that would be great.

**Comment by pineappledan** [comment]
Well maybe you should? 

The prevailing sentiment was that this is just a natural outcome of America's ability. If you want to make a scalpel change that the AI chooses not do this to other AI, but the players can still do it and AI will still do it to players, then fine. If you change this then people will complain about it, and then you'll be asked to change it back.
