### ISSUE TITLE
1.4.1 Cannot build units over supply cap

### ISSUE THREAD

**Issue by randomnublet** [LoneGazebo/Community-Patch-DLL#8615]
Not sure if a bug or undocumented feature but I don't like it, there were already penalities for building over supply cap and this removes a player choice.
![civsupply](https://user-images.githubusercontent.com/53142313/152759215-bd82d1b5-943c-4ced-9af6-9634ef995ebe.png)

**Comment by nobubblegums** [comment]
Not intended, I'm on this
