### ISSUE TITLE
VP 1.4.1 No Resources on VP Communitas Map Script

### ISSUE THREAD

**Issue by jayeye2011** [LoneGazebo/Community-Patch-DLL#8617]
_1. Mod version (X.Y.Z, e.g. 1.4.1):_
VP 1.4.1 with EUI

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The Communitas.lua map script that is included in VP 1.4.1 does not generate any starting resources.

![No starting resources](https://user-images.githubusercontent.com/69315126/152819771-50c5e7f1-ad6b-4220-8100-3c5bfc5ddb18.jpg)

_4. Steps to reproduce (optional):_
Communitas default settings were used. Standard size.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repos
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8016575/Logs.zip)
itory's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Augustus Caesar_0009 BC-3640.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8016584/Augustus.Caesar_0009.BC-3640.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@azum4roll

**Comment by azum4roll** [comment]
Communitas is incompatible with full VP. Please use Communitu_79a instead.

**Comment by jayeye2011** [comment]
Does this mean  that the Civilization V vanilla DLC map scripts I own can also become incompatible with VP when the next AssignStartingPlots change is made someday in the future so that the Commuitu_79a map script is one that will be guaranteed to work going forwards? If that's the case, I would vote that AssignStartingPlots.lua be reverted back to where it remains compatible.

**Comment by jayeye2011** [comment]
Since the Communitas.lua script is incompatible, it should not be included in the Vox Populi installer.

**Comment by azum4roll** [comment]
As long as maps don't override AssignStartingPlots functions they're always compatible.
