### ISSUE TITLE
Feature request: tourism and influence notifications link with Culture Overview

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#862]
I'm thinking about two types of popup notifications: 1) the 'Influence Shift' one; 2) the 'Historic Moment' one.

1) Left clicking on this one takes you to the 'Culture Victory' tab in the 'Culture Overview' window. I think it'd be more convenient if it took you to the 'Influence by Player' tab instead - the former doesn't really come into play until ideologies anyway and the latter is more informative about the actual influence levels.

2) This one functions exactly like the first at the moment - however, you get these much more frequently and they often come a handful at a time (2-3 and more at one turn). As you know, EUI groups those notifications in one button, so to scroll between those you need to click them, which results in the 'Culture Victory' tab being brought up every time I just want to gape in awe at my cultural power and majesty (: I'd suggest removing the link alltogether if it's possible.

I hope these UI elements won't cause too much trouble to look into.

**Comment by LoneGazebo** [comment]
1.) I can't do this, as it's actually hard-coded behind a hash that I've been unable to work with.

I'll just disable the click link.

**Comment by Edaka** [comment]
Ah, well, that will work just as fine. Thanks!
