### ISSUE TITLE
Celts not getting 3 Faith from UA

### ISSUE THREAD

**Issue by pineappledan** [LoneGazebo/Community-Patch-DLL#8620]
_1. Mod version: 1.4.1

_3. Error description:_ Celts UA is 3 Faith in all cities with their majority religion. They are not getting the 3 faith per city before founding a major religion. It used to work that you got faith once the pantheon was founded, and then when you founded the faith was tied to your religion only, so the cities with only your pantheon didn't get faith until they were converted to your religion.

With the faith only being given if the city has a religion, and with no pantheons giving any faith, I'm not sure how Celts can be expected to found anymore

![image](https://user-images.githubusercontent.com/33136027/152897709-3db7ab95-e775-4770-8ed9-4664c61f4af2.png)

**Comment by pineappledan** [comment]
I propose that all celt pantheons be given 3 Faith per city. This would delay the yields until the pantheon is founded, and it would still be tied to Celt's pantheon, so they can be removed through conversion, but it would take away the janky switchover on the found while also fixing this glitch

**Comment by LessRekkless** [comment]
Error has the same cause as #8612.

No comment on suggestion for now.
