### ISSUE TITLE
Unit production malus despite no unhappiness

### ISSUE THREAD

**Issue by 1andUnly** [LoneGazebo/Community-Patch-DLL#8621]
_1. Mod version (X.Y.Z, e.g. 1.4.1): 1.4.1

_2. Mod list (if using Vox Populi only, leave blank): Mods included, but you have to manually add 3/4UC (v75) due to Git not allowing the file size.

_3. Error description: There's a negative production modifier being applied to my units in a city(ies), despite the fact that both local and global happiness are positive. I believe it's because of the war weariness; local happy is even/positive, but the -1 or -2 in each city from weariness is flagging the city(ies) to still enforce the malus, regardless of the situation or numbers involved. Check my Capital in the save provided.

_4. Steps to reproduce (optional): Be in a lengthy war to accumulate some weariness; make sure global happy is positive. Que any unit into a city with positive local happiness and witness the production modifier kick in. 

4. Screenshots (optional):
![Screenshot (1052)](https://user-images.githubusercontent.com/59460164/152924233-de1be4ad-bfd6-4ca4-9f49-63b8f1c6b375.png)
![Screenshot (1053)](https://user-images.githubusercontent.com/59460164/152924244-5880a68a-c140-47e9-8168-dd098e286c53.png)
![Screenshot (1054)](https://user-images.githubusercontent.com/59460164/152924263-3fe8358a-0a5c-4df1-9531-498c808ffb5f.png)

[Otto_Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8021011/Otto_Bug.zip)
[Mods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8021023/Mods.zip)

**Comment by nobubblegums** [comment]
this was also reported in discord, but the issue cleared in the next turn in that case
