### ISSUE TITLE
GPExtra

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#8623]
GPExtra from Units table does not work.
When generated, the next threshold of a Great Doctor (personal mode) remains at 150 ( not 400 as it should be).

**Comment by Padre19** [comment]
@LoneGazebo Can you fix this? Thanks in advance.

**Comment by LoneGazebo** [comment]
Is that how the table is supposed to work? GP iterations are hard-coded in the DLL.

G
