### ISSUE TITLE
cppcheck 2.7 analysis

### ISSUE THREAD

**Issue by JohnsterID** [LoneGazebo/Community-Patch-DLL#8624]
In celebration of [cppcheck 2.7](https://github.com/danmar/cppcheck), a new run.

`cppcheck --max-ctu-depth=99 --cppcheck-build-dir=C:\Users\user\Downloads\community-patch-dll-cppcheck-build-dir --enable=warning,performance,portability --force --std=c++03 --suppress=uninitMemberVar --suppress=useInitializationList --suppress=postfixOperator --suppress=nullPointerRedundantCheck --suppress=identicalInnerCondition --suppress=constStatement --verbose --xml C:\Users\user\Downloads\Community-Patch-DLL-master 2> cppcheck-Community-Patch-DLL-master.xml.txt`

118 errors
31 warnings
5 performance issues

[cppcheck-Community-Patch-DLL-master.xml.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/8031818/cppcheck-Community-Patch-DLL-master.xml.txt)

**Comment by ilteroi** [comment]
yeah, lots of false positives but also some nuggets in there

**Comment by JohnsterID** [comment]
Some issues fixed: https://github.com/LoneGazebo/Community-Patch-DLL/commit/1e8953750b1dc1e0dd76fd5d462ae381a7324ea1

Cppcheck PR: https://github.com/LoneGazebo/Community-Patch-DLL/pull/8652
