### ISSUE TITLE
Well icon not on tech tree

### ISSUE THREAD

**Issue by JLazeZ2** [LoneGazebo/Community-Patch-DLL#8627]
_1. Mod version (X.Y.Z, e.g. 1.4.2):_
1.4.2

_2. Mod list (if using Vox Populi only, leave blank):_
VP, Colored Religious Icons, Promotion Flags EUI 3.1, Quick Turns, Unit Path Viewer

_3. Error description:_ 
The well icon isn't on Mining in the tech tree.

---------------------------

1. Log file - [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8043402/Logs.zip)

**Comment by nobubblegums** [comment]
I can't reproduce this, does anyone else have this issue?

**Comment by JLazeZ2** [comment]
Well this is embarrassing, this is a user problem. 

I was playing as the Aztecs and didn't know their UB replaced both the water mill AND well; I looked at it in the civilopedia and it only showed the mill so it didn't come to mind.

**Comment by RecursiveVision** [comment]
Ah. Problem solved, then.
