### ISSUE TITLE
Forge and Copper

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#863]
The Forge grants **+2** Production to Copper.

cf.
Community Balance Patch\Balance Changes\Buildings\BuildingChanges.xml
Line: 328

![forge](https://cloud.githubusercontent.com/assets/11933188/11528234/ce72dc3e-9928-11e5-9288-20827efdf8f4.png)

**Comment by LoneGazebo** [comment]
Fixed, thanks!
