### ISSUE TITLE
Primary religion logic changed in Community Patch

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#8631]
_1. Mod version (X.Y.Z, e.g. 1.4.2):_
1.4.1

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch only

_3. Error description:_ 
In the Community Patch, when a player has not found a religion, but the majority of their cities is converted to the religion of another player, that religion becomes the player's primary religion, and stored faith is converted to golden age points. This seems to be a part of the Community Balance Overhaul that was mistakenly included also in the Community Patch (it was mentioned before that the Community Patch isn't supposed to include any gameplay/balance changes).

![Screenshot (27)](https://user-images.githubusercontent.com/95587882/153725236-c6f4f769-708e-4ebd-acce-a3612ad18f2f.png)

Related to this, pantheons are also listed multiple times in the Religion overview.
![Screenshot (31)](https://user-images.githubusercontent.com/95587882/153725404-4793e2a7-4ead-4081-ab3e-cfedcbc23624.png)
(here, Ethiopia has founded Eastern Orthodoxy, which is the majority religion also for the Mayas and for the three city states).

**Comment by LessRekkless** [comment]
> In the Community Patch, when a player has not found a religion, but the majority of their cities is converted to the religion of another player, that religion becomes the player's primary religion, and stored faith is converted to golden age points.

Did it actually happen, or is it just the tooltip that says it did?

**Comment by Mileslewis** [comment]
This also happens with Balance Patch on.
It is a bug, Religions are only supposed to be primary if you own the holy city.

**Comment by axatin** [comment]
And the conversion of faith into golden age points actually takes place when using Community Patch, it's not just written there.
