### ISSUE TITLE
AI extremely passive in attacking a defenseless city

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#8634]
_1. Mod version (X.Y.Z, e.g. 1.4.2):_

1.2.1

_2. Mod list (if using Vox Populi only, leave blank):_

Promotion Flags EUI for VP (v 3)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 1.2)

_3. Error description:_ 

Portugal declared war on Netherlands around t290.
I did on t298.
The Hague is completely isolated. Portugal sent the bulk of his attacking force there.
She easily cleared any Dutch units around the city and surrounded it.
For around twenty turns she simply sat around the city with melee units.
The most artillery I ever saw near the Hague at the same time was two, maybe very briefly three. They did some work, but after Willy killed them (with city attack and bombers I guess) Portugal would send a new one maybe every five turns at most.
The melee units maybe attacked the city a few times, but mostly they just sat there.
Portugal has a massive army nearby. I obviously gave her open borders.
Note that currently Willy has six planes in the Hague, some of them stealth bombers, but that's a very recent development.
For most of the war he only had two planes in there, and they definitely weren't stealth bombers.
Basically, absolutely nothing was preventing Portugal from taking this city in a matter of a few turns, but she's just sitting there.
Over the last few turns the city actually healed 150 hp!
Portugal isn't involved in any other wars, and is friends with all her neighbors.

I don't have any autosaves, but have a save from t298 and t322.

---------------------------

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8054459/saves.zip)

4. Screenshots (optional):

![image](https://user-images.githubusercontent.com/4227288/153727063-1e3a855a-e473-481f-9855-8ce9626f361d.png)

**Comment by ilteroi** [comment]
weird, but that version is quite old ... won't fix
