### ISSUE TITLE
Trade route overview shows potential routes that aren't actually possible

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#8635]
_1. Mod version (X.Y.Z, e.g. 1.4.2):_

1.4.2
Started with 1.4.1.

_2. Mod list (if using Vox Populi only, leave blank):_

InfoAddict (v 22)
Promotion Flags EUI for VP (v 3.1)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 1.2)

_3. Error description:_ 

Trade route overview says I can send a trade route from Jakarta to Corihuayrachina.
But the caravan in Jakarta disagrees.
This is far from an isolated occurence. I've been seeing impossible trade routes in that screen for years.

---------------------------

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[BUG.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8054478/BUG.zip)

4. Screenshots (optional):

![image](https://user-images.githubusercontent.com/4227288/153727484-e5b926a6-c3e5-4f81-9de3-b42990310ca4.png)
![image](https://user-images.githubusercontent.com/4227288/153727487-573a36bf-12d5-4495-ac11-307b5c1d4d64.png)

**Comment by nobubblegums** [comment]
Hm not a real solution but have you ever tried "Filters in Trade Overview for VP" modmod? If that doesn't have this issue it would be really easy to compare the LUAs and integrate whatever needed to base VP.

**Comment by gamask** [comment]
I used to play with that mod always on, and always assumed the issue was with it and not with base VP.
It's only recently that I got tired of seeing wrong info and tried playing without it.
That mod by the way also shows wrong durations.

**Comment by nobubblegums** [comment]
So it goes deeper! Thanks for explaining

**Comment by bentakacs** [comment]
It's probably a dumb question, but you don't have **already** a TR between Jakarta and Corihuayrachina, right?

**Comment by gamask** [comment]
No, but I do have one from Surabaya.
So I guess the issue is that it doesn't filter out destination cities that are already used by other routes.
I guess it's debatable whether that's a problem or not.

However, I'm 100% certain that I've seen the actual problem I described originally.
What I'm not certain about is if I've seen it with base VP, or only with the "Filters in Trade Overview for VP" mod.
I'll keep an eye on it.

**Comment by bentakacs** [comment]
Well, then that explains it. You can make only 1 TR to a foreign city. 

I personally do not find this to be a problem, just a little bit more planning and checking is needed, but opinions may vary.
