### ISSUE TITLE
schizophrenic diplomacy

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8637]
so i just converted theodora's capital/holy city to my religion.

the very same turn she offers me a declaration of friendship ... that doesn't seem right.

edit: about 10 missionaries later their religion is finally eradicated and now they ask me to stop the conversions.

**Comment by RecursiveVision** [comment]
Not impossible that the first scenario would happen, if they value your friendship over the conversions.

The second issue is a bug though, they're supposed to get angry the first time a conversion happens.

**Comment by RecursiveVision** [comment]
Fixed this

**Comment by LessRekkless** [comment]
Weird. I'm surprised that Theodora's favourite religion wasn't her own religion.

I think the _correct_ fix is that GetFaboriteForeignReligion() should exit early and return the player's founded religion. Then a player can get angry if someone is converting them away from a religion that benefits them more.

**Comment by RecursiveVision** [comment]
@LessRekkless As the bug report above indicates, scoring of a player's favorite foreign religion fluctuates. The AI diplomacy is not currently equipped to handle this - and previously up until this cleanup happened it was only founders who got angry. 

Changing this as you suggest would remove safe targets for spreading religion based on opaque mechanics and make the AI more aggressive in general, which I don't believe is in its interests nor fun for the average human.
