### ISSUE TITLE
morocco flavors

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#864]
![image](https://cloud.githubusercontent.com/assets/1358966/11536457/dd0b129e-9918-11e5-843e-be0849d22297.png)

this is the flavor setting for morocco's next city. food (index 0) is sky-high, production (index 1) totally irrelevant. it seems the lion's share comes from a CvCitySpecializationXMLEntry, which contributes 40 of the 50.

compare to gandi:

![image](https://cloud.githubusercontent.com/assets/1358966/11536659/b9776642-9919-11e5-9c9c-a053eee95699.png)

which appears much saner.

it this by design?

it is important that these flavor weights always add up to roughly the same number, otherwise strange decisions may result (in this case settling a city in the arctic with 3 workable plots because of one little fish).

**Comment by ilteroi** [comment]
come to think of it, i'll put in a normalization step. still, outliers like this one should be removed from the database

**Comment by LoneGazebo** [comment]
That's weird. Perhaps look at the CitySpecialization_TargetYields table?

**Comment by LoneGazebo** [comment]
What's the status on this?

**Comment by ilteroi** [comment]
don't know where to find this magic table. in any case, normalization is implemented so it should be better now

**Comment by LoneGazebo** [comment]
Cool. The table is in the AICitySpecializations.xml file in the AI folder of your base civ install. I also edit it some in the CP.

G
