### ISSUE TITLE
Free Company unit does not have strategic view icon

### ISSUE THREAD

**Issue by Hokiefan00** [LoneGazebo/Community-Patch-DLL#8644]
_1. Mod version (X.Y.Z, e.g. 1.4.2):_
1.4.2 (but I've seen it since the free company was intruded)

_2. Mod list (if using Vox Populi only, leave blank):_
RAS v15
EAW 4VP v1.9
ENW v2.1
More Unique Comp 4VP v74
Lategame War Rebalance 3
Logistics Skirmishers v3
New Beliefs Mods
Promotions Flags EUI for VP v3.1
Israel for VP
Cambodia for VP v15
Canada for VP v24
Tlingit for VP v18
Greece & Macedonia Split for VP v14
Sumer (CBP) v23

_3. Error description:_ 
The Free Company unit does not have an icon in strategic view. It's been like this since it was introduced. I list all the modmods I am playing with above but I've witnessed it with all but RAS removed.

---------------------------
Supporting information:

Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/84920557/153791346-0c7320de-406c-4891-898b-8a480869fddf.png)

**Comment by nobubblegums** [comment]
`It's been like this since it was introduced. `

Hm so this predates my texture compression stuff. I'll take a look

**Comment by nobubblegums** [comment]
Ok got it, it's again a dx11 compression issue. Will be fixed in the new version, thanks for reporting
