### ISSUE TITLE
AI wants peace but can't/won't accept any deal including white peace

### ISSUE THREAD

**Issue by killwrathy** [LoneGazebo/Community-Patch-DLL#8648]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.3, DX 10 & 11):_
1.4.3

_2. Mod list (if using Vox Populi only, leave blank):_
More Unique Components for VP (v. 73)
Even More Resources for Vox Populi (v. 8)
Historical Religions Complete (BNW or GK) (v 45)
JFCDLC (07) - JFD's Cultural Diversity (Core) (v 17)
JFCDLC (07a) - JFD's Cultural Diversity (Soundtrack)
Randomize City Names (v 2)

_3. Error description:_ 
AI Siam has lost all it's cities but it's last one, which is under siege and down to no HP. They are down to -100 warscore and have no other units except the garrison. They want peace, but will not accept even a white peace, just responding with 'You cannot be serious' etc.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[Gandhi_0175 BC-1750.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8072370/Gandhi_0175.BC-1750.zip)

**Comment by RecursiveVision** [comment]
@killwrathy Please upload your MODS folder.

**Comment by killwrathy** [comment]
(Less 4 GB of irrelevant soundtrack mp3s, 270MB file so still too big to upload to github)

https://drive.google.com/file/d/1pUKr7M5c63yCZmPNbtjW__MdG8cASaI_/view?usp=sharing

**Comment by RecursiveVision** [comment]
I believe this is solved
