### ISSUE TITLE
Title for "Sanctimony" promotion is "Righteousness" instead of "Sanctimony" in Help.

### ISSUE THREAD

**Issue by calloatti** [LoneGazebo/Community-Patch-DLL#8649]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.3, DX 10 & 11):_

1.4.2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Title for "Sanctimony" promotion is "Righteousness" instead of "Sanctimony" in Help.

_4. Steps to reproduce (optional):_

4. Screenshots (optional):

![image](https://user-images.githubusercontent.com/12817862/154107585-51fd5c3b-da9e-4be3-9705-05fb2efb2028.png)

**Comment by RecursiveVision** [comment]
"Sanctimony" does not exist in the Civ V or VP text files.
