### ISSUE TITLE
cannot buy the granary

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#865]
![image](https://cloud.githubusercontent.com/assets/1358966/11545689/f9b8afa2-9948-11e5-84f0-45875a965355.png)

i have more than the usual 120 gold, but it says cost 3 and not possible to buy

**Comment by ilteroi** [comment]
ok turns out it costs 130 - so it seems to be display problem only

**Comment by LoneGazebo** [comment]
The math stuff in EUI is wonky and dumb.

**Comment by Edaka** [comment]
The newest EUI doesn't show how much money you need - it now shows how much you lack instead.

**Comment by ilteroi** [comment]
ooooookaaaay. i guess. but why does it still show a number after investing then?

nevermind, closing this
