### ISSUE TITLE
AI accepts my peace offer, but the war is still going on

### ISSUE THREAD

**Issue by brsoft1981** [LoneGazebo/Community-Patch-DLL#8651]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.3, DX 10 & 11): 1.4.3

_2. Mod list (if using Vox Populi only, leave blank): Vox Populi + Promotion Flags EUI for VP (v 3.1)

_3. Error description: AI (Austria) accepts my (The Huns) peace offer, but the war is still going on

_4. Steps to reproduce (optional): I make peace offer, AI accepts it, but the war is still going on

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0000](https://user-images.githubusercontent.com/96129291/154143096-80b46c41-8fe7-48fd-bdc1-a2f3cc355a3f.jpg)
[Ivo.Civ5Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8074434/Ivo.Civ5Save.zip)

**Comment by RecursiveVision** [comment]
Can't load the save.

**Comment by RecursiveVision** [comment]
Think I solved the issue though
