### ISSUE TITLE
Duplicate wording

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#8659]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.4, DX 10 & 11):_  1.4.4

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_  Two sentences describing the same event but slightly different wording. Seems like redundancy.
![20220217164409_1](https://user-images.githubusercontent.com/16341598/154506197-1170d75c-db9b-478f-9bff-c9e2633b0c5b.jpg)

**Comment by RecursiveVision** [comment]
That's notifications for you.
