### ISSUE TITLE
City state built a settler

### ISSUE THREAD

**Issue by MaartenPxl** [LoneGazebo/Community-Patch-DLL#8660]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.4, DX 10 & 11):_
1.4.2

_2. Mod list (if using Vox Populi only, leave blank):_
Alternative Difficulty for VP (v. 11)
![](https://i.imgur.com/UWoCbuC.png)

_3. Error description:_ 
City state built a settler
![](https://i.imgur.com/DhaEtVW.jpeg)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
[Turn on settler build AutoSave_0028 BC-2880.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8091095/Turn.on.settler.build.AutoSave_0028.BC-2880.zip)
[city state settler all autosaves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8091097/city.state.settler.all.autosaves.zip)

**Comment by RecursiveVision** [comment]
@MaartenPxl Savegame from 1 turn before the City-State built the Settler is needed.

**Comment by MaartenPxl** [comment]
I included it in the issue:
https://github.com/LoneGazebo/Community-Patch-DLL/files/8091097/city.state.settler.all.autosaves.zip

**Comment by RecursiveVision** [comment]
Ah, my mistake
