### ISSUE TITLE
Dead Custom Mod Options

### ISSUE THREAD

**Issue by IanE9** [LoneGazebo/Community-Patch-DLL#8661]
There are several unused Custom Mod Options present in the database that either go unreferenced and are thus non-functional or are now always active regardless of database settings making them constants. They should probably be removed from the database.
# Unreferenced
* ``GLOBAL_VENICE_KEEPS_RESOURCES``
* ``GLOBAL_ADJACENT_BLOCKADES``
* ``GLOBAL_ALLIES_BLOCK_BLOCKADES``
* ``GLOBAL_SHORT_EMBARKED_BLOCKADES``
* ``GLOBAL_PARATROOPS_MOVEMENT``
* ``UNITS_LOCAL_WORKERS_LANDLIMIT``
* ``UNITS_LOCAL_WORKERS_WATERLIMIT``
* ~~``UNITS_LOCAL_WORKERS_COMBATLIMIT``~~ Referenced but not cached
* ``UNITS_HOVERING_COASTAL_ATTACKS_RANGE``
* ``UNITS_HOVERING_COASTAL_ATTACKS_MULTIPLIER``
* ``UNITS_HOVERING_COASTAL_ATTACKS_DIVISOR``
# Constants
* ``API_UNIFIED_YIELDS``
* ``API_UNIFIED_YIELDS_TOURISM``
* ``API_UNIFIED_YIELDS_GOLDEN_AGE``

**Comment by RecursiveVision** [comment]
I've already swept away many of these options, but some linger; thanks for this list.

**Comment by RecursiveVision** [comment]
I removed the zombie options. MOD_API stuff is a headache so I'll do it a bit later.

**Comment by RecursiveVision** [comment]
Ok it's all gone

GOTTA, SWEEP SWEEP SWEEP!
