### ISSUE TITLE
Tagging each release in git repository.

### ISSUE THREAD

**Issue by bukowa** [LoneGazebo/Community-Patch-DLL#8665]
Hello! I wonder if we could tag each release on git repository? It's very easy to do https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/managing-tags

And then we could view all the tags in https://github.com/LoneGazebo/Community-Patch-DLL/tags

**Comment by RecursiveVision** [comment]
I added tags for 1.0 releases onwards
