### ISSUE TITLE
AI Proposes Peace Terms and Won't Accept Them

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#867]
Reported by Galaphile0125 and HammeredDog: 

"With my latest game Arabia DOW'd me and I was kicking their butt and they offered me terms but when the terms popped up there was nothing on either side of the list for trading and even when I tried to accept he refused the terms he had offered me.

I especially notice that the AI won't take capitulation even when they are the ones offering it and this is when I have totally crushed them and have a war score of 100. Has this happened for anyone else? It is really frustrating to be offered terms and then the AI refuses its own terms.  

Montezuma offered 1300 gold and Capitulation. War Score was 100 and he was down to his last city, a Dromon, no troops, and was completely surrounded by mine. I clicked Accept and he laughed at me and said "You can't be serious." I wasn't going to just give him a truce so I finally just took him out to get him out of my hair. He kept offering the same deal (gold varied), but never would accept. I modified the terms to remove capitulation and drastically lowered the gold, but no joy."

Not sure if this is the thing you already have in your to-do list, so I'll leave this here.

**Comment by DOUSHIO02** [comment]
Had this happen twice now, first against Denmark, then against Sweeden. Both times they declared war on me. When they asked for peace, at 100 war Score, they offered all of their money and most of their GPT, plus a city, capitulation and all spare luxuries. However they wouldn't peace out despite it being themselves who make the offer. They wouldn't even accept peace for free, nor would they accept my money and cities for it. The wars both took hundreds of turns and ended  only once they'd lost all their cities.

**Comment by LoneGazebo** [comment]
Yeah a fix is in the works. Thanks for report!

**Comment by Edaka** [comment]
A number of users on the forum are still reporting this issue. It seems that it's not as bad as before, though, as the AI reportedly becomes able to accept a treaty later/on a player's turn (while unable to do so on its own turn).

glaivemaster: 'The key thing here is that the AI is ready to surrender, and approaches the player with terms. If you hit accept, they decline, just like the old bug, and won't accept anything you suggest. However, once the player's turn rolls around, in my experience, you can ask the AI for peace and they'll accept. So it's half fixed, as long as you're willing to wait until your turn to make peace '

hantomaxl1207: 'Yeah had this happen too. They accepted another Treaty later.'

**Comment by LoneGazebo** [comment]
Sounds like the cached peace value isn't rolling around properly. Is the AI offering peace, or demanding it?

**Comment by Edaka** [comment]
I'd take a guess that the AI was proposing peace while probably losing. From my own experience, I'm very rarely content with accepting demands from the AI - I refuse until I try to at least break even. It's the peace deal proposals with reparations on the AI's side that I accept on the turn they offer them or try to pursue in case they don't go through for some reason. The latter is probably the case here judging from glaivemaster's description.

**Comment by Edaka** [comment]
glaivemaster: 'The AI was surrendering in every case. However, my theory has just been blown to pieces by the Netherlands offering surrender equal to their max war score and then accepting it, so it can't purely be whenever the AI offers surrender.'

Another thing to note: 'It was offering a peace deal in the region of 2 billion war score, which I'm not sure if it is a bug or not.'

**Comment by Edaka** [comment]
Another possible quirk with that peace deal counter reported by Zanteogo: 'I also noticed that vassalage in peace deals always shows worth "-1". However the AI seems to be able to calculate it's value regardless.'

**Comment by LoneGazebo** [comment]
Alright, I've reworked this some. We'll see if the next version 'truly' fixes it.

**Comment by Edaka** [comment]
That didn't seem to kill the bug (although it's reportedly less frequent now). 

PurpleMentat: "So far, the peace deals seem to not handle changing situation very well. Specifically, I can only seem to get an accurate total potential value at the beginning of my turn before any more action happens. If they offer on their turn, the value never works out. If I offer after further action (killing units, pillaging, etc), it doesn't work out." I'm fairly certain this was on the 12/16 version. 

To anybody still experiencing this issue in the latest beta - please provide your savegame before such an instance (when the AI doesn't want to accept a peace deal it proposed).
