### ISSUE TITLE
VP 1.4.6 Lua.log runtime error - not sure if it an issue or not

### ISSUE THREAD

**Issue by jayeye2011** [LoneGazebo/Community-Patch-DLL#8673]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
VP 1.4.6 with EUI, dx11, pangea map script

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Observed following runtime error being reported in lua.log although did not appear to cause any map generation issues. So just reporting it in case it might be a problem. I think it happens with any map script.
	Line 519: [92690.078] Runtime Error: C:\Users\john_i\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Community Balance Overhaul\Art/Improvements/Inca/CBP_IncaFunctions.lua:26: attempt to call field 'COMMUNITY' (a nil value)
	Line 520: [92690.078] Runtime Error: Error loading C:\Users\john_i\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Community Balance Overhaul\Art/Improvements/Inca/CBP_IncaFunctions.lua.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8104325/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Napoleon_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8104327/Napoleon_0000.BC-4000.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by nobubblegums** [comment]
Nice catch, probably due to recent sweeping @RecursiveVision

**Comment by RecursiveVision** [comment]
Hmm, probably caused by my changing the variant data type to an integer. Not sure if any modmods use this, so we'll see if another issue pops up.

**Comment by RecursiveVision** [comment]
Caused by the removal of the COMMUNITY_CORE_BALANCE_CIVS option...good catch!
