### ISSUE TITLE
Missing global defines

### ISSUE THREAD

**Issue by IanE9** [LoneGazebo/Community-Patch-DLL#8683]
There are several global defines that we cache but that we do not specify in the database. The DLL continues to function despite these missing thanks to default values being provided at construction but I'm fairly certain that Lua scripts will be unable to reach them unless they're properly defined. Those that are default defined as ``-1`` are more concerning because they may be necessary for proper function of features.

* ``QUEST_DISABLED_GIFT_SPECIFIC_UNIT=0``
* ``WARMONGER_THREAT_CITY_VALUE_MULTIPLIER=100``
* ``EXPANSION_BICKER_RANGE_HIGH=7``
* ``EXPANSION_BICKER_RANGE_MEDIUM=6``
* ``EXPANSION_BICKER_RANGE_LOW=5``
* ``MAXIMUM_WORK_PLOT_DISTANCE=3``
* ``MINIMUM_TOURISM_BLAST_STRENGTH=100``
* ``PROMOTION_DEFENSIVE_DEEPWATER_EMBARKATION=-1``
* ``PROMOTION_FLAGSHIP=-1``
* ``POLICY_BRANCH_HERITAGE=-1``

**Comment by RecursiveVision** [comment]
Fixed, thank you!

PROMOTION_FLAGSHIP and POLICY_BRANCH_HERITAGE are false positives, as these are modmod-only features.
