### ISSUE TITLE
Optimizing great works is not able to achieve optimal ordering (5 theming bonuses with artifacts mixed in)

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8687]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_
Alternative diffictulty

_3. Error description:_ 
I manually sorted the great works so I have all theming bonuses.
Upon pressing optimize it switches them around and loses 1 theming bonus.
There are 2 variations it switches between when pressing optimize, both have 1 missing theming bonus, either parthenon (2 same owner) and museum (same owner (+same era), artifacts allowed).

I believe the algorithm has problems with artifacts, since the optimal combination has artifacts in the museum.

Manually optimized:
![](https://i.imgur.com/uJ6DNRw.png)

After optimize:
Permutation 1: museum wrong
![](https://i.imgur.com/k0Zz0M1.png)

Permutation 2: Parthenon wrong
![](https://i.imgur.com/o8wKqtd.png)

Save file of the turn:
[Pachacuti_0223 AD-1565.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8137985/Pachacuti_0223.AD-1565.zip)

**Comment by LoneGazebo** [comment]
ah i see, so your capital is damage, the algorithm tries to avoid dangerous cities.

**Comment by RecursiveVision** [comment]
@LoneGazebo May want to exclude the capital?

**Comment by maarten99** [comment]
@LoneGazebo 
> ah i see, so your capital is damage, the algorithm tries to avoid dangerous cities.

Sorry for the late reply, this was in OCC, so a damaged capital shouldn't matter.
