### ISSUE TITLE
POLAND NOT GETTING ITS FREE POLICY

### ISSUE THREAD

**Issue by youngsteve11** [LoneGazebo/Community-Patch-DLL#8688]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6 DX10 & 11

_2. Mod list (if using Vox Populi only, leave blank):_
Citadels don't steal land.
Infoaddict

_3. Error description:_ 
Enter Medieval Age and no free policy, though did have one in classical age. Was using policy saving to save them once reaching med age. 

_4. Steps to reproduce (optional):_

Tried previous turn & used policies but still same when entering medieval age. Tried to complete whole classical tree but still nothing.
---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
Cannot give you save of previous turn as tried to complete whole era. 
[Casimir III_0454 AD-0770.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8140162/Casimir.III_0454.AD-0770.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by maarten99** [comment]
Poland receives a free policy in classical and every _other_ era.
So you receive one in classical, renaissance, ...

**Comment by youngsteve11** [comment]
Thank you for the reply. Bit confusing, as when I read in every other era afterwards I premuse it meant for each era. Makes it from a good civ to a quite average one as UU & UB don't stand out either.

**Comment by maarten99** [comment]
True, in vanilla/BNW Poland is the best/ 2nd best civ, and in VP he's only above average. Very versatile, and his UU is very good, one of the best.
