### ISSUE TITLE
Siam builds too many of his unique knight, still has them unupgraded in Atomic era

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8689]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_
Alternative difficulty

_3. Error description:_ 
AI build a lot of their unique unit, but in this case the unique unit is a knight that doesn't require Horses. The AI build way more of his unique unit than he has horses, so he has no way of upgrading them, leaving a significant portion of his supply cap taken up by Medieval units in Atomic era.

![](https://i.imgur.com/2dg8RBv.jpeg)

**Comment by nobubblegums** [comment]
IIRC they should disband non-upgradeble units after two tiers, so in Combustion (landship) in this case. While they're in Atomic, they still have lancers&gatlings, is it possible they rushed the top techs? Could you keep an eye on them to see whether they have UUs when they get landships?

**Comment by maarten99** [comment]
2 turns later I saw a landship of his next to those same unique Knights

**Comment by nobubblegums** [comment]
Hm, shame on them. I'll take another look at that obsolescence code

**Comment by maarten99** [comment]
By the end of the game they were all replaced. But perhaps they should have replaced them sooner. 
![image](https://user-images.githubusercontent.com/24713571/156428767-0fa3b0ee-d562-44c3-8854-f5b761d52af4.png)
