### ISSUE TITLE
AI undervalues uranium, because he has spare (but has yet to use any, just built Manhattan project)

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8690]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_
Alternative Diffictulty

_3. Error description:_ 
11 gpt for all his Uranium
![](https://i.imgur.com/Bla0LOw.jpeg)

**Comment by nobubblegums** [comment]
It seems they do that for all strategics, like  l keep getting offers of 1 gpt for 1horse/iron
