### ISSUE TITLE
Feature request: Make barbarians from city state horde event unable to spawn & enter major civ's territory

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8691]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_
3/4 UC

_3. Error description:_ 

Barbarians from the horde event are able to spawn in major civ's territory and often wander away from the city state, harrasing cities around them rather than attack the city state.

I would propose a "promotion" added to these event barbarians that make them unable to enter a major civ's territory for X turns after spawning.

example of barbs spawning:
![image](https://user-images.githubusercontent.com/24713571/155799633-9a83cd4c-04ac-4eb4-9e6f-25e2f56344d9.png)

**Comment by RecursiveVision** [comment]
Think this is out of scope.
