### ISSUE TITLE
A couple of tooltips

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#870]
1) Posted by Bromar1:

"The tooltip for temple says that it comes with a great work of art slot but I'm not able to find one."

2) Posted by pandasnail:

"The Iroquois Longhouse still gives me an engineer specialist, as if it were a forge or workshop replacement still. If it is intentional, then the civpedia and mouseover tooltip description should be updated."

I'll call this safety reporting, as in 'You've definitely seen this on the forum yourself and have probably fixed it, but I'll report just in case you've forgotten".

**Comment by LoneGazebo** [comment]
Longhouse should not have a specialist...I'll fix.

**Comment by Edaka** [comment]
Aww, I thought that was intentional. Well, I suppose it's already strong as it is without the specialist.
