### ISSUE TITLE
Allow Venice to switch puppet state's production to World Congress projects like Treasure Fleet

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8700]
Example: one city happened to be done with it's building the turn the project came available, but I'm unable to select it in other puppet cities.
![image](https://user-images.githubusercontent.com/24713571/155903768-0ca6200d-bfb0-411e-a1f6-44c7ed5e19dd.png)
![image](https://user-images.githubusercontent.com/24713571/155903775-2b690432-476e-447d-8b4a-2faa9607a659.png)

**Comment by RecursiveVision** [comment]
No. That's a drawback of playing Venice.
