### ISSUE TITLE
Can't Build DLL

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#8706]
When I try to build I get 2 errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: '../commit_id.inc': No such file or directory	VoxPopuli	C:\Users\miles\OneDrive\Documents\GitHub\Milae Patch branch\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvGame.cpp	69

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: '../commit_id.inc': No such file or directory	VoxPopuli	C:\Users\miles\OneDrive\Documents\GitHub\Milae Patch branch\Community-Patch-DLL\CvGameCoreDLL_Expansion2\CvDllContext.cpp	51	

I do have Git installed but I'm guessing it's not correct or something. Could someone please explain how it needs to be done?

**Comment by ilteroi** [comment]
there is a batch file in the root folder which creates this .inc file ... try and run it manually. but if you use the official project file it will be executed before every build.

**Comment by Mileslewis** [comment]
Okay, how do I do that?

**Comment by Mileslewis** [comment]
Running it manually doesn't seem to help

**Comment by ilteroi** [comment]
do you have a file called commit_id.inc in the root folder of the repo or not?

**Comment by Mileslewis** [comment]
No I have update_commit_id.bat which is the one I tried to run. Looked like it did run but nothing actually changed.

**Comment by ilteroi** [comment]
did you get an error message? is git in your path?

**Comment by Mileslewis** [comment]
error message when I ran the .bat? Not that I saw.

And I installed Git as someone showed on Discord but I don't know what it means to have it in my path.

**Comment by ilteroi** [comment]
then i would suggest you read up on the basics first

**Comment by Mileslewis** [comment]
Well Git is now in my system variables path and it still doesn't work. I'm not against looking things up but I don't even know what I need to look up man, this is completely new for me and I'm not the only one having issues with it.

**Comment by Mileslewis** [comment]
@ilteroi how important is it that the commit_id.inc file is updated every time? Will it work if you just send me a recent version of it?

**Comment by Mwallx** [comment]
I ran into the same issue here and coped with it with the help of gpt. The cause is that you don't have write permission to generate the file in the repo folder. You simply need to change the output folder to another one(D root worked for me), and copy the generated file back.
You can also make the file yourself, it's a one line file with this:

const char CURRENT_GAMECORE_VERSION[] = "Release-4.16 9cc2e3dec Clean"; //autogenerated, do not commit this file!

**Comment by azum4roll** [comment]
In general, don't do any development/file manipulation in the OneDrive folder. That's for storage...
