### ISSUE TITLE
Invisible items in the trade window

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#871]
Posted by chr and confirmed by a handful of users:

"One thing I noticed, is that sometimes when dealing with the AI the things offered don't appear in the list. For example the AI calls me asking for mutual open borders (I know this because of what they say), but the list is empty, or rather the items there are invisible.
Another probably very related thing is that sometimes during trades the items I click on don't appear in the list."

Apparently, even Funak "gets those every once in a while and has been getting them since forever". I only remember getting that bug a long, long time ago, though. Something to keep an eye on.

**Comment by LoneGazebo** [comment]
I can almost guarantee this is related to cache issues with changing mod versions, but I'll keep an eye on it.

**Comment by LoneGazebo** [comment]
I can't reproduce this.
