### ISSUE TITLE
City-States should gift CS-only units more

### ISSUE THREAD

**Issue by nobubblegums** [LoneGazebo/Community-Patch-DLL#8712]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

I was doing some tests on city-state gifting, and out of hundreds of units gifted, only one was CS-only. I think the game doesn't prioritize assigning CS-only units (e.g. battering ram, turtle ship) and picks CS uniques from a common pool including both major civ UUs and CS-only units, which naturally leads to this. Also worthy of note, I've seen Foreign Legion gifted, is this intended? I thought policy-locked units were out of bounds for CS'.

**Comment by LessRekkless** [comment]
Minor Civ UUs have a random weight of [50,350) compared to the normal UUs' weight of [0,300). I don't really know how to to calcult how much more likely it is to be chosen for the top 5 candidates, though.

There doesn't se to be anything differentiating Foreign Legion from Free Company/Mercenaries, but it shouldn't be chosen as the Unique Unit Gift, only as a normal unit at most.

**Comment by LessRekkless** [comment]
Hmmmmm
![image](https://user-images.githubusercontent.com/34615525/156201907-53aabaf5-b9d1-4e3d-86ac-c21ac93351b7.png)

**Comment by LessRekkless** [comment]
Minor Civ Units aren't getting added to the game at all:
`CvGame::GetRandomUniqueUnitType line 9526`
```
// Is it a unique unit from a civ that is in our game?
if (!bIncludeCivsInGame)
{
	for(int iMajorLoop = 0; iMajorLoop < MAX_PLAYERS; iMajorLoop++)  // MAX_PLAYERS so that we look at Barbarian UUs (ie. Brute) as well
	{
		PlayerTypes eMajorLoop = (PlayerTypes) iMajorLoop;
		if(GET_PLAYER(eMajorLoop).isAlive())
		{
			UnitTypes eUniqueUnitInGame = (UnitTypes) GET_PLAYER(eMajorLoop).getCivilizationInfo().getCivilizationUnits(eLoopUnitClass);
			if(eLoopUnit == eUniqueUnitInGame)
			{
				bValid = false;
				break;
			}
		}
	}
}
```
This code section checks each Major Civ in the game, and finds the Civ's unit for the Candidate Minor Civ Unique Unit's UnitClass in question.  Currently all of our Minor Civ Units are set to be the default in their own UnitClass. eg:
```
INSERT INTO UnitClasses (Type, Description, DefaultUnit) VALUES ('UNITCLASS_HUNNIC_BATTERING_RAM', 'TXT_KEY_UNIT_HUN_BATTERING_RAM', 'UNIT_HUN_BATTERING_RAM');
```
So, EVERY Civ's default unit for these Minor Civ UnitClasses will be the Minor Civ's Candidate Unit.

**Comment by LessRekkless** [comment]
azum4roll is getting his turtle ship because he reassigned it to UNITCLASS_CARAVEL.

**Comment by nobubblegums** [comment]
Great work Rek! If it helps things, the one I got today was Norwegian Ski Infantry. If I understand correctly, the suggestion would still make Minors' have only one UU in-game.  Can we make it so that all Minors can gift MinorGift units (turtle, ram, pracinha etc.) and also each Minor gets one random UU as they do now. I think as long as MinorGift units share a pool with UUs, they will be underrepresented to the point of being irrelevant.

**Comment by LessRekkless** [comment]
Getting Norwegian Ski Infantry .... kind of breaks my hypothesis.

I'm okay with Minor Civ Gifts sharing a pool with the rest.  We can boost the probability if you can figure out how the probability is actually affected, but I don't really want these unique units to be coming out super frequently.

**Comment by LessRekkless** [comment]
So, after fixing the code to actually allow minor civ gifts back into the candidate pool, a couple of tests with 16 military minor civs (and **10** minor civ only units and **43** possible choices) gave me:
5/16
4/16
3/16
5/16
3/16
So, an average of 1/4 military city states, which is almost 1 per 2 games.  I think this is frequent enough to leave alone for now.

**Comment by nobubblegums** [comment]
Nice, I think that's a good place, closing this now
