### ISSUE TITLE
CTD at turn 289 (repeatable with six-turn rollback) 

### ISSUE THREAD

**Issue by CassiusSassius** [LoneGazebo/Community-Patch-DLL#8715]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
CBP v1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_
MODS
Vox Populi (1.4.6)(with EUI)
Historical Religions (BNW or GK)(v. 55)
Infoaddict (v.22)
JFD's Cultural Diversity (Core)(v.20)
JFD's Cultural Diversity (Art) Art Styles (v.1)
JFD's Cultural Diversity (Art) Splash Screens (v.1)
JFD's Cultural Diversity (Core) Mod Support (v.1)
JFD's Cultural Diversity (Gameplay) Starting Bonuses (v.1)
JFD's Cultural Diversity (Sound) Unit Dialogue (v.1)
PerfectWorld3 (v.1)
Really Advanced Setup (v.15)
Rohwor world (v. 4)
Sukritact's Event and Decisions (v. 3)

_3. Error description:_ 
Crash to desktop on city-states/barbarian turn (immediately after City-States Turn) after proceeding to turn 290 from turn 289. To clarify, I am not certain if the crash is occurring on the city-state turn, or right as it ends, which is why is where the ambiguity comes from. I hope that much can be revealed.

After reloading an earlier save from turn 283 and playing through, I was able to repeat the crash unintentionally, with a crash on the barbarian/city-state turn at the same exact spot.

On these two saves, I was using CBP v1.4.5 . I updated to v1.4.6 hoping it would fix the issue. I attempted to advance to turn 290 on the aforementioned "reloaded save" and was met with an almost identical crash, except for now the crash occurred on the French turn, not the city-states/barbarian turn.

The older save where the crash was first encountered (OLD Oda) still occurs on the city-state turn with Vox v1.4.6

_4. Steps to reproduce (optional):_
Upon loading either save, simply proceed to the next turn (turn 290).

---------------------------
Supporting information:
[ErrorInfo.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8165024/ErrorInfo.zip)

**Comment by Padre19** [comment]
Confirm.CTD during AI turn. Sometimes during CS turn and sometimes during a civilization turn. Sometimes I go to resume the game but most of the time I don't. It's something about war or peace.
