### ISSUE TITLE
CAPITAL CITY NOT EXPANDING AFTER A TIME

### ISSUE THREAD

**Issue by youngsteve11** [LoneGazebo/Community-Patch-DLL#8716]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_

1.4.6 DX 10 & 11
_2. Mod list (if using Vox Populi only, leave blank):_

Citadels don't steal land. Infoaddict

_3. Error description:_ 
City has stopped gaining additional tiles after initial workable tiles founded, though some 4/5 ones already added.

_4. Steps to reproduce (optional):_

Wait until next tile due, then turn ends, & just starts new process again without adding new tile to city.
---------------------------
Supporting information:
Please 
[Casimir III_0630 AD-1470.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8165074/Casimir.III_0630.AD-1470.zip)
note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Casimir III_0630 AD-1470.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8165076/Casimir.III_0630.AD-1470.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LessRekkless** [comment]
Did you figure out why this is happening? Is it due to ocean tiles?
