### ISSUE TITLE
Unable to protect City States despite being a world power.

### ISSUE THREAD

**Issue by youngsteve11** [LoneGazebo/Community-Patch-DLL#8717]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_

1.4.6 DX 10 & 11
_2. Mod list (if using Vox Populi only, leave blank):_

Infoaddict; Citadels don't steal land
_3. Error description:_ 

Are unable to protect City States as seen as too weak. Have strong modern army, with latest troops & 61,741 military, compared to leader India with 66,663. Despite this cannot protect any CS as too weak, only being ranked 26% of leading military power.
_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Casimir III_0630 AD-1470.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8168214/Casimir.III_0630.AD-1470.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by youngsteve11** [comment]
I was trying to protect my neighbours, but every City State says I cannot protect them as only 26% of leading military power. India on the other hand has no trouble protecting 13 of them, which I expect might be all they have discovered. Have noticed this in other patches, & always confuses me how this is calculated. I have even gotten Terico units, which I don't think anyone else has yet. I know India seems to be stronger but I can hardly be 26% of them. If that is so how weak is everyone else.

**Comment by nobubblegums** [comment]
Yeah I'm never able to pledge either, despite being close 2nd in military.

**Comment by youngsteve11** [comment]
I would just add that the following go it seems Poland (me) is now 205% below the threshold. A massive leap in one turn. I think something is not working quite right here.

**Comment by RecursiveVision** [comment]
There's a problem with strength perception; solving it will fix a diplo AI issue as well, since it uses similar logic.

**Comment by RecursiveVision** [comment]
Just gonna use the raw military might stat for this
