### ISSUE TITLE
Trade Screen empty only when AI contacts me

### ISSUE THREAD

**Issue by chefcod22** [LoneGazebo/Community-Patch-DLL#8718]
1.4.6 
DX 11 and 9 

CBP and CP only without EUI
Infoaddict
Really advanced setup
![mods](https://user-images.githubusercontent.com/100784494/156392552-f0177550-e4f9-4042-a90a-83069a3f6246.jpg)
![dx9](https://user-images.githubusercontent.com/100784494/156392563-94812729-f552-4891-b01a-ea0a599784bb.jpg)

_3. Error description:_ 

When i contact them everyting is okay. But when they contact me on the screen is only the background of the specific leader.
My Brother has the same issue and dont uses other mods. We both made a clean installation and deleted the cache folder in my games/civ5/cache
The trade screen is a freezed image

_4. Steps to reproduce (optional):_
everytime when the ai contacts me

[leaderboards.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170543/leaderboards.log)
[Localization.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170544/Localization.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170545/Lua.log)
[modding.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170546/modding.log)
[net_message_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170547/net_message_debug.log)
[stopwatch.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170548/stopwatch.log)
[system_init.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170549/system_init.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170550/xml.log)
[xml-perf.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170551/xml-perf.log)
[achievements_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170552/achievements_debug.log)
[APP.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170553/APP.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170554/Database.log)
[init_host.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8170555/init_host.log)

everytime when the ai contacts me
I cant upload a savefile here

**Comment by RecursiveVision** [comment]
@chefcod22 You haven't enabled logging, see here for instructions: https://github.com/LoneGazebo/Community-Patch-DLL#to-enable-logging-for-bug-reports

**Comment by RecursiveVision** [comment]
Save files can be placed in a ZIP file and then uploaded.

**Comment by chefcod22** [comment]
okay i will do that

**Comment by chefcod22** [comment]
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8176477/QuickSave.zip)
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8176479/Logs.zip)

here you go :)
