### ISSUE TITLE
indian religious pressure seems to strong

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#872]
i know it's supposed to be strong, but so far they dominated every game they were in.

you usually see a pressure of 150 or even 180, when everybody else has a puny 12 or so. and inquisitors don't help against passive spread, don't know if that is intended ...

**Comment by LoneGazebo** [comment]
We can reduce it - there's a set value in the religionclasses.cpp.

**Comment by ilteroi** [comment]
re: inquistors, there is this belief:

![image](https://cloud.githubusercontent.com/assets/1358966/11600530/8f3a9a7e-9acd-11e5-948e-2a663d676a33.png)

so it seems inquisitors should eliminate religious pressure? doesn't seem like they do.

**Comment by LoneGazebo** [comment]
Presence, not pressure. That's just the # of followers.

**Comment by ilteroi** [comment]
ah. ok, so i'll be closing this one then
