### ISSUE TITLE
Temples don't provide 25% pressure, and other religious buildings might not either

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#8720]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_

1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_

InfoAddict (v 22)
Promotion Flags EUI for VP (v 3.1)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 1.2)

_3. Error description:_ 

I used IGE to add a majority religion to my city to see how much pressure it would exert.
Nearby cities received around 6-8 extra pressure.
Then I added a temple. Nothing changed.
Added a mosque. Nothing changed.
Even with rounding down, I should be getting at least 1 extra pressure from each of those, but that wasn't the case.

**Comment by LessRekkless** [comment]
Can't reproduce the issue.

No Temple:
![image](https://user-images.githubusercontent.com/34615525/156905631-3ccdc031-64b6-436b-a171-7aa65394cc30.png)
Temple:
![image](https://user-images.githubusercontent.com/34615525/156905639-ae2c81fd-a4bd-4a1b-b6b7-eb7c63f0350e.png)
Temple + Mosque:
![image](https://user-images.githubusercontent.com/34615525/156905653-f223f41b-f5dc-4565-a0cd-96f35c379d7e.png)

**Comment by gamask** [comment]
We're looking at Shinto in the screenshots below.
Medan has mosque.
61 pressure in Jakarta.
47 in Medan.
![image](https://user-images.githubusercontent.com/4227288/156908139-4ea6f9f3-ea27-4148-9420-eecd45071b60.png)
![image](https://user-images.githubusercontent.com/4227288/156908137-5ccd962a-b086-4692-a972-a8b46926100b.png)

Add temple to Medan.
No change. Still 61 and 47.
![image](https://user-images.githubusercontent.com/4227288/156908146-e7cf478a-6047-4dd2-848a-31ff98d9d636.png)
![image](https://user-images.githubusercontent.com/4227288/156908148-0e2c1135-b1f6-4178-9c50-14da49a53e5b.png)

Add church to Medan.
61 in Jakarta, 45 in Medan (???).
![image](https://user-images.githubusercontent.com/4227288/156908194-c18f0757-0c33-4cee-b57f-eb7322ef7a4b.png)
![image](https://user-images.githubusercontent.com/4227288/156908194-c18f0757-0c33-4cee-b57f-eb7322ef7a4b.png)

Remove temple and church from Medan. Then also remove one Shinto follower from Medan so it doesn't have a majority anymore.
Now 54 pressure in Jakarta.
![image](https://user-images.githubusercontent.com/4227288/156908346-6b0d7b4c-2563-4571-8877-48946eecbb49.png)


This means that base pressure from Medan is 6. Mosque (which was there all along) makes it 7.
So base pressure is high enough that 25% shouldn't get rounded down to 0.
From your example it seems like it's actually rounded properly, not down.
(5 * 1.5 = 7.5, becomes 8, not 7)

Am I missing something or is this borked?

**Comment by gamask** [comment]
[a.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8191919/a.zip)

**Comment by LessRekkless** [comment]
The issues you are having are with regards to display and integer division.

In the background calculations, base pressure from a city is 65.  This is reduced quadratically by trade-route distance between two cities compared to the maximum trade distance you can be.  

For example, based on the images, I think the distance between Medan and Jakarta is 9*1/3 (roads) = 3, but I'm not sure, a trade route may travel over the hills in a more direct path. You look like you're in the renaissance era, so max trade route distance is 20, assuming you have the **Machinery** technology.

65*(1-3/20)^2 = **46** (integer division truncates decimals)
multiply by 25% and you have **57**.

Displayed values are divided by 10 using integer division, so if Medan was the only city contributing to Jakarta, Jakarta would display 5 pressure per turn.

Playing with followers manually using IGE is ... inadvisable. That's just asking for bugs. Hot-swapping buildings in and out is also likely going to show issues, especially without reloading the game to force everything to recalculate properly.

Stepped through the code. Everything is multiplied properly.

**Comment by gamask** [comment]
Loaded my save.
Invested in a temple in Medan so it completes next turn.
Added a bunch of Shinto followers to unrelated cities to ensure that there would still be the same number of Shinto-majority cities next turn.
Made a new save and reloaded it for good measure.
Ended turn.
Next turn pressure in Jakarta was 62 (+1 compared to without temple).
Seems like you might be correct about it being IGE issues.

I'm assuming you also used IGE for your test? Did you reload after adding each building?
It doesn't really make any sense why it behaved the way it did in my test.
Especially the church, which reduced the pressure by 2.

And when you say you stepped through the code, do you mean your save or my save?

**Comment by LessRekkless** [comment]
My save; I can't load yours, unfortunately.
