### ISSUE TITLE
Conquering a city as Indonesia doesn't spawn unique luxuries

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#8721]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_

1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_

InfoAddict (v 22)
Promotion Flags EUI for VP (v 3.1)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 1.2)

_3. Error description:_ 

See title.
Civilopedia text says:
"When you gain a city, one of 3 unique luxuries will appear nearby."
So either the text is wrong, or the ability is bugged.
If it's the latter, I can provide a save. I have 50 autosaves, but I don't recall on which turn I captured a city, so I'm not going to look for the exact save unless it's necessary.

**Comment by RecursiveVision** [comment]
Ability is bugged.

**Comment by gamask** [comment]
Capture Osaka with the fusilier west of it. Annex.
[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8193334/QuickSave.zip)

**Comment by RecursiveVision** [comment]
Typo in the code, < instead of >.

Seems this has been broken for a while.
