### ISSUE TITLE
AI very careless with great generals

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#8723]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_

1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_

InfoAddict (v 22)
Promotion Flags EUI for VP (v 3.1)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 1.2)

_3. Error description:_ 

America has a single tercio and a great general far from home, attacking japanese troops.
![20220305175350_1](https://user-images.githubusercontent.com/4227288/156902374-721c42e9-9a5c-4b4e-89c2-80fff94e67b0.jpg)

_4. Steps to reproduce (optional):_

Load save, end turn.
Watch America's units nearby Surabaya.
I don't know what he's doing there to begin with, but the correct course of action is undoubtedly to go home.
There's absolutely nothing that tercio can achieve.
[BUG america general.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8191626/BUG.america.general.zip)

**Comment by ilteroi** [comment]
should be better now, probably same root cause as the mishandling of great admirals
