### ISSUE TITLE
Caravan walks over unroaded jungle instead of over roaded flatland.

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#8725]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_

1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_

InfoAddict (v 22)
Promotion Flags EUI for VP (v 3.1)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 1.2)

_3. Error description:_ 

Caravan from Jakarta goes 1W, 1W, 1SW.
Why not go along the road? 1SW, 1W, 1W.
The villlage 1SW of Jakarta is not getting the caravan bonus as a result.

Road has been in place for a long time. There haven't been any enemy units obstructing this part of the path for many turns, and maybe even not ever.

![image](https://user-images.githubusercontent.com/4227288/156902813-7fad1e84-7d68-4b68-bbb7-7bf519f90294.png)

**Comment by ilteroi** [comment]
was the trade route created before or after the road?

**Comment by gamask** [comment]
After. I have a save from turn 120 where this road already exists.
I don't believe it was ever pillaged.
