### ISSUE TITLE
Lost 6 horses after trade deal ended instead of 3

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8726]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_
Alternative Difficulty

_3. Error description:_ 
I had 12 Horses in total:  3 + 3 from trade deals and 3 + 3 from pastures.
I have 9 horse units, which means I had 3 horses left over.
After a trade deal ended, I should have lost 3 horses, but I lost 6 instead and am now at a deficit of -3 Horses, even though I still have 3 + 3 from pastures and 3 from an active trade deal.

Save before and after trade deal expired:
[Autosave before and after trade deal horse bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8191688/Autosave.before.and.after.trade.deal.horse.bug.zip)

No horses notification
![image](https://user-images.githubusercontent.com/24713571/156903474-ae6cbb89-53da-4d18-b916-a36b4beefb4e.png)

Trade deal ended
![image](https://user-images.githubusercontent.com/24713571/156903471-99494b25-89d1-46a7-ad7c-f46473634c4a.png)

-3 horses instead of 0 
![image](https://user-images.githubusercontent.com/24713571/156903476-336d7ff0-dfb3-44c1-9d04-88f9a9096fb7.png)

Active trade deal with indonesia for 3 horses
![image](https://user-images.githubusercontent.com/24713571/156903490-98ef6ed4-7461-4aa8-a892-5a74335aed9f.png)

2 Improved pastures for 6 horses (3 + 3)
![image](https://user-images.githubusercontent.com/24713571/156903498-9ed7059b-476b-40e1-8ab5-726f2471b018.png)

**Comment by LoneGazebo** [comment]
Hard to reproduce.
