### ISSUE TITLE
City States do not spawn

### ISSUE THREAD

**Issue by Advi1** [LoneGazebo/Community-Patch-DLL#8727]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
v102

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch
Community Balance Overhaul
CSD for VP
Civ IV Diplo Features
More luxeries
43 Civs Community Patch
Promotions Icrons for VP
UI for Promotion

_3. Error description:_ 
City-States do not spawn in world generation, no matter what map type.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Maria I_0218 AD-1540.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8191888/Maria.I_0218.AD-1540.zip)
[AutoSave_0400 AD-1980.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8191895/AutoSave_0400.AD-1980.zip)

4. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

5. Screenshots (optional):

**Comment by adaneslavo** [comment]
Did you test that with VP 2.0.3? It seems like some installation error. With latest release there should be no problem at all. Tested with dozens of mods even modifying or adding new City-States.
