### ISSUE TITLE
Faith Purchases for Volley Guns

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#873]
There are some intersting Costs associated with Faith purchases (using EUI)

Note how Winged Hussars are much cheaper than Volley Guns despite consting 25 more Hammers.

Volley Guns cost as much faith as Gatling Guns

![2015-12-04_00002](https://cloud.githubusercontent.com/assets/11430209/11583514/ade763b2-9a28-11e5-9b3a-d66829795b21.jpg)

![2015-12-04_00003](https://cloud.githubusercontent.com/assets/11430209/11583510/ade28234-9a28-11e5-9bc8-b91530686140.jpg)

![2015-12-04_00006](https://cloud.githubusercontent.com/assets/11430209/11583513/ade6bb56-9a28-11e5-8c94-a7735374c3f8.jpg)

**Comment by LoneGazebo** [comment]
Most of these were done via algorithm, but it seems I missed a line or two.
