### ISSUE TITLE
The Great Merge, To-Do List

### ISSUE THREAD

**Issue by nobubblegums** [LoneGazebo/Community-Patch-DLL#8730]
With the new Vox Populi folder/modinfo players will get the main benefit of merging: fewer clicks. That said, there's still some merging and consolidation to do, and we can gradually work towards them without halting development or breaking functionality.

- CBO files themselves aren't fully consolidated. The main culprit is the Corporations module, which makes additions to buildings, technologies, policies etc. Those can be merged into the base files under Balance Changes. 
- Happiness is also in the Modular Elements folder, needs to be merged.
- Religious buildings are also in a separate file. They can be merged, but not a priority.

- CSD is the most difficult one to merge, as it makes a lot of changes to base tables, it also requires some consolidation within modmod files. I suggest leaving it to last.

- C4DF files are more straightforward, but some of them have no equivalent in CBO, so we may need to create separate folders (like Concepts) under Balance Changes.

- Compatibility files seem to be the easiest ones to consolidate, they can be first consolidated into their respective parent modmod folder, and then into the base files.

- LUAs are done!

-  <strike>More Luxuries is also an easy one to consolidate, with most additions made for new resource arts. I'll restructure the main Art/Resources folder (which currently only includes Brazilwood), to accommodate them. </strike>

**Comment by nobubblegums** [comment]
Oh and there are those... The ones I meant were the simple sql&xml files that I merged into (2), I didn't touch the LUAs of 6a,b,c for now, but they'll need some treatment too.

**Comment by azum4roll** [comment]
AssignStartingPlots.lua can be moved into (2) without any changes.

**Comment by nobubblegums** [comment]
Alright, I'm moving that into CoreLua since afaik the installer removes the whole LUA folder.
