### ISSUE TITLE
Two AI lancers poof into existence and one is able to move immediately

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#8733]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_

1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_

InfoAddict (v 22)
Promotion Flags EUI for VP (v 3.1)
UI - Improved City View (Vox Populi EUI) (v 11.0)
UI - Religion Spread (Vox Populi) (v 1.2)

_3. Error description:_ 

When I end turn two Japanese lancers poof into existence 1NE and 1NW of Kyoto.
The one 1NE is able to move immediately, and kills my musketman.

Japan is not friends or allies with any militaristic city states.
Japan doesn't have vassals.
Japan doesn't have faith purchasing belief.
Kyoto is currently working the defense process.
Japan has 6 tradition, 6 fealty, 6 rationalism, 1 order.

I'm not aware of what other mechanisms exist for this to happen.
I asked on the forum, and didn't get an answer after roughly 48 hours, so I'm posting here.
Sorry if this is just me being an idiot and forgetting something obvious.

![image](https://user-images.githubusercontent.com/4227288/157355201-d9f11625-2fc1-4d0c-8f32-1948fdf8ad04.png)

_4. Steps to reproduce (optional):_

[LAST.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8210915/LAST.zip)
Load save. End turn.

**Comment by azum4roll** [comment]
They just finished building one and bought one at the same time?

**Comment by gamask** [comment]
The city is working the defense process.

**Comment by gamask** [comment]
?
