### ISSUE TITLE
One city challenge: when capturing city with Mt. Kilimanjaro, all (owned) units keep the promotion

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8738]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_
Alternative difficulty

_3. Error description:_ 
1. Capture city that has Mt. Kili on OCC
2. City gets deleted
3. All units (still) have the Natural wonder's promotion (altitude training)

![image](https://user-images.githubusercontent.com/24713571/157547083-c78fcb79-52d6-4a5f-94ef-4e94ec7aa139.png)

**Comment by LoneGazebo** [comment]
Yeah if you ever own it, you get the effect.
