### ISSUE TITLE
city/unit:IsWithinDistanceOfUnit/Promotion/Combat, et al.

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#874]
I swear I remember this being addressed when these methods were first developed, but perhaps I am mistaken. Basically, I'm looking for the city/unit:IsWithinDistanceOfX methods to include the tile of the unit object. So if a Warrior is stacked with a Great General, "unit:IsWithinDistanceOfUnit(unitWarrior, 1)" should return true. Would this be ok?

**Comment by LoneGazebo** [comment]
Right now these tests exclude the tile they are on. Let's use '0,' instead of '1' for the test, as the pathfinder returns 0 for stacked unit path distances. So unit:IsWithinDistanceOfUnit(unitWarrior, 0) will return true (in the next version I make) if they're stacked.

**Comment by LoneGazebo** [comment]
Lunch break, so I whipped it up real quick. Download incoming.

**Comment by LoneGazebo** [comment]
https://mega.nz/#!7c1UgCjA!iHE3Erul5X3vLuvHfxTvDbQHZD03CDuWgrSp7qZvWKM

**Comment by JFDaly** [comment]
Works, thank you:)
