### ISSUE TITLE
Free compannions

### ISSUE THREAD

**Issue by tolonaro** [LoneGazebo/Community-Patch-DLL#8740]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
You gain access to free companions about mid game.  The next step up though no longer exists - and the ability to update them also disappears.  huge, standard speed, narrow width, circum on

_4. Steps to reproduce (optional):_
happens in several leaders - poland, india, shoshone

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@tolonaro I have no clue what you're saying, sorry.

**Comment by tolonaro** [comment]
Vox populi 1.4.6  and earlier, when authority policies are completed, you should have ability to purchase in sequence Free companions, Foreign Legions, Mercenaries. It is possible to buy the Free companions and then upgrade them to Tercios.  However, when Mercenaries should be purchasable, Free Companions drops out but the mercenaries do appear.  In addition, if the free companions have not been upgrade to Tercios before this point, then the ability to upgrade the Free companions also disappears.
[Shoshone Art 01.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8238927/Shoshone.Art.01.zip)

**Comment by LessRekkless** [comment]
I think he means "Free Company" doesn't have an upgrade path.

**Comment by LessRekkless** [comment]
Foreign Legion is bugged and not purchaseable in 1.4.6, fixed in commit d408ac1ebd28571b11938f2c3e0cf97b3bcfd7db.

I guess this is what he's talking about, because Free Company still upgrades into Tercios when Mercenaries are available:
![image](https://user-images.githubusercontent.com/34615525/158285254-7f65b384-e30b-4a1f-aec5-4d05536c25c1.png)

**Comment by tolonaro** [comment]
Thanks for the commit
Not sure the problem with the save file.  I just grabbed one I was using.  Oh, well.
