### ISSUE TITLE
Can't buy Inquisitors after capturing Holy city

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8743]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Can't buy Inquisitors after capturing Holy city, even if the religion is majority in my empire. (and the religion is enhanced of course)

_4. Steps to reproduce (optional):_
1. Don't found religion
2. Capture Holy City (with an enhanced religion)
3. Attempt to buy Inquisitor (no option to buy them)

**Comment by LessRekkless** [comment]
this is the only holy city you own, correct?

**Comment by maarten99** [comment]
From 2.0 release log
- Swept away most of the religion weirdness, like World Congress delegates not being added and unbuyable Inquisitors
