### ISSUE TITLE
No extra votes from Religious Authority when owner of Holy City (but not founder of the religion)

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8744]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_
Alternative Difficulty
3/4 UC

_3. Error description:_ 
I own the Holy city and have 27 cities following my (acquired) religion, religion is also my majority religion.
I should get 2 votes (1 vote per 10 following) from the cities following.

![image](https://user-images.githubusercontent.com/24713571/158033227-8ac4f9e9-e9ff-44d7-99ac-36710d7a7bee.png)
![image](https://user-images.githubusercontent.com/24713571/158033236-ae63997c-4b7c-44fa-8733-2cf1ec603c9e.png)

**Comment by LessRekkless** [comment]
This is the only holy city you own, correct?

**Comment by maarten99** [comment]
At this time, I owned 2 holy cities (you can see in 1st screenshot), but I'm positive it also happens when owning 1 holy city.
