### ISSUE TITLE
City state built a settler

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8745]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_
Alternative Difficulty

_3. Error description:_ 
saves included

[auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8238458/auto.zip)

![image](https://user-images.githubusercontent.com/24713571/158035511-e9ee528d-2e0c-4351-b8a9-84e08e8a1e6e.png)

**Comment by ryanmusante** [comment]
City states are supposed to expand now, that's normal behavior, right?

**Comment by RecursiveVision** [comment]
This will be fixed in the next version.
