### ISSUE TITLE
Resource Diversity Modifier isn't a modifier?

### ISSUE THREAD

**Issue by psparky** [LoneGazebo/Community-Patch-DLL#8746]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_

Found in a very old version but still seems to exist in recent versions.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

On International Trade Routes tooltip, there is often an entry for Resource Diversity Modifier. It seems that this is actually just a bonus amount of gold, not a modifier at all. Here is an example from Discord. The 40% Resource Diversity Modifier is really 0.40 gold (Thanks to GM for the example).

![image](https://user-images.githubusercontent.com/34212653/158035850-5ebd0fcd-b8a3-4a6f-aea0-4cb0309bdf2f.png)

The question is, is it a bug in the UI, so it should just say 0.4 gold, or should it be a proper % modifier?
The bonus that Carthage gets to this 'modifier' would have a huge impact if it were a proper modifier.

If this gets changed, could the fix please be described here so I can apply a similar fix to my old version.

---------------------------

**Comment by RecursiveVision** [comment]
You're correct, nice catch! It was added as a bonus instead of a modifier.

In CvPlayerTrade::GetTradeConnectionResourceValueTimes100(), look for all instances of iResourceBonus.

Replace it with iResourceModifier, and add it to iModifier instead of iValue.

**Comment by RecursiveVision** [comment]
Note: I followed this commit up with another one
https://github.com/LoneGazebo/Community-Patch-DLL/commit/0c582cb0c8a492b5bd6133315d7d9660d22f0e06
