### ISSUE TITLE
Some AI civs appear conflated when meeting them for the first time – affects trade and research agreements

### ISSUE THREAD

**Issue by Ragnall** [LoneGazebo/Community-Patch-DLL#8749]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

_2. Mod list (if using Vox Populi only, leave blank):_
(1) Community Path (v1.02)
(2) Community Balance Overhaul (v.14)
(3) CSD for VP (v.29)
(4) Civ IV Diplomatic Features (v.12)
(5) More Luxuries (v.156)
(6a) Voc Populi - Compatibility Files (EUI) (v.1)
(7) Community Events (v.5)
(7a) Promotion Icons for VP (v.4)
(7b) UI - Promotion Tree for VP (v.22)
(9a) Enhanced Air Warfare 4VP (v.1)
(9d) Reforestation for VP (VM2.0) (v.8)
(over) More Unique Components for VP (v.75)
(over) New Beliefs Mods (v.12)
(overhaul) More Wonders for VP (v.1)
(ui) Trade Opportunities for VP (v.11)
Better Lakes for Vox Populi (v.2)
Enhanced Naval Warfare for Vox Populi (v.8)
Greatest Cities (v.11)
Improved City View (Vox Populi - with EUI) (v.11)
InfoAddict (V.22)
Ingame Editor (v.39)
Monopoly Buildings for Vox Populi (v.3)
Pineappledan's Vox Populi Tweaks (v.27)
Polar Station for VP (v.1)
Really Advanced Setup (v.15)
Ski Resort for VP (v.2)
Tectonic Map Script (v.4)
Wonder Race (v.7)

_3. Error description:_ 
Sometimes when meeting an AI civ for the first time I will also be greeted by another seemingly random civ.  On the turn following the attached save game I was first greeted by Germany which does not have a unit in the vicinity of my caravel.  I was able to trade embassies with Germany.  I was then greeted by America which does have a unit in the vicinity of my caravel, but trading embassies was unavailable.  Trade with Polynesia (their unit in the vicinity of the American unit) worked as intended.  Having played other games with this error, the issue also affects research agreements, etc.

The number of conflated civs seems to increase if the game is restarted on turn zero. I have noticed that the only remedy which seems to be largely effective is to exit the game, clear the cache and verify the integrity of game files via Steam, before starting a new game.

_4. Steps to reproduce (optional):_
Restarting a game on turn zero.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8247968/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Save_game_and_screenshots.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8247973/Save_game_and_screenshots.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Too many modmods and issue is too old.
