### ISSUE TITLE
inca and mountains

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#875]
somebody reported in the forum that inca units now like to rest on mountains ... can't reproduce that (although the UI would indicate it if the mountain was revealed not currently visible, which is fixed)

but, another issue i found is that the movement cost for mountains is 2. so only "fast" units may ever cross mountains, all others would need to end their turn there, and that's forbidden even for inca.

so is this by design? what is the desired behavior here?

**Comment by LoneGazebo** [comment]
Hmm...we could halve the movement cost of mountains – make it a flat 1 for all units, so that a single-tile 'range' would be crossed in one turn.

**Comment by Edaka** [comment]
If I'm not mistaken, mountains in Incan territory count as roads and, as such, even provide bonus speed. I'm probably horribly wrong, though, and confusing it with the city connection element.

**Comment by LoneGazebo** [comment]
they count as a connection, but not a 'road' per se.

**Comment by Der-Zorn-Gottes** [comment]
I played Inca recently (Version 11/5).

- Units can definitly end their turn on mountains. Will take 15 damage from it.

**Comment by LoneGazebo** [comment]
That's intended (being able to end turns on mountains), and the 15 damage is correct as well.

**Comment by ilteroi** [comment]
ah. ok. well, that's rather unfortunate. how about we simplify the rules here? inca can cross, but nobody may stop on a mountain, that's nice and easy.

the problem with this game is that the rules are too complex. take for example mountain crossing - we have two traits, several promotions and one mod:

GetPlayerTraits()->IsAbleToCrossMountains()
GetPlayerTraits()->IsAbleToCrossMountains2()

getCanMoveAllTerrainCount
getCanCrossMountainsCount
GetHoveringUnitCount

MOD_GLOBAL_ALPINE_PASSES

- hovercraft in mountains? (btw, hovercraft have never been tested and were poorly implemented in the first place)
- what is the difference between the two traits?

**Comment by ilteroi** [comment]
come to think of it, it's the same for ice. there's a difference between "crossing ice" and ending your turn there ... i'm trying to find a sane way to "codify" all the movement rules.

**Comment by LoneGazebo** [comment]
That changes works for me.
G

**Comment by ilteroi** [comment]
ok, can you give me a hint where to change the movement cost for mountains?

also, there was some strange bandaid code in the CanCrossMountain code to make sure you have the wheel researched. now, historically i object to this because the inca did not use the wheel and bla bla. also, you get it so early that it does not really make a difference.

so i propose to remove this requirement. however, if anybody insists on it, it should be handled via the prerequisite tech of the trait. where would you set that?

**Comment by LoneGazebo** [comment]
I'm fine with removing the requirement - I think it's tied to the city connection element that looks to see that you can build routes before attempting to make connections. Without routes unlocked, I don't think the connection will work.

I'm not at my PC currently, but all 'cost for moves' code is in the unitmovement section. Uses same code as old carthage UI, so you can trace that over.

**Comment by ilteroi** [comment]
so you mean it's hardcoded? i was looking for the place to change it in XML. or maybe the correct SQL spell. but anyway, i'll try to find it

**Comment by LoneGazebo** [comment]
Here:

else if (MOD_BALANCE_CORE && pTraits->IsMountainPass() && pToPlot->isMountain())
	{
		CvRouteInfo* pRoadInfo = GC.getRouteInfo(ROUTE_ROAD);
		iRouteCost = pRoadInfo->getMovementCost() * 3;
		iRouteFlatCost = (pRoadInfo->getFlatMovementCost() * iBaseMoves) * 3;
	}

In CvUnitMovement, line 136

**Comment by ilteroi** [comment]
same argument for city connections - usually you have the wheel before you have multiple cities? also, how often does it occur that cities are linked by a mountain range?

anyway, good that you mention it, the pure city connection should work already but workers wouldn't consider it when building routes ... problem now is that mountain counts as a road. don't know what will happen if they need railroad.

all in all, these inca traits are a bit idiosyncratic. but i don't have a better idea right now ;)

**Comment by LoneGazebo** [comment]
How so (idiosyncratic)? Mountain connections are neat! :)

G

**Comment by ilteroi** [comment]
well mountains are most rugged territory and declaring them to be equal to a road feels a bit arbitrary. also from a coding perspective, it makes everything complicated.

anyway, not being able to end the turn on a mountain has unexpected effects - it works, but only in quite narrow circumstances, i.e. when the plot on the other side of the mountain is visible. otherwise, there might be an enemy unit there which makes the path illegal.

so i fear it will confuse people. so maybe ending a turn on mountain should be possible after all. luckily with the latest changes it should not be hard to make it so.

**Comment by LoneGazebo** [comment]
I think it's okay - the AI doesn't tend to linger for too longer on attrition tiles.

**Comment by ilteroi** [comment]
yeah, totally forgot about that - does the AI know about the attrition? don't think so, at least i don't think it's included in the danger calculation like fallout. handing out an ability like that and then nerfing it again with attrition? not very logical.

how about no attrition and roads are buildable in mountains?

then there are these questions: 
- if inca have it, can others get it via tech or promotion?
- what is the defense bonus of mountains?
- are range attacks into impassable territory possible?

**Comment by LoneGazebo** [comment]
I think the attrition from mountains is included -there's a whole function for attrition (which is where fallout gets its value from).

I don't think so, not via tech.
I think there is a mountaineering promotion concept from whoward, if we had interest in it.
+25% defense?
No, I don't think so.

**Comment by LoneGazebo** [comment]
Random CTD I thought I should send your way, as it comes out of a function you've worked on. Happens on load, and I can replicate (loading a game while in a game causes it.

![1](https://cloud.githubusercontent.com/assets/7849458/11672233/a7fcdeb6-9ddc-11e5-8fbc-ddb787dd8623.png)
![2](https://cloud.githubusercontent.com/assets/7849458/11672235/aaf8df02-9ddc-11e5-9115-a8aed688739d.png)

Crash happens because it looks like a bad player value (-120) is passing into the get city function while rebuilding the saved game.

**Comment by ilteroi** [comment]
can you send me that savegame? any chance that it's simply incompatible?

regarding the mountains, units are susceptible to ranged attacks there (which is good, i guess). defense bonus is 10%, too low in my opinion.

attrition (more precisely CvPlot::getTurnDamage) is now considered in danger calculation. why did you put in this code to limit the damage instead of changing the terrain properties?

		if(MOD_BALANCE_CORE && plot()->isMountain() && iDamage > 25 && GET_PLAYER(getOwner()).GetPlayerTraits()->IsCrossesMountainsAfterGreatGeneral())
		{
			iDamage = 25;
		}
		else if(MOD_BALANCE_CORE && plot()->isMountain() && iDamage > 15 && GET_PLAYER(getOwner()).GetPlayerTraits()->IsMountainPass())
		{
			iDamage = 15;
		}

**Comment by ilteroi** [comment]
funny side effect: inca can now settle cities in mountains

![image](https://cloud.githubusercontent.com/assets/1358966/11699759/3cc1c392-9ec6-11e5-8424-975973d06de1.png)

is that intended? don't know if it would be possible to capture it :)

**Comment by LoneGazebo** [comment]
Seems...interesting. Does the city art work on larger sizes, or does it clip terribly?

Re: hardcoded values - I was testing and never defined them.

Regarding the saved game, it can be replicated – all you have to do is start a game, run it for a bit, save it, then start a brand new game. Once in that new game, load the other save. It will most likely crash.

**Comment by LoneGazebo** [comment]
Oh, also, when you get a chance, push your current working changes, and I'll merge and send back mine. My end is pretty stable right now, and I'd like to seed another beta soon.

**Comment by ilteroi** [comment]
it actually seems to work quite well:
![image](https://cloud.githubusercontent.com/assets/1358966/11700266/22013e04-9ec9-11e5-95aa-81fd31a87bc8.png)

still against "mountain==road" by the way. if mountain, why not also hill?

i propose to remove the attrition completely, and city founding and route building in mountains.

**Comment by LoneGazebo** [comment]
Heh, neat. Looks really cool, actually! I mean, they're gonna starve to death, but yeah, that's awesome. Is this something the AI knows how to do?

Removing attrition is fine, so long as other players can attack them in the mountains. Perhaps ranged can attack in mountains, and melee too, but melee just don't follow up? Or just ranged?

I think mountain roads are still quite fun - the idea is that mountains cannot be built upon normally, whereas hills can. Mountain roads + mountain cities + mountain connections = a civ that thrives in the 'negative space' on the map, which is really cool.

**Comment by ilteroi** [comment]
well it turns out that the mountains actually have yields. one food, one production. and the city tile is "normal" 2f1p1g.

ranged can attack as is, we'll have to see about melee and city capturing. 

but i see the beginning of a concept there. mountains roads yes, but you have to build them.

AI should be capable, but needs to be tested of course.

will push tonight, but mind that the inca are still a bit rough :)

**Comment by LoneGazebo** [comment]
That's fine re: Inca-rough - mainly just want to sync everything up (I should probably start doing nightly builds on github, but I'm lazy). 

Cities have a 'base yield' minimum when founded, regardless of where they're founded, to keep them from insta-starving and deleting.

**Comment by ilteroi** [comment]
@yields: yeah that's fine. 

roads can be built by default, which is also good, don't know about railroad though.

just found another oddity:

UPDATE Features
SET TurnDamage = '15'
WHERE Type = 'FEATURE_FALLOUT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_TERRAIN' AND Value= 1 );

UPDATE Features
SET ExtraTurnDamage = '-10'
WHERE Type = 'FEATURE_FALLOUT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_TERRAIN' AND Value= 1 );

note the difference in sign - which one is correct?

**Comment by LoneGazebo** [comment]
Turn v. ExtraTurn there – I think the 'extra' is used alongside the anti-fallout promotion?
G

**Comment by ilteroi** [comment]
didn't follow the breadcrumbs till the end ... but here's the TurnDamage code:

			if (eTerrain != NO_TERRAIN) {
				CvTerrainInfo* pkTerrainInfo = GC.getTerrainInfo(eTerrain);
				if (pkTerrainInfo) {
					if (!bIgnoreTerrainDamage) {
						damage += pkTerrainInfo->getTurnDamage();
					}
					
					if (bExtraTerrainDamage) {
						damage += pkTerrainInfo->getExtraTurnDamage();
					}
				}
			}

the bools come from unit promotions like this:

    pPlot->getTurnDamage(pUnit->ignoreTerrainDamage(), pUnit->ignoreFeatureDamage(), pUnit->extraTerrainDamage(), pUnit->extraFeatureDamage());

**Comment by LoneGazebo** [comment]
Yep – I did that for granularity purposes. My best code? No. But it 'works.' :)

**Comment by ilteroi** [comment]
oh man. this is cracking me up.

now it turns out that not all mountains are created equal - the old confusion between plot type and terrain type. and guess what, you apparently can't have cities on a mountain _plot_, only on mountain _terrain_.

i had a plan to clean up that stupidity, but that's dangerous terrain. pun fully intended. so for today, i'll push the inconsistent version and then we'll see

**Comment by ilteroi** [comment]
ok it's pushed.

notes:
- i tried to give the mountain terrain a yield (TerrainChanges.xml) but it did not work? can you fix that? only the inca should see it.
- there was a barb camp on a mountain somewhere
- air strikes still open
