### ISSUE TITLE
Can't make peace with AI. 

### ISSUE THREAD

**Issue by BanterTheGreat** [LoneGazebo/Community-Patch-DLL#8751]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6

_2. Mod list (if using Vox Populi only, leave blank):
All parts of Vox Populi /w 6a and 7a.
(over) More Unique Components for VP (v.76)

_3. Error description:_ 
I am at war with Byzantium and after a while they started making requests for peace. All of these requests and any I make myself are impossible to complete as the rightmost value is always on 'Impossible!'. It doesn't matter what I remove or add to the dialog. I also tried removing any city-state allies we both had but that didn't fix it either.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"): [Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8284292/Logs.zip)

4. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[AutoSave_0380 AD-1960.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8284312/AutoSave_0380.AD-1960.zip)

5. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

6. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Can't load the save.
