### ISSUE TITLE
Borobudur doesn't give prophets additional spread

### ISSUE THREAD

**Issue by TU116** [LoneGazebo/Community-Patch-DLL#8754]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
1.4.6 - no relevant mods.

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Just as title says, despite the in game text claiming prophets get additional spread, they don't. I also experienced this 2 versions ago I think so it's not all that recent.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by TU116** [comment]
PS : Any way I could manually set my prophets to 5 spread for my current game ? I'm playing pacifist India so I feel a bit bamboozled.

**Comment by PerfectDark99** [comment]
Same issue. If intentional, then the help file must be fixed as it states "missionaries and prophets" gain an additional spread.
