### ISSUE TITLE
Unplayability when attempting multiplayer

### ISSUE THREAD

**Issue by Mandritti** [LoneGazebo/Community-Patch-DLL#8757]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 1.4.6, DX 10 & 11):_
The version that was most recent on March 3rd, 2022

_2. Mod list (if using Vox Populi only, leave blank):_
A modpack that was assembled by someone who is not me - intended to just enable multiplayer and not change the VP mod.  I can track it down if necessary.

_3. Error description:_ 
A multiplayer game (standard multiplayer loading),
The game could not progress stably to turn 1.  Also, on exit and reload as a save file, map data was changed.
Sometimes a crash occurred.  minidump attached.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8356241/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[LetsVP-test-Doodles1.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8356242/LetsVP-test-Doodles1.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8356243/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by canwiz01** [comment]
See #8505
Looks like #8345 is related
