### ISSUE TITLE
No religious pressure in a nearby city

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#876]
![relpres1](https://cloud.githubusercontent.com/assets/12978597/11603983/a7fd6a10-9aef-11e5-8dfc-94a8a2a028e7.jpg)
![relpres2](https://cloud.githubusercontent.com/assets/12978597/11603985/ab27b484-9aef-11e5-8c5e-1d2a699c5f22.jpg)
Got this oddity with the December beta. An AI's city right at my holy city's doorstep wasn't getting pressured for at least a handful of turns. Eventually, the pressure appeared, but I have no idea why. Sorry if this report isn't terribly useful.

**Comment by ilteroi** [comment]
hmm. distance is not so great and there isn't any rough terrain in between. were you at war with them? that severely curtails your pressure.

**Comment by Edaka** [comment]
Nope, no war. I think I only checked back when the city already had 5 pop and at that point the pressure was there - just appeared, I presume, since no citizens have been converted yet. Should have monitored it better.

**Comment by LoneGazebo** [comment]
Did the appearance coincide with any specific tech, such as engineering?

**Comment by ilteroi** [comment]
also: was is possible to create a traderoute to that city?

**Comment by Edaka** [comment]
Alright, weird things happening. Reloaded 3 turns before the screenshot was taken. The academy that can be seen on the screen wasn't there yet and I was at war with a CS. The Indonesian city had 1 pop. Hovered over the pantheon icon - no pressure. Played for three turns, a GS spawned. During that turn I made peace with the CS, checked to see if it was possible to create a TR to the city (it was) and set a worker to auto-improve tiles. Hover over the pantheon icon - pressure appeared! Much earlier than the last time. No techs researched, no buildings built, no policies adopted.

**Comment by ilteroi** [comment]
aaah, i've got a feeling ... the whole thing hinges on the trade route cache. for the AI player this is updated every turn. but probably not for a human - until you try to create a trade route. will fix

**Comment by LoneGazebo** [comment]
That makes sense.

**Comment by ilteroi** [comment]
should be fixed

**Comment by LoneGazebo** [comment]
Cool.
