### ISSUE TITLE
Some statistics on AI operations

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8764]
just informational: here are the outcomes of 2722 AI operations which happened in a testgame on a huge "small continents" map after the latest optimizations (extracted from OperationalAILog.csv).

about 50% of operations were successful, i consider that a good quota.

average duration for the offensive operations is 9 turns (including recruiting and gathering of units).  average distance covered is around 9 plots, so the average movement speed (once they get going) is somewhere around 2 plots / turn. also quite good.

[ai-operation-results.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8370850/ai-operation-results.zip)

so i would say: mission accomplished (pun fully intended)

**Comment by RecursiveVision** [comment]
Excellent! 😄
