### ISSUE TITLE
GameEvents.MinorAlliesChanged.Add

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#8768]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.0, DX 10 & 11):_
VP 2.0

VP 2.0  somehow broke the code because GameEvents.MinorAlliesChanged.Add doesn't work even if EVENTS_MINORS = 1;

**Comment by Padre19** [comment]
@inkyant How does this event work now?

**Comment by inkyant** [comment]
I just tested it with this:
`UPDATE CustomModOptions
SET Value = '1'
WHERE Name = 'EVENTS_MINORS';`
And it worked.
Due to a bug the event would be called whether or not this flag was actually active so double check spelling and the database with SQLite spy.

**Comment by Padre19** [comment]
I have not made any changes to my mods. This event has worked before. Not now. I tested it with  VP and UCS by Enginseer. Not working.

**Comment by adaneslavo** [comment]
I can confirm that it doesn't work. UCS is mod that wasn't change really long time. Now none of the GameEvents.MinorAlliedChanged starts.

Checked with pure VP 2.0 and UCS from this [link](https://forums.civfanatics.com/threads/unique-city-states.607883/page-20#post-16250735). What i did to reproduce the bug:
```
1. Started a game with Events enabled and founded a Religion with my civ.
2. Invented Printing Press and explored all the world to enable World Congress.
3. Invented Writing and created multiple Emissaries.
4. Sent those Emissaries to Jerusalem and used them to ally with the CS.

No effect. Jerusalem didn't adopt my Religion nor Sphere of Influence were granted by the WC.


or just make an alliance with any CS through diplomatic units special action.
```

There's no lua error nor database error.

The code itself for this event:
```
function ImbalanceDemandsIt (iMinor, iMajor, bIsAlly, iOldFriendship, iNewFriendship)
	local minorPlayer = Players[iMinor]
	local majorPlayer = Players[iMajor]
	if bIsAlly then
		if majorPlayer:GetEventChoiceCooldown(GameInfoTypes["PLAYER_EVENT_CHOICE_" .. GameInfo.MinorCivilizations[minorPlayer:GetMinorCivType()].Type]) == 0 and not majorPlayer:IsEventChoiceActive(GameInfoTypes["PLAYER_EVENT_CHOICE_" .. GameInfo.MinorCivilizations[minorPlayer:GetMinorCivType()].Type]) then
			majorPlayer:DoEventChoice(GameInfoTypes["PLAYER_EVENT_CHOICE_" .. GameInfo.MinorCivilizations[minorPlayer:GetMinorCivType()].Type])
		end
	end
end

GameEvents.MinorAlliesChanged.Add(ImbalanceDemandsIt)
```
