### ISSUE TITLE
'Tourism Modifier' growth bonus from trade routes in the cityview

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#877]
![tourmodfood](https://cloud.githubusercontent.com/assets/12978597/11604018/41545fa2-9af0-11e5-9318-a4461a9e0157.jpg)
I'm talking about the one that shows 6% on the screenshot. At this time I had two trade routes going to two different civilizations. With civ A I was exotic (3% tourism modifier bonus) and familiar with civ B (6% tourism modifier bonus). I sent a trade route to civ B first and then the tooltip never got updated when I sent another to civ A. Likewise, when the first trade route to civ B was completed, the 'Tourism Modifier' got reset to 3% - that's a correct value. However, when I reestablished a trade route with civ B again, the tooltip remained at 3%.

**Comment by LoneGazebo** [comment]
Sounds like  I missed a + sign.
