### ISSUE TITLE
Unlimited free policy blocking turn

### ISSUE THREAD

**Issue by Zenroe** [LoneGazebo/Community-Patch-DLL#8771]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.1, DX 10 & 11):_
v102
DX11

_2. Mod list (if using Vox Populi only, leave blank):_
VP
JFD's RIse to power collection
IGE
InfoAddict
Faster Aircraft Animations
Quick Turns
RED DLL For BNW
YNAEMP v23

_3. Error description:_ 
I’ve got a weird glitch in my play through. I’m on marathon giant TSL earth playing as China with 43 civs and 20 cs. I reached the modern era and after picking an ideology (communism) for some reason the game keeps telling me to pick a policy. I’ve tested this and these are the results.

If I pick a tenet, I get unlimited tenets and still end up being told to pick a policy. If I pick a regular policy the pop up goes away but the next turn bar still says pick a policy. If I give myself enough culture to pick another policy via ige, it still tells me to pick a policy regardless of if I can afford it or not.

Any help solving this would be a great help as I’m 500+ turns into this game and would like to nuke Mongolia.

_4. Steps to reproduce (optional):_
Play marathon game on TSL giant earth
get to modern era
adopt ideology

---------------------------
Supporting information:
[net_message_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390311/net_message_debug.log)
[stopwatch.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390313/stopwatch.log)
[system_init.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390314/system_init.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390315/xml.log)
[xml-perf.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390316/xml-perf.log)
[achievements_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390317/achievements_debug.log)
[APP.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390318/APP.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390319/Database.log)
[Localization.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390320/Localization.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390321/Lua.log)
[modding.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390322/modding.log)
[ModInstaller.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390323/ModInstaller.log)

Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting 
[AutoSave_0640 AD-1490.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390331/AutoSave_0640.AD-1490.zip)
data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by nobubblegums** [comment]
Red Dll, I assume that's a dll mod? That's not compatible with VP, neither is JFDs package

**Comment by Zenroe** [comment]
> Red Dll, I assume that's a dll mod? That's not compatible with VP, neither is JFDs package

Yeah RED DLL adds cultural diffusion and a couple other mechanics, and JFDs package adds new government mechanics. They hadn't caused issues before but if they are the problem then thanks.
