### ISSUE TITLE
AI not bombarding, maybe also something sketchy with Citadel defense

### ISSUE THREAD

**Issue by DeAnnoCiv** [LoneGazebo/Community-Patch-DLL#8772]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.1, DX 10 & 11):_
2.0

_2. Mod list (if using Vox Populi only, leave blank):_
Milae's Difficulty mod

_3. Error description:_ 
When my units are standing in range of walled cities (both a compound bow in a citadel and some quints near a coastal city) they aren't bombarded by the AI. Also, my compound bow in the citadel was taking suspiciously high damage from compound bow attacks in the same off-turn.

_4. Steps to reproduce (optional):_
hit next turn, observe, maybe mouseover the notification log to see records

---------------------------
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390975/Logs.zip)
[bombard.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8390976/bombard.zip)

**Comment by RecursiveVision** [comment]
@ilteroi
