### ISSUE TITLE
Further investigation of GameEvents.MinorAlliesChanged

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#8773]
**I decided to start new issue after you closed [previous](https://github.com/LoneGazebo/Community-Patch-DLL/issues/8768) one. @Padre19 asked me for double checking the problem and it indeed exists. I verified it with following conditions:**

I can confirm that it doesn't work. UCS is mod that wasn't change really long time. Now none of the GameEvents.MinorAllieaChanged starts.

Checked with pure VP 2.0.1 and UCS from this [link](https://forums.civfanatics.com/threads/unique-city-states.607883/page-20#post-16250735). What i did to reproduce the bug:
```
1. Started a game with Events enabled and founded a Religion with my civ.
2. Invented Printing Press and explored all the world to enable World Congress.
3. Invented Writing and created multiple Emissaries.
4. Sent those Emissaries to Jerusalem and used them to ally with the CS.

No effect. Jerusalem didn't adopt my Religion nor Sphere of Influence were granted by the WC.


or just make an alliance with any CS through diplomatic units special action.
```
There's no lua error nor database error.
The code itself for this event:
```
function ImbalanceDemandsIt (iMinor, iMajor, bIsAlly, iOldFriendship, iNewFriendship)
	local minorPlayer = Players[iMinor]
	local majorPlayer = Players[iMajor]
	if bIsAlly then
		if majorPlayer:GetEventChoiceCooldown(GameInfoTypes["PLAYER_EVENT_CHOICE_" .. GameInfo.MinorCivilizations[minorPlayer:GetMinorCivType()].Type]) == 0 and not majorPlayer:IsEventChoiceActive(GameInfoTypes["PLAYER_EVENT_CHOICE_" .. GameInfo.MinorCivilizations[minorPlayer:GetMinorCivType()].Type]) then
			majorPlayer:DoEventChoice(GameInfoTypes["PLAYER_EVENT_CHOICE_" .. GameInfo.MinorCivilizations[minorPlayer:GetMinorCivType()].Type])
		end
	end
end

GameEvents.MinorAlliesChanged.Add(ImbalanceDemandsIt)
```
and the Jerusalem case:
```
function FindingSidon()
	for iCS, pCS in pairs(Players) do
		if (pCS:IsMinorCiv() and GameInfo.MinorCivilizations[pCS:GetMinorCivType()].Type == "MINOR_CIV_SIDON") then
			LostSidon = iCS
			GameEvents.PlayerBullied.Add(EverydayDiscoveringSomethingBrandNew)
		elseif (pCS:IsMinorCiv() and GameInfo.MinorCivilizations[pCS:GetMinorCivType()].Type == "MINOR_CIV_LHASA") then
			LostLhasa = iCS
			if not Game.AnyoneHasWonder(iBLhasa) then
				GameEvents.CityConstructed.Add(SinnersToTheGround)
				GameEvents.PlayerCanConstruct.Add(CanWeFixIt)
			end
		elseif (pCS:IsMinorCiv() and GameInfo.MinorCivilizations[pCS:GetMinorCivType()].Type == "MINOR_CIV_JERUSALEM") then
			LostJerusalem = iCS
			GameEvents.MinorAlliesChanged.Add(ImbalanceDemandsIt2)
		end
	end
end
```
EVENTS_MINORS is 1.
![obraz](https://user-images.githubusercontent.com/33016300/161120706-3f2f33c5-51c0-4ee9-ab45-196e74c93e7e.png)

Events enabled:
![obraz](https://user-images.githubusercontent.com/33016300/161121394-5b22c766-e312-4c67-8917-cb76bdf9e0a9.png)

**Comment by Padre19** [comment]
UPDATE CustomModOptions SET Value = 1 WHERE Name = 'EVENTS_MINORS';

 VP + IngameEditor + this lua

------------------------------------------------------------------
function CSAlly (iMinor, iMajor, bIsAlly, iOldFriendship, iNewFriendship)
	local minorPlayer = Players[iMinor]
	local majorPlayer = Players[iMajor]
	if bIsAlly then
	print("CS Fire bIsAlly")
	end
end
GameEvents.MinorAlliesChanged.Add(CSAlly)
-----------------------------------------------------------------

No changes in Logs / Lua file when I ally with any CS

**Comment by adaneslavo** [comment]
That's exactly what I wanted to do, but didn't make it.
At some point I thought that this could be issue with Event system, but the why other things like WC or religion stuff related to Jerusalem doesn't work as well? Maybe something went wrong during merging?

**Comment by Padre19** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/commit/18cd4a386f5bd75020ac2ada463ec208806c54d7

**Comment by inkyant** [comment]
That's strange, I will check with your mod.

In my mod I had exactly this code:
In SQL:
```
UPDATE CustomModOptions
SET Value = '1'
WHERE Name = 'EVENTS_MINORS';```
In Lua:
```
function test(a, b, c, d, e)
    print("test")
end

GameEvents.MinorFriendsChanged.Add(test)
```

**Comment by adaneslavo** [comment]
There should be GameEvents.**MinorAlliesChanged**.Add(test)

**Comment by inkyant** [comment]
Ok, I'll check that as well.

**Comment by adaneslavo** [comment]
Good to hear.
