### ISSUE TITLE
Some peace treaty weirdness

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8775]
version 2.0

* america declares war on me, doesn't make a lot of progress though
* after about 15 turns they offer peace, i do not accept
* two turns later i offer peace, they do not accept although nothing really changed
* one turn later they ask for peace again

quite weird but i don't have logs

**Comment by RecursiveVision** [comment]
@ilteroi What's likely happening is that they're close to the peace threshold and it's fluctuating because of city danger levels.

I could add a bit of leeway once they've offered peace, but that'd require a new memory value for every major.

**Comment by RecursiveVision** [comment]
@ilteroi Never mind, found a way around it with existing memory values. They now have some leeway - once they offer peace they will have some leeway before refusing again, though not in all cases.
