### ISSUE TITLE
Left clicking on stacked notifications doesn't switch to the next

### ISSUE THREAD

**Issue by azum4roll** [LoneGazebo/Community-Patch-DLL#8776]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.2, DX 10 & 11):_
2.0.2 DX11 + ilteroi's city bombard fix

_2. Mod list (if using Vox Populi only, leave blank):_
Nothing that matters

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/14953746/161254907-c94c1591-05ac-4798-a625-2ca6cea16e27.png)
Left clicking on a stacked notification just repeatedly highlights the same one instead of scrolling to the next one.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Padre19** [comment]
Where we find ilteroi's city bombard fix ?😀

**Comment by azum4roll** [comment]
Build the DLL yourself lol

**Comment by Padre19** [comment]
Or download VP 2.0.3. 😁
