### ISSUE TITLE
"Naval" to "maritime."

### ISSUE THREAD

**Issue by Lady-Glass** [LoneGazebo/Community-Patch-DLL#8778]
v2.0.2

The following notification appears on completion of a trade route: "Citizens from the [...] city of [...] used your naval Trade Route to visit the city of [...]"

This sentence should use the civilian "maritime" rather than the military "naval" to imply peaceful trade.

**Comment by adaneslavo** [comment]
More often civ 5 uses "Sea Trade Route" afair.

**Comment by RecursiveVision** [comment]
naval -> sea
