### ISSUE TITLE
City not getting the +3 hammer from Progress/Organization policy

### ISSUE THREAD

**Issue by seahrh** [LoneGazebo/Community-Patch-DLL#8779]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.3, DX 10 & 11):_
2.0.3

_2. Mod list (if using Vox Populi only, leave blank):_
No other mods.

_3. Error description:_ 
City is not getting the +3 hammer from Progress/Organization policy (or at least the city screen UI is not showing the bonus).

_4. Steps to reproduce (optional):_
Play as China and pick Progress/Organization policy.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8403340/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

[Wu Zetian_0038 BC-2480.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8403341/Wu.Zetian_0038.BC-2480.zip)

4. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

5. Screenshots (optional):
![20220404183517_1](https://user-images.githubusercontent.com/4428622/161526958-0e90058e-1085-478d-a6a7-6083c6a8912c.jpg)

**Comment by Zuizgond** [comment]
The +3 production in on city tile. Always been like this afaik.
