### ISSUE TITLE
AI built 2 wonders in 2 turns (Stonehenge gives too many instant yields to AI)

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8780]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.3, DX 10 & 11):_
2.0.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Egypt built Stonehenge on turn 28, then built Pyramids on turn 29.
I'm assuming he received enough production from choosing his pantheon (granted by Stonehenge), that he was able to build the second wonder in 1 turn.

Difficulty is Deity, and he has a golden age (30 production in capital). He did NOT get a ruin, nor was he able to tribute a mercantile city state.

Perhaps the instant yields should be reduced and instead the AI should be given cost reductions.

Auto saves:
[auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8403458/auto.zip)

![image](https://user-images.githubusercontent.com/24713571/161403232-6c44208b-5cb8-480f-9a75-26fee6c6906f.png)
![image](https://user-images.githubusercontent.com/24713571/161403234-28d44efe-bac1-404c-8dcc-2adfb0669cf4.png)

Take seat:
![image](https://user-images.githubusercontent.com/24713571/161403244-82b89de5-df05-404e-93a2-d5339031946e.png)
![image](https://user-images.githubusercontent.com/24713571/161403251-6b760106-40d0-47ac-94dc-2730cf8f87d9.png)

**Comment by RecursiveVision** [comment]
This is a natural consequence of instant Production yields.

**Comment by maarten99** [comment]
I understand that this is a product of instant yields, but this should not be intentional.
Do the instant yields get affected by the GA and UA production modifiers? Getting a second wonder for free because the first one gave them a free pantheon, and thus instant yields, is ridiculous imo.

**Comment by adaneslavo** [comment]
They got instant Faith and Pantheon, but where was Production from? Pantheon only boosted one Lake (he has no Marshes), so it was not crucial factor in this process. How did he get a Golden Age so early?

Maybe base VP should touch a bit WorldWonder factors? In More Wonders mod I modified them to make hard building more than WW in the same Era, and less in further Eras, but I did that, because of WW spam after adding multiple new WW. Here it seems like the cost of Pyramids is too low.

**Comment by maarten99** [comment]
No ruins, I checked with IGE reveal all (no units of his are near a ruin)
(You can see he has 6 units, 6/9 supply cap in the image from OP, 4 units around his city, 2 pathfinders nowhere near a ruin)
![image](https://user-images.githubusercontent.com/24713571/162441079-ec95e0d7-97dd-42ec-8127-220715ae0fb5.png)
![image](https://user-images.githubusercontent.com/24713571/162441117-ce2551ab-ffdf-4714-afbd-1610a5a2bcc5.png)
![image](https://user-images.githubusercontent.com/24713571/162441166-0f19521e-47e4-4328-8e27-f59a2845b14c.png)

**Comment by psparky** [comment]
Perhaps he had already part-built pyramids before switching to Stonehenge.

**Comment by adaneslavo** [comment]
What is the logic in this? He could lost both WWs with such a move.

**Comment by psparky** [comment]
It's not logical so the AI can't do it. Err, yeah.

Seriously though, it's always been possible for a build to be interrupted and then the AI can decide something else, including another wonder, is the best thing to build.

I was hoping the poster could check, maybe with IGE, if this might be what happened here.

**Comment by maarten99** [comment]
@psparky You could have checked yourself, I included all the autosaves, but I was kind of curious too:
![image](https://user-images.githubusercontent.com/24713571/163998438-c65900e3-d11a-4e87-9019-fc59b9aaf049.png)
![image](https://user-images.githubusercontent.com/24713571/163999349-bf8ee674-fde6-4df0-9cb2-636153ac96d8.png)
![image](https://user-images.githubusercontent.com/24713571/163998379-019e5f0e-4ef0-4ae9-9892-925c2181b426.png)
![image](https://user-images.githubusercontent.com/24713571/163999253-d83ad193-5492-4186-8122-066817029364.png)
![image](https://user-images.githubusercontent.com/24713571/163998305-c726e5b6-19fd-4e70-90e1-8342e77ce340.png)

![image](https://user-images.githubusercontent.com/24713571/163998209-0b2df98a-81f4-462c-a925-ed46d5322126.png)

![image](https://user-images.githubusercontent.com/24713571/163998144-f3ac6968-19d3-4186-9b31-a09cc62df2dd.png)


![image](https://user-images.githubusercontent.com/24713571/163997303-d23728d8-84dd-4240-b845-72070345bdb3.png)
![image](https://user-images.githubusercontent.com/24713571/163997368-3268f12c-d813-49e9-be98-dfa427fb9f01.png)
![image](https://user-images.githubusercontent.com/24713571/163997567-990937b1-9b2a-4c95-b23a-87a042a6eb88.png)
![image](https://user-images.githubusercontent.com/24713571/163997455-ff6447da-5d2a-45c1-a9d0-df8c81550d33.png)
![image](https://user-images.githubusercontent.com/24713571/163997872-3ef5b5e3-862e-4e57-bd93-6ae0b495e80b.png)
![image](https://user-images.githubusercontent.com/24713571/163997949-88f5404d-05f1-4406-ad92-278883b9f011.png)
![image](https://user-images.githubusercontent.com/24713571/163998030-c2786847-4b0b-42ba-8764-70e02b684a90.png)
![image](https://user-images.githubusercontent.com/24713571/163998528-157d9ca1-f2ba-444d-9ed6-f37e21e8cbeb.png)
![image](https://user-images.githubusercontent.com/24713571/163998619-8192ca15-952d-4483-99f7-992608b9d0e7.png)
![image](https://user-images.githubusercontent.com/24713571/163998698-8ffdb489-3e9a-4058-861f-86927164f15b.png)
![image](https://user-images.githubusercontent.com/24713571/163998762-60b01580-e2aa-48a4-9b56-bb59f690ad8f.png)
![image](https://user-images.githubusercontent.com/24713571/163998861-4e2bed17-1178-4787-a159-c06bb4f1838c.png)

**Comment by maarten99** [comment]
So no, he straight up 1 turned his 2nd wonder without a ruin, overflow or a mercantile tribute.

**Comment by maarten99** [comment]
So no, he straight up 1 turned his 2nd wonder without a ruin, overflow, prebuilding it or a mercantile tribute.

**Comment by psparky** [comment]
I don't have 2.0.n installed at this time, so couldn't check it myself. I'm glad you posted your findings, even though my suggestion was wrong, so thank you. BTW, posting the logs is often useful when raising reports - I believe they would have shown my idea was wrong in this case.
