### ISSUE TITLE
Forgotten AI units

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#8781]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.3, DX 10 & 11):_2.0.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Mongolian friendly units seem to be forgotten inside my territory (we have open borders). Mongolia as at war with Morocco who is my next door neighbor, but Mongolian units never made an attempt to go there and fight. Looks like they're abandoned by the AI. 

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8403614/QuickSave.zip)

I

**Comment by ilteroi** [comment]
cannot load it. grrr
