### ISSUE TITLE
City State Gifts

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8784]
just got an aircraft carrier as a gift from a city state. seems a bit weird? is that intended?

**Comment by adaneslavo** [comment]
What a gift! They probably love you.
Are those gifts totally random or there's some weight of frequency.

**Comment by RecursiveVision** [comment]
@LessRekkless

**Comment by LessRekkless** [comment]
Huh. From what I understand, it's a weighted random pick of the 5 units with the highest (R)CS. Wouldn't have thought an aircraft carrier would be there, but I'm not opposed to seeing it, really.

I didn't touch the normal unit gift generation, so I'm surprised this is the first mention of it.

**Comment by adaneslavo** [comment]
Where can I find the code for the spawn algorithm?

**Comment by RecursiveVision** [comment]
Wait, I closed the wrong issue, ignore that.

**Comment by ilteroi** [comment]
apparently ok #9755
