### ISSUE TITLE
AI is willing to capitulate with a low warscore

### ISSUE THREAD

**Issue by usadefcon1** [LoneGazebo/Community-Patch-DLL#8786]
**1. Mod version: 2.0.3**

**2. Mod list:**

![Mods](https://user-images.githubusercontent.com/57153924/161796367-5ae7f2af-63f3-4107-99b2-890629e6dd17.jpg)

**3. Error description:**

I got the Aztecs to capitulate at -10 and Ethiopia at -16 warscores. In both cases I hadn't taken a single city. I was expecting something out of them, but not complete surrender.

In both cases I had to manually add Capitulation to the trade board. Clicking "What Deal Would End This Confit" didn't add it.

**4. Steps to reproduce (optional):**

In the attached save game talk to the Aztec and offer Peace. Then add Capitulation to the trade board. He will take it and be very happy about it. (note that Historical Religions Complete, 4UC, ENW and EAW  are required for this save)

**1. Log files**

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8419951/Logs.zip)

**2. Save game**

[Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8419955/Save.zip)

**3. Screenshots (optional):**

![01](https://user-images.githubusercontent.com/57153924/161798080-03912ca9-4ce5-45d9-96b2-5fbe86e9e756.jpg)

![02](https://user-images.githubusercontent.com/57153924/161798098-36a2c1ba-0247-4d96-a99d-1c814562b1b2.jpg)

![03](https://user-images.githubusercontent.com/57153924/161798110-e4e678a0-d8a4-4d64-9920-aed84faae29b.jpg)

![04](https://user-images.githubusercontent.com/57153924/161798117-d4f57454-7974-4954-8da8-976865e8c80b.jpg)

**Comment by maarten99** [comment]
I had the same bug with "vanilla" VP 2.0.3
Basically in the screen where the AI sues for white peace, the player can add anything they like: captiulation, gold, ... and the AI will accept (because they think it's just white peace?).

**Comment by RecursiveVision** [comment]
@usadefcon1 Please upload your MODS folder. Alternatively, can someone provide a save without the extra mods?

**Comment by maarten99** [comment]
@RecursiveVision I hunted down my autosave for you.
[AutoSave_0196 AD-1360.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8512649/AutoSave_0196.AD-1360.zip)
[auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8512652/auto.zip)

![image](https://user-images.githubusercontent.com/24713571/163996230-5f9d87e2-0720-402f-93f3-a069dc7cfcda.png)

**Comment by RecursiveVision** [comment]
I hate the deal AI. Fixed it for now.
