### ISSUE TITLE
Colonist, Pioneer and early buildings

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#879]
Please consider adding herbalist and well to the building list of andvanced settlers.

**Comment by LoneGazebo** [comment]
This was discussed earlier, and it's not viable, as the buildings are dependent on location, unlike other buildings in the advanced list.

**Comment by Der-Zorn-Gottes** [comment]
I see.
But don`t they have harbours and lighthouses which are also dependent on location?

**Comment by LoneGazebo** [comment]
Good point. The dependcy code for those buildings operates differently, I believe, though I may have changed it. I'll check, as I don't want to spread misinformation.
