### ISSUE TITLE
Promotion Icons on some units are missing

### ISSUE THREAD

**Issue by Primarch-Alpharius** [LoneGazebo/Community-Patch-DLL#8795]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.3, DX 10 & 11):_
2.0.3
DX9
_2. Mod list (if using Vox Populi only, leave blank):_
Pdan's 4UC

CUSTOM CIVS:
SMAN's Duchy of Brittany
GH's Ainu
GH's Scotland
GH's Louisiana
Pdan's Cambodia
Pdan's Goths
Hinin's Hisatsinom
MC and LITE's Nubia
MC's Greece and Macedon Split

_3. Error description:_ 
Indirect Fire, and Barrage 2 Promotion Icons are invisible/missing on the unit's tab but functions normally as if it had the relevant promotions. The icons reappear when re-selecting the unit several times.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![1](https://user-images.githubusercontent.com/82583658/162415208-14b57c5d-7488-4bed-83d5-43e35de6065f.png)
![2](https://user-images.githubusercontent.com/82583658/162415257-2e40f5bc-9f9d-4c95-ba3a-956af395bb7b.png)

**Comment by nobubblegums** [comment]
Too late to ask this but can you share the lua log if you get this again?
