### ISSUE TITLE
EUI not being installed with VP?

### ISSUE THREAD

**Issue by treacherousfiend** [LoneGazebo/Community-Patch-DLL#8799]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.3, DX 10 & 11):_
2.0.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
EUI isn't being installed to my game when I use the VP installer.
It's very possible that i'm doing this wrong but it feels like there's a lot of conflicting info regarding EUI and VP, for example, the "How to Install" page has a dead link for a specific VP compatible version of EUI, and EUI's current download page says that its incompatible with VP (even the patch notes from the current release says it isn't).
The rest of the mod is being installed fine so I don't know if its an issue with the installer or not.
(sorry if this is the wrong place, but it looked like the troubleshooting part of the forum has been shut down)

_4. Steps to reproduce (optional):_
N/A(?)

**Comment by nobubblegums** [comment]
The link is indeed dead, but read more closely, that's for people using only the Community Patch, not VP. That part could be in bold though.
Anyway, the installer sometimes misplaces the EUI folder. You can download it from here https://drive.google.com/file/d/1uTAD_mPY8_sn_q0kV6LPv3C0DAbEDTmi/view?usp=sharing , then extract it to "YourSteamFolder\steamapps\common\Sid Meier's Civilization V\Assets\DLC" .

**Comment by treacherousfiend** [comment]
Ah thank you, the whole situation is still a bit confusing for me, but thank you nonetheless!
