### ISSUE TITLE
Something wrong with promotions TT in unit window

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#8801]
VP 2.0.3 + Promotions Overhaul testing:

I loaded my mod with new version, but have a problem I cannot resolve, and it was not present before.
Some promotions have same labels for Description and Help for example PROMOTION_IGNORE_TERRAIN_COST had TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST for both columns, which means the title is also a help text. In my PO I set (eons ago) fix for this, so, I renamed promotions and for Help texts I did additional text labels:
```
INSERT INTO Language_en_US
			(Tag,															Text)
VALUES		('TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST_HELP',					'Unit [COLOR:255:230:85:255]ignores Terrain Cost[ENDCOLOR].');

UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST_HELP' WHERE Type = 'PROMOTION_IGNORE_TERRAIN_COST';

UPDATE Language_en_US SET Text = '[COLOR:100:155:60:255]Quick[ENDCOLOR]' WHERE Tag = 'TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST';
```
In Pedia it looks like this:
![obraz](https://user-images.githubusercontent.com/33016300/162618958-bf109dfa-7d47-489c-865c-7d4b842c9edc.png)
so everything should be ok, but in Unit Popup window we have something like this:
![obraz](https://user-images.githubusercontent.com/33016300/162619033-32961cf4-f7dd-4f7e-bea2-d984215e9b1f.png)
For a comparison it should look like this:
![obraz](https://user-images.githubusercontent.com/33016300/162619076-d7dd4ee3-0033-44b1-a3c7-1c5ecd15c6f4.png)

In SQL it looks fine:
![obraz](https://user-images.githubusercontent.com/33016300/162619136-de16d864-4296-44d2-be48-4f942624b931.png)

What did you break in last update? Why promotion window does not show the Description? Why it breaks the text I have in Help label ("Unit" word becoms yellow, and I cannot tell you why)?

Such a problem exists for all promotion which shares Description and Help texts. I counted 32 such promotions. There were 4 more, but you've added new Help labels for them in recent update (I had to fix that too).
```
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_STEAM_POWERED_HELP' WHERE Type = 'PROMOTION_STEAM_POWERED';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP' WHERE Type = 'PROMOTION_ANTI_HELICOPTER';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_I_HELP' WHERE Type = 'PROMOTION_ANTI_SUBMARINE_I';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ANTI_SUBMARINE_II_HELP' WHERE Type = 'PROMOTION_ANTI_SUBMARINE_II';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ATTACK_BONUS_HELP' WHERE Type = 'PROMOTION_ATTACK_BONUS';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING_HELP' WHERE Type = 'PROMOTION_CAN_MOVE_AFTER_ATTACKING';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CAN_MOVE_IMPASSABLE_HELP' WHERE Type = 'PROMOTION_CAN_MOVE_IMPASSABLE';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY_HELP' WHERE Type = 'PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CARGO_I_HELP' WHERE Type = 'PROMOTION_CARGO_I';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CARGO_II_HELP' WHERE Type = 'PROMOTION_CARGO_II';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CARGO_III_HELP' WHERE Type = 'PROMOTION_CARGO_III';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CARGO_IV_HELP' WHERE Type = 'PROMOTION_CARGO_IV';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_FIRE_SUPPORT_HELP' WHERE Type = 'PROMOTION_FIRE_SUPPORT';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST_HELP' WHERE Type = 'PROMOTION_FLAT_MOVEMENT_COST';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_FOLIAGE_IMPASSABLE_HELP' WHERE Type = 'PROMOTION_FOLIAGE_IMPASSABLE';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_FREE_PILLAGE_MOVES_HELP' WHERE Type = 'PROMOTION_FREE_PILLAGE_MOVES';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_HEAVY_PAYLOAD_HELP' WHERE Type = 'PROMOTION_HEAVY_PAYLOAD';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST_HELP' WHERE Type = 'PROMOTION_IGNORE_TERRAIN_COST';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE_HELP' WHERE Type = 'PROMOTION_INVISIBLE_SUBMARINE';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_MOUNTED_PENALTY_HELP' WHERE Type = 'PROMOTION_MOUNTED_PENALTY';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_NAVAL_PENALTY_HELP' WHERE Type = 'PROMOTION_NAVAL_PENALTY';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE_HELP' WHERE Type = 'PROMOTION_SEE_INVISIBLE_SUBMARINE';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_SILENT_HUNTER_HELP' WHERE Type = 'PROMOTION_SILENT_HUNTER';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_RIVAL_TERRITORY_HELP' WHERE Type = 'PROMOTION_RIVAL_TERRITORY';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_ONLY_DEFENSIVE_HELP' WHERE Type = 'PROMOTION_ONLY_DEFENSIVE';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_PARADROP_HELP' WHERE Type = 'PROMOTION_PARADROP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_NO_CAPTURE_HELP' WHERE Type = 'PROMOTION_NO_CAPTURE';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES_HELP' WHERE Type = 'PROMOTION_NO_DEFENSIVE_BONUSES';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_HELP' WHERE Type = 'PROMOTION_OCEAN_IMPASSABLE';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_MUST_SET_UP_HELP' WHERE Type = 'PROMOTION_MUST_SET_UP';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING_NAVAL_HELP' WHERE Type = 'PROMOTION_CAN_MOVE_AFTER_ATTACKING_NAVAL';
UPDATE UnitPromotions SET Help = 'TXT_KEY_PROMOTION_SIGHT_PENALTY_NAVAL_HELP' WHERE Type = 'PROMOTION_SIGHT_PENALTY_NAVAL';
```
If you plan to fix them too, let me know please. I want to be prepared for another incompatibility update.

**Comment by adaneslavo** [comment]
@LessRekkless Just got your "message" from discord quoted by one user. I'm not offended, because I knew it is sort of rude, but still, nothing personal (it is just what VP makes for a while, and what made @asterix rage delete its account from civfanatics). I'm just tired and every situation like that makes me pause from modding. I got used to topics on github closed just like that without any answer. That happened at lest few times. But, this mod has been working for few years, kept up by many updates adding, removing or fixing stuff VP changed. Most of them were hidden deeply and not mentioned in the changelog, even though I requested that few times. This time I cannot fix that and found it just by coincidence. I sit and tested that bug and posted all I know. That's what I could do.

If you want to kill another modmod, your will, but without your help, or any of your colleagues developers, I cannot continue that.

If nothing broke in VP and I'm wrong, then just help me find the problem and I will apologize you and leave you alone like you desired.

**Comment by LessRekkless** [comment]
I don’t know if a fix is forthcoming on VP's side; this isn't in my wheelhouse. However, in the meantime, it looks like you can fix the problem on your end.

It seems that the `SimpleHelpText` column was added on our end in order to stop the duplicate display of promotion information in tooltips on the UnitPanel. Of course, since your database update occurs after VP’s, SimpleHelpText is already set to `true` for these promotions.

Add the following line to your *PromotionTextChanges.sql* file, after all of the `UnitPromotions` table changes are finished, perhaps inserted at line 701:
```
UPDATE UnitPromotions SET SimpleHelpText = 0 WHERE Description != Help;
```
Your users may need to clear their cache.

**Comment by adaneslavo** [comment]
It is exactly was the culprit of problems with my modmod. Thanks for help and once again sorry for my rude language, which was the effect of, I don't know, frustration? When something like that changes on VP side I meet a wall I cannot pass. Looking through the code I don;t know at all is impossible for me.
