### ISSUE TITLE
Can't gift a unit to city state if a civilian unit is on the same tile as the military unit

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8806]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.3, DX 10 & 11):_
2.0.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
example:
Want to gift an archer but the gift doesn't go through (no error message) because a worker is on the same tile. After moving the worker the unit can be gifted.

**Comment by ridjack** [comment]
Also seeing this, in the most recent version. Specifically for the remote gifting, in case that wasn't already clear. The yellow border appears, but the gifting fails silently.
