### ISSUE TITLE
EventChoices do not take requirements into account

### ISSUE THREAD

**Issue by adaneslavo** [LoneGazebo/Community-Patch-DLL#8807]
Like the title says, EventChoice table with column EventBuildingClassGlobal filled with building having a requirement inside is placed everywhere regardless of requirements it has. Tested with:
- NearbyMountainRequired (Buildings table)
- Hill (Buildings table)
- Building_ClassesNeededInCity.

**Comment by LoneGazebo** [comment]
Correct, it does not 'parse' options, it puts the building everywhere. The only two caveats are set by the event parameters:

`if (pkEventChoiceInfo->isCoastalOnly() && !pLoopCity->isCoastal())
									{
										continue;
									}
									if (pkEventChoiceInfo->isCapitalEffectOnly() && !pLoopCity->isCapital())
									{
										continue;
									}`
