### ISSUE TITLE
Manual installation instructions for community patch

### ISSUE THREAD

**Issue by Illasera** [LoneGazebo/Community-Patch-DLL#8808]
We are given a text file that says "If you downloaded this mod manually and you are also playing with the full (2) Vox Populi mod, see INSTRUCTIONS.txt ..."

Great, That's doesn't really answer anything, does it?

For those of us who don't want to deal with any installers (Rather the reason will be some antivirus going crazy or no UAC privileges of what not), How do we install the "Community patch" ONLY, manually? 
(Also consider making a proper .txt file for that actually explains it and not a redirection 1 liner text that doesn't address the issue.

* I have no intention of posting on the community patch forums, Yes i have read the installation posts there, its mostly for the installer.
(No, i won't make an account to post there, i already have an account here)

* Since this isn't a ticket, Maybe add a "Discussion" tab for this project, You can do that on github.

Thanks in advance.

**Comment by RecursiveVision** [comment]
@Illasera Just download and run as-is. I'll add a line in that file to note that.
