### ISSUE TITLE
Is this loading screen intentional?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#881]
![2015-12-05_00001](https://cloud.githubusercontent.com/assets/13937047/11610587/006c30a2-9b5c-11e5-8645-0c4cf6f988f8.jpg)

I must have missed it somewhere in the changelog, but is the text box supposed to be aligned toward the right?

**Comment by 8h42** [comment]
It is a new feature in the latest EUI.

http://forums.civfanatics.com/showpost.php?p=14066171&postcount=2141
- GameSetup: full screen dawn of man (during game load)
