### ISSUE TITLE
CTD with MPpatch

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [LoneGazebo/Community-Patch-DLL#8810]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.3, DX 10 & 11):_
Mod version: 2.03, DX 11

_2. Mod list (if using Vox Populi only, leave blank):_
Prussia by JFD
Units- Starting scout by BlouBlou
Units - Sout to Explorer by BlouBlou
Promotions - Ancient Ruins Choice by BlouBlou
Barbarians - Unlimetd Exp by BlouBlou
Soviet Union by JFD
RED Modpack (I disabled it on a save I enabled it on before but the crash still happens.
Bananas are Luxeries by mikeburnfire
Terrain - Poor Tiles Tweak by BlouBlou
Reforestation by framedarchitecture
Faster Aircraft Animations by  Gedemon
Ancient Buildings Pack by thecrazyscotsman
InfoAddict by Rob K
Bridges and Canals by hammerstorm
Civ Names by Policies by Lex
Bob Ross Great Artist by SharkyMcSnarkface
Play The World Extended (Gods and Kings Edition) by Shield Hero V
CameraRotation and WASD Controls (vanilla) by Nutzzz

[MPpatch by Limia](https://github.com/Lymia/MPPatch) (I mainly use it for the LUAJIT performance boost and to play vanilla with a few mods with friends)
_3. Error description:_ 
The save (and other saves before it) crashes to desktop at a specific turn each time i start a new save. In this save, it happens at turn 105.
_4. Steps to reproduce (optional):_
1. Load the save
2. Click next turn

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

3. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

4. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

All data is in here: [Sid Meier's Civilization 5.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8482988/Sid.Meier.s.Civilization.5.zip)

**Comment by RecursiveVision** [comment]
Sorry, no way is this gonna get fixed. Multiplayer is very hard to debug already, never mind with a bunch of modmods.

**Comment by TeaDrinkingProgrammer** [comment]
This crash is in single player thoug, so the multiplayer part shouldn't be an issue right?

**Comment by RecursiveVision** [comment]
Why are you using a multiplayer patch mod in singleplayer? I would not recommend that 🤨

I don't understand how this mod functions but if it modifies the functionality of LUA files or improves the game performance there's a lot of potential for bugs when interacting with a large project like VP.

It's highly likely the crash is a result of your other mods, and we don't debug other mods.

**Comment by TeaDrinkingProgrammer** [comment]
I have installed the mod because I sometimes play vanilla multiplayer and I don't want to uninstall it in between sessions. So where do I go from here, can't you use any of these mods? I get that you aren't responsible for other mods but I would appreciate some help since I am completely new too Civ5 modding.
