### ISSUE TITLE
World Congress Ignored Nuke

### ISSUE THREAD

**Issue by usadefcon1** [LoneGazebo/Community-Patch-DLL#8817]
In my last game the Iroquois nuked Mongolia (which is the first time I've seen the AI do this, awesome)

But when it came time to sanction the Iroquois in the World Congress nobody else was interested.

I think that using a nuke should make the other AI very motivated to stop you, especially in the World Congress.

**Comment by Illasera** [comment]
Nobody cared in WW2 as well, I don't see the issue here.

**Comment by RecursiveVision** [comment]
Not a bug.
