### ISSUE TITLE
Cityview food display 

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#882]
It doesn't differentiate between the food that comes from mercantile city states, Tradition policy tree and internal trade routes (I think). I'm not sure if I'm forgetting anything else - perhaps the Order, the Celtish pantheon and the Piety's finisher since they also give either +1 or +2 flat food to every city. Haven't checked those, though, so don't take my words for granted. Anyway, all these sources of food get grouped into the 'From terrain' category. I hope this wouldn't be a major headache to work with, but it's certainly not a big deal - just a cosmetic issue.
![food cityview](https://cloud.githubusercontent.com/assets/12978597/11613862/eadbdcfa-9c38-11e5-9659-686b506bbdab.jpg)

**Comment by LoneGazebo** [comment]
The game's core mechanics for all actually 'add' the yields to the city tile, so it does come from terrain, technically. Not currently addressable without a lot of rewrites.

**Comment by Edaka** [comment]
Ah, gotcha. Well, Firaxis knows best (:

**Comment by LoneGazebo** [comment]
Psha, yeah. They decided to dump all yields onto tiles early on their design, it seems. I think, looking at the LUA and DLL, they'd originally intended ALL yields to appear on the map.

G
