### ISSUE TITLE
Korea Research Boost is too large?  Boost multiplied by number of cities?

### ISSUE THREAD

**Issue by Tesla101a** [LoneGazebo/Community-Patch-DLL#8822]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.0.3, DX 10 & 11):_
2.0.1

_2. Mod list (if using Vox Populi only, leave blank):_
Community Patch, and InfoAddict (V. 22)

_3. Error description:_ 
Korea's UA to generate research boost triggers once for every city in your empire (I have played games where the research boost granted me 2 and a half technologies in a single turn).  I will update to the latest 2.0.3, however I did not see this bug in the changelog

_4. Steps to reproduce (optional):_
I've set up a two-city empire and have a library nearly built in the capital.  All you need to do is hit end turn.  You can see in the screenshot how I get the boost (+40 science) in each city.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
[Korea Research Boost.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8509100/Korea.Research.Boost.zip)

**Comment by Tesla101a** [comment]
Sorry forgot to mention I also use EUI 1.28g.

**Comment by nobubblegums** [comment]
This is just the Community Patch and not Vox Populi, right? CP doesn't make balance changes, so this is out of scope.

**Comment by RecursiveVision** [comment]
@nobubblegums I suspect this is a bug introduced by VP.
