### ISSUE TITLE
diplo inconsistency

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8824]
in my testgame i managed to offend 2 neighbors by settling 1 city ... both complained, both times i told them to get lost.

the very next turn both of them gift me gold. seems weird?

logs here: [diplo-logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8518552/diplo-logs.zip)
savegame here: [unexpected-gift_Post_0075 BC-1000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8518565/unexpected-gift_Post_0075.BC-1000.zip) (v2.0.3)

edit: it's even funnier. if i give the friendly answer, i still get the same amount of gold from poland but *nothing* from the netherlands.

**Comment by RecursiveVision** [comment]
So the gift logic is very simple. If the AI has a DoF, its current approach is Friendly, and you are lacking Gold/Luxuries, it will gift you one.

**Comment by RecursiveVision** [comment]
@ilteroi Added some sanity checks, should be a bit better now

Loading this without InfoAddict still crashed by the way
