### ISSUE TITLE
CTD when killing a trebuchet as the Huns, over a Great Wall border

### ISSUE THREAD

**Issue by rahenry** [LoneGazebo/Community-Patch-DLL#8828]
Edit: Found it happening in another situation. Seems it's the presence of the GG on the defending tile which causes it, perhaps in combination with the GW
![ss](https://user-images.githubusercontent.com/11766125/164883814-24ab7d39-f3d2-418f-b2e1-431822f553cf.png)

Experiencing a reproducible CTD when killing/capturing a trebuchet. I'm the Huns and I'm capturing it over a Great Wall border. Not sure if all of those factors are relevant. Capturing other units works fine, for instance I just captured the trebuchet on the right.

Amusingly I'm attacking China as the Huns, over the Great Wall

![ss](https://user-images.githubusercontent.com/11766125/164879108-a89125ea-b7b3-42e3-b4c8-0eb8d7f1b99e.png)

_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.1.0, DX 10 & 11):_
2.1

_2. Mod list (if using Vox Populi only, leave blank):_
VP (all components)
Historical Religions
Info Addict
Milae's Hotkeys
Promotion Flags
Really Advanced Setup
Reseed
Wonder Race
UI - Filters in Trade Route Overview
UI - Military Log
Unit Path Viewer

_3. Error description:_ 
CTD when killing/capturing a trebuchet as the Huns over a border, when the enemy has the Great Wall

_4. Steps to reproduce (optional):_
Capture the trebuchet as pictured

---------------------------
Supporting information:
[crash.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8546276/crash.zip)

**Comment by ilteroi** [comment]
cannot reproduce (with my own testgame)
