### ISSUE TITLE
UI propositon

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#883]
After seeing the streem with Marbozir yesterday, I think that two things would be needed:

a) repetition of how much unhappyness each 0.2 of a yield need in the happyness tooltip generates
b) when selecting to build a building from the list, a tooltip informing "given the current needs for yields and religion building this will remove X unhappyness".

**Comment by LoneGazebo** [comment]
a.)Why, exactly?
b.) That would be extremely intensive from a DLL standpoint, so no, we can't do that.

**Comment by AnastaseAlex** [comment]
The idea is that it would make the happyness system more "readable". I read on the forum however that you already did already adress that, so that this thread is just wasting your time, so I will close it.

**Comment by LoneGazebo** [comment]
No worries. I am adding a deficit model in the next version that should help with this somewhat.
G

**Comment by AnastaseAlex** [comment]
The deficit model however will not help with the percentage based reduction in needs. Having knowledge of the base needs, then the reduced needs due to buildings and then the deficit would be giving us total access to the info needed.

**Comment by LoneGazebo** [comment]
Reduced needs due to buildings? You have the % values in the happiness tooltip in cities at the bottom – those are the building values (includes building % reductions as well as increased based on tech and city-size).

**Comment by LoneGazebo** [comment]
I guess

**Comment by AnastaseAlex** [comment]
Concrete example:

My city has a defence yield of 31. It has 26 citizens. The average in the city is 1.19. The global need(avergae + %of technologie discovered) is of 1.67. If I have a baracks in the city, that is -10% going down to 1.51.

The info in the tooltip shows only 1.18 and needs 1.51.

Now, the question is what should I build: an armory or castle? (in terms of happyness)

Right now, as the system stands, I only know that the city produces 1.18 and I need 1.51. The -20% reduction promissed by the armory is not really representative, since it will actually reduce the initial ammount by another 20%, bringing needs to 1.17 while I would asume it brings it to 1.20, not enough to eliminate my happyness problem.

I would have chosen to build the castle, that would give me +10 base yield creating an average of 1.57.

This could be remedied by having access to the whole information, I guess: values produced, average value, global resuirement, city requirement, but that is what I would need to compete in immortal, I guess.

**Comment by LoneGazebo** [comment]
Well the global 'need' you see already calculates in those values (the +/-% values).

Would something like this in a Building's tooltip help?

Needs after construction: x.xx per Citizen

**Comment by LoneGazebo** [comment]
Not guaranteeing that I can do it CPU-cheaply, but is this what you are looking for?

**Comment by AnastaseAlex** [comment]
The global need does integrate those percentage reductions, I know, but I cannot guess how much a reduction a new building would give me if I do not know the initial value I needed before the reductions from policies, buildings etc...

Well I can, but it is very tiresome and removes fun from the game.

What you suggest would be amazing, yes. But the values I am asking for should normally already exist. Just adding the global average modified my tech rate, before any reductions from policies and buildings and wonders and religion, would already be a huge help if what you suggest is not feasable for calculation reasons.

**Comment by LoneGazebo** [comment]
All of the data in the tooltip is precalculated to save time, and is thus stored away in the DLL - breaking it apart would be rough.

I'll look into this. The entire tooltip for happiness probably needs a QoL change, tbh.

**Comment by AnastaseAlex** [comment]
In lower difficulties it is ok for it to be opaque, but when you are in higher difficulties, ever -1% matters

**Comment by AnastaseAlex** [comment]
I re read myself and I seem ungrateful in this post. I am sorry for that. I really really appreciate CPP. It is the ony way I have at the moment to enjoy a 4X game, and remains hugelly addictive.

**Comment by LoneGazebo** [comment]
Oh no, I didn't take it as ungrateful. I'm just trying to put together a concept that will achieve the intended result without adding tons of new numbers. 

What I may do is this:

At the bottom of the tooltip, where the +/-% need modifiers are listed, I'm going to break them down and separate out tech and population by themselves, as they are 'universal.' I'll then leave the specific +/- % modifiers for each yield type for buildings independent.

So, it'll look like this (the whole tooltip):

Unhappiness: x
Sources:
Isolation/Pillage/Starving/Religion/Disconnection (as they already are)
Poverty/Crime/Illiteracy/Boredom:
    Produce: x.x per citizen
    Need: y.y per citizen
    Deficit: z.zz (a yield value, indicating the amount of actual yield you need to bridge the gap)
Modifiers:
Capital - %
Tech - %
Population - %
Poverty: %
Crime: %
Illiteracy: %
Boredom: %

Make sense?

**Comment by AnastaseAlex** [comment]
Yes, it almost does. These modifiers are already included in the need for poverty, etc etc?

Also, the way faith needs work seems a bit opaque. When you found a religion you get a good hit on happyness because of it. It is a bit unclear as to how the specific of "need more followers" work.

Will this be in both the EUI and the non- EUI verions however? If not it needs to be noted in the installation guide.

**Comment by LoneGazebo** [comment]
Adding in the before/after needs element to building tooltips.
