### ISSUE TITLE
great wall shape

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8836]
so this is nitpicking, but the shape of the great wall wonder really bothers me sometimes ... where is this decided?

![image](https://user-images.githubusercontent.com/1358966/165683326-e9df03d6-10cd-4331-94a8-0cda47baeeac.png)

**Comment by adaneslavo** [comment]
Algorithm is quite strange. Sometimes huge areas of your country is not covered at all.

**Comment by azum4roll** [comment]
5-tiles around the city where the Great Wall is built.

**Comment by RecursiveVision** [comment]
@azum4roll Do you know where in the code this is determined?

**Comment by azum4roll** [comment]
CvCity::setupWonderGraphics(), which calls the DLL interface (gDLL->GameplayWonderCreated()) that we can't touch.
