### ISSUE TITLE
Trade screen error with CP v104

### ISSUE THREAD

**Issue by clif9710** [LoneGazebo/Community-Patch-DLL#8840]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.1.0, DX 10 & 11):_DX 10/11 CP v104

_2. Mod list (if using Vox Populi only, leave blank):_CP 104 and InfoAddict

_3. Error description:_ When trade screen opens, all items possible in game are listed for both AI and player, not limited to only those immediately available to AI and player. See screengrab at https://steamcommunity.com/sharedfiles/filedetails/?id=2801444774 Please note, **THIS DOES NOT OCCUR IF CP v89 is used** I found v89 through Steam Workshop.

_4. Steps to reproduce (optional):_open the trade screen

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
1) Did you enable ALL of the components for the version of the mod that you downloaded? You can't install the full VP package but then only enable Community Patch, you have to specifically select "Community Patch only".

2) Are you using EUI? Community Patch only is not compatible with EUI.

3) Have you tried reinstalling the mod?

If none of these three are the problem, then reopen this.

**Comment by clif9710** [comment]
Ok, though I swear I did it before, I just installed only CP and I no longer have the faulty trade screen. I wasn't using EUI, but speaking of EUI, then I must use VP if I want EUI to work? I assume that once VP is enabled as a mod, there is no way to disable it by other means (so I can get CP without VP).
    On Friday, April 29, 2022, 09:58:02 PM CDT, RecursiveVision ***@***.***> wrote:  
 
 

   
   -    
Did you enable ALL of the components for the version of the mod that you downloaded? You can't install the full VP package but then only enable Community Patch, you have to specifically select "Community Patch only".

   -    
Are you using EUI? Community Patch only is not compatible with EUI.

   -    
Have you tried reinstalling the mod?


If none of these three are the problem, then reopen this.

**Comment by RecursiveVision** [comment]
Yes, EUI will only work with full VP - the modded EUI that is included in VP, not the version on the forums.

The autoinstaller will delete any old installation of VP when installing a new version, and also deletes the EUI folder.
