### ISSUE TITLE
Reformation Belief Building Votes capped at num religions (Intentional?)

### ISSUE THREAD

**Issue by Mileslewis** [LoneGazebo/Community-Patch-DLL#8841]
Patch - 2.0

I had 80+ cities following my religion but could only ever get +5 votes in congress from religion with the reformation building.

Seems pretty intentional since I found this line in DLL:
int iMaxVotes = pReligions->GetNumReligionsFounded();

But would be good to be told this in the text if that's the case.

**Comment by RecursiveVision** [comment]
I see no reason why this should be the case tbh. Removed.
