### ISSUE TITLE
Players/AIs can settle adjacent to Natural Wonders in another civ's territory, stealing the tile.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#8844]
Newest version; looking back in Discord, the bug has existed since at least February, and likely before. ( https://discord.com/channels/707403015845576735/721543887285387314/942887820735946792 )

![image](https://user-images.githubusercontent.com/22875626/166126808-4ac484e1-f894-4489-b91b-b628b0c9f7bf.png)
![image](https://user-images.githubusercontent.com/22875626/166126810-8d9032ef-972c-4585-aa28-966663d31818.png)

**Comment by ilteroi** [comment]
for some reason impassable plots were ignored by CvPlot::IsAdjacentOwnedByTeamOtherThan(...)

**Comment by ridjack** [comment]
This issue is still present in 2.3.1.

![image](https://user-images.githubusercontent.com/22875626/172432707-0ad7b347-fa7d-4da6-85ba-c24b41a8ab57.png)

![image](https://user-images.githubusercontent.com/22875626/172432808-1478f608-d116-4919-b507-9d09f3e017b7.png)

**Comment by RecursiveVision** [comment]
@ilteroi

**Comment by ilteroi** [comment]
boolean logic is hard ...
