### ISSUE TITLE
Embarked units show combat bonuses in combat UI

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8845]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.1.0, DX 10 & 11):_
2.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/24713571/166151859-a9af2842-83d4-4a8c-b030-36d13fe63d17.png)
![image](https://user-images.githubusercontent.com/24713571/166151890-b153782e-6cf4-49ad-bcd0-10b1612b6a8c.png)

![image](https://user-images.githubusercontent.com/24713571/166151846-665fe5f4-8e40-459f-a7ed-44b86b9ce090.png)

**Comment by ilteroi** [comment]
seems to be visual only? needs to be fixed on lua side

**Comment by maarten99** [comment]
It does seem to be visual only, and not only on horse archers.
![image](https://user-images.githubusercontent.com/24713571/166166906-102e794f-3c75-44cb-b3ad-0ea8c3461a0f.png)
