### ISSUE TITLE
Embarked units not receiving combat malus from empire unhappy

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8846]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.1.0, DX 10 & 11):_
2.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Embarked units do not receive combat bonuses when embarked, but also do not receive penalties from empire unhappy.

![image](https://user-images.githubusercontent.com/24713571/166151859-a9af2842-83d4-4a8c-b030-36d13fe63d17.png)

**Comment by LessRekkless** [comment]
Intentional. The only modifier an embarked unit gets is embarkation defense.

I will fix the Enemy Unit Panel to get rid of the wrong bonuses.

**Comment by LessRekkless** [comment]
Intentional. The only modifier an embarked unit gets is embarkation defense.

I will fix the Enemy Unit Panel to get rid of the wrong bonuses.

**Comment by LessRekkless** [comment]
Close this in favour of #8845.

**Comment by maarten99** [comment]
combat malus should not be applied
