### ISSUE TITLE
AI using Great Diplomat for influence instead of an embassy too early

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8847]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.1.0, DX 10 & 11):_
2.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Venice used his first G Diplomat (in early medieval era) for influence, instead of putting down an embassy (which is only good very short term but bad long term.)
![image](https://user-images.githubusercontent.com/24713571/166167338-79925817-c9e3-40bb-9df0-dcc07d6ebd63.png)

**Comment by nobubblegums** [comment]
I asked about this on discord, I was thinking about hardcoding the AI to always build embassy when available but some people say the early yields can be as useful as embassies. So not sure what to do about this

**Comment by ilteroi** [comment]
venice may have logic to prefer influence because they want to buy the CS later. still a weird interaction. need to check.

**Comment by ilteroi** [comment]
stale
