### ISSUE TITLE
Vox Populi failing at game start

### ISSUE THREAD

**Issue by Kalthorine** [LoneGazebo/Community-Patch-DLL#8849]
_1. Mod version: Vox Populi v2.1.1
     DirectX version if reporting a graphical issue:  DirectX 12,  DirectX Database Version: 1.0.8

_2. Mod list:  Only Vox Populi (with EUI) -  as per Mod Choice screenshot in attached Screenshot file

_3. Error description:_ 

The Vox Populi mod was added to a fresh, new installation of Civilization V, with no other mods installed at all other than the time (screenshot of mod choice screen attached).  It should be noted that when I used the Automatic Installer for VP 2.1.1, it failed to install EUI at all, despite the Civilization 5 game being installed in the default location (C: Drive, Steamapps folder).  Instead I had to download it manually, adding the UI_bc1 to the "steamapps/common/Sid Meier's Civilization V/Assets/DLC/" folder and the relevant language localization files added to the "Documents\My Games\Sid Meier's Civilization 5\Text" folder.  In case the VP Installer would need to overwrite any vanilla EUI components, I then re-ran the VP 2.1.1 installer.  The cache was cleared before then starting a new game.

It should be noted that a plain, vanilla game (non-modded) game works fine.  However, on starting a new modded game with ONLY Vox Populi enabled with EUI, and no Advanced Setup at all (just a regular modded single player game), the game does not allow me to play.  The first game screen map loads, but nothing is selectable - none of the menus, none of the units, nothing.  Even the selection circles under units do not appear.  Also, the header bar looks weird.   I have enclosed a screenshot of the starting game screen for the modded version in the attached Screenshot zip file.

_4. Steps to reproduce (optional):_
- New Installation of Civilization 5
- Add Vox Populi 2.1.1 via Automatic Installer
- Manually add EUI if not present
- Re-run Vox Populi 2.1.1 via Automatic Installer (not sure if necessary, but just in case compatibility files need to overwrite any EUI components).
- Start Civ 5 game, Choose "Mods", select only the VP components (as per attached screenshot), start single player game

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8602535/Logs.zip)

2. Save game (always attach a save that was made a turn 
Could not attach a save before the turn as the error appeared on the very first turn.  I have attached a save of that turn.
[Washington_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8602539/Washington_0000.BC-4000.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
No actual crash experienced so no MiniDump file.  I have enclosed a copy of the DxDiag dump giving details of my system set-up.
[DxDiag.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/8602701/DxDiag.txt)

4. Screenshots (optional):
[Supporting Screenshots.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8602661/Supporting.Screenshots.zip)

**Comment by psparky** [comment]
It looks like you have the latest version of EUI, which is not compatible with VP. You need 1.28g.

As to why the auto-install didn't work, I'm afraid I have no idea.

**Comment by Kalthorine** [comment]
Thanks for the prompt response.  Could you please point me towards where I can get a copy of EUI 1.28g?  The link to the legacy version page on the civfanatics forum thread just takes me to a page to download 1.29i (and I did click the download link listed to be sure!) as per the attached screenshot.  Thanks in advance for your continued assistance!

[EUI legacy version link issue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8603367/EUI.legacy.version.link.issue.zip)

**Comment by psparky** [comment]
You can get it from the EUI Download Version History tab:

https://forums.civfanatics.com/resources/civ5-enhanced-user-interface.24303/history
