### ISSUE TITLE
Fishing says it gives an extra TR

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#885]
In the Civpedia it states this, yet i still have 2 TRs.

![2015-11-23_00191](https://cloud.githubusercontent.com/assets/11430209/11617632/ab5beada-9c5f-11e5-8233-99f48dfcc3e1.jpg)

![2015-11-28_00003](https://cloud.githubusercontent.com/assets/11430209/11617642/cd1fc862-9c5f-11e5-8f2e-c095b19b4b9d.jpg)

11-28 version

**Comment by LoneGazebo** [comment]
I'll fix.

**Comment by Plockets** [comment]
I am curious, is the fix to remove the text from the Civpedia, or to add a TR? ;)

**Comment by LoneGazebo** [comment]
Fix the civpedia.

G
