### ISSUE TITLE
Can't switch tile from puppet city to non-puppet city

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8851]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.1.0, DX 10 & 11):_
2.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Clicking the switch button doesn't work
![image](https://user-images.githubusercontent.com/24713571/166244452-bed94b7f-52ee-43ea-9796-a060df8cbdbf.png)
![image](https://user-images.githubusercontent.com/24713571/166244512-f6d55430-336f-4861-bba9-eaecc2b9b5d9.png)

**Comment by RecursiveVision** [comment]
Intended
