### ISSUE TITLE
Promotion UI of units not properly centered

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8855]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.1.0, DX 10 & 11):_
2.1
dx11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
It's possible this only applies to the Zulu, the promotions are either too far to the left or right:

![image](https://user-images.githubusercontent.com/24713571/166689489-3de22185-f820-467f-bd8a-71bcf3d05451.png)
![image](https://user-images.githubusercontent.com/24713571/166689510-3ae80008-495e-47e3-95c7-f27179b3199f.png)
![image](https://user-images.githubusercontent.com/24713571/166689546-a66d1bba-132a-4bc6-b186-c73f644a6831.png)
![image](https://user-images.githubusercontent.com/24713571/166689588-dc199c4d-2ae1-4a6a-930f-d14a710cdd25.png)
![image](https://user-images.githubusercontent.com/24713571/166689612-e018c44d-f2af-4096-96a8-b0fcafc6e3ec.png)

also happens on missionaries with PoW promotion
![image](https://user-images.githubusercontent.com/24713571/166713474-d1b34a06-a4a4-4511-bd69-8cd3e59b7c79.png)

**Comment by LessRekkless** [comment]
Could you share a Lua.log of even you select the unit?
