### ISSUE TITLE
Gifted units do not lose Himeji castle promotion

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8856]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.1.0, DX 10 & 11):_
2.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

![image](https://user-images.githubusercontent.com/24713571/166691986-7273c11d-3521-4208-bcdf-a1c3b79803ec.png)
![image](https://user-images.githubusercontent.com/24713571/166692080-21655067-c734-4b0d-9aca-39772a5d0241.png)

**Comment by LessRekkless** [comment]
This likely an issue with all wonders/buildings/policies/techs/traits that give a promotion.

It's pretty hard to fix, promotions don't know where they came from, so we'd have to run through each of the various sources, check to see if it gives a promotion, check to see if the promotion exists on the unit, then check to see if the new controlling civ has the same source.

As a side note: What happens to a unit's Himeji promotion if its owning Civ loses Himeji Castle?  Does it keep the promotion, or does it go away?

**Comment by RecursiveVision** [comment]
@LessRekkless Not necessarily. I think promotions such as Alhambra's Drill shouldn't be removed if Alhambra is gone.

Himeji Castle is meant to provide a +15% defense bonus to the player, so that sounds like something that shouldn't be applied via promotion?
