### ISSUE TITLE
Random diplo penalties

### ISSUE THREAD

**Issue by Plockets** [LoneGazebo/Community-Patch-DLL#886]
Using the current 11-20 version.

I have just signed Open Borders (50 turns remaining) and gotten a DoF (49 turns remaining) with Germany. I have 3 bright green, 3 dark green, and 2 bright red diplo mods with him. On the next turn, Bismark cancels our DoF, and I notice I now have  "You asked them not to spy on you" and "You demanded they not settle near your lands" penalties with him, despite doing neither thing. 

I have the save prior to Bismark cancelling our DoF here: https://drive.google.com/file/d/0B_h-nvJMOUvaQm1CVW5ZOG8xa0k/view?usp=sharing

All you should need to do is hit enter to see it happen.

**Comment by LoneGazebo** [comment]
This was addressed in the current beta version, so it'll be fixed in the future release version. Thanks for report!
