### ISSUE TITLE
City bombard range is 4

### ISSUE THREAD

**Issue by smorgasborgas** [LoneGazebo/Community-Patch-DLL#8861]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.1.0, DX 10 & 11):_
2.0.3

_2. Mod list (if using Vox Populi only, leave blank):_
![image](https://user-images.githubusercontent.com/105085236/167224207-13f5fa17-0984-4a17-ac1e-3ea0d1fb1012.png)

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/105085236/167224318-e63ee4c1-13fb-48a8-9ac3-6314dd1c92fb.png)
My crossbow was 4 tiles away from Arretium (indicated in image) but still got killed by city bombard.

Other relevant info:
Arretium is on a hill
Rome has Red Fort and therefore a Bastion (possibly in Arretium).  This still shouldn't allow for this.
Emperor difficulty

_4. Steps to reproduce (optional):_
I was in a war with Zulus (an age ago) and I didn't see this at that time.  But now against rome in the enlightenment era, it is happening every turn.  But I only see it for Arretium, the other Roman cities I tried didn't shoot me at four or even three tiles.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8643916/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[AutoSave_0700 AD-1610.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8643918/AutoSave_0700.AD-1610.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by smorgasborgas** [comment]
I think the old +1 range upgrade of the Red Fort is still active even though the description doesn't list it.

**Comment by nobubblegums** [comment]
Probably mod conflict. Afaik VP red fort still provides & lists +1 range, could be that EE overwrites the description without taking away the range
