### ISSUE TITLE
AI accepts any peace deal

### ISSUE THREAD

**Issue by manubensio** [LoneGazebo/Community-Patch-DLL#8862]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.1.0, DX 10 & 11):_

2.0.3

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
AI will accept literally anything I add in a peace deal even if I have no war score and have taken no cities

_4. Steps to reproduce (optional):_
Opening the save and trying to make peace with Napoleon while adding ridiculous demands like capitulation and several cities

[save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8645096/save.zip)

**Comment by RecursiveVision** [comment]
Fixed in latest version
