### ISSUE TITLE
should upgrading a unit require full moves?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8863]
right now you can move units as long as they have moves left. always find it a bit gamey that you can save a fractional movement point and use that for upgrading. AI sure is not so smart ...

**Comment by LessRekkless** [comment]
This is a side effect of one of your AI changes. It used to require having no unspent attacks.

I have a PR that puts that functionality back.

**Comment by LessRekkless** [comment]
It is impossible for a human player to end their turn without promoting their units (unless the promotion saving option is enabled on the game creation screen).  The AI should be forced to do the same.

**Comment by LessRekkless** [comment]
Interesting. Is the AI not upgrading properly because of it?

**Comment by ilteroi** [comment]
seems they consider only units without any current mission for upgrades. that seems ... suboptimal. will fix

**Comment by RecursiveVision** [comment]
Code was last updated by Milae.

**Comment by LessRekkless** [comment]
#8821

**Comment by ilteroi** [comment]
why reopen?
