### ISSUE TITLE
incorrect message after spy event

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8864]
![image](https://user-images.githubusercontent.com/1358966/167268698-05794fda-31bb-44b1-a5c1-86fe2a8b760c.png)

* harar is owned by me (ethiopia). 
* i did not raid my own treasury.
* it's not a raid at all, i did not lose gold

**Comment by LoneGazebo** [comment]
All of that is changing on the next version.
