### ISSUE TITLE
third party peace brokering

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8865]
![image](https://user-images.githubusercontent.com/1358966/167271254-3aba95a2-a73d-44eb-9a6f-74d77c58d1a0.png)

i've just conquered a mayan city the turn before; pacal did not want to make peace.

in fact he's in a position to counterattack - then i get this very generous offer. seems weird.

any logs needed?

edit: refused the offer, got another one from askia. refused that as well and confirmed: pacal does not want to make peace with me directly.

**Comment by ilteroi** [comment]
went ahead and killed some more mayan units (same turn)

still no peace offer from pacal, but this from napoleon:

![image](https://user-images.githubusercontent.com/1358966/167271535-77e0f953-78e8-40f4-8d57-45707c08dc88.png)

unclear why he's offering much less now.

**Comment by RecursiveVision** [comment]
Intended. If the winner has 75+ warscore and accepts a peace bribe, the loser has no say in it.

**Comment by ilteroi** [comment]
rationale?

**Comment by RecursiveVision** [comment]
My best guess is that the third party broker can't ask a human loser if they want to make peace, so this puts AI and humans on equal footing.

**Comment by ilteroi** [comment]
ah. so that is vanilla logic? means it does not have to make sense :)

the broker knows if one party (always AI) in a war wants peace and then offers a peace deal to the other party (AI or human).

obviously if the third party is AI as well it's clear whether they will accept or not but the logic is the same?

**Comment by RecursiveVision** [comment]
@ilteroi
Vanilla logic:
- Can't broker peace if the loser is a human ("no way of knowing if a human wants peace")
- Can't broker peace if either the loser or the winner doesn't want peace

VP logic:
- Can't broker peace if the winner doesn't have at least 75 warscore
- Can't broker peace if the winner is peace blocked towards the loser in CvDiplomacyAI::IsPeaceBlocked()

**Comment by RecursiveVision** [comment]
What do you propose?

**Comment by ilteroi** [comment]
ok, so who invented this arbitrary threshold of 75 if it wasn't you?

anyway, my proposal is:

* can broker AI/AI peace only if both parties want it and can do the deal
* can broker AI/human peace if the AI side wants it, it is allowed and the human explicitly confirms
  * if the human is winning, this will meaning giving the human gold as part of the deal
  * if the human is losing, this means giving the AI gold. this might be difficult to do because the AI is not part of the deal ...

seems obvious, except for the last point. or am I missing something?

**Comment by RecursiveVision** [comment]
@ilteroi Could have been Gazebo? AFAIK it's been this way since before I started modding.

> can broker AI/human peace if the AI side wants it, it is allowed and the human explicitly confirms

That's the tricky part - how do we get confirmation from the human? Would need to make an entirely new dialogue option, so that'd be a feature request, unless you have a better idea.

Not opposed to it but it's not an easy fix.

**Comment by ilteroi** [comment]
why is that a new feature? the peace broker offers a deal to the human, they either accept or not. seems simple?

re: reproducability, it's weird, i get very different offers depending on the how often i've loaded the save and whether i automate the caravel without orders. highly suspicious.

**Comment by RecursiveVision** [comment]
> if the human is losing, this means giving the AI gold. this might be difficult to do because the AI is not part of the deal ...

I'm referring to this scenario specifically.

**Comment by RecursiveVision** [comment]
My understanding is that rather than getting confirmation from the human (which could be impossible in multiplayer, especially where multiple humans are involved), the 75 warscore threshold was chosen as a simple/consistent rule.

**Comment by ilteroi** [comment]
ok i get it ... but how common is the "human is losing with -75 warscore" scenario anyhow?

maybe not the best idea to design around a corner case that never really happens.

**Comment by RecursiveVision** [comment]
Probably fairly uncommon. But I do want to redesign the dialogue system and add a few messages, so this feature may be feasible.
