### ISSUE TITLE
Toolchip questions

### ISSUE THREAD

**Issue by 8h42** [LoneGazebo/Community-Patch-DLL#887]
1.Does the **Grand Temple** exert religious pressure?
![grand temple](https://cloud.githubusercontent.com/assets/11933188/11626875/92d9c034-9d29-11e5-9c28-a75eca26b738.png)

2.Does **Futurism** grant +250 tourism when a GP is born?
![futurism](https://cloud.githubusercontent.com/assets/11933188/11626882/a863afe6-9d29-11e5-9e95-1d8bf39bc553.png)

Active mods: 
- (1) Community Patch  (12-6b)
- (2) Community Balance Patch (12-6b)
- (3) CSD for CBP
- (4) Civ IV Diplomatic Features
- (5) More Luxuries
- (6) Community Balance Patch - Compatibility Files (EUI) (12-6b)
- EUI for CBP
- Ingame Editor

**Comment by LoneGazebo** [comment]
I'll look into these two.

**Comment by LoneGazebo** [comment]
Can't reproduce futurism quirk with khan.
G

**Comment by 8h42** [comment]
How about deleting codes of **Policy_TourismOnUnitCreation**?
I suppose the codes are no longer necessary.

cf.
(2) Community Balance Patch (12-6b)\Balance Changes\Ideologies\Autocracy\Autocracy.xml
Line: 4-36

**Comment by LoneGazebo** [comment]
That's weird - navigating to that folder does not show that element on my end (I actually delete that table outright elsewhere in the CBP). I wonder what's going on.

**Comment by 8h42** [comment]
I just re-downloaded CBP 11/20 and 12/6b.
Both of them contain Policy_TourismOnUnitCreation in the Autocracy.xml.
