### ISSUE TITLE
Encampment/Eki are not included global SQL UPDATEs

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#8870]
https://github.com/LoneGazebo/Community-Patch-DLL/blob/af97813822cf99fd0aedc8507167a870c5ab556c/(2)%20Vox%20Populi/Balance%20Changes/Leaders/GodsKings/GKLeaderChanges.sql#L660-L665
https://github.com/LoneGazebo/Community-Patch-DLL/blob/af97813822cf99fd0aedc8507167a870c5ab556c/(2)%20Vox%20Populi/Balance%20Changes/Leaders/BraveNew/BNWLeaderChanges.sql#L545-L550
For some reason, the following code runs **before** the above code, so removing forests/jungles during the construction of an Eki and Encampment gives the wrong production.
https://github.com/LoneGazebo/Community-Patch-DLL/blob/af97813822cf99fd0aedc8507167a870c5ab556c/(2)%20Vox%20Populi/Balance%20Changes/Terrain/FeatureChanges.sql#L94-L95

**Comment by LessRekkless** [comment]
The simplest fix would be changing the entries in BNWLeaderChanges.sql to 40, but it won't be forwards compatible if we ever decide that production for tree removal should be changed from 40.

**Comment by psparky** [comment]
I think the order is determined by the UpdateDatabase entries in the modinfo. The actual order can be seen in stopwatch.log (sorry if you already know all this).

Whether it would be safe to mess with the order is another matter. Probably the safest fix would be to create a new SQL that runs after the leader files and move the lines from FeatureChanges to that file.

It does beg the question, are there other cases where similar order-dependent entries actually load in the wrong order (probably yes!)

**Comment by RecursiveVision** [comment]
Messing with the file load order should be safe. It's the mod load order that can be inconsistent.

**Comment by LoneGazebo** [comment]
99% sure mods load alphabetically regardless of prereqs.

**Comment by psparky** [comment]
Well, the problem in this report occurs because there is a load-order dependency between files in the same mod, so the order can be important. 

As for the load order, when I asked in the general mod forum a few months ago, Mr Howard told me that the stopwatch log file was the definitive place to see what is actually happening, and that doesn't show anything happening alphabetically, either mods or files within mods. I think DCL priority might be affected by alphabetical order.

**Comment by LoneGazebo** [comment]
1% chance to be wrong here :)

**Comment by LessRekkless** [comment]
Looks like it doesn't just affect production, the req tech to remove the feature for the given improvement is also affected.

This is more problematic than the lost production.

**Comment by LessRekkless** [comment]
explore this further using [this post by poundjd](https://forums.civfanatics.com/threads/help-with-mod-load-order.631839/#post-15130253).
