### ISSUE TITLE
Can't assign Spies to Cities other than my own

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#8874]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.2.0, DX 10 & 11):_
2.2

_2. Mod list (if using Vox Populi only, leave blank):_
ENW
EAW
3/4 UC
Really Advanced Setup
Even More Resources

_3. Error description:_ 
The only Cities I can put my Spy in are my own.  The other players' Cities list is empty.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![20220514232228_1](https://user-images.githubusercontent.com/11430209/168455898-2edce0c9-da1d-4c4b-9401-7f8b00f47cc5.jpg)

**Comment by LoneGazebo** [comment]
Lua log?

**Comment by phantommaxwell** [comment]
[Lua.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8696953/Lua.zip)

**Comment by LoneGazebo** [comment]
[4256.046] Runtime Error: C:\Users\*\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Vox Populi\Core Files\CoreLua\EspionageOverview.lua:1290: Could not find player color at row -1
[4256.046] Runtime Error: Error loading C:\Users\*\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Vox Populi\Core Files\CoreLua\EspionageOverview.lua.

You've got an issue with a custom civ.

Greece/Klepth/Klepht
