### ISSUE TITLE
Categories aren't automatically expanded in trade screen

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8877]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.2.0, DX 10 & 11):_
2.2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Adds an extra click per trade, which can be annoying.
![image](https://user-images.githubusercontent.com/24713571/168474589-d771d202-d082-491b-bbce-9507e468fcd1.png)

**Comment by nobubblegums** [comment]
Hm I'm ok with this but I like my UI tidy.
