### ISSUE TITLE
Airstrike action for bombers is missing in 2.2

### ISSUE THREAD

**Issue by calloatti** [LoneGazebo/Community-Patch-DLL#8879]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.2.0, DX 10 & 11):_

VP 2.2 dx11

_2. Mod list (if using Vox Populi only, leave blank):_

VP, Ingame Editor, Really advanced setup

_3. Error description:_ 

Bombers do not have the airstrike option in the unit panel

_4. Steps to reproduce (optional):_

Create a new game, found city, add a bomber using IGE, select the bomber, check available actions for it.

4. Screenshots (optional):

VP 2.2:

![image](https://user-images.githubusercontent.com/12817862/168624829-443945e9-2528-42e2-b39d-37a2a303dd65.png)

Exact same setup but using VP 2.1.1:

![image](https://user-images.githubusercontent.com/12817862/168624959-56b9d19d-f661-41ed-8d56-d047a3c8549e.png)

**Comment by vetox20** [comment]
To add to this, I don't have logs (forgot to re-enable) but I experienced this with triplanes and bombers and just have the stock VP with no additional addons. No option to target and icon is missing and keyboard shortcut doesn't function.

**Comment by vegeta1k95** [comment]
I also have this bug

**Comment by nobubblegums** [comment]
@ilteroi Apparently this causes the problem in CvUnit::reset() `m_iNumAttacks = (m_iBaseCombat>0) ? 1 : 0;` reverting it to `m_iNumAttacks = 1;` fixed it for me. 
https://github.com/LoneGazebo/Community-Patch-DLL/commit/fcf8fe50e632ef3bfa509716d7e3e3917bdc1e6c

**Comment by ZojakOwnith** [comment]
how would a noob change this line?

**Comment by LessRekkless** [comment]
> how would a noob change this line?

https://forums.civfanatics.com/threads/how-to-compile-the-vox-populi-dll.665916/

You first need to be able to compile the DLL on your own.

**Comment by Padre19** [comment]
will there be a hotfix for this bug?

**Comment by matrixarg** [comment]
hotfix please
