### ISSUE TITLE
too many rivers

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#888]
i've seen it mentioned in the forum and also seen it myself, there are suddenly way more rivers on all kinds of maps.

i didn't do it, at least not intentionally ... any idea how this could happen?

**Comment by LoneGazebo** [comment]
Is it possible that a change to fertility in the DLL has caused maps to make more rivers to compensate? Or perhaps the changed pathfinder is caused otherwise-failed rivers to still spawn? I'm not sure how the mapgenerator works, at all.

**Comment by ilteroi** [comment]
interesting ideas .... 

but i think it started before the big rewrite. also, no interaction between pathfinder and map generator (except for assigning area IDs when it's done).

the fertility values also came after the rivers. furthermore, rivers don't influence fertility.

but it seems to affect multiple map scripts (at least pangea and fractal) which i guess nobody touched.

**Comment by LoneGazebo** [comment]
It is very odd. I have no explanation, and neither of us have messed with mapgen.

**Comment by LoneGazebo** [comment]
It's pretty clear that something is up. Floodplains and rivers are being reported en masse by players. I'm going to stick my nose into the mapgen and see what I can find. I'll report any relevant functions here.

**Comment by Heinous-Hat** [comment]
I've been trying to figure this out as well... didn't know it was common.

I generally use Haftetavenscrap's Tectonic script, which does not override AddRivers(). Communitas, however, does replace that function (normally called in MapGenerator.lua). Rolled a few maps in WB using Communitas and everything looks normal there concerning river frequency.

**Comment by LoneGazebo** [comment]
So here's the key area:

if(passCondition(plot)) then
	if (not Map.FindWater(plot, riverSourceRange, true)) then
		if (not Map.FindWater(plot, seaWaterRange, false)) then
			local inlandCorner = plot:GetInlandCorner();
			if(inlandCorner) then
			       DoRiver(inlandCorner);
                     	end
		end
	end
end

Passcondition() calls on a few defines that aren't used by the communitas lua:
PLOTS_PER_RIVER_EDGE
RIVER_SOURCE_MIN_RIVER_RANGE
RIVER_SOURCE_MIN_SEAWATER_RANGE

GetInlandCorner() could be the culprit.


There's also this:

function GetRiverValueAtPlot(plot)

	local numPlots = PlotTypes.NUM_PLOT_TYPES;
	local sum = (numPlots - plot:GetPlotType()) * 20;

	local numDirections = DirectionTypes.NUM_DIRECTION_TYPES;
	for direction = 0, numDirections - 1, 1 do

		local adjacentPlot = Map.PlotDirection(plot:GetX(), plot:GetY(), direction);

		if (adjacentPlot ~= nil) then
			sum = sum + (numPlots - adjacentPlot:GetPlotType());
		else
			sum = sum + (numPlots * 10);
		end
		
	end

	sum = sum + Map.Rand(10, "River Rand");

	return sum;
end


Given the reshaping of direction enums, could this be overvalued?

**Comment by Hokath** [comment]
Can confirm that, only playing Communitas, have not seen the rise of the river god.

**Comment by Mitchsp** [comment]
I play with custom script too (Planet Simulator) and haven't noticed river increase

**Comment by ilteroi** [comment]
this GetRiverValueAtPlot() function looks extremely fishy to me ... doing arithmetics with the plot type?

GetInlandCorner() i don't understand, but it hasn't been touched in ages. also the problem is that we have too many rivers in the interior of the continent, so coastal or not is probably irrelevant here.

**Comment by ilteroi** [comment]
maybe i did break it with the pathfinder after all?

		function(plot)
			local area = plot:Area();
			local plotsPerRiverEdge = GameDefines["PLOTS_PER_RIVER_EDGE"];
			return (plot:IsHills() or plot:IsMountain()) and (area:GetNumRiverEdges() <	((area:GetNumTiles() / plotsPerRiverEdge) + 1));
		end,
		
		function(plot)
			local area = plot:Area();
			local plotsPerRiverEdge = GameDefines["PLOTS_PER_RIVER_EDGE"];
			return (area:GetNumRiverEdges() < (area:GetNumTiles() / plotsPerRiverEdge) + 1);
		end

seems like these pass conditions need the number of plots in the area ... will check

**Comment by LoneGazebo** [comment]
I looked at that as well, but I didn't see anything particularly fishy. Granted, it was a cursory glance. The only thing I can think of is that the pathfinder model used to define the size of areas was messed up by virtue of the new pathfinder, thus perhaps area defines are not breaking properly (leading to larger-than-actual areas).

**Comment by Plockets** [comment]
Just FYI, my game with river spaghetti is on the 11-20 version, which is prior to pathfinder changes I think? Might ask in the forum thread for people that are seeing the extra rivers to report their versions to pinpoint a possible time of change?

**Comment by LoneGazebo** [comment]
Well, there have been multiple pathfinder changes, so it may not have been the latest one that caused it.

G

**Comment by ilteroi** [comment]
thanks for the hint - i thought so but i wasn't sure - anyway the area assignment seems to work fine

**Comment by LoneGazebo** [comment]
Perhaps I just need to try and port over the addrivers() function of the communitas map into the mapgenerator.lua and overwrite it?

G

**Comment by Heinous-Hat** [comment]
Hmm...that would have a major impact on the output of non-Communitas map scripts, no? For me, part of the appeal of using something like the Tectonic script is that you get those long, winding, continuous rivers from the vanilla method. It's one of Firaxis' best features, imho. 

The PerfectWorld function is quite interesting (and tunable), but after years of looking at all of the graphical mishaps that occur around lakes and such,  I find the original very refreshing.

**Comment by LoneGazebo** [comment]
Messing with the defines mentioned above makes some differences, so that's good.
PLOTS_PER_RIVER_EDGE - Starts at 12. This one doesn't seem to do much, actually. Bumping it up to 20-100 matters little.
RIVER_SOURCE_MIN_RIVER_RANGE - Starts at 4. Likewise seems to have minimal effect, which is interesting.
RIVER_SOURCE_MIN_SEAWATER_RANGE - Starts at 2. This one has an effect. Changing it up to 6-8 makes most of the map river-free, with 1-2 areas of intense river clumping.

So, unfortunately, it does seem like this 'works,' but not reliably, and clumping still happens.

I think the problem rests in these two areas, especially that first one:

function GetOppositeFlowDirection(dir)
	--DOCUMENT Method uses magic numbers...
	local numTypes = FlowDirectionTypes.NUM_FLOWDIRECTION_TYPES;
	return ((dir + 3) % numTypes);
end

function GetRiverValueAtPlot(plot)

	local numPlots = PlotTypes.NUM_PLOT_TYPES;
	local sum = (numPlots - plot:GetPlotType()) * 20;

	local numDirections = DirectionTypes.NUM_DIRECTION_TYPES;
	for direction = 0, numDirections - 1, 1 do

		local adjacentPlot = Map.PlotDirection(plot:GetX(), plot:GetY(), direction);

		if (adjacentPlot ~= nil) then
			sum = sum + (numPlots - adjacentPlot:GetPlotType());
		else
			sum = sum + (numPlots * 10);
		end
		
	end

	sum = sum + Map.Rand(10, "River Rand");

	return sum;
end

The 'magic numbers' element may problematically interact with the change in enums for flow directions.

**Comment by ilteroi** [comment]
ok guys i think i got it.

the problem is in Map.FindWater(), respectively in CvPlot::isFreshWater()

a few weeks ago i started caching this value for performance, but obviously during map generation that doesn't work. my bad, will fix

**Comment by LoneGazebo** [comment]
Huh, I looked at that value, ilteroi, and assumed that it was being set to true as the rivers were being created. Guess not.

**Comment by ilteroi** [comment]
fixed!
