### ISSUE TITLE
Wrong culture in city panel

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8883]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.2.0, DX 10 & 11):_
2.2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
[AutoSave_0009 BC-3640.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8702877/AutoSave_0009.BC-3640.zip)

![image](https://user-images.githubusercontent.com/24713571/168667748-d6d699da-44c1-4b86-ad01-b6203197a2b7.png)

**Comment by oalzubbi** [comment]
I saw this bug too. Theres also a bug with the city tooltip on bordergrowth where it will stay on "1 turn" indefinitely:

![image](https://user-images.githubusercontent.com/13261433/169163433-f5de6448-14a9-40dc-aba6-b36f99eae149.png)

**Comment by maarten99** [comment]
duplicate of #8875
