### ISSUE TITLE
cannot trade declaration of war on friend?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8887]
why is that? i mean, it should obviously give a major backstabbing penalty but why should it be forbidden?

also, direct war declaration is possible, so why the inconsistency?

edit: ok it seems the condition checks whether I have a DoF with a third player who has a DP with my desired victim. still, that's my problem, isn't it?

**Comment by RecursiveVision** [comment]
Hmm.

**Comment by RecursiveVision** [comment]
Reasoning was:
- To prevent humans (especially new players) from falling into traps and going to war with friends
- To prevent the AI from being stupid
- Offers to declare war on your friend are weird
- The offering civ won't remember that it bribed you and would apply a backstabbing penalty to you for accepting the deal that it gave you - often resulting in denouncement, etc.

**Comment by ilteroi** [comment]
well i buy the first. the second should not affect humans. third one is meh, fourth one i don't understand.

but yeah, it's fine, just the tooltip with the "diplomatic situation" is not very specific.

**Comment by RecursiveVision** [comment]
I'll work on making it more specific.
