### ISSUE TITLE
Rigging city state election doesn't give spy xp

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8888]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.2.0, DX 10 & 11):_
2.2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_

**Comment by maarten99** [comment]
Rigging the election succesfully still gives the spy a chance to level up

**Comment by RecursiveVision** [comment]
@LoneGazebo

**Comment by Azhral** [comment]
Can confirm the same issue in my game. Got plenty of extra spies with the Statecraft policy and they have been rigging elections for hundreds of turns but not one has levelled up.
