### ISSUE TITLE
Aesthetics Finisher

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#889]
Says doubles Tourism theming bonuses, but such things no longer exist.
Also the +x next to themed buildings does not related in any way to their bonus (not sure how you go about fixing this).

**Comment by LoneGazebo** [comment]
Eh?

**Comment by LoneGazebo** [comment]
There are still theming bonuses, and the theme bonus (culture, gold, etc.) is independent of this.
G

**Comment by Hokath** [comment]
but i'm right in thinking none give tourism? this aspect of the finisher doesn't do anything

**Comment by LoneGazebo** [comment]
They all give Tourism. I'm not sure what you mean. You get bonus tourism from theming great works, just like always.
G

**Comment by Hokath** [comment]
I think I've just got completely the wrong end of the stick on this one. Not sure how I didn't notice.

**Comment by LoneGazebo** [comment]
No worries!
