### ISSUE TITLE
Feature request: Make hero worship depend on the unit taking the city (land/naval) instead of landlocked or coastal city

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8892]
This would give the player a choice and/or not give admirals to players without a navy.
(This would also fix the issue with getting admiral on a sea-less map, since cities next to lakes also count as coastal cities.)

![image](https://user-images.githubusercontent.com/24713571/169592058-1af86a87-6387-4f1b-9516-0dd7a7c8ea28.png)

**Comment by axatin** [comment]
Balance change, should be discussed in congress.
