### ISSUE TITLE
Suggestion: ICBM Need Rework

### ISSUE THREAD

**Issue by Zanteogo** [LoneGazebo/Community-Patch-DLL#8895]
The current nuclear ICBM's are very under used considering how impactful they are in real life.

Suggestions:

Change the resource cost from 2 to 1. Uranium is super rare as it is. Requiring 2 is overkill.

The range is too short. On any of the larger maps this is really noticeable. 

The build time is way too long. Needs to be cut by 25%

**Comment by RecursiveVision** [comment]
Balance suggestions should go on CivFanatics.
