### ISSUE TITLE
Influence over CS does not decay for AI

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#8897]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.2.0, DX 10 & 11):_
2.2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Rome has been beating me constantly on influence so I decided to coup. Turns out the coup only raised mine a bit but did not lower his at all

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/13261433/169667866-ed27ff76-ce3b-4bf3-9851-f164285ccd68.png)

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8748291/QuickSave.zip)

**Comment by azum4roll** [comment]
Do they have a Sphere of Influence?

**Comment by oalzubbi** [comment]
No Sphere of Influence, Rome is actually sanctioned

**Comment by azum4roll** [comment]
Coups aren't a thing anymore, so I'm closing this.
