### ISSUE TITLE
Cultural Overview pupup with Influence notifications

### ISSUE THREAD

**Issue by Plockets** [LoneGazebo/Community-Patch-DLL#890]
Using 11-20 version with EUI, left clicking on the new influence notifications for "Great person born", "Trade route completed" etc, pops up the Culture Overview, in addition to cycling between the notifications. This is mostly just an irritation, since (at least in my case) that is not what you want or expect to happen, and just leads to closing the overview every time you click on the notification to cycle it.

**Comment by LoneGazebo** [comment]
That has been removed in the beta as well. :)

**Comment by Plockets** [comment]
Sounds like I need to finish this game up so I can update to the beta.. ;)

**Comment by LoneGazebo** [comment]
Heh, yep!

**Comment by Edaka** [comment]
Speaking of these, what was the cooldown for these notifications? 50 turns? 20? I think we could try reduce that a little, they are infrequent to the point of not being informative. I think 10 turns might work for starters.

**Comment by Edaka** [comment]
Oh, sorry, I thought about the notifications for changes of cultural influence for some reason, not historic moments. I'm talking about the former.
