### ISSUE TITLE
Feature request: allow building trade units even though no available trade routes (yet)

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8902]
Example why I want this: my neighbour declared war on me and pillaged my trade route, but now I can't even build caravans until we make peace again.
![image](https://user-images.githubusercontent.com/24713571/170547176-76dd62da-838f-409a-9e99-9c458798a835.png)

**Comment by DeAnnoCiv** [comment]
You often want to build a caravan for your second city as the settler is moving, right after it finishes, I don't think this would be a useless ability at all.

**Comment by azum4roll** [comment]
You should have settled your second city way before you have Trade...

**Comment by maarten99** [comment]
I would basically only want this feature for OCC and Venice, my playthrough of the Timur + OCC actually prompted this request, because they have buffs to traderoutes but I only had one neighbour (Denmark) who likes to declare war on me.

> You should have settled your second city way before you have Trade...

not if you're playing Venice or OCC...

Not having this feature isn't that big of a deal, it just would buff the weakest civ and help OCC, that is all.

**Comment by RecursiveVision** [comment]
Adding #8935 may help solve this.

**Comment by axatin** [comment]
This should be a congress proposal.
