### ISSUE TITLE
Can add anything to trade when AI is willing to sue for white peace

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8904]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.2.1, DX 10 & 11):_
&emsp; 2.1

_2. Mod list (if using Vox Populi only, leave blank):_
&emsp; Alternative Difficulty for VP (v 13)
&emsp; (over) More Unique Components for VP (v 77) _(3/4 UC)_
&emsp; The Timurids - 4UC (VP) (v 15)

_3. Error description:_ 

&emsp; Save files:
[Timur_0127 AD-0300.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8781631/Timur_0127.AD-0300.zip)

&emsp; Only 2 War Score:
![image](https://user-images.githubusercontent.com/24713571/170564029-60989443-0d60-43a0-86c1-a796ee5a6cc6.png)

&emsp; Wants white peace:
![image](https://user-images.githubusercontent.com/24713571/170564085-3072a0b8-7930-422f-94a3-dc096e835af0.png)

&emsp; I can add anything I want and accept:
![image](https://user-images.githubusercontent.com/24713571/170564174-4fe5ba55-45a1-4e77-ada2-70958a6c571b.png)

_4. Steps to reproduce (optional):_

Be at war until the AI is willing to peace out without any party paying (low warscore)

**Comment by maarten99** [comment]
I assumed he would accept, but he doesn't ...

![image](https://user-images.githubusercontent.com/24713571/170565934-8c45b5af-4913-443f-b4af-0f9488990cc0.png)

**Comment by RecursiveVision** [comment]
Fixed in 2.2
