### ISSUE TITLE
Inquisitors stationed in cities reduce missionary spread of own missionaries.

### ISSUE THREAD

**Issue by Azhral** [LoneGazebo/Community-Patch-DLL#8905]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.2.1, DX 10 & 11):_
2.2.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Having an Inquisitor stationed in your own city reduces the spread strength of all missionaries by 50%, including your own missionaries of the same religion.

_4. Steps to reproduce (optional):_
Spread your own religion to your own city with your own Inquisitor stationed inside.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Azhral** [comment]
Also it appears the description of Inquisitor behaviour is incorrect. It appears to apply the 50% religion spread malus to any adjacent missionary, regardless of if they are stationed inside a city or not.

**Comment by RecursiveVision** [comment]
eugh, I hate the religion code
