### ISSUE TITLE
pantheon belief yields rounding down improperly

### ISSUE THREAD

**Issue by reikken** [LoneGazebo/Community-Patch-DLL#8909]
The pantheon that gives +1 yields per 2 worked plains or grasslands will give no bonus if you have 1 worked plains and 1 worked grassland, even though that's 2. Ditto for the one that gives yields per 2 worked forest or jungle. 1 forest and 1 jungle gives nothing.

**Comment by bsesar** [comment]
I believe that is intended. Perhaps the description could be made clearer: per 2 worked plains or 2 grasslands.

**Comment by LessRekkless** [comment]
Currently intended.
