### ISSUE TITLE
Great Cothon can be build in non-coastal cities

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#891]
Not sure if it's intended to works like East Trading Company without requirements or an overlook.

**Comment by LoneGazebo** [comment]
It's not ideal, but yeah, it can be. On the off-chance that Dido ends up without coastal cities, I wanted the UB to still be build-able. I can change it to coastal-only, though.

**Comment by Mitchsp** [comment]
Well, in that pretty strange situation she's screwed anyway :) so I think we can change without problems for the sake of realism.
What about this? Change to coastal & change prerequisite from Market to Harbor, so she can build it in any coastal city just after investigating Currency.

**Comment by Der-Zorn-Gottes** [comment]
I wouldn`t change. The reasoning to give her at least something if there is no coast is sound - no need to completely neuter her there.

**Comment by Mitchsp** [comment]
But how justify that an artificial dock as a Cothon, and more even a specific one like Carthage's Great Cothon, exist inland?

**Comment by LoneGazebo** [comment]
shhhh....zeppelin dock? caravan dock? space dock? I'unno.
