### ISSUE TITLE
Global hegemony

### ISSUE THREAD

**Issue by michaelgo361** [LoneGazebo/Community-Patch-DLL#8910]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.2.1, DX 10 & 11):_
2.1.1

_2. Mod list (if using Vox Populi only, leave blank):_
3rd/4th unique components, Milae's maps

_3. Error description:_ 
Votes bought of vassals prior to global hegemony session don't count/fall under the table. 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LessRekkless** [comment]
![image](https://user-images.githubusercontent.com/34615525/171016391-c25efba5-87de-40c8-b5b5-62007ac9c30c.png)
It looks like, from your screenshot, there are at least 7 players left in the game (Benin, Germany, Arabia, Carthage, Zulu, Portugal, Denmark + ?), and yet only 3 players voted. I don't know which players were your vassals (I'm assuming only Zulu and Germany), but regardless, having only three players vote at all is quite weird.

You said in Discord that you had trade for votes from all of your vassals?

**Comment by RecursiveVision** [comment]
Vassals can't trade votes in 2.2
