### ISSUE TITLE
AI is too willing to convert their cities to a foreign religion

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8911]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.2.1, DX 10 & 11):_
&emsp; 2.1

_2. Mod list (if using Vox Populi only, leave blank):_
&emsp; Alternative Difficulty for VP (v 13)
&emsp; (over) More Unique Components for VP (v 77) _(3/4 UC)_
&emsp; The Timurids - 4UC (VP) (v 15)

_3. Error description:_ 

Sweden bought a missionary of a foreign religion (Buddism) after having only 1 of his 7 cities converted. He  then of course later used this missionaries to convert his cities (and bought some more) until all his cities were converted to Buddism. He even switched the city I converted to Hinduism to Buddism.

Usually (in my experience) (since 1.4 at least) the AI only convert their cities to a foreign religion if that religion is majority in their cities (and they didn't found their own). But in this game Sweden did so after only 1/7 cities.

On top of this, they are very hard to convert to a different religion because of this, they buy the missionaries of their majority and try to keep it that way, even though they are basically just throwing away faith they could have used in industrial era and after.

In my opinion they shouldn't even convert their own cities, like in pre-1.4 (? I think it was this patch).

![image](https://user-images.githubusercontent.com/24713571/171277055-f705080b-c122-4f7f-8380-d6c0953a8471.png)

![image](https://user-images.githubusercontent.com/24713571/171277174-a28eb540-b051-444f-85a2-e2dcb25f5588.png)

**Comment by ilteroi** [comment]
if all religions are founded and the AI does not have a state religion they will spread their favorite religion internally.

so in this case they liked the tenets of buddhism better than your hinduism. nothing personal ...

**Comment by maarten99** [comment]
> if all religions are founded and the AI does not have a state religion they will spread their favorite religion internally.
> 
> so in this case they liked the tenets of buddhism better than your hinduism. nothing personal ...

They bought a missionary as soon as a single one of their cities was converted, they never considered another religion.
By the time I converted 1 of his cities he already had 3 Cities converted + another missionary bought, which he used, after which he had 5/7 causing majority in his cities, then he flipped all his cities to his (self made) majority.
