### ISSUE TITLE
Update from VP 2.2 to 2.2.1 to rectify airplane bug - now game crashes on startup

### ISSUE THREAD

**Issue by IzzyWorks** [LoneGazebo/Community-Patch-DLL#8919]
DirectX11, VP 2.2.1

Mod List

Additional Civs
(civ) DMS' Civilizations - Corsica (Pasquale Paoli) for VP v10
(civ) Hoop Thrower's Tehuelche - Maria the Elder for VP v10
(civ) SMAN's Duchy of Brittany - Anne De Bretagne for VP  v8
(civ) GH's Ainu People - Shakushain for VP   v13
(civ) GH's Scotland - Robert I Bruce for VP  v12
(civ) GH's Louisiana - Joseph Beausoleil Broussard for VP v3  
(civ) Cambodian Civilization for VP v15
(civ) Colonialist Legacies' - Phillipine Republic for Vox Populi v12   
(civ) Colonialist Legacies' Inuit for VP v18
(civ) [BNW] Colonialist Legacies' Tlingit for VP v18
(civ) JFD's Civilizations - Japan (Tojo) for Vox Populi v9
(civ) JFD's Kingdom of Norway (Haakon IV) for VP v3
(civ) Kushan Empire for VP v2.3
(civ) MC and LITE's Nubia for VP v17
(civ) Pineappledan's Chola for Vox Populi v7

Game-changing mods
(game) Capture+++  v5
(game) More Unique Components for VP   v77
(units) Enhanced Naval Warfare for Vox Populi     v2.1
(units) Maritime Battles+ v20

Quality of life
UI - InfoAddict  v22
UI - Expanded Civilopedia Entries (Brave New World)   v40 
UI - Promotion Overhaul for VP v28
UI - List Enhancements for VP  v6.1
UI - Trade Opportunities for VP v12
UI - Improved City View with Condensed Help Texts (Vox Populi) (v. 12)
UI - Religion Spread (Vox Populi) (v. 2) 
UI - Show XP in Military Overview (v 2) 
UI - Religion Spread (Vox Populi) (v. 2) 

(map) Tectonic Map Script (v 4)

_3. Error description:_ 

Game crashes to desktop while waiting for the save file to load

[Dump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8837435/Dump.zip)

**Comment by IzzyWorks** [comment]
Going over the save file I realize that I had (9a) Enhanced Air Warfare 4VP (v 1.9) activated (which I hadn't intended to use)

despite this, the save files working with 2.2 so not sure if it's related. I tried loading it with both Air Warfare mod activated and deactivated with no improvement. The game still crashes out to windows on the load of the save file.

**Comment by RecursiveVision** [comment]
We're on 2.3 now.
