### ISSUE TITLE
IsFortification() doesn't return true for Barbarian Camps

### ISSUE THREAD

**Issue by nobubblegums** [LoneGazebo/Community-Patch-DLL#8922]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.3.1, DX 10 & 11):_
2.3.1
I noticed CvPlot::IsFortification() doesn't return true for barbarian encampments, is this intended? The code checks for NoFollowUp column in Improvements table. This also affects France UI Chateau, which isn't a Fort replacement but gives 50% defense modifier. Morocco's Kasbah (30% defense), Portugal's Feitoria (25%), Shoshone's Encampment (15%) are also affected. 

Code:
```
bool CvPlot::isFortification(TeamTypes eDefenderTeam) const
{
	if (isCity())
		return true;

#if defined(MOD_GLOBAL_NO_FOLLOWUP_FROM_CITIES)
	if (MOD_GLOBAL_NO_FOLLOWUP_FROM_CITIES)
	{
		// If the attacker is in a fort or citadel or other improvement with NoFollowUp, don't advance

		if (getTeam() == eDefenderTeam && !IsImprovementPillaged())
		{
			CvImprovementEntry* pImprovementInfo = GC.getImprovementInfo(getImprovementType());
			if (pImprovementInfo && pImprovementInfo->IsNoFollowUp())
				return true;
		}
	}
#endif

	return false;
}

```

**Edit:** I misread the column, Barb Camps have NoFollowUp set to 1. This is caused by plot:getTeam().

**Comment by ilteroi** [comment]
the whole thing is a mess. it's used for checking whether a unit advances after a melee kill or not, so it's not wrong. but the name is highly misleading ...

**Comment by LessRekkless** [comment]
you'd have to set the tile to be owned by the barbarian player, I guess?

**Comment by LessRekkless** [comment]
or if that's an issue,

 IsFortification() can also return true in the case that the tile is owned by _no-one_.

**Comment by ilteroi** [comment]
disagree. no owner, no maintenance, no effect.

not that this is a common case anyhow.

**Comment by LessRekkless** [comment]
VP Improvements don't cost maintenance, and even if they did, the player who built the improvement pays for the maintenance.
