### ISSUE TITLE
Cannot demand cities without an embassy. 

### ISSUE THREAD

**Issue by Laz0rG** [LoneGazebo/Community-Patch-DLL#8923]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.3.1, DX 10 & 11):_
2.3.1

_2. Mod list (if using Vox Populi only, leave blank):_
irrelevent

_3. Error description:_ 
You cannot demand cities from enemy civilizations without an embassy.
 Not sure if this intended, but I think it would make more sense to be able to do so.

**Comment by RecursiveVision** [comment]
So Firaxis didn't bother to make any LUA distinction between demands and normal deals, they just hid your trade window. Would need new code to add this ability.

Also demand code is fucked.

**Comment by RecursiveVision** [comment]
AI will always refuse to give cities anyway
