### ISSUE TITLE
OCC unable to progress turn after conquering city (choose city fate button doesn't work)

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8925]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.3.1, DX 10 & 11):_
&emsp; 2.3.1

_2. Mod list (if using Vox Populi only, leave blank):_
&emsp; [Alternative Difficulty for VP (v 13).zip](https://mega.nz/folder/RsVEADRY#NauL_a2fWwSAPGJSDM-Umw/file/NgUTSAwb)
&emsp; [(over) More Unique Components for VP (v 77) _(3/4 UC)_](
https://forums.civfanatics.com/resources/more-unique-components-for-vox-populi.26966/download?version=33703)

_3. Error description:_ 

[bugNapoleon_0108 BC-1300.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8854775/bugNapoleon_0108.BC-1300.zip)
[last 20.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8854773/last.20.zip)

Can't progress, the button doesn't work
![image](https://user-images.githubusercontent.com/24713571/172427331-6ee5e2f7-8745-4c28-afdf-b4b96b67927b.png)

Somehow the raze city button does work, but it bugs out the OCC capital
![image](https://user-images.githubusercontent.com/24713571/172428701-55b489f0-2159-42e5-8caa-8e65227855d6.png)

![image](https://user-images.githubusercontent.com/24713571/172428811-8762e224-60c6-41de-aa5e-831b94b897cf.png)

**Comment by RecursiveVision** [comment]
To fix in your game, replace (2) Vox Populi > Core Files > CoreLua > PuppetCityPopup.lua with this version:
[PuppetCityPopup.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8887012/PuppetCityPopup.zip)

**Comment by maarten99** [comment]
I tried the fix, I can confirm that it works!
![image](https://user-images.githubusercontent.com/24713571/174343580-932b334a-190f-44e5-98f7-17219b0ae879.png)
