### ISSUE TITLE
Honor policy in Authority Tree not providing units from cities that are already over size 10

### ISSUE THREAD

**Issue by Azhral** [LoneGazebo/Community-Patch-DLL#8927]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.3.1, DX 10 & 11):_
2.3.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
On a certain turn taking Honor as my final policy is not giving the free units. Using the in-game editor in later turns to remove and re-add the policy is spawning units (but too many as its spawning on both remove and re-add and also spawning units from cities that haven't reached size 10 yet). Unfortunately removing and re-adding the policy like this breaks completion of the Authority tree preventing the building of Alhambra. On the turn I've achieved the policy repeatedly adding and removing the Honor policy does nothing.

Temporary solution: Take Honor as final policy. Advance Turn. Remove Honor using IGE (which spawns the units when the policy is removed, but is also spawning from cities that aren't yet size 10). Grant a free policy through the IGE. Take Honor again with free policy (which doesn't trigger another spawn but does trigger the completion of the Authority tree). Interestingly for this to work you have to take Honor and advance turn before removing it. Reloading a save gave after taking Honor but before removing it does not trigger the unit spawns when it is removed / re-added.

_4. Steps to reproduce (optional):_
Playing as Russia. Policy Path - Authority Opener -> Tribute -> Imperium -> Dominance -> Discipline -> Tradition Opener -> Sovereignty -> Honor
Turn 315 on Marathon speed. Researched up to Theology & Chivalry.
I also noticed this in a previous game where the circumstances were pretty much the same.

Cities that reach size 10 after taking the policy appear to act normally.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Zuizgond** [comment]
Is your number of units above your military supply when taking Honor (including war weariness)?

**Comment by RecursiveVision** [comment]
Need a savegame one turn before you would receive a unit.

**Comment by Azhral** [comment]
> Is your number of units above your military supply when taking Honor (including war weariness)?

No, but the conscripted units are military-supply free so shouldn't be affected anyways.



> Need a savegame one turn before you would receive a unit. Otherwise, no fix.

Yeah having some trouble replicating it myself. I'll update this issue if it happens again and will provide a save that I can replicate the issue on.

**Comment by Zuizgond** [comment]
> No, but the conscripted units are military-supply free so shouldn't be affected anyways.

I know but I had the same issue and this was the reason.

**Comment by RecursiveVision** [comment]
I'll check to see if that's the issue.
