### ISSUE TITLE
Monastery EUI Visual Bug

### ISSUE THREAD

**Issue by Flamingcheesepie** [LoneGazebo/Community-Patch-DLL#8928]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.3.1, DX 10 & 11):_

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When EUI describes the Monastery building it often bugs out. This is likely due to the Monastery Description column being TXT_KEY_BUILDING_MONASTERY_DESC
instead of the expected 
TXT_KEY_BUILDING_MONASTERY
. The fix would then be to create a new string TXT_KEY_BUILDING_MONASTERY with text being Monastery and update the Description column in the Monastery building. 

		<Row Tag="TXT_KEY_BUILDING_MONASTERY ">
			<Text>Monastery</Text>
		</Row>

UPDATE Buildings
SET Description= 'TXT_KEY_BUILDING_MONASTERY'
WHERE Type = 'BUILDING_MONASTERY';

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Bizarre.
