### ISSUE TITLE
Cannot Assign Delegates During WC

### ISSUE THREAD

**Issue by vetox20** [LoneGazebo/Community-Patch-DLL#8930]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.3.1, DX 10 & 11):_
2.3.1

_2. Mod list (if using Vox Populi only, leave blank):_
Enhanced Naval Warfare for Vox v.2
Simplified Warfare for Vox v4

_3. Error description:_ 
After about 300-400 turns when voting comes up for WC, you cannot enter voting screen. Clearing cache does not help. Cant progress after that.

_4. Steps to reproduce (optional):_
Load save game, wait for vote. Try and click

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8864247/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Please include the complete list of your mods next time, 4UC counts.

**Comment by RecursiveVision** [comment]
Save file won't load.
