### ISSUE TITLE
"Event choice already active" prevents surveillance from being undertaken.

### ISSUE THREAD

**Issue by Laz0rG** [LoneGazebo/Community-Patch-DLL#8932]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.3.1, DX 10 & 11):_
2.3.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Trying to enact surveillance on a city (that I assume) is under surveillance from another spy prevents you from completing this action and therefore be rendered unable to use spies to survey for more than a single turn before having to send the spy away.

EDIT: a very poor description above on my part, rephrased here. whenever there are no spy actions available in a city (likely due to other spies currently enacting them all), you are unable to spy on a city for more than the single turn in which they have arrived in the city due to there being no available spy option.

**Comment by RecursiveVision** [comment]
Savegame needed.

**Comment by bukowa** [comment]
You mean this? Cannot take action and also cannot move spy, can't progress into next turn?
![aaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/38087302/176820355-4c98ed28-0f4f-4a6a-984d-e0475968664b.png)

**Comment by Laz0rG** [comment]
> You mean this? Cannot take action and also cannot move spy, can't progress into next turn? ![aaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/38087302/176820355-4c98ed28-0f4f-4a6a-984d-e0475968664b.png)
> 
> Oh but there's "move to hideout" and i can progress turn.

Yes, that exactly. No spy options being available prevents the spy being used at all. I have no idea why I didn't explain it better in the original post. 

As for the save game, I'm working on getting one now as all my old examples are heavily modded

**Comment by mjgood** [comment]
I had the same issue in my game. Here's a copy of my save

[2022.07.30_spy_bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9227896/2022.07.30_spy_bug.zip)
.
