### ISSUE TITLE
Unable to trade World Congress votes for technology

### ISSUE THREAD

**Issue by calloatti** [LoneGazebo/Community-Patch-DLL#8934]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.3.1, DX 10 & 11):_

2.3.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Unable to trade World Congress votes for technology. I cannot trade WC votes for a tech with a vassal. I do not remember is this was always the case but I think I have been able to do that in previous versions.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![image](https://user-images.githubusercontent.com/12817862/173229735-473b9918-d708-44e4-b5b0-f40873a57d29.png)

**Comment by RecursiveVision** [comment]
Intended. The AI could take your tech and then declare war on you, cancelling the vote commitment. This safeguard makes those kinds of trades impossible on both sides.
