### ISSUE TITLE
Question about AI.

### ISSUE THREAD

**Issue by iqddd** [LoneGazebo/Community-Patch-DLL#8939]
1. Mod version: Community Patch 2.3.1

2. Mod list (if using Vox Populi only, leave blank):

Purely out of curiosity: The description of the mod clarifies that the same AI is used for both Community Patch and Community Balance Overhaul.
Question: how is this possible, given such a big difference in gameplay?
ps: Is AI being tested only for CBO, or is CP too?

**Comment by ilteroi** [comment]
most of the balance changes are in fact database changes, but there are lots of conditionals in the code and no, this is not well tested.
