### ISSUE TITLE
movement on enemy roads

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#894]
right now i think you don't get a movement bonus on enemy roads.

the question is if it has to be that way. on the one hand, granting the movement bonus would open up new strategies for scorched earth tactics (i.e. pillaging your own improvements), but on the other hand the AI would need to be taught how to do it (don't know how hard that would be)

opinions? maybe call it a "roadmap feature"?

**Comment by LoneGazebo** [comment]
I mean, it makes sense that roads would be 'hostile' (i.e. local peoples would slow you down, your unfamiliarity with landscape, etc.). You might post something on the forum to see what people say.

**Comment by Edaka** [comment]
It's certainly designed not to provide movement bonus. I think Songhai's Mandekalu cavalry has a promotion that allows them to use enemy roads, so the ability is supposed to be unique.

**Comment by LoneGazebo** [comment]
I think we leave it as-is.
