### ISSUE TITLE
expansion warning

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8943]
just settled ohrid and got told off by montezuma.

![image](https://user-images.githubusercontent.com/1358966/174157180-ea389206-57c4-42ea-9bce-cb85fb46c4fb.png)

is that intended?

**Comment by RecursiveVision** [comment]
Pissy range is 5 to 7 tiles, depending on Boldness and UA...but it simply uses plotDistance and doesn't distinguish between land and water tiles because I don't know how to do that.

**Comment by ilteroi** [comment]
well you could check if they even have a city in the CvArea of the plot.

also the spot is closer to my city then to his. but i guess a psycho like montezuma would not care about such details :)

**Comment by RecursiveVision** [comment]
I forgot about CvArea, will add a check for this.
