### ISSUE TITLE
Unintended Balance Changes in Community Patch

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#8944]
Mod version 2.3.1, Community Patch only

When playing Community Patch only, the number of available spies is doubled on large maps. Additionally, when I surround an enemy city with my units, I get a 25% attack bonus under the tag "TXT_KEY_EUPANEL_CITY_BLOCKADED". Both of these are balance changes that should only be in VP.

**Comment by RecursiveVision** [comment]
Spies scaling with game speed is intended.

Turns out the blockade bonus in VP was never being applied this entire time! While fixing the text I also fixed this.
