### ISSUE TITLE
"Declare War" button unresponsive

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#8948]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.3.1, DX 10 & 11):_ 
2.3.1

_2. Mod list (if using Vox Populi only, leave blank):_ 
Really Advanced Setup

_3. Error description:_ 
The button "Declare War" is lit and clickable, but no confirmation window pops up. Tried it with all other players (except those I have Peace Agreement with) and it just doesn't work.

Savegame:
[Can't war.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8935487/Can.t.war.zip)

**Comment by RecursiveVision** [comment]
Need lua.log

**Comment by saamohod** [comment]
> Need lua.log.
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8938612/Logs.zip)

**Comment by RecursiveVision** [comment]
[114900.015] Runtime Error: C:\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Vox Populi\Core Files\CoreLua\DiploRelationships.lua:84: Could not find player color at row -1
[114900.046] Runtime Error: C:\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Vox Populi\Core Files\CoreLua\DiploRelationships.lua:84: Could not find player color at row -1
[114947.328] Runtime Error: C:\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Vox Populi\Core Files\CoreLua\DeclareWarPopup.lua:198: attempt to index local 'playerColor' (a nil value)

**Comment by RecursiveVision** [comment]
Seems to be an issue with retrieving the colors of a City-State. Not sure what's causing this.

@saamohod Are you playing with the 43 Civ DLL?

**Comment by saamohod** [comment]
> Seems to be an issue with retrieving the colors of a City-State. Not sure what's causing this.
> 
> @saamohod Are you playing with the 43 Civ DLL?

I don't. I do use Meaningful City State Colors (https://steamcommunity.com/sharedfiles/filedetails/?id=399911115), Better Civilization Colors(https://steamcommunity.com/sharedfiles/filedetails/?id=404022144) and Colored Religions(https://steamcommunity.com/sharedfiles/filedetails/?id=78597473) graphical mods. But the issue still persists when I turn them off and leave only vanilla VP with Really Advanced Setup

**Comment by RecursiveVision** [comment]
@saamohod If you start a new game without the color mods, does the issue persist?

**Comment by saamohod** [comment]
> @saamohod If you start a new game without the color mods, does the issue persist?

No. Started two games for testing purposes. One with graphical mods, and one vanilla with Really Advanced Setup. Both cases work without the bug, but it may emerge later because this bug happened somewhere mid-game.

**Comment by RecursiveVision** [comment]
Likely a mod conflict with the color mods.

**Comment by RecursiveVision** [comment]
The issue seems to be caused when the player you're DoWing has City-State allies.
