### ISSUE TITLE
Pastures missing Ideology Yield

### ISSUE THREAD

**Issue by Flamingcheesepie** [LoneGazebo/Community-Patch-DLL#8949]
All other improvements get one of the yields from Ideologies - food from Freedom, production from Order, science from Autocracy. Pastures don't, and should probably get added into the 4 food from Civil Society in Freedom. 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Balance changes should be discussed on the forum.
