### ISSUE TITLE
air strikes don't seem to work

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#895]
you can select a target but nothing happens afterward. that might be the reason why guided missiles have been piling up in AI cities all the while?

note:
- rebasing is possible
- nuke attacks work

i just tried debugging it and it seems the attack is a normal move order, but in the end CvUnit::UnitAttack() fails (and that code hasn't been touched at all).

**Comment by LoneGazebo** [comment]
Where does it return false in unitattack()? Did you walk it through the function? There's a pathfinder call in it.

G

**Comment by ilteroi** [comment]
well - no pathfinder call for air units, that might be part of the problem. but it has always been like that, can't see how that ever worked

**Comment by Heinous-Hat** [comment]
In my game, I've seen the AI attack with guided missiles. But the rest is as you describe.

**Comment by ilteroi** [comment]
which version was that?

**Comment by LoneGazebo** [comment]
I see where the air strike is breaking:


bool CvUnit::UnitAttack(int iX, int iY, int iFlags, int iSteps)

setup at breakpoint at the top and follow it down (once you've queued up an attack with a guided missile.

Breaks here:

if(kPathNodeArray.size() > 1)
	{
		// Previous node is the same plot as the one before the destination (attack point)?
		// Prevents unit from stopping while adjacent to the enemy, but on top of another unit so it has to move to another tile before it can attack
		const CvPathNode& kNode = kPathNodeArray[1];
		if(kNode.m_iX == getX() && kNode.m_iY == getY())
		{
			// The path may not be all the way to the destination, it may be only to the unit's turn limit, so check against the final destination
			const CvPathNode& kDestNode = kPathNodeArray[0];
			if (kDestNode.m_iX == iX && kDestNode.m_iY == iY)
			{
				bAdjacent = true;
			}
		}
	}

	if(bAdjacent)
	{

The unit isn't being considered 'adjacent' when attacking, so an attack is not being reported as made, thus it doesn't follow through.

G

**Comment by ilteroi** [comment]
correct. the question is, why is that so? i have an idea how to fix it, but that's probably not the way it used to work. we'll see.

**Comment by LoneGazebo** [comment]
You can push, yep. I guess the question is, if the unit is 'dying' on impact, why does it even need to check adjacency? We know it can get there, so why not add an exclusion for 'instant death' units to ignore that entirely?

**Comment by ilteroi** [comment]
it affects also "normal" bombers. but yeah, i simply made it (bAdjacent || getDomainType()==DOMAIN_AIR". seems to work

**Comment by LoneGazebo** [comment]
Makes sense to me.

**Comment by ilteroi** [comment]
ok - pushed.

i might have to rewrite the rebasing again, with the larger rebase radius it's a bit inefficient because it only looks at the closest four cities. works but takes more turns than necessary

**Comment by LoneGazebo** [comment]
What if we just open up rebasing to any owned city, regardless of distance? You lose a whole turn in the process anyways.

**Comment by LoneGazebo** [comment]
We've got a small issue - ice seems to be passable for all units.

**Comment by ilteroi** [comment]
yeah. that sounds good, was a strange mechanic anyways.

**Comment by ilteroi** [comment]
ok rebasing takes a shortcut now if possible.

re: ice, i think there was a bug in UpdateImpassable. should be good now

**Comment by ilteroi** [comment]
aaaaand pushed

**Comment by LoneGazebo** [comment]
Awesome. Did you sync up first, or do I have to resync again? :)

Aside from what I have on the current beta 'bugs to look out for' list, are there any other outstanding/known bugs I should alert people to?
G

**Comment by ilteroi** [comment]
all merged
no known bugs at the moment

**Comment by LoneGazebo** [comment]
Quill and Funak have confirmed that ranged units can shoot over mountains. Also, city tiles on mountains make them no longer count as mountains for the purpose of improvement adjacency (i.e. the terrace farm).

If we're serious about keeping the Inca with mountain cities, we need to look into a city-graphic element for them (perhaps a modified Machu) as a base. Also, they should probably get a defensive and production bonus (as if they're on hills).

**Comment by ilteroi** [comment]
d'oh. there was a glitch in the automatic merge and i was so happy it worked without errors, i didn't even test it :)

there is already 35% defense bonus in place (25 from mountain terrain, 10 from plot type i guess).

tried to add the same yields as for hills but failed (see TerrainChanges.xml)

don't have any idea how to give different graphics to cities ...

**Comment by LoneGazebo** [comment]
I'll start to work on the graphical stuff. There's a few other quirks we need to work on (garrison caching is currently breaking garrison-related policies), but nothing that's insanely miserable. So that's nice?
