### ISSUE TITLE
Boat crossing a river in a canal expends all movement points

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8965]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.4.3, DX 10 & 11):_
2.3.1

_2. Mod list (if using Vox Populi only, leave blank):_
[Alternative Difficulty for VP (v 13).zip](https://mega.nz/folder/RsVEADRY#NauL_a2fWwSAPGJSDM-Umw/file/NgUTSAwb)

_3. Error description:_ 

Frigate moves from city to citadel and loses all movement points:
![image](https://user-images.githubusercontent.com/24713571/175749652-f43ed00d-892f-4a8e-b899-a799ab998be4.png)

![image](https://user-images.githubusercontent.com/24713571/175749708-91f0ecee-5f67-4da1-b83b-162860f482a4.png)

save file: [converted to shinto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8983380/converted.to.shinto.zip)

**Comment by ilteroi** [comment]
consider it a sea lock

**Comment by saamohod** [comment]
Yes, the citadel-canals behave weird now
![20220626195319_1](https://user-images.githubusercontent.com/16341598/175970753-bab40647-4919-4927-8bf7-ea7cafacaeb8.jpg)
