### ISSUE TITLE
Vassals are too willing to DoF their master

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#8967]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.4.3, DX 10 & 11):_
2.3.1

_2. Mod list (if using Vox Populi only, leave blank):_
[Alternative Difficulty for VP (v 13).zip](https://mega.nz/folder/RsVEADRY#NauL_a2fWwSAPGJSDM-Umw/file/NgUTSAwb)

_3. Error description:_ 

Japan captures 2 cities of Brazil including their capital, he capitulates and then they become friends the turn after.
saves: [too friendly.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8983558/too.friendly.zip)

T234 capitulation:
![image](https://user-images.githubusercontent.com/24713571/175750269-53bd3ce6-4314-4f37-8afc-6c1bd3765450.png)

T235 DoF:
![image](https://user-images.githubusercontent.com/24713571/175750319-a807c185-5986-4f25-8f0d-314e6940ccb7.png)

**Comment by RecursiveVision** [comment]
Intended.
