### ISSUE TITLE
English Crown Jewels is missing background

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#8970]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.4.3, DX 10 & 11):_
2.4.4

_3. Error description:_ 
The artifact in England's White Tower UNW is supposed to have a image background
![image](https://user-images.githubusercontent.com/34615525/175793136-5632c292-e0bc-4d04-b537-865243db0374.png)
![image](https://user-images.githubusercontent.com/34615525/175793157-a7b71f01-deba-4730-91a8-aec3f007b831.png)
![image](https://user-images.githubusercontent.com/34615525/175793244-8a2ec6c0-1378-46ae-a52b-bc965a145417.png)
It is not showing up in-game, but the dds file does exist in _(2) Vox Populi\Art_.  It looks like the frame has resized itself to properly fit the image even though it hasn't loaded. 

Note that having both an image and quote is possible; you can see it in the Great Works of Writing

**Comment by nobubblegums** [comment]
Probably a compression issue, is this dx9 or dx11?

**Comment by psparky** [comment]
If the X and Y dimensions are not multiples of 4, try clipping it slightly so they are.

**Comment by nobubblegums** [comment]
Should be fixed with https://github.com/LoneGazebo/Community-Patch-DLL/commit/851fb41610968a563b684e791a5cd2aad98c38d6
