### ISSUE TITLE
(CP) Spies make no progress stealing techs

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#8972]
Mod version 2.4.4, CP only

Spies in enemy cities don't get any Spy Power at the end of a turn, so they can't make any progress in stealing technologies. This applies to human and AI players, and makes stealing techs impossible of course.

![Screenshot (66)](https://user-images.githubusercontent.com/95587882/175814948-a6c6f16c-ed12-4369-8256-e48289499725.png)
Next Turn:
![Screenshot (67)](https://user-images.githubusercontent.com/95587882/175814951-10bcd51c-f68a-4b38-80be-6444b58ddaff.png)

A much less severe issue: The calculations of Spy Power don't match up, 100 base and two times 25% bonus don't add up to 210.

**Comment by RecursiveVision** [comment]
@LoneGazebo
