### ISSUE TITLE
AI doesn't build proper road connection between cities

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#8973]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.4.3, DX 10 & 11):_
2.4.4

_2. Mod list (if using Vox Populi only, leave blank):_
Really Advanced Setup

_3. Error description:_ 
I happened in previous version, it's still here.

Often AI doesn't finish connecting its cities to the road network, leaving those cities disconnected. In my savegame the Polish cities of Poznan and Lodz (just captured by me) aren't connected to the road network. Those are long established core cities and it's modern era.

[Gustavus Adolphus_0313 AD-1886.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/8990745/Gustavus.Adolphus_0313.AD-1886.zip)

**Comment by axatin** [comment]
These two are not the same. Community Patch is a mod mainly to improve AI performance, but it doesn't change the gameplay mechanics. Vox Populi is built on top of the Community Patch and includes all the gameplay changes. And this github is used for both.
