### ISSUE TITLE
blockades

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#8974]
just pushed a small update regarding blockaded plots (f52bb87288476f55c85804fb5a2ceca08c0c66bf) but i need some feedback ...

1. the blockaded status is now indicated in the UI (city banner and city screen)
2. the status is updated on turn end and unit kill events (not on unit move or war declaration right now)
3. if a "forced worked plot" is blockaded, the forced flag will be kept and it will be worked again asap
4. owned units can lift blockades on adjacent plots (except garrisons). not sure about this, may be too complex and requires a mid-turn status updates.
5. a city will re-allocate the plots it is working before the turn; so there is no need for micromanagement (this is not new)

**Comment by RecursiveVision** [comment]
@ilteroi I think an exception for garrisons is going to create confusion for players - it would likely be better for performance as well to only have units un-blockade the tile they're defending.

**Comment by ilteroi** [comment]
yeah, i'll remove the blockade-lifting part, that simplifies everything.
