### ISSUE TITLE
(For balparmak) Adding an explanation for inability to gift a unit to a CS

### ISSUE THREAD

**Issue by Flamingcheesepie** [LoneGazebo/Community-Patch-DLL#8977]
Add a tooltip of some sort explaining why a unit can't be gifted to a CS - 5 turn cooldown, supply limit, etc. 

Possibly take on azum4roll's suggestion of being allowed to gift if at cap, immediately disbanding the CS' worst unit (which could be your gift) - would be beyond the first question, so only if feasible.

**Comment by RecursiveVision** [comment]
Agreed.
