### ISSUE TITLE
AI troops did not defend their cities in always war game

### ISSUE THREAD

**Issue by 4CV** [LoneGazebo/Community-Patch-DLL#8979]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.4.3, DX 10 & 11):_
2.3.1

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ AI troops ran away from their city under attack, or lined up behind the city instead of defending it.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.
1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu): Savegames deleted, sorry...

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![ZURICH](https://user-images.githubusercontent.com/25335477/176058656-0fc4cf05-02ba-4cb7-b19d-c47ff3493581.jpg)
![Aarhus](https://user-images.githubusercontent.com/25335477/176058660-489c27e9-2113-4cc5-b668-a9d9631e779c.jpg)
![Mombasa](https://user-images.githubusercontent.com/25335477/176058662-bfb2ad17-f796-4a82-b45f-d1147b1fc0b0.jpg)

**Comment by ilteroi** [comment]
there are zero occurences of GAMEOPTION_ALWAYS_WAR in tactical AI

**Comment by RecursiveVision** [comment]
@ilteroi Requires the Really Advanced Setup mod.
