### ISSUE TITLE
Units with `UNITAI_MISSILE_CARRIER_SEA` are not considered as options for rebase of Missiles.

### ISSUE THREAD

**Issue by vegeta1k95** [LoneGazebo/Community-Patch-DLL#8981]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.4.3, DX 10 & 11):_
2.4.4
_2. Mod list (if using Vox Populi only, leave blank):_
_3. Error description:_ 

If you look at the [code](https://github.com/LoneGazebo/Community-Patch-DLL/blob/master/CvGameCoreDLL_Expansion2/CvHomelandAI.cpp) inside `void CvHomelandAI::ExecuteAircraftMoves()`, you'll these that the check for potential bases `vPotentialBases` to which rebase air units consists only of cities and carriers (`UNITAI_CARRIER_SEA`). 

This means, Missile Cruisers and Nuclear Submarines (which have `UNITAI_MISSILE_CARRIER_SEA`) are not considered as possible locations to rebase Guided/Nuclear Missiles.

This also applies to the function `bool CvUnit::EmergencyRebase()`.

Is it intentional? I think in my games I really haven't seen AI carrying missiles in navy units.

(Actually, the type `UNITAI_MISSILE_CARRIER_SEA` is not really used anywhere in the AI logic at all.)

**Suggestion:** Add a check, something like: 
```
...
else if (pLoopUnit->getUnitInfo().GetUnitAIType(UNITAI_MISSILE_CARRIER_SEA)) 
{
   // ... determine score of a plot and add to possible bases ...
}
...
```

**Comment by ilteroi** [comment]
these UNITAI types are quite problematic ... i check for domainCargo()==DOMAIN_AIR now, let's see how that goes

**Comment by vegeta1k95** [comment]
@ilteroi 
`UNITAI_ATTACK_SEA` is just the **default** UNITAI type for cruiser. You can check over array of all UNITAI types unit posseses with:
`pUnit->getUnitInfo().GetUnitAIType( ... type here ... )`
It returns bool, true if is of type, false if not of type.

But anyway, checking `domainCargo() == DOMAIN_AIR` should be fine as well.
Do you want me to do pull request? Or are you going to do commit yourself?

**Comment by ilteroi** [comment]
it's done
