### ISSUE TITLE
Inconsistent labeling of great diplomat

### ISSUE THREAD

**Issue by hyuckkim** [LoneGazebo/Community-Patch-DLL#8984]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.4.3, DX 10 & 11):_
2.4.4, DX 10 & 11. with eui.

_2. Mod list (if using Vox Populi only, leave blank):_
[events and decision](https://forums.civfanatics.com/threads/sukritacts-events-and-decisions.528549/)
[even more resources](https://forums.civfanatics.com/resources/even-more-resources-for-vox-populi.28019/) with edit modinfo
[my vox populi translate mod](https://github.com/hyuckkim/vp_kr) - only xml and sql.
But it doesn't matter.  

_3. Error description:_ 
It is not an error.

Only a great diplomat has a unit type after yellow unit name (Great Diplomat Units)  
But not another great people.

_4. Steps to reproduce (optional):_
I got _Glory of God_.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![image](https://user-images.githubusercontent.com/53367179/177003902-48fa4a81-1675-45d9-84e9-0557f5d41eb9.png)
![image](https://user-images.githubusercontent.com/53367179/177003904-804c63cc-587f-497b-bd17-ef8f9dc3ff78.png)

>

**Comment by RecursiveVision** [comment]
@hyuckkim Logs needed.

**Comment by hyuckkim** [comment]
The title was provocative, but what I was trying to say was just a question. I'm sorry.
 
So for example, in my language, the unit production window looks like this.
![image](https://user-images.githubusercontent.com/53367179/177271422-4a0482a5-4c69-4540-b753-629ca12abdb2.png)

But in a great diplomat, I see a unit type. (Great Diplomat Units)
![image](https://user-images.githubusercontent.com/53367179/177271315-608742e4-1146-4274-870c-225469d9c65e.png)

This message was not found even when I searched the entire Vox populi project. Is there any way to localize this text? Or can you erase this text?

Log is : I checked all the logs, but there were no logs related to this. I guess it would be a little terrible if the log was written every time you touched the mouse.

Thanks for your kind response and passionate vp team.
