### ISSUE TITLE
Barbarian ships. Barbarian activity.

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#899]
Posted by SgtCiv: 
'1) The first is probably the most important. I have not seen any barbarian ships and that is even if the camp is located on an island.

2) Inland camps will spawn at most 3 barbs, but they will all hang out at or around the camp. Mostly I see the camp with two barbs stationed inside the camp and one that will wander no more then one movement distance from the camp and then right back towards the camp the very next move. '

Haven't played enough to confirm 1, but I've definitely seen the barbarian behaviour described in 2. Barbarians seem to be a little inactive lately.

**Comment by LoneGazebo** [comment]
Hmm...I'm going to page ilteroi, as he's been in the tactical AI as of late.

**Comment by Mitchsp** [comment]
In my experience and with the mapscript I play (Planet Simulator), barbarian ship appear always, but maybe a bit late, around turn 100.

**Comment by ilteroi** [comment]
re: no ships - that seems to be due to the fact that e.g. galleys have a prerequisite tech which the barbarians don't have (anymore?). don't know why. @G: any recent changes there?

re: inactivity - difficult. they are guarding the camp as it is typically the closest tactical target. i'll disable that target type for the barbarians, that should make them swarm a bit more, but leave camps more vulnerable.

**Comment by LoneGazebo** [comment]
I'll take a look at prereq tech for barbs. I also need to figure out why CS armies virtually disappear by the mid-game.

**Comment by ilteroi** [comment]
nice. btw, just pushed another update

**Comment by LoneGazebo** [comment]
Sounds good. When you get a chance, let me know the parameters of the new mountain stuff you've changed/edited so I can have it in the changelog.

**Comment by ilteroi** [comment]
fixed, closing the issue

**Comment by ilteroi** [comment]
ah, sorry, the tech prereq thing is still open

**Comment by LoneGazebo** [comment]
I fixed it.
