### ISSUE TITLE
Suggestion: Let AI evacuate Great Works from about-to-be-captured cities

### ISSUE THREAD

**Issue by vegeta1k95** [LoneGazebo/Community-Patch-DLL#8991]
Basically title: if AI's city is about to be captured, make him evacuate all Great Works from that city to other cities (if there are places to put them). 
Maybe also add condition that the city should not be blockaded.

Supposedly this would help AI still be in a race for cultural victory if crippled by warmongering civs.

**Comment by nobubblegums** [comment]
I agree. A human player would never, ever let great works be lost that way, so neither should the AI.
