### ISSUE TITLE
Capitulation Deal Logic Suggestion

### ISSUE THREAD

**Issue by usadefcon1** [LoneGazebo/Community-Patch-DLL#8992]
The AI should be unwilling to Capitulate if their enemy is at war with someone else at the same time.

Background: I was at war with Theodora and she was willing to Capitulate. Maria declared war on me so I decided to end my war with Theodora. She Capitulated and now she was at war with Maria too.

This wasn't a good decision on her part. Once Maria joined the war against me, Theodora should have refused any Capitulation deal as it just involves more war for her.

Peace would have been smart, but not Capitulation.

**Comment by ridjack** [comment]
I don't agree with this. If someone is at the point where the capitulation option is available, they are unable to defend themselves against the threat that's already present. If Theodora had refused to capitulate in that circumstance, most likely I would have used other units to fend off Maria while I continued deleting Theodora from the game. At least with the other war, she isn't the main focus and she'll have an ally that's stronger than her.

**Comment by RecursiveVision** [comment]
I agree with ridjack.
