### ISSUE TITLE
Rounding error with monopolies

### ISSUE THREAD

**Issue by APLion-nsk** [LoneGazebo/Community-Patch-DLL#8996]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.4.3, DX 10 & 11):_
2.4.4

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi
(over) More Unique Components for VP (v 77) (1)
Better Lakes for Vox Populi (v 2.3)
Ingame Editor (v 39)
Kushan Empire for VP (v 2.3)
Reforestation (v 9)

_3. Error description:_ 
As it can be seen in the screenshot I control more than half of the oil (156/306 = 0,5098...), but do not have the corresponding monopoly (tiles with oil can be seen on screen and they do not have +2 science on them).

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![20220708060327_1](https://user-images.githubusercontent.com/72704750/177927435-155e1cd4-4724-4afa-94d1-d7686aa6dd50.jpg)

**Comment by psparky** [comment]
Pretty much everything in Civ/VP is rounded down. You need at least 51% to get the global monopoly and more than the current holder of the monopoly to take it from them. The total only counts those on the map, not any added by buildings, events, etc, so it's possible for two civs to have > 50%.
