### ISSUE TITLE
Archaeological Dig On GP Improvement

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#900]
Request for a new feature - two possible options, depending on which is possible.

#1 - Archaeological Digs don't replace GP tile Improvements.

#2 - Digs work normally, but the "automate worker" function on an Archaeologist won't send it to tear up your GP tile Improvements.

Thanks if possible, and thanks if not.  :)
-Gidoza

**Comment by LoneGazebo** [comment]
I'll take a look.

**Comment by LoneGazebo** [comment]
Went for #2.
