### ISSUE TITLE
non-sensical war declarations

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#9003]
in the situation below, rome declared war on all three neighbors successively:

079, Rome, , ***** WAR DECLARATION! *****, France
097, Rome, , ***** WAR DECLARATION! *****, Korea
114, Rome, , ***** WAR DECLARATION! *****, Siam

![image](https://user-images.githubusercontent.com/1358966/178571200-cb34db5b-76a7-4431-a859-8dbeacd215f5.png)

the result is that everybody hates them and they achieve nothing at all.

don't know what a good guidelines is here but it seems smarter to concentrate on one opponent at a time.

**Comment by RecursiveVision** [comment]
Could have been bribed?

**Comment by ilteroi** [comment]
nope. and even with a bribe it's stupid

**Comment by RecursiveVision** [comment]
I'll investigate

**Comment by RecursiveVision** [comment]
Should be better
