### ISSUE TITLE
city healing

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#9004]
```
		int iHitsHealed = /*20 in CP, 8 in VP*/ GD_INT_GET(CITY_HIT_POINTS_HEALED_PER_TURN);
```

is this new? only 8 hp healed per turn?

this seems weird ... my city has 500 hitpoints with barracks only? it takes ages to heal!

so my proposal would be: no healing when fully blockaded, low healing when any plot is blockaded, fast healing (like 40 hp/turn!) when no enemy around.

**Comment by ilteroi** [comment]
guess i should not have stopped reading after the first line :)

anyhow it's close to what i proposed. but i'd still switch to "any plot blockaded" instead of "enemy within x plots" because performance, information leakage and clear UI feedback

**Comment by RecursiveVision** [comment]
Agreed, and implemented.
