### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by besset** [LoneGazebo/Community-Patch-DLL#9008]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.4.3, DX 10 & 11):_
2.2

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Random CTD

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"): 
[All Files.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9106651/All.Files.zip)

3. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu): File provided above

4. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V): File provided above

5. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Old version, probably fixed
