### ISSUE TITLE
On Currency

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#901]
As previously discussed, I have a few requests concerning Prosperity (which adds a Currency):

**player:SetCurrency(ID)** -- simple integer
**player:GetCurrency()** -- returns the above
**GameEvents.PlayerAdoptsCurrency(playerID, newCurrencyID, oldCurrencyID)** -- oldCurrencyID would be nil if it's for the first time. This triggers whenever SetCurrency is invoked.
**player:HasCurrency()** -- a streamlined player:GetCurrency() > -1 or ~= nil (whichever works)
**player:SetCurrencyName(textKey)** -- same as with the Legislature Name from Sovereignty, storing a text key value to be retrieved from the one below.
**player:GetCurrencyName()** 

Hopefully these are simple enough, but let me know otherwise. Thanks!

**Comment by LoneGazebo** [comment]
Yep, can do. I'll try to get this into the next beta.

**Comment by LoneGazebo** [comment]
Done and done. Will link you a test version later today.

**Comment by JFDaly** [comment]
I noticed you mentioned you added Currency support in the 10/12 beta. None of the methods above appear to work, so perhaps you meant something else? Or is there an option I need to turn on (I've enabled 'BALANCE_CORE_JFD')?

**Comment by LoneGazebo** [comment]
Ah, you know what? I pushed the lua through, but didn't method it (that's the last thing I usually do). I'll get on it later today, is a real quick element.

G

**Comment by JFDaly** [comment]
Awesome, thanks

**Comment by LoneGazebo** [comment]
Alright, done, will upload test here shortly.

**Comment by LoneGazebo** [comment]
https://mega.nz/#!2JlB1JjQ!ThVXeYtWaO3vFbkXvL2cdz3KpPK9pgCkxEsRZkNwIAY

Here we go.

**Comment by LoneGazebo** [comment]
It is 'unoptimized' (i.e. not compiled with compression), so it may be a little less snappy than usual. Should work just fine.

**Comment by JFDaly** [comment]
Awesome. Only thing is the oldCurrencyID for the PlayerAdoptsCurrency event doesn't return nil or an integer, but instead a string of numbers. On the other hand, I can use player:GetCurrency() because the event triggers before the currency is changed, so it's no big deal. Thanks!

**Comment by LoneGazebo** [comment]
Glad it works, odd that the event is messed up. Here's the formatting:
GAMEEVENTINVOKE_HOOK(GAMEEVENT_PlayerAdoptsCurrency, GetID(), iValue, m_iJFDCurrency);

I wonder if the last number (the 'old' value) isn't cached? Is it a MAX_INT value?
