### ISSUE TITLE
Can't build military ships in a coastal city

### ISSUE THREAD

**Issue by rahenry** [LoneGazebo/Community-Patch-DLL#9012]
Version 2.5

Problem: Lisbon can't build military ships (triremes, dromons). Other cities can.
![ss](https://user-images.githubusercontent.com/11766125/179439201-3b885f4e-a4d2-4af9-8e1c-6b8db57836ba.png)

Mod list
![_ss1](https://user-images.githubusercontent.com/11766125/179439059-f7a55e98-7a77-4593-8a77-efdd6b260501.png)

Save
[save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9129183/save.zip)

Adding more coast with Ingame Editor "fixed" the problem. Just removing the lake was not enough however.
![ss](https://user-images.githubusercontent.com/11766125/179439676-ad4a5746-fb19-461f-b335-9415bc80f77b.png)

**Comment by axatin** [comment]
Intentional for now. In Version 2.5 it was changed that ships can't be built in lakes anymore. There are still some discussions about this change, however, since it doesn't take into account the possibility to connect lakes to the ocean using canals.

**Comment by rahenry** [comment]
It's next to the coast/ocean to the North-West

**Comment by axatin** [comment]
Oh, you're right, sorry. I will look into it.

**Comment by artemigkh** [comment]
If it helps, here's another save with the problem:
![image](https://user-images.githubusercontent.com/8049171/179992509-7b78a53c-2bda-46f8-8d52-2ef50939f44c.png)

Mod list:
![image](https://user-images.githubusercontent.com/8049171/179992992-2c3742d3-2847-41c0-b6e1-a27a92db66c2.png)

Save:
[Rostov-Cannot-Build-Trireme.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9150213/Rostov-Cannot-Build-Trireme.zip)

**Comment by ilteroi** [comment]
no idea but anyway i'm on it, there are other places as well where areas are checked instead of landmasses

**Comment by LessRekkless** [comment]
I believe @ilteroi fixed this with 9ced0d17608465e958bb3580151f3e95e7f64838.
