### ISSUE TITLE
Locking Tiles Bug

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#9013]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):
Version 2.5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
When I try to lock a tile doesn't lock, only locks sometimes. Sometimes I saw that it locked a tile but unlocked another previously locked tile.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/179469413-a220fbab-b772-495e-bf57-0132470d21aa.jpg)
![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/179469416-9498629d-ed28-4b33-a894-ddbfc6bcd535.jpg)
![Civ5Screen0002](https://user-images.githubusercontent.com/49090452/179469403-771f53b7-d71f-4d44-9492-ba7d1f31b6af.jpg)
![Civ5Screen0004](https://user-images.githubusercontent.com/49090452/179469410-4ab3cde1-5240-495e-96d8-53463a0f46cd.jpg)

**Comment by nobubblegums** [comment]
@ilteroi Could this be related to recent governor update changes for blockade stuff? I've had similar reports on this thread, but I'm pretty sure my changes don't affect city tiles https://forums.civfanatics.com/threads/need-feedback-on-lock-specialist-feature.677748/page-2#post-16307619

**Comment by DemaciaMaggotPie** [comment]
Can confirm. My workaround is that I fully reset the Governor (by clicking on the city center) then lock the tiles one by one.

**Comment by Aqinu** [comment]
The tile near city should be locked, but doenst work, I cant make it lock for any tile, I unlock the tile from first screenshot, the one south (atoll) and try to lock it on any other empy tiles but is appears only unlocked. To replicate, click in the city to reset deafault tile positions, lock all tiles to those that are autamatically chosen by the governor than start unlocking one locked tile and try to lock another empty tile.

**Comment by azum4roll** [comment]
I think this is a very old bug that happens if you leave no tile unlocked.

**Comment by maarten99** [comment]
It definitely happens way more often in 2.5 that one citizen unlocks itself, I'm not sure what causes it.
