### ISSUE TITLE
Enemy Tile Blocking and Friendly Units

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#9016]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_
2.5

While in a war and an enemy unit blocks a city from working any tiles adjacent it. You can start working the tile again if one of **your** units is on that tile

However, if an **allied or neutral** unit is on that tile, you still cannot work the tile, but they are preventing you from putting your own units there.

I think allied/friendly/neutral units should also prevent the tile from being blocked from working by enemy units. At the very least, **units that are also at war with your enemy** should stop the tile block.

**Comment by LessRekkless** [comment]
![image](https://user-images.githubusercontent.com/34615525/179543149-e6cefac0-9f12-45d7-9f0c-8660eff7dc63.png)
For example, Arabia is Ur's ally here.

**Comment by RecursiveVision** [comment]
Agreed.

**Comment by ilteroi** [comment]
ok, neutral units now lift blockades. blue helmets to the rescue!

@RecursiveVision : also changed the city healing logic a bit, check it out
