### ISSUE TITLE
strange AI embark behavior

### ISSUE THREAD

**Issue by reikken** [LoneGazebo/Community-Patch-DLL#9018]
AI is repeatedly embarking into a bad spot for seemingly no reason.

![image](https://cdn.discordapp.com/attachments/721543887285387314/999024014070652958/unknown.png)
The archer was of course immediately killed.

Not shown: A few turns before this, the nearest hoplite was standing on the hill academy at about 80% health and embarked into that spot.

Next turn, 
![image](https://user-images.githubusercontent.com/17669897/179831495-d1f4ff61-405a-4afb-8280-347c7fbe3809.png)
nothing of note, but...

Next turn
![image](https://user-images.githubusercontent.com/17669897/179831986-0552efc9-c13e-4683-83c7-cc1215c6dce2.png)
Another embark. This one at least has amphibious, though, so a little less strange.

Next turn
![image](https://user-images.githubusercontent.com/17669897/179832349-6a9a8dc4-57f9-446e-a8e6-8d6a9368ee62.png)
It stays to attack the spearman (and then gets killed)

Next turn
![image](https://user-images.githubusercontent.com/17669897/179833020-5f083061-5037-4b68-aea1-619b3b3ea96a.png)
The surviving hoplite.... embarks.

Vox Populi 2.5
only other mods are Reforestation and a very small personal sql tweak

full view of the surroundings
![image](https://user-images.githubusercontent.com/17669897/179833542-29a0bd5b-8837-4ed6-a950-378f8a7cc0c5.png)

**Comment by ilteroi** [comment]
duplicate #9199
