### ISSUE TITLE
Deals including techs won't go through sometimes

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#902]
OP by Gidoza: 

'A bug I encounter pretty often at the moment is that I strike a deal with an AI, and the deal simply doesn't happen. Usually, this involves a strategic resource.

EXAMPLE: Trading with Russia, I wanted 8 Coal, and I was offering Tea, the tech Penicillin, and 11 GPT. She accepted. But I have no Coal, and she doesn't have Penicillin. Nothing changed. Tried again and again - same thing, and it happens in other situations as well.

EDIT: Actually, I think it has to do with Tech Brokering. Even if the "No Tech Brokering" option is checked, you're still given the option to trade techs that you/they haven't actually researched. When you accept the trade, nothing happens. I tested this by trying to trade the same tech from several different Civs - and it only works on some of them, presumably the ones who actually researched the tech in question (whereas in the above scenario, I'm pretty sure I didn't research the tech in question, but honestly I don't remember ). '

So yeah, it sounds like techs that are researched by neither parties can somehow be added into the trade window, which causes deals not to go through. Maybe it's that, maybe it's not (:

**Comment by LoneGazebo** [comment]
Sounds legitimate. I'll get on it.

**Comment by Edaka** [comment]
Gidoza mentioned that he also gets this issue with trades that do not involve techs every now and then, it's just more frequent with tech trades.

**Comment by LoneGazebo** [comment]
There's a bug I've already fixed in which a deal could be agreed upon, but not completed, as the deal would 'fail' in the acceptance stage (when it should have failed in the bargaining stage).

**Comment by Edaka** [comment]
Cool! I reckon that should probably fix the most of the problem.
