### ISSUE TITLE
bad layout

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#9021]
@nobubblegums : can you do something about the layout here?

![image](https://user-images.githubusercontent.com/1358966/180054049-950b7bd5-7833-4dcd-9809-6097cd34777f.png)

i'm not even sure whether tips are needed in that screen at all ... anyway the current layout does not look very polished.

**Comment by ilteroi** [comment]
same here, the tip is not aligned with the text above

![image](https://user-images.githubusercontent.com/1358966/180069115-723919ab-8771-4f9e-b10a-e299344d4933.png)

**Comment by nobubblegums** [comment]
Mod configuration is the longest loading screen in game, so I think it's a good place for tips. I thought about perfectly aligning the tip text there, but that would create much dead space at the sides, not sure if that would be any better. I'll try that sometime though. Do you have anything else in mind about the layout? 
The second one should've been aligned though, will check it.

**Comment by ilteroi** [comment]
![image](https://user-images.githubusercontent.com/1358966/180711215-db751b88-e742-4a05-bd90-d73fb140c01a.png)

please fix - i guess the popup size should adapt to the text length?

**Comment by nobubblegums** [comment]
yeah that looked nasty. I implemented autoscaling for those, will fix alignment in the leaderscreen soon. Still not sure if the non-alignment on the mod configuration tooltip is an issue, and if so, what can be done about that. Like this layout below doesn't look problematic to me
         |         ----      |
         |    ----------  |
in fact, I find it much better than the below, which we would get from alignment
         |    ----    |
         |    ------  |
         |    ------  |
