### ISSUE TITLE
[OCC] Turn 67 CTD 

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#9028]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_
2.5

_2. Mod list (if using Vox Populi only, leave blank):_
Alternative difficulty v13

_3. Error description:_ 
Crashes to desktop during city state's turn, right before my turn starts.

_4. Steps to reproduce (optional):_

Press next turn in save:  [crashKamehameha_0067 BC-1320.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9162637/crashKamehameha_0067.BC-1320.zip)
(Accept Sweden's friend request, not sure if that matters)

Autosaves: [auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9162649/auto.zip)

**Comment by axatin** [comment]
This is caused by bug #8850 (here with the City State of Bogota)
