### ISSUE TITLE
Overblown CS resistance against tributes

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#903]
![cs tribute1](https://cloud.githubusercontent.com/assets/12978597/11703292/a791c238-9ee6-11e5-8e98-37841c0ae86e.jpg)
![cs tribute 2](https://cloud.githubusercontent.com/assets/12978597/11703294/aaed780a-9ee6-11e5-9d9d-8890e27c2aa5.jpg)
If I can do math, I say the numbers don't add up right (:

**Comment by Edaka** [comment]
Alright, 7 turns later (on turn 32) all the numbers restored back to normal. I don't know what was causing such astronomic numbers before, though.

**Comment by LoneGazebo** [comment]
Hmm...I'll take a look. I know there's a cooldown for all civs when any civ tributes a CS, but that has a TT entry. May also be a cached value not coming online properly.

**Comment by LoneGazebo** [comment]
Also, Edaka, I've added you as a collaborator on the github project, which means you should have authority to open/close requests and label them as you see fit, in the event you need/desire to.

**Comment by Edaka** [comment]
Oh! I'm most certainly honored! I don't suppose I can actually be of much help with those powers, but I thank you for your trust.

**Comment by LoneGazebo** [comment]
No worries. Just in the event that you need them.
