### ISSUE TITLE
Denmark Viking promotion not applying on pillaged tiles

### ISSUE THREAD

**Issue by 1andUnly** [LoneGazebo/Community-Patch-DLL#9034]
_1._2.5b

_2. Mod list (if using Vox Populi only, leave blank):_3/4UC

_3. Error description:_Viking promotion not applying 25% CS boost while on enemy pillaged tiles

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by LessRekkless** [comment]
It's applied to base combat strength, so you won't see it in the Enemy Unit Panel.
Combat Strength 8
![image](https://user-images.githubusercontent.com/34615525/180591142-2b5ec5b3-b671-47d4-9392-ee9c8aab3025.png)
Combat Strength 10 (+25%)
![image](https://user-images.githubusercontent.com/34615525/180591144-d34d6289-e2c8-4c91-8941-07241e564b1d.png)
