### ISSUE TITLE
Crash to desktop post 100ish turns

### ISSUE THREAD

**Issue by AyoOgunsola** [LoneGazebo/Community-Patch-DLL#9036]
1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_
2.50

2. Mod list (if using Vox Populi only, leave blank):_

-  Gedemon's YnAEMP
- Wonder Race
- Faerun Map
- Really Advanced Setup
- Fortress Borders - Outputs
- Civilization Selection Bonus tooltips
- Colored Religions
- Reseed!
- Buildings - Upgrade System
- Strange Religions 
- Germany (Hilter)
- 

3. Error description:_ 
Pressing next turn immediately crashes to desktop. Had this happen on this save, and another upon hitting turn 100. 

4. Steps to reproduce (optional):_
Load Quick Save, hit next turn.
[Civ stuff.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9174622/Civ.stuff.zip)

Supporting information:
Last night after encountering another save with this issue, I deleted a duplicate mod and tried fast turn skipping to 100 where I originally got the crash. Game continued fine, but so did this one up until 135. 
All files contained within zip.

**Comment by RecursiveVision** [comment]
Reliable loading of savegames and several crashes have been fixed for 2.6, closing all CTD reports from prior versions.
