### ISSUE TITLE
"Move your troops or declare war" is being way over-sensitive.

### ISSUE THREAD

**Issue by ridjack** [LoneGazebo/Community-Patch-DLL#9037]
Latest version.

This is the latest example, prompting me to make a bug report; I've shown other recent examples in the Discord.

https://i.imgur.com/nHNKTJh.jpeg

https://i.imgur.com/ZpHLX1K.jpeg

Two units should not trigger this, no matter how strong they are.

**Comment by maarten99** [comment]
I can attest to this, it's way overzealous in 2.5
2 spearmen not even in his vision caused him to ask
![image](https://user-images.githubusercontent.com/24713571/181917041-b7fc1fc7-d3a8-4ac1-abeb-e768a993d7d6.png)

**Comment by ilteroi** [comment]
can confirm, i got complaints after making peace?

![image](https://user-images.githubusercontent.com/1358966/182777560-000a1d57-faab-4431-8054-a4a6d75b33cb.png)

i did found texcoco during the war as well though, so unclear if sigtuna or texcoco is the trigger

![image](https://user-images.githubusercontent.com/1358966/182777771-dd109677-01e6-4ecf-a00b-cd48b8b9a9a1.png)

**Comment by RecursiveVision** [comment]
@ilteroi Should be Texcoco, and that's intended (conquered cities don't count, only settled ones).

@ridjack Should be fixed.
