### ISSUE TITLE
Investment request

### ISSUE THREAD

**Issue by Plockets** [LoneGazebo/Community-Patch-DLL#904]
I have a feeling this must be one of those things that isn't as easy to do as it should be, or it would have been done already, but it would be nice if there was a purchase button on items in the queue. It is awkward to have to remove items from the queue if you want to buy them, then add them back to the queue, and finally move them back to the top. I am using the EUI version, btw.

**Comment by TechpriestEnginseer** [comment]
non-EUI doesn't have this problem.

**Comment by LoneGazebo** [comment]
It's an EUI thing unfortunately.
