### ISSUE TITLE
Unit crossing Lake Victoria not in boats/embarked state

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#9042]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_
2.5, dx11

_2. Mod list (if using Vox Populi only, leave blank):_
alt diff

_3. Error description:_ 
![image](https://user-images.githubusercontent.com/24713571/180666661-461a953e-16ed-4577-9ee7-8a9a1e8297ba.png)

**Comment by azum4roll** [comment]
Lake Victoria is a mountain plot with no elevation, so it can be walked through as if it's a mountain.
