### ISSUE TITLE
AI pushing their general without any other units

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#9043]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_
2.5

_2. Mod list (if using Vox Populi only, leave blank):_
Alternative Difficulty for VP (v 13)

_3. Error description:_ 
autosave before and after: [auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9176786/auto.zip)

![image](https://user-images.githubusercontent.com/24713571/180667145-a96c9256-749c-4e31-8881-da962fea5cbb.png)

**Comment by LessRekkless** [comment]
This happens similarly with Admirals
![image](https://user-images.githubusercontent.com/34615525/180899958-5bb532fb-6fa9-46a0-98f7-40a1029baa0c.png)

**Comment by vegeta1k95** [comment]
I experienced this too. AI pushes GG/GA/Workers straight into my armies without any military units.
