### ISSUE TITLE
Empty offer on renew deal

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#9044]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_
Version 2.5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/180753465-ede62d47-9e23-4482-b13f-c3e20ead3343.jpg)

**Comment by RecursiveVision** [comment]
Useless without a savegame.

**Comment by Aqinu** [comment]
I looked at some save files around that time, this is from an accepted request of money, and I don't know if the AI should ask about a renewal when the deal expires. Your call.

**Comment by RecursiveVision** [comment]
Ah. Probably shouldn't.

**Comment by RecursiveVision** [comment]
I think deals should be two-sided in order to be renewed, but I'm not familiar enough with the code to do it myself.

**Comment by axatin** [comment]
The AI shouldn't ask to renew any gifts. If you encounter it again, reopen the issue and attach a save game.
