### ISSUE TITLE
Labels initialized using format strings cause errors

### ISSUE THREAD

**Issue by IanE9** [LoneGazebo/Community-Patch-DLL#9046]
I've made a commit to fix this with my pull request to add clang support (IanE9@61d7d74) but I thought it would be a good idea to document this in some capacity.

When a label is initially set to a string value that contains formatting rules, an error is logged in `Localization.log`. These errors are normally benign on Windows, but on Linux `FString::FormatV` has been compiled in such a way that bad format specifiers lead to crashing. This is specifically a problem for @Hello71's Linux port as it was crashing due to `TXT_KEY_VO_TAX_RATE` being used as the initial value for a label and when an error is logged the message gets fed through `FString::FormatV`.

I'd guess that this was only causing crashes because `TXT_KEY_VO_TAX_RATE` is defined as `Tax Rate: {1_Num}%` and the trailing `%` present in the string is an incomplete formatting specifier. @Hello71 suggested that it could be that `FString::FormatV` contains undefined behavior in the presence of bad formatting specifiers which VC90 conveniently handles "gracefully", while Clang chooses to insert a `ud2` instruction and jump to it. This could also just be caused by differences in the STL implementations on each platform as `FString::FormatV` makes several calls to STL formatting functions.

**Comment by LessRekkless** [comment]
```xml
<Row Tag="TXT_KEY_VO_TAX_RATE">
  <Text>Tax Rate: {1_Num}%</Text>
</Row>
```
This throws errors?

Or is it this, from `VassalageOverview.xml` (the UI creation):
```xml
<Label String="TXT_KEY_VO_TAX_RATE" Font="TwCenMT20" Anchor="L,T" Offset="4,8" ID="TaxSliderValue"/>
```

**Comment by LessRekkless** [comment]
Maybe there's something with:
```xml
<Label String="TXT_KEY_VO_TAX_RATE" Font="TwCenMT20" Anchor="L,T" Offset="4,8" ID="TaxSliderValue"/>
<Label String="TXT_KEY_VO_TAX_RATE" Font="TwCenMT20" Anchor="C,T" Offset="4,8" ID="LabelMasterTaxRate"/>
```
found in `VassalageOverview.xml`?

**Comment by IanE9** [comment]
> There are a massive number of text strings that end with `%`; just look inside CoreText_en_US.xml for examples (eg. TXT_KEY_FOODMOD_YIELD_GOLDEN_AGE_POLICIES, TXT_KEY_YIELD_GREAT_WORK_MODIFIER, etc). Do these all throw errors?

The problem isn't just really _just_ that they have `%`, it's that they have `%` and are being used as an initial value for a label (as you've noted in your second comment). When a label gets given a value from an XML file that value is presumably fed through the localization functions which look to populate any arguments as well. Since there is no way to provide arguments for the value from an XML file an error gets logged, and it's when that error is logged that the `%` causes problems.

**Comment by Hello71** [comment]
on windows, the following errors are output to localization.log:

```
[74.296] WRN: A resource bundle lookup returned a result from the root locale (not an error).
[217.015] ERR: Missing argument 1. (Vassal For {1_NumTurns} Turns (Turn {2_TurnStarted}))
[217.015] ERR: Failed to evaluate parameter 1. Vassal For {1_NumTurns} Turns (Turn {2_TurnStarted})
[217.015] ERR: Missing argument 1. (Tax Rate: {1_Num})
[217.015] ERR: Failed to evaluate parameter 1. Tax Rate: {1_Num}
[217.015] ERR: Missing argument 1. (Tax Rate: {1_Num})
[217.015] ERR: Failed to evaluate parameter 1. Tax Rate: {1_Num}
```

see #2154, #2156, #5019. on windows the % is simply omitted from the error message, but on linux it causes civ 5 to crash. IMO, two fixes should be applied:

1. VP shouldn't cause this error to be emitted; i.e. it should not use strings taking arguments in contexts where no arguments are provided
2. Civ 5 shouldn't use the string directly as a format string, as it may contain unexpected format sequences. (actually, now that I think about it, this could be leveraged for code execution, but that's basically "through the hatch already" territory)

strictly speaking, either of these alone would fix the issue. however, it is more correct to apply both fixes. additionally, fix 2 is much harder to apply, whereas fix 1 is trivial.

**Comment by azum4roll** [comment]
Fix 1 was applied some time ago. There's no .xml file using those text keys anymore.

No idea if fix 2 is even possible with the code we have access to.
