### ISSUE TITLE
Level up happens 1 turn late

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#9049]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_
2.5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

Unit has enough xp to level up, but actually leveling up/choosing promotion happens the turn after.
It used to be that leveling up and picking a promotion happened on the same turn of getting enough xp to level up.
![image](https://user-images.githubusercontent.com/24713571/181089807-1a7b17b1-5566-4c97-9fef-96b6bb0027af.png)

**Comment by LessRekkless** [comment]
Intentional. You can't level a unit up if it doesn't have any attacks left.

**Comment by maarten99** [comment]
Sure, just making sure it was intentional, it's not that big of a deal either way.
