### ISSUE TITLE
WorldBuilder gone wonky

### ISSUE THREAD

**Issue by Heinous-Hat** [LoneGazebo/Community-Patch-DLL#905]
The latest iterations of Community Patch aren't interacting well with WorldBuilder. Not sure when it started... I noticed a problem while investigating the recent river spam issue. Currently using the 12/6 beta.

The symptoms...

If I start WB with CP enabled (alone) and generate a map using any script, it may or may not crash the civ5 engine depending on the state of the database. If it's fresh, I can typically generate a single map successfully. Subsequent attempts will crash the civ5 process, though, and will continue to do so unless the database is deleted prior to re-launching WB.

With CP inactive, there's no problem churning out successive maps. I don't recall exactly when this began, but I'll try digging up some older builds to compare.

**Comment by LoneGazebo** [comment]
Hmm...I'll try to reproduce.

**Comment by Heinous-Hat** [comment]
This looks likes it's fixed in the latest build (12/10 beta).

Just read the resolution to the river spam issue... side effect, maybe?

**Comment by LoneGazebo** [comment]
That was the issue. Sorry meant to confirm here, but yes, overflow (ha) of fresh water booleans killed the world builder.

**Comment by Heinous-Hat** [comment]
You don't hear that phrase much anymore ;)

**Comment by LoneGazebo** [comment]
Heh. Glad it is working! Closing issue.
