### ISSUE TITLE
Can't progress to the next turn

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#9051]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_
2.5

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
The next turn button doesn't do anything.

Save game (on turn 261 is the problem, I also put the one before it, I have multiple save game files if you want):
[save game.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9197462/save.game.zip)

Required mods: 
[required mods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9197438/required.mods.zip)

Logs:
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9197439/Logs.zip)

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by Aqinu** [comment]
I found the problem, in the center south of the map I have one automated Trireme that has one move left and if i try to select it, it doesn't work, it works only from military overview panel. If I cancel the automation I can progress to the next turn.

**Comment by RecursiveVision** [comment]
@ilteroi

**Comment by RecursiveVision** [comment]
#8826
