### ISSUE TITLE
Oda Nobunaga leader flavor updates Napoleon instead

### ISSUE THREAD

**Issue by Hokiefan00** [LoneGazebo/Community-Patch-DLL#9060]
The LeaderFlavors.sql file looks to be setting the 'FLAVOR_CULTURE'  to 6 for Napoleon when it should be doing so for Oda instead. It updates Napolean's 'FLAVOR_CULTURE'  10 lines up to 8.

![image](https://user-images.githubusercontent.com/84920557/181801286-409ce2c1-c1d1-44c7-b0ee-9f1b9b508795.png)

**Comment by nobubblegums** [comment]
Nice find, thanks 👍
