### ISSUE TITLE
Units start turn in their "Do Nothing" action

### ISSUE THREAD

**Issue by jdoug312** [LoneGazebo/Community-Patch-DLL#9070]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_

2.5_farmbeta (https://drive.google.com/file/d/1QzSIT0nwS04wFeQbOyY1JzoMUuEXnWg9/view)

_2. Mod list (if using Vox Populi only, leave blank):_
VP
Dolen2's diversity
ENW
EAW
4UC

_3. Error description:_ 
Each turn, units are in their *spacebar* action by default, meaning that I won't be prompted if a unit hasn't moved. This makes unit management a nightmare because if I forget about a unit who's run out of orders, they'll just sit there for possibly many turns.

_4. Steps to reproduce (optional):_

-Use this version https://drive.google.com/file/d/1QzSIT0nwS04wFeQbOyY1JzoMUuEXnWg9/view

-found capital, then choose a tech and something for your capital to produce. 

-Next turn will pop up without your units having moved, with no prompting, camera scrolling, etc.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
@nobubblegums Did you set the default mission to Sleep or Do Nothing when a turn is force ended? They are different.

**Comment by nobubblegums** [comment]
It's do nothing but I've been overzealous on fixing that next-turn blocked thing, pushing the fix now.
