### ISSUE TITLE
CTD when loading save from the MOD menu.

### ISSUE THREAD

**Issue by abmpicoli** [LoneGazebo/Community-Patch-DLL#9071]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_
CvDllContext.cpp[154]: CvDllGameContext::InitializeSingleton - Community Patch v108 (PNM v51+) - Startup (Version 108 - Build Jul 14 2022 13:42:32)
CvDllContext.cpp[155]: CvDllGameContext::InitializeSingleton - Supporting 43 major civilizations

_2. Mod list (if using Vox Populi only, leave blank):_
THe only other mod is the "Barbarians - Unlimited XP" from the steam workshop https://steamcommunity.com/sharedfiles/filedetails/?id=82186217

_3. Error description:_ the application is failing to load a save using the same mods.

_4. Steps to reproduce (optional):_

I try to load the save and it CTD . I'm using the MOD menu, for loading the mod saved, with the exact same config.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9245750/Logs.zip)

[Catherine_0044 BC-2240.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9245797/Catherine_0044.BC-2240.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9245802/CvMiniDump.zip)

**Comment by nobubblegums** [comment]
Having "Documents" on onedrive can cause problems with applications&games, probably the game cannot access some files. There are also a lot of files under "Maps" I don't recognize, the folder is supposed to be empty on new installs. Multiplayer Mods Workaround is also logged, it's finicky and might not be properly installed.

**Comment by abmpicoli** [comment]
Well, I did remove onedrive as a recommendation. The files under maps are both custom maps and firetuner scripts. They don't affect the gameplay unless I want so. Multiplayer workaround was not enabled.

Well, whatever...
