### ISSUE TITLE
AI that lose their pathfinder/exporation unit early don't replace it and stop exploring

### ISSUE THREAD

**Issue by maarten99** [LoneGazebo/Community-Patch-DLL#9073]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_
2.5

_2. Mod list (if using Vox Populi only, leave blank):_
alt diff

_3. Error description:_ 

example: take seat as the netherlands; he didn't explore north of him, half the land south of him, and he lost his pathfinder, not sure when, but I assume early on. 
Around 20 turns after the screenshot he did start exploring, but with actual military units (trebuchets and longswordsmen).

AI should maybe try to at least have 1 exploration unit in their army? (and never explore with actual military units designed for warfare/fighting)
![image](https://user-images.githubusercontent.com/24713571/182638772-8fc86c50-a50f-458e-8a40-828d8baf216e.png)

**Comment by ilteroi** [comment]
obviously there was a failure here but there is CvEconomicAI::DoReconState() to decide how many explorers are needed. can you check the economyai log for "explorer"?

**Comment by RecursiveVision** [comment]
Might be fixed
