### ISSUE TITLE
rebase indicator is practically invisible

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#908]
![image](https://cloud.githubusercontent.com/assets/1358966/11731253/48926382-9f9a-11e5-9d39-a83ade0da41d.png)

the orange ring indicates that the unit can rebase here ... who's supposed to see that?

is there a way to improve this? there is a function ShowRebaseRangeIndicator() in InGame.lua, which seems to be responsible, but I don't know the GUI stuff so well. 

Ideally also the cursor should change when rebasing is possible, right now it's a gamble every time whether you clicked the right spot.

**Comment by LoneGazebo** [comment]
good question - I'll take a look.

**Comment by LoneGazebo** [comment]
did you see my point re: the air strike function?

**Comment by ilteroi** [comment]
i just found the embark indicator (hotkey k) which might be a good alternative ...

**Comment by LoneGazebo** [comment]
Might be able to change the size of it- perhaps we should ask JFD? He's much more of a veteran of graphical things.
G

**Comment by Iamblichos** [comment]
Yeah I just think the size needs to be changed. Perhaps a line thickness change, a little more boldness, and a little larger.

**Comment by ilteroi** [comment]
sounds good - do you know where these properties can be set?

**Comment by LoneGazebo** [comment]
I looked at it (the Highlights.xml file in the base civ install 'Overlay' folder - look for "GroupBorder." Unfortunately, changes I've made to it don't seem to take effect, meaning that it isn't a file that can be hot-loaded easily. May need to create a new <Highlights> for it and define a new graphic.

**Comment by Iamblichos** [comment]
It may be similar to civ leader scenes. Updates to those don't load up on mods properly unless you are doing a Modpack, they are cached on initial game startup. (e.g. if you want to replace a leader scene of Bizmark with Hitler, it'll often--though not always--show Bizmark's leader scene in Mods). Modpacks get around this since they are loaded on startup.

**Comment by LoneGazebo** [comment]
Figured as much. Typically, things outside the UI and Database folders don't allow for hotswap.

G
