### ISSUE TITLE
Player proximity is buggy

### ISSUE THREAD

**Issue by IanE9** [LoneGazebo/Community-Patch-DLL#9086]
Proximity between players is updated using the function `CvPlayer::DoUpdateProximityToPlayer` and is done so when any of the following events occurs:
* City is founded - `CvCity::init`
* City is destroyed - `CvCity::PostKill`
* City is captured - `CvPlayer::acquireCity`
* Player is liberated - `CvPlayer::DoLiberatePlayer`
* Teams meet - `CvTeam::makeHasMet`

Because proximity is seemingly updated without care for whether or not two players have met, updating proximity upon meeting players should be redundant with a proper implementation. Currently though proximity updates take into account transient states of players, for instance whether or not the players can embark or cross ocean. This makes the current implementation flawed because proximity is not updated when these states change.

If either players has no cities during a proximity update, then the function declares the proximity `NO_PLAYER_PROXIMITY` and returns early. This is a problem because in many locations it is assumed that players will have a proximity value set. The locations where this occurs could be made to account for this, but it challenging to do so because little useful information about the proximity of a player can be derived from the value `NO_PLAYER_PROXIMITY` other than that one or both of the involved players has not yet settled a city.

There exists a logic error _somewhere_ that causes proximity to simply not update for players. I've observed the loop in `CvEspionageAI::BuildMinorCityList` retrieve `NO_PLAYER_PROXIMITY` for minors when both involved players are alive, have cities, and have met. This should not be possible. This occurred late game during Shaka's `CvEspionageAI::BuildMinorCityList` and of note is that Shaka had almost entirely been conquered and had only one city.

**Comment by RecursiveVision** [comment]
Did some cleanup: https://github.com/LoneGazebo/Community-Patch-DLL/commit/2727abb5ab207710ec17c43be223d148c835dc75

Hopefully fixes the issues.
