### ISSUE TITLE
Vassalage Toggle

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#909]
Turning vassalage off in the options, I can still propose Vassal Tax to the Congress. Capitulation also shows up in the diplomacy screen.

**Comment by LoneGazebo** [comment]
Weird. Vassal Tax will appear because XML elements cannot be so easily toggled on/off, but I'll take a look. Sounds like an option value isn't registering for some reason.

G

**Comment by LoneGazebo** [comment]
Addressed congress issue. We'll see about capitulation. Also adding a trade deal that makes a master release his vassals. We'll see.
