### ISSUE TITLE
CTD while progressing to next turn

### ISSUE THREAD

**Issue by jdoug312** [LoneGazebo/Community-Patch-DLL#9092]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_

2.5.8

_2. Mod list (if using Vox Populi only, leave blank):_

VP
Community Events (v5)
EAW
ENW
4UC
GH's Scotland
Tlingit for VP
Ethnic Diversity
Global Warming
Global Warming Congress
Great Prophet Historical Names
Hinin's Hisatsinom for VP
Hinin's Imazighen for VP
JFD's Norway for VP
Kushan Empire for VP
Nubia for VP
Chola for VP
Phoenician for VP
Quick Turns
Civ 6 style names
Sumer
The Goths for VP
Tomatekh's Benin for VP

_3. Error description:_ 
After clicking next turn, the game progresses to Mongolia's turn and then CTDs. I also have saves from previous turns if they'll be more help.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[2.5.8 logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9282145/2.5.8.logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Next Turn CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9282142/Next.Turn.CTD.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9282136/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by nobubblegums** [comment]
Thanks for reporting, but it crashes in one of the link units functions, which I've taken out of VP, so this is in modmod territory now. I'll take look sometime, but not really a VP issue anymore
