### ISSUE TITLE
Mountains a bit borked in 12/10 version

### ISSUE THREAD

**Issue by PurpleMentat** [LoneGazebo/Community-Patch-DLL#910]
Ranged units can fire over mountains without Indirect Fire.

Barbarians are spawning on Mountains but can't walk on them
http://steamcommunity.com/sharedfiles/filedetails/?id=573405578

**Comment by LoneGazebo** [comment]
Done.

**Comment by LoneGazebo** [comment]
From forum: "Non-Incan AI is trying to make road connections through Mountains. And since they can't move into Mountains, the roads just sit there uncompleted."

**Comment by ilteroi** [comment]
yeah, that should have been solved in the 12/10b version ...

**Comment by LoneGazebo** [comment]
We shall see! :)

**Comment by LoneGazebo** [comment]
Have you noticed that mountains and natural wonders look odd in the strategic view? I think they are not being assigned terrains anymore...
G

**Comment by ilteroi** [comment]
hmm. i never use that, but now that you mention it ... there is one thing i did, i forced mountain plots to have mountain territory and vice versa to cut down on special cases.

i guess there would be other ways to handle it, let me check

**Comment by ilteroi** [comment]
ok - fixed the strategic view. need to test some more map scripts to see if there are any strange effects.

btw, leaving strategic view during autoplay crashes the game for me. reliably. same for you?

and, loading an autosave from autoplay sometimes leads to a bare map view without UI elements - that happen to you also? for a given save it seems to be reproducable. have to restart the game then. lost many an interesting autosave to that bug

**Comment by LoneGazebo** [comment]
Re: SV crash - yes, but not if I hit ESC instead of clicking the button or using the hotkey.

Was the autosave done while autoplay was active? That'll cause odd saves, yeah.

**Comment by Edaka** [comment]
Posted by Kolaris on Civfanatics: "Mountains aren't blocking LoS to units on hills. I'm on the hotfix but it's not a new game."

**Comment by ilteroi** [comment]
hmm. possible. need to check that the mountain terrain has the correct properties set
