### ISSUE TITLE
2.5  non-random CTD

### ISSUE THREAD

**Issue by Thibix-Magnus** [LoneGazebo/Community-Patch-DLL#9105]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.5.0, DX 10 & 11):_
2.5

_2. Mod list (if using Vox Populi only, leave blank):_
VP
info addict
convenient start
(never had any issue with those 2)

_3. Error description:_ 
not random CTD. Happens at turn 145 whatever the previous choices.

_4. Steps to reproduce (optional):_
load game, click end turn.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

[logs_and_save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9331620/logs_and_save.zip)

**Comment by RecursiveVision** [comment]
Might be already fixed

**Comment by RecursiveVision** [comment]
Reliable loading of savegames and several crashes have been fixed for 2.6, closing all CTD reports from prior versions.
