### ISSUE TITLE
Double Agents tenet Spy capture rate does not add up properly (or misleading tooltip)

### ISSUE THREAD

**Issue by vegeta1k95** [LoneGazebo/Community-Patch-DLL#9116]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.6.0, DX 10 & 11):_
2.6
_2. Mod list (if using Vox Populi only, leave blank):_
_3. Error description:_ 

Double Agents tenet (Order) description says that it gives twice the chance to capture enemy spies.
But percentages before/after applying this policy does not add up.

Before and after applying policy:
![image](https://user-images.githubusercontent.com/32207817/185015967-4ce10cab-9b46-4596-b126-cc81c1c1ebeb.png) ![image](https://user-images.githubusercontent.com/32207817/185016350-a3f053c7-9171-4bbc-924a-397586d5eafc.png)

The 18% chance goes to 64% somehow.

Also, description is not clear whether "capture" = "identify" and/or "capture" = "kill"

**Comment by LoneGazebo** [comment]
Good catch, I believe i've already caught this and issued a commit to fix it.

**Comment by LoneGazebo** [comment]
#9117
