### ISSUE TITLE
On founding religion, Celts lose Faith per Turn in cities with just Pantheon

### ISSUE THREAD

**Issue by PurpleMentat** [LoneGazebo/Community-Patch-DLL#912]
Screenshot showing 4 cities, 4 Faith per Turn
http://steamcommunity.com/sharedfiles/filedetails/?id=573430529

**Comment by LoneGazebo** [comment]
Not a bug, but an unclear UA - once you get a religion, you lose the bonus faith until your religion is in place. i can make that change, though.

**Comment by PurpleMentat** [comment]
Not sure it's a needed change. Puts Celts in a unique place of founding quickly but enhancing late if they rely on their UA.

**Comment by LoneGazebo** [comment]
I'll adjust text, otherwise we leave this as-is.
