### ISSUE TITLE
[2.6] Crash to desktop when opening technology screen

### ISSUE THREAD

**Issue by OmaiGrundles** [LoneGazebo/Community-Patch-DLL#9125]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.6.0, DX 10 & 11):_
Vox Populi with EUI, installed with the version 2.6 installer
DirectX 10 & 11

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi with EUI
Wonder Race

_3. Error description:_ 
It seems that once I get into the later midgame, the game will CTD when opening the technology screen more and more often.
This was mentioned in a closed issue a while back, but it seems to still be happening to me. I did a fresh install of everything before starting the current game.

_4. Steps to reproduce (optional):_
Cant quite reproduce yet, but what I did the first time was the following:
End the current turn, spend some gold in a city to trigger the bank giving enough science to finish the current tech, open the technology screen.

I expect to be able to more reliably cause the CTD if I keep playing the game, one thing to note is the couple times it has crashed for me so far, I haven't been able to get a reliable save right before the crash. It seems less prone to crash after a reload, compared to V2.5

I will keep playing and try to get further along enough to trigger the crash more reliably.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9367080/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
(Accidently sent wrong file here, see comment for better save anyway)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9367086/CvMiniDump.zip)

**Comment by OmaiGrundles** [comment]
I managed to get a save file that consistently crashes as soon as you open the tech screen, here is the save, plus all the logs.
[2.6_CrashOnTechScreen.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9368259/2.6_CrashOnTechScreen.zip)

**Comment by OmaiGrundles** [comment]
I'm starting to get crashes on other screens instead of just the tech screen. I had got a CTD when on the spy screen sending a spy to a new city, and later on got a CTD when opening the 'swap great works' screen. These seem to stop happening on a reload, but I can usually only play a couple turns before the game crashes again at some point. I'm not sure if all of these crashes are due to the same reason, but here is the logs and dump from the latest crash as well. (save included but I think it was a turn or half turn between the save and the crash)
[2.6_CrashOnSwapWorks.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9378754/2.6_CrashOnSwapWorks.zip)

**Comment by RecursiveVision** [comment]
Doesn't crash when I load it.

**Comment by OmaiGrundles** [comment]
Ok, I feel like the game is just messing with me at this point, because suddenly the save files are not crashing for me either as I wanted to make sure I sent the right files. It was so damn reliable to crash yesterday

But I *swear* I've had like 15 CTD's on this playthrough so far... are the minidump files not useful at all?
Somehow today I was able to actually do like 12 turns before it crashed on the tech screen again XD

**Comment by besset** [comment]
I also havent been able to finish a single vox populi civ game the since vox populi version 2.0, always crashes every turn in the late game, especially when opening tech screen

**Comment by RecursiveVision** [comment]
We can't fix memory-related crashes, sorry. You'll have to play with less intense settings.

**Comment by OmaiGrundles** [comment]
Ok, I've even tried changing the game to absolute *minimum* settings and it still can crash just as easily. In fact it somehow crashes even worse, like red splotches appeared on the screen before it crashed last time and I didn't even open any overlays.

Task manager doesn't even show the game using more than 1.8 gigs of ram, and i have 32 gigs available. And my GPU has 8gigs of video ram. (GTX 1080) Just what kind of memory errors are we talking about here?

**Comment by OmaiGrundles** [comment]
Ok, I finally found *one* thing that seems to have either solved the issue or massively helped: *turning off fullscreen mode*

**Comment by IanE9** [comment]
> Ok, I've even tried changing the game to absolute _minimum_ settings and it still can crash just as easily. In fact it somehow crashes even worse, like red splotches appeared on the screen before it crashed last time and I didn't even open any overlays.
> 
> Task manager doesn't even show the game using more than 1.8 gigs of ram, and i have 32 gigs available. And my GPU has 8gigs of video ram. (GTX 1080) Just what kind of memory errors are we talking about here?
> 
> Ive reloaded this dang game like 50 times on this playthrough alone, and @besset has been having issues since 2.0 How can anyone actually get to the end of a game right now?

I'm taking a look at the save you posted now that crashes when opening the tech screen. It does the same for me and memory usage is sitting at around 2.2Gib when it happens. Unfortunately since the game is a 32-bit process it can't actually use more than 4Gib of memory. The game is compiled to be[ Large Address Aware](https://docs.microsoft.com/en-us/cpp/build/reference/largeaddressaware-handle-large-addresses?view=msvc-170) which is supposed to allow it to use the whole address space so I'm not entirely certain why it's crashing at only 2.2Gib, but a typical a 32-bit Windows process only supports half of the address space so I'd assume that it really is just a crash related to memory exhaustion.

Maybe the Lua DLL isn't Large Address Aware so it's running out of memory there? If that's the case _maybe_ it can be fixed by using a custom built Lua DLL. I haven't tried this yet and I'm not familiar with the whole story regarding what Large Address Aware actually does internally so don't get your hopes up.

**Comment by IanE9** [comment]
I edited `lua51_Win32.dll` to be Large Address Aware with `EDITBIN` and initially thought this had fixed the problem, but reverting the change has revealed that it's no longer crashing at all when I'm opening the tech screen on the save you provided. I don't know what could be making this so inconsistent, but maybe Direct-X is caching something.

Regardless if you want to experiment yourself with this, you can set the Large Address Aware flag on just about any DLL/EXE if you have Visual Studio installed by running `EDITBIN /LARGEADDRESSAWARE <filename>` from a Visual Studio Command Prompt. Just remember to backup things before you go tinkering about with them. If you learn anything interesting please let me know.

**Comment by besset** [comment]
i did some reasearch here's a list of things that solved CTD's for a lot of people:
- run all graphics settings on low (not minimum setting, this can cause more instability) and low resolution (like 1080p 60hz)
- turn of all resources & yield icons, especially late game (a lot of people said CTD's was fixed by this change alone)
- remove vox populi entirely from mod folder, delete cache folder, verify integrity of game files, reinstall vox populi
- disable lua hooks https://forums.civfanatics.com/threads/stability-improvement.665199/
- zoom in everytime before ending a turn to avoid crashing

im currently trying out these steps

**Comment by OmaiGrundles** [comment]
**Turning off fullscreen mode** and leaving other graphics settings at max seems to have fixed every "overlay CTD" including the technology screen. If any of you are getting CTD's at the tech screen, try that. Ive gone like another 16 turns or so and almost in the information era without any more overlay crashes, when I was getting those nearly every turn.

Though, I am now getting the occasional "non-overlay" crashes, twice when panning the screen around, and once during an enemy turn. These may actually be the memory-related crashes, so If they keep happening I may have to try some of the things everyone mentioned above.

**Comment by IanE9** [comment]
> **Turning off fullscreen mode** and leaving other graphics settings at max seems to have fixed every "overlay CTD" including the technology screen. If any of you are getting CTD's at the tech screen, try that. Ive gone like another 16 turns or so and almost in the information era without any more overlay crashes, when I was getting those nearly every turn.
> 
> Though, I am now getting the occasional "non-overlay" crashes, twice when panning the screen around, and once during an enemy turn. These may actually be the memory-related crashes, so If they keep happening I may have to try some of the things everyone mentioned above.

I always play outside of fullscreen in case I need to debug something and was doing so when I loaded your save and crashed on the tech screen earlier today. The fact that everything is working now that you've changed to it may just be a fluke.

**Comment by OmaiGrundles** [comment]
Hmm, one other setting I just remembered I did as well was 'overlay detail' (don't know exactly what that does) in video settings was set to low, its possible that its both that and turning off fullscreen that has done it. If I ever get a tech screen or overlay crash again I will update. 

I probably need to attempt fixing the 'panning the screen around where there are a lot of units' crash I'm having now though XD

**Comment by OmaiGrundles** [comment]
> I edited `lua51_Win32.dll` to be Large Address Aware with `EDITBIN` and initially thought this had fixed the problem, but reverting the change has revealed that it's no longer crashing at all when I'm opening the tech screen on the save you provided. I don't know what could be making this so inconsistent, but maybe Direct-X is caching something.
> 
> Regardless if you want to experiment yourself with this, you can set the Large Address Aware flag on just about any DLL/EXE if you have Visual Studio installed by running `EDITBIN /LARGEADDRESSAWARE <filename>` from a Visual Studio Command Prompt. Just remember to backup things before you go tinkering about with them. If you learn anything interesting please let me know.

Will Visual Studio Code work for that? I no longer have any copies of the full IDE anymore since I left college. (Also I'm just rusty AF)
It is quite annoying just how inconsistent all of these crashes for everyone is though for sure, It has to be a nightmare for everyone working on this project.

Vox Populi has been very fun to play so far, even at Prince Difficulty the AI is no longer a complete pushover, especially in world congress. No way would I have continued to play most things after 50+ crashes but I keep coming back to this XD

**Comment by IanE9** [comment]
> > I edited `lua51_Win32.dll` to be Large Address Aware with `EDITBIN` and initially thought this had fixed the problem, but reverting the change has revealed that it's no longer crashing at all when I'm opening the tech screen on the save you provided. I don't know what could be making this so inconsistent, but maybe Direct-X is caching something.
> > Regardless if you want to experiment yourself with this, you can set the Large Address Aware flag on just about any DLL/EXE if you have Visual Studio installed by running `EDITBIN /LARGEADDRESSAWARE <filename>` from a Visual Studio Command Prompt. Just remember to backup things before you go tinkering about with them. If you learn anything interesting please let me know.
> 
> Will Visual Studio Code work for that? I no longer have any copies of the full IDE anymore since I left college. (Also I'm just rusty AF) It is quite annoying just how inconsistent all of these crashes for everyone is though for sure, It has to be a nightmare for everyone working on this project.
> 
> Vox Populi has been very fun to play so far, even at Prince Difficulty the AI is no longer a complete pushover, especially in world congress. No way would I have continued to play most things after 50+ crashes but I keep coming back to this XD

Visual Studio Code doesn't come with it as far as I'm aware. I'm fairly sure the free versions of Visual Studio do though. They use the branding "Express" so if you just search "Visual Studio 2022 Express" or similar you should be able to find them.
