### ISSUE TITLE
Gold 

### ISSUE THREAD

**Issue by paulu-asg** [LoneGazebo/Community-Patch-DLL#9126]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.6.0, DX 10 & 11):_
2.6 (August 16, 2022)

_2. Mod list (if using Vox Populi only, leave blank):_
(1) Community Patch	Version	109
(2) Vox Populi	Version	15
(3a) VP - EUI Compatibility Files	Version	1
(4a) Promotion Icons for VP	Version	6
(4b) UI - Promotion Tree for VP	Version	22
(9d) Reforestation for VP	Version	4
(game) Capture+++	Version	5
(over) More Unique Components for VP	Version	81
(overhaul) Enlightenment Era (Vox Populi)	Version	4
(overhaul) More Wonders for VP	Version	1
(overhaul) Unique City-States	Version	9
(text) Promotion Overhaul for VP	Version	27
(ui) List Enhancements for VP	Version	6
(ui) Trade Opportunities for VP	Version	12
(ui) Wonder Planner for VP	Version	10
Civic And Reform	Version	12
Better Lakes for Vox Populi	Version	2
City Limits	Version	7
Even More Resources for Vox Populi	Version	8
Improved Top Panel	Version	1
InfoAddict	Version	22
Monopoly Buildings for Vox Populi	Version	3
No Navy by Lake Cities	Version	5
(UI) Promotion Flags EUI (for VP)	Version	3
Quick Turns	Version	10
WH - Military Log for VP	Version	2
UI - Religion Spread (Vox Populi)	Version	1
Vox Populi's Bare Necessities	Version	5

_3. Error description:_ 
These behaviors are all new with the same list of installed mods when installing the newest VP version.  The same problems manifest both on the computer I was using before and a laptop where Civ was newly installed.

   a. The display for gold amount and gain in the upper left shows a text key rather than values.
   b. Even More Resources no longer functions:  the icons are placed but they do not show additional yields and do not permit the appropriate improvements.  So, for instance, the presence of tin on a grassland tile does not permit me to build a mine on it.
   c.  Most critically, Ancient Ruins are absent.

Note that I tried with no mods beyond VP and the above problems were not seen.  Of course, for issue b that is kind of trivial and issue a might be tied to a single mod.  However, the problem with Ancient Ruins is critical and mysterious.

_4. Steps to reproduce (optional):_
None.  

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9367577/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
  Since this seems to be largely a map generation problem, a save game doesn't seem relevant.

4. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

5. Screenshots (optional):

**Comment by nobubblegums** [comment]
Improved Top Panel is integrated into VP now, you should delete it. Even More Resources has been updated for VP 2.6, be sure to download that.

**Comment by RecursiveVision** [comment]
^ what he said
