### ISSUE TITLE
Discipline does not grant culture to cities that already have a unit, subtracts when unit leaves

### ISSUE THREAD

**Issue by PurpleMentat** [LoneGazebo/Community-Patch-DLL#913]
Screenshot shows -3 culture from Policies.
http://steamcommunity.com/sharedfiles/filedetails/?id=573458745

**Comment by LoneGazebo** [comment]
Huh. Must be because ilteroi cached garrison values to save performance.

**Comment by PurpleMentat** [comment]
Also, doesn't seem to be providing the happiness at all.

**Comment by LoneGazebo** [comment]
Oh good.

**Comment by pandasnail** [comment]
I had this too. I actually don't even get shield bonuses for garrisoning in a city. And this weird advisor screen shows up to tell me I shouldn't attack my own city. Those goofy 'this is a good place to found a city' people. If I left a unit in the city for like twenty turns, all of a sudden the happiness, shields and culture would show up, and stay as long as the game was open, even if the unit left for awhile. If I saved, quit, and reloaded, the bonuses left. 

(Happens with only CP as well)

Do you want me to make some logs? I did some test games earlier and I could do another one pretty quick. Xml and database, yeah?

(Sorry for not posting this on my own, I thought it was my computer being dumb, guess I shouldn't assume that)

**Comment by LoneGazebo** [comment]
I think this is an issue with garrison values being cached and refreshed at certain times – Ilteroi should be able to sort it out.

**Comment by ilteroi** [comment]
hmm. can't reproduce. discipline working fine here

**Comment by Edaka** [comment]
I can confirm the issue with city defense not immediately increasing upon stationing a unit there (no matter how strong) even with the 12/6 beta version. Haven't tried the policy, though.

**Comment by LoneGazebo** [comment]
I'm going to end-around the cached garrison value (since it is purely for dangerplot calculations) and just manually check where it needs to in the DLL.

G

**Comment by LoneGazebo** [comment]
Done.
