### ISSUE TITLE
(Planning War) leader screen text uses masculine pronouns for China, Russia, etc

### ISSUE THREAD

**Issue by jdoug312** [LoneGazebo/Community-Patch-DLL#9131]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.6.0, DX 10 & 11):_

2.6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

The text that roughly goes, "I intend to rid the world of his presence!" when you ask a civ what they think of another doesn't switch "his" to "her", etc when the target civ is run by a woman leader.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by bsesar** [comment]
Perhaps we just replace all occurrences of "he" and "she" with "they"?
