### ISSUE TITLE
CTD after selecting the Mods in the Mods Menu and clicking next

### ISSUE THREAD

**Issue by notac0der** [LoneGazebo/Community-Patch-DLL#9138]
_1. Mod version 2.6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ CTD after selecting the Mods in the Mods Menu and clicking "next"

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9387736/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9387734/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Can't reproduce.

**Comment by notac0der** [comment]
No other mods

**Comment by RecursiveVision** [comment]
Try verifying file integrity on Steam and reinstalling the mod.

**Comment by notac0der** [comment]
Thanks for the advice, but I have been doing that (+re-installing Civ 5) already :(

**Comment by RecursiveVision** [comment]
No idea how to help then, sorry

**Comment by notac0der** [comment]
Thank you for trying. I am just frustrated, that I cannot get it to run anymore.
