### ISSUE TITLE
religious pressure only for internal trade routes?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#914]
![image](https://cloud.githubusercontent.com/assets/1358966/11758644/fdc54606-a06d-11e5-8d8d-ee9ac61114ca.png)

can this be true or is it a bug?

**Comment by LoneGazebo** [comment]
Depends on how far away the route is. If it goes too far outside the distance minimum it will not produce faith.

**Comment by ilteroi** [comment]
i know - but almost by definition my own cities are closer than foreign cities - so how can that be the result?

can you reproduce it?

**Comment by LoneGazebo** [comment]
I'll give it a look, yep. I do think that we need to increase the base pressure a bit- users are reporting +3/+4 rates where they used to be +6.

**Comment by ilteroi** [comment]
didn't occur again. don't know what was the matter there. anyway i slightly reduced terrain costs for traderoutes, which should make the normalized distance a bit lower, leading to higher pressures.
