### ISSUE TITLE
CTRL+RCLICK new feature not working

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#9144]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.6.0, DX 10 & 11): 2.6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by nobubblegums** [comment]
Can you be more specific, which action did you try?

**Comment by Aqinu** [comment]
If I do the shortcut command on any notification, it should remove all of them. Doesn't seem to be working I don't know what to say more specific.

**Comment by nobubblegums** [comment]
Well there's also a CTRL+RCLICK shortcut to quickly issue build orders, but ok I get it now. I'll take a look

**Comment by RecursiveVision** [comment]
@nobubblegums I wasn't able to dismiss notifications using CTRL+RCLICK in Observer mode after loading a save file - maybe loaded notifications don't work?

**Comment by Stalker012345** [comment]
Also noting that the ctrl + rclick option for assigning waypoints to a unit is not working (assuming that is actually a thing, I saw it in the new tooltips). So maybe there is an issue with Rclicks in general?

**Comment by nobubblegums** [comment]
Waypoints are actually SHIFT + RCLICK, maybe I wrote the tooltip wrong. CTRL + RCLICK is for quick actions, e.g. move and build orders.

**Comment by nobubblegums** [comment]
@Stalker012345 Just checked waypoints, they do work fine. Tooltip also looks fine, btw waypoint orders are executed when you click on End Turn.

**Comment by nobubblegums** [comment]
Eh I simplified the function, seem to be working on my end. let's see

**Comment by Stalker012345** [comment]
I just tried the waypoint again myself, and when I click literally nothing
happens.
