### ISSUE TITLE
CTD after accepting joint war

### ISSUE THREAD

**Issue by LBier** [LoneGazebo/Community-Patch-DLL#9149]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.6.0, DX 10 & 11):_
2.6.0 - DX 11

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
Game always crashes to desktop when accepting joint war.

_4. Steps to reproduce (optional):_
Press end turn
decline greece declaration of friendship
accept joint war with mongolia <- crash

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.
[issue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9419402/issue.zip)

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by RecursiveVision** [comment]
Please be sure to list ALL of your mods - InfoAddict included.

**Comment by RecursiveVision** [comment]
[CvGameCore_Expansion2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9436153/CvGameCore_Expansion2.zip)

@LBier Replace the DLL in your MODS > (1) Community Patch folder with this one to continue playing.
