### ISSUE TITLE
CTD on AI turn (war enemy in just declared war)

### ISSUE THREAD

**Issue by ciqasty** [LoneGazebo/Community-Patch-DLL#9151]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.6.0, DX 10 & 11):_
2.6 (16th august, 2022)

_2. Mod list (if using Vox Populi only, leave blank):_
Vox Populi with EUI
Really advanced startup (Steam)
Faster aircraft animations (Steam)

_3. Error description:_ 
Crash to desktop

_4. Steps to reproduce (optional):_
Load save
End turn
Accept Morocco DoF
Reject Spain DoF
Wait for Iroquois turn

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9427617/Logs2.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[precrashsave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9427618/precrashsave.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9427619/CvMiniDump.zip)

4. Screenshots (optional):

**Comment by ciqasty** [comment]
Sorry logs were not enabled. Crash is reproducible so here are new logs + minidump, save stays the same:
[logs3.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9427691/logs3.zip)
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9427692/CvMiniDump.zip)

**Comment by RecursiveVision** [comment]
@ciqasty The bug is related to your war with the Iroquois. Do you have the save from turn 332?

**Comment by ciqasty** [comment]
Hi, I have made a save before making DoW on the same turn as the save attached (basically the beginning of turn, before any moves etc). Would that one be useful? I can upload later today, not sure if there are any autosaves from turn earlier.

**Comment by RecursiveVision** [comment]
Never mind, I solved the issue!

**Comment by ciqasty** [comment]
Nice, thanks! will test later :)
