### ISSUE TITLE
Wrong Percentage in Spy Tooltip

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#9156]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.6.0, DX 10 & 11): 2.6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description: 

When you defend your cities with a spy it say 0% chance to kill but clearly is not true. From event I choose+50% to identify and/or to kill a spy option. As you can see it did kill a foreign spy.

_4. Steps to reproduce (optional):_

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):
![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/186846248-69c1e3e3-c9b9-4857-9d23-02d1fb18749d.jpg)
![Civ5Screen0001](https://user-images.githubusercontent.com/49090452/186846255-42ecb152-3779-47d4-9449-5bbaf0f0ac26.jpg)

**Comment by RecursiveVision** [comment]
@LoneGazebo

**Comment by LoneGazebo** [comment]
Already fixed in the hotfix I sent @RecursiveVision on 8/16
