### ISSUE TITLE
Even if open-borders are renewed, units are moved out first

### ISSUE THREAD

**Issue by PerfectDark99** [LoneGazebo/Community-Patch-DLL#9158]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.6.0, DX 10 & 11):_
2.6

_2. Mod list (if using Vox Populi only, leave blank):_

_3. Error description:_ 
I'm at war with Rome and between us is the Netherlands which I have been best buddies with forever. Anyway Rome declares war on me and I move my army through Netherlands terrain. At some point during the war William ask for renewal of open-borders and I obviously agree.

BUT: All my units get moved out of his borders into Romes border. Like field guns right next to a Roman city and 3 units. My army is no completely out of place with siege units in front which I will likely loose a couple of needlessly.

I say the correct behavior should be to only move units out if the agreement is not renewed.

I will now have to completely withdraw as I'm getting wrecked as my army wasn't great to begin with and now completely unorganized.

---------------------------
![Civ5Screen0099](https://user-images.githubusercontent.com/58620501/187037852-e1501b53-0df2-4f92-ae56-3767ec0a8a77.jpg)

**Comment by saamohod** [comment]
It has always been like this, but I wish it could be changed. Very annoying.

**Comment by OmaiGrundles** [comment]
I wonder if a trade deal that 'extends open borders time' would be possible that the player could manually request

**Comment by ilteroi** [comment]
there is a flag CvDeal::m_bConsideringForRenewal which should prevent this, but apparently it's not working?

**Comment by LoneGazebo** [comment]
It’s probably an order of operations with when the deal is reviewed and the units are checked for violating borders.

**Comment by LoneGazebo** [comment]
I always dreamed of doing the civ 2 thing where you can walk anywhere but a civ can ask you to leave, but that sounds tedious to code

**Comment by ilteroi** [comment]
that's the thing - if m_bConsideringForRenewal is set, the open borders should not be cancelled on expiration, but i did not follow the spaghetti further

**Comment by LoneGazebo** [comment]
I think that bool is reset to false at the end of the turn.
