### ISSUE TITLE
Air Unit Attack

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#916]
Had a strange bug in my last game where my air units couldn't attack. Right click or Air Strike just gave me a red circle over enemies. However, using an air unit to DoW caused the attack to occur normally. Didn't seem to affect the AI so I conclude it was a LUA issue. 

Will try to reproduce in next game with any LUA stuff disabled. Posting now in case someone else saw this bug.

**Comment by Edaka** [comment]
Hm, that was a known issue that was supposed to be fixed in the latest beta version (you can see the discussion here: https://github.com/LoneGazebo/Community-Patch-DLL/issues/895 ). You're playing on that one, right?

**Comment by Hokath** [comment]
its probably this. Poor google-fu by me. Apologies.

**Comment by LoneGazebo** [comment]
This was fixed, yes.
