### ISSUE TITLE
CTD during AI turns

### ISSUE THREAD

**Issue by MrC1065** [LoneGazebo/Community-Patch-DLL#9164]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.6.0, DX 10 & 11):_
2.6.

_2. Mod list (if using Vox Populi only, leave blank):_
Accurate Earth v10, Events and Decisions.

_3. Error description:_ 
Crash to desktop with c0000005 memory error code.

_4. Steps to reproduce (optional):_
Play game, wait about 50-100 turns, game will crash during AI turns. It is possible to avert the crash by eliminating the civilization from the game, however it doesn't appear that a specific civ is the problem. In this game, India crashes the game but in another, it was the Zulus. I also couldn't see if the AI was doing anything in particular to cause a crash, as on its turn India wasn't finishing its production and just had warriors stationed around its territory. I was also able to reproduce the bug on two different PCs with completely different specs.

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9457527/Logs.zip)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change autosave frequency in the game's Options menu):
[Save.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9457547/Save.zip)

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):
[Dump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9457551/Dump.zip)

4. Screenshots (optional):

**Comment by axatin** [comment]
The crash is caused by India not having a Capital City in this game, only one city which is not its capital. Could this maybe be caused by the Events and Decisions Mod?

**Comment by MrC1065** [comment]
Yep, that was the issue. Maybe the AI on Community Patch doesn't know how to build palaces? Not sure why India doesn't start with a palace in this mod but usually you can just build one anyways.
