### ISSUE TITLE
Lost buildings on city trade

### ISSUE THREAD

**Issue by oalzubbi** [LoneGazebo/Community-Patch-DLL#917]
Cities gained via peace deal (not from direct millitary conquest) lose buildings when you receive them.

**Comment by LoneGazebo** [comment]
Peace deal cities are considered 'conquest,' just FYI.

**Comment by ilteroi** [comment]
ok - guess that explains it - but should they?

**Comment by LoneGazebo** [comment]
Not necessarily, no. I'll change the code.

**Comment by LoneGazebo** [comment]
Well, seems they are set as gifts. Odd. I added a gift check to building code of init new city, so we'll see if that fixes it.
