### ISSUE TITLE
Reproducible CTD on AI turn

### ISSUE THREAD

**Issue by TooManyCords** [LoneGazebo/Community-Patch-DLL#9172]
_1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.6.0, DX 10 & 11):_
August 16

_2. Mod list (if using Vox Populi only, leave blank):_
full VP
3+4 UC
Monopoly buildings
Naval Warfare
Unique City States
More Wonders
(a few more, see picture)

_3. Error description:_ 
CTD on AI turn just after I see a 'reformation belief added' bubble (no idea if related). 

_4. Steps to reproduce (optional):_
Load mods, load game, next turn, 💀 

---------------------------
Supporting information:
Please note that you can attach .zip files by dragging-and-dropping them. If possible, zip up all supporting data and post that way.

1. Log files (always attach your Logs folder, located at My Documents/My Games/Sid Meier's Civilization 5. For instructions, go to the repository's main page, under "To enable logging for bug reports"):
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9485682/Logs.zip)
![Screenshot 2022-09-04 181918](https://user-images.githubusercontent.com/26443204/188337644-4a095541-47cd-48f3-aadf-39e6e0b4d7b4.png)

2. Save game (always attach a save that was made a turn before the error; located at My Documents/My Games/Sid Meier's Civilization 5/ModdedSaves; you can change au
[Ashurbanipal_0253 AD-1080.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9485685/Ashurbanipal_0253.AD-1080.zip)
tosave frequency in the game's Options menu):

3. CvMiniDump.dmp file (attach if experiencing a game crash. Located at Program Files/Steam/steamapps/common/Sid Meier's Civilization V):

4. Screenshots (optional):

**Comment by JohnsterID** [comment]
> _1. Mod version, and DirectX version if reporting a graphical issue (X.Y.Z, e.g. 2.6.0, DX 10 & 11):_ August 16

Have you tried the hotfix dll posted on 26 Aug 22?

>Moderator Action: After installing this version with the autoinstaller, please see this post for a DLL replacement that fixes crashes: https://forums.civfanatics.com/threads/new-version-2-6-august-16-2022.678491/page-7#post-16324903

**Comment by TooManyCords** [comment]
Welp, that was it. Thank you much.

Sorry, I missed that hotfix, please close this ticket.
