### ISSUE TITLE
Bad AI Grand Strategy

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#9179]
_1. Mod Version (X.Y.Z). Current Version: 2.6.0_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

The AI's Grand Strategy AI is ass (CvGrandStrategyAI.cpp). Reminder to myself to clean it up.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by nobubblegums** [comment]
awesome report is awesome

**Comment by LoneGazebo** [comment]
Hey that’s my shitty code you’re talking about.

**Comment by LoneGazebo** [comment]
lol

**Comment by LoneGazebo** [comment]
The flavor system is a joke
