### ISSUE TITLE
Units don't get Fallout Resistance or Fallout Immunity

### ISSUE THREAD

**Issue by Pathologic72** [LoneGazebo/Community-Patch-DLL#9189]
_1. Mod Version (X.Y.Z). Current Version: 2.6.0

2.6.0 (with Recursive's updated .dll)

_2. DirectX Version_

_3. List of Other Mods_

None

_4. Describe the Issue_

The promotions do not appear in the unit panel, and units still take 15 damage from ending their turn in fallout. Tested by researching both techs, and producing a few different types of land units with the techs researched. It doesn't apply to either old or new units. Pretty sure this is broken?
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by LessRekkless** [comment]
Which units are you referring to?  Only civilians are supposed to receive these promotions.
