### ISSUE TITLE
no yield icons in recently annexed city

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#919]
![image](https://cloud.githubusercontent.com/assets/1358966/11764226/1eaaf860-a128-11e5-9ef9-f0ada90bbd34.png)

this city was annexed this turns. initially no yield icons at all showed up. the two locked tiles were bought and do have yields. locking was also a bit akward, had to leave the city screen and come back for it to work (but other plot yields still invisible).

EUI, i presume? is there a structured way of reporting those?

**Comment by LoneGazebo** [comment]
Yeah sounds like EUI. I'd post in the EUI thread, maybe?
