### ISSUE TITLE
AI surrenders in a cocky fashion

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#920]
The AI will often approach you with cocky, self-confident exclamations while surrendering. Imagine a situation where Montezuma strikes a peace deal with you, offering all his gold and capitulation while boasting 'That will teach you a lesson!'. It only happens if the AI approaches you on its turn.

**Comment by LoneGazebo** [comment]
Huh. Seems there's something off with the AI's evaluation of peace deals in their turn (same issue as with the deals themselves).
