### ISSUE TITLE
2.6 - Kidnap Specialist Mission is not expiring

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#9204]
_1. Mod Version (X.Y.Z). Current Version: 2.6.0_

2.6

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

The kidnap specialist mission is supposed to give a boost to the capital specialist yields of +2 for 15 turns. However, the bonus does not seem to be expiring, I have used this mission for over 50 turns and have never seen the yields come back down. My specialist yields are now quite high.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Kidnap Mission Bug.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9592424/Kidnap.Mission.Bug.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by Stalker012345** [comment]
Just to reaffirm, I watched my specialist numbers skyrocket all game with the mission, getting over 80 yields per specialist by the end. So 100% confirmed the mission is not expiring.

**Comment by LoneGazebo** [comment]
I will fix.

**Comment by LoneGazebo** [comment]
Alright I just got some time to check on this and the event is expiring correctly. However the new code 'ModifierUpdateInsertRemove' used to change the function is the culprit. That's not my code, and it is a core bit so I don't want to mess with it,

**Comment by LoneGazebo** [comment]
I'll continue to look at it but the event firing functions are working correctly.

**Comment by LoneGazebo** [comment]
Further analysis shows that the code is all working correctly, and the event is ending correctly. @Stalker012345 are you still seeing this on latest?

**Comment by Stalker012345** [comment]
I haven't checked it again since I noted the bug. I will try it on my
latest game

**Comment by Stalker012345** [comment]
Yep its confirmed. My specialist yields are never going back down no matter
how much time has passed.

[image: image.png]

**Comment by LoneGazebo** [comment]
I ran a test session on the current codebase and the bonus went down when it expired...mind sharing a save before it happens when you've got a chance? I'm wondering if there's something happening that I'm not properly simulating in my quick debug session.

**Comment by LoneGazebo** [comment]
@Stalker012345 still need a save on this...

**Comment by LoneGazebo** [comment]
Aha, I think I got it. If the duration was low enough it was not being allowed to expire properly. Fixed.
