### ISSUE TITLE
yield explosion

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#9206]
just seen in t450 of a test game:

![image](https://user-images.githubusercontent.com/1358966/190901509-8abf9370-8a9c-4671-b8fb-2e119ff0abe5.png)

is this intended? food supply seems to be a bit excessive ...

(gold is mostly from trade routes, and science from running a process, so that's ok)

**Comment by Stalker012345** [comment]
To get from 431.1 to 6155.95, you need a x14 multiplier (or 1400%). And that's not even taking into account food consumption, which is closer to x15.

While the % numbers are high, they are no where close to that (my quick math shows ~700%, or x7). So yeah there is definately something off there.

**Comment by azum4roll** [comment]
Happiness bonus is +2% per excess happiness. It isn't that hard to have 70 excess happiness in the capital if you're winning all those race quests from CS.

**Comment by Stalker012345** [comment]
A few players on discord have been noting the AI seems to surge incredibly in science around the industrial era....but its on warlord, gaining handfuls of tech in a matter of a few turns. Maybe related?
