### ISSUE TITLE
Splendor

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#922]
When Splendor triggers, I get for example 750 GA points and 250 Culture. Since the factor is three, I gues it comes from GA scaling with gamespeed and culture not.

**Comment by Edaka** [comment]
Playing on marathon speed, right?

**Comment by Kolaris8472** [comment]
Mausoleum of Halicarnassus should probably scale with Gamespeed as well. Only getting 90 Culture return in Renaissance when my Culture-per-Turn is 500.

**Comment by LoneGazebo** [comment]
Things that are % of a yield do not scale with gamespeed, as the % is a natural scaling mechanism.

**Comment by Edaka** [comment]
All of those things (Splendor's culture and GAP and Mausoleum's culture per expended great person) are flat boosts, aren't they?

**Comment by LoneGazebo** [comment]
Yes, sorry - I was saying that % boosts don't scale (MoH gets a scaler on WLTKD). Not sure if all of these flat boosts scale though.
