### ISSUE TITLE
Interaction between forts and cities as canals

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#923]
By Lord Oden: 'My capital gained access to ocean after building fort for passage. Trade route overview confirms possible sea trade routes, however I can not build trade ships in capital or transfer trade ships to capital.'

This seems like an issue that would clump up one's trade overview with trade routes that can't possibly be made. Also, it's possible to make 3 tile long, passable on water fort-city-fort canals right now (not necessarily a big deal gameplay-wise, but certainly unrealistic). I wonder if hardcoding city tiles that are not on the coast to be impassable by ships would be possible/easily done. I mean, there's something that prevents landlocked forts from being passable by boats, right?

**Comment by ilteroi** [comment]
strange. sea trade routes are only possible between coastal cities. there's an explicit check for it. having a fort should not make a difference.

the daisy-chained forts were a bug.
