### ISSUE TITLE
ExCE Jungles

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#924]
So I managed to finish a game with ExCE on, no crash (harrah!)
Going through another now and no crash there yet either.

However, at the start of the game jungles only yield 1 food.
Jungle immunity seems to let units pass through jungles, if you click a plains tile on the other side of one, for instance. However, they can't move onto them (red circle). Upon discovering Optics I can move onto them, and once I do this the yields go back to 2 food, 1 prod. Weird.

Linking this to JFD since I don't know what is causing it. Something to do with the recent fix to them eating settlers?

**Comment by LoneGazebo** [comment]
Sounds like "impassibility" might be messing with yields - I'll message ilteroi as well, as he's been working on this lately.

G

**Comment by ilteroi** [comment]
i assume it's implemented via terrain impassability and a linked tech for passability? or is this a promotion?

anyway, i just today made some improvements there, will push now - please retest.

i don't have anything to do with yields though.

**Comment by LoneGazebo** [comment]
IIRC terrain impassibility returns a base value (instead of feature-added values, etc.) for tiles to save performance. We may need to remove that.

G

**Comment by ilteroi** [comment]
ok, i just remembered one thing - players can only have yields from tiles which are passable for them (because of tech or trait - ignoring unit-specific promotions).

but i other than that i don't know of any link

**Comment by ilteroi** [comment]
btw, for the commit it's essential that SaneTerrain.sql is executed, otherwise impassability won't work

**Comment by LoneGazebo** [comment]
Cool.

**Comment by Hokath** [comment]
Did you push this? I still see the issue in 12-16-1 
(also didnt mention jungle hills give 0 yields prior to passability)

**Comment by Edaka** [comment]
I'll reopen for Gazebo/ilteroi to see just in case they haven't yet.

**Comment by LoneGazebo** [comment]
Is fixed in 12-18 version.

**Comment by Edaka** [comment]
Nice.

**Comment by LoneGazebo** [comment]
Thanks! You too.

**Comment by Hokath** [comment]
This has resurfaced.
http://forums.civfanatics.com/showthread.php?t=543208&page=63
and tested myself

**Comment by LoneGazebo** [comment]
Which part?

**Comment by Hokath** [comment]
Jungles give less food than expected

Sent from Yahoo Mail on Android 
 
  On Sat, 6 Feb, 2016 at 17:27, LoneGazebo<notifications@github.com> wrote:   
Which part?
