### ISSUE TITLE
Trade routes can't originate in mountain cities

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#926]
Originally posted by Llednar Twem: 'One more bit of mountain city weirdness: They can't have trade routes. Land routes at least, I didn't have a coastal mountain to try out sea routes. [...] All I know is I definitely couldn't send caravans from my mountain cities to even very nearby city-states. I had to make another city to do that... [...]The coastal city I used instead was significantly farther away and worked fine, so the mountain cities were definitely in range. The caravans even went along the mountain roads and through those [mountain] cities on the way. Something was just preventing them from recognizing mountain cities as a viable origin or destination.'

**Comment by LoneGazebo** [comment]
I think this is fixed, but we'll see. Let's check with ilteroi.

**Comment by ilteroi** [comment]
that works now

**Comment by LoneGazebo** [comment]
When you get a chance, check to see if incan settlers can still settle on mountains for you. They cannot on my end.
