### ISSUE TITLE
Barbarian camps spawn Ancient era units in the Renaissance

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#927]
By Zares: 'What is condition for barbarians to spawn better units? I am in reneissance era and camps spawn only brutes and archers. Immortal difficulty. I clear camps regularly [...] and new spawned camps spawn only brutes and archers'

Haven't seen that myself or anybody else report it, though.

**Comment by LoneGazebo** [comment]
Sounds like a bug, but I'll keep my eyes peeled.
G

**Comment by Edaka** [comment]
Yeah, I completely forgot to add that, as it turned out, Zares was using a mod that modifies barbarians.
