### ISSUE TITLE
helicopters

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#928]
so there's one class of units i haven't tested a lot so far, and that's helis.

some facts:
- they are land units
- they can move in all terrain
- they are hovering units (what ever that means in practice)
- right now they can move on ocean tiles, is that intended?
- they end their turn when transitioning between coast and ocean (BUG)
- can stack with ships

if you notice anything odd, please post here

**Comment by LoneGazebo** [comment]
Huh. I think 'coast' moving is fine, but ocean? Huh.

Oh, hey, random, but push whatever you've got (that you are happy with), as I'd like to push a beta tonight.

G

**Comment by LoneGazebo** [comment]
Also, melee ships can't seem to attack cities at sea. That seems problematic.

**Comment by ilteroi** [comment]
fixed the ship attack and a bunch of other stuff. helis still work in progress.

pushing in 3, 2, 1 ... now!

**Comment by LoneGazebo** [comment]
Yay!

**Comment by ilteroi** [comment]
ah - one more thing - maybe reduce the minimum settle fertility to 20k or bring back the city specialization flavors in the city site evaluation. i tested both variants and finally committed a bad combination. right now AI players seem to have a hard time to find good spots.

**Comment by LoneGazebo** [comment]
Will do. I'll merge and push my changes shortly.

**Comment by LoneGazebo** [comment]
Only bug I see remaining is that all units are capable of crossing mountains. :)

**Comment by ilteroi** [comment]
guess that means that the terrain properties (SaneTerrain.sql) are not applied correctly

**Comment by ilteroi** [comment]
fyi: there seems to be something wrong with the earth map. maybe i'll have to revert some changes

**Comment by LoneGazebo** [comment]
I had added saneterrain to the manifest.

**Comment by ilteroi** [comment]
easy check: what is the defense bonus for mountains? if it's 10 there's a problem

i had a lot of trouble with the new sql file too. wouldn't load at all but i don't use modbuddy, just edited the manifest manually. so in the end i pasted the contents into another existing file and that worked, strangely. but i assume that shouldn't be a problem for you

**Comment by LoneGazebo** [comment]
Odd. I added it via onmodactivated, but it might be unhappy about something. I'll take a look.
G

**Comment by LoneGazebo** [comment]
Oh, I figured it out. It wasn't working because the WHERE directives you were using do not exist in the CP, thus the functions weren't being processed. Removing those did the trick.

**Comment by LoneGazebo** [comment]
Yep, that fixed it. New issue though: **Mountains aren't appearing on the strategic view.**

G

**Comment by ilteroi** [comment]
hehe. i guess that was the same problem which cause the crash with the earth map. just fixed it. or rather, reverted my over-enthusiastic changes from yesterday night :)

pushed!

**Comment by LoneGazebo** [comment]
Awesome. From what you can tell, are there any outstanding issues I should report? Otherwise, I'm going to wrap this up into the next beta. I'm heading out of town Friday for the holidays, and I'd love to send this out as a full version before then.

**Comment by LoneGazebo** [comment]
Test game has been running, looking pretty good thus far. Only bug I see is that great diplomats seem to no longer move to make embassies. I imagine this is an issue with plot validity.

**Comment by ilteroi** [comment]
well, aside from the helis, i think it's fine.

re: diplomats, i just rewrote that function to use the approximate pathfinding. so maybe it's solved. the report's from which version?

**Comment by LoneGazebo** [comment]
This is with the latest version. I figured it out, too. The sorting model (std::sort(vTargets.begin(), vTargets.end());) is sorting things in reverse, putting the lowest number (0) at the 'top' of the list. I flipped it, and made it not include scores of 0 in the vector. We'll see if that fixes it. This might be a systemic problem, though.

**Comment by LoneGazebo** [comment]
In fact, I'm not sure that std:sort is sorting things properly at all. After scoring all cities for a messenger, it ordered them like this:

1. 6182
2. 1
3. 4291
4. 19452
5. 2113
6. 563

That can't be right...right?

Also, saving, closing the game, and reloading creates black graphical elements underneath mountains (as if their terrain data is not being saved and loaded properly).

Sorry for the deluge!

**Comment by LoneGazebo** [comment]
Redoing those elements as weighted vectors (not using std:sort) has fixed the bug for the diplo units (they work fine now), however the std:sort method may still have problems elsewhere. Thankfully, though, I don't see any other instances in which std: sort is being used that way.

**Comment by LoneGazebo** [comment]
Lastly, this is interesting: http://forums.civfanatics.com/showpost.php?p=14093185&postcount=150

**Comment by ilteroi** [comment]
i'm pretty sure that std::sort works as designed ... only problem is i can never remember if it's ascending or descending sort, cause it depends on the content :) anyway i'll take a look.

i'll also check the reload thing, but that shouldn't block your release, right?

**Comment by LoneGazebo** [comment]
std:sort needs that third element, though, right? Right now it has no 'sorting algorithm' on the end (it's just the .begin(), .end() elements). Going to a weighted vector and using .sortitems() works, however.

It shouldn't, unless it's breaking something else. Seems I'm still having issues with the poor embassies – now the units refuse to build them once they're on the plot. The pushmission doesn't seem to be working. I'll see if I can sort it out.

G

**Comment by LoneGazebo** [comment]
Okay, figured out embassy issue, I think. isValidMovePlot breaks city-state actions of units that need to do something in the territory to function (i.e. merchants, workers, diplomats, etc.) whether or not they have open borders.

**Comment by ilteroi** [comment]
you don't need to pass a sort predicate if operator < is defined for the container elements.

anyway, good point about ignoring the open borders. i can fix it, how much time is there?

**Comment by ilteroi** [comment]
or rather, isValidMovePlot takes a parameter bCheckTerritory - just set it to false

**Comment by LoneGazebo** [comment]
I just made it ignore minor civs when it comes to territory - there should never be a time, realistically, when a player should be forbidden from entering minor civ territory. There are lots of checks outside of the playerAI where that function could limit worker or civilian behavior (i.e. diplomats).

**Comment by ilteroi** [comment]
ok, helis now can move on shallow water only, no know issues otherwise

closing this
