### ISSUE TITLE
AI can't/won't use spies in Community-Patch-only

### ISSUE THREAD

**Issue by Tesla101a** [LoneGazebo/Community-Patch-DLL#9280]
_1. Mod Version (X.Y.Z). Using 2.6.  Current Version: 2.7.3_

Using only the community patch, not 43-civs, not balance patch, just CP.

_2. DirectX Version_

DX11

_3. List of Other Mods_

InfoAddict 22
Communitas Map 1.4.4
Quick Turns 10

_4. Describe the Issue_

The AI does not seem to use their spies at all anymore, or they are only using them to defend against enemy spies.  I'm not sure which version is began, it was either 2.6 or 2.5 when it started.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

I can build and upload one if it's absolutely necessary, but the problem is easy to reproduce, it's happened in each one of my games even with stripped down mods.

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Easy to reproduce, just play a game with AI on Community Patch only.

_9. Screenshots of the Issue (Optional)_
If you need anything else please let me know.

**Comment by axatin** [comment]
There was a similar issue some versions ago: #8972. Maybe this one is related to it?

**Comment by LoneGazebo** [comment]
I can't reproduce this, can a plucky user provide a save for me?
