### ISSUE TITLE
Ceremony policy from Tradition doesn't give council and herbalist extra science

### ISSUE THREAD

**Issue by TU116** [LoneGazebo/Community-Patch-DLL#9283]
_1. Mod Version (X.Y.Z). Current Version: 2.7.3_

2.7.3

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

^Title. Other buildings/policies may also be affected.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by pineappledan** [comment]
This is the same issue reported by an older ticket:
https://github.com/LoneGazebo/Community-Patch-DLL/issues/9265
