### ISSUE TITLE
Parthenon and Grand Temple do not seem to grant extra yields to Amphitheaters and Temples

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#9286]
_1. Mod Version (X.Y.Z). Current Version: 2.7.3_

_4. Describe the Issue_
Parthenon and Grand Temple do not seem to be giving extra yields to Amphitheaters and Temples, respectively (or at least they are not shown in the CityView tooltip).

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[missing_yields.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9767939/missing_yields.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9767945/Logs.zip)

_8. Steps to reproduce the Issue (Optional)_
For the Grand Temple to finish in Vienna, hit End Turn. Then go to Vienna and look at tooltips for Temple and Amphitheater.

_9. Screenshots of the Issue (Optional)_
<img width="960" alt="no_gold_faith_from_Grand_Temple" src="https://user-images.githubusercontent.com/620131/195425707-c1e16f7f-83d5-4f5b-a2d8-c265762a5e83.png">
<img width="960" alt="no_science_on_Amphi" src="https://user-images.githubusercontent.com/620131/195425739-d99dc6ab-1c3f-4db9-960b-f9548890ed69.png">

**Comment by bsesar** [comment]
Following a comment on the forum, I sold the Amphitheater and Temple in Vienna and the yields decreased as if there was no Parthenon or Grand Temple. In conclusion, this does not seem to be just an UI issue.

**Comment by pineappledan** [comment]
This is the same issue reported by an older ticket:
https://github.com/LoneGazebo/Community-Patch-DLL/issues/9265
