### ISSUE TITLE
Encampment tooltip update

### ISSUE THREAD

**Issue by Zuizgond** [LoneGazebo/Community-Patch-DLL#9290]
Version: 2.7.3

Minor issue but tooltips (tile + tech tree) for encampments have not been updated with latest changes (Encampment gains +1 Food at Drama and Poetry, +1 Science and +1 Production at Advanced Ballistics).

**Comment by LessRekkless** [comment]
Seems like an EUI bug? Can you show a screenshot of what you mean?

**Comment by Zuizgond** [comment]
From the patch note : 
 - Encampment gains +1 Food at Drama and Poetry, +1 Science and +1 Production at Advanced Ballistics

Those additional yields don't show up in the tooltip : 

![20221017195027_1](https://user-images.githubusercontent.com/64471766/196248292-194d6e4b-de59-47fb-8cfa-adfd8f55c60c.jpg)
![20221017195043_1](https://user-images.githubusercontent.com/64471766/196248300-904ddd46-9180-484f-a0ed-9127040c5cee.jpg)

![20221017194904_1](https://user-images.githubusercontent.com/64471766/196248285-18a61f5d-6c98-4bf1-a2ca-71903b5fff36.jpg)
As far as I understand, Advanced Ballistics should show +1 food +1 prod +2 science.

**Comment by LessRekkless** [comment]
The patch notes are incorrect; Drama and Poetry gives +1 production, Advanced Ballistics gives +1 science, +1 food.

I don't know why EUI is not showing the Drama and Poetry bonus; perhaps it's locked to only showing 7 items max.
