### ISSUE TITLE
AI and Great Diplomats

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#930]
Another one from Kolaris: "Also seeing an issue with AI Great Diplomats. They wander aimlessly about for hundreds of turns. I know I've seen them use Embassies before, but in 12/10 at least I haven't seen one. "

**Comment by Kolaris8472** [comment]
Also, r.e. the AI using them on the Influence Mission, if there's a notification to the player that your Influence has been lowered in that way, I've never received one. So I don't think they're being used at all.

**Comment by LoneGazebo** [comment]
I've fixed them. Plot data changes had an adverse effect on civilian missions like these.

Re: notification, there is not one for all players, but I can add one if desired.

**Comment by Edaka** [comment]
A notification would be nice. There have been situations where I got my influence with a CS dramatically dropped for seemingly no reason (no failed quests or anything like that). It takes some time and game knowledge to realise that's due to someone's great diplomat.
