### ISSUE TITLE
Pathfinder +0 XP when exploring in early game

### ISSUE THREAD

**Issue by mrobaczyk** [LoneGazebo/Community-Patch-DLL#9312]
_1. Mod Version 
2.7.3

_3. List of Other Mods_
VP EUI Promotion Icons

_4. Describe the Issue_
When exploring with Pathfinder in the beginning of a game, there is a floating text +0 XP. This looks wierd. Maybe it should display 1 decimal place after 0.

_9. Screenshots of the Issue (Optional)_
![image](https://user-images.githubusercontent.com/35763893/196637134-4af28e7a-0404-445a-b328-8debc20bfc50.png)

**Comment by azum4roll** [comment]
Playing on Quick speed?

**Comment by mrobaczyk** [comment]
Yes, possibly.
