### ISSUE TITLE
Culture UI:  Cicus Maximus

### ISSUE THREAD

**Issue by phantommaxwell** [LoneGazebo/Community-Patch-DLL#932]
The +10% from Circus Maximus is not showing up here.  The other modifiers are from Marble Monopoly and Sistine Chapel.  It is being Calculated in properly though, 1.35 * 66 =89.1.

Could it be because of my Resolution?  It's 1366 X 768.

![2015-12-14_00011](https://cloud.githubusercontent.com/assets/11430209/11818512/c58e21a0-a328-11e5-9e4b-6f845e738d5d.jpg)

**Comment by LoneGazebo** [comment]
No, it's simply a missing UI element. Will fix.
