### ISSUE TITLE
2.7.3 - Steal gold mission does not show how much gold is stolen

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#9329]
_1. Mod Version (X.Y.Z). Current Version: 2.7.3_

2.7.3

_2. DirectX Version_

_3. List of Other Mods_

[Other Mods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9845242/Other.Mods.zip)

_4. Describe the Issue_

![image](https://user-images.githubusercontent.com/20593976/197362023-ee94d075-823c-4381-8657-21d0f4f41201.png)

When this mission completes, there is nothing that tells you how much gold you acquired. Its neither on this notification or any others.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
This should also

**Comment by axatin** [comment]
The same problem exists when an enemy spy action is completed in an owned city

**Comment by LoneGazebo** [comment]
Is the value showing up in the events overview? I'm fairly certain this value passes through to the notification, but apparently not.
