### ISSUE TITLE
Request: Specific Trait to allow all military units to build an Improvement

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#933]
Ref:
http://forums.civfanatics.com/showthread.php?t=559617

I know you are getting slim on additions to the DLL, but I was wondering if I could make this request. I know there are a couple of ways to make this work, but I'm not satisfied by them, nor do I find them very clean. Is it possible you can create a table: Trait_UnitCombatBuildImprovement or Trait_UnitClassBuildImprovement (TraitType,UnitCombatType/UnitClassType,BuildType,WorkRate)

I know there is still the issue of Unit_Flavors and Unit_AITypes. Perhaps those can be hardcoded in with definite values, as long as they don't succeed the Combat duties.

Let me know if this doable or possible. As always, thank you.

**Comment by LoneGazebo** [comment]
I don't think you need this - you can assign all unit combat types a promotion (like the Iroquois, for example), and then use the promotion style (like the samurai) that lets them build improvements.

**Comment by Iamblichos** [comment]
Well the Samurai doesn't have a promotion that grants it the ability to build it just has worker actions like Unit_Builds (UnitType,BuildType) and it has a WorkRate value under Units that gives it the ability to build fishing boats. Moreover, I don't see how a PromotionType will grant the ability to build, unless I'm missing something. I'd also like to avoid giving all military units of all civs a (false) workrate and Unit_Build just to make it work. As I noted in that thread, that's not very clean.

**Comment by LoneGazebo** [comment]
Nope, misunderstood what you were asking. I'll take a look, but there's a lot of underlying AI elements in that which I am not terribly keen on dealing with.

G

**Comment by Iamblichos** [comment]
Just to note and FYI: right now I have the Mongolian Keshik and Khan building a Yurt improvement (unique to Mongolia), gave those two units Unit_Builds assignment and a WorkRate, also assigned them a Unit_AITypes and Unit_Flavors for respective tile (worker) tile improvements, kept the values low on Flavor so they would build the improvements while not at combat, and it seemed the AI did perform this. Looking to extend this behavior to all land units of Mongolian Trait. So I think it can work.

**Comment by LoneGazebo** [comment]
Done. I can't guarantee that the AI will perform properly (I've looked and adjusted what I need to), but the table exists:

	
	<Table name="Trait_BuildsUnitClasses">
		<Column name="TraitType" type="text" reference="Traits(Type)"/>
		<Column name="UnitClassType" type="text" reference="UnitClasses(Type)"/>
		<Column name="BuildType" type="text" reference="Builds(Type)"/>
	</Table>

**Comment by Iamblichos** [comment]
You da man! I'll let you know how it goes!

**Comment by LoneGazebo** [comment]
Note that if you don't set a workrate, the unit defaults to 100  (which is same as standard worker). If you want this in a define, I can do that later.

G

**Comment by LoneGazebo** [comment]
Table is included in new version.
