### ISSUE TITLE
Issues with the 12/15 beta

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#934]
Taken from the forum:
*Ocean and coast tiles have no yields and can't be entered on by ships;
*Lakes yield 1 food, 1 production;
*Mountains yield 1 food, 1 production.
I think these should have been solved by the hotfix, but I can't start civ up to confirm. The first one is reported to be gone, but I don't know about the other two. 

So far, his one seems to persist throughout the hotfix:
*Workboats can't create fishing boats - they lack the promotion.

**Comment by LoneGazebo** [comment]
Thanks! On it.

**Comment by ilteroi** [comment]
ok, anything i can help you with? didn't do anything to the work boats, but i suspect terrain/movement issues are mostly my fault ...

**Comment by LoneGazebo** [comment]
I think I've got the terrain stuff sorted - it's mainly an issue of how TERRAIN_COAST and TERRAIN_OCEAN are treated (the DLL is not kind to them). I'll upload my fixes (so that the mod functions) and then push to github. They probably won't be beautiful, but that's where you come in. :)

Right now I'm frustrated with the EUI stuff, as it seems every release is less and less mod-friendly (which is utterly bizarre, if you think about it).

**Comment by ilteroi** [comment]
yeah, it's funny / sad - without EUI my usual crashes with communitas map and simple restart of the game (via main menu) are gone.

it does have it's upsides though - most importantly the build queue :) maybe simply stay with an old version? which one was best?

**Comment by ilteroi** [comment]
btw, i have another update as well, finished the cleanup of the movement logic and fixed helis.

don't know if you would want it though, i guess risk-minimization is the word of the day

**Comment by LoneGazebo** [comment]
Hehe no worries. And yeah, EUI is a buggy mess in some ways. I'll include your fixes (might as well) - this is a beta version, after all. :)

**Comment by LoneGazebo** [comment]
Also, check out the followers issue - since your trade code was the last to touch it, I feel it might be related to that.

**Comment by Iamblichos** [comment]
Regarding EUI, I DO like the layout of the GameSetupScreen and LoadScreen LUA's (all those LUA's in the GameSetup folder), as it makes it easier to read my work-in-progress mod with more than 2 components (and extra Trait text), where my civs have 6 components. The rest I can really live without.
