### ISSUE TITLE
2.7.3 - Trireme can't cross 2 spaces of Ocean even with coast in sight

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#9341]
_1. Mod Version (X.Y.Z). Current Version: 2.7.3_

2.7.3

_2. DirectX Version_

_3. List of Other Mods_

[Other Mods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9861612/Other.Mods.zip)

_4. Describe the Issue_

This trireme have the movement to cross this spot of ocean and get to the coast that is in sight. Yet it is forbidden from this movement.
![image](https://user-images.githubusercontent.com/20593976/197813228-2ddd9d61-dac8-4b4f-9b95-1340754f3c08.png)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
I think this is intended. The coast tile is not in sight for the trireme, which only has a visibility range of 2.

**Comment by Stalker012345** [comment]
might just need a tooltip update then. The tooltip doesn't say the coast needs to be in active sight of the unit, just that its there. so it makes you think a revealed tile would be enough.

**Comment by LessRekkless** [comment]
This has always been the case.  You don't know if that time is blocked.

**Comment by LessRekkless** [comment]
I don't think a tooltip change is necessary.

**Comment by LessRekkless** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/blob/5ba7fe02bccb7f504d7fc9f6a319058360a57c18/(1)%20Community%20Patch/Core%20Files/Text/CoreText_en_US.sql#L128-L130
https://github.com/LoneGazebo/Community-Patch-DLL/blob/5ba7fe02bccb7f504d7fc9f6a319058360a57c18/(1)%20Community%20Patch/Core%20Files/Text/CoreText_en_US.sql#L140-L142
https://github.com/LoneGazebo/Community-Patch-DLL/blob/5ba7fe02bccb7f504d7fc9f6a319058360a57c18/(2)%20Vox%20Populi/Balance%20Changes/Text/en_US/PromotionText.sql#L524-L526

Replace
```
May move through Ocean Tiles if ending on a Coastal Tile.
```
with
```
May move through *visible* Ocean Tiles if ending on a *visible* Coastal Tile.
```
\*emphasis\* mine, not for code.
