### ISSUE TITLE
2.7.3 - United Nations tooltip says "when reach Atomic Era", but actually required Information Era

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#9353]
_1. Mod Version (X.Y.Z). Current Version: 2.7.3_

2.7.3

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

You must reach the Information Era (and have the UN policy pased) to truly activate the United Nations. However, the popup note about the UN says Atomic Era.

![image](https://user-images.githubusercontent.com/20593976/198353782-11085bc6-f34e-48b7-8282-3cf6721afec6.png)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
As discussed on Discord, this is actually unintended. The only requirement for the UN to start should be that the wonder is built. The era requirement should be removed

**Comment by LessRekkless** [comment]
whoops, didn't notice that the merge was just a text update.
