### ISSUE TITLE
2.7.3 - Laborer Food Tooltip is Inaccurate

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#9370]
_1. Mod Version (X.Y.Z). Current Version: 2.7.3_

2.7.3

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

The laborer's tooltip shows its yields and shows that it consumes 2 food.

![image](https://user-images.githubusercontent.com/20593976/198897538-b6b4a73b-d07f-4e49-9b2e-716fda7ae439.png)

However, considering that the specialist dropdown shows a very similar number but actually means "this much food ABOVE the normal 2 food cost of a person", it creates confusion.

![image](https://user-images.githubusercontent.com/20593976/198897577-9f1f9e3b-f4a5-4af1-8cae-b6f48dda4d62.png)

In this example, the user is lead to believe that switching a laborer to a merchant would meerly cost an extra .5 food (2.5 vs 2). However, this is not true, the merchant costs a full 2.5 food MORE than the laborer.

The simplest fix to remove the -2 food cost for the laborer, showing that it costs the same amount of food as a regular citizen, and nothing "above and beyond"

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by LessRekkless** [comment]
Did you mean to take a screenshot of the laborer tooltip? The first one is of a civil servant, and the second one is of a merchant.

**Comment by Stalker012345** [comment]
> Did you mean to take a screenshot of the laborer tooltip? The first one is of a civil servant, and the second one is of a merchant.

yes I did. the laborer in this example has -2 food in its tooltip.

**Comment by azum4roll** [comment]
> In this example, the user is lead to believe that switching a laborer to a merchant would meerly cost an extra .5 food (2.5 vs 2).
But this is true. The merchant only eats 0.5 more food than a normal citizen/laborer.
