### ISSUE TITLE
puppet city doesn't build anything

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#9373]
_1. Mod Version = 2.7.3

_3. List of Other Mods_
Promotion Flags EUI for VP (v 4)
InfoAddict (v 22)
UI - Small Resource Icons (v 4)
UI - Military Log (v 2)

_4. Describe the Issue_
Puppet city (Osaka) doesn't begin any new production after monument completes.
Played one more turn after that (to t66), and the queue was still empty.

_5. Save Game From 1 Turn Before
[asdBoudicca_0064 BC-1440.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9897327/asdBoudicca_0064.BC-1440.zip)

_8. Steps to reproduce the Issue (Optional)_
End turn.

**Comment by LessRekkless** [comment]
Puppets only build defensive buildings and buildings from eras ago, and instead work processes in order to save on gold

**Comment by gamask** [comment]
a) How did it build a monument?
b) It's not working any processes either.

**Comment by azum4roll** [comment]
Intentional for the version back then; logic may have changed nowadays.
