### ISSUE TITLE
Friendly/allied city states don't enter player's territory

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#938]
Gidoza noticed that city states are hesitant to enter your territory, even those who you are friendly or allied with. Are they not allowed to do so in the code? I guess it might as well be an anecdotal observation, but it's probably worth keeping an eye on in case that's not an intenhded behaviour.

**Comment by Kolaris8472** [comment]
Adding one more to anecdotal evidence. I noticed that behavior in 12-10b.

**Comment by LoneGazebo** [comment]
Probably an issue with allied CSs not having open borders.
