### ISSUE TITLE
CTD on next turn

### ISSUE THREAD

**Issue by AndreyK-555** [LoneGazebo/Community-Patch-DLL#9380]
_1. Mod Version (X.Y.Z). Current Version: 2.7.3_

_2. DirectX Version_

_3. List of Other Mods_

MUCfVP v83, pdansUnitTweaks v43, Civ4 Traits VP v7, New Beliefs Mod, Leugi's Israel for VP, IGE+ v43, Manchus for VP v4, MWfVP v0.16.1, EE(VP) v4 for VP2.0 , UCS v 10, Goldsmith for VP v4, DMS Corsica for VP v 10, Refestation for VP v4, GH Scotland f VP v 12, SMAN's Brittany for VP v8, Better Lakes for VP v 2.3, Monopoly Buildings for VP v3.4, Tree Growth (VP) v2, Quick Turns v10, RemoveBanLuxury v1, RAS v15, Resource - Granary Includes Bison v3, Wonder Race v7, ENW f VP v2.1, EAW f VP 1.9, Ski Resort Building for VP (v 2.1), Sixth Policy VP, Cemetery Building 4VP (v 1), Parks for Vox Populi (v 2), Casino Building 4VP (v 1.0), GMO Laboratory Building 4VP (v 1), Polar Station 4VP (v 1.0), Recruitment Office Building 4VP (v 3), Clock Tower Building (v 1.1), Capture Great People for VP (v 3), UI - Improved City View (Vox Populi EUI) (v 14)

_4. Describe the Issue_

By the end of Renaissance , before EE, I get CTD, tried to load couple turns before, clear cash. I get CTD after all AI's turns, CS turns after I start getting yields.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Wu Zetian_0303 AD-1415.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9909443/Wu.Zetian_0303.AD-1415.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/9909492/Database.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/9909495/xml.log)
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/9909496/Lua.log)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by AndreyK-555** [comment]
[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9909659/CvMiniDump.zip)

**Comment by axatin** [comment]
can you upload a zip-file of all those mods?

**Comment by ilteroi** [comment]
too many mods and very old
