### ISSUE TITLE
False diplomatic response trigger from AI

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#939]
Don't know if you've seen this. Posted by Kolaris: "Just founded the World Congress in 12-10b and I have AIs coming up to me and saying I helped their resolutions fail even though we haven't voted on anything yet. There's no diplo penalty though (transparent diplomacy)."

A little note aside: I think the last time I played I also got a demand not to settle any more cities near an AI when, in fact, it was her (Dido) that plopped a new city after me near a city of mine. I guess my city was also pretty freshly found (it was there for maybe a couple or another turns before Dido came), so maybe that information wasn't refreshed timely somehow?

**Comment by LoneGazebo** [comment]
For former: I'll take a look.

For latter: the AI can tell you this if your border relationship changes, whether or not you were the most recent one to settle.

G

**Comment by Edaka** [comment]
Oh wow, what a way for the AI to be an ass! (: Well, I'm glad that at least it's working as intended.

**Comment by LoneGazebo** [comment]
heh, yep, but players do it too :)

**Comment by LoneGazebo** [comment]
Can't reproduce voting quirk. If someone gets a save for it, post it here.

**Comment by Kolaris8472** [comment]
I'll keep an eye out
