### ISSUE TITLE
Broken UI - Problem with Lua codes

### ISSUE THREAD

**Issue by Nersia** [LoneGazebo/Community-Patch-DLL#9395]
_1. Mod Version (X.Y.Z). Current Version: 2.7.3_
 VP-EUI

_2. DirectX Version_
 10 & 11

_3. List of Other Mods_
 no other mods

_4. Describe the Issue_
 There are multiple problems, I can't see buildings info in construction menu, I can't open policy menu therefore can't adopt policy at all, State-city action buttons seems to be unfunctional; I can't pledge to protect them or ask for tribute. Everything works when I disable EUI. I uploaded both 3.a and logs folders.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
 
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/9969767/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![State](https://user-images.githubusercontent.com/85186113/200798903-25d10bed-7abe-430c-be28-0a1dda1762f8.PNG)
![Building](https://user-images.githubusercontent.com/85186113/200800405-1ae041a4-87a7-40ef-b043-757b89b6a5f9.PNG)

**Comment by bsesar** [comment]
Seems like an EUI problem. Check this out

https://forums.civfanatics.com/threads/new-version-2-3-1-june-1-2022.677139/post-16284129

or search for "UI_bc1" on the forum.

**Comment by Nersia** [comment]
> Seems like an EUI problem. Check this out
> 
> https://forums.civfanatics.com/threads/new-version-2-3-1-june-1-2022.677139/post-16284129
> 
> or search for "UI_bc1" on the forum.
If I install EUI alone it works just fine, but the version from VP installer has these problems

**Comment by n-core** [comment]
![image](https://user-images.githubusercontent.com/110832881/201540201-433ee57b-41ac-40dc-a828-c6a6aa95c1ca.png)
![image](https://user-images.githubusercontent.com/110832881/201540204-db53bc7c-eda4-4d6d-86e6-8b0fa3687ec6.png)
It's probably a map issue. IIRC many vanilla maps don't work with current VP.

Also, Random Africa Map isn't included with the fix.
3a50365f058ffd77e58e971911a92b04482c372f
