### ISSUE TITLE
Musketman keeps "Siege Valleys" promotion from Cho-ku-nu

### ISSUE THREAD

**Issue by alchx** [LoneGazebo/Community-Patch-DLL#9398]
_1. Mod Version (X.Y.Z). Current Version: 2.7.3_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

This is an extremely powerful unit. Deals 40 damage to another musketman and 5 more to all neighbors. 

![20221110081022_1](https://user-images.githubusercontent.com/116918964/201022034-c6be2ea8-536b-459c-8c99-222503e05298.jpg)

**Comment by LessRekkless** [comment]
If you want it to do something different, bring it up as a balance change proposal in VP Congress.
