### ISSUE TITLE
Warmonger penalties for acquiring city states with the Merchant of Venice

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#940]
By Steelrat: "I've been playing for Venice and got warmonger penalty for buying city-state."

**Comment by LoneGazebo** [comment]
That's normal, as it counts as conquest (which it is).

**Comment by Edaka** [comment]
Huh, I never even realized it was there. Seems rather counterintuitive to me, but that's better discussed on the forum. Thanks for clarifying!
