### ISSUE TITLE
CvUnit::isEnemy(...)

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#9407]
can somebody fix this please? i cannot make sense of it. i believe it's buggy or at least very easy to misuse.

the unit has an owner.
there is a given team.
the plot has an owner.

who is supposed to be whose enemy?
what does getCombatOwner() do?

total mystery but it's used in a lot of places ...

```
bool CvUnit::isEnemy(TeamTypes eTeam, const CvPlot* pPlot) const
{
	VALIDATE_OBJECT
	if(NULL == pPlot)
	{
		pPlot = plot();
	}

	if(! pPlot)
	{
		return false;
	}
	return (atWar(GET_PLAYER(getCombatOwner(eTeam, *pPlot)).getTeam(), eTeam));
}
```

**Comment by LessRekkless** [comment]
Let's take some steps:
- we are asking if this unit is at war with eTeam
- *pPlot is _only_ used for `CvUnit::getCombatOwner()`

`CvUnit::getCombatOwner()` is the same as `CvUnit::getOwner()`; it only cares about pPlot when the following is true:
- the "potential enemy" team isn't NO_TEAM
- the "potential enemy" team isn't this unit's team
- the "potential enemy" team isn't the barbarian team

If that's the case, then we check if the unit has the IsAlwaysHostile promotion and is not in a city (this is where pPlot is used).  If the unit has the IsAlwaysHostile promotion, then we return BARBARIAN_PLAYER as the owner.

That is:
If the unit in question has the IsAlwaysHostile promotion and isn't targeting a city, then this function returns true, ie. the unit treats every other unit not on its team as an enemy and can attack it.

**Comment by LessRekkless** [comment]
in effect, `getCombatOwner()` is asking if, for the purposes of targeting, the unit is effectively owned by the Barbarian player.

**Comment by ilteroi** [comment]
thanks but this is still confusing as hell ... what is the usecase?

**Comment by LessRekkless** [comment]
The AlwaysHostile promotion exists in the base BNW code.  I assume it was meant to be used in some scenario.

**Comment by ilteroi** [comment]
ok, it begins to make sense but the naming is still extremely poor and i'm quite sure there are lots of places in the code where this AlwaysHostile/FakeBarbarian flag is not considered ... question is what to do about it though.
