### ISSUE TITLE
 mountain tiles are black in strategic view after reload

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#941]
in the latest versions, i force the terrain to be mountain if the plot type is mountain after map generation.

this is because properties like yields, impassability etc are linked to the terrain. and unfortunately map scripts are a bit inconsistent, producing mountain plots with e.g. plain terrain.

so my theory is that there simply is no defined texture for mountain terrain. do you have any idea how to check this?

**Comment by LoneGazebo** [comment]
I think you are looking for the ArtDefine_StrategicView table. Looking at it, there's no SV texture for mountains. You could add one. Try:

INSERT INTO ArtDefine_StrategicView (StrategicViewType, TileType, Asset)
SELECT 'ART_DEF_TERRAIN_MOUNTAIN' , 'Terrain' , 'Sv_TerrainHexGrasslands.dds';

**Comment by LoneGazebo** [comment]
This works, btw.

**Comment by ilteroi** [comment]
excellent. closing this then

**Comment by LoneGazebo** [comment]
Sounds good. It is in the latest version. I'll upload all of it later today.

**Comment by ilteroi** [comment]
yeah i just pushed. too late for today's release but no matter. have a good trip

**Comment by LoneGazebo** [comment]
I'll probably push a full version tomorrow, barring any game-breaking bugs! We've been moving at a breakneck pace lately, so the breather is welcome!

Also, did you see this? http://forums.civfanatics.com/showpost.php?p=14094439&postcount=157

I think this may be the culprit. Makes a lot of sense.
