### ISSUE TITLE
build warning for addFinishMovesIfAcceptable: not all control paths return a value

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#9415]
@ilteroi 
![7b7f35527803f875e308861cfdd5aad6](https://user-images.githubusercontent.com/66801010/202832084-ebe94012-905b-4bd6-a8ff-6c7430145c99.png)

**Comment by ilteroi** [comment]
uh, how did i miss that. anyway just add a 'return true;' add the very end
