### ISSUE TITLE
Wrong description of chopping production

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#9417]
_1. Mod Version: 2.7.3_

_4. Describe the Issue_

Bronze working and iron working both say "+50% production from chopping forests/jungles (+25)".
Nothing about this is correct.
Initial value before bronze working is 0, so +50% doesn't make any sense.
The absolute value is also wrong.
After bronze working you get 20. After iron working you get 40.

If possible, it should also be noted somewhere that the automatic chop you get when you build a city on forest/jungle gives half the value.
Perhaps on the tooltip of the build city button on settlers and friends.

**Comment by nobubblegums** [comment]
OH! Thanks for checking this, I noticed something was wrong but didn't go into the actual values.

**Comment by nobubblegums** [comment]
Just tested in-game, indeed you don't get any production before bronze. BuildFeatures table suggests you should get 40, and I always thought it worked that way, smells like a bug

**Comment by nobubblegums** [comment]
https://github.com/LoneGazebo/Community-Patch-DLL/pull/9422#event-7871785137
