### ISSUE TITLE
Cities starve immediately upon completing settler production

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#943]
Safety report coming in (:
By Funak: "It is a weird side-effect of the food being counted after the production now, so your city can starve the same turn as it finishes the settler."
Gidoza: "I have a city that has 3 population points, but 4 citizens available to work tiles. I built a settler, and the same turn the settler finished, the city starved - only lost population, but not citizens. [...] I can't seem to get it beyond more than 1 ahead, however, I can do the 1 ahead consistently."

**Comment by Edaka** [comment]
I've just realised that this thread depicts two bugs - one being losing population immediately after finishing a settler and being able to work more tiles than you have citizens after some have starved. Gazebo, apparently you've fixed the former, but have you looked at the latter? Some are still reporting the issue: http://forums.civfanatics.com/showpost.php?p=14100129&postcount=4089

**Comment by LoneGazebo** [comment]
I'll look. Technically the starvation code is untouched, but there must be something about the reordering that caused this.
