### ISSUE TITLE
Cargo ships unable to trade with other nations...

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#944]
I started a game with Carthage, and was trading very well with my own cities, and with city states that were halfway around the map, but I could not trade with other players' cities that were much closer. This was before the world concil was founded.

**Comment by Edaka** [comment]
Could you provide a screen please? It'd be easier to see the cause.

**Comment by AnastaseAlex** [comment]
Reloaded, could not reproduce.
