### ISSUE TITLE
Puppet city with courthouse???

### ISSUE THREAD

**Issue by AnastaseAlex** [LoneGazebo/Community-Patch-DLL#945]
![image](https://cloud.githubusercontent.com/assets/5359131/11870650/f1364b50-a4c9-11e5-84a6-b53e1a23eb85.png)

**Comment by LoneGazebo** [comment]
Was it owned by someone else at some point?

**Comment by AnastaseAlex** [comment]
yes, persia. I just find bizzare that the building stays after conquest

**Comment by LoneGazebo** [comment]
There's a chance of it staying, yep.
G

**Comment by AnastaseAlex** [comment]
In which case going at war with Persia somehome looses the negative of having to build a courthouse? The second and third city I captured also had a courthouse...
