### ISSUE TITLE
3.0.2 - Cannot shift tile ownership away from a puppet

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#9463]
_1. Mod Version (X.Y.Z). Current Version: 3.0.3_

3.0.2

_2. DirectX Version_

_3. List of Other Mods_

[Other Mods.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10096620/Other.Mods.zip)

_4. Describe the Issue_

![image](https://user-images.githubusercontent.com/20593976/204098697-bc828904-e136-4ee4-853b-d15b990f9169.png)
I cannot move this academy tile ownership so that my capital can work on it. I believe the issue is the puppet to the south, which will not let this tile go.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0197 AD-1370.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10096621/AutoSave_0197.AD-1370.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs - Copy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10096623/Logs.-.Copy.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by ilteroi** [comment]
only venice can do that

**Comment by LessRekkless** [comment]
If you want to steal a city's tiles, annex it.
