### ISSUE TITLE
No resources on Highlands map

### ISSUE THREAD

**Issue by reedtanguerra** [LoneGazebo/Community-Patch-DLL#9464]
_1. Mod Version (X.Y.Z). Current Version: 3.0.3_

Vox Populi 3.0.3 with EUI

_2. DirectX Version_

_3. List of Other Mods_

Trade Opportunities for VP (v12)
Wonder Planner for VP (v12)

_4. Describe the Issue_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10096766/Logs.zip)
[Pachacuti_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10096769/Pachacuti_0000.BC-4000.zip)

Highlands map does not spawn any resources. I managed to get 1 wheat tile to spawn with the Legendary start map option, but otherwise nothing over the entire map. I haven't exhaustively checked all of the other maps, but all the other ones I checked, including Boreal & Terra which are the other two with map script changes, all spawn resources with no apparent issues.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Load new game on Highlands map.

_9. Screenshots of the Issue (Optional)_

**Comment by azum4roll** [comment]
![Image](https://user-images.githubusercontent.com/14953746/204120661-be184bd9-b51b-40a7-9546-6c35c760af40.png)
There were definitely resources...

**Comment by reedtanguerra** [comment]
I gave you my save game. Are you telling me that you booted that up and resources actually appear on the map? If so, great, are you aware of anything that would prevent the resources from appearing on screen? Once again, VP appears to be functioning as intended on other maps.

**Comment by azum4roll** [comment]
You uploaded the turn 0 save. Only farm resources and bananas are visible on turn 0.

**Comment by reedtanguerra** [comment]
No, on every other game I've played on other maps, I can see the luxury resources like incense, gold, silver etc. I may not have the tech to use them, but I can see them.
