### ISSUE TITLE
Unable to see available trade routes

### ISSUE THREAD

**Issue by jdoug312** [LoneGazebo/Community-Patch-DLL#9468]
_1. Mod Version (X.Y.Z). Current Version: 3.0.3_

3.0.3

_2. DirectX Version_

11

_3. List of Other Mods_

VP (1, 2, 3a, 4a, 4b)
Community Events v7
Israel for VP v17
EAW v1
Ainu People for VP v15
Scotland for VP v13
Tlingit for VP v18
Aircraft Command Group v1
Inuit for VP v19
Ethnic Diversity
ENW v2
Great Profit Historical Names v31
JFD Norway for VP v4
Kushan Empire for VP v2
Manchu for VP v13
Nubia for VP v19
Chola for VP v8
Phoenician Civ v5
Quick Turns v10
Civ 6 styled names v1
Benin for VP v5
Sumer for VP v24

_4. Describe the Issue_

I'm on a continent with 4 other civs. I built a caravan but I'm unable to establish a trade route with any civ, city state, or my own cities. I checked the "Routes available" in the trade overview and I see a lot of trade routes I should be able to create. Other civs are sending trade routes to me, but I cannot send any in return. I checked to see if the drop-down for routes was collapsed, but it is not; they are all expanded.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[caravan issue.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10097295/caravan.issue.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[3.0.3 logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10097297/3.0.3.logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump (2).zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10097303/CvMiniDump.2.zip)

_8. Steps to reproduce the Issue (Optional)_

Try using a caravan to create a trade route. If using the save file I'm going to attach, I have a caravan already built, and a fresh one that'll be built next turn

_9. Screenshots of the Issue (Optional)_
![20221126_195148](https://user-images.githubusercontent.com/19598149/204114463-5d95ecc5-e644-4ba1-874b-a992fea1afe4.jpg)
![20221126_195158](https://user-images.githubusercontent.com/19598149/204114470-5074d920-7df8-4422-a7dc-b0da8f0826c6.jpg)
![20221126_195213](https://user-images.githubusercontent.com/19598149/204114476-46345586-aa5f-4afc-a283-cea06f47fe06.jpg)
![20221126_195229](https://user-images.githubusercontent.com/19598149/204114477-8b9c2247-3ae0-479b-a341-a8ebe666008a.jpg)
![20221126_195236](https://user-images.githubusercontent.com/19598149/204114478-06ad35d7-2726-4155-9019-04eb81a35355.jpg)

Will send in a sec

**Comment by jdoug312** [comment]
Just found a workaround; when I open the trade overview there's a little button on the far left column under the trades available section that allows me to send trade routes

**Comment by pineappledan** [comment]
This looks like a Chola mod issue. Chola overwrite the trade menu UI, but it’s probably deprecated with the new version

**Comment by jdoug312** [comment]
You're right, I just started a new game without Chola loaded and the issue is gone. Thanks!
