### ISSUE TITLE
what's up with venice?

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#947]
did i miss something? are they allowed to settle now?

![image](https://cloud.githubusercontent.com/assets/1358966/11871689/684610d4-a4d1-11e5-9509-496e2a4f60e8.png)

**Comment by LoneGazebo** [comment]
Huh.

**Comment by LoneGazebo** [comment]
Did the Venice AI capture a minor civ, maybe?

G

**Comment by ilteroi** [comment]
don't think so, this was about turn 50 or 60

**Comment by LoneGazebo** [comment]
Huh.
