### ISSUE TITLE
Two land military units in a fort

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#9476]
_1. Mod Version (X.Y.Z). Current Version: 3.0.3_

_4. Describe the Issue_
Somehow two land military units ended up in the same fort (composite bowman and a scout). The composite bowman cannot fire unless moved out of the fort. I believe the next turn one of them gets kicked out automatically.

_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
I've attached the save that shows the two units in the same fort and the Autosave from the beginning of that turn.
[crowded fort.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10099071/crowded.fort.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10099073/Logs.zip)

_8. Steps to reproduce the Issue (Optional)_
Honestly, I don't know how the two units ended up in the same fort.

_9. Screenshots of the Issue (Optional)_
<img width="960" alt="two_military_units_in_a_fort" src="https://user-images.githubusercontent.com/620131/204156376-37758bb4-c97d-4d06-9036-ed0d05f5c33b.png">

**Comment by pineappledan** [comment]
Will it allow you to end a turn? The game allows you to have stacked units during your turn. but should ask you to unstack them before your turn is over.

**Comment by bsesar** [comment]
@pineappledan It's been awhile, but from what I remember I had to move the unit to end the turn.

**Comment by pineappledan** [comment]
Okay, that’s working exactly as intended the
