### ISSUE TITLE
Sea trade route

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#948]
Probably caused by the mod, not by my ignorance of game/mod mechanics.
Foreign sea trade routes unavailable for some reason. Only internal or with City States. Land routes work ok.
http://forums.civfanatics.com/showpost.php?p=14095355&postcount=57

![civ5screen0030](https://cloud.githubusercontent.com/assets/16341598/11880765/59c54d92-a50b-11e5-8d48-760d1c05c94a.jpg)
![civ5screen0029](https://cloud.githubusercontent.com/assets/16341598/11880768/5b16db5c-a50b-11e5-9eb8-a95871daff1c.jpg)

**Comment by LoneGazebo** [comment]
A sea trade route from where?

**Comment by saamohod** [comment]
From any of my coastal towns to another civ. London for example, or the closest to Cartage city named Utique. No sea trade routes available to other civs at all. And it's not because they are too far. From Utiqe (my city) to Cartage is 6 tiles.

**Comment by LoneGazebo** [comment]
Thanks! Will look into it.

**Comment by Edaka** [comment]
saamohod has also provided a save which should be relevant here: http://forums.civfanatics.com/showpost.php?p=14095145&postcount=17 (if needed)

**Comment by LoneGazebo** [comment]
I've reproduced it - ilteroi has the ball now.
G

**Comment by saamohod** [comment]
Fixed? Yeah!
