### ISSUE TITLE
CTD during AI's turn

### ISSUE THREAD

**Issue by jdoug312** [LoneGazebo/Community-Patch-DLL#9481]
_1. Mod Version (X.Y.Z). Current Version: 3.0.3_

3.0.3

_2. DirectX Version_

11

_3. List of Other Mods_

VP (1, 2, 3a, 4a, 4b)
Community Events v7
Israel for VP v17
EAW v1
Ainu People for VP v15
Scotland for VP v13
Tlingit for VP v18
Aircraft Command Group v1
Inuit for VP v19
Ethnic Diversity
ENW v2
Great Profit Historical Names v31
Kushan Empire for VP v2
Nubia for VP v19
Phoenician Civ v5
Quick Turns v10
Civ 6 styled names v1
Sumer for VP v24

_4. Describe the Issue_

CTD during AI's turn
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[QuickSave.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10099758/QuickSave.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10099759/logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10099761/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

End turn. You'll be asked if you want to declare a joint war (I decline), then after another AI or two are processing their turn, the game will CTD

_9. Screenshots of the Issue (Optional)_

**Comment by jdoug312** [comment]
I can now confirm that this happens on 3.0.4 as well. Turn ends as soon as Russia's turn is shown to be processing, immediately after Venice asks me to declare a joint DOW against Germany.

**Comment by axatin** [comment]
can't reproduce this, the game works fine for me. I assume it's a memory issue on your side

**Comment by ilteroi** [comment]
many mod, not reproduced
