### ISSUE TITLE
invisible unselectable unit

### ISSUE THREAD

**Issue by gamask** [LoneGazebo/Community-Patch-DLL#9482]
_1. Mod Version (X.Y.Z). Current Version: 2.7.3

_4. Describe the Issue_
Fog appears on the tile where my unit is standing, and several tiles around it.
Unit can not be selected by clicking on the tile it's on.
It can be selected by cycling through units.

_5. Save Game From 1 Turn Before
[213 BEFORE INVIS KNIGHT.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10100127/213.BEFORE.INVIS.KNIGHT.zip)

_8. Steps to reproduce the Issue
Find my knight north of Heliopolis.
End turn.
Watch fog appear where it shouldn't.
Next turn press space for all units until eventually it cycles to the knight.
Clicking on the tile with the knight doesn't work.
Moving the knight fixes everything.

_9. Screenshots of the Issue
![20221127164553_1](https://user-images.githubusercontent.com/4227288/204183346-95e1b786-0104-42cb-98f6-d0142ae7854b.jpg)

**Comment by alchx** [comment]
The same thing happens with ships. Once the 'invisible' ship could not be moved, had to be removed, Perhaps the area under it began to be considered land. The AI ​​can attack these invisible units.

**Comment by axatin** [comment]
Unfortunately, the error happened when the knight moved into the position, so a save game from before that is needed to find the cause of the bug.
