### ISSUE TITLE
Illogical position for anti-aircraft unit

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#9485]
![image](https://user-images.githubusercontent.com/66801010/204320045-3d6df112-bf24-49ef-a764-39c1c1d67491.png)

Not going to be too useful at defending that city from planes given that it's at the top of the map...and easily shot down by ranged ships.

Don't have the save for this unfortunately, but maybe you can do something with it.

**Comment by Stalker012345** [comment]
does it provide anti-air to ships near it? Could be one reason to have it

**Comment by ilteroi** [comment]
probably just a sentry, not related to air defense ... don't think this is really a problem.

btw i have a modified lua script which shows you what that the AI is doing with a given unit. can be quite interesting. goes into the "EUI Compability/LUA" folder.

[PlotHelpManager.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10122802/PlotHelpManager.zip)
