### ISSUE TITLE
AI units make suicidal attacks

### ISSUE THREAD

**Issue by alchx** [LoneGazebo/Community-Patch-DLL#9486]
_1. Mod Version (X.Y.Z). Current Version: 3.0.3_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

Sometimes the AI ​​makes pointless attacks (attempts) after which the units cannot survive, although the AI ​​sees all the threats to them.
Screenshots 1-2 - a French archer moved forward and fired on the chariot, and then both spearmen retreated, leaving him without cover. Here the peculiarity affected that long-range units move first. And the AI ​​probably ignored my unit in defense mode.
Screenshots 3-4 - no explanation. The spearman tried to run to the city, It was probably estimated that he could deal 50-70 damage (no garrison).

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Click "Next Turn" in both saves.

_9. Screenshots of the Issue (Optional)_
![20221129074406_1](https://user-images.githubusercontent.com/116918964/204535740-e9bb0913-254f-4fa1-8e06-b6f3a835bed2.jpg)
![20221129074523_1](https://user-images.githubusercontent.com/116918964/204535771-757cb0de-8a77-40f7-b605-0dbba08039e7.jpg)
![20221129083052_1](https://user-images.githubusercontent.com/116918964/204535817-0db721b1-adc6-402a-b081-8dd654a6ee1e.jpg)
![20221129082953_1](https://user-images.githubusercontent.com/116918964/204535864-129ec70f-5b45-41e3-b3c2-9b60e0e49e69.jpg)

**Comment by alchx** [comment]
Another case.
The city-state skirmisher advanced gradually and saw all the threats (my ally, also in the war with France and Japan). But he decided to run up to the pathfinder and hit him. His move to the tile with iron and the hit made it impossible for him not to be surrounded. If he had gone up the hill to my general, he could have successfully avoided encirclement.

[-suicidal skirmisher- 93 BC-0550.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10137190/-suicidal.skirmisher-.93.BC-0550.zip)


![20221201012919_1](https://user-images.githubusercontent.com/116918964/205188552-f8855096-fc13-40d1-b81e-062a6cbd3877.jpg)
![2-1](https://user-images.githubusercontent.com/116918964/205188590-abb28229-ff8f-48ce-9e6b-6ccedd3a65ac.jpg)

**Comment by cidk2000** [comment]
sorry to hijack, it just happend on vers 3.04 on my game raging barbs standard 

pure vox populi, 

pathfinder just slammed into a barbarian camp  unfortunatley i havent got any logs as im on my laptop but i do have a save game at turn 60 

![Untitled](https://user-images.githubusercontent.com/106168061/205363307-e82ca20f-44aa-4892-99cc-b64ca6a5341b.jpg)


[auto.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10143549/auto.zip) - auto saves 

[Oda Nobunaga_0062 BC-1520.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10143553/Oda.Nobunaga_0062.BC-1520.zip)
