### ISSUE TITLE
Units can be trapped by the new barbarian camp spawning too fast

### ISSUE THREAD

**Issue by alchx** [LoneGazebo/Community-Patch-DLL#9487]
_1. Mod Version (X.Y.Z). Current Version: 3.0.3_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

Raging Barbarians mode
The coastal barbarian camp was cleared and a new camp appeared the next turn, blocking the retreat of units inland, where they could take cover from Dromon. I suggest that a new camp cannot spawn within a 4 tiles radius of the destroyed one for 2 turns. This will allow units to either heal slightly or leave the area.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![20221129091355_1](https://user-images.githubusercontent.com/116918964/204541039-39455105-bad0-45e4-8d6f-0b8bc6e73016.jpg)
![20221129091500_1](https://user-images.githubusercontent.com/116918964/204541081-ba4f0bbb-d8d9-4dc8-ab37-892e49c647d2.jpg)

**Comment by azum4roll** [comment]
- Encampments CANNOT spawn within 2 tiles of a previous encampment that was cleared <15 turns ago

There is already a rule like this, but maybe the number of tiles should be expanded?
