### ISSUE TITLE
Barbarian Galley takes damage without attacking a city

### ISSUE THREAD

**Issue by alchx** [LoneGazebo/Community-Patch-DLL#9492]
_1. Mod Version (X.Y.Z). Current Version: 3.0.4_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

Barbarian Galley takes damage just by being near the city.
There is also a known issue with ships refusing to attack the city. Here, in a city without a garrison and without walls, an ordinary Galley would inflict 150-180 damage, a barbarian, probably less.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[-damaged galley-_0048 BC-2080.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10118963/-damaged.galley-_0048.BC-2080.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Click "Next Turn"

_9. Screenshots of the Issue (Optional)_

![20221130044629_1](https://user-images.githubusercontent.com/116918964/204696393-b3f51da2-3d45-490c-910f-a8b4439497b3.jpg)
![20221130044717_1](https://user-images.githubusercontent.com/116918964/204696412-7ee5ce1e-cd6d-427a-99a7-6084c2e9461e.jpg)
![20221130044733_1](https://user-images.githubusercontent.com/116918964/204696563-13fdcda2-0b47-4a5f-9a53-6d3f253aceec.jpg)

**Comment by ilteroi** [comment]
probably from looting

**Comment by LessRekkless** [comment]
Are the barbarians looting?
