### ISSUE TITLE
AI doesn't know how to purchase Authority bonus Units

### ISSUE THREAD

**Issue by theunholypotato** [LoneGazebo/Community-Patch-DLL#950]
While this may no longer be a problem (and I apologize if it isn't), in the 12/10 version, I found that other civilizations which completed Authority didn't properly utilize their ability to purchase superior-quality units for cheap. When fighting the Shoshone as France, with roughly equal technologies and territory, I utterly rolled over them via Landsknecht carpeting - 20 CS (1 less than a Longswordsman!) with looting bonuses and anti-cavalry power is absurd for less than the cost of a pikeman.

This isn't a petition to have the Landsknecht nerfed, but rather a question - can the AI be taught to purchase super-cost purchasable units in this fashion?

(I'm of the personal opinion that Landsknecht -> Musketman special is probably one of the most brutal power spikes in the game, as they keep their looting specialty when they upgrade, making them really strong on the offensive due to a much reduced need to heal. With their 3 speed, Musketeers are probably one of the largest offenders.)

**Comment by LoneGazebo** [comment]
The AI knows how. It may not choose to, but it knows. Hard-coding behavior is not viable.

**Comment by saamohod** [comment]
"Wonfix"? Does it mean the issue won't be fixed?
