### ISSUE TITLE
Cargo ships use canals of other players

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#9505]
Version 3.0.4
Is it intended that cargo ships can use canals of other players? (there is a Swedish fort west of Uppsala)
![Screenshot (182)](https://user-images.githubusercontent.com/95587882/205291422-956dd7f2-331e-4ce8-96fa-9b61953a2b2b.png)
[Savegame](https://github.com/LoneGazebo/Community-Patch-DLL/files/10141030/TradeRouteCanal.zip) (TR from Taghaza to Casablanca)

**Comment by LessRekkless** [comment]
Yep.
