### ISSUE TITLE
Pantheons listed twice in ReligionOverview

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#9506]
Version 3.0.4, non-EUI
Pantheons are still listed separately if a religion has already been founded:
![Screenshot (181)](https://user-images.githubusercontent.com/95587882/205292594-c8fb89bc-fb36-473b-a0b9-24db8b466e79.png)
[Savegame](https://github.com/LoneGazebo/Community-Patch-DLL/files/10141049/TradeRouteCanal.zip)

**Comment by LessRekkless** [comment]
Pantheons are actual religions, separate from the Religion that shares its pantheon belief.

Remember, you can still have a civilization that has cities with eg majority Buddhism, and other cities with majority Siamese Pantheon
