### ISSUE TITLE
IGE not working in 3.0.4 (New Coal deposits not counted)

### ISSUE THREAD

**Issue by PerfectDark99** [LoneGazebo/Community-Patch-DLL#9514]
1. Mod Version 3.0.4

2. List of Other Mods
- Faster Aircraft Animations
- Quick Turns
- Really Advanced Setup
- IGE

4. Describe the Issue
IGE not working in 3.0.4. I don't use it often so it might have not been working in 2.7 already. Can't say for sure.
Wat is not working? I added some coal: 3 to an existing deposit and 3 to mine hill without any. They are displayed on the map and even the resources tab (6 for Breda, 6 for Maastricht) but somehow still not counted to the total. 
Issue persist after full game restart.

______________________________________________________________________________________
5. Save Game From 1 Turn Before

[William_0290 AD-1840.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10146783/William_0290.AD-1840.zip)

The 6 coal near Breda and an Addtional 3 near Maastricht I added by IGE

6. Screenshots of the Issue (Optional)
![Coal IGE issue](https://user-images.githubusercontent.com/58620501/205447952-919cfdcf-44d2-4e91-ae9b-49cb9ec19712.jpg)

**Comment by AndreyK-555** [comment]
https://forums.civfanatics.com/threads/ingame-editor-for-vp.679650/
It's better to use this, it's in Mods Repository.  Anyway before you change coal (or other resource) (add quantity or just add) you should delete mine or whatever improvement the tile has, change and restore improvement.

**Comment by PerfectDark99** [comment]
Ok, so the procedure is to remove resource and the mine to a blank tile, then add the resource in desired amounts then add the mine again. then it works

**Comment by AndreyK-555** [comment]
You may not remove resource, but remove improvement first, then do whatever you want.
