### ISSUE TITLE
Wrong description for Holy Site creation

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#954]
Have a look at bottom left corner on the screenshot
![civ55](https://cloud.githubusercontent.com/assets/16341598/11911381/2574c3c0-a61d-11e5-93bc-82d5a1cb733c.jpg)

**Comment by Edaka** [comment]
Can confirm - the tooltip seems to have a random text every time.
![hs tooltip](https://cloud.githubusercontent.com/assets/12978597/11914873/5f4fcc7a-a695-11e5-9d58-a9fe38c3d754.jpg)

**Comment by LoneGazebo** [comment]
I think this is an EUI bug.

**Comment by Hokath** [comment]
Using EUI, I see this as well. Seems to show up as the last action a civilian performed
