### ISSUE TITLE
Spy event kidnap specialists works only one at a time

### ISSUE THREAD

**Issue by AndreyK-555** [LoneGazebo/Community-Patch-DLL#9544]
_1. Mod Version (X.Y.Z). Current Version: 3.0.4_

_2. DirectX Version_

_3. List of Other Mods_

(overhaul) More Wonders for VP (v0.17.1), (overhaul) Unique City States for VP (v11.1), (overhaul) Enlightenment Era (Vox Populi) (v 5b), InGame Editor+ (v 45), New Beliefs Mods, (over) More Unique Components for VP (v 84), Monopoly Buildings for Vox Populi (v 3.5), Cemetery Building 4VP (v 3), (9d) Reforestation for VP v.4, Better Lakes for Vox Populi (v 2.3), TreeGrowth (VP) (v 2), Quick Turns (v 10), RemoveBanLuxury (v 1), Really Advanced Setup (v 15), Wonder Race (v 7), (overhaul) Enhanced Naval Warfare for Vox Populi (v 2.1), (overhaul) Enhanced Air Warfare 4VP (v 1.9), Ski Resort Building for VP (v 2.1), Parks for Vox Populi (v 2), Casino Building 4VP (v 1.0), GMO Laboratory Building 4VP (v 1), Polar Station 4VP (v 1.0), Recruitment Office Building 4VP (v 4), Clock Tower Building (v 1.1),
Capture Great People for VP (v 3)

_4. Describe the Issue_

Kidnap specialists spy event works only one at a time, even if I work spies in several cities. I have kidnapped specialists from one city and have this event for several turns yet, but when I kidnap specialists from other cities I don't get additional yields.
It's works as I kidnap them only from one.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Wu Zetian_0388 AD-1756.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10208556/Wu.Zetian_0388.AD-1756.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/10208558/Lua.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/10208563/Database.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/10208564/xml.log)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![8930_20221212163853_1](https://user-images.githubusercontent.com/61764413/207062158-bca6a621-5439-4d71-aeec-515a5e8256c4.png)
![8930_20221212162038_1](https://user-images.githubusercontent.com/61764413/207062209-bd5563f6-4377-4fc8-9aec-0cb4216f201e.png)
![8930_20221212162022_1](https://user-images.githubusercontent.com/61764413/207062245-0ccbb8ec-e048-4952-914d-78f732e56b56.png)
![8930_20221212162008_1](https://user-images.githubusercontent.com/61764413/207062300-a1f0e7f2-eab7-46e3-a8bf-2a32daab5169.png)
![8930_20221212161920_1](https://user-images.githubusercontent.com/61764413/207062352-f0a8cebc-c034-45a6-bdad-9000f92460e2.png)

**Comment by axatin** [comment]
Intentional. Instead of gaining additional yields, the duration of the event is increased by another 30 turns (compare first and last screenshot). It is not possible to have two events active at the same time with different durations.
