### ISSUE TITLE
3.0.4 CTD during AI turn

### ISSUE THREAD

**Issue by XSamatan** [LoneGazebo/Community-Patch-DLL#9549]
_1. Mod Version (X.Y.Z). Current Version: 3.0.4_

v3.0.4, full EUI

_2. DirectX Version_

11

_3. List of Other Mods_

(9d) Reforestation for VP v.4
Calypso's Colored Religious Icons (Basic) (v 4)
Calypso's Colored Religious Icons (BNW Extended) (v 3)
Calypso's Colored Religious Icons (Extended) (v 5)
Fortress Borders (v 2)
InGame Editor+ (v 45)
Quick Turns (v 10)
Really Advanced Setup (v 15)
Improved City View
Units Wake When Ungradeable (v 1)
Wonder Race (v 7)

[Xsamatan MODS.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10242488/Xsamatan.MODS.zip)

_4. Describe the Issue_

recurring CTD during AI turn, at the end of the City states, the symbol for Barbarians does not appear

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[CTD.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10242442/CTD.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[XSamatan Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10242485/XSamatan.Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[XSanatan 3CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10242494/XSanatan.3CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

End turn ->CTD

_9. Screenshots of the Issue (Optional)_

**Comment by ilteroi** [comment]
i'm out of town ... but i would suggest to put in a point fix for the repair tasks and some plausi checks whenever a city is lost to find the root cause later.

**Comment by XSamatan** [comment]
Thanks for looking into this issue!

Don you know which plot causes the error? I sometimes use IGE to create neat borders, maybe this screwed with the ownership setting.

Regards
XSamatan

**Comment by axatin** [comment]
it is this tile:
![Screenshot (255)](https://user-images.githubusercontent.com/95587882/217361131-c31e2d61-b7cb-4b9c-bc1f-d7d2229fa934.png)
do you remember if you changed it using IGE?
