### ISSUE TITLE
Trait_FreePromotionUnitCombats

### ISSUE THREAD

**Issue by Iamblichos** [LoneGazebo/Community-Patch-DLL#955]
I've noticed that my units in the latest CP 12-18 are not getting the promotions assigned from 'Trait_FreePromotionUnitCombats' is anybody else seeing this?

**Comment by ilteroi** [comment]
hmm. i tried to make the trait handling a bit more efficient, maybe a bug crept in. will check

**Comment by ilteroi** [comment]
got it. unfortunately i can't post a new build because I don't have G's latest code yet. but we'll get to it in a few days i guess

**Comment by Kolaris8472** [comment]
Would this include the extra vision for American units? Noticed they're missing that promotion and have default sight radius.

**Comment by ilteroi** [comment]
yep
