### ISSUE TITLE
Trade route UI's cultural influence counter

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#956]
![ui1](https://cloud.githubusercontent.com/assets/12978597/11915005/8db387c6-a69c-11e5-9cea-082f79df099b.jpg)
![ui2](https://cloud.githubusercontent.com/assets/12978597/11915007/92f7551e-a69c-11e5-86d4-02f4ca2e353a.jpg)
![ui3](https://cloud.githubusercontent.com/assets/12978597/11915008/944ab9c4-a69c-11e5-999d-05f44900a110.jpg)
All these were taken on the same turn. As can be seen, I don't have the same influence over Portugal and Indonesia, and the actual numbers are far off.

**Comment by Kolaris8472** [comment]
Hmm, I thought that line showed the bonus modifier to your Tourism you'd gain as a trade partner? Is it really just supposed to just show your current Influence?

**Comment by Edaka** [comment]
IIRC, the bonus % modifier is always 25%. I'm pretty sure that counter is supposed to show your cultural influence over a target civ - makes it easier to decide where to send caravans to get the growth bonus (since it isn't otherwise displayed in that window).

**Comment by LoneGazebo** [comment]
Fixed. It was an improper math issue.
G
