### ISSUE TITLE
MOD_SANE_UNIT_MOVEMENT_COST

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#9561]
@ilteroi 

1. Can this particular commit https://github.com/LoneGazebo/Community-Patch-DLL/commit/46537c72cb44b8b7f6ab20be9da7b4a7f4090041 be cherrypicked into base VP? Is it the code necessary to fulfill the proposal you sponsored? https://forums.civfanatics.com/threads/1-19-proposed-replacements-for-trailblazer-double-movement-promotions.679967/

2. I believe this should test MOD_BALANCE_VP rather than gCustomMods.isBALANCE_CORE(), since BALANCE_CORE is enabled in Community Patch only.
```
if (!MOD_SANE_UNIT_MOVEMENT_COST)
	{
		//balance patch does not require plot ownership
		bFakeRouteTo |= (pTraits->IsWoodlandMovementBonus() && (eToFeature == FEATURE_FOREST || eToFeature == FEATURE_JUNGLE) && (gCustomMods.isBALANCE_CORE() || pToPlot->getTeam() == eUnitTeam));
		bFakeRouteFrom |= (pTraits->IsWoodlandMovementBonus() && (pFromPlot->getFeatureType() == FEATURE_FOREST || pFromPlot->getFeatureType() == FEATURE_JUNGLE) && (gCustomMods.isBALANCE_CORE() || pToPlot->getTeam() == eUnitTeam));
	}
```

**Comment by ilteroi** [comment]
1. no, it's my private thing. just ignore it for now
2. maybe, but it has been like this for while without complaints
