### ISSUE TITLE
Proposal (1-19a)

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#9565]
@ilteroi You sponsored proposal (1-19a): https://forums.civfanatics.com/threads/1-19-proposed-replacements-for-trailblazer-double-movement-promotions.679967/

> All Recon Units have base 3 moves and lose "Ignore Terrain Cost" (affects Pathfinder, Scout, Paratrooper, Special Forces, XCOM. Explorer and Commando are Unaffected)

    Trailblazer 1:
        +1 Sight.
        Ignore movement penalties on forest, jungle, and hills.
    Trailblazer 2:
        +1 moves.
        Ignore movement penalties from desert, snow, marshes, and rivers.
        no penalty for attacking over rivers.
    Trailblazer 3:
        Ignores ZOC.
        Can cross mountains and embark
        +20% CS Outside friendly territory.

> Other promotions:

    Scouting 1(Available at TB 2 and Survival 2): +1 Sight
    Scouting 2: +1 moves
    Scouting 3: removed
    Frogman (New promotion):
        Available at TB III
        Costs 1 Move to Embark and Disembark
        No penalty to attack from embarked
        +50% defense when Embarked

Will you be able to do the work for this soon or should your sponsorship be considered dropped?

Also, is it okay to merge oleole now?

**Comment by ilteroi** [comment]
i won't implement this proposal, too complicated. should never have sponsored it.

but yes, go ahead and merge my latest, just skip the superobserver stuff.
