### ISSUE TITLE
Pathfinder

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#957]
Posted by hermes11: "I'm only using the 12/18 Community Patch, and EUI [...] I think it has problems recognizing the shortest path to take with roads?
![path1](https://cloud.githubusercontent.com/assets/12978597/11915014/193a5a04-a69d-11e5-91ca-1b3110abdf87.jpg)
If the unit followed the roads this would be 2 moves from Stockholm to Sigtuna. "

Kolaris: "I had a different issue with roads in 12-16. The unit would say it was going to take the roads (eta 1 turn) but then switch to an off-road path that took 2 turns."

**Comment by saamohod** [comment]
I can confirm this. Pathfinding is weird in this version. It chooses not to use the roads quite often, when it shouldn't make sense.

**Comment by saamohod** [comment]
![civ5screen0037](https://cloud.githubusercontent.com/assets/16341598/11915106/fa777ffe-a69f-11e5-8794-2f71cca70118.jpg)

**Comment by ilteroi** [comment]
cannot reproduce. does anyone have a savegame?

**Comment by saamohod** [comment]
Can be reproduced by moving trebuchet (next to Beijing) to Chicago.
[AutoSave_0296 AD-1380.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/67646/AutoSave_0296.AD-1380.zip)

Mods used:
-all six items of CPP
-useful oil mod
-submarines ignore borders
-lake Victoria fix
-Krakatoa fix
-Gibraltar and reef optimizations
-faster plot expansion
-extra victory conditions
-improved air recom
-great prophet historical names

**Comment by ilteroi** [comment]
i seem to be missing some dlc? that's annoying. what would that be?

**Comment by Edaka** [comment]
You probably need to enable all saamohod's mods to run his savegame, did you try that?

**Comment by ilteroi** [comment]
doesn't matter anymore, i found it. pathfinder was a bit too aggressive and chose the shortest path (counted in plots) over the best path sometimes.

**Comment by saamohod** [comment]
Nice. Should we expect a hotfix then?

**Comment by ilteroi** [comment]
check over at civfanatics
