### ISSUE TITLE
Farm yield

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#9594]
_1. Mod Version (X.Y.Z). Current Version: 3.1.1_

_2. DirectX Version_9

_3. List of Other Mods_

_4. Describe the Issue_

Do farms provide +1 food? 

Here it says it does:

![20230103232344_1](https://user-images.githubusercontent.com/16341598/210443794-d815582e-9546-4b7d-a462-cd405baf47af.jpg)

Here doesn't (only mentions adjacency):

![20230103232125_1](https://user-images.githubusercontent.com/16341598/210443907-bdbc7eb5-9c0d-457a-8591-424ebe64835b.jpg)

______________________________________________________________________________________
_

**Comment by LessRekkless** [comment]
I'm pretty sure Farms on Maize don't produce extra food. See the maize resource in the Civilopedia.

**Comment by saamohod** [comment]
> I'm pretty sure Farms on Maize don't produce extra food. See the maize resource in the Civilopedia.

Civilopedia entry on farms unambiguously says that farms add +1 food.

**Comment by n-core** [comment]
> Civilopedia entry on farms unambiguously says that farms add +1 food.

Farm has +1 Food yield hardcoded into the game engine and we can't do anything about it aside from negate it to a -1 Food yield when improving a farm resource, like Maize and Rice.

**Comment by saamohod** [comment]
> > Civilopedia entry on farms unambiguously says that farms add +1 food.
> 
> Farm has +1 Food yield hardcoded into the game engine and we can't do anything about it aside from negating it to a -1 Food yield when improving a farm resource and replacing it with other yield type, like Maize and Rice.

Do I understand it correctly that placing a farm on a Rice or Maize makes no sense?

**Comment by LessRekkless** [comment]
> > I'm pretty sure Farms on Maize don't produce extra food. See the maize resource in the Civilopedia.
> 
> Civilopedia entry on farms unambiguously says that farms add +1 food.

And the Maize entry unambiguously says that farms adds -1 food.
