### ISSUE TITLE
ScorePlotBuild oddities

### ISSUE THREAD

**Issue by LessRekkless** [LoneGazebo/Community-Patch-DLL#9595]
_1. Mod Version (X.Y.Z). Current Version: 3.1.1_

3.1.1

_4. Describe the Issue_

https://github.com/LoneGazebo/Community-Patch-DLL/blob/4757c1e4da27cba6c79380166e39a5a9c11ffc55/CvGameCoreDLL_Expansion2/CvBuilderTaskingAI.cpp#L2157-L2168
CvBuilderTaskingAI::ScorePlotBuild() adds the base yields of the improvement to iTempWeight, as above.  However:
a) iTempWeight is overwritten for each new yield
b) iTempWeight isn't *used* anywhere.
This means that the BUILDER_TASKING_BASELINE_ADDS_* variables do nothing, (which seems incorrect?) and that yields are only accounted for using:
https://github.com/LoneGazebo/Community-Patch-DLL/blob/4757c1e4da27cba6c79380166e39a5a9c11ffc55/CvGameCoreDLL_Expansion2/CvBuilderTaskingAI.cpp#L1975-L1983
in a separate section of the code.

**Comment by LessRekkless** [comment]
I don't know how it was supposed to work, unfortunately.

**Comment by ilteroi** [comment]
neither do i but i made an educated guess. doesn't seem to have a big impact in any case ...

**Comment by LessRekkless** [comment]
I'm wondering if the code is superfluous at this point.

Before commit 9629f8ed69127e6e4982d380095105d18614cfaa changed it, this was a **multiplier** on score (or rather, the other way around), with a caveat: only one base weighting was used, in order of yield precedence in the yield table.  You fixed this in by just adding the weight to the yield itself. However, just like `BASELINE` implies, it only adds the base yields provided by the improvement entry.

Today, we have `CvCityStrategyAI::GetMostDeficientYield()`, which also accounts for the different yield types with its own scalers eg. `AI_CITYSTRATEGY_YIELD_DEFICIENT_FAITH`, and is scaled based off how many ACTUAL yields are to be added. The main difference between `AI_CITYSTRATEGY_YIELD_DEFICIENT_*` and `BUILDER_TASKING_BASELINE_ADDS_*` globals is that `YIELD_DEFICIENT` subtracts a baseline of how much each yield is providing per population before deciding which yield is the most necessary to improve, while `BASELINE_ADDS` states a value of the yield itself:

https://github.com/LoneGazebo/Community-Patch-
DLL/blob/46f51b0c800c8edc251e4951cae1ccf44675e2c9/CvGameCoreDLL_Expansion2/CvCityStrategyAI.cpp#L646-L679

I'll note that both sets of globals are only used in one location.
