### ISSUE TITLE
Huns Not Capturing + Unit Pathing

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#960]
Two issues I found.

1.  Playing as the Huns - mounted units are not capturing units any more.  I played the Huns in a previous version, and they were capturing things then.  Dunno what's up here.

2.  Sometimes a unit can actually reach a particular tile, but if you tell it to move there, it can't figure it out and doesn't move there.  Always has to do with a road - if you manually move it to the right road tile and then give it a second command to go to where you wanted it to go, it'll then get there.

**Comment by LoneGazebo** [comment]
Both issues are being discussed by ilteroi in other issues. I think he has or is working on a fix.

**Comment by ilteroi** [comment]
1. are you talking about horsemen or horse archers? because the latter cannot capture and never could, afaik.

2. do you have a savegame with the road issue?

**Comment by Gidoza** [comment]
1.  I'm talking about Horsemen/Knights/etc., yes, and NOT the Horse Archers.

2.  Dang - no, didn't know that sort of thing helped.  I'll bear this in mind for the next time I see it and send it to you when I have it.

**Comment by ilteroi** [comment]
1. that's strange, for me it works

2. i can reproduce it now, no worries

**Comment by Gidoza** [comment]
1.  What the heck?  O_o   I played Huns in an earlier version and it worked - I play it in this version, and it doesn't.  I should mention as well that the probability % to capture doesn't even show up in the little combat menu like it should.  After 100+ combats with horses that won battles, diddly-squat captured.

2.  Ok cool.  :)
