### ISSUE TITLE
Foreign Legion and Nau civilopedia

### ISSUE THREAD

**Issue by pandasnail** [LoneGazebo/Community-Patch-DLL#961]
The Foreign Legion page says it is similar to the Great War Infantry instead of Rifleman. IIRC, that's a base game unit y'all deleted. 

The Nau civilopedia page and tooltip both say it has more movement than the Caravel, but it has the same movement and more combat strength (which isn't mentioned). I mean, the number is right, I'm referring to the text parts.

I notice these from time to time, but I thought posting them would be akin to a 'well actually,' but now that I know you want them, I'll try to post when I see them.

**Comment by LoneGazebo** [comment]
thanks!
