### ISSUE TITLE
AOE Damage Between Unit Domains

### ISSUE THREAD

**Issue by Flamingcheesepie** [LoneGazebo/Community-Patch-DLL#9616]
Currently, AOE from Splash (on attack), Overrun (on kill), and Rend (on move, not used in base VP but available in 4UC) deal damage across domains. That is, if there is a naval unit on the coast, and you AOE a land unit on the land next to it, the ship will take damage. While this makes sense for Splash, it does not for the other 2 AOEs. If possible, could the latter 2 AOEs be changed? Alternatively, it may be best to accept that Splash should not AOE between domains. 

If this would be better served as a congress proposal I can raise it there instead, but it feels more of an oversight than a significant mechanic change, since the latter 2 AOEs really shouldn't cross domains in the first place.

**Comment by ilteroi** [comment]
overrun is already fixed
splash should be fine, ie not deal damage to units in other domains and in cities
never heard of rend
