### ISSUE TITLE
Renew deal is impossible

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#9619]
_1. Mod Version (X.Y.Z). Current Version: 3.1.1_

_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[bug_Elizabeth_0157 AD-0940.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10400172/bug_Elizabeth_0157.AD-0940.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10400174/Logs.zip)

_8. Steps to reproduce the Issue (Optional)_
hit next turn

_9. Screenshots of the Issue (Optional)_

![Screenshot (43)](https://user-images.githubusercontent.com/49090452/212033125-e40d398d-835d-4967-9f50-9d5b33df809a.png)

Deal value is positive but still impossible
![Screenshot (44)](https://user-images.githubusercontent.com/49090452/212033143-a23b82f2-6a50-4e9a-8a87-630ad74ac21b.png)

**Comment by azum4roll** [comment]
They don't want to trade away the Gold anymore?
