### ISSUE TITLE
Pasture Bonuses from Tech

### ISSUE THREAD

**Issue by Kolaris8472** [LoneGazebo/Community-Patch-DLL#962]
Pastures with Fresh Water get +1 Production from Tech, Pastures without Fresh Water get +1 Food from Tech. This seemed a bit unusual compared to most other tile improvement scalers. Intended?

EDIT: And Camps as well. Fresh Water gets +1 gold, no Fresh Water gets Food. 

I don't know why tiles without Fresh Water should be better, even if their bonus does come later.

**Comment by LoneGazebo** [comment]
It is intended as a balance mechanic, yes.
