### ISSUE TITLE
Missing loading screen (VPUI) tooltip

### ISSUE THREAD

**Issue by bsesar** [LoneGazebo/Community-Patch-DLL#9625]
_1. Mod Version (X.Y.Z). Current Version: 3.1.1_

_4. Describe the Issue_
Just started a freshly installed game of VP and the loading screen showed that VPUI tip is missing (see the screenshot below)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10417083/Logs.zip)

_9. Screenshots of the Issue (Optional)_
<img width="291" alt="missing_loading_screen_tooltip" src="https://user-images.githubusercontent.com/620131/212466484-5ba633c6-38a2-4f38-9cbd-3895e572df9a.png">

**Comment by n-core** [comment]
Fixed #9601 & #9589
