### ISSUE TITLE
How hardcoded is the World Congress?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#963]
It seems awkwardly strange that one of the key concept of Civilization 5 is the World Congress and it hasn't been made open to modding. I'm suggesting a few LUA snippets would help open up the modding of World Congress massively.

I'm suggesting if it is possible, then I would like a few LUA snippets be made for modders to be able to mod the World Congress freely. For example, what if I wanted to create a LUA script that creates a certain condition pending whether or not the resolution is passed or not passed? In the vanilla version, it is impossible, but I am wishing for the Community Patch...

**Game:GetResolution()** --Game grabs every resolution from the databanks.
**Resolution:IsProposed()** --Checks if the resolution is currently being proposed at this WC meeting.
**Resolution:IsPassed()** --Checks if the resolution was passed.
**Resolution:GetResolutionDecision()** --Checks what kind of resolution it was? (Am I voting for a religion, civilization, yes/no or ideology?)
**Players[iPlayer]:VotedForResolutionDecision()** --Checks if a player voted for yes/no, communism/autocracy for their preferred ideology, or Shinto/Buddhism for their preferred religion. (This LUA would be useful for civilizations who voted no on certain proposals!)
**Players[iPlayer]:GetVotesResolutionDecision()** --Checks how many votes a certain civilization had given toward a decision. (Determine how much votes a civilization had given toward a decision. LUA can be used to determine if a civilization gave 5 votes toward Shinto as a World Religion.)
**Players[iPlayer]:GetVotes()** --Return a value of how many this civilization has in terms of voting power.

**Comment by LoneGazebo** [comment]
The world congress is horribly hard-coded. All changes are 'streamed' into the DLL, and LUA changes would most likely cause memory corruptions and/or be overwritten. Not sure this is viable, unfortunately.

**Comment by TechpriestEnginseer** [comment]
That's a shame.

**Comment by LoneGazebo** [comment]
Yep. Firaxis hard-coded almost everything added in Brave New World. Not sure why - probably to speed up development.
G
