### ISSUE TITLE
Inconsistent yields when testing UnitPromotions_GarrisonYield

### ISSUE THREAD

**Issue by legenciv** [LoneGazebo/Community-Patch-DLL#9631]
_1. Mod Version (X.Y.Z). Current Version: 3.1.1_

3.1.1

_3. List of Other Mods_

InGame v45 (for test purposes)
34UC

_4. Describe the Issue_

When testing 'UnitPromotions_GarrisonYield' locally, the promotion may give different yields than intended depending on the unit that has the promotion. 

The local tests were with a (new) promotion that gives 2 faith and 1 culture when garrisoned. Units tested, and their yields when garrisoned, were:

Pathfinder (gives 1 faith)
Warrior, Spearman, Slinger, Archer, Composite Archer (gives 2 faith 1 culture)
Crossbowman (gives 3 faith 2 culture)

**Comment by legenciv** [comment]
Closed, ataxin answered that the yields are intended to scale from the unit's combat strength.

**Comment by n-core** [comment]
Then the table description needs to be updated.
https://github.com/LoneGazebo/Community-Patch-DLL/blob/656ccf8c49b8c9da12f6c48c97458869407c1e63/(1)%20Community%20Patch/Core%20Files/Core%20Tables/CoreTableAdditions.xml#L1911-L1916
