### ISSUE TITLE
Assyrian UI

### ISSUE THREAD

**Issue by Der-Zorn-Gottes** [LoneGazebo/Community-Patch-DLL#964]
Them amount of gold you get upon conquering a city if there's no tech to gain seems not to scale with gamespeed.
Can't tell for sure, because I don't know what the base value is, but it's not a multiple of three (for marathon speed), thats usually a valid indication.

**Comment by Edaka** [comment]
I assume you mean the science from the UA.

**Comment by Der-Zorn-Gottes** [comment]
Yes.
