### ISSUE TITLE
Science tooltip in happiness UI

### ISSUE THREAD

**Issue by Hokath** [LoneGazebo/Community-Patch-DLL#965]
the word "per" is highlighted green accidentally

**Comment by LoneGazebo** [comment]
Which tooltip? I can't reproduce. An image would be helpful.

**Comment by Hokath** [comment]
This one.
![2015-12-29_00001](https://cloud.githubusercontent.com/assets/11889219/12043123/965cd686-ae79-11e5-9213-8bf9ec2268c5.jpg)

**Comment by LoneGazebo** [comment]
got it!
