### ISSUE TITLE
12/18 hard-locks game... pathfinder bug?

### ISSUE THREAD

**Issue by pjf** [LoneGazebo/Community-Patch-DLL#967]
Hey Gazebo, thank you *so much* for an amazing Civ5 project! It *totally* rocks.

I've just updated to 12/18, and I've encountered an instance where the game hard-locks on "processing turn for (player)", both for a discovered civ (Polynesia) and for barbarians (in separate saves). When this happens I can't scroll the map, and even if I get to the main menu with escape, it doesn't let me reload or exit; I have to force-quit the game. Having enabled debugging and using `tail -f`, the last thing that appears in the logs are a number of pathfinder lines in the `stopwatch.log` file. I don't know if that's related, but I *am* using the communitas map, and it produces some pretty complex terrain.

Things to note: I'm running under wine (using PlayOnLinux on Ubuntu), but both was able to play a complete game through to completion with a previous community patch/rebalance with zero bugs whatsoever, so I'm hoping it's solid. I'm not playing with any other mods besides the community patch/rebalance. My cache was cleared. :)

[civ5saves.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/67827/civ5saves.zip) contains two saves that reproduce the bug, which should trigger when you process the next turn. In one case I had the game not lock up when I hit the next turn button, only to have the bug re-appear two turns later.

Thank you again for a fantastic mod, you've really made Civ5 great!

~ Paul

**Comment by ilteroi** [comment]
sorry can't load your saves - which mods other mods do you use? can you try with CPP only?

**Comment by pjf** [comment]
Updates on this:

- Can reproduce the same behaviour on 12/10.
- 11/20 seems to work just fine, no lock-ups. I've played hundreds of turns on it.

Missing DLC has me concerned that *I've* missed something; here's what my DLC folder looks like:

```
DLC_01
DLC_02
DLC_03
DLC_04
DLC_05
DLC_06
DLC_07
DLC_Deluxe
DLC_SP_Maps
DLC_SP_Maps_2
DLC_SP_Maps_3
Expansion
Expansion2
Shared
Tablet
```

However I *am* using the Communitas map in my `Assets/Maps` folder, and that's possibly what it's complaining about. Here's a zipfile containing it: [maps.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/67861/maps.zip).

Thanks very much for the swift response!

~ Paul

**Comment by ilteroi** [comment]
it seems the problem is DLC_SP_Maps_2 and Maps_3, could you retry without those? i don't think they cause a problem, but then i might be able to load the savegame ...

**Comment by GreenHul** [comment]
Yes I also am experiencing this problem, right around turn 11.  Like the previous person, I just see that the ai is processing its turn forever.  Cannot escape to menu or open any tabs in the game.  Must force quit in order to quit game.  As well, I'm playing Civ V on PlayMyMac since dll mods don't work on Mac.  Any help would be greatly appreciated.  I really want to play this patch, it just sucks that I can't install it onto the native Mac version of Civ V

**Comment by pjf** [comment]
@ilteroi : Thank you so much! I'm new to Civ5 modding, although not modding in general. :) Is my best option to create a save without that DLC is to remove it from the directory, start a new game with 12/18, and play until the bug rears its head?

@GreenHul : Interesting that we're both using wine! In case it's relevant I'm using wine 1.7.45, under which I'm heading on towards my second playthrough with 11/20 (so it's *REALLY* solid under previous releases).

**Comment by GreenHul** [comment]
@pjf: I have a really quick question for you though.  Whenever you load Civ V on PlayMyLinux, does your cursor flicker constantly?  Mine does and I don't know how to fix it

**Comment by pjf** [comment]
@GreenHul: Sorry. My cursor is solid. The only thing I can't do is run the game full-screen and have it survive me tabbing out of it. Otherwise it's a solid platinum in terms of experience: everything works flawlessly.

**Comment by ilteroi** [comment]
@pjf: yes, that would be the plan. however, i'm not sure i can learn a lot from it. if it's a wine-specific issue, chances are i won't be able to replicate it.

but there's an alternative, in case you're familiar with winedbg. at  https://dl.dropboxusercontent.com/u/16988401/civ/debug-build.zip you can find a debug build of the dll with debugging symbols (built from commit 3017eb9bc61e33ad4ed14338ca2849112b4500fa). run the game in winedbg and break to see what it's doing when it hangs. (note: i've never done this, just took a look at https://www.winehq.org/docs/winedev-guide/wine-debugger)

**Comment by ilteroi** [comment]
ok, finally managed to load the saves. divide by zero errors all over the place.

seems that a bunch of GC.getX() calls return zero. no idea why and how that is related to wine.

**Comment by LoneGazebo** [comment]
GC.getX()? You mean map calls? Wonder if it is an issue with tooltips and/or on-demand lua.

Linux users, are you running EUI?

**Comment by ilteroi** [comment]
sorry, i meant stuff like GD_INT_DECL(MINOR_CIV_FIRST_CONTACT_HOSTILE_BONUS_DIVISOR) - constants from the database.

it's crazy, those aren't even included in the database. also, sometimes on loading the game i get extremely strange crashes. i'm stumped.

anyway, just uploaded some changes, stops the game from crashing (in the first 100 turns at least) but that doesn't mean it works correctly with the constants being off (probably not all of them)

**Comment by LoneGazebo** [comment]
Sounds like the game may not be able to locate the game database location. Perhaps because of where it is installed in linux?

**Comment by pjf** [comment]
My apologies that I'd been pulled away for a few days; this is fantastic news that we can reproduce the error from the saves! Thank you *so much* for looking into this.

> Linux users, are you running EUI?

Absolutely, as bundled with the 12/10. But I've also used the EUI in 11/20 and by itself, and in both those cases everything runs flawlessly. If the EUI has been updated between 11/20 and 12/10, then I can try without.

> anyway, just uploaded some changes, stops the game from crashing (in the first 100 turns at least) but that doesn't mean it works correctly with the constants being off (probably not all of them)

Thank you! I'm looking at 371607437dce56b3e22ec28230628b5e47f3391f , and agree it seems constants coming from the database returning zero is *very* weird. But I'm delighted you can reproduce this with my savefiles, because it means that with the right saves, this isn't restricted just to running under wine. :)

**Comment by pjf** [comment]
> Sounds like the game may not be able to locate the game database location. Perhaps because of where it is installed in linux?

Wouldn't that have much broader reaching consequences? I would expect it to make 11/20 unplayable (it's 100% solid), or have the base game not run at all (it's also 100% solid).

Do we have git commits IDs for 11/20 and 12/10 and any interim dev builds? While I don't think I can meet the build requirements to do a `git bisect`, I can certainly use existing artefacts to narrow the search space.

**Comment by LoneGazebo** [comment]
It might, though the issue may be that the savegame is looking for a database cache directory that doesn't exist on ilteroi's machine (but does exist on yours). Thus the divide-by-zero errors he sees aren't actually the CTD you are experiencing.

EUI question was related to the GetX(), which ilteroi clarified. Isn't the issue.

Save/load of games is working, always? Any oddities?

**Comment by pjf** [comment]
> It might, though the issue may be that the savegame is looking for a database cache directory that doesn't exist on ilteroi's machine (but does exist on yours). Thus the divide-by-zero errors he sees aren't actually the CTD you are experiencing.

Aaah, I understand! Although it's not quite a CTD, we're just hanging indefinitely.

> Save/load of games is working, always? Any oddities?

Under 11/20 and vanilla absolutely reliably, never an issue at all.

Under 12/10 I've been able to save and restore, but that doesn't seem to avert the hang of doom. (But except for the hang of doom when processing a turn, save/restore seems to be working fine.)

**Comment by LoneGazebo** [comment]
Hanging indefinitely indicates an infinite loop. Are you using the hotfix DLL that ilteroi posted in the forums?

G
