### ISSUE TITLE
HurryCostModifier

### ISSUE THREAD

**Issue by Padre19** [LoneGazebo/Community-Patch-DLL#9680]
There is no rule neither for buildings nor for units.

BuildingHurryCosts.sql
-------------------------------------
UPDATE Buildings
SET HurryCostModifier = '5';

UPDATE Buildings
SET HurryCostModifier = '-5'
WHERE NOT WonderSplashImage = 'NULL';

CSDCompatibility.sql
------------------------------------------------------------
UPDATE Buildings SET HurryCostModifier = '-20';
UPDATE Buildings SET HurryCostModifier = '-5' WHERE NOT WonderSplashImage = 'NULL';

What would be the correct one?

That's what I would suggest
----------------------------------------------------------------------------------------------------------------
UPDATE Buildings SET HurryCostModifier = '5';
UPDATE Buildings SET HurryCostModifier = '-5' WHERE NOT WonderSplashImage = 'NULL';
UPDATE Buildings SET HurryCostModifier = '-1' WHERE IsDummy = '1' OR Cost = '-1';

UPDATE Units SET HurryCostModifier = '-1' WHERE Cost = '-1';
UPDATE Units SET HurryCostModifier = 0 WHERE PurchaseOnly = 1;
UPDATE Units SET HurryCostModifier = 10 WHERE HurryCostModifier > -1;
UPDATE Units SET HurryCostModifier = 15 WHERE DefaultUnitAI = 'UNITAI_TRADE_UNIT';
UPDATE Units SET HurryCostModifier = 20 WHERE DefaultUnitAI = 'UNITAI_MESSENGER';
UPDATE Units SET HurryCostModifier = 25 WHERE DefaultUnitAI = 'UNITAI_SPACESHIP_PART';

**Comment by Padre19** [comment]
Cost difference between gold cost and production cost. A unit with HurrycostModifier 10 will be 10% more expensive to buy than to build.

**Comment by Padre19** [comment]
With HurrycostModifier -1 cannot be bought with gold

**Comment by azum4roll** [comment]
UPDATE Units SET HurryCostModifier = '-1' WHERE Cost = '-1';
UPDATE Units SET HurryCostModifier = 0 WHERE PurchaseOnly = 1;
UPDATE Units SET HurryCostModifier = 10 WHERE HurryCostModifier > -1;

Why not just

UPDATE Units SET HurryCostModifier = '-1' WHERE Cost = '-1';
UPDATE Units SET HurryCostModifier = 10 WHERE PurchaseOnly = 1 OR HurryCostModifier > -1;

then?

**Comment by Padre19** [comment]
Because units that can only be bought with gold should not incur a penalty.

**Comment by n-core** [comment]
> `UPDATE Units SET HurryCostModifier = 10 WHERE HurryCostModifier > -1;`
It should be `UPDATE Units SET HurryCostModifier = 10 WHERE HurryCostModifier > -1 AND PurchaseOnly != 1;`
Otherwise, you reset the purchase cost for the purchase-only units.

**Comment by Padre19** [comment]
UPDATE Buildings SET HurryCostModifier = '5';
UPDATE Buildings SET HurryCostModifier = '-5' WHERE NOT WonderSplashImage = 'NULL';
UPDATE Buildings SET HurryCostModifier = '-1' WHERE IsDummy = '1' OR Cost = '-1';

UPDATE Units SET HurryCostModifier = '-1' WHERE Cost = '-1';
UPDATE Units SET HurryCostModifier = 0 WHERE PurchaseOnly = 1;
UPDATE Units SET HurryCostModifier = 10 WHERE HurryCostModifier > 0;
UPDATE Units SET HurryCostModifier = 15 WHERE DefaultUnitAI = 'UNITAI_TRADE_UNIT';
UPDATE Units SET HurryCostModifier = 20 WHERE DefaultUnitAI = 'UNITAI_MESSENGER';
UPDATE Units SET HurryCostModifier = 25 WHERE DefaultUnitAI = 'UNITAI_SPACESHIP_PART';

**Comment by azum4roll** [comment]
We haven't played any game with nerfed gold income and increased building maintenance yet. We may lack gold next version.

**Comment by LessRekkless** [comment]
Figure out what was intended before making balance changes.

**Comment by azum4roll** [comment]
Code is consistent now, propose in congress if you want to alter the values.
