### ISSUE TITLE
Warscore

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#969]
Feedback from Funak on 12/18, it seems: "I have no idea what's going on with the new warscore.
I managed to get it up to +28 when I captured a 75% of a neighbors cities, pillaged all his tiles and dropped his final city down to 0 hp.
A few turns later I got attacked by my backwards neighbor and since I don't have any intention of grabbing more cities (already got enough warmonger penalty) I just stood on his border blasting all his cities and solders to oblivion until he was ready to accept peace.

Anyways the war-score is currently at 0 with the descriptions saying:
Military power: "They are weaker" and Economy:"They're in shambles "

**Comment by LoneGazebo** [comment]
I wonder if my war score change made it into ilteroi's dll. Ilteroi, the updatewardamage diplo function should not have the 'geteconomicvalue' function in it, as it added to much to value of stuff.

**Comment by ilteroi** [comment]
in that case i have the previous version

**Comment by LoneGazebo** [comment]
Remove that statement.

**Comment by ilteroi** [comment]
done.

**Comment by Edaka** [comment]
ilteroi, have you uploaded a hotfix with that change? Your latest DLL on the forum still seems to have the issue.
