### ISSUE TITLE
Lancers don't upgrade 

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#970]
According to Funak, that is.

**Comment by aht820** [comment]
I'm playing as Morocco and I cannot upgrade my Lancers to Berber Calvary. I'm using the new 12/28 version. 
![2015-12-31_00001](https://cloud.githubusercontent.com/assets/13701528/12065984/7ec1884c-afae-11e5-91be-c2fe0fdaeb94.jpg)
![2015-12-31_00002](https://cloud.githubusercontent.com/assets/13701528/12065985/7ec44708-afae-11e5-94cd-2e569b76c2ba.jpg)
![2015-12-31_00003](https://cloud.githubusercontent.com/assets/13701528/12065986/7ec55ff8-afae-11e5-9a50-9596f0dc8f73.jpg)
