### ISSUE TITLE
God of War not giving instant faith yields for killing major civ units

### ISSUE THREAD

**Issue by SpankMyMetroid** [LoneGazebo/Community-Patch-DLL#9710]
_1. Mod Version (X.Y.Z).  3.2.2_

_3. List of Other Mods_
4UC, ENW

_4. Describe the Issue_
God of War pantheon gives faith yields for barbs and CS unit kills, but not major civs. Heal on kill still seems to work no matter the target.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[godofwartest.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/10992374/godofwartest.zip)

_9. Screenshots of the Issue (Optional)_

![20230316105839_1](https://user-images.githubusercontent.com/20096768/225660112-b1f58957-48db-4041-8069-4fb6dccc4689.jpg)
![20230316105715_1](https://user-images.githubusercontent.com/20096768/225660120-5fd0d788-3661-4d10-b20a-993ca5af9b17.jpg)
![20230316105830_1](https://user-images.githubusercontent.com/20096768/225660149-6b0225ca-8254-4ff7-a83d-81dc0e3ac048.jpg)

**Comment by legenciv** [comment]
I think it has to do with you conquering Sao Paulo and losing pantheon majority in the empire. The old God of War had the same behavior, and I think the celtic Morrigan pantheon does the same. If correct, then you should be unable to gain from killing barbarians, and resume gaining faith from kills when you settle another city. Can you confirm the last part?

**Comment by SpankMyMetroid** [comment]
That is indeed the answer.
