### ISSUE TITLE
Several Unhappiness info on Top Panel are missing

### ISSUE THREAD

**Issue by n-core** [LoneGazebo/Community-Patch-DLL#9715]
_1. Mod Version (X.Y.Z). Current Version: 3.2.2_

3.1.1

_3. List of Other Mods_

Too many personal mods.

_4. Describe the Issue_

Unhappiness from Puppets and Resistance is missing from Top Panel. While I can fix the Puppet one (it's only a missing text insert on the Lua file), I can't fix the Resistance one since there isn't a Lua call for it, and `GetUnhappinessFromOccupiedCities()` don't include it for some reason (it should be because the text suggested that).
https://github.com/LoneGazebo/Community-Patch-DLL/blob/10872c349c291b88dc1ae33c688bbaa29c64fb63/(2)%20Vox%20Populi/Balance%20Changes/Text/en_US/UIText.sql#L576-L586
https://github.com/LoneGazebo/Community-Patch-DLL/blob/10872c349c291b88dc1ae33c688bbaa29c64fb63/(3a)%20EUI%20Compatibility%20Files/ImprovedTopPanel/TopPanel.lua#L1432-L1468

_8. Steps to reproduce the Issue (Optional)_

Just take someone else's city and hover on the Top Panel to see if the Unhappiness from Resistance is there.

_9. Screenshots of the Issue (Optional)_
The Puppet one is fixed by me.
![image](https://user-images.githubusercontent.com/110832881/226094161-f74bd5dc-08a9-4f8a-a183-1e4a96db3e66.png)
I have several Unhappiness from Resistance in this overview, the tooltip is hardcoded into the DLL apparently.
Jalyng to Ammonion are Puppet cities, while Hariva to Drepsa are currently still in Resistance.
![image](https://user-images.githubusercontent.com/110832881/226094189-e2cfcabe-1826-41a3-ad97-b45b9d12ef4f.png)

**Comment by azum4roll** [comment]
I assume this was fixed some time ago since #10630 has that working on the UI (but not in effect).
