### ISSUE TITLE
Lost ocean travel for land units

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#972]
At some point after Renaissance Era my embarked land units lost their ability to enter ocean tiles. 
Savegame: [No ocean travel.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/68916/No.ocean.travel.zip)
Active mods: 
-CPP with EUI (all six folders)
-Extra victory conditions
-Faster plot expansion
-Gibraltar and reef optimization
-Lake Victoria fix
-Krakatoa fix
-Great prophet historical names
-Improved air recon
-Submarines ignore borders
-Thal's flag promotions
-Useful oil mod

**Comment by idontknow12** [comment]
Had a related occurrence in my game: Suddenly after finishing banking research, my galeass was able to cross ocean tiles! It couldn't before. Playing as the Celts.

**Comment by Edaka** [comment]
Copy-pasting from the forum since it's related. By R08: "I am playing as Polynesia. The Droman can enter deep ocean tiles. Once upgraded to a Galleass it gains the "Cannot enter deep ocean" promotion, and can not enter the deep ocean tiles."

**Comment by LoneGazebo** [comment]
We will see if this is fixed now that ilteroi has fixed those issues generally.
