### ISSUE TITLE
Militarism Visual Bug

### ISSUE THREAD

**Issue by Aqinu** [LoneGazebo/Community-Patch-DLL#9724]
_1. Mod Version (X.Y.Z). Current Version: 3.2.2_
3.2

_4. Describe the Issue_
Barracks appears to have +4 culture, but is should be +2 (works correctly, it's just visual).

_9. Screenshots of the Issue (Optional)_
![Civ5Screen0000](https://user-images.githubusercontent.com/49090452/226282098-9a042b1d-d0a6-41c8-974a-7106cb37987f.jpg)

**Comment by artemigkh** [comment]
I think is duplicate of #9704

**Comment by artemigkh** [comment]
Likely a duplicate of #9704
