### ISSUE TITLE
3.2.1 - The Ghost Ship

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#9725]
_1. Mod Version (X.Y.Z). Current Version: 3.2.2_

3.2.1

_2. DirectX Version_

_3. List of Other Mods_

(note this is a different mod list than the other bugs I had reported previously)

[ModList2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11020489/ModList2.zip)

_4. Describe the Issue_

This has been a problem for a few versions now. Every so often, one of your auto-exploring ships "disappears", it becomes a graphicless outline, and if you don't delete it, you can't press next turn and go forward.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[(Bug) Ghost Ship.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11020477/Bug.Ghost.Ship.zip)
The ghost ship has triggerd, and I have just click it to stop auto explore.

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs - Copy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11020487/Logs.-.Copy.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![image](https://user-images.githubusercontent.com/20593976/226401818-ac0f89aa-3186-4fb9-9d1b-dc6a4dbfed77.png)

**Comment by Stalker012345** [comment]
One more note, I have also now seen this bug with an embarked skirmisher. Having the skirmisher reembark on land seemed to fix it up.

**Comment by axatin** [comment]
A visibility issue. For some reason you don't have visibility on the tile with the ship. Would need a save game from one turn before to find out why.
