### ISSUE TITLE
3.2.2 - Wrong calculation for Culture Process

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#9733]
_1. Mod Version (X.Y.Z). Current Version: 3.2.2_

_3. List of Other Mods_

![20230324124834_1](https://user-images.githubusercontent.com/16341598/227536865-c2378f9c-c3f7-45aa-8fd8-45786456bdf9.jpg)

_4. Describe the Issue_
City view tell me that the city is getting a substantial amount of culture due to culture process (61 culture as shown in the screenshot) but the process was switched off on the previous turn. 

![20230324153951_1](https://user-images.githubusercontent.com/16341598/227537338-514a985b-1cb7-45f5-a904-dc75fa47d0fa.jpg)

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[aaNebuchadnezzar II_0259 AD-1745.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11062687/aaNebuchadnezzar.II_0259.AD-1745.zip)

_6. Logs_ 

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11062695/Logs.zip)

**Comment by axatin** [comment]
The same issue as #9719, already fixed.

**Comment by saamohod** [comment]
@axatin 
Any workaround to remove the process modifier from the calculation? I tried rearranging-reassigning the build queue, but the ghost process yield is still there.

**Comment by axatin** [comment]
@saamohod I don't think there's any workaround

**Comment by saamohod** [comment]
@axatin Never mind, the new version is out
