### ISSUE TITLE
CTD AI turn

### ISSUE THREAD

**Issue by Tarzan737** [LoneGazebo/Community-Patch-DLL#9734]
_1. Mod Version (X.Y.Z). Current Version: 3.2.2_

NON EUI Version (latest version)

_2. DirectX Version_

11

_3. List of Other Mods_

I upload all mods exept advanced air units mod v 13 (to large) i have changed some lines in my advanced air units mod v 13
as it was buggy before with help from you.. changed all assult to assault lines so that shouldnt be the problem anymore.
long time since CTD

_4. Describe the Issue_
CTD during AI turn

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

in ZIP

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
 
in ZIP

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Should be next turn
[MODS LOGS SAVE .zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11062872/MODS.LOGS.SAVE.zip)

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
This is a crash caused by the Mod "Hex Conquer", see the discussion here: https://forums.civfanatics.com/threads/new-mod-hex-conquer-borders-only.657531/post-16442285
