### ISSUE TITLE
EmbarkExtraVisibility (a UnitPromotions field) adjustment request

### ISSUE THREAD

**Issue by Tekamthi** [LoneGazebo/Community-Patch-DLL#9735]
_1. Mod Version (X.Y.Z). Current Version: 3.2.2_

3.2.2

_2. DirectX Version_

_3. List of Other Mods_

same issue exists w/ or w/o other mods

_4. Describe the Issue_

From playing and modding VP extensively, I infer that land units receive an integer value of 0 embark vision by default.  Though I vaguely recall this working differently in the distant past, VP has for a long time applied minimum 1 vision to all embarked units, ie. an embarked unit with embark vision of "1" appears indistinguishable to player from an embarked unit with embark vision "0"; both can see 1 tile while embarked.  In effect, the 0 embark vision unit gets a free +1 somewhere in the .dll.

VP has a small number of limited-application promos that grant the recipient unit "extra embarked visibility" -- these function by applying a +2 embarkextravisibility value in the UnitPromotions table, in order to achieve the desired +1 effect of what the unit can actually see.  Problems arise in rare instances when two (or more) of these embark vision promos stack: each intends to increase embarked vision by 1, but the first in-game increment, intending to increase player's vision from 1 to 2 tile range, requires the default 0 embark vision receive a +2 in tables.  When a 2nd embark vision promo applies its own +2 embarkextravisibility, the unit receives a total of 4 embark vision range, when only 3 was intended.  This creates big headache to try to mod around.

There are probably a few different ways this could be address, but i believe the following will be the easiest to implement.  I am unsure if this will capture all affected units (eg. do all units get the same embark promo at fishing/optics? or do some get a special version?) but I believe it will:

**Proposed solution:**

1.  Give the existing PROMOTION_EMBARKATION a default value of "1" for EmbarkExtraVisibility field (currently is "0"); and,
2. Change all promotions that currently add 2 EmbarkExtraVisibility, to only 1

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by Tekamthi** [comment]
thanks for looking at this -- since reporting here, I have found a few other promotions that may need an adjustment.  I have implemented a fix in the "recon pay terrain cost" modmod on CF forum, and copied the code here.  I cannot 100% vouch that I have caught all of them, nor that I have anticipated every possible conflict, but this is the list of SQL updates I've been running:

`UPDATE UnitPromotions
SET EmbarkExtraVisibility = 1
WHERE Type = 'PROMOTION_EMBARKATION';

UPDATE UnitPromotions
SET EmbarkExtraVisibility = 1
WHERE Type = 'PROMOTION_EMBARKED_SIGHT';

UPDATE UnitPromotions
SET EmbarkExtraVisibility = 1
WHERE Type = 'PROMOTION_WAR_CANOES';

UPDATE UnitPromotions
SET EmbarkExtraVisibility = 1
WHERE Type = 'PROMOTION_ALLWATER_EMBARKATION';

UPDATE UnitPromotions
SET EmbarkExtraVisibility = 1
WHERE Type = 'PROMOTION_OCEAN_CROSSING';`

**Comment by azum4roll** [comment]
Base embarked sight is now 1. You can drop all those UPDATE statements.

**Comment by Tekamthi** [comment]
Okay that's perfect for my usage.  Curious, what if I decrement this field down to 0?  Will unit have true 0 embark vision, or the false effect of 1?  In other mods I decrement vision to 0 in some cases, or even below, to simulate temporary obstructed vision, but knowing that unit will always have 1 vision regardless of a lower integer value.  Eg I will give a malus of -4 vision to ensure that all units, even those with extra vision, are fully reduced to 1 temporarily.  I don't care if this results in 1 or 0 effect, just don't wanna crash the game (units will commonly have a negative integer value in these scenarios).

Anyway I will test regardless

**Comment by azum4roll** [comment]
0 sight is impossible to have for a unit that can move. You can always test by the Move action whether there are adjacent units.

**Comment by Tekamthi** [comment]
okay i will test, this is what i'm worried about... if i decrement it too much with the new change, will unit be unable to move? anyway thanks for input and the fix

**Comment by azum4roll** [comment]
The DLL still forces a minimum of 1 sight for non-trade units.
