### ISSUE TITLE
AI doesn't send melee units to attack a 0 HP city

### ISSUE THREAD

**Issue by axatin** [LoneGazebo/Community-Patch-DLL#9739]
Mod Version 3.2.1

The AI has shot down my city of Twer to 0 HP with their ranged naval units, but for the last 10 turns or so they haven't been trying to move one single melee naval or (embarked) land unit to the city, which they could easily take.

![Screenshot (339)](https://user-images.githubusercontent.com/95587882/227647863-a6175578-7347-4e7e-be9d-84d540c574d9.png)
[Napoleon_0181 AD-1210.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11066810/Napoleon_0181.AD-1210.zip)

The MilitaryAILog says "180, Russia, requested attack on, Tver, from, Khabarovsk, not possible for lack of units"
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11068446/Logs.zip)

**Comment by ilteroi** [comment]
corner case i would say. i put a lot of effort into preventing suicidal embarkation ...

**Comment by azum4roll** [comment]
With the change to garrison CS (ships don't provide any CS now), the AI should always bring along some melee units on an amphibious conquest so the city doesn't immediately fall after capture.
