### ISSUE TITLE
Bug? Great Barrier Reef located out of any possible city work range

### ISSUE THREAD

**Issue by Mitchsp** [LoneGazebo/Community-Patch-DLL#974]
<img width="680" alt="sin titulo" src="https://cloud.githubusercontent.com/assets/13163824/11944626/c373c84c-a847-11e5-9af4-5d9269a1b22f.png">

**Comment by LoneGazebo** [comment]
Probably related to the great Plot Tile Overhaul of 2015. We'll keep an eye on it for now.
