### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#9743]
v3.1 but should not matter?

so i recently switched to DX9 and low quality textures (don't ask) and now i'm getting these artefacts here:

![image](https://user-images.githubusercontent.com/1358966/227797521-1389724c-aa42-4dfc-9cd7-a11710ab2129.png)

![image](https://user-images.githubusercontent.com/1358966/227797554-706656ca-9f31-41dd-88d2-d58ad92dcd05.png)

does anyone else see this?

**Comment by saamohod** [comment]
I have the same. Funnily, I was thinking this is the way it's supposed to look. Those chequered rags.

**Comment by saamohod** [comment]
> one's the spain ui (hacienda?) and the other is mongolian (ger?)

The Mongolian one is Ordo.

**Comment by azum4roll** [comment]
I'm closing this since there's a newer report
