### ISSUE TITLE
3.3 - Combat Estimator inaccurate

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#9754]
_1. Mod Version (X.Y.Z). Current Version: 3.3.1_

3.3

_2. DirectX Version_

_3. List of Other Mods_

[ModList2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11140071/ModList2.zip)

_4. Describe the Issue_

Looking at this combat estimation:

1) The subs combat strength should be 191.75 based on the values provided. It looks like its not getting the +5% anti-warmonger fervor benefit, as that is the exact difference.
2) the destroyers defense does appear to be accurate.

3) The final damage estimate is not accurate. 
188.5/134.2 should do 37 damage on average.
191.75/134.2 should do 37.4

so regardless of whether the combat numbers shown are accurate or not, the damage estimate overall is still not accurate.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0382 AD-1962.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11140089/AutoSave_0382.AD-1962.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs - Copy.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11140083/Logs.-.Copy.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![image](https://user-images.githubusercontent.com/20593976/229560788-635a1568-7e10-42f1-9e1d-59c357b16b1d.png)

**Comment by azum4roll** [comment]
Should it really have an anti-warmonger fervor when attacking from neutral into enemy's territory? Seems the game can't decide.

**Comment by azum4roll** [comment]
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/14953746/560ad0dd-8f91-497e-8339-4846cadc034a)

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/14953746/f96605b5-b09e-4293-bb24-537c2b4dd10b)

We can rule out anti-warmonger and unit health. Yours didn't have bonus vs submarines so it's not that either.

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/14953746/4ac9b50d-fec7-4a8f-8d80-75ddf12146ea)

Meanwhile, battleship vs fleet destroyer looks normal.

**Comment by azum4roll** [comment]
I think it's fixed now, and I have no idea how.

Report again if it comes up again next version.
