### ISSUE TITLE
Cannot liberate

### ISSUE THREAD

**Issue by der1weihnachtsmann** [LoneGazebo/Community-Patch-DLL#9759]
_1. Mod Version (X.Y.Z). Current Version: 3.3.1_

3.3.1

_3. List of Other Mods_
 
1. Community Events
2. Unique Components
3. Unique City States
4. Unique City States Leaders
5. Global Relations
6. Quick Turns
7. Squads
8. Upgrade all button

_4. Describe the Issue_

Cannot Liberate/Resurect to Life. I recently conquered the last city of Assyria, who was vassalised under Spain. Its also a holy city. I am not at war with Spain anymore.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Savefile.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11192153/Savefile.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

Didnt have logging enabled

_8. Steps to reproduce the Issue (Optional)_

Capture city

_9. Screenshots of the Issue (Optional)_
![image](https://user-images.githubusercontent.com/130388865/230945926-0489abca-a600-48c8-be09-7b844bba12de.png)
![image](https://user-images.githubusercontent.com/130388865/230946132-3f0a4f3c-6f6f-4ae4-9fc8-6628f6a48b47.png)

**Comment by der1weihnachtsmann** [comment]
I was still at war with the former master, Spain, and a cupple turns earlier I destroyed the last city of Assyria.

**Comment by der1weihnachtsmann** [comment]
Yeah but they didnt exist anymore right? Am i still at war with someone when he doesn't exist?

**Comment by axatin** [comment]
Intentional. If you're the one who has conquered the last city of Assyria, you won't be able to bring them back to life again.
