### ISSUE TITLE
Aircraft can move onto non-city tiles

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#976]
Posted by Lerrissirrel: "With the 12/18 version (without the hotfix) I found that if I attack a unit with a bomber, but the unit is outside of the range of the bomber, the bomber actually *moves* to the tile I'm attacking. Then, if I choose, I can click on another city and the bomber moves to that city."

**Comment by ilteroi** [comment]
should be fixed, at least i cannot reproduce
