### ISSUE TITLE
Cannot start a new game, immediate crash to desktop

### ISSUE THREAD

**Issue by TheRealAyCe** [LoneGazebo/Community-Patch-DLL#9764]
_1. Mod Version (3.3.1). Current Version: 3.3.1_

3.3.1, installed via installer, launched via 2K Launcher, ingame Mods menu

_2. DirectX Version_

DX 10/11 on Win7

_3. List of Other Mods_

_4. Describe the Issue_

I cannot even start a game. The game crashes in the map loading screen, either while generating or when generation is done, before I can see a button. I can read the text for a couple of seconds.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11216639/logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

Not there.

_8. Steps to reproduce the Issue (Optional)_

Happens every time I start with these settings.

_9. Screenshots of the Issue (Optional)_
![20230413004856_1](https://user-images.githubusercontent.com/11407231/231603770-4c331ccf-4489-4d10-858c-65ac5fb74959.jpg)
![20230413004857_1](https://user-images.githubusercontent.com/11407231/231603781-3da27d37-7879-4df4-a9aa-da6ff2d92f01.jpg)

Wanted to give this a try again but can't. :(

**Comment by azum4roll** [comment]
Likely fixed
