### ISSUE TITLE
Winged hussar's heavy charge

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#977]
http://forums.civfanatics.com/showpost.php?p=14099675&postcount=9
Pretty sure that units retreating to coast barefoot was fixed in ilteroi's hotfix, but tile swapping is something new.

**Comment by ilteroi** [comment]
can't reproduce

only issue is that the displaced unit is not displayed correctly

![image](https://cloud.githubusercontent.com/assets/1358966/12044344/fd1206ec-ae8f-11e5-9d2d-70a06bcef4c0.png)

but that happens time and again in other cases as well. so i don't know if that's a new thing.

**Comment by Edaka** [comment]
This was posted by Ymir9 in the latest beta thread: "Sadly, this latest update does not seem to resolve the issue with water-walking units.

Reinserting the impassable tags for coast and ocean in saneTerrain.sql seems to solve the issue with winged hussars displacing units into water, but then workboats and units cannot enter/embark into coastal tiles. Maybe I'm doing something wrong. "

Looks like the hussars' heavy charge can still displace units into water. That may be why some users (a handful, actually) are still reporting water walking units. Either that or they're on older versions (I've asked and will report back).

**Comment by ilteroi** [comment]
fixed the heavy charge

**Comment by Ymir9** [comment]
Hello there, this is Ymir reporting in.
I've run into this issue again, it seems to only occur with CBP, not with CP alone.
I've attached some screenshots and saves below.

[Darius I_0033 BC-2020.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/82140/Darius.I_0033.BC-2020.zip)
![capture2](https://cloud.githubusercontent.com/assets/16604514/12191062/fc71f7d2-b59d-11e5-8db5-ceb77372a5c8.JPG)
![capture](https://cloud.githubusercontent.com/assets/16604514/12191063/fc793876-b59d-11e5-9bac-d08f4cfc
[Pachacuti_0033 BC-2020.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/82141/Pachacuti_0033.BC-2020.zip)
9a22.JPG)
