### ISSUE TITLE
Can't Upgrade Lancers

### ISSUE THREAD

**Issue by Gidoza** [LoneGazebo/Community-Patch-DLL#978]
Another weird Horse thingy - in previous versions, I could upgrade Lancers to Cavalry.  Now, I can't.

I have the tech to build Cavalry and can build them.

**Comment by Edaka** [comment]
This has already been noted here: #970 . (Although I admit your description is more informative than that one (: ). Thanks for the report, though!

**Comment by Gidoza** [comment]
Oopsie sorry.  :D   But you're welcome!
