### ISSUE TITLE
3.3 - Anti-sub promotion does not show up in promotion screen

### ISSUE THREAD

**Issue by Stalker012345** [LoneGazebo/Community-Patch-DLL#9780]
_1. Mod Version (X.Y.Z). Current Version: 3.3.1_

3.3

_2. DirectX Version_

_3. List of Other Mods_

[ModList2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11264951/ModList2.zip)

_4. Describe the Issue_

Looking at the screenshots, you can see that the bonus vs sub promotion exists. But when we go to the promotion tree it is not present.

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_
![image](https://user-images.githubusercontent.com/20593976/232866544-ca17e62f-006f-4b74-b2df-e0202a259e7b.png)
![image](https://user-images.githubusercontent.com/20593976/232866586-f05a2a51-4ad2-42e5-8fd6-da1aeafc979c.png)

**Comment by azum4roll** [comment]
Not an issue anymore.
