### ISSUE TITLE
Shock III Doesn't Qualify for Blitz

### ISSUE THREAD

**Issue by Kolaris8472** [LoneGazebo/Community-Patch-DLL#979]
Right now you must have Drill III to get Blitz. Shouldn't Shock III qualify as well?

**Comment by Gidoza** [comment]
I think it's always been like that, but it's a good question.

Quite frankly, though, Blitz is powerful enough that I think it should be dependent on a unit's level (say, level 5 or 6) rather than on a particular upgrade path, as it then makes upgrading very one-dimensional.

**Comment by idontknow12** [comment]
There are several other upgrades that require a specific promotion path. I don't think it's a bug, but i don't know why one path is favored over the other...

**Comment by LoneGazebo** [comment]
This is by design.
