### ISSUE TITLE
3.3.1 - Tradition finisher "Throne Room" not giving +10% culture to capital

### ISSUE THREAD

**Issue by silentreply** [LoneGazebo/Community-Patch-DLL#9791]
_1. Mod Version (X.Y.Z). Current Version: 3.3.1_

_2. DirectX Version_

_3. List of Other Mods_
Squads for VP (v2)
Improved city view (v17)

_4. Describe the Issue_
Tradition finisher "Throne Room" is not applying +10% culture to capital. All other yields are increased correctly in the UI with a +10% city modifier. 
______________________________________________________________________________________
_5. Save Game
[Harun al-Rashid_0144 AD-0680.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11302358/Harun.al-Rashid_0144.AD-0680.zip)

_9. Screenshots of the Issue (Optional)_
![t144 culture](https://user-images.githubusercontent.com/59859911/233794135-4c2920a9-0bc0-4397-af77-e0b84cbf1bce.png)
![t144 gold](https://user-images.githubusercontent.com/59859911/233794138-2b351829-800e-4561-9c19-a5ff4fdbd474.png)

**Comment by n-core** [comment]
Pdan removed it from the Buildings table.
https://github.com/LoneGazebo/Community-Patch-DLL/blob/5a3d96c88dac757d6f5315d967253b3a98b088e2/(2)%20Vox%20Populi/Balance%20Changes/Buildings/NewBuildings.xml#L279-L302

But it seems like he forgot to put it in here.
https://github.com/LoneGazebo/Community-Patch-DLL/blob/5a3d96c88dac757d6f5315d967253b3a98b088e2/(2)%20Vox%20Populi/Balance%20Changes/Buildings/BuildingChanges.sql#L1323-L1342

**Comment by pineappledan** [comment]
WTF, I thought I reverted that? 

Yeah, I didn't put it in the Building_YieldModifiers table because I tried that and it didn't work. that table doesn't have culture hooked up to it and you can only use the Buildings column

**Comment by silentreply** [comment]
I put your change in #9800 in my NewBuildings.xml file and reload but nothing changed. Same at start of the next turn. Would it only apply to newly constructed throne rooms or perhaps require other changes?

**Comment by n-core** [comment]
Yes, the change won't affect the already existing building, which means your existing Throne Room won't be affected.
But, if your city doesn't have Throne Room yet, the new change will apply.
