### ISSUE TITLE
Can't create workboats

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#980]
Despite the fix in the 18/12 version, some guys are stilll reporting the issue: 
http://forums.civfanatics.com/showpost.php?p=14100017&postcount=4085
http://forums.civfanatics.com/showpost.php?p=14098399&postcount=1412
http://forums.civfanatics.com/showpost.php?p=14097288&postcount=22

**Comment by ilteroi** [comment]
cannot reproduce

**Comment by Edaka** [comment]
Yeah, figured so as I don't have it either. It's probably an issue with updating from a previous version due to installation issues. I'll close for now.
