### ISSUE TITLE
CTD during AI's turn

### ISSUE THREAD

**Issue by jdoug312** [LoneGazebo/Community-Patch-DLL#9858]
_1. Mod Version (X.Y.Z). Current Version: 3.5.2_

3.5.2

_2. DirectX Version_

DX11

_3. List of Other Mods_

VP 1-4b
Dolen2 ethnic diversity
Great Prophet Historical Names (v31)
ENW (v2.1)
Quick Turns (v10)
Sukritact's Civ 6 Style City Names

_4. Describe the Issue_

Once I end my turn, the game cycles through the AI and immediately after it starts processing Assyria's turn, the game CTDs.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0277 AD-1814.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11511021/AutoSave_0277.AD-1814.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11511022/logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11511041/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by jdoug312** [comment]
Sorry about that! Logs attached below.

[logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11523743/logs.zip)

**Comment by axatin** [comment]
I can't reproduce this, it seems to be a memory issue on your side. The next version will see some improvements to memory handling which will hopefully reduce the likelihood of such crashes.
