### ISSUE TITLE
Fealty Opener and similar effects rounding issues?

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#9859]
_1. Mod Version (X.Y.Z). Current Version: 3.5.2_
3.5.2
_4. Describe the Issue_

So let's say here.
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/13937047/9472aa16-c5e5-49ca-9ead-a65e7ac7145d)
This Mission cost 100 Faith. When I take Fealty Opener...
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/13937047/38977a3f-e5d7-4b61-bc7e-66f1834f12e4)
Instead of -25% Faith Cost, it becomes 70 Faith rather than 75 Faith. Although some of our Faith Cost are round numbers. Inquisitors recently cost more in Faith from 200 to 300. Taking Fealty Opener reduces them to 220 instead of 225.

I guess this is because hurry investments are now meant to be more round... but does this apply to Faith Purchases as well?

**Comment by axatin** [comment]
All building costs (gold and faith) are rounded to multiples of 10
```
// Make the number not be funky
int iDivisor = /*10*/ GD_INT_GET(GOLD_PURCHASE_VISIBLE_DIVISOR);
iCost /= iDivisor;
iCost *= iDivisor;
```
