### ISSUE TITLE
Pillaging Citadel with <1 Movement causes Graphical Movement Bug

### ISSUE THREAD

**Issue by lipskipolska** [LoneGazebo/Community-Patch-DLL#9862]
_1. Mod Version (X.Y.Z). Current Version: 3.5.3_

3.5.3

_2. DirectX Version_

DX 10 & 11

_3. List of Other Mods_

None

_4. Describe the Issue_

When a unit pillages a citadel with movement below 1, the unit will appear to have movement but still cannot move.

____________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Casimir III_0184 AD-1795.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11523383/Casimir.III_0184.AD-1795.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11523388/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

 1. Locate the city of Wroclaw near Rabat, then declare war on Morocco. (The citadel has no stationed units and a Hussar is in Wroclaw
2. Move the Hussar horse unit near it until you get 1.XX movement left and walk on the citadel tile, now you will have .XX movement (Easiest way is to just walk on at least 1 railroad before)
3. Pillage the tile, and now right-clicking brings up the movement graphic but cannot move and have 0 movement.

_9. Screenshots of the Issue (Optional)_

![Screenshot (9)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/134175941/6c75715d-7a56-4184-aae7-7d90eba38931)

![Screenshot (8)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/134175941/0812a7a4-b6ff-40d5-95cd-29a677db9f1d)

**Comment by ilteroi** [comment]
old version and cannot reproduce

**Comment by azum4roll** [comment]
UI issues aren't graphical.
