### ISSUE TITLE
CountNumWorkedFeature/Improvement/Resource

### ISSUE THREAD

**Issue by JFDaly** [LoneGazebo/Community-Patch-DLL#987]
I have a request for:
**city:CountNumWorkedFeature(featureID)**
**city:CountNumWorkedImprovement(improvementID)**
**city:CountNumWorkedResource(resourceID)**
**city:CountNumImprovement(improvementID)**

This would naturally return the number of a specified feature/improvement/resource worked by the city. It is akin to the city:HasWorkedFeature/Improvement/Resource() method that already exists, so I'm hoping it's not too much to ask.

**Comment by Iamblichos** [comment]
This would be really helpful and help streamline and simplify some lua code

**Comment by LoneGazebo** [comment]
Done. In a test CP version that I will link here shortly.

**Comment by LoneGazebo** [comment]
https://mega.nz/#!zVdyjaQJ!exwAiTD0sGI5j9R7W02o7Tk819ZgpNAtK8ZP1noz7Sw

Test beta. Functions have same syntax as above.

**Comment by JFDaly** [comment]
All works beautifully. Thanks again!
