### ISSUE TITLE
Espionage overview reveals civ identity of an unmet player allied with a CS you've met

### ISSUE THREAD

**Issue by ZetaLambdaNinja** [LoneGazebo/Community-Patch-DLL#9870]
1.  Mod version:  3.5.2

2.  DirectX Version:  DX 10 & 11

3.  Other mods:  None

4.  Describe the Issue:  In the espionage overview, I can see the identity of an unmet Civ that is allied with a city-state that I have met.

5.  Save Game:  [BUG - SpyViewRagusaShowsUnmetCiv.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11546976/BUG.-.SpyViewRagusaShowsUnmetCiv.zip)

6.  Logs:  None; will enable logging for the future.

7.  n/a

8.  Steps to Reproduce:  The problem is readily visible by viewing the Espionage Overview and looking at Ragusa.  Although the Civ has not yet been met, the Allied Civilization marker next to Ragusa's name is Indonesia's.

9.  Screenshots attached:
![BUG_EspionageViewUnmetCiv_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/45955870/5472c7f2-ba4f-45bc-ab55-2e72fce2e18c)
![BUG_EspionageViewUnmetCiv_2](https://github.com/LoneGazebo/Community-Patch-DLL/assets/45955870/cfade669-7c55-4d77-a645-fe6fd65232ed)

**Comment by axatin** [comment]
I already fixed this for the next version as part of the espionage rework
