### ISSUE TITLE
desert wheat / bad yield

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#988]
![image](https://cloud.githubusercontent.com/assets/1358966/11969261/66c50e96-a917-11e5-964c-f42e4872d34c.png)

somethings not right here

**Comment by LoneGazebo** [comment]
I think that's right. Deserts have base 0 yield, wheat +1, farm +1.

**Comment by ilteroi** [comment]
hmm. makes sense, now that i think about it.

but i've got another one:

![image](https://cloud.githubusercontent.com/assets/1358966/11969776/6729d756-a91f-11e5-9b91-7bd5c5fee12b.png)

should ice on coast give two food?

**Comment by LoneGazebo** [comment]
Ice may not be set as an overriding feature yield. If we set it that way it'll fix that.

**Comment by LoneGazebo** [comment]
That an element of the features xml table.

**Comment by Hokath** [comment]
Perhaps ice set food to zero before, but now you changed that impassibility thing for jungles, it doesn't?
