### ISSUE TITLE
peace deal negotiation

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#989]
![image](https://cloud.githubusercontent.com/assets/1358966/11969484/408351ea-a91a-11e5-940e-8e9a5ffbe5aa.png)

i would expect a value of around 256 + (50 * 5)*0.8 -> 456. bug or is the raw sum multiplied because they hate me?

playing around some more i found that 
- 1 jade is 800
- 1 horse is 800
- 1 paper is 2000! this is insane. nobody ever needs paper.
- capitulation is also 2000
- a size 6 city is 740

so i think cities are rather cheap right now and paper definitely needs to be reduced.

**Comment by LoneGazebo** [comment]
I think paper is high because of resource_flavor. Cities probably need a base per-pop value boost.

**Comment by LoneGazebo** [comment]
Value is higher because of hate yep. We could introduce a bWar bool for peace deals to remove emotion.

**Comment by Edaka** [comment]
By the way, adding gold to the player's side when an AI is surrendering will increase the peace deal value. 
![negot1](https://cloud.githubusercontent.com/assets/12978597/11988038/2ae7494e-a9f2-11e5-87fa-685a6a6e18a1.jpg)

**Comment by Edaka** [comment]
Related to my previous post (posted by Gidoza on the forum): 

"Making peace with an opponent - have a max value and the actual value. I add stuff from HIS side, and the actual value goes up (which makes sense) - I add stuff from my side, and the value goes down. 

But if I add lots of stuff from my side first, the actual value goes up in the same way! And the actual value goes down if I add stuff from his side. "

**Comment by LoneGazebo** [comment]
This is why I'm not going to add deal values to lua generally - values change erratically.

In any case, I'm going to make it so that non-surrendering players cannot have things added to their side of the deal. Too gamey.
G
