### ISSUE TITLE
Repository Size / History

### ISSUE THREAD

**Issue by RecursiveVision** [LoneGazebo/Community-Patch-DLL#9901]
The repository is too large (4.39 GB for me), as ilteroi has pointed out before, and cloning a new copy takes ages. This is a barrier to entry for new contributors. I've attached a list of all files in reverse order of size. The main culprits are .civ5mod and .dll files.

In addition, the history itself is an enormous mess and difficult to search through.

I've been experimenting a bit with interactive rebase and the Git terminal, and I've looked into git-filter-repo. I'm not going to make any changes to master at this time. Any commit history surgery will require a lot of planning, and I wouldn't proceed without being confident in what I'm doing. I'm importing this repository to a new one on my own account, where I can experiment with the history without risking any damage here.

However, in the future, I'd be interested in cleaning up the repository history, perhaps during one of the quieter months. This is obviously challenging, however, as rewriting history requires development to pause and everyone to rebase, not to mention like any surgery it has complications.

It might be possible to do the rewriting on a copy of the repository, and then for Gazebo to re-import it with the same URL, which would avoid the development slowdown. However, that would likely delete all the issue and pull request history.

Potential targets:
- Removing all history of the compiled .dll and .civ5mod files; perhaps these can be transferred to releases? Would take a long time to build every old version. We *could* just remove all history prior to 1.0 but I have a feeling people might be against that, and I'm not super fond of the idea myself.

- Removing the giant commits where tons of useless files were added and then deleted.

- If merge commits contain all the changes from the commits they import, then the imported commits can be removed from the history, leaving only the merge commit? Or would people be against this? Is there an alternative?

- Multiple commits made in quick succession can be squashed together.

- At one point Gazebo squashed all the changes between one release and the next into a single new release commit. Would that be desirable?

This is not something I plan on doing soon, and certainly not before the project to clean up the database in (2) is completed, but still - any thoughts?

Tips? Better ways of doing this? Should we just move to a new repo altogether?

[blob-shas-and-paths.txt](https://github.com/LoneGazebo/Community-Patch-DLL/files/11588563/blob-shas-and-paths.txt)

**Comment by n-core** [comment]
> The main culprits are **.civ5mod** and .dll files.

First, there's no .civ5mod file (compressed version, ready for Steam Workshop file of a mod) on this mod since the Package output folder is ignored through .gitignore.

If there are those files in the past, then you can easily delete them now without a problem.
DLL files, however, are part of the Community Patch Modbuddy project file. All future collaborators must build their own DLL first and then build the Community Patch project in Modbuddy.

This is probably going to be a minor inconvenience for non-DLL modders, including me. But I can just grab the DLL file from the `MODS` CP folder.

> Should we just move to a new repo altogether?

Big no, tracking changes is important for balance. As some contributors probably want to see into the past version of the mod.

**Comment by azum4roll** [comment]
If you want to test your changes mid-release, you would need to build the DLL anyway.

**Comment by ilteroi** [comment]
it was always a stupid idea to include compiled binaries in the repository.

also the git history is an embarassment, kill it already. just one force-push and we have a clean slate!

**Comment by azum4roll** [comment]
4 for pre-1.0, 2 for post-1.0
