### ISSUE TITLE
MPModpack 3.6.1 - Maptype 'Ring' does not work

### ISSUE THREAD

**Issue by Tpk2210x** [LoneGazebo/Community-Patch-DLL#9902]
_1. Mod Version (X.Y.Z). Current Version: 3.6.2_
Vox Populi version 3.6.1, modpack link: https://drive.google.com/file/d/1MefkxRRgMn5JM3YQF98Xp7POiIT99x1L/view?usp=share_link
(pasted from Cyclopia31's issue #9885)

2. Using DX 10/11

_3. List of Other Mods_
None

_4. Describe the Issue_
While the 3.6.1 modpack is correctly installed, it is not possible to start a game with the maptype 'Ring' (Singleplayer -> Setup Game).
The Game freezes and does not respond until i kill the application with windows-task-manager.
Every other Maptype is working properly.  Game Options can be seen in a screenshot below.

I tested the Modpack-Version of 3.5.3 and here it worked just fine. Probably has something to do with changes in Turn 0
desync-fixing? But im obviously not sure ! 
https://github.com/LoneGazebo/Community-Patch-DLL/issues/9864#issuecomment-1561509865

Thank you all for your hard work !
______________________________________________________________________________________

_9. Screenshots of the Issue (Optional)_
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/134875247/a6f5e7f8-0cdc-4e9b-84e5-483eb9e20f7d)
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/134875247/00088247-ea13-4264-8c00-3ab86c83572a)

**Comment by seroperson** [comment]
I think it is related to #9775 and just fires randomly, not caused by something from 3.6.1

**Comment by azum4roll** [comment]
Are you using the Ring map included with VP? For modpack you'll need to move the VP map to the Maps folder first.
