### ISSUE TITLE
Game.ScoreBelief (PlayerID iPlayer, BeliefType iBeliefType) return 

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#9903]
Within CvReligionClasses, there is a method that ScoreBelief I would like to be exposed to the Lua framework to allow the human player some suggestions on what the AI thinks is the best belief for them. I can do the UI work, I just need some method that looks like Game.ScoreBelief or Player.ScoreBelief(iBeliefType) or anything like that to return a score when a belief from a player's "AI" is chosen. 

Many players would love it, I would think.

**Comment by ilteroi** [comment]
done. ca081e732492efbb6237a9b68991f2f2fc6c7d89

**Comment by azum4roll** [comment]
Can you also do one for buildings (+units), techs and policies? It would be great for debugging (without digging into logs which lack the current game state).

**Comment by ilteroi** [comment]
well for units and building a lua interface should already be there, that's how the advisor recommendations work.

for tech and policy, i'll see what i can do if you promise to do the UI integration :)

seriously, i also think it would be nice to see what the AI would prefer for testing and as a guide for new players.

**Comment by ilteroi** [comment]
nah my last comment was @azum4roll 

anyway i checked ...

1. for tech there is RecommendNextTech() but interestingly it's not exposed to lua
2. for policy there is nothing, but would be easy to create a method like RecommendNextPolicy()
3. however, in both cases the algorithm is based on flavors, so it's unclear if the output is useful for a human player

**Comment by ilteroi** [comment]
try this for CvGame::ScoreBelief(PlayerType, BeliefType)

[CvGameCore_Expansion2_ca081e7.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11609663/CvGameCore_Expansion2_ca081e7.zip)

**Comment by ilteroi** [comment]
nice. but what would have been your picks?
