### ISSUE TITLE
Player:GetHistoricEventTourism(iHistoricEvents, pCity) and Player:GetNumHistoricEventTourism(iHistoricEvents)

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#9908]
- 0 | HISTORIC_EVENT_ERA_CHANGE | Player
- 1 | HISTORIC_EVENT_WORLD_WONDER | Player
- 2 | HISTORIC_EVENT_GREAT_PERSON | Player
- 3 | HISTORIC_EVENT_WON_WAR | Player
- 4 | HISTORIC_EVENT_GOLDEN_AGE | Player
- 5 | HISTORIC_EVENT_DIG | Player
- 6 | HISTORIC_EVENT_TRADE_LAND | requires City
- 7 | HISTORIC_EVENT_TRADE_SEA | requires City
- 8 | HISTORIC_EVENT_TRADE_CS | Player (Surprisingly, City does not affect them)

I can definitely wiggle some room in Culture Overview to talk about how Historic Events and their (most potential) yields if they achieve them. It would also be nice to get GetNumHistoricEventTourism since that is already given to us (for Arabia) and can help show us how many Historic Events of this type have been achieved for the selected player.
![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/13937047/17cfe0d3-06fd-43a6-82b2-885fd325c957)

Of course when it comes to the land trade and sea trade, I can put in (Parenthesis) Like +300 (+100) to indicate that it has a weaker tourism boost with all known Civilizations versus the one you are trading with actively.

**Comment by azum4roll** [comment]
How would you show the trade route ones when they differ between cities?

**Comment by jarcast** [comment]
To complete the picture it would also be nice for modding purposes to have a related game event for when a historic event is triggered or completed. For example:

HistoricEventTriggered(PlayerID iPlayer, CityID iCity, HistoricEventType iHistoricEvent)

HistoricEventCompleted(PlayerID iPlayer, CityID iCity, HistoricEventType iHistoricEvent)
