### ISSUE TITLE
CTD next round leads to crash

### ISSUE THREAD

**Issue by paul645625345623452** [LoneGazebo/Community-Patch-DLL#9911]
_1. Mod Version (X.Y.Z). Current Version: 3.6.2_
Mod Version 3.6.2 EUI 43 CIV + EUI

_2. DirectX Version_
DX11

_3. List of Other Mods_
CIV-Linked Great Generals v.11
Contextual Unit Names v.3
Contextual Unit Names-UI v.3
InfoAddict v.22
Ingame Editor v.39
JFD's Cultural Diversity all 6 mods
Quick Turns v. 10
Unit Path Viewer v.10
Wonder Race v.7
Yet another Erth Map Pack v. 22

_4. Describe the Issue_
next round leads to crash

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
[LastSaveBeforeCrashAutoSave_0291 BC-0590.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11612488/LastSaveBeforeCrashAutoSave_0291.BC-0590.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11612690/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11612705/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_
End round 291

_9. Screenshots of the Issue (Optional)_

**Comment by paul645625345623452** [comment]
[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11621632/Logs.zip)

**Comment by axatin** [comment]
Same issue as #9968, fixed.
