### ISSUE TITLE
City screens bug out after building Firaxite cooperation headquarters.

### ISSUE THREAD

**Issue by Kavachi** [LoneGazebo/Community-Patch-DLL#992]
I can't choose production in any city besides the city I build my Firaxite cooperation headquarters in. I also can't change any production in cities already producing something. I think this is the error as stated in the LUA log:

 Runtime Error: C:\Users\(This user*)\Documents\My Games\Sid Meier's Civilization 5\MODS\Community Balance Patch - Compatibility Files (No-EUI) (8-6)\LUA\InfoTooltipInclude.lua:335: attempt to index global 'city' (a nil value)

*name blanked out for privacy reasons.

Does anyone know how to solve this issue? Reloading has no effect.

**Comment by LoneGazebo** [comment]
Navigate to the file and line indicated and replace 'city' with 'pCity.'

**Comment by LoneGazebo** [comment]
Line 335 is the indicated line.

**Comment by Kavachi** [comment]
It worked like a charm. I don't understand any LUA or coding in general so I was quite lost. I'm really enjoying the mod so far, thanks for all the hard work!
