### ISSUE TITLE
CTD Next Turn VP 3.6.2

### ISSUE THREAD

**Issue by R3P0FFXI** [LoneGazebo/Community-Patch-DLL#9925]
_1. Mod Version (X.Y.Z). Current Version: 3.6.2_

3.6.2

_2. DirectX Version_

DX11

_3. List of Other Mods_

![Capture](https://github.com/LoneGazebo/Community-Patch-DLL/assets/10148511/95f57edf-8142-4915-9675-5e7b0892e28b)

_4. Describe the Issue_

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[Crash Next Turn.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11646536/Crash.Next.Turn.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs_2.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11646531/Logs_2.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11646537/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

Hit Next game will CTD

_9. Screenshots of the Issue (Optional)_

**Comment by axatin** [comment]
can't load the save game, no longer possible to get the old versions of some of the modmods used.
