### ISSUE TITLE
FEATURE REQUEST: OPTION TO DISABLE BARBARIAN EXPERIENCE CAP LIMIT

### ISSUE THREAD

**Issue by jayeye2011** [LoneGazebo/Community-Patch-DLL#9929]
Current version 3.6.2

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

This feature request is one to provide the option of disabling the experience cap for killing barbarian units, could either be by adding the option to the advanced settings game setup window or just adding a true/false flag to one of the sql (diplo?) files. At one time, there was a bug that did this that got fixed. (https://github.com/LoneGazebo/Community-Patch-DLL/pull/9615 ) which should provide a starting point for a code change place to add a enable/disable logic test code statement. The option of disabling the barb xp cap is no worse than other existing options like allowing great general/admiral points for killing barbs, or disabling bad or neutral events, or enabling ancient ruins. These options, while being a mild cheat,  can add some fun to the game for some of the more casual Vox Populi players.
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by n-core** [comment]
It has been requested before. I don't think this will get implemented.
https://forums.civfanatics.com/threads/4-vt-remove-xp-cap-from-barbarians-and-cs-as-an-advanced-option-resubmission.683241/

**Comment by jayeye2011** [comment]
Doesn't hurt to ask even if it's just a QoL improvement. Main dev is free to just say no way and close out this request, no hard feelings.

**Comment by jayeye2011** [comment]
@RecursiveVision While that works when you use the regular mod setup game start, it does not work if you are playing using a MP_MODPACK.

**Comment by jayeye2011** [comment]
Also, there are two CoreDefines.sql files, 
Sid Meier's Civilization V\Assets\DLC\MP_MODSPACK\Mods\(1) Community Patch (v 117)\Core Files\Core Values\CoreDefines.sql
Sid Meier's Civilization V\Assets\DLC\MP_MODSPACK\Mods\(2) Vox Populi (v 16)\Balance Changes\CoreDefines.sql
although only the one in Balance Changes has the barb xp cap setting in it

**Comment by azum4roll** [comment]
> @RecursiveVision While that works when you use the regular mod setup game start, it does not work if you are playing using a MP_MODPACK.

Search in Civ5Units.xml

**Comment by jayeye2011** [comment]
@azum4roll  Thanks man, that worked! Very Happy.
