### ISSUE TITLE
City's border growth broken logic

### ISSUE THREAD

**Issue by saamohod** [LoneGazebo/Community-Patch-DLL#9944]
_1. Mod Version (X.Y.Z). Current Version: 3.6.2_

_4. Describe the Issue_
City borders expand into resource-less tiles while ignoring tile with a resource. In the given case a tile with deer next to mountains is ignored in favor of regular forest tiles

![20230620104713_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/16341598/0b8fa430-84dc-45f3-91a0-edc45345b0ce)

**Comment by Stalker012345** [comment]
I could MAAAAYBE respect the one on the left because its open land (which gets expansion priority) but as far as I can tell the deer is equal in spread difficulty and distance from those forest tiles, so yeah that looks like an issue to me.

**Comment by ilteroi** [comment]
it's probably the river crossing
