### ISSUE TITLE
Negotiating peace on the turn of a city capture

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#995]
Right on the turn of capturing an enemy city (and after doing so) I was able to negotiate peace - apparently no cooldown was in place. One turn later, the AI was refusing peace negotiations as it should have been, though.

**Comment by LoneGazebo** [comment]
We'll need more evidence of this, but the AI's peace deal logic was loosened a bit in the current version.
G

**Comment by LoneGazebo** [comment]
Using 1/3 version, any savegames with this would be appreciated.
