### ISSUE TITLE
Movement over water preview

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#996]
Seems that it displays the amount of tiles one can move over water incorrectly, but only when the unit is on land. 
![pathfind1](https://cloud.githubusercontent.com/assets/12978597/11988084/c2afd566-a9f2-11e5-829b-d928f1436b23.jpg)
![pathfind2](https://cloud.githubusercontent.com/assets/12978597/11988085/c3ee3bd4-a9f2-11e5-89a7-abb3f4d1e312.jpg)

**Comment by ilteroi** [comment]
not sure i understand. embarking ends your turn!

**Comment by Hokath** [comment]
as in it takes 2 turns to get there, but the initial preview said 3

**Comment by Edaka** [comment]
I'll post a couple of more screenshots when I can. Basically, when your unit is on land and you set a path over water, the pathfinder shows that you'll be moving 2 tiles per turn, when in fact it's 3 tiles per turn when embarked (and more with tech)

**Comment by Iamblichos** [comment]
Nah, it's still 3 turns. 1) to embark, 2) to end at the yellow dot, and 3) to disembark. It's just that the two paths have two different routes for the same amount of turns.

**Comment by Hokath** [comment]
not seeing it. You get to the grassland forest on the second turn, 1 to embark and then you move 3 tiles, disembarking.

**Comment by Kolaris8472** [comment]
I know what he's talking about. Except for me the preview was 1 tile per turn while Embarked.

**Comment by Hokath** [comment]
what's going on is that on land, it assumes that onced embarked you will still only have 2 moves per turn. If I send a land unit to a far away continent, it says it will take like 18 turns, when in fact it is more like 6.

**Comment by Edaka** [comment]
![watermov](https://cloud.githubusercontent.com/assets/12978597/11998784/d5bae938-aab6-11e5-87f1-de6f60315d30.jpg)

**Comment by Iamblichos** [comment]
I see what you mean now.

**Comment by ilteroi** [comment]
i know where to look now :)

**Comment by ilteroi** [comment]
ok. seems to me this only occurs with explorers. how many movement points are they supposed to have on water? scouts and other embarked units get 3. explorers only get 2 at the moment.

![image](https://cloud.githubusercontent.com/assets/1358966/12008160/68b4af12-ac29-11e5-9e89-988fbbb66def.png)
