### ISSUE TITLE
deal oddities

### ISSUE THREAD

**Issue by ilteroi** [LoneGazebo/Community-Patch-DLL#9969]
v3.7.0

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/8f644ef2-b412-4aa6-ae5f-2995f6175933)

* text doesn't match the offer
* offer seems a bit on the high side? background info: they are my vassals, don't know if that has any impact

**Comment by ilteroi** [comment]
same turn ...

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/531ae470-c890-459e-b4eb-5085a48f7459)

in this case it's even weirder, because i did not propose this arabian sphere of influence ... obviously arabia did. any they are my long term allies, so if anything the russians should offer a YES vote.

**Comment by ilteroi** [comment]
can provide save file if needed

**Comment by KungCheops** [comment]
I've had many cases where an AI wants to buy a resource from me, them not having any gpt to trade, them adding something else with a much higher value and finally replacing the resource with something completely different that matches the value of what they offered.

Whenever this happens I always try to

1. Remove all the items from the trade window
2. Readd whatever they were probably trying to buy
3. Click the "what would make this work" button

Usually (always) it ends up with the same strange offer as what they initially offered, with the item of interest removed.

Would be nice if there was a way for the AI to "lock in" a particular item in the trade screen when they come to give you an offer. Or that the items already in the trade window are always kept when you click the "what would make this work" button. Guess it would be the same logic update.

**Comment by ilteroi** [comment]
more mystery text

![image](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1358966/f46ea6df-d517-4b55-9996-ea8803ed7faa)

also here's the savegame: 

[weird_deals_Post_0280 AD-1820.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11940967/weird_deals_Post_0280.AD-1820.zip)

the usual, plus infoaddict/removebanluxury

**Comment by axatin** [comment]
Fixed the text issues, and also the issue that offered items are removed when equalizing (both were caused by the same error, the AI clearing the wrong side of the deal).

Vassals always give better deals than other players. Russia asking you to vote No on the SoI is not a bug. They want you to vote No because _they_ want the SoI not to pass, it doesn't matter for them who proposed it or how you feel about it.
