### ISSUE TITLE
Request: GameEvents.UnitCanBuild (PlayerID, UnitID, BuildActionType)

### ISSUE THREAD

**Issue by TechpriestEnginseer** [LoneGazebo/Community-Patch-DLL#997]
Would like to request for a LUA event that will allow a unit to construct improvements under specific LUA conditions. Similar to the GameEvents.CityCanConstruct, returning false lead to the unit's ability to build the improvement and vice versa.

I'm making a mod at the moment where chopping forests with other nearby forests take longer than single forests by making two exact chop forest action with different <Time> and this LUA event would allow the worker to use one of the two chop forest action based on how many forest tiles are near the worker.

**Comment by Iamblichos** [comment]
Also Reference:  https://github.com/LoneGazebo/Community-Patch-DLL/issues/933

For trait specific.

**Comment by Iamblichos** [comment]
But this is another helpful function.

**Comment by JFDaly** [comment]
I believe this already exists in the form of **GameEvents.PlayerCanBuild.Add(function(iPlayer, iUnit, iX, iY, iBuild) return true end)**. There is also **GameEvents.PlotCanImprove.Add(function(iX, iY, iImprovement) return true end)**

**Comment by TechpriestEnginseer** [comment]
Yeah I just noticed it an hour ago after realizing that PlayerCanBuild is different from Unit:CanBuild.
