### ISSUE TITLE
AI focus fire

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#998]
I've noticed that AI will often not focus fire when it can to swiftly kill one unit - it will disperse damage over a handful of units instead. Take this screenshot for example:
![focusfire](https://cloud.githubusercontent.com/assets/12978597/11998738/98f8c1a6-aab5-11e5-86a9-91e42dcb1565.jpg)
You can see my musketman to the left, a foreign legion to the top and another foreign legion to the right (on the railroad). The AI (Portugal) has three ranged units - a city, a volley gun in the city and a frigate. 

The thing is that it could have focus fired my musketman to the left with all three and that would've probably killed him. However, the AI did the following: bombard the foreign legion to the top with the city, the foreign legion to the left with the frigate and the musketman with the volley gun.

**Comment by Hokath** [comment]
I've noticed it doing this quite often

**Comment by ilteroi** [comment]
yeah i've been meaning to look at that. from what it looks like in the code, they should concentrate on one enemy at a time. but apparently it doesn't work every time
