### ISSUE TITLE
Barbarian camps spawn only on coast

### ISSUE THREAD

**Issue by APLion-nsk** [LoneGazebo/Community-Patch-DLL#9982]
_1. Mod Version (X.Y.Z). Current Version: 3.7.5_

3.7.4

_2. DirectX Version_

_3. List of Other Mods_

IGE+

_4. Describe the Issue_

Barbarians spawn only on coastal tiles (lakes included). I've noticed this for a long time in all of my games
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_0023 BC-2620.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11971258/AutoSave_0023.BC-2620.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11971263/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

Play any game. In attached save you can scout the map and check that every camp except one is coastal (and I think that one is not only because of the mountain). In any case, that's not 33% of all camps

_9. Screenshots of the Issue (Optional)_
![20230707015013_1](https://github.com/LoneGazebo/Community-Patch-DLL/assets/72704750/c68e54ab-8a8b-4982-8cdb-b737be4d5974)

**Comment by APLion-nsk** [comment]
Bump

It seems pretty dumb that I can reliably ignore inland when hunting barb camps or defending caravans.

**Comment by azum4roll** [comment]
There's literally a non-coastal barb camp on your screenshot

**Comment by APLion-nsk** [comment]
It's still not 33% of all camps on a map. Have you even read my descriprion?

"Play any game. In attached save you can scout the map and check that every camp except one is coastal (and I think that one is not only because of the mountain). In any case, that's not 33% of all camps"

**Comment by azum4roll** [comment]
If there are more than 33% existing camps being coastal, the game picks the next camp out of all eligible plots, not necessarily non-coast.

Lakeside is not coast by definition either way, and I keep having non-coastal camps spawn in my games.
