### ISSUE TITLE
AI Trade Request with wrong Dialog

### ISSUE THREAD

**Issue by kienerj** [LoneGazebo/Community-Patch-DLL#9985]
1. Mod Version (X.Y.Z). Current Version: 3.7.3 EUI 43 Civ

4. Describe the Issue

Later in game I got several trade requests by AI "Asking to purchase a technology" but no technology was involved in the trade proposals.

![Civ5Screen0108](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1567309/b3d7ffd6-e26d-425d-a21a-f51342f444d8)
![Civ5Screen0109](https://github.com/LoneGazebo/Community-Patch-DLL/assets/1567309/cb6e612f-e94e-4661-9b60-534bbf95a6f2)

**Comment by axatin** [comment]
Fixed in the new version.
