### ISSUE TITLE
"More wonders" crash on load/restart

### ISSUE THREAD

**Issue by APLion-nsk** [LoneGazebo/Community-Patch-DLL#9988]
_1. Mod Version (X.Y.Z). Current Version: 3.7.6_

3.7.6

_2. DirectX Version_

_3. List of Other Mods_

IGE+
More wonders for VP
Tectonic map script

zip with mods 
https://drive.google.com/file/d/1nl-m9QCEFAGcrG93cpCvljTNaF6nvVCo/view?usp=sharing

_4. Describe the Issue_

"More wonders" crashes the game on in-game load and restart. I think the culprit is tectonic map script
______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

[AutoSave_Initial_0000 BC-4000.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11994511/AutoSave_Initial_0000.BC-4000.zip)

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11994512/Logs.zip)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

[CvMiniDump.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/11994513/CvMiniDump.zip)

_8. Steps to reproduce the Issue (Optional)_

Load the save. press restart

_9. Screenshots of the Issue (Optional)_

**Comment by n-core** [comment]
I don't think you can report it here.
But that said, this problem is occurring with other mods enabled, so this could be a VP problem.

Before someone close this issue, please take a look at the minidump file and check what's causing the crash.

**Comment by adaneslavo** [comment]
It's worth mentioning that loading the game from main menu works fine. CTDs only occur when you load game from the already run game. When you load exactly the same save from main menu everything goes smoothly.
