### ISSUE TITLE
Can't gift resource improvements to city states

### ISSUE THREAD

**Issue by Edaka** [LoneGazebo/Community-Patch-DLL#999]
![improvgift](https://cloud.githubusercontent.com/assets/12978597/11998810/d3249e7a-aab7-11e5-8436-2bef38a20055.jpg)
![improvgift2](https://cloud.githubusercontent.com/assets/12978597/11998811/d4c1895a-aab7-11e5-9d66-73402d8d337a.jpg)
The city state here has an unimproved source of aluminum, as in it doesn't have a mine on it. There is a farm on top, though, and I suspect it might be causing the problem. Can't make the gift despite having enough gold.

**Comment by TechpriestEnginseer** [comment]
Do you have the required tech?

**Comment by Edaka** [comment]
Well, I have the one that reveals aluminum (electricity?). Mining too. I don't think you need anything else.

**Comment by LoneGazebo** [comment]
I think the CS has to have the tech as well, IIRC.

**Comment by LoneGazebo** [comment]
Using the 1/3 version, any savegames with this would be appreciated.
