### ISSUE TITLE
Can't choose social policies

### ISSUE THREAD

**Issue by maxrewarding** [LoneGazebo/Community-Patch-DLL#9996]
_1. Mod Version (3.7.7).

_2. DirectX Version_
N/A

_3. List of Other Mods_
None

_4. Describe the Issue_
Everytime I reach the point where I have to pick a social policy, I can't. Clicking the button does nothing and I get stuck on that turn. I've tried enabling the option that allows you to save picking social policies until later but then I just can't open the menu. I've reinstalled the game, reinstalled the mod multiple times, and more but it still happens every time.

_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_
I don't have these, sorry

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_
[Lua.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12034580/Lua.log)
[modding.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12034581/modding.log)
[net_message_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12034582/net_message_debug.log)
[stopwatch.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12034583/stopwatch.log)
[system_init.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12034584/system_init.log)
[xml.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12034585/xml.log)
[xml-perf.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12034586/xml-perf.log)
[achievements_debug.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12034587/achievements_debug.log)
[APP.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12034588/APP.log)
[Database.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12034589/Database.log)
[init_host.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12034590/init_host.log)
[Localization.log](https://github.com/LoneGazebo/Community-Patch-DLL/files/12034591/Localization.log)

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_
N/A

_8. Steps to reproduce the Issue (Optional)_
This happens everytime I play

_9. Screenshots of the Issue (Optional)_

https://github.com/LoneGazebo/Community-Patch-DLL/assets/139414046/035bab93-9058-4508-9f33-d560717036c8
(I'm right clicking and left clicking)

**Comment by maxrewarding** [comment]
[ezyzip.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12053542/ezyzip.zip)

Here are my logs

**Comment by n-core** [comment]
It's a map generation issue and its domino effects to many other stuff. What is the map do you play?
```
[340540.500] Runtime Error: C:\Users\maxvv\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Vox Populi\Core Files\CoreLua\AssignStartingPlots.lua:8660: attempt to compare nil with number
stack traceback:
	C:\Users\maxvv\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Vox Populi\Core Files\CoreLua\AssignStartingPlots.lua:8660: in function 'AssignLuxuryToRegion'
	C:\Users\maxvv\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Vox Populi\Core Files\CoreLua\AssignStartingPlots.lua:8894: in function 'AssignLuxuryRoles'
	C:\Users\maxvv\Documents\My Games\Sid Meier's Civilization 5\MODS\(2) Vox Populi\Core Files\CoreLua\AssignStartingPlots.lua:11527: in function 'PlaceResourcesAndCityStates'
	Assets\Maps\Continents.lua:321: in function 'StartPlotSystem'
	Assets\DLC\Expansion2\Gameplay\Lua\MapGenerator.lua:815: in function <Assets\DLC\Expansion2\Gameplay\Lua\MapGenerator.lua:779>
	=[C]: ?
```

**Comment by maxrewarding** [comment]
I play on the continents map

**Comment by azum4roll** [comment]
BALANCE_MOD_POLICIES_NEEDED_IDEOLOGY doesn't exist in your Defines table. It should be set in (1). Maybe reinstall VP and try again?

**Comment by axatin** [comment]
There's definitely something wrong with the installation here. If you use any modpacks, you need to delete them first (check the folder C:\...\Steam\steamapps\common\Sid Meier's Civilization V\Assets\DLC). You also need to make sure you have all DLCs and Expansions installed. You can also try installing the mods manually, see the instructions [here](https://forums.civfanatics.com/threads/community-patch-how-to-install.528034/).

Reopen the issue if all of these don't help.
