### ISSUE TITLE
Constabulary not improving City Spy Resistance

### ISSUE THREAD

**Issue by russp77** [LoneGazebo/Community-Patch-DLL#9997]
The constabulary does not improve City Spy Resistance. I'm assuming that this wasn't changed in the recent update (I searched and I didn't find anything.) Also while I'm at it how does unhappiness work with City Spy Resistance. Attila's Court and Clusium both have positive happiness but Clusium has a negative modifier for unhappiness to spy resistance. (Also Clusium has built Public Works twice.)

Modlist: BarbarianXP (redundant I know-I changed the value in CoreDefines.spl)
	Info Addict
	Ingame Editor

I'm using version 3.7.5 EUI 43 Civ version

Thanks.

![Screenshot (209)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/139479664/7ba00434-fe3c-4302-8e1c-56501675b428)

![Screenshot (208)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/139479664/46cc4bb3-2761-4968-b959-ca0ef3f370e2)

![Screenshot (210)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/139479664/c5804d16-c35a-4eb3-8d13-f6e44c86d578)

![Screenshot (211)](https://github.com/LoneGazebo/Community-Patch-DLL/assets/139479664/99c16e84-60d8-44d8-af5c-430559f0f3fc)

[Attila_0678 AD-1566.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12041807/Attila_0678.AD-1566.zip)

_1. Mod Version (X.Y.Z). Current Version: 3.7.6_

_2. DirectX Version_

_3. List of Other Mods_

_4. Describe the Issue_

______________________________________________________________________________________
_5. Save Game From 1 Turn Before (ALWAYS ATTACH THIS IF POSSIBLE)_

_6. Logs (ALWAYS ATTACH THESE IF POSSIBLE)_

_7. CvMiniDump.dmp File (ATTACH IF REPORTING A GAME CRASH)_

_8. Steps to reproduce the Issue (Optional)_

_9. Screenshots of the Issue (Optional)_

**Comment by russp77** [comment]
I just spent an hour and a half replaying the transition into the Renaissance Era and taking screenshots. The TLDR version is that
1-When I place a spy in a city counterespionage goes to +25%
2-When surveillance is established this does not change based on the mission (it doesn't go to +50%)
3-When the network is established a few turns later the percentage doesn't change.
4-Building a constabulary does not increase the spy resistance of a city.

I took over 90 screenshots playing through about 15 turns. If needed I'll post them (3 cities from each turn and before and after changes.)

Also does spy resistance change if net happiness falls below 5? I didn't see that mentioned anywhere. Thanks.

**Comment by russp77** [comment]
My kids make fun of me when I talk to myself.
After more digging I have a couple more questions. I looked into BuildingChanges.sql in Vox Populi and the EspionageModifier is set to -50. Shouldn't it be -25? or +25?
I also looked into PrimaryEspionageEvents.xml and I saw that in the CounterSpy section there was an IDModifier set to the percentage of the various missions available. Shouldn't there also an EspionageModifier?

I'm also including the logs from my game but I don't think they have useful info.

[Logs.zip](https://github.com/LoneGazebo/Community-Patch-DLL/files/12064863/Logs.zip)

Well sorry for not waiting for a reply but I gathered this info over several days. Thanks.

**Comment by axatin** [comment]
Constabularies not improving Spy Resistance is indeed a bug that was caused by the changes in the last version.

The unhappiness issue seems to have existed for a long time, it still uses a formula based on the BNW happiness system: unhappiness level = (population - local happiness)/population.

The counterspy calculation is correct, Spy Resistance is not the same as ID/Kill Chance and it not influenced by which mission is selected.
Why should EspionageModifier be 25 for a Constabulary? It says "increase spy resistance by 50%".  The other modifier besides "IDModifier" in the xml file is "DeathModifier".

**Comment by russp77** [comment]
Thanks for getting back to me. 

About the counterspy calculation I was getting confused between the id/kill chance and spy resistance (even though I've read the civilopedia many times). 

About the EspionageModifier, I was troubleshooting comparing the Public Works in the NewProjects.xml file with the constabulary in the BuildingChanges.sql file. I tried changing the name of the variable, different numbers, and changing the minus to a plus. Nothing worked. I suggested 25 because I think that's what the value used to be and, if both the constabulary and police station are 50, it will be hard for any foreign spy to succeed. 

Also thanks for clearing up my confusion about the unhappiness level.

**Comment by russp77** [comment]
I have a few minutes so I thought I would leave this thought. It seems that the buildings only affect the City Security Level (CSL). Maybe the calculation for determining whether a foreign spy succeeds doesn't give much weight to CSL, for example the difference between a 5 and 50 only increases the chance of stopping the foreign spy by 1% or 2% (I don't know the actual formula). In my game I was able to stop foreign spies when I put level 3 spies on the 50% counterespionage mission. If true, maybe the problem is just that the EspionageModifier and GlobalEspionageModifier(?) don't show up in the Espionage Overview.

Thanks for looking into this.

**Comment by axatin** [comment]
The formula is as follows: There's a mission-specific kill chance, plus the additional chance from counterspies, and an additional chance if a high-level counterspy is used. The sum of these these is multiplied with the percentage of city security (so, between 10% and 100%).

The bugs with constabularies and with the incorrect calculation of happiness have been fixed. Also, counterspies now give +50% spy resistance per level (instead of +25%). It should now be better possible to catch enemy spies.

**Comment by russp77** [comment]
Great. Thanks.
